### ISSUE TITLE
path_provider: ^2.1.2 , NOt working in Apple M1 Max Mac(Sonoma :14.2.1 (23C71))

### ISSUE THREAD

**Issue by linslouis** [flutter/flutter#143695]
### Steps to reproduce

1)Create new Flutter project with  macos option included 
2)add path_provider: ^2.1.2 to dependency 
3)run flutter pub get
4)Select MacOs(desktop) to run app
5)Run app

### Expected results

Expected to run without any errors

### Actual results

Crash while running in macOs Desktop

### Code sample

<details open><summary>Code sample</summary>

```dart
[name: test_provider
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true]
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[[   +3 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +8 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.2.1
[        ] executing: sw_vers -buildVersion
[   +8 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23C71
[        ] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] arm64
[   +2 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +38 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +110 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 15.2
           Build version 15C500b
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 5
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] Skipping pub get: version match.
[  +35 ms] Found plugin path_provider at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider-2.1.2/
[   +2 ms] Found plugin path_provider_android at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_android-2.2.2/
[   +1 ms] Found plugin path_provider_foundation at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.2/
[   +1 ms] Found plugin path_provider_linux at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +2 ms] Found plugin path_provider_windows at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[  +27 ms] Found plugin path_provider at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider-2.1.2/
[        ] Found plugin path_provider_android at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_android-2.2.2/
[        ] Found plugin path_provider_foundation at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.2/
[        ] Found plugin path_provider_linux at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +1 ms] Found plugin path_provider_windows at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":22110}}]
[ +513 ms] executing: /usr/bin/plutil -convert xml1 -o - /Applications/Android Studio.app/Contents/Info.plist
[   +6 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>English</string>
           	<key>CFBundleDocumentTypes</key>
           	<array>
           		<dict>
           			<key>CFBundleTypeExtensions</key>
           			<array>
           				<string>ipr</string>
           			</array>
           			<key>CFBundleTypeIconFile</key>
           			<string>studio.icns</string>
           			<key>CFBundleTypeName</key>
           			<string>Android Studio Project File</string>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           		</dict>
           		<dict>
           			<key>CFBundleTypeExtensions</key>
           			<array>
           				<string>*</string>
           			</array>
           			<key>CFBundleTypeName</key>
           			<string>All documents</string>
           			<key>CFBundleTypeOSTypes</key>
           			<array>
           				<string>****</string>
           			</array>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           			<key>LSTypeIsPackage</key>
           			<false/>
           		</dict>
           	</array>
           	<key>CFBundleExecutable</key>
           	<string>studio</string>
           	<key>CFBundleGetInfoString</key>
           	<string>Android Studio 2023.1, build AI-231.9392.1.2311.11330709. Copyright JetBrains s.r.o., (c) 2000-2023</string>
           	<key>CFBundleIconFile</key>
           	<string>studio.icns</string>
           	<key>CFBundleIdentifier</key>
           	<string>com.google.android.studio</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>Android Studio</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>2023.1</string>
           	<key>CFBundleSignature</key>
           	<string>????</string>
           	<key>CFBundleURLTypes</key>
           	<array>
           		<dict>
           			<key>CFBundleTypeRole</key>
           			<string>Editor</string>
           			<key>CFBundleURLName</key>
           			<string>Stacktrace</string>
           			<key>CFBundleURLSchemes</key>
           			<array>
           				<string>idea</string>
           			</array>
           		</dict>
           	</array>
           	<key>CFBundleVersion</key>
           	<string>AI-231.9392.1.2311.11330709</string>
           	<key>JVMOptions</key>
           	<dict>
           		<key>ClassPath</key>
           		<string>$APP_PACKAGE/Contents/lib/app.jar:$APP_PACKAGE/Contents/lib/3rd-party-rt.jar:$APP_PACKAGE/Contents/lib/util.jar:$APP_PACKAGE/Contents/lib/util_rt.jar:$APP_PACKAGE/Contents/lib/util-8.jar:$APP_PACKAGE/Contents/lib/jps-model.jar:$APP_PACKAGE/Contents/lib/stats.jar:$APP_PACKAGE/Contents/lib/protobuf.jar:$APP_PACKAGE/Contents/lib/external-system-rt.jar:$APP_PACKAGE/Contents/lib/intellij-test-discovery.jar:$APP_PACKAGE/Contents/lib/forms_rt.jar:$APP_PACKAGE/Contents/lib/rd.jar:$APP_PACKAGE/Contents/lib/externalProcess-rt.jar:$APP_PACKAGE/Contents/lib/3rd-party-native.jar:$APP_PACKAGE/Contents/lib/annotations-java5.jar:$APP_PACKAGE/Contents/lib/annotations.jar:$APP_PACKAGE/Contents/lib/byte-buddy-agent.jar:$APP_PACKAGE/Contents/lib/error-prone-annotations.jar:$APP_PACKAGE/Contents/lib/groovy.jar:$APP_PACKAGE/Contents/lib/idea_rt.jar:$APP_PACKAGE/Contents/lib/intellij-coverage-agent-1.0.706.jar:$APP_PACKAGE/Contents/lib/junit.jar:$APP_PACKAGE/Contents/lib/junit4.jar:$APP_PACKAGE/Contents/lib/resources.jar:$APP_PACKAGE/Contents/lib/ant/lib/ant.jar</string>
           		<key>ErrorFile</key>
           		<string>-XX:ErrorFile=$USER_HOME/java_error_in_studio_%p.log</string>
           		<key>HeapDump</key>
           		<string>-XX:HeapDumpPath=$USER_HOME/java_error_in_studio.hprof</string>
           		<key>JVMVersion</key>
           		<string>1.8*,1.8+</string>
           		<key>MainClass</key>
           		<string>com/intellij/idea/Main</string>
           		<key>Options</key>
           		<array>
           			<string>-XX:FlightRecorderOptions=stackdepth=256</string>
           			<string>--add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.io=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.lang=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.lang.ref=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.lang.reflect=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.net=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.nio=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.nio.charset=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.text=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.time=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.util=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.util.concurrent=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/sun.nio.ch=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/sun.nio.fs=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/sun.security.ssl=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/sun.security.util=ALL-UNNAMED</string>
           			<string>--add-opens=java.base/sun.net.dns=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/com.apple.eawt=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/com.apple.eawt.event=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/com.apple.laf=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt.dnd.peer=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt.event=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt.image=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/java.awt.font=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/javax.swing=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.awt.image=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.awt=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.font=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.java2d=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED</string>
           			<string>--add-opens=java.desktop/sun.swing=ALL-UNNAMED</string>
           			<string>--add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED</string>
           			<string>--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</string>
           			<string>--add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED</string>
           			<string>--add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED</string>
           		</array>
           		<key>Properties</key>
           		<dict>
           			<key>idea.executable</key>
           			<string>studio</string>
           			<key>idea.home.path</key>
           			<string>$APP_PACKAGE/Contents</string>
           			<key>idea.paths.selector</key>
           			<string>AndroidStudio2023.1</string>
           			<key>idea.platform.prefix</key>
           			<string>AndroidStudio</string>
           			<key>idea.vendor.name</key>
           			<string>Google</string>
           			<key>java.system.class.loader</key>
           			<string>com.intellij.util.lang.PathClassLoader</string>
           			<key>jna.boot.library.path</key>
           			<string>$APP_PACKAGE/Contents/lib/jna/aarch64</string>
           			<key>jna.noclasspath</key>
           			<string>true</string>
           			<key>jna.nosys</key>
           			<string>true</string>
           			<key>pty4j.preferred.native.folder</key>
           			<string>$APP_PACKAGE/Contents/lib/pty4j</string>
           			<key>splash</key>
           			<string>true</string>
           		</dict>
           	</dict>
           	<key>LSApplicationCategoryType</key>
           	<string>public.app-category.developer-tools</string>
           	<key>LSArchitecturePriority</key>
           	<array>
           		<string>arm64</string>
           		<string>x86_64</string>
           	</array>
           	<key>LSMinimumSystemVersion</key>
           	<string>10.8</string>
           	<key>LSRequiresNativeExecution</key>
           	<string>YES</string>
           	<key>NSAppleEventsUsageDescription</key>
           	<string>An application in Android Studio requests the ability to send Apple events.</string>
           	<key>NSBluetoothAlwaysUsageDescription</key>
           	<string>An application in Android Studio requests access to Bluetooth.</string>
           	<key>NSCameraUsageDescription</key>
           	<string>An application in Android Studio requests access to the device's camera.</string>
           	<key>NSDesktopFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the user's Desktop folder.</string>
           	<key>NSDocumentsFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the user's Documents folder.</string>
           	<key>NSDownloadsFolderUsageDescription</key>
           	<string>An application in Android Studio requests access to the user's Downloads folder.</string>
           	<key>NSHighResolutionCapable</key>
           	<true/>
           	<key>NSLocationUsageDescription</key>
           	<string>An application in Android Studio requests access to the user's location information.</string>
           	<key>NSMicrophoneUsageDescription</key>
           	<string>An application in Android Studio requests access to the device's microphone.</string>
           	<key>NSNetworkVolumesUsageDescription</key>
           	<string>An application in Android Studio requests access to files on a network volume.</string>
           	<key>NSRemovableVolumesUsageDescription</key>
           	<string>An application in Android Studio requests access to files on a removable volume.</string>
           	<key>NSSupportsAutomaticGraphicsSwitching</key>
           	<true/>
           </dict>
           </plist>
[  +32 ms] executing: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java -version
[  +41 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java -version
[        ] openjdk version "17.0.7" 2023-04-18
           OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
           OpenJDK 64-Bit Server VM (build 17.0.7+0-17.0.7b1000.6-10550314, mixed mode)
[{"event":"app.start","params":{"appId":"7daf475e-636a-4fbb-ade8-e2046a805416","deviceId":"macos","directory":"/Users/linslouis/AndroidStudioProjects/providerbug","supportsRestart":true,"launchMode":"run","mode":"debug"}}]
[  +22 ms] Initializing file store
[   +3 ms] Skipping target: gen_localizations
[   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/linslouis/AndroidStudioProjects/providerbug/.dart_tool/package_config_subset}
[   +9 ms] Found plugin path_provider at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider-2.1.2/
[        ] Found plugin path_provider_android at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_android-2.2.2/
[        ] Found plugin path_provider_foundation at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.2/
[   +1 ms] Found plugin path_provider_linux at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +1 ms] Found plugin path_provider_windows at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[  +18 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[        ] complete
[   +2 ms] Launching lib/main.dart on macOS in debug mode...
[   +1 ms] /Users/linslouis/Developer/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/linslouis/Developer/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /Users/linslouis/Developer/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/ --output-dill /var/folders/fs/c79w5d5j4gz7m_5121qx6h6c0000gn/T/flutter_tools.ey9dGv/flutter_tool.NrBpEg/app.dill --packages /Users/linslouis/AndroidStudioProjects/providerbug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/a7129f421dce2c4643c9718d38694ba9.cache.dill.track.dill --source file:///Users/linslouis/AndroidStudioProjects/providerbug/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///Users/linslouis/AndroidStudioProjects/providerbug/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error --enable-experiment=alternative-invalidation-strategy
[   +9 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/linslouis/AndroidStudioProjects/providerbug/macos/Runner/Info.plist
[   +6 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/linslouis/AndroidStudioProjects/providerbug/macos/Runner/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>$(DEVELOPMENT_LANGUAGE)</string>
           	<key>CFBundleExecutable</key>
           	<string>$(EXECUTABLE_NAME)</string>
           	<key>CFBundleIconFile</key>
           	<string></string>
           	<key>CFBundleIdentifier</key>
           	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>$(PRODUCT_NAME)</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>$(FLUTTER_BUILD_NAME)</string>
           	<key>CFBundleVersion</key>
           	<string>$(FLUTTER_BUILD_NUMBER)</string>
           	<key>LSMinimumSystemVersion</key>
           	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>
           	<key>NSHumanReadableCopyright</key>
           	<string>$(PRODUCT_COPYRIGHT)</string>
           	<key>NSMainNibFile</key>
           	<string>MainMenu</string>
           	<key>NSPrincipalClass</key>
           	<string>NSApplication</string>
           </dict>
           </plist>
[  +15 ms] <- compile package:test_provider/main.dart
[  +23 ms] Found plugin path_provider at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider-2.1.2/
[        ] Found plugin path_provider_android at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_android-2.2.2/
[   +1 ms] Found plugin path_provider_foundation at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.2/
[        ] Found plugin path_provider_linux at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +1 ms] Found plugin path_provider_windows at /Users/linslouis/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[  +10 ms] executing: which pod
[   +9 ms] executing: pod --version
[ +400 ms] 1.15.2

               WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
               Consider adding the following to ~/.profile:

               export LANG=en_US.UTF-8
               
Running pod install...
[{"event":"app.progress","params":{"appId":"7daf475e-636a-4fbb-ade8-e2046a805416","id":"0","progressId":null,"message":"Running pod install...","finished":false}}]
[{"event":"app.progress","params":{"appId":"7daf475e-636a-4fbb-ade8-e2046a805416","id":"0","progressId":null,"finished":true}}]
[ +545 ms] CocoaPods' output:
           ↳
[        ]       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

[        ] Error output from CocoaPods:
           ↳
[        ]         WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
                   Consider adding the following to ~/.profile:

                   export LANG=en_US.UTF-8
                   
               /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
               	from /usr/local/bin/pod:23:in `load'
               	from /usr/local/bin/pod:23:in `<main>'
               /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
               	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
               	from /usr/local/bin/pod:23:in `load'
               	from /usr/local/bin/pod:23:in `<main>'

[ +935 ms] Exception: Error running pod install
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:705:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[{"event":"app.stop","params":{"appId":"7daf475e-636a-4fbb-ade8-e2046a805416"}}]
[   +5 ms] "flutter run" took 2,883ms.
[{"id":0,"error":"app '7daf475e-636a-4fbb-ade8-e2046a805416' not found","trace":"#0      AppDomain.stop (package:flutter_tools/src/commands/daemon.dart:778:7)\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:276:35)\n#2      new Future.sync (dart:async/future.dart:305:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:274:5)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:226:27)\n#5      _rootRunUnary (dart:async/zone.dart:1407:47)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#9      _DelayedData.perform (dart:async/stream_impl.dart:515:14)\n#10     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)\n#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)\n#12     _rootRun (dart:async/zone.dart:1391:47)\n#13     _CustomZone.run (dart:async/zone.dart:1301:19)\n#14     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)\n#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)\n#16     _rootRun (dart:async/zone.dart:1399:13)\n#17     _CustomZone.run (dart:async/zone.dart:1301:19)\n#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)\n#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)\n#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)\n#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)\n#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)\n#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)\n"}]
[  +60 ms] ensureAnalyticsSent: 59ms
[        ] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
    • Flutter version 3.16.7 on channel stable at /Users/linslouis/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (6 weeks ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/linslouis/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/linslouis/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @linslouis, the error you're getting is from cocoapods. Can you try this stackoverflow answer to see if it resolves your issue? https://stackoverflow.com/a/69395720

**Comment by linslouis** [comment]
Yes you are right. Stackoverflow solution worked. Thanks
