### ISSUE TITLE
My App crashed with red screen after set localizations

### ISSUE THREAD

**Issue by emptyfist** [flutter/flutter#143700]
### Steps to reproduce

Hello, everone!

Well, I wanna renovate existing app for Localizations.
So I followed steps from here. 
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

When I run command `fvm flutter run`, app crashed with red screen which tells `Unsupported operation: Cannot modify unmodifiable map xxxx`.

But after remove localization setting sentences(you can find out from below) from `MyMaterialApp.router()`, app works well.

What's the problem?
And How I can fix this?

Flutter Version: 3.7.1

### Expected results

I wanna see app screen but failed.
If i remove below three sentences from `MaterialApp.router()`, app runs well.

```
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          locale: const Locale("ja"),
```

### Actual results

![image](https://github.com/flutter/flutter/assets/90226717/8fdb4edf-1c00-40e4-955e-97fdcfbfef38)

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyApp extends StatefulHookConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends ConsumerState<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      if (!isFirebaseAuth()) return;
      isReadLatestAnnouncement(context, ref);
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    if (isFirebaseAuth() && state == AppLifecycleState.resumed) {
      isReadLatestAnnouncement(context, ref);
    }
  }

  @override
  Widget build(BuildContext context) {
    _configureFirebaseMessaging();

    return Sizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp.router(
          routerConfig: router,
          debugShowCheckedModeBanner: false,

          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
          locale: const Locale("ja"),
        );
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/90226717/66343f37-3129-47e0-a707-7ee2a2999917)

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(411.4,
890.3), devicePixelRatio: 2.6, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
EdgeInsets(0.0, 51.8, 0.0, 0.0), viewPadding: EdgeInsets(0.0, 51.8, 0.0, 0.0), viewInsets:
EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false,
disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional,
gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: [DisplayFeature(rect:
Rect.fromLTRB(182.9, 0.0, 238.1, 51.8), type: DisplayFeatureType.cutout, state:
DisplayFeatureState.unknown)])):
Unsupported operation: Cannot modify unmodifiable map

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///xxxxx/lib/main.dart:181:12

When the exception was thrown, this was the stack:
#0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
#1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
#2      loadDateIntlDataIfNotLoaded.<anonymous closure>
(package:flutter_localizations/src/utils/date_localizations.dart:23:33)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#4      loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/utils/date_localizations.dart:20:8)
#5      _MaterialLocalizationsDelegate.load.<anonymous closure>
(package:flutter_localizations/src/material_localizations.dart:729:12)
#6      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#7      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:728:32)
#8      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
#9      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:558:62)
#10     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:520:5)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (256 frames)
#268    _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (23 frames)
#291    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#292    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#293    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#294    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#295    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1092:18)
#296    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#297    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#298    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#299    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#303    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
W/System  (26783): Ignoring header X-Firebase-Locale because its value was null.
E/chromium(26783): [ERROR:aw_browser_terminator.cc(154)] Renderer process (26875) crash detected (code -1).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hello @emptyfist.
Thanks for filing this. 
Following the steps in https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization on a newly created Flutter project, I can't seem to reproduce this issue.
I see you are on an older version of Flutter, can you try this on a new Flutter project and on the latest version `3.19.0`.

**Comment by sudhar08** [comment]
I think you should remove the **const** keyword from the line above you mentioned

**Comment by dam-ease** [comment]
Hello @emptyfist 
Thanks for your response.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code that is a single `main.dart` that we could check to reproduce your issue?

Also, your question seems to be best suited for support channels like StackOverflow, please ask the same there for solutions if any. You can also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask more questions like this.

**Comment by emptyfist** [comment]
@dam-ease 
Thank you.
I've solved this problem. The reason is that some weird problem occurred while use flutter localizations and `initializeDateFormatting` feature.

https://zenn.dev/link/comments/2d4946487b3a86

Above is the article about this issue.
