### ISSUE TITLE
ModalRoute.of(context) + DropdownButton = Rebuild in every interaction with DropdownButton

### ISSUE THREAD

**Issue by EduardoDadalt** [flutter/flutter#143709]
### Steps to reproduce

1. Create a page with ModalRoute.of(context) in build method. 
2. Place a DropdownButton with itens. 
3. Click in DropdownButton and see entire page rebuild

### Expected results

DropdownButton not update ModalRoute

### Actual results

DropdownButton makes ModalRoute update depedencies 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  @override
  Widget build(BuildContext context) {
    final route = ModalRoute.of(context);
    _counter++;
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text("$_counter"),
            DropdownButton(
              items: const [
                DropdownMenuItem(
                  child: Text("1"),
                ),
              ],
              onChanged: (value) {},
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/99298569/2abd520f-2607-433a-ba60-53e6c55f6f09

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22631.3155], locale pt-BR)
    • Flutter version 3.19.0 on channel stable at C:\devDeps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (6 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\EduardoDadalt\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\EduardoDadalt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by moffatman** [comment]
Hi, what's the use of `ModalRoute.of(context)`? Because it is correct here, the top-level `ModalRoute` has changed.

**Comment by EduardoDadalt** [comment]
I used for get arguments of route like this cookbook: [https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments)

**Comment by android71Francis** [comment]
We encountered the same problem on this do we have any workaround for this?

**Comment by danagbemava-nc** [comment]
Hi @EduardoDadalt, since you're using a `StatefulWidget`, can you try accessing the `ModalRoute` in `didUpdateWidget` to see if it helps?

**Comment by EduardoDadalt** [comment]
Using `didUpdateWidget` not works because its not run in first build. Its works using method `didChangeDependencies`. Maybe a put a warning in this [cookbook](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments) or update this documentation using  `didChangeDependencies`?

**Comment by danagbemava-nc** [comment]
Hi @EduardoDadalt, what do you propose we add to the documentation of `didChangeDependencies`? And what warning would you suggest be added to the cookbook?

**Comment by danagbemava-nc** [comment]
> This change in ModalRoute could be breaking change?

Did this work for you as expected prior to upgrading to `3.19.0`?

> What I wanted to say in this last comment is that perhaps it would be good to include a message or warning in this [documentation](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments) about this potential problem that one might encounter. Alternatively, the [documentation](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments) could be modified to recommend using didChangeDependencies when only pulling the route argument.

Pardon me, in my previous post I wanted to know what was your recommendation for updating the documentation so that it would be easier for others to understand

**Comment by EduardoDadalt** [comment]
> Did this work for you as expected prior to upgrading to 3.19.0?

Yes 

> Pardon me, in my previous post I wanted to know what was your recommendation for updating the documentation so that it would be easier for others to understand

Sorry, i'm wrong. I thought using `didChangeDependencies` the widget not update with ModalRoute.of(context). But I tested the in version 3.16. The error happens in 3.19

> Hi @EduardoDadalt, since you're using a StatefulWidget, can you try accessing the ModalRoute in didUpdateWidget to see if it helps?

I test again in 3.19 version with `didUpdateWidget ` and not works because he not runs in initialization of the widget.

https://github.com/flutter/flutter/assets/99298569/d5a2ab65-ee46-402a-b8b2-1d6c2bc4d6f1

 And `didChangeDependencies` not work too. 

https://github.com/flutter/flutter/assets/99298569/e2c6ed60-1aca-45e6-8578-72f25beb7efc

**Comment by danagbemava-nc** [comment]
Thanks for the update. I get the "expected" behavior on stable `3.16.0` but not on the latest version of stable or master. 

Labeling for further investigation. This could either be a regression or an intentional change in behaviour but I can't say that for sure at this time. 

| master & stable 3.19.1 | stable 3.16.0 | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/c1926148-9882-44ee-9c9a-d1080e1362de" /> | <video src="https://github.com/flutter/flutter/assets/88313112/4f60105b-1c35-4764-a773-f22decff8529" /> |


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel [user-branch], 3.16.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    ! Flutter version 3.16.0 on channel [user-branch] at /Users/nexus/dev/sdks/flutter_rc/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter_rc/flutter. Consider adding /Users/nexus/dev/sdks/flutter_rc/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter_rc/flutter. Consider adding /Users/nexus/dev/sdks/flutter_rc/flutter/bin to the front of your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision db7ef5bf9f (3 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

```
[!] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.1 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (5 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.20.0-13.0.pre.31, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.20.0-13.0.pre.31 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8503febb1 (3 hours ago), 2024-02-25 23:42:25 -0500
    • Engine revision fd3136782a
    • Dart version 3.4.0 (build 3.4.0-175.0.dev)
    • DevTools version 2.33.0-dev.11

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)                • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by aytunch** [comment]
We are getting the same problem of not being able to get `ModalRoute.of(context)?.settings.arguments` after upgrading the app to 3.19
This worked perfectly in 3.16
Now we get `null` after a new page is being pushed from `didChangeDependencies`.

**Comment by bysano** [comment]
Having the same issue with new release , previously everything worked fine

**Comment by ioma8** [comment]
Hi how is it looking with this issue? Its kinda critical bug as ModalRoute.of(context)?.settings.arguments is widely used.

**Comment by goderbauer** [comment]
My guess is that this probably changed with the fix in https://github.com/flutter/flutter/pull/130841 (cc @chunhtai)

Overall, my impression is that the current behavior is correct, though. ModalRoute notifies its dependents whenever it changes - and ModalRoute.isCurrent changes whenever you open/close a drop down menu.

In general, that a Widget's `build` method is not called on every frame is a performance optimization that is not guaranteed. The additional rebuilds you're seeing shouldn't be causing any issues. If they are a performance concern you can read some advice on how to mitigate that in the "performance consideration" section in the StatefulWidget doc: https://main-api.flutter.dev/flutter/widgets/StatefulWidget-class.html

**Comment by Coin-ai** [comment]
How about using StatelessWidget?

The documentation suggests that we subscribe to a change event, although such a subscription doesn't seem to provide any benefit: https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments

This would suggest changing the nature of the discussion to for a new feature that allows fetching ModalRoute.of(context)!.settings.arguments without the need to listen or subscribe?

This approach could also solve the issue discussed here: https://github.com/flutter/flutter/issues/133833#issuecomment-1872283973

This issue Navigator ModalRoute.of(context) rebuild
<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(final BuildContext _) {
    return MaterialApp(
      initialRoute: '/page1',
      routes: <String, WidgetBuilder>{
        '/page1': (final BuildContext context) => const Page1(),
        '/page2': (final BuildContext context) => const Page2(),
      },
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({super.key});

  @override
  Widget build(final BuildContext context) {
    print('Rebuild Page 1');
    // final Object? args = ModalRoute.of(context)?.settings.arguments;
    final ModalRoute<dynamic>? modalRoute = ModalRoute.of(context);
    final Object? args = modalRoute?.settings.arguments;
    print('isActive: ${modalRoute?.isActive}');
    print('isCurrent: ${modalRoute?.isCurrent}');
    print('canPop: ${modalRoute?.canPop}');
    print('impliesAppBarDismissal:${modalRoute?.impliesAppBarDismissal}');
		print('args :${args}');
    // print(modalRoute?.route);
    return Scaffold(
      appBar: AppBar(title: const Text('Page 1')),
      body: Center(
        child: OutlinedButton(
          child: const Text('Go to Page 2'),
          onPressed: () async => Navigator.pushNamed(context, '/page2'),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({super.key});

  @override
  Widget build(final BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Page 2')),
      body: Center(
        child: OutlinedButton(
          child: const Text('Go to Page 1'),
          onPressed: () async => Navigator.of(context).pushNamed('/page1'),
        ),
      ),
    );
  }
}

```

</details>

<details><summary>Logs</summary>

```console
I/flutter ( 9907): Rebuild Page 1
I/flutter ( 9907): isActive: true
I/flutter ( 9907): isCurrent: true
I/flutter ( 9907): canPop: false
I/flutter ( 9907): impliesAppBarDismissal:false
I/flutter ( 9907): args :null
I/flutter ( 9907): Rebuild Page 1
I/flutter ( 9907): isActive: true
I/flutter ( 9907): isCurrent: false
I/flutter ( 9907): canPop: false
I/flutter ( 9907): impliesAppBarDismissal:false
I/flutter ( 9907): args :null
```

</details>

**Comment by EduardoDadalt** [comment]
If I just want to get the arguments, how do I do it? 
@goderbauer How make this works with StatefulWidget?

If i call ModalRoute.of(context) in initState, give a error because of dependency: 

<details open><summary>Error</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder:
dependOnInheritedWidgetOfExactType<_ModalScopeStatus>() or dependOnInheritedElement() was called
before _SecondPageState.initState() completed.
When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
inherited widget.
Typically references to inherited widgets should occur in widget build() methods. Alternatively,
initialization based on inherited widgets can be placed in the didChangeDependencies method, which
is called after initState and whenever the dependencies change thereafter.

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///C:/src/bug/lib/main.dart:12:12

When the exception was thrown, this was the stack:
#0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:5713:9)
#1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:5756:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4774:14)
#3      ModalRoute.of (package:flutter/src/widgets/routes.dart:1046:47)
#4      _SecondPageState.initState (package:bug/main.dart:59:23)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5611:55)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
...     Normal element mounting (220 frames)
#226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#227    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#228    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#229    Element.updateChildren (package:flutter/src/widgets/framework.dart:4033:32)
#230    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#233    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#239    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#243    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#244    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#247    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#249    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#253    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#254    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#257    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#258    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#259    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#262    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#264    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#266    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#268    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#269    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#270    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#271    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#272    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#274    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#276    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#277    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#279    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#280    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#281    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#282    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#283    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#284    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#285    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#286    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#287    _invoke (dart:ui/hooks.dart:312:13)
#288    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#289    _drawFrame (dart:ui/hooks.dart:283:31)

```

</details>
If i use `didChangeDependencies`, the page rebuild every time. 
I think the best solution is this PR #145389
