### ISSUE TITLE
Cannot pick image on iOS

### ISSUE THREAD

**Issue by g-apparence** [flutter/flutter#143832]
### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

Works on IphoneX with iOS 16.7.4
Fails on Iphone 15 pro with iOS 17.2.1

### Steps to reproduce

Call imagepicker pick image on Iphone 15 pro with iOS 17.2.1 

### Expected results

You should have the image file

### Actual results

Throws 

```bash
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_image, Impossible de charger la représentation de type public.jpeg, NSItemProviderErrorDomain, null)
#0      ImagePickerApi.pickImage (package:image_picker_ios/src/messages.g.dart:183:7)
<asynchronous suspension>
#1      ImagePickerIOS.getImageFromSource (package:image_picker_ios/image_picker_ios.dart:78:26)
<asynchronous suspension>
#2      _EditableUserAvatarState.onTapAvatar.<anonymous closure> (package:apparence_kit/modules/settings/ui/components/avatar_component.dart:109:15)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>

```dart
 final picker = ImagePicker();
    final file = await picker.pickImage(
      source: ImageSource.gallery,
    );
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on macOS 13.5.1 22G90 darwin-arm64, locale fr-FR)
    • Flutter version 3.19.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.16.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (7 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mcfly/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mcfly/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone de Ga (mobile) • 00008130-0006089126F0001C • ios            • iOS 17.2.1 21C66
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 122.0.6261.57

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hello @g-apparence.
Thanks for filing this!
Testing with the code sample in https://pub.dev/packages/image_picker/example, I can't seem to reproduce this on iOS 17.2 and iOS 17.1.1 both on Simulator and real device.
There is a similar issue https://github.com/flutter/flutter/issues/129522 and one related on in https://developer.apple.com/forums/thread/665265 but this shows it might be specific to only simulators, does this error occur on a simulator or a real device on your end?
If simulator, can you check this out on a real device as well with the sample code https://pub.dev/packages/image_picker/example to see if it still reproduces on your end?

**Comment by g-apparence** [comment]
@dam-ease thank you for answering
I tested this on real device. 
Also tried on a built ipa version and that also occurs. 

As I said I tried it IphoneX and it worked. 
It only occurs on Iphone 15 pro. (Real device)
