### ISSUE TITLE
Reland: Make impeller goldens test blocking

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143898]
https://github.com/flutter/flutter/pull/143864 was reverted (turned the tree red).

[Example failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755443299639610049/+/u/run_test.dart_for_framework_tests_shard_and_subshard_impeller/stdout):

```txt
00:38 +465 ~10: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/painting/box_painter_test.dart: BoxShadow BoxStyle.solid.wide_radius                                                            
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SkiaException was thrown while running async test code:
Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org// to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 6d33baa2ced38febfa614499adea0136 for test
painting.boxShadow.boxStyle.solid.wide_radius.0.0
Expectation for test: 793acced49364538a38c1244f2a3c8d3 (positive)
Expectation for test: a48953315ddc00ff44321e46fca2216f (positive)
Expectation for test: b20ade7d67ae66b3f15fbe07d6d1f0d1 (positive)
Expectation for test: ca2290d951c177b6016d4b299dff3e86 (positive)
Expectation for test: f5c2055b190cc92470dd39e3d3ee9790 (positive)
Expectation for test: 0c6e37ffe3b8780a32c2e148f136e025 (positive)
Expectation for test: 22a1b9739a0e965e2868881be1d7ec18 (positive)
Expectation for test: 35e24b2321cd6f2607e505d0ff3500aa (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dpainting.boxShadow.boxStyle.solid.wide_radius.0.0%26source_type%3Dflutter&digest=6d33baa2ced38febfa614499adea0136


stderr: Test: painting.boxShadow.boxStyle.solid.wide_radius.0.0 FAIL


result-state.json: No result file found.

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens/skia_client.dart:252:7)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
#3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
<asynchronous suspension>
<asynchronous suspension>
#5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/painting/box_painter_test.dart:382:5)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1019:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════

00:38 +465 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/painting/box_painter_test.dart: BoxShadow BoxStyle.solid.wide_radius [E]                                                     
  Test failed. See exception logs above.
  The test description was: BoxShadow BoxStyle.solid.wide_radius
  

00:38 +466 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
To run this test again: /Volumes/Work/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/painting/box_painter_test.dart -p vm --plain-name 'BoxShadow BoxStyle.solid.wide_radius'

00:38 +467 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +468 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +469 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +470 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +471 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +472 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
00:38 +473 ~10 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/animation/live_binding_test.dart: Should show event indicator for pointer events with setSurfaceSize                         
unhandled error during finalization of test:
/Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/painting/box_painter_test.dart
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:248:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:230:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:525:9)
<asynchronous suspension>
#3      FlutterPlatform._sta
```

There are a number of failures/segfaults above, not sure if related or not.

**Comment by jonahwilliams** [comment]
This relanded!
