### ISSUE TITLE
Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan). Found stages: SkSL OpenGLES

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#143806]
### Steps to reproduce

Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES

### Expected results

Work perfectly

### Actual results

Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES

### Code sample

<details open><summary>Code sample</summary>

```dart
Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES
```

</details>

**Comment by jonahwilliams** [comment]
You seem to be missing any flutter doctor output?

**Comment by nomoruyi** [comment]
I have same error message with the following problem:

If I install an app via debug mode on any device (emulator with any SDK or any real android device), it works as it should. As soon as I hit hot reload/restart or simply start the installed application, the code executes to a certain point and then just stops. No errors, no warnings, nothing. Debug console last messages are:

```

D/HostConnection( 7088): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
D/HostConnection( 7088): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
D/HostConnection( 7088): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 
W/Parcel  ( 7088): Expecting binder but got null!
D/HostConnection( 7088): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_1 

```
I added a button to my "base" screen, the only screen that renders, and when I click it, it shows the aforementioned Exception about shaders.


Here is my 'flutter doctor -v' output:

```
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.22621.3155], locale de-DE)
    • Flutter version 3.19.0 on channel stable at C:\Users\Nosa\.version-fox\cache\flutter\v-3.19.0\flutter-3.19.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (8 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Nosa\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\Nosa\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Opera GX\opera.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33801.468
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Users\Nosa\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Users\Nosa\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 78.1.1
    • Dart plugin version 233.13763.5

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\Nosa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    • Chrome (web)               • chrome        • web-javascript • unknown
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by jonahwilliams** [comment]
So this doesn't happen at startup, but does happen after a hot reload (or hot restart?). And you're using Impeller?

**Comment by nomoruyi** [comment]
@jonahwilliams it happens when i start the app normally too (clicking the app icon)

**Comment by nomoruyi** [comment]
For some reason, now i get the folling message over and over after the first initialization:

`E/libEGL  ( 6143): called unimplemented OpenGL ES API
`

I actually didnt change anything, I just used a different emulator (API 26)

**Comment by nomoruyi** [comment]
> So this doesn't happen at startup, but does happen after a hot reload (or hot restart?). And you're using Impeller?

Same behavior when not using

**Comment by danagbemava-nc** [comment]
Hi @nomoruyi, does this happen with the counter app? Are you seeing this on specific device or os versions?  If this does not reproduce with the counter app can you provide a minimal sample along with steps to reproduce the issue? 

Thank you

**Comment by richard457** [comment]
> You seem to be missing any flutter doctor output?

This error happened on production and yes I was using impeller

**Comment by danagbemava-nc** [comment]
Hi @richard457, please provide the flutter doctor output of the flutter version that was used to deploy the application. 

Are you able to replicate this locally?

**Comment by Vedsaga** [comment]
```
[!] Flutter (Channel beta, 3.20.0-1.2.pre, on Microsoft Windows [Version 10.0.22621.3155], locale en-IN)
    • Flutter version 3.20.0-1.2.pre on channel beta at C:\Users\harsh\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\harsh\fvm\versions\3.20.0-1.2.pre\bin\flutter, which is not
      inside your current Flutter SDK checkout at C:\Users\harsh\fvm\default. Consider adding
      C:\Users\harsh\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\harsh\fvm\versions\3.20.0-1.2.pre\bin\dart, which is not inside
      your current Flutter SDK checkout at C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin
      to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1751123cde (3 days ago), 2024-02-21 22:06:22 -0800
    • Engine revision 299e852cb9
    • Dart version 3.4.0 (build 3.4.0-99.1.beta)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\harsh\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\harsh\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.86.2)
    • VS Code at C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • vivo 1907 (mobile) • 8TBYBE6H7H55USFE • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 121.0.6167.189
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 121.0.2277.128

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

And can confirm that just after updating to the `3.20` and it happening, it was not happening... 

Also, can confirm that it happen when app is running and when clicked on button...


![image](https://github.com/flutter/flutter/assets/59083528/42a7172d-ea2d-44ac-82f8-8f72c686ddd3)


```
  @patch
  @pragma("vm:external-name", "Error_throwWithStackTrace")
  external static Never _throw(Object error, StackTrace stackTrace);
}
```

```
Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
Found stages: SkSL OpenGLES 
```


it seems this is very serious issue...

btw while app was compiling in `Development mode`...  got the log...

```
Running Gradle task 'assembleDevelopmentDebug'...
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

Note: C:\Users\harsh\AppData\Local\Pub\Cache\hosted\pub.dev\geocoding_android-2.1.2\android\src\main\java\com\baseflow\geocoding\Geocoding.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the file specified.
```
![image](https://github.com/flutter/flutter/assets/59083528/2cc5a11c-e8d3-4b73-bebb-0edaeab1a2d6)

Earlier was on last stable prior to `3.19.x` 

Assuming this should not be issue ?

cc: @danagbemava-nc  @jonahwilliams

**Comment by Vedsaga** [comment]
btw this is stacktrace...

```
E/flutter (14849): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for current backend (Vulkan).
E/flutter (14849): Found stages: SkSL OpenGLES 
E/flutter (14849): #0      new FragmentProgram._fromAsset (dart:ui/painting.dart:4446:7)
E/flutter (14849): #1      FragmentProgram.fromAsset.<anonymous closure> (dart:ui/painting.dart:4473:55)
E/flutter (14849): #2      new Future.microtask.<anonymous closure> (dart:async/future.dart:280:37)
E/flutter (14849): #3      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14849): #4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (14849): 
```

**Comment by danagbemava-nc** [comment]
Hi @Vedsaga, can you provide a minimal sample? I tested a small app on the latest master channel but I can't reproduce the issue.

**Comment by Vedsaga** [comment]
> Hi @Vedsaga, can you provide a minimal sample? I tested a small app on the latest master channel but I can't reproduce the issue.

So if we follow this step

1. Download the `version 3.16.0`  
2. Create project based on  `version 3.16.0`  
3. Switch the version to `version 3.19.1` -- latest stable

and try to run the project will be not able to even the app...

```

/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:215:9: Error: Type 'ui.KeyEventDeviceType' not found.
  final ui.KeyEventDeviceType deviceType;
        ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1182:3: Error: Type 'ui.KeyEventDeviceType' not found.
  ui.KeyEventDeviceType _convertDeviceType(RawKeyEvent rawEvent) {
  ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/painting/text_painter.dart:1504:4: Error: Type 'ui.GlyphInfo' not found.
   ui.GlyphInfo? getClosestGlyphForOffset(Offset offset) {
   ^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:127:26: Error: Undefined name 'KeyEventDeviceType'.
    this.deviceType = ui.KeyEventDeviceType.keyboard,
                         ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/rendering/editable.dart:1951:11: Error: 'GlyphInfo' isn't a type.
    final GlyphInfo? glyph = _textPainter.getClosestGlyphForOffset(effectivePosition);
          ^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/rendering/paragraph.dart:736:11: Error: 'GlyphInfo' isn't a type.
    final GlyphInfo? glyph = _textPainter.getClosestGlyphForOffset(position);
          ^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:215:12: Error: 'KeyEventDeviceType' isn't a type.
  final ui.KeyEventDeviceType deviceType;
           ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1186:17: Error: Undefined name 'KeyEventDeviceType'.
      return ui.KeyEventDeviceType.keyboard;
                ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1192:19: Error: Undefined name 'KeyEventDeviceType'.
        return ui.KeyEventDeviceType.keyboard;
                  ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1195:19: Error: Undefined name 'KeyEventDeviceType'.
        return ui.KeyEventDeviceType.directionalPad;
                  ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1198:19: Error: Undefined name 'KeyEventDeviceType'.
        return ui.KeyEventDeviceType.gamepad;
                  ^^^^^^^^^^^^^^^^^^
                  
 /C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1201:19: Error: Undefined name 'KeyEventDeviceType'.
        return ui.KeyEventDeviceType.joystick;
                  ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1204:19: Error: Undefined name 'KeyEventDeviceType'.
        return ui.KeyEventDeviceType.hdmi;
                  ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1206:15: Error: Undefined name 'KeyEventDeviceType'.
    return ui.KeyEventDeviceType.keyboard;
              ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1223:14: Error: 'KeyEventDeviceType' isn't a type.
    final ui.KeyEventDeviceType deviceType = _convertDeviceType(rawEvent);
             ^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1324:31: Error: The getter 'deviceType' isn't defined for the class 'KeyData'.
 - 'KeyData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'deviceType'.
          deviceType: keyData.deviceType,
                              ^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1333:31: Error: The getter 'deviceType' isn't defined for the class 'KeyData'.
 - 'KeyData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'deviceType'.
          deviceType: keyData.deviceType,
                              ^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1341:31: Error: The getter 'deviceType' isn't defined for the class 'KeyData'.
 - 'KeyData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'deviceType'.
          deviceType: keyData.deviceType,
                              ^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1333:31: Error: The getter 'deviceType' isn't defined for the class 'KeyData'.
 - 'KeyData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'deviceType'.
          deviceType: keyData.deviceType,
                              ^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/services/hardware_keyboard.dart:1341:31: Error: The getter 'deviceType' isn't defined for the class 'KeyData'.
 - 'KeyData' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'deviceType'.
          deviceType: keyData.deviceType,
                              ^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/painting/text_painter.dart:1508:14: Error: 'GlyphInfo' isn't a type.
    final ui.GlyphInfo? rawGlyphInfo = cachedLayout.paragraph.getClosestGlyphInfoForOffset(offset - cachedLayout.paintOffset);
             ^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/painting/text_painter.dart:1512:15: Error: Method not found: 'GlyphInfo'.
    return ui.GlyphInfo(rawGlyphInfo.graphemeClusterLayoutBounds.shift(cachedLayout.paintOffset), rawGlyphInfo.graphemeClusterCodeUnitRange, rawGlyphInfo.writingDirection);
              ^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/painting/text_painter.dart:1508:63: Error: The method 'getClosestGlyphInfoForOffset' isn't defined for the class 'Paragraph'.
 - 'Paragraph' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'getClosestGlyphInfoForOffset'.
    final ui.GlyphInfo? rawGlyphInfo = cachedLayout.paragraph.getClosestGlyphInfoForOffset(offset - cachedLayout.paintOffset);
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/harsh/fvm/default/packages/flutter/lib/src/semantics/semantics.dart:2787:7: Error: No named parameter with the name 'identifier'.
      identifier: data.identifier,
      ^^^^^^^^^^
arget kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\harsh\fvm\versions\3.16.0\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

cc: @danagbemava-nc

**Comment by Vedsaga** [comment]
Just update... after switching back to `3.16.0` and run and then switch back to `3.19.1` started working...

While not able to reproduce the starter project the above error... however still happening in `Prouduction-App`... will keep trying to figout what is that which is going wrong...

**Comment by vanlooverenkoen** [comment]
I can confirm that after updating from 3.16.9 tot 3.19.2 it is still happening. Not sure why or when exactly it happens. because i am able to debug & develop but after "a while" it fails to hot reload and I have to run flutter clean and run again.

**Comment by Vedsaga** [comment]
Just noticed... last time when tried to produce the exception forget to enable Impller,,,

this time able to reproduce it...

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Autocomplete].

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                  'Type below to autocomplete the following possible results: ${AutocompleteBasicExample._kOptions}.'),
              const AutocompleteBasicExample(),
              FilledButton(
                onPressed: () {
                  print("----Impeller Exception----");
                },
                child: Text('Click for Impeller Exception'),
              )
            ],
          ),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsViewOpenDirection: OptionsViewOpenDirection.up,
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}
```

Also, set the `EnableImpeller` true... and just run the app it should throw exception as reported earlier...
```xml

        <meta-data
            android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="true" />
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

cc: @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @Vedsaga, I was able to reproduce this on the stable channel but I can't seem to reproduce this on the `master` channel. 

Can you confirm if you still reproduce this on the master channel?
