### ISSUE TITLE
Scenario app logs are plagued with "failing to get GeneratedPluginRegistrant"

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#143950]
/cc @dnfield @johnmccutchan 

This is because the Android embedder [always expects a class called `io.flutter.plugins.GeneratedPluginRegistrant`](https://github.com/flutter/engine/blob/05ffcb1cf7d668ae85d3e144b9f4c9fc6f8e1673/shell/platform/android/io/flutter/embedding/engine/plugins/util/GeneratedPluginRegister.java#L74-L89) to exist.

A few possible options:

1. Check-in a default/blank implementation (since the `flutter` tool will never generate one in this package)
2. Remove the error message in general
3. Add some sort of flag (`GeneratedPluginRegister.debugDisableGeneratedPlugins = true`)

My preference is (1).

---

As [an example](https://storage.googleapis.com/flutter_logs/flutter/06448ee8165f4ff6579ef9510ac69322eda896ac/Android%20Scenario%20App%20Integration%20Tests%20(Skia)/3fc0c1a3-726d-4e5e-bf10-35bf0f02f8ac/logcat.txt):

```txt
[stdout] 02-22 16:08:37.983  7025  7025 E GeneratedPluginsRegister: Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@665395d) but could not find or invoke the GeneratedPluginRegistrant.
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: Received exception while registering
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: java.lang.ClassNotFoundException: io.flutter.plugins.GeneratedPluginRegistrant
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.lang.Class.classForName(Native Method)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.lang.Class.forName(Class.java:536)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.lang.Class.forName(Class.java:467)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:77)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:385)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:287)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:268)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:248)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:168)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:159)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at dev.flutter.scenarios.EngineLaunchE2ETest.lambda$smokeTestEngineLaunch$0(EngineLaunchE2ETest.java:36)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at dev.flutter.scenarios.EngineLaunchE2ETest$$ExternalSyntheticLambda0.run(Unknown Source:4)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2420)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.os.Handler.handleCallback(Handler.java:958)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.os.Handler.dispatchMessage(Handler.java:99)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.os.Looper.loopOnce(Looper.java:205)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.os.Looper.loop(Looper.java:294)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at java.lang.reflect.Method.invoke(Native Method)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[stdout] 02-22 16:08:37.988  7025  7025 E GeneratedPluginsRegister: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by jonahwilliams** [comment]
Closing as obsolete (deleted)
