### ISSUE TITLE
TextField's InkRipple.cancel can be called before InkRipple is built

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#14391]
Details filed internally.

@HansMuller

**Comment by HansMuller** [comment]
Swan song:
```
I/flutter (28903): When the exception was thrown, this was the stack:
I/flutter (28903): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (28903): #1      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:499)
I/flutter (28903): #2      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:387)
I/flutter (28903): #3      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:363)
I/flutter (28903): #4      InkRipple.cancel (package:flutter/src/material/ink_ripple.dart:204)
I/flutter (28903): #5      _TextFieldState._cancelCurrentSplash (package:flutter/src/material/text_field.dart:418)
I/flutter (28903): #6      _TextFieldState._handleTapCancel (package:flutter/src/material/text_field.dart:394)
I/flutter (28903): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
I/flutter (28903): #8      TapGestureRecognizer.rejectGesture (package:flutter/src/gestures/tap.dart:134)
```
