### ISSUE TITLE
[flutter_test]scrollUntilVisible has different results if ListTile's onTap is null or not

### ISSUE THREAD

**Issue by megur0** [flutter/flutter#143921]
### Steps to reproduce

1. Paste sample code to tests/xxx_test.dart in Flutter project
2. Execute test by flutter test --plain-name 'scrollUntilVisible'

### Expected results

The test passes, whether or not the ListTile's onTap attribute is null.

### Actual results

The test will fail if ListTile's onTap attribute is not null.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

// flutter test --plain-name 'scrollUntilVisible'
void main() {
  group("scrollUntilVisible", () {
    Future<void> pumpListViewAndScrollToEndContent(
        WidgetTester tester, bool hasOnTap) async {
      int itemCount = 30;
      final controller = ScrollController();
      await tester.pumpWidget(MaterialApp(
          home: Scaffold(
        body: ListView.builder(
          controller: controller,
          itemBuilder: (context, index) {
            if (index <= itemCount) {
              return ListTile(
                onTap: hasOnTap
                    ? () {
                        //debugPrint("tapped");
                      }
                    : null,
                title: Text("$index"),
              );
            }
            return null;
          },
        ),
      )));

      // controller.addListener(() {
      //   debugPrint(
      //       "${controller.position.pixels}, ${controller.position.maxScrollExtent}");
      // });

      await tester.scrollUntilVisible(
        find.text("${itemCount - 1}"),
        20,
        maxScrolls: 2000,
        duration: const Duration(milliseconds: 50),
        scrollable: find.byType(Scrollable),
      );
    }

    testWidgets("This results success", (tester) async {
      // ListTile has "onTap" as null
      await pumpListViewAndScrollToEndContent(tester, false);
    });

    testWidgets("This results failed", (tester) async {
      // ListTile has "onTap" as not null
      await pumpListViewAndScrollToEndContent(tester, true);
    });
  });
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
% flutter test --plain-name 'scrollUntilVisible'
00:06 +1: /xxx/xxx.dart: scrollUntilVisible This results failed                                                      
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:674:25)
#1      WidgetController.element (package:flutter_test/src/controller.dart:448:30)
#2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1709:38)
<asynchronous suspension>
#3      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#4      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1675:7)
<asynchronous suspension>
#5      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#6      main.<anonymous closure>.pumpListViewAndScrollToEndContent (/xxx/xxx_test.dart:36:7)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (/xxx/xxx_test.dart:52:7)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

</details>

### Flutter Doctor output

<details open><summary>I have not installed the Android environment, but it is not related to the test.</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.86.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment]
Thanks for the report @megur0.
I can reproduce this on the latest `stable` and `master` channels.

<details><summary>Logs</summary>
<p>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:674:25)
#1      WidgetController.element (package:flutter_test/src/controller.dart:863:30)
#2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:2222:38)
<asynchronous suspension>
#3      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#4      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:2188:7)
<asynchronous suspension>
#5      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#6      main.<anonymous closure>.pumpListViewAndScrollToEndContent (file:///Users/damilolaalimi/development/master/test/widget_test.dart:36:7)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (file:///Users/damilolaalimi/development/master/test/widget_test.dart:52:7)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1019:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  This results failed
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +1 -1: scrollUntilVisible This results failed [E]                                                                                                                                                
  Test failed. See exception logs above.
  The test description was: This results failed
  

To run this test again: /Users/damilolaalimi/fvm/versions/master/bin/cache/dart-sdk/bin/dart test /Users/damilolaalimi/development/master/test/widget_test.dart -p vm --plain-name 'scrollUntilVisible This results failed'
00:03 +1 -1: Some tests failed. 
``` 

</p>
</details> 

This might be similar or related to https://github.com/flutter/flutter/issues/54665.

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.19.1 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (2 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E • ios            •
      iOS 17.1.1 21B91
    • macOS (desktop)            • macos                     • darwin-arm64   •
      macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript •
      Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.20.0-11.0.pre.80, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-11.0.pre.80 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efee280cfa (8 hours ago), 2024-02-21 21:44:25 -0500
    • Engine revision 7eeb697687
    • Dart version 3.4.0 (build 3.4.0-163.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by hgraceb** [comment]
In the latest code on the master branch, this behavior can be corrected by adding `continuous = true`.

```diff
 await tester.scrollUntilVisible(
   find.text("${itemCount - 1}"),
   20,
   maxScrolls: 2000,
   duration: const Duration(milliseconds: 50),
   scrollable: find.byType(Scrollable),
+  continuous: hasOnTap,
 );
```

**Comment by megur0** [comment]
Thanks very much, hgraceb-san!

By the way, I think it's a bit difficult for developers to understand that the "continuous" option can solve this problem, and think the behavior when continuous:true is set is what we expect when executing the scrollUntilVisible API without any option.

I thought this opt-in was a temporary implementation to make existing code work, and hope that in the future this will become the default behavior and the "continuous" option will probably disappear altogether.

**Comment by hgraceb** [comment]
Yes, that's right. The initial proposal did not include `continuous`, but as mentioned in https://github.com/flutter/flutter/pull/159582#issuecomment-2605640309, adding an optional parameter is a compromise.
