### ISSUE TITLE
Bringup builds that use Skia gold are now failing

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#144064]
As a result of https://github.com/flutter/engine/pull/50826, the engine now reports failures on untriaged Skia gold images.

However, something unintended happened - builds marked `bringup: true` are now infinitely failing:

- 🚫 [`linux_android_emulator_opengles_tests`](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20linux_android_emulator_tests_api_33/)
- 🚫 [`linux_android_emulator_tests_api_33`](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20linux_android_emulator_opengles_tests)

We need to resolve this, having bringup builds that _never_ pass are not useful.

## test: Android Scenario App Integration Tests (Impeller/OpenGLES)

[Example failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755260238337047233/+/u/test:_Android_Scenario_App_Integration_Tests__Impeller_OpenGLES_/stdout):

```txt
skia gold comparison failed: Exception: Skia Gold received an unapproved image in post-submit 
testing. Golden file images in flutter/engine are triaged 
in pre-submit during code review for the given PR.

Visit https://flutter-engine-gold.skia.org// to view and approve 
the image(s), or revert the associated change. For more 
information, visit the wiki: 
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 2259df20880399e76dbb98daebc5dca0 for test ExternalTextureTests_testCroppedRotatedMediaSurface_bottomLeft_90
Expectation for test: 2259df20880399e76dbb98daebc5dca0 (positive)
Expectation for test: 2f80cb176bc70e3f26da67f98cb81bb0 (positive)
Expectation for test: 5ea0bffc5ccbe4c3a97abf8959412ac0 (positive)
Expectation for test: 68a643f1d6ccbd866706a08947350551 (positive)
Expectation for test: b2454b91473a21dd73f67c7da0336a44 (positive)
Expectation for test: a7ddd05be8c2585d87512b742037e17d (negative)
Expectation for test: d04cb0034d0bbce86b1cf2c21d7e2470 (positive)
Expectation for test: 0f71af5ad275f8c20ea58f055dcd878c (positive)
Expectation for test: 1cd13164b4fb06892df47c5978419ef9 (positive)
Expectation for test: 5a0525040ca8d8539011bb80c95a0741 (positive)
Expectation for test: 5ba6df7acef516f7dab78587cf30ce20 (positive)
Expectation for test: 84d38d076525be7a707bb040536f8089 (positive)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730741929048499.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)

stderr: Error running command
```

## test: Scenario App Integration Tests (API 33)

[Example output](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8755260235167443377/+/u/test:_Scenario_App_Integration_Tests__2_/stdout):

```txt
skia gold comparison failed: Exception: Skia Gold received an unapproved image in post-submit 
testing. Golden file images in flutter/engine are triaged 
in pre-submit during code review for the given PR.

Visit https://flutter-engine-gold.skia.org// to view and approve 
the image(s), or revert the associated change. For more 
information, visit the wiki: 
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 38d4029cea965bcc54e3ad97d07bb324 for test DrawSolidBlueScreenTest
Expectation for test: 0ecdc939286da111fcf82bc55f2c025c (positive)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Fetching most recent positive digest for trace with ID "32fd77fb672873775ff1b28d8de3429b".
No recent positive digests for trace with ID "32fd77fb672873775ff1b28d8de3429b". This probably means that the test was newly added.
Non-exact image comparison using algorithm "fuzzy" against most recent positive digest "".
Untriaged or negative image: https://flutter-engine-gold.skia.org/detail?grouping=name%3DDrawSolidBlueScreenTest%26source_type%3Dflutter-engine&digest=38d4029cea965bcc54e3ad97d07bb324

Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)
Error closing file skia-gold-flutter-engine/dm-json-v1/2024/02/23/23/ca2452074a49938ffb04b9614aed480a04fef1c6/waterfall/dm-1708730981516094698.json: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden (retrying)

stderr: Error running command: ''Error uploading image /b/s/w/ir/x/w/recipe_cleanup/flutter_logs_dir/DrawSolidBlueScreenTest.png to gs://skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png. Got: uploading 10480 bytes to skia-gold-flutter-engine/dm-images-v1/38d4029cea965bcc54e3ad97d07bb324.png with exponential retries: googleapi: Error 403: flutter-staging-builder@chops-service-accounts.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist)., forbidden. At gcsuploader.go:180 retry.go:37 retry.go:24 gcsuploader.go:154 gcsuploader.go:130 goldclient.go:340 errgroup.go:75 asm_amd64.s:1650. At goldclient.go:341 errgroup.go:75 asm_amd64.s:1650''
```

**Comment by matanlurey** [comment]
I just approved the Impeller OpenGLES goldens waiting for triage and am waiting for the builder to turn green. When it does, I'll send a PR moving it back to pre-submit.

For whatever reason, OpenGLES+ForceSurfaceTexture does not appear to be running:
- [CI Definition](https://github.com/search?q=repo%3Aflutter%2Fengine+path%3Aci%2Fbuilders+%22--impeller-backend%3Dopengles%22+%22run_android_tests.dart%22+%22--force-surface-producer-surface-texture%22&type=code)
- [CI Run, which omits this test](https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20Staging%20Engine%20Drone/92083/overview)

... weird, but I'll investigate it after we move a set to pre-submit (https://github.com/flutter/flutter/issues/144809).

**Comment by matanlurey** [comment]
Quick update:

1. The OpenGLES tests mostly have stabilized. I approved some digests, and I'll see how it works out.
2. The API v33 tests are crashing very frequently:

```txt
03-26 18:18:33.140 [E] AndroidRuntime: FATAL EXCEPTION: image reader/writer thread
03-26 18:18:33.140 [E] AndroidRuntime: Process: dev.flutter.scenarios, PID: 4599
03-26 18:18:33.140 [E] AndroidRuntime: java.lang.RuntimeException: nativeDetachImage failed for image!!!
03-26 18:18:33.140 [E] AndroidRuntime: at android.media.ImageReader.nativeDetachImage(Native Method)
03-26 18:18:33.140 [E] AndroidRuntime: at android.media.ImageReader.detachImage(ImageReader.java:870)
03-26 18:18:33.140 [E] AndroidRuntime: at android.media.ImageWriter.queueInputImage(ImageWriter.java:527)
03-26 18:18:33.140 [E] AndroidRuntime: at dev.flutter.scenarios.ExternalTextureFlutterActivity$ImageSurfaceRenderer.onImageAvailable(ExternalTextureFlutterActivity.java:405)
03-26 18:18:33.140 [E] AndroidRuntime: at dev.flutter.scenarios.ExternalTextureFlutterActivity$ImageSurfaceRenderer.$r8$lambda$BBcQh_YQGJ8Oq2zMsGvTmZhrjIk(Unknown Source:0)
03-26 18:18:33.140 [E] AndroidRuntime: at dev.flutter.scenarios.ExternalTextureFlutterActivity$ImageSurfaceRenderer$$ExternalSyntheticLambda2.onImageAvailable(Unknown Source:2)
03-26 18:18:33.140 [E] AndroidRuntime: at android.media.ImageReader$1.run(ImageReader.java:916)
03-26 18:18:33.140 [E] AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
03-26 18:18:33.140 [E] AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 18:18:33.140 [E] AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
03-26 18:18:33.140 [E] AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
03-26 18:18:33.140 [E] AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:67)
```

I'll file separate follow-up issues for both of these.
