### ISSUE TITLE
Integration tests failing due to PathNotFoundException

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#144008]
### Steps to reproduce

Hello,

The integration tests I've written by themselves succeed, in Android Studio the test shows up as green.
However when the tooling tries to uninstall the app from the device (Android Emulator), it fails to do so and then marks the test as failed as well.

So technically the test succeeded, but then the tooling failed for some reason marking the test as failed as well.

Note that this is not always. It feels like half of the time the test does fully succeed (including the uninstall), by running the exact same test several times in a row.

### Expected results

Either the tooling should not fail, or the test should still be marked as succeeded.

### Actual results

The test fails.

```
adb uninstall failed: ProcessException: Process exited abnormally with exit code -2:

  Command: /Users/glennruysschaert/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall app.getdriven.customer.staging.debug
unhandled error during finalization of test:
/Users/glennruysschaert/Code/get-driven-customer-app/integration_test/profile_options_test.dart
PathNotFoundException: Deletion failed, path = '/var/folders/l9/rsj1dsjd64b2hnrzxw53hvc80000gn/T/flutter_tools.VWvUbU/flutter_test_listener.Y3PBgI' (OS Error: No such file or directory, errno = 2)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:188:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:601:15)
#4      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:565:26)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#6      _FlutterPlatformStreamSinkWrapper.close.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:675:7)
<asynchronous suspension>

dart:io/directory_impl.dart 188:7                                     _Directory._deleteSync
dart:io/file_system_entity.dart 407:7                                 FileSystemEntity.deleteSync
package:file/src/forwarding/forwarding_file_system_entity.dart 70:16  ForwardingFileSystemEntity.deleteSync
package:flutter_tools/src/test/flutter_platform.dart 601:15           FlutterPlatform._createListenerDart.<fn>
package:flutter_tools/src/test/flutter_platform.dart 565:26           FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/future.dart 518:21                                         Future.wait.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/test/flutter_platform.dart 675:7            _FlutterPlatformStreamSinkWrapper.close.<fn>
Error: the Dart compiler exited unexpectedly.
package:flutter_tools/src/base/common.dart 10:3  throwToolExit
package:flutter_tools/src/compile.dart 896:9     DefaultResidentCompiler._compile.<fn>
dart:async/zone.dart 1407:47                     _rootRunUnary
dart:async/zone.dart 1308:19                     _CustomZone.runUnary
dart:async/future_impl.dart 838:45               Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 867:13               Future._propagateToListeners
dart:async/future_impl.dart 643:5                Future._completeWithValue
dart:async/future_impl.dart 713:7                Future._asyncCompleteWithValue.<fn>
dart:async/zone.dart 1399:13                     _rootRun
dart:async/zone.dart 1301:19                     _CustomZone.run
dart:async/zone.dart 1209:7                      _CustomZone.runGuarded
dart:async/zone.dart 1249:23                     _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21         _microtaskLoop
dart:async/schedule_microtask.dart 49:5          _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13     _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5      _RawReceivePort._handleMessage

PathNotFoundException: Deletion failed, path = '/var/folders/l9/rsj1dsjd64b2hnrzxw53hvc80000gn/T/flutter_tools.VWvUbU/flutter_test_listener.Y3PBgI' (OS Error: No such file or directory, errno = 2)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
Any integration test.
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
adb uninstall failed: ProcessException: Process exited abnormally with exit code -2:

  Command: /Users/glennruysschaert/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall app.getdriven.customer.staging.debug
unhandled error during finalization of test:
/Users/glennruysschaert/Code/get-driven-customer-app/integration_test/profile_options_test.dart
PathNotFoundException: Deletion failed, path = '/var/folders/l9/rsj1dsjd64b2hnrzxw53hvc80000gn/T/flutter_tools.VWvUbU/flutter_test_listener.Y3PBgI' (OS Error: No such file or directory, errno = 2)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:188:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:601:15)
#4      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:565:26)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#6      _FlutterPlatformStreamSinkWrapper.close.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:675:7)
<asynchronous suspension>

dart:io/directory_impl.dart 188:7                                     _Directory._deleteSync
dart:io/file_system_entity.dart 407:7                                 FileSystemEntity.deleteSync
package:file/src/forwarding/forwarding_file_system_entity.dart 70:16  ForwardingFileSystemEntity.deleteSync
package:flutter_tools/src/test/flutter_platform.dart 601:15           FlutterPlatform._createListenerDart.<fn>
package:flutter_tools/src/test/flutter_platform.dart 565:26           FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/future.dart 518:21                                         Future.wait.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/test/flutter_platform.dart 675:7            _FlutterPlatformStreamSinkWrapper.close.<fn>
Error: the Dart compiler exited unexpectedly.
package:flutter_tools/src/base/common.dart 10:3  throwToolExit
package:flutter_tools/src/compile.dart 896:9     DefaultResidentCompiler._compile.<fn>
dart:async/zone.dart 1407:47                     _rootRunUnary
dart:async/zone.dart 1308:19                     _CustomZone.runUnary
dart:async/future_impl.dart 838:45               Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 867:13               Future._propagateToListeners
dart:async/future_impl.dart 643:5                Future._completeWithValue
dart:async/future_impl.dart 713:7                Future._asyncCompleteWithValue.<fn>
dart:async/zone.dart 1399:13                     _rootRun
dart:async/zone.dart 1301:19                     _CustomZone.run
dart:async/zone.dart 1209:7                      _CustomZone.runGuarded
dart:async/zone.dart 1249:23                     _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21         _microtaskLoop
dart:async/schedule_microtask.dart 49:5          _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13     _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 185:5      _RawReceivePort._handleMessage

PathNotFoundException: Deletion failed, path = '/var/folders/l9/rsj1dsjd64b2hnrzxw53hvc80000gn/T/flutter_tools.VWvUbU/flutter_test_listener.Y3PBgI' (OS Error: No such file or directory, errno = 2)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.2.1 23C71 darwin-arm64
    (Rosetta), locale en-GB)
    • Flutter version 3.19.1 on channel stable at
      /Users/glennruysschaert/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (3 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/glennruysschaert/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  •
      Android 14 (API 34) (emulator)
    • Glenn’s iPhone (mobile)     • 00008130-0005148E1061401C • ios            •
      iOS 17.3.1 21D61
    • macOS (desktop)             • macos                     • darwin-arm64   •
      macOS 14.2.1 23C71 darwin-arm64 (Rosetta)
    • Chrome (web)                • chrome                    • web-javascript •
      Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for Glenn’s iPad. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @vixez 
I'm checking this issue with a minimal sample code at [An introduction to integration testing](https://docs.flutter.dev/cookbook/testing/integration/introduction) but can't see the issue (ran the test a few times)


```console
/Users/huynq/Documents/GitHub/flutter/bin/flutter --no-color test --machine --start-paused -d EUYTFEUSQSRGDA6D integration_test/app_test.dart
Testing started at 12:38 ...
Running Gradle task 'assembleDebug'...                             60.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...           5.7s
```

Could you also try this example and confirm the same result?

**Comment by huycozy** [comment]
Thanks for the update, I can reproduce the issue when debugging the test. But this only appears on Android Studio as I don't see it on VSCode. For the details, I started debugging the test on the IDE's UI as follows:

| Android Studio ❗ | VSCode ✅ |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/3a3b2b6e-8df7-4d20-b64c-42ad781407af"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/425fea00-c719-4769-9bae-204a3204943c">

✅: No Issue ❗: Issue reproduced

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (29 hours ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-13.0.pre.46, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-13.0.pre.46 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 523b0c4d84 (3 hours ago), 2024-02-26 15:55:52 -0800
    • Engine revision 04ff2868ce
    • Dart version 3.4.0 (build 3.4.0-176.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.69

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Looking at the stack trace, perhaps tool team can have thoughts on this.

**Comment by agent3bood** [comment]
I get the same error when debugging, but just running the test from IDE works.

Both run and debug commands are the same
```
/Users/username/fvm/versions/3.19.5/bin/flutter --no-color test --machine --start-paused -d 4A757678-006D-46B7-9E32-A7704DC2C067 integration_test/video_test.dart
```

**Comment by DanTup** [comment]
I just hit this too on latest master while checking if https://github.com/Dart-Code/Dart-Code/issues/5165 was still an issue (I'm hoping @matanlurey's recent changes might have fixed it).

I created a new Flutter project with the following test that takes a long time:

```
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await Future.delayed(const Duration(hours: 1));
  });
}
```

Then I ran it with `flutter test` and after a few seconds, hit Ctrl+C:

```
PS D:\Dev\Test Projects\dartcode_5165> flutter test .\test\widget_test.dart
00:09 +0: Counter increments smoke test - did not complete [E]
00:09 +0: Some tests failed.
unhandled error during finalization of test:
D:/Dev/Test Projects/dartcode_5165/test/widget_test.dart
PathNotFoundException: Deletion failed, path = 'C:\Users\danny\AppData\Local\Temp\flutter_tools.fd212f99\flutter_test_listener.76ab55e0' (OS Error:
The system cannot find the path specified.
, errno = 3)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:226:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:425:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:492:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:491:12)
#6      FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:672:15)
#7      FlutterPlatform._startTest.finalize (package:flutter_tools/src/test/flutter_platform.dart:499:26)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:528:21)
<asynchronous suspension>
#9      _DefaultShutdownHooks.runShutdownHooks (package:flutter_tools/src/base/process.dart:76:7)
<asynchronous suspension>
#10     exitWithHooks (package:flutter_tools/src/base/process.dart:733:3)
<asynchronous suspension>
#11     LocalSignals._handleSignal (package:flutter_tools/src/base/signals.dart:154:7)
<asynchronous suspension>


Terminate batch job (Y/N)?
```

**Comment by TomKrauss** [comment]
We have the same problem in our Flutter Desktop Linux Builds on the Build Server occasionally.

**Comment by DanTup** [comment]
I haven't been able to reproduce it locally yet, but I'm seeing this a lot on Dart-Code's CI tests recently (possibly since the latest Flutter stable release?), for example:

https://github.com/Dart-Code/Dart-Code/actions/runs/17245731408/job/48934734886


```
    when running tests by name
Error: 0 PM] [VmService] [Error] [Dart & Flutter (flutter test debugger when running tests by name runs a Flutter test script to completion)] unhandled error during finalization of test:
/home/runner/work/Dart-Code/Dart-Code/src/test/test_projects/flutter_hello_world/test/widget_test.dart
PathNotFoundException: Deletion failed, path = '/tmp/flutter_tools.ALXQCK/flutter_test_listener.WZBBEF' (OS Error: No such file or directory, errno = 2)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:225:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:425:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:451:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:552:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:450:12)
#6      FlutterPlatf…
```

**Comment by cpfeiffer** [comment]
> I haven't been able to reproduce it locally yet, but I'm seeing this a lot on Dart-Code's CI tests recently (possibly since the latest Flutter stable release?), for example:
> 
> https://github.com/Dart-Code/Dart-Code/actions/runs/17245731408/job/48934734886

I can reproduce it locally when interrupting a running/waiting test with Ctrl-C as described in https://github.com/flutter/flutter/issues/144008#issuecomment-2500634254

So maybe the exception is not the cause, but the result of the tests being terminated. In your logs at https://github.com/Dart-Code/Dart-Code/actions/runs/17245731408/job/48934734886 the tests seem to be terminated by node due to timeouts?

In our case, we suspect some leftover files from previous runs to cause the test aborts and as a result the PathNotFoundException.

**Comment by DanTup** [comment]
> So maybe the exception is not the cause, but the result of the tests being terminated. In your logs at https://github.com/Dart-Code/Dart-Code/actions/runs/17245731408/job/48934734886 the tests seem to be terminated by node due to timeouts?

Yep, I think you're right. The timeout is logged after that error is printed, but I think that's just because of how the test results are reported - I think this is a side-effect of the timeout/termination.
