### ISSUE TITLE
_handleChange in _AnimationState throws `(setState() called after dispose(): _AnimatedState#e2d24(lifecycle state: defunct, not mounted))`

### ISSUE THREAD

**Issue by RolfSuslik** [flutter/flutter#144087]
### Steps to reproduce

I updated flutter today and noticed the following error:

I use Riverpod to update my states. (Reproducible without Riverpod too. See first comment)
I handle the state of the content and number of tabs of my TabBar with it.
When I add a new tab and update the state with Riverpod, the TabBar gets rebuild.
When I try to open the new created tab, the app crashes. The error:
"setState() called after dispose(): _AnimatedState#e2d24(lifecycle state: defunct, not mounted)"
I looked into the stack trace and noticed that there is a method: 
```
void _handleChange() {
    setState(() {
      // The listenable's state is our build state, and it changed already.
    });
  }
```
and its in C:\dev\flutter\packages\flutter\lib\src\widgets\transitions.dart\_AnimatedState\_handleChange

When I comment out the "setState" my app works again.

### Expected results

When I create new tabs in my TabBar, I should be able to select them.

### Actual results

The app crashes when I try to select the new tab with the error message: "setState() called after dispose(): _AnimatedState#e2d24(lifecycle state: defunct, not mounted)"

### Code sample

<details open><summary>Code sample</summary>

```dart
final tabsProvider = StateProvider<int>((ref) {
  return 1;
});

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  static const String _title = 'Flutter Stateful Clicker Counter';
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({super.key});
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final tabs = ref.watch(tabsProvider);
    return DefaultTabController(
      length: tabs,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo Click Counter'),
          bottom: TabBar(
            tabAlignment: TabAlignment.start,
            isScrollable: true,
            tabs: createTabs(tabs),
          ),
        ),
        body: TabBarView(
          children: createTabViews(tabs),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => ref.read(tabsProvider.notifier).state = tabs + 1,
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}

List<Tab> createTabs(int tabs) {
  final List<Tab> tabList = [];
  for (var i = 0; i < tabs; i++) {
    tabList.add(Tab(
      text: "Tab $i",
    ));
  }
  return tabList;
}

List<Text> createTabViews(int tabs) {
  final List<Text> allTabs = [];
  for (var i = 0; i < tabs; i++) {
    allTabs.add(Text("View $i"));
  }
  return allTabs;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.3155], locale en-CH)
    • Flutter version 3.19.1 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (4 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\rsu\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\rsu\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\rsu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 121.0.6167.162
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by RolfSuslik** [comment]
Just noticed the behaivior is the same with StatefullWidget and setState

```
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  static const String _title = 'Flutter Stateful Clicker Counter';
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int tabs = 1;
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: tabs,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo Click Counter'),
          bottom: TabBar(
            tabAlignment: TabAlignment.start,
            isScrollable: true,
            tabs: createTabs(tabs),
          ),
        ),
        body: TabBarView(
          children: createTabViews(tabs),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              ++tabs;
            });
          },
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}

List<Tab> createTabs(int tabs) {
  final List<Tab> tabList = [];
  for (var i = 0; i < tabs; i++) {
    tabList.add(Tab(
      text: "Tab $i",
    ));
  }
  return tabList;
}

List<Text> createTabViews(int tabs) {
  final List<Text> allTabs = [];
  for (var i = 0; i < tabs; i++) {
    allTabs.add(Text("View $i"));
  }
  return allTabs;
}
```

**Comment by darshankawar** [comment]
Thanks for the report @RolfSuslik 
As the error says:

```
This error happens if you call setState() on a State object for a widget that no longer appears in
the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
callback. Another solution is to check the "mounted" property of this object before calling
setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is
retaining a reference to this State object after it has been removed from the tree. To avoid memory
leaks, consider breaking the reference to this object during dispose().

```

Can you do a mount check in `didChange` function and see if it helps ?
Also, the setState seems to be getting called after widget has been disposed that you can cross-check in your code implementation.

**Comment by RolfSuslik** [comment]
Hello darshankawar

You mean the `_handleChange()` function in my "C:\dev\flutter\packages\flutter\lib\src\widgets\transitions.dart_AnimatedState_handleChange"?
I can change it to this:
```
void _handleChange() {
    if (mounted) {
      setState(() {
        // The listenable's state is our build state, and it changed already.
      });
    }
  }
```
and then it will work. BUT its a function from the flutter package and I don't think I should change anything in it.
And the error occurred after I updated flutter with `flutter upgrade`. Before it worked well.

Best regards
Rolf

**Comment by darshankawar** [comment]
> And the error occurred after I updated flutter with `flutter upgrade`. Before it worked well.

What version you were on before upgrading ?

**Comment by RolfSuslik** [comment]
I am not 100% sure. I started with 3.2.3 in December. I don't know if I updated flutter in between.

**Comment by darshankawar** [comment]
Thanks for the update. Using below code sample, I was able to replicate the error log reported.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  static const String _title = 'Flutter Stateful Clicker Counter';
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int tabs = 1;
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: tabs,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo Click Counter'),
          bottom: TabBar(
            tabAlignment: TabAlignment.start,
            isScrollable: true,
            tabs: createTabs(tabs),
          ),
        ),
        body: TabBarView(
          children: createTabViews(tabs),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              ++tabs;
            });
          },
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}

List<Tab> createTabs(int tabs) {
  final List<Tab> tabList = [];
  for (var i = 0; i < tabs; i++) {
    tabList.add(Tab(
      text: "Tab $i",
    ));
  }
  return tabList;
}

List<Text> createTabViews(int tabs) {
  final List<Text> allTabs = [];
  for (var i = 0; i < tabs; i++) {
    allTabs.add(Text("View $i"));
  }
  return allTabs;
}

```

</details>



https://github.com/flutter/flutter/assets/67046386/dbb85841-a2bc-4283-ad0c-33b7150b41ff

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.20.0-15.0.pre.23, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.20.0-15.0.pre.23 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96a390a9e9 (12 minutes ago), 2024-02-28 04:51:10 +0000
    • Engine revision c79117b706
    • Dart version 3.4.0 (build 3.4.0-183.0.dev)
    • DevTools version 2.33.0-dev.11
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

<details>
<summary> error log </summary>

```

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
setState() called after dispose(): _AnimatedState#67b95(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
#2      _AnimatedState._handleChange (package:flutter/src/widgets/transitions.dart:129:5)
#3      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#4      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:856:5)
#5      Ticker._tick (package:flutter/src/scheduler/ticker.dart:258:12)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1388:15)
#7      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1235:11)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#9      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1233:17)
#10     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1150:5)
#11     _invoke1 (dart:ui/hooks.dart:328:13)
#12     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
#13     _beginFrame (dart:ui/hooks.dart:272:31)
The AnimationController notifying listeners was: AnimationController#73d43(▶ 1.114)
====================================================================================================

```

</details>

**Comment by goderbauer** [comment]
Thank you for the code sample that reproduces the crash. This crash was previously reported in https://github.com/flutter/flutter/issues/138588, but we weren't able to trace it down to the root cause because we couldn't reproduce it. Now, with the additional information provided in this bug I was able to identify https://github.com/flutter/flutter/pull/136608 as the root cause, which I am reverting in https://github.com/flutter/flutter/pull/144579.
