### ISSUE TITLE
firebase_core_web-2.11.4 method not found after upgrade

### ISSUE THREAD

**Issue by BenCherif** [flutter/flutter#144141]
### Steps to reproduce

i have those dependencies of firebase :

```
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  firebase_messaging: ^14.7.16
```

and current flutter version is : 3.19.1
when i run it by command :  `flutter run -d  chrome`

### Expected results

i expect to run  normally on web

### Actual results

i got this error  :
<img width="1590" alt="Screenshot 2024-02-26 at 14 47 41" src="https://github.com/flutter/flutter/assets/12634281/992da1cf-dd41-43f1-b224-732cc2363176">

### Code sample

<details open><summary>Code sample</summary>

```dart
 
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

 
<img width="1590" alt="Screenshot 2024-02-26 at 14 47 41" src="https://github.com/flutter/flutter/assets/12634281/1d9172d6-b689-4f5a-abc9-0a375f9286cc">

</details>

### Logs

<details open><summary>Logs</summary>

```console
  flutter run -d  chrome
Launching lib/main.dart on Chrome in debug mode...
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:19:12: Error: Type 'web.TrustedTypePolicyFactory' not found.
  external web.TrustedTypePolicyFactory? get nullableTrustedTypes;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:24:41: Error: Type 'web.TrustedTypePolicy' not found.
extension CreateScriptUrlWithoutArgs on web.TrustedTypePolicy {
                                        ^^^^^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:27:12: Error: Type 'web.TrustedScriptURL' not found.
  external web.TrustedScriptURL createScriptURLNoArgs(
           ^^^^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:37:22: Error: Type 'web.TrustedScriptURL' not found.
  external set srcTT(web.TrustedScriptURL value);
                     ^^^^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/firebase_core_web.dart:108:9: Error: 'TrustedScriptURL' isn't a type.
    web.TrustedScriptURL? trustedUrl;
        ^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/firebase_core_web.dart:115:19: Error: 'TrustedTypePolicy' isn't a type.
        final web.TrustedTypePolicy policy =
                  ^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/firebase_core_web.dart:118:15: Error: Method not found: 'TrustedTypePolicyOptions'.
          web.TrustedTypePolicyOptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/firebase_core_web.dart:116:24: Error: The getter 'trustedTypes' isn't defined for the class 'Window'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'trustedTypes'.
            web.window.trustedTypes.createPolicy(
                       ^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:37:26: Error: 'TrustedScriptURL' isn't a type.
  external set srcTT(web.TrustedScriptURL value);
                         ^^^^^^^^^^^^^^^^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:19:46: Error: Type 'invalid-type' is not a valid type in the signature of
`dart:js_interop` external APIs or APIs converted via `toJS`. The only valid types are: JS types from `dart:js_interop`, @staticInterop types, void, bool, num, double, int, String, extension types
that erases to one of these types, or a type parameter that is bound to a static interop type.
Use one of the valid types instead.
  external web.TrustedTypePolicyFactory? get nullableTrustedTypes;
                                             ^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:27:33: Error: JS interop or Native class required for 'external' extension members.
Try adding a JS interop annotation to the on type class of the extension.
  external web.TrustedScriptURL createScriptURLNoArgs(
                                ^
/Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart:37:16: Error: Type 'invalid-type' is not a valid type in the signature of
`dart:js_interop` external APIs or APIs converted via `toJS`. The only valid types are: JS types from `dart:js_interop`, @staticInterop types, void, bool, num, double, int, String, extension types
that erases to one of these types, or a type parameter that is bound to a static interop type.
Use one of the valid types instead.
  external set srcTT(web.TrustedScriptURL value);
               ^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling
file:///Users/bencherif/.pub-cache/hosted/pub.dev/firebase_core_web-2.11.4/lib/src/interop/package_web_tweaks.dart, which contains the type: FunctionType(<invalid> Function(String)).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3678)
#1      ProgramCompiler._newEmitType (package:dev_compiler/src/kernel/compiler.dart:3471)
#2      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3379)
#3      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:3731)
#4      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:3307)
#5      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7573)
#6      FunctionExpression.accept (package:kernel/ast.dart:8606)
#7      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#8      ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:5182)
#9      ReturnStatement.accept (package:kernel/ast.dart:10159)
#10     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#11     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#12     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#13     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#14     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#15     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#16     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#17     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:3262)
#18     MappedIterator.moveNext (dart:_internal/iterable.dart:403)
#19     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#20     new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#21     new List.of (dart:core-patch/array_patch.dart:39)
#22     Iterable.toList (dart:core/iterable.dart:497)
#23     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:3188)
#24     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:785)
#25     List.forEach (dart:core-patch/growable_array.dart:416)
#26     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#27     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#28     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:794)
<asynchronous suspension>
#29     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:654)
<asynchronous suspension>
#30     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...             56.1s
Failed to compile application.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.6.3 22G436 darwin-x64, locale en-MA)
    • Flutter version 3.19.1 on channel stable at /Users/bencherif/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bencherif/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • 55z5r4mn55kfj7oz • android-arm64  • Android 11 (API 30)
    • macOS (desktop)           • macos            • darwin-x64     • macOS 13.6.3 22G436 darwin-x64
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 122.0.6261.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@BenCherif 
Flutterfire related issues need to be reported in dedicated repo. Also, same issue is reported there in which you can follow-up.https://github.com/firebase/flutterfire/issues/12301

Closing from here.

**Comment by BenCherif** [comment]
i think is not the same issue because i got the error before the script run , not after the script run on chrome .the build failed because of this issue.

**Comment by miphik** [comment]
for me the same problem 
I have checked the changes from https://github.com/firebase/flutterfire/issues/12301 and it doesn't help

**Comment by BenCherif** [comment]
Unfortunately  even i update the dependencies to latest versions the issue still appears :
```

  firebase_core: ^2.25.5
  firebase_crashlytics: ^3.4.16
  firebase_messaging: ^14.7.17
```

**Comment by BenCherif** [comment]
i've found a temporary solution check this [https://github.com/firebase/flutterfire/issues/12353#issuecomment-1967361998](url)
thanks @nilsreichardt

**Comment by kevmoo** [comment]
It should be easy to do a patch release that just adds the right bits here. This is the beauty of extension types
