### ISSUE TITLE
Debug builds to IOS sim, but crashes Xcode on Archive

### ISSUE THREAD

**Issue by dgaedcke** [flutter/flutter#144176]
### Steps to reproduce

XCode -> Archive yields:

error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..6148: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:312)
#1      Source.getLocation (package:kernel/ast.dart:15021)
#2      Component.getLocation (package:kernel/ast.dart:14785)
#3      _getLocationInComponent (package:kernel/ast.dart:15236)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:630)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1774)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:400)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:290)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1657)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1599)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1804)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:118)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:587)
#18     compileToKernel (package:vm/kernel_front_end.dart:487)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

### Expected results

XCode should be able to build for archive, same as simulator

I actually switched to the beta branch because I was hitting similar / same issue on stable:
https://github.com/flutter/flutter/issues/138898

beta worked until the most recent upgrade

### Actual results

See code dump above

### Code sample

See code dump above

### Logs

error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..6148: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:312)
#1      Source.getLocation (package:kernel/ast.dart:15021)
#2      Component.getLocation (package:kernel/ast.dart:14785)
#3      _getLocationInComponent (package:kernel/ast.dart:15236)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:630)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1774)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:400)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:290)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1657)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1599)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1804)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:118)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:587)
#18     compileToKernel (package:vm/kernel_front_end.dart:487)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.20.0-1.2.pre, on macOS 14.2.1 23C71 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for dgiphone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by dam-ease** [comment]
Hello @dgaedcke.
Thanks for the report!
I tried reproducing on a new project but can't seem to reproduce the crash, does this occur on a new project on your end or only on existing projects?
I also, tested with https://github.com/flutter/flutter/issues/138898#issuecomment-1823060903 as well, but can't reproduce as well.
Could you help with more information on the reproducible steps?

**Comment by dgaedcke** [comment]
I have no idea how to reproduce this ... it's quite a large and complex project with many deps.   I just know it happened on stable;  but on device only ... not on the sim.  I switched to beta, and it ran on device until this latest beta upgrade.
What do you suggest?

**Comment by dam-ease** [comment]
Thanks for your response 
I’ll be labeling based on the logs shared in https://github.com/flutter/flutter/issues/144176#issue-2155212153 for more insights.
If you discover any reproducible steps, kindly share here to help address the issue better.

**Comment by dgaedcke** [comment]
Wanted to clarify ... even on the current version, I AM able to build to actual device (hw).  It's only when creating the archive for testflight that hit this crash:

`error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..6148: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:312)
#1      Source.getLocation (package:kernel/ast.dart:15021)
#2      Component.getLocation (package:kernel/ast.dart:14785)
#3      _getLocationInComponent (package:kernel/ast.dart:15236)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:630)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1774)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:400)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:290)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1657)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1599)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1804)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:118)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:587)
#18     compileToKernel (package:vm/kernel_front_end.dart:487)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
Failed to package /Users/dgaedcke/dev/Touchstone/TouchstoneFlutter.`

**Comment by jensjoha** [comment]
Does the offsets (approximately) match the byte length of a file (10068) which uses a part where, in the part, there is a ffi external field (or similar) at around byte offset 6148?

**Comment by jensjoha** [comment]
That should have been the other way around actually, the file size should be 6148 and the part should have a ffi thing at around byte offset 10068.

**Comment by dgaedcke** [comment]
Our code is not directly using FFI
I've searched for deps that use it and found:
Sentry;  Rive;  PackageInfoPlus; SharePlus
are the packages that are importing:
import 'package:ffi/ffi.dart';

Not sure if that helps ... I'm completely lost here and having trouble finding the beta branch from 2 weeks ago that let me get around this problem.

**Comment by dgaedcke** [comment]
thanks for the update ... I'm hitting it again;  can you tell me what branch I should use to circumvent the issue?  I'm guessing beta??

**Comment by mraleph** [comment]
I think it is only on main branch right, it was never cherry picked into beta or stable.
