### ISSUE TITLE
Cannot type in dialog

### ISSUE THREAD

**Issue by kevindmoore** [flutter/flutter#144172]
(NOTE: I did a flutter upgrade from  3.19.1 from 3.19.0, reran and it worked)

### Steps to reproduce

1. Start Flutter App in Intellij (not debugging)
2. Show dialog for text entry
3. Receive stack trace of error

### Expected results

Ability to enter text in text field

### Actual results

Nothing shows
====================================================================================================

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../providers.dart';

typedef NameCallBack = void Function(String?);

class NewItemDialog extends ConsumerStatefulWidget {
  final String title;
  final NameCallBack callBack;

  const NewItemDialog({super.key, required this.title, required this.callBack});

  @override
  ConsumerState createState() => _NewItemDialogState();
}

class _NewItemDialogState extends ConsumerState<NewItemDialog> {
  late TextEditingController textController;

  @override
  void initState() {
    super.initState();
    textController = TextEditingController(text: '');
  }

  @override
  void dispose() {
    textController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CallbackShortcuts(
      bindings: {
        const SingleActivator(LogicalKeyboardKey.keyY, meta: true): oKAction,
        const SingleActivator(LogicalKeyboardKey.keyC, meta: true): cancel,
      },
      child: AlertDialog(
        title: Text(widget.title),
        content: SizedBox(
          width: 150,
          height: 80,
          child: TextField(
            // decoration: const InputDecoration(border: InputBorder.none),
            keyboardType: TextInputType.text,
            autofocus: true,
            maxLines: 1,
            cursorColor: Colors.black,
            controller: textController,
            onSubmitted: (value) {
              oKAction();
            },
          ),
        ),
        actions: [
          TextButton(
              onPressed: () {
                cancel();
              },
              child: const Text('Cancel')),
          TextButton(
              onPressed: () {
                oKAction();
              },
              child: const Text('New')),
        ],
      ),
    );
  }

  void cancel() {
    final dialogState = ref.read(dialogStateProvider);
    dialogState.newItemDialogShowing = false;
    Navigator.pop(context);
    widget.callBack(null);
  }

  void oKAction() {
    final dialogState = ref.read(dialogStateProvider);
    dialogState.newItemDialogShowing = false;
    Navigator.pop(context);
    widget.callBack(textController.text);
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![2024-02-26_12-56-44](https://github.com/flutter/flutter/assets/1521266/cc850ac0-23b6-405e-8ca2-8a3fb6f98b86)

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#b941e(physicalKey: PhysicalKeyboardKey#f2ed2(usbHidUsage: "0x000700e3", debugName: "Meta Left"), logicalKey: LogicalKeyboardKey#e3a44(keyId: "0x200000106", keyLabel: "Meta Left", debugName: "Meta Left"), character: null, timeStamp: 540:07:08.776294)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 505 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:505:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:520:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:643:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1167:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  note_master git:(main) ✗ fdoctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2023.1)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
➜```

</details>

**Comment by kevindmoore** [comment]
This only occured the 1x and only from Intellij. I will say that Intellij gets messed up when I leave the computer asleep for awhile. (I have 3 monitors which might be causing a problem). We can close this as I've only seen it the 1x time. Restarting fixed the problem.
