### ISSUE TITLE
Spellcheck code uses context across an asynchronous gap

### ISSUE THREAD

**Issue by dvoloshyn** [flutter/flutter#144165]
### Steps to reproduce

I enabled spellcheck for `TextFormField`:
```
final spellCheck = kIsWeb
        ? null
        : SpellCheckConfiguration(
            spellCheckService: DefaultSpellCheckService(),
          );
```
and published to GooglePlay to get a pre-launch report

### Expected results

No exceptions are thrown

### Actual results

Crashlytics recorded "crashes" with the following stacktrace:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown .
       at State.context(framework.dart:958)
       at EditableTextState.buildTextSpan(editable_text.dart:5071)
       at EditableTextState._performSpellCheck(editable_text.dart:3843)
```
Quick review of the code lead me to the
```
final List<SuggestionSpan>? suggestions = await
        _spellCheckConfiguration
          .spellCheckService!
            .fetchSpellCheckSuggestions(localeForSpellChecking!, text);

      if (suggestions == null) {
        // The request to fetch spell check suggestions was canceled due to ongoing request.
        return;
      }

      spellCheckResults = SpellCheckResults(text, suggestions);
      renderEditable.text = buildTextSpan();
```

### Code sample

-

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on Manjaro Linux 6.7.4-2-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.19.1 on channel stable at /home/dvoloshyn/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/dvoloshyn/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.2+13)
    • All Android licenses accepted.
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @dvoloshyn.
I see this doesn't seem to reproduce locally. Ar

**Comment by dam-ease** [comment]
Thanks for sharing this!
I’m getting only script errors running this and following the steps.
Can you help with a screen recording and full logs you get?

**Comment by dvoloshyn** [comment]
Yes, the exception you are showing is what I'm getting in Crashlytics every time the automated tests are run in Google Play. And it's exactly what this lint rule is about: [use_build_context_synchronously](https://dart.dev/tools/linter-rules/use_build_context_synchronously)

Also, I started getting a similar but new stack trace that is, likely, also caused by concurrency issue.
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown .
       at TextPainter.computeLineMetrics(text_painter.dart:1599)
       at RenderEditable.startVerticalCaretMovement(editable.dart:2499)
       at _UpdateTextSelectionVerticallyAction.invoke(editable_text.dart:5661)
       at _OverridableContextAction.invokeDefaultAction(actions.dart:1814)
       at _OverridableActionMixin.invoke(actions.dart:1679)
       at Action._invoke(actions.dart:336)
       at ActionDispatcher.invokeActionIfEnabled(actions.dart:666)
       at ShortcutManager.handleKeypress(shortcuts.dart:874)
       at _ShortcutsState._handleOnKeyEvent(shortcuts.dart:1065)
       at _HighlightModeManager.handleKeyMessage(focus_manager.dart:2002)
       at KeyEventManager._dispatchKeyMessage(hardware_keyboard.dart:1103)
       at KeyEventManager.handleRawKeyMessage(hardware_keyboard.dart:1175)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:235)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:603)
```
Both exceptions seem to be triggered only during Google Play automated tests. And don't seem to cause any UI issues.
Even if they are harmless, how can I filter them out?

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample in https://github.com/flutter/flutter/issues/144165#issuecomment-1966124770

@dvoloshyn, please file another issue for the exception in https://github.com/flutter/flutter/issues/144165#issuecomment-2001879574

I think you should be able to filter out that exception in your crashlytics logs so it doesn't clog up the relevant logs. 

Labeling for further investigation. 

```
════════ Exception caught by widgets ═══════════════════════════════════════════
The following assertion was thrown while performing spell check:
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.

When the exception was thrown, this was the stack:
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:951:9)
framework.dart:951
#1      State.context (package:flutter/src/widgets/framework.dart:957:6)
framework.dart:957
#2      EditableTextState.buildTextSpan (package:flutter/src/widgets/editable_text.dart:5363:16)
editable_text.dart:5363
#3      EditableTextState._performSpellCheck (package:flutter/src/widgets/editable_text.dart:4116:29)
editable_text.dart:4116
<asynchronous suspension>
```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.3 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (12 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)     • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 122.0.6261.129

[!] Network resources
    ✗ A network error occurred while checking "https://cocoapods.org/": Operation timed out
    ✗ A network error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 2 categories.
```

```
[✓] Flutter (Channel master, 3.21.0-10.0.pre.52, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.21.0-10.0.pre.52 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9213b1f338 (81 minutes ago), 2024-03-19 06:24:25 -0400
    • Engine revision 4cec701f46
    • Dart version 3.4.0 (build 3.4.0-246.0.dev)
    • DevTools version 2.34.0-dev.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (6 available)
    • Pixel 7 (mobile)                • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.3.1 21D61
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 122.0.6261.129

[!] Network resources
    ✗ A network error occurred while checking "https://cocoapods.org/": Operation timed out
    ✗ A network error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 1 category.
```
</details>
