### ISSUE TITLE
 java.lang.UnsatisfiedLinkError at Runtime.loadLibrary0 crashes

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#144291]
A Google app has seen a cluster of new crashes with `UnsatisfiedLinkError` [in FlutterJNI.java](https://github.com/flutter/engine/blob/5c09604bd6de0755d48ca2a3ae645c9c36781b9d/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L146).

The message is:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
```

See Google internal bug b/327180104 for details.

The crashes only started a few days ago and they are affecting many Android API levels and devices, so it seems like it has been triggered by a change to the Flutter Android codebase. We don't have a reproduction, but just filing this to ask if there are any changes recently that might be expected to cause this issue.

<details>
<summary>Full stack trace</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{<REDACTED>}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

java.lang.RuntimeException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3970)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:291)
	at android.app.ActivityThread.main(ActivityThread.java:8134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: java.lang.RuntimeException
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:358)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:354)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:287)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:268)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:248)
	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:181)
	at com.google.mobile.flutter.contrib.background.FlutterEngineConfiguration.warmUpEngineAndSetRoute(FlutterEngineConfiguration.java:175)
	at com.google.mobile.flutter.contrib.background.FlutterEngineConfiguration.startDartIsolateAndSetRoute(FlutterEngineConfiguration.java:253)
	at <REDACTED>.FlutterEngineManager.startDartIsolate(FlutterEngineManager.java:60)
	at <REDACTED>.StandaloneFlutterActivityInitializer.initialize(StandaloneFlutterActivityInitializer.java:32)
	at <REDACTED>.StandaloneFlutterActivity.onCreate(StandaloneFlutterActivity.java:44)
	at android.app.Activity.performCreate(Activity.java:8338)
	at android.app.Activity.performCreate(Activity.java:8317)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1388)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	... 12 more
Caused by: java.util.concurrent.ExecutionException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:596)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:555)
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:243)
	... 24 more
Caused by: java.lang.UnsatisfiedLinkError
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:145)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:191)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:185)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:133)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:77)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:84)
	at com.google.common.labs.concurrent.FixedThreadPool$Worker.run(FixedThreadPool.java:564)
	at com.google.android.libraries.concurrent.AndroidExecutorsModule.lambda$withStrictMode$5(AndroidExecutorsModule.java:453)
	at com.google.android.libraries.concurrent.AndroidExecutorsModule$$ExternalSyntheticLambda10.run(AndroidExecutorsModule.java)
	at java.lang.Thread.run(Thread.java:1012)
	at com.google.android.libraries.concurrent.ManagedPriorityThread.run(ManagedPriorityThread.kt:34)
```

</details>

**Comment by math1man** [comment]
The crash actually started a few weeks ago, based on a version of Flutter built in late January.

**Comment by gmackall** [comment]
potentially related https://github.com/flutter/flutter/issues/83596

**Comment by math1man** [comment]
We restrict our app to device archictectures `x86_64`, `armeabi-v7a`, and `arm64-v8a`. We're seeing this crash on devices running those architectures, not on `x86` devices.

**Comment by reidbaker** [comment]
Something I didnt notice when looking at https://github.com/flutter/flutter/issues/83596 is this comment that shows slightly different error messages. 

https://github.com/flutter/flutter/issues/83596#issuecomment-1887758234

We should look to see what might cause android to have a different error message. Is it a different root cause or did they change the error text on newer versions of android for the same root cause.

**Comment by reidbaker** [comment]
Escalating to p0 because a similar issue has had an increase in traffic that we dismissed as misconfiguration. This impacts a 1p google customer and we can prove to ourselves if this is misconfiguration or a bug in flutter. 

Meaning it could impact a broad set of customers, definitely impacts a 1p customer and because g3 builds differently makes it unlikley that this is a build configuration only issue.

**Comment by gmackall** [comment]
> Something I didnt notice when looking at #83596 is this comment that shows slightly different error messages.
> 
> [#83596 (comment)](https://github.com/flutter/flutter/issues/83596#issuecomment-1887758234)
> 
> We should look to see what might cause android to have a different error message. Is it a different root cause or did they change the error text on newer versions of android for the same root cause.

The error messages seem to be the same across versions, it looks like they are coming from slightly different root causes. 

"Couldn't find..." seems to come from here: https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/lang/Runtime.java;l=1076?q=Runtime.java%20loadlibrary

While the "not found" version seems to come from a couple lines later, though this is harder to confirm https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/lang/Runtime.java;l=1081?q=Runtime.java%20loadlibrary

**Comment by gmackall** [comment]
It looks possible that this is a bug in Android itself? 

If the "not found" version of the error is indeed coming from the [`nativeLoad` line](https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/lang/Runtime.java;l=1090?q=Runtime.java%20loadlibrary), then it is coming right after logic where we confirm that we can find the relevent `.so` file. So that logic seems to be faulty in this case. 

This is just a guess at the moment, though, I'm going to look into the nativeload code itself now

**Comment by gmackall** [comment]
Also potentially related b/159618489

**Comment by gmackall** [comment]
Without a reproduction, it will be difficult to make any progress until we get more info from the additional logging - so I'm going to bump this back to a p1 for now

**Comment by gmackall** [comment]
This was fixed by https://github.com/flutter/engine/pull/55095. AFAICT the root cause here was only one of a couple of crash cases affecting the more overarching issue (https://github.com/flutter/flutter/issues/83596), so I won't mark that one as fixed, but closing this one as fixed.

**Comment by ldasilva-net** [comment]
> This was fixed by [flutter/engine#55095](https://github.com/flutter/engine/pull/55095). AFAICT the root cause here was only one of a couple of crash cases affecting the more overarching issue ([#83596](https://github.com/flutter/flutter/issues/83596)), so I won't mark that one as fixed, but closing this one as fixed.

Great @gmackall! Will a hotfix be sent with this change?

**Comment by FujiKinaga** [comment]
Thanks @gmackall ! Are there any plans to apply this change to 3.24.x via hotfix?

**Comment by reidbaker** [comment]
Hi, coworker of @gmackall and a release engineer here. The window for 3.24 cherry picks has closed (by months) so it will not be cherry picked. That said if you want the change can cant update to a newer flutter release with the change you can cherry pick it and ship with a custom engine. The change is pretty isolated and should not conflict.
