### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by CodingMartin** [flutter/flutter#14428]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = storage.googleapis.com, port = 53041

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:529)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:296)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:322)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:293)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:309)
#7      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:345)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:256)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:265)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:219)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#27     main (file:///C:/Dev/Flutter/dartsdk/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for C:\Dev\Flutter\dartsdk\bin\cache\artifacts\engine\windows-x64\dart-sdk\bin\dart.exe.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:86)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:215)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:236)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:236)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:211)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:93)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#25     main (file:///C:/Dev/Flutter/dartsdk/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by xster** [comment]
If you're in China, please follow https://github.com/flutter/flutter/wiki/Using-Flutter-in-China
