### ISSUE TITLE
flaky asan failures in Dart VM timeline

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#144394]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/618153/overview

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8754755997407041505/+/u/test:_test:_Host_Tests_for_host_debug_unopt/stdout

build host_debug_unopt and run:

```
out/host_debug_unopt/exe.unstripped/flutter_tester --force-multithreading --enable-impeller --use-test-fonts --icu-data-file-path=out/host_debug_unopt/icudtl.dat --flutter-assets-dir=out/host_debug_unopt/gen/flutter/lib/ui/assets --disable-asset-fonts 
 out/host_debug_unopt/gen/tracing_test.dart.dill
```

**Comment by a-siva** [comment]
//cc @derekxu16

**Comment by derekxu16** [comment]
The logs say

```
In test "Canvas.saveLayer emits tracing" Expect.deepEquals(expected: <5>, actual: <7>) fails.
#0      Expect._fail (package:expect/expect.dart:722:5)
#1      Expect.deepEquals (package:expect/expect.dart:552:7)
#2      equals.<anonymous closure> (package:async_helper/async_minitest.dart:164:14)
#3      expect (package:async_helper/async_minitest.dart:72:4)
#4      _testChromeFormatTrace (file:///b/s/w/ir/cache/builder/src/flutter/testing/dart/observatory/tracing_test.dart:38:3)
```

and also

```
[ERROR:flutter/shell/testing/tester_main.cc(658)] Unhandled exception
Exception: A test failed
```

So, I suspect that `flutter_tester` does not clean up the VM gracefully when it receives an unhandled exception, and the ASAN failure is just a symptom of the `Expect.deepEquals(expected: <5>, actual: <7>)` failure. So, the test should be changed to consistently produce N flow events instead of flakily producing either 5 or 7 flow events. If possible, maybe `flutter_tester` should also be changed to always clean up the VM gracefully? Does this seem like a fair assessment, @dnfield?

**Comment by dnfield** [comment]
Does this mean that writing timeline events allocates memory that's never freed until VM exit?

**Comment by derekxu16** [comment]
> Does this mean that writing timeline events allocates memory that's never freed until VM exit?

Correct.

**Comment by derekxu16** [comment]
@dnfield told me that this can be closed as WAI.

**Comment by zanderso** [comment]
I am still seeing asan failures in this test on CI. Flaky failures on CI are not WAI:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/631234/overview

**Comment by dnfield** [comment]
The actual problem here is that the `Canvas.saveLayer emits tracing` is flaky - it's not consistently emitting the expected number of tracing events.

**Comment by zanderso** [comment]
The flaking check of the number of flow events was added by @derekxu16 in https://github.com/flutter/engine/pull/42497. I'm going to try to disable only the failing check in https://github.com/flutter/engine/pull/51320.

**Comment by derekxu16** [comment]
This test used to not be flaky though, right? That means that something changed in the Engine recently that makes these calls (https://github.com/flutter/engine/blob/9196947bc68792e177a7c3cf03995f92f1165b8e/testing/dart/observatory/tracing_test.dart#L81-L103) record an unpredictable number of flow events. If that isn't a problem, then I think the solution to the flakiness is just to change the `expect(flowEventCount, 5);` lines in the test to `expect(flowEventCount, isPositive);`.
