### ISSUE TITLE
BackgroundIsolateBinaryMessenger.ensureInitialized raises Null check during a platform message response callback

### ISSUE THREAD

**Issue by KonstantinRr** [flutter/flutter#144342]
### Steps to reproduce

Our application is quite complex with multiple isolates working with each other. I couldn’t create a minimum reproducible example, but the nature of this bug (Flutter internal stack trace only) should still give a decent idea about what’s going wrong.

### Expected results

The error should not appear or a better error message should be given about what’s going wrong.

### Actual results

The application raises a lot of unhandled errors that come from platform callbacks i suppose.

```
 ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _TypeError was thrown during a platform message response callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
 #0      BackgroundIsolateBinaryMessenger.ensureInitialized.<anonymous closure> (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:56:34)
 #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
 (elided 6 frames from dart:async)
````

All Isolates being used execute BackgroundIsolateBinaryMessenger.ensureInitialized before performing any action. The issue seems to come from this line BackgroundIsolateBinaryMessenger.ensureInitialized:

```
portBinaryMessenger._completers
              .remove(identifier)!
              .complete(byteData);
```

### Code sample

<details open><summary>Code sample</summary>

There is no code sample since this is a Flutter only stack trace. I don’t know which code is causing it.
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown during a platform message response callback:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      BackgroundIsolateBinaryMessenger.ensureInitialized.<anonymous closure> (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:56:34)
flutter: #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
flutter: (elided 6 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
    • Flutter version 3.19.0 on channel stable at /opt/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /opt/flutter.
      Consider adding /opt/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/konstantinrr/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008101-001E4D201145001E • ios            • iOS 17.3.1 21D61
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.179
    ! Error: Browsing on the local area network for iPhone SE. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for antonis’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
    ! Error: Browsing on the local area network for G. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for G. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @KonstantinRr 
There was a proposal here at https://github.com/flutter/flutter/issues/137687 to handle null case but still need a reproduction sample to investigate it further. 

I would recommend you narrow down the issue and provide a minimal sample code to reproduce this so that we can verify the issue. Thanks!

**Comment by KonstantinRr** [comment]
Thanks for your support! I missed #137687 

I actually found the issue by now. It is quite simply because the completion handler in the Swift plugin (`result: @escaping FlutterResult`) was called twice for the same request. One time with an error and one time with data. That makes sense in the context of the error since the completion handler is removed after the first message has been handled.

I could probably build a reproducible example from here if needed. An `assert` would probably make sense at the null check to save hours of finding the bug and pinning it down.

**Comment by huycozy** [comment]
>I could probably build a reproducible example from here if needed. 

Thanks, it would be helpful!
