### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally with exit code 72:xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: /usr/bin/arch, OS error code: 72

### ISSUE THREAD

**Issue by susantp** [flutter/flutter#144479]
## Command
```
flutter build macos
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: /usr/bin/arch, OS error code: 72
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:30)
<asynchronous suspension>
#3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:117:41)
<asynchronous suspension>
#4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#11     run.<anonymous

**Comment by danagbemava-nc** [comment]
Hi @susantp, is xcode installed on your device? And have you run the following commands after installing xcode?

```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
```

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by susantp** [comment]
it had issue with xcode installation now it's resolved. Thank you @danagbemava-nc
