### ISSUE TITLE
[in_app_purchase_storekit] Native code returns wrong type for error code in `SKReceiptManager.retrieveReceiptData`

### ISSUE THREAD

**Issue by blaugold** [flutter/flutter#144595]
### Steps to reproduce

Call `SKReceiptManager.retrieveReceiptData` on a device without receipt data available.

### Expected results

A `PlatformException` is thrown.

### Actual results

A type error is thrown:

```
type 'int' is not a subtype of type 'String' in type cast

#0      InAppPurchaseAPI.retrieveReceiptData (package:in_app_purchase_storekit/src/messages.g.dart:810:38)
<asynchronous suspension>
#1      SKReceiptManager.retrieveReceiptData (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_receipt_manager.dart:22:13)
<asynchronous suspension>
#2      ShopClientImpl._dispatchPurchasedStoreKitTransactions (package:fourpics_native/shop/service/shop_client.dart:134:23)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.9 on channel stable at /Users/terwesten/fvm/versions/3.16.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (6 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/terwesten/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/terwesten/Library/Android/sdk
    • Java binary at: /Users/terwesten/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/terwesten/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
    • IntelliJ at /Users/terwesten/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Users/terwesten/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 78.1.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone von Gabriel (mobile) • 00008130-001C71EC36B8001C • ios            • iOS 17.3.1 21D61
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jmagman** [comment]
cc @LouiseHsu
