### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: ihttps:

### ISSUE THREAD

**Issue by AnuradaMishel** [flutter/flutter#144539]
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\Final Project\blood_donor\build\app\intermediates\flutter\debug/flutter_build.d --output D:\Final Project\blood_donor\build\app\intermediates\flutter\debug -dTargetFile=D:\Final Project\blood_donor\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC8wNDgxN2M5OWM5ZmQ0OTU2ZjI3NTA1MjA0ZjdlMzQ0MzM1ODEwYWVkLw== -dFlavor= -dAndroidArchs=android-x86 -dMinSdkVersion=19 -dIsAndroidLibrary=false debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: ihttps:
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1840:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2893:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2865:38)
#3      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:916:29)
#4      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:817:9)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:267:54)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:57:26)
<asynchronous suspension>
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:66:34)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
    • Flutter version 3.19.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (6 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34622.214
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.87.0)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 122.0.2365.66

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78666c8dc57e9f7548ca9f8dd0740fbf0c658dc9

**Comment by darshankawar** [comment]
@AnuradaMishel 
Can you check if there are any invalid chars in assets or in pubspec.yaml file ?
Couple of similar issues were fixed recently which may not be in stable yet, but should be available in latest master version:

https://github.com/flutter/flutter/issues/141211
https://github.com/flutter/flutter/issues/140092

Can you switch to latest master and run your scenario again to see if the same exception occurs or not ?
