### ISSUE TITLE
How to include navigation within a dialog?

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#14456]
## Steps to Reproduce

[Here is a repro](https://github.com/flutter/flutter/files/1693747/repro_navigation_within_dialog.zip)

I'm not actually sure whether this is a flutter issue, or a usage issue. Either way, I'd like to know how I go about having a dialog show a sequence of pages, any of which could return the result. At each step of the sequence, the code may decide no further steps are required, bailing early with a result. Or the user may be forced to go through all pages before the result is provided to the caller.

My attempts to achieve this via `showDialog`, `push` and `pop` have failed. When I attempt to push a second page onto the nav stack from within the dialog, I get:

```
I/flutter (31502): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (31502): The following assertion was thrown while handling a gesture:
I/flutter (31502): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 1052 pos 12: 'nextRoute is!
I/flutter (31502): PageRoute<dynamic>': is not true.
I/flutter (31502): 
I/flutter (31502): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31502): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31502): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31502):   https://github.com/flutter/flutter/issues/new
I/flutter (31502): 
I/flutter (31502): When the exception was thrown, this was the stack:
I/flutter (31502): #2      PopupRoute.didChangeNext (package:flutter/src/widgets/routes.dart:1052:12)
I/flutter (31502): #3      NavigatorState.push.<anonymous closure> (package:flutter/src/widgets/navigator.dart:930:18)
I/flutter (31502): #4      State.setState (package:flutter/src/widgets/framework.dart:1098:30)
I/flutter (31502): #5      NavigatorState.push (package:flutter/src/widgets/navigator.dart:922:5)
I/flutter (31502): #6      DialogPage1.build.<anonymous closure> (/data/user/0/com.example.repronavigationwithindialog/cache/repro_navigation_within_dialogALDMVL/repro_navigation_within_dialog/lib/main.dart:51:46)
I/flutter (31502): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:468:14)
I/flutter (31502): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:520:30)
I/flutter (31502): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (31502): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (31502): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (31502): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (31502): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (31502): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (31502): #15     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter (31502): #16     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (31502): #17     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (31502): #18     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (31502): #19     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (31502): #20     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
I/flutter (31502): #21     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter (31502): (elided 2 frames from class _AssertionError)
I/flutter (31502): 
I/flutter (31502): Handler: onTap
I/flutter (31502): Recognizer:
I/flutter (31502):   TapGestureRecognizer#22b7b(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (31502):   Offset(197.0, 37.0), sent tap down)
I/flutter (31502): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-AU, channel master)
    • Flutter version 0.0.21-pre.299 at C:\Users\kent\Repository\flutter
    • Framework revision 84580b545a (11 days ago), 2018-01-24 13:16:23 -0800
    • Engine revision d715860925
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.8d9d68751a505426eb5f59a9d29f103fde6bd474

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[√] Connected devices
    • Pixel • FA6AF0303979 • android-arm • Android 8.1.0 (API 27)
```

**Comment by kentcb** [comment]
I thought I'd take a crack at working around this for now (since it's blocking me) and have come up with (what I hope is) an interim solution. It involves subclassing `ModalRoute<T>` (since this avoids the assertion failing) and propagating any popped result along the chain to the original `showDialog` invocation.

[Here's the updated repro](https://github.com/flutter/flutter/files/1697135/repro_navigation_within_dialog.zip)

I'd appreciate some direction from the flutter team on this. Why isn't a `MaterialPageRoute` permissible in the context of a dialog? Indeed, if I simply comment out the assertion and try it with the above repro, it all seems to work fine.

**Comment by Hixie** [comment]
Looks like https://github.com/flutter/flutter/issues/4667

**Comment by Hixie** [comment]
Can you attach the main.dart file directly (assuming it's the only one with relevant code)? I'd rather not have to deal with the zip :-)

This is a bug that's actively on my list for the next month or two. It's probably just an oversight on our part.

**Comment by kentcb** [comment]
Here's `main.dart`:

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

Widget space(Widget w) =>
    new Container(
      padding: const EdgeInsets.all(10.0),
      child: w,
    );

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(body: new MyHomePage()),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var button = new RaisedButton(
      child: new Text(
        "Show Dialog"
      ),
      onPressed: () async {
        var scaffold = new Scaffold(
          body: new DialogPage1()
        );
        var result = await showDialog(context: context, child: scaffold);

        Scaffold.of(context).showSnackBar(
            new SnackBar(
                content: new Text("The result was " + (result ?? "<<NO RESULT>>"))
            )
        );
      });

    return new Center(child: button);
  }
}

class DialogPage1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var text = new Text("Here is step one of the dialog");
    var backButton = new RaisedButton(
        child: new Text("Back"),
        onPressed: () {
          Navigator.of(context).pop();
        });
    var nextStepButton = new RaisedButton(
      child: new Text("Next Step"),
      onPressed: () async {
        var result = await Navigator
            .of(context)
            //.push(new CustomRoute(child: new Scaffold(body: new DialogPage2())));
            .push(new MaterialPageRoute(builder: (context) => new Scaffold(body: new DialogPage2())));

        if (result != null) {
          Navigator.of(context).pop(result);
        }
      });

    return new Center(
      child: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          space(text),
          space(backButton),
          space(nextStepButton),
        ],
      )
    );
  }
}

class DialogPage2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var text = new Text("Here is step two of the dialog");
    var backButton = new RaisedButton(
        child: new Text("Back"),
        onPressed: () {
          Navigator.of(context).pop();
        });
    var completeButton = new RaisedButton(
        child: new Text("Complete with a Result"),
        onPressed: () {
          Navigator.of(context).pop("foo");
        });

    return new Center(
      child: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          space(text),
          space(backButton),
          space(completeButton),
        ],
      )
    );
  }
}

class CustomRoute<T> extends ModalRoute<T> {
  final Widget child;

  @override
  Color get barrierColor => Colors.green;

  @override
  bool get barrierDismissible => false;

  @override
  final String barrierLabel;

  CustomRoute({
    this.child
  });

  @override
  Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
    return new MediaQuery.removePadding(
      context: context,
      removeTop: true,
      removeBottom: true,
      removeLeft: true,
      removeRight: true,
      child: new Builder(
          builder: (BuildContext context) {
            return child;
          }
      ),
    );
  }

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    return new FadeTransition(
        opacity: new CurvedAnimation(
            parent: animation,
            curve: Curves.easeOut,
        ),
        child: child
    );
  }

  @override
  bool get maintainState => true;

  @override
  bool get opaque => false;

  @override
  Duration get transitionDuration => new Duration(milliseconds: 500);
}
```

**Comment by branflake2267** [comment]
This looks related. https://github.com/flutter/flutter/issues/13795

**Comment by branflake2267** [comment]
I'm leaving my workaround. Instead of calling showDialog from the ListTile onTap, in the FirebaseAnimated list, I call it from the page scaffold. I have a firebase stream wired up to listen for updates to the object, and when it's updated it shows the dialog. .

**Comment by long1eu** [comment]
Hi!

Same issue here but using bottom sheet. My fix is to first pop the sheet then push the new one.

**Comment by zoechi** [comment]
Seems to be fixed.
Closing as dup of #4667
