### ISSUE TITLE
Dragging a list that is currently handling an animateTo animation throws exception

### ISSUE THREAD

**Issue by VeryVito** [flutter/flutter#14452]
## Steps to Reproduce

The end goal is to create a scrolling list that automatically "snaps" to a given location based on the actual scroll position at which the user stops scrolling. This may not be the best solution (I'm new to Flutter), but here's the process by which I get the crash:

Wrap a ListView within a NotificationListener. Upon receiving a `UserScrollNotification` with `ScrollDirection.idle`, call the ScrollController's `animateTo()` method to scroll to another location (in the example here, I arbitrarily scroll to 10000.0 pixels).

### Sample code
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Scroller issue',
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final _controller = new ScrollController();

  bool _didGetNotification(ScrollNotification notification) {
    if (notification is UserScrollNotification) {
      if (notification.direction.toString() == "ScrollDirection.idle") {
        // We've stopped scrolling... now animate automatically to the 10000-pixel spot
        _controller.animateTo(10000.0, duration: const Duration(seconds: 2), curve: Curves.elasticOut);

        /* Above works great... unless the user tries to interact with the list WHILE it's
        // animating. In this case, you end up with:
        **********************************************************************************
        Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart':
          Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
        ********************************************************************************** */
      }
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new NotificationListener(
        onNotification: _didGetNotification,
        child: new ListView.builder(
          padding: new EdgeInsets.all(8.0),
          controller: _controller,
          itemExtent: 60.0,
          itemBuilder: (BuildContext context, int index) {
            return new Text('Item No. $index');
          },
        ),
      ),
    );
  }
}
```

It works great as long as the user only interacts with the ListView when it is idle, but if the user attempts to scroll/drag/touch the list _during_ the animateTo() process, the following exception is raised within the Flutter Scrollable package:

```
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
```

After this, the ListView becomes unresponsive.

I'm sure there's a better way to achieve what I'm trying to do, but the platform itself doesn't seem to recover from this. Figured I'd make a note of it. 

Thanks!

## Logs

Run your application with `flutter run` and attach all the log output.

```
    CADisplay.name = LCD;
    CADisplay.deviceName = PurpleMain;
    CADisplay.seed = 1;
    tags = 0;
    currentMode = <FBSDisplayMode: 0x604000097430; 375x667@2x (750x1334/2) 60Hz sRGB SDR>;
    safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
    nativeCenter = {375, 667};
    pixelSize = {750, 1334};
    bounds = {{0, 0}, {375, 667}};
    CADisplay = <CADisplay:LCD PurpleMain>;
}
Syncing files to device iPhone 6s...                  1.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone 6s is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 467 pos 12: '_hold == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:467:12)
#3      DragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:169:54)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:169:9)
#6      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
#7      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
(elided 4 frames from class _AssertionError and package dart:async)

Handler: onStart
Recognizer:
VerticalDragGestureRecognizer#6eafd
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 455 pos 12: '_drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 464 pos 12: '_drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_hold == null || _drag == null': is not true.

```

Run `flutter analyze` and attach any output of that command also.

```
Analyzing /Users/mfahy/Apps/list_view_attempts...
No issues found!
Ran in 6.5s
```

## Flutter Doctor
```
[  +21 ms] [/Users/mfahy/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/mfahy/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [/Users/mfahy/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/mfahy/flutter/] git log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
[        ] [/Users/mfahy/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 days ago
[        ] [/Users/mfahy/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.0.21-0-g2e449f06f
[ +473 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[+1263 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[ +452 ms] [✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel alpha)
[   +1 ms]     • Flutter version 0.0.21 at /Users/mfahy/flutter
[        ]     • Framework revision 2e449f06f0 (5 days ago), 2018-01-29 14:26:51 -0800
[        ]     • Engine revision 6921873c71
[        ]     • Tools Dart version 2.0.0-dev.16.0
[        ]     • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a
[ +130 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +218 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[  +98 ms] java -version
[  +87 ms] [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[        ]     • Android SDK at /Users/mfahy/Library/Android/sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-27, build-tools 27.0.3
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[+1189 ms] DevToolsSecurity -status
[  +49 ms] Developer mode is currently enabled.
[        ] python -c import six
[ +126 ms] idevice_id -h
[  +10 ms] idevice_id -h
[   +9 ms] idevice_id -l
[  +28 ms] 5a62f0e8de345b9794b9a61c9bfcd02026c68a86
[   +1 ms] idevicename
[  +44 ms] ios-deploy --version
[  +54 ms] ios-deploy --version
[  +16 ms] 1.9.2
[   +1 ms] ios-deploy --version
[  +33 ms] ios-deploy --version
[  +21 ms] 1.9.2
[   +2 ms] pod --version
[ +905 ms] pod --version
[ +605 ms] 1.3.1
[   +2 ms] pod --version
[ +533 ms] 1.3.1
[   +1 ms] [-] iOS toolchain - develop for iOS devices (Xcode 9.2)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 9.2, Build version 9C40b
[        ]     ✗ Verify that all connected devices have been paired with this computer in Xcode.
                 If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
                 To update, run:
                   brew uninstall --ignore-dependencies libimobiledevice
                   brew install --HEAD libimobiledevice
                   brew install ideviceinstaller
[        ]     • ios-deploy 1.9.2
[        ]     • CocoaPods version 1.3.1
[   +2 ms] [✓] Android Studio (version 3.0)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[   +6 ms] /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[ +249 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[        ] 2017.3.4
[  +79 ms] [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[        ]     • Flutter plugin version 21.2.3
[        ]     • Dart plugin version 173.4548.30
[   +4 ms] /Users/mfahy/Library/Android/sdk/platform-tools/adb devices -l
[  +17 ms] Exit code 0 from: /Users/mfahy/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +8 ms] idevice_id -h
[  +82 ms] which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +4 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +218 ms] [✓] Connected devices
[        ]     • ViPhone 6S • 5a62f0e8de345b9794b9a61c9bfcd02026c68a86 • ios • iOS 11.3
[        ]     • iPhone 6s  • 6F36E8FD-E570-453E-B943-8243E4FAEDD6     • ios • iOS 11.2 (simulator)
[  +21 ms] "flutter doctor" took 6,972ms.
[  +42 ms] ensureAnalyticsSent: 38ms
[   +2 ms] exiting with code 0
```

Hope this helps! Thanks!

**Comment by Hixie** [comment]
That's definitely a bug.

That said, the usual way to do this kind of thing is to create custom ScrollPhysics. If you look for examples of classes that extend ScrollPhysics in the framework, you may find some cases that do roughly what you want that you can crib from.

**Comment by VeryVito** [comment]
Thanks, @Hixie. I figured ScrollPhysics would be the "right" way to do it. I just haven't wrapped my head around the idea yet, and stumbled across this in the mean time. Glad to see it's not just me.

**Comment by Norbert515** [comment]
@VeryVito I'm facing the same issue, did you manage to build something using the ScrollPhysics?

**Comment by Piinks** [comment]
For discussion:
When the user interrupts the animation, does anyone have an expected behavior?

Should the user be able to interrupt/cancel the animation? Or should the user gesture be ignored until the animation is over?

_Or_ would it be beneficial to have both options and be able to specify which of these behaviors you would like to have?

**Comment by Hixie** [comment]
We should ask the designers.

**Comment by Piinks** [comment]
From the documentation for ScrollController.animateTo :

> An animation will be interrupted whenever the user attempts to scroll manually, or whenever another activity is started, or whenever the animation reaches the edge of the viewport and attempts to overscroll. 

I'm going to proceed with fulfilling this contract, as I understand it to mean user interaction would interrupt/cancel the animation.
I'll then see if we can expand from there on other opportunities to improve this experience after checking in with designers. :)

**Comment by Piinks** [comment]
After exploring different solutions in #37267, scroll notifiers do not seem to be the most robust solution for initiating scroll activities. There are several scroll notifications that are dispatched during the course of an activity, leaving open the opportunity to throw an assert like this when incomplete/new activities clash. I'm working on finding a different approach to initiating this animation, and will document it. :)
Altering the milestone and primary goal to reflect this shift.

**Comment by Piinks** [comment]
I'm not currently working on this so I'm removing my assignment in case someone else would like to take a look. :)

**Comment by VladyslavBondarenko** [comment]
Still persists. Flutter master v1.16.3-pre.56

**Comment by chunhtai** [comment]
removing crash label because this is more of improper use of the API, Instead we should provide document example it

**Comment by antonygunawan94** [comment]
any update on this?

**Comment by realappie** [comment]
Having to use an ugly hack for this that interrupts the animation and requires the user to release the touch and grab the scrollable list again to continue scrolling.

![](https://i.gyazo.com/51edad62aa7e0348e3ef6545db2abcbb.gif)

Hack
https://github.com/flutter/flutter/issues/12712#issuecomment-663618605

![](https://puu.sh/GGGoq/bf2520b1d5.png)

I see @chunhtai talked about documentation, was there any documentation made for this? I'm sure an example snippet of how to do this would also suffice for many people here.

**Comment by chunhtai** [comment]
We have not updated the documentation yet. I do not have any update. maybe @Piinks can provide more insight?

**Comment by clragon** [comment]
I am currently experiencing this problem. 
I assume there is no recommended solution yet?

**Comment by vytautas-pranskunas-** [comment]
Any updates on this?

**Comment by zcznb** [comment]
My solution is wrap with a gesture intercept widget just like  IgnorePointer. when the scroll animation is in progress, i will intercept user's gesture.
Code:
` NotificationListener<ScrollNotification>(
      onNotification: _handlerScrollNotification,
      child: ScrollConfiguration(
        behavior: NullBehavior(),
        child: IgnorePointer(
          ignoring: !isScrollEnd,
          child: widget.child,
        ),
      ),
    )`
isScrollEnd is use to determine whether  the animation ends or not
`bool _handlerScrollNotification(ScrollNotification scrollNotification) {
    if (scrollNotification is ScrollStartNotification) {
      isScrollEnd = false;
    }
    if (scrollNotification is ScrollEndNotification) {
      isScrollEnd = true;
    }
    if (scrollNotification is UserScrollNotification) {
      if (isScrollEnd) {
      //TODO
      }
    }
    setState(() {});
    return true;
  }`

**Comment by SilverFruity** [comment]
I think this problem has been fixed by https://github.com/flutter/flutter/pull/69732

**Comment by guplem** [comment]
This just happened to me, so I don't know if that fix is applied yet, but I am using Flutter 2.8.1.

I was trying to do something very similar to [this](https://github.com/flutter/flutter/issues/91166#issuecomment-936415793) from #91166

**Comment by guplem** [comment]
> removing crash label because this is more of improper use of the API, Instead we should provide document example it

Why is it an improper use of the API? Isn't it normal to animate something and expect user input at any time?

**Comment by carlos-enzo** [comment]
June 2022 and this is still an issue, any workaround?

**Comment by feinstein** [comment]
I think I got this behavior, but I am not trying to animate the list in any fancy way.

I created a windows app with a `ListView` with a bunch of clickable Cards. I am using a `Ticker` to animate its scroll, so it appears as an infinite scrolling list, like the breaking news on TV do.

When I use `animateTo` to make the list move at each tick, the cards don't accept any click or show any pointer animations for the `InkWell`. If I use `jumpTo` the clicks work and I can see the material animations on the card.

**Comment by erisanolasheni** [comment]
I need this is not the best solution guys, but what I tried to do is ignore user interaction when scrolling is not done. In my scroll controller it looked like:
```dart
_doneScrolling = true;
_scrollController.position.isScrollingNotifier.addListener(() {
// immediately before the animation
setState((){
_doneScrolling = false;
});
              _scrollController
                  .animateTo(
                      _animateWidth,
                      duration: kThemeAnimationDuration * 2,
                      curve: Curves.easeInOutCubicEmphasized)
                  .then((value) => 
                        setState(() => _doneScrolling  = true));
});

// then I wrapped with Scroll view widget with AbsorbPointer
AbsorbPointer(
absorbing: !_doneScrolling,
child: SinggleChildScrollView(
...)
):

```

**Comment by exaby73** [comment]
This issue is replicable on `Master (3.10.0-7.0.pre.46)`. Updating labels to reflect the same

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.10.0-7.0.pre.46, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
    • Flutter version 3.10.0-7.0.pre.46 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59230759be (22 minutes ago), 2023-04-19 02:39:50 -0400
    • Engine revision 609f9d5364
    • Dart version 3.1.0 (build 3.1.0-15.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 112.1.50.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by a-voyager** [comment]
any better solution?

**Comment by mu7ammadkamel** [comment]
Any updates?

**Comment by Gofive** [comment]
Any updates on this?No one is paying attention to this issue?

**Comment by Piinks** [comment]
Per our wiki on [issue hygiene](https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-issues-or-prs):

Do not add "me too" or "same" or "is there an update" comments to issues or PRs

Continued posts like this are not constructive and will result in restrictions to make further comments in this repository.

**Comment by meisocafe** [comment]
Two possible solutions for this. The problem is originated because animateTo triggers the listener again, so you can use the future it provides to avoid this behavior:
`      if (!_isAnimatingScroll) {
        _isAnimatingScroll = true;
        sController
            .animateTo(position, duration: const Duration(milliseconds: 100), curve: Curves.linear)
            .then((_) => {_isAnimatingScroll = false});
      }
`

Another solution is to wrap the scroll widget with a `GestureDetector` and use the `onPanEnd` callback instead. Note thought that this behaves differently, the scroll notifier will trigger when the scrolling physics stop, while the `GestureDetector` will fire the event when the finger is released.

**Comment by thanhdatvo** [comment]
We encounter this problem today

```
I/flutter ( 3524): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 3524): │ 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 831 pos 12: '_hold == null': is not true.
I/flutter ( 3524): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3524): │ #0   _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
I/flutter ( 3524): │ #1   _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter ( 3524): │ #2   ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:831:12)
I/flutter ( 3524): │ #3   _VerticalOuterDimensionState._handleDragDown (package:flutter/src/widgets/scrollable.dart:2141:30)
I/flutter ( 3524): │ #4   DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:734:51)
I/flutter ( 3524): │ #5   GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
I/flutter ( 3524): │ #6   DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:734:7)
I/flutter ( 3524): │ #7   DragGestureRecognizer._addPointer (package:flutter/src/gestures/monodrag.dart:388:9)
I/flutter ( 3524): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 3524): │ ⛔ FlutterError.onError
I/flutter ( 3524): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
