### ISSUE TITLE
couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by taoyaolaile** [flutter/flutter#144527]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fuse.fuseprovn/com.******.******.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.******.******-MndHH41AdD-n0oQeY524Ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.******.******-MndHH41AdD-n0oQeY524Ug==/lib/arm64, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6536)
       at java.lang.reflect.Method.invokeImpl(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:411)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
![image](https://github.com/flutter/flutter/assets/18184128/b6d2b83e-f957-4ae3-9bbe-62612d4b6bfc)

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/83596.
