### ISSUE TITLE
`Mac framework_tests_impeller` is super flaky on `widgets.shader_mask.bounds.matches_top_left`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#144555]
It has been flaky 10 times in recent commits:

Example builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_impeller/126/overview

```
10:41 +14681 ~142: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/shader_mask_test.dart: Bounds rect includes offset visual inspection                                                 
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SkiaException was thrown while running async test code:
Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org// to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash d051cff927d4ce28ab72215e43a2fb2b for test
widgets.shader_mask.bounds.matches_top_left
Expectation for test: 084ddbbcf1a5fc0c30e4c871a29ee072 (positive)
Expectation for test: 09c634d298e4513100f38d957eaaf179 (positive)
Expectation for test: 16fe16898a0e94260e913f2ecf55beaf (positive)
Expectation for test: 52f8861d4f9e3b8ef600c63626d74bec (positive)
Expectation for test: 56afb5fedead66f585d0db73be201a1c (positive)
Expectation for test: 85543c08c4e66a2fc737c14b6c68763b (positive)
Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dwidgets.shader_mask.bounds.matches_top_left%26source_type%3Dflutter&digest=d051cff927d4ce28ab72215e43a2fb2b


stderr: Test: widgets.shader_mask.bounds.matches_top_left FAIL


result-state.json: No result file found.

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens/skia_client.dart:252:7)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
#3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
<asynchronous suspension>
<asynchronous suspension>
#5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/shader_mask_test.dart:107:5)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1018:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════

10:41 +14681 ~142 -1: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/shader_mask_test.dart: Bounds rect includes offset visual inspection [E]                                          
  Test failed. See exception logs above.
  The test description was: Bounds rect includes offset visual inspection
```

**Comment by jonahwilliams** [comment]
Disabled in https://github.com/flutter/flutter/pull/144573, keeping this open for tracking.
