### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xc3 (at offset 92)

### ISSUE THREAD

**Issue by peace2knowledge** [flutter/flutter#14462]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xc3 (at offset 92)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:762)
#11     _StreamController._add (dart:async/stream_controller.dart:638)
#12     _StreamController.add (dart:async/stream_controller.dart:584)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1654)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:762)
#20     _StreamController._add (dart:async/stream_controller.dart:638)
#21     _StreamController.add (dart:async/stream_controller.dart:584)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1231)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale zh-CN, channel alpha)
    • Flutter version 0.0.21-pre.250 at D:\flutter
    • Framework revision 37e1684825 (3 weeks ago), 2018-01-16 23:19:40 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • MI 6 • dcf581ed • android-arm • Android 7.1.1 (API 25)

```

**Comment by WinterSmileSB101** [comment]
pls make sure that the path of your install flutter can be  encoding to UTF-8.

**Comment by Hixie** [comment]
We believe we've resolved this now; please let us know if you have any troubles after the next beta release.

**Comment by realluhui** [comment]
i have same problem.   if you write storeFile=<key.jks> in key.properties file, you get this error.  so you must write storeFile = key.jks.
