### ISSUE TITLE
[tool_crash] _TypeError: (#0      NativeAssets._buildIOS (package:flutter_tools/src/build_system/targets/native_assets.dart:290:68))

### ISSUE THREAD

**Issue by rushabhnavadiya** [flutter/flutter#144667]
## Command
```
flutter assemble --no-version-check --output=/Users/bhavinijain/Library/Developer/Xcode/DerivedData/Runner-cwovbipychdivxhfcxuauyrahjws/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=arm64 x86_64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dAction=install -dFrontendServerStarterPath= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=5AA2F119FA564D3E26F58D138EF009FB95F2A9E6 release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      NativeAssets._buildIOS (package:flutter_tools/src/build_system/targets/native_assets.dart:290:68))
```
#0      NativeAssets._buildIOS (package:flutter_tools/src/build_system/targets/native_assets.dart:290:68)
#1      NativeAssets.build (package:flutter_tools/

**Comment by danagbemava-nc** [comment]
Hi @rushabhnavadiya, can we get the full crash log with the output of `flutter doctor -v`?
