### ISSUE TITLE
Removing banner during dispose

### ISSUE THREAD

**Issue by NobodyForNothing** [flutter/flutter#144833]
### Steps to reproduce

1. Run the code sample
2. open banner page
3. show banner
4. go back one screen
5. see issue in the log

### Expected results

I expect that the banner is either automatically cleared when I leave the screen or is removable during the dispose phase.

### Actual results

The banner stays on screen and an "unactionable" exception is logged.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(
          builder: (context) {
            return TextButton(
              child: const Text('open banner page'),
              onPressed: () => Navigator.push(context, MaterialPageRoute(
                builder: (context) => const BannerScreen())),
            );
          }
        ),
      ),
    );
  }
}

class BannerScreen extends StatefulWidget {
  const BannerScreen({super.key});

  @override
  State<BannerScreen> createState() => _BannerScreenState();
}

class _BannerScreenState extends State<BannerScreen> {
  ScaffoldMessengerState? msgr;

  @override
  void dispose() {
    msgr?.removeCurrentMaterialBanner();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    msgr = ScaffoldMessenger.of(context);
    return Scaffold(
      body: Column(
        children: [
          TextButton(
            child: const Text('show banner'),
            onPressed: () => ScaffoldMessenger.of(context).showMaterialBanner(const MaterialBanner(
              content: Text('Banner'),
              actions: [
                IconButton(
                  onPressed: null,
                  icon: Icon(Icons.flutter_dash)
                )
              ]
            ))
          ),
          TextButton(
            child: const Text('hide banner'),
            onPressed: () => ScaffoldMessenger.of(context).removeCurrentMaterialBanner(),
          ),
          TextButton(
            child: const Text('go back one screen'),
            onPressed: () => Navigator.pop(context),
          ),
        ],
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
setState() or markNeedsBuild() called when widget tree was locked.

This AnimatedBuilder widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: AnimatedBuilder
  listenable: AnimationController#e3ba7(⏮ 0.000; paused; for MaterialBanner)➩Cubic(0.40, 0.00, 0.20, 1.00)
  state: _AnimatedState#65ce7
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5044:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5054:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
#3      _AnimatedState._handleChange (package:flutter/src/widgets/transitions.dart:129:5)
#4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#5      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:395:5)
#6      ScaffoldMessengerState.removeCurrentMaterialBanner (package:flutter/src/material/scaffold.dart:528:32)
#7      _BannerScreenState.dispose (package:bug_banner/main.dart:41:11)
#8      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689:11)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#68     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#107    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6744:14)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2074:7)
#119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2072:13)
#121    ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#122    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2085:25)
#123    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2764:15)
#124    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3174:7)
#125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:992:19)
#126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#129    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#130    _invoke (dart:ui/hooks.dart:312:13)
#131    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#132    _drawFrame (dart:ui/hooks.dart:283:31)
The AnimationController notifying listeners was: AnimationController#e3ba7(⏮ 0.000; paused; for MaterialBanner)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.19.0-0.4.pre, on Garuda Linux 6.7.9-AMD-znver3, locale en_US.UTF-8)
    • Flutter version 3.19.0-0.4.pre on channel beta at /home/derdilla/bin/apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7e7d46a04 (5 weeks ago), 2024-02-02 08:21:06 -0600
    • Engine revision 98820f0a77
    • Dart version 3.3.0 (build 3.3.0-279.3.beta)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/derdilla/Android/Sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /home/derdilla/bin/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/bin/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/derdilla/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/derdilla/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 77.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Garuda Linux 6.7.9-AMD-znver3

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by maRci002** [comment]
You shoud call `ScaffoldMessengerState.removeCurrentMaterialBanner` in the next frame.

```dart
import 'package:flutter/scheduler.dart';
// ...

  @override
  void dispose() {
    SchedulerBinding.instance.addPostFrameCallback((timeStamp) => msgr?.removeCurrentMaterialBanner());
    super.dispose();
  }

// ...
```

**Comment by NobodyForNothing** [comment]
I agree that changing the time when the banner is a viable solution.

I also just realized that the behavior I wondered about earlier is stated in the [showMaterialBanner](https://api.flutter.dev/flutter/material/ScaffoldMessengerState/showMaterialBanner.html) documentation.
