### ISSUE TITLE
[Android] ImageReader.Builder format might need to match source for videos?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#144800]
While the emulator doesn't work for me, I did get an exception that the image reader format that we set to ImageFormat.PRIVATE didn't match the expected format ImageFormat.YUV_420_888. 

https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java#L824

I'm not sure if this is a real error or not. And hard coding the value does not fix the problems in my emulator.

**Comment by jonahwilliams** [comment]
```
E/AndroidRuntime(18932): java.lang.UnsupportedOperationException: The producer output buffer format 0x23 doesn't match the ImageReader's configured buffer format 0x1.
E/AndroidRuntime(18932): 	at android.media.ImageReader.nativeImageSetup(Native Method)
E/AndroidRuntime(18932): 	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:597)
E/AndroidRuntime(18932): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:652)
E/AndroidRuntime(18932): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:541)
E/AndroidRuntime(18932): 	at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer$PerImageReader.lambda$new$0$io-flutter-embedding-engine-renderer-FlutterRenderer$ImageReaderSurfaceProducer$PerImageReader(FlutterRenderer.java:464)
E/AndroidRuntime(18932): 	at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer$PerImageReader$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
E/AndroidRuntime(18932): 	at android.media.ImageReader$1.run(ImageReader.java:947)
E/AndroidRuntime(18932): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(18932): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18932): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(18932): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(18932): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
E/AndroidRuntime(18932): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(18932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

**Comment by jonahwilliams** [comment]
maybe this is because I changed it from PRIVATE briefly...
