### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by qinjw128** [flutter/flutter#145048]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      OhosSdk.initSdkVersionMap (package:flutter_tools/src/ohos/ohos_sdk.dart:122:37)
#5      OhosSdk.localOhosSdk.findOhosHomeDir (package:flutter_tools/src/ohos/ohos_sdk.dart:90:9)
#6      OhosSdk.localOhosSdk (package:flutter_tools/src/ohos/ohos_sdk.dart:102:33)
#7      HarmonySdk.locateHarmonySdk (package:flutter_tools/src/ohos/ohos_sdk.dart:46:38)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#14     harmonySdk (package:flutter_tools/src/globals.dart:68:39)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:159:26)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#20     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#21     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#22     ApplicationPackageFactory.instance (package:flutter_tools/src/application_package.dart:10:61)
#23     FlutterCommand.setupApplicationPackages (package:flutter_tools/src/runner/flutter_command.dart:1212:55)
#24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1418:5)
```
```
encountered exception: FormatException: Invalid radix-10 number (at character 1)
hms
^


#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      OhosSdk.initSdkVersionMap (package:flutter_tools/src/ohos/ohos_sdk.dart:122:37)
#5      OhosSdk.localOhosSdk.findOhosHomeDir (package:flutter_tools/src/ohos/ohos_sdk.dart:90:9)
#6      OhosSdk.localOhosSdk (package:flutter_tools/src/ohos/ohos_sdk.dart:102:33)
#7      HarmonySdk.locateHarmonySdk (package:flutter_tools/src/ohos/ohos_sdk.dart:46:38)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     harmonySdk (package:flutter_tools/src/globals.dart:68:39)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:139:28)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     ohosValidator (package:flutter_tools/src/ohos/ohos_doctor.dart:30:45)
#19     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:134:7)
#20     Doctor.validators (package:flutter_tools/src/doctor.dart:231:47)
#21     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:237:45)
#22     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:741:60)
#23     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
#24     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:745:53)
#25     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart:738:47)
#26     DoctorText.piiStrippedText (package:flutter_tools/src/doctor.dart)
#27     CrashReporter.informUser (package:flutter_tools/src/reporting/crash_reporting.dart:92:32)
#28     _handleToolError (package:flutter_tools/runner.dart:169:36)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#30     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment]
I'm not sure why `harmonySdk` appears in the stack trace. I guess the error started at:

https://github.com/flutter/flutter/blob/ba393198430278b6595976de84fe170f553cc728/packages/flutter_tools/lib/src/doctor.dart#L134

Which Flutter version did you download/pull? 

Could you share the output of `flutter doctor -vv` (double `v`). If the log is too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it. Thanks!
