### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference

### ISSUE THREAD

**Issue by SmilingFarood** [flutter/flutter#145083]
### Steps to reproduce

I am using Flutter to design an application for a POS terminal. I have initially created an application using same SDK with Kotlin on android and the application works perfectly. I've now decided to use MethodChannel to extend my Kotlin code to the Flutter application in order to be able to give it an interface and I have not being able to get it to work as expected.

NOTE: I have used `applicationContext` and `this@MainActivity` in place of my context when initialising but both still didn't work. I've also tried to do my initialising under `onCreate` method but still not working

### Expected results

The POS terminal is supposed to print through its printer

### Actual results

```
I/PrintTemplate( 9049): view == null
E/MethodChannel#samples.flutter.dev/battery( 9049): Failed to handle method call
E/MethodChannel#samples.flutter.dev/battery( 9049): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:502)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.view.View.<init>(View.java:5320)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.view.View.<init>(View.java:5470)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.widget.TextView.<init>(TextView.java:996)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.widget.TextView.<init>(TextView.java:990)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.widget.TextView.<init>(TextView.java:986)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.widget.TextView.<init>(TextView.java:982)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.topwise.cloudpos.aidl.printer.PrnTextView.<init>(PrnTextView.java:12)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.topwise.cloudpos.aidl.printer.PrintTemplate.getPrnTextView(PrintTemplate.java:259)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.topwise.cloudpos.aidl.printer.PrintTemplate.add(PrintTemplate.java:81)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.uniswitch.octopus.MainActivity.useThePrinter(MainActivity.kt:123)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.uniswitch.octopus.MainActivity.configureFlutterEngine$lambda-0(MainActivity.kt:83)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.uniswitch.octopus.MainActivity.$r8$lambda$WTepWXtvJEBEx0VakVxbQpPmg08(Unknown Source:0)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.uniswitch.octopus.MainActivity$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:2)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at android.app.ActivityThread.main(ActivityThread.java:7723)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:618)
E/MethodChannel#samples.flutter.dev/battery( 9049): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/flutter ( 9049): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Context.isUiContext()' on a null object reference
E/flutter ( 9049): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:502)
E/flutter ( 9049): 	at android.view.View.<init>(View.java:5320)
E/flutter ( 9049): 	at android.view.View.<init>(View.java:5470)
E/flutter ( 9049): 	at android.widget.TextView.<init>(TextView.java:996)
E/flutter ( 9049): 	at android.widget.TextView.<init>(TextView.java:990)
E/flutter ( 9049): 	at android.widget.TextView.<init>(TextView.java:986)
E/flutter ( 9049): 	at android.widget.TextView.<init>(TextView.java:982)
E/flutter ( 9049): 	at com.topwise.cloudpos.aidl.printer.PrnTextView.<init>(PrnTextView.java:12)
E/flutter ( 9049): 	at com.topwise.cloudpos.aidl.printer.PrintTemplate.getPrnTextView(PrintTemplate.java:259)
E/flutter ( 9049): 	at com.topwise.cloudpos.aidl.printer.PrintTemplate.add(PrintTemplate.java:81)
E/flutter ( 9049): 	at com.uniswitch.octopus.MainActivity.useThePrinter(MainActivity.kt:123)
E/flutter ( 9049): 	at com.uniswitch.octopus.MainActivity.configureFlutterEngine$lambda-0(MainActivity.kt:83)
E/flutter ( 9049): 	at com.uniswitch.octopus.MainActivity.$r8$lambda$WTepWXtvJEBEx0VakVxbQpPmg08(Unknown Source:0)
E/flutter ( 9049): 	at com.uniswitch.octopus.MainActivity$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:2)
E/flutter ( 9049): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 9049): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 9049): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 9049): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 9049): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 9049): 	at android.app.ActivityThread.main(ActivityThread.java:7723)
E/flutter ( 9049): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9049): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:618)
E/flutter ( 9049): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
E/flutter ( 9049): )
E/flutter ( 9049): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 9049): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 9049): <asynchronous suspension>
E/flutter ( 9049): #2      _MyHomePageState.usePrinter (package:octopus/main.dart:83:20)
E/flutter ( 9049): <asynchronous suspension>
E/flutter ( 9049): 
D/ViewRootImpl( 9049): setSurfaceViewCreated, created:false
V/PhoneWindow( 9049): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@9507767, this = DecorView@c4e6914[MainActivity]
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const platform = MethodChannel('samples.flutter.dev/battery');
  int _counter = 0;
  String _batteryLevel = 'Unknown battery level.';

  Future<void> _getBatteryLevel() async {
    String batteryLevel;
    try {
      final result = await platform.invokeMethod<int>('getBatteryLevel');
      batteryLevel = 'Battery level at $result% .';

      setState(() {
        _batteryLevel = batteryLevel;
      });
    } on PlatformException catch (e) {
      log('There is an error ${e.message}');
      batteryLevel = "Failed to get battery level: '${e.message}'.";
    } catch (e) {
      log('unknown error ${e.toString()}');
    }
  }

  Future<void> usePrinter() async {
    final result = await platform.invokeMethod(
      'usePrinter',
      {
        'firstname': 'Abdul',
        'lastname': 'Olatunde',
      },
    );
  }

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: _getBatteryLevel,
              child: const Text('Get battery Level'),
            ),
            ElevatedButton(
              onPressed: usePrinter,
              child: const Text('Print'),
            ),
            Text(_batteryLevel),
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

My Kotlin code

```kotlin
package com.example.test

import android.content.ContextWrapper
import android.content.Intent
import android.content.IntentFilter
import android.os.BatteryManager
import android.os.Build
import android.os.Build.VERSION
import android.os.Build.VERSION_CODES
import android.os.Bundle
import android.os.RemoteException
import android.util.Log
import com.topwise.cloudpos.aidl.printer.AidlPrinter
import com.topwise.cloudpos.aidl.printer.AidlPrinterListener
import com.topwise.cloudpos.aidl.printer.PrintTemplate
import com.topwise.cloudpos.aidl.printer.TextUnit
import com.topwise.cloudpos.service.DeviceServiceManager
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import java.text.SimpleDateFormat
import java.util.Date


private var printRunning = false

class MainActivity : FlutterActivity() {
    private val CHANNEL = "samples.flutter.dev/battery"
    private var printerDev: AidlPrinter? = null
    private lateinit var mListen: AidlPrinterListener

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

    }


    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        DeviceServiceManager.getInstance().init(this@MainActivity)
        printerDev = DeviceServiceManager.getInstance().printManager
        mListen = object : AidlPrinterListener.Stub() {
            @Throws(RemoteException::class)
            override fun onError(i: Int) {
                printRunning = false
            }

            @Throws(RemoteException::class)
            override fun onPrintFinish() {
                val endTime = getCurTime()
                printRunning = false
            }
        }

        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL
        ).setMethodCallHandler { call, result ->
            if (call.method == "getBatteryLevel") {
                val batteryLevel = getBatteryLevel()

                if (batteryLevel != -1) {
                    result.success(batteryLevel)
                } else {
                    result.error("UNAVAILABLE", "Battery level not available.", null)
                }
            } else {
                if (call.method == "usePrinter") {
                    val arguments: Map<String, String>? = call.arguments()
                    useThePrinter(arguments)

                } else {
                    result.notImplemented()
                }

            }


        }
    }

    private fun getBatteryLevel(): Int {
        val batteryLevel: Int = if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
            val batteryManager = getSystemService(BATTERY_SERVICE) as BatteryManager
            batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY)
        } else {
            val intent = ContextWrapper(applicationContext).registerReceiver(
                null,
                IntentFilter(Intent.ACTION_BATTERY_CHANGED)
            )
            intent!!.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) * 100 / intent.getIntExtra(
                BatteryManager.EXTRA_SCALE,
                -1
            )
        }

        return batteryLevel
    }

    private fun printAddLineFree(template: PrintTemplate) {
        if (Build.DISPLAY.contains("Z3909")) {
            template.add(TextUnit(""))
        }
    }

    private fun useThePrinter(names: Map<String, String>?) {

        val template = PrintTemplate.getInstance()
        template.clear()
        template.add(TextUnit("Firstname: ${names?.get("firstname")}"))
        template.add(TextUnit("Lastname: ${names?.get("lastname")}"))
        printAddLineFree(template)
        printerDev?.addRuiImage(template.printBitmap, 0)
        printRunning = true
        printerDev?.printRuiQueue(mListen)
    }

    private fun getCurTime(): String {
        val date = Date(System.currentTimeMillis())
        val format = SimpleDateFormat("yyyy-MM-dd HH:mm:ss:SSS")
        return format.format(date)
    }
}

```

I added this permission to my xml file
```xml
<uses-permission android:name="android.permission.CLOUDPOS_PRINTER"/>
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-x64, locale en-NG)
    • Flutter version 3.19.2 on channel stable at /Users/smilingfarood/development/flutter
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.15.1/libexec/bin/dart, which is not
      inside your current Flutter SDK checkout at /Users/smilingfarood/development/flutter. Consider adding
      /Users/smilingfarood/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (2 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/smilingfarood/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • T3 (mobile)     • HD9437C000142 • android-arm    • Android 11 (API 30)
    • macOS (desktop) • macos         • darwin-x64     • macOS 14.3.1 23D60 darwin-x64
    • Chrome (web)    • chrome        • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SmilingFarood, does the `getBatteryLevel` method call work for you?

Are you using an SDK specifically for the printer? Can you provide that sdk as well? Does the sdk require the printer to be connected?

**Comment by SmilingFarood** [comment]
> Are you using an SDK specifically for the printer? Can you provide that sdk as well? Does the sdk require the printer to be connected?

Yes the `getBatteryLevel` method works perfectly. Yes I am using the SDK for the printer. It works for other things too but I need to first initialise it and when initialising, I need to provide the context. In a normal android project, the `applicationContext` works just fine but not same on a Flutter `MethodChannel` project

**Comment by darshankawar** [comment]
@SmilingFarood 
Can you provide us the repo that we can clone directly and run locally to verify this further ?

**Comment by danagbemava-nc** [comment]
Closing this as solved based on the above comment.
