### ISSUE TITLE
Exception when dragging a list `Drag target size is larger than scrollable size, which may cause bouncing`

### ISSUE THREAD

**Issue by TENX-S** [flutter/flutter#145074]
### Steps to reproduce

Drag a list item will trigger the following exception:

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scrollable_helpers.dart': Failed assertion: line 233 pos 7: 'globalRect.size.width >= _dragTargetRelatedToScrollOrigin.size.width &&
        globalRect.size.height >= _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      EdgeDraggingAutoScroller._scroll (package:flutter/src/widgets/scrollable_helpers.dart:233:7)
#3      EdgeDraggingAutoScroller.startAutoScrollIfNecessary (package:flutter/src/widgets/scrollable_helpers.dart:218:5)
#4      SliverReorderableListState._dragUpdate.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:782:22)
#5      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
#6      SliverReorderableListState._dragUpdate (package:flutter/src/widgets/reorderable_list.dart:779:5)
#7      _DragInfo.update (package:flutter/src/widgets/reorderable_list.dart:1389:15)
#8      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:100:16)
#9      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:267:13)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#22     _invoke1 (dart:ui/hooks.dart:328:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```

Can't get a minimal reproducible code for now. 

### Expected results

No excepton.

### Actual results

Got exception.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/40336192/f823c708-231d-4119-ba7f-00e0fa398b7f

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
    • Framework revision 65cd84b588 (11 days ago), 2024-03-01 21:06:15 -0500
    • Engine revision 2706c732b2
    • Dart version 3.4.0 (build 3.4.0-190.0.dev)
    • DevTools version 2.33.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
    • IntelliJ at /Users/ares/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.14888

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Microsoft Edge 122.0.2365.80

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
There is an open issue at https://github.com/flutter/flutter/issues/136331 showing the same exception that you can check if it's similar to your case or not. 

If it's not similar to this, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Also, please provide the output of `flutter doctor -v` as well.

**Comment by TENX-S** [comment]
Close this as duplicate of #136331
