### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2

### ISSUE THREAD

**Issue by gw31415** [flutter/flutter#145249]
## Command
```
flutter run -d macos
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:169:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:157:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1819:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1837:13)
#8      _rootRunUnary (dart:async/zone.dart:1407:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1407:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.3 on channel stable at /Users/ama/.asdf/installs/flutter/3.19.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (8 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.4 23E214 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ba393198430278b6595976de84fe170f553cc728
### Plugins
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
printing-5.12.0
sqlite3_flutter_libs-0.5.20

**Comment by huycozy** [comment]
There is a similar issue at https://github.com/flutter/flutter/issues/95142 when Chrome has not been installed on the OS. Closing this in favor of that one. You can try installing Chrome app to see if it works.
