### ISSUE TITLE
[tool_crash] _TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))

### ISSUE THREAD

**Issue by asosadeq** [flutter/flutter#145272]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart))
```
#0      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart)
#1      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:305:31)
<asynchronous suspension>
#2      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 3.4.0-28.0.pre.1, on Microsoft Windows [Version 10.0.22631.3296], locale en-US)
    • Flutter version 3.4.0-28.0.pre.1 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b84bfa3526 (1 year, 6 months ago), 2022-09-19 08:27:20 +0200
    • Engine revision b22a795011
    • Dart version 2.19.0 (build 2.19.0-214.0.dev)
    • DevTools version 2.17.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.87.2)
    • VS Code at C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 122.0.6261.129
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 122.0.2365.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: b84bfa35264385a897e6d85d039eae0ea6ba90ab
### Plugins
webview_flutter-4.2.2
webview_flutter_android-3.9.3
webview_flutter_wkwebview-3.7.3

**Comment by darshankawar** [comment]
@asosadeq 
This has been already fixed as part of https://github.com/flutter/flutter/issues/111877.
You are on very old version of master channel. Please upgrade to latest and run your scenario again to see the fix working.
Closing for now.
