### ISSUE TITLE
Can't use `ImageDescriptor` in isolate

### ISSUE THREAD

**Issue by t-for-taiks** [flutter/flutter#145320]
### Steps to reproduce

1. Spawn an isolate (whether with `Isolate.run` or `Isolate.spawn`), and inside the isolate: 
2. Read image bytes data from a file
3. Create an `ImmutableBuffer` for the data
4. Try to get an image descriptor with `ImageDescriptor.encoded`

### Expected results

The image descriptor contains info about the image

### Actual results

An error is thrown and no result can be obtained:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.
#0      _futurize (dart:ui/painting.dart:6980:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6786:12)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:io';
import 'dart:isolate';
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          /// The bug is triggered here
          Isolate.run(() async {
            final imageData =
                File(r"<Path to some image>").readAsBytesSync();
            final buffer = await ImmutableBuffer.fromUint8List(imageData);
            final descriptor = await ImageDescriptor.encoded(buffer); // <- bug
            print(descriptor.width);
          });
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.
#0      _futurize (dart:ui/painting.dart:6980:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6786:12)
#2      MyHomePage.build.<anonymous closure>.<anonymous closure> (package:playground_flutter/main.dart:47:54)
<asynchronous suspension>
#3      _RemoteRunner._run (dart:isolate:1092:18)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.21.0-9.0.pre.35, on Microsoft Windows [Version 10.0.22631.3155], locale zh-CN)
    • Flutter version 3.21.0-9.0.pre.35 on channel master at <>
    ! Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git to dismiss this error.
    • Framework revision c6f2b53efd (3 hours ago), 2024-03-18 03:53:17 -0400
    • Engine revision eac9db75f9
    • Dart version 3.4.0 (build 3.4.0-242.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at <>
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio 生成工具 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at <>
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.8660.129

[√] VS Code (version 1.87.1)
    • VS Code at <>
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.113
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by darshankawar** [comment]
@t-for-taiks 
`dart:ui` is not supported or expected to work outside of the main isolate, hence you are seeing the reported behavior. Can you elaborate on your use case that'll help to usage you are trying to implement ?

**Comment by t-for-taiks** [comment]
> @t-for-taiks `dart:ui` is not supported or expected to work outside of the main isolate, hence you are seeing the reported behavior. Can you elaborate on your use case that'll help to usage you are trying to implement ?

Thank you for the clarification. I'm using `ImageDescriptor.encoded` to get the dimensions of local image files. Plus, I put the job into an isolate because I'm iterating through a user-provided directory to deal with potentially large number of images. I find  `ImageDescriptor.encoded` to be the best solution I know of that's both multi-platform and doesn't require decoding the entire image. 

It's a pity I can't use this method in an isolate. I think I'd better find alternatve solutions that can work inside an isolate.

**Comment by darshankawar** [comment]
I'll close this for now as this seems to be WAI. If you disagree, write in comments and I'll reopen it.
