### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by ahmedalfaiq** [flutter/flutter#145301]
### Steps to reproduce

Use Tab Bar and display list veiw in each Tab 
suddenly renddered error occurred 

### Expected results

No Error should display list with out error

### Actual results

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  TabBarView TabBarView:file:///Users/alfaiq/AndroidStudioProjects/ablaghni/lib/screen/reports/answer_report_screen.dart:136:11
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1972:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:65)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#9      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#10     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#13     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#22     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#26     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#27     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#28     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#29     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#30     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#37     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#39     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#40     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#41     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#42     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#43     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#45     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#48     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#50     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#52     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#55     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#58     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#61     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#62     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#63     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581:43)
#64     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608:12)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#72     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#78     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#81     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#83     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3714:13)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#89     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:884:15)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#97     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#100    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#103    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#106    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#115    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#116    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#118    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#120    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#121    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#122    RenderView.performLayout (package:flutter/src/rendering/view.dart:195:14)
#123    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#124    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#125    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#126    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#131    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978:7)
#135    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderPointerListener#a9f2b relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
...  size: MISSING
...  behavior: deferToChild
...  listeners: signal
RenderObject: RenderPointerListener#a9f2b relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
  size: MISSING
  behavior: deferToChild
  listeners: signal
...  child: RenderSemanticsGestureHandler#ed30a relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
...    size: MISSING
...    behavior: opaque
...    gestures: <none>
...    child: RenderPointerListener#358fe relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
...      size: MISSING
...      behavior: opaque
...      listeners: down, panZoomStart
...      child: RenderSemanticsAnnotations#9eb88 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
...        size: MISSING
...        child: RenderIgnorePointer#1bf9a relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=430.0, 0.0<=h<=Infinity)
...          size: MISSING
...          ignoring: false
...          ignoringSemantics: null
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderPointerListener#a9f2b relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'

### Code sample

    return Scaffold(
      body: Column(
        children: [
          Material(
            child: TabBar(
              controller: _tabController,
              unselectedLabelColor: Colors.blueAccent,
              padding: EdgeInsets.all(10),
              physics: const ClampingScrollPhysics(),
              indicator: BoxDecoration(
                borderRadius: BorderRadius.circular(30),
                color: Colors.blue.withOpacity(0.5),
              ),
              tabs: [
                Container(
                  height: 40,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(30),
                    border: Border.all(color: Colors.blueAccent, width: 1),
                  ),
                  child: const Align(
                    alignment: Alignment.center,
                    child: Text("All"),
                  ),
                ),
                Container(
                  height: 40,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(30),
                    border: Border.all(color: Colors.blueAccent, width: 1),
                  ),
                  child: const Align(
                    alignment: Alignment.center,
                    child: Text("Wait"),
                  ),
                ),
              ],
            ),
          ),
          TabBarView(
            controller: _tabController,
            children: [
              (reports.length < 1)
                  ? const Center(
                      child: Text("No Report Yet"),
                    )
                  : ListView.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return ReportCard(
                          report: reports[index],
                          onClick: () => selectReport(reports[index]),
                        );
                      },
                      itemCount: reports.length,
                      // children: (reports.length < 1)
                      //     ? [
                      //         Center(
                      //           child: Text("No Report Yet"),
                      //         )
                      //       ]
                      //     : reports
                      //         .map(
                      //           (e) => ReportCard(
                      //             report: e,
                      //             onClick: () => selectReport(e),
                      //           ),
                      //         )
                      //         .toList(),
                    ),
              (reports2.length < 1)
                  ? const Center(
                      child: Text("No Report Yet"),
                    )
                  : ListView.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return ReportCard(
                          report: reports2[index],
                          onClick: () => selectReport(reports2[index]),
                        );
                      },
                      itemCount: reports2.length,
                    ),
            ],
          ),
        ],

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="965" alt="Screenshot 2024-03-18 at 2 00 15 AM" src="https://github.com/flutter/flutter/assets/59479139/ca600c4e-512a-40cb-b906-cea7bab8accc">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by ahmedalfaiq** [comment]
Can any one help
