### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by denegny** [flutter/flutter#145384]
### Why **windows**, my OS **Linux**, and build for **Linux**

_Thanks_

## Command
```
flutter build linux
```

## Steps to Reproduce
1. install app https://github.com/saladinalep/gametrader

## Logs
FileSystemException: Cannot create link, OS Error: Operation not permitted, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:339:7)
#1      _Link.createSync (dart:io/link.dart:267:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1090:12)
#5      createPluginSymlinks (package:flutter


Oops; flutter has exited unexpectedly: "PathAccessException: Cannot create link, path =
'/media/develop/500Gb/DEVELOP/Flutter/gametrader/windows/flutter/ephemeral/.plugin_symlinks/pa
th_provider_windows' (OS Error: Operation not permitted, errno = 1)".

```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.19.3, on LMDE 6 (faye
) 6.1.0-18-amd64, locale ru_RU.UTF-8)
    • Flutter version 3.19.3 on channel stable at
      /home/develop/.asdf/installs/flutter/3.19.3-st
able
    • Upstream repository https://github.com/flutter
/flutter.git
    • Framework revision ba39319843 (12 дней назад),
 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices
(Android SDK version 34.0.0)
    • Android SDK at /home/develop/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/develop/JetBrains/androi
d-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (buil
d 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/develop/JetBrains/andr
oid-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-f
lutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-d
art
    • Java version OpenJDK Runtime Environment (buil
d 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /home/develop/JetBrains/idea-IU-23
3.14015.106
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-f
lutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-d
art

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /home/develop/JetBrains/idea-IC-23
3.14015.106
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-f
lutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-d
art

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • LM
DE 6 (faye) 6.1.0-18-amd64
    • Chrome (web)    • chrome • web-javascript • Go
ogle Chrome 122.0.6261.128

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by darshankawar** [comment]
@denegny 
Can you check [this](https://github.com/flutter/flutter/issues/129124#issuecomment-1603773416) and see if it helps in your case or not ?

**Comment by denegny** [comment]
yes, bro, its was problem, thanks
