### ISSUE TITLE
[file_selector] java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by ZPGC** [flutter/flutter#145318]
### Steps to reproduce

1. Download pdf file
3. Pick another pdf file to upload

### Expected results

No crash

### Actual results

App crashes

### Code sample

<details open><summary>Code sample</summary>

```
//Downloading file
 final result = await FileSaver.instance.saveAs(
                name: fileObject.fileName.fileNameOnly!,
                ext: fileObject.fileName.extension!,
                mimeType: fetchMimeType(fileObject.fileName.extension!),
                bytes: Uint8List.fromList(fileObject.fileBytes ?? []));

// Picking file
const XTypeGroup pdfTypeGroup = XTypeGroup(
                label: 'PDFs',
                extensions: <String>['pdf', 'PDF'],
                uniformTypeIdentifiers: <String>['pdf', 'PDF'],
              );
              List<XFile> pickedFileResults = [];

              if (isMultiple) {
                pickedFileResults =
                    await openFiles(acceptedTypeGroups: <XTypeGroup>[
                  pdfTypeGroup,
                ]);
              } else {
                final pickedFileResult =
                    await openFile(acceptedTypeGroups: <XTypeGroup>[
                  pdfTypeGroup,
                ]);
                if (pickedFileResult != null) {
                  pickedFileResults = [pickedFileResult];
                }
              }

              if (pickedFileResults.isNotEmpty) {
                pickedFiles = [...pickedFileResults];

                /// Check if the total bytes is exceed in 25MB limit.
                for (final file in pickedFiles) {
                  totalFileBytes = totalFileBytes +
                      (await file.readAsBytes()).lengthInBytes.toMegaByte();
                }

                /// If the total file is greater than 25MB, throw a failure.
                if (totalFileBytes > 25) {
                  return Left(FileMaximumSizeExceedFailure(
                      message: 'File size exceed in maximum limit of 25MB'));
                }

                final List<FileObject> fileObjects = [];

                for (final file in pickedFiles) {
                  final fileBytes = await file.readAsBytes();
                  final fileName = '${file.name}.pdf';

                  final fileObject = FileObject(
                    fileKey: fileName.generateFileKey,
                    fileName: fileName,
                    fileDataType: file.mimeType,
                    fileSize: fileBytes.lengthInBytes,
                    fileBytes: fileBytes,
                  );

                  fileObjects.add(fileObject);
                }

                return Right(fileObjects);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/AndroidRuntime(32366): Shutting down VM
E/AndroidRuntime(32366): FATAL EXCEPTION: main
E/AndroidRuntime(32366): Process: app.qa, PID: 32366
E/AndroidRuntime(32366): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=222, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/32 flg=0x43 }} to activity {app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32366): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
E/AndroidRuntime(32366): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
E/AndroidRuntime(32366): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
E/AndroidRuntime(32366): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(32366): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(32366): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(32366): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
E/AndroidRuntime(32366): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(32366): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(32366): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(32366): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(32366): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32366): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(32366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(32366): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32366): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(32366): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/AndroidRuntime(32366): 	at com.incrediblezayed.file_saver.Dialog.onActivityResult(Dialog.kt:38)
E/AndroidRuntime(32366): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:813)
E/AndroidRuntime(32366): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
E/AndroidRuntime(32366): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:853)
E/AndroidRuntime(32366): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
E/AndroidRuntime(32366): 	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
E/AndroidRuntime(32366): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
E/AndroidRuntime(32366): 	... 13 more
3
D/OpenGLRenderer(32366): setSurface called with nullptr
D/InputTransport(32366): Input channel destroyed: 'ClientS', fd=493
I/BufferQueueConsumer(32366): [SurfaceTexture-0-32366-0](id:7e6e00000002,api:0,p:-1,c:32366) disconnect
I/BufferQueueConsumer(32366): [SurfaceTexture-0-32366-1](id:7e6e00000003,api:0,p:-1,c:32366) disconnect
I/BufferQueueConsumer(32366): [SurfaceTexture-0-32366-2](id:7e6e00000004,api:0,p:-1,c:32366) disconnect
W/System  (32366): A resource failed to call close. 
I/Process (32366): Sending signal. PID: 32366 SIG: 9
Lost connection to device.

Exited.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 13.3.1 22E772610a darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.87.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@ZPGC
I tried the plugin [example](https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector/example) running on Android device with which I didn't get the reported error. Can you try the same and check if using it, you still get same error or not ?
What device or emulator are you seeing this error on ? Also provide plugin version that you are using.

**Comment by stuartmorgan** [comment]
> ```
>  final result = await FileSaver.instance.saveAs(
> ```

> ```
> E/AndroidRuntime(32366): 	at com.incrediblezayed.file_saver.Dialog.onActivityResult(Dialog.kt:38)
> ```

The exception log is showing as coming from `file_saver`, which is a different plugin that you appear to be using at the beginning of your code sample. What issue are you seeing with `file_selector`?
