### ISSUE TITLE
Scaffold.geometryOf() must only be accessed during the paint phase.

### ISSUE THREAD

**Issue by mohsinnaqvi606** [flutter/flutter#145458]
### Steps to reproduce

Create 2 screens

1. Create a Screen (A) with BottomNavigationBar to have a floating action button in the **centerDocked**.
2. Create another Screen(B) and add a floating action button in the end float.
3. Now navigate from screen A to B, and go back.
4. Repeat step 3 for 5,6 times and you will see this error.

**Note: Screen B should not be part of the bottom navigation bar. it should be a separate screen**

### Expected results

It should work fine as it's working with others with no floating actions buttons screen.

### Actual results

Currently, it's giving an error with all screens that have floating action buttons.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

https://github.com/flutter/flutter/assets/14882412/e9620a42-abf6-4eae-be7f-b7ce0a62d2e5

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
Scaffold.geometryOf() must only be accessed during the paint phase.

The ScaffoldGeometry is only available during the paint phase, because its value is computed during the animation and layout phases prior to painting.
When the exception was thrown, this was the stack: 
#0      _ScaffoldGeometryNotifier.value.<anonymous closure> (package:flutter/src/material/scaffold.dart:838:9)
#1      _ScaffoldGeometryNotifier.value (package:flutter/src/material/scaffold.dart:845:6)
#2      _BottomAppBarClipper.getClip (package:flutter/src/material/bottom_app_bar.dart:262:35)
#3      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1447:25)
#4      RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2098:7)
#5      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2861:25)
#6      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2856:33)
#8      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
#9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#14     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1990:18)
#15     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#16     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:173:19)
#17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#18     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:173:19)
#19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#23     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#25     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3604:31)
#26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#32     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#34     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#35     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#36     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#40     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3734:31)
#41     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#43     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:985:81)
#44     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:800:31)
#45     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:986:22)
#46     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#47     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#48     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#49     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3857:17)
#50     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#51     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:173:19)
#52     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#53     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#54     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#55     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#56     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#57     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#58     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#59     RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:214:28)
#60     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#61     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#62     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#63     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#64     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
#65     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2482:11)
#66     RenderView.hitTest (package:flutter/src/rendering/view.dart:211:14)
#67     RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:615:34)
#68     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:391:7)
#69     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#70     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#71     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#72     _invoke1 (dart:ui/hooks.dart:328:13)
#73     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#74     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
    • Flutter version 3.19.2 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Nexgen\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Connected device (4 available)
    • Pixel 4a (mobile) • 16021JEC206054 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 122.0.6261.129
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 122.0.2365.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Based on the exception, it seems similar to https://github.com/flutter/flutter/issues/140733, so please follow-up in it for further updates. Closing as duplicate. If you disagree, write in comments and I'll reopen it.
