### ISSUE TITLE
Unable to build and run Flutter Gallery in IntelliJ

### ISSUE THREAD

**Issue by secondstreetmedia** [flutter/flutter#14547]
## Steps to Reproduce

Opened flutter_gallery in IntelliJ IDEA CE and have been unable to successfully build and run for either iOS or Android emulators. Is this something I should be able to do or will the gallery only run successfully on physical devices?

Some of these errors (maybe all of them) do not look as though they should be errors. For example, the first error in `flutter analyze` says `excludeFromSemantics` isn't defined for `Tooltip`, yet it is. The second error is looking for a concrete implementation for the `estimateMaxScrollOffset` which, as far as I can determine, `SliverGridLayout` doesn't have.

## Logs

Run your application with `flutter run` and attach all the log output.

```
~/FlutterProjects/flutter_gallery>> flutter run
Launching lib/main.dart on iPhone 8 in debug mode...
Running Xcode build...                               15.9s
Syncing files to device iPhone 8...                       
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building GalleryApp(dirty, state: GalleryAppState#d39ae):
No constructor 'MaterialApp' declared in class 'MaterialApp'.
Receiver: MaterialApp
Tried calling: new MaterialApp(title: "Flutter Gallery", color: Instance of 'MaterialColor', theme:
Instance of 'ThemeData', showPerformanceOverlay: false, checkerboardRasterCacheImages: false,
checkerboardOffscreenLayers: false, routes: _LinkedHashMap len:43, home: Instance of 'Builder',
builder: Closure: (BuildContext, Widget) => dynamic)

When the exception was thrown, this was the stack:
#0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
#1      GalleryAppState.build (/Users/tim-macbookpro/FlutterProjects/flutter_gallery/lib/gallery/app.dart:169:27)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3582:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3718:22)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2678:12)
#10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2190:19)
#14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#15     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#16     runApp (package:flutter/src/widgets/binding.dart:699:7)
#17     main (/Users/tim-macbookpro/FlutterProjects/flutter_gallery/lib/main.dart:13:3)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:278)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
════════════════════════════════════════════════════════════════════════════════════════════════════

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

Run `flutter analyze` and attach any output of that command also.

```
~/FlutterProjects/flutter_gallery>> flutter analyze
Analyzing /Users/tim-macbookpro/FlutterProjects/flutter_gallery...
  error • The named parameter 'excludeFromSemantics' isn't defined at lib/demo/cupertino/cupertino_navigation_demo.dart:110:9 • undefined_named_parameter
  error • Missing concrete implementation of 'SliverGridLayout.estimateMaxScrollOffset' at lib/demo/shrine/shrine_home.dart:50:7 • non_abstract_class_inherits_abstract_member_one
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at lib/demo/shrine/shrine_home.dart:392:11 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'SliverSafeArea' at lib/demo/shrine/shrine_home.dart:392:15 • undefined_class
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at lib/demo/shrine/shrine_order.dart:290:11 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'SliverSafeArea' at lib/demo/shrine/shrine_order.dart:290:15 • undefined_class
  error • The named parameter 'builder' isn't defined at lib/gallery/app.dart:178:7 • undefined_named_parameter
  hint • Method doesn't override an inherited method at lib/demo/shrine/shrine_home.dart:87:10 • override_on_non_overriding_method
8 issues found.
(Ran in 9.4s)
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
~/FlutterProjects/flutter_gallery>> flutter doctor
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel alpha)
    • Flutter version 0.0.21 at /flutter
    • Framework revision 2e449f06f0 (9 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/tim-macbookpro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • iPhone 8 • A406EC15-86EA-4674-954F-D80E09594B62 • ios • iOS 11.2 (simulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Do you have two versions of Flutter installed or something? It looks like you're trying to run the demos from one version with the framework from another.

**Comment by Hixie** [comment]
(All the errors above are relating to things that we've added recently, in the last week or so. The `flutter doctor` logs say you are using a version of flutter from 9 days ago.)

**Comment by secondstreetmedia** [comment]
Got it working. Switched to dev channel. Docs seem to imply only needed to run `flutter channel dev`, but nothing is downloaded, even after `flutter upgrade`. Channel remained alpha. Cloned dev branch and was able to successfully switch over. Thanks!
