### ISSUE TITLE
gclient sync for building engine fails

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#14545]
## Steps to Reproduce

I try to build the engine/[edaecdc8b8098f20512c23745b9d0b135a8ee56d](https://github.com/flutter/engine/tree/edaecdc8b8098f20512c23745b9d0b135a8ee56d) that is used from Flutter 0.0.20, but `gclient sync` failed.

Revision 6921873c71e700235c0f68f0359be2332f93c8bc that is used from 0.0.21, `gclient sync`, `gn` and `ninja` succeeded.

## Logs

```
src: gclient sync
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc" "/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e"' in /Users/najeira/Projects/najeira/engine_old failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc" "/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e"' in /Users/najeira/Projects/najeira/engine_old failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc" "/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e"' in /Users/najeira/Projects/najeira/engine_old failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc" "/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e"' in /Users/najeira/Projects/najeira/engine_old failed; will retry after a short nap...
Syncing projects: 100% (84/84) src/third_party/dart/third_party/pkg/dartdoc

src/third_party/dart/third_party/pkg/dartdoc (ERROR)
----------------------------------------
[0:00:12] Started.
[0:00:12]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc /Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e' in '/Users/najeira/Projects/najeira/engine_old'
[0:00:12] Cloning into '/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e'...
[0:00:13] fatal: remote error: want 538c08030f6fc1b45230283bfe9a8ce0376ed395 not valid
[0:00:13] fatal: The remote end hung up unexpectedly

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc /Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e' in '/Users/najeira/Projects/najeira/engine_old'
[0:00:13] Cloning into '/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e'...
[0:00:14] fatal: remote error: want 538c08030f6fc1b45230283bfe9a8ce0376ed395 not valid
[0:00:14] fatal: The remote end hung up unexpectedly

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc /Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e' in '/Users/najeira/Projects/najeira/engine_old'
[0:00:15] Cloning into '/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e'...
[0:00:15] fatal: remote error: want 538c08030f6fc1b45230283bfe9a8ce0376ed395 not valid
[0:00:15] fatal: The remote end hung up unexpectedly

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc /Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e' in '/Users/najeira/Projects/najeira/engine_old'
[0:00:17] Cloning into '/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e'...
[0:00:18] fatal: remote error: want 538c08030f6fc1b45230283bfe9a8ce0376ed395 not valid
[0:00:18] fatal: The remote end hung up unexpectedly
Traceback (most recent call last):
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_scm.py", line 907, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_scm.py", line 1211, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_utils.py", line 314, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_utils.py", line 576, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/dart-lang/dartdoc /Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e' returned non-zero exit status 128 in /Users/najeira/Projects/najeira/engine_old
----------------------------------------
Traceback (most recent call last):
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient.py", line 2917, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient.py", line 2903, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient.py", line 2658, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient.py", line 1640, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_utils.py", line 1075, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient.py", line 971, in run
    file_list)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_scm.py", line 130, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_scm.py", line 420, in update
    self._Clone(revision, url, options)
  File "/Users/najeira/Projects/najeira/engine/depot_tools/gclient_scm.py", line 915, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: '/Users/najeira/Projects/najeira/engine_old/src/third_party/dart/third_party/pkg/_gclient_dartdoc_likw9e'
```

**Comment by najeira** [comment]
I am also facing the problem of launching an application at 0.0.22.
#14502 #14491

I want to back 0.0.20 and I need my own patch to fix locale and language problem, but could not build.

**Comment by najeira** [comment]
I tried it again today, and works.
