### ISSUE TITLE
[go_router]: "There is nothing to pop" when popped fast

### ISSUE THREAD

**Issue by eli1stark** [flutter/flutter#145573]
### Steps to reproduce

**Steps:**
1. go_router: v12.1.3
2. Launch sample
3. Press 'Push And Pop" button

**Explanation:**

This issue occurs when pushing and popping pages rapidly enough. Adding a delay of 100-200ms seems to fix the issue, but this is not an optimal solution in my opinion. It's more of a hack that unnecessarily delays app interactions in the hope of avoiding the bug.

Here's an example use case for this issue and why you might need to pop a newly pushed page very quickly. A good use case would be when a Future completes fast enough, like so:

```dart
_router.pushPageA();

final status = await future();

if (status.isSuccess) {
  router.pushSomeOtherPage();
} else {
  router.pop(); // close PageA
}
```
In this example, you push PageA, await for a Future to complete, and based on the status, either push another page or pop PageA. If the Future completes quickly, the pop operation happens immediately after the push, causing the issue.

### Expected results

`PageB` should be popped without errors.

### Actual results

The error 'There is nothing to pop' occurs when attempting to pop a newly pushed PageB.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final router = GoRouter(
  routes: [
    GoRoute(
      name: 'A',
      path: '/',
      builder: (_, __) => const PageA(),
    ),
    GoRoute(
      name: 'B',
      path: '/B',
      builder: (_, __) => const PageB(),
    ),
  ],
);

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}

class PageA extends StatelessWidget {
  const PageA({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: TextButton(
              onPressed: () {
                context.pushNamed('B');
                context.pop();
              },
              child: const Text('Push And Pop'),
            ),
          ),
        ],
      ),
    );
  }
}

class PageB extends StatelessWidget {
  const PageB({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Colors.black,
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Restarted application in 835ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following GoError was thrown while handling a gesture:
There is nothing to pop

When the exception was thrown, this was the stack:
#0      GoRouterDelegate.pop (package:go_router/src/delegate.dart:94:5)
delegate.dart:94
#1      GoRouter.pop (package:go_router/src/router.dart:490:20)
router.dart:490
#2      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
extensions.dart:71
#3      PageA.build.<anonymous closure> (package:offsuit/main_development.dart:46:25)
main_development.dart:46
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
ink_well.dart:1183
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
recognizer.dart:275
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
tap.dart:652
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
tap.dart:309
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
tap.dart:242
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
recognizer.dart:630
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
pointer_router.dart:98
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
pointer_router.dart:143
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
pointer_router.dart:141
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
pointer_router.dart:127
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
binding.dart:488
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
binding.dart:468
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
binding.dart:439
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
binding.dart:413
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
binding.dart:376
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
binding.dart:323
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
binding.dart:292
#22     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410:7)
platform_dispatcher.dart:410
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
hooks.dart:262

Handler: "onTap"
Recognizer: TapGestureRecognizer#832a5
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(226.0, 447.0)
    finalLocalPosition: Offset(78.6, 19.0)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I also can reproduce this with the latest package version `go_router: ^13.2.1`. 

The issue can be also reproduced with:

```dart
context.pushNamed('B').then((_) {
	print('Page B is popped');
	context.pop();
});
```

But not reproduced with Navigator:

```dart
Navigator.pushNamed(context, '/second').then((value) {
	print('Second screen is popped');
	Navigator.pop(context);
});
```

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (29 hours ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.21.0-12.0.pre.40, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.21.0-12.0.pre.40 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d755bc222b (28 minutes ago), 2024-03-21 19:44:55 -0700
    • Engine revision e2f324beac
    • Dart version 3.4.0 (build 3.4.0-257.0.dev)
    • DevTools version 2.34.0-dev.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.58

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by eli1stark** [comment]
> This seems like an issue if all the operations are synchronous. Need more investigation

Thank you! If you need more information let me know.

**Comment by Joshix-1** [comment]
> The issue can be also reproduced with:
> 
> ```dart
> context.pushNamed('B').then((_) {
> 	print('Page B is popped');
> 	context.pop();
> });
> ```

I have similar code. It worked with go_router 12.1.1. It broke when I updated to 14.1.4. This is really annoying.

**Comment by eli1stark** [comment]
@Joshix-1 It doesn't work on 12.1.3

**Comment by Joshix-1** [comment]
Then I'm probably encountering a different issue.

**Comment by chunhtai** [comment]
I have recently look into timing issue in go router. I will take a look at this one

**Comment by hasanm08** [comment]
same issue here
go_router: ^14.2.1
[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.19045.5371], locale en-US)
    • Flutter version 3.27.0 on channel stable at C:\Users\amir.amirmahani\AppData\Roaming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (7 weeks ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

**Comment by eli1stark** [comment]
@chunhtai  Are there any updates on this issue?

As tested on the latest master `v3.33.0-1.0.pre.744` and latest go_router `v15.2.4`, the issue is still reproducible.
