### ISSUE TITLE
[google_maps_flutter] Android TalkBack crashes when useAndroidViewSurface is false

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [flutter/flutter#145501]
### Steps to reproduce

1. Enable Android TalkBack (Settings -> Accessibility -> TalkBack).
2. Open a Flutter app using google_maps_flutter and a useAndroidViewSurface value of false (the current default).
3. Interact with the map.
4. Observe crashes of the TalkBack service, effectively ANR'ing the app itself.

### Expected results

TalkBack should not crash when used in an app using google_maps_flutter.

### Actual results

TalkBack crashes and causes the app to be unusable.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter_android/google_maps_flutter_android.dart';
import 'package:google_maps_flutter_platform_interface/google_maps_flutter_platform_interface.dart';

void main() async {
  //*****ENABLE this line to avoid TalkBack crashing
  // _googleMapsFlutterSetup();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: GoogleMapPage(),
    );
  }
}

void _googleMapsFlutterSetup() {
  final mapsImplementation = GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    mapsImplementation.useAndroidViewSurface = true;
  }
}

class GoogleMapPage extends StatefulWidget {
  GoogleMapPage({Key? key}) : super(key: key);

  @override
  State<GoogleMapPage> createState() => _GoogleMapPageState();
}

class _GoogleMapPageState extends State<GoogleMapPage> {
  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      initialCameraPosition:
          const CameraPosition(target: LatLng(0.0, 0.0), zoom: 1),
    );
  }
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/AndroidRuntime(11211): FATAL EXCEPTION: main
E/AndroidRuntime(11211): Process: com.google.android.marvin.talkback, PID: 11211
E/AndroidRuntime(11211): java.lang.StackOverflowError: stack size 8188KB
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:4157)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityNodeInfo.<init>(AccessibilityNodeInfo.java:944)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:344)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:541)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityNodeInfo.getNodeForAccessibilityId(AccessibilityNodeInfo.java:4625)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityNodeInfo.getNodeForAccessibilityId(AccessibilityNodeInfo.java:4614)
E/AndroidRuntime(11211): 	at android.view.accessibility.AccessibilityNodeInfo.getParent(AccessibilityNodeInfo.java:1903)
E/AndroidRuntime(11211): 	at androidx.core.view.accessibility.AccessibilityNodeInfoCompat.getParent(PG:1)
E/AndroidRuntime(11211): 	at com.google.android.accessibility.utils.ScrollableNodeInfo.findScrollableNodeForDirectionRecursive(PG:2)
E/AndroidRuntime(11211): 	at com.google.android.accessibility.utils.ScrollableNodeInfo.findScrollableNodeForDirectionRecursive(PG:2)
E/AndroidRuntime(11211): 	at com.google.android.accessibility.utils.ScrollableNodeInfo.findScrollableNodeForDirectionRecursive(PG:2)
E/AndroidRuntime(11211): 	at com.google.android.accessibility.utils.ScrollableNodeInfo.findScrollableNodeForDirectionRecursive(PG:2)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel google3, on macOS 14.4 23E214 darwin-x64, locale en)
    • Framework revision 03b5ea519a (2 days ago), 2024-03-18T00:00:00.000
    • Engine revision aebc0021cd
    • Dart version d5cf2d3849

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /Applications/Android Studio with Blaze
      Beta.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] GoogleMac (on macos)
    • AppleWWDRCA installed.
    • Google development certificate installed.
    • Device 00008101-000539403403001E is whitelisted

[✓] Connected device (2 available)
    • Pixel 4 (mobile) • 99211FFAZ0054E • android-arm64 • Android 13 (API 33)

• No issues found!
```

</details>

**Comment by ChristianEdwardPadilla** [comment]
Google bug: b/329766984.

**Comment by ChristianEdwardPadilla** [comment]
I'm seeing this behavior on `google_maps_flutter` version 2.6.0 (also repros for me on 2.5.0 and presumably in between), and `google_maps_flutter_android` version 2.7.0 (similarly, down to 2.5.1).

**Comment by danagbemava-nc** [comment]
Hi @ChristianEdwardPadilla, are you only seeing this on the Pixel 4 device or are you experiencing this on other devices as well? When you interact with the map, how long does it take before the ANR occurs?

**Comment by ChristianEdwardPadilla** [comment]
Hey Daniel, sorry I don't have much more info. The ANR on the Pixel 4 happens after only a few seconds of interacting with the map.

However, I am unable to repro this on a Pixel 4a with the following `flutter doctor` output:

```
[✓] Flutter (Channel google3, on macOS 14.4 23E214 darwin-x64, locale en)
    • Framework revision b96c13d1e9 (5 days ago), 2024-03-20T00:00:00.000
    • Engine revision 883adfe2ef
    • Dart version 1fec623555

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /Applications/Android Studio with Blaze
      Beta.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] Connected device (2 available)
    • Pixel 4a (mobile) • 01091FQC200240 • android-arm64 • Android 13 (API 33)

• No issues found!
```

I don't have any leads on why there might be a difference for the two devices. I'll add more details as I find them.

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

Labeling based on the report shared above. For now, it seems to be only reproducing on the Pixel 4. Other devices may be affected but I didn't run into it on either my Nokia 6 or Pixel 7. 

There was a [similar issue](https://github.com/flutter/flutter/issues/38063) a while back, maybe it wasn't completely fixed (it seemed to be occuring on specific devices in the old issue as well)

**Comment by alicialiu-goog** [comment]
Hi Daniel, I am able to reproduce the issue 100% on Pixel 6 and Pixel 5a, both running Android 13, with the exact same steps. 
Build app with useAndroidViewSurface set to false
Enabling TalkBack app , swipe left/right until the Google Map widget get focus, ANR happens.

**Comment by alicialiu-goog** [comment]
Ops, sorry one in Android 14.
flutter doctor output:
```
[✓] Flutter (Channel google3, on macOS 14.4 23E214 darwin-arm64 (Rosetta), locale en)
    • Framework revision 73e78fd97c (3 days ago), 2024-03-23T00:00:00.000
    • Engine revision 689ea4b10b
    • Dart version 4ed5b58c2c

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /Applications/Android Studio with [Blaze.app/Contents/jbr/Contents/Home/bin/java](http://blaze.app/Contents/jbr/Contents/Home/bin/java)
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • Pixel 5a (mobile) • 0C181FQCB00400 • android-arm64 • Android 13 (API 33)

• No issues found!
```

```
[✓] Flutter (Channel google3, on macOS 14.4 23E214 darwin-arm64 (Rosetta), locale en)
    • Framework revision 73e78fd97c (3 days ago), 2024-03-23T00:00:00.000
    • Engine revision 689ea4b10b
    • Dart version 4ed5b58c2c

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /Applications/Android Studio with [Blaze.app/Contents/jbr/Contents/Home/bin/java](http://blaze.app/Contents/jbr/Contents/Home/bin/java)
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • Pixel 6 (mobile) • 23241FDF6003AE • android-arm64 • Android 14 (API 34)
 
• No issues found!
```

**Comment by johnmccutchan** [comment]
This will be a difficult bug to figure out because the crash isn't in code we own.

- If this platform view uses a SurfaceView it will end up in a VirtualDisplay which has completely broken a11y support.
- Using hybrid composition mode should make everything work but I understand there are performance problems with that approach.

We are investigating how to improve the performance in hybrid composition mode but that doesn't help you out today.

**Comment by reidbaker** [comment]
@mariamhas to coordinate either a work around or something else.

**Comment by ziyad-aljohani** [comment]
Since last week, Google Map is only a black widget on some of Android devices

Until I add this
```
final GoogleMapsFlutterPlatform mapsImplementation =
      GoogleMapsFlutterPlatform.instance;
  if (mapsImplementation is GoogleMapsFlutterAndroid) {
    // Force Hybrid Composition mode.
    mapsImplementation.useAndroidViewSurface = true;
  }
```
it works. What's the problem please? I don't know how to create a new issue here.

**Comment by gmackall** [comment]
This is currently on my backlog. Work on Android platform views is my current first priority, but I expect to have time to address this issue when that work is complete.
