### ISSUE TITLE
Support enabling asserts in profile builds.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#145729]
This is a request from customer: castaway, to allow QA builds to have clearer stack traces and error messages. They use debug builds on Android for this, but since debug builds can only be launched from XCode on iOS they'd need to use profile builds.

I tried the following to enable assertsions:

`flutter run --profile --extra-gen-snapshot-options=--enable-asserts`

However that crashes at start up with an engine configuration issue. Is there a way we can build the engine in an assert agnostic manner?

```
(lldb) 2024-03-25 15:42:53.668461-0700 Runner[6110:863224] [FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers no-dedup_instructions no-tsan asserts arm64 ios no-compressed-pointers null-safety' but the VM has 'release no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers no-dedup_instructions no-tsan no-asserts arm64 ios no-compressed-pointers null-safety'
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ca9b5578 libsystem_kernel.dylib`__pthread_kill + 8
```

**Comment by alexmarkov** [comment]
Passing `--enable-asserts` to `gen_snapshot` is not enough. Flutter tools and flutter engine need to pass this option consistently to
* frontend_server
* gen_snapshot
* Dart VM options at runtime

Also, we should probably support it in the standalone Dart SDK first (https://github.com/dart-lang/sdk/issues/53343) and add AOT bot with enabled assertions to Dart CI in order to verify that this mode works before landing its support in Flutter.

**Comment by jonahwilliams** [comment]
So we don't need to build a new engine variant, that is good! We already have support for passing arbitrary arguments to frontend_server/gensnapshot, and I believe applications can add allowlisted dart flags to the vm at runtime.

But if this hasn't been tried by dart before, then it would be good to confirm this will actually work first 😄

**Comment by aam** [comment]
dart aot that is used in profile build actually supports `--enable-asserts` flag(tested in https://dart-current-results.web.app/#/filter=language/assert/assert_test&showAll), so this can be passed by flutter to dart gen_snapshot and aot runtime) right now.

There are known limitations https://github.com/dart-lang/sdk/issues/34110 that make assert message and location in aot not usable - we will work on improving that. The stack trace on the raised exception though will point to the source code location where assertion failed.

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/issues/53343 has been closed as well so passing `--enable-asserts` to frontend and gen_snapshot should work.

However, attempt to compile flutter app in profile mode with `--enable-asserts` breaks on flutter framework code
```
file://p/f/f1/flutter/packages/flutter/lib/src/widgets/app.dart:60388
Constant evaluation error: Constant evaluation error:
 org-dartlang-sdk:///flutter/third_party/dart/sdk/lib/io/platform_impl.dart:2770 Constant evaluation
error: The invocation of '_environmentCache' is not allowed in a constant expression.
 Unhandled exception:
file://p/f/f1/flutter/packages/flutter/lib/src/foundation/platform.dart:2469 Error for
annotated member defaultTargetPlatform: cannot evaluate to a constant
```

The culprit seems to be the use of `@pragma('vm:platform-const-if' ` in
https://github.com/flutter/flutter/blob/35c0ad1a79184c0bbce55a0596faddc71b7999ea/packages/flutter/lib/src/foundation/platform.dart#L47 and https://github.com/flutter/flutter/blob/35c0ad1a79184c0bbce55a0596faddc71b7999ea/packages/flutter/lib/src/foundation/_platform_io.dart#L13 (commenting use of those pragmas fixes the build and make sample app with assert throw expected `AssertionError` exceptions)

**Comment by jonahwilliams** [comment]
Thank you @aam . I'll see if I can adjust the pragma a bit. I suspect with asserts enabled we're in an unexpected set of configurations and will need to adjust some other flags.

**Comment by aam** [comment]
https://github.com/flutter/flutter/blob/35c0ad1a79184c0bbce55a0596faddc71b7999ea/packages/flutter/lib/src/foundation/_platform_io.dart#L30 is better culprit - getting rid of that `assert`(which uses `Platform.enivronment`) fixes the issue as well

**Comment by a-siva** [comment]
There is some pending dart work with respect to the assert message, this is being tracked in https://github.com/dart-lang/sdk/issues/34110

**Comment by jonahwilliams** [comment]
This now almost works on ToT. Invocation:

` flutter run --profile --extra-gen-snapshot-options=--enable-asserts --extra-front-end-options=--enable-asserts --dart-flags=--enable-asserts`

Shipping this requires pssing the --dart-flags=--enable-asserts at runtime IIRC

**Comment by jonahwilliams** [comment]
Actually a few more args:

`flutter run --profile --extra-gen-snapshot-options=--enable-asserts --extra-front-end-options=--enable-asserts --dart-flags=--enable-asserts --dart-define=dart.vm.profile=false --dart-define=dart.vm.product=false`

**Comment by jonahwilliams** [comment]
This should work as of 5bc3de9d75

**Comment by jonahwilliams** [comment]
@a-siva I'm getting asserts messages at ToT. What is missing?

```
void main() {
  assert(false, "Hit an assert!");
}
```

Gives me

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:hello_world/main.dart': Failed assertion: line -1: '<optimized out>': Hit an assert!
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:45)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40)
#2      main (package:hello_world/main.dart:10)
#3      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
Installing and launching...                                         4.1s

```

**Comment by a-siva** [comment]
> @a-siva I'm getting asserts messages at ToT. What is missing?

The line number says -1: '<optimized out>' if you ran the debug version it will have the line number.

**Comment by aam** [comment]
> I'm getting asserts messages at ToT. What is missing?

Reported exception should be `Unhandled exception: '...a.dart': Failed assertion: line 2 pos 10: 'false': Hit an assert!`

**Comment by jonahwilliams** [comment]
This should work on ToT.

Add the following line to the application Info.plist:

```
<key>FLTEnableDartAsserts</key>
<true/>
```

and then build/run with the following arguments:

```
flutter run --profile --extra-gen-snapshot-options=--enable-asserts --extra-front-end-options=--enable-asserts --dart-flags=--enable-asserts --dart-define=dart.vm.profile=false --dart-define=dart.vm.product=false
```

**Comment by jonahwilliams** [comment]
Correct!

**Comment by jonahwilliams** [comment]
unassigning as I think all my work is done here.

**Comment by jonahwilliams** [comment]
You need to be on a flutter version after https://github.com/flutter/flutter/commit/817630ccf18b014b7a556c7dca28489315503c5b has landed
