### ISSUE TITLE
Issue with Range Slider Changing While Repainting a Path

### ISSUE THREAD

**Issue by justintimewatkins** [flutter/flutter#145734]
### Steps to reproduce

1. Create a range slider which manipulates time to filter coordinate points that are to be displayed
2. Have icons populate a grid based on range values
3. Have path being painted based on coordinates of icons appearing on grid
4. Slide slider in a time range when an icon is supposed to just appear and hold the slider through

### Expected results

App not crashing when slider is moved fast

### Actual results

App crashes when slider is moved during a time interval period when an icon is supposed to appear

### Code sample

```dart
import 'dart:typed_data';
import 'dart:io';
import 'dart:ui';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:item_tracking_app/dbInterface.dart';
import 'package:riverpod/riverpod.dart';
import 'itemClass.dart';
import 'package:intl/intl.dart';
import 'package:flutter/material.dart';
import 'package:item_tracking_app/firestoreDB.dart';
import 'ItemSearch.dart';
import 'main.dart';
import 'dart:async';

enum Timespan {
  minutes,
  hours,
  days,
  weeks,
  months,
  unassigned,
}

final visibleCoordinatesProvider = StateProvider<List<List<int>>>((ref) => []);

class LocateItem extends StatefulWidget {
  const LocateItem({super.key});

  @override
  State<LocateItem> createState() => _LocateItemState();
}

class _LocateItemState extends State<LocateItem> {
  //grids pixel width
  double gridWidth = 600;
  //grids pixel height
  double gridHeight = 600;
  //#boxes in grid row
  int numBoxes = 16;
  //denotes if item was selected
  bool itemSelected = false;
  //selected items info
  ItemInfo? itemInfo = null;
  //gives previous info of selected item
  ItemInfo? previousInfo = null;
  //current time
  DateTime currentTime = DateTime.now();
  //time interval multiplier in seconds to be set on selected interval by the user
  //we automatically start at hours
  //int timeIntervalMultiplierSeconds = 3600;

  //Arbitrary Fill-in functions for start date and end date values
  //which are parsed from the user text entry
  DateTime startDate = DateTime.now()
      .subtract(const Duration(hours: 48)); //DateTime? _startDate;
  DateTime endDate =
      DateTime.now().subtract(const Duration(hours: 24)); //DateTime? _endDate

  //controllers to grab text entries by the user for dates
  final TextEditingController _startDateTimeController =
      TextEditingController();
  final TextEditingController _endDateTimeController = TextEditingController();

  final DateFormat _dateFormat = DateFormat('yyyy-MM-dd HH:mm');

  //upper time label
  String upperLabel = "${DateTime.now().subtract(Duration(hours: 48)).hour}";
  //lower time label
  String lowerLabel = "${DateTime.now().subtract(Duration(hours: 24)).hour}";

  //timespan to select the intervals to become
  Timespan intervalSelection = Timespan.unassigned;

  int _maxRange = 100;

  //slider range
  RangeValues _currentRangeValues = const RangeValues(0, 24);

  List<List<int>> visibleCoordinates = dbHandler.previousCoordinates;
  //VARIABLES I'M NOT USING CORRECTLY

  //boolean for slider to be activated or deactivated based on the state of the
  //date range entries and the interval selected values
  bool isSliderActive = false;

  //manageAnimation to have pathPainting not have animation controller
  //messing up it's repainting
  int repaintTrigger = 0;
  Timer? _debounce;

  //use if using just Icon
  double itemXCoordinate(Size deviceSize, int itemXLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 12;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.width / 5) -
        pixelCorrection +
        (boxWidth * itemXLocation);
  }

  //use if using just Icon
  double itemYCoordinate(Size deviceSize, int itemYLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 12;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.height / 8) -
        pixelCorrection +
        (boxWidth * itemYLocation);
  }

  //use if using Icon Button
  double itemXCoordinateButton(Size deviceSize, int itemXLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 24;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.width / 5) -
        pixelCorrection +
        (boxWidth * itemXLocation);
  }

  //use if using Icon Button
  double itemYCoordinateButton(Size deviceSize, int itemYLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 24;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.height / 8) -
        pixelCorrection +
        (boxWidth * itemYLocation);
  }

  int _monthsBetween(DateTime startDate, DateTime endDate) {
    return (endDate.year - startDate.year) * 12 +
        endDate.month -
        startDate.month;
  }

  //the position of the RFID tag doesn't have second by second granularity in it's position
  //due to the KNN model requiring a 30 second interval cycle of RFID readings to be done
  //and averaging the RSSI for each reading and attaining the standard deviation in order
  //to make a prediction on the position
  int _calculateIntervals(
      DateTime startDate, DateTime endDate, Timespan intervalSelection) {
    Duration difference = endDate.difference(startDate);

    switch (intervalSelection) {
      case Timespan.months:
        //seconds in a month
        //timeIntervalMultiplierSeconds = 2628002;
        return _monthsBetween(startDate, endDate);
      case Timespan.weeks:
        //timeIntervalMultiplierSeconds = 604800;
        return (difference.inDays / 7).floor();
      case Timespan.days:
        //timeIntervalMultiplierSeconds = 86400;
        return endDate.difference(startDate).inDays;
      case Timespan.hours:
        //timeIntervalMultiplierSeconds = 3600;
        return endDate.difference(startDate).inHours;
      case Timespan.minutes:
        //timeIntervalMultiplierSeconds = 60;
        return endDate.difference(startDate).inMinutes;

      //TODO: CHANGE THIS TO SOMETHING MORE SIGNIFICANT
      case Timespan.unassigned:
        return 0;
    }
    // case Timespan.seconds:
    //   intervals = endDate.difference(startDate).inSeconds;
    //   break;
  }

  //method to get total duration in seconds based on the selected start and end dates
  // then utilize that total value to multiple the sliderValue and divide by the entire
  //maxRange to get the seconds which need to be added to the datetime
  //(slider value/maxIntervals)*totalRangeSeconds
  DateTime calculateDateTimeFromSliderValue(double sliderValue) {
    int totalDurationInSeconds = endDate.difference(startDate).inSeconds;
    //Calculate the number of seconds that the slider value represents
    int sliderSeconds =
        (sliderValue * totalDurationInSeconds / _maxRange).round();
    return startDate.add(Duration(seconds: sliderSeconds));
  }

  //we update slider range only when the start or end dates are changed or the intervals are chaged
  //we then reset the currentRangeValues also
  void _updateSliderRange() {
    //Parse start adn end dates from the text controllers
    if (_startDateTimeController.text.isEmpty ||
        _endDateTimeController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('Please enter both start and end date-times.'),
      ));
      setState(() {
        isSliderActive = false;
      });
      return;
    }

    try {
      DateTime tempStartDate = _dateFormat.parse(_startDateTimeController.text);
      DateTime tempEndDate = _dateFormat.parse(_endDateTimeController.text);

      if (tempStartDate.isAfter(tempEndDate)) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text('Start date-time must be before end date-time.'),
          //we don't change the current intervals at all
        ));
        setState(() {
          //again we don't want these start and end dates to continue any further either
          isSliderActive = false;
        });
        return;
      }

      setState(() {
        startDate = tempStartDate;
        endDate = tempEndDate;
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content:
                Text('Invalid date-time format. Please use yyyy-MM-dd HH:mm')),
      );
      setState(() {
        //we don't want to bring these start and end date values forward any further
        isSliderActive = false;
      });
      return;
    }

    if (intervalSelection == Timespan.unassigned) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('Time interval not selected'),
      ));
      setState(() {
        //we need a range of values to slide with, start and end date only move forward with
        //proper intervals calculated also
        isSliderActive = false;
      });
      return;
    }

    int intervals = _calculateIntervals(startDate, endDate, intervalSelection);
    if (intervals > 0) {
      //Set the maximum range of the slider to the number of intervals calculated
      setState(() {
        _maxRange = intervals;
        lowerLabel = _dateFormat.format(calculateDateTimeFromSliderValue(0));
        upperLabel = _dateFormat
            .format(calculateDateTimeFromSliderValue(_maxRange.toDouble()));
        _currentRangeValues = RangeValues(0, _maxRange.toDouble());
        isSliderActive = true;
      });
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content:
              Text('Selected interval exceeds the date range or is unassigned'),
        ),
      );
      setState(() {
        isSliderActive = false;
      });
      return;
    }
  }

  //TODO:REDO THIS FUNCTION IN DBINTERFACE HANDLER!
  // This will be called when the slider range changes.
  void _updateVisibleCoordinates(RangeValues values) {
    DateTime startRangeDate = calculateDateTimeFromSliderValue(values.start);
    DateTime endRangeDate = calculateDateTimeFromSliderValue(values.end);

    // Assuming 'dbHandler.previousTimes' contains DateTime objects of the timestamps for each coordinate
    List<List<int>> _visibleCoordinates = List.empty(growable: true);
    for (int i = 0; i < dbHandler.previousCoordinates.length; i++) {
      if (dbHandler.previousTimes[i].isAfter(startRangeDate) &&
          dbHandler.previousTimes[i].isBefore(endRangeDate)) {
        _visibleCoordinates.add(dbHandler.previousCoordinates[i]);
      }
    }

    setState(() {
      // This will rebuild your widget with the new list of coordinates.
      visibleCoordinates = _visibleCoordinates;
    });
  }

  @override
  Widget build(BuildContext context) {
    final deviceSize = MediaQuery.of(context).size;
    List<List<int>> coordinates = dbHandler.coordinates;
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Locate Item',
        ),
        leading: IconButton(
          onPressed: () async {
            setState(() {
              itemSelected = false;
            });
          },
          icon: const Icon(Icons.arrow_back_sharp),
        ),
        actions: [
          /*IconButton(
            onPressed: () async {
              await showSearch(
                  context: context,
                  // delegate to customize the search bar
                  delegate: CustomSearchDelegate());
            },
            icon: const Icon(Icons.search),
          ),*/
          IconButton(
            onPressed: () async {
              dbHandler.clear();
              Navigator.pushAndRemoveUntil(
                context,
                MaterialPageRoute(builder: (context) => const MyHomePage()),
                (Route<dynamic> route) => false,
              );
            },
            icon: const Icon(Icons.home),
          ),
        ],
      ),
      body: InteractiveViewer(
        key: ValueKey(repaintTrigger), //key to trigger repaint
        child: CustomPaint(
          painter: PathPainter.create(
            visibleCoordinates,
            itemInfo,
            itemSelected,
            gridWidth,
            numBoxes,
            _currentRangeValues,
            startDate,
            endDate,
            _maxRange,
          ),
          child: Stack(
            children: [
              /*Image.asset(
                'assets/images/floorPlan.png',
                height: decodedImage.height.toDouble() + 20,
                width: decodedImage.width.toDouble() + 20,
                alignment: Alignment.center,
                // color: Color.fromARGB(255, 15, 147, 59),
              ),*/
              Positioned(
                left: deviceSize.width / 5, //center the grid
                top: deviceSize.height / 8, //center the grid
                child: SizedBox(
                  height: gridHeight,
                  width: gridWidth,
                  child: GridPaper(
                      color: Colors.green,
                      interval: gridWidth / numBoxes,
                      //get number of boxes in x direction by doing interval equals width/#boxes
                      divisions: 1,
                      subdivisions: 1),
                ),
              ),
              for (int i = 0; i <= numBoxes; i++) ...[
                for (int j = 0; j <= numBoxes; j++) ...[
                  Positioned(
                    //give the values according to your requirement
                    left: itemXCoordinate(deviceSize, i),
                    top: itemYCoordinate(deviceSize, j),
                    child: Text(
                      '($i,$j)',
                      style: TextStyle(
                          fontSize: deviceSize.width * 0.008,
                          color: Colors.black),
                    ),
                  ),
                ],
              ],
              ///////////////////////////////////////////////////////////////////////////////////////////////EVERYTHING ABOVE THIS LEAVE ALONE

              if (itemSelected == false) ...[
                for (int i = 0; i < coordinates.length; i++) ...[
                  Positioned(
                    left:
                        itemXCoordinateButton(deviceSize, coordinates[i].first),
                    top: itemYCoordinateButton(deviceSize, coordinates[i].last),
                    //give the values according to your requirement
                    child: IconButton(
                      onPressed: () async {
                        itemInfo = await dbHandler.getItemInfo(
                            coordinates[i].first,
                            coordinates[i].last,
                            calculateDateTimeFromSliderValue(
                                _currentRangeValues.end),
                            calculateDateTimeFromSliderValue(
                                _currentRangeValues.start));
                        setState(() {
                          if (itemInfo != null) {
                            itemSelected = true;
                          }
                        });
                      },
                      icon: const Icon(
                        Icons.star,
                        color: Colors.blue,
                      ),
                    ),
                  ),
                ],
              ],

              if (itemSelected == true) ...[
                if (dbHandler.previousCoordinates.isNotEmpty) ...[
                  for (int i = 0;
                      i < dbHandler.previousCoordinates.length;
                      i++) ...[
                    //TODO: Place this if statement check somewhere better
                    //TODO: Incorporate the visible coordinates into everywhere else in code where
                    //it's needed, however for now this manages icons appropriately
                    if (dbHandler.previousTimes.isNotEmpty &&
                        dbHandler.previousTimes[i].isBefore(
                            calculateDateTimeFromSliderValue(
                                _currentRangeValues.end)) &&
                        dbHandler.previousTimes[i].isAfter(
                            calculateDateTimeFromSliderValue(
                                _currentRangeValues.start))) ...[
                      //   Positioned(
                      //     left: itemXCoordinate(
                      //         deviceSize, dbHandler.previousCoordinates[i].first),
                      //     top: itemYCoordinate(
                      //         deviceSize, dbHandler.previousCoordinates[i].last),
                      //     //give the values according to your requirement
                      //     child: const Icon(
                      //       Icons.star,
                      //       color: Colors.red,
                      //     ),
                      //   ),
                      // ],
                      Positioned(
                        left: itemXCoordinate(deviceSize,
                                dbHandler.previousCoordinates[i].first) -
                            7,
                        top: itemYCoordinate(deviceSize,
                                dbHandler.previousCoordinates[i].last) -
                            7,
                        child: IconButton(
                          onPressed: () {
                            setState(() {
                              if (itemInfo != null) {
                                itemSelected = true;
                              }
                            });

                            // Invoke the dialog to show previous location info
                            showDialog(
                              context: context,
                              builder: (BuildContext context) {
                                // You might want to check if itemInfo is not null here
                                return AlertDialog(
                                  title: const Text('Location Details'),
                                  content: SingleChildScrollView(
                                    child: ListBody(
                                      children: <Widget>[
                                        Text('RFID#: ${itemInfo?.RFID ?? ''}'),
                                        Text(
                                            'Coordinates: (${dbHandler.previousCoordinates[i].first}, ${dbHandler.previousCoordinates[i].last})'),
                                        Text(
                                            'Timestamp: ${dbHandler.previousTimes[i].toString()}'),
                                      ],
                                    ),
                                  ),
                                  actions: <Widget>[
                                    TextButton(
                                      child: Text('Close'),
                                      onPressed: () {
                                        Navigator.of(context)
                                            .pop(); // Close the Dialog
                                      },
                                    ),
                                  ],
                                );
                              },
                            );
                          },
                          iconSize: 24.0,
                          icon: const Icon(
                            Icons.star,
                            color: Colors.red,
                          ),
                        ),
                      ),
                      // Positioned(
                      //   left: itemXCoordinate(deviceSize, 0) + 100,
                      //   top: itemYCoordinate(deviceSize, 16) + 120 + 20 * i,
                      //   //give the values according to your requirement
                      //   child: Text(
                      //       'RFID#: ${itemInfo!.RFID}, coordinates: (${dbHandler.previousCoordinates[i].first}, ${dbHandler.previousCoordinates[i].last}), timestamp: ${dbHandler.previousTimes[i].toString()}'),
                      // ),
                    ],
                  ],
                ],
                if (itemInfo!.timeStamp.isBefore(
                        calculateDateTimeFromSliderValue(
                            _currentRangeValues.end)) &&
                    itemInfo!.timeStamp.isAfter(
                        calculateDateTimeFromSliderValue(
                            _currentRangeValues.start))) ...[
                  Positioned(
                    left: itemXCoordinate(deviceSize, itemInfo!.xLocation),
                    top: itemYCoordinate(deviceSize, itemInfo!.yLocation),
                    //give the values according to your requirement
                    child: const Icon(
                      Icons.star,
                      color: Colors.blue,
                    ),
                  ),
                  Positioned(
                    left: itemXCoordinate(deviceSize, 0) +
                        35, //itemXCoordinate(deviceSize, itemInfo!.xLocation) +
                    //2, //itemXCoordinate(deviceSize, 0) + 100,
                    top: itemYCoordinate(deviceSize, 16) +
                        45, //itemYCoordinate(deviceSize, itemInfo!.yLocation) +
                    //2, //itemYCoordinate(deviceSize, 16) +
                    //100, //give the values according to your requirement
                    child: Text(
                        'RFID#: ${itemInfo!.RFID}, last coordinates: (${itemInfo!.xLocation}, ${itemInfo!.yLocation}), timestamp: ${itemInfo!.timeStamp.toString()}'),
                  ),
                ],
              ],

              Positioned(
                  left: itemXCoordinate(deviceSize, 0),
                  top: itemYCoordinate(deviceSize, 16) +
                      50, //give the values according to your requirement
                  child: SizedBox(
                      width: deviceSize.width * 0.6,
                      //child: SingleChildScrollView(
                      //Allows the entire screen to be scrollable
                      child: Column(//vertical content organizer
                          children: [
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: TextField(
                            controller: _startDateTimeController,
                            decoration: const InputDecoration(
                              labelText: 'Start Date-Time',
                              hintText: 'yyyy-MM-dd HH:mm',
                            ),
                            // onSubmitted: (_) => _updateSliderRange(),
                            // onEditingComplete: () => _updateSliderRange(),
                            //tried a different way
                            onSubmitted: (_) {
                              setState(() {
                                _updateSliderRange();
                              });
                            },
                            onEditingComplete: () {
                              setState(() {
                                _updateSliderRange();
                              });
                            },
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: TextField(
                            controller: _endDateTimeController,
                            decoration: const InputDecoration(
                              labelText: 'End Date-Time',
                              hintText: 'yyyy-MM-dd HH:mm',
                            ),
                            onSubmitted: (_) => _updateSliderRange(),
                            onEditingComplete: () => _updateSliderRange(),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: DropdownButton<Timespan>(
                            value: intervalSelection,
                            onChanged: (Timespan? newValue) {
                              setState(() {
                                intervalSelection = newValue!;
                                _updateSliderRange();
                              });
                            },
                            items: Timespan.values
                                .map<DropdownMenuItem<Timespan>>(
                                    (Timespan value) {
                              return DropdownMenuItem<Timespan>(
                                value: value,
                                child: Text(value.name),
                              );
                            }).toList(),
                          ),
                        ),
                        SizedBox(
                          width: deviceSize.width * 0.6,
                          child: Visibility(
                            visible:
                                isSliderActive, // This controls the visibility of the slider based on whether it should be active or not
                            child: SliderTheme(
                              data: SliderTheme.of(context).copyWith(
                                activeTrackColor: Colors.red[700],
                                inactiveTrackColor: Colors.red[100],
                                trackShape: const RoundedRectSliderTrackShape(),
                                trackHeight: 4.0,
                                thumbShape: const RoundSliderThumbShape(
                                    enabledThumbRadius: 0.1),
                                thumbColor: Colors.redAccent,
                                overlayColor: Colors.red.withAlpha(32),
                                overlayShape: const RoundSliderOverlayShape(
                                    overlayRadius: 28.0),
                                tickMarkShape: const RoundSliderTickMarkShape(),
                                activeTickMarkColor: Colors.red[700],
                                inactiveTickMarkColor: Colors.red[100],
                                valueIndicatorShape:
                                    const PaddleSliderValueIndicatorShape(),
                                valueIndicatorColor: Colors.redAccent,
                                valueIndicatorTextStyle: const TextStyle(
                                  color: Colors.white,
                                ),
                              ),
                              child: RangeSlider(
                                values: _currentRangeValues,
                                min: 0,
                                max: _maxRange
                                    .toDouble(), // Make sure this uses _maxRange from your state
                                divisions:
                                    _maxRange, // This could be dynamic based on your _maxRange
                                labels: RangeLabels(
                                  lowerLabel,
                                  upperLabel,
                                ),
                                onChanged: (RangeValues values) {
                                  if (_debounce?.isActive ?? false) {
                                    _debounce?.cancel();
                                  }
                                  _debounce = Timer(
                                      const Duration(milliseconds: 5), () {
                                    WidgetsBinding.instance
                                        .addPostFrameCallback((_) {
                                      if (mounted) {
                                        setState(() {
                                          lowerLabel = _dateFormat.format(
                                              calculateDateTimeFromSliderValue(
                                                  values.start));
                                          upperLabel = _dateFormat.format(
                                              calculateDateTimeFromSliderValue(
                                                  values.end));
                                          _currentRangeValues = values;
                                          _updateVisibleCoordinates(values);
                                        });
                                      }
                                    });
                                  });
                                },
                                onChangeEnd: (RangeValues values) {
                                  WidgetsBinding.instance!
                                      .addPostFrameCallback((_) {
                                    if (mounted) {
                                      setState(() {
                                        repaintTrigger++;
                                      });
                                    }
                                  });
                                },
                              ),
                            ),
                          ),
                        ),
                      ])
                      //)
                      )),
            ],
          ),
        ),
      ),
    );
  }
}

// class InteractiveGrid extends ConsumerWidget {
//   final ItemInfo? itemInfo;
//   final bool itemSelected;
//   final double gridWidth;
//   final int numBoxes;
//   final RangeValues currentRangeValues;
//   final DateTime startDate;
//   final DateTime endDate;
//   final int maxRange;

//   const InteractiveGrid({
//     Key? key,
//     this.itemInfo,
//     required this.itemSelected,
//     required this.gridWidth,
//     required this.numBoxes,
//     required this.currentRangeValues,
//     required this.startDate,
//     required this.endDate,
//     required this.maxRange,
//   }) : super(key: key);
// }

// @override
// Widget build(BuildContext context, WidgetRef ref){
//   final coordinates = ref.watch(visibleCoordinatesProvider)
// }
class PathPainter extends CustomPainter {
  List<List<int>> coordinates = List.empty(growable: true);
  ItemInfo? itemInfo;
  bool itemSelected = false;
  double gridWidth = 0;
  int numBoxes = 0;
  RangeValues rangeValues = const RangeValues(0, 24);
  //Arbitrary Fill-in functions for start date and end date values
  //which are parsed from the user text entry
  DateTime startDate = DateTime.now()
      .subtract(const Duration(hours: 48)); //DateTime? _startDate;
  DateTime endDate =
      DateTime.now().subtract(const Duration(hours: 24)); //DateTime? _endDate
  //timespan to select the intervals to become
  //Timespan intervalSelection = Timespan.hours;
  int _maxRange = 24;

  DateTime calculateDateTimeFromSliderValue(double sliderValue) {
    int totalDurationInSeconds = endDate.difference(startDate).inSeconds;
    //Calculate the number of seconds that the slider value represents
    int sliderSeconds =
        (sliderValue * totalDurationInSeconds / _maxRange).round();
    return startDate.add(Duration(seconds: sliderSeconds));
  }

  @override
  PathPainter._create(
      List<List<int>> coords,
      ItemInfo? item,
      bool selected,
      double width,
      int boxes,
      RangeValues values,
      DateTime startTime,
      DateTime endTime,
      //Timespan intervalSelection
      int _maxRange) {
    coordinates = coords;
    itemInfo = item;
    itemSelected = selected;
    gridWidth = width;
    numBoxes = boxes;
    rangeValues = values;
    startTime = startTime;
    endTime = endTime;
    _maxRange = _maxRange;
    //intervalSelection = intervalSelection;
  }

  //create an instance of pathPainter to use throughout app
  static PathPainter create(
      List<List<int>> coords,
      ItemInfo? item,
      bool selected,
      double width,
      int boxes,
      RangeValues values,
      DateTime startDate,
      DateTime endDate,
      int _maxRange
      //Timespan timeInterval
      ) {
    return PathPainter._create(coords, item, selected, width, boxes, values,
        startDate, endDate, _maxRange);
  }

  @override
  void paint(Canvas canvas, Size size) {
    if (itemSelected == true) {
      Paint paint = Paint()
        ..color = Colors.black
        ..style = PaintingStyle.stroke
        ..strokeWidth = 4.0;

      for (int i = 0; i < (coordinates.length - 1); i++) {
        // if(dbHandler.previousTimes.isNotEmpty &&
        //     dbHandler.previousTimes[i].isBefore(
        //         calculateDateTimeFromSliderValue(rangeValues.end)) &&
        //     dbHandler.previousTimes[i].isAfter(
        //         calculateDateTimeFromSliderValue(rangeValues.start))) {
        Path path = Path();
        // Draws a line from moveTo to LineTo
        path.moveTo(itemXCoordinate(size, coordinates[i].first),
            itemYCoordinate(size, coordinates[i].last));
        path.lineTo(itemXCoordinate(size, coordinates[i + 1].first),
            itemYCoordinate(size, coordinates[i + 1].last));
        path.close();
        canvas.drawPath(path, paint);
        //}
      }

      if (coordinates.isNotEmpty &&
              itemInfo!.timeStamp.isBefore(
                  calculateDateTimeFromSliderValue(rangeValues.end)) &&
              itemInfo!.timeStamp
                  .isAfter(calculateDateTimeFromSliderValue(rangeValues.start))

          // itemInfo!.timeStamp.isBefore(DateTime.now()
          //     .subtract(Duration(hours: rangeValues.start.round()))) &&
          // itemInfo!.timeStamp.isAfter(DateTime.now()
          //     .subtract(Duration(hours: rangeValues.end.round())))
          ) {
        Path path = Path();
        // Draws a line from moveTo to LineTo
        path.moveTo(itemXCoordinate(size, coordinates.first.first),
            itemYCoordinate(size, coordinates.first.last));
        path.lineTo(itemXCoordinate(size, itemInfo!.xLocation),
            itemYCoordinate(size, itemInfo!.yLocation));
        path.close();
        canvas.drawPath(path, paint);
      }
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
  // @override
  // bool shouldRepaint(covariant CustomPainter oldDelegate) {
  //   // Compare old data with current data to decide if repainting is necessary
  //   return oldData != newData;
  // }

  //use if using just Icon
  double itemXCoordinate(Size deviceSize, int itemXLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 0;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.width / 5) -
        pixelCorrection +
        (boxWidth * itemXLocation);
  }

  //use if using just Icon
  double itemYCoordinate(Size deviceSize, int itemYLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 10;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.height / 8) +
        pixelCorrection +
        (boxWidth * itemYLocation);
  }

  //use if using Icon Button
  double itemXCoordinateButton(Size deviceSize, int itemXLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 24;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.width / 5) -
        pixelCorrection +
        (boxWidth * itemXLocation);
  }

  //use if using Icon Button
  double itemYCoordinateButton(Size deviceSize, int itemYLocation) {
    //correct the pixel offset of the star
    double pixelCorrection = 24;
    //box width
    double boxWidth = gridWidth / numBoxes;
    return (deviceSize.height / 8) -
        pixelCorrection +
        (boxWidth * itemYLocation);
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 519 pos 7: '_ticker != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:519:7)
animation_controller.dart:519
#3      _RenderRangeSlider._updateForHover (package:flutter/src/material/range_slider.dart:1096:32)
range_slider.dart:1096
#4      _RenderRangeSlider.hoveringEndThumb= (package:flutter/src/material/range_slider.dart:1088:5)
range_slider.dart:1088
#5      _RenderRangeSlider.handleEvent (package:flutter/src/material/range_slider.dart:1362:9)
range_slider.dart:1362
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
binding.dart:475
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
binding.dart:430
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
binding.dart:420
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
binding.dart:383
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
binding.dart:330
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
binding.dart:299
#12     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#13     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
platform_dispatcher.dart:429
#14     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
hooks.dart:262
(elided 2 frames from class _AssertionError)

Event: PointerMoveEvent#bf547(position: Offset(596.0, 1147.0))
    position: Offset(596.0, 1147.0)
Target: _RenderRangeSlider#3c9fc DISPOSED
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=614.4, 0.0<=h<=Infinity)
    semantics node: SemanticsNode#1895
    semantic boundary
    size: Size(614.4, 56.0)
════════════════════════════════════════════════════════════════════════════════
Restarted application in 379ms.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by ijashuzain** [comment]
Based on the detailed issue description and code sample provided, it seems the problem is related to the `AnimationController` being used in conjunction with a range slider to filter coordinate points and display icons on a grid based on range values. The app crashes when the slider is moved quickly, particularly at times when an icon is supposed to appear. This is indicated by the exception related to `AnimationController.reverse()` being called after `AnimationController.dispose()`. This suggests that there might be an issue with how the lifecycle of the `AnimationController` is being managed in relation to the dynamic UI updates triggered by the slider.

Make sure that the `AnimationController` is being disposed of properly by overriding the dispose method of your State class. This will prevent attempts to use the controller after it has been disposed of.

```
@override
void dispose() {
  _animationController.dispose();
  super.dispose();
}
```

Also avoid Updating UI in a Disposed State
When performing UI updates based on asynchronous operations or after some delay (for example, as a result of debouncing), always check if the State is still mounted before proceeding with setState or any operation that modifies the UI.

```
if(mounted) {
  setState(() {
    // Update your UI here
  });
}
```

**Comment by huycozy** [comment]
@justintimewatkins Your sample code is a complex code that contains undefined components/classes and also use 3rd package. 

For us to further investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
