### ISSUE TITLE
`Linux_android image_list_jit_reported_duration` keeps hanging/timingout on linux-5

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#145783]
Issue started on 03/19/2024. First failure happened on https://github.com/flutter/flutter/commit/88a9b58dd8b1da6f43161d46792feff814588e05
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/14156/overview

Other example builds: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/14284/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/14277/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/14271/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20image_list_jit_reported_duration/14265/overview
```
[2024-03-26 12:36:44.637326] [STDOUT] stdout: [   +8 ms] Shutdown hooks complete
[2024-03-26 12:36:44.637359] [STDOUT] stdout: [        ] exiting with code 0
[2024-03-26 12:36:48.224238] [STDOUT] adb logcat: 05-08 01:32:02.440  1451  1502 I ActivityManager: Displayed com.example.image_list/io.flutter.embedding.android.FlutterActivity: +7s259ms
[2024-03-26 12:36:54.874400] [STDOUT] adb logcat: 05-08 01:32:09.092  1451  1479 I ActivityManager: Waited long enough for: ServiceRecord{f524098 u0 com.amazon.mShop.android/com.amazon.mas.client.locker.service.appmgr.AppManagerService}
[2024-03-26 12:36:54.905954] [STDOUT] adb logcat: 05-08 01:32:09.123  1451  1479 I ActivityManager: Waited long enough for: ServiceRecord{4c0dd29 u0 com.amazon.mShop.android/com.amazon.venezia.notification.NotificationService}
[2024-03-26 12:36:56.240151] [STDOUT] adb logcat: 05-08 01:32:10.455  1451  4563 I ActivityManager: Killing 6780:com.google.android.gm/u0a95 (adj 904): empty #13
[2024-03-26 12:36:56.240952] [STDOUT] adb logcat: 05-08 01:32:10.456  1451  4563 I ActivityManager: Killing 5386:com.google.android.calendar/u0a82 (adj 906): empty #14
[2024-03-26 12:37:26.685296] [STDOUT] adb logcat: 05-08 01:32:40.901  1451  3964 I ActivityManager: Killing 6538:com.android.vending:download_service/u0a63 (adj 906): empty #13
[2024-03-26 12:37:26.686206] [STDOUT] adb logcat: 05-08 01:32:40.902  1451  3964 I ActivityManager: Killing 6654:com.android.printspooler/u0a118 (adj 906): empty #14
[2024-03-26 12:37:40.053104] [STDOUT] adb logcat: 05-08 01:32:54.269  1451  4565 I ActivityManager: Killing 6737:com.android.providers.calendar/u0a23 (adj 904): empty #13
```

Compared to a successful build:
```
[2024-03-26 13:19:02.050374] [STDOUT] stdout: [  +24 ms] Shutdown hooks complete
[2024-03-26 13:19:02.050443] [STDOUT] stdout: [        ] exiting with code 0
[2024-03-26 13:19:05.129192] [STDOUT] adb logcat: 03-26 16:14:37.259  1451  1463 I ActivityManager: Killing 14621:com.google.process.gapps/u0a34 (adj 906): empty #13
[2024-03-26 13:19:05.138879] [STDOUT] adb logcat: 03-26 16:14:37.265  1451  1501 I ActivityManager: Displayed com.example.image_list/io.flutter.embedding.android.FlutterActivity: +6s734ms
[2024-03-26 13:19:05.157761] [STDOUT] adb logcat: 03-26 16:14:37.289  1451  1479 I ActivityManager: Killing 14604:com.android.chrome/u0a78 (adj 906): empty #13
[2024-03-26 13:19:12.643918] [STDOUT] adb logcat: 03-26 16:14:44.774  1451  4624 I ActivityManager: Killing 14548:com.google.android.apps.maps/u0a103 (adj 906): empty #13
[2024-03-26 13:19:12.644257] [STDOUT] adb logcat: 03-26 16:14:44.775  1451  4624 I ActivityManager: Killing 14661:com.android.documentsui/u0a27 (adj 906): empty #14
[2024-03-26 13:19:18.278869] [STDOUT] adb logcat: 03-26 16:14:50.411 15125 15144 I flutter : ===image_list=== all loaded in 15357ms.
[2024-03-26 13:19:18.279637] [STDOUT] terminating...
[2024-03-26 13:19:18.281265] [STDOUT] Executing "/opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223CXXGL shell am force-stop com.example.image_list" in "/opt/s/w/ir/x/w/recipe_cleanup/tmp5xab7k77/flutter sdk/examples/image_list" with environment {BOT: true, LANG: en_US.UTF-8}
[2024-03-26 13:19:19.342624] [STDOUT] adb logcat: 03-26 16:14:51.474  1451  4014 I ActivityManager: Force stopping com.example.image_list appid=10358 user=0: from pid 15352
[2024-03-26 13:19:19.343623] [STDOUT] adb logcat: 03-26 16:14:51.475  1451  4014 I ActivityManager: Killing 15125:com.example.image_list/u0a358 (adj 0): stop com.example.image_list
[2024-03-26 13:19:19.344770] [STDOUT] adb logcat: 03-26 16:14:51.477  1451  4014 W ActivityManager: Force removing ActivityRecord{b80478e u0 com.example.image_list/io.flutter.embedding.android.FlutterActivity t183}: app died, no saved state
[2024-03-26 13:19:19.381007] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 3964:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
[2024-03-26 13:19:19.381300] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: java.lang.Throwable
[2024-03-26 13:19:19.381406] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18226)
[2024-03-26 13:19:19.381482] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18826)
[2024-03-26 13:19:19.381551] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
[2024-03-26 13:19:19.381619] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2906)
[2024-03-26 13:19:19.381687] [STDOUT] adb logcat: 03-26 16:14:51.509  1451  3739 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
[2024-03-26 13:19:19.404620] [STDOUT] adb logcat aborted
[2024-03-26 13:19:19.405428] [STDOUT] terminating adb logcat
[2024-03-26 13:19:19.407483] [STDOUT] closing logcat stream
[2024-03-26 13:19:19.420615] [STDOUT] adb logcat process terminated with exit code -15
[2024-03-26 13:19:19.427240] [STDOUT] Checking for reboot
[image_list_jit_reported_duration] Process terminated with exit code 0.
```

The hanging task seems stuck in adb logcat operations.

**Comment by keyonghan** [comment]
@zanderso Do you have any insight what may cause the hang? Since it's happening only on Linux5, with a high chance it's a bot specific issue. But linux5 seems only failing this specific test (all other tests are running okay consistently).

**Comment by zanderso** [comment]
Nothing pops out to me. It still looks like the full device logs don't capture the time period of the hanging test. I don't know that we'd find anything in there, but that might be good to fix. Also missing from this test is a screenshot capture on a timeout. Again might not be helpful for this case, but would be generally useful.

**Comment by keyonghan** [comment]
> It still looks like the full device logs don't capture the time period of the hanging test. 

Do you mean the adb log? I do see lots of logs populated to https://storage.googleapis.com/flutter_logs/flutter/b39660df8fcd67f48616b84b834556f9f6ead264/image_list_jit_reported_duration/c87e413e-4ac2-43fe-8356-2b61c229f147/ZY223CB7BV.log

There seems some time mismatch from the build log and the adb log though:
Last piece of the hanging build log:
<img width="1554" alt="Screenshot 2024-03-27 at 9 52 07 AM" src="https://github.com/flutter/flutter/assets/54558023/68fb34e1-701a-41a0-a877-0e29827a31a5">

**Comment by keyonghan** [comment]
At the same time, @kentnguyen99 Do you mind taking a look at linux-5 and the phone to see if anything suspicious?

**Comment by kentnguyen99** [comment]
@keyonghan, The phone device was disconnected from machine, connection has been restored. 
Can you check again from your end?

**Comment by kentnguyen99** [comment]
The phone device was hung and got disconnect from machine, software connection not not physical cable.

**Comment by keyonghan** [comment]
> The phone device was hung and got disconnect from machine, software connection not not physical cable.

Do you still remember how the screen looks like? Could yo help monitor this device a bit, and help upload a screenshot when it next hangs?

**Comment by kentnguyen99** [comment]
Screen was fuzzy, no text or picture and did not make any senses, will take picture next time.

**Comment by keyonghan** [comment]
Thanks @kentnguyen99 . Please upload the screenshot here if you see it again.
Quarantined the bot for now: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-5

**Comment by keyonghan** [comment]
@kentnguyen99 Do you know if we have a recent factory reset or config changes of this phone? @godofredoc mentioned that we hit this issue locally a while ago when the test was not running from the home screen, or due to landscape or vertical layout of the screen.

**Comment by kentnguyen99** [comment]
No changes on phone device.

**Comment by sealesj** [comment]
Are there any updates on this issue?

**Comment by keyonghan** [comment]
The bot has been quarantined, but we would not expect any repro.
@ricardoamador Could you help run several LEDs to repro the issue and work with @kentnguyen99 to capture the screen if it repros?

**Comment by ricardoamador** [comment]
Yes I can. Let me catch up on the issue and I will reach out to @kentnguyen99 with questions.

**Comment by ricardoamador** [comment]
Just making a note that this failure began to occur on 03/19/2024.

**Comment by ricardoamador** [comment]
@yusuf-goog Is it possible to get this particular phone to someone's desk?
