### ISSUE TITLE
[tool_crash] _TypeError: (#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4))

### ISSUE THREAD

**Issue by godwin-jg** [flutter/flutter#145854]
## Command
```
flutter --version
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4))
```
#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4)
#1      _FlutterVersionGit.frameworkCommitDate (package:flutter_tools/src/version.dart:495:37)
#2      FlutterVersion.toString (package:flutter_tools/src/version.dart:225:99)
#3      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/r

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/145781
