### ISSUE TITLE
[Deferred component] Always stuck after downloading the dynamic module

### ISSUE THREAD

**Issue by mrhabibi** [flutter/flutter#145876]
### Steps to reproduce

Simply following https://docs.flutter.dev/perf/deferred-components on a simple flutter app, and upload the AAB to internal app sharing. (No issue when testing locally using bundletool)

Install the app and open the app normally, and when downloading the dynamic module, it's stuck on infinite loading. When force closing the app, the dynamic module is listed as downloaded. When reopening the app, the app's stuck on the splash screen and can never be opened again.

Notes:
- Obfusaction active or not has no impact.
- Emulator or real device has no impact.
- I've made some Android apps before with Play Core SDK but never got this kind of issue

### Expected results

After downloading the dynamic module, the loading is finished and I can normally use the feature inside the dynamic module.

### Actual results

Stuck on infinite loading when downloading. And after force restart, it's stuck on splash screen.

### Code sample

<details open><summary>Code sample</summary>

```yaml
loading-units:
  - id: 2
    libraries:
      - package:example/navigation/other_entry.dart
      - package:example/navigation/other_module.dart
      - package:example/page/deferred_page.dart
      - package:example/page/deferred_tab.dart
      - package:example/page/deferred_component.dart
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/13618227/a4c68284-0f55-4e3d-acba-ad8264489c95

</details>

### Logs

<details open><summary>Logs</summary>

```console
2024-03-28 08:37:50.233  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.dm': No such file or directory
2024-03-28 08:37:50.233  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.dm': No such file or directory
2024-03-28 08:37:50.235  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.config.arm64_v8a.dm': No such file or directory
2024-03-28 08:37:50.235  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.config.arm64_v8a.dm': No such file or directory
2024-03-28 08:37:50.237  4960-4960  .seller.android         com.bukalapak.seller.android         W  Entry not found
2024-03-28 08:37:50.237  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.config.xxhdpi.dm': No such file or directory
2024-03-28 08:37:50.237  4960-4960  ziparchive              com.bukalapak.seller.android         W  Unable to open '/data/app/~~v4oL6MBa3Rdrm2NQkMZjHQ==/com.bukalapak.seller.android-LC5xaYbuBfQ3c8ssY89HwQ==/split_other.config.xxhdpi.dm': No such file or directory
2024-03-28 08:37:50.237  4960-4960  .seller.android         com.bukalapak.seller.android         W  Entry not found
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.4.1 23E224 darwin-arm64, locale en-ID)
    • Flutter version 3.7.12 on channel stable at /Users/mrhabibi/flutter/3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (12 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mrhabibi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mrhabibi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[!] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by mrhabibi** [comment]
I've made a repository to reproduce the issue: https://github.com/mrhabibi/deferred_component_example which following the [deferred component guideline](https://docs.flutter.dev/perf/deferred-components)

**Comment by darshankawar** [comment]
@mrhabibi 
You are on very old version of stable, can you upgrade to latest (3.19.4) and re-run your scenario to check if the reported behavior still persists or not ?

**Comment by mrhabibi** [comment]
Hi @darshankawar, thanks for your suggestion, I'm using flutter 3.7.12 to maintain the project which hasn't been ready to use the newer version.

But after I adapt the flutter 3.19.5 SDK on [my example repository](https://github.com/mrhabibi/deferred_component_example) (the changes have been pushed as well) and I uploaded the AAB to the internal app sharing, the problem still persists.

So I guess flutter version isn't the culprit, seems like I miss adding a small config to make the deferred component works.

Here's the screen recording showing it's stuck when executing `loadLibrary()`:

[screencast-Genymotion-2024-04-01_11.01.22.39.webm](https://github.com/flutter/flutter/assets/13618227/bdbf414b-35ed-41fa-a294-f6f9e2627a81)

Here's my new flutter doctor output:

```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-ID)
    • Flutter version 3.19.5 on channel stable at /Users/mrhabibi/flutter/3.19
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mrhabibi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mrhabibi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)            
    • A50 (mobile)    • 127.0.0.1:6555 • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos          • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)    • chrome         • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the update.
Please check if your issue resembles https://github.com/flutter/flutter/issues/97149 or not.

**Comment by mrhabibi** [comment]
@darshankawar after reading the issue until the last reply, I think it's a bit different where my issue occurs every time since the first download, where the issue you mentioned occurs next app launch after the first successful download.

I've tried some solutions given on the replies, but unfortunately none works.

**Comment by gmackall** [comment]
from android triage: @darshankawar were ever able to reproduce this following the getting started documentation?

**Comment by darshankawar** [comment]
> were ever able to reproduce this following the getting started documentation?

@gmackall Hello, no, I wasn't able to replicate it. I tried locally in release mode but maybe we need to upload it on playstore and then install it on device to check if it persists or not.

**Comment by mrhabibi** [comment]
> but maybe we need to upload it on playstore and then install it on device to check if it persists or not.

Exactly that's where the problem occurs, I couldn't reproduce the problem as well when testing locally with `bundletool.jar` based on [this](https://docs.flutter.dev/perf/deferred-components#running-the-app-locally).

**Comment by MICKEY88661** [comment]
I am facing the same problem here.
I could found the same warning in the logcat
`
Unable to open '/data/app/~~edDJVlV2ZaNE5FTk6JVTHw==/com.xxxM2jqH0QDHEcImNlUFFuO1A==/split_audiosComponent.dm': No such file or directory
`

**Comment by Levyks** [comment]
@mrhabibi were you ever able to fix this? I'm having the same exact issue

**Comment by mrhabibi** [comment]
@Levyks not yet, I didn't use Play Feature Delivery yet for my app due to this issue.

@darshankawar Any update on this?

**Comment by mrhabibi** [comment]
@Levyks I was using Android 33 device for testing, and I'm not really sure that's related because the new version of Play Core SDK was just released, whereas this issue happened since the very beginning of deferred component on Flutter was invented I guess.

But I'm looking forward for the result! maybe somehow it solves this issue as well.

**Comment by Levyks** [comment]
So, update, the app crashes as soon as I call `loadLibrary()` when using `com.google.android.play:feature-delivery`, probably due to some incompatibility.

> When reopening the app, the app's stuck on the splash screen and can never be opened again (the `loadLibrary()` is now done in startup because the dynamic module has been downloaded)

However, while I was playing a bit with the native Play Feature Delivery feature (without using flutter's Deferred Components wrapper), I also got this problem of the app being stuck in the splash screen on the next initialization after the module install (with exactly the same error in the logs of being unable to open some split `.dm` file), and that was solved by replacing `com.google.android.play:core` with `com.google.android.play:feature-delivery` so maybe that still has something to do with it?

**Comment by andreasunterhuber** [comment]
@Levyks can you confirm that Deferred components work by using the `com.google.android.play:feature-delivery` and probably the `com.google.android.play:asset-delivery` with current flutter releases and SDK 34?  

Gradle example
```
dependencies {
    // REMOVED: implementation "com.google.android.play:core:1.8.0"
    implementation 'com.google.android.play:asset-delivery:2.2.2'
    implementation 'com.google.android.play:feature-delivery:2.1.0'
}
```

**Comment by AlexisDeslandes** [comment]
Hello, I started working on this subject.

in component package, src/main/AndroidManifest.xml, I had to add this in manifest to make appbundle command work :
```
<application
        android:hasCode="false">
    </application>
```

The issue is now that we cannot upload .aab with com.google.android.play:core as it's incompatible with android 14.
I tried with :

```
implementation 'com.google.android.play:asset-delivery:2.2.2'
implementation 'com.google.android.play:feature-delivery:2.1.0'
```

and other new split libraries, but flutter code FlutterPlayStoreSplitApplication seems only to accept  com.google.android.play:core. There are some class missing.

**Comment by dev-aman** [comment]
We are also facing similar exception while using `asset-delivery` and `feature-delivery` 

```
implementation 'com.google.android.play:asset-delivery:2.2.2'
implementation 'com.google.android.play:feature-delivery:2.1.0'
```

Exception: 

```[ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.NoSuchMethodError: No interface method startInstall(Lcom/google/android/play/core/splitinstall/d;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/splitinstall/b; or its super classes (declaration of 'com.google.android.play.core.splitinstall.b' appears in /data/app/~~59qUA0Ti_SI9mtBQfBIMDg==/com.example.abcd-HhdCKq-amkdadamkda==/base.apk!classes2.dex)
                                                                                                    	at io.flutter.embedding.engine.deferredcomponents.PlayStoreDeferredComponentManager.installDeferredComponent(PlayStoreDeferredComponentManager.java:7)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.requestDartDeferredLibrary(FlutterJNI.java:2)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:164)
                                                                                                    	at android.os.Looper.loop(Looper.java:296)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8227)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)```

This is probably due to `FlutterPlayStoreSplitApplication` uses `com.google.android.play.core` internally. If this is the reason we except an update from flutter team on this.
