### ISSUE TITLE
[go_router] remove requirement for top level path to start with `/`

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#145867]
### Steps to reproduce

Create a GoRoute placed at the root with a path not starting with `/`.

### Expected results

It should work. It violates some oop principles where an object must be in a valid state after construction. 

### Actual results

assertion throws: top-level path must start with \"/\"

### Code sample

```
GoRouter(
  routes: [
       GoRoute(
          path:  'root-level',
          builder: (context, state) => Text('')),
       ),
  ]
);
```

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.22631.3296], locale en-BE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by darshankawar** [comment]
The exception thrown is as below:

<details>
<summary> console error log </summary>

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building MyApp(dirty):
top-level path must start with "/": GoRoute#49137(name: null, path: "root-level")
'package:go_router/src/configuration.dart':
Failed assertion: line 40 pos 18: 'route.path.startsWith('/')'

The relevant error-causing widget was: 
  MyApp MyApp:file:///Users/dhs/Documents/NCFlutter/app_foo_stable/lib/main.dart:5:16
When the exception was thrown, this was the stack: 
#2      RouteConfiguration._debugCheckPath (package:go_router/src/configuration.dart:40:18)
#3      RouteConfiguration._onRoutingTableChanged (package:go_router/src/configuration.dart:195:12)
#4      new RouteConfiguration (package:go_router/src/configuration.dart:31:5)
#5      new GoRouter.routingConfig (package:go_router/src/router.dart:205:21)
#6      new GoRouter (package:go_router/src/router.dart:142:21)
#7      RouterStuff.router (package:app_foo_stable/main.dart:30:28)
#8      RouterStuff.router (package:app_foo_stable/main.dart)
#9      MyApp.build (package:app_foo_stable/main.dart:20:33)
#10     StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462:5)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
...     Normal element mounting (27 frames)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#43     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:291:16)
#44     _RawViewElement.mount (package:flutter/src/widgets/view.dart:314:5)
...     Normal element mounting (7 frames)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#53     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1354:16)
#54     RootElement.mount (package:flutter/src/widgets/binding.dart:1323:5)
#55     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1276:18)
#56     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2844:19)
#57     RootWidget.attach (package:flutter/src/widgets/binding.dart:1275:13)
#58     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1088:27)
#59     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1070:5)
#60     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1056:7)
#64     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================

```

</details>


<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.21.0-15.0.pre.19, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.21.0-15.0.pre.19 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c09c65ff46 (2 hours ago), 2024-03-26 22:41:11 -0400
    • Engine revision d872d50e53
    • Dart version 3.4.0 (build 3.4.0-275.0.dev)
    • DevTools version 2.34.0-dev.12
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
