### ISSUE TITLE
App crashes on Android, works fine on ios and emulator

### ISSUE THREAD

**Issue by Karjan1** [flutter/flutter#145809]
### Steps to reproduce

Reproducing is an issue. App is publicly available in stores, issue happens on version available to internal testers (I could add additional people if it helps).
Issue happens when creating build locally and with Codemagic.

### Expected results

App should behave the same on android emulators and with release build. Optimally not crash, but with local crash I can try to debug the issue.

### Actual results

It works fine on local emulators. It also works with release build uploaded to ios store. App crashes only on android right after start. 

### Code sample

NONE

### Logs

There is Sentry integration in project with Proguard. From that I get following stack trace
<details open><summary>Stack Trace</summary>

```console
java.lang.NoSuchMethodException: U.u0.values []
    at java.lang.Class.getMethod(Class.java:2072)
    at java.lang.Class.getDeclaredMethod(Class.java:2050)
    at java.lang.Enum.enumValues(Enum.java:267)
    at java.lang.Enum.access$000(Enum.java:61)
    at java.lang.Enum$1.create(Enum.java:277)
    at java.lang.Enum$1.create(Enum.java:275)
    at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
    at java.lang.Enum.getSharedConstants(Enum.java:289)
    at java.lang.Class.getEnumConstantsShared(Class.java:2428)
    at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
    at java.util.EnumMap.<init>(EnumMap.java:138)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.createOutputPrefixToVariantMap(AesSivProtoSerialization.java:84)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.<clinit>(AesSivProtoSerialization.java:101)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.register(AesSivProtoSerialization.java:206)
    at com.google.crypto.tink.daead.AesSivKeyManager.register(AesSivKeyManager.java:181)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.register(DeterministicAeadConfig.java:98)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.<clinit>(DeterministicAeadConfig.java:58)
    at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:116)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$editor$2.invoke$bridge(EncryptedKeyValueRepository.kt:0)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:20)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:48)
    at com.amazonaws.amplify.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:33)
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion.setUp$lambda-1$lambda-0
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion$$InternalSyntheticLambda$1$9f51da8474726535dca027d77902b9d32fe141a7a65ba8b74270f7a9893ab2de$0.onMessage$bridge(R8$$SyntheticClass:0)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage$bridge(BasicMessageChannel.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$1$5dd8b6f7959f08bc8717eff7469e77e06ef5aed51cc0cee17f1e13794798223f$0.run
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.$r8$lambda$F0iXMzLdPiwUET1ugdCo3vpOFvI(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$InternalSyntheticLambda$2$87f003a9f337bebdd0ba7a08cc7e573e8bd1ce25d26d2f3d3923593655f1df5b$0.run$bridge
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
java.lang.RuntimeException: java.lang.NoSuchMethodException: U.u0.values []
    at java.lang.Enum.enumValues(Enum.java:270)
    at java.lang.Enum.access$000(Enum.java:61)
    at java.lang.Enum$1.create(Enum.java:277)
    at java.lang.Enum$1.create(Enum.java:275)
    at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
    at java.lang.Enum.getSharedConstants(Enum.java:289)
    at java.lang.Class.getEnumConstantsShared(Class.java:2428)
    at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
    at java.util.EnumMap.<init>(EnumMap.java:138)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.createOutputPrefixToVariantMap(AesSivProtoSerialization.java:84)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.<clinit>(AesSivProtoSerialization.java:101)
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.register(AesSivProtoSerialization.java:206)
    at com.google.crypto.tink.daead.AesSivKeyManager.register(AesSivKeyManager.java:181)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.register(DeterministicAeadConfig.java:98)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.<clinit>(DeterministicAeadConfig.java:58)
    at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:116)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$editor$2.invoke$bridge(EncryptedKeyValueRepository.kt:0)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:20)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:48)
    at com.amazonaws.amplify.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:33)
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion.setUp$lambda-1$lambda-0
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion$$InternalSyntheticLambda$1$9f51da8474726535dca027d77902b9d32fe141a7a65ba8b74270f7a9893ab2de$0.onMessage$bridge(R8$$SyntheticClass:0)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage$bridge(BasicMessageChannel.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$1$5dd8b6f7959f08bc8717eff7469e77e06ef5aed51cc0cee17f1e13794798223f$0.run
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.$r8$lambda$F0iXMzLdPiwUET1ugdCo3vpOFvI(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$InternalSyntheticLambda$2$87f003a9f337bebdd0ba7a08cc7e573e8bd1ce25d26d2f3d3923593655f1df5b$0.run$bridge
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
java.lang.ExceptionInInitializerError: null
    at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.register(AesSivProtoSerialization.java:206)
    at com.google.crypto.tink.daead.AesSivKeyManager.register(AesSivKeyManager.java:181)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.register(DeterministicAeadConfig.java:98)
    at com.google.crypto.tink.daead.DeterministicAeadConfig.<clinit>(DeterministicAeadConfig.java:58)
    at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:116)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$editor$2.invoke$bridge(EncryptedKeyValueRepository.kt:0)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:20)
    at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:48)
    at com.amazonaws.amplify.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:33)
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion.setUp$lambda-1$lambda-0
    at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion$$InternalSyntheticLambda$1$9f51da8474726535dca027d77902b9d32fe141a7a65ba8b74270f7a9893ab2de$0.onMessage$bridge(R8$$SyntheticClass:0)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
    at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage$bridge(BasicMessageChannel.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$1$5dd8b6f7959f08bc8717eff7469e77e06ef5aed51cc0cee17f1e13794798223f$0.run
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.$r8$lambda$F0iXMzLdPiwUET1ugdCo3vpOFvI(DartMessenger.java:0)
    at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$InternalSyntheticLambda$2$87f003a9f337bebdd0ba7a08cc7e573e8bd1ce25d26d2f3d3923593655f1df5b$0.run$bridge
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.2.1 23C71 darwin-arm64, locale en-PL)
    • Flutter version 3.19.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/karoljanowski/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/karoljanowski/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Users/karoljanowski/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/karoljanowski/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by darshankawar** [comment]
> ```
> at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.createOutputPrefixToVariantMap(AesSivProtoSerialization.java:84)
>     at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.<clinit>(AesSivProtoSerialization.java:101)
>     at com.google.crypto.tink.daead.internal.AesSivProtoSerialization.register(AesSivProtoSerialization.java:206)
>     at com.google.crypto.tink.daead.AesSivKeyManager.register(AesSivKeyManager.java:181)
>     at com.google.crypto.tink.daead.DeterministicAeadConfig.register(DeterministicAeadConfig.java:98)
>     at com.google.crypto.tink.daead.DeterministicAeadConfig.<clinit>(DeterministicAeadConfig.java:58)
>     at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:116)
>     at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
>     at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$sharedPreferences$2.invoke
>     at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository$editor$2.invoke$bridge(EncryptedKeyValueRepository.kt:0)
>     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
>     at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:20)
>     at com.amazonaws.amplify.amplify_secure_storage.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:48)
>     at com.amazonaws.amplify.amplify_secure_storage.AmplifySecureStoragePlugin.read(AmplifySecureStoragePlugin.kt:33)
>     at com.amazonaws.amplify.amplify_secure_storage.pigeons.AmplifySecureStoragePigeon$Companion.setUp$lambda-1$lambda-0
> ```

@Karjan1 These seems to be pointing to community package https://pub.dev/packages/amplify_secure_storage



> App crashes only on android right after start.

We would need a reproducible code sample that we can use to verify the crash reported further.

**Comment by Karjan1** [comment]
Yeah that's fair, I thought it might not be enough to be reproduced, but it's all I got 😄 
I appreciate your time @darshankawar
