### ISSUE TITLE
"A SearchController was used after being disposed"

### ISSUE THREAD

**Issue by V3ntus** [flutter/flutter#146068]
### Steps to reproduce

1. Follow SearchBar example in documentation, but use as a child of an AlertDialog
2. Open the dialog, quickly interact with search bar, then click out or spam Esc.

### Expected results

SearchController safely disposed with dialog closed

### Actual results

SearchController being used after dialog closes and the controller being disposed

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: () => showDialog(
            context: context,
            builder: (context) => StatefulBuilder(builder: (context, setState) {
              return AlertDialog(
                title: const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text("Search"),
                  ],
                ),
                content: SizedBox(
                  width: 500,
                  child: SearchAnchor(
                    builder: (context, controller) => SearchBar(
                      controller: controller,
                      padding: const MaterialStatePropertyAll<EdgeInsets>(
                        EdgeInsets.symmetric(horizontal: 16),
                      ),
                      onTap: () {
                        controller.openView();
                      },
                      onChanged: (_) {
                        controller.openView();
                      },
                      leading: const Icon(Icons.search),
                      hintText: "Search everything",
                      trailing: [
                        IconButton(
                          onPressed: () {
                            controller.clearComposing();
                          },
                          icon: const Icon(Icons.clear),
                        ),
                      ],
                    ),
                    suggestionsBuilder: (context, controller) {
                      return List<ListTile>.generate(
                        5,
                        (index) => ListTile(
                          title: Text("Item $index"),
                          onTap: () => setState(
                            () {
                              controller.closeView("Item $index");
                            },
                          ),
                        ),
                      );
                    },
                  ),
                ),
              );
            }),
          ),
          child: const Text("Search"),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/29584664/08d05aec-50f8-40ea-b475-6405078fd53d

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building RawGestureDetector(state:
RawGestureDetectorState#4cbc4(gestures: [tap, long press, tap and pan], excludeFromSemantics: true,
behavior: translucent)):
A SearchController was used after being disposed.
Once you have called dispose() on a SearchController, it can no longer be used.

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///home/joe/repos/bug/lib/main.dart:12:12

When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure>
(package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:271:27)
#3      _MergingListenable.addListener (package:flutter/src/foundation/change_notifier.dart:499:14)
#4      _AnimatedState.didUpdateWidget (package:flutter/src/widgets/transitions.dart:118:25)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5652:55)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#17     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#43     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#67     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#76     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#85     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#90     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#94     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#99     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#103    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#112    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#118    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#124    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#147    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#152    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#153    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#157    Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#158    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#160    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#162    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#164    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#171    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#173    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#175    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#179    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#181    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#182    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#185    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#187    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#190    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#192    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#197    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#199    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#201    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#203    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#208    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#212    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#215    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#216    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#218    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#223    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#224    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#225    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#226    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#227    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#228    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#229    _invoke (dart:ui/hooks.dart:312:13)
#230    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#231    _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5926 pos
14: '_dependents.isEmpty': is not true.
Another exception was thrown: Tried to build dirty widget in the wrong build scope.
Another exception was thrown: Cannot hit test a render box that has never been laid out.
Another exception was thrown: Cannot hit test a render box that has never been laid out.
...
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on NixOS 24.05 (Uakari) 6.6.22, locale en_US.UTF-8)
    • Flutter version 3.19.0 on channel stable at
      /nix/store/wkaqj97xj7glb0a0za3iplwcj95jm6mj-flutter-wrapped-3.19.0-sdk-links
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision nixpkgs000 (), 1970-01-01 00:00:00
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    • Android SDK at /home/joe/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[!] Android Studio (version 2023.2)
    • Android Studio at
      /nix/store/kxaw85n8gw6svhfr7hfjskw39ds3mc44-android-studio-stable-2023.2.1.24-unwrapped
    • Flutter plugin version 78.4.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please
      let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      /home/joe/Android/Sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:549:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:216:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:738:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:608:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @V3ntus 
To solve this, you can try passing a SearchController for SearchAnchor from outside of AlertDialog scope (similar to [SearchAnchor](https://api.flutter.dev/flutter/material/SearchAnchor-class.html) example), like this:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final SearchController _controller = SearchController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: TextButton(
          onPressed: () => showDialog(
            context: context,
            builder: (context) => StatefulBuilder(builder: (context, setState) {
              return AlertDialog(
                title: const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text("Search"),
                  ],
                ),
                content: SizedBox(
                  width: 500,
                  child: SearchAnchor(
                    searchController: _controller,
                    builder: (context, controller) => SearchBar(
                      controller: controller,
                      padding: const MaterialStatePropertyAll<EdgeInsets>(
                        EdgeInsets.symmetric(horizontal: 16),
                      ),
                      onTap: () {
                        controller.openView();
                      },
                      onChanged: (_) {
                        controller.openView();
                      },
                      leading: const Icon(Icons.search),
                      hintText: "Search everything",
                      trailing: [
                        IconButton(
                          onPressed: () {
                            controller.clearComposing();
                          },
                          icon: const Icon(Icons.clear),
                        ),
                      ],
                    ),
                    suggestionsBuilder: (context, controller) {
                      return List<ListTile>.generate(
                        5,
                        (index) => ListTile(
                          title: Text("Item $index"),
                          onTap: () => setState(
                            () {
                              controller.closeView("Item $index");
                            },
                          ),
                        ),
                      );
                    },
                  ),
                ),
              );
            }),
          ),
          child: const Text("Search"),
        ),
      ),
    );
  }
}

```
</details>

**Comment by V3ntus** [comment]
Defining the controller outside of the scope worked. In my case, I needed to call `showDialog` from a handler defined in my `main()` function attached below. I'm not sure about disposal practices with this approach, but this is a solution for now. Thank you @huycozy !
```dart
void main() async {
  final SearchController searchController = SearchController(); // define controller here
  HardwareKeyboard.instance.addHandler((event) {
    if (event is KeyDownEvent) {
      if (event.logicalKey == LogicalKeyboardKey.keyF && HardwareKeyboard.instance.isControlPressed) {
        showDialog(
          context: navigatorState.currentContext!,
          builder: (context) =>
              StatefulBuilder(builder: (context, setState) {
                return AlertDialog(
                  title: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text("Search"),
                      IconButton(
                        onPressed: () => context.pop(),
                        icon: const Icon(Icons.close),
                      ),
                    ],
                  ),
                  content: SizedBox(
                    width: 500,
                    child: SearchAnchor(
                      searchController: searchController, // pass in the above defined controller
                      builder: (context, controller) =>
                          SearchBar(
                              controller: controller,
                              ...
                          ),
                    ),
                  ),
                );
              }),
        );
        return true;
      }
    }
    return false;
  });
}
```
