### ISSUE TITLE
testWidgets fails with streams created from scratch

### ISSUE THREAD

**Issue by PvtPuddles** [flutter/flutter#146094]
### Steps to reproduce

I have a widget that creates a semi-periodic stream that dynamically calculates how long it should wait for a specific condition, but I'm getting `pendingTimers` errors.

I have a test that resembles [Creating a Stream from Scratch](https://dart.dev/articles/libraries/creating-streams#creating-a-stream-from-scratch) that reproduces the issue.

```dart
    testWidgets("example stream builder test", (tester) async {
      Stream<DateTime> createStream() async* {
        while (true) {
          await Future.delayed(const Duration(seconds: 1)); <-- Pending timers: Timer (duration: 0:00:01.000000, periodic: false), created: ...
          yield DateTime.now();
        }
      }

      final stream = createStream().asBroadcastStream();
      await tester.pumpWidget(StreamBuilder(
        stream: stream,
        builder: (context, _) => const Placeholder(),
      ));
    });
```

Nor, does it seem, that it's possible for me to cancel my own stream to end the pending timer.
```dart
    testWidgets("example flutter test", (tester) async {
      Stream<DateTime> createStream() async* {
        while (true) {
          await Future.delayed(const Duration(seconds: 1)); <-- Pending timers: Timer (duration: 0:00:01.000000, periodic: false), created: ...
          yield DateTime.now();
        }
      }

      final stream = createStream().asBroadcastStream();
      final subscription = stream.listen((event) {
        print(event);
      });
      await tester.pump(Duration(seconds: 1));
      subscription.cancel();
    });
```

I can't seem to coerce either of the flutter tests to ignore/cancel the pending timer inside the stream.

For comparison, this is the pure-dart version of this test, which works as expected.
```dart
    test("example dart test", () async {
      Stream<DateTime> createStream() async* {
        while (true) {
          await Future.delayed(const Duration(seconds: 1)); <-- Pending timers: Timer (duration: 0:00:01.000000, periodic: false), created: ...
          yield DateTime.now();
        }
      }

      final stream = createStream().asBroadcastStream();
      final subscription = stream.listen((event) {
        print(event);
      });
      await Future.delayed(Duration(seconds: 1));
      subscription.cancel();
    });
```

Can someone shed light on what I'm doing wrong?  (Or otherwise, validate that this isn't just me).

### Expected results

My expectation was that the stream builder would clean up the stream for me, including any contained futures, but that doesn't seem to be the case.

Additionally, manually canceling the stream does not result in the pending timer being removed.

### Actual results

The first two examples (and my actual widget being tested) produce the following error:

Pending timers:
Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#6      main.<anonymous closure>.<anonymous closure>.createStream (file://widget_test.dart:#:24)

### Code sample

<details open><summary>Code sample</summary>

```dart
    testWidgets("example stream builder test", (tester) async {
      Stream<DateTime> createStream() async* {
        while (true) {
          await Future.delayed(const Duration(seconds: 1)); <-- Pending timers: Timer (duration: 0:00:01.000000, periodic: false), created: ...
          yield DateTime.now();
        }
      }

      final stream = createStream().asBroadcastStream();
      tester.pumpWidget(StreamBuilder(
        stream: stream,
        builder: (context, _) => const Placeholder(),
      ));
    });
```

```dart
    testWidgets("example flutter test", (tester) async {
      Stream<DateTime> createStream() async* {
        while (true) {
          await Future.delayed(const Duration(seconds: 1)); <-- Pending timers: Timer (duration: 0:00:01.000000, periodic: false), created: ...
          yield DateTime.now();
        }
      }

      final stream = createStream().asBroadcastStream();
      final subscription = stream.listen((event) {
        print(event);
      });
      await tester.pump(Duration(seconds: 1));
      subscription.cancel();
    });
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
 flutter doctor -v

[✓] Flutter (Channel stable, 3.19.3, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.19.3 on channel stable at /Users/stephen/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (4 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/stephen/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.14888

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/stephen/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
@PvtPuddles 
Can you try to use https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html since you are doing real asynchronous operations ?

**Comment by darshankawar** [comment]
Thanks for the update. Using above code snippet, I was able to replicate the reported behavior.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.22.0-1.0.pre.37, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.22.0-1.0.pre.37 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fd8561a917 (8 hours ago), 2024-03-31 17:12:24 -0400
    • Engine revision 4f6b832c8e
    • Dart version 3.5.0 (build 3.5.0-5.0.dev)
    • DevTools version 2.34.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by goderbauer** [comment]
The flutter testing framework assumes it is a bug if there are still pending timers at the end of the test since this usually means that you triggered some kind of an action in your test, but then you didn't wait for the result to verify that the action executed as expected.

In your test you are creating a stream that always has a pending timer (because it is an infinite stream). It is your responsibility of the test author to terminate that stream so that at the end of the test there is nothing pending. If your test only consumes one item from the stream, well the stream should only produce one. If you want to consume two, produce two, and so on.

**Comment by PvtPuddles** [comment]
Hi @goderbauer, thank you for your reply.

In the real code, the test isn't the one creating the stream, it's the widget I am testing itself.  The stream is meant to infinitely pump once every `n` seconds (similar to `Timer`).

Many tests are written for the page this widget is on, so adding boiler plate for overriding the stream seems excessive.

> It is your responsibility of the test author to terminate that stream so that at the end of the test there is nothing pending.

I can agree with this, but I cannot find an obvious way to do this.  I would like to believe that the final stream listener canceling their subscription would also cancel any timers, but I see why this is not the case.

I've tried `await`ing `stream.cancel()`, but that causes the test to hang without advancing the stream to its final `yield`.

If I'm missing some way to cancel the stream and wait for the final value, please do let me know.
