### ISSUE TITLE
[tool_crash] OSError: OS Error: Operation not supported on socket, errno = 102

### ISSUE THREAD

**Issue by hughesjs** [flutter/flutter#146009]
## Command
```
flutter attach
```

## Steps to Reproduce
1. Run command

## Logs
OSError: OS Error: Operation not supported on socket, errno = 102
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1790:74)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1680:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2659:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:145:16)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:216:7)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.queryForAttach (package:flutter_tools/src/mdns_discovery.dart:95:56)
<asynchronous suspension>
#6      MDnsVmServiceDiscovery.getVMServiceUriForAttach (package:flutter_tools/src/mdns_discovery.dart:397:50)
<asynchronous suspension>
#7      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:370:22)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:266:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-x64, locale en-US)
    [32m•[39m Flutter version 3.19.3 on channel stable at /usr/local/Caskroom/flutter/3.19.3/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ba39319843 (3 weeks ago), 2024-03-07 15:22:21 -0600
    [32m•[39m Engine revision 2e4ba9c6fb
    [32m•[39m Dart version 3.3.1
    [32m•[39m DevTools version 2.31.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.15.2

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version unknown)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.84.0
    [31m✗[39m Unable to determine VS Code version.

[32m[✓][39m Connected device (2 available)
    [32m•[39m iphone (mobile) • redacted-redacted • ios        • iOS 17.3.1 21D61
    [32m•[39m macOS (desktop) • macos                     • darwin-x64 • macOS 14.4 23E214 darwin-x64

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 41456452f29d64e8deb623a3c927524bcf9f111b

**Comment by hughesjs** [comment]
Seems to be the same as this crash that got closed without ever being solved https://github.com/flutter/flutter/issues/91714

**Comment by huycozy** [comment]
Hi @hughesjs 
Looks like you are using [multicast_dns](https://pub.dev/packages/multicast_dns) package, right? If so, could you share the detailed steps to reproduce the issue along with a minimal sample code? (please check the package [example](https://github.com/flutter/packages/tree/main/packages/multicast_dns/example) as well)

**Comment by hughesjs** [comment]
Hi mate,

I don't think it's project dependent, I've just tried this:

```
flutter create demo
cd demo
flutter run
<pick my iOS device>
```

And got the same OS Error

**Comment by huycozy** [comment]
Thanks for the update. `multicast_dns` package is used inside Flutter tool ([mdns_discovery.dart](https://github.com/flutter/flutter/blob/300451adae589accbece3490f4396f10bdf15e6e/packages/flutter_tools/lib/src/mdns_discovery.dart#L8)). Labeling the issue for team's input.

**Comment by andrewkolos** [comment]
fyi @bkonyi @DanTup for expertise in communicating with the VM

**Comment by DanTup** [comment]
> fyi @bkonyi @DanTup for expertise in communicating with the VM

I don't think this is VM service-related, I think there is some multicast DNS happening to try and get the _URI_ for the VM Service. Unfortunately I don't know much about mDNS, although it does seem like there may have been changes to the code where this error originates since the original report (see https://github.com/flutter/packages/pull/6700). I don't know whether it may impact this bug though, it might be worth re-testing on the current Flutter `master` to see if it still occurs.

**Comment by hughesjs** [comment]
So I don't have the ability to recreate this issue anymore I'm afraid as I no longer have a Mac. I know that's of little use to you, apologies
