### ISSUE TITLE
Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference in method

### ISSUE THREAD

**Issue by ymka** [flutter/flutter#146034]
### Steps to reproduce

There are no steps to reproduce.
Crash came from a user on crashlytics. 
Maybe it's device-specific. The crash happened on **Motorola Moto G32 Android 13**.  
There is the reported issue related to crashlytics plugin with the same stacktrace https://github.com/firebase/flutterfire/issues/12448.

My assumptions:
The issue starts in `platform_views.dart` file next code:
```
final Map<Object?, Object?>? meta = await SystemChannels.platform_views.invokeMapMethod<Object?, Object?>(
      'resize',
      <String, dynamic>{
        'id': viewId,
        'width': size.width,
        'height': size.height,
      },
    );
```

After we go to [PlatformViewsController.java](https://github.com/flutter/engine/blob/3588d31a98f6c2a1949132e1cf610265b04185a1/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L157) `resize` method.
There is a code where theoretically NPE can happen. Because `getLayoutParams()` can return null object.
```
          final ViewGroup.LayoutParams viewWrapperLayoutParams = viewWrapper.getLayoutParams();
          viewWrapperLayoutParams.width = physicalWidth;
```

### Expected results

Calling `LayoutParams.width` only on non null object.non-null

### Actual results

Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference in method

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference in method 'void io.flutter.plugin.platform.v$a.h(g7.l$e, g7.l$b)', null, java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference in method 'void io.flutter.plugin.platform.v$a.h(g7.l$e, g7.l$b)'
	at io.flutter.plugin.platform.v$a.h(Unknown Source:125)
	at g7.l$a.h(Unknown Source:59)
	at g7.l$a.c(Unknown Source:167)
	at h7.k$a.a(Unknown Source:17)
	at w6.c.l(Unknown Source:18)
	at w6.c.m(Unknown Source:41)
	at w6.c.i(Unknown Source:0)
	at w6.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:984)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8149)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:334)
       at MethodChannel.invokeMapMethod(platform_channel.dart:534)
       at _TextureAndroidViewControllerInternals.setSize(platform_views.dart:1298)
       at RenderAndroidView._sizePlatformView(platform_view.dart:176)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.19.4, on macOS 14.3 23D56 darwin-arm64, locale en-UA)
    • Flutter version 3.19.4 on channel stable at /Users/ymka/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ymka/development/flutter. Consider adding
      /Users/ymka/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (10 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ymka/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ymka/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
> The issue starts in `platform_views.dart` file next code:
> 
> ```
> final Map<Object?, Object?>? meta = await SystemChannels.platform_views.invokeMapMethod<Object?, Object?>(
>       'resize',
>       <String, dynamic>{
>         'id': viewId,
>         'width': size.width,
>         'height': size.height,
>       },
>     );
> ```
> 
> After we go to [PlatformViewsController.java](https://github.com/flutter/engine/blob/3588d31a98f6c2a1949132e1cf610265b04185a1/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L157) `resize` method. There is a code where theoretically NPE can happen. Because `getLayoutParams()` can return null object.
> 
> ```
>           final ViewGroup.LayoutParams viewWrapperLayoutParams = viewWrapper.getLayoutParams();
>           viewWrapperLayoutParams.width = physicalWidth;
> ```
> 
> ### Expected results
> Calling `LayoutParams.width` only on the non-null object.

@ymka Please see if using this info, whether you are able to come up with a replicable code sample or a pattern that leads to the reported exception.

**Comment by ymka** [comment]
hi @darshankawar ,
Unfortunately, I can't provide a replicable code or a pattern. 
In my case crash affects only 1 user. 
My main function, if it helps.

```
Future<void> main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  String? appName;
  if (appFlavor == 'dev') {
    appName = 'dev';
  }

  unawaited(MobileAds.instance.initialize());
  await Firebase.initializeApp(
    name: appName,
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };
  final preferences = await SharedPreferences.getInstance();
  Logger.addLogListener((event) {
    if (event.level == Level.error) {
      FirebaseCrashlytics.instance.recordError(event.message, event.stackTrace);
    }
  });

  runApp(MyApp(preferences));
}
```

**Comment by darshankawar** [comment]
Thanks for the update. In above code snippet, I see flavors and mobile ads implementation, is it possible for you to narrow down by removing these implementations and see if the crash still occurs or not ?

**Comment by ymka** [comment]
Flavors were released in older versions. However mobile ads may have brought the issue because the crash appeared the first time when the ads were released.

**Comment by mikejones3** [comment]
I can at least ad some context. I am the one who opened: https://github.com/firebase/flutterfire/issues/12448

I was using Google Ads as well. I will see if I can gather more data on number of users and types of devices etc.

**Comment by mikejones3** [comment]
I have 134 crash events affecting 47 users in the last 7 days. 

Its affecting users across the board on Android versions 11-14

Additionally on these phone manufacturers:

40% Samsung
23% Xiaomi
19% Google
3% One Plus
15% Other

**Comment by darshankawar** [comment]
Thanks for the update. https://pub.dev/packages/google_mobile_ads is a third party package. If you think it is indeed occuring due to it, you may need to report in dedicated repo.

**Comment by ymka** [comment]
the problem is it's hard to say what the reason is. But if follow stacktrace you can conclude that it happens in [PlatformViewsController.java](https://github.com/flutter/engine/blob/3588d31a98f6c2a1949132e1cf610265b04185a1/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L157)

**Comment by darshankawar** [comment]
> ```
>  at _TextureAndroidViewControllerInternals.setSize(platform_views.dart:1298)
>        at RenderAndroidView._sizePlatformView(platform_view.dart:176)
> ```

Based on this, I'll keep the issue open and label for team's input / tracking.

**Comment by zoeyfan** [comment]
Given it's happening in [PlatformViewsController.java], I have a feeling that we may still be the owner for this issue rather than the Ads engineer. I can certainly bring this to their attention, but meanwhile, @bparrishMines would you please take a look here as well?

**Comment by bparrishMines** [comment]
@johnmccutchan FYI

@ymka We would need an example of how you are using the PlatformView in the widget tree. For example, is it added to a `ListView` or a `Stack`.

It could be due to a race condition. Ads uses TLHC and we set the `LayoutParams` for the view wrapper when the `View` is initially configured: https://github.com/flutter/engine/blob/3588d31a98f6c2a1949132e1cf610265b04185a1/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L625

**Comment by ymka** [comment]
@bparrishMines sorry for the late reply. You mentioned race condition, the tricky thing is it happens on some devices...
The code looks next way:
```
CustomScrollView(
      physics: const ClampingScrollPhysics(),
      slivers: [
        SliverToBoxAdapter(
          child: Column(
            children: [
                 other widgets
                BannerAds
                other widgets
           ]
         )
      ]
     )
```

I hope it can help somehow.

**Comment by johnmccutchan** [comment]
In what cases does `viewWrapper.getLayoutParams();` return null? I've never observed this.

**Comment by ymka** [comment]
@johnmccutchan there are no steps to reproduce. The crash comes to crashlytics.

**Comment by green-hub** [comment]
I was also experiencing the same error. After trying several things, this error occurred with high frequency when I processed loading mobile ads again after loading mobile ads. [google_mobile_ads 5.2.0](https://pub.dev/packages/google_mobile_ads) is used. I hope this helps.

**Comment by VNArmy** [comment]
> mobile ads again after loading mobile ads

Did you fix these bug? I got some Firebase Crashlytics report. And I also do reload some Admob NativeAds. I think that's the same errors as your.

**Comment by green-hub** [comment]
@VNArmy Yes, I fixed it. My code was reloading Native Ads objects if it was null. So, I made codes to check the Ad objects again after 2 seconds when the Ad objects are null. Then if it is still null, the Ads are reloaded. This solved the error in my case. 2s is the time considering the loading time of ads.

**Comment by fukazayo** [comment]
This issue is labelled `needs repro info`, so here is a concrete reproduction path and, I think, the
reason it has been so hard to pin down. We hit this in production: 24 crashes across 8 users over
four weeks, on Flutter 3.47.1, always 1–7 seconds after app start.

## The write that throws is the `embeddedView` one, not the `viewWrapper` one

`PlatformViewsController`'s `resize` handler has two writes to `.width`. The discussion here has
focused on the `viewWrapper` one, and @johnmccutchan asked in 2024 in what case
`viewWrapper.getLayoutParams()` could return null. I believe the answer is: it cannot.

- `configureForTextureLayerComposition` always calls `viewWrapper.setLayoutParams(new FrameLayout.LayoutParams(...))`.
- `PlatformViewWrapper.setLayoutParams` is `@NonNull`.
- Android never nulls `View.mLayoutParams` back out — there is no `mLayoutParams = null` anywhere in
  `View.java` / `ViewGroup.java`, and `setLayoutParams` throws on null. `removeView` leaves it set.
- `resize` early-returns when the wrapper is missing.

An independent check: `offset()` reads the same `viewWrapper` layout params and runs on every scroll.
In our crash data `topMargin` has **never** thrown, while `width` threw 24 times. If the wrapper path
were live, `offset()` would be failing far more often.

So the failing write is the other one, on `platformView.getView().getLayoutParams()`.

## The precondition: a `PlatformView` whose `getView()` is not stable

The engine calls `getView()` at creation (where it does `setLayoutParams` + `addView`) and calls it
**again** in `resize`. If those two calls return different instances, the second one has no parent and
no layout params, and the write NPEs.

Nothing in the `PlatformView` contract says `getView()` must return the same instance every time, so
plugins do return fresh views.

## A concrete plugin that does this — and why nobody could reproduce it

`google_mobile_ads` (current, 9.1.0), in `GoogleMobileAdsViewFactory.getErrorView()`:

```java
if (BuildConfig.DEBUG) {
  return new ErrorTextView(context, message);
} else {
  return new PlatformView() {
    @Override public View getView() { return new View(context); }  // new instance per call
    @Override public void dispose() {}
  };
}
```

That fallback is used whenever an `AdWidget` is mounted for an ad whose platform view is not
registered yet. Note the branch: debug builds get a single retained `ErrorTextView`, release builds
get a fresh `View` per call. **The bug is unreachable in a debug build.** That would explain two years
of `needs repro info` — anyone trying to reproduce it locally is running the safe branch.

I have filed this against the plugin as well — googleads/googleads-mobile-flutter#1481 — since holding one view there is a one-line fix.

## Suggestion for the engine

Even with the plugin fixed, any plugin returning a fresh view will crash the host app. Either
document that `getView()` must be stable and assert it, or null-check before the write in `resize`
(the ad would render empty rather than taking the process down). The current behaviour turns a
plugin-side contract violation into a fatal crash with a stack trace that points at framework code.

**Comment by fukazayo** [comment]
**Correction to my comment above: this does not kill the process.** The mechanism I described is
right, the severity I attached to it is not, and I would rather fix that here than leave it wrong.

`PlatformViewsChannel.onMethodCall` has no outer try/catch and `resize()` only catches
`IllegalStateException`, so the NPE does escape the handler. But `MethodChannel.IncomingMethodCallHandler.onMessage`
catches `RuntimeException` and converts it to an error envelope, so Dart just gets a
`PlatformException(error, ...)` and the app carries on. Our own analytics back that up — the user in
the case I traced kept using the app for another 71 seconds in the same session.

So the accurate framing is:

- The platform view fails to resize. For us that meant a broken ad slot, not a crash.
- Apps that route unhandled Dart errors into a crash reporter will see it recorded as a fatal crash
  anyway. That is probably worth keeping in mind when reading this issue: some of the reports here may
  be the same reporting artefact rather than real process deaths, which could also explain why the
  reproduction attempts have been so unsatisfying.

The rest of what I posted stands — the failing write is the `embeddedView` one, the `viewWrapper` one
is unreachable, and the trigger is a `PlatformView` whose `getView()` returns a new instance per call
(google_mobile_ads' release-only error view being one such case, filed as
googleads/googleads-mobile-flutter#1481).

I would still suggest a null check before the write, but as a robustness fix rather than a crash fix:
today a plugin-side contract violation produces a confusing `PlatformException` attributed to
framework code, and the view silently stops resizing.
