### ISSUE TITLE
Flutter app crashes if calling `GoogleMapController.takeSnapShot()` before layout complete

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#146059]
### Steps to reproduce

Using

* google_maps_flutter 2.6.0
* google_maps_flutter_android 2.7.0

if I run this code in a callback:

```dart
final GoogleMapController controller = await _mapControllerCompleter.future;
final mapImageSnapshot = await controller.takeSnapshot();
```

and the UI tree layout has not yet completed, the entire app crashes, with this exception:

```console
I/Google Maps Android API( 7700): Google Play services package version: 225014047
I/Google Maps Android API( 7700): Google Play services maps renderer version(legacy): 203115000
I/PlatformViewsController( 7700): Hosting view in a virtual display for platform view: 1
I/PlatformViewsController( 7700): PlatformView is using SurfaceProducer backend
I/GoogleMapController( 7700): No TextureView found. Likely using the LEGACY renderer.
W/wa      ( 7700): File created: _google_maps_sdk_crash_count_2
W/wa      ( 7700): Marker deleted: _google_maps_sdk_crash_count_1
W/wa      ( 7700): Couldn't create marker: _google_maps_sdk_crash_
D/HostConnection( 7700): createUnique: call
D/HostConnection( 7700): HostConnection::get() New Host Connection established 0x7242e1891090, tid 7989
E/AndroidRuntime( 7700): FATAL EXCEPTION: androidmapsapi-Snapshot
E/AndroidRuntime( 7700): Process: app.clicksocial, PID: 7700
E/AndroidRuntime( 7700): java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime( 7700): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1111)
E/AndroidRuntime( 7700): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1078)
E/AndroidRuntime( 7700): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1028)
E/AndroidRuntime( 7700): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:989)
E/AndroidRuntime( 7700): 	at com.google.maps.api.android.lib6.impl.a.d(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):2)
E/AndroidRuntime( 7700): 	at com.google.maps.api.android.lib6.impl.bh.run(:com.google.android.gms.dynamite_mapsdynamite@225014047@22.50.14 (190800-0):1)
E/AndroidRuntime( 7700): 	at java.lang.Thread.run(Thread.java:1012)
W/Parcel  ( 7700): Expecting binder but got null!
I/Process ( 7700): Sending signal. PID: 7700 SIG: 9
Lost connection to device.
```

I understand why the failure is happening, but this should not crash the whole app! At worst, an exception should be thrown back in the Dart code, or a `null` value should be returned.

### Expected results

A Java exception should not crash the Flutter runtime, ever! This is horrible behavior.

### Actual results

A Java exception takes down the whole Flutter app.

### Code sample

--

### Screenshots or Video

--

### Logs

--

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel main, 3.21.0-16.0.pre.11, on Fedora Linux 39 (Workstation Edition) 6.7.7-200.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.21.0-16.0.pre.11 on channel main at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6807eacb33 (4 days ago), 2024-03-27 18:31:44 -0400
    • Engine revision 73c145c9ac
    • Dart version 3.4.0 (build 3.4.0-279.0.dev)
    • DevTools version 2.34.0-dev.12

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6 (Fedora 17.0.6-2.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.85.20240301

[✓] VS Code (version 1.88.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.7.7-200.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lukehutch** [comment]
I'm doing this right now, but I don't even know if this will catch all the ways the app could crash:

```dart
  /// Take a snapshot of the map as the event creator saw it
  Future<Uint8List?> takeSnapshot() async {
    // Whole app crashes if map widget is not built when calling
    // mapController.takeSnapshot(), so double-check this
    if (!_mapControllerCompleter.isCompleted) {
      // Map controller is not initialized, so map is not built
      return null;
    }
    final mapController = await _mapControllerCompleter.future;
    if (!mounted ||
        SchedulerBinding.instance.schedulerPhase ==
            SchedulerPhase.persistentCallbacks) {
      // Widget is not mounted, or is in the process of being built
      return null;
    }
    // Take snapshot of map and return it
    return await mapController.takeSnapshot();
  }
```

**Comment by lukehutch** [comment]
Also I don't understand why the legacy renderer is being used here. I am using the latest `google_maps_flutter` package, which should already use the new renderer, according to @darshankawar in https://github.com/flutter/flutter/issues/143917 .

**Comment by darshankawar** [comment]
Thanks for the report @lukehutch 


> and the UI tree layout has not yet completed, the entire app crashes, with this exception:

I think since the layout isn't rendered yet, then `takeSnapShot()` won't have any UI elements to fetch.


> I'm doing this right now, but I don't even know if this will catch all the ways the app could crash:

Can you take a look at `onMapCreated()` and check if it helps in your case ?

```
onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open for team's input / tracking.

**Comment by lukehutch** [comment]
@stuartmorgan made this comment: https://github.com/flutter/flutter/issues/73117#issuecomment-854112851 -- does this mean that calls through `MethodChannel` are in fact supposed to throw exceptions back to Dart, if the Java code throws an exception? If so, why is it not working for this Maps API call?

**Comment by stuartmorgan** [comment]
> does this mean that calls through `MethodChannel` are in fact supposed to throw exceptions back to Dart, if the Java code throws an exception?

If it throws an exception within the handler, yes.

> If so, why is it not working for this Maps API call?

Please see [my next comment in that thread](https://github.com/flutter/flutter/issues/73117#issuecomment-854176826). Your exception stack shows it happening in a different thread.

**Comment by lukehutch** [comment]
@stuartmorgan OK, so based on the comment you linked, whoever works on the Maps Android library would need to fix this, maybe by putting a check in the FFI thread for this condition, before offloading work to the other thread?

**Comment by stuartmorgan** [comment]
I'm not sure what the "FFI thread" you are referring to is, but I would expect that this can likely be fixed in the plugin by not calling `snapshot` on the map in this scenario, and instead returning method channel error.

**Comment by lukehutch** [comment]
> I'm not sure what the "FFI thread" you are referring to is

The Java thread that `MethodChannel` runs code in, which has Flutter in its stacktrace.

> I would expect that this can likely be fixed in the plugin by not calling `snapshot` on the map in this scenario, and instead returning method channel error.

OK. So I assume this will be seen by the Maps team, since it was triaged and tagged with "p: maps".

**Comment by gmackall** [comment]
From android triage: the fix here is to modify the plugin code so that `takeSnapshot` simply does nothing when called too early.

**Comment by lukehutch** [comment]
Just wondering if the Android team has looked at this (beyond triage) yet? This is a pretty severe issue. I had to put all sorts of protections in place (checking that the map widget was properly initialized, laid-out, and rendered) so that my app doesn't trigger this.

**Comment by stuartmorgan** [comment]
@lukehutch Please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs and https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#escalating-an-issue-that-has-the-wrong-priority
