### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartao

### ISSUE THREAD

**Issue by MohamedSci** [flutter/flutter#146107]
Oops; flutter has exited unexpectedly: "ProcessException: Failed to find "C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the
search path.
  Command: C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartaotruntime.exe ".
A crash report has been written to D:\projects\flutter\fvm_ttttttttttttteeeeeesssssttt\love_romance\flutter_03.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%22+in+the+search+path.%0A++Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe+

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%22+in+the+search+path.+Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%2C+OS+error+code%3A+0&body=%23%23+Command%0A%60%60%60%0Aflutter+run%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%22+in+the+search+path.+Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%2C+OS+error+code%3A+0%0A%60%60%60%0A%230++++++LocalProcessManager.start+%28package%3Aprocess%2Fsrc%2Finterface%2Flocal_process_manager.dart%3A56%3A7%29%0A%231++++++ErrorHandlingProcessManager.start.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A686%3A24%29%0A%232++++++_run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_
io.dart%3A556%3A20%29%0A%233++++++ErrorHandlingProcessManager.start+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A685%3A12%29%0A%234++++++Defa
ultResidentCompiler._compile+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A874%3A37%29%0A%235++++++DefaultResidentCompiler._recompile+%28package%3Aflutter_tool
s%2Fsrc%2Fcompile.dart%3A734%3A14%29%0A%236++++++_RecompileRequest._run+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A420%3A16%29%0A%237++++++_CompilationReque
st.run+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A394%3A30%29%0A%238++++++DefaultResidentCompiler._handleCompilationRequest+%28package%3Aflutter_tools%2Fsrc
%2Fcompile.dart%3A780%3A23%29%0A%239++++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1407%3A47%29%0A%2310+++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1
308%3A19%29%0A%2311+++++_CustomZone.runUnaryGuarded+%28dart%3Aasync%2Fzone.dart%3A1217%3A7%29%0A%2312+++++_BufferingStreamSubscription._sendData+%28dart%3Aasync%2F
stream_impl.dart%3A339%3A11%29%0A%2313+++++_DelayedData.perform+%28dart%3Aasync%2Fstream_impl.dart%3A515%3A14%29%0A%2314+++++_PendingEvents.handleNext+%28dart%3Aas
ync%2Fstream_impl.dart%3A620%3A11%29%0A%2315+++++_PendingEvents.schedule.%3Canonymous+closure%3E+%28dart%3Aasync%2Fstream_impl.dart%3A591%3A7%29%0A%2316+++++_rootR
un+%28dart%3Aasync%2Fzone.dart%3A1391%3A47%29%0A%2317+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1301%3A19%29%0A%2318+++++_CustomZone.runGuarded+%28dart%3Aa
sync%2Fzone.dart%3A1209%3A7%29%0A%2319+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1249%3A23%29%0A%2320+++++_rootRun+
%28dart%3Aasync%2Fzone.dart%3A1399%3A13%29%0A%2321+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1301%3A19%29%0A%2322+++++_CustomZone.runGuarded+%28dart%3Aasyn
c%2Fzone.dart%3A1209%3A7%29%0A%2323+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1249%3A23%29%0A%2324+++++_microtaskLo
op+%28dart%3Aasync%2Fschedule_microtask.dart%3A40%3A21%29%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.19.5%2C+on+Mic
rosoft+Windows+%5BVersion+10.0.22631.3296%5D%2C+locale+en-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.19.5+on+channel+stable+at+C%3A%5CUsers%5Cmoham%
5Cfvm%5Cversions%5C3.19.5%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+
Framework+revision+300451adae+%285+days+ago%29%2C+2024-03-27+21%3A54%3A07+-0500%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+e76c956498%0A++++%1B%5B32m%E2%80%
A2%1B%5B39m+Dart+version+3.3.3%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.31.1%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Pub+download+mirror+https%3A%2F%2Fpub.fl
utter-io.cn%2F%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+download+mirror+https%3A%2F%2Fstorage.flutter-io.cn%2F%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Vers
ion+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SD
K+version+34.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platf
orm+android-34%2C+build-tools+34.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+ANDROID_HOME+%3D++C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%1B%5B32m%E2%
80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%5Cjbr%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime
+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Ch
rome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B33m%5B%21%5D%1B
%5B39m+Visual+Studio+-+develop+Windows+apps+%28Visual+Studio+Community+2022+17.8.6%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+at+C%3A%5CProgram+Files%5CMic
rosoft+Visual+Studio%5C2022%5CCommunity%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Community+2022+version+17.8.34525.116%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Vis
ual+Studio+is+missing+necessary+components.+Please+re-run+the+Visual+Studio+installer+for+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+and+include+these%
0A++++++components%3A%0A++++++++MSVC+v142+-+VS+2019+C%2B%2B+x64%2Fx86+build+tools%0A+++++++++-+If+there+are+multiple+build+tool+versions+available%2C+install+the+l
atest%0A++++++++C%2B%2B+CMake+tools+for+Windows%0A++++++++Windows+10+SDK%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28version+2022.1%29%0A++++%1B%5B32m%E2%80
%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F
0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+
https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+find+bundled+Java+version.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+T
ry+updating+or+re-installing+Android+Studio.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2022.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+S
tudio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2
F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins
.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%0D%0A%0A%1B
%5B32m%5B%E2%9C%93%5D%1B%5B39m+IntelliJ+IDEA+Ultimate+Edition+%28version+2023.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+IntelliJ+at+C%3A%5CProgram+Files%5CJetBrains%5
CIntelliJ+IDEA+2023.2%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2
F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%
0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.87.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CPrograms%
5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.84.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A
++++%1B%5B32m%E2%80%A2%1B%5B39m+SM+M135F+%28mobile%29+%E2%80%A2+RF8W30AC31F+%E2%80%A2+android-arm++++%E2%80%A2+Android+14+%28API+34%29%0A++++%1B%5B32m%E2%80%A2%1B%
5B39m+Windows+%28desktop%29+%E2%80%A2+windows+++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B
39m+Chrome+%28web%29++++++%E2%80%A2+chrome++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+123.0.6312.86%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++
++++%E2%80%A2+edge++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+123.0.2420.65%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%
E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+
Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A
%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+300451adae589accbece3490f4396f10bdf15e6e%0A%0A&labels=tool%2Csevere%3A+crash

Running Gradle task 'assembleDebug'...                                 -Unhandled exception:
SocketException: Connection attempt cancelled, host: www.google-analytics.com, port: 443
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2483:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2926:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2931:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2786:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2623:7)
#10     IOClient.send (package:http/src/io_client.dart:63:38)
#11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#12     BaseClient.post (package:http/src/base_client.dart:32:7)
#13     GAClient.sendData (package:unified_analytics/src/ga_client.dart:66:28)
#14     AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:610:38)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:447:22)
<asynchronous suspension>
#16     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:796:7)
<asynchronous suspension>
#17     _createLocalCrashReport (package:flutter_tools/runner.dart:262:26)
<asynchronous suspension>
#18     _handleToolError (package:flutter_tools/runner.dart:224:25)
<asynchronous suspension>
#19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:7)
<asynchronous suspension>

Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
Launching lib\main.dart on SM M135F in debug mode...

Oops; flutter has exited unexpectedly: "ProcessException: Failed to find "C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the
search path.
  Command: C:\Users\moham\fvm\versions\3.19.5\bin\cache\dart-sdk\bin\dartaotruntime.exe ".
A crash report has been written to D:\projects\flutter\fvm_ttttttttttttteeeeeesssssttt\love_romance\flutter_04.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sd
k%5Cbin%5Cdartaotruntime.exe%22+in+the+search+path.%0A++Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe+

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Cc
ache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%22+in+the+search+path.+Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartao
truntime.exe%2C+OS+error+code%3A+0&body=%23%23+Command%0A%60%60%60%0Aflutter+run%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+
Logs%0AProcessException%3A+Failed+to+find+%22C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%22+in+the+search+pa
th.+Command%3A+C%3A%5CUsers%5Cmoham%5Cfvm%5Cversions%5C3.19.5%5Cbin%5Ccache%5Cdart-sdk%5Cbin%5Cdartaotruntime.exe%2C+OS+error+code%3A+0%0A%60%60%60%0A%230++++++Loc
alProcessManager.start+%28package%3Aprocess%2Fsrc%2Finterface%2Flocal_process_manager.dart%3A56%3A7%29%0A%231++++++ErrorHandlingProcessManager.start.%3Canonymous+c
losure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A686%3A24%29%0A%232++++++_run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_
io.dart%3A556%3A20%29%0A%233++++++ErrorHandlingProcessManager.start+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A685%3A12%29%0A%234++++++Defa
ultResidentCompiler._compile+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A874%3A37%29%0A%235++++++DefaultResidentCompiler._recompile+%28package%3Aflutter_tool
s%2Fsrc%2Fcompile.dart%3A734%3A14%29%0A%236++++++_RecompileRequest._run+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A420%3A16%29%0A%237++++++_CompilationReque
st.run+%28package%3Aflutter_tools%2Fsrc%2Fcompile.dart%3A394%3A30%29%0A%238++++++DefaultResidentCompiler._handleCompilationRequest+%28package%3Aflutter_tools%2Fsrc
%2Fcompile.dart%3A780%3A23%29%0A%239++++++_rootRunUnary+%28dart%3Aasync%2Fzone.dart%3A1407%3A47%29%0A%2310+++++_CustomZone.runUnary+%28dart%3Aasync%2Fzone.dart%3A1
308%3A19%29%0A%2311+++++_CustomZone.runUnaryGuarded+%28dart%3Aasync%2Fzone.dart%3A1217%3A7%29%0A%2312+++++_BufferingStreamSubscription._sendData+%28dart%3Aasync%2F
stream_impl.dart%3A339%3A11%29%0A%2313+++++_DelayedData.perform+%28dart%3Aasync%2Fstream_impl.dart%3A515%3A14%29%0A%2314+++++_PendingEvents.handleNext+%28dart%3Aas
ync%2Fstream_impl.dart%3A620%3A11%29%0A%2315+++++_PendingEvents.schedule.%3Canonymous+closure%3E+%28dart%3Aasync%2Fstream_impl.dart%3A591%3A7%29%0A%2316+++++_rootR
un+%28dart%3Aasync%2Fzone.dart%3A1391%3A47%29%0A%2317+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1301%3A19%29%0A%2318+++++_CustomZone.runGuarded+%28dart%3Aa
sync%2Fzone.dart%3A1209%3A7%29%0A%2319+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1249%3A23%29%0A%2320+++++_rootRun+
%28dart%3Aasync%2Fzone.dart%3A1399%3A13%29%0A%2321+++++_CustomZone.run+%28dart%3Aasync%2Fzone.dart%3A1301%3A19%29%0A%2322+++++_CustomZone.runGuarded+%28dart%3Aasyn
c%2Fzone.dart%3A1209%3A7%29%0A%2323+++++_CustomZone.bindCallbackGuarded.%3Canonymous+closure%3E+%28dart%3Aasync%2Fzone.dart%3A1249%3A23%29%0A%2324+++++_microtaskLo
op+%28dart%3Aasync%2Fschedule_microtask.dart%3A40%3A21%29%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.19.5%2C+on+Mic
rosoft+Windows+%5BVersion+10.0.22631.3296%5D%2C+locale+en-US%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.19.5+on+channel+stable+at+C%3A%5CUsers%5Cmoham%
5Cfvm%5Cversions%5C3.19.5%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+
Framework+revision+300451adae+%285+days+ago%29%2C+2024-03-27+21%3A54%3A07+-0500%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+e76c956498%0A++++%1B%5B32m%E2%80%
A2%1B%5B39m+Dart+version+3.3.3%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.31.1%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Pub+download+mirror+https%3A%2F%2Fpub.fl
utter-io.cn%2F%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+download+mirror+https%3A%2F%2Fstorage.flutter-io.cn%2F%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Vers
ion+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SD
K+version+34.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platf
orm+android-34%2C+build-tools+34.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+ANDROID_HOME+%3D++C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CAndroid%5CSdk%0A++++%1B%5B32m%E2%
80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%5Cjbr%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime
+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Ch
rome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B33m%5B%21%5D%1B
%5B39m+Visual+Studio+-+develop+Windows+apps+%28Visual+Studio+Community+2022+17.8.6%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+at+C%3A%5CProgram+Files%5CMic
rosoft+Visual+Studio%5C2022%5CCommunity%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Community+2022+version+17.8.34525.116%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Vis
ual+Studio+is+missing+necessary+components.+Please+re-run+the+Visual+Studio+installer+for+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+and+include+these%
0A++++++components%3A%0A++++++++MSVC+v142+-+VS+2019+C%2B%2B+x64%2Fx86+build+tools%0A+++++++++-+If+there+are+multiple+build+tool+versions+available%2C+install+the+l
atest%0A++++++++C%2B%2B+CMake+tools+for+Windows%0A++++++++Windows+10+SDK%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28version+2022.1%29%0A++++%1B%5B32m%E2%80
%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F
0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+
https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+find+bundled+Java+version.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+T
ry+updating+or+re-installing+Android+Studio.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2022.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+S
tudio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio1%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2
F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins
.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.6%2B0-b2043.56-10027231%29%0D%0A%0A%1B
%5B32m%5B%E2%9C%93%5D%1B%5B39m+IntelliJ+IDEA+Ultimate+Edition+%28version+2023.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+IntelliJ+at+C%3A%5CProgram+Files%5CJetBrains%5
CIntelliJ+IDEA+2023.2%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2
F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%
0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.87.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cmoham%5CAppData%5CLocal%5CPrograms%
5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.84.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+available%29%0A
++++%1B%5B32m%E2%80%A2%1B%5B39m+SM+M135F+%28mobile%29+%E2%80%A2+RF8W30AC31F+%E2%80%A2+android-arm++++%E2%80%A2+Android+14+%28API+34%29%0A++++%1B%5B32m%E2%80%A2%1B%
5B39m+Windows+%28desktop%29+%E2%80%A2+windows+++++%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22631.3296%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B
39m+Chrome+%28web%29++++++%E2%80%A2+chrome++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+123.0.6312.86%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++
++++%E2%80%A2+edge++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+123.0.2420.65%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%
E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+
Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A
%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+300451adae589accbece3490f4396f10bdf15e6e%0A%0A&labels=tool%2Csevere%3A+crash

Running Gradle task 'assembleDebug'...

**Comment by MohamedSci** [comment]
It seems like you're encountering two separate issues:

    The Flutter tool crashed due to being unable to find dartaotruntime.exe in the specified path. This might be due to a misconfiguration or corruption in your Flutter installation. You can try to resolve this issue by reinstalling Flutter or ensuring that the path specified is correct.

    Additionally, there's an unhandled exception related to a socket connection attempt being canceled. This might be due to network issues or firewall settings blocking the connection. You can try checking your network connection and firewall settings to ensure that the connection to www.google-analytics.com is allowed.

For both issues, it's recommended to follow the provided links to report the crashes to the Flutter team. They can provide further assistance and potentially address these issues in future releases.
