### ISSUE TITLE
SerialTapGestureRecognizer is not supported.

### ISSUE THREAD

**Issue by lurongshuang** [flutter/flutter#146175]
### Steps to reproduce

<details>
<summary> log </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
SerialTapGestureRecognizer is not supported.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 1252 pos 20: 'false'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:1252:20)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4962:13)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#7      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3630:25)
#8      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:589:25)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

### Expected results

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
SerialTapGestureRecognizer is not supported.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 1252 pos 20: 'false'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:1252:20)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4962:13)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#7      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3630:25)
#8      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:589:25)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

### Actual results

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
SerialTapGestureRecognizer is not supported.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 1252 pos 20: 'false'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:1252:20)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4962:13)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4888:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4951:16)
#7      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3630:25)
#8      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
#10     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:589:25)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#16     _invoke (dart:ui/hooks.dart:312:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#18     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```

</details>

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moffatman** [comment]
Yep you can only use TapGestureRecognizer, DoubleTapGestureRecognizer, and LongPressGestureRecognizer

more links

- https://github.com/flutter/flutter/issues/10623
- https://github.com/flutter/flutter/issues/41923

**Comment by darshankawar** [comment]
@lurongshuang 
As mentioned above. You may follow-up in links provided.
Closing.
