### ISSUE TITLE
[camera] CameraImage obtained with startImageStream is corrupted in Android (Galaxy)

### ISSUE THREAD

**Issue by ChurikiTenna** [flutter/flutter#146252]
### Steps to reproduce

Run the code below.

### Expected results

rotate the image, or the image should be in the correct orientation (the image come out as a landscape although the device orientation is portrait)

### Actual results

fails with this error:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 460872: 920320

### Code sample

<details open><summary>Code sample</summary>

```dart
final cameras = await availableCameras();
final firstCamera = cameras.first;
_controller = CameraController(firstCamera, ResolutionPreset.high,
    enableAudio: false, imageFormatGroup: ImageFormatGroup.bgra8888);
await _controller?.initialize();

_controller?.startImageStream((image) async {
    img.Image? bitmap = img.Image.fromBytes(
      image.width, image.height,
      image.planes[0].bytes,
      format:img.Format.bgra,
    );
    bitmap = img.copyRotate(bitmap, 90);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 460872: 920320
E/flutter ( 4817): #0      _typedDataIndexCheck (dart:typed_data-patch/typed_data_patch.dart:5215:5)
E/flutter ( 4817): #1      Uint32List.[] (dart:typed_data-patch/typed_data_patch.dart:2594:13)
E/flutter ( 4817): #2      Image.getPixel (package:image/src/image.dart:422:37)
E/flutter ( 4817): #3      copyRotate (package:image/src/transform/copy_rotate.dart:23:36)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.2 on channel stable at /Users/tenna/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (5 weeks ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tenna/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (7 available)
    • SCG08 (mobile)            • RFCR71VND0N                              • android-arm64  • Android 13 (API 33)
    • Tenna’s iPhone11 (mobile) • 00008030-0012304A01D3402E                • ios            • iOS 17.3.1 21D61
    • tenna’s iphone15 (mobile) • 00008120-00120DDA1E10A01E                • ios            • iOS 17.3.1 21D61
    • Tenna’s iPad (mobile)     • d1802c9bcfe7b9b836383ca90361f9c15180f21e • ios            • iOS 17.3.1 21D61
    • Tenna’s iPad (2) (mobile) • 00008101-0015198A28782C3A                • ios            • iOS 17.3.1 21D61
    • macOS (desktop)           • macos                                    • darwin-arm64   • macOS 14.1.1 23B81
      darwin-arm64
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 123.0.6312.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @ChurikiTenna 
What is the current camera package version? Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that I can try reproducing the issue?

**Comment by ChurikiTenna** [comment]
Hi @huycozy !
The version is `camera: ^0.10.5+9`

Reproducible code:
```

import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

class MainTab extends StatefulWidget {
  const MainTab({super.key});

  @override
  State<MainTab> createState() => _MainTabState();
}

class _MainTabState extends State<MainTab> {
  CameraController? _controller;
  var finish = false;
  @override
  void initState() {
    super.initState();
    Future.sync(() async {
      // デバイスで使用可能なカメラのリストを取得
      final cameras = await availableCameras();
      // 利用可能なカメラのリストから特定のカメラを取得
      final firstCamera = cameras.first;
      _controller = CameraController(firstCamera, ResolutionPreset.high,
          enableAudio: false, imageFormatGroup: ImageFormatGroup.bgra8888);
      await _controller?.initialize();

      _controller?.startImageStream((image) async {
        if (finish) {
          return;
        }
        finish = true;

        Uint8List bytes = image.planes[0].bytes;
        img.Image? bitmap =
            img.Image.fromBytes(image.width, image.height, bytes);
        bitmap = img.copyRotate(bitmap, 90);
      });
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_controller == null) {
      return Container();
    }
    return CameraPreview(_controller!);
  }
}

```

Note: the error does not occur in iOS. Only in android device.

**Comment by ChurikiTenna** [comment]
Additional Note:

If I were to crop the image like this, it also fails with the same RangeError.
Even though the image.size is 1280 x 720.

```
bitmap = img.copyCrop(0, 0, 1000, 700);
```

**Comment by huycozy** [comment]
Are you using [image](https://pub.dev/packages/image) package or another one? Because I see params you pass to `img.Image.fromBytes` are all errors

**Comment by ChurikiTenna** [comment]
I solved it myself.
The image come from android is in yuv420 format, so it should be converted like this.

```
imglib.Image _convertYUV420toImageColor(CameraImage image) {
    const shift = (0xFF << 24);

    final int width = image.width;
    final int height = image.height;
    final int uvRowStride = image.planes[1].bytesPerRow;
    final int uvPixelStride = image.planes[1].bytesPerPixel!;

    final img = imglib.Image(height, width);

    // Fill image buffer with plane[0] from YUV420_888
    for (int x = 0; x < width; x++) {
      for (int y = 0; y < height; y++) {
        final int uvIndex =
            uvPixelStride * (x / 2).floor() + uvRowStride * (y / 2).floor();
        final int index = y * width + x;

        final yp = image.planes[0].bytes[index];
        final up = image.planes[1].bytes[uvIndex];
        final vp = image.planes[2].bytes[uvIndex];
        // Calculate pixel color
        int r = (yp + vp * 1436 / 1024 - 179).round().clamp(0, 255);
        int g = (yp - up * 46549 / 131072 + 44 - vp * 93604 / 131072 + 91)
            .round()
            .clamp(0, 255);
        int b = (yp + up * 1814 / 1024 - 227).round().clamp(0, 255);
        try {
          img.setPixelRgba(height - y, x, r, g, b, shift);
        } catch (e) {
          //print('invalid range');
        }
      }
    }

    return img;
  }
```
