### ISSUE TITLE
[integration_test] image_picker, firebase_performance, AGP 8 , androidx

### ISSUE THREAD

**Issue by Coin-ai** [flutter/flutter#146266]
### Steps to reproduce

<details open><summary>android/app/build.gradle</summary>

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.test_picker"
    compileSdk flutter.compileSdkVersion
    // ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.test_picker"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
	// implementation 'androidx.core:core-ktx:1.12.0'
	// implementation 'com.android.billingclient:billing:6.1.0'
}
```

</details>

<details open><summary>android/gradle/wrapper/gradle-wrapper.properties</summary>

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip
```

</details>

<details open><summary>android/settings.gradle</summary>

```
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    // id "com.android.application" version "7.3.0" apply false
    // id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id 'com.android.application' version '8.3.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.10' apply false
}

include ":app"

```

</details>

<details open><summary>pubspec.yaml</summary>

```
name: test_picker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4

  # one
  # flutter_email_sender: ^6.0.2
  # two
  # firebase_core: ^2.16.0
  # firebase_performance: ^0.9.3+19

  # show one
  # flutter_image_compress: ^2.0.3
  # google_sign_in: ^6.2.1

  # show two
  # implementation 'com.android.billingclient:billing:6.1.0'
  # in_app_purchase: ^3.1.13

  # implementation 'androidx.core:core-ktx:1.12.0'
  # share_plus: ^8.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


```

</details>

1.
1.1  add to pubspec.yaml 
```
firebase_core: ^2.16.0
firebase_performance: ^0.9.3+19
```
1.2  flutter run --release

<details open><summary>Logs</summary>

```console
E/AndroidRuntime(20485): FATAL EXCEPTION: main
E/AndroidRuntime(20485): Process: com.example.test_picker, PID: 20485
E/AndroidRuntime(20485): java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'J1.a' in call to 'int J1.a.next()' (declaration of 'androidx.core.content.b' appears in base.apk)
E/AndroidRuntime(20485):        at androidx.core.content.b.h(SourceFile:1)
E/AndroidRuntime(20485):        at androidx.core.content.b.e(SourceFile:1)
E/AndroidRuntime(20485):        at androidx.core.content.b.attachInfo(Unknown Source:31)
E/AndroidRuntime(20485):        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
E/AndroidRuntime(20485):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
E/AndroidRuntime(20485):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
E/AndroidRuntime(20485):        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
E/AndroidRuntime(20485):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
E/AndroidRuntime(20485):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20485):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(20485):        at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(20485):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20485):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(20485):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

</details>

1.3 add to pubspec.yaml 
`share_plus: ^8.0.2`

OR

add to android/app/build.gradle  (https://stackoverflow.com/questions/78049204/java-lang-incompatibleclasschangeerror-class-android-content-res-xmlblockpars)

```
dependencies {
	implementation 'androidx.core:core-ktx:1.12.0'
}
```

1.3.1 flutter run --release,  click to "Take a Photo"

<details open><summary>Logs</summary>

```console
E/AndroidRuntime(20946): FATAL EXCEPTION: flutter-worker-2
E/AndroidRuntime(20946): Process: com.example.test_picker, PID: 20946
E/AndroidRuntime(20946): java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'K1.a' in call to 'int K1.a.next()' (declaration of 'androidx.core.content.b' appears in base.apk)
E/AndroidRuntime(20946):        at androidx.core.content.b.i(SourceFile:1)
E/AndroidRuntime(20946):        at androidx.core.content.b.f(SourceFile:1)
E/AndroidRuntime(20946):        at androidx.core.content.b.g(SourceFile:1)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.l$b.a(SourceFile:1)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.l.R(SourceFile:1)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.l.Z(SourceFile:1)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(SourceFile:1)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.w.b(SourceFile:34)
E/AndroidRuntime(20946):        at io.flutter.plugins.imagepicker.s.a(SourceFile:3)
E/AndroidRuntime(20946):        at Z0.a$b.a(SourceFile:18)
E/AndroidRuntime(20946):        at Q0.c.k(SourceFile:19)
E/AndroidRuntime(20946):        at Q0.c.l(SourceFile:42)
E/AndroidRuntime(20946):        at Q0.c.h(SourceFile:1)
E/AndroidRuntime(20946):        at Q0.b.run(SourceFile:13)
E/AndroidRuntime(20946):        at Q0.c$h.d(SourceFile:21)
E/AndroidRuntime(20946):        at Q0.c$h.e(SourceFile:1)
E/AndroidRuntime(20946):        at Q0.c$h.b(SourceFile:1)
E/AndroidRuntime(20946):        at Q0.d.run(SourceFile:3)
E/AndroidRuntime(20946):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(20946):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(20946):        at java.lang.Thread.run(Thread.java:764)
```

</details>

2. some error with "flutter_email_sender: ^6.0.2"

3. uncommented all pubspec.yaml
3.1 remove from pubspec.yaml 

```
  # integration_test:
  #   sdk: flutter
```

All ok

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Image Picker'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, this.title});

  final String? title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ImagePicker _picker = ImagePicker();

  Future<void> _onImageButtonPressed(ImageSource source) async {
    try {
      final XFile? image = await _picker.pickImage(source: source);
    } on PlatformException catch (e) {
      if (e.code == 'camera_access_denied') {
        print('camera_access_denied');
      } else {
        print('Unexpected error: $e');
        rethrow;
      }
    } catch (e) {
      print('Error checking camera availability !: $e');
      rethrow;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: Center(
        child: FloatingActionButton(
          onPressed: () => _onImageButtonPressed(ImageSource.camera),
          tooltip: 'Take a Photo',
          child: const Icon(Icons.camera_alt),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4170], locale ru-RU)
    • Flutter version 3.19.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (7 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at G:\DB\soft_db\Android\Sdk\
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = G:\DB\soft_db\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.87.2)
    • VS Code at C:\Users\ooovid\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 123.0.6312.88
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Coin-ai 
Check [this](https://github.com/flutter/flutter/issues/142220#issuecomment-1910208300) and see if it helps in your case or not.



> add to pubspec.yaml
> `share_plus: ^8.0.2`



> 2\. some error with "flutter_email_sender: ^6.0.2"

These are community packages, ie third party to Flutter.

I would suggest you to raise this in support channels like StackOverflow for further resolution if above solution shared doesn't work for you. Closing for now. If you get similar error using flutter's first party packages, then write in comments and I'll reopen it.

**Comment by Coin-ai** [comment]
@darshankawar 
Yes "android.enableR8.fullMode=false"
But this is normal?


> > 2. some error with "flutter_email_sender: ^6.0.2"
> 
> These are community packages, ie third party to Flutter.
> 
This is just an example of package using androidx. firebase_performance with image_picker also has this error, as do other third-party Flutter packages.

If we use integration_test and image_picker, does firebase_performance always require us to set android.enableR8.fullMode=false, or should we not use integration_test in the release?

I wanted to identify the source of the problem and possibly help to fix the behavior of 'integration_test' if it is incorrect. For me, the solution is not to use integration_test in release, but this issue may be encountered by other users as well.

**Comment by darshankawar** [comment]
Thanks for the feedback @Coin-ai 


> does firebase_performance always require us to set android.enableR8.fullMode=false

I am not 100% sure about it.



> or should we not use integration_test in the release?

You may continue to use it in release mode. 



> I wanted to identify the source of the problem and possibly help to fix the behavior of 'integration_test' if it is incorrect. For me, the solution is not to use integration_test in release

Does the reported error occur if we add image_picker and `integration_test` sdk only and try to run app in release mode ?
Or any other plugin such as `firebase_performance` which leads to the said error ?

**Comment by Coin-ai** [comment]
![Code_MY28fj1H4m](https://github.com/flutter/flutter/assets/58988648/2cfa2d79-4210-4696-a024-ae1e614e9114)

**Comment by darshankawar** [comment]
@Coin-ai 
I see that you are trying to run release mode in emulator, can you try the same in physical device and see if you still get same behavior or not ?
Also, if you remove `firebase_core` and `firebase_performance` and run in release mode in device (not emulator), do you still get same behavior or not ?

**Comment by Coin-ai** [comment]
> I see that you are trying to run release mode in emulator, can you try the same in physical device and see if you still get same behavior or not ?

Yes

> Also, if you remove `firebase_core` and `firebase_performance` and run in release mode in device (not emulator), do you still get same behavior or not ?

No

**Comment by darshankawar** [comment]
> > Also, if you remove `firebase_core` and `firebase_performance` and run in release mode in device (not emulator), do you still get same behavior or not ?
> 
> No

This probably indicates the reported behavior could be due to either `firebase_core` or `firebase_performance`. Can you narrow it down by removing either of them one by one and check with plugin in conjunction with `integration_test` shows the behavior ?

**Comment by Coin-ai** [comment]
firebase_performance

**Comment by darshankawar** [comment]
Please check [this](https://stackoverflow.com/a/78077445) and see if it helps in your case or not.

**Comment by Coin-ai** [comment]
yes and no)
```
dependencies {
	implementation 'androidx.core:core-ktx:1.12.0'
}
```
in the first post step 1.3, and shown it is in the video. This helps to start the app without the initial error, but when we try to take a photo with 'image_picker', we encounter second error

**Comment by darshankawar** [comment]
Thanks for the update and patience while we try to figure this out.
I tried with fresh Flutter project on 3.19.5, added `image_picker`, `integration_test` and `firebase_performance` and ran on emulator in release mode with which the app compiled and ran without any issues. The project was created / uses `7.6.3` as gradle wrapper. I see that you are using 8.7-all which could be causing the behavior. Not all plugins could be supporting the AGP version you are using. Can you try by using 7.6.3 and see if you still get same error or not ?

**Comment by Coin-ai** [comment]
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.3-all.zip`
`id "com.android.application" version "7.3.1" apply false`
with
`android.enableR8.fullMode=true`
same error (without all ok)

AGP 8.0 enables R8 full mode by default

**Comment by darshankawar** [comment]
Thanks for the update. I am going ahead and labeling this for team's input / attention, as I am unable to replicate the reported exception.
Updating the issue title to correctly show the current behavior.

**Comment by camsim99** [comment]
@Coin-ai What is the easiest-to-follow reproduction steps? Based on the discussion, we believe that using a fresh Flutter create and setting `android.enableR8.fullMode=true` will give us the error you're seeing. Can you confirm or tell us what the best reproduction steps are?

**Comment by Coin-ai** [comment]
1. fresh Flutter create
<details open>
<summary>android/gradle.properties</summary>

```
...
android.enableR8.fullMode=true
```

</details>

<details open>
<summary>pubspec.yaml</summary>

```
name: test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.0

  firebase_performance: ^0.9.4+4

dev_dependencies:
  integration_test:
    sdk: flutter
```

</details>

`flutter run --release` - first error


2. fix first error
<details open>
<summary>android/app/build.gradle</summary>

```
dependencies {
	implementation 'androidx.core:core-ktx:1.12.0'
}
```

</details>

<details open>
<summary>lib/main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Image Picker'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, this.title});

  final String? title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ImagePicker _picker = ImagePicker();

  Future<void> _onImageButtonPressed(ImageSource source) async {
    try {
      final XFile? image = await _picker.pickImage(source: source);
    } on PlatformException catch (e) {
      if (e.code == 'camera_access_denied') {
        print('camera_access_denied');
      } else {
        print('Unexpected error: $e');
        rethrow;
      }
    } catch (e) {
      print('Error checking camera availability !: $e');
      rethrow;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: Center(
        child: FloatingActionButton(
          onPressed: () => _onImageButtonPressed(ImageSource.camera),
          child: const Text('Take a Photo'),
        ),
      ),
    );
  }
}
```

</details>

`flutter run --release`

`click 'Take a Photo'` - second error

**Comment by muttsu-623** [comment]
I encountered the same error.
Is there any updates 👀 ?

**Comment by gnprice** [comment]
It looks like this issue can be fixed by upgrading the Android Gradle plugin (AGP).

In Zulip at least, we ran into what looks like the same issue:
* https://github.com/zulip/zulip-flutter/issues/879

and found that upgrading to AGP 8.5.0 (from AGP 8.1.4) resolved it: https://github.com/zulip/zulip-flutter/pull/887#issuecomment-2287661971

In the original report above, it looks like the AGP version is 8.3.1. So presumably some AGP release between there and 8.5.0 resolves whatever is causing the issue. (I looked through the AGP release notes and didn't find anything that looked relevant; but AGP release notes are generally pretty thin, so that isn't surprising.)

---

Meanwhile FWIW we determined that the change in our tree that started triggering the issue was when we added `package:video_player` as a dependency — just in the pubspec, before we added any code to invoke it: https://github.com/zulip/zulip-flutter/issues/879#issuecomment-2283744504

So presumably something in the Android build config that that plugin introduces can trigger the issue. That might be a useful lead if someone wants to debug this further.

Given that an AGP upgrade resolves it, though, my recommendation for anyone hitting it would be to just upgrade AGP. It's likely that the bug is in AGP, and that it wouldn't make sense for Flutter to add any code to try to work around it.

**Comment by matanlurey** [comment]
Removing `f: integration_test` as I don't believe `integration_test` (explicitly) is related to this failure mode.

**Comment by andcea** [comment]
I started getting the following error once I upgraded to Gradle 8 (from 7):
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4990)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:9063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Caused by java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
       at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:100)
       at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:70)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$1.<init>(FlutterLocalNotificationsPlugin.java:508)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(FlutterLocalNotificationsPlugin.java:508)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(FlutterLocalNotificationsPlugin.java:220)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(ScheduledNotificationBootReceiver.java:20)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4981)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:9063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

Adding
```
android.enableR8.fullMode=false
```
to `gradle.properties` seems to have fixed it.

Flutter version: 3.27.3

**Comment by martin-ideeri** [comment]
Can confirm that this is still happening, and that @andcea 's solution solved the problem.
