### ISSUE TITLE
[google_sign_in] signIn() is crashing on iOS 17

### ISSUE THREAD

**Issue by Avinash-dhiraj** [flutter/flutter#146290]
### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

google_sign_in: ^6.2.1

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

Use signIn() method on iOS 17.0 device and crashes

### Expected results

Should open google signin option

### Actual results

Crash application

### Code sample

<details open><summary>Code sample</summary>

```dart
googleSignIn.signIn()
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(google_sign_in, UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <SFAuthenticationViewController: 0x10e014a00>, NSInternalInconsistencyException, null)
#0      GoogleSignInApi.signIn (package:google_sign_in_ios/src/messages.g.dart:237:7)
<asynchronous suspension>
#1      GoogleSignInIOS._signInUserDataFromChannelData (package:google_sign_in_ios/google_sign_in_ios.dart:99:3)
<asynchronous suspension>
#2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
<asynchronous suspension>
Lost connection to device.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.4 23E214 darwin-x64, locale en-GB)
    • Flutter version 3.16.8 on channel stable at /Users/tradelab/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (3 months ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tradelab/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • A47266A2-653D-4F72-9EAB-DB9EE45BE10E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 14.4 23E214 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 123.0.6312.105
    ! Error: Browsing on the local area network for Jaikishan’s iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Avinash-dhiraj** [comment]
I have tried to reproduce with minimal code but its working fine there. However, the issue persists within the context of the existing application environment. This discrepancy has made it challenging to pinpoint the root cause of the problem.
Better insight is needed here to fix this.

**Comment by huycozy** [comment]
Hi @Avinash-dhiraj 
Since the issue does not appear on the minimal sample code, it could be caused by other components on the native side (the exception above is a PlatformException). You should observe it to see if you can replicate it consistently and see if it has any pattern.

**Comment by Avinash-dhiraj** [comment]
Issue was that my pubspec.lock file has older reference for ios dependencies which was leading into the crashes. I had to run the flutter pub upgrade command to update the lock file and then everything worked fine then. 
Closing it for now.
