### ISSUE TITLE
API `file_flaky_issue_and_pr` fails due to `Validation Failed`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#146220]
```
GitHub Error: {"message":"Validation Failed","errors":[{"value":"dacoharkes","resource":"Issue","field":"assignee","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/issues/issues#create-an-issue"}
#0      IssuesService.create (package:github/src/common/issues_service.dart:186:7)
<asynchronous suspension>
#1      FileFlakyIssueAndPR._fileIssueAndPR (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:122:13)
<asynchronous suspension>
#2      FileFlakyIssueAndPR.get (package:cocoon_service/src/request_handlers/file_flaky_issue_and_pr.dart:63:36)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:50:24)
<asynchronous suspension>
#4      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:9)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:149:5)
<asynchronous suspension>
#6      createServer.<anonymous closure> (package:cocoon_service/server.dart:261:7)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Seems the ownership is incorrect. We should be using GitHub handles. /cc @dcharkes
