### ISSUE TITLE
Custom Web Engine Build on Windows: Cannot Generate `wasm_release`

### ISSUE THREAD

**Issue by antosha-surf** [flutter/flutter#146406]
I want to create a custom build of _specifically_ Web Engine _specifically_ on Windows.

I try using the `felt` tool as recommended, but I get an error in `vs_toolchain.py`.  **Details are right below**.

---

<details><summary>Engine Development Environment Setup:</summary>

I have set up my Engine development environment [as per this readme](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment):

- [✔️] `git`
- [✔️] `python3`
- [✔️] `flutter` and `dart`
- [✔️] `depot-tools`
- [✔️] `Visual Studio` (although 2022, not 2017 as was written)
- [✔️] [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)
- [✔️] `GYP_MSVS_VERSION` enviroment variable is set to `2022`
- [✔️] `GYP_MSVS_OVERRIDE_PATH` environment variable is set to `MY:\path\to\msvs_2022`
- [✔️] `DEPOT_TOOLS_WIN_TOOLCHAIN` environment variable is set to `0`
- [✔️] `src/flutter/lib/web_ui/dev` has beed added to my `path`
---

My folder setup looks kinda like this:

`engine_directory`
├─ `engine`
│         ├─ `.gclient`
│         └─ `...`
└─ `flutter` <-- a separate instance of flutter specifially to pair it with the custom engine build

---

My `.gclient` file content:

```
solutions = [
  {
    "custom_deps": {},
    "deps_file": "DEPS",
    "managed": False,
    "name": "src/flutter",
    "safesync_url": "",
    "url": "git@github.com:antosha-surf/Flutter-Engine.git",
    "custom_vars": {
      "download_emsdk": True,
    },
  },
]
```

</details>

<details><summary>My actions:</summary>

I did `fetch flutter`, set `upstream` and did `gclient sync`

Then, following [these](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-the-web-on-windows) instructions:

I did `python .\flutter\tools\gn --unoptimized --full-dart-sdk`

It created `out\host_debug_unopt`

I did `ninja -C .\out\<dir created by previous step>`, which filled this `host_debug_unopt` with many built files.

</details>

<details><summary>Using felt tool:</summary>

When using `felt build` from cmd (both regualrly and as Administrator - the results are identical):

```
A:\flutterCustomEngine\engine\src>felt build
Resolving dependencies... (1.4s)
Downloading packages...
  archive 3.4.2 (3.4.10 available)
  collection 1.17.0 (1.18.0 available)
  crypto 3.0.1 (3.0.3 available)
! engine_repo_tools 0.0.0 from path ..\..\tools\pkg\engine_repo_tools (overridden)
  file 6.1.4 (7.0.0 available)
  frontend_server_client 3.2.0 (4.0.0 available)
  http 1.1.0 (1.2.1 available)
  image 3.0.1 (4.1.7 available)
  js 0.6.4 (0.7.1 available)
  matcher 0.12.16 (0.12.16+1 available)
  path 1.8.0 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  process 4.2.3 (5.0.2 available)
  stack_trace 1.10.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test 1.24.8 (1.25.2 available)
  test_api 0.6.1 (0.7.0 available)
  test_core 0.5.8 (0.6.0 available)
  typed_data 1.3.0 (1.3.2 available)
  uuid 4.1.0 (4.3.3 available)
  vm_service 12.0.0 (14.2.0 available)
  webkit_inspection_protocol 1.0.0 (1.2.1 available)
  xml 5.4.1 (6.5.0 available)
  yaml 3.0.0 (3.1.2 available)
Got dependencies!
23 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Running gn...
Generating GN files in: out\wasm_release
Traceback (most recent call last):
  File "A:/flutterCustomEngine/engine/src/build/vs_toolchain.py", line 561, in <module>
    sys.exit(main())
  File "A:/flutterCustomEngine/engine/src/build/vs_toolchain.py", line 557, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "A:/flutterCustomEngine/engine/src/build/vs_toolchain.py", line 379, in CopyDlls
    raise Exception('Unknown target_cpu: ' + target_cpu)
Exception: Unknown target_cpu: wasm
ERROR at //build/toolchain/win/BUILD.gn:58:3: Script returned non-zero exit code.
  exec_script("//build/vs_toolchain.py",
  ^----------
Current dir: A:/flutterCustomEngine/engine/src/out/wasm_release/
Command: A:/.vpython-root/store/python_venv-feu4nmtoont0shce467kvt509k/contents/Scripts/python3.exe A:/flutterCustomEngine/engine/src/build/vs_toolchain.py copy_dlls A:/flutterCustomEngine/engine/src/out/wasm_release Release wasm
Returned 1.
See //BUILD.gn:5:1: which caused the file to be included.
group("default") {
^------------------
Running autoninja...
ninja: error: loading 'build.ninja':
ninja: Entering directory `A:\flutterCustomEngine\engine\src\out\wasm_release'
Pipeline experienced the following failures:
  "gn": Sub-process failed.
Command: A:\flutterCustomEngine\engine\src\flutter\tools\gn --web --runtime-mode=release
Working directory: A:\flutterCustomEngine\engine\src\flutter\lib\web_ui
Exit code: 1

  "ninja": Sub-process failed.
Command: autoninja -C A:\flutterCustomEngine\engine\src\out\wasm_release
Working directory: A:\flutterCustomEngine\engine\src\flutter\lib\web_ui
Exit code: 1

Test pipeline failed.

A:\flutterCustomEngine\engine\src>
```

So it tries to generate a `wasm_release` output (as expected) but fails.

</details>

---

Am I doing something horribly wrong?

Any help is appreciated.

Thanks in advance!

**Comment by huycozy** [comment]
It seems the error is thrown from:

```python
  x64_runtime, x86_runtime, arm64_runtime = vs_runtime_dll_dirs
  if target_cpu == 'x64':
    runtime_dir = x64_runtime
  elif target_cpu == 'x86':
    runtime_dir = x86_runtime
  elif target_cpu == 'arm64':
    runtime_dir = arm64_runtime
  else:
    raise Exception('Unknown target_cpu: ' + target_cpu)
```

It's telling an unknown `target_cpu` in the defined CPU list there. Could you check if your machine has CPU architecture matching one of these? 

Also, could you retry this on the latest Flutter master channel?

**Comment by antosha-surf** [comment]
My current Windows setup is Running an Intel Core i5 x86-64 processor.

I still get _the same_ result when running with the latest Flutter master channel:

<details><summary>Flutter Doctor Output</summary>

```
Flutter 3.22.0-6.0.pre.17 • channel master •
https://github.com/flutter/flutter
Framework • revision f45741bc51 (71 minutes ago) •
2024-04-08 22:47:13 +0200
Engine • revision ceb5fa2c86
Tools • Dart 3.5.0 (build 3.5.0-31.0.dev) • DevTools 2.34.1
```

</details>

But I believe my processor type and Flutter version are irrelevant here in this case. The problem is, it seems like `vs_toolchain.py` only supports building engines on Android, iOS, Linux and Windows (did not try desktops tho, but seems likely the cpu choice for those will fall into one of the currently present `target_cpu` choices and it will build okay) targets. 

The script fails because `felt` passes `target_cpu` = `wasm`, which is not in the list.

By the way, not using `felt` and using the `gn` directly does _NOT_ solve the issue - and it is logical that this will happen because, if you read the source code you'll notice `felt` just calls `gn` for us under the hood with the list of pre-defined web-specific configs (for instance, it just asks `gn` to build `--web` variant).

What is noteworthy too is the fact that `felt` on my **_Mac device_** builds the web engine _without any problem_, correctly generating `wasm_release` folder after `felt build` so the issue seems to be an outdated Windows-oriented `.py` script that does not take into account the existence of Flutter for Web.

**Comment by yjbanov** [comment]
I tried making this work, but it turned into a yak shave I couldn't win, so I gave up. If someone wants to tackle this, go ahead! However, I was successful using WSL to build the web engine on Windows.

**Comment by zhuhaichao518** [comment]
I have the same problem and I have never succeed to use felt build on windows.
Currently I can only build with `.\flutter\tools\gn --build-canvaskit --full-dart-sdk` to generate engine, then copy `canvaskit` folder to \out\host_debug\flutter_web_sdk.
Then I can build web with
`flutter build web --local-web-sdk=host_debug`
