### ISSUE TITLE
 Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\work3\tin\build, but the tool couldn't find it.

### ISSUE THREAD

**Issue by Zvirtuey** [flutter/flutter#146422]
### Steps to reproduce

1.flutter doctor No problem.

2. flutter --version   ->    
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (2 months ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5

3.There are no issues with the project operation!

4.flutter build apk -v --flavor publish --release -t lib/main.dart

### Expected results

I'm running fine,but compiling APK reports an error,I hope to output release APK.

### Actual results

```
[ +407 ms] Running Gradle task 'assemblePublishRelease'... (completed in 18.9s)
[   +4 ms] LocalFile: 'D:\work3\tin\android\build.gradle' provides AGP version: 7.1.2
[   +3 ms] "flutter apk" took 20,658ms.
[   +4 ms] Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\work3\tin\build, but the tool couldn't find it.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:1066:3)
           #2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:561:9)
           <asynchronous suspension>
           #3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:220:5)
           <asynchronous suspension>
           #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:142:5)
           <asynchronous suspension>
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +248 ms] ensureAnalyticsSent: 245ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [版本 10.0.18363.1556], locale zh-CN)
    • Flutter version 3.16.9 on channel stable at D:\Users\virtue\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (2 months ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\Users\virtue\Android\Android_Studio_Sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: D:\Program Files\androidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Virtue\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at D:\Program Files\androidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.85.2)
    • VS Code at C:\Users\Virtue\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • 16th (mobile)     • 882QAETFDMQCU • android-arm64  • Android 8.1.0 (API 27)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.18363.1556]
    • Chrome (web)      • chrome        • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 123.0.2420.81

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @Zvirtuey 
I can't reproduce the issue using this sample code [flutter-flavors-demo](https://github.com/huycozy/flutter-flavors-demo):

```console
➜  flavors-from-sdk git:(main) ✗ flutter build apk -v --flavor free --release

(verbose output logs)

➜  flavors-from-sdk git:(main) ✗ ls build/app/outputs/flutter-apk 
app-free-release.apk      app-free-release.apk.sha1
```

I'm on the latest Flutter stable version 3.19.5. You can try upgrading your Flutter to this version to check. If the issue persists, please provide a minimal sample project so that we can take a look. Thanks!
