### ISSUE TITLE
Flutter crashes with run in release mode, can't find libflutter.so

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#14646]
## Steps to Reproduce
```
rm -rf build
flutter upgrade
flutter run --release
```

Crash:

```
02-12 11:11:54.773 14016 14016 D AndroidRuntime: Shutting down VM
02-12 11:11:54.774 14016 14016 E AndroidRuntime: FATAL EXCEPTION: main
02-12 11:11:54.774 14016 14016 E AndroidRuntime: Process: <redacted>, PID: 14016
02-12 11:11:54.774 14016 14016 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/base.apk"],nativeLibraryDirectories=[/data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/lib/arm64, /data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:142)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-12 11:11:54.777   398   634 W ActivityManager:   Force finishing activity <redacted>/.MainActivity
02-12 11:11:54.779   398   413 I ActivityManager: Showing crash dialog for package <redacted> u0

```

**Comment by jason-simmons** [comment]
Auto detection of ARM64 devices is disabled right now.  Does it work if you explicitly pass `--target-platform=android-arm64`?

**Comment by chances** [comment]
@jason-simmons When will auto detection of ARM64 devices be enabled?

This issue is preventing plain debugging of an Android Flutter app in IntelliJ and Visual Studio Code.

**Comment by skotwani** [comment]
I'm still seeing this issue, and my apk only works if I pass the target-platform flag.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.9.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)

**Comment by zoechi** [comment]
@skotwani the issue is long closed. Please create a new issue.
