### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "ohpm" in the search path. Command: ohpm, OS error code: 0

### ISSUE THREAD

**Issue by jimonik** [flutter/flutter#146551]
## Command
```
flutter build hap --target-platform ohos-arm64 --debug --local-engine=/Users/jimo/Desktop/src/out/ohos_release_arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "ohpm" in the search path. Command: ohpm, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:696:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:568:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:695:12)
#4      ohpmInstall (package:flutter_tools/src/ohos/hvigor.dart:275:28)
#5      OhosHvigorBuilder.flutterBuildPre (package:flutter_tools/src/ohos/hvigor.dart:816:15)
<asynchronous suspension>
#6      OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:715:5)
<asynchronous suspension>
#7      BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:51:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel dev, 3.7.12, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.7.12 on channel dev at /Users/jimo/Desktop/flutter_flutter
    [33m![39m Warning: `flutter` on your path resolves to /Users/jimo/fvm/versions/3.19.5/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/jimo/Desktop/flutter_flutter. Consider adding
      /Users/jimo/Desktop/flutter_flutter/bin to the front of your path.
    [33m![39m Upstream repository git@gitee.com:openharmony-sig/flutter_flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@gitee.com:openharmony-sig/flutter_flutter.git to dismiss this error.
    [32m•[39m Framework revision c342eba3c3 (26 小时前), 2024-04-09 03:44:31 +0000
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m HarmonyOS toolchain - develop for HarmonyOS devices
    [32m•[39m OpenHarmony Sdk location: /Users/jimo/Library/Huawei/Sdk/openharmony, available api versions has [9]

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/jimo/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/jimo/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.14.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.107
    [33m![39m Error: Browsing on the local area network for 沈春平的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    [33m![39m Error: Browsing on the local area network for 谢乙田的iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: c342eba3c3858e8edc5759d5ffd750ed414c050c

**Comment by danagbemava-nc** [comment]
This should be reported on https://gitee.com/openharmony-sig/flutter_flutter. 

Make sure you have all the required tools installed. 

Closing from here. 

Thank you
