### ISSUE TITLE
XIAOMI Android 9.0 java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.packageName' on a null object reference

### ISSUE THREAD

**Issue by thisisjamaldin** [flutter/flutter#146633]
### Steps to reproduce

Don't know when but sometimes it crashes
and http requests are not responding with timeout exaption
there was similar error in [mozilla-mobile](https://github.com/mozilla-mobile/fenix/issues/15316)

### Expected results

work

### Actual results

```console
java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.packageName' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2080)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3973)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1714)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
	at android.app.Activity.startActivityForResult(Activity.java:5216)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:3)
	at android.app.Activity.startActivity(Activity.java:5587)
	at android.app.Activity.startActivity(Activity.java:5555)
	at mozilla.components.feature.app.links.AppLinksUseCases$OpenAppLinkRedirect.invoke(AppLinksUseCases.kt:4)
	at mozilla.components.feature.app.links.AppLinksUseCases$OpenAppLinkRedirect.invoke$default(AppLinksUseCases.kt:1)
	at mozilla.components.feature.app.links.AppLinksFeature$observer$1$onLaunchIntentRequest$doOpenApp$1.invoke(AppLinksFeature.kt:1)
	at mozilla.components.feature.app.links.AppLinksFeature$observer$1.onLaunchIntentRequest(AppLinksFeature.kt:10)
	at mozilla.components.browser.session.-$$LambdaGroup$ks$_UjHvIoGPBlrnpLBhPWojiLCNo4.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:6)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.browser.session.Session.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.session.Session$$special$$inlined$observable$9.afterChange(Delegates.kt:2)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:4)
	at mozilla.components.browser.session.Session.setLaunchIntentMetadata(Unknown Source:13)
	at mozilla.components.browser.session.engine.EngineObserver.onLaunchIntentRequest(EngineObserver.kt:1)
	at mozilla.components.browser.engine.gecko.-$$LambdaGroup$ks$5d9qHqYqF66uxPoGlnXx4EfR-Tw.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:34)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.maybeInterceptRequest(GeckoEngineSession.kt:13)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onSubframeLoadRequest(GeckoEngineSession.kt:3)
	at org.mozilla.geckoview.GeckoSession$Window$1.run(GeckoSession.java:8)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7591)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisorInjector.resolveXSpaceIntent(ActivityStackSupervisorInjector.java:108)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1292)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:515)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1107)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1076)
```
### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6.6 22G630 darwin-x64, locale en-KG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @thisisjamaldin 
The stack above doesn't contain Flutter trace but seems to belong to [mozilla-mobile/firefox-android](https://github.com/mozilla-mobile/firefox-android) instead. I would suggest opening an issue there on its repository for better support. 

Closing the issue. If you believe this is a Flutter framework bug, please provide a minimal sample code that produces the issue along with the output of `flutter run -v`. Thanks!
