### ISSUE TITLE
Local engine builds require rerunning gn script when dart updates.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#146828]
In the last few weeks I've noticed that after updating, dart targets frequently fail with an SDK version mismatch error. This doesn't go away on gclient sync, instead i need to rerun the gn wrapper script.

```
FAILED: gen/text_test.dart.dill
C:/Users/Loic/AppData/Local/.vpython-root/store/python_venv-66qaael56rivngadetj464eh50/contents/Scripts/python3.exe ../../build/gn_run_binary.py ../../flutter/prebuilts/windows-x64/dart-sdk/bin/dartaotruntime.exe --disable-dart-dev C:/Code/f/engine/src/out/host_debug_unopt/gen/frontend_server_aot.dart.snapshot -DkFlutterSrcDirectory=C:/Code/f/engine/src/flutter -DkFlutterBuildDirectory=C:/Code/f/engine/src/out/host_debug_unopt/gen -DkSkiaGoldWorkDirectory=C:/Code/f/engine/src/out/host_debug_unopt/gen/skia_gold_text_test.dart --packages ../../flutter/testing/dart/.dart_tool/package_config.json --sdk-root flutter_patched_sdk --target=flutter --depfile gen/text_test.dart.dill.d --output-dill gen/text_test.dart.dill ../../flutter/testing/dart/text_test.dart
result 8dbf20e3-4584-4ea2-bbbc-8a261a7fb891
Unhandled exception:
Crash when compiling file:///C:/Code/f/engine/src/flutter/testing/dart/text_test.dart:
Unexpected Kernel SDK Version 3d13dbfb32 (expected cb0c34389d).

#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657)
#1      BinaryBuilder._verifyComponentInitialBytes (package:kernel/binary/ast_from_binary.dart:874)
#2      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:697)
#3      Timeline.timeSync (dart:developer/timeline.dart:173)
#4      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695)
#5      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:476)
#6      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:423)
```

It seems like this shouldn't be necessary, and some sort of invalidation might be broken.

**Comment by jonahwilliams** [comment]
Maybe something broke when we moved dart from buildroot? FYI @jason-simmons

**Comment by jason-simmons** [comment]
This is due to https://github.com/flutter/engine/commit/9fe8839d3af548b08a779a5a56a6498eb6e519fc

With this change the `flutter/tools/gn` script is providing the Dart SDK commit hash as the Dart version for compatibility checking purposes in order to reduce the time needed to run GN.

If you sync to a new Dart SDK commit, then `flutter/tools/gn` must be run again to regenerate the version string.

@zanderso

**Comment by jonahwilliams** [comment]
I guess we can close this as WAI. Its unfortunate though, most of the time the gn script doesn't change and its one more thing to remember to do

**Comment by zanderso** [comment]
This is WAI. `et` folds the `gn` and `ninja` commands together, which will make this less error prone.
