### ISSUE TITLE
[tool_crash] RPCErrorflutter has exited unexpectedly: "streamListen: (-32000) Bad state: The client closed with pending request "_setStreamIncludePrivateMembers".".

### ISSUE THREAD

**Issue by ali-eryushion** [flutter/flutter#147042]
## Command
```
flutter run --machine --start-paused -d 00008020-001139221402003A --devtools-server-address http://127.0.0.1:9101/ --target /../main.dart
```

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1771:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1783:8)
#3      VmService.streamListen (package:vm_service/src/vm_service.dart:1710:7)
#4      IOSDeviceLogReader._listenToUnifiedLoggingEvents (package:flutter_tools/src/ios/devices.dart:1337:44)
#5      IOSDeviceLogReader.connectedVMService= (package:flutter_tools/src/ios/devices.dart:1240:7)
#6      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:354:50)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.2.1 23C71 darwin-x64, locale en-GB)
    • Flutter version 3.19.5 on channel stable at /Users/eryustech/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
    • Android SDK at /Users/eryustech/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • Eryushion’s Iphone (mobile) • 00008020-001139221402003A • ios            • iOS 15.3.1 19D52
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 14.2.1 23C71 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 119.0.6045.159
    ! Error: Browsing on the local area network for Vim’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e

NOTE : App Crashed and showed this error. I was working on Method channel with IOS when this error came.

**Comment by darshankawar** [comment]
> IOSDeviceLogReader._listenToUnifiedLoggingEvents (package:flutter_tools/src/ios/devices.dart:1337:44)
> #5      IOSDeviceLogReader.connectedVMService= (package:flutter_tools/src/ios/devices.dart:1240:7)

Although this is RPCError tool crash, but these log entries are different from other existing similar issues, so will keep it open for team's input / attention if this need to be tracked separately, as I couldn't find any open issue with above logs.

**Comment by ali-eryushion** [comment]
it was resolved after restarting the pc, kinda weird that it was resolved just like that though.
