### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference

### ISSUE THREAD

**Issue by LondonX** [flutter/flutter#147204]
### Steps to reproduce

1. My app embed the native, banner ads with video player, and I catch some randomly crashes on firebase.
2. Unlike the #19595 , My app is do nothing with camera.
3. It shows crashed devices are 81% Samsung and 15% Motorola along with 68% Android 14, 32% Android 13.
4. According to the fireabse events, it shows the crashes may not relate to be video player, because some users were never reach the player view before this crash.
5. The logs is attached below.

### Expected results

no crash

### Actual results

crash

### Code sample

Sorry, but I have no idea where is the key code to cause this crash, the stack trace is not point to anywhere in my code, and the firebase events indicates even no specific screen of my app cause this crash.
What I only got is crash logs from firebase.

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
       at io.flutter.plugin.platform.b.getSurface(ImageReaderPlatformViewRenderTarget.java:3)
       at io.flutter.plugin.platform.b.lockHardwareCanvas(ImageReaderPlatformViewRenderTarget.java:1)
       at io.flutter.plugin.platform.n.draw(PlatformViewWrapper.java:16)
       at android.view.View.updateDisplayListIfDirty(View.java:24024)
       at android.view.View.draw(View.java:24895)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4789)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4547)
       at android.view.View.updateDisplayListIfDirty(View.java:24010)
       at android.view.View.draw(View.java:24895)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4789)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4547)
       at android.view.View.updateDisplayListIfDirty(View.java:24010)
       at android.view.View.draw(View.java:24895)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4789)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4547)
       at android.view.View.updateDisplayListIfDirty(View.java:24010)
       at android.view.View.draw(View.java:24895)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4789)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4547)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1185)
       at android.view.View.draw(View.java:25168)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1167)
       at android.view.View.updateDisplayListIfDirty(View.java:24024)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:764)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:770)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:868)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5993)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5662)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4770)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3275)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11256)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
       at android.view.Choreographer.doFrame(Choreographer.java:1055)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8913)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at /Users/london/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/london/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/london/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 26111FDF6002Q4            • android-arm64  • Android 14 (API 34)
    • London’s iPhone (mobile) • 00008101-001E39DE3A63001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)          • macos                     • darwin-x64     • macOS 14.4 23E214 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 124.0.6367.61
    ! Error: Browsing on the local area network for 邓慧的 iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @LondonX 
Maybe it is related to Android SurfaceView that external plugins (ads in your case) could be using.
Is there a way for you to narrow it down by removing ads implementation ?
Would also be interesting to check if the same exception occurs using virtual display or hybrid composition of android views or is it just specific to surface view.

**Comment by LondonX** [comment]
I finally reproduced the crash on my device.

For now, my conclusion is the crash is related with ads (google_mobile_ads) which contained in `AnimatedContainer`.
I fixed it by replacing the `AnimatedContainer` to `isKeyboardShowing ? const SizeBox(width: double.maxFinite) : MyAdsView(...)`.

But I wonder if this crash may also reproduce on any other PlatformView with AnimatedContainer?

BTW, it seems like the refresh rate and the FPS may be positively correlated with crash rate, so I cannot reproduce this crash on Pixel 3 but can reproduce on Pixel 6, and crashed devices shows on firebase are high-end even flagship devices.

**Comment by darshankawar** [comment]
Good to know you were able to replicate the crash.



> For now, my conclusion is the crash is related with ads (google_mobile_ads) which contained in `AnimatedContainer`.
> I fixed it by replacing the `AnimatedContainer` to `isKeyboardShowing ? const SizeBox(width: double.maxFinite) : MyAdsView(...)`.

I suggest you to follow-up in dedicated repo for further resolution.



> But I wonder if this crash may also reproduce on any other PlatformView with AnimatedContainer?

If you can come up with reproducible code sample for this, we would be happy to look into it further.

**Comment by LondonX** [comment]
Strange, I created a new project with minimal code to make a Native ad in AnimatedContainer, also collapsing and expanding with keyboard visibility changing, nothing crash.

Maybe I show close this issue for now.
Thank you for your patient reply!
