### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by Heidelbergg** [flutter/flutter#147317]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      CocoaPods.invalidatePodInstallOutput (package:flutter_tools/src/macos/cocoapods.dart:306:29)
#7      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1124:26)
<asynchronous suspension>
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:369:5)
<asynchronous suspension>
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:382:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale da-DK)
    • Flutter version 3.19.6 on channel stable at /Users/ammarkm/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ammarkm/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008110-000875240222401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 124.0.6367.79

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e
### Plugins
app_links-4.0.1
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.19
flutter_secure_storage-9.0.0
flutter_secure_storage_linux-1.2.0
flutter_secure_storage_macos-3.0.1
flutter_secure_storage_web-1.1.2
flutter_secure_storage_windows-3.0.0
flutter_svprogresshud-1.0.1
google_maps_flutter-2.6.1
google_maps_flutter_android-2.7.0
google_maps_flutter_ios-2.6.0
google_maps_flutter_web-0.5.6+2
google_sign_in-6.2.1
google_sign_in_android-6.1.23
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4
gtk-2.1.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.0
sign_in_with_apple_web-2.1.0
url_launcher-6.2.6
url_launcher_android-6.3.1
url_launcher_ios-6.2.5
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by darshankawar** [comment]
@Heidelbergg 
Can you check if you have required write permission to the directory where your flutter project is?
If not, grant write permission and re-run your scenario.

**Comment by Heidelbergg** [comment]
I do have write/read permissions for the project. The thing is, every time i run "flutter clean", "flutter pub get" and try and run on an iOS device, i get this error. Im not sure why. 
@darshankawar

**Comment by darshankawar** [comment]
Thanks for the update. Check [this](https://github.com/flutter/flutter/issues/141238#issuecomment-1894841881) and see if it helps in your case or not.
