### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0

### ISSUE THREAD

**Issue by rajshukla16052** [flutter/flutter#147353]
## Command
```
flutter --version
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:711:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:710:12)
#4      _runSync (package:flutter_tools/src/version.dart:856:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:436:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:322:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
`

**Comment by christopherfujino** [comment]
@rajshukla16052 do you actually have git installed and on your path?

**Comment by rajshukla16052** [comment]
No but now i did it solved
and thankyou for your response.

**Comment by rajshukla16052** [comment]
Thanks a lot.
