### ISSUE TITLE
[arch-linux] /usr/lib/flutter/packages/flutter_tools/templates/template_manifest.json no such file or directory

### ISSUE THREAD

**Issue by manuelzzz** [flutter/flutter#147468]
### Steps to reproduce

1. flutter create test

### Actual results

Failed to send crash report. Server responded with HTTP status code 400
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file, path =
'/usr/lib/flutter/packages/flutter_tools/templates/template_manifest.json' (OS Error:
No such file or directory, errno = 2)".

### Logs

<details open>
<summary>Logs</summary>

```consoleFlutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create test

## exception

PathNotFoundException: PathNotFoundException: Cannot open file, path = '/usr/lib/flutter/packages/flutter_tools/templates/template_manifest.json' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:672:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:659:43)
#10     CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#11     CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:483:25)
#12     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:508:29)
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:361:37)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel , 3.19.6, on Arch Linux 6.8.7-arch1-1, locale pt_BR.UTF-8)
    • Flutter version 3.19.6 on channel  at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19
      03:14:08
    • Engine revision c4cd48e18646
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/mss/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/mss/android-sdk
    • Java binary at: /usr/lib/jvm/java-21-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+9)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.2
    • ninja version 1.11.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.8.7-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel , 3.19.6, on Arch Linux 6.8.7-arch1-1, locale pt_BR.UTF-8)
    • Flutter version 3.19.6 on channel  at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19
      03:14:08
    • Engine revision c4cd48e18646
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/mss/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/mss/android-sdk
    • Java binary at: /usr/lib/jvm/java-21-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+9)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.2
    • ninja version 1.11.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.8.7-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by manuelzzz** [comment]
Closed. I just reinstalled her with yay.
