### ISSUE TITLE
[ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(28)] Reached unreachable code.

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#147551]
Running flutter framework tests at tip of tree locally on a Mac appears to be crashing. 😱 

Whether running `flutter test`, or `flutter/test/some/specific_test.dart`, I am getting a crash:

```
flutter test

...

00:20 +934 ~14: ... StarBorder parameters
Shell: [ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(28)] Reached unreachable code.
unhandled error during finalization of test:
/Users/katelovett/_github/flutter/packages/flutter/test/painting/system_fonts_test.dart
TestDeviceException(Shell subprocess crashed with SIGABRT (-6).)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:248:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:230:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:525:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:581:11)
<asynchronous suspension>
```

Or another:
```
flutter test test/material/switch_test.dart

...

00:04 +20: switch sends semantic events from parent if fully merged                                       
Shell: [ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(28)] Reached unreachable code.
unhandled error during finalization of test:
/Users/katelovett/_github/flutter/packages/flutter/test/material/switch_test.dart
TestDeviceException(Shell subprocess crashed with SIGABRT (-6).)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:248:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:230:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:525:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:581:11)
<asynchronous suspension>
```

Appears to be impeller related. I've synced with TOT a couple times today and updated packages, the tree is not red, so it may just be my unfortunate circumstance.

Flutter doctor:

```
[!] Flutter (Channel [user-branch], 3.22.0-18.0.pre.61, on macOS 14.4.1 23E224 darwin-x64, locale en)
    ! Flutter version 3.22.0-18.0.pre.61 on channel [user-branch] at /Users/katelovett/_github/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 7ff31a4f7a (35 minutes ago), 2024-04-30 01:14:01 +0300
    • Engine revision c093562677
    • Dart version 3.5.0 (build 3.5.0-109.0.dev)
    • DevTools version 2.35.0-dev.16
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio with Blaze Beta.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 77.3.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33)
      (emulator)
    • iPhone 14 Pro Max (mobile)   • 3AE9FBA4-5508-4C1A-84C5-E76355E61A27 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 14.4.1 23E224
      darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome
      124.0.6367.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

**Comment by gaaclarke** [comment]
I'm not able to reproduce this @Piinks. I'm not sure what the x factor is.

```
$ flutter test test/material/switch_test.dart
...
00:07 +65: All tests passed!  
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.22.0-18.0.pre.73, on macOS 14.4.1 23E224 darwin-arm64, locale en)
    ! Flutter version 3.22.0-18.0.pre.73 on channel [user-branch] at /Users/aaclarke/dev/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 456f0101fd (28 minutes ago), 2024-04-30 12:04:09 -0400
    • Engine revision 2c1517bbf5
    • Dart version 3.5.0 (build 3.5.0-114.0.dev)
    • DevTools version 2.35.0-dev.16
```

**Comment by gaaclarke** [comment]
This crash seems to be related to runtime effects which I'm not that familiar with.  The assert has to do with an unexpected data type for uniforms.  Something like specifying a fragment shader that has a uniform that isn't a struct, float or sampler could cause this crash.

I'm not familiar with this API or what state it's in.  I think ideally this would result in a Dart exception when the shader is created instead of a runtime assert.  It may be that they just haven't implemented the other datatypes yet though.

Maybe running with a local engine and a debugger attached can tell us what datatype we are getting and hopefully trace it back to the source.

**Comment by Piinks** [comment]
I synced my branch this morning, ran `flutter clean` and `flutter doctor`, and the issue was gone. Seems to be working fine now. 👍
