### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by manuelzamdev** [flutter/flutter#147595]
## Command
```
flutter run -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:167:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:888:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#10     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:702:16)
<asynchronous suspension>
#11     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1277:18)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:401:7)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:808:27)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel , 3.19.6, on Arch Linux 6.8.8-arch1-1, locale es_ES.UTF-8)
    [32m•[39m Flutter version 3.19.6 on channel  at /usr/lib/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19 03:14:08
    [32m•[39m Engine revision c4cd48e18646
    [32m•[39m Dart version 3.3.3
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /opt/android-sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /opt/android-sdk
    [32m•[39m ANDROID_SDK_ROOT = /opt/android-sdk
    [32m•[39m Java binary at: /opt/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 17.0.6
    [32m•[39m cmake version 3.29.2
    [32m•[39m ninja version 1.12.0
    [32m•[39m pkg-config version 2.1.1

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Arch Linux 6.8.8-arch1-1
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.91

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: 
**Creation framework version**: archlinuxaur0000000000000000000000000000

**Comment by huycozy** [comment]
Can you please check [this](https://github.com/flutter/flutter/issues/141238#issuecomment-1894841881) to see if it can help to solve your case?
