### ISSUE TITLE
Navigator.push EXCEPTION

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#14769]
## Steps to Reproduce

Run the flutter 'firebase_messaging' plugin example (from https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example).

The **2nd** time the call to `_navigateToItemDetail` is made (ie the 2nd time a notification is received and 'Show' in the dialog is selected), the EXCEPTION occurs (and on every subsequent call).

## Logs
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
_WidgetsAppState#ba113](dirty, state: NavigatorState#1fe32(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1336: '!_debugLocked': is not
true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:1336)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3463)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2210)
#7      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621)
#8      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
#9      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
#10     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
#11     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
#12     _invoke (file:///Users/Andy/Downloads/react-native/flutter/bin/cache/pkg/sky_engine/lib/ui/hooks.dart:120)
#13     _drawFrame (file:///Users/Andy/Downloads/react-native/flutter/bin/cache/pkg/sky_engine/lib/ui/hooks.dart:109)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
## Flutter Analyze
```
flutter analyze
Analyzing /Users/Andy/Downloads/testflutter/testnotifications...
No issues found!
Ran in 7.1s
```
## Flutter Doctor
```
flutter doctor
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-GB, channel alpha)
    • Flutter version 0.0.21 at /Users/Andy/Downloads/react-native/flutter
    • Framework revision 2e449f06f0 (3 weeks ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Andy/androidsdk
    • Android NDK at /Users/Andy/androidsdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/Andy/androidsdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                            • android-x64 • Android 6.0 (API 23) (emulator)
    • iPhoneX                      • 23768a229413152894f2f52b445e0c68d91118ae • ios         • iOS 11.2.5
    • Andy’s iPad                  • dcb26df502ea724a72de6c75b46122e313b14ca4 • ios         • iOS 11.2.5
    • iPhone 6                     • 8342AB45-E2BD-4F29-B205-B0B5B92652E0     • ios         • iOS 11.2 (simulator)
```

**Comment by kroikie** [comment]
@agreensh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/901. Any further collaboration will be done there.
