### ISSUE TITLE
`et run` throws `UnimplementedError` for Android on Windows

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#147646]
### Steps to reproduce

1. Sync local engine repo to ToT
2. Open Android Virtual Device from device manager (Pixel 2, API 30, x86 in my case)
3. From the directory of the default Flutter example app, run `path/to/engine/bin/et run`

### Expected results

App builds and runs in emulator

### Actual results

Execution fails due to an `UnimplementedError`

### Code sample

N/A. Using default generated example project resulting from `flutter create...`

### Logs

<details open><summary>Logs</summary>

```console
Building to run on "sdk gphone x86" running android-x86
Unhandled exception:
UnimplementedError: No mapping for android-x86
#0      RunTarget.buildConfigFor (package:engine_tool/src/run_utils.dart:53:9)
#1      RunCommand._selectTargetConfig (package:engine_tool/src/commands/run_command.dart:125:19)
<asynchronous suspension>
#2      RunCommand.run (package:engine_tool/src/commands/run_command.dart:134:32)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      ToolCommandRunner.run (package:engine_tool/src/commands/command_runner.dart:109:14)
<asynchronous suspension>
#5      main (package:engine_tool/main.dart:75:19)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.20.0-16.0.pre.76, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
    ! Flutter version 3.20.0-16.0.pre.76 on channel [user-branch] at C:\src\flutter\flutter\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository git@github.com:yaakovschectman/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:yaakovschectman/flutter.git to dismiss this error.
    • Framework revision 6e7783d7b2 (7 weeks ago), 2024-03-13 17:18:42 -0400
    • Engine revision a312091719
    • Dart version 3.4.0 (build 3.4.0-190.0.dev)
    • DevTools version 2.33.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\schectman\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = C:\Users\schectman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\schectman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4291]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 124.0.6367.118
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 124.0.2478.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by yaakovschectman** [comment]
cc @loic-sharma @johnmccutchan

**Comment by yaakovschectman** [comment]
In `ci/builders`, it looks like we just don't have anything for Windows builds of the Android engine in debug mode.

**Comment by johnmccutchan** [comment]
@zanderso What should Yaakov do?

**Comment by zanderso** [comment]
`et` could give a better error message here, but the underlying GN/Ninja build does not support cross-building Android artifacts on a Windows host (and I suspect implementing it would be non-trivial). I'd recommend switching to a Linux or macOS host for working on the Android embedder.
