### ISSUE TITLE
java.lang.IllegalArgumentException when reading a Firestore document

### ISSUE THREAD

**Issue by h1man5hu** [flutter/flutter#14767]
## Steps to Reproduce
I have a root level collection **col** which has a document **doc**. 
**doc** has a single field which is an array of strings.
The app crashes when I try to get a DocumentSnapshot of *doc* using:

`DocumentSnapshot snapshot = await Firestore.instance.collection('col').document('doc').get();`

## Logs
```
E/AndroidRuntime( 4507): java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.firestore.DocumentReference@1e4a5fd1
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:260)
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:249)
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:257)
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:257)
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:52)
E/AndroidRuntime( 4507): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime( 4507): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$11.onSuccess(CloudFirestorePlugin.java:459)
E/AndroidRuntime( 4507): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$11.onSuccess(CloudFirestorePlugin.java:449)
E/AndroidRuntime( 4507): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:27)
E/AndroidRuntime( 4507): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 4507): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4507): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4507): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime( 4507): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4507): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 4507): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel dev)
    • Flutter version 0.0.25-pre.5 at C:\Users\himanshu\flutter
    • Framework revision 4ae1b5f415 (11 days ago), 2018-02-07 15:18:04 -0800
    • Engine revision 9bc2efdf47
    • Tools Dart version 2.0.0-dev.19.0
    • Engine Dart version 2.0.0-edge.ea91bc9888184d5a2fc309c36656fdd325ef503c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\himanshu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.19.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by h1man5hu** [comment]
I have tried using `Stream` instead of `Future `using `StreamBuilder `as well. Both `QuerySnapshot `and `DocumentSnapshot `give the same error.

**Comment by h1man5hu** [comment]
Okay, just realized the body of the document has some fields of type `reference` which gets mapped to `com.google.firebase.firestore.DocumentReference` in Java. Is handling this type currently in development?

**Comment by Skylled** [comment]
Can be closed via flutter/plugins#429

**Comment by cbracken** [comment]
Thanks!

**Comment by kroikie** [comment]
@h1man5hu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/902. Any further collaboration will be done there.
