### ISSUE TITLE
Ink in Drawer causes exception & wonky behaviour

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#14773]
## Steps to Reproduce

Use the following code. Open the drawer, then close. The exception seems to happen whenever there is an ink as a (moderately direct) descendant of the drawer. I was using the ink rather than a container as I have custom buttons as part of my drawer that use InkWell.

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Scaffold(
        drawer: new Drawer(
          child: new Ink(
            color: Colors.green.shade100,
            child: new ListView(
              children: <Widget>[],
            ),
          ),
        ),
        body: new Center(
          child: new RaisedButton(
            child: new Text("Press me"),
            onPressed: () {
              print("You pressed me!");
            },
          ),
        ),
      ),
    );
  }
}
```

After closing the drawer, an exception is thrown, buttons on the page behind the drawer become unresponsive, and sometimes the drawer still shows a little.

## Logs
```
I/flutter ( 5599): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5599): The following NoSuchMethodError was thrown building RawGestureDetector(state:
I/flutter ( 5599): RawGestureDetectorState#82e1d(gestures: [horizontal drag], behavior: translucent)):
I/flutter ( 5599): The method 'dispose' was called on null.
I/flutter ( 5599): Receiver: null
I/flutter ( 5599): Tried calling: dispose()
I/flutter ( 5599): 
I/flutter ( 5599): When the exception was thrown, this was the stack:
I/flutter ( 5599): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter ( 5599): #1      _InkState.deactivate (package:flutter/src/material/ink_decoration.dart:236:10)
I/flutter ( 5599): #2      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3775:12)
I/flutter ( 5599): #3      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1698:13)
I/flutter ( 5599): #4      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #8      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #12     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #18     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3659:14)
I/flutter ( 5599): #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #28     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #34     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4699:16)
I/flutter ( 5599): #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4599:14)
I/flutter ( 5599): #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1700:13)
I/flutter ( 5599): #38     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1709:7)
I/flutter ( 5599): #39     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2926:29)
I/flutter ( 5599): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2690:7)
I/flutter ( 5599): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter ( 5599): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 5599): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 5599): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 5599): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 5599): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 5599): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 5599): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 5599): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 5599): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 5599): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2883:38)
I/flutter ( 5599): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 5599): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
I/flutter ( 5599): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 5599): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 5599): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 5599): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 5599): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 5599): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 5599): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 5599): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 5599): #62     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 5599): #63     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 5599): #64     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5599): #65     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5599): #66     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5599): #67     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5599): #68     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter ( 5599): #69     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter ( 5599): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5599): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2223 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
```

## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale en-GB, channel master)
    • Flutter version 0.1.3-pre.43 at C:\VirtualDrives\Programs\flutter
    • Framework revision 1363489a86 (13 hours ago), 2018-02-18 22:27:46 -0800
    • Engine revision e5b72e5f87
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\VirtualDrives\Programs\Android\sdk
    • Android NDK at C:\VirtualDrives\Programs\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = C:\VirtualDrives\Programs\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[√] VS Code
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.7.3

[√] VS Code (version 1.19.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.7.3

[√] Connected devices
    • Nexus 5X • 00c5937b0b2c37ce • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by cbracken** [comment]
@Hixie looks like a missing `null` check in `dispose` in case it's called twice?

**Comment by pedia** [comment]
@cbracken  @Hixie  
Is #15148 same to this?  Stack traces maybe same.

**Comment by cbracken** [comment]
The NPE is fixed by #15473. Keeping open for now since arguably we shouldn't be calling `dispose()` twice on the same component in the first place.

**Comment by HansMuller** [comment]
Deactivate is applied to _InkState's InkDecoration (_ink) twice, without an intervening build. The build method creates a LayoutBuilder and _ink is initialized there.  A little unusual, but doesn't explain the double deactivate (to me anyway).

**Comment by rami-a** [comment]
Looks like the exception no longer happens. Closing this for now. @rmtmckenzie feel free to re-open if this is still an issue for you.
