### ISSUE TITLE
directory "/usr/lib/flutter/bin/cache/artifacts/gradle_wrapper" does not exist, nothing to copy 

### ISSUE THREAD

**Issue by hexaron** [flutter/flutter#147754]
## Command
```
flutter create test
```

## Steps to Reproduce
1. Do not have any flutter or dart related installed.
2. Install `flutter-devel 3.19.5-7` on Manjaro (together with its necessary dependencies).
3. Run the above command anywhere.

### exception

_Exception: Exception: Source directory "/usr/lib/flutter/bin/cache/artifacts/gradle_wrapper" does not exist, nothing to copy

```
#0      copyDirectory (package:flutter_tools/src/base/file_system.dart:120:5)
#1      CreateBase._injectGradleWrapper (package:flutter_tools/src/commands/create_base.dart:683:5)
#2      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:517:25)
<asynchronous suspension>
#3      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:361:31)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

### flutter doctor

```
[✓] Flutter (Channel , 3.19.5, on Manjaro Linux 6.8.5-1-MANJARO, locale de_DE.utf8)
    • Flutter version 3.19.5 on channel  at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19 03:14:08
    • Engine revision e76c95649884
    • Dart version 3.5.0-109.0.dev
    • DevTools version 2.35.0-dev.16

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/<name>/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /home/<name>/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.22+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.8.5-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
Hi @hexaron 
Looks like you are using a downstream Flutter SDK on https://aur.archlinux.org/packages/flutter-devel?O=20, right? 

Does the issue happen if you use Flutter upstream SDK on https://docs.flutter.dev/release/archive?tab=linux?

**Comment by hexaron** [comment]
This solution works, thanks!
