### ISSUE TITLE
[camera] regression: startImageStream throws MissingPluginException on iOS

### ISSUE THREAD

**Issue by PerLycke** [flutter/flutter#147702]
### Steps to reproduce

1. 'flutter run --release' using macos terminal with example code on an iPhone with iOS 17.4.1

### Expected results

You should, on every run, see "STREAM" printed in console, and not get a MissingPluginException.

### Actual results

Occasionally there is a MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/camera_avfoundation/imageStream) thrown. We had this issue on earlier camera_avfoundation versions: https://github.com/flutter/flutter/issues/109910

It was fixed back then, but issue is back. The example code I provide is just a slightly modified version seen in the linked issue.

The issue doesn't happen all the time. However I did upload a build to TestFlight and the issue was persistent on that occasion. I, as much as you, hate bugs you cannot reproduce 100% of the time, but this is a serious issue and it can find its way into all apps using image stream on iOS, which I guess a lot of apps use these days.

This is the exact error I see, when it actually occurs, when running the example code:

> flutter run --release
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                      1,312ms
> Xcode build done.                                           21.5s
> Installing and launching...                                         3.4s
> 
> Flutter run key commands.
> h List all available interactive commands.
> c Clear the screen
> q Quit (terminate the application on the device).
> [ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
> flutter: MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/camera_avfoundation/imageStream)
> flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
> flutter: <asynchronous suspension>
> flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676)
> flutter: <asynchronous suspension>

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:wakelock_plus/wakelock_plus.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cam issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late CameraController controller;
  List<CameraDescription>? cameras;

  @override
  void initState() {
    loadCameras();
    super.initState();
  }

  loadCameras() async {
    try {
      cameras = await availableCameras();
      setState(() {});
    } on CameraException catch (e) {
      print('Error: ${e.code}\nError Message: ${e.description}');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Cam issue"),
      ),
      body: body(),
    );
  }

  body() {
    if (cameras?.isNotEmpty ?? false) {
      return Center(
        child: MyCameraPreview(cameras: cameras!),
      );
    }
    return const Center(
      child: Text("Loading"),
    );
  }
}

class MyCameraPreview extends StatefulWidget {
  final List<CameraDescription> cameras;

  const MyCameraPreview({
    Key? key,
    required this.cameras,
  }) : super(key: key);

  @override
  State<MyCameraPreview> createState() => _MyCameraPreviewState();
}

class _MyCameraPreviewState extends State<MyCameraPreview> {
  late CameraController controller;
  bool isDetecting = false;

  @override
  void initState() {
    initController();
    super.initState();
  }

  @override
  void dispose() {
    WakelockPlus.disable();
    super.dispose();
  }

  Future<void> initController() async {
    controller = CameraController(
      widget.cameras[0],
      ResolutionPreset.high,
      enableAudio: false,
    );
    await controller.initialize();
    final maxZoomValue = await controller.getMaxZoomLevel();
    await controller.lockCaptureOrientation();
    if (!mounted) {
      return;
    }

    await controller.startImageStream((CameraImage img) async {
      print("STREAM");
    });

    await WakelockPlus.enable();

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return CameraPreview(controller);
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.19.6 on channel stable at /Users/per/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (2 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/per/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • Per’s iPhone (mobile) • xxx-xxx • ios            • iOS 17.4.1 21E236
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 124.0.6367.118

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I checked this and saw different results below:

- Flutter stable 3.16.9: 
   - The issue is reproduced in `debug` mode. 
   - I checked this a few times in `release` mode and couldn't reproduce the exception but I see callback wasn't being called
- Flutter master `3.22.0-21.0.pre.20`: 
    - The issue is not reproduced in `debug` mode and the callback is called as expected.
    - In `release` mode, the result is the same on Flutter stable 3.16.9 

But when I remove `wakelock_plus` usage from main.dart file, I don't see issue anymore on Flutter stable 3.16.9 in debug mode (in release mode, it stays the same as above). Could this package relate? Could you also check this again with these cases to make sure we see the same results?

**Comment by PerLycke** [comment]
Removing the use of `wakelock_plus` and I could no longer reproduce it on 3.19.6 stable. I'm not convinced about it though, as even with `wakelock_plus` it was not reproducible every time.

However, using something like `wakelock_plus`, with the intent of keeping your screen awake while using the camera and streaming images, causing the actual camera package to throw a MissingPluginException is weird, no?

Then I'm even more worried as one package can cause a package specific error to occur for a _different package_. I'm very confused.

That said, can we even conclude the use of wakelock_plus to be the actual issue here as it seems like some kind of race condition that happens occasionally?

**Comment by huycozy** [comment]
I also see the same result at https://github.com/flutter/flutter/issues/109910#issuecomment-1223417367 where the exception didn't occur but the camera stream callback wasn't called. Labeling this for further insights.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (31 hours ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-23.0.pre.14, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-23.0.pre.14 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7c62afb444 (77 minutes ago), 2024-05-02 21:48:17 -0400
    • Engine revision c380e9fd41
    • Dart version 3.5.0 (build 3.5.0-127.0.dev)
    • DevTools version 2.35.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.94

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by js2702** [comment]
We are having the same issue. We've done some debugging and it looks to be a problem in the camera_avfoundation version 0.9.15+1. The 0.9.15 works. We also are using wakelock_plus, so we need to do more testing.

**Comment by himanshuscapia** [comment]
Any update on this issue?

**Comment by ronstar** [comment]
@huycozy Is there any update with this? We also have the same issue, and couldn't find a workaround.

**Comment by Saad29** [comment]
Any updates here? We also have the same issue. Very hard to reproduce though, I can only see it in my sentry logs. Coincidentally, we are also using wakelock_plus

**Comment by SrivathsanSivakumar** [comment]
Downgrading to camera package to version 0.9.5 works for me

**Comment by maurojohann** [comment]
I'm experiencing the same problem as described in issue #166756. However, in my case, the code works correctly in Flutter version 3.27.3 but fails with an error when using Flutter version 3.29.3.

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/78d2b807-7d4a-474d-8223-c6995e0e1967" />

**Comment by davidmartos96** [comment]
> I'm experiencing the same problem as described in issue #166756. However, in my case, the code works correctly in Flutter version 3.27.3 but fails with an error when using Flutter version 3.29.3.
> 
> <img width="836" alt="Image" src="https://github.com/user-attachments/assets/78d2b807-7d4a-474d-8223-c6995e0e1967" />

It's a problem related to a multithread race condition during the initialization. 
You can try the fix in the following PR: https://github.com/flutter/packages/pull/8733

**Comment by ErrorCode-404** [comment]
Our customers are reporting the same error on iOS 18.5 (iPhone12,8). We are on flutter 3.29.3 and using camera: 0.11.1.
Unfortunately we couldn't reproduce the error. -.-

The PR https://github.com/flutter/packages/pull/8733 seems to solve the error. Does anybody know when the fix will be merged and when a new version of the plugin will be available?

Many thanks that there will be worked on a error solution ;)

**Comment by nebis-software** [comment]
Same issue here - the PR would be a lifesaver - any news?

**Comment by jscmidt** [comment]
Same issue here. Does anyone know a workaround until the PR is merged?

**Comment by estevez-dev** [comment]
> Same issue here. Does anyone know a workaround until the PR is merged?

Yes:
```yaml
dependency_overrides:
  camera_avfoundation: # TODO: remove after https://github.com/flutter/flutter/issues/147702
    git:
      url: https://github.com/SkillDevs/flutter_packages.git
      path: packages/camera/camera_avfoundation
      ref: fix_startstream_race_condition
```

**Comment by estevez-dev** [comment]
Have no idea why this is closed as `camera` still has this issue, because it depends on `camera_avfoundation` without the fix. The current workaround is:
```
dependency_overrides:
  camera_avfoundation: 0.9.19+3
```

**Comment by davidmartos96** [comment]
@estevez-dev It's a transitive dependency. You can upgrade it doing `flutter pub upgrade camera_avfoundation` or upgrade all your packages doing `flutter pub upgrade`

**Comment by estevez-dev** [comment]
> [@estevez-dev](https://github.com/estevez-dev) It's a transitive dependency. You can upgrade it doing `flutter pub upgrade camera_avfoundation` or upgrade all your packages doing `flutter pub upgrade`

Oh, sure. Thanks!
