### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by MohamedAhmedSaba** [flutter/flutter#147743]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:189:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:866:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:489:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel dev, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    [32m•[39m Flutter version 3.4.0-17.2.pre on channel dev at D:\fiutter\flutter_windows_3.19.6-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d6260f127f (1 year, 7 months ago), 2022-09-21 13:33:49 -0500
    [32m•[39m Engine revision 3950c6140a
    [32m•[39m Dart version 2.19.0 (build 2.19.0-146.2.beta)
    [32m•[39m DevTools version 2.16.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.88.1)
    [32m•[39m VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.63
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.67

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 676cefaaff197f27424942307668886253e1ec35
### Plugins
flutter_plugin_android_lifecycle-2.0.15
image_picker-0.7.2+1
path_provider-2.1.0
path_provider_android-2.1.0
path_provider_foundation-2.3.0
path_provider_linux-2.2.0
path_provider_windows-2.2.0
shared_preferences-0.5.5
shared_preferences_macos-0.0.1+11

**Comment by huycozy** [comment]
Hi @MohamedAhmedSaba, does this issue happen on the latest Flutter stable or master channel? If it does, could you share the entire output of `flutter run -v`? Thanks!

**Comment by dipendra-sharma** [comment]
remove `layout (location = x)` from your shader file, if using.
