### ISSUE TITLE
Add more browser support for flutter web product

### ISSUE THREAD

**Issue by ZhuChanJuan** [flutter/flutter#147965]
### Use case

As a QA, i need test my flutter project on different web browser : MacOS chrome/firefox/safari/edge, Android chrome, IOS chrome.
But i can only execute flutter test case on MacOS chrome , other web browsers can't be called by native testing framework.

### Proposal

I wanna my flutter test case could run more web browser types.

**Comment by ZhuChanJuan** [comment]
Thanks @danagbemava-nc , i tried many times by the way mentioned on the 2 documents but all failed. 
For example, if i execute the command ```
flutter drive   --driver=test_driver/integration_test.dart   --target=integration_test/card_collection_test.dart   -d web-se
rver --release --browser-name=firefox --local-engine=host_debug_unopt
```
I will get error like this :
Unable to detect local Flutter engine src directory.
Either specify a dependency_override for the sky_engine package in your pubspec.yaml and ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE
environment variable, or use --local-engine-src-path to specify the path to the root of your flutter/engine repository.

If i didn't add the --local-engine parameter in the command, the test case will always be executed on MacOS chrome.

**Comment by moffatman** [comment]
`--browser-name` is the argument to look at. You don't need local-engine / local-engine-src-path if you don't have your own engine changes. Can you try it with `-v` to collect deep logs and post it here? thx

**Comment by ZhuChanJuan** [comment]
hi @moffatman , the partial log for you :

**Comment by ZhuChanJuan** [comment]
hi @moffatman , if i change the -d from "web-server" to "chrome", the whole command will be 
`flutter drive   --driver=test_driver/integration_test.dart   --target=integration_test/app_test.dart   -d chrome --release --browser-name=edge -v`
then the MacOS chrome browser will be open automatically , i could see the web but it's not MacOS edge browser and i will get crash report like this : 
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --release --browser-name=edge -v

## exception

SessionNotCreatedException: SessionNotCreatedException (500): session not created: No matching capabilities found

```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, 3.22.0-0.3.pre, on macOS 14.3.1 23D60 darwin-arm64, locale en-CN)
    [32m•[39m Flutter version 3.22.0-0.3.pre on channel beta at /Users/vickyzhu/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 87b652410d (2 weeks ago), 2024-04-23 21:41:18 -0500
    [32m•[39m Engine revision b4bfd45986
    [32m•[39m Dart version 3.4.0 (build 3.4.0-282.3.beta)
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.156

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

**Comment by moffatman** [comment]
You need to use `-d web-server`. `-d chrome` will always open chrome yeah.

**Comment by ZhuChanJuan** [comment]
thanks @moffatman ~
but i wanna check the UI while running test cases on other web browser, is that possible ?
by the way even i use -d web-server --browser-name=edge, the test case can't be executed at all (i will paste the log for you) and i don't know how to check whether the test case is executed on other browsers except chrome.
The log for command `flutter drive   --driver=test_driver/integration_test.dart   --target=integration_test/app_test.dart   -d web-server --release --browser-name=edge`
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --release --browser-name=edge

## exception

SessionNotCreatedException: SessionNotCreatedException (500): session not created: No matching capabilities found

```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, 3.22.0-0.3.pre, on macOS 14.3.1 23D60 darwin-arm64, locale en-CN)
    [32m•[39m Flutter version 3.22.0-0.3.pre on channel beta at /Users/vickyzhu/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 87b652410d (2 weeks ago), 2024-04-23 21:41:18 -0500
    [32m•[39m Engine revision b4bfd45986
    [32m•[39m Dart version 3.4.0 (build 3.4.0-282.3.beta)
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/vickyzhu/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.76.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (5 available)
    [32m•[39m sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.3.1 23D60 darwin-arm64
    [32m•[39m Web Server (web)                • web-server            • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 124.0.6367.156

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

**Comment by moffatman** [comment]
Do you have edge installed? Or you may need specific WebDriver extension/plugin for edge to control it.

**Comment by ZhuChanJuan** [comment]
hi @moffatman , yes i installed the stable version edge and edge webdriver. also start the webdriver by command `msedgedriver --port=4444`
and they seems all works well.

but if i import the webdriver package and write test case "firefox_test.dart" like this :
`  test('My Flutter Web Test', () async {
    final driver = await createDriver(
      desired: {
        Capabilities.browserName: 'edge',
        // Capabilities.browserName: 'firefox',
      },
    );

    await driver.get('https://flutter.dev');
    Future.delayed(const Duration(seconds: 2));
    await driver.quit();
  });`

then execute the file by command 1 and command 2, all get errors
command 1 : `flutter drive   --driver=test_driver/integration_test.dart   --target=integration_test/firefox_test.dart`
command 2 : `flutter test integration_test/firefox_test.dart`

**Comment by moffatman** [comment]
Sorry I really don't know when. Will leave the ticket open someone from web team may know some more.

**Comment by danagbemava-nc** [comment]
Labeling this as a proposal for further insight from the web team

**Comment by ZhuChanJuan** [comment]
Thank you so much for your kindly help, and I am now really anxious to see if anyone has successfully run flutter native test cases on other web browsers except MacOS chrome ~

**Comment by ZhuChanJuan** [comment]
oh thanks so so much for your comment @yjbanov 

could you provide some sample code for me to run the flutter test cases by msedgedriver or geckodriver ?
, since i already installed stable version webdriver and web browser for them but don't know how to let them run on edge and firefox browsers.
i would be very appreciate for kindly help ~
