### ISSUE TITLE
crash when starting a flutter project in wsl2

### ISSUE THREAD

**Issue by GkIgor** [flutter/flutter#147946]
### Steps to reproduce

1. Install flutter sdk in link (https://docs.flutter.dev/get-started/install) any devices.
2. start project in vscode.
3. use commands `flutter run, flutter devices`
4. Crash! 

### Actual results

I installed the Flutter SDK on my WSL2 following the documentation instructions, set up everything for the framework to work with VS Code on WSL2, and so far, so good. I've been doing some tutorials using the Linux mode for debugging.

After completing the projects, I decided to test the Web, Windows, and Android modes. I looked in several places on how to show the emulators in VS Code and even tried USB debugging, but the device wouldn't show up. I gave up and tried the web again; I configured WSL to identify the Chrome executable, and it passed the flutter doctor check. However, when I try to use web debugging mode, it opens Chrome, and nothing happens. I thought it might be a compatibility issue and switched to the Web Server. Still, I can't get the project to run; it opens the browser at http://127.0.0.1:35559/, and nothing happens again. I thought about running Flutter commands through the terminal instead of VS Code, but I encounter the following error:

```bash

gkIgor@Debian:[ 07-05 19:14:11 ]:~/development/flutter/my-project/clima 🌱 flutter run
Connected devices:

Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

```

### Logs

<details open>
<summary>Logs</summary>

```console

No logs

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console


[✓] Flutter (Channel stable, 3.19.6, on Debian GNU/Linux 12 (bookworm) 5.15.146.1-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/c/Users/gkirxzin/AppData/Local/Android/Sdk
    • Platform android-34-ext8, build-tools 34.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 20)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1845:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1407:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
      #14     _rootRunUnary (dart:async/zone.dart:1415:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @GkIgor 
Can you run the command in verbose mode and provide the exception log it throws ? (ex: `flutter run -v` or `flutter devices -v`?
Most probably you are hitting https://github.com/flutter/flutter/issues/95279 that you can also check and confirm.

**Comment by GkIgor** [comment]
Yes! see the result:

# Doctor:

`flutter doctor -v`

## First time

Using a firts time, i had a message that kept looping until I closed it in the terminal.
Message: "Scanning for devices is taking a long time..."

output:

```bash
gkIgor@Debian:[ 08-05 13:13:58 ]:~/development/flutter/my-project/clima 🌱 flutter doctor -v
[✓] Flutter (Channel stable, 3.19.6, on Debian GNU/Linux 12 (bookworm) 5.15.146.1-microsoft-standard-WSL2, locale
    en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/c/Users/gkirxzin/AppData/Local/Android/Sdk
    • Platform android-34-ext8, build-tools 34.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

Sc[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm) 5.15.146.1-microsoft-standard-WSL2
    • Chrome (web)    • chrome • web-javascript • unknown

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Second time

Output:

```bash

gkIgor@Debian:[ 08-05 13:25:00 ]:~/development/flutter/my-project/clima 🌱 flutter doctor -v
[✓] Flutter (Channel stable, 3.19.6, on Debian GNU/Linux 12 (bookworm) 5.15.146.1-microsoft-standard-WSL2, locale en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/c/Users/gkirxzin/AppData/Local/Android/Sdk
    • Platform android-34-ext8, build-tools 34.0.0
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 20)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1845:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1407:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
      #14     _rootRunUnary (dart:async/zone.dart:1415:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```


# Devices

`flutter devices -v`

```bash
gkIgor@Debian:[ 08-05 13:22:08 ]:~ 🌱 flutter devices -v
[  +56 ms] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +97 ms] Found 2 connected devices:
[ +163 ms] "flutter devices" took 306ms.

[  +17 ms] Sending crash report to Google.
[+1154 ms] Crash report sent (report ID: d5c950fd81dcd56f)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".
[  +71 ms] executing: [/usr/bin/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 3 weeks ago

[  +46 ms] Sending crash report to Google.
[ +878 ms] Crash report sent (report ID: b7a827074b044b31)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +73 ms] Sending crash report to Google.
[ +866 ms] Crash report sent (report ID: 9500784d5e4ef70a)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +71 ms] Sending crash report to Google.
[ +874 ms] Crash report sent (report ID: cdb04572d485c679)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +71 ms] Sending crash report to Google.
[ +856 ms] Crash report sent (report ID: b34b297af0c8943f)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +81 ms] Sending crash report to Google.
[ +333 ms] Crash report sent (report ID: 24776eae56d44d02)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +72 ms] Sending crash report to Google.
[ +327 ms] Crash report sent (report ID: 08f54978e7766358)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +73 ms] Sending crash report to Google.
[ +896 ms] Crash report sent (report ID: 2de1a6ad66306e2c)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +68 ms] Sending crash report to Google.
[ +888 ms] Crash report sent (report ID: 066ded99f64a13db)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +70 ms] Sending crash report to Google.
[+1178 ms] Crash report sent (report ID: 7ee9b0841770ed13)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +78 ms] Sending crash report to Google.
[+1185 ms] Crash report sent (report ID: 9af32d731549acbd)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +73 ms] Sending crash report to Google.
[+1185 ms] Crash report sent (report ID: 7d9de0cf6f193d1a)
[        ] Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 20)".

[  +74 ms] Sending crash report to Google.
^C[ +170 ms] ensureAnalyticsSent: 61ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

```

^^^^^^
infinity loop, close with `CTRL + C`

**Comment by darshankawar** [comment]
Thanks for the update. Based on the exception log, it seems similar to https://github.com/flutter/flutter/issues/95279 in which you can follow-up for further updates. Closing this as a duplicate. You may share your findings in that issue for better tracking.
