### ISSUE TITLE
Service hardware keyboard broken

### ISSUE THREAD

**Issue by Prince-of-death** [flutter/flutter#147964]
### Steps to reproduce

this error happens when listening to the service.instance.keyboard

### Expected results

do whats inside the if statement

### Actual results

got some type of flutter error

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const EventsListener());
}

class EventsListener extends StatefulWidget {
  const EventsListener({
    super.key,
  });

  @override
  State<EventsListener> createState() => _EventsListenerState();
}

class _EventsListenerState extends State<EventsListener> {
  @override
  void initState() {
    super.initState();
    controller = widget.controller;
    ServicesBinding.instance.keyboard.addHandler(onKeyEvent);
  }

  @override
  void dispose() {
    ServicesBinding.instance.keyboard.removeHandler(onKeyEvent);
    super.dispose();
  }

  bool onKeyEvent(KeyEvent event) {
    final LogicalKeyboardKey key = event.logicalKey;

     if (key == LogicalKeyboardKey.space) {
        if (key is KeyRepeatEvent) {
        ////
          return true;
        }
        if (key is KeyUpEvent) {
          ////
          return true;
        }
     }
}

  @override
  Widget build(BuildContext context) {
    return MaterialApp(child: Center(Text("DFBDF")));
}
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#62db7(physicalKey: PhysicalKeyboardKey#e6f4b(usbHidUsage: "0x0007002a", debugName: "Backspace"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 84:43:38.592820)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 505 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:505:16)
hardware_keyboard.dart:505
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:520:6)
hardware_keyboard.dart:520
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:643:5)
hardware_keyboard.dart:643
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1167:37)
hardware_keyboard.dart:1167
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
platform_channel.dart:235
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603:35)
binding.dart:603
#8      _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
channel_buffers.dart:343
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737:22)
platform_dispatcher.dart:737
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
hooks.dart:257
(elided 2 frames from class _AssertionError)

Unable to parse JSON message:
The document is empty.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.3)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.89.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by Prince-of-death** [comment]
the issue was solved when i upgraded flutter
