### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by sanketp1** [flutter/flutter#148073]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:167:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:888:19)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#9      generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:56:30)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:307:9)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.6, on Ubuntu 24.04 LTS 6.8.0-31-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.19.6 on channel stable at /home/psanket18/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git

**Comment by darshankawar** [comment]
@sanketp1 
Can you check if you have required write permission to the directory where your flutter project is?
If not, grant write permission and re-run your scenario.
Also, check your shell configuration if it has required permissions and update it as required and re-run to see if it helps to resolve the issue or not.
