### ISSUE TITLE
[flutter_tool] Coverage is not collected during web tests

### ISSUE THREAD

**Issue by curt-weber** [flutter/flutter#148069]
### Steps to reproduce

Run any test with `flutter test --coverage --platform=chrome --verbose`.

### Expected results

Coverage should be collected. The `collector` (which is marked `watcher`) is never [passed](https://github.com/flutter/flutter/blob/bd443998655bc1cd94a2ea40d0bc65e8f4a3e7bd/packages/flutter_tools/lib/src/test/runner.dart#L198) on web.

### Actual results

Tests complete as expected but throw tool exit without collecting coverage.

### Code sample

<details open><summary>Code sample</summary>
</details>

### Logs

<details open><summary>Logs</summary>

```console
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:518:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19044.4291], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.5)  
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.89.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @curt-weber 
I think your issue is same as https://github.com/flutter/flutter/issues/55437 in which you can follow-up for further updates and go through underlying comments for reference.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by curt-weber** [comment]
Thanks @darshankawar - sometimes the github search fails me and populates way too many unrelated results...
