### ISSUE TITLE
IconButton Semantics Label

### ISSUE THREAD

**Issue by anasqadrei** [flutter/flutter#148167]
### Steps to reproduce

IconButton does not have a semantic label property. The closest it has is a tooltip property  which I find works as a label. it gets announced correctly on both iOS and Android. Also it shows as a label when `showSemanticsDebugger: true,` 

The problem is testing fails when using the line `expect(find.bySemanticsLabel('Settings'), findsOneWidget);`. Given the above, shouldn't tooltip be treated as a semantic label?

### Expected results

Test `expect(find.bySemanticsLabel('Settings'), findsOneWidget);` should pass

### Actual results

Test fails with error:
```
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _ElementPredicateWidgetFinder:<Found 0 widgets with element matching predicate: []>
   Which: means none were found but one was expected
```

### Code sample

<details open><summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      showSemanticsDebugger: true,
      home: Scaffold(
        body: Center(
          child: IconButton(
            onPressed: () => {},
            icon: const Icon(Icons.settings),
            tooltip: 'Settings',
          ),
        ),
      ),
    );
  }
}
```

</details>

<details open><summary>test/widget_test.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_icon_button/main.dart';

void main() {
  testWidgets('IconButton Semantics Label', (WidgetTester tester) async {
    await tester.pumpWidget(const MainApp());

    // Passes
    expect(find.byIcon(Icons.settings), findsOneWidget);

    // Prints "Settings" as a tooltip only, not a label
    debugDumpSemanticsTree();

    // Passes
    expect(
      tester.getSemantics(find.byIcon(Icons.settings)),
      containsSemantics(
        tooltip: 'Settings',
      ),
    );

    // Fails
    expect(find.bySemanticsLabel('Settings'), findsOneWidget);
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Semantics debugger shows it as a label</summary>
<img width="352" alt="Simulator Screenshot - iPhone SE (3rd generation)" src="https://github.com/flutter/flutter/assets/4755353/1f24959c-d936-4608-9010-70d033e9209e">
</details>

<details open>
<summary> Xcode Accessibility Inspector shows it as a label</summary>
<img width="352" alt="Xcode Accessibility Inspector Screenshot" src="https://github.com/flutter/flutter/assets/4755353/919d7fe0-f97d-4b4d-a3fd-09d4522c5d08">
</details>

### Logs

<details open><summary>Logs</summary>

```console
SemanticsNode#0
 │ Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
 │
 └─SemanticsNode#1
   │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0) scaled by 3.0x
   │ textDirection: ltr
   │
   └─SemanticsNode#2
     │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
     │ sortKey: OrdinalSortKey#87173(order: 0.0)
     │
     └─SemanticsNode#3
       │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
       │ flags: scopesRoute
       │
       └─SemanticsNode#4
           Rect.fromLTRB(376.0, 276.0, 424.0, 324.0)
           actions: tap
           flags: isButton, hasEnabledState, isEnabled, isFocusable
           tooltip: "Settings"
           textDirection: ltr

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _ElementPredicateWidgetFinder:<Found 0 widgets with element matching predicate: []>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/anasqaderi/Coding/play/flutter_icon_button/test/widget_test.dart:26:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/anasqaderi/Coding/play/flutter_icon_button/test/widget_test.dart line 26
The test description was:
  IconButton Semantics Label
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-AU)
    • Flutter version 3.19.6 on channel stable at /Users/anasqaderi/Coding/exe/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/anasqaderi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (5 available)
    • Anas iPhone 15 Pro Max (mobile)     • 00008130-001079A10A98001C            • ios            • iOS 17.4.1 21E236
    • Anas iPhone XS Max (mobile)         • 00008020-000E6CCA1104002E            • ios            • iOS 17.4.1 21E236
    • iPhone SE (3rd generation) (mobile) • D87F979D-BDD6-4EA4-95E5-E2DE477B4193 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 124.0.6367.201

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample provided above. 


<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.19.6 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 124.0.6367.158

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.22.0-31.0.pre.21, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.0-31.0.pre.21 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c336c2a44e (2 hours ago), 2024-05-13 01:47:29 -0400
    • Engine revision 57e74a1b38
    • Dart version 3.5.0 (build 3.5.0-147.0.dev)
    • DevTools version 2.36.0-dev.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.4.1 21E236
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 124.0.6367.158

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
Hi @anasqadrei 
You can provide semantic in the `Icon` widget in `IconButton`

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      showSemanticsDebugger: true,
      home: Scaffold(
        body: Center(
          child: IconButton(
            onPressed: () => {},
            isSelected: true,
            icon: const Icon(
              Icons.settings,
              semanticLabel: 'Settings',
            ),
          ),
        ),
      ),
    );
  }
}
```

This test pass now
```dart

void main() {
  testWidgets('IconButton Semantics Label', (WidgetTester tester) async {
    await tester.pumpWidget(const MainApp());

    // Passes
    expect(find.byIcon(Icons.settings), findsOneWidget);

    // Prints "Settings" as a tooltip only, not a label
    debugDumpSemanticsTree();

    expect(find.bySemanticsLabel('Settings'), findsOneWidget);
  });
}
```

This is tested here in the framework:
https://github.com/flutter/flutter/blob/ca3aeb015119c11075187535cdd2b54b7133c029/packages/flutter/test/material/icon_button_test.dart#L606-L628

If you've any question, feel free to comment.

**Comment by anasqadrei** [comment]
It worked. Thanks 👍
