### ISSUE TITLE
Stocks example app doesn't render any rows (just white) with `--preview-dart-2`

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14819]
Using latest code from master (b6d8615aed8062e6e9d3dff7d340edf2982c4847) if I run the Stocks app, the data rows are not rendered (they render fine without `--preview-dart2`):

<img src="https://user-images.githubusercontent.com/1078012/36540970-423ff9e0-17d4-11e8-91fc-6c7693e567a2.png" width="250" />

Console output below (I don't know if the output is related to the issue).

```text
Running "flutter packages get" in stocks...
Launching lib\main.dart on XT1562 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (30.2MB).
I/FlutterActivityDelegate(24032): onResume setting current activity to this
E/flutter (24032): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (24032): type '_BoundSinkStream<dynamic, List<int>>' is not a subtype of type '_HttpIncoming' where
E/flutter (24032):   _BoundSinkStream is from dart:async
E/flutter (24032):   List is from dart:core
E/flutter (24032):   int is from dart:core
E/flutter (24032):   List is from dart:core
E/flutter (24032):   int is from dart:core
E/flutter (24032):   _HttpIncoming is from dart:_http
E/flutter (24032):   List is from dart:core
E/flutter (24032):   int is from dart:core
E/flutter (24032):
E/flutter (24032): #0      _HttpClientResponse.listen (dart:_http/http_impl.dart:382:23)
E/flutter (24032): #1      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
E/flutter (24032): #2      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
E/flutter (24032): #3      _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
E/flutter (24032): #4      StreamView.listen (dart:async/stream.dart:1745:20)
E/flutter (24032): #5      ByteStream.toBytes (package:http/src/byte_stream.dart:24:5)
E/flutter (24032): #6      Response.fromStream (package:http/src/response.dart:69:28)
E/flutter (24032): #7      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:21)
E/flutter (24032): <asynchronous suspension>
E/flutter (24032): #8      BaseClient.get (package:http/src/base_client.dart:34:5)
E/flutter (24032): #9      StockData._fetchNextChunk (file:///M:/Coding/Applications/flutter/examples/stocks/lib/stock_data.dart:81:17)
E/flutter (24032): #10     new StockData (file:///M:/Coding/Applications/flutter/examples/stocks/lib/stock_data.dart:46:7)
E/flutter (24032): #11     StocksAppState.initState (file:///M:/Coding/Applications/flutter/examples/stocks/lib/main.dart:60:18)
E/flutter (24032): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:14)
E/flutter (24032): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter (24032): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
E/flutter (24032): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
E/flutter (24032): #16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
E/flutter (24032): #17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
E/flutter (24032): #18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
E/flutter (24032): #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
E/flutter (24032): #20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
E/flutter (24032): #21     ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
E/flutter (24032): #22     runApp (package:flutter/src/widgets/binding.dart:699:7)
E/flutter (24032): #23     main (file:///M:/Coding/Applications/flutter/examples/stocks/lib/main.dart:147:3)
E/flutter (24032): #24     _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
E/flutter (24032): #25     _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
```

@devoncarew @mit-mit

**Comment by mit-mit** [comment]
cc @mraleph @a-siva

**Comment by mraleph** [comment]
Would be fixed by https://dart-review.googlesource.com/c/sdk/+/43020 which is in the CQ right now.

**Comment by joaquinrok** [comment]
@mraleph this does not seem to be solved. The stock example app still crashes when sending a request. 
'_BoundSinkStream<dynamic, List<int>>' is not a subtype of type '_HttpIncoming'

**Comment by dovahkiin98** [comment]
They say it's been solved but the error still exists

**Comment by dovahkiin98** [comment]
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (10 days ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

**Comment by DanTup** [comment]
The fix for this was in the Dart SDK and the version in the `beta` branch doesn't contain it. I've just tested on `master` branch and it definitely seems fixed there to me 👍
