### ISSUE TITLE
Audio play error in http url

### ISSUE THREAD

**Issue by muthu-lakshmi98** [flutter/flutter#148287]
### Steps to reproduce

I am playing this audio [http://103.210.73.190:4002/assets/audio/SME/en/SME_en.m3u8](url)
I am running the app in debug mode. 
I am facing issues in Android. In chrome working fine. I referred and followed these steps [https://stackoverflow.com/questions/63032101/networksecurityconfig-using-network-security-config-from-resource-network-secu](url)

**Error**
Using Network Security Config from resource network_security_config debugBuild: true
E/ExoPlayerImplInternal( 8212): Playback error

### Expected results

I want to play audio on Android. 

### Actual results

```
I/ExoPlayerImpl( 7303): Init 35476c7 [ExoPlayerLib/2.18.7] [tissot_sprout, Mi A1, Xiaomi, 28]
W/tter_http_audi( 7303): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
I/DpmTcmClient( 7303): RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
D/NetworkSecurityConfig( 7303): Using Network Security Config from resource network_security_config debugBuild: true
E/ExoPlayerImplInternal( 7303): Playback error
E/ExoPlayerImplInternal( 7303):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
E/ExoPlayerImplInternal( 7303):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 7303):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal( 7303):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 7303):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$CleartextNotPermittedException: Cleartext HTTP traffic not permitted. See https://developer.android.com/guide/topics/media/issues/cleartext-not-permitted
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal( 7303):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 7303):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 7303):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 7303):   Caused by: java.io.IOException: Cleartext HTTP traffic to 103.210.73.190 not permitted
E/ExoPlayerImplInternal( 7303):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal( 7303):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal( 7303):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:653)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal( 7303):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:376)
E/ExoPlayerImplInternal( 7303):       ... 9 more
E/AudioPlayer( 7303): TYPE_SOURCE: Cleartext HTTP traffic not permitted. See https://developer.android.com/guide/topics/media/issues/cleartext-not-permitted
I/ExoPlayerImpl( 7303): Release 35476c7 [ExoPlayerLib/2.18.7] [tissot_sprout, Mi A1, Xiaomi, 28] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.hls, goog.exo.datasource]
E/flutter ( 7303): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (0) Source error
E/flutter ( 7303): #0      AudioPlayer._load (package:just_audio/just_audio.dart:869:9)
E/flutter ( 7303): <asynchronous suspension>
E/flutter ( 7303): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1465:28)
E/flutter ( 7303): <asynchronous suspension>

```
### Code sample

<details open><summary>Code sample</summary>

```dart
**main/Manifest file** 
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <application
        android:label="flutter_http_audio"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <!-- Required to query activities that can process text, see:
         https://developer.android.com/training/package-visibility?hl=en and
         https://developer.android.com/reference/android/content/Intent#ACTION_PROCESS_TEXT.

         In particular, this is used by the Flutter engine in io.flutter.plugin.text.ProcessTextPlugin. -->
    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT"/>
            <data android:mimeType="text/plain"/>
        </intent>
    </queries>
</manifest>

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4291], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment]
> ioPlayer( 7303): TYPE_SOURCE: Cleartext HTTP traffic not permitted. See https://developer.android.com/guide/topics/media/issues/cleartext-not-permitted
> I/ExoPlayerImpl( 7303): Release 35476c7 [ExoPlayerLib/2.18.7] [tissot_sprout, Mi A1, Xiaomi, 28] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.hls, goog.exo.datasource]
> E/flutter ( 7303): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (0) Source error
> E/flutter ( 7303): #0      AudioPlayer._load (package:just_audio/just_audio.dart:869:9)
> E/flutter ( 7303): <asynchronous suspension>
> E/flutter ( 7303): #1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1465:28)
> E/flutter ( 7303): <asynchronous suspension>

@muthu-lakshmi98 It seems you are using just_audio community package and above log is pointing towards it, so I suggest you to file the issue there for further updates from package owner.
Also, other logs are coming from native Android and not from flutter, so I suggest you to also ask the same question in stackoverflow.
