### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null) #0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7) <asynchronous suspension> #1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5) <asynchronous suspension>

### ISSUE THREAD

**Issue by AmolPatil-Git** [flutter/flutter#148208]
### Steps to reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null)
#0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5)
<asynchronous suspension>

### Expected results

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null)
#0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5)
<asynchronous suspension>

### Actual results

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null)
#0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5)
<asynchronous suspension>

### Code sample

 Future<void> _handlePendingPurchase(PurchaseDetails purchaseDetails) async {
    // Implement your logic to handle pending purchase
    // For example, show a loading indicator or message to the user
    // You may also prompt the user to complete the purchase if needed

      try {
        // Complete the transaction
      //  await InAppPurchase.instance.completePurchase(purchaseDetails);
        _inAppPurchase.completePurchase(purchaseDetails);

        // Transaction completed successfully
        toast('Transaction completed: ${purchaseDetails.productID}');
      } catch (e) {
        // Handle error
        toast('Error completing transaction: $e');
      }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null)
#0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5)
<asynchronous suspension>

### Flutter Doctor output

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storekit_finish_transaction_exception, NSInvalidArgumentException, Cannot finish a purchasing transaction, null)
#0      InAppPurchaseAPI.finishTransaction (package:in_app_purchase_storekit/src/messages.g.dart:737:7)
<asynchronous suspension>
#1      SKPaymentQueueWrapper.finishTransaction (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:164:5)
<asynchronous suspension>

**Comment by darshankawar** [comment]
@AmolPatil-Git Please try to fill out the template details with relevant info, like flutter doctor output and steps to reproduce. Currently you just pasted the exception log everywhere without providing much details.

According to the error received, you are probably trying to call finish transaction on a transaction that has the state purchasing. So try to revisit your code implementation and see if anything is missing in it or not.
Also, provide steps to replicate with flutter doctor -v and iOS version you are using and whether this occurs locally in debug mode or in production with complete reproducible code sample.
