### ISSUE TITLE
3.22 iOS --release build fails

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#148352]
### Steps to reproduce

After upgrading this morning from 3.19 to 3.22, and changing nothing about Xcode, I can no longer build a release version.  Debug mode is fine and opens on a simulator as expected. 

### Expected results

The release build should execute successfully like the debug build does.

### Actual results

The release build is throwing the following:

```
[ +128 ms] Failed to build iOS app
[ +151 ms] Error (Xcode): [+8266 ms] Unhandled exception:

[   +1 ms] "flutter ios" took 233,830ms.
[  +18 ms] Encountered error while building for device.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:691:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[  +73 ms] exiting with code 1
```

### Code sample

There is no relevant code sample. 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter build ios -v --release --flavor dev -t lib/main_dev.dart
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at /Users/neil/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (5 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/neil/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @blaneyneil 
I am unable to replicate this with a sample flavors app with latest stable version.
Can you provide us a sample repo that we can use to verify this further ?

Also, if you try to build through XCode in release mode, do you still get same error ?

**Comment by blaneyneil** [comment]
Building through XCode does produce the same "Error (Xcode): [+8319 ms] Unhandled exception:" in release mode.  I'm trying to narrow the codebase down to isolate what this could possibly be.

**Comment by blaneyneil** [comment]
I unfortunately can't pin down the problem.  I have a pretty large codebase and played whack-a-mole on a cloned repo til nearly every 3rd party package was removed.  Along with stripping most of the code down to basic components.  And yet I'd still get inexplicable "Unhandled exception" in release builds.  Sometimes inconsistently - i.e., I'd delete a block of code, run a release build that worked and think I finally narrowed it down, only to have it be a false positive. Something seems very broken in the 3.22 iOS build process.  I wish had better XCode debugging skills, but I don't.

As soon as I reverted to 3.19.6 everything was fine.

**Comment by darshankawar** [comment]
Thanks for trying. Can you run in verbose mode and provide the entire log here in properly formatted text ?

**Comment by blaneyneil** [comment]
Attached is the piped console output for release builds on both 3.22 ("Unhandled exception") and 3.19.6 (success).  These are from my full codebase and not the stripped-down version I was using to narrow down the problem.  

While I used a flavor in the build command here, I was not using flavors during my testing on the cloned repo.  

And as mentioned, debug mode works as expected on both 3.22 & 3.19.6 - it's just release mode on 3.22 that's throwing.
[319_release.txt.zip](https://github.com/flutter/flutter/files/15394685/319_release.txt.zip)
[322_release.txt.zip](https://github.com/flutter/flutter/files/15394687/322_release.txt.zip)

**Comment by darshankawar** [comment]
Posting the 3.22.0 release build log (failure part) here for quick reference:

<details>
<summary> failure part </summary>

```

[  +95 ms] Persisting file store
             [   +1 ms] Done persisting file store
             [   +3 ms] "flutter assemble" took 8,467ms.
             [        ] Running 0 shutdown hooks
             [        ] Shutdown hooks complete
             [        ] exiting with code 1
             error: [+7862 ms] Unhandled exception:
                        RangeError (offset): Invalid value: Not in inclusive range 0..3526: 3815
                        #0      RangeError.checkValueInInterval (dart:core/errors.dart:313)
                        #1      Source.getLocation (package:kernel/ast.dart:14992)
                        #2      Component.getLocation (package:kernel/ast.dart:14787)
                        #3      _getLocationInComponent (package:kernel/ast.dart:15181)
                        #4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
                        #5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
                        #6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
                        #7      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
                        #8      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
                        #9      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
                        #10     TreeNode.location (package:kernel/ast.dart:203)
                        #11     localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
                        #12     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:628)
                        #13     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1782)
                        #14     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:398)
                        #15     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:287)
                        #16     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1663)
                        #17     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1606)
                        #18     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1811)
                        #19     transformComponent (package:vm/transformations/type_flow/transformer.dart:121)
                        #20     runGlobalTransformations (package:vm/kernel_front_end.dart:589)
                        #21     compileToKernel (package:vm/kernel_front_end.dart:489)
                        <asynchronous suspension>
                        #22     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
                        <asynchronous suspension>
                        #23     starter (package:frontend_server/starter.dart:101)
                        <asynchronous suspension>
                        #24     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
                        <asynchronous suspension>

             [        ] Target kernel_snapshot failed: Exception
                        #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:274:7)
                        <asynchronous suspension>
                        #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
                        <asynchronous suspension>
                        #2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
                        <asynchronous suspension>
                        #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
                        <asynchronous suspension>
                        #4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
                        <asynchronous suspension>
                        #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
                        <asynchronous suspension>
                        #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
                        <asynchronous suspension>
                        #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:322:32)
                        <asynchronous suspension>
                        #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
                        <asynchronous suspension>
                        #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                        <asynchronous suspension>
                        #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
                        <asynchronous suspension>
                        #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
                        <asynchronous suspension>
                        #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
                        <asynchronous suspension>
                        #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #16     main (package:flutter_tools/executable.dart:93:3)
                        <asynchronous suspension>

             [   +1 ms] 
                        #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                        #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:339:7)
                        <asynchronous suspension>
                        #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
                        <asynchronous suspension>
                        #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                        <asynchronous suspension>
                        #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
                        <asynchronous suspension>
                        #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
                        <asynchronous suspension>
                        #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
                        <asynchronous suspension>
                        #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                        <asynchronous suspension>
                        #10     main (package:flutter_tools/executable.dart:93:3)
                        <asynchronous suspension>
             Failed to package /Users/neil/web/flutter/groupspot2.

             warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
             warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
             warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')
             note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
             note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
             warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')

             Result bundle written to path:
             	/var/folders/gg/y838_dds7nv7bn2f3zzzg2_c0000gn/T/flutter_tools.ka5ucZ/flutter_ios_build_temp_dirZMJARQ/temporary_xcresult_bundle


             ** BUILD FAILED **


             The following build commands failed:
             	PhaseScriptExecution Run\ Script /Users/neil/Library/Developer/Xcode/DerivedData/Runner-gwinpvsmxixqlyadxiakhdswlgoh/Build/Intermediates.noindex/Runner.build/Release-dev-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
             (1 failure)
[ +273 ms] Running Xcode build... (completed in 166.0s)
[        ] Xcode build done. 

```

</details>

**Comment by darshankawar** [comment]
Looks like similar to 

https://github.com/flutter/flutter/issues/144176
https://github.com/flutter/flutter/issues/140318

Which were fixed That you can take a look and check if these help in your case or not.

**Comment by blaneyneil** [comment]
https://github.com/flutter/flutter/issues/148565

It looks like it's (whatever "it" is, i'm still unsure of) resolved in the latest master?

**Comment by blaneyneil** [comment]
And per the comment here: https://github.com/flutter/flutter/issues/144176#issuecomment-1979273953

I had removed Sentry, Rive, PackageInfoPlus, and SharePlus (all of which I used) from my stripped-down repo that I was using to debug.

**Comment by darshankawar** [comment]
You can try by switching to latest master and re-run your scenario to confirm.

`flutter channel master`
`flutter upgrade`

**Comment by PerLycke** [comment]
We also get this error on stable 3.22.1. Did not get the error prior to 3.22.

There is no issue building an example ios app, pure `flutter create --platform ios .`

Our app is a big production app, with several that uses FFI (all version 2.0.1) and the work to single out the problematic pub would be tedious.

Also, on master I do not get the issue. I would hope to see the changes resolving https://github.com/flutter/flutter/issues/144176 to be cherry-picked into stable or beta, if this fixes this particular issue.

Build error as seen in Xcode when trying to archive:

```console
error: Unhandled exception:
RangeError (offset): Invalid value: Not in inclusive range 0..2813: 10068
#0      RangeError.checkValueInInterval (dart:core/errors.dart:313)
#1      Source.getLocation (package:kernel/ast.dart:14992)
#2      Component.getLocation (package:kernel/ast.dart:14787)
#3      _getLocationInComponent (package:kernel/ast.dart:15181)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:3329)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:207)
#7      TreeNode.location (package:kernel/ast.dart:203)
#8      localFunctionName (package:vm/transformations/type_flow/utils.dart:449)
#9      SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:628)
#10     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1782)
#11     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:398)
#12     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:287)
#13     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1663)
#14     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1606)
#15     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1811)
#16     transformComponent (package:vm/transformations/type_flow/transformer.dart:121)
#17     runGlobalTransformations (package:vm/kernel_front_end.dart:589)
#18     compileToKernel (package:vm/kernel_front_end.dart:489)
<asynchronous suspension>
#19     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#20     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#21     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
```

flutter build ios -v:

```console
[  +44 ms] Failed to build iOS app
[   +6 ms] Error (Xcode): [+8779 ms] Unhandled exception:
           
[   +2 ms] "flutter ios" took 28,427ms.
[   +1 ms] Encountered error while building for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:691:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by blaneyneil** [comment]
I still don't have the slightest clue why, but the current master channel successfully builds a release version.  stable's 3.22.1 was throwing the same unhandled exception as 3.22.0.

[✓] Flutter (Channel master, 3.23.0-13.0.pre.43, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.43 on channel master at /Users/neil/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1423723ff (45 minutes ago), 2024-05-30 16:37:47 -0700
    • Engine revision bf2e32dfd5
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10

**Comment by darshankawar** [comment]
Good to know and thanks for verifying. Since it works in master, I'll close this as fixed. Seems like fixes made in dart must have fixed this one as well, as most of the logs were pointing to dart core. If you disagree, write in comments and I'll reopen it.
