### ISSUE TITLE
Fatal Java exception when dialing the phone

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#148315]
### Steps to reproduce

I'm trying to dial the phone from my app, with a `'tel:'` scheme

### Expected results

-

### Actual results

Sometimes a weird FATAL exception is thrown in the console.
It appears on "Choose the app to make a call" dialog (I have several apps with dialing capability installed: default dialer, GetContact, Yandex, bank app and so on).
Or it may appear on going back from the system dialer to my app.
When I pressed "remember this option", it didn't appear anymore.

My device is Xiaomi Mi 11 Lite.

### Code sample

<details open><summary>Code sample</summary>

```dart
final phoneSupport = '8 (800) 250-48-46';
await launchUrl(Uri.parse('tel:$phoneSupport'));
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/AndroidRuntime(29642): FATAL EXCEPTION: pool-6-thread-1
E/AndroidRuntime(29642): Process: ru.mts.ourmts, PID: 29642
E/AndroidRuntime(29642): java.lang.NoSuchMethodError: No static method i(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V in class Lcom/google/android/datatransport/runtime/logging/Logging; or its super classes (declaration of 'com.google.android.datatransport.runtime.logging.Logging' appears in base.apk)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:286)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.cct.CctTransportBackend.$r8$lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.cct.CctTransportBackend$$ExternalSyntheticLambda0.apply(Unknown Source:4)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:123)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$com-google-android-datatransport-runtime-scheduling-jobscheduling-Uploader(Uploader.java:88)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$ExternalSyntheticLambda0.run(Unknown Source:8)
E/AndroidRuntime(29642): 	at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
E/AndroidRuntime(29642): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(29642): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(29642): 	at java.lang.Thread.run(Thread.java:1012)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-arm64, locale ru-RU)
    • Flutter version 3.22.0 on channel stable at /Users/svmolchan1/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (5 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/svmolchan1/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • M2101K9AG (mobile)              • cc706425              • android-arm64  • Android 13 (API 33)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 120.0.6099.216
    ! Error: Browsing on the local area network for iPhone (Сергей). Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @subzero911, do you experience this issue in a new project with `url_launcher` ?  

What version of `url_launcher` are you using and do you see this with only `Xiaomi Mi 11 Lite`? 

Do you get this every time or is it sporadic?

I tested on my Pixel 7 but I can't seem to reproduce the issue.
