### ISSUE TITLE
[ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.requestSendAccessibilityEvent(android.view.View, android.view.accessibility.AccessibilityEvent)' on a null object reference                                                                                                     

### ISSUE THREAD

**Issue by hezhipengzipp** [flutter/flutter#148311]
### Steps to reproduce

Using FlutterView on Android will cause crashes

### Expected results

FlutterView is used normally

### Actual results

crash
 [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.requestSendAccessibilityEvent(android.view.View, android.view.accessibility.AccessibilityEvent)' on a null object reference
                                                                                                    	at io.flutter.view.AccessibilityBridge.sendAccessibilityEvent(AccessibilityBridge.java:1952)
                                                                                                    	at io.flutter.view.AccessibilityBridge.sendWindowContentChangeEvent(AccessibilityBridge.java:2011)
                                                                                                    	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1762)
                                                                                                    	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:351)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:805)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:337)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:168)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8118)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2024-05-14 19:34:27.682 23924-23924 flutter                 com.het.family.sport.controller      A  [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1380)] Check failed: fml::jni::CheckException(env). 

### Code sample

<details open><summary>Code sample</summary>

```dart
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        // 创建 FlutterView 并设置到布局中
        val flutterView = FlutterView(this)
        binding.flContainer.addView(flutterView)
        flutterView.attachToFlutterEngine(flutterEngine)
        channel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, ChannelConstant.REQUEST_CHANNEL)
}


xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/cl_root"
        android:layout_width="match_parent"
        android:layout_height="61dp"
        android:layout_marginTop="25dp"
        app:layout_constraintTop_toTopOf="parent">

        <ImageView
            android:id="@+id/iv_back"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="16dp"
            android:padding="10dp"
            android:src="@mipmap/icon_pub_back"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <TextView
            android:id="@+id/tv_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="我的家庭"
            android:textColor="@color/color_1e1e1e"
            android:textSize="17sp"
            android:textStyle="bold"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent" />


        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/cs_right_part"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginRight="16dp"
            android:background="@drawable/bg_merge_family"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <TextView
                android:id="@+id/tv_right_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="3dp"
                android:gravity="center"
                android:paddingTop="3dp"
                android:paddingRight="8dp"
                android:paddingBottom="3dp"
                android:text="合并"
                android:textColor="#fff7567c"
                android:textSize="12sp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintLeft_toRightOf="@+id/iv_right_image"
                app:layout_constraintRight_toRightOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_goneMarginLeft="8dp" />

            <ImageView
                android:id="@+id/iv_right_image"
                android:layout_width="15dp"
                android:layout_height="15dp"
                android:layout_marginLeft="8dp"
                android:layout_marginTop="6dp"
                android:src="@mipmap/icon_merge_left"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintRight_toLeftOf="@+id/tv_right_name"
                app:layout_constraintTop_toTopOf="parent" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>

    <FrameLayout
        android:id="@+id/fl_Container"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/cl_root" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/19803305/dfe6ef4d-44ee-4ec5-a8c8-da9ce920e248)

</details>

### Logs

<details open><summary>Logs</summary>

```console
2024-05-14 19:34:27.682 23924-23924 flutter                 com.het.family.sport.controller      E  [ERROR:flutter/fml/platform/android/jni_util.cc(206)] java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.requestSendAccessibilityEvent(android.view.View, android.view.accessibility.AccessibilityEvent)' on a null object reference
                                                                                                    	at io.flutter.view.AccessibilityBridge.sendAccessibilityEvent(AccessibilityBridge.java:1952)
                                                                                                    	at io.flutter.view.AccessibilityBridge.sendWindowContentChangeEvent(AccessibilityBridge.java:2011)
                                                                                                    	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1762)
                                                                                                    	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:351)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:805)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:337)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:168)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8118)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2024-05-14 19:34:27.682 23924-23924 flutter                 com.het.family.sport.controller      A  [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1380)] Check failed: fml::jni::CheckException(env). 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [版本 10.0.17763.5696], locale zh-CN) 
    • Flutter version 3.19.6 on channel stable at C:\Users\800573\flutter                       
    • Upstream repository https://github.com/flutter/flutter.git                                
    • Framework revision 54e66469a9 (4 weeks ago), 2024-04-17 13:08:03 -0700                    
    • Engine revision c4cd48e186                                                                
    • Dart version 3.3.4 
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0) 
    • Android SDK at C:\Users\800573\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\800573\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows 
        Windows 10 SDK

[√] Android Studio (version 4.0)
    • Android Studio at D:\soft\android-studio-ide-193.6821437-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Android Studio (version 2023.2) 
    • Android Studio at C:\Program Files\Android\Android Studio 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] Android Studio (version 4.2)
    • Android Studio at D:\soft\android-studio-ide-202.7322048-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter 
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by hezhipengzipp** [comment]
binding.flutterView.attachToFlutterEngine(flutterEngine!!)  need after   setContentView(binding.root) calls
