### ISSUE TITLE
[et] Failed to parse JSON output from `gn desc`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#148431]
## Seen at
14d27622b3144d1e14218cbb789846b00360416a

## Reproduction
```sh
$ ./flutter/bin/et build -c host_debug_unopt_arm64 //flutter/impeller:impeller_unittests
[2024-05-15 15:03:50.299682] ERROR: Failed to parse JSON output from `gn desc`:
FormatException: Unexpected character (at character 1)
WARNING at build arg file (use "gn args <out_dir>" to edit):47:24: Build ar...
^

[2024-05-15 15:03:50.306646] ERROR: FatalError caught in main. Please file a bug
error: Failed to parse JSON output from `gn desc`:
FormatException: Unexpected character (at character 1)
WARNING at build arg file (use "gn args <out_dir>" to edit):47:24: Build ar...
^


stack: #0      Logger.fatal (package:engine_tool/src/logger.dart:125:5)
#1      Gn.desc (package:engine_tool/src/gn.dart:69:27)
<asynchronous suspension>
#2      BuildCommand.run (package:engine_tool/src/commands/build_command.dart:85:41)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      ToolCommandRunner.run (package:engine_tool/src/commands/command_runner.dart:97:14)
<asynchronous suspension>
#5      main (package:engine_tool/main.dart:86:19)
<asynchronous suspension>
```

**Comment by gaaclarke** [comment]
I think maybe the error may be more apparent if the output wasn't elided.  I didn't add those elipses in the description.  I think after them may have been the GN error.

**Comment by gaaclarke** [comment]
`et` works fine for my diff at 1ccd0c308b3a567fc41bc287a584f0946cca6c6b.  Something went wrong between those commits.

**Comment by gaaclarke** [comment]
My diff added a file to GN, I'm not sure if that is required for reproducing the bug.  I can supply it if it helps.

**Comment by matanlurey** [comment]
That could be useful

**Comment by matanlurey** [comment]
Locally I can't reproduce:
```sh
flutter % et build -c host_debug_unopt_arm64 //flutter/impeller:impeller_unittests
[2024-05-15T15:57:18.043][macos/host_debug_unopt_arm64: GN]: OK
[2024-05-15T15:57:19.041][macos/host_debug_unopt_arm64: RBE startup]: Proxy started successfully.
[2024-05-15T15:59:05.520][macos/host_debug_unopt_arm64: ninja]: 100.0% (893/893) LINK ./impeller_unittests
[2024-05-15T15:59:05.524][macos/host_debug_unopt_arm64: ninja]: OK
[2024-05-15T15:59:05.893][macos/host_debug_unopt_arm64: RBE shutdown]: Actions completed: 374 (331 cache hits, 43 racing locals)
```

**Comment by matanlurey** [comment]
Reduced to P1: the problem is we're not giving actionable feedback, not my specific patch.

https://github.com/flutter/engine/commit/41f10275bf1e432671ade35cf13403c73ea68a50 removed `concurrent_dart_jobs`, requiring a `./tools/gn --unopt --mac-cpu=arm64` that `et` doesn't handle today. I'll fix the logging issue (1-line fix), and file another issue for improved error handling/recovery.
