### ISSUE TITLE
"flutter build web" specifying output not working since flutter upgrade to 3.22 (from 3.16)

### ISSUE THREAD

**Issue by cmarques2** [flutter/flutter#148542]
### Steps to reproduce

create a new flutter app

```
flutter create test_output
cd test_output
flutter pub get
```

try to build it to a directory one up from itself

```
flutter build web --output=..\build
```

### Actual results

Error:
Could not write file to ..\build\assets\shaders/ink_sparkle.frag

### Logs

<details open>
<summary>Logs</summary>

```console

[  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +27 ms] Skipping pub get: version match.
[  +77 ms] Generating
D:\dev_test_aps\test_output\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +37 ms] generated_plugin_registrant.dart not found. Skipping.
[   +5 ms] Compiling lib\main.dart for the Web...
[   +2 ms] Initializing file store
[   +5 ms] Done initializing file store
[  +20 ms] Skipping target: web_entrypoint
[   +1 ms] Skipping target: gen_localizations
[        ] invalidated build due to missing files: D:\dev_test_aps\test_output\web\*\index.html,
D:\dev_test_aps\test_output\web\flutter_bootstrap.js
[        ] web_templated_files: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were
missing: D:\dev_test_aps\build\*\index.html, InvalidatedReasonKind.inputMissing: The following inputs were missing:
D:\dev_test_aps\test_output\web\*\index.html,D:\dev_test_aps\test_output\web\flutter_bootstrap.js}
[   +1 ms] web_static_assets: Starting due to {InvalidatedReasonKind.outputMissing: The following outputs were missing:
D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\flutter.js,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\canvaskit.js,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\canvaskit.js.symbols,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\canvaskit.wasm,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\chromium\canvaskit.js,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\chromium\canvaskit.js.symbols,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\chromium\canvaskit.wasm,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\skwasm.js,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\skwasm.js.symbols,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\skwasm.wasm,D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\canvaskit\skwasm.worker.js}
[ +261 ms] Skipping target: dart2js
[   +1 ms] web_static_assets: Complete
[  +10 ms] web_templated_files: Complete
[   +9 ms] web_release_bundle: Starting due to {}
[ +247 ms] shaderc command: [d:\dev\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --iplr,
--json, --sl=..\build\assets\shaders/ink_sparkle.frag, --spirv=..\build\assets\shaders/ink_sparkle.frag.spirv,
--input=d:\dev\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag,
--include=d:\dev\flutter\packages\flutter\lib\src\material\shaders,
--include=d:\dev\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
[  +11 ms] Running command: d:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
d:\dev\flutter\bin\cache\artifacts\engine\windows-x64\const_finder.dart.snapshot --kernel-file
D:\dev_test_aps\test_output\.dart_tool\flutter_build\9aae491ca62065c2c60b6fa8ba0f5573\app.dill --class-library-uri
package:flutter/src/widgets/icon_data.dart --class-name IconData --annotation-class-name _StaticIconProvider
--annotation-class-library-uri package:flutter/src/widgets/icon_data.dart
[  +71 ms] Could not write file to ..\build\assets\shaders/ink_sparkle.frag

[ +571 ms] Running font-subset: d:\dev\flutter\bin\cache\artifacts\engine\windows-x64\font-subset.exe
..\build\assets\packages/cupertino_icons/assets/CupertinoIcons.ttf
C:\Users\corey\AppData\Local\Pub\Cache\hosted\pub.dev\cupertino_icons-1.0.8\assets\CupertinoIcons.ttf, using codepoints
62629 62419 62415 62318 optional:32
[   +1 ms] Running font-subset: d:\dev\flutter\bin\cache\artifacts\engine\windows-x64\font-subset.exe
..\build\assets\fonts/MaterialIcons-Regular.otf
d:\dev\flutter\bin\cache\artifacts\material_fonts\MaterialIcons-Regular.otf, using codepoints 57415 57490 62832 57706
58332 58727 57496 57694 57695 57657 57882 57504 61453 57634 57498 57926 57704 57491 61061 61060 62834 62833 59283 59282
57499 57500 61069 61068 62842 62841 59291 59290 58011 58012 61575 61576 63348 63349 59797 59798 58372 58370 61930 61927
63708 63705 60157 60154 58771 58189 62328 61752 983402 63526 60555 59975 57502 58814 58813 57846 57862 57686 61764 57402optional:32
[  +14 ms] Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 1172 bytes (99.5% reduction).
Tree-shaking
           can be disabled by providing the --no-tree-shake-icons flag when building your app.
[   +1 ms] Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7760 bytes (99.5%
reduction).
           Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
[        ] Persisting file store
[   +4 ms] Done persisting file store
[   +3 ms] Target web_release_bundle failed: ShaderCompilerException: Shader compilation of
           "d:\dev\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to
           "..\build\assets\shaders/ink_sparkle.frag" failed with exit code 1.
           impellerc stdout:

           impellerc stderr:
           Could not write file to ..\build\assets\shaders/ink_sparkle.frag



           #0      ShaderCompiler.compileShader
           (package:flutter_tools/src/build_system/tools/shader_compiler.dart:190:9)
           <asynchronous suspension>
           #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:164:25)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
           <asynchronous suspension>
           #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:126:3)
           <asynchronous suspension>
           #4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:450:29)
           <asynchronous suspension>
           #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
           <asynchronous suspension>
           #6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
           <asynchronous suspension>
           #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
           <asynchronous suspension>
           #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
           <asynchronous suspension>
           #9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
           <asynchronous suspension>
           #10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
           <asynchronous suspension>
           #11     FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[   +5 ms] Compiling lib\main.dart for the Web... (completed in 1,244ms)
[   +1 ms] "flutter web" took 1,433ms.
[   +3 ms] Error: Failed to compile application for the Web.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:129:7)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[  +55 ms] ensureAnalyticsSent: 54ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[!] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
    • Flutter version 3.22.0 on channel stable at d:\dev\flutter
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at d:\dev\flutter. Consider adding d:\dev\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (8 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\corey\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.105

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by Bestfootballer** [comment]
Hi @cmarques2, I've followed your steps but I didn't receive any errors.

<b>Output of "flutter build web --output=..\build --verbose"</b>
```
[   +3 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.4.1
[        ] executing: sw_vers -buildVersion
[   +7 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23E224
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[   +2 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +35 ms] Skipping pub get: version match.
[  +82 ms] Generating /Users/antonio/Documents/Progetti/test_output/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +62 ms] generated_plugin_registrant.dart not found. Skipping.
[        ] Compiling lib/main.dart for the Web...
[   +2 ms] Initializing file store
[  +14 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Applications/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[        ] Skipping target: gen_localizations
[   +1 ms] invalidated build due to missing files: /Users/antonio/Documents/Progetti/test_output/web/*/index.html, /Users/antonio/Documents/Progetti/test_output/web/flutter_bootstrap.js
[        ] web_templated_files: Starting due to {InvalidatedReasonKind.buildKeyChanged: The target build key changed., InvalidatedReasonKind.inputMissing: The following inputs were missing:
/Users/antonio/Documents/Progetti/test_output/web/*/index.html,/Users/antonio/Documents/Progetti/test_output/web/flutter_bootstrap.js, InvalidatedReasonKind.inputChanged: The following inputs have updated
contents: /Applications/flutter/bin/internal/engine.version}
[   +2 ms] web_static_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Applications/flutter/bin/internal/engine.version}
[  +35 ms] web_static_assets: Complete
[  +25 ms] web_templated_files: Complete
[  +10 ms] web_entrypoint: Complete
[        ] dart2js: Starting due to {}
[   +3 ms] executing: /Applications/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Applications/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/Applications/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=true --native-null-assertions --no-source-maps -o
/Users/antonio/Documents/Progetti/test_output/.dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/app.dill --packages=.dart_tool/package_config.json --cfe-only
/Users/antonio/Documents/Progetti/test_output/.dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/main.dart
[+6018 ms] Compiled 37,578,718 input bytes (29,111,668 characters source) to 25,918,104 kernel bytes in 5.79 seconds using 538.281 MB of memory
                    Dart file .dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/main.dart compiled to dill: .dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/app.dill.
[   +1 ms] executing: /Applications/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Applications/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/Applications/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=true --native-null-assertions --no-source-maps -O4 -o
/Users/antonio/Documents/Progetti/test_output/.dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/main.dart.js
/Users/antonio/Documents/Progetti/test_output/.dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/app.dill
[+7585 ms] /Applications/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:290:11:
                    Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
                    Consider removing this 'noSuchMethod' implementation.
                      dynamic noSuchMethod(Invocation invocation) {
                              ^
                    Compiled 42,896,952 input bytes (8,517,245 characters source) to 1,552,488 characters JavaScript in 7.40 seconds using 617.750 MB of memory
[  +22 ms] dart2js: Complete
[ +354 ms] web_release_bundle: Starting due to {}
[  +76 ms] shaderc command: [/Applications/flutter/bin/cache/artifacts/engine/darwin-x64/impellerc, --sksl, --iplr, --json, --sl=..build/assets/shaders/ink_sparkle.frag,
--spirv=..build/assets/shaders/ink_sparkle.frag.spirv, --input=/Applications/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/Applications/flutter/packages/flutter/lib/src/material/shaders, --include=/Applications/flutter/bin/cache/artifacts/engine/darwin-x64/shader_lib]
[  +10 ms] Running command: /Applications/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Applications/flutter/bin/cache/artifacts/engine/darwin-x64/const_finder.dart.snapshot --kernel-file
/Users/antonio/Documents/Progetti/test_output/.dart_tool/flutter_build/8ef3e3f8fa98e7201dca5d5080bf0168/app.dill --class-library-uri package:flutter/src/widgets/icon_data.dart --class-name IconData
--annotation-class-name _StaticIconProvider --annotation-class-library-uri package:flutter/src/widgets/icon_data.dart
[ +792 ms] Running font-subset: /Applications/flutter/bin/cache/artifacts/engine/darwin-x64/font-subset ..build/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
/Users/antonio/.pub-cache/hosted/pub.dev/cupertino_icons-1.0.8/assets/CupertinoIcons.ttf, using codepoints 62629 62419 62415 62318 optional:32
[        ] Running font-subset: /Applications/flutter/bin/cache/artifacts/engine/darwin-x64/font-subset ..build/assets/fonts/MaterialIcons-Regular.otf
/Applications/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf, using codepoints 57415 57490 62832 57706 58332 58727 57496 57694 57695 57657 57882 57504 61453 57634 57498 57926 57704 57491
61061 61060 62834 62833 59283 59282 57499 57500 61069 61068 62842 62841 59291 59290 58011 58012 61575 61576 63348 63349 59797 59798 58372 58370 61930 61927 63708 63705 60157 60154 58771 58189 62328 61752
983402 63526 60555 59975 57502 58814 58813 57846 57862 57686 61764 57402 optional:32
[  +16 ms] Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7760 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when
building your
           app.
[        ] Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 1172 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your
app.
[   +3 ms] web_release_bundle: Complete
[  +52 ms] web_service_worker: Starting due to {}
[ +167 ms] web_service_worker: Complete
[ +128 ms] Persisting file store
[   +3 ms] Done persisting file store
[   +9 ms] Compiling lib/main.dart for the Web... (completed in 15,3s)
[        ] ✓ Built ..build
[  +23 ms] "flutter web" took 15.574ms.
[  +21 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[ +261 ms] exiting with code 0
```

Have you read your flutter doctor output? It says that <b>dart</b> is resolved to <b>`C:\tools\dart-sdk\bin\dart.exe`</b> ,
while your <b>Flutter</b> installation is resolved to <b>`d:\dev\flutter\bin`</b>.

Try to remove the enviroinment variable that has this value  <b>`C:\tools\dart-sdk\bin\dart.exe`</b>, or update it to this: <b>`d:\dev\flutter\bin`</b>

Making this change, you'll use dart that is inside Flutter folder.

**Comment by cmarques2** [comment]
Oh interesting, I did see that, but we have two sites, an AngularDart site that's stuck in the stone age and a Flutter web app. I need to run both versions on my machine. Is there a way around that?

**Comment by Bestfootballer** [comment]
@cmarques2 you can use FVM (Flutter Version Manager) to manage different versions of Flutter and switch to one of them whenever you need.

**Comment by huycozy** [comment]
@cmarques2 I also can't reproduce this issue. Please try re-setting `dart` env path as @Bestfootballer's suggestion to see if it works for you.
