### ISSUE TITLE
The common frontend is crashing on a slightly modified version of the flutter gallery app.

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#14850]
Crash running a branch of flutter_gallery with small changes to the Flutter package with 
`--preview-dart-2`

Repro steps using an android debug build.
Clone this branch
https://github.com/jacob314/flutter/tree/CRASH_DART_2
```
cd examples/flutter_gallery
flutter run --preview-dart-2
tweak widget_inspector.dart line 745 or probably anywhere in package:flutter and trigger a hot reload.

Crash
```

Build output:
```
Performing hot reload...
compiler message: Unhandled exception:
compiler message: Crash when compiling file:///usr/local/google/home/jacobr/git/flutter/3/flutter/examples/flutter_gallery/lib/main.dart,
compiler message: at character offset null:
compiler message: NoSuchMethodError: The getter 'typeArguments' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: typeArguments
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      _TypeSubstitutor.visitSupertype (package:kernel/type_algebra.dart:441)
compiler message: #2      Substitution.substituteSupertype (package:kernel/type_algebra.dart:309)
compiler message: #3      StrongModeMixinInferrer.generateConstraints (package:front_end/src/fasta/type_inference/type_inferrer.dart:1683)
compiler message: #4      StrongModeMixinInferrer.infer (package:front_end/src/fasta/type_inference/type_inferrer.dart:1727)
compiler message: #5      ClosedWorldClassHierarchy._topologicalSortVisit (package:kernel/class_hierarchy.dart:781)
compiler message: #6      ClosedWorldClassHierarchy._initialize (package:kernel/class_hierarchy.dart:705)
compiler message: #7      new ClassHierarchy (package:kernel/class_hierarchy.dart:38)
compiler message: #8      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:574)
compiler message: #9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:250)
compiler message: <asynchronous suspension>
compiler message: #10     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:158)
compiler message: <asynchronous suspension>
compiler message: #11     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #12     _rootRun (dart:async/zone.dart:1126)
compiler message: #13     _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #14     runZoned (dart:async/zone.dart:1501)
compiler message: #15     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
compiler message: #16     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:57)
compiler message: <asynchronous suspension>
compiler message: #17     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
compiler message: <asynchronous suspension>
```

**Comment by jacob314** [comment]
It appears this issue is fixed by

https://github.com/flutter/flutter/pull/14832 
closing for now.

**Comment by jacob314** [comment]
I spoke too soon.
Known repro steps that still apply on tip of trunk:
Edit widget_inspector.dart line 745 tweaking the const color value slightly.

**Comment by jensjoha** [comment]
I get the same stacktrace for https://github.com/dart-lang/sdk/issues/32313 .

**Comment by jensjoha** [comment]
Update: I am trying to create a standalone example of this specific issue. Once that's done I will create a bug report in the dart repo and port the link here.

**Comment by kmillikin** [comment]
@jacob314 I think this is fixed by https://github.com/dart-lang/sdk/commit/13067387a4d549aafa971dc70a2e408686bac21d.  Let me know when you can verify it.

**Comment by jacob314** [comment]
@a-siva as soon as the new dart-sdk is rolled into flutter engine, I'll try it out with my flutter branch.

**Comment by a-siva** [comment]
A new version of the dart-sdk was rolled into flutter this morning (the roll was at version 1aaebedd7045a44ba92bb1bb27c3a8bc25d74856)
