### ISSUE TITLE
InputDecoration.hintText default text style is not compliant with M3 spec

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#148787]
### Steps to reproduce

- Copy the given test to packages/flutter/test/material/input_decorator_test.dart
- Run it

### Expected results

The text succeeds because the default hint style for M3 should be bodyLarge with the color set to onSurfaceVariant.
These information are available in the M3 Figma Kit.
See this Figma screenshot taken while focusing on the 'Placeholder' text (which corresponds to hint).

![image](https://github.com/flutter/flutter/assets/840911/58d3d5c9-0984-497a-9d47-4724dcd7b2b3)

### Actual results

The test fails

### Code sample

<details open><summary>Code sample</summary>

```dart

        testWidgets('hint style is compliant with M3 spec', (WidgetTester tester) async {
          await tester.pumpWidget(
            buildInputDecorator(
              isEmpty: true,
              decoration: const InputDecoration(
                filled: true,
                hintText: hintText,
              ),
            ),
          );

          // Hint is visible because decorator is empty.
          expect(getHintOpacity(tester), 1.0);

          final ThemeData theme = Theme.of(tester.element(findDecorator()));
          final Color expectedColor = theme.colorScheme.onSurfaceVariant;
          final TextStyle expectedStyle = theme.textTheme.bodyLarge!.copyWith(color: expectedColor);
          expect(getHintStyle(tester), expectedStyle);
        });
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: TextStyle:<TextStyle(debugLabel: ((englishLike bodyLarge 2021).merge((blackMountainView
bodyLarge).apply)).copyWith, inherit: false, color: Color(0xff49454f), family: Roboto, size: 16.0,
weight: 400, letterSpacing: 0.5, baseline: alphabetic, height: 1.5x, leadingDistribution: even,
decoration: Color(0xff1d1b20) TextDecoration.none)>
  Actual: TextStyle:<TextStyle(debugLabel: ((englishLike titleMedium 2021).merge((blackMountainView
titleMedium).apply)).merge(unknown), inherit: false, color: Color(0x99000000), family: Roboto, size:
16.0, weight: 500, letterSpacing: 0.1, baseline: alphabetic, height: 1.5x, leadingDistribution:
even, decoration: Color(0xff1d1b20) TextDecoration.none)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/bruno/Nevercode/flutter/packages/flutter/test/material/input_decorator_test.dart:2840:11)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/bruno/Nevercode/flutter/packages/flutter/test/material/input_decorator_test.dart line 2840
The test description was:
  hint style is compliant with M3 spec
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.22.0-36.0.pre.51, on macOS 14.2.1 23C71
    darwin-arm64, locale fr-FR)
```

</details>

**Comment by loic-sharma** [comment]
Hello @bleroux, I'm reopening this issue as this caused Skia golden changes that might be unexpected. See: https://github.com/flutter/flutter/pull/148944#issuecomment-2143035387
