### ISSUE TITLE
flutter doctor exited unexpectedly

### ISSUE THREAD

**Issue by leagmain** [flutter/flutter#14873]
After I clone the flutter repo, and run 'flutter doctor', it always exited unexpectedly.
below is the flutter.log file content

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: The semaphore timeout period has expired.
, errno = 121, address = storage.googleapis.com, port = 55261

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:534)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:268)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:294)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:265)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:281)
#7      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:317)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:228)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:195)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:274)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#27     main (file:///C:/Users/leon/Application/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (Channel master, v0.1.6-pre.7, on Microsoft Windows [Version 10.0.16299.248], locale en-US)
    • Flutter version 0.1.6-pre.7 at C:\Users\leon\Application\flutter
    • Framework revision c3bbcb6f91 (22 hours ago), 2018-02-24 09:28:58 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\leon\AppData\Local\Android\sdk
    • Android NDK at C:\Users\leon\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by mraleph** [comment]
@leagmain have you tried following these instructions: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?
