### ISSUE TITLE
Exception when enabling performance overlay immediately after service extension added

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#14885]
I'm working on persisting VM service extensions settings across full restarts (https://github.com/Dart-Code/Dart-Code/issues/567). When I get the `ServiceExtensionAdded` notification after a full restart I send over the value we have.

It works for some things (like debug painting) but if I enable the performance overlay and then do a full restart, then when we receive `ServiceExtensionAdded` for `togglePerformanceOverlay` we immediately send a message to enable it, this happens.

Note: In the related case, @devoncarew did say:

> When restoring a value after a restart, the VM won't be ready to accept any service protocol calls until the isolate is sufficiently booted up. In IntelliJ, we wait until we receive the first Flutter.Frame over the wire before we try and restore any values.

I'm not sure whether this is the issue he was describing or not (since if I send it before we get the `ServiceExtensionAdded` notification then it does crash with a more obvious error) but since this looks like Flutter code and not the VM, I figured maybe this was a different issue.

```text
Launching lib\main.dart on XT1562 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk (31.2MB).
I/FlutterActivityDelegate(13515): onResume setting current activity to this
Restarted app in 2,604ms.
I/flutter (13515): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13515): The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(360.0, 592.0),
I/flutter (13515): devicePixelRatio: 3.0, textScaleFactor: 1.0, padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets:
I/flutter (13515): EdgeInsets.zero, alwaysUse24HourFormat: true)):
I/flutter (13515): Multiple widgets used the same GlobalKey.
I/flutter (13515): The key [GlobalObjectKey<NavigatorState> _WidgetsAppState#13254] was used by multiple widgets. The
I/flutter (13515): parents of those widgets were:
I/flutter (13515): - MediaQuery(MediaQueryData(size: Size(360.0, 592.0), devicePixelRatio: 3.0, textScaleFactor: 1.0,
I/flutter (13515):   padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
I/flutter (13515):   true), dirty)
I/flutter (13515): - MediaQuery(MediaQueryData(size: Size(360.0, 592.0), devicePixelRatio: 3.0, textScaleFactor: 1.0,
I/flutter (13515):   padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
I/flutter (13515):   true))
I/flutter (13515): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter (13515): When the exception was thrown, this was the stack:
I/flutter (13515): #0      GlobalKey._debugReserveFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:164:11)
I/flutter (13515): #1      GlobalKey._debugReserveFor (package:flutter/src/widgets/framework.dart:182:6)
I/flutter (13515): #2      Element.updateChild.<anonymous closure> (package:flutter/src/widgets/framework.dart:2664:13)
I/flutter (13515): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2667:6)
I/flutter (13515): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (13515): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (13515): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (13515): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (13515): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (13515): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (13515): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (13515): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (13515): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (13515): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (13515): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (13515): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (13515): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (13515): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (13515): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4716:32)
I/flutter (13515): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (13515): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (13515): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (13515): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (13515): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #44     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (13515): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (13515): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (13515): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (13515): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #76     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #80     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (13515): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #84     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (13515): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (13515): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (13515): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (13515): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (13515): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (13515): #96     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (13515): #97     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (13515): #98     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13515): #99     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13515): #100    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13515): #101    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (13515): #103    _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
I/flutter (13515): #104    _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
I/flutter (13515): #105    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter (13515): (elided one frame from package dart:async-patch)
I/flutter (13515): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by devoncarew** [comment]
I think this is the same issue. We'll get the `ServiceExtensionAdded` event, but we should wait to restore any previous values for those toggles until we receive the first `Flutter.Frame` event.

**Comment by DanTup** [comment]
Ok, feel free to close this if you don't think it's valid then. I've got things working with FirstFrame so as long as that's reliable I'm sorted 👍

**Comment by Hixie** [comment]
I don't understand why we'd get that precise assert, though. That seems like an actual issue.

**Comment by Hixie** [comment]
I don't see any way that this key can end up being used twice...

**Comment by Hixie** [comment]
I'm going to close this. The stack suggests that we used to have the key on the MediaQuery, we don't anymore (if we ever did). If you still see this please please please do file a new bug with the new stack because this is not something that should be happening even if you send the message too early.
