### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Equatable')  on debug web 3.22.1

### ISSUE THREAD

**Issue by flrnsbt** [flutter/flutter#149078]
### Steps to reproduce

flutter run -d chrome --debug

### Expected results

App to launches.

### Actual results

App never starts and get this error in the browser console:
Uncaught TypeError: Cannot read properties of undefined (reading 'Equatable')
    at load__packages__******************************* (

This was working perfectly before the last flutter upgrade, and it is still working in release mode

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter run -d chrome --debug
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
miner_events.dart.lib.js:40 Uncaught TypeError: Cannot read properties of undefined (reading 'Equatable')
    at load__packages__*********************************** (miner_events.dart.lib.js:40:64)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flrnsbt@flrnsbt flutter % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-TH)
    • Flutter version 3.22.1 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/flrnsbt/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.77

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by flrnsbt** [comment]
This only happens in debug mode and on chrome

**Comment by flrnsbt** [comment]
Equatable is not the only throwing this error, this is randomly happening. Refreshing the page generally solve this issue.

**Comment by darshankawar** [comment]
@flrnsbt Looks like it is coming from third party implementation. Also, we need details as requested https://github.com/flutter/flutter/issues/149076#issuecomment-2132926576
