### ISSUE TITLE
reorderable_list drag item to  other target size is larger than scrollable size throws exception

### ISSUE THREAD

**Issue by hello-coder-xu** [flutter/flutter#149029]
### Steps to reproduce

1，Scroll to the last one
2，Press and hold item2, drag it to the middle and upper position of item1
3，Throw an exception

### Expected results

no exception

### Actual results

throws exception 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class RecorderableListDragExceptionDemo extends StatefulWidget {
  const RecorderableListDragExceptionDemo({
    super.key,
    this.asxis = Axis.horizontal,
    this.isReorderableListViewType = true,
  });

  final Axis asxis;
  final bool isReorderableListViewType;

  @override
  State<RecorderableListDragExceptionDemo> createState() =>
      _RecorderableListDragExceptionDemoState();
}

class _RecorderableListDragExceptionDemoState
    extends State<RecorderableListDragExceptionDemo> {
  List<Map<String, double>> itemList = <Map<String, double>>[];

  double screenWidthOrHeight = 0;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      updateData();
    });
  }

  void updateData() {
    screenWidthOrHeight = MediaQuery.of(context).size.height;
    setState(() {
      itemList = <Map<String, double>>[
        <String, double>{'item0': 150},
        <String, double>{'item1': screenWidthOrHeight + 100},
        <String, double>{'item2': 300},
      ];
    });
  }

  void handleReorder(int fromIndex, int toIndex) {
    setState(() {
      if (toIndex > fromIndex) {
        toIndex -= 1;
      }
      itemList.insert(toIndex, itemList.removeAt(fromIndex));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Scaffold(
          body: ReorderableListView(
            onReorder: handleReorder,
            children: itemList.map((Map<String, double> element) {
              return Container(
                key: Key(element.keys.first),
                height: element.values.first,
                color: Colors.primaries[
                    itemList.indexOf(element) % Colors.primaries.length],
                alignment: Alignment.center,
                child: Text(element.keys.first),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/19924225/6abc1ad3-3e2d-4bf0-958a-762e054a055f)

</details>

### Logs

<details open><summary>Logs</summary>

```console
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      SliverReorderableListState._itemOffsetAt (package:flutter/src/widgets/reorderable_list.dart:946:25)
reorderable_list.dart:946
#1      SliverReorderableListState._dragEnd.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:813:32)
reorderable_list.dart:813
#2      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
framework.dart:1203
#3      SliverReorderableListState._dragEnd (package:flutter/src/widgets/reorderable_list.dart:794:5)
reorderable_list.dart:794
#4      _DragInfo.end (package:flutter/src/widgets/reorderable_list.dart:1405:12)
reorderable_list.dart:1405
#5      MultiDragPointerState._up (package:flutter/src/gestures/multidrag.dart:164:14)
multidrag.dart:164
#6      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:271:13)
multidrag.dart:271
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
pointer_router.dart:98
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
pointer_router.dart:143
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
pointer_router.dart:141
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
pointer_router.dart:127
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
binding.dart:495
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
binding.dart:475
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
binding.dart:450
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
binding.dart:420
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
binding.dart:383
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
binding.dart:330
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
binding.dart:299
#19     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
platform_dispatcher.dart:442
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
hooks.dart:262

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 12.5.1 21G83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

and


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.22.0-45.0.pre, on macOS 12.5.1 21G83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I see there's a similar issue at https://github.com/flutter/flutter/issues/136331 which has the same error and in a scenario when ReorderableListView has `shrinkWrap` to true. 

Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by hello-coder-xu** [comment]
I don't think they are the same issue

```console
globalRect.size.height >= _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing
```

compared

```console
════════ Exception caught by gesture library ═══════════════════════════════════
The following _TypeError was thrown while routing a pointer event:
Null check operator used on a null value
```


I already know about native, I will submit a PR to fix it,i need some time
