### ISSUE TITLE
[add2app] Android cannot register flutter plugin

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [flutter/flutter#149104]
### Steps to reproduce

1. create flutter module via document [https://docs.flutter.dev/add-to-app/android/project-setup?tab=without-android-studio](url)
2. Import some plugin that using native code  (path_provider , google_mlkit_face_detection , google_fonts , etc ...)
3. build aar via cmd `flutter build aar --no-tree-shake-icons `
3. create new android project with Groovy DSL(build.gradle)
4. follow setup via document above and run

### Expected results

feature using native code in flutter module should work normal

### Actual results

feature work normal

### Code sample

<details open><summary>Android code</summary>

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val button = findViewById<Button>(R.id.button)
        button.setOnClickListener {
            onStartEkyc(it)
        }
    }
    private fun onStartEkyc(view: View) {
        val EngineID = "1"
        val flutterEngine = FlutterEngine(this)
        flutterEngine.dartExecutor.executeDartEntrypoint(DartExecutor.DartEntrypoint.createDefault())
        FlutterEngineCache.getInstance().put(EngineID, flutterEngine)

        val channel = MethodChannel(flutterEngine.dartExecutor, "com.ekyC/mainChannel")

        var json = readJSONFromAsset()
        val config = JSONObject(json).toMap()
        channel.invokeMethod("init", config);

        startActivity(FlutterActivity.withCachedEngine(EngineID).build(this));
        val responseChannel =
            MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "com.ekyC/mainChannel")
        responseChannel.setMethodCallHandler { call, result ->
            when (call.method) {
                "exceptionCallBack" -> Log.d("exceptionCallBack", call.arguments.toString());
            }
        }
    }
    fun readJSONFromAsset(): String? {
        var json: String? = null
        try {
            val inputStream: InputStream = application.assets.open("example.json")
            json = inputStream.bufferedReader().use { it.readText() }
        } catch (ex: Exception) {
            ex.printStackTrace()
            return null
        }
        return json
    }

    fun JSONObject.toMap(): Map<String, *> = keys().asSequence().associateWith {
        when (val value = this[it]) {
            is JSONArray -> {
                val map = (0 until value.length()).associate { Pair(it.toString(), value[it]) }
                JSONObject(map).toMap().values.toList()
            }

            is JSONObject -> value.toMap()
            JSONObject.NULL -> null
            else -> value
        }
    }
}
</details>
```
In flutter module . implement some feature using imported plugin

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
<details close><summary>Error logs</summary>
2024-05-26 18:14:34.072 31475-32201 flutter                 com.example.example_android          I  MissingPluginException(No implementation found for method vision#startFaceDetector on channel google_mlkit_face_detector)
2024-05-26 18:14:34.073 31475-32201 flutter                 com.example.example_android          I  #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:520:35)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      FaceDetector.processImage (package:google_mlkit_face_detection/src/face_detector.dart:23:20)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      LivenessProvider._processImage (package:ekyc_module_v2/core/providers/liveness_provider.dart:405:19)
                                                                                                    <asynchronous suspension>
                                                                                                    #4      LivenessProvider.processCameraImage (package:ekyc_module_v2/core/providers/liveness_provider.dart:189:5)
                                                                                                    <asynchronous suspension>
2024-05-26 18:14:34.077 31475-31475 exceptionCallBack       com.example.example_android          D  MissingPluginException(No implementation found for method vision#startFaceDetector on channel google_mlkit_face_detector)
2024-05-26 18:14:49.256 31475-31487 example_androi          com.example.example_android          I  Background concurrent copying GC freed 1113(191KB) AllocSpace objects, 12(11MB) LOS objects, 55% free, 4MB/10MB, paused 512us total 112.304ms
2024-05-26 18:14:49.530 31475-31487 example_androi          com.example.example_android          I  Background concurrent copying GC freed 1079(209KB) AllocSpace objects, 5(4MB) LOS objects, 49% free, 7MB/14MB, paused 483us total 105.404ms
2024-05-26 18:14:51.771 31475-31487 example_androi          com.example.example_android          I  Background concurrent copying GC freed 1105(207KB) AllocSpace objects, 9(9MB) LOS objects, 49% free, 6MB/12MB, paused 2.138ms total 105.493ms
2024-05-26 18:14:55.675 31475-31487 example_androi          com.example.example_android          I  Background concurrent copying GC freed 994(206KB) AllocSpace objects, 8(7MB) LOS objects, 49% free, 7MB/15MB, paused 791us total 112.673ms
2024-05-26 18:14:59.280 31475-32201 flutter                 com.example.example_android          I  Error: google_fonts was unable to load font Roboto-Regular because the following exception occurred:
                                                                                                    Exception: Failed to load font with url https://fonts.gstatic.com/s/a/d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf: ClientException with SocketException: Failed host lookup: 'fonts.gstatic.com' (OS Error: No address associated with hostname, errno = 7), uri=https://fonts.gstatic.com/s/a/d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf
2024-05-26 18:14:59.281 31475-32201 flutter                 com.example.example_android          I  
                                                                                                    See https://docs.flutter.dev/development/data-and-backend/networking#platform-notes.
2024-05-26 18:14:59.281 31475-32201 flutter                 com.example.example_android          I  If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.
2024-05-26 18:14:59.281 31475-32201 flutter                 com.example.example_android          I  Exception: Failed to load font with url https://fonts.gstatic.com/s/a/d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf: ClientException with SocketException: Failed host lookup: 'fonts.gstatic.com' (OS Error: No address associated with hostname, errno = 7), uri=https://fonts.gstatic.com/s/a/d1d7c5f4500eeb1a09e051781906c3642015a3f6c9b69046b905c8bf34c6ad60.ttf
2024-05-26 18:14:59.281 31475-32201 flutter                 com.example.example_android          I  #0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:261:5)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      loadFontIfNecessary (package:google_fonts/src/google_fonts_base.dart:178:11)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      googleFontsTextStyle.<anonymous closure> (package:google_fonts/src/google_fonts_base.dart:115:22)
                                                                                                    <asynchronous suspension>
</detail>

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale vi)
    • Flutter version 3.22.1 on channel stable at /Users/caogiahieu/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/caogiahieu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/caogiahieu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/caogiahieu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Users/caogiahieu/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (1 available)
    • SM G955F (mobile) • 9889db465748464752 • android-arm64 • Android 9 (API 28)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by CaoGiaHieu-dev** [comment]
Yes . It still have error

**Comment by CaoGiaHieu-dev** [comment]
@darshankawar  here the log when i using path provider
<details open><summary>Logs</summary>

```
2024-05-28 08:39:18.620 12702-13593 flutter                 com.example.example_android          I  PlatformException(channel-error, Unable to establish connection on channel., null, null)
2024-05-28 08:39:18.620 12702-13593 flutter                 com.example.example_android          I  #0      PathProviderApi.getApplicationSupportPath (package:path_provider_android/messages.g.dart:65:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      getApplicationSupportDirectory (package:path_provider/path_provider.dart:78:24)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      _localPath (package:google_fonts/src/file_io_desktop_and_mobile.dart:39:21)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      _localFile (package:google_fonts/src/file_io_desktop_and_mobile.dart:44:16)
                                                                                                    <asynchronous suspension>
                                                                                                    #4      saveFontToDeviceFileSystem (package:google_fonts/src/file_io_desktop_and_mobile.dart:15:16)
                                                                                                    <asynchronous suspension>
```

</details>

**Comment by darshankawar** [comment]
Thanks for the update. Is it only occuring while following the instructions that are specific without Android Studio only ?
If you follow https://docs.flutter.dev/add-to-app/android/project-setup?tab=with-android-studio, can you check if you still get same error ?

**Comment by CaoGiaHieu-dev** [comment]
i did that aslo a still . get same error

**Comment by CaoGiaHieu-dev** [comment]
i resolved it . close now .
 it because the flutter package i use set minifyEnabled = true so when import it cannot found plugin
