### ISSUE TITLE
[web] JS formatter breaks the templates in the new load API.

### ISSUE THREAD

**Issue by prologikus** [flutter/flutter#149103]
### Steps to reproduce

1.Create a demo Flutter app using the latest bootstrap, using the following flutter_bootstrap.js
`{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
  config: {
    renderer: 'canvaskit',
  },
});`

2.Auto format the code using VS-Code, Javascript, or any other js formatter
3.Observe the spacing added
`{ { flutter_js } }
{ { flutter_build_config } }`
3.Attempt to flutter run
4.Observe the white screen

### Expected results

The template should be replaced even with spacing added from formatters.
There should be a warning in the documentation at least, which tells that the template must not be formatted somehow.

### Actual results

The app is blank because the templates are not replaced.

### Code sample

(Included above)

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

This reproduces in the latest master, and probably has always reproduced since we introduced the new load API.

**Comment by huycozy** [comment]
Hi @prologikus 
Please provide the output of `flutter doctor -v` which will include the exact version of master channel. 

>Create a demo Flutter app using the latest bootstrap, using the following flutter_bootstrap.js

Do you mean `/build/web/flutter_bootstrap.js`? If it is, I checked this issue on `Channel master, 3.23.0-8.0.pre.8` but couldn't reproduce it.

**Comment by prologikus** [comment]
> Hi @prologikus Please provide the output of `flutter doctor -v` which will include the exact version of master channel.
> 
> > Create a demo Flutter app using the latest bootstrap, using the following flutter_bootstrap.js
> 
> Do you mean `/build/web/flutter_bootstrap.js`? If it is, I checked this issue on `Channel master, 3.23.0-8.0.pre.8` but couldn't reproduce it.

I was on 3.23.0-8.0.pre.8 too

Did you observe the spacing added into the template ? (step 3 in bug report)

**Comment by huycozy** [comment]
Yes, if I format the code, space will be added as 3rd step above. Can you share a demo of the issue?

**Comment by kencana16** [comment]
when there is space added. generated build/webflutter_bootstrap.js is look same as web/flutter_bootstrap.js 

```
{ { flutter_js } }
{ { flutter_build_config } }

_flutter.loader.load();
```

**Comment by Mr-Pepe** [comment]
I can reproduce this on Flutter 3.22.2. The VS Code formatter adds spaces which seems to break the templating.

<details><summary>flutter doctor -v</summary>
<p>

[✓] Flutter (Channel stable, 3.22.2, on Arch Linux 6.9.1-arch1-2, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/felipe/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (7 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/felipe/Android/Sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/felipe/Applications/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/felipe/Applications/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.9.1-arch1-2
    • Chrome (web)    • chrome • web-javascript • Chromium 125.0.6422.112 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</p>
</details>

**Comment by huycozy** [comment]
If I trigger `flutter run` as @prologikus mentioned, the issue will not occur. 

But if I host the built web locally (such as `python3 -m http.server 8000`), I can see the white screen. Checking the console window on browser, I see this error:

```
ReferenceError: flutter_js is not defined
    at flutter_bootstrap.js:1:5
```

@prologikus @Mr-Pepe Can you confirm these steps as I pointed out?

**Comment by Mr-Pepe** [comment]
1. Run `flutter create bug`
2. Run `cd bug`
3. Copy 
    ```
    {{flutter_js}}
    {{flutter_build_config}}

    _flutter.loader.load();
    ```
    into `web/flutter_bootstrap.js`.
4. Auto-format the file
5. Run `flutter run -d chrome`
    - Chrome opens
    - The screen stays white
    - Console logs:
      ```
      flutter_bootstrap.js:1 Uncaught 
      ReferenceError: flutter_js is not defined
      at flutter_bootstrap.js:1:5
      ```
6. Run `flutter build web`
7. Run `python -m http.server -d build/web/`
8. Open `localhost:8000` in Chrome
     - The screen stays white
     - Console logs:
       ```
       flutter_bootstrap.js:1 Uncaught 
       ReferenceError: flutter_js is not defined
       at flutter_bootstrap.js:1:5
       ```

<details><summary>flutter doctor -v</summary>
<p>

[✓] Flutter (Channel stable, 3.22.2, on Arch Linux 6.9.3-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/felipe/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (7 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/felipe/Android/Sdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/felipe/Applications/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/felipe/Applications/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.9.3-arch1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 126.0.6478.55 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</p>
</details>

**Comment by huycozy** [comment]
Thank @Mr-Pepe. I also can reproduce this by following your detailed steps.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (31 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.212, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.212 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b6d667701 (4 hours ago), 2024-06-12 19:34:52 -0400
    • Engine revision c7fcbfce60
    • Dart version 3.5.0 (build 3.5.0-250.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by kevmoo** [comment]
Interesting. The problem: this file is a template file, even though the extension is `.js`.

Thoughts @eyebrowsoffire ?

**Comment by yunweneric** [comment]
In vscode you could just prevent the editor from formatting the file when you save it. 

in your settings.json file edit this line
->"editor.formatOnSave": true,

**Comment by matt3o** [comment]
Ran into the same issue. 
Also note that https://github.com/flutter/flutter/issues/149985 is related, there are more people running into this
