### ISSUE TITLE
iOS `flutter build ipa` Unhandled exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by marcucio** [flutter/flutter#149187]
### Steps to reproduce

Run: flutter build ipa
Result: Unhandled exception: Null check operator used on a null value

### Actual results

```
    Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks (file:///Users/mike/Development/flutter/packages/flutter_tools/bin/xcode_backend.dart:235:68)
    #1      Context.run (file:///Users/mike/Development/flutter/packages/flutter_tools/bin/xcode_backend.dart:59:9)
    #2      main (file:///Users/mike/Development/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
    Command PhaseScriptExecution failed with a nonzero exit code
```

### Logs

<details open>
<summary>Logs</summary>

[logs](https://pastebin.com/KNJBHSuf)

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.1 on channel stable at /Users/mike/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (6 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mike/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)            
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.112
    ! Device R83WC04H5MW is not authorized.
      You might need to check your device for an authorization dialog.

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by marcucio** [comment]
looks like the line that is crashing is:

flutter_tools/bin/xcode_backend.dart:235:68

```
final String flutterBuildDir = environment['FLUTTER_BUILD_DIR']!;
```

**Comment by marcucio** [comment]
looks like I'm running into this issue, but every time I build from the command line it overwrites the project.pbxproj

https://github.com/flutter/flutter/issues/140845

**Comment by VasilisPH** [comment]
A work-around it to edit and save the line like this:

final String flutterBuildDir = environment['FLUTTER_BUILD_DIR'] ?? 'build';

**Comment by darshankawar** [comment]
I think it is better to reopen the original issue and keep following in it for further updates, as per https://github.com/flutter/flutter/issues/140845#issuecomment-1930815401, it is still actionable and need to be fixed.

@marcucio I'll close this as duplicate. Please follow-up in the linked issue.

**Comment by marcucio** [comment]
Can you unlock https://github.com/flutter/flutter/issues/140845 I get the message "This conversation has been locked as resolved and limited to collaborators."

**Comment by darshankawar** [comment]
done
