### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "dartaotruntime.exe" in the search path. Command: dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by hlooi** [flutter/flutter#149163]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=dud6dibqib498d8p --start-paused --flavor=dev --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Step to Reproduce
1. When the flutter app was run from Android Studio, 'dartaotruntime.exe' was detected as  security risk by 'Symantec Endpoint Protection' with message below, thus  'dartaotruntime.exe' became not accessible. The problem happended when later versions of Flutter SDK was used (such as 3.22.1 and 3.19.6). There was no such issue with the earlier Flutter SDK verson such as 3.19.5.
------------------------------------------
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Unproven.Insight
Location: Deleted or access blocked
Action taken: Delete succeeded
------------------------------------------

## Logs
ProcessException: Failed to find "dartaotruntime.exe" in the search path. Command: dartaotruntime.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:874:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:734:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:420:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:394:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:780:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```

**Comment by darshankawar** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/143391
