### ISSUE TITLE
List/Detail template crashes on horizontal orientation of foldable android emulators 

### ISSUE THREAD

**Issue by xxfast** [flutter/flutter#149115]
### Steps to reproduce

1. Create `New Flutter Project` > `Skeleton Application (A List View / Detail View)`
2. Open Android Studio (Stable) and create an experimental resizable emulator 
3. Build apk and wait for it to launch on the emulator 
4. Once open, rotate the device left/right to horizontal orientation
5. Crash!

ADB log
```
    Process: com.example.list_detail, PID: 5225
    java.lang.IllegalArgumentException: Bounding rectangle must start at the top or left window edge for folding features
    	at androidx.window.extensions.layout.FoldingFeature.validateFeatureBounds(FoldingFeature.java:128)
    	at androidx.window.extensions.layout.FoldingFeature.<init>(FoldingFeature.java:95)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.getDisplayFeatures(WindowLayoutComponentImpl.java:341)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.getDisplayFeatures(WindowLayoutComponentImpl.java:316)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.getWindowLayoutInfo(WindowLayoutComponentImpl.java:265)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.onDisplayFeaturesChanged(WindowLayoutComponentImpl.java:250)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.$r8$lambda$CcdqSJgN0v7j8yjFplaR5_gC_ag(Unknown Source:0)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl$$ExternalSyntheticLambda0.accept(Unknown Source:4)
    	at androidx.window.common.DeviceStateManagerFoldingFeatureProducer.runCallbackWhenValidState(DeviceStateManagerFoldingFeatureProducer.java:148)
    	at androidx.window.common.DeviceStateManagerFoldingFeatureProducer.lambda$getData$0(DeviceStateManagerFoldingFeatureProducer.java:200)
    	at androidx.window.common.DeviceStateManagerFoldingFeatureProducer.$r8$lambda$aShjSiJsnArI0ZW6HG-0QPWddJk(Unknown Source:0)
    	at androidx.window.common.DeviceStateManagerFoldingFeatureProducer$$ExternalSyntheticLambda2.accept(Unknown Source:6)
    	at androidx.window.common.RawFoldingFeatureProducer.getData(RawFoldingFeatureProducer.java:71)
    	at androidx.window.common.DeviceStateManagerFoldingFeatureProducer.getData(DeviceStateManagerFoldingFeatureProducer.java:196)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.onDisplayFeaturesChangedIfListening(WindowLayoutComponentImpl.java:397)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl.-$$Nest$monDisplayFeaturesChangedIfListening(Unknown Source:0)
    	at androidx.window.extensions.layout.WindowLayoutComponentImpl$NotifyOnConfigurationChanged.onActivityConfigurationChanged(WindowLayoutComponentImpl.java:415)
    	at android.app.Application.dispatchActivityConfigurationChanged(Application.java:576)
    	at android.app.Activity.dispatchActivityConfigurationChanged(Activity.java:1631)
    	at android.app.Activity.onConfigurationChanged(Activity.java:3180)
    	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6096)
    	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6021)
    	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6366)
    	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6304)
    	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:55)
    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at android.os.Looper.loopOnce(Looper.java:205)
    	at android.os.Looper.loop(Looper.java:294)
    	at android.app.ActivityThread.main(ActivityThread.java:8177)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Expected results

App shouldn't crash 

### Actual results

App crashes 

### Code sample

<details open><summary>Code sample</summary>

This is the skeleton app created by the VSCode flutter plugin 

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/13775137/d4af1820-bd4b-4f0a-821c-a7beb8862116

</details>

### Logs

<details open><summary>Logs</summary>
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.2.1 23C71 darwin-arm64, locale en-AU)
    • Flutter version 3.22.1 on channel stable at /Users/TFNX46/Developer/FLUTTER/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/TFNX46/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Jellyfish.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.17-11446219)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio Iguana.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/TFNX46/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 (mobile)              • 56499F74-BD5D-40FC-9FD5-92D23D1E38FD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.78

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by xxfast** [comment]
Whoops - this issue might be the same as the one [here](https://github.com/flutter/flutter/issues/114868) from two years ago. 

Feel free to close this issue if this is a duplicate

**Comment by huycozy** [comment]
Closing this as a duplicate https://github.com/flutter/flutter/issues/114868. Furthermore, it could be an Android native (androidx) issue: https://issuetracker.google.com/issues/262411062?pli=1
