### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: O sistema não pode encontrar o arquivo especificado., errno = 2

### ISSUE THREAD

**Issue by CabeloSG** [flutter/flutter#149146]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: O sistema não pode encontrar o arquivo especificado.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:266:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:265:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:673:35)
#9      VersionCheckStamp.store (package:flutter_tools/src/version.dart:798:30)
#10     FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/src/version.dart:338:31)
<asynchronous suspension>
#11     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:285:47)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:11)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/s

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/76479
