### ISSUE TITLE
Go Router test with StatefulShellRoute mock throws type error: The following _TypeError was thrown building KeyedSubtree-[GlobalKey#3ccf0]: type 'Null' is not a subtype of type 'StatefulElement'

### ISSUE THREAD

**Issue by JakeHadley** [flutter/flutter#149139]
### Steps to reproduce

Create a test mocking the StatefulNavigationShell and go_router
Provide the mocked navigation shell to the real page with a parent `InheritedGoRouter`.
Observe the error

For reference and confirmation that the setup with the mocks is functioning properly, this test is passing:
```dart
testWidgets('Displays CircularProgressIndicator when not logged in',
        (tester) async {
      whenListen(
        loginBloc,
        Stream.fromIterable([LoginLoggedOut()]),
        initialState: LoginLoggedOut(),
      );

      await tester.pumpWidget(
        MaterialApp(
          home: MockGoRouterProvider(
            goRouter: mockGoRouter,
            child: BlocProvider<LoginBloc>(
              create: (context) => loginBloc,
              child: MainPage(
                navigationShell: navigationShell,
              ),
            ),
          ),
        ),
      );

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });
```
But as soon as I try to test the rendering of the navigation shell, the error gets thrown.

### Expected results

I would expect the test to pass

### Actual results

I'm getting an error saying: 
```
The following _TypeError was thrown building KeyedSubtree-[GlobalKey#3ccf0]:
type 'Null' is not a subtype of type 'StatefulElement'
```

### Code sample

<details open><summary>Code sample</summary>

```dart
//////// GoRouter //////////

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:unf_baseball/app/models/models.dart';
import 'package:unf_baseball/app/router_utils.dart';
import 'package:unf_baseball/events/events.dart';
import 'package:unf_baseball/login/bloc/login_bloc.dart';
import 'package:unf_baseball/login/view/login_page.dart';
import 'package:unf_baseball/main/view/main_page.dart';
import 'package:unf_baseball/modify_post/view/modify_post_page.dart';
import 'package:unf_baseball/network/view/network_page.dart';
import 'package:unf_baseball/onboarding/view/onboarding_page.dart';
import 'package:unf_baseball/post_detail/view/post_detail_page.dart';
import 'package:unf_baseball/posts/view/posts_page.dart';
import 'package:unf_baseball/profile/profile.dart';
import 'package:unf_baseball/resources/view/resources_page.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _postsNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'posts');
final GlobalKey<NavigatorState> _eventsNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'events');
final GlobalKey<NavigatorState> _resourcesNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'resources');
final GlobalKey<NavigatorState> _networkNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'network');

abstract class AppRouter {
  static final goRouter = GoRouter(
    // debugLogDiagnostics: true,
    navigatorKey: _rootNavigatorKey,
    initialLocation: Pages.posts.path,
    redirect: (context, state) {
      final loginState = context.read<LoginBloc>().state;
      if (loginState is LoginLoggedOut) {
        return Pages.login.path;
      }
      return null;
    },
    routes: [
      GoRoute(
        path: Pages.login.path,
        builder: (context, state) => const LoginPage(),
      ),
      GoRoute(
        path: Pages.onboarding.path,
        builder: (context, state) => const OnboardingPage(),
      ),
      GoRoute(
        path: Pages.profile.path,
        builder: (context, state) => const ProfilePage(),
        routes: [
          GoRoute(
            path: Pages.profileInfo.path,
            builder: (context, state) => const ProfileInfoPage(),
          ),
        ],
      ),
      StatefulShellRoute.indexedStack(
        builder: (context, state, navigationShell) {
          return MainPage(navigationShell: navigationShell);
        },
        branches: [
          StatefulShellBranch(
            navigatorKey: _postsNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.posts.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: PostsPage(),
                ),
                routes: [
                  GoRoute(
                    path: Pages.modifyPost.path,
                    builder: (context, state) {
                      final params = state.extra! as ModifyPostPageParams;

                      return ModifyPostPage(
                        isEditing: params.isEditing,
                        post: params.post,
                      );
                    },
                  ),
                  GoRoute(
                    path: Pages.postDetail.path,
                    builder: (context, state) => PostDetailPage(
                      postId: state.uri.queryParameters['postId']!,
                    ),
                  ),
                ],
              ),
            ],
          ),
          StatefulShellBranch(
            navigatorKey: _eventsNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.events.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: EventsPage(),
                ),
                routes: [
                  GoRoute(
                    path: Pages.modifyEvent.path,
                    builder: (context, state) {
                      final params = state.extra! as ModifyEventPageParams;
                      return ModifyEventPage(isEditing: params.isEditing);
                    },
                  ),
                  GoRoute(
                    path: Pages.eventDetail.path,
                    builder: (context, state) => const EventDetailPage(),
                  ),
                ],
              ),
            ],
          ),
          StatefulShellBranch(
            navigatorKey: _resourcesNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.resources.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: ResourcesPage(),
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            navigatorKey: _networkNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.network.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: NetworkPage(),
                ),
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

//////// MockGoRouterProvider //////////

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:mocktail/mocktail.dart';

class MockGoRouter extends Mock implements GoRouter {}

class MockGoRouterProvider extends StatelessWidget {
  const MockGoRouterProvider({
    required this.goRouter,
    required this.child,
    super.key,
  });

  final MockGoRouter goRouter;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return InheritedGoRouter(
      goRouter: goRouter,
      child: child,
    );
  }
}


//////// MainPageTest //////////
import 'dart:async';

import 'package:bloc_test/bloc_test.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:mocktail/mocktail.dart';
import 'package:unf_baseball/login/bloc/login_bloc.dart';
import 'package:unf_baseball/main/bloc/main_bloc.dart';
import 'package:unf_baseball/main/view/main_page.dart';
import 'package:unf_baseball/models/user.dart';
import 'package:unf_baseball/services/database_service.dart';
import '../../test_helpers/test_helpers.dart';

class MockLoginBloc extends MockBloc<LoginEvent, LoginState>
    implements LoginBloc {}

class MockMainBloc extends MockBloc<MainEvent, MainState> implements MainBloc {}

class MockDatabaseService extends Mock implements DatabaseService {}

class MockStatefulNavigationShell extends Mock
    implements StatefulNavigationShell {
  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return '';
  }
}

void main() {
  group('MainPage', () {
    late LoginBloc loginBloc;
    late MainBloc mainBloc;
    late DatabaseService databaseService;
    late MockGoRouter mockGoRouter;
    late StatefulNavigationShell navigationShell;
    late StreamController<User> userStreamController;

    setUp(() {
      loginBloc = MockLoginBloc();
      mainBloc = MockMainBloc();
      databaseService = MockDatabaseService();
      mockGoRouter = MockGoRouter();
      navigationShell = MockStatefulNavigationShell();

      userStreamController = StreamController<User>();
      when(() => databaseService.getUserStream(any()))
          .thenAnswer((_) => userStreamController.stream);
    });

    testWidgets('renders with children', (tester) async {
      final dummyUser = User(uid: 'test_uid', displayName: 'test_name');
      whenListen(
        loginBloc,
        Stream.fromIterable([LoginLoggedIn(dummyUser)]),
        initialState: LoginLoggedIn(dummyUser),
      );

      whenListen(
        mainBloc,
        Stream.fromIterable([MainUserLoaded(user: dummyUser)]),
        initialState: MainUserLoaded(user: dummyUser),
      );

      when(() => navigationShell.currentIndex).thenReturn(0);

      await tester.pumpWidget(
        MaterialApp(
          home: MockGoRouterProvider(
            goRouter: mockGoRouter,
            child: RepositoryProvider(
              create: (context) => databaseService,
              child: MultiBlocProvider(
                providers: [
                  BlocProvider<LoginBloc>(
                    create: (context) => loginBloc,
                  ),
                  BlocProvider<MainBloc>(
                    create: (context) => mainBloc,
                  ),
                ],
                child: MainPage(
                  navigationShell: navigationShell,
                ),
              ),
            ),
          ),
        ),
      );

      await tester.pumpAndSettle();

      expect(find.byType(MainPage), findsOneWidget);
    });
  });
}


//////// MainPage //////////
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:unf_baseball/app/router_utils.dart';
import 'package:unf_baseball/login/bloc/login_bloc.dart';
import 'package:unf_baseball/main/bloc/main_bloc.dart';
import 'package:unf_baseball/services/database_service.dart';

class MainPage extends StatelessWidget {
  const MainPage({
    required this.navigationShell,
    super.key,
  });

  final StatefulNavigationShell navigationShell;

  static final List<Pages> _pages = [
    Pages.posts,
    Pages.events,
    Pages.resources,
    Pages.network,
  ];

  void _goBranch(int index) {
    navigationShell.goBranch(
      index,
      initialLocation: index == navigationShell.currentIndex,
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<LoginBloc, LoginState>(
      builder: (context, state) {
        if (state is! LoginLoggedIn) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        }

        final uid = state.user.uid;

        return MultiBlocProvider(
          providers: [
            BlocProvider<MainBloc>(
              create: (context) {
                final databaseService =
                    RepositoryProvider.of<DatabaseService>(context);

                return MainBloc(
                  databaseService: databaseService,
                  uid: uid,
                );
              },
              lazy: false,
            ),
          ],
          child: Scaffold(
            body: navigationShell,
            bottomNavigationBar: NavigationBar(
              selectedIndex: navigationShell.currentIndex,
              destinations: _pages
                  .map(
                    (page) => NavigationDestination(
                      key: ValueKey('bottom_nav_${page.name}'),
                      label: page.label,
                      icon: page.icon!,
                    ),
                  )
                  .toList(),
              onDestinationSelected: _goBranch,
            ),
          ),
        );
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The following _TypeError was thrown building KeyedSubtree-[GlobalKey#3ccf0]:
type 'Null' is not a subtype of type 'StatefulElement'

The relevant error-causing widget was:
  Scaffold Scaffold:file:///Users/jakehadley/dev/unf_baseball/lib/main/view/main_page.dart:60:18

When the exception was thrown, this was the stack:
#0      MockStatefulNavigationShell.createElement (file:///Users/jakehadley/dev/unf_baseball/test/main/view/main_page_test.dart:24:7)
...     Normal element mounting (25 frames)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#26     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904:36)
#27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916:32)
...     Normal element mounting (111 frames)
#138    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#145    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#152    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#159    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#166    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (9 frames)
#175    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (21 frames)
#196    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#203    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#210    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#217    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#224    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#231    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#238    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#245    _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#252    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#259    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#266    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (240 frames)
#506    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#507    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904:36)
#508    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916:32)
...     Normal element mounting (457 frames)
#965    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
#966    Element.updateChild (package:flutter/src/widgets/framework.dart:3843:20)
#967    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#968    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#969    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#970    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#971    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#972    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#973    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#974    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#975    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#976    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#977    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#978    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#979    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#980    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#981    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#982    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#983    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#984    _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:291:16)
#985    _RawViewElement.update (package:flutter/src/widgets/view.dart:378:5)
#986    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#987    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#988    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#989    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#990    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#991    RootElement._rebuild (package:flutter/src/widgets/binding.dart:1581:16)
#992    RootElement.update (package:flutter/src/widgets/binding.dart:1559:5)
#993    RootElement.performRebuild (package:flutter/src/widgets/binding.dart:1573:7)
#994    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#995    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#996    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1418:19)
#997    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#998    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#999    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#1000   AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1273:9)
#1003   TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#1004   AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1260:27)
#1005   WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:602:22)
#1008   TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#1009   WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:599:27)
#1010   main.<anonymous closure>.<anonymous closure> (file:///Users/jakehadley/dev/unf_baseball/test/main/view/main_page_test.dart:94:20)
#1011   testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:29)
<asynchronous suspension>
#1012   TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @JakeHadley 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thanks!

**Comment by JakeHadley** [comment]
> Hi @JakeHadley For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thanks!

I have a minimal sample now, would it be better to link to another repo, or just paste all the code changes to reproduce it here?

**Comment by JakeHadley** [comment]
I'll paste them here:
```dart
// router.dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:go_router_test/app/router_utils.dart';
import 'package:go_router_test/counter/view/counter_page.dart';
import 'package:go_router_test/events/view/events_page.dart';
import 'package:go_router_test/main/view/main_page.dart';
import 'package:go_router_test/posts/view/posts_page.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _postsNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'posts');
final GlobalKey<NavigatorState> _eventsNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'events');

abstract class AppRouter {
  static final goRouter = GoRouter(
    // debugLogDiagnostics: true,
    navigatorKey: _rootNavigatorKey,
    initialLocation: Pages.posts.path,
    routes: [
      GoRoute(
        path: Pages.counter.path,
        builder: (context, state) => const CounterPage(),
      ),
      StatefulShellRoute.indexedStack(
        builder: (context, state, navigationShell) {
          return MainPage(navigationShell: navigationShell);
        },
        branches: [
          StatefulShellBranch(
            navigatorKey: _postsNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.posts.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: PostsPage(),
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            navigatorKey: _eventsNavigatorKey,
            routes: [
              GoRoute(
                path: Pages.events.path,
                pageBuilder: (context, state) => const NoTransitionPage(
                  child: EventsPage(),
                ),
              ),
            ],
          ),
        ],
      ),
    ],
  );
}
```
```dart
// router_utils.dart
import 'package:flutter/material.dart';

enum Pages { posts, events, counter }

class PageData {
  PageData({
    required this.path,
    required this.name,
    required this.label,
    this.icon,
    this.subpath,
  });

  factory PageData.fromEnum(Pages page) {
    switch (page) {
      case Pages.posts:
        return PageData(
          path: '/posts',
          icon: const Icon(Icons.home),
          name: 'posts',
          label: 'Posts',
        );

      case Pages.events:
        return PageData(
          path: '/events',
          icon: const Icon(Icons.calendar_month_outlined),
          name: 'events',
          label: 'Events',
        );
      case Pages.counter:
        return PageData(
          path: 'counter',
          name: 'counter',
          label: 'Counter',
        );
    }
  }

  final String path;
  final String name;
  final String label;
  final Icon? icon;
  final String? subpath;
}

final pageDataMap = Map.fromEntries(
  Pages.values.map((page) => MapEntry(page, PageData.fromEnum(page))),
);

extension AppPageExtension on Pages {
  String get path => pageDataMap[this]!.path;
  String get label => pageDataMap[this]!.label;
  String get name => pageDataMap[this]!.name;
  Icon? get icon => pageDataMap[this]!.icon;
  String? get subpath => pageDataMap[this]!.subpath;
}
```
```dart
// app.dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:go_router_test/app/router.dart';
import 'package:go_router_test/l10n/l10n.dart';

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: AppRouter.goRouter,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      debugShowCheckedModeBanner: false,
    );
  }
}
```
```dart
// main_page.dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:go_router_test/app/router_utils.dart';

class MainPage extends StatelessWidget {
  const MainPage({
    required this.navigationShell,
    super.key,
  });

  final StatefulNavigationShell navigationShell;

  static final List<Pages> _pages = [
    Pages.posts,
    Pages.events,
  ];

  void _goBranch(int index) {
    navigationShell.goBranch(
      index,
      initialLocation: index == navigationShell.currentIndex,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: navigationShell,
      bottomNavigationBar: NavigationBar(
        selectedIndex: navigationShell.currentIndex,
        destinations: _pages
            .map(
              (page) => NavigationDestination(
                key: ValueKey('bottom_nav_${page.name}'),
                label: page.label,
                icon: page.icon!,
              ),
            )
            .toList(),
        onDestinationSelected: _goBranch,
      ),
    );
  }
}
```
```dart
//main_page_test.dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:go_router_test/main/view/main_page.dart';
import 'package:mocktail/mocktail.dart';

import '../../helpers/mock_go_router.dart';

class MockStatefulNavigationShell extends Mock
    implements StatefulNavigationShell {
  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return '';
  }
}

void main() {
  group('MainPage', () {
    late MockGoRouter mockGoRouter;
    late StatefulNavigationShell navigationShell;

    setUp(() {
      mockGoRouter = MockGoRouter();
      navigationShell = MockStatefulNavigationShell();
    });

    testWidgets('renders with children', (tester) async {
      when(() => navigationShell.currentIndex).thenReturn(0);

      await tester.pumpWidget(
        MaterialApp(
          home: MockGoRouterProvider(
            goRouter: mockGoRouter,
            child: MainPage(
              navigationShell: navigationShell,
            ),
          ),
        ),
      );

      await tester.pumpAndSettle();

      expect(find.byType(MainPage), findsOneWidget);
    });
  });
}
```
```dart
// mock_go_router.dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:mocktail/mocktail.dart';

class MockGoRouter extends Mock implements GoRouter {}

class MockGoRouterProvider extends StatelessWidget {
  const MockGoRouterProvider({
    required this.goRouter,
    required this.child,
    super.key,
  });

  final MockGoRouter goRouter;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return InheritedGoRouter(
      goRouter: goRouter,
      child: child,
    );
  }
}
```
```yaml
// pubspec.yaml
name: go_router_test
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  go_router: ^13.0.1
  intl: ^0.19.0

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
```

**Comment by huycozy** [comment]
Thanks for the update. However, it's still missing some classes (CounterPage, PostsPage, EventsPage). I created them as the following complete sample code and also removed unnecessary packages then I can see the error above: [repro_149139.zip](https://github.com/flutter/flutter/files/15479113/repro_149139.zip)

The issue is on the latest go_router package version: `go_router: ^14.1.4`.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (11 hours ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.76

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-12.0.pre.5, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-12.0.pre.5 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 886de22182 (31 minutes ago), 2024-05-29 02:33:16 +0000
    • Engine revision d0323905fc
    • Dart version 3.5.0 (build 3.5.0-191.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by JakeHadley** [comment]
Awesome, yeah sorry about that. I should have zipped it up for you. Next time. Thanks for triaging it!

**Comment by chunhtai** [comment]
It looks like something wrong with the mock, but I think the fix should be on the test code, not go_router. If you think something is wrong with go_router, please provide a repro without mock

**Comment by JakeHadley** [comment]
> It looks like something wrong with the mock, but I think the fix should be on the test code, not go_router. If you think something is wrong with go_router, please provide a repro without mock

Great, good to know. There is zero documentation out there as to how to mock and test go_router elements, so it's very possible my mock is not handling the appropriate cases correctly. I'm assuming the test project linked here was not ran/tested, so is there any guidance that can be provided as to how to properly test the widgets go_router provides? Or if there are some mocks out there already for `IndexedStack` and the like that I can use to test this use case? Even getting to point of mocking go_router properly for basic use cases was painstaking, difficult, and time consuming. 

Any amount of effort to provide some assistance here would be greatly appreciated.

**Comment by chunhtai** [comment]
Since `StatefulNavigationShell` is a widget and will be part of widget tree, I think I would probably use `class MockShell extends StatefulNavigationShell` and mock out the method instead. Or just create a real `StatefulNavigationShell` directly using constructor.
