### ISSUE TITLE
[two_dimensional_scrollables] IconTreeShakerException when trying to build web

### ISSUE THREAD

**Issue by patrickseiter-hkcsoftware** [flutter/flutter#149267]
### Steps to reproduce

1. Add two_dimensional_scrollables 0.3.0 to pubspec.yaml
2. Add TableView to the code
3. Run flutter build web

The same code builds fine with version 0.2.1. I guess the source of the error is within the new TreeView?

### Expected results

The application should successfully build.

### Actual results

The build fails with an IconTreeShakerException. (see logs)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: TableView.list(
        columnBuilder: (i) => const TableSpan(extent: FixedTableSpanExtent(100)),
        rowBuilder: (i) => const TableSpan(extent: FixedTableSpanExtent(50)),
        cells: List.generate(3, (c) => List.generate(10, (r) => TableViewCell(child: Text('$c $r')))),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Target web_release_bundle failed: IconTreeShakerException: Invalid ConstFinder result. Expected "fontPackage" to be a String, "fontFamily" to be a String, and "codePoint" to be an int, got: {codePoint: 9658.0, fontFamily: null, fontPackage: null,
matchTextDirection: false, fontFamilyFallback: null}.

To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
#0      IconTreeShaker._parseConstFinderResult (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:333:9)
#1      IconTreeShaker._findConstants (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:321:12)
<asynchronous suspension>
#2      IconTreeShaker._getIconData (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:109:45)
<asynchronous suspension>
#3      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:178:5)
<asynchronous suspension>
#4      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:158:25)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:126:3)
<asynchronous suspension>
#7      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:450:29)
<asynchronous suspension>
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#10     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#12     WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#13     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4412], locale de-DE)
    • Flutter version 3.22.1 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (7 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\...\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4412]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.67

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @patrickseiter-hkcsoftware 
I do see the same exception in latest stable version, but not in master, wherein, the command works properly without throwing the said error.

```
dhs@Dhss-MacBook-Pro ip_issue % flutter build web

Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 1172 bytes (99.5% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7692 bytes (99.5% reduction). Tree-shaking can be disabled by providing the
--no-tree-shake-icons flag when building your app.
Compiling lib/main.dart for the Web...                             35.0s
✓ Built build/storybook/web
dhs@Dhss-MacBook-Pro ip_issue % 

```

This indicates it is likely fixed in master which you can check and confirm.  Since the exception doesn't occur in master, I'll closed this as fixed per triage policy. If you disagree, write in comments and I'll reopen it.

**Comment by helgoboss** [comment]
I ran into this issue as well. Here's some more info.

The same issue was also reported by @Piinks, the `two_dimensional_scrollables` author: https://github.com/flutter/flutter/issues/147189. They fixed it on the Flutter engine side by making the icon tree shaker more tolerant, but looks like this change hasn't made it yet into Flutter Stable.

@Piinks Would it be possible to fix this in `two_dimensional_scrollables` as well so that it works for people who don't use cutting-edge Flutter? I think it would be enough to apply the following change to [the original builder function](https://github.com/flutter/packages/blob/main/packages/two_dimensional_scrollables/lib/src/tree_view/tree.dart#L560).

Replace this:

```dart
child: const Icon(IconData(0x25BA), size: 14),
```

with this:

```dart
const Center(
    child: Text("►", style: TextStyle(fontSize: 14)),
)
```

This should yield the same result without needing special support from the icon tree shaker.
