### ISSUE TITLE
[tool_crash] FileSystemException: readInto failed, OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by brayonpi** [flutter/flutter#149228]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readInto failed, OS Error: Operation timed out, errno = 60
```
#0      _RandomAccessFile.readIntoSync (dart:io/file_impl.dart:835:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:593:35)
#2      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#4      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#6      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#7      CocoaPods._addPodsDependencyToFlutterXcconfig (package:flutter_tools/src/macos/cocoapods.dart:293:35)
#8      CocoaPods.addPodsDependencyToFlutterXcconfig (package:flutter_tools/src/macos/cocoapods.dart:287:5)
#9      CocoaPods.setupPodfile (package:flutter_tools/src/macos/cocoapods.dart:258:7)
#10     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1207:34)
<asynchronous suspension>
#11

**Comment by darshankawar** [comment]
@brayonpi 
Since it says operation timed out, it could be related to network connection. Do you have fast / stable internet connection ?
If you run the command everytime, does it throw same exception consistently ?
