### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by wajipu** [flutter/flutter#149312]
## Command
```
flutter --quiet assemble --no-version-check --depfile /Users/xx/Documents/2024Project/flutter_cai_gli/build/app/intermediates/flutter/release/flutter_build.d --output /Users/xx/Documents/2024Project/flutter_cai_gli/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:420:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:82:12)
#6      Target.clearStamp (package:flutter_tools/src/build_system/build_system.dart:164:29)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:868:19)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#13     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
<asynchronous suspension>
#14     Future.wait.<anonymous

**Comment by huycozy** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/148761. Please follow that issue for further investigation. Thanks!
