### ISSUE TITLE
`flutter run` fails but `flutter build apk --debug` or android studio build succeed

### ISSUE THREAD

**Issue by rusenask** [flutter/flutter#14933]
## Steps to Reproduce

Tried both `beta` and `master` channels. This issue came up quite recently. When I try to run the app with `flutter run` it crashes. But if I try to `flutter build apk --debug` or do it via android studio, it always succeeds.

At first I thought it was the same issue as I had due to packaging options:

```
    packagingOptions {
        exclude 'lib/arm64-v8a/libgojni.so'
    }
```

But I still have that packaging option and I suspect it's something else. 

## Logs

Flutter run doesn't detect anything unusual:

```
flutter run

Running "flutter packages get" in pop...              0.9s
Launching lib/main.dart on Nexus 6P in debug mode...
Initializing gradle...                                1.2s
Resolving dependencies...                             1.2s
Running 'gradlew assembleDebug'...                   17.4s
Built build/app/outputs/apk/debug/app-debug.apk (29.2MB).
Installing build/app/outputs/apk/app.apk...          22.1s
```

Available logs from Android Studio:

```
02-27 22:31:36.488 21639-21639/com.appscension.pop E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.appscension.pop, PID: 21639
                                                                     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appscension.pop-ljAJwMyBBvRheZkwbDgu_g==/base.apk"],nativeLibraryDirectories=[/data/app/com.appscension.pop-ljAJwMyBBvRheZkwbDgu_g==/lib/arm64, /data/app/com.appscension.pop-ljAJwMyBBvRheZkwbDgu_g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libgojni.so"
                                                                         at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                         at java.lang.System.loadLibrary(System.java:1657)
                                                                         at go.LoadJNI.<clinit>(LoadJNI.java:23)
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.Class.forName(Class.java:453)
                                                                         at java.lang.Class.forName(Class.java:378)
                                                                         at go.Seq.<clinit>(Seq.java:28)
                                                                         at go.Seq.touch(Seq.java:45)
                                                                         at plugin.Plugin.<clinit>(Plugin.java:11)
                                                                         at plugin.Plugin.bootstrap(Native Method)
                                                                         at com.appscension.fluttergo.GoPlugin.registerWith(GoPlugin.java:20)
                                                                         at com.appscension.pop.MainActivity.onCreate(MainActivity.java:34)
                                                                         at android.app.Activity.performCreate(Activity.java:6999)
                                                                         at android.app.Activity.performCreate(Activity.java:6990)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

## Flutter Doctor

```
flutter doctor -v

[✓] Flutter (Channel master, v0.1.8-pre.2, on Mac OS X 10.13.3 17D47, locale en-GB)
    • Flutter version 0.1.8-pre.2 at /Users/karolisrusenas/Projects/flutter
    • Framework revision 29d59e3cb7 (2 hours ago), 2018-02-27 13:15:32 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/karolisrusenas/Library/Android/sdk
    • Android NDK at /Users/karolisrusenas/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/karolisrusenas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.0

[✓] Connected devices (1 available)
    • Nexus 6P • ENU7N15A27000419 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by cbracken** [comment]
What happens when you `flutter run --target-platform=android-arm` (to request a 32-bit build)?

**Comment by rusenask** [comment]
Thanks! It works with `flutter run --target-platform=android-arm`. 

Did default value changed?

**Comment by cbracken** [comment]
> Did default value changed?

@rusenask we recently added some logic that attempts to detect whether the device being deployed to needs a 32-bit or 64-bit binary. That logic still needs some tuning.

**Comment by mzejcom** [comment]
I always have  this message : 

'flutter' is not recognised as an internal or external command
operable program or patch file 

:(   this is inside the AppDir
Any suggestion please

**Comment by zoechi** [comment]
@mzejcom what OS? 
What directory did you install Flutter to?
Did you add the `bin/` sub-directory of the Flutter install directory to PATH?

**Comment by mzej** [comment]
@zoechi Thanks >>> it h b solved
Flutter\bin already has been added
But, the problem was solved after adding Windows Power shell PATH.
Regards

**Comment by dkashkin** [comment]
@cbracken I am using the latest greatest flutter as of December 2nd 2018, and the bug that you acknowledged 9(!) months ago seems to be still there. The default Android Studio build is incorrectly assuming that my target device is 64 bit, so the app crashes on start because the APK is missing libflutter.so under armeabi-v7a. So, I am having to use the console and force the target architecture (flutter run --target-platform=android-arm). Needless to say, this is a super visible issue to all new Flutter developers. When are you guys going to fix it?

**Comment by cbracken** [comment]
@dkashkin one means the team uses to prioritise work is thumbs-up reactions on issues. I'd definitely encourage you to add a thumbs-up on this issue if it's causing you a lot of pain. 

Adding the output of a `flutter doctor` run would also be useful data to help correct the issue. It seems as though most devices are being detected correctly, but some devices (looks like at least the Nexus 6P) are being detected incorrectly.

**Comment by Allan-Nava** [comment]
I got this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:189: error: resource android:attr/fontVariationSettings not found.
  /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:190: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

  Command: /Users/ies/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/6fb856bc368a193ba4e928dec52b55c6/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/ies/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          it.iesitalia.seafymanager\
          -0\
          apk\
          --output-text-symbols\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0
  Output:  /Users/ies/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/50ce7570525b113663a4d82aa935d514/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /Users/ies/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/50ce7570525b113663a4d82aa935d514/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.
  Command: /Users/ies/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/6fb856bc368a193ba4e928dec52b55c6/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/ies/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          it.iesitalia.seafymanager\
          -0\
          apk\
          --output-text-symbols\
          /Users/ies/Desktop/work/seafy/seafy/seafy_manager/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

How can I fix it?

**Comment by zoechi** [comment]
@Allan-Nava https://github.com/flutter/flutter/issues/27170#issuecomment-458054069, #27106

**Comment by jonathankablan** [comment]
Hi how build an apk unsigned with flutter ? , already tried https://flutter.dev/docs/deployment/android

**Comment by jmagman** [comment]
If anyone's still seeing this, the output of the following would be helpful:
```
$ flutter doctor -v
$ adb shell getprop ro.product.cpu.abi
$ adb shell getprop ro.product.cpu.abilist
```

**Comment by alexmik95** [comment]
It could be related to [this dart issue](https://github.com/dart-lang/sdk/issues/40589). i'm on archlinux with latest linux kernel (5.5+) and `flutter run` stuck forever at `gradlew assembleDebug`. Temporaly solved installing `linux-lts` kernel and in my case `nvidia-lts` drivers.

**Comment by TahaTesser** [comment]
Hi @rusenask 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
