### ISSUE TITLE
 flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by imyyq-star** [flutter/flutter#14940]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = storage.googleapis.com, port = 55126

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:534)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:268)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:294)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:265)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:281)
#7      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:317)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:228)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:195)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:274)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#27     main (file:///D:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (Channel master, v0.1.8-pre.7, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 0.1.8-pre.7 at D:\Flutter\flutter
    • Framework revision 6993b203c0 (63 minutes ago), 2018-02-27 17:39:49 -0800
    • Engine revision e133da723c
    • Dart version 2.0.0-dev.30.0.flutter-0b4f01f759
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Android\sdk
    • Android NDK at C:\Android\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA 2017.1.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by coloer** [comment]
我也出现了这情况。
I also occur this error.

**Comment by mraleph** [comment]
Check out these instructions: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by xster** [comment]
Duping the action item for this into #14587
