### ISSUE TITLE
Flutter crashed

### ISSUE THREAD

**Issue by allowthere** [flutter/flutter#14943]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release --release

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/user/Downloads/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --await_is_keyword --vm_snapshot_data=/home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release/isolate_snapshot_data --packages=.packages --url_mapping=dart:ui,/home/user/Downloads/flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart --url_mapping=dart:vmservice_io,/home/user/Downloads/flutter/bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --print_snapshot_sizes --dependencies=/home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release/snapshot.d --causal_async_stacks --embedder_entry_points_manifest=/home/user/Downloads/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points.txt --embedder_entry_points_manifest=/home/user/Downloads/flutter/bin/cache/artifacts/engine/android-arm-release/dart_io_entries.txt --snapshot_kind=app-aot-blobs --vm_snapshot_instructions=/home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/home/user/Downloads/flutter/examples/hello_world/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/user/Downloads/flutter/examples/hello_world/lib/main.dart

```
#0      runAsync (package:flutter_tools/src/base/process.dart:220)
<asynchronous suspension>
#1      _buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:384)
<asynchronous suspension>
#2      buildAotSnapshot (package:flutter_tools/src/commands/build_aot.dart:121)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:77)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#5      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#9      new Future.sync (dart:async/future.dart:222)
#10     CommandRunner.run (package:args/command_runner.dart:109)
#11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#19     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#21     main (file:///home/user/Downloads/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[!] Flutter (on Linux, locale en_US.UTF-8, channel beta)
    • Flutter version 0.1.4 at /home/user/Downloads/flutter
    • Framework revision f914e701c5 (8 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/user/AndroidStudio/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/user/AndroidStudio/Sdk
    • Java binary at: /home/user/Downloads/android-studio-1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.1)
    • Android Studio at /home/user/Downloads/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/user/Downloads/android-studio1
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /home/user/Downloads/android-studio-1/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/user/AndroidStudio/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.20.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.9.0

[✓] Connected devices
    • Google Pixel, 8 0, API 26, 1080x1920 • 192.168.59.101:5555 • android-x86 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Comment by mraleph** [comment]
What kind of Linux ditro are you running on? Do suggestions from https://github.com/flutter/flutter/issues/6207 fix it?

**Comment by allowthere** [comment]
Debian testing (Buster)

**Comment by allowthere** [comment]
Yes. That fixes it.
