### ISSUE TITLE
Can't profile an app using iPhone 15 simulator

### ISSUE THREAD

**Issue by JuaniV2002** [flutter/flutter#149420]
### Steps to reproduce

1. Have an existing (and working) flutter app.
2. Have an iPhone 15 emulator up and running (I tested with that device, the problem may be the same with the newer Apple phones)
3. Instead of just running the app **without debugging**, run the app with the `--profile` flag (CLI), or if you are using VS Code, just click on "Profile", just above the `main()` method.
4. As soon as I run `flutter run --profile`, I get this error message on my terminal: "Profile mode is not supported by iPhone 15.'

### Expected results

As far as I know, profiling the app allows me to "feel" the app the same way the end user will, removing many features that make the app slower, but better for debugging.

### Actual results

I'm getting this error message: "Profile mode is not supported by iPhone 15.".

![Screenshot 2024-05-31 at 12 36 55](https://github.com/flutter/flutter/assets/98132290/26c4261c-65c1-4fdc-99ed-731a5539c041)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter run --profile --verbose
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +9 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.5
[        ] executing: sw_vers -buildVersion
[   +8 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23F79
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[   +3 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[   +7 ms] Unable to locate an Android SDK.
[  +88 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +177 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 15.4
           Build version 15F31d
[   +2 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 5
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +27 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 2
[        ] /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[        ] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted
[ +113 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 17.5 --
               iPhone 15 (4C70534D-73A5-4691-AB03-B874FC79A292) (Booted)
[ +127 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-17-5" : [
                          {
                            "lastBootedAt" : "2024-05-31T15:32:18Z",
                            "dataPath" :
                            "\/Users\/juani\/Library\/Developer\/CoreSimulator\/Devices\/4C70534D-73A5-4691-AB03-B874FC79A292\/data",
                            "dataPathSize" : 1764913152,
                            "logPath" : "\/Users\/juani\/Library\/Logs\/CoreSimulator\/4C70534D-73A5-4691-AB03-B874FC79A292",
                            "udid" : "4C70534D-73A5-4691-AB03-B874FC79A292",
                            "isAvailable" : true,
                            "logPathSize" : 389120,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-15",
                            "state" : "Booted",
                            "name" : "iPhone 15"
                          }
                        ]
                      }
                    }
[+2877 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,1",
                        "identifier" : "64343AFD-E878-4784-B6FD-F5210E2F5F2B",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-1",
                        "modelName" : "iPhone 15 Pro",
                        "name" : "iPhone 15 Pro",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "059424A3-2AF4-4BAA-A16D-2D9EBBF0D4C6",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad16,6",
                        "identifier" : "137F94CD-8C2E-4AD7-8674-2E635087F65C",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-m4-13-1",
                        "modelName" : "iPad Pro 13-inch (M4)",
                        "name" : "iPad Pro 13-inch (M4)",
                        "ignored" : false
                      },
                      {
                        "ignored" : false,
                        "modelCode" : "Mac14,2",
                        "simulator" : false,
                        "modelName" : "MacBook Air",
                        "operatingSystemVersion" : "14.5 (23F79)",
                        "identifier" : "00008112-001844820E08201E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "arm64e",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookair-13-2022"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,11",
                        "identifier" : "95EECF3B-A0C2-458D-B149-4B68ACDD7117",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air-m2-13-1",
                        "modelName" : "iPad Air 13-inch (M2)",
                        "name" : "iPad Air 13-inch (M2)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,9",
                        "identifier" : "A536EED0-CC82-4289-A3F7-A5D91549314F",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air-m2-1",
                        "modelName" : "iPad Air 11-inch (M2)",
                        "name" : "iPad Air 11-inch (M2)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad16,4",
                        "identifier" : "55AD1986-5903-4B2B-9870-F8195DA8FEA3",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-m4-1",
                        "modelName" : "iPad Pro 11-inch (M4)",
                        "name" : "iPad Pro 11-inch (M4)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,4",
                        "identifier" : "4C70534D-73A5-4691-AB03-B874FC79A292",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-1",
                        "modelName" : "iPhone 15",
                        "name" : "iPhone 15",
                        "ignored" : false
                      },
                      {
                        "ignored" : false,
                        "modelCode" : "iPhone14,4",
                        "simulator" : false,
                        "modelName" : "iPhone 13 mini",
                        "error" : {
                          "code" : -27,
                          "failureReason" : "",
                          "description" : "Browsing on the local area network for Juani’s iPhone 13 mini",
                          "recoverySuggestion" : "Ensure the device is unlocked and attached with a cable or associated with the same local
                          area network as this Mac.\nThe device must be opted into Developer Mode to connect wirelessly.",
                          "domain" : "com.apple.dt.deviceprep"
                        },
                        "operatingSystemVersion" : "17.4.1 (21E236)",
                        "identifier" : "00008110-001E5424262B801E",
                        "platform" : "com.apple.platform.iphoneos",
                        "architecture" : "arm64e",
                        "interface" : "usb",
                        "available" : false,
                        "name" : "Juani’s iPhone 13 mini",
                        "modelUTI" : "com.apple.iphone-13-mini-1"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "F0C9ED9A-6F1F-48AB-B577-7D6161592472",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "06CF3B18-4AB5-4DFF-8224-882C353149A9",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "16F1B4BA-8D1B-45CA-8F78-37B21F2C2F06",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,5",
                        "identifier" : "8712D418-6D8D-46EB-A255-80ACAA2BB2C9",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-plus-1",
                        "modelName" : "iPhone 15 Plus",
                        "name" : "iPhone 15 Plus",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,1",
                        "identifier" : "9345A4D5-81F1-43F5-B92E-A4744A558F6B",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-1",
                        "modelName" : "iPhone 15 Pro",
                        "name" : "iPhone 15",
                        "ignored" : false
                      }
                    ]

                    2024-05-31 12:38:50.036 xcdevice[62286:2845815]  DVTDeviceOperation: 00008110-001E5424262B801E: skipping implicit
                    preparation because autoConnectStyle == ignored
                    2024-05-31 12:38:50.037 xcdevice[62286:2845815]  DVTDeviceOperation: 00008110-001E5424262B801E: skipping implicit
                    preparation because autoConnectStyle == ignored
[   +4 ms] executing: /usr/bin/arch -arm64e xcrun devicectl --version
[  +58 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun devicectl --version
[        ] 355.28
[   +2 ms] executing: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output
/var/folders/_g/h27gm9rn31s9yc0mc9fw4l6h0000gn/T/flutter_tools.ONc7fI/core_devices.taDWY8/core_device_list.json
[+1079 ms] Devices:
                    Name                     Hostname                                     Identifier                             State
                    Model
                    ----------------------   ------------------------------------------   ------------------------------------   -----------
                    ---------------------------
                    Juani’s iPhone 13 mini   00008110-001E5424262B801E.coredevice.local   A3234226-249E-458E-8F1C-F5F3E77C3586   unavailable
                    iPhone 13 mini (iPhone14,4)
[   +2 ms] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/_g/h27gm9rn31s9yc0mc9fw4l6h0000gn/T/flutter_tools.ONc7fI/core_devices.taDWY8/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "355.28"
             },
             "result" : {
               "devices" : [
                 {
                   "capabilities" : [
                     {
                       "featureIdentifier" : "com.apple.coredevice.feature.unpairdevice",
                       "name" : "Unpair Device"
                     }
                   ],
                   "connectionProperties" : {
                     "authenticationType" : "manualPairing",
                     "isMobileDeviceOnly" : false,
                     "lastConnectionDate" : "2024-05-30T18:50:07.327Z",
                     "pairingState" : "paired",
                     "potentialHostnames" : [
                       "00008110-001E5424262B801E.coredevice.local",
                       "A3234226-249E-458E-8F1C-F5F3E77C3586.coredevice.local"
                     ],
                     "tunnelState" : "unavailable"
                   },
                   "deviceProperties" : {
                     "bootedFromSnapshot" : true,
                     "bootedSnapshotName" : "com.apple.os.update-A43F71ACF1A95587B0207FAD96CDF7D8CC9124D7CB57650F1B322A1F5FF27AE2",
                     "ddiServicesAvailable" : false,
                     "developerModeStatus" : "enabled",
                     "hasInternalOSBuild" : false,
                     "name" : "Juani’s iPhone 13 mini",
                     "osBuildUpdate" : "21E236",
                     "osVersionNumber" : "17.4.1",
                     "rootFileSystemIsWritable" : false
                   },
                   "hardwareProperties" : {
                     "cpuType" : {
                       "name" : "arm64e",
                       "subType" : 2,
                       "type" : 16777228
                     },
                     "deviceType" : "iPhone",
                     "ecid" : 8536763537260574,
                     "hardwareModel" : "D16AP",
                     "internalStorageCapacity" : 128000000000,
                     "isProductionFused" : true,
                     "marketingName" : "iPhone 13 mini",
                     "platform" : "iOS",
                     "productType" : "iPhone14,4",
                     "reality" : "physical",
                     "serialNumber" : "T3VDFWQM2C",
                     "supportedCPUTypes" : [
                       {
                         "name" : "arm64e",
                         "subType" : 2,
                         "type" : 16777228
                       },
                       {
                         "name" : "arm64",
                         "subType" : 0,
                         "type" : 16777228
                       },
                       {
                         "name" : "arm64",
                         "subType" : 1,
                         "type" : 16777228
                       },
                       {
                         "name" : "arm64_32",
                         "subType" : 1,
                         "type" : 33554444
                       }
                     ],
                     "supportedDeviceFamilies" : [
                       1
                     ],
                     "thinningProductType" : "iPhone14,4",
                     "udid" : "00008110-001E5424262B801E"
                   },
                   "identifier" : "A3234226-249E-458E-8F1C-F5F3E77C3586",
                   "visibilityClass" : "default"
                 }
               ]
             }
           }

[   +5 ms] Error: Browsing on the local area network for Juani’s iPhone 13 mini. Ensure the device is unlocked and attached with a cable or
associated with the same local area network as this Mac.
           The device must be opted into Developer Mode to connect wirelessly. (code -27)
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] Skipping pub get: version match.
[  +88 ms] Generating
/Users/juani/programs/flutter_apps/meals_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +76 ms] "flutter run" took 4,742ms.
[  +33 ms] Profile mode is not supported by iPhone 15.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:768:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[ +127 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-AR)
    • Flutter version 3.22.1 on channel stable at /Users/juani/programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (9 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/VS Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone 15 (mobile)              • 4C70534D-73A5-4691-AB03-B874FC79A292 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.113
    ! Error: Browsing on the local area network for Juani’s iPhone 13 mini. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Connection reset by peer

! Doctor found issues in 3 categories.
```

</details>

**Comment by moffatman** [comment]
Profile/release mode in the simulator is not really useful as the simulator has its own unique performance characteristics.

See https://github.com/flutter/flutter/issues/11754

**Comment by JuaniV2002** [comment]
Hi @moffatman, thank you for your reply!

I get it, nonetheless the profile mode should work for all the simulators! Not just for iOS simulators, but for Android too...

**Comment by moffatman** [comment]
What's the use case besides performance testing?

**Comment by JuaniV2002** [comment]
Well, first of all I would like to know what "useful performance characteristics" the simulator has...

**Comment by moffatman** [comment]
I didn't say useful. I said unique. E.G. it uses software rendering, so graphics performance will not be similar to a real iPhone 15. Different things will be slower and faster (most slower) depending on Apple's implementation as well as your Mac's specs. The only real way to test performance is to have the device.

**Comment by JuaniV2002** [comment]
So you suggest profiling works when testing on a real device (android or iOS)?

**Comment by moffatman** [comment]
Yes if you plug in a real device you can use profile mode to gather useful information about your app's performance.

**Comment by JuaniV2002** [comment]
Thank you! I'll give it a shot with my phone
