### ISSUE TITLE
Regression: Semantic Tree Generation for Custom Widget Fails Due to TextField Semantic Enabled Property Change

### ISSUE THREAD

**Issue by xsahil03x** [flutter/flutter#149401]
### Description
We are encountering a regression in our semantic tests for a custom widget after updating to the latest Flutter version. The issue appears to be related to a recent change in the TextField implementation where the enabled property was added to the Semantics widget.

Related PR: https://github.com/flutter/flutter/pull/143601

### Steps to reproduce

1. Create a new Flutter test using the code sample provided below.
2. Run the provided semantic test and observe the failure.

### Expected results

The semantic tree should be generated as it was in Flutter version `3.19.3`:

```
SemanticsNode#4
   Rect.fromLTRB(8.0, 304.0, 792.0, 352.0)
   actions: tap
   flags: isTextField, hasEnabledState, isEnabled
   label:
     "Label
     Hint text"
   hint: "Help text"
   textDirection: ltr
   currentValueLength: 0
 ```
 
 The test fails due to this difference.

### Actual results

The semantic tree generated in Flutter version `3.22.1` is different:

```
SemanticsNode#4
     │ Rect.fromLTRB(8.0, 304.0, 792.0, 352.0)
     │ flags: hasEnabledState, isEnabled
     │ label: "Label"
     │ hint: "Help text"
     │ textDirection: ltr
     │
     └─SemanticsNode#5
         Rect.fromLTRB(0.0, 0.0, 784.0, 48.0)
         actions: tap
         flags: isTextField, hasEnabledState, isEnabled
         label: "Hint text"
         textDirection: ltr
         currentValueLength: 0
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Custom widget semantics test', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        body: Semantics(
          label: 'Label',
          hint: 'Help text',
          enabled: true,
          child: TextField(
            enabled: true,
            decoration: InputDecoration(
              hintText: 'Hint text',
            ),
          ),
        ),
      ),
    ));

    expect(
      tester.getSemantics(find.byType(TextField)),
      matchesSemantics(
        label: 'Label\nHint text',
        isTextField: true,
        isEnabled: true,
        hasTapAction: true,
        hasEnabledState: true,
        currentValueLength: 0,
      ),
    );
  });
}
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: has semantics with label: Label
          Hint text with actions: [tap]  without actions: [longPress, scrollLeft, scrollRight,
scrollUp, scrollDown, increase, decrease, showOnScreen, moveCursorForwardByCharacter,
moveCursorBackwardByCharacter, setSelection, copy, cut, paste, didGainAccessibilityFocus,
didLoseAccessibilityFocus, dismiss, moveCursorForwardByWord, moveCursorBackwardByWord, setText]
with flags: [isTextField, hasEnabledState, isEnabled]  without flags: [hasCheckedState, isChecked,
isCheckStateMixed, isSelected, isButton, isSlider, isKeyboardKey, isLink, isReadOnly, isFocused,
isFocusable, isInMutuallyExclusiveGroup, isHeader, isObscured, isMultiline, namesRoute, scopesRoute,
isHidden, isImage, isLiveRegion, hasToggledState, isToggled, hasImplicitScrolling, hasExpandedState,
isExpanded]  with currentValueLength: 0
  Actual: SemanticsNode:<SemanticsNode#4(Rect.fromLTRB(8.0, 304.0, 792.0, 352.0), flags:
[hasEnabledState, isEnabled], label: "Label", hint: "Help text", textDirection: ltr)>
   Which: label was: Label

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Users/sahilkumar/StudioProjects/universal-client/uniclient/core/design_system/test/molecules/form/label_form_field_test.dart:209:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/sahilkumar/StudioProjects/universal-client/uniclient/core/design_system/test/molecules/form/label_form_field_test.dart line 209
The test description was:
  Semantics should include [label] and [hint]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.3 23D56 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.1)
[✓] VS Code (version 1.89.1)
[✓] VS Code (version 1.85.1)
[✓] Network resources
```

</details>

### Additional Information:
The test passes if we remove the enabled property from the Semantics widget in our custom widget:

```diff
Semantics(
  label: widget.label,
  hint: widget.helpText,
- enabled: widget.enabled,
  child: TextField(
    enabled: widget.enabled,
    decoration: InputDecoration(
      hintText: widget.hintText,
    ),
  ),
);

```

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on latest stable and master versions, but the test passes in 3.19.6.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (5 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.23.0-13.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b295c86b2e (32 minutes ago), 2024-05-30 00:29:41 -0400
    • Engine revision 19707e811b
    • Dart version 3.5.0 (build 3.5.0-203.0.dev)
    • DevTools version 2.36.0-dev.10
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by justinmc** [comment]
CC @hangyujin did your PR https://github.com/flutter/flutter/pull/143601 cause this?

**Comment by hangyujin** [comment]
Yes  https://github.com/flutter/flutter/pull/143601 caused this, this should be WAI

**Comment by xsahil03x** [comment]
Hey @hangyujin, what exactly is the action on this issue?

**Comment by hangyujin** [comment]
@xsahil03x 

Removing the enabled property from the Semantics widget in your custom widget is the right resolution.  

Since TextField supports `enabled` semantics now, you don't need it in your custom widget.
