### ISSUE TITLE
SocketException: SocketException: OS Error: 信号灯超时时间已到

### ISSUE THREAD

**Issue by m-maohuawei** [flutter/flutter#14957]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create hello

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = storage.googleapis.com, port = 50040

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:534)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:268)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:294)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:265)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:281)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:453)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:228)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:195)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:274)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#27     main (file:///D:/Local/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale zh-CN, channel beta)
    • Flutter version 0.1.4 at D:\Local\Flutter\flutter
    • Framework revision f914e701c5 (9 days ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Local\Android\Sdk
    • Android NDK at D:\Local\Android\Sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\3.2\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\3.2\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by cbracken** [comment]
Thanks for reporting! Do the instructions here help?
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by xster** [comment]
Duping into #14587

**Comment by linguanghua** [comment]
@m-maohuawei 
问题解决了吗？我也遇到这个问题
Is the problem solved? I have this problem too.
win10 64

**Comment by cyy2yjp** [comment]
i have same problem while set the pub_..._url still erro,but use git bash every thing is ok,mine os win10
