### ISSUE TITLE
Flutter crashes on hot reload when switching tabs.

### ISSUE THREAD

**Issue by Treidexy** [flutter/flutter#149606]
### Steps to reproduce

1. On windows app, hot reload or hot restart.
2. Quickly alt+tab to flutter application (before the hot reload finishes).
3. Release alt+tab, press any key. (I found it most likely to crash when spamming alt+tab)

### Expected results

No error should appear. The flutter app should continue as normal.

### Actual results

A keydown error is reported. Sometimes the application crashes.

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp());
}
```

### Logs

<details open><summary>Logs</summary>

**Error**

```console
Performing hot restart...
Restarted application in 503ms.
Unable to parse JSON message:
The document is empty.

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this
occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
was the event: KeyDownEvent#e3bac(physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2",
debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt
Left", debugName: "Alt Left"), character: null, timeStamp: 98:27:11.761852)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 505 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:505:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:520:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:643:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1167:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:228:31)
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Unable to parse JSON message:
The document is empty.
Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented
in `HardwareKeyboard`. This was the event: KeyDownEvent#e3bac(physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2", debugName: "Alt Left"),
logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 98:27:11.761852)
Unable to parse JSON message:
The document is empty.
Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented
in `HardwareKeyboard`. This was the event: KeyDownEvent#e3bac(physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2", debugName: "Alt Left"),
logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 98:27:11.761852)

Unable to parse JSON message:
The document is empty.
Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented
in `HardwareKeyboard`. This was the event: KeyDownEvent#e3bac(physicalKey: PhysicalKeyboardKey#f0183(usbHidUsage: "0x000700e2", debugName: "Alt Left"),
logicalKey: LogicalKeyboardKey#e5ce6(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 98:27:11.761852)
```

**Crash 1**

```console
Performing hot restart...
Restarted application in 2,580ms.
Lost connection to device.
```

**Crash 2**

```console
Performing hot restart...
Restarted application in 484ms.
[FATAL:flutter/shell/platform/windows/keyboard_key_handler.cc(142)] Could not find pending key event for sequence ID 6
Lost connection to device.

Taking screenshot for Windows...
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.2-0.0.pre.1, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
    • Flutter version 3.19.2-0.0.pre.1 on channel stable at C:\Users\yo2mo\Projects\Dart\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3e5a6c6114 (3 months ago), 2024-03-02 11:44:53 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\yo2mo\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.89.1)
    • VS Code at C:\Users\yo2mo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.67

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
I think this is similar to https://github.com/flutter/flutter/issues/141091, which also occurs while pressing and releasing key during hot reload / restart, so please follow-up in it for further updates.
Closing this as duplicate.
