### ISSUE TITLE
Desktop Windows: ProcessException: The parameter is incorrect

### ISSUE THREAD

**Issue by mobilevvdn** [flutter/flutter#149605]
### Steps to reproduce

I want to work desktop application using flutter so i have download the flutter windows stable SDK and setup all this things but when i try to run the application on windows 10 from Android Studio i am getting this error like  **ProcessException: The parameter is incorrect.**
I am able to generate .exe file while i hit the run buttont but unable to open automatic, it gives this error, so please help me out what i need to do?

My System Config:
Processor: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Ram: 16GB
System Type: 64bit Windows 10 Pro

### Actual results

It should run the windows based desktop application without any error.
It should mark all the things on flutter doctor commad.

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4474], locale en-IN)
    • Flutter version 3.22.1 on channel stable at D:\Developement\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (12 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: The parameter is incorrect.

        Command: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command "Get-Process | Format-List Path"
    • #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
      #1      Process.start (dart:io-patch/process_patch.dart:38:20)
      #2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
      #3      Process.run (dart:io-patch/process_patch.dart:49:12)
      #4      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:72:22)
      #5      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:661:24)
      #6      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
      #7      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:660:12)
      #8      ProcessLister.getProcessesWithPath
      (package:flutter_tools/src/windows/windows_version_validator.dart:111:27)
      #9      WindowsVersionValidator._topazScan
      (package:flutter_tools/src/windows/windows_version_validator.dart:40:69)
      #10     WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:81:15)
      #11     Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:273:72)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #13     _rootRun (dart:async/zone.dart:1399:13)
      #14     _CustomZone.run (dart:async/zone.dart:1301:19)
      #15     _runZoned (dart:async/zone.dart:1826:10)
      #16     runZonedGuarded (dart:async/zone.dart:1814:12)
      #17     runZoned (dart:async/zone.dart:1760:12)
      #18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:265:9)
      #20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:397:72)
      #21     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #22     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1758:12)
      <asynchronous suspension>
      #23     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #25     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
      <asynchronous suspension>
      #29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
      <asynchronous suspension>
      #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #31     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Developement\AndroidSdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: D:\Developement\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at D:\Developement\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4474]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.113
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.79

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Could you try running command `Get-Process | Format-List Path` directly from PowerShell to see if any error occurs?
