### ISSUE TITLE
ICU-to-flutter roller has been failing for multiple weeks

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#149684]
### Steps to reproduce

A google-internal mechanism for rolling ICU updates to Flutter has been failing.

I think the issue is due to licensing text changes. (Why they have to keep it changing is beyond me but here we are.)

### Expected results

The roll succeeds.

### Actual results

The license check fails.

```

failure: failed to handle ../../../flutter/third_party/icu/LICENSE
could not parse ICU license file
Original stack:
#0      new _RepositoryIcuLicenseFile (package:licenses/main.dart:426:7)
#1      _RepositoryDirectory.createFile (package:licenses/main.dart:1016:27)
#2      _RepositoryDirectory.crawl (package:licenses/main.dart:927:43)
#3      new _RepositoryDirectory (package:licenses/main.dart:902:5)
#4      _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:986:12)
#5      _RepositoryFlutterThirdPartyDirectory.createSubdirectory (package:licenses/main.dart:1738:18)
#6      _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#7      new _RepositoryDirectory (package:licenses/main.dart:902:5)
#8      new _RepositoryGenericThirdPartyDirectory (package:licenses/main.dart)
#9      new _RepositoryFlutterThirdPartyDirectory (package:licenses/main.dart)
#10     _RepositoryFlutterDirectory.createSubdirectory (package:licenses/main.dart:1705:14)
#11     _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#12     new _RepositoryDirectory (package:licenses/main.dart:902:5)
#13     new _RepositoryFlutterDirectory (package:licenses/main.dart)
#14     _EngineSrcDirectory.createSubdirectory (package:licenses/main.dart:1400:14)
#15     _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#16     new _RepositoryDirectory (package:licenses/main.dart:902:5)
#17     new _EngineSrcDirectory (package:licenses/main.dart:1378:42)
#18     main (package:licenses/main.dart:2020:39)
#19     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

#0      _RepositoryDirectory.crawl (package:licenses/main.dart:936:13)
#1      new _RepositoryDirectory (package:licenses/main.dart:902:5)
#2      _RepositoryDirectory.createSubdirectory (package:licenses/main.dart:986:12)
#3      _RepositoryFlutterThirdPartyDirectory.createSubdirectory (package:licenses/main.dart:1738:18)
#4      _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#5      new _RepositoryDirectory (package:licenses/main.dart:902:5)
#6      new _RepositoryGenericThirdPartyDirectory (package:licenses/main.dart)
#7      new _RepositoryFlutterThirdPartyDirectory (package:licenses/main.dart)
#8      _RepositoryFlutterDirectory.createSubdirectory (package:licenses/main.dart:1705:14)
#9      _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#10     new _RepositoryDirectory (package:licenses/main.dart:902:5)
#11     new _RepositoryFlutterDirectory (package:licenses/main.dart)
#12     _EngineSrcDirectory.createSubdirectory (package:licenses/main.dart:1400:14)
#13     _RepositoryDirectory.crawl (package:licenses/main.dart:922:46)
#14     new _RepositoryDirectory (package:licenses/main.dart:902:5)
#15     new _EngineSrcDirectory (package:licenses/main.dart:1378:42)
#16     main (package:licenses/main.dart:2020:39)
#17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#18     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

aborted.
```

### Code sample

n/a

### Screenshots or Video

n/a

### Logs

n/a

### Flutter Doctor output

n/a

**Comment by filmil** [comment]
Please assign me to this bug.
