### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by MaRuDoRaRa** [flutter/flutter#149642]
## Command
```
flutter build ipa --release --build-number=1 --flavor=dev --dart-define=FLAVOR=dev --export-options-plist=ios/ExportOptions/ExportOptions-app-store.plist --verbose
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:228:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      OperatingSystemUtils.getDirectorySize (package:flutter_tools/src/base/os.dart:111:53)
#5      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:528:43)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale ja-JP)
    • Flutter version 3.22.1 on channel stable at /Users/j-maruyama/fvm/versions/3.22.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (13 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/j-maruyama/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (4 available)
    • j-maruyamaのiPhone (mobile)      • 00008101-001A198C1A52001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.141

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.12.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 7de92e26534876a2db36e117315f048c9a74c7a1
### Plugins
app_settings-5.1.1
device_info_plus-10.1.0
file_picker-8.0.3
firebase_analytics-10.10.7
firebase_analytics_web-0.5.7+7
firebase_core-2.32.0
firebase_core_web-2.17.0
firebase_crashlytics-3.5.7
flutter_blue_plus-1.32.7
flutter_custom_tabs-2.0.0+1
flutter_custom_tabs_android-2.0.0+1
flutter_custom_tabs_ios-2.0.0
flutter_custom_tabs_web-2.0.0
flutter_native_splash-2.4.0
flutter_plugin_android_lifecycle-2.0.20
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
package_info_plus-8.0.0
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.6
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
share_plus-9.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
url_launcher-6.3.0
url_launcher_android-6.3.3
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1

**Comment by huycozy** [comment]
Could you try https://github.com/flutter/flutter/issues/119165#issuecomment-1405080216 to see if it helps?
