### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0

### ISSUE THREAD

**Issue by Abdurrahman2312** [flutter/flutter#149758]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:711:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:710:12)
#4      _runSync (package:flutter_tools/src/version.dart:852:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:436:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9

**Comment by LimaneGaya** [comment]
Hi @Abdurrahman2312, seems like it does't find git in you path variable. Do you have it installed and added to path?

**Comment by huycozy** [comment]
@Abdurrahman2312 Please check if you have installed and added git to your path.
