### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference

### ISSUE THREAD

**Issue by marchlqq** [flutter/flutter#149792]
### Steps to reproduce

1、update flutter version from 3.3.9 to 3.16.9
2、Open the phone settings and turn on the application password book function
3、create a viewpage fragment, one is native fragment and has edit, other is flutter fragment and init
then, 
When you click on the edit box of the native fragment, it will inevitably collapse and appear.

### Expected results

click normal

### Actual results

```console
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference
at io.flutter.embedding.android.FlutterView.onProvideAutofillVirtualStructure(FlutterView.java:1525)
at android.view.View.dispatchProvideStructure(View.java:10364)
at android.view.View.dispatchProvideAutofillStructure(View.java:10356)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3708)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:527)
at android.app.assist.AssistStructure.<init>(AssistStructure.java:2345)
at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:4101)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
### Code sample

<details open><summary>Code sample</summary>

```java
        fragmentList = new ArrayList<>();
        nativeFragment = new NativeFragment();

        addFragmentThenHide(R.id.fragment_stub, nativeFragment, "tab_" + 0);

        mesFragment = new MsgFlutterFragment
                .CachedEngineFragmentBuilder(MsgFlutterFragment.class)
                .url("tab_message")
                .build();

        addFragmentThenHide(R.id.fragment_stub, mesFragment, "tab_" + 2);

        friendFragment = new FriendFlutterFragment
                .CachedEngineFragmentBuilder(FriendFlutterFragment.class)
                .url("tab_friend")
                .build();
```

```dart

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[mtp_test_demo.zip](https://github.com/user-attachments/files/15604847/mtp_test_demo.zip)

</details>

### Logs

<details open><summary>Logs</summary>

```console
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference
at io.flutter.embedding.android.FlutterView.onProvideAutofillVirtualStructure(FlutterView.java:1525)
at android.view.View.dispatchProvideStructure(View.java:10364)
at android.view.View.dispatchProvideAutofillStructure(View.java:10356)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3708)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:527)
at android.app.assist.AssistStructure.<init>(AssistStructure.java:2345)
at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:4101)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by marchlqq** [comment]
FlutterView  method：
 public void onProvideAutofillVirtualStructure(@NonNull ViewStructure structure, int flags) {
        super.onProvideAutofillVirtualStructure(structure, flags);
        this.textInputPlugin.onProvideAutofillVirtualStructure(structure, flags);
    }


This method adds try-catch, which can be added, but it is difficult and there is no other way to deal with this problem.

**Comment by huycozy** [comment]
Hi @marchlqq 

>Open the phone settings and turn on the application password book function

What is `passwork book` function? Which Android device are you using? (OS, model)

Also, the goal of this Github repo is not to assist in personal code or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests. Your sample code ([mtp_test_demo.zip](https://github.com/user-attachments/files/15604847/mtp_test_demo.zip)) is a package project that contains the complex implementation and also uses 3rd packages. 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample and please provide output of `flutter doctor -v` as well.

**Comment by marchlqq** [comment]
hi @huycozy 
1、[演示视频](https://private-user-images.githubusercontent.com/9548501/337154973-77a5ccd7-e3fd-4659-a9ea-01b172b92952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjczNzUsIm5iZiI6MTcxNzY2NzA3NSwicGF0aCI6Ii85NTQ4NTAxLzMzNzE1NDk3My03N2E1Y2NkNy1lM2ZkLTQ2NTktYTllYS0wMWIxNzJiOTI5NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDk0NDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjk1ZmNlNjhiNzIzMmI2ODI0OWNlMjdjZWY1MTRiOGRiYzY3Y2ZiMGU2ZjZkZmVlZmQ1N2MyMTY1OTBjNzgxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EwgU5Yx-Jae3TVxoIOks5beBhuDq8ZihwyQAFgm6ozk)


2、Mobile phone: pad or folding screen mobile phone

**Comment by marchlqq** [comment]
Current demo：
[mtp_test_demo.zip](https://github.com/user-attachments/files/15604847/mtp_test_demo.zip)

A complete and minimal reproducible code example is not available yet.

**Comment by huycozy** [comment]
Please try to provide a minimal sample code so that we can look into it easier. Thanks!

**Comment by marchlqq** [comment]
> Please try to provide a minimal sample code so that we can look into it easier. Thanks!

The problem occurs when:
```
public void onProvideAutofillVirtualStructure(@nonnull ViewStructure structure, int flags) {
super.onProvideAutofillVirtualStructure(structure, flags);
this.textInputPlugin.onProvideAutofillVirtualStructure(structure, flags);
}
```
I clicked on the initial interface and the input method popped up, but because the system password book function was turned on, a rough code was run, but the textInputPlugin was not initialized, so it crashed.

I want to add try-catch to this method body.

**Comment by huycozy** [comment]
To help us look at the issue more easily, please narrow the issue down by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected code, and isolating the issue into a minimal sample code. And please share it here when you have such an example. Thanks!
