### ISSUE TITLE
_debugUltimatePreviousSiblingOf(after, equals : _firstChild)': is not true

### ISSUE THREAD

**Issue by ybmeng** [flutter/flutter#14971]
## Logs
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5983): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 5983): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2730:
I/flutter ( 5983): '_debugUltimatePreviousSiblingOf(after, equals : _firstChild)': is not true.
I/flutter ( 5983): 
I/flutter ( 5983): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5983): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5983): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5983):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5983): 
I/flutter ( 5983): When the exception was thrown, this was the stack:
I/flutter ( 5983): #2      RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2730)
I/flutter ( 5983): #3      RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2764)
I/flutter ( 5983): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209)
I/flutter ( 5983): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:849)
I/flutter ( 5983): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4470)
I/flutter ( 5983): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4240)
I/flutter ( 5983): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4610)
I/flutter ( 5983): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 5983): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 5983): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 5983): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 5983): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 5983): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 5983): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 5983): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 5983): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3916)
I/flutter ( 5983): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 5983): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 5983): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 5983): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741)
I/flutter ( 5983): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 5983): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 5983): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 5983): #31     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702)
I/flutter ( 5983): #32     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671)
I/flutter ( 5983): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #36     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4340)
I/flutter ( 5983): #37     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726)
I/flutter ( 5983): #38     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:187)
I/flutter ( 5983): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #66     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5983): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #78     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5983): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #84     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #90     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4340)
I/flutter ( 5983): #91     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726)
I/flutter ( 5983): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #95     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #105    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5983): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5983): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #115    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #119    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #123    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5983): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #127    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 5983): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5983): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5983): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5983): #131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225)
I/flutter ( 5983): #132    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621)
I/flutter ( 5983): #133    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter ( 5983): #134    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter ( 5983): #135    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter ( 5983): #136    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter ( 5983): #137    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter ( 5983): #138    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter ( 5983): (elided 2 frames from class _AssertionError)
I/flutter ( 5983): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5983): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2730: '_debugUltimatePreviousSiblingOf(after, equals : _firstChild)': is not true.
I/chatty  ( 5983): uid=10071(u0_a71) ui_thread identical 1 line
I/flutter ( 5983): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2730: '_debugUltimatePreviousSiblingOf(after, equals : _firstChild)': is not true.
I/flutter ( 5983): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480: 'owner._debugCurrentBuildTarget == this': is not true.
I/chatty  ( 5983): uid=10071(u0_a71) ui_thread identical 15 lines
I/flutter ( 5983): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3480: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5983): Another exception was thrown: type 'RenderErrorBox' is not a subtype of type 'RenderSemanticsGestureHandler' of 'semanticsGestureHandler' where

**Comment by ybmeng** [comment]
Code snippet:

onExpansionChanged: (isExpanded) {
          // Keep element alive if it's expanded.
          if (isExpanded) {
            new KeepAliveNotification(_keepAliveHandle = new KeepAliveHandle()).dispatch(context);
          } else if (_keepAliveHandle != null) {
            _keepAliveHandle.release();
            _keepAliveHandle.dispose();
            _keepAliveHandle = null;
          }
        }, // onExpansionChanged.

**Comment by ybmeng** [comment]
Nvm, I need to do more debugging. I'm adding to a list and rerendering, and that breaks the notification.
