### ISSUE TITLE
[flutter_markdown] Null check operator used on a null value in MarkdownBuilder._buildRichText.<fn>(builder.dart:957)

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#149817]
(Same issue as #146282 which was reported back in April and closed by bot)

After updating my production app I've been getting crashlytics reports:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown .
       at MarkdownBuilder._buildRichText.<fn>(builder.dart:957)
       at _SelectableTextState._handleSelectionChanged(selectable_text.dart:628)
       at EditableTextState._handleSelectionChanged(editable_text.dart:3976)
       at EditableTextState._formatAndSetValue(editable_text.dart:4184)
       at EditableTextState.userUpdateTextEditingValue(editable_text.dart:4554)
       at RenderEditable._setTextEditingValue(editable.dart:719)
       at RenderEditable._setSelection(editable.dart:738)
       at RenderEditable.selectWordsInRange(editable.dart:2117)
       at RenderEditable.selectWord(editable.dart:2098)
       at _SelectableTextSelectionGestureDetectorBuilder.onSingleLongTapStart(selectable_text.dart:105)
       at _TextSelectionGestureDetectorState._handleLongPressStart(text_selection.dart:3332)
       at LongPressGestureRecognizer._checkLongPressStart.<fn>(long_press.dart:703)
       at GestureRecognizer.invokeCallback(recognizer.dart:344)
       at LongPressGestureRecognizer._checkLongPressStart(long_press.dart:703)
       at LongPressGestureRecognizer.didExceedDeadline(long_press.dart:607)
       at PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent(recognizer.dart:724)
       at PrimaryPointerGestureRecognizer.addAllowedPointer.<fn>(recognizer.dart:667)   
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown .
       at MarkdownBuilder._buildRichText.<fn>(builder.dart:957)
       at _SelectableTextState._handleSelectionChanged(selectable_text.dart:628)
       at EditableTextState._handleSelectionChanged(editable_text.dart:3976)
       at EditableTextState._formatAndSetValue(editable_text.dart:4184)
       at EditableTextState.userUpdateTextEditingValue(editable_text.dart:4554)
       at RenderEditable._setTextEditingValue(editable.dart:719)
       at RenderEditable._setSelection(editable.dart:738)
       at RenderEditable.selectPositionAt(editable.dart:2088)
       at RenderEditable.selectPosition(editable.dart:2065)
       at _SelectableTextSelectionGestureDetectorBuilder.onSingleTapUp(selectable_text.dart:145)
       at _TextSelectionGestureDetectorState._handleTapUp(text_selection.dart:3299)
       at BaseTapAndDragGestureRecognizer._checkTapUp.<fn>(tap_and_drag.dart:1198)
       at GestureRecognizer.invokeCallback(recognizer.dart:344)
       at BaseTapAndDragGestureRecognizer._checkTapUp(tap_and_drag.dart:1198)
       at BaseTapAndDragGestureRecognizer.acceptGesture(tap_and_drag.dart:996)
       at GestureArenaManager.sweep(arena.dart:167)
       at GestureBinding.handleEvent(binding.dart:499)
       at GestureBinding.dispatchEvent(binding.dart:475)
       at RendererBinding.dispatchEvent(binding.dart:425)
       at GestureBinding._handlePointerEventImmediately(binding.dart:420)
       at GestureBinding.handlePointerEvent(binding.dart:383)
       at GestureBinding._flushPointerEventQueue(binding.dart:330)
       at GestureBinding._handlePointerDataPacket(binding.dart:299)
```

I'm unsure where in my app this is being generated as the stacktrace seems entirely outside of my codebase. So until these customers contact me and report where in the app the problem is occurring I'm unable to create a reproducible example. As this issue was reported back in #146282 with the same error it seems to be a genuine bug. They highlighted the code:

![319922844-39632c84-49c0-4d4a-b2c5-78a1c38e4a3c](https://github.com/flutter/flutter/assets/298850/ec39f5a4-1f44-4ca6-ad71-69eb232d5819)

It looks like `onSelectionChanged` is not always set?

<details>
<summary>Flutter doctor</summary>

```

[✓] Flutter (Channel stable, 3.22.1, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
    • Flutter version 3.22.1 on channel stable at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.89.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Pixel 5 (mobile)                • 09021FDD40027X        • android-arm64  • Android 14 (API 34)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by jimmyff** [comment]
@bogdannedelcu Did you get any further with your original issue reporting this? #146282

**Comment by bogdannedelcu** [comment]
That parameter which is optional should be set. Then no more errors like
this.

It is indeed a bug in the code. Either correct the code or add mandatory to
the parameter.

În joi, 6 iun. 2024 la 17:42 Jimmy Forrester-Fellowes <
***@***.***> a scris:

**Comment by jsoberan** [comment]
I've confirmed that setting the onSelectionChanged parameter fixes the exception.

**Comment by darshankawar** [comment]
@jimmyff Please check above possible solution and see if it helps in your case or not.

**Comment by jimmyff** [comment]
I'll add the parameter but also sent a PR with the fix

**Comment by darshankawar** [comment]
I observed a similar error log upon running below code sample and while trying to select text from the code blocks:

```
======== Exception caught by widgets ===============================================================
The following _TypeError was thrown while calling onSelectionChanged for SelectionChangedCause.longPress:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      MarkdownBuilder._buildRichText.<anonymous closure> (package:flutter_markdown/src/builder.dart:966:35)
#1      _SelectableTextState._handleSelectionChanged (package:flutter/src/material/selectable_text.dart:628:32)
#2      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:3972:34)
#3      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:4180:7)
#4      EditableTextState.userUpdateTextEditingValue (package:flutter/src/widgets/editable_text.dart:4550:5)
#5      RenderEditable._setTextEditingValue (package:flutter/src/rendering/editable.dart:719:27)
#6      RenderEditable._setSelection (package:flutter/src/rendering/editable.dart:738:5)
#7      RenderEditable.selectWordsInRange (package:flutter/src/rendering/editable.dart:2117:5)
#8      RenderEditable.selectWord (package:flutter/src/rendering/editable.dart:2098:5)
#9      _SelectableTextSelectionGestureDetectorBuilder.onSingleLongTapStart (package:flutter/src/material/selectable_text.dart:105:20)
#10     _TextSelectionGestureDetectorState._handleLongPressStart (package:flutter/src/widgets/text_selection.dart:3332:35)
#11     LongPressGestureRecognizer._checkLongPressStart.<anonymous closure> (package:flutter/src/gestures/long_press.dart:703:75)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#13     LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:703:11)
#14     LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:607:5)
#15     PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:724:5)
#16     PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:667:41)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
D/EGL_emulation(14808): app_time_stats: avg=9575.93ms min=10.24ms max=19141.63ms count=2



```

<details>
<summary> code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SelectionArea(
          child: Center(
            child: MarkdownBody(
              selectable: true,
              data: '''
# Hello, Markdown!

`sudo dnf install xorg-x11-xauth`

```
env XDG_SESSION_TYPE=x11 <app>
```
''',
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>
