### ISSUE TITLE
Failed build for Web app with Flutter 3.22.2

### ISSUE THREAD

**Issue by lyskouski** [flutter/flutter#149962]
### Steps to reproduce

flutter build -v web --profile --no-tree-shake-icons --base-href="/app/"

### Expected results

Build is succeed 

### Actual results

Error: Failed to compile application for the Web.

### Code sample

<details open><summary>Code sample</summary>

Assume, sample project can be used `flutter create .`

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

Full log: https://github.com/lyskouski/app-finance/actions/runs/9428619608/job/25974160308

```console
 [   +5 ms] executing: /opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/opt/hostedtoolcache/flutter/stable-3.22.2-x64/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.profile=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/ -DFLUTTER_WEB_AUTO_DETECT=true --native-null-assertions --no-source-maps -o /home/runner/work/app-finance/app-finance/.dart_tool/flutter_build/6b1d7e5a1efdc7cd7360f598adcfc7a0/app.dill --packages=.dart_tool/package_config.json --cfe-only /home/runner/work/app-finance/app-finance/.dart_tool/flutter_build/6b1d7e5a1efdc7cd7360f598adcfc7a0/main.dart
[+19022 ms] ../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:119:50:
            Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
             - 'Iterable' is from 'dart:core'.
                    for (final track in _srcObject!.jsStream.getVideoTracks()) {
                                                             ^
            ../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:125:50:
            Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
             - 'Iterable' is from 'dart:core'.
                    for (final track in _srcObject!.jsStream.getAudioTracks()) {
                                                             ^
            ../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:167:50:
            Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
             - 'Iterable' is from 'dart:core'.
                    for (final track in _srcObject!.jsStream.getVideoTracks()) {
                                                             ^
            ../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.9.48+hotfix.1/lib/src/web/rtc_video_renderer_impl.dart:175:50:
            Error: The type 'JSArray<MediaStreamTrack>' used in the 'for' loop must implement 'Iterable<dynamic>'.
             - 'Iterable' is from 'dart:core'.
                    for (final track in _srcObject!.jsStream.getAudioTracks()) {
                                                             ^
            Error: Compilation failed.

...

 [  +10 ms] Compiling lib/main.dart for the Web... (completed in 19.4s)
[        ] "flutter web" took 22,031ms.
[   +2 ms] Error: Failed to compile application for the Web.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:129:7)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
[        ] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on KDE neon 6.0 6.5.0-35-generic, locale C.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/vlyskouski/Programs/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 дня назад), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/vlyskouski/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/vlyskouski/Programs/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.29.0
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/vlyskouski/Programs/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/vlyskouski/Programs/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.90.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.89.1)
    • VS Code at /var/lib/flatpak/app/com.visualstudio.code/x86_64/stable/active/files/extra/vscode
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • KDE neon 6.0 6.5.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 125.0.6422.141 snap

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by bartekpacia** [comment]
This looks like a problem with https://pub.dev/packages/flutter_webrtc, not with Flutter

**Comment by lyskouski** [comment]
Reverted [flutter_webrtc](https://pub.dev/packages/flutter_webrtc), succeeded. My concern was regarding deviations between `flutter build` (fail) and `flutter run` (success). Thanks
