### ISSUE TITLE
Path Error when running on IOS '/Users/avinashkasukurthi/Developer/firebase.json'  (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by AvinashKasukurthi** [flutter/flutter#149994]
### Steps to reproduce

Run Flutter Run or Run build from Xcode

### Expected results

We need to get the build.

### Actual results

PathNotFoundException: Cannot open file, path = '/Users/avinashkasukurthi/Developer/firebase.json' (OS Error: No such file or directory, errno = 2)
    #0      _checkForErrorResponse (dart:io/common.dart:55:9)
    #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
    <asynchronous suspension>
    #2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
    <asynchronous suspension>
    #3      _File.readAsString (dart:io/file_impl.dart:621:18)
    <asynchronous suspension>
    #4      appleConfigFromFirebaseJson (package:flutterfire_cli/src/common/utils.dart:286:7)
    <asynchronous suspension>
    #5      UploadCrashlyticsSymbols._getConfigurationFromFirebaseJsonFile (package:flutterfire_cli/src/commands/upload_symbols.dart:278:9)
    <asynchronous suspension>
    #6      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:331:34)
    <asynchronous suspension>
    #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
    <asynchronous suspension>
    #8      main (file:///Users/avinashkasukurthi/.pub-cache/hosted/pub.dev/flutterfire_cli-1.0.0/bin/flutterfire.dart:63:5)
    <asynchronous suspension>
    Command PhaseScriptExecution failed with a nonzero exit code

### Code sample

// Error not related to code

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
UNINSTALLED_PRODUCTS_DIR\=/Users/avinashkasukurthi/Library/Developer/Xcode/DerivedData/Runner-eennggqhgqntmibjfuuehxxwpsqb/Build/Intermediates.noindex/Un
                            installedProducts
                            export UNLOCALIZED_RESOURCES_FOLDER_PATH\=Runner.app
                            export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_NO\=Runner.app/Resources
                            export UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_YES\=Runner.app
                            export UNSTRIPPED_PRODUCT\=NO
                            export USER\=avinashkasukurthi
                            export USER_APPS_DIR\=/Users/avinashkasukurthi/Applications
                            export USER_LIBRARY_DIR\=/Users/avinashkasukurthi/Library
                            export USE_DYNAMIC_NO_PIC\=YES
                            export USE_HEADERMAP\=YES
                            export USE_HEADER_SYMLINKS\=NO
                            export USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES\=YES
                            export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
                            export VALIDATE_PRODUCT\=NO
                            export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
                            export VERBOSE_PBXCP\=NO
                            export VERBOSE_SCRIPT_LOGGING\=YES
                            export VERSIONING_SYSTEM\=apple-generic
                            export VERSIONPLIST_PATH\=Runner.app/version.plist
                            export VERSION_INFO_BUILDER\=avinashkasukurthi
                            export VERSION_INFO_FILE\=Runner_vers.c
                            export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:Runner\ \ PROJECT:Runner-92\"
                            export WRAPPER_EXTENSION\=app
                            export WRAPPER_NAME\=Runner.app
                            export WRAPPER_SUFFIX\=.app
                            export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
                            export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
                            export XCODE_PRODUCT_BUILD_VERSION\=15F31d
                            export XCODE_VERSION_ACTUAL\=1540
                            export XCODE_VERSION_MAJOR\=1500
                            export XCODE_VERSION_MINOR\=1540
                            export XPCSERVICES_FOLDER_PATH\=Runner.app/XPCServices
                            export YACC\=yacc
                            export _WRAPPER_CONTENTS_DIR_SHALLOW_BUNDLE_NO\=/Contents
                            export _WRAPPER_PARENT_PATH_SHALLOW_BUNDLE_NO\=/..
                            export _WRAPPER_RESOURCES_DIR_SHALLOW_BUNDLE_NO\=/Resources
                            export __IS_NOT_MACOS\=YES
                            export __IS_NOT_MACOS_macosx\=NO
                            export __IS_NOT_SIMULATOR\=NO
                            export __IS_NOT_SIMULATOR_simulator\=NO
                            export arch\=undefined_arch
                            export variant\=normal
                            /bin/sh -c

/Users/avinashkasukurthi/Library/Developer/Xcode/DerivedData/Runner-eennggqhgqntmibjfuuehxxwpsqb/Build/Intermediates.noindex/Runner.build/Debug-iphonesim
                            ulator/Runner.build/Script-CA95B0AF52816A7D9A1538AF.sh
                        Unhandled exception:
                        PathNotFoundException: Cannot open file, path = '/Users/avinashkasukurthi/Developer/firebase.json' (OS Error: No such file or directory,
errno = 2)
                        #0      _checkForErrorResponse (dart:io/common.dart:55:9)
                        #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
                        <asynchronous suspension>
                        #2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
                        <asynchronous suspension>
                        #3      _File.readAsString (dart:io/file_impl.dart:621:18)
                        <asynchronous suspension>
                        #4      appleConfigFromFirebaseJson (package:flutterfire_cli/src/common/utils.dart:286:7)
                        <asynchronous suspension>
                        #5      UploadCrashlyticsSymbols._getConfigurationFromFirebaseJsonFile (package:flutterfire_cli/src/commands/upload_symbols.dart:278:9)
                        <asynchronous suspension>
                        #6      UploadCrashlyticsSymbols.run (package:flutterfire_cli/src/commands/upload_symbols.dart:331:34)
                        <asynchronous suspension>
                        #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                        <asynchronous suspension>
                        #8      main (file:///Users/avinashkasukurthi/.pub-cache/hosted/pub.dev/flutterfire_cli-1.0.0/bin/flutterfire.dart:63:5)
                        <asynchronous suspension>
                        Command PhaseScriptExecution failed with a nonzero exit code
                    
                        warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any
outputs. To address this
                        warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency
analysis" in the script
                        phase. (in target 'abseil' from project 'Pods')
                        warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any
outputs. To address this
                        warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency
analysis" in the script
                        phase. (in target 'gRPC-Core' from project 'Pods')
                        warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any
outputs. To address this
                        warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency
analysis" in the script
                        phase. (in target 'gRPC-C++' from project 'Pods')
                    
                        Result bundle written to path:
                                /var/folders/vv/l96pnk5d49z96x0w400w0r0m0000gn/T/flutter_tools.n3SbfA/flutter_ios_build_temp_diruYSCsl/temporary_xcresult_bundle
                    
                    
[ +381 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone 15 Pro.
[   +4 ms] "flutter run" took 59,777ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:840:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +119 ms] ensureAnalyticsSent: 119ms
[        ] Running 1 shutdown hook
[  +27 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
[✓] VS Code (version 1.90.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
It seems you are hitting https://github.com/invertase/flutterfire_cli/issues/284. You can check that issue to see if it's a similar bug to your case. Otherwise, please file another issue on flutterfire_cli repository for better support there. 

Closing this as it doesn't seem to be a Flutter framework or 1st party package issue.
