### ISSUE TITLE
Updated layout information required for RenderIndexedSemantics#99262 NEEDS-LAYOUT to calculate semantics.

### ISSUE THREAD

**Issue by gautamkell** [flutter/flutter#150087]
### Steps to reproduce

I'm using StaggeredGridView.countBuilder(
with obx list which will be updated onInit API response
staggeredTileBuilder: (index) => const StaggeredTile.fit(1),
                  mainAxisSpacing: 14,
                  crossAxisSpacing: 14,
                  crossAxisCount: 2,
                  controller: scrollController,
                  padding: EdgeInsets.zero,
                  physics: !exploreController.isFloatingTapped.value
                      ? const NeverScrollableScrollPhysics()
                      : const ScrollPhysics(),
                  itemCount: exploreDiscoverController
                          .discoverFeedItemList.isEmpty
                      ? 0
                      : exploreDiscoverController.discoverFeedItemList.length +
                          1,

### Expected results

There should not be render box error as I'm getting list response from the API and updating the View based on that.

### Actual results

Updated layout information required for RenderIndexedSemantics#99262 NEEDS-LAYOUT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 3649 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3649:12)
object.dart:3649
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#4      Iterable.forEach (dart:core/iterable.dart:347:35)
iterable.dart:347
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
sliver_variable_size_box_adaptor.dart:296
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#13     Iterable.forEach (dart:core/iterable.dart:347:35)
iterable.dart:347
#14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:314:10)
viewport.dart:314
#15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#17     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#18     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#19     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3612:11)
proxy_box.dart:3612
#20     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#21     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#22     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#23     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#24     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4281:11)
proxy_box.dart:4281
#25     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#26     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#27     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#28     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#29     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#30     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#31     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#32     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#33     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#34     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#35     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#36     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#37     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#38     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3665:61)
object.dart:3665
#39     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4081:14)
object.dart:4081
#40     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3806:5)
object.dart:3806
#41     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3663:5)
object.dart:3663
#42     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3615:41)
object.dart:3615
#43     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
object.dart:1303
#44     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
object.dart:1308
#45     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:589:25)
binding.dart:589
#46     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:991:13)
binding.dart:991
#47     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
binding.dart:448
#48     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
binding.dart:1386
#49     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
binding.dart:1311
#50     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
binding.dart:1169
#51     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
platform_dispatcher.dart:399
#53     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
`flutter_staggered_grid_view` is a third-party package and so is `getx`. Any issues you face using the packages should be reported on their repo. 

Closing from here as this is caused by the use of third-party packages. 

Thank you
