### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Program Files\Java\jdk-20\bin\bin\java" in the search path. Command: C:\Program Files\Java\jdk-20\bin\bin\java, OS error code: 0

### ISSUE THREAD

**Issue by ReyDev2009** [flutter/flutter#150077]
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Program Files\Java\jdk-20\bin\bin\java" in the search path. Command: C:\Program Files\Java\jdk-20\bin\bin\java, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:714:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:713:12)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:377:51)
#5      Java.version.<anonymous closure> (package:flutter_tools/src/android/java.dart:139:44)
#6      Java.version (package:flutter_tools/src/android/java.dart:179:5)
#7      Java.version (package:flutter_tools/src/android/java.dart)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:510:41)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Versi¢n 10.0.19045.4291], locale es-US)
    • Flutter version 3.16.3 on channel stable at C:\SDKFlutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 months ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] VS Code (version 1.90.0)
    • VS Code at C:\Users\ReyDev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.4291]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0366e0a3f089e15fd89c97604ab402fe26b724c

**Comment by huycozy** [comment]
This is similar to https://github.com/flutter/flutter/issues/139180 and should be fixed on new versions. Please try upgrading your Flutter SDK and retry. 

I will close this as fixed. If you still experience this on the latest Flutter stable 3.22.2, please write in comments and I will reopen this.
