### ISSUE TITLE
When using FlexibleSpaceBar, Dart returns "Null check operator used on a null value error"

### ISSUE THREAD

**Issue by IbrahimTalha0** [flutter/flutter#150054]
### 1. Create AppTextTheme and especially add this code line .apply(bodyColor: something):
like this: ".apply(fontFamily: "Poppins", bodyColor: AppColorLight.textColor"

### 2. Implement textTheme to Material App
`MaterialApp(
      title: 'Wincoi',
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      home: MessagesPage(),
    );`
### Expected results

It was supposed to be no error.

### Actual results

![simulator_screenshot_F173A169-7C3F-46D3-9B8A-EA78879801A1](https://github.com/flutter/flutter/assets/75858218/6c722c8d-fe0b-4eac-ac61-d41f0e66fef7)

The error is returned:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building LayoutBuilder:
Null check operator used on a null value

The relevant error-causing widget was:
    FlexibleSpaceBar FlexibleSpaceBar:file:///Users/ibrahimtalhademir/Project/wincoi_user_mobile_app/lib/view/pages/main_bottom_bar/messages/messages_page.dart:15:28

When the exception was thrown, this was the stack:
#0      _FlexibleSpaceBarState.build.<anonymous closure> (package:flutter/src/material/flexible_space_bar.dart:327:38)
#1      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:139:77)
#2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:19)
#3      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:173:12)
#4      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688:59)
#5      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
#6      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688:14)
#7      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:248:7)
#8      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:331:5)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#14     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#15     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:574:43)
#16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:601:12)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#29     RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:242:12)
#30     RenderSliverScrollingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:373:5)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#32     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
#33     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
#34     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#48     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#49     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#50     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#51     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#56     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#64     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#65     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:574:43)
#66     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:601:12)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#79     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3712:13)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#83     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974:13)
#84     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288:9)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#106    RenderView.performLayout (package:flutter/src/rendering/view.dart:244:14)
#107    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
#108    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
#109    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
#110    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
#111    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
#112    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#113    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#114    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#115    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1035:9)
#116    PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#120    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 1241 libraries in 317ms (compile: 15 ms, reload: 81 ms, reassemble: 122 ms).

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
```

### Code sample

<details open><summary></summary>

```dart
final class AppTextSize {
static const double xLargeSize = 30;
static const double largeXSize = 23;
static const double largeSize = 20;
static const double xMedium = 18;
static const double mediumSize = 16;
static const double smallSize = 14;
static const double xSmallSize = 12;
static const double xxSmallSize = 10;
}

class AppText {
static const appTextSize = AppTextSize;

static TextTheme get textThemeLight => const TextTheme(
displayLarge: TextStyle(fontSize: AppTextSize.xLargeSize),
displayMedium: TextStyle(fontSize: AppTextSize.largeSize),
bodyLarge: TextStyle(fontSize: AppTextSize.mediumSize),
bodyMedium: TextStyle(fontSize: AppTextSize.smallSize),
bodySmall: TextStyle(fontSize: AppTextSize.xSmallSize),
headlineSmall: TextStyle(fontSize: AppTextSize.xxSmallSize),
).apply(fontFamily: "Poppins", bodyColor: AppColorLight.textColor);
}

MaterialApp( title: 'Wincoi', theme: AppTheme.lightTheme, debugShowCheckedModeBanner: false, home: MessagesPage(), );

class MessagesPage extends StatelessWidget {
  const MessagesPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          const SliverAppBar(
            expandedHeight: 150,
            backgroundColor: AppColorLight.primaryColor,
            flexibleSpace: FlexibleSpaceBar(
              background: Center(
                child: Text(
                  "Messages",
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                  ),
                ),
              ),
              centerTitle: false,
              titlePadding: EdgeInsets.all(10),
              title: Text("Messages"),
            ),
          ),
          SliverList.builder(itemBuilder: (context, index) {
            return const ListTile(
              title: Text("Messages"),
            );
          }),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-TR)
    • Flutter version 3.22.1 on channel stable at
      /Users/ibrahimtalhademir/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ibrahimtalhademir/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • FA45ADA6-09B0-40B0-97C5-3C0636C79F9E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64
      • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin
      • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by nate-thegrate** [comment]
Thanks for the bug report and pull request! Unfortunately, I haven't able to reproduce this error on the latest `master` or `stable` branches.

The code sample above doesn't include the `AppTheme` or `AppColorLight` classes, so I switched the references out for `ThemeData(textTheme: AppText.textThemeLight)` and `Colors.lightBlue` respectively.

Here's a DartPad link that runs the app without any problems: https://dartpad.dev/?id=be83860280487f3f0063bb533760b01d
Could you let me know what needs to be changed to trigger that null check error?

**Comment by darshankawar** [comment]
Thanks for verifying @nate-thegrate 
I also couldn't replicate the reported error running on Android and iOS with the code you provided, as @IbrahimTalha0, your code sample seemed incomplete. Please provide runnable code that triggers the crash.
