### ISSUE TITLE
Flutter and cloud_firestore - is not a subtype of type

### ISSUE THREAD

**Issue by defaultbr** [flutter/flutter#15007]
## Steps to Reproduce

```
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import './Screens/home.dart';



Future query() async {
  DocumentSnapshot result = await Firestore.instance.collection('dummydocs').document("doc1").get();
  print("RESULT: " + result.data.toString());
}

void main() {
  query();
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Home(title:"Nothing Special"),
    );
  }
}
```

## Logs

```
03-01 00:24:42.975 7906-7926/com.project E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, dynamic>' where
      _InternalLinkedHashMap is from dart:collection
      Map is from dart:core
      String is from dart:core
    
    #0      DocumentReference.get (file:///home/tarcisio/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.2.9/lib/src/document_reference.dart)
    <asynchronous suspension>
    #1      query (file:///home/tarcisio/AndroidStudioProjects/test_flutter/lib/main.dart:10:87)
    <asynchronous suspension>
    #2      main (file:///home/tarcisio/AndroidStudioProjects/test_flutter/lib/main.dart:15:3)
    #3      _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
    #4      _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
```

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

-> No Issues found!

**Comment by defaultbr** [comment]
@Purus 

i did another collection to test and same error:
```
- Collection ("example")
-- Document (''test")
--- field: "field_text"
```
```
    DocumentSnapshot result = await Firestore.instance.collection('example')
        .document("test")
    .get();
```

and keep the same error

**Comment by defaultbr** [comment]
solved in version 0.2.10 (i was using 0.2.9)

changes -> https://github.com/flutter/plugins/commit/915e260d97ac6af1268c5243c7300aca44cb86bf


thanks guys =) that was fast

**Comment by Asoseil** [comment]
same problem, is there any workaround?

**Comment by jmrboosties** [comment]
Sorry for the late response, I had avoided this issue and worked on some other stuff in the project for a while. I think I figured out a fix, but it's extremely goofy...

```
Map<String, dynamic> mapJson = document.data;
new MyObject.fromJson(json.decode(json.encode(mapJson))));
```

¯\_(ツ)_/¯

**Comment by kroikie** [comment]
@defaultbr

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/899. Any further collaboration will be done there.
