### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by Sajalreef** [flutter/flutter#150189]
## Command
```
flutter run -d chrome --web-renderer html
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/tools/shader_compiler.dart:190:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:218:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:185:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:991:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:562:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:322:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22621.3672], locale
    en-US)
    [32m•[39m Flutter version 3.22.0 on channel stable at D:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5dcb86f68f (5 weeks ago), 2024-05-09 07:39:20 -0500
    [32m•[39m Engine revision f6344b75dc
    [32m•[39m Dart version 3.4.0
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.8.34316.72
    [32m•[39m Windows 10 SDK version 10.0.22621.0
    [31m✗[39m The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual
      Studio.

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m VS Code (version 1.72.2)
    [32m•[39m VS Code at C:\Users\High Tech\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22621.3672]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.142
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
cloud_firestore-4.17.4
cloud_firestore_web-3.12.4
file_saver-0.2.12
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+1
firebase_auth-4.19.6
firebase_auth_web-5.11.6
firebase_core-2.31.1
firebase_core_web-2.17.0
firebase_storage-11.7.6
firebase_storage_web-3.9.6
flutter_plugin_android_lifecycle-2.0.19
image_picker-1.1.1
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.11+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_web-3.1.1
image_picker_windows-0.2.1+1
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1

**Comment by danagbemava-nc** [comment]
Hi @Sajalreef, does this issue persist on subsequent run(s) or only once? If you can reproduce it anytime, can you share the entire output of `flutter run -v -d chrome`?
