### ISSUE TITLE
[rfw] golden test disabled due to blocking flutter->packages roller

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#150127]
[Implement Material properties](https://github.com/flutter/packages/blob/main/packages/rfw/test/material_widgets_test.dart#L521) test is failing due to the golden file:

```
00:16 +106 -1: /b/s/w/ir/x/w/packages/packages/rfw/test/material_widgets_test.dart: Implement Material properties                                                                                      
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "goldens/material_test.material_properties.png": Pixel test failed, 0.00%, 2px diff detected.
Failure feedback can be found at /b/s/w/ir/x/w/packages/packages/rfw/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:106:5)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
#3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
<asynchronous suspension>
<asynchronous suspension>
#5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///b/s/w/ir/x/w/packages/packages/rfw/test/material_widgets_test.dart:566:5)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)
```

Also see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8745322292877407601/+/u/Run_package_tests/custom_tests/stdout?format=raw

Test is now skipped to unblock the roller.

**Comment by bparrishMines** [comment]
cc @Hixie

**Comment by stuartmorgan** [comment]
(This is the flutter->packages version of https://github.com/flutter/tests/pull/375)
