### ISSUE TITLE
%5Btool_crash%5D ProcessException%3A Process exited abnormally with exit code -10%3A%0A Command%3A xcrun%2C OS error code%3A -10

### ISSUE THREAD

**Issue by mazab99** [flutter/flutter#150104]
flutter create .

Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally with exit code -10:

  Command: xcrun xcodebuild -list".

**Comment by darshankawar** [comment]
@mazab99 
Can you provide complete exception log in properly formatted text along with `flutter doctor -v` ?

**Comment by mazab99** [comment]
mahmoudazab@192 jalisa_user % flutter create .                                                

Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally with exit code -10:

  Command: xcrun xcodebuild -list".
A crash report has been written to /Volumes/D/Programming/My Work/Flutter Apps/HighQ Apps/1 - Clean
Arch/jalisa_user/flutter_01.log
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+Process+exited+abnormally+with+exit+code+-10%3A%0A%0A++Command%3A+xcrun+xcodebuild+-list

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ProcessException%3A+Process+exited+abnormally+with+exit+code+-10%3A%0A+Command%3A+xcrun%2C+OS+error+code%3A+-10&body=%23%23+Command%0A%60%60%60%0Aflutter+create+.%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AProcessException%3A+Process+exited+abnormally+with+exit+code+-10%3A%0A+Command%3A+xcrun%2C+OS+error+code%3A+-10%0A%60%60%60%0A%230++++++RunResult.throwException+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A125%3A5%29%0A%231++++++_DefaultProcessUtils.run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fprocess.dart%3A321%3A19%29%0A%3Casynchronous+suspension%3E%0A%232++++++XcodeProjectInterpreter.getInfo+%28package%3Aflutter_tools%2Fsrc%2Fios%2Fxcodeproj.dart%3A342%3A30%29%0A%3Casynchronous+suspension%3E%0A%233++++++IosProject.projectInfo+%28package%3Aflutter_tools%2Fsrc%2Fxcode_project.dart%3A452%3A29%29%0A%3Casynchronous+suspension%3E%0A%234++++++IosProject.productBundleIdentifier+%28package%3Aflutter_tools%2Fsrc%2Fxcode_project.dart%3A253%3A36%29%0A%3Casynchronous+suspension%3E%0A%235++++++FlutterProject.organizationNames+%28package%3Aflutter_tools%2Fsrc%2Fproject.dart%3A143%3A42%29%0A%3Casynchronous+suspension%3E%0A%236++++++CreateBase.getOrganization+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%3A258%3A49%29%0A%3Casynchronous+suspension%3E%0A%237++++++CreateCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate.dart%3A261%3A33%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1394%3A27%29%0A%3Casynchronous+suspension%3E%0A%239++++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%2310+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A372%3A9%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A153%3A19%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B33m%5B%21%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.22.2%2C+on+macOS+14.4+23E214+darwin-x64%2C+locale+en-EG%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.22.2+on+channel+stable+at+%2FUsers%2Fmahmoudazab%2FDeveloper%2Fflutter%0A++++%1B%5B33m%21%1B%5B39m+Warning%3A+%60dart%60+on+your+path+resolves+to+%2Fusr%2Flocal%2FCellar%2Fdart%2F3.3.4%2Flibexec%2Fbin%2Fdart%2C+which+is+not+inside%0A++++++your+current+Flutter+SDK+checkout+at+%2FUsers%2Fmahmoudazab%2FDeveloper%2Fflutter.+Consider+adding%0A++++++%2FUsers%2Fmahmoudazab%2FDeveloper%2Fflutter%2Fbin+to+the+front+of+your+path.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+761747bfc5+%287+days+ago%29%2C+2024-06-05+22%3A15%3A13+%2B0200%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+edd8546116%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+3.4.3%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.34.3%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+If+those+were+intentional%2C+you+can+disregard+the+above+warnings%3B+however+it+is+recommended+to+use+%22git%22%0A++++++directly+to+perform+update+checks+and+upgrades.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+34.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+%2FUsers%2Fmahmoudazab%2FLibrary%2FAndroid%2Fsdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-34%2C+build-tools+34.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+%2FApplications%2FAndroid+Studio.app%2FContents%2Fjbr%2FContents%2FHome%2Fbin%2Fjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.10%2B0-17.0.10b1087.21-11572160%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Xcode+-+develop+for+iOS+and+macOS+%28Xcode+15.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Xcode+at+%2FApplications%2FXcode.app%2FContents%2FDeveloper%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Build+15E204a%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+CocoaPods+version+1.15.2%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Chrome+-+develop+for+the+web+%28Cannot+find+Chrome+executable+at+%2FApplications%2FGoogle%0A++++Chrome.app%2FContents%2FMacOS%2FGoogle+Chrome%29%0A++++%1B%5B33m%21%1B%5B39m+Cannot+find+Chrome.+Try+setting+CHROME_EXECUTABLE+to+a+Chrome+executable.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2023.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+%2FApplications%2FAndroid+Studio.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.10%2B0-17.0.10b1087.21-11572160%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.90.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+%2FApplications%2FVisual+Studio+Code.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.90.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.88.1%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+%2FVolumes%2FD%2FMahmoud%2FPrograms%2FIOS%2FMac%2FVisual+Studio+Code.app%2FContents%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.90.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%282+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+sdk+gphone64+x86+64+%28mobile%29+%E2%80%A2+emulator-5554+%E2%80%A2+android-x64+%E2%80%A2+Android+14+%28API+34%29+%28emulator%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+macOS+%28desktop%29++++++++++++++%E2%80%A2+macos+++++++++%E2%80%A2+darwin-x64++%E2%80%A2+macOS+14.4+23E214+darwin-x64%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Network+resources%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+expected+network+resources+are+available.%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+ba393198430278b6595976de84fe170f553cc728%0A%23%23%23+Plugins%0Aamplitude_flutter-3.16.2%0Aandroid_id-0.4.0%0Aaudio_session-0.1.19%0Aconnectivity_plus-6.0.3%0Adevice_info_plus-10.1.0%0Afile_picker-8.0.5%0Afile_selector_linux-0.9.2%2B1%0Afile_selector_macos-0.9.4%0Afile_selector_windows-0.9.3%2B1%0Afirebase_core-3.1.0%0Afirebase_core_web-2.17.2%0Afirebase_messaging-15.0.1%0Afirebase_messaging_web-3.8.9%0Aflutter_app_badger-1.5.0%0Aflutter_keyboard_visibility-5.4.1%0Aflutter_keyboard_visibility_linux-1.0.0%0Aflutter_keyboard_visibility_macos-1.0.0%0Aflutter_keyboard_visibility_web-2.0.0%0Aflutter_keyboard_visibility_windows-1.0.0%0Aflutter_local_notifications-17.1.2%0Aflutter_native_splash-2.4.0%0Aflutter_plugin_android_lifecycle-2.0.20%0Aflutter_timezone-1.0.8%0Aflutter_windowmanager-0.2.0%0Afluttertoast-8.2.6%0Ageocoding-3.0.0%0Ageocoding_android-3.3.1%0Ageocoding_ios-3.0.1%0Ageolocator-10.1.1%0Ageolocator_android-4.6.0%0Ageolocator_apple-2.3.7%0Ageolocator_web-2.2.1%0Ageolocator_windows-0.2.3%0Agoogle_maps_flutter-2.7.0%0Agoogle_maps_flutter_android-2.9.0%0Agoogle_maps_flutter_ios-2.7.0%0Agoogle_maps_flutter_web-0.5.8%0Aimage_picker-1.1.2%0Aimage_picker_android-0.8.12%2B3%0Aimage_picker_for_web-3.0.4%0Aimage_picker_ios-0.8.12%0Aimage_picker_linux-0.2.1%2B1%0Aimage_picker_macos-0.2.1%2B1%0Aimage_picker_windows-0.2.1%2B1%0Ajust_audio-0.9.38%0Ajust_audio_web-0.4.11%0Amap_location_picker-1.2.8%2B3%0Apackage_info_plus-8.0.0%0Apath_provider-2.1.3%0Apath_provider_android-2.2.5%0Apath_provider_foundation-2.4.0%0Apath_provider_linux-2.2.1%0Apath_provider_windows-2.2.1%0Ashared_preferences-2.2.3%0Ashared_preferences_android-2.2.3%0Ashared_preferences_foundation-2.4.0%0Ashared_preferences_linux-2.3.2%0Ashared_preferences_web-2.3.0%0Ashared_preferences_windows-2.3.2%0Asqflite-2.3.3%2B1%0Auni_links2-0.6.0%2B2%0Auni_links_web2-0.1.0%2B2%0Aurl_launcher-6.3.0%0Aurl_launcher_android-6.3.3%0Aurl_launcher_ios-6.3.0%0Aurl_launcher_linux-3.1.1%0Aurl_launcher_macos-3.2.0%0Aurl_launcher_web-2.3.1%0Aurl_launcher_windows-3.1.1%0Avibration-1.9.0%0Avideo_player-2.8.7%0Avideo_player_android-2.5.0%0Avideo_player_avfoundation-2.6.1%0Avideo_player_web-2.3.1%0Awakelock_plus-1.2.5%0Awebview_flutter-4.8.0%0Awebview_flutter_android-3.16.4%0Awebview_flutter_wkwebview-3.13.1%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by darshankawar** [comment]
> jalisa_user/flutter_01.log

Provide this log file. The url you shared isn't the actual crash and I can't access it. Please provide the requested details properly.

**Comment by mazab99** [comment]
[flutter_01.log](https://github.com/user-attachments/files/15805726/flutter_01.log)

**Comment by darshankawar** [comment]
## command

flutter create .

## exception

ProcessException: ProcessException: Process exited abnormally with exit code -10:

  Command: xcrun xcodebuild -list

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:452:29)
<asynchronous suspension>
#4      IosProject.productBundleIdentifier (package:flutter_tools/src/xcode_project.dart:253:36)
<asynchronous suspension>
#5      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:143:42)
<asynchronous suspension>
#6      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:258:49)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:261:33)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, 3.22.2, on macOS 14.4 23E214 darwin-x64, locale en-EG)
    [32m•[39m Flutter version 3.22.2 on channel stable at /Users/mahmoudazab/Developer/flutter
    [33m![39m Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.3.4/libexec/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/mahmoudazab/Developer/flutter. Consider adding
      /Users/mahmoudazab/Developer/flutter/bin to the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (7 days ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/mahmoudazab/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [32m•[39m CocoaPods version 1.15.2

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[32m[✓][39m VS Code (version 1.90.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m VS Code (version 1.88.1)
    [32m•[39m VS Code at /Volumes/D/Mahmoud/Programs/IOS/Mac/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)
    [32m•[39m macOS (desktop)              • macos         • darwin-x64  • macOS 14.4 23E214 darwin-x64

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
Keeping the issue open based on the tool crash report.
