### ISSUE TITLE
OutlineBorder path for RTL InputDecorator is offsetted by 2 pixels

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#150109]
### Steps to reproduce

1. Copy the given test into packages/flutter/test/material/input_decorator_test.dart
2. Run the test

### Expected results

The test succeeds

### Actual results

The test failed.

To make it pass uncomment the line which adds a slight horizontal offset:

```dart
      // labelBottomRightLocalToBorder += const Offset(2, 0);
```

### Code sample

<details open><summary>Code sample</summary>

```dart

    testWidgets('OutlineBorder starts at the right position when text direction is RTL', (WidgetTester tester) async {
      Widget buildFrame(TextDirection textDirection) {
        return MaterialApp(
          home: Scaffold(
            body: Container(
              padding: const EdgeInsets.all(16.0),
              alignment: Alignment.center,
              child: Directionality(
                textDirection: textDirection,
                child: RepaintBoundary(
                  child: InputDecorator(
                    isFocused: true,
                    isEmpty: true,
                    decoration: InputDecoration(
                      labelText: labelText,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(30.0),
                        gapPadding: 0.0,
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      }

      await tester.pumpWidget(buildFrame(TextDirection.rtl));
      final RenderBox borderBox = InputDecorator.containerOf(tester.element(findBorderPainter()))!;
      // Convert label bottom right offset to border path coordinate system.
      Offset labelBottomRightLocalToBorder = borderBox.globalToLocal(getLabelRect(tester).bottomRight);
      // labelBottomRightLocalToBorder += const Offset(2, 0);

      expect(findBorderPainter(), paints
        ..save()
        ..path(
          // The label bottom right corner should not be part of the border.
          excludes: <Offset>[
            labelBottomRightLocalToBorder,
          ],
          // The points just after the label bottom right corner should be part of the border.
          includes: <Offset>[
            labelBottomRightLocalToBorder + const Offset(1, 0),
            labelBottomRightLocalToBorder + const Offset(1, 1),
          ],
        )
        ..restore(),
      );
    });

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/840911/594f38cc-7d3f-48d0-85f9-a7f7c30344ed)

Code sample used to create the screenshot:

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          padding: const EdgeInsets.all(16.0),
          alignment: Alignment.center,
          child: Directionality(
            textDirection: TextDirection.rtl,
            child: RepaintBoundary(
              child: InputDecorator(
                isFocused: true,
                isEmpty: true,
                decoration: InputDecoration(
                  labelText: 'label',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(30.0),
                    gapPadding: 0.0,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: Object or closure painting:
          'save()'
          'a path with that contains [Offset(757.0, 7.0), Offset(757.0, 8.0)] and does not contain
[Offset(756.0, 7.0)]'
          'restore()'
  Actual: _DescendantWidgetFinder:<Found 1 widget with widget matching predicate descending from
widget with widget matching predicate: [
            CustomPaint(renderObject: RenderCustomPaint#7d329),
          ]>
   Which: threw the following exception:
          It called drawPath with a path that unexpectedly did not contain Offset(757.0, 7.0).
          #0      _PathPaintPredicate.verifyArguments
(package:flutter_test/src/mock_canvas.dart:1263:11)
          #1      _DrawCommandPaintPredicate.match (package:flutter_test/src/mock_canvas.dart:934:5)
          #2      _TestRecordingCanvasPatternMatcher._evaluatePredicates
(package:flutter_test/src/mock_canvas.dart:848:27)
          #3      _TestRecordingCanvasMatcher.matches
(package:flutter_test/src/mock_canvas.dart:554:16)
          #4      _expect (package:matcher/src/expect/expect.dart:138:30)
          #5      expect (package:matcher/src/expect/expect.dart:56:3)
          #6      expect (package:flutter_test/src/widget_tester.dart:474:18)
          #7      main.<anonymous closure>.<anonymous closure>
(file:///home/bruno/Nevercode/flutter/packages/flutter/test/material/input_decorator_test.dart:1748:7)
          <asynchronous suspension>
          #8      testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:183:15)
          <asynchronous suspension>
          #9      TestWidgetsFlutterBinding._runTestBody
(package:flutter_test/src/binding.dart:1025:5)
          <asynchronous suspension>
          #10     StackZoneSpecification._registerCallback.<anonymous closure>
(package:stack_trace/src/stack_zone_specification.dart:114:42)
          <asynchronous suspension>
          The complete display list was:
            * save()
            * drawPath(Path, Paint(PaintingStyle.stroke 2.0 StrokeJoin.miter up to 0.0;
Color(0xff6750a4)))
            * restore()

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/bruno/Nevercode/flutter/packages/flutter/test/material/input_decorator_test.dart:1748:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/bruno/Nevercode/flutter/packages/flutter/test/material/input_decorator_test.dart line 1748
The test description was:
  OutlineBorder starts at the right position when text direction is RTL
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.22.0-18.0.pre.719, on Ubuntu 24.04 LTS 6.8.0-35-generic, locale fr_FR.UTF-8)
```

</details>

**Comment by bleroux** [comment]
Labelling P3 because I'm not sure it is a real issue or just due to some rounding.
