### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by ArthurFleischman** [flutter/flutter#150152]
## Command
```
flutter run --machine --start-paused -d 00008120-000C19E81490C01E --devtools-server-address http://127.0.0.1:9100/ --target /Users/arthur/Projects/AGL/taurasia_living_mobile/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2584:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:618:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.1, on macOS 15.0 24A5264n darwin-arm64, locale en-US)
    • Flutter version 3.22.1 on channel stable at /Users/arthur/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/arthur/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/arthur/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Users/arthur/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Arthur’s iPhone (mobile)        • 00008120-000C19E81490C01E • ios            • iOS 18.0 22A5282m
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A5264n darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A5264n darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d

**Comment by darshankawar** [comment]
> ios            • iOS 18.0 22A5282m

Looks like this is specific to iOS 18. A similar [issue](https://github.com/flutter/flutter/issues/150131) is open describing same crash. Please follow-up in it for further updates.
