### ISSUE TITLE
[go_router] GoRouter.of(context).removeListener() does not remove the listener. The listener function is still called.

### ISSUE THREAD

**Issue by arix2000** [flutter/flutter#150256]
### Steps to reproduce

1. put the code in the example project and start navigating through the different screens (until you call onDispose in the screen where you have the listener)
2. after calling onDispose (and in it removeListener()), the listener function will still try to invoke causing an error

### Expected results

function should stop calling after GoRouter.of(context).removeListener() is called

### Actual results

_listener is still being invoked

### Code sample

<details open><summary>Code sample</summary>

```dart
  late VoidCallback _listener;
// [...]
  @override
  void initState() {
    super.initState();
    stateHolder.productSku = widget.sku;
    bloc = serviceLocator()
      ..add(GetProductDetailsEvent(stateHolder.productSku));
    _listener = () { _onPopToThisPage(); };
    GoRouter.of(context).routerDelegate.addListener(_listener);
  }



  void _onPopToThisPage() {
    if (context.mounted && GoRouter.of(context).location.startsWith(
        AppPage.productDetailsPage.toPath)) {
      bloc.add(GetProductDetailsEvent(stateHolder.productSku));
    }
  }

  @override
  void dispose() {
    GoRouter.of(context).routerDelegate.removeListener(_listener);
    bloc.close();
    super.dispose();
  }
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for GoRouterDelegate:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4738:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4752:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4787:12)
#3      GoRouter.maybeOf (package:go_router/src/router.dart:516:10)
#4      GoRouter.of (package:go_router/src/router.dart:506:33)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@arix2000 
Can you provide complete runnable reproducible code sample ? Also, check on latest stable if the error still persists or not.

**Comment by arix2000** [comment]
I cannot provide such an example because it is a close source project, but I have found a solution. Instead of saving the listener locally, I need to save the GoRouter locally on the widget and use it to add and remove the listener, but for some reason I have to add the listener and GoRouter from didUpdateDependencies:

```dart
  late VoidCallback? _listener;
  late GoRouter? goRouter;

  void _onPopToThisPage() {
    if (context.mounted &&
        goRouter?.location.startsWith(
                AppPage.productDetailsPage.toPath.replaceFirst(":sku", "")) ==
            true) {
      bloc.add(GetProductDetailsEvent(stateHolder.productSku));
    }
  }

  @override
  void didChangeDependencies() {
    goRouter = GoRouter.of(context);
    _listener = () {
      _onPopToThisPage();
    };
    goRouter?.routerDelegate.addListener(_listener!);
    super.didChangeDependencies();
  }

  @override
  void dispose() {
    if (_listener != null) {
      goRouter?.routerDelegate.removeListener(_listener!);
    }
    super.dispose();
  }
```

**Comment by darshankawar** [comment]
Good to know. Closing as resolved.
