### ISSUE TITLE
Dart 2 firebase_auth getTokenId error

### ISSUE THREAD

**Issue by lschmierer** [flutter/flutter#15027]
## Steps to Reproduce

Cannot `await` returned `Future` of `FirebaseUser. getIdToken()` when using Dart 2 Preview.

```Dart
final idToken = await user.getIdToken();
```

## Logs

```
I/flutter ( 9988): type '_Future' is not a subtype of type 'Future<String>' where
I/flutter ( 9988):   _Future is from dart:async
I/flutter ( 9988):   Future is from dart:async
I/flutter ( 9988):   String is from dart:core
I/flutter ( 9988): #0      FirebaseUser.getIdToken (package:firebase_auth/firebase_auth.dart:76:33)
I/flutter ( 9988): #1      CloudFunctions._putAuth (file:///.../lib/data/cloud_functions.dart:44:61)
...
```

## Flutter Doctor
```
[✓] Flutter (Channel dev, v0.1.7, on Mac OS X 10.13.3 17D47, locale en-DE)
    • Flutter version 0.1.7 at /Users/lschmierer/flutter
    • Framework revision 3b84503403 (3 days ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/lschmierer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • Pixel • FA69N0312108 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by mit-mit** [comment]
cc @mravn-google

**Comment by mraleph** [comment]
I have the fix for it here: https://github.com/flutter/plugins/pull/403

but we still need to go through the whole `plugins/packages` folder to update either tests or packages for Dart 2. I see some cryptic failures there which I don't have time to debug right away.

**Comment by kroikie** [comment]
@lschmierer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/898. Any further collaboration will be done there.
