### ISSUE TITLE
dart in --preview-dart-2  fails to run dev/devicelab/test/all.dart

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15028]
```
~/projects/flutter/test_root6/flutter/flutter/dev/devicelab  ‹master*› 
╰─➤  ../../bin/cache/dart-sdk/bin/dart --checked --preview-dart-2 test/all.dart
Unhandled exception:
Unhandled exception:
type 'List' is not a subtype of type 'Iterable<String>' of 'variables' where
  List is from dart:core
  Iterable is from dart:core
  String is from dart:core

#0      new All (package:boolean_selector/src/all.dart)
#1      new Metadata._unresolved (package:test/src/backend/metadata.dart:153:26)
#2      new Metadata (package:test/src/backend/metadata.dart:167:59)
#3      new Declarer (package:test/src/backend/declarer.dart:109:29)
#4      _declarer (package:test/test.dart:58:25)
#5      group (package:test/test.dart:207:3)
#6      main (file://$FH/flutter/dev/devicelab/test/adb_test.dart:13:3)
#7      main (file://$FH/flutter/dev/devicelab/test/all.dart:10:12)
#8      _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
error: error evaluating constant constructor'package:test/src/backend/platform_selector.dart': error: line 25 pos 63: Not a constant expression.
  static const all = const PlatformSelector._(BooleanSelector.all);
                                                              ^
'package:test/src/backend/metadata.dart': error: line 198 pos 52: Not a constant expression.
      : testOn = testOn == null ? PlatformSelector.all : testOn,
                                                   ^

#0      new Metadata._unresolved (package:test/src/backend/metadata.dart:153:26)
#1      new Metadata (package:test/src/backend/metadata.dart:167:59)
#2      new Declarer (package:test/src/backend/declarer.dart:109:29)
#3      _declarer (package:test/test.dart:58:25)
#4      group (package:test/test.dart:207:3)
#5      main (file://$FH/flutter/dev/devicelab/test/adb_test.dart:13:3)
#6      main (file://$FH/flutter/dev/devicelab/test/all.dart:10:12)
#7      _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
```

**Comment by aam** [comment]
cc @mraleph @a-siva
