### ISSUE TITLE
Critical error on Linux desktop: assertion 'lookup_hash_table(self->pressing_records, physical_key) != 0' failed

### ISSUE THREAD

**Issue by cuihaoleo** [flutter/flutter#150326]
### Steps to reproduce

A minimal test code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MainScreen(),
    );
  }
}

class MainScreen extends StatelessWidget {
  const MainScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: const Row(
        children: [
          Expanded(
            child: TextField(),
          ),
        ],
      ),
    );
  }
}
```

- Run the code in debug mode on Linux.
- Input, paste, delete some text from the text box. I'm not quite clear what actions triggerred the errors but it's fairly easy to trigger. One sequence that consistently triggers the error is: paste some text using ctrl-V -> delete any character from the end using backspace.

### Expected results

No error.

### Actual results

Tons of errors:
```
** (text_field_test:353067): CRITICAL **: 14:40:20.078: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) != 0' failed
```

And if I ignore the error, the text box acts wierdly. It feels like ctrl key is being hold. For example, if I press `a`, it will select all the text. If I press backspace, it will delete a whole word.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

[Screencast_20240616_143424.webm](https://github.com/flutter/flutter/assets/889871/45e5a96b-a32d-49bc-8311-9d0505778115)

### Logs

Output of `flutter --verbose run -d Linux`:
[flutter_run_log.txt](https://github.com/user-attachments/files/15859918/flutter_run_log.txt)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on Arch Linux 6.9.4-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.22.0 on channel stable at /home/cuihao/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (5 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/cuihao/opt/Android-Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/cuihao/opt/Android-Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.29.5
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2023.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.9.4-arch1-1
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.61

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @cuihaoleo 
I'm using wayland on Ubuntu distro. I ran Flutter app with X11 as above but couldn't reproduce this issue. Maybe this only occurs on Arch?

Can you run with verbose (`flutter run -v`) and share the entire error trace? Please also try on the latest Flutter stable and master version to see if the issue persists or not. Thanks!

**Comment by cuihaoleo** [comment]
I tried both Flutter 3.22.2 and master. There is no difference.

It could be KDE or Wayland-specific, but I don't think Arch is special in any way.


## With Flutter 3.22.2

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Arch Linux 6.9.4-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

Log of running `flutter run -v -d linux > flutter_run.log`: [flutter_run.log](https://github.com/user-attachments/files/15880796/flutter_run.log)

## With master version

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.23.0-13.0.pre.262, on Arch Linux 6.9.4-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

Log: [flutter_run_master.log](https://github.com/user-attachments/files/15880825/flutter_run_master.log)

**Comment by huycozy** [comment]
Thanks for the update. I excerpt the main stack trace from your log file here so others can quickly look into:

```console
[+2964 ms] ** (simple_llm_gui:736813): CRITICAL **: 22:22:19.254: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) != 0' failed
[        ] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 1073 pos 16: 'data.physical != 0 && data.logical != 0': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] #2      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:1073:16)
[        ] #3      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:510:41)
[        ] #4      _invoke1 (dart:ui/hooks.dart:328:13)
[        ] #5      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:508:7)
[        ] #6      _invoke2 (dart:ui/hooks.dart:344:13)
[        ] #7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
[        ] #8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
[        ] #9      ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
[        ] #10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
[        ] #11     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
```

**Comment by Rob-bb** [comment]
> Hi @cuihaoleo I'm using wayland on Ubuntu distro. I ran Flutter app with X11 as above but couldn't reproduce this issue. Maybe this only occurs on Arch?
> 
> Can you run with verbose (`flutter run -v`) and share the entire error trace? Please also try on the latest Flutter stable and master version to see if the issue persists or not. Thanks!

Happening to me on Ubuntu 23.10 too, so probably not an Arch issue

**Comment by Rob-bb** [comment]
I am having this same error. I am developing on Ubuntu 23.10 over ssh with X11 forwarding.  I am using android studio.  I can trigger it by left clicking in the terminal pane, either debugging or just running makes no difference.

```
** (gv:526595): CRITICAL **: 20:42:03.795: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) != 0' failed
[👾] [38;5;196m[zone]: [38;5;196mUncaught exception
[38;5;196m'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 1074 pos 16: 'data.physical != 0 && data.logical != 0': is not true.
[38;5;196m#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[38;5;196m#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[38;5;196m#2      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:1074:16)
[38;5;196m#3      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:510:41)
[38;5;196m#4      _invoke1 (dart:ui/hooks.dart:328:13)
[38;5;196m#5      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:508:7)
[38;5;196m#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:347:15)
[38;5;196m#7      _rootRun (dart:async/zone.dart:1399:13)

** (gv:526595): WARNING **: 20:42:03.845: Unable to retrieve framework response: Message is not valid JSON
[log] Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#b1f59(logicalKey: LogicalKeyboardKey#3b7a5(keyId: "0x1500000000", keyLabel: "", debugName: "Key with ID 0x01500000000"), physicalKey: PhysicalKeyboardKey#5b142(usbHidUsage: "0x00070053", debugName: "Num Lock"), repeat: false) and its data: RawKeyEventDataLinux#d809f(toolkit: GTK, unicodeScalarValues: 0, scanCode: 77, keyCode: 0, modifiers: 0, isDown: true)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 862 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'
      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
      #2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:862:7)
      #3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1161:30)
      #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
      #5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
      #6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:347:15)
      #7      _rootRun (dart:async/zone.dart:1399:13)
      #8      _CustomZone.run (dart:async/zone.dart:1301:19)
      #9      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
      #10     _invoke2 (dart:ui/hooks.dart:346:10)
      #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
      #12     _Channel.push (dart:ui/channel_buffers.dart:135:31)
      #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
      #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
      #15     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
```

**Comment by justinmc** [comment]
CC @dkwingsmt in case you have any idea as it relates to keyboard input.

**Comment by shivamkj** [comment]
Flutter does support Linux, but this critical error makes Linux almost unusable when interacting with text field, which is a very common use case. Please consider prioritizing this issue to make flutter usable on Linux.
