### ISSUE TITLE
The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...

### ISSUE THREAD

**Issue by herowws** [flutter/flutter#150332]
### Steps to reproduce

```
 flutter doctor       
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.90.1)
[✓] Connected device (4 available)
[✓] Network resources

```
flutter run --verbose
......
```
[+1465 ms] [ 75%] CreatingContainer
[  +16 ms] [ 80%] InstallingApplication
[  +20 ms] [ 85%] PostflightingApplication
[  +16 ms] [ 90%] SandboxingApplication
[  +17 ms] [ 95%] GeneratingApplicationMap
[+2741 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +126 ms] ------ Debug phase ------
[        ] Starting debug of bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd (N56AP, iPhone 6 Plus, iphoneos, arm64, 12.5.7, 16H81) a.k.a. 'herowws的 iPhone' connected through USB...
[+1346 ms] [  0%] Looking up developer disk image
[  +44 ms] [ 95%] Developer disk image mounted successfully
[ +635 ms] Symbol Path: /Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols
[ +984 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +142 ms] (lldb) command source -s 0 '/tmp/8B3D42C4-8A51-410D-8A45-7CFB3A62C395/fruitstrap-lldb-prep-cmds-bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd'
[        ] Executing commands in '/tmp/8B3D42C4-8A51-410D-8A45-7CFB3A62C395/fruitstrap-lldb-prep-cmds-bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd'.
[        ] (lldb)     platform select remote-'ios' --sysroot '/Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]    Sysroot: /Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols
[        ]   SDK Path: "/Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols"
[        ] (lldb)     target create "/Users/forrest/code/flutter/v2/xary_business/build/ios/iphoneos/Runner.app"
[+5876 ms] Current executable set to '/Users/forrest/code/flutter/v2/xary_business/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/C2A63C3A-1A0B-4157-8B44-247E21619AFF/Runner.app"
[  +20 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:57742"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols/usr" /System
"/Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols/System" "/private/var/containers/Bundle/Application/C2A63C3A-1A0B-4157-8B44-247E21619AFF"
"/Users/forrest/code/flutter/v2/xary_business/build/ios/iphoneos" "/var/containers/Bundle/Application/C2A63C3A-1A0B-4157-8B44-247E21619AFF"
"/Users/forrest/code/flutter/v2/xary_business/build/ios/iphoneos" /Developer "/Users/forrest/Library/Developer/Xcode/iOS DeviceSupport/iPhone7,1 12.5.7 (16H81)/Symbols/Developer"
[  +39 ms] (lldb)     command script import "/tmp/8B3D42C4-8A51-410D-8A45-7CFB3A62C395/fruitstrap_bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd.py"
[   +2 ms] (lldb)     command script add -f fruitstrap_bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_bde9bee4751ee5e59300f4b8d2fb8b5045ada3fd.safequit_command safequit
[        ] (lldb)     connect
[  +30 ms] (lldb)     run
[ +367 ms] success
[        ] (lldb)     safequit
[ +147 ms] Process 212 detached
[  +61 ms] Application launched on the device. Waiting for Dart VM Service url.
[+30003 ms] The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...
q^C[+22823 ms] the Dart compiler exited unexpectedly.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:898:9)
           #2      _rootRunUnary (dart:async/zone.dart:1407:47)
           #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
           #4      Future._propagateToListeners (dart:async/future_impl.dart:876:13)
           #5      Future._completeWithValue (dart:async/future_impl.dart:652:5)
           #6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
           #7      _rootRun (dart:async/zone.dart:1399:13)
           #8      _CustomZone.run (dart:async/zone.dart:1301:19)
           #9      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
           #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
           #11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[  +41 ms] Installing and launching... (completed in 88.4s)
[        ] Error launching application on herowws,s iPhone.
[        ] "flutter run" took 163,687ms.
[  +26 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:840:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +183 ms] ensureAnalyticsSent: 254ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] ensureAnalyticsSent: 254ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[  +67 ms] ensureAnalyticsSent: 251ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[ +141 ms] exiting with code 0
```

### Expected results

run success

### Actual results

run failure

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by herowws** [comment]
iPhone: iPhone6Plus  os:12.5.7
