### ISSUE TITLE
Fasta crashes on second time running a flutter app after performing a hot reload

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#15033]
## Steps to Reproduce

`flutter run --preview-dart-2`

Make any tiny tweak to widget_inspector.dart or any other file in package:flutter

Trigger hot reload

stop the app and rerun by issuing
`flutter run --preview-dart-2`

Startup fails with the following exception:

```
examples/flutter_gallery$ flutter run --preview-dart-2
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.0s
Resolving dependencies...                                    0.9s
Running 'gradlew assembleDebug'...
compiler message: Unhandled exception:
package:flutter/widgets.dart: Internal problem: Unhandled Null in finalizeExports.
#0      internalProblem (package:front_end/src/fasta/problems.dart:31)
#1      unhandled (package:front_end/src/fasta/problems.dart:44)
#2      DillLibraryBuilder.finalizeExports (package:front_end/src/fasta/dill/dill_library_builder.dart:185)
#3      DillLoader.finalizeExports.<anonymous closure> (package:front_end/src/fasta/dill/dill_loader.dart:71)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#5      DillLoader.finalizeExports (package:front_end/src/fasta/dill/dill_loader.dart:69)
#6      DillTarget.buildOutlines (package:front_end/src/fasta/dill/dill_target.dart:54)
<asynchronous suspension>
#7      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:123)
<asynchronous suspension>
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
#13     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
<asynchronous suspension>
#14     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#15     _FrontendCompiler.compile.<anonymous closure> (package:frontend_server/server.dart:200)
#16     new Future.<anonymous closure> (dart:async/future.dart:174)
#17     _rootRun (dart:async/zone.dart:1122)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     _CustomZone.runGuarded (dart:async/zone.dart:925)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
````

**Comment by a-siva** [comment]
@jacob314 do you see the following error when you do a hot reload after the making your change
```
Initializing hot reload...                                       
compiler message: file:///usr/local/google/home/asiva/workspace/flutter-roll/flutter/packages/flutter/lib/src/widgets/overlay.dart: Error: The parameter 'value' of the method '_RenderTheatre::child' has type #lib1::RenderStack, which does not match the corresponding type in the overridden method (#lib2::RenderBox).
compiler message: Change to a supertype of #lib2::RenderBox (or, for a covariant parameter, a subtype).
compiler message: file:///usr/local/google/home/asiva/workspace/flutter-roll/flutter/packages/flutter/lib/src/rendering/object.dart: Context: This is the overriden method ('child').
Reloaded 237 of 561 libraries in 6,005ms.
```
I feel the second issue is caused maybe because we are loading an inconsistent '.dill' file produced during the hot reload,

**Comment by Hixie** [comment]
@a-siva Did this get fixed? (The associated issues are closed.)
