### ISSUE TITLE
TestDeviceException(Shell subprocess crashed with SIGABRT (-6).)  after upgrading to v3.22.2

### ISSUE THREAD

**Issue by hasanmhallak** [flutter/flutter#150429]
### Steps to reproduce

I'm not sure how to reproduce this issue.

The test is part of a Flutter package I maintain. Whenever I try to isolate the target code (writing the code and the test in the same file), all failing tests pass.

When running the test using the VS Code plugin for Flutter, it fails with an "Unknown test failure." However, when running the test from the CLI, I get the following logs:

<details open><summary>Logs</summary>

```console
➜  date_picker git:(master) ✗ flutter test test/shared/year_view_test.dart
00:01 +0: YearView should select the right year when tap.                                                                                         Shell: [ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(27)] Reached unreachable code.
unhandled error during finalization of test:
/Users/hasanm.hallak/Desktop/date_picker/test/shared/year_view_test.dart
TestDeviceException(Shell subprocess crashed with SIGABRT (-6).)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:248:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:230:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:525:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:581:11)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.90.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

<details open><summary>Logs Verbose</summary>

```console
➜  date_picker git:(master) ✗ flutter test test/shared/year_view_test.dart -v
[   +3 ms] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.5.2
[        ] executing: sw_vers -buildVersion
[   +6 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22G91
[        ] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] arm64
[   +3 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +50 ms] Found 1 files which will be executed as Widget Tests.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +27 ms] Skipping pub get: version match.
[ +152 ms] running test package with arguments: [--chain-stack-traces, --,
file:///Users/hasanm.hallak/Desktop/date_picker/test/shared/year_view_test.dart?]
00:00 +0: loading /Users/hasanm.hallak/Desktop/date_picker/test/shared/year_view_test.dart                                                        [  +98 ms] test 0: starting test /Users/hasanm.hallak/Desktop/date_picker/test/shared/year_view_test.dart
[   +3 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/hasanm.hallak/Desktop/date_picker
[   +1 ms] Compiler will use the following file as its incremental dill file:
/var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_compiler.BDrtpZ/output.dill
[        ] Listening to compiler controller...
[   +4 ms] Compiling file:///var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_listener.X8fa2N/listener.dart
[  +22 ms] No packages with native assets. Skipping native assets compilation.
[        ] Writing native_assets.yaml.
[   +7 ms] Writing /Users/hasanm.hallak/Desktop/date_picker/build/native_assets/macos/native_assets.yaml done.
[   +2 ms] /Users/hasanm.hallak/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev
/Users/hasanm.hallak/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/Users/hasanm.hallak/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --no-print-incremental-dependencies
--target=flutter --experimental-emit-debug-metadata --output-dill
/var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_compiler.BDrtpZ/output.dill --packages
/Users/hasanm.hallak/Desktop/date_picker/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --initialize-from-dill /Users/hasanm.hallak/Desktop/date_picker/build/test_cache/build/cache.dill.track.dill
--native-assets file:///Users/hasanm.hallak/Desktop/date_picker/build/native_assets/macos/native_assets.yaml --verbosity=error
[   +8 ms] <- native-assets file:///Users/hasanm.hallak/Desktop/date_picker/build/native_assets/macos/native_assets.yaml
[        ] <- compile file:///var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_listener.X8fa2N/listener.dart
[ +632 ms] <- accept
[        ] <- reset
[        ] Compiling file:///var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_listener.X8fa2N/listener.dart took
673ms
[        ] test 0: starting test device
[   +1 ms] test 0: awaiting connection to test device
[        ] test 0: VM Service uri is not available
[   +1 ms] test 0: test harness socket server is running at port:60244
[        ] Using this directory for fonts configuration:
/var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_fonts.sOr6pO
[        ] test 0: Starting flutter_tester process with command=[/Users/hasanm.hallak/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester,
--disable-vm-service, --enable-checked-mode, --verify-entry-points, --enable-software-rendering, --skia-deterministic-rendering,
--enable-dart-profiling, --non-interactive, --use-test-fonts, --disable-asset-fonts,
--packages=/Users/hasanm.hallak/Desktop/date_picker/.dart_tool/package_config.json,
--flutter-assets-dir=/Users/hasanm.hallak/Desktop/date_picker/build/unit_test_assets,
/var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_listener.X8fa2N/listener.dart.dill], environment={FLUTTER_TEST:
true, FONTCONFIG_FILE: /var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_fonts.sOr6pO/fonts.conf, SERVER_PORT:
60244, APP_NAME: date_picker_plus, UNIT_TEST_ASSETS: /Users/hasanm.hallak/Desktop/date_picker/build/unit_test_assets}
[   +4 ms] test 0: Started flutter_tester process at pid 21262
[ +267 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:01 +0: YearView should select the right year when tap.                                                                                         [ +388 ms] test 0: Shell: [ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(27)] Reached unreachable code.
[        ] Shell: [ERROR:flutter/impeller/runtime_stage/runtime_stage.cc(27)] Reached unreachable code.
[  +65 ms] test 0: Test process is no longer needed by test harness
[        ] test 0: finished
[        ] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down DevTools server
[        ] test 0: Test harness is no longer needed by test process
[        ] test 0: Shutting down test harness socket server
[        ] test 0: flutter_tester process at pid 21262 exited with code=-6
[        ] test 0: error while cleaning up; reporting to console
[        ] unhandled error during finalization of test:
           /Users/hasanm.hallak/Desktop/date_picker/test/shared/year_view_test.dart
           TestDeviceException(Shell subprocess crashed with SIGABRT (-6).)
           #0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:248:5)
           <asynchronous suspension>
           #1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:230:5)
           <asynchronous suspension>
           #2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:525:9)
           <asynchronous suspension>
           #3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:581:11)
           <asynchronous suspension>
           
[        ] test 0: deleting temporary directory
[   +1 ms] test 0: finished with out-of-band failure
00:01 +0: YearView should select the right year when tap. - did not complete [E]                                                                  
00:01 +0: Some tests failed.                                                                                                                      
No tests were found.
[   +4 ms] Deleting /var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_compiler.BDrtpZ...
[   +1 ms] killing pid 21253
[   +6 ms] Deleting /var/folders/ld/9sbqbpl14m73hhg2d3stfwxc0000gn/T/flutter_tools.FfFFN5/flutter_test_fonts.sOr6pO...
[   +1 ms] test package returned with exit code 79
[        ] Runtime for phase TestRunner: Wall-clock: 0:00:01.534474; combined: 0:00:01.534493.
[        ] Runtime for phase Compile: Wall-clock: 0:00:00.673300; combined: 0:00:00.673316.
[        ] Runtime for phase Run: Wall-clock: 0:00:00.729977; combined: 0:00:00.729980.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.000529; combined: 0:00:00.000529.
[   +3 ms] "flutter test" took 1,742ms.
[  +23 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:624:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +183 ms] ensureAnalyticsSent: 182ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[   +9 ms] exiting with code 1
```

</details>

**Comment by hasanmhallak** [comment]
Solved by updating dart sdk to `sdk: ">=3.0.0 <4.0.0"` instead of `sdk: ">=2.18.0 <4.0.0"` is pubspec.yaml
