### ISSUE TITLE
Does flutter support cleartext basic-auth in the URL? (https://username:password@domain.tld)

### ISSUE THREAD

**Issue by poisonnuke** [flutter/flutter#150411]
### Steps to reproduce

simple video player using flutter that accesses media on an SSL encrypted webserver. This webserver is protected using basic auth.

the connection is establised using the 
https://username:password@domain.tld:port

format, which is working for other connections in that application to that server, but not with flutter. 

### Actual results

Flutter is not playing the video and returning an codec not supported error. But when disabling basic auth on the server, the media is playing without issues.

I know there are other means to establish basic-auth connections but that require some changes in the app and it shouldnt be needed as URL passing of credentials is also secure way when the app is using an encrypted vault and HTTPS. 

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

FlutterError - CatchAll
Exception: Exception: Invalid image data
Library: image resource service
Context: resolving an image codec

```

</details>

**Comment by huycozy** [comment]
Are you using [video_player](https://pub.dev/packages/video_player) package? Please check https://github.com/flutter/flutter/issues/75995 to see if it also assembles your case.

**Comment by poisonnuke** [comment]
> Are you using [video_player](https://pub.dev/packages/video_player) package? Please check #75995 to see if it also assembles your case.

yes, the video-player is used. Certs in question are from Letsencrypt.

**Comment by huycozy** [comment]
Please provide the following information so we can verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The version of video_player package you are using
- Complete error stack trace
- Which target environment did this issue happen in? (Android, iOS, etc)

Thank you!

**Comment by poisonnuke** [comment]
Can you please answer my question first, if there is no support then I dont need to do all of those steps in the first place. 

Because the client (in this case the video player from flutter -> the https framework its using) needs to be able to handle a URI like this. Any maybe that support is not present in the Android version, then we dont need a stack-trace and everything else. Will take me some time to gather that.

**Comment by huycozy** [comment]
I thought this was similar to https://github.com/flutter/flutter/issues/75995 but it's an issue with self-signed SSL but not with CA SSL as you said (Letsencrypt) and there is no issue with CA SSL reported in our issue database.

>Flutter is not playing the video and returning an codec not supported error

>Exception: Exception: Invalid image data

Since this information is incomplete so I can't confirm/answer your question now. If this causes a crash, it could be a bug instead. And this needs to be investigated to see if it's a bug on Flutter plugin (video_player) side or native platform side (exoplayer if it's Android or AVPlayer if it's iOS) as well.

**Comment by poisonnuke** [comment]
The issue only occurs on Android, not on iOS, which might indicate an issue with the underlying exoplayer. 


The videoplayer itself and where the stack-trace is thrown (which is not relevant I guess):
https://github.com/immich-app/immich/blob/79a8ab71efc526de88dee89435d91c0a3f8e398b/mobile/lib/pages/common/video_viewer.page.dart#L34

The part where the HTTP headers are created:
https://github.com/immich-app/immich/blob/79a8ab71efc526de88dee89435d91c0a3f8e398b/mobile/lib/providers/asset_viewer/video_player_controller_provider.dart#L28


This is the stack-trace as of now, I only getting this error now and not the Codec-Error anymore:

```
Instance of 'FlutterErrorDetails'
Exception: PlatformException(VideoError, Video player had error y2.r: Source error, null, null)
Library: widgets library
Context: Instance of 'ErrorDescription'
```

```
#1      AsyncError.value (package:riverpod/src/common.dart:494:0)
#2      VideoViewerPage.build (package:immich_mobile/pages/common/video_viewer.page.dart:36:0)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:0)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:0)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:0)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:438:0)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:0)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:0)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:0)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:0)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:0)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:0)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:0)
#16     _invoke (dart:ui/hooks.dart:312:0)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:0)
#18     _drawFrame (dart:ui/hooks.dart:283:0)
```

**Comment by huycozy** [comment]
Is the video url playable without authentication? If it is, can you try using it on our [basic sample code](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/example/lib/basic.dart) to see if the issue appears? You can also try with [Exoplay](https://github.com/google/ExoPlayer) if you are familiar with Android native.

**Comment by poisonnuke** [comment]
This would require extensive changes in the application (and its likely to work because thats the default way). 

Isnt there anything in the stack trace of value? As you can see we are handing the entire URL string to flutter so somewhere down the line the authority information is lost or not used. Is there a specific Exoplayer implementation in flutter we can look into?

**Comment by huycozy** [comment]
>Exception: PlatformException(VideoError, Video player had error y2.r: Source error, null, null)

This error is thrown from native on ExoPlayerEventListener callback: https://github.com/flutter/packages/blob/9c6f691a8c891ff61d32eec4382c1850df599c67/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/ExoPlayerEventListener.java#L93

There may be a problem with the TLS certificate, see https://github.com/google/ExoPlayer/issues/9851#issuecomment-1010325447.

**Comment by poisonnuke** [comment]
we already excluded an issue with TLS as its working withouth basic-auth enabled on that server and the cert is letsencrypt so extremely unlikely to be an TLS issue.

And because basic-auth is also happening at the same time, the high-level error remains the same. Is there any way we can dig deeper to see where the URL incorrectly handled? 

How and where does flutter hand the URL to exoplayer?

**Comment by huycozy** [comment]
>Is there any way we can dig deeper to see where the URL incorrectly handled?
How and where does flutter hand the URL to exoplayer?

You can look at the [video_player](https://github.com/flutter/packages/tree/main/packages/video_player) package source code and try debugging it. Since you only see the issue on Android, please check https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android.

**Comment by poisonnuke** [comment]
does someone in the flutter-team know whats happening here? As I'm completely new to the code its hard to debug just like that. Any maybe for someone in the team it'll ring a bell that there was a special case with android and URL handling? For me its currently looking for a needle in a haystack, for someone in your team it could be a quick look.

**Comment by huycozy** [comment]
Since there is no reproduction, it could take time to investigate the issue. Labeling this for team's input. In the meantime, please provide the version of `video_player_android` package you are using. 

### Issue summary
- Issue happens with video URL hosted on a webserver with CA SSL 
- Issue only occurs on Android, not on iOS
- Error trace: https://github.com/flutter/flutter/issues/150411#issuecomment-2179944917

**Comment by stuartmorgan** [comment]
> does someone in the flutter-team know whats happening here?

It's not clear at this point that the issue is related to Flutter-team-authored code, rather than an ExoPlayer limitation. Given the lack of repro case, I would recommend trying a simple non-Flutter Android app using ExoPlayer directly to see if reproduces therer.

**Comment by poisonnuke** [comment]
@stuartmorgan  to create a repro case I need to know where in the flutter player the URL and authentication handling is done and where the exo_player implementation is. From there I can start debugging and try giving better info back to your team.

**Comment by poisonnuke** [comment]
I was able to trace the problem to the ExoPlayer, even though Im stuck at this point as Im not able to debug the ExoPlayer. 

And there is the practical question: ExoPlayer is discontinued and does not receive any further commits, therefore it does not make sense to delve deeper into that topic in the first place. 
When will flutter update to the successor of ExoPlayer? Maybe the problem does not exist in the new player

**Comment by stuartmorgan** [comment]
> And there is the practical question: ExoPlayer is discontinued and does not receive any further commits

ExoPlayer is not discontinued. Are you referring specifically to `com.google.android.exoplayer` rather than `androidx.media3:media3-exoplayer`?

> When will flutter update to the successor of ExoPlayer?

Assuming by "ExoPlayer" you actually mean `com.google.android.exoplayer` and by "the successor of ExoPlayer" you mean `androidx.media3:media3-exoplayer`, `video_player` (which I assume is what you mean by "flutter", since the Flutter SDK doesn't use ExoPlayer) migrated [last month](https://github.com/flutter/packages/pull/6535).

**Comment by poisonnuke** [comment]
ok that was confusing from Google as the project page states that ExoPlayer is suceeded by media3, but now thats clearer to me. 

Ok we upgraded to latest flutter 2 days ago, which means the bug is still in exoplayer. Ill try to setup a simple project just with EP, but can we please leave this issue open until its really clear that there is nothing that flutter can do.

**Comment by poisonnuke** [comment]
Ok current state is, Ive setup a test-server with just CA-SSL and basic auth in nginx and simple document serving. In the app using flutter its the same result. 

Using ExoPlayer as standalone, it works. So the problem is either in flutter or in the app. 

Is there an example project available that uses the flutter video_player? I cannot find any samples in the flutter samples repo. Maybe Im missing something?

**Comment by huycozy** [comment]
>Is there an example project available that uses the flutter video_player? I cannot find any samples in the flutter samples repo. Maybe Im missing something?

@poisonnuke This is repository for all 1st party packages: https://github.com/flutter/packages/tree/main/packages. You can find example project on each one there. For video_player package, let's check this [basic example](https://github.com/flutter/packages/blob/main/packages/video_player/video_player/example/lib/basic.dart).

**Comment by poisonnuke** [comment]
thank you, would'nt've found that on my own.

Ive tried the video_player_android example and simply exchanged the hardcoded bee.mp4 URI with my own test-server and this app is also not able to play that video behind basic-auth. Even though that ExoPlayer is reporting the source-error, something between flutter and exoplayer is causing this issue. 

the bee.mp4 was working btw, so the example works fine for me. At least we can say for sure the bug is in flutter. But I have no idea how to debug any further (I only have Android Studio and no IDE and and therefore I cannot set a break-point in the main.dart. If you want I can provide you the URL + test basic auth with an example video from my server. ?

**Comment by poisonnuke** [comment]
Ive setup VS Code to debug, but Im stuck, debugging thows an exception while creating a message and seemingly debugging takes too long and so the channel cannot be created. Im not sure how to debug the async messages in dart.

**Comment by stuartmorgan** [comment]
> It really might be easier if someone of you guys could please try to test and debug

Please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#when-will-my-bug-be-fixed. There is no timeframe on when a P2 issue will be investigated in detail.

**Comment by poisonnuke** [comment]
where can I find informations about the messages in flutter and maybe some hints how to debug?

**Comment by stuartmorgan** [comment]
https://docs.flutter.dev/testing/debugging has links to various information about debugging.

**Comment by poisonnuke** [comment]
ExoPlayer team figured out the issue:

DefaultHttpDataSource is the problem. It does not understand BasicAuth. There are three possible solutions:
switching to HttpEngineDataSource for SDK >= 34, using CRONET data source, or using the ResolvingDataSource wrapped around DefaultHttpDataSource.

Is anything of that a possbility with flutter?

**Comment by stuartmorgan** [comment]
> Could the team look into this issue and give a feedback if the issue can be solved on flutter end or not?

Please refer to my earlier comment:

>> Please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#when-will-my-bug-be-fixed. There is no timeframe on when a P2 issue will be investigated in detail.

Anyone interested in solving this issue is welcome to continue from [your findings](https://github.com/flutter/flutter/issues/150411#issuecomment-2302724229) to make a PR, which we would be happy to review.

**Comment by IsmoilAzamov** [comment]
I two tried different plugins video_player, better_player_plus. But the same error occurs when I use issue self-signed SSL. in iOS it is working fine.

I tried to wrap ExoPlayer with HttpOverrides but there is no single inherit of network requests as the plugins have lots of interactions with ExoPlayer.  Maybe we need to make video rendering package with pure dart code.
