### ISSUE TITLE
Flutter Ios - Cocoapods & Ruby issue...

### ISSUE THREAD

**Issue by jayptl-me** [flutter/flutter#150419]
I have been encountering this same issue since last year when I got my new mac m2 for IOS development with flutter(3.0) & cocoapods(1.10.2) it was working fine until I upgraded it to greater than 1.10.2!! I have tried 1.11.0, 1.13 & so on....currently I am working on 1.15.2!! Same error and I am unable to even de bug my code due to this error I dunno what is causing this I have tried everything from uninstalling - reinstalling and even terminal zhsrc shell's configuration like this -

```
export LANG=en_US.ASCII-8BIT
export lc_all=en_us.utf-8
export LC_ALL=en_US.UTF-8
LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$PATH:/Users/jayptl/src/homebrew/bin"
export PATH="$PATH:/Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin"
export PATH="$PATH:/Users/jayptl/src/flutter/bin"
export PATH="$PATH:$HOME/.pub-cache/bin"

export LC_ALL=en_US.UTF-8export JAVA_HOME=$(/usr/libexec/java_home)

export PATH="$PATH:/Users/jayptl/src/.bun/bin"
export PATH="$PATH:/usr/local/bin:$PATH"

export PATH="$PATH:/Users/jayptl/src/homebrew/opt/ruby/bin:$PATH"

export LDFLAGS="-L/Users/jayptl/src/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/Users/jayptl/src/homebrew/opt/ruby/include"


if [ -d "/Users/jayptl/src/homebrew/opt/ruby/bin" ]; then
  export PATH=/Users/jayptl/src/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi
```

Now the error encountered is -

```
Launching lib/main.dart on iPhone 15 Pro in debug mode...
CocoaPods' output:
↳
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        
    /Users/jayptl/src/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'
    /Users/jayptl/src/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'

Error running pod install

Error launching application on iPhone 15 Pro.
```

I have tried everything from uninstalling - reinstalling and even terminal zhsrc shell's configuration as shown above. I have tried reinstalling Cocoapods, rosetta, xCode, VsCode, android studio, flutter even...nothing helps it just works on 1.10.2 and that is depreciated I have some flutter packages such as firebase app check requiring Cocoapods 1.13.0 at least...at least higher than 1.10.2!!!

Flutter doctor shows nothing is wrong and everything is green!!

I am working on flutter 3.22.0 & Cocoapods 1.15.2(1.10.2 works just fine but depreciated.)

 I tried using bash terminal as well yet the same error with the same configuration.

<img width="1184" alt="Screenshot 2024-06-18 at 4 18 02 PM" src="https://github.com/flutter/flutter/assets/144714788/345a84aa-c570-4db1-9e28-cb998c0fda0d">

**Comment by danagbemava-nc** [comment]
Hi @jayptl-me, you've set certain values multiple times in your .*rc files. 

```
export LANG=en_US.ASCII-8BIT
export lc_all=en_us.utf-8
export LC_ALL=en_US.UTF-8
LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

This is likely the issue you're having with cocoapods. You most likely don't need 

```
export LANG=en_US.ASCII-8BIT
export lc_all=en_us.utf-8
export LC_ALL=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

You should also check your .*rc configurations. 

```
export LC_ALL=en_US.UTF-8export JAVA_HOME=$(/usr/libexec/java_home)
```

This is not properly formatted and could lead to other issues.

**Comment by jayptl-me** [comment]
I tried that same error.

**Comment by danagbemava-nc** [comment]
Can you share what your `.bashrc` or `.zshrc` looks like now?

**Comment by jayptl-me** [comment]
<img width="1391" alt="Screenshot 2024-06-25 at 5 25 17 PM" src="https://github.com/flutter/flutter/assets/144714788/d55d5304-46c7-4714-8e67-3964dbd38d6f">

I use zsh terminal for vs code. same error!

**Comment by danagbemava-nc** [comment]
Hi @jayptl-me, do you run `source ./*rc` after you make any changes? 

You might also want to check https://stackoverflow.com/questions/59405671/ios-cocoapods-requires-your-terminal-to-be-using-utf-8-encoding-after-latest. 

This is pretty much an issue with your terminal configuration and there isn't much we can do to fix it other than offer guidance. 

You might also want to check https://github.com/CocoaPods/CocoaPods/issues/6333

I'll be closing this since this is not a flutter issue. 

Thank you
