### ISSUE TITLE
[Flutter WASM] Images may not be rendered properly when scrolling

### ISSUE THREAD

**Issue by mit-73** [flutter/flutter#150502]
### Steps to reproduce

1. `flutter build web --wasm --no-strip-wasm`
2. `cd build/web`
3. `dart pub global run dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'`
4. open browser: `localhost:8080`

### Expected results

The application works without errors.

<details open>
<summary>Screenshots / Video demonstration</summary>

![screenshot](https://github.com/flutter/flutter/assets/43699145/2c15ae7b-2099-42d4-b9a7-0b16ab17692a)

</details>

### Actual results

An error comes out, the window hangs.

<details open>
<summary>Screenshots / Video demonstration</summary>

![screenshot](https://github.com/flutter/flutter/assets/43699145/58fcf364-50b6-4d6e-bcf3-a66d756d42a3)
![screenshot](https://github.com/flutter/flutter/assets/43699145/71cf8133-6d3d-448f-a2a3-8db8f1a56201)
![screenshot](https://github.com/flutter/flutter/assets/43699145/39769a48-143d-49b3-8b1e-fd84b892786d)

</details>

### Code sample

[Code sample](https://github.com/mit-73/flutter_wasm_bug)

### Logs

<details open><summary>Logs</summary>

```console
worker sent an error! https://www.gstatic.com/flutter-canvaskit/55eae6864b296dd9f43b2cc7577ec256e5c32a8d/skwasm.wasm:1: Uncaught RuntimeError: memory access out of bounds
a.onerror @ skwasm.js:25
error (async)
(anonymous) @ skwasm.js:25
ba @ skwasm.js:24
ta @ skwasm.js:26
(anonymous) @ skwasm.js:23
hb @ skwasm.js:27
td @ skwasm.js:159
sd @ skwasm.js:158
Oa @ skwasm.js:16
a @ skwasm.js:101
(anonymous) @ flutter_bootstrap.js:3
await in (anonymous) (async)
(anonymous) @ flutter_bootstrap.js:3
(anonymous) @ skwasm.js:101
(anonymous) @ skwasm.js:101
(anonymous) @ flutter_bootstrap.js:3
load (async)
(anonymous) @ flutter_bootstrap.js:3
_ @ flutter_bootstrap.js:3
load @ flutter_bootstrap.js:3
await in load (async)
(anonymous) @ flutter_bootstrap.js:12


Uncaught ErrorEvent {isTrusted: true, message: 'Uncaught RuntimeError: memory access out of bounds', filename: 'https://www.gstatic.com/flutter-canvaskit/55eae6864b296dd9f43b2cc7577ec256e5c32a8d/skwasm.wasm', lineno: 1, colno: 41129, …}
a.onerror @ skwasm.js:26
error (async)
(anonymous) @ skwasm.js:25
ba @ skwasm.js:24
ta @ skwasm.js:26
(anonymous) @ skwasm.js:23
hb @ skwasm.js:27
td @ skwasm.js:159
sd @ skwasm.js:158
Oa @ skwasm.js:16
a @ skwasm.js:101
(anonymous) @ flutter_bootstrap.js:3
await in (anonymous) (async)
(anonymous) @ flutter_bootstrap.js:3
(anonymous) @ skwasm.js:101
(anonymous) @ skwasm.js:101
(anonymous) @ flutter_bootstrap.js:3
load (async)
(anonymous) @ flutter_bootstrap.js:3
_ @ flutter_bootstrap.js:3
load @ flutter_bootstrap.js:3
await in load (async)
(anonymous) @ flutter_bootstrap.js:12


Uncaught RuntimeError: memory access out of bounds
    at skwasm.wasm:0xa0a8
    at skwasm.wasm:0x1e5318
    at f (skwasm.js:61:400)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
% fvm flutter doctor -v                                                                                                        
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.2.1 23C71 darwin-arm64, locale ru-RU)
    • Flutter version 3.22.1 on channel stable at /Users/user/SDK/flutter/versions/3.22.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/user/SDK/android_studio
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/user/SDK/android_studio
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by mit-73** [comment]
Clarification: if you use canvas/html renderer everything works as it should, no problems are observed.

**Comment by danagbemava-nc** [comment]
Hi @mit-73, I noticed the web directory is missing from your code sample. I recreated it but when I ran the `flutter build web --wasm --no-strip-wasm` command, I get the error below. Can you share a complete project that builds? 

```
┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/wasm for more information.                                     │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.


../../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/lib/src/svg/_tessellator_ffi.dart:6:1: Error: 'dart:ffi' can't be
imported when compiling to Wasm.
import 'dart:ffi' as ffi;
^
../../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/lib/src/svg/_path_ops_ffi.dart:6:1: Error: 'dart:ffi' can't be imported
when compiling to Wasm.
import 'dart:ffi' as ffi;
^
  Command: /Users/nexus/dev/sdks/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--dart-sdk=/Users/nexus/dev/sdks/flutter/bin/cache/dart-sdk
  --extra-compiler-option=--platform=/Users/nexus/dev/sdks/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui --extra-compiler-option=--delete-tostring-package-uri=package:flutter
  --extra-compiler-option=--import-shared-memory --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/
  -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  --extra-compiler-option=--depfile=/Users/nexus/Downloads/flutter_wasm_bug/.dart_tool/flutter_build/4fdf32e3f71d02b76e34cf45605086e2/dar
  t2wasm.d -O4 --name-section -o
  /Users/nexus/Downloads/flutter_wasm_bug/.dart_tool/flutter_build/4fdf32e3f71d02b76e34cf45605086e2/main.dart.wasm
  /Users/nexus/Downloads/flutter_wasm_bug/.dart_tool/flutter_build/4fdf32e3f71d02b76e34cf45605086e2/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:329:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             34.8s
Error: Failed to compile application for the Web.
```

**Comment by mkustermann** [comment]
> Hi @mit-73, I noticed the web directory is missing from your code sample. I recreated it but when I ran the flutter build web --wasm --no-strip-wasm command, I get the error below. Can you share a complete project that builds?
> 
> ```
> Error: 'dart:ffi' can't be imported ...
> ```

@danagbemava-nc  this is completely unrelated. That issue requires changing `package:vector_graphics_compiler`, see  https://github.com/dnfield/vector_graphics/issues/244

**Comment by mit-73** [comment]
@mkustermann @danagbemava-nc cleaned up the repository and added a web directory. I have no problems with the build.

**Comment by danagbemava-nc** [comment]
Hi @mit-73, it would appear that this has been fixed on the master channel. I see the image as expected with on errors in the console. See the screenshot below. Can you confirm if this is the case for you as well? 

<img width="1792" alt="Screenshot 2024-06-21 at 07 36 20" src="https://github.com/flutter/flutter/assets/88313112/fea478dc-5efa-4cc4-a396-786913e1a8fc">

**Comment by mit-73** [comment]
Hi @danagbemava-nc, it looks like the solution works as intended on the main channel. However, it is important to note that images can disappear or enlarge when scrolling. This behavior was not observed on the canvas.

**Comment by danagbemava-nc** [comment]
The issue with the runtime memory out of bounds has been fixed on master so I am changing this to track the issue with the image reported in https://github.com/flutter/flutter/issues/150502#issuecomment-2182617364

I can reproduce the issue with the images disappearing on scrolling on the master channel. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.23.0-13.0.pre.313, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.23.0-13.0.pre.313 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 778eaf6c1d (6 hours ago), 2024-06-25 01:20:29 +0000
    • Engine revision be7db94196
    • Dart version 3.5.0 (build 3.5.0-293.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.115

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by eyebrowsoffire** [comment]
The most recent platform view fixes in skwasm should have resolved this issue. @mit-73 can you verify that this is fixed on the flutter master branch?

**Comment by mit-73** [comment]
Hi @eyebrowsoffire, most of the issues have been resolved.  But I have another problem: if I scroll backwards (from bottom to top) we suddenly appear at the very top. It looks like Scrollbar is getting the wrong dimensions for the height of the pictures.

https://github.com/user-attachments/assets/36674adf-b176-4f8d-9a90-7b1f11c77ade

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/issues/150502#issuecomment-2268856609 is not related to Web or Wasm.

It has something to do with the implementation of the app's `Picture` widget and its interaction with scrolling.

This reduced version of the app's Web implementation of `Picture` reproduces the issue on non-web platforms:

```
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:wasm_bug/data_provider.dart';

import 'common.dart';

class Picture extends StatelessWidget {
  const Picture(
    this.url, {
    super.key,
    this.boxFit,
    this.height,
    this.width,
    this.color,
    this.gradient,
    this.errorPlaceHolder,
    this.errorPlaceHolderColor,
    this.onRefresh,
    this.loadingWidget,
  });

  final String url;
  final BoxFit? boxFit;
  final double? height;
  final double? width;
  final Color? color;
  final Gradient? gradient;
  final Widget? errorPlaceHolder;
  final Color? errorPlaceHolderColor;
  final VoidCallback? onRefresh;
  final Widget? loadingWidget;

  @override
  Widget build(BuildContext context) {
    return PictureDataProvider(
      url: url,
      boxFit: boxFit,
      height: height,
      width: width,
      color: color,
      gradient: gradient,
      errorPlaceholder: errorPlaceHolder,
      errorPlaceholderColor: errorPlaceHolderColor,
      onRefresh: onRefresh,
      loadingWidget: loadingWidget,
      child: const _WebPicture(),
    );
  }
}

class _WebPicture extends StatefulWidget {
  const _WebPicture();

  @override
  State<_WebPicture> createState() => _WebPictureState();
}

class _WebPictureState extends State<_WebPicture> {
  PictureDataProvider get pictureProvider =>
      DataProvider.of<PictureDataProvider>(context, listen: false);

  final _haveError = ValueNotifier<bool>(false);

  StreamSubscription<void>? onErrorSubscription;

  @override
  void initState() {
    super.initState();
    changeToHtml();
  }

  @override
  void dispose() {
    onErrorSubscription?.cancel();
    super.dispose();
  }

  void changeToHtml() {
    Stream<void> stream = Stream<void>.fromFuture(
      Future<void>.delayed(Duration(milliseconds: 100)));
    onErrorSubscription = stream.listen((_) {
      _haveError.value = true;
    });
  }

  @override
  Widget build(BuildContext context) {
    final PictureDataProvider pictureProvider =
        DataProvider.of<PictureDataProvider>(context);

    return SizedBox(
      width: pictureProvider.width,
      height: pictureProvider.height,
      child: ListenableBuilder(
        listenable: _haveError,
        builder: (context, _) {
          if (_haveError.value) {
            return Icon(Icons.refresh, size: 1000);
          }
          return Text('Loading', style: TextStyle(fontSize: 40));
        },
      ),
    );
  }
}
```

**Comment by mit-73** [comment]
Yeah, that's a point I missed... Then I guess there's no more problems and the issue can be closed.

Thank you all for such a prompt resolution to the bug!

**Comment by eyebrowsoffire** [comment]
Awesome, thanks for verifying!
