### ISSUE TITLE
Flutter web+wasm app fails to load when referencing strokeMiterLimit

### ISSUE THREAD

**Issue by tdenniston** [flutter/flutter#150591]
### Steps to reproduce

Create a new blank app:
```
$ flutter create wasmtest
$ cd wasmtest
$ vim lib/main.dart
```

Patch `lib/main.dart` to reference `strokeMiterLimit`, e.g.:
```dart
import 'dart:ui';
// .. snip ..
  @override
  Widget build(BuildContext context) {
    final paint = Paint();
    print('${paint.strokeMiterLimit}');  // Add these lines
    return MaterialApp(
// .. snip
```

Build:
```
flutter build web --wasm
```

Serve the app (e.g. as described at [https://docs.flutter.dev/platform-integration/web/wasm#serving-wasm-locally](https://docs.flutter.dev/platform-integration/web/wasm#serving-wasm-locally).

Visit the app in Chrome, and observe that the app fails to load, with this message printed in console:
```
main.dart.mjs:689 Uncaught (in promise) 
LinkError: WebAssembly.instantiate(): Import #537 "skwasm" "paint_getMiterLimit": function import requires a callable
    at Module.instantiate (main.dart.mjs:689:38)
    at async f._loadWasmEntrypoint (flutter_bootstrap.js:1:2259)
instantiate	@	main.dart.mjs:689
```

### Expected results

Able to reference `strokeMiterLimit` in a wasm build.

### Actual results

App fails to load and error message is printed to console:
```
main.dart.mjs:689 Uncaught (in promise) 
LinkError: WebAssembly.instantiate(): Import #537 "skwasm" "paint_getMiterLimit": function import requires a callable
    at Module.instantiate (main.dart.mjs:689:38)
    at async f._loadWasmEntrypoint (flutter_bootstrap.js:1:2259)
instantiate	@	main.dart.mjs:689
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:ui';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final paint = Paint();
    print('${paint.strokeMiterLimit}');
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

// Rest of example app omitted for brevity.
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\username\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code, 64-bit edition (version 1.90.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @tdenniston, it would appear that this has been fixed on the master channel. The app loads just fine with the code changes on the master for me. Can you confirm if this is the same for you as well? 


<img width="1792" alt="Screenshot 2024-06-21 at 07 37 47" src="https://github.com/flutter/flutter/assets/88313112/0b2b326e-f54b-41e5-99fc-29ae486f082c">

**Comment by tdenniston** [comment]
Thanks @danagbemava-nc, tested on the master channel (3.23.0-13.0.pre.292) and it is indeed fixed. Appreciate it!
