### ISSUE TITLE
flutter js error when deploy to ubuntu nginx server

### ISSUE THREAD

**Issue by ThwinHAung** [flutter/flutter#150686]
I deploy flutter web and laravel as backend api to server but I got these error when open console

`js_helper.dart:1190 Uncaught 
    at Object.e (https://championmaung.com/main.dart.js:5172:19)
    at Object.aJo (https://championmaung.com/main.dart.js:7205:9)
    at a9Y.hM (https://championmaung.com/main.dart.js:45367:19)
    at a9Y.be (https://championmaung.com/main.dart.js:45369:21)
    at https://championmaung.com/main.dart.js:51037:14
    at ay9.a (https://championmaung.com/main.dart.js:6545:63)
    at ay9.$2 (https://championmaung.com/main.dart.js:43430:14)
    at axm.$1 (https://championmaung.com/main.dart.js:43424:21)
    at arn.av9 (https://championmaung.com/main.dart.js:44040:34)
    at arn.LD (https://championmaung.com/main.dart.js:44043:13)
e @ js_helper.dart:1190
aPW @ core_patch.dart:277
aPX @ errors.dart:120
$0 @ zone.dart:1386
aWN @ schedule_microtask.dart:40
aX_ @ schedule_microtask.dart:49
$1 @ async_patch.dart:48
childList (async)
$1 @ async_patch.dart:61
aJy @ async_patch.dart:26
xJ @ zone.dart:1466
a7X @ zone.dart:1681
mh @ future_impl.dart:695
d1 @ future_impl.dart:291
aZ @ streams.dart:196
aVE @ stream_pipe.dart:57
$1 @ stream.dart:1589
$1 @ streams.dart:218
aRP @ js_helper.dart:914
aVA @ js_allow_interop_patch.dart:55
(anonymous) @ js_allow_interop_patch.dart:33
load (async)
UH @ streams.dart:253
KY @ streams.dart:219
gP @ stream.dart:1588
(anonymous) @ browser_client.dart:71
(anonymous) @ async_patch.dart:303
$2 @ async_patch.dart:328
$1 @ async_patch.dart:279
av9 @ zone.dart:1661
LD @ zone.dart:1660
$0 @ future_impl.dart:128
wQ @ future_impl.dart:890
tB @ future_impl.dart:666
$0 @ future_impl.dart:736
aWN @ schedule_microtask.dart:40
aX_ @ schedule_microtask.dart:49
$1 @ async_patch.dart:48
childList (async)
$1 @ async_patch.dart:61
aJy @ async_patch.dart:26
xJ @ zone.dart:1466
a7X @ zone.dart:1681
mh @ future_impl.dart:695
fF @ future_impl.dart:44
ix @ future_impl.dart:42
Uz @ ticker.dart:417
aBm @ ticker.dart:407
hF @ animation_controller.dart:685
Om @ animation_controller.dart:650
jX @ animation_controller.dart:498
bM @ animation_controller.dart:478
qP @ ink_ripple.dart:194
YH @ ink_well.dart:1163
(anonymous) @ js_helper.dart:2249
Zg @ recognizer.dart:344
d6 @ recognizer.dart:331
YJ @ tap.dart:652
OS @ tap.dart:309
YF @ tap.dart:242
iF @ recognizer.dart:696
(anonymous) @ js_helper.dart:2259
aac @ pointer_router.dart:98
$2 @ pointer_router.dart:143
ac @ linked_hash_map.dart:195
PN @ pointer_router.dart:141
a04 @ pointer_router.dart:127
kL @ binding.dart:495
apg @ binding.dart:475
Ri @ binding.dart:450
K8 @ binding.dart:383
FI @ binding.dart:330
aea @ binding.dart:299
(anonymous) @ js_helper.dart:2259
mQ @ platform_dispatcher.dart:1420
att @ platform_dispatcher.dart:333
(anonymous) @ js_helper.dart:2269
pV @ main.dart.js:37027
$1 @ pointer_binding.dart:1001
$1 @ pointer_binding.dart:930
$1 @ pointer_binding.dart:531
aRP @ js_helper.dart:914
aVA @ js_allow_interop_patch.dart:55
(anonymous) @ js_allow_interop_patch.dart:33Understand this error
2js_helper.dart:1190 Uncaught 
    at Object.e (https://championmaung.com/main.dart.js:5172:19)
    at Object.aJo (https://championmaung.com/main.dart.js:7205:9)
    at a9Y.hM (https://championmaung.com/main.dart.js:45367:19)
    at a9Y.be (https://championmaung.com/main.dart.js:45369:21)
    at https://championmaung.com/main.dart.js:51037:14
    at ay9.a (https://championmaung.com/main.dart.js:6545:63)
    at ay9.$2 (https://championmaung.com/main.dart.js:43430:14)
    at axm.$1 (https://championmaung.com/main.dart.js:43424:21)
    at arn.av9 (https://championmaung.com/main.dart.js:44040:34)
    at arn.LD (https://championmaung.com/main.dart.js:44043:13)`

**Comment by huycozy** [comment]
Hi @ThwinHAung, 
For the issue to be workable, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that illustrates the problem.

And please also provide the following information:
- The output of `flutter doctor -v` to show the version of Flutter you are seeing this issue on
- Reproduction steps if needed. Does the issue only occur on nginx server or any other servers? Do you see it when running app in local machine?
