### ISSUE TITLE
Key pressed but now showing up, but displaying error in the terminal

### ISSUE THREAD

**Issue by flochristos** [flutter/flutter#150697]
```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message
callback:
A KeyUpEvent is dispatched, but the state shows that the
physical key is not pressed. If this occurs
in real application, please report this bug to Flutter. If
this occurs in unit tests, please ensure
that simulated events follow Flutter's event model as
documented in `HardwareKeyboard`. This was the
event: KeyUpEvent#fd749(physicalKey:
PhysicalKeyboardKey#c222c(usbHidUsage: "0x0007001d",
debugName:
"Key Z"), logicalKey: LogicalKeyboardKey#5989a(keyId:
"0x0000007a", keyLabel: "Z", debugName: "Key
Z"), character: null, timeStamp: 5:42:09.546916)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 509 pos 16:
'_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework
itself, or we should provide substantially
more information in this error message to help you determine
and fix the underlying cause.
In either case, please report this assertion by filing a bug
on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bu
  g.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous
closure>
(package:flutter/src/services/hardware_keyboard.dart:509:16)
#3      HardwareKeyboard._assertEventIsRegular
(package:flutter/src/services/hardware_keyboard.dart:520:6)
#4      HardwareKeyboard.handleKeyEvent
(package:flutter/src/services/hardware_keyboard.dart:643:5)
#5      KeyEventManager.handleRawKeyMessage
(package:flutter/src/services/hardware_keyboard.dart:1167:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous
closure>
(package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous
closure> (package:flutter/src/services/binding.dart:603:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke
(dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push
(dart:ui/channel_buffers.dart:343:17)
#12     PlatformDispatcher._dispatchPlatformMessage
(dart:ui/platform_dispatcher.dart:737:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
═════════════════════════════════════════════════════════════
═══════════════════════════════════════

Another exception was thrown: A KeyUpEvent is dispatched, but
the state shows that the physical key is not pressed. If this
occurs in real application, please report this bug to
Flutter. If this occurs in unit tests, please ensure that
simulated events follow Flutter's event model as documented
in `HardwareKeyboard`. This was the event:
KeyUpEvent#fd749(physicalKey:
PhysicalKeyboardKey#c222c(usbHidUsage: "0x0007001d",
debugName: "Key Z"), logicalKey:
LogicalKeyboardKey#5989a(keyId: "0x0000007a", keyLabel: "Z",
debugName: "Key Z"), character: null, timeStamp:
5:42:09.546916)
```

**Comment by darshankawar** [comment]
@flochristos 
Can you provide `flutter doctor -v` and platform (windows, web) in which you are seeing this exception ?
Assuming you are using physical keyboard to input and then pressing Z key is throwing this exception, is this correct interpretation ?  If not, please provide replication pattern and code sample.

**Comment by flochristos** [comment]
When i restarted, everything was fine, i only could salvage that info from terminal log. @darshankawar

**Comment by darshankawar** [comment]
Thanks for the update. If you see the same crash again and have concrete replication steps or pattern, write in comments and I'll reopen it. Closing for now.
