### ISSUE TITLE
iOS crash on startup due to Unable to read Dart source 'package:flutter/material.dart'.

### ISSUE THREAD

**Issue by matthewtsmith** [flutter/flutter#15070]
I recently upgraded to the beta channel. 

When I run `flutter run` I get the output of:

```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                1.0s
Starting Xcode build...                                   
 ├─Assembling Flutter resources...             1.8s
 └─Compiling, linking and signing...           3.6s
Xcode build done                                      6.9s
Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 52193
```

The app crashes on startup which led me to run it from Xcode. When I do that, the console outputs 

`Unable to read Dart source 'package:flutter/material.dart'.`

before crashing.

Here is my flutter doctor:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.12.6 16G1036, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[✓] VS Code (version 1.20.1)
[✓] Connected devices (2 available)

• No issues found!
MacBook-Pro-3:mobile_client matthew$ flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.12.6 16G1036, locale en-US)
    • Flutter version 0.1.5 at /users/matthew/flutter
    • Framework revision 3ea4d06340 (8 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/matthew/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/matthew/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.0

[✓] Connected devices (2 available)
    • Matthew’s iPhone • 8fc1e1f4bf9da438d662fb2872d3f7b0adb266f9 • ios • iOS 11.2.6
    • iPhone X         • 09DD8734-6D76-4811-8F3E-395B0B4CF434     • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by matthewtsmith** [comment]
I tried to run flutter run with bug reporting turned on but it's getting hung on:

```
[ +104 ms] Scanning asset files
[   +3 ms] Scanning for deleted files
[  +10 ms] Updating files
[   +5 ms] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 54532
[        ] "flutter run" took 22,005ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:351)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#3      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#7      new Future.sync (dart:async/future.dart:222)
#8      CommandRunner.run (package:args/command_runner.dart:109)
#9      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#10     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#11     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#12     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#17     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#19     main (file:///users/matthew/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


[ +256 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Invalid VMService message data detected: {jsonrpc: 2.0, method: _registerService, params: {service: reloadSources, alias: Flutter Tools}}
``` 

So I'm currently unable to attach that.

**Comment by Hixie** [comment]
Strange. Do you have any unusual firewalls or anything like that?

**Comment by matthewtsmith** [comment]
@Hixie No firewalls running or anything like that. I started it up this morning to try and collect some more info but it's now able to run on iOS. Not sure what changed but I'll go ahead and close this issue.
