### ISSUE TITLE
[Web] - Crashes when running local development during hot restart

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#150760]
### Steps to reproduce

I don't have a consistent set of reproduction steps. As I'm working on a web app, making code changes, and automatically running Hot Restart through Android Studio, the whole test browser crashes and forces me to rebuild and relaunch.

I've included a random example of error output when the crash happens.

### Expected results

Hot Restart gracefully handles changes to code, including momentary invalid code.

### Actual results

While working on live code in debug mode in the test browser, the whole browser crashes and disappears.

### Code sample

I don't have a code sample for this. It happens regardless which file I'm working in.

### Logs

<details open><summary>Logs</summary>

```console
Performing hot restart...
Waiting for connection from debug service on Chrome...
../../../../../DevLibs/flutter/packages/flutter/lib/src/rendering/layer.dart:1068:13: Error: The method 'setRasterizerTracingThreshold' isn't defined for the class 'SceneBuilder'.
 - 'SceneBuilder' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'setRasterizerTracingThreshold'.
    builder.setRasterizerTracingThreshold(rasterizerThreshold);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../DevLibs/flutter/packages/flutter/lib/src/rendering/layer.dart:1069:13: Error: The method 'setCheckerboardRasterCacheImages' isn't defined for the class 'SceneBuilder'.
 - 'SceneBuilder' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'setCheckerboardRasterCacheImages'.
    builder.setCheckerboardRasterCacheImages(checkerboardRasterCacheImages);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../DevLibs/flutter/packages/flutter/lib/src/rendering/layer.dart:1070:13: Error: The method 'setCheckerboardOffscreenLayers' isn't defined for the class 'SceneBuilder'.
 - 'SceneBuilder' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'setCheckerboardOffscreenLayers'.
    builder.setCheckerboardOffscreenLayers(checkerboardOffscreenLayers);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
file:///Users/matt/Projects/super_editor/super_editor/clones/quill/lib/editor/editor.dart: No class info for FeatherEditor
#0      ClosedWorldClassHierarchy.infoFor (package:kernel/class_hierarchy.dart:714)
#1      ClosedWorldClassHierarchy.getClassAsInstanceOf (package:kernel/class_hierarchy.dart:1045)
#2      ProgramCompiler._emitIterable (package:dev_compiler/src/kernel/compiler.dart:2397)
#3      ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2075)
#4      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:905)
#5      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#6      List.forEach (dart:core-patch/growable_array.dart:417)
#7      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#8      List.forEach (dart:core-patch/growable_array.dart:417)
#9      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#10     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:221)
#11     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:869)
<asynchronous suspension>
#12     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:1038)
<asynchronous suspension>
#13     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1464)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (3 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

</details>

**Comment by matthew-carroll** [comment]
CC @kevmoo @yjbanov

**Comment by mraleph** [comment]
cc @nshahan

**Comment by huycozy** [comment]
I also can't reproduce this issue (only tried with a new Flutter project). Labeling this for team's tracking.

**Comment by nshahan** [comment]
@matthew-carroll
The stack trace you posted shows a crash in the web development compiler (DDC) while trying to calculate how a class is representable as an `Iterable` supertype. In that process it failed to find information for the class `FeatherEditor`. If possible I'd like to look at the class hierarchy to understand more about what could be a possible reproduction. Does the file uri printed translate to some open source repo I can see? `file:///Users/matt/Projects/super_editor/super_editor/clones/quill/lib/editor/editor.dart`

@elliette @bkonyi 
I'm not familiar with the android studio integration. Is there a separate codebase for this or would you expect similar problems to appear in vscode?

**Comment by elliette** [comment]
> I'm not familiar with the android studio integration. Is there a separate codebase for this or would you expect similar problems to appear in vscode?

Android Studio vs VS Code shouldn't make a difference here, this should be reproducible from VS Code as well.

**Comment by matthew-carroll** [comment]
@nshahan it is open source, but not merged yet. Just a private branch. But `FeatherEditor` is a `StatefulWidget`. No other inheritance or mixins applied to it other than `extends StatefulWidget`.

**Comment by matthew-carroll** [comment]
Here's another stack trace:

```
lib/deltas/deltas_display.dart:6:9: Error: Type 'Editor' not found.
  final Editor editor;
        ^^^^^^
lib/deltas/deltas_display.dart:6:9: Error: 'Editor' isn't a type.
  final Editor editor;
        ^^^^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///Users/matt/Projects/super_editor/super_editor/clones/quill/lib/deltas/deltas_display.dart, which contains the type: InvalidType(<invalid>).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3227)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3188)
#2      ProgramCompiler._emitClassFieldSignature (package:dev_compiler/src/kernel/compiler.dart:1641)
#3      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1617)
#4      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:962)
#5      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#6      List.forEach (dart:core-patch/growable_array.dart:417)
#7      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#8      List.forEach (dart:core-patch/growable_array.dart:417)
#9      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#10     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:221)
#11     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:869)
<asynchronous suspension>
#12     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:1038)
<asynchronous suspension>
#13     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1464)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
```

This crash seems to happen when I'm in the middle of editing and there are references in my code that aren't connected yet. Of course, these things happen when developers move from file to file and write code. These intermediate broken states don't cause problems when running on desktop and mobile, and I don't think this used to happen on web, but it does now.

**Comment by jensjoha** [comment]
Oh, and a reproduction:

flutter create a new project, then put in
`main.dart:`
```dart
import 'package:flutter/material.dart';
import 'foo.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  Foo foo = new Foo();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              foo.pressedText(),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

`foo.dart`:
```dart
class Foo {
  String pressedText() => 'You have pushed the button this many times:';
}
```

flutter run in chrome, once it's ready change `foo.dart` to for instance

```dart
class FooX {
  String pressedText() => 'You have pushed the button this many times:';
}
```

and reload and I get:

```
Performing hot restart...                                       
lib/main.dart:35:3: Error: Type 'Foo' not found.
  Foo foo = new Foo();
  ^^^
lib/main.dart:35:3: Error: 'Foo' isn't a type.
  Foo foo = new Foo();
  ^^^
lib/main.dart:35:17: Error: Couldn't find constructor 'Foo'.
  Foo foo = new Foo();
                ^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling
file:///usr/local/google/home/jensj/code/nobackup/flutter/tmp/issue_150760/lib/main.dart, which contains the type: InvalidType(<invalid>).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3236)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3197)
#2      ProgramCompiler._emitClassFieldSignature (package:dev_compiler/src/kernel/compiler.dart:1651)
#3      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1627)
#4      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:962)
#5      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:819)
#6      List.forEach (dart:core-patch/growable_array.dart:416)
#7      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:757)
#8      List.forEach (dart:core-patch/growable_array.dart:416)
#9      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#10     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#11     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:801)
<asynchronous suspension>
#12     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:966)
<asynchronous suspension>
#13     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1389)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Performing hot restart...                                          160ms
```

**Comment by nshahan** [comment]
cc @Markzipan
This is the issue we were discussing. Maybe you could take a look to see if the flutter infra is correctly recognizing errors from the frontend server responses before attempting to compile with DDC.

**Comment by darshankawar** [comment]
@nshahan Hello, should this be tracked in dart-lang repo ? as most likely it seems to be related to `web-dev-compiler` and `area-web`

**Comment by nshahan** [comment]
It doesn't exactly sound like a `web-dev-compiler` issue to me because something in the tooling is sending invalid code to the compiler and it is crashing because it assumes the nodes to be well formed at that point. It could be that the code doing this is in the Dart SDK somewhere so I'm fine with you moving the issue if you want.

I would be nice to have a repro that doesn't involve flutter though.
