### ISSUE TITLE
impeller-cmake-example builder broken: fails to locate unable to locate cmake

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#150870]
Example of breakage: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8744040972625785457/+/u/gn_--impeller-cmake-example_--xcode-symlinks/stdout

```
Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/ci/impeller_cmake_build_test.py", line 138, in <module>
    sys.exit(main(sys.argv))
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/ci/impeller_cmake_build_test.py", line 132, in main
    subprocess.check_call(cmake_command, env=cmake_env, cwd=impeller_cmake_dir)
  File "/Volumes/Work/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Volumes/Work/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Volumes/Work/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Volumes/Work/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Work/s/w/ir/cache/builder/src/buildtools/mac-x64/cmake/bin/cmake'
```

**Comment by christopherfujino** [comment]
@bdero I'm guessing the path in your script is wrong? https://github.com/flutter/engine/blob/main/DEPS#L1010
