### ISSUE TITLE
Timing issue with overlay (Overlay not ready in MaterialApp context)

### ISSUE THREAD

**Issue by EistenGaming** [flutter/flutter#150878]
### Steps to reproduce

1. Start app (windows native)
2. Try to show an overlay during initialization phase of the app (i want it to report a failed connection test to the user)

### Expected results

The overlay is displayed (see the test call at line 165 in main.dart (attached)

### Actual results

The overlay is not shown, context is null

### Code sample

<details open><summary>Code sample</summary>

```

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'base_layout.dart';
import 'networking.dart';
import 'logger.dart';
import 'user_manager.dart';
import 'splash_screen.dart';
import 'overlay_service.dart'; // Import the OverlayService

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await LoggerService.init();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => EveAppState()),
        Provider<ApiService>(create: (_) => ApiService()),
      ],
      child: MaterialApp(
        title: 'Eve Client',
        navigatorKey: OverlayService.navigatorKey, // Set the navigatorKey
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color.fromARGB(255, 117, 130, 137),
            brightness: Brightness.dark,
          ),
          textTheme: TextTheme(
            displayLarge: const TextStyle(
              fontSize: 57,
              fontWeight: FontWeight.bold,
            ),
            displayMedium: const TextStyle(
              fontSize: 45,
              fontWeight: FontWeight.bold,
            ),
            displaySmall: const TextStyle(
              fontSize: 36,
              fontWeight: FontWeight.normal,
            ),
            headlineLarge: const TextStyle(
              fontSize: 32,
              fontWeight: FontWeight.normal,
            ),
            headlineMedium: const TextStyle(
              fontSize: 28,
              fontWeight: FontWeight.normal,
            ),
            headlineSmall: const TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.normal,
            ),
            titleLarge: const TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.normal,
            ),
            titleMedium: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.normal,
            ),
            titleSmall: const TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.normal,
            ),
            labelLarge: const TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.normal,
            ),
            labelMedium: const TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.normal,
            ),
            labelSmall: const TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.normal,
            ),
            bodyLarge: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.normal,
            ),
            bodyMedium: const TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.normal,
            ),
            bodySmall: const TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.normal,
            ),
          ),
        ),
        home: Scaffold(
          body: FutureBuilder(
            future: _initializeApp(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return SplashScreen();
              } else {
                return BaseLayout();
              }
            },
          ),
        ),
      ),
    );
  }

  Future<void> _initializeApp() async {
    // Perform any necessary initialization tasks here
    await Future.delayed(Duration(seconds: 2)); // Simulate a delay for initialization
    // Ensure EveAppState is initialized after the MaterialApp is built
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final context = navigatorKey.currentContext;
      if(context != null){
        Provider.of<EveAppState>(navigatorKey.currentContext!, listen: false).initialize();
        Provider.of<EveAppState>(navigatorKey.currentContext!, listen: false)._autoSignIn();
      }
    });
  }
}

class EveAppState extends ChangeNotifier {
  bool _isSignedIn = false;

  bool get isSignedIn => _isSignedIn;

  EveAppState() {
    // Constructor remains empty
  }

  void initialize() {
    // WidgetsBinding.instance.addPostFrameCallback((_) {
    //   _autoSignIn();
    // });
  }

  Future<void> _autoSignIn() async {
    String? username = await UserDataManager.getUserData('username');
    String? password = await UserDataManager.getUserData('password');
    
    if (username != null && password != null) {
      await signIn(username, password);
    }
  }

  Future<void> signIn(String username, String password) async {
    final apiService = ApiService();
    bool success = await apiService.login(username, password);
    if (success) {
      _isSignedIn = true;
      notifyListeners();
      LoggerService.logger.info('User signed in successfully');
      
      // Save user credentials
      await UserDataManager.saveUserData('username', username);
      await UserDataManager.saveUserData('password', password);
    } else {
      // Handle login failure (e.g., show an error message)
      OverlayService.showOverlay("TEST", Severity.error);
      LoggerService.logger.warning('Login failed for user: $username');
    }
  }

  void signOut() {
    _isSignedIn = false;
    notifyListeners();
    LoggerService.logger.info('User signed out');
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
(eveenv) D:\dev\eve>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22635.3790], locale
    en-CH)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.2)
[!] Android Studio (not installed)
[✓] VS Code, 64-bit edition (version 1.90.2)
[✓] VS Code (version 1.75.0-insider)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by EistenGaming** [comment]
and here's the overlay_service.dart:

```dart
import 'package:flutter/material.dart';

class OverlayService {
  static final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  static void showOverlay(String message, Severity severity) {
    final context = navigatorKey.currentContext;
    if (context == null) return;

    WidgetsBinding.instance.addPostFrameCallback((_) {
      final overlay = Overlay.of(context);
      //if (overlay == null) return;

      final overlayEntry = OverlayEntry(
        builder: (context) => Positioned(
          top: 50.0, // Adjust this value to position the overlay at the desired height
          right: 20.0, // Align to the right
          child: Material(
            color: Colors.transparent,
            child: Container(
              constraints: BoxConstraints(maxWidth: 200.0), // Set max width to 200 pixels
              padding: EdgeInsets.symmetric(horizontal: 24.0, vertical: 12.0),
              decoration: BoxDecoration(
                color: _getBackgroundColor(context, severity).withOpacity(0.9), // 10% transparent
                borderRadius: BorderRadius.circular(10.0),
                border: Border.all(
                  color: _getBorderColor(context, severity),
                  width: 2.0,
                ),
              ),
              child: Text(
                message,
                style: TextStyle(color: _getTextColor(severity)),
              ),
            ),
          ),
        ),
      );

      overlay.insert(overlayEntry);

      // Remove the overlay after a delay (optional)
      Future.delayed(Duration(seconds: 3), () {
        overlayEntry.remove();
      });
    });
  }

  static Color _getBackgroundColor(BuildContext context, Severity severity) {
    switch (severity) {
      case Severity.info:
        return Colors.blue.withOpacity(0.8); // 10% transparent;
      case Severity.warning:
        return Colors.deepOrange.withOpacity(0.8); 
      case Severity.error:
        return Colors.red.withOpacity(0.8); 
      default:
        return Theme.of(context).colorScheme.surface;
    }
  }

  static Color _getBorderColor(BuildContext context, Severity severity) {
    switch (severity) {
      case Severity.info:
        return Colors.blueAccent;
      case Severity.warning:
        return Colors.orangeAccent;
      case Severity.error:
        return Colors.redAccent;
      default:
        return Theme.of(context).colorScheme.onSurface;
    }
  }

  static Color _getTextColor(Severity severity) {
    switch (severity) {
      case Severity.info:
      case Severity.warning:
      case Severity.error:
        return Colors.white;
      default:
        return Colors.black;
    }
  }
}

enum Severity {
  info,
  warning,
  error,
}
```

**Comment by EistenGaming** [comment]
I found one mistake in main.dart - here's the corrected code.
```Dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'base_layout.dart';
import 'networking.dart';
import 'logger.dart';
import 'user_manager.dart';
import 'splash_screen.dart';
import 'overlay_service.dart'; // Import the OverlayService

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await LoggerService.init();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => EveAppState()),
        Provider<ApiService>(create: (_) => ApiService()),
      ],
      child: MaterialApp(
        title: 'Eve Client',
        navigatorKey: OverlayService.navigatorKey, // Set the navigatorKey
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color.fromARGB(255, 117, 130, 137),
            brightness: Brightness.dark,
          ),
          textTheme: TextTheme(
            displayLarge: const TextStyle(
              fontSize: 57,
              fontWeight: FontWeight.bold,
            ),
            displayMedium: const TextStyle(
              fontSize: 45,
              fontWeight: FontWeight.bold,
          ),
        ),
        home: Scaffold(
          body: FutureBuilder(
            future: _initializeApp(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting) {
                return SplashScreen();
              } else {
                return BaseLayout();
              }
            },
          ),
        ),
      ),
    );
  }

  Future<void> _initializeApp() async {
    // Perform any necessary initialization tasks here
    await Future.delayed(Duration(seconds: 2)); // Simulate a delay for initialization
    // Ensure EveAppState is initialized after the MaterialApp is built
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final context = OverlayService.navigatorKey.currentContext;
      if (context != null) {
        Provider.of<EveAppState>(context, listen: false).initialize();
      }
    });
  }
}

class EveAppState extends ChangeNotifier {
  bool _isSignedIn = false;

  bool get isSignedIn => _isSignedIn;

  EveAppState() {
    // Constructor remains empty
  }

  void initialize() {
    _autoSignIn();
  }

  Future<void> _autoSignIn() async {
    String? username = await UserDataManager.getUserData('username');
    String? password = await UserDataManager.getUserData('password');
    
    if (username != null && password != null) {
      await signIn(username, password);
    }
  }

  Future<void> signIn(String username, String password) async {
    final apiService = ApiService();
    bool success = await apiService.login(username, password);
    if (success) {
      _isSignedIn = true;
      notifyListeners();
      LoggerService.logger.info('User signed in successfully');
      
      // Save user credentials
      await UserDataManager.saveUserData('username', username);
      await UserDataManager.saveUserData('password', password);
    } else {
      // Handle login failure (e.g., show an error message)
      OverlayService.showOverlay("TEST", Severity.error);
      LoggerService.logger.warning('Login failed for user: $username');
    }
  }

  void signOut() {
    _isSignedIn = false;
    notifyListeners();
    LoggerService.logger.info('User signed out');
  }
}
```

**Comment by EistenGaming** [comment]
This error now get thrown in `overlay_service.dart`:
```
The following assertion was thrown during a scheduler callback:
No Overlay widget found.
Some widgets require an Overlay widget ancestor for correct operation.
The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
The context from which that widget was searching for an overlay was: Navigator-[LabeledGlobalKey<NavigatorState>#e51de]
    dependencies: [HeroControllerScope, UnmanagedRestorationScope]
    state: NavigatorState#aa498(tickers: tracking 1 ticker)

When the exception was thrown, this was the stack:
#0      Overlay.of.<anonymous closure> (package:flutter/src/widgets/overlay.dart:547:9)
overlay.dart:547
#1      Overlay.of (package:flutter/src/widgets/overlay.dart:550:6)
overlay.dart:550
#2      OverlayService.showOverlay.<anonymous closure> (package:eve_client/overlay_service.dart:11:31)
overlay_service.dart:11
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
binding.dart:1326
#5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#6      _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#7      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#8      _drawFrame (dart:ui/hooks.dart:283:31)
```

and the overlay is null (overlay_service.dart):

```Dart
WidgetsBinding.instance.addPostFrameCallback((_) {
      final overlay = Overlay.of(context);
```

**Comment by EistenGaming** [comment]
After a bit more of debugging:

"error: org-dartlang-debug:synthetic_debug_expression:1:1: Error: Undefined name 'overlay'.
overlay
^^^^^^^"

**Comment by darshankawar** [comment]
@EistenGaming 
Please provide us only minimal but complete reproducible code sample without third party package implementation, that still shows the reported behavior.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by EistenGaming** [comment]
@darshankawar : the provided classes provide the real-life context in which the problem occurs. The imports in main.dart are from my own project and not relevant for the issue in 'overlay_service.dart'. 

Boiled down, the issue seems to be here (overlay-service.dart):
```Dart
    final context = navigatorKey.currentContext;
    if (context == null) return;

//    WidgetsBinding.instance.addPostFrameCallback((_) {
      final overlay = Overlay.of(context);
      if (overlay == null) return;
```
I do get a context now, but `Overlay.of(context)` returns null.

I got overlays to work in my project, it is this specific use-case which is not working.

**Comment by darshankawar** [comment]
See if [this](https://github.com/flutter/flutter/issues/148314#issuecomment-2166343128) helps.

**Comment by EistenGaming** [comment]
I switched to GetX in the mean time - which works out of the box. The on-board approach was becoming far too cumbersome and error-prone.

**Comment by darshankawar** [comment]
> See if [this](https://github.com/flutter/flutter/issues/148314#issuecomment-2166343128) helps.

Did this link help ? Based on your comment, is it safe to close this as resolved ?

**Comment by EistenGaming** [comment]
No it did not help, but I solved the issue by using the GetX library. So yes, the issue can be closed.
