### ISSUE TITLE
Unable to run integration tests with `--web-renderer skwasm`

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#150947]
### Steps to reproduce

Run the following command after starting chromedriver. I'm trying to run the integration tests for the camera_web plugin.

I get the same results on Flutter channels stable and master

```console
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/camera_bitrate_test.dart \
  -d chrome --web-renderer skwasm
```

### Expected results

The test runs

### Actual results

```console
dart_sdk.js:1 
        
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
localhost/:1 Refused to execute script from 'http://localhost:58254/dart_sdk.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
require.js:143 Uncaught Error: Script error for "dart_sdk", needed by: main_module.bootstrap, web_entrypoint.dart
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:168:17)
    at HTMLScriptElement.onScriptError (require.js:1738:36)
```

### Code sample

This can be reproduced with the project created from running. Although you have to copy the `test_driver` file form an existing project since `flutter create` doesn't create it for some reason. Maybe we should file an issue for that as well?

```console
flutter create --template plugin --platforms web project_name
```

### Logs

The logs above are from the camera_web plugin integration tests

I get this log line when attempting to run integration tests in a fresh project:

```console
flutter_bootstrap.js:3 Uncaught (in promise) FlutterLoader could not find a build compatible with configuration and environment.
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.23.0-13.0.pre.361, on macOS 14.5 23F79
    darwin-arm64, locale en-US)
    • Flutter version 3.23.0-13.0.pre.361 on channel main at
      /Users/rexios/repos/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 5bf0192f58 (45 minutes ago), 2024-06-27 10:52:48 -0700
    • Engine revision a9194f0f01
    • Dart version 3.5.0 (build 3.5.0-304.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio
      Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Aaron’s iPhone (mobile)         • 00008130-001C35CE3A20001C • ios
      • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    •
      web-javascript • Google Chrome 125.0.6422.142
    ! Error: Browsing on the local area network for Raj's Apple Vision Pro.
      Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac. (code -27)
    ! Error: Browsing on the local area network for Joe’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by Rexios80** [comment]
I realized that the `index.html` file was out of date for the `camera_web` integration tests. I updated it and now get the same error as a fresh project:

```console
flutter_bootstrap.js:3 Uncaught (in promise) FlutterLoader could not find a build compatible with configuration and environment.
```

**Comment by huycozy** [comment]
Hi @Rexios80, I see there is a proposal to support integration test with wasm https://github.com/flutter/flutter/issues/127730. Since this hasn't been supported yet, I'm going to close this issue. Please follow #127730 for updates. Thanks!

**Comment by Rexios80** [comment]
I'm not sure that's the same issue. There is an option to run the integration tests compiled to WASM but it doesn't work.

**Comment by huycozy** [comment]
You can pass `--web-renderer` because `flutter run` and `flutter drive` shared web renderer options, see:

https://github.com/flutter/flutter/blob/eb58fe16b60f38ab403b75edd3805e884f4eddb8/packages/flutter_tools/lib/src/commands/drive.dart#L54

https://github.com/flutter/flutter/blob/eb58fe16b60f38ab403b75edd3805e884f4eddb8/packages/flutter_tools/lib/src/commands/run.dart#L37-L43

**Comment by Rexios80** [comment]
Should using that option fail gracefully instead of whatever is happening now?
