### ISSUE TITLE
Dart Analysis Server keeps crashing on MacOS

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#151053]
### Steps to reproduce

1. Open a complex project with multiple gradle modules native app and "aar" module which also targets all common Platforms (except web)
2. Refactor a class and move some code from one code file to another
3. Now are imports missing and some fields cannot be found since their references were not fixed yet
4. The Dart Analysis Server keeps crashing in that project for me

### Expected results

I can use the features:
- Code completion
- FInd usages
- Add imports
- Syntax highlighting were fields are now unknown -> Compile errors

### Actual results

None of the features work in Android Studio, IntelliJ and Visual Studio Code on MacOS

### Code sample

I have no code sample yet. I hope this issue is a duplicate which I did not find yet.

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
From Visual Studio Code:
The Dart Analysis Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

For the IntelliJ based IDEs I see no clear errors but might be this helps:
2024-06-29 22:20:26,017 [ 660310]   INFO - #c.i.o.v.n.p.FSRecords - Checking VFS started
2024-06-29 22:20:27,043 [ 661336]   INFO - #c.i.o.v.n.p.FSRecords - Checking VFS finished (healthy): VFSHealthCheckReport[healthy: true](FileRecordsReport[recordsChecked=46046, recordsDeleted=0, childrenChecked=46013]{nullNameIds=0, unresolvableNameIds=0, notNullContentIds=271, unresolvableContentIds=0, unresolvableAttributesIds=0, nullParents=0, inconsistentParentChildRelationships=0, generalErrors=0), RootsReport(rootsCount=32, rootsWithParents=0, rootsDeletedButNotRemoved=0, generalErrors=0), NamesEnumeratorReport(namesChecked=13729, namesResolvedToNull=0, idsResolvedToNull=0, inconsistentNames=0, generalErrors=0), ContentEnumeratorReport(contentRecordsChecked=146621, generalErrors=0)){timeTaken=1.010504709s}
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - [Bad state: Unexpected message type MessageType.staticType, #0      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:219:17)
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - #1      _rootRun (dart:async/zone.dart:1399:13)
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - #2      _CustomZone.run (dart:async/zone.dart:1301:19)
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - #3      withRemoteInstanceZone (package:_macros/src/executor/remote_instance.dart:172:15)
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - #4      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:45:9)
2024-06-29 22:20:35,696 [ 669989]   INFO - STDERR - #5      _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #13     _SingleIsolatedMacroExecutor.start.<anonymous closure> (package:_macros/src/executor/isolated_executor.dart:64:33)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #14     _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - #22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
2024-06-29 22:20:35,697 [ 669990]   INFO - STDERR - ]
2024-06-29 22:21:29,444 [ 723737]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-29 22:21:29,445 [ 723738]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-29 22:21:37,528 [ 731821]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-29 22:21:37,531 [ 731824]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-29 22:24:23,487 [ 897780]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [cscrm_flutter]
2024-06-29 22:24:23,495 [ 897788]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@5ec9bd3e (reason: Push on VFS changes)
2024-06-29 22:24:23,503 [ 897796]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@5ec9bd3e (reason: Push on VFS changes)
2024-06-29 22:24:23,508 [ 897801]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [cscrm_flutter]
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - [Bad state: Unexpected message type MessageType.staticType, #0      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:219:17)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #1      _rootRun (dart:async/zone.dart:1399:13)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #2      _CustomZone.run (dart:async/zone.dart:1301:19)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #3      withRemoteInstanceZone (package:_macros/src/executor/remote_instance.dart:172:15)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #4      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:45:9)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #5      _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #13     _SingleIsolatedMacroExecutor.start.<anonymous closure> (package:_macros/src/executor/isolated_executor.dart:64:33)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #14     _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - #22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
2024-06-29 22:24:26,050 [ 900343]   INFO - STDERR - ]
2024-06-29 22:33:51,942 [1466235]   INFO - STDERR - [Bad state: Unexpected message type MessageType.staticType, #0      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:219:17)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #1      _rootRun (dart:async/zone.dart:1399:13)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #2      _CustomZone.run (dart:async/zone.dart:1301:19)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #3      withRemoteInstanceZone (package:_macros/src/executor/remote_instance.dart:172:15)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #4      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:45:9)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #5      _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #13     _SingleIsolatedMacroExecutor.start.<anonymous closure> (package:_macros/src/executor/isolated_executor.dart:64:33)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #14     _rootRunUnary (dart:async/zone.dart:1415:13)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - #22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
2024-06-29 22:33:51,943 [1466236]   INFO - STDERR - ]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
[✓] VS Code (version 1.90.2)
```

</details>

**Comment by rekire** [comment]
### Flutter Doctor output on Windows 11
This seems not to happen on Windows 11
<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by victorsanni** [comment]
As a workaround, delete the `~/dartServer` folder.

**Comment by rekire** [comment]
Thank you for this workaround, but it seems that I don't have this directory
```bash
% ls -la ~/dartServer
ls: /Users/rekire/dartServer: No such file or directory
```

**Comment by victorsanni** [comment]
Typo... I missed a period. It is a hidden directory.

**Comment by rekire** [comment]
Thank you for clarification, unfortunately this did not change the behavior. However I notices that this behavior is just in one project I worked on this weekend. I'm still looking for pattern and a demo case

**Comment by darshankawar** [comment]
@rekire 
Looking at the log, the entries are pointing to dart and macros, so you will most probably need to report this in dedicated repo: https://github.com/dart-lang/sdk/issues

Closing from here.
