### ISSUE TITLE
Google SignIn plugin - Status{statusCode=DEVELOPER_ERROR, resolution=null

### ISSUE THREAD

**Issue by carljmosca** [flutter/flutter#15108]
## Steps to Reproduce
Running example in packages/google_sign_in/example

An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8107/
For a more detailed help message, press "h". To quit, press "q".
D/EGL_emulation( 7597): eglMakeCurrent: 0xae614840: ver 3 0 (tinfo 0xae6bc1c0)
I/FlutterActivityDelegate( 7597): onResume setting current activity to this
D/EGL_emulation( 7597): eglMakeCurrent: 0xae614840: ver 3 0 (tinfo 0xae6bc1c0)
E/Surface ( 7597): getSlotFromBufferLocked: unknown buffer: 0x9d86d020
I/flutter ( 7597): PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)

The example was working for me before I upgraded to the latest flutter and dart (flutter has had additional updates since I first encountered the error as has this plugin).  Current version of the plugin is 2.1.2.

**Comment by carljmosca** [comment]
I believe this was the result of an incorrect package name.  I had been working with a couple of other example apps and I made a mistake as a result of renaming a package from the default.

**Comment by stevedj** [comment]
Hi @carljmosca 

I encountered the same issue, is there any clue to renaming package, I have tried to search and even replace all in android studio, but it is still behaving the same

**Comment by zoechi** [comment]
Probably https://stackoverflow.com/questions/37273145/error-statusstatuscode-developer-error-resolution-null/37273494

**Comment by dancingbannana** [comment]
Hi @carljmosca 
could you be a little more specific what you did to fix this. I have the same issue. my sha1 key is correct and google-services is in the app directory.

**Comment by jpratt9** [comment]
@zoechi do you have any idea how to find your sha-1 key in a Flutter project? The file structure in the `/android/` folder in a flutter project is much different from that of a normal Android project.

**Comment by carljmosca** [comment]
@dancingbannana I am sorry but I have not had time to get back to this - I will try to take a look over the next day or two

**Comment by dancingbannana** [comment]
I apologize i finally figured it out for some reason i never got the point of you need to use the SHA-1 key from a random android studio project. I was using the android part of my flutter project and was getting a different key.

**Comment by tdesc** [comment]
Spend quite a bit time getting this "DEVELOPER_ERROR" related to Android SHA certificate fingerprints 
not set.

**Comment by carljmosca** [comment]
@dancingbannana glad to know it worked out - yes @tdesc it seems the docs were a bit sparse at least last I looked

**Comment by xProgrammer-007** [comment]
Created a keystore file and got sha1 out of it , copied to firebase , still i get this. No clue
`E/flutter (13297): PlatformException(sign_in_failed, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
`
When creating keystore , is there any regulations to follow with respect to firebase ?

**Comment by 17twenty** [comment]
Same issue on Android emulator and physical.
```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8105/
For a more detailed help message, press "h". To quit, press "q".
W/ActivityThread( 9540): handleWindowVisibility: no activity for token android.os.BinderProxy@620571d
D/EGL_emulation( 9540): eglMakeCurrent: 0xe656f320: ver 2 0 (tinfo 0xe4ba2800)
E/flutter ( 9540): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9540): PlatformException(sign_in_failed, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
E/flutter ( 9540): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter ( 9540): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 9540): <asynchronous suspension>
E/flutter ( 9540): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:185:58)
E/flutter ( 9540): <asynchronous suspension>
E/flutter ( 9540): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:240:28)
E/flutter ( 9540): #4      _RootZone.run (dart:async/zone.dart:1376:54)
E/flutter ( 9540): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
E/flutter ( 9540): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
E/flutter ( 9540): #7      Future._propagateToListeners (dart:async/future_impl.dart:659:37)
E/flutter ( 9540): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342:9)
E/flutter ( 9540): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9540): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/FlutterActivityDelegate( 9540): onResume setting current activity to this
D/EGL_emulation( 9540): eglMakeCurrent: 0xe656f320: ver 2 0 (tinfo 0xe4ba2800)
```

This is with the app approved, the generated `google-services.json` has been copied to `./android/app/google-services.json` and I have run the keytool as above and add the SHA-1 and SHA-256 to firebase:

```
$ keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android
Alias name: androiddebugkey
Creation date: 28/08/2018
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: C=US, O=Android, CN=Android Debug
Issuer: C=US, O=Android, CN=Android Debug
Serial number: 1
Valid from: Tue Aug 28 10:02:00 AEST 2018 until: Thu Aug 20 10:02:00 AEST 2048
Certificate fingerprints:
	 MD5:  3F:F5:01:67:B1:9E:EE:4C:03:98:99:79:2C:7B:D8:80
	 SHA1: C9:42:A5:92:88:E2:ED:87:1F:54:AF:D8:59:95:B8:B5:0B:2E:3D:78
	 SHA256: B4:55:50:06:84:A2:D3:B3:5E:78:5C:E2:F1:CF:1C:40:15:36:5C:10:D5:2D:9D:C4:79:64:13:A3:4E:CB:D4:5C
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 1024-bit RSA key
Version: 1

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /Users/me/.android/debug.keystore -destkeystore /Users/nickglynn/.android/debug.keystore -deststoretype pkcs12".
```

Some help would be appreciated as this currently works fine on iOS and the iOS Simulator App but not on a Pixel running Pie nor the emulator for Pie.

**Comment by DQvsRA** [comment]
Have the same problem. After I had registered my application in Firebase and attached the google-services.json to the Android project (from Firebase steps), copied SHA-1 from gradle->signingReport, I  still have this problem:
I/flutter (25221): PlatformException(sign_in_failed, Status{statusCode=NETWORK_ERROR, resolution=null}, null)

Spent to much time on it. What to do?

**Comment by MohammedGhoname** [comment]
Dear sir,
As this issue is really stopper, may you please mention steps in correct order please, as there is something i cannot understand
the above solution didnt work with me.

Lets say I generate a certificate using Keytool (without any reference to the apk) and got the SHA-1, SHA-256 signatures. and set them into firebase application (on firebase console cloud). and after every thing I got the client ID and set it into google plus object in ionic. the point here how does google will know that this signature is correct and valid and related to this APK?

**Comment by zoechi** [comment]
You need to download the google-services.json file like explained in the README.md of the plugin.

**Comment by csmac3144** [comment]
> Solution is as follows (if the `google_sign_in` package from [here](https://pub.dartlang.org/packages/google_sign_in) is causing your error for sure, probably with other packages/configs that interact with Google's Sign-In API (?), too):
> 
> Run `keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android` in terminal (replace ` ~/` with the location of your `.android` folder if you chose to install it to a non-default location while setting up Android Studio).
> 
> There should be some output that's similar to this:
> 
> ```
> Certificate fingerprints:
> 	 SHA1: C8:A7:...:2D:3E
> 	 SHA256: 41:26:...:1B:5A
> ```
> Copy paste the `SHA1` variable into your "SHA certificate fingerprints" in your Firebase App's Project Settings in your Firebase Console. See [here](https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application) for details on where these settings are located.
> 
> Note: this solution is only for devs attempting to make a Firebase app and having trouble implementing Google Sign-In into their project. YMMV.

jpratt9 solved it.
