### ISSUE TITLE
[Web] WebGL2RenderingContext.bufferSubData: Argument 3 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB

### ISSUE THREAD

**Issue by nitroplr** [flutter/flutter#151057]
### Steps to reproduce

I can not reproduce this error even by loading the exact same PaginatedDataTable as the user who this error was reported for.  This error was reported to me by Sentry.  Recently I wanted to add an error page to my app to be displayed when FlutterError.onError catches an error.  I thought it would be a good idea to connect my app to Sentry for a bit and make sure I did not have errors in my app that did not crash the app and cause an unnecessary redirect to my error page.  However, some of the errors sentry is reporting are beyond me to deal with and I am not sure what to do about them.  I apologize if this is the wrong place for this or if the screenshots are useless information, but I thought they might be important to someone.

### Expected results

The table should render fine, it is not especially large, I render tables 5x as large in the emulator with no problems regularly.

### Actual results

Errors I do not have the ability to fix.

### Code sample

The error is happening on a page with a PaginatedDataTable that has 66 rows and 8 columns.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![image](https://github.com/flutter/flutter/assets/48568777/4c1ae86d-8898-42ff-8328-00d3601ec311)
![image](https://github.com/flutter/flutter/assets/48568777/3ab672db-ad38-42b6-a31c-1b48fcf5ff45)
![image](https://github.com/flutter/flutter/assets/48568777/fbea381d-ecf9-433c-a12d-e94df5d37168)
![image](https://github.com/flutter/flutter/assets/48568777/23913430-503e-464b-8651-33ab5384e081)
![image](https://github.com/flutter/flutter/assets/48568777/75f42c00-5691-4a77-a636-b29bd2b3f3d8)
![image](https://github.com/flutter/flutter/assets/48568777/6307bd26-3601-4f54-8cb3-b176583b2f7b)
![image](https://github.com/flutter/flutter/assets/48568777/ac03bbcf-6be3-4036-8ea4-43cd78aa37c6)
![image](https://github.com/flutter/flutter/assets/48568777/d0913a25-7ba1-496a-9204-0ddd952992ab)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\nitro\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\nitro\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\nitro\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at C:\Users\nitro\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\nitro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.81

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@nitroplr Seems like this is only occuring in Firefox ? If so, could it be a limitation of it of ArrayBufferView ?
Is there a way to check if it also occurs in chrome or not ? 
Also, please provide the stacktrace in properly formatted text instead of in screenshots.

**Comment by nitroplr** [comment]
@darshankawar Of the 8 or 9 errors I can see in Sentry right now they are all coming from Firefox.  They are also all happening after the app.lifecycle state is inactive, and on multiple different pages of my app, not all of which are PaginatedDataTables.  Unfortunately in Sentry I do not believe I can get a complete stacktrace.  Each of those rows in my screenshots where the arrow is pointing down can be expanded like the ones that are pointing up.  There are sometimes tens of thousands of lines in between each stacktrace entry.  
![image](https://github.com/flutter/flutter/assets/48568777/e5483898-7107-40c0-8a6f-9217a4d2dddc)

**Comment by nitroplr** [comment]
I could expand each of them and copy the text in if you would like me to.  It looks like there are about 60 different stacktrace entries reported by Sentry.

**Comment by nitroplr** [comment]
I edited my previous comment, so far each page with this error does contain some type of table.

**Comment by nitroplr** [comment]
The Sentry Discord helped me out, there was an option to view the raw stack trace!  

minified:adR: Error: WebGL2RenderingContext.texSubImage2D: Argument 9 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
  at Na(canvaskit.js:188:371)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[93]:0x0(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5776]:0x326dd3(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5765]:0x324aa1(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[11470]:0x4dcefc(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2581]:0x1140ae(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5663]:0x314662(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5668]:0x314fa3(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[6776]:0x37910e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2071]:0xcfa3e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4225]:0x21f271(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1546]:0x8b336(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4089]:0x1ef79e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[814]:0x396bf(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4118]:0x1fb258(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2877]:0x13be6b(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[7221]:0x3b2365(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10804]:0x4ae963(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1370]:0x75802(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2289]:0xef72e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[3229]:0x179688(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10975]:0x4be671(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10798]:0x4ade34(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1240]:0x6bbe7(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2289]:0xef7de(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[3229]:0x179688(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10975]:0x4be671(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10798]:0x4ade34(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1240]:0x6bbe7(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10824]:0x4b0065(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[948]:0x48db4(unparsed)
  at CanvasKitInit.<fn>.<fn>(canvaskit.js:115:52)
  at CanvasKitInit.<fn>.<fn>(canvaskit.js:49:299)
  at aVH(main.dart.js:49089:8)
  at chz.<fn>(main.dart.js:5531:65)
  at a1(main.dart.js:61107:20)
  at Ei(main.dart.js:49944:5)
  at anB.<fn>(main.dart.js:49271:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at anB(main.dart.js:49288:10)
  at G0(main.dart.js:49253:21)
  at aVG.<fn>(main.dart.js:50270:20)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aVG(main.dart.js:50272:10)
  at Ku(main.dart.js:50256:19)
  at aKK.<fn>(main.dart.js:50464:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aKK(main.dart.js:50468:10)
  at I4(main.dart.js:50457:23)
  at aFK.<fn>(main.dart.js:50434:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aFK(main.dart.js:50456:10)
  at AH(main.dart.js:50425:19)
  at b1y.<fn>(main.dart.js:50419:3)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at b1y(main.dart.js:50424:10)
  at z0(main.dart.js:50405:21)
  at b1w.<fn>(main.dart.js:55916:19)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at b1w(main.dart.js:55918:10)
  at Nc(main.dart.js:55908:21)
  at aT8(main.dart.js:105388:5)
  at VD(main.dart.js:98803:158)
  at VD(main.dart.js:110473:3)
  at aDe(main.dart.js:98793:13)
  at chz.<fn>(main.dart.js:5531:65)
  at a51(main.dart.js:106343:7)
  at a50(main.dart.js:106347:22)
  at ae_(main.dart.js:106333:3)
  at aBz(main.dart.js:106309:10)
  at chz.<fn>(main.dart.js:5530:79)
  at bPJ(main.dart.js:7073:9)
  at <fn>(main.dart.js:167988:66)
  at t1(main.dart.js:64036:12)
  at vx(main.dart.js:64011:10)
  at wp(main.dart.js:2034:8)
  at $1(main.dart.js:55270:3)
  at cne(main.dart.js:5354:69)
  at c3i(main.dart.js:8128:21)
  at csj(main.dart.js:9735:19)
  at csF.<fn>(main.dart.js:9731:42)

**Comment by nitroplr** [comment]
Here is a related stack trace from a different error of the same type.

minified:adR: Error: WebGL2RenderingContext.texSubImage2D: Argument 9 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
  at Na(canvaskit.js:188:371)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[93]:0x0(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5776]:0x326dd3(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5765]:0x324aa1(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[11470]:0x4dcefc(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2581]:0x1140ae(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5663]:0x314662(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[5668]:0x314fa3(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[6776]:0x37910e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2071]:0xcfa3e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4225]:0x21f271(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1546]:0x8b336(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4089]:0x1ef79e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[814]:0x396bf(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[4118]:0x1fb258(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2877]:0x13be6b(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[7221]:0x3b2365(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10804]:0x4ae963(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1370]:0x75802(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2289]:0xef72e(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[3229]:0x179688(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10975]:0x4be671(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10798]:0x4ade34(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1240]:0x6bbe7(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[2289]:0xef7de(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[3229]:0x179688(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10975]:0x4be671(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10798]:0x4ade34(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[1240]:0x6bbe7(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[10824]:0x4b0065(unparsed)
  at @https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/canvaskit.wasm:wasm-function[948]:0x48db4(unparsed)
  at CanvasKitInit.<fn>.<fn>(canvaskit.js:115:52)
  at CanvasKitInit.<fn>.<fn>(canvaskit.js:49:299)
  at aVH(main.dart.js:49089:8)
  at chz.<fn>(main.dart.js:5531:65)
  at a1(main.dart.js:61107:20)
  at Ei(main.dart.js:49944:5)
  at anB.<fn>(main.dart.js:49271:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at anB(main.dart.js:49288:10)
  at G0(main.dart.js:49253:21)
  at aVG.<fn>(main.dart.js:50270:20)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aVG(main.dart.js:50272:10)
  at Ku(main.dart.js:50256:19)
  at aKK.<fn>(main.dart.js:50464:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aKK(main.dart.js:50468:10)
  at I4(main.dart.js:50457:23)
  at aFK.<fn>(main.dart.js:50434:14)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at aFK(main.dart.js:50456:10)
  at AH(main.dart.js:50425:19)
  at b1y.<fn>(main.dart.js:50419:3)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at b1y(main.dart.js:50424:10)
  at z0(main.dart.js:50405:21)
  at b1w.<fn>(main.dart.js:55916:19)
  at m.<fn>(main.dart.js:6775:64)
  at $2(main.dart.js:62820:14)
  at p(main.dart.js:6761:10)
  at b1w(main.dart.js:55918:10)
  at Nc(main.dart.js:55908:21)
  at aT8(main.dart.js:105388:5)
  at VD(main.dart.js:98803:158)
  at VD(main.dart.js:110473:3)
  at aDe(main.dart.js:98793:13)
  at chz.<fn>(main.dart.js:5531:65)
  at a51(main.dart.js:106343:7)
  at a50(main.dart.js:106347:22)
  at ae_(main.dart.js:106333:3)
  at aBz(main.dart.js:106309:10)
  at chz.<fn>(main.dart.js:5530:79)
  at bPJ(main.dart.js:7073:9)
  at <fn>(main.dart.js:167988:66)
  at t1(main.dart.js:64036:12)
  at vx(main.dart.js:64011:10)
  at wp(main.dart.js:2034:8)
  at $1(main.dart.js:55270:3)
  at cne(main.dart.js:5354:69)
  at c3i(main.dart.js:8128:21)
  at csj(main.dart.js:9735:19)
  at csF.<fn>(main.dart.js:9731:42)

**Comment by darshankawar** [comment]
Thanks for the log @nitroplr.
Please check https://github.com/flutter/flutter/issues/115928 and see if it resembles your case or not. [This](https://github.com/flutter/flutter/issues/115928#issuecomment-1396277890) comment seems to be similar to what you are seeing and may give you further reference.

**Comment by nitroplr** [comment]
I do use a lot of really small images on the pages that are crashing.  Is there anything I can do to at least catch the error?

**Comment by nitroplr** [comment]
I do notice that the places I use image.memory flicker when I load the page, but image.network does not.

**Comment by darshankawar** [comment]
> I use image.memory flicker when I load the page, but image.network does not.

Please provide us a runnable code sample based on it, so that we can properly address the issue.

**Comment by nitroplr** [comment]
The flickering was just from the widget being rebuilt.  By caching the MemoryImage instead of base64Decoding the image string every time the widget is rebuilt I got the flickering to go away.  I am hoping this solves the current error as well with the image decoding not happening on rebuilds.

**Comment by nitroplr** [comment]
Just deployed my app update with no flickering images, I'll know in a few days if that fixes the error caused by no flicker browsers.

**Comment by nitroplr** [comment]
Fixing the flickering images allowed me to narrow this error down to one page of my website that was a paginated data table with a setstate infinite loop in my sorting logic.  With these two problems fixed the error is either gone completely or just hasn't shown up again yet.
