### ISSUE TITLE
Getting NullPointerException in FlutterView.dispatchKeyEvent 

### ISSUE THREAD

**Issue by SAKET3901** [flutter/flutter#151068]
### Steps to reproduce

- I am using Flutter Add to App
- There are Flutter screens with InputField widget which opens keyboard on getting focus
- Next when I turn off the internet a NO Internet fragment comes up 
- The moment it comes I press hardware back my app crashes 

### Expected results

I can see that  in 
`getKeyDispatcherState().startTracking(event, this);` 
- `getKeyDispatcherState` is returning null 

### Actual results

If this function can return null a proper null check should be handled 

### Code sample

<details open><summary>Code sample</summary>

```dart
  @Override
  public boolean dispatchKeyEvent(@NonNull KeyEvent event) {
    if (event.getAction() == KeyEvent.ACTION_DOWN && event.getRepeatCount() == 0) {
      // Tell Android to start tracking this event.
      getKeyDispatcherState().startTracking(event, this);
    } else if (event.getAction() == KeyEvent.ACTION_UP) {
      // Stop tracking the event.
      getKeyDispatcherState().handleUpEvent(event);
    }
    // If the key processor doesn't handle it, then send it on to the
    // superclass. The key processor will typically handle all events except
    // those where it has re-dispatched the event after receiving a reply from
    // the framework that the framework did not handle it.
    return (isAttachedToFlutterEngine() && keyboardManager.handleEvent(event))
        || super.dispatchKeyEvent(event);
  }
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
FATAL EXCEPTION: main                                         
                                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.KeyEvent$DispatcherState.startTracking(android.view.KeyEvent, java.lang.Object)' on a null object reference
                                                                                         	at io.flutter.embedding.android.FlutterView.dispatchKeyEvent(FlutterView.java:908)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1995)
                                                                                         	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:547)
                                                                                         	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1913)
                                                                                         	at android.app.Activity.dispatchKeyEvent(Activity.java:4427)
                                                                                         	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
                                                                                         	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
                                                                                         	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
                                                                                         	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                                                                                         	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                         	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
                                                                                         	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:434)
                                                                                         	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7633)
                                                                                         	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7494)
                                                                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6907)
                                                                                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6969)
                                                                                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6930)
                                                                                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7100)
                                                                                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6938)
                                                                                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7157)
                                                                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6911)
                                                                                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6969)
                                                                                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6930)
                                                                                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6938)
                                                                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6911)
                                                                                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6969)
                                                                                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6930)
                                                                                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7133)
                                                                                         	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7344)
                                                                                         	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4464)
                                                                                         	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3893)
                                                                                         	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3884)
                                                                                         	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
                                                                                         	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4441)
                                                                                         	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
                                                                                         	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                         	at android.os.MessageQueue.next(MessageQueue.java:350)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
> * I am using Flutter Add to App
> * There are Flutter screens with InputField widget which opens keyboard on getting focus

@SAKET3901 Please provide us a reproducible code sample or a sample repo that we can clone to verify this further. Make sure it doesn't have any third party package implementation and code is minimal.



> * press hardware back my app crashes

Do you mean the device's back / home button ?

**Comment by SAKET3901** [comment]
Yes @darshankawar device back /home button. 
Let me get back with the code sample
