### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by mrcsh** [flutter/flutter#151038]
### Steps to reproduce

The web version flutter app I work on was locked.  The developer console was being flooded with  1000s the following exceptions.  This has happened multiple times now, though it is not very frequent.  This time it happened overnight when there was certainly no interaction, though it did have some async notifications that would have caused UI updates.
Browser was brave this time, but I do think I saw the same thing on chrome.

```
ERROR 04:52:15.693:btK.OZ/123584:RuntimeError: memory access out of bounds
RuntimeError: memory access out of bounds
    at https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.wasm:wasm-function[1368]:0x78850
    at https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.wasm:wasm-function[9339]:0x440ebb
    at https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.wasm:wasm-function[1330]:0x6fd98
    at Tb.<anonymous> (https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.js:115:52)
    at Tb.<anonymous> (https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.js:155:256)
    at new PictureRecorder (https://www.gstatic.com/flutter-canvaskit/edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4/chromium/canvaskit.js:104:189)
    at a1h.HN (https://beta.lochbox.app/fFocm4p_cc7_BeC1wFCi0Q.js.gz:107499:13)
    at https://beta.lochbox.app/fFocm4p_cc7_BeC1wFCi0Q.js.gz:107537:3
    at e9q.a (https://beta.lochbox.app/fFocm4p_cc7_BeC1wFCi0Q.js.gz:7719:63)
    at e9q.$2 (https://beta.lochbox.app/fFocm4p_cc7_BeC1wFCi0Q.js.gz:122432:14)
```
I tried to deobfuncate but it only produced the following
```
org-dartlang-sdk:///dart-sdk/lib/_internal/js_runtime/lib/js_number.dart 642:17     JSInt._binaryGcd
org-dartlang-sdk:///dart-sdk/lib/_internal/js_runtime/lib/js_number.dart 511:36     JSInt._binaryGcd
org-dartlang-sdk:///dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 307:10  CkPictureRecorder.beginRecording
org-dartlang-sdk:///lib/_engine/engine/canvaskit/rasterizer.dart 55:5               ViewRasterizer.draw
org-dartlang-sdk:///dart-sdk/lib/_internal/js_runtime/lib/async_patch.dart 303:19   _wrapJsFunctionForAsync
org-dartlang-sdk:///dart-sdk/lib/_internal/js_runtime/lib/async_patch.dart 328:23   _wrapJsFunctionForAsync.<anonymous function>

```

### Expected results

No exceptions.

### Actual results

App is completely non-responsive.

### Code sample

Since the stack trace does not have any of our code it in I have no idea what code is even implicated.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

I have saved the console log from brave, but it's the same error over 57000 times.
```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on Fedora Linux 40 (Forty) 6.8.11-300.fc40.x86_64, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /server/home/csh/lib/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /server/home/csh/lib/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.6 (Fedora 18.1.6-3.fc40)
    • cmake version 3.28.2
    • ninja version 1.12.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2023.3)
    • Android Studio at /server/home/csh/lib/android-studio
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 40 (Forty) 6.8.11-300.fc40.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by mrcsh** [comment]
The only thing that I can see that similar is that both traces have to with "Picture", recording in my case and rendering in #150119.   We are not compiling our webapp to WASM.  And we are not using any WebViewWidgets in our code.

We compile our webapp with 
flutter build web --release --no-tree-shake-icons --web-renderer auto --source-maps

**Comment by darshankawar** [comment]
Can you share a reproducible code sample that we can use to verify this further ?

**Comment by mrcsh** [comment]
No, I don't even know what code is causing this to even begin to try to isolate it, and the fact that it happens on the order of days and when I'm not using it.

**Comment by darshankawar** [comment]
Keeping the issue open based on the report, for team's attention.

**Comment by ditman** [comment]
Without a reproducible sample, it's hard to debug what's going on :/

I'm going to close this, but if anybody finds a reproducible sample, just reopen the bug and we'll take another look!
