### ISSUE TITLE
TextField: Frequent Clipboard Access During Text Input in Android 

### ISSUE THREAD

**Issue by akindone** [flutter/flutter#151076]
### Description

I have noticed that while entering text in an Android TextField, there is frequent access to the clipboard. This behavior seems unnecessary and could potentially raise privacy concerns.

### Steps to reproduce

1. Create a Flutter project.
2. Add a TextField widget in the app.
3. Run the app on an Android device.
4. Monitor clipboard access while typing in the TextField.
To check if the clipboard is being accessed, I used [PrivacySentry](https://github.com/allenymt/PrivacySentry), an Android privacy compliance detection tool. This tool uses annotations and ASM (Abstract Syntax Tree) to modify bytecode for detection.

### Expected results

The TextField should not frequently access the clipboard during text input.

### Actual results

The TextField frequently accesses the clipboard, even when the clipboard is not relevant to the current input.

### Logs

<details open><summary>Logs</summary>

```console
	at android.content.ClipboardManager.getPrimaryClipDescription(Native Method)
	at com.yl.lib.privacy_proxy.PrivacyProxyCall$Proxy.getPrimaryClipDescription(PrivacyProxyCall.kt:365)
	at io.flutter.plugin.platform.PlatformPlugin.clipboardHasStrings(PlatformPlugin.java:602)
	at io.flutter.plugin.platform.PlatformPlugin.access$1200(PlatformPlugin.java:35)
	at io.flutter.plugin.platform.PlatformPlugin$1.clipboardHasStrings(PlatformPlugin.java:148)
	at io.flutter.embedding.engine.systemchannels.PlatformChannel$1.onMethodCall(PlatformChannel.java:184)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:8115)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@akindone 
What Android device are you using that is showing this behavior ? Can you provide device's make, model and OS version ?
Can you try [this](https://api.flutter.dev/flutter/material/TextField/enableInteractiveSelection.html) property and set it to false to check if the behavior still persists or not ?

**Comment by akindone** [comment]
> @akindone What Android device are you using that is showing this behavior ? Can you provide device's make, model and OS version ? Can you try [this](https://api.flutter.dev/flutter/material/TextField/enableInteractiveSelection.html) property and set it to false to check if the behavior still persists or not ?

my device is HUAWEI Mate20, model: HMA-AL00,Android 9. I set enableInteractiveSelection false, and the behavior still persists.

**Comment by darshankawar** [comment]
> and the behavior not show

You mean if you set it to false, the clipboard access logs are not showing anymore ? That means the property usage is correct and may help you forward in your app. Does that help resolve your issue ?
