### ISSUE TITLE
Flutter Web Apps fails to run in Brave Browser with Shields Up

### ISSUE THREAD

**Issue by tratum** [flutter/flutter#151069]
### **Issue**
Flutter web applications are unable to run in the Brave browser when the shields are up. This issue impacts the usability and accessibility of Flutter web apps for users who prefer the Brave browser with its default privacy and security settings.

### **Steps to Reproduce**
1. Deploy a Flutter web app to a production environment.
2. Open the deployed Flutter web app in the Brave browser.
3. Ensure that the Brave browser shields are turned on (default setting).
4. Observe that the Flutter web app fails to load or function properly.

### **Expected Behavior**:
The Flutter web app should load and function correctly in the Brave browser with shields up, similar to how it operates in other major browsers (e.g., Chrome, Firefox, Safari).

### **Actual Behavior**:
The Flutter web app either fails to load entirely or exhibits significant functionality issues when accessed through the Brave browser with shields up.

### **Additional Information**:
- The issue is reproducible with multiple Flutter web apps.
- Disabling shields in the Brave browser resolves the issue, indicating that the problem is related to the browser's privacy and security settings.
- This issue is affecting a significant portion of users ( Approx. 67.7 million people ) who use Brave as their primary browser with shields enabled for enhanced privacy and security.
![Screenshot from 2024-06-30 23-55-41](https://github.com/flutter/flutter/assets/90713896/04bc62fb-dbca-4123-80c4-e9e2b8bcacde)

### **Environment**:
- Flutter version
   ```
   Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
  Framework • revision bae5e49bc2 (5 months ago) • 2024-02-13 17:46:18 -0800
  Engine • revision 04817c99c9
  Tools • Dart 3.3.0 • DevTools 2.31.1
   ```
- Brave browser version
   `Version 1.67.123 Chromium: 126.0.6478.126 (Official Build)`

- Operating System
   ```
   OS: Fedora Linux 40 (Workstation Edition) x86_64 
   Host: TUF Gaming FX505DT
   Kernel: 6.9.4-200.fc40.x86_64 
   ```
### **Workaround**:
Currently, the only workaround is to instruct users to disable shields in the Brave Browser, which is not ideal from a privacy and security perspective.

### **Request**:
Investigate the compatibility issues between Flutter web apps and the Brave browser with Shields Up, and provide a solution or guidance on how to ensure Flutter web apps can function correctly without compromising user privacy and security.

#### _**Given that approximately 67 million people are using the Brave browser, resolving this issue is crucial to maintain and expand the user base for Flutter web apps. This is a very severe issue, so please address it with High Priority and Urgency.**_

**Comment by famasf1** [comment]
iirc Flutter Web App is using Dart2js heavily to complied Dart into JS. JS is essential to make Flutter functional on web. Of which Brave Browser is known to block a lot of.

I don't think this will ever become a priority for Flutter. Considering over 65% of entire human population that use internet prefer Chrome.

**Comment by huycozy** [comment]
@tratum I don't see the issue on my deployed site with Flutter counter app:

<details>
<summary>Demo</summary>

![Screenshot 2024-07-01 at 17 57 32](https://github.com/flutter/flutter/assets/104349824/a27a6ed8-486d-421f-8eb3-82ed87878260)
</details>

Since you are on an old Flutter version (3.19.0), could you retry on the latest Flutter stable (3.22.2) and confirm? If the issue persists, please help to check:
- Does the issue only occur on production? Can you reproduce it locally? (with debug and release mode)
- When the issue occurs, is there any error trace from browser's console tab?

**Comment by tratum** [comment]
@huycozy sure i'll try it on the latest flutter build and check if the issue still persists

### Does the issue only occur on production? Can you reproduce it locally? (with debug and release mode)
- Yes, it only occurs in production and no it doesn't get reproduced locally

### When the issue occurs, is there any error trace from browser's console tab?
- Yes there are Error Trace in my browser's console tab. Here is a specific error for one of my prod web app:
  ```
  main.dart.js:9891 Uncaught TypeError: Cannot read properties of null (reading 'match')
    at R (canvaskit.js:182:154)
    at canvaskit.wasm:0x4b336
    at canvaskit.wasm:0x46a2cd
    at canvaskit.wasm:0x8d0f4
    at Object._MakeGrContext (canvaskit.js:115:52)
    at a.MakeWebGLContext (canvaskit.js:15:268)
    at Object.callMethod (main.dart.js:17399:24)
    at Surface.createOrUpdateSurface$1 (main.dart.js:51413:34)
    at Surface.acquireFrame$1 (main.dart.js:51283:12)
    at main.dart.js:50719:79
  ```
  
### **The Log File is provided below**
[acadameet.tratum.dev-1719833090328.log](https://github.com/user-attachments/files/16052017/acadameet.tratum.dev-1719833090328.log)

**Comment by callmephil** [comment]
This only happens when the **Block script** is turned on (for me) my app is running on 3.19.6 which is not active by default on Brave. 
![image](https://github.com/flutter/flutter/assets/2213079/e81265b8-4563-4ee5-ae4c-27c0c81251cf)

**Comment by tratum** [comment]
These are my brave configurations
![Screenshot from 2024-07-05 21-30-02](https://github.com/flutter/flutter/assets/90713896/15fb1645-c92a-4f27-b5f2-2cadc61802a1)

but i am still not able to run my prod web app

**Comment by huycozy** [comment]
By default, `Block scripts` is turned off and `Shields` is up, the web loads and displays normally. I re-checked this issue with additional tests below on browser's settings by toggling `Block scripts` and `Shields` on address bar, I saw the web doesn't display on a case but I can't see the error trace as [above](https://github.com/flutter/flutter/issues/151069#issuecomment-2199898252). The same results below are on local and deployed web. 

| Block scripts | Shields on address bar | Is Web loaded/displayed?
| --------------- | --------------- |  --------------- | 
Off | Up | Yes ✅
Off | Down | Yes ✅
On | Up | No ❗
On | Down | Yes ✅

@tratum Could you retry and confirm with these settings? And also share your results if some of them are different?

**Comment by tratum** [comment]
@huycozy Based on my tests with the settings you provided these are the results
| Block scripts | Brave Shields | Is Web loaded/displayed? |
|---------------|------------------------|--------------------------|
| Off           | Up                     |  No ❗                      |
| Off           | Down                   | Yes ✅                   |
| On            | Up                     | No ❗                    |
| On            | Down                   | Yes ✅                   |

### **Upgraded Environment**
- Flutter Version
  ```
    • Flutter version 3.22.2 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
  ```
### _**The Console Log File is Provided Below**_
[log-1720418204835.log](https://github.com/user-attachments/files/16123389/log-1720418204835.log)

**Comment by tratum** [comment]
> @huycozy Based on my tests with the settings you provided these are the results
> 
> Block scripts	Brave Shields	Is Web loaded/displayed?
> Off	Up	No ❗
> Off	Down	Yes ✅
> On	Up	No ❗
> On	Down	Yes ✅
> ### **Upgraded Environment**
> * Flutter Version
>   ```
>     • Flutter version 3.22.2 on channel stable
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
>     • Engine revision edd8546116
>     • Dart version 3.4.3
>     • DevTools version 2.34.3
>   ```
> 
> ### _**The Console Log File is Provided Below**_
> [log-1720418204835.log](https://github.com/user-attachments/files/16123389/log-1720418204835.log)

I am also using Firebase for this prod web app

**Comment by huycozy** [comment]
@tratum Thanks for checking that. I see there is only a different case between my and your results. 

Did you build web with a specific renderer? (html, canvaskit or wasm) Could you also give it a try on a version without using Firebase plugins to see if the issue persists?

**Comment by tratum** [comment]
My build command looks something like this
`flutter build web --web-renderer auto --release`
and  for a different prod web app where firebase was not used is working perfectly when i turned off the Block Script Option in Brave Shield
and it looked something like this
| Block scripts | Brave Shields | Is Web loaded/displayed? |
|---------------|------------------------|--------------------------|
| Off           | Up                     |  Yes ✅                  |
| Off           | Down                   | Yes ✅                   |
| On            | Up                     | No ❗                    |
| On            | Down                   | Yes ✅                   |

**Comment by huycozy** [comment]
Thanks. It's similar to my result [above](https://github.com/flutter/flutter/issues/151069#issuecomment-2213029407) on a simple Web app (counter app). Labeling this for further insights.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-14.0.pre.157, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-14.0.pre.157 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ad6166a8b8 (3 hours ago), 2024-07-07 19:58:25 -0400
    • Engine revision ca79a56a66
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.127
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by ditman** [comment]
@tratum can you check the network panel of Brave (or the responses to firebase SDKs) to see if the browser is blocking those, or messing with the requests/responses?

I'm trying to understand *what* is Brave doing to break your app, so we can figure out if there's anything we can fix.

**Comment by tratum** [comment]
@ditman  the flutter service worker is getting disconnected
![Screenshot from 2024-07-28 19-45-07](https://github.com/user-attachments/assets/4d9e1fc8-d82d-46b1-a094-81aca1214694)

**Comment by ditman** [comment]
@tratum, it's hard to help if you only offer parts of images, but you keep censoring bits of information.

Either reproduce this in a way that you can openly share, or there isn't much that we can do here.

**Comment by ditman** [comment]
It seems the Brave browser is blocking some resources that Flutter relies on.

The browser itself suggests users to "try Shields down." if the "site seems broken" as a workaround.

Since Brave is not yet part of our [browser support matrix](https://docs.flutter.dev/reference/supported-platforms), and there's a workaround, I'm cataloguing this as a P3.

**Comment by ditman** [comment]
I'm also keeping this open, because we might want to revisit in the future.
