### ISSUE TITLE
flutter doctor can't find Android SDK, but ANDROID_HOME is deprecated.

### ISSUE THREAD

**Issue by binary132** [flutter/flutter#15114]
```sh
brew install android-sdk
echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> ~/.zshrc
source ~/.zshrc
flutter doctor
```

```
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
```

ANDROID_HOME is [deprecated](https://developer.android.com/studio/command-line/variables.html).  The variable is now called ANDROID_SDK_ROOT.

**Comment by binary132** [comment]
It also complains that `Android SDK is missing command line tools`, but I have installed:

```
  Path                                                | Version | Description                                     | Location                     
  -------                                             | ------- | -------                                         | -------                                
  build-tools;27.0.3                                  | 27.0.3  | Android SDK Build-Tools 27.0.3                  | build-tools/27.0.3/               
  emulator                                            | 27.1.10 | Android Emulator                                | emulator/                                                   
  extras;intel;Hardware_Accelerated_Execution_Manager | 6.2.1   | Intel x86 Emulator Accelerator (HAXM installer) | extras/intel/Hardware_Accelerated_Execution_Manager/        
  patcher;v4                                          | 1       | SDK Patch Applier v4                            | patcher/v4/                                                 
  platform-tools                                      | 27.0.1  | Android SDK Platform-Tools                      | platform-tools/                 
  tools                                               | 26.1.1  | Android SDK Tools                               | tools/
```

which "tools" are missing?

**Comment by binary132** [comment]
`ANDROID_HOME` is deprecated......  why doesn't `flutter` look in `$ANDROID_HOME/tools`?

**Comment by binary132** [comment]
Adding these to my PATH didn't fix it.  I tried adding `build-tools`, too.  That didn't fix it either.

**Comment by gauravagarwalr** [comment]
Also it doesn't detect ANDROID_NDK_HOME path automatically.

**Comment by gauravagarwalr** [comment]
[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • ANDROID_HOME = /usr/local/share/android-sdk
    ✗ Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

`$ ls $ANDROID_NDK_HOME/`

> CHANGELOG.md       build/             ndk-build*         ndk-gdb*           ndk-which*         prebuilt/          shader-tools/      source.properties  sysroot/            README.md          meta/              ndk-depends*       ndk-stack*         platforms/         python-packages/   simpleperf/        sources/           toolchains/

`$ ls $ANDROID_SDK_ROOT/`
> .knownPackages  build-tools/    emulator/       extras/         licenses/       patcher/        platform-tools/ tools/

`$ echo $PATH`
> ...:/usr/local/share/android-sdk/tools:/usr/local/share/android-sdk/platform-tools:...

**Comment by crux** [comment]
1. 
so i checked the flutter code, ANDROID_HOME might be deprecated but is still used in the code. I think the easiest and safest bet is have them both pointing to the same sdk.
"packages/flutter_tools/lib/src/android/android_sdk.dart"
"packages/flutter_tools/lib/src/android/android_workflow.dart" 

for my mac OSX the means:

export ANDROID_SDK_ROOT=/Users/<user>/Library/Android/sdk
export ANDROID_HOME=$ANDROID_SDK_ROOT

Note: flutter seams to remember these settings. So removing the env vars and running flutter doctor again might work! It's really quite hard to exactly know whats going on because flutter tries to be really smart (I prefer dump software)

2. second problem, 

also realated to flutter trying to be smart, the android platform tools. I had a android sdk installed via homebrew and a android studio later. To clean things up removed the homebrew install only to have flutter suddenly complaining about the missing android sdk..
Again, flutter remembers junk taken up from somewhere..

2a) add the android sdk to the shall command path:
export PATH=${PATH}:/Users/<user>/Library/Android//sdk/platform-tools/

2b) gradle bakes some env state into properties. In my case removing some local.properties files actualle solved my problem. I used 'ag android-sdk' to find places in my src dir which referring to an old android-sdk dir from homebrew and removed them. 

have fun,

**Comment by jackyq2015** [comment]
I have the same issue. But it works fine on command line when run flutter doctor. When I run it from AS, I got:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_CA.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.21.1)

! Doctor found issues in 2 categories.
```
I am using Ubuntu 17.0.4. ANDROID_HOME is pointing the right folder.

**Comment by gauravagarwalr** [comment]
I got the flutter installation working, the android setup is the tricky part. I have detailed out how I have done it in this blog post: https://blog.gauravagarwalr.com/posts/2018-04-11-setting-up-flutter/

**Comment by binary132** [comment]
ANDROID_HOME is not "might be" deprecated.  It is deprecated.

**Comment by MishraUdit** [comment]
I have the same issue. I have tried the above solutions but none of them is helpful. I am currently using Windows 10 version 1803(OS Build: 17134.112). Here, I am showing my output of flutter command: `flutter doctor -v`. Moreover, I have tried the `flutter upgrade` command too...
Please help me, I am unable to use flutter...
![capture](https://user-images.githubusercontent.com/24964084/42226248-197e792a-7efc-11e8-95ed-45b91d9b6be9.PNG)
![image](https://user-images.githubusercontent.com/24964084/42226342-5f3d006c-7efc-11e8-9292-6503c91b79bf.png)

**Comment by rameshsambu-dev** [comment]
Still same issue

**Comment by Isonomic** [comment]
Hey I might catch a lot of grief here, but I have the same warning come up and it has not affected one single thing as far as running commands, creating apps or running the emulator or anything at all. I just ignore it and proceed with app development.

**Comment by sivang** [comment]
also affected by it, has anyone found a deterministic solution for that? I reckon this prevents you from developing with Flutter right? e.g. not just an ignorable error?

**Comment by sluongng** [comment]
having the same issue... this is a discouraging way for people who starting out with their existing IDE(s) and dont wana grab the full android studio package...

**Comment by bcseda** [comment]
I was having this problem as well. Was able to fix it based @crux's on solution: https://github.com/flutter/flutter/issues/15114#issuecomment-376582281

export ANDROID_SDK_ROOT="/Users/$USER/Library/Android/sdk"
export ANDROID_HOME=$ANDROID_SDK_ROOT

**Comment by nbro** [comment]
In my case, I simply didn't have Android Studio installed. During the installation of the AS, apparently, a few files under the `/Users/$USER/Library/Android/sdk/` folder are replaced by "new ones".

**Comment by nbro** [comment]
In my case, I simply didn't have Android Studio installed. During the installation of the AS, apparently, a few files under the /Users/$USER/Library/Android/sdk/ folder are replaced by "new ones"...

`echo $ANDROID_SDK_ROOT` and echo `$ANDROID_HOME` print empty lines. I had first tried to instal sdkmanager using brew, but it didn't solve the problem, so I uninstalled it later.

**Comment by nbro** [comment]
In my case, installing Android Studio solved the problem. During the installation of the AS, apparently, a few files and folders under the /Users/$USER/Library/Android/sdk/ folder are replaced by "new ones"...

`echo $ANDROID_SDK_ROOT` and echo `$ANDROID_HOME` print empty lines. I had first tried to instal sdkmanager using brew, but it didn't solve the problem, so I uninstalled it later.

**Comment by nbro** [comment]
In my case, installing Android Studio solved the problem. During the installation of the AS, apparently, a few files and folders under the `/Users/$USER/Library/Android/sdk/` folder are replaced by "new ones"...

`echo $ANDROID_SDK_ROOT` and `echo $ANDROID_HOME` print empty lines. I had first tried to instal `sdkmanager` using `brew`, but it didn't solve the problem, so I uninstalled it later.

**Comment by badelmann** [comment]
I had the same issue on win 10 using VS Code. It was resolved by running VS Code in administrator mode.

**Comment by binary132** [comment]
Running as root is not a "resolution".  This variable is deprecated and the implementation should be fixed.

**Comment by mohammedalyhari** [comment]
> 
> 
> I was having this problem as well. Was able to fix it based @crux's on solution: [#15114 (comment)](https://github.com/flutter/flutter/issues/15114#issuecomment-376582281)
> 
> export ANDROID_SDK_ROOT="/Users/$USER/Library/Android/sdk"
> export ANDROID_HOME=$ANDROID_SDK_ROOT

I have same problem 

How i can do this and Is this for windows or mac 

> export ANDROID_SDK_ROOT="/Users/$USER/Library/Android/sdk"
> export ANDROID_HOME=$ANDROID_SDK_ROOT

**Comment by lsianturi** [comment]
Flutter provide command to update our Android SDK path:

Use `flutter config --android-sdk <path-to-your-android-sdk-path>`

**Comment by jarias14** [comment]
> Flutter provide command to update our Android SDK path:
> 
> Use `flutter config --android-sdk <path-to-your-android-sdk-path>`
Thank you! 
Before:
```[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.```
After:
```[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
```

This is on Ubuntu 16.04. Perhaps the flutter doctor documentation just needs to be updated.

**Comment by davidwparker** [comment]
> Flutter provide command to update our Android SDK path:
> 
> Use `flutter config --android-sdk <path-to-your-android-sdk-path>`

Worked for me as well. OSX Mojave.

Kept getting this error:
```
Android sdkmanager tool not found (/usr/local/Cellar/android-sdk/24.4.1_1/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.io/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidValidator._ensureCanRunSdkManager (package:flutter_tools/src/android/android_workflow.dart:260:7)
#2      AndroidValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:194:5)
<asynchronous suspension>
#3      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:155:19)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:52)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
#6      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:152:24)
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

After setting: `flutter configure --android-sdk /Users/davidwparker/Library/Android/sdk/` it was fine.

**Comment by rielzzapps** [comment]
What is flutter looking for?
I installed the tools (sdkmanager is just working fine) and installed platform-tools with sdkmanager, as it is supposed to. 

android-sdk is downloaded and installed to /tools but even pointing $ANDROID_HOME to this folder is not helping flutter detecting sdk tools. 

What does it expect?

PS I want to run flutter build on a headless machine.

**Comment by sky1095** [comment]
Solved: By adding two paths in  "System variable"'s Path destination.
1. ../Android/sdk/platforms
2. ../Android/sdk/platform-tools
P.S. Should be added to System Variables -> Path (Not on User Variables -> Path)
[https://imgur.com/a/kTxUaOd](url)

**Comment by binary132** [comment]
That doesn't "solve" the fact that ANDROID_HOME is deprecated.

**Comment by DanTup** [comment]
> That doesn't "solve" the fact that Flutter relies on a deprecated environment variable.

You should be able to set the SDK path using `flutter config` if you'd prefer not to use the `ANDROID_HOME` variable. A few people above have said this worked fine - is it not working for you?

(FWIW, I don't think Android Studio deprecating their use of ANDROID_HOME means it's any less valid for Flutter to read it - setting an environment variable to pass paths to applications is common and Flutter presumably picked ANDORID_HOME for convenience because many people already had it set.. it's not all that different to if Flutter supported setting a variable named FLUTTER_ANDROID_SDK and used that).

**Comment by binary132** [comment]
I'm no longer using Flutter, and I'm not asking for help.  I'm pointing out that Flutter is using a deprecated envar.  This seems to be causing some issues for some new users.

It's convenient that a bunch of workarounds are in this thread now, though.

**Comment by AlexanderArendar** [comment]
That's a total crap that this issue opened on March 3rd is still actual at December 7th after Flutter 1.0 has been released. Starting working with Flutter and being not able to smoothly run a sample project is a real shame and as I see from this thread this is happening for a lot of people.

**Comment by QuietLakeStone** [comment]
I finally solved the problem!!!!.>>Ubuntu 18<<, Need to make paths the same，
like:/home/name/flutter   and /home/name/Android-SDK
Check ndk-bundle/toolchains Is it complete?,You can download> android-ndk-r16b-linux-x86_64.zip 
Then modify the environment and AS configure,restart AS,no devices ->Android Device
I hope I can help you all.

**Comment by linangchen** [comment]
```
export ANDROID_HOME=/home/liangchen/Android/Sdk
export PATH=$ANDROID_HOME/tools:$PATH
```

**Comment by linangchen** [comment]
```
export ANDROID_HOME=/home/liangchen/Android/Sdk
export PATH=$ANDROID_HOME/tools:$PATH

```

**Comment by linangchen** [comment]
```
export ANDROID_HOME=/home/liangchen/Android/Sdk
export PATH=$ANDROID_HOME/tools:$PATH
```

**Comment by seanbhart** [comment]
Be sure to install the Android SDK Platform-Tools as well:

![image](https://user-images.githubusercontent.com/10830846/52529845-72541700-2cbf-11e9-874a-1f5f6d66d334.png)

**Comment by zhangrunhao** [comment]
> Flutter provide command to update our Android SDK path:
> 
> Use `flutter config --android-sdk <path-to-your-android-sdk-path>`

thank you

**Comment by linangchen** [comment]
check your sdk path,i had this error before. make sure your sdk path have platform folder

**Comment by obadaro** [comment]
If `ANDROID_HOME/licenses` doesn't exists, `flutter doctor` will not find Android SDK. 

Flutter (Channel beta, v1.3.8, on Linux)

**Comment by Young-devps** [comment]
#Just copy this for Android Studio set up
#SDK exporting - this will solve your issue
export ANDROID_HOME=/home/youngdevps/Android/Sdk 
#Tools exporting - it can be need in your case
export PATH=/home/{Username}/Android/Sdk/platform-tools:$PATH
export PATH=/home/{Username}/Android/Sdk/tools:$PATH
export PATH=/home/{Username}/Android/ndk-build:$PATH

export ANDROID_SDK_ROOT=$HOME/Android/sdk
#avdmanager, sdkmanager
export PATH=$ANDROID_SDK_ROOT/tools:$PATH
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
#adb, logcat
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
#emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator


#Just copy this for Flutter set up set up
#fLUTTER
export PATH=${PATH}:/home/{Username}/development/flutter/bin
export PATH=${PATH}:/home/{Username}/development/flutter/bin/cache/dart-sdk/bin
export PATH="$PATH":"~/.pub-cache/bin"
export PATH="$PATH:/home/{Username}/development/flutter/bin"
export PATH=/home/{Username}/development/flutter/bin:$PATH
export PATH=$PATH:/home/{Username}/development/flutter/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/{Username}/.sdkman"
[[ -s "/home/{Username}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{Username}/.sdkman/bin/sdkman-init.sh"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"





It will work if you copy and change username correctly. and suscribe to my channel for programming help 
https://www.youtube.com/channel/UCaYBAKpckm_6OSs7rJNGodQ?view_as=subscriber

**Comment by MortezaHeydari97** [comment]
## Hi guys. Please help me in flutter.


When I run `flutter doctor` command, It shows me this error:

![Untitled](https://user-images.githubusercontent.com/37476323/59932198-eb2c6200-945b-11e9-91fc-4b0a6c183608.png)



I update the flutter, Android Studio, and even sdk manager, however I see this error again.
Please help me to resolve this problem.

**Comment by clayton8011** [comment]
I search this page,but I don't look carefully.I try in Flutter console ,find config method,and set SDK path.Log tips type error. Add quotes pass.

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/flutter-does-not-find-android-sdk-2

**Comment by milanpatel18** [comment]
Flutter provide command to update our Android SDK path:

Use flutter config --android-sdk <path-to-your-android-sdk-p

**Comment by Krunal79-flutter** [comment]
Flutter provide command to update our Android SDK path:

Use flutter config --android-sdk <path-to-your-android-sdk-p

**Comment by srikanthkyatham** [comment]
For me the issue was the usage of tilde operator in the Android_home path.

I had to change my ANDROID_HOME 
export ANDROID_HOME=~/Library/Android/sdk ->
export ANDROID_HOME=/Users/username/Library/Android/sdk 

it worked after that

**Comment by sagarkhurana00786** [comment]
on running "flutter config --android-sdk /Users/sagarkhurana/Library/Android/sdk/"
getting output 

`Setting "android-sdk" value to "/Users/sagarkhurana/Library/Android/sdk/". You may need to restart any open editors for them to read new settings.
`

and after that running "flutter doctor --android-licenses"
getting same output 

`Android sdkmanager tool not found
(/Users/sagarkhurana/Library/Android/sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.`

Please help

**Comment by chuckinSpace** [comment]
I tried everything!, the only thing that worked for me was finding where the sdkmanger was in the first place, for me /usr/local/bin/sdkmanager and literally copy the sdk manager and paste it in the /users/username/Library/Android/sdk/tools/bin/sdkmanager. (yes I did create tools and bin folders because the were not there), after reinstalling and installing sdk and android studio at least 6 times, this was the only option left

**Comment by leohmoraes** [comment]
> on running "flutter config --android-sdk /Users/sagarkhurana/Library/Android/sdk/"
> getting output
> 
> `Setting "android-sdk" value to "/Users/sagarkhurana/Library/Android/sdk/". You may need to restart any open editors for them to read new settings. `
> 
> and after that running "flutter doctor --android-licenses"
> getting same output
> 
> `Android sdkmanager tool not found (/Users/sagarkhurana/Library/Android/sdk/tools/bin/sdkmanager). Try re-installing or updating your Android SDK, visit https://flutter.dev/setup/#android-setup for detailed instructions.`
> 
> Please help

Verify that following path exists: /Users/sagarkhurana/Library/Android/sdk/tools/bin/sdkmanager
My .zshrc (Catalina):

```
export PATH="$PATH:$HOME/flutter/flutter/bin"
export PATH="$PATH:$HOME/flutter/flutter/.pub-cache/bin"

export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
export ANDROID_HOME=$ANDROID_SDK_ROOT

export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
```
![image](https://user-images.githubusercontent.com/5436213/75921711-5b3f1480-5e40-11ea-8c3c-2c1436e217fc.png)

/Users/{USER}/Library/....

![image](https://user-images.githubusercontent.com/5436213/75923081-1ec0e800-5e43-11ea-9f32-8e85c639897f.png)

**Comment by mehdico** [comment]
on Mac OS open  /Users/YOUR USER NAME/.flutter_settings and edit the path.

**Comment by Merrit** [comment]
Found the solution thanks to sagarkhurana00786

On Linux I did:
`flutter config --android-sdk /home/merritt/Android/Sdk/`
(change to where your Sdk is actually installed)
