### ISSUE TITLE
Layout Tutorial Step 2 Broken

### ISSUE THREAD

**Issue by patientplatypus** [flutter/flutter#15112]
If you go to this site: [layout tutorial](https://flutter.io/tutorials/layout/) and copy step 2 into a basic flutter template so it looks like this: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Widget titleSection = new Container(
      padding: const EdgeInsets.all(32.0),
      child: new Row(
        children: [
          new Expanded(
            child: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                new Container(
                  padding: const EdgeInsets.only(bottom: 8.0),
                  child: new Text(
                    'Oeschinen Lake Campground',
                    style: new TextStyle(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                new Text(
                  'Kandersteg, Switzerland',
                  style: new TextStyle(
                    color: Colors.grey[500],
                  ),
                ),
              ],
            ),
          ),
          new Icon(
            Icons.star,
            color: Colors.red[500],
          ),
          new Text('41'),
        ],
      ),
    );
  }
}
```

You get the following error: 

```
Performing full restart...
Restarted app in 1,231ms.
I/flutter (26758): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (26758): The following assertion was thrown building MyApp(dirty):
I/flutter (26758): A build function returned null.
I/flutter (26758): The offending widget is: MyApp
I/flutter (26758): Build functions must never return null. To return an empty space that causes the building widget to
I/flutter (26758): fill available room, return "new Container()". To return an empty space that takes as little room as
I/flutter (26758): possible, return "new Container(width: 0.0, height: 0.0)".
I/flutter (26758): 
I/flutter (26758): When the exception was thrown, this was the stack:
I/flutter (26758): #0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:252:7)
I/flutter (26758): #1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:261:4)
I/flutter (26758): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3626:7)
I/flutter (26758): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (26758): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (26758): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (26758): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (26758): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (26758): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
I/flutter (26758): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
I/flutter (26758): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
I/flutter (26758): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter (26758): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
I/flutter (26758): #13     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
I/flutter (26758): #14     runApp (package:flutter/src/widgets/binding.dart:699:7)
I/flutter (26758): #15     main (/data/user/0/com.yourcompany.fluttertutorial3/cache/fluttertutorial3YYHCWZ/fluttertutorial3/lib/main.dart:3:16)
I/flutter (26758): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
I/flutter (26758): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter (26758): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I'm completely new to the language so it's a little difficult to debug if the tutorials don't compile.

**Comment by rrousselGit** [comment]
You created a widget but forgot to return it.

Thats what the exception is saying

**Comment by patientplatypus** [comment]
Hmmm.....Maybe the code examples in the tutorial could compile as you go? I didn't know I had to return anything.

**Comment by diegoaguiar90** [comment]
Hey guys, did you have have some problem with layouts tutorial, about dependecies?
I copy same code of tutorial but i always receive same error:
"Your application could not be compiled, because its dependencies could not be established.
Could not read "/home/cursos/Flutter/mylayoutapp/lib/main.dart" when determining Dart dependencies.
Exited (sigterm)"
Anyone had same problem?

**Comment by Hixie** [comment]
@diegoaguiar90 Please file a separate bug for separate problems. Thanks!

@patientplatypus Can you elaborate on which tutorial you were following and at which step it broke?

**Comment by Hixie** [comment]
@patientplatypus Oh, I see what you're seeing.
The tutorial is not attempting to have working code until step 6, when you put it all together.
Maybe we should make that clearer though.

**Comment by sadia60** [comment]
Add new before every Widget

**Comment by zoechi** [comment]
@sadia60 that sounds like you are using an old Flutter version. `new` became optional a while ago.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1911](https://github.com/flutter/website/issues/1911) via [**ZenHub**](https://www.zenhub.com/)

**Comment by InfiniteVerma** [comment]
The error occurs if you run after typing only the first section. I copied the entire text and it ran.
