### ISSUE TITLE
The application switches to the background and then back, causing the camera to freeze

### ISSUE THREAD

**Issue by 4396mingkai** [flutter/flutter#151161]
### Steps to reproduce

1.When my application opened the camera, switched to another application, and then switched back, the camera went black and was frozen. Currently, the reason cannot be found, and the console did not report an error

### Expected results

I hope to release camera resources when switching the application to the background, and then reload the camera to take photos when switching to the application

### Actual results

But in reality, when I switched the application to the background, I had already released the camera's resources and used the dispose method. However, when I switched back to the application and reinitialized the camera, the camera froze and could not take photos

### Code sample

```dart
// this is  'takephoto_controller.dart'  


import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:get/get.dart';
import '../../utils/api.dart';

// import 'package:flutter_easyloading/flutter_easyloading.dart';
import '../../global.dart';

import 'dart:io';
import '../../common/colors/theme_colors.dart';

import 'package:camera/camera.dart';
import 'package:image/image.dart' as imglib;

import 'package:tencentcloud_cos_sdk_plugin/cos.dart';
import 'package:tencentcloud_cos_sdk_plugin/cos_transfer_manger.dart';
import 'package:tencentcloud_cos_sdk_plugin/fetch_credentials.dart';
import 'package:tencentcloud_cos_sdk_plugin/pigeon.dart';
import 'package:tencentcloud_cos_sdk_plugin/transfer_task.dart';

import 'dart:async';

import 'package:image_picker/image_picker.dart';

class TakephotoController extends GetxController with WidgetsBindingObserver {
  late CameraController controller;
  final cameraInit = false.obs;
  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    WidgetsBinding.instance.addObserver(this); // 监听app切换前后台
    getCameras();
  }

  // 监听app的存活状态
  // 应用从后台切换到前台时的逻辑
  // 部分手机需要重新初始化相机 否则卡死
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    var _controller = controller;
    try {
       if (state == AppLifecycleState.inactive) {
        _controller.dispose();
      }

      // 应用从后台切换到前台
      if (state == AppLifecycleState.resumed) {
        print('切换到前台${controller.value.isInitialized}');
        // _controller.initialize();
         getCameras();
      }
    } catch (e) {
      getCameras();
    }
  }
// 屏幕聚焦
  void onScreenTapped() async {
    try {
      await controller.setExposureMode(ExposureMode.auto);
      await controller.setFocusMode(FocusMode.auto);
    } catch (e) {
      print('Error: $e');
    }
  }
  getCameras() async {
    List<CameraDescription> cameras = await availableCameras();
    controller = CameraController(cameras[0], ResolutionPreset.high, enableAudio: false);
    await controller.initialize();
    cameraInit.value = true;
  }
}
```

```dart
// this is  'takephoto_view.dart'  
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

import 'package:get/get.dart';

import '../../components/custom_scaffold.dart';
import 'takephoto_controller.dart';
import '../../common/colors/theme_colors.dart';

import 'dart:math' as math;

class TakephotoPage extends GetView<TakephotoController> {
  TakephotoPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Container(
          padding: const EdgeInsets.only(top: 50),
          width: Get.width,
          height: Get.height - 150,
          child: Obx(() => Container(
                padding: const EdgeInsets.symmetric(vertical: 0, horizontal: 0),
                child: !controller.cameraInit.value ? const SizedBox() : CameraPreview(controller.controller),
              ))),
      InkWell(
          onTap: () {
            controller.onScreenTapped();
          },
          child: Text('这是按钮'))
    ]);
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<video src="https://github.com/flutter/flutter/assets/28614556/7727327e-1d6a-4989-9a04-50a4622edbce" />

</details>

### Logs

<details open><summary>Logs</summary>

```console
java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@39bef79 rejected from java.util.concurrent.ThreadPoolExecutor@cf204be[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
E/System  (17505):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  (17505):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  (17505):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  (17505):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  (17505):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (17505):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:594)
E/System  (17505):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:900)
E/System  (17505):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:344)
E/System  (17505):      at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:329)
E/System  (17505):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:305)
E/System  (17505):      at java.lang.Daemons$Daemon.run(Daemons.java:150)
E/System  (17505):      at java.lang.Thread.run(Thread.java:1012)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.22631.3737], locale zh-CN)
    • Flutter version 3.22.2 on channel stable at D:\SDK\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\SDK\androidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\SDK\androidSDK
    • Java binary at: D:\installApp\androidstudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = D:\installApp\chrome\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.2)
    • Visual Studio at D:\installApp\visualStudio\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35004.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at D:\installApp\androidstudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Connected device (4 available)
    • PHF110 (mobile)   • 8954495c • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.3737]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 126.0.6478.61
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 126.0.2592.81

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @4396mingkai, what version of `camera` & `camera_android` are you experiencing this issue with? 

Does this happen with the camera plugin example app?

**Comment by 4396mingkai** [comment]
> 你好@4396mingkai，您使用版本`camera`时遇到的问题？`camera_android`
> 
> 相机插件示例文件是否创建了文件？

Hello, the camera version I am using is ^ 0.10.5+9, and the version number of android_camera is version: "0.10.9+2"
version:
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

I created a camera example but still have this problem

**Comment by 4396mingkai** [comment]
> Hi @4396mingkai, what version of `camera` & `camera_android` are you experiencing this issue with?
> 
> Does this happen with the camera plugin example app?

I upgraded the camera library to the latest version. Running the camera example is possible, but it still doesn't work in my project. Is it because it conflicts with the Getx library

**Comment by danagbemava-nc** [comment]
>  Is it because it conflicts with the Getx library

That could be. Can you try it without using Getx in your app? Also, instead of calling `getCameras` again, can you check how the plugin example handles the lifecycle changes and try to use that to see if you still experience the issue?
