### ISSUE TITLE
Not able to find element by Semantics in Release build

### ISSUE THREAD

**Issue by saikrishna321** [flutter/flutter#151238]
### Steps to reproduce

Unable to find element by Semantics 

### Expected results

Should be able to find element bySemanticsLabel

### Actual results

No element is found

### Code sample

<details open><summary>Code sample</summary>

FileName - test.dart
```dart
import 'package:appium_testing_app/main.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
            (tester) async {
          // Load app widget.
          await tester.pumpWidget(const MyApp());
          // Finds the floating action button to tap on.
          final fab = find.bySemanticsLabel('username_text_field');
          print(fab.evaluate());
          List<DiagnosticsNode> nodes = tester
              .widget(fab)
              .toDiagnosticsNode()
              .getProperties();
          // Emulate a tap on the floating action button.
          await tester.tap(fab);
          for (DiagnosticsNode node in nodes) {
            print("Flutter - ${node.name} -> ${node.value}");
          }
          // Trigger a frame.
          await tester.pumpAndSettle();
        });
  });
}
```
App Code
```
Semantics(
              label: "username_text_field",
              key: const Key("username_text_field"),
              // textField: true,
              explicitChildNodes: true,
              container: true,
              child: TextField(
                decoration:
                    const InputDecoration.collapsed(hintText: "Username"),
                controller: userNameController,
              ),
            ),
```

</details>

Command Used to build the IPA 

```
flutter build ipa --release --export-options-plist=/Documents/ExportOptions.plist  /Downloads/git/appium-flutter-server/demo-app/integration_test/test.dart
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
{"msg":"Jul  3 19:22:35 God- kernel(AppleMobileFileIntegrity)[0] \u003cNotice\u003e: AMFI: constraint violation /private/var/containers/Bundle/Application/394C6BFC-9825-4665-A685-48F161BF8357/Runner.app/Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview has entitlements but is not a main binary"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: 00:00 +0: end-to-end test tap on the floating action button, verify counter"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: Found 0 widgets with element matching predicate: []"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: Bad state: No element"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #0      Iterable.single (dart:core/iterable.dart:674)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #1      WidgetController.widget (package:flutter_test/src/controller.dart:801)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #2      main.\u003canonymous closure\u003e.\u003canonymous closure\u003e (file:///Users/saikrishna/Downloads/git/appium-flutter-server/demo-app/integration_test/test.dart:17)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: \u003casynchronous suspension\u003e"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #3      testWidgets.\u003canonymous closure\u003e.\u003canonymous closure\u003e (package:flutter_test/src/widget_tester.dart:183)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: \u003casynchronous suspension\u003e"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: \u003casynchronous suspension\u003e"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: #5      TestWidgetsFlutterBinding._createTestCompletionHandler.\u003canonymous closure\u003e (package:flutter_test/src/binding.dart:809)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: \u003casynchronous suspension\u003e"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: 00:00 +0: end-to-end test tap on the floating action button, verify counter [E]"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter:   Test failed. See exception logs above.\n  The test description was: tap on the floating action button, verify counter"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter:"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: 00:00 +0 -1: (tearDownAll)"}
{"msg":"Jul  3 19:22:36 God- Runner(Flutter)[66332] \u003cNotice\u003e: flutter: 00:00 +1 -1: Some tests failed."}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by sudharsan-selvaraj** [comment]
This behaviour is only observed in iOS real devices on release builds.

**Comment by huycozy** [comment]
@saikrishna321 Looks like you hit https://github.com/flutter/flutter/issues/147020. But since you mentioned this only occurs in release mode, I also tried reproducing it. I see that this occurs in debug mode with `flutter test <test-file>` as well, can you confirm this?

If the issue only happens with `flutter build`, can you update the steps? What is the next step to produce the error?

**Comment by saikrishna321** [comment]
@huycozy Thanks for taking time and looking into the issue. 

I'm able to run the test and it works fine in debug mode. 
Command: `flutter run integration_test/test.dart`

Logs

```
2024-07-04 11:46:07.086326+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: 00:00 +0: end-to-end test tap on the floating action button, verify counter
2024-07-04 11:46:07.614498+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Found 1 widget with element matching predicate: [
2024-07-04 11:46:07.663491+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - container -> true
2024-07-04 11:46:07.663790+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - properties -> SemanticsProperties(label: "username_text_field")
2024-07-04 11:46:07.663894+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - checked -> null
2024-07-04 11:46:07.663955+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - mixed -> null
2024-07-04 11:46:07.664044+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - expanded -> null
2024-07-04 11:46:07.664166+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - selected -> null
2024-07-04 11:46:07.664242+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - identifier -> null
2024-07-04 11:46:07.664320+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - label -> username_text_field
2024-07-04 11:46:07.664382+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - attributedLabel -> null
2024-07-04 11:46:07.664455+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - value -> null
2024-07-04 11:46:07.664506+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - attributedValue -> null
2024-07-04 11:46:07.664626+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - increasedValue -> null
2024-07-04 11:46:07.664694+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - attributedIncreasedValue -> null
2024-07-04 11:46:07.664753+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - decreasedValue -> null
2024-07-04 11:46:07.664806+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - attributedDecreasedValue -> null
2024-07-04 11:46:07.664856+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - hint -> null
2024-07-04 11:46:07.664905+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - attributedHint -> null
2024-07-04 11:46:07.664957+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - tooltip -> null
2024-07-04 11:46:07.665040+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - textDirection -> null
2024-07-04 11:46:07.665133+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - sortKey -> null
2024-07-04 11:46:07.665211+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: Flutter - hintOverrides -> null
2024-07-04 11:46:08.736662+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: 00:01 +1: (tearDownAll)
2024-07-04 11:46:08.769432+0530 0xeb7c99   Default     0x0                  23210  0    Runner: (Flutter) flutter: 00:01 +2: All tests passed!
```

The problem exists when we build the IPA in release mode. 

```
flutter build ipa --release --export-options-plist=/Documents/ExportOptions.plist  /Downloads/git/appium-flutter-server/demo-app/integration_test/test.dart
```

This creates a IPA and I install the IPA on the device outside flutter context. Now I open the app and expect the test.dart to get executed but it can't the locator with Semantics Label.

Let me know if you need any more information.

**Comment by huycozy** [comment]
@saikrishna321 It seems this requires distributing ipa to device. Unfortunately, there is a signing issue on my end so I can't try this now. Could you please confirm:
- Does this issue only occur with `bySemanticsLabel` but not with `byType`/`byKey` or similar?
- Does this issue occur on Android as well?
- What is your current Flutter version? Could you try on the latest stable (3.22.2) or master (3.23.x) version?

**Comment by saikrishna321** [comment]
@huycozy 

>> Does this issue only occur with bySemanticsLabel but not with byType/byKey or similar?

Happens only on bySemanticsLabel others work fine. 

>> Does this issue occur on Android as well?

No issues. 

>> Flutter Version

Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (6 weeks ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3


Let me try updating to the latest and update this ticket.

**Comment by saikrishna321** [comment]
@huycozy Tried with flutter 3.22.2 its the same 

```
❯ flutter --version
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

**Comment by huycozy** [comment]
Thanks for checking that. I confirm I also can reproduce this issue by the following steps:

1. Build project in release mode for the test (to make sure it can point to correct target test file instead of main.dart by default, can re-check this on `FLUTTER_TARGET` from `ios/Flutter/Generated.xcconfig` file)
```
flutter build ipa --release  /Users/huynq/Desktop/repro_issues/integration_test/semantic_151238_test.dart
```
2. Open `ios` module on XCode
3. Adjust the current scheme by selecting `Release` in Build Configuration
4. Run project on a device from XCode and see the test has failed with stack trace as provided in Logs section above

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-14.0.pre.145, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-14.0.pre.145 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac74e26a70 (2 hours ago), 2024-07-04 21:46:34 -0400
    • Engine revision 1f0f950ea0
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by saikrishna321** [comment]
@huycozy Thank you for verifying and confirming the issue. Could you please let us know the next course of action for this ticket? Additionally, is there a plan to address this issue in the upcoming release?

We are building a flutter-integration-driver for appium https://github.com/AppiumTestDistribution/appium-flutter-integration-driver. We will point to this ticket.

**Comment by huycozy** [comment]
@saikrishna321 The issue will be verified by domain team (ios team in this case) and then be prioritized. You can check [Team issue triage process](https://github.com/flutter/flutter/blob/master/docs/triage/README.md#team-issue-triage-process) and [Priorities](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#priorities) for more information.

**Comment by jmagman** [comment]
It looks like `bySemanticsLabel` uses the `debugSemantics` label.
https://github.com/flutter/flutter/blob/f2be1260dfe59084cb4ec382dbbe914ed62c8bf8/packages/flutter_driver/lib/src/common/handler_factory.dart#L63-L71

Which is null in release mode.
https://github.com/flutter/flutter/blob/f2be1260dfe59084cb4ec382dbbe914ed62c8bf8/packages/flutter/lib/src/rendering/object.dart#L3574-L3585

I'm not familiar how this works, from that comment maybe something can be done with `PipelineOwner.ensureSemantics`?


I'm unsure how in the world this would be working on Android though...

> > > Does this issue occur on Android as well?
> 
> No issues.

**Comment by pulpcorn** [comment]
Hi,
Any updates for this?
I came to this topic from #151236 because I met same issue since built build ipa in debug mode.

I tried to run multiple_flutters_ios and embeded to my native ios code, everything works fine in simulator.
When I built ipa in debug mode, it still fine. I can normally open ios app on my iphone but tapped on Flutter embeded functions it crashed.

The log on XCode said "Cannot create a FlutterEngine instance in debug mode without Flutter tooling or Xcode.
To launch in debug mode in iOS 14+, run flutter run from Flutter tools, run from an IDE with a Flutter IDE plugin or run the iOS project from Xcode.
Alternatively profile and release mode apps can be launched from the home screen."

Thanks.
