### ISSUE TITLE
[tool] Adding an `await` to `DefaultResidentCompiler._recompile` fails test(s) in test/general.shard/devfs_test.dart

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#151255]
Discovered while working on https://github.com/flutter/flutter/pull/151146. Blocks fixing https://github.com/flutter/flutter/issues/137184.

### Repro
1. Checkout master (I used fbd6890fb7bc29097ac7a40034ed60a6513f5194).
2. Open [packages/flutter_tools/lib/src/compile.dart](https://github.com/flutter/flutter/blob/e410b7cd5e01554f899d43c5b2a8ee5baea7e760/packages/flutter_tools/lib/src/compile.dart#L748). Add `await Future.value()` after the `server.stdin.writeln('recompile $mainUri $inputKey');` (the line in the link).
3. Run [this test](https://github.com/flutter/flutter/blob/0fc08abe5b9b092214f30664fbec7f2f6ca9d267/packages/flutter_tools/test/general.shard/devfs_test.dart#L499) using `dart test test/general.shard/devfs_test.dart --name "DevFS actually starts compile before processing bundle"` from the packages/flutter_tools directory.

The test will fail:

```
andrewkolos-macbookpro:flutter_tools andrewkolos$ dart test test/general.shard/devfs_test.dart --name "DevFS actually starts compile before processing bundle"
Building package executable... (1.8s)
Built test:test.
00:01 +0: DevFS actually starts compile before processing bundle                                                                                                                                                                
Expected: a value greater than <3>
  Actual: <2>
   Which: is not a value greater than <3>

#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect (package:matcher/src/expect/expect.dart:144:3)
#2      expect (package:matcher/src/expect/expect.dart:56:3)
#3      main.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/general.shard/devfs_test.dart:603:5)
<asynchronous suspension>
#4      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/src/context.dart:151:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/andrewkolos/Documents/GitHub/flutter/packages/flutter_tools/test/src/context.dart:140:22)
<asynchronous suspension>

line1
line2
line1
line2

00:01 +0 -1: DevFS actually starts compile before processing bundle [E]                                                                                                                                                         
  Expected: a value greater than <3>
    Actual: <2>
     Which: is not a value greater than <3>
  
  package:matcher                                     expect
  test/general.shard/devfs_test.dart 603:5            main.<fn>
  ===== asynchronous gap ===========================
  test/src/context.dart 151:26                        testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:flutter_tools/src/base/context.dart 153:19  AppContext.run.<fn>
  ===== asynchronous gap ===========================
  test/src/context.dart 140:22                        testUsingContext.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/andrewkolos/Documents/GitHub/flutter/bin/cache/dart-sdk/bin/dart test test/general.shard/devfs_test.dart -p vm --plain-name 'DevFS actually starts compile before processing bundle'
00:01 +0 -1: Some tests failed.                                                                                                                                                                                                 

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

Looks like this method deferring to the event loop causes a mis-sequencing of events somehow.

**Comment by andrewkolos** [comment]
https://github.com/flutter/flutter/pull/92255 seems related. I haven't properly investigated yet, but I wonder if this was a timing hack (adding an `await null;` to mess with execution order).

**Comment by andrewkolos** [comment]
Adding an await to [`TestCompiler._onCompilationRequest`](https://github.com/flutter/flutter/blob/21d996929bb96facd791d650d1ad35e6024d44ae/packages/flutter_tools/lib/src/test/test_compiler.dart#L212) seems to be able to fail a different [test](https://github.com/flutter/flutter/blob/21d996929bb96facd791d650d1ad35e6024d44ae/packages/flutter_tools/test/general.shard/test/test_compiler_test.dart#L111). Possibly related.

**Comment by jonahwilliams** [comment]
There is definitely some weirdness in this sequencing. IIRC, we had some issues with async/await causing us to not actually run certain jobs concurrently. I can try to dig up those issues next week, or feel free to grab to if you want to do some debugging.

**Comment by andrewkolos** [comment]
> There is definitely some weirdness in this sequencing. IIRC, we had some issues with async/await causing us to not actually run certain jobs concurrently. I can try to dig up those issues next week, or feel free to grab to if you want to do some debugging.

Reading into https://github.com/flutter/flutter/pull/92255, it does seem like we want to run compilation in parallel with building the asset bundle.

In `DevFS::update`, we see [a call to recompile Dart code](https://github.com/flutter/flutter/blob/13beab1ecccf52993ae6bfcce4150fa4d3b734f2/packages/flutter_tools/lib/src/devfs.dart#L598) (`ResidentCompiler::recompile`). However, we don't `await` this, because we want to concurrently build the asset bundle (this code immediately proceeds the `recompile` call). The idea here is that bundle processing happens on the main and only isolate, while the dart compilation happens in another process. This is what allows us to do this concurrently despite the Flutter tool running as a single isolate.

However, due to the implementation of `ResidentCompiler`, the recompilation request isn't sent off to the compiler process until one turning of the event loop (`ResidentCompiler::recompile` merely enqueues a compilation request on an internal stream)[^1]. To work around this, https://github.com/flutter/flutter/pull/92255 added an `await null` to the bundle-building code to turn the event loop. However, adding _N_ additional `await`s to `DefaultResidentCompiler::_recompile` before the actual call to the frontend server will again result in the recompilation request not being sent off until _N_ more turnings of the event loop, hence this issue.

I think `ResidentCompiler::recompile` and friends should return a separate future that represents when compilation has actually started. Then, `DevFS::update` can `await` that, start processing the bundle, and _then_ `await` completion of compilation.

[^1]: An internal `stream` is used to enforce serial processing of compilation requests. See https://github.com/flutter/flutter/pull/18618 for the reason behind this.

**Comment by andrewkolos** [comment]
Unassigning this doesn't necessarily block fixing https://github.com/flutter/flutter/issues/137184. This issue can probably be worked around.

**Comment by andrewkolos** [comment]
In the context of https://github.com/flutter/flutter/issues/137184, I attempted to work around this issue by simply serializing calls to `ProcessUtils.writelnToStdinGuarded` and not awaiting them, but this seems to result in a race (that's never won). [Logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8742824882489477457/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/stdout). I'm guessing that the change is causing `DefaultResidentCompiler::recompile` to complete before we actually write everything to the test compiler, (`IOSink::flush` is fast but not de-facto instant like `IOSink::write` is). I didn't actually confirm this, but I don't think it's even worth the time. This issue is something we should just fix properly.

**Comment by andrewkolos** [comment]
Unassigning as I plan to work around the issue by extending the existing hack.
