### ISSUE TITLE
Exception for calling availableCameras() with cached engine and FlutterFragment on Android

### ISSUE THREAD

**Issue by theManWithoutQualities** [flutter/flutter#151358]
### Steps to reproduce

Create an Android project with add-to-app Flutter module, cached engine and navigation to/from FlutterFragment as in [example](https://github.com/theManWithoutQualities/TryFlutterModule)
Add call of availableCameras() in flutter code after navigation to FlutterFragment.
In application: navigate to FlutterFragment -> close it by back button -> open new FlutterFragment

### Expected results

No exception for availableCameras()

### Actual results

Exception for availableCameras()
```
PlatformException(java.lang.NullPointerException, NullPointerException, Cause: null, Stacktrace: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:220)
at io.flutter.plugins.camerax.CameraSelectorHostApiImpl.filter(CameraSelectorHostApiImpl.java:49)
at io.flutter.plugins.camerax.GeneratedCameraXLibrary$CameraSelectorHostApi.lambda$setup$1(GeneratedCameraXLibrary.java:1039)
at io.flutter.plugins.camerax.GeneratedCameraXLibrary$CameraSelectorHostApi$$ExternalSyntheticLambda1.onMessage(D8$$SyntheticClass:0)
at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
, null)
```

### Code sample

[Code in example project](https://github.com/theManWithoutQualities/TryFlutterModule/blob/main/flutter_module/lib/main.dart)

### Flutter Doctor output

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-BY)
    • Flutter version 3.22.2 on channel stable at /Users/mikalai/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mikalai/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/mikalai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.85.1)
    • VS Code at /Users/mikalai/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```

**Comment by huycozy** [comment]
I checked this issue on both Flutter stable 3.22.2 but I saw a different exception:

```console
E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
   #0      InstanceManagerHostApi.clear (package:camera_android_camerax/src/camerax_library.g.dart:315:7)
   <asynchronous suspension>
I  Connecting to camera service
D  Added camera: 0
I  Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
D  Added camera: 1
I  Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
```

After try upgrading to Flutter master channel (I'm on 3.23.0-14.0.pre.157), I don't see that exception anymore. By any chance, could you also try on Flutter master channel?

**Comment by theManWithoutQualities** [comment]
@huycozy 
I confirm the reported behaviour on Flutter master channel as well (the stack trace is slightly different). I tested on emulators and device.

<details>
  <summary>Flutter Doctor</summary>

  ```
[✓] Flutter (Channel master, 3.23.0-14.0.pre.159, on macOS 14.5 23F79 darwin-x64, locale en-BY)
    • Flutter version 3.23.0-14.0.pre.159 on channel master at /Users/mikalai/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 484cddd1a4 (5 hours ago), 2024-07-08 04:09:13 -0400
    • Engine revision 69075e7e87
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mikalai/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/mikalai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.85.1)
    • VS Code at /Users/mikalai/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```
</details>

<details>
  <summary>Exception</summary>

```
PlatformException(java.lang.NullPointerException, NullPointerException, Cause: null, Stacktrace: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at io.flutter.plugins.camerax.ProcessCameraProviderHostApiImpl.getAvailableCameraInfos(ProcessCameraProviderHostApiImpl.java:92)
at io.flutter.plugins.camerax.GeneratedCameraXLibrary$ProcessCameraProviderHostApi.lambda$setup$1(GeneratedCameraXLibrary.java:1157)
at io.flutter.plugins.camerax.GeneratedCameraXLibrary$ProcessCameraProviderHostApi$$ExternalSyntheticLambda1.onMessage(D8$$SyntheticClass:0)
at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
com.example.tryfluttermodule         I  , null)
```
</details>
Just to be sure I explain steps clear: I push button in my app and go to Flutter fragment, then **go back** by system back button, then **go to Flutter fragment for the second time**.

I did these steps with debug build. I tried with release build and saw the exception you mentioned when I went to Flutter fragment for the first time (didn't see in debug build). I believe, this case can be something about proguard/R8.

However, my exception takes place in both release and debug build modes.

**Comment by huycozy** [comment]
Thanks for providing the clear steps. I can reproduce NullPointerException now. 

<details>
<summary>Output log</summary>

```console
2024-07-09 11:15:03.485 32522-32612 flutter                 com.example.tryfluttermodule         E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                                                                    #0      InstanceManagerHostApi.clear (package:camera_android_camerax/src/camerax_library.g.dart:315:7)
                                                                                                    <asynchronous suspension>
2024-07-09 11:15:03.489 32522-32612 flutter                 com.example.tryfluttermodule         I  PlatformException(channel-error, Unable to establish connection on channel., null, null)
2024-07-09 11:17:12.644 32522-32522 WindowOnBackDispatcher  com.example.tryfluttermodule         W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2024-07-09 11:17:12.749 32522-357   CameraManagerGlobal     com.example.tryfluttermodule         I  Connecting to camera service
2024-07-09 11:17:12.793 32522-357   CameraRepository        com.example.tryfluttermodule         D  Added camera: 0
2024-07-09 11:17:12.803 32522-357   Camera2CameraInfo       com.example.tryfluttermodule         I  Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
2024-07-09 11:17:12.805 32522-357   CameraRepository        com.example.tryfluttermodule         D  Added camera: 1
2024-07-09 11:17:12.806 32522-357   Camera2CameraInfo       com.example.tryfluttermodule         I  Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
2024-07-09 11:17:12.806 32522-357   CameraValidator         com.example.tryfluttermodule         D  Verifying camera lens facing on panther, lensFacingInteger: null
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  PlatformException(java.lang.NullPointerException, NullPointerException, Cause: null, Stacktrace: java.lang.NullPointerException
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at java.util.Objects.requireNonNull(Objects.java:207)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.plugins.camerax.ProcessCameraProviderHostApiImpl.getAvailableCameraInfos(ProcessCameraProviderHostApiImpl.java:92)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$ProcessCameraProviderHostApi.lambda$setup$1(GeneratedCameraXLibrary.java:1157)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$ProcessCameraProviderHostApi$$ExternalSyntheticLambda1.onMessage(D8$$SyntheticClass:0)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at android.os.Handler.handleCallback(Handler.java:959)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at android.os.Handler.dispatchMessage(Handler.java:100)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at android.os.Looper.loopOnce(Looper.java:232)
2024-07-09 11:17:12.818 32522-32612 flutter                 com.example.tryfluttermodule         I  	at android.os.Looper.loop(Looper.java:317)
2024-07-09 11:17:12.819 32522-32612 flutter                 com.example.tryfluttermodule         I  	at android.app.ActivityThread.main(ActivityThread.java:8592)
2024-07-09 11:17:12.819 32522-32612 flutter                 com.example.tryfluttermodule         I  	at java.lang.reflect.Method.invoke(Native Method)
2024-07-09 11:17:12.819 32522-32612 flutter                 com.example.tryfluttermodule         I  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
2024-07-09 11:17:12.819 32522-32612 flutter                 com.example.tryfluttermodule         I  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-07-09 11:17:12.819 32522-32612 flutter                 com.example.tryfluttermodule         I  , null)
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-14.0.pre.157, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-14.0.pre.157 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ad6166a8b8 (3 hours ago), 2024-07-07 19:58:25 -0400
    • Engine revision ca79a56a66
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode15.4.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.127
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by gmackall** [comment]
From Android triage: cc @bparrishMines @camsim99 
Looks like the error is coming from here
https://github.com/flutter/packages/blob/main/packages/camera/camera_android_camerax/android/src/main/java/io/flutter/plugins/camerax/CameraSelectorHostApiImpl.java#L49
Do we expect that a cached version of the engine would interact poorly with the instance manager/have any other bugs that have run into that class of problem?

**Comment by camsim99** [comment]
So, `filter` gets called on a newly created `CameraSelector` in `availableCameras` (see [source](https://github.com/flutter/packages/blob/4d02058efbe5fd70d6afac6139fecc482bbaa9db/packages/camera/camera_android_camerax/lib/src/android_camera_camerax.dart#L281-L284)), so I find it odd that the new `CameraSelector` instance would no longer have an identifier after going back, but I do recall us expecting complications with add-to-app use cases.
 
@bparrishMines Do you have any insight on this?

**Comment by bparrishMines** [comment]
@gmackall I'm not that familiar with add-to-app scenario for a cached engine on Android. Do you know if the [FlutterPlugin](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html) events get triggered. Also do any of the [ActivityAware](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html) events trigger? They could potentially break the interop, but I'll will probably need to log in an example app to see what specifically is being triggered.

**Comment by josephmangmang** [comment]
Hi me also have problem when opening camera 0.11 from android host app via flutter 
I start the flutter app from kotlin:
```
startActivity(
                FlutterActivity
                    .withCachedEngine(MyApplication.FLUTTER_ENGINE_ID)
                    .build(this)
            )
```
Then I got this error when accessing camera API again.

```
Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b13e581 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    android.app.IntentReceiverLeaked: Activity io.flutter.embedding.android.FlutterActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b13e581 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                                    	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1594)
                                                                                                    	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1374)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1614)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1580)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1568)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:668)
                                                                                                    	at io.flutter.plugins.camerax.DeviceOrientationManager.start(DeviceOrientationManager.java:73)
                                                                                                    	at io.flutter.plugins.camerax.DeviceOrientationManagerHostApiImpl.startListeningForDeviceOrientationChange(DeviceOrientationManagerHostApiImpl.java:65)
                                                                                                    	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi.lambda$setup$0(GeneratedCameraXLibrary.java:1606)
                                                                                                    	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi$$ExternalSyntheticLambda0.onMessage(D8$$SyntheticClass:0)
                                                                                                    	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by josephmangmang** [comment]
This is related to my issue https://github.com/flutter/flutter/issues/155492

**Comment by vlasentiy** [comment]
I had the same problem when used ver. [^0.11.0+2](https://pub.dev/packages/camera), but if you use [0.10.6](https://pub.dev/packages/camera/versions/0.10.6) it's everything works. Answer is in change that android implementation of the camera plugin migrate from camera_android to camera_android_camerax
