### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by biniyam-a2sv** [flutter/flutter#151461]
## Command
```
flutter --quiet assemble --no-version-check --depfile C:\Users\user\Documents\Projects\RateEat\rateeat_business_mobile\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Users\user\Documents\Projects\RateEat\rateeat_business_mobile\build\app\intermediates\flutter\debug -dTargetFile=C:\Users\user\Documents\Projects\RateEat\rateeat_business_mobile\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9lZGQ4NTQ2MTE2NDU3YmRmMWM1YmRmYjEzZWNiOTQ2M2QyYmI1ZWQ0Lw== -dFlavor= -dAndroidArchs=android-x64 -dMinSdkVersion=21 debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:80:12)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:778:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:666:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:322:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\user\OneDrive\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.91.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.93.20240702

[✓] Connected device (5 available)
    • SM A315G (mobile)            • RR8NA07Q2ZN   • android-arm64  • Android 12 (API 31)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 126.0.2592.87

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d
### Plugins
connectivity_plus-6.0.3
firebase_analytics-11.1.0
firebase_analytics_web-0.5.8
firebase_core-3.1.1
firebase_core_web-2.17.2
firebase_in_app_messaging-0.8.0+2
firebase_messaging-15.0.2
firebase_messaging_web-3.8.10
firebase_performance-0.10.0+2
firebase_performance_web-0.1.6+10
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
sqflite-2.3.3+1
video_player-2.8.6
video_player_android-2.4.14
video_player_avfoundation-2.6.1
video_player_web-2.3.0

**Comment by danagbemava-nc** [comment]
Does this reproduce consistently? If so, can you try one of the techniques from [superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows](https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows) to determine what other process is using these files?

If there is a bug in the Flutter SDK, we would need reproducible steps in order to diagnose and fix.

**Comment by FusoraTech** [comment]
> • Flutter version 3.22.2 on channel stable at C:\Users\user\OneDrive\Documents\flutter

Don't put your tooling and dev environment inside any "internet shared" folder.

Make it local, Copy to shared places only to store/share afterwards, not "live".
