### ISSUE TITLE
issue when enable minifyEnabled as true

### ISSUE THREAD

**Issue by georgesamirt2** [flutter/flutter#151456]
### Steps to reproduce

when creating  minifyEnabled and shrinkResources  as true project is crashed and plugin doesn't work
build.gradle

```gradle
buildTypes {
  release {
      minifyEnabled true
      shrinkResources true
     .......
  }
```

### Expected results

Camera to be worked fine with shrink resources and minfyEnable as true

### Actual results

```console
I/CameraManagerGlobal(28857): Connecting to camera service
D/VendorTagDescriptor(28857): addVendorDescriptor: vendor tag id 11706189966126095484 added
D/VendorTagDescriptor(28857): addVendorDescriptor: vendor tag id 15055940602041719656 added
I/CameraManagerGlobal(28857): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client app.t2.test.availo API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 2 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 20 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 21 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 23 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 3 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 4 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client client.pid<1638> API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 52 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 54 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 56 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 58 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 90 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
D/CameraRepository(28857): Added camera: 0
E/AndroidRuntime(28857): FATAL EXCEPTION: CameraX-core_camera_0
E/AndroidRuntime(28857): Process: app.t2.test.availo, PID: 28857
E/AndroidRuntime(28857): java.lang.ExceptionInInitializerError
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraControlImpl.<init>(Camera2CameraControlImpl.java:210)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraImpl.<init>(Camera2CameraImpl.java:246)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraFactory.getCamera(Camera2CameraFactory.java:93)
E/AndroidRuntime(28857): 	at androidx.camera.core.impl.CameraRepository.init(CameraRepository.java:66)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2(CameraX.java:331)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX.$r8$lambda$dnuYhxGsACX_lH-9SVlUVTdtTJg(Unknown Source:0)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda1.run(Unknown Source:10)
E/AndroidRuntime(28857): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(28857): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(28857): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(28857): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: androidx.camera.core.impl.CameraCaptureMetaData$AfState.values []
E/AndroidRuntime(28857): 	at java.lang.Enum.enumValues(Enum.java:315)
E/AndroidRuntime(28857): 	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
E/AndroidRuntime(28857): 	at java.lang.Enum$1.create(Enum.java:322)
E/AndroidRuntime(28857): 	at java.lang.Enum$1.create(Enum.java:320)
E/AndroidRuntime(28857): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(28857): 	at java.lang.Enum.getSharedConstants(Enum.java:334)
E/AndroidRuntime(28857): 	at java.lang.Class.getEnumConstantsShared(Class.java:4036)
E/AndroidRuntime(28857): 	at java.util.EnumSet.getUniverse(EnumSet.java:410)
E/AndroidRuntime(28857): 	at java.util.EnumSet.noneOf(EnumSet.java:112)
E/AndroidRuntime(28857): 	at java.util.EnumSet.of(EnumSet.java:286)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CapturePipeline.<clinit>(Camera2CapturePipeline.java:86)
E/AndroidRuntime(28857): 	... 10 more
E/AndroidRuntime(28857): Caused by: java.lang.NoSuchMethodException: androidx.camera.core.impl.CameraCaptureMetaData$AfState.values []
E/AndroidRuntime(28857): 	at java.lang.Class.getMethod(Class.java:2937)
E/AndroidRuntime(28857): 	at java.lang.Class.getDeclaredMethod(Class.java:2914)
E/AndroidRuntime(28857): 	at java.lang.Enum.enumValues(Enum.java:312)
E/AndroidRuntime(28857): 	... 20 more
I/Process (28857): Sending signal. PID: 28857 SIG: 9
```
### Code sample

<details open><summary>Code sample</summary>

```dart
static Future<void> initCamera() async {
    try {
      final list = await availableCameras();
      if (cameras.isNotEmpty) {
        cameras.clear();
      }
      cameras.addAll(list);
    } catch (error, stackTrace) {
      clog.log('', error: error, stackTrace: stackTrace);
    }
    return Future.value();
  }

void main() async {
WidgetsFlutterBinding.ensureInitialized();
await  initCamera();
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/CameraManagerGlobal(28857): Connecting to camera service
D/VendorTagDescriptor(28857): addVendorDescriptor: vendor tag id 11706189966126095484 added
D/VendorTagDescriptor(28857): addVendorDescriptor: vendor tag id 15055940602041719656 added
I/CameraManagerGlobal(28857): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client app.t2.test.availo API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 2 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 20 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 21 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 23 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 3 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 4 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client client.pid<1638> API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 52 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 54 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 56 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 58 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
I/CameraManagerGlobal(28857): Camera 90 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client android.system API Level 2 User Id 0
D/CameraRepository(28857): Added camera: 0
E/AndroidRuntime(28857): FATAL EXCEPTION: CameraX-core_camera_0
E/AndroidRuntime(28857): Process: app.t2.test.availo, PID: 28857
E/AndroidRuntime(28857): java.lang.ExceptionInInitializerError
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraControlImpl.<init>(Camera2CameraControlImpl.java:210)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraImpl.<init>(Camera2CameraImpl.java:246)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CameraFactory.getCamera(Camera2CameraFactory.java:93)
E/AndroidRuntime(28857): 	at androidx.camera.core.impl.CameraRepository.init(CameraRepository.java:66)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2(CameraX.java:331)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX.$r8$lambda$dnuYhxGsACX_lH-9SVlUVTdtTJg(Unknown Source:0)
E/AndroidRuntime(28857): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda1.run(Unknown Source:10)
E/AndroidRuntime(28857): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(28857): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(28857): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(28857): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: androidx.camera.core.impl.CameraCaptureMetaData$AfState.values []
E/AndroidRuntime(28857): 	at java.lang.Enum.enumValues(Enum.java:315)
E/AndroidRuntime(28857): 	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
E/AndroidRuntime(28857): 	at java.lang.Enum$1.create(Enum.java:322)
E/AndroidRuntime(28857): 	at java.lang.Enum$1.create(Enum.java:320)
E/AndroidRuntime(28857): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(28857): 	at java.lang.Enum.getSharedConstants(Enum.java:334)
E/AndroidRuntime(28857): 	at java.lang.Class.getEnumConstantsShared(Class.java:4036)
E/AndroidRuntime(28857): 	at java.util.EnumSet.getUniverse(EnumSet.java:410)
E/AndroidRuntime(28857): 	at java.util.EnumSet.noneOf(EnumSet.java:112)
E/AndroidRuntime(28857): 	at java.util.EnumSet.of(EnumSet.java:286)
E/AndroidRuntime(28857): 	at androidx.camera.camera2.internal.Camera2CapturePipeline.<clinit>(Camera2CapturePipeline.java:86)
E/AndroidRuntime(28857): 	... 10 more
E/AndroidRuntime(28857): Caused by: java.lang.NoSuchMethodException: androidx.camera.core.impl.CameraCaptureMetaData$AfState.values []
E/AndroidRuntime(28857): 	at java.lang.Class.getMethod(Class.java:2937)
E/AndroidRuntime(28857): 	at java.lang.Class.getDeclaredMethod(Class.java:2914)
E/AndroidRuntime(28857): 	at java.lang.Enum.enumValues(Enum.java:312)
E/AndroidRuntime(28857): 	... 20 more
I/Process (28857): Sending signal. PID: 28857 SIG: 9
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3810], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2023.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @georgesamirt2 
I ran the complete sample code below in `release` mode but couldn't reproduce the issue on my device (Pixel 7, Android 14):

<details>
<summary>Sample code</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  // Ensure that plugin services are initialized so that `availableCameras()`
  // can be called before `runApp()`
  WidgetsFlutterBinding.ensureInitialized();

  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();

  // Get a specific camera from the list of available cameras.
  final firstCamera = cameras.first;

  runApp(
    MaterialApp(
      theme: ThemeData.dark(),
      home: TakePictureScreen(
        // Pass the appropriate camera to the TakePictureScreen widget.
        camera: firstCamera,
      ),
    ),
  );
}

// A screen that allows users to take a picture using a given camera.
class TakePictureScreen extends StatefulWidget {
  const TakePictureScreen({
    super.key,
    required this.camera,
  });

  final CameraDescription camera;

  @override
  TakePictureScreenState createState() => TakePictureScreenState();
}

class TakePictureScreenState extends State<TakePictureScreen> {
  late CameraController _controller;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,
      // Define the resolution to use.
      ResolutionPreset.medium,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        // Provide an onPressed callback.
        onPressed: () async {
          // Take the Picture in a try / catch block. If anything goes wrong,
          // catch the error.
          try {
            // Ensure that the camera is initialized.
            await _initializeControllerFuture;

            // Attempt to take a picture and get the file `image`
            // where it was saved.
            final image = await _controller.takePicture();

            if (!context.mounted) return;

            // If the picture was taken, display it on a new screen.
            await Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => DisplayPictureScreen(
                  // Pass the automatically generated path to
                  // the DisplayPictureScreen widget.
                  imagePath: image.path,
                ),
              ),
            );
          } catch (e) {
            // If an error occurs, log the error to the console.
            print(e);
          }
        },
        child: const Icon(Icons.camera_alt),
      ),
    );
  }
}

// A widget that displays the picture taken by the user.
class DisplayPictureScreen extends StatelessWidget {
  final String imagePath;

  const DisplayPictureScreen({super.key, required this.imagePath});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Display the Picture')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Image.file(File(imagePath)),
    );
  }
}

```
</details>

What version of camera package are you working on? And please provide device info as well (os, model). Thanks!

**Comment by georgesamirt2** [comment]
Android version 14 with One UI (6.1)
device info Samsung s23 ultra
Plugin version 
camera: ^0.11.0+1

**Comment by huycozy** [comment]
Here is my `buildTypes`, I enabled settings for both debug and release modes but still couldn't reproduce the exception as reported.

```gradle
buildTypes {
    debug {
        shrinkResources true
        minifyEnabled true
    }
    release {
        // TODO: Add your own signing config for the release build.
        // Signing with the debug keys for now, so `flutter run --release` works.
        signingConfig signingConfigs.release
        shrinkResources true
        minifyEnabled true
    }
}
```

>while calling the previews function on main it returns this exception and application crash

Have you tried my sample code above? Can it reproduce the crash as reported on your device? If it's not the same, please provide an updated one, thanks!

**Comment by georgesamirt2** [comment]
While I have used older version 0.10.6 it works fine and after using new version 0.11.0+1

**Comment by huycozy** [comment]
I'm also using the latest package version `camera: ^0.11.0+1` but still can't reproduce this. From `0.11.0`, `camera` will use `camera_android_camerax` instead of `camera_android`. But I think this could be a ProGuard issue, please see a such similar case https://github.com/flutter/flutter/issues/113157#issuecomment-1273543447 to see if it helps. Otherwise, please provide a minimal sample project that doesn't contain 3rd packages or production code that may help us investigate this further. Thanks!
