### ISSUE TITLE
flutter doctor: crash after installing xcode

### ISSUE THREAD

**Issue by DrGo** [flutter/flutter#15143]
## Steps to Reproduce
installed xcode from App Store. Then ran flutter doctor twice. crashed each time with the following 
error: 
```
flutter doctor


Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.


Building flutter tool...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to /Users/salah/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
➜  ~ sudo flutter doctor
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
/Users/salah/local/flutter/bin/flutter: line 75: [: !=: unary operator expected

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to /Users/salah/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## Logs
crash log flutter_01:
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.

```
#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:235)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:252)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#6      new Future.sync (dart:async/future.dart:222)
#7      CommandRunner.run (package:args/command_runner.dart:109)
#8      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#9      run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1501)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#18     main (file:///Users/salah/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.




#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:236)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:112)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/salah/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

crash log flutter_02:
`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 
You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.

```
#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:235)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:252)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#6      new Future.sync (dart:async/future.dart:222)
#7      CommandRunner.run (package:args/command_runner.dart:109)
#8      FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#9      run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1501)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#18     main (file:///Users/salah/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#19     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 
You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.


#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:236)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:112)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/salah/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
`

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by DanTup** [comment]
There has been a recent change to escaping on that shell script that I wonder if may have fixed this:

https://github.com/flutter/flutter/pull/15087

Are you still seeing the issue with the latest beta?
