### ISSUE TITLE
App crashed while running flutter example

### ISSUE THREAD

**Issue by nsreenath** [flutter/flutter#15156]
I ran `flutter/examples/layers/widgets/custom_render_box.dart` and the app crashed while playing with it.
Device is: Moto G4 Plus (Android 7.0)
I simply copy pasted the code of custom_render_box.dart on to main.dart of a helloworld app. After the crash, the app restarted with previous helloworld app instead of the custom_render_box code I was playing with.

Logcat says only this much:
```
03-05 16:00:11.737 25851-903/com.yourcompany.helloflutter A/libc: Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 903 (Thread-8)
                                                                  
	  [ 03-05 16:00:11.748   394:  394 W/         ]
	  debuggerd: handling request: pid=25851 uid=10285 gid=10285 tid=903
	  
	  
	  [ 03-05 16:00:11.867   914:  914 E/         ]
	  debuggerd: process stopped due to unexpected signal 27
	  
	  
	  [ 03-05 16:00:11.889   394:  394 W/         ]
	  debuggerd: resuming target 25851

```

**Comment by chinmaygarde** [comment]
Can you post the full logcat trace?

**Comment by nsreenath** [comment]
@chinmaygarde I got a similar error today for another app.
Here is the log from logcat:

```
03-27 00:57:03.524  3596  4229 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 4229 (Thread-2)
03-27 00:57:03.525  1223  1223 W         : debuggerd: handling request: pid=3596 uid=10073 gid=10073 tid=4229
03-27 00:57:04.065  4248  4248 E         : debuggerd: process stopped due to unexpected signal 27
03-27 00:57:04.068  1607  4249 W ActivityManager:   Force finishing activity com.sergiandreplace.flutteranimations.flutteranimations/.MainActivity
03-27 00:57:04.069  1607  1627 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
03-27 00:57:04.072  1223  1223 W         : debuggerd: resuming target 3596
03-27 00:57:04.080  1273  1273 E lowmemorykiller: Error writing /proc/3596/oom_score_adj; errno=22
03-27 00:57:04.080  1607  1623 W ActivityManager: Failed setting process group of 3596 to 1
03-27 00:57:04.083  1607  1623 W System.err: java.lang.IllegalArgumentException: Given thread 3622 does not exist
03-27 00:57:04.111  1607  1684 W InputDispatcher: channel '61b2721 com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-27 00:57:04.111  1607  1684 E InputDispatcher: channel '61b2721 com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-27 00:57:04.120  1607  2034 D GraphicsStats: Buffer count: 4
03-27 00:57:04.208  1607  1623 W System.err:    at android.os.Process.setThreadPriority(Native Method)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20514)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21013)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:272)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1222)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:172)
03-27 00:57:04.208  1607  1623 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 00:57:04.208  1607  1623 W System.err:    at android.os.Looper.loop(Looper.java:154)
03-27 00:57:04.208  1607  1623 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
03-27 00:57:04.208  1607  1623 W System.err:    at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-27 00:57:04.210  1607  1624 W art     : Long monitor contention with owner ActivityManager (1623) at void com.android.server.am.BroadcastQueue.processNextBroadcast(boolean)(BroadcastQueue.java:760) waiters=0 in void com.android.server.am.AppErrors.handleShowAppErrorUi(android.os.Message) for 127ms
03-27 00:57:04.306  1607  1607 W art     : Long monitor contention with owner ActivityManager (1623) at void com.android.server.am.BroadcastQueue.processNextBroadcast(boolean)(BroadcastQueue.java:760) waiters=1 in int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int) for 220ms
03-27 00:57:04.307  1607  2034 I ActivityManager: Process com.sergiandreplace.flutteranimations.flutteranimations (pid 3596) has died
03-27 00:57:04.307  1607  2034 D ActivityManager: cleanUpApplicationRecord -- 3596
03-27 00:57:04.608  1607  1618 W art     : Long monitor contention with owner android.display (1630) at void com.android.server.wm.WindowAnimator$1.doFrame(long)(WindowAnimator.java:144) waiters=0 in void com.android.server.wm.WindowState$DeathRecipient.binderDied() for 489ms
03-27 00:57:04.648  1607  2288 W art     : Long monitor contention with owner android.display (1630) at void com.android.server.wm.WindowAnimator$1.doFrame(long)(WindowAnimator.java:144) waiters=1 in void com.android.server.wm.Session.binderDied() for 528ms
03-27 00:57:04.672  1607  1619 W art     : Long monitor contention with owner android.display (1630) at void com.android.server.wm.WindowAnimator$1.doFrame(long)(WindowAnimator.java:144) waiters=2 in void com.android.server.wm.WindowState$DeathRecipient.binderDied() for 551ms
03-27 00:57:04.672  1607  1619 I WindowManager: WIN DEATH: Window{61b2721 u0 com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity}
03-27 00:57:04.672  1607  1619 W InputDispatcher: Attempted to unregister already unregistered input channel '61b2721 com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity (server)'
03-27 00:57:04.672  1607  1619 W WindowManager: Force-removing child win Window{babf18f u0 SurfaceView - com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity} from container Window{61b2721 u0 com.sergiandreplace.flutteranimations.flutteranimations/com.sergiandreplace.flutteranimations.flutteranimations.MainActivity}
03-27 00:57:04.675  1607  2034 W art     : Long monitor contention with owner android.display (1630) at void com.android.server.wm.WindowAnimator$1.doFrame(long)(WindowAnimator.java:144) waiters=3 in void com.android.server.wm.WindowManagerService.notifyAppRelaunchesCleared(android.os.IBinder) for 368ms
03-27 00:57:04.688  1275  1275 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-27 00:57:04.692  1607  1618 W WindowManager: Failed looking up window
03-27 00:57:04.692  1607  1618 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@401e746 does not exist
03-27 00:57:04.692  1607  1618 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
03-27 00:57:04.692  1607  1618 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
03-27 00:57:04.692  1607  1618 W WindowManager:         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
03-27 00:57:04.692  1607  1618 W WindowManager:         at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
03-27 00:57:04.692  1607  1618 I WindowManager: WIN DEATH: null
03-27 00:57:04.697  1607  3095 W art     : Long monitor contention with owner android.ui (1624) at void com.android.server.am.AppErrors.handleShowAppErrorUi(android.os.Message)(AppErrors.java:682) waiters=2 in void com.android.server.am.ActivityManagerService.finishReceiver(android.os.IBinder, int, java.lang.String, android.os.Bundle, boolean, int) for 486ms
03-27 00:57:04.700  1607  1607 W art     : Long monitor contention with owner Binder:1607_5 (2034) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1475) waiters=2 in int com.android.server.am.ActivityManagerService.broadcastIntent(android.app.IApplicationThread, android.content.Intent, java.lang.String, android.content.IIntentReceiver, int, java.lang.String, android.os.Bundle, java.lang.String[], int, android.os.Bundle, boolean, boolean, int) for 394ms
03-27 00:57:04.701  1607  1624 W art     : Long monitor contention with owner Binder:1607_5 (2034) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1475) waiters=3 in android.content.Intent com.android.server.am.ActivityManagerService.registerReceiver(android.app.IApplicationThread, java.lang.String, android.content.IIntentReceiver, android.content.IntentFilter, java.lang.String, int) for 388ms
03-27 00:57:04.706  1275  1334 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-27 00:57:04.743  1275  1980 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.750  3677  3706 D         : HostConnection::get() New Host Connection established 0xc816f140, tid 3706
03-27 00:57:04.756  3677  3706 I OpenGLRenderer: Initialized EGL, version 1.4
03-27 00:57:04.756  3677  3706 D OpenGLRenderer: Swap behavior 1
03-27 00:57:04.756  3677  3706 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-27 00:57:04.756  3677  3706 D OpenGLRenderer: Swap behavior 0
03-27 00:57:04.770  1275  1980 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.784  1275  1981 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.801  1275  1980 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.826  1275  1981 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.890  1275  1981 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.962  1607  1630 W art     : Long monitor contention with owner android.ui (1624) at int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.content.res.Configuration, android.view.Surface)(WindowManagerService.java:2850) waiters=0 in void com.android.server.wm.WindowAnimator$1.doFrame(long) for 169ms
03-27 00:57:04.965  1607  4253 D         : HostConnection::get() New Host Connection established 0x7c5583f87300, tid 4253
03-27 00:57:04.966  1275  1565 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:04.972  1607  4253 I OpenGLRenderer: Initialized EGL, version 1.4
03-27 00:57:04.972  1607  4253 D OpenGLRenderer: Swap behavior 1
03-27 00:57:04.972  1607  4253 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-27 00:57:04.972  1607  4253 D OpenGLRenderer: Swap behavior 0
03-27 00:57:05.016  1275  1565 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:05.070  1275  1565 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-27 00:57:05.572  2250  2318 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-27 00:57:05.668  3677  3677 I OptInState: There is a new client and it does not support opt-in. Dropping request.
03-27 00:57:05.747  3677  3677 I MicroDetectionWorker: Micro detection mode: [mDetectionMode: [1]].
03-27 00:57:05.779  3677  3677 I AudioController: Using mInputStreamFactoryBuilder
03-27 00:57:05.779  3677  3688 I art     : Background sticky concurrent mark sweep GC freed 9813(711KB) AllocSpace objects, 4(80KB) LOS objects, 12% free, 9MB/10MB, paused 6.594ms total 35.752ms
03-27 00:57:05.801  3677  4261 I GsaNativeCrashHandler: Loaded shared library: nativecrashreporter
03-27 00:57:05.814  3677  4261 I MicroDataManager: Created a new hotword model for:
03-27 00:57:05.814  3677  4261 I MicroDataManager: # com.google.android.apps.gsa.speech.microdetection.g@36410d17
03-27 00:57:05.821  3677  4263 I MicroRecognitionRunner: Starting detection.
03-27 00:57:09.811  2708  4254 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
03-27 00:57:14.859  2708  4254 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
03-27 00:57:19.718  1607  1623 I ActivityManager: Waited long enough for: ServiceRecord{1825e08 u0 com.google.android.gms/.stats.service.DropBoxEntryAddedService}
03-27 00:57:19.906  2708  4254 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.

```

**Comment by zoechi** [comment]
We are sorry for not being able to coming back to this earlier. 
Is this still an issue?
