### ISSUE TITLE
[flutter_adaptive_scaffold][go_router][SelectionArea]: Assertion error on subroutes with SelectionArea and AdaptiveScaffold

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#151536]
### Steps to reproduce

Execute the code sample (tested on `web` or `macos`)

### Expected results

To not throw any error

### Actual results

```console
The following assertion was thrown during a scheduler callback:
RenderBox was not laid out: RenderFractionalTranslation#32ab0 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'
```

But nothing visually wrong.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_adaptive_scaffold/flutter_adaptive_scaffold.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
      ),
      routerConfig: GoRouter(
        initialLocation: '/subpage', // Initial location must point to the sub route.
        routes: [
          GoRoute(
            path: '/',
            routes: [
              GoRoute(path: 'subpage', builder: (context, state) => const MyHomePage(title: 'Sub page')),
            ],
            builder: (context, state) => const MyHomePage(title: 'Root page'),
          )
        ],
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    var destinations = <NavigationDestination>[
      const NavigationDestination(
        icon: Icon(Icons.list_alt),
        selectedIcon: Icon(Icons.list_alt_outlined),
        label: 'Root',
      ),
      const NavigationDestination(
        icon: Icon(Icons.widgets_outlined),
        selectedIcon: Icon(Icons.widgets),
        label: 'Subpage',
      )
    ];
    return SelectionArea(
      // SelectionArea must be activated
      child: AdaptiveScaffold(
        destinations: destinations,
        appBarBreakpoint: Breakpoints.smallAndUp,
        transitionDuration: const Duration(milliseconds: 0),
        selectedIndex: selectedIndex,
        onSelectedIndexChange: (int index) {
          GoRouter.of(context).go(['/', '/subpage'][index]);
        },
        body: (_) => const Text('A'),
        secondaryBody: (_) => const Text('B'), // secondary body must be set
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

Web:
```console
Launching lib/test_main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:56108/pmYkwM1S-38=/ws
Debug service listening on ws://127.0.0.1:56108/pmYkwM1S-38=/ws
Debug service listening on ws://127.0.0.1:56108/pmYkwM1S-38=/ws

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: file:///opt/homebrew/Caskroom/flutter/3.22.2/flutter/packages/flutter/lib/src/rendering/box.dart:2165:12
hasSize
"RenderBox was not laid out: RenderFractionalTranslation#d1f01 NEEDS-LAYOUT NEEDS-PAINT"

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3   assertFailed
packages/flutter/src/rendering/box.dart 2165:12                              get size
packages/flutter/src/rendering/proxy_box.dart 2936:29                        applyPaintTransform
packages/flutter/src/rendering/object.dart 3354:22                           getTransformTo
packages/flutter/src/rendering/paragraph.dart 2003:22                        getTransformTo
packages/flutter/src/widgets/selectable_region.dart 1925:8                   [_compareScreenOrder]
dart-sdk/lib/internal/sort.dart 69:51                                        _insertionSort
dart-sdk/lib/internal/sort.dart 58:7                                         _doSort
dart-sdk/lib/internal/sort.dart 33:5                                         sort
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 471:12           sort]
packages/flutter/src/widgets/selectable_region.dart 1824:70                  <fn>
packages/flutter/src/widgets/selectable_region.dart 1824:75                  [_flushAdditions]
packages/flutter/src/widgets/selectable_region.dart 1818:7                   [_updateSelectables]
packages/flutter/src/widgets/selectable_region.dart 1797:9                   runScheduledTask
packages/flutter/src/scheduler/binding.dart 1392:7                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1326:11                          handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1035:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:11      internalCallback
====================================================================================================
```

macOS:
```console
Launching lib/test_main.dart on macOS in debug mode...
Building macOS application...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006030-0008311802D0001C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006030-0008311802D0001C, name:My Mac }
✓ Built build/macos/Build/Products/Debug/swi_toolbox.app
[IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(66)] Using the Skia rendering backend (Metal).
Debug service listening on ws://127.0.0.1:56427/06ZpCvy9xOk=/ws
Syncing files to device macOS...

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
RenderBox was not laid out: RenderFractionalTranslation#32ab0 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2936:24)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3354:24)
#5      _SelectableFragment.getTransformTo (package:flutter/src/rendering/paragraph.dart:2003:22)
#6      MultiSelectableSelectionContainerDelegate._compareScreenOrder (package:flutter/src/widgets/selectable_region.dart:1925:9)
#7      Sort._insertionSort (dart:_internal/sort.dart:69:36)
#8      Sort._doSort (dart:_internal/sort.dart:58:7)
#9      Sort.sort (dart:_internal/sort.dart:33:5)
#10     ListBase.sort (dart:collection/list.dart:321:10)
#11     MultiSelectableSelectionContainerDelegate._flushAdditions (package:flutter/src/widgets/selectable_region.dart:1824:70)
#12     MultiSelectableSelectionContainerDelegate._updateSelectables (package:flutter/src/widgets/selectable_region.dart:1818:7)
#13     MultiSelectableSelectionContainerDelegate._scheduleSelectableUpdate.runScheduledTask (package:flutter/src/widgets/selectable_region.dart:1797:9)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
#16     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1035:9)
#17     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
2024-07-10 15:23:49.211 swi_toolbox[3194:1234378] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.6 23G5061b darwin-arm64, locale en-US)
    • Flutter version 3.22.2 on channel stable at /opt/homebrew/Caskroom/flutter/3.22.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/swi-oberhauser/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G5061b darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G5061b darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample provided above. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

  
```
[!] Flutter (Channel master, 3.24.0-1.0.pre.78, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.78 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7de634bf25 (6 hours ago), 2024-07-10 20:52:29 -0400
    • Engine revision 6534fbf3c2
    • Dart version 3.6.0 (build 3.6.0-25.0.dev)
    • DevTools version 2.37.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (5 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • Dean’s iPad (mobile)            • 00008103-000825C811E3401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by stuartmorgan** [comment]
Framework team: is it expected that a package bug could cause this error? It's not clear to me from the stack.

**Comment by chunhtai** [comment]
cc @Renzo-Olivares

**Comment by helpisdev** [comment]
I just encountered the same error using a regular `Scaffold` with `GoRouter` and `SelectionArea`. Are there any updates on this?

**Comment by Gustl22** [comment]
It may has to do with the fact, that the same scaffold is stacked on top via the navigation, and the selection_area may confuses them (?). If I wrap the `secondaryBody` within its own `SelectionArea`, it doesn't throw an error.

@helpisdev @sunenvidiado-nx @gabrielrf97 you may want to thumb up (+1) the original issue description to support pushing this issue. I think comments like this should be avoided: https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene#comments

**Comment by Gustl22** [comment]
A theory: I adapted the example to better debug the thing.
- There are two `AdaptiveScaffold` stacked on top of each other.
- Both texts `A` and `B` from the root `AdaptiveScaffold` and `subA` and `subB` from the subpage are added to the SelectionArea tree.
- The framwork complains that `RenderFractionalTranslation#40372 NEEDS-LAYOUT NEEDS-PAINT`, so these are the two selectable Texts from the root Scaffold: `A` and `B`.
- ASSUMPTION (no proof): The `AdaptiveScaffold` uses [_SlotIds](https://github.com/flutter/packages/blob/ee43c7eb37ebf3e0b8911814db5513f0fa4a417e/packages/flutter_adaptive_scaffold/lib/src/adaptive_layout.dart#L16) to layout the childs. I think these slot ids are not unique, if there are multiple `AdaptiveScaffold`s involved, so it just layouts the wrong [child](https://github.com/flutter/packages/blob/ee43c7eb37ebf3e0b8911814db5513f0fa4a417e/packages/flutter_adaptive_scaffold/lib/src/adaptive_layout.dart#L514) `Text` by chance. I can't really tell, why this is only the case, when both, the secondaryBody and the body are present.

@Renzo-Olivares Can this be correct?

**Comment by Gustl22** [comment]
I could reproduce it without `flutter_adaptive_scaffold`. The problem is, that the `SelectableArea` tries to [compare](https://github.com/flutter/flutter/blob/4f8ab5bfe266394a747b86a0a5a8511bd86119df/packages/flutter/lib/src/widgets/selectable_region.dart#L2104) the selectables (if there are more than 2), and then cannot determine the size of the ones of the `root`, because they weren't even layouted.

1. So the selectables of the root scaffold shouldn't even be added to the seletables tree in the first place? or does this conflict / not work, when navigating back to the root page?
1. Alternatively it should be made sure, that the underlying navigation is rendered before the selection is compared.
1. Or can we somehow circumvent that it can compare these selectables, without being layouted / rendered?

Cc: @Renzo-Olivares

**Comment by annd22** [comment]
Any update on this, this can make application on Windows crashed

**Comment by Disregard-Therest** [comment]
Hello, I have the same bug when I have 2 routes with same scaffold and SelectionArea around the body
If I keep only one router on Navigator everything is fine.

**Comment by Albert0sans** [comment]
any updates?

**Comment by Gustl22** [comment]
I am on it, at least I try

**Comment by chunhtai** [comment]
this is most likely a framework issue

**Comment by Gustl22** [comment]
For now it should be solvable by wrapping the inner shell Routes builder with a `Material` class. This avoids registering the `InkDecoration` (which is used in many widgets) at the outer Scaffold (which is a `Material`).

I opened #147452 to address this.

**Comment by franboladoruiz** [comment]
I started getting this issue after upgrading from Flutter v3.27.3 to v3.29.2. I didn't change anything in the affected screen, but it does use GoRouter, AdaptiveScaffold and SelectionArea.

<details>

<summary>Stacktrace</summary>

```dart
E/flutter (22864): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2251 pos 12: 'hasSize': RenderBox was not laid out: RenderTransform#55b81 NEEDS-LAYOUT NEEDS-PAINT
E/flutter (22864): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:63:4)
E/flutter (22864): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:45:5)
E/flutter (22864): #2      RenderBox.size (package:flutter/src/rendering/box.dart:2251:12)
E/flutter (22864): #3      RenderTransform._effectiveTransform (package:flutter/src/rendering/proxy_box.dart:2531:49)
E/flutter (22864): #4      RenderTransform.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2615:24)
E/flutter (22864): #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3520:25)
E/flutter (22864): #6      _SelectionContainerState.getTransformTo (package:flutter/src/widgets/selection_container.dart:208:40)
E/flutter (22864): #7      MultiSelectableSelectionContainerDelegate._compareScreenOrder (package:flutter/src/widgets/selectable_region.dart:2545:52)
E/flutter (22864): #8      Sort._insertionSort (dart:_internal/sort.dart:77:36)
E/flutter (22864): #9      Sort._doSort (dart:_internal/sort.dart:62:7)
E/flutter (22864): #10     Sort.sort (dart:_internal/sort.dart:33:5)
E/flutter (22864): #11     ListBase.sort (dart:collection/list.dart:321:10)
E/flutter (22864): #12     MultiSelectableSelectionContainerDelegate._flushAdditions (package:flutter/src/widgets/selectable_region.dart:2442:70)
E/flutter (22864): #13     MultiSelectableSelectionContainerDelegate._updateSelectables (package:flutter/src/widgets/selectable_region.dart:2436:7)
E/flutter (22864): #14     MultiSelectableSelectionContainerDelegate._scheduleSelectableUpdate.runScheduledTask (package:flutter/src/widgets/selectable_region.dart:2415:9)
E/flutter (22864): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (22864): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

</details>

**Comment by ValentinVignal** [comment]
> For now it should be solvable by wrapping the inner shell Routes builder with a `Material` class. This avoids registering the `InkDecoration` (which is used in many widgets) at the outer Scaffold (which is a `Material`).
> 
> I opened [#158918](https://github.com/flutter/flutter/pull/158918) to address this.

@Gustl22 I didn't understand what is the suggested work around. 

In the code sample you have:

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final router = GoRouter(
      // Default to the nested location
      // Or for a more realistic use-case, navigate to the url /a/b on the web
      initialLocation: '/root/sub',
      routes: [
        GoRoute(
          path: '/root',
          builder: (_, __) {
            // With selection area here, error will occur
            return const SelectionArea(
              child: Column(
                children: [
                  // Must be at least two selectable texts
                  Text('rootA'),
                  Text('rootB'),
                ],
              ),
            );
          },
          routes: [
            GoRoute(
              path: 'sub',
              builder: (_, __) {
                return const SelectionArea(
                  child: Column(
                    children: [
                      // Must be at least two selectable texts
                      Text('subA'),
                      Text('subB'),
                    ],
                  ),
                );
              },
            ),
          ],
        ),
      ],
    );
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}
```

</details>

What should be wrapped with a `Material` ?

**Comment by Gustl22** [comment]
> What should be wrapped with a Material ?

Sorry for the confusion, I kind of mixed up the tickets and also thought this one has the same source of failure than the one with a [StatefulShellRoute](https://github.com/flutter/flutter/issues/147452#issuecomment-2764738536). I think the fix can be  the same but not the example. So in the case of this ticket, I couldn't find a workaround (yet).

But here's a more basic reproduction sample:

<details>
  <summary>Code</summary>
  
```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Overlay].

void main() {
  runApp(const OverlayApp());
}

class OverlayApp extends StatelessWidget {
  const OverlayApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: OverlayExample());
  }
}

class OverlayExample extends StatefulWidget {
  const OverlayExample({super.key});

  @override
  State<OverlayExample> createState() => _OverlayExampleState();
}

class _OverlayExampleState extends State<OverlayExample> {
  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Overlay(
        initialEntries: [
          OverlayEntry(
            builder: (BuildContext context) {
              return SelectionArea(
                child: Column(
                  children: [
                    // Must be at least two selectable texts
                    Text('rootA'),
                    Text('rootB'),
                  ],
                ),
              );
            },
            opaque: true,
            canSizeOverlay: true,
            maintainState: true,
          ),
          OverlayEntry(
            builder: (BuildContext context) {
              return Text('subA');
            },
            opaque: true,
            canSizeOverlay: true,
            maintainState: true,
          ),
        ],
      ),
    );
  }
}
```

</details>

**Comment by franboladoruiz** [comment]
I can confirm that this issue is still present in Flutter 3.32.1 and that I have not yet found a workaround either.

**Comment by andreBalh** [comment]
Same here, the issue still exists in flutter `3.35.4`

**Comment by annd22** [comment]
I'm experiencing the same issue in Flutter 3.35.4. The error seems to have started right after we converted our project to GoRouter.

**Comment by davidmigloz** [comment]
I've put together a minimal repro that crashes reliably:

**Repo:** https://github.com/davidmigloz/flutter_selection_crash
**Live demo:** https://davidmigloz.github.io/flutter_selection_crash

Three approaches, each hitting a different frame inside `_compareScreenOrder`:
- **A:** `_getBoundingBox` → `SelectionContainerState.boundingBoxes` → `paintBounds` → `size`
- **B:** `_SelectableTextContainerDelegate._compareScreenOrder` → `_SelectableFragment.boundingBoxes` → `getBoxesForSelection` (proves the `text.dart` delegate is also vulnerable)
- **C:** `getTransformTo` → `RenderFractionalTranslation.applyPaintTransform` → `size`

All three crash immediately on page load.

#### Root cause

`_RenderTheater` intentionally skips laying out non-topmost `OverlayEntry` children (performance optimization). But the skipped entries' `SelectionContainerDelegate` keeps processing registered selectables whose `RenderBox`es have no size. When `_flushAdditions` runs the merge-sort via `compareOrder`, `_compareScreenOrder` accesses `paintBounds`/`getTransformTo`/`getBoxesForSelection` on those unlaid-out RenderBoxes → `StateError`.

#### Production workaround

We use a route-aware `SelectionArea` toggle: when the route is current, child is wrapped in `SelectionArea`; when another route covers it, child is wrapped in `SelectionContainer.disabled` (selectables deregister before the route goes offstage). Uses `ModalRoute.of(context)?.isCurrent` + `GlobalKey`/`KeyedSubtree` to preserve state. Routes stay opaque, no visual overlap.

This is the same `SelectionContainer.disabled` pattern from my [go_router PR #11062](https://github.com/flutter/packages/pull/11062), where @Renzo-Olivares [suggested](https://github.com/flutter/packages/pull/11062#pullrequestreview-3893563878) to move the fix to the framework:

> "I think the fix for this issue should probably live in the framework that way we can fix the root issue. [...] Generally any route we are making offstage/not the current route we should wrap with a `SelectionContainer.disabled` similar to how you've done in this pull request."

#### Proposed framework fix

Apply the same pattern at `_ModalScopeState.build()` in `packages/flutter/lib/src/widgets/routes.dart`: wrap route content in `SelectionContainer.disabled` when the route is not current.

I'm preparing a framework PR for this. 

#### Prior art

- PR #157996 by @Gustl22 — self-closed incomplete draft (same direction)
- PR #158918 by @Gustl22 — diagnostic draft, explicitly flagged the `SelectionArea` case as needing deeper understanding
- My go_router PR: [flutter/packages#11062](https://github.com/flutter/packages/pull/11062) (open, implements the workaround at the package level)

**Comment by davidmigloz** [comment]
Quick follow-up: the framework PR is up: https://github.com/flutter/flutter/pull/184900.

The "Proposed framework fix" I sketched above didn't work out. Wrapping non-current route content in `SelectionContainer.disabled` at `_ModalScopeState.build()` can't reach selectables inside nested `SelectionArea` / `SelectableRegion` subtrees: those widgets install their own `SelectionContainer(registrar: this, ...)` inside the route (`selectable_region.dart:1944`) that shadows the disabled outer scope, so the route-level wrapper has no effect on the code path that actually crashes.

The PR instead adds a surgical try/catch guard in both `_compareScreenOrder` overrides (`selectable_region.dart` and `text.dart`), catching `StateError` / `AssertionError` thrown from unlaid-out `RenderBox`es and returning `0`. It's a crash guard at sort time rather than a structural fix, the dead-zone behavior described in #182573 is unchanged, but it eliminates the crash across all three repro approaches (A / B / C) in https://github.com/davidmigloz/flutter_selection_crash. Full rationale, red/green test coverage, and the long-term structural-fix direction are in the PR description.
