### ISSUE TITLE
Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\fling\build, but the tool couldn't find it.

### ISSUE THREAD

**Issue by fling-project** [flutter/flutter#151645]
### Steps to reproduce

so when i use flutter run OR flutter build apk command it is showing this error
D:\fling> flutter build apk

Running Gradle task 'assembleRelease'...                            5.7s
Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\fling\build, but the tool couldn't
find it.

### Actual results

```
  +21 ms] Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\fling\build, but the tool
couldn't
           find it.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:1125:3)
           #2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:574:9)
           <asynchronous suspension>
           #3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:223:5)
           <asynchronous suspension>
           #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:140:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
```

### Logs

<details open>
<summary>Logs</summary>

```console

  +21 ms] Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\fling\build, but the tool
couldn't
           find it.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:1125:3)
           #2      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:574:9)
           <asynchronous suspension>
           #3      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:223:5)
           <asynchronous suspension>
           #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:140:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

PS D:\fling> flutter doctor                      
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.90.2)
[√] Connected device (4 available)
[√] Network resources



```

</details>

**Comment by darshankawar** [comment]
@fling-project 
I was able to build the apk properly on a sample app without the reported error. 
In your case, does it occur everytime you try to build apk ? 
If you create a new Flutter project and build apk for it, does it throw the same error ? If not, it could be specific to your code project for which can you provide app level and project level build.gradle ?

**Comment by fling-project** [comment]
yes, here is the app level and project level build apk file

project level build file

buildscript {
    ext.kotlin_version = '2.0.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

app level build file

plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    namespace = "com.example.fling"
    compileSdk = 34  // Latest compile SDK version
    ndkVersion "26.3.11579264"  // Specify the required NDK version

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17  // Updated for Java 17
        targetCompatibility = JavaVersion.VERSION_17  // Updated for Java 17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId = "com.example.fling"
        minSdk = 23  // Updated min SDK version
        targetSdk = 34  // Latest target SDK version
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.debug
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "${variant.buildType.name}-${variant.versionName}.apk"
                }
            }
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"  // Latest Kotlin version
    implementation 'androidx.appcompat:appcompat:1.6.1'  // Latest appcompat version
    implementation 'androidx.core:core-ktx:1.8.0'  // Latest core-ktx version
}

**Comment by darshankawar** [comment]
I have below that you can try and see if it helps in your case or not:

project level:

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```


app level:

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    namespace = "com.example.new_test"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.new_test"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}
```

**Comment by cantuccis** [comment]
I was experiencing the same issue. Got fixed after switching to latest version in beta channel.
