### ISSUE TITLE
FlutterFire FirebaseAnimatedList reference fails when using dynamic query

### ISSUE THREAD

**Issue by WolfgangSenff** [flutter/flutter#15160]
This occurred when working on the Codelab for adding Firebase to the Friendlychat Flutter app. The only fundamental difference that I've made is I wanted certain messages to go to the logged-in user only. I have a separate FirebaseAnimatedList for them, with a separate reference. The only difference in my query is:

`query: rootDbRef.child(uid),`

Conversely, the place to which I'm pushing my messages is:
` rootDbRef.child(uid).push().set(`

rootDbRef looks like:
`final rootDbRef = FirebaseDatabase.instance.reference().child('root').child('users');` (yes, I know you shouldn't need this, but I have multiple databases in one, so 'root' is just a temporary thing here while I test)

With these as the values, the app fails to find the children inside the LinkedHashMap and always returns null, no matter what the values are. What's essentially happening is that it returns the parent of the query, so all the children at once as a list, rather than each individual child. This makes it so when you're building the individual children, you get back the entire list, and don't have an index or a key to look up in order to figure out which child you should currently be building. I'll be searching through the framework code today to find where this might be the issue, or where I might have misunderstood how to write it and let you know more later. I can't seem to take a picture of the exact popup showing what the snapshot looks like, because it goes away when I try to screenshot it, but I can say when I change everything to just be a reference that doesn't involve the user's id (or anything dynamic), it works correctly. I think it must be a parsing bug in the queries, but we'll see.

The following log is from running flutter run, attempting to parse what amounts to a null DateTime (it's not null in my db).

Launching lib/main.dart on Pixel XL in debug mode...
Initializing gradle...                                1.1s
Resolving dependencies...                             0.8s
Running 'gradlew assembleDebug'...                        
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_auth' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':google_sign_in' is deprecated. Use 'implementation' instead.
Built build/app/outputs/apk/debug/app-debug.apk (27.6MB).
Installing build/app/outputs/apk/app.apk...           5.5s
I/FlutterActivityDelegate( 7461): onResume setting current activity to this
Syncing files to device Pixel XL...                       
I/DynamiteModule( 7461): Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
I/DynamiteModule( 7461): Selected remote version of com.google.android.gms.firebase_database, version >= 6
W/zygote64( 7461): Unsupported class loader
D/NetworkSecurityConfig( 7461): No Network Security Config specified, using platform default
I/zygote64( 7461): Do partial code cache collection, code=30KB, data=21KB
I/zygote64( 7461): After code cache collection, code=28KB, data=20KB
I/zygote64( 7461): Increasing code cache capacity to 128KB
I/flutter ( 7461): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7461): The following ArgumentError was thrown building ChatMessage(dirty):
I/flutter ( 7461): Invalid argument(s)
I/flutter ( 7461): 
I/flutter ( 7461): When the exception was thrown, this was the stack:
I/flutter ( 7461): #0      _RegExp.firstMatch (dart:core-patch/dart:core/regexp_patch.dart:191)
I/flutter ( 7461): #1      DateTime.parse (dart:core/date_time.dart:342)
...

Results of flutter analyze - forgive me, I'm a C# addict.

Analyzing ...
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:46:16 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:76:11 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:115:10 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:196:8 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:203:16 • non_constant_identifier_names
  lint • Name non-constant identifiers using lowerCamelCase at lib/main.dart:215:16 • non_constant_identifier_names
6 issues found.
(Ran in 5.0s)

No issues found with flutter doctor -v.

**Comment by WolfgangSenff** [comment]
Okay, I've figured out what was wrong with my code. Essentially, EnsureLoggedIn() isn't called until you actually submit a value. It needs to be called when the app starts up so that the UID exists when the stuff is pulled down. What was happening was it was missing the UID because it was empty, so considered it to be not an extra step down the reference.
