### ISSUE TITLE
CameraX doesn't release resources (DeviceOrientation)

### ISSUE THREAD

**Issue by arsenioo** [flutter/flutter#151715]
### What package does this bug report belong to?

camera/CameraX

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  camera:
    dependency: "direct main"
    description:
      name: camera
      sha256: "2170a943dcb67be2af2c6bcda8775e74b41d4c02d6a4eb10bdc832ee185c4eea"
      url: "https://pub.dev"
    source: hosted
    version: "0.11.0+1"
  camera_android_camerax:
    dependency: transitive
    description:
      name: camera_android_camerax
      sha256: "7c03940cb8c92eb5b184952674a07cc4a73c6ba2b3568aad70255ad4cb913660"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.7+1"
  camera_avfoundation:
    dependency: transitive
    description:
      name: camera_avfoundation
      sha256: "95c2f40b4d06cdb0fd2ad893c762d1f2c931a5e370793ec34c939eb4fcbf96bb"
      url: "https://pub.dev"
    source: hosted
    version: "0.9.17"
  camera_platform_interface:
    dependency: transitive
    description:
      name: camera_platform_interface
      sha256: b3ede1f171532e0d83111fe0980b46d17f1aa9788a07a2fbed07366bbdbb9061
      url: "https://pub.dev"
    source: hosted
    version: "2.8.0"
  camera_web:
    dependency: transitive
    description:
      name: camera_web
      sha256: b9235ec0a2ce949daec546f1f3d86f05c3921ed31c7d9ab6b7c03214d152fc2d
      url: "https://pub.dev"
    source: hosted
    version: "0.3.4"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  cross_file:
    dependency: transitive
    description:
      name: cross_file
      sha256: "55d7b444feb71301ef6b8838dbc1ae02e63dd48c8773f3810ff53bb1e2945b32"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.4+1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      sha256: ba631d1c7f7bef6b729a622b7b752645a2d076dba9976925b8f25725a30e1ee6
      url: "https://pub.dev"
    source: hosted
    version: "1.0.8"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: "3f41d009ba7172d5ff9be5f6e6e6abb4300e263aab8866d2a0842ed2a70f8f0c"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      sha256: c6b0b4c05c458e1c01ad9bcc14041dd7b1f6783d487be4386f793f47a8a4d03e
      url: "https://pub.dev"
    source: hosted
    version: "2.0.20"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  leak_tracker:
    dependency: transitive
    description:
      name: leak_tracker
      sha256: "7f0df31977cb2c0b88585095d168e689669a2cc9b97c309665e3386f3e9d341a"
      url: "https://pub.dev"
    source: hosted
    version: "10.0.4"
  leak_tracker_flutter_testing:
    dependency: transitive
    description:
      name: leak_tracker_flutter_testing
      sha256: "06e98f569d004c1315b991ded39924b21af84cf14cc94791b8aea337d25b57f8"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.3"
  leak_tracker_testing:
    dependency: transitive
    description:
      name: leak_tracker_testing
      sha256: "6ba465d5d76e67ddf503e1161d1f4a6bc42306f9d66ca1e8f079a47290fb06d3"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.1"
  lints:
    dependency: transitive
    description:
      name: lints
      sha256: "976c774dd944a42e83e2467f4cc670daef7eed6295b10b36ae8c85bcbf828235"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: d2323aa2060500f906aa31a895b4030b6da3ebdcc5619d14ce1aada65cd161cb
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16+1"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "0e0a020085b65b6083975e499759762399b4475f766c21668c4ecca34ea74e5a"
      url: "https://pub.dev"
    source: hosted
    version: "0.8.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "7687075e408b093f36e6bbf6c91878cc0d4cd10f409506f7bc996f68220b9136"
      url: "https://pub.dev"
    source: hosted
    version: "1.12.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "087ce49c3f0dc39180befefc60fdb4acd8f8620e5682fe2476afd0b3688bb4af"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.0"
  permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      sha256: "18bf33f7fefbd812f37e72091a15575e72d5318854877e0e4035a24ac1113ecb"
      url: "https://pub.dev"
    source: hosted
    version: "11.3.1"
  permission_handler_android:
    dependency: transitive
    description:
      name: permission_handler_android
      sha256: b29a799ca03be9f999aa6c39f7de5209482d638e6f857f6b93b0875c618b7e54
      url: "https://pub.dev"
    source: hosted
    version: "12.0.7"
  permission_handler_apple:
    dependency: transitive
    description:
      name: permission_handler_apple
      sha256: e6f6d73b12438ef13e648c4ae56bd106ec60d17e90a59c4545db6781229082a0
      url: "https://pub.dev"
    source: hosted
    version: "9.4.5"
  permission_handler_html:
    dependency: transitive
    description:
      name: permission_handler_html
      sha256: "54bf176b90f6eddd4ece307e2c06cf977fb3973719c35a93b85cc7093eb6070d"
      url: "https://pub.dev"
    source: hosted
    version: "0.1.1"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      sha256: "48d4fcf201a1dad93ee869ab0d4101d084f49136ec82a8a06ed9cfeacab9fd20"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.1"
  permission_handler_windows:
    dependency: transitive
    description:
      name: permission_handler_windows
      sha256: "1a790728016f79a41216d88672dbc5df30e686e811ad4e698bfc51f76ad91f1e"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      sha256: "4820fbfdb9478b1ebae27888254d445073732dae3d6ea81f0b7e06d5dedc3f02"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.8"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: "73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
      url: "https://pub.dev"
    source: hosted
    version: "1.11.1"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7
      url: "https://pub.dev"
    source: hosted
    version: "2.1.2"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      sha256: "14a00e794c7c11aa145a170587321aedce29769c08d7f58b1d141da75e3b1c6f"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "9955ae474176f7ac8ee4e989dadfb411a58c30415bcfb648fa04b2b8a03afa7f"
      url: "https://pub.dev"
    source: hosted
    version: "0.7.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: "3923c89304b715fb1eb6423f017651664a03bf5f4b29983627c4da791f74a4ec"
      url: "https://pub.dev"
    source: hosted
    version: "14.2.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "97da13628db363c635202ad97068d47c5b8aa555808e7a9411963c533b449b27"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.1"
sdks:
  dart: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.0"

```

</details>

### Steps to reproduce

1. Run the sample provided
2. Accept (grant) permissions
3. See how camera preview works
4. Go back (back button or gesture) to initiate controller!.dispose() to release camera resources

### Expected results

No exceptions or warnings

### Actual results

See in logs how exception fires in Android Platform code:
```
Activity com.example.cameratest.MainActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b0735 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 5515): android.app.IntentReceiverLeaked: Activity com.example.cameratest.MainActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b0735 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 5515): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1847)
E/ActivityThread( 5515): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1620)
E/ActivityThread( 5515): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1798)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:permission_handler/permission_handler.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final camera = (await availableCameras()).first;
  runApp(MyApp(camera: camera));
}

class MyApp extends StatelessWidget {
  final CameraDescription camera;

  const MyApp({super.key, required this.camera});

  @override
  Widget build(BuildContext context) => MaterialApp(
      home: CameraScreen(camera: camera),
    );
}

class CameraScreen extends StatefulWidget {
  final CameraDescription camera;

  const CameraScreen({super.key, required this.camera});

  @override
  CameraScreenState createState() => CameraScreenState();
}

class CameraScreenState extends State<CameraScreen> {
  CameraController? _controller;

  @override
  void initState() {
    print("----- CameraScreenState.initState()");
    super.initState();
    _initCamera();
  }

  @override
  void dispose() {
    print("----- CameraScreenState.dispose()");
    _controller?.dispose();
    super.dispose();
  }

  Future<void> _initCamera() async {
    print("----- _initCamera()");
    if (await Permission.camera.request().isGranted) {
      _controller = CameraController(
        widget.camera,
        ResolutionPreset.low,
      );
      await _controller!.initialize();
      setState(() {}); // Trigger a rebuild after initialization
    } else {
      // Handle no permission
    }
  }

  Widget _buildCameraPreview() => (_controller?.value.isInitialized ?? false) ?
      CameraPreview(_controller!) :
      const Center(child: CircularProgressIndicator());

  Future<bool> _onPop() async {
    print("----- _onPop: entered");
    await _controller?.dispose();
    print("----- _onPop: after dispose");
    return true;
  }

  @override
  Widget build(BuildContext context) => WillPopScope(
      onWillPop: _onPop,
      child: Scaffold(
        appBar: AppBar(title: const Text('Camera')),
        body: _buildCameraPreview(),
      ),
    );
}

```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter ( 5515): ----- _onPop: entered
D/ImageCapture( 5515): clearPipeline
D/DeferrableSurface( 5515): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@84b1e2c
D/DeferrableSurface( 5515): surface closed,  useCount=1 closed=true androidx.camera.core.impl.ImmediateSurface@461f118
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Use cases [androidx.camera.core.Preview-a2ec5906-5cc3-4a34-8bab-dcef5b00f6df78779881, androidx.camera.core.ImageCapture-fb068b64-e325-49ae-871f-fbe19c5000d163553948, androidx.camera.core.ImageAnalysis-fb2bb5a8-2e45-4f4d-8472-0ad9029b697e214718330] now DETACHED for camera
D/UseCaseAttachState( 5515): All use case: [] for camera: 0
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Resetting Capture Session
I/flutter ( 5515): ----- _onPop: after dispose
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Releasing session in state OPENED
D/UseCaseAttachState( 5515): Active and attached use case: [] for camera: 0
D/UseCaseAttachState( 5515): Active and attached use case: [] for camera: 0
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Closing camera.
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Transitioning camera internal state: OPENED --> CLOSING
D/CameraStateRegistry( 5515): Recalculating open cameras:
D/CameraStateRegistry( 5515): Camera                                       State                 
D/CameraStateRegistry( 5515): -------------------------------------------------------------------
D/CameraStateRegistry( 5515): Camera@7b051f8[id=1]                         UNKNOWN               
D/CameraStateRegistry( 5515): Camera@2e5dd99[id=0]                         CLOSING               
D/CameraStateRegistry( 5515): -------------------------------------------------------------------
D/CameraStateRegistry( 5515): Open count: 1 (Max allowed: 1)
D/CameraStateMachine( 5515): New public camera state CameraState{type=CLOSING, error=null} from CLOSING and null
D/CameraStateMachine( 5515): Publishing new public camera state CameraState{type=CLOSING, error=null}
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Resetting Capture Session
E/BufferQueueProducer( 5515): [SurfaceTexture-0-5515-0](id:158b00000002,api:4,p:831,c:5515) queueBuffer: BufferQueue has been abandoned
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Releasing session in state CLOSING
D/CaptureSession( 5515): onSessionFinished()
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} CameraDevice.onClosed()
D/BufferQueueConsumer( 5515): [ImageReader-320x240f21m4-5515-0](id:158b00000003,api:0,p:-1,c:5515) disconnect
D/BufferQueueConsumer( 5515): [ImageReader-320x240f23m4-5515-1](id:158b00000004,api:0,p:-1,c:5515) disconnect
D/Camera2CameraImpl( 5515): {Camera@2e5dd99[id=0]} Transitioning camera internal state: CLOSING --> INITIALIZED
D/CameraStateRegistry( 5515): Recalculating open cameras:
D/CameraStateRegistry( 5515): Camera                                       State                 
D/CameraStateRegistry( 5515): -------------------------------------------------------------------
D/CameraStateRegistry( 5515): Camera@7b051f8[id=1]                         UNKNOWN               
D/CameraStateRegistry( 5515): Camera@2e5dd99[id=0]                         CLOSED                
D/CameraStateRegistry( 5515): -------------------------------------------------------------------
D/CameraStateRegistry( 5515): Open count: 0 (Max allowed: 1)
D/CameraStateMachine( 5515): New public camera state CameraState{type=CLOSED, error=null} from CLOSED and null
D/CameraStateMachine( 5515): Publishing new public camera state CameraState{type=CLOSED, error=null}
D/BLASTBufferQueue( 5515): [SurfaceView[com.example.cameratest/com.example.cameratest.MainActivity]#1](f:0,a:1) destructor()
D/BufferQueueConsumer( 5515): [SurfaceView[com.example.cameratest/com.example.cameratest.MainActivity]#1(BLAST Consumer)1](id:158b00000001,api:0,p:-1,c:5515) disconnect
D/BLASTBufferQueue( 5515): [VRI[MainActivity]#0](f:0,a:1) destructor()
E/BLASTBufferQueue( 5515): [VRI[MainActivity]#0](f:0,a:1) Applying pending transactions on dtor 1
D/BufferQueueConsumer( 5515): [VRI[MainActivity]#0(BLAST Consumer)0](id:158b00000000,api:0,p:-1,c:5515) disconnect
D/InputTransport( 5515): Destroy ARC handle: 0xb400006e8a66e5c0
E/ActivityThread( 5515): Activity com.example.cameratest.MainActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b0735 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 5515): android.app.IntentReceiverLeaked: Activity com.example.cameratest.MainActivity has leaked IntentReceiver io.flutter.plugins.camerax.DeviceOrientationManager$1@b0735 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 5515): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1847)
E/ActivityThread( 5515): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1620)
E/ActivityThread( 5515): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1798)
E/ActivityThread( 5515): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1750)
E/ActivityThread( 5515): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1738)
E/ActivityThread( 5515): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:747)
E/ActivityThread( 5515): 	at io.flutter.plugins.camerax.DeviceOrientationManager.start(DeviceOrientationManager.java:73)
E/ActivityThread( 5515): 	at io.flutter.plugins.camerax.DeviceOrientationManagerHostApiImpl.startListeningForDeviceOrientationChange(DeviceOrientationManagerHostApiImpl.java:65)
E/ActivityThread( 5515): 	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi$-CC.lambda$setup$0(GeneratedCameraXLibrary.java:1606)
E/ActivityThread( 5515): 	at io.flutter.plugins.camerax.GeneratedCameraXLibrary$DeviceOrientationManagerHostApi$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
E/ActivityThread( 5515): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
E/ActivityThread( 5515): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/ActivityThread( 5515): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/ActivityThread( 5515): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/ActivityThread( 5515): 	at android.os.Handler.handleCallback(Handler.java:942)
E/ActivityThread( 5515): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ActivityThread( 5515): 	at android.os.Looper.loopOnce(Looper.java:201)
E/ActivityThread( 5515): 	at android.os.Looper.loop(Looper.java:288)
E/ActivityThread( 5515): 	at android.app.ActivityThread.main(ActivityThread.java:7946)
E/ActivityThread( 5515): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 5515): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
E/ActivityThread( 5515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale en-UA)
    • Flutter version 3.22.2 on channel stable at /Users/apc/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apc/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/apc/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/apc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • TB310FU (mobile) • HA1ZXJ30 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@arsenioo 
It seems to have been fixed as part of https://github.com/flutter/flutter/issues/146395 that you can check and confirm.

**Comment by arsenioo** [comment]
> @arsenioo It seems to have been fixed as part of #146395 that you can check and confirm.

I suppose this bug looks similar but it is not the same as you mentioned. I've already used latest available camerax package version 0.6.7+1 (you can see it in pubspec) and the bug is still here. Were you able to reproduce it at your side? Thank you

**Comment by darshankawar** [comment]
Have you tried with latest master version ?

**Comment by arsenioo** [comment]
> Have you tried with latest master version ?

@darshankawar,
I can confirm that with the following change to pubspec I don't see the bug mentioned above:

```
  camera:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/camera/camera
      ref: main

```

**Comment by darshankawar** [comment]
Closing as fixed.
