### ISSUE TITLE
node.isRepaintBoundary': is not true.

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#151757]
### Steps to reproduce

Every time some widget builds, but I cannot write reproducible code cause I cannot pinpoint the exact issue due to vague stack trace.

### Expected results

No failure.

### Actual results

When the exception was thrown, this was the stack:

```console
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1181:20)
object.dart:1181
#3      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1193:15)
object.dart:1193
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:604:23)
binding.dart:604
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
binding.dart:1164
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
binding.dart:1313
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#10     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#12     _drawFrame (dart:ui/hooks.dart:283:31)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
When the exception was thrown, this was the stack:
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1181:20)
object.dart:1181
#3      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1193:15)
object.dart:1193
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:604:23)
binding.dart:604
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
binding.dart:1164
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
binding.dart:1313
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#10     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#12     _drawFrame (dart:ui/hooks.dart:283:31)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.23.0-0.1.pre on channel beta at
      /Users/alexandrudochioiu/.asdf/installs/flutter/3.23.0-0.1.pre-beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (6 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/alexandrudochioiu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/alexandrudochioiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.91.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile)      • 43FE0B1E-F504-496F-8722-D4C6F396221B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS
      14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google
      Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for Alexandru’s iPhone 15. Ensure the device is unlocked
      and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with
      a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by huycozy** [comment]
With the given information (issue's title and the truncated stack trace), this may be similar to https://github.com/flutter/flutter/issues/120874 which has a clear steps to reproduce. Please check and confirm if it's also your case. Otherwise, please provide the complete stack trace. Thanks!

**Comment by AlexDochioiu** [comment]
Indeed, it is a very similar thing. Layout Builder -> Animated Switcher -> Some (Custom) Animated Widget. I'll close this ticket.
