### ISSUE TITLE
Wrong positioned Expanded hangs the UI in Release while it just show an error in Debug mode

### ISSUE THREAD

**Issue by c-lucera-pvotal** [flutter/flutter#151891]
### Steps to reproduce

Having a wrongly positioned `Expanded` or `Flexible` breaks the application in release mode, while in debug mode the Expanded widget is simply ignored and an error is logged.

from the following code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool useExpanded = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                setState(() {
                  useExpanded = !useExpanded;
                });
              },
              child: Text(useExpanded ? "Remove Expanded" : "Use Expanded"),
            ),
            Text("top"),
            SizedBox(
              child: useExpanded
                  ? Expanded(
                      child: Center(
                        child: Text('center'),
                      ),
                    )
                  : Center(
                      child: Text('center'),
                    ),
            ),
            Text("bottom"),
          ],
        ),
      ),
    );
  }
}
```

Run the application, first in debug

- `flutter run --debug`
- tap the button several times
- observe how the button changes while the layout doesn't

then in release mode

- `flutter run --release`
- tap the button several times
- observe how the button changes only the first time, then the layout breaks and the button become non responsive anymore (can be tapped but nothing changes, even the name)

Video sample, left debug mode (with debug banner) right release mode

https://github.com/user-attachments/assets/102a19a1-93e7-4a4c-98de-fed60b034bdc

### Expected results

The UI behave the same way both in `debug` and in `release` mode.
Either by breaking in both or by ignoring the wrongly positioned `Expanded` in both

### Actual results

The behaviour is different from debug and release mode, this make some issues arising only on mobile, i.e. I change a column for a Stack, everything seems as intended in debug mode, but the release mode then go completely non responsive

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool useExpanded = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                setState(() {
                  useExpanded = !useExpanded;
                });
              },
              child: Text(useExpanded ? "Remove Expanded" : "Use Expanded"),
            ),
            Text("top"),
            SizedBox(
              child: useExpanded
                  ? Expanded(
                      child: Center(
                        child: Text('center'),
                      ),
                    )
                  : Center(
                      child: Text('center'),
                    ),
            ),
            Text("bottom"),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/102a19a1-93e7-4a4c-98de-fed60b034bdc

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter run --release

flutter: type 'ParentData' is not a subtype of type 'FlexParentData' in type cast
flutter: #0      Flexible.applyParentData (package:flutter/src/widgets/basic.dart:5223)
flutter: #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6564)
flutter: #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6605)
flutter: #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6467)
flutter: #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6768)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3843)
flutter: #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #15     Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
flutter: #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #24     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #34     Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
flutter: #35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #58     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #84     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #97     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale
    en-IT)
    • Flutter version 3.22.0 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.19.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (10 weeks ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3
    • Pub download mirror
      https://pvotaltech.jfrog.io/artifactory/api/pub/pvotal-pub/

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/clucera/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 78.2.1
    • Dart plugin version 231.9414.10

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @c-lucera-pvotal, this is being tracked in https://github.com/flutter/flutter/issues/108186

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Comment by c-lucera-pvotal** [comment]
Thank you @danagbemava-nc tried to search but didn't find it, thank you!
