### ISSUE TITLE
FlexibleSpaceBar causing Null check operator used on a null value

### ISSUE THREAD

**Issue by adekmaulana** [flutter/flutter#151991]
### Steps to reproduce

1. Create CustomScrollView
2. Use 'SliverPersistentHeader'
3. Create 'SliverPersistentHeaderDelegate'
4. Use 'AppBar' in the Delegate
5. Add 'FlexibleSpaceBar'

Related: https://github.com/flutter/flutter/issues/150054

DartPad: https://dartpad.dev/?id=c217091899ee7ec8e01e4ad09ef37fe4

### Expected results

working????

### Actual results

![simulator_screenshot_4D080541-9F49-45D5-9441-11CDE9B73FA4](https://github.com/user-attachments/assets/5eecc0eb-599b-474d-92f2-67914279ea65)

### Code sample

<details open><summary>Code sample</summary>

Screen
```dart
import 'package:flutter/material.dart';

import 'package:get/get.dart';

import 'controllers/profile.controller.dart';
import 'profile.appbar.dart';

class ProfileScreen extends GetView<ProfileController> {
  const ProfileScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      extendBody: true,
      body: CustomScrollView(
        physics: const ClampingScrollPhysics(),
        slivers: [
          SliverPersistentHeader(
            delegate: ProfileAppBar(),
            pinned: true,
            floating: true,
          ),
          SliverFillRemaining(
            child: Container(color: Colors.black),
          ),
        ],
      ),
    );
  }
}

```

Delegate
```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../infrastructure/theme/app.color.dart';
import 'controllers/profile.controller.dart';

class ProfileAppBar extends SliverPersistentHeaderDelegate {
  final ProfileController controller = Get.find<ProfileController>();

  static final appBarColorTween = ColorTween(
    begin: Colors.transparent,
    end: AppColor.primaryColor,
  );
  static final appbarIconColorTween = ColorTween(
    begin: AppColor.primaryBlackColor,
    end: Colors.white,
  );

  @override
  Widget build(
    BuildContext context,
    double shrinkOffset,
    bool overlapsContent,
  ) {
    final relativeScroll = min(shrinkOffset, 300) / 300;
    return AppBar(
      automaticallyImplyLeading: false,
      backgroundColor: appBarColorTween.transform(relativeScroll),
      systemOverlayStyle:
          appBarColorTween.transform(relativeScroll) == Colors.transparent
              ? SystemUiOverlayStyle.dark
              : SystemUiOverlayStyle.light,
      flexibleSpace: FlexibleSpaceBar(),
    );
  }

  @override
  double get maxExtent => 380.0 + Get.mediaQuery.viewPadding.top;

  @override
  double get minExtent =>
      AppBar().preferredSize.height + Get.mediaQuery.viewPadding.top;

  @override
  bool shouldRebuild(ProfileAppBar oldDelegate) {
    return true;
  }

  @override
  OverScrollHeaderStretchConfiguration get stretchConfiguration =>
      OverScrollHeaderStretchConfiguration(
        stretchTriggerOffset: maxExtent,
      );
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building LayoutBuilder:
Null check operator used on a null value

The relevant error-causing widget was:
    FlexibleSpaceBar FlexibleSpaceBar:file:///Users/floothink/core/swapbook/lib/presentation/profile/profile.appbar.dart:97:22

When the exception was thrown, this was the stack:
#0      _FlexibleSpaceBarState.build.<anonymous closure> (package:flutter/src/material/flexible_space_bar.dart:226:76)
flexible_space_bar.dart:226
#1      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:139:77)
layout_builder.dart:139
#2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:19)
framework.dart:2845
#3      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:173:12)
layout_builder.dart:173
#4      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688:59)
object.dart:2688
#5      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
object.dart:1097
#6      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688:14)
object.dart:2688
#7      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:248:7)
layout_builder.dart:248
#8      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:331:5)
layout_builder.dart:331
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#12     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
layout_helper.dart:52
#13     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:574:43)
stack.dart:574
#14     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:601:12)
stack.dart:601
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#27     RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:242:12)
sliver_persistent_header.dart:242
#28     RenderSliverFloatingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:676:5)
sliver_persistent_header.dart:676
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#30     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
viewport.dart:601
#31     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
viewport.dart:1516
#32     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
viewport.dart:1427
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#46     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:333:14)
layout_builder.dart:333
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#48     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
custom_layout.dart:173
#49     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
scaffold.dart:1097
#50     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
custom_layout.dart:237
#51     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
custom_layout.dart:404
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#56     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
proxy_box.dart:1426
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
proxy_box.dart:105
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#62     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:500:13)
sliver_multi_box_adaptor.dart:500
#63     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:360:17)
sliver_fixed_extent_list.dart:360
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#65     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:121:12)
sliver_padding.dart:121
#66     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:158:11)
sliver_fill.dart:158
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
object.dart:2577
#68     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
viewport.dart:601
#69     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
viewport.dart:1516
#70     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
viewport.dart:1427
#71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
object.dart:2416
#72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
object.dart:1051
#73     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
object.dart:1064
#74     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
binding.dart:577
#75     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
binding.dart:1138
#76     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
binding.dart:443
#77     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#78     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
binding.dart:1313
#79     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#80     _invoke (dart:ui/hooks.dart:312:13)
#81     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#82     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    en-ID)
    • Flutter version 3.22.2 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.19.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    35.0.0-rc3)
    • Android SDK at /Users/floothink/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc3
    • ANDROID_HOME = /Users/floothink/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)            
    • iPhone 13 mini (mobile)         • 6924AFED-D078-48A0-8C38-9AFD0EBBD6B8 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 126.0.6478.128
    ! Error: Browsing on the local area network for Adek’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @adekmaulana 
This seems like an incomplete implementation. Typically, `AppBar` gets  `FlexibleSpaceBarSettings` from `Scaffold` to determine some basic sizing and opacity information when you provide `AppBar` in the `Scaffold.appBar` parameter. However, when you build `AppBar` in `SliverPersistentHeaderDelegate`, you need to provide the `FlexibleSpaceBarSettings` yourself.

To fix this, simply the `AppBar` with `FlexibleSpaceBar.createSettings` and provide required `currentExtent`.

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: ProfileScreen(),
    );
  }
}

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverPersistentHeader(
            delegate: ProfileAppBar(),
          ),
        ],
      ),
    );
  }
}

class ProfileAppBar extends SliverPersistentHeaderDelegate {
  @override
  Widget build(
    BuildContext context,
    double shrinkOffset,
    bool overlapsContent,
  ) {
    return FlexibleSpaceBar.createSettings(
      currentExtent: 0.0,
      child: AppBar(
        title: const Text('Profile'),
        flexibleSpace: const FlexibleSpaceBar(),
      ),
    );
  }

  @override
  double get maxExtent => 380.0;

  @override
  double get minExtent => 58.0;

  @override
  bool shouldRebuild(ProfileAppBar oldDelegate) => false;
}

```

</details>


This looks like a implementation issue rather than a bug as a result closing this issue.
