### ISSUE TITLE
WidgetTester.takeException does not catch FlutterError when tap gesture fails

### ISSUE THREAD

**Issue by fujidaiti** [flutter/flutter#151965]
### Steps to reproduce

Run the attached test code.

### Expected results

The test passes.

### Actual results

The test fails with an error message that the button tap failed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  WidgetController.hitTestWarningShouldBeFatal = true;

  testWidgets('Tapping button should fail', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: IgnorePointer(
          ignoring: true,
          child: Center(
            child: TextButton(
              onPressed: () {},
              child: const Text('button'),
            ),
          ),
        ),
      ),
    );

    await tester.tap(find.byType(TextButton), warnIfMissed: true);
    expect(tester.takeException(), isA<FlutterError>());
  });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
$ flutter test

00:01 +0: Counter increments smoke test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Finder specifies a widget that would not receive pointer events.
A call to tap() with finder "Found 1 widget with type "TextButton": [
  TextButton(dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#a7049]],
state: _ButtonStyleState#e1b6e),
]" derived an Offset (Offset(400.0, 300.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot
receive pointer events.
The finder corresponds to this RenderBox: RenderSemanticsAnnotations#6b471 relayoutBoundary=up1(creator: Semantics ← TextButton ← Center ← IgnorePointer ← Semantics ← Builder ← RepaintBoundary-[GlobalKey#02027] ← IgnorePointer ← ListenableBuilder ← SnapshotWidget ← _ZoomExitTransition ← SnapshotWidget ← ⋯, parentData: offset=Offset(345.7, 276.0) (can use size), constraints: BoxConstraints(0.0<=w<=800.0, 0.0<=h<=600.0), semantics node: SemanticsNode#4, semantic boundary, size: Size(108.6, 48.0))
The hit test result at that offset is: HitTestResult(RenderMouseRegion#91a08@Offset(400.0, 300.0),
RenderSemanticsAnnotations#3bad5@Offset(400.0, 300.0), RenderPointerListener#72e3a@Offset(400.0,
300.0), RenderSemanticsGestureHandler#f8833@Offset(400.0, 300.0),
RenderExcludeSemantics#22afc@Offset(400.0, 300.0), RenderBlockSemantics#067db@Offset(400.0, 300.0),
RenderIgnorePointer#ef082@Offset(400.0, 300.0), _RenderTheater#61a13@Offset(400.0, 300.0),
RenderAbsorbPointer#ffa04@Offset(400.0, 300.0), RenderPointerListener#73370@Offset(400.0, 300.0),
RenderSemanticsAnnotations#7d5a7@Offset(400.0, 300.0), RenderCustomPaint#02eff@Offset(400.0, 300.0),
RenderSemanticsAnnotations#84e1b@Offset(400.0, 300.0),
RenderSemanticsAnnotations#56821@Offset(400.0, 300.0), RenderTapRegionSurface#fb9c9@Offset(400.0,
300.0), RenderSemanticsAnnotations#6f61d@Offset(400.0, 300.0),
RenderSemanticsAnnotations#aa6aa@Offset(400.0, 300.0),
RenderSemanticsAnnotations#2cfca@Offset(400.0, 300.0),
HitTestEntry<HitTestTarget>#364cd(_ReusableRenderView#088e5),
HitTestEntry<HitTestTarget>#5816e(<AutomatedTestWidgetsFlutterBinding>))
If you expected this target not to be able to receive pointer events, pass "warnIfMissed: false" to
"tap()".
To make this error into a non-fatal warning, set WidgetController.hitTestWarningShouldBeFatal to
false.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1914:11)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1784:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:1032:18)
#3      main.<anonymous closure> (file:///Users/fujidaiti/Dev/issue103/test/widget_test.dart:22:18)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: Counter increments smoke test [E]
  Test failed. See exception logs above.
  The test description was: Counter increments smoke test


To run this test again: /Users/fujidaiti/.fvm/versions/stable/bin/cache/dart-sdk/bin/dart test /Users/fujidaiti/Dev/issue103/test/widget_test.dart -p vm --plain-name 'Counter increments smoke test'
00:01 +0 -1: Some tests failed.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale ja-JP)
    • Flutter version 3.22.2 on channel stable at /Users/fujidaiti/.fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fujidaiti/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.90.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • iPhone 13 (iOS 17.5) (mobile)   • 9F89D57D-2C9E-434E-B414-FD65A9182262 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         •
      macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript •
      Google Chrome 126.0.6478.182
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for 藤田大地のiPhone. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.22.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (33 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.24.0-1.0.pre.197, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.197 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0bac2be379 (76 minutes ago), 2024-07-19 00:15:26 -0400
    • Engine revision ea1e53a4e8
    • Dart version 3.6.0 (build 3.6.0-55.0.dev)
    • DevTools version 2.37.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by fujidaiti** [comment]
It seems like `WidgetTester.takeException` can not handle errors/exceptions from the testing framework. This is because that method relies on `FlutterError.onError` to obtain a recently thrown error, but `WidgetTester.tap` and other gesture simulation APIs from the testing framework don't forward their errors to `FlutterError.onError`.

Based on the above findings, I have come up with two solutions. The first one is to wrap `tester.tap(...)` in try-catch to catch errors from the testing framework and use `expect` to verify if an expected error is thrown.

```dart
Object? error;
try {
  await tester.tap(find.byType(TextButton), warnIfMissed: true);
} on Error catch (e) {
  error = e;
}

expect(error, isA<FlutterError>()); // Passes
```

Alternatively, we can create a custom tapping method like the following to align the semantics of test code with the other testing APIs from the framework.

```dart
@pragma('vm:notify-debugger-on-exception')
Future<void> customTap(WidgetTester tester, Finder finder) async {
  try {
    await tester.tap(finder, warnIfMissed: true);
  } on Error catch (error, stackTrace) {
    // Forward the error to Flutter.onError
    FlutterError.reportError(
      FlutterErrorDetails(
        exception: error,
        stack: stackTrace,
      ),
    );
  }
}

...

// And use it in test
await customTap(tester, find.byType(TextButton));
expect(tester.takeException(), isA<FlutterError>()); // Passes
```

I don't know this is a correct way to fix the issue, but works fine for my use-cases. 
If you have any thoughts or alternative approaches, I'd be interested to hear them.

thanks
