### ISSUE TITLE
Compiler unhandled exception

### ISSUE THREAD

**Issue by tlarsen7572** [flutter/flutter#15206]
## Steps to Reproduce

When I try to run my app on an iPhone7 simulator I receive an unhandled compiler exception while compiling main.dart.  I have had this happen sporadically for the last few weeks, but re-running the app usually 'fixed' whatever was happening.  I have finally gotten it to reliably crash in my current app project, which you can access [here](https://github.com/tlarsen7572/checklist).

## Logs

Here is the message I receive when trying to run the app on the simulator:

```
Running "flutter packages get" in checklist...
Launching lib/main.dart on iPhone 7 in debug mode...
compiler message: Unhandled exception:
Crash when compiling file:///Users/tlarsen/Documents/Projects/checklist/lib/main.dart,
at character offset null:
Reference to root::package:checklist/src/note.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:217)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:495)
#2      SourceLoader.computeFullProgram (package:front_end/src/fasta/source/source_loader.dart:570)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580)
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:166)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
#11     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
<asynchronous suspension>
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#13     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:207)
#14     new Future.<anonymous closure> (dart:async/future.dart:174)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#23     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#24     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      Reference.asLibrary (package:kernel/ast.dart:217)
#1      LibraryDependency.targetLibrary (package:kernel/ast.dart:495)
#2      SourceLoader.computeFullProgram (package:front_end/src/fasta/source/source_loader.dart:570)
#3      SourceLoader.computeHierarchy (package:front_end/src/fasta/source/source_loader.dart:580)
#4      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:252)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:166)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:103)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:103)
#11     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:58)
<asynchronous suspension>
#12     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#13     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:207)
#14     new Future.<anonymous closure> (dart:async/future.dart:174)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#23     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#24     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on lib/main.dart
Error launching application on iPhone 7.
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.1.9-pre.44, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.9-pre.44 at /Users/tlarsen/flutter
    • Framework revision 3ecc2a4ed2 (9 hours ago), 2018-03-06 09:24:31 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/tlarsen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • iPhone 7 • B3ECB1A2-524B-4C57-801A-C34AE83D617E • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by mraleph** [comment]
Thank you for the reproduction! 

/cc @aam @peter-ahe-google @a-siva @kmillikin

**Comment by aam** [comment]
Thanks Tom.
Any chance we can find 'draggablelistview' package somewhere?

```
╰─➤  $FH/flutter/bin/flutter run --preview-dart-2                                                                  1 ↵
Downloading package sky_engine...                            0.3s
Downloading common tools...                                  0.5s
Downloading darwin-x64 tools...                              1.8s
Downloading android-arm-profile/darwin-x64 tools...          0.2s
Downloading android-arm-release/darwin-x64 tools...          0.2s
Downloading android-arm64-profile/darwin-x64 tools...        0.3s
Downloading android-arm64-release/darwin-x64 tools...        0.3s
Downloading android-x86 tools...                             1.0s
Downloading android-x64 tools...                             1.2s
Downloading android-arm tools...                             0.5s
Downloading android-arm-profile tools...                     0.4s
Downloading android-arm-release tools...                     0.4s
Downloading android-arm64 tools...                           0.5s
Downloading android-arm64-profile tools...                   0.4s
Downloading android-arm64-release tools...                   0.4s
Downloading ios tools...                                     1.4s
Downloading ios-profile tools...                             1.3s
Downloading ios-release tools...                             1.2s
Running "flutter packages get" in checklist...                   
Could not find package draggablelistview at "/Users/tlarsen/Documents/Projects/draggablelistview".
Depended on by:
- checklist 
pub get failed (66)
```

**Comment by tlarsen7572** [comment]
Sure thing, it is available [here](https://github.com/tlarsen7572/draggablelistview) and is the same version as I have in my PC.

**Comment by aam** [comment]
Thanks @tlarsen7572 .
I know this won't help much, but I was not able to reproduce it right away:
```
╰─➤  $FH/flutter/bin/flutter run --preview-dart-2
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                       1.2s
Running Xcode clean...                                       1.4s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    4.4s
 └─Compiling, linking and signing...                 19.2s
Xcode build done                                            31.9s
Syncing files to device iPhone X...                          2.7s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Initializing hot reload...                                       
Reloaded 0 of 514 libraries in 605ms.

Performing full restart...                                       
Restarted app in 2,323ms.
```

This is on 59e7e35ada761d7822037b35d2407b4550e8baac revision of `checklist` app, b68f9b8ca57bd227e7ffeee24bb8039f2f4e62d3 of `draggablelistview` and 758b302c8ddf97382e99bc0ff3b6e39fcbe8ad98 revision of `flutter`.

Are you able to reproduce this failure after `flutter clean` too?

**Comment by tlarsen7572** [comment]
Huh.  `flutter clean` seems to have fixed it.  Sorry for not trying that before submitting an issue.

**Comment by Hixie** [comment]
If you ever see this again don't hesitate to file a bug even if `flutter clean` fixes it; we don't want to crash in any situation, even if there's bad data on disk.

**Comment by tlarsen7572** [comment]
Thanks Hixie, I will do that.

**Comment by peter-ahe-google** [comment]
I agree that we want to handle this situation more gracefully and I've filed dart-lang/sdk#32449 to track this.

**Comment by tlarsen7572** [comment]
I got an update.  When I tried running my app on the simulator this morning I got another unhandled exception with the stack trace below.  I was able to get it working by simply re-running the app (without `flutter clean`), but something is definitely 'off' with either Dart 2, Flutter, or my installation:

```
compiler message: Unhandled exception:
Reference to root::package:flutter/src/widgets/framework.dart is not bound to an AST node. A library was expected
#0      Reference.asLibrary (package:kernel/ast.dart:217)
#1      _PrivateName.library (package:kernel/ast.dart:4714)
#2      CanonicalName.getChildFromQualifiedName (package:kernel/canonical_name.dart:110)
#3      CanonicalName.getChildFromMember (package:kernel/canonical_name.dart:116)
#4      Class.computeCanonicalNames (package:kernel/ast.dart:787)
#5      Library.computeCanonicalNames (package:kernel/ast.dart:397)
#6      LimitedBinaryPrinter.computeCanonicalNames (package:kernel/binary/limited_ast_to_binary.dart:36)
#7      BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:283)
#8      FrontendCompiler.compile (package:vm/frontend_server.dart:229)
<asynchronous suspension>
#9      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29)
<asynchronous suspension>
#10     starter (package:frontend_server/server.dart:107)
<asynchronous suspension>
#11     main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on lib/main.dart
Error launching application on iPhone 7.
```

**Comment by peter-ahe-google** [comment]
OK, this is a similar problem, but the exception occurs in a different place. I've raised the priority of the Dart issue.

**Comment by jensjoha** [comment]
I have at least been able to reproduce the stack trace from https://github.com/flutter/flutter/issues/15206#issuecomment-371090563 (by checking out the old version of flutter) - upgrading flutter did indeed fix the issue.

**Comment by tlarsen7572** [comment]
I updated a few days ago and have not seen this issue re-occur.  Thanks!

**Comment by andreidiaconu** [comment]
I am seeing a similar error after upgrading flutter
```
Launching lib/main.dart on iPhone X in debug mode...
compiler message: Unhandled exception:
Crash when compiling file:///Users/andrei/FlutterProjects/gramstudio/lib/main.dart,
at character offset 5887:
lib/main.dart: Internal problem: Unhandled this in defaultTreeNode.
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#9      PropertyGet.accept (package:kernel/ast.dart:2242)
#10     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#11     PropertyGet.accept (package:kernel/ast.dart:2242)
#12     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#13     PropertyGet.accept (package:kernel/ast.dart:2242)
#14     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#15     MethodInvocation.accept (package:kernel/ast.dart:2820)
#16     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#17     MethodInvocation.accept (package:kernel/ast.dart:2820)
#18     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:169)
#19     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#20     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#21     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#22     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#23     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#24     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#25     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#26     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#27     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#28     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#29     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#30     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#31     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#32     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#33     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#34     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#35     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#36     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#37     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#38     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#39     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#40     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#41     _rootRun (dart:async/zone.dart:1126)
#42     _CustomZone.run (dart:async/zone.dart:1023)
#43     runZoned (dart:async/zone.dart:1501)
#44     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#45     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#46     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#47     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#48     new Future.<anonymous closure> (dart:async/future.dart:174)
#49     _rootRun (dart:async/zone.dart:1122)
#50     _CustomZone.run (dart:async/zone.dart:1023)
#51     _CustomZone.runGuarded (dart:async/zone.dart:925)
#52     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#53     _rootRun (dart:async/zone.dart:1126)
#54     _CustomZone.run (dart:async/zone.dart:1023)
#55     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#56     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#57     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#58     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#9      PropertyGet.accept (package:kernel/ast.dart:2242)
#10     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#11     PropertyGet.accept (package:kernel/ast.dart:2242)
#12     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#13     PropertyGet.accept (package:kernel/ast.dart:2242)
#14     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#15     MethodInvocation.accept (package:kernel/ast.dart:2820)
#16     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#17     MethodInvocation.accept (package:kernel/ast.dart:2820)
#18     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:169)
#19     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#20     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#21     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#22     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#23     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#24     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#25     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#26     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#27     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#28     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#29     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#30     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#31     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#32     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#33     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#34     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#35     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#36     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#37     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#38     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#39     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#40     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#41     _rootRun (dart:async/zone.dart:1126)
#42     _CustomZone.run (dart:async/zone.dart:1023)
#43     runZoned (dart:async/zone.dart:1501)
#44     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#45     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#46     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#47     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#48     new Future.<anonymous closure> (dart:async/future.dart:174)
#49     _rootRun (dart:async/zone.dart:1122)
#50     _CustomZone.run (dart:async/zone.dart:1023)
#51     _CustomZone.runGuarded (dart:async/zone.dart:925)
#52     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#53     _rootRun (dart:async/zone.dart:1126)
#54     _CustomZone.run (dart:async/zone.dart:1023)
#55     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#56     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#57     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#58     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on lib/main.dart
Error launching application on iPhone X.
```
Flutter doctor output:
```
[✓] Flutter (Channel dev, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-RO)
    • Flutter version 0.2.8 at /Users/andrei/Library/Android/flutter
    • Framework revision b397406561 (2 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/andrei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.0-rc1
    • ANDROID_HOME = /Users/andrei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • iPhone X • 7D6D4BE2-0A99-40ED-9ECC-472CE5E212A6 • ios • iOS 11.3 (simulator)
```

**Comment by andreidiaconu** [comment]
Related: https://github.com/flutter/flutter/issues/16242

**Comment by kmillikin** [comment]
This is a different issue, related to the Dart implementation of implicit `new` and `const`.  We've pushed out a revision that has only partial support for inferring `const` and unfortunately crashes on the cases it doesn't support.  This was unintentional :(.  The issue is tracked at https://github.com/dart-lang/sdk/issues/32737
