### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "/Users/chenguangshao/code/flutter_private/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64" in the search path. Command: /Users/chenguangshao/code/flutter_private/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64, OS error code: 0

### ISSUE THREAD

**Issue by shaochenguang** [flutter/flutter#152011]
## Command
```
flutter assemble --no-version-check -dTargetPlatform=darwin -dDarwinArchs=arm64 x86_64 -dTargetFile=/Users/chenguangshao/StudioProjects/nested_scroll_view_not_scroll/lib/main.dart -dBuildMode=release -dTreeShakeIcons=false -dDartObfuscation=false -dSplitDebugInfo= -dTrackWidgetCreation=true -dAction=build --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC85MTJlN2IwMmIzNzUwZmUyYzdmZTU5Y2M2NWEzN2NlMWQ1MzVjY2RjLw== --ExtraGenSnapshotOptions= --ExtraFrontEndOptions= --build-inputs=/Users/chenguangshao/StudioProjects/nested_scroll_view_not_scroll/macos/Flutter/ephemeral/FlutterInputs.xcfilelist --build-outputs=/Users/chenguangshao/StudioProjects/nested_scroll_view_not_scroll/macos/Flutter/ephemeral/FlutterOutputs.xcfilelist --output=/Users/chenguangshao/StudioProjects/nested_scroll_view_not_scroll/build/macos/Build/Products/Release release_macos_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "/Users/chenguangshao/code/flutter_private/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64" in the search path. Command: /Users/chenguangshao/code/flutter_private/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot_arm64, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:689:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:559:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:688:12)
#4      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:428:28)
#5      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:448:35)
#6      GenSnapshot.run (package:flutter_tools/src/base/build.dart:78:26)
#7      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:255:56)
#8      CompileMacOSFramework.build (package:flutter_tools/src/build_system/targets/macos.dart:308:31)
<asynchronous suspension>
#9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:881:9)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:819:32)
<asynchronous suspension>
#12     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:648:16)
<asynchronous suspension>
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:342:32)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1354:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
```
```
[!] Flutter (Channel [user-branch], 3.13.1-0.0.pre.1173, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.1-0.0.pre.1173 on channel [user-branch] at /Users/chenguangshao/code/flutter_private
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not the same as FL

**Comment by danagbemava-nc** [comment]
Hi @shaochenguang, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable/main to see if you still experience this issue. If you do, please provide the full verbose output of the command you run along with the updated flutter doctor -v output. 

Thank you
