### ISSUE TITLE
add firestore dependency ios not build

### ISSUE THREAD

**Issue by michaelsam94** [flutter/flutter#152081]
### StackTrace
`Comparing resolved specification to the sandbox manifest
      A BoringSSL-GRPC
      A Firebase
      A FirebaseAppCheckInterop
      A FirebaseCore
      A FirebaseCoreExtension
      A FirebaseCoreInternal
      A FirebaseFirestore
      A FirebaseFirestoreInternal
      A FirebaseSharedSwift
      A Flutter
      A GoogleUtilities
      A PromisesObjC
      A abseil
      A cloud_firestore
      A firebase_core
      A gRPC-C++
      A gRPC-Core
      A leveldb-library
      A nanopb

    Downloading dependencies

    -> Installing BoringSSL-GRPC (0.0.32)
     > Git download
     > Git download
         $ /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/yq/6kg85fpn55g0jcz_cp6bh20w0000gn/T/d20240721-75610-y4m09a --template=

    [!] Error installing BoringSSL-GRPC
    [!] /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/yq/6kg85fpn55g0jcz_cp6bh20w0000gn/T/d20240721-75610-y4m09a --template=

    Cloning into '/var/folders/yq/6kg85fpn55g0jcz_cp6bh20w0000gn/T/d20240721-75610-y4m09a'...
    error: RPC failed; curl 18 transfer closed with outstanding read data remaining
    fatal: the remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed

    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:144:in `rescue in execute_command'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:141:in `execute_command'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/base.rb:175:in `block in executable'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/git.rb:107:in `block in clone'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:175:in `block in ui_sub_action'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:174:in `ui_sub_action'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/git.rb:105:in `clone'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/git.rb:73:in `download!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/base.rb:83:in `block in download'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:159:in `block in ui_action'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:158:in `ui_action'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-downloader-2.1/lib/cocoapods-downloader/base.rb:81:in `download'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:110:in `download_source'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:77:in `download_request'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:256:in `download'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:239:in `block in uncached_pod'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:42:in `download'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:535:in `each'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:535:in `install_pod_sources'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:257:in `download_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:163:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'

Error output from CocoaPods:
↳
         Cloning into '/var/folders/yq/6kg85fpn55g0jcz_cp6bh20w0000gn/T/d20240721-75610-y4m09a'...
         error: RPC failed; curl 18 transfer closed with outstanding read data remaining
         fatal: the remote end hung up unexpectedly
         fatal: early EOF
         fatal: index-pack failed

Error running pod install
Error launching application on iPhone 15 Pro.
`
### Steps to reproduce
   * Open Android Studio.
   * Create new flutter project.
   * run command flutter pud add cloud_firestore.
   * uncomment first line in pod file and make ios version 13.0 instead of 12.0.
   * run the project on iPhone simulator.
### Minimum example repo:- https://github.com/michaelsam94/firestore_example

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. You may want to checkout https://stackoverflow.com/questions/61603856/flutter-boringssl-grpc-unable-to-install to see if any of the comments help. You may also file an issue on the flutterfire repo for assistance. 

Closing from here. 

Thank you
