### ISSUE TITLE
Flutter beta 3.24.0-0.1.pre - Test "test smoke test -- this test SHOULD FAIL": Failed

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#152119]
Part of https://github.com/flutter/flutter/issues/152118

From https://github.com/flutter/engine/pull/54003/checks?check_run_id=27656676677

Tracking first round of presubmit failures:

`Linux linux_host_engine` ([build](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_host_engine/33574/infra)) -> ci/host_debug ([build](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/2504659/infra)) -> "test: Host Tests for host_debug" ([test log](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8741995511020869457/+/u/test:_Host_Tests_for_host_debug/stdout))

```
Test "test smoke test -- this test SHOULD FAIL": Failed
In test "test smoke test -- this test SHOULD FAIL" Expect.isTrue(false) fails.
unittest-suite-wait-for-done
#1      Expect.isTrue (package:expect/expect.dart:181:5)
unittest-suite-wait-for-done
#2      isTrue (package:async_helper/async_minitest.dart:209:10)
#3      expect (package:async_helper/async_minitest.dart:72:4)
#4      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/flutter/testing/smoke_test_failure/fail_test.dart:9:5)
#5      Test.run.<anonymous closure>.<anonymous closure> (package:litetest/src/test.dart:69:21)
#6      new Future.<anonymous closure> (dart:async/future.dart:258:40)
#7      _rootRun (dart:async/zone.dart:1391:47)
#8      _CustomZone.run (dart:async/zone.dart:1301:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#11     _rootRun (dart:async/zone.dart:1399:13)
#12     _CustomZone.run (dart:async/zone.dart:1301:19)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by zanderso** [comment]
The real failure in the logs was the header filter regex test. The SHOULD FAIL test failed like it was supposed to and wasn't the cause of the build failure.

**Comment by christopherfujino** [comment]
Ahh, read this log wrong, thanks.
