### ISSUE TITLE
Hot reload fails with _CompileTimeError "Unsupported tag at this point"

### ISSUE THREAD

**Issue by Crazywater** [flutter/flutter#15214]
First of all, I'm sorry about the vague issue description, but I haven't been able to reproduce this with a minimal example.

I recently ran flutter upgrade and since then all hot reloads in my app fail with this error:

```
I/flutter ( 7777): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7777): The following _CompileTimeError was thrown building
I/flutter ( 7777): _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#1ab0f](dirty, state: _OverlayEntryState#ef3b1):
I/flutter ( 7777): error: Unsupported tag at this point: 128.
I/flutter ( 7777): 
I/flutter ( 7777): When the exception was thrown, this was the stack:
I/flutter ( 7777): #0      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:150:27)
I/flutter ( 7777): #1      ModalRoute._buildModalScope (package:flutter/src/widgets/routes.dart:1027:13)
I/flutter ( 7777): #2      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter ( 7777): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter ( 7777): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 7777): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4340:32)
I/flutter ( 7777): #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:17)
I/flutter ( 7777): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #11     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 7777): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #15     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter ( 7777): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter ( 7777): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter ( 7777): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter ( 7777): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #43     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 7777): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #47     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 7777): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #51     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 7777): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #67     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #75     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #79     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter ( 7777): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter ( 7777): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #95     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter ( 7777): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 7777): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 7777): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 7777): #99     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 7777): #100    ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 7777): #101    _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 7777): #102    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7777): #103    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7777): #104    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 7777): #106    _Timer._runTimers (dart:isolate/timer_impl.dart:382:19)
I/flutter ( 7777): #107    _Timer._handleMessage (dart:isolate/timer_impl.dart:416:5)
I/flutter ( 7777): #108    _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
I/flutter ( 7777): (elided one frame from package dart:async)
I/flutter ( 7777): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

What does that mean and how would I go about debugging it? I tried to set a breakpoint at MaterialPageRoute.buildPage, but I don't understand any of the variable contents and it doesn't seem like that's really the source of the error.

What's going on here?

Any pointers really appreciated!

## Flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.1.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 2.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[!] VS Code (version 1.20.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

I also tried switching to the beta channel, same error.

**Comment by mraleph** [comment]
128 is a `kSpecializedVariableGet`.

@jensjoha any idea?

**Comment by mraleph** [comment]
@Crazywater as a workaround you can switch Dart 2 preview off and your project should start working fine.

**Comment by jensjoha** [comment]
We currently have 14 places where we give the same error message (which is unfortunate on our part) - making it hard to figure out what exactly happened.

Would you be willing to share an example (it doesn't have to be "minimal", just any reproduction will help us a lot!).

**Comment by Crazywater** [comment]
Ah, this is related to Dart 2? Sorry! I should have specified that I'm on the bleeding edge. I've already removed all the "new"s, so I'll have to revert that before trying whether everything still works in Dart 1.

If you're interested in the full project for debugging, let me know - I could share a tarball.

**Comment by mraleph** [comment]
@Crazywater please share the code if you can - that would greatly speed up the resolution of the issue.

Please send it to `vegorov@google.com`.

**Comment by jensjoha** [comment]
Thank you for reporting this issue.
We have found and fixed an issue in regards to hot reload that will likely resolve this issue (https://github.com/dart-lang/sdk/commit/66af0113defb0842ce355a0a2089fb8ff48c42bc), though it hasn't made it into flutter yet.

**Comment by mraleph** [comment]
I am tentatively closing this as fixed.

**Comment by aam** [comment]
@Crazywater have you tried `flutter clean` in your project after flutter upgrade?
