### ISSUE TITLE
PlatformException(error, No active stream to cancel, null, null)

### ISSUE THREAD

**Issue by Aging-Developer** [flutter/flutter#152302]
### Steps to reproduce

This is an extension of issue: https://github.com/flutter/flutter/issues/91782

This is still happening, and causing issues.

Create 2 page app, 1st page has video player playing in a loop and a button (gonamed) going to page 2.. page two doesnt need to do anything.  Execute the App on a physical device (happens on Samsung as that most common).

Leave page 1 open for ten minutes with no activity, then after ten minutes navigate to page 2, that then shows the error:

![image](https://github.com/user-attachments/assets/057cc6e3-b4b4-401c-ba28-c1c46c58e48e)

The error happen more often on devices running apps deployed via store, not often in Android Studio, but sometimes.

### Expected results

For the error not to happen, the receiveBroadcastStream need to handle this issue.

### Actual results

I believe this is happening when the platform cancels/times out a stream, and that causes receiveBroadcastStream to try to cancel something that is no longer there.

### Code sample

```
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:flutter/services.dart';
import 'dart:async';

const kDefaultAspectRatio = 16 / 9;

class LoopingVideoPlayer extends StatefulWidget {
  const LoopingVideoPlayer({
    Key? key,
    this.width,
    this.height,
    required this.videoAsset,
  }) : super(key: key);

  final double? width;
  final double? height;
  final String videoAsset;

  @override
  State<LoopingVideoPlayer> createState() => _LoopingVideoPlayerState();
}

class _LoopingVideoPlayerState extends State<LoopingVideoPlayer>
    with WidgetsBindingObserver {
  VideoPlayerController? _videoPlayerController;
  ChewieController? _chewieController;
  bool _isError = false;
  String? _errorMessage;
  StreamSubscription? _videoPlayerErrorSubscription;

  double get aspectRatio =>
      _chewieController?.videoPlayerController.value.aspectRatio ??
          kDefaultAspectRatio;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _initializeVideoPlayer();
  }

  Future<void> _initializeVideoPlayer() async {
    try {
      _videoPlayerController =
          VideoPlayerController.asset('assets/videos/${widget.videoAsset}');
      await _videoPlayerController?.initialize();
      
      // Listen for errors
      _videoPlayerErrorSubscription =
          _videoPlayerController?.videoPlayerErrorStream.listen((event) {
        setState(() {
          _isError = true;
          _errorMessage = 'Video Player Error: $event';
        });
      });

      _chewieController = ChewieController(
        videoPlayerController: _videoPlayerController!,
        aspectRatio: _videoPlayerController!.value.aspectRatio,
        autoPlay: true,
        looping: true,
        showControls: false, // Hide the controls
      );
      setState(() {});
    } on PlatformException catch (e) {
      if (e.code == 'MediaCodecVideoRenderer') {
        setState(() {
          _isError = true;
          _errorMessage = 'MediaCodecVideoRenderer error: ${e.message}';
        });
      } else {
        setState(() {
          _isError = true;
          _errorMessage = 'PlatformException: ${e.message}';
        });
      }
    } catch (e) {
      setState(() {
        _isError = true;
        _errorMessage = 'Unknown error: $e';
      });
    }
  }

  @override
  void didUpdateWidget(LoopingVideoPlayer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.videoAsset != widget.videoAsset) {
      _disposeCurrentPlayer();
      _initializeVideoPlayer();
    }
  }

  @override
  void deactivate() {
    if (_videoPlayerController?.value.isInitialized == true &&
        _videoPlayerController?.value.isPlaying == true) {
      _videoPlayerController?.pause();
    }
    super.deactivate();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _videoPlayerErrorSubscription?.cancel();
    _disposeCurrentPlayer();
    super.dispose();
  }

  void _disposeCurrentPlayer() {
    _chewieController?.dispose();
    _videoPlayerController?.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (_videoPlayerController != null) {
      if (state == AppLifecycleState.inactive) {
        _videoPlayerController?.pause();
      } else if (state == AppLifecycleState.resumed) {
        _videoPlayerController?.play();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isError) {
      return Center(
        child: Text(
          _errorMessage ?? 'Error loading video',
          style: TextStyle(color: Colors.red),
        ),
      );
    }

    return AspectRatio(
      aspectRatio: aspectRatio,
      child: _chewieController != null &&
              _chewieController!.videoPlayerController.value.isInitialized
          ? Chewie(
              controller: _chewieController!,
            )
          : Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Colors.blue),
                strokeWidth: 2.0,
              ),
            ),
    );
  }
}
```

### Screenshots or Video

![image](https://github.com/user-attachments/assets/2da3cf92-1304-4712-b0c5-801656cba111)

### Logs

<details open><summary>Logs</summary>

```console
[GoRouter] getting location for name: "HomePage"
[GoRouter] going to /homePage
I/ExoPlayerImpl(23319): Init 6903b3a [ExoPlayerLib/2.18.7] [a5y17lte, SM-A520F, samsung, 26]
V/Surface (23319): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/ACodec  (23319):  [] Now uninitialized
I/ACodec  (23319): [] onAllocateComponent
I/OMXClient(23319): Treble IOmx obtained
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Loaded
V/Surface (23319): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/SurfaceUtils(23319): connecting to surface 0x78ba8c0010, reason connectToSurface
I/MediaCodec(23319): [OMX.Exynos.avc.dec] setting surface generation to 23878661
D/SurfaceUtils(23319): disconnecting from surface 0x78ba8c0010, reason connectToSurface(reconnect)
D/SurfaceUtils(23319): connecting to surface 0x78ba8c0010, reason connectToSurface(reconnect)
I/ACodec  (23319): can't find wfdsink-exynos-enable
I/ACodec  (23319): codec does not support config priority (err -1010)
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Loaded->Idle
D/SurfaceUtils(23319): set up nativeWindow 0x78ba8c0010 for 500x350, color 0x121, rotation 0, usage 0x2900
I/ACodec  (23319): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 5
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Idle->Executing
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (23319):  [] Now uninitialized
I/ACodec  (23319): [] onAllocateComponent
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now handling output port settings change
W/AHierarchicalStateMachine(23319): Warning message AMessage(what = 'omxI') = {
W/AHierarchicalStateMachine(23319):   int32_t type = 0
W/AHierarchicalStateMachine(23319):   int32_t event = 3
W/AHierarchicalStateMachine(23319):   int32_t data1 = 1
W/AHierarchicalStateMachine(23319):   int32_t data2 = 117440527
W/AHierarchicalStateMachine(23319): } unhandled in root state.
I/OMXClient(23319): Treble IOmx obtained
D/SurfaceUtils(23319): set up nativeWindow 0x78ba8c0010 for 512x352, color 0x121, rotation 0, usage 0x2900
I/ACodec  (23319): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 5
I/ACodec  (23319): [OMX.google.aac.decoder] Now Loaded
I/ACodec  (23319): codec does not support config priority (err -2147483648)
I/ACodec  (23319): codec does not support config operating rate (err -2147483648)
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (23319): [OMX.google.aac.decoder] Now Loaded->Idle
I/ACodec  (23319): [OMX.google.aac.decoder] Now Idle->Executing
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing
I/ACodec  (23319): [OMX.google.aac.decoder] Now handling output port settings change
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing
D/AudioTrack(23319): Client defaulted notificationFrames to 11536 for frameCount 23072
D/AudioManager(23319): dispatching onAudioFocusChange(-1) to android.media.AudioManager$331da2ccom.google.android.exoplayer2.AudioFocusManager$AudioFocusListener$b98e69c
I/AudioTrack(23319): This process already got info. FadeIn[0] FadeOut[0] FadeInRing[0]
I/ACodec  (23319): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (23319): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 5/5 input, 1/15 output).
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ExoPlayerImpl(23319): Release 2480a6c [ExoPlayerLib/2.18.7] [a5y17lte, SM-A520F, samsung, 26] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (23319): [OMX.google.aac.decoder] signalFlush
I/ACodec  (23319): [OMX.google.aac.decoder] ExecutingState flushing now (codec owns 4/4 input, 0/4 output).
D/AudioTrack(23319): stop() called with 0 frames delivered
I/ACodec  (23319): [OMX.google.aac.decoder] Now Flushing
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,0)
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing->Idle
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-2] cancelBuffer: BufferQueue has been abandoned
I/chatty  (23319): uid=10245(u0_a245) JNISurfaceTextu identical 6 lines
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-2] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-2] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-2] cancelBuffer: BufferQueue has been abandoned
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Idle->Loaded
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (23319):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
D/SurfaceUtils(23319): disconnecting from surface 0x78c347f010, reason disconnectFromSurface
I/MediaCodec(23319): Codec shutdown complete
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing->Idle
I/ACodec  (23319): [OMX.google.aac.decoder] Now Idle->Loaded
I/ACodec  (23319): [OMX.google.aac.decoder] Now Loaded
I/ACodec  (23319):  [OMX.google.aac.decoder] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
I/MediaCodec(23319): Codec shutdown complete
I/ACodec  (23319): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (23319): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 5/5 input, 1/15 output).
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing
I/ExoPlayerImpl(23319): Release f5e360b [ExoPlayerLib/2.18.7] [a5y17lte, SM-A520F, samsung, 26] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/ACodec  (23319): [OMX.google.aac.decoder] signalFlush
D/AudioTrack(23319): stop() called with 0 frames delivered
I/ACodec  (23319): [OMX.google.aac.decoder] ExecutingState flushing now (codec owns 4/4 input, 0/4 output).
I/ACodec  (23319): [OMX.google.aac.decoder] Now Flushing
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,0)
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing->Idle
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-1] cancelBuffer: BufferQueue has been abandoned
I/chatty  (23319): uid=10245(u0_a245) JNISurfaceTextu identical 8 lines
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-1] cancelBuffer: BufferQueue has been abandoned
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Idle->Loaded
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (23319):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
D/SurfaceUtils(23319): disconnecting from surface 0x78cc492010, reason disconnectFromSurface
I/MediaCodec(23319): Codec shutdown complete
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing->Idle
I/ACodec  (23319): [OMX.google.aac.decoder] Now Idle->Loaded
I/ACodec  (23319): [OMX.google.aac.decoder] Now Loaded
I/ACodec  (23319):  [OMX.google.aac.decoder] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
I/MediaCodec(23319): Codec shutdown complete
I/ACodec  (23319): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (23319): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 5/5 input, 1/15 output).
I/ExoPlayerImpl(23319): Release 40a6d55 [ExoPlayerLib/2.18.7] [a5y17lte, SM-A520F, samsung, 26] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec  (23319): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (23319): [OMX.google.aac.decoder] signalFlush
I/ACodec  (23319): [OMX.google.aac.decoder] ExecutingState flushing now (codec owns 4/4 input, 0/4 output).
D/AudioTrack(23319): stop() called with 0 frames delivered
I/ACodec  (23319): [OMX.google.aac.decoder] Now Flushing
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,0)
I/ACodec  (23319): [OMX.google.aac.decoder] FlushingState onOMXEvent(0,1,1)
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Executing->Idle
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-0] cancelBuffer: BufferQueue has been abandoned
I/chatty  (23319): uid=10245(u0_a245) JNISurfaceTextu identical 5 lines
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-0] cancelBuffer: BufferQueue has been abandoned
I/chatty  (23319): uid=10245(u0_a245) JNISurfaceTextu identical 1 line
E/BufferQueueProducer(23319): [SurfaceTexture-0-23319-0] cancelBuffer: BufferQueue has been abandoned
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Idle->Loaded
I/ACodec  (23319): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (23319):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
D/SurfaceUtils(23319): disconnecting from surface 0x78bf4d6010, reason disconnectFromSurface
I/MediaCodec(23319): Codec shutdown complete
I/ACodec  (23319): [OMX.google.aac.decoder] Now Executing->Idle
I/ACodec  (23319): [OMX.google.aac.decoder] Now Idle->Loaded
I/ACodec  (23319): [OMX.google.aac.decoder] Now Loaded
I/ACodec  (23319):  [OMX.google.aac.decoder] Now uninitialized
I/ACodec  (23319):  [] Now kWhatShutdownCompleted event : 8478
I/MediaCodec(23319): Codec shutdown complete

======== Exception caught by services library ======================================================
The following PlatformException was thrown while de-activating platform stream on channel flutter.io/videoPlayer/videoEvents0:
PlatformException(error, No active stream to cancel, null, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:688:9)
<asynchronous suspension>
====================================================================================================
```

</details>

### Flutter Doctor output

I will provide in a bit.

**Comment by darshankawar** [comment]
@Aging-Developer 
Please provide the error log in properly formatted text instead of in screenshots.


> ### Code sample
> I will provide in a bit.

Please provide this so as to make the issue actionable.

**Comment by Aging-Developer** [comment]
@darshankawar Hi, Issues updated as requested.

**Comment by darshankawar** [comment]
Thanks for the update. chewie is a third party package. Does the reported error occurs without using it ? If so, please provide updated code.

**Comment by Aging-Developer** [comment]
Yes the error happens without chewie.

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class BasicLoopingVideoPlayer extends StatefulWidget {
  final String videoAsset;

  const BasicLoopingVideoPlayer({
    Key? key,
    required this.videoAsset,
  }) : super(key: key);

  @override
  _BasicLoopingVideoPlayerState createState() => _BasicLoopingVideoPlayerState();
}

class _BasicLoopingVideoPlayerState extends State<BasicLoopingVideoPlayer>
    with WidgetsBindingObserver {
  VideoPlayerController? _controller;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _initializeVideoPlayer();
  }

  Future<void> _initializeVideoPlayer() async {
    _controller = VideoPlayerController.asset('assets/videos/${widget.videoAsset}')
      ..initialize().then((_) {
        _controller!.setLooping(true);
        _controller!.play();
        setState(() {}); // Ensure the UI is updated after initialization.
      });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _controller?.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (_controller != null) {
      if (state == AppLifecycleState.inactive) {
        _controller?.pause();
      } else if (state == AppLifecycleState.resumed) {
        _controller?.play();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return _controller != null && _controller!.value.isInitialized
        ? AspectRatio(
            aspectRatio: _controller!.value.aspectRatio,
            child: VideoPlayer(_controller!),
          )
        : Center(
            child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(Colors.blue),
              strokeWidth: 2.0,
            ),
          );
  }
}

**Comment by darshankawar** [comment]
@Aging-Developer 
Can you check if `when the EventChannel#receiveBroadcastStream() method is being called twice` in your case or not ?
If so, then the said error could arise if trying to canel the second stream.
