### ISSUE TITLE
`flutter test --preview-dart-2` regression

### ISSUE THREAD

**Issue by aam** [flutter/flutter#15232]
With recent dart roll (landed in https://github.com/flutter/flutter/pull/15213)  `flutter test --preview-dart-2` regressed:
```
╰─➤  ../../bin/flutter test --preview-dart-2                                                                                                                   
Building flutter tool...
Running "flutter packages get" in flutter...                 0.6s
00:04 +0: loading $FH/flutter/packages/flutter/test/scheduler/debug_test.dart                                            
Finished compilation of /var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerkfrTVl/listener.dart into /var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerkfrTVl/listener.dart.dill
00:05 +1: loading $FH/flutter/packages/flutter/test/scheduler/debug_test.dart                                            
Finished compilation of /var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerF1IQdb/listener.dart into /var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerkfrTVl/listener.dart.dill
Shell: ../../third_party/dart/runtime/vm/kernel_binary.cc: 21: error: Invalid magic identifier
Shell: Dumping native stack trace for thread 5503
Shell:   [0x000000010ba565f9] dart::Profiler::DumpStackTrace(bool)
Shell:   [0x000000010ba565f9] dart::Profiler::DumpStackTrace(bool)
Shell:   [0x000000010d451ff0] dart::DynamicAssertionHelper::Fail(char const*, ...)
Shell:   [0x000000010b922c11] dart::kernel::Program::ReadFrom(dart::kernel::Reader*, bool)
Shell:   [0x000000010b92318b] dart::ReadPrecompiledKernelFromBuffer(unsigned char const*, long)
Shell:   [0x000000010d43cf7c] Dart_ReadKernelBinary
Shell:   [0x000000010d3e0510] blink::DartController::RunFromKernel(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
Shell:   [0x000000010c0a01bb] shell::Engine::RunBundleAndSource(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)
Shell:   [0x000000010d40eaaa] shell::TestRunner::Run(shell::TestRunner::TestDescriptor const&)::$_1::operator()() const
Shell:   [0x000000010d40e94b] void std::__1::__invoke_void_return_wrapper<void>::__call<shell::TestRunner::Run(shell::TestRunner::TestDescriptor const&)::$_1&>(shell::TestRunner::Run(shell::TestRunner::TestDescriptor const&)::$_1&&&)
Shell:   [0x000000010d40e607] std::__1::__function::__func<shell::TestRunner::Run(shell::TestRunner::TestDescriptor const&)::$_1, std::__1::allocator<shell::TestRunner::Run(shell::TestRunner::TestDescriptor const&)::$_1>, void ()>::operator()()
Shell:   [0x000000010bce4513] std::__1::function<void ()>::operator()() const
Shell:   [0x000000010bcf9ccd] fml::MessageLoopImpl::RunExpiredTasks()
Shell:   [0x000000010bcf8f33] fml::MessageLoopImpl::RunExpiredTasksNow()
Shell:   [0x000000010bd0ac03] fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
Shell:   [0x00007fff39a7fdd4] __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Shell:   [0x00007fff39a7fa47] __CFRunLoopDoTimer
Shell:   [0x00007fff39a7f54a] __CFRunLoopDoTimers
Shell:   [0x00007fff39a76b4b] __CFRunLoopRun
Shell:   [0x00007fff39a75f43] CFRunLoopRunSpecific
Shell:   [0x000000010bd0b209] fml::MessageLoopDarwin::Run()
Shell:   [0x000000010bcfa70f] fml::MessageLoopImpl::DoRun()
Shell:   [0x000000010bcf5dbb] fml::MessageLoop::Run()
Shell:   [0x000000010bd088ac] fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const
Shell:   [0x000000010bd085cb] std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*, void*)
Shell:   [0x00007fff616186c1] _pthread_body
Shell:   [0x00007fff6161856d] _pthread_body
Shell:   [0x00007fff61617c5d] thread_start
Shell: -- End of DumpStackTrace
00:05 +1 -1: loading $FH/flutter/packages/flutter/test/scheduler/ticker_test.dart [E]                                    
  Failed to load "$FH/flutter/packages/flutter/test/scheduler/ticker_test.dart":
  Shell subprocess crashed with SIGABRT (-6) before connecting to test harness.
  Test: $FH/flutter/packages/flutter/test/scheduler/ticker_test.dart
  Shell: $FH/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
  
  
compiler message: Unhandled exception:
compiler message: FileSystemException: Cannot open file, path = '/var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerkfrTVl/listener.dart.dill' (OS Error: No such file or directory, errno = 2)
compiler message: #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:351)
compiler message: #1      _RootZone.runUnary (dart:async/zone.dart:1381)
compiler message: #2      _FutureListener.handleValue (dart:async/future_impl.dart:129)
compiler message: #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
compiler message: #4      _Future._propagateToListeners (dart:async/future_impl.dart:662)
compiler message: #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
compiler message: #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
compiler message: #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
compiler message: #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
compiler message: #9      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
compiler message: #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
00:06 +1 -1: loading $FH/flutter/packages/flutter/test/scheduler/debug_test.dart                                         
Finished compilation of /var/folders/q2/g9pw0kqx18v8109_qg1lxll0008dk8/T/dart_test_listenerqyjRZG/listener.dart into null
00:06 +1 -2: loading $FH/flutter/packages/flutter/test/scheduler/priority_test.dart [E]                                  
  Failed to load "$FH/flutter/packages/flutter/test/scheduler/priority_test.dart":
  Compilation failed
  Test: $FH/flutter/packages/flutter/test/scheduler/priority_test.dart
  Shell: $FH/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
```

**Comment by aam** [comment]
cc @a-siva @mraleph
