### ISSUE TITLE
Crash both on android and io; RenderBox was not laid out: RenderUiKitView#2992f NEEDS-LAYOUT NEEDS-PAINT

### ISSUE THREAD

**Issue by doraspocket** [flutter/flutter#152359]
### Steps to reproduce

class AppWebviewWidget extends StatefulWidget {
  const AppWebviewWidget({super.key});

  @override
  State<AppWebviewWidget> createState() => _AppWebviewWidgetState();
}

class _AppWebviewWidgetState extends State<AppWebviewWidget> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();

    // #docregion webview_controller
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onHttpError: (HttpResponseError error) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://flutter.dev'));
    // #enddocregion webview_controller
  }

  @override
  Widget build(BuildContext context) {
    return WebViewWidget(controller: controller);
  }
}

==========================
class RootView extends GetView{
  const RootView({
    super.key
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: _createAppBar(),
      body: AppWebviewWidget()
    );
  }
}

### Expected results

Error when scroll

### Actual results

WebView content can be loaded correctly, but once there is a scroll operation it will report an error

======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
RenderBox was not laid out: RenderUiKitView#3e621 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'

### Code sample

class AppWebviewWidget extends StatefulWidget {
  const AppWebviewWidget({super.key});

  @override
  State<AppWebviewWidget> createState() => _AppWebviewWidgetState();
}

class _AppWebviewWidgetState extends State<AppWebviewWidget> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();

    // #docregion webview_controller
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onHttpError: (HttpResponseError error) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://flutter.dev'));
    // #enddocregion webview_controller
  }

  @override
  Widget build(BuildContext context) {
    return WebViewWidget(controller: controller);
  }
}

==========================
class RootView extends GetView{
  const RootView({
    super.key
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: _createAppBar(),
      body: AppWebviewWidget()
    );
  }
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.3 23D56 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @doraspocket, please provide a complete runnable code sample __without any third-party packages__ so that we can properly investigate this.

Thank you

**Comment by moheb-badawy** [comment]
I am facing the same issue.

@danagbemava-nc , the sample provided by @doraspocket is using flutter webview plugin that's causing the issue.

**Comment by danagbemava-nc** [comment]
Hi @moheb-badawy, please provide a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by moheb-badawy** [comment]
Hello @danagbemava-nc thanks for your support.

Thanks to @huycozy, He already introduced a sample in #83481.
I forked his sample and updated the implementation and dependancies at #[356f6d2](https://github.com/moheb-badawy/platformviews-demo/commit/356f6d2f76350f177aab31f1756bfbee3fab5a6a)

**Comment by moheb-badawy** [comment]
Hello @danagbemava-nc.

Thanks to @huycozy, He already introduced a sample at https://github.com/flutter/flutter/issues/83481.
I forked his sample and updated the implementation and dependancies at https://github.com/moheb-badawy/platformviews-demo/tree/platform_route

Flutter doctor -v (stable and master)
`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!`



Exception Log 
`======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
RenderBox was not laid out: RenderUiKitView#9ec93 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2164 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2164:12)
#3      RenderDarwinPlatformView._handleGlobalPointerEvent (package:flutter/src/rendering/platform_view.dart:353:25)
#4      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#5      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#7      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:133:5)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:501:19)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
#16     _invoke1 (dart:ui/hooks.dart:328:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================`

You support is highly appreciated, thank you.

**Comment by danagbemava-nc** [comment]
Hi @moheb-badawy, this is indeed related to https://github.com/flutter/flutter/issues/83481. It's a duplicate of the issue linked above. Kindly follow up in the original issue for updates. 

Closing from here as duplicate.
