### ISSUE TITLE
Can't put a Navigator inside a Focus

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1523]
```
02-02 10:32:21.593  3047  3077 I flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
02-02 10:32:21.594  3047  3077 I flutter : Exception caught while building Flexible(flex: 1)
02-02 10:32:21.596  3047  3077 I flutter : 'packages/flutter/src/widgets/framework.dart': Failed assertion: line 1083: '() {
02-02 10:32:21.596  3047  3077 I flutter :           if (_debugBuilding) {
02-02 10:32:21.596  3047  3077 I flutter :             bool foundTarget = false;
02-02 10:32:21.596  3047  3077 I flutter :             visitAncestorElements((Element element) {
02-02 10:32:21.596  3047  3077 I flutter :                   if (element == _debugCurrentBuildTarget) {
02-02 10:32:21.596  3047  3077 I flutter :                     foundTarget = true;
02-02 10:32:21.596  3047  3077 I flutter :                     return false;
02-02 10:32:21.596  3047  3077 I flutter :                   }
02-02 10:32:21.596  3047  3077 I flutter :                   return true;
02-02 10:32:21.597  3047  3077 I flutter :                 });
02-02 10:32:21.597  3047  3077 I flutter :             if (foundTarget)
02-02 10:32:21.597  3047  3077 I flutter :             return true;
02-02 10:32:21.597  3047  3077 I flutter :           }
02-02 10:32:21.597  3047  3077 I flutter :           return !_debugStateLocked || (_debugAllowIgnoredCallsToMarkNeedsBuild && dirty);
02-02 10:32:21.597  3047  3077 I flutter :         }' is not true.
02-02 10:32:21.597  3047  3077 I flutter : Stack trace:
02-02 10:32:21.605  3047  3077 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
02-02 10:32:21.605  3047  3077 I flutter : #1      BuildableElement.markNeedsBuild (packages/flutter/src/widgets/framework.dart:1083)
02-02 10:32:21.605  3047  3077 I flutter : #2      State.setState (packages/flutter/src/widgets/framework.dart:339)
02-02 10:32:21.605  3047  3077 I flutter : #3      _FocusState._setFocusedScope (packages/flutter/src/widgets/focus.dart:226)
02-02 10:32:21.605  3047  3077 I flutter : #4      Focus.moveScopeTo (packages/flutter/src/widgets/focus.dart:158)
02-02 10:32:21.605  3047  3077 I flutter : #5      ModalRoute.didPush (packages/flutter/src/widgets/routes.dart:405)
02-02 10:32:21.605  3047  3077 I flutter : #6      NavigatorState._push.<anonymous closure> (packages/flutter/src/widgets/navigator.dart:239)
02-02 10:32:21.605  3047  3077 I flutter : #7      State.setState (packages/flutter/src/widgets/framework.dart:338)
02-02 10:32:21.605  3047  3077 I flutter : #8      NavigatorState._push (packages/flutter/src/widgets/navigator.dart:234)
02-02 10:32:21.605  3047  3077 I flutter : #9      NavigatorState.initState (packages/flutter/src/widgets/navigator.dart:174)
02-02 10:32:21.605  3047  3077 I flutter : #10     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1260)
02-02 10:32:21.605  3047  3077 I flutter : #11     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.605  3047  3077 I flutter : #12     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.605  3047  3077 I flutter : #13     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1806)
02-02 10:32:21.605  3047  3077 I flutter : #14     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.605  3047  3077 I flutter : #15     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.605  3047  3077 I flutter : #16     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
02-02 10:32:21.605  3047  3077 I flutter : #17     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
02-02 10:32:21.605  3047  3077 I flutter : #18     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
02-02 10:32:21.605  3047  3077 I flutter : #19     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.605  3047  3077 I flutter : #20     ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1366)
02-02 10:32:21.606  3047  3077 I flutter : #21     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #22     MultiChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1806)
02-02 10:32:21.606  3047  3077 I flutter : #23     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #24     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #25     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
02-02 10:32:21.606  3047  3077 I flutter : #26     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
02-02 10:32:21.606  3047  3077 I flutter : #27     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
02-02 10:32:21.606  3047  3077 I flutter : #28     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.606  3047  3077 I flutter : #29     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #30     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #31     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
02-02 10:32:21.606  3047  3077 I flutter : #32     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
02-02 10:32:21.606  3047  3077 I flutter : #33     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
02-02 10:32:21.606  3047  3077 I flutter : #34     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.606  3047  3077 I flutter : #35     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #36     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #37     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1727)
02-02 10:32:21.606  3047  3077 I flutter : #38     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #39     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #40     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
02-02 10:32:21.606  3047  3077 I flutter : #41     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
02-02 10:32:21.606  3047  3077 I flutter : #42     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
02-02 10:32:21.606  3047  3077 I flutter : #43     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1270)
02-02 10:32:21.606  3047  3077 I flutter : #44     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.606  3047  3077 I flutter : #45     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #46     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #47     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1202)
02-02 10:32:21.606  3047  3077 I flutter : #48     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1123)
02-02 10:32:21.606  3047  3077 I flutter : #49     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1169)
02-02 10:32:21.606  3047  3077 I flutter : #50     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1270)
02-02 10:32:21.606  3047  3077 I flutter : #51     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1164)
02-02 10:32:21.606  3047  3077 I flutter : #52     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:817)
02-02 10:32:21.606  3047  3077 I flutter : #53     Element.updateChild (packages/flutter/src/widgets/framework.dart:695)
02-02 10:32:21.606  3047  3077 I flutter : #54     RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:236)
02-02 10:32:21.607  3047  3077 I flutter : #55     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:202)
02-02 10:32:21.607  3047  3077 I flutter : #56     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1056)
02-02 10:32:21.607  3047  3077 I flutter : #57     RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:199)
02-02 10:32:21.607  3047  3077 I flutter : #58     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:156)
02-02 10:32:21.607  3047  3077 I flutter : #59     runApp (packages/flutter/src/widgets/binding.dart:163)
02-02 10:32:21.607  3047  3077 I flutter : #60     main.<main_async_body> (/media/jimbe/mojossd/sysui/src/theone/android/lib/main.dart:239)
02-02 10:32:21.607  3047  3077 I flutter : #61     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
02-02 10:32:21.607  3047  3077 I flutter : #62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
02-02 10:32:21.607  3047  3077 I flutter : #63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
02-02 10:32:21.607  3047  3077 I flutter : ------------------------------------------------------------------------
```

**Comment by abarth** [comment]
Fixed by the new focus system.  I've posted a PR with a test.
