### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by komlan55** [flutter/flutter#152434]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target /Users/komlan/DEV/Flutter/bladeconnect/lib/main.dart
```

## Steps to Reproduce
1. /path/to/project/android/local.properties

```
sdk.dir=/Users/komlan/Library/Android/sdk
flutter.sdk=/Users/komlan/tools/flutter
flutter.buildMode=debug
flutter.versionName=0.1.0
flutter.minSdk=24
flutter.compileSdkVersion=android-34
flutter.targetSdkVersion=and�roid-34
```

3. ...
4. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:217:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:216:12)
#6      new SettingsFile.parseFromFile (package:flutter_tools/src/base/utils.dart:156:36)
#7      updateLocalProperties (package:flutter_tools/src/android/gradle_utils.dart:714:29)
#8      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:695:12)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:371:21)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1743:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-CA)
    • Flutter version 3.19.6 on channel stable at /Users/komlan/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/komlan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
camera-0.10.5+9
camera_android-0.10.8+16
camera_avfoundation-0.9.14+1
camera_web-0.3.2+4
cloud_firestore-4.14.0
cloud_firestore_web-3.9.0
desktop_webview_auth-0.0.15
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_auth-4.16.0
firebase_auth_web-5.8.13
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_crashlytics-3.4.9
firebase_dynamic_links-5.4.8
firebase_storage-11.6.0
firebase_storage_web-3.6.17
flutter_native_splash-2.3.10
flutter_plugin_android_lifecycle-2.0.17
geolocator-11.0.0
geolocator_android-4.5.2
geolocator_apple-2.3.6
geolocator_web-3.0.0
geolocator_windows-0.2.2
google_sign_in-6.2.1
google_sign_in_android-6.1.21
google_sign_in_ios-5.7.4
google_sign_in_web-0.12.4
image_picker-1.0.7
image_picker_android-0.8.9+3
image_picker_for_web-3.0.2
image_picker_ios-0.8.9+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.0
permission_handler_android-12.0.5
permission_handler_apple-9.4.0
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2

**Comment by komlan55** [comment]
Solution: 

```
sdk.dir=/Users/komlan/Library/Android/sdk
flutter.sdk=/Users/komlan/tools/flutter
flutter.buildMode=debug
flutter.versionName=0.1.0
flutter.minSdk=24
flutter.compileSdkVersion=android-34
flutter.targetSdkVersion=android-34 <--- Remov the special characters

```
