### ISSUE TITLE
【Windows Platform】When `flutter run`, related dll and assets files are compiled and installed to the wrong location

### ISSUE THREAD

**Issue by ggdream** [flutter/flutter#152448]
### Steps to reproduce

I used Windows 10 and VS 2019 before, and it worked fine. Now I have changed to a new computer with Windows 11 and VS 2022. The previous code has such a problem, but if it is a new project, there will be no such problem.

Note that my project root directory is in `C:\Users\mocar\code\tg_app`, and the flutter package name is `app`. However, when running `flutter run`, cmake puts the relevant dependency files in `C:/Program Files/app`, resulting in `Built build\windows\x64\runner\Debug\app.exe` not being able to find the dependency files.

### Expected results

Run it!

### Actual results

```
[        ]   -- Installing: C:/Program
Files/app/data/flutter_assets/packages/map_launcher/assets/icons/truckmeister.svg
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/map_launcher/assets/icons/waze.svg
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/map_launcher/assets/icons/yandexMaps.svg[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/map_launcher/assets/icons/yandexNavi.svg[
       ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/media_kit
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/media_kit/assets
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/media_kit/assets/web
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/media_kit/assets/web/hls1.4.10.js
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/wakelock_plus
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/wakelock_plus/assets
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/packages/wakelock_plus/assets/no_sleep.js
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/shaders
[        ]   -- Installing: C:/Program Files/app/data/flutter_assets/shaders/ink_sparkle.frag
[   +9 ms] FinalizeBuildStatus:
[        ]   正在删除文件“x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild”。
[        ]   正在对“x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate”执行 Touch 任务。
[        ] 已完成生成项目“C:\Users\mocar\code\tg_app\build\windows\x64\INSTALL.vcxproj”(默认目标)的操作。
[   +1 ms] 已成功生成。
[        ]     0 个警告
[        ]     0 个错误
[        ] 已用时间 00:00:44.18
[  +27 ms] Building Windows application... (completed in 60.9s)
[   +2 ms] √ Built build\windows\x64\runner\Debug\app.exe
[  +51 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +2 ms] Error launching application on Windows.
[   +2 ms] "flutter run" took 64,698ms.
[  +19 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:840:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[ +237 ms] ensureAnalyticsSent: 229ms
[   +1 ms] Running 1 shutdown hook
[  +18 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1
```

### Code sample

flutter run

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[!] Flutter (Channel stable, 3.22.3, on Microsoft Windows [版本 10.0.22631.3880], locale zh-CN)
    • Flutter version 3.22.3 on channel stable at C:\Users\mocar\AppData\Roaming\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\mocar\AppData\Roaming\fvm\versions\3.22.3\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\mocar\AppData\Roaming\fvm\default. Consider adding
      C:\Users\mocar\AppData\Roaming\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\mocar\AppData\Roaming\fvm\versions\3.22.3\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\mocar\AppData\Roaming\fvm\default. Consider adding
      C:\Users\mocar\AppData\Roaming\fvm\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (11 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\env\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\env\Android\Sdk
    • Java binary at: C:\Users\mocar\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35122.118
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\mocar\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\mocar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.183
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.74

[!] Network resources
    X An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 2 categories.
```

**Comment by danagbemava-nc** [comment]
Hi @ggdream, if you do not face this issue with a new project but with an existing project, then it likely means you might have modified the build output directory of the application. 

Please provide a complete minimal reproducible code sample in a repository that we can clone so that we can properly investigate this. 

Thank you
