### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by Soukouna32** [flutter/flutter#152457]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=22X7N19308001335 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2236:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:934:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:594:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:867:13)
#17     Future._completeWithValue (dart:async/future_impl.dart:643:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
#19     _rootRun (dart:async/zone.dart:1399:13)
#20     _CustomZone.run (dart:async/zone.dart:1301:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
```
[✓] Flutter (Channel stable, 3.19.6, on Microsoft Windows [version 10.0.19045.4651], locale fr-FR)
    • Flutter version 3.19.6 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\Mel\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34622.214
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • VOG L29 (mobile)  • 22X7N19308001335 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [version 10.0.19045.4651]
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 126.0.2592.113

[!] Network resources
    ✗ An HTTP error occurred while checking "https://storage.googleapis.com/": Connection closed before full header was received

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 54e66469a933b60ddf175f858f82eaeb97e48c8d
### Plugins
cloud_firestore-4.17.5
cloud_firestore_web-3.12.5
emoji_picker_flutter-2.2.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_auth-4.20.0
firebase_auth_web-5.12.0
firebase_core-2.32.0
firebase_core_web-2.17.3
firebase_messaging-14.9.4
firebase_messaging_web-3.8.7
firebase_storage-11.7.7
firebase_storage_web-3.9.7
flutter_local_notifications-9.9.1
flutter_plugin_android_lifecycle-2.0.19
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3+1

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371
