### ISSUE TITLE
App not compiling

### ISSUE THREAD

**Issue by Zeedinstein** [flutter/flutter#15246]
Hi, I'm following the coding setups in https://codelabs.developers.google.com/codelabs/flutter-firebase/

And I've gotten to a point where the app won't compile. Even if I re-download the github projects from scripts and not change a thing, the app does not start up. It seems the image-picker is the problem...

## Logs
```
E:\Development\friendlychat\friendlychat-steps\full_steps\step_1_set_up_firebase>flutter run
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0,6s
Resolving dependencies...                            15,9s
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Development\friendlychat\friendlychat-steps\full_steps\step_1_set_up_firebase\android\build.gradle' line: 27

* What went wrong:
Could not determine the dependencies of task ':app:prepareDebugDependencies'.
> Could not resolve all task dependencies for configuration ':app:_debugApk'.
   > Could not find com.github.esafirm.android-image-picker:imagepicker:1.5.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://jcenter.bintray.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.pom
         https://maven.google.com/com/github/esafirm/android-image-picker/imagepicker/1.5.0/imagepicker-1.5.0.aar
     Required by:
         project :app > project :image_picker

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Gradle build failed: 1

E:\Development\friendlychat\friendlychat-steps\full_steps\step_1_set_up_firebase>flutter analyze
Analyzing E:\Development\friendlychat\friendlychat-steps\full_steps\step_1_set_up_firebase...
No issues found!
Ran in 4.7s
```

## Flutter Doctor
```
E:\Development\friendlychat\friendlychat-steps\full_steps\step_1_set_up_firebase>flutter doctor -v
[√] Flutter (Channel dev, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale en-ZA)
    • Flutter version 0.1.5 at E:\flutter\flutter
    • Framework revision 3ea4d06340 (13 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\AndroidSDK
    • Android NDK at E:\AndroidSDK\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = E:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by Josemboa** [comment]
Please add _**maven { url "https://jitpack.io" }**_ to your buid.gradle:

allprojects {
   repositories {
       jcenter()
       maven { url "https://maven.google.com" }
       _**maven { url "https://jitpack.io" }    // add this line**_
   }
}
Found it on: [https://stackoverflow.com/questions/44821172/intellij-idea-wont-run-flutter-app](url)

**Comment by zoechi** [comment]
can you please try `flutter update-packages --force-upgrade`

**Comment by Zeedinstein** [comment]
That didn't seem to work...

I started a new flutter project in android studio 3
and setup the project structure to point to android\app\src\main\AndroidManifest.xml instead of android\AndroidManifest.xml
Installed packages
and then tried to generate a signed APK and got this error:

Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_ZA
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_ZA
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.runBuildConfigGeneration(AndroidSourceGeneratingBuilder.java:620)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:218)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1263)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:940)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1012)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:903)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:736)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:384)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:192)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zoechi** [comment]
I assume this issue is stale.

**Comment by kroikie** [comment]
@Zeedinstein

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/895. Any further collaboration will be done there.

**Comment by yourshinsuke** [comment]
```
something/android/app/src/main/kotlin/jp/yourmystar/partner/MainActivity.kt: (7, 41): Unresolved reference: FirebaseCorePlugin
something/android/app/src/main/kotlin/jp/yourmystar/partner/MainActivity.kt: (8, 48): Unresolved reference: firebasecrashlytics
something/android/app/src/main/kotlin/jp/yourmystar/partner/MainActivity.kt: (25, 35): Unresolved reference: FirebaseCorePlugin
something/android/app/src/main/kotlin/jp/yourmystar/partner/MainActivity.kt: (26, 35): Unresolved reference: FirebaseCrashlyticsPlugin
```

**Comment by yourshinsuke** [comment]
not resolved!

**Comment by PegasusPool** [comment]
I see the same error now after upgrading to firebase_core v0.5.0

**Comment by PegasusPool** [comment]
Looks like `GeneratedPluginRegistrant` already handles adding `FirebaseCorePlugin` and `FirebaseCrashlyticsPlugin` via `registerWith(flutterEngine)`

I removed the following lines from `MainActivity.kt` to resolve the error.
```
import io.flutter.plugins.firebase.core.FirebaseCorePlugin;
import io.flutter.plugins.firebase.database.FirebaseDatabasePlugin;

...

flutterEngine.plugins.add(FirebaseDatabasePlugin())
flutterEngine.plugins.add(FirebaseCorePlugin())
```
