### ISSUE TITLE
AudioPlayer while writing Golden tests

### ISSUE THREAD

**Issue by CpedniyNikon** [flutter/flutter#152667]
### Steps to reproduce

1.
```dart
group('AudioPlayer Test', (){

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
        const MethodChannel('plugins.flutter.io/path_provider'),
            (MethodCall methodCall) async {
          return '.';
        });

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
        const MethodChannel('xyz.luan/audioplayers'),
            (MethodCall methodCall) async {
          return '.';
        });

    testGoldens('admin collection page', (tester) async {
      final builder = DeviceBuilder()
        ..addScenario(
            widget: const MaterialApp(
                debugShowCheckedModeBanner: false, home: AdminCollectionPage()));
      await tester.pumpDeviceBuilder(builder);
      await screenMatchesGolden(tester, 'admin_collection_page');
    });
  });
```

2. This page uses 
```dart
late AudioPlayer audioPlayer;
```
and 
```dart
rootPath = Platform.isAndroid
        ? await getExternalStorageDirectory()
        : await getApplicationSupportDirectory(); 
```
3. flutter test --update-goldens --tags=golden

### Expected results

test passed

### Actual results

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
xyz.luan/audioplayers/events/039d2269-6791-4970-975b-5d6320cb003b:
MissingPluginException(No implementation found for method listen on channel
xyz.luan/audioplayers/events/039d2269-6791-4970-975b-5d6320cb003b)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary><asynchronous suspension>

</summary>

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
xyz.luan/audioplayers/events/039d2269-6791-4970-975b-5d6320cb003b:
MissingPluginException(No implementation found for method listen on channel
xyz.luan/audioplayers/events/039d2269-6791-4970-975b-5d6320cb003b)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22000.2899], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

```

</details>

**Comment by huycozy** [comment]
>MissingPluginException(No implementation found for method listen on channel
xyz.luan/audioplayers/events/039d2269-6791-4970-975b-5d6320cb003b)

This error is thrown before `testGoldens` call and it looks like you put the test file into the wrong test directory. Please see https://docs.flutter.dev/testing/plugins-in-tests and https://docs.flutter.dev/testing/testing-plugins for the documentation. If you are running integration test on `integration_test` directory and still see the error, please provide a complete and minimal sample code. Thanks!
