### ISSUE TITLE
gradle error after 35 sdk upgrade: `A problem occurred starting process...`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#152771]
## reproduction

```
flutter run --profile
```

## error
```
/Users/aaclarke/dev/flutter/dev/benchmarks/macrobenchmarks/build/app/intermediates/flutter/profile
-dTargetFile=/Users/aaclarke/dev/flutter/dev/benchmarks/macrobenchmarks/lib/main.dart -dTargetPlatform=android -dBuildMode=profile -dTrackWidgetCreation=true -dFlavor=
-dAndroidArchs=android-arm64 -dMinSdkVersion=21 android_aot_bundle_profile_android-arm64
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildProfile'.
[        ] > A problem occurred starting process 'command '/Users/aaclarke/dev/flutter/bin/flutter''
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] > Get more help at https://help.gradle.org.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileFlutterBuildProfile'.
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
[        ] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
[        ] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
[        ] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[        ] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[        ] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[        ] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
[        ] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[        ] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[        ] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
[        ] 	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:138)
[        ] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:123)
[        ] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
[        ] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[        ] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[        ] 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
[        ] 	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$10(DefaultBuildLifecycleController.java:264)
[        ] 	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
[        ] 	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:177)
[        ] 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[        ] 	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:177)
[        ] 	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:255)
[        ] 	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:220)
[        ] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
[        ] 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
[        ] 	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:181)
[        ] 	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:50)
[        ] 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.lambda$run$0(DefaultBuildController.java:198)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
[        ] 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:198)
[        ] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[        ] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[        ] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ] 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[        ] 	at java.base/java.lang.Thread.run(Unknown Source)
[        ] Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/Users/aaclarke/dev/flutter/bin/flutter''
[        ] 	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
[        ] 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
[        ] 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:386)
[        ] 	at org.gradle.process.internal.ExecHandleRunner.lambda$run$3(ExecHandleRunner.java:102)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
[        ] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:101)
[        ] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ] 	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[        ] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[        ] 	at java.base/java.lang.Thread.run(Unknown Source)
[        ] Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/Users/aaclarke/dev/flutter/bin/flutter'
[        ] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
[        ] 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
[        ] 	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:122)
[        ] 	at org.gradle.process.internal.ExecHandleRunner.lambda$run$0(ExecHandleRunner.java:80)
[        ] 	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
[        ] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:79)
[        ] 	... 5 more
[        ] Caused by: java.io.IOException: Cannot run program "/Users/aaclarke/dev/flutter/bin/flutter" (in directory
"/Users/aaclarke/dev/flutter/dev/benchmarks/macrobenchmarks"): error=0, Failed to exec spawn helper: pid: 4654, signal: 11
[        ] 	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
[        ] 	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
[        ] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
[        ] 	... 10 more
[        ] Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 4654, signal: 11
[        ] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[        ] 	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
[        ] 	at java.base/java.lang.ProcessImpl.start(Unknown Source)
[        ] 	... 13 more
[        ] BUILD FAILED in 546ms
```

## doctor
```
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.24.0-1.0.pre.424, on macOS 14.5 23F79 darwin-arm64, locale en)
    ! Flutter version 3.24.0-1.0.pre.424 on channel [user-branch] at /Users/aaclarke/dev/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision d6e4555494 (27 minutes ago), 2024-08-03 02:46:24 +0530
    • Engine revision 353c6b237b
    • Dart version 3.6.0 (build 3.6.0-109.0.dev)
    • DevTools version 2.38.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode_15.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • Pixel 4a (mobile)               • 11121JEC203798            • android-arm64  • Android 13 (API 33)
    • iPhone (5) (mobile)             • 00008110-001524D40A10401E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.
```

**Comment by gaaclarke** [comment]
I tried just opening the `android` folder and building with android studio directly and it results in a different but similar error:

```
> Task :gradle:compileGroovy FAILED
Execution failed for task ':gradle:compileGroovy'.
> Failed to run Gradle Worker Daemon
   > A problem occurred starting process 'Gradle Worker Daemon 13'
```

I tried using "AGP Upgrade Assistant" but clicking on it just does nothing.

**Comment by gaaclarke** [comment]
I was finally able to progress by manually editing the `./android/gradle/wrapper/gradle-wrapper.properties` file to upgrade gradle:

```diff
- distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
```

@reidbaker is the tool supposed to do this automatically somehow?

**Comment by reidbaker** [comment]
I checked out d6e4555494 and ran flutter run --profile lib/gestures/velocity_tracker_bench.dart from dev/benchmarks/microbenchmarks which I think replicates what you were trying and had no issues.

**Comment by reidbaker** [comment]
> I was finally able to progress by manually editing the `./android/gradle/wrapper/gradle-wrapper.properties` file to upgrade gradle:
> 
> ```diff
> - distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
> + distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
> ```
> 
> @reidbaker is the tool supposed to do this automatically somehow?

The flutter tool does not automatically update gradle. The Android Studio AGP update assistant might. Which android app are you trying to build?

**Comment by gaaclarke** [comment]
> Which android app are you trying to build?

I started a new flutter proejct and tried to run macrobenchmarks.

> The Android Studio AGP update assistant might.

It didn't, it just showed an error and had no way to progress.

**Comment by reidbaker** [comment]
Can you share the full command you tried to run that is failing for you?

**Comment by gaaclarke** [comment]
> Can you share the full command you tried to run that is failing for you?

`flutter run --profile`, `flutter run` also would fail.

I can also state that after having manually edited the `./android/gradle/wrapper/gradle-wrapper.properties` file and run successfully, that change isn't required anymore.  Manually editing that file must have unblocked the android tooling.

So what happens with me is that I'll spend a lot of time on iOS then switch over to android, so there are large gaps between running android stuff which I'm guessing is creating situations that aren't tested as well.  The android team is probably testing incremental updates of tooling, but not large jumps.

This problem seems to fall squarely on the android team, I'm not sure if there is anything we can do from the flutter side.

**Comment by reidbaker** [comment]
My issue was I was in microbenchmarks which does not have a lib/main.dart so I was trying to figure out which benchmark was falling for you. It is possible that your machine did not have the right combination of java/gradle/agp and that could be "our" fault if we forgot to update something, or it could be "your" fault because java is the host machines responsibility but your java version looks good (17.0.11). 

I cant reproduce. Are you ok if I close?

**Comment by gaaclarke** [comment]
Yea, the workaround is documented.  We'll see if anyone runs into this in the future.
