### ISSUE TITLE
"error in the framework itself" when i used "controller.nextPage()"

### ISSUE THREAD

**Issue by mahdi-sharifii** [flutter/flutter#152842]
### Steps to reproduce

When I want to go to another page from "PageView()" I get this error

When I use
 `flutter clean`
 and then
 `flutter pub get`
 the problem is temporarily fixed

```
        BlocBuilder<CalendarCubit, CalendarState>(
              buildWhen: (p, c) =>(p.controller != c.controller || p.month != c.month) ,
              builder: (context, state) {
                if (state.controller == null) return const SizedBox();
                if (header != null) {
                  return header!(state.controller!, state.month!);
                }
                return Header(
                  controller: state.controller!,
                  calendarStyle: calendarStyle,
                );
              },
            )
```

```
 header: (controller, month) {
          return ElevatedButton(
                    onPressed: () {
                      controller.nextPage(
                        duration: const Duration(milliseconds: 700),
                        curve: Curves.linear,
                      );
                    },
                    child: const Text('Next'),
                  ),
              }
```

### Expected results

It should go to the next page!

### Actual results

```

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
PageController.page cannot be accessed before a PageView is built with it.
'package:flutter/src/widgets/page_view.dart':
Failed assertion: line 170 pos 7: 'positions.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      PageController.page (package:flutter/src/widgets/page_view.dart:170:7)
#3      PageController.nextPage (package:flutter/src/widgets/page_view.dart:223:26)
#4      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:test_calendar/main.dart:184:34)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:696:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#23     _invoke1 (dart:ui/hooks.dart:328:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
Handler: "onTap"
Recognizer: TapGestureRecognizer#475f4
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(63.4, 230.3)
  finalLocalPosition: Offset(35.4, 22.3)
  button: 1
  sent tap down
====================================================================================================

```

### Code sample

<details open><summary>Code sample</summary>

```dart
As above
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Flutter Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
• Flutter version 3.22.3 on channel stable at C:\src\flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/b0850beeb25f6d5b10426284f506557f66181b36 (3 weeks ago), 2024-07-16 21:43:41 -0700
• Engine revision 235db911ba
• Dart version 3.4.4
• DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at C:\Users\SH\AppData\Local\Android\sdk
• Platform android-34, build-tools 34.0.0
• Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
• Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
• Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
• Visual Studio Community 2022 version 17.7.34031.279
• Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.3)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.91.1)
• Flutter extension version 3.92.0

[√] Connected device (4 available)
• sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)
• Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19045.4529]
• Chrome (web) • chrome • web-javascript • Google Chrome 127.0.6533.89
• Edge (web) • edge • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
• All expected network resources are available.

• No issues found!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.91.1)
[√] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @mahdi-sharifii, please provide a complete minimal reproducible code sample `without any third-party packages` so that we can properly investigate this issue. 

Thank you
