### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: File exists, errno = 17

### ISSUE THREAD

**Issue by 4-alok** [flutter/flutter#152851]
## Command
```
flutter build linux
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: File exists, errno = 17
```
#0      _Link.throwIfError (dart:io/link.dart:339:7)
#1      _Link.createSync (dart:io/link.dart:267:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:981:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:903:5)
#6      buildLinux (package:flutter_tools/src/linux/build_linux.dart:72:3)
#7      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:89:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.3, on Ubuntu 24.04 LTS 6.8.0-39-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.22.3 on channel stable at /home/alok/.flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    [32m•[39m Engine revision 235db911ba
    [32m•[39m Dart version 3.4.4
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /home/alok/Android/Sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /snap/android-studio/161/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 18.1.3 (1ubuntu1)
    [32m•[39m cmake version 3.28.3
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 1.8.1

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /snap/android-studio/161
    [32m•[39m Flutter plugin version 80.0.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m VS Code (version 1.92.0)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04 LTS 6.8.0-39-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.72

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0850beeb25f6d5b10426284f506557f66181b36
### Plugins
path_provider-2.0.14
path_provider_android-2.0.24
path_provider_foundation-2.2.1
path_provider_linux-2.1.10
path_provider_windows-2.1.5

**Comment by danagbemava-nc** [comment]
Hi @4-alok, do you get this every time or was it a one time issue? If it is frequent, can you provide the output of `flutter build linux -v`?
