### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "/Users/stackgeeks/Documents/Flutter/sdk/flutter/bin/cache/dart-sdk/bin/dartaotruntime" in the search path. Command: /Users/stackgeeks/Documents/Flutter/sdk/flutter/bin/cache/dart-sdk/bin/dartaotruntime, OS error code: 0

### ISSUE THREAD

**Issue by kanika783** [flutter/flutter#152921]
## Command
```
flutter run -t lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "/Users/stackgeeks/Documents/Flutter/sdk/flutter/bin/cache/dart-sdk/bin/dartaotruntime" in the search path. Command: /Users/stackgeeks/Documents/Flutter/sdk/flutter/bin/cache/dart-sdk/bin/dartaotruntime, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:694:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:564:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:693:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:876:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:736:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:422:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:396:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:782:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.3, on macOS 12.7.6 21H1320 darwin-x64, locale en-IN)
    [32m•[39m Flutter version 3.22.3 on channel stable at /Users/stackgeeks/Documents/Flutter/sdk/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    [32m•[39m Engine revision 235db911ba
    [32m•[39m Dart version 3.4.4
    [32m•[39m DevTools version 2.34.3

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/stackgeeks/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[33m[!][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS
      development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[32m[✓][39m VS Code (version 1.92.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m AC2001 (mobile) • 9ab532ec • android-arm64  • Android 12 (API 31)
    [32m•[39m macOS (desktop) • macos    • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    [32m•[39m Chrome (web)    • chrome   • web-javascript • Google Chrome 127.0.6533.89

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0850beeb25f6d5b10426284f506557f66181b36

**Comment by danagbemava-nc** [comment]
https://github.com/flutter/flutter/issues/143391
