### ISSUE TITLE
[tool_crash] ProcessException: The command failed Command: hvigorw, OS error code: 255

### ISSUE THREAD

**Issue by hujiabing** [flutter/flutter#152914]
## Command
```
flutter build hap --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed Command: hvigorw, OS error code: 255
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:414:17)
#2      hvigorwTask (package:flutter_tools/src/ohos/hvigor.dart:141:41)
#3      assembleHar (package:flutter_tools/src/ohos/hvigor.dart:206:10)
#4      OhosHvigorBuilder.assembleHars (package:flutter_tools/src/ohos/hvigor.dart:704:33)
#5      OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:461:11)
<asynchronous suspension>
#6      BuildHapCommand

**Comment by danagbemava-nc** [comment]
This should be reported on [gitee.com/openharmony-sig/flutter_flutter](https://gitee.com/openharmony-sig/flutter_flutter).

Make sure you have all the required tools installed.

Closing from here.

Thank you
