### ISSUE TITLE
`flutter analyze` now requires ios/Runner.xcodeproj to exist, breaking website builds

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#15301]
## Steps to Reproduce

1. Clone https://github.com/flutter/website
2. Run `./tool/travis.sh`

**Explanation:** We're analyzing our sample code in CI. The files exist in file structures that aren't real flutter projects ([example](https://github.com/flutter/website/tree/master/_includes/code)). This worked well until very recently but now all our builds fail.

I can work around this but it would be great to have actual Flutter analysis run on these standalone files.

## Logs from running the above command

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

### command

flutter analyze _includes/code/animation/animate1/main.dart

### exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/filiph/dev/flutter-website/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:318)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:277)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:99)
#7      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:114)
#8      injectPlugins (package:flutter_tools/src/plugins.dart:246)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:278)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#27     main (file:///Users/filiph/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

### flutter doctor

```
[✓] Flutter (Channel master, v0.1.3-pre.19, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.3-pre.19 at /Users/filiph/dev/flutter
    • Framework revision 2337ddef0b (2 days ago), 2018-03-06 22:03:42 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by filiph** [comment]
Actually, same goes for `flutter packages get`.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter packages get

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/filiph/dev/flutter-website/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:318)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:277)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:99)
#7      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:114)
#8      injectPlugins (package:flutter_tools/src/plugins.dart:246)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:80)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#28     main (file:///Users/filiph/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.1.3-pre.19, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.3-pre.19 at /Users/filiph/dev/flutter
    • Framework revision 2337ddef0b (2 days ago), 2018-03-06 22:03:42 -0800
    • Engine revision 24cf8ebd86
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[✓] VS Code (version 1.20.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by filiph** [comment]
Oh hey, this is a duplicate of https://github.com/flutter/flutter/issues/15293

**Comment by filiph** [comment]
Worked around with https://github.com/flutter/website/pull/872 for now.

**Comment by ba127004** [comment]
I did the switching to beta version, but apparently it still throws the same errors!

flutter upgrade (after changing the branch to beta)
======================================
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (4 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

on build to IOS simulator / device 
==========================
Launching lib/main.dart on iPhone 6s Plus in debug mode...

Finished with error: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/$USER/workspace/$APPNAME/flutter_app/ios/Runner.xcodeproj -target Runner -showBuildSettings

**Comment by zoechi** [comment]
@ba127004 This issue is long closed. It's probably better to create a new issue (with a link to this one)
