### ISSUE TITLE
Unable to run on uos (a linux distribution, mainly used by some enterprises in China) after the flutter version is upgraded to 3.22 or 3.24, 

### ISSUE THREAD

**Issue by leisu1** [flutter/flutter#153009]
### Steps to reproduce

1.update flutter framework to 3.22 or 3.24
2.create a demo on uos operation system
3.build
4.run

### Expected results

the demo open success.

### Actual results

The demo crashed.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
when run in debug mode, it show toast: ZX WARNING:da spawn: headda is kept and spawn a new da，and then crashed.
 In /var/log/message，I find the crash info: 2024-08-07 15:08:58 01363827XC1 kernel: [12126.318621] demo[16314]: segfault at 0 ip 00007f8bdd4cbabd sp 00007fff6124ed90 error 4 in zx_dri.so[7f8bdd0c0000+6b1000]。

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
upchat@XC1:~/StudioProjects/testdpi$ flutter doctor
Flutter assets will be downloaded from http://xxxx(private ip, for internal use). Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on UnionTech OS Desktop 20 Pro 4.19.0-amd64-desktop, locale zh_CN.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 2022.1)
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue
      at https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      /home/upchat/Android/Sdk/platform-tools/adb
      Error details: Process exited abnormally with exit code 1:
      adb: failed to check server version: protocol fault (couldn't read status): Connection reset by peer
[!] Network resources
    ✗ A network error occurred while checking "https://cocoapods.org/": Connection reset by peer
    ✗ A network error occurred while checking "https://github.com/": Connection reset by peer

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Please provide the entire output of `flutter run -v` which may contain the complete stack trace for us to investigate further. The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it. Thank you!

**Comment by leisu1** [comment]
[run_console.txt](https://github.com/user-attachments/files/16536798/run_console.txt)

**Comment by leisu1** [comment]
I have a new discovery today, the problem may have relations with the graphics drive of the computer. Using the coredumpctl and gdb commands, the crash information was located at /usr/lib/x86_64-linux-gnu/dri/zx_dri.so. This dynamic library file belongs to the zhaoxin-linux-graphics-driver-dri package。

**Comment by huycozy** [comment]
The tail of output log [above](https://github.com/flutter/flutter/issues/153009#issuecomment-2274821420):

<details open>
<summary>Logs</summary>

```console
[  +73 ms] Building Linux application... (completed in 17.2s)
[  +30 ms] ✓ Built build/linux/x64/debug/bundle/testdpi
[ +496 ms] ZX WARNING:da spawn: headda is kept and spawn a new da 
[  +38 ms] ZX WARNING:da spawn: headda is kept and spawn a new da 
[+1088 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[  +25 ms] Error launching application on Linux.
[+4380 ms] "flutter run" took 24,839ms.
[  +15 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
```
</details>


Can you share Graphics Card information as well? Can you also try running this [simple GTK program](https://gist.github.com/huycozy/e256eb638287f3ce5799c53f881bcce9) to see if it works normally?

**Comment by leisu1** [comment]
Thank you very much for your patient reply！
I found the cause of the problem and fixed it. This problem should only occur on computers with zhaoxin cpu, just update the driver package zhaoxin-linux-graphics-driver-dri  can solve.

**Comment by huycozy** [comment]
Glad to see it's solved. The case you share may be helpful for others to experience this issue in the future. Closing.
