### ISSUE TITLE
"Encountered invalid export-method input." when running `flutter build ipa --export-method enterprise` using Flutter 3.24

### ISSUE THREAD

**Issue by Akmalismail** [flutter/flutter#153000]
### Steps to reproduce

1. Make sure currently using Flutter 3.24
2. run `flutter create sample`
3. cd sample
4. run `flutter build ipa --export-method enterprise` with a valid enterprise apple id

### Expected results

Successfully builds `.xcarchive` and `.ipa` in `build/ios/ipa`

### Actual results

`Runner.xrarchive` successfully built but the message `Encountered invalid export-method input.` was displayed (see screenshot below).

### Code sample

Following the steps above using Flutter 3.24. 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="694" alt="image" src="https://github.com/user-attachments/assets/9c7c7da3-63bf-48af-99c3-8456cd46d2fa">

</details>

### Logs

<details open><summary>Logs</summary>

Since build and archive was successful, only the error part is pasted.

```console]
...
           [!] App Settings Validation
[        ]     • Version Number: 1.0.0
[        ]     • Build Number: 1
[        ]     • Display Name: Sample
[        ]     • Deployment Target: 12.0
[        ]     • Bundle Identifier: com.example.another.sample.project
[        ]     ! Your application still contains the default "com.example" bundle identifier.
[        ] 
           [!] App Icon and Launch Image Assets Validation
[        ]     ! App icon is set to the default placeholder icon. Replace with unique icons.
[        ]     ! Launch image is set to the default placeholder icon. Replace with unique launch image.
[        ] 
           To update the settings, please refer to https://flutter.dev/to/ios-deploy
           
[   +1 ms] "flutter ipa" took 24,656ms.
[   +1 ms] Encountered invalid export-method input.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BuildIOSArchiveCommand._getVersionAppropriateExportMethod (package:flutter_tools/src/commands/build_ios.dart:596:13)
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:471:22)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[        ] Running 2 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/akmalismail/Documents/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/akmalismail/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89
    ! Error: Browsing on the local area network for Akmal’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by Akmalismail** [comment]
Downgrading flutter to `3.22.3` successfully creates `.ipa`

**Comment by huycozy** [comment]
Thank you for the report! 

I see the error is thrown here:

https://github.com/flutter/flutter/blob/e0c051f47f9e33cb16c2928273cee554987e27c0/packages/flutter_tools/lib/src/commands/build_ios.dart#L594-L605

This is added by https://github.com/flutter/flutter/pull/150407. Also, I see `enterprise` still belongs to method (from `xcodebuild --help`). It seems `enterprise` was missed as a case in `_getVersionAppropriateExportMethod()`.

>method : String Describes how Xcode should export the archive. Available options: app-store-connect, release-testing, enterprise, debugging, developer-id, mac-application, validation, and package. The list of options varies based on the type of archive. Defaults to debugging. Additional options include app-store (deprecated: use app-store-connect), ad-hoc (deprecated: use release-testing), and development (deprecated: use debugging).


Reproduced this on the latest Flutter stable and master channels. cc @LouiseHsu

```
Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-x64, locale en-VN
Channel master, 3.24.0-1.0.pre.486, on macOS 14.6 23G80 darwin-x64, locale en-VN
```
