### ISSUE TITLE
Navigator.onDidRemovePage does not give the result the route was popped with

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#153122]
### Steps to reproduce

Starting with 3.24.0 stable, `Navigator.onPopPage` is deprecated and replaced by `Navigator.onDidRemovePage`. However, the new API doesn't provide the result the page-based route has been removed with.
My use case - I have a custom navigation solution implemented with `Router`, let's call it `MyNav`. It manages its own pages, and when a page is added to it, it returns a `Future`. Then, when the page is removed with any method my solution supports, the methods accept an optional `result` and the `Future` is completed with it.
With `Navigator.onPopPage` the result of `Navigator.pop` was available and I could call my page removal method with this result. With the new `Navigator.onDidRemovePage` this is no longer possible. In other words, if I use `MyNav.push` and await on the `Future`, and then use `Navigator.pop(aResult)`, the `Future` has no chance of returning the value.
I read the rationale why this new API exists, but it is mostly about not playing nice with other popping solutions, like the iOS back gesture when the old callback decides to veto and the application hangs. But why is the result gone?

### Expected results

The `onDidRemovePage` callback provides the value so that custom navigation solutions see it.

### Actual results

The result is not available.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by wujek-srujek** [comment]
I know @chunhtai knows a lot about the `Navigator`/`Router` and implemented a lot of its code, and maintains `go_router`, and @goderbauer reviewed the PR with the new API. Hopefully I'm not doing anything wrong by mentioning them here.

**Comment by chunhtai** [comment]
you should access type safe result in Page.onPopInvoked. Navigator.ondidRemovePage should just focus on removing page since you can't veto at this point

**Comment by wujek-srujek** [comment]
But this is so far away from the `Future` handling code, and makes things that used to be simple so much more complicated.
Let alone the fact that I get an exception:
```
The following _TypeError was thrown while handling a gesture:
type '(bool, String?) => void' is not a subtype of type '(bool, Object?) => void'

When the exception was thrown, this was the stack:
#0      Route.onPopInvokedWithResult (package:flutter/src/widgets/navigator.dart:390:12)
#1      ModalRoute.onPopInvokedWithResult (package:flutter/src/widgets/routes.dart:1782:11)
#2      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:3171:11)
#3      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4340:22)
#4      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5368:7)
...
```
I'm not sure yet why this is, looks like https://github.com/flutter/flutter/blob/3.24.0/packages/flutter/lib/src/widgets/navigator.dart#L389 might be responsible - my page is `Page<String>`, and I'm trying to complete it with a `String`, but the code casts it to `Page<Object?>`, and the exception happens.

**Comment by wujek-srujek** [comment]
> you should access type safe result in Page.onPopInvoked. Navigator.ondidRemovePage should just focus on removing page since you can't veto at this point

I don't want to veto anything, I just need the result. I don't think vetoing and getting the result have anything to do with each other, and it seems that by removing 1 facet of the old API (vetoing) you might have inadvertently removed another, unrelated one. I can't fathom why you would require people to jump through hoops to just get hold of the result.

**Comment by wujek-srujek** [comment]
Creating a `Page` and passing the `Page.onPopInvoked` is done by the client in client code, and the `Futures` are handled in the routing library code. How can I make it so that I get the result in the navigation code? I don't have any control over what the client does in the callback. I think I might not understand the whole concept of navigation with `Router` in Flutter.

**Comment by chunhtai** [comment]
> But this is so far away from the `Future` handling code, and makes things that used to be simple so much more complicated. Let alone the fact that I get an exception:

this looks like a bug. Can you file an issue with repro and pin me on it?

**Comment by chunhtai** [comment]
> I don't want to veto anything, I just need the result.

I do get that if page is provided from client code there isn't a good way to inject library code to it. I was trying to come up with a way to do that. If i can't figure it out, slapping a result on the onDidRmoevePage should be easy.

**Comment by wujek-srujek** [comment]
> > But this is so far away from the `Future` handling code, and makes things that used to be simple so much more complicated. Let alone the fact that I get an exception:
> 
> this looks like a bug. Can you file an issue with repro and pin me on it?

I can, but it will take some time to 'depropriatize' the code. But I think the problem is easy to fix. The code is:
```dart
@mustCallSuper
  void onPopInvokedWithResult(bool didPop, T? result) {
    if (_isPageBased) {
      final Page<Object?> page = settings as Page<Object?>;
      page.onPopInvoked(didPop, result);
    }
  }
```
Shouldn't it be:
```dart
@mustCallSuper
  void onPopInvokedWithResult(bool didPop, T? result) {
    if (_isPageBased) {
      final Page<T?> page = settings as Page<T?>;
      page.onPopInvoked(didPop, result);
    }
  }
```
Not sure whether the `?` is necessary. But it does look like the typing is wrong in the Flutter code, right?

**Comment by wujek-srujek** [comment]
Yeah, I quickly prototyped and this:
```dart
  @mustCallSuper
  void onPopInvokedWithResult(bool didPop, T? result) {
    if (_isPageBased) {
      final Page<T> page = settings as Page<T>;
      page.onPopInvoked(didPop, result);
    }
  }
```
fixes the exception I'm seeing.
I guess I don't need to create any repro? The issue with typing seems obvious, but I am not well versed in Flutter code.

**Comment by chunhtai** [comment]
yes this might be it. I think you can easily repro it with a test case like

MyCustomPage<String> page = MyCustomPage<String>()
MyRoute<String> route = page.createRoute();
route.onPopInvokedWithResult(bool didPop, result).

Since you already have a fix, do you want to submit a pr?

**Comment by wujek-srujek** [comment]
> yes this might be it. I think you can easily repro it with a test case like
> 
> MyCustomPage page = MyCustomPage() MyRoute route = page.createRoute(); route.onPopInvokedWithResult(bool didPop, result).
> 
> Since you already have a fix, do you want to submit a pr?

I'm sorry, I won't be able to. My experience with getting my things merged to huge projects like this has been frustrating, and not good for my mental health.

**Comment by wujek-srujek** [comment]
> > I don't want to veto anything, I just need the result.
> 
> I do get that if page is provided from client code there isn't a good way to inject library code to it. I was trying to come up with a way to do that. If i can't figure it out, slapping a result on the onDidRmoevePage should be easy.

How does `go_router` deal with this? I think it doesn't let clients provide `Page`s, it creates them internally from the configuration and hooks the callback somehow to do the right thing?

**Comment by chunhtai** [comment]
right, I have to find a way to inject the page which i think is possible to do things like
```dart
class PageProxy extends Page {
   class PageProxy(this.child)
   
   PopInovkedWithResult onPopInvokeWithResult (didpop, result) {
   ...do some hookin up
   child.onPopInvokeWithResult(didpop, result);
  }
   Route createRoute => child.createRoute();
}
```

**Comment by chunhtai** [comment]
This feels like a heck though, but I will use this as a temporary bandage until i have a more systematic way to create a page proxy

**Comment by wujek-srujek** [comment]
I was thinking of a similar solution: wrap the page from client code in my own, to be able to provide my own `onPopInvoked`. This is exactly what I meant when I wrote 'things that used to be simple are complex now'. Hopefully not many people have to write their customized navigation solutions.

Judging by what you wrote, I guess `go_router` doesn't support that either as of right now? Especially as there is the typing issue that I guess would also trigger in `go_router`.

For the time being, I have two quick solutions in my project:
1. Ban direct `Navigator` usage.
2. Not change my code and use the deprecated callback.
I personally don't like either of them.

**Comment by wujek-srujek** [comment]
Another issue is the other way round - if I pop a route with my custom navigation solution, and its `Page` has the `onPopInvoked` callback defined, it is always called with `null` result. It makes sense, Flutter (as of now) can't know what my navigation solution resolved the `Future` with. I think this might be a source of many bugs as well.

I starting to think that it is a very, very bad idea to mix navigation calls with solutions like my own or `go_router` with `Navigator`-based APIs (like `push` or `pop`) - there are simply too many edge cases that will make devs scratch their heads. I think Flutter should be more explicit about the pitfalls, the current official information (https://docs.flutter.dev/ui/navigation#using-router-and-navigator-together) makes it sound like all will work fine. Also the documentation https://api.flutter.dev/flutter/widgets/Page/onPopInvoked.html should mention that the result is only available if popped with `Navigator`.

**Comment by darshankawar** [comment]
@wujek-srujek Trying to wrap my head around the discussion. 

I guess you have filed a new issue for https://github.com/flutter/flutter/issues/153122#issuecomment-2276638627.

Is https://github.com/flutter/flutter/issues/153122#issuecomment-2276664427 a solution for new issue ? Or does this solution resolve the issue you reported here ?

**Comment by wujek-srujek** [comment]
@darshankawar https://github.com/flutter/flutter/issues/153150 seems like a bug in `Navigator` code and I also mention the possible fix there (and yes, https://github.com/flutter/flutter/issues/153122#issuecomment-2276664427 looks like the solution) .
https://github.com/flutter/flutter/issues/153150 and this one are about different things. But https://github.com/flutter/flutter/issues/153150 makes it impossible to implement the idea proposed by @chunhtai in https://github.com/flutter/flutter/issues/153122#issuecomment-2276591945 for how to access the result when the page is popped using `Navigator`. And even if it worked, which I suppose it will soon enough, this doesn't fix my problem with the new API because it will make things more complex (look at the 'page proxy' idea mentioned here https://github.com/flutter/flutter/issues/153122#issuecomment-2276750121, vs just getting the result in the callback, as it used to be).
Hope this helps.

**Comment by chunhtai** [comment]
The reason for this change is onPopPage doesn't work with popscope and android predictive back. android predictive back needs to know whether navigator can be pop before the pop was called. Therefore any veto mechanism does not work unless we always assume it can't be popped, but that means we permanently disable predictive back.

The onDidRemovePage and onPopInvokedWithResult API is not likely to change, but I will try to figure out if there is a better way to inject library code into pages.

**Comment by wujek-srujek** [comment]
I understand why this change was done (the veto stuff), and I agree that it is for the better.
But, could you explain why you think that passing the value that `Navigator.pop` was called with to `Navigator.onPopInvoked` has anything to do with the veto mechanism that you wanted gone? It's a genuine question, I see no relation between the two and your rationale makes no sense to me, but I've been wrong before and I don't know the Flutter internals.
For the time being, we decided to not update to the new API and set an ignore, because it breaks our code and would otherwise require a rule ('don't use `Navigator.pop`) that we don't yet want to impose.

Do you have any comment to this?
> Another issue is the other way round - if I pop a route with my custom navigation solution, and its Page has the onPopInvoked callback defined, it is always called with null result. It makes sense, Flutter (as of now) can't know what my navigation solution resolved the Future with. I think this might be a source of many bugs as well.

I think this behavior should at least be documented.

**Comment by wujek-srujek** [comment]
> > I think this might be a source of many bugs as well.
> 
> Can you elaborate?

I mean that removing pages with custom navigators (like in my case) does result in a call to `Page.onPopInvoked` if it is defined for the page, but the code in that callback doesn't see the result. People might not know this and hunt for bugs why their dialog or whatever doesn't return the value they expect. That's why I also wrote that my feeling is that it is a bad idea to use both custom navigators and e.g. `Navigator.pop` in the same app - because obviously the integration is not as deep as Flutter documentation makes it seem (in my opinion).

**Comment by chunhtai** [comment]
>  if it is defined for the page, but the code in that callback doesn't see the result. People might not know this and hunt for bugs why their dialog or whatever doesn't return the value they expect

I am not too concern about this. This is already the case in Navigator API, you will only get result if you programmatically call Navigator.pop(). Things like cupertino backswipe and android back button or other mechanism will pop the page with null. So it is no worse than people do
```dart
var myResult = await showDialog();
```

they will just have to deal with the result being null that dialog may be removed not in the way they are expected.

Something to think about is whether the custom navigation method should include some way to accept a result that will be send to onPopInvoke.

**Comment by wujek-srujek** [comment]
Of course, I know they have to deal with nulls (the type system forces them anyway as they get `Future<Foo?>`), but in cases like this it is expected to be null as it's the platform that does the popping as a result of e.g. a gesture, not explicit code. I'm talking about the precedent where people do actively pop in code with a result in their, only for the callback not to see the value. You surely acknowledge that it is a different use case and can be considered unexpected by programmers?

**Comment by chunhtai** [comment]
> I'm talking about the precedent where people do actively pop in code with a result in their, only for the callback not to see the value. You surely acknowledge that it is a different use case and can be considered unexpected by programmers?

Making sure I understand. so user uses `Navigator.pop(result)` but somehow it go through a library code path and it drop the result somewhere?

or do you meant the a custom navigation `myCustomPop(result)` and you are not sure how to wire that result to the Page.onPopInovked?

I think in either cases, the fix will be on the library side. If any of the current API blocks you from doing it correctly, can you provide a some sample code that demostrate what are you trying to do?

**Comment by wujek-srujek** [comment]
Ok, let me summarize it here to the best of my abilities and understanding of the issue.

We have a custom navigation solution implemented using `Router`, let's call it `MyNav`; this solution returns `Future`s when pages are added (e.g. with `MyNav.push`), and the `Future`s are completed when the pages are removed with `MyNav` (e.g. with `MyNav.pop`), possibly with a value.
Then there is the `Navigator`, with its `push` returning a `Future` and `pop` completing it, possibly with a value.

1. When code adds a page using `MyNav.push`, and then uses `Navigator.pop` to pop the route corresponding to that page - the `Navigator. onDidRemovePage` callback is invoked, but it doesn't specify the value passed to `Navigator.pop`, making it hard for `MyNav` developers to complete their `Future` with the result. The previous API, `Navigator.onPopPage`, now deprecated, made the value available by passing it as a parameter. With the new API, we need a new mechanism to get the value, for example we need to specify `Page.onPopInvoked` (it needs to be fixed first, see https://github.com/flutter/flutter/issues/153150). But this makes it hard because `MyNav` might accept `Page`s from client code, so it needs to introduce some kid of wrapper/proxy, to be able to get the value and use it to resolve its internal `Future`. Not ideal, more work for `MyNav` (and any other custom navigation solutions based on `Router`) maintainers, and it used to be very simple.
1. When code adds a page using `MyNav.push` and then pops using `MyNav.pop` and specifies a value, `Page.onPopInvoked` is called (again, assuming the bug is fixed). But because this callback is invoked by `Navigator`, which has no idea about the `Future`s handled by `MyNav`, the result passed to `Page.onPopInvoked` is always `null`, even though the route is actually popped with a value.

To fix 1. (which this issue is about), if Flutter decides to fix it, we can either get a 'value' parameter in the new callback, or some other solution. The current idea for the other solution is some kind of `Page` proxying, or another idea to allow `MyNav` to 'inject' code to `Page` so that it can somehow get the value. The latter seems like a bad idea to me, since a working solution is very simple (the aforementioned parameter for the value), IMHO we don't need yet another 'delegate' for the `Router` or something of similar caliber.
To fix 2. (which the original issue is not about, it just came up while I was testing stuff), we also need some kind of an API, so that `MyNav` can give `Navigator` the value, so that `Page.onPopInvoked` 'sees' the value.

Ideally, we get a fix for both 1. and 2.

> I think in either cases, the fix will be on the library side

I understand and agree, but Flutter would need to provide an API for `MyNav` to call or implement, or any other way to make the value somehow visible to `Navigator`, so that it can invoke `Page.onPopInvoked` with it. Right now I don't think this is possible, or complicated and not obvious.

Until the fixes are available, I find it a bit disingenuous of Flutter to say that using `Router` and `Navigator` together works fine (https://docs.flutter.dev/ui/navigation#using-router-and-navigator-together). It might seem that it works at a very high level and in trivial examples, but once you start getting more involved, you discover caveats and pitfalls, mainly about the result seen by one or the other. Flutter documentation should at least mention them, and possibly even warn developers to not mix the two APIs (e.g. push with `MyNav` and pop with `Navigator`, because the value gets lost), instead as of righ now kind of promoting it. Similarly, the documentation (https://api.flutter.dev/flutter/widgets/Page/onPopInvoked.html, or maybe https://api.flutter.dev/flutter/widgets/PopInvokedWithResultCallback.html) should mention that the `result` might not contain the value, depending on what you push with and how you pop. Rigth now all it says `The result contains the pop result.`, which we by now know is not always true.

For the sake of this discussion and to make things simple, `MyNav` has `push` and `pop`. It might actually contain completely different APIs, but let's not complicate things.

**Comment by darshankawar** [comment]
Labeled for continued discussion / tracking.

**Comment by chunhtai** [comment]
I don't have much else to add for 1 since I don't have a solution yet.

for 2, if the Page.onPopInvoked is called, that means somehow Navigator.pop or maybepop is called as a result of MyNav.pop. In the case why didn't it pass the result from MyNav.pop to Navigator.pop

**Comment by wujek-srujek** [comment]
> for 2, if the Page.onPopInvoked is called, that means somehow Navigator.pop or maybepop is called as a result of MyNav.pop.

If you are saying that the code is intentionally calling `Navigator.pop/maybePop` somewhere, this is not the case, see the sample at the end. All it does it it manipulates a `List<Page>`.

>  In the case why didn't it pass the result from MyNav.pop to Navigator.pop

Is it a rhetorical question, or a question to me why I didn't pass the value to `Navigator.pop`? If the latter, the answer is easy - I never use `Navigator.pop`, so how can I pass the value to it?

Please see the repro below - the code is almost the same as in https://github.com/flutter/flutter/issues/153150, with the addition of a few `print` statements. Of course, you need to fix the typing as mentioned in the other issue for `Page.onPopInvoked` to not throw.

What the sample does:
- A custom push, and awaits on the result (this is what I call `MyNav.push`).
- A custom pop with a result. (`MyNav.pop`).
- Prints the result it gets after the await.
- Prints the result that `Page.onPopInvoked` sees.
- It doesn't use the `Navigator` directly anywhere, except for creating it in the custom `RouterDelegate`.

You will see in the logs (filter for `<<<>>>`) that the result after the awaited push is a string, yet it is `null` in `Page.onPopInvoked`. This is inconsistent, I would expect the latter to also report the correct value. As I mentioned, I understand why it works this way (`Navigator` has no idea about the `Future`s managed by `MyNav`). But there should be a way to make it work; maybe there is and I just don't know it yet? But if not, it is another edge case that Flutter should make devs aware of.

<details open><summary>Code sample</summary>

import 'dart:async';

import 'package:flutter/material.dart';

Page<String> _createPage<String>(Widget child) {
  return MaterialPage<String>(
    child: child,
    onPopInvoked: (didPop, result) {
      print("<<<>>> Result in 'onPopInvoked': $result");
    },
  );
}

final _routerDelegate = _RouterDelegate()
  ..push(_createPage(_FirstPageWidget()));
final _routerConfig = RouterConfig<Uri>(
  routerDelegate: _routerDelegate,
);

void main() {
  runApp(
    MaterialApp.router(
      routerConfig: _routerConfig,
    ),
  );
}

class _FirstPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            final result = await _routerDelegate.push(
              _createPage(_SecondPageWidget()),
            );

            print('<<<>>> Result after push/pop: $result');
          },
          child: const Text('Push'),
        ),
      ),
    );
  }
}

class _SecondPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () => _routerDelegate.pop('FooBarBazQux'),
          child: const Text('Pop'),
        ),
      ),
    );
  }
}

class _RouterDelegate extends RouterDelegate<Uri> with ChangeNotifier {
  List<Page<String>> _pages = [];
  final Map<Page<String>, Completer<String?>> _pageCompleters = Map.identity();

  @override
  Widget build(BuildContext context) {
    return Navigator(
      onDidRemovePage: _pages.remove,
      pages: _pages,
    );
  }

  Future<String?> push(Page<String> page) {
    _pages = [..._pages..add(page)];
    final completer = Completer<String?>();
    _pageCompleters[page] = completer;

    notifyListeners();

    return completer.future;
  }

  void pop(String? result) {
    final page = _pages.removeLast();
    _pages = [..._pages];
    final completer = _pageCompleters.remove(page);

    completer?.complete(result);

    notifyListeners();
  }

  @override
  Future<bool> popRoute() => throw StateError('irrelevant for this repro');

  @override
  Future<void> setNewRoutePath(Uri configuration) =>
      throw StateError('irrelevant for this repro');
}

</details>

**Comment by wujek-srujek** [comment]
Maybe `Page.onPopInvoked` reporting `null` using the sample above should be an issue of its own?

**Comment by chunhtai** [comment]
Ah I see what is going on now, you are current that even by just modifying the page list, the TransitionDelegate will do a RouteTransitionRecord.markForPop on the last page which will in term call onPopInvoked.

So it makes sense that the onpopinvoked is called even if you just modifying the page list to remove the last entry, but call it does uses pop to remove the last entry in the navigator.

You can fix this by creating a transitionDelegate, or just copy over the implementation and replace
```
exitingPageRoute.markForPop(exitingPageRoute.route.currentResult);
```

with something like

```
exitingPageRoute.markForPop(myPopResult);
```

**Comment by wujek-srujek** [comment]
> However why did you just call Navigator.pop instead in this case?

Because if I do, the `Future` awaited in the `push` button handler will never be resolved, right? And `MyNav` supports `pop` so why wouldn't I use it? Also, it does more things than just the `pop`, that I need done, which `Navigator.pop` has no idea about. It just makes sense to me.

That's one of the points I'm trying to make - there are many things that do not work as I (and possibly others) would expect if we mix `Router`-based custom `MyNav` with `Navigator.push/pop`. They will be difficult to track down, documentation isn't always helpful, and Flutter is advertising this way of programming as 'designed to work together'. But it is just too edge-casey IMHO.

I looked into `go_router` and it also manages its own `Future`s, I think that package has the issues mentioned in this post, but I guess people didn't come across them yet, or they did, and their fix was to just not mix `go_router` calls with `Navigator` calls and never reported back here. Or I'm blowing things out of proportion. But these things are breaking for us. (E.g. using `Navigator.pop` will cause the result value to never be seen, or require quite a bit of work, see the original issue in this thread.)

> You can fix this by creating a transitionDelegate, or just copy over the implementation and replace

Ok, I didn't now this, thank you very much, I need to look more into this delegate. 
What I do know, though, is that I didn't want to touch the `TransitionDelegate` for as long as I could, this is way over my head in terms of complexity (and I know I'm not the only one, I've seen a lot of issues and discussion about it, and other `Router`-related APIs).
And quite honestly, if the solution is to copy the code from Flutter, which is about 60 lines of dense, difficult (for me) code - I think something is not right here.

> with something like
```dart
exitingPageRoute.markForPop(myPopResult);
```

How do I even get `myPopResult` inside the `TransitionDelegate` instance to use if for the `markForPop` call?

> I wouldn't consider current behavior to be a bug though.

You might not, and you might be right. But it is definitely a gotcha and unexpected behavior (`Page.onPopInvoked` reports `null` result even though I did pop it with a value, and other parts of the code see it.). Especially since https://api.flutter.dev/flutter/widgets/PopInvokedWithResultCallback.html says 'The result contains the pop result.' It should at least say 'The result contains the pop result but only if popped with `Navigator.pop`, or your custom `TransitionDelegate` passes the result to `exitingPageRoute.markForPop`; otherwise it is `null`.'

**Comment by wujek-srujek** [comment]
> You can fix this by creating a transitionDelegate, or just copy over the implementation and replace
> 
> ```
> exitingPageRoute.markForPop(exitingPageRoute.route.currentResult);
> ```
> 
> with something like
> 
> ```
> exitingPageRoute.markForPop(myPopResult);
> ```

You are maybe forgetting that the `TransitionDelegate` could (should?) be something that users of the package define? If they want custom animations, they will define their own delegate and give it to my package, and then that would break my custom code that knows what to `markForPop` with, right? Kind of the same situation as with `Page` possibly being passed form client code and making it hard for me to implement `Page.onPopInvoked` the way I want (as I have no control over what `Page` is in my package, see above for more details about that part of the discussion).

**Comment by chunhtai** [comment]
> Because if I do, the Future awaited in the push button handler will never be resolved, right? And MyNav supports pop so why wouldn't I use it?

nvm I think I know why you do it this way. I originally meant why didn't the MyNav.pop calls Navigator.pop directly. but them you will run into issue to where you can't extract the result from onDidRemovePage or inject the code into Page.onPopInvoked

I really want to have a way to be able to create a proxy Page similar to how widget can wrap another widget. I have run into issues where I want to host an inherited widget for a user provided page.

Let me think a bit more.

> You are maybe forgetting that the TransitionDelegate could (should?) be something that users of the package define?

I would very interested in seeing use cases for these, like you said this is kind of complex and low level API and it is something that will likely be abstract away in a routing library.

> If they want custom animations, they will define their own delegate and give it to my package

For custom animation, they will likely use a PageRouteBuilder or Custom page that provide animationbuilder.

Since flutter is opensource, everything is possible. So I am just speculating here. However, I usually would only consider this as a problem if we really run into a real world use case; otherwise, it will be impossible to do anything.

**Comment by wujek-srujek** [comment]
> > You are maybe forgetting that the TransitionDelegate could (should?) be something that users of the package define?
> 
> I would very interested in seeing use cases for these, like you said this is kind of complex and low level API and it is something that will likely be abstract away in a routing library.

One use case is to disable animated transitions completely, globally. There is even a Flutter snippet in the official documentation on how to do it: https://api.flutter.dev/flutter/widgets/TransitionDelegate-class.html.

In my project, we have nested navigation, and we use different delegates for both levels. We consider specifying the `TransitionDelegate` to be the task for client code - as only this code knows what it really wants. The routing package can't possibly know all types of things their clients might want to do, so it can't have transition delegates for all situations.

> > If they want custom animations, they will define their own delegate and give it to my package
> 
> For custom animation, they will likely use a PageRouteBuilder or Custom page that provide animationbuilder.
> 
> Since flutter is opensource, everything is possible. So I am just speculating here. However, I usually would only consider this as a problem if we really run into a real world use case; otherwise, it will be impossible to do anything.

Looking for a solution to the original issue (`Navigator.onDidRemovePage` not making the result visible), which is breaking for us, you suggested using `Page.onPopInvoked`. But it has its own issues (the typing bug and the pop result not visible there). To me it seems real world enough, but I might be biased because it breaks (or rather, doesn't help fix) my code.

For us, to make everything work again, the fix will be one of: A. implementing more code in our routing package so that we make it work once Flutter makes it possible, or B. banning direct `Navigator` usage as it isn't reliable, or C. not migrating to the new API, for as long as the old one exists.

'C' will break at some point (the deprecated API will be removed), and it might start having its own issues as Flutter is moving away from it and adds features that don't get ported to work with the old API. 'A' should be reasonably easy for us to pick it up; it might be possible right now, but not obvious, and I don't want to create `Page` wrappers/proxies just to get the value. It is much easier to just pick 'B' and ban `Navigator`.

And this brings me full circle to what I'm also advocating for in this issue - better and more transparent documentation that these edge cases do exist when one mixes custom routing and `Navigator`.

**Comment by lukaszciastko-spica** [comment]
I believe we have a similar approach in our application. I’ve implemented a custom navigator that wraps around the router, exposing all the default `push` and `pop` methods for our custom Route types. This setup integrates seamlessly with the existing Navigator, allowing us to handle standard actions like displaying dialogs.

In the custom Navigator, I define a stack like this:

```dart
final stackEntries = <StackEntry>[];
```

To construct pages, I use the following approach:

```dart
pages: [
  for (final entry in stackEntries)
    MaterialPage(
      arguments: entry.arguments,
      ...
    ),
]
```

Previously, my logic for handling `popPage` was as follows:

```dart
onPopPage: (route, result) {
  // Handle standard routes, e.g., dialogs:
  if (!route.didPop(result)) {
    return false;
  }
  
  // Handle custom stack entries:
  if (stackEntries.isNotEmpty && stackEntries.length > 1) {
    stackEntries.last.completer?.complete(result);
    stackEntries.removeLast();
  }

  _notify();

  return true;
},
```

Now, as I transition to the new solution and incorporate your suggestions, it seems all I need to do is leave the `onDidRemovePage` method empty:

```dart
onDidRemovePage: (_) {
  // Do nothing.
},
```

Then, I can move the logic for handling custom entries into the `MaterialPage`:

```dart
MaterialPage(
  arguments: entry.arguments,
  onPopInvoked: (didPop, result) {
    if (didPop) {
      entry.completer?.complete(result);
      stackEntries.remove(entry);
      _notify();
    }
  },
```

I haven’t run all the E2E tests yet, but I’m optimistic that this approach will work as expected.

**Comment by wujek-srujek** [comment]
Siemanko.

We discussed all of this already in this thread.

Your approach will work, but only when https://github.com/flutter/flutter/issues/153150 is fixed, I believe, you should really run you E2E test ;>

But your code snippets are showing exactly what I'm arguing. How useful is this code?
```dart
onDidRemovePage: (_) {
  // Do nothing.
},
```
You have to specify it but do nothing? Probably because you don't have all the information. It also looks pretty confusing. And instead you have to do this:
```dart
MaterialPage(
  arguments: entry.arguments,
  onPopInvoked: (didPop, result) {
    if (didPop) {
      entry.completer?.complete(result);
      stackEntries.remove(entry);
      _notify();
    }
  },
```
You basically moved the code that performs the pop away from the central place - the `Navigator` (possibly because the new API is not giving you all the information you need) - and instead you put it in every `Page`. Which is a) more code, b) a bit confusing - why do it in the page, not in the Navigator callback, and c) limiting.

By 'limiting' I mean that now your clients (code that is using your custom navigation) need to specify `onPopInvoked` the way your custom navigation expects it to, or otherwise it all won't work. Or they are forced to use your predefined `Page` superclass or factory function - because the page relies on `onPopInvoked` to be very specifically implemented, even using a private `_notify` function. I understand that it works for your app, what I'm talking about here is a general-purpose package which accepts `Page`s of any type, shape or form, from client code, so you can't assume anything about their `Page.onPopInvoked`. One solution, already discussed in this thread, would be to 'proxy' the pages you get from the outside and provide your special `onPopInvoked` - but this is much more work that just have `Navigator.onDidRemovePage` do the right thing with all the information, including the result.
