### ISSUE TITLE
[go_router] Using GoRouter.routingConfig and switch between StatefulShellRoute and GoRoute will cause type error

### ISSUE THREAD

**Issue by evan361425** [flutter/flutter#153258]
### Steps to reproduce

Reproducible in go_router `14.2.3`

In mobile device, we use bottom nav bar, something like:

```dart
final mobileConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: route1Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: route2Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: route3Builder)]),
    ],
  ),
  GoRoute(path: '/route4', builder: route4Builder),
  GoRoute(path: '/route4', builder: route5Builder),
]);
```

In desktop device, we use rail, which allow more branches:

```dart
final desktopConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: route1Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: route2Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: route3Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route4', builder: route4Builder)]),
      StatefulShellBranch(routes: [GoRoute(path: '/route5', builder: route5Builder)]),
    ],
  ),
]);
```

When we monitor device width and change the routing config from `mobileConfig` to `desktopConfig`, it will cause error:

```
type 'ShellRouteMatch' is not a subtype of type 'RouteMatch' of 'value'
```

1. First use `mobileConfig` by setting device to portrait
2. Nav to `/route5`
3. Turn the device to landscape
4. Error show up

### Expected results

Still stay in `/route5` without any error.

### Actual results

Throw the error and stop changing route config:

```
════════ Exception caught by foundation library ════════════════════════════════
The following _TypeError was thrown while dispatching notifications for ValueNotifier<RoutingConfig>:
type 'ShellRouteMatch' is not a subtype of type 'RouteMatch' of 'value'

When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart:277:14)
growable_array.dart:277
#1      RouteMatchList._createNewMatchUntilIncompatible (package:go_router/src/match.dart:623:10)
match.dart:623
#2      RouteMatchList.push (package:go_router/src/match.dart:593:16)
match.dart:593
#3      RouteConfiguration.reparse (package:go_router/src/configuration.dart:328:23)
configuration.dart:328
#4      GoRouter._handleRoutingConfigChanged (package:go_router/src/router.dart:298:27)
router.dart:298
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
change_notifier.dart:433
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
change_notifier.dart:555
#7      App.build (package:example/app.dart:30:20)
app.dart:30
#8      StatelessElement.build (package:flutter/src/widgets/framework.dart:5557:49)
framework.dart:5557
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:15)
framework.dart:5487
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
framework.dart:5203
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
framework.dart:2905
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
binding.dart:1136
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
binding.dart:443
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
binding.dart:1313
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#20     _invoke (dart:ui/hooks.dart:314:10)
hooks.dart:314
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#22     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 3 frames from dart:async)

The ValueNotifier<RoutingConfig> sending notification was: ValueNotifier<RoutingConfig>#ac657(Instance of 'RoutingConfig')
════════════════════════════════════════════════════════════════════════════════
```

### Code sample

<details open><summary>Code sample</summary>

```dart
class App extends StatelessWidget {
  final routingConfig = ValueNotifier<RoutingConfig>(mobileConfig);

  App({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraint) {
        routingConfig.value =  constraint.width < 600 ? mobileConfig : desktopConfig;
        return MaterialApp.router(
          routerConfig: routingConfig.value,
        );
      },
    );
  }
}

final mobileConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: createBuilder('route1'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: createBuilder('route2'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: createBuilder('route3'))]),
    ],
  ),
  GoRoute(path: '/route4', builder: createBuilder('route4')),
  GoRoute(path: '/route4', builder: createBuilder('route5')),
]);
final desktopConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: createBuilder('route1'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: createBuilder('route2'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: createBuilder('route3'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route4', builder: createBuilder('route4'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route5', builder: createBuilder('route5'))]),
    ],
  ),
]);

Widget Function(BuildContext, GoRouterState) createBuilder(String name) {
  return (ctx, state) => Scaffold(body: Text(name));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v                             Sun Aug 11 10:36:21 2024
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-TW)
    • Flutter version 3.22.1 on channel stable at /Users/evan.lu/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 months ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/evan.lu/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 127.0.6533.100

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@evan361425 
Can you provide complete runnable code sample ? It seems to have custom implementation.

<details>
<summary> code </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  final routingConfig = ValueNotifier<RoutingConfig>(mobileConfig);

  App({super.key});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraint) {
        routingConfig.value =  constraint.width < 600 ? mobileConfig : desktopConfig;
        return MaterialApp.router(
          routerConfig: routingConfig.value,
        );
      },
    );
  }
}

final mobileConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: createBuilder('route1'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: createBuilder('route2'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: createBuilder('route3'))]),
    ],
  ),
  GoRoute(path: '/route4', builder: createBuilder('route4')),
  GoRoute(path: '/route4', builder: createBuilder('route5')),
]);
final desktopConfig = RoutingConfig(routes: [
  StatefulShellRoute.indexedStack(
    builder: builder,
    branches: [
      StatefulShellBranch(routes: [GoRoute(path: '/route1', builder: createBuilder('route1'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route2', builder: createBuilder('route2'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route3', builder: createBuilder('route3'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route4', builder: createBuilder('route4'))]),
      StatefulShellBranch(routes: [GoRoute(path: '/route5', builder: createBuilder('route5'))]),
    ],
  ),
]);

Widget Function(BuildContext, GoRouterState) createBuilder(String name) {
  return (ctx, state) => Scaffold(body: Text(name));
}

```

</details>

**Comment by evan361425** [comment]
@darshankawar thanks for the replied. I've update the code sample, please take a look.

**Comment by darshankawar** [comment]
Thanks for the update. Seeing the same behavior using updated code sample and running in emulator.

```
======== Exception caught by foundation library ====================================================
The following _TypeError was thrown while dispatching notifications for ValueNotifier<RoutingConfig>:
type 'ShellRouteMatch' is not a subtype of type 'RouteMatch' of 'value'

When the exception was thrown, this was the stack: 
#0      List.add (dart:core-patch/growable_array.dart:278:14)
#1      RouteMatchList._createNewMatchUntilIncompatible (package:go_router/src/match.dart:623:10)
#2      RouteMatchList.push (package:go_router/src/match.dart:593:16)
#3      RouteConfiguration.reparse (package:go_router/src/configuration.dart:328:23)
#4      GoRouter._handleRoutingConfigChanged (package:go_router/src/router.dart:298:27)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437:24)
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:559:5)
#7      Example.build.<anonymous closure> (package:new_web_app/main.dart:18:23)
#8      _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:196:77)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3046:19)
#10     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:236:12)
#11     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738:59)
#12     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108:15)
#13     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738:14)
#14     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:283:5)
#15     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:374:5)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2627:7)
#17     RenderView.performLayout (package:flutter/src/rendering/view.dart:285:12)
#18     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2465:7)
#19     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1062:18)
#20     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1075:15)
#21     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:609:23)
#22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178:13)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#27     _invoke (dart:ui/hooks.dart:312:13)
#28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#29     _drawFrame (dart:ui/hooks.dart:283:31)
The ValueNotifier<RoutingConfig> sending notification was: ValueNotifier<RoutingConfig>#622f0(Instance of 'RoutingConfig')
====================================================================================================

```

**Comment by evan361425** [comment]
I've fixed the error locally by changing [this line](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/match.dart#L606):

```dart
final List<RouteMatchBase> newMatches = currentMatches.toList();
```

to

```dart
final List<RouteMatchBase> newMatches = currentMatches.cast<RouteMatchBase>().toList();
```

The problem is when `currentMatches` is an empty list, Dart seams to not cast correctly to `List<RouteMatchBase>`. Instead, it casts to `List<RouteMatch>`.
