### ISSUE TITLE
Error with flutter.groovy and flutter.bat

### ISSUE THREAD

**Issue by ilyesksr** [flutter/flutter#153242]
### Steps to reproduce

1-running "flutter build apk" command 

### Actual results

i get this error 
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1687

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

### Logs

<details open>
<summary>This the result of running flutter run -v</summary>

```console

[ +149 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] executing: C:\Users\ksr\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +81 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] No supported devices connected.
[   +3 ms]
           The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
           Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.

[  +10 ms] "flutter run" took 305ms.
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:634:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1710:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[ +215 ms] ensureAnalyticsSent: 212ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1


```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (12 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ksr\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.92.1)
    • VS Code at C:\Users\ksr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.


```

</details>

**Comment by iapicca** [comment]
> [  +83 ms] No supported devices connected.

the `flutter run` logs are not pointing at anything,
maybe the full logs of `flutter build apk -v` could help (maybe as a .log)

**Comment by darshankawar** [comment]
@ilyesksr 
As suggested above, please run in verbose mode and check if it throws any meaningful error that we can use to analyze further. If so, provide the same in properly formatted text.

**Comment by ilyesksr** [comment]
> @ilyesksr As suggested above, please run in verbose mode and check if it throws any meaningful error that we can use to analyze further. If so, provide the same in properly formatted text.

Here is the output of running flutter build apk -v :
[build_output.txt](https://github.com/user-attachments/files/16603302/build_output.txt)

**Comment by ilyesksr** [comment]
> > [  +83 ms] No supported devices connected.
> 
> the `flutter run` logs are not pointing at anything, maybe the full logs of `flutter build apk -v` could help (maybe as a .log)

Here is the output of running flutter build apk -v :
[build_output.txt](https://github.com/user-attachments/files/16603306/build_output.txt)

**Comment by ilyesksr** [comment]
the previews flutter build apk -v said that :
`flutter : [   +4 ms] [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app 
<app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.`

so i make a new project and copy assets, code and pubspect.yaml and now i get this error output:
[build_output.txt](https://github.com/user-attachments/files/16603819/build_output.txt)

**Comment by darshankawar** [comment]
> so i make a new project and copy assets, code and pubspect.yaml and now i get this error output:
> [build_output.txt](https://github.com/user-attachments/files/16603819/build_output.txt)

It shows below log:

```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following 
locations:

RemoteException
    + FullyQualifiedErrorId : NativeCommandError

```

```
Target aot_android_asset_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with 
--no-tree-shake-icons.
```

Try to follow `build again with 
--no-tree-shake-icons.` and see if it helps in your case or not.

**Comment by ilyesksr** [comment]
After i tried `flutter build apk --no-tree-shake-icons` and following this :
Deprecated imperative apply of Flutter's Gradle plugins steps :
[https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply#androidsettings-gradle](url)
it finally works, thank you all guys.
