### ISSUE TITLE
recipes-with-led presubmit fails because of outdated recipe dependency

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#153391]
On the recipes CL: https://flutter-review.googlesource.com/c/recipes/+/59120?tab=checks
On the build: https://ci.chromium.org/ui/p/flutter/builders/try/recipes-with-led/b8739689494104325889/infra

```
The recipe has crashed at point 'Uncaught exception'!

Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 597, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 1009, in run_steps
    recipe_result = invoke_with_properties(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 88, in invoke_with_properties
    return _invoke_with_properties(callable_obj, all_props, environ, prop_defs,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 52, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/recipes.py", line 119, in RunSteps
    api.recipe_testing.run_tests(checkout_path, SELFTEST_CL, opts)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipe_modules/recipe_testing/api.py", line 367, in run_tests
    self.m.commit_queue.all_tryjobs(
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/commit_queue/api.py", line 28, in all_tryjobs
    cfg = self._load(project, config_name=config_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/commit_queue/api.py", line 16, in _load
    return self.m.luci_config.commit_queue(project=project, config_name=config_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/luci_config/api.py", line 96, in commit_queue
    return self.fetch_config(config_name, cv_config_pb2.Config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/luci_config/api.py", line 56, in fetch_config
    textpb.Parse(text, cfg)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 709, in Parse
    return ParseLines(text.split(b'\n' if isinstance(text, bytes) else u'\n'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 786, in ParseLines
    return parser.ParseLines(lines, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 839, in ParseLines
    self._ParseOrMerge(lines, message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 864, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 997, in _MergeField
    merger(tokenizer, message, field)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 1072, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 997, in _MergeField
    merger(tokenizer, message, field)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 1072, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 997, in _MergeField
    merger(tokenizer, message, field)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 1072, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 997, in _MergeField
    merger(tokenizer, message, field)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 1072, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 997, in _MergeField
    merger(tokenizer, message, field)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 1072, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/chrome-bot/.cache/.vpython-root/store/python_venv-qd5invqojaf9hbipbv7ni5877k/contents/lib/python3.11/site-packages/google/protobuf/text_format.py", line 962, in _MergeField
    raise tokenizer.ParseErrorPreviousToken(
google.protobuf.text_format.ParseError: 28:11 : Message type "cv.config.Verifiers.Tryjob.Builder.LocationFilter" has no field named "gerrit_ref_regexp".
```

I suspect this is due to our recipes being out of date: https://github.com/flutter/flutter/issues/151137

**Comment by christopherfujino** [comment]
@athomas does this by any chance look familiar, from your time dealing with manually rolling Dart recipes? I'm guessing that I'll have to roll Flutter's DEPS without recipes-with-led :'(

**Comment by athomas** [comment]
No, nothing I had to deal with (I don't think we have any recipes interacting with luci config that way). But it looks indeed like a consequence of outdated recipe deps. The field was recently added to the CV config protos [1]. Specifically, you're missing [2].

[1]: https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/5753810
[2]: https://chromium.googlesource.com/infra/luci/recipes-py/+/2fce2a15ca35063f0344117d8069111fc4b9da2b

**Comment by christopherfujino** [comment]
> No, nothing I had to deal with (I don't think we have any recipes interacting with luci config that way). But it looks indeed like a consequence of outdated recipe deps. The field was recently added to the CV config protos [1](https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/5753810). Specifically, you're missing [2](https://chromium.googlesource.com/infra/luci/recipes-py/+/2fce2a15ca35063f0344117d8069111fc4b9da2b).

Thanks for tracking these down!

**Comment by christopherfujino** [comment]
Assigning to myself to roll to https://chromium.googlesource.com/infra/luci/recipes-py/+/2fce2a15ca35063f0344117d8069111fc4b9da2b

**Comment by christopherfujino** [comment]
This has been resolved after a herculean effort from athomas
