### ISSUE TITLE
Installation failed when a path includes special characters

### ISSUE THREAD

**Issue by graddotdev** [flutter/flutter#15332]
## Steps to Reproduce

```
$ pwd
/Volumes/Hard disk drive #1/Code

$ git clone -b beta https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Counting objects: 114951, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 114951 (delta 0), reused 0 (delta 0), pack-reused 114948
Receiving objects: 100% (114951/114951), 34.72 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (85931/85931), done.

$ export PATH=`pwd`/flutter/bin:$PATH

$ flutter doctor
Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.3M  100 43.3M    0     0  8075k      0  0:00:05  0:00:05 --:--:-- 9352k
Building flutter tool...
vm-service: Error: Unhandled exception:
Unsupported operation: Cannot extract a file path from a URI with a fragment component
#0      _Uri.toFilePath (dart:core/uri.dart:2597)
#1      _loadFile (loader.dart:427:26)
#2      _handleResourceRequest (loader.dart:512:7)
#3      _processLoadRequest (loader.dart:1017:9)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
![screen shot 2018-03-09 at 11 25 38](https://user-images.githubusercontent.com/4836709/37198542-bb47c82e-238f-11e8-80f6-7066998e81c5.png)

**Comment by Hixie** [comment]
@a-siva It looks like Dart itself isn't property encoding the path when it turns it into a URL?

**Comment by bkonyi** [comment]
It looks like we're passing the `#` of the path to `Uri.parse` without percent encoding it. `#` represents a fragment in a URI, so `Uri.parse` can't tell that the `#` is part of the directory name.

**Comment by bkonyi** [comment]
Potential fix in [this CL](https://dart-review.googlesource.com/c/sdk/+/63303).

**Comment by lrhn** [comment]
As mentioned on the CL, the mistake is using `Uri.parse`. Instead use [`Uri(path: ...)`](https://api.dartlang.org/stable/1.24.3/dart-core/Uri/Uri.html) or, more likely, [`Uri.file(filePath)`](https://api.dartlang.org/stable/1.24.3/dart-core/Uri/Uri.file.html).

Or just don't store file paths in a `Uri`.

**Comment by bkonyi** [comment]
While I was working to resolve this by passing file paths as strings in `loader.dart`, I ran into instances in the frontend that also throw exceptions due to this path containing a #. It seems to be a common pattern to keep all path-like state as instances of `Uri`, often created using `Uri.parse`, throughout the SDK so I think it's likely we'll run into this issue all over the place.

Personally, I would prefer to update `Uri.toFilePath` to not throw an exception if the `Uri` has a fragment and instead return the path including the fragment since calling `Uri.toFilePath` makes it clear that the user expects that the `Uri` is a file path in the first place. This is a rather simple fix, but the # should technically be escaped as per the URI spec. 

The only other solutions I can think of here is to go find all the uses of `Uri.parse` and add additional checks so the correct `Uri` constructor is used, or update `Uri.parse` to escape these sorts of characters if the argument contains `file://` or no scheme. What are your thoughts @lrhn?

**Comment by bkonyi** [comment]
Friendly ping @lrhn

**Comment by lrhn** [comment]
My thoughts are split in two directions.
It's clear that the `Uri` class isn't working the way people are using it. It was never intended to work that way, but it suggests that the usability is bad when it's not obvious when you are using the class incorrectly.
There are two solutions. Either we embrace the way it's being used, or we double down on making it hard to use the class incorrectly. The latter is hard since the current way it's being used is a *valid* use, just not with the semantics the user expects.

You can use `Uri.parse` for an input which can be either a file path or a URI, and for relative paths on non-Windows, you can't even tell the difference. It just breaks down for inputs which are Windows file paths or which contains "?" or "#" as characters (at least Windows paths can't contain "/" as a character!), but that's rare enough the people likely won't find the bug.

The safest thing to do is probably to allow and include query and fragment in the output of `Uri.toFIlePath`, like we do for `data:` URIs. I'm sure there are still ways that parsing can break paths (like normalizing `%` escapes).

In the long run, if we get a new `Uri` class implementation, then we should just store the input verbatim and parse it lazily, like the JavaScript URL class does (which will make it easier to reuse that).

**Comment by bkonyi** [comment]
Thanks for the thorough response @lrhn. Just to make sure I understand, we still don't want to change the `Uri.toFilePath` implementation right? If that's the case, is the resolution to this issue to specify that Flutter does not support paths which contain `#` on Windows? I know that we would ideally update our code to properly use the `Uri` class, but I'm afraid that rabbit hole is quite deep as well and would require changes throughout many of our libraries. What are your thoughts?

**Comment by Hixie** [comment]
We should be using `Uri.file()` in `flutter_tools` when creating `Uri`s from file paths. If we don't, that's a bug, and we should fix it.

**Comment by Hixie** [comment]
(Same with the VM or wherever this error is coming from.)

**Comment by bkonyi** [comment]
@Hixie it actually looks like we use `Uri.parse` all over the place throughout the Dart SDK. I've run into at least a few instances in the CFE where this causes issues and I'm fairly certain there's multiple other callsites that would also not be able to handle a path with a `#`.

**Comment by Hixie** [comment]
Time for an audit? :-)

**Comment by lrhn** [comment]
I think the safest is to open a bug saying that Flutter (and Dart in general) currently doesn't handle paths with `#` or `?` in them, and then work towards fixing it ASAP.

**Comment by bkonyi** [comment]
Even if we addressed this in the Flutter tool, this is going to be an issue throughout the Dart + Flutter tooling ecosystem. We need to find a more general solution for this, but that likely needs to happen in the Dart SDK.
