### ISSUE TITLE
Unable to execute flutter run on a clean project

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#15339]
## Steps to Reproduce

> Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

Can't use `flutter run` on a clean project after installing flutter. Please note that I am behind a **corporate proxy** which requires authentication. Moreover, the proxy signs every incoming certificates. My `.profile` is correctly set-up with the url and password, and Android Studio also have the correct configurations and is able to update itself. (I'm very disappointed that Android Studio doesn't use my `https_proxy` config, but that's out of subject.)

The error seems to be `Could not GET` and related to the network and the proxy. However, I am able to open the link in the error with Firefox and Chrome, proving that my configuration is correct.

Here's what we use : 
Squid 3.5.27 - https://www.freshports.org/www/squid
pfSense - https://www.pfsense.org/

If there's additional configurations that I need, I would appreciate a link to the appropriate documentation. Otherwise, if I can download the required files manually and place them in the project, it can be a viable temporary solution.

## Logs

> Run your application with `flutter run` and attach all the log output.

```Bash
flutter run -v
[  +28 ms] [/home/users/n.gendron/GitHub/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/home/users/n.gendron/GitHub/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/home/users/n.gendron/GitHub/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/users/n.gendron/GitHub/flutter/] git log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [/home/users/n.gendron/GitHub/flutter/] git log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[        ] [/home/users/n.gendron/GitHub/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.5-0-g3ea4d06
[ +141 ms] /opt/android-sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           05473ea90a673764       device usb:1-1.3.3 product:hammerhead model:Nexus_5 device:hammerhead transport_id:1
[ +174 ms] /opt/android-sdk/platform-tools/adb -s 05473ea90a673764 shell getprop
[  +95 ms] ro.hardware = hammerhead
[        ] ro.build.characteristics = nosdcard
[ +691 ms] Launching lib/main.dart on Nexus 5 in debug mode...
[   +7 ms] Initializing gradle...
[   +8 ms] Using gradle from /home/users/n.gendron/GitLab/n.gendron/techno_store/android/gradlew.
[  +77 ms] /home/users/n.gendron/GitLab/n.gendron/techno_store/android/gradlew -v
[ +673 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                   OS:           Linux 4.13.0-37-generic amd64
[   +1 ms] Resolving dependencies...
[        ] [android/] /home/users/n.gendron/GitLab/n.gendron/techno_store/android/gradlew app:properties
[+1395 ms]
                   FAILURE: Build failed with an exception.

                   * What went wrong:
                   A problem occurred configuring root project 'android'.
                   > Could not resolve all files for configuration ':classpath'.
                      > Could not resolve com.android.tools.build:gradle:3.0.1.
                        Required by:
                            project :
                         > Could not resolve com.android.tools.build:gradle:3.0.1.
                            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                               > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                         > Could not resolve com.android.tools.build:gradle:3.0.1.
                            > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                               > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

                   * Get more help at https://help.gradle.org

                   BUILD FAILED in 1s
[   +6 ms] * Error running Gradle:
           Exit code 1 from: /home/users/n.gendron/GitLab/n.gendron/techno_store/android/gradlew app:properties:

           FAILURE: Build failed with an exception.

           * What went wrong:
           A problem occurred configuring root project 'android'.
           > Could not resolve all files for configuration ':classpath'.
              > Could not resolve com.android.tools.build:gradle:3.0.1.
                Required by:
                    project :
                 > Could not resolve com.android.tools.build:gradle:3.0.1.
                    > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                       > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                          > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                 > Could not resolve com.android.tools.build:gradle:3.0.1.
                    > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                       > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
                          > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s

[  +22 ms] "flutter run" took 3,235ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:114)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81)
<asynchronous suspension>
#4      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:86)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:270)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:262)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:345)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1126)
#21     _CustomZone.run (dart:async/zone.dart:1023)
#22     runZoned (dart:async/zone.dart:1501)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#26     main (file:///home/users/n.gendron/GitHub/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


[ +262 ms] ensureAnalyticsSent: 253ms
[   +1 ms] exiting with code 1
```

> Run `flutter analyze` and attach any output of that command also.

```Bash
flutter analyze -v
[  +29 ms] [/home/users/n.gendron/GitHub/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/home/users/n.gendron/GitHub/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/home/users/n.gendron/GitHub/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/users/n.gendron/GitHub/flutter/] git log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [/home/users/n.gendron/GitHub/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[        ] [/home/users/n.gendron/GitHub/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.5-0-g3ea4d06
[ +437 ms] /home/users/n.gendron/GitHub/flutter/bin/cache/dart-sdk/bin/dartanalyzer --packages /home/users/n.gendron/GitLab/n.gendron/techno_store/.packages /home/users/n.gendron/GitLab/n.gendron/techno_store
[  +72 ms] Analyzing /home/users/n.gendron/GitLab/n.gendron/techno_store...
[+7491 ms] No issues found!
[  +57 ms] Ran in 7.7s
[  +24 ms] "flutter analyze" took 8,002ms.
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] exiting with code 0
```

## Flutter Doctor

> Paste the output of running `flutter doctor -v` here.

```Bash
flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.UTF-8)
    • Flutter version 0.1.5 at /home/users/n.gendron/GitHub/flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices (1 available)
    • Nexus 5 • 05473ea90a673764 • android-arm • Android 7.1.2 (API 25)

• No issues found!
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by NatoBoram** [comment]
In the logs, there's a connection to : https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom

This returns the following : 
```JSON
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}
```

**Comment by NatoBoram** [comment]
Turns out it's a certificate issue. You have to add it to your certificates.

1. Set `$JAVA_HOME`
2. Import the certificate

```Bash
keytool -importcert -file /etc/ssl/certs/guardianCA.pem
```
