### ISSUE TITLE
☂️ RPCError: <method name>: (-32000) Service connection disposed

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#153471]
**(added on 8/20) Summary for archaeologists from the future:** a couple of the changes to package:vm_service made it such that any pending requests are completed with `RPCError`s when the service is suddenly shut down (e.g. the user shut down their device during `flutter run`). Such errors should be captured by the tool and either discarded entirely or be captured and replaced by a helpful error message where appropriate.

(added on 11/22): Per https://github.com/flutter/flutter/issues/153471#issuecomment-2403337193, there probably are legitimate bug(s) here, but I am not sure if they still exist in the 3.27 beta.
____________

Tool crashes with messages of the form `RPCError: <RPC method name>: (-32000) Service connection disposed` have come to represent a significant number of tool crashes. On 3.24.0 to-date (8/24), 1870 crashes have been reported by 410-517 clients.

This exception comes with a few stack traces, hence this creating this umbrella issue.

- [ ] https://github.com/flutter/flutter/issues/153472 (affected 410 clients, but no stack trace)
  * This one has no stack trace. I wonder if this means this must come from [`VMService::dispose`](https://github.com/dart-lang/sdk/blob/6c92babf4d3a256c15d98f126a5a6c30ed148c7a/pkg/vm_service/lib/src/vm_service.dart#L1739-L1745) since that callsite does not provide a stack trace in its `Completer::completeError` call.
- [ ] https://github.com/flutter/flutter/issues/153473 (only affected 7 clients)
- [ ] https://github.com/flutter/flutter/issues/153474 (affected 100 clients)
  * Originates from [`VMService::_call`](https://github.com/dart-lang/sdk/blob/6c92babf4d3a256c15d98f126a5a6c30ed148c7a/pkg/vm_service/lib/src/vm_service.dart#L1769-L1773). I wonder if the tool is making vm service calls after the vm service has been disposed and what might be causing this.

Edit: some more instances since we now get stack traces on these:

- [x] https://github.com/flutter/flutter/issues/154905
- [x] https://github.com/flutter/flutter/issues/154906
- [x] https://github.com/flutter/flutter/issues/154903

**Comment by andrewkolos** [comment]
Marking P1 since this a quite common crash and the current flutter tool crash rate is severe (see https://github.com/flutter/flutter/issues/153523).

cc @bkonyi and @DanTup in case they have seen similar issues in the past. The lattermost issue listed (https://github.com/flutter/flutter/issues/153474) seems to be the only one that gives us a complete stack trace. I'm guessing the VM service is getting shut down unexpectedly while there are still outgoing requests (e.g. from https://github.com/flutter/flutter/blob/72432c3f15b26fe55f8fd822e5fb3581260f75dd/packages/flutter_tools/lib/src/run_hot.dart#L303). I wonder why this issue has become so prominent in 3.24.0.

**Comment by andrewkolos** [comment]
Possibly related: https://github.com/dart-lang/sdk/commit/a479f91e80875dd6661b12108c9b81bdaeb2af65, which introduced a new source of `RPCError`s with the message `Service connection disposed`. However, any exceptions from there are thrown using `throw`, so I believe a stack trace would be present here. However, the top crasher here is without a stack trace, so I assume that those are coming from [`VMService::dispose`](https://github.com/dart-lang/sdk/blob/6c92babf4d3a256c15d98f126a5a6c30ed148c7a/pkg/vm_service/lib/src/vm_service.dart#L1740-L1744).

**Comment by andrewkolos** [comment]
> Possibly related: [dart-lang/sdk@a479f91](https://github.com/dart-lang/sdk/commit/a479f91e80875dd6661b12108c9b81bdaeb2af65), which introduced a new source of `RPCError`s...

When also considering https://github.com/dart-lang/sdk/commit/a7d8707a5964e174f2ce321d075e96e37a9a16ad (which automatically calls `dispose` on a `VMService` when its connection closes), it looks there was an overarching effort to have all pending (or new) calls to a disposed `VMService` to be completed with `RPCError`s. Said another way, it's possible that Flutter 3.24.0 did not introduce any new regressions; instead, changes to `package:vm_service` exposed the fact that the Flutter tool is making or awaiting calls to a disposed `VMService` in the form of these new exceptions.

**Comment by andrewkolos** [comment]
> it looks there was an overarching effort to have all pending (or new) calls to a disposed `VMService` to be completed with `RPCError`s.

Additional context for this: https://github.com/dart-lang/sdk/issues/55559

**Comment by andrewkolos** [comment]
Looking throughout the tool code, it seems pretty normal to need to handle the VM service suddenly shutting down. grep the code for `RPCError catch` to see what I mean. [Example](https://github.com/flutter/flutter/blob/271e0427e367c7ca6d2f28fd52df50b850efd137/packages/flutter_tools/lib/src/vmservice.dart#L500-L511). It's possible all these catches should be updated to catch these `RPCError`s with matching code and messages (the code -32000 is not unique to this particular scenario, I'm afraid).

**Comment by DanTup** [comment]
Yeah, I think it's pretty common for the VM Service to be disposed during requests. Lots of actions trigger a bunch of async requests but the user could also close their app (or click Stop Debugging) at any time. I think in most cases these errors should be handled on the assumption that the app is terminating.

The stack trace in https://github.com/flutter/flutter/issues/153473 includes a call to `_withErrorHandling` which is handling errors with the text "The client closed with pending request" but not "Service connection disposed", but I think they should be treated the same. I'll open a change in DDS/DAP for updating that.

**Comment by DanTup** [comment]
@bkonyi I also wonder if https://github.com/dart-lang/sdk/commit/a479f91e80875dd6661b12108c9b81bdaeb2af65 should have used an error message like "The client closed with pending request" so that any existing error handling catching that kind of error also works (since it seems like it's the same - I'm not sure in which situation we currently get the existing message - maybe VM Service without DDS?).

**Comment by bkonyi** [comment]
We should probably move to creating dedicated error codes for these scenarios as JSON-RPC 2.0 specifies that we can use -32000 to -32099 for implementation specific server errors. Using error messages to determine the type of error isn't easy to get right across multiple projects.

**Comment by DanTup** [comment]
I've opened https://dart-review.googlesource.com/c/sdk/+/381501 with a change to add this (I see Flutter is using the constants from vm_service so I added it to both to ensure they never reuse the same number for different purposes). For now, this only adds the constant, and we can change code to use it when we're happy enough of the callers have updated (and perhaps bump the major version as noted above).

**Comment by paul-thommithazhe** [comment]
I am facing this issue , - Oops; flutter has exited unexpectedly: "_flutter.listViews: (-32000) Service connection disposed".Working fine in android but for the iOS it crashes.

**Comment by andrewkolos** [comment]
Reopening since this is still appearing on 3.24.2 despite https://github.com/flutter/flutter/pull/153769

**Comment by FluffyDiscord** [comment]
Still happening on Flutter 3.24.3 I literally cannot start my app in Android emulator on my M1 Mac. Every attempt ends with
```
Lost connection to device.
Finished with error: getVM: (-32000) Service connection disposed
```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (3 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by andrewkolos** [comment]
> Still happening on Flutter 3.24.3 I literally cannot start my app in Android emulator on my M1 Mac. Every attempt ends with

Interesting, so the app doesn't event start (I am/was assuming that almost all of these crashes occur while shutting down at the end of `flutter run` or that the user quit the app/shut down the device in the middle of `flutter run`). @FluffyDiscord, does this happen when targeting other devices (e.g. not an Android emulator)? I am wondering if this issue is more common to a particular host platform and/or target platform. Also, if you are willing to share the verbose log output from one of these attempts (using the `-v` flag), it might help us figure out what's going wrong here.

**Comment by FluffyDiscord** [comment]
I should clarify the statement about the app startup - all I see is the native splash screen, then that message appears. Technically the app starts, but in practice it gets stuck and refuses to load further. iOS simulator does not seem to have this issue, only Android has. Today I found out that app actually does start from time to time (like 1 in 10 attempts, been doing random things like flutter clean, package upgrades, etc), but immediately disconnects from the runner (flutter pub run), so I cannot see anything.

I can send you the verbose log, but not publicly - too much headache to cleanup/anonymize. Can I send it to your email with this issue number? Meanwhile I am attaching a crash log that flutter generated. [flutter_01.log](https://github.com/user-attachments/files/17309609/flutter_01.log)

**Comment by andrewkolos** [comment]
Thank you so much for the follow-up!

From seeing `FlutterDevice.initLogReader` in the stack trace in the crash log, I see you are running into https://github.com/flutter/flutter/issues/154906

> all I see is the native splash screen, then that message appears. Technically the app starts, but in practice it gets stuck and refuses to load further.

Originally, I was thinking that this crash was being caused by users terminating the app/device while `flutter run` was starting up (though I began to suspect otherwise as we got more and more reports). However, you've helped confirm that this issue can occur in normal workflows, so thank you for that. I'll reopen that issue.

> Today I found out that app actually does start from time to time (like 1 in 10 attempts, been doing random things like flutter clean, package upgrades, etc), but immediately disconnects from the runner (flutter pub run), so I cannot see anything.

Yeah, it's very believable that there is some flakiness going on here.

> I can send you the verbose log, but not publicly - too much headache to cleanup/anonymize. Can I send it to your email with this issue number?

Sure, my email is listed in my profile. If I do find anything relevant, I'll share only that bit here and make sure there's nothing identifying in there—not even so much as a file path or app name.

**Comment by andrewkolos** [comment]
Note for myself: the only direct reference in the tool to `VmService.dispose` is [`FlutterVmService.dispose`](https://github.com/flutter/flutter/blob/5ecf10052fc2bf59f3f427dd21d21f22cb74acd9/packages/flutter_tools/lib/src/vmservice.dart#L1090-L1093), which is in-turn only referenced early on in [`FlutterDevice.connect`](https://github.com/flutter/flutter/blob/3941346723c72ad65d9c7ed6c3402e78f34cd25b/packages/flutter_tools/lib/src/resident_runner.dart#L282) (from what I can tell here all this code does is connect to the vm service and then immediately dispose that connection as a means to test for the presence of the vm service). All of this is only to say that I think this class of issue is _not_ due to the tool directly disposing of the VM service early.

**Comment by FluffyDiscord** [comment]
@andrewkolos Hi, any updates on this? It has been a month and I still cannot develop the Android version on emulator.

**Comment by andrewkolos** [comment]
> @andrewkolos Hi, any updates on this? It has been a month and I still cannot develop the Android version on emulator.

No, there is still no known way to reproduce this issue for debugging within the Flutter team.

@bkonyi We may need to escalate this issue, because at this point finding a cause for this is a needle-in-a-haystack problem[^1] that I don't have the bandwidth to dig into. Regardless, I'm preoccupied with 5 flake issues and assisting with the monorepo project, so I'm unassigning myself.

(Also fyi @FluffyDiscord, if you sent me verbose logs, I don't think I ever received them)

[^1]: further complicated by the fact that there is no known way to distinguish between the cases of 1) the VM service connection being explicitly closed 2) the VM service being killed by the host and 3) the VM service crashing

**Comment by FluffyDiscord** [comment]
> (Also fyi @FluffyDiscord, if you sent me verbose logs, I don't think I ever received them)

@andrewkolos I have sent you the verbose log month ago, to be exactly on 9th October (see image from Protonmail)
![image](https://github.com/user-attachments/assets/8b66614b-f94c-403a-9e76-08ad64167a8c)

I am sending you the mail again.

**Comment by bkonyi** [comment]
> @bkonyi We may need to escalate this issue, because at this point finding a cause for this is a needle-in-a-haystack problem[1](#user-content-fn-1-537cd7985d27e12fb1280599b0a39fd7) that I don't have the bandwidth to dig into. Regardless, I'm preoccupied with 5 flake issues and assisting with the monorepo project, so I'm unassigning myself.

SGTM. I can try and pick this up next week and see if there's anything we can do to make it more obvious what's happening when the connection goes down.

**Comment by andrewkolos** [comment]
> > (Also fyi @FluffyDiscord, if you sent me verbose logs, I don't think I ever received them)
> 
> @andrewkolos I have sent you the verbose log month ago, exactly on 9th October (see image from Protonmail) ![image](https://private-user-images.githubusercontent.com/10332247/382357675-8b66614b-f94c-403a-9e76-08ad64167a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODg4MTYsIm5iZiI6MTczMDQ4ODUxNiwicGF0aCI6Ii8xMDMzMjI0Ny8zODIzNTc2NzUtOGI2NjYxNGItZjk0Yy00MDNhLTllNzYtMDhhZDY0MTY3YThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE5MTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjI5ZmQ2NzNlOGNhNDdjMDM3Y2VlYzM3OGU0MjFkZDYzODNkNDVlZWE0ZjJhZjVkOWY3YTAxMmQyZGFkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fIUiNuIIt3NcxSeXw1diKYfEzHcXO5uPZubikOZRUGc)
> 
> I am sending you the mail again.

Got it, thanks. It got buried in the Updates tab in gmail—sorry about that.

I'll be hiding these comments to reduce noise for other folks reading this issue.

**Comment by brittlewis12** [comment]
Howdy folks,

Ran into this crash attempting to build an apk for android using a default generic android emulator, seemingly while binding the location service:

```
Running Gradle task 'assembleDevDebug'...                          37.1s
✓ Built build/app/outputs/flutter-apk/app-dev-debug.apk
Installing build/app/outputs/flutter-apk/app-dev-debug.apk...      1,647ms
D/FlutterLocationService(10115): Creating service.
D/FlutterLocationService(10115): Binding to location service.
Lost connection to device.

Oops; flutter has exited unexpectedly: "getVM: (-32000) Service connection disposed".
```

```
❯ flutter emulators

Id                  • Name                • Manufacturer • Platform

Medium_Phone_API_35 • Medium Phone API 35 • Generic      • android
```

When I switched to a Pixel emulator instead, this issue resolved itself. I also was able to work around by bumping the `safe_device` package to at least version `1.1.5`.

<details><summary>Full output from the associated flutter.log</summary>

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run lib/main.dart --flavor dev --dart-define=IS_LOCAL=true

## exception

RPCError: getVM: (-32000) Service connection disposed

```
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.24.3 on channel stable at /Users/britt/.local/share/mise/installs/flutter/3.24.3-stable
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (2 months ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/britt/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Users/britt/.local/share/mise/installs/java/17.0.2/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.2+8-86)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.15.2

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[32m[✓][39m Connected device (3 available)
    [32m•[39m sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64 • Android 15 (API 35) (emulator)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64  • macOS 15.1.1 24B91 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin        • macOS 15.1.1 24B91 darwin-arm64

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.
```

</details>

**Comment by karmicdice** [comment]
```bash
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
Lost connection to device.
Finished with error: getVM: (-32000) Service connection disposed
```

This happened after my SplashScreen started checking for user's login status before navigating with GoRouter.

Upon re-running couple of times - it just works without any issues.
Maybe something to do with `async` ?

**Comment by bkonyi** [comment]
@brittlewis12 @karmicdice, did your application crash when you got this error by any chance?

**Comment by TheNoumanDev** [comment]
Getting this error occaitonaly, breaks 2-3 times and then suddenly works and then next time crashes again.

## command
```
flutter run
```
## exception
```
RPCError: getVM: (-32000) Service connection disposed
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[33m[!][39m Flutter (Channel [user-branch], 3.24.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
    [33m![39m Flutter version 3.24.3 on channel [user-branch] at C:\Users\Nouman\dev\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    [33m![39m Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    [32m•[39m Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\Nouman\AppData\Local\Android\sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.10.35122.118
    [32m•[39m Windows 10 SDK version 10.0.22621.0

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[32m[✓][39m VS Code (version 1.96.0)
    [32m•[39m VS Code at C:\Users\Nouman\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone16k x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    [32m•[39m Windows (desktop)             • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    [32m•[39m Chrome (web)                  • chrome        • web-javascript • Google Chrome 131.0.6778.109
    [32m•[39m Edge (web)                    • edge          • web-javascript • Microsoft Edge 131.0.2903.86

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.
```

**Comment by burnermanx** [comment]
> Howdy folks,
> 
> Ran into this crash attempting to ~build~run an apk for android using a default generic android emulator, seemingly while binding the location service:
> 
> ```
> Running Gradle task 'assembleDevDebug'...                          37.1s
> ✓ Built build/app/outputs/flutter-apk/app-dev-debug.apk
> Installing build/app/outputs/flutter-apk/app-dev-debug.apk...      1,647ms
> D/FlutterLocationService(10115): Creating service.
> D/FlutterLocationService(10115): Binding to location service.
> Lost connection to device.
> 
> Oops; flutter has exited unexpectedly: "getVM: (-32000) Service connection disposed".
> ```
> 
> ```
> ❯ flutter emulators
> 
> Id                  • Name                • Manufacturer • Platform
> 
> Medium_Phone_API_35 • Medium Phone API 35 • Generic      • android
> ```
> 
> When I switched to a Pixel emulator instead, this issue resolved itself. I also was able to work around by bumping the `safe_device` package to at least version `1.1.5`.
> 
> Full output from the associated flutter.log

This worked for me too. So, this would be a way to reproduce the problem @andrewkolos. 
With a generic device emulator, I faced the same problem. When I created an "Pixel 9 Pro" device, the issue is gone.

**Comment by gotecq-linhdoan** [comment]
Has anyone found a solution yet? 
I'm encountering an issue after switching from a Mac Mini M1 to a Mac Mini M2. When running on both the iOS simulator and a real device, the error persists. I've tried using Flutter versions 3.24.3 and the latest, but although the error message changes, the problem remains. Changing the iOS device doesn't help either. Strangely, some apps run normally while others crash immediately at startup. Even more puzzling, when testing the same code on two repositories (for different environments) on another Mac Mini M1, one runs without issues while the other encounters this error.
 ```
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-VN)
    • Flutter version 3.24.0 on channel stable at /Users/doantuanlinh/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Android SDK at /Users/doantuanlinh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/doantuanlinh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] Connected device (4 available)
    • iPhone 15 (mobile)              • F563FEE4-3EAE-4354-8467-583A3EDF67A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3.1 24D70 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 133.0.6943.142
    ! Error: Browsing on the local area network for iPhone GoTECQ MO. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

**Comment by karmicdice** [comment]
> Has anyone found a solution yet? I'm encountering an issue after switching from a Mac Mini M1 to a Mac Mini M2. When running on both the iOS simulator and a real device, the error persists. I've tried using Flutter versions 3.24.3 and the latest, but although the error message changes, the problem remains. Changing the iOS device doesn't help either. Strangely, some apps run normally while others crash immediately at startup. Even more puzzling, when testing the same code on two repositories (for different environments) on another Mac Mini M1, one runs without issues while the other encounters this error.
> 
> ```
> flutter doctor -v
> [✓] Flutter (Channel stable, 3.24.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-VN)
>    • Flutter version 3.24.0 on channel stable at /Users/doantuanlinh/fvm/versions/3.24.0
>    • Upstream repository https://github.com/flutter/flutter.git
>    • Framework revision 80c2e84975 (7 months ago), 2024-07-30 23:06:49 +0700
>    • Engine revision b8800d88be
>    • Dart version 3.5.0
>    • DevTools version 2.37.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
>    • Android SDK at /Users/doantuanlinh/Library/Android/sdk
>    • Platform android-35, build-tools 35.0.1
>    • ANDROID_HOME = /Users/doantuanlinh/Library/Android/sdk
>    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
>    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
>    • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 16.2)
>    • Xcode at /Applications/Xcode.app/Contents/Developer
>    • Build 16C5032a
>    • CocoaPods version 1.16.2
> 
> [✓] Chrome - develop for the web
>    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2024.2)
>    • Android Studio at /Applications/Android Studio.app/Contents
>    • Flutter plugin can be installed from:
>      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>    • Dart plugin can be installed from:
>      🔨 https://plugins.jetbrains.com/plugin/6351-dart
>    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
> 
> [✓] Connected device (4 available)
>    • iPhone 15 (mobile)              • F563FEE4-3EAE-4354-8467-583A3EDF67A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
>    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
>    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.3.1 24D70 darwin-arm64
>    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 133.0.6943.142
>    ! Error: Browsing on the local area network for iPhone GoTECQ MO. Ensure the device is unlocked and attached with a cable or associated with the same local area network
>      as this Mac.
>      The device must be opted into Developer Mode to connect wirelessly. (code -27)
> 
> [✓] Network resources
>    • All expected network resources are available.
> ```

Mac notoriously picks up Java versions wrong. I had issues with Android. After setting JAVA_HOME the issue solved itself. Oh and I changed the phone, used Pixel 8 through emulator.

**Comment by bsb-github** [comment]
@gotecq-linhdoan which folder you replaced unfortunately getting same error

**Comment by gotecq-linhdoan** [comment]
@bsb-github I didn't notice any changes, but somehow it just worked like black magic after replacing the entire app folder.

**Comment by bsb-github** [comment]
@gotecq-linhdoan which folder? ios folder ?

**Comment by gotecq-linhdoan** [comment]
@bsb-github I need the fully functional Flutter project, including Android, iOS, lib, and all necessary files, but specifically the working one.

**Comment by bkonyi** [comment]
I think we've dealt with the majority of the instances of this error, so I'm going to close this for now.
