### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/BackEvent

### ISSUE THREAD

**Issue by liaoweiyi** [flutter/flutter#153491]
### Steps to reproduce

In Flutter SDK version 3.22 and later, calling EventBus.getDefault().register(this) in FlutterActivity throws the following exception:
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/BackEvent.

Details:

Affected Versions: The issue occurs in Flutter SDK 3.22 and later.
Unaffected Versions: The issue does not exist in Flutter SDK version 3.19.6 and earlier.
Device-Specific: The exception occurs only on certain devices.
Specific Context: This problem is observed only when registering in FlutterActivity. It does not appear when registering in other classes or activities.

### Expected results

No abnormalities

### Actual results

crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
 FATAL EXCEPTION: main
                                                                                                    Process: com.gbits.rastar.debug, PID: 9488
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gbits.rastar.debug/com.gbits.rastar.flutter.LtcFlutterActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.gbits.rastar.flutter.LtcFlutterActivity and its super classes have no public methods with the @Subscribe annotation
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.gbits.rastar.flutter.LtcFlutterActivity and its super classes have no public methods with the @Subscribe annotation
                                                                                                    	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
                                                                                                    	at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
                                                                                                    	at com.gbits.common.event.EventManager.register(EventManager.kt:14)
                                                                                                    	at com.gbits.rastar.flutter.LtcFlutterActivity.onCreate(LtcFlutterActivity.kt:139)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8595)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8573)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@liaoweiyi 
Can you check if [this](https://github.com/flutter/flutter/issues/149648#issuecomment-2149293359) helps to resolve your case ?
