### ISSUE TITLE
Hot reload is broken under select scenario when using `Map.entries`

### ISSUE THREAD

**Issue by GregoryConrad** [flutter/flutter#153536]
### Steps to reproduce

From a fresh new flutter application:

`pubspec.yaml`:
```yaml
name: hot_reload_reproduce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.6.7
  rearch: ^1.10.1

flutter:
  uses-material-design: true
```

`main.dart`:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_rearch/flutter_rearch.dart';
import 'package:rearch/rearch.dart';

void main() {
  runApp(
    const RearchBootstrapper(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'App Name',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const CounterAppBody(),
    );
  }
}

class CounterAppBody extends RearchConsumer {
  const CounterAppBody({super.key});

  @override
  Widget build(BuildContext context, WidgetHandle use) {
    final (count, incrementCount) = use(countManager);
    final countPlusOne = use(countPlusOneCapsule);
    final textHandler = use(textInputManager);

    return Scaffold(
      appBar: AppBar(title: const Text('ReArch Demo')),
      floatingActionButton: FloatingActionButton(
        onPressed: incrementCount,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
      body: Center(
        child: Column(
          children: [
            SizedBox(
              width: 200,
              child: TextField(
                onChanged: textHandler.$2,
              ),
            ),
//            Text(textHandler.$1),            // UNCOMMENT THIS LINE, SAVE, AND HOT RELOAD
            Text(
              '$count + 1 = $countPlusOne',
              style: Theme.of(context).textTheme.bodyLarge,
            ),
          ],
        ),
      ),
    );
  }
}

(int, void Function()) countManager(CapsuleHandle use) {
  final (count, setCount) = use.state(0);
  return (count, () => setCount(count + 1));
}

(String, void Function(String)) textInputManager(CapsuleHandle use) {
  final (val, setval) = use.state('initial');
  return (
    val,
    (str) {
      setval(str);
    }
  );
}

int countPlusOneCapsule(CapsuleHandle use) => use(countManager).$1 + 1;
```

1. `flutter run -d macos` (guessing this will trigger on other platforms too, but it certainly does on macOS).
2. Uncomment the commented out line
3. Save
4. Hot reload

### Expected results

App successfully hot-reloads.

### Actual results

`Map.entries` appears to have some weird invalid type casting going on and the app breaks. See logs below.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
Syncing files to device macOS...                                    42ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:54431/-WnJXHwu4j0=/
flutter: {}
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:54431/-WnJXHwu4j0=/

flutter: {Closure: (CapsuleHandle) => (int, () => void) from Function 'countManager': static.: Closure: () => void, Closure: (CapsuleHandle) => int from Function 'countPlusOneCapsule': static.: Closure: () => void, Closure: (CapsuleHandle) => (String, (String) => void) from Function 'textInputManager': static.: Closure: () => void}

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building CounterAppBody(dirty, dependencies:
[CapsuleContainerProvider, InheritedCupertinoTheme, _InheritedTheme,
_LocalizationsScope-[GlobalKey#3c52e]]):
type 'Null' is not a subtype of type '() => void' in type cast

The relevant error-causing widget was:
  CounterAppBody
  CounterAppBody:file:///Users/gconrad/Downloads/thingy/lib/main.dart:25:19

When the exception was thrown, this was the stack:
#0      MapBase.entries.<anonymous closure> (dart:collection/maps.dart:76:62)
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:450:22)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
#6      Iterable.toList (dart:core/iterable.dart:498:7)
#7      _RearchElement.build (package:flutter_rearch/src/widgets/consumer.dart:83:12)
#8      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:5617:15)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#10     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#11     BuildScope._flushDirtyElements
(package:flutter/src/widgets/framework.dart:2752:11)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#14     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:468:5)
#15     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1397:15)
#16     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1318:9)
#17     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:1040:9)
#18     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure>
(dart:ui/platform_dispatcher.dart:837:16)
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
```

Note that the following:
```
flutter: {Closure: (CapsuleHandle) => (int, () => void) from Function 'countManager': static.: Closure: () => void, Closure: (CapsuleHandle) => int from Function 'countPlusOneCapsule': static.: Closure: () => void, Closure: (CapsuleHandle) => (String, (String) => void) from Function 'textInputManager': static.: Closure: () => void}
```
Is a print statement I added in to `flutter_rearch` locally to show that the `Map` does in fact have _no_ null keys/values, and that this is a bug with the `Map.entries` implementation after a hot reload.

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @GregoryConrad, can you please present this issue with a simpler sample code without using 3rd party package? That helps us understand what simple piece of code triggers this error and also helps similar issues to be found later. Thanks!

**Comment by GregoryConrad** [comment]
@huycozy I'll see what I can do. Might need to duplicate some parts of ReArch in order to trigger this bug, but I'll try to make it as minimal as possible.

**Comment by GregoryConrad** [comment]
@huycozy Hopefully this should be sufficient. There may still be some extra fat, but it's sitting at only 200 LoC.

To reproduce:
1. `flutter create hot_reload_bug`
2. Replace `main.dart` with the following:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hot Reload Bug',
      home: const AppBody(),
    );
  }
}

class AppBody extends RearchConsumer {
  const AppBody({super.key});

  @override
  Widget build(BuildContext context, CapsuleReader use) {
    final count = use(countCapsule);

    return Scaffold(
      appBar: AppBar(title: const Text('ReArch Demo')),
      body: Center(
        child: Column(
          children: [
// Text('hi'),                         // UNCOMMENT THIS LINE, SAVE, HOT RELOAD
            Text('$count'),
          ],
        ),
      ),
    );
  }
}

int countCapsule(CapsuleReader use) => 1;

final container = CapsuleContainer();

abstract class RearchConsumer extends Widget {
  const RearchConsumer({super.key});

  @override
  Element createElement() => _RearchElement(this);

  @protected
  Widget build(BuildContext context, CapsuleReader use);
}

class _RearchElement extends ComponentElement implements CapsuleReader {
  _RearchElement(RearchConsumer super.widget);

  /// Represents a [Map] of capsules to void [Function]s that
  /// remove the dependency of this [Element] on those capsules.
  final capsuleToRemoveDependency = <Capsule<Object?>, void Function()>{};

  /// Represents the [Set] of `use`d capsules in the ongoing build.
  Set<Capsule<Object?>>? capsulesUsedInCurrBuild;

  /// Clears out the [Capsule] dependencies of this [_RearchElement].
  void clearDependencies() {
    for (final dispose in capsuleToRemoveDependency.values) {
      dispose();
    }
    capsuleToRemoveDependency.clear();
  }

  @override
  Widget build() {
    capsulesUsedInCurrBuild = {};
    try {
      final consumer = super.widget as RearchConsumer;
      return consumer.build(
        this,
        this,
      );
    } finally {
      // We need to do some dependency management here to ensure that we
      // get all the capsule updates we need, but nothing more.

      // First, let's remove any no-longer used dependencies.
      capsuleToRemoveDependency.entries
          .where((e) => !capsulesUsedInCurrBuild!.contains(e.key))
          .toList()
          .forEach((e) {
        e.value(); // dispose() from onNextUpdate
        capsuleToRemoveDependency.remove(e.key);
      });

      // Next, for each capsule used in the current build,
      // let's make sure we depend upon it.
      capsulesUsedInCurrBuild!
          .where((cap) => !capsuleToRemoveDependency.containsKey(cap))
          .forEach((cap) {
        capsuleToRemoveDependency[cap] = container.onNextUpdate(cap, () {
          markNeedsBuild();
          capsuleToRemoveDependency.remove(cap);
        });
      });

      // Finally, let's reset everything for the next build.
      capsulesUsedInCurrBuild = null;
    }
  }

  @override
  void update(RearchConsumer newWidget) {
    super.update(newWidget);
    rebuild(force: true);
  }

  @override
  void deactivate() {
    clearDependencies();
    super.deactivate();
  }

  @override
  T call<T>(Capsule<T> capsule) {
    capsulesUsedInCurrBuild?.add(capsule);
    return container.read(capsule);
  }
}

abstract interface class Disposable {
  void dispose();
}

typedef Capsule<T> = T Function(CapsuleReader);

/// Provides a mechanism to read the current state of [Capsule]s.
abstract interface class CapsuleReader {
  T call<T>(Capsule<T> capsule);
}

typedef SideEffectApiCallback = void Function();

/// Contains the data of [Capsule]s.
class CapsuleContainer implements Disposable {
  final _capsules = <_UntypedCapsule, _CapsuleManager>{};

  _CapsuleManager _managerOf(_UntypedCapsule capsule) {
    return _capsules.putIfAbsent(
      capsule,
      () => _CapsuleManager(this, capsule)..buildSelf(),
    );
  }

  /// Reads the current data of the supplied [Capsule],
  /// initializing it if needed.
  T read<T>(Capsule<T> capsule) => _managerOf(capsule).data as T;

  /// Runs the supplied [callback] the next time [capsule] is
  /// updated *or* disposed.
  ///
  /// You can also prematurely remove the callback from the container
  /// via the returned [void Function()] (which does not invoke [callback]).
  /// It also will free [capsule] from the container if possible
  /// (i.e., if it is idempotent and has no dependents) when invoked.
  void Function() onNextUpdate<T>(
    Capsule<T> capsule,
    void Function() callback,
  ) {
    // This uses the fact that if we add an idempotent capsule, it will be
    // automatically disposed whenever the supplied capsule is updated/disposed
    // via the idempotent gc.
    void tempCapsule(CapsuleReader use) => use<T>(capsule);
    final tempManager = _managerOf(tempCapsule);
    tempManager.toDispose.add(callback);

    return () {
      tempManager.toDispose.remove(callback);
      tempManager.dispose();
    };
  }

  @override
  void dispose() {
    // We need toList() to copy the list in order to
    // prevent container modification during iteration
    // (dispose() removes the manager from the container).
    for (final manager in _capsules.values.toList()) {
      manager.dispose();
    }
  }
}

typedef _UntypedCapsule = Capsule<Object?>;

class _CapsuleManager implements Disposable, CapsuleReader {
  _CapsuleManager(this.container, this.capsule);

  final CapsuleContainer container;
  final _UntypedCapsule capsule;

  late Object? data;
  final toDispose = <SideEffectApiCallback>{};

  void buildSelf() => data = capsule(this);

  @override
  void dispose() {
    container._capsules.remove(capsule);
    for (final callback in toDispose) {
      callback();
    }
  }

  @override
  T call<T>(Capsule<T> capsule) => container.read(capsule);
}
```
3. `flutter run -d macos` -- guessing this will work on other OS but it does on macOS
4. Uncomment the specified line, save, hot reload. Exception thrown.

**Comment by GregoryConrad** [comment]
Possibly related as well: https://github.com/rrousselGit/riverpod/issues/3193

**Comment by huycozy** [comment]
Thank you for providing a simpler reproduction code. Reproduced this on `Channel master, 3.24.0-1.0.pre.623`.

<details>
<summary>Exception log</summary>

```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building AppBody(dirty):
type 'Null' is not a subtype of type '() => void' in type cast

The relevant error-causing widget was:
    AppBody AppBody:file:///Users/huynq/Desktop/repro_issues/lib/hotreload_153536.dart:14:19

When the exception was thrown, this was the stack:
#0      MapBase.entries.<anonymous closure> (dart:collection/maps.dart:76:62)
maps.dart:76
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:403:20)
iterable.dart:403
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:450:22)
iterable.dart:450
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
growable_array.dart:202
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
growable_array.dart:152
#5      new List.of (dart:core-patch/array_patch.dart:39:18)
array_patch.dart:39
#6      Iterable.toList (dart:core/iterable.dart:498:7)
iterable.dart:498
#7      _RearchElement.build (package:repro_issues/hotreload_153536.dart:88:12)
hotreload_153536.dart:88
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:15)
framework.dart:5637
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
framework.dart:5353
#10     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2701:15)
framework.dart:2701
#11     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2760:11)
framework.dart:2760
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
framework.dart:3056
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1176:21)
binding.dart:1176
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
binding.dart:475
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#17     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
binding.dart:1040
#18     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
platform_dispatcher.dart:837
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 3 frames from class _Timer and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 713 libraries in 700ms (compile: 35 ms, reload: 195 ms, reassemble: 182 ms).
```
</details>

**Comment by jason-simmons** [comment]
This started with https://dart.googlesource.com/sdk/+/8ff777e61ff03ebed0d4ad104494fb3f387f3eb2

@alexmarkov

**Comment by mraleph** [comment]
also cc @rmacnak-google 

This type of error indicates that hash of some closure changed as a result of hot reload which of course broke map in which that function was used as a key.
