### ISSUE TITLE
camera plugin fails in --preview-dart-2

### ISSUE THREAD

**Issue by terrywarwar** [flutter/flutter#15359]
## Steps to Reproduce

Downloaded camera plugin example and ran it.  Works in non `--preview-dart-2`, but fails when `--preview-dart-2` is enabled.  

## Logs

```I/CameraManagerGlobal( 5351): Connecting to camera service
E/flutter ( 5351): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5351): type 'List' is not a subtype of type 'List<Map<String, String>>' where
E/flutter ( 5351):   List is from dart:core
E/flutter ( 5351):   List is from dart:core
E/flutter ( 5351):   Map is from dart:core
E/flutter ( 5351):   String is from dart:core
E/flutter ( 5351):   String is from dart:core
E/flutter ( 5351): 
E/flutter ( 5351): #0      availableCameras (package:camera/camera.dart)
E/flutter ( 5351): <asynchronous suspension>
E/flutter ( 5351): #1      main (file:///Users/terry/Downloads/plugins-master/packages/camera/example/lib/main.dart:170:19)
E/flutter ( 5351): <asynchronous suspension>
E/flutter ( 5351): #2      _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
E/flutter ( 5351): #3      _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)```


## flutter analyze
Analyzing /Users/terry/Downloads/plugins-master/packages/camera/example...
No issues found!
Ran in 3.7s


## Flutter Doctor

flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D2104, locale en-AU)
    • Flutter version 0.1.5 at /Users/terry/flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/terry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.21.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[✓] Connected devices (1 available)
    • iPhone X • 4419315F-328F-436C-A1E8-548A1D631E5E • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by mraleph** [comment]
Thanks for reporting. Fix is out for review: https://github.com/flutter/plugins/pull/417
