### ISSUE TITLE
`'!ancestor._needsSemanticsUpdate': is not true.` assertion failure on Flutter 3.24.0

### ISSUE THREAD

**Issue by jerry-company** [flutter/flutter#153692]
### Steps to reproduce

```dart
  await tester.tap(find.byKey(Key(key)));
  await tester.pumpFrames(tester.allWidgets.whereType<App>().first,
      Duration(milliseconds: milliseconds));
```

We have lots of BDD test cases.
However, after upgrading Flutter SDK to 3.24.0, in specific widget test cases, the above `pumpFrames()` fails with an assertion failure message.

I couldn't make a simple unit test to reproduce this failure.

### Expected results

No assertion failure should happen because there is no application-side bug.

### Actual results

There are some test cases fail with the following call stack.
```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 5184 pos 18:
'!ancestor._needsSemanticsUpdate': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:5184:18)
#3      new _SemanticsGeometry (package:flutter/src/rendering/object.dart:5125:5)
#4      _SwitchableSemanticsFragment._computeSemanticsGeometry (package:flutter/src/rendering/object.dart:5059:9)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4973:42)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:5022:16)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:5022:16)
#8      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3701:25)
#9      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
#10     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
#11     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1446:35)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#15     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1288:9)
#18     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#19     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1275:27)
#20     WidgetTester.pumpFrames.<anonymous closure> (package:flutter_test/src/widget_tester.dart:749:23)
<asynchronous suspension>
#21     TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:120:7)
<asynchronous suspension>
...
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale ko-JP)
    • Flutter version 3.24.0 on channel stable at /Users/jerry/.fenv/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/jerry/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/jerry/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode-15.2.0.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by jerry-company** [comment]
https://github.com/flutter/flutter/pull/151688 looks suspicious IMHO.

**Comment by huycozy** [comment]
Hi @jerry-company 

>https://github.com/flutter/flutter/pull/151688 looks suspicious IMHO.

I see you are on stable 3.24.0 while this PR is only on Flutter master channel but hasn't landed to stable yet.

>in specific widget test cases, the above pumpFrames() fails with an assertion failure message.

Please try to narrow the test case down into a minimal sample code so that we can reproduce it to investigate further. Thanks!

**Comment by jerry-company** [comment]
@huycozy 
Thanks for the answer.
Although it doesn't look so easy, I'm gonna try to find a simple bug case.
