### ISSUE TITLE
PathNotFoundException: MaterialIcons-Regular.otf

### ISSUE THREAD

**Issue by arditneziri93** [flutter/flutter#153680]
### Steps to reproduce

1. Create app
2. Run the app on web

### Expected results

Expected to run the App

### Actual results

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
PathNotFoundException: PathNotFoundException: Cannot open file, path = '/Users/arditneziri/Developer/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf' (OS Error: No such file or directory, errno = 2)

#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      ForwardingFile.openSync (package:file/src/forwarding/forwarding_file.dart:74:16)
#3      ErrorHandlingFile.copySync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:319:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:595:14)
#5      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:318:5)
#6      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:230:19)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#8      writeBundle (package:flutter_tools/src/bundle_builder.dart:185:3)
<asynchronous suspension>
#9      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:991:9)
<asynchronous suspension>
#10     ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:562:35)
<asynchronous suspension>
#11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:322:41)
<asynchronous suspension>
#12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[32m[✓][39m Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale de-DE)
    [32m•[39m Flutter version 3.22.3 on channel stable at
      /Users/arditneziri/Developer/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0850beeb2 (5 weeks ago), 2024-07-16 21:43:41 -0700
    [32m•[39m Engine revision 235db911ba
    [32m•[39m Dart version 3.4.4
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [32m•[39m Android SDK at /Users/arditneziri/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 30.0.3
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.91.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 14.5 23F79 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 127.0.6533.120

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @arditneziri93 
Does the issue persist if you run app again? Can you please try upgrading Flutter SDK to the latest stable version 3.24.0 and retry?

**Comment by arditneziri93** [comment]
Hi
I did it and it was still missing. I had to download the
Material-Icons-Regular.utf and place it manually in the folder so that it
worls again. This happened after I installed the latest flutter version.

Am Di., 20. Aug. 2024 um 07:25 Uhr schrieb Huy ***@***.***>:

**Comment by huycozy** [comment]
I think that file is somehow missing or corrupted while downloading Flutter SDK. I will mark this as solved. If you experience it again and can reproduce it consistently, please write in comments or file a new issue. Thanks!
