### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Operation timed out, errno = 60

### ISSUE THREAD

**Issue by raneem-yad** [flutter/flutter#153707]
## Command
```sh
flutter create test_app_todelete_later
```

## Steps to Reproduce
1. flutter create app

## Logs
FileSystemException: Directory listing failed, OS Error: Operation timed out, errno = 60
```console
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:228:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      new Template._ (package:flutter_tools/src/template.dart:108:63)
#5      Template.merged (package:flutter_tools/src/template.dart:155:21)
<asynchronous suspension>
#6      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:477:31)
<asynchronous suspension>
#7      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:508:23)
<asynchronous suspension>
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:369:31)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#10

**Comment by huycozy** [comment]
Hi @raneem-yad 
This could be a network connection issue. Can you confirm you have a stable internet connection? Does the issue appear again if you retry?

**Comment by huycozy** [comment]
Hi @raneem-yad 
Does the issue appear again if you retry? Can you please provide the output of `flutter doctor -v` as well? Thanks!

**Comment by raneem-yad** [comment]
Hi @huycozy,

I retried, and the issue has been resolved. Everything is now working as intended.

Thank you so much!
