### ISSUE TITLE
Assertion thrown when toggle select widget mode is clicked

### ISSUE THREAD

**Issue by seandotmoon** [flutter/flutter#15370]
## Steps to Reproduce

I just tried to use the flutter inspector and an assertion is thrown when I toggled select widget mode button.

## Logs
```
I/flutter ( 5525): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5525): The following assertion was thrown building Banner("SLOW MODE", textDirection: ltr, location:
I/flutter ( 5525): topEnd, Color(0xa0b71c1c), text inherit: true, text color: Color(0xffffffff), text size: 10.2, text
I/flutter ( 5525): weight: 900, text height: 1.0x):
I/flutter ( 5525): 'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 518:
I/flutter ( 5525): 'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.
I/flutter ( 5525): 
I/flutter ( 5525): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5525): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5525): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5525):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5525): 
I/flutter ( 5525): When the exception was thrown, this was the stack:
I/flutter ( 5525): #2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart:518)
I/flutter ( 5525): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734)
I/flutter ( 5525): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 5525): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 5525): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 5525): #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 5525): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5525): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5525): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5525): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5525): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5525): #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685)
I/flutter ( 5525): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5525): #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5525): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 5525): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 5525): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 5525): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 5525): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
```
## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D47, locale en-US)
    • Flutter version 0.1.5 at /Users/Smoon/dev/tools/flutter
    • Framework revision 3ea4d06340 (2 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Smoon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by Hixie** [comment]
cc @jacob314

**Comment by jacob314** [comment]
This issue was fixed last June but I failed to close the bug. I've gone ahead and verified and I can't reproduce the issue.

**Comment by goderbauer** [comment]
Awesome! Thanks.
