### ISSUE TITLE
StateError: Bad state: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 49801

### ISSUE THREAD

**Issue by paul-thommithazhe** [flutter/flutter#153840]
### Steps to reproduce

1. flutter run

### Expected results

app is crashing on iOS , but working on android . 

### Actual results

```console
DDS has failed to start and there is not an existing DDS instance available to connect to.

 WebSocketChannelException: SocketException: Connection refused (OS Error: Connection
 refused, errno = 61), address = 127.0.0.1, port = 61364.

Oops; flutter has exited unexpectedly: "Bad state: WebSocketChannelException:
SocketException: Connection refused (OS Error: Connection refused, errno = 61), address =
127.0.0.1, port = 61364".
```

### Code sample

<details open><summary>Code sample</summary>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

## exception

StateError: Bad state: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 61364

```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:290:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.25.0-1.0.pre.61, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-IN)
    • Flutter version 3.25.0-1.0.pre.61 on channel master at
      /Users/paulthommithazhe/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 36a391f689 (3 hours ago), 2024-08-21 17:45:32 +0800
    • Engine revision b94e009703
    • Dart version 3.6.0 (build 3.6.0-164.0.dev)
    • DevTools version 2.39.0-dev.15

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/paulthommithazhe/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64
      • Android 15 (API 35) (emulator)
    • iPhone 15 Pro Max (mobile)      • 0F39EF98-2096-43EB-8AD7-2873EF9CBF48 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64
      • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin
      • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by huycozy** [comment]
Hi @paul-thommithazhe 
How frequently does this issue appear? Does it occur on a newly created Flutter project? If so, can you please provide the output of `flutter run -v`? 

Can you also check this on Flutter stable channel? Thanks!
