### ISSUE TITLE
Deobfuscated stack-traces should show package path like normal stack-traces

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#153813]
### Use case

When using the `--symbolize` option with an obfuscated stack-trace, the source-code paths appear to be absolute.

For example:

```
at #00 abs 00000070889bcc93 virt 000000000018fc93 _kDartIsolateSnapshotInstructions+0xb9153 (unparsed:null)
at #01 abs 00000070889464fb virt 00000000001194fb _kDartIsolateSnapshotInstructions+0x429bb (unparsed:null)
```
becomes:
```
at #0      _MyAppState.build.<anonymous closure> (/path/to/my/my_app/lib/main.dart:89:17)
at #1      _InkResponseState.handleTap (/path/to/my/sdk/flutter/packages/flutter/lib/src/material/ink_well.dart:1170:21)
```

In a normal (not obfuscated) stack-trace, the paths are all referencing the packages:

e.g.
```
at _MyAppState.build.<fn> line 113, column 24 (package:my_app/main.dart:113)
at _InkResponseState.handleTap line 1170, column 21 (package:flutter/src/material/ink_well.dart:1170) 
```

### Proposal

Looking at the symbols file with a hex editor, I can see that the paths are all absolute to my machine.

I wonder if it would be possible to store package relative paths instead in the symbol files, as they can be observed in non-obfuscated stack-traces.

Main reasons for this request are:

- Stack-traces are consistent between obfuscated and non-obfuscated apps.
- Stack-traces are consistent between machines/setups (as paths won't matter anymore).
- Shorter package relative paths are easier to read.

**Comment by andrewkolos** [comment]
@a-siva Do you think this would be feasible?

**Comment by mraleph** [comment]
@matanlurey the tool code itself is forcing the resolution [here](https://github.com/flutter/flutter/blob/dcae0c4ca0c3ee3317ed3198a2141184e949fb03/packages/flutter_tools/lib/src/base/build.dart#L210). Without that flag paths would be using original unresolved URIs.
