### ISSUE TITLE
Step 5 Add Functionality Errors When Attempting to Test

### ISSUE THREAD

**Issue by Outright-Graham** [flutter/flutter#153871]
Followed the project to a "T" and had massive errors

```
lib/main.dart:119:7: Error: 'App' is already declared in this scope.
class App extends StatelessWidget {
      ^^^
lib/main.dart:18:7: Context: Previous declaration of 'App'.
class App extends StatelessWidget {
      ^^^
lib/main.dart:15:41: Error: Couldn't find constructor 'App'.
    builder: ((context, child) => const App()),
                                        ^^^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling
file:///home/radbinadmin/Desktop/_prototypes/flutter-codelabs/firebase-get-to-know-flutter/step_02/lib/main.dart, which contains the
type: FunctionType(<invalid> Function(BuildContext, Widget?)).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3224)
#1      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3185)
#2      ProgramCompiler._emitFunctionTagged (package:dev_compiler/src/kernel/compiler.dart:3031)
#3      ProgramCompiler.visitFunctionExpression (package:dev_compiler/src/kernel/compiler.dart:7027)
#4      FunctionExpression.accept (package:kernel/ast.dart:8588)
#5      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3925)
#6      ProgramCompiler._emitNamedExpression (package:dev_compiler/src/kernel/compiler.dart:6306)
#7      ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6298)
#8      ProgramCompiler.visitConstructorInvocation (package:dev_compiler/src/kernel/compiler.dart:6520)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:6666)
#10     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3925)
#11     ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:6295)
#12     ProgramCompiler.visitStaticInvocation (package:dev_compiler/src/kernel/compiler.dart:6193)
#13     StaticInvocation.accept (package:kernel/ast.dart:6582)
#14     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3925)
#15     ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:4006)
#16     ExpressionStatement.accept (package:kernel/ast.dart:9128)
#17     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3834)
#18     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#19     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#20     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#21     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#22     new List.of (dart:core-patch/array_patch.dart:39)
#23     SetBase.toList (dart:collection/set.dart:119)
#24     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4019)
#25     Block.accept (package:kernel/ast.dart:9181)
#26     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3834)
#27     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3867)
#28     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3573)
#29     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2553)
#30     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3610)
#31     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3569)
#32     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3385)
#33     ProgramCompiler._emitLibraryFunction (package:dev_compiler/src/kernel/compiler.dart:2986)
#34     MappedIterator.moveNext (dart:_internal/iterable.dart:403)
#35     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#36     new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#37     new List.of (dart:core-patch/array_patch.dart:39)
#38     Iterable.toList (dart:core/iterable.dart:498)
#39     ProgramCompiler._emitLibraryProcedures (package:dev_compiler/src/kernel/compiler.dart:2912)
#40     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:758)
#41     List.forEach (dart:core-patch/growable_array.dart:417)
#42     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:486)
#43     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:221)
#44     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:870)
<asynchronous suspension>
#45     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:685)
<asynchronous suspension>
#46     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1385)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...             12.1s
Failed to compile application.
```

**Comment by danagbemava-nc** [comment]
Hi @Outright-Graham, this is a crash in the web compiler, what version of flutter/dart are you using? Please provide the output of `flutter doctor -v`. Can you also provide the code sample that you experienced the crash with?

**Comment by Outright-Graham** [comment]
Hello Daniel and thanks for getting back to me so quickly. I apologize
profusely for not supplying enough information.

I have decided to choose another tutorial and continue my efforts in the
fastest way possible. You can close this ticket, and have a great weekend.

-Graham

**Comment by danagbemava-nc** [comment]
Closing this for now. Please feel free to file a new issue with more details if you encounter this issue again. 

Thank you
