### ISSUE TITLE
[tool_crash] StackOverflowError: (null)

### ISSUE THREAD

**Issue by ninjagaru** [flutter/flutter#153820]
## Command
```
flutter run -d 00008020-00195CD63403002E
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StackOverflowError: (null)
```
#0      _StringBase._createOneByteString (dart:core-patch/string_patch.dart:248:3)
#1      _StringBase.createFromCharCodes (dart:core-patch/string_patch.dart:150:16)
#2      new String.fromCharCodes (dart:core-patch/string_patch.dart:21:24)
#3      _Utf8Decoder.decodeGeneral (dart:convert/utf.dart:668:31)
#4      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1746:14)
#5      _readFQDN (package:multicast_dns/src/packet.dart:165:24)
#6      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#7      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#8      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#9      _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#10     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#11     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#12     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#13     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#14     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#15     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#16     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#17     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#18     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#19     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#20     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#21     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#22     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#23     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
#24     _readFQDN (package:multicast_dns/src/packet.dart:147:38)
```
```
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.6.1 23G93 darwin-arm64, locale en-TH)
    • Flutter version 3.19.5 on channel stable at /Users/humansoft/fvm/versions/3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 months ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/humansoft/Libr

**Comment by danagbemava-nc** [comment]
Hi @ninjagaru, can you upgrade to the latest stable version of flutter (3.24.0 at the time of writing) to see if you still experience this issue?
