### ISSUE TITLE
[tool_crash] StateError: Bad state: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:45039/aNcinXekEQ4=/ws

### ISSUE THREAD

**Issue by qomosoloto** [flutter/flutter#153825]
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --flavor=development --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:45039/aNcinXekEQ4=/ws
```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:290:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```
```console
[!] Flutter (Channel master, 3.25.0-1.0.pre.13, on Manjaro Linux 6.9.12-1-MANJARO, locale zh_CN.UTF-8)
    • Flutter version 3.25.0-1.0.pre.13 on channel master at /home/matrixer/flutter-sdk
    ! The flutter binary is not on your path. Consider adding /home/matrixer/flutter-sdk/bin to your path.
    ! Warning: `dart` on your path resolves to /opt/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /home/matrixer/flutter-sdk. Consider adding /home/matrixer/flutter-sdk/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c5ae033e1 (2 天前), 2024-08-19 06:47:25 -0400
    • Engine revision 356d51d467
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/matrixer/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/matrixer/ides/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/matrixer/ides/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /home/matrixer/ides/idea-IU
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/matrixer/ides/ideaIU-2024.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 15 (API 35) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Manjaro Linux 6.9.12-1-MANJARO

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": Connection timed out

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.2.0-beta.2+111
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
camera-0.11.0+2
camera_android_camerax-0.6.7+2
camera_avfoundation-0.9.17+3
camera_web-0.3.5
camera_windows-0.2.5
connectivity_plus-6.0.5
device_info_plus-10.1.2
dynamic_color-1.7.0
espresso-0.4.0+1
file_selector-1.0.3
file_selector_android-0.5.1+6
file_selector_ios-0.5.3
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_web-0.9.4+2
file_selector_windows-0.9.3+2
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.21
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web
flutter_secure_storage_windows-3.1.2
integration_test
irondash_engine_context-0.5.4
lw_sysapi
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
printing-5.13.2
screen_retriever-0.1.9
share_plus-10.0.2
shared_preferences-2.3.2
shared_preferences_android-2.3.1
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
super_native_extensions-0.8.19
url_launcher-6.3.0
url_launcher_android-6.3.9
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
window_manager-0.4.2

**Comment by danagbemava-nc** [comment]
Hi @qomosoloto, how often do you get this crash? If it is frequent, can you provide the verbose output of the flutter command that is run by your IDE?
