### ISSUE TITLE
Start new app on Pixel 2 emulator.

### ISSUE THREAD

**Issue by purtcer** [flutter/flutter#15398]
## Steps to Reproduce

Start new app on Pixel 2 emulator.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target D:\Repos\barcodecollecter\lib\main.dart --output-file D:\Repos\barcodecollecter\build\app\intermediates\flutter\debug/app.flx --depfile D:\Repos\barcodecollecter\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --snapshot D:\Repos\barcodecollecter\build\app\intermediates\flutter\debug/snapshot_blob.bin --working-dir D:\Repos\barcodecollecter\build\app\intermediates\flutter\debug/flutter_assets

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xe5 (at offset 26)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#11     _StreamController._add (dart:async/stream_controller.dart:639)
#12     _StreamController.add (dart:async/stream_controller.dart:585)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1662)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#20     _StreamController._add (dart:async/stream_controller.dart:639)
#21     _StreamController.add (dart:async/stream_controller.dart:585)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1235)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:788)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.2.1-pre.59, on Microsoft Windows [Version 10.0.16299.248], locale ru-RU)
    • Flutter version 0.2.1-pre.59 at C:\Users\Сергей\Documents\GitRepos\Flutter
    • Framework revision 48bb5b7926 (25 hours ago), 2018-03-09 22:49:19 -0800
    • Engine revision 1d0da77995
    • Dart version 2.0.0-dev.33.0.flutter-b5b8080b2c

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:/Program Files/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:/Program Files/Android/SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jerrywell** [comment]
could be a dart 2.0 issue. ref: https://github.com/dart-lang/sdk/issues/31621

**Comment by Hixie** [comment]
We believe we have resolved this. Please let us know if this still happens for you.
