### ISSUE TITLE
"Linux Web Framework Tests" broken after recipe changes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#154025]
For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/879847/infra

```
[  +31 ms] Local engine auto-detection sky_engine in null is the same version in bin/cache.
[   +4 ms] Unable to detect local Flutter engine src directory.
           Either specify a dependency_override for the sky_engine package in your pubspec.yaml and ensure --package-root is set if necessary, or set the $FLUTTER_ENGINE environment variable, or use --local-engine-src-path to specify the path to the root of your flutter/engine repository.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      LocalEngineLocator.findEnginePath (package:flutter_tools/src/runner/local_engine.dart:98:7)
           <asynchronous suspension>
           #2      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:351:48)
           <asynchronous suspension>
           #3      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

```

**Comment by christopherfujino** [comment]
This recipes CL reverts 3 manual path-related changes and an autoroll: https://flutter-review.googlesource.com/c/recipes/+/59440

**Comment by christopherfujino** [comment]
Here's a re-schedule build post recipe change landing: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/23597/infra

**Comment by christopherfujino** [comment]
Tree is green
