### ISSUE TITLE
[go_router] Exception Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by Vedsaga** [flutter/flutter#154000]
### Steps to reproduce

Running this example linked below
https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/custom_stateful_shell_route.dart

### Expected results

There should not be `Exception caught by widgets library`

### Actual results

There is `Exception caught by widgets library`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Connecting to VM Service at ws://127.0.0.1:53498/R0A5oskHxQQ=/ws
Connected to the VM Service.
I/BLASTBufferQueue(32305): [SurfaceView[com.example.go_router_bug/com.example.go_router_bug.MainActivity]@0#1](f:0,a:0,s:0) onFrameAvailable the first frame is available
D/SurfaceView@aabeae8(32305): 179038952 setAlpha: alpha=1.0
I/SurfaceView(32305): 179038952 Changes: creating=false format=false size=false visible=false alpha=true hint=false visible=false left=false top=false z=false attached=true lifecycleStrategy=false
I/SurfaceView@aabeae8(32305): 179038952 Cur surface: Surface(name=null)/@0x8dd9b8d
I/SurfaceView@aabeae8(32305): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@aabeae8(32305): updateSurface: mSurfaceCreated = true surfaceChanged = false visibleChanged = false
I/SurfaceView(32305): 179038952 surfaceRedrawNeeded
I/SurfaceView(32305): 179038952 finishedDrawing
V/SurfaceView@aabeae8(32305): Layout: x=0 y=0 w=1080 h=2340, frame=Rect(0, 0 - 1080, 2340)
I/ViewRootImpl@a5c9e56[MainActivity](32305): Setup new sync=wmsSync-ViewRootImpl@a5c9e56[MainActivity]#2
I/ViewRootImpl@a5c9e56[MainActivity](32305): Creating new active sync group ViewRootImpl@a5c9e56[MainActivity]#3
I/ViewRootImpl@a5c9e56[MainActivity](32305): registerCallbacksForSync syncBuffer=false
D/SurfaceView(32305): 179038952 updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1080, 2340] surfaceSize = 1080x2340
I/SurfaceView@aabeae8(32305): uSP: rtp = Rect(0, 0 - 1080, 2340) rtsw = 1080 rtsh = 2340
I/SurfaceView@aabeae8(32305): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@aabeae8(32305): aOrMT: ViewRootImpl@a5c9e56[MainActivity] t = android.view.SurfaceControl$Transaction@e54f8e fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:369 
I/ViewRootImpl@a5c9e56[MainActivity](32305): mWNT: t=0xb4000079c3a45150 mBlastBufferQueue=0xb400007873a3ddd0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.SurfaceView.applyOrMergeTransaction:1598 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1666 
I/ViewRootImpl@a5c9e56[MainActivity](32305): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@a5c9e56[MainActivity](32305): mWNT: t=0xb4000079c3a544b0 mBlastBufferQueue=0xb400007873a3ddd0 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13841 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack> 
I/ViewRootImpl@a5c9e56[MainActivity](32305): Setting up sync and frameCommitCallback
I/BLASTBufferQueue(32305): [ViewRootImpl@a5c9e56[MainActivity]#0](f:0,a:0,s:0) onFrameAvailable the first frame is available
I/ViewRootImpl@a5c9e56[MainActivity](32305): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
D/OpenGLRenderer(32305): CFMS:: SetUp Pid : 32305    Tid : 32329


I/ViewRootImpl@a5c9e56[MainActivity](32305): reportDrawFinished seqId=0
I/ViewRootImpl@a5c9e56[MainActivity](32305): handleWindowFocusChanged: 1 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
D/ViewRootImpl@a5c9e56[MainActivity](32305): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007893a58f80}
D/InputMethodManagerUtils(32305): startInputInner - Id : 0
I/InputMethodManager(32305): startInputInner - IInputMethodManagerGlobalInvoker.startInputOrWindowGainedFocus
D/InputMethodManagerUtils(32305): startInputInner - Id : 0
I/InsetsController(32305): onStateChanged: host=com.example.go_router_bug/com.example.go_router_bug.MainActivity, from=android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:7209, state=InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mDisplayCutout=DisplayCutout{insets=Rect(0, 99 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(505, 0 - 575, 99), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2340 physicalDisplayWidth=1080 physicalDisplayHeight=2340 density={3.0} cutoutSpec={M 0,0 M 0,29 a 35,35 0 1,0 0,70 a 35,35 0 1,0 0,-70 Z} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=121, center=Point(121, 121)}, RoundedCorner{position=TopRight, radius=121, center=Point(959, 121)}, RoundedCorner{position=BottomRight, radius=121, center=Point(959, 2219)}, RoundedCorner{position=BottomLeft, radius=121, center=Point(121, 2219)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2340), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 99) rotation=0}, mDisplayShape=DisplayShape{ spec=-311912193 displayWidth=1080 displayHeight=2340 physicalPixelDisplaySizeRatio=1.0 rotation=0 offsetX=0 offsetY=0 scale=1.0}, mSources= { InsetsSource: {8ff80001 mType=navigationBars mFrame=[0,0][0,0] mVisible=true mFlags=[SUPPRESS_SCRIM]}, InsetsSource: {8ff80004 mType=systemGestures mFrame=[0,0][84,2340] mVisible=true mFlags=[]}, InsetsSource: {8ff80005 mType=mandatorySystemGestures mFrame=[0,2270][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {8ff80006 mType=tappableElement mFrame=[0,0][0,0] mVisible=true mFlags=[]}, InsetsSource: {8ff80024 mType=systemGestures mFrame=[996,0][1080,2340] mVisible=true mFlags=[]}, InsetsSource: {a6ae0000 mType=statusBars mFrame=[0,0][1080,99] mVisible=true mFlags=[]}, InsetsSource: {a6ae0005 mType=mandatorySystemGestures mFrame=[0,0][1080,133] mVisible=true mFlags=[]}, InsetsSource: {a6ae0006 mType=tappableElement mFrame=[0,0][1080,99] mVisible=true mFlags=[]}, InsetsSource: {3 mType=ime mFrame=[0,0][0,0] mVisible=false mFlags=[]}, InsetsSource: {27 mType=displayCutout mFrame=[0,0][1080,99] mVisible=true mFlags=[]} }
I/InsetsSourceConsumer(32305): applyRequestedVisibilityToControl: visible=false, type=ime, host=com.example.go_router_bug/com.example.go_router_bug.MainActivity
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 0
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 1
D/ProfileInstaller(32305): Installing profile for com.example.go_router_bug
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 0
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 1
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 0
I/ViewRootImpl@a5c9e56[MainActivity](32305): ViewPostIme pointer 1


════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.
The key [GlobalObjectKey int#0f3e9] was used by multiple widgets. The parents of those widgets were:
- _BranchNavigatorProxy-[StatefulShellBranch#63871](state: _BranchNavigatorProxyState#b8514)
- _BranchNavigatorProxy-[StatefulShellBranch#63871](state: _BranchNavigatorProxyState#82655)
A GlobalKey can only be specified on one widget at a time in the widget tree.


When the exception was thrown, this was the stack:
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3205:13)
framework.dart:3205
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3149:20)
framework.dart:3149
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:3144:36)
framework.dart:3144
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:3213:6)
framework.dart:3213
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3267:11)
framework.dart:3267
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3342:8)
framework.dart:3342
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
binding.dart:1169
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
binding.dart:1040
#13     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
platform_dispatcher.dart:837
#17     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
isolate_patch.dart:184
(elided 3 frames from class _Timer and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
I/BLASTBufferQueue_Java(32305): update, w= 1080 h= 2340 mName = ViewRootImpl@a5c9e56[MainActivity] mNativeObject= 0xb400007873a3ddd0 sc.mNativeObject= 0xb4000078a3a2fcd0 format= -3 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3017 android.view.ViewRootImpl.relayoutWindow:10131 android.view.ViewRootImpl.performTraversals:4110 android.view.ViewRootImpl.doTraversal:3288 android.view.ViewRootImpl$TraversalRunnable.run:11344 android.view.Choreographer$CallbackRecord.run:1689 
I/ViewRootImpl@a5c9e56[MainActivity](32305): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=true req=(1080,2340)0 dur=0 res=0x0 s={true 0xb400007893a58f80} ch=false seqId=0
I/ViewRootImpl@a5c9e56[MainActivity](32305): updateBoundsLayer: t=android.view.SurfaceControl$Transaction@d3981fd sc=Surface(name=Bounds for - com.example.go_router_bug/com.example.go_router_bug.MainActivity@0)/@0xdc59ef2 frame=2
I/ViewRootImpl@a5c9e56[MainActivity](32305): registerCallbackForPendingTransactions
I/ViewRootImpl@a5c9e56[MainActivity](32305): mWNT: t=0xb4000079c3a62e70 mBlastBufferQueue=0xb400007873a3ddd0 fn= 2 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$6.onFrameDraw:5635 android.view.ViewRootImpl$2.onFrameDraw:2146 android.view.ThreadedRenderer$1.onFrameDraw:792 
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel beta, 3.25.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.4037], locale en-IN)
    • Flutter version 3.25.0-0.1.pre on channel beta at C:\Users\harsh\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\harsh\fvm\versions\beta\bin\flutter, which is not inside your current Flutter SDK checkout at
      C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\harsh\fvm\versions\beta\bin\dart, which is not inside your current Flutter SDK checkout at
      C:\Users\harsh\fvm\default. Consider adding C:\Users\harsh\fvm\default\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3733fcb0e (2 days ago), 2024-08-21 10:27:04 -0500
    • Engine revision 062b3a72fc
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\harsh\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.92.2)
    • VS Code at C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (1 available)
    • SM G990B2 (mobile) • RZCX1046DPX • android-arm64 • Android 14 (API 34)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by iapicca** [comment]
works on dartpad

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/5b012e65-0e44-463d-8985-db3585b591e4">

**Comment by danagbemava-nc** [comment]
Hi @Vedsaga, can you provide steps to reproduce? I just tested on both android and iOS and I can't reproduce it. Seems like it doesn't reproduce on web either. See https://github.com/flutter/flutter/issues/154000#issuecomment-2307019582

**Comment by Vedsaga** [comment]
Sorry made mistake on my end, had made little changes in the original example code, it is figured out why it was happening.

The cause was that, I was using custom animation, in that multiple children was using the same key due to that it was happening.
