### ISSUE TITLE
Video player on Huawei Android 29 device does not play media

### ISSUE THREAD

**Issue by KonstantenKomkov** [flutter/flutter#154068]
### What package does this bug report belong to?

video_player

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Steps to reproduce

Run simple example of video player app. Problem in video_player_android 2.7.0 with 2.6.0 worked.
It may be related to https://github.com/flutter/flutter/issues/149721

### Expected results

Video is playing

### Actual results

Video not playing

### Code sample

<b>IMPELLER</b>

### Logs

```console
I/ExoPlayerImpl(22874): Init b456022 [AndroidXMedia3/1.4.0] [HWCLT, CLT-L29, HUAWEI, 29]
W/ple.food_drive(22874): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
W/VideoCapabilities(22874): Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities(22874): Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities(22874): Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities(22874): Unsupported profile 5 for video/mpeg2
I/chatty  (22874): uid=12958(com.example.food_driver) ExoPlayer:Playb identical 2 lines
I/VideoCapabilities(22874): Unsupported profile 5 for video/mpeg2
W/VideoCapabilities(22874): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(22874): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(22874): Unrecognized profile/level 32768/64 for video/mp4v-es
I/OMXClient(22874): IOmx service obtained
I/ACodec  (22874): In onAllocateComponent create compenent, codec name: OMX.hisi.video.decoder.avc
D/SurfaceUtils(22874): connecting to surface 0x7eb25e8010, reason connectToSurface
I/MediaCodec(22874): [OMX.hisi.video.decoder.avc] setting surface generation to 23422977
D/SurfaceUtils(22874): disconnecting from surface 0x7eb25e8010, reason connectToSurface(reconnect)
D/SurfaceUtils(22874): connecting to surface 0x7eb25e8010, reason connectToSurface(reconnect)
E/ACodec  (22874): [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) and dataspace 0x104
I/ACodec  (22874): onStart
I/HwExtendedUtils(22874): Set to window composer mode as 2
I/ACodec  (22874): gralloc usage: 0(OMX) => 0x2900(ACodec)
D/SurfaceUtils(22874): disconnecting from surface 0x7eb25e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(22874): connecting to surface 0x7eb25e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(22874): set up nativeWindow 0x7eb25e8010 for 1280x1280, color 0x30d, rotation 0, usage 0x2900
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 10 failed: -1010
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 9 failed: -1010
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] Allocating 8 buffers from a native window of size 2703360 on output port
W/Gralloc3(22874): allocator 3.x is not supported
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) and dataspace 0x104
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] Now handling output port settings change
I/ACodec  (22874): [OMX.hisi.video.decoder.avc] Output port now disabled.
I/HwExtendedUtils(22874): Set to window composer mode as 2
I/ACodec  (22874): gralloc usage: 0(OMX) => 0x2900(ACodec)
D/SurfaceUtils(22874): disconnecting from surface 0x7eb25e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(22874): connecting to surface 0x7eb25e8010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(22874): set up nativeWindow 0x7eb25e8010 for 1280x1280, color 0x30d, rotation 0, usage 0x2900
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 16 failed: -1010
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 15 failed: -1010
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 14 failed: -1010
W/ACodec  (22874): [OMX.hisi.video.decoder.avc] setting nBufferCountActual to 13 failed: -1010
E/ACodec  (22874): Failed to allocate output port buffers after port reconfiguration: (-1010)
E/ACodec  (22874): signalError(omxError 0x80001001, internalError -1010)
E/ACodec  (22874): Error occurred while disabling the output port
E/MediaCodec(22874): Codec reported err 0xfffffc0e, actionCode 0, while in state 6
D/SurfaceUtils(22874): disconnecting from surface 0x7eb25e8010, reason disconnectFromSurface
E/MediaCodecVideoRenderer(22874): Video codec error
E/MediaCodecVideoRenderer(22874):   java.lang.IllegalStateException
E/MediaCodecVideoRenderer(22874):       at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/MediaCodecVideoRenderer(22874):       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2450)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:145)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1485)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/MediaCodecVideoRenderer(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/MediaCodecVideoRenderer(22874):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/MediaCodecVideoRenderer(22874):       at android.os.Looper.loop(Looper.java:219)
E/MediaCodecVideoRenderer(22874):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(22874): Playback error
E/ExoPlayerImplInternal(22874):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1280, 1280, 25.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(22874):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(22874):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(22874):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(22874):   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.hisi.video.decoder.avc
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal(22874):       ... 3 more
E/ExoPlayerImplInternal(22874):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(22874):       at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/ExoPlayerImplInternal(22874):       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2450)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:145)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1485)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
E/ExoPlayerImplInternal(22874):       ... 6 more
E/ExoPlayerImplInternal(22874): Disable failed.
E/ExoPlayerImplInternal(22874):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(22874):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(22874):       at android.media.MediaCodec.flush(MediaCodec.java:2194)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
E/ExoPlayerImplInternal(22874):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
E/ExoPlayerImplInternal(22874):       at android.os.Handler.dispatchMessage(Handler.java:106)
E/ExoPlayerImplInternal(22874):       at android.os.Looper.loop(Looper.java:219)
E/ExoPlayerImplInternal(22874):       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Flutter Doctor output

Flutter 3.24.1

**Comment by huycozy** [comment]
Looks like this is similar to your old reported issue at https://github.com/flutter/flutter/issues/149721 and seems to relate to Impeller. I see the latest version 2.7.1 has reverted Impeller support (https://pub.dev/packages/video_player_android/changelog#271), can you check and confirm?

**Comment by matanlurey** [comment]
We rolled forward, so if it was valid before it is likely valid now.

**Comment by matanlurey** [comment]
@jonahwilliams Have we had to do anything special for a HUAWEI/29 device before?

Looks like (without looking deeper) possibly something to do with ImageReader+Android 29 (on Huawai)

**Comment by KonstantenKomkov** [comment]
With 2.7.1 version worked becouse version comment is "Revert Impeller support."

**Comment by matanlurey** [comment]
> With 2.7.1 version worked becouse version comment is "Revert Impeller support."

Konstanten, does this issue happen on the video player example application, or only your own codebase?

https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android/example

**Comment by KonstantenKomkov** [comment]
It's not very critical for me right now because I can use a different version. Now I don't have any projects with a video player, there used to be a lot. It seems enough that the problem is reproduced in the sample code from the video_player library.

**Comment by matanlurey** [comment]
Thanks, that is very useful. We'll try to acquire a test device and I'll leave this issue open for the time being.

**Comment by jonahwilliams** [comment]
@KonstantenKomkov what is the device model that you are seeing these issues on?

**Comment by KonstantenKomkov** [comment]
Huawei p20 pro

**Comment by jonahwilliams** [comment]
Thanks!

**Comment by jonahwilliams** [comment]
I can confirm that the AHB import does not work on certain Huawei devices, so I'm adding support for falling back to the old approach here:

https://github.com/flutter/engine/pull/54879

This makes the video player examples work for me and still supports vulkan.
