### ISSUE TITLE
'(int, SemanticsAction, ByteData) => void' is not a subtype of type 'SemanticsActionCallback' of 'callback'

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15421]
Produced a strange error when full restarting the hamilton project on Android
```
Performing full restart...
Restarted app in 3,038ms.
E/flutter (23290): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (23290): type '(int, SemanticsAction, ByteData) => void' is not a subtype of type 'SemanticsActionCallback' of 'callback'
E/flutter (23290): #0      Window.onSemanticsAction= (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/window.dart:433)
E/flutter (23290): #1      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:42:9)
E/flutter (23290): #2      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:241:24)
E/flutter (23290): #3      new BindingBase (package:flutter/src/foundation/binding.dart:51:5)
E/flutter (23290): #4      new BindingBase&GestureBinding (package:flutter/src/gestures/binding.dart:19:1)
E/flutter (23290): #5      new BindingBase&GestureBinding&ServicesBinding (package:flutter/src/services/binding.dart:19:1)
E/flutter (23290): #6      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/scheduler/binding.dart:189:1)
E/flutter (23290): #7      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/painting/binding.dart:15:1)
E/flutter (23290): #8      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart:24:1)
E/flutter (23290): #9      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart:234:1)
E/flutter (23290): #10     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart:891:1)
E/flutter (23290): #11     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:906:11)
E/flutter (23290): #12     runApp (package:flutter/src/widgets/binding.dart:698:25)
E/flutter (23290): #13     main (/data/user/0/com.hamilton.app/cache/hamilton-flutterZLUYWU/hamilton-flutter/lib/main.dart:22:5)
E/flutter (23290): <asynchronous suspension>
E/flutter (23290): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
E/flutter (23290): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

Though the local SDK's rendering/binding.dart's SDK is `void _handleSemanticsAction(int id, SemanticsAction action, ByteData args)` and the engine's SemanticsActionCallback signature has been same (https://github.com/flutter/engine/blame/master/lib/ui/window.dart#L17) for the past 3 months. 

No local engine used. Suspect some gradle issue perhaps.

**Comment by zoechi** [comment]
A lot has changed since then. I assume this is stale.
