### ISSUE TITLE
Object.noSuchMethod : Tried calling: run(Instance(length:2) of '_GrowableList', environment: null, workingDirectory: null)

### ISSUE THREAD

**Issue by veightz** [flutter/flutter#15420]
### Steps
```
➜   flutter doctor -v
```
> On `dev` branch

### Output
```
[✓] Flutter (Channel dev, v0.2.0, on Mac OS X 10.13.3 17D102, locale en-CN)
    • Flutter version 0.2.0 at /Users/veightz/Developer/flutter
    • Framework revision f8ac23cd86 (6 days ago), 2018-03-05 23:27:57 +0100
    • Engine revision a00f8e8bc0
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: b476089de70f6fd6)
Unhandled exception:
NoSuchMethodError: The method 'run' was called on null.
Receiver: null
Tried calling: run(Instance(length:2) of '_GrowableList', environment: null, workingDirectory: null)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      runAsync (package:flutter_tools/src/base/process.dart:224)
<asynchronous suspension>
#2      IOSWorkflow.macDevMode (package:flutter_tools/src/ios/ios_workflow.dart:45)
<asynchronous suspension>
#3      IOSWorkflow.validate (package:flutter_tools/src/ios/ios_workflow.dart:90)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/veightz/Developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by joshstilwell** [comment]
I'm also getting this error..

**Comment by jakeleveroni** [comment]
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D102, locale en-US)

I am getting the same error as well but on the beta channel

**Comment by jakeleveroni** [comment]
same issue on beta branch

**Comment by jimmy-han** [comment]
same program

**Comment by stjernstrom** [comment]
Same here, fresh setup following https://flutter.io/setup-macos/

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D102, locale en-SE)
    • Flutter version 0.2.3 at /Users/mathias/dev/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 0b407121866287fd)
Unhandled exception:
NoSuchMethodError: The method 'run' was called on null.
Receiver: null
Tried calling: run(Instance(length:2) of '_GrowableList', environment: null, workingDirectory: null)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      runAsync (package:flutter_tools/src/base/process.dart:227)
<asynchronous suspension>
#2      IOSWorkflow.macDevMode (package:flutter_tools/src/ios/ios_workflow.dart:45)
<asynchronous suspension>
#3      IOSWorkflow.validate (package:flutter_tools/src/ios/ios_workflow.dart:90)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/mathias/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

**Comment by veightz** [comment]
I fixed this problem by checking out `beta` branch...

**Comment by stjernstrom** [comment]
@veightz beta did not work for me, but when using Alpha it worked for me

**Comment by VishPanwar** [comment]
same problem .

**Comment by VishPanwar** [comment]
I solved the problem by making sure that Android studio executes the android application without any errors. I don't know what exactly is the problem but its related to android studio.

**Comment by thejoker101** [comment]
Updating the older version of Android Studio also fixed this issue for me.

**Comment by somit** [comment]
Checking out alpha worked for me. Beta has same issue. Even updating Android Studion didn't fix the issue.

**Comment by jimmy-han** [comment]
yes,alpha work for me too

**Comment by zoechi** [comment]
Sorry for the late response. Is this still an issue for anyone?
