### ISSUE TITLE
[tool_crash] StateError: Bad state: Failed to start Dart Development Service

### ISSUE THREAD

**Issue by shen-lin** [flutter/flutter#154315]
## Command
```sh
flutter run -d macos --enable-impeller
```

## Steps to Reproduce
1. Follow flutter GPU steps as described in https://medium.com/flutter/getting-started-with-flutter-gpu-f33d497b7c11#d558
2. Without `renderPass.draw();`, macos dev window is launched with blue background.
3. Add `renderPass.draw();`, macos window launched followed by immediate close.  Console log:

```
A Dart VM Service on macOS is available at: http://127.0.0.1:51637/IGsGiEe8o0k=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51637/IGsGiEe8o0k=/
Lost connection to device.
```

## Logs
StateError: Bad state: Failed to start Dart Development Service
```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:290:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel main, 3.25.0-1.0.pre.167, on macOS 14.6 23G80 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.25.0-1.0.pre.167 on channel main at /Users/shenlin/Development/native/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 32e29fc39b (2 hours ago), 2024-08-28 16:09:05 -0700
    [32m•[39m Engine revision 8d248aead3
    [32m•[39m Dart version 3.6.0 (build 3.6.0-175.0.dev)
    [32m•[39m DevTools version 2.39.0-dev.15

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.92.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m I830561’s iPhone (mobile)       • 00008110-000C6D081E87801E • ios            • iOS 17.6.1 21G93
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6 23G80 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.85

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: main
**Creation framework version**: 32e29fc39bc680ca03adc62079ca8a7a1c5f3e9c

**Comment by shen-lin** [comment]
Problem solved thus closing the issue.

**Comment by kpss01** [comment]
@shen-lin how did you solve the above issue?
