### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by usmanrajpoot534** [flutter/flutter#154329]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: Access is denied.
, errno = 5
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:170:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:236:46)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:33:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:1110:24)
#5      new ResidentWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:107:8)
#6      DwdsWebRunnerFactory.createWebRunner (package:flutter_tools/src/isolated/resident_web_runner.dart:63:12)
#7      RunCommand.createRunner (package:flutter_tools/src/commands/run.dart:676:32)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:798:35)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4780], locale en-US)
    [32m•[39m Flutter version 3.22.3 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision b0850beeb2 (6 weeks ago), 2024-07-16 21:43:41 -0700
    [32m•[39m Engine revision 235db911ba
    [32m•[39m Dart version 3.4.4
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\usman\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.38)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.35026.282
    [31m✗[39m The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at C:\Users\usman\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.86
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.42

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 46787ee49c1fd80ab603f0702733edab54653aef
### Plugins
file_picker-8.0.7
flutter_plugin_android_lifecycle-2.0.21
smart_auth-2.0.0

**Comment by darshankawar** [comment]
@usmanrajpoot534 
Do you get this error everytime consistently upon running `flutter run` ?
Can you check if temporary directory is read only instead of writeable ? If so, try making it writeable and re-run to check if it resolves the crash or not.
