### ISSUE TITLE
Flutter testing configuration

### ISSUE THREAD

**Issue by anandb5** [flutter/flutter#15433]
**I just started setting up our Flutter App testing added the following dependencies .
 in pubspec.yaml 
flutter_driver: sdk: flutter
test_driver folder in project
and add test file with extension .dart
and created Flutter-Driver folder for creating scripts.
But unfortunately, I can't run the test. I got the following error**
# while debugging 

exception = DriverError: Could not determine URL to connect to application.
Either the VM_SERVICE_URL environment variable should be set, or
when you run the script

#  while running the script
C:\Users\KRISHNA_CHIMPLE\Documents\GitHub\git\flutter\bin\cache\dart-sdk\bin\dart.exe --checked --enable-vm-service:65143 C:\Users\KRISHNA_CHIMPLE\Downloads\flutter_app-master\flutter_app-master\test_driver\Navigation_test.dart
Observatory listening on http://127.0.0.1:65143/

00:00 +0: flutter app transitions (setUpAll)
00:00 +0 -1: flutter app transitions (setUpAll) [E]
 DriverError: Could not determine URL to connect to application.
 Either the VM_SERVICE_URL environment variable should be set, or an explicit
 URL should be provided to the FlutterDriver.connect() method.
 Original error: null
 Original stack trace:
 null
     
 package:flutter_driver/src/driver/driver.dart 154:7           FlutterDriver.connect
 ===== asynchronous gap ===========================
 dart:async/future_impl.dart 22                                _Completer.completeError
 package:flutter_driver/src/driver/driver.dart                 FlutterDriver.connect
 ===== asynchronous gap ===========================
 dart:async/zone.dart 1047                                     _CustomZone.registerCallback
 dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
 dart:async/schedule_microtask.dart 147                        scheduleMicrotask
 dart:async/future.dart 198                                    new Future.microtask
 package:flutter_driver/src/driver/driver.dart 150:85          FlutterDriver.connect
 test_driver\Navigation_test.dart 12:36                        main.<fn>.<fn>
 ===== asynchronous gap ===========================
 dart:async/zone.dart 1047                                     _CustomZone.registerCallback
 dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
 dart:async/schedule_microtask.dart 147                        scheduleMicrotask
 dart:async/future.dart 198                                    new Future.microtask
 test_driver\Navigation_test.dart 11:23                        main.<fn>.<fn>

**Comment by Hemalatha195** [comment]
Hello
I also tried to run my test script for me also getting the same error, is there any dependencies or packages I have to add before running the script please help me how to configure.

**Comment by AvinashPratap** [comment]
I tried and not able to run the my script in my application some Flutter driver issue is coming.
The script is only running on Flutter Gallery only or Flutter Application only.
Can someone help me find the solution????

**Comment by Biswajeet-chimple** [comment]
I tried to do the same with adding same dependencies in pubspec.yaml
i.e. flutter_driver: sdk: flutter
test_driver folder in the project
and added  test file with extension .dart
inside another test file but it is not working. It's saying uri not found error. Please help me to configure.

**Comment by zoechi** [comment]
What's the output of `flutter doctor -v`?

**Comment by anandb5** [comment]
In my system Flutter is configured to develop Android Apps. 
Ios platform is not set anyhow we more inclined towards Android only
 This is Output of  flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-IN)
    • Flutter version 0.1.5 at /Users/hadoop/Desktop/git/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hadoop/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/hadoop/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.

**Comment by anandb5** [comment]
@zoechi Any update?

**Comment by zoechi** [comment]
@anandb5 sorry, no idea. Perhaps someone from the Flutter team knows more.

**Comment by franzejr** [comment]
Any update?

**Comment by zoechi** [comment]
@franzejr please provide more information about your issue.

**Comment by gordianknot1981** [comment]
I've encountered this while running test in android studio, but performs well while triggering test using command line.  Hope this info can help.

**Comment by jonahwilliams** [comment]
Are you running the test via `flutter drive` or are you executing it directly with dart?

**Comment by DK15** [comment]
@anandb5, @Hemalatha195 , @AvinashPratap , @franzejr. Not sure if you are still looking for this solution, but I posted my working answer on SO on this. 

https://stackoverflow.com/questions/53361718/how-to-automate-flutter-integration-testing-command/56286951#56286951

**Comment by Hixie** [comment]
I don't understand the actual bug described here. Please provide steps to reproduce starting from `flutter create` and describing all the files that are changed and the commands that are run. We can't resolve problems we don't understand. :-)

**Comment by dnfield** [comment]
Flutter driver tests need to be run via `flutter drive`. This bug is occurring when the user is trying to invoke `dart.exe` directly, which does not set up the right environment variables or command line options (or even compile the assets the way they're supposed to be).

The only possible bug we might have is that we should fail more gracefully somehow if someone invokes a driver test via `dart`.

**Comment by dnfield** [comment]
E.g. when we print that error about the VM_SERVICE_URL variable, we could ask the user `Did you invoke this test via 'flutter drive'?`

**Comment by harasadina** [comment]
is there a solution for this problem? i run the test script from terminal using flutter driver find message 'connecting flutter app ...' url is always different to 'Observatory listening on ...' url, followed by this error.
When i try specifying the url in dartVmServiceUrl the error gone but the console keeps printing 'It is taking an unusually long time to connect to the VM...'

**Comment by harasadina** [comment]
here is my flutter doctor

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by TheBlueaa** [comment]
请帮帮我

**Comment by ZeroOneTV** [comment]
I had a similar problem here, which generated the error: 
![image](https://user-images.githubusercontent.com/31084564/120026152-0862f700-bfc8-11eb-8381-d9d6a48fca92.png)

To fix it (I use windows 10), I added 'ANDROID_SDK_ROOT' as a name in the environment variables and added the base folder of the SDK that android studio works with

Obviously, I did it in a separate file to run the integration test
I have the base class for setting the environment and the target class to run the test itself

I don't know if it's going to be the way you're doing, but it was a problem that occurred to me and that's how I solved it
I hope it helps :)

**Comment by ZeroOneTV** [comment]
I had a similar problem here, which generated the error: 
![Sem título](https://user-images.githubusercontent.com/31084564/120026775-f6358880-bfc8-11eb-85e2-5600cd350152.png)

To fix it (I use windows 10), I added 'ANDROID_SDK_ROOT' as a name in the environment variables and added the base folder of the SDK that android studio works with

Obviously, I did it in a separate file to run the integration test
I have the base class for setting the environment and the target class to run the test itself

I don't know if it's going to be the way you're doing, but it was a problem that occurred to me and that's how I solved it
I hope it helps :)

**Comment by maheshmnj** [comment]
I ran into this today when running `fluter test integration_test` when following the [integration test docs](https://docs.flutter.dev/cookbook/testing/integration/introduction). I did not specify the `dartVmServiceUrl`.

```console
mahesh@Maheshs-MacBook-Air-M1 sample % flutter test integration_test
00:07 +0: loading /Users/mahesh/Desktop/server/sample/integration_test/app_test.dart                                                                                                       R00:08 +0: loading /Users/mahesh/Desktop/server/sample/integration_test/app_test.dart                                                                                                  974ms
00:57 +0: loading /Users/mahesh/Desktop/server/sample/integration_test/app_test.dart                                                                                                       
01:24 +0: loading /Users/mahesh/Desktop/server/sample/integration_test/app_test.dart                                                                                                  27.4s
Xcode build done.                                           76.0s
01:28 +0: end-to-end test tap on the floating action button, verify counter                                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following DriverError was thrown running a test:
Could not determine URL to connect to application.
Either the VM_SERVICE_URL environment variable should be set, or an explicit URL should be provided
to the FlutterDriver.connect() method.

When the exception was thrown, this was the stack:
#0      VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:78:7)
#1      FlutterDriver.connect (package:flutter_driver/src/driver/driver.dart:157:35)
#2      main.<anonymous closure>.<anonymous closure> (file:///Users/mahesh/Desktop/server/sample/integration_test/app_test.dart:16:60)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/mahesh/Desktop/server/sample/integration_test/app_test.dart:14:9)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  tap on the floating action button, verify counter
════════════════════════════════════════════════════════════════════════════════════════════════════
01:28 +0 -1: end-to-end test tap on the floating action button, verify counter [E]                                                                                                         
  Test failed. See exception logs above.
  The test description was: tap on the floating action button, verify counter
  
01:28 +0 -1: Some tests failed. 
```

<details>
<summary>sample test</summary>


`integration_test/app_test.dart`
```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:flutter_driver/flutter_driver.dart' as d;
import 'package:integration_test/integration_test_driver_extended.dart';
import 'package:sample/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
        (WidgetTester tester) async {
      app.main();
      final d.FlutterDriver driver = await d.FlutterDriver.connect();

      //   await integrationDriver(
      //     driver: driver,
      //     onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
      //       print('screenshot taken');
      //       return true;
      //     },
      //   );

      await tester.pumpAndSettle();

      // Verify the counter starts at 0.
      expect(find.text('0'), findsOneWidget);

      // Finds the floating action button to tap on.
      final Finder fab = find.byTooltip('Increment');

      // Emulate a tap on the floating action button.
      await tester.tap(fab);

      // Trigger a frame.ch
      await tester.pumpAndSettle();

      //   final pixels = await driver.screenshot();
      //   final File file = File('../screenshots/screenshot.png');
      //   await file.writeAsBytes(pixels);
      // Verify the counter increments by 1.
      expect(find.text('1'), findsOneWidget);
    });
  });
}

```
</details>

**Comment by matanlurey** [comment]
Flutter driver tests need to be run via flutter drive. 

There is no workaround.
