### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by fernan8** [flutter/flutter#154458]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:963:57)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:583:56)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:334:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel , 3.24.1, on Arch Linux 6.10.7-arch1-1, locale pt_BR.UTF-8)
    [32m•[39m Flutter version 3.24.1 on channel  at /usr/lib/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19 03:14:08
    [32m•[39m Engine revision c9b9d5780da3
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 18.1.8
    [32m•[39m cmake version 3.30.3
    [32m•[39m ninja version 1.12.1
    [32m•[39m pkg-config version 2.1.1

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin version 79.0.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Arch Linux 6.10.7-arch1-1
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 127.0.6533.119

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: 
**Creation framework version**: archlinuxaur0000000000000000000000000000

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/68958

**Comment by fernan8** [comment]
resolvi o meu problema removendo todos os arquivos e reinstalando de novo inclusive as versões de extensão para linux que tem na galeria package do arch linux remove todo o cache  e os bin depois de atualizar o meu começou a não abrir direto no linux
