### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by ivrachni** [flutter/flutter#154401]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22000.1574], locale en-US)
    [32m•[39m Flutter version 3.24.1 on channel stable at C:\Users\Giorgos\Desktop\dev\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5874a72aa4 (10 days ago), 2024-08-20 16:46:00 -0500
    [32m•[39m Engine revision c9b9d5780d
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Giorgos\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.10.35027.167
    [31m✗[39m Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[32m[✓][39m VS Code (version 1.82.1)
    [32m•[39m VS Code at C:\Users\Giorgos\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    [32m•[39m Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1574]
    [32m•[39m Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.31

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bae5e49bc2a867403c43b2aae2de8f8c33b037e4
### Plugins
firebase_auth-5.2.0
firebase_auth_web-5.12.6
firebase_core-3.4.0
firebase_core_web-2.17.5
google_sign_in-6.2.1
google_sign_in_android-6.1.28
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by darshankawar** [comment]
@ivrachni 
Do you get this error everytime while running `flutter run` ? 
Are there any specific steps that you can take that triggers this crash ?
