### ISSUE TITLE
[tool_crash] StateError: Bad state: Failed to start Dart Development Service

### ISSUE THREAD

**Issue by 4refr0nt** [flutter/flutter#154436]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. clone https://github.com/yandex/mapkit-flutter-demo
2. put .env file with your API_KEY
3. flutter run

## Logs
StateError: Bad state: Failed to start Dart Development Service
```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:116:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel master, 3.25.0-1.0.pre.211, on macOS 14.6.1 23G93 darwin-arm64, locale ru-RU)
    [32m•[39m Flutter version 3.25.0-1.0.pre.211 on channel master at /Users/victor/dev/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9fc160b11c (23 minutes ago), 2024-08-30 11:22:06 -0700
    [32m•[39m Engine revision 94487cc576
    [32m•[39m Dart version 3.6.0 (build 3.6.0-198.0.dev)
    [32m•[39m DevTools version 2.39.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/victor/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/victor/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/victor/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (6 available)
    [32m•[39m victor (mobile)                 • 00008030-000C388E3CB8802E            • ios            • iOS 17.5.1 21F90
    [32m•[39m iPad Victor (mobile)            • 00008030-00034859027B402E            • ios            • iOS 17.6.1 21G93
    [32m•[39m iPhone 15 (mobile)              • CAA40D73-378F-4A1E-87DE-6F08A765C2DC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    [32m•[39m macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.127

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 41456452f29d64e8deb623a3c927524bcf9f111b
### Plugins
flutter_plugin_android_lifecycle-2.0.22
yandex_maps_mapkit-4.6.1-beta3

**Comment by darshankawar** [comment]
> 2\. put .env file with your API_KEY

@4refr0nt The repo has two different folders. Where do we need to create .env file ? Also, in order to get api key, we will need to create an account with yandex. 
Is that the only log you get ? Can you provide complete error log ?
