### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by Fayziddin2000** [flutter/flutter#154540]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1721:14)
#2      VmService.callMethod (package:vm_service/src/vm_service.dart:1712:12)
#3      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
#4      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:913:51)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:304:63)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-UZ)
    [32m•[39m Flutter version 3.24.1 on channel stable at /Users/f.buriyev/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    [32m•[39m Engine revision c9b9d5780d
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/f.buriyev/Library/Android/sdk
    [31m✗[39m cmdlin

**Comment by darshankawar** [comment]
@Fayziddin2000 
Can you provide exact replication steps ? Does this error occur everytime you run the said command ?
