### ISSUE TITLE
Calling VirtualDisplayController::resize() just before VirtualDisplayController::dispose() causes a crash

### ISSUE THREAD

**Issue by andriiudovenko** [flutter/flutter#154613]
### Steps to reproduce

In PlatformViewsController.java, there is a channelHandler object that implements the PlatformViewsChannel.PlatformViewsHandler interface. This interface includes two methods: resize() and dispose(). If resize() is called immediately before dispose(), it may lead to a crash.

1) When resize() is called with viewId = 0, it triggers a call to vdController.resize(). This call includes a Runnable object (lambda) as its third parameter, which is added to the message queue using View::postDelayed().
![1](https://github.com/user-attachments/assets/673e9dfe-0ca8-4bd7-aa8e-20f38dbc6921)
![2](https://github.com/user-attachments/assets/c16810fe-9bd5-47c9-8910-48e08b45deac)
![3](https://github.com/user-attachments/assets/8b4a53a0-24b9-440a-8203-dd67b4b71f1d)

2) Then we call the dispose() function, which invokes vdController.dispose() and removes vdController from the HashMap.
![4](https://github.com/user-attachments/assets/1599facb-2fd6-4252-98f4-5281357153d1)

3) After calling dispose(), the lambda previously added to the message queue using View::postDelayed() begins execution. Here, we attempt to retrieve the dimensions of the render target: vdController.getRenderTargetWidth(), vdController.getRenderTargetHeight().
![5](https://github.com/user-attachments/assets/c3f4fd33-64cc-4f59-b954-294dfc6ee8b1)

4) In VirtualDisplayController::getRenderTargetWidth() we call renderTarget.getWidth()
![6](https://github.com/user-attachments/assets/75f7f32e-ac9c-44ec-94b0-2da9508879eb)

5) Inside the SurfaceProducerPlatformViewRenderTarget, the producer object was released when vdController.dispose() was called, resulting in producer being null.
![7](https://github.com/user-attachments/assets/1994bf72-e83e-41e4-8169-7115fb5719ac)

### Expected results

Calling VirtualDisplayController::resize() just before VirtualDisplayController::dispose() shouldn't cause a crash

### Actual results

The app is crashed.

### Code sample

<details open><summary>Code sample</summary>

No code. This issue is obvious from the attached screenshots of Flutter code from the steps to reproduce section.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Crash log</summary>
08-02 15:25:22.167 18044 18044 E AndroidRuntime: FATAL EXCEPTION: main
08-02 15:25:22.167 18044 18044 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int io.flutter.view.TextureRegistry$SurfaceProducer.getWidth()' on a null object reference
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at io.flutter.plugin.platform.SurfaceProducerPlatformViewRenderTarget.getWidth(SurfaceProducerPlatformViewRenderTarget.java:25)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at io.flutter.plugin.platform.VirtualDisplayController.getRenderTargetWidth(VirtualDisplayController.java:132)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController$1.lambda$resize$0$io-flutter-plugin-platform-PlatformViewsController$1(PlatformViewsController.java:352)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController$1$$ExternalSyntheticLambda0.run(Unknown Source:8)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
08-02 15:25:22.167 18044 18044 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@andriiudovenko 
Can you provide `flutter doctor -v` so as to know in which version is this crash occuring ?

**Comment by andriiudovenko** [comment]
[✓] Flutter (Channel stable, 3.22.3, on Ubuntu 22.04.4 LTS 6.8.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.22.3 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (7 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/audovenko/Android/Sdk/
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.23.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/audovenko/android-studio-2023.3.1.20-linux/android-studio
    • Flutter plugin version 80.0.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.4 LTS 6.8.0-40-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.126

**Comment by darshankawar** [comment]
Thanks for the update @andriiudovenko 
Although you mentioned code sample is not required, but in order to properly address the issue, it would be helpful to have a  reproducible code sample that we can also verify at our end and to analyze further.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping the issue open and labeling for team's tracking.

**Comment by reidbaker** [comment]
@johnmccutchan FYI, on a first pass does the suggested fix look like what we would want to implement or would you want to fix the race condition another way.

**Comment by nagendiran89** [comment]
My app also affected by this issue from November 12. Because I have updated flutter from 2.10.5 on the date. Then I found this issue in play console. Affected by many type of android versions.
Crash Log:
`Exception java.lang.NullPointerException: Attempt to invoke interface method 'int io.flutter.view.TextureRegistry$SurfaceProducer.getWidth()' on a null object reference
  at io.flutter.plugin.platform.SurfaceProducerPlatformViewRenderTarget.getWidth (SurfaceProducerPlatformViewRenderTarget.java:25)
  at io.flutter.plugin.platform.VirtualDisplayController.getRenderTargetWidth (VirtualDisplayController.java:132)
  at io.flutter.plugin.platform.PlatformViewsController$1.lambda$resize$0$io-flutter-plugin-platform-PlatformViewsController$1 (PlatformViewsController.java:352)
  at io.flutter.plugin.platform.PlatformViewsController$1$$ExternalSyntheticLambda0.run (Unknown Source:8)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:204)
  at android.os.Looper.loop (Looper.java:291)
  at android.app.ActivityThread.main (ActivityThread.java:8134)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:588)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1019)`
![Screenshot 2024-11-16 104129](https://github.com/user-attachments/assets/6af914df-6081-4267-a5a3-b2a65bba937e)

**Comment by hariharan-raja** [comment]
@darshankawar  We are also facing same issue . Please find below log. 
`java.lang.NullPointerException: Attempt to invoke interface method 'int io.flutter.view.TextureRegistry$SurfaceProducer.getWidth()' on a null object reference
                                                                                                    	at io.flutter.plugin.platform.D.getWidth(Unknown Source:2)
                                                                                                    	at io.flutter.plugin.platform.F.f(Unknown Source:4)
                                                                                                    	at io.flutter.plugin.platform.w$a.k(Unknown Source:24)
                                                                                                    	at io.flutter.plugin.platform.w$a.j(Unknown Source:0)
                                                                                                    	at io.flutter.plugin.platform.v.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by Mohit8G** [comment]
Can we get some timelines regarding this issue, is our crash log are impacting day by day.
<img width="1130" alt="Screenshot 2025-01-05 at 12 54 02 AM" src="https://github.com/user-attachments/assets/5be29270-389f-4eeb-8e4d-c8b293e00619" />

**Comment by reidbaker** [comment]
Hey folks,
To determine if a bug is being worked on, look at the assignee and priority.  If this bug is not assigned to anyone right now, it means no one is actively working on it. If it is assigned, the engineer working on it should have set a priority. You can read more about the priorities we use on our [issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed) page.

If it is not assigned, it is available for anyone to work on. If you feel this issue needs to be escalated, see [escalating an issue](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#escalating-an-issue-that-has-the-wrong-priority).

**Comment by iamrishavraj1** [comment]
Hey,
any solutions for this issue?

**Comment by giorgio79** [comment]
@andriiudovenko  have you Implemented your suggestion? Just started getting this error and Google Play is burying my app due to "bad behaviour" crash rate.

**Comment by andriiudovenko** [comment]
> [@andriiudovenko](https://github.com/andriiudovenko) have you Implemented your suggestion? Just started getting this error and Google Play is burying my app due to "bad behaviour" crash rate.

No, I haven't, I can't change Flutter code. My suggestion was as a possible way to solve the problem for the Flutter team.

**Comment by giorgio79** [comment]
PS in my case, it seems the issue was related to an AnimatedList where the items got out of sync from the originating list, and the itemBuilder got some invalid indexes. Adding an index check, suggedted by chatgpt helped 👍  

```
                    AnimatedList(
                      shrinkWrap: true,
                      physics: const ClampingScrollPhysics(),
                      key: widget.myKey,
                      initialItemCount: widget.myList.length,
                      itemBuilder: (BuildContext context, int userIndex,
                          Animation<double> animation) {
                        if (userIndex < 0 ||
                            userIndex >= widget.myList.length) {
                          log.d("Index out of bounds: $userIndex");
                          return const SizedBox(); // Prevents invalid index access
                        } else { .... display item here
```

**Comment by giorgio79** [comment]
I just spotted in my Crashlytics for this error the following key called flutter_error_exception
Looks like Google maps was involved. Any of you guys have google maps in your app?

![Image](https://github.com/user-attachments/assets/f2f66171-28b2-4313-9c3d-7b2147472210)


  ```
| PlatformException(com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view. Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions., c, Cause: null, Stacktrace: com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view. Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions. at com.google.maps.api.android.lib6.common.m.h(:com.google.android.gms.dynamite_mapsdynamite@250335029@25.03.35 (190400-0):8) at com.google.maps.api.android.lib6.gmm6.api.c.l(:com.google.android.gms.dynamite_mapsdynamite@250335029@25.03.35 (190400-0):27) at com.google.maps.api.android.lib6.impl.ae.a(:com.google.android.gms |  
-- | -- | --

```

**Comment by nagendiran89** [comment]
@giorgio79 Yes, I have using google maps in my app.

**Comment by Mojo1917** [comment]
I encountered the same issue when using the `mapbox_maps_flutter` package. The crash occurs in about 70% of app starts on Android when a virtual display is added to the widget tree and then immediately removed, such as when navigating with Navigator.pushReplacement.

I am using a Pixel 5 with the latest software updates.

I've provided additional details in a related discussion: mapbox/mapbox-maps-flutter#887.

The issue can be reproduced with the following minimal code (ensure a valid Mapbox token is set):
```
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';

void main() {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  MapboxOptions.setAccessToken("<TOKEN>");
  runApp(MaterialApp(
    home: InitialPage(),
  ));
}

class InitialPage extends StatefulWidget {
  @override
  _InitialPageState createState() => _InitialPageState();
}

class _InitialPageState extends State<InitialPage> {
  @override
  void initState() {
    super.initState();
    Future.delayed(Duration(milliseconds: 100), () {
      Navigator.pushReplacement(
          context, MaterialPageRoute(builder: (_) => AnotherPage()));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: MapWidget(
        textureView: false,
        androidHostingMode: AndroidPlatformViewHostingMode.TLHC_VD,
      ),
    );
  }
}

class AnotherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text("Another Page")),
    );
  }
}
```

**Error logs**
> FATAL EXCEPTION: main
                                                                                                    Process: XXX, PID: 15063
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'int io.flutter.view.TextureRegistry$SurfaceProducer.getWidth()' on a null object reference
                                                                                                    	at io.flutter.plugin.platform.SurfaceProducerPlatformViewRenderTarget.getWidth(SurfaceProducerPlatformViewRenderTarget.java:25)
                                                                                                    	at io.flutter.plugin.platform.VirtualDisplayController.getRenderTargetWidth(VirtualDisplayController.java:132)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1.lambda$resize$0$io-flutter-plugin-platform-PlatformViewsController$1(PlatformViewsController.java:351)
                                                                                                    	at io.flutter.plugin.platform.PlatformViewsController$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Flutter doctor:**
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.1, on macOS 15.3.1 24D70 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.98.0)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by giorgio79** [comment]
@johnmccutchan could you check @reidbaker 's comment from 2024?
"@johnmccutchan FYI, on a first pass does the suggested fix look like what we would want to implement or would you want to fix the race condition another way."

I am happy to chip in to a fix if someone wants to tackle this one.

**Comment by johnmccutchan** [comment]
@giorgio79 The proposed fix (returning early in the callback if the view isn't registered for virtual display) looks correct to me.

**Comment by lloydurbino** [comment]
Do we have a timeline on when can we include the fix for this? Thanks.

**Comment by orestesgaolin** [comment]
I hope that can be helpful to reproduce - this is a list of devices that are affected by this crash that we can find in Crashlytics. We cannot reproduce it internally, but we see hundreds of users getting this particular crash. It is affecting all Android versions we support (10, 11, 12, 13, 14, 15). I own SM-G991B but was not able to reproduce it too.

<details>

```
Blackview	BV4900Pro
Fairphone	FP3
Fairphone	FP4
Google	Pixel 2
Google	Pixel 2 XL
Google	Pixel 3a
Google	Pixel 4a
Google	Pixel 4a (5G)
Google	Pixel 5
HMD Global	Nokia 3.4
HMD Global	Nokia 7 plus
HMD Global	Nokia 8 Sirocco
HMD Global	Nokia C12
HMD Global	Nokia C30
HMD Global	Nokia XR20
HUAWEI	BLA-L29
HUAWEI	COL-L29
HUAWEI	ELE-L29
HUAWEI	EML-L09
HUAWEI	EML-L29
HUAWEI	HRY-LX1T
HUAWEI	MAR-LX1A
HUAWEI	POT-LX1
HUAWEI	SNE-LX1
HUAWEI	STK-L22
HUAWEI	STK-LX1
HXY	MP06
Hisense	HLTE556N
LGE	LM-G710
LGE	LM-G850
LGE	LM-X430
OPPO	CPH2021
OPPO	CPH2135
OPPO	CPH2269
OPPO	CPH2271
OPPO	CPH2273
OnePlus	ONEPLUS A5000
OnePlus	ONEPLUS A5010
OnePlus	ONEPLUS A6003
Sony	H8324
Sony	J9210
Sony	XQ-CQ54
Volla	Volla Phone
Xiaomi	21061119DG
Xiaomi	2109119DG
Xiaomi	22011119UY
Xiaomi	2201116SG
Xiaomi	2201117TY
Xiaomi	M1908C3JGG
Xiaomi	M2003J15SC
Xiaomi	M2101K6G
Xiaomi	M2101K9AG
Xiaomi	Mi 10
Xiaomi	Mi 9 Lite
Xiaomi	Mi 9T
Xiaomi	Mi A3
Xiaomi	Redmi Note 7
Xiaomi	Redmi Note 8
Xiaomi	Redmi Note 8T
asus	ASUS_Z01RD
motorola	moto e20
motorola	moto e30
motorola	moto e32
motorola	moto g power
motorola	moto g power (2021)
motorola	moto g pure
motorola	moto g stylus
motorola	moto g stylus 5G (2022)
motorola	moto g(10)
motorola	moto g(30)
motorola	moto g(60)
motorola	moto g(7) plus
motorola	moto g(8)
motorola	moto g(8) plus
motorola	moto g(8) power
motorola	moto g(9) play
motorola	moto g(9) plus
motorola	moto g04
motorola	moto g31(w)
motorola	moto g42
motorola	motorola one
motorola	motorola one 5G ace
motorola	motorola one hyper
motorola	motorola one zoom
samsung	SM-A057F
samsung	SM-A057G
samsung	SM-A105FN
samsung	SM-A115F
samsung	SM-A125F
samsung	SM-A127F
samsung	SM-A135F
samsung	SM-A136B
samsung	SM-A137F
samsung	SM-A145P
samsung	SM-A145R
samsung	SM-A155F
samsung	SM-A202F
samsung	SM-A205U
samsung	SM-A205W
samsung	SM-A217F
samsung	SM-A225F
samsung	SM-A235F
samsung	SM-A236B
samsung	SM-A245M
samsung	SM-A256B
samsung	SM-A256E
samsung	SM-A315G
samsung	SM-A336B
samsung	SM-A336E
samsung	SM-A346B
samsung	SM-A346E
samsung	SM-A356B
samsung	SM-A356E
samsung	SM-A405FN
samsung	SM-A415F
samsung	SM-A505FN
samsung	SM-A505W
samsung	SM-A505YN
samsung	SM-A515F
samsung	SM-A525F
samsung	SM-A526B
samsung	SM-A526W
samsung	SM-A528B
samsung	SM-A536B
samsung	SM-A536E
samsung	SM-A536W
samsung	SM-A546B
samsung	SM-A546E
samsung	SM-A556B
samsung	SM-A556E
samsung	SM-A600FN
samsung	SM-A605FN
samsung	SM-A705FN
samsung	SM-A705YN
samsung	SM-A725F
samsung	SM-A736B
samsung	SM-A750FN
samsung	SM-F711B
samsung	SM-F741B
samsung	SM-F936B
samsung	SM-F946B
samsung	SM-G525F
samsung	SM-G770F
samsung	SM-G780F
samsung	SM-G780G
samsung	SM-G781B
samsung	SM-G781U
samsung	SM-G781W
samsung	SM-G960F
samsung	SM-G960W
samsung	SM-G965F
samsung	SM-G965W
samsung	SM-G970F
samsung	SM-G970U
samsung	SM-G973F
samsung	SM-G973U
samsung	SM-G975F
samsung	SM-G981B
samsung	SM-G981W
samsung	SM-G986B
samsung	SM-G986W
samsung	SM-G990B
samsung	SM-G990B2
samsung	SM-G990E
samsung	SM-G990W2
samsung	SM-G991B
samsung	SM-G991W
samsung	SM-G996W
samsung	SM-G998B
samsung	SM-G998W
samsung	SM-M317F
samsung	SM-N960F
samsung	SM-N981B
samsung	SM-N986B
samsung	SM-S711B
samsung	SM-S711W
samsung	SM-S721B
samsung	SM-S721W
samsung	SM-S901B
samsung	SM-S901E
samsung	SM-S901W
samsung	SM-S906B
samsung	SM-S906E
samsung	SM-S908B
samsung	SM-S908E
samsung	SM-S908W
samsung	SM-S911B
samsung	SM-S911W
samsung	SM-S916B
samsung	SM-S918B
samsung	SM-S918W
samsung	SM-S921B
samsung	SM-S921W
samsung	SM-S926B
samsung	SM-S926W
samsung	SM-S928B
samsung	SM-S928W
samsung	SM-X810
vivo	V2044
vivo	V2250
vivo	V2337
```
</details>

**Comment by AnilYadavBB** [comment]
@tirth-patel-nc - Is this issue fixed? Could you please update on this

**Comment by EnmaniacSoftware** [comment]
I am able to reproduce the issue on our app on simulator as well (Pixel XL API 29):

```
D/AndroidRuntime(20198): Shutting down VM
E/AndroidRuntime(20198): FATAL EXCEPTION: main
E/AndroidRuntime(20198): Process: XYZ, PID: 20198
E/AndroidRuntime(20198): java.lang.NullPointerException: Attempt to invoke interface method 'int io.flutter.view.TextureRegistry$SurfaceProducer.getWidth()' on a null object reference
E/AndroidRuntime(20198): 	at io.flutter.plugin.platform.SurfaceProducerPlatformViewRenderTarget.getWidth(SurfaceProducerPlatformViewRenderTarget.java:25)
E/AndroidRuntime(20198): 	at io.flutter.plugin.platform.VirtualDisplayController.getRenderTargetWidth(VirtualDisplayController.java:132)
E/AndroidRuntime(20198): 	at io.flutter.plugin.platform.PlatformViewsController$1.lambda$resize$0$io-flutter-plugin-platform-PlatformViewsController$1(PlatformViewsController.java:351)
E/AndroidRuntime(20198): 	at io.flutter.plugin.platform.PlatformViewsController$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/AndroidRuntime(20198): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20198): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20198): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(20198): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(20198): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20198): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(20198): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (20198): Sending signal. PID: 20198 SIG: 9
```

Flutter info:

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.32.5, on macOS 15.7 24G222 darwin-arm64, locale en-US) [1,965ms]
    • Flutter version 3.32.5 on channel stable at /Users/banaszki/flutter-3.32.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcf2c11572 (3 months ago), 2025-06-24 11:44:07 -0700
    • Engine revision dd93de6fb1
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [17.8s]
    • Android SDK at /Users/banaszki/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/banaszki/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [6.8s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [16ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [15ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] VS Code (version 1.104.1) [13ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.118.0

[✓] Connected device (4 available) [11.7s]
    • Android SDK built for arm64 (mobile) • emulator-5554             • android-arm64  • Android 10 (API 29) (emulator)
    • Enmaniac’s iPhone 13 (mobile)        • 00008110-000A383A2143801E • ios            • iOS 18.6.2 22G100
    • macOS (desktop)                      • macos                     • darwin-arm64   • macOS 15.7 24G222 darwin-arm64
    • Chrome (web)                         • chrome                    • web-javascript • Google Chrome 140.0.7339.210
    ! Error: Browsing on the local area network for Enmaniac iPhone XS. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,764ms]
    • All expected network resources are available.

• No issues found!
```
