### ISSUE TITLE
Failed assertion: line 5227pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by surajgju** [flutter/flutter#154626]
### Steps to reproduce

1.when tap on navigate back leading in appbar which is inside widget YoutubePlayerBuilder it throw the  error Failed assertion: line 5534 pos 12: '!_debugLocked': is not true.
2. i think this is youtube_player_flutter issue since its showing in Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
3. i am writing back like this simple leading: IconButton(
                          icon: const Icon(Icons.arrow_back_ios), // Customize the icon as needed
                          onPressed: () => Navigator.of(context).pop(),
                        ),

### Expected results

i should goes back to previous screen.

### Actual results

i am unable to navigate back to previous screen might be due to this widget YoutubePlayerBuilder.

### Code sample

<details open><summary>Code sample</summary>

```dart
Widget build(BuildContext context) {
    ScreenUtil.init(context);
    // final _chapterDetailProvider = Provider.of<ChapterDetailProvider>(context);
    return Consumer<ChapterDetailProvider>(
        builder: (context, _chapterDetailProvider, child) {
      return chaptersTopicsList.isNotEmpty
          ? YoutubePlayerBuilder(
              // key: UniqueKey(),
              player: YoutubePlayer(
                controller: videoController!,
                onReady: () {
                  // isPlayerReady = true;
                },
                //aspectRatio:videoController!.value.isFullScreen ? 3/3 : 16 / 9 ,
                aspectRatio: 16 / 8,

                bottomActions: [
                  Expanded(
                      child: ClipRRect(
                    borderRadius: BorderRadius.circular(10.0),
                    child: BackdropFilter(
                      filter: ui.ImageFilter.blur(
                        sigmaX: 10.0,
                        sigmaY: 10.0,
                        //tileMode: TileMode.mirror
                      ),
                      child: Container(
                        margin: EdgeInsets.only(bottom: 5, left: 10, right: 10),
                        child: Row(
                          children: [
                            CurrentPosition(),
                            const SizedBox(width: 10.0),
                            ProgressBar(
                              isExpanded: true,
                              controller: videoController,
                              colors: ProgressBarColors(
                                playedColor: Colors.white,
                                handleColor: Colors.white,
                                bufferedColor: const Color.fromARGB(
                                  60,
                                  255,
                                  255,
                                  255,
                                ),
                                backgroundColor: Colors.white24,
                              ),
                            ),
                            const SizedBox(width: 10.0),
                            RemainingDuration(),
                            SizedBox(
                              width: 10.0,
                            ),
                            Row(
                              children: [
                                InkWell(
                                    onTap: () {
                                      setState(() {
                                        videoController!.seekTo(Duration(
                                            seconds: videoController!
                                                    .value.position.inSeconds -
                                                Duration(seconds: 10)
                                                    .inSeconds));
                                      });
                                    },
                                    child: Container(
                                        child: Image.asset(
                                      "assets/img/rewind.png",
                                      filterQuality: FilterQuality.high,
                                      fit: BoxFit.fill,
                                      width: videoController!.value.isFullScreen
                                          ? 15.w
                                          : 20.w,
                                      height:
                                          videoController!.value.isFullScreen
                                              ? 45.h
                                              : 20.h,
                                    ))),
                                SizedBox(
                                  width: 5,
                                ),
                                InkWell(
                                    onTap: () {
                                      setState(() {
                                        videoController!.seekTo(Duration(
                                            seconds: videoController!
                                                    .value.position.inSeconds +
                                                10));
                                      });
                                    },
                                    child: Container(
                                        child: Image.asset(
                                      "assets/img/forward.png",
                                      filterQuality: FilterQuality.high,
                                      fit: BoxFit.fill,
                                      width: videoController!.value.isFullScreen
                                          ? 15.w
                                          : 20.w,
                                      height:
                                          videoController!.value.isFullScreen
                                              ? 45.h
                                              : 20.h,
                                    ))),
                              ],
                            ),
                            Container(
                                margin: EdgeInsets.only(left: 7),
                                child: PlaybackSpeedButton()),
                            FullScreenButton(
                              controller: videoController!,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ))
                ],
              ),
              builder: (context, player) {
                return Scaffold(
                    backgroundColor: Colors.white,
                    appBar: AppBar(
                        backgroundColor: Colors.white,
                        //subjectCircleFillCOlor,
                        elevation: 0,
                        centerTitle: true,
                        flexibleSpace: Image(
                          image: AssetImage(Images.homebgImg),
                          fit: BoxFit.cover,
                          // height: 25,
                        ),
                        title: GestureDetector(
                          onTap: () {
                            // Navigator.of(context).push(MaterialPageRoute(builder: (builder)=>YoutubePlayerDemoApp()));
                          },
                          child: SvgPicture.asset(
                            "assets/img/logo.svg",
                            semanticsLabel: 'Vidya mine',
                            width: 125.w,
                            height: 25.h,
                          ),
                        ),
                        leading: IconButton(
                          icon: const Icon(Icons.arrow_back_ios), // Customize the icon as needed
                          onPressed: () => Navigator.of(context).pop(),
                        ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======= Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#67fa5](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#9415e(tickers: tracking 4 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5534 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/suraj/development/vidyamine/lib/main.dart:61:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5534:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#78     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#82     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#86     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#97     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#104    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#109    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#112    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#114    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#118    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#129    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#130    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#133    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#135    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#144    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#149    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#156    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#159    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#160    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#161    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#164    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#166    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#170    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#172    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#176    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#177    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#187    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#191    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#194    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#195    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#198    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#200    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#203    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#204    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#207    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#209    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#213    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#216    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#218    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#223    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#225    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#226    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#228    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#229    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#230    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#233    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#239    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#243    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#251    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#252    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#253    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#254    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#255    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#256    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#257    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
#261    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================
Reloaded 15 of 2559 libraries in 1,718ms (compile: 235 ms, reload: 949 ms, reassemble: 214 ms).

======== Exception caught by widgets library =
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.0)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by darshankawar** [comment]
@surajgju 
The code sample you provided contains third party package implementation. In order to properly address the issue, please narrow down the code to framework itself by removing all external code and check if the reported behavior still occurs or not. If yes, provide updated code sample so as to make the issue actionable.

**Comment by mplgn** [comment]
I'm running into this issue as well, only after upgrading to flutter 3.24.3.    It was working correctly with 3.24.0.
