### ISSUE TITLE
error in flutter build apk command 

### ISSUE THREAD

**Issue by mohamadAdibTawil** [flutter/flutter#154660]
### Steps to reproduce

flutter build apk

### Actual results

<details>
<summary> log </summary>

```

flutter build apk
Resolving dependencies... (12.6s)
Downloading packages... (14.2s)
+ _fe_analyzer_shared 72.0.0 (73.0.0 available)
+ _macros 0.3.2 from sdk dart     
+ analyzer 6.7.0 (6.8.0 available)
+ animated_emoji 3.1.0
+ archive 3.6.1
+ args 2.5.0
+ asn1lib 1.5.3
+ async 2.11.0
+ audio_session 0.1.21
+ avatar_glow 3.0.1
+ bloc 8.1.4
+ boolean_selector 2.1.1
+ build 2.4.1
+ build_config 1.1.1
+ build_daemon 4.0.2
+ build_resolvers 2.4.2
+ build_runner 2.4.12
+ build_runner_core 7.3.2
+ built_collection 5.1.1
+ built_value 8.9.2
+ cached_network_image 3.3.1 (3.4.1 available)
+ cached_network_image_platform_interface 4.0.0 (4.1.1 available)
+ cached_network_image_web 1.2.0 (1.3.1 available)
+ characters 1.3.0
+ checked_yaml 2.0.3
+ chewie 1.8.4
+ clock 1.1.1
+ code_builder 4.10.0
+ collection 1.18.0 (1.19.0 available)
+ color 3.0.0
+ convert 3.1.1
+ country_flags 3.0.0
+ cross_file 0.3.4+2
+ crypto 3.0.5
+ csslib 1.0.0
+ cupertino_icons 1.0.8
+ dio_web_adapter 2.0.0
+ dynamic_tabbar 1.0.7
+ emoji_picker_flutter 2.2.0 (3.0.0 available)
+ encrypt 5.0.3
+ equatable 2.0.5
+ fake_async 1.3.1
+ faker 2.2.0
+ ffi 2.1.3
+ file 7.0.0
+ file_selector_linux 0.9.2+1
+ file_selector_macos 0.9.4
+ file_selector_platform_interface 2.6.2
+ file_selector_windows 0.9.3+2
+ fixnum 1.1.0
+ flutter 0.0.0 from sdk flutter
+ flutter_bloc 8.1.6
+ flutter_cache_manager 3.3.1 (3.4.1 available)
+ flutter_gen_core 5.7.0
+ flutter_gen_runner 5.7.0
+ flutter_image_slideshow 0.1.6
+ flutter_lints 4.0.0
+ flutter_plugin_android_lifecycle 2.0.22
+ flutter_spinkit 5.2.1
+ flutter_staggered_animations 1.1.1
+ flutter_staggered_grid_view 0.7.0
+ flutter_svg 2.0.9 (2.0.10+1 available)
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ font_awesome_flutter 10.7.0
+ frontend_server_client 4.0.0
+ glob 2.1.2
+ google_identity_services_web 0.3.1+4
+ google_sign_in 6.2.1
+ google_sign_in_android 6.1.30
+ google_sign_in_ios 5.7.7
+ google_sign_in_platform_interface 2.4.5
+ google_sign_in_web 0.12.4+2
+ graphs 2.3.2
+ hashcodes 2.0.0
+ html 0.15.4
+ http 0.13.6 (1.2.2 available)
+ http_multi_server 3.2.1
+ http_parser 4.0.2 (4.1.0 available)
+ image_picker 1.1.2
+ image_picker_android 0.8.12+13
+ image_picker_for_web 3.0.5
+ image_picker_ios 0.8.12
+ image_picker_linux 0.2.1+1
+ image_picker_macos 0.2.1+1
+ image_picker_platform_interface 2.10.0
+ image_picker_windows 0.2.1+1
+ image_size_getter 2.1.3
+ infinite_scroll_pagination 4.0.0
+ intl 0.19.0
+ io 1.0.4
+ jovial_misc 0.8.5
+ jovial_svg 1.1.14 (1.1.22 available)
+ js 0.6.7 (0.7.1 available)
+ json_annotation 4.9.0
+ just_audio 0.9.40
+ just_audio_platform_interface 4.3.0
+ just_audio_web 0.4.12
+ leak_tracker 10.0.5 (10.0.7 available)
+ leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
+ leak_tracker_testing 3.0.1
+ lints 4.0.0
+ logging 1.2.0
+ lottie 3.0.0 (3.1.2 available)
+ macros 0.1.2-main.4 (0.1.3-main.0 available)
+ matcher 0.12.16+1
+ material_color_utilities 0.11.1 (0.12.0 available)
+ meta 1.15.0
+ mime 1.0.6
+ nested 1.0.0
+ octo_image 2.1.0
+ oktoast 3.4.0
+ package_config 2.1.0
+ package_info_plus 8.0.2
+ package_info_plus_platform_interface 3.0.1
+ path 1.9.0
+ path_drawing 1.0.1
+ path_parsing 1.0.1
+ path_provider 2.1.4
+ path_provider_android 2.2.10
+ path_provider_foundation 2.4.0
+ path_provider_linux 2.2.1
+ path_provider_platform_interface 2.1.2
+ path_provider_windows 2.3.0
+ permission_handler 11.3.1
+ permission_handler_android 12.0.12
+ permission_handler_apple 9.4.5
+ permission_handler_html 0.1.3+2
+ permission_handler_platform_interface 4.2.2
+ permission_handler_windows 0.2.1
+ petitparser 6.0.2
+ photo_view 0.15.0
+ pin_code_fields 8.0.1
+ platform 3.1.5
+ plugin_platform_interface 2.1.8
+ pointycastle 3.9.1
+ pool 1.5.1
+ popup_menu 2.0.0
+ progress_state_button 1.0.4
+ protobuf 2.1.0 (3.1.0 available)
+ provider 6.1.2
+ pub_semver 2.1.4
+ pubspec_parse 1.3.0
+ record 4.4.4 (5.1.2 available)
+ record_linux 0.4.1 (0.7.2 available)
+ record_macos 0.2.2
+ record_platform_interface 0.5.0 (1.1.0 available)
+ record_web 0.5.0 (1.1.3 available)
+ record_windows 0.7.1 (1.0.3 available)
+ rxdart 0.27.7 (0.28.0 available)
+ shared_preferences 2.3.2
+ shared_preferences_android 2.3.2
+ shared_preferences_foundation 2.5.2
+ shared_preferences_linux 2.4.1
+ shared_preferences_platform_interface 2.4.1
+ shared_preferences_web 2.4.2
+ shared_preferences_windows 2.4.1
+ shelf 1.4.1 (1.4.2 available)
+ shelf_web_socket 2.0.0
+ shimmer 3.0.0
+ shimmer_container 0.0.2
+ sky_engine 0.0.99 from sdk flutter
+ sliver_tools 0.2.12
+ source_span 1.10.0
+ sprintf 7.0.0
+ sqflite 2.3.3+1
+ sqflite_common 2.5.4+2
+ stack_trace 1.11.1
+ stop_watch_timer 3.1.1 (3.2.1 available)
+ stream_channel 2.1.2
+ stream_transform 2.1.0
+ string_scanner 1.2.0 (1.3.0 available)
+ svgaplayer_flutter 2.2.0
+ synchronized 3.2.0
+ term_glyph 1.2.1
+ test_api 0.7.2 (0.7.3 available)
+ time 2.1.4
+ timing 1.0.1
+ transparent_image 2.0.1
+ typed_data 1.3.2
+ universal_io 2.2.2
+ url_launcher 6.3.0
+ url_launcher_android 6.3.10
+ url_launcher_ios 6.3.1
+ url_launcher_linux 3.2.0
+ url_launcher_macos 3.2.0
+ url_launcher_platform_interface 2.3.2
+ url_launcher_web 2.3.3
+ url_launcher_windows 3.1.2
+ uuid 4.5.0
+ vector_graphics 1.1.10+1 (1.1.11+1 available)
+ vector_graphics_codec 1.1.10+1 (1.1.11+1 available)
+ vector_graphics_compiler 1.1.10+1 (1.1.11+1 available)
+ vector_math 2.1.4
+ video_player 2.9.1
+ video_player_android 2.7.3
+ video_player_avfoundation 2.6.1
+ video_player_platform_interface 6.2.2
+ video_player_web 2.3.2
+ vm_service 14.2.4 (14.2.5 available)
+ wakelock_plus 1.2.8
+ url_launcher_windows 3.1.2
+ uuid 4.5.0
+ vector_graphics 1.1.10+1 (1.1.11+1 available)
+ vector_graphics_codec 1.1.10+1 (1.1.11+1 available)
+ vector_graphics_compiler 1.1.10+1 (1.1.11+1 available)
+ vector_math 2.1.4
+ video_player 2.9.1
+ video_player_android 2.7.3
+ video_player_avfoundation 2.6.1
+ video_player_platform_interface 6.2.2
+ video_player_web 2.3.2
+ vm_service 14.2.4 (14.2.5 available)
+ wakelock_plus 1.2.8
+ video_player_android 2.7.3
+ video_player_avfoundation 2.6.1
+ video_player_platform_interface 6.2.2
+ video_player_web 2.3.2
+ vm_service 14.2.4 (14.2.5 available)
+ wakelock_plus 1.2.8
+ vm_service 14.2.4 (14.2.5 available)
+ wakelock_plus 1.2.8
+ wakelock_plus 1.2.8
+ wakelock_plus_platform_interface 1.2.1
+ watcher 1.1.0
+ wave_blob 1.0.5
+ web 0.5.1 (1.0.0 available)
+ web_socket 0.1.6
+ web_socket_channel 3.0.1
+ win32 5.5.4
+ xdg_directories 1.0.4
+ xml 6.5.0
+ yaml 3.1.2
+ zego_express_engine 3.16.2
+ zego_zim 2.17.1Changed 217 dependencies!
34 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

[ZEGO][PLUGIN] Download native dependency
[ZEGO][PLUGIN] Native version: 3.16.2.40097
[ZEGO][PLUGIN] Done!e: C:/Users/Moham/.gradle/caches/transforms-3/1a36c150372f3edd1303b1fe7aa45a27/transformed/fragment-1.7.1-api.jar!/META-INF/fragment_release.kotlin_module: Module 
was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/771019485631ab15bbf2f55576601182/transformed/jetified-activity-1.8.1-api.jar!/META-INF/activity_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/438ed2e4091540a2b5e58ad09f29180b/transformed/jetified-lifecycle-livedata-core-ktx-2.7.0-api.jar!/META-INF/lifecycle-livedata-core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/27df29044ba91fe46c9dffb5e7df281a/transformed/lifecycle-livedata-2.7.0-api.jar!/META-INF/lifecycle-livedata_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/19b728f961b9a2a2e294ea48663dc0ec/transformed/lifecycle-viewmodel-2.7.0-api.jar!/META-INF/lifecycle-viewmodel_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/336a6902295b05cab8ac711c22cb04bb/transformed/lifecycle-livedata-core-2.7.0-api.jar!/META-INF/lifecycle-livedata-core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/ba169a17df1c6a69824263f5b42c8712/transformed/jetified-lifecycle-viewmodel-savedstate-2.7.0-api.jar!/META-INF/lifecycle-viewmodel-savedstate_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/572387d248dd1e3be4d778989e6e1939/transformed/jetified-core-ktx-1.13.1-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/911fe644afed3451792dbf57bd5aaf68/transformed/core-1.13.1-api.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/6b117bb37d91b649fafd3c9c1578d561/transformed/lifecycle-runtime-2.7.0-api.jar!/META-INF/lifecycle-runtime_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/7905d1776b2850da1369a1b0dcc18f3e/transformed/jetified-lifecycle-process-2.7.0-api.jar!/META-INF/lifecycle-process_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.7.0/85334205d65cca70ed0109c3acbd29e22a2d9cb1/lifecycle-common-2.7.0.jar!/META-INF/lifecycle-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/95420fb350fbe2be2322952e0ce38deb/transformed/jetified-savedstate-1.2.1-api.jar!/META-INF/savedstate_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/460553c51bcca98624fce744e471f6a7/transformed/jetified-window-1.2.0-api.jar!/META-INF/window_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/063b6ee920cf2f7578c3f9f5a6ee4674/transformed/jetified-window-java-1.2.0-api.jar!/META-INF/window-java_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/fb88794ff9ec5bc224b9768e27626f48/transformed/jetified-kotlinx-coroutines-core-jvm-1.7.1.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.        
e: C:/Users/Moham/.gradle/caches/transforms-3/4f605e1ab2e2c5b8d016291b0e9fa40d/transformed/jetified-kotlinx-coroutines-android-1.7.1.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.      
e: C:/Users/Moham/.gradle/caches/transforms-3/ee2cfbe4d5d6c56718716c47e8211d63/transformed/jetified-kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: C:/Users/Moham/.gradle/caches/transforms-3/050948ac127f28b59f2f55c875ca5183/transformed/jetified-kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Moham\AppData\Local\Pub\Cache\hosted\pub.dev\zego_express_engine-3.16.2\android\src\main\java\im\zego\zego_express_engine\internal\ZegoExpressEngineMethodHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Moham\AppData\Local\Pub\Cache\hosted\pub.dev\zego_zim-2.17.1\android\src\main\java\im\zego\zim_flutter\internal\ZIMPluginConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Bad state: No canonical name found.
#0      BinaryBuilder.readNonNullCanonicalNameReference (package:kernel/binary/ast_from_binary.dart:1073:7)
#1      BinaryBuilder._readExtensionMemberDescriptor (package:kernel/binary/ast_from_binary.dart:1603:32)
#2      BinaryBuilder._readExtensionMemberDescriptorList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1595:24)
#3      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#4      new List.generate (dart:core-patch/array_patch.dart:46:13)
#5      BinaryBuilder._readExtensionMemberDescriptorList (package:kernel/binary/ast_from_binary.dart:1594:16)
#6      BinaryBuilder.readExtension (package:kernel/binary/ast_from_binary.dart:1582:30)
#7      BinaryBuilder._readExtensionList.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1311:34)
#8      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#9      new List.generate (dart:core-patch/array_patch.dart:46:13)
#10     BinaryBuilder._readExtensionList (package:kernel/binary/ast_from_binary.dart:1310:40)
#11     BinaryBuilder.readLibrary (package:kernel/binary/ast_from_binary.dart:1265:5)
#12     BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:935:9)
#13     BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:710:34)
#14     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#15     BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695:21)
#16     loadComponentFromBytes (package:kernel/kernel.dart:33:28)
#17     loadComponentFromBinary (package:kernel/kernel.dart:28:10)
#18     ConstFinder.findInstances (package:kernel/const_finder.dart:207:12)
#19     main (file:///C:/b/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6m 55s
Running Gradle task 'assembleRelease'...                          418.5s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ C:\flutter_app\lklk-live\android\settings.gradle.                                                      │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ C:\flutter_app\lklk-live\android\build.gradle                                                          │
│ ext.kotlin_version = '<latest-version>'                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1

```

</details>

### Logs

<details open>
<summary>Logs</summary>

```console


┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                 │
│ Find the latest version on https://kotlinlang.org/docs/releases.html#release-details, then update the  │
│ C:\flutter_app\lklk-live\android\settings.gradle.                                                      │
│                                                                                                        │
│ Alternatively (if your project was created before Flutter 3.19), update                                │
│ C:\flutter_app\lklk-live\android\build.gradle                                                          │
│ ext.kotlin_version = '<latest-version>'                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019 16.0.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!


this is C:\flutter_app\lklk-live\android\build.gradle   
`allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

this is C:\flutter_app\lklk-live\android\settings.gradle
`pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "2.0.20" apply false
}

include ":app"

```
</details>

**Comment by darshankawar** [comment]
> Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
> │ [!] Your project requires a newer version of the Kotlin Gradle plugin.

@mohamadAdibTawil Have you tried this fix as suggested ? If not, please upgrade as suggested and re-run your scenario to check if you still get same error or not.

Another error from the log is:

> Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
> Bad state: No canonical name found.

This looks like a genuine error. Can you try to replicate with reproducible code sample ?

**Comment by mohamadAdibTawil** [comment]
> > Flutter Fix ──────────────────────────────────────────────────────────────────────────────────────────┐
> > │ [!] Your project requires a newer version of the Kotlin Gradle plugin.
> 
> @mohamadAdibTawil Have you tried this fix as suggested ? If not, please upgrade as suggested and re-run your scenario to check if you still get same error or not.
> 
> Another error from the log is:
> 
> > Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
> > Bad state: No canonical name found.
> 
> This looks like a genuine error. Can you try to replicate with reproducible code sample ?

Yes I try to fix suggested , update my kotlin version to last version 
i try this is work 'flutter build apk --no-tree-shake-icons' but i want to fix the problem for this 'flutter build apk'

**Comment by darshankawar** [comment]
> i want to fix the problem for this 'flutter build apk'

For this to address properly, try to trim down your app implementation to minimal. I see that you are using lot of external dependencies which may be causing this error.
