### ISSUE TITLE
[go_router] context.push and then context.pop and then context.push causes pages to be presented (or built) twice

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#154759]
### Steps to reproduce

This occurs with: 
go_router version 14.2.7
Flutter 3.24.2 or 3.25.x (any version of 3.25)

This is not happening in all scenarios, but in some scenarios if I programmatically `.push` --> `.pop` --> `.push` the screen a second time, then the new screen and the original screen are both presented.   

Searching through other issues Ive seen people discuss builder running twice.  In this case, I'm wondering if its not a situation of the builder running twice, but rather the `.pop()` is not actually removing the page when it was first put there from `.push`, although visually it looks like it was removed.  In that situation when you ask it to push a new one it rebuilds the original page as well to 'restore' the state.  Im not exactly sure, but the stateful routes have been a life saver and do not want to mess with that, but from observation it seems like this is what might be happening

Ive put in a console debugPrint to show which screens are showing when

This behavior **ONLY** occurs if you programmatically `push` then `pop` then `push` again.  If you close a screen using the back button on the top left of the screen or if you drag to close a screen (drag left to right) then the screen is properly popped or closed

Ive attached code below as a demonstrator model, but to reproduce the problem here are some steps

**WORKING/PROPER OPERATION:**
1. Tap `purple` container to open `Screen B`
2. Either swipe the screen closed or tap the text "Press Here to Close me out!" to close the screen
3. Tap `blue` container to open `Screen C`
4. Either swipe the screen closed or tap the text "Press Here to Close me out!" to close the screen

**BUGGED OPERATION**
1. Tap `purple` container to open `Screen B`
**2. Tap the house icon on the bottom navigation bar to programmatically close the screen (`context.pop()`)**
3. Tap `blue` container to open `Screen C`
4. Either swipe the screen closed or tap the text "Press Here to Close me out!" to close the screen
5. You will notice that `Screen B` is underneath `Screen C`

**Notes**
In bugged operation, you can observe in the console, that when Step 3 is performed, the builder for screen B and C are both run back to back as the debugPrint `***** I AM BUILDING SCREEN B *****` and `***** I AM BUILDING SCREEN C *****` are both presented in the console

**Extra notes:**
- If I were to use `context.go` then this bug does not occur.  However, in my implementation I may have to get to `Screen B` or `Screen C` from any number of places and I would have to expand my route list massively and almost endlessly to account from all the points at which those screen could be opened.   Using `.push` is ideal to allow my users to enter those screens at any time they like
- Ive read one suggestion about turning ScreenB/C into `const` widgets to avoid 'rebuilding' them.  I don't believe this is a rebuild issue, but regardless turning them into `const` is not viable since I need to feed a bunch of variables to them.  In this case for the demonstrator I put a title variable in the builder to see.  Those vars come in as params or extra using context.push or from deep links url pattern

### Expected results

Two screens should not be opened

### Actual results

Two screen are opened

### Code sample

<details open><summary>Code sample</summary>

**main.dart**
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'main_router.dart';

final GlobalKey<NavigatorState> rootNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'root');

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: router,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Column(
              children: [
                const Text("Hi i'm screen A (home screen)"),

                Container(height:20),

                GestureDetector(
                  onTap: (){
                    context.pushNamed('screenB');
                  },
                  child: Container(
                    color: Colors.purple,
                    child: const Text(
                      'Press Here to goto Screen B',
                    ),
                  ),
                ),


                Container(height:20),

                GestureDetector(
                  onTap: (){
                    context.pushNamed('screenC');
                  },
                  child: Container(
                    color: Colors.blue,
                    child: const Text(
                      'Press Here to goto Screen C',
                    ),
                  ),
                ),

              ],
            ),
          ],
        ),
      ),
    );
  }
}



class ScreenB extends StatefulWidget {
  const ScreenB({super.key, required this.title});
  final String title;

  @override
  State<ScreenB> createState() => _ScreenBState();
}

class _ScreenBState extends State<ScreenB> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Text('im screen B!'),
          Text('my title is: ${widget.title}'),
          Container(height:20),
          GestureDetector(
            onTap: (){
              context.pop();
            },
            child: const Text(
              'Press Here to Close me out!',
            ),
          ),
        ],
      )),
    );
  }
}



class ScreenC extends StatefulWidget {
  const ScreenC({super.key, required this.title});
  final String title;

  @override
  State<ScreenC> createState() => _ScreenCState();
}

class _ScreenCState extends State<ScreenC> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Text('im screen C!'),
          Text('my title is: ${widget.title}'),
          Container(height:20),
          GestureDetector(
            onTap: (){
              context.pop();
            },
            child: const Text(
              'Press Here to Close me out!',
            ),
          ),
        ],
      )),
    );
  }
}

```

**main_router.dart**
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'main.dart';
import 'main_router_scaffold.dart';

final GoRouter router = GoRouter(
  debugLogDiagnostics: true,
  initialLocation:'/',
  navigatorKey: rootNavigatorKey,
  routes: <RouteBase>[



        StatefulShellRoute(
        builder: (context, state, navigationShell) {
            return navigationShell;
        },
        navigatorContainerBuilder: (BuildContext context,
        StatefulNavigationShell navigationShell,
        List<Widget> children) {
            return ScaffoldWithNavBarWithState(navigationShell: navigationShell, children: children);
        },
        branches: <StatefulShellBranch>[

            StatefulShellBranch(
                routes: [
                        GoRoute(
                        path: '/',
                          builder: (BuildContext context, GoRouterState state) {

                            var theTitle = "Hello friends";

                            return MyHomePage(title:theTitle);
                          },
                          routes: <RouteBase>[
                            GoRoute(
                              path: 'screenb.php',
                              name: 'screenB',
                              builder: (BuildContext context, GoRouterState state) {

                                debugPrint('***** I AM BUILDING SCREEN B *****');
                                var theTitle = "Hi this is Screen B";

                                return ScreenB(title: theTitle);
                              },
                            ),



                            GoRoute(
                              path: 'screenc.php',
                              name: 'screenC',
                              builder: (BuildContext context, GoRouterState state) {

                                debugPrint('***** I AM BUILDING SCREEN C *****');
                                var theTitle = "Hi this is Screen C";

                                return ScreenC(title: theTitle);
                              },
                            ),


                          ],
                        ),
              ]
            )

        ],
      )

    ]
);
```

**main_router_scaffold.dart**
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';


class ScaffoldWithNavBarWithState extends StatefulWidget {
  const ScaffoldWithNavBarWithState({
    Key? key,
    required this.children,
    required this.navigationShell,}) : super(key: key ?? const ValueKey<String>('ScaffoldWithNavBar'));
  /// Body, i.e. the index stack
  //final Widget body;
  final List<Widget> children;

  /// The navigation shell and container for the branch Navigators.
  final StatefulNavigationShell navigationShell;

  @override
  State<ScaffoldWithNavBarWithState> createState() => _ScaffoldWithNavBarWithStateState();
}

class _ScaffoldWithNavBarWithStateState extends State<ScaffoldWithNavBarWithState> {


  @override
  void initState(){
    super.initState();
  }


  @override
  Widget build(BuildContext context) {


    return
      PopScope(

        onPopInvoked: (popped) async {
          //debugPrint('what!');
        },

        child: CupertinoTabScaffold(
          resizeToAvoidBottomInset: true,
          //controller:bottomTabBarController,
          restorationId: 'cupertino_tab_scaffold',
          key: const ValueKey('tab_scaffold'),
          tabBar:

          CupertinoTabBar(
            items: const <BottomNavigationBarItem>[

              BottomNavigationBarItem(icon: Icon(Icons.house), label: 'First Screen'),
              BottomNavigationBarItem(icon: Icon(Icons.house), label: 'Second Screen'),

            ],
            currentIndex: widget.navigationShell.currentIndex,
            onTap: (int tappedIndex) {

              context.pop();

              return widget.navigationShell.goBranch(
                  tappedIndex
                //navigatorKey: _bottomNavBranches[tappedIndex].navigatorKey
              );


            },
          ),
          tabBuilder: (BuildContext context, int index) {

            return widget.children[index];

          },
        ),
      );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by SuicaLondon** [comment]
I think that is not related to #153498, because that issue is normal behavior of go_router.

 One thing you should do first is to put your log into your builder function in screen B widget instead of the route builder and make the widget as const because the router builder will be called every time you change the route. ( As I mentioned in the [comment](https://github.com/flutter/flutter/issues/153498#issuecomment-2292469759).


However, I can reproduced this issue on my device at **3.24.0** in all devices. While, I did moved the print into the widget B and C and make the widget as const even if the page was pop, the old page is still able to be called. 

<img width="924" alt="Screenshot 2024-09-07 at 10 33 32 PM" src="https://github.com/user-attachments/assets/66b8e8de-2b3d-44fb-b363-b81adc0c4d71">

While
<img width="478" alt="Screenshot 2024-09-07 at 10 50 54 PM" src="https://github.com/user-attachments/assets/6d73ddf4-07bd-44ce-bec5-db7841619818">


<img width="630" alt="Screenshot 2024-09-07 at 10 51 11 PM" src="https://github.com/user-attachments/assets/eec48eed-98ae-4f07-abc8-3e60d421ca63">

It should be a bug.

**Comment by mark8044** [comment]
@SuicaLondon Agree, I believe this is not actually an issue of builder being called multiple times but actually that .pop does not remove this from the underlying tree somehow. In my basic explanation.   Thanks for trying this out and reproducing it on your end as well

**Comment by darshankawar** [comment]
I was able to replicate the reported behavior. While doing so, also received below error in the console which seem to be similar to https://github.com/flutter/flutter/issues/123369 that was fixed.

<details>
<summary> console error log </summary>

```
[GoRouter] popping /

======== Exception caught by gesture ===============================================================
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      ImperativeRouteMatch.complete (package:go_router/src/match.dart:455:15)
#2      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:161:14)
#3      GoRouterDelegate._handlePopPageWithRouteMatch (package:go_router/src/delegate.dart:136:7)
#4      _CustomNavigatorState._handlePopPage (package:go_router/src/builder.dart:416:42)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5399:28)
#6      GoRouterDelegate.pop (package:go_router/src/delegate.dart:115:11)
#7      GoRouter.pop (package:go_router/src/router.dart:490:20)
#8      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
#9      _ScaffoldWithNavBarWithStateState.build.<anonymous closure> (package:integration_dummy/main_router_scaffold.dart:59:23)
#10     _CupertinoTabScaffoldState.build.<anonymous closure> (package:flutter/src/cupertino/tab_scaffold.dart:372:40)
#11     CupertinoTabBar._buildTabItems.<anonymous closure> (package:flutter/src/cupertino/bottom_tab_bar.dart:238:62)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
#15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246:7)
#16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703:9)
#17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#19     _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:502:19)
#23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482:22)
#24     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457:11)
#25     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#26     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#27     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#28     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#29     _invoke1 (dart:ui/hooks.dart:328:13)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#0c226
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(108.6, 680.8)
  finalLocalPosition: Offset(108.6, 23.4)
  button: 1
  sent tap down
====================================================================================================
D/EGL_emulation( 3655): app_time_stats: avg=1338.23ms min=2.41ms max=15915.01ms count=12
[GoRouter] popping /

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5392 pos 12: '!_debugLocked': is not true.

When the exception was thrown, this was the stack: 
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5392:12)
#3      GoRouterDelegate.pop (package:go_router/src/delegate.dart:115:11)
#4      GoRouter.pop (package:go_router/src/router.dart:490:20)
#5      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
#6      _ScaffoldWithNavBarWithStateState.build.<anonymous closure> (package:integration_dummy/main_router_scaffold.dart:59:23)
#7      _CupertinoTabScaffoldState.build.<anonymous closure> (package:flutter/src/cupertino/tab_scaffold.dart:372:40)
#8      CupertinoTabBar._buildTabItems.<anonymous closure> (package:flutter/src/cupertino/bottom_tab_bar.dart:238:62)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
#12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246:7)
#13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703:9)
#14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#16     _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:502:19)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#26     _invoke1 (dart:ui/hooks.dart:328:13)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
Handler: "onTap"
Recognizer: TapGestureRecognizer#0c226
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(104.0, 690.0)
  finalLocalPosition: Offset(104.0, 32.5)
  button: 1
  sent tap down
====================================================================================================
[GoRouter] popping /

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5392 pos 12: '!_debugLocked': is not true.

When the exception was thrown, this was the stack: 
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5392:12)
#3      GoRouterDelegate.pop (package:go_router/src/delegate.dart:115:11)
#4      GoRouter.pop (package:go_router/src/router.dart:490:20)
#5      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
#6      _ScaffoldWithNavBarWithStateState.build.<anonymous closure> (package:integration_dummy/main_router_scaffold.dart:59:23)
#7      _CupertinoTabScaffoldState.build.<anonymous closure> (package:flutter/src/cupertino/tab_scaffold.dart:372:40)
#8      CupertinoTabBar._buildTabItems.<anonymous closure> (package:flutter/src/cupertino/bottom_tab_bar.dart:238:62)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
#12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246:7)
#13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703:9)
#14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#16     _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:502:19)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#26     _invoke1 (dart:ui/hooks.dart:328:13)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
Handler: "onTap"
Recognizer: TapGestureRecognizer#9a356
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(313.1, 687.7)
  finalLocalPosition: Offset(107.4, 30.3)
  button: 1
  sent tap down
====================================================================================================

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building Builder:
RangeError (length): Invalid value: Only valid value is 0: 1

The relevant error-causing widget was: 
  CupertinoTabScaffold-[<'tab_scaffold'>] CupertinoTabScaffold:file:///Users/dhs/Documents/NCFlutter/integration_dummy/lib/main_router_scaffold.dart:42:16
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart)
#1      _ScaffoldWithNavBarWithStateState.build.<anonymous closure> (package:integration_dummy/main_router_scaffold.dart:71:35)
#2      _TabSwitchingViewState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/cupertino/tab_scaffold.dart:496:67)
#3      Builder.build (package:flutter/src/widgets/basic.dart:7716:48)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5707:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#7      StatelessElement.update (package:flutter/src/widgets/framework.dart:5713:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5966:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:112:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6927:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5823:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5966:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:5823:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6927:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#34     StatelessElement.update (package:flutter/src/widgets/framework.dart:5713:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#36     Element.updateChildren (package:flutter/src/widgets/framework.dart:4098:32)
#37     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7080:17)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5823:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6927:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:5966:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#50     Element.updateChildren (package:flutter/src/widgets/framework.dart:4098:32)
#51     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7080:17)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6927:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#58     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2701:15)
#59     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2760:11)
#60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
#61     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1176:21)
#62     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#63     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#64     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#65     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#66     _invoke (dart:ui/hooks.dart:312:13)
#67     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#68     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
D/EGL_emulation( 3655): app_time_stats: avg=351.42ms min=10.95ms max=4239.08ms count=13
Application finished.
the Dart compiler exited unexpectedly.

```

</details>

```
Stable : 3.24.2
Master: 3.25.0-1.0.pre.269
```

**Comment by yelmuratoff** [comment]
Please check also examples from this closed issue: https://github.com/flutter/flutter/issues/157219
These errors are more likely to occur inside the ShellRoute.

**Comment by uttamkh** [comment]
Have you guys found any workaround for this? I am facing the same issue when I pop the screen and press back button on browser it will call the popped screen once again

**Comment by mark8044** [comment]
@uttamkh I have not unfortunately.  Others must have since it seems like a glaring problem?  I personally use a hybrid of grouter with navigator.push which avoids the problem.  Im sure I've created other problems by doing this, but it gets me by for now

**Comment by Gaby-Torres** [comment]
Hi, anyone figure out a good workaround for this that works well with dependency injection? My team has been debugging a serious memory leak that I finally traced back to this bug and the related bugs like #170255 and #164969
