### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by aw-birdgang** [flutter/flutter#154708]
## Command
```
flutter analyze
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception
```

```
```
[32m[✓][39m Flutter (Channel stable, 3.19.5, on macOS 12.7.6 21H1320 darwin-x64, locale ko-KR)
    [32m•[39m Flutter version 3.19.5 on channel stable at /Users/birdgang/fvm/versions/3.19.5
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 300451adae (5 months ago), 2024-03-27 21:54:07 -0500
    [32m•[39m Engine revision e76c956498
    [32m•[39m Dart version 3.3.3
    [32m•[39m DevTools version 2.31.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
    [32m•[39m Android SDK at /Users/birdgang/Library/Android/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0-rc3
    [31m✗[39m Android SDK file not found: /Users/birdgang/Library/Android/sdk/platforms/android-35/android.jar.
    [32m•[39m Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 14.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14C18
    [33m![39m CocoaPods 1.11.3 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin version 221.5591.58

[32m[✓][39m VS Code (version 1.65.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.40.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 12.7.6 21H1320 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.120



**Comment by huycozy** [comment]
Hi @aw-birdgang 
Do you see this issue appear consistently? Is there a crash stack trace that you can provide for us to investigate futher?

**Comment by passos** [comment]
Hi, I can repro this issue consistently. See #155875

## Steps to Reproduce
```sh
$ flutter create testapp
$ cd testapp
$ flutter analyze
```

## Logs
_Exception
```console
Error from the analysis server: Internal error: Bad state: No definition of type String
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:503:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:511:19)
#2      TypeProviderImpl.stringType (package:analyzer/src/dart/element/type_provider.dart:410:28)
#3      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:230:41)
#4      ResolverVisitor.visitSimpleStringLiteral (package:analyzer/src/generated/resolver.dart:3582:18)
#5      SimpleStringLiteralImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:15765:14)
#6      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:748:16)
#7      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:547:9)
#8      InvocationInferrer._visitArguments (package:analyzer/src/dart/resolver/invocation_inferrer.dart:563:18)
#9      FullInvocationInferrer.resolveInvocation (package:analyzer/src/dart/resolver/invocation_inferrer.dart:244:36)
#10     InstanceCreationExpressionResolver._resolveInstanceCreationExpression
(package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:70:10)
#11     InstanceCreationExpressionResolver.resolve
(package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:49:5)
#12     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:3002:41)
#13     InstanceCreationExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:10127:14)
#14     ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:748:16)
#15     TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:547:9)
#16     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:113:22)
#17     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
#18     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:6736:28)
#19     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
#20     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
#21     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
#22     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
<asynchronous suspension>
#23     Linker.link.<anonymous closure> (package:analyzer/src/summary2/link.dart:123:7)
<asynchronous suspension>
#24     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#25     Linker.link (package:analyzer/src/summary2/link.dart:122:5)
<asynchronous suspension>
#26     link (package:analyzer/src/summary2/link.dart:41:3)
<asynchronous suspension>
#27     LibraryContext.load.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:211:22)
<asynchronous suspension>
#28     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#29     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:24)
<asynchronous suspension>
#30     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#31     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#32     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:296:7)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#34     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:5)
<asynchronous suspension>
#35     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1976:5)
<asynchronous suspension>
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1251:7)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2455:7)
<asynchronous suspension>



#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:425:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:222:11)
<asynchronous suspension>
#2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:296:7)
<asynchronous suspension>
#5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:5)
<asynchronous suspension>
#7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1976:5)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1251:7)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2455:7)
<asynchronous suspension>


Unhandled exception:
Bad state: No definition of type String
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:503:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:511:19)
#2      TypeProviderImpl.stringType (package:analyzer/src/dart/element/type_provider.dart:410:28)
#3      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:230:41)
#4      ResolverVisitor.visitSimpleStringLiteral (package:analyzer/src/generated/resolver.dart:3582:18)
#5      SimpleStringLiteralImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:15765:14)
#6      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:748:16)
#7      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:547:9)
#8      InvocationInferrer._visitArguments (package:analyzer/src/dart/resolver/invocation_inferrer.dart:563:18)
#9      FullInvocationInferrer.resolveInvocation (package:analyzer/src/dart/resolver/invocation_inferrer.dart:244:36)
#10     InstanceCreationExpressionResolver._resolveInstanceCreationExpression
(package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:70:10)
#11     InstanceCreationExpressionResolver.resolve
(package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:49:5)
#12     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:3002:41)
#13     InstanceCreationExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:10127:14)
#14     ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:748:16)
#15     TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:547:9)
#16     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:113:22)
#17     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
#18     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:6736:28)
#19     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
#20     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
#21     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
#22     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
<asynchronous suspension>
#23     Linker.link.<anonymous closure> (package:analyzer/src/summary2/link.dart:123:7)
<asynchronous suspension>
#24     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#25     Linker.link (package:analyzer/src/summary2/link.dart:122:5)
<asynchronous suspension>
#26     link (package:analyzer/src/summary2/link.dart:41:3)
<asynchronous suspension>
#27     LibraryContext.load.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:211:22)
<asynchronous suspension>
#28     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#29     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:24)
<asynchronous suspension>
#30     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#31     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#32     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:296:7)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#34     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:5)
<asynchronous suspension>
#35     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1976:5)
<asynchronous suspension>
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1251:7)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2455:7)
<asynchronous suspension>


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:425:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:222:11)
<asynchronous suspension>
#2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
<asynchronous suspension>
#4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:296:7)
<asynchronous suspension>
#5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:5)
<asynchronous suspension>
#7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1976:5)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1251:7)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2455:7)
<asynchronous suspension>
Analyzing testapp...

Oops; flutter has exited unexpectedly: "Exception: analysis server exited with code 255 and output:
[stderr]
[stderr] #0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:425:5)
[stderr] #1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:222:11)
[stderr] <asynchronous suspension>
[stderr] #2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
[stderr] <asynchronous suspension>
[stderr] #3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:158:9)
[stderr] <asynchronous suspension>
[stderr] #4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:296:7)
[stderr] <asynchronous suspension>
[stderr] #5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
[stderr] <asynchronous suspension>
[stderr] #6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:287:5)
[stderr] <asynchronous suspension>
[stderr] #7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1976:5)
[stderr] <asynchronous suspension>
[stderr] #8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1251:7)
[stderr] <asynchronous suspension>
[stderr] #9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2455:7)
[stderr] <asynchronous suspension>".
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 14.7 23H124 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.24.3 on channel stable at /opt/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /opt/android_sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m ANDROID_HOME = /opt/android_sdk
    [32m•[39m Java binary at: /Applications/Android Studio Jellyfish.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.3)
    [32m•[39m Android Studio at /Applications/Android Studio Jellyfish.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.93.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m iPhone 15 Pro Max (mobile)      • 38B87AAE-A5E8-48B9-8F36-418A0EE587C9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    [32m•[39m macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.7 23H124 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.60
    [33m![39m Error: Browsing on the local area network for iPhone15. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2663184aa79047d0a33a14a3b607954f8fdd8730

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.7 23H124 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone15. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

$ dart --version
Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"
```
