### ISSUE TITLE
The app crashes during the SMS auto-verify call on Android 14 when I change the targetSdkVersion to 34

### ISSUE THREAD

**Issue by ragul-steamA** [flutter/flutter#154705]
### Steps to reproduce

Change the targetSdkVersion in build.gradle to 34.

use this plugin(sms_autofill: ^2.3.0) for sms auto fill.

### Expected results

It should fetch the OTP code from the message.

### Actual results

App crashes when moving to the verify otp screen.

### Code sample

<details open><summary>Code sample</summary>

```dart
void listenOtp() async {
    await SmsAutoFill().listenForCode();
    startResendTimer();
    print("OTP listen Called");
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/b1fcbd27-0558-4dfd-84a4-955ae57fed0d)

</details>

### Logs

<details open><summary>Logs</summary>

```console
FATAL EXCEPTION: main E/AndroidRuntime(19989): Process: com.namp.zeon, PID: 19989 E/AndroidRuntime(19989): java.lang.SecurityException: com.namp.zeon: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts E/AndroidRuntime(19989): at android.os.Parcel.createExceptionOrNull(Parcel.java:3087) E/AndroidRuntime(19989): at android.os.Parcel.createException(Parcel.java:3071) E/AndroidRuntime(19989): at android.os.Parcel.readException(Parcel.java:3054) E/AndroidRuntime(19989): at android.os.Parcel.readException(Parcel.java:2996) E/AndroidRuntime(19989): at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684) E/AndroidRuntime(19989): at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1868) E/AndroidRuntime(19989): at android.app.ContextImpl.registerReceiver(ContextImpl.java:1804) E/AndroidRuntime(19989): at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792) E/AndroidRuntime(19989): at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:765) E/AndroidRuntime(19989): at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(Unknown Source:44) E/AndroidRuntime(19989): at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(Unknown Source:2) E/AndroidRuntime(19989): at com.google.android.gms.tasks.zzm.run(Unknown Source:25) E/AndroidRuntime(19989): at android.os.Handler.handleCallback(Handler.java:958) E/AndroidRuntime(19989): at android.os.Handler.dispatchMessage(Handler.java:99) E/AndroidRuntime(19989): at android.os.Looper.loopOnce(Looper.java:257) E/AndroidRuntime(19989): at android.os.Looper.loop(Looper.java:368) E/AndroidRuntime(19989): at android.app.ActivityThread.main(ActivityThread.java:8839) E/AndroidRuntime(19989): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(19989): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) E/AndroidRuntime(19989): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) E/AndroidRuntime(19989): Caused by: android.os.RemoteException: Remote stack trace: E/AndroidRuntime(19989): at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14900) E/AndroidRuntime(19989): at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570) E/AndroidRuntime(19989): at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005) E/AndroidRuntime(19989): at android.os.Binder.execTransactInternal(Binder.java:1387) E/AndroidRuntime(19989): at android.os.Binder.execTransact(Binder.java:1299) E/AndroidRuntime(19989):
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
ragulpr@Admins-MacBook-Air ev-flutter % flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.19.5 on channel stable at /Users/ragulpr/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 months ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ragulpr/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.91.1)
    • VS Code at /Users/ragulpr/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (6 available)
    • CPH2467 (mobile)        • 652e778c                             • android-arm64  • Android 14 (API 34)
    • iPhone (mobile)         • 00008030-001451981A30802E            • ios            • iOS 17.6.1 21G93
    • Sharath iPhone (mobile) • 00008110-000C2D413661401E            • ios            • iOS 17.1.2 21B101
    • iPhone 15 (mobile)      • 48838D81-081C-449E-9552-E6597A3FE747 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for Pratheep’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for KEERTHANA’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Arvind’s iPhone . Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Treesa’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @ragul-steamA 
`sms_autofill` is a 3rd plugin/package, so please report the issue to its developers for better support. Closing this as it's not an issue in Flutter framework or 1st party packages.
