### ISSUE TITLE
Relanding FlutterViewTest.java in embedding

### ISSUE THREAD

**Issue by jesswrd** [flutter/flutter#154746]
While working on https://github.com/flutter/flutter/issues/99421, I discovered that FlutterViewTest.java was possibly accidentally deleted at this PR: https://github.com/flutter/engine/pull/44047

This bug tracks restoring the FlutterViewTest file and ensuring that the tests pass.
Path to FlutterViewTest: shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java

Tests that need to be readded: 
- [x] itSendsTextShowPasswordToFrameworkOnAttach
- [x] setPaddingTopToZeroForFullscreenMode
- [ ] itSendsDarkPlatformBrightnessToFlutter
- [ ] itSendsLightPlatformBrightnessToFlutter
- [x] setPaddingTopToZeroForFullscreenModeLegacy

**Comment by reidbaker** [comment]
https://github.com/flutter/engine/pull/55048

**Comment by reidbaker** [comment]
and another test 
```
java.lang.ClassCastException: Cannot cast org.robolectric.shadows.ShadowViewGroup to io.flutter.embedding.android.FlutterViewTest$ShadowFullscreenView
        at java.base/java.lang.Class.cast(Class.java:3889)
        at android.view.View.getWindowSystemUiVisibility(View.java)
        at com.android.internal.policy.DecorView.updateColorViews(DecorView.java:1102)
        at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:3021)
        at android.view.Window.setFlags(Window.java:1192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.robolectric.shadows.ShadowWindow$WindowReflector$$Reflector381.setFlags(Unknown Source)
        at org.robolectric.shadows.ShadowWindow.setFlags(ShadowWindow.java:52)
        at android.view.Window.setFlags(Window.java)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2395)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2707)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2130)
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:171)
        at android.app.Activity.performCreate(Activity.java:8004)
        at android.app.Activity.performCreate(Activity.java:7979)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:382)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:138)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:243)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:136)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:146)
        at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:340)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:134)
        at io.flutter.embedding.android.FlutterViewTest.setPaddingTopToZeroForFullscreenMode(FlutterViewTest.java:452)
```

```
  @SuppressWarnings("deprecation")
  // Robolectric.setupActivity
  // TODO(reidbaker): https://github.com/flutter/flutter/issues/133151
  // This test uses the API 30+ Algorithm for window insets. The legacy algorithm is
  // set to -1 values, so it is clear if the wrong algorithm is used.
  @Test
  @TargetApi(30)
  @Config(
      sdk = 30,
      shadows = {
        FlutterViewTest.ShadowFullscreenView.class,
        FlutterViewTest.ShadowFullscreenViewGroup.class
      })
  public void setPaddingTopToZeroForFullscreenMode() {
    FlutterView flutterView = new FlutterView(Robolectric.setupActivity(Activity.class));
    FlutterEngine flutterEngine = spy(new FlutterEngine(ctx, mockFlutterLoader, mockFlutterJni));
    FlutterRenderer flutterRenderer = spy(new FlutterRenderer(mockFlutterJni));
    when(flutterEngine.getRenderer()).thenReturn(flutterRenderer);

    // When we attach a new FlutterView to the engine without any system insets, the viewport
    // metrics
    // default to 0.
    flutterView.attachToFlutterEngine(flutterEngine);
    ArgumentCaptor<FlutterRenderer.ViewportMetrics> viewportMetricsCaptor =
        ArgumentCaptor.forClass(FlutterRenderer.ViewportMetrics.class);
    verify(flutterRenderer).setViewportMetrics(viewportMetricsCaptor.capture());
    assertEquals(0, viewportMetricsCaptor.getValue().viewPaddingTop);

    // Then we simulate the system applying a window inset.
    WindowInsets windowInsets =
        new WindowInsets.Builder()
            .setInsets(
                android.view.WindowInsets.Type.navigationBars()
                    | android.view.WindowInsets.Type.statusBars(),
                Insets.of(100, 100, 100, 100))
            .build();
    flutterView.onApplyWindowInsets(windowInsets);

    // Verify.
    verify(flutterRenderer, times(3)).setViewportMetrics(viewportMetricsCaptor.capture());
    validateViewportMetricPadding(viewportMetricsCaptor, 100, 100, 100, 100);
  }
  ```

**Comment by reidbaker** [comment]
```
FlutterViewTest > itSendsLightPlatformBrightnessToFlutter FAILED
    java.lang.NullPointerException: Cannot invoke "io.flutter.embedding.engine.systemchannels.SettingsChannel$MessageBuilder.setNativeSpellCheckServiceDefined(boolean)" because the return value of "io.flutter.embedding.engine.systemchannels.SettingsChannel$MessageBuilder.setDisplayMetrics(android.util.DisplayMetrics)" is null
        at io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter(FlutterView.java:1449)
        at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:1159)
        at io.flutter.embedding.android.FlutterViewTest.itSendsLightPlatformBrightnessToFlutter(FlutterViewTest.java:298)
```

```
 @SuppressWarnings("deprecation")
  // Robolectric.setupActivity
  // TODO(reidbaker): https://github.com/flutter/flutter/issues/133151
  // TODO(mattcarroll): turn this into an e2e test. GitHub #42990
  @Test
  public void itSendsLightPlatformBrightnessToFlutter() {
    // Setup test.
    AtomicReference<SettingsChannel.PlatformBrightness> reportedBrightness =
        new AtomicReference<>();

    // FYI - The default brightness is LIGHT, which is why we don't need to configure it.
    FlutterView flutterView = new FlutterView(Robolectric.setupActivity(Activity.class));
    FlutterEngine flutterEngine = spy(new FlutterEngine(ctx, mockFlutterLoader, mockFlutterJni));

    SettingsChannel fakeSettingsChannel = mock(SettingsChannel.class);
    SettingsChannel.MessageBuilder fakeMessageBuilder = mock(SettingsChannel.MessageBuilder.class);
    when(fakeMessageBuilder.setTextScaleFactor(any(Float.class))).thenReturn(fakeMessageBuilder);
    when(fakeMessageBuilder.setNativeSpellCheckServiceDefined(any(Boolean.class)))
        .thenReturn(fakeMessageBuilder);
    when(fakeMessageBuilder.setBrieflyShowPassword(any(Boolean.class)))
        .thenReturn(fakeMessageBuilder);
    when(fakeMessageBuilder.setUse24HourFormat(any(Boolean.class))).thenReturn(fakeMessageBuilder);
    when(fakeMessageBuilder.setPlatformBrightness(any(SettingsChannel.PlatformBrightness.class)))
        .thenAnswer(
            new Answer<SettingsChannel.MessageBuilder>() {
              @Override
              public SettingsChannel.MessageBuilder answer(InvocationOnMock invocation)
                  throws Throwable {
                reportedBrightness.set(
                    (SettingsChannel.PlatformBrightness) invocation.getArguments()[0]);
                return fakeMessageBuilder;
              }
            });
    when(fakeSettingsChannel.startMessage()).thenReturn(fakeMessageBuilder);
    when(flutterEngine.getSettingsChannel()).thenReturn(fakeSettingsChannel);

    flutterView.attachToFlutterEngine(flutterEngine);

    // Execute behavior under test.
    flutterView.sendUserSettingsToFlutter();

    // Verify results.
    assertEquals(SettingsChannel.PlatformBrightness.light, reportedBrightness.get());
  }
```

**Comment by reidbaker** [comment]
```
FlutterViewTest > setPaddingTopToZeroForFullscreenModeLegacy FAILED
    java.lang.ClassCastException: Cannot cast org.robolectric.shadows.ShadowViewGroup to io.flutter.embedding.android.FlutterViewTest$ShadowFullscreenView
        at java.base/java.lang.Class.cast(Class.java:3889)
        at android.view.View.getWindowSystemUiVisibility(View.java)
        at com.android.internal.policy.DecorView.updateColorViews(DecorView.java:1056)
        at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:2986)
        at android.view.Window.setFlags(Window.java:1111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.robolectric.shadows.ShadowWindow$WindowReflector$$Reflector367.setFlags(Unknown Source)
        at org.robolectric.shadows.ShadowWindow.setFlags(ShadowWindow.java:52)
        at android.view.Window.setFlags(Window.java)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2335)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2672)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2071)
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:160)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:382)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:138)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:243)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:136)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:146)
        at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:340)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:134)
        at io.flutter.embedding.android.FlutterViewTest.setPaddingTopToZeroForFullscreenModeLegacy(FlutterViewTest.java:494)
```

```
@SuppressWarnings("deprecation")
  // Robolectric.setupActivity
  // TODO(reidbaker): https://github.com/flutter/flutter/issues/133151
  // This test uses the pre-API 30 Algorithm for window insets.
  @Test
  @TargetApi(28)
  @Config(
      sdk = 28,
      shadows = {
        FlutterViewTest.ShadowFullscreenView.class,
        FlutterViewTest.ShadowFullscreenViewGroup.class
      })
  public void setPaddingTopToZeroForFullscreenModeLegacy() {
    FlutterView flutterView = new FlutterView(Robolectric.setupActivity(Activity.class));
    FlutterEngine flutterEngine = spy(new FlutterEngine(ctx, mockFlutterLoader, mockFlutterJni));
    FlutterRenderer flutterRenderer = spy(new FlutterRenderer(mockFlutterJni));
    when(flutterEngine.getRenderer()).thenReturn(flutterRenderer);

    // When we attach a new FlutterView to the engine without any system insets, the viewport
    // metrics
    // default to 0.
    flutterView.attachToFlutterEngine(flutterEngine);
    ArgumentCaptor<FlutterRenderer.ViewportMetrics> viewportMetricsCaptor =
        ArgumentCaptor.forClass(FlutterRenderer.ViewportMetrics.class);
    verify(flutterRenderer).setViewportMetrics(viewportMetricsCaptor.capture());
    assertEquals(0, viewportMetricsCaptor.getValue().viewPaddingTop);

    // Then we simulate the system applying a window inset.
    WindowInsets windowInsets = mock(WindowInsets.class);
    mockSystemWindowInsets(windowInsets, 100, 100, 100, 100);
    flutterView.onApplyWindowInsets(windowInsets);

    // Verify.
    verify(flutterRenderer, times(2)).setViewportMetrics(viewportMetricsCaptor.capture());
    validateViewportMetricPadding(viewportMetricsCaptor, 100, 0, 100, 0);
  }
```

**Comment by reidbaker** [comment]
Reopening because I had to remove 5 tests.
