### ISSUE TITLE
Exception has occurred. FirebaseAuthException 

### ISSUE THREAD

**Issue by mmmcompanies** [flutter/flutter#154899]
### Steps to reproduce

I have call the auth methods -- 

```
final UserCredential userCredential = await _auth.signInWithEmailAndPassword(
      email: email,
      password: password,
    );
```

    
i have passed wrong email and password for check and handle errors in code. 

### Expected results

```
 FirebaseAuthException catch (e) {
    // Handle Firebase authentication-related errors
    switch (e.code) {
      case 'email-already-in-use':
        return 'This email address is already in use. Please try logging in or use a different email.';
      case 'invalid-email':
        return 'The email address is invalid. Please check and enter a valid email.';
      case 'operation-not-allowed':
        return 'Email/password accounts are not enabled. Please contact support.';
      case 'weak-password':
        return 'The password provided is too weak. Please use a stronger password.';
      case 'too-many-requests':
        return 'Too many requests at the moment. Please try again later.';
      case 'user-token-expired':
        return 'Your session has expired. Please log in again.';
      case 'network-request-failed':
        return 'Network error occurred. Please check your internet connection.';
        case 'invalid-credential':
        return 'The supplied auth credential is incorrect, malformed or has expired.';
      default:
        return 'An unknown error occurred: ${e.message}';
    }
```    
    
must be handle not the crash app or Exception has occurred.

### Actual results

```
FirebaseAuthException catch (e) {
    // Handle Firebase authentication-related errors
```
    
    
always run this code  when any error coming from auth. 

```
 // SIGN IN METHOD with password validation and saving user data
 Future<String?> signIn({
  required String email,
  required String password,
}) async {
  try {
    // Attempt to sign in the user with email and password
    final UserCredential userCredential = await _auth.signInWithEmailAndPassword(
      email: email,
      password: password,
    );

    // Check if the user credential is valid
    if (userCredential.user == null) {
      throw FirebaseAuthException(
        message: "User not found",
        code: "user-not-found",
      );
    }

    // Retrieve the user's UID
    String uid = userCredential.user!.uid;

    // Fetch the user's data from Firebase Realtime Database
    DatabaseEvent event = await _dbRef.child('users/$uid').once();
    DataSnapshot snapshot = event.snapshot;

    // Ensure that the user data exists in the database
    if (snapshot.value == null) {
      throw FirebaseAuthException(
        message: "User data not found",
        code: "user-not-found",
      );
    }

    // Cast snapshot value to Map
    Map<dynamic, dynamic> userData = snapshot.value as Map<dynamic, dynamic>;

    // Validate the user's password against the stored hashed password
    bool isValidPassword = BCrypt.checkpw(password, userData['password'] as String);
    if (!isValidPassword) {
      throw FirebaseAuthException(
        message: "Invalid password",
        code: "wrong-password",
      );
    }

    // Cast the Map<dynamic, dynamic> to Map<String, dynamic>
    Map<String, dynamic> userDataStringKey = Map<String, dynamic>.from(userData);

    // Convert the user data to a UserModel instance
    UserModel userModel = UserModel.fromMap(userDataStringKey);

    // Save the user data locally using SharedPreferences
    await SharedPrefsManager.instance.saveUser(userModel);

    // Return null if the sign-in is successful
    return null;
  } on FirebaseAuthException catch (e) {
    // Handle Firebase authentication-related errors
    switch (e.code) {
      case 'email-already-in-use':
        return 'This email address is already in use. Please try logging in or use a different email.';
      case 'invalid-email':
        return 'The email address is invalid. Please check and enter a valid email.';
      case 'operation-not-allowed':
        return 'Email/password accounts are not enabled. Please contact support.';
      case 'weak-password':
        return 'The password provided is too weak. Please use a stronger password.';
      case 'too-many-requests':
        return 'Too many requests at the moment. Please try again later.';
      case 'user-token-expired':
        return 'Your session has expired. Please log in again.';
      case 'network-request-failed':
        return 'Network error occurred. Please check your internet connection.';
        case 'invalid-credential':
        return 'The supplied auth credential is incorrect, malformed or has expired.';
      default:
        return 'An unknown error occurred: ${e.message}';
    }
  } on FirebaseException catch (e) {
    // Handle PlatformException
    if (e.code == 'ERROR_INVALID_CREDENTIAL') {
      return 'The supplied auth credential is incorrect, malformed, or expired.';
    } 
    if (e.code == 'invalid-credential') {
      return 'The supplied auth credential is incorrect, malformed, or expired.';
    }
    else {
      return 'An unknown error occurred: ${e.message}';
    }
  } catch (e) {
    // Catch any other types of exceptions and return a general error message
    return 'An unknown error occurred: ${e.toString()}';
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

![Screenshot 2024-09-10 at 9 02 43 AM](https://github.com/user-attachments/assets/8aa84f46-b571-4dee-adf9-2ecfbdf9d9e3)

![Screenshot 2024-09-10 at 9 25 46 AM](https://github.com/user-attachments/assets/3760ef61-eb2c-4685-999e-8c65709285be)
</details>

### Logs

```
I/flutter ( 7713): Main
I/flutter ( 7713): 3
I/flutter ( 7713): Main
I/flutter ( 7713): 0
E/flutter ( 7713): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7713): #0      State.setState (package:flutter/src/widgets/framework.dart:1159)
E/flutter ( 7713): #1      _WrapperState.didChangeAppLifecycleState.<anonymous closure> (package:shoonya/ui/main_screen.dart:120)
E/flutter ( 7713): #2      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420)
E/flutter ( 7713): #3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
E/flutter ( 7713): #4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
E/flutter ( 7713): #5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
E/flutter ( 7713): 
```

### Flutter Doctor output

demo % flutter doctor -v

```
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.0 23A344 darwin-x64, locale en-GB)
    • Flutter version 3.24.2 on channel stable at /Users/madankumawat/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (6 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/madankumawat/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (4 available)
    • RMX3782 (mobile)   • S4BIYXTCDM95YXVW          • android-arm64  • Android 14 (API 34)
    • iPhone 11 (mobile) • 00008030-0014058611FA2345 • ios            • iOS 17.5.1 21F90
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 14.0 23A344 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by danagbemava-nc** [comment]
This is an issue with the firebase plugin not flutter. Closing from here as this should be filed on the flutterfire repo. 

Thank you
