### ISSUE TITLE
Garbage collector test for `menu_anchor` sometimes flakes

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#154858]
https://github.com/flutter/flutter/pull/154843 flakes while running `Mac framework_tests_impeller`, even though its not possible that any of the code in this PR affected this test suite.

The [specific failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737244374199615553/+/u/run_test.dart_for_framework_tests_shard_and_subshard_impeller/stdout) is as follows:

```txt
06:10 +7937 ~21: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart: Garbage collector destroys child _MenuAnchorState after parent is closed
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: null
  Actual: _SubmenuButtonState:<_SubmenuButtonState#31f73(lifecycle state: defunct, not mounted)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart:4508:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart line 4508
The test description was:
  Garbage collector destroys child _MenuAnchorState after parent is closed
```

This test was somewhat recently added in https://github.com/flutter/flutter/pull/149586.

The following diff is somewhat suspicious:
```diff
+ // Garbage collect. 1 should be enough, but 3 prevents flaky tests.
+ await tester.runAsync<void>(() async {
+   await forceGC(fullGcCycles: 3);
+ });
```

I suspect if we don't know why a single `forceGC` doesn't work, we can't guarantee `3` will work either.

**Comment by Piinks** [comment]
FYI @davidhicks980 can you share more context on why we called forceGC so many times?

**Comment by davidhicks980** [comment]
Yeah, I actually had this problem so I asked about it in the chat https://discord.com/channels/608014603317936148/608021635370582020/1252245824113475705 

The only example test using forceGC I could find that in the Flutter repo which wasn't a test driver test called forceGC 3 times, so I just copied that 😕. I'm not too familiar with how the dart GC works, but I know that forceGC just allocates an array until the reachability barrier increments. Calling forceGC once was flaky -- I should have added that as a comment. The test I used as a reference is here:

https://github.com/flutter/flutter/blob/621e7ef9511fd224d7621f26c413beba2f4c0121/packages/flutter/test/widgets/widget_inspector_test.dart#L336

**Comment by Piinks** [comment]
Since we apparently have know forceGC is flaky (see widget inspector test above), I have put up a [PR](https://github.com/flutter/flutter/pull/155968) to disable this menu test until we can fix the root issue.
It was flaking on other shards, not just impeller.
I will leave this issue open for follow up.
