### ISSUE TITLE
[google_maps_flutter] `setAndGetScrollPosition` failing on iOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#154826]
I'm seeing persistent, but seemingly slightly flaky in how it manifests, failures in `setAndGetScrollPosition` in `webview_flutter` and `webview_flutter_wkwebview` in post-submit, closing the tree. It's showing up in [this commit](https://github.com/flutter/packages/pull/7599), but since presubmit past, while postsubmit failed four times in a row, it seems like maybe it's OOB rather than from the roll? Or it's flake and presubmit was just lucky.

I'm going to disable these test for now to re-open the tree. /cc @bparrishMines

**Comment by stuartmorgan** [comment]
This also affects the `setAndGetAndListenScrollPosition` variant.

Also, I forgot to include the failures. The values are unexpected; examples:

```
00:41 +13 ~1: /Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart: Programmatic Scroll setAndGetAndListenScrollPosition
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <123>
  Actual: <311.3333333333333>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart:796:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter_wkwebview/example/integration_test/webview_flutter_test.dart line 796
The test description was:
  setAndGetAndListenScrollPosition
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <246>
  Actual: <434.3333333333333>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart:564:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Volumes/Work/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart line 564
The test description was:
  setAndGetScrollPosition
════════════════════════════════════════════════════════════════════════════════════════════════════

00:34 +8 ~2 -1: Programmatic Scroll setAndGetScrollPosition [E]                                                                                                                                        
  Test failed. See exception logs above.
  The test description was: setAndGetScrollPosition
```

**Comment by bparrishMines** [comment]
Looking at the test for `webview_flutter`. This can probably be fixed by changing the test  to wait for the `onScrollPositionChange` callback to trigger with the correct value. I'll create a PR for this.
