### ISSUE TITLE
Integration driver will not show the correct result when testWidget has retries

### ISSUE THREAD

**Issue by guixijing** [flutter/flutter#154810]
### Steps to reproduce

1. Include the test suite `group('', (){ ... }, retry: 2)`
2. run integration test via `flutter drive`
3. If the test failed once but succeed in retry
4. The overall result of test will NOT show `All tests passed.` with `exit(0)` 

### Expected results

When test case passed by retry, the result should not print the error and exit(0).

### Actual results

When test case passed by retry, the result will throw errors and exit(1)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![image](https://github.com/user-attachments/assets/686456b1-012c-4598-a254-0c5d59292614)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.6.1 23G93 darwin-arm64, locale
    en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.1)
[✓] VS Code (version 1.92.2)
```

</details>

**Comment by huycozy** [comment]
Hi @guixijing, please share a complete test sample code for this case. Thanks!

**Comment by guixijing** [comment]
@huycozy 
#### The entry file for the test case :
```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'my_test/test_case_1_test.dart';

// entry_file.dart
void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group("test_case_1_integration_test", test_case_1_test.main, retry: 3);
}

```

#### The test case file:
```
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:my_project/view/app_view.dart';

// my_test/test_case_1_test.dart
void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test case 1:', () {
    testWidgets('should go to next page', (tester) async {
      await tester.pumpWidget(AppView());
      await tester.pumpAndSettle();


      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_home_screenshot",
      );

      await tester.tap(find.text('Home'));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Next'));

      expect(find.text('Next Page'), findsOneWidget);
      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_next_page_screenshot",
      );
    });
  });
}

_takeScreenShot({binding, tester, String? screenShotName}) async {
  if (kIsWeb) {
    await binding.takeScreenshot(screenShotName);
    return;
  } else if (Platform.isAndroid) {
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
  }
  await binding.takeScreenshot(screenShotName);
}
```
#### The command we are using
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/entry_file.dart
```

**Comment by huycozy** [comment]
Can you also share the content of `app_view.dart` file?

**Comment by guixijing** [comment]
@huycozy 
```
import 'package:flutter/material.dart';

// app_view.dart
class AppView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Page')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const SizedBox(height: 20.0),
          Center(
            child: TextButton(
              child: const Text('Next'),
              onPressed: () => _navigateToNextPage(context),
            ),
          ),
        ],
      ),
    );
  }

  void _navigateToNextPage(BuildContext context) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (BuildContext context) => const NextPageScreen(),
      ),
    );
  }
}

class NextPageScreen extends StatelessWidget {
  const NextPageScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Next Page'),
      ),
      body: const Center(
        child: Text('This is the 2nd Page'),
      ),
    );
  }
}
```

If could be reproduced when we add a random logic in test case

```
// my_test/test_case_1_test.dart
void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test case 1:', () {
    testWidgets('should go to next page', (tester) async {
      await tester.pumpWidget(AppView());
      await tester.pumpAndSettle();


      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_home_screenshot",
      );

      await tester.tap(find.text('Home'));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Next'));

     Random random = new Random();
     int randomNumber = random.nextInt(3)
     expect(find.text(['Next Page', 'Wrong Page', 'Home Page'][randomNumber]), findsOneWidget);
      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_next_page_screenshot",
      );
    });
  });
}

_takeScreenShot({binding, tester, String? screenShotName}) async {
  if (kIsWeb) {
    await binding.takeScreenshot(screenShotName);
    return;
  } else if (Platform.isAndroid) {
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
  }
  await binding.takeScreenshot(screenShotName);
}
```

**Comment by huycozy** [comment]
I see this error when running the test:

```console
The finder "Found 0 widgets with text "Home": []" (used in a call
to "tap()") could not find any matching widgets.
```

So I commented out `expect(find.text(['Next Page', 'Wrong Page', 'Home Page'][randomNumber]), findsOneWidget);` to make the test pass but hit another error on `_takeScreenShot` method: `Surface already converted to an image`

<details>
<summary>Complete error output</summary>

```console
I/flutter (  877): 00:00 +0: test case 1: should go to next page
VMServiceFlutterDriver: Connected to Flutter application.
D/CompatibilityChangeReporter(  877): Compat change id reported: 236825255; UID 10458; state: ENABLED
I/flutter (  877): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (  877): The following assertion was thrown running a test:
I/flutter (  877): Surface already converted to an image
I/flutter (  877): 'package:integration_test/src/_callback_io.dart':
I/flutter (  877): Failed assertion: line 71 pos 12: '!_isSurfaceRendered'
I/flutter (  877): 
I/flutter (  877): When the exception was thrown, this was the stack:
I/flutter (  877): #2      _IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/src/_callback_io.dart:71:12)
I/flutter (  877): #3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:201:27)
I/flutter (  877): #4      _takeScreenShot (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:45:19)
I/flutter (  877): #5      main.<anonymous closure>.<anonymous closure> (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:31:13)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): (elided 2 frames from class _AssertionError)
I/flutter (  877): 
I/flutter (  877): The test description was:
I/flutter (  877):   should go to next page
I/flutter (  877): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  877): 00:01 +0: test case 1: should go to next page [E]
I/flutter (  877):   Test failed. See exception logs above.
I/flutter (  877):   The test description was: should go to next page
I/flutter (  877):   
I/flutter (  877): Retry: test case 1: should go to next page
I/flutter (  877): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (  877): The following assertion was thrown running a test:
I/flutter (  877): Surface already converted to an image
I/flutter (  877): 'package:integration_test/src/_callback_io.dart':
I/flutter (  877): Failed assertion: line 71 pos 12: '!_isSurfaceRendered'
I/flutter (  877): 
I/flutter (  877): When the exception was thrown, this was the stack:
I/flutter (  877): #2      _IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/src/_callback_io.dart:71:12)
I/flutter (  877): #3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:201:27)
I/flutter (  877): #4      _takeScreenShot (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:45:19)
I/flutter (  877): #5      main.<anonymous closure>.<anonymous closure> (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:31:13)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): (elided 2 frames from class _AssertionError)
I/flutter (  877): 
I/flutter (  877): The test description was:
I/flutter (  877):   should go to next page
I/flutter (  877): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  877):   Test failed. See exception logs above.
I/flutter (  877):   The test description was: should go to next page
I/flutter (  877):   
I/flutter (  877): Retry: test case 1: should go to next page
I/flutter (  877): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (  877): The following assertion was thrown running a test:
I/flutter (  877): Surface already converted to an image
I/flutter (  877): 'package:integration_test/src/_callback_io.dart':
I/flutter (  877): Failed assertion: line 71 pos 12: '!_isSurfaceRendered'
I/flutter (  877): 
I/flutter (  877): When the exception was thrown, this was the stack:
I/flutter (  877): #2      _IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/src/_callback_io.dart:71:12)
I/flutter (  877): #3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:201:27)
I/flutter (  877): #4      _takeScreenShot (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:45:19)
I/flutter (  877): #5      main.<anonymous closure>.<anonymous closure> (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:31:13)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): (elided 2 frames from class _AssertionError)
I/flutter (  877): 
I/flutter (  877): The test description was:
I/flutter (  877):   should go to next page
I/flutter (  877): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  877):   Test failed. See exception logs above.
I/flutter (  877):   The test description was: should go to next page
I/flutter (  877):   
I/flutter (  877): Retry: test case 1: should go to next page
D/ProfileInstaller(  877): Installing profile for com.example.repro_issues
I/flutter (  877): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (  877): The following assertion was thrown running a test:
I/flutter (  877): Surface already converted to an image
I/flutter (  877): 'package:integration_test/src/_callback_io.dart':
I/flutter (  877): Failed assertion: line 71 pos 12: '!_isSurfaceRendered'
I/flutter (  877): 
I/flutter (  877): When the exception was thrown, this was the stack:
I/flutter (  877): #2      _IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/src/_callback_io.dart:71:12)
I/flutter (  877): #3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:201:27)
I/flutter (  877): #4      _takeScreenShot (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:45:19)
I/flutter (  877): #5      main.<anonymous closure>.<anonymous closure> (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:31:13)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): #8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
I/flutter (  877): <asynchronous suspension>
I/flutter (  877): (elided 2 frames from class _AssertionError)
I/flutter (  877): 
I/flutter (  877): The test description was:
I/flutter (  877):   should go to next page
I/flutter (  877): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (  877):   Test failed. See exception logs above.
I/flutter (  877):   The test description was: should go to next page
I/flutter (  877):   
I/flutter (  877): 00:03 +0 -1: (tearDownAll)
I/flutter (  877): 00:03 +1 -1: Some tests failed.
Failure Details:
Failure in method: should go to next page
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
Surface already converted to an image
'package:integration_test/src/_callback_io.dart':
Failed assertion: line 71 pos 12: '!_isSurfaceRendered'

When the exception was thrown, this was the stack:
#2      _IOCallbackManager.convertFlutterSurfaceToImage (package:integration_test/src/_callback_io.dart:71:12)
#3      IntegrationTestWidgetsFlutterBinding.convertFlutterSurfaceToImage (package:integration_test/integration_test.dart:201:27)
#4      _takeScreenShot (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:45:19)
#5      main.<anonymous closure>.<anonymous closure> (file:///Users/huynq/Desktop/repro_issues/integration_test/retry_154810_test.dart:31:13)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
#8      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  should go to next page
═════════════════════════════════════════════════════════════════

end of failure 1
```
</details>

Here is the complete sample code, can you try upgrading to the latest Flutter stable 3.24.2 and confirm if you also hit the error as mine?

<details>
<summary>Sample code</summary>

```dart
import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test case 1:', () {
    testWidgets('should go to next page', (tester) async {
      await tester.pumpWidget(AppView());
      await tester.pumpAndSettle();

      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_home_screenshot",
      );

      await tester.tap(find.text('Home Page'));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Next'));

      // Random random = Random();
      // int randomNumber = random.nextInt(3);
      // expect(find.text(['Next Page', 'Wrong Page', 'Home Page'][randomNumber]), findsOneWidget);
      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_next_page_screenshot",
      );
    });
  }, retry: 3);
}

_takeScreenShot({binding, tester, String? screenShotName}) async {
  if (kIsWeb) {
    await binding.takeScreenshot(screenShotName);
    return;
  } else if (Platform.isAndroid) {
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
  }
  await binding.takeScreenshot(screenShotName);
}

class AppView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Page')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const SizedBox(height: 20.0),
          Center(
            child: TextButton(
              child: const Text('Next'),
              onPressed: () => _navigateToNextPage(context),
            ),
          ),
        ],
      ),
    );
  }

  void _navigateToNextPage(BuildContext context) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (BuildContext context) => const NextPageScreen(),
      ),
    );
  }
}

class NextPageScreen extends StatelessWidget {
  const NextPageScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Next Page'),
      ),
      body: const Center(
        child: Text('This is the 2nd Page'),
      ),
    );
  }
}

```
</details>

**Comment by guixijing** [comment]
Hi @huycozy , sorry for the incorrect sample code. I've tailored the test file to focus on reproducing the issue.  App view file will remain the same.

The entry file for the test case :
```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'my_test/test_case_1_test.dart' as test_case_1_test;

// entry_file.dart
void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group("test_case_1_integration_test", test_case_1_test.main, retry: 3);
}
```


```
// my_test/test_case_1_test.dart
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test case 1:', () {
    testWidgets('should go to next page', (tester) async {
      await tester.pumpWidget(AppView());
      await tester.pumpAndSettle();

      await tester.tap(find.text('Home Page'));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Next'));
      await tester.pumpAndSettle();

      Random random = Random();
      int randomNumber = random.nextInt(3);
      expect(find.text(['Next Page', 'Wrong Page', 'Home Page'][randomNumber]), findsOneWidget);
    });
  });
}
```

I've upgraded to the latest 3.24.3. I think the issue is still there. All tests passed with retries but the `integration_test_driver_extended.dart` will still print out the failure details instead of `All tests passed.`

![image](https://github.com/user-attachments/assets/b6b65171-eaf2-4925-9d4c-80988129766f)

#### My flutter doctor:
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (5 available)
[✓] Network resources

```

Note: You might need to run `flutter drive` multiple time if it does not hit the retry.

**Comment by darshankawar** [comment]
@guixijing 
Instead of `flutter driver`, can you try with `integration_test` directly to see if you still get same behavior or not ?

https://docs.flutter.dev/testing/integration-tests#test-on-a-mobile-device

**Comment by guixijing** [comment]
@darshankawar , `integration_test` will not have this issue. But we need to take screen shot so we have to use the driver.

I think the problem is coming from [this line](https://github.com/flutter/flutter/blob/b4903228ebcff6b4b685860efd8c091beada9b55/packages/integration_test/lib/integration_test_driver_extended.dart#L169) in `integration_test_driver_extended.dart`. If the tests failed, retried and all passed, the `response.allTestsPassed` will not be true.

**Comment by darshankawar** [comment]
Thanks for the update. I am trying to replicate this using the setup you have. 
Where is this file located in your project structure ?


> // my_test/test_case_1_test.dart

I have below setup:

integration_test/entry_file.dart
main.dart --> https://github.com/flutter/flutter/issues/154810#issuecomment-2345328335


> test_driver/integration_test.dart

What does this file contain ?

**Comment by guixijing** [comment]
@darshankawar Here is the project structure, can remove the `my_test` from the uri
![image](https://github.com/user-attachments/assets/45414f65-6d6c-48c4-9e7b-849426bf53d8)

The `test_driver/integration_test.dart` contains:
```
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  await integrationDriver();
}
```

**Comment by darshankawar** [comment]
Thanks for the update. Using the details provided above and running the flutter driver command as below, does show the reported error, ie throws `exit(1)` error.

<details>
<summary> main.dart </summary>

```

import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test case 1:', () {
    testWidgets('should go to next page', (tester) async {
      await tester.pumpWidget(AppView());
      await tester.pumpAndSettle();

      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_home_screenshot",
      );

      await tester.tap(find.text('Home Page'));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Next'));

      // Random random = Random();
      // int randomNumber = random.nextInt(3);
      // expect(find.text(['Next Page', 'Wrong Page', 'Home Page'][randomNumber]), findsOneWidget);
      await _takeScreenShot(
        binding: binding,
        tester: tester,
        screenShotName: "test_case_next_page_screenshot",
      );
    });
  }, retry: 3);
}

_takeScreenShot({binding, tester, String? screenShotName}) async {
  if (kIsWeb) {
    await binding.takeScreenshot(screenShotName);
    return;
  } else if (Platform.isAndroid) {
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
  }
  await binding.takeScreenshot(screenShotName);
}

class AppView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Page')),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const SizedBox(height: 20.0),
          Center(
            child: TextButton(
              child: const Text('Next'),
              onPressed: () => _navigateToNextPage(context),
            ),
          ),
        ],
      ),
    );
  }

  void _navigateToNextPage(BuildContext context) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (BuildContext context) => const NextPageScreen(),
      ),
    );
  }
}

class NextPageScreen extends StatelessWidget {
  const NextPageScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Next Page'),
      ),
      body: const Center(
        child: Text('This is the 2nd Page'),
      ),
    );
  }
}


```

</details>

<details>
<summary> test_driver/integration_test.dart </summary>

```

import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  await integrationDriver();
}

```

</details>

Under `integration_test` folder, https://github.com/flutter/flutter/issues/154810#issuecomment-2351359294

And root-cause probably as mentioned here https://github.com/flutter/flutter/issues/154810#issuecomment-2352114594

```
Stable : 3.24.3
Master : 3.26.0-1.0.pre.152
```

**Comment by nquangminhBK** [comment]
I also encountered this issue, even though I didn’t "retry" the test.
![image](https://github.com/user-attachments/assets/2dcf10de-ca65-4845-80e0-ca5535080d14)
I found that it's related to the find.text or find.textContaining
Flutter version  3.24.3
