### ISSUE TITLE
ValueNotifier setter not recognized as a function

### ISSUE THREAD

**Issue by ashtonthomas** [flutter/flutter#15482]
# ValueNotifier<T> setter 

The [set value(T newValue)](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/change_notifier.dart#L213-L218) on ValueNotifier doesn't seem to be working. When I try to use it as I would expect I get the following error:

IDE Error: `'value' isn't a function`

![](https://cl.ly/0W0K3Q2N2F20/download/Image%202018-03-13%20at%206.21.01%20AM.png)

As a workaround I copied the ValueNotifier code into my file and just renamed to `FooValueNotifier` with a `foo` (just something other than `value`) method to act like the setter. I had to remove the `set` keyword and this worked.

```
  foo(T newValue) {
    if (_value == newValue)
      return;
    _value = newValue;
    notifyListeners();
  }
```

## Steps to Reproduce

Instantiate a ValueNotifier and then try to set a new value vis the `set value(T value` method.

## Logs

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyApp(dirty):
Class 'String' has no instance method 'call'.
Receiver: "initial string"
Tried calling: call("new string")

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      MyApp.build (/Users/atown/git/misc/value_change_reproduce/lib/main.dart:11:20)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
#14     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
#15     runApp (package:flutter/src/widgets/binding.dart:699:7)
#16     main (/Users/atown/git/misc/value_change_reproduce/lib/main.dart:3:16)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze`:

```
➜  value_change_reproduce flutter analyze
Analyzing /Users/atown/git/misc/value_change_reproduce...
  error • 'value' isn't a function at lib/main.dart:11:20 • invocation_of_non_function
  error • 'value' isn't a function at lib/main.dart:14:18 • invocation_of_non_function
2 issues found.
(Ran in 6.8s)
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

```
➜  flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.5 at /Users/atown/git/flutter/flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/atown/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • iPhone X • 87F12481-BCBA-422D-B2C0-5C9F10698EAB • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by xqwzts** [comment]
Hey @ashtonthomas : The `set` keyword defines `value` in `ValueNotifier` as a setter and not a regular method on the class. It's a convenience method that allows you to set the value of `value` on the class instance directly:

```dart
ValueNotifier<String> stringNotifier = new ValueNotifier<String>('initial String');
stringNotifier.value = 'new string';
```

This might explain it better: https://www.dartlang.org/resources/dart-tips/dart-tips-ep-10

**Comment by ashtonthomas** [comment]
Heh, and I decided to remove the disclaimer that I'm one week new to Dart... Sorry about the needless issue!

Thanks, @xqwzts.

**Comment by xqwzts** [comment]
We've all been there, good luck!

**Comment by jay23794** [comment]
ValueNotifier<List<VfmTopBarCardsModel>> topBarCardss = ValueNotifier<List<VfmTopBarCardsModel>>([]);
 how to set array list
