### ISSUE TITLE
Double scrolling in a screen

### ISSUE THREAD

**Issue by abbskhan** [flutter/flutter#154819]
### Steps to reproduce

i have a pageview.builder at top of the screen having 3 pages and then below it i have more content wrapped all in single child scroll view now when i scroll the screen it gives the issue

```
The following assertion was thrown while notifying listeners for AnimationController:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 158 pos 12: '_positions.length == 1'
```

### Expected results

the following error should not be displayed and i can scroll without any exception

### Actual results

when i scroll the screen it gives this issue
The following assertion was thrown while notifying listeners for AnimationController:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 158 pos 12: '_positions.length == 1'

### Code sample

// ignore_for_file: prefer_const_constructors

<details>
<summary> code </summary>

```

import 'package:dots_indicator/dots_indicator.dart';
import 'package:easy_date_timeline/easy_date_timeline.dart';
import 'package:easy_stepper/easy_stepper.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:noir_cinema/controllers/movieDetailController/movieDetailController.dart';
import 'package:noir_cinema/helpers/constants.dart';
import 'package:noir_cinema/menu/bottom_nav_bar.dart';
import 'package:noir_cinema/model/moviesDataModel/moviesDataModel.dart';
import 'package:noir_cinema/utils/app_colors.dart';
import 'package:noir_cinema/utils/customTextStyles.dart';
import 'package:noir_cinema/views/movieDetailScreen/widgets/highlightMovieTicketContainer.dart';
import 'package:noir_cinema/views/movieDetailScreen/widgets/movieTrailorContainer.dart';
import 'package:noir_cinema/views/seatsScreen/seatsScreen.dart';
import 'package:noir_cinema/views/upComingMovies/upComingMovies.dart';
import 'package:noir_cinema/views/whatsOnMoviesScreen/whatsOnMoviesScreen.dart';
import 'package:noir_cinema/widgets/customAppBar.dart';
import 'package:noir_cinema/widgets/customButton.dart';
import 'package:noir_cinema/widgets/customStrepper.dart';
import 'package:noir_cinema/widgets/headerAppBar.dart';
import 'package:noir_cinema/widgets/timeContainerWidget.dart';

import '../../assetsPath/assetsPath.dart';

class MovieDetailScreen extends StatefulWidget {
  Result? result;
  MovieDetailScreen({super.key, this.result});

  @override
  State<MovieDetailScreen> createState() => _MovieDetailScreenState();
}

class _MovieDetailScreenState extends State<MovieDetailScreen> with TickerProviderStateMixin {
  TabController? tabcontroller;
  MovieDetailController movieDetailController = Get.put(MovieDetailController());
  int activeStep = 1;

  @override
  void initState() {
    super.initState();
    activeStep = 1;

    tabcontroller = TabController(length: 2, vsync: this);
  }

  final List<String> cities = [
    'Riyadh',
    'Jeddah',
    'Dhahran',
  ];
  final List<String> seatingCatagory = [
    'Comfort',
    'Average',
    'Too Good',
  ];
  final times = ['10:00am', '12:00pm', '02:00pm'];

  @override
  Widget build(BuildContext context) {
    var height = MediaQuery.sizeOf(context).height;
    var width = MediaQuery.sizeOf(context).width;
    DateTime now = DateTime.now();
    DateTime startDate = DateTime(now.year - 10, now.month, now.day);
    List<DateTime> disabledDates = [];

    for (DateTime date = startDate; date.isBefore(now); date = date.add(Duration(days: 1))) {
      disabledDates.add(date);
    }

    return Scaffold(
        backgroundColor: AppColors.backGroundColor,
        body: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Stack(
                children: [
                  Container(
                    height: height * 0.520,
                    width: width,
                    child: PageView.builder(
                      allowImplicitScrolling: true,
                      itemCount: 3,
                      controller: movieDetailController.pageController,
                      onPageChanged: (int page) {
                        movieDetailController.currentPage.value = page;
                        movieDetailController.pageController.animateToPage(page,
                            duration: const Duration(milliseconds: 100), curve: Curves.easeInOut);
                      },
                      itemBuilder: (context, index) {
                        return MovieTrailorContainer(
                          height: height,
                          width: width,
                          result: widget.result,
                        );
                      },
                    ),
                  ),
                  Positioned(
                    bottom: 4,
                    left: 0,
                    right: 0,
                    child: Obx(() {
                      return DotsIndicator(
                        dotsCount: 3,
                        position: movieDetailController.currentPage.value,
                        decorator: DotsDecorator(
                          activeColor: AppColors.whiteColor,
                          color: AppColors.grey,
                          sizes: const [Size(60.0, 2.0), Size(60.0, 2.0), Size(60.0, 2.0)],
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(5.0),
                          ),
                          activeSize: const Size(60.0, 2.0),
                          activeShape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(5.0),
                          ),
                        ),
                      );
                    }),
                  )
                ],
              ),
              SizedBox(height: 27),
              Padding(
                padding: const EdgeInsets.only(left: 16, right: 16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    CustomStepper(activeStep: activeStep),
                    SizedBox(height: 20),
                    EasyDateTimeLine(
                      headerProps: EasyHeaderProps(showHeader: false),
                      initialDate: now,
                      disabledDates: disabledDates,
                      onDateChange: (selectedDate) {
                        print('Selected date: $selectedDate');
                      },
                      dayProps: EasyDayProps(
                        borderColor: AppColors.greylil,
                        dayStructure: DayStructure.monthDayNumDayStr,
                        activeDayStyle: DayStyle(
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.all(Radius.circular(8)),
                            color: AppColors.darkGrey,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(height: 25),
                    Text(
                      'Cinema Location',
                      style: CustomTextStyles.l14_MEDIUM_POPPINS_BLACK,
                    ),
                    SizedBox(height: 10),
                    Container(
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: AppColors.greylil)),
                      child: Theme(
                        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
                        child: ExpansionTile(
                          shape: InputBorder.none,
                          trailing: SvgPicture.asset('${Assets.iconsPath}${Assets.downSvg}'),
                          backgroundColor: AppColors.whiteColor,
                          title: Text(
                            'Al Qasr Mall - Riyadh',
                          ),
                          children: [
                            Column(
                              children: cities.map((city) {
                                return ListTile(
                                  title: Text(city),
                                  onTap: () {},
                                );
                              }).toList(),
                            ),
                          ],
                        ),
                      ),
                    ),
                    SizedBox(height: 25),
                    Text(
                      'Seating Catagory',
                      style: CustomTextStyles.l14_MEDIUM_POPPINS_BLACK,
                    ),
                    SizedBox(height: 10),
                    Container(
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: AppColors.greylil)),
                      child: Theme(
                        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
                        child: ExpansionTile(
                          shape: InputBorder.none,
                          trailing: SvgPicture.asset('${Assets.iconsPath}${Assets.downSvg}'),
                          backgroundColor: AppColors.whiteColor,
                          title: Text(
                            'Comfort',
                          ),
                          children: [
                            Column(
                              children: seatingCatagory.map((seats) {
                                return ListTile(
                                  title: Text(seats),
                                  onTap: () {},
                                );
                              }).toList(),
                            ),
                          ],
                        ),
                      ),
                    ),
                    SizedBox(height: 25),
                    Text(
                      'Show Time',
                      style: CustomTextStyles.l14_MEDIUM_POPPINS_BLACK,
                    ),
                    SizedBox(height: 10),
                    //time
                    Obx(() {
                      return Container(
                        padding: EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: AppColors.greylil),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: List.generate(3, (rowIndex) {
                            return Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Riyadh Refah Mall',
                                  style: CustomTextStyles.l14_MEDIUM_POPPINS_BLACK,
                                ),
                                SizedBox(height: 12),
                                Row(
                                  children: List.generate(times.length, (index) {
                                    return Padding(
                                      padding: EdgeInsets.symmetric(horizontal: 4),
                                      child: TimeContainer(
                                        time: times[index],
                                        isSelected:
                                            movieDetailController.selectedIndices[rowIndex] ==
                                                index,
                                        onTap: () {
                                          if (movieDetailController.selectedIndices[rowIndex] ==
                                              index) {
                                            movieDetailController.selectedIndices[rowIndex] = -1;
                                          } else {
                                            movieDetailController.selectedIndices[rowIndex] = index;
                                          }
                                        },
                                      ),
                                    );
                                  }),
                                ),
                                SizedBox(height: 13),
                              ],
                            );
                          }),
                        ),
                      );
                    }),

                    SizedBox(height: 34),
                    HighlightMovieTicketContainer(width: width),
                    SizedBox(height: 34),
                    Row(
                      children: [
                        CustomButton(
                          text: 'Next',
                          height: 44,
                          width: width / 2.5,
                          color: AppColors.darkLiver,
                          borderRadius: 12,
                          textStyle: CustomTextStyles.l12_MEDIUM_POPPINS_WHITE,
                          onPressed: () {
                            setState(() {
                              activeStep++;
                            });
                            CONSTANTS.navigateToScreen(
                                context, SeatsScreen(activeStep: activeStep));
                          },
                        ),
                      ],
                    )
                  ],
                ),
              ),
              SizedBox(height: 30),
            ],
          ),
        ),
        bottomNavigationBar: CustomBottomNavBar(currentIndex: 0));
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```

Performing hot reload...
Syncing files to device sdk gphone64 x86 64...
I/flutter (28439): 2024-09-04 00:00:00.000
I/flutter (28439): 2024-07-31 00:00:00.000
I/flutter (28439): 2024-07-03 00:00:00.000
I/flutter (28439): 2024-08-07 00:00:00.000
I/flutter (28439): 2024-07-31 00:00:00.000
I/flutter (28439): 2024-03-14 00:00:00.000
I/flutter (28439): active in payment :: 5
I/flutter (28439): active in adons  :: 4
I/flutter (28439): object
I/flutter (28439): object
I/flutter (28439): object
I/flutter (28439): object
I/flutter (28439): object
I/flutter (28439): object
I/flutter (28439): active in seats Screen :: 4
Reloaded 1 of 1843 libraries in 5,576ms (compile: 62 ms, reload: 2015 ms, reassemble: 3385 ms).
I/flutter (28439): Selected date: 2024-09-11 00:00:00.000
I/flutter (28439): Selected date: 2024-09-11 00:00:00.000
D/EGL_emulation(28439): app_time_stats: avg=1988.55ms min=9.22ms max=29569.25ms count=15
D/EGL_emulation(28439): app_time_stats: avg=36.91ms min=8.30ms max=425.39ms count=26
D/EGL_emulation(28439): app_time_stats: avg=39.69ms min=7.34ms max=870.37ms count=36
I/flutter (28439): Selected date: 2024-09-13 00:00:00.000
D/EGL_emulation(28439): app_time_stats: avg=3041.46ms min=8.42ms max=112019.50ms count=37
D/EGL_emulation(28439): app_time_stats: avg=2204.03ms min=4.71ms max=118542.56ms count=54
D/EGL_emulation(28439): app_time_stats: avg=24.56ms min=6.79ms max=505.71ms count=51
D/EGL_emulation(28439): app_time_stats: avg=215.53ms min=5.61ms max=2250.06ms count=11
D/EGL_emulation(28439): app_time_stats: avg=28.10ms min=10.11ms max=283.50ms count=35
D/EGL_emulation(28439): app_time_stats: avg=4156.93ms min=6.65ms max=115965.70ms count=28
D/EGL_emulation(28439): app_time_stats: avg=119.56ms min=6.97ms max=3790.64ms count=36
D/EGL_emulation(28439): app_time_stats: avg=23.49ms min=4.40ms max=312.58ms count=40
I/flutter (28439): object

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 158 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:158:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:191:41)
#4      _MovieDetailScreenState.build.<anonymous closure> (package:noir_cinema/views/movieDetailScreen/movieDetailScreen.dart:90:62)
#5      _PageViewState.build.<anonymous closure> (package:flutter/src/widgets/page_view.dart:915:34)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3403:18)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3406:13)
#9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3406:13)
#10     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:5077:24)
#11     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#12     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:104:92)
#13     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:1032:15)
#14     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:379:9)
#15     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:80:18)
#16     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:599:21)
#17     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:585:10)
#18     AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#19     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:908:5)
#20     Ticker._tick (package:flutter/src/scheduler/ticker.dart:261:12)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#22     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
#23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#24     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
#25     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
#26     _invoke1 (dart:ui/hooks.dart:328:13)
#27     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
#28     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)
The AnimationController notifying listeners was: AnimationController#89d21(▶ 226.326; for BallisticScrollActivity)
====================================================================================================
D/EGL_emulation(28439): app_time_stats: avg=40.30ms min=4.98ms max=597.08ms count=22

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 158 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:158:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:191:41)
#4      _MovieDetailScreenState.build.<anonymous closure> (package:noir_cinema/views/movieDetailScreen/movieDetailScreen.dart:90:62)
#5      _PageViewState.build.<anonymous closure> (package:flutter/src/widgets/page_view.dart:915:34)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3403:18)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3406:13)
#9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3406:13)
#10     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:5077:24)
#11     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#12     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:104:92)
#13     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:1032:15)
#14     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:379:9)
#15     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:80:18)
#16     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:599:21)
#17     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:585:10)
#18     AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#19     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:908:5)
#20     Ticker._tick (package:flutter/src/scheduler/ticker.dart:261:12)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#22     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
#23     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#24     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
#25     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
#26     _invoke1 (dart:ui/hooks.dart:328:13)
#27     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
#28     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)
The AnimationController notifying listeners was: AnimationController#df52a(▶ 620.887; for BallisticScrollActivity)
====================================================================================================
D/EGL_emulation(28439): app_time_stats: avg=10.30ms min=4.21ms max=54.65ms count=57
D/EGL_emulation(28439): app_time_stats: avg=13203.75ms min=4.89ms max=118786.23ms count=9
D/EGL_emulation(28439): app_time_stats: avg=71.26ms min=6.02ms max=1303.49ms count=22
D/EGL_emulation(28439): app_time_stats: avg=10830.65ms min=5.64ms max=151496.09ms count=14
D/EGL_emulation(28439): app_time_stats: avg=24.44ms min=7.15ms max=267.71ms count=36
D/EGL_emulation(28439): app_time_stats: avg=14.88ms min=5.99ms max=35.11ms count=53
D/EGL_emulation(28439): app_time_stats: avg=90.86ms min=11.86ms max=1155.56ms count=20
D/EGL_emulation(28439): app_time_stats: avg=15.74ms min=6.63ms max=159.67ms count=49
D/EGL_emulation(28439): app_time_stats: avg=19.73ms min=6.27ms max=189.74ms count=46


```

### Flutter Doctor output

 PS D:\abbas_projects\noir-cinema> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4112], locale en-PK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
PS D:\abbas_projects\noir-cinema>

**Comment by darshankawar** [comment]
@abbskhan 
The code you provided is not minimal and contains third party / custom implementation. In order to properly address the issue, try to narrow it down to only framework code and keep it minimal but completel which still triggers the reported error.
Also, when you open an issue, please try to format the code and logs so that it is readable.

Closing for now. You may raise this in support channels like StackOverflow.

**Comment by abbskhan** [comment]
> @abbskhan The code you provided is not minimal and contains third party / custom implementation. In order to properly address the issue, try to narrow it down to only framework code and keep it minimal but completel which still triggers the reported error. Also, when you open an issue, please try to format the code and logs so that it is readable.
> 
> Closing for now. You may raise this in support channels like StackOverflow.

I am sorry for not ordering the code properly as this was my first post on github thatwhy i didnt know how to post an issue properly

**Comment by darshankawar** [comment]
No problem. Try to use new issue [template](https://github.com/flutter/flutter/issues/new/choose) and fill out requested details.
