### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by deepak93275** [flutter/flutter#154901]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```console
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/tools/shader_compiler.dart:161:7)
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:221:46)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:187:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:1005:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:583:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:334:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.24.2 on channel stable at /Users/subashkumar/Documents/sdk/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4cf269e36d (6 days ago), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio 2.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.93.0)
    [32m•[39m VS Code at /Users/subashkumar/Desktop/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /Users/subashkumar/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /Users/subashkumar/Downloads/Visual Studio Code 2.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m VS Code (version 1.77.0)
    [32m•[39m VS Code at /Users/subashkumar/Downloads/Visual Studio Code 3.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m VS Code (version 1.77.0)
    [32m•[39m VS Code at /Users/subashkumar/Downloads/Visual Studio Code 4.app/Contents
    [32m•[39m Flutter extension version 3.96.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.120

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4cf269e36de2573851eaef3c763994f8f9be494d

**Comment by danagbemava-nc** [comment]
Hi @Sajalreef, does this issue persist on subsequent run(s) or only once? If you can reproduce it anytime, can you share the entire output of `flutter run -v`?
