### ISSUE TITLE
Ios app hangs on splash screen in release mode

### ISSUE THREAD

**Issue by hadi7khan** [flutter/flutter#154978]
### Steps to reproduce

I recently upgraded flutter to 3.24.2. Since then I am not able to run ios app in release mode. It is working fine in Android and ios debug mode. I tried everything - Deleting PodFile etc but nothing seems to work. It was working fine before.
I have captured logs when i try to run it on xcode: 

```
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 1065, TID: 113911
Backtrace
=================================================================
3   GPUToolsCore                        0x00000001071f85e0 _ZN8GPUTools9Interpose15DYInitInterposeEPFP16DYGuestAppClientvEi + 392
4   dyld                                0x00000001f258bbdc A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 27612
5   dyld                                0x00000001f25dad08 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 351496
6   dyld                                0x00000001f258a3d0 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 21456
7   dyld                                0x00000001f2589868 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 18536
8   dyld                                0x00000001f2588d7c A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 15740
9   dyld                                0x00000001f259394c A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 59724
10  dyld                                0x00000001f2590758 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 46936
11  dyld                                0x00000001f258d388 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 33672
12  dyld                                0x00000001f25920bc A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 53436
13  dyld                                0x00000001f25c1608 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 247304
14  dyld                                0x00000001f259a648 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 87624
15  dyld                                0x00000001f2598d88 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 81288
2024-09-11 12:19:28.728101+0530 ProgressCenter[1065:113911] Metal API Validation Enabled
2024-09-11 12:19:29.228009+0530 ProgressCenter[1065:113911] [IMPORTANT:flutter/shell/common/shell.cc(456)] [Action Required] The application opted out of Impeller by either using the --no-enable-impeller flag or FLTEnableImpeller=false plist flag. This option is going to go away in an upcoming Flutter release. Remove the explicit opt-out. If you need to opt-out, report a bug describing the issue.
2024-09-11 12:19:29.236352+0530 ProgressCenter[1065:113911] [IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(71)] Using the Skia rendering backend (Metal).
2024-09-11 12:19:29.344736+0530 ProgressCenter[1065:114290] [[GoogleUtilities/AppDelegateSwizzler]] 11.0.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
2024-09-11 12:19:29.434216+0530 ProgressCenter[1065:114305] flutter: The Dart VM service is listening on http://127.0.0.1:51800/6EPklw-Aa7Y=/
2024-09-11 12:19:31.453637+0530 ProgressCenter[1065:114294] fopen failed for data file: errno = 2 (No such file or directory)
2024-09-11 12:19:31.453754+0530 ProgressCenter[1065:114294] Errors found! Invalidating cache...
2024-09-11 12:19:31.694888+0530 ProgressCenter[1065:114290] [connection] nw_resolver_start_query_timer_block_invoke [C1.1] Query fired: did not receive all answers in time for firebaseinstallations.googleapis.com:443
2024-09-11 12:19:31.721609+0530 ProgressCenter[1065:114294] fopen failed for data file: errno = 2 (No such file or directory)
2024-09-11 12:19:31.721698+0530 ProgressCenter[1065:114294] Errors found! Invalidating cache...
2024-09-11 12:19:31.737892+0530 ProgressCenter[1065:114293] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      SharedPreferenceHelper.getUserToken (package:progresscenter_app_v4/src/core/shared_pref/shared_preference_helper.dart:85:21)
#1      DioInterceptor.onRequest (package:progresscenter_app_v4/src/core/network/interceptor/dio_interceptor.dart:19:66)
#2      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:387:17)
#3      new Future.<anonymous closure> (dart:async/future.dart:258:40)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
2024-09-11 12:19:31.949290+0530 ProgressCenter[1065:114281] [] nw_path_necp_check_for_updates Failed to copy updated result (22)
2024-09-11 12:19:31.965134+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C2.1] Query fired: did not receive all answers in time for device-provisioning.googleapis.com:443
2024-09-11 12:19:32.851209+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C3.1] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
2024-09-11 12:19:33.421945+0530 ProgressCenter[1065:114293] flutter: user granted permission
2024-09-11 12:19:33.434807+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C4] Query fired: did not receive all answers in time for firebaseinstallations.googleapis.com:443
2024-09-11 12:19:33.444089+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C5] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
2024-09-11 12:19:33.444757+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C6] Query fired: did not receive all answers in time for device-provisioning.googleapis.com:443
2024-09-11 12:19:33.956898+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C7.1] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
``` 

### Expected results

I want it to run as normally. App should not get stuck on splash screen.

### Actual results

App is getting stuck on splash screen. In ios release mode only. In debug mode it is working fine.

### Code sample

<details open><summary>Code sample</summary>

```dart
  @override
  void initState() {
    super.initState();

    // Method for calling to intialize notifications
    FirebaseApi().requestNotificationPermission();
    FirebaseApi().forgroundMessage();
    FirebaseApi().firebaseInit(context);
    FirebaseApi().setupInteractMessage(context);
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      ref.watch(fetchUserControllerProvider.notifier).fetchUser().then((value) {
        _prefsLocator.setPrimaryColor(color: value.preferences!.primaryColor!);
        _prefsLocator.saveUserModel(value);
        navigateInitialRoute();
      });
    });
  }
```
This is my initstate of splash screen. It was like that for half a year. No changes made to it.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 1065, TID: 113911
Backtrace
=================================================================
3   GPUToolsCore                        0x00000001071f85e0 _ZN8GPUTools9Interpose15DYInitInterposeEPFP16DYGuestAppClientvEi + 392
4   dyld                                0x00000001f258bbdc A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 27612
5   dyld                                0x00000001f25dad08 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 351496
6   dyld                                0x00000001f258a3d0 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 21456
7   dyld                                0x00000001f2589868 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 18536
8   dyld                                0x00000001f2588d7c A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 15740
9   dyld                                0x00000001f259394c A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 59724
10  dyld                                0x00000001f2590758 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 46936
11  dyld                                0x00000001f258d388 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 33672
12  dyld                                0x00000001f25920bc A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 53436
13  dyld                                0x00000001f25c1608 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 247304
14  dyld                                0x00000001f259a648 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 87624
15  dyld                                0x00000001f2598d88 A2AA3A68-07F7-3D52-A49E-D29D136813F3 + 81288
2024-09-11 12:19:28.728101+0530 ProgressCenter[1065:113911] Metal API Validation Enabled
2024-09-11 12:19:29.228009+0530 ProgressCenter[1065:113911] [IMPORTANT:flutter/shell/common/shell.cc(456)] [Action Required] The application opted out of Impeller by either using the --no-enable-impeller flag or FLTEnableImpeller=false plist flag. This option is going to go away in an upcoming Flutter release. Remove the explicit opt-out. If you need to opt-out, report a bug describing the issue.
2024-09-11 12:19:29.236352+0530 ProgressCenter[1065:113911] [IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(71)] Using the Skia rendering backend (Metal).
2024-09-11 12:19:29.344736+0530 ProgressCenter[1065:114290] [[GoogleUtilities/AppDelegateSwizzler]] 11.0.0 - [GoogleUtilities/AppDelegateSwizzler][I-SWZ001011] App Delegate Proxy is disabled.
2024-09-11 12:19:29.434216+0530 ProgressCenter[1065:114305] flutter: The Dart VM service is listening on http://127.0.0.1:51800/6EPklw-Aa7Y=/
2024-09-11 12:19:31.453637+0530 ProgressCenter[1065:114294] fopen failed for data file: errno = 2 (No such file or directory)
2024-09-11 12:19:31.453754+0530 ProgressCenter[1065:114294] Errors found! Invalidating cache...
2024-09-11 12:19:31.694888+0530 ProgressCenter[1065:114290] [connection] nw_resolver_start_query_timer_block_invoke [C1.1] Query fired: did not receive all answers in time for firebaseinstallations.googleapis.com:443
2024-09-11 12:19:31.721609+0530 ProgressCenter[1065:114294] fopen failed for data file: errno = 2 (No such file or directory)
2024-09-11 12:19:31.721698+0530 ProgressCenter[1065:114294] Errors found! Invalidating cache...
2024-09-11 12:19:31.737892+0530 ProgressCenter[1065:114293] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      SharedPreferenceHelper.getUserToken (package:progresscenter_app_v4/src/core/shared_pref/shared_preference_helper.dart:85:21)
#1      DioInterceptor.onRequest (package:progresscenter_app_v4/src/core/network/interceptor/dio_interceptor.dart:19:66)
#2      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:387:17)
#3      new Future.<anonymous closure> (dart:async/future.dart:258:40)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
2024-09-11 12:19:31.949290+0530 ProgressCenter[1065:114281] [] nw_path_necp_check_for_updates Failed to copy updated result (22)
2024-09-11 12:19:31.965134+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C2.1] Query fired: did not receive all answers in time for device-provisioning.googleapis.com:443
2024-09-11 12:19:32.851209+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C3.1] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
2024-09-11 12:19:33.421945+0530 ProgressCenter[1065:114293] flutter: user granted permission
2024-09-11 12:19:33.434807+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C4] Query fired: did not receive all answers in time for firebaseinstallations.googleapis.com:443
2024-09-11 12:19:33.444089+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C5] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
2024-09-11 12:19:33.444757+0530 ProgressCenter[1065:114286] [connection] nw_resolver_start_query_timer_block_invoke [C6] Query fired: did not receive all answers in time for device-provisioning.googleapis.com:443
2024-09-11 12:19:33.956898+0530 ProgressCenter[1065:114287] [connection] nw_resolver_start_query_timer_block_invoke [C7.1] Query fired: did not receive all answers in time for fcmtoken.googleapis.com:443
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.2 on channel stable at /Users/hadikhan/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (7 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/hadikhan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • Hadi’s iPhone (mobile)          • 05d93d9c6127a5d8810fc7a545da88ceb6682290 • ios            • iOS 16.1.1 20B101
    • macOS (desktop)                 • macos                                    • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @hadi7khan, your logs show that there's an error in your code. Can you try fixing it to see if you're able to start your application?

```
 2024-09-11 12:19:31.737892+0530 ProgressCenter[1065:114293] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      SharedPreferenceHelper.getUserToken (package:progresscenter_app_v4/src/core/shared_pref/shared_preference_helper.dart:85:21)
```

**Comment by hadi7khan** [comment]
@danagbemava-nc No this error has nothing to do with it. If it was so the error would prevent it from running in debug mode. or it would prevent Android app(debug and release mode) from running. Something is wrong with release mode only and it happened after I upgraded flutter to 3.24.2.
