### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by Code4Hacker** [flutter/flutter#154923]
## Command
```sh
flutter build apk --release  -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Operation not permitted, errno = 1
```console
#0      _checkForE rrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _Cus tomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
# 5      _File.readAsString (dart:io/file_impl.dart:621:18)
<asynchronous suspension>
#6      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:53:24)
<asynchronous suspens ion>
#7      findPlugins (package:flutter_tools/src/flutter_plugins.dart:96:28)
<asynchronous suspension>
#8      injectBuildTimePluginFiles (package:flutter_tools/src/flutter_plugins.dart% 3A1053:32)
<asynchronous suspension>
#9      WebProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:989:5)
<asynchronous suspension>
#10     FlutterProject .ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:396:7)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flu tter_command.dart:1750:7)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension >
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[31m[☠][39m Flut ter (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github .com/flutter/flutter/issues.
    [31m✗[39m Error: Flutter failed to read a file at "/Users/gemini/Documents/flutter/bin/cache/dart-sdk/bin/resources/devtools/version.json".% 0A      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
      Try running:
        sudo chown -R $(whoami) /Users/gemini/Documents /flutter/bin/cache/dart-sdk/bin/resources/devtools/version.json

    [32m•[39m #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _t hrowFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:844:3)
      #2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:774:3)
       #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:610:7)
      #4      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:229:12% 29
      #5      Cache.devToolsVersion (package:flutter_tools/src/cache.dart:393:51)
      #6      _DefaultDoctorValidatorsProvider.validators.<anonymous closure> (package:flutter_tools/src/doc tor.dart:135:46)
      #7      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:555:84)
      #8      Doctor.startValidatorTasks.<anon

**Comment by darshankawar** [comment]
> ```
> �[31m✗�[39m Error: Flutter failed to read a file at "/Users/gemini/Documents/flutter/bin/cache/dart-sdk/bin/resources/devtools/version.json".% 0A      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
>       Try running:
>         sudo chown -R $(whoami) /Users/gemini/Documents /flutter/bin/cache/dart-sdk/bin/resources/devtools/version.json
> ```

@Code4Hacker Try as suggested to see if it helps or not.
The issue is as mentioned by the tool:

`Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user`
