### ISSUE TITLE
MediaCodecDecoderInitializationException video codec error

### ISSUE THREAD

**Issue by ibrahimEltayfe** [flutter/flutter#155077]
### Steps to reproduce

When using imagePicker package or the device's screen recorder or anything the uses the device codec, the video player reports an error and hasError becomes true, an errorDescription says Decoder init failed.

1. setup video player
2. add image picker package, then open the picker
3. return back to the app, you will see error in video player

### Expected results

Video should play correctly without errors.

### Actual results

VideoPlayer fail with DecoderInitializationException

### Code sample

<details open><summary>Code sample</summary>

```dart
class VideoPlayerIssue extends StatefulWidget {
  const VideoPlayerIssue({super.key});

  @override
  State<VideoPlayerIssue> createState() => _VideoPlayerIssueState();
}

class _VideoPlayerIssueState extends State<VideoPlayerIssue> {
  final VideoPlayerController videoPlayerController = VideoPlayerController.networkUrl(
    Uri.parse("https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4")
  );

  bool hasError = false;

  @override
  void initState() {
    videoPlayerController.initialize().whenComplete(() {
      videoPlayerController.play();
      videoPlayerController.setLooping(true);
    },);

    videoPlayerController.addListener(() {
      if(videoPlayerController.value.hasError){
        print(videoPlayerController.value.errorDescription);
        setState(() {
          hasError = true;
        });
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    videoPlayerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            SizedBox(
              height: 200,
              child: Stack(
                children: [
                  VideoPlayer(videoPlayerController),

                  if(hasError)
                  Positioned.fill(
                    child: Container(
                      color: Colors.black26,
                      alignment: Alignment.center,
                      child: const Text("Error", style: TextStyle(color: Colors.white, fontSize: 20),),
                    ),
                  )
                ],
              )
            ),

            const SizedBox(height: 16,),

            GestureDetector(
              onTap: (){
                ImagePicker().pickImage(source: ImageSource.gallery);
              },
              child: const Text("Pick image"),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

With image picker

https://github.com/user-attachments/assets/b7e8e4ac-68a0-46ac-adc1-311c1c08b65f

With the device screen recorder

https://github.com/user-attachments/assets/c988f72f-b6fd-44df-a420-66b6d4420b84

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/MediaCodecVideoRenderer(25896): Video codec error
E/MediaCodecVideoRenderer(25896):   androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder, Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.975233, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])

E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/MediaCodecVideoRenderer(25896):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/MediaCodecVideoRenderer(25896):       at android.os.Looper.loopOnce(Looper.java:257)
E/MediaCodecVideoRenderer(25896):       at android.os.Looper.loop(Looper.java:368)
E/MediaCodecVideoRenderer(25896):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/MediaCodecVideoRenderer(25896):   Caused by: java.lang.IllegalArgumentException: 
E/MediaCodecVideoRenderer(25896):       at android.media.MediaCodec.native_configure(Native Method)
E/MediaCodecVideoRenderer(25896):       at android.media.MediaCodec.configure(MediaCodec.java:2332)
E/MediaCodecVideoRenderer(25896):       at android.media.MediaCodec.configure(MediaCodec.java:2248)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:173)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
E/MediaCodecVideoRenderer(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
E/MediaCodecVideoRenderer(25896):       ... 12 more
D/MediaCodec(25896): [0xb400007ca4866800] [c2.mtk.avc.decoder] kWhatReleaseCompleted
D/MediaCodec(25896): [0xb400007ca4866800] setState: 0
I/hw-BpHwBinder(25896): onLastStrongRef automatically unlinking death recipients
D/MediaCodec(25896): flushMediametrics
E/ExoPlayerImplInternal(25896): Playback error
E/ExoPlayerImplInternal(25896):   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.975233, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(25896):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(25896):       at android.os.Looper.loopOnce(Looper.java:257)
E/ExoPlayerImplInternal(25896):       at android.os.Looper.loop(Looper.java:368)
E/ExoPlayerImplInternal(25896):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25896):   Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.mtk.avc.decoder, Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.975233, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
E/ExoPlayerImplInternal(25896):       ... 4 more
E/ExoPlayerImplInternal(25896):   Caused by: java.lang.IllegalArgumentException: 
E/ExoPlayerImplInternal(25896):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(25896):       at android.media.MediaCodec.configure(MediaCodec.java:2332)
E/ExoPlayerImplInternal(25896):       at android.media.MediaCodec.configure(MediaCodec.java:2248)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:173)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
E/ExoPlayerImplInternal(25896):       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
E/ExoPlayerImplInternal(25896):       ... 12 more
D/MediaCodec(25896): [0xb400007ca4866800] ~MediaCodec
D/MediaCodec(25896): flushMediametrics
W/MediaCodec(25896): no metrics handle found
D/OplusCCodec(25896): ~OplusCCodec [303]: (0xb400007c903cbe00)
D/OplusFeedbackInfo(25896): ~OplusAnalysisFPS
I/flutter (25896): Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.975233, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.1.2 23B92 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
This seems to be fundamental ExoPlayer issue (https://github.com/google/ExoPlayer/issues/8473, https://github.com/google/ExoPlayer/issues/10526, and more with this [filter](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+DecoderInitializationException+Video+codec+error+is%3Aopen+)). 

I'm not sure if there is any action from Flutter for this, can you share how it affects your implementation code? Does it rely on `hasError`?

**Comment by ibrahimEltayfe** [comment]
> This seems to be fundamental ExoPlayer issue ([google/ExoPlayer#8473](https://github.com/google/ExoPlayer/issues/8473), [google/ExoPlayer#10526](https://github.com/google/ExoPlayer/issues/10526), and more with this [filter](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+DecoderInitializationException+Video+codec+error+is%3Aopen+)).
> 
> I'm not sure if there is any action from Flutter for this, can you share how it affects your implementation code? Does it rely on `hasError`?

Hi, thank you for your reply.
In my implementation, I rely on the hasError property to manage playback errors and show a retry button to users if an error occurs.

```
 void _videoPlayerListener(){
    if(videoController.hasError){
      //logic to show retry button..
    }
  }
```

**Comment by huycozy** [comment]
I see `hasError` can work for this case as it's true when the issue occurs so you can rely on it. But I think the underlying issue comes from ExoPlayer, so the error persists even if you retry many times afterward. 

>Video player had error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.975233, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES

This looks similar to https://github.com/flutter/flutter/issues/81804. I see there are many reports there. I will close this in favor of that one to concentrate on one issue. You can also add your case there which may help to investigate the issue further, thanks!
