### ISSUE TITLE
[flutter_markdown] RangeError with a particular Markdown input

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#155020]
### What package does this bug report belong to?

flutter_markdown

### What target platforms are you seeing this bug on?

Android, iOS, Web, macOS, Linux, Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

flutter_markdown version 0.7.3+1

### Steps to reproduce

Go to the example in the repository and use the following markdown input in one of the markdown inputs

```
![Image](
<>
![Image](
<>
``` 

### Expected results

No crash

### Actual results

Crashes

### Code sample

<details open><summary>Code sample</summary>

Example app in the package repository

</details>

### Logs

<details open><summary>Logs</summary>

```console
[+1862 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following RangeError was thrown building MinimalMarkdownDemo:
                    RangeError (length): Invalid value: Not in inclusive range 0..24: 25
                    
                    The relevant error-causing widget was:
                      MinimalMarkdownDemo
                      MinimalMarkdownDemo:file:///home/david/data_ssd/Dev/Flutter/flutter_packages/packages/flutter_markdown/example/lib/screens/home_screen.dart:26:11
                    
                    When the exception was thrown, this was the stack:
                    #0      _StringBase.codeUnitAt (dart:core-patch/string_patch.dart)
                    #1      InlineParser.charAt (package:markdown/src/inline_parser.dart:324:35)
                    #2      LinkSyntax._parseInlineBracketedLink (package:markdown/src/inline_syntaxes/link_syntax.dart:305:25)
                    #3      LinkSyntax._parseInlineLink (package:markdown/src/inline_syntaxes/link_syntax.dart:263:14)
                    #4      LinkSyntax.close (package:markdown/src/inline_syntaxes/link_syntax.dart:63:26)
                    #5      InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:150:32)
                    #6      InlineParser.parse (package:markdown/src/inline_parser.dart:106:9)
                    #7      Document.parseInline (package:markdown/src/document.dart:94:67)
                    #8      Document._parseInlineContent (package:markdown/src/document.dart:100:29)
                    #9      Document._parseInlineContent (package:markdown/src/document.dart:105:9)
                    #10     Document.parseLineList (package:markdown/src/document.dart:88:5)
                    #11     Document.parseLines (package:markdown/src/document.dart:80:7)
                    #12     _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:384:45)
                    #13     _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:348:5)
                    #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5636:11)
                    #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463:5)
                    ...     Normal element mounting (71 frames)
                    #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
                    #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3849:18)
                    #88     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:860:37)
                    #89     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:845:20)
                    #90     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:19)
                    #91     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:837:12)
                    #92     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:360:23)
                    #93     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688:59)
                    #94     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
                    #95     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688:14)
                    #96     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:5)
                    #97     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:435:5)
                    #98     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:315:12)
                    #99     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #100    RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:121:12)
                    #101    _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:158:11)
                    #102    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #103    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
                    #104    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
                    #105    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
                    #106    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #108    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #110    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #112    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #114    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #116    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #118    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #119    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
                    #120    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
                    #121    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
                    #122    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
                    #123    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #125    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #127    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426:11)
                    #128    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #130    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #131    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #132    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #133    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #134    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #136    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #137    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #138    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #139    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #140    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #142    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #144    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #146    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #147    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3710:14)
                    #148    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:21)
                    #150    RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
                    #151    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974:13)
                    #152    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288:9)
                    #153    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
                    #154    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
                    #155    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
                    #156    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
                    #157    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
                    #158    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
                    #159    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
                    #160    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
                    #161    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
                    #162    _invoke (dart:ui/hooks.dart:312:13)
                    #163    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
                    #164    _drawFrame (dart:ui/hooks.dart:283:31)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on Fedora Linux 39 (Workstation Edition) 6.10.8-100.fc39.x86_64, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/david/.puro/envs/3.24.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on latest versions.

```
Stable : 3.24.2
Master: 3.26.0-1.0.pre.72
```

<details>
<summary> runnable code </summary>

```


import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:markdown/markdown.dart' as md;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: MarkdownBody(
              data:
              '![Image](<>![Image](<>',
           //   selectable: true
          )
      ),
    );
  }
}

class B2BlockSyntax extends md.BlockSyntax {
  static const String _pattern = r'^\[\[warning\]\](.*)$';
  @override
  RegExp get pattern => RegExp(_pattern);

  B2BlockSyntax();

  @override
  md.Node parse(md.BlockParser parser) {
    var childLines = parseChildLines(parser);

    var content = childLines.join('\n');

    final md.Element el = md.Element('p', [
      md.Element('warning', [md.Text(content)]),
    ]);

    return el;
  }

}

class WarningBuilder extends MarkdownElementBuilder {
  @override
  Widget visitElementAfter(md.Element element, TextStyle? preferredStyle) {
    return Builder(builder: (context) {

      return Container(
        width: double.infinity,
        margin: const EdgeInsets.symmetric(vertical: 15),
        padding: EdgeInsets.all(10),
        decoration: BoxDecoration(
          color: Colors.white,
          border: Border(left: BorderSide(color: Colors.red, width: 2)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: EdgeInsets.only(bottom: 10),
              child: const Text('Warning !', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
            Text(element.textContent, style: preferredStyle),
          ],
        ),
      );
    });
  }
}

```

</details>

**Comment by andrechalella** [comment]
I fixed this in `markdown` with PR https://github.com/dart-lang/markdown/pull/624.
