### ISSUE TITLE
Widget not rendering

### ISSUE THREAD

**Issue by rishabhmishra208** [flutter/flutter#155158]
### Steps to reproduce

1. Logout the app
2. And reload 
        return MaterialApp.router(
          locale: Locale(localeCode),
          debugShowCheckedModeBanner: false,
          routerDelegate: Modular.routerDelegate,
          supportedLocales: Constants.localizationCodes,
          routeInformationParser: Modular.routeInformationParser,
          theme: ThemeData(
            primarySwatch: Colors.purple,
            fontFamily: mainFontFamily,
            useMaterial3: false,
            highlightColor: Colors.transparent,
            hoverColor: Colors.transparent,
            splashColor: Colors.transparent,
          ),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          builder: (context, child) {
            return ScrollConfiguration(
              behavior: MyBehavior(),
              child: child ?? const SizedBox.shrink(),
            );
          },
        );
        
3. Is not rendering
          builder: (context, child) {
            return ScrollConfiguration(
              behavior: MyBehavior(),
              child: child ?? const SizedBox.shrink(),
            );
          },

### Expected results

It should be render the ui

### Actual results

It's throw ui rendering error

### Code sample

<details open><summary>Code sample</summary>

```dart
Observer(
      builder: (context) {
        var localeCode = authService.localeCode ?? 'en';

        return MaterialApp.router(
          locale: Locale(localeCode),
          debugShowCheckedModeBanner: false,
          routerDelegate: Modular.routerDelegate,
          supportedLocales: Constants.localizationCodes,
          routeInformationParser: Modular.routeInformationParser,
          theme: ThemeData(
            primarySwatch: Colors.purple,
            fontFamily: mainFontFamily,
            useMaterial3: false,
            highlightColor: Colors.transparent,
            hoverColor: Colors.transparent,
            splashColor: Colors.transparent,
          ),
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          builder: (context, child) {
            return ScrollConfiguration(
              behavior: MyBehavior(),
              child: child ?? const SizedBox.shrink(),
            );
          },
        );
      },
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![flutter_01](https://github.com/user-attachments/assets/4b6ec57a-856b-40a5-abae-0c140fdfc38b)

### Logs

<details open><summary>Logs</summary>

```console

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2116 pos 12:
'_elements.contains(element)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  ScrollConfiguration
  ScrollConfiguration:file:///D:/Live%20Project/OnePlay-App/oneplay-flutter-gui/lib/TV_App/tv_widget.dart:58:20

When the exception was thrown, this was the stack:
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:2116:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:4397:30)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4440:35)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3957:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#12     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#16     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#21     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#45     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#49     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#53     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#73     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#75     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#79     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#92     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#96     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#100    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#105    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#107    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#113    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#114    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#117    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#119    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#127    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#128    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#139    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#140    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#145    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#150    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#154    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#157    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#159    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#165    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#166    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#169    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#170    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#171    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#174    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#176    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#180    StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#186    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#187    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#190    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#192    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#195    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#197    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#201    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#205    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#208    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#209    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#210    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#214    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#215    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#217    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#218    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#219    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#220    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#223    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#228    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#229    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#231    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#232    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#233    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#235    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#239    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#240    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#243    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#244    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#245    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#249    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#253    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#258    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#262    StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#264    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#266    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#267    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#268    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#269    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#270    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#271    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#272    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#273    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
#274    PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#278    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4112], locale en-IN)
    • Flutter version 3.24.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (10 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.93.0)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (5 available)
    • AFTKA (mobile)     • 192.168.1.2:5555 • android-arm    • Android 9 (API 28)
    • IMTM4000R (mobile) • 192.168.1.4:5555 • android-arm    • Android 11 (API 30)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.4112]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 128.0.6613.137
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 128.0.2739.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@rishabhmishra208 
Please try to format the code properly so that it is readable. 
Also, provide us [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without third party package implementation that still shows the reported error.
