### ISSUE TITLE
 Context null in  MaterialLocalizations.of(context) (package:flutter/src/material/material_localizations.dart:684)

### ISSUE THREAD

**Issue by assemblyios** [flutter/flutter#155337]
### Steps to reproduce

The   iPhone14pro(17.4.1 System version)   occasionally displays an abnormal  Tabbar
Not all iOS devices will show up
Android devices were not found to have this problem

```dart
static MaterialLocalizations of(BuildContext context) {
    assert(debugCheckHasMaterialLocalizations(context));
    return Localizations.of<MaterialLocalizations>(context, MaterialLocalizations)!;
  }
```

This API returns null

Two similar issues premised on this
https://github.com/flutter/flutter/issues/152979
https://github.com/flutter/flutter/issues/101292

Our solution is to let the user reinstall the APP, which is likely to avoid repetition

Full stacktrace

```
# Null check operator used on a null value

#0 MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:684)
#1 _TabBarState.build (package:ylcstudent/kffa/widgets/custom_tabbar.dart:1323)
#2 StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#3 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#4 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#5 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#6 StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#7 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#8 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#9 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#10 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#11 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#12 StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#13 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#14 Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#15 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#16 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#18 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#19 ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#20 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#21 Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#22 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#23 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#25 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#26 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#27 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#28 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#29 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#30 StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#31 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#32 Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#33 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#34 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#35 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#36 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#37 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#38 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#40 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#41 StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#42 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#43 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#44 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#45 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#46 StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#47 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#48 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#49 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#50 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#51 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#52 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#53 Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#54 StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#55 Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#56 _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:298)
#57 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#58 _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:296)
#59 _RenderSliverPersistentHeaderForWidgetsMixin.updateChild (package:flutter/src/widgets/sliver_persistent_header.dart:382)
#60 RenderSliverPersistentHeader.layoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_persistent_header.dart:223)
#61 RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#62 PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#63 RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#64 RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:221)
#65 RenderSliverPinnedPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:417)
#66 RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#67 RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
#68 RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554)
#69 RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463)
#70 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#71 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#72 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#73 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#74 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#75 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#76 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#77 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#78 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#79 _rootRun (dart:async/zone.dart:1399)
#80 _CustomZone.run (dart:async/zone.dart:1301)
#81 _CustomZone.runGuarded (dart:async/zone.dart:1209)
#82 _invoke (dart:ui/hooks.dart:314)
#83 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#84 _drawFrame (dart:ui/hooks.dart:283)
```

### Expected results

The   iPhone14pro(17.4.1 System version)   occasionally displays an normal  Tabbar

### Actual results

The   iPhone14pro(17.4.1 System version)   occasionally displays an abnormal  Tabbar

### Code sample

<details open><summary>Code sample</summary>

```dart
class HomeApp extends StatelessWidget {
  const HomeApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: const [
        // 这行是关键
        RefreshLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('zh', 'CN'),
      ],
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          title: Text('Test'),
          bottom:
              TabBar(tabs: ['tab1', 'tab2'].map((e) => Tab(text: e)).toList()),
        ),
        body: Column(
          children: [TextField()],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at
      /Users/edy/Documents/3.16.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/edy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/edy/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • iPhoneXs (mobile) • 00008020-000270543A83002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 14.1.1 23B81
      darwin-arm64
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome
      128.0.6613.138

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @assemblyios, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.3) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by assemblyios** [comment]
> Hi @assemblyios, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.3) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`.
> 
> Thank you

Okay, I'll upgrade 3.24.3 first

**Comment by assemblyios** [comment]
> Hi @assemblyios, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.24.3) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`.
> 
> Thank you

We upgraded to the latest 3.24.3 and still have problems

This time it is the DialogRoute that has problems

flutter doctor -v

[✓] Flutter (Channel stable, 3.24.3, on macOS 14.1.1 23B81 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.24.3 on channel stable at
      /Users/edy/Documents/3.24.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (12 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/edy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/edy/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhoneXs (mobile)               • 00008020-000270543A83002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.58

[✓] Network resources
    • All expected network resources are available.

Full stacktrace

# Null check operator used on a null value


0
#0 MaterialLocalizations.of (package:flutter/src/material/material_localizations.dart:691)
1
#1 new DialogRoute (package:flutter/src/material/dialog.dart:1582)
2
#2 showDialog (package:flutter/src/material/dialog.dart:1431)
3
#3 showCenterDialog (package:ylcstudent/dialog/custom_dialog.dart:927)
4
#4 _SettingPageState.build.<anonymous closure> (package:ylcstudent/page/user/setting/setting_page.dart:186)
5
#5 WidgetExt.inkWell.<anonymous closure> (package:kfextension/widget_extension.dart:25)
6
#6 _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
7
#7 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
8
#8 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
9
#9 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
10
#10 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246)
11
#11 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703)
12
#12 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
13
#13 PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
14
#14 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
15
#15 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
16
#16 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
17
#17 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:501)
18
#18 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
19
#19 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
20
#20 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
21
#21 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
22
#22 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
23
#23 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
24
#24 _rootRunUnary (dart:async/zone.dart:1415)
25
#25 _CustomZone.runUnary (dart:async/zone.dart:1308)
26
#26 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
27
#27 _invoke1 (dart:ui/hooks.dart:330)
28
#28 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
29
#29 _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

**Comment by danagbemava-nc** [comment]
Hi @assemblyios, thanks for the update. Can you provide a sample .arb file that we can use? Also, does the `TabBar` still render incorrectly? Is there any specific step we need to take with the code sample you provided initially to reproduce the issue?

**Comment by assemblyios** [comment]
Thanks, the tabbar still displays abnormally, we can use the code originally provided, but it may not be repeated. We only have an error on iphone14pro (17.4.1 System version), and it is accidental. There is a certain probability that the uninstallation and reinstallation of the app will be normal. If you want to reproduce, please run the corresponding iphone14pro (17.4.1 System version) repeatedly to see if it can appear
TabBar and DialogRoute both display rendering error because MaterialLocalizations.of(context) returns null error

**Comment by assemblyios** [comment]
> Hi @assemblyios, thanks for the update. Can you provide a sample .arb file that we can use? Also, does the `TabBar` still render incorrectly? Is there any specific step we need to take with the code sample you provided initially to reproduce the issue?

Thanks, the tabbar still displays abnormally, we can use the code originally provided, but it may not be repeated. We only have an error on iphone14pro (17.4.1 System version), and it is accidental. There is a certain probability that the uninstallation and reinstallation of the app will be normal. If you want to reproduce, please run the corresponding iphone14pro (17.4.1 System version) repeatedly to see if it can appear,
TabBar and DialogRoute both display rendering error because MaterialLocalizations.of(context) returns null error

**Comment by assemblyios** [comment]
> > Hi @assemblyios, thanks for the update. Can you provide a sample .arb file that we can use? Also, does the `TabBar` still render incorrectly? Is there any specific step we need to take with the code sample you provided initially to reproduce the issue?
> 
> Thanks, the tabbar still displays abnormally, we can use the code originally provided, but it may not be repeated. We only have an error on iphone14pro (17.4.1 System version), and it is accidental. There is a certain probability that the uninstallation and reinstallation of the app will be normal. If you want to reproduce, please run the corresponding iphone14pro (17.4.1 System version) repeatedly to see if it can appear, TabBar and DialogRoute both display rendering error because MaterialLocalizations.of(context) returns null error

![Pasted Graphic](https://github.com/user-attachments/assets/8c86d34e-4eac-4f74-942b-0bbaa1dacae9)
![image](https://github.com/user-attachments/assets/7f70be4c-b8d1-4d7d-b78d-aeecbf1a0128)
This is where the flutter SDK source code goes wrong

**Comment by danagbemava-nc** [comment]
Hi @assemblyios, can you share a screenshot of the abnormal view of the `TabBar`?

**Comment by danagbemava-nc** [comment]
Thanks for the update. 

@assemblyios, one more thing. Kindly share the `RefreshLocalizations` file and how you generated that file. 

Thank you

**Comment by assemblyios** [comment]
> Thanks for the update.
> 
> @assemblyios, one more thing. Kindly share the `RefreshLocalizations` file and how you generated that file.
> 
> Thank you

![image](https://github.com/user-attachments/assets/27c991cc-9e23-40fd-9503-ff33641755ca)


It is a third-party library, please import it
File in pubspec.yaml 
pull_to_refresh: 2.0.0

**Comment by danagbemava-nc** [comment]
Hi @assemblyios, do you still experience this issue if you don't use the pull_to_refresh library and its `RefreshLocalizations`?

**Comment by assemblyios** [comment]
> Hi @assemblyios, do you still experience this issue if you don't use the pull_to_refresh library and its `RefreshLocalizations`?
Hello, I have the same problem with this library without using pull_to_refresh

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation as I cannot reproduce this locally with the sample provided above. We have seen several instances of this as reported in the initial post.

**Comment by assemblyios** [comment]
> Labeling this for further investigation as I cannot reproduce this locally with the sample provided above. We have seen several instances of this as reported in the initial post.

OK, I hope this problem can be solved soon. Thank you

**Comment by lihehehehe** [comment]
> > 将此标记为进一步调查，因为我无法使用上面提供的示例在本地重现此情况。我们已经看到了几个这样的实例，如最初的帖子中所报告的那样。
> 
> 好的，希望这个问题能尽快解决。谢谢

同样的偶问题，但是目前看线上日志之出现在澳门地区，国内其他地区并没有上报此异常。配置代码如下：

localizationsDelegates: const [
            RefreshLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],

supportedLocales: const [
            Locale('en'),
            Locale('zh'),
          ],

localeResolutionCallback: (
            Locale? locale,
            Iterable<Locale> supportedLocales,
          ) {
            return locale;
          },

**Comment by lihehehehe** [comment]
> > 将此标记为进一步调查，因为我无法使用上面提供的示例在本地重现此情况。我们已经看到了几个这样的实例，如最初的帖子中所报告的那样。
> 
> 好的，希望这个问题能尽快解决。谢谢

同样的问题，但是目前看线上日志之出现在澳门地区，国内其他地区并没有上报此异常。配置代码如下：

localizationsDelegates: const [
RefreshLocalizations.delegate,
GlobalMaterialLocalizations.delegate,
GlobalWidgetsLocalizations.delegate,
GlobalCupertinoLocalizations.delegate,
],

supportedLocales: const [
Locale('en'),
Locale('zh'),
],

localeResolutionCallback: (
Locale? locale,
Iterable supportedLocales,
) {
return locale;
},

请问有找到解决方案吗？

**Comment by assemblyios** [comment]
> > > 将此标记为进一步调查，因为我无法使用上面提供的示例在本地重现此情况。我们已经看到了几个这样的实例，如最初的帖子中所报告的那样。
> > 
> > 
> > 好的，希望这个问题能尽快解决。谢谢
> 
> 同样的问题，但是目前看线上日志之出现在澳门地区，国内其他地区并没有上报此异常。配置代码如下：
> 
> localizationsDelegates: const [ RefreshLocalizations.delegate, GlobalMaterialLocalizations.delegate, GlobalWidgetsLocalizations.delegate, GlobalCupertinoLocalizations.delegate, ],
> 
> supportedLocales: const [ Locale('en'), Locale('zh'), ],
> 
> localeResolutionCallback: ( Locale? locale, Iterable supportedLocales, ) { return locale; },
> 
> 请问有找到解决方案吗？

找不到啊，官方一直不解决，蛋疼的很
