### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by dwikyhardi** [flutter/flutter#155394]
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008120-############## --start-paused --flavor=development --dart-define=flutter.inspector.structuredErrors=true lib/main_development.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 15.0 24A335 darwin-arm64, locale en-ID)
    • Flutter version 3.24.0 on channel stable at /Users/dwiky/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dwiky/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.0

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Dwikyhardi’s iPhone (mobile)    • 00008120-############## • ios          • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64 • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin       • macOS 15.0 24A335 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+7
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
app_settings-5.1.1
cloud_firestore-5.2.1
cloud_firestore_web-4.1.1
connectivity_plus-6.0.5
device_info_plus-10.1.2
file_picker-8.1.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-11.2.1
firebase_analytics_web-0.5.9+1
firebase_app_installations-0.3.0+4
firebase_app_installations_web-0.1.5+12
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_crashlytics-4.0.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
firebase_remote_config-5.0.4
firebase_remote_config_web-1.6.12
flutter_image_cropper_plus-0.0.1
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.21
image_picker-1.1.2
image_picker_android-0.8.12+12
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
intercom_flutter-9.0.8
intercom_flutter_web-1.1.1
local_auth-2.3.0
local_auth_android-1.0.43
local_auth_darwin-1.4.0
local_auth_windows-1.0.11
mobile_scanner-41a0d4fa33c216666271834cc4dfb8b1e8e1be49
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
sentry_flutter-8.7.0
sqflite-2.3.3+1
syncfusion_flutter_pdfviewer-26.2.9
syncfusion_pdfviewer_macos-26.2.9
syncfusion_pdfviewer_web-26.2.9
syncfusion_pdfviewer_windows-26.2.9
url_launcher-6.3.0
url_launcher_android-6.3.9
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.8.0
webview_flutter_android-3.16.6
webview_flutter_wkwebview-3.14.0

**Comment by dwikyhardi** [comment]
fixed this by adding this into PodFile

```Pod
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
```

and Change the `Allow Non-modular Includes in Framework Modules` to `YES` in Xcode `Build Setting`
