### ISSUE TITLE
Clearer error message for crash when mixing 64 and 32 bit code on Android

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15530]
According to @jason-simmons, on 64-bit Android devices, Flutter will automatically build with 64-bit native code but it's possible to bring in other 32-bit JNI code via gradle. Launching an app built this way would crash on launch.

```
03-14 12:49:37.531  4779  4779 D AndroidRuntime: Shutting down VM
03-14 12:49:37.531  4779  4779 E AndroidRuntime: FATAL EXCEPTION: main
03-14 12:49:37.531  4779  4779 E AndroidRuntime: Process: com.hamilton.app, PID: 4779
03-14 12:49:37.531  4779  4779 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hamilton.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.hamilton.app-2/lib/arm, /data/app/com.hamilton.app-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1567)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:163)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:148)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at com.hamilton.app.App.onCreate(App.kt:16)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
03-14 12:49:37.531  4779  4779 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
``` 

If possible, detect and adapt automatically while building. 

The current solution according to Jason is to build on the command-line and switch everything to 32-bit by building with something like `flutter run --target-platform android-arm`.

cc @devoncarew since this workaround doesn't seem to be available in IntelliJ.

**Comment by igorwojda** [comment]
duplicated by https://github.com/flutter/flutter/issues/15733

**Comment by PieterAelse** [comment]
What's the currently excepted workaround? If i do `ndk { abiFilters "armeabi-v7a" }`, the resulting release APK won't install on my emulator. If I don't do it, the app will crash (couldn't find libflutter.so) on my Pixel 2.

Should 2 APK's be made? (32bit and 64bit)

**Comment by AdamBCo** [comment]
Any update on this? I'm having the same issue.

**Comment by Kiruel** [comment]
I think you can check this. @AdamBCo #18494

**Comment by kw2019ltd** [comment]
![image](https://user-images.githubusercontent.com/47334522/81492997-4a2ddc00-92a5-11ea-9c1b-7fe21ecf047d.png)
