### ISSUE TITLE
gn flake: //build/mac/find_sdk.py

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#155309]
This was seen blocking the skia roller.

## instance
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1164527/overview

## log
```
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/ci/android_release_arm64
ERROR at //build/config/mac/mac_sdk.gni:41:7: Script returned non-zero exit code.
      exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
      ^----------
Current dir: /Volumes/Work/s/w/ir/cache/builder/src/out/ci/android_release_arm64/
Command: vpython3 /Volumes/Work/s/w/ir/cache/builder/src/build/mac/find_sdk.py --symlink /Volumes/Work/s/w/ir/cache/builder/src/flutter/prebuilts --print_sdk_path 10.14
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/build/mac/find_sdk.py", line 135, in <module>
    sys.exit((main()))
  File "/Volumes/Work/s/w/ir/cache/builder/src/build/mac/find_sdk.py", line 97, in main
    sdk_json_output = run_command_with_retry(sdk_command, timeout=300)
  File "/Volumes/Work/s/w/ir/cache/builder/src/build/mac/find_sdk.py", line 49, in run_command_with_retry
    result = subprocess.check_output(command, timeout=timeout)
  File "/Users/chrome-bot/Library/Caches/.vpython-root/store/cpython+pvkc65g756tssn1rh3h5u9e3lg/contents/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/chrome-bot/Library/Caches/.vpython-root/store/cpython+pvkc65g756tssn1rh3h5u9e3lg/contents/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/chrome-bot/Library/Caches/.vpython-root/store/cpython+pvkc65g756tssn1rh3h5u9e3lg/contents/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/chrome-bot/Library/Caches/.vpython-root/store/cpython+pvkc65g756tssn1rh3h5u9e3lg/contents/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/Users/chrome-bot/Library/Caches/.vpython-root/store/cpython+pvkc65g756tssn1rh3h5u9e3lg/contents/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['xcodebuild', '-showsdks', '-json']' timed out after 300 seconds

See //build/toolchain/mac/BUILD.gn:8:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //build/compiled_action.gni:122:14: which caused the file to be included.
    deps = [ host_tool ]
             ^--------
```

**Comment by gaaclarke** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/155106
