### ISSUE TITLE
Task :flutter_inappwebview:syncReleaseLibJars FAILED

### ISSUE THREAD

**Issue by Alihassan20** [flutter/flutter#155396]
### Steps to reproduce

I face this error and I haven't found any solution

after upgrading Flutter to the latest version this appears in release mode but in debug mode, it runs correctly

and iam using   flutter_inappwebview: ^5.8.0 with cannot use last version of flutter_inappwebview because tabby_flutter_inapp_sdk: ^1.4.2 depend on tabby_flutter_inapp_sdk ^5.8.0  or less 

** it happen in android version not ios 

### Expected results

run in release mode as debug mode to upload it 

### Actual results

FAILURE: Build failed with an exception.

    What went wrong:
    A problem was found with the configuration of task ':flutter_inappwebview:syncReleaseLibJars' (type 'LibraryAarJarsTask').

        In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file 'myPth/build/flutter_inappwebview/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview.jar' which doesn't exist.

        Reason: An input file was expected to be present but it doesn't exist.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Code sample</summary>

```dart

[        ] Transforming versionedparcelable-1.1.1.aar (androidx.versionedparcelable:versionedparcelable:1.1.1) with ExtractAarTransform
[        ] Transforming versionedparcelable-1.1.1.aar (androidx.versionedparcelable:versionedparcelable:1.1.1) with AarResourcesCompilerTransform
[        ] Transforming core-runtime-2.2.0.aar (androidx.arch.core:core-runtime:2.2.0) with JetifyTransform
[        ] Transforming core-runtime-2.2.0.aar (androidx.arch.core:core-runtime:2.2.0) with ExtractAarTransform
[        ] Transforming core-runtime-2.2.0.aar (androidx.arch.core:core-runtime:2.2.0) with AarResourcesCompilerTransform
[        ] Caching disabled for task ':flutter_downloader:verifyReleaseResources' because:
[        ]   Build cache is disabled
[        ] Skipping task ':flutter_downloader:verifyReleaseResources' as it is up-to-date.
[        ] Resolve mutations for :app:packageRelease (Thread[Execution worker Thread 2,5,main]) started.
[        ] :app:packageRelease (Thread[Execution worker Thread 2,5,main]) started.
[        ] Resolve mutations for :flutter_downloader:assembleRelease (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_downloader:assembleRelease (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_downloader:assembleRelease UP-TO-DATE
[        ] Skipping task ':flutter_downloader:assembleRelease' as it has no actions.
[        ] Resolve mutations for :flutter_inappwebview:stripReleaseDebugSymbols (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:stripReleaseDebugSymbols (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_inappwebview:stripReleaseDebugSymbols NO-SOURCE
[        ] Skipping task ':flutter_inappwebview:stripReleaseDebugSymbols' as it has no source files and no previous output files.
[        ] Resolve mutations for :flutter_inappwebview:copyReleaseJniLibsProjectAndLocalJars (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:copyReleaseJniLibsProjectAndLocalJars (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_inappwebview:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:copyReleaseJniLibsProjectAndLocalJars' because:
[        ]   Build cache is disabled
[        ]   Caching has been disabled for the task
[        ] Skipping task ':flutter_inappwebview:copyReleaseJniLibsProjectAndLocalJars' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:extractDeepLinksForAarRelease (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:extractDeepLinksForAarRelease (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_inappwebview:extractDeepLinksForAarRelease UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:extractDeepLinksForAarRelease' because:
[        ]   Build cache is disabled
[        ] Skipping task ':flutter_inappwebview:extractDeepLinksForAarRelease' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:extractReleaseAnnotations (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:extractReleaseAnnotations (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_inappwebview:extractReleaseAnnotations UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:extractReleaseAnnotations' because:
[        ]   Build cache is disabled
[        ] Skipping task ':flutter_inappwebview:extractReleaseAnnotations' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:mergeReleaseGeneratedProguardFiles (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:mergeReleaseGeneratedProguardFiles (Thread[Execution worker Thread 6,5,main]) started.
[        ] > Task :flutter_inappwebview:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:mergeReleaseGeneratedProguardFiles' because:
[        ]   Build cache is disabled
[        ]   Simple merging task
[        ] Skipping task ':flutter_inappwebview:mergeReleaseGeneratedProguardFiles' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:mergeReleaseConsumerProguardFiles (Thread[Execution worker Thread 6,5,main]) started.
[        ] :flutter_inappwebview:mergeReleaseConsumerProguardFiles (Thread[Execution worker,5,main]) started.
[        ] > Task :flutter_inappwebview:mergeReleaseConsumerProguardFiles UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:mergeReleaseConsumerProguardFiles' because:
[        ]   Build cache is disabled
[        ]   Simple merging task
[        ] Skipping task ':flutter_inappwebview:mergeReleaseConsumerProguardFiles' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:prepareLintJarForPublish (Thread[Execution worker,5,main]) started.
[        ] :flutter_inappwebview:prepareLintJarForPublish (Thread[Execution worker,5,main]) started.
[        ] > Task :flutter_inappwebview:prepareLintJarForPublish UP-TO-DATE
[        ] Caching disabled for task ':flutter_inappwebview:prepareLintJarForPublish' because:
[        ]   Build cache is disabled
[        ]   Caching has been disabled for the task
[        ] Skipping task ':flutter_inappwebview:prepareLintJarForPublish' as it is up-to-date.
[        ] Resolve mutations for :flutter_inappwebview:syncReleaseLibJars (Thread[Execution worker,5,main]) started.
[        ] :flutter_inappwebview:syncReleaseLibJars (Thread[Execution worker,5,main]) started.
[        ] > Task :flutter_inappwebview:syncReleaseLibJars FAILED
[+1932 ms] > Task :app:packageRelease
[        ] Custom actions are attached to task ':app:packageRelease'.
[        ] Caching disabled for task ':app:packageRelease' because:
[        ]   Build cache is disabled
[        ]   Caching has been disabled for the task
[        ] Task ':app:packageRelease' is not up-to-date because:
[        ]   Input property 'allClasspathInputFiles' file /Users/mackbook/KUN ACADEMY/build/app/intermediates/stripped_native_libs/release/stripReleaseDebugSymbols/out/lib/armeabi-v7a/libapp.so has been removed.
[        ]   Input property 'allClasspathInputFiles' file /Users/mackbook/KUN ACADEMY/build/app/intermediates/stripped_native_libs/release/stripReleaseDebugSymbols/out/lib/armeabi-v7a/libc++_shared.so has been added.
[        ]   Input property 'allClasspathInputFiles' file /Users/mackbook/KUN ACADEMY/build/app/intermediates/stripped_native_libs/release/stripReleaseDebugSymbols/out/lib/armeabi-v7a/libc++_shared.so has been removed.
[        ]   and more...
[        ] The input changes require a full rebuild for incremental task ':app:packageRelease'.
[ +500 ms] Resolve mutations for :app:createReleaseApkListingFileRedirect (Thread[Execution worker,5,main]) started.
[        ] :app:createReleaseApkListingFileRedirect (Thread[Execution worker,5,main]) started.
[        ] > Task :app:createReleaseApkListingFileRedirect UP-TO-DATE
[        ] Caching disabled for task ':app:createReleaseApkListingFileRedirect' because:
[        ]   Build cache is disabled
[        ]   Caching has been disabled for the task
[        ] Skipping task ':app:createReleaseApkListingFileRedirect' as it is up-to-date.
[ +198 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] A problem was found with the configuration of task ':flutter_inappwebview:syncReleaseLibJars' (type 'LibraryAarJarsTask').
[        ]   - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file '/Users/mackbook/KUN
ACADEMY/build/flutter_inappwebview/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview.jar' which doesn't exist.
[        ]     Reason: An input file was expected to be present but it doesn't exist.
[        ]     Possible solutions:
[        ]       1. Make sure the file exists before the task is called.
[        ]       2. Make sure that the task which produces the file is declared as an input.
[        ]     For more information, please refer to https://docs.gradle.org/8.10.1/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] > Get more help at https://help.gradle.org.
[        ] * Exception is:
[        ] org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':flutter_inappwebview:syncReleaseLibJars' (type 'LibraryAarJarsTask').
[        ]   - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file '/Users/mackbook/KUN
ACADEMY/build/flutter_inappwebview/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview.jar' which doesn't exist.
[        ]     Reason: An input file was expected to be present but it doesn't exist.
[        ]     Possible solutions:
[        ]       1. Make sure the file exists before the task is called.
[        ]       2. Make sure that the task which produces the file is declared as an input.
[        ]     For more information, please refer to https://docs.gradle.org/8.10.1/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.
[        ]      at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.build(WorkValidationException.java:137)
[        ]      at org.gradle.internal.execution.WorkValidationException$BuilderWithSummary.get(WorkValidationException.java:119)
[        ]      at org.gradle.internal.execution.steps.ValidateStep.throwValidationException(ValidateStep.java:174)
[        ]      at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:99)
[        ]      at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:56)
[        ]      at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:64)
[        ]      at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:43)
[        ]      at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:125)
[        ]      at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:56)
[        ]      at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:36)
[        ]      at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
[        ]      at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
[   +2 ms]      at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
[        ]      at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
[        ]      at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
[        ]      at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
[        ]      at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:289)
[        ]      at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
[        ]      at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
[   +2 ms]      at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
[        ]      at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
[        ]      at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
[        ]      at java.base/java.util.Optional.orElseGet(Optional.java:364)
[        ]      at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
[        ]      at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
[        ]      at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
[        ]      at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
[   +9 ms]      at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:48)
[        ]      at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:35)
[        ]      at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:61)
[        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:127)
[        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
[        ]      at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[        ]      at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[  +39 ms]      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[        ]      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
[        ]      at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
[   +9 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[        ]      at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[  +11 ms]      at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
[        ]      at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:85)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
[        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
[   +4 ms]      at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
[        ]      at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
[        ]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[        ]      at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[        ]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[        ]      at java.base/java.lang.Thread.run(Thread.java:842)
[        ] BUILD FAILED in 31s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[   +3 ms] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[        ] 1098 actionable tasks: 33 executed, 1065 up-to-date
[   +6 ms] Watched directory hierarchies: [/Users/mackbook/development/flutter/packages/flutter_tools/gradle, /Users/mackbook/KUN ACADEMY/android]
[ +166 ms] Running Gradle task 'assembleRelease'... (completed in 32.0s)
[  +77 ms] Error: Gradle task assembleRelease failed with exit code 1
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:498:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:223:5)
           <asynchronous suspension>
           #3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:583:7)
           <asynchronous suspension>
           #4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:533:33)
           <asynchronous suspension>
           #5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:55:28)
           <asynchronous suspension>
           #6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:833:27)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #15     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
[  +17 ms] "flutter run" took 50,901ms.
[  +63 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:840:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +257 ms] ensureAnalyticsSent: 252ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[  +49 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.6.7 22G720 darwin-x64, locale en-AE)
    • Flutter version 3.22.2 on channel stable at /Users/mackbook/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mackbook/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Users/mackbook/Downloads/Xcode 4.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Connected device (3 available)
    • SM A245F (mobile) • RZ8W501B7SE • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 13.6.7 22G720 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 126.0.6478.182
    ! Error: Browsing on the local area network for iPhone kun. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@Alihassan20 
The error is pointing to `flutter_inappwebview` which is third party package. Try to upgrade your dependencies to latest versions and re-run your scenario to check. Else also try upgrading your gradle version.

**Comment by Alihassan20** [comment]
after updating flutter_inappwebview to last version 6.0.0
and my gradel is distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip

Still have this Error 

FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] A problem was found with the configuration of task ':flutter_inappwebview_android:syncReleaseLibJars' (type 'LibraryAarJarsTask').
[        ]   - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.LibraryAarJarsTask' property 'javaResourcesJar' specifies file '/mypath/build/flutter_inappwebview_android/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview_android.jar' which doesn't exist.

after upgrade flutter with dart 


this file doesn't exist.

**Comment by darshankawar** [comment]
> '/mypath/build/flutter_inappwebview_android/intermediates/merged_java_res/release/minifyReleaseWithR8/feature-flutter_inappwebview_android.jar' which doesn't exist.

I think you will need to report this in dedicated repo, as the path points to the plugin.

**Comment by Alihassan20** [comment]
ok I found the solution, it is the Gradle version 
thanks

**Comment by nikorehnback** [comment]
@Alihassan20 care to share what change you needed to do here to get it working?

**Comment by Alihassan20** [comment]
step one : 
in android/gradle/wrapper/gradle-wrapper.properties add this line to upgrade gradle
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip

step two : 
in android/app/build.gradle
add this lines 
        compileSdkVersion 34
        minSdkVersion 23
        targetSdkVersion 34
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17

    }
    kotlinOptions {
        jvmTarget=17
    }

**Comment by yeisa231189** [comment]
Unsubscribe

**Comment by darshankawar** [comment]
Closing as resolved.
