### ISSUE TITLE
"FlutterApplicationInfo.flutterAssetsDir' on a null object reference" from FlutterApplication class

### ISSUE THREAD

**Issue by andrew-pillyze** [flutter/flutter#155443]
### Steps to reproduce

This happens very rarely, and it seems like FlutterApplicationInfo is accessed when it wasn't loaded properly.

### Expected results

This should always load properly. 

### Actual results

Sometimes it couldn't find resource. (30times in DAU 30K)

### Code sample

<details open><summary>Code sample</summary>

```dart
class MainApplication : FlutterApplication() {
    override fun onCreate() {
        super.onCreate()
        AirbridgeFlutter.init(this, "sample app name", "sample api key") // HERE
    }
}


class AirbridgeFlutter: FlutterPlugin {
    companion object {
        @JvmStatic
        fun init(application: Application, appName: String, appToken: String) {
            Airbridge.init(
                app = application,
                config = AirbridgeConfig
                    .Builder(appName, appToken)
                    .setFromAirbridgeJSON(application) // HERE
                    .setOnAttributionResultReceiveListener{
                        AttributionAPI.attributionTracker.provideResult(it)
                    }
                    .setPlatform("flutter")
                    .build()
            )
        }
...
...


fun AirbridgeConfig.Builder.setFromAirbridgeJSON(context: Context): AirbridgeConfig.Builder {
    val loader = FlutterInjector.instance().flutterLoader()
    val json = loader.loadJsonAsset("assets/airbridge.json", context) // HERE, It couldn't find the "airbridge.json" 
...
...

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

Caused by java.lang.NullPointerException
Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(java.lang.String)'

          Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(java.lang.String)'
       at io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(FlutterLoader.java:495)
       at io.flutter.embedding.engine.loader.FlutterLoader.getLookupKeyForAsset(FlutterLoader.java:470)
       at co.ab180.airbridge.flutter.utility.FlutterUtilityKt.loadJsonAsset(FlutterUtility.kt:10)
       at co.ab180.airbridge.flutter.utility.AirbridgeConfigUtilityKt.setFromAirbridgeJSON(AirbridgeConfigUtility.kt:10)
       at co.ab180.airbridge.flutter.AirbridgeFlutter$Companion.init(AirbridgeFlutter.kt:18)
       at com.pillyze.health.MainApplication.onCreate(MainApplication.kt:9)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4 23E214 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by andrew-pillyze** [comment]
It seems to me that the initialization is sometimes delayed. I wonder if the FlutterLoad initialization is guaranteed to be done in Application class.

**Comment by darshankawar** [comment]
@andrew-pillyze 
Can you provide us a complete reproducible code sample (or a sample repo) that we can clone directly to verify this further ?
