### ISSUE TITLE
[Integration Test] [Web] flutter driver crashing on linux with chrome driver on docker

### ISSUE THREAD

**Issue by desmond206x** [flutter/flutter#155406]
### Steps to reproduce

Setup the code in the example section.
Install chrome and chrome-driver in the version 129.0.6668.58.

Start the chrome web driver 129.0.6668.58 with the command:
`chromedriver --port=4444`

Start the integration test with the command:
`flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart -d web-server --browser-name=chrome --driver-port=4444 --web-port=8888 --headless --web-run-headless --profile --web-browser-flag="--no-sandbox"`

I think some command parts could be deleted but I don't have the time to check this currently.
I didn't test if it is the same error without docker.

### Expected results

Succesfully test run.

### Actual results

```
root@66ac1faae6ee:/opt/integration_test_demo# /opt/flutter/master/bin/flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart -d web-server --browser-name=chrome --driver-port=4444 --web-port=8888 --headless --web-run-headless --profile --web-browser-flag="--no-sandbox"
Resolving dependencies...
Downloading packages...
  flutter_lints 3.0.2 (4.0.0 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
Got dependencies!
3 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching integration_test/integration_test.dart on Web Server in profile mode...
Compiling integration_test/integration_test.dart for the Web...        40.3s
✓ Built build/web
integration_test/integration_test.dart is being served at http://localhost:8888
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices
for an improved development workflow.
Unhandled exception:
DriverError: Driver extension has not been initialized correctly.
If the test uses a custom VM service extension, make sure it conforms to the protocol used by package:integration_test and package:flutter_driver.
If the test uses VM service extensions provided by the Flutter SDK, then this error is likely caused by a bug in Flutter. Please report it by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
Original error: UnknownException (500): unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=129.0.6668.58)
Original stack trace:
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cCoreHandler.parseExecuteResponse (package:webdriver/src/handler/w3c/core.dart:59:19)
#2      WebDriver.execute.<anonymous closure> (package:webdriver/src/async/web_driver.dart:260:37)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      FlutterWebConnection.sendCommand (package:flutter_driver/src/driver/web_driver.dart:304:7)
<asynchronous suspension>
#5      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:123:14)
<asynchronous suspension>
#6      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:547:39)
<asynchronous suspension>
#7      integrationDriver (package:integration_test/integration_test_driver.dart:74:29)
<asynchronous suspension>


#0      FlutterWebConnection.sendCommand (package:flutter_driver/src/driver/web_driver.dart:306:7)
<asynchronous suspension>
#1      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:123:14)
<asynchronous suspension>
#2      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:547:39)
<asynchronous suspension>
#3      integrationDriver (package:integration_test/integration_test_driver.dart:74:29)
<asynchronous suspension>
Application finished.
```

### Code sample

<details open><summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Please fix flutter web'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const TextField(),
    );
  }
}

```
</details>

<details open><summary>integration_test.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:integration_test_demo/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets(
    'example',
    (tester) async {
      app.main();
      await tester.pumpAndSettle();

      tester.testTextInput.register();

      await tester.tap(find.byType(EditableText));
      await tester.pumpAndSettle();

      await tester.enterText(find.byType(EditableText), 'text');
      await tester.pumpAndSettle();

      expect(find.text('text'), findsOneWidget, reason: 'Can not find text field text');

      await Future.delayed(const Duration(seconds: 10));

      tester.testTextInput.unregister();
    },
  );
}
```
</details>

<details open><summary>flutter_driver.dart</summary>

```dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() async => integrationDriver();

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[!] Flutter (Channel master, 3.26.0-1.0.pre.161, on Ubuntu 24.04.1 LTS 5.15.0-113-generic, locale en_US)
    • Flutter version 3.26.0-1.0.pre.161 on channel master at /opt/flutter/master
    ! The flutter binary is not on your path. Consider adding /opt/flutter/master/bin to your path.
    ! The dart binary is not on your path. Consider adding /opt/flutter/master/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 568ed33da9 (4 hours ago), 2024-09-19 06:03:32 -0400
    • Engine revision 1d889dd5ac
    • Dart version 3.6.0 (build 3.6.0-266.0.dev)
    • DevTools version 2.40.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android/sdk/
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from
      https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from
      https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 5.15.0-113-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.58

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
> Original error: UnknownException (500): unknown error: session deleted because of page crash
> from unknown error: cannot determine loading status
> from tab crashed

@desmond206x Probably it is related to chromeDriver. See https://stackoverflow.com/a/76563366 to check if it helps in your case or not.

**Comment by desmond206x** [comment]
@darshankawar 
No. I saw this comment on stackoverflow before, but it is not related to this bug.
The chrome and chromedriver are both of version 129.0.6668.58 (newest).

**Comment by desmond206x** [comment]
Can someone explain me why the test isn't starting if I run the command with --debug instead of --profile on linux docker?

**Comment by darshankawar** [comment]
> DriverError: Error while executing FlutterDriver result for command: window.$flutterDriver('{"command":"request_data","timeout":"1200000"}')

I think you are hitting a timeout issue, as reported here as well : https://github.com/flutter/flutter/issues/155019

Can you try the command only with `headless` and `no-sandbox` flags and remove other unwanted params ?

**Comment by desmond206x** [comment]
flutter drive without -d web-server changes the test run to -d chrome. I don't think this makes any sense.

Without the web-server parameter the chrome won't start, because I can't use flutter drive with --no-sandbox.

```
/opt/flutter/3.24.3/bin/flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart --headless --web-browser-flag="--no-sandbox"
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Connected devices:
Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 5.15.0-113-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 129.0.6668.58
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 2
Launching integration_test/integration_test.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.1s
[CHROME]:[11570:11570:0923/102551.001185:ERROR:zygote_host_impl_linux.cc(101)] Running as root without --no-sandbox is
not supported. See https://crbug.com/638180.
Failed to launch browser after 3 tries. Command used to launch it: /opt/google/chrome/google-chrome
--user-data-dir=/tmp/flutter_tools.IACWOF/flutter_tools_chrome_device.IGVWVT --remote-debugging-port=46455
--disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run
--no-default-browser-check --disable-default-apps --disable-translate http://localhost:45065
Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server
instead and filing an issue at https://github.com/flutter/flutter/issues.
```

**Comment by darshankawar** [comment]
> command only with `headless` and `no-sandbox` flags and remove other unwanted params

I meant without unwanted flags, but not removing the ones that are mandatory to make the command run. Anyways, I will keep the issue open for team's attention.

**Comment by desmond206x** [comment]
Sorry, i am just a little but frustrated about the current integration test situation for flutter web.
I had multiple problems with this topic tha past two weeks and tried so many ways to get our integration test running on windows & linux, headless & non-headless and if possible in the profile mode. 
Non-Headless had other problems with duplicate runs while using the "-d chrome" parameter. https://github.com/flutter/flutter/issues/67090#issuecomment-2348397670

So back to this issue here. 
Here is the output for the minimum parameter set
```
/opt/flutter/3.24.3/bin/flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart -d web-server --headless --web-browser-flag="--no-sandbox" --profile
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching integration_test/integration_test.dart on Web Server in profile mode...
Compiling integration_test/integration_test.dart for the Web...        38.2s
✓ Built build/web
integration_test/integration_test.dart is being served at http://localhost:41357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices
for an improved development workflow.
Unhandled exception:
DriverError: Driver extension has not been initialized correctly.
If the test uses a custom VM service extension, make sure it conforms to the protocol used by package:integration_test and package:flutter_driver.
If the test uses VM service extensions provided by the Flutter SDK, then this error is likely caused by a bug in Flutter. Please report it by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
Original error: UnknownException (500): unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=129.0.6668.58)
Original stack trace:
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cCoreHandler.parseExecuteResponse (package:webdriver/src/handler/w3c/core.dart:59:19)
#2      WebDriver.execute.<anonymous closure> (package:webdriver/src/async/web_driver.dart:260:37)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      FlutterWebConnection.sendCommand (package:flutter_driver/src/driver/web_driver.dart:304:7)
<asynchronous suspension>
#5      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:123:14)
<asynchronous suspension>
#6      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:540:39)
<asynchronous suspension>
#7      integrationDriver (package:integration_test/integration_test_driver.dart:74:29)
<asynchronous suspension>


#0      FlutterWebConnection.sendCommand (package:flutter_driver/src/driver/web_driver.dart:306:7)
<asynchronous suspension>
#1      WebFlutterDriver.sendCommand (package:flutter_driver/src/driver/web_driver.dart:123:14)
<asynchronous suspension>
#2      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:540:39)
<asynchronous suspension>
#3      integrationDriver (package:integration_test/integration_test_driver.dart:74:29)
<asynchronous suspension>
Application finished.
```

I also have a --verbose log of the chrome driver:
https://pastebin.com/ts8p44yb

____

Without the --profile flag the test will start in --debug mode which did not throws an exception but runs forever. 
The chromedriver log just repeats this part:
```
[1727099592.975][DEBUG]: DevTools WebSocket Command: Page.getFrameTree (id=423) (session_id=C13155B2F38444EA3EE0A2847F0F1ADF) 26798BF08C836BBC413BEEB3FD060B00 {
}
[1727099592.976][DEBUG]: DevTools WebSocket Response: Page.getFrameTree (id=423) (session_id=C13155B2F38444EA3EE0A2847F0F1ADF) 26798BF08C836BBC413BEEB3FD060B00 {
   "frameTree": {
      "frame": {
         "adFrameStatus": {
            "adFrameType": "none"
         },
         "crossOriginIsolatedContextType": "NotIsolated",
         "domainAndRegistry": "",
         "gatedAPIFeatures": [  ],
         "id": "26798BF08C836BBC413BEEB3FD060B00",
         "loaderId": "CFBD9F588B3490403505214FC6DE0FBF",
         "mimeType": "text/html",
         "secureContextType": "SecureLocalhost",
         "securityOrigin": "http://localhost:38239",
         "url": "http://localhost:38239/"
      }
   }
}
[1727099592.977][DEBUG]: DevTools WebSocket Command: Runtime.callFunctionOn (id=424) (session_id=C13155B2F38444EA3EE0A2847F0F1ADF) 26798BF08C836BBC413BEEB3FD060B00 {
   "arguments": [  ],
   "awaitPromise": true,
   "functionDeclaration": "function(){ return (function() { // Copyright 2012 The Chromium Authors\n// Use of this source code is governed by a BSD-style license that can be\n// found in the LICENSE file.\n\n/**\n * Enum for WebD...",
   "serializationOptions": {
      "serialization": "deep"
   },
   "uniqueContextId": "3701111945452156229.-1624557425831652051"
}
```

The --release does the same as above with --profile.

**Comment by desmond206x** [comment]
I got it running with Firefox. Maybe this helps others or the devs to identify the error in the chrome driver.

Start geckodriver
`/opt/firefox/geckodriver --binary=/opt/firefox/firefox/firefox`

Start flutter integration test with firefox in **debug** mode:
```
root@66ac1faae6ee:/opt/integration_test_demo# /opt/flutter/3.24.3/bin/flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart -d web-server --browser-name=firefox
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching integration_test/integration_test.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         20.0s
integration_test/integration_test.dart is being served at http://localhost:36009
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices
for an improved development workflow.
All tests passed.
Application finished.
```

Start flutter integration test with firefox in **profile** mode:
```
root@66ac1faae6ee:/opt/integration_test_demo# /opt/flutter/3.24.3/bin/flutter drive --driver=test_driver/test_driver.dart --target=integration_test/integration_test.dart -d web-server --browser-name=firefox --profile
Resolving dependencies...
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 3.0.0 (4.0.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
Got dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching integration_test/integration_test.dart on Web Server in profile mode...
Compiling integration_test/integration_test.dart for the Web...        45.5s
✓ Built build/web
integration_test/integration_test.dart is being served at http://localhost:35971
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices
for an improved development workflow.
All tests passed.
Application finished.
```

**Comment by ditman** [comment]
The flutter driver error seems to suggest that the page under test crashed, and in the [verbose log](https://pastebin.com/ts8p44yb) you can see a fairly normal flutter initialization (there's even some font downloading going on).

The only "error" I see right before the crash, seems to be related to the GPU "stalling":

```
[13004:13004:0923/134854.545306:ERROR:gl_utils.cc(426)] [.RendererMainThread-0x1484012ce200]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
```

Here's a couple of things to try:

* Is your Docker container being started with GPU support?
  * I'm not sure how to enable this in your specific infra, but gitlab has some [docs that may help](https://docs.gitlab.com/runner/configuration/gpus.html).
* Is there any way you can launch your container and interactively run the test that you're trying to `flutter drive`, with `flutter run`, that might let you see what's going on more directly (in the JS console, whether the page crashes or not, etc...)

**Comment by desmond206x** [comment]
> * Is your Docker container being started with GPU support?

No it isn't. I can't test it with GPU support.

> * Is there any way you can launch your container and interactively run the test that you're trying to `flutter drive`, with `flutter run`, that might let you see what's going on more directly (in the JS console, whether the page crashes or not, etc...)

The mini test app runs without any errors in the JS console.

**Comment by yjbanov** [comment]
Technically, Flutter Web does not require a real GPU, but it does require a working WebGL implementation. It's OK if it is CPU-emulated (e.g. via SwiftShader), but it must be fully functional. I'm not sure there's an action we can take on the Flutter side to fix this. The issue seems to be in the configuration of the Docker environment.
