### ISSUE TITLE
Wasm Error: ref.eq's left argument should be a subtype of eqref

### ISSUE THREAD

**Issue by BirjuVachhani** [flutter/flutter#155442]
### Steps to reproduce

I wish I could but I couldn't create a minimal reproducible example of this. I am running following command to compile my app to wasm.

```
flutter build web --wasm
```

I was able to run with wasm using following command but then it crashes at runtime with error: `ref.eq[0] expected either eqref or (ref null shared eq), found i32.const of type i32 @+20305914`.

```
flutter run -d chrome --wasm
```

### Expected results

The project should compile just fine and run without any errors.

### Actual results

Wasm compilation Crashes with following logs in console.

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
Error: Wasm compilation failed while optimizing output
[wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
[wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get (local.get $3)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
($4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const 0)
0)
0)
0)
0)
Fatal: error validating input
  Command: /Users/birjuvachhani/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/birjuvachhani/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false
  -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/36335019a8eab588c3c2ea783c618d90505be233/
  --extra-compiler-option=--depfile=/Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efa
  ac59f5b3d3830b6371088b0e/dart2wasm.d -O4 --strip-wasm --extra-compiler-option=--no-source-maps -o
  /Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efaac59f5b3d3830b6371088b0e/main.dart
  .wasm
  /Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efaac59f5b3d3830b6371088b0e/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:334:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             98.7s
Error: Failed to compile application for the Web.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
Error: Wasm compilation failed while optimizing output
[wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
[wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get (local.get $3)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
($4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const [wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on 
(local.get $4)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on 
(i32.const 0)
0)
0)
0)
0)
Fatal: error validating input
  Command: /Users/birjuvachhani/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/birjuvachhani/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false
  -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/36335019a8eab588c3c2ea783c618d90505be233/
  --extra-compiler-option=--depfile=/Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efa
  ac59f5b3d3830b6371088b0e/dart2wasm.d -O4 --strip-wasm --extra-compiler-option=--no-source-maps -o
  /Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efaac59f5b3d3830b6371088b0e/main.dart
  .wasm
  /Users/birjuvachhani/Documents/Projects/Codelessly/codelessly/.dart_tool/flutter_build/2b928efaac59f5b3d3830b6371088b0e/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:334:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             98.7s
Error: Failed to compile application for the Web.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/birjuvachhani/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/birjuvachhani/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/birjuvachhani/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/birjuvachhani/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.2.2)
    • IntelliJ at /Users/birjuvachhani/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • Birju’s iPhone (mobile)         • 00008110-000E35A83A82401E            • ios            • iOS 18.0 22A3354
    • iPhone 15 Pro Max (mobile)      • 91845D7F-BE70-47DE-B953-D77C1496F98C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @BirjuVachhani, can we get the full output of `flutter build web --wasm -v`? Also, if you add run the command `flutter build web --wasm -O0`, does it build? If not, can you also provide the full verbose output of that command?

**Comment by mraleph** [comment]
cc @osa1 @mkustermann

**Comment by BirjuVachhani** [comment]
@danagbemava-nc I have added the logs you asked for.

**Comment by rayliverified** [comment]
Hi @mraleph, it took us a bit of time but I was able to create a single file reproducible example.

```flutter
import 'package:codelessly_sdk/codelessly_sdk.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Codelessly.instance.initialize(
    config: CodelesslyConfig(
      authToken: "cSlMIT93cj1lXkBuYk5QNmImSTUsTHw2MDQ4VkdlOCZFLHc7",
      isPreview: kDebugMode,
      preload: true,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Comment out the themeData below that uses a CustomPaint Slider to build for Wasm successfully.
      // If the themeData is used, the app will crash when building for Wasm.
      theme: themeData,
      home: Scaffold(
        body: Center(
          child: CodelesslyWidget(
            layoutID: "0R0yRfzR23SQfDGrbg3h",
            loadingBuilder: (context) {
              return const CupertinoActivityIndicator();
            },
          ),
        ),
      ),
    );
  }
}

final ThemeData themeData = ThemeData(
  sliderTheme: SliderThemeData(
    thumbShape: const ThumbShape(),
    trackShape: TrackShape(),
  ),
);

class ThumbShape extends SliderComponentShape {
  final double thumbRadius;

  const ThumbShape({
    this.thumbRadius = 6.0,
  });

  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) {
    return Size.fromRadius(thumbRadius);
  }

  @override
  void paint(
    PaintingContext context,
    Offset center, {
    Animation<double>? activationAnimation,
    Animation<double>? enableAnimation,
    bool? isDiscrete,
    TextPainter? labelPainter,
    RenderBox? parentBox,
    SliderThemeData? sliderTheme,
    TextDirection? textDirection,
    double? value,
    double? textScaleFactor,
    Size? sizeWithOverflow,
  }) {
    final Canvas canvas = context.canvas;

    Paint fillPaint = Paint()
      ..color = sliderTheme!.thumbColor!
      ..style = PaintingStyle.fill;

    Paint borderPaint = Paint()
      ..color = sliderTheme.activeTrackColor!
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke;

    canvas.drawCircle(center, thumbRadius, fillPaint);
    canvas.drawCircle(center, thumbRadius, borderPaint);
  }
}

class TrackShape extends SliderTrackShape {
  @override
  Rect getPreferredRect({
    RenderBox? parentBox,
    Offset? offset = Offset.zero,
    SliderThemeData? sliderTheme,
    bool? isEnabled,
    bool? isDiscrete,
  }) {
    final double thumbWidth =
        sliderTheme!.thumbShape!.getPreferredSize(true, isDiscrete!).width;
    final double trackHeight = sliderTheme.trackHeight!;
    assert(thumbWidth >= 0);
    assert(trackHeight >= 0);
    assert(parentBox!.size.width >= thumbWidth);
    assert(parentBox!.size.height >= trackHeight);

    const double paddingLeft = 0;
    const double paddingRight = 0;

    final double trackLeft = (offset!.dx + thumbWidth / 2);
    final double trackTop =
        offset.dy + (parentBox!.size.height - trackHeight) / 2;
    final double trackWidth = parentBox.size.width - thumbWidth;
    return Rect.fromLTWH(
      trackLeft + paddingLeft,
      trackTop,
      trackWidth - paddingRight * 2,
      trackHeight,
    );
  }

  @override
  void paint(
    PaintingContext context,
    Offset offset, {
    RenderBox? parentBox,
    SliderThemeData? sliderTheme,
    Animation<double>? enableAnimation,
    TextDirection? textDirection,
    Offset? thumbCenter,
    bool? isDiscrete,
    bool? isEnabled,
    Offset? secondaryOffset,
  }) {
    if (sliderTheme?.trackHeight == 0) {
      return;
    }

    final Canvas canvas = context.canvas;

    final Rect trackRect = getPreferredRect(
      parentBox: parentBox,
      offset: offset,
      sliderTheme: sliderTheme,
      isEnabled: isEnabled,
      isDiscrete: isDiscrete,
    );

    final Paint inactivePaint = Paint()
      ..color = sliderTheme!.inactiveTrackColor!
      ..strokeWidth = 3
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;

    final Paint activePaint = Paint()
      ..color = sliderTheme.activeTrackColor!
      ..style = PaintingStyle.fill
      ..strokeWidth = 3
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;

    Path inactiveSegment = Path()
      ..moveTo(trackRect.left, thumbCenter!.dy)
      ..lineTo(trackRect.right, thumbCenter.dy);

    Path activeSegment = Path()
      ..moveTo(trackRect.left, thumbCenter.dy)
      ..lineTo(thumbCenter.dx, thumbCenter.dy);

    canvas.drawPath(inactiveSegment, inactivePaint);
    canvas.drawPath(activeSegment, activePaint);
  }
}
```

**Example repo:** https://github.com/rayliverified/FlutterWasmCompilationError

**Notes:**

- Removing `theme: themeData` builds for Wasm successfully.
- Removing CodelesslyWidget aka the `codelessly_sdk` also builds for Wasm successfully.
- So there's something conflating about the library files and the slider theme data breaking compilation. 
- There's no duplicated names in the Slider class as those inside the library. ThumbShape is the class name in `main.dart` and a parameter name in the library. That's it.


<details><summary>Compilation error</summary>
<p>
```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:        
Error: Wasm compilation failed while optimizing output
[wasm-validator error in module] ref.eq's left argument should be a subtype of eqref, on       
(local.get $10)
[wasm-validator error in module] ref.eq's right argument should be a subtype of eqref, on      
(i32.const 0)
Fatal: error validating input
  Command: C:\Users\searc\Development\flutter\bin\cache\dart-sdk\bin\dart.exe compile wasm     
  --packages=.dart_tool/package_config.json
  --extra-compiler-option=--platform=C:\Users\searc\Development\flutter\bin\cache\flutter_web_s
  dk\kernel\dart2wasm_platform.dill
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui
  --extra-compiler-option=--delete-tostring-package-uri=package:flutter
  --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true   
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/36335019a8eab588c3c2ea7
  83c618d90505be233/
  --extra-compiler-option=--depfile=C:\Users\searc\Development\FlutterWasmCompilationError\.dar
  t_tool\flutter_build\309b0ca34262b8503b61880a5e0ec018\dart2wasm.d -O4 --strip-wasm
  --extra-compiler-option=--no-source-maps -o
  C:\Users\searc\Development\FlutterWasmCompilationError\.dart_tool\flutter_build\309b0ca34262b
  8503b61880a5e0ec018\main.dart.wasm
  C:\Users\searc\Development\FlutterWasmCompilationError\.dart_tool\flutter_build\309b0ca34262b
  8503b61880a5e0ec018\main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:334:5)  
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)   
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)  
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             26.9s
Error: Failed to compile application for the Web.
```
</p>
</details>

**Comment by danagbemava-nc** [comment]
Hi @rayliverified, @BirjuVachhani it seems like this may be fixed on the master & beta channels. Can you confirm if you're able to build successfully on these channels as well?

**Comment by rayliverified** [comment]
Amazing, thank you so much @danagbemava-nc 

It builds on Beta and Master.

**Comment by kevmoo** [comment]
We can close this out then, right?
