### ISSUE TITLE
FileSystemException: Cannot open file, path = '.../flutter/bin/cache/dart-sdk/version'

### ISSUE THREAD

**Issue by xster** [flutter/flutter#15552]
Get a new flutter version, run flutter, ctrl-c as soon as Downloading Dart SDK from Flutter engine xxxx... appears. 

I ended up in a state where 
```
Building flutter tool...
Unhandled exception:
FileSystemException: Cannot open file, path = '.../flutter/bin/cache/dart-sdk/version' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:628)
#1      _File.openSync (dart:io/file_impl.dart:472)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:532)
#3      _File.readAsStringSync (dart:io/file_impl.dart:577)
#4      readTextFile (package:pub/src/io.dart:153)
#5      _getVersion (package:pub/src/sdk.dart:44)
#6      version (package:pub/src/sdk.dart:32)
#7      version (package:pub/src/sdk.dart:32)
#8      PubCommandRunner.runCommand (package:pub/src/command_runner.dart:159)
<asynchronous suspension>
#9      PubCommandRunner.run (package:pub/src/command_runner.dart:116)
<asynchronous suspension>
#10     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
Unhandled exception:
FileSystemException: Cannot open file, path = '.../flutter/bin/cache/dart-sdk/version' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:628)
#1      _File.openSync (dart:io/file_impl.dart:472)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:532)
#3      _File.readAsStringSync (dart:io/file_impl.dart:577)
#4      readTextFile (package:pub/src/io.dart:153)
#5      _getVersion (package:pub/src/sdk.dart:44)
#6      version (package:pub/src/sdk.dart:32)
#7      version (package:pub/src/sdk.dart:32)
#8      PubCommandRunner.runCommand (package:pub/src/command_runner.dart:159)
<asynchronous suspension>
#9      PubCommandRunner.run (package:pub/src/command_runner.dart:116)
<asynchronous suspension>
#10     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```
permanently

**Comment by adammendoza** [comment]
Same here. Any fix?

**Comment by jonahwilliams** [comment]
Perhaps we could download the dart sdk to temp and only copy it to bin cache once it is done

**Comment by xster** [comment]
Sure, seems reasonable.

**Comment by altafkhan8719** [comment]
Same here. Any fix?

**Comment by Codered81** [comment]
I was able to resolve this issue by copying the 'version' file from the parent directory to this directory.
