### ISSUE TITLE
Unable to Build Flutter to Android: Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by njlimbaga3** [flutter/flutter#155594]
### Steps to reproduce

Simply Creating a New Flutter Project; then, ``flutter run``

### Actual results

I cloned a repository as I'm changing my laptop. Now, I get build errors even if I create a new blank flutter app. 

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

The main.dart code is the default. When I run and build this for a Windows App, it works perfectly fine; but deploying to an android device and even an emulator causes the issue below.

### Logs

<details open>
<summary>Logs</summary>

```console

[ +120 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] executing: C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +43 ms] List of devices attached
           R9AT205GABE            device product:a22xnsxx model:SM_A226B device:a22x transport_id:1
[   +5 ms] C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe -s R9AT205GABE shell getprop
[ +161 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +93 ms] Skipping pub get: version match.
[  +92 ms] Generating C:\Users\neil.limbaga\Projects\ftest_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +44 ms] ro.hardware = mt6833
[        ] ro.build.characteristics = phone
[  +61 ms] No packages with native assets. Skipping native assets compilation.
[   +1 ms] Initializing file store
[   +4 ms] Skipping target: gen_localizations
[   +2 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\neil.limbaga\Projects\ftest_app\.dart_tool\package_config_subset}
[  +64 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib\main.dart on SM A226B in debug mode...
[   +1 ms] C:\Users\neil.limbaga\.dev\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe --disable-dart-dev
C:\Users\neil.limbaga\.dev\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server_aot.dart.snapshot --sdk-root C:\Users\neil.limbaga\.dev\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/   
--incremental --target=flutter --experimental-emit-debug-metadata --output-dill C:\Users\NEIL~1.LIM\AppData\Local\Temp\flutter_tools.7190744a\flutter_tool.a519b01c\app.dill --packages
C:\Users\neil.limbaga\Projects\ftest_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root       
--initialize-from-dill build\cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[   +8 ms] executing: C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe -s R9AT205GABE shell -x logcat -v time -t 1
[  +14 ms] <- compile package:ftest_app/main.dart
[ +538 ms] --------- beginning of main
                    09-24 10:11:28.423 E/HfLooper( 1277): eventConvertAll, lux = 227.000000
[   +5 ms] executing: C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +31 ms] Android Debug Bridge version 1.0.41
           Version 35.0.2-12147458
           Installed as C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe
           Running on Windows 10.0.19045
[   +1 ms] executing: C:\Users\neil.limbaga\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +32 ms] Building APK
[   +4 ms] executing: C:\Program Files\Android\Android Studio 2024\jbr\bin\java -version
[  +85 ms] Exit code 0 from: C:\Program Files\Android\Android Studio 2024\jbr\bin\java -version
[        ] openjdk version "17.0.11" 2024-04-16
           OpenJDK Runtime Environment (build 17.0.11+0--11852314)
           OpenJDK 64-Bit Server VM (build 17.0.11+0--11852314, mixed mode)
[   +5 ms] executing: C:\Program Files\Android\Android Studio 2024\jbr\bin\java --version
[  +78 ms] Exit code 0 from: C:\Program Files\Android\Android Studio 2024\jbr\bin\java --version
[        ] openjdk 17.0.11 2024-04-16
           OpenJDK Runtime Environment (build 17.0.11+0--11852314)
           OpenJDK 64-Bit Server VM (build 17.0.11+0--11852314, mixed mode)
[  +12 ms] Using gradle from C:\Users\neil.limbaga\Projects\ftest_app\android\gradlew.bat.
[   +1 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] executing: [C:\Users\neil.limbaga\Projects\ftest_app\android/] C:\Users\neil.limbaga\Projects\ftest_app\android\gradlew.bat --full-stacktrace --info -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=C:\Users\neil.limbaga\Projects\ftest_app\lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true        
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +144 ms] Downloading https://services.gradle.org/distributions/gradle-8.3-all.zip
[ +181 ms] Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to
requested target
[   +1 ms]      at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[        ]      at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
[   +1 ms]      at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
[        ]      at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
[        ]      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1351)
[        ]      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
[        ]      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
[   +1 ms]      at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[        ]      at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[        ]      at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[        ]      at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[        ]      at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[   +1 ms]      at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
[        ]      at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
[   +1 ms]      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[        ]      at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[        ]      at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
[        ]      at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1687)
[        ]      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
[        ]      at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[        ]      at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[        ]      at org.gradle.wrapper.Download.download(Download.java:44)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:61)
[        ]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[        ]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[        ]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[        ]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[        ]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[        ] Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested 
target
[        ]      at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[        ]      at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
[        ]      at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[        ]      at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[        ]      at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[        ]      at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
[        ]      ... 24 more
[        ] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[        ]      at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
[        ]      at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
[        ]      at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[        ]      at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[        ]      ... 29 more
[  +13 ms] Running Gradle task 'assembleDebug'... (completed in 365ms)
[  +10 ms] Error: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 1,861ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[  +47 ms] ensureAnalyticsSent: 43ms
[        ] Running 2 shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-GB)
    • Flutter version 3.24.3 on channel stable at C:\Users\neil.limbaga\.dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (13 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\neil.limbaga\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio 2024\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35312.102
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio 2024
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\neil.limbaga\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (4 available)
    • SM A226B (mobile) • R9AT205GABE • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.4894]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 128.0.6613.138
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 129.0.2792.52

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@njlimbaga3 
Looking at the error log, it doesn't seem to be related to Flutter, but coming from native. Check your local internet connection and confirm if it is working fine. Make sure you are not using VPN or any restricted network or office network with proxy. 
Another possibility is combination of gradle + android studio config. Check https://stackoverflow.com/questions/26697118/android-studio-unable-to-find-valid-certification-path-to-requested-target for further reference.

Closing for now. If you think it is a genuine bug in flutter, provide exact and relevant details so that we can properly address the issue.
