### ISSUE TITLE
[in_app_purchase] [iOS] Can not load the storekit configure

### ISSUE THREAD

**Issue by tuyen3962** [flutter/flutter#155503]
### Steps to reproduce

1. Create storekit configuration and add product with certain id
2. Edit scheme and add storekit into scheme
3. Call function queryProductDetails with certain id and not return product

### Expected results

Call function queryProductDetails and return the product which setup in the Storekit configuration file 

### Actual results

Call function queryProductDetails and throw storekit_getproductrequest_platform_error

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@tuyen3962 
In order to properly address the issue, please provide us complete minimal reproducible code sample along with `flutter doctor -v`.



> and throw storekit_getproductrequest_platform_error

Please provide complete error log.

**Comment by darshankawar** [comment]
> please provide us complete minimal reproducible code sample

@tuyen3962 This as well importantly.

**Comment by tuyen3962** [comment]
Please check it for me

Code sample:
final result = await InAppPurchase.instance.queryProductDetails({'id'});
      if (result.error != null && result.productDetails.isEmpty) {
        return;
      }

Now I receive the error message when I query product detail in the version 3.2.0 in_app_purchase

Error when I debug it
#0      SKPriceLocaleMessage.decode (package:in_app_purchase_storekit/src/messages.g.dart:417:29)
#1      SKProductMessage.decode (package:in_app_purchase_storekit/src/messages.g.dart:372:41)
#2      _InAppPurchaseAPICodec.readValueOfType (package:in_app_purchase_storekit/src/messages.g.dart:556:33)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#4      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
#5      _InAppPurchaseAPICodec.readValueOfType (package:in_app_purchase_storekit/src/messages.g.dart:564:22)
#6      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#7      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
#8      _InAppPurchaseAPICodec.readValueOfType (package:in_app_purchase_storekit/src/messages.g.dart:564:22)
#9      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#10     _InAppPurchaseAPICodec.readValueOfType (package:in_app_purchase_storekit/src/messages.g.dart:560:49)
#11     StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#12     StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
#13     _InAppPurchaseAPICodec.readValueOfType (package:in_app_purchase_storekit/src/messages.g.dart:564:22)
#14     StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#15     StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:341:28)
#16     BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:218:18)
<asynchronous suspension>
#17     InAppPurchaseAPI.startProductRequest (package:in_app_purchase_storekit/src/messages.g.dart:703:47)
<asynchronous suspension>
#18     SKRequestMaker.startProductRequest (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_request_maker.dart:32:9)
<asynchronous suspension>
#19     InAppPurchaseStoreKitPlatform.queryProductDetails (package:in_app_purchase_storekit/src/in_app_purchase_storekit_platform.dart:167:18)
<asynchronous suspension>
#20     PaymentController.handleForm (package:source_base/screen/payment_course/payment_course_controller.dart:118:22)
<asynchronous suspension>
#21     FormTextFieldHandler.onSubmit (package:source_base/widget/textfield/text_field_node.dart:189:7)
<asynchronous suspension>

**Comment by darshankawar** [comment]
@tuyen3962 
You are most probably hitting https://github.com/flutter/flutter/issues/154047 which has been fixed last month. So please upgrade your sdk and re-run your scenario to confirm.

**Comment by tuyen3962** [comment]
@darshankawar this is another variable which can be null when convert from list to object.

I find the root problem in the line 417 of message.g.dart file:

countryCode: result[2]! as String

Please check it again

**Comment by darshankawar** [comment]
> SKPriceLocaleMessage.decode (package:in_app_purchase_storekit/src/messages.g.dart:417:29)
> #1      SKProductMessage.decode (package:in_app_purchase_storekit/src/messages.g.dart:372:41)

https://github.com/flutter/packages/blob/4926c0f8bd99ac61e5208e3410182be97ec0c2a4/packages/in_app_purchase/in_app_purchase_storekit/lib/src/messages.g.dart#L417

and

https://github.com/flutter/packages/blob/4926c0f8bd99ac61e5208e3410182be97ec0c2a4/packages/in_app_purchase/in_app_purchase_storekit/lib/src/messages.g.dart#L372

Probably `queryProductDetails()` with the `productID` gets data from storekit, but field that will go into `countryCode` in the function `SkPriceLocaleMessage.decode(Object result)` resulting in `null`.

**Comment by tuyen3962** [comment]
Yes, it is relevant to country code when i test it with storekit. Please check and fix it 🤩🤩🤩

**Comment by hellohuanlin** [comment]
cc @LouiseHsu

**Comment by timevoltex** [comment]
any update?

**Comment by tuyen3962** [comment]
I have configured it successfully so I close this issue
