### ISSUE TITLE
[tool_crash] StateError: Bad state: Failed to start Dart Development Service

### ISSUE THREAD

**Issue by bhattishani** [flutter/flutter#155589]
## Command
```sh
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target E:\android\sangath\lib\main.dart
```

## Steps to Reproduce
1. Launch App In Debug Mode
2. Wait until debug apk getting generated
3. Wait for Splash Screen

## Logs
StateError: Bad state: Failed to start Dart Development Service
```console
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:114:9)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:294:11)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel master, 3.26.0-1.0.pre.176, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.26.0-1.0.pre.176 on channel master at E:\android\flutter_sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4ca51a1de5 (20 hours ago), 2024-09-23 05:51:28 -0400
    • Engine revision 61f0a3fbab
    • Dart version 3.6.0 (build 3.6.0-270.0.dev)
    • DevTools version 2.40.0-dev.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\bhatt\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: H:\android\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.2)
    • Visual Studio at H:\Microsoft Visual Studio
    • Visual Studio Community 2022 version 17.10.35004.147
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at H:\android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 128.0.6613.138
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 129.0.2792.52

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9e1c857886f07d342cf106f2cd588bcd5e031bb2
### Plugins
flutter_native_splash-2.4.0
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2

**Comment by huycozy** [comment]
Hi @bhattishani 
How frequently do you see this error? Does it only happen one time? Do you see this issue on your Flutter project or even on a newly created project? 

This looks similar to https://github.com/flutter/flutter/issues/154477
