### ISSUE TITLE
[tool_crash] _TypeError: (#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4))

### ISSUE THREAD

**Issue by Metz01** [flutter/flutter#155504]
## Command
```sh
flutter --version
```

## Steps to Reproduce
OS: Arch Linux
on: yay -Rs flutter

## Logs
_TypeError: (#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4))
```console
#0      _gitCommitDate (package:flutter_tools/src/version.dart:387:4)
#1      _FlutterVersionGit.frameworkCommitDate (package:flutter_tools/src/version.dart:495:37)
#2      FlutterVersion.toString (package:flutter_tools/src/version.dart:225:99)
#3      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:408:30)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#6      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[31m[☠][39m Flutter (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m Null check operator used on a null value
    [32m•[39m #0      FlutterValidator._getFlutterUpstreamMessage
      (package:flutter_tools/src/doctor.dart:677:86)
      #1      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:544:20)
      #2      Doctor.startValidatorTasks.<anonymous closure>
      (package:flutter_tools/src/doctor.dart:247:72)
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #4      _rootRun (dart:async/zone.dart:1399:13)
      #5      _CustomZone.run (dart:async/zone.dart:1301:19)
      #6      _runZoned (dart:async/zone.dart:1826:10)
      #7      runZonedGuarded (dart:async/zone.dart:1814:12)
      #8      runZoned (dart:async/zone.dart:1760:12)
      #9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #10     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:239:9)
      #11     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:760:60)
      #12     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
      #13     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:764:53)
      #14     DoctorText.text (package:flutter_tools/src/doctor.dart:756:36)
      #15     DoctorText.text (package:flutter_tools/src/doctor.dart)
      #16     _createLocalCrashReport (package:flutter_tools/runner.dart:273:51)
      #17     _handleToolError (package:flutter_tools/runner.dart:235:31)
      <asynchronous suspension>
      #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #19     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /opt/android-sdk
    [32m•[39m Platform android-35, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /opt/android-sdk
    [32m•[39m ANDROID_SDK_ROOT = /opt/android-sdk
    [32m•[39m Java binary at: /usr/bin/java
    [31m✗[39m Could not determine java version
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK li

**Comment by danagbemava-nc** [comment]
Hi @Metz01, do you know what version of flutter was installed by your package manager? Also, what version of git is installed on your device?
