### ISSUE TITLE
Firebase Auth Freezes the App sometimes and Throws this Error

### ISSUE THREAD

**Issue by harriscreativity** [flutter/flutter#15562]
```
Reloaded 4 of 503 libraries in 5,577ms.
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.util.SparseArray.removeAt(SparseArray.java:168)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleStopListeningAuthState(FirebaseAuthPlugin.java:291)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:95)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:133)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/FirebaseAuth(28187): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(28187): [FirebaseAuth:] Preparing to create service connection to gms implementation
I/FlutterActivityDelegate(28187): onResume setting current activity to this
```

**Comment by harriscreativity** [comment]
throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);

**Comment by diego-lipinski-de-castro** [comment]
I'm running on this aswell, using googlesignin, if i open the popup but click outside it just freezes, even tho i used try catch

**Comment by Jaxhunter66** [comment]
same problem here
throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
made sure my SHA-1 was set up, Google Sign In was enabled in the FB console, and my App ID was correct. I can't tell if it's my fault or the plugin.

**Comment by ram231** [comment]
Never tried any apps in android that signs in with google, but this gives me an error. I will investigate the error too. hopefully someone will link an issue to this one.

**Comment by ofekashery** [comment]
Any update?

**Comment by collinjackson** [comment]
It would be helpful to get a complete reduced test case for what you're trying to do.

**Comment by bparrishMines** [comment]
I believe this was fixed by https://github.com/flutter/plugins/pull/620. Closing.

**Comment by kroikie** [comment]
@harriscreativity

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/887. Any further collaboration will be done there.
