### ISSUE TITLE
Pub autoroller broken on version constraint violation

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#155704]
For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20packages_autoroller/12098/infra

**Comment by christopherfujino** [comment]
From the bottom of the logs:

```
Executing [/b/s/w/ir/x/w/flutter_conductor_checkouts/framework/bin/dart, /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart, --no-gradle-generation, --no-exclusion]...
If you don't wish to re-generate the settings.gradle, build.gradle, and gradle-wrapper.properties files,
add the flag `--no-gradle-generation`.
This tool automatically excludes a set of android subdirectories, defined at dev/tools/bin/config/lockfile_exclusion.yaml.
To disable this behavior, run with `--no-exclusion`.

Running without exclusion.
/b/s/w/ir/x/w/flutter_conductor_checkouts/framework/packages/integration_test/android/gradle/wrapper/gradle-wrapper.properties does not exist - skipping
Processing /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/packages/integration_test/example/android
Unhandled exception:
ProcessException: Downloading Material fonts...                                      396ms
Downloading Gradle Wrapper...                                       34ms
Downloading package sky_engine...                                  130ms
Downloading package flutter_gpu...                                  35ms
Downloading flutter_patched_sdk tools...                           266ms
Downloading flutter_patched_sdk_product tools...                   200ms
Downloading linux-x64 tools...                                   1,177ms
Downloading linux-x64/font-subset tools...                         122ms
Resolving dependencies...
Note: vm_service is pinned to version 14.2.5 by integration_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because integration_test_example depends on integration_test from sdk which depends on vm_service 14.2.5, vm_service 14.2.5 is required.
So, because integration_test_example depends on vm_service 14.3.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on vm_service: flutter pub add dev:vm_service:^14.2.5
Failed to update packages.

  Command: flutter pub get
#0      exec (file:///b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart:213:5)
#1      main (file:///b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart:182:5)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Unhandled exception:
Exception: ProcessException: ProcessException: Process failed
  Command: /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/bin/dart /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart --no-gradle-generation --no-exclusion
#0      PackageAutoroller.roll (package:conductor_core/src/packages_autoroller.dart:106:7)
<asynchronous suspension>
#1      run (file:///b/s/w/ir/x/w/flutter/dev/conductor/core/bin/packages_autoroller.dart:83:3)
<asynchronous suspension>
```

This looks to me like updating the pub packages with `flutter update-packages --force-upgrade` succeeded, but then it must have generated an invalid solve (I didn't think this was possible...), since when we try to pub get as part of re-generating gradle lockfiles, pub is failing because the constraints don't match.

What I would do is try to reproduce this locally, and then inspect the pubspec's to see what went wrong.

**Comment by christopherfujino** [comment]
> Because integration_test_example depends on integration_test from sdk which depends on vm_service 14.2.5, vm_service 14.2.5 is required.
> So, because integration_test_example depends on vm_service 14.3.0, version solving failed.

I thought this was impossible, based on how `flutter update-packages --force-upgrade` works...

**Comment by christopherfujino** [comment]
Oh btw, I marked this build target bringup: true, which puts it in the staging pool. This also effectively makes it fail 100% of the time, because this script requires a github access token which only the prod pool has access to.

**Comment by gmackall** [comment]
Re-opening till we can confirm the pr fixes the bot

**Comment by gmackall** [comment]
This is fixed
