### ISSUE TITLE
DropdownMenu throws exception when nested inside two ListView

### ISSUE THREAD

**Issue by bcerjan** [flutter/flutter#155831]
### Steps to reproduce

1. Add a `DropdownMenu` inside two `ListViews`
2. Run the debugger
3. Try to change the value of the `DropdownMenu` (note: it only throws the error if there is already a value selected)

I assume this is related to #146764, but it appears as though that was already fixed. I am working on Windows.

### Expected results

I expect this to not throw an error.

### Actual results

It throws: `'renderer.parent != null': is not true`

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class TestWidget extends StatelessWidget {
  const TestWidget({super.key});
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
        itemCount: 2,
        itemBuilder: (contex, index) => LevelOneItem(index: index));
  }
}

class LevelOneItem extends StatefulWidget {
  const LevelOneItem({super.key, required this.index});
  final int index;
  static List<Color> colors = [Colors.blue, Colors.green, Colors.red];

  @override
  State<LevelOneItem> createState() => _LevelOneItemState();
}

class _LevelOneItemState extends State<LevelOneItem> {
  List<int> selections = [1, 2, 1];

  void update(int index, int val) {
    setState(() {
      final temp = List<int>.from(selections);
      temp.removeAt(index);
      temp.insert(index, val);
      selections = temp;
    });
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
        physics: const ClampingScrollPhysics(),
        shrinkWrap: true,
        itemCount: selections.length,
        itemBuilder: (context, index) => Container(
              height: 100,
              color: LevelOneItem.colors[index],
              child: LevelTwoItem(
                selected: selections[index],
                cb: (value) => update(index, value),
              ),
            ));
  }
}

class LevelTwoItem extends StatelessWidget {
  const LevelTwoItem({
    super.key,
    required this.selected,
    required this.cb,
  });
  final int selected;
  final ValueChanged<int> cb;
  final List<DropdownMenuEntry<int>> entries = const [
    DropdownMenuEntry(value: 1, label: 'one'),
    DropdownMenuEntry(value: 2, label: 'two')
  ];
  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        const Text('Menu'),
        DropdownMenu<int>(
          initialSelection: selected,
          dropdownMenuEntries: entries,
          onSelected: (value) => cb(value ?? selected),
        )
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3347 pos 14: 'renderer.parent != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3347:14)
#3      ScrollPosition.ensureVisible (package:flutter/src/widgets/scroll_position.dart:799:28)
#4      ScrollableState._performEnsureVisible (package:flutter/src/widgets/scrollable.dart:1028:55)
#5      Scrollable.ensureVisible (package:flutter/src/widgets/scrollable.dart:475:45)
#6      _DropdownMenuState.scrollToHighlight.<anonymous closure> (package:flutter/src/material/dropdown_menu.dart:509:20)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#10     _invoke (dart:ui/hooks.dart:312:13)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#12     _drawFrame (dart:ui/hooks.dart:283:31)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.4169], locale en-US)
    • Flutter version 3.22.2 on channel stable at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\bcerj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 128.0.6613.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.52

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @bcerjan, I checked this again on the latest Flutter stable 3.24.3 but didn't see the issue when changing value on DropdownMenu items. I tested it on macOS app.

I see you are on 3.22.2 which doesn't seem to contain the fix https://github.com/flutter/flutter/commit/a766945bdd006893e1041a3acbe590344ab45a12. Can you try upgrading Flutter and retry?

**Comment by bcerjan** [comment]
@huycozy that seems to have fixed it, my mistake for not upgrading before posting. Thanks for your help.
