### ISSUE TITLE
Flutter Widget Inspector encountered an assertion error

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#155847]
I encountered an error while using the Flutter inspector.

### Steps to reproduce

I don't have exact reproduction steps, but I was doing roughly the following when the error occurred:

1. flutter create sample
2. flutter run -d <ios device identifier>
3. With the app open, click on the devtools URL in the terminal, to open the Devtools
4. Select the Flutter Inspector tab
5. An error is printed to the console (see below)
6. The inspector floating action button is shown in the bottom left
7. Try to select a widget 
8. The Devtools UI stays empty, but the Flutter app devtools overlay works

<details>

 <summary>Flutter Doctor</summary>
 
 ```console
 [✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-x64, locale
    en-BE)
    • Flutter version 3.24.1 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision 5874a72aa4 (8 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • motorola one (mobile) • ZL5228NFL7                           •
      android-arm64  • Android 10 (API 29)
    • iPhone Xs (mobile)    • A1C65549-1101-4825-B9ED-41E7C098ACD5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)       • macos                                • darwin-x64
      • macOS 14.6.1 23G93 darwin-x64
    • Chrome (web)          • chrome                               •
      web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
 ```

</details>

<details>

 <summary>Logs</summary>
 
 ```
 navaronbracke@MacBook-Pro-van-Navaron sample_app % flutter run -d <device id>
Launching lib/main.dart on iPhone Xs in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        32.6s
Xcode build done.                                           54.2s
Syncing files to device iPhone Xs...                               352ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone Xs is available at: http://127.0.0.1:63670/mW-A2XQtUBY=/
The Flutter DevTools debugger and profiler on iPhone Xs is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:63670/mW-A2XQtUBY=/

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for
"ext.flutter.inspector.getRootWidgetTree":
'package:flutter/src/painting/text_style.dart': Failed assertion: line 1583 pos 14:
'decorationDescription.isNotEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      TextStyle.debugFillProperties (package:flutter/src/painting/text_style.dart:1583:14)
#3      Text.debugFillProperties (package:flutter/src/widgets/text.dart:721:12)
#4      Element.debugFillProperties (package:flutter/src/widgets/framework.dart:5102:14)
#5      DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2837:17)
#6      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2840:8)
#7      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2851:77)
#8      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1623:13)
#9      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#10     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#11     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#13     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#14     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#15     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#16     new List.of (dart:core-patch/array_patch.dart:39:18)
#17     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#18     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#19     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#20     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#21     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#22     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#23     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#24     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#25     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#26     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#27     new List.of (dart:core-patch/array_patch.dart:39:18)
#28     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#29     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#30     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#31     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#32     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#33     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#34     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#35     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#36     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#37     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#38     new List.of (dart:core-patch/array_patch.dart:39:18)
#39     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#40     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#41     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#42     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#43     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#44     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#45     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#46     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#47     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#48     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#49     new List.of (dart:core-patch/array_patch.dart:39:18)
#50     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#51     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#52     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#53     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#54     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#55     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#56     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#57     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#58     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#59     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#60     new List.of (dart:core-patch/array_patch.dart:39:18)
#61     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#62     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#63     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#64     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#65     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#66     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#67     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#68     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#69     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#70     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#71     new List.of (dart:core-patch/array_patch.dart:39:18)
#72     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#73     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#74     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#75     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#76     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#77     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#78     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#79     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#80     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#81     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#82     new List.of (dart:core-patch/array_patch.dart:39:18)
#83     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#84     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#85     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#86     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#87     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#88     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#89     MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#90     ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#91     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#92     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#93     new List.of (dart:core-patch/array_patch.dart:39:18)
#94     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#95     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#96     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#97     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#98     _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#99     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#100    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#101    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#102    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#103    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#104    new List.of (dart:core-patch/array_patch.dart:39:18)
#105    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#106    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#107    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#108    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#109    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#110    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#111    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#112    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#113    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#114    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#115    new List.of (dart:core-patch/array_patch.dart:39:18)
#116    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#117    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#118    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#119    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#120    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#121    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#122    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#123    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#124    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#125    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#126    new List.of (dart:core-patch/array_patch.dart:39:18)
#127    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#128    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#129    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#130    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#131    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#132    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#133    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#134    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#135    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#136    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#137    new List.of (dart:core-patch/array_patch.dart:39:18)
#138    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#139    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#140    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#141    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#142    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#143    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#144    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#145    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#146    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#147    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#148    new List.of (dart:core-patch/array_patch.dart:39:18)
#149    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#150    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#151    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#152    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#153    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#154    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#155    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#156    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#157    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#158    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#159    new List.of (dart:core-patch/array_patch.dart:39:18)
#160    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#161    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#162    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#163    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#164    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#165    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#166    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#167    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#168    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#169    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#170    new List.of (dart:core-patch/array_patch.dart:39:18)
#171    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#172    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#173    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#174    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#175    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#176    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#177    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#178    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#179    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#180    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#181    new List.of (dart:core-patch/array_patch.dart:39:18)
#182    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#183    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#184    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#185    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#186    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#187    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#188    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#189    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#190    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#191    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#192    new List.of (dart:core-patch/array_patch.dart:39:18)
#193    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#194    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#195    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#196    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#197    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#198    DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1677:19)
#199    MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#200    ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#201    new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#202    new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#203    new List.of (dart:core-patch/array_patch.dart:39:18)
#204    ListIterable.toList (dart:_internal/iterable.dart:224:7)
#205    DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1678:8)
#206    DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1645:23)
#207    DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1652:6)
#208    _ElementDiagnosticableTreeNode.toJsonMap (package:flutter/src/widgets/framework.dart:5369:45)
#209    WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1735:18)
#210    WidgetInspectorService._getRootWidgetTreeImpl (package:flutter/src/widgets/widget_inspector.dart:2025:12)
#211    WidgetInspectorService._getRootWidgetTree (package:flutter/src/widgets/widget_inspector.dart:1981:42)
#212    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:950:32)
<asynchronous suspension>
#213    _runExtension.<anonymous closure> (dart:developer-patch/developer.dart:112:11)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 1583 pos 14: 'decorationDescription.isNotEmpty': is not true.
Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 1583 pos 14: 'decorationDescription.isNotEmpty': is not true.
 ```

</details>

![Screenshot 2024-08-29 at 10 53 41](https://github.com/user-attachments/assets/ba29126f-afc2-41ab-acef-557cf3880105)

![Screenshot 2024-08-29 at 10 53 28](https://github.com/user-attachments/assets/d9f972d6-c89f-4ac4-b591-b13a47576fa5)

**Comment by elliette** [comment]
Based on the stacktrace, this looks like a Flutter issue not a DevTools issue. Transferring to the Flutter repo.

**Comment by huycozy** [comment]
Hi @navaronbracke 
I am not able to reproduce this issue on counter app on Flutter stable 3.24.3. Do you only see this issue on your project as the demo screenshot provided? Please try to narrow the code down into a simpler one that can reproduce the issue and share it when you have it. Thank you!

**Comment by navaronbracke** [comment]
I did an additional test on the specific project where I encountered the issue.

I cannot reproduce this anymore on Flutter 3.24.3 (stable) or 3.26.0-1.0.pre.263 (master)

Perhaps this was fixed between 3.24.1 and 3.24.3 ?

**Comment by huycozy** [comment]
As far as I can see, `getRootWidgetTree` was added by https://github.com/flutter/flutter/pull/150010. And that PR commit https://github.com/flutter/flutter/commit/1f93809ad25090a0e5b6f5b8b690e2e6e2c78ef7 is available on Flutter 3.24.1 as well which means the fix for this issue should come after that. I can't find the exact commit for the fix but maybe it was one of these commit on [widget_inspector.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/widget_inspector.dart)?

```console
5c5b3c5796 Ignore both unused_element and unused_element_parameter (#152689)
788a0e3d2f Implementing null-aware logic in `/packages/flutter/` (#152294)
7b5462cc34 `docImport`s for the widgets library (#152339)
d07a165d22 Implementing a few switch statements (#150946)
d7af9314b3 Update flutter.dev links from framework to more permanent destinations (#150531)
1f93809ad2 Add new `WidgetInspector` service extension: `getRootWidgetTree` (#150010) //was added on 3.24.1, so exclude this one
```

If you want to cherry-pick and find the fix, maybe bisecting between 3.24.1 and 3.24.3 could help.

**Comment by navaronbracke** [comment]
I'll try to bisect the exact fix commit, but if it is fixed on the latest stable, do we need a cherry-pick?

**Comment by huycozy** [comment]
I meant to cherry-pick the fix commit onto your current Flutter version 3.24.1 in case you don't want to upgrade Flutter to 3.24.3.

**Comment by navaronbracke** [comment]
Ah, no worries, I already did the upgrade on my end :) It's only a hotfix release, so the chance of something breaking is very minimal anyway.
