### ISSUE TITLE
Could not run command "salt-call state.apply" from both mac-12 and mac-14, got errors.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#155971]
### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Hi Brandon,

I'm getting errors when run command "satl-call state.apply" from both mac-12 & mac-14 machines.  Can you take a look from Salt master?  I'm got same errors like last time, couldn't connect to Salt master to obtain new certificate keys.

 ID: /etc/pki/flutter-devicelab-mac-14.mtv.corp.google.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/states/x509.py", line 671, in certificate_managed
                  name, days_remaining, append_certs, **kwargs
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/states/x509.py", line 501, in _certificate_is_valid
                  testrun=True, **cert_spec
                File "/opt/salt/lib/python3.7/site-packages/salt-3002.1-py3.7.egg/salt/modules/x509.py", line 1452, in create_certificate
                  if not any(certs):
              TypeError: 'NoneType' object is not iterable
     Started: 17:22:38.240847
    Duration: 226.766 ms
     Changes:   
----------
          ID: /var/lib/luci_machine_tokend
    Function: file.directory
      Result: True
     Comment: The directory /var/lib/luci_machine_tokend is in the correct state
     Started: 17:22:38.467876
    Duration: 1.199 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: file.managed
      Result: True
     Comment: File /opt/luci/machine_tokend/run.sh is in the correct state
     Started: 17:22:38.469705
    Duration: 271.539 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-14.mtv.corp.google.com.crt
     Started: 17:22:38.742618
    Duration: 0.003 ms
     Changes:   
----------
          ID: /opt/luci/machine_tokend/run.sh >/dev/null 2>&1
    Function: cron.present
      Result: False
     Comment: One or more requisite failed: machine_tokend./etc/pki/flutter-devicelab-mac-14.mtv.corp.google.com.crt
     Started: 17:22:38.743096
    Duration: 0.002 ms
     Changes:   
----------
          ID: /usr/local/bin/validate_json.py
    Function: file.managed
      Result: True
     Comment: File /usr/local/bin/validate_json.py is in the correct state
     Started: 17:22:38.743133
    Duration: 155.755 ms
     Changes:   
----------
          ID: kvm
    Function: group.present
      Result: True
     Comment: Group kvm is present and up to date
     Started: 17:22:38.899034
    Duration: 12.382 ms
     Changes:   
----------
          ID: plugdev
    Function: group.present
      Result: True
     Comment: Group plugdev is present and up to date
     Started: 17:22:38.911506
    Duration: 10.534 ms
     Changes:   
----------
          ID: swarming
    Function: group.present
      Result: True
     Comment: Group swarming is present and up to date
     Started: 17:22:38.922128
    Duration: 10.419 ms
     Changes:   
----------
          ID: swarming
    Function: user.present
      Result: True
     Comment: User swarming is present and up to date
     Started: 17:22:38.933301
    Duration: 215.336 ms
     Changes:   
----------
          ID: swarming
    Function: file.directory
        Name: /Users/swarming
      Result: True
     Comment: The directory /Users/swarming is in the correct state
     Started: 17:22:39.148851
    Duration: 0.956 ms
     Changes:   
----------
          ID: /etc/sudoers
    Function: file.append
      Result: True
     Comment: File /etc/sudoers is in correct state
     Started: 17:22:39.150179
    Duration: 29.827 ms
     Changes:   
----------
          ID: /opt/s
    Function: file.directory
      Result: True
     Comment: The directory /opt/s is in the correct state
     Started: 17:22:39.180644
    Duration: 1.354 ms
     Changes:   
----------
          ID: /opt/s/bot_code.py
    Function: cmd.script
      Result: False
     Comment: Command '/opt/s/bot_code.py' run
     Started: 17:22:39.182712
    Duration: 602.447 ms
     Changes:   
              ----------
              pid:
                  31153
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/opt/s/__salt.tmp.gigze7e3.py", line 12, in <module>
                      with closing(urlopen(req)) as res:
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
                      return opener.open(url, data, timeout)
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
                      response = meth(req, response)
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
                      response = self.parent.error(
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
                      return self._call_chain(*args)
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
                      result = func(*args)
                    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
                      raise HTTPError(req.full_url, code, msg, hdrs, fp)
                  urllib.error.HTTPError: HTTP Error 401: Unauthorized
              stdout:
----------
          ID: /Library/LaunchDaemons/org.swarm.bot.plist
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: luci/swarming./opt/s/bot_code.py
     Started: 17:22:39.785922
    Duration: 0.003 ms
     Changes:   
----------
          ID: org.swarm.bot
    Function: service.running
      Result: False
     Comment: One or more requisite failed: luci/swarming./Library/LaunchDaemons/org.swarm.bot.plist, luci/swarming./opt/s/bot_code.py
     Started: 17:22:39.786472
    Duration: 0.003 ms
     Changes:   
----------
          ID: /System/Volumes/Data/.fseventsd/no_log
    Function: file.touch
      Result: True
     Comment: Updated times on file /System/Volumes/Data/.fseventsd/no_log
     Started: 17:22:39.786515
    Duration: 0.729 ms
     Changes:   
              ----------
              touched:
                  /System/Volumes/Data/.fseventsd/no_log
----------
          ID: git
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 17:22:39.787334
    Duration: 19.084 ms
     Changes:   
----------
          ID: fuchsia/salt-version-base
    Function: event.send
      Result: True
     Comment: Event fired
     Started: 17:22:39.806503
    Duration: 203.192 ms
     Changes:   
              ----------
              data:
                  ----------
                  hash:
                      0a6271cd3e58292ff7d0b6c2e9045251e6f27a1a
                  date:
                      2024-09-10
              tag:
                  fuchsia/salt-version-base

Summary for local
-------------
Succeeded: 41 (changed=12)
Failed:     6

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
I ran same command today "salt-call state.apply" and was successful. No action required, this service ticket can be closed.
