### ISSUE TITLE
ProcessException: Failed to find "powershell" in the search path.         Command: powershell

### ISSUE THREAD

**Issue by shawnmcpeek** [flutter/flutter#156189]
### Steps to reproduce

flutter doctor -v

### Actual results

I get told:
```
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:87:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:674:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:673:12)
      #4      ProcessLister.getProcessesWithPath
      (package:flutter_tools/src/windows/windows_version_validator.dart:111:27)
      #5      WindowsVersionValidator._topazScan
      (package:flutter_tools/src/windows/windows_version_validator.dart:40:69)
      #6      WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:81:15)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:247:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1826:10)
      #12     runZonedGuarded (dart:async/zone.dart:1814:12)
      #13     runZoned (dart:async/zone.dart:1760:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:239:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:371:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>
```
      
     I think the problem is that powershell v7, the current version, has the main exe file as pwsh.exe, not powershell.exe

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
PS C:\Users\shawn\OneDrive\Documents\RWAFlutter\ridewealth_assistant> $env:PATH = "C:\Program Files\PowerShell\7;$env:PATH"; flutter doctor -v
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Users\shawn\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "powershell" in the search path.
        Command: powershell
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:87:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:674:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:569:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:673:12)
      #4      ProcessLister.getProcessesWithPath
      (package:flutter_tools/src/windows/windows_version_validator.dart:111:27)
      #5      WindowsVersionValidator._topazScan
      (package:flutter_tools/src/windows/windows_version_validator.dart:40:69)
      #6      WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:81:15)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:247:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1826:10)
      #12     runZonedGuarded (dart:async/zone.dart:1814:12)
      #13     runZoned (dart:async/zone.dart:1760:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:239:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:371:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:93:3)
      <asynchronous suspension>


[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\shawn\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\shawn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13763.5

[√] VS Code (version 1.94.0)
    • VS Code at C:\Users\shawn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] VS Code, 64-bit edition (version 1.87.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
> that powershell v7, the current version, has the main exe file as pwsh.exe, not powershell.exe

Windows PowerShell versions 5.1 and earlier: The executable file is named powershell.exe 
PowerShell version 6 and higher: The executable file is named pwsh.exe on Windows, and pwsh on macOS and Linux

Can you try with 5.1 and re-run your scenario to check if you still get same error or not ? If not, then we might need to see if there's a possibility of tool identifying this and to show a message.

**Comment by shawnmcpeek** [comment]
I was having similar issues with 5.1 but it may not have been in my PATH so
not sure on that. I did end up changing pwsh.exe to powershell.exe and
making sure that was in my PATH, and it worked. If isn't recognizing Java
version now.

**Comment by darshankawar** [comment]
> If isn't recognizing Java version now.

What log is it showing for this ?

**Comment by darshankawar** [comment]
> I think the problem is that powershell v7, the current version, has the main exe file as pwsh.exe, not powershell.exe

I will keep the issue open based on the error report and for this observation to know if there's any fix needed from tool side for this finding.

**Comment by andrewkolos** [comment]
Looking at the stack trace, here's a quick link to the relevant code:

https://github.com/flutter/flutter/blob/3123d98132ba392025469d459846f7ccc44b6040/packages/flutter_tools/lib/src/windows/windows_version_validator.dart#L109-L112
