### ISSUE TITLE
[image_picker] error caused by ClassCastException

### ISSUE THREAD

**Issue by nnwh20** [flutter/flutter#156207]
Halo, so i'm using add-to-apps on android and installing image_picker

**Steps to reproduce**
1. Installing image_picker
2. run the apps

**Expected results**
image_picker successfully installed and can pick image from gallery or take image from camera

**Actual results**
force close immediately on android using emulator and real devices when flutter activity is running

**Logs**

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rrq.mobile.debug/io.flutter.embedding.android.FlutterActivity}: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Application
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Application
                                                                                                    	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onAttachedToActivity(ImagePickerPlugin.java:210)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivityInternal(FlutterEngineConnectionRegistry.java:350)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:323)
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:208)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`
                                                                                                    	
**Flutter Doctor output**

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6 23G80 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/qdh/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/qdh/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/qdh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by darshankawar** [comment]
@nnwh20 
Can you try running `flutter pub upgrade` and then re-run your scenario to check if the error still occurs or not ?
If still yes, please provide us a runnable reproducible code sample or a sample github repo that we can clone to verify this further.

**Comment by RitikSharma02** [comment]
try running the application using chrome instead of emulator and do use widget inspector see where the issue coming from most probably its a package use caused by SDK version or flutter version mismatch do a thorough clean up of package if possible from project and analyse issue step by step as you are re integrating

**Comment by nnwh20** [comment]
Thanks to all for the feedback. I have debugged the issue and finally resolved it, at least for now. i changed 
        (Application) pluginBinding.getApplicationContext() to (Application) binding.getActivity().getApplicationContext() inside onAttachedToActivity at ImagePickerPlugin.

**Comment by darshankawar** [comment]
Closing as resolved.
