### ISSUE TITLE
[Flutter GPU] Windows: UI thread hangs indefinitely on RenderPass::Draw.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#156305]
Noticed this while investigating https://github.com/bdero/flutter_scene/issues/30#issuecomment-2395753547.

**Comment by bdero** [comment]
It's the pipeline future:

![image](https://github.com/user-attachments/assets/cd94aa74-12f2-43f5-a0d9-76dfae939096)

**Comment by bdero** [comment]
We can get around the reactor queueing and resolve it immediately by posting a raster task.
But this is only necessary when a new pipeline actually needs to be created. Need to add a way to check for the presence of a pipeline in the library without triggering a new pipeline creation.

```diff
@@ -134,8 +140,27 @@ RenderPass::GetOrCreatePipeline() {
   render_pipeline_->BindToPipelineDescriptor(*context.GetShaderLibrary(),
                                              pipeline_desc);

-  auto pipeline =
-      context.GetPipelineLibrary()->GetPipeline(pipeline_desc).Get();
+  std::shared_ptr<impeller::Pipeline<impeller::PipelineDescriptor>> pipeline;
+
+  if (context.GetBackendType() == impeller::Context::BackendType::kOpenGLES) {
+    // Get the pipeline on the raster thread.
+    auto dart_state = flutter::UIDartState::Current();
+    std::promise<
+        std::shared_ptr<impeller::Pipeline<impeller::PipelineDescriptor>>>
+        pipeline_promise;
+    auto pipeline_future = pipeline_promise.get_future();
+    fml::TaskRunner::RunNowOrPostTask(
+        dart_state->GetTaskRunners().GetRasterTaskRunner(),
+        fml::MakeCopyable([promise = std::move(pipeline_promise),
+                           context = GetContext(), pipeline_desc]() mutable {
+          promise.set_value(
+              context->GetPipelineLibrary()->GetPipeline(pipeline_desc).Get());
+        }));
+    pipeline = pipeline_future.get();
+  } else {
+    pipeline = context.GetPipelineLibrary()->GetPipeline(pipeline_desc).Get();
+  }
+
   FML_DCHECK(pipeline) << "Couldn't resolve render pipeline";
   return pipeline;
 }
```

Next issue is with shader compilation:
```
[ERROR:flutter/impeller/renderer/backend/gles/pipeline_library_gles.cc(74)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to compile vertex shader for '' with error:
ERROR: 0:1: '120' : client/version number not supported

Shader source was:
#version 120
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct FrameInfo
{
    mat4 mvp;
    vec4 color;
};

uniform FrameInfo frame_info;

varying vec4 v_color;
attribute vec2 position;

void main()
{
    v_color = frame_info.color;
    gl_Position = frame_info.mvp * vec4(position, 0.0, 1.0);
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}
```

**Comment by bdero** [comment]
Fixed the shader issues. Now I'm crashing on a div by zero while looping through the uniforms:

![image](https://github.com/user-attachments/assets/5bcc7130-aac9-4025-845e-8224fc0e8917)

**Comment by bdero** [comment]
It was a 1 character typo!

```diff
diff --git a/lib/gpu/shader_library.cc b/lib/gpu/shader_library.cc
index 78d130ca07..ea00f5ba79 100644
--- a/lib/gpu/shader_library.cc
+++ b/lib/gpu/shader_library.cc
@@ -225,7 +221,7 @@ fml::RefPtr<ShaderLibrary> ShaderLibrary::MakeFromFlatbuffer(
                 .byte_length =
                     static_cast<size_t>(struct_member->total_size_in_bytes()),
                 .array_elements =
-                    struct_member->array_elements() != 0
+                    struct_member->array_elements() == 0
                         ? std::optional<size_t>(std::nullopt)
                         : static_cast<size_t>(struct_member->array_elements()),
             });
```

Now the CommandBuffer is failing to submit:
```
The following _Exception was thrown during paint():
Exception: Failed to submit CommandBuffer

The relevant error-causing widget was:
  CustomPaint
  CustomPaint:file:///C:/Users/bdero/projects/flutter/apps/flutter-gpu-examples/lib/triangle.dart:216:9

When the exception was thrown, this was the stack:
#0      CommandBuffer.submit (package:flutter_gpu/src/command_buffer.dart:24:7)
#1      TrianglePainter.paint (package:gputest/triangle.dart:159:19)
```

**Comment by bdero** [comment]
Got it working:
![image](https://github.com/user-attachments/assets/44e4a011-394d-4a1f-aa1a-6402ee848b0d)

But it's crashing with an access violation while binding textures.

**Comment by bdero** [comment]
Okay, got it working. I was feeding the metadata incorrectly.
![image](https://github.com/user-attachments/assets/9eecb67f-a980-4556-8060-b0c947713534)
![image](https://github.com/user-attachments/assets/f34dce08-3503-4564-9945-aee9b3a831dd)

**Comment by jonahwilliams** [comment]
FYI @chinmaygarde
