### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by mimbrown** [flutter/flutter#156325]
### Steps to reproduce

Not sure. Some Navigator error that the framework is telling me to report.

### Expected results

No error, or helpful error

### Actual results

Internal error

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3952 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      NavigatorState.dispose (package:flutter/src/widgets/navigator.dart:3952:12)
navigator.dart:3952
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5826:11)
framework.dart:5826
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
framework.dart:2077
#5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
framework.dart:5669
#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
framework.dart:5669
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
framework.dart:5669
#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
framework.dart:2075
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
framework.dart:5669
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
framework.dart:2073
#17     ListIterable.forEach (dart:_internal/iterable.dart:49:13)
iterable.dart:49
#18     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
framework.dart:2086
#19     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2954:15)
framework.dart:2954
#20     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3264:7)
framework.dart:3264
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
binding.dart:1169
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
binding.dart:1176
#26     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#28     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5
    23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at
      /Users/michaelbrown/fvm/versions/3.24.1
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (7 weeks ago),
      2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices
    (Android SDK version 33.0.1)
    • Android SDK at
      /Users/michaelbrown/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME =
      /Users/michaelbrown/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment
      (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flut
      ter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment
      (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     •
      emulator-5554             • android-arm64  •
      Android 13 (API 33) (emulator)
    • Michael Brown’s iPhone (mobile) •
      00008110-000A558A022BA01E • ios            •
      iOS 17.6.1 21G93
    • macOS (desktop)                 • macos
      • darwin-arm64   • macOS 14.5 23F79
      darwin-arm64
    • Mac Designed for iPad (desktop) •
      mac-designed-for-ipad     • darwin         •
      macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome
      • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @mimbrown, this is typically caused by something triggering navigation when it isn't supposed to. This is likely caused by your code so we will need some code to investigate this. 

Please provide a complete reproducible code sample so that we can properly investigate this. 

Thank you

**Comment by mimbrown** [comment]
Hi @danagbemava-nc, I found issue was a extra call to `Navigation.pop`, it was trying to pop an empty stack. The bug was definitely on my side, but the error message makes it sound like there's a self-assigned need for better error messaging in this case.

Here's a reproduction that produces a similar error message, at least on DartPad (which is totally broken right now?):

```
// Copyright 2019 the Dart project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  initState() {
    Future.delayed(const Duration(seconds: 1), () {
      Navigator.of(context).pop();
      Navigator.of(context).pop();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text(
          'I am about to break',
        ),
      ),
    );
  }
}

```

**Comment by danagbemava-nc** [comment]
Hi @mimbrown, for this case, there was an error that pointed to the issue before the framework exception. Did you see something similar in your application? 

```
E/flutter ( 5956): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter ( 5956): #0      Iterable.lastWhere (dart:core/iterable.dart:734:9)
E/flutter ( 5956): #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5355:40)
E/flutter ( 5956): #2      _MyHomePageState.initState.<anonymous closure> (package:asb/main.dart:42:29)
E/flutter ( 5956): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:431:42)
E/flutter ( 5956): #4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 5956): #5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 5956): #6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 5956): #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
