### ISSUE TITLE
[camera] [API 10+, API 11+]  Samsung S24 crash - reboot phone

### ISSUE THREAD

**Issue by ricardobegar** [flutter/flutter#156345]
### Steps to reproduce

The only thing you have to do is start the camera several times. This also happens on other devices but on the S24 with Android 14 approximately on attempt number 6 the phone crashes. It doesn't crash, not even the app, but the entire phone and it resets.

### Expected results

Do not close the app and even less reboot the phone

### Actual results

The  phone is rebooting on the S24 and on other devices like the Tecno camon 19 pro just close the app

### Code sample

Repo
https://github.com/tyba-co/document_selfie_verification

Steps
- clone repo
- install dependencies
- run example
- take Picture
- Repeat Photo
- take Picture
- Repeat Photo
- take Picture
- Repeat Photo
- take Picture
- Repeat Photo
- take Picture
- Repeat Photo
- take Picture
- Repeat Photo
    

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/187f5a66-c497-4f5d-98bf-1b26704dcf89

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/Camera  (29142): startPreview
I/Camera  (29142): CameraCaptureSession onConfigured
I/Camera  (29142): Updating builder settings
D/Camera  (29142): Updating builder with feature: ExposureLockFeature
D/Camera  (29142): Updating builder with feature: ExposurePointFeature
D/Camera  (29142): Updating builder with feature: ZoomLevelFeature
D/Camera  (29142): Updating builder with feature: AutoFocusFeature
D/Camera  (29142): Updating builder with feature: NoiseReductionFeature
I/Camera  (29142): updateNoiseReduction | currentSetting: fast
D/Camera  (29142): Updating builder with feature: FocusPointFeature
D/Camera  (29142): Updating builder with feature: ResolutionFeature
D/Camera  (29142): Updating builder with feature: SensorOrientationFeature
D/Camera  (29142): Updating builder with feature: FlashFeature
D/Camera  (29142): Updating builder with feature: ExposureOffsetFeature
D/Camera  (29142): Updating builder with feature: FpsRangeFeature
I/Camera  (29142): refreshPreviewCaptureSession
I/CameraManagerGlobal(29142): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.example API Level 2 User Id 0
W/System  (29142): A resource failed to call Surface.release. 
E/System  (29142): Uncaught exception thrown by finalizer
E/System  (29142): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@aa1fe05 rejected from java.util.concurrent.ThreadPoolExecutor@f3cde5a[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 9]
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  (29142):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  (29142):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
E/System  (29142):      at java.lang.Daemons$Daemon.run(Daemons.java:131)
E/System  (29142):      at java.lang.Thread.run(Thread.java:1012)
W/System  (29142): A resource failed to call Surface.release. 
E/System  (29142): Uncaught exception thrown by finalizer
E/System  (29142): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@a896d68 rejected from java.util.concurrent.ThreadPoolExecutor@2497581[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 8]
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  (29142):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  (29142):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
E/System  (29142):      at java.lang.Daemons$Daemon.run(Daemons.java:131)
E/System  (29142):      at java.lang.Thread.run(Thread.java:1012)
W/System  (29142): A resource failed to call Surface.release. 
E/System  (29142): Uncaught exception thrown by finalizer
E/System  (29142): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@24ee267 rejected from java.util.concurrent.ThreadPoolExecutor@73bf814[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 9]
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  (29142):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  (29142):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
E/System  (29142):      at java.lang.Daemons$Daemon.run(Daemons.java:131)
E/System  (29142):      at java.lang.Thread.run(Thread.java:1012)
W/System  (29142): A resource failed to call Surface.release. 
E/System  (29142): Uncaught exception thrown by finalizer
E/System  (29142): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@358deb2 rejected from java.util.concurrent.ThreadPoolExecutor@5d3e03[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 7]
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  (29142):      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  (29142):      at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  (29142):      at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  (29142):      at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
E/System  (29142):      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
E/System  (29142):      at java.lang.Daemons$Daemon.run(Daemons.java:131)
E/System  (29142):      at java.lang.Thread.run(Thread.java:1012)
F/crash_dump64(31960): crash_dump.cpp:554] failed to attach to thread 973: Permission denied
F/crash_dump64(32045): crash_dump.cpp:554] failed to attach to thread 1202: Permission denied
F/crash_dump64(32126): crash_dump.cpp:554] failed to attach to thread 973: Permission denied
F/crash_dump64(32213): crash_dump.cpp:554] failed to attach to thread 1202: Permission denied
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.2 23B92 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Ricardo’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
Based on the error log triggered, it seems similar to https://github.com/flutter/flutter/issues/108941, so please follow-up in it for further updates.
Closing this as a duplicate.
