### ISSUE TITLE
Stocks App in the examples throws errors with --preview-dart-2

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#15632]
Running the stocks app in the examples throws the following runtime errors when using `--preview-dart-2`. The app is fine when not using the preview.

```
E/flutter (  668): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (  668): type 'List' is not a subtype of type 'List<List<String>>' where
E/flutter (  668):   List is from dart:core
E/flutter (  668):   List is from dart:core
E/flutter (  668):   List is from dart:core
E/flutter (  668):   String is from dart:core
E/flutter (  668): 
E/flutter (  668): #0      StockData._fetchNextChunk.<anonymous closure> (file:///Volumes/Mojo/flutter/examples/stocks/lib/stock_data.dart:89:19)
E/flutter (  668): #1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (  668): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (  668): #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (  668): #4      _Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (  668): #5      _Future._completeWithValue (dart:async/future_impl.dart:477:5)
E/flutter (  668): #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
E/flutter (  668): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (  668): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by mraleph** [comment]
I think this is fixed by @chinmaygarde
