### ISSUE TITLE
`SurfaceProducer.Callback` should not fire once the surface is released

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#156434]
While it could be annoyed the client now needs to do manual accounting of the state, which defeats the point of this interface.

This caused (part of) https://github.com/flutter/flutter/issues/156158 where a `dispose`-d `VideoPlayer` still resulted in callback events about `onSurfaceDestroyed`.

**Comment by matanlurey** [comment]
Looking at the code, it should already be doing this - so either it's a more subtle bug, or something else.

**Comment by matanlurey** [comment]
Surprisingly (to me) the test failed! Iterating on this a bit more.

**Comment by matanlurey** [comment]
The bug is actually in `onTrimMemory`, even after a producer is released, it still receives trim memory events!

**Comment by matanlurey** [comment]
Nope, I'm wrong.

**Comment by matanlurey** [comment]
Nope, I'm right:

```txt
FlutterRendererTest > ImageReaderSurfaceProducerUnsubscribesWhenReleased FAILED
    org.mockito.exceptions.verification.NeverWantedButInvoked: 
    callback.onSurfaceDestroyed();
    Never wanted here:
    -> at io.flutter.embedding.engine.renderer.FlutterRendererTest.ImageReaderSurfaceProducerUnsubscribesWhenReleased(FlutterRendererTest.java:798)
    But invoked here:
    -> at io.flutter.embedding.engine.renderer.FlutterRenderer$ImageReaderSurfaceProducer.onTrimMemory(FlutterRenderer.java:701) with arguments: []
        at io.flutter.embedding.engine.renderer.FlutterRendererTest.ImageReaderSurfaceProducerUnsubscribesWhenReleased(FlutterRendererTest.java:798)
```

**Comment by matanlurey** [comment]
1-line fix: there is a memory leak and we accumulate infinite onTrimMemoryListeners.
