### ISSUE TITLE
link libjpeg failed when develop plugin on linux.

### ISSUE THREAD

**Issue by yanshouwang** [flutter/flutter#156480]
### Steps to reproduce

1. Create a linux plugin.
2. Modify the CMakeLists.txt under the linux folder.
3. Include the `libjpeg.h` header and write some codes.
4. Run `flutter build linux -v` under the example. 

### Expected results

The plugin should link the libjpeg and build successfully.

### Actual results

The build process failed.

### Code sample

<details open><summary>Code sample</summary>

``` cmake
# Source include directories and library dependencies. Add any plugin-specific
# dependencies here.
target_include_directories(${PLUGIN_NAME} INTERFACE
  "${CMAKE_CURRENT_SOURCE_DIR}/include")

pkg_check_modules(JPEG REQUIRED IMPORTED_TARGET libjpeg)

target_link_libraries(${PLUGIN_NAME} PRIVATE flutter)
target_link_libraries(${PLUGIN_NAME} PRIVATE PkgConfig::GTK)
target_link_libraries(${PLUGIN_NAME} PRIVATE PkgConfig::JPEG)
```

``` c++
#include <jpeglib.h>

static void test() {
    jpeg_decompress_struct cinfo;
    jpeg_error_mgr jerr;

    cinfo.err = jpeg_std_error(&jerr);
    cinfo.out_color_space = JCS_EXT_RGBX;
    cinfo.output_components = 4;

    jpeg_create_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
yanshouwang@NUC:~/dev/hybrid_sdk/hybrid_v4l2/example$ flutter build linux -v
[  +30 ms] executing: uname -m
[  +12 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +108 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +116 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +110 ms] Skipping pub get: version match.
[ +289 ms] Found plugin hybrid_v4l2 at /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/
[  +70 ms] Found plugin integration_test at /home/yanshouwang/snap/flutter/common/flutter/packages/integration_test/
[ +164 ms] Found plugin hybrid_v4l2 at /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/
[  +43 ms] Found plugin integration_test at /home/yanshouwang/snap/flutter/common/flutter/packages/integration_test/
[ +289 ms] Building Linux application...
[  +59 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux
[ +202 ms] -- The CXX compiler identification is Clang 10.0.0
[   +6 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +218 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[        ] -- Detecting CXX compiler ABI info
[ +237 ms] -- Detecting CXX compiler ABI info - done
[  +24 ms] -- Detecting CXX compile features
[        ] -- Detecting CXX compile features - done
[  +11 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[  +36 ms] --   Found gtk+-3.0, version 3.24.20
[ +161 ms] -- Checking for module 'glib-2.0'
[ +182 ms] --   Found glib-2.0, version 2.64.6
[  +44 ms] -- Checking for module 'gio-2.0'
[  +16 ms] --   Found gio-2.0, version 2.64.6
[ +205 ms] -- The C compiler identification is Clang 10.0.0
[   +2 ms] -- Check for working C compiler: /snap/flutter/current/usr/bin/clang
[ +128 ms] -- Check for working C compiler: /snap/flutter/current/usr/bin/clang -- works
[   +5 ms] -- Detecting C compiler ABI info
[ +159 ms] -- Detecting C compiler ABI info - done
[  +17 ms] -- Detecting C compile features
[        ] -- Detecting C compile features - done
[   +2 ms] -- Checking for module 'libjpeg'
[  +30 ms] --   Found libjpeg, version 2.1.5
[+5086 ms] -- Found Python: /usr/bin/python3 (found version "3.12.3") found components: Interpreter 
[   +2 ms] -- Looking for pthread.h
[ +128 ms] -- Looking for pthread.h - found
[   +1 ms] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
[ +138 ms] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
[   +2 ms] -- Found Threads: TRUE  
[  +10 ms] -- Configuring done
[  +42 ms] -- Generating done
[   +2 ms] -- Build files have been written to: /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/linux/x64/release
[  +46 ms] executing: ninja -C build/linux/x64/release install
[  +15 ms] ninja: Entering directory `build/linux/x64/release'
[ +202 ms] [1/25] Building C object plugins/hybrid_v4l2/shared/CMakeFiles/hybrid_v4l2.dir/hybrid_v4l2.c.o
[  +94 ms] [2/25] Linking C shared library plugins/hybrid_v4l2/shared/libhybrid_v4l2.so
[+2073 ms] [3/25] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ +587 ms] [4/25] Building CXX object _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[+2984 ms] [5/25] Building CXX object _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[+9204 ms] [6/25] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  +52 ms] [7/25] Linking CXX static library lib/libgtest.a
[  +27 ms] [8/25] Linking CXX static library lib/libgmock.a
[  +30 ms] [9/25] Linking CXX static library lib/libgmock_main.a
[        ] [10/25] Linking CXX static library lib/libgtest_main.a
[+16240 ms] [11/25] Generating /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +19 ms] [  +38 ms] executing: uname -m
[        ] [  +16 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [ +228 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +8 ms] [   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +210 ms] Initializing file store
[   +2 ms] [  +70 ms] Skipping target: gen_localizations
[        ] [  +34 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/package_config_subset}
[        ] [  +25 ms] unpack_linux: Starting due to {}
[        ] [ +126 ms] unpack_linux: Complete
[        ] [+1007 ms] Found plugin hybrid_v4l2 at /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/
[        ] [  +79 ms] Found plugin integration_test at /home/yanshouwang/snap/flutter/common/flutter/packages/integration_test/
[   +1 ms] [  +18 ms] gen_dart_plugin_registrant: Complete
[        ] [   +1 ms] kernel_snapshot_program: Starting due to {}
[   +2 ms] [  +26 ms] /home/yanshouwang/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev /home/yanshouwang/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/home/yanshouwang/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --delete-tostring-package-uri=dart:ui --delete-tostring-package-uri=package:flutter --aot
--tfa --target-os linux --packages /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/package_config.json --output-dill /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/program.dill --depfile
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/kernel_snapshot_program.d --verbosity=error package:hybrid_v4l2_example/main.dart
[   +9 ms] [+16503 ms] kernel_snapshot_program: Complete
[        ] [ +565 ms] native_assets: Starting due to {}
[        ] [  +27 ms] No packages with native assets. Skipping native assets compilation.
[        ] [        ] Writing native_assets.yaml.
[   +1 ms] [  +20 ms] Writing /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/native_assets.yaml done.
[        ] [   +2 ms] native_assets: Complete
[   +7 ms] [   +2 ms] kernel_snapshot_native_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/native_assets.yaml,/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/package_config_subset,/home/yanshouwang/snap/flutter/common/flutter/packages/flutter_tools/lib/src/build_sys
tem/targets/common.dart,/home/yanshouwang/snap/flutter/common/flutter/bin/internal/engine.version,/home/yanshouwang/snap/flutter/common/flutter/bin/internal/engine.version,/home/yanshouwang/snap/flutter/common/flutter/bin/internal/engine.version,/home/yanshouwang/snap/flutter/common/flutter/bin/intern
al/engine.version}
[   +4 ms] [   +3 ms] kernel_snapshot_native_assets: Complete
[   +3 ms] [   +1 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/program.dill,/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/native_assets.dill}
[   +6 ms] [  +21 ms] kernel_snapshot: Complete
[   +1 ms] [ +188 ms] aot_elf_release: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/yanshouwang/snap/flutter/common/flutter/packages/flutter_tools/lib/src/build_system/targets/common.dart,/home/yanshouwang/snap/flutter/common/flutter/bin/internal/engine.version,/home/yanshouwang/snap/flutter/common/flutter/bin/internal/engine.version,/home/yanshouwang/snap/flutter/common/flutte
r/bin/internal/engine.version,/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/app.dill}
[   +4 ms] [   +3 ms] targetingApplePlatform = false
[        ] [        ] extractAppleDebugSymbols = true
[   +2 ms] [        ] Will strip AOT snapshot during build.
[  +18 ms] [   +1 ms] executing: /home/yanshouwang/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/app.so --strip /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/app.dill
[   +8 ms] [+9565 ms] aot_elf_release: Complete
[        ] [  +33 ms] linux_aot_bundle: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/.dart_tool/flutter_build/976b0e65d39a9cacbe5e2b39196d660c/app.so}
[   +5 ms] [   +4 ms] linux_aot_bundle: Complete
[        ] [  +33 ms] release_bundle_linux-x64_assets: Starting due to {}
[   +1 ms] [ +156 ms] shaderc command: [/home/yanshouwang/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/impellerc, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr, --sl=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/flutter_assets/shaders/ink_sparkle.frag,
--spirv=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/flutter_assets/shaders/ink_sparkle.frag.spirv, --input=/home/yanshouwang/snap/flutter/common/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/home/yanshouwang/snap/flutter/common/flutter/packages/flutter/lib/src/material/shaders, --include=/home/yanshouwang/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/shader_lib]
[   +7 ms] [ +661 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +50 ms] Persisting file store
[   +1 ms] [  +11 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [  +14 ms] "flutter assemble" took 29,749ms.
[        ] [ +300 ms] ensureAnalyticsSent: 250ms
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [ +260 ms] exiting with code 0
[+1188 ms] [12/25] Building CXX object CMakeFiles/hybrid_v4l2_example.dir/main.cc.o
[ +268 ms] [13/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_api.cc.o
[ +216 ms] [14/25] Building CXX object CMakeFiles/hybrid_v4l2_example.dir/flutter/generated_plugin_registrant.cc.o
[ +290 ms] [15/25] Building CXX object CMakeFiles/hybrid_v4l2_example.dir/my_application.cc.o
[ +315 ms] [16/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_plugin.cc.o
[ +479 ms] [17/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_texture.cc.o
[ +200 ms] [18/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/test/hybrid_v4l2_plugin_test.cc.o
[ +267 ms] [19/25] Linking CXX executable plugins/hybrid_v4l2/hybrid_v4l2_test
[        ] FAILED: plugins/hybrid_v4l2/hybrid_v4l2_test plugins/hybrid_v4l2/hybrid_v4l2_test[1]_tests.cmake 
[  +39 ms] : && /snap/flutter/current/usr/bin/clang++  -O3 -DNDEBUG  -B/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -B/snap/flutter/current/usr/lib/x86_64-linux-gnu -B/snap/flutter/current/lib/x86_64-linux-gnu -B/snap/flutter/current/usr/lib/
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error -luuid -lpthread -ldl -lepoxy -lfontconfig
-B/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -B/snap/flutter/current/usr/lib/x86_64-linux-gnu -B/snap/flutter/current/lib/x86_64-linux-gnu -B/snap/flutter/current/usr/lib/ -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu
-L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error -luuid -lpthread -ldl -lepoxy -lfontconfig plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/test/hybrid_v4l2_plugin_test.cc.o
plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_plugin.cc.o plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_api.cc.o plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_texture.cc.o  -o plugins/hybrid_v4l2/hybrid_v4l2_test
-L/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral -Wl,-rpath,/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/linux/flutter/ephemeral  lib/libgtest_main.a  lib/libgmock.a  -lflutter_linux_gtk  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libharfbuzz.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so  lib/libgtest.a && cd
/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/linux/x64/release/plugins/hybrid_v4l2 && /snap/flutter/145/usr/bin/cmake -D TEST_TARGET=hybrid_v4l2_test -D TEST_EXECUTABLE=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/linux/x64/release/plugins/hybrid_v4l2/hybrid_v4l2_test -D
TEST_EXECUTOR= -D TEST_WORKING_DIR=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/linux/x64/release/plugins/hybrid_v4l2 -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=hybrid_v4l2_test_TESTS -D
CTEST_FILE=/home/yanshouwang/dev/hybrid_sdk/hybrid_v4l2/example/build/linux/x64/release/plugins/hybrid_v4l2/hybrid_v4l2_test[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -P /snap/flutter/145/usr/share/cmake-3.16/Modules/GoogleTestAddTests.cmake
[  +17 ms] /snap/flutter/current/usr/bin/ld: plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_test.dir/hybrid_v4l2_texture.cc.o: in function `hybrid_v4l2_texture_copy_pixels(_FlPixelBufferTexture*, unsigned char const**, unsigned int*, unsigned int*, _GError**)':
[        ] hybrid_v4l2_texture.cc:(.text+0x20d): undefined reference to `jpeg_std_error'
[        ] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x23c): undefined reference to `jpeg_CreateDecompress'
[        ] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x24c): undefined reference to `jpeg_mem_src'
[   +1 ms] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x259): undefined reference to `jpeg_read_header'
[   +1 ms] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x291): undefined reference to `jpeg_start_decompress'
[   +3 ms] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x2eb): undefined reference to `jpeg_read_scanlines'
[        ] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x305): undefined reference to `jpeg_finish_decompress'
[        ] /snap/flutter/current/usr/bin/ld: hybrid_v4l2_texture.cc:(.text+0x339): undefined reference to `jpeg_destroy_decompress'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[  +64 ms] [20/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_plugin.dir/hybrid_v4l2_texture.cc.o
[ +307 ms] [21/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_plugin.dir/hybrid_v4l2_plugin.cc.o
[  +81 ms] [22/25] Building CXX object plugins/hybrid_v4l2/CMakeFiles/hybrid_v4l2_plugin.dir/hybrid_v4l2_api.cc.o
[        ] ninja: build stopped: subcommand failed.
[  +30 ms] Building Linux application... (completed in 42.6s)
[   +3 ms] "flutter linux" took 43,787ms.
[  +65 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +257 ms] ensureAnalyticsSent: 251ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[ +265 ms] exiting with code 1
```

</details>

**Comment by huycozy** [comment]
Hi @yanshouwang 
Can you please provide a complete sample code (maybe a GitHub repository with open-source license) so that I can pull and try running it? 

And please provide the output of `flutter doctor -v`. Thanks!

**Comment by yanshouwang** [comment]
@huycozy Seems the issue is realated to flutter installed with snap store, I fixed this by reinstall flutter use VSCode. But This issue is not exists on  another machine wihch flutter is also installed in snap store.
