### ISSUE TITLE
`Mac_ios microbenchmarks_ios` failing very frequently

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#156506]
The test and its recent runs: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios

Last 3 failed builds:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios/14122/infra
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios/14124/infra
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios/14123/infra

There is no obvious culprit:

- it happens across multiple physical bots
- the first commit (I can see) where it failed seems unrelated: https://github.com/flutter/flutter/pull/156375

**Comment by christopherfujino** [comment]
It appears this was failing due to the daily random seed used for ordering the tests: `225627159`. I'm reducing the priority on this since *today* it is no longer failing, and assigning to @codefu to debug.

**Comment by jtmcdole** [comment]
Yep - this failed locally for me on the first microbenchmark run in the seed (`layout/text_intrinsic_bench.dart`)

**Comment by jason-simmons** [comment]
I was able to reproduce this by:
* patching https://github.com/flutter/flutter/blob/master/dev/benchmarks/microbenchmarks/lib/benchmark_collection.dart to only run the `layout/text_intrinsic_bench.dart` benchmark
* running `lib/benchmark_collection.dart` in release mode on an iPhone 11

The error occurs when two calls to `LiveTestWidgetsFlutterBinding.handleBeginFrame` happen with no `handleDrawFrame` call in between.

```
Bad state: handleBeginFrame() called before previous handleDrawFrame()
 #0      LiveTestWidgetsFlutterBinding.handleBeginFrame (package:flutter_test/src/binding.dart:1788)
 #1      BenchmarkingBinding.handleBeginFrame (package:microbenchmarks/benchmark_binding.dart:15)
 #2      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155)
 #6      _invoke1 (dart:ui/hooks.dart:330)
 #7      PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:405)
 #8      _beginFrame (dart:ui/hooks.dart:272)

```

On my setup that happened due to a race between the `handleBeginFrame` calls made by `WidgetTester.pumpBenchmark` and `handleBeginFrame` calls initiated by the engine in response to system events.

Shortly after launching the benchmark the iOS engine received an event that triggered a call to `updateViewportMetrics`.  This causes the engine to schedule a frame and call `handleBeginFrame` at the next vsync.  If that `handleBeginFrame` happens during a frame interval started by `pumpBenchmark`, then you get the exception above.

@goderbauer Would it make sense for `LiveTestWidgetsFlutterBinding` to be less strict about the interleaving of `handleBeginFrame` and `handleDrawFrame` calls?  The test framework can not assume that it has complete control over frame scheduling.

Instead of throwing,`LiveTestWidgetsFlutterBinding.handleBeginFrame` could warn about an unexpected `handleBeginFrame` and skip the call to the superclass.

**Comment by jtmcdole** [comment]
I'm currently moving to cycle the microbenchmarks from native, with new a FlutterEngine created for each to keep the test time low and try to stabilize the test numbers.
