### ISSUE TITLE
Handler (android.os.Handler) {4fd3eed} sending message to a Handler on a dead thread.

### ISSUE THREAD

**Issue by SmitKmph** [flutter/flutter#156563]
### Steps to reproduce

1. Initialize the video.
2. Go to your mobile home screen and reopen the app 5 to 6 times.
3. In step 2, wait until the video becomes visible each time.

### Expected results

video should play into screen.

### Actual results

Result should video should comes and play into screen

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:resiliency/app/helper/helper.dart';
import 'package:video_player/video_player.dart';

import '../../../utils/app_images.dart';

class GetStartController extends GetxController with WidgetsBindingObserver {
  VideoPlayerController? videoPlayerController;

  @override
  void onInit() {
    super.onInit();
    log("Initializing Video Player");
    initializeVideoPlayer();
    WidgetsBinding.instance.addObserver(this); // Observe app lifecycle
  }

  /// Initializes the video player and plays the video
  void initializeVideoPlayer() {
    try {
      videoPlayerController = VideoPlayerController.asset(
        AppImage.getStart,
        videoPlayerOptions: VideoPlayerOptions(allowBackgroundPlayback: false),
      )
        ..initialize().then((_) {
          log('Video Initialized');
          videoPlayerController?.play();

          update(); // Update UI after initialization
        })
        ..setLooping(true); // Optionally set looping
    } catch (e) {
      printAction("=====>>" + e.toString());
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    log("$state - Pausing Video");

    // Ensure the controller is initialized before handling lifecycle events
    if (videoPlayerController != null && videoPlayerController!.value.isInitialized) {
      if (state == AppLifecycleState.paused) {
        log("App Paused - Pausing Video");
        videoPlayerController?.pause();
      } else if (state == AppLifecycleState.resumed) {
        log("App Resumed - Playing Video");
        videoPlayerController?.play();
      }
    } else if (state == AppLifecycleState.paused) {
      // If the video player was disposed, reinitialize it
      log("App Resumed - Reinitializing Video Player");
      initializeVideoPlayer();
    }
  }

  @override
  void onClose() {
    videoPlayerController?.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.onClose();
  }

  @override
  void dispose() {
    log("Disposing Video Player");
    videoPlayerController?.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}
```

```dart
import 'dart:io';

import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:resiliency/app/common/change_language.dart';
import 'package:resiliency/app/common/common_bottom_sheet.dart';
import 'package:resiliency/app/modules/get_start/views/video_player_screen.dart';
import 'package:resiliency/app/utils/all_imports.dart';
import 'package:responsive_sizer/responsive_sizer.dart';
import 'package:video_player/video_player.dart';

import '../controllers/get_start_controller.dart';

class GetStartView extends GetView<GetStartController> {
  const GetStartView({super.key});

  @override
  Widget build(BuildContext context) {
    TextTheme textTheme = Theme.of(context).textTheme;
    ColorScheme colorScheme = Theme.of(context).colorScheme;
    return GetBuilder(
        init: GetStartController(),
        builder: (context) {
          return Scaffold(
            body: Stack(
              children: [
                Positioned(
                  top: 0,
                  bottom: 0.px,
                  left: 0.px,
                  right: 0.px,
                  child: (controller.videoPlayerController!.value.isInitialized)
                      ? AspectRatio(
                          aspectRatio: controller.videoPlayerController!.value.aspectRatio,
                          child: VideoPlayer(controller.videoPlayerController!),
                        )
                      : const SizedBox(),
                ),
                Positioned.fill(
                  child: /*AppImageAsset(
                  image: AppImage.bording_5,
                  fit: BoxFit.cover,
                ),*/
                      Container(
                    decoration: BoxDecoration(
                      gradient: LinearGradient(colors: [
                        Colors.transparent,
                        Colors.transparent,
                        const Color(0xff181818).withOpacity(0.5),
                        const Color(0xff181818),
                      ], begin: Alignment.topCenter, end: Alignment.bottomCenter),
                    ),
                  ),
                ),
                Positioned.fill(
                  child: SafeArea(
                    child: Column(
                      children: [
                        ChangeLanguage().alignTopLeft.paddingAll(8.px),
                        const Spacer(),
                        Text(
                          AppString.resiliency,
                          style: textTheme.headlineLarge?.copyWith(fontSize: 40.px, fontWeight: FontWeight.w700, color: AppColors.white),
                        ),
                        12.heightBox,
                        Text(
                          AppString.trackEverythingInOnePlace,
                          style: textTheme.bodyLarge?.copyWith(color: AppColors.white),
                        ),
                        100.heightBox,
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Expanded(
                              child: CommonButton(
                                onTap: () {
                                  List social = [
                                    AppImage.ic_Facebook,
                                    AppImage.ic_Google,
                                    if (Platform.isIOS) AppImage.ic_Apple,
                                  ];
                                  showModalBottomSheet(
                                    context: Get.context!,
                                    builder: (context) => CommonBottomSheet(
                                      title: AppString.login,
                                      body: Column(
                                        children: [
                                          24.heightBox,
                                          CommonButton(
                                            onTap: () {
                                              Get.back();
                                              Get.toNamed(Routes.SIGN_IN);
                                            },
                                            child: Row(
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              children: [
                                                AppImageAsset(
                                                  image: AppImage.ic_Mail,
                                                  height: 20.px,
                                                ),
                                                4.widthBox,
                                                Text(
                                                  AppString.continueWithEmail,
                                                  style: textTheme.headlineMedium?.copyWith(color: AppColors.white),
                                                ),
                                              ],
                                            ),
                                          ),
                                          30.heightBox,
                                          Text(
                                            AppString.orContinueWith,
                                            style: textTheme.headlineMedium,
                                          ),
                                          12.heightBox,
                                          Row(
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            children: List.generate(
                                              social.length,
                                              (index) => CircleAvatar(
                                                radius: (56 / 2).px,
                                                backgroundColor: colorScheme.onSurface,
                                                child: Center(
                                                  child: AppImageAsset(
                                                    image: social[index],
                                                    height: 32.px,
                                                  ),
                                                ),
                                              ).paddingSymmetric(horizontal: 8.px),
                                            ),
                                          ),
                                          8.heightBox,
                                        ],
                                      ),
                                    ),
                                  );
                                },
                                color: colorScheme.secondaryContainer,
                                text: AppString.login,
                                textStyle: textTheme.headlineSmall,
                              ),
                            ),
                            12.widthBox,
                            Expanded(
                              child: CommonButton(
                                onTap: () {
                                  List social = [
                                    AppImage.ic_Facebook,
                                    AppImage.ic_Google,
                                    if (Platform.isIOS) AppImage.ic_Apple,
                                  ];
                                  showModalBottomSheet(
                                    context: Get.context!,
                                    builder: (context) => CommonBottomSheet(
                                      title: AppString.signUp,
                                      body: Column(
                                        children: [
                                          24.heightBox,
                                          CommonButton(
                                            onTap: () {
                                              Get.back();

                                              Get.toNamed(Routes.SIGN_UP);
                                            },
                                            child: Row(
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              children: [
                                                AppImageAsset(
                                                  image: AppImage.ic_Mail,
                                                  height: 20.px,
                                                ),
                                                4.widthBox,
                                                Text(
                                                  AppString.continueWithEmail,
                                                  style: textTheme.headlineMedium?.copyWith(color: AppColors.white),
                                                ),
                                              ],
                                            ),
                                          ),
                                          30.heightBox,
                                          Text(
                                            AppString.orContinueWith,
                                            style: textTheme.headlineMedium,
                                          ),
                                          12.heightBox,
                                          Row(
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            children: List.generate(
                                              social.length,
                                              (index) => CircleAvatar(
                                                radius: (56 / 2).px,
                                                backgroundColor: colorScheme.onSurface,
                                                child: Center(
                                                  child: AppImageAsset(
                                                    image: social[index],
                                                    height: 32.px,
                                                  ),
                                                ),
                                              ).paddingSymmetric(horizontal: 8.px),
                                            ),
                                          ),
                                          8.heightBox,
                                        ],
                                      ),
                                    ),
                                  );
                                },
                                text: AppString.signUp,
                              ),
                            ),
                          ],
                        )
                      ],
                    ).paddingAll(16.px),
                  ),
                ),
              ],
            ),
          );
        });
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/e1b4c256-5c77-4edd-87f5-47beae903fe1

</details>

### Logs

<details open><summary>Logs</summary>

```
W/MessageQueue(26497): Handler (android.os.Handler) {4fd3eed} sending message to a Handler on a dead thread
W/MessageQueue(26497): java.lang.IllegalStateException: Handler (android.os.Handler) {4fd3eed} sending message to a Handler on a dead thread
W/MessageQueue(26497): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:574)
W/MessageQueue(26497): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(26497): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(26497): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(26497): 	at android.os.Handler.sendMessage(Handler.java:635)
W/MessageQueue(26497): 	at android.os.Message.sendToTarget(Message.java:481)
W/MessageQueue(26497): 	at androidx.media3.common.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:160)
W/MessageQueue(26497): 	at androidx.media3.exoplayer.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:352)
W/MessageQueue(26497): 	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfoForPlayWhenReadyAndSuppressionReasonStates(ExoPlayerImpl.java:2821)
W/MessageQueue(26497): 	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2804)
W/MessageQueue(26497): 	at androidx.media3.exoplayer.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:833)
W/MessageQueue(26497): 	at androidx.media3.common.BasePlayer.pause(BasePlayer.java:119)
W/MessageQueue(26497): 	at io.flutter.plugins.videoplayer.VideoPlayer.pause(VideoPlayer.java:132)
W/MessageQueue(26497): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.pause(VideoPlayerPlugin.java:187)
W/MessageQueue(26497): 	at io.flutter.plugins.videoplayer.Messages$AndroidVideoPlayerApi$-CC.lambda$setup$9(Messages.java:910)
W/MessageQueue(26497): 	at io.flutter.plugins.videoplayer.Messages$AndroidVideoPlayerApi$$ExternalSyntheticLambda1.onMessage(Unknown Source:2)
W/MessageQueue(26497): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
W/MessageQueue(26497): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
W/MessageQueue(26497): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/MessageQueue(26497): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/MessageQueue(26497): 	at android.os.Handler.handleCallback(Handler.java:942)
W/MessageQueue(26497): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/MessageQueue(26497): 	at android.os.Looper.loopOnce(Looper.java:211)
W/MessageQueue(26497): 	at android.os.Looper.loop(Looper.java:300)
W/MessageQueue(26497): 	at android.app.ActivityThread.main(ActivityThread.java:8348)
W/MessageQueue(26497): 	at java.lang.reflect.Method.invoke(Native Method)
W/MessageQueue(26497): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
W/MessageQueue(26497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
I/ExoPlayerImpl(26497): Init 12c5ea5 [AndroidXMedia3/1.4.1] [miel, 2201117PI, Xiaomi, 33]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This was initially reported in https://github.com/flutter/flutter/issues/156451 and has since been fixed. 

Kindly run `flutter pub upgrade` to upgrade your `video_player_android` version to the latest version. 

Closing since this has already been fixed. If you still face this issue after upgrading to `video_player_android` 2.7.12, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by OnClickListener2048** [comment]
I'm using video_player_android 2.7.12 ,I still get this error

**Comment by danagbemava-nc** [comment]
Kindly subscribe to https://github.com/flutter/flutter/issues/156936 for updates
