### ISSUE TITLE
[engine] Build failure for host_debug_unopt_arm64 on gen/flutter/impeller/fixtures/assets/kernel_blob.bin

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#156575]
When trying to build HHH (engine, dart, framework) on Mac M1 the build fails on:

`FAILED: gen/flutter/impeller/fixtures/assets/kernel_blob.bin`

(It works fine on Linux.)

Am I holding it wrong?
Is using a different Dart build no longer supported in engine builds?

Full log:

```
$ et build -c host_debug_unopt_arm64
[2024-10-11T11:21:12.090][macos/host_debug_unopt_arm64: GN]: OK
[2024-10-11T11:21:13.174][macos/host_debug_unopt_arm64: RBE startup]: Proxy started successfully.
[macos/host_debug_unopt_arm64: ninja] 1.6% (30/1835) CXX o...ller/entity/vk/embed_vk_entity_shaders.entity_shaders_vk.o[2024-10-11 11:21:17.832844][macos/host_debug_unopt_arm64: ninja]: FAILED
COMMAND:
/Users/dacoharkes/flt/engine/src/flutter/third_party/ninja/ninja -C /Users/dacoharkes/flt/engine/src/out/host_debug_unopt_arm64 -j 800
STDOUT:
ninja: Entering directory `/Users/dacoharkes/flt/engine/src/out/host_debug_unopt_arm64'
FAILED: gen/flutter/impeller/fixtures/assets/kernel_blob.bin 
vpython3 ../../build/gn_run_binary.py ../../flutter/prebuilts/macos-arm64/dart-sdk/bin/dartaotruntime /Users/dacoharkes/flt/engine/src/out/host_debug_unopt_arm64/gen/frontend_server_aot.dart.snapshot --packages /Users/dacoharkes/flt/engine/src/flutter/.dart_tool/package_config.json --sdk-root flutter_patched_sdk --target=flutter --depfile gen/flutter/impeller/fixtures/assets/kernel_blob.bin.d --output-dill gen/flutter/impeller/fixtures/assets/kernel_blob.bin ../../flutter/impeller/fixtures/dart_tests.dart
Command failed: ./../../flutter/prebuilts/macos-arm64/dart-sdk/bin/dartaotruntime /Users/dacoharkes/flt/engine/src/out/host_debug_unopt_arm64/gen/frontend_server_aot.dart.snapshot --packages /Users/dacoharkes/flt/engine/src/flutter/.dart_tool/package_config.json --sdk-root flutter_patched_sdk --target=flutter --depfile gen/flutter/impeller/fixtures/assets/kernel_blob.bin.d --output-dill gen/flutter/impeller/fixtures/assets/kernel_blob.bin ../../flutter/impeller/fixtures/dart_tests.dart
exitCode: 255
result 6a7522c1-de79-4a83-94b3-1f3b9ceabf3f
Unhandled exception:
Crash when compiling file:///Users/dacoharkes/flt/engine/src/flutter/impeller/fixtures/dart_tests.dart:
Unexpected Kernel SDK Version b4d5272d99 (expected 3c4726445b).

#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657)
#1      BinaryBuilder._verifyComponentInitialBytes (package:kernel/binary/ast_from_binary.dart:874)
#2      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:697)
#3      Timeline.timeSync (dart:developer/timeline.dart:173)
#4      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695)
#5      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:570)
#6      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:523)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:94)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/base/crash.dart:138)
<asynchronous suspension>
#9      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:60)
<asynchronous suspension>
#10     CompilerContext.clear (package:front_end/src/base/compiler_context.dart:79)
<asynchronous suspension>
#11     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:59)
<asynchronous suspension>
#12     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:44)
<asynchronous suspension>
#13     compileToKernel (package:vm/kernel_front_end.dart:528)
<asynchronous suspension>
#14     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:664)
<asynchronous suspension>
#15     starter (package:frontend_server/starter.dart:109)
<asynchronous suspension>
#16     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

ninja: build stopped: subcommand failed.

STDERR:


[2024-10-11T11:21:18.180][macos/host_debug_unopt_arm64: RBE shutdown]: Actions completed: 3 (3 cache hits)
```

I also have a draconic script locally (not `et`) that does HHH builds, ~~and it fails with the same error~~.

**Comment by mraleph** [comment]
You need to be passing `--no-prebuilt-dart-sdk` _somewhere_ I presume.

**Comment by dcharkes** [comment]
> You need to be passing `--no-prebuilt-dart-sdk` _somewhere_ I presume.

Ah right, my draconic script did that, but I commented that out on Mac due to another error. 🙈

I'll make a PR for `et` to take `--no-prebuilt-dart-sdk` and `--full-dart-sdk` options.

**Comment by dcharkes** [comment]
I'll close this issue as the actual engine build succeeds with the right flags when using a custom dart.
