### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: No space left on device, errno = 28

### ISSUE THREAD

**Issue by taghassan** [flutter/flutter#156674]
## Command
```sh
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: No space left on device, errno = 28
```console
#0      _Directory.createTempSync (dart:io/directory_impl.dart:170:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:28:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:236:46)
#3      ErrorHandlingFileSystem.systemTempDirectory (package:flutter_tools/src/base/error_handling_io.dart:127:31)
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:378:40)
<asynchronous suspension>
#5      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:696:37)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.3, on macOS 14.3 23D56 darwin-x64, locale en-GB)
    [32m•[39m Flutter version 3.24.3 on channel stable at /Volumes/2tb/development/flutter3
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Volumes/2tb/development/Library/Android/sdk
    [32m•[39m Platform android-34-ext8, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Volumes/2tb/development/Library/Android/sdk
    [32m•[39m Java binary at: /Volumes/2tb/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Volumes/2tb/Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [32m•[39m CocoaPods version 1.15.2

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Volumes/2tb/Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /Volumes/2tb/Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[31m[☠][39m Connected device (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m FileSystemException: Creation of temporary directory fail

**Comment by the-best-is-best** [comment]
Check disk free size

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/54213
