### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by abhi-tupparwar** [flutter/flutter#15666]
everytime I run flutter doctor this error pops up help with this issue

crash report:

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for where.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:163)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:41)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:107)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:164)
#6      AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:268)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#9      new Future.sync (dart:async/future.dart:222)
#10     CommandRunner.run (package:args/command_runner.dart:109)
#11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#19     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#21     main (file:///C:/Program%20Files/Git/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for where.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:163)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:41)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:107)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:164)
#6      getAdbPath (package:flutter_tools/src/android/android_sdk.dart:51)
#7      AndroidWorkflow.canListDevices (package:flutter_tools/src/android/android_workflow.dart:31)
#8      AndroidDevices.canListAnything (package:flutter_tools/src/android/android_device.dart:50)
#9      DeviceManager.canListAnything.<anonymous closure> (package:flutter_tools/src/device.dart:99)
#10     Iterable.any (dart:core/iterable.dart:403)
#11     DeviceManager.canListAnything (package:flutter_tools/src/device.dart:99)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:53)
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:111)
<asynchronous suspension>
#14     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#22     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#23     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#25     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#26     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#27     _rootRun (dart:async/zone.dart:1126)
#28     _CustomZone.run (dart:async/zone.dart:1023)
#29     runZoned (dart:async/zone.dart:1501)
#30     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#31     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#32     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#33     main (file:///C:/Program%20Files/Git/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#34     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by anandwana001** [comment]
It seems like you miss some steps while setting up flutter on your machine! 
try out this [link](https://www.youtube.com/playlist?list=PLBbgqtDgdc_RUWUCInIqxpY--C94C6Xjh)

**Comment by abhi-tupparwar** [comment]
did exactly the same it wont work

**Comment by abhi-tupparwar** [comment]
got it up and running needed to " C:\Windows\System32 " to Path variable

**Comment by sakshamsri4** [comment]
I am having the same issue, this issue started after I upgraded my flutter, before that it was working fine.

**Comment by fantania** [comment]
@sakshamsri4  did your issue got resolved? if yes how? Thanks
