### ISSUE TITLE
[iOS ]CameraException(Error -11814, Cannot Record)

### ISSUE THREAD

**Issue by crianpiro** [flutter/flutter#156657]
### Steps to reproduce

Previous reported issue: https://github.com/flutter/flutter/issues/138151 

The error happens when trying to use the camera to take a photo.

The info.plist contains the descriptions for:

```
<key>NSCameraUsageDescription</key>
<string>your usage description here</string>
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>
```

The error is present in the physical device.

By running the code example is reproducible. 

Physical device use iPhone 14 pro (iOS version 17.6.1)

### Expected results

The camera preview is displayed an works without throwing an error.

### Actual results

The camera preview is not initialized because of the exception CameraException(Error -11814, Cannot Record).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Camera project',
      home: CameraView(),
    );
  }
}

class CameraView extends StatefulWidget {
  const CameraView({super.key});

  @override
  State<CameraView> createState() => _CameraViewState();
}

final CameraController controller = CameraController(
    const CameraDescription(name: "Cam", lensDirection: CameraLensDirection.back, sensorOrientation: 0),
    ResolutionPreset.max,
    enableAudio: false,
  );

class _CameraViewState extends State<CameraView> {
  
  @override
  void initState() {
    super.initState();
    controller.initialize().then((_) {
      setState(() {});
    });
  }
  
  @override
  Widget build(BuildContext context) {
    return controller.value.isInitialized? CameraPreview(
      controller,
    ) : const Center(
      child: CircularProgressIndicator(),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![WhatsApp Image 2024-10-12 at 20 10 48](https://github.com/user-attachments/assets/34c3487f-8be1-4fa2-93bf-c76f296bd35a)

<img width="723" alt="image" src="https://github.com/user-attachments/assets/c0c2bb99-df2b-483d-b417-2bf6fdf3e21c">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[   +6 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/arch -arm64e xcrun osascript -l JavaScript /Users/piconc/fvm/versions/3.24.3/packages/flutter_tools/bin/xcode_debug.js check-workspace-opened --xcode-path /Applications/Xcode.app --project-path /Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcodeproj --workspace-path /Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcworkspace --verbose
[ +163 ms] {"status":true,"errorMessage":null,"debugResult":null}

           {"command":"check-workspace-opened","xcodePath":"/Applications/Xcode.app","projectPath":"/Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcodeproj","projectName":null,"expectedConfigurationBuildDir":null,"workspacePath":"/Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcworkspace","targetDestinationId":null,"targetSchemeName":null,"skipBuilding":null,"launchArguments":null,"closeWindowOnStop":null,"promptToSaveBeforeClose":null,"verbose":true}
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun osascript -l JavaScript /Users/piconc/fvm/versions/3.24.3/packages/flutter_tools/bin/xcode_debug.js debug --xcode-path /Applications/Xcode.app --project-path /Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcodeproj --workspace-path /Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcworkspace --project-name Runner --expected-configuration-build-dir /Users/piconc/Development/_Development/camera_not_working/build/ios/iphoneos --device-id 00008120-000A43D82E8BC01E --scheme Runner --skip-building --launch-args ["--enable-dart-profiling"] --verbose
[  +33 ms] stderr: {"command":"debug","xcodePath":"/Applications/Xcode.app","projectPath":"/Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcodeproj","projectName":"Runner","expectedConfigurationBuildDir":"/Users/piconc/Development/_Development/camera_not_working/build/ios/iphoneos","workspacePath":"/Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcworkspace","targetDestinationId":"00008120-000A43D82E8BC01E","targetSchemeName":"Runner","skipBuilding":true,"launchArguments":["--enable-dart-profiling"],"closeWindowOnStop":null,"promptToSaveBeforeClose":null,"verbose":true}
[ +127 ms] stderr: Workspace: /Users/piconc/Development/_Development/camera_not_working/ios/Runner.xcodeproj
[ +134 ms] stderr: Device: My Mac (00006000-001C61AE2191801E)
[ +133 ms] stderr: Device: Andres's iPhone (00008120-000A43D82E8BC01E)
[+1221 ms] stderr: CONFIGURATION_BUILD_DIR: /Users/piconc/Development/_Development/camera_not_working/build/ios/iphoneos
[  +40 ms] stderr: Action result status: not yet started
[ +515 ms] {"status":true,"errorMessage":null,"debugResult":{"completed":false,"status":"running","errorMessage":null}}
[   +1 ms] Application launched on the device. Waiting for Dart VM Service url.
[   +2 ms] Checking for advertised Dart VM Services...
[+2214 ms] VM Service URL on device: http://127.0.0.1:60714/OTqin3xrow4=/
[   +2 ms] Attempting to forward device port 60714 to host port 57561
[        ] executing: /Users/piconc/fvm/versions/3.24.3/bin/cache/artifacts/usbmuxd/iproxy 57561:60714 --udid 00008120-000A43D82E8BC01E --debug
[ +817 ms] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(Error -11814, Cannot Record)
[        ] #0      AVFoundationCamera.createCameraWithSettings (package:camera_avfoundation/src/avfoundation_camera.dart:108:7)
[        ] <asynchronous suspension>
[        ] #1      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:344:19)
[        ] <asynchronous suspension>
[        ] #2      _CameraViewState.initState.<anonymous closure> (package:camera_not_working/main.dart:38:34)
[        ] <asynchronous suspension>
[  +92 ms] Checking for available port on camera.notworking.example._dartVmService._tcp.local
[   +1 ms] Checking for authentication code for camera.notworking.example._dartVmService._tcp.local
[   +2 ms] Attempting to forward device port 60714 to host port 57588
[        ] executing: /Users/piconc/fvm/versions/3.24.3/bin/cache/artifacts/usbmuxd/iproxy 57588:60714 --udid 00008120-000A43D82E8BC01E --debug
[  +92 ms] Forwarded port ForwardedPort HOST:57561 to DEVICE:60714
[        ] Forwarded host port 57561 to device port 60714 for VM Service
[        ] Installing and launching... (completed in 6.5s)


----------------------------------------


[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(Error -11814, Cannot Record)
#0      AVFoundationCamera.createCameraWithSettings (package:camera_avfoundation/src/avfoundation_camera.dart:108:7)
avfoundation_camera.dart:108
<asynchronous suspension>
#1      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:344:19)
camera_controller.dart:344
<asynchronous suspension>
#2      _CameraViewState.initState.<anonymous closure> (package:camera_not_working/main.dart:38:34)
main.dart:38
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-CO)
    • Flutter version 3.24.3 on channel stable at /Users/piconc/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/piconc/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.94.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • Cristian Picon’s iPad (mobile)  • 00008103-000A653C3C68A01E • ios            • iOS 17.6.1 21G93
    • Andres's iPhone (mobile)        • 00008120-000A43D82E8BC01E • ios            • iOS 17.6.1 21G93
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 129.0.6668.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @crianpiro, what version of `camera` & `camera_avfoundation` are you using? Just out of curiosity, do you still experience this issue with the camera example app?

**Comment by crianpiro** [comment]
Hello @danagbemava-nc I am using camera: ^0.11.0+2 but not avfoundation and I tested it in a new flutter project besides of the project I was working on.

**Comment by danagbemava-nc** [comment]
Hi @crianpiro, `camera_avfoundation` is a dependency of `camera` so it should be in your `pubspec.lock`. 
Are you only seeing this on the iPhone 14 Pro? 

> I tested it in a new flutter project besides of the project I was working on.

I'm asking if you can reproduce with the camera example because the camera example selects or allows you to select a camera to use, your code sample doesn't appear to be doing that so perhaps a camera is being selected which the plugin may not yet have support for

**Comment by crianpiro** [comment]
Hello @danagbemava-nc , thanks for clarifying. Checking the camera example I realized the CameraDescription is not an object to be created but to be obtained from the device. After selecting one of the cameras provided from the `availableCameras` method it works as expected.

Thank you so much for your time.
