### ISSUE TITLE
When closing Chrome at the end of `flutter run --machine`: `WebSocketException: Connection to 'http://localhost55388/devtools/page/8B8BA1FC234B2A5EBF0770CE0DA9255E#' was not upgraded to websocket`

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#156700]
Since 3.24.0

Command: `flutter run` (mostly with `--machine`)

Represents about 1% on crashes on 3.24.3 (which has ~1% of users experiencing crashes)

There are a couple of other stack traces, but 96% of them looked like this:

```
WebSocketException: WebSocketException: Connection to 'http://localhost:55388/devtools/page/8B8BA1FC234B2A5EBF0770CE0DA9255E#' was not upgraded to websocket
at _WebSocketImpl.connect(websocket_impl.dart:1011)
at WebSocket.connect(websocket.dart:320)
at WipConnection.connect(webkit_inspection_protocol.dart:231)
at ChromeTab.connect(webkit_inspection_protocol.dart:184)
at Chromium.close(chrome.dart:515)
at <asynchronous gap>(async)
at ChromiumDevice.stopApp(web_device.dart:164)
at <asynchronous gap>(async)
at ResidentWebRunner._cleanup(resident_web_runner.dart:203)
at <asynchronous gap>(async)
at ResidentWebRunner.cleanupAtFinish(resident_web_runner.dart:191)
at <asynchronous gap>(async)
at ResidentRunner.waitForAppToFinish(resident_runner.dart:1482)
at <asynchronous gap>(async)
at RunCommand.runCommand(run.dart:788)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1408)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:212)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:420)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:364)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:130)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:153)
at <asynchronous gap>(async)
at main(executable.dart:93)
at <asynchronous gap>(async)
```

**Comment by andrewkolos** [comment]
> Command: `flutter run` (mostly with `--machine`)

It looks like when running a Flutter app with Visual Studio Code and stopping it (e.g. clicking the "Stop Debugging" button), this code (`ChromiumDevice.stopApp`) is called twice. I wonder if this is why this crash occurs much more often with `--machine`.

**Comment by andrewkolos** [comment]
It also looks like `Chrome.close` is called twice when quitting via pressing `q` at the end of `flutter run`. Anyway, I inserted `print(StackTrace.current)` at the beginning of `Chrome.close` and this is what I see when running and stopping an app:

<details>

<summary> From CLI (`flutter run` then pressing `q`) </summary>

```
#0      Chromium.close (package:flutter_tools/src/web/chrome.dart:512:22)
#1      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:163:20)
#2      FlutterDevice.exitApps (package:flutter_tools/src/resident_runner.dart:370:19)
#3      ResidentWebRunner.exitApp (package:flutter_tools/src/isolated/resident_web_runner.dart:735:19)
#4      ResidentRunner.exit (package:flutter_tools/src/resident_runner.dart:1271:11)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1728:9)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1787:7)
<asynchronous suspension>

#0      Chromium.close (package:flutter_tools/src/web/chrome.dart:512:22)
#1      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:163:20)
#2      ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:201:27)
<asynchronous suspension>
#3      ResidentWebRunner._cleanupAndExit (package:flutter_tools/src/isolated/resident_web_runner.dart:215:5)
<asynchronous suspension>
#4      Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:895:56)
<asynchronous suspension>
```

</details>

<details>

<summary> from VSCode </summary>

```
#0      Chromium.close (package:flutter_tools/src/web/chrome.dart:512:22)
#1      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:163:20)
#2      FlutterDevice.exitApps (package:flutter_tools/src/resident_runner.dart:370:19)
#3      ResidentWebRunner.exitApp (package:flutter_tools/src/isolated/resident_web_runner.dart:735:19)
#4      ResidentRunner.exit (package:flutter_tools/src/resident_runner.dart:1271:11)
<asynchronous suspension>
#5      AppDomain.stop.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:936:7)
<asynchronous suspension>
#6      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:297:22)
<asynchronous suspension>

#0      Chromium.close (package:flutter_tools/src/web/chrome.dart:512:22)
#1      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:163:20)
#2      ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:201:27)
<asynchronous suspension>
#3      ResidentWebRunner._cleanupAndExit (package:flutter_tools/src/isolated/resident_web_runner.dart:215:5)
<asynchronous suspension>
#4      Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:895:56)
<asynchronous suspension>
```

</details>

This was on c083cbcf8964cc097d6419beb8ba5d4137e32f40

**Comment by andrewkolos** [comment]
As an experiment, I tried to remove the code that initiates cleanup upon the dev fs disconnecting:

https://github.com/flutter/flutter/blob/a8528c70b65da8f05790c7763d4a8247d5ddb17e/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L633

When doing this, yet another route to stopping at the app appears:

```
#0      Chromium.close (package:flutter_tools/src/web/chrome.dart:512:22)
#1      ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:163:20)
#2      ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:201:27)
<asynchronous suspension>
#3      ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:188:5)
<asynchronous suspension>
#4      ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1436:5)
<asynchronous suspension>
#5      ResidentWebRunner.attach (package:flutter_tools/src/isolated/resident_web_runner.dart:724:7)
<asynchronous suspension>
#6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

**Comment by andrewkolos** [comment]
In summary, when the user stops their app (e.g. presses `q`), there is code to stop the app on the device, but there are also listeners that are tripped by the app stopping that then try to clean up (which includes trying to stop the app).

**Comment by andrewkolos** [comment]
Looks like this logic stems from https://github.com/flutter/flutter/commit/0f8b8c91a3d8fa3b4182ab71144b88672c9f9a1b. The idea is that when the browser disconnects (e.g. the tab is closed), we should shut down the resident runner. However, the resident runner shutdown logic also includes a call to close the browser.
