### ISSUE TITLE
Issues with TwoDimensionalScrollView, DiagonalDragBehavior.free and AbsorbPointer

### ISSUE THREAD

**Issue by jonaslundquist** [flutter/flutter#156711]
### Steps to reproduce

1. Clone the repo at https://github.com/jonaslundquist/absorb_pointer_question
2. Run on iOS Simulator
3. Perform a pinch/spread gesture

We need to do it this way with `Listener` and `AbsorbPointer`, because `GestureDetector#onScaleXXX` does not fire when `DiagonalDragBehavior` is `free`. This is also possibly a bug? We're not sure about the expected behavior here.

### Expected results

No error logs

### Actual results

Error:

```
======== Exception caught by gesture ===============================================================
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _VerticalOuterDimensionState.horizontalScrollable (package:flutter/src/widgets/scrollable.dart:2095:109)
#1      _VerticalOuterDimensionState._handleDragCancel (package:flutter/src/widgets/scrollable.dart:2265:9)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
#3      DragGestureRecognizer._checkCancel (package:flutter/src/gestures/monodrag.dart:842:7)
#4      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:702:9)
#5      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:538:9)
#6      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:714:5)
#7      DragGestureRecognizer.rejectGesture (package:flutter/src/gestures/monodrag.dart:690:5)
#8      GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:240:16)
#9      GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:55:12)
#10     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:451:13)
#11     OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:469:5)
#12     DragGestureRecognizer.dispose (package:flutter/src/gestures/monodrag.dart:849:11)
#13     RawGestureDetectorState.dispose (package:flutter/src/widgets/gesture_detector.dart:1486:18)
#14     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5826:11)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6998:16)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#118    ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#119    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
#120    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2954:15)
#121    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3264:7)
#122    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
#123    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#124    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#125    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#126    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#127    _invoke (dart:ui/hooks.dart:312:13)
#128    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#129    _drawFrame (dart:ui/hooks.dart:283:31)
Handler: "onCancel"
Recognizer: PanGestureRecognizer#f1d7f
  start behavior: start
====================================================================================================
```

### Code sample

See repo above.

### Logs

<details open><summary>Logs</summary>

```console
Performing hot restart...
Syncing files to device iPhone 15...
Restarted application in 338ms.

======== Exception caught by gesture ===============================================================
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _VerticalOuterDimensionState.horizontalScrollable (package:flutter/src/widgets/scrollable.dart:2095:109)
#1      _VerticalOuterDimensionState._handleDragCancel (package:flutter/src/widgets/scrollable.dart:2265:9)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
#3      DragGestureRecognizer._checkCancel (package:flutter/src/gestures/monodrag.dart:842:7)
#4      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:702:9)
#5      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:538:9)
#6      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:714:5)
#7      DragGestureRecognizer.rejectGesture (package:flutter/src/gestures/monodrag.dart:690:5)
#8      GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:240:16)
#9      GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:55:12)
#10     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:451:13)
#11     OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:469:5)
#12     DragGestureRecognizer.dispose (package:flutter/src/gestures/monodrag.dart:849:11)
#13     RawGestureDetectorState.dispose (package:flutter/src/widgets/gesture_detector.dart:1486:18)
#14     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5826:11)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2077:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6998:16)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5669:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2075:7)
#116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6886:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2073:13)
#118    ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#119    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2086:25)
#120    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2954:15)
#121    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3264:7)
#122    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
#123    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#124    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#125    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#126    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#127    _invoke (dart:ui/hooks.dart:312:13)
#128    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#129    _drawFrame (dart:ui/hooks.dart:283:31)
Handler: "onCancel"
Recognizer: PanGestureRecognizer#f1d7f
  start behavior: start
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.1.1 23B81 darwin-arm64, locale en-SE)
    • Flutter version 3.24.3 on channel stable at /Users/jonaslundquist/.asdf/installs/flutter/3.24.3-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jonaslundquist/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/jonaslundquist/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 (mobile)              • 6A190504-1078-4AF8-8B5B-37CF50A39A1C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.91
    ! Error: Browsing on the local area network for Jonas’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Thanks for your detailed report! I also observe this issue on Flutter `Channel master, 3.27.0-1.0.pre.45`.

**Comment by Piinks** [comment]
TwoDimensionalScrollView does not currently support a pinch or spread gesture to scale. That feature request is being tracked in https://github.com/flutter/flutter/issues/156142. Closing as a duplicate, please subscribe to the other issue for updates.
