### ISSUE TITLE
Unable to load large assets as string with dart 2 preview

### ISSUE THREAD

**Issue by simolus3** [flutter/flutter#15694]
When including large assets files, trying to load those as a string with the dart 2 preview turned on will crash the app in debug mode and throw an dart error in release builds. If one is not supposed to use `loadString` in these scenarios, I believe that this should be documented and still not crash the app.
## Steps to Reproduce

Create a new Flutter project with `flutter create test_asset_bug`. Include a large file as a resource (I have been using [this one](https://www.lottiefiles.com/download_public/72)):
```yaml
  assets:
    - data.json
```
Now, trying to load the file as a string via the DefaultAssetBundle will fail:
```dart
void _incrementCounter() {
    DefaultAssetBundle.of(context).loadString("data.json");

    setState(() {
      // This call to setState tells the Flutter framework that something has
//[...]
```
After starting the app with `flutter run --preview-dart-2`, pressing on the button will crash the app with this error:
```
Revision: '0'
ABI: 'arm'
pid: 14092, tid: 14142, name: ui_thread  >>> com.example.testassetbug <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    r0 00000000  r1 00000000  r2 40509190  r3 00000001
    r4 00000000  r5 73200000  r6 00000047  r7 00000000
    r8 512e1748  r9 00000000  sl 512a1380  fp 516fcc00
    ip 00000001  sp 730c0688  lr 0000000d  pc 417b8c34  cpsr 600f0030
backtrace:
    #00 pc 00061c34  /system/lib/libc.so (je_huge_salloc+7)
    #01 pc 0006599b  /system/lib/libc.so (ifree+246)
    #02 pc 00065d33  /system/lib/libc.so (je_free+70)
    #03 pc 000a2d55  /data/app/com.example.testassetbug-1/lib/arm/libflutter.so
    #04 pc 003b2cfb  /data/app/com.example.testassetbug-1/lib/arm/libflutter.so
    #05 pc 0056d2ef  /data/app/com.example.testassetbug-1/lib/arm/libflutter.so
    #06 pc 0056d225  /data/app/com.example.testassetbug-1/lib/arm/libflutter.so
    #07 pc 004c335d  /data/app/com.example.testassetbug-1/lib/arm/libflutter.so
    #08 pc 00047cb3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
    #09 pc 00019dcd  /system/lib/libc.so (__start_thread+6)
Lost connection to device.
```

With `flutter run --preview-dart-2 --release`, this following error will be thrown. The Future returned by `loadString(...)` will then resolve to `null`.
```
I/FlutterActivityDelegate(14264): onResume setting current activity to this
E/flutter (14264): [ERROR:flutter/runtime/dart_init.cc(167)] Isolate (948568864) 'flutter_assets:_spawn()' exited with an error
E/flutter (14264): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (14264): type '(ByteData) => String' is not a subtype of type '(dynamic) => dynamic'
E/flutter (14264): #0      _spawn.<anonymous closure> (package:flutter/src/foundation/isolates.dart:0)
E/flutter (14264): #1      Timeline.timeSync (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/developer/timeline.dart:168)
E/flutter (14264): #2      _spawn (package:flutter/src/foundation/isolates.dart:91)
E/flutter (14264): #3      _startIsolate.<anonymous closure> (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/runtime/lib/isolate_patch.dart:282)
E/flutter (14264): #4      _RawReceivePortImpl._handleMessage (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/runtime/lib/isolate_patch.dart:165)
Application finished.
```
Running the app without the dart2 preview will work fine with both the release and the debug configuration. Trying to load smaller files (I tried including the autogenerated README.md) will not result in an error, neither does loading large files with `load` instead of `loadString`.

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale de_DE.UTF-8)
    • Flutter version 0.1.5 at /home/simon/bin/flutter
    • Framework revision 3ea4d06340 (vor 4 Wochen), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /home/simon/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /home/simon/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/simon/bin/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.21.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.10.0

[✓] Connected devices (1 available)
    • GT I9300 • 32305bd8f5c48001 • android-arm • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by jason-simmons** [comment]
This is reproducible in the beta release (https://github.com/flutter/flutter/commit/3ea4d06340a97a1e9d7cae97567c64e0569dcaa2) but no longer occurs on the master branch
