### ISSUE TITLE
Flutter throws an Exception when changing LifeCycle state from inactive to paused and vice versa causing app crash in production

### ISSUE THREAD

**Issue by mohammadamini-tooti** [flutter/flutter#156937]
### Steps to reproduce

To reproduce you can use image cropper after calling image picker while you have implemented app life cycle listening logic in your app.

Below is the exception I get:

```console
════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Invalid state transition from AppLifecycleState.inactive to AppLifecycleState.paused
'package:flutter/src/widgets/app_lifecycle_listener.dart':
Failed assertion: line 250 pos 16: 'previousState == null || previousState == AppLifecycleState.hidden'
```

### Expected results

Ideally, the state should not transition form InActive to Paused when you open image cropper.

### Actual results

But right now, Flutter emits inActive state when you open image picker and then emits paused state when image cropper is opened.

### Code sample

<details open><summary>Code sample</summary>

```dart
class TemplateHome extends StatefulWidget {
  static const String path = '/home';
  final int index;

  const TemplateHome({
    super.key,
    this.index = 0,
  });

  @override
  State<TemplateHome> createState() => _TemplateHomeState();
}

class _TemplateHomeState extends State<TemplateHome>
    with WidgetsBindingObserver {
  late AppLifecycleListener _listener;
  late int _currentIndex;
  late PageController _pageController;
  AppLifecycleState? _previousState;

  final items = [
    const ScreenHome(),
    const ScreenReels(),
    const ScreenExplore(),
    const ScreenProfile(),
  ];

  @override
  void initState() {
    super.initState();
    setUserActive();

    _currentIndex = widget.index;
    _pageController = PageController(initialPage: _currentIndex);

    _listener = AppLifecycleListener(onStateChange: onStateChanged);
  }

  @override
  void dispose() {
    _pageController.dispose();
    _listener.dispose();
    super.dispose();
  }

  void onStateChanged(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.detached:
        onDetached();
        break;
      case AppLifecycleState.resumed:
        onResumed();
        break;
      case AppLifecycleState.inactive:
        onInactive();
        break;
      case AppLifecycleState.paused:
        onPaused();
        break;
      case AppLifecycleState.hidden:
        onHidden();
        break;
      default:
        debugPrint('Unexpected state: $state');
    }
  }

  Future setUserActive() async {
    // Set user status to active
  }

  Future setUserInActive() async {
    // Set user status to in-active
  }

  void onDetached() async => await setUserInActive();
  void onResumed() async => await setUserActive();
  void onInactive() async => await setUserInActive();
  void onHidden() async => await setUserActive();
  void onPaused() async => await setUserInActive();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: _pageController,
        children: items,
        onPageChanged: (index) {
          setState(() {
            _currentIndex = index;
          });
        },
      ),
      bottomNavigationBar: TootiBottomNavbar(
        currentIndex: _currentIndex,
        onTap: onTap,
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
D/EGL_emulation(29070): app_time_stats: avg=22.99ms min=14.61ms max=31.17ms count=18
D/ffmpeg-kit-flutter(29070): selectDocument completed with requestCode: 2342, resultCode: -1, data: Intent { dat=content://media/... flg=0x41 clip={image/* video/* {U(content)}} }.
I/ffmpeg-kit-flutter(29070): FFmpegKitFlutterPlugin ignored unsupported activity result for requestCode: 2342.
2
I/flutter (29070): [🌎 Easy Localization] [WARNING] Localization key [profileCropPage.title] not found
D/BitmapWorkerTask(29070): Uri scheme: file
D/TransformImageView(29070): Image size: [390:280]
W/View    (29070): requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{9d90069 V.ED..... ......ID 624,30-719,83 #7f0a02e9 app:id/text_view_scale} during layout: running second layout pass
D/EGL_emulation(29070): app_time_stats: avg=31.99ms min=20.59ms max=49.74ms count=16
D/VRI[MainActivity](29070): visibilityChanged oldVisibility=true newVisibility=false
I/PLogger (29070): {adapter}  {system service}  {SystemChannels.lifecycle.MessageHandler, AppLifecycleState.paused}  {16/10/2024 12:11:05}  {INFO}
I/PLogger (29070): {adapter}  {system service}  {app lifecycle state:AppLifecycleState.paused}  {16/10/2024 12:11:05}  {INFO}
I/PLogger (29070): {call-invitation}  {isolate guard}  {app life style:AppLifecycleState.paused}  {16/10/2024 12:11:05}  {INFO}

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown during a platform message callback:
Invalid state transition from AppLifecycleState.inactive to AppLifecycleState.paused
'package:flutter/src/widgets/app_lifecycle_listener.dart':
Failed assertion: line 250 pos 16: 'previousState == null || previousState == AppLifecycleState.hidden'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AppLifecycleListener.didChangeAppLifecycleState (package:flutter/src/widgets/app_lifecycle_listener.dart:250:16)
app_lifecycle_listener.dart:250
#3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:963:16)
binding.dart:963
#4      ZegoSystemService.initSystemService.<anonymous closure> (package:zego_plugin_adapter/src/services/system.dart:40:31)
system.dart:40
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
platform_channel.dart:235
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:35)
binding.dart:618
#7      _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#8      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#9      _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#10     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
channel_buffers.dart:343
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
platform_dispatcher.dart:750
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
hooks.dart:257
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-45-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @mohammadamini-tooti 
The given sample code is incomplete and seems to use 3rd packages. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

**Comment by mohammadamini-tooti** [comment]
The application is very big and I can't send all the code. BTW, the error occurs because of how the app transitions between image picker and image cropper so I can't reproduce the issue without using the 3rd party package.

**Comment by huycozy** [comment]
Please refrain from sharing the project source code as it is quite complex to look into. I'm not aware of which image cropper plugin you are using or how it works. It would be better for further investigation if you could find a way to replicate the issue without relying on it. In case you can't find a way, you can share a runnable **sample code** to illustrate the issue only (remove unrelated code to the issue) in a `main.dart` file and share it here.

If the issue is solved on your end, please feel free to close it.

**Comment by mohammadamini-tooti** [comment]
I am closing the issue as I was able to solve it using other methods and I'm also not able to provide the runnable code right now.
