### ISSUE TITLE
Gradle throws an exception when launching/generating the app

### ISSUE THREAD

**Issue by qucals** [flutter/flutter#156901]
### Steps to reproduce

1. flutter create bug
2. flutter run for android

### Expected results

Launch the app or build it for Android.

### Actual results

Exception when launching the app.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[  +16 ms] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +74 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +37 ms] List of devices attached
           emulator-5554          device product:sdk_gphone64_x86_64 model:sdk_gphone64_x86_64 device:emu64xa
           transport_id:1
[   +9 ms] /opt/android-sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +27 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] Skipping pub get: version match.
[ +112 ms] Generating
/home/totalboy/projects/flutter/flweb/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +50 ms] ro.hardware = ranchu
[  +87 ms] No packages with native assets. Skipping native assets compilation.
[   +2 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs
have updated contents: /home/totalboy/projects/flutter/flweb/.dart_tool/package_config_subset}
[  +35 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +6 ms] Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
[   +4 ms] /home/totalboy/projects/.flutter-sdk/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev
/home/totalboy/projects/.flutter-sdk/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot
--sdk-root /home/totalboy/projects/.flutter-sdk/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --experimental-emit-debug-metadata --output-dill
/tmp/flutter_tools.HEYDEJ/flutter_tool.AEVMWH/app.dill --packages
/home/totalboy/projects/flutter/flweb/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/cache.dill.track.dill --verbosity=error --enable-experiment=alternative-invalidation-strategy
[   +9 ms] executing: /opt/android-sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +9 ms] <- compile package:flweb/main.dart
[  +68 ms] --------- beginning of main
           10-15 21:48:44.784 I/BugleRcsEngine( 4257): No RCS Configuration was found in Bugle for simID:
           redacted-pii:sim_id[chars:20,last3:897] [CONTEXT log_prefix="ProvisioningEngineDataRetriever"
           thread_id=82 ]
[  +12 ms] executing: /opt/android-sdk/platform-tools/adb version
[   +9 ms] Android Debug Bridge version 1.0.41
           Version 35.0.2-12147458
           Installed as /opt/android-sdk/platform-tools/adb
           Running on Linux 6.11.3-arch1-1 (x86_64)
[   +1 ms] executing: /opt/android-sdk/platform-tools/adb start-server
[   +8 ms] Building APK
[   +9 ms] executing: /opt/android-studio/jbr/bin/java -version
[ +101 ms] Exit code 0 from: /opt/android-studio/jbr/bin/java -version
[        ] openjdk version "21.0.3" 2024-04-16
           OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
           OpenJDK 64-Bit Server VM (build 21.0.3+-12282718-b509.11, mixed mode)
[   +9 ms] executing: /opt/android-studio/jbr/bin/java --version
[  +88 ms] Exit code 0 from: /opt/android-studio/jbr/bin/java --version
[        ] openjdk 21.0.3 2024-04-16
           OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
           OpenJDK 64-Bit Server VM (build 21.0.3+-12282718-b509.11, mixed mode)
[   +2 ms] Version of Java is different than impacted version, no migration attempted.
[  +32 ms] Using gradle from /home/totalboy/projects/flutter/flweb/android/gradlew.
[   +8 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] executing: [/home/totalboy/projects/flutter/flweb/android/]
/home/totalboy/projects/flutter/flweb/android/gradlew --full-stacktrace --info -Pverbose=true
-Ptarget-platform=android-x64 -Ptarget=/home/totalboy/projects/flutter/flweb/lib/main.dart
-Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +569 ms] Initialized native services in: /home/totalboy/.gradle/native
[        ] Initialized jansi services in: /home/totalboy/.gradle/native
[ +116 ms] Received JVM installation metadata from '/opt/android-studio/jbr': {JAVA_HOME=/opt/android-studio/jbr,
JAVA_VERSION=21.0.3, JAVA_VENDOR=JetBrains s.r.o., RUNTIME_NAME=OpenJDK Runtime Environment,
RUNTIME_VERSION=21.0.3+-12282718-b509.11, VM_NAME=OpenJDK 64-Bit Server VM, VM_VERSION=21.0.3+-12282718-b509.11,
VM_VENDOR=JetBrains s.r.o., OS_ARCH=amd64}
[ +199 ms] Found daemon DaemonInfo{pid=93440, address=[657d3b46-4bff-4685-a6d8-99e531364763 port:44539,
addresses:[/127.0.0.1]], state=Idle, lastBusy=1726249590103,
context=DefaultDaemonContext[uid=b0ac8b92-0ae7-41c5-a336-10f02aa8f210,javaHome=/usr/lib/jvm/java-11-openjdk,javaVers
ion=11,javaVendor=Arch
Linux,daemonRegistryDir=/home/totalboy/.gradle/daemon,pid=93440,idleTimeout=10800000,priority=NORMAL,applyInstrument
ationAgent=true,nativeServicesMode=ENABLED,daemonOpts=--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.b
ase/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=
ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.
javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED
,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryE
rror,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=RU,-Duser.language=ru,-Duser.variant]} however its
context does not match the desired criteria.
[   +1 ms] JVM is incompatible.
[        ] Wanted: DaemonRequestContext{jvmCriteria=/opt/android-studio/jbr (no JDK specified, using current Java
home), daemonOpts=[-XX:MaxMetaspaceSize=2G, -XX:+HeapDumpOnOutOfMemoryError,
--add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED,
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED, --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=java.base/java.nio.charset=ALL-UNNAMED,
--add-opens=java.base/java.net=ALL-UNNAMED, --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED, -Xmx4G,
-Dfile.encoding=UTF-8, -Duser.country=RU, -Duser.language=ru, -Duser.variant], applyInstrumentationAgent=true,
nativeServicesMode=ENABLED, priority=NORMAL}
[   +1 ms] Actual:
DefaultDaemonContext[uid=b0ac8b92-0ae7-41c5-a336-10f02aa8f210,javaHome=/usr/lib/jvm/java-11-openjdk,javaVersion=11,j
avaVendor=Arch
Linux,daemonRegistryDir=/home/totalboy/.gradle/daemon,pid=93440,idleTimeout=10800000,priority=NORMAL,applyInstrument
ationAgent=true,nativeServicesMode=ENABLED,daemonOpts=--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.b
ase/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=
ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-exports=jdk.compiler/com.sun.tools.
javac.util=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED
,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryE
rror,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=RU,-Duser.language=ru,-Duser.variant]
[   +1 ms]   Looking for a different daemon...
[        ] The client will now receive all logging from the daemon (pid: 22145). The daemon log file:
/home/totalboy/.gradle/daemon/8.10.1/daemon-22145.out.log
[        ] Starting 8th build in daemon [uptime: 47 mins 10.741 secs, performance: 98%, GC rate: 0.00/s, heap usage:
0% of 4 GiB, non-heap usage: 2% of 2 GiB]
[        ] Using 16 worker leases.
[        ] Now considering [/home/totalboy/projects/flutter/flweb/android] as hierarchies to watch
[        ] Watching the file system is configured to be enabled if available
[        ] File system watching is active
[        ] Starting Build
[        ] Now considering [/home/totalboy/projects/.flutter-sdk/flutter/packages/flutter_tools/gradle,
/home/totalboy/projects/flutter/flweb/android] as hierarchies to watch
[  +55 ms] Running Gradle task 'assembleDebug'... (completed in 945ms)
[+7490 ms] Error: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 9 390ms.
[  +34 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +134 ms] ensureAnalyticsSent: 131ms
[        ] Running 2 shutdown hooks
[   +6 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on Arch Linux 6.11.3-arch1-1, locale
    ru_RU.UTF-8)
    • Flutter version 3.24.3 on channel stable at
      /home/totalboy/projects/.flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 недель назад), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.5
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15
      (API 35) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Arch Linux
      6.11.3-arch1-1
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 129.0.6668.100

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
>[   +1 ms] JVM is incompatible.

This could be an incompatible issue with Gradle and JDK versions. When a Flutter project is created, you might see Gradle 8.3 (`distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip`). Can you try a higher version to see if it works? (maybe `distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip`)

**Comment by qucals** [comment]
> > [   +1 ms] JVM is incompatible.
> 
> This could be an incompatible issue with Gradle and JDK versions. When a Flutter project is created, you might see Gradle 8.3 (`distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip`). Can you try a higher version to see if it works? (maybe `distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip`)

I tried to do it with 8.3, 8.5, 8.9 and 8.10 versions of Gradle and there's the same error

**Comment by huycozy** [comment]
Can you please compress the sample project and share it here? I can try it on my end.
