### ISSUE TITLE
Codesigning failing for 3.27 beta

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#157016]
[engine commit](https://flutter.googlesource.com/mirrors/engine/+/d63244175cfeba9ac15dd0af1d1ba3369218f046)
[build](https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20Production%20Engine%20Drone/14363/infra)
[logs](https://logs.chromium.org/logs/dart-internal/buildbucket/cr-buildbucket/8733911943888945617/+/u/Global_generators/Codesign__Volumes_Work_s_w_ir_cache_builder_src_out_debug_framework_unsigned_framework.zip/codesign_Apple_engine_binaries/stdout)

```
[INFO] codesign: Executing: /usr/bin/codesign --keychain build.keychain -f -s Developer ID Application: FLUTTER.IO LLC (S8QB4VV633) /Volumes/Work/s/w/ir/x/t/conductor_codesignBmgvmt/single_artifact/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework --timestamp --options=runtime

Unhandled exception:
Exception: Failed to codesign binary or bundle at /Volumes/Work/s/w/ir/x/t/conductor_codesignBmgvmt/single_artifact/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework with args: /usr/bin/codesign --keychain build.keychain -f -s Developer ID Application: FLUTTER.IO LLC (S8QB4VV633) /Volumes/Work/s/w/ir/x/t/conductor_codesignBmgvmt/single_artifact/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework --timestamp --options=runtime
stdout:
stderr:
/Volumes/Work/s/w/ir/x/t/conductor_codesignBmgvmt/single_artifact/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework: replacing existing signature
/Volumes/Work/s/w/ir/x/t/conductor_codesignBmgvmt/single_artifact/FlutterMacOS.xcframework/macos-arm64_x86_64/FlutterMacOS.framework: unsealed contents present in the root directory of an embedded framework
#0      FileCodesignVisitor.codesignAtPath.<anonymous closure> (package:codesign/src/file_codesign_visitor.dart:388)
<asynchronous suspension>
#1      RetryOptions.retry (package:retry/retry.dart:131)
<asynchronous suspension>
#2      FileCodesignVisitor.codesignAtPath (package:codesign/src/file_codesign_visitor.dart:381)
<asynchronous suspension>
#3      FileCodesignVisitor.visitDirectory (package:codesign/src/file_codesign_visitor.dart:289)
<asynchronous suspension>
#4      FileCodesignVisitor.visitDirectory (package:codesign/src/file_codesign_visitor.dart:264)
<asynchronous suspension>
#5      FileCodesignVisitor.visitDirectory (package:codesign/src/file_codesign_visitor.dart:264)
<asynchronous suspension>
#6      FileCodesignVisitor.visitDirectory (package:codesign/src/file_codesign_visitor.dart:264)
<asynchronous suspension>
#7      FileCodesignVisitor.processRemoteZip (package:codesign/src/file_codesign_visitor.dart:221)
<asynchronous suspension>
#8      FileCodesignVisitor.validateAll (package:codesign/src/file_codesign_visitor.dart:182)
<asynchronous suspension>

```

**Comment by christopherfujino** [comment]
Per https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG312:

> codesign says I have 'unsealed content' somewhere.
> Do not put files or directories into the top directory of an app or framework bundle
> All content must be inside Contents or Versions respectively as described [earlier](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG201).

**Comment by cbracken** [comment]
Would be great if they told us what that content was -- is there a zip I can download to take a look?

**Comment by christopherfujino** [comment]
I will work on trying to get you a zipped bundle

**Comment by christopherfujino** [comment]
This should upload logs once codesiging fails: https://flutter-review.googlesource.com/c/recipes/+/60420

**Comment by christopherfujino** [comment]
Ok, we have new release builds that we expect to fail again, but to upload the offending zipped archives: https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20engine_release_builder/713/overview

**Comment by christopherfujino** [comment]
This is out to address: https://github.com/flutter/cocoon/pull/3955

**Comment by christopherfujino** [comment]
Ok, we have two new CIPD packages of codesign published:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20codesign/735/infra
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20codesign/1626/infra

I now need to move the `live` ref

**Comment by christopherfujino** [comment]
The first time I updated the `live` ref, I executed:

```
cipd set-ref flutter/codesign/mac-amd64 -ref live -version SG027FIkNBc7L3Sggfv94iPFHXTWHGXGLyYKRnDRl04C
cipd set-ref flutter/codesign/mac-arm64 -ref live -version 8NisvNZ5P4cc03qlPVvrxlBXD4SvbfoBHSbsOFOrIJgC
```

This time, it will be:

```
cipd set-ref flutter/codesign/mac-amd64 -ref live -version YNJmqIY5w82rqxIA33c08Hh869zTLoomsQiR97qhLNsC
cipd set-ref flutter/codesign/mac-arm64 -ref live -version avtFuPUue13nyl19hgKYSxfJSVXDq0eO6IR6XFCVCP8C
```

They both succeeded:

- https://chrome-infra-packages.appspot.com/p/flutter/codesign/mac-amd64/+/YNJmqIY5w82rqxIA33c08Hh869zTLoomsQiR97qhLNsC
- https://chrome-infra-packages.appspot.com/p/flutter/codesign/mac-arm64/+/avtFuPUue13nyl19hgKYSxfJSVXDq0eO6IR6XFCVCP8C

**Comment by christopherfujino** [comment]
New build used the new codesign app, but appeared to fail exactly the same.

**Comment by jmagman** [comment]
The codesigning build failure is complaining  `unsealed contents present in the root directory of an embedded framework` I _bet_ it's because the `PrivacyInfo.xcprivacy` file needs to be in the `Resources` directory on macOS (a different spot than iOS) https://github.com/flutter/engine/pull/55078

I made a new macOS framework project, added an App Privacy file, and the copy step puts it in `TestFramework.framework/Versions/A/Resources`:
```
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/m/Projects/TestFramework/PrivacyInfo.xcprivacy /Users/m/Library/Developer/Xcode/DerivedData/TestFramework-cazhopysvkdhedbgjtqzoiwsrxbt/Build/Products/Debug/TestFramework.framework/Versions/A/Resources
```

**Comment by cbracken** [comment]
Ugh yeah that's what I was initially wondering when I noticed it in the dump in the logs, since it's the only new file we've embedded in there since the last release and it is at the root. That said, the .DS_Store thing seemed a bit more promising at the time based on StackOverflow, and on the assumption that Apple's code-signing tools would know about privacy manifests. Sounds like that was probably a bad assumption though.

**Comment by jmagman** [comment]
The beta fix is at https://github.com/flutter/engine/pull/55938. The beta framework test https://github.com/flutter/flutter/pull/157136 should be merged first.

**Comment by christopherfujino** [comment]
> The beta fix is at [flutter/engine#55938](https://github.com/flutter/engine/pull/55938). The beta framework test #157136 should be merged first.

I *think* it will be ok merging this first, provided we merge the framework test *before* rolling the engine.

**Comment by christopherfujino** [comment]
> > The beta fix is at [flutter/engine#55938](https://github.com/flutter/engine/pull/55938). The beta framework test #157136 should be merged first.
> 
> I _think_ it will be ok merging this first, provided we merge the framework test _before_ rolling the engine.

It actually doesn't matter, I merged both.

**Comment by christopherfujino** [comment]
I believe this is resolved since the engine builds succeeded. I'll leave this open until we roll it to the framework and the updated test passes.

**Comment by jmagman** [comment]
Cherry-picking back to master so this doesn't regress in the next beta: https://github.com/flutter/engine/pull/56010 and https://github.com/flutter/flutter/pull/157318

**Comment by zhuhaichao518** [comment]
@jmagman You saved my day! `PrivacyInfo.xcprivacy` is exactly the file causing the problem in my case.

**Comment by cbracken** [comment]
> I believe this is resolved since the engine builds succeeded. I'll leave this open until we roll it to the framework and the updated test passes.

Whoops! Better late than never -- closing!
