### ISSUE TITLE
i try to use FlutterFragment to load a thirdPlugin but it call a fail  on platformview but i try to use FlutterActivity load is ok 

### ISSUE THREAD

**Issue by feifeihuaidan1** [flutter/flutter#157142]
### Steps to reproduce

i try to use FlutterFragment to load a thirdPlugin but it call a fail  on platformview but i try to use FlutterActivity load is ok 
 ```
E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method touch on channel flutter/platform_views)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
    <asynchronous suspension>
    #1      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:869:5)
    <asynchronous suspension>
    #2      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:965:7)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
    <asynchronous suspension>
    #1      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1141:28)
    <asynchronous suspension>
    #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
    <asynchronous suspension>
    #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:831:7)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
```

### Expected results

try to load  thirdPlugin normaly

### Actual results

```
E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method touch on channel flutter/platform_views)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
    <asynchronous suspension>
    #1      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:869:5)
    <asynchronous suspension>
    #2      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:965:7)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
    <asynchronous suspension>
    #1      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1141:28)
    <asynchronous suspension>
    #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:804:5)
    <asynchronous suspension>
    #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:831:7)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.16.6, on macOS 12.4 21F79 darwin-arm64 (Rosetta),
    locale zh-Hans-CN)
    • Flutter version 3.16.6 on channel stable at
      /Users/feifei.zhang/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (9 months ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/feifei.zhang/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/feifei.zhang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.
```

**Comment by feifeihuaidan1** [comment]
all the plugins can not loaded normaly , please help to find the issue

**Comment by darshankawar** [comment]
@feifeihuaidan1 
Your question is better suited for support channels like stackoverflow, so please ask the same there.
If you think there's a genuine bug in the framework, please use issue template, fill out requested details so that we can properly address it. 
Closing for now.
