### ISSUE TITLE
Cannot execute -h\bin\java to determine the version

### ISSUE THREAD

**Issue by hshhshsjsgeh** [flutter/flutter#157148]
### Steps to reproduce

1. set `JAVA_HOME` variable to `C:\Program Files\Android\Android Studio\jbr`
2. run `PS C:\> flutter doctor --android-licenses`
3. get the error
4. try to set `JAVA_HOME` variable to `C:\Program Files\Java\jdk-23`
5. get the same error

### Actual results

```console
PS C:\Users\tri36> flutter doctor --android-licenses

ERROR: JAVA_HOME is set to an invalid directory: -h

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Android sdkmanager tool was found, but failed to run
(C:\Users\tri36\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/to/windows-android-setup for detailed instructions.
```

### Logs

<details open>
<summary>Logs</summary>

```console

ERROR: JAVA_HOME is set to an invalid directory: -h

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Android sdkmanager tool was found, but failed to run
(C:\Users\tri36\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/to/windows-android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:410:9)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:26)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.5011], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\Users\tri36\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\tri36\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\tri36\AppData\Local\Android\Sdk
    • Java binary at: -h\bin\java
    ✗ Cannot execute -h\bin\java to determine the version

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.89

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Can you provide the output of these commands?

```console
echo %JAVA_HOME%
```
and
```console
java --version
```

**Comment by hshhshsjsgeh** [comment]
```console
openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
OpenJDK 64-Bit Server VM (build 21.0.3+-12282718-b509.11, mixed mode)
```

**Comment by huycozy** [comment]
Let's try executing the command to see if it works:

```console
flutter config --jdk-dir "C:\Program Files\Android\Android Studio\jbr"
```

If it does not work, can you provide output of `flutter doctor -vv` (two `v`)?

**Comment by hshhshsjsgeh** [comment]
@huycozy 
thanks it's worked correctly
