### ISSUE TITLE
Install firebase_database fails

### ISSUE THREAD

**Issue by faboweb** [flutter/flutter#15716]
I can't install firebase_database.

Current pubspec.yml:
```
...

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  # firebase
  firebase_core: "^0.1.0"
  firebase_database: "0.4.0"
  firebase_auth: "^0.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

...
```

When I install the packages I get:

```
>flutter packages get -v
[  +64 ms] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +175 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git rev-parse --abbrev-ref HEAD
[ +132 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git ls-remote --get-url origin
[ +111 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git log -n 1 --pretty=format:%H
[ +138 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
[        ] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git log -n 1 --pretty=format:%ar
[ +121 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[        ] [C:\Users\Fabo\Documents\Entwicklung\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +96 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.5-0-g3ea4d0634
[ +192 ms] Running "flutter packages get" in mira...
[   +6 ms] [C:\Users\Fabo\Documents\Entwicklung\mira\] C:\Users\Fabo\Documents\Entwicklung\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile
[+1624 ms] Package firebase_database has no versions that match 0.4.0 derived from:
[   +1 ms] - mira depends on version 0.4.0
[  +82 ms] "flutter get" took 1.756ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      pub (package:flutter_tools/src/dart/pub.dart:164)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:100)
<asynchronous suspension>
#3      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:74)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#5      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#9      new Future.sync (dart:async/future.dart:222)
#10     CommandRunner.run (package:args/command_runner.dart:109)
#11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#19     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#21     main (file:///C:/Users/Fabo/Documents/Entwicklung/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


[  +58 ms] ensureAnalyticsSent: 48ms
[   +3 ms] exiting with code 1

```

Flutter doctor gives me:

```
>flutter doctor -v
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale de-DE)
    • Flutter version 0.1.5 at C:\Users\Fabo\Documents\Entwicklung\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Fabo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] VS Code (version 1.21.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
try switching to `dev` channel or try an older version of the `firebase_database` dependency

**Comment by Hixie** [comment]
It's probably because the firebase packages have been updated to require more recent Flutters (with Dart 2). As @zoechi says, if you loosen the version constraint, or update to a more recent flutter, it should work fine.

**Comment by faboweb** [comment]
Thank you for the help.

I tested which versions pub would resolve by setting:
  firebase_auth: any
  firebase_core: any
  firebase_database: "0.4.1" // latest

The configuration that was resolved and works:
  firebase_auth: "0.5.1"
  firebase_core: "0.0.7"
  firebase_database: "0.4.1"

I hope this helps people in the future.
