### ISSUE TITLE
`flutter_desktop_darwin_unittests` doesn't run on arm64 ci

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#157205]
## steps to reproduce
https://github.com/flutter/engine/pull/55968
## error
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/1259641/overview
## log
```
Failed Command:

/Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_profile_arm64_tests/flutter_desktop_darwin_unittests --gtest_repeat=2 --gtest_shuffle

Exit Code: -5

Output:
[INFO:flutter/testing/test_timeout_listener.cc(76)] Test timeout of 300 seconds per test case will be enforced.

Repeating all tests (iteration 1) . . .

Note: Randomizing tests' orders with a seed of 31833 .
[==========] Running 199 tests from 24 test suites.
[----------] Global test environment set-up.
[----------] 13 tests from FlutterViewControllerMockEngineTest
[ RUN      ] FlutterViewControllerMockEngineTest.TestKeyEquivalentIsPassedToTextInputPlugin
flutter: The Dart VM service is listening on http://127.0.0.1:51195/XpIJBtGVkwE=/
[       OK ] FlutterViewControllerMockEngineTest.TestKeyEquivalentIsPassedToTextInputPlugin (104 ms)
[ RUN      ] FlutterViewControllerMockEngineTest.TestKeyEventsAreNotPropagatedIfHandled
flutter: The Dart VM service is listening on http://127.0.0.1:51196/vayix9mBX-I=/
[       OK ] FlutterViewControllerMockEngineTest.TestKeyEventsAreNotPropagatedIfHandled (8 ms)
[ RUN      ] FlutterViewControllerMockEngineTest.TestFlagsChangedEventsArePropagatedIfNotHandled
flutter: The Dart VM service is listening on http://127.0.0.1:51197/YavpTKH4t4M=/
[       OK ] FlutterViewControllerMockEngineTest.TestFlagsChangedEventsArePropagatedIfNotHandled (7 ms)
[ RUN      ] FlutterViewControllerMockEngineTest.TestTrackpadGesturesAreSentToFramework

Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1394, in <module>
    sys_exit(main())
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1307, in main
    run_cc_tests(build_dir, engine_filter, args.coverage, args.engine_capture_core_dump)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 511, in run_cc_tests
    run_engine_executable(
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 316, in run_engine_executable
    run_cmd(
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 127, in run_cmd
    raise RuntimeError(
RuntimeError: Command "/Volumes/Work/s/w/ir/cache/builder/src/out/ci/host_profile_arm64_tests/flutter_desktop_darwin_unittests --gtest_repeat=2 --gtest_shuffle" (in /Volumes/Work/s/w/ir/cache/builder/src) exited with code -5.
```

**Comment by gaaclarke** [comment]
It can be reproduced locally by just running the one test:
```
$ ./flutter_desktop_darwin_unittests --gtest_filter="FlutterViewControllerMockEngineTest.TestTrackpadGesturesAreSentToFramework"
[INFO:flutter/testing/test_timeout_listener.cc(76)] Test timeout of 300 seconds per test case will be enforced.
Note: Google Test filter = FlutterViewControllerMockEngineTest.TestTrackpadGesturesAreSentToFramework
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from FlutterViewControllerMockEngineTest
[ RUN      ] FlutterViewControllerMockEngineTest.TestTrackpadGesturesAreSentToFramework
Trace/BPT trap: 5
```

**Comment by gaaclarke** [comment]
Here's the stack trace for the crash:
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x18c0915a4)
  * frame #0: 0x000000018c0915a4 libobjc.A.dylib`object_getClass + 48
    frame #1: 0x0000000100b95cc4 flutter_desktop_darwin_unittests`+[OCMArg resolveSpecialValues:](self=<unavailable>, _cmd=<unavailable>, value=0x0000600001b789e0) at OCMArg.m:133:28 [opt]
    frame #2: 0x0000000100b97bc4 flutter_desktop_darwin_unittests`-[OCMInvocationStub invokeArgActionsForInvocation:](self=0x0000600001b60f40, _cmd=<unavailable>, anInvocation=0x0000600000e6fec0) at OCMInvocationStub.m:87:27 [opt]
    frame #3: 0x0000000100b97984 flutter_desktop_darwin_unittests`-[OCMInvocationStub handleInvocation:](self=0x0000600001b60f40, _cmd=<unavailable>, anInvocation=0x0000600000e6fec0) at OCMInvocationStub.m:53:5 [opt]
    frame #4: 0x0000000100b9cdc4 flutter_desktop_darwin_unittests`-[OCMockObject handleInvocation:](self=0x0000600003f4cb40, _cmd=<unavailable>, anInvocation=0x0000600000e6fec0) at OCMockObject.m:445:9 [opt]
    frame #5: 0x0000000100b9eb6c flutter_desktop_darwin_unittests`-[OCPartialMockObject forwardInvocationForRealObject:](self=<unavailable>, _cmd=<unavailable>, anInvocation=0x0000600000e6fec0) at OCPartialMockObject.m:254:8 [opt]
    frame #6: 0x000000018c523ce0 CoreFoundation`___forwarding___ + 976
    frame #7: 0x000000018c523850 CoreFoundation`_CF_forwarding_prep_0 + 96
    frame #8: 0x0000000100125a14 flutter_desktop_darwin_unittests`-[FlutterViewController touchesBeganWithEvent:](self=0x000000014f7199e0, _cmd=<unavailable>, event=0x0000600003841310) at FlutterViewController.mm:1089:7 [opt]
    frame #9: 0x00000001000d8f50 flutter_desktop_darwin_unittests`-[FlutterViewControllerTestObjC testTrackpadGesturesAreSentToFramework:](self=<unavailable>, _cmd=<unavailable>, engineMock=<unavailable>) at FlutterViewControllerTest.mm:827:3 [opt]
    frame #10: 0x00000001000d038c flutter_desktop_darwin_unittests`flutter::testing::FlutterViewControllerMockEngineTest_TestTrackpadGesturesAreSentToFramework_Test::TestBody(this=<unavailable>) at FlutterViewControllerTest.mm:286:3 [opt]
    frame #11: 0x0000000100bf305c flutter_desktop_darwin_unittests`testing::Test::Run() [inlined] void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(object=0x000060000154c000, method=0x00000000000000000000000000000020, location=<unavailable>) at gtest.cc:0 [opt]
    frame #12: 0x0000000100bf3044 flutter_desktop_darwin_unittests`testing::Test::Run(this=0x000060000154c000) at gtest.cc:2688:5 [opt]
    frame #13: 0x0000000100bf3e68 flutter_desktop_darwin_unittests`testing::TestInfo::Run(this=0x000000014f712cc0) at gtest.cc:2837:11 [opt]
    frame #14: 0x0000000100bf4b24 flutter_desktop_darwin_unittests`testing::TestSuite::Run(this=0x000000014f712540) at gtest.cc:3016:30 [opt]
    frame #15: 0x0000000100c03980 flutter_desktop_darwin_unittests`testing::internal::UnitTestImpl::RunAllTests(this=0x000000014f704b20) at gtest.cc:5922:44 [opt]
    frame #16: 0x0000000100c03500 flutter_desktop_darwin_unittests`testing::UnitTest::Run() [inlined] bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(object=<unavailable>, method=<unavailable>, location=<unavailable>) at gtest.cc:0 [opt]
    frame #17: 0x0000000100c034ec flutter_desktop_darwin_unittests`testing::UnitTest::Run(this=<unavailable>) at gtest.cc:5486:10 [opt]
    frame #18: 0x0000000100169784 flutter_desktop_darwin_unittests`main [inlined] RUN_ALL_TESTS() at gtest.h:2316:73 [opt]
    frame #19: 0x000000010016977c flutter_desktop_darwin_unittests`main(argc=1, argv=<unavailable>) at run_all_unittests.cc:0 [opt]
    frame #20: 0x000000018c0db154 dyld`start + 2476
```

**Comment by gaaclarke** [comment]
Here is invocation in the crash:
```
(lldb) up
frame #2: 0x0000000100b99624 flutter_desktop_darwin_unittests`-[OCMInvocationStub invokeArgActionsForInvocation:](self=0x00006000023e5780, _cmd=<unavailable>, anInvocation=0x00006000036d4fc0) at OCMInvocationStub.m:87:27 [opt]
   84  	            continue;
   85  	
   86  	        if([recordedArg isKindOfClass:[NSValue class]])
-> 87  	            recordedArg = [OCMArg resolveSpecialValues:recordedArg];
   88  	
   89  	        if([recordedArg isKindOfClass:[OCMArgAction class]])
   90  	            [recordedArg handleArgument:passedArg];
(lldb) po anInvocation
<NSInvocation: 0x6000036d4fc0>
return value: {v} void
target: {@} 0x14300a550
selector: {:} sendPointerEvent:
argument 2: {r^{?=QiQddiiddiqddddq}} 0x16fdfe8f0

(lldb) po 0x14300a550
<FlutterEngine: 0x14300a550>
```

Originally I thought we were going to be missing a method or the target would be deallocated, that doesn't seem to be the case.

It may have something to do with the argument being a reference.  It seems to be messing up with that.
