### ISSUE TITLE
[go_router] Multiple pop not working inside ShellRoute. [go_router]

### ISSUE THREAD

**Issue by yelmuratoff** [flutter/flutter#157219]
### Steps to reproduce

1. Copy code
2. Run
3. Push to B screen
4. Push to C screen
5. Double pop to A Screen (initial) will be report error.

### Expected results

Successfully popped to A screen

### Actual results

Error from Logs section

### Code sample

<details open><summary>With ShellRoute (Error)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

final parentNavigationKey = GlobalKey<NavigatorState>();
final shellRouteKey = GlobalKey<NavigatorState>();

class AScreen extends StatelessWidget {
  const AScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('A Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () => context.push('/b'),
            child: const Text('Push to B'),
          ),
        ),
      );
}

class BScreen extends StatelessWidget {
  const BScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('B Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () => context.push('/c'),
            child: const Text('Push to C'),
          ),
        ),
      );
}

class CScreen extends StatelessWidget {
  const CScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('C Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () {
              context
                ..pop()
                ..pop();
            },
            child: const Text('Return to A'),
          ),
        ),
      );
}

final router = GoRouter(
  navigatorKey: parentNavigationKey,
  initialLocation: '/a',
  routes: [
    GoRoute(
      path: '/a',
      builder: (context, state) => const AScreen(),
    ),
    ShellRoute(
      navigatorKey: shellRouteKey,
      builder: (context, state, child) => Scaffold(
        appBar: AppBar(title: const Text('B and C Shell')),
        body: child,
      ),
      routes: [
        GoRoute(
          path: '/b',
          name: 'b',
          builder: (context, state) => const BScreen(),
        ),
        GoRoute(
          path: '/c',
          name: 'c',
          builder: (context, state) => const CScreen(),
        ),
      ],
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: router,
        theme: ThemeData(
          colorScheme: const ColorScheme.highContrastLight(secondary: Colors.amber),
        ),
      );
}
```

</details>

<details open><summary>Without ShellRoute (Success)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

final parentNavigationKey = GlobalKey<NavigatorState>();
final shellRouteKey = GlobalKey<NavigatorState>();

class AScreen extends StatelessWidget {
  const AScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('A Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () => context.push('/b'),
            child: const Text('Push to B'),
          ),
        ),
      );
}

class BScreen extends StatelessWidget {
  const BScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('B Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () => context.push('/c'),
            child: const Text('Push to C'),
          ),
        ),
      );
}

class CScreen extends StatelessWidget {
  const CScreen({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(title: const Text('C Screen')),
        body: Center(
          child: FilledButton(
            onPressed: () {
              context
                ..pop()
                ..pop();
            },
            child: const Text('Return to A'),
          ),
        ),
      );
}

final router = GoRouter(
  navigatorKey: parentNavigationKey,
  initialLocation: '/a',
  routes: [
    GoRoute(
      path: '/a',
      builder: (context, state) => const AScreen(),
    ),
    ShellRoute(
      navigatorKey: shellRouteKey,
      builder: (context, state, child) => Scaffold(
        appBar: AppBar(title: const Text('B and C Shell')),
        body: child,
      ),
      routes: [
        GoRoute(
          path: '/b',
          name: 'b',
          builder: (context, state) => const BScreen(),
        ),
        GoRoute(
          path: '/c',
          name: 'c',
          builder: (context, state) => const CScreen(),
        ),
      ],
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: router,
        theme: ThemeData(
          colorScheme: const ColorScheme.highContrastLight(secondary: Colors.amber),
        ),
      );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
The following StateError was thrown while handling a gesture:
Bad state: Future already completed

When the exception was thrown, this was the stack:
#1      ImperativeRouteMatch.complete (package:go_router/src/match.dart:456:15)
match.dart:456
#2      GoRouterDelegate._completeRouteMatch (package:go_router/src/delegate.dart:162:14)
delegate.dart:162
#3      GoRouterDelegate._handlePopPageWithRouteMatch (package:go_router/src/delegate.dart:137:7)
delegate.dart:137
#4      _CustomNavigatorState._handlePopPage (package:go_router/src/builder.dart:417:42)
builder.dart:417
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5357:28)
navigator.dart:5357
#6      GoRouterDelegate.pop (package:go_router/src/delegate.dart:94:11)
delegate.dart:94
#7      GoRouter.pop (package:go_router/src/router.dart:491:20)
router.dart:491
#8      GoRouterHelper.pop (package:go_router/src/misc/extensions.dart:71:65)
extensions.dart:71
#9      CScreen.build.<anonymous closure> (package:digital_bridge/main_dev.dart:65:19)
main_dev.dart:65
#10     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
ink_well.dart:1170
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
recognizer.dart:351
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
tap.dart:656
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
tap.dart:313
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:246:7)
tap.dart:246
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:703:9)
recognizer.dart:703
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
pointer_router.dart:98
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
pointer_router.dart:143
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
pointer_router.dart:141
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
pointer_router.dart:127
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:501:19)
binding.dart:501
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
binding.dart:481
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
binding.dart:450
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
binding.dart:426
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
binding.dart:389
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
binding.dart:336
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
binding.dart:305
#28     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
platform_dispatcher.dart:442
#30     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
hooks.dart:262
(elided one frame from dart:async)

Handler: "onTap"
Recognizer: TapGestureRecognizer#d1796
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(217.0, 543.7)
    finalLocalPosition: Offset(64.6, 12.2)
    button: 1
    sent tap down
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.0.1 24A348 darwin-arm64, locale en-KZ)
    • Flutter version 3.24.1 on channel stable at /Users/yelamanyelmuratov/fvm/versions/3.24.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (8 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/yelamanyelmuratov/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/yelamanyelmuratov/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.99.20240930

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • 09247B21-91E4-44CE-901D-8D2D1FD686F8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.101

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by yelmuratoff** [comment]
I would also like to point out that the same example with different approaches gives the same problem. For example:

<details open><summary>Without go_router_builder (Work)</summary>
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _sectionANavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'sectionANav');

void main() {
  runApp(NestedTabNavigationExampleApp());
}

class NestedTabNavigationExampleApp extends StatelessWidget {
  NestedTabNavigationExampleApp({super.key});

  final GoRouter _router = GoRouter(
    navigatorKey: _rootNavigatorKey,
    debugLogDiagnostics: true,
    initialLocation: '/a',
    routes: <RouteBase>[
      GoRoute(
        path: '/success',
        builder: (BuildContext context, GoRouterState state) => TabScreen(
          text: 'Success',
          onPressed: () {
            context.pop(true);
            context.pop(false);
          },
        ),
      ),
      GoRoute(
        path: '/categories',
        builder: (BuildContext context, GoRouterState state) => TabScreen(
          text: 'Categories',
          onPressed: () => context.push<bool>('/success'),
        ),
      ),
      StatefulShellRoute.indexedStack(
        builder: (BuildContext context, GoRouterState state, StatefulNavigationShell navigationShell) {
          return ScaffoldWithNavBar(
            navigationShell: navigationShell,
          );
        },
        branches: <StatefulShellBranch>[
          StatefulShellBranch(
            navigatorKey: _sectionANavigatorKey,
            routes: <RouteBase>[
              GoRoute(
                path: '/a',
                builder: (BuildContext context, GoRouterState state) => const TabScreen(
                  text: 'A',
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: <RouteBase>[
              GoRoute(
                path: '/b',
                builder: (BuildContext context, GoRouterState state) => TabScreen(
                  text: 'B',
                  onPressed: () => GoRouter.of(context).push<bool>('/b/bb'),
                ),
                routes: [
                  GoRoute(
                    path: 'bb',
                    builder: (BuildContext context, GoRouterState state) => TabScreen(
                      text: 'BB',
                      onPressed: () => GoRouter.of(context).push('/categories'),
                    ),
                  ),
                ],
              ),
            ],
          ),
          StatefulShellBranch(
            routes: <RouteBase>[
              GoRoute(
                path: '/c',
                builder: (BuildContext context, GoRouterState state) => const TabScreen(
                  text: 'C',
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: <RouteBase>[
              GoRoute(
                path: '/d',
                builder: (BuildContext context, GoRouterState state) => const TabScreen(
                  text: 'D',
                ),
              ),
            ],
          ),
        ],
      ),
    ],
  );

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router,
      );
}

class TabScreen extends StatelessWidget {
  const TabScreen({
    required this.text,
    this.onPressed,
    super.key,
  });

  final String text;
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              text,
              style: const TextStyle(fontSize: 24),
            ),
            ElevatedButton(
              onPressed: onPressed,
              child: const Text('Go'),
            ),
          ],
        ),
      ),
    );
  }
}

class ScaffoldWithNavBar extends StatefulWidget {
  const ScaffoldWithNavBar({
    required this.navigationShell,
    Key? key,
  }) : super(key: key ?? const ValueKey<String>('ScaffoldWithNavBar'));

  final StatefulNavigationShell navigationShell;

  @override
  State<ScaffoldWithNavBar> createState() => _ScaffoldWithNavBarState();
}

class _ScaffoldWithNavBarState extends State<ScaffoldWithNavBar> with TickerProviderStateMixin {
  late final TabController _tabController = TabController(length: 4, vsync: this);

  @override
  void dispose() {
    super.dispose();
    _tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.navigationShell,
      bottomNavigationBar: TabBar(
        controller: _tabController,
        tabs: const <Tab>[
          Tab(icon: Icon(Icons.work), text: 'A'),
          Tab(icon: Icon(Icons.work), text: 'B'),
          Tab(icon: Icon(Icons.tab), text: 'C'),
          Tab(icon: Icon(Icons.settings), text: 'D'),
        ],
        onTap: (int index) async {
          widget.navigationShell.goBranch(
            index,
            initialLocation: index == widget.navigationShell.currentIndex,
          );
        },
      ),
    );
  }
}
```

Route tree:
[GoRouter] Full paths for routes:
           ├─/success (TabScreen)
           ├─/categories (TabScreen)
           └─ (ShellRoute)
             ├─/a (TabScreen)
             ├─/b (TabScreen)
             │ └─/b/bb (TabScreen)
             ├─/c (TabScreen)
             └─/d (TabScreen)
[GoRouter] setting initial location /a
</details>

<details open><summary>With go_router_builder (Error)</summary>
```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'pop_generated.g.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _sectionANavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'sectionANav');

void main() {
  runApp(NestedTabNavigationExampleApp());
}

class NestedTabNavigationExampleApp extends StatelessWidget {
  NestedTabNavigationExampleApp({super.key});

  final GoRouter _router = GoRouter(
    navigatorKey: _rootNavigatorKey,
    debugLogDiagnostics: true,
    initialLocation: '/a',
    routes: $appRoutes,
  );

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router,
      );
}

class TabScreen extends StatelessWidget {
  const TabScreen({
    required this.text,
    this.onPressed,
    super.key,
  });

  final String text;
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              text,
              style: const TextStyle(fontSize: 24),
            ),
            ElevatedButton(
              onPressed: onPressed,
              child: const Text('Go'),
            ),
          ],
        ),
      ),
    );
  }
}

class ScaffoldWithNavBar extends StatefulWidget {
  const ScaffoldWithNavBar({
    required this.navigationShell,
    Key? key,
  }) : super(key: key ?? const ValueKey<String>('ScaffoldWithNavBar'));

  final StatefulNavigationShell navigationShell;

  @override
  State<ScaffoldWithNavBar> createState() => _ScaffoldWithNavBarState();
}

class _ScaffoldWithNavBarState extends State<ScaffoldWithNavBar> with TickerProviderStateMixin {
  late final TabController _tabController = TabController(length: 4, vsync: this);

  @override
  void dispose() {
    super.dispose();
    _tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.navigationShell,
      bottomNavigationBar: TabBar(
        controller: _tabController,
        tabs: const <Tab>[
          Tab(icon: Icon(Icons.work), text: 'A'),
          Tab(icon: Icon(Icons.work), text: 'B'),
          Tab(icon: Icon(Icons.tab), text: 'C'),
          Tab(icon: Icon(Icons.settings), text: 'D'),
        ],
        onTap: (int index) async {
          widget.navigationShell.goBranch(
            index,
            initialLocation: index == widget.navigationShell.currentIndex,
          );
        },
      ),
    );
  }
}

// <-- Routes -->

@TypedGoRoute<SuccessRoute>(path: '/success')
class SuccessRoute extends GoRouteData {
  const SuccessRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'Success route',
      onPressed: () {
        context.pop(true);
        context.pop(false);
      },
    );
  }
}

@TypedGoRoute<CategoriesRoute>(path: '/categories')
class CategoriesRoute extends GoRouteData {
  const CategoriesRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'Categories route',
      onPressed: () => context.push<bool>('/success'),
    );
  }
}

// <-- Stateful Shell -->

@TypedStatefulShellRoute<MainShellRouteData>(
  branches: <TypedStatefulShellBranch<StatefulShellBranchData>>[
    TypedStatefulShellBranch<AShellBranchData>(
      routes: [
        TypedGoRoute<ARouteData>(path: '/a'),
      ],
    ),
    TypedStatefulShellBranch<BShellBranchData>(
      routes: [
        TypedGoRoute<BRouteData>(path: '/b', routes: [
          TypedGoRoute<BBRouteData>(path: '/bb'),
        ]),
      ],
    ),
    TypedStatefulShellBranch<CShellBranchData>(
      routes: [
        TypedGoRoute<CRouteData>(path: '/c'),
      ],
    ),
    TypedStatefulShellBranch<DShellBranchData>(
      routes: [
        TypedGoRoute<DRouteData>(path: '/d'),
      ],
    ),
  ],
)
class MainShellRouteData extends StatefulShellRouteData {
  const MainShellRouteData();

  @override
  Widget builder(
    BuildContext context,
    GoRouterState state,
    StatefulNavigationShell navigationShell,
  ) {
    return ScaffoldWithNavBar(
      navigationShell: navigationShell,
    );
  }
}

class AShellBranchData extends StatefulShellBranchData {
  static final GlobalKey<NavigatorState> $navigatorKey = _sectionANavigatorKey;

  const AShellBranchData();
}

class BShellBranchData extends StatefulShellBranchData {
  const BShellBranchData();
}

class CShellBranchData extends StatefulShellBranchData {
  const CShellBranchData();
}

class DShellBranchData extends StatefulShellBranchData {
  const DShellBranchData();
}

// <-- Stateful Routes -->

class ARouteData extends GoRouteData {
  const ARouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'A');
  }
}

class BRouteData extends GoRouteData {
  const BRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'B',
      onPressed: () => context.push<bool>('/b/bb'),
    );
  }
}

class BBRouteData extends GoRouteData {
  const BBRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'BB',
      onPressed: () => context.push('/categories'),
    );
  }
}

class CRouteData extends GoRouteData {
  const CRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'C');
  }
}

class DRouteData extends GoRouteData {
  const DRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'D');
  }
}
```

Route tree:
[GoRouter] setting initial location /a
[GoRouter] Full paths for routes:
           ├─/success (Widget)
           ├─/categories (Widget)
           └─ (ShellRoute)
             ├─/a (Widget)
             ├─/b (Widget)
             │ └─/b/bb (Widget)
             ├─/c (Widget)
             └─/d (Widget)
</details>

**Comment by yelmuratoff** [comment]
With `go_router_builder` it's not work.


<details open><summary>With go_router_builder (Error)</summary>

```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'pop_generated.g.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _sectionANavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'sectionANav');

void main() {
  runApp(NestedTabNavigationExampleApp());
}

class NestedTabNavigationExampleApp extends StatelessWidget {
  NestedTabNavigationExampleApp({super.key});

  final GoRouter _router = GoRouter(
    navigatorKey: _rootNavigatorKey,
    debugLogDiagnostics: true,
    initialLocation: '/a',
    routes: $appRoutes,
  );

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router,
      );
}

class TabScreen extends StatelessWidget {
  const TabScreen({
    required this.text,
    this.onPressed,
    super.key,
  });

  final String text;
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              text,
              style: const TextStyle(fontSize: 24),
            ),
            ElevatedButton(
              onPressed: onPressed,
              child: const Text('Go'),
            ),
          ],
        ),
      ),
    );
  }
}

class ScaffoldWithNavBar extends StatefulWidget {
  const ScaffoldWithNavBar({
    required this.navigationShell,
    Key? key,
  }) : super(key: key ?? const ValueKey<String>('ScaffoldWithNavBar'));

  final StatefulNavigationShell navigationShell;

  @override
  State<ScaffoldWithNavBar> createState() => _ScaffoldWithNavBarState();
}

class _ScaffoldWithNavBarState extends State<ScaffoldWithNavBar> with TickerProviderStateMixin {
  late final TabController _tabController = TabController(length: 4, vsync: this);

  @override
  void dispose() {
    super.dispose();
    _tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.navigationShell,
      bottomNavigationBar: TabBar(
        controller: _tabController,
        tabs: const <Tab>[
          Tab(icon: Icon(Icons.work), text: 'A'),
          Tab(icon: Icon(Icons.work), text: 'B'),
          Tab(icon: Icon(Icons.tab), text: 'C'),
          Tab(icon: Icon(Icons.settings), text: 'D'),
        ],
        onTap: (int index) async {
          widget.navigationShell.goBranch(
            index,
            initialLocation: index == widget.navigationShell.currentIndex,
          );
        },
      ),
    );
  }
}

// <-- Routes -->

@TypedGoRoute<SuccessRoute>(path: '/success')
class SuccessRoute extends GoRouteData {
  const SuccessRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'Success route',
      onPressed: () {
        context.pop(true);
        context.pop(false);
      },
    );
  }
}

@TypedGoRoute<CategoriesRoute>(path: '/categories')
class CategoriesRoute extends GoRouteData {
  const CategoriesRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'Categories route',
      onPressed: () => context.push<bool>('/success'),
    );
  }
}

// <-- Stateful Shell -->

@TypedStatefulShellRoute<MainShellRouteData>(
  branches: <TypedStatefulShellBranch<StatefulShellBranchData>>[
    TypedStatefulShellBranch<AShellBranchData>(
      routes: [
        TypedGoRoute<ARouteData>(path: '/a'),
      ],
    ),
    TypedStatefulShellBranch<BShellBranchData>(
      routes: [
        TypedGoRoute<BRouteData>(path: '/b', routes: [
          TypedGoRoute<BBRouteData>(path: '/bb'),
        ]),
      ],
    ),
    TypedStatefulShellBranch<CShellBranchData>(
      routes: [
        TypedGoRoute<CRouteData>(path: '/c'),
      ],
    ),
    TypedStatefulShellBranch<DShellBranchData>(
      routes: [
        TypedGoRoute<DRouteData>(path: '/d'),
      ],
    ),
  ],
)
class MainShellRouteData extends StatefulShellRouteData {
  const MainShellRouteData();

  @override
  Widget builder(
    BuildContext context,
    GoRouterState state,
    StatefulNavigationShell navigationShell,
  ) {
    return ScaffoldWithNavBar(
      navigationShell: navigationShell,
    );
  }
}

class AShellBranchData extends StatefulShellBranchData {
  static final GlobalKey<NavigatorState> $navigatorKey = _sectionANavigatorKey;

  const AShellBranchData();
}

class BShellBranchData extends StatefulShellBranchData {
  const BShellBranchData();
}

class CShellBranchData extends StatefulShellBranchData {
  const CShellBranchData();
}

class DShellBranchData extends StatefulShellBranchData {
  const DShellBranchData();
}

// <-- Stateful Routes -->

class ARouteData extends GoRouteData {
  const ARouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'A');
  }
}

class BRouteData extends GoRouteData {
  const BRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'B',
      onPressed: () => context.push<bool>('/b/bb'),
    );
  }
}

class BBRouteData extends GoRouteData {
  const BBRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return TabScreen(
      text: 'BB',
      onPressed: () => context.push('/categories'),
    );
  }
}

class CRouteData extends GoRouteData {
  const CRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'C');
  }
}

class DRouteData extends GoRouteData {
  const DRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const TabScreen(text: 'D');
  }
}

```

</details>

Route tree:
[GoRouter] setting initial location /a
[GoRouter] Full paths for routes:
           ├─/success (Widget)
           ├─/categories (Widget)
           └─ (ShellRoute)
             ├─/a (Widget)
             ├─/b (Widget)
             │ └─/b/bb (Widget)
             ├─/c (Widget)
             └─/d (Widget)

**Comment by darshankawar** [comment]
@yelmuratoff 
There are similar open issues with same log and behavior that you can go through and follow-up in:

https://github.com/flutter/flutter/issues/156809
https://github.com/flutter/flutter/issues/154759

and https://github.com/flutter/flutter/issues/151080 to check the solution.

Closing in favor of linked issues. If you disagree, write in comments and I'll reopen it.

**Comment by yelmuratoff** [comment]
> @yelmuratoff There are similar open issues with same log and behavior that you can go through and follow-up in:
> 
> #156809 #154759
> 
> and #151080 to check the solution.
> 
> Closing in favor of linked issues. If you disagree, write in comments and I'll reopen it.

https://github.com/flutter/flutter/issues/151080 this one is not fix this problem. But it maybe relates to first two issues. In any case, it does not specify that this is happening inside the ShellRoute.
