### ISSUE TITLE
Keyboard input not detect, error message tells me to submit report, see log

### ISSUE THREAD

**Issue by keithloughnane** [flutter/flutter#157240]
### Steps to reproduce

I'm not sure how to reproduce (but you error tells me to submit a report.
I'm using Bonfire (which uses Flame) and I think it has something to do with a popup I have on top of bonfire/flame and going back to it, after I go back 90% of the time it's ok but about 10% of the time keyboard input no longer works.

### Expected results

Keyboard input should work (for player character input)

### Actual results

about 10% of the time keyboard input will stop working until the app is restarted

### Code sample

sorry, my app is too complicated.
I'm submitting a report because your error message told me too. See below

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

flutter: Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#e3331(physicalKey: PhysicalKeyboardKey#91fcd(usbHidUsage: "0x0007000c", debugName: "Key I"), logicalKey: LogicalKeyboardKey#29639(keyId: "0x00000069", keyLabel: "I", debugName: "Key I"), character: "i", timeStamp: 143:34:39.377453)
[log] FLUTTER ERROR: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═══════════════════════
The following assertion was thrown during a platform message
callback:
A KeyDownEvent is dispatched, but the state shows that the
physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's
event model as documented in `HardwareKeyboard`. This was the
event: KeyDownEvent#e3331(physicalKey:
PhysicalKeyboardKey#91fcd(usbHidUsage: "0x0007000c", debugName:
"Key I"), logicalKey: LogicalKeyboardKey#29639(keyId:
"0x00000069", keyLabel: "I", debugName: "Key I"), character: "i",
timeStamp: 143:34:39.377453)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 505 pos 16:
'!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:505:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:520:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:643:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1164:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
═════════════════════════════════════════════════════════════════

flutter: Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#e3331(physicalKey: PhysicalKeyboardKey#91fcd(usbHidUsage: "0x0007000c", debugName: "Key I"), logicalKey: LogicalKeyboardKey#29639(keyId: "0x00000069", keyLabel: "I", debugName: "Key I"), character: "i", timeStamp: 143:34:39.377453)
[log] FLUTTER ERROR: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞═══════════════════════
The following assertion was thrown during a platform message
callback:
A KeyDownEvent is dispatched, but the state shows that the
physical key is already pressed. If this occurs in real
application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's
event model as documented in `HardwareKeyboard`. This was the
event: KeyDownEvent#e3331(physicalKey:
PhysicalKeyboardKey#91fcd(usbHidUsage: "0x0007000c", debugName:
"Key I"), logicalKey: LogicalKeyboardKey#29639(keyId:
"0x00000069", keyLabel: "I", debugName: "Key I"), character: "i",
timeStamp: 143:34:39.377453)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 505 pos 16:
'!_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:505:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:520:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:643:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1164:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
#8      _invoke2 (dart:ui/hooks.dart:344:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
═════════════════════════════════════════════════════════════════

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by rekire** [comment]
Random guess, did you press a key while the first frame was not yet rendered?

**Comment by keithloughnane** [comment]
Interesting. I tried starting with shift pressed and it did lock up. In my case I had two widgets a bottom one taking up most of the screen that I want to get keyboard input (bonfire) and a popup. It's implemented as a stack of widgets and the popup is added or removed then required. For me it seems to happen when the popup is added and then removed. It's like it steals keyboard input from the bottom widget but then the popup is removed it never returns but it doesn't happen consistently.

**Comment by huycozy** [comment]
>Random guess, did you press a key while the first frame was not yet rendered and released it when the first frame was rendered?

@keithloughnane If you don't encounter this case, and only see the issue when app has already started, please try to narrow the code down into a minimal sample code so it will be easier for us to verify the issue, see [Provide reduced test cases](https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#provide-reduced-test-cases).

Also, which platform are you seeing this issue on? (Please also provide the output of `flutter doctor -v`). You can check this [search filter](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+physical+key+is+already+pressed+label%3A%22a%3A+text+input%22+shift+) and find if you encounter one of cases there.

**Comment by keithloughnane** [comment]
@huycozy Sorry I haven't had time to get back to this. I'm seeing it in both cases just the case with starting the app with the key down isn't how I initially noticed it. I was running on mac. I probably wont have time to create the test case for a while. If you need to close this for now I'll understand.

**Comment by huycozy** [comment]
It's ok. From my end, I attempted to reproduce the issue on a simple code with a Text only, by pressing `Shift` key before app launch but couldn't see the issue. 

Once you have consistent steps to reproduce along with a minimal sample for us, and there is no reported issue yet, please file a new issue when you have time. Thanks! Closing the issue from here.
