### ISSUE TITLE
Test fails with SIGABRT, error in unzipper_provider.cc, dart_init.cc

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#15731]
When I run the tests for my local app, I get these errors:

```
00:00 +0: /home/ianh/dev/cruisemonkey/test/calendar_test.dart: - Calendar
00:00 +1: loading /home/ianh/dev/cruisemonkey/test/karaoke_test.dart
00:00 +1: /home/ianh/dev/cruisemonkey/test/calendar_test.dart: - Calendar (Details)
00:00 +2: loading /home/ianh/dev/cruisemonkey/test/karaoke_test.dart
00:00 +2: /home/ianh/dev/cruisemonkey/test/calendar_test.dart: - Calendar (no reload on return)
00:01 +3: loading /home/ianh/dev/cruisemonkey/test/karaoke_test.dart
Shell: [ERROR:flutter/assets/unzipper_provider.cc(16)] Unable to open zip file: /tmp/dart_test_listenerMISGOB/listener.dart.dill
Shell: [FATAL:flutter/runtime/dart_init.cc(424)] Check failed: Dart_IsolateMakeRunnable(isolate).
00:01 +3 -1: loading /home/ianh/dev/cruisemonkey/test/karaoke_test.dart [E]
  Failed to load "/home/ianh/dev/cruisemonkey/test/karaoke_test.dart":
  Shell subprocess crashed with SIGABRT (-6) after tests finished.
  Test: /home/ianh/dev/cruisemonkey/test/karaoke_test.dart
  Shell: /home/ianh/dev/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester


00:03 +3 -1: /home/ianh/dev/cruisemonkey/test/drawer_test.dart: - Drawer
00:04 +4 -1: loading /home/ianh/dev/cruisemonkey/test/dynamic_test.dart
00:05 +4 -1: /home/ianh/dev/cruisemonkey/test/dynamic_test.dart: - DynamicView
00:05 +5 -1: loading /home/ianh/dev/cruisemonkey/test/deck_plans_test.dart
00:06 +5 -1: /home/ianh/dev/cruisemonkey/test/deck_plans_test.dart: - Deck Plans
00:07 +6 -1: loading /home/ianh/dev/cruisemonkey/test/progress_test.dart
00:08 +6 -1: /home/ianh/dev/cruisemonkey/test/progress_test.dart: - PollingValueNotifier
00:08 +7 -1: Some tests failed.
```

**Comment by Hixie** [comment]
Here's a self-contained test case that fails:

```dart
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

Future<void> main() async {
  final AssetBundle bundle = new TestAssetBundle();
  await initSongs(bundle);
}

class TestAssetBundle extends CachingAssetBundle {
  static const String songs =
    'My Artist\tMy Song\n'
    'Alexander Hamilton\tMy Shot\n'
    'Jonathan Coulton\tI Feel Fantastic';

  @override
  Future<ByteData> load(String key) async {
    if (key == 'resources/JoCoKaraokeSongCatalog.txt')
      return new ByteData.view(new Uint8List.fromList(utf8.encode(songs)).buffer);
    return null;
  }
}
 
class Song {
  const Song(this.title, this.artist);

  final String title;
  final String artist;
}
 
String catalogResource = 'resources/JoCoKaraokeSongCatalog.txt';

Future<void> initSongs(AssetBundle bundle) async {
  await bundle.loadStructuredData<List<Song>>(
    catalogResource,
    (String data) => compute<String, List<Song>>(_parser, data),
  );
  return null;
}
 
List<Song> _parser(String data) {
  final List<String> lines = data.split('\n');
  final List<Song> songs = <Song>[];
  for (String line in lines) {
    final List<String> parts = line.split('\t');
    if (parts.length >= 2)
      songs.add(new Song(parts[1], parts[0]));
  }
  songs.sort();
  return songs;
}
```

**Comment by Hixie** [comment]
cc @aam

**Comment by Hixie** [comment]
cc @a-siva

**Comment by jason-simmons** [comment]
This test is spawning an isolate.

It looks like isolates are not currently working in flutter_tester with Dart 2.

If I run a trivial test program in the latest flutter_tester:
```
foo(dynamic _) => print('foo');

main() {
  Isolate.spawn(foo, null); 
}
```

it produces an error:
```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: Isolates must use file:// URIs
#0      Isolate.spawn (dart:isolate-patch/dart:isolate/isolate_patch.dart:363)
<asynchronous suspension>
#1      main (test/foo.dart:46:11)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

The `IsolateCreateCallback` in `dart_init.cc` is being called with an invalid script_uri (the URI is `test/test/foo.dart` if the script was loaded from the file path `test/foo.dart`)

**Comment by anuragvohraec** [comment]
> This test is failing because it spawns an isolate.
> `IsolateCreateCallback` in `dart_init.cc` is looking for the suffix `.dart` in the script URI. If it doesn't see a `.dart` file, it thinks it's running from an FLX and tries to extract assets from there.

So whats the solution to the problem ?
How do we test an isolate based class ?
