### ISSUE TITLE
Rapidly switching with AnimatedSwitcher causes error:`Failed assertion: line 1191 pos 20: 'node.isRepaintBoundary': is not true.`

### ISSUE THREAD

**Issue by Peng-Qian** [flutter/flutter#157312]
### Steps to reproduce

1. Run the sample code.
2. Quickly click the button (log in and log out).

### Expected results

When switching back quickly, there should be no errors, and the animation should continue smoothly

### Actual results

Cause the app to break and freeze.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool signedIn = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: AnimatedSwitcher(
        duration: const Duration(seconds: 1),
        child: signedIn
            ? HomeScreen(onPressed: () => setState(() => signedIn = false))
            : AuthScreen(onPressed: () => setState(() => signedIn = true)),
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  static const routeName = 'homeScreen';

  final VoidCallback onPressed;

  const HomeScreen({super.key, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: const ValueKey('homeScreen'),
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: const Text('Home Screen', style: TextStyle(color: Colors.white)),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: onPressed,
          style: ButtonStyle(backgroundColor: WidgetStateProperty.all(Colors.blue)),
          child: const Text('log out', style: TextStyle(color: Colors.white)),
        ),
      ),
    );
  }
}

class AuthScreen extends StatelessWidget {
  static const routeName = 'authScreen';

  final VoidCallback onPressed;

  const AuthScreen({super.key, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.blue,
        title: const Text('Auth Screen', style: TextStyle(color: Colors.white)),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: onPressed,
          style: ButtonStyle(backgroundColor: WidgetStateProperty.all(Colors.blue)),
          child: const Text('log in', style: TextStyle(color: Colors.white)),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/76e42e97-7d61-4356-902e-673afd2829c8

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
[✓] VS Code (version 1.77.1)
[✓] Connected device (5 available)
[✓] Network resources

```

</details>

**Comment by Peng-Qian** [comment]
I know there’s a workaround using SizedBox to wrap the child and controlling changes with a key, but I’m wondering if this issue can be properly fixed. Otherwise, we would need to wrap all children or create a SafeAnimatedSwitcher to ensure proper functionality across all switchers.

**Comment by huycozy** [comment]
Reproduced this issue on Flutter master channel `3.27.0-1.0.pre.151` and also on the previous stable release `3.22.3`. 

There was an issue with a similar error stack trace at https://github.com/flutter/flutter/issues/120874 which was fixed. 

<details open>
<summary>Error stack trace</summary>

```console
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1191 pos 20: 'node.isRepaintBoundary': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1191:20)
object.dart:1191
#3      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1203:15)
object.dart:1203
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:611:23)
binding.dart:611
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178:13)
binding.dart:1178
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
binding.dart:475
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
binding.dart:1176
#10     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
platform_dispatcher.dart:427
#12     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by YeungKC** [comment]
I am interested in this issue, but I am curious, if instead of using a click to trigger, we continuously switch signedIn automatically, will the same problem occur?
