### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: Unexpected end of document on app installation

### ISSUE THREAD

**Issue by AwaisQazii** [flutter/flutter#157332]
### Steps to reproduce

1. org.xmlpull.v1.XmlPullParserException: Unexpected end of document on app installation

### Expected results

- 

### Actual results

Cannot read /data/user/0/com.myapp_demo/shared_prefs/RpT1ZU1I8L1DwWmyTpvIyhI9aQbDIthNwKg8uhl1Vdwo.xml
org.xmlpull.v1.XmlPullParserException: Unexpected end of document 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

W/SharedPreferencesImpl(11064): Cannot read /data/user/0/com.myapp_demo/shared_prefs/RpT1ZU1I8L1DwWmyTpvIyhI9aQbDIthNwKg8uhl1Vdwo.xml
W/SharedPreferencesImpl(11064): org.xmlpull.v1.XmlPullParserException: Unexpected end of document
W/SharedPreferencesImpl(11064): 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1549)
W/SharedPreferencesImpl(11064): 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:970)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:171)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl.-$$Nest$mloadFromDisk(Unknown Source:0)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:140)
W/SharedPreferencesImpl(11064): Cannot read /data/user/0/com.myapp_demo/shared_prefs/Wlt1W1fPbJpd4ruaWXEfSOI6xIP5pXkILsDlQskY.xml
W/SharedPreferencesImpl(11064): org.xmlpull.v1.XmlPullParserException: Unexpected end of document
W/SharedPreferencesImpl(11064): 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1549)
W/SharedPreferencesImpl(11064): 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:970)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:171)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl.-$$Nest$mloadFromDisk(Unknown Source:0)
W/SharedPreferencesImpl(11064): 	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:140)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-PK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (version 2023.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.94.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

</details>

**Comment by danagbemava-nc** [comment]
Hi @AwaisQazii, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can properly investigate this issue. Please also provide the version of `shared_preferences` & `shared_preferences_android` you're using. 

Also, what device(s) are you seeing this on and can you reproduce this locally?

**Comment by AwaisQazii** [comment]
This issue is resolved after update . Thank you for your prompt response

**Comment by danagbemava-nc** [comment]
Closing based on https://github.com/flutter/flutter/issues/157332#issuecomment-2469910102
