### ISSUE TITLE
`flutter <build> <ios>` regenerates plugins multiple times

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#157391]
To reproduce:

```diff
diff --git a/packages/flutter_tools/lib/src/flutter_plugins.dart b/packages/flutter_tools/lib/src/flutter_plugins.dart
index 67e9799087..0f543219f5 100644
--- a/packages/flutter_tools/lib/src/flutter_plugins.dart
+++ b/packages/flutter_tools/lib/src/flutter_plugins.dart
@@ -1011,6 +1011,7 @@ Future<void> refreshPluginsList(
   bool macOSPlatform = false,
   bool forceCocoaPodsOnly = false,
 }) async {
+  print('>>> refreshPluginList() ::: ${StackTrace.current}');
   final List<Plugin> plugins = await findPlugins(project);
   // Sort the plugins by name to keep ordering stable in generated files.
   plugins.sort((Plugin left, Plugin right) => left.name.compareTo(right.name));

```

And then create and run an iOS (and I believe, MacOS) build:

```sh
$ flutter create . --platforms ios

>>> refreshPluginList() :: refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1103:51)
#1      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:373:11)
#2      FlutterProject.regeneratePlatformSpecificTooling (package:flutter_tools/src/project.dart:344:12)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1793:21)

>>> refreshPluginList() ::: #0      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1103:51)
#1      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:29:9)
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:280:9)
#3      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:701:37)
```

As far as I can tell, every `FlutterCommand` regenerates plugins as long as `shouldRunPub` is set, so when the code was added (again) in https://github.com/flutter/flutter/pull/146256 it might have been duplicate work? Defer to the iOS team, maybe they see something I don't.

(This complicates conditionally removing the `.flutter-plugins` file which is why I'm bringing it up)

**Comment by matanlurey** [comment]
I looked into this, and it feels like this was added in order to make the tests pass - again defer to the iOS folks to be certain.

**Comment by jmagman** [comment]
I don't think it was added in https://github.com/flutter/flutter/pull/146256, but the call site parameters were changed. 

The behavior was moved a few times but I think it was added here? https://github.com/flutter/flutter/pull/21276/files#diff-5908b963d89d579976aca7c6a2c3043d09a71206e19976d645aace43757431a0R337

I can't think of why it would be necessary to call a second time.  We could remove it from `processPodsIfNeeded` and see what breaks.

**Comment by matanlurey** [comment]
As-per discussion on https://github.com/flutter/flutter/pull/157393 I'll re-assign this to @loic-sharma and land a short-term fix instead.

**Comment by matanlurey** [comment]
@loic-sharma I'm running into a case where this is (soft)-blocking again.

I can either work around it, try to take a shot at this issue myself, or I'll need your help finishing this cleanup.
