### ISSUE TITLE
Updating engine sources and rebuilding causes errors during file copy.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#157367]
On macOS, I see the following errors.

```
FAILED: artifacts_x64/gen_snapshot_arm64 
vpython3 ../../flutter/sky/tools/cp.py /src/out/host_debug_unopt_arm64/clang_x64/gen_snapshot /src/out/host_debug_unopt_arm64/artifacts_x64/gen_snapshot_arm64
Traceback (most recent call last):
  File "../../flutter/sky/tools/cp.py", line 25, in <module>
    sys.exit(main(sys.argv[1], sys.argv[2]))
  File "../../flutter/sky/tools/cp.py", line 20, in main
    shutil.copy(src, os.path.normpath(dst))
  File "/Caches/.vpython-root/store/python_venv-v4nknu7iae9tlv5ufkeqoi6jjs/contents/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Caches/.vpython-root/store/python_venv-v4nknu7iae9tlv5ufkeqoi6jjs/contents/lib/python3.8/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/src/out/host_debug_unopt_arm64/clang_x64/gen_snapshot' and '/src/out/host_debug_unopt_arm64/artifacts_x64/gen_snapshot_arm64' are the same file
ninja: build stopped: subcommand failed.
```

This patch looks like the culprit https://github.com/flutter/engine/pull/55830. cc @aam

**Comment by chinmaygarde** [comment]
The linked PR has been reverted. To reproduce, it is sufficient to perform a build before applying the PR and trying again. This reproduces reliably on macOS (M1 Max).

**Comment by aam** [comment]
thank you @chinmaygarde . I uploaded https://github.com/flutter/engine/pull/56061 with the fix.
