### ISSUE TITLE
[tool_crash] _CompileTimeError: (#0      _ChunkedJsonParser.parseStringToBuffer (dart:convert-patch/convert_patch.dart:1099:18))

### ISSUE THREAD

**Issue by royscs71** [flutter/flutter#157400]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CompileTimeError: (#0      _ChunkedJsonParser.parseStringToBuffer (dart:convert-patch/convert_patch.dart:1099:18))
```
#0      _ChunkedJsonParser.parseStringToBuffer (dart:convert-patch/convert_patch.dart:1099:18)
#1      _ChunkedJsonParser.parseString (dart:convert-patch/convert_patch.dart:1014:16)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:835:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      new AppResourceBundle (package:flutter_tools/src/localizations/gen_l10n_types.dart:580:26)
#7      LocalizationsGenerator._templateBundle (package:flutter_tools/src/localizations/gen_l10n.dart:553:50)
#8      LocalizationsGenerator._templateBundle (package:flutter_tools/src/localizations/gen_l10n.dart)
#9      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:914:37)
#10     generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:78:9)
#11     GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:60:11)
#12     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:27)
<asynchronous suspension>
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#14     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:57:30)
<asynchronous suspension>
#15     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:307:9)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#18     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-x64, locale
    en-US)
    [32m•[39m Flutter version 3.22.2 on channel stable at /Users/roy/stuff/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/roy/stuff/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m ANDROID_HOME = /Users/roy/stuff/sdk
    [32m•[39m ANDROID_SDK_ROOT = /Users/roy/stuff/sdk
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[31m[☠][39m Xcode - develop for iOS and macOS (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    [31m✗[39m error: Unexpected tag 0 (Nothing) in
      __JsonStringParser&_JsonParserWithListener&_ChunkedJsonParser@10003594.par
      seStringEscape, expected declaration
    [32m•[39m #0      _ChunkedJsonParser.parseStringToBuffer
      (dart:convert-patch/convert_patch.dart:1099:18)
      #1      _ChunkedJsonParser.parseString
      (dart:convert-patch/convert_patch.dart:1014:16)
      #2      _ChunkedJsonParser.parse
      (dart:convert-patch/convert_patch.dart:835:22)
      #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
      #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
      #5      JsonCodec.decode (dart:convert/json.dart:216:41)
      #6      SimControl.listAvailableIOSRuntimes
      (package:flutter_tools/src/ios/simulators.dart:327:42)
      <asynchronous suspension>
      #7      XcodeValidator._validateSimulatorRuntimeInstalled
      (package:flutter_tools/src/macos/xcode_validator.dart:113:48)
      <asynchronous suspension>
      #8      XcodeValidator.validate
      (package:flutter_tools/src/macos/xcode_validator.dart:74:58)
      <asynchronous suspension>
      #9      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>


[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /Applications/Microsoft
      Edge.app/Contents/MacOS/Microsoft Edge

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone XXX (mobile) • ce4a1603f063ea6b173616da3ed710e591cbb157 • ios
      • iOS 16.7.10 20H350
    [32m•[39m macOS (desktop)     • macos                                    •
      darwin-x64     • macOS 14.5 23F79 darwin-x64
    [32m•[39m Chrome (web)        • chrome                                   •
      web-javascript • Microsoft Edge 128.0.2739.79

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment]
Hi @royscs71, can you upgrade to the latest version of flutter stable 3.24.3 to see if you still experience this issue?

**Comment by royscs71** [comment]
Hi @danagbemava-nc, Thank to your response.
I try to re-install Xcode (it's pain) and run `flutter clean` then the issue is gone

**Comment by danagbemava-nc** [comment]
Glad the issue has been resolved. 

Closing based on https://github.com/flutter/flutter/issues/157400#issuecomment-2432686508
