### ISSUE TITLE
GoRouter nested navigation error !keyReservation.contains(key)

### ISSUE THREAD

**Issue by rsids** [flutter/flutter#157436]
### Steps to reproduce

In an application which uses GoRouter shellroutes, navigate using GoRouter.push() from a route to a nested route throws a ` !keyReservation.contains(key)` error.
In the example: one can navigate between nestedA/B/C without problems, one can navigate between outerA & outerB, but navigating from outer to nested throws an exception

### Expected results

The application should navigate to the nested route

### Actual results

The application throws:
`_AssertionError ('package:flutter/src/widgets/navigator.dart': Failed assertion: line 3925 pos 18: '!keyReservation.contains(key)': is not true.)`

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}

class HomePage extends StatelessWidget {
  final Widget child;
  const HomePage({super.key, required this.child});
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: child);
  }
}

class AppPage extends StatelessWidget {
  final String page;
  const AppPage({super.key, required this.page});

  @override
  Widget build(BuildContext context) {
    List<String> buttons = [
      'start',
      'nestedA',
      'nestedB',
      'nestedC',
      'outerA',
      'outerB',
    ];
    return SafeArea(
      child: Column(
        children: [
          Text(
            page,
            style: Theme.of(context).textTheme.displayLarge,
          ),
          ...buttons.map((b) => TextButton(
              onPressed: () => GoRouter.of(context).pushNamed(b),
              child: Text(b)))
        ],
      ),
    );
  }
}

final GlobalKey<NavigatorState> _rootNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _shellNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'shell');
final GlobalKey<NavigatorState> _overlayNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'overlay');

double startOffset = 1.0;
final GoRouter router = GoRouter(
  navigatorKey: _rootNavigatorKey,
  initialLocation: '/',
  routes: <RouteBase>[
    ShellRoute(
        navigatorKey: _overlayNavigatorKey,
        builder: (context, state, child) => child,
        routes: [
          ShellRoute(
            navigatorKey: _shellNavigatorKey,
            pageBuilder: (context, state, child) {
              return transitionPageBuilder(context, state,
                  child: HomePage(child: child));
            },
            routes: <RouteBase>[
              GoRoute(
                parentNavigatorKey: _shellNavigatorKey,
                path: '/',
                name: AppRoutes.start,
                pageBuilder: (context, state) {
                  return transitionPageBuilder(context, state);
                },
              ),
              GoRoute(
                parentNavigatorKey: _shellNavigatorKey,
                path: '/nestedA',
                name: AppRoutes.nestedA,
                pageBuilder: (context, state) =>
                    transitionPageBuilder(context, state),
              ),
              GoRoute(
                parentNavigatorKey: _shellNavigatorKey,
                path: '/nestedB',
                name: AppRoutes.nestedB,
                pageBuilder: (context, state) =>
                    transitionPageBuilder(context, state),
              ),
              GoRoute(
                parentNavigatorKey: _shellNavigatorKey,
                path: '/nestedC',
                name: AppRoutes.nestedC,
                builder: (BuildContext context, state) =>
                    openPage(context, state),
              ),
            ],
          ),
          GoRoute(
            path: '/outerA',
            name: AppRoutes.outerA,
            parentNavigatorKey: _overlayNavigatorKey,
            pageBuilder: (context, state) {
              return transitionPageBuilder(context, state);
            },
          ),
          GoRoute(
            path: '/outerB',
            name: AppRoutes.outerB,
            parentNavigatorKey: _overlayNavigatorKey,
            pageBuilder: (context, state) {
              return transitionPageBuilder(context, state);
            },
          ),
        ]),
  ],
);

CustomTransitionPage transitionPageBuilder(context, GoRouterState state,
    {Widget? child}) {
  if (state.extra != null) {
    startOffset = (state.extra as Map)['forward'] == true ? 1.0 : -1.0;
  }
  return CustomTransitionPage(
    key: state.pageKey,
    transitionDuration: Durations.medium1,
    child: child ?? openPage(context, state),
    transitionsBuilder: (context, animation, secondaryAnimation, child) {
      if (secondaryAnimation.value > 0.0 && secondaryAnimation.value < 1.0) {
        return SlideTransition(
          position: Tween<Offset>(
                  begin: Offset.zero, end: Offset(startOffset * -1, 0))
              .animate(secondaryAnimation),
          child: child,
        );
        // } else {
      }

      return SlideTransition(
        position: Tween<Offset>(begin: Offset(startOffset, 0), end: Offset.zero)
            .animate(animation),
        child: child,
      );
    },
  );
}

class AppRoutes {
  static const String start = 'start';
  static const String nestedA = 'nestedA';
  static const String nestedB = 'nestedB';
  static const String outerA = 'outerA';
  static const String outerB = 'outerB';
  static const String nestedC = 'nestedC';
}

Widget openPage(BuildContext context, GoRouterState state) {
  return AppPage(page: state.name ?? 'unknown');
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
#139    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
framework.dart:5803
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
framework.dart:3941
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
framework.dart:5642
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
framework.dart:5780
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
framework.dart:5333
#144    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
framework.dart:2693
#145    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
framework.dart:2752
#146    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
framework.dart:3048
#147    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
binding.dart:1162
#148    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#149    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#150    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#151    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
binding.dart:1176
#152    _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#153    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#154    _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-NL)
    • Flutter version 3.24.3 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (5 available)
    • iPhone van xxx (mobile)         • 00008110-001959263491801E            • ios            • iOS 17.6.1 21G93
    • iPhone 15 Pro Max (mobile)      • FF0DCC77-3FEE-4C00-AACE-BE09E097AD49 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 130.0.6723.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/140586.

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you
