### ISSUE TITLE
[tool_crash] ProcessException: The command failed Command: ohpm, OS error code: 1

### ISSUE THREAD

**Issue by mao0808** [flutter/flutter#157408]
## Command
```
flutter build hap --debug --local-engine=/Users/mao/Work/flutter_engine/src/out/ohos_release_arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed Command: ohpm, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:414:17)
#2      ohpmInstall (package:flutter_tools/src/ohos/hvigor.dart:124:16)
#3      OhosHvigorBuilder.flutterBuildPre (package:flutter_tools/src/ohos/hvigor.dart:544:11)
<asynchronous suspension>
#4      OhosHvigorBuilder.buildApplicationPipeLine (package:flutter_tools/src/ohos/hvigor.dart:671:5)
<asynchronous suspension>
#5      OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:467:5)
<asynchronous suspension>
#6      BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:80:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel master, 3.7.12-ohos-1.0.2, on macOS 14.4.1 23E224 darwin-arm64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.7.12-ohos-1.0.2 on channel master at /Users/mao/Work/flutter_flutter
    [32m•[39m Upstream repository https://gitee.com/openharmony-sig/flutter_flutter.git
    [32m•[39m FLUTTER_GIT_URL = https://gitee.com/openharmony-sig/flutter_flutter.git
    [32m•[39m Framework revision 7a712dd5fd (6 hours ago), 2024-10-23 03:14:17 +0000
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn

[32m[✓][39m HarmonyOS toolchain - develop for HarmonyOS devices
    [32m•[39m OpenHarmony Sdk at /Applications/DevEco-Studio.app/Contents/sdk, available api versions has [12:default]
    [32m•[39m Ohpm version 5.0.7
    [32m•[39m Node version v18.20.1
    [32m•[39m Hvigorw binary at /Applications/DevEco-Studio.app/Contents/tools/hvigor/bin/hvigorw

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    [32m•[39m Android SDK at /Users/mao/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 15.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15E204a
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[31m[✗][39m Cannot determine if IntelliJ is installed
    [31m✗[39m Directory listing failed

[32m[✓][39m Connected device (3 available)
    [32m•[39m FMR0223C13000131 (mobile) • FMR0223C13000131 • ohos-arm64     • Ohos OpenHarmony-5.0.1.71 (API 13)
    [32m•[39m macOS (desktop)           • macos            • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    [32m•[39m Chrome (web)              • chrome           • web-javascript • Google Chrome 130.0.6723.60

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by danagbemava-nc** [comment]
This should be reported on [gitee.com/openharmony-sig/flutter_flutter](https://gitee.com/openharmony-sig/flutter_flutter).

Make sure you have all the required tools installed.

Closing from here.

Thank you
