### ISSUE TITLE
gclient sync of the engine cannot pull flutter/java/openjdk/linux-aarch64

### ISSUE THREAD

**Issue by RossComputerGuy** [flutter/flutter#157576]
I get an error saying gclient cannot find `flutter/java/openjdk/linux-aarc64` on aarch64 Linux. Looks like it doesn't exist? https://chrome-infra-packages.appspot.com/p/flutter/java/openjdk

```
> ________ running 'cipd ensure -log-level error -root /nix/store/q0pwqcvz1il5b0b38h6r8agnifx8v2cr-flutter-engine-source-af0f0d559c8a87d912a20971bbd84afc80a54b0f-x86_64-linux-x86_64-linux -ensure-file /build/tmpzwogih2k.ensure' in '.'
> Errors:
>   failed to resolve flutter/java/openjdk/linux-arm64@version:17 (line 23): no such package: flutter/java/openjdk/linux-arm64
> Error: Command 'cipd ensure -log-level error -root /nix/store/q0pwqcvz1il5b0b38h6r8agnifx8v2cr-flutter-engine-source-af0f0d559c8a87d912a20971bbd84afc80a54b0f-x86_64-linux-x86_64-linux -ensure-file /build/tmpzwogih2k.ensure' returned non-zero exit status 1
> Errors:
>   failed to resolve flutter/java/openjdk/linux-arm64@version:17 (line 23): no such package: flutter/java/openjdk/linux-arm64
```

**Comment by huycozy** [comment]
Hi @RossComputerGuy 
Can you please provide the information indicated below? 

- Are you compiling for Linux? If not, which target platform are you compiling for? (Refer to https://github.com/flutter/engine/blob/main/docs/contributing/Compiling-the-engine.md)
- Did you make any modifications to the engine that you built or use the default engine code on main/master channel? Please share the output of `flutter doctor -v` as well.
- Please share the entire error stack trace if any. Thanks!

**Comment by RossComputerGuy** [comment]
I'm compiling for aarch64-linux on aarch64-linux. I am using the engine from Flutter `3.27.0-0.1.pre` which is `af0f0d559c8a87d912a20971bbd84afc80a54b0f` so there's no modifications. There are no other errors.

**Comment by jonahwilliams** [comment]
From triage: we don't think its possible to build the engine on linux arm currently. The prior strategy for linux arm64 was to cross compile.

**Comment by RossComputerGuy** [comment]
I've been compiling the engine on native aarch64 for the past year.

**Comment by jonahwilliams** [comment]
We didn't know that would work

**Comment by WaterSandy** [comment]
> It's fine, not many people are developing on aarch64 Linux systems. I was able to forcefully remove the OpenJDK package and compile this version of the engine.

I also meet this problem, can you tell me how to forcefully remove the OpenJDK package

**Comment by knopp** [comment]
Can confirm that this is a regression. It was possible to build linux/arm64 engine on apple silicon in a virtual machine without having to edit DEPS.

**Comment by digimap2000** [comment]
I am also seeing this issue on both ARMv8 (arm64) and ARMv7 (arm) having previously built on both.

It looks like someone decided that it was undesirable to require the host to have java runtime preinstalled and made installation of openJDK a mandatory part of the dependencies. Of course this fails miserably when trying to compile on something other than the big platforms.

For reference it is this commit:
https://github.com/flutter/engine/commit/19d858e0202d2cafe5bf768c258eb50f19a3181a

The fix is to edit the src/flutter/DEP file to put the dependancy on android back in then make sure your android dependency resolves to false (or just hard code it).

**Comment by lhoward** [comment]
Does anyone with sufficient gn-fu know if it's possible to override the JDK dependency by setting `custom_deps` and/or `custom_vars`? We're using Yocto to build the engine and patching the DEPS file would be cumbersome.

**Comment by RossComputerGuy** [comment]
> Does anyone with sufficient gn-fu know if it's possible to override the JDK dependency by setting `custom_deps` and/or `custom_vars`?

I tried that when I originally discovered this issue in nixpkgs, it didn't work. Not sure why but gclient seems to ignore `custom_deps` with cipd.

**Comment by AngeloAvv** [comment]
> [@AngeloAvv](https://github.com/AngeloAvv) I can compile the engine but it requires modifying gclient DEPS stuff so I don't get the openjdk error.

Have you tried doing it recently? If I try to restore the `'condition': 'download_android_deps',` as mentioned in the comments above, I'm facing a similar issue with llvm-readelf

I'm using the Flutter 3.38.5 tag reference.

```
flutter_builder  | Installing Git Hooks
flutter_builder  | ________ running 'python3 engine/src/flutter/tools/fuchsia/with_envs.py engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py' in '/home/builder/work'
flutter_builder  | Traceback (most recent call last):
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 519, in <module>
flutter_builder  |     sys.exit(main())
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 515, in main
flutter_builder  |     ProcessSdkManifest()
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 491, in ProcessSdkManifest
flutter_builder  |     PopulateBuildIdDirectory(toplevel_meta)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 460, in PopulateBuildIdDirectory
flutter_builder  |     parser(meta_json)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 432, in parse_cc_prebuilt_library
flutter_builder  |     probe_path(values.get("debug"))
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 404, in probe_path
flutter_builder  |     build_id = GetGnuBuildId(debug_path, readelf_path)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 104, in GetGnuBuildId
flutter_builder  |     ret = subprocess.run([readelf_path, "-n", elf_file],
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 493, in run
flutter_builder  |     with Popen(*popenargs, **kwargs) as process:
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 858, in init
flutter_builder  |     self._execute_child(args, executable, preexec_fn, close_fds,
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 1704, in _execute_child
flutter_builder  |     raise child_exception_type(errno_num, err_msg, err_filename)
flutter_builder  | FileNotFoundError: [Errno 2] No such file or directory: '/home/builder/work/engine/src/flutter/buildtools/linux-x64/clang/bin/llvm-readelf'
flutter_builder  | Error: Command 'python3 engine/src/flutter/tools/fuchsia/with_envs.py engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py' returned non-zero exit status 1 in /home/builder/work
flutter_builder  | Traceback (most recent call last):
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 519, in <module>
flutter_builder  |     sys.exit(main())
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 515, in main
flutter_builder  |     ProcessSdkManifest()
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 491, in ProcessSdkManifest
flutter_builder  |     PopulateBuildIdDirectory(toplevel_meta)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 460, in PopulateBuildIdDirectory
flutter_builder  |     parser(meta_json)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 432, in parse_cc_prebuilt_library
flutter_builder  |     probe_path(values.get("debug"))
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 404, in probe_path
flutter_builder  |     build_id = GetGnuBuildId(debug_path, readelf_path)
flutter_builder  |   File "engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py", line 104, in GetGnuBuildId
flutter_builder  |     ret = subprocess.run([readelf_path, "-n", elf_file],
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 493, in run
flutter_builder  |     with Popen(*popenargs, **kwargs) as process:
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 858, in init
flutter_builder  |     self._execute_child(args, executable, preexec_fn, close_fds,
flutter_builder  |   File "/home/builder/.cache/vpython-root.1000/store/cpython+c02ee5virn3bdf1gtjhtljl34k/contents/lib/python3.8/subprocess.py", line 1704, in _execute_child
flutter_builder  |     raise child_exception_type(errno_num, err_msg, err_filename)
flutter_builder  | FileNotFoundError: [Errno 2] No such file or directory: '/home/builder/work/engine/src/flutter/buildtools/linux-x64/clang/bin/llvm-readelf'
flutter_builder  |
flutter_builder  | Hook 'python3 engine/src/flutter/tools/fuchsia/with_envs.py engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py' took 38.62 secs
```

I tried building everything in a Docker container, but I'm facing the same issue on two different devices: an Apple Silicon Debian 13 VM and on a cross compiling on amd64 workstation.
