### ISSUE TITLE
Always encountering [dev.flutter.pigeon.path_provider_android.PathProviderApi.getApplicationDocumentsPath"., null, null)] error

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#157586]
### Steps to reproduce

1

### Expected results

1

### Actual results

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on M2011K2C in debug mode...
Running Gradle task 'assembleDebug'...
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: ClientException with SocketException: 信号灯超时时间已�?
SEVERE:  (OS Error: 信号灯超时时间已�?
SEVERE: , errno = 121), address = github.com, port = 54232, uri=https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/aarch64-linux-android_libirondash_engine_context_native.so.sig
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      IOClient.send (package:http/src/io_client.dart:119:7)
SEVERE: <asynchronous suspension>
SEVERE: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
SEVERE: <asynchronous suspension>
SEVERE: #2      _withClient (package:http/http.dart:166:12)
SEVERE: <asynchronous suspension>
SEVERE: #3      ArtifactProvider._get (package:build_tool/src/artifacts_provider.dart:165:16)
SEVERE: <asynchronous suspension>
SEVERE: #4      ArtifactProvider._tryDownloadArtifacts (package:build_tool/src/artifacts_provider.dart:192:23)
SEVERE: <asynchronous suspension>
SEVERE: #5      ArtifactProvider._getPrecompiledArtifacts (package:build_tool/src/artifacts_provider.dart:133:11)
SEVERE: <asynchronous suspension>
SEVERE: #6      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:54:20)
SEVERE: <asynchronous suspension>
SEVERE: #7      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #8      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #9      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #11     runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
√ Built build\app\outputs\flutter-apk\app-debug.apk
Installing build\app\outputs\flutter-apk\app-debug.apk...
```

```
D:\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [版本 10.0.22631.4391], locale zh-CN)
    • Flutter version 3.24.3 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\AndroidSDK\SDK14.0
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:/AndroidSDK/SDK14.0
    • Java binary at: D:\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.4
    • Flutter plugin version 82.0.1
    • Dart plugin version 233.15325.11

[√] Connected device (5 available)
    • M2011K2C (mobile)            • 198e9c6       • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.22631.4391]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 130.0.2849.46

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
Process finished with exit code 0
```

```
I/flutter (22406): PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.path_provider_android.PathProviderApi.getApplicationDocumentsPath"., null, null)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ddxl123, please provide a complete minimal reproducible code sample without any third party packages so that we can properly investigate this. 

Please also provide the version of `path_provider` & `path_provider_android` you're using. 

Thank you

**Comment by ddxl123** [comment]
> Hi @ddxl123, please provide a complete minimal reproducible code sample without any third party packages so that we can properly investigate this.
> 
> Please also provide the version of `path_provider` & `path_provider_android` you're using.
> 
> Thank you

```
path: ^1.9.0
path_provider: ^2.1.4
path_provider_android: ^2.2.12
package_info_plus: ^8.0.2
```

I cannot reproduce this problem. It occurs sporadically and I don't know under what circumstances it will return to normal. I am on the Chinese network. However, whether there is a proxy or not, it occurs sporadically. But once it occurs, it is fatal and will lead to the inability to use functions such as PackageInfo.fromPlatform() and getApplicationDocumentsPath().


```
Launching lib\main.dart on M2011K2C in debug mode...
Running Gradle task 'assembleDebug'...
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: ClientException with SocketException: 信号灯超时时间已�?
SEVERE:  (OS Error: 信号灯超时时间已�?
SEVERE: , errno = 121), address = github.com, port = 49704, uri=https://github.com/irondash/irondash/releases/download/precompiled_c8cbb92de1e8b3dc787cdf8cb122c753/aarch64-linux-android_libirondash_engine_context_native.so.sig
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      IOClient.send (package:http/src/io_client.dart:119:7)
SEVERE: <asynchronous suspension>
SEVERE: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
SEVERE: <asynchronous suspension>
SEVERE: #2      _withClient (package:http/http.dart:166:12)
SEVERE: <asynchronous suspension>
SEVERE: #3      ArtifactProvider._get (package:build_tool/src/artifacts_provider.dart:165:16)
SEVERE: <asynchronous suspension>
SEVERE: #4      ArtifactProvider._tryDownloadArtifacts (package:build_tool/src/artifacts_provider.dart:192:23)
SEVERE: <asynchronous suspension>
SEVERE: #5      ArtifactProvider._getPrecompiledArtifacts (package:build_tool/src/artifacts_provider.dart:133:11)
SEVERE: <asynchronous suspension>
SEVERE: #6      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:54:20)
SEVERE: <asynchronous suspension>
SEVERE: #7      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #8      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #9      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #11     runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
SEVERE: ================================================================================
SEVERE: Cargokit BuildTool failed with error:
SEVERE: --------------------------------------------------------------------------------
SEVERE: ClientException with SocketException: 信号灯超时时间已�?
SEVERE:  (OS Error: 信号灯超时时间已�?
SEVERE: , errno = 121), address = github.com, port = 49467, uri=https://github.com/superlistapp/super_native_extensions/releases/download/precompiled_3bf6bd97fc3bb54fbbb337876cad5ca3/aarch64-linux-android_libsuper_native_extensions.so.sig
SEVERE: --------------------------------------------------------------------------------
SEVERE: #0      IOClient.send (package:http/src/io_client.dart:119:7)
SEVERE: <asynchronous suspension>
SEVERE: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
SEVERE: <asynchronous suspension>
SEVERE: #2      _withClient (package:http/http.dart:166:12)
SEVERE: <asynchronous suspension>
SEVERE: #3      ArtifactProvider._get (package:build_tool/src/artifacts_provider.dart:165:16)
SEVERE: <asynchronous suspension>
SEVERE: #4      ArtifactProvider._tryDownloadArtifacts (package:build_tool/src/artifacts_provider.dart:192:23)
SEVERE: <asynchronous suspension>
SEVERE: #5      ArtifactProvider._getPrecompiledArtifacts (package:build_tool/src/artifacts_provider.dart:133:11)
SEVERE: <asynchronous suspension>
SEVERE: #6      ArtifactProvider.getArtifacts (package:build_tool/src/artifacts_provider.dart:54:20)
SEVERE: <asynchronous suspension>
SEVERE: #7      BuildGradle.build (package:build_tool/src/build_gradle.dart:32:23)
SEVERE: <asynchronous suspension>
SEVERE: #8      BuildGradleCommand.runBuildCommand (package:build_tool/src/build_tool.dart:62:5)
SEVERE: <asynchronous suspension>
SEVERE: #9      BuildCommand.run (package:build_tool/src/build_tool.dart:34:5)
SEVERE: <asynchronous suspension>
SEVERE: #10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
SEVERE: <asynchronous suspension>
SEVERE: #11     runMain (package:build_tool/src/build_tool.dart:248:5)
SEVERE: <asynchronous suspension>
SEVERE: --------------------------------------------------------------------------------
SEVERE: BuildTool arguments: [build-gradle]
SEVERE: ================================================================================
√ Built build\app\outputs\flutter-apk\app-debug.apk
Debug service listening on ws://127.0.0.1:49607/R827o-Cc8tY=/ws
Syncing files to device M2011K2C...
[GETX] Instance "GlobalLogic" has been created
[GETX] Instance "GlobalLogic" has been initialized
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized
[GETX] GOING TO ROUTE /home
[GETX] Instance "HomeLogic" has been created
[GETX] Instance "HomeLogic" has been initialized
W/OnBackInvokedCallback(10515): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(10515): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/libEGL  (10515): pre_cache appList: ,,
E/flutter (10515): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
E/flutter (10515): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:80:26)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #4      LocalInstance._initAppInfo (package:aaa_memory/global/local_instance.dart:75:19)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #5      LocalInstance.init (package:aaa_memory/global/local_instance.dart:34:5)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): #6      GlobalLogic._futureInit (package:aaa_memory/global/global_logic_state/logic.dart:27:5)
E/flutter (10515): <asynchronous suspension>
E/flutter (10515): 
D/long.aaa_memory(10515): MiuiProcessManagerServiceStub setSchedFifo
```

**Comment by danagbemava-nc** [comment]
Hi @ddxl123, how do you build your app? Do you have some intermediary tool that runs some processes before flutter starts? 

Do you get this issue with a newly created flutter app?

**Comment by dupuisdavid** [comment]
Hello! Got the same exception but only on Xiaomi device.
`I/flutter (23791): PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.path_provider_android.PathProviderApi.getApplicationDocumentsPath"., null, null)
I/flutter (23791): #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_android/messages.g.dart:148:7)
I/flutter (23791): <asynchronous suspension>
I/flutter (23791): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)`


[✓] Flutter (Channel stable, 3.22.2, on macOS 15.0.1 24A348 darwin-arm64, locale fr-FR)
    • Flutter version 3.22.2 on channel stable at /Users/dd/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/dupuisdavid/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/dd/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/dupuisdavid/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • 21081111RG (mobile)             • mbr8zt4xvoprprqc      • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.117
    ! Error: Browsing on the local area network for iPhone de iPhone12. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!


>   path_provider: ^2.1.3
  path: ^1.9.0

**Comment by danagbemava-nc** [comment]
Hi @dupuisdavid, do you only get this issue when you try to call `getApplicationDocumentsDirectory`  or do you get this with other path_provider methods as well?

**Comment by ganjiajun-ola** [comment]
hello @danagbemava-nc we got the same exception but only on Xiaomi device.

I think other libraries are affected as well

```
I/flutter (16849): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16849): │ 
I/flutter (16849): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (16849): │ #0   PathProviderApi.getApplicationDocumentsPath (package:path_provider_android/messages.g.dart:86:7)
I/flutter (16849): │ #1   <asynchronous suspension>
I/flutter (16849): │ #2   getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:121:24)
I/flutter (16849): │ #3   <asynchronous suspension>
I/flutter (16849): │ #4   BaseLog._initGather (package:baselog/src/base_log.dart:94:27)
I/flutter (16849): │ #5   <asynchronous suspension>
I/flutter (16849): │ #6   BaseLog._init (package:baselog/src/base_log.dart:90:5)
I/flutter (16849): │ #7   <asynchronous suspension>
I/flutter (16849): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (16849): │ PlatformException(channel-error, Unable to establish connection on channel., null, null)
I/flutter (16849): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16849): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16849): │ 
I/flutter (16849): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (16849): │ #0   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (16849): │ #1   <asynchronous suspension>
I/flutter (16849): │ #2   MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
I/flutter (16849): │ #3   <asynchronous suspension>
I/flutter (16849): │ #4   MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
I/flutter (16849): │ #5   <asynchronous suspension>
I/flutter (16849): │ #6   PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:41:26)
I/flutter (16849): │ #7   <asynchronous suspension>
I/flutter (16849): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (16849): │ MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
I/flutter (16849): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16849): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16849): │ 
I/flutter (16849): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (16849): │ PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.shared_preferences_android.SharedPreferencesApi.getAll"., null, null)
```

**Comment by danagbemava-nc** [comment]
Hi @ganjiajun-ola, what versions of android are they running and what version of flutter are you using?

**Comment by ganjiajun-ola** [comment]
hello @danagbemava-nc the android version that they are running are `MIUI 12.5.6.0` which is `Android 11 RP1A.200720.011` and my version of flutter is `Flutter 3.22.3-0.0.pre.2` `Tools • Dart 3.4.3 • DevTools 2.34.3`

**Comment by ganjiajun-ola** [comment]
found the issue already. It's because of the mmkv version [2.0.1](https://pub.dev/packages/mmkv/versions/2.0.1) which is causing the issue, downgrading the version of mmkv would resolve my issue

**Comment by ganjiajun-ola** [comment]
similar issue which was resolved as well, can take a look

https://github.com/flutter/flutter/issues/153683

**Comment by danagbemava-nc** [comment]
@dupuisdavid, @ddxl123 are you using mmkv plugin in your apps as well? Have you upgraded your gradle syntax to the latest?
