### ISSUE TITLE
flutter can not open custom localization file

### ISSUE THREAD

**Issue by IsayaOsward** [flutter/flutter#157506]
### Steps to reproduce

1. Install flutter_localization and intl packages
2. Enable generation in pubspec.yaml
3. add l10n.yaml at the root of the project
the specified information in this file was

arb-dir: lib/config/localization/l10n
template-arb-file: app_en.arb
output-localization-file: lib/config/localization/localizations.dart

4. add arb files as specified in the app
5. run flutter gen-l10n

### Expected results

Expected to have AppLocalization classes created on the specified output file

### Actual results

Flutter throwed exceptions
[flutter_01.log](https://github.com/user-attachments/files/17508013/flutter_01.log)

**Comment by huycozy** [comment]
_(This is from [flutter_01.log](https://github.com/user-attachments/files/17508013/flutter_01.log))_

## command

flutter gen-l10n

## exception

PathNotFoundException: PathNotFoundException: Cannot open file, path = '/home/egovridc/Desktop/Ridc-Projects/nhc-mobile/.dart_tool/flutter_gen/gen_l10n/lib/config/localization/localizations.dart' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:279:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:278:5)
#8      LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1379:20)
#9      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:79:9)
#10     GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:264:11)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-47-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.24.3 on channel stable at /home/egovridc/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    [32m•[39m Engine revision 36335019a8
    [32m•[39m Dart version 3.5.3
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /home/egovridc/Android/Sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /snap/android-studio/161/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /snap/android-studio/161
    [32m•[39m Flutter plugin version 81.0.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2024.2)
    [32m•[39m IntelliJ at /snap/intellij-idea-community/537
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2024.2)
    [32m•[39m IntelliJ at /snap/intellij-idea-ultimate/532
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Pixel 5 (mobile) • 09181FDD40078C • android-arm64  • Android 14 (API 34)
    [32m•[39m Linux (desktop)  • linux          • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-47-generic
    [32m•[39m Chrome (web)     • chrome         • web-javascript • Google Chrome 130.0.6723.58

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

**Comment by huycozy** [comment]
Does this issue occur consistently or only one time? Can you try again? If it persists, can you please share the sample project so that I can try it on my end. Thanks!

**Comment by IsayaOsward** [comment]
I tried it several times, it does the same, but if you let flutter decide the output file destination, nothing goes wrong

**Comment by huycozy** [comment]
Can you share a sample project for this so that I can pull and check it on my end? (you can try my sample project [here](https://github.com/huycozy/Flutter-demo-l10n) as well)
