### ISSUE TITLE
Sentry plugin throws type exception on new SentryClient(dsn: dsn);

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#15760]
On a recent master version of Flutter, Sentry is throwing the following exception when calling `new SentryClient`

```
E/flutter (30716): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30716): 'package:sentry/sentry.dart': error: line 70 pos 12: file:///Users/DudeGuy/.pub-cache/hosted/pub.dartlang.org/sentry-0.0.6/lib/sentry.dart:70:12: Error: A value of type '() → dart.core::bool' can't be assigned to a variable of type 'dart.core::bool'.
E/flutter (30716): Try changing the type of the left hand side, or casting the right hand side to 'dart.core::bool'.
E/flutter (30716):     assert(() {
E/flutter (30716):            ^
E/flutter (30716):     assert(() {
E/flutter (30716):            ^
E/flutter (30716): 
E/flutter (30716): #0      main (file:///Users/DudeGuy/Developer/Testing/sentry0d0d6test/lib/main.dart:7:7)
E/flutter (30716): #1      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter (30716): #2      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

## Steps to Reproduce
- `flutter create` a new project
- add `sentry: "^0.0.6"` to the pubspec.yaml
- call `new SentryClient(dsn: YOUR_DSN);`

## Logs
See above

## Flutter Doctor
```
[✓] Flutter (Channel master, v0.2.4-pre.66, on Mac OS X 10.12.6 16G1212, locale en-US)
    • Flutter version 0.2.4-pre.66 at /Users/KG/Developer/Flutter/flutter
    • Framework revision d9e3715620 (4 hours ago), 2018-03-20 08:14:08 -0700
    • Engine revision c3ab0c9143
    • Dart version 2.0.0-dev.39.0.flutter-f1ebe2bd5c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0
```

**Comment by xster** [comment]
Seems like the new head on the repo needs to be pushed to pub

**Comment by xster** [comment]
Ah, Yegor is already on it.

**Comment by KevinTheGray** [comment]
@xster / @yjbanov, you poibably know but I think `flutter_image` needs a similar treatment: https://github.com/flutter/flutter_image

**Comment by xster** [comment]
Ya, I think a bunch of them do. We'll try to go through all of them

**Comment by yjbanov** [comment]
To be fair, @pulyaevskiy is on it. I'm just reviewing PRs 😎

**Comment by yjbanov** [comment]
v2.0.0 of `package:sentry` has been published to pub. It should fix this issue. https://pub.dartlang.org/packages/sentry
