### ISSUE TITLE
"flutter doctor --android-licenses" problem

### ISSUE THREAD

**Issue by johnaaronrose** [flutter/flutter#157684]
### Steps to reproduce

In Ubuntu 24.04:
sudo snap install android-studio --classic
sudo snap install flutter --classic
flutter doctor --android-licenses 

### Actual results

`john@Desktop:~$ flutter doctor --android-licenses
Could not find the Android Studio installation at the manually configured path
"/snap/android-studio/current/android-studio".

Please verify that the path is correct and update it by running this command:
flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir

john@Desktop:~$ flutter config --android-studio-dir
Could not find an option named "android-studio-dir".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and
options.
`

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- john@Desktop:~$ flutter doctor --android-licenses
Could not find the Android Studio installation at the manually configured path
"/snap/android-studio/current/android-studio".

Please verify that the path is correct and update it by running this command:
flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir
-->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- john@Desktop:~$ flutter doctor --android-licenses --verbose
Could not find the Android Studio installation at the manually configured path
"/snap/android-studio/current/android-studio".

Please verify that the path is correct and update it by running this command:
flutter config --android-studio-dir '<path>'
To have flutter search for Android Studio installations automatically, remove
the configured path by running this command: flutter config --android-studio-dir



#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidStudio._configuredDir
(package:flutter_tools/src/android/android_studio.dart:500:7)
#2      AndroidStudio.latestValid
(package:flutter_tools/src/android/android_studio.dart:239:44)
#3      AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:107:42)
#4      _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:543:23)
#5      AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:95:20)
#6      AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#7      AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#8      AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#9      androidStudio (package:flutter_tools/src/globals.dart:70:45)
#10     runInContext.<anonymous closure>
(package:flutter_tools/src/context_runner.dart:274:32)
#11     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:107:42)
#12     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:543:23)
#13     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:95:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#15     AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#17     java (package:flutter_tools/src/globals.dart:307:27)
#18     runInContext.<anonymous closure>
(package:flutter_tools/src/context_runner.dart:115:23)
#19     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:107:42)
#20     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:543:23)
#21     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:95:20)
#22     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#23     AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#24     AppContext.get (package:flutter_tools/src/base/context.dart:122:23)
#25     androidLicenseValidator
(package:flutter_tools/src/android/android_workflow.dart:28:65)
#26     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:52:32)
#27     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1772:12)
<asynchronous suspension>
#28     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#30     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#33     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#34     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
 -->

```

</details>

**Comment by huycozy** [comment]
It seems you set the wrong path. Could you try this one?

```console
flutter config --android-studio-dir="/snap/android-studio/current"
```

**Comment by johnaaronrose** [comment]
@huycozy Thanks for the suggestion: I didn't understand the help for that config option. The command was accepted  but I now get:
`john@Desktop:~$ flutter config --android-studio-dir="/snap/android-studio/current"
Setting "android-studio-dir" value to "/snap/android-studio/current".

You may need to restart any open editors for them to read new settings.
john@Desktop:~$ flutter doctor --android-licenses
Unable to locate Android SDK.

john@Desktop:~$ flutter doctor --android-licenses
Unable to locate Android SDK.

`
Any ideas on that error?

**Comment by huycozy** [comment]
>Unable to locate Android SDK

What is your Android SDK path? You need to set it with this command: `flutter config --android-sdk="<your Android SDK path here>"`

**Comment by johnaaronrose** [comment]
@huycozy Worked Ok when I set the Android SDK Path as per your instruction.
