### ISSUE TITLE
[tool_crash] ProcessException: The command failed with exit code 255 Command: hvigorw, OS error code: 255

### ISSUE THREAD

**Issue by wangguanxiao** [flutter/flutter#157692]
## Command
```
flutter build hap --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed with exit code 255 Command: hvigorw, OS error code: 255
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:456:17)
#2      hvigorwTask (package:flutter_tools/src/ohos/hvigor.dart:166:41)
#3      assembleHap (package:flutter_tools/src/ohos/hvigor.dart:188:10)
#4      OhosHvigorBuilder.buildHap (package:flutter_tools/src/ohos/hvigor.dart:497:33)
<asynchronous suspension>
#5      BuildHapCommand.runCommand (package:flutter_tools/src/commands/build_hap.dart:80:5)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
```
```
[33m[!][39m Flutter (Channel oh-3.22.0, 3.22.0-ohos, on macOS 14.6.1 23G93 darwin-x64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.22.0-ohos on channel oh-3.22.0 at /Users/apple/Desktop/Code/Harmony/HMFlutter/flutter
    [33m![39m Upstream repository https://gitee.com/harmonycommando_flutter/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://gitee.com/harmonycommando_flutter/flutter.git to dismiss this error.
    [32m•[39m Framework revision 85630b0330 (2 days ago), 2024-10-26 02:39:47 +0000
    [32m•[39m Engine revision f6344b75dc
    [32m•[39m Dart version 3.4.0
    [32m•[39m DevTools version 2.34.1
    [32m•[39m Pub download mirror https://pub.flutter-io.cn
    [32m•[39m Flutter download mirror https://storage.flutter-io.cn
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[32m[✓][39m HarmonyOS toolchain - develop for HarmonyOS devices
    [32m•[39m OpenHarmony Sdk at /Applications/DevEco-Studio.app/Contents/sdk, available api versions has [12:HarmonyOS-NEXT-DB1]
    [32m•[39m Ohpm version 5.0.2
    [32m•[39m Node version v18.20.1
    [32m•[39m Hvigorw binary at /Applications/DevEco-Studio.app/Contents/tools/hvigor/bin/hvigorw

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java

**Comment by navaronbracke** [comment]
This seems to be related to HarmonyOS.

However, as stated in https://github.com/flutter/flutter/issues/150536#issuecomment-2180018715 you should consult the developers of that third-party embedded (which is probably https://gitee.com/openharmony-sig/flutter_flutter/tree/master/packages)

**Comment by danagbemava-nc** [comment]
As noted above, this should be reported on the open harmony fork. 

Closing from here as this is not a flutter issue. 

Thank you
