### ISSUE TITLE
`build_appbundle_test.dart` fails locally, succeeds on CI

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#157629]
Local results:

```txt
Expected: contains Event:<{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":250429440}}>
  Actual: [
            Event:{"eventName":"command_usage_values","eventData":{"workflow":"create","commandHasTerminal":false,"createProjectType":"app","createAndroidLanguage":"kotlin","createIosLanguage":"swift"}},
            Event:{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":246366208}},
            Event:{"eventName":"timing","eventData":{"workflow":"flutter","variableName":"create","elapsedMilliseconds":335,"label":"success"}},
            Event:{"eventName":"command_usage_values","eventData":{"workflow":"appbundle","commandHasTerminal":false,"buildAppBundleTargetPlatform":"android-arm,android-arm64,android-x64","buildAppBundleBuildMode":"release"}},
            Event:{"eventName":"flutter_command_result","eventData":{"commandPath":"appbundle","result":"success","commandHasTerminal":false,"maxRss":250429440}},
            Event:{"eventName":"timing","eventData":{"workflow":"flutter","variableName":"appbundle","elapsedMilliseconds":6,"label":"success"}}
          ]
   Which: does not contain Event:<{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":250429440}}>

#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect (package:matcher/src/expect/expect.dart:144:3)
#2      expect (package:matcher/src/expect/expect.dart:56:3)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/matanl/Developer/flutter/packages/flutter_tools/test/commands.shard/permeable/build_appbundle_test.dart:131:7)
<asynchronous suspension>
#4      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/matanl/Developer/flutter/packages/flutter_tools/test/src/context.dart:152:26)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/matanl/Developer/flutter/packages/flutter_tools/test/src/context.dart:141:22)
<asynchronous suspension>

Expected: contains Event:<{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":250429440}}>
  Actual: [
            Event:{"eventName":"command_usage_values","eventData":{"workflow":"create","commandHasTerminal":false,"createProjectType":"app","createAndroidLanguage":"kotlin","createIosLanguage":"swift"}},
            Event:{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":246366208}},
            Event:{"eventName":"timing","eventData":{"workflow":"flutter","variableName":"create","elapsedMilliseconds":335,"label":"success"}},
            Event:{"eventName":"command_usage_values","eventData":{"workflow":"appbundle","commandHasTerminal":false,"buildAppBundleTargetPlatform":"android-arm,android-arm64,android-x64","buildAppBundleBuildMode":"release"}},
            Event:{"eventName":"flutter_command_result","eventData":{"commandPath":"appbundle","result":"success","commandHasTerminal":false,"maxRss":250429440}},
            Event:{"eventName":"timing","eventData":{"workflow":"flutter","variableName":"appbundle","elapsedMilliseconds":6,"label":"success"}}
          ]
   Which: does not contain Event:<{"eventName":"flutter_command_result","eventData":{"commandPath":"create","result":"success","commandHasTerminal":false,"maxRss":250429440}}>

package:matcher                                                expect
test/commands.shard/permeable/build_appbundle_test.dart 131:7  main.<fn>.<fn>
===== asynchronous gap ===========================
test/src/context.dart 152:26                                   testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
===== asynchronous gap ===========================
package:flutter_tools/src/base/context.dart 153:19             AppContext.run.<fn>
===== asynchronous gap ===========================
test/src/context.dart 141:22   
```

On [CI in the same state](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8733080043648608785/+/u/run_test.dart_for_tool_tests_shard_and_subshard_commands/stdout):

```txt
03:05 +246 ~2: test/commands.shard/permeable/build_appbundle_test.dart: analytics logs success
```

Potentially related to https://github.com/flutter/flutter/issues/157627? Not sure.

**Comment by matanlurey** [comment]
I have a fix for this I detached from a larger PR. Will send out now.
