### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: https://github.com/gradle/gradle-distributions/releases/download/v8.0.0/gradle-8.0.0-all.zip

### ISSUE THREAD

**Issue by carenkedis** [flutter/flutter#157676]
I need help to fix this error please

**Comment by darshankawar** [comment]
@carenkedis 
Please try to provide complete details as mentioned in issue template so as to properly help you.
Closing due to lack of details.

**Comment by carenkedis** [comment]
this is the detailed error: Exception in thread "main" java.io.FileNotFoundException: https://github.com/gradle/gradle-distributions/releases/download/v8.0.0/gradle-8.0.0-all.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while downloading artifacts from the network.
