### ISSUE TITLE
'flutter run -t' is not working as expectation

### ISSUE THREAD

**Issue by tsun424** [flutter/flutter#15769]
## Steps to Reproduce
My current app is working fine with `lib/main.dart` file as the entrypoint, I am trying to create different entrypoint files for dev/prod, etc. I created `lib/main_dev.dart`, try to run the command
`flutter run -t lib/main_dev.dart --preview-dart-2`, but got the following error
```
$ flutter run -t lib/main_dev.dart --preview-dart-2
Launching lib/main_dev.dart on iPad Pro (9.7-inch) in debug mode...
compiler message: lib/main.dart: Error: No such file or directory
compiler message: Unhandled exception:
root::file:///Users/test/lib/main.dart is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:154)
#1      LimitedBinaryPrinter.computeCanonicalNames (package:kernel/binary/limited_ast_to_binary.dart:35)
#2      BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:283)
#3      _FrontendCompiler.compile (package:frontend_server/server.dart:203)
<asynchronous suspension>
#4      starter (package:frontend_server/server.dart:375)
<asynchronous suspension>
#5      main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:6)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on lib/main.dart
```
## Version
```
flutter --version
Flutter 0.1.5 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3ea4d06340 (4 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

**Comment by zoechi** [comment]
I think this way you are passing `--preview-dart-2` to `main_dev.dart`

Try 
```
flutter --preview-dart-2 run -t lib/main_dev.dart 
```

**Comment by zoechi** [comment]
Sorry, I got it wrong as well. I updated my comment.

**Comment by tsun424** [comment]
@zoechi , cheers! :thumbsup: it's working now. I didn't realise the position of `--preview-dart-2`. Thank you very much.
