### ISSUE TITLE
Assertion Error in ListView.builder

### ISSUE THREAD

**Issue by AbhinavKrShukla** [flutter/flutter#157738]
### Steps to reproduce

1. Create a list of items (to be displayed using ListView.builder)
`List<String> items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];`
2. Create a ListView.builder, and then display the items in ListTile, for example:
```dart
ListView.builder(
  itemCount: items.length,
  itemBuilder: (context, index) {
    return ListTile(
      title: Text(items[index]),
    );
  },
),
```

This would produce the assertion error

### Expected results

It should show ListTiles with the item names in the list.

### Actual results

It is throwing an **assertion error**

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderViewport#8f826 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2164 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  ListView ListView:file:///C:/Users/abhin/StudioProjects/Foodie/lib/Views/Category/CategoryIndex.dart:99:28
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2164:12)
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1401:39)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1448:11)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#22     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:61:11)
#23     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:985:73)
#24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:1051:32)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#26     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:451:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#28     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:61:11)
#29     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:985:73)
#30     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:1051:32)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#32     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#33     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1092:7)
#34     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#35     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#40     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1448:11)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3728:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#65     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1002:13)
#66     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1311:9)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#75     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#89     RenderView.performLayout (package:flutter/src/rendering/view.dart:281:14)
#90     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#91     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#92     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#93     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#94     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#95     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#96     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#97     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#98     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
#99     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#103    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderViewport#8f826 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: MISSING
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#e34f8(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#2e5de, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#8f826 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#e34f8(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#2e5de, ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#cb7dd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#f4e71 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      geometry: null
...      no children current live
====================================================================================================
```

### Code sample

<details open><summary>Code sample</summary>

```dart
// somewhere accessible in the file
List<String> items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];

// 
ListView.builder(
  itemCount: items.length,
  itemBuilder: (context, index) {
    return ListTile(
      title: Text(items[index]),
    );
  },
),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.40)
[√] Android Studio (version 2024.2)
[!] Android Studio (version 2024.2)
    X Unable to determine bundled Java version.
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@AbhinavKrShukla 
What platform are you seeing this error on ? 
I tried using latest master on Android and macos desktop in which I didn't get it. Below is complete runnable code.

<details>
<summary> code </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {

    List<String> items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];

    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(items[index]),
            );
          }
        )
      ),
    );
  }
}

```

</details>
