### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by takoron** [flutter/flutter#157798]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ShaderCompilerException
```console
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/tools/shader_compiler.dart:161:7)
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:221:46)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:187:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:1005:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:583:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:334:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-x64, locale
    ja-JP)
    [32m•[39m Flutter version 3.24.4 on channel stable at
      /usr/local/Caskroom/flutter/3.24.4/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 603104015d (5 days ago), 2024-10-24 08:01:25 -0700
    [32m•[39m Engine revision db49896cf2
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[33m[!][39m Android toolchain - develop for Android devices
    [32m•[39m Android SDK at /Users/okuramami/Library/Android/sdk
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    [32m•[39m ANDROID_HOME = /Users/okuramami/Library/Android/sdk
    [31m✗[39m Android SDK file not found: adb.
    [32m•[39m Try re-installing or updating your Android SDK,
      visit https://flutter.dev/to/macos-android-setup for detailed
      instructions.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [31m✗[39m CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see
      https://guides.cocoapods.org/using/getting-started.html#installation

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 130.0.6723.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 603104015dd692ea3403755b55d07813d5cf8965

**Comment by danagbemava-nc** [comment]
Hi @takoron, do you get this issue frequently? Or was it a one-off occurrence? If it is frequent, can you get us the full output of `flutter run -v`? 

Thank you
