### ISSUE TITLE
invalid image data when _cameraImage!.planes[0].bytes show to Image.memory widget

### ISSUE THREAD

**Issue by indratrisnar** [flutter/flutter#157901]
### Steps to reproduce

1. capture image from this camera plugin
2. access via bytes
3. show to Image.memory widget

### Expected results

Show Image Widget

### Actual results

Exception: Invalid Image Data

### Code sample

<details open><summary>Init Camera</summary>

```dart
_cameraController.initialize().then((value) {
      _isInitialized.value = true;
      _cameraController.startImageStream((image) {
        _cameraImage = image;
      });

      _isInitialized.refresh();
    })
```

</details>

<details open><summary>Capture function</summary>

```dart
void capture() async {
    if (_cameraImage == null) return;
    if (_cameraImage!.planes.isEmpty) {
      return print('Planes empty');
    }
    _listImage.add(_cameraImage!.planes[0].bytes);
    _listImage.refresh();
```

</details>

<details open><summary>Widget</summary>

```dart
return Container(
    color: Colors.black26,
    child: Image.memory(
      list[index],
      width: 50,
      height: 100,
      fit: BoxFit.cover,
    ),
  );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/c68b4d4d-621e-4cdc-a947-51c616705ae9)

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:7021:5)
painting.dart:7021
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6827:12)
painting.dart:6827
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2306:60)
painting.dart:2306
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:146:15)
binding.dart:146
#4      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:1579:18)
image_provider.dart:1579
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013:3)
image_stream.dart:1013
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
PS C:\Users\Indra\Documents\Latihan\flutter\latihan_ml_kit> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4317], locale en-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.5)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.95.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
I think this is similar to https://github.com/flutter/flutter/issues/137889 so I will close this in favor of that one. Please follow it for updates. Thanks!
