### ISSUE TITLE
Ensure Flutter's Devicelab survives SALT package repo migration

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#157963]
https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

It sounds like anything fetching packages from repo.saltproject.io will cease to work "by end of October 2024", which would be today.

In addition, the "Salt Project is dropping all packages older than Salt v3006", so we would need to ensure everything is using at least v3006.

**Comment by christopherfujino** [comment]
I believe our mac bots are using v3002.

**Comment by christopherfujino** [comment]
So the tarball here: https://packages.broadcom.com/artifactory/saltproject-generic/onedir/3006.0/salt-3006.0-onedir-linux-aarch64.tar.xz

Has the code I think we need. But it doesn't look like there is an ubuntu package that would install these all to the right system dirs.

**Comment by christopherfujino** [comment]
bdero@ believes that we're actually already at v3006.3, at least on flutter-devicelab-linux-58

**Comment by christopherfujino** [comment]
@kentnguyen99 I will find a macOS hostname for you to re-run the provisioning script on, but I first need to land this change to the script: https://github.com/flutter/cocoon/pull/4001

**Comment by christopherfujino** [comment]
I landed a change to the SALT config in an effort to unblock provisioning a newer SALT client on macOS: https://dash-internal-review.git.corp.google.com/c/salt/+/2220

**Comment by christopherfujino** [comment]
Ok, after pulling my change to update to a newer m2crypto python package, I now get the following error:

```
           ID: /etc/pki/flutter-devicelab-mac-10.mtv.corp.google.com.crt
     Function: x509.certificate_managed
       Result: False
      Comment: An exception occurred in this state: Traceback (most recent call last):
                 File "/opt/salt/lib/python3.10/site-packages/salt/state.py", line 2381, in call
                   ret = self.states[cdata["full"]](
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                   ret = self.loader.run(run_func, *args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                   return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                   return _func_or_method(*args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
                   return f(*args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/states/x509.py", line 681, in certificate_managed
                   is_valid, invalid_reason, current_cert_info = _certificate_is_valid(
                 File "/opt/salt/lib/python3.10/site-packages/salt/states/x509.py", line 525, in _certificate_is_valid
                   required_cert_info = __salt__["x509.create_certificate"](
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
                   ret = self.loader.run(run_func, *args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
                   return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
                   return _func_or_method(*args, **kwargs)
                 File "/opt/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1474, in create_certificate
                   if not any(certs):
               TypeError: 'NoneType' object is not iterable
      Started: 09:53:55.406025
     Duration: 261.358 ms
      Changes:
```

Note this is a slightly different stacktrace than what Kent hit in: https://github.com/flutter/flutter/issues/142627#issuecomment-1919922724

Pulling up the python code locally, here's the context:

```
1467         certs = __salt__["publish.publish"](
1468             tgt=ca_server,
1469             fun="x509.sign_remote_certificate",
1470             arg=salt.utils.data.decode_dict(kwargs, to_str=True),
1471             timeout=30,
1472         )
1473
1474         if not any(certs):
1475             raise salt.exceptions.SaltInvocationError(
1476                 "ca_server did not respond"
1477                 " salt master must permit peers to"
1478                 " call the sign_remote_certificate function."
1479             )
```

So invoking `__salt__["publish.publish"]()` is returning None, and we get a type error passing it to `any()`. However, I wonder if it's a bug in this code that it does not handle None, but that the underlying problem is what the `raise` on 1476 is referring to, that the ca_server did not respond.

**Comment by christopherfujino** [comment]
> Ok, after pulling my change to update to a newer m2crypto python package, I now get the following error:
> 
> ```
>            ID: /etc/pki/flutter-devicelab-mac-10.mtv.corp.google.com.crt
>      Function: x509.certificate_managed
>        Result: False
>       Comment: An exception occurred in this state: Traceback (most recent call last):
>                  File "/opt/salt/lib/python3.10/site-packages/salt/state.py", line 2381, in call
>                    ret = self.states[cdata["full"]](
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
>                    ret = self.loader.run(run_func, *args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
>                    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
>                    return _func_or_method(*args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
>                    return f(*args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/states/x509.py", line 681, in certificate_managed
>                    is_valid, invalid_reason, current_cert_info = _certificate_is_valid(
>                  File "/opt/salt/lib/python3.10/site-packages/salt/states/x509.py", line 525, in _certificate_is_valid
>                    required_cert_info = __salt__["x509.create_certificate"](
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
>                    ret = self.loader.run(run_func, *args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
>                    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
>                    return _func_or_method(*args, **kwargs)
>                  File "/opt/salt/lib/python3.10/site-packages/salt/modules/x509.py", line 1474, in create_certificate
>                    if not any(certs):
>                TypeError: 'NoneType' object is not iterable
>       Started: 09:53:55.406025
>      Duration: 261.358 ms
>       Changes:
> ```
> 
> Note this is a slightly different stacktrace than what Kent hit in: [#142627 (comment)](https://github.com/flutter/flutter/issues/142627#issuecomment-1919922724)
> 
> Pulling up the python code locally, here's the context:
> 
> ```
> 1467         certs = __salt__["publish.publish"](
> 1468             tgt=ca_server,
> 1469             fun="x509.sign_remote_certificate",
> 1470             arg=salt.utils.data.decode_dict(kwargs, to_str=True),
> 1471             timeout=30,
> 1472         )
> 1473
> 1474         if not any(certs):
> 1475             raise salt.exceptions.SaltInvocationError(
> 1476                 "ca_server did not respond"
> 1477                 " salt master must permit peers to"
> 1478                 " call the sign_remote_certificate function."
> 1479             )
> ```
> 
> So invoking `__salt__["publish.publish"]()` is returning None, and we get a type error passing it to `any()`. However, I wonder if it's a bug in this code that it does not handle None, but that the underlying problem is what the `raise` on 1476 is referring to, that the ca_server did not respond.

The `Function: x509.certificate_managed` is defined as:
```yaml
{{ machine_tokend.cert_pem }}:
  x509.certificate_managed:
    - ca_server: {{ ca.ca }}
    - signing_policy: fuchsia-bot
    - public_key:  {{ machine_tokend.pkey_pem }}
    - CN: {{ grains['host'] }}
    - subjectAltName: "DNS: {{ grains['fqdn'] }}"
    - days_remaining: 30
    - backup: True
    - makedirs: True
    - require:
{% if grains['os'] == 'Ubuntu' or grains['os'] == 'Debian' %}
      - pip: pip3-m2crypto
{% elif grains['os'] == 'MacOS' %}
      - pip: m2crypto
{% endif %}
      - x509: {{ machine_tokend.pkey_pem }}
```

**Comment by christopherfujino** [comment]
And `- ca_server: {{ ca.ca }}` is defined in https://dash-internal.googlesource.com/salt/+/refs/heads/main/salt/ca/map.jinja as:

```
    'ca': grains.master | replace(".endpoints.", ".c.") | replace(".cloud.goog", ".internal"),
```

Where grains.master = is the domain of the master, from go/flutter-salt#accessing-master-servers

**Comment by christopherfujino** [comment]
Ok, I've been bad about updating this, updates from the past few days:

1. We got mac-10 (an intel CPU) updated with the script from https://github.com/flutter/cocoon/pull/4002, by running `sudo salt-call state.apply` multiple times, which I think is (unfortunately) how this worked previously.
2. When we tried with mac-11 (with an ARM CPU), we got a failure that SWIG wasn't installed. I believe this is a bug in the SALT state, where for M1 macs we don't require swig: https://dash-internal.googlesource.com/salt/+/refs/heads/main/salt/machine_tokend/init.sls#26. I'm blocked on fixing this because git cl upload doesn't work on this repo. I will follow up next week.

**Comment by bdero** [comment]
https://github.com/flutter/cocoon/pull/4216 gets the provision script working on Linux again. Currently working out a swarming certificate problem.

**Comment by bdero** [comment]
Okay, all the things seem to be solved. Needed to pin the version of m2crypto.

The provision script will work on linux for new machines again once https://github.com/flutter/cocoon/pull/4216 lands. (FYI @kentnguyen99)

state.apply on linux-74:
```
Summary for local
-------------
Succeeded: 39 (changed=7)
Failed:     0
-------------
Total states run:     39
Total run time:    6.419 s
```

**Comment by kentnguyen99** [comment]
@bdero 
./cocoon/dev/provision_salt.sh dev still broken, I ran command and still getting same errors as before on linux-75.
Will you take a look again?  Thanks.

flutter@flutter-devicelab-linux-75:~/Downloads$ ./cocoon/dev/provision_salt.sh dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73032  100 73032    0     0   385k      0 --:--:-- --:--:-- --:--:--  383k
[sudo] password for flutter: 
dpkg: warning: ignoring request to remove salt-minion which isn't installed
Selecting previously unselected package salt-api.
(Reading database ... 164040 files and directories currently installed.)
Preparing to unpack /tmp/salt.deb ...
Unpacking salt-api (3006.9) ...
dpkg: dependency problems prevent configuration of salt-api:
 salt-api depends on salt-master; however:
  Package salt-master is not installed.

dpkg: error processing package salt-api (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 salt-api
