### ISSUE TITLE
Semantic Issue (Xcode): Use of undeclared identifier 'SharedPreferencesPlugin'

### ISSUE THREAD

**Issue by gd-liusida** [flutter/flutter#158008]
### Steps to reproduce

xcode 16.1 , 
Flutter 3.24.4 
[   +1 ms] Semantic Issue (Xcode): Use of undeclared identifier 'SharedPreferencesPlugin'
           /Users/ada/moreschool_flutter/ios/Runner/GeneratedPluginRegistrant.m:17:3
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 16 Pro.

### Actual results

运行到ios 环境

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.95.1)
[✓] Connected device (5 available)
[✓] Network resources

</details>

**Comment by huycozy** [comment]
Hi @gd-liusida
Please provide the proper `Steps to reproduce` and the entire output of `flutter run -v` [^1].

[^1]: The `flutter run` verbose output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.

**Comment by PrakashkumarM** [comment]
Could not build the precompiled application for the device.
Semantic Issue (Xcode): Use of undeclared identifier 'PointerInterceptorIosPlugin'
/ios/Runner/GeneratedPluginRegistrant.m:29:3


Semantic Issue (Xcode): Use of undeclared identifier 'SharedPreferencesPlugin'
ios/Runner/GeneratedPluginRegistrant.m:30:3


Semantic Issue (Xcode): Use of undeclared identifier 'URLLauncherPlugin'
ios/Runner/GeneratedPluginRegistrant.m:31:3

**Comment by huycozy** [comment]
@PrakashkumarM Please provide the information mentioned above comment https://github.com/flutter/flutter/issues/158008#issuecomment-2453977787.

**Comment by pradyutsingh** [comment]
Facing the same issue here
>Semantic Issue (Xcode): Use of undeclared identifier 'PathProviderPlugin'
{Path}//ios/Runner/GeneratedPluginRegistrant.m:17:3

>Could not build the application for the simulator.
Error launching application on iPhone 16.

Flutter doctor -v output

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.24.5 on channel stable at /Users/pradyutsingh/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (13 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.90.2)
    • VS Code at /Users/pradyutsingh/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • iPhone 16 (mobile)              • 924E013D-ECF1-4238-B653-0EC4EED2B177 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64
      • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin
      • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

```


Flutter run -v output

```
Semantic Issue (Xcode): Use of undeclared identifier 'PathProviderPlugin'
{Path}//ios/Runner/GeneratedPluginRegistrant.m:17:3


[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 16.
[  +53 ms] "flutter run" took 17,690ms.
[  +18 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[  +52 ms] ensureAnalyticsSent: 51ms
[        ] Running 2 shutdown hooks
[        ] Shutdown hooks complete
```

**Comment by DroidGar** [comment]
i have the same issue, start a new proyect Flutter and add the SharedPreferences plugin and not compile on ios with same message:

`Semantic Issue (Xcode): Use of undeclared identifier 'SharedPreferencesPlugin'
/Users/xxxxxxxx/StudioProjects/xxxxxxx/ios/Runner/GeneratedPluginRegistrant.m:17:3
`
