### ISSUE TITLE
The name '' is defined in the libraries 'dart:async' and 'dart:convert'.

### ISSUE THREAD

**Issue by Raj-impetrosys** [flutter/flutter#158092]
### Steps to reproduce

While exporting 'dart:async' and 'dart:collection' getting The name '' is defined in the libraries 'dart:async' and 'dart:convert'.
 
<img width="1440" alt="Screenshot 2024-11-04 at 12 45 42 PM" src="https://github.com/user-attachments/assets/9b69d9b5-3f69-4f6f-a2c0-b6474a279654">

### Expected results

I've tried to find name '' and tried to hiding name but getting err

### Actual results

export 'dart:async' hide interface, '';
export 'dart:collection' hide interface, '';
export 'dart:convert' hide interface,'';
export 'dart:io' hide interface,'';
export "dart:math" hide interface, '';

### Code sample

<details open><summary>Code sample</summary>

```dart
export 'dart:async' hide interface, '';
export 'dart:collection' hide interface, _;
export 'dart:convert' hide interface, _;
export 'dart:io' hide interface, _;
export "dart:math" hide interface, _;

export 'package:flutter/material.dart' hide '';
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="1440" alt="Screenshot 2024-11-04 at 12 45 42 PM" src="https://github.com/user-attachments/assets/cb1b0d9e-8cea-4d3b-9003-5aa4d70cfc75">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/rajkumar/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rajkumar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FileSystemException: Creation of temporary directory failed, path =
      '/var/folders/fz/lqfg8f0j3hn58k286272gy_c0000gn/T/flutter_tools.' (OS Error: No space left on
      device, errno = 28)
    • #0      _Directory.createTempSync (dart:io/directory_impl.dart:170:7)
      #1      ForwardingDirectory.createTempSync
      (package:file/src/forwarding/forwarding_directory.dart:28:21)
      #2      LocalFileSystem.systemTempDirectory
      (package:flutter_tools/src/base/file_system.dart:236:46)
      #3      ErrorHandlingFileSystem.systemTempDirectory
      (package:flutter_tools/src/base/error_handling_io.dart:127:31)
      #4      IOSCoreDeviceControl._listCoreDevices
      (package:flutter_tools/src/ios/core_devices.dart:65:49)
      #5      IOSCoreDeviceControl.getCoreDevices
      (package:flutter_tools/src/ios/core_devices.dart:120:48)
      #6      XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcdevice.dart:487:72)
      <asynchronous suspension>
      #7      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:548:36)
      <asynchronous suspension>
      #8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
      <asynchronous suspension>
      #9      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:218:40)
      <asynchronous suspension>
      #10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:715:34)
      <asynchronous suspension>
      #11     Future.any.onValue (dart:async/future.dart:628:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    • Flutter version 3.24.3 on channel stable at /Users/rajkumar/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rajkumar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FileSystemException: Creation of temporary directory failed, path =
      '/var/folders/fz/lqfg8f0j3hn58k286272gy_c0000gn/T/flutter_tools.' (OS Error: No space left on
      device, errno = 28)
    • #0      _Directory.createTempSync (dart:io/directory_impl.dart:170:7)
      #1      ForwardingDirectory.createTempSync
      (package:file/src/forwarding/forwarding_directory.dart:28:21)
      #2      LocalFileSystem.systemTempDirectory
      (package:flutter_tools/src/base/file_system.dart:236:46)
      #3      ErrorHandlingFileSystem.systemTempDirectory
      (package:flutter_tools/src/base/error_handling_io.dart:127:31)
      #4      IOSCoreDeviceControl._listCoreDevices
      (package:flutter_tools/src/ios/core_devices.dart:65:49)
      #5      IOSCoreDeviceControl.getCoreDevices
      (package:flutter_tools/src/ios/core_devices.dart:120:48)
      #6      XCDevice.getAvailableIOSDevices (package:flutter_tools/src/macos/xcdevice.dart:487:72)
      <asynchronous suspension>
      #7      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:548:36)
      <asynchronous suspension>
      #8      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
      <asynchronous suspension>
      #9      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:218:40)
      <asynchronous suspension>
      #10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:715:34)
      <asynchronous suspension>
      #11     Future.any.onValue (dart:async/future.dart:628:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jaypal1046** [comment]
In Dart, the export statement with hide is used to expose only specific parts of a library by excluding certain classes, functions, or symbols that you don’t want to make available to other files that import your library. Here’s how you can use export with hide to selectively exclude functions or classes:
export 'dart:async' hide Completer, Future;
export 'dart:collection' hide HashMap, LinkedHashMap;
export 'dart:convert' hide jsonDecode, jsonEncode;
export 'dart:io' hide File, Directory;
export 'dart:math' hide Random;
In this example, certain classes and functions (such as Completer, Future, HashMap, etc.) are excluded from being accessible to any file that imports this library, allowing more control over what parts of each library are exposed.

**Comment by danagbemava-nc** [comment]
Hi @Raj-impetrosys, can you share the actual classes, you're trying to exclude? interface & _ are not defined the libraries you're specifying

**Comment by Rajkumar07793** [comment]
Actually I'm unable to use following exports in a same file I'm getting errors like above screenshots I've shared

export 'dart:async';
export 'dart:collection';
export 'dart:convert';
export 'dart:io';
export "dart:math";
export 'package:flutter/material.dart;

**Comment by Rajkumar07793** [comment]
> Hi @Raj-impetrosys, can you share the actual classes, you're trying to exclude? interface & _ are not defined the libraries you're specifying

Actually I'm unable to use following exports in a same file I'm getting errors like above screenshots I've shared

export 'dart:async';
export 'dart:collection';
export 'dart:convert';
export 'dart:io';
export "dart:math";
export 'package:flutter/material.dart;
