### ISSUE TITLE
can't debug the app 

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#15801]
I used Android studio 3.2 , and I can't run the app on my android device 

Android studio output :

```
Launching lib/main.dart on PGN610 in debug mode...
Initializing gradle...
Finished with error: Exit code 1 from: /home/alouch/Desktop/flutter_app/android/gradlew -v:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/alouch/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

flutter Doctor :

`alouch@machine:~$ flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
Try `flutter channel dev` `flutter doctor` `flutter clean`

**Comment by dalerka** [comment]
Same issue here. Just installed fresh Android Studio and Flutter, setup the device according to instructions (Flutter does see the my android device correctly).
The suggestion above by @zoechi  didn't help.  
What else can we try?

**Comment by HaileApp** [comment]
Same error here..In my case the Visual Studio code prints...
`Exit code 1 from: C:\Users\DELL I5\Desktop\Android\flut\ka\android\gradlew.bat -v:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\DELL I5\.gradle\wrapper\dists\gradle-4.1-all\bzyivzo6n839fup2jbap0tjew\gradle-4.1-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exited (sigterm)
`

**Comment by deadcoder0904** [comment]
did anyone find a solution? i'm facing same problem

**Comment by zoechi** [comment]
I think this issue is stale.
If you disagree please create a new issue with properly filled out issue template.

**Comment by deadcoder0904** [comment]
@zoechi its for a new project. first time using flutter. i am trying the whole day to figure out & found out similar issues but none worked. i've installed gradle 5.0 through brew & android studio 3.2 but unable to start flutter simple app. it just shows `initializing gradle..` forever 😢

**Comment by zoechi** [comment]
Flutter uses Gradle 4.10.2

**Comment by deadcoder0904** [comment]
It should be mentioned somewhere :( 

Wasted a day trying to figure this out 😭

**Comment by deadcoder0904** [comment]
Okay its an issue now #24884

**Comment by zoechi** [comment]
@deadcoder0904 https://github.com/flutter/flutter/issues/24757#issuecomment-443292335

I don't have deep Gradle knowledge but I think you don't need to install a specific Gradle version.
You need to update generated files in `ios/` and `android/` from time to time though.
Flutter downloads and uses the version defined in `android/gradle/wrapper/gradel-wrapper.properties` See also https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by deadcoder0904** [comment]
@zoechi I made it work yesterday.

I downloaded `gradle-4.10.2-all.zip` from website & installed it & pointed android studio to it.

It didn't work with `gradle-5` though.

So it works for now. Thank you 🙌
