### ISSUE TITLE
ImageStreamListener is never called under widget test

### ISSUE THREAD

**Issue by artem-kamyshev** [flutter/flutter#158134]
### Steps to reproduce

1. My Thumbnail widget gets an Image from memory, thus the image is already available
2. I need to read the real size of an image, to do this I add a listener so I get the ui.Image object when it's ready.

This works fine when I run code on an Android simulator, but fails when running via `flutter test`.

I've had issues with this from the beginning (I tried to use FutureBuilder, you can see this approach here: https://stackoverflow.com/questions/79068000/widget-built-by-futurebuilder-works-in-application-but-is-never-created-under-wi), I managed to make it work. But now it doesn't work again. I removed FutureBuilder and simplified the code to just use an StatefulWidget (so I have less dependencies), but still it doesn't work: I've run it with debugger (via Android Studio) and found out that a callback passed to ImageStreamListener is never called.

### Expected results

A callback passed to Image is called both in production and unit tests.

### Actual results

Not called and as a result IconButton widget is not created.

### Code sample

<details open><summary>Code sample</summary>

```dart
class ThumbnailState extends State<Thumbnail> {
  ui.Image? _image;

  @override
  void initState() {
    widget.thumbnailImage.image
        .resolve(const ImageConfiguration())
        .addListener(ImageStreamListener((image, synchronousCall) {
      if (_image == null) {
        setState(() {
          _image = image.image;
        });
      }
      image.dispose();
    }));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(alignment: Alignment.center, children: [
      widget.thumbnailImage,
      Offstage(
          offstage: _image == null, child: makeIconButton(context, _image)),
    ]);
  }
```

I've made a minimal project with my Thumbnail widget here, in the public repository:
https://github.com/artem-kamyshev/FlutterImageStreamListenerBug

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
c:\repos\flutterbug\bug>flutter --verbose test test\widget_test.dart
[ +165 ms] Found 1 files which will be executed as Widget Tests.
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +49 ms] Skipping pub get: version match.
[ +152 ms] Generating c:\repos\flutterbug\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +132 ms] running test package with arguments: [--chain-stack-traces, --, file:///c:/repos/flutterbug/bug/test/widget_test.dart?]
00:00 +0: loading c:/repos/flutterbug/bug/test/widget_test.dart                                                                                                                                                                             [ +183 ms] test 0: starting test c:/repos/flutterbug/bug/test/widget_test.dart
[   +7 ms] Stopping scan for flutter_test_config.dart; found project root at c:\repos\flutterbug\bug
[   +3 ms] Compiler will use the following file as its incremental dill file: C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_compiler.5de41aa2\output.dill
[        ] Listening to compiler controller...
[  +13 ms] Compiling file:///C:/Users/Arks/AppData/Local/Temp/flutter_tools.6f9b9125/flutter_test_listener.fc7c776e/listener.dart
[  +53 ms] No packages with native assets. Skipping native assets compilation.
[   +2 ms] Writing native_assets.yaml.
[  +14 ms] Writing c:\repos\flutterbug\bug\build\native_assets\windows\native_assets.yaml done.
[   +5 ms] C:\FlutterSDK\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe --disable-dart-dev C:\FlutterSDK\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server_aot.dart.snapshot --sdk-root
C:\FlutterSDK\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --no-print-incremental-dependencies --target=flutter --experimental-emit-debug-metadata --output-dill
C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_compiler.5de41aa2\output.dill --packages c:\repos\flutterbug\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --initialize-from-dill c:\repos\flutterbug\bug\build\test_cache\build\cache.dill.track.dill --native-assets file:///c:/repos/flutterbug/bug/build/native_assets/windows/native_assets.yaml --verbosity=error
[  +19 ms] <- native-assets file:///c:/repos/flutterbug/bug/build/native_assets/windows/native_assets.yaml
[        ] <- compile file:///C:/Users/Arks/AppData/Local/Temp/flutter_tools.6f9b9125/flutter_test_listener.fc7c776e/listener.dart
00:07 +0: loading c:/repos/flutterbug/bug/test/widget_test.dart                                                                                                                                                                             [+7218 ms] <- accept
[   +2 ms] <- reset
[   +2 ms] Compiling file:///C:/Users/Arks/AppData/Local/Temp/flutter_tools.6f9b9125/flutter_test_listener.fc7c776e/listener.dart took 7315ms
[        ] test 0: starting test device
[   +3 ms] test 0: awaiting connection to test device
[   +1 ms] test 0: VM Service uri is not available
[   +3 ms] test 0: test harness socket server is running at port:53761
[   +2 ms] Using this directory for fonts configuration: C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_fonts.eca12e98
[   +4 ms] test 0: Starting flutter_tester process with command=[C:\FlutterSDK\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe, --disable-vm-service, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts, --disable-asset-fonts, --packages=c:\repos\flutterbug\bug\.dart_tool\package_config.json,
--flutter-assets-dir=c:\repos\flutterbug\bug\build\unit_test_assets, C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_listener.fc7c776e\listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_fonts.eca12e98/fonts.conf, SERVER_PORT: 53761, APP_NAME: bug, UNIT_TEST_ASSETS: c:\repos\flutterbug\bug\build\unit_test_assets}
[  +13 ms] test 0: Started flutter_tester process at pid 23184
[ +350 ms] test 0: connected to test device, now awaiting test result
[   +3 ms] test 0: Waiting for test harness or tests to finish
00:08 +0: Thumbnail
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "Found 0 widgets with type "IconButton": []" (used in a call to "tap()") could not find
any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1884:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1784:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:1032:18)
#3      main.<anonymous closure> (file:///c:/repos/flutterbug/bug/test/widget_test.dart:40:20)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Thumbnail
════════════════════════════════════════════════════════════════════════════════════════════════════
00:08 +0 -1: Thumbnail [E]
  Test failed. See exception logs above.
  The test description was: Thumbnail


To run this test again: C:\FlutterSDK\flutter\bin\cache\dart-sdk\bin\dart.exe test c:/repos/flutterbug/bug/test/widget_test.dart -p vm --plain-name "Thumbnail"
[ +891 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[   +5 ms] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[   +1 ms] test 0: Terminating flutter_tester process
[   +1 ms] test 0: Shutting down DevTools server
[   +1 ms] test 0: Test process is no longer needed by test harness
[   +2 ms] test 0: Shutting down test harness socket server
[  +14 ms] test 0: flutter_tester process at pid 23184 exited with code=-1
[   +1 ms] test 0: deleting temporary directory
[   +6 ms] test 0: finished
00:08 +0 -1: Some tests failed.
[  +10 ms] Deleting C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_compiler.5de41aa2...
[   +7 ms] killing pid 33896
[  +54 ms] Deleting C:\Users\Arks\AppData\Local\Temp\flutter_tools.6f9b9125\flutter_test_fonts.eca12e98...
[   +5 ms] test package returned with exit code 1
[   +2 ms] Runtime for phase TestRunner: Wall-clock: 0:00:08.925601; combined: 0:00:08.925631.
[   +1 ms] Runtime for phase Compile: Wall-clock: 0:00:07.316784; combined: 0:00:07.316808.
[        ] Runtime for phase Run: Wall-clock: 0:00:01.278264; combined: 0:00:01.278265.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.000850; combined: 0:00:00.000851.
[   +8 ms] "flutter test" took 9 373ms.
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:624:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[  +97 ms] ensureAnalyticsSent: 92ms
[   +1 ms] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
c:\repos\flutterbug\bug>flutter doctor -v
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.5011], locale ru-RU)
    • Flutter version 3.22.2 on channel stable at C:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Arks\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.35013.160
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] VS Code (version 1.95.1)
    • VS Code at C:\Users\Arks\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[√] VS Code (version 1.87.0-insider)
    • VS Code at C:\Users\Arks\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 129.0.6668.58
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 130.0.2849.68

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by artem-kamyshev** [comment]
A bit more info, hope it can help clarify the issue: the bug or smth I do wrong:

Here is a call which I get on a normal execution and never get in tests:
![image](https://github.com/user-attachments/assets/d9146b32-4f88-4d93-b604-23a215688b40)

**Comment by darshankawar** [comment]
@artem-kamyshev 
Can you try to set `ensureVisible()` before `tap()` to see if it helps ?

**Comment by artem-kamyshev** [comment]
@darshankawar
Thanks for your reply.
This worn't help because `find.byType(IconButton)` doesn't find any widget, so there's nothing to ask to make it visible. I've rewritten the test to show it (I've also added `ensureVisible` but on the Image, not the IconButton):

```
      final image = find.byType(Image);
      expect(image, findsOneWidget);
      await tester.ensureVisible(image);

      await tester.pumpAndSettle();
      final iconButton = find.byType(IconButton);
      expect(iconButton, findsOneWidget);
      await tester.tap(iconButton);
```

With this code I get the following error:

> The following TestFailure was thrown running a test:
> Expected: exactly one matching candidate
>   Actual: _TypeWidgetFinder:<Found 0 widgets with type "IconButton": []>
>    Which: means none were found but one was expected

**Comment by artem-kamyshev** [comment]
Ok, finally got how to make it work. I would really appreciate more docs and more detailed info in docs on the topic. I'll post details in a day or two.

**Comment by darshankawar** [comment]
> I would really appreciate more docs and more detailed info in docs on the topic

You may file a new issue for this so that it can be tracked and addressed properly.

**Comment by artem-kamyshev** [comment]
> I'll post details on what was wrong and how I made it work in a day or two.

So, here it is. ImageProvider does its work async to the main UI thread (isolate). I haven't yet found how and where exactly it works, but it's the reason my test haven't worked. I've changed the test to run inside `runAsync` and added a `completer` to wait for the end of image's loading and now it's fine:

```
void main() {
  testWidgets('Thumbnail', (WidgetTester tester) async {
    await tester.runAsync(() async {
      var imageProvider = MemoryImage(
          thumbnail); // DummyImageProvider(width: 64, height: 64);
      var thumbnailPage = Scaffold(
          appBar: AppBar(title: const Text('Thumbnail')),
          body: Thumbnail(
              thumbnail: thumbnail,
              mainImage: Image( //thumbnail_package.ImagePage(
                //'MainImage',
                  image: imageProvider // MemoryImage(thumbnail)
              )
          ));
      await tester.pumpWidget(
          MaterialApp(home: thumbnailPage)
      );

      final thumbnailFinder = find.byType(Thumbnail);
      expect(thumbnailFinder, findsOneWidget);
      await (tester.state(thumbnailFinder) as ThumbnailState).completer!.future;

      final image = find.byType(Image);
      expect(image, findsOneWidget);

      await tester.pumpAndSettle();
      final iconButton = find.byType(IconButton);
      expect(iconButton, findsOneWidget);
      await tester.tap(iconButton);
    });
  });
}
```

And the class itself:

```
class ThumbnailState extends State<Thumbnail> {
  ui.Image? _image;
  Completer<ui.Image>? completer;

  @override
  void initState() {
    completer = Completer<ui.Image>();
    widget.thumbnailImage.image
        .resolve(const ImageConfiguration())
        .addListener(ImageStreamListener((image, synchronousCall) {
      if (!completer!.isCompleted) {
        completer!.complete(image.image);
      }
      if (_image == null) {
        setState(() {
          _image = image.image;
        });
      }
      image.dispose();
    }));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(alignment: Alignment.center, children: [
      widget.thumbnailImage,
      Offstage(
          offstage: _image == null, child: makeIconButton(context, _image)),
    ]);
  }
```

All the code is uploaded into https://github.com/artem-kamyshev/FlutterImageStreamListenerBug.

I would appreciate any suggestion where to look for the details of the process. Where's the real image loading/decoding happens? Have I overseen this info in the docs?

**Comment by darshankawar** [comment]
Good to know. Closing as resolved.
