### ISSUE TITLE
Changing animation before hot reload causes crash

### ISSUE THREAD

**Issue by totaki** [flutter/flutter#15816]
When i make this step from codelab https://codelabs.developers.google.com/codelabs/flutter/index.html#6, i have are error

```
I/flutter ( 6472): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6472): The following assertion was thrown building ChatMessage(dirty):
I/flutter ( 6472): 'package:flutter/src/animation/animations.dart': Failed assertion: line 334 pos 15: 'parent !=
I/flutter ( 6472): null': is not true.
I/flutter ( 6472): 
I/flutter ( 6472): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6472): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6472): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6472):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6472): 
I/flutter ( 6472): When the exception was thrown, this was the stack:
I/flutter ( 6472): #2      new CurvedAnimation (package:flutter/src/animation/animations.dart:334:15)
I/flutter ( 6472): #3      ChatMessage.build (/data/user/0/com.emelianov.mychat/cache/my_chatMYLWVE/my_chat/lib/main.dart:31:25)
I/flutter ( 6472): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
I/flutter ( 6472): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 6472): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 6472): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 6472): #8      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 6472): #9      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 6472): #10     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6472): #11     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6472): #12     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 6472): #14     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
I/flutter ( 6472): #15     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
I/flutter ( 6472): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter ( 6472): (elided 3 frames from class _AssertionError and package dart:async-patch)
```

Flutter doctor
```
[✓] Flutter (Channel beta, v0.1.5, on Linux, locale ru_RU.UTF-8)
    • Flutter version 0.1.5 at /home/totaki/soft/flutter
    • Framework revision 3ea4d06340 (4 недели назад), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/totaki/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/totaki/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/totaki/soft/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.21.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by ThuAbLKA** [comment]
try 
`parent: animationController.view,`

instead of 
`parent: animationController,`

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by opensourcegps** [comment]
Problem is still present in v0.5.9-pre.41. It's only visible in debug builds, not in production. Happens when you push new Route and it opens. However not everywhere, possibly when route pushed from screen with tabs.

```
[✓] Flutter (Channel master, v0.5.9-pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.9-pre.41 at /home/flutter/flutter_v0.5.1-master/flutter
    • Framework revision faffd3aef3 (3 weeks ago), 2018-08-15 01:01:30 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/android/sdk
    • Java binary at: /home/android/src/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/android/src/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.1.0 (API 27) (emulator)
   
• No issues found!
```

```
I/flutter (17444): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17444): The following assertion was thrown building
I/flutter (17444): _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#8f773](dirty, state: _OverlayEntryState#fa6c7):
I/flutter (17444): 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent !=
I/flutter (17444): null': is not true.
I/flutter (17444): 
I/flutter (17444): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17444): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17444): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17444):   https://github.com/flutter/flutter/issues/new
I/flutter (17444): 
I/flutter (17444): When the exception was thrown, this was the stack:
I/flutter (17444): #2      new CurvedAnimation (package:flutter/src/animation/animations.dart:340:15)
I/flutter (17444): #3      ModalRoute._buildModalBarrier (package:flutter/src/widgets/routes.dart:1183:21)
I/flutter (17444): #4      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter (17444): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (17444): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (17444): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (17444): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (17444): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (17444): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (17444): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (17444): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (17444): #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4450:32)
I/flutter (17444): #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter (17444): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (17444): #16     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (17444): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (17444): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (17444): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (17444): #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (17444): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (17444): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (17444): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17444): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17444): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (17444): #26     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (17444): #27     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (17444): (elided 2 frames from class _AssertionError)
I/flutter (17444): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17444): Another exception was thrown: 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent != null': is not true.
I/flutter (17444): Another exception was thrown: 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent != null': is not true.
````

**Comment by opensourcegps** [comment]
I'll try to make reproducible example. Actually this happens because of Hero animation involved.

**Comment by zoechi** [comment]
The bot has kind of it's own will :D

**Comment by opensourcegps** [comment]
I think it's better to remove/add "waiting for customer response" label. It might calm down the bot :)

**Comment by zoechi** [comment]
You are right, forgot to check.

**Comment by opensourcegps** [comment]
This bug is inconsistent. Happened only in debug builds. I've managed to fix it by just adding:

import 'dart:async';

This import stays grey, so no idea how it fixed it, probably just a coincidence. However after playing with some delays in initstate and then removing all testing stuff and only keeping  'dart:async' import, kind of resolved the issue. I can't explain how it fixed itself.

Bug can be closed. If anyone triggers it again, try the following:

- add 1 sec delay in initstate on the pushed route. This fixes the problem, but you have delay.
- remove delay, problem somehow stays fixed. Crazy :)

**Comment by bujordan** [comment]
Just thought I'd post I saw this after completing the "Add a SizeTransition Widget" step of this tutorial here: https://codelabs.developers.google.com/codelabs/flutter/#6. 

**Output of flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G2307, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (2 available)

• No issues found!

**Error Message** (trimmed)
```
flutter: The following assertion was thrown building ChatMessage(dirty):
flutter: 'package:flutter/src/animation/animations.dart': Failed assertion: line 339 pos 15: 'parent !=
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new CurvedAnimation (package:flutter/src/animation/animations.dart:339:15)
flutter: #3      ChatMessage.build (file:///Users/bucky/projects/hotel_chat/lib/main.dart:119:23)
```

The error occurred when the hot reload happened automatically after saving my changes. Doing a flutter clean and restarting the app in the simulator fixed it.

I'm completely new to dart and flutter so I may be way off base, but from the first part of the error "failed assertion of parent != null is not true", it seems like there's a simple widget state issue here (which would explain why it only happens in debug and adding a delay magically fixed it and also why a clean would fix it- it's not unreasonable for state to get a little screwy after a lot of hot reloads, or getting up and going to lunch as in my case, for example).

It might be good to update the error message with "try flutter clean & restart app, if that doesn't work see issue #" or something similar as telling folks to create an issue for this doesn't seem ideal.

**Comment by sateesh-penumalla** [comment]
This is not fixed. Its totally irritating. Feeling like why did I upgrade.

**Comment by sateesh-penumalla** [comment]
Flutter is very unstable now

**Comment by opensourcegps** [comment]
This issue was happening for me with the following:

1. Push new route.
2. On new route display dialog.

Solution was to add 1 sec delay to dialog display. Maybe one animation (dialog) right after another (route transition) was not working well.

**Comment by VHiep** [comment]
Still happen in Hot Reload. Flutter ver 1.0

**Comment by chriswu14** [comment]
can confirm issue still happens when following https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..index#6
for adding animation part during hot reload. 

re-run application does not seem to trigger error

**Comment by egorges** [comment]
Me too having the same issue with my App.

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1666 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1666:12)
#3      Navigator.push (package:flutter/src/widgets/navigator.dart:1011:34)
#4      PageReportMode.requestAction (package:catcher/mode/page_report_mode.dart:25:15)
#5      Catcher._reportError (package:catcher/core/catcher.dart:207:35)
<asynchronous suspension>
#6      Catcher._setupErrorHooks.<anonymous closure> (package:catcher/core/catcher.dart:112:13)
<asynchronous suspension>
#7      _rootRunBinary (dart:async/zone.dart:1148:13)
#8      _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#9      runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#10     _CustomZone.handleUncaughtErr<…>


![image](https://user-images.githubusercontent.com/47680522/57037787-7ba1af80-6c2e-11e9-9be0-48066a8e0ad1.png)

**Comment by dnfield** [comment]
Possibly related to https://github.com/flutter/flutter/issues/26503?

**Comment by egorges** [comment]
> Possibly related to #26503?

My screen doesn't have a widget that rebuilds very often:
An Scaffold, a FutureBuilder with a get from Firebase, a ListView with around 10 tiles, half of them with images read from asset.

**Comment by CocoaZX** [comment]
@opensourcegps  same issue to me, do you fix this?

**Comment by mauhcs** [comment]
Any update on this?

Thank you

**Comment by alishashaw439** [comment]
Waiting for an update.

**Comment by darshankawar** [comment]
Hi @totaki,
Can you please confirm if this is still an issue with latest version of Flutter ?
Thanks.

**Comment by FathyRida** [comment]
Hello Guys any update please I got the same issue
