### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by gerardoargueta** [flutter/flutter#158144]
## Command
```sh
flutter run --machine --start-paused -d 00008110-000A61D02E07801E --devtools-server-address http://127.0.0.1:9100/ --target /Users/gerardoarguetabermudez/project/sellia/sellia-agente-app/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale es-MX)
    • Flutter version 3.24.3 on channel stable at /Users/gerardoarguetabermudez/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (8 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/gerardoarguetabermudez/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/gerardoarguetabermudez/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • Nor (mobile)                    • 00008110-000A61D02E07801E • ios            • iOS 17.6.1 21G93
    • BlackFalcon (mobile)            • 00008110-001649E10205801E • ios            • iOS 18.1 22B82
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.2.7+39
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2663184aa79047d0a33a14a3b607954f8fdd8730
### Plugins
audio_session-0.1.21
device_info_plus-10.1.2
emoji_picker_flutter-3.1.0
file_picker-8.1.3
firebase_analytics-11.3.3
firebase_analytics_web-0.5.10+2
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_messaging-15.1.3
firebase_messaging_web-3.9.2
flutter_local_notifications-17.2.3
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.23
flutter_secure_storage_x-10.1.0
flutter_secure_storage_x_linux-1.4.2
flutter_secure_storage_x_macos-3.4.2
flutter_secure_storage_x_web-2.1.2
flutter_secure_storage_x_windows-3.3.3
flutter_sound-9.16.3
flutter_sound_web-9.16.3
fluttertoast-8.2.8
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.10
google_maps_flutter_ios-2.13.1
google_maps_flutter_web-0.5.10
just_audio-0.9.41
just_audio_web-0.4.13
path_provider-2.1.4
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pdfx
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
shared_preferences-2.3.2
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.12
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
video_player-2.9.2
video_player_android-2.7.13
video_player_avfoundation-2.6.2
video_player_web-2.3.2

**Comment by huycozy** [comment]
Duplicate of https://github.com/flutter/flutter/issues/150131
