### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by SivaranjanVithushan** [flutter/flutter#158306]
## Command
```sh
flutter run --no-enable-impeller
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#4      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.4, on macOS 15.0 24A335 darwin-arm64, locale en-LK)
    [32m•[39m Flutter version 3.24.4 on channel stable at /Users/vithushan/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    [32m•[39m Engine revision db49896cf2
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/vithushan/Library/Android/sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.95.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0 24A335 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.92

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 0.2.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
ably_flutter-1.2.34
app_links-6.3.2
app_links_linux-1.0.3
app_links_web-1.0.4
connectivity_plus-6.0.5
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+1
firebase_core-3.4.0
firebase_core_web-2.17.5
flutter_plugin_android_lifecycle-2.0.20
geocoding-3.0.0
geocoding_android-3.3.1
geocoding_ios-3.0.1
geolocator-12.0.0
geolocator_android-4.6.0
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
google_maps_flutter-2.7.0
google_maps_flutter_android-2.12.0
google_maps_flutter_ios-2.10.0
google_maps_flutter_web-0.5.8
google_sign_in-6.2.1
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
gtk-2.1.0
image_picker-1.1.2
image_picker_android-0.8.12+4
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.3
path_provider_android-2.2.6
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
share_plus-9.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
url_launcher-6.3.0
url_launcher_android-6.3.8
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1
video_player-2.9.1
video_player_android-2.6.0
video_player_avfoundation-2.6.1
video_player_web-2.3.1

**Comment by prachishukla007** [comment]
I'm facing this too.
