### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by al1103** [flutter/flutter#158383]
## Command
```sh
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```console
#0      Scanner._removeSimpleKey (package:yaml/src/scanner.dart:540:7)
#1      Scanner._fetchStreamEnd (package:yaml/src/scanner.dart:612:5)
#2      Scanner._fetchNextToken (package:yaml/src/scanner.dart:368:7)
#3      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:351:7)
#4      Scanner.peek (package:yaml/src/scanner.dart:329:27)
#5      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:426:26)
#6      Parser._stateMachine (package:yaml/src/parser.dart:100:16)
#7      Parser.parse (package:yaml/src/parser.dart:61:19)
#8      Loader._loadMapping (package:yaml/src/loader.dart:175:23)
#9      Loader._loadNode (package:yaml/src/loader.dart:92:16)
#10     Loader._loadDocument (package:yaml/src/loader.dart:68:20)
#11     Loader.load (package:yaml/src/loader.dart:60:20)
#12     loadYamlDocument (package:yaml/yaml.dart:72:25)
#13     loadYamlNode (package:yaml/yaml.dart:57:5)
#14     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:30:29)
#15     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:307:15)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1772:12)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
```
```console
[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4317], locale vi-VN)
    • Flutter version 3.24.1 on channel stable at C:\Users\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (3 months ago), 2024-08-20 16:46:00 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Zilongz\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: D:\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.95.2)
    • VS Code at C:\Users\Zilongz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 130.0.6723.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 130.0.2849.46

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 603104015dd692ea3403755b55d07813d5cf8965

**Comment by huycozy** [comment]
Per https://github.com/flutter/flutter/issues/110815#issuecomment-1643419879: if you can reproduce this issue consistently, please share the yaml file content.
