### ISSUE TITLE
ImagePicker Android release crash : FileUtils.java - Volume external_primary not found

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#158331]
### Steps to reproduce

Here is the crash log from my Crashlytics dashboard : 

<img width="493" alt="Capture d’écran 2024-11-07 à 17 53 33" src="https://github.com/user-attachments/assets/cb9f4e82-80db-4bba-a811-097b889da1d9">

```
 Fatal Exception: java.lang.IllegalArgumentException: Volume external_primary not found
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2014)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1813)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1490)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:55)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.getPathsFromIntent(ImagePickerDelegate.java:673)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:684)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0(ImagePickerDelegate.java:615)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

Unfortunately i can't reproduce it, it happened on my Android live app and i have the error log in Crashlytics. 

I can provide the Android configuration where the crash occured : 

<img width="1048" alt="Capture d’écran 2024-11-07 à 17 52 09" src="https://github.com/user-attachments/assets/01b02d0e-c35e-498c-97d9-2c9d5904edc2">

### Expected results

The app should not crash.

### Actual results

The app is crashing.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
  Fatal Exception: java.lang.IllegalArgumentException: Volume external_primary not found
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2014)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1813)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1490)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:55)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.getPathsFromIntent(ImagePickerDelegate.java:673)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:684)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0(ImagePickerDelegate.java:615)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1 24B83 darwin-x64, locale
    fr-FR)
    • Flutter version 3.24.4 on channel stable at
      /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.95.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS
      18.1 22B83
    • macOS (desktop)         • macos                     • darwin-x64     •
      macOS 15.1 24B83 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript •
      Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Tom3652 
It may be related to the permissions depending on api level you are using. Can you take a look at https://stackoverflow.com/questions/63111091/java-lang-illegalargumentexception-volume-external-primary-not-found-in-android to see if it helps in your case or not ?

**Comment by Tom3652** [comment]
Hi @darshankawar thanks for the link, i think you may right but the code is inside the `image_picker` plugin, i have no native code in my app so i can't do this kind of check. 
I think it should be done inside the plugin code if there is something to catch here.

**Comment by darshankawar** [comment]
Since you mentioned image_picker, I looked it up and found that related case is documented here https://pub.dev/packages/image_picker_android#photo-picker. Can you try to to toggle this flag to true:
`imagePickerImplementation.useAndroidPhotoPicker = true` and check if it helps further or not ?

**Comment by Tom3652** [comment]
Thanks for the link, i have double checked it but i don't things it is relevant since it's a setup to use the Android photo picker on older Android versions.

I don't actually / especially want to use that picker.

When i build my app i test it on a Motorola under android 11 and i have a very correct output with the picker. I have never got any crashes before without using this Android photo picker.

The crash i mention here should not happen even if i choose to not use the Android photo picker on older versions.

**Comment by darshankawar** [comment]
Are you trying to access images or files from external storage such as SD card ?

**Comment by Tom3652** [comment]
It is possible, but it's one of my live users that had this crash i have no idea what he tried to do but it's maybe the case indeed if we look at `external_primary` not found.

**Comment by darshankawar** [comment]
Or maybe trying to select non-image file from image_picker selection. Is there a way to confirm this from user ?

**Comment by Tom3652** [comment]
Mmh it is possible that he tried to pick non-image file indeed. I am using these methods in the app : 

- `ImagePicker().pickImage(source: ImageSource.gallery)`
- `ImagePicker().pickMedia()`
- `ImagePicker().pickMultiImage()`
- `ImagePicker().pickMultipleMedia()`

According to the stack trace provided : ` at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:684)
` 

We can guess the method used is to pick Images but i am not sure.

> Is there a way to confirm this from user ? 

Unfortunately no since the crash logs are anonymized and i have no user ID binded to this one...

**Comment by darshankawar** [comment]
> ```
> at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:55)
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.getPathsFromIntent(ImagePickerDelegate.java:673)
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:684)
>        at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0(ImagePickerDelegate.java:615)
> ```

I will keep the issue open based on this stacktrace pointing to image_picker plugin. 

Maybe the case that `FileUtils.getPathFromUri` could return `null` for an internal error but then `handleChooseImageResult` may continue to run without checking `null` ?

**Comment by esodot** [comment]
Crashes only on Android once I create an APK. Testing it on simulator in debug mode or connected to physical device in debug mode, works and camera opens. 
But with APK release it crashes on simulator and physical device once calling.
`      var imageFile = await imagePicker.pickImage(
        source: source,
        maxWidth: 500,
        maxHeight: 500,
        imageQuality: quality,
      );`

**Comment by arham-anees** [comment]
I am facing the same issue but I have a very different stack trace. Though it is the same line as @esodot which is crashing in release mode while working fine in debug mode. This crash started after change to the `settings.gradle`,  and `build.gradle` files in android. 
I have tried downgrading the package but the app keeps crashing. I have also https://pub.dev/packages/image_picker_android#photo-picker in my app. 
A fix would be appreciated.

**Comment by AhmedAlaaGenina** [comment]
Hello all 
also app carsh with me but with diffrent error 
the error: 
java.lang.IllegalStateException: Own package not found for user 95: package=com.google.android.photopicker
the code: 
      XFile? image = await ImagePicker().pickImage(source: ImageSource.gallery);
any help ?

**Comment by antoinepemeja** [comment]
Same issue, in debug camera open without issue. In release mode app crash :
Android 15.0 Google Pixel 6a
Android 14.0 Google Pixel 6a

`image_picker: ^1.1.2`

`final XFile? image = await _picker.pickImage(source: ImageSource.camera, imageQuality: 10);`
`final XFile? image = await _picker.pickImage(source: ImageSource.gallery, imageQuality: 10);`

```
2025-02-04 12:04:51.257 28005-29430 AndroidRuntime          com.nanolike.binconnect.staging      E  FATAL EXCEPTION: flutter-worker-2
Process: com.nanolike.binconnect.staging, PID: 28005
java.lang.IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'v9.a' in call to 'java.lang.String v9.a.c()' (declaration of 'io.flutter.plugins.imagepicker.ImagePickerFileProvider' appears in /data/app/~~tDcSjUkH1dwT3lQAKY64tg==/com.nanolike.binconnect.staging-gEx7VrRs6Hd94Ce5f7wzqw==/base.apk)
	at io.flutter.plugins.imagepicker.ImagePickerFileProvider.k(SourceFile:56)
	at io.flutter.plugins.imagepicker.ImagePickerFileProvider.e(SourceFile:1)
	at b3.c.l(SourceFile:6)
	at io.flutter.plugins.imagepicker.j.j(SourceFile:74)
	at io.flutter.plugins.imagepicker.s.x(SourceFile:622)
	at com.google.android.gms.internal.measurement.u5.b(SourceFile:28)
	at v7.b.run(SourceFile:138)
	at v7.i.b(SourceFile:1)
	at v7.h.run(SourceFile:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Androidsignal** [comment]
> Since you mentioned image_picker, I looked it up and found that related case is documented here https://pub.dev/packages/image_picker_android#photo-picker. Can you try to to toggle this flag to true: `imagePickerImplementation.useAndroidPhotoPicker = true` and check if it helps further or not ?

Its working
