### ISSUE TITLE
ListView generating Failed assertion 'hasSize'

### ISSUE THREAD

**Issue by robertflesch** [flutter/flutter#15831]
Goal is to put a ListView as a child of a page.
```
Widget _seasonData = new Container(
    child: new StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection('teamSeason').where( "teamName", isEqualTo: "BayCityRollers" ).snapshots,
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (!snapshot.hasData) return const Text('Loading...');
        return new ListView(
          shrinkWrap: true,
          children: snapshot.data.documents.map((DocumentSnapshot document) {
            new Text(
              document['seasonName'],
              style: Theme.of(context).textTheme.headline,
            );
          }).toList(),
        );
      },
    ),
  );

Launching lib\main.dart on Moto G 4 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk (28.9MB).
I/FlutterActivityDelegate(14478): onResume setting current activity to this
Syncing files to device Moto G 4...
W/common.FileUtils(14478): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
W/common.FileUtils(14478): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
W/common.FileUtils(14478): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
W/common.FileUtils(14478): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
W/linker  (14478): /data/app/com.google.android.gms-2/lib/arm/libconscrypt_gmscore_jni.so: unused DT entry: type 0xf arg 0x1dc
V/NativeCrypto(14478): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 279 native methods...
D/NetworkSecurityConfig(14478): No Network Security Config specified, using platform default
I/ProviderInstaller(14478): Installed default security provider GmsCore_OpenSSL
I/flutter (14478): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (14478): The following assertion was thrown during performLayout():
I/flutter (14478): 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 291: 'child != null': is not true.
I/flutter (14478): 
I/flutter (14478): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14478): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14478): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14478):   https://github.com/flutter/flutter/issues/new
I/flutter (14478): 
I/flutter (14478): When the exception was thrown, this was the stack:
I/flutter (14478): #2      SliverChildListDelegate.build (package:flutter/src/widgets/sliver.dart:291)
I/flutter (14478): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716)
I/flutter (14478): #4      _HashMap.putIfAbsent (dart:collection-patch/dart:collection/collection_patch.dart:143)
I/flutter (14478): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716)
I/flutter (14478): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729)
I/flutter (14478): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205)
I/flutter (14478): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722)
I/flutter (14478): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254)
I/flutter (14478): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666)
I/flutter (14478): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740)
I/flutter (14478): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666)
I/flutter (14478): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243)
I/flutter (14478): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351)
I/flutter (14478): #15     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78)
I/flutter (14478): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182)
I/flutter (14478): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285)
I/flutter (14478): #20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1335)
I/flutter (14478): #21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1298)
I/flutter (14478): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter (14478): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #39     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738)
I/flutter (14478): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter (14478): #41     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124)
I/flutter (14478): #42     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:256)
I/flutter (14478): #43     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194)
I/flutter (14478): #44     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338)
I/flutter (14478): #45     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445)
I/flutter (14478): #46     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709)
I/flutter (14478): #47     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270)
I/flutter (14478): #48     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622)
I/flutter (14478): #49     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter (14478): #50     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter (14478): #51     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter (14478): #52     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter (14478): #53     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter (14478): #54     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (14478): (elided 2 frames from class _AssertionError)
I/flutter (14478): 
I/flutter (14478): The following RenderObject was being processed when the exception was fired:
I/flutter (14478):   RenderSliverList#02bc9 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (14478):   creator: SliverList ← MediaQuery ← SliverPadding ← ShrinkWrappingViewport ← _ScrollableScope ←
I/flutter (14478):   IgnorePointer-[GlobalKey#425ac] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (14478):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#663b0] ←
I/flutter (14478):   _ExcludableScrollSemantics-[GlobalKey#4be4e] ← RepaintBoundary ← ⋯
I/flutter (14478):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (14478):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (14478):   scrollOffset: 0.0, remainingPaintExtent: Infinity, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (14478):   AxisDirection.right, viewportMainAxisExtent: Infinity)
I/flutter (14478):   geometry: null
I/flutter (14478):   no children current live
I/flutter (14478): This RenderObject has no descendants.
I/flutter (14478): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (14478): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (14478): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (14478): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1446: 'hasSize': is not true.
.... a number of these
I/flutter (14478): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1446: 'hasSize': is not true.
I/FirebaseAuth(14478): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(14478): [FirebaseAuth:] Preparing to create service connection to gms implementation


Analyzing C:\Users\TheBeast\IdeaProjects\clearfocussports...
  hint - Unused import: 'dart:math' at lib\main.dart:6:8 - unused_import
  hint - Unused import: 'dart:io' at lib\main.dart:7:8 - unused_import
  hint - Unused import: 'package:firebase_database/ui/firebase_animated_list.dart' at lib\main.dart:16:8 - unused_import
  hint - Unused import: 'package:firebase_storage/firebase_storage.dart' at lib\main.dart:17:8 - unused_import
  hint - Unused import: 'package:image_picker/image_picker.dart' at lib\main.dart:20:8 - unused_import
  hint - Unused import: 'package:video_player/video_player.dart' at lib\main.dart:21:8 - unused_import
  hint - The function '_ensureLoggedIn' isn't used at lib\main.dart:217:14 - unused_element
  hint - The value of the local variable 'dr' isn't used at lib\main.dart:390:21 - unused_local_variable
  hint - Method doesn't override an inherited method at lib\smackChat.dart:56:10 - override_on_non_overriding_method
9 issues found.

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.1.5 at E:\devTools\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\TheBeast\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\TheBeast\AppData\Local\Android\Sdk
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] IntelliJ IDEA Ultimate Edition (version 2016.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] Connected devices (1 available)
    • Moto G 4 • ZY223TFZPN • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by Hixie** [comment]
You are missing a `return` in the closure you pass to `map`, so it's just returning null instead.

**Comment by zoechi** [comment]
I assume this is solved by Hixies comment.
