### ISSUE TITLE
[in_app_purchase] java.lang.NullPointerException on debug console

### ISSUE THREAD

**Issue by siamahnaf** [flutter/flutter#158442]
### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

```
dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.2.0
```

### Steps to reproduce

1. The error only throwed on a purchase subscribed or close window without subscribed

### Expected results

Even I try it with using Subscription Stream, it showing me up same issues.

### Actual results

When I click on Subscribe button, it open a subscribe window like image. Now if close this window by clicking outside of the window or even when I subscribe it, then the of closing the window, the error is thrown on debug console.

I didn't write huge code, just install the package, initialize it and get products then handler. I do not do anything on my android folder.

The error is like the second image.

### Code sample

```
class _SubscriptionPageState extends State<SubscriptionPage> {
  final InAppPurchase _inAppPurchase = InAppPurchase.instance;

  //Product Listing
  static const List<String> _productIds = ['com....subscription'];

  Future<Subscription> getProducts() async {
    final bool isAvailable = await _inAppPurchase.isAvailable();
    if (!isAvailable) {
      return Subscription(
        isAvailable: isAvailable,
        products: [],
        notFoundIds: [],
      );
    }
    final ProductDetailsResponse productDetailResponse =
        await _inAppPurchase.queryProductDetails(_productIds.toSet());

    if (productDetailResponse.error != null) {
      throw Exception(productDetailResponse.error!.message);
    }
    return Subscription(
      isAvailable: isAvailable,
      products: productDetailResponse.productDetails,
      notFoundIds: productDetailResponse.notFoundIDs,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: QueryBuilder(
        query: Query(
          key: ['subscription'],
          queryFn: () => getProducts(),
          config: QueryConfig(
            storeQuery: false,
            cacheDuration: const Duration(milliseconds: 500),
          ),
        ),
        builder: (context, state) {
          final product = state.data!.products[0];
          return BasicAppButton(
            title: 'Subscribe',
            onPressed: () {
              final PurchaseParam param = GooglePlayPurchaseParam(
                productDetails: product,
                changeSubscriptionParam: null,
              );
              _inAppPurchase.buyNonConsumable(
                purchaseParam: param,
              );
            },
            level: '3',
          );
        },
      ),
    );
  }
}
```

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/80146027-c300-49ab-bcb2-ee88dbf4aad4)

### Logs

![image (1)](https://github.com/user-attachments/assets/13fe5c2c-255a-402e-aacb-a32e2fe1a12e)

### Flutter Doctor output

![image](https://github.com/user-attachments/assets/441e3bee-a1f7-4392-9ece-f2dd165b5f34)

**Comment by darshankawar** [comment]
@siamahnaf 
Can you provide the complete error log in properly formatted text instead of in screenshot ?
Also, please provide a complete runnable reproducible code sample that triggers this error.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by siamahnaf** [comment]
I can share the whole code with you but not on publicly.

I invite to you join my repository where you find the whole code (Please consider it). As it already published on google play and it has some critical information.


Step to reproduce (See the following video)

https://github.com/user-attachments/assets/3f4d2901-8b13-4ec1-9615-0cc4b5a5faf5

**On the video, the error also occurred successfully subscribe it.**

Here is the complete log-

```
W/BillingLogger( 9609): Unable to log.
W/BillingLogger( 9609): java.lang.NullPointerException
W/BillingLogger( 9609): 	at com.google.android.gms.internal.play_billing.zzbp.<init>(com.android.billingclient:billing@@6.2.0:4)
W/BillingLogger( 9609): 	at com.google.android.gms.internal.play_billing.zzdd.zzA(com.android.billingclient:billing@@6.2.0:4)
W/BillingLogger( 9609): 	at com.google.android.gms.internal.play_billing.zzdd.zzk(com.android.billingclient:billing@@6.2.0:2)
W/BillingLogger( 9609): 	at com.google.android.gms.internal.play_billing.zzgy.zzB(com.android.billingclient:billing@@6.2.0:1)
W/BillingLogger( 9609): 	at com.android.billingclient.api.zzcd.zzc(com.android.billingclient:billing@@6.2.0:1)
W/BillingLogger( 9609): 	at com.android.billingclient.api.zzj.onReceive(com.android.billingclient:billing@@6.2.0:12)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1814)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/BillingLogger( 9609): 	at android.os.Handler.handleCallback(Handler.java:959)
W/BillingLogger( 9609): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/BillingLogger( 9609): 	at android.os.Looper.loopOnce(Looper.java:232)
W/BillingLogger( 9609): 	at android.os.Looper.loop(Looper.java:317)
W/BillingLogger( 9609): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
W/BillingLogger( 9609): 	at java.lang.reflect.Method.invoke(Native Method)
W/BillingLogger( 9609): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
W/BillingLogger( 9609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
W/BillingLogger( 9609): Unable to create logging payload
W/BillingLogger( 9609): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
W/BillingLogger( 9609): 	at com.android.billingclient.api.zzcd.zzf(com.android.billingclient:billing@@6.2.0:7)
W/BillingLogger( 9609): 	at com.android.billingclient.api.zzj.onReceive(com.android.billingclient:billing@@6.2.0:20)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1814)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
W/BillingLogger( 9609): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
W/BillingLogger( 9609): 	at android.os.Handler.handleCallback(Handler.java:959)
W/BillingLogger( 9609): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/BillingLogger( 9609): 	at android.os.Looper.loopOnce(Looper.java:232)
W/BillingLogger( 9609): 	at android.os.Looper.loop(Looper.java:317)
W/BillingLogger( 9609): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
W/BillingLogger( 9609): 	at java.lang.reflect.Method.invoke(Native Method)
W/BillingLogger( 9609): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
W/BillingLogger( 9609): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

Here is full widget-

```

//Product Listing
const List<String> _productIds = ['com.fitnesschallengeuk.subscription'];

class SubscriptionPage extends StatefulWidget {
  const SubscriptionPage({super.key});

  @override
  State<SubscriptionPage> createState() => _SubscriptionPageState();
}

class _SubscriptionPageState extends State<SubscriptionPage> {
  final InAppPurchase _inAppPurchase = InAppPurchase.instance;
  late StreamSubscription<List<PurchaseDetails>> _subscription;

  @override
  void initState() {
    final Stream<List<PurchaseDetails>> purchaseUpdated =
        _inAppPurchase.purchaseStream;
    _subscription =
        purchaseUpdated.listen((List<PurchaseDetails> purchaseDetailsList) {
      if (mounted) {
        _listenToPurchaseUpdated(purchaseDetailsList, context);
      }
    }, onDone: () {
      _subscription.cancel();
    }, onError: (Object error) {
      if (mounted) {
        showSnackBar(context, 'Something went wrong', Severity.error);
      }
    });
    super.initState();
  }

  Future<Subscription> getProducts() async {
    final bool isAvailable = await _inAppPurchase.isAvailable();
    if (!isAvailable) {
      return Subscription(
        isAvailable: isAvailable,
        products: [],
        notFoundIds: [],
      );
    }
    final ProductDetailsResponse productDetailResponse =
        await _inAppPurchase.queryProductDetails(_productIds.toSet());

    if (productDetailResponse.error != null) {
      throw Exception(productDetailResponse.error!.message);
    }
    return Subscription(
      isAvailable: isAvailable,
      products: productDetailResponse.productDetails,
      notFoundIds: productDetailResponse.notFoundIDs,
    );
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    var media = MediaQuery.of(context).size;
    return Scaffold(
      appBar: const BasicAppBar(
        title: 'Subscription',
        isBack: true,
        level: '3',
      ),
      body: QueryBuilder(
        query: Query(
          key: ['subscription'],
          queryFn: () => getProducts(),
          config: QueryConfig(
            storeQuery: false,
          ),
        ),
        builder: (context, state) {
          if (state.status == QueryStatus.loading) {
            return const Center(
              child: SizedBox(
                width: 25,
                height: 25,
                child: CircularProgressIndicator(
                  color: AppColors.primaryOrange,
                  strokeWidth: 3,
                ),
              ),
            );
          }
          if (state.status == QueryStatus.error) {
            return SizedBox(
              width: media.width,
              child: Text(
                state.error.toString(),
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                  color: Colors.red,
                ),
                textAlign: TextAlign.center,
              ),
            );
          }
          final product = state.data!.products[0];
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 10),
            child: SizedBox(
              width: media.width,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Text(
                    product.title
                        .replaceAll(
                            '(com.fitnesschallengeuk.fitness_challenge_uk (unreviewed))',
                            '')
                        .trim(),
                    style: const TextStyle(
                      fontSize: 16,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: media.height * 0.06),
                  SvgPicture.asset(
                    AppVectors.subscriptionIcon,
                    width: 260,
                  ),
                  SizedBox(height: media.height * 0.065),
                  Text(
                    product.price,
                    style: const TextStyle(
                      fontSize: 35,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  const Text('/month'),
                  SizedBox(height: media.height * 0.06),
                  Text(
                    product.description,
                    style: const TextStyle(
                      fontSize: 13,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const Spacer(),
                  const Text(
                    'Are you want to subscribe?',
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 30),
                  BasicAppButton(
                    title: 'Subscribe',
                    onPressed: () {
                      final PurchaseParam param = GooglePlayPurchaseParam(
                        productDetails: product,
                        changeSubscriptionParam: null,
                      );
                      _inAppPurchase.buyNonConsumable(
                        purchaseParam: param,
                      );
                    },
                    level: '3',
                  ),
                  const SizedBox(height: 20),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  final Mutation<Success, SubscriptionParams> _purchaseMutation = Mutation(
    queryFn: (arg) =>
        serviceLocator<SubscriptionRepository>().verifySubscription(arg),
    onError: (arg, error, fallback) {
      showSnackBar(
        arg.context,
        'An error occurred while processing your subscription',
        Severity.error,
      );
    },
    onSuccess: (res, arg) {
      ScaffoldMessenger.of(arg.context).hideCurrentSnackBar();
      Navigator.of(arg.context).pop();
    },
  );

  Future<void> _listenToPurchaseUpdated(
      List<PurchaseDetails> purchaseDetailsList, BuildContext context) async {
    for (final PurchaseDetails purchaseDetails in purchaseDetailsList) {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        showSnackBar(
          context,
          'You are purchasing a subscription',
          Severity.success,
        );
      } else if (purchaseDetails.status == PurchaseStatus.error) {
        showSnackBar(
          context,
          'Your purchased failed!',
          Severity.error,
        );
      } else if (purchaseDetails.status == PurchaseStatus.purchased) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Processing your purchase...'),
            backgroundColor: Colors.black,
            duration: Duration(days: 1),
          ),
        );
        _purchaseMutation.mutate(SubscriptionParams(
          token: purchaseDetails.verificationData.serverVerificationData,
          context: context,
        ));
      }
    }
  }
}

```

**Comment by darshankawar** [comment]
@siamahnaf 
From the error log you shared, they are coming from native Android and not from flutter plugin. 
The repo you shared seems to be a full fledged app, but in order to properly address or narrow down the issue to flutter plugin, we only need minimal reproducible code sample that triggers the reported error, so please provide one if it is possible.

**Comment by darshankawar** [comment]
> java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

This is the error that you will need to check in your code implementation. Seems you are passing null or value is null when it is not suppose to be.

**Comment by siamahnaf** [comment]
Okay, this is the only code where I am providing something-

```
final PurchaseParam param = GooglePlayPurchaseParam(
        productDetails: product,
        changeSubscriptionParam: null,
);
_inAppPurchase.buyNonConsumable(
        purchaseParam: param
)
```

But in the product, it has value. Because I am using show product info in my UI. Is there any specific field under product which are getting null. Give suggestion of list to check me so that I can ensure it is null or not.!

**Comment by darshankawar** [comment]
You must be calling `iterator()` method on a `null` List, to avoid this you can have a list != null check where ever you are using it to see if it helps to resolve the issue or not.

**Comment by siamahnaf** [comment]
I check all my code.
1. As the error throwed from the package, that means I provide null where the package want list. But it is 100% sure that, error not producing from my code.

2. Then I check my code where I am providing null to the 'in_app_purchase' package. I check every line of my code. I am not providing any wrong data.

So, it might be a bug from the package!

**Comment by huycozy** [comment]
I can reproduce this issue using [package's example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example). The current Android platform package version `in_app_purchase_android: ^0.3.6+12`. 

I doubt this may be caused by Android billing library, I also found a similar [issue](https://discussions.unity.com/t/unity-iap-4-12-0-receiving-warnings-of-nullpointerexeptions-during-logging-from-within-billing/949480/19) on Unity forum. Keeping this for further insights.

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-x64, locale en-VN)
    • Flutter version 3.24.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (32 hours ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_SDK_ROOT = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio Ladybug.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.1 24B83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by siamahnaf** [comment]
Hello, what's the update as @huycozy said that he can reproduce it!

**Comment by stuartmorgan** [comment]
It doesn't look like there's any plugin code in the stack, so the issue may be in the SDK rather than the plugin.

**Comment by mhlim8157** [comment]
I am facing the same issue too! Is there any solution? I'm using in_app_purchase v3.2.0

**Comment by RobertOdrowaz** [comment]
The exception was caused by the Google Play Billing Library, so it should be resolved in `in_app_purchase: ^3.2.1` (`in_app_purchase_android: ^0.4.0`), which uses the new version of the Google Play Billing Library (7.1.1)
