### ISSUE TITLE
[tool_crash] StateError: Bad state: dart pub deps --json had unexpected output: Expected field "devDependencies" to be a list, got "null"

### ISSUE THREAD

**Issue by KarlMathuthu** [flutter/flutter#158445]
## Command
```sh
flutter run --machine --start-paused -d 00008020-00180D561E41002E --devtools-server-address http://127.0.0.1:9100/ --target /Users/wakhiwekarl/Flutter Projects/swap-teach/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: dart pub deps --json had unexpected output: Expected field "devDependencies" to be a list, got "null"
```console
#0      computeExclusiveDevDependencies.fail (package:flutter_tools/src/compute_dev_dependencies.dart:33:5)
#1      computeExclusiveDevDependencies.asListOrFail (package:flutter_tools/src/compute_dev_dependencies.dart:68:7)
#2      computeExclusiveDevDependencies (package:flutter_tools/src/compute_dev_dependencies.dart:117:39)
<asynchronous suspension>
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:130:23)
<asynchronous suspension>
#4      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1061:32)
<asynchronous suspension>
#5      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:31:3)
<asynchronous suspension>
#6      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:280:3)
<asynchronous suspension>
#7      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:488:44)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:483:33)
<asynchronous suspension>
#9      HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart:426:14)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:520:21)
<asynchronous suspension>
#11     HotRunner.run (package:flutter_tools/src/run_hot.dart:457:34)
<asynchronous suspension>
#12     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:824:9)
<asynchronous suspension>
#13     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:822:5)
```
```console
[!] Flutter (Channel master, 3.27.0-1.0.pre.443, on macOS 14.6.1 23G93 darwin-x64, locale en-GB)
    • Flutter version 3.27.0-1.0.pre.443 on channel master at /Users/wakhiwekarl/flutter
    ! The flutter binary is not on your path. Consider adding /Users/wakhiwekarl/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.5.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/wakhiwekarl/flutter. Consider adding /Users/wakhiwekarl/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5fd650f68b (6 hours ago), 2024-11-10 23:02:25 -0500
    • Engine revision 01c76e42c2
    • Dart version 3.7.0 (build 3.7.0-123.0.dev)
    • DevTools version 2.41.0-dev.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices
    • Android SDK at /Users/wakhiwekarl/Library/Android/sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.

**Comment by danagbemava-nc** [comment]
Hi @KarlMathuthu, this is being tracked in https://github.com/flutter/flutter/issues/158441. Kindly follow up in the original issue for updates. 

Please share any additional information you can in the original issue. 

Thank you

**Comment by KarlMathuthu** [comment]
Alright, thanks mate!
