### ISSUE TITLE
flutter build apk issue

### ISSUE THREAD

**Issue by trevburley** [flutter/flutter#15840]
## Steps to Reproduce

Not sure if this is a flutter issue or just me doing something wrong. I'm a react native developer just experimenting with Flutter's animations at the moment to scope it's viability for a new project I have coming up.

Running in the simulator works perfectly.

Running flutter build apk (after following the instructions here: https://flutter.io/android-release/) fails with the following error:

## Logs

**flutter build apk -v**
```
> D:\Flutter Apps\logoanimationapp>flutter build apk -v
> [  +28 ms] [D:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
> [  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [        ] origin/beta
> [        ] [D:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
> [  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [        ] beta
> [        ] [D:\Flutter\flutter\] git ls-remote --get-url origin
> [  +70 ms] Exit code 0 from: git ls-remote --get-url origin
> [        ] https://github.com/flutter/flutter.git
> [        ] [D:\Flutter\flutter\] git log -n 1 --pretty=format:%H
> [  +64 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
> [        ] 3ea4d06340a97a1e9d7cae97567c64e0569dcaa2
> [        ] [D:\Flutter\flutter\] git log -n 1 --pretty=format:%ar
> [  +71 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
> [        ] 4 weeks ago
> [        ] [D:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
> [  +61 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
> [        ] v0.1.5-0-g3ea4d0634
> [ +323 ms] Initializing gradle...
> [   +1 ms] Using gradle from D:\Flutter Apps\logoanimationapp\android\gradlew.bat.
> [  +95 ms] D:\Flutter Apps\logoanimationapp\android\gradlew.bat -v
> [ +617 ms]
>                    ------------------------------------------------------------
>                    Gradle 4.1
>                    ------------------------------------------------------------
> 
>                    Build time:   2017-08-07 14:38:48 UTC
>                    Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
> 
>                    Groovy:       2.4.11
>                    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
>                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
>                    OS:           Windows 10 10.0 amd64
> [   +6 ms] Resolving dependencies...
> [        ] [android\] D:\Flutter Apps\logoanimationapp\android\gradlew.bat app:properties
> [+1204 ms] NDK is missing a "platforms" directory.
>                    If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Applications\Android\SDK\ndk-bundle.
>                    If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
> 
>                    :app:properties
> 
>                    ------------------------------------------------------------
>                    Project :app
>                    ------------------------------------------------------------
> 
>                    allprojects: [project ':app']
>                    android: com.android.build.gradle.AppExtension_Decorated@3d2fb6a2
>                    androidDependencies: task ':app:androidDependencies'
>                    ant: org.gradle.api.internal.project.DefaultAntBuilder@6c53cec8
>                    antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@45529665
>                    archivesBaseName: app
>                    artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@3deb4fe9
>                    asDynamicObject: DynamicObject for project ':app'
>                    assemble: task ':app:assemble'
>                    assembleAndroidTest: task ':app:assembleAndroidTest'
>                    assembleDebug: task ':app:assembleDebug'
>                    assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
>                    assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
>                    assembleProfile: task ':app:assembleProfile'
>                    assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
>                    assembleRelease: task ':app:assembleRelease'
>                    assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
>                    baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@7d317450
>                    buildDependents: task ':app:buildDependents'
>                    buildDir: D:\Flutter Apps\logoanimationapp\build\app
>                    buildFile: D:\Flutter Apps\logoanimationapp\android\app\build.gradle
>                    buildNeeded: task ':app:buildNeeded'
>                    buildOutputs: BaseVariantOutput container
>                    buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@fe6d0b0
>                    buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@5e569e97
>                    bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
>                    bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
>                    bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
>                    bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
>                    bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
>                    bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
>                    bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
>                    check: task ':app:check'
>                    checkDebugManifest: task ':app:checkDebugManifest'
>                    checkProfileManifest: task ':app:checkProfileManifest'
>                    checkReleaseManifest: task ':app:checkReleaseManifest'
>                    childProjects: {}
>                    class: class org.gradle.api.internal.project.DefaultProject_Decorated
>                    classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@39a516b3
>                    cleanBuildCache: task ':app:cleanBuildCache'
>                    compileDebugAidl: task ':app:compileDebugAidl'
>                    compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
>                    compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
>                    compileDebugAndroidTestKotlin: task ':app:compileDebugAndroidTestKotlin'
>                    compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
>                    compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
>                    compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
>                    compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
>                    compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
>                    compileDebugKotlin: task ':app:compileDebugKotlin'
>                    compileDebugNdk: task ':app:compileDebugNdk'
>                    compileDebugRenderscript: task ':app:compileDebugRenderscript'
>                    compileDebugShaders: task ':app:compileDebugShaders'
>                    compileDebugSources: task ':app:compileDebugSources'
>                    compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
>                    compileDebugUnitTestKotlin: task ':app:compileDebugUnitTestKotlin'
>                    compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
>                    compileLint: task ':app:compileLint'
>                    compileProfileAidl: task ':app:compileProfileAidl'
>                    compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
>                    compileProfileKotlin: task ':app:compileProfileKotlin'
>                    compileProfileNdk: task ':app:compileProfileNdk'
>                    compileProfileRenderscript: task ':app:compileProfileRenderscript'
>                    compileProfileShaders: task ':app:compileProfileShaders'
>                    compileProfileSources: task ':app:compileProfileSources'
>                    compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
>                    compileProfileUnitTestKotlin: task ':app:compileProfileUnitTestKotlin'
>                    compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
>                    compileReleaseAidl: task ':app:compileReleaseAidl'
>                    compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
>                    compileReleaseKotlin: task ':app:compileReleaseKotlin'
>                    compileReleaseNdk: task ':app:compileReleaseNdk'
>                    compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
>                    compileReleaseShaders: task ':app:compileReleaseShaders'
>                    compileReleaseSources: task ':app:compileReleaseSources'
>                    compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
>                    compileReleaseUnitTestKotlin: task ':app:compileReleaseUnitTestKotlin'
>                    compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
>                    components: SoftwareComponentInternal set
>                    configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@4fc06623
>                    configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@761a5c3b
>                    configurations: configuration container
>                    connectedAndroidTest: task ':app:connectedAndroidTest'
>                    connectedCheck: task ':app:connectedCheck'
>                    connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
>                    consumeConfigAttr: task ':app:consumeConfigAttr'
>                    convention: org.gradle.api.internal.plugins.DefaultConvention@1cd2c649
>                    copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
>                    copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
>                    copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
>                    createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
>                    createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
>                    createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
>                    defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@d534bee
>                    defaultTasks: []
>                    deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@41eec519
>                    dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@6531b29b
>                    depth: 1
>                    description: null
>                    deviceAndroidTest: task ':app:deviceAndroidTest'
>                    deviceCheck: task ':app:deviceCheck'
>                    displayName: project ':app'
>                    distsDir: D:\Flutter Apps\logoanimationapp\build\app\distributions
>                    distsDirName: distributions
>                    docsDir: D:\Flutter Apps\logoanimationapp\build\app\docs
>                    docsDirName: docs
>                    ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@6fdbd0fa
>                    extensions: org.gradle.api.internal.plugins.DefaultConvention@1cd2c649
>                    extractProguardFiles: task ':app:extractProguardFiles'
>                    fileOperations: org.gradle.api.internal.file.DefaultFileOperations@7840ead4
>                    fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@4fb13ec8
>                    flutter: FlutterExtension_Decorated@27fce8cf
>                    flutterBuildDebug: task ':app:flutterBuildDebug'
>                    flutterBuildProfile: task ':app:flutterBuildProfile'
>                    flutterBuildRelease: task ':app:flutterBuildRelease'
>                    flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
>                    flutterDependenciesDebug: task ':app:flutterDependenciesDebug'
>                    flutterDependenciesProfile: task ':app:flutterDependenciesProfile'
>                    flutterDependenciesRelease: task ':app:flutterDependenciesRelease'
>                    generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
>                    generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
>                    generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
>                    generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
>                    generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
>                    generateDebugAssets: task ':app:generateDebugAssets'
>                    generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
>                    generateDebugResValues: task ':app:generateDebugResValues'
>                    generateDebugResources: task ':app:generateDebugResources'
>                    generateDebugSources: task ':app:generateDebugSources'
>                    generateProfileAssets: task ':app:generateProfileAssets'
>                    generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
>                    generateProfileResValues: task ':app:generateProfileResValues'
>                    generateProfileResources: task ':app:generateProfileResources'
>                    generateProfileSources: task ':app:generateProfileSources'
>                    generateReleaseAssets: task ':app:generateReleaseAssets'
>                    generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
>                    generateReleaseResValues: task ':app:generateReleaseResValues'
>                    generateReleaseResources: task ':app:generateReleaseResources'
>                    generateReleaseSources: task ':app:generateReleaseSources'
>                    gradle: build 'android'
>                    group: android
>                    identityPath: :app
>                    inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@1611b0ca
>                    installDebug: task ':app:installDebug'
>                    installDebugAndroidTest: task ':app:installDebugAndroidTest'
>                    installProfile: task ':app:installProfile'
>                    installRelease: task ':app:installRelease'
>                    javaPreCompileDebug: task ':app:javaPreCompileDebug'
>                    javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
>                    javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
>                    javaPreCompileProfile: task ':app:javaPreCompileProfile'
>                    javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
>                    javaPreCompileRelease: task ':app:javaPreCompileRelease'
>                    javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
>                    kapt: org.jetbrains.kotlin.gradle.plugin.KaptExtension_Decorated@69f8fe96
>                    kotlin: org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension_Decorated@2ff9ca1f
>                    kotlin_version: 1.1.51
>                    layout: org.gradle.api.internal.file.DefaultProjectLayout@6f83e5bf
>                    libsDir: D:\Flutter Apps\logoanimationapp\build\app\libs
>                    libsDirName: libs
>                    lint: task ':app:lint'
>                    lintDebug: task ':app:lintDebug'
>                    lintProfile: task ':app:lintProfile'
>                    lintRelease: task ':app:lintRelease'
>                    lintVitalRelease: task ':app:lintVitalRelease'
>                    logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@13b1287
>                    logging: org.gradle.internal.logging.services.DefaultLoggingManager@740f8f65
>                    mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
>                    mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
>                    mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
>                    mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
>                    mergeDebugAssets: task ':app:mergeDebugAssets'
>                    mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
>                    mergeDebugResources: task ':app:mergeDebugResources'
>                    mergeDebugShaders: task ':app:mergeDebugShaders'
>                    mergeProfileAssets: task ':app:mergeProfileAssets'
>                    mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
>                    mergeProfileResources: task ':app:mergeProfileResources'
>                    mergeProfileShaders: task ':app:mergeProfileShaders'
>                    mergeReleaseAssets: task ':app:mergeReleaseAssets'
>                    mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
>                    mergeReleaseResources: task ':app:mergeReleaseResources'
>                    mergeReleaseShaders: task ':app:mergeReleaseShaders'
>                    mockableAndroidJar: task ':app:mockableAndroidJar'
>                    modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@5aadd33c
>                    modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@17981207
>                    module: org.gradle.api.internal.artifacts.ProjectBackedModule@433c035e
>                    name: app
>                    normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@3be54344
>                    objects: org.gradle.api.internal.model.DefaultObjectFactory@70403bcb
>                    org.gradle.jvmargs: -Xmx1536M
>                    packageDebug: task ':app:packageDebug'
>                    packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
>                    packageProfile: task ':app:packageProfile'
>                    packageRelease: task ':app:packageRelease'
>                    parent: root project 'android'
>                    parentIdentifier: root project 'android'
>                    path: :app
>                    platformAttrExtractor: task ':app:platformAttrExtractor'
>                    pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@4bbbe79a
>                    plugins: [org.gradle.api.plugins.HelpTasksPlugin@5e09bf2f, com.android.build.gradle.api.AndroidBasePlugin@2c5d5a87, org.gradle.language.base.plugins.LifecycleBasePlugin@685ee
> b29, org.gradle.api.plugins.BasePlugin@86614b0, org.gradle.api.plugins.ReportingBasePlugin@35849b0d, org.gradle.platform.base.plugins.ComponentBasePlugin@13905539, org.gradle.language.base.plug
> ins.LanguageBasePlugin@2ddf8b5, org.gradle.platform.base.plugins.BinaryBasePlugin@73e4be5, org.gradle.api.plugins.JavaBasePlugin@75dcfad9, com.android.build.gradle.internal.coverage.JacocoPlugi
> n@507e9830, com.android.build.gradle.AppPlugin@24f8d8c5, org.jetbrains.kotlin.gradle.plugin.KotlinAndroidPluginWrapper@1683eff2, FlutterPlugin@5c90cd25]
>                    preBuild: task ':app:preBuild'
>                    preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
>                    preDebugBuild: task ':app:preDebugBuild'
>                    preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
>                    preProfileBuild: task ':app:preProfileBuild'
>                    preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
>                    preReleaseBuild: task ':app:preReleaseBuild'
>                    preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
>                    prepareLintJar: task ':app:prepareLintJar'
>                    processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
>                    processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
>                    processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
>                    processDebugJavaRes: task ':app:processDebugJavaRes'
>                    processDebugManifest: task ':app:processDebugManifest'
>                    processDebugResources: task ':app:processDebugResources'
>                    processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
>                    processOperations: org.gradle.api.internal.file.DefaultFileOperations@7840ead4
>                    processProfileJavaRes: task ':app:processProfileJavaRes'
>                    processProfileManifest: task ':app:processProfileManifest'
>                    processProfileResources: task ':app:processProfileResources'
>                    processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
>                    processReleaseJavaRes: task ':app:processReleaseJavaRes'
>                    processReleaseManifest: task ':app:processReleaseManifest'
>                    processReleaseResources: task ':app:processReleaseResources'
>                    processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
>                    project: project ':app'
>                    projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@43473d2f
>                    projectDir: D:\Flutter Apps\logoanimationapp\android\app
>                    projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
>                    projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@77472248
>                    projectPath: :app
>                    projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@6629a087
>                    properties: {...}
>                    providers: org.gradle.api.internal.provider.DefaultProviderFactory@141ec4c8
>                    reporting: org.gradle.api.reporting.ReportingExtension_Decorated@723a1cef
>                    reportsDir: D:\Flutter Apps\logoanimationapp\build\app\reports
>                    repositories: repository container
>                    resolveConfigAttr: task ':app:resolveConfigAttr'
>                    resources: org.gradle.api.internal.resources.DefaultResourceHandler@86ee9c2
>                    rootDir: D:\Flutter Apps\logoanimationapp\android
>                    rootProject: root project 'android'
>                    scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@46f5dfe5
>                    scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@6df37224
>                    serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@4f0cd611
>                    services: ProjectScopeServices
>                    signingReport: task ':app:signingReport'
>                    sourceCompatibility: 1.8
>                    sourceSets: SourceSet container
>                    splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
>                    splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
>                    splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
>                    splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
>                    standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@740f8f65
>                    state: project state 'EXECUTED'
>                    status: integration
>                    subprojects: []
>                    targetCompatibility: 1.8
>                    tasks: task set
>                    test: task ':app:test'
>                    testDebugUnitTest: task ':app:testDebugUnitTest'
>                    testProfileUnitTest: task ':app:testProfileUnitTest'
>                    testReleaseUnitTest: task ':app:testReleaseUnitTest'
>                    testReportDir: D:\Flutter Apps\logoanimationapp\build\app\reports\tests
>                    testReportDirName: tests
>                    testResultsDir: D:\Flutter Apps\logoanimationapp\build\app\test-results
>                    testResultsDirName: test-results
>                    transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
>                    transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
>                    transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
>                    transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
>                    transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
>                    transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
>                    transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
>                    transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
>                    transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
>                    transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
>                    transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
>                    transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
>                    transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
>                    transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
>                    transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
>                    transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
>                    transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
>                    transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
>                    transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
>                    transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
>                    transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
>                    transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
>                    uninstallAll: task ':app:uninstallAll'
>                    uninstallDebug: task ':app:uninstallDebug'
>                    uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
>                    uninstallProfile: task ':app:uninstallProfile'
>                    uninstallRelease: task ':app:uninstallRelease'
>                    validateSigningDebug: task ':app:validateSigningDebug'
>                    validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
>                    validateSigningProfile: task ':app:validateSigningProfile'
>                    validateSigningRelease: task ':app:validateSigningRelease'
>                    version: unspecified
>                    writeDebugApplicationId: task ':app:writeDebugApplicationId'
>                    writeProfileApplicationId: task ':app:writeProfileApplicationId'
>                    writeReleaseApplicationId: task ':app:writeReleaseApplicationId'
> 
>                    BUILD SUCCESSFUL in 1s
>                    1 actionable task: 1 executed
> [   +7 ms] Running 'gradlew assembleRelease'...
> [   +2 ms] [android\] D:\Flutter Apps\logoanimationapp\android\gradlew.bat -Ptarget=lib/main.dart assembleRelease
> [ +944 ms] NDK is missing a "platforms" directory.
> [   +1 ms] If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Applications\Android\SDK\ndk-bundle.
> [        ] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
> [ +199 ms] :app:preBuild UP-TO-DATE
> [  +18 ms] :app:preReleaseBuild UP-TO-DATE
> [   +9 ms] :app:compileReleaseAidl UP-TO-DATE
> [        ] :app:compileReleaseRenderscript UP-TO-DATE
> [        ] :app:checkReleaseManifest UP-TO-DATE
> [   +9 ms] :app:generateReleaseBuildConfig UP-TO-DATE
> [        ] :app:cleanMergeReleaseAssets UP-TO-DATE
> [        ] :app:flutterDependenciesRelease UP-TO-DATE
> [ +109 ms] :app:flutterBuildRelease FAILED
> [   +2 ms] FAILURE: Build failed with an exception.
> [        ] * What went wrong:
> [        ] Failed to capture snapshot of input files for task 'flutterBuildRelease' property 'sourceFiles' during up-to-date check.
> [        ] > Failed to create MD5 hash for file 'D:\Flutter\flutter\bin\cache\lockfile'.
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 1s
> [        ] 8 actionable tasks: 1 executed, 7 up-to-date
> [ +466 ms] "flutter apk" took 3,906ms.
> Gradle build failed: 1
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
> #1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:324)
> <asynchronous suspension>
> #2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:243)
> <asynchronous suspension>
> #3      buildApk (package:flutter_tools/src/android/apk.dart:36)
> <asynchronous suspension>
> #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:39)
> <asynchronous suspension>
> #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
> <asynchronous suspension>
> #6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
> <asynchronous suspension>
> #7      CommandRunner.runCommand (package:args/command_runner.dart:194)
> <asynchronous suspension>
> #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
> <asynchronous suspension>
> #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
> #10     new Future.sync (dart:async/future.dart:222)
> #11     CommandRunner.run (package:args/command_runner.dart:109)
> #12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
> #13     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
> <asynchronous suspension>
> #14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #16     _rootRun (dart:async/zone.dart:1126)
> #17     _CustomZone.run (dart:async/zone.dart:1023)
> #18     runZoned (dart:async/zone.dart:1501)
> #19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #20     run (package:flutter_tools/runner.dart:61)
> <asynchronous suspension>
> #21     main (package:flutter_tools/executable.dart:48)
> <asynchronous suspension>
> #22     main (file:///D:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
> #23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
> #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
> 
> 
> [  +27 ms] ensureAnalyticsSent: 20ms
> [   +2 ms] exiting with code 1
```

**flutter analyze**
```
> D:\Flutter Apps\logoanimationapp>flutter analyze
> Analyzing D:\Flutter Apps\logoanimationapp...
> No issues found!
> Ran in 5.5s
```
## Flutter Doctor
```
> D:\Flutter Apps\logoanimationapp>flutter doctor -v
> [√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.125], locale en-GB)
>     • Flutter version 0.1.5 at D:\Flutter\flutter
>     • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
>     • Engine revision ead227f118
>     • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759
> 
> [√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at D:\Applications\Android\SDK
>     • Android NDK at D:\Applications\Android\SDK\ndk-bundle
>     • Platform android-27, build-tools 27.0.3
>     • ANDROID_HOME = D:\Applications\Android\SDK
>     • Java binary at: D:\Applications\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> [√] Android Studio (version 3.0)
>     • Android Studio at D:\Applications\Android\Android Studio
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> [√] IntelliJ IDEA Community Edition (version 2017.3)
>     • Flutter plugin version 22.2.2
>     • Dart plugin version 173.4548.30
> 
> [!] Connected devices
>     ! No devices available
> 
> ! Doctor found issues in 1 category.
```
Anything else that's needed - please ask!

Many Thanks - Trev

**Comment by Hixie** [comment]
This part looks suspicious:
```
> [ +944 ms] NDK is missing a "platforms" directory.
> [   +1 ms] If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\Applications\Android\SDK\ndk-bundle.
> [        ] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
```

No idea what could be causing it though...

**Comment by thirddimensionstudios** [comment]
I've managed to fix it now but I can't be sure what the actual fix was (many changes were made). I made countless changes to the project, deleted a lot of lock files and reinstalled dependancies.

I also reinstalled all my Android sdk's etc just in case and checked all my path's.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
