### ISSUE TITLE
[flutter_markdown] Invalid image URI crashes the app (instead of just showing an error at the image area)

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#158428]
### Steps to reproduce

1. Run the code sample below.
2. Remove `https` from the URI in the text field.
3. Press on the Preview button to go to the preview page.
4. See the error is shown in the body of the page, i.e. in the `Markdown` widget.
5. Go back to the main page with the back button.
6. See the error is shown in the whole page, so the app is no longer working.

### Expected results

The image is not rendered, and an error widget is used instead like below.

![](https://github.com/user-attachments/assets/5ce9ca4c-e523-4e88-88b5-38090589dcea)

### Actual results

The Markdown widget itself causes an error, and then, to make matters worse, the whole app stops working.

This means that when my app has a Markdown editing feature, just a user's mistype in an image URI in the Markdown image notation will get the user into trouble. Nothing can be done any more and the editor content is lost (unless the app has state restoration logic). As long as it can happen, I cannot use the package for production.

FYI, the error differs depending on the typo:

- URI starting with `://`
    > Invalid empty scheme (at character 1)
- URI starting with `ttps://`
    > Unsupported operation: Cannot extract a file path from a ttps URI

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(
    MaterialApp(home: const EditorPage()),
  );
}

class EditorPage extends StatefulWidget {
  const EditorPage();

  @override
  State<EditorPage> createState() => _EditorPageState();
}

class _EditorPageState extends State<EditorPage> {
  late final TextEditingController _controller = TextEditingController()
    ..text = '# Image\n\n'
        '![](https://avatars.githubusercontent.com/u/20254485?v=4)';

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            TextFormField(
              controller: _controller,
              maxLines: 10,
            ),
            ElevatedButton(
              onPressed: () => Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (_) => PreviewPage(markdown: _controller.text),
                ),
              ),
              child: const Text('Preview'),
            ),
          ],
        ),
      ),
    );
  }
}

class PreviewPage extends StatelessWidget {
  const PreviewPage({required this.markdown});

  final String markdown;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Preview'),
      ),
      body: SafeArea(
        child: Markdown(data: markdown),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img src="https://github.com/user-attachments/assets/35a15f2b-69bd-4444-b0d7-2e58c2a4b821" height="400">

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following FormatException was thrown building MediaQuery(MediaQueryData(size: Size(694.0, 596.0), devicePixelRatio: 1.0, textScaler: no scaling, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, systemGestureInsets: EdgeInsets.zero, alwaysUse24HourFormat: true, accessibleNavigation: false, highContrast: false, onOffSwitchLabels: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional, gestureSettings: DeviceGestureSettings(touchSlop: null), displayFeatures: [], supportsShowingSystemContextMenu: false)):
Invalid empty scheme (at character 1)
://avatars.githubusercontent.com/u/20254485?v=4
^

The relevant error-causing widget was: 
  SafeArea SafeArea:file:///D:/xxxx/lib/main.dart:64:13
When the exception was thrown, this was the stack: 
#0      _Uri._fail (dart:core/uri.dart:1737:5)
#1      new _Uri.notSimple (dart:core/uri.dart:1601:9)
#2      Uri.parse (dart:core/uri.dart:1138:17)
#3      MarkdownBuilder._buildImage (package:flutter_markdown/src/builder.dart:604:25)
#4      MarkdownBuilder.visitElementAfter (package:flutter_markdown/src/builder.dart:511:11)
#5      Element.accept (package:markdown/src/ast.dart:53:15)
#6      Element.accept (package:markdown/src/ast.dart:50:17)
#7      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:202:12)
#8      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:405:25)
#9      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:348:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5766:11)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
...     Normal element mounting (40 frames)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#52     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#53     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (338 frames)
#391    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#392    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#393    Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#394    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#395    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#396    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#397    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#398    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#399    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#400    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#401    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#402    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#403    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#404    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#405    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#407    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#408    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#409    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#410    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#411    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#412    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#413    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#414    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#415    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#416    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#417    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#418    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#419    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#420    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#421    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#422    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#423    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#424    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#425    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#426    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#427    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#428    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#429    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#430    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#431    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#432    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#433    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#434    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#435    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#436    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#437    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#438    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#439    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#440    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#441    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#442    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#443    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#444    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#445    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#446    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#447    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#448    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#449    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#450    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#451    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#452    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#453    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#454    _invoke (dart:ui/hooks.dart:312:13)
#455    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#456    _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.22631.4317], locale ja-JP)
    • Flutter version 3.24.4 on channel stable at D:\xxxx\flutter\sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\xxxx\android\sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = D:\xxxx\android\sdk
    • Java binary at: D:\xxxx\java\jdks\jbr-17.0.11\bin\java
    • Java version OpenJDK Runtime Environment JBR-17.0.11+1-1312.2-nomod (build 17.0.11+1-b1312.2)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5
    • Flutter plugin version 82.1.3
    • Dart plugin version 242.22855.32

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.98.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 130.0.2849.56

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample and steps provided above. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (3 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```
[!] Flutter (Channel master, 3.27.0-1.0.pre.443, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    • Flutter version 3.27.0-1.0.pre.443 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5fd650f68b (6 hours ago), 2024-11-10 23:02:25 -0500
    • Engine revision 01c76e42c2
    • Dart version 3.7.0 (build 3.7.0-123.0.dev)
    • DevTools version 2.41.0-dev.2

```
</details>

**Comment by csells** [comment]
This is a pain, to be sure, @kaboc, but there is a workaround: include an `imageBuilder` with the `Markdown` constructor:

```dart
Markdown(
  data: '<your markdown goes here>',
  imageBuilder: (uri, title, alt) => Image.network(
    uri.toString(),
    // use an error builder to avoid the unhandled exception
    errorBuilder: (context, error, stack) => Placeholder(
      color: Colors.red,
      child: Text(error.toString()),
    ),
  ),
),
```

Ideally that would be the default implementation of the `flutter_markdown` internal image builder, but until that happens, the work-around isn't too bad.

**Comment by kaboc** [comment]
Unfortunately, I still get the error although I've already used it to customise the appearance. The error seems to be thrown at `Uri.parse()` being used without try-catch before the URI is passed to the builder. But, thank you for trying to help me, @csells!

**Comment by csells** [comment]
Are you sure you're using the latest version of flutter_markdown, @kaboc? Here's the whole example I'm using and it works the way I expect, both in the face of 404 on the image and malformed URLs:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

const markdown = '''
# Valid Image
![](https://avatars.githubusercontent.com/u/20254485)

# Valid URL, Invalid Image
![](https://example.com/image.jpg)

# Invalid URL
![](foo)
''';

void main() => runApp(const MaterialApp(home: MarkdownPage(markdown)));

class MarkdownPage extends StatelessWidget {
  const MarkdownPage(this.markdown, {super.key});
  final String markdown;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Markdown(
          data: markdown,
          imageBuilder: (uri, title, alt) => Image.network(
            uri.toString(),
            // use an error builder to avoid the unhandled exception
            errorBuilder: (context, error, stack) => Placeholder(
              color: Colors.red,
              child: Text(error.toString()),
            ),
          ),
        ),
      );
}
```

<img width="609" alt="image" src="https://github.com/user-attachments/assets/80e708fb-d587-42fb-bef9-2c75ad5a64be">

**Comment by csells** [comment]
Ah. You're totally right. The right way to fix that issue is with an update to `flutter_markdown` that translate a malformed URI into a `Placeholder` with the error message. The `imageBuilder` callback is not good enough, since the parsing of the URI itself happens before the call to the `imageBuilder`.

The only way to work around this is to pre-parse all of the image `src` properties and replace images with malformed URIs, which is far more trouble than the simple fix in `flutter_markdown` package.

**Comment by kaboc** [comment]
> The only way to work around this is to pre-parse all of the image src properties and replace images with malformed URIs

Sounds like a nice solution to work around the issue. I didn't come up with it. Thank you!

I happen to already have [a way to extract all of the `src` properties](https://bsky.app/profile/kaboc.bsky.social/post/3lbhi7srsc22b), so it shouldn't be difficult. (I think I need to add a check of the `img` tag name, which seems missing. I just now noticed it thanks to you.)

**Comment by csells** [comment]
this has not been fixed; the URI parsing should not cause a crash of the `Markdown` or `MarkdownBody` widgets and the default `imageBuilder` should provide an `errorBuilder` that creates a `Placeholder` widget by default. It should not be possible to crash a rendering of markdown, no matter how malformed.

**Comment by navaronbracke** [comment]
@csells To clarify, the current state of the plugin (after the fix that is mentioned here) is not exactly like what is stated in

> should provide an errorBuilder that creates a Placeholder widget by default

I opted to display empty `SizedBox` widgets for now, as to avoid the crashes. As a follow up, we could definitely update the default builder to return `Placeholder` widgets instead, although in that case, we should probably wire up an image error builder that the user can override. Perhaps adding an `imageErrorBuilder` callback, next to the existing `imageBuilder` is sufficient?

**Comment by csells** [comment]
I like what you came up with; you avoided both of the classes of crashes and I can still provide a placeholder for one of them. For the other kind of crash (the malformed url), I agree that some other error builder would be handy.

**Comment by danagbemava-nc** [comment]
Hi @csells, should this be closed? It appears there's still some work to be done here

**Comment by navaronbracke** [comment]
@danagbemava-nc Filed https://github.com/flutter/flutter/issues/159581 as a follow up issue for the extra customisation.
