### ISSUE TITLE
Flutter run stuck at hot reload and full restart

### ISSUE THREAD

**Issue by pahwa014** [flutter/flutter#15859]
While performing minor code changes and hot reloading the command prompt shows following errors
```
Performing hot reload...
Syncing files to device...
Hot reload failed: TimeoutException: Request to Dart VM Service timed out: _reloadSources({pause: false, rootLibUri: /data/user/0/com.example.sampleapp/cache/sample_appFODMM
H/sample_app/lib/main.dart, packagesUri: /data/user/0/com.example.sampleapp/cache/sample_appFODMMH/sample_app/.packages, isolateId: isolates/16321023})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:741)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:998)
#2      Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
<asynchronous suspension>
#3      FlutterDevice.reloadSources (package:flutter_tools/src/resident_runner.dart:139)
#4      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:527)
<asynchronous suspension>
#5      HotRunner.restart (package:flutter_tools/src/run_hot.dart:457)
<asynchronous suspension>
#6      HotRunner.handleTerminalCommand (package:flutter_tools/src/run_hot.dart:236)
<asynchronous suspension>
#7      ResidentRunner.processTerminalInput (package:flutter_tools/src/resident_runner.dart:740)
<asynchronous suspension>
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:480)
#16     _rootRunUnary (dart:async/zone.dart:1134)
#17     _CustomZone.runUnary (dart:async/zone.dart:1031)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#24     _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:298)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#27     _rootRunUnary (dart:async/zone.dart:1134)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#32     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#33     _StreamController._add (dart:async/stream_controller.dart:639)
#34     _StreamController.add (dart:async/stream_controller.dart:585)
#35     _Socket._onData (dart:io-patch/socket_patch.dart:1654)
#36     _rootRunUnary (dart:async/zone.dart:1138)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#41     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#42     _StreamController._add (dart:async/stream_controller.dart:639)
#43     _StreamController.add (dart:async/stream_controller.dart:585)
#44     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1231)
#45     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#48     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

Try again after fixing the above error(s).
```

So when i tried for full restart then similar error appeared.
```
Performing full restart...
Syncing files to device ...
TimeoutException: Request to Dart VM Service timed out: getIsolate({isolateId: isolates/21838813})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:741)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:998)
#2      Isolate._fetchDirect (package:flutter_tools/src/vmservice.dart:981)
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:418)
<asynchronous suspension>
#4      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:383)
<asynchronous suspension>
#5      HotRunner.restart (package:flutter_tools/src/run_hot.dart:439)
<asynchronous suspension>
#6      HotRunner.handleTerminalCommand (package:flutter_tools/src/run_hot.dart:236)
<asynchronous suspension>
#7      ResidentRunner.processTerminalInput (package:flutter_tools/src/resident_runner.dart:740)
<asynchronous suspension>
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:480)
#16     _rootRunUnary (dart:async/zone.dart:1134)
#17     _CustomZone.runUnary (dart:async/zone.dart:1031)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#24     _SimpleAsciiDecoderSink.add (dart:convert/ascii.dart:298)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#27     _rootRunUnary (dart:async/zone.dart:1134)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#32     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#33     _StreamController._add (dart:async/stream_controller.dart:639)
#34     _StreamController.add (dart:async/stream_controller.dart:585)
#35     _Socket._onData (dart:io-patch/socket_patch.dart:1654)
#36     _rootRunUnary (dart:async/zone.dart:1138)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#41     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#42     _StreamController._add (dart:async/stream_controller.dart:639)
#43     _StreamController.add (dart:async/stream_controller.dart:585)
#44     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1231)
#45     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#48     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

Application finished.
```

Note that full restart was performed after `flutter run` when hot reload didn't work in former case.

Similar issue was faced when performing the same operation through Intellij IDE. It got stuck for like 10 minutes and didn't respond and at last I had to stop execution manually.

**Comment by zoechi** [comment]
Exception looks similar to #17980

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by pahwa014** [comment]
I haven't seen this issue in a while. It can be reopened if it appears again.

**Comment by TheScriptan** [comment]
Not sure if I can write here when the issue is closed, but I got into the same situation. Just downloaded Flutter and started testing Hot Reload on Android Studio and it got stuck on "Performing hot reload"

![image](https://user-images.githubusercontent.com/14857616/56092523-75d16d80-5ebd-11e9-90bc-cc0faf35d361.png)

**Comment by gauravmehta13** [comment]
![image](https://user-images.githubusercontent.com/51997260/91680329-7cbb5780-eb68-11ea-8ae9-883bc1f9ef05.png)
Same issue after VS code update

**Comment by ataberkw** [comment]
![image](https://user-images.githubusercontent.com/10375421/98440865-58ea3400-210c-11eb-982c-f8e5a84f639f.png)

It's getting boring

**Comment by LassazVegaz** [comment]
I have the same and I am using latest VS Code, Flutter and Dart ( all of them were updated few weeks ago )

**Comment by houdayec** [comment]
> I have the same and I am using latest VS Code, Flutter and Dart ( all of them were updated few weeks ago )

Did you fix it? I'm getting the same problem.

**Comment by LassazVegaz** [comment]
> Did you fix it? I'm getting the same problem.

Now I don't see the issue. I think it is resolved in the new update...

**Comment by gretzke** [comment]
I have the same issue with VS Code, Intellij works fine
