### ISSUE TITLE
firebase_auth signInWithCustomToken Unhandled exception

### ISSUE THREAD

**Issue by lasseschmitt** [flutter/flutter#15864]
## Steps to Reproduce

Its easy to reproduce. Just try to sign in via token. 
```dart
  FirebaseAuth.instance.signInWithCustomToken(token: "token").then((user) {
            print("logged in ");
   });
```

## Logs

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, dynamic>' where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core

#0      FirebaseAuth.signInWithCustomToken (package:firebase_auth/firebase_auth.dart)
<asynchronous suspension>
#1      LogoWidget.build.<anonymous closure> (package:student/splashScreen.dart:39:33)
<asynchronous suspension>
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recog<…>
Application finished.
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.2.5-pre.29, on Mac OS X 10.13.3 17D102, locale en-DE)
    • Flutter version 0.2.5-pre.29 at /Users/eikebartels/Applications/flutter
    • Framework revision ce28378178 (5 hours ago), 2018-03-23 11:37:56 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985
```

**Comment by zoechi** [comment]
Might be related to #15865

**Comment by cyanglaz** [comment]
Seems related to #15865, can we close this issue and track it there? @lasseschmitt

**Comment by kroikie** [comment]
@lasseschmitt

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/877. Any further collaboration will be done there.
