### ISSUE TITLE
firebase_auth signInWithEmailAndPassword Unhandled exception

### ISSUE THREAD

**Issue by lasseschmitt** [flutter/flutter#15865]
## Steps to Reproduce

Just call 

```dart
FirebaseAuth.instance.signInWithEmailAndPassword(email: credentials.email, password: credentials.password).then((user) {

 });
```

## Logs

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type '(Exception) => Null' is not a subtype of type '(Object) => FutureOr'
#0      _FutureListener.handleError (dart:async/future_impl.dart:145:11)
#1      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645:47)
#2      _Future._propagateToListeners (dart:async/future_impl.dart:666:24)
#3      _Future._completeError (dart:async/future_impl.dart:485:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      FirebaseAuth.signInWithEmailAndPassword (package:firebase_auth/firebase_auth.dart)
<asynchronous suspension>
#7      _ViewModel.fromStore.<anonymous closure> (package:student/uiComponents/login_dialog.dart:177:40)
#8      __DialogState._handleSubmitted (package:student/uiComponents/login_dialog.dart:69:19)
#9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#10     _InkResponseState.build.<anonymo<…>
Application finished.
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.2.5-pre.29, on Mac OS X 10.13.3 17D102, locale en-DE)
    • Flutter version 0.2.5-pre.29 at /Users/eikebartels/Applications/flutter
    • Framework revision ce28378178 (5 hours ago), 2018-03-23 11:37:56 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985
```

**Comment by zoechi** [comment]
What's the version of the plugin you're using (from `pubspec.lock`)`

**Comment by DrivEddy** [comment]
It is without `--preview-dart-2` 

From `pubspec.lock`

```
firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.2"
```

**Comment by jezer07** [comment]
Any update on this?

**Comment by Paul-Todd** [comment]
I tried this and I did'nt see a problem

```
final FirebaseAuth _auth = FirebaseAuth.instance;

Future<MyModel> _signinWithEmail(final String email, final String password) async {
    final firebaseUser = await _auth.signInWithEmailAndPassword(email: email, password: password);

    final m = new MyModel(firebaseUser.uid, firebaseUser.email);

    return m;
}
```

using 

```
  firebase_auth: ^0.5.3
```

Doctor:
```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
```

**Comment by vapolonio** [comment]
same issue

**Comment by cyanglaz** [comment]
@lasseschmitt @vapolonio Is the issue still happening for you if you try using firebase_auth above 0.5.3, suggested by @Paul-Todd ?

**Comment by kroikie** [comment]
@lasseschmitt

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/876. Any further collaboration will be done there.
