### ISSUE TITLE
Can't use the firebase_messaging package with other firebase packages

### ISSUE THREAD

**Issue by dongjason1** [flutter/flutter#15866]
## Steps to Reproduce
I'm having any issue building my app when I use the firebase_messaging package. I can run the example on its own but when I try to add other packages (e.g. firebase_auth) in the pubspec.yaml my build fails. The same is true the otherway around, I can build an example firebase_auth app but I can't include the firebase_messaging package. 

## Logs
Running "flutter packages get" in my_friendlychat...
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Configuration 'compile' in project ':firebase_analytics' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_auth' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_database' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':firebase_storage' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':google_sign_in' is deprecated. Use 'implementation' instead.
Configuration 'compile' in project ':image_picker' is deprecated. Use 'implementation' instead.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbq;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbq;

com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbq;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbq;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Finished with error: Gradle build failed: 1

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] Connected devices (1 available)

**Comment by dongjason1** [comment]
I figured it out. I was using old versions of some of the packages and just needed to change them to the up to date ones. Feeling dumb...
