### ISSUE TITLE
Failed assertion in AOT precompiler

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#15867]
From a [thread on flutter-dev](https://groups.google.com/forum/#!topic/flutter-dev/m15DOpB-zBI) (/cc @hugovangalen):

I'm using the master branch (it contains a fix for slow startups on Android with lots of assets), and recently I am running into the following error while building:

```
[+14098 ms] ../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 2789: error: unreachable code 
[        ] Dart snapshot generator failed with exit code -6 
[   +1 ms] ../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 2789: error: unreachable code 
[  +18 ms] "flutter aot" took 30,505ms.
```

I wonder how I can figure out what is causing this exact issue (other than to dissect the project and slowly piece things together again).

Thanks in advance for any hints.

BTW, peaking inside the called `gen_snapshot` binary hinted there is a `--verbose_debug` switch. Not sure how that is supposed to be used, but I ran it with that and then it core dumped:

```
$ /path/to/gen_snapshot --verbose_debug --await_is_keyword --
vm_snapshot_data=build/aot/vm_snapshot_data --isolate_snapshot_data=build/aot/isolate_snapshot_data --packages=.packages --url_mapping=dart:ui,/data/development/git/flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart --url_mapping=dart:vmservice_io,/data/development/git/flutter/bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --print_snapshot_sizes --dependencies=build/aot/snapshot.d --causal_async_stacks --embedder_entry_points_manifest=/data/development/git/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points.txt --embedder_entry_points_manifest=/data/development/git/flutter/bin/cache/artifacts/engine/android-arm-release/dart_io_entries.txt --snapshot_kind=app-aot-blobs --vm_snapshot_instructions=build/aot/vm_snapshot_instr --isolate_snapshot_instructions=build/aot/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division --reify-generic-functions --strong build/app.dill  
../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 2789: error: unreachable code 
Aborted (core dumped)
```

FWIW:
```
#0  0xf76e4be9 in __kernel_vsyscall () 
#1  0xf730dea9 in raise () from /lib/i386-linux-gnu/libc.so.6 
#2  0xf730f407 in abort () from /lib/i386-linux-gnu/libc.so.6 
#3  0x004cec5b in ?? () 
#4  0x0073e61d in ?? () 
#5  0x005c384d in ?? () 
#6  0x005c6633 in ?? () 
#7  0x005bf8cc in ?? () 
#8  0x005b9077 in ?? () 
#9  0x005b68a5 in ?? () 
#10 0x005b66d7 in ?? () 
#11 0x00729df6 in ?? () 
#12 0x003411a0 in ?? () 
#13 0x0033fad6 in ?? () 
#14 0x003415c4 in ?? () 
#15 0xf72fa637 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6 
#16 0x0033c021 in ?? ()
```

**Comment by alexmarkov** [comment]
Unfortunately, we haven't got any reproduction from user. I don't think we can investigate this issue without reproducing it.
