### ISSUE TITLE
[flutter_svg] Issues

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158783]
_Imported from https://github.com/dnfield/flutter_svg/issues/1004_

Original report by @krll-kov on Oct 19, 2023

```Dart
[2023-10-19 14:39:22] [DART] [Build: 3.2.31.0] XmlParserException: ">" expected at 2:8; 
#0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:42)
#1      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:673)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554)
#3      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:764)
#4      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:799)
#5      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76)
#6      encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:143)
#7      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:137)
#8      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#9      _RemoteRunner._run (dart:isolate:1021)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

```Dart
[2023-10-19 14:18:24] [DART] [Build: 3.2.31.0] Bad state: No element; 
#0      ListQueue.last (dart:collection/queue.dart:690)
#1      SvgParser.endElement (package:vector_graphics_compiler/src/svg/parser.dart:925)
#2      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:782)
#3      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:799)
#4      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76)
#5      encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:143)
#6      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:137)
#7      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#8      _RemoteRunner._run (dart:isolate:1021)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

```Dart
[2023-10-18 13:23:20] [DART] [Build: 3.2.31.0] XmlParserException: name expected at 3:50; 
#0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:42)
#1      SvgParser._readSubtree (package:vector_graphics_compiler/src/svg/parser.dart:673)
#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554)
#3      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:764)
#4      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:799)
#5      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:76)
#6      encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:143)
#7      SvgLoader._load.<anonymous closure>.<anonymous closure> (package:flutter_svg/src/loaders.dart:137)
#8      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#9      _RemoteRunner._run (dart:isolate:1021)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

Hi, in my errors logs that are automatically collected by clients and are sent to server i see a lot of this error:
![image](https://github.com/dnfield/flutter_svg/assets/63228361/6e525e7e-d77b-4045-90f3-a737486a4526)

I, myself, do not face this issue so i have no idea how to reproduce this issue, maybe these logs will help to fix these errors

---
Comment by @dnfield on Oct 19, 2023
It sounds like you're dealing with some SVG that isn't valid XML. Perhaps due to a network error?

---
Comment by @krll-kov on Oct 20, 2023
> It sounds like you're dealing with some SVG that isn't valid XML. Perhaps due to a network error?

All SVG are stored in assets and precompiled with the app

---
Comment by @dnfield on Oct 20, 2023
The error indicates that an attempt was made to parse something as XML that isn't XML.

---
Comment by @krll-kov on Oct 20, 2023
> The error indicates that an attempt was made to parse something as XML that isn't XML.

But I do not face this issue myself

---
Comment by @krll-kov on Oct 26, 2023
Is there something like errorBuilder or a callback to verify that svg is valid upon layout?

---
Comment by @krll-kov on Jan 25, 2024
@dnfield i tried everything, checked svgs with such methods to replace them with placeholder with 100% working svg, added assets integrity verification, but issues are still sent to my server, maybe there's just some problem on some windows versions? How do i completely disable this logs? 
![image](https://github.com/dnfield/flutter_svg/assets/63228361/742d2554-83ba-471b-b613-3fcea6afe2fb)

**Comment by jonahwilliams** [comment]
You'd need to provde a minimal repro for us to be able to fix anything here.
