### ISSUE TITLE
[vector_graphics] build: Occasionaly fails to rename vector file after transforming during build

### ISSUE THREAD

**Issue by stuartmorgan-g** [flutter/flutter#158870]
_Imported from https://github.com/dnfield/vector_graphics/issues/252_

Original report by @ZiyadF296 on Aug 8, 2024

When building an app, while transforming assets, the following error gets dumped (built with verbose):

<details>
<summary>Error dump</summary>
[  +19 ms] Target web_release_bundle failed: Error: User-defined transformation of asset
           "C:\Users\username\div\My_Cool_Flutter_App\flutter_app\assets\Icons\heart_border.svg" failed.
           Transformer process terminated with non-zero exit code: 255
           Transformer package: vector_graphics_compiler
           Full command: C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler
           --input=C:\Users\username\AppData\Local\Temp\flutter_tools.9e394f6\heart_border.svg-transformOutput0.svg
           --output=C:\Users\username\AppData\Local\Temp\flutter_tools.9e394f6\heart_border.svg-transformOutput1.svg
           stdout:

           stderr:
           Cannot rename file to

'C:\Users\username\div\My_Cool_Flutter_App\flutter_app\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compiler.dart-3.4.4.sn
           apshot', path =

'C:\Users\username\div\My_Cool_Flutter_App\flutter_app\.dart_tool/pub\bin\vector_graphics_compiler\tmpb6899b1\vector_graphics_compiler.da
           rt-3.4.4.snapshot.incremental.temp' (OS Error: Access is denied.
           , errno = 5)
           PathAccessException: Cannot rename file to

'C:\Users\username\div\My_Cool_Flutter_App\flutter_app\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compiler.dart-3.4.4.sn
           apshot', path =

'C:\Users\username\div\My_Cool_Flutter_App\flutter_app\.dart_tool/pub\bin\vector_graphics_compiler\tmpb6899b1\vector_graphics_compiler.da
           rt-3.4.4.snapshot.incremental.temp' (OS Error: Access is denied.
           , errno = 5)

           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:154:19)
           <asynchronous suspension>
           #2      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
           <asynchronous suspension>
           #3      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:126:3)
           <asynchronous suspension>
           #4      WebReleaseBundle.build (package:flutter_tools/src/build_system/targets/web.dart:450:29)
           <asynchronous suspension>
           #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
           <asynchronous suspension>
           #6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
           <asynchronous suspension>
           #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
           <asynchronous suspension>
           #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
           <asynchronous suspension>
           #9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
           <asynchronous suspension>
           #10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
           <asynchronous suspension>
           #11     FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #14     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

[  +10 ms] Compiling lib\main.dart for the Web... (completed in 118.8s)
[   +1 ms] "flutter web" took 123,432ms.
[  +41 ms] Error: Failed to compile application for the Web.
</details>

Also, please note this is not a persistent error. Subsequently building the app WITHOUT any changes resolves it and the OS no longer throws a permission denied error when build tool tries to rename the vector file. It's a 50/50 chance of a build succeeding.

**Comment by tguerin** [comment]
I encountered this issue because I had multiple SVG files with the same name located in different directories. It appears the transformer does not consider the file's directory, which can lead to naming conflicts. Since the process is asynchronous, these conflicts may occur inconsistently.

**Comment by corepuncher** [comment]
This is a critical issue for me, can someone please take a look?  I did a test here below, which will hopefully lead you to deduce the answer.

--------------------
1) In pubspec.yaml, only tried transform on a single dir with 31 svgs, each 200 to 500 bytes in size.

```
    - path: assets/xyz/
      transformers:
        - package: vector_graphics_compiler
```

(flutter run)

FAILED

--------------------
2) Made new dir /test with 1 svg item in it.

```
    - path: assets/test/
      transformers:
        - package: vector_graphics_compiler
```

SUCCESS

--------------------
3) Copied the 31 svg's from /xyz into the /test dir

FAILED

--------------------
4) Went back and tried the single svg item again

SUCCESS

--------------------
5) This time tried with 2 svg's in /test dir

SUCCESS

--------------------
6) Tried with 15 svg's in /test dir

FAILED

It transformed 11 items: 

```
[+1999 ms] [+2082 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item30.svg' (2406ms)
[  +94 ms] [  +33 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item45.svg' (2437ms)
[        ] [  +18 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item65.svg' (2454ms)
[        ] [  +23 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item40.svg' (2481ms)
[        ] [   +6 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item50.svg' (2483ms)
[        ] [   +1 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item20.svg' (2491ms)
[  +93 ms] [  +36 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item55.svg' (2523ms)
[        ] [   +2 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item10.svg' (2534ms)
[        ] [   +3 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item60.svg' (2529ms)
[        ] [   +1 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item35.svg' (2533ms)
[        ] [  +12 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item15.svg' (2548ms)

Stuck for several minutes (CPU loud), then

[+341702 ms] [+341688 ms] Persisting file store
[   +2 ms] [  +18 ms] Done persisting file store
[   +2 ms] [  +11 ms] Target debug_android_application failed: Error: User-defined transformation of asset 
"C:\Users\me\projectname\dev-projectname\assets\test\item70.svg" failed.
[   +3 ms]            Transformer process terminated with non-zero exit code: 255
[        ]            Transformer package: vector_graphics_compiler
[        ]            Full command: C:\Flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler
--input=C:\Users\me\AppData\Local\Temp\flutter_tools.6ccc28c2\item70.svg-transformOutput0.svg
--output=C:\Users\me\AppData\Local\Temp\flutter_tools.6ccc28c2\item70.svg-transformOutput1.svg
[        ]            stdout:
[        ]            stderr:
[        ]            Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmp449ac982\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            PathAccessException: Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmp449ac982\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      copyAssets.<anonymous closure>
...dart errors
```


--------------------
7) This time I limited it to 10 svg's, and ensured I included item70.svg

FAILED

It transformed 9 of the items, INCLUDING item70.svg.  This time, it "failed" at item 65.svg with same errors as above.

--------------------
8) This time, tried 5 svg's

SUCCESS

And that includes item65.svg and item70.svg

--------------------
9) Tried 8 svg's

FAILED

As always, it stops on a random SVG, so I do not think the file is the issue.

This time it processed 7 out of 8 and died:

```
[+1194 ms] [+1266 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item20.svg' (1487ms)
[        ] [  +10 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item15.svg' (1493ms)
[        ] [        ] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item35.svg' (1492ms)
[  +91 ms] [  +21 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item65.svg' (1513ms)
[        ] [  +20 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item70.svg' (1533ms)
[        ] [        ] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item25.svg' (1536ms)
[        ] [   +3 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item5.svg' (1538ms)
[        ] [   +2 ms] Persisting file store
[        ] [  +18 ms] Done persisting file store
[        ] [  +11 ms] Target debug_android_application failed: Error: User-defined transformation of asset 
"C:\Users\me\projectname\dev-projectname\assets\test\item40.svg" failed.
[   +1 ms]            Transformer process terminated with non-zero exit code: 255
[        ]            Transformer package: vector_graphics_compiler
[        ]            Full command: C:\Flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler
--input=C:\Users\me\AppData\Local\Temp\flutter_tools.d2ba8b6f\item40.svg-transformOutput0.svg
--output=C:\Users\me\AppData\Local\Temp\flutter_tools.d2ba8b6f\item40.svg-transformOutput1.svg
[        ]            stdout:
[        ]            stderr:
[        ]            Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmpd270e2c4\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            PathAccessException: Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmpd270e2c4\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      copyAssets.<anonymous closure>
(package:flutter_tools/src/build_system/targets/assets.dart:157:19)
```

--------------------
10) Tried 7 items

FAILED

This time, it only finished 5 items out of 7.  

It is telling that the "finished" item count for a list of items (say 9 finished out of 10) can be HIGHER than the TOTAL number of items when it fails (for example, finished only 5 out of 7). 

Here is another clue:  When I include ALL my dirs and items, about 200 items, it processes MOST of them, then eventually fails. 

--------------------
11) Let's try 6 items:

FAILED

Processed 5 out of 6

--------------------
12) NOW, back to 5 items, which worked in the past

SUCCESS!

--------------------
13) As a final test, instead of processing a dir like /test in pubspec.yaml, I explicitly entered 12 separate files like:

```
    - path: assets/test/item10.svg
      transformers:
        - package: vector_graphics_compiler
```
        
FAILED

--------------------
So from my testing, > 5 items always fails.

**Comment by davidsturm96** [comment]
Any news on this problem?

We are facing it as well! 

For one folder with 5 files, it (mostly) works, but having folders with more files, the process fails randomly.

**Comment by gajendrapandeya** [comment]
For me i was getting this issue with the vector_graphics_compiler

"/Users/gazzu/Development/nobullcode/flutter_hub_design_system/assets/folder_icons/.DS_Store" failed.
Transformer process terminated with non-zero exit code: 1
Transformer package: vector_graphics_compiler

When I ran `rm assets/folder_icons/.DS_Store` and ran the project, it worked.

**Comment by darshankawar** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/158869.

**Comment by corepuncher** [comment]
> Closing this in favor of [#158869](https://github.com/flutter/flutter/issues/158869).

But #158869 only has to do with non-svg files being in the directory. Only the last comment from @gajendrapandeya above is related to that issue. The rest of the thread is a different issue.

The primary issue from @davidsturm96  and my self happens when > 5 svg's in a dir.  
Can you please try with 20 svg files in a dir, on a Windows machine?  Not sure if @davidsturm96 was also using Windows or not.

**Comment by davidsturm96** [comment]
@darshankawar  I agree with @corepuncher, the problems are unrelated in my opinion. This one happened, like he said, only to folders with many svg's. Also on windows for me
