### ISSUE TITLE
[vector_graphics] isn't run for flutter web

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158866]
_Imported from https://github.com/dnfield/vector_graphics/issues/241_

Original report by @JgomesAT on May 24, 2024

When I try to run my code with vector graphics compiler in Flutter Web, the command always finishes with Exit and don't run the code

---
Comment by @alod2019 on May 25, 2024
I can confirm. In my case the assets section of pubspec.yaml has vector_graphics_compiler appied to folders rather than separte files. On MacOS  web build just crashes with 
```
Compiling lib/main.dart for the Web...                          
Target web_release_bundle failed: ProcessException: Too many open files
  Command: /Users/admin/flutter-3.22.1/bin/cache/dart-sdk/bin/dart run vector_graphics_compiler --input=/var/folders/6h/rfdkq1md3v79423cgp0_kpbh0000gn/T/flutter_tools.tfmC7z/ic_calendar.svg-transformOutput0.svg --output=/var/folders/6h/rfdkq1md3v79423cgp0_kpbh0000gn/T/flutter_tools.tfmC7z/ic_calendar.svg-transformOutput1.svg
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:72:22)
#5      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:661:24)
#6      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#7      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:660:12)
#8      AssetTransformer._applyTransformer (package:flutter_tools/src/build_system/tools/asset_transformer.dart:115:56)
#9      AssetTransformer.transformAsset (package:flutter_tools/src/build_system/tools/asset_transformer.dart:64:70)
<asynchronous suspension>
```
on Windows the picture is better and some of SVG files are transformed but finally build also fails with a file error

---
Comment by @willhlas on May 28, 2024
I had this issue too but just needed to update my flutter version to `3.22.1`! Maybe try this?

---
Comment by @alod2019 on May 29, 2024
my crashlog above shows that it happens with flutter 3.22.1

**Comment by darshankawar** [comment]
I ran the vector_graphics plugin [example](https://github.com/flutter/packages/tree/main/packages/vector_graphics/example) on web using latest stable version and it compiled and ran properly without throwing the said error or any issues:

<img width="1385" height="746" alt="Image" src="https://github.com/user-attachments/assets/a4197803-d7e6-42a9-915e-d8f17211344f" />

Closing, as originally reported issue doesn't occur anymore. If that is still the case using latest plugin version, please file new issue with relevant details.
