### ISSUE TITLE
[flutter_svg] Bad state: SVG did not specify dimensions 

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158801]
_Imported from https://github.com/dnfield/flutter_svg/issues/1043_

Original report by @higaski on Feb 25, 2024

I keep getting `Bad state: SVG did not specify dimensions` errors when using the SVG attached here and I can't wrap my head around why? The SVG clearly contains all the 3 attributes the error message is complaining about?

This is the error in detail
```sh
Bad state: SVG did not specify dimensions

The SVG library looks for a `viewBox` or `width` and `height` attribute to determine the viewport boundary of the SVG.  Note that these attributes, as with all SVG attributes, are case sensitive.
```

And this is the beginning of the SVG data
```xml
<svg
   width="271.099mm"
   height="155.14697mm"
   viewBox="0 0 271.099 155.14699"
   version="1.1"
   ...
```

![logo_bricks](https://github.com/dnfield/flutter_svg/assets/13762516/91d665eb-1bc2-4789-9594-f355a656a512)

---
Comment by @LucaCoduriV on Mar 3, 2024
same for me

---
Comment by @rajrushilmakkar on Mar 7, 2024
facing the same issue with this svg
![Social-Emotional-Learning](https://github.com/dnfield/flutter_svg/assets/56961633/1dbd9019-934a-44ab-90bb-1e5872baf27a)

---
Comment by @dnfield on Mar 7, 2024
> facing the same issue with this svg

viewBox is case sensitive. Maybe I should lighten this up though since browsers seem to.

---
Comment by @dnfield on Mar 7, 2024
@higaski your example has a couple pattern elements in it that are using not well supported features for this package, and also includes JavaScript which will never work with this package.

It _is_ a bug that we're requiring a `viewBox` on a `pattern` that has no `width` or `height`, but fixing that won't fix your SVG unfortunately.

---
Comment by @rajrushilmakkar on Mar 7, 2024
 > viewBox is case sensitive.
 
Hi, thanks, changing to viewBox did fix my issue

>  Maybe I should lighten this up though since browsers seem to.

I think that would be nice. Happy to create a PR @dnfield

**Comment by darshankawar** [comment]
Replicable with latest stable and plugin version:

```
Syncing files to device iPhone 16 Pro Max...
flutter: unhandled element <sodipodi:namedview/>; Picture key: Svg loader
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Bad state: SVG did not specify dimensions

The SVG library looks for a `viewBox` or `width` and `height` attribute to determine the viewport boundary of the SVG.  Note that these attributes, as with all SVG attributes, are case sensitive.
During processing, the following attributes were found:
  {collect: always, href: #Bricks, id: pattern83, patternTransform: scale(0.25), x: 0, y: 0, preserveAspectRatio: none}
#0      SvgParser._parseViewBox (package:vector_graphics_compiler/src/svg/parser.dart:1122:7)
#1      _Elements.pattern (package:vector_graphics_compiler/src/svg/parser.dart:166:45)
#2      SvgParser._parseTree (package:vector_graphics_compiler/src/svg/parser.dart:785:20)
#3      SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:805:5)
#4      parse (package:vector_graphics_compiler/vector_graphics_compiler.dart:78:17)
#5      encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:145<…>
```
