### ISSUE TITLE
[vector_graphics] IMPROVEMENT: add an arg to skip non svg files

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#158869]
_Imported from https://github.com/dnfield/vector_graphics/issues/250_

Original report by @alefwd on Jul 30, 2024

I have a folder /assets where I have a mix of svgs and json files, and I cannot change this. I would like to be able to apply the vector_graphics_compiler transformation to the folder.
When I tried something like:
```
    - path: assets/
      transformers:
        - package: vector_graphics_compiler
```
I received exceptions relative to transforming the json files.

What I propose is either to skip non svg files by default, or to enable it using an arg:
```
    - path: assets/
      transformers:
        - package: vector_graphics_compiler
           args: ['--svg-only']
```

---
Comment by @t-unit on Aug 9, 2024
I also run into this sometimes with files generated by the OS, very annoying. E.g. for `.DS_Store`:

```
Target debug_android_application failed: Error: User-defined transformation of asset "/Users/***/assets/vector/.DS_Store" failed.
Transformer process terminated with non-zero exit code: 1
Transformer package: vector_graphics_compiler
Full command: /Users/***/flutter/bin/cache/dart-sdk/bin/dart run vector_graphics_compiler --input=/var/folders/5l/cwy_qpwn32bf5r7qcnz2ns740000gn/T/flutter_tools.1xhZrW/.DS_Store-transformOutput0 --output=/var/folders/5l/cwy_qpwn32bf5r7qcnz2ns740000gn/T/flutter_tools.1xhZrW/.DS_Store-transformOutput1
stdout:
XXXXXXXXXXX /var/folders/5l/cwy_qpwn32bf5r7qcnz2ns740000gn/T/flutter_tools.1xhZrW/.DS_Store-transformOutput0 XXXXXXXXXXXXX
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/var/folders/5l/cwy_qpwn32bf5r7qcnz2ns740000gn/T/flutter_tools.1xhZrW/.DS_Store-transformOutput0'
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      IsolateProcessor._process.<anonymous closure> (file:///Users/***/.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/bin/util/isolate_processor.dart:110:37)
isolate_processor.dart:110
#3      _RemoteRunner._run (dart:isolate:1090:47)
#4      _RemoteRunner._remoteExecute (dart:isolate:1084:12)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by divyanshub024** [comment]
I'm getting the same error 
```
Error (Xcode): Target debug_ios_bundle_flutter_assets failed: Error: User-defined transformation of asset "/Users/***/StudioProjects/***/assets/svg/.DS_Store" failed.
```

**Comment by darshankawar** [comment]
I was able to replicate this with latest stable version and with below setup:

<img width="406" height="138" alt="Image" src="https://github.com/user-attachments/assets/244fba70-e209-42ae-bc51-e3decff98128" />

And upon trying to run the app on all platforms, below error is thrown:

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Finished with error: User-defined transformation of asset "assets/image.png" failed.
Transformer process terminated with non-zero exit code: 1
Transformer package: vector_graphics_compiler
Full command: /Users/dhs/Documents/Fluttersdk/flutter/bin/cache/dart-sdk/bin/dart run vector_graphics_compiler --input=/var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.oTDnHR/YwYtRx/image.png-transformOutput0.png --output=/var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.oTDnHR/YwYtRx/image.png-transformOutput1.png
stdout:
XXXXXXXXXXX /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.oTDnHR/YwYtRx/image.png-transformOutput0.png XXXXXXXXXXXXX
FileSystemException: Failed to decode data using encoding 'utf-8', path = '/var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/flutter_tools.oTDnHR/YwYtRx/image.png-transformOutput0.png'
#0      _File._tryDecode (dart:io/file_impl.dart:707:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:718:7)
#2      IsolateProcessor._process.<anonymous closure> (file:///Users/dhs/.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.17/bin/util/isolate_processor.dart:112:37)
#3      _RemoteRunner._run (dart:isolate:1116:47)
#4      _RemoteRunner._remoteExecute (dart:isolate:1110:12)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:317:17)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)

Some targets failed.

stderr:
```
https://docs.flutter.dev/ui/assets/asset-transformation#specifying-asset-transformations


Maybe the tool team can look into this for their thoughts on the reported behavior.

/cc @bkonyi

**Comment by darshankawar** [comment]
If I add an svg file instead of png, then the error doesn't occur.

**Comment by bkonyi** [comment]
SVG's are UTF-8 decodable XML files, whereas PNGs are binary data, so it makes sense that we're throwing an exception here when we try to decode it.

I don't think there's anything we can do about this in the tool since it's a user defined transformation implemented in `package:vector_graphics`. It should be verifying that the files it's trying to transform are UTF-8 decodable and properly formatted SVG files, otherwise it should be ignoring them.

**Comment by chinmaygarde** [comment]
This isn't an engine issue as this is a user transformation in a package.

**Comment by corepuncher** [comment]
@darshankawar 

#158870 was closed as a duplicate in favor of this issue.  However, it is not the same issue.  Please read last couple comments on #158870 and consider keeping open, thanks.

**Comment by adigladi** [comment]
Running in to this issue a lot and the `.DS_Store` files on mac is making it very hard to run the transformer on a asset directory since they get created all the time.

**Comment by qeepcologne** [comment]
yeah really sucks, i got lots of build errors, 
Error: unable to find directory entry in pubspec.yaml:  ...
(This is because these files arent' there for flavors, we don't currenly build).
then i tried to add .gitkeep, but this causing the transformer here to fail with the error above.
So i have to add file like .__keep_folder.svg
```<svg xmlns="http://www.w3.org/2000/svg" width="1mm" height="1mm" viewBox="0 0 1 1"/>```

So at least i expect:
- ignore folder for other flavors (if i build flavor a, 
```
    - path: assets/flavorb/
      flavors:
      - b
      transformers:
        - package: vector_graphics_compiler
```
should be completely ignore and should not produce any warnings or errors

- ignore at leat .gitignore to allow addings empty folders (or all files starting with . and without extension)
