### ISSUE TITLE
[camera_android] Crash CameraDevice was already closed `unlockAutoFocus` > `checkIfCameraClosedOrInError`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#158878]
Seeing this in packages CI as Firebase flakes:

```
java.lang.IllegalStateException: CameraDevice was already closed
     FATAL EXCEPTION: CameraBackground
Process: io.flutter.plugins.cameraexample, PID: 23790
java.lang.IllegalStateException: CameraDevice was already closed
	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2445)
	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1237)
	at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:1099)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:189)
	at io.flutter.plugins.camera.Camera.unlockAutoFocus(Camera.java:807)
	at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:719)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$4$android-hardware-camera2-impl-CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:708)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```
See link from https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8731360356815402769/+/u/Run_package_tests/Firebase_Test_Lab/stdout

I see this mentioned in comment  https://github.com/flutter/flutter/issues/92762#issuecomment-1408013677 but I _think_ that issue is tracking something different.

**Comment by IbrokhimMirzaev** [comment]
Any Updates ?
