### ISSUE TITLE
Error on flutter run

### ISSUE THREAD

**Issue by CrazyStaff** [flutter/flutter#15892]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next

```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      defaultRecoveryStrategy (package:front_end/src/fasta/scanner/recover.dart:158)
#2      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:93)
#3      scanString (package:front_end/src/fasta/scanner.dart:84)
#4      _Scanner2.tokenize (package:analyzer/src/dart/scanner/scanner.dart:169)
#5      parseDirectives (package:analyzer/analyzer.dart:90)
#6      DartDependencySetBuilder._parse (package:flutter_tools/src/dart/dependencies.dart:121)
#7      DartDependencySetBuilder.build (package:flutter_tools/src/dart/dependencies.dart:46)
#8      HotRunner._refreshDartDependencies (package:flutter_tools/src/run_hot.dart:85)
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:208)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:345)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#28     main (file:///C:/Users/Johan/Desktop/Programmieren/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale de-DE)
    • Flutter version 0.1.5 at C:\Users\Johan\Desktop\Programmieren\Flutter\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Johan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • HTC U11 • FA78N1802029 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
try `flutter channel dev` `flutter doctor`

**Comment by zoechi** [comment]
Closing due to inactivity.
