### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by baj9032** [flutter/flutter#15897]
## Steps to Reproduce

When I run below command its give me exception.

## command

flutter run --verbose

## exception

String: Exit code 1 from: D:\Desktop\GitRepo\flutterdemo\android\gradlew.bat -v:
Error: Could not find or load main class org.gradle.launcher.GradleMain

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:242)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:177)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:159)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:94)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:86)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:270)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:262)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:345)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#28     main (file:///D:/Desktop/GitRepo/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 0.1.5 at D:\Desktop\GitRepo\flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\baj9032\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.10.0

[✓] Connected devices (1 available)
    • Moto G 4 • ZY223DPBX9 • android-arm • Android 7.0 (API 24)

**Comment by amangautam1** [comment]
getting the same issue when running app

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                   \CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 8cf10479232cb890)
Crash report written to C:\Users\Aman gautam\Documents\FlutterProjects\hello_workd\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by Hixie** [comment]
@baj9032 Do you still see this? We don't really have enough information here to address the problem. If you still see this can you attach a sample application showing the problem?
