### ISSUE TITLE
[webview_flutter] PlatformException(recreating_view, trying to create an already created view, view id: '0', null) on macOS while hot reloading

### ISSUE THREAD

**Issue by sma** [flutter/flutter#158977]
### Steps to reproduce

On macOS the flutter engine throws an exception when trying to hot reload code which makes it nearly impossible to work with the webview widget.

### Expected results

It should work like on iOS.

### Actual results

```
Restarted application in 259ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '0', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:646:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PlatformViewsService.initAppKitView (package:flutter/src/services/platform_views.dart:294:5)
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:927:36)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final controller = WebViewController();

  @override
  void initState() {
    super.initState();
    controller.loadRequest(Uri.parse('https://heise.de'));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(body: WebViewWidget(controller: controller)));
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.27.0-1.0.pre.511, on macOS 15.1 24B83 darwin-arm64, locale
    de-DE)
    • Flutter version 3.27.0-1.0.pre.511 on channel main at /Users/sma/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eaa99f28b1 (9 hours ago), 2024-11-14 17:38:26 -0800
    • Engine revision 619804c0fb
    • Dart version 3.7.0 (build 3.7.0-140.0.dev)
    • DevTools version 2.41.0-dev.2

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS
      15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS
      15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google
      Chrome 131.0.6778.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by sma** [comment]
I forgot to mention the webview version:
```
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
```
