### ISSUE TITLE
Flutter doctor failed

### ISSUE THREAD

**Issue by f1010** [flutter/flutter#15899]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `2.0.0-dev.16.0`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 3840x2160`

# Exception

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Found element with null library: ButtonTextTheme
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:805)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:286)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2310)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:5370)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2310)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8050)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2233)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5986)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4570)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2943)
#11     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:5360)
#12     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2229)
#13     AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:162)
#14     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4371)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5986)
#16     PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4570)
#17     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011)
#18     ResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:5604)
#19     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:4565)
#20     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4367)
#21     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8050)
#22     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:7083)
#23     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7060)
#24     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5321)
#25     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#26     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5387)
#27     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#28     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:696)
#29     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:125)
#30     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#31     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:124)
#32     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:99)
<asynchronous suspension>
#33     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:217)
<asynchronous suspension>
#34     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:95)
<asynchronous suspension>
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1216)
<asynchronous suspension>
#36     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:879)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:386)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:436)
#45     _rootRun (dart:async/zone.dart:1126)
#46     _CustomZone.run (dart:async/zone.dart:1023)
#47     runZoned (dart:async/zone.dart:1501)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:476)
#49     Driver.start (package:analysis_server/src/server/driver.dart:435)
#50     main (file:///E:/b/build/slave/dart-sdk-windows-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

```
1521884267677 <= {"event":"analysis.errors","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\workspace
1521884267771 <= {"event":"analysis.errors","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\wallet.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\workspa
1521884267987 <= {"event":"analysis.errors","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\test\\widget_test.dart","errors":[]}}
1521884267988 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521884276852 => {"id":"401","method":"edit.getAssists","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","offset":4476,"length":0},"clientRequestTime":1521884276852}
1521884276879 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521884276964 <= {"event":"analysis.errors","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"D:\\worksp
1521884276965 <= {"id":"401","result":{"assists":[{"message":"Split variable declaration","edits":[{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","fileStamp":0,"edits":[{"of
1521884276966 <= {"event":"analysis.highlights","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT
1521884276969 <= {"event":"analysis.navigation","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"lengt
1521884276969 <= {"event":"analysis.closingLabels","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","labels":[{"offset":2696,"length":556,"label":"Row"},{"offset":272
1521884276971 <= {"event":"analysis.outline","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":
1521884276971 <= {"event":"analysis.overrides","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","overrides":[{"offset":517,"length":11,"superclassMember":{"element":{
1521884276972 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1521884276972 <= {"event":"analysis.implemented","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","classes":[],"members":[]}}
1521884277977 => {"id":"402","method":"edit.getAssists","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","offset":4586,"length":0},"clientRequestTime":1521884277977}
1521884277981 <= {"id":"402","result":{"assists":[{"message":"Wrap with new widget","edits":[{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","fileStamp":0,"edits":[{"offset":
1521884278420 => {"id":"403","method":"edit.getAssists","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","offset":4584,"length":4},"clientRequestTime":1521884278420}
1521884278426 <= {"id":"403","result":{"assists":[{"message":"Wrap with new widget","edits":[{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","fileStamp":0,"edits":[{"offset":
1521884286428 => {"id":"404","method":"edit.getAssists","params":{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","offset":4516,"length":0},"clientRequestTime":1521884286428}
1521884286435 <= {"id":"404","result":{"assists":[{"message":"Wrap with new widget","edits":[{"file":"D:\\workspaces\\dart_workspace\\Light\\Light\\lib\\payment.dart","fileStamp":0,"edits":[{"offset":
1521884286725 => {"id":"405","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286728 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1521884286733 => {"id":"406","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286740 => {"id":"407","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286747 => {"id":"408","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286755 => {"id":"409","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286763 => {"id":"410","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286772 => {"id":"411","method":"analysis.getHover","params":{"file":"C:\\Users\\krupa\\flutter\\packages\\flutter\\lib\\src\\material\\raised_button.dart","offset":3088},"clientRequestTime":152
1521884286777 <= {"event":"server.error","params":{"isFatal":false,"message":"Found element with null library: ButtonTextTheme","stackTrace":"null exception\n#0      AnalysisServer.sendServerErrorNoti
```

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Found element with null library: ButtonTextTheme
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:805)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:286)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2310)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:5370)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2310)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8050)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2233)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5986)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4570)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2943)
#11     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:5360)
#12     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2229)
#13     AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:162)
#14     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4371)

**Comment by zoechi** [comment]
Looks like you're running a quite outdated Flutter version.
Try `flutter upgrade` `flutter doctor`
The version you have caused issues with `flutter upgrade` for many. It might be better to just purge it and start over with a fresh install.
You can also try in the `flutter` install directory `flutter pull` `git reset --hard` `flutter channel dev` `flutter doctor`

**Comment by Hixie** [comment]
cc @devoncarew
