### ISSUE TITLE
vector_graphics_compiler - Fails To Compile (windows env): (OS Error: Access is denied. , errno = 5) 

### ISSUE THREAD

**Issue by corepuncher** [flutter/flutter#159058]
### What package does this bug report belong to?

vector_graphics

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1) I have several directories of svg files.
2) I attempt to apply transformers on them using vector_graphics_compiler in pubspec.yaml.
3) The builds always fail on seemingly random filenames and same error.

### Expected results

It should compile.  

### Actual results

It does not compile, despite checking permissions of the dirs, deleting them, reinstalling, etc etc.

### Code sample

<details open><summary>Code sample</summary>

```dart
Here is my pubspec.yaml:

flutter:
  assets:
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/obs/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/obs/symbols/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/obs/dark/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/obs/cy/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/abc/
      transformers:
        - package: vector_graphics_compiler
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Here is an example of the error:

Target debug_android_application failed: Error: User-defined transformation of asset "C:\project\assets\icons\gpsToggle.svg" failed.
Transformer process terminated with non-zero exit code: 255
Transformer package: vector_graphics_compiler
Full command: C:\Flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler --input=C:\username\AppData\Local\Temp\flutter_tools.7a6f9885\gpsToggle.svg-transformOutput0.svg --output=C:\username\AppData\Local\Temp\flutter_tools.7a6f9885\gpsToggle.svg-transformOutput1.svg
stdout:

stderr:
Cannot rename file to 'C:\project\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compiler.dart-3.5.3.snapshot', path = 'C:\project\.dart_tool/pub\bin\vector_graphics_compiler\tmp588a24b2\vector_graphics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
, errno = 5)
PathAccessException: Cannot rename file to 'C:\project\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compiler.dart-3.5.3.snapshot', path = 'C:\project\.dart_tool/pub\bin\vector_graphics_compiler\tmp588a24b2\vector_graphics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
, errno = 5)
```

</details>

I don't know if the alternating slash directions are an issue. For example, see above the "\.dart_tool/pub\bin"

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22....], locale
    en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.95.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!```

</details>

**Comment by darshankawar** [comment]
@corepuncher 
Looks like it is similar to https://github.com/flutter/flutter/issues/158869. 

> ```dart
> Here is my pubspec.yaml:
> ```

Does it have any non-svg files ? Can you try to narrow it down to minimal reproducible pattern or code that triggers the reported error log ?

**Comment by corepuncher** [comment]
Regarding your previous question, no non-svg files. I had pngs before, and it failed with an obvious error, so I moved them.

BUT here is my revealing test !

- Windows 11 env
- flutter run --verbose

--------------------
1) In pubspec.yaml, only tried transform on a single dir with 31 svgs, each 200 to 500 bytes in size.

    - path: assets/xyz/
      transformers:
        - package: vector_graphics_compiler

(flutter run)

FAILED

--------------------
2) Made new dir /test with 1 svg item in it.

    - path: assets/test/
      transformers:
        - package: vector_graphics_compiler

SUCCESS

--------------------
3) Copied the 31 svg's from /xyz into the /test dir

FAILED

--------------------
4) Went back and tried the single svg item again

SUCCESS

--------------------
5) This time tried with 2 svg's in /test dir

SUCCESS

--------------------
6) Tried with 15 svg's in /test dir

FAILED

It transformed 11 items: 

[+1999 ms] [+2082 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item30.svg' (2406ms)
[  +94 ms] [  +33 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item45.svg' (2437ms)
[        ] [  +18 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item65.svg' (2454ms)
[        ] [  +23 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item40.svg' (2481ms)
[        ] [   +6 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item50.svg' (2483ms)
[        ] [   +1 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item20.svg' (2491ms)
[  +93 ms] [  +36 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item55.svg' (2523ms)
[        ] [   +2 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item10.svg' (2534ms)
[        ] [   +3 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item60.svg' (2529ms)
[        ] [   +1 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item35.svg' (2533ms)
[        ] [  +12 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item15.svg' (2548ms)

Stuck for several minutes (CPU loud), then

[+341702 ms] [+341688 ms] Persisting file store
[   +2 ms] [  +18 ms] Done persisting file store
[   +2 ms] [  +11 ms] Target debug_android_application failed: Error: User-defined transformation of asset 
"C:\Users\me\projectname\dev-projectname\assets\test\item70.svg" failed.
[   +3 ms]            Transformer process terminated with non-zero exit code: 255
[        ]            Transformer package: vector_graphics_compiler
[        ]            Full command: C:\Flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler
--input=C:\Users\me\AppData\Local\Temp\flutter_tools.6ccc28c2\item70.svg-transformOutput0.svg
--output=C:\Users\me\AppData\Local\Temp\flutter_tools.6ccc28c2\item70.svg-transformOutput1.svg
[        ]            stdout:
[        ]            stderr:
[        ]            Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmp449ac982\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            PathAccessException: Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmp449ac982\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      copyAssets.<anonymous closure>
...dart errors


--------------------
7) This time I limited it to 10 svg's, and ensured I included item70.svg

FAILED

It transformed 9 of the items, INCLUDING item70.svg.  This time, it "failed" at item 65.svg with same errors as above.

--------------------
8) This time, tried 5 svg's

SUCCESS

And that includes item65.svg and item70.svg

--------------------
9) Tried 8 svg's

FAILED

As always, it stops on a random SVG, so I do not think the file is the issue.

This time it processed 7 out of 8 and died:

[+1194 ms] [+1266 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item20.svg' (1487ms)
[        ] [  +10 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item15.svg' (1493ms)
[        ] [        ] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item35.svg' (1492ms)
[  +91 ms] [  +21 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item65.svg' (1513ms)
[        ] [  +20 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item70.svg' (1533ms)
[        ] [        ] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item25.svg' (1536ms)
[        ] [   +3 ms] Finished transforming asset at path
'C:\Users\me\projectname\dev-projectname\assets\test\item5.svg' (1538ms)
[        ] [   +2 ms] Persisting file store
[        ] [  +18 ms] Done persisting file store
[        ] [  +11 ms] Target debug_android_application failed: Error: User-defined transformation of asset 
"C:\Users\me\projectname\dev-projectname\assets\test\item40.svg" failed.
[   +1 ms]            Transformer process terminated with non-zero exit code: 255
[        ]            Transformer package: vector_graphics_compiler
[        ]            Full command: C:\Flutter\bin\cache\dart-sdk\bin\dart.exe run vector_graphics_compiler
--input=C:\Users\me\AppData\Local\Temp\flutter_tools.d2ba8b6f\item40.svg-transformOutput0.svg
--output=C:\Users\me\AppData\Local\Temp\flutter_tools.d2ba8b6f\item40.svg-transformOutput1.svg
[        ]            stdout:
[        ]            stderr:
[        ]            Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmpd270e2c4\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            PathAccessException: Cannot rename file to
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\vector_graphics_compile
r.dart-3.5.3.snapshot', path =
'C:\Users\me\projectname\dev-projectname\.dart_tool/pub\bin\vector_graphics_compiler\tmpd270e2c4\vector_grap
hics_compiler.dart-3.5.3.snapshot.incremental.temp' (OS Error: Access is denied.
[        ]            , errno = 5)
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      copyAssets.<anonymous closure>
(package:flutter_tools/src/build_system/targets/assets.dart:157:19)

--------------------
-> 10) Tried 7 items

FAILED

This time, it only finished 5 items out of 7.  

It is telling that the "finished" item count for a list of items (say 9 finished out of 10) can be HIGHER than the TOTAL number of items when it fails (for example, finished only 5 out of 7). 

Here is another clue:  When I include ALL my dirs and items, about 200 items, it processes MOST of them, then eventually fails. 

Are the failures related to dir listings?

--------------------
11) Let's try 6 items:

FAILED

Processed 5 out of 6

--------------------
12) NOW, back to 5 items, which worked in the past

SUCCESS!


So from my testing, > 5 items always fails.

**Comment by darshankawar** [comment]
Based on the error log shared above, it is similar to https://github.com/flutter/flutter/issues/158870, so please follow-up in it for further updates. You may share your findings in that issue for better tracking and provide a runnable reproducible code (minimal app or main.dart with pubspec.yaml) that consistently throws the reported error.

If you disagree, write in comments and I'll reopen it.
