### ISSUE TITLE
ANR Android createAndRunDefaultEngine

### ISSUE THREAD

**Issue by ashraf-patel-hs** [flutter/flutter#159071]
### Steps to reproduce

We are creating flutter engine group in my our Android Application class on main thread and it's causing ANR.

> App Launch

### Expected results

No ANR

### Actual results

ANR

### Code sample
```
engines = new FlutterEngineGroup(this);
engines.createAndRunDefaultEngine(this);
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
main (native):tid=1 systid=28550 
#00 pc 0x9da54 libc.so (__ioctl + 12) (BuildId: 8b21ee25038a8bdda0846f1e8fb16297)
#01 pc 0x696b3 libc.so (ioctl + 26) (BuildId: 8b21ee25038a8bdda0846f1e8fb16297)
#02 pc 0x5e941 libhidlbase.so (android::hardware::IPCThreadState::talkWithDriver + 168) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#03 pc 0x5fe03 libhidlbase.so (android::hardware::IPCThreadState::waitForResponse + 38) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#04 pc 0x5fae7 libhidlbase.so (android::hardware::IPCThreadState::transact + 114) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#05 pc 0x5c8ad libhidlbase.so (android::hardware::BpHwBinder::transact + 36) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#06 pc 0x42a4f libhidlbase.so (android::hidl::manager::V1_0::BpHwServiceManager::_hidl_getTransport + 246) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#07 pc 0x53b25 libhidlbase.so (android::hidl::manager::V1_2::BpHwServiceManager::getTransport + 40) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#08 pc 0x34cef libhidlbase.so (android::hardware::details::getRawServiceInternal + 134) (BuildId: 69c2d5161c2099c51ae6a9b99a85b68d)
#09 pc 0xebe1 android.hardware.configstore@1.0.so (android::sp<android::hardware::configstore::V1_0::ISurfaceFlingerConfigs> android::hardware::details::getServiceInternal<android::hardware::configstore::V1_0::BpHwSurfaceFlingerConfigs, android::hardware::configstore::V1_0::ISurfaceFlingerConfigs, void, void> + 124) (BuildId: 379de05bf8581c2fc7e349623bcd0608)
#10 pc 0xecfb android.hardware.configstore@1.0.so (android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::getService + 6) (BuildId: 379de05bf8581c2fc7e349623bcd0608)
#11 pc 0x9899 libSurfaceFlingerProp.so (android::sp<android::hardware::configstore::V1_0::ISurfaceFlingerConfigs> android::hardware::configstore::getService<android::hardware::configstore::V1_0::ISurfaceFlingerConfigs> + 112) (BuildId: 9ca6e2afcd2449ada9c8d242dc303970)
#12 pc 0xb0e3 libSurfaceFlingerProp.so (decltype android::hardware::configstore::get<android::hardware::configstore::V1_0::OptionalBool, android::hardware::configstore::V1_0::ISurfaceFlingerConfigs, &android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay>::'lambda'::operator const + 26) (BuildId: 9ca6e2afcd2449ada9c8d242dc303970)
#13 pc 0xb081 libSurfaceFlingerProp.so (decltype android::hardware::configstore::get<android::hardware::configstore::V1_0::OptionalBool, android::hardware::configstore::V1_0::ISurfaceFlingerConfigs, &android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay> + 628) (BuildId: 9ca6e2afcd2449ada9c8d242dc303970)
#14 pc 0x89ad libSurfaceFlingerProp.so (android::sysprop::has_wide_color_display + 36) (BuildId: 9ca6e2afcd2449ada9c8d242dc303970)
#15 pc 0x1010b libEGL.so (android::egl_display_t::initialize + 758) (BuildId: 9c710fe9314e2d6c8ef3b25bea676837)
#16 pc 0x28c1ad libflutter.so (BuildId: 842ef3cd1a9002b3bce8a615b82553adc61d8c10)
       at io.flutter.embedding.engine.FlutterJNI.nativeAttach(FlutterJNI.java)
       at io.flutter.embedding.engine.FlutterJNI.performNativeAttach(FlutterJNI.java:432)
       at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:424)
       at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:399)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:369)
       at io.flutter.embedding.engine.FlutterEngineGroup.createEngine(FlutterEngineGroup.java:206)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:158)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:121)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:100)
       at io.flutter.embedding.engine.FlutterEngineGroup.createAndRunDefaultEngine(FlutterEngineGroup.java:82)
       at         
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.0 23A344 darwin-arm64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)            
    ! Error: Browsing on the local area network for Ashraf’s iPhone (2). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hello @ashraf-patel-hs 
For us to investigate this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thank you!
