### ISSUE TITLE
Hot Reload Issue with Multiple GlobalKey<NavigatorState> in Parent and Child Navigators

### ISSUE THREAD

**Issue by leedagr88** [flutter/flutter#159091]
### Steps to reproduce

1. Create a MaterialApp with a top-level Navigator using a GlobalKey<NavigatorState>.
2. Inside one of the screens of the app, create a child Navigator (e.g., inside a FlowNavigator widget) with a separate GlobalKey<NavigatorState>.
3. Push routes onto the child navigator.
4. Perform a hot reload.
5. Observe that the child navigator's state might be reset, or routes are popped incorrectly due to interference from the parent navigator's state.

### Expected results

The parent and child navigators should operate independently of each other, and the state of the child navigator should not be affected by the parent navigator during a hot reload or rebuild

### Actual results

The state of the child navigator is unexpectedly reset, or routes are popped incorrectly due to interference from the parent navigator's state.

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // Parent Navigator Global Key
  static final GlobalKey<NavigatorState> appNavigatorKey =
      GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: appNavigatorKey, // Global Key for the main Navigator
      home: ParentScreen(),
    );
  }
}

class ParentScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Parent Navigator')),
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () {
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (context) => ChildScreen(),
                ),
              );
            },
            child: Text('Go to Child Screen'),
          ),
        ],
      ),
    );
  }
}

class ChildScreen extends StatelessWidget {
  // Child Navigator Global Key
  static final GlobalKey<NavigatorState> childNavigatorKey =
      GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Child Navigator')),
      body: FlowNavigator(childNavigatorKey: childNavigatorKey),
    );
  }
}

class FlowNavigator extends StatelessWidget {
  final GlobalKey<NavigatorState> childNavigatorKey;

  FlowNavigator({required this.childNavigatorKey});

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: childNavigatorKey, // Child Navigator Key
      initialRoute: '/first',
      onGenerateRoute: (settings) {
        if (settings.name == '/first') {
          return MaterialPageRoute(builder: (_) => FirstChildScreen());
        } else if (settings.name == '/second') {
          return MaterialPageRoute(builder: (_) => SecondChildScreen());
        }
        return null;
      },
    );
  }
}

class FirstChildScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('First Child Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).pushNamed('/second');
          },
          child: Text('Go to Second Child Screen'),
        ),
      ),
    );
  }
}

class SecondChildScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Second Child Screen')),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).pop(); // Pop to previous screen
          },
          child: Text('Go Back'),
        ),
      ),
    );
  }
}   
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.7 23H124 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/lejohnson/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (10 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/lejohnson/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/lejohnson/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.2)
    • VS Code at /Users/lejohnson/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 15 Pro Max (mobile)      • CB675D2F-4561-45AB-B337-42C786FE7B33 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.7 23H124 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.7 23H124 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by darshankawar** [comment]
@leedagr88 
Upon running the code and tapping on `Go to child screen`, I get below error:

<details>
<summary> error log </summary>

```

======== Exception caught by Flutter framework =====================================================
The following message was thrown:
Could not navigate to initial route.
The requested route name was: "/first"
There was no corresponding route in the app, and therefore the initial route specified will be ignored and "/" will be used instead.

====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building FlowNavigator:
Navigator.onGenerateRoute was null, but the route named "/" was referenced.

To use the Navigator API with named routes (pushNamed, pushReplacementNamed, or pushNamedAndRemoveUntil), the Navigator must be provided with an onGenerateRoute handler.
The Navigator was:
  NavigatorState#ebbe8(lifecycle state: initialized)
The relevant error-causing widget was: 
  FlowNavigator FlowNavigator:file:///Users/dhs/Documents/NCFlutter/integration_dummy/lib/main.dart:53:13
When the exception was thrown, this was the stack: 
#0      NavigatorState._routeNamed.<anonymous closure> (package:flutter/src/widgets/navigator.dart:4505:9)
#1      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4515:6)
#2      Navigator.defaultGenerateInitialRoutes (package:flutter/src/widgets/navigator.dart:2904:28)
#3      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3745:41)
#4      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:924:5)
#5      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:910:7)
#6      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3792:11)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5766:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
...     Normal element mounting (31 frames)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#40     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047:32)
...     Normal element mounting (338 frames)
#379    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#380    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#381    Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#382    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#383    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#384    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#385    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#386    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#387    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#388    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#389    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#390    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#391    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#392    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#393    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#394    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#395    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#396    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#397    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#398    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#399    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#400    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#401    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#402    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#403    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#404    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#405    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#406    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#407    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#408    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#409    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#410    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#411    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#412    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#413    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#414    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#415    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#416    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#417    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#418    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#419    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#420    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#421    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#422    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#423    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#424    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#425    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#426    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#427    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#428    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#429    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#430    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#431    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#432    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#433    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#434    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#435    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#436    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#437    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#438    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#439    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#440    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#441    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#442    _invoke (dart:ui/hooks.dart:312:13)
#443    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#444    _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
W/OnBackInvokedCallback( 3719): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 3719): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/EGL_emulation( 3719): app_time_stats: avg=2116.06ms min=298.26ms max=3933.86ms count=2

```

</details>

Then tapping on appbar back button and hot reloading gives me below error:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [LabeledGlobalKey<_OverlayEntryWidgetState>#b670a]
  [LabeledGlobalKey<_OverlayEntryWidgetState>#86d6b]
This was determined by noticing that after widgets with the above global keys were moved out of their previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widgets were moved, in either case implying that it still thinks that it should have a child with those global keys.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- _Theater(skipCount: 0, dependencies: [Directionality], renderObject: _RenderTheater#aa66e NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3317:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3342:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1040:9)
#7      PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
Reloaded 0 libraries in 408ms (compile: 24 ms, reload: 0 ms, reassemble: 225 ms).
D/EGL_emulation( 3719): app_time_stats: avg=251.04ms min=14.18ms max=3904.77ms count=17

```

Note the `duplicate keys detected` message and `A GlobalKey can only be specified on one widget at a time in the widget tree.` message considering the fact that you are using multiple global keys, so please re-visit your code implementation to check if you are making use of global keys correctly.

**Comment by leedagr88** [comment]
@darshankawar sorry I updated the code, try now please

**Comment by darshankawar** [comment]
After hot reloading on second screen, I get below:

<img width="152" alt="Screenshot 2024-11-20 at 11 13 06 AM" src="https://github.com/user-attachments/assets/874e60dc-6633-4c0f-8139-46a8fa95a4f5">

Is this what are you reporting ?
