### ISSUE TITLE
Flutter Wasm Web App Crashes in Opera Often

### ISSUE THREAD

**Issue by rayliverified** [flutter/flutter#159096]
### Steps to reproduce

This issue is filed to the Flutter team because the crashes occur in Opera, but not in Chrome or Edge.

```
skwasm.js:17 Uncaught RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at za (skwasm.js:17:79)
    at abort (skwasm.js:66:400)
    at skwasm.wasm:0xa72c
    at skwasm.wasm:0x6f33b
    at skwasm.wasm:0x1f0e3
    at skwasm.wasm:0x9be3f
    at skwasm.wasm:0x93066
    at skwasm.wasm:0x9c773
    at skwasm.wasm:0x54e00
    at skwasm.wasm:0x45e6b
```

1. Open https://dev.codelessly.com on Opera Browser.
2. Create an account or login with email / password.
3. App crashes.
4. Refresh, load app again.
5. Click around a few times. App crashes sometimes immediately, sometimes in 10 - 20 seconds.

![image](https://github.com/user-attachments/assets/521b514b-5a99-4bd9-8fdb-d80f21f30155)

![image](https://github.com/user-attachments/assets/c8c0c062-bbc6-488b-a9f6-4063c56894f2)

I would appreciate help in getting more information:

1. How to debug Wasm exceptions and crashes? Wasm exceptions don't contain helpful information.
2. Is there a way to get the browser crash logs? Opera only reports them and doesn't seem to store them in a readable format.

### Expected results

App should not crash like in Chrome. Crashes only happen in Opera.

Related: Google Cloud Console and Google Meet also crash often in Opera. This is the only other sites where I experience frequent crashes in Opera.

### Actual results

Flutter Wasm app crashes often immediately and consistently within 20 seconds on Opera.

### Code sample

Unable to provide a minimal reproducible sample yet as the example likely requires Firebase libraries to trigger the crash. No luck yet.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Freezes browser tab, refresh doesn't work, requires closing tab and process instance.

https://github.com/user-attachments/assets/01b4c98d-df75-42bd-aa8c-da681f35ee0e
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel beta, 3.27.0-0.1.pre, on Microsoft Windows [Version
    10.0.22631.4460], locale en-US)
    • Flutter version 3.27.0-0.1.pre on channel beta at C:\Users\searc\fvm\versions\beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e2c358c9b (4 weeks ago), 2024-10-22 11:02:13 -0400
    • Engine revision af0f0d559c
    • Dart version 3.6.0 (build 3.6.0-334.3.beta)
    • DevTools version 2.40.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\searc\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34202.233
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\searc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version
      10.0.22631.4460]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.51        

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @rayliverified 
I followed the steps but couldn't see the crash trace as reported. Is there any trace you can get and share here? Does the crash only occur when dragging at `Recent projects` area?

**Comment by rayliverified** [comment]
Thanks for testing!

Oh, I forgot to mention this, the crashing is on Opera Windows. Were you
able to experience the crash on Opera?

The crash often happens immediate, other times after a few seconds, as a
result of no particular action.

**Comment by huycozy** [comment]
I checked this on Opera on macOS host but the crash didn't occur, here is the demo:

<details>
<summary>Demo video (crash does not appear)</summary>

https://github.com/user-attachments/assets/abc5b538-9b62-4d1e-aa75-fe3c8276772c

</details>

I will mark this issue for input from team. Once you can reproduce the issue with a reduced sample code, please provide it so it's more helpful to investigate further. Thanks!

**Comment by brian-superlist** [comment]
As a heads up, we're experiencing this as well on https://app.superlist.com. Not sure what Opera is doing differently than edge/chrome, but it'd be great to look into.

**Comment by rayliverified** [comment]
Ah ha, found a good repo. It's not the minimal code though as it's reproducible in Dartpad.

Open the following URL in Opera. Wait for the demo to load.
https://api.flutter.dev/flutter/widgets/PreferredSize-class.html

Result: Demo Flutter app freezes. Tab crashes.

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/b1b75fae-6312-4c42-8825-fc19fa7c7f4a" />

https://github.com/user-attachments/assets/a638c157-c6c7-4b62-b220-7e0cd8066f8b

**Comment by rayliverified** [comment]
Good news, the latest Opera One(version: 115.0.5322.119) seems to have fixed Wasm crashing.

The remaining issues and crashes I see on Wasm web are:
1. Wasm and Flutter Web still suffer from OOM.
2. Too many Firebase / Firestore queries crashes.

But those are separate issues.
