### ISSUE TITLE
Build linux failed by INSTALL not found "native_assets/linux" 

### ISSUE THREAD

**Issue by shilkazx** [flutter/flutter#159199]
### Steps to reproduce

flutter build linux will trigger this bug

### Expected results

build successfully just as 'flutter build apk' does.

### Actual results

```
CMake Error at cmake_install.cmake:112 (file):
  file INSTALL cannot find "/home/....../build/native_assets/linux": No such
  file or directory.
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on Arch Linux 6.11.9-zen1-1-zen, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @shilkazx 
Does this issue also appear with `flutter run` command? Can you please share the entire output of running command with verbose? (`flutter run -v` or `flutter build linux -v`) [^1]

[^1]: The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it.

**Comment by shilkazx** [comment]
> Hi @shilkazx Does this issue also appear with `flutter run` command? Can you please share the entire output of running command with verbose? (`flutter run -v` or `flutter build linux -v`) [1](#user-content-fn-1-c981bb592aae5e63f6907a8701d844c0)
> ## Footnotes
> 
>     1. The output may be too large to be uploaded to GitHub, you may upload it as a txt file or use online tools like https://pastebin.com/ to share it. [↩](#user-content-fnref-1-c981bb592aae5e63f6907a8701d844c0)

Sure, the `flutter run` failed just like what build linux do. And the verbose output is:
```
flutter build linux -v      
[  +11 ms] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +31 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[  +27 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +34 ms] Skipping pub get: version match.
[  +86 ms] Generating /home/user/Nutstore/project/flutter/xuan/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +61 ms] Building Linux application...
[   +3 ms] executing: [~/.cache/gradle_build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/user/Nutstore/project/flutter/xuan/linux
[  +38 ms] -- Configuring done (0.0s)
[   +8 ms] -- Generating done (0.0s)
[        ] -- Build files have been written to: /home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release
[  +18 ms] executing: ninja -C ~/.cache/gradle_build/linux/x64/release install
[  +14 ms] ninja: Entering directory `~/.cache/gradle_build/linux/x64/release'
[+1134 ms] [1/5] Generating /home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/user/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/user/Nutstore
Files/Nutstore/project/flutter/xuan/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [   +7 ms] executing: uname -m
[        ] [   +5 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +26 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +1 ms] Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[        ] [  +48 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +34 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +31 ms] Skipping target: gen_localizations
[        ] [   +4 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +130 ms] Skipping target: unpack_linux
[        ] [ +177 ms] Skipping target: kernel_snapshot_program
[        ] [   +1 ms] Skipping target: native_assets
[        ] [        ] Skipping target: kernel_snapshot_native_assets
[        ] [        ] Skipping target: kernel_snapshot
[        ] [ +107 ms] Skipping target: aot_elf_release
[        ] [  +17 ms] Skipping target: linux_aot_bundle
[        ] [  +21 ms] Skipping target: release_bundle_linux-x64_assets
[        ] [        ] Persisting file store
[        ] [   +3 ms] Done persisting file store
[        ] [   +2 ms] build succeeded.
[        ] [   +3 ms] "flutter assemble" took 601ms.
[        ] [ +252 ms] ensureAnalyticsSent: 229ms
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [   +3 ms] exiting with code 0
[ +285 ms] [2/5] Building CXX object CMakeFiles/xuan.dir/flutter/generated_plugin_registrant.cc.o
[  +33 ms] [3/5] Building CXX object CMakeFiles/xuan.dir/my_application.cc.o
[  +76 ms] [4/5] Linking CXX executable intermediates_do_not_run/xuan
[        ] [4/5] Install the project...
[   +7 ms] -- Install configuration: "Release"
[   +1 ms] -- Installing: /home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release/bundle/xuan
[        ] -- Set non-toolchain portion of runtime path of "/home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release/bundle/xuan" to "$ORIGIN/lib"
[        ] -- Installing: /home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release/bundle/data/icudtl.dat
[        ] -- Installing: /home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release/bundle/lib/libflutter_linux_gtk.so
[   +7 ms] CMake Error at cmake_install.cmake:112 (file):
[        ]   file INSTALL cannot find "/home/user/Nutstore
[        ]   Files/Nutstore/project/flutter/xuan/build/native_assets/linux": No such
[        ]   file or directory.
[        ] FAILED: CMakeFiles/install.util 
[        ] cd "/home/user/Nutstore/project/flutter/xuan/~/.cache/gradle_build/linux/x64/release" && /usr/bin/cmake -P cmake_install.cmake
[        ] ninja: build stopped: subcommand failed.
[   +8 ms] Building Linux application... (completed in 1,640ms)
[        ] "flutter linux" took 1,885ms.
[  +24 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:87:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +136 ms] ensureAnalyticsSent: 134ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1

```

**Comment by darshankawar** [comment]
Can you try [this](https://github.com/flutter/flutter/issues/115230#issuecomment-1323412869) to see if it helps in your case or not ?

**Comment by shilkazx** [comment]
> Can you try [this](https://github.com/flutter/flutter/issues/115230#issuecomment-1323412869) to see if it helps in your case or not ?

Thanks for your hints. But that's not my situation. In the post you mentioned above, the bug reporter uses a Redhat based system and lack of libstdc++ library. But I use an up-to-date Archlinux and the content shipped with "libstdc++-devel" under Redhat is already shipped with gcc in Archlinux(I've checked the content of libstdc++-devel on a Rocky Linux server).

**Comment by darshankawar** [comment]
@shilkazx 
I don't have the said Linux setup to verify at my end. Can you switch to latest master and re-run your scenario to check if it still persist or not ?

**Comment by shilkazx** [comment]
> @shilkazx I don't have the said Linux setup to verify at my end. Can you switch to latest master and re-run your scenario to check if it still persist or not ?

I've cloned repo with depth 1, and it gives me this error:
```
The current Flutter SDK version is 0.0.0-unknown.

Because every version of flutter_test from sdk depends on leak_tracker_flutter_testing >=2.0.3 which requires Flutter SDK version >=3.18.0-18.0.pre.54, flutter_test from sdk is forbidden.
So, because test depends on flutter_test from sdk, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.24.5. 
Failed to update packages.
```

**Comment by darshankawar** [comment]
@shilkazx 
You probably are on checkout version of stable. Please run `flutter channel master` and then try to run your scenario.

**Comment by shilkazx** [comment]
It drives me nuts.
The `flutter channel master` works perfect and I run `flutter upgrade` also completed without error:
```
Flutter is already up to date on channel master
Flutter • channel master • https://gitee.com/mirrors/Flutter.git
Framework • revision 9bd2853737 (14 hours ago) • 2024-11-24 19:06:26 -0500
Engine • revision 0ced389c84
Tools • Dart 3.7.0 (build 3.7.0-183.0.dev) • DevTools 2.41.0-dev.2
```
Then `flutter build linux` still complain "The current Flutter SDK version is 0.0.0-unknown." etc.

**Comment by darshankawar** [comment]
> Then `flutter build linux` still complain "The current Flutter SDK version is 0.0.0-unknown." etc.

Check https://github.com/flutter/flutter/issues/148000 for further reference.



> The `flutter channel master` works perfect and I run `flutter upgrade` also completed without error:

Does this mean the reported error doesn't occur in master ?

**Comment by shilkazx** [comment]
> > Then `flutter build linux` still complain "The current Flutter SDK version is 0.0.0-unknown." etc.
> 
> Check #148000 for further reference.
> 
> > The `flutter channel master` works perfect and I run `flutter upgrade` also completed without error:
> 
> Does this mean the reported error doesn't occur in master ?

No. The new obstacle block the build process.

I tried to fix this according to #148000, but met another bug that the flutter hint about `git remote set-url` not work:
```
> git remote set-url upstream https://github.com/flutter/flutter.git                                                                                             > ./bin/flutter update-packages                                                                                                                                  
The current Flutter SDK version is 0.0.0-unknown.

Because flutter_update_packages depends on provider >=4.0.0-dev which requires Flutter SDK version >=1.12.1, version solving failed.


If the current version was resolved as 0.0.0-unknown and this is a fork of flutter/flutter, you forgot to set the remote upstream branch to point to the canonical flutter/flutter: 

  git remote set-url upstream https://github.com/flutter/flutter.git

See https://github.com/flutter/flutter/blob/main/docs/contributing/Setting-up-the-Framework-development-environment.md#set-up-your-environment.
Failed to update packages.
```

**Comment by darshankawar** [comment]
I will keep the issue open for team's tracking as currently I don't have linux setup to verify this.

**Comment by shilkazx** [comment]
UPDATE:

I create and build a sample project on a rocky linux 9.3 server. Everything worked fine. I checked the `build/native_assets/linux` directory and found it was empty. 
Then I manually create the `build/native_assets/linux` folder under project position on my buggy Arch Linux. Rebuild my project--it completed without error. 
So it seems this bug might be something related to build/make process(scripts) but not lack of some library. 

Regards,

**Comment by aefn** [comment]
I did something and resolved this issue for me maybe it helps others too.
my flutter version output

```
Flutter 3.32.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d7b523b356 (6 days ago) • 2025-07-15 17:03:46 -0700
Engine • revision 39d6d6e699 (6 days ago) • 2025-07-15 15:39:12 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1
```

I've created my main project as `flutter create -e my_main_project` as empty project and it was not working.
Then I created a test project as `flutter create test_project` which use the default template.
I could run the test project, you also need to first check that you can run it or not, if you can then follow next step.

I copied the `linux` dir from `test_project` into `my_main_project` and replace all `test_project` from linux/CMakeLists.txt with `my_main_project`.

Then run 
`flutter clean && flutter pub get`
And afterwards `flutter run`works on linux.
Hope it helps.

**Comment by EinarArnason** [comment]
in the cmake file, PROJECT_BUILD_DIR points to `<source dir>/build` instead of `<source dir>/<custom build dir>`. So it seems it's hard coded.

**Comment by merlinnot** [comment]
#180429 should fix it. Worked for me.

**Comment by 41y08h** [comment]
I had this problem on windows and in my case the fix was just `flutter clean`
