### ISSUE TITLE
Error when initialice  SharedPreferences.getInstance();

### ISSUE THREAD

**Issue by jcrasgado** [flutter/flutter#15916]
Good day 

Today when i tried to run my app i had this error,  yesterday i worked with SharedPreferences and i didn't have problem, any solution?

I work with shared_preferences: ^0.4.0

Thaks...

E/flutter (27114): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27114): type '_InternalLinkedHashMap' is not a subtype of type 'Map<String, Object>' where
E/flutter (27114):   _InternalLinkedHashMap is from dart:collection
E/flutter (27114):   Map is from dart:core
E/flutter (27114):   String is from dart:core
E/flutter (27114):   Object is from dart:core
E/flutter (27114): 
E/flutter (27114): #0      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart)
E/flutter (27114): <asynchronous suspension>
E/flutter (27114): #1      _MyLoginState._loginButton (package:RamApp/screen/login.dart:118:53)
E/flutter (27114): <asynchronous suspension>
E/flutter (27114): #2      _MyLoginState._setAutenticar.<anonymous closure> (package:RamApp/screen/login.dart:101:5)
E/flutter (27114): #3      State.setState (package:flutter/src/widgets/framework.dart:1108:30)
E/flutter (27114): #4      _MyLoginState._setAutenticar (package:RamApp/screen/login.dart:95:3)
E/flutter (27114): #5      _MyLoginState.build.<anonymous closure> (package:RamApp/screen/login.dart:252:11)
E/flutter (27114): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (27114): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (27114): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (27114): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (27114): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (27114): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (27114): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (27114): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (27114): #14     _BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (27114): #15     _BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (27114): #16     _BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (27114): #17     _BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (27114): #18     _BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (27114): #19     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (27114): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

**Comment by zoechi** [comment]
Please show the code that causes this error, 
the output of `flutter doctor -v`,
 and the version of `shared_preferences` from `pubspec.lock`

**Comment by fractalemagic** [comment]
I had the same issue earlier, running `flutter clean` fixed it for me.

**Comment by moregrins** [comment]
I'm getting the same error. The problem happens right in: SharedPreferences prefs = await SharedPreferences.getInstance();

flutter doctor -v
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.3 at C:\Users\Candamo LLC\flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Candamo LLC\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Software Development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Software Development\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!

----------------------------
# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.31.1"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  barback:
    dependency: transitive
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+14"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+1"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.6"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  front_end:
    dependency: transitive
    description:
      name: front_end
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0-alpha.9"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+16"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2+1"
  isolate:
    dependency: transitive
    description:
      name: isolate
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  kernel:
    dependency: transitive
    description:
      name: kernel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.0-alpha.9"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.1+4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6"
  mockito:
    dependency: transitive
    description:
      name: mockito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.3"
  multi_server_socket:
    dependency: transitive
    description:
      name: multi_server_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  node_preamble:
    dependency: transitive
    description:
      name: node_preamble
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  package_resolver:
    dependency: transitive
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.1"
  plugin:
    dependency: transitive
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+2"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.2"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.28.0"
  shared_preferences:
    dependency: "direct main"
    description:
      name: shared_preferences
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.2"
  shelf_packages_handler:
    dependency: transitive
    description:
      name: shelf_packages_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  shelf_static:
    dependency: transitive
    description:
      name: shelf_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.7"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_map_stack_trace:
    dependency: transitive
    description:
      name: source_map_stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.4"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.2"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.4"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  test:
    dependency: transitive
    description:
      name: test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.32+1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  utf:
    dependency: transitive
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+4"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+7"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.13"
sdks:
  dart: ">=2.0.0-dev.28.0 <=2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c"
  flutter: ">=0.1.4 <2.0.0"

**Comment by MarcinusX** [comment]
For me this worked:

1. delete `pub-cache` directory
2.  run `flutter clean`
3. make sure version `^0.4.1` is in `pubspec.yaml`

**Comment by zoechi** [comment]
Deleting `pub cache` is unlikely to help. 
That was a good suggestion when Pub was new and unstable, but I didn't have to use it since years.

**Comment by MarcinusX** [comment]
Interesting, to be honest, I use it from time to time and it usually helps :) Especially during flutter-beta/dart2.0 migrations.

**Comment by mikeashelby** [comment]
I'm having this exact problem too! On that line I get an app crash, but no error messages at all. SharedPreferences: ^0.4.1

Was working completely fine. Started trying to add firebase auth for my firestore database. Not sure if the two are related, but when I did it, this bug started. It's taken me the last 24 hours to track it down to this line!

Just for you info Flutter doctor:

`/Users/mikeashelby/development/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E202, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

• No issues found!
Process finished with exit code 0`

Thanks in advance for your help. Let me know if you need any more info form me. It'll be Monday now, but happy to drop it to you!

**Comment by zoechi** [comment]
Is anybody still seeing this?

**Comment by MarcinusX** [comment]
Not me since then. And FYI I am the only one who voted up that issue, so I guess it's safe to close :)

**Comment by ascmp** [comment]
I still see this issue:

```
alessio@haisuli:~/workspace/dss_flux$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
```
with dependency:

```
  # Shared preferences
  shared_preferences: ^0.5.3+4
```
when I change one test from initializing shared preferences like this:

```
    setUp(() {
      SharedPreferences.setMockInitialValues({});
    });
```
to initializing shared preferences with some default values:

```
    setUp(() {
      SharedPreferences.setMockInitialValues({
        "MyModel.MyName": "myName",
        "MyModel.MyEmail": "myEmail",
        "MyModel.MyPassword": "myPassword"
      });
    });
```

**Comment by tudor07** [comment]
I still see this issue

**Comment by tudor07** [comment]
@zoechi I still see this issue, can you re-open?

**Comment by simbakowo** [comment]
I am also getting the same error on the same line: ```  SharedPreferences prefs = await SharedPreferences.getInstance();```
Was working one day and then just started throwing an error there. The error is NoSuchMethod()

**Comment by imranjanwari** [comment]
Try these,

1. Run flutter clean
2. Use latest version "2.0.5" is in pubspec.yaml
3. Make sure the value you are setting doesn't have null. It is confusing at point, it will throw error on getInstance() while issue will be further setting null values. example below,

```
SharedPreferences prefs = await SharedPreferences.getInstance();
prefs.setString('name', ((data != null) ? data : ""));
```

**Comment by melvinm99** [comment]
> Try these,
> 
> 1. Run flutter clean
> 2. Use latest version "2.0.5" is in pubspec.yaml
> 3. Make sure the value you are setting doesn't have null. It is confusing at point, it will throw error on getInstance() while issue will be further setting null values. example below,
> 
> ```
> SharedPreferences prefs = await SharedPreferences.getInstance();
> prefs.setString('name', ((data != null) ? data : ""));
> ```

This worked for me

**Comment by YorelAcostaB** [comment]
> 
> 
> Is anybody still seeing this?

Yup, I've the same error...
