### ISSUE TITLE
DropdownButton assert could report a more helpful error description.

### ISSUE THREAD

**Issue by dss539** [flutter/flutter#15911]
When setting `DropdownButton`'s `value` parameter to a value that is not contained within the `items` list, the following assert is triggered.

```
I/flutter (31441): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31441): The following assertion was thrown building MyEditor(dirty, state: _MyEditorState#de0af):
I/flutter (31441): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 468 pos 15: 'value == null ||
I/flutter (31441): items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.
I/flutter (31441): 
I/flutter (31441): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31441): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31441): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31441):   https://github.com/flutter/flutter/issues/new
I/flutter (31441): 
I/flutter (31441): When the exception was thrown, this was the stack:
I/flutter (31441): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:468:15)
I/flutter (31441): #3      _MyEditorState.build (/data/user/0/REDACTED/cache/REDACTED/lib/my_editor.dart:84:34)
I/flutter (31441): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (31441): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (31441): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #53     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4340:32)
I/flutter (31441): #54     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:17)
I/flutter (31441): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #56     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (31441): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #78     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #82     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
I/flutter (31441): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #88     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #92     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #96     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #100    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #104    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #112    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #120    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #124    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #128    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (31441): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #132    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
I/flutter (31441): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #136    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
I/flutter (31441): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #140    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
Reloaded 2 of 497 libraries in 1,830ms.
I/flutter (31441): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (31441): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (31441): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (31441): #144    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (31441): #145    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (31441): #146    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (31441): #147    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (31441): #148    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (31441): #149    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (31441): #151    _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
I/flutter (31441): #152    _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
I/flutter (31441): #153    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter (31441): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (31441): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by alexandretperez** [comment]
I'm with the same problem.

A workaround for now is set null when the value is invalid.

```
DropdownButton(
    items: _categories.map((value) {
        return DropdownMenuItem<String>(
            child: Text(value),
            value: value,
        );
     }).toList(),
     onChanged: (String value) {},
     value: _category == "" ? null : _category
)
```

**Comment by Anyoks** [comment]
In-case you still face this issue kindly check my response [here](https://github.com/flutter/flutter/issues/17903#issuecomment-568278319)
