### ISSUE TITLE
Firebase is not working with iOS

### ISSUE THREAD

**Issue by bartektartanus** [flutter/flutter#15914]
I've added dependency to Firebase in my project, just like described here:
https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4

and I'm getting this error while trying to start an iOS app (android works fine):
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in FirebaseAnalyticsPlugin.o
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in FirebaseAnalyticsPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I commented out firebase analytic dependency from yaml file and the ios app started. But now I'm getting another error - this time with database dependency:

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
<asynchronous suspension>
#1      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:48:38)
#2      _runGuarded (dart:async/stream_controller.dart:804)
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217)
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817)
#5      _StreamImpl.listen (dart:async/stream_impl.dart:466)
#6      ListBase&StreamSubscriberMixin.listen (package:firebase_database/ui/utils/stream_subscriber_mixin.dart:15:33)
#7      new FirebaseSortedList (package:firebase_database/ui/firebase_sorted_list.dart:32:5)
#8      FirebaseAnimatedListState.didChangeDependencies (package:firebase_database/ui/firebase_animated_list.dart:143<…>
```
and app does not fetch data from firebase database.

## Flutter Doctor
```
flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale pl-PL)
    • Flutter version 0.1.5 at /Users/bartolini/workspace-private/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bartolini/Library/Android/sdk
    • Android NDK at /Users/bartolini/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio 3.1-rc.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 3.1-rc.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 6.0 (API 23) (emulator)
    • iPhone X                  • A148EE0D-0C6C-4786-BBE1-258E11548992 • ios         • iOS 11.2 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Please try `flutter channel dev` `flutter doctor`
`beta` is a bit dated already. I guess a new one will be released soon.

**Comment by bartektartanus** [comment]
Thanks, that helped, closing. :)
