### ISSUE TITLE
[go_router] Navigating to a route in shell route, pop the route, then navigate to another route in the shell route causes Multiple widgets used the same GlobalKey error when using Globalkey<NavigatorState>

### ISSUE THREAD

**Issue by mironsaid** [flutter/flutter#159262]
### Steps to reproduce

1. Push a route in a shell route that has a GlobalKey<NavigatorState>
2. Pop that route
3. Push another route inside that shell route

### Expected results

I expected that this works exactly as

final result = await Navigator.push(...)
if (result != null) {
await Navigator.push(...)
Navigator.pop(..);
}

### Actual results

Errors, black screen, but once I hot reload it works

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final class GoFadeTransition<T> extends CustomTransitionPage<T> {
  GoFadeTransition({
    required super.child,
    super.transitionDuration = const Duration(milliseconds: 250),
  }) : super(
    transitionsBuilder: (context, animation, secondaryAnimation, child) => FadeTransition(
      opacity: animation,
      child: child,
    ),
  );
}

class MyRouter {
  const MyRouter._();

  static final _rootNavigatorKey = GlobalKey<NavigatorState>();
  static final _testNavigatorKey = GlobalKey<NavigatorState>();

  static GlobalKey<NavigatorState> rootNavigatorKey = _rootNavigatorKey;
  static GlobalKey<NavigatorState> testNavigatorKey = _testNavigatorKey;

  static final router = GoRouter(
    initialLocation: '/',
    debugLogDiagnostics: true,
    navigatorKey: _rootNavigatorKey,
    routes: [
      GoRoute(
        name: '/',
        path: '/',
        pageBuilder: (context, state) => GoFadeTransition(child: const RootPage()),
        routes: [
          ShellRoute(
            navigatorKey: _testNavigatorKey,
            pageBuilder: (context, state, child) => GoFadeTransition(child: child),
            routes: [
              GoRoute(
                name: 'test1',
                path: '/test1',
                pageBuilder: (context, state) => GoFadeTransition(child: const Test1()),
                routes: [
                  GoRoute(
                    name: 'test2',
                    path: '/test2',
                    pageBuilder: (context, state) => GoFadeTransition(child: const Test2()),
                  ),
                ],
              ),
            ],
          ),
          GoRoute(
              name: 'another-one',
              path: '/another-one',
              pageBuilder: (context, state) => GoFadeTransition(child: const AnotherOne()))
        ],
      ),
    ],
  );
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerDelegate: MyRouter.router.routerDelegate,
        routeInformationProvider: MyRouter.router.routeInformationProvider,
        routeInformationParser: MyRouter.router.routeInformationParser,
      );
}

class RootPage extends StatefulWidget {
  const RootPage({super.key});

  @override
  State<RootPage> createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () => context.pushNamed('another-one'),
            child: const Text('Go to another one'),
          ),
        ),
      );
}

class Test1 extends StatefulWidget {
  const Test1({super.key});

  @override
  State<Test1> createState() => _Test1State();
}

class _Test1State extends State<Test1> {
  @override
  Widget build(BuildContext context) => Center(
        child: ElevatedButton(
          onPressed: () {
            context.pop(true);
          },
          child: const Text('Go back to another one'),
        ),
      );
}

class Test2 extends StatefulWidget {
  const Test2({super.key});

  @override
  State<Test2> createState() => _Test2State();
}

class _Test2State extends State<Test2> {
  @override
  Widget build(BuildContext context) => const Center(child: Text('We are in test2'));
}

class AnotherOne extends StatefulWidget {
  const AnotherOne({super.key});

  @override
  State<AnotherOne> createState() => _AnotherOneState();
}

class _AnotherOneState extends State<AnotherOne> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              final result = await context.pushNamed<bool?>('test1');

              if (result case final _? when context.mounted) {
                await context.pushNamed(
                  'test2',
                );
                if (context.mounted) {
                  context.pop();
                }
              }
            },
            child: const Text('Do stuff with test1 & go to test 2'),
          ),
        ),
      );
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screen_recording_20241121_164101](https://github.com/user-attachments/assets/a6e86cfe-59b1-44ba-957b-c152fe3ddd42)

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [GlobalObjectKey int#bacd3] was used by multiple widgets. The parents of those widgets were:
- Semantics(container: false, properties: SemanticsProperties, renderObject: RenderSemanticsAnnotations#69446)
- Semantics(container: false, properties: SemanticsProperties, renderObject: RenderSemanticsAnnotations#d1108)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3113:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:3057:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:3052:36)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:3121:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3178:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3260:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1143:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#13     _invoke (dart:ui/hooks.dart:312:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#15     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-AE)
    • Flutter version 3.22.3 on channel stable at /Users/amirsaid/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (4 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/amirsaid/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@mironsaid 
Can you check if your case resembles [this](https://github.com/flutter/flutter/issues/112181) issue or not ?

**Comment by mironsaid** [comment]
Yes and no.

Yes that the global key problem that occurs is similar to that issue.

No that despite removing the fade animation and despite having already done this with Navigator 1.0 with a separate navigator instance with its own global key with the fade transition worked well before migrating to go_router.

**Comment by darshankawar** [comment]
@mironsaid 
Upon running your code with latest stable version on Android, it gives me below error:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building MyApp(dirty):
sub-route path may not start or end with "/": GoRoute#a42b7(name: "test1", path: "/test1")
'package:go_router/src/configuration.dart':
Failed assertion: line 43 pos 18: '!route.path.startsWith('/') && !route.path.endsWith('/')'
```

**Comment by mironsaid** [comment]
```import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final class GoFadeTransition<T> extends CustomTransitionPage<T> {
  GoFadeTransition({
    required super.child,
    super.transitionDuration = const Duration(milliseconds: 250),
  }) : super(transitionsBuilder: (context, animation, secondaryAnimation, child) => child
            // FadeTransition(
            //   opacity: animation,
            //   child: child,
            // ),
            );
}

class MyRouter {
  const MyRouter._();

  static final _rootNavigatorKey = GlobalKey<NavigatorState>();
  static final _testNavigatorKey = GlobalKey<NavigatorState>();

  static GlobalKey<NavigatorState> rootNavigatorKey = _rootNavigatorKey;
  static GlobalKey<NavigatorState> testNavigatorKey = _testNavigatorKey;

  static final router = GoRouter(
    initialLocation: '/',
    debugLogDiagnostics: true,
    navigatorKey: _rootNavigatorKey,
    routes: [
      GoRoute(
        name: '/',
        path: '/',
        pageBuilder: (context, state) => GoFadeTransition(child: const RootPage()),
        routes: [
          ShellRoute(
            navigatorKey: _testNavigatorKey,
            pageBuilder: (context, state, child) => GoFadeTransition(child: child),
            routes: [
              GoRoute(
                name: 'test1',
                path: 'test1',
                pageBuilder: (context, state) => GoFadeTransition(child: const Test1()),
                routes: [
                  GoRoute(
                    name: 'test2',
                    path: 'test2',
                    pageBuilder: (context, state) => GoFadeTransition(child: const Test2()),
                  ),
                ],
              ),
            ],
          ),
          GoRoute(
              name: 'another-one',
              path: 'another-one',
              pageBuilder: (context, state) => GoFadeTransition(child: const AnotherOne()))
        ],
      ),
    ],
  );
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerDelegate: MyRouter.router.routerDelegate,
        routeInformationProvider: MyRouter.router.routeInformationProvider,
        routeInformationParser: MyRouter.router.routeInformationParser,
      );
}

class RootPage extends StatefulWidget {
  const RootPage({super.key});

  @override
  State<RootPage> createState() => _RootPageState();
}

class _RootPageState extends State<RootPage> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () => context.pushNamed('another-one'),
            child: const Text('Go to another one'),
          ),
        ),
      );
}

class Test1 extends StatefulWidget {
  const Test1({super.key});

  @override
  State<Test1> createState() => _Test1State();
}

class _Test1State extends State<Test1> {
  @override
  Widget build(BuildContext context) => Center(
        child: Scaffold(
          body: Center(
            child: ElevatedButton(
              onPressed: () {
                context.pop(true);
              },
              child: const Text('Go back to another one'),
            ),
          ),
        ),
      );
}

class Test2 extends StatefulWidget {
  const Test2({super.key});

  @override
  State<Test2> createState() => _Test2State();
}

class _Test2State extends State<Test2> {
  @override
  Widget build(BuildContext context) => const Center(child: Text('We are in test2'));
}

class AnotherOne extends StatefulWidget {
  const AnotherOne({super.key});

  @override
  State<AnotherOne> createState() => _AnotherOneState();
}

class _AnotherOneState extends State<AnotherOne> {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              final result = await context.pushNamed<bool?>('test1');

              if (result case final _? when context.mounted) {
                await context.pushNamed(
                  'test2',
                );
                if (context.mounted) {
                  context.pop();
                }
              }
            },
            child: const Text('Do stuff with test1 & go to test 2'),
          ),
        ),
      );
}

```

Despite the fixes added, the global key problem still exists.

**Comment by mironsaid** [comment]
@darshankawar Hi, can you suggest a possible alternative way to programmatically navigate in the same manner to avoid the key duplication problem for the time or should I go back to Navigator 1.0?

**Comment by darshankawar** [comment]
Check [this](https://github.com/flutter/flutter/issues/154759) if it helps in your case or not.

**Comment by mironsaid** [comment]
I have decided to stop using go router and instead use auto route. Thank you.
