### ISSUE TITLE
[tool_crash] Bad state: No definition of type String

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#159236]
## Command
```sh
flutter analyze
```

## Steps to Reproduce
1. run `flutter analyze` 

## Logs

```console
Error from the analysis server: Internal error: Bad state: No definition of type String
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:590:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:598:19)
#2      TypeProviderImpl.stringType (package:analyzer/src/dart/element/type_provider.dart:492:28)
#3      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:231:41)
#4      ResolverVisitor.visitSimpleStringLiteral (package:analyzer/src/generated/resolver.dart:3668:18)
#5      SimpleStringLiteralImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:16303:14)
#6      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:763:16)
#7      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:564:9)
#8      InvocationInferrer._visitArguments (package:analyzer/src/dart/resolver/invocation_inferrer.dart:568:18)
#9      FullInvocationInferrer.resolveInvocation (package:analyzer/src/dart/resolver/invocation_inferrer.dart:247:36)
#10     InstanceCreationExpressionResolver._resolveInstanceCreationExpression (package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:70:10)
#11     InstanceCreationExpressionResolver.resolve (package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:49:5)
#12     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:3049:41)
#13     InstanceCreationExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:10511:14)
#14     ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:763:16)
#15     TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:564:9)
#16     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:115:22)
#17     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
#18     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9133:28)
#19     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
#20     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
#21     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
#22     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
<asynchronous suspension>
#23     Linker.link.<anonymous closure> (package:analyzer/src/summary2/link.dart:123:7)
<asynchronous suspension>
#24     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#25     Linker.link (package:analyzer/src/summary2/link.dart:122:5)
<asynchronous suspension>
#26     link (package:analyzer/src/summary2/link.dart:41:3)
<asynchronous suspension>
#27     LibraryContext.load.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:197:22)
<asynchronous suspension>
#28     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#29     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:194:24)
<asynchronous suspension>
#30     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#31     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#32     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#34     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#35     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>



#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:411:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:11)
<asynchronous suspension>
#2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>


Unhandled exception:
Bad state: No definition of type String
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:590:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:598:19)
#2      TypeProviderImpl.stringType (package:analyzer/src/dart/element/type_provider.dart:492:28)
#3      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:231:41)
#4      ResolverVisitor.visitSimpleStringLiteral (package:analyzer/src/generated/resolver.dart:3668:18)
#5      SimpleStringLiteralImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:16303:14)
#6      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:763:16)
#7      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:564:9)
#8      InvocationInferrer._visitArguments (package:analyzer/src/dart/resolver/invocation_inferrer.dart:568:18)
#9      FullInvocationInferrer.resolveInvocation (package:analyzer/src/dart/resolver/invocation_inferrer.dart:247:36)
#10     InstanceCreationExpressionResolver._resolveInstanceCreationExpression (package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:70:10)
#11     InstanceCreationExpressionResolver.resolve (package:analyzer/src/dart/resolver/instance_creation_expression_resolver.dart:49:5)
#12     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:3049:41)
#13     InstanceCreationExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:10511:14)
#14     ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:763:16)
#15     TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:564:9)
#16     AstResolver.resolveExpression (package:analyzer/src/summary2/ast_resolver.dart:115:22)
#17     _PropertyInducingElementTypeInference.perform (package:analyzer/src/summary2/top_level_inference.dart:263:17)
#18     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9133:28)
#19     _InitializerInference.perform (package:analyzer/src/summary2/top_level_inference.dart:153:15)
#20     TopLevelInference.infer (package:analyzer/src/summary2/top_level_inference.dart:106:26)
#21     Linker._performTopLevelInference (package:analyzer/src/summary2/link.dart:424:29)
#22     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:268:5)
<asynchronous suspension>
#23     Linker.link.<anonymous closure> (package:analyzer/src/summary2/link.dart:123:7)
<asynchronous suspension>
#24     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#25     Linker.link (package:analyzer/src/summary2/link.dart:122:5)
<asynchronous suspension>
#26     link (package:analyzer/src/summary2/link.dart:41:3)
<asynchronous suspension>
#27     LibraryContext.load.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:197:22)
<asynchronous suspension>
#28     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#29     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:194:24)
<asynchronous suspension>
#30     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#31     LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#32     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#34     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#35     AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:411:5)
#1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:11)
<asynchronous suspension>
#2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
<asynchronous suspension>
#4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
<asynchronous suspension>
#5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
<asynchronous suspension>
#7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
<asynchronous suspension>
Analyzing bestie-app...

Oops; flutter has exited unexpectedly: "Exception: analysis server exited with code 255 and output:
[stderr]
[stderr] #0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:411:5)
[stderr] #1      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:208:11)
[stderr] <asynchronous suspension>
[stderr] #2      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
[stderr] <asynchronous suspension>
[stderr] #3      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:144:9)
[stderr] <asynchronous suspension>
[stderr] #4      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:282:7)
[stderr] <asynchronous suspension>
[stderr] #5      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
[stderr] <asynchronous suspension>
[stderr] #6      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:273:5)
[stderr] <asynchronous suspension>
[stderr] #7      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1967:5)
[stderr] <asynchronous suspension>
[stderr] #8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1252:7)
[stderr] <asynchronous suspension>
[stderr] #9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2446:7)
[stderr] <asynchronous suspension>".
```

```
$ flutter doctor -v

[✓] Flutter (Channel beta, 3.27.0-0.2.pre, on macOS 15.1 24B83 darwin-x64, locale en-GB)
    • Flutter version 3.27.0-0.2.pre on channel beta at /Users/olostan/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc011960a2 (6 days ago), 2024-11-14 12:19:18 -0800
    • Engine revision 397deba30f
    • Dart version 3.6.0 (build 3.6.0-334.4.beta)
    • DevTools version 2.40.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/olostan/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • Pixel 7 (mobile) • 34251FDH2007NM • android-arm64  • Android 15 (API 35)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 15.1 24B83 darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 132.0.6834.6 beta

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by olostan** [comment]
Similar report https://github.com/flutter/flutter/issues/155875

**Comment by olostan** [comment]
same issue after `flutter clean`

**Comment by darshankawar** [comment]
I was not able to replicate this error, but based on the report and error log, I will keep the issue open for team's tracking.

**Comment by olostan** [comment]
Switching from beta to stable and clearing pub cache helped.

**Comment by a-siva** [comment]
> Switching from beta to stable and clearing pub cache helped.

I presume that means you are on Flutter 3.24 now and we still have the issue with Flutter 3.27

**Comment by a-siva** [comment]
//cc @srawlins @bwilkerson Seems like an Analyzer crash, could somebody from the Analyzer team take a look

**Comment by a-siva** [comment]
@bwilkerson or @srawlins any updates on this issue ?

**Comment by srawlins** [comment]
I'm unfamiliar with that area of the code. @scheglov or @bwilkerson do you know what that error might indicate?

**Comment by bwilkerson** [comment]
The stack trace suggests that we might have been unable to find the `dart:core` library. I don't know off hand why that would happen unless the installed SDK isn't in the expected format for some reason.

**Comment by scheglov** [comment]
Yes, maybe Dart SDK is not there, or in process of being updated, so incomplete.

**Comment by a-siva** [comment]
Sounds like an user error and things are working as intended, closing issue.
