### ISSUE TITLE
EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK only outputs ═════.. in vscode if test is outside of test folder

### ISSUE THREAD

**Issue by lewinpauli** [flutter/flutter#159264]
### Steps to reproduce

when writing a test that throws an exception in vscode only these lines : "═════" are the output, instead of the expected result if the test file is outside of the /test folder or its sub directories (the debug console displays the correct exception, but as you can see in the screenshot inside vscode file the exception only displays "═════"... )

I had the test inside /integration_test folder and only figured out that it has something todo with the file location, while creating a test project for this github issue

I dont think this is expected behavior because the test run fine outside of the /test folder

And the official tutorial is also creating the integration tests inside /integration_test
https://docs.flutter.dev/testing/integration-tests#create-the-integration-test-files 

when someone is working on the testing part on flutter maybe also take a look at this
https://github.com/flutter/flutter/issues/159276
https://github.com/flutter/flutter/issues/159284

### Expected results

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "Found 0 widgets with key [<'NotExistingKey'>]: []" (used in a call to "tap()") could not
find any matching widgets.

### Actual results

════════════════════════════════════════════════════════════════════════════════════════════════════

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

Future<void> main() async {
  group(
    "integration test",
    () {
      testWidgets("test1", (WidgetTester tester) async {
        await tester.tap(find.byKey(Key("NotExistingKey")));
      });
    },
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/ff687920-9df4-486e-aeb5-478c4379d5cd)

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter test integration_test/test_test.dart  --verbose
[   +9 ms] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +35 ms] Found 1 files which will be executed as Integration Tests.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: /home/lpauli/Android/Sdk/platform-tools/adb devices -l
[  +52 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] Skipping pub get: version match.
[  +51 ms] Found plugin integration_test at /home/lpauli/Desktop/projects/flutter/packages/integration_test/
[  +65 ms] Found plugin integration_test at /home/lpauli/Desktop/projects/flutter/packages/integration_test/
[  +39 ms] Found plugin integration_test at /home/lpauli/Desktop/projects/flutter/packages/integration_test/
[   +2 ms] Generating /home/lpauli/Desktop/projects/debugging_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +143 ms] Connected devices:
[  +64 ms] Linux (desktop) • linux  • linux-x64      • Fedora Linux 41 (Workstation Edition) 6.11.8-300.fc41.x86_64
[        ] Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.85
[        ] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[        ] Please choose one (or "q" to quit)
[        ] : 
[+1522 ms] 1
[   +5 ms] running test package with arguments: [--concurrency=1, --chain-stack-traces, --, file:///home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart?]
00:00 +0: loading /home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart                                                                                   [ +146 ms] test 0: starting test /home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart
[   +7 ms] Stopping scan for flutter_test_config.dart; found project root at /home/lpauli/Desktop/projects/debugging_flutter
[   +1 ms] test 0: starting test device
[   +4 ms] test 0: awaiting connection to test device
[  +22 ms] Building Linux application...
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/lpauli/Desktop/projects/debugging_flutter/linux
[  +47 ms] -- Configuring done (0.0s)
[  +13 ms] -- Generating done (0.0s)
[        ] -- Build files have been written to: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug
[  +30 ms] executing: ninja -C build/linux/x64/debug install
[  +16 ms] ninja: Entering directory `build/linux/x64/debug'
00:07 +0: loading /home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart                                                                                   [+7690 ms] [1/5] Generating /home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/lpauli/Desktop/projects/debugging_flutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +7 ms] [   +8 ms] executing: uname -m
[        ] [   +8 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +46 ms] Initializing file store
[        ] [  +15 ms] Skipping target: gen_localizations
[        ] [   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/package_config_subset}
[        ] [   +4 ms] unpack_linux: Starting due to {}
[        ] [  +69 ms] unpack_linux: Complete
[        ] [ +503 ms] Found plugin integration_test at /home/lpauli/Desktop/projects/flutter/packages/integration_test/
[        ] [   +5 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot_program: Starting due to {}
[   +2 ms] [   +6 ms] /home/lpauli/Desktop/projects/flutter/bin/cache/dart-sdk/bin/dartaotruntime --disable-dart-dev
/home/lpauli/Desktop/projects/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server_aot.dart.snapshot --sdk-root
/home/lpauli/Desktop/projects/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DINTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/package_config.json --output-dill
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/program.dill --depfile
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/kernel_snapshot_program.d --incremental --initialize-from-dill
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/program.dill --verbosity=error
file:///tmp/flutter_tools.VLKUMN/flutter_test_listener.WYVMHX/listener.dart
[   +1 ms] [+5001 ms] kernel_snapshot_program: Complete
[        ] [ +524 ms] native_assets: Starting due to {}
[        ] [  +12 ms] No packages with native assets. Skipping native assets compilation.
[        ] [        ] Writing native_assets.yaml.
[        ] [  +11 ms] Writing /home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/native_assets.yaml done.
[        ] [        ] native_assets: Complete
[   +1 ms] [   +1 ms] kernel_snapshot_native_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/native_assets.yaml,/home/lpauli/Desktop/projects/debugging_flutter/.dart_to
ol/package_config_subset,/home/lpauli/Desktop/projects/flutter/packages/flutter_tools/lib/src/build_system/targets/common.dart,/home/lpauli/Desktop/projects/flutter/bin/internal/eng
ine.version,/home/lpauli/Desktop/projects/flutter/bin/internal/engine.version,/home/lpauli/Desktop/projects/flutter/bin/internal/engine.version,/home/lpauli/Desktop/projects/flutter
/bin/internal/engine.version}
[   +1 ms] [   +1 ms] kernel_snapshot_native_assets: Complete
[        ] [        ] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flutter_build/64234d3d458838576ad0520a6e8d080e/program.dill,/home/lpauli/Desktop/projects/debugging_flutter/.dart_tool/flu
tter_build/64234d3d458838576ad0520a6e8d080e/native_assets.dill}
[        ] [  +20 ms] kernel_snapshot: Complete
[        ] [        ] debug_bundle_linux-x64_assets: Starting due to {}
[        ] [ +141 ms] shaderc command: [/home/lpauli/Desktop/projects/flutter/bin/cache/artifacts/engine/linux-x64/impellerc, --sksl, --runtime-stage-gles, --runtime-stage-vulkan,
--iplr, --sl=/home/lpauli/Desktop/projects/debugging_flutter/build/flutter_assets/shaders/ink_sparkle.frag,
--spirv=/home/lpauli/Desktop/projects/debugging_flutter/build/flutter_assets/shaders/ink_sparkle.frag.spirv,
--input=/home/lpauli/Desktop/projects/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/home/lpauli/Desktop/projects/flutter/packages/flutter/lib/src/material/shaders,
--include=/home/lpauli/Desktop/projects/flutter/bin/cache/artifacts/engine/linux-x64/shader_lib]
[   +1 ms] [ +374 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +429 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 7,264ms.
[        ] [  +85 ms] ensureAnalyticsSent: 54ms
[        ] [        ] Running 1 shutdown hook
[        ] [        ] Shutdown hooks complete
[        ] [   +9 ms] exiting with code 0
00:08 +0: loading /home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart                                                                                   [ +405 ms] [2/5] Building CXX object CMakeFiles/debugging_flutter.dir/flutter/generated_plugin_registrant.cc.o
[  +28 ms] [3/5] Building CXX object CMakeFiles/debugging_flutter.dir/my_application.cc.o
[ +124 ms] [4/5] Linking CXX executable intermediates_do_not_run/debugging_flutter
[        ] [4/5] Install the project...
[   +5 ms] -- Install configuration: "Debug"
[  +10 ms] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/debugging_flutter
[   +9 ms] -- Set non-toolchain portion of runtime path of "/home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/debugging_flutter" to "$ORIGIN/lib"
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[        ] -- Up-to-date: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/lib
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/lib/native_assets.yaml
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/shaders
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/shaders/ink_sparkle.frag
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.bin
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/lpauli/Desktop/projects/debugging_flutter/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[  +23 ms] Building Linux application... (completed in 8.4s)
[   +2 ms] ✓ Built build/linux/x64/debug/bundle/debugging_flutter
[ +231 ms] VM Service URL on device: http://127.0.0.1:45757/77FtgaqQLgM=/
[   +1 ms] test 0: Connecting to vm service
[   +4 ms] test 0: VM Service uri is available at http://127.0.0.1:45757/77FtgaqQLgM=/
[ +108 ms] test 0: Finding the correct isolate with the integration test service extension
[  +47 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:09 +0: end-to-end test test1                                                                                                                                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "Found 0 widgets with key [<'NotExistingKey'>]: []" (used in a call to "tap()") could not
find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1892:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1792:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:1040:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart:15:20)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  test1
════════════════════════════════════════════════════════════════════════════════════════════════════
00:09 +0 -1: end-to-end test test1 [E]                                                                                                                                              
  Test failed. See exception logs above.
  The test description was: test1
  

To run this test again: /home/lpauli/Desktop/projects/flutter/bin/cache/dart-sdk/bin/dart test /home/lpauli/Desktop/projects/debugging_flutter/integration_test/test_test.dart -p vm --plain-name 'end-to-end test test1'
00:09 +0 -1: (tearDownAll)                                                                                                                                                          [ +837 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[        ] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Test process is no longer needed by test harness
[        ] test 0: deleting temporary directory
[        ] test 0: finished
00:09 +0 -1: Some tests failed.                                                                                                                                                     
[   +7 ms] test package returned with exit code 1
[   +1 ms] Runtime for phase TestRunner: Wall-clock: 0:00:09.870390; combined: 0:00:09.870413.
[        ] Runtime for phase Compile: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase Run: Wall-clock: 0:00:09.698803; combined: 0:00:09.698820.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.000000; combined: 0:00:00.000000.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:00.000061; combined: 0:00:00.000062.
[   +2 ms] "flutter test" took 11,936ms.
[  +44 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:641:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[  +63 ms] ensureAnalyticsSent: 60ms
[        ] Running 2 shutdown hooks
[        ] Shutdown hooks complete
[   +5 ms] exiting with code 1
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on Fedora Linux 41 (Workstation Edition) 6.11.8-300.fc41.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@lewinpauli 
Can you provide the project structure ? If I understand, you have integration_test folder and tests are outside of the folder ?

**Comment by lewinpauli** [comment]
integration_test and test folder are both in the root of the project
relative file paths:

/integration_test
/test

**Comment by lewinpauli** [comment]
I also need to mention that this is just a vscode/flutter extension bug (as far as I can tell), the debug console shows the correct exception.

If this is the wrong place for this issue, please let me know where to open it correctly.

**Comment by darshankawar** [comment]
> his is just a vscode/flutter extension bug (as far as I can tell), the debug console shows the correct exception.
> 
> If this is the wrong place for this issue, please let me know where to open it correctly.

Please file it here https://github.com/Dart-Code/Dart-Code/issues

Closing this issue.
