### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#15937]
## Steps to Reproduce

Similar to #13921

Call one of 
```dart
ImagePicker.pickImage(source: ImageSource.camera));
ImagePicker.pickImage(source: ImageSource.camera));
```

When called the first time it requests permission to camera or storage and the permissions are enabled in the application info.

This worked already a few days ago. Might be a Flutter upgrade that caused it. 

```
[        ] E/AndroidRuntime( 9268): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2345, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.lookatyou.lookatmybaby/com.lookatyou.lookatmybaby.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
[        ] E/AndroidRuntime( 9268): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 9268): 	at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[        ] E/AndroidRuntime( 9268): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 9268): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime( 9268): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[        ] E/AndroidRuntime( 9268): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
[        ] E/AndroidRuntime( 9268): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
[        ] E/AndroidRuntime( 9268): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
[        ] E/AndroidRuntime( 9268): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
[        ] E/AndroidRuntime( 9268): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onRequestPermissionsResult(ImagePickerPlugin.java:171)
[        ] E/AndroidRuntime( 9268): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:175)
[        ] E/AndroidRuntime( 9268): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
[        ] E/AndroidRuntime( 9268): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:117)
[        ] E/AndroidRuntime( 9268): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7429)
[        ] E/AndroidRuntime( 9268): 	at android.app.Activity.dispatchActivityResult(Activity.java:7280)
[        ] E/AndroidRuntime( 9268): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
[        ] E/AndroidRuntime( 9268): 	... 9 more
```

```
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1"
```
## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

```
 (dart2) $ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.2-pre.5, on Mac OS X 10.13.3 17D102, locale en-AT)
    • Flutter version 0.2.2-pre.5 at /Users/zoechi/flutter/flutter
    • Framework revision 0608a7a2cc (3 days ago), 2018-03-23 11:10:37 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
I don't think this is still an issue.

**Comment by zoechi** [comment]
Dup of #16164
