### ISSUE TITLE
ListTile Crashes When Width Is Reduced with Leading or Trailing Widgets

### ISSUE THREAD

**Issue by atillayurtseven** [flutter/flutter#159380]
When using the ListTile widget in a Flutter application on macOS, the app crashes if the window width is reduced and the ListTile contains a leading or trailing widget. This issue is reproducible consistently and seems related to how the widget handles layout constraints during window resizing.

### Steps to reproduce

1. Create a Flutter app targeting macOS.
2. Add a ListTile widget with either a leading or trailing widget.
3. Run the app and gradually reduce the width of the window.
4. Observe that the app crashes when the window reaches a certain narrow width.

### Expected results

The ListTile should adapt gracefully to changing window sizes without crashing, regardless of whether leading or trailing widgets are present.

### Actual results

The application crashes as the window width decreases when a ListTile contains leading or trailing widgets. The crash appears to be related to layout constraints.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:portfolio/providers.dart';

class Homepage extends ConsumerWidget {
  const Homepage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final portfolio = ref.watch(portfolioProvider);

    return ListView.builder(
      shrinkWrap: true,
      itemCount: portfolio.length,
      itemBuilder: (context, index) {
        final stock = portfolio[index];
        return ListTile(
          title: Text(
            stock.name,
            overflow: TextOverflow.ellipsis,
          ),
          subtitle: Text(
            "Qty: ${stock.quantity}",
            overflow: TextOverflow.ellipsis,
          ),
          trailing: Text("Price: ${stock.price}"),
        );
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
_AssertionError._doThrowNew (/Users/ates/development/flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/errors_patch.dart:50)
_AssertionError._throwNew (/Users/ates/development/flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/errors_patch.dart:40)
_RenderListTile._computeSizes (/Users/ates/development/flutter/packages/flutter/lib/src/material/list_tile.dart:1356)
_RenderListTile.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/material/list_tile.dart:1459)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderPadding.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/shifted_box.dart:234)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderPadding.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/shifted_box.dart:234)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)
RenderObject.layout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/object.dart:2608)
RenderProxyBoxMixin.performLayout (/Users/ates/development/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:111)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@atillayurtseven 
The code sample you provided contains third party implementation. Does the reported behavior occur without using those packages code ? If so, please provide us updated code sample along with `flutter doctor -v`.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by darshankawar** [comment]
Thanks for the update @atillayurtseven 
The error log mentions / suggests why it could be occuring with a hint on how to fix it.

```
The following assertion was thrown during performLayout():
Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing
ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1356 pos 7: 'tileWidth != trailingSize?.width || tileWidth == 0.0'

```

Try to use `SizedBox` widget and follow the link mentioned of the example to see if it helps in your case or not.

**Comment by darshankawar** [comment]
Thanks for checking. As the error log points to https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4 which I tried and doesn't throw the said error. Please try to see its implementation and check if it helps in your case or not.

**Comment by atillayurtseven** [comment]
I have tried the ListTile.4 code in my Mac app and same problem occurs.

Please find the full code and the `flutter doctor -v` output below.

```
import 'package:flutter/material.dart';

/// Flutter code sample for [ListTile].

void main() => runApp(const ListTileApp());

class ListTileApp extends StatelessWidget {
  const ListTileApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const ListTileExample(),
    );
  }
}

class ListTileExample extends StatelessWidget {
  const ListTileExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('ListTile Sample')),
      body: ListView(
        children: const <Widget>[
          ListTile(
            leading: CircleAvatar(child: Text('A')),
            title: Text('Headline'),
            subtitle: Text('Supporting text'),
            trailing: Icon(Icons.favorite_rounded),
          ),
          Divider(height: 0),
          ListTile(
            leading: CircleAvatar(child: Text('B')),
            title: Text('Headline'),
            subtitle: Text(
                'Longer supporting text to demonstrate how the text wraps and how the leading and trailing widgets are centered vertically with the text.'),
            trailing: Icon(Icons.favorite_rounded),
          ),
          Divider(height: 0),
          ListTile(
            leading: CircleAvatar(child: Text('C')),
            title: Text('Headline'),
            subtitle: Text(
                "Longer supporting text to demonstrate how the text wraps and how setting 'ListTile.isThreeLine = true' aligns leading and trailing widgets to the top vertically with the text."),
            trailing: Icon(Icons.favorite_rounded),
            isThreeLine: true,
          ),
          Divider(height: 0),
        ],
      ),
    );
  }
}
```

`flutter doctor -v` output

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale tr-TR)
    • Flutter version 3.24.4 on channel stable at /Users/atillayurtseven/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/atillayurtseven/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/atillayurtseven/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
(base) atillayurtseven@10 portfolio % 
 *  History restored 

(base) atillayurtseven@10 portfolio % flutter doctor -v
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1.1 24B91 darwin-arm64, locale tr-TR)
    • Flutter version 3.24.4 on channel stable at /Users/atillayurtseven/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/atillayurtseven/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2023.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/atillayurtseven/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
In above code, if you update as below, then the said error doesn't occur:

```
trailing: SizedBox(
              child: Icon(Icons.favorite_rounded),
            ),
```

**Comment by darshankawar** [comment]
> are you trying this on macOS simulator?

I've been running on macos desktop platform (flutter run -d macos), I don't think there's a macOS simulator, but coming back to the issue, I do see the crash log on latest sdk versions (stable and master), as shown below:


https://github.com/user-attachments/assets/8d573106-19a3-4ab0-aee3-0f3b5bafb959


```
stable : 3.24.5
master : 3.27.0-1.0.pre.669
```

<details>
<summary> crash log </summary>

```

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile
with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1350 pos 7: 'tileWidth != leadingSize?.width || tileWidth == 0.0'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
  ListTile ListTile:file:///Users/dhs/Documents/NCFlutter/integration_dummy/lib/main.dart:28:11

When the exception was thrown, this was the stack:
#2      _RenderListTile._computeSizes (package:flutter/src/material/list_tile.dart:1350:7)
#3      _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1459:27)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#7      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#23     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:211:28)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#25     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:121:12)
#26     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:327:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#28     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
#29     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
#30     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#47     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#59     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#60     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1092:7)
#61     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#62     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#67     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1448:11)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#75     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:61:11)
#76     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
#77     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#90     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3728:13)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#94     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1002:13)
#95     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1311:9)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#104    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#107    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#113    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#116    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#118    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#120    RenderView.performLayout (package:flutter/src/rendering/view.dart:281:14)
#121    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#122    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#123    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#124    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#129    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#130    _invoke (dart:ui/hooks.dart:312:13)
#131    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#132    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: _RenderListTile#ddb38 relayoutBoundary=up12 NEEDS-PAINT:
  creator: _ListTile ← IconButtonTheme ← IconTheme ← Builder ← MediaQuery ← Padding ← SafeArea ←
    Builder ← Padding-[GlobalKey#27fbd] ← Ink ← Semantics ← Listener ← ⋯
  parentData: offset=Offset(16.0, 0.0) (can use size)
  constraints: BoxConstraints(w=36.0, 0.0<=h<=Infinity)
  size: Size(41.0, 488.0)
This RenderObject had the following descendants (showing up to depth 5):
    leading: RenderConstrainedBox#29432 relayoutBoundary=up13 NEEDS-PAINT
      child: RenderConstrainedBox#d19fb relayoutBoundary=up14 NEEDS-PAINT
        child: RenderDecoratedBox#00b5d NEEDS-PAINT
          child: RenderPadding#d676a NEEDS-PAINT
            child: RenderPositionedBox#56c42 NEEDS-PAINT
    title: RenderParagraph#bee5f relayoutBoundary=up13 NEEDS-PAINT
      text: TextSpan
    subtitle: RenderParagraph#a0553 relayoutBoundary=up13 NEEDS-PAINT
      text: TextSpan
    trailing: RenderConstrainedBox#13035 relayoutBoundary=up13 NEEDS-PAINT
      child: RenderSemanticsAnnotations#40441 relayoutBoundary=up14 NEEDS-PAINT
        child: RenderExcludeSemantics#201d0 relayoutBoundary=up15 NEEDS-PAINT
          child: RenderConstrainedBox#878e8 relayoutBoundary=up16 NEEDS-PAINT
            child: RenderPositionedBox#852bd
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
Another exception was thrown: Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)

```

</details>

I also tried using the suggestions as mentioned in the error log, but it still gives same result.

**Comment by TahaTesser** [comment]
Here is a simplified code sample reproducing this bug 

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: ListTileSample(),
    );
  }
}

class ListTileSample extends StatefulWidget {
  const ListTileSample({super.key});

  @override
  ListTileSampleState createState() => ListTileSampleState();
}

class ListTileSampleState extends State<ListTileSample> {
  bool _isExpanded = true;

  void _toggleExpansion() {
    setState(() {
      _isExpanded = !_isExpanded;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          spacing: 16,
          mainAxisSize: MainAxisSize.min,
          children: [
            AnimatedContainer(
              duration: Durations.medium4,
              width: _isExpanded ? 300 : 80,
              child: _isExpanded
                  ? const ListTile(
                      title: Text('Tile'),
                      tileColor: Colors.amber,
                      trailing: SizedBox(
                        width: 60,
                        child: Icon(Icons.arrow_drop_down),
                      ),
                    )
                  : const Placeholder(
                      fallbackHeight: 48,
                      fallbackWidth: 300,
                    ),
            ),
            ElevatedButton(
              onPressed: _toggleExpansion,
              child: Text(_isExpanded ? 'Collapse' : 'Expand'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>
