### ISSUE TITLE
Exception of form.validate()

### ISSUE THREAD

**Issue by pashya98** [flutter/flutter#15933]
**form.validate()**
=====================================================================
```dart
class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => new _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final scaffoldKey = new GlobalKey<ScaffoldState>();
  final formKey = new GlobalKey<FormState>();

  String _email;
  String _password;
```
  
after submitting if we submitting correct value, we are getting an exception 
```dart
void _submit() {
    final form = formKey.currentState;

    if (form.validate()) {
      form.save();

      // Email & password matched our validation rules
      // and are saved to _email and _password fields.
      _performLogin();
    }
  }
```
```dart
  void _performLogin() {
    // This is just a demo, so no actual login here.
    final snackbar = new SnackBar(
      content: new Text('Email: $_email, password: $_password'),
    );

    scaffoldKey.currentState.showSnackBar(snackbar);
  }
```

```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: scaffoldKey,
      appBar: new AppBar(
        title: new Text('Validating forms'),
      ),
      body: new Padding(
        padding: const EdgeInsets.all(16.0),
        child: new Form(
          key: formKey,
          child: new Column(
            children: [
              new TextFormField(
                decoration: new InputDecoration(labelText: 'Your email'),
                validator: (val) =>
                !val.contains('@') ? 'Not a valid email.' : null,
                onSaved: (val) => _email = val,
              ),
              new TextFormField(
                decoration: new InputDecoration(labelText: 'Your password'),
                validator: (val) =>
                val.length < 6 ? 'Password too short.' : null,
                onSaved: (val) => _password = val,
                obscureText: true,
              ),
              new RaisedButton(
                onPressed: _submit,
                child: new Text('Login'),),], ),),),);
  }
}
```
=======================================================================
but we have getting following exception,  after the submit correct value.........

```
I/flutter ( 2460): ══╡ EXCEPTION CAUGHT BY GESTURE ╞════
I/flutter ( 2460): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter ( 2460): Class 'FormState' has no instance getter 'ture'.
I/flutter ( 2460): Receiver: Instance of 'FormState'
I/flutter ( 2460): Tried calling: ture
I/flutter ( 2460): 
I/flutter ( 2460): When the exception was thrown, this was the stack:
I/flutter ( 2460): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter ( 2460): #1      FormState._validate (package:flutter/src/widgets/form.dart:138)
I/flutter ( 2460): #2      FormState.validate (package:flutter/src/widgets/form.dart:131)
I/flutter ( 2460): #3      _LoginPageState._submit (package:listview/list_details.dart:18)
I/flutter ( 2460): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478)
I/flutter ( 2460): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530)
I/flutter ( 2460): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
I/flutter ( 2460): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161)
I/flutter ( 2460): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94)
I/flutter ( 2460): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315)
I/flutter ( 2460): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
I/flutter ( 2460): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
I/flutter ( 2460): #12     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143)
I/flutter ( 2460): #13     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121)
I/flutter ( 2460): #14     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101)
I/flutter ( 2460): #15     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64)
I/flutter ( 2460): #16     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48)
I/flutter ( 2460): #17     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
I/flutter ( 2460): #18     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)
I/flutter ( 2460): 
I/flutter ( 2460): Handler: onTap
I/flutter ( 2460): Recognizer:
I/flutter ( 2460):   TapGestureRecognizer#d4b85(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter ( 2460):   Offset(191.7, 248.8), sent tap down)
I/flutter ( 2460): ════════════════════════════════════════════════════════════════
I/flutter ( 2460): Another exception was thrown: NoSuchMethodError: Class 'FormState' has no instance getter 'ture'.
I/flutter ( 2460): Another exception was thrown: NoSuchMethodError: Class 'FormState' has no instance getter 'ture'.
```
-------------------------------------------------------------------------------------

Download code from:  https://github.com/FlutterRocks/form-validation-sample

**Comment by zoechi** [comment]
Sorry for the late reply. Is this still an issue? 
Can you try `flutter clean` and then try again?

**Comment by abhisondagar605** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building CreateAccountPage(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#0560e]], state: _CreateAccountPageState#8ae4d):
The method 'validate' was called on null.
Receiver: null
Tried calling: validate()

The relevant error-causing widget was: 
  CreateAccountPage file:///C:/Users/Abhi%20Sondagar/AndroidStudioProjects/instagram_app/lib/pages/HomePage.dart:44:51
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CreateAccountPageState.submitUserName (package:instagramapp/pages/CreateAccountPage.dart:18:14)
#2      _CreateAccountPageState.build (package:instagramapp/pages/CreateAccountPage.dart:88:26)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
D/libc-netbsd(27927): [getaddrinfo]:  hostname=firestore.googleapis.com; servname=(null);   app_uid=10624; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0 from prox result 0
