### ISSUE TITLE
'elapsedInSeconds >= 0.0': is not true

### ISSUE THREAD

**Issue by liaochzh** [flutter/flutter#159319]
### Steps to reproduce

There will be an exception when switching between app tab pages

### Expected results

occur exeption

### Actual results

occur exeption

### Code sample

<details open><summary>Code sample</summary>

```dart
class MainPageModel {
  final ImageProvider icon;
  final ImageProvider? activeIcon;
  final String? title;
  final IndexedWidgetBuilder builder;
  final ValueNotifier<int>? badge;

  const MainPageModel({
    required this.icon,
    this.activeIcon,
    this.title,
    required this.builder,
    this.badge,
  });

  factory MainPageModel.normal(
    ImageProvider icon,
    String title,
    IndexedWidgetBuilder builder, {
    ValueNotifier<int>? badge,
    ImageProvider? activeIcon,
  }) =>
      MainPageModel(
        icon: icon,
        activeIcon: activeIcon,
        title: title.tr,
        badge: badge,
        builder: builder,
      );
}

///
class NormalMainPage extends StatefulWidget {
  final List<MainPageModel> list;
  final Color? selectedItemColor;
  final Color? unselectedItemColor;

  const NormalMainPage(this.list, {super.key, this.selectedItemColor, this.unselectedItemColor});

  @override
  State<StatefulWidget> createState() => _State();
}
///
class _State extends State<NormalMainPage> {
  late int _selectedIndex = 0;
  // 使用 List<Widget?> 存储页面，初始为 null 实现 lazy loading
  late final _pages = List<Widget?>.filled(widget.list.length, null, growable: false);

  Timer? _debounceTimer;

  // 防抖时间间隔（毫秒）
  late final Duration _debounceDuration = const Duration(milliseconds: 180);

  ///
  late final bottomItems = List<BottomNavigationBarItem>.generate(
    widget.list.length,
    (idx) {
      final e = widget.list[idx];
      final (icon, activeIcon) = _buildIconsItem(
        e.icon,
        e.badge,
        activeProvider: e.activeIcon,
        activeColor: widget.selectedItemColor,
      );
      return BottomNavigationBarItem(
        icon: icon,
        activeIcon: activeIcon,
        label: e.title,
      );
    },
    growable: false,
  );

  final key1 = GlobalKey();
  final key2 = GlobalKey();

  /////////////////////////////

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback(
      (_) => interfaceChannel.invokeMethod("vc.homePageDidLoad"),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _debounceTimer?.cancel();
    _debounceTimer = null;
    _pages.fillRange(0, _pages.length);
  }

  @override
  Widget build(BuildContext context) {
    final list = widget.list;
    _buildPage(_selectedIndex);
    //
    return Scaffold(
      body: IndexedStack(
        key: key1,
        index: _selectedIndex,
        children: List.generate(
          list.length,
          (idx) => _pages[idx] ?? const SizedBox.shrink(),
          growable: false,
        ),
      ),
      bottomNavigationBar: Material(
        key: key2,
        animationDuration: const Duration(milliseconds: 400),
        child: BottomNavigationBar(
          backgroundColor: AppColors.white,
          type: BottomNavigationBarType.fixed,
          selectedItemColor: widget.selectedItemColor,
          unselectedItemColor: widget.unselectedItemColor,
          elevation: 10,
          enableFeedback: false,
          // selectedIconTheme: widget.selectedItemColor != null ? IconThemeData(color: widget.selectedItemColor) : null,
          // unselectedIconTheme: widget.selectedItemColor != null ? IconThemeData(color: widget.unselectedItemColor) : null,
          selectedLabelStyle: TextStyle(
            fontSize: 10,
            fontWeight: FontWeight.w600,
            color: Colors.blue,
          ),
          unselectedLabelStyle: TextStyle(
            fontSize: 10,
            fontWeight: FontWeight.w600,
            color: Colors.pink,
          ),
          items: bottomItems,
          currentIndex: _selectedIndex,
          onTap: (idx) {
            // 相同的不处理
            if (idx == _selectedIndex) return;
            // 如果防抖计时器正在运行，直接返回，防止重复点击
            if (_debounceTimer?.isActive ?? false) return;
            // 设置防抖计时器
            _debounceTimer = Timer(_debounceDuration, () => _debounceTimer = null);
            // 设置 idx
            setState(() => _selectedIndex = idx);
          },
        ),
      ),
    );
  }

  ///
  (Widget, Widget) _buildIconsItem(
    ImageProvider iconProvider,
    ValueNotifier<int>? badge, {
    ImageProvider? activeProvider,
    Color? activeColor,
  }) {
    if (badge != null) {
      return _buildIconsBadgeItem(
        iconProvider,
        badge,
        activeProvider: activeProvider,
        activeColor: activeColor,
      );
    } else {
      return _buildIconsDefaultItem(
        iconProvider,
        activeProvider: activeProvider,
        activeColor: activeColor,
      );
    }
  }

  ///
  (Widget, Widget) _buildIconsDefaultItem(ImageProvider iconProvider,
      {ImageProvider? activeProvider, Color? activeColor}) {
    final Widget icon = _buildIcon(iconProvider);
    final Widget activeIcon;
    if (activeProvider == null) {
      activeIcon = _buildIcon(iconProvider, activeColor);
    } else {
      activeIcon = _buildIcon(activeProvider);
    }
    return (icon, activeIcon);
  }

  ///
  (Widget, Widget) _buildIconsBadgeItem(
    ImageProvider iconProvider,
    ValueNotifier<int> badge, {
    ImageProvider? activeProvider,
    Color? activeColor,
  }) {
    var (icon, activeIcon) =
        _buildIconsDefaultItem(iconProvider, activeProvider: activeProvider, activeColor: activeColor);

    ///
    Widget builder(BuildContext context, int value, Widget? child) => Badge.count(
          count: value,
          isLabelVisible: value > 0,
          offset: const Offset(7, -7),
          child: child,
        );
    //
    icon = ValueListenableBuilder(
      valueListenable: badge,
      builder: builder,
      child: icon,
    );
    activeIcon = ValueListenableBuilder(
      valueListenable: badge,
      builder: builder,
      child: activeIcon,
    );
    return (icon, activeIcon);
  }

  ///
  Widget _buildIcon(ImageProvider icon, [Color? color]) => Container(
        alignment: Alignment.center,
        width: 21,
        height: 23,
        padding: const EdgeInsets.only(bottom: 2),
        child: ImageIcon(icon, color: color),
      );

      // , color: color

  /// 页面切换时动态构建页面
  void _buildPage(int index) {
    if (_pages[index] != null) return;
    final page = widget.list[index].builder(context, index);
    _pages[index] = page;
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
#17     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
tap.dart:281
#18     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:271:25)
arena.dart:271
#19     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:251:31)
arena.dart:251
(elided 4 frames from class _FrameCallbackEntry and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1.1 24B91 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.4 on channel stable at /Users/lcr/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (4 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lcr/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.13+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (5 available)
    • SM S911U (mobile)               • RFCWA02FAND               • android-arm64  • Android 14 (API 34)
    • Charlie’s iPhone (mobile)       • 00008101-001620122232001E • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@liaochzh 
Please provide complete runnable reproducible code sample without third party package implementation (ex: main.dart) that triggers the error.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jtmcdole** [comment]
Logs stacktrace was cut off; unsure without it.
