### ISSUE TITLE
App does not work after flutter upgrade.

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#15943]
I just tried to upgrade flutter to 0.2.4
The engine upgrade worked but post upgrade flutter doctor reports errors and my app also does not work anymore.

# App execution error::

Launching lib/main.dart on iPhone X in debug mode...
[VERBOSE-2:dart_error.cc(16)] error: Unsupported tag at this point: 0.
[VERBOSE-2:dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.

# flutter doctor error ::
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.2.4, on Mac OS X 10.13.3 17D102, locale en-US)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 2f792ac750627b94)
Unhandled exception:
NoSuchMethodError: The method 'run' was called on null.
Receiver: null
Tried calling: run(Instance(length:2) of '_GrowableList', environment: null, workingDirectory: null)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      runAsync (package:flutter_tools/src/base/process.dart:227)
<asynchronous suspension>
#2      IOSWorkflow.macDevMode (package:flutter_tools/src/ios/ios_workflow.dart:45)
<asynchronous suspension>
#3      IOSWorkflow.validate (package:flutter_tools/src/ios/ios_workflow.dart:97)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Users/MBahl/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by manujbahl** [comment]
@Hixie  any ideas ?

**Comment by zoechi** [comment]
Please ensure you have the latest version of dependencies 
`flutter clean` is worth a try

**Comment by manujbahl** [comment]
I had already tried those but unfortunately did not help

**Comment by abacaj** [comment]
I just downloaded flutter following the getting started guide, same exact error soon as I run `flutter doctor` on Macosx Sierra xcode 8.3.3

**Comment by klilley** [comment]
@manujbahl Have you resolved this?
I have re-cloned the flutter repo but it didn't solve anything. I am guessing the build is broken.

**Comment by rongshuizhou** [comment]
I encountered the same problem in version 0.2.3, how did you solve it?

**Comment by zoechi** [comment]
@rongshuizhou 0.2.3 is quite an old version. Can't you update to a newer Flutter version?
