### ISSUE TITLE
Hit weird assert when popping a navigator route

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1594]
``` dart
02-03 16:11:35.369  5156  5173 I flutter : Exception caught while building Overlay-[GlobalKey 536735121]
02-03 16:11:35.369  5156  5173 I flutter : 'packages/flutter/src/widgets/framework.dart': Failed assertion: line 1398: '_dependants.isEmpty' is not true.
02-03 16:11:35.370  5156  5173 I flutter : Stack trace:
02-03 16:11:35.374  5156  5173 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
02-03 16:11:35.375  5156  5173 I flutter : #1      InheritedElement.debugDeactivated.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1398)
02-03 16:11:35.375  5156  5173 I flutter : #2      InheritedElement.debugDeactivated (packages/flutter/src/widgets/framework.dart:1397)
02-03 16:11:35.375  5156  5173 I flutter : #3      _InactiveElements._deactivate.<anonymous closure> (packages/flutter/src/widgets/framework.dart:557)
02-03 16:11:35.375  5156  5173 I flutter : #4      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:557)
02-03 16:11:35.375  5156  5173 I flutter : #5      OneChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1715)
02-03 16:11:35.375  5156  5173 I flutter : #6      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:556)
02-03 16:11:35.375  5156  5173 I flutter : #7      ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1213)
02-03 16:11:35.375  5156  5173 I flutter : #8      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:556)
02-03 16:11:35.375  5156  5173 I flutter : #9      ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1213)
02-03 16:11:35.375  5156  5173 I flutter : #10     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:556)
02-03 16:11:35.375  5156  5173 I flutter : #11     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1213)
```

**Comment by abarth** [comment]
@Hixie

**Comment by abarth** [comment]
Any idea how to reproduce the issue?

**Comment by apwilson** [comment]
FWIW I can reliably reproduce with my current app.

**Comment by apwilson** [comment]
It seems to be related to having a widget with the same key between the two routes.  @Hixie suggested I comment out assert and see if I get a duplicate key assert but when I comment out the assert I don't get any asserts.

**Comment by Hixie** [comment]
Since this bug has no steps to reproduce and we haven't heard complaints recently, I'm going to close it. Please reopen and attach a demo app that triggers to bug if you still see this.
