### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by PrenSJ2** [flutter/flutter#159458]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[33m[!][39m Flutter (Channel [user-branch], 3.24.2, on macOS 15.1.1 24B91 darwin-arm64, locale en-GB)
    [33m![39m Flutter version 3.24.2 on channel [user-branch] at /Users/seb/Documents/Code/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/setup.
    [33m![39m Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    [32m•[39m Framework revision 4cf269e36d (3 months ago), 2024-09-03 14:30:00 -0700
    [32m•[39m Engine revision a6bd3f1de1
    [32m•[39m Dart version 3.5.2
    [32m•[39m DevTools version 2.37.2
    [32m•[39m If those were intentional, you can disregard the above warnings; however it is recommended to use
      "git" directly to perform update checks and upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    [32m•[39m Android SDK at /Users/seb/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 33.0.2
    [32m•[39m Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment Homebrew (build 17.0.13+0)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Users/seb/Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[32m[✓][39m VS Code (version 1.92.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.92.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Seb’s iPhone (mobile)           • 00008120-001248DE2680C01E • ios            • iOS 18.2 22C5131e
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91
      darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91
      darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript • Google Chrome
      131.0.6778.86

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.9+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
camera-0.10.6
camera_android-0.10.9+11
camera_avfoundation-0.9.17+3
camera_web-0.3.5
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
cloud_functions-5.1.3
cloud_functions_web-4.10.2
file_picker-8.1.2
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_analytics-11.3.3
firebase_analytics_web-0.5.10+2
firebase_auth-5.3.1
firebase_auth_web-5.13.2
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_performance-0.10.0+8
firebase_performance_web-0.1.7+2
firebase_remote_config-5.1.3
firebase_remote_config_web-1.7.2
firebase_storage-12.3.2
firebase_storage_web-3.10.2
flutter_plugin_android_lifecycle-2.0.20
geolocator-13.0.1
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
google_sign_in-6.2.1
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.12.4+2
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
share_plus-6.3.4
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-6.1.2
sign_in_with_apple_web-2.1.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.2
video_player_android-2.7.13
video_player_avfoundation-2.6.2
video_player_web-2.3.2
wakelock_plus-1.2.8

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Comment by PrenSJ2** [comment]
solved by https://github.com/flutter/flutter/issues/150131#issuecomment-2501798285
