### ISSUE TITLE
Failed to access the internal image decoder registry on this isolate

### ISSUE THREAD

**Issue by atiqurgotipath** [flutter/flutter#159531]
### Steps to reproduce

multiple time tried to rebuild and get log but my final array(images) length is 0, but internal(temp) future array(futureImages) is as expected

### Expected results

I want List<Future<ui.Image>>

### Actual results

But it's nothing returning after await keyword no return.

### Code sample

<details open><summary>Code sample</summary>

```dart
Future<void> processImages() async {
    debugPrint('processImages START ${widget.vttModel.length}');

    List<Future<ui.Image>> futureImages = [];

    for (var i = 0; i < widget.vttModel.length-1; i++) {
      debugPrint('processImages futu ${futureImages.length}');

      final params = {
        'bytes': widget.image,
        'x': widget.vttModel[i].getXYWH.x.toDouble(),
        'y': widget.vttModel[i].getXYWH.y.toDouble(),
        'width': widget.vttModel[i].getXYWH.w.toDouble(),
        'height': widget.vttModel[i].getXYWH.h.toDouble(),
      };
      futureImages.add(compute(clipImageInIsolate, params));
    }

    images = await Future.wait(futureImages).catchError((e) { debugPrint('processImages D Erro: $e'); });

    setState(() {});
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/flutter (31534): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
E/flutter (31534): #0      _FutureListener.handleError (dart:async/future_impl.dart:197:7)
E/flutter (31534): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
E/flutter (31534): #2      Future._propagateToListeners (dart:async/future_impl.dart:894:13)
E/flutter (31534): #3      Future._completeError (dart:async/future_impl.dart:674:5)
E/flutter (31534): #4      Future.wait.handleError (dart:async/future.dart:524:19)
E/flutter (31534): #5      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (31534): #6      _FutureListener.handleError (dart:async/future_impl.dart:178:22)
E/flutter (31534): #7      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
E/flutter (31534): #8      Future._propagateToListeners (dart:async/future_impl.dart:894:13)
E/flutter (31534): #9      Future._completeError (dart:async/future_impl.dart:674:5)
E/flutter (31534): #10     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:760:7)
E/flutter (31534): #11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (31534): #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.7.1 23H222 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@atiqurgotipath 
Please provide complete runnable reproducible code sample along with steps and platform on which you are running it.

**Comment by anhnv-rabiloo** [comment]
import 'dart:ui' doesn't support isolate, It only use in main isolate, I think this is the problem you are facing
https://github.com/flutter/flutter/issues/115030
I am having this problem too!

**Comment by anhnv-rabiloo** [comment]
You can switch to using
https://pub.dev/packages/dart_ui_isolate
instead of compute as per issue
https://github.com/flutter/flutter/issues/10647
