### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by PizzaDev13** [flutter/flutter#159653]
## Command
```sh
flutter run --machine --start-paused -d 00008030-00016D603C3B802E --devtools-server-address http://127.0.0.1:9101/ --target /Users/joshuagibb/Desktop/Coding/Flutter/book_box_2/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[!] Flutter (Channel stable, 3.24.4, on macOS 15.2 24C5089c darwin-arm64, locale en-US)
    • Flutter version 3.24.4 on channel stable at /Users/joshuagibb/Documents/flutter
    ! The flutter binary is not on your path. Consider adding /Users/joshuagibb/Documents/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/joshuagibb/Documents/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (5 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/joshuagibb/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (6 available)
    • sdk gphone arm64 (mobile)       • emulator-5554             • android-arm64  • Android 11 (API 30) (emulator)
    • Taco’s iPad (mobile)            • 00008103-000A29091420801E • ios            • iOS 18.2 22C5109p
    • Taco’s Watch Phone (mobile)     • 00008030-00016D603C3B802E • ios            • iOS 18.2 22C5142a
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C5089c darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C5089c darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 130.0.6723.116
    ! Error: Browsing on the local area network for Mama bear 14. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 603104015dd692ea3403755b55d07813d5cf8965
### Plugins
camera-0.11.0+2
camera_android_camerax-0.6.10
camera_avfoundation-0.9.17+5
camera_web-0.3.5
firebase_auth-5.3.3
firebase_auth_web-5.13.4
firebase_core-3.8.0
firebase_core_web-2.18.1
firebase_storage-12.3.6
firebase_storage_web-3.10.5
flutter_plugin_android_lifecycle-2.0.23
mobile_scanner-6.0.2

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

Kindly try https://github.com/flutter/flutter/issues/150131#issuecomment-2366836574 to see if it helps
