### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by Ggre55** [flutter/flutter#159617]
## Command
```sh
flutter run --trace-startup --trace-systrace
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1775:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1787:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1725:14)
#4      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:894:28)
#5      FlutterVmService.getTimeline (package:flutter_tools/src/vmservice.dart:1094:12)
#6      Tracing.stopTracingAndDownloadTimeline (package:flutter_tools/src/tracing.dart:111:59)
<asynchronous suspension>
#7      downloadStartupTrace (package:flutter_tools/src/tracing.dart:142:41)
<asynchronous suspension>
#8      ColdRunner.run (package:flutter_tools/src/run_cold.dart:119:9)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:853:27)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1396:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
```
```console
[32m[✓][39m Flutter (Channel beta, 3.23.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.4391], locale en-US)
    [32m•[39m Flutter version 3.23.0-0.1.pre on channel beta at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 2feea7a407 (6 months ago), 2024-06-06 10:19:10 +0700
    [32m•[39m Engine revision bb10c54666
    [32m•[39m Dart version 3.5.0 (build 3.5.0-180.3.beta)
    [32m•[39m DevTools version 2.36.0

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\Younes\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = C:\Users\Younes\AppData\Local\Android\Sdk
    [32m•[39m ANDROID_SDK_ROOT = C:\Users\Younes\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2023.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.2
    [32m•[39m Flutter plugin version 74.0.4
    [32m•[39m Dart plugin version 231.9065

[32m[✓][39m VS Code (version 1.95.3)
    [32m•[39m VS Code at C:\Users\Younes\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.100.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m VOX Alpha (mobile) • VOXALPHA1903569 • android-arm64  • Android 8.1.0 (API 27)
    [32m•[39m Windows (desktop)  • windows         • windows-x64    • Microsoft Windows [Version 10.0.22631.4391]
    [32m•[39m Chrome (web)       • chrome          • web-javascript • Google Chrome 131.0.6778.86
    [32m•[39m Edge (web)         • edge            • web-javascript • Microsoft Edge 131.0.2903.70

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ee4e09cce01d6f2d7f4baebd247fde02e5008851
### Plugins
path_provider-2.1.5
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
sqflite-2.3.3+1
webview_flutter-4.8.0
webview_flutter_android-3.16.8
webview_flutter_wkwebview-3.14.0

**Comment by danagbemava-nc** [comment]
Hi @Ggre55, you are using an older version of the beta channel. Kindly switch to the either the latest beta(3.27.0-0.2.pre) or stable(3.24.5) to see if you still experience this issue. 

Thank you
