### ISSUE TITLE
Failed assertion: line 3720 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#159751]
### Steps to reproduce

When attempting to display a dialog as per the code below.

### Expected results

The dialog should display.

### Actual results

The assert was thrown.

### Code sample

<details open><summary>Code sample</summary>

```dart
 Widget _buildCreateInvoiceButton() => Padding(
      padding: const EdgeInsets.all(8),
      child: ElevatedButton(
        onPressed: () async {
          final selectedJob = await showDialog<Job?>(
            context: context,
            builder: (context) => const SelectJobDialog(),
          );
          if (selectedJob != null) {
            await _createInvoice(selectedJob);
          }
        },
        child: const Text('Create Invoice'),
      ));

import 'package:flutter/material.dart';
import 'package:future_builder_ex/future_builder_ex.dart';

import '../../dao/dao_job.dart';
import '../../entity/job.dart';

class SelectJobDialog extends StatelessWidget {
  const SelectJobDialog({super.key});

  @override
  Widget build(BuildContext context) => AlertDialog(
        title: const Text('Select Active Job'),
        content: FutureBuilderEx<List<Job>>(
          // ignore: discarded_futures
          future: DaoJob().getActiveJobs(null),
          builder: (context, jobs) {
            if (jobs!.isEmpty) {
              return const Center(child: Text('No active jobs found.'));
            }
            return ListView.builder(
              shrinkWrap: true,
              itemCount: jobs.length,
              itemBuilder: (context, index) {
                final job = jobs[index];
                return ListTile(
                  title: Text(job.summary),
                  subtitle: Text('Customer: ${job.customerId}'),
                  onTap: () => Navigator.pop(context, job),
                );
              },
            );
          },
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
        ],
      );
}


```

stack trace
```
#117    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3877:5)
object.dart:3877
#118    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4281:11)
proxy_box.dart:4281
#119    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3734:5)
object.dart:3734
#120    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3736:61)
object.dart:3736
#121    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4152:14)
object.dart:4152
#122    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3877:5)
object.dart:3877
#123    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4281:11)
proxy_box.dart:4281
#124    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3734:5)
object.dart:3734
#125    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3736:61)
object.dart:3736
#126    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4152:14)
object.dart:4152
#127    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3877:5)
object.dart:3877
#128    RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4281:11)
proxy_box.dart:4281
#129    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3734:5)
object.dart:3734
#130    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:3736:61)
object.dart:3736
#131    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4152:14)
object.dart:4152
#132    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:3877:5)
object.dart:3877
#133    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:3734:5)
object.dart:3734
#134    RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3686:41)
object.dart:3686
#135    PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1303:16)
object.dart:1303
#136    PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1308:15)
object.dart:1308
#137    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:609:25)
binding.dart:609
#138    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
binding.dart:1164
#139    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
binding.dart:468
#140    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#141    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
binding.dart:1318
#142    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
binding.dart:1176
#143    _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#144    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#145    _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
The relevant error-causing widget was:
    AlertDialog AlertDialog:file:///home/bsutton/git/hmb/lib/ui/invoicing/select_job_dialog.dart:11:41
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Ubuntu 24.04.1 LTS 6.8.0-48-generic, locale en_AU.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/linux-android-setup for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.2)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = xxx
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.95.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@bsutton Thanks for the report.
Although the error log is pointing to framework, but we would need a complete runnable reproducible code sample (without third party implementation) so as to properly investigate the issue, so please provide the same.

https://stackoverflow.com/help/minimal-reproducible-example
