### ISSUE TITLE
[in_app_purchase] Crash for iOS 18.2 when purchase, when Deprecated field `applicationUsername` is null.

### ISSUE THREAD

**Issue by givip** [flutter/flutter#159807]
### Steps to reproduce

1. On iOS 18.2 calling buyNonConsumable or buyConsumable API will crash

This issue is copy of https://github.com/flutter/flutter/issues/158097, because it needs attention.

`applicationUsername` is deprecated by apple since iOS 18.
https://developer.apple.com/documentation/storekit/skmutablepayment/applicationusername

Hence it should not crash we pass null there.

### Expected results

Should not crash.

### Actual results

Got
Fatal Exception: NSInvalidArgumentException -[NSNull length]
in Xcode

### Code sample

<details open><summary>Code sample</summary>

```dart
PurchaseParam purchaseParam =
            PurchaseParam(productDetails: product, applicationUserName: null);
        _connection.buyNonConsumable(purchaseParam: purchaseParam);
```
or
```
PurchaseParam purchaseParam =
            PurchaseParam(productDetails: product);
        _connection.buyNonConsumable(purchaseParam: purchaseParam);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Keeping the issue open and labeling for team's tracking based on said field's deprecation and for any changes required.

**Comment by evanave** [comment]
obfuscatedAccountId is null, but placing a string here will prevent the crash.

Does anybody know if putting a random string here will impact restore purchase?

      return await _channel.invokeMethod('buyProduct', <String, dynamic>{
        'sku': productId,
        'forUser': obfuscatedAccountId ?? "NEED_STRING_HERE_AS_THIS_IS_NULL",
      });

**Comment by kimiaki704** [comment]
Hello.
I had the same problem, but was able to work around it by changing the Flutter version to 3.24.5.
I hope this helps!

**Comment by tony-soft** [comment]
> I had the same problem, but was able to work around it by changing the Flutter version to 3.24.5. I hope this helps!

I have the same issue!
Did you just upgrade your flutter version to 3.24.5? Is that all?

**Comment by kimiaki704** [comment]
@tony-soft 
> Did you just upgrade your flutter version to 3.24.5? Is that all?

Yes. To be precise, we updated the flutter version from 3.19.6 to 3.24.5, and with that, several packages needed to be updated.
I don't think it should necessarily be 3.24.5, but I was able to work around it by upgrading flutter anyway.

**Comment by tony-soft** [comment]
I upgraded Flutter version to 3.24.5, but it's not working.
I solved this problem by using the `applicationUserName` parameter.
```dart
await InAppPurchase.instance.buyNonConsumable(
        purchaseParam: PurchaseParam(
          productDetails: details,
          applicationUserName: applicationUserName,
        ),
      );
```

**Comment by maulik-benzatine** [comment]
@givip @tony-soft 

Hello,

I have get same issue in latest in_app_purchase lib and latest Flutter version.

Is there any update?

**Comment by wph144** [comment]
> I upgraded Flutter version to 3.24.5, but it's not working.
> I solved this problem by using the `applicationUserName` parameter.
> ```dart
> await InAppPurchase.instance.buyNonConsumable(
>         purchaseParam: PurchaseParam(
>           productDetails: details,
>           applicationUserName: applicationUserName,
>         ),
>       );
> ```

This is only a temporary solution and not a correct fix. As @givip said, the correct fix is ​​to prevent a crash even if the applicationUserName parameter is not used. And this is not something for users of the in_app_purchase package to modify, but for in_app_purchase developers to quickly modify it.

**Comment by ampl-agoyani** [comment]
I am facing the same issue.
i try to upgrade latest sdk but still i am facing the same issue.

**Comment by Pythogen7** [comment]
Same issue as well. I have several applications that do not require a sign in. Each user does not have an applicationUserName, so I do not think using the applicationUserName parameter workaround will work for me. Is there another temporary solution while we wait for this fix?

**Comment by lslv1243** [comment]
@Pythogen7 you can use an empty string as value if you don't need it.

**Comment by GabriellArthur** [comment]
It happens to me too, even before making the purchase, it happens in:

```
await iapConnection.countryCode();
```

Flutter: 3.27.3
XCode: 16.2
iOS: 18.2

I'm talking about this error: 
```
[log] Error: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
[log] #0      InAppPurchaseAPI.storefront (package:in_app_purchase_storekit/src/messages.g.dart:685:7)
      <asynchronous suspension>
      #1      SKPaymentQueueWrapper.storefront (package:in_app_purchase_storekit/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:57:50)
sk_payment_queue_wrapper.dart:57
      <asynchronous suspension>
      #2      InAppPurchaseStoreKitPlatform.countryCode (package:in_app_purchase_storekit/src/in_app_purchase_storekit_platform.dart:244:13)
```

**Comment by vashworth** [comment]
cc @LouiseHsu

**Comment by alexprogrammr** [comment]
My app started crashing in production but I didn't perform any new updates for the last several months. When I started figuring out what went wrong - it turned out that users aren't able to buy subscriptions.

Almost three months passed since this issue was reported and there is still no fix for that. I regret choosing flutter. Not only because of this issue, on my way there were always some stupid obstacles and workarounds. Generally I liked flutter for it's speed of development. But this issue is a last straw. Never again.

**Comment by syahrisnt** [comment]
> [@darshankawar](https://github.com/darshankawar)
> 
> Hello,
> 
> I have get same issue in latest in_app_purchase lib and latest Flutter version.
> 
> The parameter is not passed in store kit library
> 
> ![image](https://github.com/user-attachments/assets/e8df3a19-e17a-40d5-ae9f-4bc2225fea31)

I try adding applicationUserName but still produce an error. Is there any other ways to fix this? @maulik-benzatine

**Comment by LouiseHsu** [comment]
I will start working on this issue next. For those that can't use @tony-soft 's workaround, can you send me a minimal repro?

**Comment by davidengler** [comment]
Any update on this?

**Comment by LouiseHsu** [comment]
> Any update on this?

Are you still hitting this? I cannot repro it on the latest `0.3.21` version of in_app_purchase_storekit

**Comment by davidengler** [comment]
It is not reproduced on latest version, thanks

**Comment by lslv1243** [comment]
> I will start working on this issue next.

> Are you still hitting this? I cannot repro it on the latest 0.3.21 version of in_app_purchase_storekit

@LouiseHsu Have you worked on this issue and that is why it isn't reproducible anymore? I guess it might make sense to comment in this issue about that update.

**Comment by LouiseHsu** [comment]
> > I will start working on this issue next.
> 
> > Are you still hitting this? I cannot repro it on the latest 0.3.21 version of in_app_purchase_storekit
> 
> [@LouiseHsu](https://github.com/LouiseHsu) Have you worked on this issue and that is why it isn't reproducible anymore? I guess it might make sense to comment in this issue about that update and reference the PR and/or the release where the fix was introduced.

Unfortunately I've never been able to repro this issue, even back when this was initially filed. This issue seems to be Storekit 1/ios 18.2 exclusive, and storekit 1 code hasn't been touched in a while. I will keep this issue open in case anyone else still runs into this issue.

**Comment by LouiseHsu** [comment]
It doesn't look like anyone has run into this issue for a while, and a comment mentioned upgrading flutter helped. Ill reopen if someone else runs into this
