### ISSUE TITLE
build web --wasm --dart-define-from-file config.json fails when entry in config.json starts with "="

### ISSUE THREAD

**Issue by verscph** [flutter/flutter#159840]
### Steps to reproduce

1. Create flutter web app
2. Create config.json with an entry that has a value starting with "="
`{
  "API_AUTH_KEY": "=1234xYz",
}`
3. Build the app with `build web --wasm --dart-define-from-file config.json`

### Expected results

Successful build

### Actual results

```
Compiling lib/main.dart for the Web...                          
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
#0      processEnvironment.<anonymous closure> (package:dart2wasm/dart2wasm.dart:113)
#1      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#3      MapBase.addEntries (dart:collection/maps.dart:89)
#4      new Map.fromEntries (dart:core/map.dart:210)
#5      processEnvironment (package:dart2wasm/dart2wasm.dart:110)
#6      options.<anonymous closure> (package:dart2wasm/dart2wasm.dart:72)
#7      Option.applyToOptions (package:dart2wasm/option.dart:18)
#8      parseArguments (package:dart2wasm/dart2wasm.dart:147)
#9      main (package:dart2wasm/dart2wasm.dart:164)
#10     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

Argument Error: Invalid argument(s): Bad define string: API_AUTH_KEY==1234xYz
Usage: dart2wasm [<options>] <infile.dart> <outfile.wasm>
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/philip.verschueren/fvm/versions/3.24.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/philip.verschueren/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • iPhone 16 Pro (mobile)          • 76B455C7-7E00-4C7C-AB43-FC5D256F7F74 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.87

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by jason-simmons** [comment]
Fixed by https://dart.googlesource.com/sdk/+/00478a7d3caca41be36dd33ba34189af534b7c12
