### ISSUE TITLE
i am experin

### ISSUE THREAD

**Issue by codecrafteryt** [flutter/flutter#159973]
### Steps to reproduce

in my home screen i simply implemented the API and this bug shows

### Expected results

bug stops my all app. anywhere i touch the screen nothing happens

### Actual results

my app goes stuck

### Code sample

```
import 'package:braelo_app/controller/home_controller/home_controller.dart';
import 'package:braelo_app/utils/values/my_color.dart';
import 'package:braelo_app/views/card.dart';
import 'package:braelo_app/views/widgets/custom_loading_indicator.dart';
import 'package:braelo_app/views/widgets/shimmer_custom_card.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:get/get_instance/get_instance.dart';
import 'package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart';

class RecentListingScreen extends StatelessWidget {
  final HomeController controller = Get.find();
  RecentListingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return  CustomScrollView(
        controller: controller.scrollController,
        slivers: [
          Obx(() {
            if (controller.isLoading.value || controller.getRecentModel.value.results == null || controller.getRecentModel.value.results!.isEmpty) {
              return SliverToBoxAdapter(
                child: GridView.builder(
                  padding: EdgeInsets.all(16.0.w),
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2,
                    crossAxisSpacing: 8.0,
                    mainAxisSpacing: 12.0,
                    childAspectRatio: 0.75,
                  ),
                  itemCount: 6,
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemBuilder: (context, index) => const ShimmerCustomCard(),
                ),
              );
            }
            if (controller.getRecentModel.value.results!.isNotEmpty) {
              return SliverGrid(
                delegate: SliverChildBuilderDelegate(
                      (context, index) {
                    final vehicle = controller.getRecentModel.value.results![index];
                    return GestureDetector(
                      onTap: () {
                        final selectedListing = controller.getRecentModel.value.results![index];
                        final selectedSubcategory = controller.selectedSubcategory.value;
                        debugPrint("Selected Index: $index");
                        debugPrint("Selected Listing ID: ${selectedListing.id}");
                        //controller.onCategorySelected(controller.selectedCategory.toString());
                        //Get.to(() => CommonGetListingWidgetScreen(vehicle: selectedListing, ),);
                        controller.setIndex(index);
                        debugPrint("12345");
                      },
                      child: CustomJobCard1(
                        imageUrl: vehicle.pictures?.isNotEmpty ?? false ? vehicle.pictures!.first : 'https://images.unsplash.com/photo-1234567890abcd.jpg',
                        title: vehicle.title ?? 'No title',
                        category: vehicle.category ?? 'No category',
                        location: vehicle.location ?? 'No location',
                        price: vehicle.price?.toString() ?? '0.00',
                      ),
                    );
                  },
                  childCount: controller.getModel.value.results!.length,
                ),
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  crossAxisSpacing: 10,
                  mainAxisSpacing: 20,
                  childAspectRatio: 0.68,
                ),
              );
            }
            return const SliverToBoxAdapter(child: SizedBox.shrink());
          }),
          SliverToBoxAdapter(
            child: Obx(() {
              if (controller.isLoadingMore.value) {
                return Padding(
                  padding: EdgeInsets.all(16.0.w),
                  child: const Center(
                      child: CustomLoadingIndicator()
                  ),
                );
              }
              return const SizedBox.shrink();
            }),
          ),
        ]
    );
  }
}
```

### Screenshots or Video

![Screenshot 2024-12-09 184833](https://github.com/user-attachments/assets/8aa4d55a-4572-404f-884d-557e76b37050)

### Logs

```
======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout() in RenderTapRegionSurface.performLayout.
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2178 pos 16: 'sizeAccessAllowed'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:2178:16)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:2199:6)
#4      RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:210:10)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#11     RenderView.hitTest (package:flutter/src/rendering/view.dart:300:14)
#12     RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:635:34)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:397:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
#17     _invoke1 (dart:ui/hooks.dart:328:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout() in RenderTapRegionSurface.performLayout.
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2178 pos 16: 'sizeAccessAllowed'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:2178:16)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:2199:6)
#4      RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:210:10)
#5      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:124:19)
#10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2750:11)
#11     RenderView.hitTest (package:flutter/src/rendering/view.dart:300:14)
#12     RendererBinding.hitTestInView (package:flutter/src/rendering/binding.dart:635:34)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:397:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
#17     _invoke1 (dart:ui/hooks.dart:328:13)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
I/ViewRootImpl@ca5e369[MainActivity](14336): ViewPostIme pointer 1
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@codecrafteryt 
When you file an issue, please atleast try to format the code sample and logs so that it'll be readable.
Also, your issue is better suited for support channels like StackOverflow so please ask the same there, as it more looks like a code implementation issue rather than bug in framework.
Closing for now.
