### ISSUE TITLE
ActivityThread.throwRemoteServiceException : android.app.RemoteServiceException$CannotDeliverBroadcastException - can't deliver broadcast

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#159948]
### Steps to reproduce

Unfortunately the crash happened to my live app on an Android device `Realme C53` under Android 13 but i am not sure this is device specific or not. 

I have no ways to reproduce it as i don't even understand what is this error but the app has crashed.

I am attaching the whole [StackTrace](https://github.com/user-attachments/files/18052433/stackTrace1.txt) for deeper insights on your side if that tells you anything...

### Expected results

The app is crashing

### Actual results

The app should not crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: android.app.RemoteServiceException$CannotDeliverBroadcastException: can't deliver broadcast
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2060)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-x64, locale fr-FR)
    • Flutter version 3.24.5 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 15.1.1 24B91 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Tom3652 
It most likely could be related to native Android. See this https://issuetracker.google.com/issues/245258072?pli=1 which has recent reports of same issue although it is closed as fixed. Also, per stacktrace, firebase setup is involved, so can't rule out an issue with it as well specifically firebase android sdk, so you will probably need to do some more digging to see what could be causing it.

**Comment by Tom3652** [comment]
Yes you are right, it's very possible it is FirebaseMessaging causing this and i confirm by seeing your issue tracker that it appears on Android 13.

This is very likely the same issue even if they say it's fixed, it seems it isn't unfortunately... I will raise an issue in the proper repo.
