### ISSUE TITLE
FlutterActivity.onResume : java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#159949]
### Steps to reproduce

Unfortunately the crash happened to my live app on Android, so i have no clue about how to reproduce it i have never encountered it in debug mode or release mode by testing event when playing with the `onResume` state...

I am attaching the whole [StackTrace](https://github.com/user-attachments/files/18052447/stackTrace2.txt)) because github doesn't allow that many characters in the `Logs` section.

### Expected results

The app is crashing

### Actual results

The app should not crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.myappname/com.myappname.MainActivity}: java.lang.IllegalArgumentException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4008)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4040)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by java.lang.IllegalArgumentException:
       at android.os.Parcel.createException(Parcel.java:1970)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:7826)
       at android.app.Activity.isTopOfTask(Activity.java:6544)
       at android.app.Activity.onResume(Activity.java:1404)
       at io.flutter.embedding.android.FlutterActivity.onResume(FlutterActivity.java:822)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
       at android.app.Activity.performResume(Activity.java:7558)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4000)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4040)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-x64, locale fr-FR)
    • Flutter version 3.24.5 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 15.1.1 24B91 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Tom3652 
From the stacktrace file as well, there's only one entry pointing to Flutter frame `at io.flutter.embedding.android.FlutterActivity.onResume` which probably isn't enough to deduce anything. 

I think there could be more to the log, maybe a message that you probably need to find out by digging deep. Something like this:

`Unable to resume activity : java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent`
