### ISSUE TITLE
Windows 10 upgrade failed

### ISSUE THREAD

**Issue by xeurun** [flutter/flutter#15996]
## Steps to Reproduce

A:\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from A:\flutter...
From https://github.com/flutter/flutter
   49c87d010..171f94d17  master     -> origin/master
Already up to date.

Upgrading engine...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 39c834a69d345530)
Crash report written to A:\flutter\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

### command

flutter --no-color upgrade

### exception

ArgumentError: Invalid argument(s): Cannot find executable for bin\flutter.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133)
<asynchronous suspension>
#4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:61)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:222)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#22     main (file:///A:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## Flutter Doctor

PS> flutter doctor -v
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.17127.1], locale en-US)
    • Flutter version 0.2.3 at A:\flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Program Files\Android
      but Android SDK not found at this location.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

! Doctor found issues in 1 category.

**Comment by Hixie** [comment]
The problem might be that we're not handling Windows here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart#L83
It's not clear if this is actually failing on Windows but we definitely need to check before we do another release.

**Comment by bkonyi** [comment]
I'm not able to reproduce this on my machine (both cmd and powershell).

Initial run:
```
PS C:\Workspace\flutter> .\bin\flutter.bat --no-color upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e61bb9ac3a3fd789754e2e54220bcfc27076a857...
Unzipping Dart SDK...
Updating flutter tool...
Upgrading Flutter from C:\Workspace\flutter...
Already up-to-date.

Upgrading engine...
Downloading package sky_engine...

Flutter 0.2.3 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[√] Android Studio (version 3.0)

! Doctor found issues in 1 category.
PS C:\Workspace\flutter> .\bin\flutter.bat --no-color upgrade
Upgrading Flutter from C:\Workspace\flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.3 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[√] Android Studio (version 3.0)

! Doctor found issues in 1 category.                                                                      
```

Run when we're already up-to-date:
```
PS C:\Workspace\flutter> .\bin\flutter.bat --no-color upgrade
Upgrading Flutter from C:\Workspace\flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.3 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[√] Android Studio (version 3.0)

! Doctor found issues in 1 category.
PS C:\Workspace\flutter> flutter --no-color upgrade
Upgrading Flutter from C:\Workspace\flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.3 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[√] Android Studio (version 3.0)

! Doctor found issues in 1 category.
```

**Comment by cbracken** [comment]
Unlabelling `TODAY` since we're unable to reproduce locally. We have some further checking to do on `flutter upgrade` on Windows.

**Comment by xeurun** [comment]
I reinstall flutter (with removing flutter folder and AppData dart folders)

And again get this error, it seems I found the reason but I do not understand why so

![sketch](https://user-images.githubusercontent.com/1073935/38073379-cc4f4730-333b-11e8-806c-594fe4673880.png)

Windows 10 Enterprise **Insider**
Version: 1803
Build: 17127.1

**Comment by NathanaelA** [comment]
@xeurun - 
1. I assume you have rebooted since modifying the `Path`...   (If not, this is probably why it is failing)
2. In your cmd prompt; type `echo %PATH%` and see what it says.

I just upgraded both the beta and master channels fine on Windows 7.     But you might have found a issue on Windows 10 Insider if you have rebooted.

**Comment by xeurun** [comment]
I restarted the computer several times
![2018-03-29](https://user-images.githubusercontent.com/1073935/38074688-a58f451e-3340-11e8-9283-4aaf3205e6c2.png)

**Comment by NathanaelA** [comment]
Wow, that is very interesting.   Can you try clicking into Properties->options on the console window; and then choose `Use Legacy Console`; restart the console and see if you can type "flutter" alone w/o the `.bat` file

**Comment by xeurun** [comment]
This is very very interesting

![sketch2](https://user-images.githubusercontent.com/1073935/38076719-85e02ace-3347-11e8-8e64-8825a44463c3.png)

generate broken log file

![2018-03-29 3](https://user-images.githubusercontent.com/1073935/38076748-9ae78afc-3347-11e8-8f2a-742d15abe7f1.png)

i open in notepad and resave

![2018-03-29 2](https://user-images.githubusercontent.com/1073935/38076805-cf7fe732-3347-11e8-9be4-95405431e168.png)

**Comment by NathanaelA** [comment]
That is very interesting..   

So if you don't have `use legacy console` - `flutter.bat` actually works.   But `flutter` (without .bat) doesn't.   If you do have `legacy console` enabled `flutter` and `flutter.bat` run and just crash while trying to upgrade check.

1. Can you verify you are still on the "beta" branch..  `git status` should tell you the branch.
2. If you run `flutter` from inside powershell does it crash?    Or only the cmd w/ legacy?

**Comment by NathanaelA** [comment]
I wish I had windows 10 to test this on...  So if you don't mind testing this...

I have one more idea that I would be curious to know if it works.    
Remove the `use legacy console`, restart the cmd window.     
Create a file called "flutter.cmd" in the flutter\bin folder.
In this file put `flutter.bat %*` as it's only line...
Then try typing `flutter` and see if it works...

**Comment by xeurun** [comment]
version.dart
[version.dart.txt](https://github.com/flutter/flutter/files/1859444/version.dart.txt)
proof beta branch
![2018-03-29 5](https://user-images.githubusercontent.com/1073935/38081702-b76fab4c-3355-11e8-9421-683a536e43c0.png)
test no legacy (flutter.cmd copy flutter.bat)
![nolegacy](https://user-images.githubusercontent.com/1073935/38081724-c2cb8470-3355-11e8-8524-0bc1414917a0.png)
test legacy (flutter.cmd copy flutter.bat)
![legacy](https://user-images.githubusercontent.com/1073935/38081937-53e61754-3356-11e8-87b0-a50b167f5b55.png)
test no legacy (flutter.cmd is flutter.bat %*)
![2018-03-29 6](https://user-images.githubusercontent.com/1073935/38082078-a84d3ca0-3356-11e8-96c6-60724a109445.png)
log
```

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for bin\flutter.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133)
<asynchronous suspension>
#4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:61)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#6      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#10     new Future.sync (dart:async/future.dart:222)
#11     CommandRunner.run (package:args/command_runner.dart:109)
#12     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#14     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#15     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#20     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#22     main (file:///A:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.17127.1], locale en-US)
    • Flutter version 0.2.3 at A:\flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at S:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = S:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

```

**Comment by NathanaelA** [comment]
Awesome, thanks for trying that.   That is very interesting.   
1. Delete the `flutter.cmd` it didn't do what I was hoping it would do; and it might have caused the last crash for the upgrade from inside powershell.   Since it says powershell couldn't find the executable; it is possible it confused it...   I was really hoping that windows would see the .cmd extension since it wasn't seeing the .bat extension and would allow us to redirect to the batch file.   But according to all your screen snap shots; windows insider is ignore both .bat and .cmd files unless you manually put the extension on them.   ;-(

2. Just to confirm -- does `flutter.bat upgrade` work fine from the cmd prompt without the legacy and without my `flutter.cmd` that I had you create for testing?

**Comment by xeurun** [comment]
flutter.bat upgrade not work since call bin/flutter, see last log or first log

**Comment by xeurun** [comment]
@NathanaelA magic, i moved the flutter from A: drive to S: drive and... works

`
PS C:\Users\XeuRun> flutter upgrade
Upgrading Flutter from S:\flutter...
From https://github.com/flutter/flutter
cab8242f2..f69d12595  master     -> origin/master
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.17127.1], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
PS C:\Users\XeuRun>
`
