### ISSUE TITLE
enable ASAN for impeller_unittests and impeller_golden_tests on macos ci

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#159985]
Spawned from https://github.com/flutter/engine/pull/57015

There is a `--asan` flag in GN.  If you set it it will compile the binaries with the correct flags.  The impeller targets will fail to compile though because `flatc` will fail to execute.  Clang on macos links a runtime library ( `libclang_rt.asan_osx_dynamic.dylib` ) that isn't available to dyld without some sort of change.  I'm not sure what mechanisms GN has to run otool to edit the linkage.

**Comment by gaaclarke** [comment]
Looks like we are bringing in the required dylibs already:
```
/Users/aaclarke/dev/engine/src/flutter/buildtools/mac-arm64/clang/lib/clang/18/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
/Users/aaclarke/dev/engine/src/flutter/buildtools/mac-x64/clang/lib/clang/18/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
```

**Comment by gaaclarke** [comment]
I got it compiling locally but it looks like swiftshader causes it to crash:
```
[ RUN      ] Play/AiksTest.DrawAtlasNoColor/Vulkan
[INFO:flutter/impeller/renderer/backend/vulkan/capabilities_vk.cc(67)] Vulkan validations are enabled.
[INFO:flutter/impeller/renderer/backend/vulkan/capabilities_vk.cc(67)] Vulkan validations are enabled.
[WARNING:flutter/impeller/renderer/backend/vulkan/pipeline_cache_data_vk.cc(80)] Persisted pipeline cache is not compatible with current Vulkan context. Ignoring.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==82680==ERROR: AddressSanitizer: BUS on unknown address (pc 0x000112a600b0 bp 0x000170209ff0 sp 0x000170209de0 T41)
==82680==The signal is caused by a WRITE memory access.
==82680==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x112a600b0  (<unknown module>)
    #1 0x13ad91040 in std::_fl::__function::__func<sw::DrawCall::run(vk::Device*, marl::Pool<sw::DrawCall>::Loan const&, marl::Ticket::Queue*, marl::Ticket::Queue*)::$_1, std::_fl::allocator<sw::DrawCall::run(vk::Device*, marl::Pool<sw::DrawCall>::Loan const&, marl::Ticket::Queue*, marl::Ticket::Queue*)::$_1>, void ()>::operator()()+0x2dc (libvk_swiftshader.dylib:arm64+0x261040)
    #2 0x13acea070 in marl::Scheduler::Worker::runUntilIdle()+0xcb4 (libvk_swiftshader.dylib:arm64+0x1ba070)
    #3 0x13ace91c0 in marl::Scheduler::Worker::run()+0x460 (libvk_swiftshader.dylib:arm64+0x1b91c0)
    #4 0x13acf2898 in std::_fl::__function::__func<marl::Scheduler::Worker::start()::$_0, std::_fl::allocator<marl::Scheduler::Worker::start()::$_0>, void ()>::operator()()+0x760 (libvk_swiftshader.dylib:arm64+0x1c2898)
    #5 0x13acfdd70 in void* std::_fl::__thread_proxy[abi:v15000]<std::_fl::tuple<std::_fl::unique_ptr<std::_fl::__thread_struct, std::_fl::default_delete<std::_fl::__thread_struct>>, marl::Thread::Impl::Impl(marl::Thread::Affinity&&, std::_fl::function<void ()>&&)::'lambda'()>>(void*)+0xb8 (libvk_swiftshader.dylib:arm64+0x1cdd70)
    #6 0x10f9bd844 in asan_thread_start(void*)+0x48 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x51844)
    #7 0x185689f90 in _pthread_start+0x84 (libsystem_pthread.dylib:arm64+0x6f90)
    #8 0x5962800185684d30  (<unknown module>)

==82680==Register values:
 x[0] = 0x000000102e0413bc   x[1] = 0x0000000139c3a550   x[2] = 0x000000017020a040   x[3] = 0x000000013a0ad550  
 x[4] = 0x000061a0001b4e90   x[5] = 0x0000000000000003   x[6] = 0x0000000000000000   x[7] = 0x0000000000000000  
 x[8] = 0x00000000f1f1f1f1   x[9] = 0x0000001000000000  x[10] = 0x0000007027436e4c  x[11] = 0x0000000000000000  
x[12] = 0x0000007027436e48  x[13] = 0xffffff8fd8bc91cf  x[14] = 0x0000007027436e2c  x[15] = 0x0000000170209de0  
x[16] = 0x00000001856b9ed0  x[17] = 0x000000017020a09c  x[18] = 0x0000000000000000  x[19] = 0x0000000170209f20  
x[20] = 0x000000017020a040  x[21] = 0x000061a0001b4e90  x[22] = 0x000000013a0ad550  x[23] = 0x0000000139c3a550  
x[24] = 0x0000000139c3a550  x[25] = 0x000000013a0b7278  x[26] = 0x0000625000a40b5c  x[27] = 0x0000007000020000  
x[28] = 0x0000625000a40b40     fp = 0x0000000170209ff0     lr = 0x000000013ad91044     sp = 0x0000000170209de0  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (<unknown module>) 
Thread T41 created by T0 here:
    #0 0x10f9b8300 in pthread_create+0x58 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x4c300)
    #1 0x13acfdbe0 in marl::Thread::Impl::Impl(marl::Thread::Affinity&&, std::_fl::function<void ()>&&)+0x1a0 (libvk_swiftshader.dylib:arm64+0x1cdbe0)
    #2 0x13acfd3cc in marl::Thread::Thread(marl::Thread::Affinity&&, std::_fl::function<void ()>&&)+0x54 (libvk_swiftshader.dylib:arm64+0x1cd3cc)
    #3 0x13ace1800 in marl::Scheduler::Worker::start()+0x218 (libvk_swiftshader.dylib:arm64+0x1b1800)
    #4 0x13ace3600 in marl::Scheduler::Scheduler(marl::Scheduler::Config const&)+0xb80 (libvk_swiftshader.dylib:arm64+0x1b3600)
    #5 0x13abda964 in vkCreateDevice+0x12f4 (libvk_swiftshader.dylib:arm64+0xaa964)
    #6 0x12c947870 in terminator_CreateDevice+0x39c (libvulkan.1.3.243.dylib:arm64+0x27870)
    #7 0x133774664 in vulkan_layer_chassis::CreateDevice(VkPhysicalDevice_T*, VkDeviceCreateInfo const*, VkAllocationCallbacks const*, VkDevice_T**)+0x268 (libVkLayer_khronos_validation.dylib:arm64+0x2d0664)
    #8 0x12c945294 in loader_create_device_chain+0xaf4 (libvulkan.1.3.243.dylib:arm64+0x25294)
    #9 0x12c9443e4 in loader_layer_create_device+0x2e4 (libvulkan.1.3.243.dylib:arm64+0x243e4)
    #10 0x12c94cf04 in vkCreateDevice+0x74 (libvulkan.1.3.243.dylib:arm64+0x2cf04)
    #11 0x10667ceec in impeller::ContextVK::Setup(impeller::ContextVK::Settings)+0x3f20 (impeller_golden_tests:arm64+0x106028eec)
    #12 0x106678e0c in impeller::ContextVK::Create(impeller::ContextVK::Settings)+0x18c (impeller_golden_tests:arm64+0x106024e0c)
    #13 0x105dc72d8 in impeller::PlaygroundImplVK::PlaygroundImplVK(impeller::PlaygroundSwitches)+0xc6c (impeller_golden_tests:arm64+0x1057732d8)
    #14 0x105dcae00 in impeller::PlaygroundImplVK::PlaygroundImplVK(impeller::PlaygroundSwitches)+0x30 (impeller_golden_tests:arm64+0x105776e00)
    #15 0x105d98ed4 in std::_fl::__unique_if<impeller::PlaygroundImplVK>::__unique_single std::_fl::make_unique[abi:v15000]<impeller::PlaygroundImplVK, impeller::PlaygroundSwitches&>(impeller::PlaygroundSwitches&)+0x148 (impeller_golden_tests:arm64+0x105744ed4)
    #16 0x105d98510 in impeller::PlaygroundImpl::Create(impeller::PlaygroundBackend, impeller::PlaygroundSwitches)+0x4e0 (impeller_golden_tests:arm64+0x105744510)
    #17 0x1069ab188 in impeller::(anonymous namespace)::MakeVulkanPlayground(bool)+0x388 (impeller_golden_tests:arm64+0x106357188)
    #18 0x1069a89d8 in impeller::(anonymous namespace)::GetSharedVulkanPlayground(bool)+0x1b4 (impeller_golden_tests:arm64+0x1063549d8)
    #19 0x1069a7a50 in impeller::GoldenPlaygroundTest::SetUp()+0x8ac (impeller_golden_tests:arm64+0x106353a50)
    #20 0x106bfc178 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x1e0 (impeller_golden_tests:arm64+0x1065a8178)
    #21 0x106b75c34 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x1fc (impeller_golden_tests:arm64+0x106521c34)
    #22 0x106b757e8 in testing::Test::Run()+0x21c (impeller_golden_tests:arm64+0x1065217e8)
    #23 0x106b77e84 in testing::TestInfo::Run()+0x4cc (impeller_golden_tests:arm64+0x106523e84)
    #24 0x106b7ad50 in testing::TestSuite::Run()+0x5a8 (impeller_golden_tests:arm64+0x106526d50)
    #25 0x106b989b0 in testing::internal::UnitTestImpl::RunAllTests()+0xa48 (impeller_golden_tests:arm64+0x1065449b0)
    #26 0x106c1c830 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x1e0 (impeller_golden_tests:arm64+0x1065c8830)
    #27 0x106b97e30 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x1fc (impeller_golden_tests:arm64+0x106543e30)
    #28 0x106b97a40 in testing::UnitTest::Run()+0x26c (impeller_golden_tests:arm64+0x106543a40)
    #29 0x1006692d8 in RUN_ALL_TESTS()+0x20 (impeller_golden_tests:arm64+0x1000152d8)
    #30 0x100668364 in main+0x88c (impeller_golden_tests:arm64+0x100014364)
    #31 0x1852ff150 in start+0x9a8 (dyld:arm64+0xfffffffffff4d150)
    #32 0xef5c7ffffffffffc  (<unknown module>)

==82680==ABORTING
Abort trap: 6
```
