### ISSUE TITLE
Flutter build issue

### ISSUE THREAD

**Issue by vijaybadugu** [flutter/flutter#160091]
### Steps to reproduce

We have recently installed flutter in windows 11. I am getting this error 

Installed ArcGIS SDK for Flutter and try to run from VS code 

### Actual results

We have recently installed flutter in windows 11. I am getting this error 

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':arcgis_maps:compileDebugKotlin'.
> Unknown Kotlin JVM target: 21

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by maheshj01** [comment]
Hello @vijaybadugu, Is thie build failure when building for Android only or all platforms?

Please share the output of `flutter run -v` and `flutter doctor -v`

**Comment by rnwxyz** [comment]
I have the same error, this is the output of my `flutter run -v`

```
[   +1 ms] To suppress this warning, add/update
[   +1 ms]     android.suppressUnsupportedCompileSdk=34
[   +1 ms] to this project's gradle.properties.
[  +82 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':arcgis_maps:compileDebugKotlin'.
[   +1 ms] > Unknown Kotlin JVM target: 21
[   +1 ms] * Try:
[   +1 ms] > Run with --debug option to get more log output.
[   +2 ms] > Run with --scan to get full insights.
[   +1 ms] > Get more help at https://help.gradle.org.
[   +1 ms] * Exception is:
[   +1 ms] org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task 
':arcgis_maps:compileDebugKotlin'.
[   +2 ms]      at
org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.
java:68)
[   +2 ms]      at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:49)
[   +2 ms]      at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:148)
[   +1 ms]      at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:122)
[   +1 ms]      at org.gradle.execution.plan.DefaultExecutionPlan.discoverNodeRelationships(DefaultExecutionPlan.java:184)
[   +2 ms]      at org.gradle.execution.plan.DefaultExecutionPlan.doAddEntryNodes(DefaultExecutionPlan.java:156)      
[   +1 ms]      at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:131)        
[   +1 ms]      at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:123)        
[   +1 ms]      at
org.gradle.execution.TaskNameResolvingBuildTaskScheduler.scheduleRequestedTasks(TaskNameResolvingBuildTaskScheduler.ja
va:54)
[   +2 ms]      at
org.gradle.execution.DefaultTasksBuildTaskScheduler.scheduleRequestedTasks(DefaultTasksBuildTaskScheduler.java:72)    
[   +2 ms]      at
org.gradle.initialization.DefaultTaskExecutionPreparer.lambda$scheduleRequestedTasks$0(DefaultTaskExecutionPreparer.ja
va:46)
[   +2 ms]      at org.gradle.internal.Factories$1.create(Factories.java:31)
[   +1 ms]      at
org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:360)
[   +1 ms]      at
org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(
DefaultProjectStateRegistry.java:228)
[   +2 ms]      at
org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(
DefaultProjectStateRegistry.java:221)
[   +3 ms]      at
org.gradle.initialization.DefaultTaskExecutionPreparer.scheduleRequestedTasks(DefaultTaskExecutionPreparer.java:45)   
[   +2 ms]      at
org.gradle.initialization.VintageBuildModelController.lambda$scheduleRequestedTasks$0(VintageBuildModelController.java
:76)
[   +3 ms]      at org.gradle.internal.model.StateTransitionController.lambda$inState$1(StateTransitionController.java:99)
[   +9 ms]      at
org.gradle.internal.model.StateTransitionController.lambda$inState$2(StateTransitionController.java:114)
[   +2 ms]      at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[   +2 ms]      at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:110)    
[   +2 ms]      at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:98)
[   +2 ms]      at
org.gradle.initialization.VintageBuildModelController.scheduleRequestedTasks(VintageBuildModelController.java:76)     
[   +3 ms]      at
org.gradle.internal.build.DefaultBuildLifecycleController$DefaultWorkGraphBuilder.addRequestedTasks(DefaultBuildLifecy
cleController.java:351)
[   +3 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeWorkPreparer.lambda$scheduleRequestedTasks$0(DefaultBuildTreeWorkPrepare
r.java:41)
[   +2 ms]      at
org.gradle.internal.build.DefaultBuildLifecycleController.lambda$populateWorkGraph$7(DefaultBuildLifecycleController.j
ava:186)
[   +3 ms]      at org.gradle.internal.build.DefaultBuildWorkPreparer.populateWorkGraph(DefaultBuildWorkPreparer.java:42)
[   +4 ms]      at
org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer$PopulateWorkGraph.populateTaskGraph(BuildOperationFiri
ngBuildWorkPreparer.java:106)
[   +2 ms]      at
org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer$PopulateWorkGraph.run(BuildOperationFiringBuildWorkPre
parer.java:92)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[   +4 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
[   +1 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
[   +3 ms]      at
org.gradle.internal.build.BuildOperationFiringBuildWorkPreparer.populateWorkGraph(BuildOperationFiringBuildWorkPrepare
r.java:67)
[   +2 ms]      at
org.gradle.internal.build.DefaultBuildLifecycleController.lambda$populateWorkGraph$8(DefaultBuildLifecycleController.j
ava:186)
[   +4 ms]      at org.gradle.internal.model.StateTransitionController.lambda$inState$1(StateTransitionController.java:99)
[   +2 ms]      at
org.gradle.internal.model.StateTransitionController.lambda$inState$2(StateTransitionController.java:114)
[   +2 ms]      at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[   +3 ms]      at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:110)    
[   +2 ms]      at org.gradle.internal.model.StateTransitionController.inState(StateTransitionController.java:98)     
[   +2 ms]      at
org.gradle.internal.build.DefaultBuildLifecycleController.populateWorkGraph(DefaultBuildLifecycleController.java:186) 
[   +1 ms]      at
org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.populateWorkGraph(DefaultBuildWorkGrap
hController.java:169)
[   +2 ms]      at org.gradle.composite.internal.DefaultBuildController.populateWorkGraph(DefaultBuildController.java:76)
[   +2 ms]      at
org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraphBuilder.withWorkGraph(DefaultIncl
udedBuildTaskGraph.java:153)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeWorkPreparer.lambda$scheduleRequestedTasks$1(DefaultBuildTreeWorkPrepare
r.java:41)
[   +3 ms]      at
org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraph$1.run(DefaultIncludedBuildTaskGr
aph.java:209)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
[   +1 ms]      at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
[   +2 ms]      at
org.gradle.composite.internal.DefaultIncludedBuildTaskGraph$DefaultBuildTreeWorkGraph.scheduleWork(DefaultIncludedBuil
dTaskGraph.java:204)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeWorkPreparer.scheduleRequestedTasks(DefaultBuildTreeWorkPreparer.java:37
)
[   +2 ms]      at
org.gradle.configurationcache.VintageBuildTreeWorkController$scheduleAndRunRequestedTasks$1.apply(VintageBuildTreeWork
Controller.kt:36)
[   +4 ms]      at
org.gradle.configurationcache.VintageBuildTreeWorkController$scheduleAndRunRequestedTasks$1.apply(VintageBuildTreeWork
Controller.kt:35)
[   +2 ms]      at
org.gradle.composite.internal.DefaultIncludedBuildTaskGraph.withNewWorkGraph(DefaultIncludedBuildTaskGraph.java:112)  
[   +2 ms]      at
org.gradle.configurationcache.VintageBuildTreeWorkController.scheduleAndRunRequestedTasks(VintageBuildTreeWorkControll
er.kt:35)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$scheduleAndRunTasks$1(DefaultBuildTreeLifecyc
leController.java:68)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleControlle
r.java:98)
[   +2 ms]      at
org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:169)
[   +2 ms]      at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
[   +1 ms]      at
org.gradle.internal.model.StateTransitionController.lambda$transition$7(StateTransitionController.java:169)
[   +1 ms]      at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
[   +1 ms]      at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:169) 
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:95
)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleControl
ler.java:68)
[   +2 ms]      at
org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleControl
ler.java:63)
[   +3 ms]      at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
[   +1 ms]      at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[   +1 ms]      at
org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)        
[   +2 ms]      at
org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)   
[   +2 ms]      at
org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:
140)
[   +3 ms]      at
org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:
41)
[   +2 ms]      at
org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.
java:40)
[   +2 ms]      at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:123)
[   +1 ms]      at
org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40) 
[   +2 ms]      at
org.gradle.internal.buildtree.InitDeprecationLoggingActionExecutor.execute(InitDeprecationLoggingActionExecutor.java:5
8)
[   +2 ms]      at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)     
[   +1 ms]      at
org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.
java:65)
[   +2 ms]      at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:58)
[   +1 ms]      at
org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65) 
[   +2 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
[   +1 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationR
unner.java:204)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationR
unner.java:199)
[   +1 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[   +2 ms]      at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[   +2 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57
)
[   +2 ms]      at
org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.ja
va:36)
[   +2 ms]      at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)   
[   +1 ms]      at
org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
[   +4 ms]      at
org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)   
[   +2 ms]      at
org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.ja
va:110)
[   +2 ms]      at
org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64) 
[   +2 ms]      at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46) 
[   +2 ms]      at
org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBu
ildActionExecuter.java:92)
[   +2 ms]      at
org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBu
ildActionExecuter.java:80)
[   +3 ms]      at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
[   +1 ms]      at
org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildAction
Executer.java:62)
[   +2 ms]      at
org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildAction
Executer.java:41)
[   +1 ms]      at
org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.j
ava:64)
[   +2 ms]      at
org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.j
ava:32)
[   +2 ms]      at
org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecut
er.java:51)
[   +2 ms]      at
org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecut
er.java:39)
[   +2 ms]      at
org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
[   +2 ms]      at
org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
[   +4 ms]      at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
[   +1 ms]      at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
[   +2 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at
org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)   
[   +2 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)     
[   +1 ms]      at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)     
[   +1 ms]      at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
[   +1 ms]      at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)      
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)        
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
[   +1 ms]      at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at
org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
[   +2 ms]      at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
[   +1 ms]      at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
[   +2 ms]      at
org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
[   +2 ms]      at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)    
[   +1 ms]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[   +2 ms]      at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)      
[   +1 ms]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[   +1 ms]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[   +1 ms]      at java.base/java.lang.Thread.run(Unknown Source)
[   +2 ms] Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 21
[   +1 ms]      at org.jetbrains.kotlin.gradle.dsl.JvmTarget$Companion.fromTarget(JvmTarget.kt:27)
[   +1 ms]      at
org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$Companion$wireJvmTargetToJvm$1.invoke(DefaultKotlinJavaTo
olchain.kt:195)
[   +2 ms]      at
org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$Companion$wireJvmTargetToJvm$1.invoke(DefaultKotlinJavaTo
olchain.kt:187)
[   +2 ms]      at
org.jetbrains.kotlin.gradle.tasks.DefaultKotlinJavaToolchain$sam$org_gradle_api_Transformer$0.transform(DefaultKotlinJ
avaToolchain.kt)
[   +2 ms]      at org.gradle.api.internal.provider.ValueSupplier$Present.transform(ValueSupplier.java:541)
[   +2 ms]      at org.gradle.api.internal.provider.TransformBackedProvider.mapValue(TransformBackedProvider.java:91)
[   +1 ms]      at
org.gradle.api.internal.provider.TransformBackedProvider.calculateExecutionTimeValue(TransformBackedProvider.java:76) 
[   +2 ms]      at org.gradle.api.internal.provider.OrElseValueProducer.isMissing(OrElseValueProducer.java:65)        
[   +2 ms]      at org.gradle.api.internal.provider.OrElseValueProducer.visitProducerTasks(OrElseValueProducer.java:53)
[   +2 ms]      at
[   +1 ms]      at
org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:103)
[   +2 ms]      at
org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
[   +2 ms]      at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
[   +2 ms]      at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)[   +1 ms]      at
org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
[   +2 ms]      ... 145 more
[   +2 ms] BUILD FAILED in 5s
[   +2 ms] 4 actionable tasks: 4 up-to-date
[   +1 ms] Watched directory hierarchies: [C:\flutter\packages\flutter_tools\gradle]
[ +500 ms] Running Gradle task 'assembleDebug'... (completed in 7.0s)
[+27533 ms] Error: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 38,917ms.
[ +154 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:860:9)
                    <asynchronous suspension>
                    #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
                    <asynchronous suspension>
                    #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                    <asynchronous suspension>
                    #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                    <asynchronous suspension>
                    #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
                    <asynchronous suspension>
                    #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                    <asynchronous suspension>
                    #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
                    <asynchronous suspension>
                    #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
                    <asynchronous suspension>
                    #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                    <asynchronous suspension>
                    #10     main (package:flutter_tools/executable.dart:94:3)
                    <asynchronous suspension>


[ +263 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running 2 shutdown hooks
[  +17 ms] Shutdown hooks complete
[ +160 ms] exiting with code 1
```
