### ISSUE TITLE
Package roll breaks flutter_tools

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#160055]
See https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20packages_autoroller/13050/infra

```
 Executing [/b/s/w/ir/x/w/flutter_conductor_checkouts/framework/bin/dart, /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart, --no-gradle-generation, --no-exclusion]...
 If you don't wish to re-generate the settings.gradle, build.gradle, and gradle-wrapper.properties files,
 add the flag `--no-gradle-generation`.
 This tool automatically excludes a set of android subdirectories, defined at dev/tools/bin/config/lockfile_exclusion.yaml.
 To disable this behavior, run with `--no-exclusion`.
 Running without exclusion.
 /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/packages/integration_test/android/gradle/wrapper/gradle-wrapper.properties does not exist - skipping
 Processing /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/packages/integration_test/example/android
 Unhandled exception:
 ProcessException: Resolving dependencies...
 Downloading packages...
 Got dependencies.
 Building flutter tool...
 ../../flutter_tools/lib/src/base/analyze_size.dart:152:13: Error: 'InputStreamBase' isn't a type.
       final InputStreamBase? rawContent = archiveFile.rawContent;
             ^^^^^^^^^^^^^^^
   Command: /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/bin/flutter pub get
 #0      exec (file:///b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart:218:5)
 #1      main (file:///b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart:187:5)
 #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
 #3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
 Unhandled exception:
 Exception: ProcessException: ProcessException: Process failed
   Command: /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/bin/dart /b/s/w/ir/x/w/flutter_conductor_checkouts/framework/dev/tools/bin/generate_gradle_lockfiles.dart --no-gradle-generation --no-exclusion
 #0      PackageAutoroller.roll (package:conductor_core/src/packages_autoroller.dart:106:7)
 <asynchronous suspension>
 #1      run (file:///b/s/w/ir/x/w/flutter/dev/conductor/core/bin/packages_autoroller.dart:83:3)
 <asynchronous suspension>
```

Note that this is AFTER we've updated pub packages in the bot, then while building the tool to re-generate gradle lockfiles, we fail compilation.

**Comment by christopherfujino** [comment]
`InputStreamBase` is provided by package:archive, which has had a major version bump and migration guide: https://github.com/brendan-duncan/archive/blob/main/doc/migrating_3_to_4.md

**Comment by christopherfujino** [comment]
cc @bkonyi & @andrewkolos

**Comment by christopherfujino** [comment]
This will be resolved by: https://github.com/flutter/flutter/pull/160174
