### ISSUE TITLE
[google_maps_flutter] Unknown Map Id 0 

### ISSUE THREAD

**Issue by Pakket2Go** [flutter/flutter#160179]
### Steps to reproduce

Its not replicable everytime and happens randomly

```
flutter: Error in fitting markers
flutter: Unknown map ID 0
flutter: #0      GoogleMapsFlutterIOS._hostApi (package:google_maps_flutter_ios/src/google_maps_flutter_ios.dart:73:7)
flutter: #1      GoogleMapsFlutterIOS.getZoomLevel (package:google_maps_flutter_ios/src/google_maps_flutter_ios.dart:429:12)
flutter: #2      GoogleMapController.getZoomLevel (package:google_maps_flutter/src/controller.dart:295:47)
flutter: #3      MapUtils.fitLatLngInMap (package:bmh/meta/utils/map_utils.dart:125:46)
flutter: <asynchronous suspension>
flutter: #4      TraccarHomeController.fitMarkers (package:bmh/components/traccar/screens/traccar_home/traccar_home_controller.dart:301:7)
```

### Expected results

The map controller should work as expected

### Actual results

Map controller throws Unknown map ID  when called.

### Code sample

<details open><summary>Code sample</summary>

```dart
    Listener(
            onPointerMove: widget.onPointerMove,
            child: GoogleMap(
                style: Theme.of(context).brightness == Brightness.dark ? darkMapStyle : null,
                onTap: widget.onTap,
                myLocationButtonEnabled: false,
                myLocationEnabled: widget.showLocationButton,
                mapToolbarEnabled: false,
                rotateGesturesEnabled: false,
                onMapCreated: (e) {
                  mapController = e;
                  widget.onMapCreated?.call(e);

                  for (var element in widget.infoWindows) {
                    element.googleMapController = e;
                  }
                },
                onCameraMove: (e) {
                  widget.onCameraMove?.call(e);
                  for (var element in widget.infoWindows) {
                    element.onCameraMove?.call();
                  }
                },
                compassEnabled: false,
                padding: widget.padding,
                mapType: mapType,
                zoomControlsEnabled: false,
                trafficEnabled: trafficEnabled,
                markers: widget.markers,
                circles: widget.circles,
                polylines: widget.polylines,
                polygons: widget.polygons,
                initialCameraPosition: widget.initialCameraPosition ??
                    const CameraPosition(target: LatLng(52.13159010815422, 5.096997767686844), zoom: 8)),
          ),
       
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="808" alt="image" src="https://github.com/user-attachments/assets/b9c0539e-6bc8-4357-8c13-087699afd0a4" />
https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter_ios/lib/src/google_maps_flutter_ios.dart

</details>

### Logs

<details open><summary>Logs</summary>

```console
flutter: Error in fitting markers
flutter: Unknown map ID 0
flutter: #0      GoogleMapsFlutterIOS._hostApi (package:google_maps_flutter_ios/src/google_maps_flutter_ios.dart:73:7)
flutter: #1      GoogleMapsFlutterIOS.animateCamera (package:google_maps_flutter_ios/src/google_maps_flutter_ios.dart:350:12)
flutter: #2      GoogleMapController.animateCamera (package:google_maps_flutter/src/controller.dart:194:10)
flutter: #3      MapUtils.fitLatLngInMap (package:bmh/meta/utils/map_utils.dart:119:25)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.96.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```
The error comes when using mapController to do anything like animate camera or stuff

</details>

**Comment by maheshj01** [comment]
Hello @Pakket2Go, Thanks for filing the issue. Please share a minimal and complete reproducible code sample to investigate the issue.   Does this issue occures only on ios or android too?

**Comment by Pakket2Go** [comment]
The issue occurs on both, and happens randomly, so there's no actual way of reproducing.

**Comment by maheshj01** [comment]
@Pakket2Go  Without enough information, it will be extremely difficult to find the root cause of the issue. I would suggest sharing more details regarding the issue 
- A minimal complete code sample with which the issue was reproduced
- And the complete logs or output of `flutter run -v` when the issue occured.

Also what version of the maps plugin are you using?
