### ISSUE TITLE
Exception during scheduler callback in rendering/object.dart

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#160115]
### Steps to reproduce

This test https://github.com/flutter/packages/blob/8238e1c5ada8c6a99f7fb6087484b52face33721/packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_controller.dart#L24 
is failing due to this bug

### Expected results

test would pass

### Actual results

https://firebase.corp.google.com/u/0/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/5930255440447877879/details?stepId=bs.4d2e9690cf189957&testCaseId=23&query=et.4a4f17838d485ced&deeplink=true

test fails with exception

### Code sample

https://github.com/flutter/packages/blob/8238e1c5ada8c6a99f7fb6087484b52face33721/packages/google_maps_flutter/google_maps_flutter/example/integration_test/src/maps_controller.dart#L24 

link to code in flutter/packages

### Logs

link to logs 
https://firebase.corp.google.com/u/0/project/flutter-infra-staging/testlab/histories/bh.8eb89ae93eb3eb36/matrices/5930255440447877879/details?stepId=bs.4d2e9690cf189957&testCaseId=23&query=et.4a4f17838d485ced&deeplink=true

### Flutter Doctor output

This is in the flutter packages ci, I don't have access to the doctor output

**Comment by tarrinneal** [comment]
This is currently blocking the flutter -> packages roller. I will be temporarily disabling the test to allow for rolls.
https://github.com/flutter/packages/pull/8269 (failing roll)
which is rolling an engine -> flutter roll into packages https://github.com/flutter/flutter/pull/159858
likely cause is a dart -> engine roll https://github.com/flutter/engine/pull/56980

Based on conversation with @stuartmorgan , it may be a race condition in the framework that has been subtly altered due to a change in Dart.

**Comment by goderbauer** [comment]
This looks like a crash in the semantics tree compiler:

```
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/object.dart': Failed assertion:
line 4791 pos 12: '!node.isInvisible || children.isEmpty': is not
true.
Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
https://github.com/flutter/flutter/issues/new?template=2_bug.yml
When the exception was thrown, this was the stack:
#2 _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4791:12)
#3 RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3730:25)
#4 PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1313:16)
#5 PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1318:15)
#6 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:616:25)
#7 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178:13)
#8 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#9 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#10 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#11 LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1809:13)
#12 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#16 _invoke (dart:ui/hooks.dart:314:10)
#17 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
#18 _drawFrame (dart:ui/hooks.dart:283:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by chunhtai** [comment]
I can't reproduce locally, I will try to reenable the test and see if it still fails
