### ISSUE TITLE
Unhandled exception aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#160137]
### Steps to reproduce

The `flutter build appbundle` command is failing with the following exception on a large private project (the full exception log is below).

```
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Reference to package:flutter_soloud/src/sound_handle.dart::SoundHandle is not bound to an AST node. An extension type declaration was expected
```

I wasn't been able to reproduce it in an isolated project and `flutter build appbundle` command works on the example app from the `flutter_soloud`.

If it would help, the `SoundHandle` extension type from [flutter_soloud](https://github.com/alnitak/flutter_soloud/blob/5303435ce7ce5a3fdba6b564e62a81c953bd9e49/lib/src/sound_handle.dart#L19-L38) is declared like this:

```
extension type const SoundHandle._(int id) {
  /// Constructs a valid handle with [id].
  @internal
  const SoundHandle(this.id)
      : assert(
            id >= 0,
            'Handle with id<0 is being constructed. '
            'These are reserved for invalid handles.');

  /// Constructs an invalid handle (for APIs that need to return _some_ handle
  /// even during errors).
  @internal
  const SoundHandle.error() : this._(-1);

  /// Checks if the handle represents an error (it was constructed
  /// with [SoundHandle.error]).
  ///
  /// Does _not_ check whether the handle is "valid" (i.e. attached
  /// to an active sound) or not.
  bool get isError => id < 0;
}
```

### Expected results

The build should success

### Actual results

IconTreeShakerException

### Code sample

<details open><summary>Code sample</summary>

```dart
N/A
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Reference to package:flutter_soloud/src/sound_handle.dart::SoundHandle is not bound to an AST node. An extension type declaration was expected
#0      Reference.asExtensionTypeDeclaration (package:kernel/canonical_name.dart:559:7)
#1      ExtensionType.extensionTypeDeclaration (package:kernel/src/ast/types.dart:1363:41)
#2      ExtensionType.visitChildren (package:kernel/src/ast/types.dart:1460:5)
#3      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#4      VisitorDefault.defaultDartType (package:kernel/visitor.dart:1524:39)
#5      DartTypeVisitorDefaultMixin.visitExtensionType (package:kernel/visitor.dart:804:47)
#6      ExtensionType.accept (package:kernel/src/ast/types.dart:1450:14)
#7      InstanceGet.visitChildren (package:kernel/src/ast/expressions.dart:588:16)
#8      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#9      VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#10     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#11     ExpressionVisitorDefaultMixin.visitInstanceGet (package:kernel/visitor.dart:107:43)
#12     InstanceGet.accept (package:kernel/src/ast/expressions.dart:577:44)
#13     EqualsNull.visitChildren (package:kernel/src/ast/expressions.dart:2244:16)
#14     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#15     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#16     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#17     ExpressionVisitorDefaultMixin.visitEqualsNull (package:kernel/visitor.dart:141:41)
#18     EqualsNull.accept (package:kernel/src/ast/expressions.dart:2236:44)
#19     Not.visitChildren (package:kernel/src/ast/expressions.dart:2834:13)
#20     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#21     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#22     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#23     ExpressionVisitorDefaultMixin.visitNot (package:kernel/visitor.dart:156:27)
#24     Not.accept (package:kernel/src/ast/expressions.dart:2827:44)
#25     IfStatement.visitChildren (package:kernel/src/ast/statements.dart:1021:15)
#26     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#27     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#28     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#29     StatementVisitorDefaultMixin.visitIfStatement (package:kernel/visitor.dart:373:43)
#30     IfStatement.accept (package:kernel/src/ast/statements.dart:1013:43)
#31     visitList (package:kernel/src/ast/helpers.dart:91:14)
#32     Block.visitChildren (package:kernel/src/ast/statements.dart:110:5)
#33     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#34     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#35     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#36     StatementVisitorDefaultMixin.visitBlock (package:kernel/visitor.dart:345:31)
#37     Block.accept (package:kernel/src/ast/statements.dart:103:43)
#38     FunctionNode.visitChildren (package:kernel/src/ast/functions.dart:231:11)
#39     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#40     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#41     TreeVisitorDefaultMixin.visitFunctionNode (package:kernel/visitor.dart:577:45)
#42     FunctionNode.accept (package:kernel/src/ast/functions.dart:214:38)
#43     Procedure.visitChildren (package:kernel/src/ast/members.dart:1212:14)
#44     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#45     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#46     TreeVisitorDefault.defaultMember (package:kernel/visitor.dart:626:35)
#47     MemberVisitorDefaultMixin.visitProcedure (package:kernel/visitor.dart:411:39)
#48     _ConstVisitor.visitProcedure (package:kernel/const_finder.dart:97:11)
#49     Procedure.accept (package:kernel/src/ast/members.dart:1199:40)
#50     visitList (package:kernel/src/ast/helpers.dart:91:14)
#51     Class.visitChildren (package:kernel/src/ast/declarations.dart:519:5)
#52     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#53     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#54     TreeVisitorDefaultMixin.visitClass (package:kernel/visitor.dart:556:31)
#55     _ConstVisitor.visitClass (package:kernel/const_finder.dart:132:11)
#56     Class.accept (package:kernel/src/ast/declarations.dart:481:38)
#57     visitList (package:kernel/src/ast/helpers.dart:91:14)
#58     Library.visitChildren (package:kernel/src/ast/libraries.dart:336:5)
#59     ConstFinder.findInstances (package:kernel/const_finder.dart:208:15)
#60     main (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#61     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#62     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.0, on macOS 13.6.6 22G630 darwin-arm64, locale en-CA)
    • Flutter version 3.27.0 on channel stable at ***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (29 hours ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at ***
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode_15.2.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23177

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 13.6.6 22G630 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 13.6.6 22G630 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.110

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ekuleshov, can you provide the full output of `flutter build appbundle -v`? The output may be huge so kindly put it into a .txt file and attach it here. Could you also try the master channel to see if this reproduces there as well?

**Comment by ekuleshov** [comment]
> Hi @ekuleshov, can you provide the full output of `flutter build appbundle -v`? The output may be huge so kindly put it into a .txt file and attach it here. Could you also try the master channel to see if this reproduces there as well?

[a.txt](https://github.com/user-attachments/files/18112879/a.txt) from stable.

And here is the same error with stacktrace with master channel

```
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Reference to package:flutter_soloud/src/sound_handle.dart::SoundHandle is not bound to an AST node. An extension type declaration was expected
#0      Reference.asExtensionTypeDeclaration (package:kernel/canonical_name.dart:559:7)
#1      ExtensionType.extensionTypeDeclaration (package:kernel/src/ast/types.dart:1364:41)
#2      ExtensionType.visitChildren (package:kernel/src/ast/types.dart:1461:5)
#3      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#4      VisitorDefault.defaultDartType (package:kernel/visitor.dart:1524:39)
#5      DartTypeVisitorDefaultMixin.visitExtensionType (package:kernel/visitor.dart:804:47)
#6      ExtensionType.accept (package:kernel/src/ast/types.dart:1451:14)
#7      InstanceGet.visitChildren (package:kernel/src/ast/expressions.dart:588:16)
#8      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#9      VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#10     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#11     ExpressionVisitorDefaultMixin.visitInstanceGet (package:kernel/visitor.dart:107:43)
#12     InstanceGet.accept (package:kernel/src/ast/expressions.dart:577:44)
#13     EqualsNull.visitChildren (package:kernel/src/ast/expressions.dart:2244:16)
#14     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#15     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#16     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#17     ExpressionVisitorDefaultMixin.visitEqualsNull (package:kernel/visitor.dart:141:41)
#18     EqualsNull.accept (package:kernel/src/ast/expressions.dart:2236:44)
#19     Not.visitChildren (package:kernel/src/ast/expressions.dart:2834:13)
#20     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#21     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#22     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#23     ExpressionVisitorDefaultMixin.visitNot (package:kernel/visitor.dart:156:27)
#24     Not.accept (package:kernel/src/ast/expressions.dart:2827:44)
#25     IfStatement.visitChildren (package:kernel/src/ast/statements.dart:1021:15)
#26     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#27     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#28     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#29     StatementVisitorDefaultMixin.visitIfStatement (package:kernel/visitor.dart:373:43)
#30     IfStatement.accept (package:kernel/src/ast/statements.dart:1013:43)
#31     visitList (package:kernel/src/ast/helpers.dart:91:14)
#32     Block.visitChildren (package:kernel/src/ast/statements.dart:110:5)
#33     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#34     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#35     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#36     StatementVisitorDefaultMixin.visitBlock (package:kernel/visitor.dart:345:31)
#37     Block.accept (package:kernel/src/ast/statements.dart:103:43)
#38     FunctionNode.visitChildren (package:kernel/src/ast/functions.dart:231:11)
#39     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#40     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#41     TreeVisitorDefaultMixin.visitFunctionNode (package:kernel/visitor.dart:577:45)
#42     FunctionNode.accept (package:kernel/src/ast/functions.dart:214:38)
#43     Procedure.visitChildren (package:kernel/src/ast/members.dart:1212:14)
#44     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#45     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#46     TreeVisitorDefault.defaultMember (package:kernel/visitor.dart:626:35)
#47     MemberVisitorDefaultMixin.visitProcedure (package:kernel/visitor.dart:411:39)
#48     _ConstVisitor.visitProcedure (package:kernel/const_finder.dart:97:11)
#49     Procedure.accept (package:kernel/src/ast/members.dart:1199:40)
#50     visitList (package:kernel/src/ast/helpers.dart:91:14)
#51     Class.visitChildren (package:kernel/src/ast/declarations.dart:519:5)
#52     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#53     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#54     TreeVisitorDefaultMixin.visitClass (package:kernel/visitor.dart:556:31)
#55     _ConstVisitor.visitClass (package:kernel/const_finder.dart:132:11)
#56     Class.accept (package:kernel/src/ast/declarations.dart:481:38)
#57     visitList (package:kernel/src/ast/helpers.dart:91:14)
#58     Library.visitChildren (package:kernel/src/ast/libraries.dart:336:5)
#59     ConstFinder.findInstances (package:kernel/const_finder.dart:208:15)
#60     main (file:///Volumes/Work/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#61     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#62     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
```

**Comment by danagbemava-nc** [comment]
Hi @ekuleshov, thanks for the update. 

Labeling this for further investigation from the team

**Comment by mraleph** [comment]
cc @alexmarkov @jensjoha

**Comment by jensjoha** [comment]
Reproduction:

`test.dart`:
```dart
import 'test_lib.dart';

void main() {
  Class c = new Class();
  c.procedure();
}

class Class {
  void procedure() {
    Helper helper = new Helper();
    if (helper.instance != null) {
      print("hello");
    }
  }
}

class Helper {
  Helper();
  MyExtensionType? get instance {
    return null;
  }
}
```

`test_lib.dart`:
```dart
extension type const MyExtensionType._(int foo) {}
```

compiled like this:
```
out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform  out/ReleaseX64/vm_platform_strong.dill --aot test.dart
```

We then get this crash if trying to dump the kernel like `out/ReleaseX64/dart pkg/vm/bin/dump_kernel.dart test.dart.dill test.dart.dill.txt`:
```

Unhandled exception:
Reference to test_lib.dart::MyExtensionType is not bound to an AST node. An extension type declaration was expected
#0      Reference.asExtensionTypeDeclaration (package:kernel/canonical_name.dart:559:7)
#1      ExtensionType.extensionTypeDeclaration (package:kernel/src/ast/types.dart:1364:41)
#2      ExtensionType.nullability (package:kernel/src/ast/types.dart:1393:16)
#3      Printer.visitExtensionType (package:kernel/text/ast_to_text.dart:2627:27)
#4      ExtensionType.accept (package:kernel/src/ast/types.dart:1451:14)
#5      Printer.writeType (package:kernel/text/ast_to_text.dart:661:10)
#6      Printer.visitInstanceGet (package:kernel/text/ast_to_text.dart:2048:5)
#7      InstanceGet.accept (package:kernel/src/ast/expressions.dart:577:44)
#8      Printer.writeNode (package:kernel/text/ast_to_text.dart:621:12)
#9      Printer.writeExpression (package:kernel/text/ast_to_text.dart:1027:5)
#10     Printer.visitExpressionStatement (package:kernel/text/ast_to_text.dart:2165:5)
#11     ExpressionStatement.accept (package:kernel/src/ast/statements.dart:50:43)
#12     Printer.writeNode (package:kernel/text/ast_to_text.dart:621:12)
#13     List.forEach (dart:core-patch/growable_array.dart:421:8)
#14     Printer.writeBlockBody (package:kernel/text/ast_to_text.dart:2176:16)
#15     Printer.visitBlock (package:kernel/text/ast_to_text.dart:2185:5)
#16     Block.accept (package:kernel/src/ast/statements.dart:103:43)
#17     Printer.writeNode (package:kernel/text/ast_to_text.dart:621:12)
#18     List.forEach (dart:core-patch/growable_array.dart:421:8)
#19     Printer.writeFunctionBody (package:kernel/text/ast_to_text.dart:792:23)
#20     Printer.writeFunction (package:kernel/text/ast_to_text.dart:759:7)
#21     Printer.visitProcedure (package:kernel/text/ast_to_text.dart:1157:9)
#22     Procedure.accept (package:kernel/src/ast/members.dart:1199:40)
#23     Printer.writeNode (package:kernel/text/ast_to_text.dart:621:12)
#24     ListBase.forEach (dart:collection/list.dart:51:13)
#25     Printer.visitClass (package:kernel/text/ast_to_text.dart:1246:21)
#26     Class.accept (package:kernel/src/ast/declarations.dart:481:38)
#27     Printer.writeNode (package:kernel/text/ast_to_text.dart:621:12)
#28     List.forEach (dart:core-patch/growable_array.dart:421:8)
#29     Printer.writeStandardLibraryContent (package:kernel/text/ast_to_text.dart:450:21)
#30     Printer.writeComponentFile (package:kernel/text/ast_to_text.dart:531:13)
#31     writeComponentToText (package:kernel/kernel.dart:76:8)
#32     main (pkg/vm/bin/dump_kernel.dart:59:3)
#33     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#34     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
```

or via this helper that should reproduce the const finder user in flutter:
```dart
import 'dart:convert';
import 'dart:io';

import 'package:kernel/const_finder.dart';

void main(List<String> args) {
  File appDill = new File(args.single);
  final String annotationClassName = "_StaticIconProvider";
  final String annotationClassLibraryUri = "package:flutter/src/widgets/icon_data.dart";

  final ConstFinder finder = ConstFinder(
    kernelFilePath: appDill.path,
    classLibraryUri: "package:flutter/src/widgets/icon_data.dart",
    className: "IconData",
    annotationClassName: annotationClassName,
    annotationClassLibraryUri: annotationClassLibraryUri,
  );

  final JsonEncoder encoder = const JsonEncoder.withIndent('  ');
  stdout.writeln(encoder.convert(finder.findInstances()));
}
```

I get this crash:

```
Unhandled exception:
Reference to test_lib.dart::MyExtensionType is not bound to an AST node. An extension type declaration was expected
#0      Reference.asExtensionTypeDeclaration (package:kernel/canonical_name.dart:559:7)
#1      ExtensionType.extensionTypeDeclaration (package:kernel/src/ast/types.dart:1364:41)
#2      ExtensionType.visitChildren (package:kernel/src/ast/types.dart:1461:5)
#3      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#4      VisitorDefault.defaultDartType (package:kernel/visitor.dart:1524:39)
#5      DartTypeVisitorDefaultMixin.visitExtensionType (package:kernel/visitor.dart:804:47)
#6      ExtensionType.accept (package:kernel/src/ast/types.dart:1451:14)
#7      InstanceGet.visitChildren (package:kernel/src/ast/expressions.dart:588:16)
#8      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#9      VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#10     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#11     ExpressionVisitorDefaultMixin.visitInstanceGet (package:kernel/visitor.dart:107:43)
#12     InstanceGet.accept (package:kernel/src/ast/expressions.dart:577:44)
#13     ExpressionStatement.visitChildren (package:kernel/src/ast/statements.dart:58:16)
#14     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#15     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#16     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#17     StatementVisitorDefaultMixin.visitExpressionStatement (package:kernel/visitor.dart:343:7)
#18     ExpressionStatement.accept (package:kernel/src/ast/statements.dart:50:43)
#19     visitList (package:kernel/src/ast/helpers.dart:91:14)
#20     Block.visitChildren (package:kernel/src/ast/statements.dart:110:5)
#21     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#22     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#23     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#24     StatementVisitorDefaultMixin.visitBlock (package:kernel/visitor.dart:345:31)
#25     Block.accept (package:kernel/src/ast/statements.dart:103:43)
#26     visitList (package:kernel/src/ast/helpers.dart:91:14)
#27     Block.visitChildren (package:kernel/src/ast/statements.dart:110:5)
#28     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#29     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#30     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#31     StatementVisitorDefaultMixin.visitBlock (package:kernel/visitor.dart:345:31)
#32     Block.accept (package:kernel/src/ast/statements.dart:103:43)
#33     FunctionNode.visitChildren (package:kernel/src/ast/functions.dart:231:11)
#34     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#35     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#36     TreeVisitorDefaultMixin.visitFunctionNode (package:kernel/visitor.dart:577:45)
#37     FunctionNode.accept (package:kernel/src/ast/functions.dart:214:38)
#38     Procedure.visitChildren (package:kernel/src/ast/members.dart:1212:14)
#39     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#40     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#41     TreeVisitorDefault.defaultMember (package:kernel/visitor.dart:626:35)
#42     MemberVisitorDefaultMixin.visitProcedure (package:kernel/visitor.dart:411:39)
#43     _ConstVisitor.visitProcedure (package:kernel/const_finder.dart:97:11)
#44     Procedure.accept (package:kernel/src/ast/members.dart:1199:40)
#45     visitList (package:kernel/src/ast/helpers.dart:91:14)
#46     Class.visitChildren (package:kernel/src/ast/declarations.dart:519:5)
#47     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#48     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#49     TreeVisitorDefaultMixin.visitClass (package:kernel/visitor.dart:556:31)
#50     _ConstVisitor.visitClass (package:kernel/const_finder.dart:132:11)
#51     Class.accept (package:kernel/src/ast/declarations.dart:481:38)
#52     visitList (package:kernel/src/ast/helpers.dart:91:14)
#53     Library.visitChildren (package:kernel/src/ast/libraries.dart:336:5)
#54     ConstFinder.findInstances (package:kernel/const_finder.dart:208:15)
#55     main (helper.dart:20:41)
#56     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:313:33)
#57     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
```

I believe what happens is that the tree shaker has decided that the lib library isn't needed at all, but as it is referenced from the return value of `instance` it will be serialized as we for instance serialize references to the platform when not including the platform, i.e. once we load it we expect it to be loaded later (before actually using it).

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/401481

**Comment by alexmarkov** [comment]
The fix rolled into Flutter in https://github.com/flutter/flutter/commit/895f0e291af00c3d45df0d931900bbad3061b681.

**Comment by ekuleshov** [comment]
@mraleph @alexmarkov Thank  you guys! I should have reported it earlier...

Is this one severe enough for the flutter cherry-picks? Or I'll have to wait til the next Flutter stable?
