### ISSUE TITLE
examples/layers can't run formally on linux

### ISSUE THREAD

**Issue by wucong1997** [flutter/flutter#160157]
### Steps to reproduce

1. cd examples/layers
2. flutter run rendering/hello_world.dart
3. choose linux

### Expected results

texts are displayed on the screen

### Actual results

![image](https://github.com/user-attachments/assets/6b420231-3e7d-43fa-882d-477194c54b06)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>
[✓] Flutter (Channel master, 3.28.0-1.0.pre.87, on Ubuntu 22.04.5 LTS 6.8.0-49-generic, locale zh_CN.UTF-8)
    • Flutter version 3.28.0-1.0.pre.87 on channel master at /home/wucong/flutter_ori/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = https://github.com/flutter/flutter.git
    • Framework revision 3a4b07bf52 (8 小时前), 2024-12-11 22:13:39 -0500
    • Engine revision 847deb2089
    • Dart version 3.7.0 (build 3.7.0-237.0.dev)
    • DevTools version 2.41.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/linux-android-setup for detailed instructions).

[✓] VS Code (version 1.93.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.5 LTS 6.8.0-49-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.139

[✓] Network resources
    • All expected network resources are available.
```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the hello_world.dart, spinning_square.dart, touch_input.dart examples in the examples/layers directory in the framework (other examples could be affected, but these were the ones I tested). 

Reproduces on my Pixel 7, the iOS 18.2 simulator. MacOS works as expected. 

```
Launching rendering/hello_world.dart on Pixel 7 in debug mode...
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
✓ Built build/app/outputs/flutter-apk/app-debug.apk
I/flutter (25209): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Connecting to VM Service at ws://127.0.0.1:62282/aLu6122wgok=/ws
Connected to the VM Service.
E/flutter (25209): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
E/flutter (25209): #0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
E/flutter (25209): #1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
E/flutter (25209): #2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
E/flutter (25209): #3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
E/flutter (25209): #4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
E/flutter (25209): #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
E/flutter (25209): #6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
E/flutter (25209): #7      new BindingBase (package:flutter/src/foundation/binding.dart:164:5)
E/flutter (25209): #8      new _RenderingFlutterBinding&BindingBase&GestureBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #9      new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #10     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #11     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #12     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #13     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #14     new RenderingFlutterBinding (package:flutter/src/rendering/binding.dart)
E/flutter (25209): #15     new ViewRenderingFlutterBinding (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
E/flutter (25209): #16     main (file:///Users/deanli/dev/stable/examples/layers/rendering/hello_world.dart:14:3)
E/flutter (25209): #17     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (25209): #18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (25209): #19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (25209):
D/ProfileInstaller(25209): Installing profile for io.flutter.examples.layers
I/examples.layers(25209): Background concurrent mark compact GC freed 26MB AllocSpace bytes, 3(60KB) LOS objects, 90% free, 2518KB/26MB, paused 263us,28.317ms total 83.788ms
```

```
Launching rendering/hello_world.dart on iPhone 16 Pro in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           24.1s
Connecting to VM Service at ws://127.0.0.1:63610/Ncn15nBELSo=/ws
Connected to the VM Service.
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
#0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
#1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
#2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
#3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
#4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
#5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
#6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
#7      new BindingBase (package:flutter/src/fou<…>
```

```
Launching rendering/hello_world.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000329201AD1001E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008103-000329201AD1001E, name:My Mac }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
✓ Built build/macos/Build/Products/Debug/layers.app
Connecting to VM Service at ws://127.0.0.1:64715/NG2Ub4dYaD4=/ws
Connected to the VM Service.
2024-12-12 13:04:08.119 layers[30098:346712] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-12 13:04:08.119 layers[30098:346712] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.87, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.87 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a4b07bf52 (10 hours ago), 2024-12-11 22:13:39 -0500
    • Engine revision 847deb2089
    • Dart version 3.7.0 (build 3.7.0-237.0.dev)
    • DevTools version 2.41.0

```

</details>

**Comment by wucong1997** [comment]
> Reproducible using the hello_world.dart, spinning_square.dart, touch_input.dart examples in the examples/layers directory in the framework (other examples could be affected, but these were the ones I tested).
> 
> Reproduces on my Pixel 7, the iOS 18.2 simulator. MacOS works as expected.
> 
> ```
> Launching rendering/hello_world.dart on Pixel 7 in debug mode...
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> warning: [options] source value 8 is obsolete and will be removed in a future release
> warning: [options] target value 8 is obsolete and will be removed in a future release
> warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
> 3 warnings
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk
> I/flutter (25209): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
> Connecting to VM Service at ws://127.0.0.1:62282/aLu6122wgok=/ws
> Connected to the VM Service.
> E/flutter (25209): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
> E/flutter (25209): #0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> E/flutter (25209): #1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
> E/flutter (25209): #2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
> E/flutter (25209): #3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
> E/flutter (25209): #4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
> E/flutter (25209): #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
> E/flutter (25209): #6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
> E/flutter (25209): #7      new BindingBase (package:flutter/src/foundation/binding.dart:164:5)
> E/flutter (25209): #8      new _RenderingFlutterBinding&BindingBase&GestureBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #9      new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #10     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #11     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #12     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #13     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #14     new RenderingFlutterBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #15     new ViewRenderingFlutterBinding (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> E/flutter (25209): #16     main (file:///Users/deanli/dev/stable/examples/layers/rendering/hello_world.dart:14:3)
> E/flutter (25209): #17     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
> E/flutter (25209): #18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
> E/flutter (25209): #19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> E/flutter (25209):
> D/ProfileInstaller(25209): Installing profile for io.flutter.examples.layers
> I/examples.layers(25209): Background concurrent mark compact GC freed 26MB AllocSpace bytes, 3(60KB) LOS objects, 90% free, 2518KB/26MB, paused 263us,28.317ms total 83.788ms
> ```
> 
> ```
> Launching rendering/hello_world.dart on iPhone 16 Pro in debug mode...
> Warning: Missing build name (CFBundleShortVersionString).
> Warning: Missing build number (CFBundleVersion).
> Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
> Xcode build done.                                           24.1s
> Connecting to VM Service at ws://127.0.0.1:63610/Ncn15nBELSo=/ws
> Connected to the VM Service.
> [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
> #0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> #1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
> #2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
> #3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
> #4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
> #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
> #6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
> #7      new BindingBase (package:flutter/src/fou<…>
> ```
> 
> ```
> Launching rendering/hello_world.dart on macOS in debug mode...
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:arm64, id:00008103-000329201AD1001E, name:My Mac }
> { platform:macOS, arch:x86_64, id:00008103-000329201AD1001E, name:My Mac }
> warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
> ✓ Built build/macos/Build/Products/Debug/layers.app
> Connecting to VM Service at ws://127.0.0.1:64715/NG2Ub4dYaD4=/ws
> Connected to the VM Service.
> 2024-12-12 13:04:08.119 layers[30098:346712] +[IMKClient subclass]: chose IMKClient_Modern
> 2024-12-12 13:04:08.119 layers[30098:346712] +[IMKInputSession subclass]: chose IMKInputSession_Modern
> ```
> 
> flutter doctor -v



> Reproducible using the hello_world.dart, spinning_square.dart, touch_input.dart examples in the examples/layers directory in the framework (other examples could be affected, but these were the ones I tested).
> 
> Reproduces on my Pixel 7, the iOS 18.2 simulator. MacOS works as expected.
> 
> ```
> Launching rendering/hello_world.dart on Pixel 7 in debug mode...
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> warning: [options] source value 8 is obsolete and will be removed in a future release
> warning: [options] target value 8 is obsolete and will be removed in a future release
> warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
> 3 warnings
> ✓ Built build/app/outputs/flutter-apk/app-debug.apk
> I/flutter (25209): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
> Connecting to VM Service at ws://127.0.0.1:62282/aLu6122wgok=/ws
> Connected to the VM Service.
> E/flutter (25209): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
> E/flutter (25209): #0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> E/flutter (25209): #1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
> E/flutter (25209): #2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
> E/flutter (25209): #3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
> E/flutter (25209): #4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
> E/flutter (25209): #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
> E/flutter (25209): #6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
> E/flutter (25209): #7      new BindingBase (package:flutter/src/foundation/binding.dart:164:5)
> E/flutter (25209): #8      new _RenderingFlutterBinding&BindingBase&GestureBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #9      new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #10     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #11     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #12     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #13     new _RenderingFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&SemanticsBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #14     new RenderingFlutterBinding (package:flutter/src/rendering/binding.dart)
> E/flutter (25209): #15     new ViewRenderingFlutterBinding (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> E/flutter (25209): #16     main (file:///Users/deanli/dev/stable/examples/layers/rendering/hello_world.dart:14:3)
> E/flutter (25209): #17     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
> E/flutter (25209): #18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
> E/flutter (25209): #19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> E/flutter (25209):
> D/ProfileInstaller(25209): Installing profile for io.flutter.examples.layers
> I/examples.layers(25209): Background concurrent mark compact GC freed 26MB AllocSpace bytes, 3(60KB) LOS objects, 90% free, 2518KB/26MB, paused 263us,28.317ms total 83.788ms
> ```
> 
> ```
> Launching rendering/hello_world.dart on iPhone 16 Pro in debug mode...
> Warning: Missing build name (CFBundleShortVersionString).
> Warning: Missing build number (CFBundleVersion).
> Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
> Xcode build done.                                           24.1s
> Connecting to VM Service at ws://127.0.0.1:63610/Ncn15nBELSo=/ws
> Connected to the VM Service.
> [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: LateInitializationError: Field '_renderView@21044400' has not been initialized.
> #0      ViewRenderingFlutterBinding._renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart)
> #1      ViewRenderingFlutterBinding.renderView (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:39:32)
> #2      ViewRenderingFlutterBinding.createRootPipelineOwner.<anonymous closure> (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:59:9)
> #3      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1266:34)
> #4      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1368:5)
> #5      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:58:23)
> #6      ViewRenderingFlutterBinding.initInstances (file:///Users/deanli/dev/stable/examples/layers/rendering/src/binding.dart:28:11)
> #7      new BindingBase (package:flutter/src/fou<…>
> ```
> 
> ```
> Launching rendering/hello_world.dart on macOS in debug mode...
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:arm64, id:00008103-000329201AD1001E, name:My Mac }
> { platform:macOS, arch:x86_64, id:00008103-000329201AD1001E, name:My Mac }
> warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
> ✓ Built build/macos/Build/Products/Debug/layers.app
> Connecting to VM Service at ws://127.0.0.1:64715/NG2Ub4dYaD4=/ws
> Connected to the VM Service.
> 2024-12-12 13:04:08.119 layers[30098:346712] +[IMKClient subclass]: chose IMKClient_Modern
> 2024-12-12 13:04:08.119 layers[30098:346712] +[IMKInputSession subclass]: chose IMKInputSession_Modern
> ```
> 
> flutter doctor -v

Is there a plan to fix this bug? Could you provide a fix idea? I want to fix this bug locally as soon as possible.

**Comment by goderbauer** [comment]
From the stack traces it looks like there could be a race condition between creating the RenderView at ...

https://github.com/flutter/flutter/blob/3762f2e9731ce97808fb2d78805f6712be83654d/examples/layers/rendering/src/binding.dart#L31

... and enabling semantics on it at ...

https://github.com/flutter/flutter/blob/3762f2e9731ce97808fb2d78805f6712be83654d/examples/layers/rendering/src/binding.dart#L59

With the right timing (e.g. when the platform reports that semantics should be turned on before the app is fully launched) it is possible that the binding is calling `renderView.scheduleInitialSemantics()` before it has created that `renderView` because triggering the `onSemanticsOwnerCreated` callback could potentially happen in the `super.initInstances()` call of the `ViewRenderingFlutterBinding` binding.

**Comment by goderbauer** [comment]
As far as I can tell, this is exclusively a problem of the `ViewRenderingFlutterBinding` used by the `layers` example. The bindings shipped with the framework seem to not have this problem.

**Comment by wucong1997** [comment]
> As far as I can tell, this is exclusively a problem of the `ViewRenderingFlutterBinding` used by the `layers` example. The bindings shipped with the framework seem to not have this problem.

how to fix it in the layers examples?
