### ISSUE TITLE
 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true. when emulation touches on a mobile device with a mouse

### ISSUE THREAD

**Issue by himxnshudxhiyx** [flutter/flutter#160144]
### Steps to reproduce

Just Tap on the Mobile Screen with the help of TouchPad of your laptop

### Expected results

It should not come and not shown in the terminal

### Actual results

Getting the Issue ->

<details open><summary>Logs</summary>

```console

======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      MouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracker.dart:224:12)
#3      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:318:10)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:20)
#5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#8      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
#11     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1141" alt="Screenshot 2024-12-12 at 1 07 14 PM" src="https://github.com/user-attachments/assets/5fde0e5f-ead2-45e3-9496-48ac18c158c5" />

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Hardik's iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for AKSHAY DAHIYA’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Himanshu’s iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @himxnshudxhiyx, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can properly investigate this. 

Also, what device(s) are you seeing this issue on?

**Comment by JaffaKetchup** [comment]
This occurs on any scrolling gesture. ie. an extremely simple app with just a lone `ListView` is enough to trigger the issue. In some cases, the scrolling gesture does not work at all, other times it reverts to its previous state, other times it works.

I'm reproducing this on an Android device remote controlled through [scrcpy](https://github.com/Genymobile/scrcpy). I imagine it would happen any time a touch event is being emulated by a mouse cursor?

**Comment by danagbemava-nc** [comment]
Hi @JaffaKetchup, if you use an actual mouse, do you still get this issue or is it only through scrcpy? I tested with a mouse connected to my device and I did not see any errors in my console and scrolling worked as expected. See the recording below


https://github.com/user-attachments/assets/04763004-ecc8-4fea-93f1-e055bc58d431

**Comment by JaffaKetchup** [comment]
The issue does not occur when using a mouse on the same Android device. I imagine it only happens when a touchscreen touch is emulated by a mouse, such as with scrcpy or other remote control software.

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample below and the scrcpy tool. It worked as expected with an actual mouse connected to the device. This did not occur when I used the Vysor tool. 

Labeling for further investigation. 

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(),
        body: ListView.builder(
          itemBuilder: (context, index) {
            return ListTile(
              title: Text('item ${index + 1}'),
            );
          },
          itemCount: 50,
        ),
      ),
    );
  }
}

```
</details>



```
Launching lib/main.dart on Pixel 7 in debug mode...
Warning: Errors during XML parse:
Warning: Additionally, the fallback loader failed to parse the XML.
✓ Built build/app/outputs/flutter-apk/app-debug.apk
I/flutter (21659): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
Connecting to VM Service at ws://127.0.0.1:50453/B2ia_uAQx3I=/ws
Connected to the VM Service.
D/ProfileInstaller(21659): Installing profile for com.example.lighthouse
I/Choreographer(21659): Skipped 54 frames!  The application may be doing too much work on its main thread.

════════ Exception caught by gestures library ══════════════════════════════════
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      MouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracker.dart:224:12)
#3      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:318:10)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:20)
#5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#8      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#9      _invoke1 (dart:ui/hooks.dart:329:13)
#10     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
#11     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gestures library ══════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.
════════════════════════════════════════════════════════════════════════════════
Application finished.

Exited.
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (13 hours ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.157, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.157 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 27ef1967b0 (3 hours ago), 2024-12-16 20:29:14 -0800
    • Engine revision 23731d6a96
    • Dart version 3.7.0 (build 3.7.0-256.0.dev)
    • DevTools version 2.41.0

```
</details>

**Comment by s9th** [comment]
I can also add that I see the same error in Flutter Web project.

**Comment by AlexV525** [comment]
This is reproducible with `scrcpy` when your mouse button is lifted from any position of the view.

**Comment by barankutluay** [comment]
> This is reproducible with `scrcpy` when your mouse button is lifted from any position of the view.

+1

**Comment by himxnshudxhiyx** [comment]
Is there any way to overcome this?

**Comment by AslamNazeerShaikh** [comment]
Hi I am facing same issue. 

![Image](https://github.com/user-attachments/assets/caf1dc00-20d4-4d9e-ba85-5cbced9588d3)

**Comment by criscardozo** [comment]
Any news? Thanks!

**Comment by niamotullah** [comment]
I'm also facing that issue when hover or click on screen when mirroring using [scrcpy](https://github.com/Genymobile/scrcpy).

> # logs
```logs
Restarted application in 3,781ms.
D/ViewRootImplExtImpl(17473): the up motion event handled by client, just return
D/ViewRootImplExtImpl(17473): the up motion event handled by client, just return

════════ Exception caught by gestures library ══════════════════════════════════
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      MouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracker.dart:224:12)
#3      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:318:10)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:20)
#5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#8      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
#11     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```
> # System
```bash
$ flutter --version            
Flutter 3.27.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c519ee916e (8 days ago) • 2025-01-21 10:32:23 -0800
Engine • revision e672b006cb
Tools • Dart 3.6.1 • DevTools 2.40.2

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**Comment by corepuncher** [comment]
I am getting this same error now, sporadically, when using my bluetooth mouse connected to my S9 tablet.

**Comment by uallis** [comment]
Same error here with scrcpy

**Comment by mfurkanyuceal** [comment]
Same error

**Comment by AlexV525** [comment]
Bisected and found the first bad commit to the framework is 1dce0c7ffb9e9686876400d69a1d26985a43169e #155194.

**Comment by AlexV525** [comment]
I've made some local edits so no assertions will be thrown and the flow seems correct. For people who want to make those edits:

### #L224

https://github.com/flutter/flutter/blob/4e39d13a6f67fa04a9dc424cd20663da9b81301b/packages/flutter/lib/src/rendering/mouse_tracker.dart#L224

```diff dart
- assert((event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)); 
+ assert(() {
+   if (event is PointerAddedEvent) {
+     return lastEvent is PointerMoveEvent || lastEvent is PointerHoverEvent;
+   }
+   return lastEvent is! PointerRemovedEvent;
+ }());
```

### #L336

https://github.com/flutter/flutter/blob/4e39d13a6f67fa04a9dc424cd20663da9b81301b/packages/flutter/lib/src/rendering/mouse_tracker.dart#L336

```diff dart
- assert(event is! PointerAddedEvent); 
```

**Comment by gmackall** [comment]
From what I can tell the source of the problem is that there is a mismatch between the engine and the framework in how we are determining the source of the touch:

In `AndroidTouchProcessor.java`, the engine believes the events are of type `PointerDeviceKind.TOUCH`
https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java#L150
while printing the `event.kind` out in `mouse_tracker.dart` shows that the source is `PointerDeviceKind.mouse`
https://github.com/flutter/flutter/blob/4e39d13a6f67fa04a9dc424cd20663da9b81301b/packages/flutter/lib/src/rendering/mouse_tracker.dart#L224

I assume this is because `scrcpy` intentionally generates touch events: https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/doc/control.md?plain=1#L110



It looks like a potential workaround is to pass `--no-mouse-hover` to `scrcpy` (the issue no longer reproduces for me when passing this flag).

**Comment by AlexV525** [comment]
> It looks like a potential workaround is to pass `--no-mouse-hover` to `scrcpy` (the issue no longer reproduces for me when passing this flag).

I can confirm that using `--no-mouse-hover` in `scrcpy` can workaround the assertion.

**Comment by gmackall** [comment]
> From what I can tell the source of the problem is that there is a mismatch between the engine and the framework in how we are determining the source of the touch:
> 
> In `AndroidTouchProcessor.java`, the engine believes the events are of type `PointerDeviceKind.TOUCH` https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java#L150 while printing the `event.kind` out in `mouse_tracker.dart` shows that the source is `PointerDeviceKind.mouse`
> 
> [flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart](https://github.com/flutter/flutter/blob/4e39d13a6f67fa04a9dc424cd20663da9b81301b/packages/flutter/lib/src/rendering/mouse_tracker.dart#L224)
> 
> Line 224 in [4e39d13](/flutter/flutter/commit/4e39d13a6f67fa04a9dc424cd20663da9b81301b)
> 
>  assert((event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)); 
> I assume this is because `scrcpy` intentionally generates touch events: https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/doc/control.md?plain=1#L110
> 
> It looks like a potential workaround is to pass `--no-mouse-hover` to `scrcpy` (the issue no longer reproduces for me when passing this flag).

This is slightly wrong - the problem isn't actually a framework<->engine mismatch, but rather the fact that `scrcpy` itself reports the tool type as mouse for the hover events, but then as a finger when actually clicking. I've filed https://github.com/Genymobile/scrcpy/issues/6103 to understand the motivation here, to see if that is a bug that should be fixed in `scrcpy`, or if that is intended and we should think about loosening the assert here.

**Comment by KamWithK** [comment]
> > From what I can tell the source of the problem is that there is a mismatch between the engine and the framework in how we are determining the source of the touch:
> > In `AndroidTouchProcessor.java`, the engine believes the events are of type `PointerDeviceKind.TOUCH` https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java#L150 while printing the `event.kind` out in `mouse_tracker.dart` shows that the source is `PointerDeviceKind.mouse`
> > [flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart](https://github.com/flutter/flutter/blob/4e39d13a6f67fa04a9dc424cd20663da9b81301b/packages/flutter/lib/src/rendering/mouse_tracker.dart#L224)
> > Line 224 in [4e39d13](/flutter/flutter/commit/4e39d13a6f67fa04a9dc424cd20663da9b81301b)
> > assert((event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent));
> > I assume this is because `scrcpy` intentionally generates touch events: https://github.com/Genymobile/scrcpy/blob/c5ed2cfc28ee7c7b59b11eb4db1258ac1c633bff/doc/control.md?plain=1#L110
> > It looks like a potential workaround is to pass `--no-mouse-hover` to `scrcpy` (the issue no longer reproduces for me when passing this flag).
> 
> This is slightly wrong - the problem isn't actually a framework<->engine mismatch, but rather the fact that `scrcpy` itself reports the tool type as mouse for the hover events, but then as a finger when actually clicking. I've filed [Genymobile/scrcpy#6103](https://github.com/Genymobile/scrcpy/issues/6103) to understand the motivation here, to see if that is a bug that should be fixed in `scrcpy`, or if that is intended and we should think about loosening the assert here.

You can reproduce the issue without scrcpy, just add a Listener and then switch between touch and stylus inputs and the assertion throws a bunch of times
I've never used that library before but am getting the same error, just like #162443

EDIT: I don't even think you need a Listener to cause it, literally just a coloured box and I can reproduce

**Comment by Rotse4** [comment]
Any fix. Its affecting my app

**Comment by kjm0202** [comment]
Everybody have only talked about scrcpy, so I just want to mention that Samsung Flow has exact same issue, when mirroring mobile screen to PC.

**Comment by gmackall** [comment]
This should be fixed on master now by https://github.com/flutter/flutter/pull/171240. Please let me know if you encounter further issues
