### ISSUE TITLE
animation_controller.dart BUG on Windows

### ISSUE THREAD

**Issue by homelee** [flutter/flutter#160230]
### Steps to reproduce

1、create new flutter project
2、run on windows with debug mode
3、mouse fast move over FloatingActionButton button repeat

### Expected results

print the error log in console window

### Actual results

in my project,will block the UI

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 904 pos 12: 'elapsedInSeconds >= 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:904:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:261:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
#11     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:611:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:277:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:183:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:824:42)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:695:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:504:12)
#8      ImplicitlyAnimatedWidgetState.didUpdateWidget (package:flutter/src/widgets/implicit_animations.dart:389:11)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5789:55)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#14     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#25     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#26     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#33     _invoke (dart:ui/hooks.dart:312:13)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#35     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _FrameCallbackEntry)
====================================================================================================
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4541], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (7 available)
[!] Network resources
    ✗ An HTTP error occurred while checking "https://maven.google.com/": Connection closed before full
      header was received
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @homelee, is your device a high refresh rate device? Can you also try on stable 3.27 to see if this still persists?
