### ISSUE TITLE
"'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 900 pos 12: 'elapsedInSeconds >= 0.0': is not true." after a longer time

### ISSUE THREAD

**Issue by keyem88** [flutter/flutter#160303]
### Steps to reproduce

1. Start app
2. Wait 2 - 3 minutes
3. Click any button (in this example "Cancel"-Button to return to the Main-Menue

### Expected results

The code in the button's onClick method is executed. In my example it is a window change using Get.offAll(...)

### Actual results

App freezed with the following error:

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 900 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:900:12)
animation_controller.dart:900
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:261:12)
ticker.dart:261
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
binding.dart:1240
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
binding.dart:1238
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
binding.dart:1155
#9      _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
platform_dispatcher.dart:397
#11     _beginFrame (dart:ui/hooks.dart:272:31)
hooks.dart:272
(elided 2 frames from class _AssertionError)
This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:611:49)
binding.dart:611
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:277:46)
ticker.dart:277
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:183:7)
ticker.dart:183
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:820:42)
animation_controller.dart:820
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:691:12)
animation_controller.dart:691
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:500:12)
animation_controller.dart:500
#8      new InkSparkle (package:flutter/src/material/ink_sparkle.dart:133:8)
ink_sparkle.dart:133
#9      _InkSparkleFactory.create (package:flutter/src/material/ink_sparkle.dart:473:12)
ink_sparkle.dart:473
#10     _InkResponseState._createSplash (package:flutter/src/material/ink_well.dart:1063:72)
ink_well.dart:1063
#11     _InkResponseState._startNewSplash (package:flutter/src/material/ink_well.dart:1153:42)
ink_well.dart:1153
#12     _InkResponseState.handleAnyTapDown (package:flutter/src/material/ink_well.dart:1120:5)
ink_well.dart:1120
#13     _InkResponseState.handleTapDown (package:flutter/src/material/ink_well.dart:1124:5)
ink_well.dart:1124
#14     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:628:61)
tap.dart:628
#15     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
recognizer.dart:351
#16     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:628:11)
tap.dart:628
#17     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:304:5)
tap.dart:304
#18     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
tap.dart:281
#19     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:271:25)
arena.dart:271
#20     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:251:31)
arena.dart:251
(elided 4 frames from class _FrameCallbackEntry and dart:async)
```

### Code sample

<details open><summary>class ShowQRCodeView</summary>

```dart

//This view shows a QR code to start a new game. The opponent must scan the QR code to start the game.

import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:myapp/controller/game_controller.dart';
import 'package:myapp/models/User/user.dart';
import 'package:myapp/utils/constants/app_constants.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../config/themes/app_colors.dart';

class ShowQRCodeView extends StatelessWidget {
  ShowQRCodeView({
    super.key,
    required this.user,
  }) {
    controller = Get.put(GameController(
      deviceType: DeviceType.advicer,
      user: user,
    ));
  }

  final ElCardsUser user;
  GameController? controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.primary,
      body: Center(child: Obx(() {
        if (controller!.finishInit.value) {
          return Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              const Text(
                textAlign: TextAlign.center,
                'Let your component scan your Game-Code to start VS-Game',
                style: TextStyle(
                  fontSize: 24,
                ),
              ),
              Container(
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(
                      20,
                    ),
                    color: AppColors.primaryLight),
                child: QrImageView(
                  data: jsonEncode({
                    'userId': controller!.user.userID,
                    'cards': jsonEncode(controller!.user.cardDeck),
                    'firstTurn': jsonEncode(!controller!.game.ownTurn.value),
                  }),
                  version: QrVersions.auto,
                  size: 200.0,
                ),
              ),
              ElevatedButton(
                  onPressed: controller!.clickCancelButton,
                  child: const Text('Cancel'))
            ],
          );
        } else {
          return const CircularProgressIndicator();
        }
      })),
    );
  }
}

```

</details>

<details open><summary>clickCancelButton-Function in Controller-Class</summary>

```dart

  //Click Cancel Button
  void clickCancelButton() {
    user.resetCardDeck();
    user.cardSet.allCardsFromDeck();
    connectedDevice = null;
    Get.offAll(() => MainMenuView());
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.19045.5247], locale de-DE)
    • Flutter version 3.24.0 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (5 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Android
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = D:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java      
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)       
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome\Application\chrome.exe 

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[!] Android Studio (version 4.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Connected device (5 available)
    • SM S901B (mobile) • 192.168.2.160:32997 • android-arm64  • Android 14 (API 34)
    • SM S908B (mobile) • 192.168.2.73:46475  • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows             • windows-x64    • Microsoft Windows [Version 10.0.19045.5247]
    • Chrome (web)      • chrome              • web-javascript • Google Chrome 131.0.6778.109
    • Edge (web)        • edge                • web-javascript • Microsoft Edge 128.0.2739.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by nate-thegrate** [comment]
I believe this assertion failure was reported in https://github.com/flutter/flutter/issues/106277.

We should probably update that specific check so it no longer recommends filing a bug report.

**Comment by darshankawar** [comment]
@keyem88 
Can you provide us only minimal but reproducible code sample ? The code you provided contains third party implementation. 

https://stackoverflow.com/help/minimal-reproducible-example
