### ISSUE TITLE
Improve message and/or functionality for Material banner with no actions

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#160365]
### Steps to reproduce

1. show a material banner with actions [] and trigger it at runtime

### Expected results

1. Material banner imho should work with no action - as a snack bar on top with material banner style. or have a default action of "Okay" to dismiss or simlar
2. At least make it easy to find your usage 103 lines and i can't see where i called it from

### Actual results

```
Gives an exception with not very useful info and "please file a bug" message
======== Exception caught by widgets library =======================================================
The following assertion was thrown building MaterialBanner-[#f2347](dirty, dependencies: [MediaQuery], state: _MaterialBannerState#82133):
'package:flutter/src/material/banner.dart': Failed assertion: line 329 pos 12: 'widget.actions.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

======== Exception caught by widgets library =======================================================
The following assertion was thrown building MaterialBanner-[#f2347](dirty, dependencies: [MediaQuery], state: _MaterialBannerState#82133):
'package:flutter/src/material/banner.dart': Failed assertion: line 329 pos 12: 'widget.actions.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/nwarner/youversion-flutter/apps/bible-app/lib/app/home/home.dart:212:37
When the exception was thrown, this was the stack: 
#2      _MaterialBannerState.build (package:flutter/src/material/banner.dart:329:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593:5)
...     Normal element mounting (13 frames)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468:16)
#23     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035:36)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#25     Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060:17)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#30     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#55     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#79     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#84     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#88     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#93     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#94     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#95     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#96     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#97     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#101    _invoke (dart:ui/hooks.dart:312:13)
#102    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#103    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.24.3, on macOS 14.7.1 23H222 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.5.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nwarner/flutter. Consider adding
      /Users/nwarner/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Community Edition (version 2024.3)
[✓] VS Code (version 1.95.3)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment]
This is an assert, so it only appears in debug mode. In release/profile mode the banner will be shown. I wonder if the assert is necessary. 

The assert is here https://github.com/flutter/flutter/blob/8631412f252243a18da849068b5a10d4619dd56c/packages/flutter/lib/src/material/banner.dart#L341

Labeling for further insight

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (15 hours ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.157, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.157 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 27ef1967b0 (5 hours ago), 2024-12-16 20:29:14 -0800
    • Engine revision 23731d6a96
    • Dart version 3.7.0 (build 3.7.0-256.0.dev)
    • DevTools version 2.41.0
```

</details>
