### ISSUE TITLE
Using universal_html breaks wasm builds on stable & master:  'dart:html' is not available on this platform.

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#160318]
Using universal_html breaks wasm builds on latest stable. This was not happening just a week ago so i'm not sure what updated but isnt the point of universal_html (if i understand correctly) is to allow the import so you can compile but in reality its just a dart.html conditional import under the hood. 

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../../../../.pub-cache/hosted/pub.dev/universal_html-2.2.4/lib/src/_sdk/html.dart:32:1: Error: Dart library 'dart:html' is not available on this platform.
export 'dart:html';
^
Context: The unavailable library 'dart:html' is imported through these packages:

    main.dart => package:docs => package:pylon => package:universal_html => dart:html
    main.dart => package:docs => package:universal_html => dart:html
    main.dart => package:docs => package:pylon => package:universal_html => dart:html
    ...

```

Min viable repro
```dart
import 'package:universal_html/html.dart' as html;

void main(){
    if (kIsWeb) {
        print(Uri.parse(html.window.location.href));
    }

    runApp(...);
}
```

Doctor
```dart
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.2 24C101 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/cyberpwn/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (5 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cyberpwn/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/cyberpwn/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/cyberpwn/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1)
    • IntelliJ at /Users/cyberpwn/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23177

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Brave Browser 131.1.73.97

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

Not posting pub deps because its just a bunch of noise, anything importing universal html ends up triggering this issue on wasm builds. I'm specifically using universal_html 2.2.4

* This works on android, ios & macos builds just fine
* This obviously works fine & builds just fine on web builds (js)
* It has recently started failing to build for wasm specifically.

--- 

Also tested on master

```
[✓] Flutter (Channel master, 3.28.0-1.0.pre.123, on macOS 15.2 24C101 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.123 on channel master at /Users/cyberpwn/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a4be7cd70a (3 hours ago), 2024-12-15 18:46:19 +0100
    • Engine revision a9f7fa8ca6
    • Dart version 3.7.0 (build 3.7.0-243.0.dev)
    • DevTools version 2.41.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cyberpwn/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/cyberpwn/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/cyberpwn/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.1)
    • IntelliJ at /Users/cyberpwn/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23177

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Brave Browser 131.1.73.97

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

Same result

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../../../../.pub-cache/hosted/pub.dev/universal_html-2.2.4/lib/src/_sdk/html.dart:32:1: Error: Dart library 'dart:html' is not available on this platform.
export 'dart:html';
^
Context: The unavailable library 'dart:html' is imported through these packages:

    main.dart => package:docs => package:pylon => package:universal_html => dart:html
    main.dart => package:docs => package:universal_html => dart:html
    main.dart => package:docs => package:pylon => package:universal_html => dart:html
    ...
```

**Comment by darshankawar** [comment]
@cyberpwnn 
I think `dart:html` is not available to wasm. Since you are using `universal_html`, the work need to be done in this package so as to make it work with wasm. Please see https://github.com/flutter/flutter/issues/138769 and https://github.com/flutter/flutter/issues/138769#issuecomment-1965041230.

See https://github.com/dint-dev/universal_html/issues/102 and https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm, so I don't think this is an issue with flutter, but the in the said package you are using.

**Comment by cyberpwnn** [comment]
Given the issue is almost a year ago with no resolution, your saying my best bet is to just do the old way of conditional imports with empty implementations of whatever im trying to use?

**Comment by cyberpwnn** [comment]
Actually no, it's impossible to even try to import html and compile on wasm, and this wasnt a problem last week worked fine on wasm just diddnt function because of conditional imports. I.e. 

f_html.dart
```dart
import 'dart:html' as html;

String get $href => html.window.location.href;
```

f_io.dart
```dart
String get $hrefPylon => "";
```

f_js.dart
```dart
import 'dart:js_interop';
import 'dart:js_util' as js_util;

@JS('window')
@staticInterop
external JSObject get $window;

String get $href {
  final location = js_util.getProperty($window, 'location') as JSObject;
  return js_util.getProperty(location, 'href') as String;
}
```

Then finally

```dart
import '../f_io.dart' // stub
    if (dart.library.js_interop) '../f_html.dart' web html
    if (dart.library.html) '../f_js.dart'; // web without html (wasm) js
```

Build still fails with 

```

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 254:
../lib/src/f_html.dart:1:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    main.dart => package:example => package:pylon => dart:html

Detailed import paths for (some of) the these imports:

    main.dart => package:example/main.dart => package:pylon/pylon.dart => package:pylon/src/port.dart => package:pylon/src/f_html.dart => dart:html

../lib/src/util/address_bar_html.dart:3:31: Error: Undefined name 'window'.
String get $hrefPylon => html.window.location.href;
                              ^^^^^^
../lib/src/util/f_html.dart:7:10: Error: Undefined name 'window'.
    html.window.history.pushState(data, title, url);
         ^^^^^^
  Command: /Users/cyberpwn/development/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=/Users/cyberpwn/development/workspace/pylon/example/.dart_tool/package_config.json
  --extra-compiler-option=--platform=/Users/cyberpwn/development/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill -Ddart.vm.profile=false -Ddart.vm.product=true
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false -DFLUTTER_WEB_USE_SKWASM=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a9f7fa8ca61366a9abbabd63c409f8500286fd2b/
  --extra-compiler-option=--depfile=/Users/cyberpwn/development/workspace/pylon/example/.dart_tool/flutter_build/ede50069fa7a98f72bb6f200bedf2edd/dart2wasm.d -O4 --strip-wasm --no-source-maps -o
  /Users/cyberpwn/development/workspace/pylon/example/.dart_tool/flutter_build/ede50069fa7a98f72bb6f200bedf2edd/main.dart.wasm
  /Users/cyberpwn/development/workspace/pylon/example/.dart_tool/flutter_build/ede50069fa7a98f72bb6f200bedf2edd/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:389:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:356:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:891:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:528:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:528:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:829:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:651:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:232:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1422:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:443:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:386:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

So actually no, I think that something last week changed that now makes the wasm build overly-strict and will just fail the second it sees dart:html even through conditional imports which it shouldnt be walking through the dart.library.html condition just to fail.

**Comment by darshankawar** [comment]
Please see https://github.com/flutter/flutter/issues/158087 with underlying comments for further reference if it helps.

**Comment by cyberpwnn** [comment]
No its not that issue

```
import 'package:pylon/src/util/address_bar_io.dart'
    if (dart.library.html) (import for js)
    if (dart.library.js_interop) (import for html)
```

So while i havent tested the js interop its not failing the build so I can close this.
