### ISSUE TITLE
[tool_crash] FileSystemException: flush failed, OS Error: Structure needs cleaning, errno = 117

### ISSUE THREAD

**Issue by rkandroid** [flutter/flutter#160434]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: flush failed, OS Error: Structure needs cleaning, errno = 117
```
#0      _RandomAccessFile.flushSync (dart:io/file_impl.dart:999:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:647:25)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:668:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#4      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:266:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#6      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:265:5)
#7      _writeFlutterPluginsListLegacy (package:flutter_tools/src/flutter_plugins.dart:268:15)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1118:30)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:369:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.da

**Comment by maheshj01** [comment]
Hi @rkandroid, Please share the output of `flutter doctor -v`
