### ISSUE TITLE
GestureDetector.onTapCancel is called during build phase, causing setState error unexpectedly

### ISSUE THREAD

**Issue by chooyan-eng** [flutter/flutter#160508]
### Steps to reproduce

1. run the sample code below
2. press grey box
3. remove grey box by rebuilding (in the sample code, this will be done using `Timer`)
4. `onTapCancel` is called, where I call `setState()` inside.
5. the error below happens.

### Expected results

No error occurs, meaning `onTapCancel` should be called outside of the rebuilding process.

### Actual results

The error below happened.

```console
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
setState() or markNeedsBuild() called when widget tree was locked.
This TapCancelDemo widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: TapCancelDemo
    state: _TapCancelDemoState#27489

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5193:9)
framework.dart:5193
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5203:6)
framework.dart:5203
#2      State.setState (package:flutter/src/widgets/framework.dart:1224:15)
framework.dart:1224
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: TapCancelDemo()));

class TapCancelDemo extends StatefulWidget {
  const TapCancelDemo({super.key});

  @override
  State<TapCancelDemo> createState() => _TapCancelDemoState();
}

class _TapCancelDemoState extends State<TapCancelDemo> {
  String? _message;
  bool _isVisible = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (_isVisible)
            Expanded(
              child: GestureDetector(
                onTapCancel: () {
                  setState(() => _message = 'onTapCancel');
                },
                onTapDown: (details) {
                  setState(() => _message = 'onTapDown');
                  Timer(const Duration(milliseconds: 100), () {
                    // remove the widget after 100ms
                    setState(() => _isVisible = false);
                  });
                },
                child: Container(
                  margin: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    color: Colors.grey,
                  ),
                  child: const Center(
                    child: Text('Tap me'),
                  ),
                ),
              ),
            ),
          const SizedBox(height: 32),
          Text(_message ?? ''),
          const SizedBox(height: 32),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/cf9ceed8-87a8-4707-b8f9-a8c7107ec10f

</details>

### Logs

<details open><summary>Logs</summary>

```console

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
setState() or markNeedsBuild() called when widget tree was locked.
This TapCancelDemo widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: TapCancelDemo
    state: _TapCancelDemoState#f8162

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:5193:9)
framework.dart:5193
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5203:6)
framework.dart:5203
#2      State.setState (package:flutter/src/widgets/framework.dart:1224:15)
framework.dart:1224
#3      _TapCancelDemoState.build.<anonymous closure> (package:example/reorderable_page.dart:29:19)
reorderable_page.dart:29
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
recognizer.dart:351
#5      TapGestureRecognizer.handleTapCancel (package:flutter/src/gestures/tap.dart:680:11)
tap.dart:680
#6      BaseTapGestureRecognizer._checkCancel (package:flutter/src/gestures/tap.dart:318:5)
tap.dart:318
#7      BaseTapGestureRecognizer.resolve (package:flutter/src/gestures/tap.dart:266:7)
tap.dart:266
#8      OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:469:5)
recognizer.dart:469
#9      PrimaryPointerGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:762:11)
recognizer.dart:762
#
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 14.3.1 23D60 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.95.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by maheshj01** [comment]
Hi @chooyan-eng, Thanks for filing the issue. I am able to reproduce the issue there seems to be some sort of race condition   When the tap is cancelled `onTapCancelled` is not getting invoked.


<details>
<summary>logs</summary>

```console
#28     _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
platform_dispatcher.dart:427
#30     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283

Handler: "spontaneous onTapCancel"
Recognizer: TapGestureRecognizer#b03fe
    debugOwner: GestureDetector
    state: possible
    won arena
    button: 1
    sent tap down
═════════════════
```
</details> 

<details>
<summary>flutter doctor -v</summary>




```console
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (7 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B2091
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B2091
      darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome
      128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.123, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.123 on channel master at /Users/mahesh/Development/flutter_master
    • Framework revision a547c7f050 (4 days ago), 2024-12-13 22:11:39 -0500
    • Engine revision 4e4a430bcd
    • Dart version 3.7.0 (build 3.7.0-243.0.dev)
    • DevTools version 2.41.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use
      "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B2091
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B2091
      darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome
      128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>
