### ISSUE TITLE
sysctl: unknown old 'hw.optional.arm64' when building for iOS

### ISSUE THREAD

**Issue by gummz** [flutter/flutter#160530]
### Steps to reproduce

The error occurs when executing

`flutter build iOS
`

This is very specific to my project, but I have a complete log from `flutter build ios -v`, and I believe I know the exact error message:

`sysctl: unknown oid 'hw.optional.arm64'`

The command: flutter build ios

I have tried 

flutter clean
flutter pub get
pod repo update
pod deintegrate
pod install
Removing ios/Pods, ios/Podfile.lock, DerivedData directory

Machine model:
MacBook Pro 2020 Sonoma 14.6.1

### Actual results

[flutter_build.log](https://github.com/user-attachments/files/18188810/flutter_build.log)

The generic error message is:

```
Error (Xcode): Error parsing assemble command: your generated configuration may be out of date. Try re-running
'flutter build ios' or the appropriate build command.
```

The relevant (I think) snippet from the log is below but I believe the actual error is this:

` sysctl: unknown oid 'hw.optional.arm64'`

Would appreciate any suggestions as to what the cause of this error might be.

**Logs surrounding error message (full log file uploaded here as attachment):**

```
`/bin/sh -c /Users/gudmhb/Library/Developer/Xcode/DerivedData/Runner-abizgewvidhcnpalwierdzgwcuyl/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
            ♦ /Users/gudmhb/development/flutter/bin/flutter --verbose assemble --no-version-check --output=/Users/gudmhb/Projects/emote/build/ios/Release-iphoneos/ -dTargetPlatform=ios -dTargetFile=/lib/main.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk -dSplitDebugInfo= -dTreeShakeIcons=true -dTrackWidgetCreation=false -dDartObfuscation=false -dAction=build -dFrontendServerStarterPath= --ExtraGenSnapshotOptions= --DartDefines=FLAVOR=production --ExtraFrontEndOptions= -dCodesignIdentity=AF77BA517530838410D3ABF23F3410148111EC01 release_ios_bundle_flutter_assets
            [  +32 ms] executing: sysctl hw.optional.arm64
            [  +17 ms] Exit code 1 from: sysctl hw.optional.arm64
            [        ] sysctl: unknown oid 'hw.optional.arm64'

 Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
            [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
            [  +38 ms] "flutter assemble" took 173ms.
            [   +1 ms] Running 1 shutdown hook
            [        ] Shutdown hooks complete
            [   +1 ms] exiting with code 1
            error: [   +5 ms] Error parsing assemble command: your generated configuration may be out of date. Try re-running 'flutter build ios' or the appropriate build command.
            [   +2 ms] 
                       #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                       #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:308:7)
                       #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1815:12)
                       <asynchronous suspension>
                       #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
                       <asynchronous suspension>
                       #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                       <asynchronous suspension>
                       #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
                       <asynchronous suspension>
                       #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
                       <asynchronous suspension>
                       #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                       <asynchronous suspension>
                       #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
                       <asynchronous suspension>
                       #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
                       <asynchronous suspension>
                       #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
                       <asynchronous suspension>
                       #11     main (package:flutter_tools/executable.dart:94:3)
                       <asynchronous suspension>
            Failed to package /Users/gudmhb/Projects/emote.`
```

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

(base) gudmhb@Gumundurs-MacBook-Pro ios % flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 14.6.1 23G93 darwin-x64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (2 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gudmhb/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/gudmhb/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] VS Code (version 1.84.0)
    • VS Code at /Users/gudmhb/Downloads/Visual Studio Code-2.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • iPhone 16 Pro (mobile) • 619559C6-F401-43AF-AC3A-33E676C25EF3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 14.6.1 23G93
      darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 131.0.6778.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@gummz 
Check if [this](https://stackoverflow.com/questions/72708385/what-may-cause-error-sysctl-n-hw-optional-arm64-returned-unexpected-output) helps in your case or not.

**Comment by gummz** [comment]
Unfortunately not, as “which sysctl” returns the location on my machine.

fim., 19. des.. 2024 klukkan 07:45, darshankawar ***@***.***(mailto:fim., 19. des.. 2024 klukkan 07:45, darshankawar <<a href=)> skrifaði:

**Comment by darshankawar** [comment]
It seems you are hitting https://github.com/flutter/flutter/issues/134766, so please follow-up in it for further updates. You may share your findings in it for better tracking.
Closing this as a duplicate.
