### ISSUE TITLE
Attempt to execute code removed by Dart AOT compiler (TFA) (crash after updating to 3.27.1 from 3.24.5)

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#160551]
### Steps to reproduce

I get this error when launching iOS application with 3.27.1 (on 3.24.5 it works fine)

The stacktrace points to PopupMenuButton but that is not even being used anywhere in the app.

### Expected results

The app should behave exactly like how it works when build with 3.24.5

### Actual results

The app shows blank screen with the above error showing in the console

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at x
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (23 hours ago)
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @MohiuddinM, please provide the full output of `flutter run -v` or the full verbose output of whatever command you ran. Please also provide a complete minimal reproducible code sample so that we can properly investigate this. 

Thank you

**Comment by MohiuddinM** [comment]
I can not find what the issue is so I can not come up with a minimal reproduction. Also the stacktrace is not very helpful, because its all just internal flutter files. But the app works fine with 3.25.5, so its probably a bug introduced after that.

**Comment by danagbemava-nc** [comment]
Please provide the full output of `flutter run -v` or the full verbose output of whatever command you ran. Without it we don't know where to begin looking to fix the issue. 

Thank you

**Comment by MohiuddinM** [comment]
There is a big in dart compiler that causes the removed code in AOT, because a `double` value was assigned an `int` in the constructor.

**Comment by danagbemava-nc** [comment]
Hi @MohiuddinM, it would be helpful if you could provide the crash logs so that this can be fixed. 

Thank you

**Comment by MohiuddinM** [comment]
Here is the stacktrace:
```
flutter: Attempt to execute code removed by Dart AOT compiler (TFA)
flutter: #0      PopupMenuButton.build (popup_menu_button.dart)
flutter: #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5701)
flutter: #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5631)
flutter: #3      Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #13     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049)
flutter: #14     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #16     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049)
flutter: #17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #34     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049)
flutter: #35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7061)
flutter: #36     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:232)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5785)
flutter: #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6914)
flutter: #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #72     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5785)
flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5607)
flutter: #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:5347)
flutter: #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5613)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by MohiuddinM** [comment]
> @MohiuddinM Can you share what part of code implementation did you use this ?

What do you mean by this?

**Comment by MohiuddinM** [comment]
Unfortunately, I can not post the code here as it is not open source. But there is nothing fancy in it; it is just a simple Widget that wraps the PopupMenuButton from the Material library.

**Comment by MohiuddinM** [comment]
I made a little reproduction for you @alexmarkov:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: ItemList.primary(items: (_) => [Text('Item')])));
}

abstract base class ItemList extends StatelessWidget {
  const ItemList({super.key});

  const factory ItemList.primary({
    Key? key,
    double elevation,
    required List<dynamic> Function(BuildContext) items,
  }) = PrimaryItemList;
}

final class PrimaryItemList<T> extends ItemList {
  const PrimaryItemList({super.key, this.elevation = 10, required this.items});

  final double elevation;
  final List<T> Function(BuildContext context) items;

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () {},
      style: ElevatedButton.styleFrom(elevation: elevation),
      child: Text('Primary Button'),
    );
  }
}
```

Run this with `flutter run --release` to see the error, then change elevation `10 `to `10.0` and then the error goes away.

**Comment by alexmarkov** [comment]
Thank you, @MohiuddinM !

A smaller pure Dart repro:
```dart
void main() {
  print(PrimaryItemList().elevation);
}

abstract class ItemList {
  ItemList();

  factory ItemList.primary({
    double elevation,
  }) = PrimaryItemList;
}

class PrimaryItemList<T> extends ItemList {
  PrimaryItemList({this.elevation = 10});
  final double elevation;
}
```

It crashes both in JIT and AOT modes.

Kernel AST (in JIT mode):
```
  abstract class ItemList extends core::Object {
    constructor •() → foo4::ItemList
      : super core::Object::•()
      ;
    static factory primary({core::double elevation = #C1}) → foo4::ItemList /* redirection-target: foo4::PrimaryItemList::•<dynamic>*/
      return new foo4::PrimaryItemList::•<dynamic>(elevation: elevation);
  }
  class PrimaryItemList<T extends core::Object? = dynamic> extends foo4::ItemList {
    final field core::double elevation;
    constructor •({core::double elevation = #C1}) → foo4::PrimaryItemList<foo4::PrimaryItemList::T%>
      : foo4::PrimaryItemList::elevation = elevation, super foo4::ItemList::•()
      ;
  }
  static method main() → void {
    core::print(new foo4::PrimaryItemList::•<dynamic>().{foo4::PrimaryItemList::elevation}{core::double});
  }
}
constants  {
  #C1 = 10
}
```

The default value of constructor parameters `#C1` is `10` - it was not converted from int to double, which results in the incorrectly typed AST. If I remove `ItemList` or type parameter `<T>` from this example, the default value is correctly converted to `10.0`:

```
  abstract class ItemList extends core::Object {
    constructor •() → foo4::ItemList
      : super core::Object::•()
      ;
    static factory primary({core::double elevation = #C1}) → foo4::ItemList /* redirection-target: foo4::PrimaryItemList::• */
      return new foo4::PrimaryItemList::•(elevation: elevation);
  }
  class PrimaryItemList extends foo4::ItemList {
    final field core::double elevation;
    constructor •({core::double elevation = #C1}) → foo4::PrimaryItemList
      : foo4::PrimaryItemList::elevation = elevation, super foo4::ItemList::•()
      ;
  }
  static method main() → void {
    core::print(new foo4::PrimaryItemList::•().{foo4::PrimaryItemList::elevation}{core::double});
  }
}
constants  {
  #C1 = 10.0
}
```

This conversion should happen in the front-end, so this looks like a CFE bug. /cc @johnniwinther

**Comment by a-siva** [comment]
@johnniwinther I presume somebody from your team is taking over this issue,

**Comment by chloestefantsova** [comment]
I'm working on a fix at https://dart-review.googlesource.com/c/sdk/+/404822

**Comment by chloestefantsova** [comment]
This is fixed in https://dart-review.googlesource.com/c/sdk/+/404822.

**Comment by a-siva** [comment]
The above change was rolled into Flutter here https://github.com/flutter/flutter/pull/161989
Closing issue.
