### ISSUE TITLE
`CarouselView` throws `AssertionError` when parent size is 0

### ISSUE THREAD

**Issue by LukasMirbt** [flutter/flutter#160679]
### Steps to reproduce

1. Run the code sample
2. Note that there is an error in the console

### Expected results

`CarouselView` should not throw when parent size is 0.

### Actual results

`CarouselView` throws an `AssertionError` when parent size is 0.

The documentation for the `itemExtent` property mentions that _the item extent should not exceed the available space that the carousel view occupies to ensure at least one item is fully visible_. However, the same error is thrown when both the `SizedBox` and `itemExtent` is set to 0. I would also argue that the widget should gracefully handle having 0 size since this can happen indirectly through the parent widget size.

Additionally, an `UnsupportedError` (`Unsupported operation: Infinity or NaN toInt`) is thrown when the `SizedBox` size is set to 100 and `itemExtent` is set to 0.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SizedBox(
          width: 0,
          child: CarouselView(
            itemExtent: 100,
            children: [
              Container(
                color: Colors.red,
                width: 100,
                height: 100,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                           14.2s
Connecting to VM Service at ws://127.0.0.1:64008/DOq4En-aJYE=/ws
Connected to the VM Service.

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1515 pos 12: 'correctedOffset.isFinite': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    CarouselView CarouselView

When the exception was thrown, this was the stack:
#2      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1515:12)
#3      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1467:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#5      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#17     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:393:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:293:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#21     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:180:12)
#22     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1118:7)
#23     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:249:7)
#24     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:419:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1483:11)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#37     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:62:11)
#38     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:646:43)
#39     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:673:12)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#52     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3750:13)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#56     _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:1076:13)
#57     _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1422:9)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#66     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:574:11)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:18)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2715:7)
#82     RenderView.performLayout (package:flutter/src/rendering/view.dart:294:12)
#83     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2548:7)
#84     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1112:18)
#85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1125:15)
#86     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:617:23)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1231:13)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:483:5)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442:15)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1355:9)
#91     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1064:9)
#92     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:873:16)
#96     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderViewport#74279 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=0.0, 0.0<=h<=852.0)
    size: Size(0.0, 852.0)
    axisDirection: right
    crossAxisDirection: down
    offset: _CarouselPosition#7e9dc(offset: NaN, range: null..null, viewport: 0.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a8b19, ScrollDirection.idle)
    anchor: 0.0
    center child: _RenderSliverFixedExtentCarousel#5c1a8 NEEDS-LAYOUT NEEDS-PAINT
        parentData: paintOffset=Offset(0.0, 0.0)
        constraints: MISSING
        geometry: null
        no children current live
RenderObject: RenderViewport#74279 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=0.0, 0.0<=h<=852.0)
    size: Size(0.0, 852.0)
    axisDirection: right
    crossAxisDirection: down
    offset: _CarouselPosition#7e9dc(offset: NaN, range: null..null, viewport: 0.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a8b19, ScrollDirection.idle)
    anchor: 0.0
    center child: _RenderSliverFixedExtentCarousel#5c1a8 NEEDS-LAYOUT NEEDS-PAINT
        parentData: paintOffset=Offset(0.0, 0.0)
        constraints: MISSING
        geometry: null
        no children current live
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.28.0-2.0.pre.38555, on macOS 14.4.1 23E224 darwin-arm64, locale en-SE)
    • Flutter version 3.28.0-2.0.pre.38555 on channel main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 181f4244b4 (3 hours ago), 2024-12-20 18:46:55 +0100
    • Engine revision 181f4244b4
    • Dart version 3.7.0 (build 3.7.0-266.0.dev)
    • DevTools version 2.41.0
```

</details>

**Comment by maheshj01** [comment]
Reproducible on latest stable and the master channel.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (4 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B2091 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B2091 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[✓] Flutter (Channel master, 3.28.0-1.0.pre.123, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.123 on channel master at /Users/mahesh/Development/flutter_master
    • Framework revision a547c7f050 (7 days ago), 2024-12-13 22:11:39 -0500
    • Engine revision 4e4a430bcd
    • Dart version 3.7.0 (build 3.7.0-243.0.dev)
    • DevTools version 2.41.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.94.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B2091 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B2091 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 128.0.6613.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details> 

<details>
<summary>logs</summary>

```console
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Assertion failed:
file:///Users/mahesh/Development/flutter/packages/flutter/lib/src/rendering/viewport.dart:1479:12
correctedOffset.isFinite
is not true

The relevant error-causing widget was:
  CarouselView CarouselView:file:///Users/mahesh/Development/platform_stack_test/lib/main.dart:16:18

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 110:39            assertFailed
packages/flutter/src/rendering/viewport.dart 1479:27                         [_attemptLayout]
packages/flutter/src/rendering/viewport.dart 1435:20                         performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/widgets/layout_builder.dart 379:7                       performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 297:7                          performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/custom_layout.dart 178:10                     layoutChild
packages/flutter/src/material/scaffold.dart 1105:7                           performLayout
packages/flutter/src/rendering/custom_layout.dart 242:7                      [_callPerformLayout]
packages/flutter/src/rendering/custom_layout.dart 409:5                      performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/proxy_box.dart 1476:11                        performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/layout_helper.dart 61:10                      layoutChild
packages/flutter/src/rendering/stack.dart 601:43                             [_computeSize]
packages/flutter/src/rendering/stack.dart 628:12                             performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/proxy_box.dart 3722:13                        performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/widgets/overlay.dart 1016:12                            layoutChild
packages/flutter/src/widgets/overlay.dart 1328:9                             performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/custom_paint.dart 572:11                      performLayout
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/proxy_box.dart 117:21                         <fn>
packages/flutter/src/rendering/object.dart 2627:7                            layout
packages/flutter/src/rendering/view.dart 285:12                              performLayout
packages/flutter/src/rendering/object.dart 2465:7                            [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 1062:17                           flushLayout
packages/flutter/src/rendering/object.dart 1075:14                           flushLayout
packages/flutter/src/rendering/binding.dart 609:5                            drawFrame
packages/flutter/src/widgets/binding.dart 1178:13                            drawFrame
packages/flutter/src/rendering/binding.dart 475:5                            [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1397:7                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1318:9                           handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1040:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 47:11      internalCallback

The following RenderObject was being processed when the exception was fired: RenderViewport#2bb4b NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: Viewport ← IgnorePointer-[GlobalKey#13b0d] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#14900] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#29a97] ← NotificationListener<ScrollMetricsNotification> ←
    Scrollable ← LayoutBuilder ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=0.0, 0.0<=h<=813.0)
  size: Size(0.0, 813.0)
  axisDirection: right
  crossAxisDirection: down
  offset: _CarouselPosition#f6b11(offset: NaN, range: null..null, viewport: 0.0, ScrollableState,
    BouncingScrollPhysics -> RangeMaintainingScrollPhysics -> BouncingScrollPhysics ->
    RangeMaintainingScrollPhysics, IdleScrollActivity#e4d89, ScrollDirection.idle)
  anchor: 0.0
This RenderObject had the following child:
    center child: _RenderSliverFixedExtentCarousel#fd70b NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by navaronbracke** [comment]
I'll have a fix up soon, although most people will be off on holiday, so the review might take a while.

**Comment by navaronbracke** [comment]
Can someone remove the "wiating for PR to land" label? This is not fully fixed yet.
