### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by Abdurahmon727** [flutter/flutter#160736]
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1457:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1324:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:927:22)
#3      _JsonStringDecoderSink.addSlice (dart:convert-patch/convert_patch.dart:1544:13)
#4      _JsonStringDecoderSink.add (dart:convert-patch/convert_patch.dart:1549:5)
#5      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#7      _rootRunUnary (dart:async/zone.dart:1422:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#16     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#17     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#18     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#19     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#20     _rootRunUnary (dart:async/zone.dart:1422:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
```
```console
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.0.1 24A348 darwin-arm64, locale en-UZ)
    • Flutter version 3.27.0 on channel stable at /Users/macstore.uz/sdks/flutter_latest
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (12 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macstore.uz/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.96.2)
    • VS Code at /Users/macstore.uz/Documents/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554         • android-arm64  • Android 9 (API 28) (emulator)
    • macOS (desktop)                      • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop)      • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                         • chrome                • web-javascript • Google Chrome 131.0.6778.205
    ! Error: Browsing on the local area network for udevs’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone (Soburjon). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 796c8ef79279f9c774545b3771238c3098dbefab
### Plugins
connectivity_plus-6.1.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.4
shared_preferences_android-2.4.0
shared_preferences_foundation-2.5.4
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1

**Comment by Abdurahmon727** [comment]
Fixed by updating to flutter version 3.27.1
