### ISSUE TITLE
Could not start Dart VM service HTTP server

### ISSUE THREAD

**Issue by Tatsukiyoshi** [flutter/flutter#160741]
### Steps to reproduce

1. Start Android Emulator
2. Start Debug on Visual Studio Code

### Actual results

Start Flutter Application on Android Emulator

### Logs

<details open>
<summary>Logs</summary>

```console
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk
I/flutter ( 3271): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/flutter ( 3271): Could not start Dart VM service HTTP server:
I/flutter ( 3271): SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 0
I/flutter ( 3271): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
I/flutter ( 3271): <asynchronous suspension>
I/flutter ( 3271): #1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1818:15)
I/flutter ( 3271): <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
PS D:\Repository\Weekend_Programming\flutter\practice\vol8> flutter doctor -v
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26120.2705], locale ja-JP)
    • Flutter version 3.27.1 on channel stable at C:\Users\taish\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (6 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\taish\AppData\Local\Android\sdk
    • Platform android-Baklava, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12771278-b631.28)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.0 Preview 2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.13.35617.110
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12771278-b631.28)

[√] IntelliJ IDEA Community Edition (version 2024.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.3
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23177

[√] VS Code (version 1.96.2)
    • VS Code at C:\Users\taish\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.26120.2705]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.205
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 132.0.2957.55

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by JoseGeorges8** [comment]
This happened to me literally 1-5 minutes ago, with a real device.

I added the internet permission to the manifest and it worked.

`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by Tatsukiyoshi** [comment]
Thanks for the reply, I'll check it when I get home.

**Comment by Tatsukiyoshi** [comment]
It started up!
