### ISSUE TITLE
RenderSliverFixedExtentBoxAdapter fails assert during page view navigation

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#16086]
Occurred when using Android emulator with project flutter/flutter_attract (private repo):
```
I/flutter (13483): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13483): The following assertion was thrown during performLayout():
I/flutter (13483): 'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 226 pos 12:
I/flutter (13483): 'firstIndex == 0 || childScrollOffset(firstChild) <= scrollOffset': is not true.
I/flutter (13483):
I/flutter (13483): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13483): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13483): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13483):   https://github.com/flutter/flutter/issues/new
I/flutter (13483):
I/flutter (13483): When the exception was thrown, this was the stack:
I/flutter (13483): #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart)
I/flutter (13483): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (13483): #4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
I/flutter (13483): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
I/flutter (13483): #6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
I/flutter (13483): #7      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (13483): #8      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (13483): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (13483): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
I/flutter (13483): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13483): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13483): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13483): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13483): #15     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (13483): #16     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (13483): (elided 2 frames from class _AssertionError)
I/flutter (13483):
I/flutter (13483): The following RenderObject was being processed when the exception was fired:
I/flutter (13483):   RenderSliverFillViewport#d9f88 relayoutBoundary=up1 NEEDS-LAYOUT
I/flutter (13483):   creator: SliverFillViewport ← Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#9e330] ←
I/flutter (13483):   Semantics ← Listener ← _GestureSemantics ←
I/flutter (13483):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#397f0] ←
I/flutter (13483):   _ExcludableScrollSemantics-[GlobalKey#b384c] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ← ⋯
I/flutter (13483):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (13483):   constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward,
I/flutter (13483):   ScrollDirection.reverse, scrollOffset: 6973.7, remainingPaintExtent: 774.9, crossAxisExtent:
I/flutter (13483):   411.4, crossAxisDirection: AxisDirection.down, viewportMainAxisExtent: 774.9)
I/flutter (13483):   geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 774.9, maxPaintExtent: Infinity,
I/flutter (13483):   hasVisualOverflow: true)
I/flutter (13483):   currently live children: 9 to 9
I/flutter (13483): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (13483):   RenderRepaintBoundary#95a58
I/flutter (13483):     RenderDecoratedBox#5cec2
I/flutter (13483):       RenderPositionedBox#b61f9
I/flutter (13483):         RenderPadding#ad613 relayoutBoundary=up1
I/flutter (13483):           RenderFittedBox#311ce relayoutBoundary=up2
I/flutter (13483): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[C:\git\flutter_attract] flutter doctor -v
[√] Flutter (Channel master, v0.2.5-pre.76, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.2.5-pre.76 at c:\git\flutter
    • Framework revision 29eebcbe88 (5 hours ago), 2018-03-29 22:02:29 +0200
    • Engine revision 6473f1b106
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\timsneath\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.1
```

**Comment by goderbauer** [comment]
Do you happen to have a runnable code sample that reproduces the problem so we can debug it?
