### ISSUE TITLE
[tool_crash] StateError: Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by mybelatar** [flutter/flutter#160842]
## Command
```sh
flutter run -d chrome --web-hostname localhost --web-port 55910
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: StreamSink is closed
```console
#0      _StreamSinkImpl.add (dart:_http/http_impl.dart:919:7)
#1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1223:11)
#2      vmServiceConnectUriWithFactory.<anonymous closure> (package:vm_service/vm_service_io.dart:37:46)
#3      VmService._processRequest (package:vm_service/src/vm_service.dart:2030:18)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.27.1, on Microsoft Windows [version 10.0.19045.5247], locale fr-MA)
    [32m•[39m Flutter version 3.27.1 on channel stable at D:\flutter_windows_3.24.5-stable\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 17025dd882 (9 days ago), 2024-12-17 03:23:09 +0900
    [32m•[39m Engine revision cb4b5fff73
    [32m•[39m Dart version 3.6.0
    [32m•[39m DevTools version 2.40.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at C:\Users\BELATAR\AppData\Local\Android\Sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m ANDROID_HOME = C:\Users\BELATAR\AppData\Local\Android\Sdk
    [32m•[39m ANDROID_SDK_ROOT = C:\Users\BELATAR\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.12.35527.113
    [32m•[39m Windows 10 SDK version 10.0.26100.0

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at C:\Users\BELATAR\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.5247]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.205
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.112

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668
### Plugins
fluttertoast-8.2.10
google_sign_in-6.2.2
google_sign_in_android-6.1.34
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3
path_provider-2.1.5
path_provider_android-2.2.15
path_provider_foundation-2.4.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
share_plus-10.1.3
shared_preferences-2.3.4
shared_preferences_android-2.4.0
shared_preferences_foundation-2.5.4
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.2
url_launcher_linux-3.2.1
url_launcher_macos-3.2.2
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment]
Might be related to https://github.com/flutter/flutter/issues/150759

Stacktrace appears to be a bit different. 

@mybelatar, is this the full crash log you got from the tool?
