### ISSUE TITLE
[integration_test] No implementation found for method captureScreenshot on channel

### ISSUE THREAD

**Issue by MaslovskayaMarina** [flutter/flutter#160944]
### Steps to reproduce

1. flutter drive --driver=test_driver/test_driver.dart --target=integration_test/main_test.dart  -d windows --verbose

### Expected results

screenshot taken

### Actual results

binding.takeScreenshot MissingPluginException(No implementation found for method captureScreenshot on channel

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

Future<void> main() async {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
  binding.testTextInput.register();

  testWidgets('Test1', (tester) async {
    final screenshotData = await binding.takeScreenshot('simpleName');
  });
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[   +1 ms] Failure in method: Test1
[        ] ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
[        ] The following MissingPluginException was thrown running a test:
[        ] MissingPluginException(No implementation found for method
[        ] captureScreenshot on channel plugins.flutter.io/integration_test)
[        ] When the exception was thrown, this was the stack:
[        ] #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
[        ] <asynchronous suspension>
[        ] #1      _IOCallbackManager.takeScreenshot (package:integration_test/src/_callback_io.dart:93:33)
[        ] <asynchronous suspension>
[        ] #2      IntegrationTestWidgetsFlutterBinding.takeScreenshot (package:integration_test/integration_test.dart:186:39)
[        ] <asynchronous suspension>
[        ] #3      main.<anonymous closure> (path to my test file)        
[        ] <asynchronous suspension>
[        ] #4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
[        ] <asynchronous suspension>
[        ] #5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
[        ] <asynchronous suspension>
[        ] #6      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:824:12)
[        ] <asynchronous suspension>
[        ] The test description was:
[        ]   Test1
[        ] ═════════════════════════════════════════════════════════════════
[        ] end of failure 1
[  +16 ms] "flutter drive" took 63 633ms.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4460], locale ru-RU)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@MaslovskayaMarina 
There's already a similar issue https://github.com/flutter/flutter/issues/123063, so please follow-up in it. Closing this as a duplicate.
