### ISSUE TITLE
[tool_crash] SocketException: Write failed, OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by SuchithShivakumar** [flutter/flutter#160936]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Write failed, OS Error: Broken pipe, errno = 32
```console
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1252:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2010:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2487:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2222:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2174:11)
#5      _rootRunUnary (dart:async/zone.dart:1422:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777:19)
#11     _StreamController._add (dart:async/stream_controller.dart:651:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#14     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#15     _Socket.write (dart:io-patch/socket_patch.dart:2320:36)
#16     _StdSink.writeln (dart:io/stdio.dart:426:13)
#17     DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:902:20)
<asynchronous suspension>
#18     _CompilationRequest.run (package:flutter_tools/src/compile.dart:393:24)
<asynchronous suspension>
#19     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:779:9)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-x64, locale en-US)
    [32m•[39m Flutter version 3.27.1 on channel stable at /Users/suchithshivakumar/Documents/Projects/FlutterLearning/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 17025dd882 (11 days ago), 2024-12-17 03:23:09 +0900
    [32m•[39m Engine revision cb4b5fff73
    [32m•[39m Dart version 3.6.0
    [32m•[39m DevTools version 2.40.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    [32m•[39m Android SDK at /Users/suchithshivakumar/Library/Android/sdk
    [32m•[39m Platform android-35, build-tools 35.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16C5032a
    [32m•[39m CocoaPods version 1.16.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2024.3.1.1)
    [32m•[39m IntelliJ at /Users/suchithshivakumar/Applications/IntelliJ IDEA Community Edition.app
    [32m•[39m Flutter plugin version 83.0.4
    [32m•[39m Dart plugin version 243.23177

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at /Users/suchithshivakumar/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 16 Pro (mobile) • 4D499936-ACA9-48D2-972B-10D77D157273 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-2 (simulator)
    [32m•[39m macOS (desktop)        • macos                                • darwin-x64     • macOS 15.2 24C101 darwin-x64
    [32m•[39m Chrome (web)           • chrome                               • web-javascript • Google Chrome 131.0.6778.205

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 17025dd88227cd9532c33fa78f5250d548d87e9a

**Comment by maheshj01** [comment]
Hi @SuchithShivakumar, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/136753, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
