### ISSUE TITLE
[tool_crash] ProcessException: 系统找不到指定的文件。 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2

### ISSUE THREAD

**Issue by izumkineno** [flutter/flutter#160970]
## Command
```sh
flutter run
```
I open dev tool, then it give this error
is must use chrome ?, I only use edge

## Logs
ProcessException: 系统找不到指定的文件。
 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2
```console
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:156:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:148:18)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:188:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:176:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1818:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1836:13)
#8      _rootRunUnary (dart:async/zone.dart:1407:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#16     _rootRunUnary (dart:async/zone.dart:1407:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on Microsoft Windows [版本 10.0.22631.3880], locale zh-CN)
    [32m•[39m Flutter version 3.24.5 on channel stable at E:\flutter\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (7 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at E:\Android
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = E:\Android
    [32m•[39m Java binary at: E:\Program\IntelliJ IDEA 2023.2\jdk\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 20.0.2+9-78)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
    [32m•[39m Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    [32m•[39m Visual Studio Community 2022 version 17.6.33815.320
    [32m•[39m Windows 10 SDK version 10.0.22000.0

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at E:\Program\android studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at C:\Users\CEO\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m AGS6 W00 (mobile) • 32ZBB24902202188 • android-arm64  • Android 12 (API 31)
    [32m•[39m Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.22631.3880]
    [32m•[39m Edge (web)        • edge             • web-javascript • Microsoft Edge 131.0.2903.112

[33m[!][39m Network resources
    [31m✗[39m A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

    [31m✗[39m A network error occurred while checking "https://github.com/": 信号灯超时时间已到


[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668
### Plugins
device_info_plus-9.1.2
fijkplayer-0.11.0
file_picker-8.1.6
file_selector_linux-0.9.3+2
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_baidu_mapapi_base-3.8.1
flutter_baidu_mapapi_map-3.8.1
flutter_bmflocation-3.6.0
flutter_plugin_android_lifecycle-2.0.23
image_picker-1.1.2
image_picker_android-0.8.12+17
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154940
