### ISSUE TITLE
Unable to compile iOS code when using package written in swift

### ISSUE THREAD

**Issue by s-bauer** [flutter/flutter#16097]
## Steps to Reproduce

1. "flutter create test"
2. add an library written in swift to the project. e.g. "https://github.com/s-bauer/loca_notifications_own"
3. try running on iOS using "flutter run"
4. Build fails with the log output found below

In contrast, anything works fine when I create the project using "flutter create -i swift test"

## Logs

```
flutter run
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Running pod install...                                       0.8s
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`arm64`)
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Pods/.symlinks/flutter/ios`
    -> Fetching podspec for `local_notifications` from `Pods/.symlinks/plugins/loca_notifications_own-64f732ba11141f2e5b53bc6c53e67c65b0fa7657/ios`
    
    Resolving dependencies of `Podfile`
    
    Comparing resolved specification to the sandbox manifest
      A Flutter
      A local_notifications
    
    Downloading dependencies
    
    -> Installing Flutter (1.0.0)
    
    -> Installing local_notifications (0.0.1)
      - Running pre install hooks
    [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: local_notifications
    
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:116:in `block (2 levels) in verify_framework_usage'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `each'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:111:in `block in verify_framework_usage'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `each'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:108:in `verify_framework_usage'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:406:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:118:in `install!'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
    
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone 8 Plus.

```

```
[✓] Flutter (Channel master, v0.2.5-pre.44, on Mac OS X 10.13 17A365, locale en-DE)
    • Flutter version 0.2.5-pre.44 at /Users/simonbauer/Desktop/flutter
    • Framework revision 067be92ae8 (3 days ago), 2018-03-26 22:16:48 -0700
    • Engine revision dd6f46c485
    • Dart version 2.0.0-dev.41.0.flutter-2f68e82526

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices (1 available)
    • iPhone 8 Plus • C8428C0E-6FBB-413C-904B-F00861D5DE56 • ios • iOS 11.2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by s-bauer** [comment]
A workarround I found is to copy the "ios/" directory of an swift project to the "normal" objective-c project. Then it compiles without problems

**Comment by xster** [comment]
Duping into #16049
