### ISSUE TITLE
flutter upgrade faile with error NoSuchMethodError: The getter 'isMacOS' was called on null.

### ISSUE THREAD

**Issue by jkicha** [flutter/flutter#16096]
## Steps to Reproduce

flutter upgrade -v throws the following error

```
G:\>flutter upgrade -v
[  +38 ms] [G:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +303 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/beta
[   +1 ms] [G:\flutter\] git rev-parse --abbrev-ref HEAD
[ +229 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +1 ms] [G:\flutter\] git ls-remote --get-url origin
[ +235 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] [G:\flutter\] git log -n 1 --pretty=format:%H
[ +261 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[        ] [G:\flutter\] git log -n 1 --pretty=format:%ar
[ +227 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 weeks ago
[   +2 ms] [G:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +219 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.2.3-0-g5a58b36
[ +419 ms] [G:\flutter\] git rev-parse @{u}
[ +271 ms] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[   +1 ms] Upgrading Flutter from G:\flutter...
[   +4 ms] [G:\flutter\] git pull --ff-only
[+12304 ms] From https://github.com/flutter/flutter
[   +5 ms]    3352a3f..bffae21  dev        -> origin/dev
[   +1 ms]    b4274ef..1d06722  master     -> origin/master
[   +1 ms]  * [new tag]         v0.2.5     -> v0.2.5
[ +271 ms] Already up-to-date.
[  +20 ms] Upgrading engine...
[   +1 ms] [G:\flutter\] bin\flutter --no-color precache
[+4639 ms] Already up-to-date.
[ +720 ms] Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
                   Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
                   Engine • revision e61bb9ac3a
                   Tools • Dart 2.0.0-dev.35.flutter-290c576264
[   +4 ms] Running flutter doctor...
[   +1 ms] [G:\flutter\] bin\flutter doctor
[+4321 ms] Doctor summary (to see all details, run flutter doctor -v):
**[+1818 ms] [√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.17127.1], locale en-IN)
[  +61 ms] Oops; flutter has exited unexpectedly.
[  +20 ms] Sending crash report to Google.
[+3422 ms] Crash report sent (report ID: e286ab55dfc5727f)
[ +826 ms] Unhandled exception:
[   +2 ms] NoSuchMethodError: The getter 'isMacOS' was called on null.
[   +3 ms] Receiver: null
[   +3 ms] Tried calling: isMacOS
[   +3 ms] #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)**
[   +5 ms] #1      IOSDevices.supportsPlatform (package:flutter_tools/src/ios/devices.dart:34)
[   +7 ms] #2      DeviceManager._platformDiscoverers.<anonymous closure> (package:flutter_tools/src/device.dart:85)
[   +5 ms] #3      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
[   +3 ms] #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:90)
[   +6 ms] <asynchronous suspension>
[   +3 ms] #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:560)
[   +7 ms] <asynchronous suspension>
[   +3 ms] #6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
[   +5 ms] #7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
[   +6 ms] <asynchronous suspension>
[   +4 ms] #8      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
[  +13 ms] #9      AppContext._run (package:flutter_tools/src/base/context.dart:76)
[   +5 ms] <asynchronous suspension>
[   +6 ms] #10     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
[   +5 ms] #11     _rootRun (dart:async/zone.dart:1126)
[   +3 ms] #12     _CustomZone.run (dart:async/zone.dart:1023)
[   +6 ms] #13     runZoned (dart:async/zone.dart:1501)
[   +4 ms] #14     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
[   +5 ms] #15     _doctorText (package:flutter_tools/runner.dart:237)
[   +6 ms] <asynchronous suspension>
[   +4 ms] #16     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
[   +5 ms] <asynchronous suspension>
[   +5 ms] #17     _handleToolError (package:flutter_tools/runner.dart:167)
[   +4 ms] <asynchronous suspension>
[   +3 ms] #18     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
[   +7 ms] <asynchronous suspension>
[   +4 ms] #19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
[   +5 ms] <asynchronous suspension>
[   +6 ms] #20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
[   +5 ms] #21     _rootRun (dart:async/zone.dart:1126)
[   +3 ms] #22     _CustomZone.run (dart:async/zone.dart:1023)
[   +5 ms] #23     runZoned (dart:async/zone.dart:1501)
[   +4 ms] #24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
[   +5 ms] #25     run (package:flutter_tools/runner.dart:61)
[   +4 ms] <asynchronous suspension>
[   +5 ms] #26     main (package:flutter_tools/executable.dart:48)
[   +4 ms] <asynchronous suspension>
[   +3 ms] #27     main (file:///G:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
[   +7 ms] #28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
[   +5 ms] #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
[  +69 ms] "flutter upgrade" took 29,105ms.
[ +266 ms] ensureAnalyticsSent: 260ms
[   +8 ms] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +4 ms] exiting with code 0
```

## Flutter Doctor

```
G:\>flutter doctor -v
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.17127.1], locale en-IN)
    • Flutter version 0.2.3 at G:\flutter
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264


Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: fb30d6b75a059426)
Unhandled exception:
NoSuchMethodError: The getter 'isMacOS' was called on null.
Receiver: null
Tried calling: isMacOS
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      IOSDevices.supportsPlatform (package:flutter_tools/src/ios/devices.dart:34)
#2      DeviceManager._platformDiscoverers.<anonymous closure> (package:flutter_tools/src/device.dart:85)
```

**Comment by 98732** [comment]
First time trying to use Flutter and that happened to me :/

**Comment by 98732** [comment]
Just switched from beta branch to v0.2.6 and it's working fine now

**Comment by srb24** [comment]
what command did you use to switch to v0.2.6?

**Comment by 98732** [comment]
Go to the folder where you installed (cloned) Flutter an then
```
git checkout "v0.2.6"
```
run ```flutter doctor``` again and prey for the best

**Comment by srb24** [comment]
thanks, it worked eventually ("totally uninstalling then reinstalling Android Studio)

**Comment by harrypunk** [comment]
@srb24 confirmed.
Tried uninstall Android Studio totally and install latest v3.1. Work perfectly.
```git checkout "v0.2.6"``` cause detached HEAD, better checkout with new branch```git checkout -b ...```

**Comment by kajaljoshi** [comment]
Hi all, I am getting same error. Switching to v2.0.6  is unexpectedly closing flutter doctor. And reinstalling angular studio also dont work for me. 
Getting same error : isMacOs  is null

**Comment by kajaljoshi** [comment]
Issue is solved for me, by switching to v0.1.5 of Beta branch.
I followed below step 
1. git clone -b beta https://github.com/flutter/flutter.git
2. git checkout "v0.1.5"

and then run flutter doctor.

**Comment by zoechi** [comment]
Is this still an issue with recent Flutter versions or does updating Flutter fix it as mentioned by kajaljoshi?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
