### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by deepakbhartiad** [flutter/flutter#160968]
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=72bf29de --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```console
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1457:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1324:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:927:22)
#3      _JsonStringDecoderSink.addSlice (dart:convert-patch/convert_patch.dart:1544:13)
#4      _JsonStringDecoderSink.add (dart:convert-patch/convert_patch.dart:1549:5)
#5      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#7      _rootRunUnary (dart:async/zone.dart:1422:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#16     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#17     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#18     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#19     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#20     _rootRunUnary (dart:async/zone.dart:1422:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
```
```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 12.7.4 21H1123 darwin-x64, locale en-IN)
    • Flutter version 3.27.1 on channel stable at /Users/mac/Developer/sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (13 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (3 available)
    • RMX3842 (mobile) • 72bf29de • android-arm64  • Android 14 (API 34)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 12.7.4 21H1123 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 5.0.0+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0850beeb25f6d5b10426284f506557f66181b36
### Plugins
connectivity_plus-6.0.5
file_picker-8.1.2
firebase_core-2.32.0
firebase_core_web-2.18.0
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
flutter_local_notifications-17.2.2
flutter_local_notifications_linux-4.0.1
flutter_plugin_android_lifecycle-2.0.22
local_auth-2.3.0
local_auth_android-1.0.46
local_auth_darwin-1.4.2
local_auth_windows-1.0.11
package_info_plus-8.1.1
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
share_plus-10.0.3
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sqflite-2.3.3+1
url_launcher-6.3.1
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.9.0
webview_flutter_android-3.16.7
webview_flutter_wkwebview-3.15.0
youtube_player_iframe-5.2.0
youtube_player_iframe_web-3.1.0

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905
