### ISSUE TITLE
flutter run -d macos --release - Null check operator used in a null value

### ISSUE THREAD

**Issue by hardmode98** [flutter/flutter#161026]
### Steps to reproduce

flutter build macos or flutter run -d macos --release

### Expected results

The build should go through but i get the below error , i got from building in verbose as well 

 ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      PhaseScriptExecution Run\ Script /Users/zeeshanmir/Projects/dott_native/build/macos/Build/Intermediates.noindex/Runner.build/Release/Flutter\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh
(in target 'Flutter Assemble' from project 'Runner')
[        ]      Building workspace Runner with scheme Runner and configuration Release
[        ] (2 failures)
[  +82 ms] Building macOS application... (completed in 26.8s)
[        ] Error: Build process failed
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:220:5)
           <asynchronous suspension>
           #2      MacOSDevice.buildForDevice (package:flutter_tools/src/macos/macos_device.dart:75:5)
           <asynchronous suspension>
           #3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:120:7)
           <asynchronous suspension>
           #4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:538:33)
           <asynchronous suspension>
           #5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:53:28)
           <asynchronous suspension>
           #6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:854:27)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #15     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
[   +9 ms] "flutter run" took 33,187ms.
[  +23 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:860:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +168 ms] ensureAnalyticsSent: 167ms
[        ] Running 2 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

### Actual results

The app should build 

### Code sample

<details open><summary>Code sample</summary>

```dart
Unhandled exception:
Null check operator used on a null value
#0      SummaryCollector.visitFunctionExpression (package:vm/transformations/type_flow/summary_collector.dart:1742)
#1      FunctionExpression.accept (package:kernel/src/ast/expressions.dart:4609)
#2      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#3      SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:1001)
#4      SummaryCollector.visitConstructorInvocation (package:vm/transformations/type_flow/summary_collector.dart:1735)
#5      ConstructorInvocation.accept (package:kernel/src/ast/expressions.dart:2687)
#6      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#7      SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:1001)
#8      SummaryCollector.visitConstructorInvocation (package:vm/transformations/type_flow/summary_collector.dart:1735)
#9      ConstructorInvocation.accept (package:kernel/src/ast/expressions.dart:2687)
#10     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#11     SummaryCollector.visitReturnStatement (package:vm/transformations/type_flow/summary_collector.dart:2408)
#12     ReturnStatement.accept (package:kernel/src/ast/statements.dart:1076)
#13     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:978)
#14     List.forEach (dart:core-patch/growable_array.dart:417)
#15     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:2251)
#16     Block.accept (package:kernel/src/ast/statements.dart:103)
#17     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:978)
#18     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:838)
#19     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1912)
#20     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:399)
#21     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:288)
#22     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1793)
#23     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1736)
#24     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1941)
#25     transformComponent (package:vm/transformations/type_flow/transformer.dart:122)
#26     runGlobalTransformations (package:vm/kernel_front_end.dart:639)
#27     compileToKernel (package:vm/kernel_front_end.dart:550)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:664)
<asynchronous suspension>
#29     starter (package:frontend_server/starter.dart:109)
<asynchronous suspension>
#30     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot_program failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 16.2)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.96.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Zeeshan’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources
```

</details>

**Comment by mraleph** [comment]
Likely duplicate of https://github.com/flutter/flutter/issues/159760

**Comment by huycozy** [comment]
I cannot reproduce this issue on the latest Flutter stable version `3.27.1`. The fix has likely been landed on this stable version (regarding latest comments at https://github.com/flutter/flutter/issues/159760). So, @hardmode98 please try upgrading your Flutter SDK and retry. Thanks! Marking this as a duplicate of https://github.com/flutter/flutter/issues/159760.
