### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2

### ISSUE THREAD

**Issue by azizi06** [flutter/flutter#161023]
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: .\Google\Chrome\Application\chrome.exe, OS error code: 2
```console
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:177:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:170:13)
#4      FlutterResidentDevtoolsHandler._launchDevToolsForDevices (package:flutter_tools/src/resident_devtools_handler.dart:180:24)
#5      FlutterResidentDevtoolsHandler.launchDevToolsInBrowser (package:flutter_tools/src/resident_devtools_handler.dart:168:7)
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1768:56)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1786:13)
#8      _rootRunUnary (dart:async/zone.dart:1422:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:370:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:467:11)
#16     _rootRunUnary (dart:async/zone.dart:1422:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1324:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1233:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#23     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#24     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
```
```console
[32m[✓][39m Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.22631.4602], locale en-US)
    [32m•[39m Flutter version 3.27.1 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 17025dd882 (2 weeks ago), 2024-12-17 03:23:09 +0900
    [32m•[39m Engine revision cb4b5fff73
    [32m•[39m Dart version 3.6.0
    [32m•[39m DevTools version 2.40.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at D:\Android-SDK
    [32m•[39m Platform android-35, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Java\jdk-20\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 20.0.2+9-78)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at D:\Android
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at C:\Users\محمد عبد العزيز\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m SM F127G (mobile) • RZ8T40YE4PP • android-arm64  • Android 13 (API 33)
    [32m•[39m Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    [32m•[39m Edge (web)        • edge        • web-javascript • Microsoft Edge 131.0.2903.112

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 17025dd88227cd9532c33fa78f5250d548d87e9a
### Plugins
cloud_firestore-5.6.0
cloud_firestore_web-4.4.0
firebase_auth-5.3.4
firebase_auth_web-5.13.5
firebase_core-3.9.0
firebase_core_web-2.19.0
firebase_messaging-15.1.6
firebase_messaging_web-3.9.5
google_sign_in-6.2.2
google_sign_in_android-6.1.34
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3
path_provider-2.1.5
path_provider_android-2.2.15
path_provider_foundation-2.4.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.4
shared_preferences_android-2.4.0
shared_preferences_foundation-2.5.4
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1

**Comment by azizi06** [comment]
issue resolved with
```bash
flutter clean
```

**Comment by danagbemava-nc** [comment]
Hi @azizi06, did you try to open devtools without chrome installed?
