### ISSUE TITLE
Exception calling static functions using Dart 2 syntax when building from Android Studio

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#16110]
The below snippet works fine in Xcode and IntelliJ for both iOS/Android. However, running in Android Studio, despite being on the newest version (3.1), will result in an exception. It will run if you add `new` before calling the `testFunc` static method on `TestModel`. I suspect the issue is with the Flutter/Dart plugins in Android Studio.

```
03-30 15:04:35.834 31145-31168/com.example.fluttersample I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
03-30 15:04:35.848 31145-31168/com.example.fluttersample I/flutter: The following NoSuchMethodError was thrown building Builder:
    No static method 'testFunc' declared in class 'TestModel'.
    Receiver: TestModel
    Tried calling: testFunc(true)
03-30 15:04:35.893 31145-31168/com.example.fluttersample I/flutter: When the exception was thrown, this was the stack:
03-30 15:04:35.919 31145-31168/com.example.fluttersample I/flutter: #0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
    #1      _MyHomePageState.initState (file:///Users/albertlardizabal/dev/flutter-examples/flutter_sample/lib/main.dart:46)
```

Sample Code:
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class TestModel {
  final bool testFlag;

  TestModel.testFunc(bool flag)
      : this.testFlag = flag;
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    // the below fails
    final testModel = TestModel.testFunc(true);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

`flutter doctor -v`
```
[✓] Flutter (Channel master, v0.2.6, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.6 at /Users/albertlardizabal/dev/flutter
    • Framework revision 1d067220da (14 hours ago), 2018-03-29 22:14:04 -0700
    • Engine revision 9af82c5a1a
    • Dart version 2.0.0-dev.43.0.flutter-e305117519

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Android NDK at /Users/albertlardizabal/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25
```

**Comment by xster** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
@alardizabal, that error looks like it's coming from the runtime (and not something like the analyzer). 

> works fine in Xcode and IntelliJ for both iOS/Android. However, running in Android Studio

Two ways I could see this happening:

- you're pointing to a different version of the flutter sdk in Android Studio (as opposed to the one IntelliJ is pointing to)
- you have different values of the `Run apps in Dart 2.0 mode` set in IntelliJ vs. Android Studio (one running w/ --preview-dart-2, and one without); I'd double check that first; some more docs here: https://github.com/flutter/flutter-intellij#preview-dart-2

**Comment by alardizabal** [comment]
@devoncarew screenshots from AS below (still seeing the exception). Do you see anything off?

<img width="777" alt="screen shot 2018-03-30 at 7 35 30 pm" src="https://user-images.githubusercontent.com/3614291/38157141-1170f20c-3452-11e8-957c-38b1eae341c1.png">

<img width="777" alt="screen shot 2018-03-30 at 7 35 42 pm" src="https://user-images.githubusercontent.com/3614291/38157144-13791b9c-3452-11e8-86ac-61b9fc3fcc71.png">

**Comment by devoncarew** [comment]
> Do you see anything off?

No - w/o android studio and having a different setting or sdk from `flutter run`, I can't explain whats going on here.

My only advice would be to wait for issues like https://github.com/dart-lang/sdk/issues/32737 to be fixed - slightly better behavior of the runtime wrt optional new and consts.

**Comment by Hixie** [comment]
@alardizabal Do you still see this?

**Comment by alardizabal** [comment]
@Hixie This looks fixed to me. Thanks!

**Comment by patelkrunal78** [comment]
You can write a file with just that function, like:

test.dart

void launchWebView () {
print("1234");
}
and then import that file like this:

main.dart

import "test.dart";

class _MyHomePageState extends State<MyHomePage> {
@override
Widget build(BuildContext context) {
launchWebView();

Find Code At [Here](https://icetutor.com/question/how-to-use-functions-of-another-file-in-dart-flutter)
