### ISSUE TITLE
 Unhandled exceptions

### ISSUE THREAD

**Issue by hgabe** [flutter/flutter#16141]
running ---> flutter upgrade
```
Upgrading Flutter from /home/hgabe/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (3 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_US.UTF-8)
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


## flutter analyze

No application yet just running flutter upgrade and flutter doctor -v

Run `flutter analyze` and attach any output of that command also.

Analyzing /home/homefolder...
Unhandled exception:
FileSystemException: Directory listing failed, path = '/home/hgabe/.cache/dconf' (OS Error: Permission denied, errno = 13)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:34)
#1      _Directory.listSync (dart:io/directory_impl.dart:214)
#2      Driver._collectFiles (package:analyzer_cli/src/driver.dart:596)
#3      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:317)
<asynchronous suspension>
#4      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:231)
<asynchronous suspension>
#5      Driver.start (package:analyzer_cli/src/driver.dart:200)
<asynchronous suspension>
#6      main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart:13)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
(Ran in 1.8s)
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.3 at /home/hgabe/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

```
-Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by zoechi** [comment]
Sorry for not being able to come back to this earlier.
A lot has changed since then. Is this still an issue?

**Comment by hgabe** [comment]
no you can close it

**Comment by zoechi** [comment]
@hgabe Great! Thanks a lot for the feedback.
