### ISSUE TITLE
Firebase messaging for topics is partially working

### ISSUE THREAD

**Issue by cybaker** [flutter/flutter#16166]
```
Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git Framework • revision 5a58b36e36 (3 weeks ago) • 2018-03-13 13:20:13 -0700 Engine • revision e61bb9ac3a Tools • Dart 2.0.0-dev.35.flutter-290c576264
```

I have also tried disabling Dart 2. The behavior is the same for both Dart 1 and 2. This might be related to issue #15541.

Firebase user segment messaging is working for the messaging example when a message is issued and the app is in foreground, background, or terminated. In the foreground, FirebaseMessaging.onMessage is called. In the background, after the user taps on the system notification, FirebaseMessaging.onResume is called. In killed, after the user taps on the system notification, FirebaseMessaging.onLaunch is called. These are all called with with the desired message keys and values.

Firebase topic messaging is working only in foreground mode. FirebaseMessaging.onMessage is called with the desired message keys and values. When in background or killed state, after the user taps on the system notification, neither FirebaseMessaging.onResume or FirebaseMessaging.onLaunch is called. A FlutterActivityDelegate message is shown in the debugger instead, the message being "onResume setting current activity to this", which shows up in FlutterActivityDelegate.java code.

The below is the output from two messages sent, one with the app in the foreground receiving onMessage, and the second is when the app is in the background and after the user taps the system notification to resume the app.

```
I/flutter (11925): onMessage: {keyTest: valueTest}
I/FlutterActivityDelegate(11925): onResume setting current activity to this
```

## Steps to Reproduce
Run example messaging Flutter app
Subscribe to a test topic
Leave app in the foreground
Issue a Push Message from Firebase Notification console for the test topic
Note onMessage is called
Tap the home button putting the app in the background
Issue the same Push Message from Firebase Notification console for the test topic
Note that onMessage, onResume, and onLaunch are not called and note the onResume setting current activity to this message from FlutterActivityDelegate

## Logs
```
I/flutter (11925): onMessage: {keyTest: valueTest}
I/FlutterActivityDelegate(11925): onResume setting current activity to this
```

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by ItsCalebJones** [comment]
I am seeing this issue as well, thought I was going crazy.

**Comment by jmcdole** [comment]
I think I am having luck by adding the FLUTTER_NOTIFICATION_CLICK to the message payload as described under sending messages: https://pub.dartlang.org/packages/firebase_messaging

![screen shot 2018-05-30 at 3 57 16 pm](https://user-images.githubusercontent.com/20527861/40744361-48bdc884-6422-11e8-9790-340733e38678.png)

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by followthemoney1** [comment]
the same
```
2019-04-22 15:32:23.824 18384-18384/menus.flutterocrmenu E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: No virtual method subscribeToTopic(Ljava/lang/String;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/messaging/FirebaseMessaging; or its super classes (declaration of 'com.google.firebase.messaging.FirebaseMessaging' appears in /data/app/menus.flutterocrmenu-YaDxa_jVuTQF4GMbmws2fQ==/base.apk!classes17.dex)
        at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:112)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-22 15:32:23.824 18384-18384/menus.flutterocrmenu A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
2019-04-22 15:32:23.824 18384-18384/menus.flutterocrmenu A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18384 (.flutterocrmenu), pid 18384 (.flutterocrmenu)
2019-04-22 15:
```
