### ISSUE TITLE
Unable to run flutter codelab step_5_data_syncing

### ISSUE THREAD

**Issue by bourrhia** [flutter/flutter#16179]
## Steps to Reproduce

Hi,

I'm currently going through the Flutter Firebase codelab step_5_data_syncing.
Downloaded the sample code for the firebase codelab.
Tried to run step 5 on my Android device.
I've followed all the steps, but I'm getting the following error : 

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk (28.3MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate( 7307): onResume setting current activity to this
D/        ( 7307): HostConnection::get() New Host Connection established 0xe6c92e00, tid 7341
D/EGL_emulation( 7307): eglMakeCurrent: 0xee764ec0: ver 3 0 (tinfo 0xe6c835f0)
I/Choreographer( 7307): Skipped 42 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 7307): eglMakeCurrent: 0xee765460: ver 3 0 (tinfo 0xe52bbb80)
Syncing files to device Android SDK built for x86...
I/flutter ( 7307): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7307): The following assertion was thrown building ChatScreen(dirty, state: ChatScreenState#fa4a5):
I/flutter ( 7307): type '(dynamic, DataSnapshot, Animation<double>) => dynamic' is not a subtype of type
I/flutter ( 7307): 'FirebaseAnimatedListItemBuilder' of 'itemBuilder'
I/flutter ( 7307): 
I/flutter ( 7307): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7307): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7307): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7307):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7307): 
I/flutter ( 7307): When the exception was thrown, this was the stack:
I/flutter ( 7307): #0      new FirebaseAnimatedList (package:firebase_database/ui/firebase_animated_list.dart:25)
I/flutter ( 7307): #1      ChatScreenState.build (file:///Users/Bourrhia/IdeaProjects/myfirstfriendlychat/lib/main.dart:138)
I/flutter ( 7307): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713)
I/flutter ( 7307): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625)
I/flutter ( 7307): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #76     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #79     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738)
I/flutter ( 7307): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #82     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493)
I/flutter ( 7307): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #98     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #108    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #117    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633)
I/flutter ( 7307): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #149    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #151    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #157    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #161    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #162    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #163    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #170    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #176    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #187    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #188    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #197    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #199    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #200    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #201    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #202    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #206    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #207    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #212    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #214    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752)
I/flutter ( 7307): #215    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7307): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7307): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7307): #221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7307): #222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7307): #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7307): #224    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852)
I/flutter ( 7307): #225    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823)
I/flutter ( 7307): #226    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769)
I/flutter ( 7307): #227    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205)
I/flutter ( 7307): #228    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768)
I/flutter ( 7307): #229    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657)
I/flutter ( 7307): #230    runApp (package:flutter/src/widgets/binding.dart:699)
I/flutter ( 7307): #231    main (file:///Users/Bourrhia/IdeaProjects/myfirstfriendlychat/lib/main.dart:39)
I/flutter ( 7307): #232    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
I/flutter ( 7307): #233    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter ( 7307): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/FirebaseAuth( 7307): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth( 7307): [FirebaseAuth:] Preparing to create service connection to gms implementation
```

## Logs

**# flutter analyze**
```
Analyzing /Users/Bourrhia/IdeaProjects/myfirstfriendlychat...
  error • The argument type '(BuildContext, DataSnapshot, Animation<double>) → ChatMessage' can't be assigned to the parameter type '(BuildContext, DataSnapshot, Animation<double>, int) → Widget' at lib/main.dart:135:15 • argument_type_not_assignable
  error • Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart' at test/widget_test.dart:8:8 • uri_does_not_exist
  error • The function 'testWidgets' isn't defined at test/widget_test.dart:13:3 • undefined_function
  error • Undefined class 'WidgetTester' at test/widget_test.dart:13:49 • undefined_class
  error • Undefined class 'MyApp' at test/widget_test.dart:15:33 • undefined_class
  error • The function 'expect' isn't defined at test/widget_test.dart:18:5 • undefined_function
  error • Undefined name 'find' at test/widget_test.dart:18:12 • undefined_identifier
  error • Undefined name 'findsOneWidget' at test/widget_test.dart:18:28 • undefined_identifier
  error • The function 'expect' isn't defined at test/widget_test.dart:19:5 • undefined_function
  error • Undefined name 'find' at test/widget_test.dart:19:12 • undefined_identifier
  error • Undefined name 'findsNothing' at test/widget_test.dart:19:28 • undefined_identifier
  error • Undefined name 'find' at test/widget_test.dart:22:22 • undefined_identifier
  error • The function 'expect' isn't defined at test/widget_test.dart:26:5 • undefined_function
  error • Undefined name 'find' at test/widget_test.dart:26:12 • undefined_identifier
  error • Undefined name 'findsNothing' at test/widget_test.dart:26:28 • undefined_identifier
  error • The function 'expect' isn't defined at test/widget_test.dart:27:5 • undefined_function
  error • Undefined name 'find' at test/widget_test.dart:27:12 • undefined_identifier
  error • Undefined name 'findsOneWidget' at test/widget_test.dart:27:28 • undefined_identifier
  hint • The top level variable '_name' isn't used at lib/main.dart:31:14 • unused_element
  hint • Unused import: 'package:myfirstfriendlychat/main.dart' at test/widget_test.dart:10:8 • unused_import
20 issues found.
(Ran in 7.8s)
```
## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D47, locale fr-FR)
    • Flutter version 0.2.3 at /USERS/Bourrhia/Documents/Web_dev/Flutter_apps/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Bourrhia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by Sfshaza** [comment]
The original Firebase+Flutter codelab has been obsoleted and replaced by another Firebase+Flutter codelab, at the same URL. (Baby name vote generator.)

Closing.
