### ISSUE TITLE
`flutter run --machine` doesn't correctly stop/terminate if sent app.stop during build

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#16183]
If I try to terminate before the build has finished, I get back a response from the `app.stop` (and a message saying `Application finished`, but it carries on running and launches the app (resulting in a white paused screen, because I never connect to the debugger).

```text
[14:02:24]: Spawning /Users/dantup/Dev/Google/flutter/bin/flutter with args ["run","--machine","-t","lib/main.dart","-d","E9DE19A9-CB73-48B2-8152-3912BAB91CB0","--start-paused"]
[14:02:24]: ..  in /Users/dantup/Dev/Google/flutter/examples/stocks
[14:02:24]: ..  in {"FLUTTER_HOST":"VSCode"}
[14:02:25]: <== [{"event":"app.start","params":{"appId":"beb6d2a6-ce0e-43cb-986c-8fb61953c7e8","deviceId":"E9DE19A9-CB73-48B2-8152-3912BAB91CB0","directory":"/Users/dantup/Dev/Google/flutter/examples/stocks","supportsRestart":true}}]
[14:02:26]: <== Launching lib/main.dart on iPhone X in debug mode...
[14:02:27]: ==> [{"id":"1","method":"app.stop","params":{"appId":"beb6d2a6-ce0e-43cb-986c-8fb61953c7e8"}}]
[14:02:27]: <== Application finished.
[14:02:27]: <== [{"id":"1","result":true}]
[14:02:31]: <== [{"event":"app.debugPort","params":{"appId":"beb6d2a6-ce0e-43cb-986c-8fb61953c7e8","port":8100,"wsUri":"ws://127.0.0.1:8100/ws","baseUri":"file:///Users/dantup/Library/Developer/CoreSimulator/Devices/E9DE19A9-CB73-48B2-8152-3912BAB91CB0/data/Containers/Data/Application/E4D448D4-5694-4A87-B302-D785B3315041/tmp/stocksZtBNGN/stocks/"}}]
[14:02:31]: <== [{"event":"app.progress","params":{"appId":"beb6d2a6-ce0e-43cb-986c-8fb61953c7e8","id":"0","progressId":null,"message":"Syncing files to device iPhone X..."}}]
// ...
```

**Comment by DanTup** [comment]
I tried sending `daemon.shutdown` too, that also didn't work:

```text
[14:28:23]: ==> [{"id":"1","method":"app.stop","params":{"appId":"c6768494-fe7c-4b15-a98d-6050e9f4b115"}}]
[14:28:23]: <== Application finished.
[14:28:23]: <== [{"id":"1","result":true}]
[14:28:23]: ==> [{"id":"2","method":"daemon.shutdown"}]
[14:28:23]: <== [{"id":"2"}]
[14:28:27]: <== [{"event":"app.debugPort","params":{"appId":"c6768494-fe7c-4b15-a98d-6050e9f4b115","port":8100,"wsUri":"ws://127.0.0.1:8100/ws","baseUri":"file:///Users/dantup/Library/Developer/CoreSimulator/Devices/E9DE19A9-CB73-48B2-8152-3912BAB91CB0/data/Containers/Data/Application/EC829325-CF87-4DDF-B7D2-E3F2884814A9/tmp/stocks7Am83u/stocks/"}}]
[14:28:27]: <== [{"event":"app.progress","params":{"appId":"c6768494-fe7c-4b15-a98d-6050e9f4b115","id":"0","progressId":null,"message":"Syncing files to device iPhone X..."}}]
[14:28:29]: <== [{"event":"app.progress","params":{"appId":"c6768494-fe7c-4b15-a98d-6050e9f4b115","id":"0","progressId":null,"finished":true}}]
[14:28:29]: <== [{"event":"app.started","params":{"appId":"c6768494-fe7c-4b15-a98d-6050e9f4b115"}}]
```

**Comment by DanTup** [comment]
I don't like the idea of SIGKILL - apparently that gives the application no possibility for cleanup which increases the chances of me leaving processes around (which is the thing I'm trying to fix). It would also be a race, because as I issue the SIGKILL, flutter could've started the app and be sending me an `app.started`.

**Comment by devoncarew** [comment]
We do listen for both `SIGINT` and `SIGTERM` in flutter_tools, and handle cleanup when we receive them (from looking up `SIGKILL`, you're correct in that looks like too big of a hammer).

**Comment by devoncarew** [comment]
https://github.com/flutter/flutter/blob/af74a7253b5117cfd999d338db1eec4aea0f6fbf/packages/flutter_tools/lib/src/resident_runner.dart#L585

**Comment by DanTup** [comment]
I think something weird might be happening because I'm having to spawn using a shell (to fix issues with spaces in paths). Should `daemon.shutdown` do the same thing?

**Comment by DanTup** [comment]
@devoncarew I managed to eliminate my use of `shell` and I'm sure there's something still wrong here. Given this script:

```ts
import * as child_process from "child_process";

const p = child_process.spawn(
	"/Users/dantup/Dev/Google/flutter/bin/flutter",
	["run", "--machine"],
	{ cwd: "/Users/dantup/Dev/Google/flutter/examples/stocks", stdio: "inherit" },
);

setTimeout(() => {
	console.log("##########################");
	console.log("#### KILLING PROCESS");
	console.log("##########################");
	p.kill();
}, 10000);
```

Running via node, the process never finishes and there are two `dart` processes left living after the `kill` command is sent. I tried with both `SIGTERM` and `SIGINT`.

```text
dantup-macbookpro:Dart-Code dantup$ node out/tool/test_flutter_terminate.js 
[{"event":"app.start","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","deviceId":"E9DE19A9-CB73-48B2-8152-3912BAB91CB0","directory":"/Users/dantup/Dev/Google/flutter/examples/stocks","supportsRestart":true}}]
Launching lib/main.dart on iPhone X in debug mode...
Skipping compilation. Fingerprint match.
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"0","progressId":null,"message":"Running Xcode clean..."}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"0","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"1","progressId":null,"message":"Starting Xcode build..."}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"1","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"2","progressId":null,"message":" ├─Assembling Flutter resources..."}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"2","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"1","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"3","progressId":null,"message":" └─Compiling, linking and signing..."}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"3","progressId":null,"finished":true}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"1","progressId":null,"finished":true}}]
Xcode build done.                                            3.7s
##########################
#### KILLING PROCESS
##########################
[{"event":"app.debugPort","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","port":8100,"wsUri":"ws://127.0.0.1:8100/ws","baseUri":"file:///Users/dantup/Library/Developer/CoreSimulator/Devices/E9DE19A9-CB73-48B2-8152-3912BAB91CB0/data/Containers/Data/Application/2558A0A1-337F-40E2-BEEB-4A7AC3D851B8/tmp/stocksamVuqF/stocks/"}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"4","progressId":null,"message":"Syncing files to device iPhone X..."}}]
[{"event":"app.progress","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf","id":"4","progressId":null,"finished":true}}]
[{"event":"app.started","params":{"appId":"308dd579-018f-4336-af22-e4c753b4cfbf"}}]
```

**Comment by DanTup** [comment]
(note: if I wait for 30 seconds instead of 10, then the nodejs process does seem to finish, however it still leaves two dart processes around)

**Comment by DanTup** [comment]
Ok, I changed my code to call `flutter_tools.dart` directly like this:

```ts
const p = child_process.spawn(
	"/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart",
	["/Users/dantup/Dev/Google/flutter/packages/flutter_tools/bin/flutter_tools.dart", "run", "--machine"],
	{ cwd: "/Users/dantup/Dev/Google/flutter/examples/stocks", stdio: "inherit" },
);
```

And as far as I can tell, it's now working correctly. So, I'm wondering whether this is caused by the flutter binary. I'm not sure how that's built - is there any obvious reason why that might behave differently?

**Comment by DanTup** [comment]
Oh, it's not a binary, it's just a shell script :-/

**Comment by DanTup** [comment]
Ok, seems like spawning a shell script means the `kill` process goes to the shell (eg. bash) and it is free to just ignore it. a Possible fix is to spawn with `detached: true` and then kill by passing negative `pid`:

https://stackoverflow.com/questions/33325301/killing-a-bash-script-does-not-kill-child-processes/33431896

However, it seems like this may spawn command windows on Windows.

I think to make this work reliably and well we should handle it within Flutter, and allow something like `app.stop` or `daemon.shutdown` to cleanly tear everything down and terminate.

**Comment by DanTup** [comment]
Sending `daemon.shutdown` doesn't seem to cleanly shutdown, and results in an error to `stderr`:

```text
[11:36:17]: ==> [{"id":"1","method":"app.stop","params":{"appId":"47595436-0791-42b0-8606-4b6e861260ad"}}]
[11:36:17]: <== Application finished.
[11:36:17]: <== [{"id":"1","result":true}]
[11:36:17]: ==> [{"id":"2","method":"daemon.shutdown"}]
[11:36:17]: <== [{"id":"2"}]
[11:36:18]: ERR Unhandled exception:
Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:253)
#1      _IOSSimulatorLogReader._onDeviceLine (package:flutter_tools/src/ios/simulators.dart:634)
#2      _rootRunUnary (dart:async/zone.dart:1134)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#7      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#8      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#9      _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#10     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#11     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#12     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#14     _rootRunUnary (dart:async/zone.dart:1134)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#24     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_c…
```

I don't know if the error is the reason it's not cleaning up properly or not though.

**Comment by DanTup** [comment]
Even when it doesn't error, it doesn't stop:

```text
[12:51:30]: Spawning /Users/dantup/Dev/Google/flutter/bin/flutter with args ["run","--machine","-t","lib/main.dart","-d","E9DE19A9-CB73-48B2-8152-3912BAB91CB0","--start-paused"]
[12:51:30]: ..  in /Users/dantup/Dev/Google/flutter/examples/stocks
[12:51:30]: ..  in {"FLUTTER_HOST":"VSCode"}
[12:51:31]: <== [{"event":"app.start","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","deviceId":"E9DE19A9-CB73-48B2-8152-3912BAB91CB0","directory":"/Users/dantup/Dev/Google/flutter/examples/stocks","supportsRestart":true}}]
[12:51:32]: <== Launching lib/main.dart on iPhone X in debug mode...
[12:51:36]: ==> [{"id":"1","method":"app.stop","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa"}}]
[12:51:36]: <== Application finished.
[12:51:36]: <== [{"id":"1","result":true}]
[12:51:36]: ==> [{"id":"2","method":"daemon.shutdown"}]
[12:51:36]: <== [{"id":"2"}]
[12:51:40]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"0","progressId":null,"message":"Running Xcode clean..."}}]
[12:51:40]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"0","progressId":null,"finished":true}}]
[12:51:40]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"1","progressId":null,"message":"Starting Xcode build..."}}]
[12:51:49]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"1","progressId":null,"finished":true}}]
[12:51:49]: <== Xcode build done.
[12:51:54]: <== [{"event":"app.debugPort","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","port":8100,"wsUri":"ws://127.0.0.1:8100/ws","baseUri":"file:///Users/dantup/Library/Developer/CoreSimulator/Devices/E9DE19A9-CB73-48B2-8152-3912BAB91CB0/data/Containers/Data/Application/968C4E05-6520-42C8-A13D-B904A53CFCD4/tmp/stocksIgQru0/stocks/"}}]
[12:51:54]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"2","progressId":null,"message":"Syncing files to device iPhone X..."}}]
[12:51:57]: <== [{"event":"app.progress","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa","id":"2","progressId":null,"finished":true}}]
[12:51:57]: <== [{"event":"app.started","params":{"appId":"3d40c9e5-b7cd-4f01-8a8c-353d2408a4aa"}}]
[12:51:57]: 
```

**Comment by devoncarew** [comment]
Some notes:
- we think the best resolution here is for `daemon.shutdown` to work better (`Bad state: Cannot add new events after calling close`)
- and, for `app.stop` to be able to stop apps in the middle of a build (it currently ignores it, and continues to build)

**Comment by DanTup** [comment]
@devoncarew Ok, I have a failiing test for this issue, however it turns out to not be as straight forward as I hoped!

The chain from starting to running one of the build processes looks like this:

`AppDomain.start` -> `AppDomain.startApp` -> `HotRunner.run` -> `FlutterDevice.runHot` -> `IOSSimulator(or AndroidDevice!).startApp` -> `IOSSimulator._setupUpdatedApplicationBundle` -> `_sideloadUpdatedAssetsForInstalledApplicationBundle` -> `bundle.build` -> `Snapshotter.buildScriptSnapshot` -> `GenSnapshot.run` -> `runCommandAndStreamOutput`

In `runCommandAndStreamOutput` there doesn't currently seem to be any way to cancel and terminate the process. I'm not sure of the best way to handle this. It seems to me like the best way would be to have some sort of cancellation token we can pass all the way through this chain (and all other related calls) which allows us to signal a cancellation from the top and have any long-running processes cancelled.

In C# there's `CancellationTokenSource`/`CancellationToken` for this kind of thing (you create a source which gives you a token and `cancel` method; the token gets passed down and has a boolean for whether it's cancelled and some kind of event for cancellation). I can't tell if Dart has anything similar but I think it could work here (we create the source at the top level and feed the token down through all these methods, and when we spawn a process we can chain onto the tokens cancellation Future with a .kill call). This feels cleaner than collecting all the processes into some big list that we can terminate. WDYT?

**Comment by DanTup** [comment]
Ok, I may have some ideas for easier fixes here! :)

While investigating https://github.com/Dart-Code/Dart-Code/issues/907 I realised that I could get the `pid` from Observatory for the VM process and terminate that to avoid dangling processes. It worked fine; though in the case of `flutter run` it's not the VM process running the app we want to terminate, it's the `flutter run` process.

So I rigged the `app.start` event to provide the `pid` of the current process, and changed Dart Code to also terminate that. It solves this issue - it sends a kill signal to the Flutter tools, and it avoids the app from launching.

While doing this, it also occurred to me that since `flutter run` is handling the `app.stop` request ok, another possible fix could be to just exit the process inside the `app.stop` code (if running in `--machine` mode). I'll need to do a little more testing there though.

If we decide to expose the `pid`, we may wish to add a new startup event rather than putting it into `app.start`, since that feels a bit app-specific (and this is the pid of its own process). If we did do this, it'd also give us somewhere to put a version number to simplify clients being able to adapt behaviour based on the version (for example, knowing whether it's valid to send emulator commands rather than relying on being able to send a request with no side-effects and catch the error).

**Comment by DanTup** [comment]
Ok, calling `exit(1);` inside ResidentRunner's `appFinished` method also seems to solve the issue. It might not be a good idea doing it there (since we might not be in `run --machine`) and I don't know if we should be calling something like `_cleanUpAndExit` instead; but this seems like the simplest fix - no change to the external interface.

@devoncarew WDYT?

**Comment by DanTup** [comment]
I've opened a PR at https://github.com/flutter/flutter/pull/17873. Although it doesn't directly fix this issue, it would give clients a way to ensure they can get the kill signal to the correct process.

**Comment by DanTup** [comment]
Closing this because #17873 has given me a way to fix in Dart Code. We can re-open if it becomes an issue we'd like to solve in flutter_tools but for now there are better things to spend effort on!
