### ISSUE TITLE
RangeError crash in _StringBase.substring

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#16200]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

RangeError: RangeError: Value not in range: 1

```
#0      _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:372)
#1      ApkManifestData.parseFromAaptBadging (package:flutter_tools/src/application_package.dart:340)
#2      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:61)
#3      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:90)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:382)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:401)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:49)
#36     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#37     main (file:///c:/git/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.2.8-pre.3, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.2.8-pre.3 at c:\git\flutter
    • Framework revision b397406561 (26 hours ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\timsneath\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by Hixie** [comment]
Do you have steps to reproduce? (e.g. the code you were running?)

cc @jason-simmons

**Comment by timsneath** [comment]
I've shared the project with you both. Steps: should be as simple as just unzipping it and running `flutter run`.

**Comment by Hixie** [comment]
Based on Jason's research it sounds like this may be Windows-only.

**Comment by Pushkar98** [comment]
Hey we are getting the same error pointed out above. However going by the feed, the solution is not clear for the same. Can anyone help?
