### ISSUE TITLE
Document how FutureBuilder.builder shouldn't include logic beyond building widgets (e.g. don't call Navigator.push), and say where to put that logic instead

### ISSUE THREAD

**Issue by marscj** [flutter/flutter#16218]
How to call Navigator.push in FutureBuilder

error log:
```
I/flutter (29158): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═════════════════════════════════════════════
I/flutter (29158): The following assertion was thrown building FutureBuilder<Result>(dirty, state:
I/flutter (29158): _FutureBuilderState<Result>#de36b):
I/flutter (29158): setState() or markNeedsBuild() called during build.
I/flutter (29158): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (29158): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (29158): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (29158): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (29158): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (29158): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (29158):   Overlay-[LabeledGlobalKey<OverlayState>#a53eb](state: OverlayState#95866(entries:
I/flutter (29158):   [OverlayEntry#8b3e2(opaque: false; maintainState: false), OverlayEntry#0c205(opaque: false;
I/flutter (29158):   maintainState: true), OverlayEntry#8b1ef(opaque: false; maintainState: false),
I/flutter (29158):   OverlayEntry#bcfba(opaque: false; maintainState: true)]))
I/flutter (29158): The widget which was currently being built when the offending call was made was:
I/flutter (29158):   FutureBuilder<Result>(dirty, state: _FutureBuilderState<Result>#de36b)
I/flutter (29158):
I/flutter (29158): When the exception was thrown, this was the stack:
I/flutter (29158): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3419:11)
I/flutter (29158): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3445:6)
I/flutter (29158): #2      State.setState (package:flutter/src/widgets/framework.dart:1124:14)
I/flutter (29158): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
I/flutter (29158): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:35:24)
I/flutter (29158): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:167:18)
I/flutter (29158): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:719:18)
I/flutter (29158): #7      NavigatorState.push.<anonymous closure> (package:flutter/src/widgets/navigator.dart:925:13)
I/flutter (29158): #8      State.setState (package:flutter/src/widgets/framework.dart:1108:30)
I/flutter (29158): #9      NavigatorState.push (package:flutter/src/widgets/navigator.dart:922:5)
I/flutter (29158): #10     Navigator.push (package:flutter/src/widgets/navigator.dart:557:34)
I/flutter (29158): #11     OrderListState.build.futureBuilder.<anonymous closure> (package:dispature/screen/order_new.dart:73:27)
I/flutter (29158): #12     _FutureBuilderState.build (package:flutter/src/widgets/async.dart:504:48)
I/flutter (29158): #13     StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (29158): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (29158): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (29158): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (29158): #17     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (29158): #18     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (29158): #19     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (29158): #20     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (29158): #21     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (29158): #22     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter (29158): #23     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (29158): ══════════════════════════════════════════════
```

**Comment by marscj** [comment]
Sometimes the connection server returns 401. At this point I want to jump to the login screen

**Comment by marscj** [comment]
futureBuilder(){
      if (retry > 0)
      return new FutureBuilder<model.Result>(
        future: loader.orderStaff(),
        builder: (BuildContext context, AsyncSnapshot<model.Result> snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.none:
            case ConnectionState.waiting:
              return new CircularProgressIndicator();
            default:
              if (snapshot.hasError) {
                return new OffLineWidget(onTap: () {
                  setState((){
                    retry ++;
                  });
                });
              } else if (snapshot.data.statusCode == 200) {
                return new ListView.builder(
                    padding: kMaterialListPadding,
                    key: const ValueKey<String>('task-list'),
                    itemCount: snapshot.data.data.orders.length,
                    itemBuilder: (BuildContext context, int index) {
                      return new Text('abc');
                      // return new TaskRow(
                      //   task: taskPage.tasks[index],
                      // );
                    });
              } else if (snapshot.data.statusCode == 401){
                return new FlatButton(
                  child: new Text('click to signin'),
                  onPressed: () {
                    Navigator.push(
                        context,
                        new MaterialPageRoute<String>(
                          builder: (BuildContext context) => new SignIn(),
                          fullscreenDialog: true,
                        ));
                  },
                );
              }
          }
        });
    }

**Comment by marscj** [comment]
@ianloic @paulcbetts @sgraham @sethladd @kevmoo 


futureBuilder(){
      if (retry > 0)
      return new FutureBuilder<model.Result>(
        future: loader.orderStaff(),
        builder: (BuildContext context, AsyncSnapshot<model.Result> snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.none:
            case ConnectionState.waiting:
              return new CircularProgressIndicator();
            default:
              if (snapshot.hasError) {
                return new OffLineWidget(onTap: () {
                  setState((){
                    retry ++;
                  });
                });
              } else if (snapshot.data.statusCode == 200) {
                return new ListView.builder(
                    padding: kMaterialListPadding,
                    key: const ValueKey<String>('task-list'),
                    itemCount: snapshot.data.data.orders.length,
                    itemBuilder: (BuildContext context, int index) {
                      return new Text('abc');
                      // return new TaskRow(
                      //   task: taskPage.tasks[index],
                      // );
                    });
              } else if (snapshot.data.statusCode == 401){
                return new FlatButton(
                  child: new Text('click to signin'),
                  onPressed: () {
                    Navigator.push(
                        context,
                        new MaterialPageRoute<String>(
                          builder: (BuildContext context) => new SignIn(),
                          fullscreenDialog: true,
                        ));
                  },
                );
              }
          }
        });
    }

**Comment by zoechi** [comment]
Can you please edit your posts and wrap code and log output in ``` to make it readable?

**Comment by blackwolf12333** [comment]
I am actually experiencing a similar problem with StreamBuilder. When the login is successful I would like to push the HomePage to the Navigator. However when I do that I get the following error:

    I/flutter ( 3238): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY 
    ╞═══════════════════════════════════════════════════════════
    I/flutter ( 3238): The following assertion was thrown building StreamBuilder<AuthState>(dirty, state:
    I/flutter ( 3238): _StreamBuilderBaseState<AuthState, AsyncSnapshot<AuthState>>#0011f):
    I/flutter ( 3238): setState() or markNeedsBuild() called during build.
    I/flutter ( 3238): This Overlay widget cannot be marked as needing to build because the framework is already in the
    I/flutter ( 3238): process of building widgets. A widget can be marked as needing to be built during the build phase
    I/flutter ( 3238): only if one of its ancestors is currently building. This exception is allowed because the framework
    I/flutter ( 3238): builds parent widgets before children, which means a dirty descendant will always be built.
    I/flutter ( 3238): Otherwise, the framework might not visit this widget during this build phase.
    I/flutter ( 3238): The widget on which setState() or markNeedsBuild() was called was:
    I/flutter ( 3238):   Overlay-[LabeledGlobalKey<OverlayState>#0eca6](state: OverlayState#a40b3(entries:
    I/flutter ( 3238):   [OverlayEntry#a88f9(opaque: false; maintainState: false), OverlayEntry#4e90c(opaque: false;
    I/flutter ( 3238):   maintainState: true), OverlayEntry#d14d2(opaque: false; maintainState: false),
    I/flutter ( 3238):   OverlayEntry#49f80(opaque: false; maintainState: true)]))
    I/flutter ( 3238): The widget which was currently being built when the offending call was made was:
    I/flutter ( 3238):   StreamBuilder<AuthState>(dirty, state: _StreamBuilderBaseState<AuthState,
    I/flutter ( 3238):   AsyncSnapshot<AuthState>>#0011f)
    I/flutter ( 3238): When the exception was thrown, this was the stack:
    I/flutter ( 3238): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3436:11)
    I/flutter ( 3238): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3462:6)
    I/flutter ( 3238): #2      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
    I/flutter ( 3238): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
    I/flutter ( 3238): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:40:24)
    I/flutter ( 3238): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:182:11)
    I/flutter ( 3238): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:740:11)
    I/flutter ( 3238): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1443:11)
    I/flutter ( 3238): #8      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:1360:12)
    I/flutter ( 3238): #9      _BootPageState.build.<anonymous closure> (file:///home/peter/development/uscki/wilson/lib/main.dart:71:39)
    I/flutter ( 3238): #10     StreamBuilder.build (package:flutter/src/widgets/async.dart:408:74)
    I/flutter ( 3238): #11     _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
    I/flutter ( 3238): #12     StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
    I/flutter ( 3238): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
    I/flutter ( 3238): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
    I/flutter ( 3238): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
    I/flutter ( 3238): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
    I/flutter ( 3238): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
    I/flutter ( 3238): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
    I/flutter ( 3238): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    I/flutter ( 3238): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
    I/flutter ( 3238): #21     _invoke (dart:ui/hooks.dart:120:13)
    I/flutter ( 3238): #22     _drawFrame (dart:ui/hooks.dart:109:3)
    I/flutter ( 3238): ════════════════════════════════════════════════════════════════════════════════════════════════════

Which is very similar to the original error reported in this issue.

**Comment by zoechi** [comment]
@blackwolf12333 please add the output of `flutter doctor -v` and the code that allows to reproduce.

**Comment by duhber** [comment]
Im also experiencing the same problem. Please help


  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(
            'Sign up',
            style: Theme.of(context).primaryTextTheme.title,
          ),
        ),
        body:
            StreamBuilder<UserAccount>(
                stream: _bloc.formResponse,
                builder: (context,snapshot){
                  print(_isMobileExist);
                  if(snapshot.hasData){
                      Navigator.pushNamed(context, "/");
                  }
                  return _buildSignUpPage();
                }
            )
    );
  }

**Comment by blackwolf12333** [comment]
@zoechi I'll try to create a test case and send the output of flutter doctor after work.

**Comment by zoechi** [comment]
@Hixie

**Comment by blackwolf12333** [comment]
@zoechi @Hixie Hereby the output of `flutter doctor -v`. And I created a repository [here](https://github.com/blackwolf12333/flutter_crash_demo) that has a very simple test case.

      [+13 ms] [/home/peter/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
      [  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
      [        ] origin/alpha
      [        ] [/home/peter/development/flutter/] git rev-parse --abbrev-ref HEAD
      [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
      [        ] alpha
      [        ] [/home/peter/development/flutter/] git ls-remote --get-url origin
      [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
      [        ] https://github.com/flutter/flutter.git
      [        ] [/home/peter/development/flutter/] git log -n 1 --pretty=format:%H
      [   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
      [        ] 553fc4264e5c3bd85531e73fb7d89bdfab0fa3ec
      [        ] [/home/peter/development/flutter/] git log -n 1 --pretty=format:%ar
      [   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
      [        ] 4 months ago
      [        ] [/home/peter/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
      [  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
      [        ] v0.0.21-1-g553fc4264
      [ +564 ms] [✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
      [   +1 ms]     • Flutter version 0.0.22-pre.1 at /home/peter/development/flutter
      [        ]     • Framework revision 553fc4264e (4 months ago), 2018-03-01 09:30:25 -0800
      [        ]     • Engine revision 6921873c71
      [        ]     • Tools Dart version 2.0.0-dev.16.0
      [        ]     • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a
      [ +459 ms] java -version
      [  +52 ms] [✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
      [        ]     • Android SDK at /home/peter/Android/Sdk
      [        ]     • Android NDK location not configured (optional; useful for native profiling support)
      [        ]     • Platform android-27, build-tools 26.0.2
      [        ]     • Java binary at: /opt/android-studio/jre/bin/java
      [        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
      [   +1 ms] [✓] Android Studio (version 3.1)
      [        ]     • Android Studio at /opt/android-studio
      [        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
      [  +78 ms] [✓] IntelliJ IDEA Community Edition (version 2018.1)
      [        ]     • Flutter plugin version 26.0.2
      [        ]     • Dart plugin version 181.4892.1
      [   +5 ms] /home/peter/Android/Sdk/platform-tools/adb devices -l
      [   +4 ms] Exit code 0 from: /home/peter/Android/Sdk/platform-tools/adb devices -l
      [        ] List of devices attached
                 emulator-5554          device product:sdk_google_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:1
      [  +14 ms] /home/peter/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
      [  +36 ms] ro.hardware = ranchu
      [   +3 ms] [✓] Connected devices
      [        ]     • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)
      [  +35 ms] "flutter doctor" took 1,181ms.
      [  +70 ms] ensureAnalyticsSent: 67ms
      [   +1 ms] exiting with code 0

**Comment by devxpy** [comment]
Arrived to the same problem here at #19194

**Comment by Hixie** [comment]
The FutureBuilder's builder should only build widgets, it shouldn't have any logic. Builders can get called arbitrarily.
The logic should be added in the place that triggered the future (e.g. your `initState`), using the regular future logic (`.then`, `await`, or whatever you want to use).

**Comment by devxpy** [comment]
If you go over to #19194, you'll see that i tried that as well :)

**Comment by devxpy** [comment]
Specifically, [this](https://github.com/flutter/flutter/issues/19194#issuecomment-403975321) comment.
I can provide a full test case if you want.

**Comment by blackwolf12333** [comment]
@Hixie Thanks for the response, I expected it would be something like this. Maybe include that this also applies to StreamBuilder. Or probably for any kind of builder right?

**Comment by Hixie** [comment]
Yeah, we should definitely document this on FutureBuilder and StreamBuilder in particular, since people hit it for those a lot, as well as on StatelessWidget.build and State.build.

**Comment by Hixie** [comment]
@devxpy Please file a new issue for the case where you're getting this in initState (including the stack trace).

**Comment by devxpy** [comment]
Sure

**Comment by devxpy** [comment]
#19330

**Comment by devxpy** [comment]
Should I also create one for `didChangeDependencies()` too?

**Comment by Hixie** [comment]
Sure.

**Comment by Hixie** [comment]
Oh, actually, I see. I didn't realise that you were calling the push synchronously from initState or didChangeDependencies. Yeah, those will have the same problem as here.

**Comment by maqoo** [comment]
I don't know if this is a viable or safe aproach but we used smth like this:

```
Future<void> navigateSomewhere(BuildContext context) async {
    await Future<void>.microtask(() {
      Navigator.pushReplacement(
          context, MaterialPageRoute<PhoneVerificationPage>(
          builder: (BuildContext context) {
            return PhoneVerificationPage.build();
          }));
    });
}
```

**Comment by kwent** [comment]
Logic should be added this way:

```dart

  @override
  void initState() {
    super.initState();
    _bloc = AuthBloc();
    _listen();
  }

  void _listen() {
    _bloc.signedIn.listen((value) {
      if (value is StateSuccess) {
        Navigator.pushReplacementNamed(context, Routes.home);
      }
    });
  }

  @override
  void dispose() {
    _bloc.dispose();
    super.dispose();
  }
```

**Comment by thetrav** [comment]
@kwent it's not clear in your snippet that context is available from the context of 
```
void _listen()
```

**Comment by InMatrix** [comment]
I don't believe https://github.com/flutter/flutter/pull/58213 fully fixes this issue, specifically the API doc still offers no advice on "where to put that logic instead." There are a lot of dubious workarounds in https://github.com/flutter/flutter/issues/19194. It seems to be important to provide a verified solution in the official docs.

**Comment by InMatrix** [comment]
By the way "setState() or markNeedsBuild() called during build" is still one of the most common errors according to our logs, so people are probably still running into this.

**Comment by KaisLeung** [comment]
You can use WidgetsBinding.instance.addPostFrameCallback，just like this：
WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
        setState(() {

        });
});

**Comment by davemg3** [comment]
The above case use `FutureBuilder.then( )...` to call `Navigator.pushNamed`

But the documentation still doesnt clarify how to proceed if we need to call` Navigator.pushNamed` inside `FutureBuilder` body. For example if we need to call Navigate from a click on widget button created inside FutureBuilder and based on some results received from this `FutureBuilder` snapshot.

**Comment by Chakib-Temal** [comment]
> Arrived to the same problem here at #19194.
> 
> I do have a hacky solution that seems to work.
> 
> Instead of `FutureBuilder`, just put the async call in `build()`
> 
> `checkIfAuthenticated()` is a future that takes some time..
> 
> ```dart
> class LandingPage extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
> 
>     checkIfAuthenticated().then((success) {
>       if (success) {
>         Navigator.pushReplacementNamed(context, '/home');
>       } else {
>         Navigator.pushReplacementNamed(context, '/login');
>       }
>     });
> 
>     return Center(
>       child: CircularProgressIndicator(),
>     );
>   }
> }
> ```
> 
> It produces the desired result, but as @zoechi suggested,
> 
> > build() can be called more than once.
> 
> So it might cause problems.

Best Solution

**Comment by nancyades** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This Consumer widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Consumer
The widget which was currently being built when the offending call was made was:
  Consumer
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4424:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4439:6)
#2      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:451:20)
#3      _rootRunBinary (dart:async/zone.dart:1450:47)
#4      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#5      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
#6      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/provider_base.dart:534:24)
#7      ResultData.map (package:riverpod/src/framework/provider_base.dart:1085:16)
#8      ProviderElementBase._notifyListeners (package:riverpod/src/framework/provider_base.dart:531:14)
#9      ProviderElementBase._performBuild.<anonymous closure> (package:riverpod/src/framework/provider_base.dart:450:25)
#10     ResultData.map (package:riverpod/src/framework/provider_base.dart:1085:16)
#11     ProviderElementBase._performBuild (package:riverpod/src/framework/provider_base.dart:449:15)
#12     ProviderElementBase.flush (package:riverpod/src/framework/provider_base.dart:417:7)
#13     ProviderContainer.read (package:riverpod/src/framework/container.dart:295:13)
#14     ProviderContainer.refresh (package:riverpod/src/framework/container.dart:349:12)
#15     ConsumerStatefulElement.refresh (package:flutter_riverpod/src/consumer.dart:492:59)
#16     _TestTypeValueState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:production_testing/screen/tests/testContent.dart:350:35)
#17     AsyncValueX.when.<anonymous closure> (package:riverpod/src/common.dart:264:24)
#18     AsyncData._map (package:riverpod/src/common.dart:161:16)
#19     AsyncValueX.when (package:riverpod/src/common.dart:263:12)
#20     _TestTypeValueState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:production_testing/screen/tests/testContent.dart:347:60)
#21     Consumer.build (package:flutter_riverpod/src/consumer.dart:269:20)
#22     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:371:19)
#23     StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#24     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:431:20)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#28     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#40     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#41     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#42     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#43     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#44     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#45     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#46     _rootRun (dart:async/zone.dart:1426:13)
#47     _CustomZone.run (dart:async/zone.dart:1328:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#49     _invoke (dart:ui/hooks.dart:151:10)
#50     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#51     _drawFrame (dart:ui/hooks.dart:115:31)
