### ISSUE TITLE
error when running flutter doctor 

### ISSUE THREAD

**Issue by RofiAlfarid** [flutter/flutter#16214]
i want installing flutter at the first time but when run flutter doctor i got this log
all the path git, flutter and sndroid_home are already checked, i'm new here 
it says cannot find specified file sdkmanager.bat but i check iin that dir and that file are exist. i don't know what's going on.
[flutter_07.log](https://github.com/flutter/flutter/files/1874542/flutter_07.log)

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter analyze -v

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: E:\Rofi\Else\Flutter\flutter\bin\cache\dart-sdk\bin\dartanalyzer.BAT C:\Users\Lawencon

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133)
<asynchronous suspension>
#1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:98)
<asynchronous suspension>
#2      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:70)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      new Future.sync (dart:async/future.dart:222)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#11     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#20     main (file:///E:/Rofi/Else/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: ProcessException: The system cannot find the file specified.

  Command: E:\SDK\tools\bin\sdkmanager.BAT --licenses

#0      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:188)
<asynchronous suspension>
#1      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:149)
<asynchronous suspension>
#2      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#3      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#4      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:237)
#5      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#6      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#11     _doctorText (package:flutter_tools/runner.dart:237)
<asynchronous suspension>
#12     _createLocalCrashReport (package:flutter_tools/runner.dart:212)
<asynchronous suspension>
#13     _handleToolError (package:flutter_tools/runner.dart:167)
<asynchronous suspension>
#14     run.<anonymous closure> (package:flutter_tools/runner.dart:94)
<asynchronous suspension>
#15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#21     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#23     main (file:///E:/Rofi/Else/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by tvolkert** [comment]
I wonder if it has something to do with it being on a different drive...?

Can you run `flutter analyze -v --bug-report` and attach the resulting bug report ZIP file here?

**Comment by zoechi** [comment]
Is there something special with the `E:` drive?

**Comment by zoechi** [comment]
Is this still an issue?
