### ISSUE TITLE
google_sign_in firebase_auth PlatformException Error Code: 2

### ISSUE THREAD

**Issue by tabuz** [flutter/flutter#16239]
I'm simply trying to use google_sign_in plugin to authorize myself on firebase via firebase_auth with function shown under. On the other hand I'm able to create user via email and password in my firebase project just this bloody google sign in is misbehaving. 

## Steps to Reproduce
```dart
Future<String> signInWithGoogle () async {

    try {
      GoogleSignIn googleSignIn = new GoogleSignIn();
      GoogleSignInAccount googleUser = await googleSignIn.signIn();
      GoogleSignInAuthentication googleAuth = await googleUser.authentication;

      FirebaseAuth firebaseAuth = FirebaseAuth.instance;
      print(googleAuth.accessToken);
      print(googleAuth.idToken);

      await firebaseAuth.signInWithGoogle(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      final FirebaseUser user = firebaseAuth.currentUser;
      print(user.displayName);

      return('signInWithGoogle succeeded ');
    } catch (e) {
      print(e);
    }
```

### Log from Android studio terminal try/catch
```
/flutter (25608): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25608): type '_AssertionError' is not a subtype of type 'PlatformException' of 'onError' where
E/flutter (25608):   _AssertionError is from dart:core
E/flutter (25608):   PlatformException is from package:flutter/src/services/message_codec.dart
E/flutter (25608): 
E/flutter (25608): #0      LoginScreenState._loginWithGoogle.<anonymous closure> (package:flutter_flat_app/screens/Login/index.dart:65:38)
E/flutter (25608): #1      _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter (25608): #2      _FutureListener.handleError (dart:async/future_impl.dart:144)
E/flutter (25608): #3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #4      _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #5      _Future._complete (dart:async/future_impl.dart:467)
E/flutter (25608): #6      _SyncCompleter.complete (dart:async/future_impl.dart:51)
E/flutter (25608): #7      _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
E/flutter (25608): #8      UserAuth.signInWithGoogle (package:flutter_flat_app/services/authentication.dart:59:3)
E/flutter (25608): #9      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:84)
E/flutter (25608): #10     _RootZone.runBinary (dart:async/zone.dart:1386)
E/flutter (25608): #11     _FutureListener.handleError (dart:async/future_impl.dart:141)
E/flutter (25608): #12     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #13     _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #14     _Future._completeError (dart:async/future_impl.dart:485)
E/flutter (25608): #15     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter (25608): #16     _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (25608): #17     FirebaseAuth.signInWithGoogle (package:firebase_auth/firebase_auth.dart)
E/flutter (25608): #18     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:84)
E/flutter (25608): #19     _RootZone.runBinary (dart:async/zone.dart:1386)
E/flutter (25608): #20     _FutureListener.handleError (dart:async/future_impl.dart:141)
E/flutter (25608): #21     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #22     _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #23     _Future._completeError (dart:async/future_impl.dart:485)
E/flutter (25608): #24     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter (25608): #25     _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (25608): #26     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (25608): #27     _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter (25608): #28     _FutureListener.handleValue (dart:async/future_impl.dart:129)
E/flutter (25608): #29     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
E/flutter (25608): #30     _Future._propagateToListeners (dart:async/future_impl.dart:662)
E/flutter (25608): #31     _Future._completeWithValue (dart:async/future_impl.dart:477)
E/flutter (25608): #32     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
E/flutter (25608): #33     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (25608): #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

### Print from 'catchError'  method 
```
  void _loginWithGoogle() {
    userAuth.signInWithGoogle().then((onValue) {
      if (onValue == "signInWithGoogle succeeded ")
        Navigator.pushNamed(context, "/HomePage");
      else
        showInSnackBar(onValue);
    }).catchError((PlatformException onError) {
      print(onError.toString());
      showInSnackBar(onError.message);
    });
  }


flutter (26060): PlatformException(exception, An internal error has occurred. [ Error code:2 ], null)
```

### Flutter analyze
```
Analyzing /home/tabuz/projects/flat-app...
  error • Target of URI doesn't exist: 'package:flutter_flat_app/Screens/Login/index.dart' at test/widget_test.dart:8:8 • uri_does_not_exist
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'LoginScreen' at test/widget_test.dart:15:33 • undefined_class
  warning • This function declares a return type of 'Future<String>', but doesn't end with a return statement at lib/services/authentication.dart:34:3 • missing_return
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/Buttons/roundedButton.dart:3:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/Buttons/textButton.dart:3:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/TextFields/inputField.dart:3:7 • must_be_immutable
7 issues found.
(Ran in 7.9s)
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale pl_PL.UTF-8)
    • Flutter version 0.2.3 at /home/tabuz/software/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/tabuz/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/tabuz/software/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/tabuz/software/android-studio
    • Java version openjdk version "1.8.0_152-release"

[✓] Connected devices (1 available)
    • Pixel • FA69L0304820 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
### Dependencies

```
  image_picker: 0.1.1                                             # new
  google_sign_in: 0.3.1                                           # new
  firebase_analytics: 0.0.4                                       # new
  firebase_auth: 0.1.1                                            # new
  firebase_database: 0.0.12                                       # new
  firebase_storage: 0.0.5                                         # new
```

**Comment by tabuz** [comment]
Hi guys,

I'm still fighting with firebase-auth and google_sign_in. I moved a little bit forward and found this log in `./adb logcat -- see` 

```
04-11 20:22:46.158  2438  8049 E Volley  : [454] BasicNetwork.performRequest: Unexpected response code 503 for https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?alt=proto&key=[KEY]
04-11 20:22:46.168  2438 26403 I AuthChimeraService: Error description received from server: Error code: 2
04-11 20:22:46.171  2438 26403 W FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess starts
04-11 20:22:46.171  2438 26403 W FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess ends
04-11 20:22:46.175 29546 29571 E flutter : [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
04-11 20:22:46.175 29546 29571 E flutter : PlatformException(exception, An internal error has occurred. [ Error code:2 ], null)
04-11 20:22:46.175 29546 29571 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:502)
04-11 20:22:46.175 29546 29571 E flutter : #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)
04-11 20:22:46.175 29546 29571 E flutter : <asynchronous suspension>
04-11 20:22:46.175 29546 29571 E flutter : #2      FirebaseAuth.signInWithGoogle (package:firebase_auth/firebase_auth.dart:137)
04-11 20:22:46.175 29546 29571 E flutter : <asynchronous suspension>
04-11 20:22:46.175 29546 29571 E flutter : #3      RecordScreenState._postOffer (package:flutter_flat_app/screens/Record/index.dart:127)
04-11 20:22:46.175 29546 29571 E flutter : <asynchronous suspension>
04-11 20:22:46.175 29546 29571 E flutter : #4      RecordScreenState._prepFilePath (package:flutter_flat_app/screens/Record/index.dart:118)
04-11 20:22:46.175 29546 29571 E flutter : <asynchronous suspension>
04-11 20:22:46.175 29546 29571 E flutter : #5      RecordScreenState.build.<anonymous closure> (package:flutter_flat_app/screens/Record/index.dart:208)
04-11 20:22:46.175 29546 29571 E flutter : #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478)
04-11 20:22:46.175 29546 29571 E flutter : #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530)
04-11 20:22:46.175 29546 29571 E flutter : #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102)
04-11 20:22:46.175 29546 29571 E flutter : #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161)
04-11 20:22:46.175 29546 29571 E flutter : #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94)
04-11 20:22:46.175 29546 29571 E flutter : #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315)
04-11 20:22:46.175 29546 29571 E flutter : #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
04-11 20:22:46.175 29546 29571 E flutter : #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
04-11 20:22:46.175 29546 29571 E flutter : #14     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143)
04-11 20:22:46.175 29546 29571 E flutter : #15     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121)
04-11 20:22:46.175 29546 29571 E flutter : #16     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101)
04-11 20:22:46.175 29546 29571 E flutter : #17     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64)
04-11 20:22:46.175 29546 29571 E flutter : #18     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48)
04-11 20:22:46.175 29546 29571 E flutter : #19     _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
04-11 20:22:46.175 29546 29571 E flutter : #20     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:91)

```

**Comment by dynac01** [comment]
I'm having the same problem, did you finally get it fixed?

**Comment by remosingh** [comment]
I also have this issue...however, only when I try to run Android release version. Android in debug mode and iOS in any mode work just fine.

**Comment by kroikie** [comment]
@tabuz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/864. Any further collaboration will be done there.

**Comment by TreeStrepek** [comment]
was there a solution?
