### ISSUE TITLE
After updating Flutter seeing crash on compilation

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#16242]
```
Flutter (Channel master, v0.2.5-pre.115, on Microsoft Windows [Version 10.0.16299.334], 
locale en-US)
```

After updating flutter to master I'm seeing the issue as logged in #15206. Not sure if it is a Dart 2 related issue. Tried running `flutter clean` but that didn't help.

Right now I don't have much in the application, however if I do:

```dart
@override
Widget build(BuildContext context) => StoreProvider(
  ...
);
```

It will crash. If I do:

```dart
@override
Widget build(BuildContext context) => new StoreProvider(
  ...
);
```

it will work. The crash details are below:

```
compiler message: Unhandled exception: Crash when compiling <folder omited by me>/main.dart, at character offset 659: lib/main.dart: Internal problem: Unhandled this in defaultTreeNode. 
#0 internalProblem (package:front_end/src/fasta/problems.dart:30) 
#1 unhandled (package:front_end/src/fasta/problems.dart:43) 
#2 ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112) 
#3 TreeVisitor.defaultExpression (package:kernel/visitor.dart:140) 
#4 TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171) 
#5 ThisExpression.accept (package:kernel/ast.dart:3341) 
#6 ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287) 
#7 PropertyGet.accept (package:kernel/ast.dart:2242) 
#8 ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175) 
#9 ConstructorInvocation.accept (package:kernel/ast.dart:2983) 
#10 ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99) 
#11 evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466) 
#12 BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710) 
#13 BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697) 
#14 DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684) 
#15 DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#16 DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565) 
#17 DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530) 
#18 Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796) 
#19 Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670) 
#20 Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467) 
#21 Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#22 Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659) 
#23 Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535) 
#24 Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451) 
#25 Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335) 
#26 SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198) <asynchronous suspension> 
#27 Loader.buildBodies (package:front_end/src/fasta/loader.dart:157) <asynchronous suspension> 
#28 KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292) <asynchronous suspension> 
#29 IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140) <asynchronous suspension> 
#30 CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105) 
#31 _rootRun (dart:async/zone.dart:1126) 
#32 _CustomZone.run (dart:async/zone.dart:1023) 
#33 runZoned (dart:async/zone.dart:1501) 
#34 CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105) 
#35 IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61) <asynchronous suspension> 
#36 IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33) <asynchronous suspension> 
#37 FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254) 
#38 new Future.<anonymous closure> (dart:async/future.dart:174) 
#39 _rootRun (dart:async/zone.dart:1122) 
#40 _CustomZone.run (dart:async/zone.dart:1023) 
#41 _CustomZone.runGuarded (dart:async/zone.dart:925) 
#42 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965) 
#43 _rootRun (dart:async/zone.dart:1126) 
#44 _CustomZone.run (dart:async/zone.dart:1023)
#45 _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#46 Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#47 _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#48 _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#49 _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by andreidiaconu** [comment]
Same here. Your hint helped me get my app running again. I had a 
```
alignment: Alignment( x, y)
```
for a Transform widget. After adding the `new` keyword it started compiling again.

**Comment by kmillikin** [comment]
Thanks for the report @lukef and @andreidiaconu.  This is an unfortunate bug in Dart's implementation of implicit `new` and `const`, tracked here: https://github.com/dart-lang/sdk/issues/32737

**Comment by tvolkert** [comment]
Closing as dup of https://github.com/dart-lang/sdk/issues/32737
