### ISSUE TITLE
'flutter channel master' followed by 'flutter upgrade' -> crash report

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter#16303]
## steps to reproduce

I was on the `dev` branch and then did a `flutter channel master` followed by `flutter upgrade` when the crash happened.

## command

flutter upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/bjorn/bin/flutter/bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:69)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:212)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:77)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#16     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#17     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#18     _rootRun (dart:async/zone.dart:1120)
#19     _CustomZone.run (dart:async/zone.dart:1001)
#20     runZoned (dart:async/zone.dart:1467)
#21     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#22     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#23     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#24     main (file:///Users/bjorn/bin/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/bjorn/bin/flutter/bin/cache/artifacts/engine/darwin-x64/dart-sdk/bin/dart.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      Cache.engineDartVersion (package:flutter_tools/src/cache.dart:139)
#3      FlutterVersion.engineDartVersion (package:flutter_tools/src/version.dart:69)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:212)
<asynchronous suspension>
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:106)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:236)
#7      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#8      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     runZoned (dart:async/zone.dart:1467)
#12     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#13     _doctorText (package:flutter_tools/runner.dart:236)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:211)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:93)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:44)
<asynchronous suspension>
#25     main (file:///Users/bjorn/bin/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by tvolkert** [comment]
What's the output from `git rev-parse HEAD`?

Also, can you try `rm -rf <flutter_root>/bin/cache` to see if that resolves the problem?

**Comment by bjornbjorn** [comment]
The problem solved itself when I did a `flutter upgrade` a second time.

`git rev-parse HEAD` now says `5a58b36e36b8d7aace89d3950e6deb307956a6a0`

**Comment by tvolkert** [comment]
If you're on the `master` channel, you should be at a much more recent commit than 5a58b36...

**Comment by bjornbjorn** [comment]
Ah, yes sorry - I'm back on the beta now. Basically I switched from beta, to dev, to master when this crash happened. I got it working on master by doing `flutter upgrade` a second time. But have since gone back to `beta`. Just wanted to report this as that's what the log file told me to do :-)

**Comment by tvolkert** [comment]
Sounds good.
