### ISSUE TITLE
Firestore Plugin Bugs

### ISSUE THREAD

**Issue by putraxor** [flutter/flutter#16302]
I can't trace which part of dart code still using snaphost. There is no code calls the `exist` object from firestore snaphost.
```
D/AndroidRuntime(16798): Shutting down VM
E/AndroidRuntime(16798): FATAL EXCEPTION: main
E/AndroidRuntime(16798): Process: com.kodeversitas.criptomania, PID: 16798
E/AndroidRuntime(16798): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.firestore.DocumentSnapshot.exists()' on a null object reference
E/AndroidRuntime(16798): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:179)
E/AndroidRuntime(16798): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:168)
E/AndroidRuntime(16798): 	at com.google.firebase.firestore.DocumentReference.zza(Unknown Source)
E/AndroidRuntime(16798): 	at com.google.firebase.firestore.zzd.onEvent(Unknown Source)
E/AndroidRuntime(16798): 	at com.google.android.gms.internal.zzevc.zza(Unknown Source)
E/AndroidRuntime(16798): 	at com.google.android.gms.internal.zzevd.run(Unknown Source)
E/AndroidRuntime(16798): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(16798): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16798): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(16798): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime(16798): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16798): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(16798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I/Process (16798): Sending signal. PID: 16798 SIG: 9
```

**Comment by putraxor** [comment]
Fixed in version 0.2.12
