### ISSUE TITLE
Dart 2 - LicensePage in AboutDialog doesn't load licenses

### ISSUE THREAD

**Issue by joernahrens** [flutter/flutter#16305]
## Steps to Reproduce

1. Use Dart 2
2. Use `AboutDialog`
3. Open Licenses

I tested with flutter `beta` and `master` channel.

## Logs

This is what I see in logs:

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
type '_GeneratedStreamImpl<LicenseEntry>' is not a subtype of type 'LicenseEntry' of 'event' where
  _GeneratedStreamImpl is from dart:async
  LicenseEntry is from package:flutter/src/foundation/licenses.dart
  LicenseEntry is from package:flutter/src/foundation/licenses.dart

#0      _AsyncStarStreamController.add (dart:async/async_patch.dart)
#1      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding._addLicenses (package:flutter/src/services/binding.dart:68:5)
<asynchronous suspension>
#2      LicenseRegistry.licenses (package:flutter/src/foundation/licenses.dart:305:23)
<asynchronous suspension>
#3      _LicensePageState._initLicenses (package:flutter/src/material/about.dart:381:56)
<asynchronous suspension>
#4      _LicensePageState.initState (package:flutter/src/material/about.dart:372:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
```

## Flutter Doctor

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v0.2.2-pre.37, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.2-pre.37 at /Users/joern/repo/flutter
    • Framework revision d28e9aa5c9 (3 weeks ago), 2018-03-13 09:41:49 -0700
    • Engine revision b6df7a6374
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/joern/Library/Android/sdk
    • Android NDK at /Users/joern/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/joern/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.0.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by mtthsfrdrch** [comment]
reproducible in Flutter Gallery when running with `--preview-dart-2`

**Comment by bjornbjorn** [comment]
Can confirm that we're getting this in our app after upgrading to Dart 2.

**Comment by realcarlos** [comment]
And if click 'view license button in non-English enviroment, and close the License view , environment change to English . FlutterErrorhooks.dart in _drawFrame
errorsetState() called after dispose(): _LicensePageState#bd3ea(lifecycle state: defunct, not mounted) This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree. This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

**Comment by Hixie** [comment]
@realcarlos Please file a separate bug for that issue.

**Comment by Hixie** [comment]
@joernahrens do you still see this?

**Comment by Hixie** [comment]
I've marked this customer blocker because if this is still a problem it will probably block everyone.

**Comment by goderbauer** [comment]
This does not reproduce on a release build of the gallery on iOS.

**Comment by joernahrens** [comment]
@Hixie @goderbauer 

Just tested and I think this is fixed. `doctor`s output:

```
$ flutter doctor                                                                                                                                                 [8:51:17]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```
