### ISSUE TITLE
Issue with showDatePicker and locale

### ISSUE THREAD

**Issue by asierf** [flutter/flutter#16304]
## Steps to Reproduce

I've tried to open a DatePicker with differents Locale instances but is not working using eu_ES.

```dart
showDatePicker(
  context: context, 
  initialDate: new DateTime.now(), 
  firstDate: new DateTime(1900), 
  lastDate: new DateTime(2019), 
  locale: const Locale('eu', 'ES'))
.then((date){  });
```

## Logs
```
I/flutter ( 7859): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7859): The following NoSuchMethodError was thrown building Directionality(textDirection: ltr):
I/flutter ( 7859): The method 'formatFullDate' was called on null.
I/flutter ( 7859): Receiver: null
I/flutter ( 7859): Tried calling: formatFullDate(Instance of 'DateTime')
I/flutter ( 7859):
I/flutter ( 7859): When the exception was thrown, this was the stack:
I/flutter ( 7859): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter ( 7859): #1      _DatePickerDialogState.didChangeDependencies (package:flutter/src/material/date_picker.dart:817)
I/flutter ( 7859): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
I/flutter ( 7859): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741)
I/flutter ( 7859): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
I/flutter ( 7859): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741)
I/flutter ( 7859): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741)
I/flutter ( 7859): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
I/flutter ( 7859): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741)
I/flutter ( 7859): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
I/flutter ( 7859): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
I/flutter ( 7859): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
I/flutter ( 7859): #100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4398)
I/flutter ( 7859): #101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726)
I/flutter ( 7859): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #103    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507)
I/flutter ( 7859): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 7859): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #111    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870)
I/flutter ( 7859): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 7859): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760)
I/flutter ( 7859): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 7859): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618)
I/flutter ( 7859): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2682)
I/flutter ( 7859): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
I/flutter ( 7859): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
I/flutter ( 7859): #125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225)
I/flutter ( 7859): #126    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621)
I/flutter ( 7859): #127    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter ( 7859): #128    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter ( 7859): #129    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter ( 7859): #130    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter ( 7859): #131    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter ( 7859): #132    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter ( 7859): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [VersiÃ³n 6.1.7601], locale es-ES)
    • Flutter version 0.1.5 at C:\Flutter\flutterSdk
    • Framework revision 3ea4d06340 (6 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at C:\Users\afernandezdeaguirre\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] VS Code (version 1.22.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • SM J710F • 52037e16e2cf3489 • android-arm • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by HansMuller** [comment]
We don't provide support for Locale('eu', 'ES') yet, see https://docs.flutter.io/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

The fact that we're not reporting the failure as "no support for locale ..." is a bug, sorry about that.

cc @yjbanov

**Comment by asierf** [comment]
Thanks, I will keep it in mind

**Comment by alexd1971** [comment]
Locale('ru') is provided, but I've got the same error

**Comment by HansMuller** [comment]
@alexd1971  - can you provide a small example that demos the problem you're seeing with the Russian locale?

**Comment by alexd1971** [comment]
I solved the problem. Everything works

**Comment by RiccardoMetaTime** [comment]
@alexd1971 i'm facing the same problem with Locale('de') How did you solve it?

**Comment by alexd1971** [comment]
@RiccardoMetaTime 
```dart
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'App Title',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
          const Locale('en', 'US'),
          const Locale('ru', 'RU'),
      ],
```

**Comment by andreyvgavrilov** [comment]
I'm trying to add Russian locale like this:
```

return new MaterialApp(
      title: '',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new OnboardingPage(title: 'Добро пожаловать'),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'US'),
        const Locale('ru', 'RU'),
      ],
    );

```

and get the following error logs:

```

I/flutter (10602): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10602): The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(411.4,
I/flutter (10602): 683.4), devicePixelRatio: 2.625, textScaleFactor: 1.0, padding: EdgeInsets(0.0, 24.0, 0.0, 0.0),
I/flutter (10602): viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false)):
I/flutter (10602): Unsupported operation: Cannot set value in unmodifiable Map
I/flutter (10602): 
I/flutter (10602): When the exception was thrown, this was the stack:
Syncing files to device Android SDK built for x86...
I/flutter (10602): #0      _ImmutableMap.[]= (dart:core/runtime/libimmutable_map.dart:76:5)
I/flutter (10602): #1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:34:19)
I/flutter (10602): #2      _loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:505:31)
I/flutter (10602): #3      _ImmutableMap.forEach (dart:core/runtime/libimmutable_map.dart:45:8)
I/flutter (10602): #4      _loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/material_localizations.dart:502:36)
I/flutter (10602): #5      new GlobalMaterialLocalizations (package:flutter_localizations/src/material_localizations.dart:81:5)
I/flutter (10602): #6      GlobalMaterialLocalizations.load (package:flutter_localizations/src/material_localizations.dart:429:61)
I/flutter (10602): #7      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:551:84)
I/flutter (10602): #8      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
I/flutter (10602): #9      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:504:62)
I/flutter (10602): #10     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:469:5)
I/flutter (10602): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
I/flutter (10602): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (10602): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (10602): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (10602): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (10602): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (10602): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (10602): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (10602): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (10602): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (10602): #72     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (10602): #73     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (10602): #74     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (10602): #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter (10602): #76     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (10602): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (10602): #78     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (10602): #79     main (file:///C:/Users/263/AndroidStudioProjects/smsfinance_app/lib/main.dart:7:16)
I/flutter (10602): #80     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (10602): #81     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (10602): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/        (10602): HostConnection::get() New Host Connection established 0x82fe8cc0, tid 10623
D/EGL_emulation(10602): eglMakeCurrent: 0xa3fb26a0: ver 3 0 (tinfo 0x85e3f770)

```

Can't find anything about this error in the context of Flutter.

**Comment by andreyvgavrilov** [comment]
Was able to fix it. The "initializeDateFormatting" function is only needed if "localizationsDelegates" aren't used. They can't work together.

**Comment by yjbanov** [comment]
@andreyvgavrilov, could please a file an issue for us to improve the error message?

**Comment by FViscardi** [comment]
> Was able to fix it. The "initializeDateFormatting" function is only needed if "localizationsDelegates" aren't used. They can't work together.

This fix worked for me as well. I had both "initializeDateFormatting" and "localizationsDelegates" active (it worked with Flutter-hot-reload, but not after restarting the app completely).

I was following these instructions: https://pub.dartlang.org/documentation/intl/latest/intl/DateFormat-class.html

**Comment by Canislupax** [comment]
how did you solve the problem? have the same problem with de -> ru and other languages with no problems

**Comment by ChangJoo-Park** [comment]
+1 here

**Comment by HansMuller** [comment]
The CupertinoTheme doesn't have localizations yet: https://github.com/flutter/flutter/issues/13452

**Comment by jhonnet31** [comment]
I just to have the same problem and the solution was edit the material_localizations.dart  and i got to show spanish text in datepicker

**Comment by leonetosoft** [comment]
The problem persists with me, I tried anyway, I need to update to pt_BR,

Can someone help me?

**Comment by TeuryBazzo** [comment]
@leonetosoft Igot used pt_BR, i fix this using this [link](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up)

**Comment by leonetosoft** [comment]
@TeuryBazzo fiz o procedimento conforme o link porém meu aplicativo da erro, pode postar o seu initApp aqui ? por gentileza

**Comment by TeuryBazzo** [comment]
`return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('pt'),
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Demo'),
    );`

and you need update your pubspec.yaml

`  flutter_localizations:
    sdk: flutter`

**Comment by mauricioluz** [comment]
I'm getting some problems when I try to use in Web. I'm receiving the error "Unable to find modules for some sources...' when I try to import flutter_localizations.

**Comment by TahaTesser** [comment]
Hi @asierf 
This isn't an issue with Flutter

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'US'),
        const Locale('ru', 'RU'),
      ],
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  DateTime selectedDate = DateTime.now();

  Future<Null> _selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
        context: context,
        locale: const Locale('eu', 'ES'),
        initialDate: selectedDate,
        firstDate: DateTime(2015, 8),
        lastDate: DateTime(2101));
    if (picked != null && picked != selectedDate)
      setState(() {
        selectedDate = picked;
      });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: RaisedButton(
              child: Text('Press'),
              onPressed: () async {
                _selectDate(context);
              })),
    );
  }
}
```

and make sure you've `flutter_localizations` in your `pubspec.yaml`
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by parasarorahere** [comment]
Every time I call its rebuild my Whole Widget. Can anyOne help me?

  Future<DateTime> showDateDialog(BuildContext context) async {
    
    return await showDatePicker(
      context: context,
      initialDate: DateTime.now();
      firstDate: new DateTime(1990);
      lastDate:  DateTime(2080);
    );

  }
