### ISSUE TITLE
devfs_test appears to be non-hermetic, which is causing flakiness

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16318]
```
03:41 +298 ~1: test/devfs_test.dart: devfs local add new package with double slashes in URI
03:41 +299 ~1: test/devfs_test.dart: devfs local add an asset bundle
03:41 +300 ~1: test/devfs_test.dart: devfs local add a file to the asset bundle - bundleDirty
03:41 +301 ~1: test/devfs_test.dart: devfs local add a file to the asset bundle
03:41 +302 ~1: test/devfs_test.dart: devfs local delete a file from the asset bundle
03:41 +303 ~1: test/devfs_test.dart: devfs local delete all files from the asset bundle
03:41 +304 ~1: test/devfs_test.dart: devfs local delete dev file system
03:41 +305 ~1: test/devfs_test.dart: devfs local (tearDownAll)
03:41 +305 ~1: test/devfs_test.dart: devfs remote (setUpAll)
03:41 +305 ~1: test/devfs_test.dart: devfs remote create dev file system
04:11 +305 ~1 -1: test/devfs_test.dart: devfs remote create dev file system [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
  
04:11 +305 ~1 -1: test/devfs_test.dart: devfs remote delete dev file system
Expected: empty
  Actual: ['writeFile test lib/foo.txt', 'writeFile test packages/somepkg/somefile.txt']
prior test timeout

#0      fail (package:test/src/frontend/expect.dart:165:30)
#1      _expect (package:test/src/frontend/expect.dart:159:3)
#2      expect (package:test/src/frontend/expect.dart:69:3)
#3      main.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/devfs_test.dart:337:7)
<asynchronous suspension>
#4      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:100:42)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      runZoned (dart:async/zone.dart:1501)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:88:30)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1490)
#14     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:86:18)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     testUsingContext.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:63:22)
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#26     runInContext (package:flutter_tools/src/context_runner.dart:41:24)
<asynchronous suspension>
#27     testUsingContext.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:62:11)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#29     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#34     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#35     _rootRun (dart:async/zone.dart:1126)
#36     _CustomZone.run (dart:async/zone.dart:1023)
#37     runZoned (dart:async/zone.dart:1501)
#38     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#39     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#40     new Future.<anonymous closure> (dart:async/future.dart:174)
#41     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#42     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#43     _rootRun (dart:async/zone.dart:1122)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.runGuarded (dart:async/zone.dart:925)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#47     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#48     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#49     _rootRun (dart:async/zone.dart:1126)
#50     _CustomZone.run (dart:async/zone.dart:1023)
#51     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#52     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#53     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#54     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

04:11 +305 ~1 -2: test/devfs_test.dart: devfs remote delete dev file system [E]
  Expected: empty
    Actual: ['writeFile test lib/foo.txt', 'writeFile test packages/somepkg/somefile.txt']
  prior test timeout
  
  package:test                                         expect
  test/devfs_test.dart 337:7                           main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           _Completer.completeError
  test/devfs_test.dart                                 main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  test/devfs_test.dart 336:57                          main.<fn>.<fn>
  test/src/context.dart 100:42                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  test/src/context.dart 93:32                          testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  test/src/context.dart 88:30                          testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                           runZoned
  test/src/context.dart 86:18                          testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  test/src/context.dart 63:22                          testUsingContext.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  package:flutter_tools/src/context_runner.dart 41:24  runInContext
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/context_runner.dart 40:10  runInContext
  test/src/context.dart 62:11                          testUsingContext.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  test/src/context.dart 61:30                          testUsingContext.<fn>
  
04:11 +305 ~1 -2: test/devfs_test.dart: devfs remote cleanup preexisting file system
Expected: equals ['create test'] unordered
  Actual: [
            'writeFile test lib/foo.txt',
            'writeFile test packages/somepkg/somefile.txt',
            'create test',
            'destroy test',
            'create test'
          ]
   Which: has too many elements (5 > 1)

#0      fail (package:test/src/frontend/expect.dart:165:30)
#1      _expect (package:test/src/frontend/expect.dart:159:3)
#2      expect (package:test/src/frontend/expect.dart:69:3)
#3      BasicMock.expectMessages (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/mocks.dart:384:5)
#4      main.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/devfs_test.dart:356:17)
<asynchronous suspension>
#5      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:100:42)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:88:30)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1490)
#15     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:86:18)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     testUsingContext.<anonymous closure>.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:63:22)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#27     runInContext (package:flutter_tools/src/context_runner.dart:41:24)
<asynchronous suspension>
#28     testUsingContext.<anonymous closure> (file:///b/build/slave/Mac/build/flutter/packages/flutter_tools/test/src/context.dart:62:11)
<asynchronous suspension>
#29     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#30     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#35     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#36     _rootRun (dart:async/zone.dart:1126)
#37     _CustomZone.run (dart:async/zone.dart:1023)
#38     runZoned (dart:async/zone.dart:1501)
#39     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#41     new Future.<anonymous closure> (dart:async/future.dart:174)
#42     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#43     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#44     _rootRun (dart:async/zone.dart:1122)
#45     _CustomZone.run (dart:async/zone.dart:1023)
#46     _CustomZone.runGuarded (dart:async/zone.dart:925)
#47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#48     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#49     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#50     _rootRun (dart:async/zone.dart:1126)
#51     _CustomZone.run (dart:async/zone.dart:1023)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#53     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#54     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#55     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

04:11 +305 ~1 -3: test/devfs_test.dart: devfs remote cleanup preexisting file system [E]
  Expected: equals ['create test'] unordered
    Actual: [
              'writeFile test lib/foo.txt',
              'writeFile test packages/somepkg/somefile.txt',
              'create test',
              'destroy test',
              'create test'
            ]
     Which: has too many elements (5 > 1)
  
  package:test                                         expect
  test/src/mocks.dart 384:5                            BasicMock.expectMessages
  test/devfs_test.dart 356:17                          main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           _Completer.completeError
  test/devfs_test.dart                                 main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           _asyncThenWrapperHelper
  test/devfs_test.dart 345:66                          main.<fn>.<fn>
  test/src/context.dart 100:42                         testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  test/src/context.dart 93:32                          testUsingContext.<fn>.<fn>.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  test/src/context.dart 88:30                          testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                           runZoned
  test/src/context.dart 86:18                          testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  test/src/context.dart 63:22                          testUsingContext.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 142:29   AppContext.run.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 142:16   AppContext.run.<fn>
  dart:async                                           runZoned
  package:flutter_tools/src/base/context.dart 141:18   AppContext.run
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/base/context.dart 134:12   AppContext.run
  package:flutter_tools/src/context_runner.dart 41:24  runInContext
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  package:flutter_tools/src/context_runner.dart 40:10  runInContext
  test/src/context.dart 62:11                          testUsingContext.<fn>
  ===== asynchronous gap ===========================
  dart:async                                           new Future.microtask
  test/src/context.dart 61:30                          testUsingContext.<fn>
  ```

**Comment by Hixie** [comment]
We haven't seen this in a long time...
