### ISSUE TITLE
Upon focusing an Input, keyboard slides up and immediately slides down

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1632]
@abarth 

Steps to reproduce:

1) Change ~flutter/examples/hello_world/lib/main.dart to read:

``` dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() => runApp(new HelloWorldApp());

class HelloWorldApp extends StatelessComponent {
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Hello World',
      routes: <String, RouteBuilder>{
        '/': (RouteArguments args) => new HelloWorldWidget()
      }
    );
  }
}

class HelloWorldWidget extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Material(
      key: new GlobalKey(),
      child: new Column(
        children: <Widget>[
          new Text('Hello, world!'),
          new Input(key: new GlobalKey()),
          new Input(key: new GlobalKey()),
        ]
      )
    );
  }
}
```

2) `$ flutter start`

Expected results:

Two basic text inputs

Actual results:

Upon a text input being focused, the keyboard shows and hides itself.  See http://54.91.18.239/issue.mp4 for an example

**Comment by abarth** [comment]
I added triple backticks to make GitHub format your code same correctly.

**Comment by eseidelGoogle** [comment]
You can add "dart" after your 3rd backtick if it can't figure out it's dart by itself:
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by abarth** [comment]
The problem is that you're creating new global keys every time you rebuild HelloWorldWidget.  When the view resizes, it rebuilds and the new global keys give the input widgets a new identity.  The new identity doesn't have focus and so the keyboard goes away.

**Comment by abarth** [comment]
The fix is to make HelloWorldWidget stateful and store the global keys as member variables of the State for that widget.

**Comment by tvolkert** [comment]
So here's what's strange... if I add an apk folder to the project and build a proper apk, then the issue doesn't happen.  If I do so, I also get layout errors with the above code and had to change HelloWorldWidget to:

```
class HelloWorldWidget extends StatelessComponent {
  Widget build(BuildContext context) {
    return new Center(
      child: new Material(
        key: new GlobalKey(),
        child: new Column(
          children: <Widget>[
            new Container(
              child: new Text('Hello, world!')
            ),
            new Container(
              child: new Input(
                key: new GlobalKey()
              )
            ),
            new Container(
              child: new Input(
                key: new GlobalKey()
              )
            ),
          ]
        )
      )
    );
  }
}
```

**Comment by abarth** [comment]
Containers that have a single child and no other parameters should be no-ops.  What are the layout errors?  One difference might be that you're running the APK without checked mode whereas when you run using `flutter start` you're running using checked mode.

**Comment by tvolkert** [comment]
```
I/flutter (16471): -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
I/flutter (16471): The following exception was raised during performLayout():
I/flutter (16471): 'packages/flutter/src/rendering/paragraph.dart': Failed assertion: line 86: 'constraints.isNormalized' is not true.
I/flutter (16471): The following RenderObject was being processed when the exception was fired:
I/flutter (16471): RenderFlex NEEDS-LAYOUT OVERFLOWING
I/flutter (16471): This RenderObject had the following owner:
I/flutter (16471): Column ← DefaultTextStyle ← InkFeatures-[GlobalKey ink renderer] ← NotificationListener<LayoutChangedNotification> ← DecoratedBox ← Container ← DecoratedBox ← Container ← AnimatedContainer ← Material-[GlobalKey 423747225] ← ⋯
I/flutter (16471): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (16471): RenderParagraph relayoutSubtreeRoot=up1
I/flutter (16471): RenderSemanticsGestureHandler relayoutSubtreeRoot=up1
I/flutter (16471):   RenderPointerListener relayoutSubtreeRoot=up2
I/flutter (16471):     RenderPadding relayoutSubtreeRoot=up3
I/flutter (16471):       RenderStack relayoutSubtreeRoot=up4
I/flutter (16471):         RenderPadding relayoutSubtreeRoot=up5
I/flutter (16471): RenderSemanticsGestureHandler relayoutSubtreeRoot=up1
I/flutter (16471):   RenderPointerListener relayoutSubtreeRoot=up2
I/flutter (16471):     RenderPadding relayoutSubtreeRoot=up3
I/flutter (16471):       RenderStack relayoutSubtreeRoot=up4
I/flutter (16471):         RenderPadding relayoutSubtreeRoot=up5
I/flutter (16471): This exception was thrown while debugDoesMeetConstraints() was running.
I/flutter (16471): debugDoesMeetConstraints() verifies that some invariants are not being
I/flutter (16471): violated. For example, it verifies that RenderBox objects are sized in
I/flutter (16471): a manner consistent with the constraints provided, and, in addition, that
I/flutter (16471): the getMinIntrinsicWidth(), getMaxIntrinsicWidth(), etc, functions all
I/flutter (16471): return consistent values within the same constraints.
I/flutter (16471): If you are not writing your own RenderObject subclass, then this is not
I/flutter (16471): your fault. Contact support: https://github.com/flutter/flutter/issues/new
I/flutter (16471): Stack trace:
I/flutter (16471): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter (16471): #1      RenderParagraph.getMaxIntrinsicHeight (packages/flutter/src/rendering/paragraph.dart:86)
I/flutter (16471): #2      RenderFlex._getIntrinsicSize (packages/flutter/src/rendering/flex.dart:234)
I/flutter (16471): #3      RenderFlex.getMinIntrinsicWidth (packages/flutter/src/rendering/flex.dart:286)
I/flutter (16471): #4      RenderBox.debugDoesMeetConstraints (packages/flutter/src/rendering/box.dart:551)
I/flutter (16471): #5      RenderBox.size= (packages/flutter/src/rendering/box.dart:450)
I/flutter (16471): #6      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:458)
I/flutter (16471): #7      RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #8      RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #9      RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #10     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #11     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #12     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #13     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #14     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #15     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #16     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #17     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #18     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #19     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #20     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #21     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #22     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:77)
I/flutter (16471): #23     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #24     RenderStackBase.performLayout (packages/flutter/src/rendering/stack.dart:326)
I/flutter (16471): #25     RenderObject.layout (packages/flutter/src/rendering/object.dart:1039)
I/flutter (16471): #26     RenderView.performLayout (packages/flutter/src/rendering/view.dart:97)
I/flutter (16471): #27     RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:945)
I/flutter (16471): #28     RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:923)
I/flutter (16471): #29     BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
I/flutter (16471): #30     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:92)
I/flutter (16471): #31     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:157)
I/flutter (16471): #32     runApp (packages/flutter/src/widgets/binding.dart:163)
I/flutter (16471): #33     main (/usr/local/google/home/tvolkert/project/flutter/flutter/examples/hello_world/lib/main.dart:8)
I/flutter (16471): ------------------------------------------------------------------------
```

**Comment by tvolkert** [comment]
Adding the Container instances was a red herring - it's the Center that fixes the above exception

**Comment by abarth** [comment]
```
I/flutter (16471): If you are not writing your own RenderObject subclass, then this is not
I/flutter (16471): your fault. Contact support: https://github.com/flutter/flutter/issues/new
```

@Hixie ^^^^

@tvolkert That exception is a separate issue from the focus issue.  We should probably file it separately.

**Comment by tvolkert** [comment]
Went to file the other issue and couldn't repro - will file if I see it agian.

Regarding this issue, why would flutter apk not exhibit the behavior of the input losing focus because it's got a new identity due to the newly instantiated global key?

**Comment by abarth** [comment]
I would see if `flutter start --no-checked` has the same behavior as `flutter apk`.  If so, then there's a difference in our error handling w.r.t. checked mode.  If not, I'd guess there was some sort of version confusion with the `flutter apk` experiment and I'd try to reproduce it carefully with positive and negative controls.

**Comment by tvolkert** [comment]
Yeah, same thing happens with ```flutter start --no-checked```.  Leaving this alone for now since I'm working on a different issue.

**Comment by Hixie** [comment]
If you sync to tip of tree and try again you should get better messages now.

**Comment by sethladd** [comment]
Not sure this is a text input issue?

Is there something actionable here?

**Comment by cbracken** [comment]
No longer repros -- adjusted for current widgets given that `Input` is gone.
