### ISSUE TITLE
"flutter packages get" command failing in a flutter package

### ISSUE THREAD

**Issue by vjgcodes** [flutter/flutter#16362]
## Steps to Reproduce

When I am trying to import sqflite package in my own flutter package like below, it is failing with No such file error (logs are below) . 

```
dependencies:
  flutter:
    sdk: flutter
  sqflite: '>=0.8.5'
  path_provider: '>=0.3.0'
```
## command

flutter --no-color packages get

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/vjgcodes/FlutterProjects/TestPackage/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:280)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:144)
#7      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:114)
#8      injectPlugins (package:flutter_tools/src/plugins.dart:246)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:80)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:222)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
#19     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#28     main (file:///Users/vjgcodes/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D47, locale en-US)
    • Flutter version 0.2.3 at /Users/vjgcodes/flutter
    • Framework revision 5a58b36e36 (4 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/vjgcodes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/vjgcodes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.22.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by KgotsoK** [comment]
Same here

**Comment by granoeste** [comment]
How about deleting Flutter's package from pubspec.yaml of package module?

```
dependencies:
#  flutter:
#    sdk: flutter
  sqflite: '>=0.8.5'
  path_provider: '>=0.3.0'
```

**Comment by vjgcodes** [comment]
@granoeste 
Unfortunately, it is not working.

**Comment by zoechi** [comment]
Can you try with master channel? `flutter channel master` `flutter doctor`.
I think there were changes that make some commands independent of Xcode stuff.

**Comment by vjgcodes** [comment]
still the same error with master channel as well.

**Comment by andela-pessien** [comment]
@vjgcodes In the meantime you can delete the `ios` folder and re-run `flutter packages get`

**Comment by coldapache** [comment]
Having similar problem. The packages file does not contain the packages I've added. 

I've restarted, deleted pubspec.lock and reattempted to get everything.. code comes out as exit code 0 after flutter packages get runs.
