### ISSUE TITLE
Firebase database fails on reference.once()

### ISSUE THREAD

**Issue by Zmeu213** [flutter/flutter#16374]
## Steps to Reproduce

Use firebase database plugin 0.0.12
Use this code for accessing path that are not exist yet, in my example /users/hash
Use `await reference.once()`
Sample code:

```
    DatabaseReference userpath = FirebaseDatabase.instance.reference().child('users').child(hash);
    print(userpath.path);
    DataSnapshot snapshot = await userpath.once()
    print(snapshot)
```

## Logs

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'Future<dynamic>' is not a subtype of type 'Future<int>' where
Future is from dart:async
Future is from dart:async
int is from dart:core
#0      Query._observe.<anonymous closure> (file:///Users/me/project/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-0.0.12/lib/src/query.dart:48:38)
#1      _runGuarded (dart:async/stream_controller.dart:804:24)
#2      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217:7)
#3      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817:19)
#4      _StreamImpl.listen (dart:async/stream_impl.dart:466:9)
#5      Stream.first (dart:async/stream.dart:1156:25)
#6      Query.once (file:///Users/me/project/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-0.0.12/lib/src/query.dart:73:55)
<asynchronous suspension>
#7      DB.getOrCreateUser (file:///Users/me/project/mobile/lib/db.dart:35:37)
<asynchronous suspension<…>
```

## Flutter Doctor

mobile git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.9, on Mac OS X 10.13.4 17E199, locale ru-RU)
    • Flutter version 0.2.9 at /Users/kirill/Difogic/flutter
    • Framework revision 487e6bc91e (6 days ago), 2018-04-03 10:59:12 -0700
    • Engine revision 04f3c6557c
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/kirill/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone SE • 3458DA8A-2B55-4F79-A287-1A3A79CBE135 • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.

**Comment by Zmeu213** [comment]
Updating to `0.4.2` solved the issue.
Looks like example code in https://codelabs.developers.google.com/codelabs/flutter-firebase/#2 should be fixed as it use static versions of firebase
