### ISSUE TITLE
UX for finder errors in driver needs improvement

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#16383]
My team is frequently confused by errors that driver tests provide.

Example:

Let's say we have this line:

```
await driver.tap(find.byTooltip('Back'));
```

And we remove a screen that has the back button. The error we get is:

```
DriverError: Error in Flutter application: Timeout while executing tap: TimeoutException after 0:00:05.000000: Future not completed...
```

We could improve this error message by saying something like:

```
DriverError: Tap failed. Timed out after waiting 5 seconds to find tooltip with text "Back".
```

**Comment by nerder** [comment]
IMO the DX of the `flutter driver` can be hardly improved, not only with the error messages but as well as extending the set of methods the driver has, for instance as shown in this issue: 

`await driver.tap(find.byTooltip('Back'));` is very fragile, for instance changing the locale of the device will make the tooltip change and the test fail. 

Would be good to start such discussion on improvement here?

**Comment by pedromassangocode** [comment]
Hi @alanrussian 
Can you confirm that this issue still valid? If yes, then please provide a minimum reproducible code of your test suite that reproduce the issue.

**Comment by alanrussian** [comment]
I no longer work on a Flutter app and unfortunately don't have time to verify this. However, it should be easy to verify this. You can modify an example driver test expectation to purposefully fail and run the test.

**Comment by pedromassangocode** [comment]
The error message was updated since then, but still valid issue because the actual message is not the same as the one proposed by this issue.

<details>
<summary> Complete sample code</summary>

### App widget
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Counter App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('App to Test'),
        ),
      ),
    );
  }
}
```

### Test
```
// Imports the Flutter Driver API.
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Driver Test', () {
    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });
    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('look for non-existent tooltip', () async {
      await driver.tap(find.byTooltip('Hide and seek'));
    });
  });
}
```
</details>

<details>
<summary> Logs</summary>

```
00:01 +0: Driver Test look for non-existent tooltip

VMServiceFlutterDriver: tap message is taking a long time to complete...
00:31 +0 -1: Driver Test look for non-existent tooltip [E]

  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts

  package:test_api/src/backend/invoker.dart 322:28               Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 320:10               Invoker._handleError
  package:test_api/src/backend/invoker.dart 276:9                Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 275:38               Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1021:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 18:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1114:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1020:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1263:21                                   _rootCreateTimer
  dart:async/zone.dart 1154:19                                   _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 274:34               Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage


00:31 +0 -1: Driver Test (tearDownAll)

00:31 +0 -1: Driver Test look for non-existent tooltip [E]

  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #3      _rootRun (dart:async/zone.dart:1182:47)
  #4      _CustomZone.run (dart:async/zone.dart:1093:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
  #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #13     _rootRun (dart:async/zone.dart:1190:13)
  #14     _CustomZone.run (dart:async/zone.dart:1093:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
  #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
  #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



  package:flutter_driver/src/driver/vmservice_driver.dart 336:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 232:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage


00:31 +0 -1: Some tests failed.


Unhandled exception:
Dummy exception to set exit code.
Stopping application instance.
Driver tests failed: 255
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (13 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
This is still the case using latest versions, but treating this issue as a proposal to improve the stacktrace as mentioned in the original description. Hence, removing `found in release` and `has reproducible steps` labels.
