### ISSUE TITLE
flutter test failed with 'Connection closed before test suite loaded'

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#16398]
Enter path flutter/packages/flutter, 
$ flutter -v test test/engine/color_test.dart
```
[  +26 ms] [/path/to/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/path/to/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/path/to/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/path/to/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] ec3e350f88f10ab5d52b037dfa7605dff41765ba
[        ] [/path/to/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 minutes ago
[        ] [/path/to/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +21 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.3-12-gec3e350f8
[ +245 ms] running test package with arguments: [--, /path/to/flutter/packages/flutter/test/engine/color_test.dart]
00:00 +0: loading /path/to/flutter/packages/flutter/test/engine/color_test.dart                                                                                
[ +148 ms] test 0: starting test /path/to/flutter/packages/flutter/test/engine/color_test.dart
[   +9 ms] test 0: starting shell process in preview-dart-2 mode
[   +5 ms] Compiling /var/folders/vb/1d3369114yz78xwy_83q3wn80000gn/T/dart_test_listenery1yfBD/listener.dart
00:01 +0: loading /path/to/flutter/packages/flutter/test/engine/color_test.dart                                                                                
[+1150 ms] /path/to/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --flutter-assets-dir=/var/folders/vb/1d3369114yz78xwy_83q3wn80000gn/T/flutter_bundle_directoryaA6C2P --enable-checked-mode --enable-dart-profiling --non-interactive --use-test-fonts --packages=/path/to/flutter/packages/flutter/.packages /var/folders/vb/1d3369114yz78xwy_83q3wn80000gn/T/dart_test_listenery1yfBD/listener.dart.dill
[   +7 ms] test 0: awaiting initial result for pid 54785
[ +395 ms] test 0: process with pid 54785 connected to test harness
[        ] test 0: awaiting test result for pid 54785
[  +13 ms] test 0: process with pid 54785 no longer needs test harness
[        ] test 0: cleaning up...
[        ] test 0: shutting down test harness socket server
[   +1 ms] test 0: deleting temporary directory
[   +1 ms] test 0: deleting temporary bundle directory
[   +1 ms] test 0: ensuring end-of-process for shell
[  +10 ms] test 0: waiting for controller sink to close
[   +1 ms] test 0: finished
00:01 +0 -1: loading /path/to/flutter/packages/flutter/test/engine/color_test.dart [E]
  Failed to load "/path/to/flutter/packages/flutter/test/engine/color_test.dart": Connection closed before test suite loaded.
00:01 +0 -1: Some tests failed.
[  +33 ms] test package returned with exit code 1
[  +12 ms] "flutter test" took 1,985ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:231)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///path/to/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## $ flutter doctor -v
```
[✓] Flutter (Channel master, v0.1.4-pre.12, on Mac OS X 10.13.4 17E199, locale en-HK)
    • Flutter version 0.1.4-pre.12 at /path/to/flutter
    • Framework revision ec3e350f88 (17 minutes ago), 2018-04-10 10:14:53 +0800
    • Engine revision 6474647f52
    • Dart version 2.0.0-dev.46.0.flutter-ef926f98f5

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /path/Library/Android/sdk
    • Android NDK at /path/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone 6s • E5C9A093-5EFD-43C3-826A-3FE4775E23A3 • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by Hixie** [comment]
The tests in the engine repo aren't "flutter test" tests. But this isn't the expected failure mode, indeed. I hope it's a different root cause; I'm pretty sure we have a test for that bug's fix.

cc @jason-simmons who may enjoying finding the cause of this one.
cc @tvolkert since it's related to a failure in `flutter test`.

**Comment by tvolkert** [comment]
In doesn't look like it's relevant, but in case it is, that test is one of a few dozen that imports `package:test` directly rather than `package:flutter_test`.

**Comment by pedia** [comment]
I've even unable to reproduce this after a few times of checkout previous version and master of Flutter.
Close this issue now.

What happened before:
First I test my own test code failed with 'Connection closed before test suite loaded'
Then I choose an xx_test.dart in the folder of flutter, failed again.
So I opened this issue.

**Comment by DjordjeWork** [comment]
I ran into this problem today, and resolved it by updating flutter version with `flutter upgrade`. (From 2.0.3 to 2.0.5)

**Comment by mohammadshrahi** [comment]
I faced this issue on version 2.0.3, the problem was that the flutter_tester executable was missing.
deleting flutter/bin/cache folder and run` flutter pub get `fix the problem for me.
