### ISSUE TITLE
Improve error messages when Drag is used with conflicting types

### ISSUE THREAD

**Issue by rishabhsutara** [flutter/flutter#16407]
[bug.txt](https://github.com/flutter/flutter/files/1892957/bug.txt)

```
I/flutter ( 6765): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6765): The following assertion was thrown while routing a pointer event:
I/flutter ( 6765): type '_DragAvatar<dynamic>' is not a subtype of type '_DragAvatar<int>' where
I/flutter ( 6765):   _DragAvatar is from package:flutter/src/widgets/drag_target.dart
I/flutter ( 6765):   _DragAvatar is from package:flutter/src/widgets/drag_target.dart
I/flutter ( 6765):   int is from dart:core
I/flutter ( 6765):
I/flutter ( 6765): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6765): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6765): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6765):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6765):
I/flutter ( 6765): When the exception was thrown, this was the stack:
I/flutter ( 6765): #0      _DragTargetState.didEnter.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:422:31)
I/flutter ( 6765): #1      State.setState (package:flutter/src/widgets/framework.dart:1108:30)
I/flutter ( 6765): #2      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart:421:7)
I/flutter ( 6765): #3      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:549:23)
I/flutter ( 6765): #4      _ListBase&Object&ListMixin.firstWhere (dart:collection/list.dart:142:15)
I/flutter ( 6765): #5      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:547:51)
I/flutter ( 6765): #6      _DragAvatar.update (package:flutter/src/widgets/drag_target.dart:505:5)
I/flutter ( 6765): #7      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:72:15)I/flutter ( 6765): #8      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:227:13)
I/flutter ( 6765): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 6765): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 6765): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter ( 6765): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 6765): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 6765): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 6765): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 6765): #16     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 6765): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 6765):
I/flutter ( 6765): Event:
I/flutter ( 6765):   PointerMoveEvent(Offset(90.3, 214.6))
I/flutter ( 6765): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.
I/flutter ( 6765): Another exception was thrown: 'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 431 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.I/flutter ( 6765): NavigatorState#a4f7e(tickers: tracking 3 tickers)
I/FirebaseAuth( 6765): [FirebaseAuth:] Loading module via FirebaseOptions.I/FirebaseAuth( 6765): [FirebaseAuth:] Preparing to create service connection to gms implementation
```

**Comment by naiveaiguy** [comment]
Could you remove the `bug.txt` file and just use its contents in the template? It'll be easier to look at.

**Comment by Hixie** [comment]
It would be good to see what the code you are using is. My guess is that you have some cases where you're using generics and some where you're not, and those are not compatible in Dart2.
