### ISSUE TITLE
Running 'flutter doctor' throws an error for v0.2.8

### ISSUE THREAD

**Issue by kyleaisho** [flutter/flutter#16402]
## Steps to reproduce
Have a working version of flutter v0.1 with a clean run of flutter doctor
Download Flutter v0.2.8 flutter_macos_v0.2.8-beta.zip from https://flutter.io/setup-macos/
Replace flutter folder with the unzipped archive above
Run flutter doctor

Observed - Flutter doctor quits due to an error trying to get an Android SDK folder

Stack Trace
`
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/kytasha/Library/Android/sdk/tools/bin/sdkmanager.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:188)
<asynchronous suspension>
#4      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:149)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:49)
#36     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#37     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/kytasha/Library/Android/sdk/tools/bin/sdkmanager.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:188)
<asynchronous suspension>
#4      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:149)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:71)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:128)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:189)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#13     _doctorText (package:flutter_tools/runner.dart:188)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:121)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#23     run (package:flutter_tools/runner.dart:49)
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

`

**Comment by dl14** [comment]
I am running into the same issue. Is there a solution to this issue?

**Comment by zoechi** [comment]
@kyleaisho thanks for the update. I assume it's ok to close this issue?

**Comment by kyleaisho** [comment]
Hi @zoechi, Yah I haven't encountered this issue since 👍
