### ISSUE TITLE
'No pubspec.yaml file found' when project in OneDrive folder

### ISSUE THREAD

**Issue by Jephen** [flutter/flutter#16411]
## Steps to Reproduce

Run `flutter packages get` in the root of my project, and it prompts the following
```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
exit code 1
```
This problem only appears in the project located under the OneDrive folder.
I can run flutter projects elsewhere.

## Logs

Run `flutter packages get -v`
```
[  +26 ms] [D:\Program Files\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +107 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/beta
[        ] [D:\Program Files\flutter\] git rev-parse --abbrev-ref HEAD
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [D:\Program Files\flutter\] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [D:\Program Files\flutter\] git log -n 1 --pretty=format:%H
[  +69 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b397406561f5e7a9c94e28f58d9e49fca0dd58b7
[        ] [D:\Program Files\flutter\] git log -n 1 --pretty=format:%ar
[  +68 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 7 days ago
[        ] [D:\Program Files\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +70 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.2.8-0-gb39740656
[ +154 ms] "flutter get" took 34ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:416)
<asynchronous suspension>
#1      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:312)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1126)
#5      _CustomZone.run (dart:async/zone.dart:1023)
#6      runZoned (dart:async/zone.dart:1501)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#8      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#9      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     runZoned (dart:async/zone.dart:1501)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#17     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#18     new Future.sync (dart:async/future.dart:222)
#19     CommandRunner.run (package:args/command_runner.dart:109)
#20     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#28     run (package:flutter_tools/runner.dart:49)
#29     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#30     main (file:///D:/Program%20Files/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#31     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by Jephen** [comment]
After I reinstalled win10 today, this problem disappeared. So I guess this is my personal reason.
