### ISSUE TITLE
Dart 2's const/new ability can cause Flutter to hang on hot reload.

### ISSUE THREAD

**Issue by newfivefour** [flutter/flutter#16449]
## Steps to Reproduce and Logs

Given this program:

```
import 'package:flutter/widgets.dart';
main() => runApp(MyTest());

class MyTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new StreamBuilder<String>(initialData: "", builder: (BuildContext context, AsyncSnapshot<String> snap) {
      return new Container();
    }); 
  }
}
```

This compiles and runs with `flutter -v run -v`. If you then remove the `new` on `StreamBuilder` and press hot reload the following error occurs:

```
[+5385 ms] Performing hot reload...
[        ] Refreshing active FlutterViews before reloading.
[        ] _flutter.listViews: {}
[ +188 ms] Syncing files to device Nexus 7...
[        ] DevFS: Starting sync from LocalDirectory: '/home/newfivefour/AndroidStudioProjects/testdrive2'
[        ] Scanning project files
[        ] Scanning package files
[  +18 ms] Scanning asset files
[        ] Scanning for deleted files
[   +1 ms] Compiling dart to kernel with 1 updated files
[  +84 ms] compiler message: Unhandled exception:
[        ] compiler message: Crash when compiling file:///home/newfivefour/AndroidStudioProjects/testdrive2/lib/main.dart,
[        ] compiler message: at character offset 283:
[        ] compiler message: lib/main.dart:12:60: Internal problem: Unhandled (#lib1::BuildContext context, #lib2::AsyncSnapshot<dart.core::String> snap) → #lib3::Container {
[        ] compiler message:   return new #lib3::Container::•();
[        ] compiler message: } in defaultTreeNode.
[        ] compiler message:     return StreamBuilder<String>(initialData: "", builder: (BuildContext context, AsyncSnapshot<String> snap) {
[        ] compiler message:                                                            ^
[        ] compiler message: #0      internalProblem (package:front_end/src/fasta/problems.dart:30)
[        ] compiler message: #1      unhandled (package:front_end/src/fasta/problems.dart:43)
[        ] compiler message: #2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
[        ] compiler message: #3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
[        ] compiler message: #4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
[        ] compiler message: #5      FunctionExpression.accept (package:kernel/ast.dart:3513)
[        ] compiler message: #6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
[        ] compiler message: #7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
[        ] compiler message: #8      ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
[        ] compiler message: #9      evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
[        ] compiler message: #10     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
[        ] compiler message: #11     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
[        ] compiler message: #12     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
[        ] compiler message: #13     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
[        ] compiler message: #14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
[        ] compiler message: #15     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
[        ] compiler message: #16     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
[        ] compiler message: #17     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
[        ] compiler message: #18     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
[        ] compiler message: #19     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
[        ] compiler message: #20     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
[        ] compiler message: #21     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
[        ] compiler message: #22     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
[        ] compiler message: #23     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
[        ] compiler message: #24     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #25     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #26     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #27     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #28     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
[        ] compiler message: #29     _rootRun (dart:async/zone.dart:1126)
[        ] compiler message: #30     _CustomZone.run (dart:async/zone.dart:1023)
[        ] compiler message: #31     runZoned (dart:async/zone.dart:1501)
[        ] compiler message: #32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
[        ] compiler message: #33     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #34     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #35     FrontendCompiler.recompileDelta (package:vm/frontend_server.dart:338)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #36     _FlutterFrontendCompiler.recompileDelta (package:frontend_server/server.dart:34)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #37     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:468)
[        ] compiler message: #38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] compiler message: #42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] compiler message: #43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] compiler message: #44     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
[        ] compiler message: #45     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
[        ] compiler message: #46     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
[        ] compiler message: #47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] compiler message: #48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] compiler message: #52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] compiler message: #53     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] compiler message: #54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
[        ] compiler message: #55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
[        ] compiler message: #56     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
[        ] compiler message: #57     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
[        ] compiler message: #58     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] compiler message: #59     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #62     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
[        ] compiler message: #63     _StreamController._add (dart:async/stream_controller.dart:639)
[        ] compiler message: #64     _StreamController.add (dart:async/stream_controller.dart:585)
[        ] compiler message: #65     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
[        ] compiler message: #66     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #69     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
[        ] compiler message: #70     _StreamController._add (dart:async/stream_controller.dart:639)
[        ] compiler message: #71     _StreamController.add (dart:async/stream_controller.dart:585)
[        ] compiler message: #72     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
[        ] compiler message: #73     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
[        ] compiler message: #74     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] compiler message: #75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] compiler message: #76     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
[        ] compiler message: #77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
[        ] compiler message:
[        ] compiler message:
[        ] compiler message: #0      internalProblem (package:front_end/src/fasta/problems.dart:30)
[        ] compiler message: #1      unhandled (package:front_end/src/fasta/problems.dart:43)
[        ] compiler message: #2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
[        ] compiler message: #3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
[        ] compiler message: #4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
[        ] compiler message: #5      FunctionExpression.accept (package:kernel/ast.dart:3513)
[        ] compiler message: #6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
[        ] compiler message: #7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
[        ] compiler message: #8      ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
[        ] compiler message: #9      evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
[        ] compiler message: #10     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
[        ] compiler message: #11     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
[        ] compiler message: #12     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
[        ] compiler message: #13     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
[        ] compiler message: #14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
[        ] compiler message: #15     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
[        ] compiler message: #16     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
[        ] compiler message: #17     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
[        ] compiler message: #18     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
[        ] compiler message: #19     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
[        ] compiler message: #20     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
[        ] compiler message: #21     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
[        ] compiler message: #22     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
[        ] compiler message: #23     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
[        ] compiler message: #24     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #25     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #26     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #27     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #28     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
[        ] compiler message: #29     _rootRun (dart:async/zone.dart:1126)
[        ] compiler message: #30     _CustomZone.run (dart:async/zone.dart:1023)
[        ] compiler message: #31     runZoned (dart:async/zone.dart:1501)
[        ] compiler message: #32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
[        ] compiler message: #33     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #34     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #35     FrontendCompiler.recompileDelta (package:vm/frontend_server.dart:338)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #36     _FlutterFrontendCompiler.recompileDelta (package:frontend_server/server.dart:34)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #37     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:468)
[        ] compiler message: <asynchronous suspension>
[        ] compiler message: #38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] compiler message: #42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] compiler message: #43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] compiler message: #44     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
[        ] compiler message: #45     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
[        ] compiler message: #46     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
[        ] compiler message: #47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] compiler message: #48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] compiler message: #52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] compiler message: #53     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] compiler message: #54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
[        ] compiler message: #55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
[        ] compiler message: #56     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
[        ] compiler message: #57     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
[        ] compiler message: #58     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] compiler message: #59     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #62     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
[        ] compiler message: #63     _StreamController._add (dart:async/stream_controller.dart:639)
[        ] compiler message: #64     _StreamController.add (dart:async/stream_controller.dart:585)
[        ] compiler message: #65     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
[        ] compiler message: #66     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
[        ] compiler message: #67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] compiler message: #68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] compiler message: #69     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
[        ] compiler message: #70     _StreamController._add (dart:async/stream_controller.dart:639)
[        ] compiler message: #71     _StreamController.add (dart:async/stream_controller.dart:585)
[        ] compiler message: #72     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
[        ] compiler message: #73     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
[        ] compiler message: #74     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] compiler message: #75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] compiler message: #76     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
[        ] compiler message: #77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
[  +16 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[        ] _reloadSources: {pause: false, rootLibUri: /data/user/0/com.example.testdrive2/cache/testdrive2ZEEBTN/testdrive2/lib/main.dart.dill, packagesUri: /data/user/0/com.example.testdrive2/cache/testdrive2ZEEBTN/testdrive2/.packages, isolateId: isolates/72891658}
[ +269 ms] reloaded 1 of 382 libraries
[        ] Sending reload events to Nexus 7
[        ] Sending reload event to "file:///data/user/0/com.example.testdrive2/app_flutter/flutter_assets$main-72891658"
[        ] getIsolate: {isolateId: isolates/72891658}
[  +82 ms] _flutter.listViews: {}
[  +42 ms] Evicting dirty assets
[        ] Reassembling application
[        ] ext.flutter.reassemble: {isolateId: isolates/72891658}
[ +116 ms] ext.ui.window.scheduleFrame: {isolateId: isolates/72891658}
[  +47 ms] Hot reload performed in 857ms.
[        ] _getUnusedChangesInLastReload: {isolateId: isolates/72891658}
[  +49 ms] Reloaded 1 of 382 libraries in 928ms.
```

If we reinsert the `new` and press hot reload then we have the following logs:

```
[+156474 ms] Performing hot reload...
[        ] Refreshing active FlutterViews before reloading.
[        ] _flutter.listViews: {}
[ +177 ms] Syncing files to device Nexus 7...
[        ] DevFS: Starting sync from LocalDirectory: '/home/newfivefour/AndroidStudioProjects/testdrive2'
[        ] Scanning project files
[        ] Scanning package files
[  +16 ms] Scanning asset files
[        ] Scanning for deleted files
[   +1 ms] Compiling dart to kernel with 1 updated files
```

And it hangs forever. Or at least ten minutes (that's when I stopped waiting). 

If I try to type enter in the terminal during this I get `Ignoring terminal input: "" because we are busy.`.

## Flutter Analyze

```
$ flutter analyze
Analyzing /home/user/AndroidStudioProjects/testdrive2...
No issues found!
Ran in 3.8s
```

## Flutter Doctor

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by newfivefour** [comment]
It turns out my issue is fixed in master, using `flutter channel master`.

https://github.com/flutter/flutter/issues/16440

I'm not sure whether to close this or not.

Can we please have a new beta soon, one where these Dart 2 const/new problems are fixed?

**Comment by Hixie** [comment]
Yup, we'll hopefully have a new beta in a about 2 weeks.

**Comment by Hixie** [comment]
Closing since reporter says it's fixed on master.
