### ISSUE TITLE
google_sign_in: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by ykphuah** [flutter/flutter#16480]
## Steps to Reproduce

I created a flutter project, with the beta channel, then I added google_sign_in as dependencies. When I try to run the code for signIn, I get this following error:

MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

I found the (closed) issue in 14137, which was fixed by going to dev/master channel, however, I get other errors when I switch to dev/master channel.

I saw the latest commit in google_sign_in says that it should only work with the beta channel, which I am currently in.

## Logs

> ykphuah@cendol:~/Development/myndlikewater$ flutter run
> Launching lib/main.dart on iPhone 8 Plus in debug mode...
> Syncing files to device iPhone 8 Plus...                     2.9s
> 
> 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
> An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:8105/
> For a more detailed help message, press "h". To quit, press "q".
> )
> [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
> MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
> #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
> <asynchronous suspension>
> #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:146:33)
> <asynchronous suspension>
> #2      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:196:28)
> #3      _RootZone.run (dart:async/zone.dart:1376:54)
> #4      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151:18)
> #5      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603:39)
> #6      Future._propagateToListeners (dart:async/future_impl.dart:659:37)
> #7      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342:9)
> #8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #9      _startMicrotaskLoop (dart:async/schedule_microtask<…>

> ykphuah@cendol:~/Development/myndlikewater$ flutter analyze
> Analyzing /Users/ykphuah/Development/myndlikewater...
>   hint • The method '_buildTransitionsStack' isn't used at lib/main.dart:174:10 • unused_element
> 1 issue found.
> (Ran in 7.8s)

## Flutter Doctor

> ykphuah@cendol:~/Development/myndlikewater$ flutter doctor -v
> [✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-MY)
>     • Flutter version 0.2.8 at /Users/ykphuah/Development/flutter
>     • Framework revision b397406561 (9 days ago), 2018-04-02 13:53:20 -0700
>     • Engine revision c903c217a1
>     • Dart version 2.0.0-dev.43.0.flutter-52afcba357
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
>     • Android SDK at /Users/ykphuah/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 26.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.3, Build version 9E145
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.0
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] Connected devices (1 available)
>     • iPhone 8 Plus • 8027F6C8-B4CE-4B13-8B63-D116C302BE77 • ios • iOS 11.3 (simulator)
> 
> • No issues found!

**Comment by ykphuah** [comment]
I did a flutter packages upgrade, and downgraded the cocoapods to 1.4.0, and get another issue now:

The app crashed instead of throwing the init method not found error. I am guessing this is a step further now.

> ykphuah@cendol:~/Development/myndlikewater$ flutter run
> Launching lib/main.dart on iPhone 8 Plus in debug mode...
> Running Xcode clean...                                       1.1s
> Starting Xcode build...                                          
>  ├─Assembling Flutter resources...                    5.2s
>  └─Compiling, linking and signing...                  5.9s
> Xcode build done                                            12.9s
> Syncing files to device iPhone 8 Plus...                         
> )
> 
> 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
> An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:8105/
> For a more detailed help message, press "h". To quit, press "q".
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000010eb061e6 __exceptionPreprocess + 294
> 	1   libobjc.A.dylib                     0x000000010e19b031 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010eb7b975 +[NSException raise:format:] + 197
> 	3   Runner                              0x000000010bbee594 -[GIDSignIn signInWithOptions:] + 242
> 	4   Runner                              0x000000010bbeaf80 -[GIDSignIn signIn] + 64
> 	5   Runner                              0x000000010bbf85d5 -[FLTGoogleSignInPlugin handleMethodCall:result:] + 1461
> 	6   Flutter                             0x000000010bed6c37 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 118
> 	7   Flutter                             0x000000010beedea9 _ZN5shel<…>
> Lost connection to device.

**Comment by SarthakTandon9** [comment]
H, I stilll get this error when i try to use both google vision api and google sign in together, could someone please help?
