### ISSUE TITLE
NoSuchMethodError: The method '???' was called on null. Only in release mode.

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#16492]
## Steps to Reproduce

Not sure if it's easy to reproduce as it's happening in my app and only on device in release mode. I think it's related to this problem I had in https://github.com/flutter/flutter/issues/16451 and the workaround I implemented.

Submitting this as it seems like at least exception and stack trace could be improved.

## Logs

```
NoSuchMethodError: The method '???' was called on null.
#0      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:0)
```

```
Analyzing /Users/anatoly/Projects/richtext/example...
No issues found!
Ran in 6.4s
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.2.11-pre.24, on Mac OS X 10.13.3 17D102, locale en-BY)
    • Flutter version 0.2.11-pre.24 at /Users/anatoly/flutter
    • Framework revision cf500bf6cd (11 hours ago), 2018-04-11 08:52:17 -0700
    • Engine revision ed303c628f
    • Dart version 2.0.0-dev.47.0.flutter-23ae4fa098

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/anatoly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.22.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.0-dev

[✓] Connected devices (2 available)
    • Anatoly’s iPhone • <cut> • ios • iOS 11.3
    • iPhone 7 Plus    • 629AF95E-52DD-4771-9A37-328E1FB78DAB     • ios • iOS 11.3 (simulator)

• No issues found!
```

**Comment by mraleph** [comment]
@pulyaevskiy does it fail in release mode if you build it with `--no-preview-dart-2`?

@alexmarkov looks like `???` it is coming from `CheckNull`. Maybe we need to fix dart-lang/sdk#30480 to have a better error message for such cases.

**Comment by pulyaevskiy** [comment]
@mraleph just checked, it does, but the message is a bit more helpful:

```
NoSuchMethodError: The getter 'minWidth' was called on null.
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
```

This is good to know, thanks for the hint!

**Comment by alexmarkov** [comment]
@pulyaevskiy, thank you for reporting this.

@mraleph, you're right, this message is coming from null checks. https://github.com/dart-lang/sdk/issues/30480 is a meta-issue for optimization work which included adding null checks. Created a specific dart-sdk issue to improve error messages in null checks: https://github.com/dart-lang/sdk/issues/32863.

**Comment by alexmarkov** [comment]
The [fix](https://github.com/dart-lang/sdk/commit/2786b9ff4327fc5a428cf72b2e201d58de8817fb) was rolled into Flutter.
