### ISSUE TITLE
Flutter Doctor Error - SocketException: Write failed (OS Error: Broken pipe, errno = 32)

### ISSUE THREAD

**Issue by raulinoneto** [flutter/flutter#16491]
I followed the "Get Started Tutorial" and when I run the ‘Flutter: New Project’ show this message:
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/raulino/.development/flutter
    • Framework revision b397406561 (9 dias atrás), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

-Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```
Otherwise when I run the 'flutter doctor' in terminal runs normal like this:

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale pt_BR.UTF-8)
    • Flutter version 0.2.8 at /home/raulino/.development/flutter
    • Framework revision b397406561 (9 dias atrás), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/raulino/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/raulino/Android/Sdk
    • Java binary at: /home/raulino/.development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/raulino/.development/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by rabbaniqibar2302** [comment]
can you help me please , my flutter cant instal and then i type flutter doctor in cmd or power shell it cant be install , sorry my english bad

**Comment by raulinoneto** [comment]
I installed the flutter SDK again after I installed the Java JDK and the error presists, so I gave up to use the VS Code, I'll only use the Android Studio, later I'll analyze the VS Code to find a problem.

**Comment by ricardoalcantara** [comment]
Same error here, I tried many times with different versions.
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale pt_BR.UTF-8)
    • Flutter version 0.2.8 at /home/users/ricardo.salcantara/Flutter
    • Framework revision b397406561 (2 semanas atrás), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

-Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by jpospychala** [comment]
I'm getting the same
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale en_US.UTF-8)
-Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by idealopamp** [comment]
Not sure if it's the same root cause, but in case it helps -- this was happening to me until I installed the Flutter and Dart plugins for Android Studio (inside the studio - install plugins - required clicking "search repositories").

**Comment by alescdb** [comment]
OK, for me it was my default java, I switch from `openjdk-11` to `openjdk-8` and problem is now solved.

I found this out when I tried to remove my android-studio from path (moving it from `android-studio` to `android-studio.old`) that ` flutter doctor` is trying to access an non existent java path : 

```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Cannot execute /usr/lib/jvm/java-8-openjdk-amd64/bin/java to determine the version
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[!] Connected devices
    ! No devices available
```
I hope this helps.

**Comment by ecoto17** [comment]
I did have the same issue, I did have that change the JAVA_HOME in the (profile) file

**Comment by zoechi** [comment]
@Hixie

**Comment by jcraven-worksight** [comment]
I was receiving this error on Ubuntu 18.04. I fixed it by running:
```console
flutter config --android-studio-dir <dir>
flutter config --android-sdk <dir>
```

**Comment by mohith7548** [comment]
I'm also facing same issue, @jcraven-worksight your solution is not working for me

**Comment by zoechi** [comment]
@mohith7548 please provide your `flutter doctor -v` output

**Comment by mohith7548** [comment]
@zoechi here it is

![screenshot from 2018-09-16 14-30-20](https://user-images.githubusercontent.com/24828445/45594734-1b227280-b9bd-11e8-92de-8c4c0e865c30.png)

**Comment by zoechi** [comment]
@mohith7548 this looks like a network issue. Is there something special about your network config?

**Comment by jobel-code** [comment]
Same problem: flutter doctor -v 

[✓] Flutter (Channel beta, v0.8.2, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.2 at /home/jobel/development/flutter_linux_v0.8.2-beta/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

-Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by ericdallo** [comment]
I was having the same issue on NixOS which doesn't write permissions on some folders. It seems to me that the issue happens when flutter try to access the android sdk dir and that dir has no write permission.

Therefore changing the android sdk dir solved the issue:
```bash
flutter config --android-studio-dir <dir>
flutter config --android-sdk <dir>
```

**Comment by bkonyi** [comment]
If this is still relevant, please open a new issue for this.
