### ISSUE TITLE
Flutter_driver(QA Environment) Trying to scroll through multiple cupertino pickers.

### ISSUE THREAD

**Issue by deonchimple** [flutter/flutter#16504]
## Steps to Reproduce

I was trying to scroll through scroll-able cupertino pickers using flutter driver. Also the reason it says the 'All the Tests passed' because I have put it within a try and catch.

## Logs

 ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21496): The following assertion was thrown while dispatching a pointer event:
I/flutter (21496): 'package:flutter/src/gestures/arena.dart': Failed assertion: line 69 pos 12: 'isOpen': is not true.
I/flutter (21496):
I/flutter (21496): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21496): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21496): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21496):   https://github.com/flutter/flutter/issues/new
I/flutter (21496):
I/flutter (21496): When the exception was thrown, this was the stack:
I/flutter (21496): #2      _GestureArena.add (package:flutter/src/gestures/arena.dart)
I/flutter (21496): #3      GestureArenaManager.add (package:flutter/src/gestures/arena.dart:111:11)
I/flutter (21496): #4      OneSequenceGestureRecognizer._addPointerToArena (package:flutter/src/gestures/recognizer.dart:203:49)
I/flutter (21496): #5      OneSequenceGestureRecognizer.startTrackingPointer (package:flutter/src/gestures/recognizer.dart:216:25)
I/flutter (21496): #6      DragGestureRecognizer.addPointer (package:flutter/src/gestures/monodrag.dart:115:5)
I/flutter (21496): #7      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:602:18)
I/flutter (21496): #8      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2400:14)
I/flutter (21496): #9      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (21496): #10     FlutterDriverExtension._scroll (package:flutter_driver/src/extension/extension.dart:310:21)
I/flutter (21496): <asynchronous suspension>
I/flutter (21496): #11     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168:51)
I/flutter (21496): <asynchronous suspension>
I/flutter (21496): #12     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370:32)
I/flutter (21496): <asynchronous suspension>
I/flutter (21496): #13     _runExtension (dart:developer/runtime/libdeveloper.dart:85:23)
I/flutter (21496): (elided 2 frames from class _AssertionError)
I/flutter (21496):
I/flutter (21496): Event:
I/flutter (21496):   PointerDownEvent(Offset(106.8, 410.7))
I/flutter (21496): Target:
I/flutter (21496):   RenderPointerListener#6ce6f
I/flutter (21496): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 28 pos 12: '!routes.contains(route)': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 28 pos 12: '!routes.contains(route)': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 28 pos 12: '!routes.contains(route)': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 28 pos 12: '!routes.contains(route)': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
00:16 [32m+1[0m: login (tearDownAll)[0m
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
00:16 [32m+1[0m: All tests passed![0m
I/flutter (21496): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 131 pos 12: '_state != _DragState.ready': is not true.
Stopping application instance.

**Comment by zoechi** [comment]
Sorry for not responding earlier?
Is this still an issue?
Can you please add the output of `flutter doctor -v`?
