### ISSUE TITLE
Crash when downloading on bad network

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16545]
SocketException: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: nodename nor servname provided, or not known, errno = 8)

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:551)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:285)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:311)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:282)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:298)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:470)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:245)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:201)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:317)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#18     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#27     new Future.sync (dart:async/future.dart:224)
#28     CommandRunner.run (package:args/command_runner.dart:109)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1126)
#33     _CustomZone.run (dart:async/zone.dart:1023)
#34     runZoned (dart:async/zone.dart:1501)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:49)
#38     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#39     main (file:///Users/ianh/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by jcollins-g** [comment]
Thanks for the backtrace, now I know exactly where to catch that elusive SocketException.
