### ISSUE TITLE
Crash when setting new data on cloud firestore

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#16550]
## Steps to Reproduce

Try running our app from here: https://github.com/emshack/sufficient_goldfish and then hit the fab at the bottom. Watch for the resulting stack trace. Looks like we're trying to call "trim" on nothing. Here are the values I'm passing in a hashmap when I get this error:

```
{Field.id: -L9wqleURPasyEmTD22J, Field.profilePicture1: https://firebasestorage.googleapis.com/v0/b/sufficientgoldfish.appspot.com/o/fish-silhouette.png?alt=media&token=27fed5f3-9a70-4355-a3d7-7ec378c40acd, Field.name: Frank,  Field.lastSeenLatitude: -122.3505293, Field.lastSeenLongitude: 47.6487257}
```
## Logs
```
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:5)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:79)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:89)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:498)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30025): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (30025): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30025): PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference, null)
E/flutter (30025): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter (30025): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (30025): <asynchronous suspension>
E/flutter (30025): #2      DocumentReference.setData (file:///usr/local/google/home/efortuna/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.4.0/lib/src/document_reference.dart:39:30)
```

## Flutter Doctor

```
[✓] Flutter (Channel dev, v0.2.11, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.11 at /usr/local/google/home/efortuna/googleio/flutter
    • Framework revision f408bb06f9 (2 days ago), 2018-04-10 14:27:53 -0700
    • Engine revision 6474647f52
    • Dart version 2.0.0-dev.46.0.flutter-ef926f98f5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/efortuna/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • Pixel 2 XL • 711KPAE0891080 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

cc @emshack

**Comment by aston1238** [comment]
Did you manage to find a solution?

**Comment by Livinglist** [comment]
I think this issue is still not resolved?

**Comment by ened** [comment]
@efortuna please try again with latest flutter & cloud_firestore versions & submit output of `flutter doctor -v`, `pubspec.yaml`, `pubspec.lock` in case you run into any trouble.

**Comment by kroikie** [comment]
@efortuna

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/852. Any further collaboration will be done there.
