### ISSUE TITLE
onPressed causing Internal problem: Unhandled () 

### ISSUE THREAD

**Issue by andrewpmoore** [flutter/flutter#16562]
## Steps to Reproduce
I've stripped down my example as far as I can while still getting this error, here's the code

```
import 'package:flutter/material.dart';

void main() => runApp(new Home());

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: new Text('Basic Counter'),
      ),
      body: new Center(
          child: new IconButton(
            icon: new Icon(Icons.add),
            onPressed: () {
              print('onPressed here');
            },
          )),
    );
  }
}
```

As soon as I put anything into the onPressed I get this. I was trying to navigate to a 2nd page following the cookbook

```
onPressed: () {
  Navigator.push(
    context,
    new MaterialPageRoute(builder: (context) => new SecondScreen()),
  );
}
```

but it seems anything into the onPressed is causing the issue

## Logs

Flutter run
#########
```
Launching lib/main.dart on Pixel 2 XL in debug mode...
Initi
aunching lib/main.dart on Pixel 2 XL in debug mode...
Initializing gradle...                                       1.2s
Resolving dependencies...                                    3.4s
Running 'gradlew assembleDebug'...
compiler message: Unhandled exception:
Crash when compiling file:///C:/Users/andrew/projects/flutter/scope_test/lib/main.dart,
at character offset 167:
lib/main.dart:15:20: Internal problem: Unhandled () → dart.core::Null {
  dart.core::print("onPressed here");
} in defaultTreeNode.
        onPressed: () {
                   ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
#5      FunctionExpression.accept (package:kernel/ast.dart:3513)
#6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#11     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#12     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#13     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#14     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#16     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#17     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#18     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#19     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#20     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#21     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#22     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#23     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#24     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#25     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#26     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#27     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#28     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#29     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#31     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#37     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#38     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#39     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#40     new Future.<anonymous closure> (dart:async/future.dart:174)
#41     _rootRun (dart:async/zone.dart:1122)
#42
compiler message:    _CustomZone.run (dart:async/zone.dart:1023)
#43     _CustomZone.runGuarded (dart:async/zone.dart:925)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#45     _rootRun (dart:async/zone.dart:1126)
#46     _CustomZone.run (dart:async/zone.dart:1023)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#48     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#49     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#50     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
#5      FunctionExpression.accept (package:kernel/ast.dart:3513)
#6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#11     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#12     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#13     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#14     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#15     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#16     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#17     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#18     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#19     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#20     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#21     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#22     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#23     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#24     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#25     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#26     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#27     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#28     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#29     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#31     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#37     IncrementalC
compiler message: ompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#38     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#39     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#40     new Future.<anonymous closure> (dart:async/future.dart:174)
#41     _rootRun (dart:async/zone.dart:1122)
#42     _CustomZone.run (dart:async/zone.dart:1023)
#43     _CustomZone.runGuarded (dart:async/zone.dart:925)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#45     _rootRun (dart:async/zone.dart:1126)
#46     _CustomZone.run (dart:async/zone.dart:1023)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#48     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#49     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#50     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on C:\Users\andrew\projects\flutter\scope_test\lib/main.dart

FAILURE: Build failed with an exception.


* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 441

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Gradle build failed: 1
```

Run `flutter analyze` and attach any output of that command also.
```
Analyzing C:\Users\andrew\projects\flutter\scope_test...
No issues found!
Ran in 9.0s
```

## Flutter Doctor

```
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.17639.1000], locale en-GB)
    • Flutter version 0.2.8 at C:\flutter
    • Framework revision b397406561 (10 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\andrew\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\andrew\AppData\Local\Android\sdk
    • Java binary at: C:\AndroidStudio3.2\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\AndroidStudio3
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.2)
    • Android Studio at C:\AndroidStudio3.2\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b01)

[√] Connected devices (1 available)
    • Pixel 2 XL • 711KPTM0799753 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by aliceblock** [comment]
Try to Wrap Scaffold with MaterialApp?
```
void main() => runApp(new MaterialApp(
  home: new MyApp()
));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
        child: new FlatButton(
          onPressed: () => Navigator.push(context, PageTwo()),
          child: new Text("Goto page 2")
        )
      )
    );
  }
}
```

**Comment by pebreo** [comment]
I also have the same error. I will try to switch to master channel.

**Comment by jack4git** [comment]
I had a similar but not identical problem, can provide details if it would be helpful. In my case, it appeared to be related to an onTap within a ListTile which was simply doing a print().

running `flutter channel master` fixed it for me also.

`
Crash when compiling file:///Users/jackivers/Projects/Flutter/flutter_power_2/lib/presentation/device_list_item.dart,
at character offset 467:
lib/presentation/device_list_item.dart: Internal problem: Unhandled this in defaultTreeNode.
`

**Comment by bigonlnn** [comment]
Internal problem: Unhandled () → dart.core::Null {} in defaultTreeNode.
      onPressed: () {},
                 ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)

**Comment by monty8800** [comment]
切到master下执行，完美解决！！！

**Comment by zoechi** [comment]
I believe this is fixed since a while.
