### ISSUE TITLE
UnconstrainedBox: updateRenderObject throws exception if constrainedAxis is null

### ISSUE THREAD

**Issue by maksimr** [flutter/flutter#16593]
## Steps to Reproduce

- Run `flutter create bar`
- Change the content of `main.dart` on this:
- Run `flutter run`
- After start run "Hot Reload" (just type `r` in terminal where flutter is running)

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return new UnconstrainedBox(
      child: new SizedBox(
        width: 40.0,
        height: 40.0,
        child: new DecoratedBox(
          decoration: new BoxDecoration(
            color: Colors.green,
          ),
        ),
      ),
    );
  }
}
```

## Logs

```
Performing hot reload...
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyApp:
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 629 pos 12: 'value !=
null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      RenderUnconstrainedBox.constrainedAxis= (package:flutter/src/rendering/shifted_box.dart)
#3      UnconstrainedBox.updateRenderObject (package:flutter/src/widgets/basic.dart:1768:9)
#4      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4271:12)
#5      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4642:11)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#16     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#17     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 3 frames from class _AssertionError and package dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 629 pos 12: 'value != null': is not true.
Another exception was thrown: buildScope missed some dirty elements.
Reloaded 1 of 385 libraries in 478ms.
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-RU)
    • Flutter version 0.2.8 at /Users/maksimrv/www/dart/flutter
    • Framework revision b397406561 (12 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Users/maksimrv/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • CFD8611A-2EF7-4F24-8137-30046ADA3A66 • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by chinmaygarde** [comment]
cc @Hixie
