### ISSUE TITLE
Scrolling through SliverGridList Throws an AssertionFailure

### ISSUE THREAD

**Issue by abhishekdewan101** [flutter/flutter#16596]
Hi, 

I am currently creating an app where I download data and show it as a SliverGridList with 2 columns. Everytime I scroll too fast through the list the following assertion error is thrown. I am not sure what's causing this error as I am not doing anything special other than just creating a grid list of child items. 

Also the error mentioned to be open an issue so I am opening this issue. Hope this helps.

Thanks

Abhishek

```
Performing full restart...
Restarted app in 2,629ms.
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
W/BiChannelGoogleApi( 1300): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms
D/FirebaseAuth( 1300): Notifying id token listeners about user ( anhSwjYVKvXssSw2sKIKGRgO5Qk1 ).
D/FirebaseApp( 1300): Notifying auth state listeners.
D/FirebaseApp( 1300): Notified 1 auth state listeners.
I/flutter ( 1300): [[38;5;102m00:50:57[0m]  Firebase User Has been Logged In dewan.dev2@gmail.com
I/flutter ( 1300): https://api.themoviedb.org/3/discover/movie?api_key=e3ddbb353811c2ead0fdb30472f6f462&page=1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
I/flutter ( 1300): https://api.themoviedb.org/3/discover/movie?api_key=e3ddbb353811c2ead0fdb30472f6f462&page=1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
I/flutter ( 1300): https://api.themoviedb.org/3/discover/movie?api_key=e3ddbb353811c2ead0fdb30472f6f462&page=2
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
I/flutter ( 1300): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1300): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 1300): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3707 pos 12: '_state._widget ==
I/flutter ( 1300): null': is not true.
I/flutter ( 1300): 
I/flutter ( 1300): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1300): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1300): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1300):   https://github.com/flutter/flutter/issues/new
I/flutter ( 1300): 
I/flutter ( 1300): When the exception was thrown, this was the stack:
I/flutter ( 1300): #2      new StatefulElement (package:flutter/src/widgets/framework.dart)
I/flutter ( 1300): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:781:42)
I/flutter ( 1300): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2888:40)
I/flutter ( 1300): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 1300): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 1300): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 1300): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 1300): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 1300): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 1300): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 1300): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 1300): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 1300): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 1300): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 1300): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 1300): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 1300): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 1300): #19     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
I/flutter ( 1300): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 1300): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 1300): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 1300): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 1300): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 1300): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 1300): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 1300): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 1300): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 1300): #29     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
I/flutter ( 1300): #30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter ( 1300): #31     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter ( 1300): #32     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter ( 1300): #33     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter ( 1300): #34     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter ( 1300): #35     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter ( 1300): #36     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter ( 1300): #37     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:411:5)
I/flutter ( 1300): #38     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:583:17)
I/flutter ( 1300): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 1300): #40     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
I/flutter ( 1300): #41     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
I/flutter ( 1300): #42     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
I/flutter ( 1300): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 1300): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 1300): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 1300): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
I/flutter ( 1300): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 1300): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 1300): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 1300): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 1300): #51     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 1300): #52     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 1300): (elided 2 frames from class _AssertionError)
I/flutter ( 1300): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 215 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2209 pos 20: '_debugCurrentBuildTarget == context': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 596 pos 14: 'childParentData.index == index': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@653e5c0[MainActivity]( 1300): ViewPostImeInputStage processPointer 1
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
I/flutter ( 1300): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter ( 1300): Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
> 

> 
```

**Comment by abhishekdewan101** [comment]
Just an update. I built a release apk and it doesn't seem to be happening on the release built which is strange.

**Comment by chinmaygarde** [comment]
Can you post a reduced test case?

cc @Hixie, @HansMuller

**Comment by abhishekdewan101** [comment]
Hi @chinmaygarde I am not sure what you mean by a reduced test case? If you can provide me with more details, I will more than happy to help with it.

**Comment by chinmaygarde** [comment]
Just a simple app that you shows the error. You could add the widgets in the failing configuration to a new project created by `flutter create`.

**Comment by abhishekdewan101** [comment]
Ohh ok. I have tried to attach the files that cause the issue below:

**List Page - This page creates the SliverGridList**

``` dart
 @override
  Widget build(BuildContext context) {
    return new Padding(
      padding: const EdgeInsets.only(
          left: 10.0,
          right: 10.0,
          top: 10.0
      ),
      child: new CustomScrollView(
            slivers: <Widget>[
              new SliverGrid(
                  delegate: new SliverChildBuilderDelegate(
                     (BuildContext context, int index) {
                       if (index == mMovieListAdapter.length - mThresholdValue) {
                         loadMovieData();
                       }
                       return getGridChildItem(context,mMovieListAdapter[index]);
                     },
                     childCount: mMovieListAdapter.length
                  ),
                  gridDelegate: new SliverGridDelegateWithMaxCrossAxisExtent(
                      maxCrossAxisExtent: 200.0,
                      mainAxisSpacing: 10.0,
                      crossAxisSpacing: 10.0,
                      childAspectRatio: 0.60,
                  )
              )
            ],
          ),
    );
  }
```

where mMovieListAdapter is the List that is populated by a Future and using setState method to tell Flutter to re-draw the page.

**Movie Poster Class - The thing that gets displayed in the SliverGridList**
``` dart
import 'package:flutter/material.dart';
import 'package:movieee_app/data/Configs.dart';
import 'package:movieee_app/data/NetworkManager.dart';
import 'package:movieee_app/ui/apphomescreen/movielist/MoviePosterDetail.dart';
import 'package:movieee_app/utils/NavigatorUtils.dart';

class MoviePoster extends StatefulWidget {
  MoviePosterState posterState;

  MoviePoster(Movie movie) {
    posterState = new MoviePosterState(movie);
  }

  @override
  State<StatefulWidget> createState() => posterState;
}

class MoviePosterState extends State<MoviePoster> {
  Movie movie;
  MoviePosterState(this.movie);

  @override
  Widget build(BuildContext context) {
    return getNormalMoviePoster();
  }

  Widget getNormalMoviePoster() {
    return new Material(
      borderRadius: new BorderRadius.circular(10.0),
      color: Colors.white,
      child: new InkWell(
        onTap: () { showMovieDetail(context,movie); },
        splashColor: Colors.black26,
        child: new Stack(
          children: <Widget>[
            new Image.network(
              Configs.IMAGE_URL + movie.mPosterUrl,
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
              fit: BoxFit.cover,
              alignment: Alignment.center,
            )
          ],
        ),
      ),
    );
  }

  void showMovieDetail(BuildContext context,Movie movie) {
    NavigatorUtils.pushRouteWithSlideAnimation(context,new MoviePosterDetail(movie));
  }
}
```

This is the first time I've contributed to a Open Source project so I apologize for any mistakes in posting the code. Please let me know if there is any way i can help. 

Also of interest is that the first time I come to the page that creates the list, the list is populated without any error, if I keep scrolling down, the list works properly, however, whenever I scroll up after having scrolled down, thats when the issue happens. Also only happens on Debug builds and is OS agnostic.

**Comment by abacaj** [comment]
I just had this issue as well. Seems like no one has looked at it.

**Comment by Hixie** [comment]
cc @dnfield who may be interested in this one (it might be similar to that bug you fixed recently)

**Comment by dnfield** [comment]
@abhishekdewan101 and @abacaj - 

1. Can you see if this still reproduces with the latest code in master?
2. If so, can you try to provide me with a small sample reproduction that doesn't require querying an external API (e.g. with a mocked hard coded `List`, including the hard coded list)?

**Comment by abacaj** [comment]
> @abhishekdewan101 or @abacaj -
> 
> 1. Can you see if this still reproduces with the latest code in master?  It's hard to say for sure, but it's possible that #21350 fixed this.
> 2. If it is still an issue, can you try to provide me with a small sample reproduction that doesn't require querying an external API (e.g. with a mocked hard coded `List`, including the hard coded list)?

I will try to get you a code sample, it happened only in debug mode and it happens on both iOS and android emulators when scrolling down fast

**Comment by zoechi** [comment]
@abacaj any progress?
Is this still an issue?

**Comment by kiran1496** [comment]
i'm facing the same problem, any progress on this?
