### ISSUE TITLE
RefreshIndicator not compiling.

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#16622]
## Steps to Reproduce
Having this code:
```
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return /*new*/ Scaffold(
      body: new RefreshIndicator(
        child: new ListView.builder(
            itemBuilder: (context, index) => new Text("index $index")),
        onRefresh: () {},
      ),
    );
  }
}
```
I got compile error.

However, if I add `new` keyword to `Scaffold` everything works. Not sure if it should work like that.

## Logs
Flutter analyze shows no issues.
Output:
```
Launching lib/main.dart on ALE L21 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
compiler message: Unhandled exception:
Crash when compiling file:///home/marcinus/dev/wlasne/flutter/error/lib/main.dart,
at character offset 527:
lib/main.dart:29:20: Internal problem: Unhandled () → dart.core::Null {} in defaultTreeNode.
        onRefresh: () {},
                   ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
#5      FunctionExpression.accept (package:kernel/ast.dart:3513)
#6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#11     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#12     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#13     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#14     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#15     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#17     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#18     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#19     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#20     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#21     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#22     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#23     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#28     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#29     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#30     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#35     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#36     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#37     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#38     new Future.<anonymous closure> (dart:async/future.dart:174)
#39     _rootRun (dart:async/zone.dart:1122)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#43     _rootRun (dart:async/zone.dart:1126)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#47     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#48     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitFunctionExpression (package:kernel/visitor.dart:177)
#5      FunctionExpression.accept (package:kernel/ast.dart:3513)
#6      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#8      ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#10     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#11     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#12     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#13     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#14     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#15     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#16     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#17     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#18     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#19     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#20     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#21     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#22     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#23     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#24     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#25     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#26     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#28     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#29     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#30     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#35     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#36     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#37     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#38     new Future.<anonymous closure> (dart:async/future.dart:174)
#39     _rootRun (dart:async/zone.dart:1122)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     _CustomZone.runGuarded (dart:async/zone.dart:925)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#43     _rootRun (dart:async/zone.dart:1126)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#46     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#47     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#48     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on /home/marcinus/dev/wlasne/flutter/error/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/home/marcinus/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 441

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/home/marcinus/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle build failed: 1
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/marcinus/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/marcinus/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/marcinus/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/marcinus/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at /home/marcinus/idea-IU-171.4073.35
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /home/marcinus/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/173.4674.33
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700

[✓] VS Code (version 1.21.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.8.2

[✓] Connected devices (2 available)
    • ALE L21                   • W3D7N16C16019415 • android-arm64 • Android 6.0 (API 23)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 7.0 (API 24) (emulator)
```

**Comment by zoechi** [comment]
Can you please try channel `master`? (`flutter channel master` `flutter doctor`)

**Comment by MarcinusX** [comment]
On `master` everything works fine. :)

**Comment by zoechi** [comment]
Ok, so this is aleeady fixed and only needs to land on `dev` and `beta` channel.

**Comment by zoechi** [comment]
Can this issue be closed?

**Comment by MarcinusX** [comment]
Yes, definately :)
