### ISSUE TITLE
Crash when compiling simple project

### ISSUE THREAD

**Issue by gregko** [flutter/flutter#16632]
## Steps to Reproduce

Attaching ProjBug.zip with the complete Android Studio project. Used to work fine in older version of Flutter.

## Logs

Run your application with `flutter run` and attach all the log output.
C:\android\atVoicePlugins\avar_catalogs>flutter run
Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    2.0s
Running 'gradlew assembleDebug'...
compiler message: Unhandled exception:
Crash when compiling file:///C:/android/atVoicePlugins/avar_catalogs/lib/main.dart,
at character offset 1887:
RangeError (offset): Invalid value: Not in range 0..4450, inclusive: 6759
#0      RangeError.checkValueInInterval (dart:core/errors.dart:267)
#1      Source.getLocation (package:kernel/ast.dart:5885)
#2      Component.getLocation (package:kernel/ast.dart:5679)
#3      _getLocationInComponent (package:kernel/ast.dart:6000)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:1685)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#7      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#8      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#9      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#10     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#11     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#12     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#13     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#14     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#15     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#16     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#17     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#18     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#19     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#20     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#21     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#22     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#23     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#24     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#25     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#26     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#27     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#28     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#29     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#30     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#31     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#32     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#33     TreeNode.location (package:kernel/ast.dart:165)
#34     TreeNode.location (package:kernel/ast.dart:164)
#35     ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:113)
#36     TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#37     TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#38     ThisExpression.accept (package:kernel/ast.dart:3341)
#39     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#40     PropertyGet.accept (package:kernel/ast.dart:2242)
#41     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#42     MethodInvocation.accept (package:kernel/ast.dart:2820)
#43     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#44     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#45     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#46     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#47     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#48     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#49     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#50     DietListe
compiler message: ner.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#51     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#52     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#53     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#54     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#55     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#56     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#57     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#58     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#59     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#60     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#61     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#62     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#63     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#64     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#65     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#66     _rootRun (dart:async/zone.dart:1126)
#67     _CustomZone.run (dart:async/zone.dart:1023)
#68     runZoned (dart:async/zone.dart:1501)
#69     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#70     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#71     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#72     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#73     new Future.<anonymous closure> (dart:async/future.dart:174)
#74     _rootRun (dart:async/zone.dart:1122)
#75     _CustomZone.run (dart:async/zone.dart:1023)
#76     _CustomZone.runGuarded (dart:async/zone.dart:925)
#77     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#78     _rootRun (dart:async/zone.dart:1126)
#79     _CustomZone.run (dart:async/zone.dart:1023)
#80     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#81     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#82     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#83     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

#0      RangeError.checkValueInInterval (dart:core/errors.dart:267)
#1      Source.getLocation (package:kernel/ast.dart:5885)
#2      Component.getLocation (package:kernel/ast.dart:5679)
#3      _getLocationInComponent (package:kernel/ast.dart:6000)
#4      Procedure._getLocationInEnclosingFile (package:kernel/ast.dart:1685)
#5      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#6      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#7      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#8      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#9      TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#10     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#11     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#12     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#13     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#14     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#15     TreeNode._getLocationI
compiler message: nEnclosingFile (package:kernel/ast.dart:169)
#16     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#17     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#18     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#19     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#20     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#21     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#22     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#23     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#24     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#25     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#26     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#27     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#28     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#29     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#30     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#31     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#32     TreeNode._getLocationInEnclosingFile (package:kernel/ast.dart:169)
#33     TreeNode.location (package:kernel/ast.dart:165)
#34     TreeNode.location (package:kernel/ast.dart:164)
#35     ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:113)
#36     TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#37     TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#38     ThisExpression.accept (package:kernel/ast.dart:3341)
#39     ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#40     PropertyGet.accept (package:kernel/ast.dart:2242)
#41     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#42     MethodInvocation.accept (package:kernel/ast.dart:2820)
#43     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:175)
#44     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#45     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#46     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#47     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#48     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#49     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#50     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#51     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#52     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#53     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#54     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#55     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#56     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#57     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#58     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#59     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#60     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#61     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#62     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#63     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous s
compiler message: uspension>
#64     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#65     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#66     _rootRun (dart:async/zone.dart:1126)
#67     _CustomZone.run (dart:async/zone.dart:1023)
#68     runZoned (dart:async/zone.dart:1501)
#69     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#70     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#71     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#72     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#73     new Future.<anonymous closure> (dart:async/future.dart:174)
#74     _rootRun (dart:async/zone.dart:1122)
#75     _CustomZone.run (dart:async/zone.dart:1023)
#76     _CustomZone.runGuarded (dart:async/zone.dart:925)
#77     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#78     _rootRun (dart:async/zone.dart:1126)
#79     _CustomZone.run (dart:async/zone.dart:1023)
#80     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#81     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#82     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#83     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on C:\android\atVoicePlugins\avar_catalogs\lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\greg\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 441

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\Users\greg\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Gradle build failed: 1

Run `flutter analyze` and attach any output of that command also.
C:\android\atVoicePlugins\avar_catalogs>flutter analyze
Analyzing C:\android\atVoicePlugins\avar_catalogs...
No issues found!
Ran in 6.8s
[ProjBug.zip](https://github.com/flutter/flutter/files/1916950/ProjBug.zip)

## Flutter Doctor

C:\android\atVoicePlugins\avar_catalogs>flutter doctor -v
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
    • Flutter version 0.2.8 at c:\Users\greg\flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\android\android-sdk
    • Android NDK at C:\android\android-sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\android\android-sdk
    • Java binary at: C:\apps\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\apps\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code, 32-bit edition (version 1.19.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 2 categories.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jason-simmons** [comment]
Try switching to the Flutter master channel.

The attached app is working for me on master.

**Comment by gregko** [comment]
Thank you, Jason, will try it. Hope the devs can fix this bug in Flutter 2 as well - I tried to get rid of the "new" keywords, but adding them back does not fix the compile problem in beta.
