### ISSUE TITLE
after updating flutter I get subtype errors for my JsonDecoder classes

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#16637]
upon running `inventories.save()` I get

```
E/flutter (29983): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (29983): type 'List<Map<String, dynamic>>' is not a subtype of type 'List<String>' where
E/flutter (29983):   List is from dart:core
E/flutter (29983):   Map is from dart:core
E/flutter (29983):   String is from dart:core
E/flutter (29983):   List is from dart:core
E/flutter (29983):   String is from dart:core
E/flutter (29983): 
E/flutter (29983): #0      InventoriesData.save (package:maxanet_uploader/InventoriesData.dart:19:52)
E/flutter (29983): <asynchronous suspension>
E/flutter (29983): #1      InventoriesState._addHandler (package:maxanet_uploader/pages/inventories.dart:33:25)
E/flutter (29983): <asynchronous suspension>
E/flutter (29983): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (29983): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (29983): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (29983): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (29983): #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (29983): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (29983): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (29983): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (29983): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (29983): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (29983): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (29983): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (29983): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (29983): #15     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (29983): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

Here is the entire class below, line number 19 is inside the `save () async {` function

```dart
import 'dart:async';
import 'dart:convert';
import 'package:m_uploaderr/InventoryData.dart';
import 'package:shared_preferences/shared_preferences.dart';

class InventoriesData {
  Future<SharedPreferences> _prefs = SharedPreferences.getInstance();
  List<InventoriesItem> items;

  static final InventoriesData _singleton = new InventoriesData._internal();
  InventoriesData._internal();

  static InventoriesData get instance => _singleton;

  Future<bool> save() async {
    final SharedPreferences prefs = await _prefs;
    prefs.setStringList('inventories', inventories.itemsToJson());
    // await new Future.delayed(const Duration(seconds: 1));
    return true;
  }

  Future<bool> load() async {
    final SharedPreferences prefs = await _prefs;
    if (prefs.getStringList('inventories') == null) {
      inventories.items = new List<InventoriesItem>();
    } else {
      inventories.items = jsonToItems(prefs.getStringList('inventories'));
    }

    for (var i = 0; i < inventories.items.length; i++) {
      inventories.items[i].data = await inventory.load(inventories.items[i].name);
    }

    return true;
  }

  Future<bool> remove(name) async {
    await inventory.remove(name);

    for (var i = 0; i < inventories.items.length; i++) {
      if (name == inventories.items[i].name) {
        inventories.items.removeAt(i);
      }
    }

    await inventories.save();
    return true;
  }

  itemsToJson() {
    return inventories.items.map((InventoriesItem item) {
      return item.toJson();
    }).toList(growable: true);
  }

  jsonToItems(items) {
    return items.map((item) {
      return new InventoriesItem.fromJson(item);
    }).toList(growable: true);
  }

}

class InventoriesItem extends JsonDecoder {
  String name;
  List<InventoryItem> data;
  InventoriesItem(this.name);

  stats () {
    if (this.data == null) {
      return 'nothing found';
    }
    int items = this.data.length;
    int photos = 0;
    for (int i = 0; i < this.data.length; i++) {
      photos += this.data[i].photos.length;
    }

    return '$items items wtih $photos photos';
  }

  InventoriesItem.fromJson(Map<String, dynamic> json)
    : name = json['name'];

  Map<String, dynamic> toJson() => { 'name': name };
}

var inventories = new InventoriesData._internal();
```

**Comment by zoechi** [comment]
Dart2 semantics is now default (was opt-in previously) which has more tight type checks at runtime.
You'll need to update your code.

`inventories.itemsToJson()` seems to return a list of `Map` instead of a list of `String`

**Comment by acidjazz** [comment]
thanks @zoechi, I learned all of this and spent the day re-factoring my code to be a bit more strict, closing this non-issue. Great tip on the plugin settings change.
