### ISSUE TITLE
camera plugin has type errors

### ISSUE THREAD

**Issue by ezrasandzerbell** [flutter/flutter#16647]
## Steps to Reproduce

This code has been working fine for months, but began failing today after updating flutter. Similar error messages have popped up on the Flutter gitter channel, which leads me to believe there is a bug in the update. 

 **Main.js**
```
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

Future main() async{
  cameras = await availableCameras();
  runApp(new MyApp());
}
```
**pubspec.yaml**
```
dependencies:

  flutter:
    sdk: flutter
  camera: ^0.0.2
```
## Logs
```
Running "flutter packages get" in FLUTTER-ios-android-app...
Launching lib/main.dart on iPhone 6s in debug mode...
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<Map<String, String>>' where
  List is from dart:core
  List is from dart:core
  Map is from dart:core
  String is from dart:core
  String is from dart:core

#0      availableCameras (package:camera/camera.dart)
<asynchronous suspension>
#1      main (file:///Users/Ezra/Desktop/FLUTTER-ios-android-app/lib/main.dart:16:19)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
Syncing files to device iPhone 6s...

```

**Comment by jonahwilliams** [comment]
This was fixed via https://github.com/flutter/plugins/pull/417 and https://github.com/flutter/plugins/pull/439
