### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by choallin** [flutter/flutter#16674]
## Steps to Reproduce

I want to test the "Test drive" app with Android Studio (v 3.1.1) on my connected Sony phone (Xperia XZ)
I am using openSUSE Tmbleweed with (nearly) all updates.

## Logs

Flutter crash report

## command

flutter build flx --suppress-analytics --target /home/choallin/code/food_watcher/lib/main.dart --preview-dart-2 --output-file /home/choallin/code/food_watcher/build/app/intermediates/flutter/debug/app.flx --depfile /home/choallin/code/food_watcher/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --working-dir /home/choallin/code/food_watcher/build/app/intermediates/flutter/debug/flutter_assets

## exception

String: Exit code 7 from: zip -q /home/choallin/code/food_watcher/build/app/intermediates/flutter/debug/app.flx.tmp packages/cupertino_icons/assets/CupertinoIcons.ttf fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE kernel_blob.bin platform.dill:

Command Line Error:
Unknown switch:
-q

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:249)
<asynchronous suspension>
#1      _ZipToolBuilder.createZip (package:flutter_tools/src/zip.dart:100)
<asynchronous suspension>
#2      assemble (package:flutter_tools/src/flx.dart:183)
<asynchronous suspension>
#3      build (package:flutter_tools/src/flx.dart:109)
<asynchronous suspension>
#4      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:68)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:298)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:254)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#22     new Future.sync (dart:async/future.dart:222)
#23     CommandRunner.run (package:args/command_runner.dart:109)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:168)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1126)
#28     _CustomZone.run (dart:async/zone.dart:1023)
#29     runZoned (dart:async/zone.dart:1501)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:49)
#33     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#34     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_GB.UTF-8)
    • Flutter version 0.2.8 at /home/choallin/flutter
    • Framework revision b397406561 (2 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/choallin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /home/choallin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/choallin/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • F8331 • CB512CTKRA • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

## Flutter Doctor

See above

**Comment by choallin** [comment]
I found the reason. Suse comes with 7z preinstalled and the zip command is a symlink to 7z instead of unzip
