### ISSUE TITLE
Invalid argument(s): Cannot find executable for sw_vers

### ISSUE THREAD

**Issue by affinnen** [flutter/flutter#16689]
## Steps to Reproduce

On MacOS High Sierra (10.13.4)
1. unzip flutter_macos_v0.2.8-beta.zip
2. Run
flutter doctor

## Logs

Unhandled exception:
Invalid argument(s): Cannot find executable for sw_vers.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84)
#2      _PosixUtils.name (package:flutter_tools/src/base/os.dart:133)
#3      new Usage (package:flutter_tools/src/usage.dart:35)
#4      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:71)
#5      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#6      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#7      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#8      AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#9      Usage.instance (package:flutter_tools/src/usage.dart:52)
#10     flutterUsage (package:flutter_tools/src/usage.dart:20)
#11     _handleToolError (package:flutter_tools/runner.dart:108)
<asynchronous suspension>
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#19     run (package:flutter_tools/runner.dart:49)
#20     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#21     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by affinnen** [comment]
Add path
PATH=/usr/bin:${PATH}
