### ISSUE TITLE
Will not run in iPhone Simulator anymore in Flutter 0.3.1-pre.28 • channel master

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#16684]
## Steps to Reproduce
```
Upgrade to latest version Flutter 0.3.1-pre.25 • channel master and Flutter Projects will no longer open up in iPhone Simulator.
```

Flutter Version:
```
Flutter 0.3.1-pre.25 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9a0b562524 (70 minutes ago) • 2018-04-17 16:57:47 -0700
Engine • revision 0c09bf03d1
Tools • Dart 2.0.0-dev.48.0.flutter-f76dad0adc
```

Error:
```
Launching lib/main.dart on iPhone X in debug mode...
Skipping compilation. Fingerprint match.
Xcode build done.
Error connecting to the service protocol: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 50433
Exited (sigterm)
```

## Logs
`flutter run`
```
Pix:fatima_prayers marco$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Skipping compilation. Fingerprint match.
Running Xcode clean...                                       1.1s
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.7s
 └─Compiling, linking and signing...                 13.9s
Xcode build done.                                           18.5s
```

`flutter analyze`
```
Analyzing /Users/marco/Documents/Pixolini/Flutter_Development/fatima_prayers...
No issues found!
Ran in 7.8s
```

## Flutter Doctor
```
Pix:fatima_prayers marco$ flutter doctor -v
[✓] Flutter (Channel master, v0.3.1-pre.25, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.3.1-pre.25 at /Users/marco/flutter
    • Framework revision 9a0b562524 (74 minutes ago), 2018-04-17 16:57:47 -0700
    • Engine revision 0c09bf03d1
    • Dart version 2.0.0-dev.48.0.flutter-f76dad0adc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/marco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • 55C63F10-A0FA-4CD8-9E89-BF66AA5FEA8F • ios • iOS 11.3 (simulator)

• No issues found!
```

Thank you

**Comment by Sun3** [comment]
I tested with Flutter 0.3.1-pre.25 and Flutter 0.3.1-pre.28 with same results.

**Comment by yjbanov** [comment]
Could you please run it in verbose mode (`flutter run -v`) and share the log output around the `WebSocketChannelException`? I'm wondering if it resembles issue https://github.com/flutter/flutter/issues/13655.

**Comment by Sun3** [comment]
## flutter run -v  Log
```
Pix:fatima_prayers marco$ flutter run -v
[  +38 ms] [/Users/marco/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/marco/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/Users/marco/Development/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/marco/Development/flutter/] git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c058c6a6d70fd7d63c83a8aa2cde52bccdbf248c
[        ] [/Users/marco/Development/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 56 minutes ago
[   +1 ms] [/Users/marco/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +29 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.0-38-gc058c6a6d
[ +148 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +45 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +128 ms] /Users/marco/Library/Android/sdk/platform-tools/adb devices -l
[  +19 ms] Exit code 0 from: /Users/marco/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +10 ms] idevice_id -h
[  +85 ms] which ideviceinstaller
[   +4 ms] Exit code 0 from: which ideviceinstaller
[   +3 ms] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[ +150 ms] /usr/bin/xcrun simctl list --json devices
[ +133 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] Marco’s iPhone • • ios • iOS 11.3
[        ] iPhone X       •      • ios • iOS 11.3 (simulator)
[  +29 ms] "flutter run" took 679ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:256)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:312)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///Users/marco/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by yjbanov** [comment]
I was curious to see the log output just before it fails. I'll close the issue as is seems to have been fixed.

**Comment by Sun3** [comment]
Great. I have updated to the latest master version and it's working again.
