### ISSUE TITLE
GridView.{builder, custom} no longer work without itemCount

### ISSUE THREAD

**Issue by perlatus** [flutter/flutter#16688]
Something changed around SliverGrid. The regression hit me when I recompiled my app for the first time in a few months. This used to work. I didn't see anything in the docs that hint that I'm instantiating the GridView incorrectly.

Another bug I filed, #11071 switching ListView.builder to GridView.builder in my example repo encounters the same problem. 

## Steps to Reproduce

Here's a simplified example with GridView.builder.

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new GridView.builder(
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3),
      itemBuilder: (ctx, i) {
        return new Card(child: new Center(child: new Text(i.toString())));
      },
  )));
}
```

## Logs

```
I/flutter ( 4797): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4797): The following assertion was thrown during performLayout():
I/flutter ( 4797): 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 227 pos 12: 'childCount !=
I/flutter ( 4797): null': is not true.
I/flutter ( 4797): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4797): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4797): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4797):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4797): When the exception was thrown, this was the stack:
I/flutter ( 4797): #2      SliverGridRegularTileLayout.computeMaxScrollOffset (package:flutter/src/rendering/sliver_grid.dart)
I/flutter ( 4797): #3      SliverGrid.estimateMaxScrollOffset (package:flutter/src/widgets/sliver.dart:601:46)
I/flutter ( 4797): #4      SliverMultiBoxAdaptorElement.estimateMaxScrollOffset (package:flutter/src/widgets/sliver.dart:792:19)
I/flutter ( 4797): #5      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:607:54)
I/flutter ( 4797): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4797): #7      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 4797): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4797): #9      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
I/flutter ( 4797): #10     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
I/flutter ( 4797): #11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
I/flutter ( 4797): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 4797): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
...
```
## Flutter Doctor

```
▶ flutter doctor -v
[✓] Flutter (Channel master, v0.2.12-pre.33, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.12-pre.33 at /Users/(( snip ))/data/code/clone/flutter
    • Framework revision ea30c95dc9 (4 days ago), 2018-04-13 17:02:14 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/(( snip ))/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • SM S766C • 3696d6c6 • android-arm • Android 4.3 (API 18)

• No issues found!
```

**Comment by perlatus** [comment]
From what I've managed to look at so far, it's related to how SliverChildBuilderDelegate's childCount variable can be meaningfully null. And in all the cases I can think of, you wouldn't pass in an explicit childCount anyway if you need a builder to create the elements on-demand.

```
class SliverChildBuilderDelegate extends SliverChildDelegate {
...
  /// The total number of children this delegate can provide.
  ///
  /// If null, the number of children is determined by the least index for which
  /// [builder] returns null.
  final int childCount;
...
  @override
  int get estimatedChildCount => childCount;
```

**Comment by perlatus** [comment]
Passing in a large itemCount stops the assertion from failing at least

**Comment by andrewrabon** [comment]
This is currently making it impossible for me to implement an infinitely-scrolling grid via Firebase (I believe, let me know if there's a solution I'm missing.) The large itemCount "fix" doesn't really fix it.

**Comment by perlatus** [comment]
I'm just appending items to my backing list and calling setState. When it rebuilds with the new items (and updated item count), the scroll position is unchanged.

**Comment by ng1905** [comment]
I would be interested in a fix too, I just spent the last hour trying to find out what is wrong with my code.

**Comment by Hixie** [comment]
The fix is probably to move the following lines:

```dart
    final int childCount = this.childCount;
    if (childCount == null)
      return double.infinity;
```

...from `_extrapolateMaxScrollOffset` in `widgets/slivers.dart`, where it acts as a fallback, to the top of `SliverMultiBoxAdaptorElement.estimateMaxScrollOffset` (then pass `childCount` to `_extrapolateMaxScrollOffset` as an argument and make that method static).

If any of you would like to try that change that would be great. It just needs a quick test as well, which would just be some code that fails today, to make sure it no longer fails (and can scroll to large numbers).

**Comment by ng1905** [comment]
Working on it.
