### ISSUE TITLE
Syncing files to device failed

### ISSUE THREAD

**Issue by fralways** [flutter/flutter#16742]
## Steps to Reproduce

I am trying to run flutter app on my iPhone. It builds, it runs, but syncing files to device fails and I cannot do hot reload which is very annoying. Tried using command line - `flutter run -d 4b34bf2bfb20b14a787f66f964f9a9ca8a2eac42 --verbose` and android studio, same issue. It prints error after ~10 mins.

## Logs

```
[   +2 ms] Updating assets
[ +248 ms] Syncing files to device Filip's iPhone...
[   +1 ms] DevFS: Starting sync from LocalDirectory: '/XXXPATHXXX'
[        ] Scanning project files
[   +5 ms] Scanning package files
[  +64 ms] Scanning asset files
[  +16 ms] Scanning for deleted files
[  +12 ms] Compiling dart to kernel with 433 updated files
[+1305 ms] Updating files
[+1010312 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] Retrying writing "build/flutter_assets/assets/images/2.0x/Profile.png" to DevFS due to error: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8112/
[        ] Retrying writing "build/flutter_assets/assets/images/3.0x/vorspeise.png" to DevFS due to error: HttpException: , uri = http://127.0.0.1:8112/
[        ] Retrying writing "build/flutter_assets/assets/images/2.0x/lidl.png" to DevFS due to error: HttpException: , uri = http://127.0.0.1:8112/
[        ] Retrying writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS due to error: HttpException: , uri = http://127.0.0.1:8112/
[   +8 ms] DevFS sync failed. Lost connection to device: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 127.0.0.1, port = 58430
[   +1 ms] "flutter run" took 1,035,142ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:407)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///xxxflutterpathxxx/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.3.1-pre.35, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)
```

**Comment by jonasbark** [comment]
Same here with [✓] Flutter (Channel dev, v0.2.11, on Mac OS X 10.13.4 17E199, locale de-DE)
Running works just fine, but with debugging I'm having the same issue

**Comment by fralways** [comment]
It seems like there is some maximum size of assets we can have until this gets broken. Ive tested by commenting out all of my assets in pubspec.yaml and after rebuild hot reload works. I then uncomment couple of small images, syncing is successful and hot reload works. Then I then try to uncomment image that is 8mb large and syncing fails. What I tried next, I comment out large image and then I uncomment small images one by one, and sync + hot reload works up until some point when this fails again.

**Comment by caseycrogers** [comment]
I'm having the same issue-adding 'flutter_firebase_ui: ^0.0.7' to my pubspec causes lost connection to device. Removing it fixes it. Is there a workaround or a fix yet?

**Comment by zoechi** [comment]
@caseycrogers can you please post the output of `flutter doctor -v`?

**Comment by matthew-carroll** [comment]
I think I'm running into the same problem.  Here are the relevant logs and output from Flutter Doctor

```
[        ] Sending reload events to iPhone 7
[        ] Sending reload event to "main.dart$main-1055205564"
[        ] getIsolate: {isolateId: isolates/1055205564}
[  +11 ms] _flutter.listViews: {isolateId: isolates/1055205564}
[   +1 ms] Evicting dirty assets
[   +1 ms] ext.flutter.evict: {value: AssetManifest.json, isolateId: isolates/1055205564}
[   +6 ms] ext.flutter.evict: {value: FontManifest.json, isolateId: isolates/1055205564}
[   +1 ms] ext.flutter.evict: {value: LICENSE, isolateId: isolates/1055205564}
[   +1 ms] Reassembling application
[        ] ext.flutter.reassemble: {isolateId: isolates/1055205564}
[  +83 ms] ext.ui.window.scheduleFrame: {isolateId: isolates/1055205564}
[   +3 ms] Hot reload performed in 705ms.
[        ] Reloaded 3 of 402 libraries in 712ms.
[  +20 ms] [DEVICE LOG] 2018-07-22 20:56:26.569978-0700  localhost Runner[41341]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
[   +4 ms] flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2018-07-22 20:56:26.572366-0700  localhost Runner[41341]: (Flutter) flutter: The following assertion was thrown resolving an image codec:
[        ] [DEVICE LOG] 2018-07-22 20:56:26.572458-0700  localhost Runner[41341]: (Flutter) flutter: Unable to load asset: lib/data/card_photos/mountain.jpg
[        ] [DEVICE LOG] 2018-07-22 20:56:26.572792-0700  localhost Runner[41341]: (Flutter) flutter:
[        ] [DEVICE LOG] 2018-07-22 20:56:26.572883-0700  localhost Runner[41341]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] flutter: The following assertion was thrown resolving an image codec:
[        ] flutter: Unable to load asset: lib/data/card_photos/mountain.jpg
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[   +3 ms] [DEVICE LOG] 2018-07-22 20:56:26.578753-0700  localhost Runner[41341]: (Flutter) flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
[        ] flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.578926-0700  localhost Runner[41341]: (Flutter) flutter: <asynchronous suspension>
[        ] flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-07-22 20:56:26.579351-0700  localhost Runner[41341]: (Flutter) flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.579501-0700  localhost Runner[41341]: (Flutter) flutter: <asynchronous suspension>
[        ] flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
[        ] flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-07-22 20:56:26.579660-0700  localhost Runner[41341]: (Flutter) flutter: #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.579770-0700  localhost Runner[41341]: (Flutter) flutter: #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.580006-0700  localhost Runner[41341]: (Flutter) flutter: #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
[        ] flutter: #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
[        ] flutter: #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
[        ] flutter: #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.580639-0700  localhost Runner[41341]: (Flutter) flutter: #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.580934-0700  localhost Runner[41341]: (Flutter) flutter: (elided 8 frames from package dart:async)
[        ] flutter: #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
[        ] flutter: (elided 8 frames from package dart:async)
[   +1 ms] [DEVICE LOG] 2018-07-22 20:56:26.583168-0700  localhost Runner[41341]: (Flutter) flutter:
[        ] flutter:
[        ] [DEVICE LOG] 2018-07-22 20:56:26.583261-0700  localhost Runner[41341]: (Flutter) flutter: Image provider: AssetImage(bundle: null, name: "lib/data/card_photos/mountain.jpg")
[        ] [DEVICE LOG] 2018-07-22 20:56:26.583337-0700  localhost Runner[41341]: (Flutter) flutter: Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#5b641(), name:
[        ] [DEVICE LOG] 2018-07-22 20:56:26.583402-0700  localhost Runner[41341]: (Flutter) flutter: "lib/data/card_photos/mountain.jpg", scale: 1.0)
[        ] flutter: Image provider: AssetImage(bundle: null, name: "lib/data/card_photos/mountain.jpg")
[        ] flutter: Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#5b641(), name:
[        ] flutter: "lib/data/card_photos/mountain.jpg", scale: 1.0)
[        ] [DEVICE LOG] 2018-07-22 20:56:26.583538-0700  localhost Runner[41341]: (Flutter) flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +344 ms] [DEVICE LOG] 2018-07-22 20:56:26.927758-0700  localhost Runner[41341]: (Flutter) flutter: Another exception was thrown: Unable to load asset: lib/data/card_photos/road.jpg
[        ] flutter: Another exception was thrown: Unable to load asset: lib/data/card_photos/road.jpg






[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.7 at /Users/mattcarroll/Documents/Libs/flutter
    • Framework revision 66091f9696 (13 days ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mattcarroll/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1012-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • iPhone 7 • 218EC2F0-895D-43BC-AED4-542620D66578 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by cbracken** [comment]
@matthew-carroll if I'm reading the logs right, your issue looks more like an issue loading assets from within the app, whereas the original report appears to be an issue with assets pushed via `devfs` during a hot reload/restart.

**Comment by matthew-carroll** [comment]
@cbracken Maybe I was having both problems then, but my primary issue was definitely a hot reload issue.  Hot reload was broken for me, seemingly as a result of having large assets.

**Comment by lukepighetti** [comment]
I'm having this same issue here https://github.com/flutter/flutter/issues/19772#event-2045271003

**Comment by zoechi** [comment]
@lukepighetti could it be the size of assets in your case as well as mentioned in https://github.com/flutter/flutter/issues/16742#issuecomment-384283190 ?

**Comment by dodongindong** [comment]
Same here after running this command flutter package upgrade with **percent_indicator: "^1.0.12"** after removing the dependency hot reload seems to work

Here is my info:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.16299.847], locale en-PH)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```

**Comment by mdibaiee** [comment]
Can confirm, switching to LTS worked.
`pacman -S linux-lts linux-lts-headers` and then create a new bootloader entry for LTS

**Comment by jonahwilliams** [comment]
Closing for the same reason as https://github.com/flutter/flutter/issues/19772#issuecomment-572844234
