### ISSUE TITLE
UI Tests: If test is waiting for an expect(...emits) test a strange exception is thrown

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#16746]
## Steps to Reproduce

clone https://github.com/escamoteur/rx_widgets/tree/UI_Test_Exception

and run the test in rx_widgets/example/test/homepage_test.dart

you will get this output

```
Running "flutter packages get" in example...
Received: null
Called Execute
Received: [Instance of 'WeatherEntry']
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart': Failed assertion: line 672 pos 7:
'_fakeAsync.nonPeriodicTimerCount == 0'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:487:7)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:464:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:646:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:644:16)
#14     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
#15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#16     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#20     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#21     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#25     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#40     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#41     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 28 frames from class _AssertionError, class _FakeAsync, package dart:async, and package
stack_trace)

The test description was:
Tapping update button updates the weather
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Tapping update button updates the weather
✖ HomePage - Tapping update button updates the weather
Some tests failed.
```

This is the Test:

```Dart
    testWidgets('Tapping update button updates the weather', (tester) async {
      final model = new MockModel();
     final command = new MockCommand<String,List<WeatherEntry>>();
       final widget = new ModelProvider(
        model: model,
        child: new MaterialApp(home: new HomePage()),
      );

      when(model.updateWeatherCommand).thenReturn(command);

      // Expectation doesn't match output an exception is thwon inside Flutter. 
      // Change `Londo` to `London` and it will run again
      command.queueResultsForNextExecuteCall([CommandResult<List<WeatherEntry>>(
                  [WeatherEntry("Londo", 10.0, 30.0, "sunny", 12)],null, false)]);

      expect(command, emitsInOrder([ crm(null, false, false), crm([WeatherEntry("London", 10.0, 30.0, "sunny", 12)], false, false) ]));

      command.listen((data)=> print("Received: " + data.data.toString()));

      await tester.pumpWidget(widget); // Build initial State
      await tester.pump(); // Build after Stream delivers value
      await tester.tap(find.byKey(AppKeys.updateButtonEnabled));


    });
```

Because the expected event never is received the expects would normally timeout with an timeout exception together with Flutter it is an exception deep in flutter.

Change `Londo` to `London` again and it runs through

## Flutter Doctor

```
PS C:\Entwicklung\FlutterApps\packages\rx_widgets\example> flutter doctor -v
[√] Flutter (Channel dev, v0.3.0, on Microsoft Windows [Version 10.0.16299.371], locale de-DE)
    • Flutter version 0.3.0 at C:\Entwicklung\Flutter
    • Framework revision c73b8a7cf6 (7 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.22.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.12.0-dev.windows-paths-experimental

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Adding a delay to `pumpWidget(...)` or `pump(...)` should fix that.

**Comment by escamoteur** [comment]
Can no longer reproduce this
