### ISSUE TITLE
Theme Tween breaking when transitioning themes dynamically

### ISSUE THREAD

**Issue by fmatosqg** [flutter/flutter#16779]
May be related to #16277 

Tested on emulator 8.1 and HTC U11 on Nougat, noticed same behavior.

## Steps to Reproduce

Create `new MaterialApp(theme: _themeData)` and modify `_themeData` dynamically. Themes that contain `textTheme: new TextTheme()` will cause screen glitch followed by stack trace with assertion errors in  `TextStyle.lerp` (`display4: TextStyle.lerp(a.display4, b.display4, t),`).

Expected behavior: see new theme being applied with animation.
Actual behavior: theme gets applied but momentarily shows error screen.

When explicitly defining a new `TextTheme` with absolutely all optional property fields there's no error coming from assertions.

Sample project on git@github.com:fmatosqg/flutter_problem.git commit bdf397a

I reproduced and added notes on other related problems:
- `ThemeData.copyWith` missing primarySwatch
- When hot reload after editing a theme property no changes are noticed, needs full reload, even with transitions between themes. Same with font size changes. 
- Small size change on AppBar text when changing swatch color, or textStyle color or size (it shrinks a bit then comes back)

More detailed notes on bottom of project's `main.dart`.

```
## Logs
I/flutter (15045): 'package:flutter/src/painting/text_style.dart': Failed assertion: line 500 pos 12: 'b != null': is
I/flutter (15045): not true.
I/flutter (15045): 
I/flutter (15045): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15045): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15045): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15045):   https://github.com/flutter/flutter/issues/new
I/flutter (15045): 
I/flutter (15045): When the exception was thrown, this was the stack:
I/flutter (15045): #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart)
I/flutter (15045): #3      TextTheme.lerp (package:flutter/src/material/typography.dart:307:27)
I/flutter (15045): #4      ThemeData.lerp (package:flutter/src/material/theme_data.dart:665:28)
I/flutter (15045): #5      ThemeDataTween.lerp (package:flutter/src/material/theme.dart:188:41)
I/flutter (15045): #6      Tween.evaluate (package:flutter/src/animation/tween.dart:160:12)
I/flutter (15045): #7      _AnimatedThemeState.build (package:flutter/src/material/theme.dart:247:19)
I/flutter (15045): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter (15045): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (15045): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (15045): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (15045): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (15045): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (15045): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15045): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (15045): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (15045): #17     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (15045): #18     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (15045): (elided 2 frames from class _AssertionError)
I/flutter (15045): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15045): 6th theme
I/flutter (15045): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 499 pos 12: 'a != null': is not true.
I/flutter (15045): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 499 pos 12: 'a != null': is not true.
I/flutter (15045): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 499 pos 12: 'a != null': is not true.
I/flutter (15045): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 499 pos 12: 'a != null': is not true.
```

```
> flutter analyze
Analyzing /Users/fabio.dematos/code/android/samples/flutter/flutter_problem...
No issues found!
Ran in 5.3s
```
## Flutter Doctor

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.12.6 16G29, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 2.3)
[✓] Connected devices (3 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
