### ISSUE TITLE
Make flutter_test work with sync-async semantics

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#16801]

**Comment by mravn-google** [comment]
We do plan to fix the test failure [just exposed by the device lab](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci8zOWQ3ZjIyYTk2NmIyZGU3NDU2NWEzZjY4MTFjZmEyODIzNGNiYTc4DAsSBFRhc2sYgICAgICA2AkM). We do not yet know, if it is a problem with the test or the driver.

**Comment by yjbanov** [comment]
`microbenchmarks` do not use `flutter_driver`. We `flutter run` them in profile mode: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/microbenchmarks.dart

**Comment by mravn-google** [comment]
After applying the above, I still get stack traces like this during the first part of the microbenchmark test suite:
```
[microbenchmarks] [STDOUT] [+5384 ms] I/flutter ( 2601): (The following exception is now available via WidgetTester.takeException:)
[microbenchmarks] [STDOUT] [   +4 ms] I/flutter ( 2601): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): The following assertion was thrown running a test:
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): Failed assertion: boolean expression must not be null
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): 
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): Either the assertion indicates an error in the framework itself, or we should provide substantially
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): more information in this error message to help you determine and fix the underlying cause.
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): In either case, please report this assertion by filing a bug on GitHub:
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601):   https://github.com/flutter/flutter/issues/new
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): 
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): When the exception was thrown, this was the stack:
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): #0      LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:0)
[microbenchmarks] [STDOUT] [   +2 ms] I/flutter ( 2601): #1      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): #2      main.<anonymous closure>.<anonymous closure> (file:///Users/mravn/github/flutter/dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart:51)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): #11     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): #12     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): #13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): (elided 8 frames from package dart:async)
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): 
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): 
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): ════════════════════════════════════════════════════════════════════════════════════════════════════
[microbenchmarks] [STDOUT] [        ] I/flutter ( 2601): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
```
The boolean expression mentioned appears to be the first conditional in `handleDrawFrame` in `flutter_test/lib/src/binding.dart`. That method is supposed to be called in alternation with calls to `handleBeginFrame` above it, but at this point in the test, `handleBeginFrame` is called twice in a row, followed by two calls in a row to `handleDrawFrame`.

**Comment by tomaszpolanski** [comment]
With this being closed, can `FlutterDriverExtension::_waitForElement` be modified?
