### ISSUE TITLE
Flake while running coverage

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#16839]
```
unhandled error during test:
/b/build/slave/Linux/build/flutter/packages/flutter/test/widgets/sliver_list_test.dart
NoSuchMethodError: The getter 'pathSegments' was called on null.
Receiver: null
Tried calling: pathSegments
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      collect (package:coverage/src/collect.dart:16)
<asynchronous suspension>
#2      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55)
<asynchronous suspension>
#3      CoverageCollector.onFinishedTests (package:flutter_tools/src/test/coverage_collector.dart:23)
<asynchronous suspension>
#4      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:501)
<asynchronous suspension>
#5      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:266)
#6      PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:63)
<asynchronous suspension>
#7      Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:252)
<asynchronous suspension>
#8      new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89)
<asynchronous suspension>
#9      invoke (package:test/src/utils.dart:297)
#10     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88)
#11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403)
<asynchronous suspension>
```

**Comment by tvolkert** [comment]
Still happening

**Comment by tvolkert** [comment]
More recent stack trace:

```
NoSuchMethodError: The getter 'pathSegments' was called on null.
Receiver: null
Tried calling: pathSegments
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      collect (package:coverage/src/collect.dart:16)
<asynchronous suspension>
#2      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55)
<asynchronous suspension>
#3      CoverageCollector.onFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:23)
<asynchronous suspension>
#4      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:510)
<asynchronous suspension>
#5      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:266)
#6      PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:63)
<asynchronous suspension>
#7      Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:252)
<asynchronous suspension>
#8      new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89)
<asynchronous suspension>
#9      invoke (package:test/src/utils.dart:297)
#10     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88)
#11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403)
<asynchronous suspension>
#12     new Future.<anonymous closure> (dart:async/future.dart:174)
#13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
#14     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
#20     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by cbracken** [comment]
Just saw this twice in a row.

This seems to occur because the `observatoryUri` [passed to](https://github.com/flutter/flutter/blob/c9954f1053463c03d9088bc17290b3d7661edbf6/packages/flutter_tools/lib/src/test/coverage_collector.dart#L56) `collect()` is null. That comes off the ProcessEvent passed [here](https://github.com/flutter/flutter/blob/c9954f1053463c03d9088bc17290b3d7661edbf6/packages/flutter_tools/lib/src/test/coverage_collector.dart#L23).

**Comment by Panthro** [comment]
Here's a full log from travis. If you need any reference: https://travis-ci.org/CrochetLand/app/jobs/394125608

From what I could investigate, it's happening only in OSX, I have the same build in travis with linux and it doesn't happen.

As for now I'm disabling coverage inside the OSX box.

The error is random, sometimes does not happen as you can see in this build: https://travis-ci.org/CrochetLand/app/builds/393343349

**Comment by DanTup** [comment]
Not sure it's useful, but here's an additional log:

https://build.chromium.org/p/client.flutter/builders/Linux/builds/6229/steps/run%20test.dart%20for%20coverage%20shard/logs/stdio

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by DanTup** [comment]
Yep, seen just yesterday :(

**Comment by liyuqian** [comment]
Just see it today...

**Comment by Hixie** [comment]
I see this reliably on my home machine.

We should probably all start putting `export FLUTTER_TOOL_ARGS=--checked` in our `.bash_profile`s.

**Comment by Hixie** [comment]
Attempt #1 at fixing this: https://github.com/flutter/flutter/pull/20506

**Comment by zoechi** [comment]
Is this still happening or did #20506 fix it?

**Comment by tvolkert** [comment]
Haven't seen this in a while - closing.
