### ISSUE TITLE
Directory Listing Failed

### ISSUE THREAD

**Issue by seant4** [flutter/flutter#16889]
After running flutter analyze, i get this error 
Unhandled exception:
```
FileSystemException: Directory listing failed, path = '/home/sean/.local/lib/python2.7' (OS Error: Permission denied, errno = 13)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:34)
#1      _Directory.listSync (dart:io/directory_impl.dart:214)
#2      Driver._collectFiles (package:analyzer_cli/src/driver.dart:597)
#3      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:318)
<asynchronous suspension>
#4      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:232)
<asynchronous suspension>
#5      Driver.start (package:analyzer_cli/src/driver.dart:201)
<asynchronous suspension>
#6      main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart:13)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
(Ran in 1.0s)
```

Here is the flutter doctor stuff --
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.20.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
Sorry for the late response.
DartAnalyzer shouldn't have a reason to list this directory.
Is this still an issue?
