### ISSUE TITLE
flutter run -t example/layers/rendering/flex_layout.dart example blows up on master channel

### ISSUE THREAD

**Issue by gedw99** [flutter/flutter#16887]
I am building a custom 2D Rendering app with Dart, and hit one of the examples failing

## Steps to Reproduce

```
git clone github.com/flutter/flutter
cd examples/layers && flutter run -t rendering/flex_layout.dart
```

## Logs

```
flutter run -t rendering/flex_layout.dart
Launching rendering/flex_layout.dart on iPhone 8 Plus in debug mode...
Skipping compilation. Fingerprint match.
Syncing files to device iPhone 8 Plus...                     3.8s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Performing full restart...
Restarted app in 990ms.
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is
flutter: undefined.
flutter: 'package:flutter/src/rendering/flex.dart': Failed assertion: line 439 pos 18: 'textDirection !=
flutter: null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart)
flutter: #3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:636:12)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #5      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #7      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #11     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
flutter: #12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
flutter: #13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
flutter: #14     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #15     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #16     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #17     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #18     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #19     _invoke (dart:ui/hooks.dart:120:13)
flutter: #20     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderFlex#41910 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
flutter:   parentData: offset=Offset(0.0, 0.0); flex=1; fit=null (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=736.0, h=0.0)
flutter:   size: MISSING
flutter:   direction: horizontal
flutter:   mainAxisAlignment: start
flutter:   mainAxisSize: max
flutter:   crossAxisAlignment: start
flutter:   verticalDirection: down
flutter:   textBaseline: alphabetic
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:   RenderDecoratedBox#d05c1 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderParagraph#f4428 NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderDecoratedBox#84111 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderParagraph#b5544 NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderFlex#dc515 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderDecoratedBox#b44fa NEEDS-LAYOUT NEEDS-PAINT
flutter:       RenderParagraph#505a6 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderSolidColorBox#9a6b0 NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#41910 relayoutBoundary=up1 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#b574c NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#0e5d7 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#fdea7
flutter: Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
flutter: Another exception was thrown: Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is undefined.
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#41910 relayoutBoundary=up1 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#b574c NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#0e5d7 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#fdea7
flutter: Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
```

## Flutter Doctor

```
x-MacBook-Pro:layers apple$ flutter doctor -v
[✓] Flutter (Channel master, v0.3.4-pre.2, on Mac OS X 10.13.4 17E199, locale en-DE)
    • Flutter version 0.3.4-pre.2 at /Users/apple/workspace/flutter/flutter_macos_v0.2.8-beta/flutter
    • Framework revision fd7222eea8 (14 hours ago), 2018-04-23 02:03:46 +0100
    • Engine revision cb3376c5de
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 10FA54AF-3CDB-414B-92B9-9F0D15DA861D • ios • iOS 11.2 (simulator)
```

**Comment by filleduchaos** [comment]
Seems like this example hasn't kept up with the times 😅

**Comment by gedw99** [comment]
Its useful though to see how to do low level stuff to paint to the scene.
I was running it to learn more at this level as i wanted to make a custom 2D and 3D layout thing thats driven from golang and render using flutter

**Comment by filleduchaos** [comment]
Hmmm - I've fixed it, just not raised a PR yet (I'm checking through the rest of the examples first). You can see the necessary changes [here](https://github.com/flutter/flutter/compare/master...filleduchaos:fix_broken_examples)

**Comment by gedw99** [comment]
it was mostly just fmt formatting stuff from the looks of your pr ?

**Comment by gedw99** [comment]
Nice work. I was also thinking about that

**Comment by jonahwilliams** [comment]
I believe this has since been fixed, since I can run it fine on the current master.
