### ISSUE TITLE
Error -32601 received from application: Method not found

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#16950]
## Steps to Reproduce

After updating to Dart 2.0.0-dev.49.0, the following four lines of error was printed out in log. The app run fine though.

## Logs

```dart
I/FlutterActivityDelegate(20521): onResume setting current activity to this
D/EGL_emulation(20521): eglMakeCurrent: 0xa79a8940: ver 2 0 (tinfo 0x95406130)
D/EGL_emulation(20521): eglCreateContext: 0xa79a83a0: maj 2 min 0 rcv 2
D/EGL_emulation(20521): eglMakeCurrent: 0xa79a83a0: ver 2 0 (tinfo 0xa6e7fe10)
D/EGL_emulation(20521): eglMakeCurrent: 0xa79a8940: ver 2 0 (tinfo 0x95406130)
Syncing files to device Android SDK built for x86...
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
I/flutter (20521): App loaded on 2018-04-25 02:42:10.766794
D/        (20521): HostConnection::get() New Host Connection established 0xa979f540, tid 20539
D/EGL_emulation(20521): eglMakeCurrent: 0xa79a83a0: ver 2 0 (tinfo 0xa9783240)
I/zygote  (20521): Do partial code cache collection, code=29KB, data=24KB
I/zygote  (20521): After code cache collection, code=29KB, data=24KB
I/zygote  (20521): Increasing code cache capacity to 128KB
```

Run `flutter analyze` and attach any output of that command also.

```
Analyzing /home/k/dwork/dartsugar...
No issues found!
Ran in 14.7s
```

## Flutter Doctor

```
flutter doctor -v
[✓] Flutter (Channel master, v0.3.6-pre.7, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.6-pre.7 at /home/k/flutter
    • Framework revision 8f03d27fa7 (34 minutes ago), 2018-04-24 19:14:39 -0700
    • Engine revision 6a93ef1c70
    • Dart version 2.0.0-dev.49.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/k/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/k/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/k/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /home/k/opt/ideaIU-2018.1/idea-IU-181.4203.550
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4203.498

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /home/k/opt/idea
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[!] VS Code (version 1.22.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by diego-lipinski-de-castro** [comment]
@zoechi im having this

**Comment by zoechi** [comment]
@diego-lipinski-de-castro 
Please add the output of `flutter doctor -v`
and if possible other information that allows to reproduce or track down the cause.

**Comment by diego-lipinski-de-castro** [comment]
![image](https://user-images.githubusercontent.com/29608698/44151227-5349db34-a078-11e8-8dda-c3e16bc02d3a.png)

unfortunately I dont have the project anymore, I started a new project and It worked, sad I am not able to tell you the cause of the problem now, couldnt figure it out

**Comment by diego-lipinski-de-castro** [comment]
Np, I can tell you I remember I was using fluro for routing, it was a really small attempt to test case flutter, Idk if fluro is the problem but I thought it was worth mentioning

**Comment by eligt** [comment]
For me, this error occurs when using the `android_alarm_manage` plugin. It seems that, the second the Alarm Manager creates an additional thread (so the App bumps to 3 threads) then saving files causes this error. 

Sometimes I get different errors, I'm assuming it depends on the execution point in one of the Isolates. For instance, this is one of those errors:
```
Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///data/user/0/com.package.test/cache/xxxxxxxx/lib/main.dart.incremental.dill, packagesUri: file:///data/user/0/com.package.test/xxxxxxx/.packages, isolateId: isolates/213920045}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Exited (255)
```
Might be somewhat related to this: https://github.com/flutter/flutter/issues/26813

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /media/sw/sdk/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/user/sw/sdk/Android/sdk
    • Android NDK at /home/user/sw/sdk/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/user/sw/sdk/Android/sdk
    • Java binary at: /media/sw/sdk/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /media/sw/sdk/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
@eligt your issue doesn't look related. What made you think it is?

**Comment by zoechi** [comment]
I run into this error when I tried to reproduce https://github.com/flutter/flutter/issues/19903#issuecomment-458278453

**Comment by eligt** [comment]
@zoechi I get the "Error -32601 ... : Method not found" consistently when using the AlarmManager with a .periodic() alarm, once the alarm is triggered at least a second time (therefore the app ends up having a total of 3 or more threads) and I save any file in the app. 

In my prior comment I added a different error which I also occasionally get when saving file whilst the app is running, which hopefully provides more insight into the issue.

**Comment by irwinOT** [comment]
same issue

flutter doctor:

[✓] Flutter (Channel master, v1.4.11-pre.34, on Mac OS X 10.13.6 17G6030, locale
    es-EC)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by kf6gpe** [comment]
@yathit, @irwinOT, is this still an issue with 1.12.13? Do you have a minimal repro we could use to investigate this?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
