### ISSUE TITLE
Navigator pop or maybe pop error with recent flutter update

### ISSUE THREAD

**Issue by artAst** [flutter/flutter#16987]
## Steps to Reproduce

Navigator.pop(context, "CANCEL");

## Logs

E/flutter ( 4523): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 4523): type 'String' is not a subtype of type 'Null' of 'result' where
E/flutter ( 4523):   String is from dart:core
E/flutter ( 4523):   Null is from dart:core
E/flutter ( 4523): 
E/flutter ( 4523): #0      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
E/flutter ( 4523): #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1683:15)
E/flutter ( 4523): #2      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:1648:9)
E/flutter ( 4523): <asynchronous suspension>
E/flutter ( 4523): #3      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1024:34)
E/flutter ( 4523): #4      showMainFrameDialogWithCancel.<anonymous closure> (package:myapp/src/util/ScreenUtils.dart:1334:23)
E/flutter ( 4523): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:490:14)
E/flutter ( 4523): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:545:30)
E/flutter ( 4523): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 4523): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter ( 4523): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter ( 4523): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 4523): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 4523): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 4523): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter ( 4523): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 4523): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 4523): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 4523): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 4523): #18     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter ( 4523): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)

## Flutter Doctor

[✓] Flutter (Channel dev, v0.3.0, on Mac OS X 10.13.4 17E199, locale en-PH)
    • Flutter version 0.3.0 at /Users/macbook/Documents/flutter
    • Framework revision c73b8a7cf6 (13 days ago), 2018-04-12 16:17:26 -0700
    • Engine revision 8a6e64a8ef
    • Dart version 2.0.0-dev.47.0.flutter-4126459025

[!] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK at /Users/macbook/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.17.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by artAst** [comment]
## I updated Flutter:

[✓] Flutter (Channel dev, v0.3.5, on Mac OS X 10.13.4 17E199, locale en-PH)
    • Flutter version 0.3.5 at /Users/macbook/Documents/flutter
    • Framework revision 7ffcd3d22d (2 days ago), 2018-04-24 14:03:41 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK at /Users/macbook/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.17.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

! Doctor found issues in 1 category.

And also force upgrade the packages.
When I tried to run my app, forces to stop
/Users/macbook/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.danceframe.ballroomgo

**Comment by artAst** [comment]
How can I know why it forces the app to stop?
I tried to run --verbose but I can't see any errors

**Comment by artAst** [comment]
Now when I revert back to v0.3.0 its the same issue. I cannot run my project now :(

**Comment by AppleEducate** [comment]
Just started experiencing this

**Comment by artAst** [comment]
Still experiencing this issue with Flutter v0.3.5
any inputs on this for later version releases?

**Comment by AppleEducate** [comment]
@artast in the gallery example it uses a enum for the alert types and expects it in the .Then() part of the function. 

'''
enum DialogDemoAction {
  cancel,
  discard,
  disagree,
  agree,
}
'''

Then present
'''
showDemoDialog<DialogDemoAction>(
                context: context,
                child: new AlertDialog(
                  content: new Text(
                    _alertWithoutTitleText,
                    style: dialogTextStyle
                  ),
                  actions: <Widget>[
                    new FlatButton(
                      child: const Text('CANCEL'),
                      onPressed: () { Navigator.pop(context, DialogDemoAction.cancel); }
                    ),
                    new FlatButton(
                      child: const Text('DISCARD'),
                      onPressed: () { Navigator.pop(context, DialogDemoAction.discard); }
                    )
                  ]
                )
              );
'''

**Comment by artAst** [comment]
It did solve the issue. I also passed in the String object and it works as well. Thanks

This was not present on previous version of flutter with Dart 1.0

**Comment by Hixie** [comment]
The problem is that you said you were returning a Null (the type argument to showDialog), but then you passed a String.

We should definitely make these error messages clear.

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          await showDialog<Null>(
            context: context,
            barrierDismissible: false, // user must tap button!
            child: new AlertDialog(
              title: new Text('Title'),
              content: new SingleChildScrollView(
                child: new ListBody(
                  children: <Widget>[new Text('Message')],
                ),
              ),
              actions: <Widget>[
                new FlatButton(
                  child: new Text('NO'),
                  onPressed: () {
                    //Navigator.pop(context, "CANCEL");
                    Navigator.maybePop(context, "CANCEL");
                  },
                ),
                new FlatButton(
                  child: new Text('YES'),
                  onPressed: () {
                    //Navigator.pop(context, "OK");
                    Navigator.maybePop(context, "CANCEL");
                  },
                ),
              ],
            ),
          ).then((val) {
            return val;
          });
        },
      ),
    );
  }
}


```

</details> 

<details> 
<summary>logs</summary> 

```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Xcode build done.                                           22.6s
Connecting to VM Service at ws://127.0.0.1:51293/mi-GbXBvZG0=/ws
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'String' is not a subtype of type 'Null' of 'result'
#0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
[38;5;244m#1      _RouteEntry.pop[39;49m
[38;5;244m#2      NavigatorState.pop[39;49m
[38;5;244m#3      NavigatorState.maybePop[39;49m
<asynchronous suspension>
[38;5;244m#4      Navigator.maybePop[39;49m
[38;5;248m#5      Home.build.<anonymous closure>.<anonymous closure>[39;49m
[38;5;244m#6      _InkResponseState._handleTap[39;49m
[38;5;244m#7      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244m#8      GestureRecognizer.invokeCallback[39;49m
[38;5;244m#9      TapGestureRecognizer.handleTapUp[39;49m
#10<…>

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 9248fda410 (11 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by asashour** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: const Center(
        child: Text('Hello World'),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () async {

          await showDialog<Null>(
            context: context,
            barrierDismissible: false, // user must tap button!
            builder: (BuildContext context) {
              return AlertDialog(
                title: const Text('Title'),
                content: SingleChildScrollView(
                  child: ListBody(
                    children: const [Text('Message')],
                  ),
                ),
                actions: [
                  TextButton(
                    child: const Text('NO'),
                    onPressed: () {
                      //Navigator.pop(context, "CANCEL");
                      Navigator.maybePop(context, "CANCEL");
                    },
                  ),
                  TextButton(
                    child: const Text('YES'),
                    onPressed: () {
                      //Navigator.pop(context, "OK");
                      Navigator.maybePop(context, "CANCEL");
                    },
                  ),
                ],
              );
            },
          ).then((val) {
            return val;
          });
        },
      ),
    );
  }
}
```
</details>

<details>
<summary>logs</summary>

```
Error: Expected a value of type 'Null', but got one of type 'String'
    at Object.throw_ [as throw] (http://localhost:50113/dart_sdk.js:5063:11)
    at Object.castError (http://localhost:50113/dart_sdk.js:5022:15)
    at Object.cast [as as] (http://localhost:50113/dart_sdk.js:5345:17)
    at Function.as (http://localhost:50113/dart_sdk.js:119378:19)
    at DialogRoute.new.didPop (http://localhost:50113/packages/flutter/src/widgets/widget_inspector.dart.lib.js:14601:18)
    at navigator$._RouteEntry.new.pop (http://localhost:50113/packages/flutter/src/widgets/widget_inspector.dart.lib.js:17279:22)
    at navigator$.NavigatorState.new.pop (http://localhost:50113/packages/flutter/src/widgets/widget_inspector.dart.lib.js:18582:15)
    at navigator$.NavigatorState.new.maybePop (http://localhost:50113/packages/flutter/src/widgets/widget_inspector.dart.lib.js:18562:18)
    at maybePop.next (<anonymous>)
    at http://localhost:50113/dart_sdk.js:37788:33
    at _RootZone.runUnary (http://localhost:50113/dart_sdk.js:37659:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50113/dart_sdk.js:32861:29)
    at handleValueCallback (http://localhost:50113/dart_sdk.js:33413:49)
    at Function._propagateToListeners (http://localhost:50113/dart_sdk.js:33451:17)
    at _Future.new.[_completeWithValue] (http://localhost:50113/dart_sdk.js:33299:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50113/dart_sdk.js:33320:35)
    at Object._microtaskLoop (http://localhost:50113/dart_sdk.js:37926:13)
    at _startMicrotaskLoop (http://localhost:50113/dart_sdk.js:37932:13)
    at http://localhost:50113/dart_sdk.js:33667:9

```
</details>

**Comment by Piinks** [comment]
Not sure if this is still reproducible, we should check.

**Comment by puneetkukreja98** [comment]
I have tested the issue and confirmed it still exists. In ` await showDialog<Null>(`, the return type is set as `Null`, but a `String` is being returned instead `Navigator.maybePop(context, "CANCEL");
`. This type mismatch is what is causing the error.
