### ISSUE TITLE
Flutter Gradle android/Hello_world example fails with studio.

### ISSUE THREAD

**Issue by swapnildavangave** [flutter/flutter#16999]
## Error Log

```
org.gradle.process.internal.ExecException: Process 'command '/home/user/Downloads/flutter/bin/flutter'' finished with non-zero exit value 254
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:188)
	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1086)
	at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1081)
	at org.gradle.api.Project$exec$8.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
```

## Build Logs
```
:app:flutterBuildDebug	1s 900ms
Execute build	1s 861ms
null
Unhandled exception:	
```

### Gradle local.properties contents
```
sdk.dir=/home/user/Android/Sdk
flutter.sdk=/home/user/Downloads/flutter
```

**Comment by mit-mit** [comment]
@swapnildavangave which version of Android Studio are you using?

Also, can you please include the output of `flutter doctor` ?

**Comment by swapnildavangave** [comment]
@mit-mit  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.23.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by swapnildavangave** [comment]
@mit-mit  

Solved .
Android studio needed to be installed. I wasn't aware of that requirement.
Thanks.
