### ISSUE TITLE
flutter run -d flutter-tester quits after 2 frames

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17045]
This is another go at #16963! When running using the `flutter-tester` device it's still quitting while I'm attached to the debugger if I don't hit a breakpoint or something.

To repro run `flutter run -d flutter-tester --start-paused` then connect to observatory and send a resume (or open in browser and type `continue`). The device will quit. Here's the output from the terminal:

```
dantup-macbookpro:flutter_hello_world dantup$ flutter run -d flutter-tester --start-paused
Launching lib/main.dart on Flutter test device in debug mode...
Skipping compilation. Fingerprint match.
Syncing files to device Flutter test device...               2.0s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50967/
For a more detailed help message, press "h". To quit, press "q".
Lost connection to device.
StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:_http/http_impl.dart:537:31)
#1      _StreamSinkImpl.add (dart:_http/http_impl.dart:542:7)
#2      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1203:11)
#3      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#4      VMService._eventMessageHandler (dart:_vmservice:245:16)
#5      VMService._removeClient (dart:_vmservice:219:7)
#6      Client.close (dart:_vmservice/client.dart:37:13)
#7      new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:26:29)
#8      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:477:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

In my real test, I'm using `flutter run -machine` but the results are the same; I trie to ensure the app is still running after 10 seconds (to ensure it was launched correctly), but it's not.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by DanTup** [comment]
Nope, it's good now 👍
