### ISSUE TITLE
Long-pressing text field crashes with "Bad State : No Element"

### ISSUE THREAD

**Issue by Rushabhshroff** [flutter/flutter#17087]
## Steps to Reproduce
I have added a TextField as a child of singleChildScrollView. Max lines for Textfield  is set to null. When I long press it. It throws this error to me. 
## Log
```
I/flutter ( 4955): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4955): The following StateError was thrown building _TextSelectionHandleOverlay(dirty, state:
I/flutter ( 4955): _TextSelectionHandleOverlayState#8ab70):
I/flutter ( 4955): Bad state: No element
I/flutter ( 4955):
I/flutter ( 4955): When the exception was thrown, this was the stack:
I/flutter ( 4955): #0 List.first (dart:core/runtime/libarray.dart:89:5)
I/flutter ( 4955): #1 RenderEditable.getEndpointsForSelection (package:flutter/src/rendering/editable.dart:491:45)
I/flutter ( 4955): #2 _TextSelectionHandleOverlayState.build (package:flutter/src/widgets/text_selection.dart:524:68)
I/flutter ( 4955): #3 StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter ( 4955): #4 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 4955): #5 Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4955): #6 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4955): #7 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4955): #8 ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4955): #9 Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4955): #10 Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4955): #11 SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter ( 4955): #12 Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4955): #13 Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4955): #14 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4955): #15 Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4955): #16 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter ( 4955): #17 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter ( 4955): #18 ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter ( 4955): #19 Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter ( 4955): #20 Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter ( 4955): #21 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4420:32)
I/flutter ( 4955): #22 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
I/flutter ( 4955): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 4955): #24 _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 4955): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter ( 4955): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter ( 4955): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 4955): #28 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 4955): #29 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 4955): #30 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 4955): #31 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4955): #32 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4955): #33 _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 4955): #34 _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 4955): #35 _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 4955): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
I/flutter ( 4955): Another exception was thrown: Bad state: No element
## Flutter Doctor
√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-IN)
    • Flutter version 0.2.8 at D:\Programs\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Cryvis\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\Programs\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at D:\Programs\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at D:\Programs\IntelliJ IDEA Community Edition 2018.1
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.11.2

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

##CODE
```dart
new ConstrainedBox(
                    constraints: new BoxConstraints(
                      minHeight: 0.0,
                      minWidth: 0.0,
                      maxHeight: 70.0,
                    ),
                    child: new Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10.0),
                      margin: const EdgeInsets.all(5.0),
                      decoration: new BoxDecoration(
                          color: Theme.of(context).primaryColorDark,
                          borderRadius: new BorderRadius.circular(10.0),
                          border: Border.all(
                            color: Colors.white30,
                            width: 0.5
                          )
                          ),
                      child: new SingleChildScrollView(
                        reverse: true,
                        child: new TextField(
                          maxLines: null,
                          style: new TextStyle(color: Colors.white,fontSize: 15.0),
                          decoration: new InputDecoration(
                            contentPadding: const EdgeInsets.all(2.0),
                            border: InputBorder.none,
                          ),
                        ),
                      ),
                    ),
                  ),
```
##GIF
https://user-images.githubusercontent.com/32430562/39405517-fafda338-4bc3-11e8-974d-6c4a825e3c3b.gif

**Comment by zoechi** [comment]
Wrapping code in ``` makes it readable

**Comment by jonahwilliams** [comment]
@xster @GaryQian Similar to the other longPress + maxLines:null issues I cannot reproduce, I think this was fixed?

**Comment by xster** [comment]
I haven't experienced this either. Feel free to close if you can't repro.
