### ISSUE TITLE
Failed assertion exception in Flutter Codelab

### ISSUE THREAD

**Issue by PAKalucki** [flutter/flutter#17083]
## Steps to Reproduce

I was following Codelab Building Beautiful UIs with Flutter, part 7 Animate your app. After sending a message in the app I'm getting an Failed assertion exception.

## Logs

flutter run output:
```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.5s
Resolving dependencies...                                    0.5s
Running 'gradlew assembleDebug'...                           1.2s
Built build/app/outputs/apk/debug/app-debug.apk (30.3MB).
I/FlutterActivityDelegate( 5483): onResume setting current activity to this
Syncing files to device Android SDK built for x86...             
D/        ( 5483): HostConnection::get() New Host Connection established 0x9d1aa800, tid 5501
D/EGL_emulation( 5483): eglMakeCurrent: 0x9a8df900: ver 2 0 (tinfo 0x9d1839a0)
D/EGL_emulation( 5483): eglMakeCurrent: 0x9a8df9c0: ver 2 0 (tinfo 0x9a8feff0)

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".
W/IInputConnectionWrapper( 5483): getCursorCapsMode on inactive InputConnection
I/flutter ( 5483): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5483): The following assertion was thrown building SizeTransition(animation: AnimationController#fceb9(▶
I/flutter ( 5483): Infinity)➩Cubic(0.00, 0.00, 0.58, 1.00), dirty, state: _AnimatedState#9b33f):
I/flutter ( 5483): 'package:flutter/src/animation/curves.dart': Failed assertion: line 227 pos 12: 't >= 0.0 && t <=
I/flutter ( 5483): 1.0': is not true.
I/flutter ( 5483): 
I/flutter ( 5483): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5483): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5483): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5483):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5483): 
I/flutter ( 5483): When the exception was thrown, this was the stack:
I/flutter ( 5483): #2      Cubic.transform (package:flutter/src/animation/curves.dart)
I/flutter ( 5483): #3      CurvedAnimation.value (package:flutter/src/animation/animations.dart:417:24)
I/flutter ( 5483): #4      SizeTransition.build (package:flutter/src/widgets/transitions.dart:293:58)
I/flutter ( 5483): #5      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:97:48)
I/flutter ( 5483): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
I/flutter ( 5483): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter ( 5483): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter ( 5483): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter ( 5483): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter ( 5483): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5483): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5483): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5483): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5483): #15     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 5483): #16     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 5483): (elided 2 frames from class _AssertionError)
I/flutter ( 5483): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5483): Another exception was thrown: 'package:flutter/src/animation/curves.dart': Failed assertion: line 227 pos 12: 't >= 0.0 && t <= 1.0': is not true.
I/chatty  ( 5483): uid=10085(u0_a85) ui_thread identical 22 lines
I/flutter ( 5483): Another exception was thrown: 'package:flutter/src/animation/curves.dart': Failed assertion: line 227 pos 12: 't >= 0.0 && t <= 1.0': is not true.
```
Flutter analyze output:
```
Analyzing /home/przemek/workspace/android_projects/flutter_codelab...
No issues found!
Ran in 4.5s
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /home/przemek/flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/przemek/Android/Sdk
    • Android NDK at /home/przemek/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/przemek/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/przemek/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • IntelliJ at /home/przemek/idea-IC
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4006

[✓] VS Code (version 1.22.2)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
There were no other reports. I assume this is stale.
