### ISSUE TITLE
Error in other device

### ISSUE THREAD

**Issue by giovannilima262** [flutter/flutter#17095]
I/flutter (13963): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13963): The following NoSuchMethodError was thrown building BackButton(dirty):
I/flutter (13963): The getter 'backButtonTooltip' was called on null.
I/flutter (13963): Receiver: null
I/flutter (13963): Tried calling: backButtonTooltip
I/flutter (13963): When the exception was thrown, this was the stack:
I/flutter (13963): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
I/flutter (13963): #1      BackButton.build (package:flutter/src/material/back_button.dart:87)
I/flutter (13963): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3687)
I/flutter (13963): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634)
I/flutter (13963): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3487)
I/flutter (13963): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614)
I/flutter (13963): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609)
I/flutter (13963): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
I/flutter (13963): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
I/flutter (13963): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646)
I/flutter (13963): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
I/flutter (13963): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
I/flutter (13963): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645)
I/flutter (13963): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3487)

**Comment by giovannilima262** [comment]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

• No issues found!
