### ISSUE TITLE
SizedBox: render library exception when width or height is null

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#17090]
## The code

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        body: new SizedBox(
            width: 200.0,
            height: null,
            child: new FittedBox(
              fit: BoxFit.contain,
              child: new Image(image: new NetworkImage('http://via.placeholder.com/400x100'))  ,
            )),
      ),
    );
  }
}
```

Documentation says that `width` and `height` can be null. The code above attepts to constrain on the width, letting the height being adjusted automatically. It actually works, but with the following log:

```
I/flutter (28864): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (28864): The following assertion was thrown during performLayout():
I/flutter (28864): 'package:flutter/src/rendering/box.dart': Failed assertion: line 303 pos 12: 'width > 0.0': is not
I/flutter (28864): true.
I/flutter (28864):
I/flutter (28864): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28864): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28864): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28864):   https://github.com/flutter/flutter/issues/new
I/flutter (28864):
I/flutter (28864): When the exception was thrown, this was the stack:
I/flutter (28864): #2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart)
I/flutter (28864): #3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2161:26)
I/flutter (28864): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #5      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
I/flutter (28864): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #7      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (28864): #8      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (28864): #9      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (28864): #10     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (28864): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
I/flutter (28864): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #32     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2712:13)
I/flutter (28864): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #34     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:514:15)
I/flutter (28864): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #36     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2712:13)
I/flutter (28864): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #63     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:514:15)
I/flutter (28864): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #65     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (28864): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28864): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (28864): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (28864): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (28864): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (28864): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627
I/flutter (28864): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.
I/flutter (28864): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (28864): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (28864): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (28864): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (28864): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (28864): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (28864): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (28864):
I/flutter (28864): The following RenderObject was being processed when the exception was fired:
I/flutter (28864):   RenderFittedBox#9e461 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (28864):   creator: FittedBox ← SizedBox ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter (28864):   CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (28864):   _InkFeatures-[GlobalKey#085b2 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (28864):   PhysicalModel ← AnimatedPhysicalModel ← ⋯
I/flutter (28864):   parentData: <none> (can use size)
I/flutter (28864):   constraints: BoxConstraints(w=200.0, 0.0<=h<=592.0)
I/flutter (28864):   size: MISSING
I/flutter (28864):   fit: contain
I/flutter (28864):   alignment: center
I/flutter (28864):   textDirection: ltr
I/flutter (28864): This RenderObject had the following child:
I/flutter (28864):   RenderImage#d80d4 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (28864): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28864): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#9e461 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (28864): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#ece9f relayoutBoundary=up1 NEEDS-PAINT
I/flutter (28864): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#9e461 relayoutBoundary=up2
```

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.1, on Microsoft Windows [Version 10.0.16299.402], locale zh-HK)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[!] Android Studio (version 3.0)
    X Unable to determine bundled Java version.
[√] Android Studio (version 3.1)
[!] Android Studio (version 2.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
[!] VS Code, 64-bit edition (version 1.19.1)
[√] Connected devices (1 available)

! Doctor found issues in 3 categories.
```

**Comment by jacob314** [comment]
Fyi @csells

**Comment by Piinks** [comment]
Initial thoughts, this appears to be an issue of the `FittedBox` needing to know from `SizedBox` what size it is in order to scale and position its child, and `SizedBox` needing to know from `FittedBox` what size it is so it can match its size. 

Playing around a bit with the code, I don't know how this could actually work. Perhaps this is an exception to the documentation and it should be updated to reflect that?
