### ISSUE TITLE
How to design cupertino date picker

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter#17105]
## Steps to Reproduce

I am trying to build cupertino date picker 
I was able to build cupertino picker with single picker like date only 
Now i am trying to build date / month / year together with cupertino picker
i tried putting rows and columns inside of  children property of cupertinopicker but didnt work out
even it tried putting mutiple cupertino picker inside a rows inside of bottomsheet but that also didnt work out.

here is my code : 

https://gist.github.com/jagdishjadeja/112af66ab82106577f7f2b8f0086adef

and 

https://gist.github.com/jagdishjadeja/4f6012317625f5c1cc2fd67474a31b48

## Logs

Here is log when i try to use mulitple cupertino picker inside of row
```
I/flutter (17189): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17189): The following assertion was thrown during performLayout():
I/flutter (17189): BoxConstraints forces an infinite width.
I/flutter (17189): These invalid constraints were provided to RenderDecoratedBox's layout() function by the following
I/flutter (17189): function, which probably computed the invalid constraints in question:
I/flutter (17189):   RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
I/flutter (17189): The offending constraints were:
I/flutter (17189):   BoxConstraints(w=Infinity, h=32.0)
I/flutter (17189):
I/flutter (17189): When the exception was thrown, this was the stack:
I/flutter (17189): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:468:9)
I/flutter (17189): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:509:21)
I/flutter (17189): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:515:6)
I/flutter (17189): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1485:24)
I/flutter (17189): #4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
I/flutter (17189): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (17189): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:514:15)
I/flutter (17189): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (17189): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (17189): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:257:13)
I/flutter (17189): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
I/flutter (17189): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #35     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1107:13)
I/flutter (17189): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #38     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141:11)
I/flutter (17189): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #53     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2712:13)
I/flutter (17189): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #55     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:514:15)
I/flutter (17189): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #57     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (17189): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (17189): #67     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (17189): #68     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (17189): #69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (17189): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (17189): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (17189): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (17189): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17189): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17189): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17189): #77     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17189): #78     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17189): #79     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (17189): (elided one frame from package dart:async)
I/flutter (17189):
I/flutter (17189): The following RenderObject was being processed when the exception was fired:
I/flutter (17189):   RenderConstrainedBox#88ecc relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17189):   creator: ConstrainedBox ← Container ← Column ← IgnorePointer ← Stack ← DecoratedBox ←
I/flutter (17189):   CupertinoPicker ← Row ← MediaQuery ← Padding ← SafeArea ← Listener ← ⋯
I/flutter (17189):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter (17189):   constraints: BoxConstraints(unconstrained)
I/flutter (17189):   size: MISSING
I/flutter (17189):   additionalConstraints: BoxConstraints(w=Infinity, h=32.0)
I/flutter (17189): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (17189):   RenderDecoratedBox#a4f0f NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17189):     RenderPadding#c2ef6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17189): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#88ecc relayoutBoundary=up5
NEEDS-PAINT
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderFlex#45978 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#e71d9 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderStack#7bc33 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#72dee relayoutBoundary=up1 NEEDS-PAINT
I/flutter (17189): Another exception was thrown: RenderBox was not laid out: RenderFlex#df88d NEEDS-PAINT
I/flutter (17189): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null
```

Can someone explain me where i am doing wrong ?

**Comment by b-cancel** [comment]
I had a similar issue a while back, but "BoxConstraints forces an infinite width" describes the problem quite well. 
You need some non infinite Constraint
So whatever container is holding the the pickers needs to have some defined with or height.
You can do this by defining width and height with MediaQuery.of(context).size.width and MediaQuery.of(context).size.height.
Or you can wrap each picker in a Flexible widget and then they will share the available space (which is what I ended up doing)

**Comment by jagdishjadeja** [comment]
it is resolved

**Comment by zoechi** [comment]
Thanks for the update!

**Comment by iLeafSolutionsPvtLtd** [comment]
Bro just make a copy of the original Cupertino class and edit it, Replace BoxConstraints.expand (lin: 269)with just BoxConstraints and give maxHeight and maxWidth
