### ISSUE TITLE
Full restart while setting up flutter_google_map_view example

### ISSUE THREAD

**Issue by salmonella56** [flutter/flutter#17103]
## Steps to Reproduce
```
_/* 
I altered the build.gradle file as indicated in the doc for the sample app.  Note that Properties and GradleException were both flagged red as 'cannot resolve symbol'
/*_

def localProperties = new **Properties**()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new **GradleException**("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.itsthecops.mapexample"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4'
}
```
## Logs
```
Run your application with `flutter run` and attach all the log output.
Performing full restart...
Restarted app in 9,767ms.
E/BpSurfaceComposerClient(11441): Failed to transact (-1)
E/BpSurfaceComposerClient(11441): Failed to transact (-1)
I/FlutterActivityDelegate(11441): onResume setting current activity to this
I/zygote64(11441): Do partial code cache collection, code=29KB, data=26KB
I/zygote64(11441): After code cache collection, code=29KB, data=26KB
I/zygote64(11441): Increasing code cache capacity to 128KB
I/flutter (11441): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (11441): The following assertion was thrown while handling a gesture:
I/flutter (11441): type '_BroadcastSubscription<Location>' is not a subtype of type 'StreamSubscription<Null>' where
I/flutter (11441):   _BroadcastSubscription is from dart:async
I/flutter (11441):   Location is from package:map_view/location.dart
I/flutter (11441):   StreamSubscription is from dart:async
I/flutter (11441):   Null is from dart:core
I/flutter (11441): 
I/flutter (11441): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11441): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11441): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11441):   https://github.com/flutter/flutter/issues/new
I/flutter (11441): 
I/flutter (11441): When the exception was thrown, this was the stack:
I/flutter (11441): #0      _MyAppState.showMap (file:///C:/Users/Ken/AndroidStudioProjects/mapexample/lib/main.dart:116:10)
I/flutter (11441): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
I/flutter (11441): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
I/flutter (11441): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (11441): #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (11441): #5      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
I/flutter (11441): #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (11441): #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (11441): #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (11441): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter (11441): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (11441): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (11441): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (11441): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (11441): #14     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (11441): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (11441): 
I/flutter (11441): Handler: onTap
I/flutter (11441): Recognizer:
I/flutter (11441):   TapGestureRecognizer#58601(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (11441):   Offset(198.6, 202.6), sent tap down)
I/flutter (11441): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/MethodChannel#com.apptreesoftware.map_view(11441): Failed to handle method call
E/MethodChannel#com.apptreesoftware.map_view(11441): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.itsthecops.mapexample/com.apptreesoftware.mapview.MapActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1933)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Activity.startActivity(Activity.java:4806)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.Activity.startActivity(Activity.java:4774)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at com.apptreesoftware.mapview.MapViewPlugin.onMethodCall(MapViewPlugin.kt:117)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#com.apptreesoftware.map_view(11441): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (11441): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (11441): PlatformException(error, Unable to find explicit activity class {com.itsthecops.mapexample/com.apptreesoftware.mapview.MapActivity}; have you declared this activity in your AndroidManifest.xml?, null)
E/flutter (11441): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:544:7)
E/flutter (11441): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (11441): <asynchronous suspension>
E/flutter (11441): #2      MapView.show (package:map_view/map_view.dart:59:14)
E/flutter (11441): #3      _MyAppState.showMap (file:///C:/Users/Ken/AndroidStudioProjects/mapexample/lib/main.dart:98:13)
E/flutter (11441): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (11441): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (11441): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (11441): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (11441): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (11441): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (11441): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (11441): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (11441): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (11441): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (11441): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (11441): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (11441): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (11441): #17     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (11441): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/zygote64(11441): Do partial code cache collection, code=60KB, data=44KB
I/zygote64(11441): After code cache collection, code=60KB, data=44KB
I/zygote64(11441): Increasing code cache capacity to 256KB
Lost connection to device.


C:\Users\Ken>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

C:\Users\Ken>flutter doctor -v
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
    • Flutter version 0.2.8 at C:\Users\Ken\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Ken\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Pixel XL • HT7390202499 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

C:\Users\Ken>flutter analyze
Analyzing C:\Users\Ken...
Unhandled exception:
FileSystemException: Directory listing failed, path = 'C:\Users\Ken\AppData\Local\ElevatedDiagnostics\*' (OS Error: Access is denied.

, errno = 5)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:34)
#1      _Directory.listSync (dart:io/directory_impl.dart:214)
#2      Driver._collectFiles (package:analyzer_cli/src/driver.dart:597)
#3      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:318)
<asynchronous suspension>
#4      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:232)
<asynchronous suspension>
#5      Driver.start (package:analyzer_cli/src/driver.dart:201)
<asynchronous suspension>
#6      main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analyzer_cli/bin/analyzer.dart:13)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
(Ran in 154.4s)

C:\Users\Ken>
## Flutter Doctor

C:\Users\Ken>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

C:\Users\Ken>flutter doctor -v
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
    • Flutter version 0.2.8 at C:\Users\Ken\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Ken\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Pixel XL • HT7390202499 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

C:\Users\Ken>
```

**Comment by Hixie** [comment]
Looks like you're having all kinds of issues. Can you elaborate on exactly which problem you are concerned about?

**Comment by paulsarrias** [comment]
Did you manage to solve this. I am having the same behaviour.

**Comment by zoechi** [comment]
@Illusionist3886 doesn't looks the same from the error output.
This issue is long closed. Please create a new issue with properly filled issue template and all information that you can provide about how to reproduce.
