### ISSUE TITLE
Constructor asserts should be clearer when they throw

### ISSUE THREAD

**Issue by glassp** [flutter/flutter#17125]
### Run
```
I/flutter (18085): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18085): The following assertion was thrown building SettingsUI(dirty):
I/flutter (18085): 'package:flutter/src/material/checkbox.dart': Failed assertion: line 63 pos 15: 'tristate || value
I/flutter (18085): != null': is not true.
I/flutter (18085): 
I/flutter (18085): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18085): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18085): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18085):   https://github.com/flutter/flutter/issues/new
I/flutter (18085): 
I/flutter (18085): When the exception was thrown, this was the stack:
I/flutter (18085): #2      new Checkbox (package:flutter/src/material/checkbox.dart)
I/flutter (18085): #3      new SettingsMap.<anonymous closure> (file:///C:/Users/Pasi/AndroidStudioProjects/car_manager/lib/main.dart:233:19)
I/flutter (18085): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (18085): #5      new SettingsMap (file:///C:/Users/Pasi/AndroidStudioProjects/car_manager/lib/main.dart:231:15)
I/flutter (18085): #6      SettingsUI.build (file:///C:/Users/Pasi/AndroidStudioProjects/car_manager/lib/main.dart:81:26)
I/flutter (18085): #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
I/flutter (18085): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (18085): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (18085): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (18085): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter (18085): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (18085): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter (18085): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
I/flutter (18085): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
I/flutter (18085): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
I/flutter (18085): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
I/flutter (18085): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
I/flutter (18085): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
I/flutter (18085): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (18085): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (18085): #60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
I/flutter (18085): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (18085): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (18085): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (18085): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (18085): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (18085): #67     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (18085): #68     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (18085): #69     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (18085): (elided 3 frames from class _AssertionError and package dart:async)
```
### Analyze
```
  hint - The value of the local variable 'l' isn't used at lib\main.dart:225:9 - unused_local_variable
  hint - Unused import: 'package:flutter/material.dart' at test\widget_test.dart:7:8 - unused_import
  hint - Unused import: 'package:flutter_test/flutter_test.dart' at test\widget_test.dart:8:8 - unused_import
  hint - Unused import: 'package:car_manager/main.dart' at test\widget_test.dart:10:8 - unused_import
```

## Flutter Doctor
```
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale de-DE)
    • Flutter version 0.2.8 at C:\Users\Pasi\Downloads\flutter_windows_v0.2.8-beta\flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Pasi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • HUAWEI VNS L31  • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by HansMuller** [comment]
The log's implication is that a checkbox was created without specifying a true/false value or `tristate: true`. 

If you think there's  a bug in the framework, please provide a small example that demonstrates it.

**Comment by Hixie** [comment]
We should hide the "an error in the framework itself" message for this kind of assert. Maybe if the stack is a constructor in frame 1, non-framework code in frame 2, and the exception is an assert, we can hide that message and add a separate paragraph that talks about what it means to have a constructor assert.

**Comment by duzenko** [comment]
The annoying aspect of this issue is that the assert is in RenderToggleable code while it should really be in e.g. Switch.
This makes it impossible to immediately identify the offending widget from the stack trace.

**Comment by goderbauer** [comment]
This is a bug in the application. As the exception says, tristate may not be null.
