### ISSUE TITLE
Google Signin Issue

### ISSUE THREAD

**Issue by engr-zeeshan** [flutter/flutter#17189]
##
I copied my root folder of project in other drive (removed my ssd and copied project to my hdd) . This was followed by installing packages and flutter upgrade.
Now if i run app, i get gmail accounts list but after selecting account , I am not able to login and proceed

## Error messages
```
 Restarted app in 3,497ms.
[ +292 ms] I/HwPointEventFilter(29919): do not support AFT because of no config
[+2138 ms] I/FlutterActivityDelegate(29919): onResume setting current activity to this
[  +44 ms] E/flutter (29919): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[   +2 ms] E/flutter (29919): PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
[        ] E/flutter (29919): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
[        ] E/flutter (29919): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
[        ] E/flutter (29919): <asynchronous suspension>
[        ] E/flutter (29919): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:156:58)
[   +1 ms] E/flutter (29919): <asynchronous suspension>
[        ] E/flutter (29919): #3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:180:20)
[        ] E/flutter (29919): #4      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:237:43)
[        ] E/flutter (29919): #5      LoginPageState.initState (file:///C:/Users/Muhammad%20Zeeshan/Desktop/cdapp/lib/main.dart:53:19)
[        ] E/flutter (29919): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
[        ] E/flutter (29919): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] E/flutter (29919): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
[        ] E/flutter (29919): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] E/flutter (29919): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] E/flutter (29919): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[        ] E/flutter (29919): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] E/flutter (29919): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
[        ] E/flutter (29919): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
[        ] E/flutter (29919): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
[        ] E/flutter (29919): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
[   +1 ms] E/flutter (29919): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +1 ms] E/flutter (29919): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] E/flutter (29919): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[        ] E/flutter (29919): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
[        ] E/flutter (29919): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] E/flutter (29919): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] E/flutter (29919): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] E/flutter (29919): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[        ] E/flutter (29919): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] E/flutter (29919): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] E/flutter (29919): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] E/flutter (29919): #44     ComponentElement.performRebuild (packag
```

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.1, on Microsoft Windows [Version 10.0.16299.98], locale en-PK)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.22.2)
[√] Connected devices (1 available)

• No issues found!

**Comment by josefigueredo** [comment]
In my case it was a SHA mismatch as said in [https://github.com/flutter/flutter/issues/12819](url)

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

You might need to delete the files and directories that are listed in the various `.gitignore` files (project root directory, `ios/`, `android/`)

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
