### ISSUE TITLE
firebase_core 'await existingApp.options == options': is not true

### ISSUE THREAD

**Issue by patrioticcow** [flutter/flutter#17207]
I have a base app and I added `firebase_core` and `firebase_database`.

I'm setting up some basic config

```dart
Future<void> main() async {
  final FirebaseApp app = await FirebaseApp.configure(
    name: 'test-0909...',
    options: Platform.isIOS
        ? const FirebaseOptions(
            googleAppID: '1:248...',
            gcmSenderID: '248...',
            databaseURL: 'https://est-0909...firebaseio.com',
          )
        : const FirebaseOptions(
            googleAppID: '1:248...',
            apiKey: 'AIza...',
            databaseURL: 'https://est-0909...firebaseio.com',
          ),
  );

  runApp(new MyApp(app: app));
}
```

error:

```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'file:///Users/cristi/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart': Failed assertion: line 70 pos 14: 'await existingApp.options == options': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      FirebaseApp.configure (file:///Users/cristi/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.3/lib/src/firebase_app.dart)
<asynchronous suspension>
#3      main (file:///Users/cristi/Work/delete_me/hello_world/lib/main.dart:10:45)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

If I try to debug the firebase_code file and print
```dart
    print(await existingApp.options);
    print(options);
```
I get

```
flutter: {APIKey: null, bundleID: com.test.test, clientID: null, trackingID: null, GCMSenderID: 248..., projectID: null, androidClientID: null, googleAppID: 1:248..., databaseURL: null, deepLinkURLScheme: null, storageBucket: null}

flutter: {APIKey: null, bundleID: null, clientID: null, trackingID: null, GCMSenderID: 248..., projectID: null, androidClientID: null, googleAppID: 1:248..., databaseURL: https://est-0909...firebaseio.com, deepLinkURLScheme: null, storageBucket: null}
```

Notice that they are no the same. The second one is my configuration. The first one is from.. i don't know where.

I could pass the `bundleID` to my params, but for some reason the `await existingApp.options` doesn't have the `databaseURL`.

Is there a super simple fix for this?

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)
```

**Comment by patrioticcow** [comment]
I read the comments of the config method
```
 /// Configuring the default app is not currently supported. Plugins that
  /// can interact with the default app should configure it automatically at
  /// plugin registration time.
  ///
  /// Changing the options of a configured app is not supported. Reconfiguring
  /// an existing app will assert that the options haven't changed.
```

hmmm....

**Comment by AppleEducate** [comment]
So when using firebase cloud store we cannot hot restart?

**Comment by zoechi** [comment]
> So when using firebase cloud store we cannot hot restart?

How did you derive that?

**Comment by zoechi** [comment]
@patrioticcow sorry for not responding earlier. Is this still an issue?

**Comment by AppleEducate** [comment]
@zoechi Currently using firebase cloud store and testing in the simulator. when you change things related to firestore in the app and hot restart not hot reload, you get this error. I have to rebuild and launch the app to clear it.

**Comment by zoechi** [comment]
@AppleEducate  Can you please add the output of `flutter doctor -v`.

**Comment by AppleEducate** [comment]
```
[✓] Flutter (Channel beta, v0.5.2-pre.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.2-pre.1 at /Users/Shared/CrossMedia/flutter
    • Framework revision 890aef9e76 (7 days ago), 2018-07-17 09:35:34 -0400
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rodydavis/Library/Android/sdk
    • Android NDK at /Users/rodydavis/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (4 available)
    • Pixel              • FA7670303400                             • android-arm64 • Android 8.1.0 (API 27)
    • Rody’s iPhone X 📱 • 68cab38f1e7de5b8aece2a1ebb7ca9a5d4761e19 • ios           • iOS 11.4.1
    • Rody’s iPad        • 90288c0d9ae73afb8a84663c0475d208744fc569 • ios           • iOS 11.4
    • iPhone X           • 77AB621B-E938-42F5-8FDD-2409423C312C     • ios           • iOS 11.4 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by dooboolab** [comment]
I am facing same issue.

**Comment by absin1** [comment]
@dooboolab  One of the issues, VS Code one, seems to be happening because of case mismatch between the plugin name and what flutter checks. Check [18515](https://github.com/flutter/flutter/pull/18515). The other may be because `CocoaPods` seems to be out of date. Check [stackoverflow](https://stackoverflow.com/questions/39481636/updating-to-latest-version-of-cocoapods)

**Comment by dooboolab** [comment]
The problem is resoved when I upgraded flutter. Below is flutter doctor log.
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

Hope above helps.

**Comment by jromero** [comment]
This issue is still occurring.

I've discovered that there are at least two reasons for the discrepancies:

1. `bundleID` is not configured by the user but set internally in the plugin.
```objective-c
[mutableOptionsDict setValue:[[NSBundle mainBundle] bundleIdentifier] forKey:kFIRBundleID];
```
2. `databaseURL` gets returned from the plugin as `databaseUrl` but expected as `databaseURL` (case-sensitivity). 

```dart
databaseURL = map['databaseURL'],
```

**Comment by vijaykanta** [comment]
This problem exists in latest plugin too. Hot restart fails and throws the same error as the OP pointed out. Stop and start is a helluva lengthy process. :(

**Comment by kroikie** [comment]
@patrioticcow

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/838. Any further collaboration will be done there.
