### ISSUE TITLE
In proposed flutter engine roll `flutter build aot` regressed

### ISSUE THREAD

**Issue by aam** [flutter/flutter#17214]
https://github.com/flutter/engine/pull/5155 is the dart sdk roll where flutter build aot fails:
```
$ $FH/flutter/bin/flutter build aot --local-engine android_release -v
...
  +53 ms] Building AOT snapshot in release mode (android_release)...
[   +1 ms] Compiling Dart to kernel: $FH/flutter/examples/flutter_gallery/lib/main.dart
[   +3 ms] $FH/engine/src/out/host_release/dart-sdk/bin/dart $FH/engine/src/out/host_release/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/android_release/flutter_patched_sdk/ --strong --target=flutter --aot --tfa --entry-points $FH/engine/src/out/android_release/dart_entry_points/entry_points.json --entry-points $FH/engine/src/out/android_release/dart_entry_points/entry_points_extra.json --output-dill build/aot/app.dill --depfile build/aot/kernel_compile.d $FH/flutter/examples/flutter_gallery/lib/main.dart
[+19640 ms] compiler message: Unhandled exception:
                    NoSuchMethodError: The method 'toFilePath' was called on null.
                    Receiver: null
                    Tried calling: toFilePath()
                    #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
                    #1      _writeDepfile (package:vm/frontend_server.dart:438)
                    #2      new Future.microtask.<anonymous closure> (dart:async/future.dart:200)
                    #3      _microtaskLoop (dart:async/schedule_microtask.dart:41)
                    #4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
                    #5      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
                    #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

cc @alexmarkov

**Comment by aam** [comment]
https://github.com/dart-lang/sdk/commit/47e90395128ed2744213786ba9fa26281cc92d64 is the culprit for this regression

@mraleph @jensjoha
