### ISSUE TITLE
flutter.bat crashes when launched

### ISSUE THREAD

**Issue by prasannajeet** [flutter/flutter#17235]
**## Steps to Reproduce**

1. Download flutter_windows_v0.3.1-betal.zip
2. Extract
3. Add the flutter\bin to the User Variables "Path"
4. Go to \bin and double click on the flutter.bat file
5. Crashes

**## Logs**

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter 

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: your current branch 'beta' does not have any commits yet

```
#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:235)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      runZoned (dart:async/zone.dart:1501)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:224)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#22     run (package:flutter_tools/runner.dart:49)
#23     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#24     main (file:///C:/Flutterspace/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: your current branch 'beta' does not have any commits yet


#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:256)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:69)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:126)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:189)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#13     _doctorText (package:flutter_tools/runner.dart:188)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:121)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#23     run (package:flutter_tools/runner.dart:49)
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///C:/Flutterspace/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by mit-mit** [comment]
@prasannajeet can you try to double-click `flutter_console.bat` and in there run the command `flutter doctor -v` and share the output of that?

**Comment by mit-mit** [comment]
cc @gspencergoog

**Comment by prasannajeet** [comment]
@mit-mit I could not find the file flutter_console.bat anywhere. Which is why I went to \bin\flutter.bat as I thought it might have been renamed. What would be the exact location of the file inside the "flutter" folder?

**Comment by mit-mit** [comment]
It should be at the root of the flutter folder. Do you not see this?

![image](https://user-images.githubusercontent.com/13644170/39582041-488ec38a-4eed-11e8-8ef0-64f23e58f04d.png)

**Comment by gspencergoog** [comment]
cc @goderbauer

**Comment by prasannajeet** [comment]
I don't. This is what I see :( Even when I double click and open the zip file I don't see the bat file

But I see it when i open the same zip file on my Android phone :(


<img width="277" alt="111" src="https://user-images.githubusercontent.com/3320483/39609323-bfdb6356-4f0d-11e8-8b30-4191bf2370e0.png">

**Comment by goderbauer** [comment]
@prasannajeet What app did you use to unzip?

**Comment by prasannajeet** [comment]
The Windows default option. Right Click and "Extract"

**Comment by goderbauer** [comment]
I just double-checked: When I use Windows' build-in unzipper on my system `flutter_console.bat` gets extracted correctly. It's definitely in the ZIP.

Do you have any kind of virus scanner active that might interrupt the extracting process? You can also try a different unzipper, e.g. 7zip.
