### ISSUE TITLE
`flutter create` dir_path should be able to specified before options.

### ISSUE THREAD

**Issue by polenchheang** [flutter/flutter#17281]
## Steps to Reproduce

1. Run command: `flutter create new_flutter_project --with-driver-test`
2. Eorror Message: 

> Multiple output directories specified.
> Try moving --with-driver-test to be immediately following create
> 

3. Run command: `flutter create --with-driver-test new_flutter_project`
4. new_flutter_project created

## Logs

```
flutter run --verbose
[  +24 ms] [/home/polen/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/home/polen/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/home/polen/Flutter/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/polen/Flutter/flutter/] git log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d820e5f3b1faf5660c1fdcd9b80596701c4c69ed
[        ] [/home/polen/Flutter/flutter/] git log -n 1 --pretty=format:%ar
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 hours ago
[        ] [/home/polen/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.5-113-gd820e5f
[ +122 ms] /home/polen/Android/Sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /home/polen/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] No connected devices.
[  +14 ms] "flutter run" took 103ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:254)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:42)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///home/polen/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
flutter analyze
Analyzing /home/polen/Flutter/WorkSpaces/new_flutter_project...
No issues found!
Ran in 5.9s

```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.3.6-pre.113, on Linux, locale en_GB.UTF-8)
    • Flutter version 0.3.6-pre.113 at /home/polen/Flutter/flutter
    • Framework revision d820e5f3b1 (4 hours ago), 2018-05-03 22:27:29 -0700
    • Engine revision e976be13c5
    • Dart version 2.0.0-dev.53.0.flutter-e6d7d67f4b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/polen/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/polen/Android/Sdk
    • Java binary at: /home/polen/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/polen/Android/android-studio
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.0)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
I don't think this will work well.
`new_flutter_project` is an optional command and they can only be on the end as far as I know.
To allow `--with-driver-test` at the end, the directory would need an option like
```
flutter create --directory=new_flutter_project --with-driver-test
```
or perhaps
```
flutter create -dnew_flutter_project --with-driver-test
```

/cc @Hixie

**Comment by polenchheang** [comment]
Hi @zoechi , This may not an issue if `flutter create --help` give a clear message on where the folder name would be.
Currently, it show `Usage: flutter create <output directory>`, It should show `Usage: flutter create [ options | arguments ] <output directory>` .

**Comment by jonahwilliams** [comment]
This is an issue with package:args, not with the flutter tool

**Comment by jmagman** [comment]
@tvolkert Do you know who has permissions to move this to https://github.com/dart-lang/args/issues?

**Comment by dnfield** [comment]
@polenchheang the tool uses package:args to parse command line arguments, which doesn't support this today.  We don't plan to migrate away from args to support this. It would be best to file an issue in package args that is more general than this one (the link that @jmagman  provided) to be able to place optional arguments in such a way.

Since the tool has no intention of migrating away from package args and we don't plan to fix package args to do this ourselves, I'm going to close this here.  I'm not sure it has much value to track in this repo at this point.
