### ISSUE TITLE
command line flutter doctor run error

### ISSUE THREAD

**Issue by thitoo** [flutter/flutter#17291]
## exception
```
VersionCheckError: VersionCheckError: Command exited with code 1: git log -n 1 --pretty=format:%ad --date=iso
Standard error: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
```

```
#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:235)
<asynchronous suspension>
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      runZoned (dart:async/zone.dart:1501)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:224)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#22     run (package:flutter_tools/runner.dart:49)
#23     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#24     main (file:///Volumes/DataDrive/development/flutter_sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 1: git log -n 1 --pretty=format:%ad --date=iso
Standard error: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.


#0      _runSync (package:flutter_tools/src/version.dart:439)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:256)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:69)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:126)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:189)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#13     _doctorText (package:flutter_tools/runner.dart:188)
<asynchronous suspension>
#14     _createLocalCrashReport (package:flutter_tools/runner.dart:166)
<asynchronous suspension>
#15     _handleToolError (package:flutter_tools/runner.dart:121)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:58)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#23     run (package:flutter_tools/runner.dart:49)
#24     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#25     main (file:///Volumes/DataDrive/development/flutter_sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
