### ISSUE TITLE
error when hot reload

### ISSUE THREAD

**Issue by wzhtc** [flutter/flutter#17338]
I was following the [Flutter Challenge](https://github.com/matthew-carroll/flutter_ui_challenge_music_player) and got this error when try to hot reload.

> Performing hot reload...
> flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> flutter: The following assertion was thrown building RadialProgressBar(state: _RadialProgressBarState#c68e1):
> flutter: Failed assertion: boolean expression must not be null
> flutter:
> flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
> flutter: more information in this error message to help you determine and fix the underlying cause.
> flutter: In either case, please report this assertion by filing a bug on GitHub:
> flutter:   https://github.com/flutter/flutter/issues/new
> flutter:
> flutter: When the exception was thrown, this was the stack:
> flutter: #0      _RenderCustomClip.clipper= (package:flutter/src/rendering/proxy_box.dart)
> flutter: #1      ClipOval.updateRenderObject (package:flutter/src/widgets/basic.dart:581:18)
> flutter: #2      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4280:12)
> flutter: #3      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4651:11)
> flutter: #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #5      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4371:32)
> flutter: #52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
> flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #62     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4371:32)
> flutter: #63     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
> flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #95     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #99     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #113    StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #119    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4371:32)
> flutter: #120    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
> flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #124    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> Reloaded 0 of 393 libraries in 447ms.
> flutter: #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #142    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #146    StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #149    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #150    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #152    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #156    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #161    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #162    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
> flutter: #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #166    StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
> flutter: #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #168    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
> flutter: #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #172    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
> flutter: #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
> flutter: #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
> flutter: #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
> flutter: #176    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
> flutter: #177    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
> flutter: #178    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
> flutter: #179    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
> flutter: #180    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
> flutter: #181    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
> flutter: #183    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
> flutter: #184    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
> flutter: #185    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
> flutter: (elided one frame from package dart:async)
> flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Xgamefactory** [comment]
Hi we got same error. You have closed issue, did you find solution ?

**Comment by Xgamefactory** [comment]
The solution is https://github.com/flutter/flutter/issues/20983#issuecomment-415715785
