### ISSUE TITLE
Error on inspection

### ISSUE THREAD

**Issue by kdaker** [flutter/flutter#17339]
getting the following error when trying to inspect the view using the Flutter Inspector in Android Studio.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Banner("DEBUG", textDirection: ltr, location: topEnd,
Color(0xa0b71c1c), text inherit: true, text color: Color(0xffffffff), text size: 10.2, text weight:
900, text height: 1.0x):
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 547 pos 12:
'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#51     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#71     StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#77     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4362:32)
#78     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4752:17)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#82     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#87     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#96     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#104    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#114    ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#120    StatefulElement.update (package:flutter/src/widgets/framework.dart:3782:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#124    StatelessElement.update (package:flutter/src/widgets/framework.dart:3685:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4644:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#130    ProxyElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#134    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#140    _invoke (dart:ui/hooks.dart:120:13)
#141    _drawFrame (dart:ui/hooks.dart:109:3)
(elided 2 frames from class _AssertionError)
```

## Steps to reproduce

1. Start flutter application
2. Open new screen using `Navigator.push` 
3. Click 'Toggle select widget mode' in Flutter Inspector

## Logs

```
$ flutter doctor                                                                                                                           [18:34:20]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[!] VS Code (version 1.21.0)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

```
$ flutter analyze
flutter analyze                                                                                                                          [18:34:28]
Analyzing /Users/me/Projects/collections_flutter...
  hint • The value of the local variable 'result' isn't used at test/service/collections_service_test.dart:60:11 • unused_local_variable
1 issue found.
(Ran in 5.4s)
```

**Comment by etheodor42** [comment]
Same for me

**Comment by zoechi** [comment]
@etheodor42 there is not enough information available to reproduce and investigate.
This issue is long closed. Please create a new issue with a properly filled out issue template and if possible a minimal runnable reproduction.

**Comment by iBotasky** [comment]
I got same issue in this enviorment:
```
Flutter 1.1.3-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7ecef3aa27 (4 hours ago) • 2018-12-17 15:56:26 -0800
Engine • revision 5af435098d
Tools • Dart 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)
```
the flutter plugin version on AndroidStudio is:`31.3.1`

**Comment by zoechi** [comment]
@iBotasky please check you don't nest multiple `MaterialApp` widgets.

**Comment by iBotasky** [comment]
@zoechi 
Yeah, there are multi `MaterialApp` widget. Now the inspection works fine. Thanks.

**Comment by fabryx92** [comment]
Is there no way to have the Inspector working with nested `MaterialApp` widgets?
