### ISSUE TITLE
Example App for Flutter platform swift crashes on start

### ISSUE THREAD

**Issue by aditya2kx** [flutter/flutter#17340]
Stack Trace:
```
Launching lib/main.dart on iPhone X in debug mode...
Skipping compilation. Fingerprint match.
Running Xcode clean...
Starting Xcode build...
Xcode build done.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder:
flutter: type '(PlatformException) => void' is not a subtype of type '(Object) => FutureOr<dynamic>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #3      new _ControllerSubscription (dart:async/stream_controller.dart)
flutter: #4      new _BroadcastSubscription (dart:async/broadcast_stream_controller.dart)
flutter: #8      _PlatformChannelState.initState (file:///Users/adi2ky/Documents/Workspace/flutter/examples/platform_channel_swift/lib/main.dart:40:43)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4751:32)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #76     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #80     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #89     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #117    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #127    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4751:32)
flutter: #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #130    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
flutter: #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #143    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
Syncing files to device iPhone X...
flutter: #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #146    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #151    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #152    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #156    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #159    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #163    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #165    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #175    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #205    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #210    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #211    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #214    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #216    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #220    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #222    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #223    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #224    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #225    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #227    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #229    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #230    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #231    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #232    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #233    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #235    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #236    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #237    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #239    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #241    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #242    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #243    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #244    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #245    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #247    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #248    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #249    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #250    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #251    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #252    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #254    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #255    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #256    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #257    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #258    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #260    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #261    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #262    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #263    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #264    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #265    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #266    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
flutter: #267    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
flutter: #268    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
flutter: #269    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
flutter: #270    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
flutter: #271    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
flutter: #272    runApp (package:flutter/src/widgets/binding.dart:704:7)
flutter: #273    main (file:///Users/adi2ky/Documents/Workspace/flutter/examples/platform_channel_swift/lib/main.dart:83:3)
flutter: #274    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
flutter: #275    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided 6 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: type '(PlatformException) => void' is not a subtype of type '(Object) => FutureOr<dynamic>'
flutter: Another exception was thrown: type '(PlatformException) => void' is not a subtype of type '(Object) => FutureOr<dynamic>'
```

**Comment by aditya2kx** [comment]
```
C02TV23GHTDD-lm:fantasy-ios adi2ky$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.13.4 17E199, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✗] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.4)
[✓] Connected devices (2 available)

! Doctor found issues in 2 categories.
```

Doing the iOS development, so lacking android modules should be fine.

**Comment by zoechi** [comment]
Do you have the newest versions of all dependencies?
Can you try if you can reproduce with `dev` and `master` channel?

**Comment by aditya2kx** [comment]
yep just tried, happens on all channels.
