### ISSUE TITLE
Correct way to update local dependencies ?

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#17353]
I have a local dependency. If I make changes to the local dependency - how do I tell flutter to get a new version ?

    keyboard:
      path: ../../dart/kbml_parser

My flutter project is in Android Studio, my dart project is in Intellij.

I tried :
1. "Packages get" in the pubspec.yaml
2. "Packages upgrade" in the pubspec.yaml
3. (Pubspec has been edited) "Get dependencies" from the flutter file
4. (Pubspec has been edited) "Upgrade dependencies" from the flutter file

None of these had any effect.
I tried increasing the version number in the pubspec.yaml in the dart project to 1.0.0, and "Packages Upgrade :

    keyboard: ^1.0.0
      path: ../../dart/kbml_parser

But I get the error :

    /work/installs/flutter/bin/flutter --no-color packages upgrade
    Running "flutter packages upgrade" in kbml_viewer...
    Error on line 14, column 9 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
        path: ../../dart/kbml_parser
            ^
    pub upgrade failed (65)
    Process finished with exit code 65

I finally got it to work with File > "Invalidate Caches / Restart..."

Is this the recommended way? It seems heavy handed since it restarts all my Android Studio instances.

**Comment by Rockvole** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.3.5, on Linux, locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[!] VS Code (version 1.22.2)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

https://github.com/dart-lang/sdk/issues/33062

**Comment by zoechi** [comment]
There is no need to do anything.

>  Mapping values are not allowed here. Did you miss a colon earlier?
    path: ../../dart/kbml_parser

seems to indicate that there is an error in your `pubspec.yaml` formatting.

**Comment by Rockvole** [comment]
I think it is telling me I am not allowed to add version numbers for packages which are local relative ?
I added the version number to see if that would allow me to "upgrade" and so find the changes.

My question is whether the only way to pick up local dependency changes is to invalidate caches in Android studio ? That was the only thing which worked, but it is quite heavy handed. I will have to do that many times per day since I am developing these in parallel.

**Comment by zoechi** [comment]
You don't need to do anything to get changes from local dependencies.
There can be only one version of a local dependency (at least for `path` dependencies), therefore adding a version number is invalid.

If your local dependency is specified as `git` dependency in `pubspec.yaml`, then you can use tags to link to a specific version.
  
Recently many run into an issue where they needed to run `flutter clean` for changes to take effect (but also for changes in application code, not only in dependencies). 
You could try if that helps.

**Comment by Rockvole** [comment]
<code>flutter clean</code> doesnt help.

    flutter clean
    Deleting 'build/'.
Now try running my code :

    compiler message: Unhandled exception:
    compiler message: FileSystemException: Cannot open file, path = 'build/app.dill' (OS Error: No such file or directory, errno = 2)
    compiler message: #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:351)
    compiler message: #1      _RootZone.runUnary (dart:async/zone.dart:1381)
    compiler message: #2      _FutureListener.handleValue (dart:async/future_impl.dart:129)
    compiler message: #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
    compiler message: #4      Future._propagateToListeners (dart:async/future_impl.dart:666)
    compiler message: #5      Future._completeWithValue (dart:async/future_impl.dart:481)
    compiler message: #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:511)
    compiler message: #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
    compiler message: #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    compiler message: #9      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
    compiler message: #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
    Unhandled exception:
    SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
    #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
    #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #3      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
    #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

Maybe we need <code>flutter invalidatecaches</code> :)

**Comment by zoechi** [comment]
There are no caches beside `build/` and `flutter clean` deletes that. Your issue comes from something else.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by Rockvole** [comment]
I still do invalidate caches to pick up my local changes - seems heavy handed, sometimes I am doing that 30 times a day. I haven't found another way that works.

**Comment by zoechi** [comment]
I also use local path dependencies and never had such an issue with IntelliJ.
No idea what could cause this.

**Comment by zoechi** [comment]
Why are you using IntelliJ and AndroidStudio together in the same project. 
In Regard to Flutter there is no difference between these two as far as I know.
You could even open both within the same window.

**Comment by Rockvole** [comment]
I prefer to use 2 independent IDEs. When you have 2 different projects in android studio / intellij they behave like one ide with 2 different views. So you get crossover in projects that have nothing to do with each other. Like opening a dialog means you cant open a dialog in the other project. You cant have a search open and look at the other project. Quite irritating.

Also, with the dart project in Intellij (which does not have the flutter plugin). I cannot accidentally introduce flutter remnants (like data types) - so the dart project can be included in the flutter project or run on the server (it parses an xml language) - for example if I want a web front-end for it (quite likely).

**Comment by zoechi** [comment]
Makes sense and shouldn't cause issues. Just looking for cues.

**Comment by Rockvole** [comment]
Yes, it should not cause issues since its the same as downloading a plugin repo locally and refer to it from flutter, and then keep pulling the new changes. I do that pretty regularly (although not 30 times a day).
Would cause a lot of confusion and wasted time when the changes are not taking effect.

**Comment by zoechi** [comment]
Do you still see this?
I think this should be moved to flutter/flutter-intellij

**Comment by zoechi** [comment]
Sounds great! Thanks for the update.
Feel free to reopen if you run into it again.

**Comment by zoechi** [comment]
@bhammer88 what do you expect to happen? What do you mean with "change"?

**Comment by dark-chocolate** [comment]
Does `flutter update` update all the local dependency? 
For instance, I have `firebase_admob:  0.7.0` in my `pubspec.yaml` and now say there is new version available (say 0.7.1), so if I do `flutter update`, will this dependency gets updated? 

If no, then which command can help me to do that without me having to update every dependency on manually?

**Comment by zoechi** [comment]
@dark-chocolate I assume you mean `flutter packages upgrade`.
`firebase_admob: 0.7.0` is **not** a local dependency, it's a hosted dependency - hosted on the (or a) pub server. A local dependency is a dependency stored on your machine that you reference with a file path like shown in the initial comment

```
keyboard:
  path: ../../dart/kbml_parser
```

For local dependencies referenced with `path` there is nothing to do. They are always up-to-date automatically.

`flutter packages upgrade` upgrades within the limits of the version constraints of the dependency in `pubspec.yaml`. (see for example https://stackoverflow.com/questions/53742443/in-the-flutter-what-is-best-way-to-add-package-in-pubspec-yaml-file/53742552#53742552 for more details)

If more than one of your dependencies have a shared transitive dependency, where one of them depends on an older version of the shared transitive dependency, this might hold `flutter packages upgrade` back in upgrading the dependency to the newest version as well.

**Comment by zoechi** [comment]
@dark-chocolate Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by dark-chocolate** [comment]
I am really sorry, I didn't know there is support channel, next time I'll use it. Thank you for you help, and sorry for putting question here.

**Comment by crcaicedo** [comment]
Same problem and same solution: invalidates cache & restart

_flutter clean_ not working in this specific case.

Not always, most of the times, changes are immediate but need hard restarting sometimes.

**Comment by patelkrunal78** [comment]
Similar To [how to use local flutter package in another flutter application?](https://icetutor.com/question/how-to-use-local-flutter-package-in-another-flutter-application)

**Comment by milanpatel18** [comment]
locate this file in your flutter application => pubspec.yaml

make local dependency

dependencies:
flutter:
sdk: flutter
my_new_package:
path: ./my_new_package

Founded At [Here](https://icetutor.com/question/how-to-use-local-flutter-package-in-another-flutter-application)

**Comment by eliaweiss** [comment]
I actually had to restart Android Studio to solve this.

**Comment by ben-lotze** [comment]
Try deleting the package-folder from the git cache in the flutter sdk directory:
flutter/.pub-cache/git
flutter/.pub-cache/git/cache

If this works, place the path in your file manager's favorites somewhere. Much faster than restarting.

This was the only thing that helped for me. flutter clean, restarting AndroidStudio and invalidating caches all did not work.
In my case this may have to do with the fact that I changed the pubspec.yaml from using a local path to a git url and later back to a local path. I don't knonw why, but before that, it always worked.
