### ISSUE TITLE
Not descriptive error message

### ISSUE THREAD

**Issue by nkoroste** [flutter/flutter#17371]
Following the Flutter code-lab, [step 6](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..%2Findex#5)

Follow IDE suggestions I forgot to copy the context in the following code snippet:
```Dart
  void _pushSaved() {
    Navigator.of(context).push(
        new MaterialPageRoute(
            builder: (BuildContext context) {
              final Iterable<ListTile> tiles = _saved.map((WordPair pair) {
                return new ListTile(
                  title: new Text (
                    pair.asPascalCase,
                    style: _biggerFont,
                  ),
                );
              });
              final List<Widget> divided = ListTile.divideTiles(
                  tiles: tiles,
                  // context: context // <---------- forgot this line which caused the error
              ).toList();

              return new Scaffold(
                  appBar: new AppBar(title: const Text("Saved Suggestions"),
                  ),
                  body: new ListView(children: divided,)
              );
            }
        )
    );
  }
```

Got the following error:
```
I/flutter ( 5149): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5149): The following assertion was thrown building Builder(dirty):
I/flutter ( 5149): 'package:flutter/src/material/list_tile.dart': Failed assertion: line 286 pos 12: 'color != null ||
I/flutter ( 5149): context != null': is not true.
I/flutter ( 5149): 
I/flutter ( 5149): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5149): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5149): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5149):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5149): 
I/flutter ( 5149): When the exception was thrown, this was the stack:
I/flutter ( 5149): #2      ListTile.divideTiles (package:flutter/src/material/list_tile.dart)
I/flutter ( 5149): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
I/flutter ( 5149): #4      new List.from (dart:core/runtime/libarray_patch.dart:58:17)
I/flutter ( 5149): #5      Iterable.toList (dart:core/iterable.dart:413:16)
I/flutter ( 5149): #6      RandomWordsState._pushSaved.<anonymous closure> (file:///usr/local/google/home/nkorsote/src/android-testing/ui/espresso/startup_namer/lib/main.dart:75:17)
I/flutter ( 5149): #7      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:157:14)
I/flutter ( 5149): #8      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:497:43)
I/flutter ( 5149): #9      Builder.build (package:flutter/src/widgets/basic.dart:5279:41)
I/flutter ( 5149): #10     StatelessElement.build (package:flutter/src/widgets/framework.dart:3687:28)
I/flutter ( 5149): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter ( 5149): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 5149): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 5149): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 5149): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #74     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 5149): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 5149): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 5149): #93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 5149): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 5149): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 5149): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 5149): #97     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4429:32)
I/flutter ( 5149): #98     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
I/flutter ( 5149): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #100    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 5149): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #104    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter ( 5149): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #108    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
I/flutter ( 5149): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 5149): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter ( 5149): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 5149): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 5149): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 5149): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 5149): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 5149): #122    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter ( 5149): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 5149): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5149): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5149): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5149): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5149): #128    _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 5149): #129    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 5149): (elided 2 frames from class _AssertionError)
I/flutter ( 5149): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by HansMuller** [comment]
Given the error, this seems like a pretty reasonable message.  What would have been better?

**Comment by zoechi** [comment]
Closing due to inactivity.
