### ISSUE TITLE
Assertion bug

### ISSUE THREAD

**Issue by efidje** [flutter/flutter#17382]
Problems with building a simple project in VS code. Below is the dump from the terminal.

```
Initializing gradle...
Built build\app\outputs\apk\debug\app-debug.apk (30.3MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(27844): onResume setting current activity to this
Syncing files to device A701...
I/flutter (27844): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27844): The following assertion was thrown building HomePage(dirty):
I/flutter (27844): 'package:flutter/src/widgets/basic.dart': Failed assertion: line 1682 pos 15: 'constraints != null':
I/flutter (27844): is not true.
I/flutter (27844): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (27844): more information in this error message to help you determine and fix the underlying cause.
I/flutter (27844): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (27844):   https://github.com/flutter/flutter/issues/new
I/flutter (27844): When the exception was thrown, this was the stack:
I/flutter (27844): #2      new ConstrainedBox (package:flutter/src/widgets/basic.dart)
I/flutter (27844): #3      HomePage.build (file:///C:/Users/Endre/App-projects/Flutter_test/Flutter_drawer/flutter_draw/lib/main.dart:26:18)
I/flutter (27844): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
I/flutter (27844): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
I/flutter (27844): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #74     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #96     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4742:32)
I/flutter (27844): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #99     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter (27844): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #105    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #144    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4637:14)
I/flutter (27844): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #193    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #198    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #210    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #214    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #216    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #218    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #225    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #226    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #227    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #229    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #230    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #231    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
I/flutter (27844): #232    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #233    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #234    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
I/flutter (27844): #236    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
I/flutter (27844): #237    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
I/flutter (27844): #238    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
I/flutter (27844): #239    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
I/flutter (27844): #240    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
I/flutter (27844): #241    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:852:16)
I/flutter (27844): #242    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:823:5)
I/flutter (27844): #243    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:769:17)
I/flutter (27844): #244    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter (27844): #245    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:768:13)
I/flutter (27844): #246    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:657:7)
I/flutter (27844): #247    runApp (package:flutter/src/widgets/binding.dart:699:7)
I/flutter (27844): #248    main (file:///C:/Users/Endre/App-projects/Flutter_test/Flutter_drawer/flutter_draw/lib/main.dart:4:16)
I/flutter (27844): #249    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (27844): #250    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (27844): (elided 2 frames from class _AssertionError)
I/flutter (27844): ════════════════════════════════════════════════════════════════════════════════════════════════════

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on A701 is available at: http://127.0.0.1:8101/
For a more detailed help message, press "h". To quit, press "q".
D/dalvikvm(27844): GC_EXPLICIT freed 224K, 6% free 4598K/4864K, paused 8ms+4ms, total 47ms
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`
and the code that allows to reproduce.

**Comment by zoechi** [comment]
Closing due to inactivity
