### ISSUE TITLE
Assertion "type 'int' is not a subtype of type 'String'" in performLayout()

### ISSUE THREAD

**Issue by mrmax99** [flutter/flutter#17500]
Filing this issue because the assertion asked me to.

Adding this function (I think) led to the below error:

```
Widget _buildListItem(BuildContext context, DocumentSnapshot document) {
    //return new Text(" online count: ${document['count']} -- local count: $_counter");
    return new ListTile(
      key: new ValueKey(document.documentID),
      title: new Container(
        decoration: new BoxDecoration(
          border: new Border.all(color: Colors.deepOrange),
          borderRadius: new BorderRadius.circular(5.0),
        ),
        padding: const EdgeInsets.all(10.0),
        child: new Row(
          children: <Widget>[
            new Expanded(child: new Text(document['count'],)),
            new Text("local: $_counter")
          ],
        )
      ),
      onTap: () => Firestore.instance.runTransaction((transaction) async {
        DocumentSnapshot freshSnap = await transaction.get(document.reference);
        await transaction.update(freshSnap.reference, {'count': freshSnap['count'] + 1});
      }),
    );
  }
```

I was roughly following this tutorial:
https://codelabs.developers.google.com/codelabs/flutter-firebase/#9

========================================

I/flutter ( 5277): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5277): The following assertion was thrown during performLayout():
I/flutter ( 5277): type 'int' is not a subtype of type 'String' where
I/flutter ( 5277):   int is from dart:core
I/flutter ( 5277):   String is from dart:core
I/flutter ( 5277):
I/flutter ( 5277): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5277): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5277): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5277):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5277):
I/flutter ( 5277): When the exception was thrown, this was the stack:
I/flutter ( 5277): #0      _MyHomePageState._buildListItem (******lib/main.dart:55:50)
I/flutter ( 5277): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (******lib/main.dart:90:15)
I/flutter ( 5277): #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197:20)
I/flutter ( 5277): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716:67)
I/flutter ( 5277): #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter ( 5277): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716:26)
I/flutter ( 5277): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:55)
I/flutter ( 5277): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
I/flutter ( 5277): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter ( 5277): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter ( 5277): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter ( 5277): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter ( 5277): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter ( 5277): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter ( 5277): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351:5)
I/flutter ( 5277): #15     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:169:12)
I/flutter ( 5277): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 5277): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
I/flutter ( 5277): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
I/flutter ( 5277): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
I/flutter ( 5277): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter ( 5277): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5277): #39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 5277): #40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter ( 5277): #41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 5277): #42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 5277): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 5277): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 5277): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 5277): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 5277): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5277): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5277): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5277): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5277): #51     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 5277): #52     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 5277):
I/flutter ( 5277): The following RenderObject was being processed when the exception was fired:
I/flutter ( 5277):   RenderSliverFixedExtentList#bde56 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5277):   creator: SliverFixedExtentList ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter ( 5277):   IgnorePointer-[GlobalKey#61729] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 5277):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#6cc51] ←
I/flutter ( 5277):   _ExcludableScrollSemantics-[GlobalKey#aa973] ← RepaintBoundary ← CustomPaint ← ⋯
I/flutter ( 5277):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter ( 5277):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 5277):   scrollOffset: 0.0, remainingPaintExtent: 593.4, crossAxisExtent: 411.4, crossAxisDirection:
I/flutter ( 5277):   AxisDirection.right, viewportMainAxisExtent: 603.4)
I/flutter ( 5277):   geometry: null
I/flutter ( 5277):   no children current live
I/flutter ( 5277): This RenderObject has no descendants.
I/flutter ( 5277): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5277): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 5277): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 5277): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

**Comment by mrmax99** [comment]
I figured it out, sorry.
document['count'] was a number, not a string.
