### ISSUE TITLE
updateQuest called with no from

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1751]
I was in accessibility mode, and I two-finger dragged down.

```
-- EXCEPTION CAUGHT BY SCHEDULER LIBRARY -------------------------------
An exception was raised during a scheduler callback:
The null object does not have a getter 'settings'.
NoSuchMethodError: method not found: 'settings'
Receiver: null
Arguments: []
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      HeroController._getMostValuableKeys (widgets/heroes.dart:495)
#3      HeroController._updateQuest (widgets/heroes.dart:503)
#4      BindingBase&Scheduler.invokeFrameCallback (scheduler/scheduler.dart:270)
#5      BindingBase&Scheduler.handleBeginFrame (scheduler/scheduler.dart:253)
#6      _beginFrame (sky/bindings/hooks.dart:48)
------------------------------------------------------------------------
```

**Comment by Hixie** [comment]
Just hit the same again without accessibility: I was just alternatively hitting "Weathers" and the "<-" back arrow continually at high speed and suddenly boom.

**Comment by Hixie** [comment]
In both cases I was using a release binary mode, no-checked mode.

**Comment by HansMuller** [comment]
This code path doesn't exist anymore, see https://github.com/flutter/flutter/pull/8112
