### ISSUE TITLE
AnimatedBuilder exception doesn't provide enough information to tell the programmer why it failed

### ISSUE THREAD

**Issue by joelfaul** [flutter/flutter#17581]
I received this exception when trying to grab a reference to one of the newly created objects in a Column widget. In listed each of the Column's children, I used the line 'musicPlayer = new MusicPlayer()' instead of just 'new MusicPlayer' for one of the children. Once I took out the 'musicPlayer =' portion, the exception did not occur.

I'm reporting this only because the exception said I should, presumably because the exception should provide more info.
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building AnimatedBuilder-[<CSTHomeTab.firstTab>](animation:
flutter: Listenable.merge([TextEditingController#2714a(TextEditingValue(text: ┤├, selection:
flutter: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional:
flutter: false), composing: TextRange(start: -1, end: -1))), null]), dirty, state: _AnimatedState#f42e0):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1648 pos 14:
flutter: '!children.any((Widget child) => child == null)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart)
flutter: #3      new Flex (package:flutter/src/widgets/basic.dart)
flutter: #4      new Column (package:flutter/src/widgets/basic.dart)
flutter: #5      CSTHomeState._buildPlaybackListTab.<anonymous closure> (file:///Users/joel/AndroidStudioProjects/music_experiment/lib/homepage.dart:299:22)
flutter: #6      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:634:12)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
