### ISSUE TITLE
FloatingActionButton.extended causes RenderFlex errors

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#17583]
![screenshot](https://user-images.githubusercontent.com/19204050/40023983-1a163090-57cd-11e8-9879-1a7356ee30b0.png)

I am using a the ActionButton like this

```
Scaffold(
  floatingActionButton: FloatingActionButton.extended(
    label: Container(width: 60.0,),
    icon: Icon(Icons.done),
    onPressed: () {},
  ),
)
```

Changing the `Container` to a `Text` widget does not change anything, I only did this to better visualize the issue. When I navigate to a page with a Scaffold (this will animate the FAB) the following error is thrown and also when just opening the route on app start.

```
I/flutter ( 3032): The following assertion was thrown during a scheduler callback:
I/flutter ( 3032): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 322 pos 12: '() {
I/flutter ( 3032):       final Animation<double> initial = initialManifest.animation;
I/flutter ( 3032):       switch (initialManifest.type) {
I/flutter ( 3032):         case _HeroFlightType.pop:
I/flutter ( 3032):           return initial.value == 1.0 && initial.status == AnimationStatus.reverse;
I/flutter ( 3032):         case _HeroFlightType.push:
I/flutter ( 3032):           return initial.value == 0.0 && initial.status == AnimationStatus.forward;
I/flutter ( 3032):       }
I/flutter ( 3032):     }()': is not true.
I/flutter ( 3032): 
I/flutter ( 3032): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3032): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3032): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3032):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3032): 
I/flutter ( 3032): When the exception was thrown, this was the stack:
I/flutter ( 3032): #2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart)
I/flutter ( 3032): #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:532:64)
I/flutter ( 3032): #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
I/flutter ( 3032): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3032): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter ( 3032): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3032): #9      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3032): #10     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3032): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3032): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 3032): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/        ( 3032): HostConnection::get() New Host Connection established 0xc92fe040, tid 3057
D/EGL_emulation( 3032): eglMakeCurrent: 0xe847de40: ver 3 0 (tinfo 0xe0c15ab0)
I/flutter ( 3032): Another exception was thrown: A RenderFlex overflowed by 62 pixels on the right.
```

**Comment by HansMuller** [comment]
Can you provide a complete example that demonstrates the problem you've run into?

**Comment by creativecreatorormaybenot** [comment]
Trying to recreate it I realised that for me it only occurs when using it in a `MaterialPageRoute` within the `onGenerateRoute` parameter in a `MaterialApp`. I think that this issue thus should be closed and I should dig into the problem based on that. @HansMuller

**Comment by js1972** [comment]
Can this be re-opened? I have noticed that you get these renderflex errors whenever you leave the default hero behaviour. If you set hero `heroTag: null` the issue goes away.

i.e.
```
floatingActionButton: FloatingActionButton.extended(
        onPressed: _createNotification,
        icon: Icon(Icons.add),
        label: const Text('New'),
        heroTag: null,
      ),
```
where createNotification navigates to a new screen. Upon navigating back (pop) you get the RenderFlex errors unless you null out the hero.
