### ISSUE TITLE
Flutter Gallery example crashes from user input

### ISSUE THREAD

**Issue by phat-sumo** [flutter/flutter#17598]
![flutter_crash](https://user-images.githubusercontent.com/14286025/40038443-5fa4cc0a-57cf-11e8-964a-0b33ee150663.png)
I was evaluating using Flutter with the Flutter Gallery for look / feel before using it when I found this bug.

Flutter crashes in the 'Studies' > 'Contact Profile' section after rapidly scrolling up / down and repeatedly selecting an app bar option from the menu in the upper right-hand corner.

The stack trace from the flutter command line app is as follows:

```
I/flutter (31551): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (31551): The following NoSuchMethodError was thrown while dispatching notifications for ValueNotifier<bool>:
I/flutter (31551): The method 'stop' was called on null.
I/flutter (31551): Receiver: null
I/flutter (31551): Tried calling: stop(canceled: true)
I/flutter (31551):
I/flutter (31551): When the exception was thrown, this was the stack:
I/flutter (31551): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
I/flutter (31551): #1      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:499:13)
I/flutter (31551): #2      RenderSliverFloatingPersistentHeader.maybeStopSnapAnimation (package:flutter/src/rendering/sliver_persistent_header.dart:457:18)
I/flutter (31551): #3      _FloatingAppBarState._isScrollingListener (package:flutter/src/material/app_bar.dart:548:15)
I/flutter (31551): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:161:21)
I/flutter (31551): #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:217:5)
I/flutter (31551): #6      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:583:25)
I/flutter (31551): #7      ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:122:11)
I/flutter (31551): #8      ScrollPositionWithSingleContext.drag (package:flutter/src/widgets/scroll_position_with_single_context.dart:250:5)
I/flutter (31551): #9      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:443:22)
I/flutter (31551): #10     DragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:169:47)
I/flutter (31551): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (31551): #12     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:169:9)
I/flutter (31551): #13     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
I/flutter (31551): #14     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
I/flutter (31551): (elided 2 frames from package dart:async)
I/flutter (31551):
I/flutter (31551): The ValueNotifier<bool> sending notification was:
I/flutter (31551):   ValueNotifier<bool>#152a4(true)
I/flutter (31551): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31551): Another exception was thrown: AnimationController.dispose() called more than once.
I/flutter (31551): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (31551): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (31551): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4681 pos 12: 'renderObject.child == child': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4681 pos 12: 'renderObject.child == child': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4062 pos 14: '() {
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2240 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3681 pos 12: 'child == _child': is not true.
I/flutter (31551): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3681 pos 12: 'child == _child': is not true.
I/flutter (31551): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3681 pos 12: 'child == _child': is not true.
I/flutter (31551): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/FlutterActivityDelegate(31551): onResume setting current activity to this
I/OpenGLRenderer(31551): Initialized EGL, version 1.4
D/OpenGLRenderer(31551): Swap behavior 1
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3681 pos 12: 'child == _child': is not true.
I/flutter (31551): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/FlutterActivityDelegate(31551): onResume setting current activity to this
I/FlutterActivityDelegate(31551): onResume setting current activity to this
I/OpenGLRenderer(31551): Initialized EGL, version 1.4
D/OpenGLRenderer(31551): Swap behavior 1
I/flutter (31551): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3681 pos 12: 'child == _child': is not true.
I/flutter (31551): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

Is this an issue that's only possible due to the nature of the example changing the app bar behavior? This bug can also be found in the version of the example found in the Google Play store (I found it first there, then installed via github to produce a stack trace). Bug was found on version 0.4.2 on a Nexus 6P.

**Comment by phat-sumo** [comment]
Okay, I actually just uploaded the video to vimeo [here](https://vimeo.com/269916224) - it may take a minute to finish encoding.

**Comment by zoechi** [comment]
Same exception in #19582

**Comment by HansMuller** [comment]
This was a difficult problem to track down.

This test case can be used to demonstrate the bug: https://gist.github.com/HansMuller/c78f6798d8bb15a5aa81622a5d97e104. Scroll the green content upwards a little (compresses the app bar). Then press the `snap=false` button, and then scroll upwards a little more.

The source of the problem is in `set snapConfiguration` in RenderSliverFloatingPersistentHeader:
```
...
if (value == null) {
  _controller?.dispose();
} else {
  ...
}
```

The _controller var should be set to null in this case (as it is in the detach method) so that if the maybeStopAnimation method is called, it will quietly do nothing:
```
void maybeStopSnapAnimation(ScrollDirection direction) {
  _controller?.stop();
}
```

Will upload a fix shortly.
