### ISSUE TITLE
I get this error when my Timer calls a function that requests server data

### ISSUE THREAD

**Issue by aidaspleckaitis** [flutter/flutter#17605]
```
The following assertion was thrown building SettingsPage(dirty, state: SettingsPageState#0681f):
I/flutter ( 9826): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 482 pos 15: 'value == null ||
I/flutter ( 9826): items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.

Stack trace:

I/flutter ( 9826): #2      new DropdownButton (package:flutter/src/material/dropdown.dart)
I/flutter ( 9826): #3      SettingsPageState.build (file:///home/aidas/Flutter/map_task/lib/settingsPage.dart:100:21)
I/flutter ( 9826): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
I/flutter ( 9826): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter ( 9826): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 9826): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter ( 9826): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 9826): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9826): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9826): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9826): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9826): #13     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 9826): #14     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 9826): (elided 2 frames from class _AssertionError)
```

**Comment by aidaspleckaitis** [comment]
I'm a junior so am certain that there is a problem in my code and the way i am approaching this.
The thing i want to do is that i want to refresh only my token in example every 10 minutes and get a new one.

My code: (I took out the sensitive data so don't mind the empty strings)

`
import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

import './main.dart';

class SettingsPage extends StatefulWidget {
  @override
  SettingsPageState createState() => new SettingsPageState();
}

class SettingsPageState extends State<SettingsPage> {

  var getRequest;
  var postRequest;
  var response;
  var token;
  var email;

  final String postUrl = '';
  final String getUrl = '';

  String countrieValue;
  List<String> dataConvertedToJSON;
  List<String> listOfCountries = [];

  Future<String> handleData() async {
    postRequest = await http.post(
      Uri.encodeFull(postUrl),
      body: {'username': '', 'password': ''});

    token = json.decode(postRequest.body)['token'];

    getRequest = await http.get(
      Uri.encodeFull(getUrl),
      headers: {'X-AUTH-TOKEN': '$token'});

    response = json.decode(getRequest.body);

    for (var i = 0; i < response.length; i++) {
     listOfCountries.add(response[i]['countryName']);
    }
    print(listOfCountries);
    setState(() {
      dataConvertedToJSON = listOfCountries;
      countrieValue = dataConvertedToJSON.elementAt(0);      
    });

    print('TOKEN: $token');

    return "Success!";
  }
  
  

  @override
  void initState() {
    super.initState();
    Timer.periodic(Duration(seconds: 10), (Timer timer) => this.handleData());
  }
  
  void onChanged(String value) {
    setState(() {
      countrieValue = value;      
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Theme(
        data: themeData,
        child: new Scaffold(
            appBar: new AppBar(
              title: new Text('SETTINGS',
                  textAlign: TextAlign.center,
                  style: new TextStyle(
                      color: Colors.grey[200],
                      fontWeight: FontWeight.w300,
                      fontSize: 18.0)),
            ),
            body: Container(
              alignment: Alignment.topCenter,
              margin: const EdgeInsets.only(top: 60.0),
              child: new Column(
                children: <Widget>[
                  
                  new Padding(
                    padding: const EdgeInsets.all(25.0),
                    child: Text('Select language', style: TextStyle(
                      fontSize: 18.0,
                      color: Colors.grey[200],
                      fontWeight: FontWeight.w300,
                    ),),
                  ),
                  dataConvertedToJSON != null ?
                    DropdownButton(
                      style: TextStyle(color: Colors.lightGreenAccent),
                        elevation: 8,
                        value: countrieValue,
                        items: dataConvertedToJSON.map((String value) {
                          return DropdownMenuItem(
                            value: value,
                            child: Text('$value'));
                          }).toList(), 
                        onChanged: (String value) {
                          onChanged(value);
                    })
                  : CircularProgressIndicator(backgroundColor: Colors.lime,)
                ],
              ),
            )));
  }
}

`

**Comment by zoechi** [comment]
I'm not able to spot the value, but at some point when `build()` is run, `contrieValue` contains a value not contained in `dataConvertedToJSON` which I think is what the error message points out.

**Comment by zoechi** [comment]
Debug the code where you create the `DropDownButton`. Set breakpoints or print the values of `countrieValue` and `dataConvertedToJSON` and check if there are inconsistencies.

**Comment by zoechi** [comment]
Closing due to inactivity.

**Comment by IRiS-SK2** [comment]
@aidaspleckaitis  Did you manage to find a workaround for this? I'm having the same problem and I want to send requests in the timer callback
