### ISSUE TITLE
TextField/TextFormField reset issue work-around PR generating errors

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#17621]
In reference to the issue #11500 where TextFormFields are reseting when you scroll, on an attempt to use the work around in PR #15484 I'm getting the following errors.

Above in my State class..
```dart
final List<TextEditingController> _controllers = new List.generate(25, (int n) {
    return new TextEditingController();
```

One of my TextFormField's:
```dart
new TextFormField(
  decoration: const InputDecoration(
    icon: const Icon(Icons.computer),
    labelText: 'FTP Host',
  ),
  validator: _validateField,
  initialValue: user.ftpHost,
  keyboardType: TextInputType.url,
  onSaved: (String value) {
    user.ftpHost = value;
  },
  controller: _controllers[0],
)
```

I keep getting 
```
'package:flutter/src/material/text_form_field.dart': Failed assertion: line 72 pos 15: 'initialValue == null || controller == null': is not true.
```
Exception
```
I/flutter ( 8385): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8385): The following assertion was thrown building Settings(dirty, state: SettingsState#47968):
I/flutter ( 8385): 'package:flutter/src/material/text_form_field.dart': Failed assertion: line 72 pos 15: 'initialValue
I/flutter ( 8385): == null || controller == null': is not true.
I/flutter ( 8385): 
I/flutter ( 8385): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8385): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8385): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8385):   https://github.com/flutter/flutter/issues/new
I/flutter ( 8385): 
I/flutter ( 8385): When the exception was thrown, this was the stack:
I/flutter ( 8385): #2      new TextFormField (package:flutter/src/material/text_form_field.dart)
I/flutter ( 8385): #3      SettingsState.build (package:maxanet_uploader/pages/settings.dart:103:21)
I/flutter ( 8385): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
I/flutter ( 8385): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter ( 8385): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 8385): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter ( 8385): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 8385): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 8385): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8385): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8385): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8385): #13     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 8385): #14     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 8385): (elided 2 frames from class _AssertionError)
I/flutter ( 8385): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by acidjazz** [comment]
I have found a different solution thanks to @Mahender-Prayuta , I'll keep this issue open though since the PR still produces these errors.

```dart
...
body: new Form(
  key: _formKey,
  child: new Container(
    padding: new EdgeInsets.symmetric(horizontal: 30.0, vertical: 30.0),
    child: SingleChildScrollView(
      child: new Column(
        children: <Widget>[
          new TextFormField(
            decoration: const InputDecoration(
              icon: const Icon(Icons.computer),
              labelText: 'FTP Host',
            ),
            validator: _validateField,
            initialValue: user.ftpHost,
            keyboardType: TextInputType.url,
            onSaved: (String value) {
              user.ftpHost = value;
            },
          ),
          new TextFormField(
            decoration: const InputDecoration(
              icon: const Icon(Icons.account_box),
              labelText: 'FTP Username',
            ),
            validator: _validateField,
            initialValue: user.ftpUsername,
            keyboardType: TextInputType.url,
            onSaved: (String value) {
              user.ftpUsername = value;
            },
          ),
...
```

**Comment by zoechi** [comment]
@acidjazz did @Atlantis-lcc 's suggestion solve your issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by mohamedHassanKa** [comment]
any solution guys i got this probleme too

**Comment by adesolaadegboye** [comment]
You cannot have InitialValue and controller you have to delete one of them

**Comment by kevin-haynie** [comment]
I too have this problem and the only way I can make it work is to use a SingleChildScrollView with child as a column as mohamedHassanKa suggests....  This does need to get fixed as my customers are losing their form data.  

I'm using Flutter 1.8.3 with framework from 2019-7-27 and engine revision 38ac5f30a7 using iOS app.

**Comment by neenabastin123** [comment]
Is there any fix for this issue? My TextField is inside Listview (dynamically creating TextFields) and when I enter any input and scrolled the value is not persisiting, I cannot use SingleChildScrollView as I am using SliverList, is there any solution yet?
