### ISSUE TITLE
Curved Animation exception

### ISSUE THREAD

**Issue by vinbhai4u** [flutter/flutter#17641]
## Steps to Reproduce

https://github.com/vinbhai4u/flutter_social_app/blob/master/lib/bottom_data_widget.dart
I create a Animation and it works perfectly. But when I change to CurvedAnimation its throws the below exception

![simulator screen shot - iphone 6s - 2018-05-16 at 13 07 38](https://user-images.githubusercontent.com/1851565/40104558-525483b6-590e-11e8-88ab-32c473a3458e.png)

```
//buttonAnimation is a CurvedAnimation
buttonAnimation = new Tween(
      begin: 120.0,
      end: 40.0,
    ).animate(
      new CurvedAnimation(
        parent: buttonAnimationController,
        curve: Curves.easeIn,
      ),
    )..addListener(() {
        setState(() {});
      });
```

```
//working code
//buttonAnimation is a Animation
buttonAnimation = new Tween(
      begin: 120.0,
      end: 40.0,
    ).animate(buttonAnimationController)
      ..addListener(() {
        setState(() {});
      });
```

## Logs

```
flutter: #544    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
flutter: #545    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
flutter: #546    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
flutter: #547    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
flutter: #548    runApp (package:flutter/src/widgets/binding.dart:704:7)
flutter: #549    main (file:///CommonFiles/Development/Vineeth/Git/flutter_social_app/lib/main.dart:8:16)
flutter: #550    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
flutter: #551    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderFlex overflowed by 99795 pixels on the right.
```

```
[✓] Flutter (Channel master, v0.4.5-pre.21, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.5-pre.21 at /CommonFiles/Development/flutter
    • Framework revision f38743593d (5 hours ago), 2018-05-15 19:37:21 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • iPhone 6s • A8F263A3-36D0-4CA1-A459-2E2543C7A678 • ios • iOS 11.3 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
Is this still an issue?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
