### ISSUE TITLE
Keyword new is sometimes not optional anyway

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#17644]
I recently removed all occurrences of `new` from the `google_maps_flutter` plugin and example app. When launching the example from Android Studio, I get:
```
05-16 10:16:11.621 10447-10492/io.flutter.plugins.googlemapsexample E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    NoSuchMethodError: Attempted to use type 'MapUiPage' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the MapUiPage constructor and forget the 'new' operator?
    Receiver: MapUiPage
    Tried calling: MapUiPage()
    #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
    #1      _allPages (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:14)
    #2      _allPages (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:13)
    #3      main (file:///Users/mravn/github/plugins/packages/google_maps_flutter/example/lib/main.dart:48)
    #4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
Works fine with `flutter run` from a terminal.

## Flutter doctor output

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.4.5-pre.15, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.5-pre.15 at /Users/mravn/github/flutter
    • Framework revision 9115b1841a (45 minutes ago), 2018-05-16 11:34:30 +0200
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Android NDK at /Users/mravn/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.1.2
    • Dart plugin version 181.4668.60

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by mravn-google** [comment]
cc @devoncarew

**Comment by alardizabal** [comment]
We recently removed `new` from the Hamilton project and can confirm that the above issue happens in Android Studio. No issues with iOS.

**Comment by mravn-google** [comment]
Workaround: add 
```
preview-dart-2=true
```
to the Android project's `gradle.properties` file.
