### ISSUE TITLE
"Error: No pubspec.yaml file found" When project located in OneDrive

### ISSUE THREAD

**Issue by Duchynko** [flutter/flutter#17650]
Today I moved my projects to OneDrive and can't run any of them. Found out that someone had similar problem and Windows reinstall worked. However that's not perfect solution for me.

## Steps to Reproduce

1. Move project directory into OneDrive
2. Run project

Also tried to run from cmd as administrator, same output

## Logs

```
[  +40 ms] [C:\Users\jakub\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +85 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[   +1 ms] [C:\Users\jakub\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] [C:\Users\jakub\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Users\jakub\flutter\] git log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f9bb4289e9fd861d70ae78bcc3a042ef1b35cc9d
[        ] [C:\Users\jakub\flutter\] git log -n 1 --pretty=format:%ar
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 days ago
[   +2 ms] [C:\Users\jakub\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +48 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.4.4-0-gf9bb4289e
[ +157 ms] "flutter run" took 31ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:427)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:251)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#31     main (file:///C:/Users/jakub/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

     _Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue._

```
Running "flutter packages get" in task_07_backdrop...        9.1s
Analyzing task_07_backdrop...
Error response from the server: SERVER_ERROR NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileSystemState.hasUri (package:analyzer/src/dart/analysis/file_state.dart:894)
#2      AnalysisDriver.addFile (package:analyzer/src/dart/analysis/driver.dart:526)
#3      ServerContextManagerCallbacks.applyChangesToContext.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1333)
#4      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#5      ServerContextManagerCallbacks.applyChangesToContext (package:analysis_server/src/analysis_server.dart:1332)
#6      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1200)
#7      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:757)
#8      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:894)
#9      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:340)
#10     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:265)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1490)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1134)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1134)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#56     _rootRunUnary (dart:async/zone.dart:1138)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

Error from the analysis server: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\jakub\OneDrive - ViaUC\src\udacity_flutter\udacity-course\cour
se\07_backdrop\task_07_backdrop], excluded: []}}
FileSystemException: Exists failed, path = 'C:\Users\jakub\OneDrive - ViaUC\src\udacity_flutter\udacity-course\course\07_backdrop\task_07_backdrop\.idea\task_07_backdrop.iml___jb_old___' (OS E
rror: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157)
#6      _rootRun (dart:async/zone.dart:1122)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      _CustomZone.runGuarded (dart:async/zone.dart:925)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#14     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#15     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

Flutter doctor is okay

**Comment by darylrue** [comment]
Same problem

**Comment by zoechi** [comment]
Can you provide any information that would allow us to reproduce?

**Comment by vishalbasnet23** [comment]
If anyone is still facing the issue. I got it resolved on my arch Linux by:
1. Run package remove command.
2. Remove /opt/flutter by sudo rm -rf /opt/flutter
3. Install it again from AUR.
4. change the flutter directory ownership to your user by sudo chown -R $USER /opt/flutter
5. run flutter upgrade.
6. run flutter doctor.
7. Done.

I hope this helps.
