### ISSUE TITLE
flutter bug

### ISSUE THREAD

**Issue by kimailis** [flutter/flutter#17695]
```
 #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart)
I/flutter ( 3176): #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1232:7)
I/flutter ( 3176): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2588:11)
I/flutter ( 3176): #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:128:13)
I/flutter ( 3176): #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1077:11)
I/flutter ( 3176): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2583:7)
I/flutter ( 3176): #8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4661:18)
I/flutter ( 3176): #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4505:35)
I/flutter ( 3176): #10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2966:5)
I/flutter ( 3176): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2891:18)
I/flutter ( 3176): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 3176): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4751:32)
I/flutter ( 3176): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 3176): #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 3176): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 3176): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 3176): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 3176): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 3176): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 3176): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 3176): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 3176): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 3176): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 3176): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 3176): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 3176): #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 3176): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 3176): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 3176): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 3176): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 3176): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 3176): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter ( 3176): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 3176): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #69     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
I/flutter ( 3176): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 3176): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter ( 3176): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #79     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
I/flutter ( 3176): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
I/flutter ( 3176): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #85     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
I/flutter ( 3176): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
I/flutter ( 3176): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 3176): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 3176): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
I/flutter ( 3176): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 3176): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 3176): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3176): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3176): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3176): #96     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3176): #97     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3176): #98     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3176): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 3176): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3176): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
I/flutter ( 3176): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 102 pos 12: '_owner != null': is not true.
```

**Comment by zoechi** [comment]
How to reproduce?
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
