### ISSUE TITLE
Updated AppBar action button during validate callback in TextFormField

### ISSUE THREAD

**Issue by shujames** [flutter/flutter#17704]
Requirement: 
When TextFormField validate callback detects an error, update the AppBar in the Scaffold to disable an action button. 
I was trying to call setState in the validate callback to trigger another widget.build() call. Unfortunately I get "setState() or markNeedsBuild() called during build." error. 

What is the correct way to do this behavior. 

I am doing a work around by attaching an onChange callback inside a Form widget that wraps the TextFormField. Call validate() on the TextFormField's FormState and setState that way. 

Since Form is not required for TextFormField, this doesn't seem like the correct way of doing this.

**Comment by johnfesa** [comment]
Asked another way, how do you idiomatically set a button to be enabled/disabled based on form validation? Form could probably use an onValidated callback to accomplish this.

**Comment by jklint-g** [comment]
Does `scheduleMicrotask(() => setState(() {...}))` work for you? That would move the execution of setState out of the middle of the current build call. Not sure if it's the best solution.

**Comment by tvolkert** [comment]
@robertoscaramuzzi reminder to sync up with @HansMuller on this

**Comment by mehmetf** [comment]
@robertoscaramuzzi @DaveShuckerow Please sync up and see if there's a leafy solution to this since afaicr, they did not run into this issue due to putting the entire scaffold inside their form.

**Comment by DaveShuckerow** [comment]
@robertoscaramuzzi and I discussed this. The Leafy approach doesn't use Flutter's Form at all, which means that this issue, which depends on the internal behavior of the FormState, doesn't apply to the Leafy design.  It also means that the Leafy approach can't be quickly adopted in Mulligan.

The underlying problem is that the formfields' validator() callbacks are invoked during build, and so if they contain a setState() call, they will crash.  This is done here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/form.dart#L112

The form calls every validator it contains as part of its build process when it auto-validates.

Short-term, the resolution to this is to schedule the setState() calls for after build is completed.  One approach is to use scheduleMicrotask() to wrap all setState() calls in validators.  The other approach is the one that Mulligan has used.

On Flutter's side, I think we should consider if there is a way we can streamline the Form's logic so that it does not call validator() callbacks during build.  I imagine a common use case for our forms is to update some state based on whether or not a field is valid or if the whole form is valid.  When we make calls to validator() during build, that use case becomes difficult for users to manage.

**Comment by pedromassangocode** [comment]
Found in `1.21.0-1.0.pre`.

<details>
<summary> Complete sample code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _enabledButton = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.security),
            onPressed: _enabledButton ? () {} : null,
          )
        ],
      ),
      body: Center(
        child: TextFormField(
          autovalidate: true,
          validator: (v) {
            if(!v.contains('@')) {
              if (_enabledButton) {
                setState(() => _enabledButton = false);
              }
              return 'invalid email';
            }
            setState(() => _enabledButton = true);
            return null;
          },
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> Logs</summary>

```
W/IInputConnectionWrapper( 4908): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4908): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4908): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4908): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4908): endBatchEdit on inactive InputConnection

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building TextFormField(dirty, dependencies: [_LocalizationsScope-[GlobalKey#a29a0], _InheritedTheme], state: _TextFormFieldState#fd7d9):
setState() or markNeedsBuild() called during build.

This MyApp widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: MyApp
  state: _MyAppState#f980e
The widget which was currently being built when the offending call was made was: TextFormField
  dirty
  dependencies: [_LocalizationsScope-[GlobalKey#a29a0], _InheritedTheme]
  state: _TextFormFieldState#fd7d9
The relevant error-causing widget was: 
  TextFormField file:///Users/pedro/dev/projects/hello_flutter/lib/main.dart:26:16
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4167:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4182:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1253:14)
#3      _MyAppState.build.<anonymous closure> (package:hello_flutter/main.dart:35:13)
#4      FormFieldState._validate (package:flutter/src/widgets/form.dart:392:36)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (8 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (2 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
Verified using latest versions and issue reported is replicable.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _enabledButton = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.security),
            onPressed: _enabledButton ? () {} : null,
          )
        ],
      ),
      body: Center(
        child: TextFormField(
          autovalidateMode: AutovalidateMode.always,
          validator: (v) {
            if(!v!.contains('@')) {
              if (_enabledButton) {
                setState(() => _enabledButton = false);
              }
              return 'invalid email';
            }
            setState(() => _enabledButton = true);
            return null;
          },
        ),
      ),
    );
  }
}

```

</details>

<details>
<summary> log </summary>

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building TextFormField(dirty, dependencies: [UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#8212a]], state: _TextFormFieldState#6fefa):
setState() or markNeedsBuild() called during build.

This MyApp widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: MyApp
  state: _MyAppState#57d19
The widget which was currently being built when the offending call was made was: TextFormField
  dirty
  dependencies: [UnmanagedRestorationScope, _InheritedTheme, _LocalizationsScope-[GlobalKey#8212a]]
  state: _TextFormFieldState#6fefa
The relevant error-causing widget was: 
  TextFormField TextFormField:file:///Users/dhs/Documents/NCFlutter/test_app/lib/main.dart:26:16
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4634:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4646:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1153:15)
#3      _MyAppState.build.<anonymous closure> (package:test_app/main.dart:35:13)
#4      FormFieldState._validate (package:flutter/src/widgets/form.dart:448:43)
#5      FormFieldState.build (package:flutter/src/widgets/form.dart:499:11)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:21)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1275:15)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204:9)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1062:5)
#16     _invoke (dart:ui/hooks.dart:145:13)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#18     _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.3.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (10 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.5.0-12.0.pre.45, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.45 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c2edb20f3d (53 minutes ago), 2022-10-31 21:18:37 -0700
    • Engine revision f721db653d
    • Dart version 2.19.0 (build 2.19.0-356.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by justinmc** [comment]
From above in https://github.com/flutter/flutter/issues/17704#issuecomment-398911428:

 >  I think we should consider if there is a way we can streamline the Form's logic so that it does not call validator() callbacks during build.

I agree with that. We probably shouldn't be calling `validate` inside of the build method here:

https://github.com/flutter/flutter/blob/557a959547258f6edb912fae552d606c93ac8052/packages/flutter/lib/src/widgets/form.dart#L272-L275
