### ISSUE TITLE
Error inside InputDecoration when using labelText and border together

### ISSUE THREAD

**Issue by rafaelcb21** [flutter/flutter#17710]
Below is a fairly simple code, however a rather strange error is occurring.

When using the `labelText` and `border` keys as shown in the code below the following error occurs. Only when using only `labelText` or only `border` the error does not happen.

The error appears when I execute the command:
`flutter run --release`

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new InputDecorator(
        decoration: new InputDecoration(
          labelText: 'XP',
          border: OutlineInputBorder()
        ),
      )
    );
  }
}
```
**Error**

```
Initializing gradle...
Launching lib/main.dart on Redmi Note 4X in release mode...
Running 'gradlew assembleRelease'...
Built build/app/outputs/apk/release/app-release.apk (8.0MB).
Installing build/app/outputs/apk/app.apk...

To repeat this help message, press "h". To quit, press "q".
I/FlutterActivityDelegate( 2431): onResume setting current activity to this
I/flutter ( 2431): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 2431): The following ArgumentError was thrown during performLayout():
I/flutter ( 2431): Invalid argument(s): 0.0
I/flutter ( 2431): When the exception was thrown, this was the stack:
I/flutter ( 2431): #0      _Double.clamp (dart:core/runtime/libdouble.dart:143)
I/flutter ( 2431): #1      TextPainter.layout (package:flutter/src/painting/text_painter.dart:384)
I/flutter ( 2431): #2      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:179)
I/flutter ( 2431): #3      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:183)
I/flutter ( 2431): #4      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:249)
I/flutter ( 2431): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #8      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:776)
I/flutter ( 2431): #9      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:891)
I/flutter ( 2431): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #11     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141)
I/flutter ( 2431): #12     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399)
I/flutter ( 2431): #13     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211)
I/flutter ( 2431): #14     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355)
I/flutter ( 2431): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1141)
I/flutter ( 2431): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #36     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2712)
I/flutter ( 2431): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:514)
I/flutter ( 2431): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #40     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107)
I/flutter ( 2431): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570)
I/flutter ( 2431): #48     RenderView.performLayout (package:flutter/src/rendering/view.dart:125)
I/flutter ( 2431): #49     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445)
I/flutter ( 2431): #50     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709)
I/flutter ( 2431): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270)
I/flutter ( 2431): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627)
I/flutter ( 2431): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter ( 2431): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter ( 2431): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter ( 2431): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751)
I/flutter ( 2431): #58     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
I/flutter ( 2431): #59     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
I/flutter ( 2431): #60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
I/flutter ( 2431): (elided one frame from package dart:async)
I/flutter ( 2431): The following RenderObject was being processed when the exception was fired:
I/flutter ( 2431):   RenderParagraph#2f369 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 2431):   parentData: <none>
I/flutter ( 2431):   constraints: BoxConstraints(0.0<=w<=-24.0, h=0.0; NOT NORMALIZED)
I/flutter ( 2431):   size: MISSING
I/flutter ( 2431):   textAlign: start
I/flutter ( 2431):   textDirection: ltr
I/flutter ( 2431):   softWrap: wrapping at box width
I/flutter ( 2431):   overflow: ellipsis
I/flutter ( 2431):   maxLines: unlimited
I/flutter ( 2431): This RenderObject has no descendants.
I/flutter ( 2431): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2431): Another exception was thrown: NoSuchMethodError: The method '???' was called on null.
I/flutter ( 2431): Another exception was thrown: NoSuchMethodError: The method '???' was called on null.
Application finished.
```

**Comment by zoechi** [comment]
please add the output of `flutter doctor`

**Comment by rafaelcb21** [comment]
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by HansMuller** [comment]
I can reproduce the problem which does only occur in release mode. Looking into it...

**Comment by HansMuller** [comment]
The source of the problem is that in release mode we manage to layout a frame before discovering what the window's size is. You can see this if you replace the body of the example with:
```
      body: new LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          print(constraints);
          return new Container();
        },
      )
```

InputDecorator shouldn't fail if the incoming constraints are 0x0, I will fix that.
