### ISSUE TITLE
Firebase RTDB: Failed to turn object into JSON in dependencies using 15.0

### ISSUE THREAD

**Issue by mshipton** [flutter/flutter#17715]
I recently upgraded my Firebase dependencies to the following:

```
  firebase_auth: "0.5.5"
  firebase_database: "0.4.6"
  firebase_analytics: "0.3.3"
```

Change lots show these all include `Updated Google Play Services dependencies to version 15.0.0`. Since then when reading or writing to the RTDB I see an Exception in the `Run` logs. The data is read/written locally but the remote database is not hit. I am reading/writing with basic user access rules and anonymous accounts.

```
E/StorageHelpers(15261): Failed to turn object into JSON
E/StorageHelpers(15261): java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
E/StorageHelpers(15261):    at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:126)
E/StorageHelpers(15261):    at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
E/StorageHelpers(15261):    at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:28)
E/StorageHelpers(15261):    at com.google.firebase.auth.zzm.zza(Unknown Source:3)
E/StorageHelpers(15261):    at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27)
E/StorageHelpers(15261):    at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
E/StorageHelpers(15261):    at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
E/StorageHelpers(15261):    at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:42)
E/StorageHelpers(15261):    at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:13)
E/StorageHelpers(15261):    at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
E/StorageHelpers(15261):    at android.os.Binder.execTransact(Binder.java:697)
```

If I downgrade back to previous versions then everything works correctly.

```
  firebase_auth: "0.4.7"
  firebase_database: "0.3.6"
  firebase_analytics: "0.2.2+1"
```

I both cases I'm using `'com.google.gms:google-services:3.2.1'` in my Android build.gradle file.

After some searching it appears this problem occurs for other Android users. One of the solutions given was to use `'com.google.gms:google-services:3.3.1'. However, this is not currently possible (app won't build using this version). See: https://stackoverflow.com/questions/50265988/failed-to-turn-object-into-json

Perhaps there is some version mis-alignment?

**Comment by mshipton** [comment]
```
/Users/mark/work/sdk/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.12.6 16G29, locale en)
Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[!] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```
Presently my computer is not fully setup for iOS development hence the warnings above.
I've observed the issue both using emulator and a Nexus 5x.

**Comment by mshipton** [comment]
After downgrading Flutter dependency versions, rebuilding and reinstalling the APK onto my Nexus 5x (via `adb install -r`) database reading/writing resumed successfully. This indicates it's a dependency issue rather than an environment issue?

**Comment by alardizabal** [comment]
We're seeing the same issue on the Hamilton app. Re-installing does work but leads to a subpar experience since users updating through the play store get stuck at startup trying to authenticate. I've read various posts about changing firebase dependency versions but I haven't been successful.

```
-30 00:07:36.146 32340-32352/? E/StorageHelpers: Failed to turn object into JSON
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:116)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92)
        at com.google.firebase.auth.FirebaseAuth$zza.zza(Unknown Source:12)
        at com.google.firebase.auth.api.internal.zzbj.zzaa(Unknown Source:20)
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzdb.zza(Unknown Source:46)
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:127)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.execTransact(Binder.java:697)
```

`flutter doctor -v`
```
☆ flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel master, v0.5.1-pre.15, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.5.1-pre.15 at /Users/albertlardizabal/dev/flutter
    • Framework revision c7ea3ca377 (4 hours ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Android NDK at /Users/albertlardizabal/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1
```

**Comment by mshipton** [comment]
@alardizabal I'm using the following dependency versions to workaround this problem:

```
  firebase_auth: "0.4.7"
  firebase_database: "0.3.6"
  firebase_analytics: "0.2.2+1"
```

I uploaded a revised build of my APK to Google Play which downgraded the versions. Following this I observed a very large sync of data from my users. With the latest Firebase versions the app data was written locally but syncing always failed, downgrading fixed this problem and syncing resumed.

**Comment by zoechi** [comment]
@Hixie

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by mshipton** [comment]
@zoechi I'm still running the workaround mentioned above. I'll perform a test with the latest versions and report back.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by mshipton** [comment]
@zoechi apologies for the delay. I've not touched this code in a long time!

I updated Flutter to beta branch v1.2.0 and updated all dependencies to allow the build to complete. I can confirm that using Firebase Auth dependency at version 0.5.5 no longer causes this problem. I tried more recent versions of the dependency too and they were also fine.

**Comment by kroikie** [comment]
@mshipton

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/819. Any further collaboration will be done there.
