### ISSUE TITLE
BREAKING cloud_firestore bug on iOS (Swift).

### ISSUE THREAD

**Issue by jeroen-meijer** [flutter/flutter#17723]
## Steps to Reproduce

1. `flutter create -i swift firebasetest`
2. Add  `cloud_firestore: "^0.7.2"` to `pubspec.yaml`
3. `flutter run`

## Logs

`flutter run --verbose` (with `-d 16CCF677-5656-40BA-9FF4-9C0813BAE91B` to make sure it runs on my emulator)
File: [flutter_verbose_output.txt](https://github.com/flutter/flutter/files/2017750/flutter_verbose_output.txt)
Pastebin: [https://pastebin.com/xnSGQRwV](https://pastebin.com/xnSGQRwV)

The error part:
```
...
/Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:115:45: warning: implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
                 @"oldIndex" : [NSNumber numberWithInt:documentChange.oldIndex],
                               ~                       ^~~~~~~~~~~~~~~~~~~~~~~
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:116:45: warning: implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
                 @"newIndex" : [NSNumber numberWithInt:documentChange.newIndex],
                               ~                       ^~~~~~~~~~~~~~~~~~~~~~~
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:160:21: warning: implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'UInt32' (aka 'unsigned int') [-Wshorten-64-to-32]
               [self writeSize:blob.length];
               ~               ^~~~~~~~~~~
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:270:7: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 transactions[transactionId] = transaction;
                 ^
                 self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:277:29: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                                       transactionResults[transactionId] = doTransactionResult;
                                       ^
                                       self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:284:14: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 return transactionResults[transactionId];
                        ^
                        self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:298:37: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 FIRTransaction *transaction = transactions[transactionId];
                                               ^
                                               self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:322:37: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 FIRTransaction *transaction = transactions[transactionId];
                                               ^
                                               self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:331:37: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 FIRTransaction *transaction = transactions[transactionId];
                                               ^
                                               self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:340:37: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
                 FIRTransaction *transaction = transactions[transactionId];
                                               ^
                                               self->
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:350:17: error: no visible @interface for 'FIRDocumentReference' declares the selector 'setData:merge:completion:'
                 [document setData:call.arguments[@"data"] merge:YES completion:defaultCompletionBlock];
                  ~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           /Users/jeroen/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/ios/Classes/CloudFirestorePlugin.m:438:14: error: no visible @interface for 'FIRWriteBatch' declares the selector 'setData:forDocument:merge:'
                 [batch setData:call.arguments[@"data"] forDocument:document merge:YES];
                  ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           10 warnings and 2 errors generated.
           
           
[   +2 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone X.
[   +2 ms] "flutter run" took 8.647ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:407)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///Users/jeroen/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

`flutter analyze`
```
Analyzing /Users/jeroen/Projects/_temp/firebasetest...
No issues found!
Ran in 5.8s
```

`flutter doctor -v`
```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale nl-NL)
    • Flutter version 0.3.2 at /Users/jeroen/Development/flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jeroen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 9.4, Build version 9Q1019a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (1 available)
    • iPhone X • 16CCF677-5656-40BA-9FF4-9C0813BAE91B • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by jeroen-meijer** [comment]
Judging by the absence of replies on this thread, I assume nobody else is having these issues?

**Comment by jeroen-meijer** [comment]
I can confirm this error also appears in iOS 11.3 using regular Xcode 9.3.1 (in addition to iOS 11.4 on Xcode beta 9.4).

**Comment by hari-yarapotina** [comment]
The following has worked for me. Updated pod repo update, deleted podfile, pod lock, pods, .packages,.flutter-plugins & pubspec.lock.

**Comment by jeroen-meijer** [comment]
That unfortunately didn't work for me, but thanks for the suggestion.

**Comment by jeroen-meijer** [comment]
Nevermind, it all works when running it through Xcode. Thank you @hari-yarapotina!

**Comment by BerndWessels** [comment]
@jeroen-meijer @hari-yarapotina 

I am on the latest dev channel with these dependencies and still get this error - how did you fix it?

```
             /Users/bernd/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.3/ios/Classes/CloudFirestorePlugin.m:350:17: error: no visible @interface for 'FIRDocumentReference' declares the selector 'setData:merge:completion:'
                   [document setData:call.arguments[@"data"] merge:YES completion:defaultCompletionBlock];
                    ~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             /Users/bernd/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.3/ios/Classes/CloudFirestorePlugin.m:438:14: error: no visible @interface for 'FIRWriteBatch' declares the selector 'setData:forDocument:merge:'
                   [batch setData:call.arguments[@"data"] forDocument:document merge:YES];
                    ~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             10 warnings and 2 errors generated.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.4 17E202, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

```
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  rxdart: ^0.18.0

  firebase_core: ^0.2.4
  cloud_firestore: ^0.7.3

  cached_network_image: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by BerndWessels** [comment]
[this fixes and explains it for me](https://github.com/flutter/flutter/issues/17469#issuecomment-400486492)
