### ISSUE TITLE
'dart:core/uri.dart': error: Unexpected tag 0 (Nothing) in ?, expected expression

### ISSUE THREAD

**Issue by trycodin** [flutter/flutter#17740]
Today I updated Flutter after 28 days. And then I got below error, not only for one project but app is working(flutter run using cmd). Only on pysical device.

What is the meaning? and do I need to worry about this?

```
flutter run
Launching lib/main.dart on E2115 in debug mode...
Initializing gradle...                                      13.2s
Resolving dependencies...                                    8.4s
Running 'gradlew assembleDebug'...                          10.0s
Built build\app\outputs\apk\debug\app-debug.apk (32.7MB).
Installing build\app\outputs\apk\app.apk...                 19.8s
E/DartVM  (25910): 'dart:core/string.dart': error: Unexpected tag 0 (Nothing) in ?, expected expression
E/DartVM  (25910): ../../third_party/dart/runtime/vm/compiler/intrinsifier.cc: 106: error: Intrinsifier failed to find method get:hashCode in class _StringBase
E/DartVM  (25910):
E/DartVM  (25910): Dumping native stack trace for thread 6573
E/DartVM  (25910):   [0x60f742c1] Unknown symbol
E/DartVM  (25910):   [0x60f742c1] Unknown symbol
E/DartVM  (25910): -- End of DumpStackTrace
I/FlutterActivityDelegate(26086): onResume setting current activity to this
E/DartVM  (26086): vm-service: Error: Unhandled exception:
E/DartVM  (26086): 'dart:core/uri.dart': error: Unexpected tag 0 (Nothing) in ?, expected expression
E/DartVM  (26086): #0      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
E/DartVM  (26086): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/DartVM  (26086): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/DartVM  (26086): #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
E/DartVM  (26086): #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/DartVM  (26086): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
E/DartVM  (26086):
E/flutter (26086): [ERROR:flutter/runtime/dart_isolate.cc(713)] Isolate (907501011) 'vm-service' exited with an error
E/flutter (26086): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26086): 'dart:core/uri.dart': error: Unexpected tag 0 (Nothing) in ?, expected expression
E/flutter (26086): #0      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
E/flutter (26086): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (26086): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (26086): #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
E/flutter (26086): #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (26086): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Regards!

**Comment by mraleph** [comment]
Does this continue to happen if you do `flutter clean` in the directory of your project?

**Comment by trycodin** [comment]
Sorry for the late response. Yes,. it's fixed by `flutter clear`
