### ISSUE TITLE
Exception Caught by Widgets Library

### ISSUE THREAD

**Issue by losvedir** [flutter/flutter#17758]
New Flutter user here, just got a crash of some sort, and I understand the error message to be requesting that I post an issue here.

The error message I got was:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building HanzeeHome(dirty, state: HanzeeState#f9b29):
flutter: type 'MappedListIterable<Transaction, Widget>' is not a subtype of type 'List<Widget>' where
flutter:   MappedListIterable is from dart:_internal
flutter:   Widget is from package:flutter/src/widgets/framework.dart
flutter:   Transaction is from file:///Users/gdurazo/hanzee/hanzee/lib/main.dart
flutter:   Widget is from package:flutter/src/widgets/framework.dart
flutter:   List is from dart:core
flutter:   Widget is from package:flutter/src/widgets/framework.dart
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
```

The stacktrace was:

```
flutter: When the exception was thrown, this was the stack:
flutter: #0      HanzeeState.build (file:///Users/gdurazo/hanzee/hanzee/lib/main.dart:42:40)
flutter: #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
flutter: #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
flutter: #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4751:32)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #85     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #120    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #121    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #122    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #123    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4751:32)
flutter: #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #126    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
flutter: #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #132    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
Restarted app in 1,646ms.
flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #155    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #161    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #171    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
flutter: #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #176    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #187    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #188    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #197    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #199    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #200    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #201    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #207    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #212    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #218    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #219    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #220    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #225    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #226    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #227    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #231    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #232    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #233    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #234    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #235    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #237    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #238    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #245    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #246    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #247    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #248    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #250    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #251    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #252    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #253    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #256    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #257    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #258    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
flutter: #259    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #260    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #261    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #263    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #264    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
flutter: #265    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
flutter: #266    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
flutter: #267    Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
flutter: #268    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
flutter: #269    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
flutter: #270    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
flutter: #271    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
flutter: #272    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
flutter: #273    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
flutter: #274    runApp (package:flutter/src/widgets/binding.dart:704:7)
flutter: #275    main (file:///Users/gdurazo/hanzee/hanzee/lib/main.dart:4:16)
flutter: #276    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
flutter: #277    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: ══════════════════════════════════════════════
```

My code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Hanzee - Expense Tracker',
      home: new HanzeeHome(),
      theme: new ThemeData(
        primaryColor: Colors.pink[400],
        splashColor: Colors.black,
      ),
    );
  }
}

class HanzeeHome extends StatefulWidget {
  @override
  createState() => new HanzeeState();
}

class HanzeeState extends State<HanzeeHome> {
  final _transactions = <Transaction>[
    Transaction(4.75, "Dunkin' Donuts"),
    Transaction(4.75, "Dunkin' Donuts"),
    Transaction(100, "Watami"),
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Row(
          children: <Widget>[
            Text("Total:"),
            Text(_transactions.fold(0, (sum, txn) => sum + txn.amount).toString()),
          ],
        ),
        Column(children: _transactions.map(_buildTransactionRow)),
      ],
    );
  }

  Widget _buildTransactionRow(Transaction txn) {
    return Row(
      children: <Widget>[
        Text(txn.description),
        Text(txn.amount.toString()),
      ],
    );
  }
}

class Transaction {
  final num amount;
  final String description;

  Transaction(this.amount, this.description);
}
```

**Comment by jonahwilliams** [comment]
The problem is that Column expects a List of widgets, but the 'map' method produces a lazy iterable.  To solve this, make sure you call 'toList' after using Iterable methods.  Most IDEs will warn you about this as well.

**Comment by losvedir** [comment]
Yep, that fixed it. Thanks!

I'll leave the issue open for now since the error message indicated this issue should be created, but obviously feel free to close it.
