### ISSUE TITLE
OnePlus 5 "_pointers.containsKey(datum.device)" assertion

### ISSUE THREAD

**Issue by robertgol** [flutter/flutter#17765]
Hey, my app (complete example from [Write your first app](https://flutter.io/get-started/codelab/) tutorial with some minor changes) is throwing an error when taking a screenshot on OnePlus 5 (using gesture).

Here is a [gist](https://gist.github.com/robertgol/5b69ed6e7b7fef4f88ba3d8c9633c013) with my main.dart file code.

VS Code shows this message:
```
Exception has occurred.
'package:flutter/src/gestures/converter.dart': Failed assertion: line 239 pos 18: '_pointers.containsKey(datum.device)': is not true.
```
VS Code stops on a breakpoint when exception is thrown, after i click to continue the app is working normally.

Also, if I press the heart IconButon while taking the screenshot it leaves the IconButton looking pressed.

![screenshot_20180521-112006](https://user-images.githubusercontent.com/17677124/40301714-3a369f34-5ced-11e8-87c5-527d000495ce.jpg)

## Steps to Reproduce

1. Run app from VS Code
2. Take a screenshot using 3 finger swipe gesture

## Logs

Logs from running app `flutter run --verbose` and taking a screenshot.
```
[+12091 ms] D/ViewRootImpl( 7302): Gesture Screenshot Enabled = true
[   +4 ms] E/flutter ( 7302): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter ( 7302): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 239 pos 18: '_pointers.containsKey(datum.device)': is not true.
[        ] E/flutter ( 7302): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
[        ] E/flutter ( 7302): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
[        ] E/flutter ( 7302): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart)
[        ] E/flutter ( 7302): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
[        ] E/flutter ( 7302): #4      ListQueue.addAll (dart:collection/queue.dart:744:25)
[        ] E/flutter ( 7302): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:46:27)
[        ] E/flutter ( 7302): #6      _invoke1 (dart:ui/hooks.dart:134:13)
[        ] E/flutter ( 7302): #7      _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

Running flutter analyze -> **No issues found!**

Flutter doctor: 
```
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.3.2 at C:\flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\272461\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\272461\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Users\272461\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\181.4892.42
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • ONEPLUS A5000 • 307461e • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Sorry, for the late response. Is this still an issue in recent Flutter versions?

**Comment by rgeurgas** [comment]
It does the same thing on my OnePlus 5t

**Comment by zoechi** [comment]
@rgeurgas can you please add the output of `flutter doctor`?

**Comment by Hixie** [comment]
Weird, I wonder if the OnePlus 5s are sending us bogus pointer events or something.

**Comment by rgeurgas** [comment]
Logs:
```
[   +3 ms] E/flutter (17560): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter (17560): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 239 pos 18: '_pointers.containsKey(datum.device)': is not true.
[        ] E/flutter (17560): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
[        ] E/flutter (17560): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
[        ] E/flutter (17560): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart)
[        ] E/flutter (17560): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
[        ] E/flutter (17560): #4      ListQueue.addAll (dart:collection/queue.dart:727:25)
[        ] E/flutter (17560): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:46:27)
[        ] E/flutter (17560): #6      _invoke1 (dart:ui/hooks.dart:134:13)
[        ] E/flutter (17560): #7      _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```
Flutter analyze:
```
Analyzing flutter_fog...
No issues found! (ran in 22.4s)
```

Flutter doctor:
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/rodrigo/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/rodrigo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Android Studio
    • Android Studio at /home/rodrigo/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected devices (1 available)
    • ONEPLUS A5010 • 693495c0 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
@rgeurgas can you still reproduce?

**Comment by goderbauer** [comment]
I am closing this tentatively as a dup of https://github.com/flutter/flutter/issues/20517.

**Comment by virenvvarasadiya** [comment]
i face the same issue in oneplus 6T. any solutions ?

**Comment by cllee1214** [comment]
there is same issue in simulator.

**Comment by keitoro** [comment]
I have the same issue on iphone. it started just a couple of days ago all across my app.
