### ISSUE TITLE
Android: Text entry field under TalkBack does not show soft keyboard

### ISSUE THREAD

**Issue by gregko** [flutter/flutter#17801]
I'm popping up a SimpleDialog with prompt text and TextFiled to enter something. Works fine without TalkBack, soft keyboard appears and text can be typed. If TalkBack is active, the soft keyboard never appears, and the Run window under Android Studio shows this crash:

```
E/flutter ( 3991): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3991): NoSuchMethodError: The getter 'selection' was called on null.
E/flutter ( 3991): Receiver: null
E/flutter ( 3991): Tried calling: selection
E/flutter ( 3991): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
E/flutter ( 3991): #1      _TextFieldState.build.<anonymous closure> (package:flutter/src/material/text_field.dart:509:26)
E/flutter ( 3991): #2      RenderSemanticsAnnotations._performTap (package:flutter/src/rendering/proxy_box.dart:3856:7)
E/flutter ( 3991): #3      SemanticsConfiguration._addArgumentlessAction.<anonymous closure> (package:flutter/src/semantics/semantics.dart:2126:14)
E/flutter ( 3991): #4      SemanticsOwner.performAction (package:flutter/src/semantics/semantics.dart:1964:14)
E/flutter ( 3991): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handleSemanticsAction (package:flutter/src/rendering/binding.dart:192:36)
E/flutter ( 3991): #6      _invoke3 (dart:ui/hooks.dart:162:13)
E/flutter ( 3991): #7      _dispatchSemanticsAction (dart:ui/hooks.dart:95:3)
```

Observed on both beta 2 and master channel, both in the release and debug builds. It's a serious issue for blind and visually impaired users.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.4.5-pre.64, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition (version 1.19.3)
[√] Connected devices (1 available)

! Doctor found issues in 2 categories.

**Comment by gregko** [comment]
Here is a link to a demo project for this bug. Build the app, install on a phone, press the + FAB button at bottom-right. You may press edit field and type. Now try the same under TalkBack - impossible to show the soft keyboard and type anything at all.

https://hyperionics.com/downloads/test/flutter_TalkBack_bug.zip

**Comment by gregko** [comment]
More on the bug - easy to fix, and most probably not limited to Android Oreo only. In flutter/packages/flutter/lib/src/material/text_field.dart, near the very end we have:

```
    return new Semantics(
      onTap: () {
        if (!_controller.selection.isValid)
          _controller.selection = new TextSelection.collapsed(offset: _controller.text.length);
        _requestKeyboard();
      },
      // ....
      ),
    );
```
But _controller is null if the app sets its own controller. Should be instead:

    return new Semantics(
      onTap: () {
        if (!_effectiveController.selection.isValid)
          _effectiveController.selection = new TextSelection.collapsed(offset: _effectiveController.text.length);
        _requestKeyboard();
      },
      // ...

Please fix.
