### ISSUE TITLE
Some network images fail to load

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#17822]
## Steps to Reproduce
Load the image with `new Image.network(...)`.
Examples of images that fail:
- https://www.vanityfair.com/favicon.ico
- https://www.scientificamerican.com/public/resources/favicons/favicon-4c8c70500bd3f01ae8c38cf7dd2771fe.ico
- https://zdnet2.cbsistatic.com/fly/bundles/zdnetcss/images/logos/logo-192x192.png

## Logs

Exception with vanityfair.com image:
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
RangeError (end): Invalid value: Not in range 0..1897, inclusive: 12610
#0      RangeError.checkValidRange (dart:core/errors.dart:319:9)
#1      __Uint8List&_TypedList&_IntListMixin.setRange (dart:typed_data/runtime/libtyped_data_patch.dart:190:18)
#2      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:38:13)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
#9      _FilterSink.addSlice (dart:io/data_transformer.dart:579:15)
#10     _FilterSink.add (dart:io/data_transformer.dart:<…>
[VERBOSE-2:codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
RangeError (end): Invalid value: Not in range 0..1897, inclusive: 2476
#0      RangeError.checkValidRange (dart:core/errors.dart:319:9)
#1      __Uint8List&_TypedList&_IntListMixin.setRange (dart:typed_data/runtime/libtyped_data_patch.dart:190:18)
#2      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:38:13)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
#9      _FilterSink.addSlice (dart:io/data_transformer.dart:579:15)
#10     _FilterSink.add (dart:io/data_transformer.dart:5<…>
```

Exception with scientificamerican.com image:
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
RangeError (end): Invalid value: Not in range 0..4958, inclusive: 10514
#0      RangeError.checkValidRange (dart:core/errors.dart:319:9)
#1      __Uint8List&_TypedList&_IntListMixin.setRange (dart:typed_data/runtime/libtyped_data_patch.dart:190:18)
#2      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:38:13)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
#9      _FilterSink.addSlice (dart:io/data_transformer.dart:579:15)
#10     _FilterSink.add (dart:io/data_transformer.dart:<…>
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
RangeError (end): Invalid value: Not in range 0..4958, inclusive: 19904
#0      RangeError.checkValidRange (dart:core/errors.dart:319:9)
#1      __Uint8List&_TypedList&_IntListMixin.setRange (dart:typed_data/runtime/libtyped_data_patch.dart:190:18)
#2      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:38:13)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
#9      _FilterSink.addSlice (dart:io/data_transformer.dart:579:15)
#10     _FilterSink.add (dart:io/data_transformer.dart:<…>
[VERBOSE-2:codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
```

Exception with zdnet image:
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
RangeError (end): Invalid value: Not in range 0..7657, inclusive: 8101
#0      RangeError.checkValidRange (dart:core/errors.dart:319:9)
#1      __Uint8List&_TypedList&_IntListMixin.setRange (dart:typed_data/runtime/libtyped_data_patch.dart:190:18)
#2      consolidateHttpClientResponseBytes.<anonymous closure> (package:flutter/src/foundation/consolidate_response.dart:38:13)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
#9      _FilterSink.addSlice (dart:io/data_transformer.dart:579:15)
#10     _FilterSink.add (dart:io/data_transformer.dart:5<…>
[VERBOSE-2:codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
```

## flutter analyze
```
No issues found!
```

## flutter doctor -v
```
[✓] Flutter (Channel beta, v0.3.2, on Mac OS X 10.13.4 17E202, locale en-KR)
    • Flutter version 0.3.2 at /Users/thibaultdeckers/projects/flutter
    • Framework revision 44b7e7d3f4 (5 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/thibaultdeckers/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (2 available)
    • E5823     • CB5A28Q7EL                           • android-arm64 • Android 7.1.1 (API 25)
    • iPhone 6s • 41F87FD3-BCD7-4A3A-BDEC-84432AA09BB1 • ios           • iOS 11.3 (simulator)

• No issues found!
```

**Comment by jonahwilliams** [comment]
@deckerst, could you check if this is still an error on master? There was a recently fixed issue with seems related.
