### ISSUE TITLE
"The getter 'baseUri' was called on null" in resetAssetDirectory on restart

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#17836]
Not sure if I'll be able to repro this, but just saw this when sending a restart... I'll add more info if I can figure out anything useful..

```
Exception has occurred: Error
Error: Hot reload failed: NoSuchMethodError: The getter 'baseUri' was called on null.
Receiver: null
Tried calling: baseUri
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FlutterDevice.resetAssetDirectory (package:flutter_tools/src/resident_runner.dart:157)
<asynchronous suspension>
#2      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:528)
<asynchronous suspension>
#3      HotRunner.restart (package:flutter_tools/src/run_hot.dart:461)
<asynchronous suspension>
#4      AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:816)
#5      AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:479)
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1126)
#8      _CustomZone.run (dart:async/zone.dart:1023)
#9      runZoned (dart:async/zone.dart:1501)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#11     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:828)
#12     AppDomain.restart (package:flutter_tools/src/commands/daemon.dart:478)
<asynchronous suspension>
#13     Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:185)
#14     new Future.sync (dart:async/future.dart:222)
#15     Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:183)
#16     Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:145)
#17     _rootRunUnary (dart:async/zone.dart:1134)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#22     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#23     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#24     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#25     _rootRunUnary (dart:async/zone.dart:1134)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#30     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#31     _WhereStream._handleData (dart:async/stream_pipe.dart:207)
#32     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#33     _rootRunUnary (dart:async/zone.dart:1134)
#34     _CustomZone.runUnary (dart:async/zone.dart:1031)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#41     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#42     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#43     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#45     _rootRunUnary (dart:async/zone.dart:1134)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#50     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#51     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#52     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#53     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#54     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#55     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#56     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#57     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#58     _rootRunUnary (dart:async/zone.dart:1134)
#59     _CustomZone.runUnary (dart:async/zone.dart:1031)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#63     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#64     _StreamController._add (dart:async/stream_controller.dart:639)
#65     _StreamController.add (dart:async/stream_controller.dart:585)
#66     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#67     _rootRunUnary (dart:async/zone.dart:1138)
#68     _CustomZone.runUnary (dart:async/zone.dart:1031)
#69     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#72     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#73     _StreamController._add (dart:async/stream_controller.dart:639)
#74     _StreamController.add (dart:async/stream_controller.dart:585)
#75     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#76     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#77     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#78     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#79     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by DanTup** [comment]
Ok, I think this is just as a result of another issue. A hot reload is causing an exception in the app, which is resulting in my tearing down the app; and this seems to be as a result of that. I'll debug this and figure out why the reload is causing an exception in the app.
