### ISSUE TITLE
Framework error  in semantics

### ISSUE THREAD

**Issue by Asoseil** [flutter/flutter#17883]
```
 ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1918 pos 14:
flutter: 'node.parent?._dirty != true': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart)
flutter: #3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:889:23)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #11     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #12     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 434 libraries in 2,183ms.
flutter: Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1918 pos 14: 'node.parent?._dirty != true': is not true.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.4.5-pre.84, on Mac OS X 10.13.4 17E202, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
[!] VS Code (version 1.21.0)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by Asoseil** [comment]
No it’s solved whit latest version

**Comment by zoechi** [comment]
Thanks for the update!
