### ISSUE TITLE
Exception on writing Widgettest for a Widget using Futures

### ISSUE THREAD

**Issue by Gleydar** [flutter/flutter#17881]
## Steps to Reproduce

1. Use a Future.delayed somewhere in the Widget Tree
2. Try to write a test for a widget containing this Future
3. Run the test

## Logs
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart': Failed assertion: line 787 pos 7:
'_fakeAsync.nonPeriodicTimerCount == 0'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:520:7)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:751:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:749:16)
#14     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
#15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#16     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#20     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#21     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#25     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#26     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#40     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#41     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 28 frames from class _AssertionError, class _FakeAsync, package dart:async, and package
stack_trace)
```

```
Analyzing cie...
No issues found! (ran in 1.5s)
```

```
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.48], locale de-DE)
    • Flutter version 0.4.4 at D:\Daten\Gleydar\Dokumente\Code\Libaries\flutter
    • Framework revision f9bb4289e9 (13 days ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Gleydar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Users\Gleydar\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.5087.20
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Users\Gleydar\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.2574.2
    • Flutter plugin version 23.2.3
    • Dart plugin version 182.2371.1

[√] Connected devices (1 available)
    • SM G960F • 21fbe6c040047ece • android-arm64 • Android 8.0.0 (API 26) (emulator)
```

**Comment by zoechi** [comment]
Do you return the future at the end of the test?
Can you please add the test code that allows to reproduce?

**Comment by Gleydar** [comment]
of course, can do:
```
 testWidgets('HomeScreenTest', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(new MaterialApp(home: new LocationScreen()));
    expect(find.byType(BottomNavigationBar), findsOneWidget);
  });
```
The Future itself is used in the widget:

```
class LocationScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _LocationState();
}

class _LocationState extends State<LocationScreen> {
  CampusProvider _campusProvider;
  List<Campus> _campuses;

  _LocationState() {
    var data = new Data();
    _campusProvider = data.campusProvider;
    _campusProvider.getCampuses().then((campuses) {
      if (mounted) {
        setState(() {
          _campuses = campuses;
        });
      }
    });
  }
```

I can test widgets without these futures just fine.

**Comment by zoechi** [comment]
There should be at least a way to tell the test framework to ignore pending timers.

**Comment by Gleydar** [comment]
Do you know how this can be done? Using `await tester.idle()` didn't work in my case.

**Comment by zoechi** [comment]
No, no idea if something like that is supported already.

**Comment by zoechi** [comment]
```dart
await tester.pumpAndSettle(const Duration(seconds: 2));
```
(with or without the optional duration parameter)
should do that.

I guess you figured that out by now yourself. 
Can this issue be closed?

**Comment by Gleydar** [comment]
Actually I didn't figure it out... We solved the problem by refractoring in the end and putting all futures in providers that supplied the widgets. However, this solution would probably come in handy for smaller projects where that kind of refractoring would just be too much work.
