### ISSUE TITLE
License script fails to handle newly rolled boringssl in flutter/engine

### ISSUE THREAD

**Issue by aam** [flutter/flutter#17931]
From https://github.com/flutter/engine/pull/5390 with attempt to roll dart with rolled boringssl

```
╰─➤  flutter/travis/licenses.sh                   
Verifying license script is still happy...
Resolving dependencies... 
Got dependencies!
Finding files...
failed to handle ../../../third_party/boringssl/src/LICENSE: found too many authors for this copyright:
OpenSSL License
...
#0      License._readAuthors (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/licenses.dart:406:7)
#1      new License._ (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/licenses.dart:272:127)
#2      new MultiLicense._ (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/licenses.dart:954:70)
#3      new License.fromBodyAndType.<anonymous closure> (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/licenses.dart:182:22)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:270)
#5      new License.fromBodyAndType (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/licenses.dart:161:32)
#6      new RepositoryOpenSSLLicenseFile (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1983:29)
#7      RepositoryBoringSSLSourceDirectory.createFile (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1965:18)
#8      RepositoryDirectory.crawl (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:864:36)
#9      new RepositoryDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:837:5)
#10     new RepositoryBoringSSLSourceDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1948:85)
#11     RepositoryBoringSSLDirectory.createSubdirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:2014:18)
#12     RepositoryDirectory.crawl (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:859:39)
#13     new RepositoryDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:837:5)
#14     new RepositoryBoringSSLDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:2002:79)
#15     RepositoryRootThirdPartyDirectory.createSubdirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1904:18)
#16     RepositoryDirectory.crawl (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:859:39)
#17     new RepositoryDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:837:5)
#18     new RepositoryGenericThirdPartyDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1200:87)
#19     new RepositoryRootThirdPartyDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:1874:84)
#20     RepositoryRoot.createSubdirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:2310:18)
#21     RepositoryDirectory.crawl (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:859:39)
#22     new RepositoryDirectory (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:837:5)
#23     new RepositoryRoot (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:2280:37)
#24     main (file:///Users/aam/projects/flutter/test_root6/flutter/engine/src/flutter/tools/licenses/lib/main.dart:2411:42)
<asynchronous suspension>
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

aborted.
```

**Comment by aam** [comment]
Changes to LICENSE that triggered this error are below. @Hixie any thoughts on what is the right fix for this?

```
╰─➤  diff LICENSE $FH/engine/src/third_party/boringssl/src/LICENSE 
181a182,251
> 
> 
> Licenses for support code
> -------------------------
> 
> Parts of the TLS test suite are under the Go license. This code is not included
> in BoringSSL (i.e. libcrypto and libssl) when compiled, however, so
> distributing code linked against BoringSSL does not trigger this license:
> 
> Copyright (c) 2009 The Go Authors. All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met:
> 
>    * Redistributions of source code must retain the above copyright
> notice, this list of conditions and the following disclaimer.
>    * Redistributions in binary form must reproduce the above
> copyright notice, this list of conditions and the following disclaimer
> in the documentation and/or other materials provided with the
> distribution.
>    * Neither the name of Google Inc. nor the names of its
> contributors may be used to endorse or promote products derived from
> this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
> "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
> LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
> A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
> OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
> SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
> LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
> DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
> THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
> OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> 
> BoringSSL uses the Chromium test infrastructure to run a continuous build,
> trybots etc. The scripts which manage this, and the script for generating build
> metadata, are under the Chromium license. Distributing code linked against
> BoringSSL does not trigger this license.
> 
> Copyright 2015 The Chromium Authors. All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are
> met:
> 
>    * Redistributions of source code must retain the above copyright
> notice, this list of conditions and the following disclaimer.
>    * Redistributions in binary form must reproduce the above
> copyright notice, this list of conditions and the following disclaimer
> in the documentation and/or other materials provided with the
> distribution.
>    * Neither the name of Google Inc. nor the names of its
> contributors may be used to endorse or promote products derived from
> this software without specific prior written permission.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
> "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
> LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
> A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
> OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
> SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
> LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
> DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
> THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
> OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by aam** [comment]
Proposed fix is to ignore last part that starts with `BoringSSL uses the Chromium test infrastructure to run a continuous build,` - 
https://github.com/flutter/engine/pull/5390/commits/65604b11e9fe36ada32148be3da7bdbcad85ab92

**Comment by Hixie** [comment]
I forget how boringssl is handled, but basically we just need to update that code to handle the new combined license and then basically ignore these last two additions. If it's handled as a special case then it's just a matter of updating the regexp. If it's handled as multiple licenses then we need to update the patterns to correctly split the above into the relevant separate blocks, and then skip them.

**Comment by aam** [comment]
Thanks @Hixie 
boringssl license is handled as an openssl license, so [my fix](https://github.com/flutter/engine/commit/65604b11e9fe36ada32148be3da7bdbcad85ab92#diff-498bddb8dfa5429f3420a0e16ef68e18R1990) sounds similar to what you are suggesting, except it simply cuts bottom part of license text that trips copyright count verification.

**Comment by aam** [comment]
Fixed by https://github.com/flutter/engine/commit/65604b11e9fe36ada32148be3da7bdbcad85ab92#diff-498bddb8dfa5429f3420a0e16ef68e18
