### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by mikeashelby** [flutter/flutter#17968]
Hi,

I've just had the following error occurring in my flutter project.

It says to report it, so I have!

Let me know if there's anything further I can help with. I haven't yet found a flaw in my code that is causing this - but that doesn't mean there isn't one!

Many thanks,

Mike

```flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building App(dirty, state: AppState#1ddca):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1656 pos 14:
flutter: '!children.any((Widget child) => child == null)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart)
flutter: #3      new Stack (package:flutter/src/widgets/basic.dart)
flutter: #4      AppState.build (file:///Users/mikeashelby/StudioProjects/superboss_todo/lib/main.dart:99:12)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #15     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #16     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by najeira** [comment]
paste your code.

**Comment by mikeashelby** [comment]
There was no reference to my code, so I didn't know which bit to paste! The error has now magically gone away, but I think may have had something to do with an empty list. Shall I have close this and keep an eye out in the future? Which section of my code should I post next time it happens?

**Comment by xster** [comment]
It's likely related to 
```
flutter: #4      AppState.build (file:///Users/mikeashelby/StudioProjects/superboss_todo/lib/main.dart:99:12)
```
and likely because you're building a Stack with null in the list of children.

**Comment by mikeashelby** [comment]
Thanks for the tip! I think the reference didn't point to anything I could see an error with, but it's possible you've diagnosed what I then fixed. A more helpful error would have been handy 😀!
