### ISSUE TITLE
can't create checkbox widget without tristate property

### ISSUE THREAD

**Issue by imhtapm** [flutter/flutter#17970]
```
I/flutter (16851): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16851): The following assertion was thrown building AddClothPage(dirty, state: AddClothPageState#2340c):
I/flutter (16851): 'package:flutter/src/material/checkbox.dart': Failed assertion: line 62 pos 15: 'tristate || value
I/flutter (16851): != null': is not true.
I/flutter (16851): 
I/flutter (16851): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16851): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16851): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16851):   https://github.com/flutter/flutter/issues/new
I/flutter (16851): 
I/flutter (16851): When the exception was thrown, this was the stack:
I/flutter (16851): #2      new Checkbox (package:flutter/src/material/checkbox.dart)
I/flutter (16851): #3      AddClothPageState.build (package:clothx_stores/pages/AddClothPage.dart:81:38)
I/flutter (16851): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter (16851): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (16851): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (16851): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (16851): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (16851): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (16851): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (16851): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (16851): #101    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4437:32)
I/flutter (16851): #102    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (16851): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #104    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (16851): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (16851): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #112    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (16851): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (16851): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (16851): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (16851): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (16851): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (16851): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (16851): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (16851): #126    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (16851): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (16851): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (16851): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (16851): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (16851): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (16851): #132    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (16851): #133    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (16851): (elided 2 frames from class _AssertionError)
I/flutter (16851): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

# ****This was my code**
```
new Padding(
                             padding: const EdgeInsets.all(8.0),
                             child: new Column(
                               children: <Widget>[
                                 new Text('S'),
                                 new Checkbox(
                                    value: _s,
                                    onChanged: (bool newValue) {
                                      setState(() {
                                        _s = newValue;
                                      });
                                    },
                                  ),
                               ],
                             ),
                           ),
```

**## 
if i delete the tristate and use the checkbox this create bug or it provide above error**  

![checkbox error](https://user-images.githubusercontent.com/25448577/40625098-fe2a7cea-62cd-11e8-9155-1e199ca29a29.gif)

**Comment by goderbauer** [comment]
This works fine for me on master. Is it possible that your variable `_s` is uninitialized (e.g. null) when you build the checkbox? What you pass to `value` has to be either true or false, never null. When you pass null, you (correctly) get the error you posted.

**Comment by imhtapm** [comment]
thank you issue solved :+1: :)

**Comment by HansMuller** [comment]
I'm guessing that your app didn't initialize `_s` to true/false. Null is only a valid value for checkbox if tristate is true.

**Comment by Mafarra** [comment]
c

**Comment by Mafarra** [comment]
bool isComplete = false;
  @override
  Widget build(BuildContext context) { ...
.
.
CheckboxListTile(
                title: Text('isComplete!'),
                value: isComplete,
                onChanged: (value) {
                  setState(() {
                    this.isComplete = value;
                  });
                },
              ),
