### ISSUE TITLE
`flutter run` crashes spontaneously

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#17980]
Twice today, after a hot restart, the `flutter run` process crashed with the following. In the second case (maybe the first as well, but definitely the second, whose stack is below), the process on the device hadn't stopped, and the phone was still visible to `flutter doctor`.

```
Performing hot restart...
Restarted app in 1,458ms.
I/zygote64(13195): Do partial code cache collection, code=30KB, data=24KB
I/zygote64(13195): After code cache collection, code=30KB, data=24KB
I/zygote64(13195): Increasing code cache capacity to 128KB
I/zygote64(13195): Do partial code cache collection, code=60KB, data=42KB
I/zygote64(13195): After code cache collection, code=60KB, data=42KB
I/zygote64(13195): Increasing code cache capacity to 256KB
Unhandled exception:
TimeoutException: Request to Dart VM Service timed out: getIsolate({isolateId: isolates/246276819})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:793)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:1056)
#2      Isolate._fetchDirect (package:flutter_tools/src/vmservice.dart:1039)
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:463)
<asynchronous suspension>
#4      VMService._handleStreamNotify (package:flutter_tools/src/vmservice.dart:272)
#5      new VMService._.<anonymous closure> (package:flutter_tools/src/vmservice.dart:107)
#6      Server._handleSingleRequest (package:json_rpc_2/src/server.dart:164)
<asynchronous suspension>
#7      Server._handleRequest (package:json_rpc_2/src/server.dart:140)
<asynchronous suspension>
#8      _rootRunUnary (dart:async/zone.dart:1134)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#14     _StreamController._add (dart:async/stream_controller.dart:639)
#15     _StreamController.add (dart:async/stream_controller.dart:585)
#16     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:93)
#17     _rootRunUnary (dart:async/zone.dart:1134)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#22     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#23     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#24     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#25     CastStreamSubscription.onData.<anonymous closure> (dart:_internal/async_cast.dart:36)
#26     _rootRunUnary (dart:async/zone.dart:1134)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#31     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#32     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#33     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#40     _StreamController._add (dart:async/stream_controller.dart:639)
#41     _StreamController.add (dart:async/stream_controller.dart:585)
#42     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128)
#43     _rootRunUnary (dart:async/zone.dart:1134)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#50     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334)
#51     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#53     _rootRunUnary (dart:async/zone.dart:1134)
#54     _CustomZone.runUnary (dart:async/zone.dart:1031)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#59     _StreamController._add (dart:async/stream_controller.dart:639)
#60     _StreamController.add (dart:async/stream_controller.dart:585)
#61     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#62     _rootRunUnary (dart:async/zone.dart:1138)
#63     _CustomZone.runUnary (dart:async/zone.dart:1031)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#67     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#68     _StreamController._add (dart:async/stream_controller.dart:639)
#69     _StreamController.add (dart:async/stream_controller.dart:585)
#70     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#71     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#74     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

`flutter doctor` output:

```
[✓] Flutter (Channel master, v0.4.5-pre.96, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.5-pre.96 at /home/ianh/dev/flutter
    • Framework revision d79f2ee223 (2 days ago), 2018-05-26 12:29:53 -0700
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/ianh/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/ianh/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/ianh/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices (1 available)
    • Pixel 2 XL • 709KPNY0045135 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by Hixie** [comment]
Just happened a third time for me. I was doing network communications at the time in the app.

**Comment by zoechi** [comment]
This hasn't been reported since a long time.
Do you think this can be closed?
There is still #7314 which has a similar exception.

**Comment by p30arena** [comment]
@zoechi @Hixie 
Similar Issue?
https://github.com/flutter/flutter/issues/30911

**Comment by timsneath** [comment]
Still relevant, @hixie?

**Comment by onir272** [comment]
same here

**Comment by vitormnoel** [comment]
still happening...

**Comment by SanjoyPator1** [comment]
I am still having this problem. Can someone help me

**Comment by bachowsky** [comment]
So do i. It would be very great to find the solution.
