### ISSUE TITLE
bug in flutter with context

### ISSUE THREAD

**Issue by kushal-kapoor** [flutter/flutter#18021]
When I'm running an app with bottomSheet I'm geting this bug

- here is the log 

```
I/flutter (31498): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (31498): The following assertion was thrown while handling a gesture:
I/flutter (31498): 'package:flutter/src/material/bottom_sheet.dart': Failed assertion: line 281 pos 10: 'context !=
I/flutter (31498): null': is not true.
I/flutter (31498): 
I/flutter (31498): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31498): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31498): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31498):   https://github.com/flutter/flutter/issues/new
I/flutter (31498): 
I/flutter (31498): When the exception was thrown, this was the stack:
I/flutter (31498): #2      showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart)
I/flutter (31498): #3      _BuilderState._showModalSheet (package:flutter_app3/New%20Order.dart:191:5)
I/flutter (31498): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (31498): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (31498): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (31498): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (31498): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (31498): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (31498): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (31498): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (31498): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (31498): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (31498): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (31498): #15     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (31498): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (31498): (elided 2 frames from class _AssertionError)
I/flutter (31498): 
I/flutter (31498): Handler: onTap
I/flutter (31498): Recognizer:
I/flutter (31498):   TapGestureRecognizer#292dc(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (31498):   Offset(289.1, 117.6), sent tap down)
I/flutter (31498): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/FlutterActivityDelegate(21628): onResume setting current activity to this
I/FlutterActivityDelegate(21628): onResume setting current activity to this
I/FlutterActivityDelegate(21628): onResume setting current activity to this
Lost connection to device.
```

- here is NewOrder.dart 

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app3/Chat.dart';
import 'package:flutter_app3/main.dart';
//import 'package:firebase_messaging/firebase_messaging.dart';

void main ( ) {
  runApp (
      new MaterialApp(
          home: new NewOrder(
          )
          )
      );
}

final scafolldKey = new GlobalKey<ScaffoldState>(
);

Color header = Color (
    0xFF4E6882
    );

Color header1 = Color (
    0xFF4E6882
    );

class NewOrder extends StatefulWidget {
  @override
  _NewOrderState createState ( ) =>
      new _NewOrderState(
      );
}

class _NewOrderState extends State<NewOrder> {
  _BuilderState builder = new _BuilderState(
  );
  Monetization monetization = new Monetization(
  );
  static double total = 0.0;
  VoidCallback _showBottomShhetCallback;

  @override
  void initState ( ) {
    super.initState (
    );
  }

  @override
  Widget build ( BuildContext context ) {
    return new Scaffold(
      key: scafolldKey ,
      appBar: new AppBar(
          backgroundColor: header ,
          title: new Row(
            children: <Widget>[
              new Text(
                  'All Categories'
                  ) ,
              new IconButton(
                icon: new Icon(
                    Icons.filter_list
                    ) ,
                onPressed: ( ) {
                  Navigator.push (
                      context ,
                      new MaterialPageRoute(
                          builder: ( context ) =>
                          new SecondScreen(
                          )
                          )
                      );
                } ,
                )
            ] ,
            )
          ) ,
      body: new Center(
        child: ListView (
          padding: EdgeInsets.all (
              8.0
              ) ,
          children: <Widget>[
            builder.List_Item (
                "sgdxdrfhdfhxf" , 345 , 'suit'
                )
          ] ,
          ) ,
        ) ,
      drawer: new Drawer(
        // Add a ListView to the drawer. This ensures the user can scroll
        // through the options in the Drawer if there isn't enough vertical
        // space to fit everything.
        child: new ListView(
          // Important: Remove any padding from the ListView.
          padding: EdgeInsets.zero ,
            children: <Widget>[
              new DrawerHeader(
                child: new Text(
                    'Fas POS'
                    ) ,
                decoration: new BoxDecoration(
                  color: header ,
                  ) ,
                ) ,
              new ListTile(
                title: new Text(
                    'Bill'
                    ) ,
                onTap: ( ) {
                  // Update the state of the app
                  // ...
                  // Then close the drawer
                  Navigator.push (
                      context ,
                      new MaterialPageRoute(
                          builder: ( context ) =>
                          new SecondScreen(
                          )
                          )
                      );
                } ,
                ) ,
              new ListTile(
                title: new Text(
                    'Chat'
                    ) ,
                onTap: ( ) {
                  // Update the state of the app
                  // ...
                  // Then close the drawer
                  Navigator.push (
                      context ,
                      new MaterialPageRoute(
                          builder: ( context ) =>
                          new FriendlychatApp(
                          )
                          )
                      );
                } ,
                ) ,
            ] ,
          ) ,
        ) ,
      );
  }
}

class Builder extends StatefulWidget {
  @override
  _BuilderState createState() => new _BuilderState();
}

class _BuilderState extends State<Builder> {
  @override
  Widget build(BuildContext context) {
    return new Container();
  }
  VoidCallback _showPersBottomSheetCallBack;

  @override
  void initState() {
    super.initState();
    _showPersBottomSheetCallBack = _showBottomSheet;
  }

  void _showBottomSheet() {
    setState(() {
      _showPersBottomSheetCallBack = null;
    });

    scafolldKey.currentState
        .showBottomSheet((context) {
      return new Container(
        height: 300.0,
        color: Colors.greenAccent,
        child: new Center(
          child: new Text("Hi BottomSheet"),
          ),
        );
    })
        .closed
        .whenComplete(() {
      if (mounted) {
        setState(() {
          _showPersBottomSheetCallBack = _showBottomSheet;
        });
      }
    });
  }

  void _showModalSheet() {
    showModalBottomSheet(
        context: context,
        builder: (builder) {
          return new Container(
            color: Colors.greenAccent,
            child: new Center(
              child: new Text("Hi ModalSheet"),
              ),
            );
        });
  }

  double total = 0.0;

  int i = 0;
  String Avatar = "";

  Widget List_Item ( String name , int price , String imageName ) {

    while (i <= name.length) {
      String q = name[i];
      i == 0 ? Avatar = q : Avatar = Avatar;
      q == "" ? Avatar = Avatar + q : Avatar = Avatar;
      i++;

      String imageLocation = "images/$imageName.png";
      return new ListTile(
        leading: new CircleAvatar(
          //: Colors.transparent,
          child: new Text(
              "$Avatar"
              )
          ) ,

        title: new Column(
          children: <Widget>[
            new Text(
              "$name" ,
              textAlign: TextAlign.left ,
              style: new TextStyle(
                  fontSize: 14.0 , color: Color (
                  0xFF404040
                  )
                  ) ,
              ) ,
            new Row(
              mainAxisAlignment: MainAxisAlignment.center ,
              children: <Widget>[
                new Text(
                  "₹ " ,
                  textAlign: TextAlign.left ,
                  style: new TextStyle(
                      fontSize: 12.0 , color: Color (
                      0xFF404040
                      )
                      ) ,
                  ) ,
                new Text(
                  "$price" ,
                  textAlign: TextAlign.left ,
                  style: new TextStyle(
                      fontSize: 12.0 , color: Color (
                      0xFF404040
                      )
                      ) ,
                  ) ,
              ] ,
              ) ,
          ] ,
          ) ,
        trailing: RaisedButton (
          child: new Text(
              'ADD'
              ) , color: Color (
            0xFF2B98F0
            ) ,
          onPressed: _showModalSheet,

          ) ,

        );
    }
  }
}
`
-here is main.dart





`import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app3/Chat.dart';
import 'package:flutter_app3/New Order.dart';
//import 'package:firebase_messaging/firebase_messaging.dart';

void main() {
  runApp(new MaterialApp(home: new SecondScreen()));
}

Color headerColour = Color(0xFF4E6882);

class SecondScreen extends StatelessWidget {
  Builder builder = new Builder();
  Monetization monetization = new Monetization();
  static double total = 0.0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        backgroundColor: headerColour,
        title: new Text("Order Summary"),
        ),
      body: new Center(

        child: ListView(

          padding: EdgeInsets.all(8.0),
          children: <Widget>[
            new Card(
              child: Column(
                children: <Widget>[
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        "Order Number",
                        style: new TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 18.0,
                            color: Color(0xFF404040)),
                        ),
                    ],
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        "DATE",
                        style: new TextStyle(
                            fontSize: 10.0, color: Color(0xFF4A4A4A)),
                        ),
                      new Text(
                        "12 /9/2014",
                        style: new TextStyle(
                            fontSize: 12.0, color: Color(0xFF404040)),
                        ),
                    ],
                    ),
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                ],
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 24.0,
                ),
              ),
            new Row(
              children: <Widget>[
                new Text(
                  "PRODUCTS",
                  style:
                  new TextStyle(fontSize: 12.0, color: Color(0xFF4A4A4A)),
                  ),
              ],
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Card(
              child: new Column(
                children: <Widget>[
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        "FULFILLED",
                        style: new TextStyle(
                            fontSize: 10.0, color: Color(0xFF808080)),
                        ),
                    ],
                    ),
                  new Container(
                    height: 120.0,
                    child: new ListView(
                      children: <Widget>[
                        builder.List_Item("gsuv", "vsfgpsdj", 657, 2, 0),
                        builder.List_Item("sfsd", "dfbndidb", 457, 7, 24),
                      ],
                      ),
                    ),
                  new Opacity(
                    opacity: 0.0,
                    child: new Divider(
                      height: 8.0,
                      ),
                    ),
                  new Row(
                    children: <Widget>[
                      new Text(
                        "UNFULFILLED",
                        style: new TextStyle(
                            fontSize: 10.0, color: Color(0xFF808080)),
                        ),
                    ],
                    ),
                  new Container(
                    height: 60.0,
                    child: new ListView(
                      children: <Widget>[
                        builder.List_Item("gsuv", "vsfgpsdj", 657, 2, 0),
                        builder.List_Item("sfsd", "dfbndidb", 457, 7, 24),
                      ],
                      ),
                    ),
                ],
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 20.0,
                ),
              ),
            new Text(
              "BILL DETAILS",
              style: new TextStyle(fontSize: 12.0, color: Color(0xFF4A4A4A)),
              ),
            new Card(
              child: new Container(
                height: 178.0,
                child: new Column(
                  children: <Widget>[
                    new ListTile(
                      title: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[
                              new Text(
                                "Total",
                                style: new TextStyle(
                                    fontSize: 14.0, color: Color(0xFF404040)),
                                )
                            ],
                            ),
                          new Row(
                            children: <Widget>[
                              new Text(
                                "Dicount",
                                style: new TextStyle(
                                    fontSize: 14.0, color: Color(0xFF4D4D4D)),
                                )
                            ],
                            ),
                        ],
                        ),
                      trailing: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[
                              new Text(
                                "₹  534",
                                style: new TextStyle(
                                    fontSize: 14.0, color: Color(0xFF404040)),
                                )
                            ],
                            ),
                          new Row(
                            children: <Widget>[
                              new Text(
                                "₹  534",
                                style: new TextStyle(
                                    fontSize: 14.0, color: Color(0xFF404040)),
                                )
                            ],
                            ),
                        ],
                        ),
                      ),
                    new ListTile(
                      title: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("CGST @ 2.5%")],
                            ),
                          new Row(
                            children: <Widget>[new Text("SGST@ 2.5%")],
                            ),
                        ],
                        ),
                      trailing: new Column(
                        children: <Widget>[
                          new Row(
                            children: <Widget>[new Text("₹  534")],
                            ),
                          new Row(
                            children: <Widget>[new Text("₹  534")],
                            ),
                        ],
                        ),
                      ),
                    new Divider(
                      height: 8.0,
                      color: Colors.black,
                      ),
                    new ListTile(
                      title: new Row(
                        children: <Widget>[
                          new Text(
                            "Total",
                            style: new TextStyle(
                                fontSize: 14.0, color: Color(0xFF404040)),
                            )
                        ],
                        ),
                      trailing: new Row(
                        children: <Widget>[
                          new Text(
                            "₹  534",
                            style: new TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 24.0,
                                color: Color(0xFF404040)),
                            )
                        ],
                        ),
                      ),
                  ],
                  ),
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Text(
              "PAYMENT DETAILS",

              style: new TextStyle(fontSize: 12.0, color: Color(0xFF4A4A4A)),
              ),
            new Card(
              child: Container(
                height: 112.0,
                child: Column(
                  children: <Widget>[
                    monetization.listItem(267, "Cash"),
                    monetization.listItem(267, "Card"),
                  ],
                  ),
                ),
              ),
            new Opacity(
              opacity: 0.0,
              child: new Divider(
                height: 8.0,
                ),
              ),
            new Text(
              "CUSTOMER DETAILS",
              style: new TextStyle(fontSize: 12.0, color: Color(0xFF4A4A4A)),
              ),
            new Card(
              child: Container(
                height: 50.0,
                child: new ListTile(
                  title: new Column(
                    children: <Widget>[
                      new Row(
                        children: <Widget>[
                          new Text(
                            "NAME",
                            style: new TextStyle(
                                fontSize: 14.0, color: Color(0xFF4A4A4A)),
                            )
                        ],
                        ),
                      new Row(
                        children: <Widget>[
                          new Text(
                            "PHONE NO:",
                            style: new TextStyle(
                                fontSize: 12.0, color: Color(0xFF808080)),
                            )
                        ],
                        ),
                    ],
                    ),
                  trailing: new Row(
                    children: <Widget>[
                      new Icon(
                        Icons.create,
                        color: Color(0xFF3B99FC),
                        )
                    ],
                    ),
                  ),
                ),
              ),
          ],
          ),
        ),
      drawer: new Drawer(
        // Add a ListView to the drawer. This ensures the user can scroll
        // through the options in the Drawer if there isn't enough vertical
        // space to fit everything.
        child: new ListView(
          // Important: Remove any padding from the ListView.
          padding: EdgeInsets.zero,
            children: <Widget>[
              new DrawerHeader(
                child: new Text('Fast POS'),
                decoration: new BoxDecoration(
                  color: headerColour,
                  ),
                ),
              new ListTile(
                title: new Text('New Order'),
                onTap: () {
                  Navigator.push(
                      context,
                      new MaterialPageRoute(
                          builder: (context) => new NewOrder()));
                },
                ),
              new ListTile(
                title: new Text('Chat'),
                onTap: () {
                  // Update the state of the app
                  // ...
                  // Then close the drawer
                  Navigator.push(
                      context,
                      new MaterialPageRoute(
                          builder: (context) => new FriendlychatApp()));
                },
                ),
            ],
          ),
        ),
      );
  }
}

class Builder extends StatelessWidget {
  double total = 0.0;

  @override
  Widget build(BuildContext context) {
    return null;
  }

  Widget List_Item(String name, String description, int indPrice, int quantity,
      int discountPercent) {
    int price = quantity * indPrice;
    double opac = 0.0;
    double disc = (discountPercent / 100);
    double mdiscPrice = disc * price;
    String discPrice = mdiscPrice.toStringAsFixed(2);

    mdiscPrice != 0.0 ? opac = 1.0 : opac = 0.0;

    return new ListTile(
      leading: new Checkbox(
        value: false,
        tristate: true,
        onChanged: null,
        ),
      title: new Row(
        children: <Widget>[
          new Column(
            children: <Widget>[
              new Text(
                "$name",
                textAlign: TextAlign.left,
                style: new TextStyle(fontSize: 14.0, color: Color(0xFF404040)),
                ),
              new Container(
                child: new Text(
                  "$description",
                  textAlign: TextAlign.left,
                  style:
                  new TextStyle(fontSize: 12.0, color: Color(0xFF404040)),
                  ),
                ),
              new Row(
                children: <Widget>[
                  new Opacity(
                    opacity: opac,
                    child: new Text(
                      "Discount @ $discountPercent%",
                      style: new TextStyle(
                          fontSize: 12.0, color: Color(0xFF808080)),
                      ),
                    ),
                ],
                ),
            ],
            ),
        ],
        ),
      trailing: new Row(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          new Container(
            padding: EdgeInsets.only(right: 30.0),
            child: new Text(
              'X  $quantity ',
              style: new TextStyle(fontSize: 14.0, color: Color(0xFF666666)),
              ),
            ),
          new Column(
            children: <Widget>[
              new Text(
                ' ₹  $price',
                style: new TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 14.0,
                    color: Color(0xFF404040)),
                ),
              new Opacity(
                opacity: opac,
                child: new Text(
                  '-₹  $discPrice',
                  style:
                  new TextStyle(fontSize: 12.0, color: Color(0xFF808080)),
                  ),
                ),
            ],
            ),
        ],
        ),
      );
  }
}

class Monetization extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return null;
  }

  Widget listItem(
      int price,
      String mode,
      ) {
    bool cash = false;
    if (mode == 'Cash') {
      cash = true;
    }
    return new ListTile(
        title: new Text('$mode',
                            style: new TextStyle(fontSize: 16.0, color: Color(0xFF404040))),
        leading: new Icon(
          cash ? Icons.attach_money : Icons.credit_card,
          color: Color(0xFF404040),
          ),
        trailing: new Text(
          '₹  $price',
          style: new TextStyle(fontSize: 16.0, color: Color(0xFF4A4A4A)),
          ));
  }
}
`
-here is chat.dart





`import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:flutter_app3/New%20Order.dart';
import 'package:flutter_app3/main.dart';

//import 'package:firebase_messaging/firebase_messaging.dart';

void main() {
  runApp(new MaterialApp(home: new FriendlychatApp()));
}

Color header = Color(0xFF4E6882);

final ThemeData kIOSTheme = new ThemeData(
  primarySwatch: Colors.orange,
  primaryColor: Colors.grey[100],
  primaryColorBrightness: Brightness.light,
  );

final ThemeData kDefaultTheme = new ThemeData(
  primarySwatch: Colors.blueGrey,
  accentColor: Colors.orangeAccent[400],
  );

const String _name = "Your Name";

class FriendlychatApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "Friendlychat",
      theme: defaultTargetPlatform == TargetPlatform.iOS
          ? kIOSTheme
          : kDefaultTheme,
      home: new ChatScreen(),
      );
  }
}

class ChatMessage extends StatelessWidget {
  ChatMessage({this.text, this.animationController});

  final String text;
  final AnimationController animationController;

  @override
  Widget build(BuildContext context) {
    new Drawer(
      // Add a ListView to the drawer. This ensures the user can scroll
      // through the options in the Drawer if there isn't enough vertical
      // space to fit everything.
      child: new ListView(
        // Important: Remove any padding from the ListView.
        padding: EdgeInsets.zero,
          children: <Widget>[
            new DrawerHeader(
              child: new Text('Drawer Header'),
              decoration: new BoxDecoration(
                color: Colors.blue,
                ),
              ),
            new ListTile(
              title: new Text('bill'),
              onTap: () {
                Navigator.push(
                  context,
                  new MaterialPageRoute(builder: (context) => new SecondScreen()),
                  );
              },
              ),
            new ListTile(
              title: new Text('New Order'),
              onTap: () {
                Navigator.push(
                  context,
                  new MaterialPageRoute(builder: (context) => new NewOrder()),
                  );
              },
              ),
          ],
        ),
      );
    return new SizeTransition(
        sizeFactor: new CurvedAnimation(
            parent: animationController, curve: Curves.easeOut),
        axisAlignment: 0.0,
        child: new Container(
          margin: const EdgeInsets.symmetric(vertical: 10.0),
          child: new Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              new Container(
                margin: const EdgeInsets.only(right: 16.0),
                child: new CircleAvatar(child: new Text(_name[0])),
                ),
              new Expanded(
                child: new Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    new Text(_name, style: Theme.of(context).textTheme.subhead),
                    new Container(
                      margin: const EdgeInsets.only(top: 5.0),
                      child: new Text(text),
                      ),
                  ],
                  ),
                ),
            ],
            ),
          ));
  }
}

class ChatScreen extends StatefulWidget {
  @override
  State createState() => new ChatScreenState();
}

class ChatScreenState extends State<ChatScreen> with TickerProviderStateMixin {
  final List<ChatMessage> _messages = <ChatMessage>[];
  final TextEditingController _textController = new TextEditingController();
  bool _isComposing = false;

  void _handleSubmitted(String text) {
    _textController.clear();
    setState(() {
      _isComposing = false;
    });
    ChatMessage message = new ChatMessage(
      text: text,
      animationController: new AnimationController(
        duration: new Duration(milliseconds: 700),
        vsync: this,
        ),
      );
    setState(() {
      _messages.insert(0, message);
    });
    message.animationController.forward();
  }

  void dispose() {
    for (ChatMessage message in _messages)
      message.animationController.dispose();
    super.dispose();
  }

  Widget _buildTextComposer() {
    return new IconTheme(
      data: new IconThemeData(color: Theme.of(context).accentColor),
      child: new Container(
          margin: const EdgeInsets.symmetric(horizontal: 8.0),
          child: new Row(children: <Widget>[
            new Flexible(
              child: new TextField(
                controller: _textController,
                onChanged: (String text) {
                  setState(() {
                    _isComposing = text.length > 0;
                  });
                },
                onSubmitted: _handleSubmitted,
                decoration:
                new InputDecoration.collapsed(hintText: "Send a message"),
                ),
              ),
            new Container(
                margin: new EdgeInsets.symmetric(horizontal: 4.0),
                child: Theme.of(context).platform == TargetPlatform.iOS
                    ? new CupertinoButton(
                  child: new Text("Send"),
                  onPressed: _isComposing
                      ? () => _handleSubmitted(_textController.text)
                      : null,
                  )
                    : new IconButton(
                  icon: new Icon(Icons.send),
                  onPressed: _isComposing
                      ? () => _handleSubmitted(_textController.text)
                      : null,
                  )),
          ]),
          decoration: Theme.of(context).platform == TargetPlatform.iOS
              ? new BoxDecoration(
              border:
              new Border(top: new BorderSide(color: Colors.grey[200])))
              : null),
      );
  }

  Widget build(BuildContext context) {
    return new Scaffold(
      drawer: new Drawer(
        // Add a ListView to the drawer. This ensures the user can scroll
        // through the options in the Drawer if there isn't enough vertical
        // space to fit everything.
        child: new ListView(
          // Important: Remove any padding from the ListView.
          padding: EdgeInsets.zero,
            children: <Widget>[
              new DrawerHeader(
                child: new Text('Fast Pos'),
                decoration: new BoxDecoration(
                  color: header,
                  ),
                ),
              new ListTile(
                title: new Text('bill'),
                onTap: () {
                  Navigator.push(
                    context,
                    new MaterialPageRoute(
                        builder: (context) => new SecondScreen()),
                    );
                },
                ),
              new ListTile(
                title: new Text('chat'),
                onTap: () {
                  Navigator.push(
                      context,
                      new MaterialPageRoute(
                          builder: (context) => new FriendlychatApp()));
                },
                ),
            ],
          ),
        ),
      appBar: new AppBar(
          title: new Text("Friendlychat"),
          elevation:
          Theme.of(context).platform == TargetPlatform.iOS ? 0.0 : 4.0),
      body: new Container(

          child: new Column(
              children: <Widget>[
                new Flexible(
                    child: new ListView.builder(
                      padding: new EdgeInsets.all(8.0),
                      reverse: true,
                      itemBuilder: (_, int index) => _messages[index],
                      itemCount: _messages.length,
                      )),
                new Divider(height: 1.0),
                new Container(
                  decoration: new BoxDecoration(color: Theme.of(context).cardColor),
                  child: _buildTextComposer(),
                  ),
              ]),
          decoration: Theme.of(context).platform == TargetPlatform.iOS
              ? new BoxDecoration(
              border:
              new Border(top: new BorderSide(color: Colors.grey[200])))
              : null
          //new

          ), //new
      );
  }
}
```

**Comment by zoechi** [comment]
I think you need to change 
```dart
onPressed: _showModalSheet,
```

to

```dart
onPressed: () => _showModalSheet(context),
```

and
```
void _showModalSheet() {
```
to

```
void _showModalSheet(BuildContext context) {
```

Also please add the output of `flutter doctor` to your issue.

**Comment by zoechi** [comment]
Closing due to inactivity.
Feel free to create a new issue if there are still unsolved problems.
