### ISSUE TITLE
Improve clarity of returned errors

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#18027]
It is not very obvious what exceptions are being thrown in code, it would be good to make it explicit.

e.g.

    int.tryParse(null);

    Unhandled exception:
    Invalid argument(s): The source must not be null
    #0      int.tryParse (dart:core-patch/dart:core/integers_patch.dart:112)
    #1      main (file:///work/projects/dart/kbml_parser/main_test.dart:11:9)
    #2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
    #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

It is not clear at all that this exception can be trapped with <code>ArgumentError</code>

If we compare this with Java - the exception being thrown is clearly shown :

    java.lang.IllegalArgumentException: timeout value is negative

**Comment by Rockvole** [comment]
Ooops - I put this in the wrong githut

**Comment by Rockvole** [comment]
https://github.com/dart-lang/sdk/issues/33275
