### ISSUE TITLE
Improve error message when a qualified import should be relative

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#18045]
I had a PR validation fail because I used a fully qualified import where I should have used a relative import.  The error message in the out was as follows:

```bash
dart ./dev/bots/test.dart
SHARD=analyze
⏩ RUNNING: cd examples/hello_world; ../../bin/flutter inject-plugins
Unhandled exception:
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _deepSearch (file:///tmp/flutter%20sdk/dev/bots/test.dart:520:17)
#2      _deepSearch (file:///tmp/flutter%20sdk/dev/bots/test.dart:525:28)
#3      _verifyNoBadImportsInFlutter (file:///tmp/flutter%20sdk/dev/bots/test.dart:454:31)
<asynchronous suspension>
#4      _analyzeRepo (file:///tmp/flutter%20sdk/dev/bots/test.dart:100:9)
<asynchronous suspension>
#5      main (file:///tmp/flutter%20sdk/dev/bots/test.dart:56:26)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

We should have a better error message that points in the direction of the problem.

The specific import was in:
`circle_avatar.dart`

I initially imported material colors with full qualification:
`import 'package:flutter/src/material/colors.dart';`

The correct import was a relative one:
`import 'colors.dart'`

**Comment by zoechi** [comment]
@Hixie would the analyzer need specific Flutter support to do that?
Or is this error from the compiler?
Is this something Flutter can fix or should this be moved to the dart-lang/sdk repo?

**Comment by Hixie** [comment]
This is just a bug in our `test.dart` script.

**Comment by TahaTesser** [comment]
Not sure how to verify if this issue is still in `dev/bots/test.dart`
