### ISSUE TITLE
Exception while reading remote JSON data

### ISSUE THREAD

**Issue by vkappsvcs** [flutter/flutter#18053]
```
Performing hot reload...
I/flutter ( 4210): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4210): The following assertion was thrown building FutureBuilder<Post>(dirty, state:
I/flutter ( 4210): _FutureBuilderState<Post>#b5901):
I/flutter ( 4210): 'package:flutter/src/widgets/text.dart': Failed assertion: line 213 pos 15: 'data != null': is not
I/flutter ( 4210): true.
I/flutter ( 4210): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4210): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4210): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4210):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4210): When the exception was thrown, this was the stack:
I/flutter ( 4210): #2      new Text (package:flutter/src/widgets/text.dart)
I/flutter ( 4210): #3      MyApp.build.<anonymous closure> (file:///Users/vishykasinadhuni/Documents/mdsdiscourses/lib/main.dart:49:28)
I/flutter ( 4210): #4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter ( 4210): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter ( 4210): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 4210): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter ( 4210): #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 4210): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4210): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4210): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #79     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4210): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #93     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4210): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4210): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4210): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #109    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4210): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4210): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4210): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4210): #113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 4210): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 4210): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 4210): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4210): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4210): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 4210): #120    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 4210): #121    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 4210): #122    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 4210): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 4210): 
Reloaded 1 of 489 libraries in 1,971ms.
I/flutter ( 4210): Another exception was thrown: 'package:flutter/src/widgets/text.dart': Failed assertion: line 213 pos 15: 'data != null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by xclud** [comment]
It seems you are passing a null to the Text widget. Check if your JSON object has the properties you are looking for. Accessing a non-existing property of a JSON object returns null. There is nothing wrong with reading remote JSON data.

**Comment by zoechi** [comment]
See https://medium.com/@jimmyhott/using-futurebuilder-to-create-a-better-widget-4c7d4f52a329 how to use FutureBuilder. You need to check `hasData` and return an alternative widget or pass an alternative string to `Text(...)` in case `hasData` is false.
