### ISSUE TITLE
Podfile error after attempting to add ANY plugin (iOS specific)

### ISSUE THREAD

**Issue by theEpicality** [flutter/flutter#18055]
## Boring version stuff:
- Cocoapods: 1.5.3,
- Xcode: 9.4,
- Flutter: 0.5.2-pre.8 (Master channel),
- Dart: 2.0.0-dev.59.0.flutter-ff815d05a5,

## Steps to Reproduce
1. Create a new flutter project
(Running the app on any device at this point works fine)
2. Add ANY flutter plugin to the pubspec.yaml file in the dependencies section (I was attempting to use `firebase_database: 1.0.0`)
3. Run the app on an iOS device (not hot reload/restart)

Judging from the nature of the error message, I guessing my symlinks might be screwed up. If that is the case I honestly have no idea how to fix it.

## Logs

Pressing the run button or using `flutter run` in terminal:
```
Launching lib/main.dart on Nathan Bird’s iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Nathan Bird (E3Z3MWA8FC)"
Running pod install...
CocoaPods' output:
↳
    
    [!] Invalid `Podfile` file: No such file or directory @ rb_file_s_symlink - (/Users/nathanbird/flutter/bin/cache/artifacts/engine, Pods/.symlinks/flutter).
    
     #  from /Users/nathanbird/AndroidStudioProjects/podtest2/ios/Podfile:43
     #  -------------------------------------------
     #        symlink = File.join('Pods', '.symlinks', 'flutter')
     >        File.symlink(File.dirname(p[:path]), symlink)
     #        pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
     #  -------------------------------------------
    
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:299:in `rescue in block in from_ruby'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:293:in `block in from_ruby'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:291:in `new'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:291:in `from_ruby'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:257:in `from_file'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/config.rb:191:in `podfile'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:37:in `run'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Users/nathanbird/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Finished with error: Error running pod install
```

'flutter doctor -v':
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.2-pre.8, on Mac OS X 10.13.4 17E199, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.0)
[!] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Michaels-MBP:podtest nathanbird$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.2-pre.8, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.5.2-pre.8 at /Users/nathanbird/flutter
    • Framework revision c65e9d19a4 (13 hours ago), 2018-05-30 16:51:25 +0200
    • Engine revision 16f5cd8106
    • Dart version 2.0.0-dev.59.0.flutter-ff815d05a5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/nathanbird/Library/Android/sdk
    • Android NDK at /Users/nathanbird/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Nathan Bird’s iPhone • e4d3c5162a330e23ee66a46b101101d45f991a2c • ios • iOS 11.3.1

! Doctor found issues in 1 category.
```

**Comment by xster** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
@theEpicality I cannot reproduce by following the indicated steps. The Podfile of Flutter master is different from yours, it seems. See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-objc.

Are you updating an existing project rather than doing `flutter create some_unused_folder`? In that case, please be aware that Flutter tooling does not overwrite existing files. My guess is that your pre-existing Podfile has at some point been modified to follow the latest template in the folder setup part in lines 32-33, but not in line 42 where those folders are used. At least, I can reproduce the error you get by adding `'Pods'` as first argument to `File.join` in line 42 of the Podfile created by Flutter for a brand new project. But this is all guesswork. Please let us know, if something else is at play here.

**Comment by theEpicality** [comment]
That fixed it. I'm not quite sure how I could have screwed up the Podfile lol. 👍
