### ISSUE TITLE
NPE in image_picker plugin 0.4.2

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#18059]
## MyProblem
1. I use the image_picker plugin 0.4.2 version.
2. The android device(true machine)'s android version is android 6.0.0, the plugin report a NPE.
3. I run the code in intellij Idea,
my code 
```
new RaisedButton(
              child: new Text('upload'),
              onPressed: () async {
                var file = await ImagePicker.pickImage(source: ImageSource.camera);
                upload(file);
              })
```

## Logs

This is the error log in my logcat
```
05-31 13:42:48.600 17510-17510/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sxw365.sxwapp, PID: 17510
                                                   java.lang.RuntimeException: Unable to resume activity {com.sxw365.sxwapp/com.example.sxwapp.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.sxw365.sxwapp/com.example.sxwapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3132)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
                                                    Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.sxw365.sxwapp/com.example.sxwapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3730)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3119)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                       at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.getFullImagePath(ImagePickerDelegate.java:143)
                                                       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleTakePictureResult(ImagePickerDelegate.java:369)
                                                       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:349)
                                                       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
                                                       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:146)
                                                       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:139)
                                                       at com.example.sxwapp.MainActivity.onActivityResult(MainActivity.java:52)
                                                       at android.app.Activity.dispatchActivityResult(Activity.java:6597)
                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3726)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3119) 
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:165) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:150) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682) 
                                                   
```
## other 
The size of the picture is about 6M~7M, and the source of the picture is the camera.

Running in debug mode

## flutter doctor -v
```
[✓] Flutter (Channel master, v0.4.5-pre.85, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
    • Flutter version 0.4.5-pre.85 at /Users/cai/fluttersdk/flutter
    • Framework revision 677df7c351 (6 days ago), 2018-05-24 16:33:46 -0700
    • Engine revision abd74ed5ed
    • Dart version 2.0.0-dev.55.0.flutter-97b6c2e09d

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Android NDK at /Users/cai/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.12.1

[✓] Connected devices (3 available)
    • GEM 703LT  • XJC6R16107001515                         • android-arm64 • Android 6.0 (API 23)
    •            • c1a72d5adaafd7469108babf59ba102437a09de2 • ios           • iOS
    • iPad mini2 • 58366e2a63aae6f85e6e806039316c27faa52868 • ios           • iOS 10.0.2
```

**Comment by zoechi** [comment]
What actions causes this exception? Accepting a taken photo, cancel, ...?

**Comment by zoechi** [comment]
@Hixie

**Comment by CaiJingLong** [comment]
I check the log, seem in ImagePickerDelegate's line 420, the `pendingCameraMediaUri` is null.
So the line 149 is NPE.
I plan to add some logs to help track why the URI is empty.

**Comment by CaiJingLong** [comment]
I can't resolve the problem.
The device memory is 2G, and I capture picture from camera, then flutter activity will recreate.

**Comment by CaiJingLong** [comment]
Now, I use android activity to capture image from camera,
I hope the problem can be fix future.

**Comment by arrowoliver** [comment]
I am facing the same issue.
Any update on this issue?

**Comment by zoechi** [comment]
Looks similar to #17950

**Comment by CaiJingLong** [comment]
maybe is #17950
