### ISSUE TITLE
Gradle fails to build any flutter application

### ISSUE THREAD

**Issue by ng1905** [flutter/flutter#18088]
## Steps to Reproduce

1. flutter create test01
2. cd test01
3. flutter run

## Logs

```
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                       0,4s
Resolving dependencies...                                        
* Error running Gradle:
Exit code 1 from: /home/noah/Git/test01/android/gradlew app:properties:
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: compileSdkVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:551)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy24.afterEvaluate(Unknown Source)
...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/noah/Git/test01/android/app/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find com.android.tools:common:36.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/36.0.1/common-36.0.1.pom
         https://jcenter.bintray.com/com/android/tools/common/36.0.1/common-36.0.1.jar
         https://dl.google.com/dl/android/maven2/com/android/tools/common/36.0.1/common-36.0.1.pom
         https://dl.google.com/dl/android/maven2/com/android/tools/common/36.0.1/common-36.0.1.jar
```

```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale de_DE.UTF-8)
    • Flutter version 0.4.4 at /home/noah/Programme/flutter
    • Framework revision f9bb4289e9 (vor 3 Wochen), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/noah/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/noah/Programme/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/noah/Programme/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 5X • 024f3b092152ab5a • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by ng1905** [comment]
I don't know why this happened on a fresh install of flutter, but I just fixed it.
For anyone having the same issue, remove ~/.gradle and re-run ``flutter run``

**Comment by Therebelentropy** [comment]
> I don't know why this happened on a fresh install of flutter, but I just fixed it.
> For anyone having the same issue, remove ~/.gradle and re-run `flutter run`

How do you remove ~/.gradle, Sorry if it's a very easy doubt, but I am still unable to figure it out.

**Comment by ng1905** [comment]
@Therebelentropy ~/.gradle is the folder location on Linux, where ~ is the equivalent of C:\Users\[USERNAME] on Windows. Might be that the folder is also called "gradle" (without the dot) on Windows machines.

**Comment by harishsambasivam** [comment]
> > I don't know why this happened on a fresh install of flutter, but I just fixed it.
> > For anyone having the same issue, remove ~/.gradle and re-run `flutter run`
> 
> How do you remove ~/.gradle, Sorry if it's a very easy doubt, but I am still unable to figure it out.

rm -rf ~/.gradle

**Comment by Zigdon7** [comment]
For anyone else who comes across this issue, I deleted my build folder and it finally worked
