### ISSUE TITLE
File<popup_menu.dart> bug

### ISSUE THREAD

**Issue by trycat110** [flutter/flutter#18105]
```
I/flutter (28622): When the exception was thrown, this was the stack:
I/flutter (28622): #2      showMenu (package:flutter/src/material/popup_menu.dart)
I/flutter (28622): #3      _PopupMenuButtonState.showButtonMenu (package:flutter/src/material/popup_menu.dart:880:5)
I/flutter (28622): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (28622): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (28622): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (28622): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (28622): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (28622): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (28622): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (28622): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (28622): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (28622): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (28622): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (28622): #15     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (28622): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (28622): (elided 2 frames from class _AssertionError)
I/flutter (28622): 
I/flutter (28622): Handler: onTap
I/flutter (28622): Recognizer:
I/flutter (28622):   TapGestureRecognizer#0bec0(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (28622):   Offset(337.7, 57.7), sent tap down)
I/flutter (28622): Another exception was thrown: 'package:flutter/src/material/popup_menu.dart': Failed assertion: line 715 pos 10: 'items != null && items.isNotEmpty': is not true.
```

**Comment by chinmaygarde** [comment]
Have you verified that the items passed to the `showMenu` method are not null or empty as stated in the stack trace?

If you think this is a bug in the framework, please provide a reduced test case along with the other information requested in the issue template.

**Comment by zoechi** [comment]
Closing due to inactivity.
