### ISSUE TITLE
Flutter build goes to infinite Initializing gradle Loading

### ISSUE THREAD

**Issue by nitishk72** [flutter/flutter#18106]
1. I had just installed Flutter and Everything is working fine
2. But when I try to RUN app in Android Studio on my emulator it takes infinite loading
3.  When I try to Run command flutter build APK then I get this error

## Logs

C:\Users\nitishk72\AndroidStudioProjects\flutter_app>flutter build apk
Initializing gradle...                                          /
Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Users\nitishk72\AndroidStudioProjects\flutter_app\android\gradlew.bat -v:
Downloading https://services.gradle.org/distributions/gradle-4.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".
Sending crash report to Google.
Crash report sent (report ID: 2967c855d2d2238e)
Crash report written to C:\Users\nitishk72\AndroidStudioProjects\flutter_app\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

```
```
C:\Users\nitishk72\AndroidStudioProjects\flutter_app>flutter doctor -v
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.81], locale en-IN)
    • Flutter version 0.4.4 at C:\flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\nitishk72\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```
```

**Comment by PascalProgrammingX** [comment]
Goto Android Studio - File - Other Setting - Defaukt Project Structure
Uncheck use Embeded JDk
Below, set your JDK path.
Found in Program files - Java - Jdk.

**Comment by shahidpacmahn** [comment]
facing the same problem
how to solve?

**Comment by nitishk72** [comment]
@shahidpacmahn wait for sometime. Basically in background some file is being downloaded. In my case it took 25 minutes to complete the process

**Comment by PascalProgrammingX** [comment]
Turn off your Anti virus.  If win 10 turn off Windows Defender.
