### ISSUE TITLE
[Camera Plugin] throws IllegalStateException: swapBuffers: EGL error: 0x300d when stop video recording

### ISSUE THREAD

**Issue by jzillmann** [flutter/flutter#18138]
Checked out flutter plugins repository at a6f2ecbc2b47e3bb1a23795983104733a9dd761a (v0.2.1).
Pushed on my Galaxy Tab A (2016) device, SM-T280.
Flutter is on 0.3.2.

- The app opens
- I can start video recording
- When i stop video recording i'm seeing this:
```
E/CameraDeviceGLThread-1( 7976): Received exception on GL render thread: 
E/CameraDeviceGLThread-1( 7976): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:729)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-1( 7976): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-1( 7976): 	at android.os.Looper.loop(Looper.java:145)
E/CameraDeviceGLThread-1( 7976): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Full log:
```
Running "flutter packages get" in example...
Launching lib/main.dart on SM T280 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk (30.4MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate( 7976): onResume setting current activity to this
I/FlutterActivityDelegate( 7976): onResume setting current activity to this
I/Timeline( 7976): Timeline: Activity_idle id: android.os.BinderProxy@13264778 time:1732988
Syncing files to device SM T280...
D/ViewRootImpl( 7976): ViewPostImeInputStage ACTION_DOWN
I/CameraManager( 7976): Using legacy camera HAL.
I/CameraDeviceState( 7976): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1( 7976): Configure outputs: 2 surfaces configured.
D/Camera  ( 7976): app passed NULL surface
I/RequestThread-1( 7976): configureOutputs - set take picture size to 1616x1212
I/CameraDeviceState( 7976): Legacy camera service transitioning to state IDLE
I/RequestQueue( 7976): Repeating capture request set.
W/LegacyRequestMapper( 7976): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/CameraDeviceState( 7976): Legacy camera service transitioning to state CAPTURING
D/ViewRootImpl( 7976): ViewPostImeInputStage ACTION_DOWN
I/RequestQueue( 7976): Repeating capture request cancelled.
I/CameraDeviceState( 7976): Legacy camera service transitioning to state IDLE
I/CameraDeviceState( 7976): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1( 7976): Configure outputs: 2 surfaces configured.
E/BufferQueueProducer( 7976): [unnamed-7976-2] cancelBuffer: slot 1 is not owned by the producer (state = 0)
E/BufferQueueProducer( 7976): [unnamed-7976-2] cancelBuffer: slot 2 is not owned by the producer (state = 3)
E/BufferQueueProducer( 7976): [unnamed-7976-2] cancelBuffer: slot 7 is not owned by the producer (state = 0)
D/Camera  ( 7976): app passed NULL surface
I/CameraDeviceState( 7976): Legacy camera service transitioning to state IDLE
I/RequestQueue( 7976): Repeating capture request set.
W/LegacyRequestMapper( 7976): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/CameraDeviceState( 7976): Legacy camera service transitioning to state CAPTURING
D/ViewRootImpl( 7976): ViewPostImeInputStage ACTION_DOWN
E/[EGL-ERROR]( 7976): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b4008; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR]( 7976): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b4008; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR]( 7976): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b4008; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR]( 7976): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b4008; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/CameraDeviceGLThread-1( 7976): Received exception on GL render thread: 
E/CameraDeviceGLThread-1( 7976): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:729)
E/CameraDeviceGLThread-1( 7976): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-1( 7976): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-1( 7976): 	at android.os.Looper.loop(Looper.java:145)
E/CameraDeviceGLThread-1( 7976): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/CameraDeviceState( 7976): Legacy camera service transitioning to state ERROR
E/CameraCaptureSession( 7976): Session 1: Exception while stopping repeating: 
E/CameraCaptureSession( 7976): android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
E/CameraCaptureSession( 7976): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
E/CameraCaptureSession( 7976): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
E/CameraCaptureSession( 7976): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:336)
E/CameraCaptureSession( 7976): 	at io.flutter.plugins.camera.CameraPlugin$Camera.closeCaptureSession(CameraPlugin.java:711)
E/CameraCaptureSession( 7976): 	at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:658)
E/CameraCaptureSession( 7976): 	at io.flutter.plugins.camera.CameraPlugin$Camera.stopVideoRecording(CameraPlugin.java:650)
E/CameraCaptureSession( 7976): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:237)
E/CameraCaptureSession( 7976): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:199)
E/CameraCaptureSession( 7976): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/CameraCaptureSession( 7976): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/CameraCaptureSession( 7976): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraCaptureSession( 7976): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/CameraCaptureSession( 7976): 	at android.os.Looper.loop(Looper.java:130)
E/CameraCaptureSession( 7976): 	at android.app.ActivityThread.main(ActivityThread.java:6939)
E/CameraCaptureSession( 7976): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 7976): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CameraCaptureSession( 7976): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/CameraCaptureSession( 7976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
I/flutter ( 7976): Error: videoRecordingFailed
I/flutter ( 7976): Error Message: The camera device has encountered a serious error
E/RequestThread-1( 7976): Timed out while waiting for request to complete.
W/CaptureCollector( 7976): Preview buffers dropped for request: 1
E/CameraDeviceState( 7976): Cannot receive result while in state: 0
E/CameraDeviceState( 7976): Cannot receive result while in state: 0
E/CameraDeviceState( 7976): Cannot receive result while in state: 0
E/BufferQueueProducer( 7976): [unnamed-7976-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer( 7976): [unnamed-7976-3] cancelBuffer: BufferQueue has been abandoned
```

Potential Solution: https://stackoverflow.com/questions/27907090/android-camera-2-api/32621903#32621903

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jzillmann** [comment]
Hey @zoechi , just upgraded flutter and the camera plugin to 0.2.3. Output of the doctor is 
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.7.3 at /Users/jz/Documents/mobile/flutter
    • Framework revision 3b309bda07 (12 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/jz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • SM T280 • 5203c5494d2eb300 • android-arm • Android 5.1.1 (API 22)
```

The video is recorded, but the exception is still part of the log:
```
I/CameraManager(20883): Using legacy camera HAL.
I/CameraDeviceState(20883): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1(20883): Configure outputs: 2 surfaces configured.
D/Camera  (20883): app passed NULL surface
I/RequestThread-1(20883): configureOutputs - set take picture size to 1616x1212
I/CameraDeviceState(20883): Legacy camera service transitioning to state IDLE
I/RequestQueue(20883): Repeating capture request set.
W/LegacyRequestMapper(20883): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/CameraDeviceState(20883): Legacy camera service transitioning to state CAPTURING
D/ViewRootImpl(20883): ViewPostImeInputStage ACTION_DOWN
I/RequestQueue(20883): Repeating capture request cancelled.
I/CameraDeviceState(20883): Legacy camera service transitioning to state IDLE
I/CameraDeviceState(20883): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-1(20883): Configure outputs: 2 surfaces configured.
E/BufferQueueProducer(20883): [unnamed-20883-2] cancelBuffer: slot 2 is not owned by the producer (state = 0)
E/BufferQueueProducer(20883): [unnamed-20883-2] cancelBuffer: slot 3 is not owned by the producer (state = 0)
E/BufferQueueProducer(20883): [unnamed-20883-2] cancelBuffer: slot 4 is not owned by the producer (state = 3)
D/Camera  (20883): app passed NULL surface
I/CameraDeviceState(20883): Legacy camera service transitioning to state IDLE
I/RequestQueue(20883): Repeating capture request set.
W/LegacyRequestMapper(20883): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
I/flutter (20883): Snackbar: Saving video to /storage/emulated/0/talkdeeply-offline/tmp/video-1.mp4
I/CameraDeviceState(20883): Legacy camera service transitioning to state CAPTURING
D/ViewRootImpl(20883): ViewPostImeInputStage ACTION_DOWN
E/[EGL-ERROR](20883): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b5808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](20883): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b5808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](20883): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b5808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/[EGL-ERROR](20883): void __egl_platform_dequeue_buffer(egl_surface*):1997: failed to dequeue buffer from native window 0xb44b5808; err = -19, buf = 0x0,max_allowed_dequeued_buffers 3
E/CameraDeviceGLThread-1(20883): Received exception on GL render thread: 
E/CameraDeviceGLThread-1(20883): java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
E/CameraDeviceGLThread-1(20883): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
E/CameraDeviceGLThread-1(20883): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
E/CameraDeviceGLThread-1(20883): 	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:729)
E/CameraDeviceGLThread-1(20883): 	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
E/CameraDeviceGLThread-1(20883): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/CameraDeviceGLThread-1(20883): 	at android.os.Looper.loop(Looper.java:145)
E/CameraDeviceGLThread-1(20883): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/CameraDeviceState(20883): Legacy camera service transitioning to state ERROR
E/CameraCaptureSession(20883): Session 1: Exception while stopping repeating: 
E/CameraCaptureSession(20883): android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
E/CameraCaptureSession(20883): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
E/CameraCaptureSession(20883): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
E/CameraCaptureSession(20883): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:336)
E/CameraCaptureSession(20883): 	at io.flutter.plugins.camera.CameraPlugin$Camera.closeCaptureSession(CameraPlugin.java:711)
E/CameraCaptureSession(20883): 	at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:658)
E/CameraCaptureSession(20883): 	at io.flutter.plugins.camera.CameraPlugin$Camera.stopVideoRecording(CameraPlugin.java:650)
E/CameraCaptureSession(20883): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:237)
E/CameraCaptureSession(20883): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:199)
E/CameraCaptureSession(20883): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/CameraCaptureSession(20883): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/CameraCaptureSession(20883): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraCaptureSession(20883): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/CameraCaptureSession(20883): 	at android.os.Looper.loop(Looper.java:130)
E/CameraCaptureSession(20883): 	at android.app.ActivityThread.main(ActivityThread.java:6939)
E/CameraCaptureSession(20883): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(20883): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CameraCaptureSession(20883): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/CameraCaptureSession(20883): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
I/flutter (20883): Snackbar: Error: videoRecordingFailed
I/flutter (20883): The camera device has encountered a serious error
I/flutter (20883): Snackbar: Video recorded to: /storage/emulated/0/talkdeeply-offline/tmp/video-1.mp4
E/RequestThread-1(20883): Timed out while waiting for request to complete.
W/CaptureCollector(20883): Preview buffers dropped for request: 1
E/CameraDeviceState(20883): Cannot receive result while in state: 0
E/CameraDeviceState(20883): Cannot receive result while in state: 0
E/CameraDeviceState(20883): Cannot receive result while in state: 0
E/BufferQueueProducer(20883): [unnamed-20883-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] queueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(20883): [unnamed-20883-3] cancelBuffer: BufferQueue has been abandoned

```

**Comment by vijaykanta** [comment]
I am getting the same error. I thought it was because I was creating a custom directory using file provider api before recording but the stoprecording() function was from stock library. My phone is a Samsung S5.

**Comment by Chank1e** [comment]
I found solution. At least for myself)
https://github.com/flutter/flutter/issues/23039#issuecomment-430221188

**Comment by devdennysegura** [comment]
on last version of flutter this is solved.

**Comment by zoechi** [comment]
@jzillmann can you confirm that this is solved?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
