### ISSUE TITLE
showSearch cannot be reopened after closing with OS back button

### ISSUE THREAD

**Issue by westy92** [flutter/flutter#18145]
## Steps to Reproduce

1. call `showSearch()`
2. hit the OS back button on Android
3. try to call `showSearch()` again.

Everything works fine as long as you call `close(context, null)` inside your `SearchDelegate`, which is done when tapping the back arrow in the example.

## Logs

```
I/flutter (15760): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (15760): The following assertion was thrown while handling a gesture:
I/flutter (15760): 'package:flutter/src/material/search.dart': Failed assertion: line 55 pos 10: 'delegate._result ==
I/flutter (15760): null || delegate._result.isCompleted': is not true.
I/flutter (15760):
I/flutter (15760): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15760): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15760): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15760):   https://github.com/flutter/flutter/issues/new
I/flutter (15760):
I/flutter (15760): When the exception was thrown, this was the stack:
I/flutter (15760): #2      showSearch (package:flutter/src/material/search.dart)
I/flutter (15760): #3      _HomePageState.build.<anonymous closure> (file:///home/westy92/Source/checkiday-mobile/lib/main.dart:316:15)
I/flutter (15760): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (15760): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (15760): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (15760): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (15760): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (15760): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (15760): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (15760): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (15760): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (15760): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (15760): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (15760): #15     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (15760): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (15760): (elided 2 frames from class _AssertionError)
I/flutter (15760):
I/flutter (15760): Handler: onTap
I/flutter (15760): Recognizer:
I/flutter (15760):   TapGestureRecognizer#25139(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (15760):   Offset(357.0, 54.1), sent tap down)
```

```
Analyzing checkiday-mobile...                                    
No issues found! (ran in 16.0s)
```

```
[✓] Flutter (Channel dev, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/westy92/Source/flutter
    • Framework revision c7ea3ca377 (4 days ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/westy92/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/westy92/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/westy92/android-studio
    • Flutter plugin version 21.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Pixel • FA74C0300048 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by westy92** [comment]
It looks like https://docs.flutter.io/flutter/widgets/WillPopScope-class.html may be helpful.

**Comment by westy92** [comment]
This hack at least gets things to work for now:

```dart
class _MySearchDelegate extends SearchDelegate<String> {
  // ...

  @override
  Widget buildLeading(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        close(context, null);
        return false;
      },
      child: IconButton(
        tooltip: 'Back',
        icon: AnimatedIcon(
          icon: AnimatedIcons.menu_arrow,
          progress: transitionAnimation,
        ),
        onPressed: () {
          close(context, null);
        },
      ),
    );
  }

  // ...
}
```

**Comment by HansMuller** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
Thanks for the report. I was able to reproduce it and pushed a fix out for review.
