### ISSUE TITLE
Can't find devise : DeviceSelectorAction

### ISSUE THREAD

**Issue by koami** [flutter/flutter#18162]
## What happened

Juste made the last update and the issue occure, using Win 10.

## Version information

Android Studio `3.1.2` • Flutter plugin `io.flutter 25.0.1` • Dart plugin `173.4700`

Error getting Flutter sdk information.

## Exception

update failed for AnAction(io.flutter.actions.DeviceSelectorAction) with ID=Flutter.DeviceSelector: Not a JSON Object: null

```
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfigImpl(FlutterSdk.java:454)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:409)
	at io.flutter.android.IntelliJAndroidSdk.chooseAndroidHome(IntelliJAndroidSdk.java:118)
	at io.flutter.android.AndroidSdk.createFromProject(AndroidSdk.java:35)
	at io.flutter.actions.OpenEmulatorAction.getEmulatorActions(OpenEmulatorAction.java:22)
	at io.flutter.actions.DeviceSelectorAction.updateActions(DeviceSelectorAction.java:130)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$2(DeviceSelectorAction.java:72)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:653)
	at io.flutter.FlutterUtils.invokeAndWait(FlutterUtils.java:61)
	at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:71)
	at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:66)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:257)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:227)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1005)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:182)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:643)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:624)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:594)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$13(FocusManagerImpl.java:476)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2795)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.runListenerAction(ActionManagerImpl.java:1420)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.notifyListeners(ActionManagerImpl.java:1410)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1394)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by zoechi** [comment]
Just adding the output of `flutter doctor` would be better than 

> Android Studio 3.1.2 • Flutter plugin io.flutter 25.0.1 • Dart plugin 173.4700

**Comment by koami** [comment]
Wrong script snapshot version, expected '41bd5eab5c21a0d6a57f3da2d31d9545' found '1b155eedb
The Output of "flutter doctor"

Wrong script snapshot version, expected '41bd5eab5c21a0d6a57f3da2d31d9545' found '1b155eedb
b3a2640a88d2e54d2f2d204'
'
Unhandled exception:
Could not import "package:flutter_tools/src/commands/emulators.dart" from "package:flutter_
tools/executable.dart": FileSystemException: Cannot open file, path = 'C:\Users\Koami\flutt
er\packages\flutter_tools\lib\src\commands\emulators.dart' (OS Error: The system cannot fin
d the file specified.
, errno = 2)
null
Error: Unable to create dart snapshot for flutter tool.

**Comment by zoechi** [comment]
Sounds like something is wrong with your flutter installation.
Try `git clean -xffd` `flutter doctor` in your Flutter install directory.

**Comment by koami** [comment]
Already done. There's the flutter doctor output after the pull;
 cat: /c/Users/Koami/flutter/bin/internal/dart-sdk.version: No such file or directory

**Comment by zoechi** [comment]
Can update to a newer PowerShell version?

**Comment by koami** [comment]
I updated and still get the same error message.

**Comment by koami** [comment]
Solved:

Delete the flutter repository on my laptop and replace it with the unzip of the one on the flutter.io.
