### ISSUE TITLE
"Result of truncating division is Infinity or NaN" in RenderList

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1819]
Not sure what I did, but I got this while playing around in Stocks with animations set very slow:
```
[Android] I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
[Android] I/flutter : The following exception was raised during performLayout():
[Android] I/flutter : Unsupported operation: Result of truncating division is Infinity or NaN
[Android] I/flutter : The following RenderObject was being processed when the exception was fired:
[Android] I/flutter : RenderList NEEDS-LAYOUT
[Android] I/flutter : This RenderObject had the following owner:
[Android] I/flutter : ListViewport ← Listener ← Listener ← _GestureSemantics ← GestureDetector ← ScrollableList ← StockList ← Container-['StockHomeTab.market'] ← RepaintBoundary-['['Sto\
ckHomeTab.market']'] ← PageViewport ← ⋯
[Android] I/flutter : This RenderObject had the following descendants (showing up to depth 5):
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter :   RenderRepaintBoundary
[Android] I/flutter :     RenderSemanticsGestureHandler
[Android] I/flutter :       RenderPointerListener
[Android] I/flutter :         RenderDecoratedBox
[Android] I/flutter :           RenderPadding
[Android] I/flutter : Stack trace:
[Android] I/flutter : #0      double._trunc_div (dart:core-patch/double.dart:33)
[Android] I/flutter : #1      double.~/ (dart:core-patch/double.dart:31)
[Android] I/flutter : #2      _VirtualListViewportElement.layout (packages/flutter/src/widgets/scrollable_list.dart:196)
[Android] I/flutter : #3      RenderObject.invokeLayoutCallback (packages/flutter/src/rendering/object.dart:1113)
[Android] I/flutter : #4      RenderList.performLayout (packages/flutter/src/rendering/list.dart:130)
[Android] I/flutter : #5      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:944)
[Android] I/flutter : #6      RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:922)
[Android] I/flutter : #7      BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
[Android] I/flutter : #8      WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:95)
[Android] I/flutter : #9      BindingBase&Scheduler&Gesturer&MojoShell&Renderer._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:77)
[Android] I/flutter : #10     BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:273)
[Android] I/flutter : #11     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:250)
[Android] I/flutter : #12     _beginFrame (file:///usr/local/google/home/ianh/dev/engine/src/out/android_Debug/gen/sky/bindings/hooks.dart:48)
```

**Comment by abarth** [comment]
Is there something collapsing the item extent?  If it were zero, I could see this exploding.

**Comment by Hixie** [comment]
I'm closing this because I've no idea how to reproduce it and this code is about to be refactored.
