### ISSUE TITLE
Document how to fix "Too many open files in system" error on macOS

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter#18225]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target /Users/liaoyuhao/mblock/lib/main.dart --preview-dart-2 --filesystem-scheme org-dartlang-root --depfile /Users/liaoyuhao/mblock/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --asset-dir /Users/liaoyuhao/mblock/build/app/intermediates/flutter/debug/flutter_assets

## exception

FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files in system, errno = 23)

```
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:61)
#1      Uri.base (dart:core-patch/dart:core/uri_patch.dart:20)
#2      current (package:path/path.dart:82)
#3      new Context (package:path/src/context.dart:31)
#4      LocalFileSystem.path (package:file/src/backends/local/local_file_system.dart:34)
#5      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:175)
<asynchronous suspension>
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#7      Future.wait (dart:async/future.dart:385)
#8      writeBundle (package:flutter_tools/src/bundle.dart:173)
<asynchronous suspension>
#9      assemble (package:flutter_tools/src/bundle.dart:163)
<asynchronous suspension>
#10     build (package:flutter_tools/src/bundle.dart:103)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:67)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#29     new Future.sync (dart:async/future.dart:222)
#30     CommandRunner.run (package:args/command_runner.dart:109)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     runZoned (dart:async/zone.dart:1501)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:49)
#40     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#41     main (file:///Users/liaoyuhao/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale zh-Hans-CN)
    • Flutter version 0.4.4 at /Users/liaoyuhao/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/liaoyuhao/sdk
    • Android NDK at /Users/liaoyuhao/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/liaoyuhao/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4127.31

[!] VS Code (version 1.23.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone 8                  • 457655CF-2A61-4403-AF5F-F551EBDB1217 • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by xuexin** [comment]
My app have a huge number of assets(4000+), maybe it is the cause of this issue?

**Comment by zoechi** [comment]
Perhaps https://gist.github.com/devinrhode2/4cbf7f02a9701510d61f5be0515b8286

**Comment by xuexin** [comment]
Thx @zoechi 
This issue don't happen again, after I restart mac.

**Comment by goderbauer** [comment]
We should probably document this somewhere.

**Comment by zoechi** [comment]
@Sfshaza or increase available file handlrs

**Comment by goderbauer** [comment]
@Sfshaza No, I believe the fix on MacOS is to increase the number of available file handlers by running `ulimit -S -n 2048`. We are also doing this when running flutter on our infrastructure for the same reasons: https://github.com/flutter/flutter/blob/71b2cfb2a0724af692c298a62f86b3a934b6d3ca/.travis.yml#L47

**Comment by ShannonChenCHN** [comment]
@goderbauer Thanks for giving the reason and the solution. But I'm wondering would the command `ulimit -S -n 2048` has any side effect?

**Comment by robindespouys** [comment]
Increasing the number of authorized files read and write should never be considered as a good common pratique.

@ShannonChenCHN 

I may suggest simply trying to kill some overwhelming processes.
Perhaps the ones responsable of the increase in number of file manipulations.

You should try

ps -e -a |grep flut |for i in `awk {'print$1'}`; do kill -9 $i; done

You should tune the inputs of the grep command and also maybe watchout to other mighty daemons.

Have fun :)

**Comment by ShannonChenCHN** [comment]
@robindespouys Thanks for detailed explanation! But I found the reason I got file exception is the very first calling of `Uri.base.scheme`, so I figured it is a flutter issue.

SDK version:
```
➜  / flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
```

Exception log:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following FileSystemException was thrown building _DefaultInheritedProviderScope<AlbumStateContainer>(value: <not yet loaded>):
Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)

The relevant error-causing widget was: 
  ChangeNotifierProvider<AlbumStateContainer> file:///Users/xianglongchen/Desktop/CtripGitRepo/ctrip_flutter/lib/main.dart:24:14
When the exception was thrown, this was the stack: 
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:66:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:23:41)
#2      _HotelAlbumPageState.initState (package:ctrip_flutter/hotel/module/album/page/hotel_album_page.dart:56:34)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by ShannonChenCHN** [comment]
@robindespouys Thanks for detailed explanation! But I found the reason I got file exception is the very first calling of `Uri.base.scheme`, so I figured it is a flutter issue.

SDK version:
```
➜  / flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
```

Exception log:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following FileSystemException was thrown building _DefaultInheritedProviderScope<AlbumStateContainer>(value: <not yet loaded>):
Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)

The relevant error-causing widget was: 
  ChangeNotifierProvider<AlbumStateContainer> file:///Users/xianglongchen/Desktop/xxxx/xxxx_flutter/lib/main.dart:24:14
When the exception was thrown, this was the stack: 
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:66:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:23:41)
#2      _HotelAlbumPageState.initState (package:xxxx_flutter/hotel/module/album/page/hotel_album_page.dart:56:34)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by ShannonChenCHN** [comment]
> @robindespouys Thanks for detailed explanation! But I found the reason why I got file exception is the very first calling of `Uri.base.scheme`, so I figured it is a flutter issue.
> 
> SDK version:
> 
> ```
> ➜  / flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E287, locale
>     zh-Hans-CN)
> ```
> 
> Exception info:
> ![image](https://user-images.githubusercontent.com/15443132/90587727-b016f180-e20c-11ea-9891-5a040d74c791.png)

We finally found out the real reason now! Because `Uri.base` try to access current working directory, but we called `-changeCurrentDirectoryPath:` to change current directory path to a new path and then we removed that directory, this made current directory path become `null`. Consequently, calling `Uri.base` would leads a file system exception.

We fixed this issue and that file system exception doesn't come again.

**Comment by robindespouys** [comment]
@ShannonChenCHN 

Really thank you for this explanation. Now I understand what was the origin of the problem. 
Good job on finding the Truth !! :)
