### ISSUE TITLE
Calling showModalBottomSheet causes exception, seemingly related to localization

### ISSUE THREAD

**Issue by kengorab** [flutter/flutter#18254]
## Steps to Reproduce

1. Create a new flutter application: `flutter create bottom_modal_sheet_test`
2. Replace `main.dart` with this code (taken from the [bottom_modal_sheet_demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/modal_bottom_sheet_demo.dart) example):

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // The following will print 'null'
    print(MaterialLocalizations.of(context));

    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(title: const Text('Modal bottom sheet')),
        body: new Center(
          child: new RaisedButton(
            child: const Text('SHOW BOTTOM SHEET'),
            onPressed: () {
              showModalBottomSheet<void>(context: context, builder: (BuildContext context) {
                return new Container(
                  child: new Padding(
                    padding: const EdgeInsets.all(32.0),
                    child: new Text('This is the modal bottom sheet. Click anywhere to dismiss.',
                      textAlign: TextAlign.center,
                      style: new TextStyle(
                        color: Theme.of(context).accentColor,
                        fontSize: 24.0
                      )
                    )
                  )
                );
              });
            }
          )
        )
      )
    );
  }
}
```
3. Run the project: `flutter run`
4. Tap the `SHOW BOTTOM SHEET` button, and an error will be raised (verbose output in Logs section below)

## Logs
```
[+11846 ms] I/flutter (26697): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +9 ms] I/flutter (26697): The following NoSuchMethodError was thrown while handling a gesture:
[        ] I/flutter (26697): The getter 'modalBarrierDismissLabel' was called on null.
[        ] I/flutter (26697): Receiver: null
[        ] I/flutter (26697): Tried calling: modalBarrierDismissLabel
[        ] I/flutter (26697):
[        ] I/flutter (26697): When the exception was thrown, this was the stack:
[  +43 ms] I/flutter (26697): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
[   +1 ms] I/flutter (26697): #1      showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart:286:53)
[        ] I/flutter (26697): #2      MyApp.build.<anonymous closure> (file:///Users/kengorab/Desktop/bottom_modal_sheet_test/lib/main.dart:18:15)
[        ] I/flutter (26697): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
[        ] I/flutter (26697): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
[  +10 ms] I/flutter (26697): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[   +2 ms] I/flutter (26697): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] I/flutter (26697): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
[        ] I/flutter (26697): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] I/flutter (26697): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] I/flutter (26697): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] I/flutter (26697): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] I/flutter (26697): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] I/flutter (26697): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] I/flutter (26697): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] I/flutter (26697): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] I/flutter (26697): #16     _invoke1 (dart:ui/hooks.dart:134:13)
[        ] I/flutter (26697): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
[   +7 ms] I/flutter (26697):
[   +1 ms] I/flutter (26697): Handler: onTap
[        ] I/flutter (26697): Recognizer:
[        ] I/flutter (26697):   TapGestureRecognizer#0898f(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
[        ] I/flutter (26697):   Offset(156.1, 323.1), sent tap down)
[        ] I/flutter (26697): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
The error occurs here (within `flutter/lib/src/material/bottom_sheet.dart`):

```dart
Future<T> showModalBottomSheet<T>({
  @required BuildContext context,
  @required WidgetBuilder builder,
}) {
  assert(context != null);
  assert(builder != null);
  return Navigator.push(context, new _ModalBottomSheetRoute<T>(
    builder: builder,
    theme: Theme.of(context, shadowThemeOnly: true),
    barrierLabel: MaterialLocalizations.of(context).modalBarrierDismissLabel,
    // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ HERE IS THE ERROR
  ));
}
```
since `MaterialLocalizations.of(context)` returns `null`. If you look at the first line of my `build` method in my example, I've also printed out that value, which prints `null`.

No errors when running `flutter analyze`

Output of `flutter doctor -v`:
```
[~/Desktop/bottom_modal_sheet_test] → flutter doctor -v
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.4 at /usr/local/bin/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
    • Android SDK at /Users/kengorab/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.0-rc2
    • ANDROID_HOME = /Users/kengorab/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by HansMuller** [comment]
The problem here is that MaterialApp creates the MaterialLocalizations inherited widget, along with many others. So the context you're using to lookup (like upwards) the MaterialLocalizations widget is above it.

There are various ways to avoid this. Here's one way:
```
void main() => runApp(new MaterialApp(home: new MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // The following will print 'null'
    print(MaterialLocalizations.of(context));
    return new Scaffold(
    ...
```

**Comment by kengorab** [comment]
Okay, that makes sense. I actually ran into a similar-seeming issue when trying to use `Navigator.push` with the same initial setup, and gnawf's answer in #13795 feels similar. Is there any documentation around this that I missed?

Or maybe should it just be the recommendation that `MaterialApp` be immediately used within the `runApp` call, and not part of the underlying widget tree? Or maybe that should be in the template when `flutter create` runs?

At any rate, thank you for your help, this can probably be considered closed at this point. Hopefully others who encounter this bug will find this and it'll help them.

**Comment by HansMuller** [comment]
I agree that the inherited widget lookup widgets can be confusing. There's a discussion of the kind of problem you ran into in https://docs.flutter.io/flutter/material/Scaffold/of.html however the failure mode is always confusing, and the docs for most of the other inherited widgets don't cover this case.

**Comment by Hixie** [comment]
Usually I would recommend putting the contents of the MaterialApp (the routes), and the MaterialApp itself, each into their own separate widgets, yes (even if you just have one). That's what the default `flutter create` template does, I believe.

(Putting the MaterialApp itself into a widget allows hot reload of changes to the app theme, too.)

**Comment by shunjid** [comment]
> The problem here is that `MaterialApp` creates the `MaterialLocalizations` inherited widget, along with many others. So the context you're using to lookup (like upwards) the `MaterialLocalizations` widget is above it.
> 
> There are various ways to avoid this. Here's one way:
> 
> ```dart
> void main() => runApp(new MaterialApp(home: new MyApp()));
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     // The following will print 'null'
>     print(MaterialLocalizations.of(context));
>     return new Scaffold(
>     ...
> ```

You saved my life, bro. But I didn't understand your explanation. Can you please elaborate it more easier for a beginner?
