### ISSUE TITLE
Firebase Auth Failed assertion

### ISSUE THREAD

**Issue by TheDOme6** [flutter/flutter#18310]
## Steps to Reproduce
Call the standart signinmethod from firebase in initState()

```dart
@override
  void initState() {
    super.initState();
    _signin().then((value) {
      _user = value;
      print(_user.uid);
    });
  }

  Future<FirebaseUser> _signin() async {
    final FirebaseUser user = await _auth.signInAnonymously();
    assert(user != null);
    assert(user.isAnonymous);
    assert(!user.isEmailVerified);
    assert(await user.getIdToken() != null);
    if (Platform.isIOS) {
      // Anonymous auth doesn't show up as a provider on iOS
      assert(user.providerData.isEmpty);
    } else if (Platform.isAndroid) {
      // Anonymous auth does show up as a provider on Android
      assert(user.providerData.length == 1);
      assert(user.providerData[0].providerId == 'firebase');
      assert(user.providerData[0].uid != null);
      assert(user.providerData[0].displayName == null);
      assert(user.providerData[0].photoUrl == null);
      assert(user.providerData[0].email == null);
    }

    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);

    return currentUser;
  }
```

## Logs
```

E/flutter (30187): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30187): 'file:///root/tools/FlutterProjekts/questionnaire/lib/main.dart': Failed assertion: line 101 pos 14: 'user.providerData[0].displayName == null': is not true.
E/flutter (30187): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter (30187): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter (30187): #2      SurveyState._signin (file:///root/tools/FlutterProjekts/questionnaire/lib/main.dart)
E/flutter (30187): <asynchronous suspension>
E/flutter (30187): #3      SurveyState.initState (file:///root/tools/FlutterProjekts/questionnaire/lib/main.dart:80:5)
E/flutter (30187): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter (30187): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (30187): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30187): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (30187): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (30187): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (30187): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (30187): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30187): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30187): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30187): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter (30187): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (30187): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (30187): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (30187): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
E/flutter (30187): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (30187): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (30187): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (30187): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter (30187): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter (30187): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter (30187): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter (30187): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter (30187): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter (30187): #44     ComponentElement._fi
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale de_DE.UTF-8)
    • Flutter version 0.4.4 at /root/tools/flutter
    • Framework revision f9bb4289e9 (vor 4 Wochen), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /root/Android/Sdk
    • Android NDK at /root/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /root/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /root/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Dart Code extension version 2.13.2

[✓] Connected devices (1 available)
    • HUAWEI VNS L31 • FUH0216919010873 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by TheDOme6** [comment]
Fixed it temporary by changing:
```
assert(user.providerData[0].displayName != null);
assert(user.providerData[0].email != null);
```

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@TheDOme6

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/803. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
were the issue fixed?
