### ISSUE TITLE
image.toByteData() errors on Android and iOS devices with hardware rendering

### ISSUE THREAD

**Issue by tomnewton** [flutter/flutter#18323]
If you set --enable-software-rendering, this error does not occur.

If you do a release build, or if you just run it in debug without the --enable-software-rendering flag you get the following issue:

## Steps to Reproduce

I have published a sample project which demonstrates this issue here: [https://github.com/tomnewton/imagefail](https://github.com/tomnewton/imagefail)

Just run it on an Android device (edit: now verified on iOS device too), and ensure you don't have the --enable-software-rendering flag set, or do a release build. 

```dart

  void _loadImageAndGetPixels() async {
    ByteData png = await services.rootBundle.load("images/google.png");
    Codec codec = await instantiateImageCodec(png.buffer.asUint8List());
    var frameInfo = await codec.getNextFrame();
    var image = frameInfo.image;

    var bytes = await image.toByteData(); // This operation fails.
  }
```

## Logs

```
E/flutter (24878): [ERROR:flutter/lib/ui/painting/image_encoding.cc(71)] Pixel copy failed.
E/flutter (24878): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (24878): Exception: operation failed
E/flutter (24878): #0      _MyHomePageState._loadImageAndGetPixels (file:///Users/tn/workspace/lstn/deps/tmp/imagefail/lib/main.dart:58:17)
E/flutter (24878): <asynchronous suspension>
E/flutter (24878): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
E/flutter (24878): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
E/flutter (24878): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (24878): #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (24878): #5      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (24878): #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (24878): #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (24878): #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (24878): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (24878): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (24878): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (24878): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (24878): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (24878): #14     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (24878): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.2, on Mac OS X 10.13.4 17E202, locale en-KY)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[!] VS Code (version 1.23.1)
[✓] Connected devices (3 available)
```

**Comment by tomnewton** [comment]
I setup a provision profile, and tested this on an iPhone running iOS 11.2 and the same error occurs.

**Comment by tvolkert** [comment]
Our call to [`image->makeRasterImage()`](https://github.com/flutter/engine/blob/8f023c5dacba213c9944e4da22c253803d31af89/lib/ui/painting/image_encoding.cc#L69) is returning `null`.

/cc @chinmaygarde @liyuqian

**Comment by tvolkert** [comment]
See also https://github.com/flutter/flutter/issues/17687

**Comment by chinmaygarde** [comment]
@tvolkert: The issue you linked to seems unrelated. In this instance, image encoding fails because the image dimensions are invalid. That issue is related to screenshot support of sub-hierarchies.

<img width="195" alt="screen shot 2018-06-11 at 4 00 44 pm" src="https://user-images.githubusercontent.com/44085/41261491-c522aed6-6d90-11e8-805b-4a5c7ce57f0d.png">

**Comment by chinmaygarde** [comment]
On further investigation, the root cause seems similar though. x-context images used in rendering operation where the GrContext cannot be reached. I am going to follow up with the skia folks on both issues together.

**Comment by chinmaygarde** [comment]
cc @gspencergoog

**Comment by chinmaygarde** [comment]
The Skia API update does not seem to be trivial. I patched the engine instead.

**Comment by jinfagang** [comment]
Same error got when parse a image bytes from a ImageProvider:

```
widget.imageProvider
        .resolve(new ImageConfiguration())
        .addListener((imgInfo, _) {

          print('imgInfo: $imgInfo');
      imgInfo.image.toByteData().then((data) {
        print('data.buffer.asUint8List(): ${data.buffer.asUint8List()}');
        _toSaveImgFile.writeAsBytes(data.buffer.asUint8List());
      });
    });
```

Error:

```
[ERROR:flutter/lib/ui/painting/image_encoding.cc(71)] Pixel copy failed.
E/flutter ( 2340): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2340): Exception: operation failed
E/flutter ( 2340): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
E/flutter ( 2340): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2340): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by zoechi** [comment]
@jinfagang 
Please add the output of `flutter doctor`

**Comment by jinfagang** [comment]
@zoechi Thanks for your response, already updated it

**Comment by zoechi** [comment]
This issue is closed since a while. 
It's probably better to create a new one (with a link to this one).
Sorry for not suggesting that in the first place.
