### ISSUE TITLE
Flutter Video Player Plugin doesn't support m3u8 files on Android

### ISSUE THREAD

**Issue by pyros2097** [flutter/flutter#18328]
The flutter videoplayer plugin doesn't play m3u8 video formats. But the underlying exoplayer2 for android which is used supports it.
Currently the plugin uses the `ExtractorMediaSource` of the exoplayer2 for all videos.
https://github.com/flutter/plugins/blob/master/packages/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java#L87

But exoplayer2 specifies that you need use the `HlsMediaSource` for playing HLS /dash video files.
As given here in this example. 
https://github.com/yusufcakmak/ExoPlayerSample

The videoplayer plugin should allow to pass a parameter which will decide if its a HLS video and use the HSLMediaSource so that m3u8 videos could be supported.

## Steps to Reproduce

This is a flutter app that shows the error.
https://gist.github.com/pyros2097/b839209899482d63b22ac396d213916f

## Logs
```
[+1916 ms] I/System.out(11421): Keeping screen on
[ +112 ms] I/ExoPlayerImpl(11421): Init 26ce7c7 [ExoPlayerLib/2.8.0] [generic_x86, Android SDK built for x86, Google, 27]
[  +16 ms] D/NetworkSecurityConfig(11421): No Network Security Config specified, using platform default
[+1259 ms] E/ExoPlayerImplInternal(11421): Source error.
[        ] E/ExoPlayerImplInternal(11421): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
[        ] E/ExoPlayerImplInternal(11421):      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:931)
[        ] E/ExoPlayerImplInternal(11421):      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
[        ] E/ExoPlayerImplInternal(11421):      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
[        ] E/ExoPlayerImplInternal(11421):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[        ] E/ExoPlayerImplInternal(11421):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[        ] E/ExoPlayerImplInternal(11421):      at java.lang.Thread.run(Thread.java:764)
```

```
Analyzing limitless...
No issues found! (ran in 2.3s)
```

```
[!] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/pyros2097/Applications/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5


[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/pyros2097/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/pyros2097/Android/Sdk
    • Java binary at: /home/pyros2097/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.1)
    • Android Studio at /home/pyros2097/Android/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by pyros2097** [comment]
Corresponding PR here.
https://github.com/flutter/plugins/pull/607

**Comment by pyros2097** [comment]
Closed the PR 607 and improved on it to support more video formats not just .m3u8
Here is the current PR for tracking.
https://github.com/flutter/plugins/pull/613

**Comment by pyros2097** [comment]
https://github.com/flutter/plugins/pull/613
PR Merged. Closing now.
