### ISSUE TITLE
applocalizations causes crash (only in release and profile modes) when +300 messages are localized

### ISSUE THREAD

**Issue by ebeem** [flutter/flutter#18332]
## Details
gist: https://gist.github.com/ebeem/7825c56c352d9bec84e1cd0e88c6f5b2

debugging mode works, but release mode and profile mode fail
when I delete all the translation entries from `"string_255"` to `"string_349"` in `messages_messages.dart` the app works fine in release mode, if I add just one more entry which is `"string_255"`, the app crashes again in release mode

I made the project as simple as possible, it does not actually use localizations at all, it crashes when it tries to load the messages, so as long as the delegate is there, it will crash when it tries to load the locale messages on application start.

## Steps to Reproduce
1. create a new flutter application
2. implement localization in the project and add your custom `LocalizationsDelegate` to your `MaterialApp`
3. add large unique translation entries (+300) to your `messages.*` file
4. run the app in release mode (debug mode works)

## Logs
flutter
```
Installing build/app/outputs/apk/app.apk...                  3.3s

To repeat this help message, press "h". To quit, press "q".
I/FlutterActivityDelegate(23453): onResume setting current activity to this

```

logcat

```
06-09 18:58:39.913 23373-23373/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
06-09 18:58:39.918 23373-23373/? D/AndroidRuntime: CheckJNI is OFF
06-09 18:58:40.010 23373-23373/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
06-09 18:58:40.048 23373-23373/? I/Radio-JNI: register_android_hardware_Radio DONE
06-09 18:58:40.065 23373-23373/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
06-09 18:58:40.072 897-1793/system_process I/ActivityManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.test.flutterlocalization/.MainActivity (has extras)} from uid 2000 on display 0
06-09 18:58:40.086 1804-1804/is.shortcut I/NotificationController: paused
06-09 18:58:40.097 23373-23373/? D/AndroidRuntime: Shutting down VM
06-09 18:58:40.107 1804-23376/is.shortcut D/AnalyticsDatabaseHelper: Read 1 records from analytics logs table.
06-09 18:58:40.108 1804-23376/is.shortcut D/AnalyticsHandler: Uploading analytics... 1
06-09 18:58:40.142 897-9087/system_process I/ActivityManager: Start proc 23453:com.test.flutterlocalization/u0a209 for activity com.test.flutterlocalization/.MainActivity
06-09 18:58:40.416 23453-23453/com.test.flutterlocalization I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
06-09 18:58:40.452 23453-23488/com.test.flutterlocalization I/flutter: Observatory listening on http://127.0.0.1:48093/
06-09 18:58:40.462 23453-23453/com.test.flutterlocalization I/FlutterActivityDelegate: onResume setting current activity to this
06-09 18:58:40.503 23453-23490/com.test.flutterlocalization I/OpenGLRenderer: Initialized EGL, version 1.4
06-09 18:58:40.503 23453-23490/com.test.flutterlocalization D/OpenGLRenderer: Swap behavior 1
    
    --------- beginning of crash
06-09 18:58:40.552 23453-23483/com.test.flutterlocalization A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1b in tid 23483 (1.ui)
06-09 18:58:40.549 23493-23493/? W/debuggerd: type=1400 audit(0.0:2485): avc: denied { search } for name="com.test.flutterlocalization" dev="mmcblk0p28" ino=154921 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
    type=1400 audit(0.0:2486): avc: denied { search } for name="com.test.flutterlocalization" dev="mmcblk0p28" ino=154921 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
06-09 18:58:40.570 23453-23483/com.test.flutterlocalization A/libc: failed to resend signal during crash: Operation not permitted
06-09 18:58:40.572 23493-23493/? E/DEBUG: unexpected waitpid response: n=23483, status=00000000
    debuggerd: failed to kill process 23453: No such process
06-09 18:58:40.575 897-23495/system_process W/ActivityManager:   Force finishing activity com.test.flutterlocalization/.MainActivity
06-09 18:58:40.576 897-915/system_process I/BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
06-09 18:58:40.584 897-1757/system_process D/GraphicsStats: Buffer count: 9
06-09 18:58:40.586 897-23101/system_process I/WindowManager: WIN DEATH: Window{533f3f1 u0 com.test.flutterlocalization/com.test.flutterlocalization.MainActivity}
06-09 18:58:40.586 897-23101/system_process W/WindowManager: Force-removing child win Window{76c1e57 u0 SurfaceView - com.test.flutterlocalization/com.test.flutterlocalization.MainActivity} from container Window{533f3f1 u0 com.test.flutterlocalization/com.test.flutterlocalization.MainActivity}
06-09 18:58:40.592 897-1763/system_process W/WindowManager: Failed looking up window
    java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@8d87bd6 does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
        at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
06-09 18:58:40.592 897-1763/system_process I/WindowManager: WIN DEATH: null
06-09 18:58:40.594 897-23495/system_process W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:785)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1141)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3523)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3359)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
        at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
        at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
        at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
        at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13508)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
06-09 18:58:40.595 291-291/? E/lowmemorykiller: Error opening /proc/23453/oom_score_adj; errno=2
06-09 18:58:40.595 897-23495/system_process W/ActivityManager: Failed setting process group of 23453 to 1
06-09 18:58:40.596 897-23495/system_process W/System.err: java.lang.IllegalArgumentException: Given thread 23453 does not exist
        at android.os.Process.setThreadPriority(Native Method)
        at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20544)
        at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21048)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2447)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2127)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1833)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1823)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1196)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3523)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3359)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
        at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
06-09 18:58:40.597 897-23495/system_process W/System.err:     at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
        at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
        at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13508)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
06-09 18:58:40.623 897-1766/system_process D/WindowManager: relayoutVisibleWindow: Window{6ec6a24 u0 is.shortcut/com.voxel.launcher3.Launcher EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
06-09 18:58:40.654 1789-22126/com.google.android.gms I/Icing: Indexing 8B408E919557C2DC2FA90031B91E7486D83BB7D1 from com.google.android.gms
06-09 18:58:40.721 897-23102/system_process I/ActivityManager: Process com.test.flutterlocalization (pid 23453) has died
06-09 18:58:40.721 897-23102/system_process D/ActivityManager: cleanUpApplicationRecord -- 23453
06-09 18:58:40.735 897-911/system_process W/art: Long monitor contention with owner NativeCrashReport (23495) at void com.android.server.am.AppErrors.crashApplicationInner(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo)(AppErrors.java:324) waiters=2 in void com.android.server.am.ActivityManagerService$MainHandler.handleMessage(android.os.Message) for 138ms
06-09 18:58:40.768 1804-1804/is.shortcut I/NotificationController: resumed
```

```
```

## flutter doctor
```
[✓] Flutter (Channel master, v0.5.3-pre.11, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.3-pre.11 at /****/workspace/git/flutter
    • Framework revision b8c81e46a3 (33 hours ago), 2018-06-08 00:08:28 -0700
    • Engine revision 5d2f24aa5c
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /****/Android/Sdk/
    • Android NDK at /****/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/ebeem/Android/Sdk/
    • Java binary at: /****/jetbrains/android-studio-canary/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /****/jetbrains/android-studio-canary
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio
    • Android Studio at /****/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /****/jetbrains/apps/IDEA-U/ch-0/181.4892.42
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Nexus 5 • ***** • android-arm • Android 7.1.2 (API 25)

• No issues found!
flutter doctor -v  6.19s user 0.52s system 72% cpu 9.282 total
```

**Comment by mraleph** [comment]
Thanks for providing such a reduced reproduction. I was able to reproduce this outside of a Flutter, looking into this.

**Comment by mraleph** [comment]
Fix is up for review upstream.

https://dart-review.googlesource.com/c/sdk/+/59640

**Comment by ebeem** [comment]
Amazing, Thanks for your quick action
I am so excited to try this out

**Comment by mraleph** [comment]
The fix has landed upstream. Waiting for a roll of Dart into Flutter.

**Comment by ebeem** [comment]
@mraleph 
Thanks for the fix

the current dart SDK in my flutter setup is `2.0.0-dev.61.0.flutter-c95617b19c`

your commit should have been included in this version
https://github.com/dart-lang/sdk/compare/2.0.0-dev.61.0...master
 
I made sure I clear and re-build in release mode
sadly, the same exact issue is still there, it crashes in **release mode**

can you check that please? I am afraid I am doing something wrong

```
Upgrading engine...
Already up-to-date.

Flutter 0.5.5-pre.17 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2ae48845a8 (22 minutes ago) • 2018-06-13 12:46:39 -0700
Engine • revision c3976b3c71
Tools • Dart 2.0.0-dev.61.0.flutter-c95617b19c

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.17, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!
flutter upgrade  5.74s user 0.76s system 91% cpu 7.064 total
```

**Comment by ebeem** [comment]
oh, sorry about that
thanks for the explanation

**Comment by mraleph** [comment]
@ebeem no worries. I will close this bug as soon as the roll is done.

**Comment by ebeem** [comment]
@mraleph 
this is working now, thank you so much!
I think this issue can be closed
