### ISSUE TITLE
App crashes after upgrading flutter

### ISSUE THREAD

**Issue by AnandAron** [flutter/flutter#18351]
App keeps on crashing while installing to my phone, after upgrading flutter. It was working properly before upgrading flutter

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 23.1.1` • Dart plugin `171.4424`

Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:174)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:153)
	at io.flutter.view.FlutterView.displayEmptyContent(FlutterView.java:304)
	at io.flutter.view.FlutterView.access$300(FlutterView.java:64)
	at io.flutter.view.FlutterView$2.lambda$connectionClosed$0(FlutterView.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by AnandAron** [comment]
##Console Output

    Running "flutter packages get" in flutter_app...
    Launching lib/main.dart on Redmi 3S in debug mode...
    Initializing gradle...
    Resolving dependencies...
    Running 'gradlew assembleDebug'...
    Built build/app/outputs/apk/debug/app-debug.apk.
    Installing build/app/outputs/apk/app.apk...

##Flutter doctor

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_IN)
    [✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    [✓] Android Studio (version 3.0)
    [✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
Upgrading to Android Studio 3.1 might be worth a try (3.2 isn't properly supported AFAIK)

What do you mean with "while installing"? 
What are the steps to reproduce?

**Comment by J-Bledsoe** [comment]
After running flutter upgrade from the terminal, I also had this issue from within VS Code and Android studio. An uninstall and reinstall of the flutter plugins for VS code and Android Studio after upgradinf resolved the issue for me

**Comment by AnandAron** [comment]
Actually I installed flutter and Android studio in another windows pc, used my phone as the debugging device, which I used to debug before in the previous case and had the same issue. But when I used another phone for debugging, I had no issues. The app was installed and opened smoothly. I donno what's the problem with my phone.

**Comment by AnandAron** [comment]
@zoechi it's Redmi 3s prime.

**Comment by AnandAron** [comment]
Take a note that the problem occured when I was trying to connect to firebase for the first time. Now I connected another phone's flutter app to firebase successfully.  

And also take a note that after the first crash, my other projects too crashed, the same way. Even new pre baked projects

**Comment by zoechi** [comment]
does `adb logcat` contain any hint (stack trace, ...) what might cause the crash?

**Comment by dnfield** [comment]
Is it possible you have some old artifacts stuck on the phone? Perhaps completely uninstall the app from the phone and retry?

**Comment by AnandAron** [comment]
@zoechi 
##logcat output
    06-12 11:30:11.898 27861-27861/? E/Icon: Unable to load resource 0x00000000 from pkg=com.android.systemui
                                         android.content.res.Resources$NotFoundException: Resource ID #0x0
                                             at android.content.res.Resources.getValue(Resources.java:1369)
                                             at android.content.res.MiuiResources.getValue(MiuiResources.java:145)
                                             at android.content.res.Resources.getDrawable(Resources.java:822)
                                             at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:313)
                                             at android.graphics.drawable.Icon.loadDrawable(Icon.java:269)
                                             at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:377)
                                             at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
                                             at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:174)
                                             at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:131)
                                             at com.android.systemui.statusbar.StatusBarIconView.updateDarkMode(StatusBarIconView.java:266)
                                             at com.android.systemui.statusbar.phone.SimpleStatusBar.updateDarkMode(SimpleStatusBar.java:264)
                                             at com.android.systemui.statusbar.phone.PhoneStatusBar$31.run(PhoneStatusBar.java:3496)
                                             at android.os.Handler.handleCallback(Handler.java:742)
                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                             at android.os.Looper.loop(Looper.java:154)
                                             at android.app.ActivityThread.main(ActivityThread.java:5529)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

@dnfield Yeah that was the first thing I tried. But in vain

**Comment by zoechi** [comment]
@AnandAron 
I found the same error output in 

- https://stackoverflow.com/questions/41422380/when-i-open-phone-photos-choose-one-to-back-app-force-closed-with-xiaomi-miui-o?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
- https://stackoverflow.com/questions/35489828/fragmenttransaction-setcustomanimations-doesnt-work-when-battery-saver-is-on 

but I don't see how these could be related.
You could check anyway and see if any suggestion rings a bell.

**Comment by zoechi** [comment]
@Hixie

**Comment by BondarenkoStas** [comment]
Seems that the issue is stale and not relevant anymore. Closing it, please correct me if I'm wrong.
