### ISSUE TITLE
Failed assertion: line 3150 pos 12: '!node.isInvisible': is not true.

### ISSUE THREAD

**Issue by nzlov** [flutter/flutter#18396]
```
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58
```
```
I/flutter ( 3986): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3986): The following assertion was thrown during a scheduler callback:
I/flutter ( 3986): 'package:flutter/src/rendering/object.dart': Failed assertion: line 3150 pos 12:
I/flutter ( 3986): '!node.isInvisible': is not true.
I/flutter ( 3986):
I/flutter ( 3986): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3986): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3986): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3986):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3986):
I/flutter ( 3986): When the exception was thrown, this was the stack:
I/flutter ( 3986): #2      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart)
I/flutter ( 3986): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
I/flutter ( 3986): #4      Iterable.single (dart:core/iterable.dart:556:13)
I/flutter ( 3986): #5      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2306:7)
I/flutter ( 3986): #6      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887:16)
I/flutter ( 3986): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
I/flutter ( 3986): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 3986): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 3986): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3986): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3986): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3986): #14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3986): #15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3986): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3986): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 3986): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
I'm going to close this as dup of #17148.
Would be great if you could provide some information that allows to reproduce.
