### ISSUE TITLE
Firestore ERROR : failed to handle method call

### ISSUE THREAD

**Issue by imhtapm** [flutter/flutter#18405]
**my code to add data to firestore** 
```

  CollectionReference coRef;
  CollectionReference cartRef;


  @override
  void initState() {
    super.initState();
    final firestore = Firestore.instance;
    coRef = firestore.collection('clothes');
    cartRef = firestore.collection('cart');

    cartRef.add({'crn':"7"});
  }

```

## I am getting this error

```
``E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source:77)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:79)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:89)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:504)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at android.app.ActivityThread.main(ActivityThread.java:6649)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9232): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
E/flutter ( 9232): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9232): PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null)
E/flutter ( 9232): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter ( 9232): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 9232): <asynchronous suspension>
E/flutter ( 9232): #2      DocumentReference.setData (file:///home/light/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.3/lib/src/document_reference.dart:43:30)
E/flutter ( 9232): #3      MyHomePageState.initState (package:clothxshopping/pages/HomePage.dart:26:24)
E/flutter ( 9232): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3751:58)
E/flutter ( 9232): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 9232): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 9232): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 9232): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter ( 9232): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 9232): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 9232): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 9232): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter ( 9232): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 9232): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 9232): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 9232): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter ( 9232): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
E/flutter ( 9232): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 9232): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 9232): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
E/flutter ( 9232): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
E/flutter ( 9232): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
E/flutter ( 9232): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
E/flutter ( 9232): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 9232): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 9232): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
E/flutter ( 9232): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
E/flutter ( 9232): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
E/flutter ( 9232): #44     Element.updateChild (package:fl

```

**Comment by seancondev** [comment]
I also get this error - what was the path to green?

**Comment by zoechi** [comment]
@seancondev please create a new issue with instructions how to reproduce `flutter doctor -v` output and the full error output.

**Comment by sunaarun** [comment]
I have the same problem  , and I run flutter doctor , and this is the output ..  

[!]Android toolchain - develop for android devices (Android SDK version 28.0.3)
  !Some Android licenses not accepted . To resolve this, run : flutter doctor --android-licenses
