### ISSUE TITLE
Running on iOS device is fine but Android shows some gradle error

### ISSUE THREAD

**Issue by debutdeveloper** [flutter/flutter#18404]
## Steps to Reproduce

    Fully working project on one machine, clone to different machine and run on iOS working fine but running on Android device it fails and gives the error

  
![screen shot 2018-06-12 at 6 39 39 pm](https://user-images.githubusercontent.com/34939301/41292370-0121d71a-6e70-11e8-8999-0c0424336e06.png)

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d 00dc63d161c691c1

## exception

String: Exit code 1 from: /Users/ankush/BitBucket/debut_assets/android/gradlew -v:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:249)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:179)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:161)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:96)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:89)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:83)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:89)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:306)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:272)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:236)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     _runZoned (dart:async/zone.dart:1518)
#17     runZoned (dart:async/zone.dart:1465)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:314)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     _runZoned (dart:async/zone.dart:1518)
#26     runZoned (dart:async/zone.dart:1465)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:270)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#30     new Future.sync (dart:async/future.dart:222)
#31     CommandRunner.run (package:args/command_runner.dart:109)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:179)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1126)
#36     _CustomZone.run (dart:async/zone.dart:1023)
#37     _runZoned (dart:async/zone.dart:1518)
#38     runZoned (dart:async/zone.dart:1465)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:50)
#42     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#43     main (file:///Users/ankush/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v0.5.2, on Mac OS X 10.13.3 17D47, locale en-IN)
    • Flutter version 0.5.2 at /Users/ankush/flutter
    • Framework revision 0a26ac0970 (6 days ago), 2018-06-06 15:28:20 -0700
    • Engine revision a83b37d35a
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/ankush/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (3 available)
    • Nexus 5X     • 00dc63d161c691c1                         • android-arm64 • Android 8.1.0 (API 27)
    • Debut 6 Plus • f116f9636a5702885e7afcedafa2de2925eb1ca4 • ios           • iOS 11.3.1
    • iPhone X     • B062A68D-6897-4BE1-98D7-BC56ADA8092C     • ios           • iOS 11.3 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Do you still see that?

**Comment by zoechi** [comment]
Closing as dup of #17280
