### ISSUE TITLE
Flutter test fail because of an async method

### ISSUE THREAD

**Issue by acrozes** [flutter/flutter#18435]
The working example: 
https://github.com/brianegan/scoped_model/pull/17/commits/1ccd67bd18115927863231f9d7543892e544a9a9

There are two widgets tests:
- the first with a scoped_model that contains an async method that fail
- the second with a scoped_model that contains no async method that success

I don't understand why the first test fail with the message:
```
Testing started at 02:44 ...
C:\flutter\flutter\bin\flutter.bat --no-color test --machine --plain-name "Counter increments test with the CounterModel => FAIL because the model contains an async function called" test\widget_test.dart
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: no matching nodes in the widget tree
  Actual: ?:<exactly one widget with text "0" (ignoring offstage widgets): Text("0", debugLabel:
  (englishLike display1).merge(blackMountainView display1), inherit: false, color:
  Color(0x8a000000), family: Roboto, size: 34.0, weight: 400, baseline: alphabetic, decoration:
  TextDecoration.none)>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Mes%20documents/github/scoped_model/exampleAsyncAndTest/test/widget_test.dart:28:9)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:63:25)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:509:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:751:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:749:16)
#17     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#23     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#24     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#28     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#43     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#44     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 26 frames from class _FakeAsync, package dart:async, and package stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Mes%20documents/github/scoped_model/exampleAsyncAndTest/test/widget_test.dart line 28

The test description was:
Counter increments test with the CounterModel => FAIL because the model contains an async function
called
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Counter increments test with the CounterModel => FAIL because the model contains an async function called
```

FYI:
```
C:\flutter\flutter\bin\flutter.bat --no-color doctor
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 31 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [version 6.3.9600], locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by zoechi** [comment]
Is this still an issue. The linked PR is merged.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by jondhc** [comment]
https://stackoverflow.com/a/58582291/6811780
