### ISSUE TITLE
Gradle build failure for project on external SD Card

### ISSUE THREAD

**Issue by jnickzlim** [flutter/flutter#18475]
Hello,

I am writing this post for a wired case that i encounter, and i am new to flutter, this case may be related to android studio, i am not sure, just sharing my experience on the issue.

I've just install flutter to my MacBook Pro without any problem, until i tried to build a new testing flutter app and decided to save the project inside my SD Card. 

I tried run the app on iOS, it runs without any problem, then i tried run it on an android emulator, encounter the below error:

```
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().
```

I tried searching around what is the problem, and couldn't find any solution to the case.
It's just so wired to encounter this error, i spends hours on searching and trying to solve the error.

Until i tried to create another new flutter application project on my MacBook Pro's HDD, and run it, it work! There seems to be a problem for android studio to run the application (Project saved under external storage) with the error above.

**Comment by cbracken** [comment]
The error message appears to be coming from Gradle, which is part of Android Studio. If you do `flutter --verbose run`, do you get more detailed output?

gradle/gradle#3318 looks potentially relevant.

**Comment by iampawan** [comment]
Facing the same bug if using a real device when the project is located into external sd card on my macbook pro  

Error - Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().

**Comment by apaatsio** [comment]
@jnickzlim @iampawan Does running flutter with sudo help? E.g. `sudo flutter run`

This is probably same issue as #27447

**Comment by red-ibanez** [comment]
Hello,

I ran into this issue under the same scenario as @jnickzlim . I was just trying to learn/build a simple flutter app and I couldn't build it.  It has been very frustrating to understand what is going on.  I still don't know the exact culprit, other than it works on the regular MAC SSD but not on an external SD card.  Because my MAC was running low in space, I've been using an externally mounted disk that sits flushed to the side of the MAC. It is a $128GB SD card and it has worked perfectly for all my purposes.. well, except this one.   

The errors pointed me to gradle issues, but couldn't figured out until i bumped into this thread and tried on the native disk, and voila.  Thanks for the help. 

To answer @apaatsio 's question... no, a sudo flutter run doesn't fix it. 

I guess I will work on my HD in the meantime, but here is more detail in case it can be of help:

***************************************
ON THE SD CARD:
PRSs-MacBook-Pro:flutter_firstapp prs$ flutter --verbose run
[  +42 ms] executing: [/Users/prs/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/prs/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +28 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +20 ms] executing: [/Users/prs/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/prs/Development/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +135 ms] executing: [/Users/prs/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[  +35 ms] executing: sw_vers -productName
[  +54 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +32 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +23 ms] Exit code 0 from: sw_vers -buildVersion
[   +4 ms] 18G103
[  +96 ms] executing: /usr/bin/xcode-select --print-path
[  +32 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[   +3 ms] /Library/Developer/CommandLineTools
[   +5 ms] executing: /usr/bin/xcodebuild -version
[   +8 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools'
is a command line tools instance
[ +142 ms] executing: /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +49 ms] executing: /Users/prs/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +74 ms] executing: /usr/bin/xcodebuild -version
[   +6 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools'
is a command line tools instance
[  +18 ms] /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb -s emulator-5554 shell getprop
[ +122 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +324 ms] Generating
/Volumes/MicroSD/Developer/flutter_firstapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +373 ms] ro.hardware = ranchu
[  +14 ms] executing: /usr/bin/xcodebuild -version
[   +6 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools'
is a command line tools instance
[  +27 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software
rendering with
           "--enable-software-rendering".
[  +32 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +35 ms] executing: /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb -s emulator-5554 shell -x logcat -v time -s flutter
[  +11 ms] executing: /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb version
[  +32 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb
[   +6 ms] executing: /Volumes/MicroSD/Library/Android/SDK/platform-tools/adb start-server
[  +14 ms] Building APK
[  +50 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +10 ms] Using gradle from /Volumes/MicroSD/Developer/flutter_firstapp/android/gradlew.
[+1218 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +16 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"MainClass":"com.intellij.idea.Main","ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Content
s\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.ja
r:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","Properties":{"idea.home.path"
:"$APP_PACKAGE\/Contents","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.paths.selector":"AndroidStudio3.5"},"W
orkingDirectory":"$APP_PACKAGE\/Contents\/bin"},"LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-191.8026.42.35.6010548","CFBun
dleDevelopmentRegion":"English","CFBundleDocumentTypes":[{"CFBundleTypeExtensions":["ipr"],"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeIconFile":"studio.icns","CFBundleTypeRole":"Editor"},{"CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"
LSTypeIsPackage":false,"CFBundleTypeName":"All
documents","CFBundleTypeRole":"Editor"}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"st
udio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"3.5","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":
"studio","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"],"CFBundleTy
peRole":"Editor"}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","C
FBundleSignature":"????","LSMinimumSystemVersion":"10.8","CFBundleGetInfoString":"Android Studio 3.5, build AI-191.8026.42.35.6010548.
Copyright JetBrains s.r.o., (c) 2000-2019"}
[  +10 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +312 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +2 ms] executing: [/Volumes/MicroSD/Developer/flutter_firstapp/android/] /Volumes/MicroSD/Developer/flutter_firstapp/android/gradlew
-Pverbose=true -Ptarget=/Volumes/MicroSD/Developer/flutter_firstapp/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+7409 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [  +40 ms] executing: [/Users/prs/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [ +116 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +14 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] [   +1 ms] executing: [/Users/prs/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.5-0-g27321ebba
[        ] [  +27 ms] executing: [/Users/prs/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/prs/Development/flutter/] git ls-remote --get-url origin
[        ] [  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +119 ms] executing: [/Users/prs/Development/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [   +1 ms] stable
[   +1 ms] [  +70 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +218 ms] Initializing file store
[        ] [  +29 ms] kernel_snapshot: Starting due to {}
[  +55 ms] [  +17 ms] /Users/prs/Development/flutter/bin/cache/dart-sdk/bin/dart
/Users/prs/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/prs/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --no-link-platform --packages /Volumes/MicroSD/Developer/flutter_firstapp/.packages --output-dill
/Volumes/MicroSD/Developer/flutter_firstapp/.dart_tool/flutter_build/c64c25a82e98e615938e2ff785b5244f/app.dill --depfile
/Volumes/MicroSD/Developer/flutter_firstapp/.dart_tool/flutter_build/c64c25a82e98e615938e2ff785b5244f/kernel_snapshot.d package:flutter_firstapp/main.dart
[+11899 ms] [+11921 ms] kernel_snapshot: Complete
[+1587 ms] [+1678 ms] debug_android_application: Starting due to {}
[+11700 ms] [+11604 ms] debug_android_application: Complete
[ +699 ms] [ +777 ms] Persisting file store
[ +201 ms] [ +172 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[ +100 ms] [ +103 ms] "flutter assemble" took 26,640ms.
[+4199 ms] > Task :app:packLibsflutterBuildDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[ +694 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +104 ms] > Task :app:checkDebugManifest
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[+17164 ms] > Task :app:generateDebugBuildConfig
[ +233 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[+6015 ms] > Task :app:mergeDebugShaders
[+3388 ms] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[+7910 ms] > Task :app:mergeDebugAssets
[+13187 ms] > Task :app:copyFlutterAssetsDebug
[+2610 ms] > Task :app:mainApkListPersistenceDebug
[ +487 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[+30005 ms] > Task :app:mergeDebugResources
[+20303 ms] > Task :app:createDebugCompatibleScreenManifests
[+28026 ms] > Task :app:processDebugManifest
[ +665 ms] > Task :app:processDebugJavaRes NO-SOURCE
[+4500 ms] > Task :app:checkDebugDuplicateClasses
[+42809 ms] > Task :app:processDebugResources
[+31389 ms] > Task :app:compileDebugKotlin
[+2200 ms] > Task :app:javaPreCompileDebug
[+28106 ms] > Task :app:desugarDebugFileDependencies
[+1894 ms] > Task :app:compileDebugJavaWithJavac
[+33997 ms] > Task :app:compileDebugJavaWithJavac FAILED
[ +126 ms] FAILURE: Build failed with an exception.
[  +14 ms] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > Could not create service of type DefaultGeneralCompileCaches using GradleScopeCompileServices.createGeneralCompileCaches().
[        ] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 5m 13s
[        ] 20 actionable tasks: 19 executed, 1 up-to-date
[ +734 ms] Running Gradle task 'assembleDebug'... (completed in 316.0s, longer than expected)
[  +19 ms] "flutter run" took 317,788ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
<asynchronous suspension>
#2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _runZoned (dart:async/zone.dart:1518:10)
#13     runZoned (dart:async/zone.dart:1465:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _runZoned (dart:async/zone.dart:1518:10)
#22     runZoned (dart:async/zone.dart:1465:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#30     _rootRun (dart:async/zone.dart:1126:13)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _runZoned (dart:async/zone.dart:1518:10)
#33     runZoned (dart:async/zone.dart:1502:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _runZoned (dart:async/zone.dart:1518:10)
#39     runZoned (dart:async/zone.dart:1465:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#41     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#42     run (package:flutter_tools/runner.dart:50:10)
#43     main (package:flutter_tools/executable.dart:65:9)
#44     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

***************************************
ON THE SD CARD:
PRSs-MacBook-Pro:flutter_firstapp prs$ gradle --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #16 of type ReservedFileSystemLocationRegistry.
> Cannot create service of type ReservedFileSystemLocationRegistry using ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.service.ServiceCreationException: Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #16 of type ReservedFileSystemLocationRegistry.
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:741)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:628)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:651)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:423)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:932)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1018)
        at org.gradle.internal.service.DefaultServiceRegistry.getService(DefaultServiceRegistry.java:308)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:302)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:287)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:282)
        at org.gradle.execution.ProjectExecutionServiceRegistry$DefaultNodeExecutionContext.getService(ProjectExecutionServiceRegistry.java:71)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:40)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type ReservedFileSystemLocationRegistry using ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:741)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.prepare(DefaultServiceRegistry.java:628)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.getService(DefaultServiceRegistry.java:651)
        at org.gradle.internal.service.DefaultServiceRegistry$OwnServices.getService(DefaultServiceRegistry.java:423)
        at org.gradle.internal.service.DefaultServiceRegistry$CompositeServiceProvider.getService(DefaultServiceRegistry.java:932)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1018)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1500(DefaultServiceRegistry.java:71)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:739)
        ... 22 more
Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:835)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:765)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:556)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:614)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:778)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:764)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:556)
        at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:614)
        at org.gradle.internal.service.DefaultServiceRegistry.getCollectionService(DefaultServiceRegistry.java:1065)
        at org.gradle.internal.service.DefaultServiceRegistry.getCollectionService(DefaultServiceRegistry.java:1047)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:1010)
        at org.gradle.internal.service.DefaultServiceRegistry.access$1500(DefaultServiceRegistry.java:71)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.bind(DefaultServiceRegistry.java:739)
        ... 29 more
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock execution history cache (/Volumes/MicroSD/Developer/flutter_firstapp/.gradle/6.2.1/executionHistory). It is currently in use by another Gradle instance.
Owner PID: unknown
Our PID: 10471
Owner Operation: unknown
Our operation:
Lock file: /Volumes/MicroSD/Developer/flutter_firstapp/.gradle/6.2.1/executionHistory/executionHistory.lock
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:304)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:163)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:109)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:106)
        at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.acquireFileLock(LockOnDemandCrossProcessCacheAccess.java:168)
        at org.gradle.cache.internal.DefaultCacheAccess.onStartWork(DefaultCacheAccess.java:375)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:211)
        at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:201)
        at org.gradle.cache.internal.DefaultCacheAccess.newCache(DefaultCacheAccess.java:292)
        at org.gradle.cache.internal.DefaultCacheAccess.newCache(DefaultCacheAccess.java:61)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.createCache(DefaultPersistentDirectoryStore.java:162)
        at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.createCache(DefaultCacheFactory.java:186)
        at org.gradle.api.internal.changedetection.state.DefaultExecutionHistoryCacheAccess.createCache(DefaultExecutionHistoryCacheAccess.java:51)
        at org.gradle.internal.execution.history.impl.DefaultExecutionHistoryStore.<init>(DefaultExecutionHistoryStore.java:46)
        at org.gradle.internal.service.scopes.ExecutionGradleServices.createExecutionHistoryStore(ExecutionGradleServices.java:89)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:34)
        at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:833)
        ... 41 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 4s
PRSs-MacBook-Pro:flutter_firstapp prs$ pwd
/Volumes/MicroSD/Developer/flutter_firstapp
PRSs-MacBook-Pro:flutter_firstapp prs$


************************
ON REGULAR HD

gradle --stacktrace

> Task :help

Welcome to Gradle 6.2.1.

To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

For troubleshooting, visit https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 8s
1 actionable task: 1 executed
