### ISSUE TITLE
 No implementation found for nativeGetIsSoftwareRenderingEnabled

### ISSUE THREAD

**Issue by hpsoar** [flutter/flutter#18476]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.chunyu.hybridflutter, PID: 15881
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{me.chunyu.hybridflutter/me.chunyu.hybridflutter.BaseFlutterActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.flutter.view.FlutterView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2917)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6646)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                   Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.flutter.view.FlutterView
                   Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class io.flutter.view.FlutterView
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at me.chunyu.hybridflutter.BaseFlutterActivity.onCreate(BaseFlutterActivity.kt:12)
                      at android.app.Activity.performCreate(Activity.java:6912)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6646)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                   Caused by: java.lang.UnsatisfiedLinkError: No implementation found for boolean io.flutter.view.FlutterView.nativeGetIsSoftwareRenderingEnabled() (tried Java_io_flutter_view_FlutterView_nativeGetIsSoftwareRenderingEnabled and Java_io_flutter_view_FlutterView_nativeGetIsSoftwareRenderingEnabled__)
                      at io.flutter.view.FlutterView.nativeGetIsSoftwareRenderingEnabled(Native Method)
                      at io.flutter.view.FlutterView.<init>(FlutterView.java:129)
                      at io.flutter.view.FlutterView.<init>(FlutterView.java:123)
                      at java.lang.reflect.Constructor.newInstance0(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:865) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:525) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:378) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at me.chunyu.hybridflutter.BaseFlutterActivity.onCreate(BaseFlutterActivity.kt:12) 
                      at android.app.Activity.performCreate(Activity.java:6912) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6646) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by hpsoar** [comment]
forget to set:     android:name="io.flutter.app.FlutterApplication"
