### ISSUE TITLE
TabController with a single element fails assertion on horizontal tab scroll after number of tabs was decreased from 2 to 1

### ISSUE THREAD

**Issue by strokine** [flutter/flutter#18481]
## Steps to Reproduce
1. Create TabController with 2 tabs and assign it to `TabPageSelector`, show `TabPageSelector` on a screen.
2. Create `TabController` with 1 tab and assign it to `TabPageSelector`, call `setState((_){});`
3. Try to slide horizontally the tab.

## Logs

```
I/flutter ( 7749): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7749): The following assertion was thrown while handling a gesture:
I/flutter ( 7749): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 174 pos 12: 'length > 1':
I/flutter ( 7749): is not true.
I/flutter ( 7749): 
I/flutter ( 7749): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7749): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7749): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7749):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7749): 
I/flutter ( 7749): When the exception was thrown, this was the stack:
I/flutter ( 7749): #2      TabController.offset= (package:flutter/src/material/tab_controller.dart)
I/flutter ( 7749): #3      _TabBarViewState._handleScrollNotification (package:flutter/src/material/tabs.dart:1152:21)
I/flutter ( 7749): #4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125:27)
I/flutter ( 7749): #5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter ( 7749): #6      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:35:18)
I/flutter ( 7749): #7      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3295:39)
I/flutter ( 7749): #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59:12)
I/flutter ( 7749): #9      DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:443:122)
I/flutter ( 7749): #10     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:598:14)
I/flutter ( 7749): #11     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:219:9)
I/flutter ( 7749): #12     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
I/flutter ( 7749): #13     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:132:5)
I/flutter ( 7749): #14     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:373:14)
I/flutter ( 7749): #15     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:451:12)
I/flutter ( 7749): #16     DragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:175:48)
I/flutter ( 7749): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 7749): #18     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:175:9)
I/flutter ( 7749): #19     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:263:12)
I/flutter ( 7749): #20     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
I/flutter ( 7749): #21     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
I/flutter ( 7749): #22     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:166:13)
I/flutter ( 7749): #23     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:154:11)
I/flutter ( 7749): #24     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 7749): #25     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 7749): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter ( 7749): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 7749): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 7749): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 7749): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 7749): #31     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 7749): #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 7749): (elided 2 frames from class _AssertionError)
I/flutter ( 7749): 
I/flutter ( 7749): Handler: onUpdate
I/flutter ( 7749): Recognizer:
I/flutter ( 7749):   HorizontalDragGestureRecognizer#c3031
```

Flutter Doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

The solution could be adding a check in:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tabs.dart#L1151

```dart
      if(_pageController.page - _controller.index > 1) {
        _controller.offset = (_pageController.page - _controller.index).clamp(-1.0, 1.0);
      }
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by strokine** [comment]
Updated the initial message with flutter doctor output

**Comment by zoechi** [comment]
Sounds like you are removing the active page. I guess you need to make page 0 active at the same time.

**Comment by strokine** [comment]
Yes, you are correct. And it works fine until only 2 pages left. The widget even animates the process of the previous page taking place of the removed one, except if we are removing the first page (which is another issue, but not a big deal).
The problem appears when, there are 2 pages left, I'm removing one, everything looks good, until I'm trying to paginate the remaining page. If I slide it horizontally, the assertion error pops up.
The fix is simple, but it is in the `tabs.dart` file. And I'm sure it could be done some how better (especially it could be addressed during work on animation of removing the first page), but at least this check should be present in the file.

**Comment by zoechi** [comment]
@HansMuller

**Comment by HansMuller** [comment]
Thanks for the report and the analysis.  I was able to reproduce the problem, https://gist.github.com/HansMuller/880b28b02b92e00b97c0ec858d4c9cb6

Will make sure that this is fixed.

**Comment by HansMuller** [comment]
This bug has been fixed.
