### ISSUE TITLE
[testing] Exception while passing consecutive inputs via `tester.testTextInput`

### ISSUE THREAD

**Issue by yigit** [flutter/flutter#18577]
I have a TextField which takes an action when user hits done.

While trying to create a test for it, the first time i can successfully send the done button but second time it fails.

I'm using the following code to send the done event:

```dart
Future<Null> submit(WidgetTester tester, Finder finder) async {
  return TestAsyncUtils.guard(() async {
    await tester.showKeyboard(finder);
    tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.idle();
  });
}
```

Repro test:
```dart
void main() {
  testWidgets("my custom test", (WidgetTester tester)
  async {
    await tester.pumpWidget(new Directionality(
      child: new Card(
        child: TextField(),
      ),
      textDirection: TextDirection.ltr,
    ));
    var inputPredicate = find.byType(TextField);
    expect(inputPredicate, findsOneWidget);
    await submit(tester, find.byType(TextField));
    await tester.pump();
    await submit(tester, find.byType(TextField));// this fails
    await tester.pump();
  }
  );
}

Future<Null> submit(WidgetTester tester, Finder finder) async {
  return TestAsyncUtils.guard(() async {
    await tester.showKeyboard(finder);
    tester.testTextInput.receiveAction(TextInputAction.done);
    await tester.idle();
  });
}
```

error log:
```
Testing started at 3:04 PM ...
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  _client must be non-zero

When the exception was thrown, this was the stack:
#0      TestTextInput.receiveAction (package:flutter_test/src/test_text_input.dart:116:7)
#1      submit.<anonymous closure> (file:///home/yboyar/src/test_failure/test_failure/test/test_failure_test.dart:28:26)
<asynchronous suspension>
#4      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#5      submit (file:///home/yboyar/src/test_failure/test_failure/test/test_failure_test.dart:26:25)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///home/yboyar/src/test_failure/test_failure/test/test_failure_test.dart:19:11)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:63:25)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:509:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:751:24)
#18     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:749:16)
#19     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
#20     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#21     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#25     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#26     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#30     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#45     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#46     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
(elided 28 frames from class _FakeAsync, package dart:async, and package stack_trace)

The test description was:
my custom test
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: my custom test
```

**Comment by zoechi** [comment]
cc @Hixie

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/18615

**Comment by zoechi** [comment]
I assume this has landed a while ago.
