### ISSUE TITLE
flutter_test needs to be updated to support the latest analyzer.

### ISSUE THREAD

**Issue by wooldridgetm** [flutter/flutter#18648]
## Steps to Reproduce

1. Open Terminal & type **flutter create sample_project**
2. type **cd sample_project**
3. type **flutter packages get**
4. type **code pubspec.yaml** 
     - VSC should open the pubspec.yaml file.
5. add the dependencies for [JSON Serializable](https://github.com/dart-lang/json_serializable)
6. Return to Terminal & type **flutter packages upgrade**
7. the command will fail with the following message:

_Because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2 and json_serializable >=0.5.3 depends on analyzer ^0.32.0, flutter_test from sdk is incompatible with json_serializable >=0.5.3._
_So, because jam2018 depends on both json_serializable ^0.5.4 and flutter_test any from sdk, version solving failed._
_pub get failed (1)_

[Corresponding issue report at JSON Serializable repo](https://github.com/dart-lang/json_serializable/issues/241)

## Logs

```
[sample_project]$ flutter packages upgrade --verbose
[  +30 ms] [/Users/wooldridgetm/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/wooldridgetm/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/wooldridgetm/Development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/wooldridgetm/Development/flutter/] git log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [/Users/wooldridgetm/Development/flutter/] git log -n 1 --pretty=format:%ar
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] [/Users/wooldridgetm/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +27 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca
[ +134 ms] Running "flutter packages upgrade" in sample_project...
[   +4 ms] [/Users/wooldridgetm/Development/flutterStudio/sample_project/] /Users/wooldridgetm/Development/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning --verbose upgrade --no-precompile
[+5084 ms] Because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2 and json_serializable >=0.5.3 depends on analyzer ^0.32.0, flutter_test from sdk is incompatible with json_serializable >=0.5.3.
[        ] So, because sample_project depends on both json_serializable ^0.5.4 and flutter_test any from sdk, version solving failed.
[  +37 ms] "flutter upgrade" took 5,205ms.
pub upgrade failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      pub (package:flutter_tools/src/dart/pub.dart:168)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:60)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:83)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#22     new Future.sync (dart:async/future.dart:222)
#23     CommandRunner.run (package:args/command_runner.dart:109)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1126)
#28     _CustomZone.run (dart:async/zone.dart:1023)
#29     runZoned (dart:async/zone.dart:1501)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50)
#33     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#34     main (file:///Users/wooldridgetm/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
[sample_project]$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Users/wooldridgetm/Development/flutter
    • Framework revision c7ea3ca377 (3 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/wooldridgetm/Library/Android/sdk
    • Android NDK at /Users/wooldridgetm/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/wooldridgetm/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.3.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.24.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.13.2

[✓] Connected devices (1 available)
    • iPhone X • DB37E26D-A616-4EC2-B891-BA37E261586A • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by OZ20** [comment]
Any workaround yet?

**Comment by pcqpcq** [comment]
just a workaround for me:

remove `flutter_test`, and use `build_runner: "^0.8.10"` for now.

and wait for flutter_test to be updated to support the latest analyzer.

```yaml

dev_dependencies:
  # flutter_test:   # <-- remove this for now.
  #   sdk: flutter
  
  build_runner: "^0.8.10"  # <-- use this for now.
  json_serializable: "^0.5.8"
```

**Comment by zoechi** [comment]
You could also try to add
```
dependency_overrides:
  analyzer: ^0.31.2-alpha.2
```

**Comment by jaggerwang** [comment]
Same problem!

```
[app] flutter packages get
Running "flutter packages get" in app...
Because every version of flutter_driver from sdk depends on analyzer 0.31.2-alpha.2 and json_serializable >=0.5.3 depends on analyzer ^0.32.0, flutter_driver from sdk is incompatible with json_serializable >=0.5.3.
So, because tangbole depends on both json_serializable ^0.5.8 and flutter_driver any from sdk, version solving failed.
pub get failed (1)
exit code 1
```

**Comment by deepakrana0011** [comment]
@jaggerwang  have you got any solution for this because i am facing the same issue.

**Comment by Muldec** [comment]
@deepakrana0011 the workaround proposed by @zoechi worked for me.

**Comment by OZ20** [comment]
Just remove the test dependencies

**Comment by eturk1** [comment]
@zoechi solution works. 
commenting out test dependencies causes lots of dart errors in test\widget_test.dart

these dependency versions:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^1.5.0
```
causes this error:
```
Because every version of flutter_test from sdk depends on analyzer 0.33.0-alpha.0 and json_serializable 1.5.0 depends on analyzer ^0.32.2, flutter_test from sdk is incompatible with json_serializable 1.5.0.
And because no versions of json_serializable match >1.5.0 <2.0.0, flutter_test from sdk is incompatible with json_serializable ^1.5.0.
So, because mystrengths depends on both json_serializable ^1.5.0 and flutter_test any from sdk, version solving failed.
```

workaround was to add version number flutter_test demands:
```
dependency_overrides:
  analyzer: ^0.33.0-alpha.0
```

(Note: this warning just popped up for me in the last few days. This issue post solved it finally so I could run again. Maybe there will be a more proper fix so it doesn't break?)

**Comment by pouledodue** [comment]
dependencies errors are clearly what I hate the most about Flutter

**Comment by zoechi** [comment]
@pouledodue how would that be Flutters error?
It's easy to not have dependency issues in a 20y old platform where hardly any breaking changes are made ever.
I agree that some dependencies could be updated more quickly after dependencies introduced breaking changes, but the main problem is that Flutter is new and moving fast.
That allows you to use modern tech but has some disadvantages like that not all project can keep up with the pace. 

What I think helps most is to create issues if dependencies need updates to notify maintainers.
Even better are pull requests ;-)

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by ffischer1984** [comment]
still have this error with: flutter upgrade
Flutter is already up to date on channel stable
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
and here is the error:
Because every version of flutter_test from sdk depends on meta 1.3.0 and json_annotation >=4.1.0 depends on meta ^1.4.0, flutter_test from sdk is incompatible with json_annotation >=4.1.0.
So, because flutter_g_tms depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because flutter_g_tms depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.)
