### ISSUE TITLE
Program specified by service does not contain one of the requested architectures: XPC_FLAG

### ISSUE THREAD

**Issue by MiguelCatalan** [flutter/flutter#18652]
After deploying to the App Store and being accepted, some users started to report the app is not working on some 9.3 devices.

It seems that the app is installed correctly but when opening the app crashes. On iOS 11 is working fine, but not in 9.3. Also happens not only for released apps but also to emulators and in debug mode.

And reports the following error
```
Jun 21 00:22:42 Eleanor com.apple.CoreSimulator.SimDevice.8A059639-9DE4-4667-8FAE-BF514DE1C789[21434] (UIKitApplication:ly.eval.reportingtool[0x6108][29172]): Program specified by service does not contain one of the requested architectures: XPC_FLAGS=0x0
Exit code 1 from: /usr/bin/xcrun simctl launch 8A059639-9DE4-4667-8FAE-BF514DE1C789 ly.eval.reportingtool --enable-dart-profiling --enable-checked-mode --observatory-port=8118:
ly.eval.reportingtool: -1

An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1):
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
Error launching application on iPad 2.
```
## Steps to Reproduce

1. Create a 9.3 iPad emulator
2. Run against that emulator
3. The app do not start and crashes

## Logs

```
Install Successful; Staging: 0.25s; Waiting: 0.00s; Preflight/Patch: 0.02s, Verifying: 0.01s; Overall: 0.34s
[  +37 ms] [DEVICE LOG] Jun 21 00:12:09 Eleanor SpringBoard[21449]: Installed apps did change.
[        ] [DEVICE LOG]         Added: {(
[        ] [DEVICE LOG]             "ly.eval.reportingtool"
[        ] [DEVICE LOG]         )}
[        ] [DEVICE LOG]         Removed: {(
[        ] [DEVICE LOG]         )}
[        ] [DEVICE LOG]         Modified: {(
[        ] [DEVICE LOG]         )}
[        ]      Added: {(
[        ]          "ly.eval.reportingtool"
[        ]      )}
[        ]      Removed: {(
[        ]      )}
[        ]      Modified: {(
[        ]      )}
[ +981 ms] [DEVICE LOG] Jun 21 00:12:10 Eleanor containermanagerd[21468]: 0xb09de000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
[   +1 ms] [DEVICE LOG] Jun 21 00:12:10 Eleanor containermanagerd[21468]: 0xb0858000 systemGroupContainerPath: com.apple.containermanagerd.internal is not entitled for system group identifier: systemgroup.com.apple.lsd
[+1506 ms] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Registered for possible future reinstall: (ly.eval.reportingtool, file:///Users/miguelcatalan/Projects/Evally/evally_mobile_flutter/build/ios/iphonesimulator/Runner.app/, {
[        ] [DEVICE LOG]             CFBundleIdentifier = "ly.eval.reportingtool";
[        ] [DEVICE LOG]             PackageType = Developer;
[        ] [DEVICE LOG]             SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot";
[        ] [DEVICE LOG]             SimulatorUserPath = "/Users/miguelcatalan/Library/Developer/CoreSimulator/Devices/8A059639-9DE4-4667-8FAE-BF514DE1C789/data";
[        ] [DEVICE LOG]         })
[        ]          CFBundleIdentifier = "ly.eval.reportingtool";
[        ]          PackageType = Developer;
[        ]          SimulatorRootPath = "/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot";
[        ]          SimulatorUserPath = "/Users/miguelcatalan/Library/Developer/CoreSimulator/Devices/8A059639-9DE4-4667-8FAE-BF514DE1C789/data";
[        ]      })
[  +14 ms] /usr/bin/xcrun simctl launch 8A059639-9DE4-4667-8FAE-BF514DE1C789 ly.eval.reportingtool --enable-dart-profiling --enable-checked-mode --observatory-port=8118
[ +169 ms] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Pasteboard change listener callback port <NSMachPort: 0x78607800> registered
[  +16 ms] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Requesting launch of ly.eval.reportingtool with options: {
[        ] [DEVICE LOG]             arguments =     (
[        ] [DEVICE LOG]                 "--enable-dart-profiling",
[        ] [DEVICE LOG]                 "--enable-checked-mode",
[        ] [DEVICE LOG]                 "--observatory-port=8118"
[        ] [DEVICE LOG]             );
[        ] [DEVICE LOG]             environment =     {
[        ] [DEVICE LOG]             };
[        ] [DEVICE LOG]         }
[        ]          arguments =     (
[        ]              "--enable-dart-profiling",
[        ]              "--enable-checked-mode",
[        ]              "--observatory-port=8118"
[        ]          );
[        ]          environment =     {
[        ]          };
[        ]      }
[        ] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Beginning launch sequence for bundle 'ly.eval.reportingtool'
[        ] [DEVICE LOG]                 retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
[        ] [DEVICE LOG]                 bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
[  +13 ms] [DEVICE LOG]                 bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
[        ] [DEVICE LOG]                 Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
[        ] [DEVICE LOG]         Simulator booted at: 2018-06-20 21:35:23 +0000
[        ] [DEVICE LOG]         Current time: 2018-06-20 22:12:11 +0000
[        ] [DEVICE LOG]         Within boot leeway: NO
[        ] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Launch attempt #0 for bundle 'ly.eval.reportingtool', have been trying to launch for 0 seconds. Modern launch services = NO
[        ] [DEVICE LOG] Jun 21 00:12:11 Eleanor CoreSimulatorBridge[21456]: Got LSBundleProxy for 'ly.eval.reportingtool', sequenceNumber 64, cacheGUID <__NSConcreteUUID 0x78608000> 94A55391-D440-46FC-8582-02102330F945
[        ]              retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
[        ]              bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
[        ]              bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
[        ]              Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
[        ]      Simulator booted at: 2018-06-20 21:35:23 +0000
[        ]      Current time: 2018-06-20 22:12:11 +0000
[        ]      Within boot leeway: NO
[  +77 ms] [DEVICE LOG] Jun 21 00:12:12 Eleanor com.apple.CoreSimulator.SimDevice.8A059639-9DE4-4667-8FAE-BF514DE1C789[21434] (UIKitApplication:ly.eval.reportingtool[0x1060][27711]): Program specified by service does not contain one of the requested architectures: XPC_FLAGS=0x0
[        ] Jun 21 00:12:12 Eleanor com.apple.CoreSimulator.SimDevice.8A059639-9DE4-4667-8FAE-BF514DE1C789[21434] (UIKitApplication:ly.eval.reportingtool[0x1060][27711]): Program specified by service does not contain one of the requested architectures: XPC_FLAGS=0x0
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor SpringBoard[21449]: Unable to get pid for 'UIKitApplication:ly.eval.reportingtool[0x1060]': No such process (err 3)
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor SpringBoard[21449]: Bootstrapping failed for <FBApplicationProcess: 0x7ee4ad80; ly.eval.reportingtool; pid: -1>
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor SpringBoard[21449]: [FBSystemService] Error launching ly.eval.reportingtool: Unspecified (1)
[        ] [DEVICE LOG] Jun 21 00:12:12 --- last message repeated 1 time ---
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor CoreSimulatorBridge[21456]: Error Launching: Error Domain=FBSOpenApplicationErrorDomain Code=1 "(null)"
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor CoreSimulatorBridge[21456]: Unrecoverable error launching 'ly.eval.reportingtool', will NOT retry. Error was: Error Domain=FBSOpenApplicationErrorDomain Code=1 "(null)"
[        ] [DEVICE LOG] Jun 21 00:12:12 Eleanor SpringBoard[21449]: Application 'UIKitApplication:ly.eval.reportingtool[0x1060]' exited voluntarily.
[   +3 ms] [DEVICE LOG] Jun 21 00:12:12 Eleanor CoreSimulatorBridge[21456]: Pasteboard change listener callback port <NSMachPort: 0x78c0d0c0> registered
[   +2 ms] ly.eval.reportingtool: -1
           
           An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1):
           The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
[   +1 ms] Exit code 1 from: /usr/bin/xcrun simctl launch 8A059639-9DE4-4667-8FAE-BF514DE1C789 ly.eval.reportingtool --enable-dart-profiling --enable-checked-mode --observatory-port=8118:
           ly.eval.reportingtool: -1
           
           An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=1):
           The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
[   +2 ms] Error launching application on iPad 2.
[  +14 ms] "flutter run" took 43,384ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:401)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      _runZoned (dart:async/zone.dart:1518)
#8      runZoned (dart:async/zone.dart:1465)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:322)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     _runZoned (dart:async/zone.dart:1518)
#17     runZoned (dart:async/zone.dart:1465)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:278)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#21     new Future.sync (dart:async/future.dart:222)
#22     CommandRunner.run (package:args/command_runner.dart:109)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:187)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1126)
#27     _CustomZone.run (dart:async/zone.dart:1023)
#28     _runZoned (dart:async/zone.dart:1518)
#29     runZoned (dart:async/zone.dart:1465)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50)
#33     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#34     main (file:///Users/miguelcatalan/Projects/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

```

No related errors running `flutter analyze`

```
Analyzing evally_mobile_flutter...                               

   info • Unused import: 'package:evally_mobile_flutter/domain/instructor/Instructor.dart' • lib/data/instructor/InstructorTokenApiModelMapper.dart:4:8
   info • The value of the local variable 'imageUrl' isn't used • lib/data/student/StudentsApiModelMapper.dart:22:9
   info • Unused import: 'package:evally_mobile_flutter/domain/instructor/Instructor.dart' • lib/domain/instructor/IsTheInstructorLoggedInUseCase.dart:3:8
   info • Unused import: 'package:evally_mobile_flutter/domain/lesson/Fault.dart' • lib/domain/lesson/GetLessonUseCase.dart:3:8
   info • Don't import implementation files from another package • lib/injector/AppInjector.dart:18:8
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/Router.dart:16:16
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/Router.dart:17:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/Router.dart:18:17
   info • Don't explicitly initialize variables to null • lib/presentation/login/LoginPage.dart:32:10
   info • Don't explicitly initialize variables to null • lib/presentation/login/LoginPage.dart:33:10
   info • 'child' is deprecated and shouldn't be used • lib/presentation/login/LoginPage.dart:147:34
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/presentation/map/EvallyMap.dart:13:7
   info • The getter '_provideIsAStudentSelectedUseCase' isn't used • lib/presentation/reporting/ReportingInjector.dart:35:33
warning • Element 'Image' from SDK library 'ui.dart' is implicitly hidden by 'image.dart' • lib/presentation/reporting/ReportingPage.dart:168:22
   info • Unused import: 'package:evally_mobile_flutter/domain/lesson/DeviceLocation.dart' • lib/presentation/reporting/ReportingView.dart:1:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/presentation/reporting/TimerText.dart:7:7
   info • 'child' is deprecated and shouldn't be used • lib/presentation/reporting/students/AddStudentDialog.dart:22:9
   info • 'child' is deprecated and shouldn't be used • lib/presentation/reporting/students/SelectStudentDialog.dart:18:9
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:5:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:11:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:17:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:23:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:29:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:35:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:41:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:48:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:54:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:60:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:66:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:72:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:78:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:84:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:90:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:96:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:102:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:108:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:114:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:120:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:126:20
   info • Name non-constant identifiers using lowerCamelCase • lib/presentation/resources/BrandTypography.dart:132:20
   info • 'child' is deprecated and shouldn't be used • lib/presentation/review/comment/AddCommentDialog.dart:22:9
warning • Element 'Image' from SDK library 'ui.dart' is implicitly hidden by 'image.dart' • lib/presentation/review/faults/FaultsListView.dart:85:20

42 issues found. (ran in 25.5s)

```

Runnig `flutter doctor -v`
```

[✓] Flutter (Channel dev, v0.5.5, on Mac OS X 10.13.5 17F77, locale en-ES)
    • Flutter version 0.5.5 at /Users/miguelcatalan/Projects/Flutter/flutter
    • Framework revision 020e0ef55c (6 days ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/miguelcatalan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • iPad 2 • 8A059639-9DE4-4667-8FAE-BF514DE1C789 • ios • iOS 9.3 (simulator)

• No issues found!

```

**Comment by zoechi** [comment]
@cbracken

**Comment by cbracken** [comment]
@MiguelCatalan Thanks for reporting!

It sounds like there are two things going on here:
1. You've hit a [32-bit iOS specific bug](https://github.com/flutter/flutter/issues/16124) that was fixed in the latest beta-channel release (released a couple days ago).
2. There might be something mis-configured with the `ARCHS` setting for your Xcode project.

To fix the first problem, run `flutter upgrade` to update to the latest version of Flutter.

For the seconds problem, would you mind pasting the output of the following command, run from your app's directory?
`grep -r XPC_FLAG ios/`

Failure to launch on the simulator looks suspiciously like it might be related to the build architecture settings. Under the build settings for your project, can you verify the Architectures setting says `$(ARCHS_STANDARD)` as described in [this wiki page](https://github.com/flutter/engine/wiki/iOS-Builds-Supporting-ARMv7)?

**Comment by MiguelCatalan** [comment]
Any tips about how to approach this? @cbracken

**Comment by cbracken** [comment]
Two questions:
1. What shell are you using?
2. Can you try `flutter clean` followed by `flutter -v run` with the simulator up and dump the full logs here? Specifically the bit where Xcode dumps the environment would be useful (it'll include vars like ARCHS and others).

It *looks* like somehow Xcode has picked up a separate environment variable and its value (`XPC_FLAGS=0x0`) as the current arch instead of `x86_64`, which is what we'd expect for a simulator run.

**Comment by MiguelCatalan** [comment]
Sorry for answering so late.

1. The output of the `echo $SHELL` instruction outputs: `/bin/bash`
2. Afte running `flutter clean`, the `flutter -v run` instruction outputs: (was so large that cant be printed in a github comment, here it is a link to a gist: https://gist.github.com/MiguelCatalan/8e2f7084032cd18072f4b5bf73635090)

**Comment by MiguelCatalan** [comment]
Any news on this? @cbracken

**Comment by MiguelCatalan** [comment]
@cbracken?

**Comment by MiguelCatalan** [comment]
After creating a new project (this time with swift) seems to work
