### ISSUE TITLE
build_bench produces exception during and after run 

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#18715]
There are two kinds:

```
[   +3 ms] I/flutter ( 9512): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter ( 9512): The following ArgumentError was thrown during a scheduler callback:
[        ] I/flutter ( 9512): Invalid argument (other): Matrix cannot be inverted: Instance of 'Matrix4'
[        ] I/flutter ( 9512): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9512): #0      new Matrix4.inverted (file:///usr/local/google/home/vegorov/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.6/lib/src/vector_math_64/matrix4.dart:237)
[        ] I/flutter ( 9512): #1      TransformLayer.find (package:flutter/src/rendering/layer.dart:780)
[        ] I/flutter ( 9512): #2      RenderView._updateSystemChrome (package:flutter/src/rendering/view.dart:215)
[        ] I/flutter ( 9512): #3      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:198)
[        ] I/flutter ( 9512): #4      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:273)
[        ] I/flutter ( 9512): #5      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding&ServicesBinding&PaintingBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627)
[        ] I/flutter ( 9512): #6      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
[        ] I/flutter ( 9512): #7      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
[        ] I/flutter ( 9512): #8      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
[        ] I/flutter ( 9512): #9      LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1092)
[        ] I/flutter ( 9512): #10     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751)
[        ] I/flutter ( 9512): #19     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
[        ] I/flutter ( 9512): #20     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
[        ] I/flutter ( 9512): #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
[        ] I/flutter ( 9512): (elided 8 frames from package dart:async)
[        ] I/flutter ( 9512): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

and 

```
[+1831 ms] I/flutter ( 9512): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[   +1 ms] I/flutter ( 9512): The following assertion was thrown running a test (but after the test had completed):
[        ] I/flutter ( 9512): Failed assertion: boolean expression must not be null
[   +2 ms] I/flutter ( 9512): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 9512): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9512): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9512):   https://github.com/flutter/flutter/issues/new
[   +2 ms] I/flutter ( 9512): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9512): #0      LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:0)
[        ] I/flutter ( 9512): #1      _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:809)
[        ] I/flutter ( 9512): #2      main.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/vegorov/src/flutter/flutter/dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart:50)
[        ] I/flutter ( 9512): #11     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
[        ] I/flutter ( 9512): #12     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
[        ] I/flutter ( 9512): #13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
[        ] I/flutter ( 9512): (elided 8 frames from package dart:async)
[        ] I/flutter ( 9512): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I am not sure if this is expected or is this Dart bug we need to look into? Any guidance @Hixie?

**Comment by mkustermann** [comment]
Here's what is happening:

The benchmark looks like this [from ](https://github.com/flutter/flutter/blob/master/dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart#L18):
```dart

const Duration kBenchmarkTime = Duration(seconds: 15);

Future<void> main() async {
  ...

  final Stopwatch watch = Stopwatch();
  int iterations = 0;

  await benchmarkWidgets((WidgetTester tester) async {
    ...
    watch.start();
    while (watch.elapsed < kBenchmarkTime) {
      ...
      Timer.run(() { ui.window.onBeginFrame(Duration(milliseconds: iterations * 16)); });
      Timer.run(() { ui.window.onDrawFrame(); });
      await tester.idle(); // wait until the frame has run (also uses Timer.run)
      iterations += 1;
    }
    watch.stop();
  });

  final BenchmarkResultPrinter printer = BenchmarkResultPrinter();
  printer.addResult(
    description: 'Stock build',
    value: watch.elapsedMicroseconds / iterations,
    unit: 'µs per iteration',
    name: 'stock_build_iteration',
  );
  ...
```
Now here we can see that this code **explicitly** injects calls to `ui.window.onBeginFrame` and `ui.window.onDrawFrame` via:
```dart
      Timer.run(() { ui.window.onBeginFrame(Duration(milliseconds: iterations * 16)); });
      Timer.run(() { ui.window.onDrawFrame(); });
```

Though this is not the only code which causes those methods to be called, the embedder does as well via from [engine/flutter/lib/ui/window/window.cc](https://github.com/flutter/engine/blob/master/lib/ui/window/window.cc#L271):
```c++
  DartInvokeField(library_.value(), "_beginFrame", { Dart_NewInteger(microseconds),});
  UIDartState::Current()->FlushMicrotasksNow();
  DartInvokeField(library_.value(), "_drawFrame", {});
```

Now what can happen is the following
  * the two `Timer.run(<callback>)` callbacks have been added to the end of the event loop
  * the embedder calls `Window::BeginFrame()` above, which will
      - invoke `_beginFrame`
      - then run any tasks in the eventloop
           * will invoke the callback of `Timer.run(() { ui.window.onBeginFrame(...); })`
           * will invoke the callback of `Timer.run(() { ui.window.onDrawFrame(...); })`
      - invoke `_drawFrame`

i.e. We have nested _beginFrame / _beginFrame / _drawFrame / _drawFrame (error happens here)

Now this **does not make the benchmark fail**, instead the exceptions get swallowed, the future returned by `benchmarkWidgets()` completes, we mark the benchmark as done (despite having only run it for 2 or 3 seconds) and loop will continue to run afterwards (for `kBenchmarkTime = Duration(seconds: 15)`).

This can be easily verified by adding prints to this code.

@Hixie @mraleph Due to this particular problem our benchmarking results of the build benchmark are extremely unreliable - which makes it hard for Dart VM developers to see whether CLs improve or regress it. It would be very much appreciated if someone from the flutter team could fix this.

**Comment by mkustermann** [comment]
The PR for fixing it is out now https://github.com/flutter/flutter/pull/25049

**Comment by zoechi** [comment]
I assume this can be closed. The PR was merged a while ago.
