### ISSUE TITLE
segmented_control_test.dart seems flaky

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#18737]
Was diagnosing problems with AppVeyor on #18725 and saw segmented_control_test.dart fail once, though not on all runs.  Browsing around on other AppVeyor runs suggest that this could be a flake not related to my PR.

```
⏩ RUNNING: cd packages\flutter; ..\..\bin\flutter.bat test
00:32 +174 ~3: C:\projects\flutter sdk\packages\flutter\test\cupertino\segmented_control_test.dart: Golden Test Pressed State                                                                          
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test (but after the test had completed):
  Expected: one widget whose rasterized image matches golden image "segmented_control_test.1.0.png"
  Actual: ?:<zero widgets with type "RepaintBoundary" (ignoring offstage widgets)>
   Which: does not match
When the exception was thrown, this was the stack:
#0      fail (package:test/src/frontend/expect.dart:165:30)
#1      _expect.<anonymous closure> (package:test/src/frontend/expect.dart:140:9)
#23     _MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/matchers.dart)
<asynchronous suspension>
#24     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:708:22)
#27     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:706:26)
#28     _MatchesGoldenFile.matchAsync (package:flutter_test/src/matchers.dart:1273:20)
#30     _MatchesGoldenFile.matchAsync (package:flutter_test/src/matchers.dart:1254:28)
#31     _expect (package:test/src/frontend/expect.dart:122:26)
#32     expect (package:test/src/frontend/expect.dart:60:3)
#33     expect (package:flutter_test/src/widget_tester.dart:153:16)
#34     main.<anonymous closure> (file:///C:/projects/flutter%20sdk/packages/flutter/test/cupertino/segmented_control_test.dart:928:5)
#48     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:862:17)
#50     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:850:39)
(elided 53 frames from class _FakeAsync, package dart:async, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Full log:  
https://ci.appveyor.com/project/flutter/flutter/build/1.0.14463

Other appveyor runs showing this failure:
https://ci.appveyor.com/project/flutter/flutter/build/1.0.14447
https://ci.appveyor.com/project/flutter/flutter/build/1.0.14442

**Comment by xster** [comment]
@gspencergoog can you take a look?

**Comment by gspencergoog** [comment]
We haven't seen this flake in a while.
