### ISSUE TITLE
test_smoke_test/timeout_pass_test.dart is flaky

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#18741]
@Hixie 

Trying to land #18725 and ran into a flake on AppVeyor in this test at least twice:

```
⏩ RUNNING: cd dev\automated_tests; ..\..\bin\flutter.bat test test_smoke_test\timeout_pass_test.dart
00:11 +0: flutter_test timeout logic - addTime - positive                                                                                                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TimeoutException was thrown running a test:
TimeoutException after 0:00:04.000000: The test exceeded the timeout. It may have hung.
Consider using "addTime" to increase the timeout before expensive operations.
When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._checkTimeout (package:flutter_test/src/binding.dart:786:25)
#16     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#17     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
#22     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:836:25)
#23     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:68:22)
#24     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
#27     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:0:0)
#28     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
#34     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:402:15)
(elided 24 frames from package dart:async and package stack_trace)
The test description was:
flutter_test timeout logic - addTime - positive
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +0 -1: flutter_test timeout logic - addTime - positive [E]                                                                                                                                       
  Test failed. See exception logs above.
  The test description was: flutter_test timeout logic - addTime - positive
  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 873 pos 12: '_currentFakeAsync !=
null': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:519:5)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:502:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:846:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:843:15)
00:11 +0 -1: Some tests failed.                                                                                                                                                                        
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

The [test code](https://github.com/flutter/flutter/blob/d6465c477ab5123e61b57f560eca96128226683e/dev/automated_tests/test_smoke_test/timeout_pass_test.dart#L10) seems to suggest that this is just a case of AppVeyor's dart run not being quite fast enough sometimes to get in under the timeout (only 500ms of wiggle room).

I'll try giving it more wiggle room, but this sort of timing test depending on a real clock always has the potential to flake.

Full log: https://ci.appveyor.com/project/flutter/flutter/build/1.0.14468

**Comment by jcollins-g** [comment]
Duplicate of #18507.
