### ISSUE TITLE
Problems with TextFormField in ListView

### ISSUE THREAD

**Issue by VVlESEL** [flutter/flutter#18755]
Hey, i experienced a weird issue and do not know where it comes from. Everything used to work fine until today. Now i get this error:

```
I/flutter (20447): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20447): The following assertion was thrown during performLayout():
I/flutter (20447): not implemented
I/flutter (20447): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (20447): 
I/flutter (20447): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20447): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20447): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20447):   https://github.com/flutter/flutter/issues/new
I/flutter (20447): 
I/flutter (20447): When the exception was thrown, this was the stack:
I/flutter (20447): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (20447): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (20447): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (20447): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (20447): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (20447): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (20447): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (20447): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (20447): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (20447): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (20447): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (20447): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (20447): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (20447): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (20447): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (20447): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (20447): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (20447): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (20447): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:779:38)
I/flutter (20447): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (20447): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #32     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:384:13)
I/flutter (20447): #33     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
I/flutter (20447): #34     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
I/flutter (20447): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #36     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (20447): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #38     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter (20447): #39     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
I/flutter (20447): #40     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
I/flutter (20447): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #58     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (20447): #59     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (20447): #60     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (20447): #61     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (20447): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #66     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (20447): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (20447): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #82     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2829:14)
I/flutter (20447): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (20447): #84     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (20447): #85     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (20447): #86     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (20447): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (20447): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (20447): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (20447): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (20447): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (20447): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (20447): #93     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (20447): #94     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (20447): (elided 2 frames from class _AssertionError)
I/flutter (20447): 
I/flutter (20447): The following RenderObject was being processed when the exception was fired:
I/flutter (20447):   _RenderListTile#79c11 relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (20447):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (20447):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← RepaintBoundary-[<1>] ← ⋯
I/flutter (20447):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (20447):   constraints: BoxConstraints(w=379.4, 0.0<=h<=Infinity)
I/flutter (20447):   size: MISSING
I/flutter (20447): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20447):   RenderParagraph#fe64d relayoutBoundary=up9 NEEDS-PAINT
I/flutter (20447):   RenderSemanticsAnnotations#e3fd3 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (20447):     RenderIgnorePointer#34889 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (20447):       RenderPointerListener#45087 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (20447):         _RenderDecoration#dd394 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (20447):           RenderRepaintBoundary#fcf91 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (20447):           RenderOpacity#7041c relayoutBoundary=up13 NEEDS-PAINT
I/flutter (20447):           RenderConstrainedBox#cf7fd relayoutBoundary=up13 NEEDS-PAINT
I/flutter (20447):           RenderCustomPaint#12641 NEEDS-PAINT
I/flutter (20447): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I use this body in a Scaffold:

```dart
      body: Form(
        key: _formKey,
        child: ListView(
          children: <Widget>[
            FlatButton(
              onPressed: _updateImage,
              child: Center(
                child: _image == null
                    ? Container(
                        height: 150.0,
                      )
                    : Container(
                        width: 150.0,
                        height: 150.0,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          image:
                              DecorationImage(fit: BoxFit.fill, image: _image),
                        ),
                      ),
              ),
            ),
            ListTile(
              title: Text(
                "Name",
                style: _titleStyle,
              ),
              subtitle: TextFormField(
                controller: _nameController,
                validator: (text) {
                  if (text.isEmpty) return "Please enter your name";
                },
                decoration: InputDecoration(
                  hintText: "Type your display name here",
                  hintStyle: _titleStyle,
                ),
              ),
            ),
            ListTile(
              title: Text(
                "About",
                style: _titleStyle,
              ),
              subtitle: TextFormField(
                controller: _aboutController,
                validator: (text) {
                  if (text.isEmpty) return "Please tell us something about you";
                },
                maxLines: 5,
                decoration: InputDecoration(
                  hintText: "What describes you and your skills the best?",
                  hintStyle: _titleStyle,
                ),
              ),
            ),
            ListTile(
              title: Text(
                "Website",
                style: _titleStyle,
              ),
              subtitle: TextFormField(
                validator: (text) {},
                controller: _websiteController,
                decoration: InputDecoration(
                  hintText: "https://www.",
                  hintStyle: _titleStyle,
                ),
              ),
            ),
          ],
        ),
      ),
```

If I comment all the ListTiles out and only leave the FlatButton in the List everything works. It also works fine when I add a ListTile without the subtitle. As soon as i add the subtitle with the TextFormField I get this error message.

I would be glad if someone could help me out. Thanks :)

Greetings, René

**Comment by escamoteur** [comment]
Could you please add your flutter doctor -v output so that we know on which version you are. I just checked in the dev branch and there isn't an assert on that line.

**Comment by VVlESEL** [comment]
Sure. This is the output:
flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale de-DE)
    • Flutter version 0.5.1 at C:\Program Files\flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\BM Trading\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

Thanks for your support.

**Comment by VVlESEL** [comment]
I just removed the ListTiles now and put the TextFields directly into the parent ListView. That solved the problem. Still kinda weird to me that it throws an error if I put the TextFormField into the subtitle...

**Comment by escamoteur** [comment]
Please reopen it so that the team can check it out

**Comment by jonahwilliams** [comment]
I believe the fact that this error was thrown is intentional, though the actual problem needs to be communicated better.  I'm less familiar with this code, but I'll take this up as an issue to improve that error message

**Comment by VVlESEL** [comment]
Do I have to reopen this or is it okay now? Sorry I am kinda new to this...

**Comment by escamoteur** [comment]
That's fine so

**Comment by ThinkDigitalRepair** [comment]
I'm having this issue as well with the `TextFormField` inside a `ListTile` `subtitle`

**Comment by jonahwilliams** [comment]
cc @HansMuller

**Comment by goderbauer** [comment]
I am de-duping this against https://github.com/flutter/flutter/issues/24705, which has the same underlying issue.
