### ISSUE TITLE
Tabview error

### ISSUE THREAD

**Issue by jhionan** [flutter/flutter#18763]
have a bottom navigation bar, and the 2 tab is have appbar + 2 tabs.

get error when clicking bottomNavigationBar 3 to 1 without clicking at 2

https://github.com/jhionan/flutterError

Error:
```
`I/flutter (11406): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11406): The following assertion was thrown while finalizing the widget tree:
I/flutter (11406): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 657 pos 12: 'pixels !=
I/flutter (11406): null': is not true.
I/flutter (11406): 
I/flutter (11406): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11406): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11406): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11406):   https://github.com/flutter/flutter/issues/new
I/flutter (11406): 
I/flutter (11406): When the exception was thrown, this was the stack:
I/flutter (11406): #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart)
I/flutter (11406): #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:255:11)
I/flutter (11406): #4      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:324:14)
I/flutter (11406): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3821:12)
I/flutter (11406): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter (11406): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #26     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
I/flutter (11406): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (11406): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (11406): #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (11406): #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (11406): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
I/flutter (11406): #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (11406): #76     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (11406): #77     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter (11406): #78     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2328:27)
I/flutter (11406): #79     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2160:15)
I/flutter (11406): #80     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2327:7)
I/flutter (11406): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628:18)
I/flutter (11406): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (11406): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (11406): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (11406): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (11406): #86     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (11406): #87     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (11406): (elided 2 frames from class _AssertionError)
I/flutter (11406): ════════════════════════════════════════════════════════════════════════════════════════════════════`
```

**Comment by escamoteur** [comment]
Please add your flutter doctor -v output

**Comment by zoechi** [comment]
I'm going to close this as dup of #18756 because it has a bit more information.
Thanks @escamoteur for finding the dup.
