### ISSUE TITLE
Invalid Websocket upgrade request

### ISSUE THREAD

**Issue by imphat** [flutter/flutter#18776]
I am getting this error when trying to run a new project on both vscode and android studio: 

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate(11715): onResume setting current activity to this
E/DartVM  (11715): vm-service: Error: Unhandled exception:
E/DartVM  (11715): WebSocketException: Invalid WebSocket upgrade request
E/DartVM  (11715): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
E/DartVM  (11715): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/DartVM  (11715): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/DartVM  (11715): #3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
E/DartVM  (11715): #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
E/DartVM  (11715):
E/flutter (11715): [ERROR:flutter/runtime/dart_isolate.cc(749)] Isolate (927231947) 'vm-service' exited with an error
E/flutter (11715): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (11715): WebSocketException: Invalid WebSocket upgrade request
E/flutter (11715): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
E/flutter (11715): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (11715): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (11715): #3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
E/flutter (11715): #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
Exited (sigterm)

flutter doctor seems ok
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

Can anyone help me fixing it? I am on ubuntu 18.04

**Comment by imphat** [comment]
It seems to be an issue with my proxy settings. As suggested [here](https://github.com/flutter/flutter/issues/16875), adding noproxy=127.0.0.1 to my .profile file solved the problem so far.
