### ISSUE TITLE
input_decorator.dart': Failed assertion: line 918 pos 12: 'false'

### ISSUE THREAD

**Issue by dhaliwaljee** [flutter/flutter#18778]
```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart'; //https://pub.dartlang.org/packages/path_provider#-installing-tab-

void main() async {
  var data = await readData();

  if (data != null) {
    String message = await readData();
    print(message);
  }

  runApp(new MaterialApp(
    title: 'IO',
    home: new Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => new _HomeState();
}

class _HomeState extends State<Home> {
  var _enterDataField = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Read/Write'),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),
      body: new Container(
        padding: const EdgeInsets.all(13.4),
        alignment: Alignment.topCenter,
        child: new ListTile(
          title: new TextField(
            controller: _enterDataField,
            decoration: new InputDecoration(labelText: 'Write Something'),
          ),
          subtitle: new FlatButton(
              color: Colors.redAccent,
              onPressed: () {
                //save to file
                writeData(_enterDataField.text);
              },
              child: new Column(
                children: <Widget>[
                  new Text('Save Data'),
                  new Padding(padding: new EdgeInsets.all(14.5)),
                  new FutureBuilder(
                      future: readData(),
                      builder:
                          (BuildContext context, AsyncSnapshot<String> data) {
                        if (data.hasData != null) {
                          return new Text(
                            data.data.toString(),
                            style: new TextStyle(color: Colors.white70),
                          );
                        } else {
                          return new Text("No data saved");
                        }
                      })
                ],
              )),
        ),
      ),
    );
  }
}

Future<String> get _localPath async {
  final directory = await getApplicationDocumentsDirectory();
  return directory.path; //home/directory/
}

Future<File> get _localFile async {
  final path = await _localPath;

  return new File('$path/data.txt'); //home/directory/data.txt
}

//Write and Read from our file
Future<File> writeData(String message) async {
  final file = await _localFile;

  //write to file
  return file.writeAsString('$message');
}

Future<String> readData() async {
  try {
    final file = await _localFile;

    //Read
    String data = await file.readAsString();

    return data;
  } catch (e) {
    return "Nothing saved yet!";
  }
}

```

### Exception

```
> Launching lib\Files\Files_Main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...
> Resolving dependencies...
> Running 'gradlew assembleDebug'...
> Built build\app\outputs\apk\debug\app-debug.apk.
> Installing build\app\outputs\apk\app.apk...
> I/flutter (  794): Nothing saved yet!
> Syncing files to device Android SDK built for x86...
> I/flutter (  794): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
> I/flutter (  794): The following assertion was thrown during performLayout():
> I/flutter (  794): not implemented
> I/flutter (  794): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 918 pos 12: 'false'
> I/flutter (  794): 
> I/flutter (  794): Either the assertion indicates an error in the framework itself, or we should provide substantially
> I/flutter (  794): more information in this error message to help you determine and fix the underlying cause.
> I/flutter (  794): In either case, please report this assertion by filing a bug on GitHub:
> I/flutter (  794):   https://github.com/flutter/flutter/issues/new
> I/flutter (  794): 
> I/flutter (  794): When the exception was thrown, this was the stack:
> I/flutter (  794): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
> I/flutter (  794): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1636:50)
> I/flutter (  794): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
> I/flutter (  794): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1636:22)
> I/flutter (  794): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
> I/flutter (  794): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1636:50)
> I/flutter (  794): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
> I/flutter (  794): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1636:22)
> I/flutter (  794): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
> I/flutter (  794): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1636:50)
> I/flutter (  794): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
> I/flutter (  794): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1636:22)
> I/flutter (  794): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
> I/flutter (  794): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1636:50)
> I/flutter (  794): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
> I/flutter (  794): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1636:22)
> I/flutter (  794): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1619:27)
> I/flutter (  794): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:883:16)
> I/flutter (  794): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:942:32)
> I/flutter (  794): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
> I/flutter (  794): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
> I/flutter (  794): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
> I/flutter (  794): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
> I/flutter (  794): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
> I/flutter (  794): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
> I/flutter (  794): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
> I/flutter (  794): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
> I/flutter (  794): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2820:13)
> I/flutter (  794): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
> I/flutter (  794): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
> I/flutter (  794): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
> I/flutter (  794): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
> I/flutter (  794): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
> I/flutter (  794): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
> I/flutter (  794): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
> I/flutter (  794): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
> I/flutter (  794): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
> I/flutter (  794): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
> I/flutter (  794): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
> I/flutter (  794): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
> I/flutter (  794): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
> I/flutter (  794): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
> I/flutter (  794): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
> I/flutter (  794): (elided 3 frames from class _AssertionError and package dart:async)
> I/flutter (  794): 
> I/flutter (  794): The following RenderObject was being processed when the exception was fired:
> I/flutter (  794):   _RenderListTile#06df8 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
> I/flutter (  794):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
> I/flutter (  794):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
> I/flutter (  794):   parentData: offset=Offset(0.0, 0.0) (can use size)
> I/flutter (  794):   constraints: BoxConstraints(0.0<=w<=352.6, 0.0<=h<=576.6)
> I/flutter (  794):   size: MISSING
> I/flutter (  794): This RenderObject had the following descendants (showing up to depth 5):
> I/flutter (  794):   RenderSemanticsAnnotations#59aee relayoutBoundary=up8 NEEDS-PAINT
> I/flutter (  794):     RenderIgnorePointer#3c9a1 relayoutBoundary=up9 NEEDS-PAINT
> I/flutter (  794):       RenderPointerListener#9ed19 relayoutBoundary=up10 NEEDS-PAINT
> I/flutter (  794):         _RenderDecoration#2c0f6 relayoutBoundary=up11 NEEDS-PAINT
> I/flutter (  794):           RenderRepaintBoundary#4e360 relayoutBoundary=up12 NEEDS-PAINT
> I/flutter (  794):           RenderTransform#acc66 relayoutBoundary=up12 NEEDS-PAINT
> I/flutter (  794):           RenderConstrainedBox#e3673 relayoutBoundary=up12 NEEDS-PAINT
> I/flutter (  794):           RenderCustomPaint#e4e3a NEEDS-PAINT
> I/flutter (  794):   RenderSemanticsAnnotations#2a5d2 relayoutBoundary=up8 NEEDS-PAINT
> I/flutter (  794):     RenderConstrainedBox#e6f71 relayoutBoundary=up9 NEEDS-PAINT
> I/flutter (  794):       RenderPhysicalShape#bdee3 relayoutBoundary=up10 NEEDS-PAINT
> I/flutter (  794):         RenderCustomPaint#df0ec relayoutBoundary=up11 NEEDS-PAINT
> I/flutter (  794):           _RenderInkFeatures#64e41 relayoutBoundary=up12 NEEDS-PAINT
> I/flutter (  794): ════════════════════════════════════════════════════════════════════════════════════════════════════
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: _RenderListTile#06df8 relayoutBoundary=up7 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderPadding#cea21 relayoutBoundary=up6 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#c528f relayoutBoundary=up5 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#cb535 relayoutBoundary=up4 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
> D/        (  794): HostConnection::get() New Host Connection established 0xe2b886c0, tid 820
> D/EGL_emulation(  794): eglMakeCurrent: 0xea7b4f20: ver 3 1 (tinfo 0xe2b83350)
> I/flutter (  794): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: _RenderListTile#06df8 relayoutBoundary=up7 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderPadding#cea21 relayoutBoundary=up6 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#c528f relayoutBoundary=up5 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#cb535 relayoutBoundary=up4 NEEDS-PAINT
> I/flutter (  794): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
> 
```

**Comment by coolzilj** [comment]
Seems like `input_decorator` is not implemented some protocol which is called by ListTile's title.
I suggest you try another container, it's weird to wrap so many elements in a ListTile.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by jmolins** [comment]
You can't use a TextField as a `title` in ListTile (with the present implementation).

`InputDecorator`, which is used by the `TextField`, implements a [unusable default](https://github.com/flutter/flutter/blob/af5d4c688205c7b348201c702b05c03f1f5eb9ff/packages/flutter/lib/src/material/input_decorator.dart#L916) `computeDistanceToActualBaseline()` that produces the assertion.

```
  @override
  double computeDistanceToActualBaseline(TextBaseline baseline) {
    assert(false, 'not implemented');
    return 0.0;
  }
```

[ListTile](https://github.com/flutter/flutter/blob/af5d4c688205c7b348201c702b05c03f1f5eb9ff/packages/flutter/lib/src/material/list_tile.dart#L876) requires the method to be implemented as it is called when its own `computeDistanceToActualBaseline()` method is called:

```
  @override
  double computeDistanceToActualBaseline(TextBaseline baseline) {
    assert(title != null);
    final BoxParentData parentData = title.parentData;
    return parentData.offset.dy + title.getDistanceToActualBaseline(baseline);
  }
```
The last call `title.getDistanceToActualBaseline(baseline)` produces the assertion when the first code is called.

**Comment by zoechi** [comment]
I believe this is a dup of #18755

**Comment by zoechi** [comment]
I think this is a dup of #18755
