### ISSUE TITLE
I'm posting about "please let us know at https://github.com/flutter/flutter/issues.".

### ISSUE THREAD

**Issue by kendji** [flutter/flutter#18780]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --release

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x92 (at offset 0)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:574)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#11     _StreamController._add (dart:async/stream_controller.dart:639)
#12     _StreamController.add (dart:async/stream_controller.dart:585)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#20     _StreamController._add (dart:async/stream_controller.dart:639)
#21     _StreamController.add (dart:async/stream_controller.dart:585)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.5.6-pre.26, on Microsoft Windows [Version 10.0.17134.112], locale ja-JP)
    • Flutter version 0.5.6-pre.26 at C:\Users\takitani.kenji.AIRIKI\Flutter SDK
    • Framework revision 08d1ec36de (6 days ago), 2018-06-19 00:58:20 -0700
    • Engine revision 0c119932c0
    • Dart version 2.0.0-dev.62.0.flutter-4b2d60cb18

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\takitani.kenji.AIRIKI\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[✓] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

• No issues found!
```

**Comment by coolzilj** [comment]
change your project files encoding to UTF-8, save it, compile one more time

**Comment by khanghyxda** [comment]
Window Japanses language has the same error. Window English build ok.

**Comment by kendji** [comment]
Alright, thank you.
I think it is not serious.
