### ISSUE TITLE
Missing Czech Language (cs) in Material Localization

### ISSUE THREAD

**Issue by vladaman** [flutter/flutter#18794]
Localization package does not contain Czech language translations for Material widgets. It causes crash when app is executed on device with cs locale.

**Comment by wychi** [comment]
Indonesian, Indonesia (id_ID) has the same problem
```
E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    Invalid argument(s): Invalid locale 'id_ID'
    #0      Intl._throwLocaleError (package:intl/intl.dart:240:5)
    #1      Intl.verifiedLocale (package:intl/intl.dart:234:21)
    #2      Intl.verifiedLocale (package:intl/intl.dart:219:14)
    #3      new DateFormat (file:///Users/wychi/.pub-cache/hosted/pub.dartlang.org/intl-0.15.6/lib/src/intl/date_format.dart:246:20)
   ```

```
Flutter 0.5.6-pre.61 • channel unknown • unknown source
Framework • revision 2e559584e2 (9 days ago) • 2018-06-22 16:32:32 -0700
Engine • revision 549c855e89
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
```

**Comment by HansMuller** [comment]
Sorry about the cryptic error message.

We don't support Czech ("cs" locale) yet however I've requested support for "from the translations team. Should be available in roughly two weeks.

See also: #14890, #13482, #17182

**Comment by HansMuller** [comment]
@wychi We have included support of Indonesian since https://github.com/flutter/flutter/pull/15708 (it's included in the current beta/dev channels).

Perhaps you're running into a bug. If you could submit a new issue with  a small test case that fails when the current locale is 'id_ID', I'll look into it.

**Comment by wychi** [comment]
@HansMuller 

Here is the sample code.
I found  another crash while creating this sample.
You can find it in the comment.

Thanks


```
import 'dart:async';

import 'package:coin_master/utils/env.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';
import 'package:intl/intl_standalone.dart';

class SampleApp extends StatelessWidget {
  // Note: uncomment this, the crash goes away.
  // final DateFormat dateFormat = new DateFormat('MM/dd HH:mm');

  @override
  Widget build(BuildContext context) {
    // https://github.com/flutter/flutter/issues/14128
    Future<String> future;
    if (isiOS()) {
      future = Future.value("in_ID");
    } else {
      future = findSystemLocale();
    }

    return FutureBuilder(
      future: future,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Container();
        }
        var currentLocale = snapshot.data;
        // NOTE: override for demo
        currentLocale = new Locale("id", "ID");
        return new MaterialApp(
          locale: currentLocale,
          title: 'Flutter Demo',
          theme: new ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: ClockWidget(),
// Note: crash2
//          home: Container(
//            child: Text(
//                "Date ${new DateFormat().add_Hms().format(new DateTime.now())}"),
//          ),
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
          ],
        );
      },
    );
  }
}

class ClockWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final DateFormat dateFormat = new DateFormat('MM/dd HH:mm');

    return Container(
      child: Text("Date ${dateFormat.format(new DateTime.now())}"),
    );
  }
}

void main() {
  runApp(new SampleApp());
}

```

**Comment by wychi** [comment]
@HansMuller 
I already submit another issue regard to my problem
https://github.com/flutter/flutter/issues/19155

**Comment by HansMuller** [comment]
@vladaman support for Czech was added in https://github.com/flutter/flutter/pull/19567
