### ISSUE TITLE
TextField focused in a TabView

### ISSUE THREAD

**Issue by xascis** [flutter/flutter#18793]
## Description
Error while navigating among tabs.

## Error
```
I/flutter ( 4532): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4532): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 4532): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2811 pos 14:
I/flutter ( 4532): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 4532): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4532): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4532): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4532):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4532): When the exception was thrown, this was the stack:
I/flutter ( 4532): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart)
I/flutter ( 4532): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2845:5)
I/flutter ( 4532): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 4532): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:865:18)
I/flutter ( 4532): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4513:35)
I/flutter ( 4532): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4279:5)
I/flutter ( 4532): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4653:11)
I/flutter ( 4532): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4532): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4532): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4532): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4532): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4532): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4532): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4532): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4532): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter ( 4532): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4532): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4532): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 4532): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 4532): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 4532): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 4532): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 4532): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter ( 4532): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
I/flutter ( 4532): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter ( 4532): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter ( 4532): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 4532): #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 4532): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 4532): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4532): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 4532): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4532): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4532): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4532): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #77     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4532): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 4532): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 4532): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 4532): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 4532): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 4532): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 4532): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 4532): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 4532): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4532): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4532): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 4532): #95     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 4532): #96     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 4532): (elided 2 frames from class _AssertionError)
I/flutter ( 4532): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
## Example

Focus on TextField in Tab1, write some text. Go to Tab 3, and back to Tab 1.

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: new MyHomePage(title: 'Flutter Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        elevation: 0.0,
        title: Text(widget.title),
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: Container(
              child: DefaultTabController(
                length: 3,
                child: Column(
                  children: <Widget>[
                    TabBar(
                      tabs: <Widget>[
                        Tab(text: 'Tab 1'),
                        Tab(text: 'Tab 2'),
                        Tab(text: 'Tab 3'),
                      ],
                    ),
                    Expanded(
                      child: Container(
                        padding: EdgeInsets.all(20.0),
                        child: TabBarView(
                          children: <Widget>[
                            Center(
                              child: Row(
                                children: <Widget>[
                                  Expanded(
                                    child: Container(
                                      child: TextField(
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Center(child: Text('Tab 2')),
                            Center(child: Text('Tab 3'))
                          ],
                        ),
                      ),
                    )
                  ],
                )
              ),
            ),
          ),
        ],
      )
    );
  }
}

```

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.6-pre.23, on Microsoft Windows [VersiÃ³n 10.0.16299.492], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.24.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
might be a dup of #11895

**Comment by zoechi** [comment]
Closing as dup of #11895
