### ISSUE TITLE
Problem when inspect variable values ​​when in debug mode

### ISSUE THREAD

**Issue by yuridiniz** [flutter/flutter#18857]
## Steps to Reproduce

1. Create a application in VSCode or Android Studio
2. Run the app in Debug mode
3. Put a break point
4. When the application pauses at the breakpoint, move the cursor to the variable to see the value

## Logs
```
compiler message: Unhandled exception:
compiler message: NoSuchMethodError: The getter 'loader' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: loader
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:429)
compiler message: <asynchronous suspension>
compiler message: #2      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #3      new Future.sync (dart:async/future.dart:222)
compiler message: #4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #5      _rootRun (dart:async/zone.dart:1126)
compiler message: #6      _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #7      _runZoned (dart:async/zone.dart:1518)
compiler message: #8      runZoned (dart:async/zone.dart:1465)
compiler message: #9      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117)
compiler message: #10     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:428)
compiler message: <asynchronous suspension>
compiler message: #11     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:103)
compiler message: #12     FrontendCompiler.compileExpression (package:vm/frontend_server.dart:448)
compiler message: <asynchronous suspension>
compiler message: #13     _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:55)
compiler message: #14     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:650)
compiler message: <asynchronous suspension>
compiler message: #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
compiler message: #19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
compiler message: #20     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
compiler message: #21     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
compiler message: #22     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
compiler message: #23     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
compiler message: #24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
compiler message: #25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
compiler message: #29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
compiler message: #30     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
compiler message: #31     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
compiler message: #32     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
compiler message: #33     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
compiler message: #34     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
compiler message: #35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
compiler message: #36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #39     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
compiler message: #40     _StreamController._add (dart:async/stream_controller.dart:639)
compiler message: #41     _StreamController.add (dart:async/stream_controller.dart:585)
compiler message: #42     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
compiler message: #43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
compiler message: #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
compiler message: #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
compiler message: #46     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
compiler message: #47     _StreamController._add (dart:async/stream_controller.dart:639)
compiler message: #48     _StreamController.add (dart:async/stream_controller.dart:585)
compiler message: #49     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
compiler message: #50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
compiler message: #51     _microtaskLoop (dart:async/schedule_microtask.dart:41)
compiler message: #52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
compiler message: #53     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
compiler message: #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.6-pre.78, on Microsoft Windows [versÃ£o 10.0.17134.112], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.24.1)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

```

```
[√] Flutter (Channel master, v0.5.6-pre.78, on Microsoft Windows [versÃ£o 10.0.17134.112], locale pt-BR)
    • Flutter version 0.5.6-pre.78 at C:\flutter
    • Framework revision b44784b429 (58 minutes ago), 2018-06-26 15:11:37 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Yuri\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[√] Connected devices (1 available)
    • Moto Z2 Play • 0040861752 • android-arm • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
I think this is supposed to be fixed in master by #18703,
but seems not to.
See also https://github.com/flutter/flutter/issues/18574#issuecomment-399858283

**Comment by zoechi** [comment]
Seems I get this currently when a breakpoint is hit.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.97, on Mac OS X 10.13.5 17F77, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] Connected devices (1 available)
```
The debugger then stops working and I have to restart the app.

**Comment by DanTup** [comment]
Can anyone still repro this? There were quite a few expression evaluation issues around this time and hopefully they've all been fixed (and I've added some integration tests that stop at breakpoints and evaluate expressions to try and catch regressions).

If you can still repro, please run `Dart: Capture Logs`, tick `Flutter Run` + `Debugger` and then repro and provide the log.

**Comment by danielleiszen** [comment]
I still have this issue.  Is this the expected result on beta channels with flutter-web?
DevTools says I already have a debug session in VSCode but that is useless without variable inspection. So actually I do not have a debug session anywhere...
What did I do wrong?

[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18362.836], locale hu-HU)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android
    • ANDROID_SDK_ROOT = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files (x86)\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

**Comment by DanTup** [comment]
@danielleiszen this issue is quite old and pre-web. It would be better to open a new issue if you're having issues with web, including the exact behaviour/error you see.

That said, expression evaluation for web is currently behind a flag - you can find details (and instructions on how to set it for VS Code) here under the title "Web Debugging with Expression Evaluation":

https://medium.com/flutter/flutter-web-support-updates-8b14bfe6a908
