### ISSUE TITLE
More helpful error messages and stack traces

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#18856]
This is the extent of the error message I get, with no stack trace that leads me to my code.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

**Comment by ThinkDigitalRepair** [comment]
After restarting, it crashed again with a stack trace.
I/flutter ( 5757): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5757): The following NoSuchMethodError was thrown during performLayout():
I/flutter ( 5757): The method '[]' was called on null.
I/flutter ( 5757): Receiver: null
I/flutter ( 5757): Tried calling: [](0)
I/flutter ( 5757): 
I/flutter ( 5757): When the exception was thrown, this was the stack:
I/flutter ( 5757): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
I/flutter ( 5757): #1      _RecordingsTabState.build.<anonymous closure> (file:///home/thinkdigital/IdeaProjects/livekh_flutter/lib/ui/hall_page_tabs/recordings_tab.dart:42:32)
I/flutter ( 5757): #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197:20)
I/flutter ( 5757): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716:67)
I/flutter ( 5757): #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter ( 5757): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716:26)
I/flutter ( 5757): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:55)
I/flutter ( 5757): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 5757): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter ( 5757): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter ( 5757): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter ( 5757): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter ( 5757): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter ( 5757): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter ( 5757): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
I/flutter ( 5757): #15     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter ( 5757): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 5757): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter ( 5757): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
I/flutter ( 5757): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
I/flutter ( 5757): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 5757): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #41     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:384:13)
I/flutter ( 5757): #42     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:208:17)
I/flutter ( 5757): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 5757): #44     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter ( 5757): #45     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
I/flutter ( 5757): #46     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
I/flutter ( 5757): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 5757): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 5757): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 5757): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 5757): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5757): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5757): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5757): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5757): #55     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 5757): #56     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 5757): 
I/flutter ( 5757): The following RenderObject was being processed when the exception was fired:
I/flutter ( 5757):   RenderSliverList#c3d86 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5757):   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter ( 5757):   IgnorePointer-[GlobalKey#5985d] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 5757):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e24c6] ←
I/flutter ( 5757):   _ExcludableScrollSemantics-[GlobalKey#17aea] ← RepaintBoundary ← ⋯
I/flutter ( 5757):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter ( 5757):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 5757):   scrollOffset: 0.0, remainingPaintExtent: 643.7, crossAxisExtent: 411.4, crossAxisDirection:
I/flutter ( 5757):   AxisDirection.right, viewportMainAxisExtent: 643.7, remainingCacheExtent: 893.7 cacheOrigin: 0.0 )
I/flutter ( 5757):   geometry: null
I/flutter ( 5757):   no children current live
I/flutter ( 5757): This RenderObject has no descendants.
I/flutter ( 5757): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter ( 5757): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
I/flutter ( 5757): _AudioTabState.dispose() called.
D/ViewRootImpl@2bda172[MainActivity]( 5757): ViewPostIme pointer 1
D/ViewRootImpl@2bda172[MainActivity]( 5757): ViewPostIme pointer 0
V/MediaPlayer-JNI( 5757): native_finalize
V/MediaPlayer-JNI( 5757): release
D/ViewRootImpl@2bda172[MainActivity]( 5757): ViewPostIme pointer 1
E/flutter ( 5757): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 5757): NoSuchMethodError: The getter 'visible' was called on null.
E/flutter ( 5757): Receiver: null
E/flutter ( 5757): Tried calling: visible
E/flutter ( 5757): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
E/flutter ( 5757): #1      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:503:26)
E/flutter ( 5757): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #5      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2727:37)
E/flutter ( 5757): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #9      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:165:19)
E/flutter ( 5757): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #17     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:500:18)
E/flutter ( 5757): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #23     _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1471:22)
E/flutter ( 5757): #24     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:455:11)
E/flutter ( 5757): #25     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1137:11)
E/flutter ( 5757): #26     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:503:43)
E/flutter ( 5757): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #30     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2727:37)
E/flutter ( 5757): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1863:11)
E/flutter ( 5757): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:118:19)
E/flutter ( 5757): #34     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:165:19)
E/flutter ( 5757): #35     _RenderProxyBox&RenderBox&RenderObjectWithChild
