### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0x4c (at offset 684)

### ISSUE THREAD

**Issue by OkancanCosar** [flutter/flutter#18875]
## Steps to Reproduce

1. I am getting this kinda exceptions when i wrote 'flutter run' in command line
2. I have already checked other UTF-8 issues of flutter. However, it doesnt work for me.
3. For some reason, i am using flutter v0.2.4, i also have tried to last update .In the last update, the logcat shows me that error "This Flutter engine instance is already running an application".
4. File->Settings-> File Encodings -> Project Encoding -> UTF-8 => done.

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x4c (at offset 684)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#11     _StreamController._add (dart:async/stream_controller.dart:639)
#12     _StreamController.add (dart:async/stream_controller.dart:585)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#20     _StreamController._add (dart:async/stream_controller.dart:639)
#21     _StreamController.add (dart:async/stream_controller.dart:585)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

```
$  flutter analyze

Analyzing C:\Users\xxxx\persistent_service\example...
  hint - Unused import: 'package:flutter/services.dart' at lib\main.dart:2:8 - unused_import
  hint - Unused import: 'package:persistent_service/persistent_service.dart' at lib\main.dart:3:8 - unused_import
2 issues found.
(Ran in 6.8s)
```

```

$  flutter doctor -v

[√] Flutter (Channel unknown, v0.2.4, on Microsoft Windows [Version 10.0.17134.112], locale tr-TR)
    • Flutter version 0.2.4 at F:\Flutter
    • Framework revision 3352a3fb48 (3 months ago), 2018-03-20 19:30:06 +0100
    • Engine revision 6280adbfb1
    • Dart version 2.0.0-dev.39.0.flutter-06949dc985

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\xxxx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices (1 available)
    • LG D802TR • LGD802TR1d6f75a2 • android-arm • Android 5.0.2 (API 21)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
You are using quite an outdated Flutter version. 

There was a recent change (might not have landed in `master` yet). 
Can you please check if you can still reproduce with master?
