### ISSUE TITLE
Cant create flutter apps if Windows User Profile name has a space in it

### ISSUE THREAD

**Issue by SherOnDale** [flutter/flutter#18938]
My only User Profile in my Windows PC has a space in it. Because of that, I cant do anything with flutter. Will this be fixed? Only way around this is to create a new User Account without space?

## Steps to Reproduce

1.  Create a User account with space in it.
2.  run flutter create test_app

## Logs
```
Running "flutter packages get" in first...                  19.2s

CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 3a63d7dedece9c9d)
-CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Sherin Binu\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runSync (package:flutter_tools/src/base/process.dart:296)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:557)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:54)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:165)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:93)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:530)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#13     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:194)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     _doctorText (package:flutter_tools/runner.dart:193)
<asynchronous suspension>
#20     _createLocalCrashReport (package:flutter_tools/runner.dart:171)
<asynchronous suspension>
#21     _handleToolError (package:flutter_tools/runner.dart:126)
<asynchronous suspension>
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:50)
#30     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#31     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

<!-- If possible, paste the output of running `flutter doctor -v` here. -->
## When i run flutter doctor -v

[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-IN)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (4 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

-CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Sherin Binu\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runSync (package:flutter_tools/src/base/process.dart:296)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:557)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:54)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:165)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:93)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:530)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#13     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1126)
#26     _CustomZone.run (dart:async/zone.dart:1023)
#27     runZoned (dart:async/zone.dart:1501)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#31     new Future.sync (dart:async/future.dart:222)
#32     CommandRunner.run (package:args/command_runner.dart:109)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1126)
#37     _CustomZone.run (dart:async/zone.dart:1023)
#38     runZoned (dart:async/zone.dart:1501)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:50)
#42     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#43     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by DanTup** [comment]
Possibly this is the same issue as reported in #15609. There's a comment at https://github.com/flutter/flutter/issues/9976#issuecomment-365051558 suggesting all spaces-in-paths issues are fixed.

Can you run `flutter --version` and confirm which version of Flutter you're using?

**Comment by SherOnDale** [comment]
Yes, That path is correct and it got only fixed only after I removed the space from the User Profile name. Windows 10 BTW.

**Comment by DanTup** [comment]
Weird; I think I've done exactly the same and can't repro. I created a new user account called "Test Account" and my Android SDK is installed in the AppData folder like yours:

```
M:\Coding\Applications\Google\flutter>bin\flutter.bat doctor -v
[v] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-GB)
    � Flutter version 0.5.1 at M:\Coding\Applications\Google\flutter
    � Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    � Engine revision 1ed25ca7b7
    � Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    � Android SDK at C:\Users\Test Account\AppData\Local\Android\sdk
    � Android NDK location not configured (optional; useful for native profiling support)
    � Platform android-28, build-tools 28.0.1
    � Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    � Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

M:\Coding\Applications\Google\flutter>
```

Yet there's no crash trying to list devices or create a new app:

```
C:\Users\TESTAC~1\AppData\Local\Temp>m:bin\flutter.bat create test_test_test
Creating project test_test_test...
  test_test_test\.gitignore (created)
  (##snip lots of files##)
  test_test_test\test\widget_test.dart (created)
Wrote 65 files.

Running "flutter packages get" in test_test_test...         11.6s

[v] Flutter is fully installed. (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-GB)
[!] Android toolchain - develop for Android devices is partially installed; more components are available. (Android SDK 28.0.1)
[v] Android Studio is fully installed. (version 3.1)
[!] VS Code, 64-bit edition is partially installed; more components are available. (version 1.24.1)
[!] Connected devices is partially installed; more components are available.

Run "flutter doctor" for information about installing additional components.

All done! In order to run your application, type:

  $ cd test_test_test
  $ flutter run

Your main program file is lib/main.dart in the test_test_test directory.


C:\Users\TESTAC~1\AppData\Local\Temp>
```

Is there anything else you think might influence this? Are you running from CMD or PowerShell? Anything custom? Did you make any other changes than removing the space in the SDK folder to fix it?

**Comment by YannikZ** [comment]
I have the same Problem. I am using a Microsoft Account (Yannik Z...). Can that cause this Problem ?

**Comment by Abderrahmane-H** [comment]
@YannikZ  same problem as yours, using microsoft account.

**Comment by YannikZ12** [comment]
After investigsting a Bit and moving the Android SDK & Flutter SDK to my D:, everything Is Working fine now ...

**Comment by permanar** [comment]
@SherOnDale I have the same issue like yours and realized that my User Profile has a Space on it. Do you have any idea for this problem? Or do I really need to rename my Windows User Profile???

**Comment by SherOnDale** [comment]
@permanar or you could try this

> After investigsting a Bit and moving the Android SDK & Flutter SDK to my D:, everything Is Working fine now ...

**Comment by YannikZ12** [comment]
I think i know the Problem. When u look at your Userfolder, the path look like this: "Users/your profle name". But the real path is something like that: "Users/your'somecharacters'profile'somecharacters'name". I think that Dart can't handle it at the moment. Atm the Solution is to move ure Android and Flutter Sdk to an Save location like: "D:\src".

**Comment by permanar** [comment]
> @permanar or you could try this
> 
> > After investigsting a Bit and moving the Android SDK & Flutter SDK to my D:, everything Is Working fine now ...

Already tried every solution on this page except changing my Windows User Profile. 
Now my Flutter Sdk dir is on D:

**Comment by permanar** [comment]
> I think i know the Problem. When u look at your Userfolder, the path look like this: "Users/your profle name". But the real path is something like that: "Users/your'somecharacters'profile'somecharacters'name". I think that Dart can't handle it at the moment. Atm the Solution is to move ure Android and Flutter Sdk to an Save location like: "D:\src".

I think my Android Sdk is on AppData folder, should I just normally cut/move the folder to my D:? @YannikZ12

**Comment by YannikZ12** [comment]
Did you moved your Android SDK?
Did you updated the Enviromentvariables?
Did you run Flutter Doctor ?

**Comment by YannikZ12** [comment]
Yes, move it to D: some folder, but dont forget do Update ure Enviromentvariables

**Comment by YannikZ12** [comment]
Yes @SherOnDale is right. I just did it to have both together. For some Autim reasons.

**Comment by permanar** [comment]
Alright then I'm gonna try it.
Do I need to move with the Android folder, or just the Sdk?

Thanks for replying me guys.

**Comment by YannikZ12** [comment]
In the Android folder is only the SDK, if u have ure EnviromentVariables right everything is ok. I moved it with the Android folder :)

**Comment by permanar** [comment]
Got it mate. Already do it.
I'm a bit surprised that my Android Sdk is 10GB.

**Comment by DanTup** [comment]
It'd be good to get to the bottom of this but I couldn't repro on my Windows box with a space in my profile foldername. Could someone who can repro possibly try the following code for me?

```
import 'package:process/process.dart';
import 'package:process/process.dart';
import 'dart:io' show ProcessResult;

main() {
  final ProcessManager processManager = new LocalProcessManager();
  final ProcessResult results = processManager.runSync(
    <String>[r'C:\\Path to ADB\\adb.exe', 'devices', '-l'],
  );
  print(results.stdout);
  print(results.stderr);
}
```

You'll need to add:

```yaml
dependencies:
  process:
```

to your pubspec to get the process package. This is just a simplified copy of the code running in the stack at the top of this issue.

**Comment by DanTup** [comment]
@YannikZ12 Unfortunately I've already tried that, my results are at https://github.com/flutter/flutter/issues/18938#issuecomment-402649248

>  Android SDK at C:\Users\Test Account\AppData\Local\Android\sdk

That said, I don't seem to have included the output of `flutter devices` there so now I'm questioning how thorough the testing was. I'll jump on the PC shortly and try again.

**Comment by DanTup** [comment]
Tested again; definitely don't see this here by just having a space in the username:

![flutter devices](https://user-images.githubusercontent.com/1078012/45826679-d2d0c080-bcec-11e8-980f-81dac51fa376.png)
![flutter space issue](https://user-images.githubusercontent.com/1078012/45826680-d2d0c080-bcec-11e8-9de9-b4b098447c57.png)

I'm on Windows 10 Professional, Flutter master, v0.8.7-pre.7.

I'd be interested to know the output of the script I gave above run on by someone who does have this issue.

**Comment by crashless** [comment]
Just adding some other data here - I'm having this issue as well. I am on Win10 Pro .17134.320 en-US. I DO have a space in my username.

Get same behavior both on Beta Channel (0.8.2) and Dev Channel (0.9.6). 

"adb.EXE devices" Does work in as expected when run from windows command line.

I ran the script above and got the following output:
```
Unhandled exception:
Invalid argument(s): Cannot find executable for C:\Path to ADB\adb.exe.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      main (file:///C:/Users/User%20Name/StudioProjects/flutter_app_testing/lib/adb.dart:6:48)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Process finished with exit code 255
```

I also get the error "Error initilizing ADB: Android Debug Bridge not found." When I use the Device File Explorer.

FWIW this is the first time I'm setting up Flutter - I've never had it running on this system.

**Comment by DanTup** [comment]
@crashless Thanks for trying this. In the script above, though you need to replace `Path to ADB` to the actual path to your copy of `adb.exe`. Probably it's something like `C:\\Users\\yourname\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe`.

**Comment by crashless** [comment]
Wow - sorry, missed that one. Here you go - now the output through line #3 is exactly like what I get when I run "flutter doctor". 

```
C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --enable-asserts --enable-vm-service:62156 "C:\Users\Vince Anido\StudioProjects\flutter_app_testing\lib\adb.dart"
Observatory listening on http://127.0.0.1:62156/

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\\Users\\Vince Anido\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      main (file:///C:/Users/User%20Name/StudioProjects/flutter_app_testing/lib/adb.dart:6:48)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Process finished with exit code 255
```

**Comment by DanTup** [comment]
@crashless Thanks! I'm not sure what to make of this :/ Could you try moving the test script to another location (that doesn't have a space in the name) to see whether the space in the running script is having any effect (I suspect not, but it's weird I can't repro on the same version of Windows).

Btw - did you replace anything in that output? In the call stack it has `User%20Name`:

> file:///C:/Users/User%20Name/StudioProjects/flutter_app_testing/lib/adb.dart

But in the command you ran it has another name (if you edited it out, you missed it here - if you didn't edit it out, something really weird has happened!).

**Comment by crashless** [comment]
Whoops - yeah. I replaced "My Name" with "User Name". Kept capitalization of my actual user account. Thanks for catching my missed replacements.

No joy when moving script to another location:

```
C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --enable-asserts --enable-vm-service:64977 C:\flutter_app_testing\lib\adb.dart
Observatory listening on http://127.0.0.1:64977/

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\User Name\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      main (file:///C:/flutter_app_testing/lib/adb.dart:6:48)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Process finished with exit code 255
```

**Comment by crashless** [comment]
OK I finally have things working.  I was only able to get the app to run after BOTH the SDK/NDK and the PROJECT were moved to folder outside my user folder.

The false start happened because I was able to get 'flutter doctor' to give me the thumbs up, and your script worked, but Android Studio failed when trying to start the app.

Once I copied the project to another folder (c:\src\Projects\flutter_app_testing) it finally worked properly.

Error when 'flutter_app_testing' was inside my user folder at c:\Users\User Name\StudioProjects\flutter_app_testing  (same error if virtual device or USB)

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
CreateProcessW failed 193
Finished with error: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\User Name\StudioProjects\flutter_app_testing\android\gradlew.bat -v
```

**Comment by DanTup** [comment]
I'm a bit stumped. No matter what I do, I don't seem to be able to repro. I've tried both with the script being in the user folder and not, and also running with the cwd with and without a space:

![adb](https://user-images.githubusercontent.com/1078012/46719690-78c97800-cc66-11e8-9abd-89503f8b1d98.png)

I'll see if I can find anyone internally that can repro that might be better placed to debug.

**Comment by dnfield** [comment]
Can you share teh output of `echo %ANDROID_HOME%` for someone who sees this failing?  I'm wondering if people who see this fail have an unquoted environment variable whereas those who see it succeed have quotes.

So if it's set to `C:\Users\Some User\...` it might fail, whereas if it's `"C:\Users\Some User\..."` it might not.

**Comment by DanTup** [comment]
@dnfield The last few comments from @crashless above are reproducing the issue with a hard-coded path in a Dart script :-/

**Comment by DanTup** [comment]
@crashless In some of the above comments, `EXE` is written in uppercase. Apparently Windows can do case-sensitive file systems now (https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/). Could you check whether your casing in the test script matches the file on disk?

**Comment by crashless** [comment]
@DanTup I'd love to help out more with this, but now that I've moved my sdk etc and things are working I'm a little reluctant to break them again because it took several hours to get AS to re-install everything. However I'm sure I moved things 'the hard way'. 

Is there an easy way to maintain the SDKs in two locations and switch the system back and forth on which it uses?

**Comment by DanTup** [comment]
@crashless You shouldn't need to mess around with much, just make a copy of your Android `platform-tools` folder (which contains ADB) back in `AppData` and use the simple test script with the hard-coded path from above. Shouldn't affect any of your real projects/SDKs :-)

**Comment by crashless** [comment]
Huh - so this may be interesting (or super not).

Changing the EXE to exe did not work. However when I tried changing the case sensitivity of that folder this happened:

```
PS C:\Windows\system32> fsutil.exe file setCaseSensitiveInfo "C:\Users\User Name\AppData\Local\Android\Sdk\platform-to
ols" enable
Error:  The request is not supported.
PS C:\Windows\system32> fsutil.exe file setCaseSensitiveInfo "C:\Users\User Name\AppData\Local\Android\Sdk\platform-to
ols" disable
Case sensitive attribute on directory C:\Users\User Name\AppData\Local\Android\Sdk\platform-tools is disabled.
PS C:\Windows\system32> fsutil.exe file setCaseSensitiveInfo "C:\Users\User Name\AppData\Local\Android\Sdk\platform-to
ols" enable
Error:  The request is not supported.
```

So there seems to be limitations on this case sensitivity for that folder. I checked the tree using "queryCaseSensitiveInfo" and the entire directory structure all the way back to C:\ was disabled.

**Comment by ChalittaKhampachua** [comment]
Change your user profile name, I solution this issue below link.
https://www.youtube.com/watch?v=J_rTOA4gXJI

I have changed and run project flutter again then found the device.

**Comment by SherOnDale** [comment]
@ChalittaKhampachua that shouldn't be the solution.

**Comment by YannikZ12** [comment]
@GuoYuefei For a temporary Solution you can move your android sdk to a Place like C:\Temp\Android. That should work.

**Comment by SherOnDale** [comment]
@YannikZ12 AFAIK location of Android SDK doesn't matter. You have to move the Flutter SDK to a path without spaces

**Comment by permanar** [comment]
> @GuoYuefei For a temporary Solution you can move your android sdk to a Place like C:\Temp\Android. That should work.

This should work perfectly imo.

**Comment by SherOnDale** [comment]
> 1). Atm, I didn't moved my Android Sdk.
> 2). Yes.
> 3). Already run it several times and got the exact same error. I have upgrade my Flutter version with the latest one, and still nope.
> 
> Yes, I think I should change some configuration at Environment Variables, but which one should change?

**Comment by SherOnDale** [comment]
Yeah, sorry. got confused. 

> @permanar if you have the same error as mine, you have to move the Android SDK, not the flutter SDK. Since i have my flutter SDK in the root of C: and it's not affected by the Windows User Profile name.

**Comment by GuoYuefei** [comment]
> There are spaces in my username, but it can be executed normally at first. Now I don't know what's going on and it doesn't work properly.
----
I found that my problem was that the virtual machine didn't use the Android image recommended by Google.When I used the system image recommended by Google, the problem was solved.
Give 66666666666

**Comment by HackrHIVE** [comment]
> Yes, That path is correct and it got only fixed only after I removed the space from the User Profile name. Windows 10 BTW. And Flutter 0.5.1

How did u change user profile name?
Help me out here.

**Comment by epebojot** [comment]
I know the solution about this, just copy or move any file related to your android sdk or flutter sdk to a name without space, after, change the user variable, then open flutter_console.bat
You should not see this:

c:/users/My Name With Space

instead a name without space...

**Comment by epebojot** [comment]
> I know the solution about this, just copy or move any file related to your android sdk or flutter sdk to a name without space, after, change the user variable, then open flutter_console.bat
> You should not see this:
> 
> c:/users/My Name With Space
> 
> instead a name without space...

Change the user varible including the path

**Comment by epebojot** [comment]
> > I think i know the Problem. When u look at your Userfolder, the path look like this: "Users/your profle name". But the real path is something like that: "Users/your'somecharacters'profile'somecharacters'name". I think that Dart can't handle it at the moment. Atm the Solution is to move ure Android and Flutter Sdk to an Save location like: "D:\src".
> 
> I think my Android Sdk is on AppData folder, should I just normally cut/move the folder to my D:? @YannikZ12

Working. Actually most of guys gives a lot of solution, but the main topic is about the android sdk inside appData
