### ISSUE TITLE
"Enable Repaint Rainbow" debug feature broken

### ISSUE THREAD

**Issue by slightfoot** [flutter/flutter#18971]
## Steps to Reproduce

**In IDE**
1. Open app in Intellij.
2. Click cog icon in Flutter Inspector panel
3. Check Enable Repaint Rainbow.

**In App**
1. Perform 3-4 route changes.
2. Exception is thrown.

## Logs

**Exception**
```
I/flutter ( 9023): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9023): The following assertion was thrown during a scheduler callback:
I/flutter ( 9023): 'package:flutter/src/painting/colors.dart': Failed assertion: line 99 pos 16: 'hue <= 360.0': is not
I/flutter ( 9023): true.
I/flutter ( 9023): 
I/flutter ( 9023): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9023): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9023): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9023):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9023): 
I/flutter ( 9023): When the exception was thrown, this was the stack:
I/flutter ( 9023): #2      new HSVColor.fromAHSV (package:flutter/src/painting/colors.dart)
I/flutter ( 9023): #3      HSVColor.withHue (package:flutter/src/painting/colors.dart:156:16)
I/flutter ( 9023): #4      RenderView.compositeFrame.<anonymous closure> (package:flutter/src/rendering/view.dart:203:63)
I/flutter ( 9023): #5      RenderView.compositeFrame (package:flutter/src/rendering/view.dart:205:8)
I/flutter ( 9023): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:273:16)
I/flutter ( 9023): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 9023): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9023): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9023): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9023): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9023): #12     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 9023): #13     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 9023): (elided 2 frames from class _AssertionError)
I/flutter ( 9023): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**flutter doctor -v**
```
[√] Flutter (Channel master, v0.5.6-pre.76, on Microsoft Windows [Version 10.0.17134.112], locale en-GB)
    • Flutter version 0.5.6-pre.76 at C:\Android\flutter
    • Framework revision 579116412f (4 days ago), 2018-06-26 12:18:50 +0200
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Android\Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Users\Simon\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.4892.42
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[√] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[√] Connected devices (1 available)
    • Google Nexus 5X, 8 0, API 26, 1080x1920 • 192.168.188.101:5555 • android-x86 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by zoechi** [comment]
Did it work for you before?

**Comment by slightfoot** [comment]
Never used it before.

I believe the fix is straight-forward. Add modulus 360 to https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/view.dart#L203
