### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by sahil311289** [flutter/flutter#18979]
```Performing hot restart...
Restarted app in 2,687ms.
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_DOWN
I/flutter (20672): _MyAppState.activateSpeechRecognizer... 
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_UP
D/SpeechRecognitionPlugin(20672): Current Locale : en_GB
I/flutter (20672): _platformCallHandler call speech.onCurrentLocale en_GB
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_UP
I/flutter (20672): Dislike
I/flutter (20672): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (20672): The following assertion was thrown while handling a gesture:
I/flutter (20672): type 'List<dynamic>' is not a subtype of type 'List<String>'
I/flutter (20672): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20672): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20672): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20672):   https://github.com/flutter/flutter/issues/new
I/flutter (20672): When the exception was thrown, this was the stack:
I/flutter (20672): #0      _ChatListTileItemState.build.<anonymous closure> (file:///Users/sahil/IdeaProjects/gabhub_anonym_text/lib/live_chat_tab_base.dart:429:85)
I/flutter (20672): #1      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (20672): #2      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (20672): #3      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (20672): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (20672): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (20672): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (20672): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (20672): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (20672): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (20672): #10     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (20672): #11     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (20672): Handler: onTap
I/flutter (20672): Recognizer:
I/flutter (20672):   TapGestureRecognizer#cf6d7(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (20672):   Offset(125.9, 380.8), sent tap down)
I/flutter (20672): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20672): ViewRoot's Touch Event : ACTION_UP

**Comment by sahil311289** [comment]
```Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by sahil311289** [comment]
Assigning a List type to an actual List gives an exception.
```Error caught by gesture, thrown while handling a gesture.
type 'List<dynamic>' is not a subtype of type 'List<String>'
Handler:

**Comment by jonahwilliams** [comment]
@sahil311289 this looks like a type error in your code, maybe see [sound dart](https://www.dartlang.org/guides/language/sound-dart). 

For example, you might be doing something like this:

```dart
List xs = ["asd", "dss"]; // list<dynamic>
taksesAListOfStrings(xs); // error List<dynamic> is not a subtype of List<String>
```

**Comment by sahil311289** [comment]
This is what I'm trying to do:
```
print('Like');
update(widget.document.reference, LiveChat.fromMap(widget.document.data).like, 'sahil');
```
In LiveChat class, I'm trying to encode/decode:
```
import 'dart:collection';

class LiveChat {
  String message;
  DateTime timestamp;
  String university;
  String email;
  dynamic like = new List<String>();
  dynamic dislike = new List<String>();
  dynamic laugh = new List<String>();
  dynamic cry = new List<String>();
  dynamic angry = new List<String>();

  LiveChat(this.message, this.timestamp, this.university, this.email, this.like,
      this.dislike, this.laugh, this.cry, this.angry);

  LiveChat.fromMap(Map<String, dynamic> data) {
    this.message = data['message'];
    this.timestamp = data['timestamp'];
    this.university = data['university'];
    this.email = data['email'];
    this.like = data['like'];
    this.dislike = data['dislike'];
    this.laugh = data['laugh'];
    this.cry = data['cry'];
    this.angry = data['angry'];
  }

  Map<String, dynamic> toMap() => {
        'message': this.message,
        'timestamp': this.timestamp,
        'university': this.university,
        'email': this.email,
        'like': this.like,
        'dislike': this.dislike,
        'laugh': this.laugh,
        'cry': this.cry,
        'angry': this.angry
      };
}
```
Even though data['like'] is of type _List, it gives an exception if I initialize 'like' like the following:
```
List<String> like = new List<String>();
```
Initializing the list as dynamic doesn't give exception. But adding to it at a later point surely gives one.
```
Future<bool> update(DocumentReference reference, dynamic likes, String s) async {
    final TransactionHandler updateTransaction = (Transaction transaction) async {

      final DocumentSnapshot freshSnap = await transaction.get(reference);
      Map<String, dynamic> data = new Map();
      likes.add('sahil');   // Exception here

      data.putIfAbsent('like', () => likes);
      await freshSnap.reference.setData(data, merge: true);
      return {'result': true};
    };
    return Firestore.instance.runTransaction(updateTransaction).then((r) => r['result']).catchError((e) {
      print('GabHub dart error: $e');
      return false;
    });
  }
```
I'm trying to add to an existing list but it fails.

**Comment by jonahwilliams** [comment]
The problem is your `fromMap` constructor is reading from a `Map<String, dynamic>`, so I bet that all of the lists in that map are actually `List<dynamic>` or just `dynamic`. Try doing this instead:

```
List<String> likes;

LiveChat.fromMap(Map<String, dynamic> data) {
  likes = data['likes'].cast<String>();
}

```

**Comment by sahil311289** [comment]
That fixed the type casting error.
Here's another one:
```Future<bool> update(DocumentReference reference, List<String> likes, String s) async {
    final TransactionHandler updateTransaction = (Transaction transaction) async {

      final DocumentSnapshot freshSnap = await transaction.get(reference);
      Map<String, List<String>> data = new Map();
      likes.add(s);        // Exception

      data.putIfAbsent('like', () => likes);
      await freshSnap.reference.setData(data, merge: true);
      return {'result': true};
    };
    return Firestore.instance.runTransaction(updateTransaction).then((r) => r['result']).catchError((e) {
      print('GabHub dart error: $e');
      return false;
    });
  }
```

**Comment by jonahwilliams** [comment]
What is the exception there?

**Comment by sahil311289** [comment]
![screen shot 2018-07-01 at 12 07 30 pm](https://user-images.githubusercontent.com/1798083/42137782-64f506ca-7d27-11e8-9b65-a69ff77f012a.png)

**Comment by jonahwilliams** [comment]
Possibly related to https://github.com/flutter/flutter/issues/17663?

**Comment by sahil311289** [comment]
I had that same issue. Got it resolved by playing aorund with data.
The followong works perfectly fine:
```
Future<bool> update(DocumentReference reference, List<String> likes, String s) async {
    final TransactionHandler updateTransaction = (Transaction transaction) async {

      final DocumentSnapshot freshSnap = await transaction.get(reference);
      Map<String, List<String>> data = new Map();
//      likes.add(s);        // Exception

      List<String> names = new List<String>();
      names.add('Sahil');
      names.add('Jonahwilliams');

      data.putIfAbsent('like', () => names);
      await freshSnap.reference.setData(data, merge: true);
      return {'result': true};
    };
    return Firestore.instance.runTransaction(updateTransaction).then((r) => r['result']).catchError((e) {
      print('GabHub dart error: $e');
      return false;
    });
  }
```

But as soon as you introduce Firebase data, it starts giving issues.

**Comment by sahil311289** [comment]
![screen shot 2018-07-01 at 12 19 30 pm](https://user-images.githubusercontent.com/1798083/42137890-0e58ab1c-7d29-11e8-8722-c894be8ca7dd.png)

Please notice the difference in the structures of 'likes' and 'names'. perhaps casting is not the best option.

**Comment by sahil311289** [comment]
```
Future<bool> update(DocumentReference reference, dynamic likes, String s) async {
    final TransactionHandler updateTransaction = (Transaction transaction) async {

      final DocumentSnapshot freshSnap = await transaction.get(reference);
      Map<String, List<String>> data = new Map();

      String likesListString = likes.toString();
      likesListString = likesListString.substring(1, likesListString.length-1);
      List<String> likeList = likesListString.split(", ");

      data.putIfAbsent('like', () => likeList);
      await freshSnap.reference.setData(data, merge: true);
      return {'result': true};
    };
    return Firestore.instance.runTransaction(updateTransaction).then((r) => r['result']).catchError((e) {
      print('GabHub dart error: $e');
      return false;
    });
  }
```
I presumed this would work since I'm making use of pure List<String> type. Guess what? I was wrong. @jonahwilliams: You were right. This is not a type casting issue alone. Here's the result:
```
Performing hot reload...
Reloaded 3 of 515 libraries in 1,964ms.
I/ViewRootImpl(16691): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(16691): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(16691): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(16691): ViewRoot's Touch Event : ACTION_UP
I/flutter (16691): Like
E/flutter (16691): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (16691): type 'Future<dynamic>' is not a subtype of type 'FutureOr<bool>'
E/flutter (16691): #0      _ChatListTileItemState.update (file:///Users/sahil/IdeaProjects/gabhub_anonym_text/lib/live_chat_tab_base.dart:557:90)
E/flutter (16691): <asynchronous suspension>
E/flutter (16691): #1      _ChatListTileItemState.build.<anonymous closure> (file:///Users/sahil/IdeaProjects/gabhub_anonym_text/lib/live_chat_tab_base.dart:429:31)
E/flutter (16691): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (16691): #3      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (16691): #4      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (16691): #5      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (16691): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (16691): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (16691): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (16691): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (16691): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (16691): #11     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (16691): #12     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): java.lang.IllegalStateException: Task is already complete
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.google.android.gms.tasks.zzu.zzdr(Unknown Source)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.google.android.gms.tasks.zzu.setResult(Unknown Source)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3$1.success(CloudFirestorePlugin.java:283)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:169)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at io.flutter.view.FlutterNativeView.handlePlatformMessageResponse(FlutterNativeView.java:187)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at android.app.ActivityThread.main(ActivityThread.java:5349)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
E/MethodChannel#plugins.flutter.io/cloud_firestore(16691): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by jonahwilliams** [comment]
`runTransaction` probably returns a `Future<dynamic>`, so you would need to update your code to actually return a `Future<bool>`. 

```dart
Future<bool> update(DocumentReference reference, dynamic likes, String s) async {
  /* */
  try {
    final result = await Firestore.instance.runTransaction(updateTransaction);
    return true;
  }  catch (err) {
     return false;
  }
}

```

**Comment by unibeck** [comment]
I did what @jonahwilliams suggested with the `cast<Type>()` and it was working nicely for a while. Though I encountered an error where if the value for the key in the map was null (e.g. not found) and threw the following error:
```
I/flutter (17982): The method 'cast' was called on null.
I/flutter (17982): Receiver: null
I/flutter (17982): Tried calling: cast<DocumentReference>()
```
with the following code
```
Object.fromMap(Map<String, dynamic> map, {this.reference})
    : readBy = map['readBy'].cast<DocumentReference>();
```

----

To fix this you can make an ugly inline null check:
```
readBy = (map['readBy'] != null) ? map['readBy'].cast<DocumentReference>() : null
``` 
**But** the cleaner and more Dart*ful* way of accomplishing this is with the null-aware `?.` operator:
```
readBy = map['readBy']?.cast<DocumentReference>()
```
Leaving this slight improvement here encase anyone else comes across this issue.

**Comment by vivekanandasuggu** [comment]
My model class is like this

`import 'dart:convert';

List<ServiceLogsModel> serviceLogsModelFromJson(String str) => new List<ServiceLogsModel>.from(json.decode(str).map((x) => ServiceLogsModel.fromJson(x)));

String serviceLogsModelToJson(List<ServiceLogsModel> data) => json.encode(new List<dynamic>.from(data.map((x) => x.toJson())));

class ServiceLogsModel {
  String vitCasenumber;
  String title;
  DateTime createdon;
  DateTime modifiedon;
  String statuscodeODataCommunityDisplayV1FormattedValue;
  int statecode;
  String incidentid;
  bool vitIsfilemandatory;
  String customeridContact;
  String vitFilesuploadedtosharepoint;
  String vitJsondata;
  int vitTypeofform;
  bool vitReadstatus;

  ServiceLogsModel({
    this.vitCasenumber,
    this.title,
    this.createdon,
    this.modifiedon,
    this.statuscodeODataCommunityDisplayV1FormattedValue,
    this.statecode,
    this.incidentid,
    this.vitIsfilemandatory,
    this.customeridContact,
    this.vitFilesuploadedtosharepoint,
    this.vitJsondata,
    this.vitTypeofform,
    this.vitReadstatus,
  });

  factory ServiceLogsModel.fromJson(Map<String, dynamic> json) => new ServiceLogsModel(
    vitCasenumber: json["vit_casenumber"],
    title: json["title"],
    createdon: DateTime.parse(json["createdon"]),
    modifiedon: DateTime.parse(json["modifiedon"]),
    statuscodeODataCommunityDisplayV1FormattedValue: json["statuscode@OData.Community.Display.V1.FormattedValue"],
    statecode: json["statecode"],
    incidentid: json["incidentid"],
    vitIsfilemandatory: json["vit_isfilemandatory"],
    customeridContact: json["customerid_contact"],
    vitFilesuploadedtosharepoint: json["vit_filesuploadedtosharepoint"],
    vitJsondata: json["vit_jsondata"],
    vitTypeofform: json["vit_typeofform"],
    vitReadstatus: json["vit_readstatus"],
  );

  Map<String, dynamic> toJson() => {
    "vit_casenumber": vitCasenumber,
    "title": title,
    "createdon": createdon.toIso8601String(),
    "modifiedon": modifiedon.toIso8601String(),
    "statuscode@OData.Community.Display.V1.FormattedValue": statuscodeODataCommunityDisplayV1FormattedValue,
    "statecode": statecode,
    "incidentid": incidentid,
    "vit_isfilemandatory": vitIsfilemandatory,
    "customerid_contact": customeridContact,
    "vit_filesuploadedtosharepoint": vitFilesuploadedtosharepoint,
    "vit_jsondata": vitJsondata,
    "vit_typeofform": vitTypeofform,
    "vit_readstatus": vitReadstatus,
  };
}
`
I am getting the response like this

[
    {
        "vit_casenumber": "CM1902849",
        "title": "Request For Reference Letter",
        "createdon": "2019-06-27T04:43:44Z",
        "modifiedon": "2019-06-27T04:54:03Z",
        "statuscode@OData.Community.Display.V1.FormattedValue": "New",
        "statecode": 0,
        "incidentid": "e7d38720-9698-e911-a855-000d3ae0a7f8",
        "vit_isfilemandatory": false,
        "customerid_contact": null,
        "vit_filesuploadedtosharepoint": null,
        "vit_jsondata": null,
        "vit_typeofform": 2,
        "vit_readstatus": true
    },
    {
        "vit_casenumber": "CM1902848",
        "title": "Request For Reference Letter",
        "createdon": "2019-06-26T12:53:13Z",
        "modifiedon": "2019-06-26T12:53:17Z",
        "statuscode@OData.Community.Display.V1.FormattedValue": "New",
        "statecode": 0,
        "incidentid": "681bb658-1198-e911-a852-000d3ae0b82e",
        "vit_isfilemandatory": false,
        "customerid_contact": null,
        "vit_filesuploadedtosharepoint": null,
        "vit_jsondata": null,
        "vit_typeofform": 2,
        "vit_readstatus": false
    }
]

when I am executing this line 

   json.decode(response.body);

I am getting this error 
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'String'

Please help me to sort out the problem

**Comment by akarabach** [comment]
Faced with the same problem, and I pretty sure that code is fine. Why did we close this one ?

**Comment by joao-rafael** [comment]
Got the same issue while trying to pass a list to the _items_ property of the DorpdownMenu widget.

**Comment by patelkrunal78** [comment]
The problem here is that type inference fails in an unexpected way. The solution is to provide a type argument to the map method.

Find You Solution at [Here](https://icetutor.com/question/type-list-is-not-a-subtype-of-type-list)

**Comment by patelkeval78** [comment]
(I assume you’re using a Row because you want to put other widgets beside the TextField in the future.)

The Row widget wants to determine the intrinsic size of its non-flexible children so it knows how much space that it has left for the flexible ones. However, TextField doesn’t have an intrinsic width; it only knows how to size itself to the full width of its parent container. Try wrapping it in a Flexible or Expanded to tell the Row that you’re expecting the TextField to take up the remaining space:

new Row(
children: <Widget>[
new Flexible(
child: new TextField(
decoration: const InputDecoration(helperText: "Enter App ID"),
style: Theme.of(context).textTheme.body1,
),
),
],
),

Find Source With Example [Here](https://icetutor.com/question/textfield-inside-of-row-causes-layout-exception-unable-to-calculate-size/)

**Comment by Ashbuhrz** [comment]
> The problem is your `fromMap` constructor is reading from a `Map<String, dynamic>`, so I bet that all of the lists in that map are actually `List<dynamic>` or just `dynamic`. Try doing this instead:
> 
> ```
> List<String> likes;
> 
> LiveChat.fromMap(Map<String, dynamic> data) {
>   likes = data['likes'].cast<String>();
> }
> ```

   body: Container(
        child: Center(
          child: FutureBuilder(
            future:
                DefaultAssetBundle.of(context).loadString('jsons/data.json'),
            builder: (context, snapshot) {
              if (!snapshot.hasData) {
                return CircularProgressIndicator();
              }
              var myData = jsonDecode(snapshot.data);
              final welcome = welcomeFromJson(myData);

              print(myData.length);
              return ListView.builder(
                itemBuilder: (BuildContext context, int index) {
                  return Card(
                      child: ListTile(
                    title: Text(welcome[index]
                        .tableMenuList[index]
                        .categoryDishes[index]
                        .dishName),
                  ));
                },
                itemCount: myData == null ? 0 : myData.length,
              );
            },
          ),
        ),
      ),

error : type 'List<dynamic>' is not a subtype of type 'String'

**Comment by mohit-solankee99** [comment]
@Ashbuhrz You should add mydata in List
with following code

List data;

var myData = jsonDecode(snapshot.data);
data=mydata['];

and item count will be

itemCount: myData == null ? 0 : myData.length,

**Comment by mohit-solankee99** [comment]
You should pass mydata to List 

List data;

 var myData = jsonDecode(snapshot.data);
data=mydata[''];

and your itemcount will be


itemCount: data == null ? 0 : data.length,

**Comment by Viki04** [comment]
ceci brate

**Comment by mamedshahmaliyev** [comment]
just use: (yourlist as List<dynamic>).map((e) => e.toString()).toList();

**Comment by ella97** [comment]
class Product {
  int id;
  String name;
  String photo;
  int price;
  int discount;
  String productDetail;
  int quantity;

  toMap() {
    var map = Map<String, dynamic>();
    map['productId'] = id;
    map['productName'] = name;
    map['productPhoto'] = photo;
    map['productPrice'] = price;
    map['productDiscount'] = discount;
    map['productQuantity'] = quantity;
    return map;
  }

  
}


type 'List<dynamic>' is not a subtype of type 'List<String>' please help

**Comment by fluttercorner1** [comment]
all possible solution added Here [[Solved] type ‘List‘ is not a subtype of type ‘List‘ in Flutter
](https://fluttercorner.com/solved-type-list-is-not-a-subtype-of-type-list-in-flutter/)

**Comment by Santosh1432** [comment]
> ### My model class is like this
> `import 'dart:convert';
> 
> List serviceLogsModelFromJson(String str) => new List.from(json.decode(str).map((x) => ServiceLogsModel.fromJson(x)));
> 
> String serviceLogsModelToJson(List data) => json.encode(new List.from(data.map((x) => x.toJson())));
> 
> class ServiceLogsModel {
> String vitCasenumber;
> String title;
> DateTime createdon;
> DateTime modifiedon;
> String statuscodeODataCommunityDisplayV1FormattedValue;
> int statecode;
> String incidentid;
> bool vitIsfilemandatory;
> String customeridContact;
> String vitFilesuploadedtosharepoint;
> String vitJsondata;
> int vitTypeofform;
> bool vitReadstatus;
> 
> ServiceLogsModel({
> this.vitCasenumber,
> this.title,
> this.createdon,
> this.modifiedon,
> this.statuscodeODataCommunityDisplayV1FormattedValue,
> this.statecode,
> this.incidentid,
> this.vitIsfilemandatory,
> this.customeridContact,
> this.vitFilesuploadedtosharepoint,
> this.vitJsondata,
> this.vitTypeofform,
> this.vitReadstatus,
> });
> 
> factory ServiceLogsModel.fromJson(Map<String, dynamic> json) => new ServiceLogsModel(
> vitCasenumber: json["vit_casenumber"],
> title: json["title"],
> createdon: DateTime.parse(json["createdon"]),
> modifiedon: DateTime.parse(json["modifiedon"]),
> statuscodeODataCommunityDisplayV1FormattedValue: json["[statuscode@OData.Community.Display.V1.FormattedValue](mailto:statuscode@OData.Community.Display.V1.FormattedValue)"],
> statecode: json["statecode"],
> incidentid: json["incidentid"],
> vitIsfilemandatory: json["vit_isfilemandatory"],
> customeridContact: json["customerid_contact"],
> vitFilesuploadedtosharepoint: json["vit_filesuploadedtosharepoint"],
> vitJsondata: json["vit_jsondata"],
> vitTypeofform: json["vit_typeofform"],
> vitReadstatus: json["vit_readstatus"],
> );
> 
> Map<String, dynamic> toJson() => {
> "vit_casenumber": vitCasenumber,
> "title": title,
> "createdon": createdon.toIso8601String(),
> "modifiedon": modifiedon.toIso8601String(),
> "[statuscode@OData.Community.Display.V1.FormattedValue](mailto:statuscode@OData.Community.Display.V1.FormattedValue)": statuscodeODataCommunityDisplayV1FormattedValue,
> "statecode": statecode,
> "incidentid": incidentid,
> "vit_isfilemandatory": vitIsfilemandatory,
> "customerid_contact": customeridContact,
> "vit_filesuploadedtosharepoint": vitFilesuploadedtosharepoint,
> "vit_jsondata": vitJsondata,
> "vit_typeofform": vitTypeofform,
> "vit_readstatus": vitReadstatus,
> };
> }
> `
> 
> ### I am getting the response like this
> [
> {
> "vit_casenumber": "CM1902849",
> "title": "Request For Reference Letter",
> "createdon": "2019-06-27T04:43:44Z",
> "modifiedon": "2019-06-27T04:54:03Z",
> "[statuscode@OData.Community.Display.V1.FormattedValue](mailto:statuscode@OData.Community.Display.V1.FormattedValue)": "New",
> "statecode": 0,
> "incidentid": "e7d38720-9698-e911-a855-000d3ae0a7f8",
> "vit_isfilemandatory": false,
> "customerid_contact": null,
> "vit_filesuploadedtosharepoint": null,
> "vit_jsondata": null,
> "vit_typeofform": 2,
> "vit_readstatus": true
> },
> {
> "vit_casenumber": "CM1902848",
> "title": "Request For Reference Letter",
> "createdon": "2019-06-26T12:53:13Z",
> "modifiedon": "2019-06-26T12:53:17Z",
> "[statuscode@OData.Community.Display.V1.FormattedValue](mailto:statuscode@OData.Community.Display.V1.FormattedValue)": "New",
> "statecode": 0,
> "incidentid": "681bb658-1198-e911-a852-000d3ae0b82e",
> "vit_isfilemandatory": false,
> "customerid_contact": null,
> "vit_filesuploadedtosharepoint": null,
> "vit_jsondata": null,
> "vit_typeofform": 2,
> "vit_readstatus": false
> }
> ]
> 
> ### when I am executing this line
> json.decode(response.body);
> 
> ### I am getting this error
> Unhandled Exception: type 'List' is not a subtype of type 'String'
> 
> ### Please help me to sort out the problem

Hi Vivek, Can u Please send the solution for this Error

**Comment by exeptionerror** [comment]
all possible solution added[ [Solved] Error type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'](https://fluttercorner.com/error-listdynamic-is-not-a-subtype-of-type-mapstring-dynamic/)
