### ISSUE TITLE
Can't display Gifs from Giphy

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#18975]
Cannot display Giphy Gifs. I receive the following error: [ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter (28186): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter (28186): The following _Exception was thrown resolving an image codec:
I/flutter (28186): Exception: operation failed
I/flutter (28186): 
I/flutter (28186): When the exception was thrown, this was the stack:
I/flutter (28186): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:452:12)
I/flutter (28186): <asynchronous suspension>
I/flutter (28186): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:425:14)
I/flutter (28186): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
I/flutter (28186): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
I/flutter (28186): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
I/flutter (28186): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (28186): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:263:30)
I/flutter (28186): #7      _ImageProviderResolver.resolve (package:flutter/src/widgets/fade_in_image.dart:332:29)
I/flutter (28186): #8      _FadeInImageState._resolveImage (package:flutter/src/widgets/fade_in_image.dart:407:20)
I/flutter (28186): #9      _FadeInImageState.didChangeDependencies (package:flutter/src/widgets/fade_in_image.dart:389:5)
I/flutter (28186): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3767:12)
I/flutter (28186): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (28186): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (28186): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (28186): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #80     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (28186): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #93     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter (28186): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (28186): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (28186): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (28186): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (28186): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (28186): #103    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter (28186): #104    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
I/flutter (28186): #105    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter (28186): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #109    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #113    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter (28186): #114    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (28186): #115    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter (28186): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #119    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #131    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (28186): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #155    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #159    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (28186): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #167    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #169    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter (28186): #170    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (28186): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #174    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #177    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #178    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #182    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #187    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #188    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (28186): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (28186): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #194    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #198    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #201    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #202    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #206    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (28186): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #210    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (28186): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (28186): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (28186): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28186): #214    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (28186): #215    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (28186): #216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (28186): #217    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (28186): #218    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (28186): #219    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (28186): #220    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (28186): #221    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (28186): 
I/flutter (28186): Image provider: NetworkImage("https://giphy.com/gifs/musicchoice-reaction-happy-EOmQixWgSLCDHprXOQ",
I/flutter (28186): scale: 1.0)
I/flutter (28186): Image key: NetworkImage("https://giphy.com/gifs/musicchoice-reaction-happy-EOmQixWgSLCDHprXOQ",
I/flutter (28186): scale: 1.0)
I/flutter (28186): ════════════════════════════════════════════════════════════════════════════════════════════════════

My code is `new FadeInImage.memoryNetwork(placeholder: kTransparentImage, image: _gifList[index].url, fit: BoxFit.cover,),`

**Comment by rlee1990** [comment]
Closing issue was with the urls coming from the library.
