### ISSUE TITLE
Problem with state restoration of multiple navigation stacks inside a `BottomNavigationBar`

### ISSUE THREAD

**Issue by bizz84** [flutter/flutter#18980]
## Steps to Reproduce

Source code here:
https://gist.github.com/bizz84/d9cdea03f3255cac6ed4348fed9efe0b

I have also open sourced this example here in case contributors want to suggest a fix / open a PR: https://github.com/bizz84/nested-navigation-demo-flutter

This sample app shows how to use separate navigators for each tab in a [BottomNavigationBar](https://docs.flutter.io/flutter/material/BottomNavigationBar-class.html).

#### Preview 

![green-root](https://user-images.githubusercontent.com/153167/42138498-6cac3b64-7d76-11e8-90d3-667fac95d0cb.png)

![green-detail](https://user-images.githubusercontent.com/153167/42138501-70017a0e-7d76-11e8-98f1-96f33c44d50c.png)

## Problem statement

**Enable state restoration of multiple navigation stacks inside a `BottomNavigationBar`. This is a common use case for a lot of apps.**

## Context

* Pushing a new [MaterialPageRoute](https://docs.flutter.io/flutter/material/MaterialPageRoute-class.html) from within a `BottomNavigationBar` causes the whole screen to be pushed out with the new page.
* This is hardly desirable: most apps using a bottom navigation bar have a separate navigation stack for each tab (e.g. the YouTube app). The bottom navigation bar stays in place when performing push navigation within a tab.
* This can be done in Flutter by using a `MaterialApp` as the `body` of the `BottomNavigationBar`, and configuring it with a separate global `navigationKey` for each tab.
* This solves only half of the problem though, as the navigation state is lost when switching tabs.
* Some state restoration logic alleviates this problem by keeping track of the desired `initialRoute` for each tab as routes are pushed and popped.
* In order to reliably track this, it should be possible to register a `NavigatorObserver` when creating the `MaterialApp`, and override the `didPush` / `didPop` methods to keep track of state.
* Unfortunately, registering a `NavigatorObserver` causes an exception when switching tabs:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building DefaultTextStyle(debugLabel: fallback style; consider
flutter: putting your text in a Material, inherit: true, color: Color(0xd0ff0000), family: monospace, size:
flutter: 48.0, weight: 900, decoration: double Color(0xffffff00) TextDecoration.underline, softWrap: wrapping
flutter: at box width, overflow: clip):
flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1209 pos 14:
flutter: 'observer.navigator == null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
```

Debugging this reveals that the `observer.navigator` is an instance of `HeroController`.

#### Reproduction steps

1. Run the app
2. Tap on the `green` or `blue` tab at the bottom.
3. Exception: `'observer.navigator == null': is not true.`

#### WidgetsApp

Further investigation reveals that with some tweaks it may be possible to use [WidgetsApp](https://docs.flutter.io/flutter/widgets/WidgetsApp-class.html) instead of `MaterialApp` (`WidgetsApp` doesn't have a `HeroController`), but it seems dubious that this is the way to go. In any case, when trying to push a route with `WidgetsApp` I encounter another exception:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building BackButton(dirty):
flutter: The getter 'backButtonTooltip' was called on null.
flutter: Receiver: null
flutter: Tried calling: backButtonTooltip
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
flutter: #1      BackButton.build (package:flutter/src/material/back_button.dart:87:50)
```

## Summary / Questions

* How to keep track of the navigation state of multiple Navigators within a `BottomNavigationBar`?
* Is there an alternative to `BottomNavigationBar`, which allows to use multiple navigation stacks and preserve their state?

## Logs

[main.log](https://github.com/flutter/flutter/files/2153169/main.log)

```
Analyzing nested_navigation_demo_flutter...                      
No issues found! (ran in 1.9s)

```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.3 17D47, locale en-GB)
    • Flutter version 0.5.1 at /Users/andrea/dev/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/andrea/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (3 available)
    • Andrea iPhone 6 • d55e78eee17b7004891adf317eda2e03f756f81c • ios • iOS 11.4
    • iPhone 8        • 80B2AA7F-7D83-4747-9DC1-8A43DB29EE28     • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-3 (simulator)
    • iPhone X        • 26A68A3D-8AF8-4D8B-B685-2F95BD0988C2     • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-3 (simulator)

! Doctor found issues in 1 category.

```

**Comment by bizz84** [comment]
@mravn-google 👆

**Comment by bizz84** [comment]
I have came up a solution that works. 

This involves using multiple `Navigators`, an a `Stack` with `Offstage` widgets to ensure all `Navigators` are preserved, while only one is visible at any given time.

I have updated my repo with the working solution:

https://github.com/bizz84/nested-navigation-demo-flutter

So, I'm closing this issue.
