### ISSUE TITLE
FirebaseMessaging: Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by eharango** [flutter/flutter#19004]
## Steps to Reproduce

Hi Guys,
I'm using `firebase_messaging: 1.0.3` I'm seeing this problem on android, the information that is sent from firebase is the following

```json
{
  "notification": {
    "title": "title test1",
    "body": "body message"
  },
  "data": {
    "click_action": "FLUTTER_NOTIFICATION_CLICK"
  }
}
```
## Logs

```
W/FirebaseMessaging( 6923): Error while parsing timestamp in GCM event
W/FirebaseMessaging( 6923): java.lang.NumberFormatException: s == null
W/FirebaseMessaging( 6923): 	at java.lang.Integer.parseInt(Integer.java:577)
W/FirebaseMessaging( 6923): 	at java.lang.Integer.parseInt(Integer.java:650)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.zzb.zzb(Unknown Source:90)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.zzb.zzc(Unknown Source:3)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:348)
W/FirebaseMessaging( 6923): 	at com.google.firebase.iid.zzg.run(Unknown Source:29)
W/FirebaseMessaging( 6923): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseMessaging( 6923): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseMessaging( 6923): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
W/FirebaseMessaging( 6923): 	at java.lang.Thread.run(Thread.java:764)
W/FirebaseMessaging( 6923): Error while parsing timestamp in GCM event
W/FirebaseMessaging( 6923): java.lang.NumberFormatException: s == null
W/FirebaseMessaging( 6923): 	at java.lang.Integer.parseInt(Integer.java:577)
W/FirebaseMessaging( 6923): 	at java.lang.Integer.parseInt(Integer.java:650)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.zzb.zzb(Unknown Source:90)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.zzb.zzf(Unknown Source:3)
W/FirebaseMessaging( 6923): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:390)
W/FirebaseMessaging( 6923): 	at com.google.firebase.iid.zzg.run(Unknown Source:29)
W/FirebaseMessaging( 6923): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseMessaging( 6923): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseMessaging( 6923): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
W/FirebaseMessaging( 6923): 	at java.lang.Thread.run(Thread.java:764)


```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale es_PE.UTF-8)
    • Flutter version 0.5.1 at /home/ed/flutter
    • Framework revision c7ea3ca377 (hace 5 semanas), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/ed/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by shinyford** [comment]
FWIW I'm seeing this problem too. However, I've had to lower my firebase-core version to 15, to get over a missing function problem (`zzc`?) which happened when using 16.0.0.

**Comment by MarioClot** [comment]
Try to remove the click_action.

**Comment by lidroider** [comment]
I have same issues 
@MarioClot 
I removed click_action but it don't effect
```
"notification": {
    "title": "title",
    "body": "body",
    "android_channel_id": "thuyloicuchi_android_channel",
    "color": "#ff0000"
  }
```

**Comment by yauri-io** [comment]
I have the same issue, the notification sent from Firebase-Admin NodeJS package

**Comment by KorexDevelopment** [comment]
Ive the same error. Have anyone found a solution?

**Comment by lanchana** [comment]
+1

**Comment by zloyreznic** [comment]
{"data":{"action":"zzz"},"android":{"notification":{"icon":"ic_launcher","color":"#1b77d2","title":"n.title","body":"n.body","clickAction":".ac"}},"token":"zzz"}

I dont use flutter but some error

**Comment by Ibrahim-Keyrouz** [comment]
Anything new guys ?

**Comment by mikron123** [comment]
+1

**Comment by SPodjasek** [comment]
Same issue here, unable to send messages with notification - data works fine:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.249, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

```
firebase_messaging: ^1.0.4
```

**Comment by msanchezcisneros** [comment]
I have the same issue, I already tested with v17.3.1, please help me. Thank you.
![bug-firebase](https://user-images.githubusercontent.com/43045085/45175844-f582b580-b1d3-11e8-926c-077f719a93ac.jpg)

**Comment by zoechi** [comment]
@msanchezcisneros that doesn't look like the same issue to me.

**Comment by msanchezcisneros** [comment]
@zoechi it has this issue
![image](https://user-images.githubusercontent.com/43045085/45176496-c8cf9d80-b1d5-11e8-9a0c-eedd6e96fbf2.png)

**Comment by zoechi** [comment]
@msanchezcisneros 
Please post code and errors as text instead of screenshots. 

Please post 

- the full error output (as text)
- the output of `flutter doctor -v`
- the version of `firebase_messaging` from the `pubspec.lock` file.

**Comment by msanchezcisneros** [comment]
The firebase messaging's version is 17.3.1. Thank you, I've found the issue is proper to firebase, I'll looking there for answers.

**Comment by aocwoojin** [comment]
anyone else?

**Comment by whitefox920** [comment]
I've updated com.google.firebase:firebase-messaging to 17.3.4 and issue disappeared. But there is a new issue now - the sound is played but notification is not displayed.

**Comment by kroikie** [comment]
@EdHuamani

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/770. Any further collaboration will be done there.
