### ISSUE TITLE
[Framework] non bool before ternary fails assert

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#19002]
Code that throws run time error:

```dart
theme.primaryColor ?? theme.brightness == Brightness.dark ? Colors.white : Colors.black
```

-primaryColor is a Color type
-brightness is a bool
-Colors.white and Colors.black are Color types

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building AnimatedBuilder(animation: AnimationController#b6128(⏮
0.000; paused), dirty, state: _AnimatedState#284b4):
type 'MaterialColor' is not a subtype of type 'bool'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      _OutlineButtonState._getOutlineColor (package:flutter/src/material/outline_button.dart)
#1      _OutlineButtonState._getOutline (package:flutter/src/material/outline_button.dart:383:14)
#2      _OutlineButtonState.build.<anonymous closure> (package:flutter/src/material/outline_button.dart:428:19)
#3      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:633:12)
#4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:96:48)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
#16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
#17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
#20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#24     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
#42     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
#43     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:835:5)
#44     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:849:7)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
#46     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
#47     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:763:18)
#48     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#49     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#50     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#51     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:677:9)
#54     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#55     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:664:27)
#56     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:224:22)
#59     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#60     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:221:27)
#61     main.<anonymous closure> (file:///Users/antrob/git/flutter/packages/flutter/test/material/outline_button_test.dart:107:18)
<asynchronous suspension>
#62     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:69:23)
#63     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:528:19)
<asynchronous suspension>
#66     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:512:14)
#67     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:856:24)
#73     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:853:15)
#74     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:68:22)
#75     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
<asynchronous suspension>
#76     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#81     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#82     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
#87     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
<asynchronous suspension>
#88     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#102    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#103    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#104    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by goderbauer** [comment]
I think you just have to add parentheses to get the correct evaluation order:

```dart
theme.primaryColor ?? (theme.brightness == Brightness.dark ? Colors.white : Colors.black);
```

Please reopen with more details if that doesn't fix it.
