### ISSUE TITLE
Dialog builder returning null for a particular widget

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#19016]
## Code

```
class TestApp extends StatelessWidget {
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Unit Converter',
      theme: ThemeData(
        textTheme: Theme.of(context).textTheme.apply(
          bodyColor: Colors.black,
          displayColor: Colors.grey[600],
        ),
        // This colors the [InputOutlineBorder] when it is selected
        primaryColorBrightness: Brightness.dark,
        accentColorBrightness: Brightness.light,
        primaryColorDark: Colors.grey[700],
        primaryColorLight: Colors.grey[400],
        primaryColor: Colors.grey[500],
        accentColor: Colors.yellow[700],
        textSelectionHandleColor: Colors.yellow[200],
      ),
      home: new TestFlushWidget(),
    );
  }
}

class TestFlushWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: Container(
        child: new Padding(
          padding: const EdgeInsets.symmetric(vertical: 200.0, horizontal: 64.0),
          child: new FloatingActionButton(
            onPressed: () {
              showDialog<String>(
                context: context,
                builder: (BuildContext contextInner) {

                    //return FloatingActionButton(onPressed: (){}, child: Icon(Icons.add),);

                  /*return new Flushbar(
                    title: "New DialogFlush",
                    message: "Shit! It works",
                  );*/
                },
              );
            },
            child: Icon(Icons.repeat),
          ),
        ),
      ),
    );
  }
}
```

## Steps to Reproduce

1. Import [Flushbar](https://pub.dartlang.org/packages/flushbar)
2. Uncomment the line `return FloatingActionButton(onPressed: (){}, child: Icon(Icons.add),);`
3. Run the app and click the button. Everything works fine.
4. Comment the previous line and uncomment
 ```
return new Flushbar(
                    title: "New DialogFlush",
                    message: "Shit! It works",
                  );

```
5. Run the app and click the button
6. An error appears

Flushbar is a StetefullWidget, that same as FloatingActionButton. Why am I getting this error?

## Logs

```
I/flutter (22628): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22628): The following assertion was thrown building Builder(dirty):
I/flutter (22628): A build function returned null.
I/flutter (22628): The offending widget is: Builder
I/flutter (22628): Build functions must never return null. To return an empty space that causes the building widget to
I/flutter (22628): fill available room, return "new Container()". To return an empty space that takes as little room as
I/flutter (22628): possible, return "new Container(width: 0.0, height: 0.0)".
I/flutter (22628): When the exception was thrown, this was the stack:
I/flutter (22628): #0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:250:7)
I/flutter (22628): #1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:259:4)
I/flutter (22628): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3643:7)
I/flutter (22628): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (22628): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (22628): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (22628): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (22628): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (22628): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (22628): #111    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (22628): #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (22628): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (22628): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (22628): #115    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4437:32)
I/flutter (22628): #116    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (22628): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #118    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (22628): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (22628): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #126    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (22628): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (22628): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #132    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (22628): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #134    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (22628): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (22628): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (22628): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (22628): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (22628): #140    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (22628): #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (22628): #142    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (22628): #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22628): #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22628): #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (22628): #146    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (22628): #147    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (22628): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## Doctor

[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by jonahwilliams** [comment]
@AndreHaueisen if it is only causing an error when you build the Flushbar widget, then it seems like a bug there?

**Comment by AndreHaueisen** [comment]
@jonahwilliams , the widget itself works normally when it not used inside a builder. I will investigate further and post the solution if I find it.

**Comment by AndreHaueisen** [comment]
@jonahwilliams ,  I found the problem. Not a flutter bug. Sorry for wasting your time. Feel free to close this issue.

**Comment by jonahwilliams** [comment]
No problem!
