### ISSUE TITLE
"Bad state: No element" doing initial hot reload

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19020]
Steps to reproduce:

* `flutter run` the gallery.
* Add a bogus argument to a constructor somewhere.
* Hot reload.

```
Initializing hot reload...
compiler message: lib/demo/material/overscroll_demo.dart:53:15: Error: No named parameter with the name 'expandedHeight'.
compiler message:               expandedHeight: 150.0,
compiler message:               ^^^^^^^^^^^^^^
compiler message: file:///usr/local/google/home/ianh/dev/flutter/packages/flutter/lib/src/material/app_bar.dart:135:3: Context: Found this candidate, but the arguments don't match.
compiler message:   AppBar({
compiler message:   ^
Unable to hot reload. No instance of Flutter is currently running.
Try again after fixing the above error(s).
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/dart:core/array.dart:165)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:579)
#2      _rootRunUnary (dart:async/zone.dart:1134)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#6      Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      Future._completeWithValue (dart:async/future_impl.dart:482)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

cc @aam

**Comment by suparnavg** [comment]
@Hixie did you manage to figure this out? I'm using Submine Text 3 and the console, following the steps given on the [set up page](https://flutter.io/get-started/test-drive/#terminal)

**Comment by prntcena** [comment]
just try reinstalling the app on either emulator or on your device

**Comment by jonahwilliams** [comment]
I'm no longer able to reproduce this on master:

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter run
Running "flutter packages get" in hello_world...                    0.3s
Launching lib/main.dart on iPhone XS Max in debug mode...

Compiler message:
lib/main.dart:7:65: Error: No named parameter with the name 'fizz'.
void main() => runApp(const Center(child: Text('Hello, world!', fizz: 'bar', textDirection: TextDirection.ltr)));
                                                                ^^^^
file:///Users/jonahwilliams/Documents/flutter/packages/flutter/lib/src/widgets/text.dart:227:9: Context: Found this candidate, but the arguments don't
match.
  const Text(
        ^
Compiler failed on /Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/main.dart
Error launching application on iPhone XS Max.
```
