### ISSUE TITLE
A basic app of Container with ListView of images throws a textDirection != null error

### ISSUE THREAD

**Issue by srix55** [flutter/flutter#19039]
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(
      color: Colors.green,
      child: ListView(
        children: <Widget>[
          Image(image: AssetImage('images/Handsome_Squidward.jpg')),
          Image(image: AssetImage('images/Handsome_Squidward.jpg')),
          Image(image: AssetImage('images/Handsome_Squidward.jpg')),
          Image(image: AssetImage('images/Handsome_Squidward.jpg'))
        ],
      ),
    );
  }
}

I/flutter ( 7242): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7242): The following assertion was thrown building _ScrollableScope:
I/flutter ( 7242): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 220 pos 10: 'textDirection
I/flutter ( 7242): != null': is not true.
I/flutter ( 7242): 
I/flutter ( 7242): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7242): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7242): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7242):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7242): 
I/flutter ( 7242): When the exception was thrown, this was the stack:
I/flutter ( 7242): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart)
I/flutter ( 7242): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
I/flutter ( 7242): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
I/flutter ( 7242): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4276:28)
I/flutter ( 7242): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4755:11)
I/flutter ( 7242): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter ( 7242): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 7242): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 7242): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 7242): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 7242): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 7242): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 7242): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 7242): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 7242): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 7242): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #54     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 7242): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 7242): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 7242): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 7242): #58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 7242): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 7242): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 7242): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7242): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7242): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 7242): #65     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 7242): #66     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 7242): #67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 7242): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 7242): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
If you don't wrap it in a `Scaffold` you need to provide a few widgets on your own, like 
```dart
new MediaQuery(
      data: new MediaQueryData.fromWindow(ui.window),
      child: new Directionality(
          textDirection: TextDirection.ltr,
          child: /* your widget here */));
```
You might also need `Material` as parent for some material widgets.

I'm going to close the issue because there doesn't seem to be any action necessary.
Feel free to add a comment if you think it should be reopened.
