### ISSUE TITLE
App crashes during the launch on android 4.1.2

### ISSUE THREAD

**Issue by Viked** [flutter/flutter#19080]
## Steps to Reproduce

1. Run "flutter build apk"
2. Install on android emulator 4.1.2 with "adb install build/app/outputs/apk/release/app-release.apk"
3. Launch app

## Logs

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.UnsatisfiedLinkError: Couldn't load flutter: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:365)
        at java.lang.System.loadLibrary(System.java:535)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:172)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:149)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
```

```
Analyzing mobile...                                              

   info • Name non-constant identifiers using lowerCamelCase • lib/model/model.dart:2:16
   info • Name non-constant identifiers using lowerCamelCase • lib/model/model.dart:3:16
   info • Name non-constant identifiers using lowerCamelCase • lib/tests/test_page.dart:39:8
   info • Name non-constant identifiers using lowerCamelCase • lib/tests/test_page.dart:44:8
   info • Use `;` instead of `{}` for empty constructor bodies • lib/tests/test_page.dart:53:24
warning • The asset icons/ does not exist • pubspec.yaml:44:6

6 issues found. (ran in 3.3s)
```

```

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Users/yevgeniishein/Library/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/yevgeniishein/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/yevgeniishein/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.24.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.13.2

[✓] Connected devices (1 available)
    • emulator-5554 • emulator-5554 • android-x86 • Android 4.1.2 (API 16) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by rostopira** [comment]
Yep, it's still an issue

**Comment by zoechi** [comment]
@rostopira can you please provide more information about how to reproduce?

Please add the output of `flutter doctor -v`.

**Comment by rostopira** [comment]
Just install Jelly Bean emulator via AVD, 4.1.2 with Google APIs, try to launch anything
Gonna test with 4.2 now
But to be honest, I think it's emulator bug, not flutter

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.1 18B75, locale
    en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
[!] VS Code (version 1.31.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by rostopira** [comment]
Got a response from tester
App works just fine on a real device running Andoid 4.1.1

**Comment by zoechi** [comment]
Is this also with `flutter run` or only with `flutter build ...` and `flutter install`?

**Comment by rostopira** [comment]
@zoechi with both and `--debug` param, I've even tried with `--target-platform=android-x86` and `--target-platform=android-x64`

**Comment by zoechi** [comment]
> Is this also with `flutter run` or only with `flutter build ...` and `flutter install`?

Sorry, I meant  `flutter build ...` and `adb install`

> 2\. Install on android emulator 4.1.2 with `adb install build/app/outputs/apk/release/app-release.apk`
