### ISSUE TITLE
Hot reload bug in CupertinoTabScaffold

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#19084]
Flutter version:
Flutter (Channel dev, v0.5.5, on Mac OS X 10.12.6 16G1408, locale en-US)
    • Flutter version 0.5.5
    • Framework revision 020e0ef55c (3 weeks ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

Repro steps:

1. Deploy an app with the following structure
2. Remove one of the tabs from the `CupertinoTabBar` and save (with hot reload)
3. An error occurs.

Widget structure to start with:
```dart
@override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(items: [
        BottomNavigationBarItem(
          icon: Icon(
            Icons.home,
          ),
          title: Text('Today'),
        ),
        BottomNavigationBarItem(
          icon: Icon(
            Icons.home,
          ),
          title: Text('Games'),
        ),
        BottomNavigationBarItem(
          icon: Icon(
            Icons.home,
          ),
          title: Text('Apps'),
        ),
        BottomNavigationBarItem(
          icon: Icon(
            Icons.home,
          ),
          title: Text('Updates'),
        ),
        BottomNavigationBarItem(
          icon: Icon(
            Icons.home,
          ),
          title: Text('Search'),
        ),
      ]),
      tabBuilder: (BuildContext context, int index) {
        return CupertinoPageScaffold(
          navigationBar: CupertinoNavigationBar(
            middle: Text('App Store'),
          ),
          child: Center(
            child: Container(
              color: Colors.green,
            ),
          ),
        );
      },
    );
  }
```

Error:
```
Performing hot reload...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following RangeError was thrown building _TabSwitchingView(dirty, state:
flutter: _TabSwitchingViewState#e9f48):
flutter: RangeError (index): Invalid value: Not in range 0..3, inclusive: 4
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core/runtime/libarray.dart:10:52)
flutter: #1      _TabSwitchingViewState.build.<anonymous closure> (package:flutter/src/cupertino/tab_scaffold.dart:286:27)
flutter: #2      new List.generate (dart:core/list.dart:162:28)
flutter: #3      _TabSwitchingViewState.build (package:flutter/src/cupertino/tab_scaffold.dart:283:21)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
flutter: #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #18     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
flutter: #35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #61     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #87     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #91     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #98     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #99     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #100    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by matthew-carroll** [comment]
CC @xster

**Comment by xster** [comment]
Yup, looks buggy. _CupertinoTabScaffoldState.didUpdateWidget definitely needs to handle tabBar.items.length. Also needs to handle tabBuilder changing and swap out the cached widgets from _TabSwitchingViewState.tabs.

**Comment by jianggaocheng** [comment]
The same bugs, hope to fix
