### ISSUE TITLE
Failed assertion: line 62 pos 15: 'tristate || value flutter: != null': is not true.

### ISSUE THREAD

**Issue by bradh43** [flutter/flutter#19119]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LoginPage(dirty, state: _LoginPageState#0cb7c(ticker
flutter: inactive)):
flutter: 'package:flutter/src/material/checkbox.dart': Failed assertion: line 62 pos 15: 'tristate || value
flutter: != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Checkbox (package:flutter/src/material/checkbox.dart)
flutter: #3      _LoginPageState.keepSignedIn (file:///Users/bradhodkinson/Desktop/projects/flut_run/lib/pages/login_page.dart:192:13)
flutter: #4      _LoginPageState.loginBody (file:///Users/bradhodkinson/Desktop/projects/flut_run/lib/pages/login_page.dart:259:27)
flutter: #5      _LoginPageState.loginTab (file:///Users/bradhodkinson/Desktop/projects/flut_run/lib/pages/login_page.dart:240:9)
flutter: #6      _LoginPageState.build (file:///Users/bradhodkinson/Desktop/projects/flut_run/lib/pages/login_page.dart:228:13)
flutter: #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #20     _invoke (dart:ui/hooks.dart:120:13)
flutter: #21     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jonahwilliams** [comment]
@bradh43 The error is that you've passed a value of `null` to a checkbox, but this is only supported if the tristate property is true (somewhere around `login_page.dart:192:13`).

**Comment by zoechi** [comment]
I assume @jonahwilliams' comment solved the problem.
