### ISSUE TITLE
Either the assertion indicates an error in the framework itself

### ISSUE THREAD

**Issue by dtunctuncer** [flutter/flutter#19118]
```
07-06 16:28:29.265 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
07-06 16:28:29.269 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: The following assertion was thrown during performLayout():
    'package:flutter/src/widgets/basic.dart': Failed assertion: line 5364 pos 15: 'builder != null': is
    not true.
07-06 16:28:29.272 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new
    When the exception was thrown, this was the stack:
07-06 16:28:29.278 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: #2      new Builder (package:flutter/src/widgets/basic.dart)
    #3      showDialog (package:flutter/src/material/dialog.dart:643:25)
    #4      _MyHomePageState._clickPostItem (package:flutter_net_test_app/MyHomePage.dart:68:5)
    #5      _MyHomePageState._buildRow (package:flutter_net_test_app/MyHomePage.dart:63:14)
    #6      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:flutter_net_test_app/MyHomePage.dart:43:26)
    #7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197:20)
    #8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716:67)
    #9      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
    #10     SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716:26)
    #11     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:55)
    #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
    #13     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
    #14     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
    #15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
    #16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
    #17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
    #18     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
    #19     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
    #20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
07-06 16:28:29.279 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #22     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #24     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
    #25     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
    #26     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
    #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
    #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
    #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
    #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
    #48     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
    #49     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
    #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
    #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
    #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
    #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
07-06 16:28:29.280 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
    #56     _invoke (dart:ui/hooks.dart:120:13)
    #57     _drawFrame (dart:ui/hooks.dart:109:3)
    (elided 2 frames from class _AssertionError)
07-06 16:28:29.286 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: The following RenderObject was being processed when the exception was fired:
      RenderSliverList#1fe4c relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
      creator: SliverList ← SliverPadding ← Viewport ← _ScrollableScope ←
      IgnorePointer-[GlobalKey#5575d] ← Semantics ← Listener ← _GestureSemantics ←
      RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b4f2f] ←
      _ExcludableScrollSemantics-[GlobalKey#e70b4] ← RepaintBoundary ← CustomPaint ← ⋯
      parentData: paintOffset=Offset(0.0, 0.0) (can use size)
      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
      scrollOffset: 0.0, remainingPaintExtent: 587.4, crossAxisExtent: 379.4, crossAxisDirection:
      AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 837.4 cacheOrigin: 0.0 )
      geometry: null
      no children current live
    This RenderObject has no descendants.
    ════════════════════════════════════════════════════════════════════════════════════════════════════
07-06 16:28:29.292 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
    Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
07-06 16:28:29.295 13081-13099/com.dtunctuncer.flutternettestapp I/flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor -v`?

**Comment by dtunctuncer** [comment]
```
➜ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-TR)
    • Flutter version 0.5.1 at /Users/deniztuncer/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/deniztuncer/Library/Android/sdk
    • Android NDK at /Users/deniztuncer/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by dnfield** [comment]
Please include the content of     `_MyHomePageState` - I suspect you're missing something in there.

**Comment by dtunctuncer** [comment]
I haved solved the problem but I think framework should tell me what was the problem. 

I was trying to use showDialog() method I pass the only context value since it is required.
And I get this exception. I fix it like this

```
showDialog(
          context: context,
          builder: (context) {
            return new AlertDialog(
              title: new Text(data.title.toUpperCase()),
              content: new Text(data.body),
              actions: <Widget>[
                new MaterialButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: new Text("CLOSE"),
                )
              ],
            );
          },
        );
```

**Comment by obbe79** [comment]
Hi, it appears I have a similar problem using showDialog() method.
This is the output:

```I/flutter (25151): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25151): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (25151): _WidgetsAppState#5cf06](dirty, state: NavigatorState#3c558(tickers: tracking 3 tickers)):
I/flutter (25151): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1946 pos 12: '!_debugLocked':
I/flutter (25151): is not true.
I/flutter (25151): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25151): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25151): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25151):   https://github.com/flutter/flutter/issues/new
I/flutter (25151): When the exception was thrown, this was the stack:
I/flutter (25151): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:1946:12)
I/flutter (25151): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (25151): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (25151): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (25151): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (25151): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (25151): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (25151): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #24     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (25151): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (25151): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (25151): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (25151): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #58     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (25151): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (25151): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (25151): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (25151): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (25151): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (25151): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (25151): #74     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (25151): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter (25151): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (25151): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25151): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25151): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (25151): #81     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (25151): #82     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (25151): #83     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (25151): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (25151): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 421 libraries in 1.209ms.
```


My flutter doctor output is the following:

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Versione 10.0.16299.726], locale it-IT)
    • Flutter version 0.9.4 at C:\Users\user\flutterSdk\flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • HTC One • SH35NW904840 • android-arm • Android 5.0.2 (API 21)

• No issues found!
```
