### ISSUE TITLE
Weird assert occurs after tapping a gesture detector on ios.  Not sure what the issue is.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1912]
```dart
[iPad Air 2] Runner: '/Users/apwilson/git/lolwat/packages/flutter/src/gestures/converter.dart': Failed assertion: line 124: 'position == state.lastPosition' is not true.
[iPad Air 2] Runner: #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
[iPad Air 2] Runner: #1      PointerEventConverter.expand.<expand_sync_body> (/Users/apwilson/git/lolwat/packages/flutter/src/gestures/converter.dart:124)
[iPad Air 2] Runner: #2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:61)
[iPad Air 2] Runner: #3      BindingBase&Scheduler&Gesturer._handlePointerPacket (/Users/apwilson/git/lolwat/packages/flutter/src/gestures/binding.dart:42)
[iPad Air 2] Runner: #4      _dispatchPointerPacket (file:///private/tmp/flutter_build_workspace/src/out/ios_sim_Release/gen/sky/bindings/hooks.dart:43)
```

**Comment by apwilson** [comment]
My app applies an animated opacity, translation, scale, and rotation transform via an AnimatedBuilder with the onTap GestureDetector as a child if that makes any difference.

**Comment by apwilson** [comment]
Also, the assert doesn't happen until  a large nuimber of taps have already gone through.  Maybe 30 or so.

**Comment by chinmaygarde** [comment]
Does this happen on Android? I tried to reproduce this in a reduced test case and was unsuccessful. Makes me think this is a framework issue.

**Comment by eseidelGoogle** [comment]
I'm hitting this as well.

```
flutter --version
Flutter from https://github.com/flutter/flutter.git (on master)
flutter revision: 7a2c38abc8745d8580cac1ddb0d3b18bd5fb6e73 (20 hours ago)
engine revision : 9e1e1fba5474b458458b65f1aa1d0d730af2705b
```

Seems like a showstopper.

**Comment by eseidelGoogle** [comment]
This may need consult from @Hixie or @abarth.
