### ISSUE TITLE
RadioListTile triggers error when tapped related to changing backgroundColor

### ISSUE THREAD

**Issue by slamethendry** [flutter/flutter#19139]
## Steps to Reproduce

I am using RadioListTile to set app colour, which is defined in Scaffold's backgroundColor.  When I tap on the RadioListTile, it triggers error message.  

This might be specific to setting the colour.  Other RadioListTile in the app does not trigger the error.

```
var _colourSetting = Colors.grey;

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: _str('My App'), 
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(_str('Home')),
        centerTitle: true,
        backgroundColor: _colourSetting, // HERE IS THE CONTEXT for this issue;
        actions: <Widget>[
          new IconButton(
              icon: new Icon(Icons.file_download),
              onPressed: _showDownloadResult),
        ],
      ),
      backgroundColor: _colourSetting, // HERE IS THE CONTEXT for this issue
      drawer: _myDrawer(),
      body: null,
    );
  }
```

And then elsewhere in the setting panel.
```
    Navigator.of(context).push(new MaterialPageRoute(builder: (context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text(_str('Settings')),
          centerTitle: true,
        ),
        body: ListView(
          children: <Widget>[
            new ListTile(
              title: Text(_str('Theme')),
            ),
            new RadioListTile<Color>(
              title: const Text('Grey'),
              value: Colors.grey,
              groupValue: _colourSetting,
              onChanged: (Color value) { // HERE IS THE TRIGGER
                setState(() {
                  _colourSetting = value;
                });
              },
            ),
            new RadioListTile<Color>(
              title: const Text('White'),
              value: Colors.white,
              groupValue: _colourSetting,
              onChanged: (Color value) { // HERE IS THE TRIGGER
                setState(() {
                  _colourSetting = value;
                });
              },
            ),
          ],
        ),
      );
    }));
```

## Logs

```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Syncing files to device iPhone X...
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞══
flutter: The following assertion was thrown while handling a gesture:
flutter: type 'Color' is not a subtype of type 'MaterialColor'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _MyHomePageState._editSettings.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/sh/Documents/flutter_proj/c2c/lib/main.dart:153:36)
flutter: #1      State.setState (package:flutter/src/widgets/framework.dart:1125:30)
flutter: #2      _MyHomePageState._editSettings.<anonymous closure>.<anonymous closure> (file:///Users/sh/Documents/flutter_proj/c2c/lib/main.dart:152:17)
flutter: #3      _RadioState._handleChanged (package:flutter/src/material/radio.dart)
flutter: #4      RenderToggleable._handleTap (package:flutter/src/material/toggleable.dart:285:9)
flutter: #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
flutter: #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #14     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#783d1(state: ready, won arena, finalPosition: Offset(38.3, 579.0), sent tap
flutter:   down)
flutter: 
Application finished.
```

```
flutter analyze .
Analyzing lib...                                                 
No issues found! (ran in 1.7s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-ID)
    • Flutter version 0.5.1 at /Users/sh/Documents/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • D1C012E4-272D-43AA-994C-9CAA3782E2AE • ios • iOS 11.4 (simulator)
```

Thank you for taking a look at this.

**Comment by jonahwilliams** [comment]
Hi @slamethendry, the error is actually right here:

```dart
var _colourSetting = Colors.grey;
```

Should instead be:

```dart
Color _colorSetting = Colors.grey;
```

The problem is that when you type a member with `var`, you tell dart to infer the type based on the right hand side.  When it does that, it will use the most specific type possible (otherwise everything would get typed as `Object`).  Since `Colors.grey` is a `Color` and a `MaterialColor`, and MaterialColor is more specific, it gets inferred as that.  And try to assign a `Color` to a `MaterialColor` is causes the type error above, similar to trying to assign an `Object` to a `String`.

**Comment by slamethendry** [comment]
Got it.  Many thanks.
