### ISSUE TITLE
Rendering Exception in Flutter Version v0.5.1

### ISSUE THREAD

**Issue by BM2304** [flutter/flutter#19136]
```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main () async {

  var data = await readData();
  if (data != null){
    String message = await readData();
    print(message);
  }

  runApp(new MaterialApp(
    title: 'IO',
    home: new Home(),
  )
  );
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {

  var _enterDataField = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Read/Write'),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),
      body: new Container(
        padding: const EdgeInsets.all(14.4),
        alignment: Alignment.topCenter,
        child: new ListTile(
          title: new TextField(
            controller: _enterDataField,
            decoration: new InputDecoration(
                labelText: 'Write Something'
            ),
          ),
          subtitle: new Text('Test')
        ),
      ),
    );
  }
}
```

```
## Logs
I/flutter (12326): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12326): The following assertion was thrown during performLayout():
I/flutter (12326): not implemented
I/flutter (12326): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (12326): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12326): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12326): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12326):   https://github.com/flutter/flutter/issues/new
I/flutter (12326): When the exception was thrown, this was the stack:
I/flutter (12326): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (12326): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (12326): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (12326): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (12326): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (12326): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (12326): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (12326): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (12326): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (12326): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (12326): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (12326): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (12326): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (12326): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (12326): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (12326): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (12326): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (12326): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (12326): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:778:32)
I/flutter (12326): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12326): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (12326): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12326): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (12326): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (12326): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (12326): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (12326): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (12326): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter (12326): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (12326): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12326): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (12326): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (12326): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (12326): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (12326): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (12326): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (12326): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (12326): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12326): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12326): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (12326): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (12326): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (12326): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (12326): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (12326): The following RenderObject was being processed when the exception was fired:
I/flutter (12326):   _RenderListTile#8329a relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12326):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (12326):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
I/flutter (12326):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (12326):   constraints: BoxConstraints(0.0<=w<=350.6, 0.0<=h<=573.5)
I/flutter (12326):   size: MISSING
I/flutter (12326): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12326):   RenderSemanticsAnnotations#bf7c7 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (12326):     RenderIgnorePointer#4bd6c relayoutBoundary=up9 NEEDS-PAINT
I/flutter (12326):       RenderPointerListener#78fca relayoutBoundary=up10 NEEDS-PAINT
I/flutter (12326):         _RenderDecoration#822b1 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (12326):           RenderRepaintBoundary#1ef3a relayoutBoundary=up12 NEEDS-PAINT
I/flutter (12326):           RenderTransform#0e18d relayoutBoundary=up12 NEEDS-PAINT
I/flutter (12326):           RenderConstrainedBox#2e38f relayoutBoundary=up12 NEEDS-PAINT
I/flutter (12326):           RenderCustomPaint#de67b NEEDS-PAINT
I/flutter (12326):   RenderParagraph#730ae relayoutBoundary=up8 NEEDS-PAINT
I/flutter (12326): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12326): Another exception was thrown: RenderBox was not laid out: _RenderListTile#8329a relayoutBoundary=up7 NEEDS-PAINT
I/flutter (12326): Another exception was thrown: RenderBox was not laid out: RenderPadding#98ebf relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12326): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#2f17b relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12326): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#53669 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12326): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
--
Analyzing readwritedata...
No issues found! (ran in 3.4s)
```

--
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale de-DE)
    • Flutter version 0.5.1 at C:\Flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\bjorn_000\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.2
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code, 64-bit edition (version 1.22.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Looks quite similar to #18778
