### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by xadelx** [flutter/flutter#19141]
![image](https://user-images.githubusercontent.com/32979588/42412912-9ac4aa2e-81e3-11e8-84e5-3769e8b8aa3a.png)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 3d16e9496950e4bb)
Crash report written to /tmp/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.

**What should i do to fix this issue?**

**Comment by jonahwilliams** [comment]
@xadelx The error will be in the log file written, if you could include that it would help.  Since it is crashing so early I imagine it is an installation problem though.

**Comment by xadelx** [comment]
@jonahwilliams  
Yeah, I really found 3 problems in the log file
But how to fix them , any help! 

the following lines are of the log file ..


## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/home/adel/dev/flutter/version' (OS Error: Permission denied, errno = 13)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368)
#1      _rootRunUnary (dart:async/zone.dart:1134)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#5      Future._propagateToListeners (dart:async/future_impl.dart:662)
#6      Future._completeWithValue (dart:async/future_impl.dart:477)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/adel/dev/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/adel/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /home/adel/Android/Sdk
    • Java binary at: /home/adel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.1)
    • Android Studio at /home/adel/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.0)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by jonahwilliams** [comment]
@xadelx looks like you don't have permission to read/write/execute the directory where you downloaded flutter.  Maybe something like - `sudo chown -R $USER:admin /home/adel/dev/flutter/`?

**Comment by xadelx** [comment]
You were right, I can finally run flutter now.
Thank you @jonahwilliams :+1:

**Comment by jonahwilliams** [comment]
No problem!
