### ISSUE TITLE
Setting textTheme in ThemeData not working like answers in Stackoverflow suggest

### ISSUE THREAD

**Issue by AntonTrapp** [flutter/flutter#19150]
```dart
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building AnimatedTheme(duration: 200ms, dirty, state:
flutter: _AnimatedThemeState#0ba4c(ticker active, ThemeDataTween(ThemeData#3ddda(primaryColor:
flutter: MaterialColor(primary value: Color(0xffff9800)), primaryColorBrightness: light, accentColor:
flutter: Color(0xffff9800), accentColorBrightness: light, secondaryHeaderColor: Color(0xfffff3e0),
flutter: textSelectionColor: Color(0xffffcc80), textSelectionHandleColor: Color(0xffffb74d), backgroundColor:
flutter: Color(0xffffcc80), indicatorColor: Color(0xffff9800), toggleableActiveColor: Color(0xfffb8c00),
flutter: buttonTheme: ButtonThemeData#c7a4e, textTheme: TextTheme#d15b2, primaryTextTheme: TextTheme#d15b2,
flutter: accentTextTheme: TextTheme#d15b2, inputDecorationTheme: InputDecorationTheme#40048, iconTheme:
flutter: IconThemeData#a143c(color: Color(0xff000000)), primaryIconTheme: IconThemeData#a143c(color:
flutter: Color(0xff000000)), accentIconTheme: IconThemeData#a143c(color: Color(0xff000000)), sliderTheme:
flutter: SliderThemeData#6824b(activeTrackColor: Color(0xffff9800), inactiveTrackColor: Color(0x3dff9800),
flutter: disabledActiveTrackColor: Color(0x52f57c00), disabledInactiveTrackColor: Color(0x1ff57c00),
flutter: activeTickMarkColor: Color(0x8affe0b2), inactiveTickMarkColor: Color(0x8aff9800),
flutter: disabledActiveTickMarkColor: Color(0x1fffe0b2), disabledInactiveTickMarkColor: Color(0x1ff57c00),
flutter: thumbColor: Color(0xffff9800), disabledThumbColor: Color(0x52f57c00), overlayColor:
flutter: Color(0x29ff9800), valueIndicatorColor: Color(0xffff9800), valueIndicatorTextStyle:
flutter: TextStyle(debugLabel: blackCupertino body2, inherit: true, color: Color(0xdd000000), family: .SF UI
flutter: Text, decoration: TextDecoration.none)), chipTheme: ChipThemeData#11816(secondarySelectedColor:
flutter: Color(0x3dff9800), secondaryLabelStyle: TextStyle(debugLabel: (blackCupertino body2).copyWith,
flutter: inherit: true, color: Color(0xdeff9800), family: .SF UI Text, decoration: TextDecoration.none))) →
flutter: ThemeData#f053e(primaryColor: MaterialColor(primary value: Color(0xffff9800)),
flutter: primaryColorBrightness: light, accentColor: Color(0xffff9800), accentColorBrightness: light,
flutter: secondaryHeaderColor: Color(0xfffff3e0), textSelectionColor: Color(0xffffcc80),
flutter: textSelectionHandleColor: Color(0xffffb74d), backgroundColor: Color(0xffffcc80), indicatorColor:
flutter: Color(0xffff9800), toggleableActiveColor: Color(0xfffb8c00), buttonTheme: ButtonThemeData#c7a4e,
flutter: textTheme: TextTheme#786f1(display4: TextStyle(debugLabel: ((englishLike
flutter: display4).merge(blackCupertino display4)).apply, inherit: false, color: Color(0xffffffff), family:
flutter: .SF UI Display, size: 112.0, weight: 100, baseline: alphabetic, decoration: TextDecoration.none),
flutter: display3: TextStyle(debugLabel: ((englishLike display3).merge(blackCupertino display3)).apply,
flutter: inherit: false, color: Color(0xffffffff), family: .SF UI Display, size: 56.0, weight: 400, baseline:
flutter: alphabetic, decoration: TextDecoration.none), display2: TextStyle(debugLabel: ((englishLike
flutter: display2).merge(blackCupertino display2)).apply, inherit: false, color: Color(0xffffffff), family:
flutter: .SF UI Display, size: 45.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none),
flutter: display1: TextStyle(debugLabel: ((englishLike display1).merge(blackCupertino display1)).apply,
flutter: inherit: false, color: Color(0xffffffff), family: .SF UI Display, size: 34.0, weight: 400, baseline:
flutter: alphabetic, decoration: TextDecoration.none), headline: TextStyle(debugLabel: ((englishLike
flutter: headline).merge(blackCupertino headline)).apply, inherit: false, color: Color(0xffffffff), family:
flutter: .SF UI Display, size: 24.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none),

... about 500GB of text ...

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

In either case, please report this assertion by filing a bug on GitHub: https://github.com/flutter/flutter/issues/new

flutter: When the exception was thrown, this was the stack:
flutter: #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart)
flutter: #3      TextTheme.lerp (package:flutter/src/material/typography.dart:380:27)
flutter: #4      ThemeData.lerp (package:flutter/src/material/theme_data.dart:685:28)
flutter: #5      ThemeDataTween.lerp (package:flutter/src/material/theme.dart:188:41)
flutter: #6      Tween.evaluate (package:flutter/src/animation/tween.dart:160:12)
flutter: #7      _AnimatedThemeState.build (package:flutter/src/material/theme.dart:247:19)
flutter: #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #17     _invoke (dart:ui/hooks.dart:120:13)
flutter: #18     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 521 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.
flutter: Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 521 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.
...
```

What I tried to do:

```dart
       theme: ThemeData(
        primarySwatch: Colors.orange,
        textTheme: Theme.of(context).textTheme.apply(
          bodyColor: Colors.white,
          displayColor: Colors.white,
        ),
      ),
```

(like the Stackflow answers ie https://stackoverflow.com/questions/49203740/how-to-change-the-entire-themes-text-color-in-flutter?rq=1, the only source for changing the text color I found)

--> In either case, please report this assertion by filing a bug on GitHub --> did that :)

**Comment by AntonTrapp** [comment]
If anybody has the same problem, found a solution for simple black and white text at least (for some widgets, FloatingActionButton ie is completely ignoring the text color):

```dart
      theme: ThemeData(
        primarySwatch: Colors.orange,
        primaryTextTheme: Typography(platform: TargetPlatform.iOS).white,
        // accentTextTheme: Typography(platform: TargetPlatform.iOS).black,
        textTheme: Typography(platform: TargetPlatform.iOS).black,
      ),
```

**Comment by psyanite** [comment]
Works for me 
```
getTheme(context) => ThemeData(
  primarySwatch: Burnt.material_primary,
  accentColor: Burnt.material_primary,
  fontFamily: Burnt.fontBase,
  textTheme: Theme.of(context).textTheme.apply(
    bodyColor: Burnt.textBody,
    displayColor: Burnt.textBody,
  ).merge(
    TextTheme(
      body1: TextStyle(fontSize: 16.0)
    )
  ),
);


...

      child: MaterialApp(title: 'Crust', theme: getTheme(context), routes: <String, WidgetBuilder>{
        MainRoutes.root: (context) => MainTabNavigator(),
      }),
```

**Comment by AntonTrapp** [comment]
Actually ditched flutter after my evaluation. Not nearly as stable/mature as I want it (for me!), faster with native iOS and Android at the moment. So: sorry, don't have the code any more. Basically it was a standard sample where I tried just some minor UI changes at that point. As about half a year has gone bye probably not relevant any more. And as nobody else can reproduce it I will close it. If anybody still has the same problem he/she can reopen it.

**Comment by zoechi** [comment]
@AntonTrapp thanks for the update!

**Comment by AntonTrapp** [comment]
you're welcome und schöne Grüße die paar Kilometer ;)

**Comment by patelkrunal78** [comment]
Maybe a bit late... but you can use this:

ThemeData(
    primaryTextTheme: Typography(platform: TargetPlatform.iOS).white,
    textTheme: Typography(platform: TargetPlatform.iOS).white,
)

https://icetutor.com/question/how-to-change-the-entire-themes-text-color-in-flutter

**Comment by milanpatel18** [comment]
This is Worked For Me

final newTextTheme = Theme.of(context).textTheme.apply(
bodyColor: Colors.pink,
displayColor: Colors.pink,
);

Founded At [here](https://icetutor.com/question/how-to-change-the-entire-themes-text-color-in-flutter/)

**Comment by Kthulu120** [comment]
FYI just so no one has a similar problem you **cannot** mix TextThemeData 2016 and 2018 terms otherwise Flutter will not recognize the Theme.
