### ISSUE TITLE
Why is not iPad Simulator full screen?

### ISSUE THREAD

**Issue by 9wisit** [flutter/flutter#19161]
## Steps to Reproduce

1. Run iPad Pro (12.9-inch) 11.4
2. Run application
3. It worked.

## Log

```
[  +43 ms] [/Users/Wisit/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/Wisit/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/Wisit/flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/Wisit/flutter/] git log -n 1 --pretty=format:%H
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [/Users/Wisit/flutter/] git log -n 1 --pretty=format:%ar
[  +16 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 6 weeks ago
[   +1 ms] [/Users/Wisit/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +46 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca37
[ +711 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/MAMP/Library/scgi_temp/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/MAMP/Library/uwsgi_temp/' (OS Error: Permission denied, errno = 13)
[   +5 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/MAMP/Library/proxy_temp/' (OS Error: Permission denied, errno = 13)
[+1153 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/MAMP/Library/fastcgi_temp/' (OS Error: Permission denied, errno = 13)
[  +57 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/MAMP/Library/client_body_temp/' (OS Error: Permission denied, errno = 13)
[+18461 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +167 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[   +1 ms] 3.1
[ +270 ms] /Users/Wisit/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/Wisit/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           31002b57a1c55345       device usb:337641472X product:j7xeltexx model:SM_J710F device:j7xelte transport_id:1
[  +30 ms] idevice_id -h
[ +148 ms] which ideviceinstaller
[  +14 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +8 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[ +574 ms] /usr/bin/xcrun simctl list --json devices
[ +243 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +13 ms] /Users/Wisit/Library/Android/sdk/platform-tools/adb -s 31002b57a1c55345 shell getprop
[ +164 ms] ro.hardware = samsungexynos7870
[   +7 ms] SM J710F             • 31002b57a1c55345                         • android-arm • Android 7.0 (API 24)
[   +1 ms] Wisit Phusi’s iPhone • 539ca7a9dcbf0538cc978fb5c942e90d6c385d43 • ios         • iOS 11.4
[        ] iPhone X             • DB206619-452A-4663-8529-FE6E8AF41E3C     • ios         • iOS 11.4 (simulator)
[        ] iPad Pro (12.9-inch) • FADF9C11-A3B7-433C-8751-84059F695161     • ios         • iOS 11.4 (simulator)
[  +13 ms] "flutter run" took 21,987ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:250)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:50)
#30     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#31     main (file:///Users/Wisit/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```                           
   info • Unused import: 'package:sanook_trips/screen/ImageViewScreen.dart' • lib/dart/Screen.dart:1:8
   info • Name non-constant identifiers using lowerCamelCase • lib/data/PlaceDetail.dart:5:10
   info • Name non-constant identifiers using lowerCamelCase • lib/data/PlaceDetail.dart:8:10
   info • Unused import: 'dart:convert' • lib/home/tabs/accountTab.dart:6:8
   info • Unused import: 'package:sanook_trips/lang/lang.dart' • lib/home/tabs/accountTab.dart:7:8
   info • Cancel instances of dart.async.StreamSubscription • lib/home/tabs/homeTab.dart:190:43
   info • The value of the field '_locationSubscription' isn't used • lib/home/tabs/homeTab.dart:190:43
   info • The method '_onTab' isn't used • lib/home/tabs/homeTab.dart:246:3
   info • The value of the field '_visible' isn't used • lib/home/tabs/homeTab.dart:298:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/home/tabs/homeTab.dart:801:7
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/home/tabs/homeTab.dart:861:7
   info • Unused import: 'dart:async' • lib/home/tabs/newsTab.dart:1:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/home/tabs/shareTab.dart:194:7
   info • Unused import: 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart' • lib/home/tabs/tripTab.dart:2:8
   info • Unused import: 'dart:convert' • lib/home/tabs/tripTab.dart:4:8
   info • Unused import: 'package:sanook_trips/models/auth.dart' • lib/home/tabs/tripTab.dart:10:8
   info • Unused import: 'package:sanook_trips/lang/lang.dart' • lib/home/tabs/tripTab.dart:11:8
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/home/tabs/tripTab.dart:12:8
   info • Avoid using braces in interpolation when not needed • lib/landmark/DetailScreen.dart:141:61
   info • Avoid using braces in interpolation when not needed • lib/landmark/DetailScreen.dart:141:68
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/landmark/DetailScreen.dart:1564:7
   info • Unused import: 'package:sanook_trips/lang/lang.dart' • lib/main.dart:3:8
   info • Unused import: 'dart:convert' • lib/main.dart:8:8
   info • Avoid using braces in interpolation when not needed • lib/main.dart:44:28
   info • Avoid using braces in interpolation when not needed • lib/screen/ImageViewScreen.dart:119:65
   info • The value of the field '_message' isn't used • lib/screen/LoginScreen.dart:17:10
   info • The method '_logOut' isn't used • lib/screen/LoginScreen.dart:71:16
   info • Unused import: 'package:flutter_html_view/flutter_html_view.dart' • lib/screen/NewsDetailScreen.dart:6:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/screen/NewsDetailScreen.dart:8:7
   info • Unused import: 'dart:async' • lib/screen/OtopDetailScreen.dart:1:8
   info • Unused import: 'package:transparent_image/transparent_image.dart' • lib/screen/OtopDetailScreen.dart:3:8
   info • The value of the local variable 'itemHeight' isn't used • lib/screen/OtopScreen.dart:113:18
   info • The value of the local variable 'itemWidth' isn't used • lib/screen/OtopScreen.dart:114:18
   info • Unused import: 'package:transparent_image/transparent_image.dart' • lib/screen/ShareCreateScreen.dart:6:8
   info • Unused import: 'package:location/location.dart' • lib/screen/ShareCreateScreen.dart:7:8
   info • Unused import: 'package:flutter/services.dart' • lib/screen/ShareCreateScreen.dart:8:8
   info • Unused import: 'package:sanook_trips/data/Place.dart' • lib/screen/ShareCreateScreen.dart:9:8
   info • Unused import: 'package:sanook_trips/API.dart' • lib/screen/ShareCreateScreen.dart:10:8
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/screen/ShareCreateScreen.dart:12:8
   info • Unused import: 'package:sanook_trips/screen/TripDetailScreen.dart' • lib/screen/ShareCreateScreen.dart:13:8
   info • Unused import: 'package:sanook_trips/models/auth.dart' • lib/screen/ShareCreateScreen.dart:14:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/screen/TripCreateScreen.dart:326:7
   info • Unused import: 'package:sanook_trips/landmark/DetailScreen.dart' • lib/screen/TripDetailScreen.dart:2:8
   info • Unused import: 'package:share/share.dart' • lib/screen/TripDetailScreen.dart:4:8
   info • Unused import: 'package:sanook_trips/data/News.dart' • lib/screen/TripDetailScreen.dart:5:8
   info • Avoid using braces in interpolation when not needed • lib/screen/TripDetailScreen.dart:299:48
   info • Avoid using braces in interpolation when not needed • lib/screen/TripDetailScreen.dart:299:66

47 issues found. (ran in 5.4s)

```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-TH)
    • Flutter version 0.5.1 at /Users/Wisit/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Wisit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (4 available)
    • SM J710F             • 31002b57a1c55345                         • android-arm • Android 7.0 (API 24)
    • Wisit Phusi’s iPhone • 539ca7a9dcbf0538cc978fb5c942e90d6c385d43 • ios         • iOS 11.4
    • iPhone X             • DB206619-452A-4663-8529-FE6E8AF41E3C     • ios         • iOS 11.4 (simulator)
    • iPad Pro (12.9-inch) • FADF9C11-A3B7-433C-8751-84059F695161     • ios         • iOS 11.4 (simulator)

• No issues found!
```
## Result
![simulator screen shot - ipad pro 12 9-inch - 2018-07-09 at 16 56 32](https://user-images.githubusercontent.com/32625530/42444399-2f374862-839a-11e8-97bf-9a21929ac32a.png)

**Comment by 9wisit** [comment]
Now, Flutter is supported.
