### ISSUE TITLE
memory_nav_test is flaky

### ISSUE THREAD

**Issue by sigurdm** [flutter/flutter#19164]
Seems to time out.

https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci83YWMxODM3OTRiNDFkZWEwYTY2YzYxZjlkOTk1YWQ2MTdiOTBjYjNiDAsSBFRhc2sYgICAgICAoAgM

```
stdout: [  +11 ms] Will connect to already running application instance.
stdout: [   +1 ms] Running driver tests.
stdout: [   +1 ms] /home/linux2/.cocoon/flutter/bin/cache/dart-sdk/bin/dart /home/linux2/.cocoon/flutter/examples/flutter_gallery/test_driver/memory_nav_test.dart --packages=/home/linux2/.cocoon/flutter/examples/flutter_gallery/.packages -rexpanded --preview-dart-2
stdout: [ +339 ms] 00:00 [32m+0[0m: flutter gallery transitions (setUpAll)[0m
stderr: [  +24 ms] [info ] FlutterDriver: Connecting to Flutter application at http://localhost:38095
stderr: [ +158 ms] [trace] FlutterDriver: Isolate found with number: 143809981
stderr: [  +91 ms] [trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
stderr: [  +30 ms] [info ] FlutterDriver: Connected to Flutter application.
stdout: [   +3 ms] 00:00 [32m+0[0m: flutter gallery transitions navigation[0m
stdout: [+5044 ms] 00:05 [32m+0[0m[31m -1[0m: flutter gallery transitions navigation [1m[31m[E][0m[0m
stdout: [   +2 ms]   DriverError: Error in Flutter application: Timeout while executing tap: TimeoutException after 0:00:05.000000: Future not completed
stdout: [        ]   #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168)
stdout: [        ]   
stdout: [        ]   #1      BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:392)
stdout: [        ]   
stdout: [        ]   #2      _runExtension (dart:developer/runtime/libdeveloper.dart:85)
stdout: [        ]   Original error: null
stdout: [        ]   Original stack trace:
stdout: [        ]   null
stdout: [  +29 ms]   package:flutter_driver/src/driver/driver.dart 366:7   FlutterDriver._sendCommand
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/future_impl.dart 22                        _Completer.completeError
stdout: [        ]   dart:async-patch/dart:async/async_patch.dart 40       _AsyncAwaitCompleter.completeError
stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055                             _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/dart:async/async_patch.dart 77       _asyncThenWrapperHelper
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 343:68  FlutterDriver._sendCommand
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 392:11  FlutterDriver.tap
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055                             _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/dart:async/async_patch.dart 77       _asyncThenWrapperHelper
stdout: [        ]   package:test/src/backend/declarer.dart 159:70         Declarer.test...
stdout: [        ]   package:test/src/backend/invoker.dart 249:15          Invoker.waitForOutstandingCallbacks.
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047                             _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964                              _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/timer.dart 52                              new Timer
stdout: [        ]   dart:async/timer.dart 87                              Timer.run
stdout: [        ]   dart:async/future.dart 172                            new Future
stdout: [        ]   package:test/src/backend/invoker.dart 402:15          Invoker._onRun...
stdout: [        ] 00:05 [32m+0[0m[31m -1[0m: flutter gallery transitions (tearDownAll)[0m
stdout: [  +21 ms] 00:05 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
stderr: [   +1 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
stderr: [        ] #0      _rootHandleUncaughtError. (dart:async/zone.dart:1114)
stderr: [        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
stderr: [        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
stderr: [        ] #3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
stderr: [        ] #4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
stderr: [        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
stdout: [  +25 ms] Leaving the application running.
stdout: [   +6 ms] "flutter drive" took 6,043ms.
stderr: Driver tests failed: 255
stderr: 
stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:26)
stderr: #1      _runTests (package:flutter_tools/src/commands/drive.dart:303)
stderr: 
stderr: #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:126)
stderr: 
stderr: #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
stderr: 
stderr: #4      FlutterCommand.run. (package:flutter_tools/src/runner/flutter_command.dart:282)
stderr: 
stderr: #5      AppContext.run. (package:flutter_tools/src/base/context.dart:142)
stderr: 
stderr: #6      _rootRun (dart:async/zone.dart:1126)
stderr: #7      _CustomZone.run (dart:async/zone.dart:1023)
stderr: #8      _runZoned (dart:async/zone.dart:1518)
stderr: #9      runZoned (dart:async/zone.dart:1465)
stderr: #10     AppContext.run (package:flutter_tools/src/base/context.dart:141)
stderr: 
stderr: #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:273)
stderr: #12     CommandRunner.runCommand (package:args/command_runner.dart:194)
stderr: 
stderr: #13     FlutterCommandRunner.runCommand. (package:flutter_tools/src/runner/flutter_command_runner.dart:322)
```

**Comment by godofredoc** [comment]
The test has been renamed, removed or we are not running it anymore.
