### ISSUE TITLE
'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19198]
I was studying about File i/o, but I got an unknown error and searching for a long time. I couldn't found at all. What is the problem? Below things are code and error message.

```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import 'dart:async';


void main() {
	runApp(
		MaterialApp(
			title: 'IO',
			home: Home(),
		)
	);
}

Future<String> get _localPath async {
	final directory = await getApplicationDocumentsDirectory();
	return directory.path;
}

Future<File> get _localFile async {
	final path = await _localPath;
	return File('$path/data.txt');
}

Future<File> writeData(String message) async {
	try{
		final file = await _localFile;
		return file.writeAsString(message);
	}catch(e) {
		return null;
	}
}

Future<String> readData() async {
	try{
		final file = await _localFile;
		String data = await file.readAsString();

		return data;
	}catch(e) {
		return "Nothing saved yet!";
	}
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {

	final _dataField = TextEditingController();


  @override
  Widget build(BuildContext context) {
    return Scaffold(
	    appBar: AppBar(
		    title: Text("Read/Write"),
		    centerTitle: true,
		    backgroundColor: Colors.greenAccent,
	    ),
	    body: Container(
		    padding: const EdgeInsets.all(13.4),
		    alignment: Alignment.topCenter,
		    child: ListTile(
			    title: TextField(
				    controller: _dataField,
				    decoration: InputDecoration(
					    labelText: "Write something"
				    ),
			    ),
			    subtitle: FlatButton(
				    onPressed: (){
				    	// save to file
				    },
				    child: Column(
					    children: <Widget>[
					    	Text("Save data"),
						    Padding(padding: const EdgeInsets.all(14.5)),
						    Text("Saved data goes here")
					    ],
				    ),
			    ),
		    ),
	    ),
    );
  }
}
```

```
Launching lib\main.dart on SM G955N in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(24323): onResume setting current activity to this
Syncing files to device SM G955N...
I/flutter (24323): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (24323): The following assertion was thrown during performLayout():
I/flutter (24323): not implemented
I/flutter (24323): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (24323): 
I/flutter (24323): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24323): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24323): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24323):   https://github.com/flutter/flutter/issues/new
I/flutter (24323): 
I/flutter (24323): When the exception was thrown, this was the stack:
I/flutter (24323): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (24323): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (24323): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (24323): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (24323): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (24323): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (24323): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (24323): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (24323): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (24323): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (24323): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (24323): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (24323): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (24323): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (24323): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (24323): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (24323): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (24323): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (24323): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:778:32)
I/flutter (24323): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (24323): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (24323): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (24323): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (24323): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (24323): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (24323): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (24323): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (24323): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter (24323): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (24323): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (24323): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (24323): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (24323): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (24323): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (24323): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (24323): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (24323): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (24323): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (24323): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (24323): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (24323): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (24323): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (24323): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (24323): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (24323): 
I/flutter (24323): The following RenderObject was being processed when the exception was fired:
I/flutter (24323):   _RenderListTile#22f65 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (24323):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (24323):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
I/flutter (24323):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (24323):   constraints: BoxConstraints(0.0<=w<=352.6, 0.0<=h<=690.9)
I/flutter (24323):   size: MISSING
I/flutter (24323): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (24323):   RenderSemanticsAnnotations#f9872 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (24323):     RenderIgnorePointer#9caa3 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (24323):       RenderPointerListener#a9ba9 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (24323):         _RenderDecoration#9bc12 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (24323):           RenderRepaintBoundary#0b3e8 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (24323):           RenderTransform#5429e relayoutBoundary=up12 NEEDS-PAINT
I/flutter (24323):           RenderConstrainedBox#e66f1 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (24323):           RenderCustomPaint#57156 NEEDS-PAINT
I/flutter (24323):   RenderSemanticsAnnotations#e636e relayoutBoundary=up8 NEEDS-PAINT
I/flutter (24323):     RenderConstrainedBox#567fe relayoutBoundary=up9 NEEDS-PAINT
I/flutter (24323):       RenderClipPath#21085 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (24323):         RenderCustomPaint#b5a07 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (24323):           _RenderInkFeatures#efe08 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (24323): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24323): Another exception was thrown: RenderBox was not laid out: _RenderListTile#22f65 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (24323): Another exception was thrown: RenderBox was not laid out: RenderPadding#81995 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (24323): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#30afb relayoutBoundary=up5 NEEDS-PAINT
I/flutter (24323): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#4e973 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (24323): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
D/libGLESv2(24323): STS_GLApi : DTS, ODTC are not allowed for Package : com.haram.flutterapp
V/InputMethodManager(24323): Starting input: tba=android.view.inputmethod.EditorInfo@ba597e1 nm : com.haram.flutterapp ic=null
I/InputMethodManager(24323): startInputInner - mService.startInputOrWindowGainedFocus
D/SurfaceView(24323): BG show() Surface(name=Background for - SurfaceView - com.haram.flutterapp/com.haram.flutterapp.MainActivity@a226ed7@0) io.flutter.view.FlutterView{a226ed7 VFE...... .F...... 0,0-1080,2094}
D/SurfaceView(24323): surfaceDestroyed 1 io.flutter.view.FlutterView{a226ed7 VFE...... .F...... 0,0-1080,2094}
D/ViewRootImpl@498b071[MainActivity](24323): performDraw() was skipped by AOD_SHOW_STATE... DisplayState=3
D/ViewRootImpl@498b071[MainActivity](24323): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(24323): BG show() Surface(name=Background for - SurfaceView - com.haram.flutterapp/com.haram.flutterapp.MainActivity@a226ed7@0) io.flutter.view.FlutterView{a226ed7 VFE...... .F...... 0,0-1080,2094}
D/OpenGLRenderer(24323): eglDestroySurface = 0x752001ddc0
D/ViewRootImpl@498b071[MainActivity](24323): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={valid=false 0} changed=true
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by baeharam** [comment]
@zoechi I resolved, cannot add subtitle to FlatButton

**Comment by zoechi** [comment]
Great. I think the error behavior should be improved though.

**Comment by zoechi** [comment]
Looks like a dup of #18755
