### ISSUE TITLE
Strange behaviour of CrossAxisAlignment in Rows

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#19203]
Hi,

The full repro project can be found at 

https://github.com/escamoteur/flutter_bug_repro/tree/cross_axis_in_row

I encountered some strange effects using a Row:

```Dart
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          centerTitle: true,
          backgroundColor: Colors.white,
          elevation: 0.0,
          title: Text("Event Details"),
        ),
        body: SingleChildScrollView(
          child: Container(
            color: const Color(0xffE5E5E5),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Text('Heder'),
                SizedBox(
                  height: 10.0,
                ),
                Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.blue, width: 5.0),
                      borderRadius: BorderRadius.only(topLeft: Radius.circular(5.0)),
                    ),
                  ),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        EventInfoBlock(title: "Block1", children: <Widget>[                        
                        Text('SomeText'),
                        Text('SomeText'),
                        Text('SomeText'),
                        Text('SomeText'),
                        Text('SomeText'),
                        ]),
                      ],
                    ),
                  ),
                ]),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class EventInfoBlock extends StatelessWidget {
  final String title;
  final List<Widget> children;

  const EventInfoBlock({
    Key key,
    this.title,
    this.children,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<Widget> rows = [
      Text(
        title,
        style: Theme.of(context).textTheme.caption,
      ),
      SizedBox(
        height: 10.0,
      ),
      Padding(
          padding: const EdgeInsets.only(left: 10.0, right: 20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: children,
          ))
    ];

    return Container(
      margin: const EdgeInsets.only(bottom: 10.0),
      padding: const EdgeInsets.all(15.0),
      color: Colors.white,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: rows,
      ),
    );
  }
```

Produces
![image](https://user-images.githubusercontent.com/16635729/42504904-739b23cc-843d-11e8-962c-8b9c5ebe4726.png)

Why isn't the blue container stretched vertically? I think it normally takes all available space?

If I change to `crossAxisAlignment: CrossAxisAlignment.stretch`

```Dart
                Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
                  Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.blue, width: 5.0),
                      borderRadius: BorderRadius.only(topLeft: Radius.circular(5.0)),
                    ),
                  ),
```

I get this exception:

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
D/        ( 7696): HostConnection::get() New Host Connection established 0xb2688600, tid 7716
D/EGL_emulation( 7696): eglMakeCurrent: 0xa4e24340: ver 3 1 (tinfo 0xb2683200)
I/flutter ( 7696): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7696): The following assertion was thrown during performLayout():
I/flutter ( 7696): BoxConstraints forces an infinite height.
I/flutter ( 7696): These invalid constraints were provided to RenderDecoratedBox's layout() function by the following
I/flutter ( 7696): function, which probably computed the invalid constraints in question:
I/flutter ( 7696):   RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 7696): The offending constraints were:
I/flutter ( 7696):   BoxConstraints(0.0<=w<=Infinity, h=Infinity)
I/flutter ( 7696):
I/flutter ( 7696): When the exception was thrown, this was the stack:
I/flutter ( 7696): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:514:9)
I/flutter ( 7696): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:557:21)
I/flutter ( 7696): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:561:6)
I/flutter ( 7696): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1485:24)
I/flutter ( 7696): #4      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 7696): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 7696): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #10     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:479:13)
I/flutter ( 7696): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #28     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 7696): #29     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter ( 7696): #30     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 7696): #31     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 7696): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1147:11)
I/flutter ( 7696): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #38     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 7696): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #55     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2824:13)
I/flutter ( 7696): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #57     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 7696): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #59     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 7696): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 7696): #71     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter ( 7696): #72     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 7696): #73     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
I/flutter ( 7696): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 7696): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 7696): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 7696): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7696): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7696): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 7696): #81     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 7696): #82     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 7696): #83     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 7696): (elided one frame from package dart:async)
I/flutter ( 7696):
I/flutter ( 7696): The following RenderObject was being processed when the exception was fired:
I/flutter ( 7696):   RenderFlex#2d17b relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):   creator: Row ← Column ← DecoratedBox ← Container ← _SingleChildViewport ← _ScrollableScope ←
I/flutter ( 7696):   IgnorePointer-[GlobalKey#a0ac9] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 7696):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#20d7d] ←
I/flutter ( 7696):   _ExcludableScrollSemantics-[GlobalKey#5ba09] ← ⋯
I/flutter ( 7696):   parentData: offset=Offset(0.0, 26.0); flex=null; fit=null (can use size)
I/flutter ( 7696):   constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
I/flutter ( 7696):   size: Size(360.0, 144.0)
I/flutter ( 7696):   direction: horizontal
I/flutter ( 7696):   mainAxisAlignment: start
I/flutter ( 7696):   mainAxisSize: max
I/flutter ( 7696):   crossAxisAlignment: stretch
I/flutter ( 7696):   textDirection: ltr
I/flutter ( 7696):   verticalDirection: down
I/flutter ( 7696): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 7696):   RenderDecoratedBox#bcf30 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):     RenderPadding#27c5d relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):       RenderLimitedBox#14271 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):         RenderConstrainedBox#1003f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):   RenderFlex#38c29 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):     RenderPadding#61270 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):       RenderDecoratedBox#030c4 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):         RenderPadding#ce0c7 relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696):           RenderFlex#4b691 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7696): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 2 of 396 libraries in 476ms.
Reloaded 2 of 396 libraries in 332ms.
```

I found out that if I wrap the `Row` with an `IntrinsicHeight` the Container stretches even with `CrossAxisAlignment.start` and with center it doesn't throw an exception.

![image](https://user-images.githubusercontent.com/16635729/42505213-682a04f8-843e-11e8-8f5d-4139e37c87fd.png)

Is this the correct behavior?

**Comment by AbdulRahmanAlHamali** [comment]
I think this is the correct behaviour, because your row is placed inside a SingleChildScrollView, which basically has an infinite height and can get as big as the child requires.

So when a row sets the crossAxisAlignment to stretch, it is asking to take all the available vertical space, but the available vertical space is infinite, which will cause this exception

**Comment by gmaggio** [comment]
One would definitely expected it to take all the available space of the **direct parent**, though. Taking the space of the **top most parent** seems to be somewhat counter intuitive.

**Comment by shubhamhackz** [comment]
CrossAxisAligment isn't working either in Flex,Row or Column. If we have an option of assigning CrossAxisAligment then it should take whole Space vertically in a row if we have declared 
crossAxisAligment: CrossAxisAligment.stretch

**Comment by chunhtai** [comment]
@gmaggio Do you have a runnable example that can reproduce it? I didn't see the behavior you mentioned.

@shubhamhackz I do see the CrossAxisAligment.stretch will take the whole vertically space if its parent has a limited height. Do you have a runnable example as well?

**Comment by bestkanthed** [comment]
same issue

**Comment by chunhtai** [comment]
> same issue

Can you provide more details? an running example will be good

**Comment by bestkanthed** [comment]
I somehow solved it. I don't remeber how exactly.

**Comment by chunhtai** [comment]
Usually this happen when there is no height or width limit specify in parent. In this case, there is no clear definition on what the correct behavior should be, thus we throw the assertion.

Feel free to report back if you remember something that is different from above case.
