### ISSUE TITLE
Flutter upgrade crash report of failed to download artifacts.zip

### ISSUE THREAD

**Issue by franklzt** [flutter/flutter#19248]
Just upgrade the flutter and I am in China. it report the crash.

## Logs
Flutter crash report; please file at https://github.com/flutter/flutter/issues.
## command

flutter packages get

## exception

HttpException: HttpException: , uri = https://storage.googleapis.com/flutter_infra/flutter/ce06bbac58d7c68487dd09616864c904e2f71a72/windows-x64/artifacts.zip

```
#0      _attempt (package:flutter_tools/src/base/net.dart:55)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:564)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:298)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:324)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:295)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:311)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:483)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:258)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:214)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:331)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:282)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     _runZoned (dart:async/zone.dart:1518)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:273)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:322)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     _runZoned (dart:async/zone.dart:1518)
#25     runZoned (dart:async/zone.dart:1465)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:278)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#29     new Future.sync (dart:async/future.dart:222)
#30     CommandRunner.run (package:args/command_runner.dart:109)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:187)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     _runZoned (dart:async/zone.dart:1518)
#37     runZoned (dart:async/zone.dart:1465)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:42)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:50)
#41     main (package:flutter_tools/executable.dart:50)
<asynchronous suspension>
#42     main (file:///D:/GithubExample/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

**Comment by zoechi** [comment]
Did you follow https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?

**Comment by franklzt** [comment]
thanks.
