### ISSUE TITLE
Assert when calling setState - unclear what the issue is

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1925]
```dart
android: --------- beginning of main
android: --------- beginning of system
android: I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
android: I/flutter : Exception caught while building LayoutId-<info about widget and id>
android: I/flutter : 'packages/flutter/src/widgets/framework.dart': Failed assertion: line 1097: '() {
android: I/flutter :           if (_debugBuilding) {
android: I/flutter :             bool foundTarget = false;
android: I/flutter :             visitAncestorElements((Element element) {
android: I/flutter :                   if (element == _debugCurrentBuildTarget) {
android: I/flutter :                     foundTarget = true;
android: I/flutter :                     return false;
android: I/flutter :                   }
android: I/flutter :                   return true;
android: I/flutter :                 });
android: I/flutter :             if (foundTarget)
android: I/flutter :             return true;
android: I/flutter :           }
android: I/flutter :           return !_debugStateLocked || (_debugAllowIgnoredCallsToMarkNeedsBuild && dirty);
android: I/flutter :         }' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      BuildableElement.markNeedsBuild (packages/flutter/src/widgets/framework.dart:1097)
android: I/flutter : #2      State.setState (packages/flutter/src/widgets/framework.dart:353)

```

**Comment by apwilson** [comment]
The problem seems to have been calling a callback in initState that triggers a setState on a different class.

**Comment by abarth** [comment]
Do you have a test case that triggers this assert?

**Comment by apwilson** [comment]
I'm not sure if I can get a reduced test case but I can reliably reproduce for you.  Need a reduced test case?

**Comment by apwilson** [comment]
Reduced testcase:

```dart

class A extends StatefulComponent {
  A() : super(key: new GlobalKey());
  AState createState() => new AState();
}

class AState extends State<A> {
  B b;
  void addB(B b) {
    setState(() {
      this.b = b;
    });
  }

  void refresh() {
    setState(() {});
  }

  Widget build(_) {
    return new Container(
        decoration: new BoxDecoration(backgroundColor: new Color(0xFFFF00FF)),
        child: b);
  }
}

class B extends StatefulComponent {
  final Function onInitState;
  B(this.onInitState);
  BState createState() => new BState();
}

class BState extends State<B> {
  void initState() {
    super.initState();
    config.onInitState();
  }

  Widget build(_) {
    return new Container(
        width: 100.0,
        height: 100.0,
        decoration: new BoxDecoration(backgroundColor: new Color(0xFFFFFF00)));
  }
}

void main() {
  A a = new A();
  new Timer(const Duration(seconds: 1), () {
    (a.key as GlobalKey).currentState.addB(new B(() {
      (a.key as GlobalKey).currentState.refresh();
    }));
  });
  runApp(a);
}
```

**Comment by Hixie** [comment]
The assertion is telling you that you're calling setState from within initState.

But yeah, we should improve the way we report that to match the more useful style we've been moving to.
