### ISSUE TITLE
File names could be shortened a bit in casual stack traces when shown in IDEs

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#19291]
_From @mit-mit on March 7, 2017 15:43_

File names take up a lot of space in casual stack traces:

```
#0      doWork.<doWork_async_body> (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart:5:5)
<asynchronous suspension>
#1      doWork (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart)
#2      doWork.<doWork_async_body> (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart:8:9)
<asynchronous suspension>
#3      doWork (file:///Users/johnmccutchan/workspace/stacktrace_demos/lib/recursive_timer.dart)

```

Would be great if we could shorten them a bit.

_Copied from original issue: dart-lang/sdk#28979_

**Comment by devoncarew** [comment]
_From @zanderso on March 7, 2017 15:52_

@johnmccutchan

**Comment by devoncarew** [comment]
_From @rmacnak-google on June 28, 2018 0:52_

The Dart standard requires StackTrace.toString() to report function activations exactly: no omitted frames (e.g., from inlining), no synthetic frames, no obfuscation, and precise source locations. The base stack traces should not be lossy.

**Comment by devoncarew** [comment]
_From @mit-mit on June 28, 2018 8:47_

Sure, but surely that doesn't prevent us from post-processing it to make it more usable to the developer when used in a tooling context?

**Comment by devoncarew** [comment]
_From @zanderso on June 28, 2018 15:11_

@mit-mit If the idea is to post-process with tooling, would you mind editing the issue title and/or applying the right labels for that? Thanks!

**Comment by devoncarew** [comment]
_From @mit-mit on June 29, 2018 10:32_

cc @devoncarew should this actually be in the tools tracker?

**Comment by devoncarew** [comment]
We do some work in the flutter framework to make traces more appealing, and may do as well in flutter_tools. If we move this issue over, it would be nice to first verify that traces aren't already post-processed.

**Comment by devoncarew** [comment]
_From @dgrove on July 11, 2018 15:34_

@devoncarew can you please apply the right area tag for this? (it's not clear to me where this should land)

**Comment by devoncarew** [comment]
I'll move this to the flutter repo.

**Comment by zoechi** [comment]
Are you still seeing this?

Stack traces look like 
(from https://github.com/flutter/flutter/issues/27029)
```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone XS Max is available at: http://127.0.0.1:8182/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Title(title: "Flutter Gallery", color:
flutter: MaterialColor(primary value: Color(0xff9e9e9e))):
flutter: 'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 2181 pos 12:
flutter: 'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart:2181:12)
flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
```
