### ISSUE TITLE
Compiler messages in thrown exceptions are duplicated.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19314]
When there is a compilation error in a running program, the exception that is thrown, and what shows up on the device screen, print the same error line twice, when it should only print it once.

For instance, the following program has exactly one line with an error, but it prints the following twice:

```
I/flutter ( 1963):     return const Placeholder(bogus: 1.0);
I/flutter ( 1963):                              ^
I/flutter ( 1963):     return const Placeholder(bogus: 1.0);
I/flutter ( 1963):                              ^
```

Here's the whole output:

```
compiler message: lib/main.dart:9:30: Error: No named parameter with the name 'bogus'.
compiler message:     return const Placeholder(bogus: 1.0);
compiler message:                              ^^^^^
compiler message: file:///usr/local/google/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/placeholder.dart:54:9: Context: Found this candidate, but the arguments don't match.
compiler message:   const Placeholder({
compiler message:         ^
I/flutter ( 1963): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1963): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter ( 1963): 'file:///usr/local/google/home/gspencer/code/mytest/lib/main.dart': error: line 9 pos 30:
I/flutter ( 1963): lib/main.dart:9:30: Error: No named parameter with the name 'bogus'.
I/flutter ( 1963):     return const Placeholder(bogus: 1.0);
I/flutter ( 1963):                              ^
I/flutter ( 1963):     return const Placeholder(bogus: 1.0);
I/flutter ( 1963):                              ^
I/flutter ( 1963): 
I/flutter ( 1963): When the exception was thrown, this was the stack:
I/flutter ( 1963): #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3708:28)
I/flutter ( 1963): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter ( 1963): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 1963): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 1963): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 1963): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 1963): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 1963): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 1963): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 1963): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 1963): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 1963): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 1963): (elided one frame from package dart:async)
I/flutter ( 1963): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

And here's the test program (pasted into a newly created flutter app):

```dart
import 'package:flutter/widgets.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const Placeholder(bogus: 1.0);
  }
}
```

**Comment by goderbauer** [comment]
Looks like this is no longer an issue. It now prints something more reasonable:

```
Compiler message:
lib/main.dart:9:30: Error: No named parameter with the name 'bogus'.
    return const Placeholder(bogus: 1.0);
                             ^^^^^
file:///Users/goderbauer/dev/flutter/packages/flutter/lib/src/widgets/placeholder.dart:54:9: Context: Found this candidate, but the arguments don't match.
  const Placeholder({
        ^
Compiler failed on /Users/goderbauer/dev/elevation/lib/main.dart
```
