### ISSUE TITLE
"NoSuchMethodError: The getter 'pathSegments' was called on null." in service_extensions_test.dart

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19320]
Saw this flake on the linux infrabot:

```
03:53 +344: /b/build/slave/Linux/build/flutter/packages/flutter/test/foundation/service_extensions_test.dart: Service extensions - posttest                                                            
unhandled error during test:
/b/build/slave/Linux/build/flutter/packages/flutter/test/foundation/service_extensions_test.dart
NoSuchMethodError: The getter 'pathSegments' was called on null.
Receiver: null
Tried calling: pathSegments
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      collect (package:coverage/src/collect.dart:16)
<asynchronous suspension>
#2      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:59)
<asynchronous suspension>
#3      CoverageCollector.onFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27)
<asynchronous suspension>
#4      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:611)
<asynchronous suspension>
#5      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:367)
#6      PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65)
<asynchronous suspension>
#7      Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:248)
<asynchronous suspension>
#8      new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89)
<asynchronous suspension>
#9      invoke (package:test/src/utils.dart:242)
#10     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88)
#11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403)
<asynchronous suspension>
#12     new Future.<anonymous closure> (dart:async/future.dart:174)
#13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
#14     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#15     _rootRun (dart:async/zone.dart:1122)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209)
#20     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

03:53 +345: /b/build/slave/Linux/build/flutter/packages/flutter/test/foundation/service_extensions_test.dart: Service extensions - posttest                                                            
03:53 +345 -1: loading /b/build/slave/Linux/build/flutter/packages/flutter/test/foundation/service_extensions_test.dart [E]                                                                            
  NoSuchMethodError: The getter 'pathSegments' was called on null.
  Receiver: null
  Tried calling: pathSegments
  package:flutter_tools/src/test/flutter_platform.dart 652  _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                            _Completer.completeError
  dart:async-patch/dart:async/async_patch.dart 40           _AsyncAwaitCompleter.completeError
  package:flutter_tools/src/test/flutter_platform.dart      _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                 _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77           _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart 374  _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 367  _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 65           PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                 _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77           _asyncThenWrapperHelper
  package:test/src/runner/loader.dart 242                   Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89                new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                 _CustomZone.registerCallback
  dart:async/zone.dart 964                                  _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                  new Timer
  dart:async/timer.dart 87                                  Timer.run
  dart:async/future.dart 172                                new Future
  package:test/src/backend/invoker.dart 402                 Invoker._onRun.<fn>.<fn>.<fn>
  
```

**Comment by tvolkert** [comment]
Dup of https://github.com/flutter/flutter/issues/16839?

**Comment by Hixie** [comment]
yeah
