### ISSUE TITLE
Running test from IntelliJ crashes, `flutter test` works

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#19340]
```
dart:async/stream_controller.dart 594:43                     _StreamController.addError
dart:async/stream_controller.dart 862:13                     _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 140:14     _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 131:5      _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 454:29  _FlutterPlatform._startTest.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback
dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest.<fn>
package:flutter_tools/src/test/flutter_platform.dart 630:26  _FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback
dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest
package:flutter_tools/src/test/flutter_platform.dart 367:36  _FlutterPlatform.loadChannel
package:test/src/runner/plugin/platform.dart 65:19           PlatformPlugin.load
===== asynchronous gap ===========================
dart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback
dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
package:test/src/runner/loader.dart                          Loader.loadFile.<fn>
package:test/src/runner/load_suite.dart 89:31                new LoadSuite.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1047:19                                 _CustomZone.registerCallback
dart:async/zone.dart 964:22                                  _CustomZone.bindCallbackGuarded
dart:async/timer.dart 52:45                                  new Timer
dart:async/timer.dart 87:9                                   Timer.run
dart:async/future.dart 172:11                                new Future
package:test/src/backend/invoker.dart 402:15                 Invoker._onRun.<fn>.<fn>.<fn>

Shell subprocess crashed with segmentation fault after tests finished.
Test: /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/test/localization/localizations_test.dart
Shell: /Users/zoechi/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester
```

![image](https://user-images.githubusercontent.com/405837/42685676-ef648dba-8693-11e8-9c2a-b84abadf2e80.png)

![image](https://user-images.githubusercontent.com/405837/42685697-fc943972-8693-11e8-8880-4e178328627e.png)

[✓] Flutter (Channel master, v0.5.7-pre.111, on Mac OS X 10.13.5 17F77, locale en-AT)
    • Flutter version 0.5.7-pre.111 at /Users/zoechi/flutter/flutter
    • Framework revision 7ebf2728dc (12 hours ago), 2018-07-12 14:59:22 -0700
    • Engine revision fed2ea458e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

This worked with `master` channel from yesterday.

**Comment by DanTup** [comment]
Maybe related:

https://github.com/flutter/flutter/issues/17989

It came up previously and the change was reverted. I don't know if it's been re-applied and the underlying issue still remains (cc @aam @mravn-google).

**Comment by pulyaevskiy** [comment]
Just got the same error after upgrading to the latest Flutter from master:

Flutter (Channel master, v0.5.7-pre.115, on Mac OS X 10.13.5 17F77, locale en-BY)

Looks like IDEA crashes only when running tests in debug mode (with observatory?)

**Comment by DanTup** [comment]
Yeah, that's what I noticed in the linked issue - only happened when I had a breakpoint.

**Comment by aam** [comment]
@DanTup wrote

> Maybe related:
> #17989

That issue was about sync-async only partially enabled(enabled in vm, but not enabled in frontend). Now it's enabled everywhere.

@pulyaevskiy wrote
> Looks like IDEA crashes only when running tests in debug mode (with observatory?)

Running tests in Flutter Gallery seems to work fine. Do folks have a sample app where the problem can be reproduced?

**Comment by pulyaevskiy** [comment]
@aam 
Sorry I forgot to mention that tests should be run in debug mode and there needs to be a breakpoint.

I was able to reproduce this in flutter_gallery just now:
![image](https://user-images.githubusercontent.com/441756/42727149-14e28f2a-8756-11e8-9d5b-d7afb32dde3d.png)

I can reproduce this from the CLI as well by adding a breakpoint via Observatory UI.

Command:

```shell
/Users/anatoly/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "Flutter Gallery drawer item test" test/drawer_test.dart
```

Then go to observatory, add a breakpoint in that test and resume with `F7`. I got following output:

```
{"protocolVersion":"0.1.0","runnerVersion":"0.12.41","type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/anatoly/flutter/examples/flutter_gallery/test/drawer_test.dart"},"type":"suite","time":7}
{"test":{"id":1,"name":"loading /Users/anatoly/flutter/examples/flutter_gallery/test/drawer_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":9}
{"count":1,"type":"allSuites","time":13}

[{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:53054/"}}]
{"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":32212}
{"test":{"id":3,"name":"Flutter Gallery drawer item test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":66,"column":3,"url":"package:flutter_test/src/widget_tester.dart","root_line":15,"root_column":3,"root_url":"file:///Users/anatoly/flutter/examples/flutter_gallery/test/drawer_test.dart"},"type":"testStart","time":32213}
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":32217}
{"testID":1,"error":"Shell subprocess crashed with segmentation fault after tests finished.\nTest: /Users/anatoly/flutter/examples/flutter_gallery/test/drawer_test.dart\nShell: /Users/anatoly/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester\n\n","stackTrace":"dart:async/stream_controller.dart 594:43                     _StreamController.addError\ndart:async/stream_controller.dart 862:13                     _StreamSinkWrapper.addError\npackage:stream_channel/src/guarantee_channel.dart 140:14     _GuaranteeSink._addError\npackage:stream_channel/src/guarantee_channel.dart 131:5      _GuaranteeSink.addError\npackage:flutter_tools/src/test/flutter_platform.dart 454:29  _FlutterPlatform._startTest.<fn>\n===== asynchronous gap ===========================\ndart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback\ndart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper\npackage:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest.<fn>\npackage:flutter_tools/src/test/flutter_platform.dart 630:26  _FlutterPlatform._startTest\n===== asynchronous gap ===========================\ndart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback\ndart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper\npackage:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest\npackage:flutter_tools/src/test/flutter_platform.dart 367:36  _FlutterPlatform.loadChannel\npackage:test/src/runner/plugin/platform.dart 65:19           PlatformPlugin.load\n===== asynchronous gap ===========================\ndart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback\ndart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper\npackage:test/src/runner/loader.dart                          Loader.loadFile.<fn>\npackage:test/src/runner/load_suite.dart 89:31                new LoadSuite.<fn>.<fn>\n===== asynchronous gap ===========================\ndart:async/zone.dart 1047:19                                 _CustomZone.registerCallback\ndart:async/zone.dart 964:22                                  _CustomZone.bindCallbackGuarded\ndart:async/timer.dart 52:45                                  new Timer\ndart:async/timer.dart 87:9                                   Timer.run\ndart:async/future.dart 172:11                                new Future\npackage:test/src/backend/invoker.dart 402:15                 Invoker._onRun.<fn>.<fn>.<fn>\n","isFailure":false,"type":"error","time":32578}
{"testID":3,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":32588}
{"success":false,"type":"done","time":32601}
```

**Comment by aam** [comment]
Thanks @pulyaevskiy  for the repro steps!

> @DanTup wrote

> > Maybe related:
> > #17989
> That issue was about sync-async only partially enabled(enabled in vm, but not enabled in frontend). It > is enabled now both in vm and in frontend.

Or so I thought! It seems that with enabling dart2 by default we once again have sync_async is inconsistently set: it is enabled in frontend compiler, but is disabled in dart vm that runs in the engine.

cc @a-siva

**Comment by zoechi** [comment]
Can't reproduce anymore.
Does someone still see this or should we close?

**Comment by DanTup** [comment]
This was fixed some time ago, and we have [tests covering it](https://github.com/flutter/flutter/blob/cf764e301240d05741bdf2437cd437d63e2912c6/packages/flutter_tools/test/integration/lifetime_test.dart#L37-L47) now (which pass on macOS/Linux but are skipped on Windows - something I think I can address today).

**Comment by JalalMirzayev** [comment]
I am running on Windows 10 (IntelliJ Community 2020.1.2). Flutter version 1.18.0-11.1.pre at C:\idea\projects\flutter\sdk\flutter
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta).

I tried to run a standard test and I get a similar error.

```
Testing started at 21:48 ...
C:\idea\projects\flutter\sdk\flutter\bin\flutter.bat --no-color test --machine test\counter_test.dart
Waiting for another flutter command to release the startup lock...
Shell: [ERROR:flutter/shell/testing/tester_main.cc(301)] Unhandled exception
Shell: Exception: WebSocketException: Connection to 'http://127.0.0.1:62253#' was not upgraded to websocket
Shell: Stack trace: #0      _WebSocketImpl.connect.<anonymous closure>.error (dart:_http/websocket_impl.dart:1057:9)
Shell: #1      _WebSocketImpl.connect.<anonymous closure> (dart:_http/websocket_impl.dart:1066:14)
Shell: #2      _rootRunUnary (dart:async/zone.dart:1192:38)
Shell: #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
Shell: #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
Shell: #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
Shell: #6      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
Shell: #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
Shell: #8      Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
Shell: #9      _rootRunUnary (dart:async/zone.dart:1192:38)
Shell: #10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
Shell: #11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
Shell: #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
Shell: #13     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
Shell: #14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
Shell: #15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
Shell: #16     _rootRun (dart:async/zone.dart:1184:13)
Shell: #17     _CustomZone.run (dart:async/zone.dart:1077:19)
Shell: #18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
Shell: #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
Shell: #20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
Shell: #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
Shell: 
dart:async/stream_controller.dart 609:43                       _StreamController.addError
dart:async/stream_controller.dart 877:13                       _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14       _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5        _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 567:27    FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart 369:36    FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 322:46    FlutterPlatform.load
package:test_core/src/runner/loader.dart 232:38                Loader.loadFile.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                       Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31             new LoadSuite.<fn>.<fn>
package:test_core/src/runner/load_suite.dart 108:8             new LoadSuite.<fn>
package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
dart:async/future.dart 176:37                                  new Future.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
dart:async/timer.dart 54:45                                    new Timer
dart:async/timer.dart 91:9                                     Timer.run
dart:async/future.dart 174:11                                  new Future
package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 148:7                Invoker.guard
package:test_api/src/backend/invoker.dart 436:15               Invoker._guardIfGuarded
package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:stack_trace/src/chain.dart 99:12                       Chain.capture
package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
dart:async/future.dart 202:37                                  new Future.microtask.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
dart:isolate-patch/timer_impl.dart 405:11                      _Timer._runTimers
dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

Failed to load "C:\idea\projects\flutter\flutter_development_show_01\test\counter_test.dart":
Shell subprocess cleanly reported an error before connecting to test harness. Check the logs above for an error message.
Test: C:\idea\projects\flutter\flutter_development_show_01\test\counter_test.dart
Shell: C:\idea\projects\flutter\sdk\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe 
```
