### ISSUE TITLE
VM Service extensions crash the Flutter VM

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#19354]
## Steps to Reproduce

Modify any ext.flutter. service extension to throw an exception 
For example modify the debugPaint service extension as follows:

```dart
      registerBoolServiceExtension(
        name: 'debugPaint',
        getter: () async => debugPaintSizeEnabled,
        setter: (bool value) {
          throw Exception("Throwing an exception here shouldn't crash"); // new line.
          if (debugPaintSizeEnabled == value)
            return new Future<Null>.value();
          debugPaintSizeEnabled = value;
          return _forceRepaint();
        }
      );

```
Trigger the service extension either from flutter tool or from intellij.
From flutter tool, press 'p' to trigger this extension.

From intellij you just get a crash in C++ code. With flutter tool you get a bit more information.
Example

```
flutter (20275): service extension method received: ext.flutter.debugPaint({isolateId: isolates/113087773})
I/flutter (20275): Action "Wait for outer event loop" took 0:00:00.003126
I/flutter (20275): service extension method received: ext.flutter.debugPaint({enabled: true, isolateId: isolates/113087773})
I/flutter (20275): Action "Wait for outer event loop" took 0:00:00.000373
I/flutter (20275): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter (20275): The following _Exception was thrown during a service extension callback for
I/flutter (20275): "ext.flutter.debugPaint":
I/flutter (20275): Exception: Throwing an exception here shouldn't crash
I/flutter (20275): 
I/flutter (20275): When the exception was thrown, this was the stack:
I/flutter (20275): #0      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initServiceExtensions.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/binding.dart:63:11)
I/flutter (20275): #1      BindingBase.registerBoolServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:283:23)
I/flutter (20275): <asynchronous suspension>
I/flutter (20275): #2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:392:32)
I/flutter (20275): <asynchronous suspension>
I/flutter (20275): #3      _runExtension (dart:developer/runtime/libdeveloper.dart:85:23)
I/flutter (20275): ════════════════════════════════════════════════════════════════════════════════════════════════════
Error -32000 received from application: Server error
JSON-RPC error -32000: Server error
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 68:15                 Peer.sendRequest
package:flutter_tools/src/vmservice.dart 293:13        VMService._sendRequest
package:flutter_tools/src/vmservice.dart 842:12        VM.invokeRpcRaw
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 1111:15       Isolate.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 1240:20       Isolate.invokeFlutterExtensionRpcRaw
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 1274:21       Isolate._flutterToggle
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 1284:72       Isolate.flutterToggleDebugPaintSizeEnabled
package:flutter_tools/src/resident_runner.dart 213:28  FlutterDevice.toggleDebugPaintSizeEnabled
===== asynchronous gap ===========================
package:flutter_tools/src/resident_runner.dart 532:20  ResidentRunner._debugToggleDebugPaintSizeEnabled
===== asynchronous gap ===========================
package:flutter_tools/src/resident_runner.dart 714:15  ResidentRunner._commonTerminalInputHandler
===== asynchronous gap ===========================
package:flutter_tools/src/resident_runner.dart 758:34  ResidentRunner.processTerminalInput
===== asynchronous gap ===========================
dart:async/zone.dart 1134:38                           _rootRunUnary
dart:async/zone.dart 1031:19                           _CustomZone.runUnary
dart:async/zone.dart 933:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/broadcast_stream_controller.dart 379:20     _SyncBroadcastStreamController._sendData
dart:async/broadcast_stream_controller.dart 254:5      _BroadcastStreamController.add
dart:async/broadcast_stream_controller.dart 480:11     _AsBroadcastStreamController.add
dart:async/zone.dart 1134:38                           _rootRunUnary
dart:async/zone.dart 1031:19                           _CustomZone.runUnary
dart:async/zone.dart 933:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_transformers.dart 68:11              _SinkTransformerStreamSubscription._add
dart:async/stream_transformers.dart 15:11              _EventSinkWrapper.add
dart:convert/string_conversion.dart 268:11             _StringAdapterSink.add
dart:convert/string_conversion.dart 273:7              _StringAdapterSink.addSlice
dart:convert/string_conversion.dart 348:20             _Utf8ConversionSink.addSlice
dart:convert/ascii.dart 280:17                         _ErrorHandlingAsciiDecoderSink.addSlice
dart:convert/ascii.dart 266:5                          _ErrorHandlingAsciiDecoderSink.add
dart:convert/chunked_conversion.dart 86:18             _ConverterStreamEventSink.add
dart:async/stream_transformers.dart 120:24             _SinkTransformerStreamSubscription._handleData
dart:async/zone.dart 1134:38                           _rootRunUnary
dart:async/zone.dart 1031:19                           _CustomZone.runUnary
dart:async/zone.dart 933:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 763:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 639:7                _StreamController._add
dart:async/stream_controller.dart 585:5                _StreamController.add
dart:io/runtime/binsocket_patch.dart 1714:41           _Socket._onData
dart:async/zone.dart 1138:13                           _rootRunUnary
dart:async/zone.dart 1031:19                           _CustomZone.runUnary
dart:async/zone.dart 933:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 763:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 639:7                _StreamController._add
dart:async/stream_controller.dart 585:5                _StreamController.add
dart:io/runtime/binsocket_patch.dart 1276:33           new _RawSocket.<fn>
dart:io/runtime/binsocket_patch.dart 819:14            _NativeSocket.issueReadEvent.issue
dart:async/schedule_microtask.dart 41:21               _microtaskLoop
dart:async/schedule_microtask.dart 50:5                _startMicrotaskLoop
dart:isolate/runtime/libisolate_patch.dart 113:13      _runPendingImmediateCallback
dart:isolate/runtime/libisolate_patch.dart 166:5       _RawReceivePortImpl._handleMessage

Lost connection to device.

```

**Comment by aam** [comment]
I tried this on beta(c7ea3ca377e909469c68f2ab878a5bc53d3cf66b), it exhibits same behavior. So this is not recent regression.

**Comment by aam** [comment]
The RPC exception above is really bringing just flutter tools down. The reason for that is that flutter tools doesn't handle exceptions thrown by RPC call. Wrapping _debugToggleDebugPaintSizeEnabled in flutter_tools/lib/src/resident_runner.dart with `try {} on Exception catch() {}` allows flutter tools to handle it.

**Comment by aam** [comment]
I'm happy to add exception handling, it would be nice to confirm impact on Jacob's work first to understand why this became a problem now.

Meanwhile, removing 'TODAY' tag as this doesn't look like a recent regression.

**Comment by jacob314** [comment]
Not sure what is different on our setups but this definitely crashes on my laptop. The crash is not purely in Flutter tools. I am using an android emulator to repro.

Here is a repro of it not crashing at all on an older build.
https://github.com/jacob314/flutter/tree/crash_repro

If you merge to include the latest engine roll it will crash the dart vm when running in an android emulator.
Note that I really care about the behavior with IntelliJ not flutter tools. Using flutter tools is just a simpler way to repro the crash.

**Comment by aam** [comment]
Does it crash the same way when you run on physical device?
I checked out your crash_repro repo, did flutter run in flutter_gallery with physical Moto G4 connected, pressed 'p' and got same exception as on latest head:

```
╭─$FH /flutter/examples/flutter_gallery  ‹37bb045e5*› 
╰─➤  $FH/flutter/bin/flutter run -v
...
[        ] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[        ] An Observatory debugger and profiler on Moto G 4 is available at: http://127.0.0.1:8102/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+42314 ms] _flutter.listViews: {}
[  +10 ms] ext.flutter.debugPaint: {isolateId: isolates/116899885}
[  +70 ms] ext.flutter.debugPaint: {enabled: true, isolateId: isolates/116899885}
[  +58 ms] I/flutter (13729): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
[  +22 ms] I/flutter (13729): The following _Exception was thrown during a service extension callback for
[        ] I/flutter (13729): "ext.flutter.debugPaint":
[        ] I/flutter (13729): Exception: Throwing an exception here shouldn't crash
[        ] I/flutter (13729): 
[        ] I/flutter (13729): When the exception was thrown, this was the stack:
[  +12 ms] I/flutter (13729): #0      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initServiceExtensions.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/binding.dart:63:11)
[        ] I/flutter (13729): #1      BindingBase.registerBoolServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:281:23)
[        ] I/flutter (13729): <asynchronous suspension>
[        ] I/flutter (13729): #2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370:32)
[        ] I/flutter (13729): <asynchronous suspension>
[        ] I/flutter (13729): #3      _runExtension (dart:developer/runtime/libdeveloper.dart:85:23)
[   +1 ms] I/flutter (13729): ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +15 ms] Error -32000 received from application: Server error
[        ] {details: {"exception":"Exception: Throwing an exception here shouldn't crash","stack":"#0      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initServiceExtensions.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/binding.dart:63:11)\n#1      BindingBase.registerBoolServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:281:23)\n<asynchronous suspension>\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370:32)\n<asynchronous suspension>\n#3      _runExtension (dart:developer/runtime/libdeveloper.dart:85:23)\n","method":"ext.flutter.debugPaint"}}
[  +14 ms] JSON-RPC error -32000: Server error
           package:json_rpc_2/src/client.dart 110                  Client.sendRequest
           package:json_rpc_2/src/peer.dart 68                     Peer.sendRequest
           package:flutter_tools/src/vmservice.dart 239            VMService._sendRequest
           package:flutter_tools/src/vmservice.dart 787            VM.invokeRpcRaw
           ===== asynchronous gap ===========================
           package:flutter_tools/src/vmservice.dart 1052           Isolate.invokeRpcRaw
           package:flutter_tools/src/vmservice.dart 1181           Isolate.invokeFlutterExtensionRpcRaw
           ===== asynchronous gap ===========================
           package:flutter_tools/src/vmservice.dart 1215           Isolate._flutterToggle
           ===== asynchronous gap ===========================
           package:flutter_tools/src/vmservice.dart 1225           Isolate.flutterToggleDebugPaintSizeEnabled
           package:flutter_tools/src/resident_runner.dart 210      FlutterDevice.toggleDebugPaintSizeEnabled
           ===== asynchronous gap ===========================
           package:flutter_tools/src/resident_runner.dart 523      ResidentRunner._debugToggleDebugPaintSizeEnabled
           ===== asynchronous gap ===========================
           package:flutter_tools/src/resident_runner.dart 704      ResidentRunner._commonTerminalInputHandler
           ===== asynchronous gap ===========================
           package:flutter_tools/src/resident_runner.dart 748      ResidentRunner.processTerminalInput
           ===== asynchronous gap ===========================
           dart:async/zone.dart 1134                               _rootRunUnary
           dart:async/zone.dart 1031                               _CustomZone.runUnary
           dart:async/zone.dart 933                                _CustomZone.runUnaryGuarded
           dart:async/stream_impl.dart 330                         _BufferingStreamSubscription._sendData
           dart:async/stream_impl.dart 257                         _BufferingStreamSubscription._add
           dart:async/broadcast_stream_controller.dart 379         _SyncBroadcastStreamController._sendData
           dart:async/broadcast_stream_controller.dart 254         _BroadcastStreamController.add
           dart:async/broadcast_stream_controller.dart 480         _AsBroadcastStreamController.add
           dart:async/zone.dart 1134                               _rootRunUnary
           dart:async/zone.dart 1031                               _CustomZone.runUnary
           dart:async/zone.dart 933                                _CustomZone.runUnaryGuarded
           dart:async/stream_impl.dart 330                         _BufferingStreamSubscription._sendData
           dart:async/stream_impl.dart 257                         _BufferingStreamSubscription._add
           dart:async/stream_transformers.dart 68                  _SinkTransformerStreamSubscription._add
           dart:async/stream_transformers.dart 15                  _EventSinkWrapper.add
           dart:convert/string_conversion.dart 268                 _StringAdapterSink.add
           dart:convert/ascii.dart 301                             _SimpleAsciiDecoderSink.add
           dart:convert/chunked_conversion.dart 86                 _ConverterStreamEventSink.add
           dart:async/stream_transformers.dart 120                 _SinkTransformerStreamSubscription._handleData
           dart:async/zone.dart 1134                               _rootRunUnary
           dart:async/zone.dart 1031                               _CustomZone.runUnary
           dart:async/zone.dart 933                                _CustomZone.runUnaryGuarded
           dart:async/stream_impl.dart 330                         _BufferingStreamSubscription._sendData
           dart:async/stream_impl.dart 257                         _BufferingStreamSubscription._add
           dart:async/stream_controller.dart 763                   _StreamController&&_SyncStreamControllerDispatch._sendData
           dart:async/stream_controller.dart 639                   _StreamController._add
           dart:async/stream_controller.dart 585                   _StreamController.add
           dart:io-patch/socket_patch.dart 1672                    _Socket._onData
           dart:async/zone.dart 1138                               _rootRunUnary
           dart:async/zone.dart 1031                               _CustomZone.runUnary
           dart:async/zone.dart 933                                _CustomZone.runUnaryGuarded
           dart:async/stream_impl.dart 330                         _BufferingStreamSubscription._sendData
           dart:async/stream_impl.dart 257                         _BufferingStreamSubscription._add
           dart:async/stream_controller.dart 763                   _StreamController&&_SyncStreamControllerDispatch._sendData
           dart:async/stream_controller.dart 639                   _StreamController._add
           dart:async/stream_controller.dart 585                   _StreamController.add
           dart:io-patch/socket_patch.dart 1245                    new _RawSocket.<fn>
           dart:io-patch/socket_patch.dart 797                     _NativeSocket.issueReadEvent.issue
           dart:async/schedule_microtask.dart 41                   _microtaskLoop
           dart:async/schedule_microtask.dart 50                   _startMicrotaskLoop
           dart:isolate-patch/dart:isolate/isolate_patch.dart 113  _runPendingImmediateCallback
           dart:isolate-patch/dart:isolate/isolate_patch.dart 166  _RawReceivePortImpl._handleMessage
           
[   +5 ms] ext.flutter.exit: {isolateId: isolates/116899885}
```

**Comment by aam** [comment]
On emulator I get the same exception as I do on physical device

**Comment by jacob314** [comment]
My macbook pro has started crashing in general so let me make sure I can repro the physical device crashes on my linux machine as well. I'll update when I have instructions that expose a C++ crash not just a flutter_tool crash.

**Comment by jacob314** [comment]
Ok so the problem is the C++ crash only reproduces using IntelliJ to communicate with Flutter instead of using Flutter Tool directly. The difference is probably that when using flutter tool, you are not waiting for uncaught exceptions so the code paths that cause the exception are not triggered. 

Here is the crash from IntelliJ using tip of trunk with the engine roll.
```
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Android SDK built for x86...
I/flutter (10357): service extension method received: ext.flutter.inspector.setPubRootDirectories({arg0: /usr/local/google/home/jacobr/git/flutter/3/flutter/examples/flutter_gallery, isolateId: isolates/283830717})
I/flutter (10357): service extension method received: ext.flutter.inspector.isWidgetTreeReady({isolateId: isolates/283830717})
D/        (10357): HostConnection::get() New Host Connection established 0xa2224200, tid 10376
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.420486
I/flutter (10357): service extension method received: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_0, isolateId: isolates/283830717})
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.345270
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.015364
D/EGL_emulation(10357): eglMakeCurrent: 0xa222ea40: ver 2 0 (tinfo 0xa227f010)
I/flutter (10357): service extension method received: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_1, isolateId: isolates/283830717})
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.011412
I/flutter (10357): service extension method received: ext.flutter.inspector.getSelectedWidget({objectGroup: selection_1, isolateId: isolates/283830717})
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.000238
I/flutter (10357): service extension method received: ext.flutter.inspector.getRootWidgetSummaryTree({objectGroup: tree_2, isolateId: isolates/283830717})
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.000219
I/flutter (10357): service extension method received: ext.flutter.debugPaint({enabled: true, isolateId: isolates/283830717})
I/flutter (10357): Action "Wait for outer event loop" took 0:00:00.000203
F/libc    (10357): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x744e25d3 in tid 10375 (1.ui), pid 10357 (er.demo.gallery)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.007/4586646:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 10357, tid: 10375, name: 1.ui  >>> io.flutter.demo.gallery <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x744e25d3
    eax 1144f468  ebx 94122aa0  ecx 51c43d04  edx 9121b058
    esi a3feba00  edi 916c0021
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip 936eaf26  ebp 92ffddb8  esp 92ffdd70  flags 00010202
backtrace:
    #00 pc 00624f26  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #01 pc 00625284  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #02 pc 00622524  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #03 pc 0062a040  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #04 pc 00637cc5  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #05 pc 00637c74  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #06 pc 00585ae2  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #07 pc 00585911  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #08 pc 0000068f  <anonymous:91640000>
    #09 pc 0000913f  <anonymous:82440000>
    #10 pc 00009097  <anonymous:82440000>
    #11 pc 00008fb4  <anonymous:82440000>
    #12 pc 000206c8  <anonymous:80340000>
    #13 pc 00008922  <anonymous:82440000>
    #14 pc 00003285  <anonymous:82440000>
    #15 pc 0003e431  <anonymous:85500000>
    #16 pc 0000848e  <anonymous:82440000>
    #17 pc 000206c8  <anonymous:80340000>
    #18 pc 00012bfc  <anonymous:84680000>
    #19 pc 000206c8  <anonymous:80340000>
    #20 pc 0001691f  <anonymous:85900000>
    #21 pc 00016551  <anonymous:85900000>
    #22 pc 00016235  <anonymous:85900000>
    #23 pc 00003285  <anonymous:82440000>
    #24 pc 0000c2f6  <anonymous:85900000>
    #25 pc 0001ed3b  <anonymous:85900000>
    #26 pc 00030a71  <anonymous:8f4c0000>
    #27 pc 00003285  <anonymous:82440000>
    #28 pc 0000faed  <anonymous:85900000>
    #29 pc 000206c8  <anonymous:80340000>
    #30 pc 0000eeb3  <anonymous:85900000>
    #31 pc 0000d5ea  <anonymous:85900000>
    #32 pc 0000d1e7  <anonymous:85900000>
    #33 pc 000206c8  <anonymous:80340000>
    #34 pc 0001c794  <anonymous:8e300000>
    #35 pc 0000096f  <anonymous:91640000>
    #36 pc 0061c688  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #37 pc 0061c35c  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #38 pc 0061fdb5  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #39 pc 0063e69c  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #40 pc 006696ae  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #41 pc 006697d8  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #42 pc 00941a68  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #43 pc 004c888f  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #44 pc 004c8adc  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #45 pc 000950d6  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #46 pc 00094c94  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #47 pc 00099832  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #48 pc 00014af7  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39)
    #49 pc 00015936  /system/lib/libutils.so (android::Looper::pollInner(int)+982)
    #50 pc 000154d6  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+118)
    #51 pc 0000ff10  /system/lib/libandroid.so (ALooper_pollOnce+96)
    #52 pc 0009976c  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #53 pc 0009530f  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #54 pc 00094572  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #55 pc 0009791d  /data/app/io.flutter.demo.gallery-TrALbIZuko30ET3tlTlRNg==/lib/x86/libflutter.so
    #56 pc 00071445  /system/lib/libc.so (__pthread_start(void*)+53)
    #57 pc 000205db  /system/lib/libc.so (__start_thread+75)
    #58 pc 0001ec16  /system/lib/libc.so (__bionic_clone+70)
Lost connection to device.
```
I'm not sure why service methods are being invoked differently in this case.
You can use the regular released Flutter IntelliJ plugin to repro. let me know if you have any trouble reproducing.

**Comment by jacob314** [comment]
Update is the latest engine roll should fix the issue. I will close as soon as it lands. Likely this is a duplicate of the other breakpoint related bug.

**Comment by zoechi** [comment]
@jacob314 I assume you mean #19379 which landed and fixed it.
Can we close?
