### ISSUE TITLE
firebase_core 0.2.4 unhandled exception on hot restart

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19351]
```
Performing hot restart...
Restarted app in 2,817ms.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'file:///Users/lukepighetti/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.4/lib/src/firebase_app.dart': Failed assertion: line 66 pos 14: 'await existingApp.options == options': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      FirebaseApp.configure (file:///Users/lukepighetti/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.4/lib/src/firebase_app.dart)
<asynchronous suspension>
#3      _Firebase.connect (file:///Users/lukepighetti/code/when-coin/when_coin/lib/modules/firebase.dart:24:29)
<asynchronous suspension>
```

```
Lukes-iMac:when_coin lukepighetti$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✗] Android Studio (not installed)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)

! Doctor found issues in 3 categories.
```

**Comment by cyanglaz** [comment]
This is fixed with https://github.com/flutter/plugins/pull/1204

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/755. Any further collaboration will be done there.
