### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY Failed assertion: line 405 pos 16: 'url != I/flutter ( 2782): null': is not true.

### ISSUE THREAD

**Issue by mohabmm** [flutter/flutter#19388]
```
I/FlutterActivityDelegate( 2782): onResume setting current activity to this
I/Timeline( 2782): Timeline: Activity_idle id: android.os.BinderProxy@39f615a5 time:443898009
I/flutter ( 2782): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2782): The following assertion was thrown building PhotoBrowser(dirty, state: _PhotoBrowserState#991a4):
I/flutter ( 2782): 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 405 pos 16: 'url !=
I/flutter ( 2782): null': is not true.
I/flutter ( 2782): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2782): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2782): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2782):   https://github.com/flutter/flutter/issues/new
I/flutter ( 2782): When the exception was thrown, this was the stack:
I/flutter ( 2782): #2      new NetworkImage (package:flutter/src/painting/image_provider.dart)
I/flutter ( 2782): #3      new Image.network (package:flutter/src/widgets/image.dart:169:20)
I/flutter ( 2782): #4      _PhotoBrowserState.build (package:tic_tic/Cards/photos.dart:101:13)
I/flutter ( 2782): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter ( 2782): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 2782): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
I/flutter ( 2782): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #98     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #107    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 2782): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #117    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter ( 2782): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #123    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #128    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 2782): #129    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 2782): #130    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 2782): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 2782): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 2782): #133    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4437:32)
I/flutter ( 2782): #134    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 2782): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2782): #136    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 2782): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 2782): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 2782): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 2782): #140    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 2782): #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 2782): #142    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 2782): #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2782): #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2782): #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 2782): #146    _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 2782): #147    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 2782): (elided 2 frames from class _AssertionError)
I/flutter ( 2782): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2782): Another exception was thrown: 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 405 pos 16: 'url != null': is not true.
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
V/ActivityThread( 2782): updateVisibility : ActivityRecord{2c576721 token=android.os.BinderProxy@39f615a5 {com.tic.tictic/com.tic.tictic.MainActivity}} show : true
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
W/zzaeo   ( 2782): [{0}] Failed to resolve name. status={1}
```

**Comment by zoechi** [comment]
As the error message says you must not pass `null` as URL.
We would need to see your code for more concrete advice how to fix.
It's probably better to ask this question on StackOverflow.

**Comment by lichentao** [comment]
I have did this error , final fix by  post request . call back data to fill UI,  need  flollow !

               builder: (context, snapshot){
                 if (snapshot.hasData){}
}

**Comment by Pushan-Gupta** [comment]
This error means that we are providing a null url to the builder. 

say,

```
var listView = new ListView.builder(
        itemCount: _total,
        itemBuilder: (BuildContext context, int index) {
          Data data = _getData(index);

            return new Container(
                height: 200.0,
                child: new Image.network(
                    data.path------------->This is the error source
                )
            );
          

        });
```

To solve this,

We can do something like: 

```
var listView = new ListView.builder(
        itemCount: _total,
        itemBuilder: (BuildContext context, int index) {
          Data data = _getData(index);
          if(data.path!=null){----->Note this

            return new Container(
                height: 200.0,
                child: new Image.network(
                    data.path
                )
            );
          }

        });
```
