### ISSUE TITLE
ArgumentError: Invalid argument(s): join(null, "Applications"): part 0 was null, but part 1 was not.

### ISSUE THREAD

**Issue by john1q** [flutter/flutter#19392]
## Steps to Reproduce

cant run flutter doctor and find issues
## Logs

flutter doctor
flutter doctor -v

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): join(null, "Applications"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1088)
#1      Context.join (package:path/src/context.dart:231)
#2      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:165)
#3      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:137)
#4      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:55)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:80)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:87)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#18     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1501)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#27     new Future.sync (dart:async/future.dart:222)
#28     CommandRunner.run (package:args/command_runner.dart:109)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1126)
#33     _CustomZone.run (dart:async/zone.dart:1023)
#34     runZoned (dart:async/zone.dart:1501)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50)
#38     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#39     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-KZ)
    • Flutter version 0.5.1 at /Users/zhanik/development/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by marico-sun** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): join(null, "Applications"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1088:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:203:29)
#3      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:175:26)
#4      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:65:51)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:121:46)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:128:39)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:111:11)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:51:10)
#41     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#42     main (file:///Users/MacLocation/Flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.6.3 at /Users/MacLocation/Flutter
    [32m•[39m Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    [32m•[39m Engine revision 8dc3a4cde2
    [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[33m![39m Doctor found issues in 2 categories.
```

**Comment by RanaRanvijaySingh** [comment]
I received the same error on JENKINS, which turned out I was missing the HOME environment variable on my Jenkins system. 
Find your path with

> echo $HOME

Set the same in Jenkins > Manage Jenkins > Configure System > Global Properties > Environment Variables > 
Name: HOME
Value: [Your path]
