### ISSUE TITLE
I/flutter (25517): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'

### ISSUE THREAD

**Issue by mojason-81** [flutter/flutter#19406]
It seems having a `TextField` as the `title` and of a `ListTile` and having a `subtitle` of anything for the `ListTile` is throwing this error.  Here's the offensive code and output from Android Studio.  If I remove the `subtitle` from the `ListTile` in `_HomeState -> Scaffold -> body(Container) -> child(ListTile)`, *_or_* make the title a simple `Text` widget, the error does not occur.

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MaterialApp(title: 'IO', home: Home()));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var _enterDataField = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Read / Write'),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),
      body: Container(
        padding: const EdgeInsets.all(13.4),
        alignment: Alignment.topCenter,
        child: ListTile(
            // title: Text('hello'),
            // subtitle: Text('world'),
            title: TextField(
              controller: _enterDataField,
              decoration: InputDecoration(
                labelText: 'Write Something',
              ),
            ),
            subtitle: Column(
              children: <Widget>[
                FlatButton(
                  onPressed: () {
                    return null;
                  },
                  child: Column(
                    children: <Widget>[
                      Text('Save Data'),
                      Padding(
                        padding: EdgeInsets.all(14.5),
                      ),
                      Text('Saved data goes here')
                    ],
                  ),
                ),
              ],
            ),
          ),
      ),
    );
  }

  Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  Future<File> get _localFile async {
    final path = await _localPath;
    return File('$path/data.txt');
  }

  // Write and Read from file

  Future<File> writeData(String message) async {
    final file = await _localFile;
    return file.writeAsString('$message');
  }

  Future<String> readData() async {
    try {
      final file = await _localFile;
      String data = await file.readAsString();
      return data;
    } catch (e) {
      return "Nothing saved yet.";
    }
  }
}
```

```
Performing hot restart...
Restarted app in 1,073ms.
I/flutter (25517): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25517): The following assertion was thrown during performLayout():
I/flutter (25517): not implemented
I/flutter (25517): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (25517): 
I/flutter (25517): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25517): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25517): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25517):   https://github.com/flutter/flutter/issues/new
I/flutter (25517): 
I/flutter (25517): When the exception was thrown, this was the stack:
I/flutter (25517): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (25517): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (25517): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (25517): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (25517): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (25517): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (25517): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (25517): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (25517): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (25517): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (25517): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (25517): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (25517): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (25517): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (25517): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (25517): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (25517): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (25517): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (25517): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:778:32)
I/flutter (25517): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (25517): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (25517): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (25517): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (25517): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (25517): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (25517): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (25517): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (25517): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter (25517): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (25517): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25517): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25517): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (25517): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (25517): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (25517): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (25517): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (25517): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (25517): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25517): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25517): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (25517): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (25517): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (25517): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (25517): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (25517): 
I/flutter (25517): The following RenderObject was being processed when the exception was fired:
I/flutter (25517):   _RenderListTile#57b83 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25517):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (25517):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
I/flutter (25517):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (25517):   constraints: BoxConstraints(0.0<=w<=301.2, 0.0<=h<=485.2)
I/flutter (25517):   size: MISSING
I/flutter (25517): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (25517):   RenderSemanticsAnnotations#7d1d3 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (25517):     RenderIgnorePointer#be0b9 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (25517):       RenderPointerListener#89f26 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (25517):         _RenderDecoration#2b3d6 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (25517):           RenderRepaintBoundary#fe3dd relayoutBoundary=up12 NEEDS-PAINT
I/flutter (25517):           RenderTransform#43037 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (25517):           RenderConstrainedBox#98017 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (25517):           RenderCustomPaint#1a1be NEEDS-PAINT
I/flutter (25517):   RenderFlex#dcb7e relayoutBoundary=up8 NEEDS-PAINT
I/flutter (25517):     RenderSemanticsAnnotations#5ad98 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (25517):       RenderConstrainedBox#74adf relayoutBoundary=up10 NEEDS-PAINT
I/flutter (25517):         RenderClipPath#9341d relayoutBoundary=up11 NEEDS-PAINT
I/flutter (25517):           RenderCustomPaint#8ce22 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (25517): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25517): Another exception was thrown: RenderBox was not laid out: _RenderListTile#57b83 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (25517): Another exception was thrown: RenderBox was not laid out: RenderPadding#94e0a relayoutBoundary=up6 NEEDS-PAINT
I/flutter (25517): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#1449c relayoutBoundary=up5 NEEDS-PAINT
I/flutter (25517): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#20a39 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (25517): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
Have you tried in `dev` channel?
```
flutter channel dev
flutter doctor
```

**Comment by mojason-81** [comment]
Haven't tried dev channel.  Will try switching to that tonight.  Here's the output you requested:

```
 $ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/jason/project/dev_tools/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/jason/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/idea-IC-181.5087.20
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by mojason-81** [comment]
@zoechi Same problem after switching to dev channel.
```
/home/jason/project/dev_tools/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0
```

**Comment by mojason-81** [comment]
Looks the error doesn't occur in Flutter v0.4.4, but does as of v0.5.0.
