### ISSUE TITLE
Crash in background

### ISSUE THREAD

**Issue by b-connect** [flutter/flutter#19465]
## Steps to Reproduce
Seems to be a problem in a isolate running in background.

Using android_job_scheduler

## Logs

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter logs

## exception

_TypeError: type 'Future<FlutterCommandResult>' is not a subtype of type 'FutureOr<Null>'

```
#0      LogsCommand.verifyThenRunCommand (package:flutter_tools/src/commands/logs.dart:36:18)
#1      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#7      Future._complete (dart:async/future_impl.dart:472:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#10     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#11     FlutterCommand.findTargetDevice (package:flutter_tools/src/runner/flutter_command.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#18     Future._complete (dart:async/future_impl.dart:472:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#22     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#29     Future._complete (dart:async/future_impl.dart:472:7)
#30     Stream.toList.<anonymous closure> (dart:async/stream.dart:961:18)
#31     _rootRun (dart:async/zone.dart:1122:38)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#34     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#35     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#36     _DelayedDone.perform (dart:async/stream_impl.dart:603:14)
#37     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#38     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.5.8-pre.58, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.8-pre.58 at /home/erik/projects/flutter/flutter
    • Framework revision 85f09f622e (6 hours ago), 2018-07-16 22:42:06 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/erik/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/erik/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/erik/projects/android-studio
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • F5321 • BH901GN05Z • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```
## Analyze
```
   info • Close instances of `dart.core.Sink` • lib/services/database.dart:20:30

```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
[✓] Flutter (Channel master, v0.5.8-pre.58, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.8-pre.58 at /home/erik/projects/flutter/flutter
    • Framework revision 85f09f622e (6 hours ago), 2018-07-16 22:42:06 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/erik/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/erik/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/erik/projects/android-studio
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • F5321 • BH901GN05Z • android-arm64 • Android 8.0.0 (API 26
```

**Comment by zoechi** [comment]
Can you please provide more information about how to reproduce?
The error message actually tells what's wrong.

**Comment by b-connect** [comment]
Seems only occur when i call `flutter logs`

**Comment by zoechi** [comment]
Sorry, missed the `flutter logs` line
