### ISSUE TITLE
erroe

### ISSUE THREAD

**Issue by sreedath19** [flutter/flutter#19463]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.1.3` • Flutter plugin `io.flutter 26.0.1` • Dart plugin `173.4700`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.InstanceRef.getKind(InstanceRef.java:42)
	at io.flutter.server.vmService.frame.DartVmServiceValue.computeVarHavingStringValuePresentation(DartVmServiceValue.java:189)
	at io.flutter.server.vmService.frame.DartVmServiceValue.computePresentation(DartVmServiceValue.java:148)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:70)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.lambda$addChildren$0(XValueContainerNode.java:98)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:104)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:101)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by escamoteur** [comment]
Please add you `flutter doctor`output to your issue

**Comment by zoechi** [comment]
What action causes this exception? How can this be reproduced?
