### ISSUE TITLE
 Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by parasthekoder** [flutter/flutter#19462]
When I upgrade to the v0.5.7 in the dev channel I got this error which was previously working fine.
Then I tried beta channel too but this error is not going. I don't know how to handle it as I got no clue searching over google.

####The potential candidate of the crash is this code
`
  Future getImage(BuildContext context,ImageSource imageSource) async {

    Io.File image = await ImagePicker.pickImage(source: imageSource);
    if(image!=null){
      print(image);
      showPhoto(context,image);
    }else{
      _scaffoldkey.currentState.showSnackBar(new SnackBar(content: new Text('Unable to select photo, Try again..')));
    }
  }

  void showPhoto(BuildContext context,Io.File image) async {
    final value = await Navigator.push(context, new MaterialPageRoute(
        builder: (BuildContext context) =>
        new MediaExplorer(name: widget.name, image: image, uuid: widget.uuid)
    ));
    if (value != null) {
      _widgets.add(ImageTile(imageCard: value, uid: widget.uuid,));
    }
  }`
####When I click on the file to track where the error occured it navigates to this line in above code
` final value = await Navigator.push(context, new MaterialPageRoute(`

### Exception 
`[+8427 ms] I/flutter (22485): File: '/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20180717-WA0000.jpg'
[   +2 ms] E/flutter (22485): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter (22485): Looking up a deactivated widget's ancestor is unsafe.
[        ] E/flutter (22485): At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
[        ] E/flutter (22485):
[   +1 ms] E/flutter (22485): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3203:9)
[        ] E/flutter (22485): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3212:6)
[        ] E/flutter (22485): #2      Element.ancestorStateOfType (package:flutter/src/widgets/framework.dart:3254:12)
[        ] E/flutter (22485): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:1176:19)
[        ] E/flutter (22485): #4      Navigator.push (package:flutter/src/widgets/navigator.dart:816:22)
[        ] E/flutter (22485): #5      TimelinePanelState.showPhoto (package:hms/panels/timeline_panel.dart:192:35)
[        ] E/flutter (22485): <asynchronous suspension>
[   +2 ms] E/flutter (22485): #6      TimelinePanelState.getImage (package:hms/panels/timeline_panel.dart:185:7)
[   +1 ms] E/flutter (22485): <asynchronous suspension>
[        ] E/flutter (22485): #7      TimelinePanelState.chooseSource.<anonymous closure>.<anonymous closure> (package:hms/panels/timeline_panel.dart:172:14)
[        ] E/flutter (22485): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
[        ] E/flutter (22485): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
[        ] E/flutter (22485): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] E/flutter (22485): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
[        ] E/flutter (22485): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
[        ] E/flutter (22485): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] E/flutter (22485): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] E/flutter (22485): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] E/flutter (22485): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] E/flutter (22485): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] E/flutter (22485): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] E/flutter (22485): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] E/flutter (22485): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] E/flutter (22485): #21     _invoke1 (dart:ui/hooks.dart:134:13)
[        ] E/flutter (22485): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
[        ] I/FlutterActivityDelegate(22485): onResume setting current activity to this
[  +17 ms] W/Adreno-EGL(22485): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
[   +5 ms] W/Adreno-EGL(22485): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
[   +1 ms] D/vndksupport(22485): Loading /vendor/lib/hw/gralloc.msm8916.so from current namespace instead of sphal namespace.`

###Flutter Doctor

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

• No issues found!`

**Comment by KaranChimple** [comment]
Hi, I am facing the same issue but I am unable to understand where I am going wrong. Try having a look at my code:

```
class WelcomeScreen extends StatefulWidget {
  @override
  State createState() => new WelcomeScreenState();
}

class WelcomeScreenState extends State<WelcomeScreen> {
  bool delayed = false;
  String _animationName = "hello";
  bool paused = false;

  void initState() {
    super.initState();
  }

  void _complete(bool mounted) {
   if (mounted) {
      setState(() {
        paused = true;
        _animationName = null;
      });
      // Navigator.of(context).pushReplacementNamed('/tab');
   }
  }

  @override
  Widget build(BuildContext context) {
    MediaQueryData media = MediaQuery.of(context);

    var size = media.size;
    print('animation $_animationName');
    // TODO: implement build
    return new Scaffold(
            body: new Container(
                decoration: new BoxDecoration(
                  color: const Color(0xFF0E4476),
                ),
                child: new Stack(
                    alignment: AlignmentDirectional.bottomCenter,
                    children: <Widget>[
                      new Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: <Widget>[
                            Align(
                              alignment: AlignmentDirectional.center,
                              child: new AspectRatio(
                                aspectRatio:
                                    size.height > size.width ? 1.5 : 3.8,
                                child: new NimaActor(
                                  "assets/quack",
                                  paused: paused,
                                  alignment: Alignment.center,
                                  fit: BoxFit.scaleDown,
                                  animation: _animationName,
                                  mixSeconds: 0.2,
                                  completed: (String animtionName) {
                                    Navigator.of(context)
                                        .pushReplacementNamed('/tab');
                                    // print(
                                    //     'inside Complete  $_animationName $mounted');
                                    _complete(mounted);
                                  },
                                ),
                              ),
                            ),
                          ])
                    ])));
  }
}
```

**Comment by rakeshlanjewarwork** [comment]
//For Future Reference
**Note for Scoped model user  (My Assumption):-** 
        
       Please look for the context which you are passing, i have encountered the same issue.
The context which is passed by the ScopedModelDescendant's builder is different than the context which is passed by the build method, so if you are passing the context to functions then you need to pass the build functions context to the function if not then this exception will occur.

**Comment by sofferjacob** [comment]
I had the same issue with my app. The problem was I was trying to show a dialog using a previously popped context. The way I solved it was creating a global key for the scaffold in the page where I wanted the dialog to be shown, then instead of passing the current context to the `showDialog()` method, I passed the context from the scaffold.

Here is an incomplete code snippet for reference:

```
GlobalKey _scaffold = Global Key();
Scaffold(
  key: _scaffold
);
...
showDialog(context: _scaffold.currentContext)
```

Hope it helps

**Comment by mahmoudatef955** [comment]
> //For Future Reference
> **Note for Scoped model user (My Assumption):-**
> 
> ```
>    Please look for the context which you are passing, i have encountered the same issue.
> ```
> The context which is passed by the ScopedModelDescendant's builder is different than the context which is passed by the build method, so if you are passing the context to functions then you need to pass the build functions context to the function if not then this exception will occur.

I am using ScopedModel and facing the same problem, but i couldn't figure out how i am passing different context

**Comment by mahmoudatef955** [comment]
My Build Function

@override
  Widget build(BuildContext context) {
    //shadow

    var imagehight = 917;
    var imagewidth = 622;
    var scaleFactor = MediaQuery.of(context).size.width / imagewidth;
    this.pageHeight = MediaQuery.of(context).size.height;
    this.pageWidth = MediaQuery.of(context).size.width;
    this.scaleFactor1 = scaleFactor;
      double shadowMargin = pageHeight * 0.4457 - 269.55;
    var height = scaleFactor * imagehight;
    var width = MediaQuery.of(context).size.width;

    return Scaffold(
      //key: _scaffoldKey,
      body: Stack(
        children: <Widget>[
          PositionedTapDetector(
            child: ScopedModelDescendant<AyaList>(
                builder: (context, child, model) {
              this.ayaInPage = model.ayaInPage();
              this.selectModel = model;
              return mushafPageImage(
                  height, width); //ImageCarousel(model: model,);
            }),
            onTap: (position) {
              _togglebar();
              print('onTap: ${position.global}, ${position.relative}');
            },
            onLongPress: (position) {
              _toggleshadow();
              _onLongPressSelectAya(_selectedAya(
                  position.global.dx.ceil(), position.global.dy.ceil()));
            },
          ),
          _showShadow
              ? Container(
                  margin: EdgeInsets.only(top: shadowMargin),
                  child: ScopedModelDescendant<AyaList>(
                      builder: (context, child, model) {
                    return CustomPaint(
                      painter: GreenPaint(
                          Colors.green.withOpacity(0.3888),
                          scaleFactor,
                          height,
                          model.isFirstAyaInPage() ? 0 : model.prevAya().x,
                          model.isFirstAyaInPage() ? 0 : model.prevAya().y,
                          model.aya.x,
                          model.aya.y),
                    );
                  }),
                )
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
          Opacity(
            child: ScopedModelDescendant<AyaList>(
                builder: (context, child, model) {
              return customAppBar1();
            }),
            opacity: _showbar ? 1.0 : 0.0,
            //duration: Duration(milliseconds: 500),
          ),
          _showbar
              ? customButtomBar1()
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
          _showbar
              ? copyIcon()
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
        ],
      ),
    );
  }

**Comment by rakeshlanjewarwork** [comment]
> My Build Function
> 
> @override
> Widget build(BuildContext context) {
> //shadow
> 
> ```
> var imagehight = 917;
> var imagewidth = 622;
> var scaleFactor = MediaQuery.of(context).size.width / imagewidth;
> this.pageHeight = MediaQuery.of(context).size.height;
> this.pageWidth = MediaQuery.of(context).size.width;
> this.scaleFactor1 = scaleFactor;
>   double shadowMargin = pageHeight * 0.4457 - 269.55;
> var height = scaleFactor * imagehight;
> var width = MediaQuery.of(context).size.width;
> 
> return Scaffold(
>   //key: _scaffoldKey,
>   body: Stack(
>     children: <Widget>[
>       PositionedTapDetector(
>         child: ScopedModelDescendant<AyaList>(
>             builder: (context, child, model) {
>           this.ayaInPage = model.ayaInPage();
>           this.selectModel = model;
>           return mushafPageImage(
>               height, width); //ImageCarousel(model: model,);
>         }),
>         onTap: (position) {
>           _togglebar();
>           print('onTap: ${position.global}, ${position.relative}');
>         },
>         onLongPress: (position) {
>           _toggleshadow();
>           _onLongPressSelectAya(_selectedAya(
>               position.global.dx.ceil(), position.global.dy.ceil()));
>         },
>       ),
>       _showShadow
>           ? Container(
>               margin: EdgeInsets.only(top: shadowMargin),
>               child: ScopedModelDescendant<AyaList>(
>                   builder: (context, child, model) {
>                 return CustomPaint(
>                   painter: GreenPaint(
>                       Colors.green.withOpacity(0.3888),
>                       scaleFactor,
>                       height,
>                       model.isFirstAyaInPage() ? 0 : model.prevAya().x,
>                       model.isFirstAyaInPage() ? 0 : model.prevAya().y,
>                       model.aya.x,
>                       model.aya.y),
>                 );
>               }),
>             )
>           : Container(
>               width: 0.0,
>               height: 0.0,
>             ),
>       Opacity(
>         child: ScopedModelDescendant<AyaList>(
>             builder: (context, child, model) {
>           return customAppBar1();
>         }),
>         opacity: _showbar ? 1.0 : 0.0,
>         //duration: Duration(milliseconds: 500),
>       ),
>       _showbar
>           ? customButtomBar1()
>           : Container(
>               width: 0.0,
>               height: 0.0,
>             ),
>       _showbar
>           ? copyIcon()
>           : Container(
>               width: 0.0,
>               height: 0.0,
>             ),
>     ],
>   ),
> );
> ```
> }

What is the error ??

**Comment by mahmoudatef955** [comment]
I made a dialog with a TextField when i press on it i receive this error


I/flutter (30369): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30369): The following assertion was thrown building Builder(dirty):
I/flutter (30369): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (30369): At this point the state of the widget's element tree is no longer stable. To safely refer to a
I/flutter (30369): widget's ancestor in its dispose() method, save a reference to the ancestor by calling
I/flutter (30369): inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
I/flutter (30369):

**Comment by mahmoudatef955** [comment]
![Screenshot_2019-04-11-06-00-10-209_com halaqat halaqat](https://user-images.githubusercontent.com/18610560/56093820-59d5c800-5ecd-11e9-98bf-fe285811be93.png)

**Comment by rakeshlanjewarwork** [comment]
> I made a dialog with a TextField when i press on it i receive this error
> 
> I/flutter (30369): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter (30369): The following assertion was thrown building Builder(dirty):
> I/flutter (30369): Looking up a deactivated widget's ancestor is unsafe.
> I/flutter (30369): At this point the state of the widget's element tree is no longer stable. To safely refer to a
> I/flutter (30369): widget's ancestor in its dispose() method, save a reference to the ancestor by calling
> I/flutter (30369): inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
> I/flutter (30369):


Can you do like this :-

Widget build(BuildContext **mainContext**) {
}

and pass mainContext to the dialog.

try and reply if its working or not working..

**Comment by rakeshlanjewarwork** [comment]
pass the build functions BuildContext not the ScopedModelDescendant BuildContext both are different.

**Comment by mahmoudatef955** [comment]
same Problem here is what is did

@override
  Widget build(BuildContext mainContext) {
    super.build(mainContext);
    //shadow

    var imagehight = 917;
    var imagewidth = 622;
    var scaleFactor = MediaQuery.of(mainContext).size.width / imagewidth;
    this.pageHeight = MediaQuery.of(mainContext).size.height;
    this.pageWidth = MediaQuery.of(mainContext).size.width;
    this.scaleFactor1 = scaleFactor;
    print('Screen height : $pageHeight   width:$pageWidth');
    print('ScaleFactor:  $scaleFactor  page Height: $pageHeight ');
    double shadowMargin = pageHeight * 0.4457 - 269.55;
    //print(shadowMargin);
    var height = scaleFactor * imagehight;
    var width = MediaQuery.of(mainContext).size.width;

    return Scaffold(
      //key: _scaffoldKey,
      body: Stack(
        children: <Widget>[
          PositionedTapDetector(
            child: ScopedModelDescendant<AyaList>(
                builder: (context, child, model) {
              this.ayaInPage = model.ayaInPage();
              this.selectModel = model;
              return mushafPageImage(
                  height, width,mainContext); //ImageCarousel(model: model,);
            }),
            onTap: (position) {
              _togglebar();
              print('onTap: ${position.global}, ${position.relative}');
            },
            onLongPress: (position) {
              _toggleshadow();
              print('longPress: ${position.global}, ${position.relative}');
              _onLongPressSelectAya(_selectedAya(
                  position.global.dx.ceil(), position.global.dy.ceil()));
            },
          ),
          _showShadow
              ? Container(
                  margin: EdgeInsets.only(top: shadowMargin),
                  child: ScopedModelDescendant<AyaList>(
                      builder: (context, child, model) {
                    return CustomPaint(
                      painter: GreenPaint(
                          Colors.green.withOpacity(0.3888),
                          scaleFactor,
                          height,
                          model.isFirstAyaInPage() ? 0 : model.prevAya().x,
                          model.isFirstAyaInPage() ? 0 : model.prevAya().y,
                          model.aya.x,
                          model.aya.y),
                    );
                  }),
                )
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
          Opacity(
            child: ScopedModelDescendant<AyaList>(
                builder: (context, child, model) {
              return customAppBar1(mainContext);
            }),
            opacity: _showbar ? 1.0 : 0.0,
            //duration: Duration(milliseconds: 500),
          ),
          _showbar
              ? customButtomBar1(mainContext)
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
          _showbar
              ? copyIcon()
              : Container(
                  width: 0.0,
                  height: 0.0,
                ),
        ],
      ),
    );
  }



Widget customAppBar1(mainContext) {
    return ScopedModelDescendant<AyaList>(
      builder: (context, child, model) {
        return Container(
          width: MediaQuery.of(mainContext).size.width,
          color: Colors.white,
          //padding: EdgeInsets.fromLTRB(0.0, 20.0, 0.0, 0.0),
          height: 100.0,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              SizedBox(width: 4.0),
              GestureDetector(
                onTap: () {
                  showDialog(
                      context: mainContext,
                      builder: (BuildContext mainContext) {
                        return AlertDialog(
                          content: //dynamicDialog(parent: this),
                          _AddFasel(),

                        );
                      });

                },
                child: Container(
                  margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 10.0),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: <Widget>[
                      Icon(
                        Icons.note_add,
                        color: Colors.teal[600],
                      ),
                      Text("فاصل جديد"),
                      SizedBox(height: 4.0)
                    ],
                  ),
                ),
              ),
              SizedBox(
                width: 1.0,
              ),
              Container(
                  margin: EdgeInsets.only(top: 23.0, right: 8.0),
                  height: 80.0,
                  width: 0.5,
                  color: Colors.black87),
              Container(
                margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 10.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: <Widget>[
                    GestureDetector(
                      child: Icon(
                        Icons.search,
                        color: Colors.teal[600],
                      ),
                    ),
                    Text("الفواصل"),
                    SizedBox(height: 4.0)
                  ],
                ),
              ),
              SizedBox(
                width: 5.0,
              ),
              Container(
                  margin: EdgeInsets.only(top: 23.0),
                  height: 80.0,
                  width: 0.5,
                  color: Colors.black87),
              SizedBox(width: 85.0),
              Row(
                children: <Widget>[
                  Padding(
                    padding: const EdgeInsets.only(
                      top: 20.0,
                    ),
                    child: GestureDetector(
                      onTap: //_showDialog,
                          () {
                        showDialog(
                            context: mainContext,
                            builder: (BuildContext context) {
                              return AlertDialog(
                                content: //dynamicDialog(parent: this),
                                    ScopedModel<AyaList>(
                                        //mushaf()
                                        model: model,
                                        child: model != null
                                            ? dynamicDialog(
                                                parent: this,
                                                suraList1:
                                                    this.widget.suratable,
                                              )
                                            : Container(
                                                height: 370.0,
                                                child: Center(
                                                  child:
                                                      CircularProgressIndicator(),
                                                ),
                                              )),
                              );
                            });
                      },
                      child: Icon(
                        Icons.keyboard_arrow_down,
                        size: 28.0,
                        color: Colors.teal[600],
                      ),
                    ),
                  ),
                  Column(
                    children: <Widget>[
                      Container(
                          margin: EdgeInsets.only(top: 26.0, right: 42.0),
                          child: Text(
                            //"hg",
                            this.widget.suratable[model.aya.sura - 1].name,
                            style: TextStyle(fontSize: 18.0),
                          )),
                      Container(
                          padding: EdgeInsets.only(top: 0.0, right: 42.0),
                          child: Text(
                            //"الاية 1",
                            model.aya.aya.toString(),
                            style: TextStyle(fontSize: 18.0),
                          )),
                    ],
                  ),
                ],
              ),
            ],
          ),
        );
      },
    );
  }

**Comment by mahmoudatef955** [comment]
its working,the problem is solved... thanks

**Comment by rakeshlanjewarwork** [comment]
> its working,the problem is solved... thanks

Glad to know !!!!!!!!

**Comment by neveyam39** [comment]
> I had the same issue with my app. The problem was I was trying to show a dialog using a previously popped context. The way I solved it was creating a global key for the scaffold in the page where I wanted the dialog to be shown, then instead of passing the current context to the `showDialog()` method, I passed the context from the scaffold.
> 
> Here is an incomplete code snippet for reference:
> 
> ```
> GlobalKey _scaffold = Global Key();
> Scaffold(
>   key: _scaffold
> );
> ...
> showDialog(context: _scaffold.currentContext)
> ```
> 
> Hope it helps
Genius!!! Great solution, thanks!!!

**Comment by Gabrielhn** [comment]
> > I made a dialog with a TextField when i press on it i receive this error
> > I/flutter (30369): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> > I/flutter (30369): The following assertion was thrown building Builder(dirty):
> > I/flutter (30369): Looking up a deactivated widget's ancestor is unsafe.
> > I/flutter (30369): At this point the state of the widget's element tree is no longer stable. To safely refer to a
> > I/flutter (30369): widget's ancestor in its dispose() method, save a reference to the ancestor by calling
> > I/flutter (30369): inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
> > I/flutter (30369):
> 
> Can you do like this :-
> 
> Widget build(BuildContext **mainContext**) {
> }
> 
> and pass mainContext to the dialog.
> 
> try and reply if its working or not working..

Worked!

**Comment by CanRau** [comment]
For anyone experiencing this issue with a `PopupMenuButton`.
Setting `captureInheritedThemes: false` fixed it for me 🥳
More detail and source: https://stackoverflow.com/a/59690903
