### ISSUE TITLE
FutureBuilder does not work properly with FireStore

### ISSUE THREAD

**Issue by DionysusG** [flutter/flutter#19493]
to reproduce the problem, let us assume a collection 'A' that have document 'b' in FireStore.
Also, we have tested the collection with StreamBuilder, which means `Firestore.instance.collection('A').getSanpshops()` does work properly with StreamBuilder.
then, the following codes

```
class ErrorDemo extends StatefulWidget {
  @override
  createState() => ErrorDemoState();
}

class ErrorDemoState extends State<ErrorDemo> {

  @override
  build(BuildContext context) {
    return new FutureBuilder<DocumentSnapshot>(
      future: Firestore.instance.document('A/b').get(),
      builder: (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot){
        if(snapshot.connectionState == ConnectionState.waiting)
          return Text('waiting');
        if (!snapshot.hasData)
          return new Text('Unknow');
        if (snapshot.error)
          return new Text('Error');

        return new Text('finish');
      },
    );
  }
}
```

will not display the page properly and give the following log 

```
flutter: The following assertion was thrown building FutureBuilder<DocumentSnapshot>(dirty, state:
flutter: _FutureBuilderState<DocumentSnapshot>#8a3f1):
flutter: Failed assertion: boolean expression must not be null
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ErrorDemoState.build.<anonymous closure> (file:///Users/GanYuan/FlutterProjects/project_bubbleTea/flutter/lib/main.dart)
flutter: #1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #11     _invoke (dart:ui/hooks.dart:120:13)
flutter: #12     _drawFrame (dart:ui/hooks.dart:109:3)
```

This happens on iOS, I did not test the case on Android.

The flutter doctor information is as follow
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)
```

the FireStore plugin version is 
```
cloud_firestore: ^0.7.3
```

**Comment by zoechi** [comment]
I think you should implement it like shown in the example code in https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html

I assume that the case `ConnectionState.none` is happening with `snapshot == null` and then `!snapshot.hasData` or `snapshot.hasError` throw the error you got.

**Comment by 5ummit** [comment]
Can you do this with query?
