### ISSUE TITLE
Can't build using cloud_functions on iOS

### ISSUE THREAD

**Issue by alamboley** [flutter/flutter#19512]
Hey, having trouble making an iOS applications with firebase cloud_functions plugin:

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  json_annotation: ^0.2.5
  flutter_webview_plugin: ^0.1.6
  firebase_auth: ^0.5.11
  firebase_database: ^1.0.1
  firebase_messaging: ^1.0.3
  cloud_functions: ^0.0.1
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.3
  flutter_iap: ^1.2.1
```

Error:
```
Launching lib/main.dart on iPhone X in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 35QLRQBKZ9
Running pod install...
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
    Finding Podfile changes
      - Flutter
      - cloud_functions
      - firebase_auth
      - firebase_core
      - firebase_database
      - firebase_messaging
      - flutter_iap
      - flutter_webview_plugin
      - shared_preferences
      - url_launcher
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `flutter_iap` from `.symlinks/plugins/flutter_iap/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    
    Resolving dependencies of `Podfile`
    
    Comparing resolved specification to the sandbox manifest
      - Firebase
      - FirebaseAnalytics
      - FirebaseAuth
      - FirebaseCore
      - FirebaseDatabase
      - FirebaseFunctions
      - FirebaseInstanceID
      - FirebaseMessaging
      - Flutter
      - GTMSessionFetcher
      - GoogleToolboxForMac
      - Protobuf
      - cloud_functions
      - firebase_auth
      - firebase_core
      - firebase_database
      - firebase_messaging
      - flutter_iap
      - flutter_webview_plugin
      - leveldb-library
      - nanopb
      - shared_preferences
      - url_launcher
    
    Downloading dependencies
    
    -> Using Firebase (5.4.0)
    
    -> Using FirebaseAnalytics (5.0.1)
    
    -> Using FirebaseAuth (5.0.2)
    
    -> Using FirebaseCore (5.0.5)
    
    -> Using FirebaseDatabase (5.0.2)
    
    -> Using FirebaseFunctions (2.1.0)
    
    -> Using FirebaseInstanceID (3.1.1)
    
    -> Using FirebaseMessaging (3.0.3)
    
    -> Using Flutter (1.0.0)
    
    -> Using GTMSessionFetcher (1.1.15)
    
    -> Using GoogleToolboxForMac (2.1.4)
    
    -> Using Protobuf (3.6.0)
    
    -> Using cloud_functions (0.0.1)
    
    -> Using firebase_auth (0.0.1)
    
    -> Using firebase_core (0.0.1)
    
    -> Using firebase_database (0.0.1)
    
    -> Using firebase_messaging (0.0.1)
    
    -> Using flutter_iap (1.2.0)
    
    -> Using flutter_webview_plugin (0.0.1)
    
    -> Using leveldb-library (1.20)
    
    -> Using nanopb (0.3.8)
    
    -> Using shared_preferences (0.0.1)
    
    -> Using url_launcher (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static frameworks: (FirebaseFunctions, FirebaseCore, FirebaseAuth, FirebaseDatabase, and FirebaseMessaging)
    
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:87:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] Automatically assigning platform `ios` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Finished with error: Error running pod install
```
Any ideas? No problem before adding cloud_functions plugin.

**Comment by zoechi** [comment]
Cloud functions is pretty new. Switching to `dev` or `master` channel might be worth a try.
Also updating to cocoapods 1.5.3 might help

**Comment by alamboley** [comment]
@zoechi unfortunately same issue with cocoapods 1.5.3. I also tried switching to `dev` or `master` channel without luck.

For me it seems to be a problem with Podfile, here is mine:
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  use_frameworks!
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
I've added `use_frameworks!` since it's required by this [iap plugin](https://github.com/JackAppDev/flutter_iap/issues/17).

I mentioned @kroikie since he creates this pub.

**Comment by alamboley** [comment]
Ok, so if remove things related to the iap plugin, and so comment `use_frameworks!` in the podfile. I can compile. Don't know the issue is on which side finally.

**Comment by OpticNectar** [comment]
I"m getting this same error and i'm not using the iap plugin. Any idea how to fix this?

**Comment by kroikie** [comment]
@alamboley

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/750. Any further collaboration will be done there.
