### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by YusufJo** [flutter/flutter#19522]
when i try to run my application for the first time, i get these messages 

> 

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 42166fb9f119ab6f)
Crash report written to /Users/yusuf/Documents/Flutter/flutter_app1/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.

> 

**crash report**

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --device-id=F57A730B-8D40-41B7-8F5C-67140B7296B9 lib/main.dart

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/yusuf/Documents/Flutter/flutter_app1/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java' (OS Error: Permission denied, errno = 13)

```
#0      _File.throwIfError (dart:io/file_impl.dart:647)
#1      _File.openSync (dart:io/file_impl.dart:491)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:616)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:640)
#4      LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:156)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:238)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:332)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Users/yusuf/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/yusuf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • iPhone X • F57A730B-8D40-41B7-8F5C-67140B7296B9 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by YusufJo** [comment]
@zoechi , yes the file exists, this is its content ..

```
package io.flutter.plugins;

import io.flutter.plugin.common.PluginRegistry;

/**
 * Generated file. Do not edit.
 */
public final class GeneratedPluginRegistrant {
  public static void registerWith(PluginRegistry registry) {
    if (alreadyRegisteredWith(registry)) {
      return;
    }
  }

  private static boolean alreadyRegisteredWith(PluginRegistry registry) {
    final String key = GeneratedPluginRegistrant.class.getCanonicalName();
    if (registry.hasPlugin(key)) {
      return true;
    }
    registry.registrarFor(key);
    return false;

  }
}
```
I ran the commands in the terminal and that's what i got for **flutter channel master**

```
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:    b8b6d4166..f0639bb02  master     -> origin/master
git: Switched to a new branch 'master'
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
```

**flutter doctor -v**

```
Downloading Dart SDK from Flutter engine 482469bad8094ff05fd66dfc07149fbef4ae00ac...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77.6M  100 77.6M    0     0   554k      0  0:02:23  0:02:23 --:--:--  566k
Building flutter tool...
Downloading package sky_engine...                            3.5s
Downloading common tools...                                 11.3s
Downloading darwin-x64 tools...                             48.3s
Downloading android-arm-profile/darwin-x64 tools...          7.5s
Downloading android-arm-release/darwin-x64 tools...          5.6s
Downloading android-arm64-profile/darwin-x64 tools...        7.3s
Downloading android-arm64-release/darwin-x64 tools...        6.0s
Downloading android-x86 tools...                            25.8s
Downloading android-x64 tools...                            25.5s
Downloading android-arm tools...                            13.8s
Downloading android-arm-profile tools...                    11.8s
Downloading android-arm-release tools...                    10.2s
Downloading android-arm64 tools...                          15.1s
Downloading android-arm64-profile tools...                  12.9s
Downloading android-arm64-release tools...                  11.4s
Downloading ios tools...                                    56.5s
Downloading ios-profile tools...                            47.8s
Downloading ios-release tools...                            42.4s
[✓] Flutter (Channel master, v0.5.8-pre.98, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.8-pre.98 at /Users/yusuf/development/flutter
    • Framework revision f0639bb022 (8 hours ago), 2018-07-20 09:21:41 +0200
    • Engine revision 482469bad8
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/yusuf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```
Now when i run my code i still face the same issue, but BTW when i run the code for the 2ed or the 3rd time it sometimes work, so i keep running it until it's working and then i stick with hot reload.
