### ISSUE TITLE
How to collect unknown exceptions/errors in run time?

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#19550]
I see all answers #10695 #11206,  in order to catch exceptions、errors must need `try...catch...`?
How to catch unknown dart exception? for example:
```
new Image.asert("images/back.png")
```
actually, image `back.png` does not exist, it will throw exception like:
```
 ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
    Unable to load asset: lib/images/backs.png
When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
    <asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
    <asynchronous suspension>
    #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
    #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
    #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
    #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
    (elided 8 frames from package dart:async)
Image provider: AssetImage(bundle: null, name: "lib/images/backs.png")
    Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#2707c(), name: "lib/images/backs.png",
    scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
How to catch these unknown error in run time?

**Comment by zoechi** [comment]
Support for that is work in progress https://github.com/flutter/flutter/pull/18424
