### ISSUE TITLE
Crash when trying to go back to the previous screen.

### ISSUE THREAD

**Issue by dooboolab** [flutter/flutter#19554]
Trying to figure out why this is occurring but currently no idea. I just came across the issue in the console.

```
flutter: When the exception was thrown, this was the stack:
flutter: #2      MultiChildRenderObjectElement.forgetChild (package:flutter/src/widgets/framework.dart)
flutter: #3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:2868:14)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2895:32)
flutter: #5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
flutter: #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #8      _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #47     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #65     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #69     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #73     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #81     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #85     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #92     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #93     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #94     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
Reloaded 2 of 423 libraries in 394ms.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the code of a minimal example that allows to reproduce.

**Comment by dooboolab** [comment]
@zoechi Sorry for that. I'll put the output next time. Close for now since it's not occurring anymore.

**Comment by zoechi** [comment]
No worries. Don't hesitate to create a new issue.
