### ISSUE TITLE
Flutter crash report when I run iOS emulators

### ISSUE THREAD

**Issue by CooperFu** [flutter/flutter#19556]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter emulators --launch iOS Simulator

## exception

_TypeError: type '_TypeError' is not a subtype of type 'String'

```
#0      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:75:20)
<asynchronous suspension>
#1      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#9      Future._complete (dart:async/future_impl.dart:472:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.6-pre.202, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.6-pre.202 at /Users/jackcooper/flutter
    • Framework revision e7832a3897 (3 days ago), 2018-07-14 09:32:41 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jackcooper/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/jackcooper/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L176w
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Looks like a dup of #19387.
Please upvote this issue instead.
