### ISSUE TITLE
FileSystemException: FileSystemException: Directory listing failed

### ISSUE THREAD

**Issue by ParkinWu** [flutter/flutter#19557]
I'm going to embed a new flutter app to an exsiting app, https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

the last step，something looks wrong, this is crash log

macOS Mojave 10.14 Beta (18A336e)

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --use-application-binary /Users/parkinwu/outofwork/flutter/embedder/build/ios/Debug-iphoneos/embedder.app -d iPhone X

## exception

FileSystemException: FileSystemException: Directory listing failed, path = '/var/folders/gh/9m3fw8sx7jv9wglkjdpyx1bc0000gn/T/flutter_app_iXRxJ3/Payload/' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37)
#1      _Directory.listSync (dart:io/directory_impl.dart:250)
#2      LocalFileSystemEntity&ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45)
#3      new IOSApp.fromIpa (package:flutter_tools/src/application_package.dart:158)
#4      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:277)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.14 18A336e, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/parkinwu/Documents/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L201y
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • iPhone 6s • CA2E2711-70E8-4EF0-9F5C-EE0622D00472 • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
    • iPhone X  • B6D3CAA2-F32E-4BE0-B256-FC81DF09FD77 • ios • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by MrMarik** [comment]
me too

**Comment by zoechi** [comment]
Could be a dup of #21297

**Comment by zoechi** [comment]
Is this only on Android or only iOS or both?
Is this only in release or also in debug mode?

**Comment by BigAlKo** [comment]
me too
@zoechi android and iOS and every time in release mode, in debug mode only sometimes

**Comment by matthew-carroll** [comment]
@ParkinWu @BigAlKo would either of you mind trying this again to see if the problem still exists?

Also, would you please provide the relevant logs from both the iOS and Android attempts?

Additionally, please describe the general structure of the app that you're adding to.  Is the project configuration customized at all?  Does the initial launching ViewController/Activity contain Flutter content? etc.

I've been using the add2app instructions for Android for a couple months and have never had any issue like this in debug or release mode.

**Comment by gspencergoog** [comment]
We can't reproduce this.  If you're still seeing this, please reopen this with more context, as @matthew-carroll  mentioned above.  Thanks!
