### ISSUE TITLE
Launching Activity that uses ARCore from Flutter causes crash

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#19566]
Trying to add a native activity that uses ARCore to my project.  However, once I launch it, the app crashes with the following error:
```
07-19 13:13:37.334 31792-31792/com.example.arcorefluttertest E/native: status.cc:158 ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT: 
07-19 13:13:37.335 31792-31792/com.example.arcorefluttertest D/AndroidRuntime: Shutting down VM
07-19 13:13:37.339 31792-31792/com.example.arcorefluttertest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.arcorefluttertest, PID: 31792
    com.google.ar.core.exceptions.MissingGlContextException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:73)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Unknown Source:12)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(Unknown Source:10)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source:16)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I have verified that the activity can run without crashing, as demonstrated in this video: https://www.youtube.com/watch?v=AzexF4h6x5g

I've uploaded the source code for the video here: https://github.com/KevinTheGray/flutterarcoreissue

I have verified this happens on a Nexus 5x running 8.1 and a Pixel, not sure the version of that.

## Steps to Reproduce

1. Create a Flutter project
2. From Flutter, launch an Activity that uses ARCore
3. Observe crash

Alternatively, you can clone the repo above and follow the same process in the video.  You will need to run from Android Studio or modify the Manifest if you want to use `flutter run`

## Logs
From Logcat

```
07-19 13:29:27.654 1793-1793/? I/zygote: Late-enabling -Xcheck:jni
07-19 13:29:27.736 1793-1793/com.example.arcorefluttertest W/ActivityThread: Application com.example.arcorefluttertest is waiting for the debugger on port 8100...
07-19 13:29:27.737 1793-1793/com.example.arcorefluttertest I/System.out: Sending WAIT chunk
07-19 13:29:28.680 1793-1802/com.example.arcorefluttertest I/zygote: Debugger is active
07-19 13:29:28.752 1793-1793/com.example.arcorefluttertest I/System.out: Debugger has connected
07-19 13:29:28.753 1793-1793/com.example.arcorefluttertest I/System.out: waiting for debugger to settle...
07-19 13:29:29.759 1793-1793/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) identical 5 lines
07-19 13:29:29.960 1793-1793/com.example.arcorefluttertest I/System.out: waiting for debugger to settle...
07-19 13:29:30.161 1793-1793/com.example.arcorefluttertest I/System.out: debugger has settled (1315)
07-19 13:29:30.416 1793-1822/com.example.arcorefluttertest D/OpenGLRenderer: HWUI GL Pipeline
07-19 13:29:30.474 1793-1822/com.example.arcorefluttertest I/Adreno: QUALCOMM build                   : 8e59954, I0be83d0d26
    Build Date                       : 09/22/17
    OpenGL ES Shader Compiler Version: EV031.21.02.00
    Local Branch                     : O17A
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
07-19 13:29:30.477 1793-1822/com.example.arcorefluttertest D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8992.so from current namespace instead of sphal namespace.
07-19 13:29:30.491 1793-1822/com.example.arcorefluttertest I/Adreno: PFP: 0x00000000, ME: 0x00000000
07-19 13:29:30.501 1793-1822/com.example.arcorefluttertest I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-19 13:29:30.503 1793-1822/com.example.arcorefluttertest I/OpenGLRenderer: Initialized EGL, version 1.4
07-19 13:29:30.503 1793-1822/com.example.arcorefluttertest D/OpenGLRenderer: Swap behavior 2
07-19 13:29:30.522 1793-1822/com.example.arcorefluttertest D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
07-19 13:29:30.524 1793-1822/com.example.arcorefluttertest D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8992.so from current namespace instead of sphal namespace.
07-19 13:30:42.515 1793-1902/com.example.arcorefluttertest I/flutter: Observatory listening on http://127.0.0.1:46262/
07-19 13:30:42.669 1793-1822/com.example.arcorefluttertest D/OpenGLRenderer: endAllActiveAnimators on 0xd34cde00 (RippleDrawable) with handle 0xd4c2ecb0
07-19 13:30:48.119 1793-1800/com.example.arcorefluttertest I/zygote: Do partial code cache collection, code=25KB, data=30KB
    After code cache collection, code=25KB, data=30KB
    Increasing code cache capacity to 128KB
07-19 13:30:48.185 1793-1793/com.example.arcorefluttertest I/Filament: FEngine (32 bits) created at 0xd457e800
07-19 13:30:48.275 1793-1793/com.example.arcorefluttertest W/linker: "/data/app/com.example.arcorefluttertest-88D56pH92BGWWiHOCLpEhw==/lib/arm/libarcore_sdk_jni.so" unused DT entry: type 0xf arg 0x2cb7
07-19 13:30:48.279 1793-1793/com.example.arcorefluttertest I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_create
07-19 13:30:48.284 1793-1793/com.example.arcorefluttertest I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 180604066
07-19 13:30:48.338 1793-1793/com.example.arcorefluttertest W/native: commandlineflags.cc:1512 Ignoring RegisterValidateFunction() for flag pointer 0xc5cdad68: no flag found at that address
07-19 13:30:48.338 1793-1793/com.example.arcorefluttertest I/native: version_check.cc:23 ARCore Version: APK version:1.3.180604066
    version_check.cc:24 ARCore Version: emulated SDK version:1.3.180525000
07-19 13:30:48.338 1793-1793/com.example.arcorefluttertest I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.3
    Dynamite load ok.
07-19 13:30:48.355 1793-1793/com.example.arcorefluttertest W/native: commandlineflags.cc:1512 Ignoring RegisterValidateFunction() for flag pointer 0xc5c72d00: no flag found at that address
07-19 13:30:48.358 1793-1793/com.example.arcorefluttertest I/native: session_create_implementation.cc:59 Entering ArSession_createImplementation. ARCore SDK version: [1.3.180525000].
07-19 13:30:48.358 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 20.)
    ~JniHelper: did not need to detach thread. (Called from line 648.)
    JniHelper: about to attach thread. (Called from line 79.)
    JniHelper: thread already attached. (Called from line 79.)
07-19 13:30:48.359 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 79.)
07-19 13:30:48.374 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 361.)
07-19 13:30:48.374 1793-1793/com.example.arcorefluttertest I/native: device_profile_conversions.cc:64 used_active_calibration: 2
07-19 13:30:48.375 1793-1793/com.example.arcorefluttertest I/native: profile_conversion.cc:116 MOTION_TRACKING_PRIMARY Android Camera ID is: 0
    profile_conversion.cc:121 COLOR_PRIMARY Android Camera ID is: 0
07-19 13:30:48.375 1793-1793/com.example.arcorefluttertest W/native: profile_conversion.cc:21 Camera facing direction unknown, setting REAR_FACING.
07-19 13:30:48.375 1793-1793/com.example.arcorefluttertest I/native: device_profile_conversions.cc:64 used_active_calibration: 2
07-19 13:30:48.376 1793-1793/com.example.arcorefluttertest I/native: profile_conversion.cc:116 MOTION_TRACKING_PRIMARY Android Camera ID is: 0
    profile_conversion.cc:121 COLOR_PRIMARY Android Camera ID is: 0
07-19 13:30:48.376 1793-1793/com.example.arcorefluttertest W/native: profile_conversion.cc:21 Camera facing direction unknown, setting REAR_FACING.
07-19 13:30:48.378 1793-1793/com.example.arcorefluttertest I/native: android_sensors.cc:51 Using uncalibrated accelerometer.
07-19 13:30:48.381 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 68.)
    JniHelper: thread already attached. (Called from line 68.)
07-19 13:30:48.381 1793-1927/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 188.)
07-19 13:30:48.381 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 68.)
07-19 13:30:48.382 1793-1927/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: attached thread. (Called from line 188.)
07-19 13:30:48.382 1793-1793/com.example.arcorefluttertest I/native: performance_manager.cc:22 Processor data: Num processors 6
    Processor type: LittleBig
    Num small cores 4
    Max frequency 1440000
    Min frequency 384000
    Small cores 0 1 2 3
    Num big cores 2
    Max frequency 1824000
    Min frequency 384000
    Big cores 4 5
07-19 13:30:48.383 1793-1793/com.example.arcorefluttertest I/native: device_provider.cc:1025 Identified device type: kBullhead
07-19 13:30:48.421 1793-1793/com.example.arcorefluttertest I/native: feature_combo_node.cc:148 Created feature-track-extender for klt-stitching.
    vio_helper.cc:48 Use calibrated IMU scale factors.
    vio_helper.cc:60 Use calibrated IMU misalignment factors.
07-19 13:30:48.570 1793-1793/com.example.arcorefluttertest W/AnchorServiceClientFactory: The API key for use with the Google AR service could not be obtained!
07-19 13:30:48.621 1793-1793/com.example.arcorefluttertest D/NetworkSecurityConfig: No Network Security Config specified, using platform default
07-19 13:30:48.685 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 271.)
    ~JniHelper: did not need to detach thread. (Called from line 175.)
07-19 13:30:48.688 1793-1793/com.example.arcorefluttertest I/native: fake_data_source.cc:24 FakeDataSource constructor
07-19 13:30:48.697 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 44.)
    JniHelper: thread already attached. (Called from line 44.)
07-19 13:30:48.700 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: did not need to detach thread. (Called from line 44.)
07-19 13:30:48.700 1793-1793/com.example.arcorefluttertest I/native: session_create_implementation.cc:186 ArSession_createImplementation returning OK.
07-19 13:30:48.707 1793-1793/com.example.arcorefluttertest I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc: Loading AImage symbols
07-19 13:30:48.708 1793-1793/com.example.arcorefluttertest I/third_party/arcore/ar/core/android/sdk/image_metadata_jni.cc: Loading ACameraMetadata symbols
07-19 13:30:48.743 1793-1793/com.example.arcorefluttertest W/linker: "/data/app/com.example.arcorefluttertest-88D56pH92BGWWiHOCLpEhw==/lib/arm/libarsceneview_jni.so" unused DT entry: type 0xf arg 0x4a0
07-19 13:30:48.744 1793-1793/com.example.arcorefluttertest I/native: session.cc:417 Entering Session::Resume.
07-19 13:30:48.744 1793-1793/com.example.arcorefluttertest V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: about to attach thread. (Called from line 44.)
    JniHelper: thread already attached. (Called from line 44.)
    ~JniHelper: did not need to detach thread. (Called from line 44.)
07-19 13:30:48.744 1793-1793/com.example.arcorefluttertest I/native: android_camera.cc:1083 Initializing camera manager.
07-19 13:30:48.746 1793-1793/com.example.arcorefluttertest I/native: android_camera.cc:1099 Camera manager initialized successfully with 2 cameras.
07-19 13:30:48.749 1793-1793/com.example.arcorefluttertest I/native: android_sensors.cc:94 Starting thread.
07-19 13:30:48.750 1793-1793/com.example.arcorefluttertest E/NdkImageReader: AImageReader_getWindow
07-19 13:30:48.750 1793-1946/com.example.arcorefluttertest I/native: android_sensors.cc:140 Gyro min delay 2.5ms requesting 5ms
07-19 13:30:48.755 1793-1946/com.example.arcorefluttertest I/native: android_sensors.cc:157 Accel min delay 2.5ms requesting 5ms
07-19 13:30:48.866 1793-1944/com.example.arcorefluttertest I/native: cameras.cc:715 Camera changed state from 0 to 1: Camera device opened succesfully.
    cameras.cc:715 Camera changed state from 1 to 2: Capture session starting...
    cameras.cc:715 Camera changed state from 2 to 3: Capture session started streaming.
07-19 13:30:48.866 1793-1793/com.example.arcorefluttertest I/native: session.cc:494 Session::Resume returning OK.
07-19 13:30:48.875 1793-1793/com.example.arcorefluttertest I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
07-19 13:30:48.881 1793-1793/com.example.arcorefluttertest E/native: session.cc:970 FrameHitTest while not tracking. Returning empty list.
07-19 13:30:49.115 1793-1947/com.example.arcorefluttertest I/native: timebase_helpers.cc:167 Timebase offset intialized to 33h22m58.329699539s
07-19 13:30:49.120 1793-1926/com.example.arcorefluttertest I/native: arcore_feature_extractor_wrapper.cc:29 Extracting features using  ArcoreFeatureExtractorWrapper.
07-19 13:30:49.120 1793-1926/com.example.arcorefluttertest I/native: arcore_feature_extractor_wrapper.cc:48 Narrow camera model.
07-19 13:30:49.156 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:49.156 1793-1930/com.example.arcorefluttertest W/native: gyro_helper.cc:59 Gyro samples do not cover << [ 0 ; 160287.813387817005 ] sec. Use identity R. Gyro samples cover [ 160287.545867220004 ; 160287.876019517018 ] sec.
    feature_processing.cc:152 Skipping first feature measurement because we don't have a previous to diff against.
07-19 13:30:49.157 1793-1933/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:49.157 1793-1933/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:49.158 1793-1930/com.example.arcorefluttertest I/native: vio_initializer.cc:635 Not accepting frame as first BA keyframe.
07-19 13:30:49.224 1793-1800/com.example.arcorefluttertest I/zygote: Do partial code cache collection, code=61KB, data=60KB
    After code cache collection, code=61KB, data=60KB
    Increasing code cache capacity to 256KB
07-19 13:30:49.228 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:49.238 1793-1793/com.example.arcorefluttertest I/Adreno: Invalid colorspace 1
07-19 13:30:49.240 1793-1793/com.example.arcorefluttertest E/native: session.cc:970 FrameHitTest while not tracking. Returning empty list.
07-19 13:30:49.245 1793-1928/com.example.arcorefluttertest I/native: vio_initializer.cc:635 Not accepting frame as first BA keyframe.
07-19 13:30:49.292 1793-1793/com.example.arcorefluttertest E/native: status.cc:158 ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT: 
07-19 13:30:49.294 1793-1793/com.example.arcorefluttertest D/AndroidRuntime: Shutting down VM
07-19 13:30:49.300 1793-1793/com.example.arcorefluttertest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.arcorefluttertest, PID: 1793
    com.google.ar.core.exceptions.MissingGlContextException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:73)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Unknown Source:12)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(Unknown Source:10)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source:16)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-19 13:30:49.425 1793-1929/com.example.arcorefluttertest I/native: vio_initializer.cc:635 Not accepting frame as first BA keyframe.
07-19 13:30:49.716 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:49.716 1793-1936/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:49.716 1793-1936/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:49.816 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:49.911 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:50.016 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:50.113 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 1 line
07-19 13:30:50.217 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:50.217 1793-1936/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:50.217 1793-1936/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:50.315 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:50.615 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 3 lines
07-19 13:30:50.718 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:50.720 1793-1931/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:50.720 1793-1931/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:50.824 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:51.127 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 3 lines
07-19 13:30:51.247 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:51.247 1793-1933/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:51.247 1793-1933/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:51.326 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:51.634 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 3 lines
07-19 13:30:51.729 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:51.731 1793-1932/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:51.731 1793-1932/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:51.828 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:52.126 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 3 lines
07-19 13:30:52.231 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:52.232 1793-1937/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:52.232 1793-1937/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:52.334 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:52.436 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:52.625 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 2 lines
07-19 13:30:52.728 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:52.728 1793-1937/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:52.729 1793-1937/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:52.831 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:53.130 1793-1926/com.example.arcorefluttertest I/chatty: uid=10944(com.example.arcorefluttertest) keypoint.lift identical 3 lines
07-19 13:30:53.228 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
07-19 13:30:53.229 1793-1936/com.example.arcorefluttertest I/native: image_target_detector.cc:187 Input query has too few keypoints.
07-19 13:30:53.229 1793-1936/com.example.arcorefluttertest E/native: planar_target_tracking_manager.cc:352 generic::unavailable: redwood::FAILED_PRECONDITION: VIO is not tracking
07-19 13:30:53.333 1793-1926/com.example.arcorefluttertest I/native: distribute.cc:92 No keypoints to prune.
```

```
$ flutter analyze
Analyzing arcorefluttertest...                                   
No issues found! (ran in 2.7s)
```

```
[✓] Flutter (Channel master, v0.5.8-pre.61, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.8-pre.61 at /Users/KG/Developer/Flutter/flutter
    • Framework revision b8b6d4166c (2 days ago), 2018-07-17 18:07:54 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Nexus 5X • 0106bcc49c8ca3eb • android-arm64 • Android 8.1.0 (API 27)
```

**Comment by KevinTheGray** [comment]
@jason-simmons hey, thanks for the quick feedback.  however I have found an issue that I believe is the same as this one. 

using the sample project above or with your own test project, if you follow these steps, it will crash with the same exception:

1. Launch an activity that uses ARCore
2. Exit from the activity back to Flutter
3. Open the activity that uses ARCore again and crash

Maybe the ARCore session is holding some sort of singleton reference to the GL context, and that is getting cleared by flutter

**Comment by KevinTheGray** [comment]
also I have updated to a version of flutter with the `flutter/engine#5895` in it.  My current flutter doctor:

```
[✓] Flutter (Channel master, v0.5.8-pre.195, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.8-pre.195 at /Users/KG/Developer/Flutter/flutter
    • Framework revision 2a66fd34a3 (12 hours ago), 2018-07-31 20:54:37 -0700
    • Engine revision 91ff524e63
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by jason-simmons** [comment]
Both Flutter and ARCore are trying to set the EGL context that is active on the application's main thread.

When you go back to the Flutter activity, Flutter will call eglMakeCurrent() to make Flutter's context active on the main thread for a short time during setup and teardown of the Flutter view.

The ARCore activity needs to reactivate ARCore's context when the activity is resumed.  But I'm not familiar with the ARCore API and how it manages ARCore's EGL context.

**Comment by KevinTheGray** [comment]
I see, thanks.  I'll take a look into the API and see what I need to do.

**Comment by etanxing** [comment]
Hey @KevinTheGray, have you figured out this issue? I'm facing the same.

**Comment by KevinTheGray** [comment]
@etanxing No, I have not figured it out, sorry.  The client ultimately decided to prioritize iOS first so I haven't had a chance to look into it yet.

**Comment by gedw99** [comment]
@mirobouma Can you put that working example on line ?

**Comment by khalithartmann** [comment]
Hey, im having the same problem. Would like to know if you fixed the problem and if yes, how ? 
thanks in advance :) !

**Comment by mirobouma** [comment]
@gedw99 Yes, i've used the code from that repository and wrapped it in a platform view (see this article: https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6 )

**Comment by khalithartmann** [comment]
thank you very much! Really appreciate it 👍

**Comment by khalithartmann** [comment]
hey @mirobouma , is there a specific reason why you didn't use Scenefrom? Im still inexperienced with openGL, so I wanted to ask you if it is possible to use Sceneform .

**Comment by mirobouma** [comment]
@khalithartmann sceneform manages the opengl context itself and because of how the way flutter works, it loses the opengl context for drawing, sceneform does not expose the functionality to properly manage therefore my only solution to fix the crashing issue was doing everything manually

**Comment by khalithartmann** [comment]
thats what i thought! thanks dude helped me a lot 👍

**Comment by khalithartmann** [comment]
@mirobouma  is it maybe possible to send me the whole project code ? doesnt matter if its a mess ^^.

**Comment by khalithartmann** [comment]
Checkout my new ARCore plugin : https://pub.dartlang.org/packages/arcore_plugin#-analysis-tab-
Feedback is always welcome
