### ISSUE TITLE
flutter devices --bug-report crashes every time.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19578]
Looks like a dart2 problem:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter devices --bug-report

## exception

`_TypeError: type 'Future<dynamic>' is not a subtype of type 'Future<RandomAccessFile>'`

```
#0      RecordingFile.open (org-dartlang-sdk:///sdk/lib/io/file.dart:456:28)
#1      Cache.lock (package:flutter_tools/src/cache.dart:77:82)
#2      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#3      Cache.lock (package:flutter_tools/src/cache.dart:73:27)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:313:23)
#5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:306:13)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _runZoned (dart:async/zone.dart:1518:10)
#13     runZoned (dart:async/zone.dart:1465:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#15     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:302:19)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#24     Future._complete (dart:async/future_impl.dart:472:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#27     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#28     getRecordingPlatform (package:flutter_tools/src/base/platform.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#30     _rootRunUnary (dart:async/zone.dart:1134:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#35     Future._complete (dart:async/future_impl.dart:472:7)
#36     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#37     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#38     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:292:13)
#39     _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:482:5)
#47     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512:7)
#48     _rootRun (dart:async/zone.dart:1126:13)
#49     _CustomZone.run (dart:async/zone.dart:1023:19)
#50     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

## flutter doctor

```
[✓] Flutter (Channel shard_tests, v0.5.8-pre.88, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.8-pre.88 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision a79c7d98f8 (22 hours ago), 2018-07-18 15:54:08 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-with-blaze-3.0
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/my-intellij-ce-2018.1
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • Nexus 6P • 84B7N15A07007628 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by gspencergoog** [comment]
This appears to be caused by: https://github.com/google/file.dart/issues/88

(I'm actually amazed that anything using file works at all now that Dart2 is turned on.)
