### ISSUE TITLE
ListView.builder exception after scroll to top

### ISSUE THREAD

**Issue by marosc** [flutter/flutter#19581]
```
Performing hot reload...
Reloaded 1 of 391 libraries in 1 833ms.
I/flutter ( 9883): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9883): The following assertion was thrown during a scheduler callback:
I/flutter ( 9883): 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 538 pos 12:
I/flutter ( 9883): 'elapsedInSeconds >= 0.0': is not true.
I/flutter ( 9883): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9883): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9883): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9883):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9883): When the exception was thrown, this was the stack:
I/flutter ( 9883): #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart)
I/flutter ( 9883): #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:229:5)
I/flutter ( 9883): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9883): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter ( 9883): #6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
I/flutter ( 9883): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter ( 9883): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter ( 9883): #9      _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 9883): #10     _beginFrame (dart:ui/hooks.dart:105:3)
I/flutter ( 9883): (elided 2 frames from class _AssertionError)
I/flutter ( 9883): This exception was thrown in the context of a scheduler callback. When the scheduler callback was
I/flutter ( 9883): _registered_ (as opposed to when the exception was thrown), this was the stack:
I/flutter ( 9883): #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:109:33)
I/flutter ( 9883): #1      new _FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:112:6)
I/flutter ( 9883): #2      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:426:53)
I/flutter ( 9883): #3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:244:46)
I/flutter ( 9883): #4      Ticker.start (package:flutter/src/scheduler/ticker.dart:159:7)
I/flutter ( 9883): #5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:471:41)
I/flutter ( 9883): #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:401:12)
I/flutter ( 9883): #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:318:12)
I/flutter ( 9883): #8      _GlowController._recede (package:flutter/src/widgets/overscroll_indicator.dart:423:21)
I/flutter ( 9883): #9      _GlowController.scrollEnd (package:flutter/src/widgets/overscroll_indicator.dart:393:7)
I/flutter ( 9883): #10     _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:204:28)
I/flutter ( 9883): #11     NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125:27)
I/flutter ( 9883): #12     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter ( 9883): #13     _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:35:18)
I/flutter ( 9883): #14     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3295:39)
I/flutter ( 9883): #15     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59:12)
I/flutter ( 9883): #16     DragScrollActivity.dispatchScrollEndNotification (package:flutter/src/widgets/scroll_activity.dart:461:7)
I/flutter ( 9883): #17     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:635:14)
I/flutter ( 9883): #18     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:604:9)
I/flutter ( 9883): #19     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:117:11)
I/flutter ( 9883): #20     ScrollPositionWithSingleContext.goIdle (package:flutter/src/widgets/scroll_position_with_single_context.dart:132:5)
I/flutter ( 9883): #21     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:151:7)
I/flutter ( 9883): #22     ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:390:14)
I/flutter ( 9883): #23     ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:457:12)
I/flutter ( 9883): #24     DragGestureRecognizer.didStopTrackingLastPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:209:45)
I/flutter ( 9883): #25     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 9883): #26     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:209:9)
I/flutter ( 9883): #27     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:231:9)
I/flutter ( 9883): #28     OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:240:7)
I/flutter ( 9883): #29     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:157:5)
I/flutter ( 9883): #30     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 9883): #31     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 9883): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
I/flutter ( 9883): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 9883): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 9883): #35     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 9883): #36     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 9883): #37     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 9883): #38     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 9883): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` and if possible the code that allows to reproduce.

**Comment by marosc** [comment]
I cant reproduce the exception.
