### ISSUE TITLE
Compiling flutter/engine on Mac with error

### ISSUE THREAD

**Issue by CLARKYJ** [flutter/flutter#19597]
hello
    I'm trying to compile flutter/engine, and I'm following guides here:
    https://github.com/flutter/engine/blob/master/CONTRIBUTING.md

    when I am using cmd "gclient sync" in folder "engine" as it recommended, I got promblems like this:
    

```
Bootstrapping cipd client for mac-amd64 from https://chrome-infra-packages.appspot.com/client?platform=mac-amd64&version=git_revision:521b9b64770d3b43a221b1e2bd277687616adacf...
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Syncing projects: 100% (84/84), done.                                           

________ running '/usr/bin/python src/tools/android/download_android_tools.py' in '/Users/jieyin/Documents/GitHub/debug/engine'
/Users/jieyin/Documents/GitHub/depot_tools/vpython: line 42: /Users/jieyin/Documents/GitHub/depot_tools/.cipd_bin/vpython: No such file or directory
/Users/jieyin/Documents/GitHub/depot_tools/vpython: line 42: exec: /Users/jieyin/Documents/GitHub/depot_tools/.cipd_bin/vpython: cannot execute: No such file or directory
/Users/jieyin/Documents/GitHub/depot_tools/vpython: line 42: /Users/jieyin/Documents/GitHub/depot_tools/.cipd_bin/vpython: No such file or directory
/Users/jieyin/Documents/GitHub/depot_tools/vpython: line 42: exec: /Users/jieyin/Documents/GitHub/depot_tools/.cipd_bin/vpython: cannot execute: No such file or directory
Running ['python', '/Users/jieyin/Documents/GitHub/depot_tools/gsutil.py', 'cp', 'gs://mojo/android/tool/fa5ea0ca1e0c7c2e40914f3202c7545de4dbca9c.tar.gz', '/Users/jieyin/Documents/GitHub/debug/engine/src/third_party/android_tools/sdk.tar.gz']
Failed.
WARNING: Failed to download Android tools.
Running ['python', '/Users/jieyin/Documents/GitHub/depot_tools/gsutil.py', 'cp', 'gs://mojo/android/tool/ed883dfaad6f27350eb3de426ccbf9abdc2943e8.tar.gz', '/Users/jieyin/Documents/GitHub/debug/engine/src/third_party/android_tools/ndk.tar.gz']
Failed.
WARNING: Failed to download Android tools.
Running hooks:  62% ( 5/ 8) dart      
________ running '/usr/bin/python src/tools/dart/update.py' in '/Users/jieyin/Documents/GitHub/debug/engine'
Traceback (most recent call last):
  File "src/tools/dart/update.py", line 92, in <module>
    sys.exit(main())
  File "src/tools/dart/update.py", line 82, in main
    urllib.urlretrieve(sdk_url, output_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1207, in getreply
    response = self._conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
IOError: [Errno socket error] [Errno 54] Connection reset by peer
Error: Command '/usr/bin/python src/tools/dart/update.py' returned non-zero exit status 1 in /Users/jieyin/Documents/GitHub/debug/engine
```

I think the warning is not that important, but error "update.py returned non-zero exit status 1" leads to
my failed to go on.

**Comment by CLARKYJ** [comment]
I have tried about 20 times， but everytime it failed at 62%，some said operation time out，some said unzip failed. I wanna know why I always failed at 62%

very disapointed...

**Comment by CLARKYJ** [comment]
or is there a mirror site ?

**Comment by zoechi** [comment]
cc @cbracken

**Comment by cbracken** [comment]
I can't say I've ever seen this issue before, but I see some non-Flutter-related mentions of similar issues on StackOverflow:

* [Curl returns “Unknown protocol”](https://stackoverflow.com/questions/21619468/curl-returns-unknown-protocol)
* [node-request - Getting error “SSL23_GET_SERVER_HELLO:unknown protocol”](https://stackoverflow.com/questions/15421050/node-request-getting-error-ssl23-get-server-hellounknown-protocol)

Do either of those help?

**Comment by huangturen** [comment]
I meet a similar trouble. After excuted "gclient sync", it always stopped at "Running hooks:  62% ( 5/ 8) dart ", and finally a error was catched
"""""""""
Error: Command '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/tools/dart/update.py' returned non-zero exit status 1 in "my engine path"

""""""""""

**Comment by zoechi** [comment]
@huangturen are you still seeing this?

**Comment by cbracken** [comment]
@huangturen one thing I note is that the `python` on your path is from homebrew and `gclient` and its associated tools is sometimes quite picky about the specific version of Python in use. You could try putting a symlink to the system python install (`/usr/bin/python`) somewhere earlier in your path than Homebrew (I typically do this in `~/bin`) and see if that helps.
