### ISSUE TITLE
Exception when showing AlertDialog with ListView or GridView content

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#19613]
Happens on the latest master version (Channel master, v0.5.8-pre.98).

This was tested with an Android emulator (Nexus 5), Android phone (Sony Xperia) and Android tablet.

The documentation recommends wrapping the contents of an `AlertDialog` into a `ListView`:

```dart
  /// Typically, this is a [ListView] containing the contents of the dialog.
  /// Using a [ListView] ensures that the contents can scroll if they are too
  /// big to fit on the display.
  final Widget content;
```

I did just that. It works very well in portrait orientation (at least on my phone), no matter how large the content is and if `shrinkWrap` is enabled or not.

But in landscape mode (both orientations on my tablet), the following errors are thrown (and only a semi-transparent backdrop is visible):

When `shrinkWrap: false`:
```
I/flutter (10060): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10060): The following assertion was thrown during performLayout():
I/flutter (10060): RenderViewport does not support returning intrinsic dimensions.
I/flutter (10060): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter (10060): defeats the point of viewports being lazy.
I/flutter (10060): If you are merely trying to shrink-wrap the viewport in the main axis direction, consider a
I/flutter (10060): RenderShrinkWrappingViewport render object (ShrinkWrappingViewport widget), which achieves that
I/flutter (10060): effect without implementing the intrinsic dimension API.
I/flutter (10060): 
I/flutter (10060): When the exception was thrown, this was the stack:
I/flutter (10060): #0      RenderViewportBase.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:299:9)
...
```
The error suggests that enabling `shrinkWrap` would solve the problem.

When `shrinkWrap: true`:
```
I/flutter (10721): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10721): The following assertion was thrown during performLayout():
I/flutter (10721): RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
I/flutter (10721): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter (10721): defeats the point of viewports being lazy.
I/flutter (10721): If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
I/flutter (10721): to achieve that effect by just giving the viewport loose constraints, without needing to measure its
I/flutter (10721): intrinsic dimensions.
I/flutter (10721): 
I/flutter (10721): When the exception was thrown, this was the stack:
I/flutter (10721): #0      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1544:9)
I/flutter (10721): #1      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:1554:6)
I/flutter (10721): #2      RenderViewportBase.computeMaxIntrinsicWidth (package:flutter/src/rendering/viewport.dart:321:12)
I/flutter (10721): #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #6      RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #11     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #16     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #21     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #23     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #24     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #25     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #26     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #28     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #29     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #30     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #31     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #34     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #36     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #38     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #39     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #40     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #41     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:81:20)
I/flutter (10721): #43     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #44     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #45     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #46     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #47     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:163:20)
I/flutter (10721): #48     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #49     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #50     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #51     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #52     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:575:60)
I/flutter (10721): #53     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:552:58)
I/flutter (10721): #54     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:572:12)
I/flutter (10721): #55     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (10721): #56     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10721): #57     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (10721): #58     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1291:12)
I/flutter (10721): #59     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:622:36)
I/flutter (10721): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #66     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1147:11)
I/flutter (10721): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #68     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:263:13)
I/flutter (10721): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #70     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (10721): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #72     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10721): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #76     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10721): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #88     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10721): #89     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2824:13)
I/flutter (10721): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10721): #91     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (10721): #92     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (10721): #93     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
I/flutter (10721): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (10721): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (10721): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (10721): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10721): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (10721): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (10721): #100    _invoke (dart:ui/hooks.dart:125:13)
I/flutter (10721): #101    _drawFrame (dart:ui/hooks.dart:114:3)
I/flutter (10721): 
I/flutter (10721): The following RenderObject was being processed when the exception was fired:
I/flutter (10721):   RenderIntrinsicWidth#1b077 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):   creator: IntrinsicWidth ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (10721):   _InkFeatures-[GlobalKey#02057 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (10721):   CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
I/flutter (10721):   Center ← ⋯
I/flutter (10721):   parentData: <none> (can use size)
I/flutter (10721):   constraints: BoxConstraints(280.0<=w<=512.0, 0.0<=h<=288.0)
I/flutter (10721):   size: MISSING
I/flutter (10721):   stepWidth: null
I/flutter (10721):   stepHeight: null
I/flutter (10721): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (10721):   RenderFlex#b6207 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):     RenderPadding#44560 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):       RenderSemanticsAnnotations#0847a NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):         RenderParagraph#4110e NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):     RenderPadding#b728b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):       RenderRepaintBoundary#22c8d NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):         RenderCustomPaint#f7921 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721):           RenderRepaintBoundary#f191e NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10721): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10721): Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#1b077 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (10721): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#fca13 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (10721): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#b713d relayoutBoundary=up3 NEEDS-PAINT
I/flutter (10721): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#968ac relayoutBoundary=up2 NEEDS-PAINT
I/flutter (10721): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
I/flutter (10721): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#968ac relayoutBoundary=up2
```

How to reproduce
------------------

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Dialog Landscape Error',
      home: new DialogTestScreen(),
    );
  }
}

class DialogTestScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Dialog Landscape Error'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            RaisedButton(
              child: Text('Open Dialog without shrinkWrap'),
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (BuildContext context) => TestDialog(shrinkWrap: false),
                );
              },
            ),
            RaisedButton(
              child: Text('Open Dialog with shrinkWrap'),
              onPressed: () {
                showDialog(
                  context: context,
                  builder: (BuildContext context) => TestDialog(shrinkWrap: true),
                );
              },
            ),
          ],
        )
      ),
    );
  }
}
```

**Comment by CalebQ42** [comment]
Having the same issue (on a Nexus 5X AVD). A quick fix is to use a SingleChildScrollView with a Column child. Works exactly the same as a ListView, but for some reason doesn't have any issue.

**Comment by MaskyS** [comment]
Hit this same issue today, but works when using SingleChildScrollView + Column as @CalebQ42 specified.

**Comment by zgusth** [comment]
I have the same problem but with GridView inside AlertDialog. It works fine on mobile, but not on tablets.

**Comment by ZeroCool00** [comment]
is it solved yet? i have a same issue today, gridview not rendring in ModalRoute. Tested in both ios and android

**Comment by sir-boformer** [comment]
In my experience, it works when you compile in release mode.

**Comment by eakers42** [comment]
I had the same problem. Was working on real device, failed with same error on simulator, both Android and iOS. It seems that the main issue for me was that the alert dialog did not have a defined size in the simulator for some reason. After defining a size with a container, I needed to add an Expanded widget to the ListView.builder.

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('Title'),
      content: Container(
        width: MediaQuery.of(context).size.width * 0.9,
        height: MediaQuery.of(context).size.height * 0.9,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: ListView.builder(
                itemCount: someList.length,
                itemBuilder: (BuildContext buildContext, int index) => buildRow(context, someList[index]),
                shrinkWrap: true,
              ),
            ),
          ],
        ),
      ),
    );
  }

Each row was built as follows with a ListTile
Widget buildRow(BuildContext context, MyContent content) {
    return ListTile(
      title: Text(title),
      subtitle: Text(info),
      isThreeLine: true,
      onTap: () => Navigator.of(context).pop(data),
    );
  }

**Comment by zoechi** [comment]
Looks similar to #18108
