### ISSUE TITLE
APP does not open on install 

### ISSUE THREAD

**Issue by SagarKarwande** [flutter/flutter#19641]
When I build the APP through Android studio, it gets installed on phone but closes suddenly and throws following `error` in the Android studio console.

```
Launching lib/main.dart on HTC Desire 820G PLUS dual sim in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(30286): onResume setting current activity to this
E/DartVM  (30286): vm-service: Error: Unhandled exception:
E/DartVM  (30286): 'dart:async/future_impl.dart': error: Unexpected tag 0 (Nothing) in ?, expected type
E/DartVM  (30286): #0      Future._thenNoZoneRegistration (dart:async/future_impl.dart:250:5)
E/DartVM  (30286): #1      _awaitHelper (dart:async/runtime/libasync_patch.dart:110:17)
E/DartVM  (30286): #2      Server.startup (dart:vmservice_io/server.dart:364:13)
E/DartVM  (30286): <asynchronous suspension>
E/DartVM  (30286): #3      main (dart:vmservice_io:239:12)
E/DartVM  (30286): 
E/flutter (30286): [ERROR:flutter/runtime/dart_isolate.cc(719)] Isolate (1032737077) 'vm-service' exited with an error
E/flutter (30286): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30286): 'dart:async/future_impl.dart': error: Unexpected tag 0 (Nothing) in ?, expected type
E/flutter (30286): #0      Future._thenNoZoneRegistration (dart:async/future_impl.dart:250:5)
E/flutter (30286): #1      _awaitHelper (dart:async/runtime/libasync_patch.dart:110:17)
E/flutter (30286): #2      Server.startup (dart:vmservice_io/server.dart:364:13)
E/flutter (30286): <asynchronous suspension>
E/flutter (30286): #3      main (dart:vmservice_io:239:12)
Application finished.

```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by SagarKarwande** [comment]
@zoechi 
```
[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_IN)
    • Flutter version 0.4.4 at /home/sagar/flutter_dev/flutter
    • Framework revision f9bb4289e9 (2 months ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/sagar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.18.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • HTC Desire 820G PLUS dual sim • LC56BB420389 • android-arm • Android 4.4.2 (API 19)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
That's an outdated Flutter version. You should update at least to beta 0.5.1 or probably the `dev` or `master` channel.
```
flutter upgrade
```
and/or
```
flutter channel dev
flutter doctor
```

**Comment by SagarKarwande** [comment]
On running `flutter upgrade` and running the new counter app from android studio following are the result

flutter doctor -v
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_IN)
    • Flutter version 0.5.1 at /home/sagar/flutter_dev/flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/sagar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.18.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • HTC Desire 820G PLUS dual sim • LC56BB420389 • android-arm • Android 4.4.2 (API 19)

! Doctor found issues in 1 category.
```
Errors on Android Studio after the app gets installed on phone 
```
Launching lib/main.dart on HTC Desire 820G PLUS dual sim in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
E/DartVM  (11855): 'dart:core/string.dart': error: Unexpected tag 176 (Unknown) in ?, expected expression
E/DartVM  (11855): ../../third_party/dart/runtime/vm/compiler/intrinsifier.cc: 153: error: Intrinsifier failed to find method get:hashCode in class _StringBase
E/DartVM  (11855): 
E/DartVM  (11855): Dumping native stack trace for thread 2e68
E/DartVM  (11855):   [0x4989b6a9] Unknown symbol
E/DartVM  (11855):   [0x4989b6a9] Unknown symbol
E/DartVM  (11855): -- End of DumpStackTrace
E/DartVM  (11855): 'dart:core/string.dart': error: Unexpected tag 176 (Unknown) in ?, expected expression
E/DartVM  (11855): ../../third_party/dart/runtime/vm/compiler/intrinsifier.cc: 153: error: Intrinsifier failed to find method get:hashCode in class _StringBase
E/DartVM  (11855): 
E/DartVM  (11855): Aborting re-entrant request for stack trace.
E/DartVM  (11971): 'dart:typed_data/runtime/libtyped_data_patch.dart': error: Unexpected tag 0 (Nothing) in ?, expected expression
E/DartVM  (11971): ../../third_party/dart/runtime/vm/compiler/intrinsifier.cc: 153: error: Intrinsifier failed to find method [] in class _Int32List
E/DartVM  (11971): 
E/DartVM  (11971): Dumping native stack trace for thread 2eda
E/DartVM  (11971):   [0x4989b6a9] Unknown symbol
E/DartVM  (11971):   [0x4989b6a9] Unknown symbol
E/DartVM  (11971): -- End of DumpStackTrace
```

**Comment by SagarKarwande** [comment]
Also tried the dev channel and following are result for new counter app installation from android studio

flutter doctor -v
```
[✓] Flutter (Channel dev, v0.5.7, on Linux, locale en_IN)
    • Flutter version 0.5.7 at /home/sagar/flutter_dev/flutter
    • Framework revision 66091f9696 (13 days ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/sagar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.18.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • HTC Desire 820G PLUS dual sim • LC56BB420389 • android-arm • Android 4.4.2 (API 19)

! Doctor found issues in 1 category.

```

Errors on Android Studio after the app gets installed on phone
```
Launching lib/main.dart on HTC Desire 820G PLUS dual sim in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
E/DartVM  (23935): 'dart:_internal/list.dart': error: Unexpected tag 224 (Unknown) in ?, expected type
E/DartVM  (23935): ../../third_party/dart/runtime/vm/compiler/intrinsifier.cc: 169: error: Intrinsifier failed to find method get:length in class _ImmutableList
E/DartVM  (23935): 
E/DartVM  (23935): Dumping native stack trace for thread 5d9b
E/DartVM  (23935):   [0x498792a1] Unknown symbol
E/DartVM  (23935):   [0x498792a1] Unknown symbol
E/DartVM  (23935): -- End of DumpStackTrace
```

**Comment by SagarKarwande** [comment]
Looks like the issue is with my device. I tried app installation with other devices, there it works fine.

**Comment by zoechi** [comment]
I assume this issue is stale.
Please add a comment to have it reopened if you have more information about how to reproduce.

**Comment by zoechi** [comment]
Duplicate of #17747
