### ISSUE TITLE
Issue from website page Implement Swipe to Dismiss

### ISSUE THREAD

**Issue by Quinzel** [flutter/flutter#19646]
From URL: https://flutter.io/cookbook/gestures/dismissible/

Hi,
When removing all items from the list I'm getting RangeError exception every time. (I've copy-pasted the code)
```
Restarted app in 1 234ms.
I/flutter (18779): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18779): The following RangeError was thrown while notifying listeners for AnimationController:
I/flutter (18779): RangeError (index): Invalid value: Not in range 0..1, inclusive: 3
I/flutter (18779): 
I/flutter (18779): When the exception was thrown, this was the stack:
I/flutter (18779): #0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
I/flutter (18779): #1      List.removeAt (dart:core/runtime/libgrowable_array.dart:27:22)
I/flutter (18779): #2      MyApp.build.<anonymous closure>.<anonymous closure> (file:///G:/Env/project/todo/doorsplit/lib/main.dart:38:23)
I/flutter (18779): #3      _DismissibleState._handleResizeProgressChanged (package:flutter/src/widgets/dismissible.dart:443:16)
I/flutter (18779): #4      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
I/flutter (18779): #5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:546:5)
I/flutter (18779): #6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:229:5)
I/flutter (18779): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (18779): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (18779): #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
I/flutter (18779): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (18779): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (18779): #12     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (18779): #13     _beginFrame (dart:ui/hooks.dart:105:3)
I/flutter (18779): 
I/flutter (18779): The AnimationController notifying listeners was:
I/flutter (18779):   AnimationController#83455(⏭ 1.000; paused)
I/flutter (18779): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Sfshaza** [comment]
@brianegan

**Comment by brianegan** [comment]
Good call, I'll fix that up!

**Comment by brianegan** [comment]
Fix posted here: https://github.com/flutter/website/pull/1120
