### ISSUE TITLE
Can not create flutter project on windows 10 (x64)

### ISSUE THREAD

**Issue by tushroy** [flutter/flutter#19741]
Tried to create a new flutter project but flutter exiting unexpectedly each time.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create proj_1

## exception

FileSystemException: FileSystemException: Cannot create file, path = 'E:\Local_Repository\zxcz\proj_1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:647)
#1      _File.createSync (dart:io/file_impl.dart:285)
#2      LocalFileSystemEntity&ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:23)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:132)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#5      Template.render (package:flutter_tools/src/template.dart:108)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:321)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:221)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Did you try a different drive or directory?
The error indicates that your user doesn't have sufficient permission for this directory but that's weird because the parent directories were created by `flutter create`.
Perhaps some anti-virus software caused the issue?

**Comment by tushroy** [comment]
Thanks, tried to run the command turning off kaspersky antivirus and it able to create the files. 
But got another problem.
Now i am stuck on
`
Running "flutter packages get" in test1...
Could not resolve URL "https://pub.dartlang.org".
pub get failed (69) -- attempting retry 1 in 1 second...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 2 in 2 seconds...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 3 in 4 seconds...
`

**FYI: I am behind a corporate proxy, Is there any way to set proxy for flutter**?

**Comment by zoechi** [comment]
Are you using a proxy to access the internet?

**Comment by tushroy** [comment]
@zoechi Yes and I have solved the issue setting environment variable `https_proxy`
