### ISSUE TITLE
I code a slide, but sometimes it will throw a NoSuchMethodError, why?

### ISSUE THREAD

**Issue by hozhis** [flutter/flutter#19756]
```
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
Receiver: null
Tried calling: inheritFromWidgetOfExactType(_TabControllerScope)
#0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1 DefaultTabController.of (package:flutter/src/material/tab_controller.dart:280:47)
#2 _SlidePageSelectorState._handleArrowButtonPress (package:jixiaoshi/layout/home.dart:232:59)
#3 _SlidePageSelectorState.initState. (package:jixiaoshi/layout/home.dart:227:7)
#4 _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5 _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
Receiver: null
Tried calling: inheritFromWidgetOfExactType(_TabControllerScope)
#0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1 DefaultTabController.of (package:flutter/src/material/tab_controller.dart:280:47)
#2 _SlidePageSelectorState._handleArrowButtonPress (package:jixiaoshi/layout/home.dart:232:59)
#3 _SlidePageSelectorState.initState. (package:jixiaoshi/layout/home.dart:227:7)
#4 _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5 _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
```

```dart
class SlidePage {
  SlidePage({@required this.image, this.routeName, this.params})
      : assert(image != null);

  final String image;

  final String routeName;

  final Map params;
}

class _SlidePageSelector extends StatefulWidget {
  const _SlidePageSelector({this.pages});

  final List<SlidePage> pages;

  @override
  _SlidePageSelectorState createState() => _SlidePageSelectorState();
}

class _SlidePageSelectorState extends State<_SlidePageSelector> {
  final GlobalKey<_SlidePageSelectorState> selectorKey =
      GlobalKey<_SlidePageSelectorState>();

  @override
  void initState() {
    super.initState();

    /// 启动轮播图定时器
    Timer.periodic(Duration(milliseconds: 3800), (timer) {
      _autoSlide(selectorKey.currentContext, 1);
    });
  }

  void _autoSlide(BuildContext context, int delta) {
    final TabController controller = DefaultTabController.of(context);
    final List<SlidePage> pages = widget.pages;

    if (!controller.indexIsChanging) {
      if (controller.index >= pages.length - 1 && delta > 0) {
        controller.animateTo(
          (controller.index - pages.length + 1).clamp(0, pages.length - 1),
        );
      } else if (controller.index <= 0 && delta < 0) {
        controller.animateTo(
          (controller.index + pages.length - 1).clamp(0, pages.length - 1),
        );
      } else {
        controller.animateTo(
          (controller.index + delta).clamp(0, pages.length - 1),
        );
      }
    }
  }

  void _handleDragUpdateGesture(DragUpdateDetails details) {}

  @override
  Widget build(BuildContext context) {
    final List<SlidePage> pages = widget.pages;
    final TabController controller = DefaultTabController.of(context);
    return SafeArea(
      key: selectorKey,
      top: false,
      bottom: false,
      child: Column(
        children: <Widget>[
          Expanded(
            child: Stack(
              children: <Widget>[
                GestureDetector(
                  onHorizontalDragUpdate: _handleDragUpdateGesture,
                  onTap: () {
//                    Navigator.pushNamed(context, '/login');
                  },
                  child: TabBarView(
                    children: pages.map(
                      (SlidePage page) {
                        return Container(
                          child: Card(
                            elevation: 0.0,
                            margin: EdgeInsets.zero,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(0.0),
                            ),
                            child: Image.network(
                              page.image,
                              fit: BoxFit.cover,
                              alignment: Alignment.topCenter,
                            ),
                          ),

                          /// end of Card
                        );
                      },
                    ).toList(),
                  ),
                ),

                /// end of GestureDetector

                Positioned(
                  bottom: 5.0,
                  left: 10.0,
                  right: 10.0,
                  child: Center(
                    child: TabPageSelector(
                      controller: controller,
                      color: Color(0xFFFFFFF0),
                      selectedColor: Colors.amberAccent,
                      indicatorSize: 3.0,
                      shape: IndicatorShape.rectangle,
                    ),
                  ),
                ),
              ],
            ),

            /// end of Stack
          ),

          /// end of Expanded
        ],
      ),
    );
  }
}
```

**Comment by hozhis** [comment]
![img_3403 trim](https://user-images.githubusercontent.com/12829578/43195267-1cbf110c-9037-11e8-9251-f3e3fb0db990.gif)

**Comment by zoechi** [comment]
Thanks for the reproduction!
Can you elaborate on "sometimes"?
Is this after it runs for a longer time or after hot-reload, ...?
The code runs here but I haven't seen the exception yet.

**Comment by zoechi** [comment]
You could try to 

```dart
...
  Timer _timer;
  
  @override
  void initState() {
    super.initState();

    /// 启动轮播图定时器
    _timer = Timer.periodic(Duration(milliseconds: 3000), (timer) {
      _autoSlide(selectorKey.currentContext, 1);
    });
  }
  
  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  void _autoSlide(BuildContext context, int delta) {
    assert(context != null);
...
```

**Comment by hozhis** [comment]
@zoechi , I have tried the code you suggested, but it still have errors. 

````
Performing hot reload...
Reloaded 4 of 403 libraries in 1,118ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while finalizing the widget tree:
flutter: The method 'cancel' was called on null.
flutter: Receiver: null
flutter: Tried calling: cancel()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
flutter: #1      _SlidePageSelectorState.dispose (package:jixiaoshi/layout/home.dart:235:12)
flutter: #2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3834:12)
flutter: #3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
flutter: #4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #14     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4655:14)
flutter: #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
flutter: #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3689:14)
flutter: #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
flutter: #40     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #41     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
flutter: #42     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2341:27)
flutter: #43     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2173:15)
flutter: #44     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2340:7)
flutter: #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628:18)
flutter: #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #50     _invoke (dart:ui/hooks.dart:120:13)
flutter: #51     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:jixiaoshi/layout/home.dart': Failed assertion: line 240 pos 12: 'null': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      _SlidePageSelectorState._autoSlide (package:jixiaoshi/layout/home.dart)
#3      _SlidePageSelectorState.initState.<anonymous closure> (package:jixiaoshi/layout/home.dart:227:7)
#4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


````

**Comment by zoechi** [comment]
Weird, it's disposed before it's initialized.
Try instead
```dart
timer?.cancel();
```

**Comment by hozhis** [comment]
````
A TabController was used after being disposed.
Once you have called dispose() on a TabController, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:155:12)
#3      TabController._changeIndex.<anonymous closure> (package:flutter/src/material/tab_controller.dart:124:11)
#4      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:390:15)
#5      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#6      _FutureListener.handleError (dart:async/future_impl.dart:147:20)
#7      Future._propagateToListeners.handleError (dart:async/future_impl.dart:650:47)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:24)
#9   <…>
````

**Comment by zoechi** [comment]
I can not reproduce both issues 

> 'package:jixiaoshi/layout/home.dart': Failed assertion: line 240 pos 12: 'null': is not true.

and 

> A TabController was used after being disposed.

With above code what actions do I have to take (step by step) to reproduce?

Can you please try if you can reproduce in `master` channel?

```
flutter channel master
flutter doctor
```
