### ISSUE TITLE
scroll_controller.dart: _positions.length == 1

### ISSUE THREAD

**Issue by smm13344331** [flutter/flutter#19764]
```
The following assertion was thrown building AnimatedBuilder(animation: PageController#3cc22(2
I/flutter (25966): clients), dirty, state: _AnimatedState#4590f):
I/flutter (25966): ScrollController attached to multiple scroll views.
I/flutter (25966): 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12:
I/flutter (25966): '_positions.length == 1'
I/flutter (25966): 
I/flutter (25966): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25966): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25966): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25966):   https://github.com/flutter/flutter/issues/new
I/flutter (25966): 
I/flutter (25966): When the exception was thrown, this was the stack:
I/flutter (25966): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart)
I/flutter (25966): #3      _CarouselSliderState.build.<anonymous closure>.<anonymous closure> (package:carousel_slider/carousel_slider.dart:133:41)
I/flutter (25966): #4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:633:12)
I/flutter (25966): #5      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:96:48)
I/flutter (25966): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (25966): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (25966): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (25966): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (25966): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (25966): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (25966): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (25966): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (25966): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (25966): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (25966): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (25966): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (25966): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (25966): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (25966): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (25966): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (25966): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (25966): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (25966): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (25966): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (25966): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (25966): #27     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3968:11)
I/flutter (25966): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (25966): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (25966): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (25966): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (25966): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (25966): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (25966): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (25966): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (25966): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (25966): #37     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter (25966): #38     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
I/flutter (25966): #39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (25966): #40     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter (25966): #41     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter (25966): #42     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter (25966): #43     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:735:15)
I/flutter (25966): #44     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter (25966): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter (25966): #46     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
I/flutter (25966): #47     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:169:12)
I/flutter (25966): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #49     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (25966): #50     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1311:12)
I/flutter (25966): #51     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1229:20)
I/flutter (25966): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #69     RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:522:13)
I/flutter (25966): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #73     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter (25966): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #75     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (25966): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #77     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (25966): #78     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1311:12)
I/flutter (25966): #79     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1229:20)
I/flutter (25966): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #97     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter (25966): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (25966): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #101    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:199:18)
I/flutter (25966): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (25966): #103    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (25966): #104    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1311:12)
I/flutter (25966): #105    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1229:20)
I/flutter (25966): #106    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (25966): #107    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
I/flutter (25966): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (25966): #109    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (25966): #110    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (25966): #111    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25966): #112    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25966): #113    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (25966): #114    _invoke (dart:ui/hooks.dart:120:13)
I/flutter (25966): #115    _drawFrame (dart:ui/hooks.dart:109:3)
D/ViewRootImpl@256a8a1[MainActivity](25966): ViewPostIme pointer 1
I/flutter (25966): (elided 2 frames from class _AssertionError)
```

**Comment by smm13344331** [comment]
To reproduce this I have to share the whole app , which unfortunately I cannot. I have no idea when, or how this happens but, basically this happens sometimes at the middle of scrolling a PageView, something very much like [this ](https://stackoverflow.com/questions/51250646/how-to-zoom-image-inside-listview-in-flutter/51464717#51464717) scenario .

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by smm13344331** [comment]
I think this issue needs to be closed, because I cannot reproduce it.

**Comment by zoechi** [comment]
@smm13344331 thanks for the update.
Don't hesitate to add a comment to get it reopened or to create a new issue if you run into this again.

**Comment by smm13344331** [comment]
@zoechi thank you for the good job on the project and your lightning fast responses.

**Comment by zoechi** [comment]
Similar error in https://stackoverflow.com/questions/53824944/flutter-exception-scrollcontroller-attached-to-multiple-scroll-views

**Comment by patelkrunal78** [comment]
if you would like to immediately scroll to the bottom of the list on start (in the initState()), you can place the following code chunk from Collin’s solution before the first time you call setState().

This Can Help Chek It [Here ](https://icetutor.com/question/how-to-get-full-size-of-a-scrollcontroller)

**Comment by tharwatsamy** [comment]
`
class AdvertismentView extends StatelessWidget {
  final List<String> _tabs = ['المدينه', 'الحي', 'الاقرب'];
  @override
  Widget build(BuildContext context) {
    // final statusBarHeight = MediaQuery.of(context).padding.top;
    // var pinnedHeaderHeight = statusBarHeight + kToolbarHeight;
    return DefaultTabController(
      length: _tabs.length,
      child: Scaffold(
        backgroundColor: Colors.white,
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            // These are the slivers that show up in the "outer" scroll view.
            return <Widget>[
              SliverOverlapAbsorber(
                // This widget takes the overlapping behavior of the SliverAppBar,
                // and redirects it to the SliverOverlapInjector below. If it is
                // missing, then it is possible for the nested "inner" scroll view
                // below to end up under the SliverAppBar even when the inner
                // scroll view thinks it has not been scrolled.
                // This is not necessary if the "headerSliverBuilder" only builds
                // widgets that do not overlap the next sliver.
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title:
                      const Text('Books'), // This is the title in the app bar.
                  pinned: true,
                  expandedHeight: 150.0,
                  // The "forceElevated" property causes the SliverAppBar to show
                  // a shadow. The "innerBoxIsScrolled" parameter is true when the
                  // inner scroll view is scrolled beyond its "zero" point, i.e.
                  // when it appears to be scrolled below the SliverAppBar.
                  // Without this, there are cases where the shadow would appear
                  // or not appear inappropriately, because the SliverAppBar is
                  // not actually aware of the precise position of the inner
                  // scroll views.
                  forceElevated: innerBoxIsScrolled,
                  bottom: TabBar(
                    // These are the widgets to put in each tab in the tab bar.
                    tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: Center(
            child: GestureDetector(
              onTap: () {
                Get.to(DetailsView());
              },
              child: Container(
                child: const Text('Throws an Exception'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
`

This code produce this exception  
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1440], locale ar-EG)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.55.0)
[√] Connected device (3 available)
