### ISSUE TITLE
The following assertion was thrown building NotificationListener<KeepAliveNotification>:

### ISSUE THREAD

**Issue by Jon-Millent** [flutter/flutter#19809]
Hello, I am trying to use flutter to make an app, but I have a problem.     
I saw a similar problem, but I still can't find a solution.  
We will use flutter in the next project, I hope to help me, thank you very much!

# problem
![Video_2018-07-26_155305.gif](https://i.loli.net/2018/07/26/5b5982c392568.gif)

# code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

typedef double GetOffsetMethod();
typedef void SetOffsetMethod(double offset);

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  TabController controller;
  double listViewOffset=0.0;

  @override
  void initState() {
    super.initState();
    controller = new TabController(
      length: 4,
      vsync: this,
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    var tabs = <Tab>[
      new Tab(icon: new Icon(Icons.home), text: 'Tab 1'),
      new Tab(icon: new Icon(Icons.account_box), text: 'Tab 2'),
      new Tab(icon: new Icon(Icons.account_box), text: 'Tab 3'),
      new Tab(icon: new Icon(Icons.account_box), text: 'Tab 4'),
    ];

    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new TabBarView(
          controller: controller,
          children: <Widget>[
            new StatefulListView(
              getOffsetMethod: () => listViewOffset,
              setOffsetMethod: (offset) => this.listViewOffset = offset,
            ),
            new Center(child: new Text('Tab 2')),
            new StatefulListView(
              getOffsetMethod: () => listViewOffset,
              setOffsetMethod: (offset) => this.listViewOffset = offset,
            ),
            new StatefulListView(
              getOffsetMethod: () => listViewOffset,
              setOffsetMethod: (offset) => this.listViewOffset = offset,
            )
          ]),
      bottomNavigationBar: new Material(
        color: Colors.deepOrange,
        child: new TabBar(controller: controller, tabs: tabs),
      ),
    );
  }
}

class StatefulListView extends StatefulWidget {
  StatefulListView({Key key, this.getOffsetMethod, this.setOffsetMethod}) : super(key: key);

  final GetOffsetMethod getOffsetMethod;
  final SetOffsetMethod setOffsetMethod;

  @override
  _StatefulListViewState createState() => new _StatefulListViewState();
}

class _StatefulListViewState extends State<StatefulListView> with AutomaticKeepAliveClientMixin{

  ScrollController scrollController;


  @override
  bool get wantKeepAlive => true;


  @override
  void initState() {
    super.initState();
    scrollController = new ScrollController(
//        initialScrollOffset: widget.getOffsetMethod()
    );
  }

  @override
  Widget build(BuildContext context) {
    return new NotificationListener(
      child: new ListView.builder(
        controller: scrollController,
        itemCount: 50,
        itemBuilder: (BuildContext context, int index) {
          return new Text("Data------------------------------ "+index.toString());
        },
      ),
      onNotification: (notification) {
        if (notification is ScrollNotification) {
          widget.setOffsetMethod(notification.metrics.pixels);
        }
      },
    );
  }
}
```

# logs

```cmd
I/flutter ( 5076): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5076): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 5076): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14:
I/flutter ( 5076): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 5076): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5076): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5076): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5076):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5076): When the exception was thrown, this was the stack:
I/flutter ( 5076): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart)
I/flutter ( 5076): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2809:5)
I/flutter ( 5076): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 5076): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:865:18)
I/flutter ( 5076): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4513:35)
I/flutter ( 5076): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4279:5)
I/flutter ( 5076): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4653:11)
I/flutter ( 5076): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5076): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5076): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 5076): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 5076): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5076): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5076): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 5076): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 5076): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter ( 5076): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5076): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5076): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 5076): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 5076): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 5076): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5076): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5076): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter ( 5076): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
I/flutter ( 5076): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter ( 5076): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter ( 5076): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 5076): #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 5076): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 5076): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5076): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 5076): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 5076): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5076): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5076): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #77     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 5076): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 5076): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter ( 5076): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 5076): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 5076): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5076): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 5076): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 5076): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 5076): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5076): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5076): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5076): #95     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 5076): #96     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 5076): (elided 2 frames from class _AssertionError)
I/flutter ( 5076): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2775 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3497 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5076): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
I/flutter ( 5076): Another exception was thrown: type 'RenderErrorBox' is not a subtype of type 'RenderSemanticsGestureHandler'
I/flutter ( 5076): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
I/flutter ( 5076): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#3bee0 NEEDS-LAYOUT NEEDS-PAINT

```

# info
```flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.15063], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.0)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (2 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
I think this is an issue that was fixed a while ago.
Can you please try with a more recent Flutter version?
```
flutter upgrade
```

**Comment by CarGuo** [comment]
`flutter upgrade`  0.5.7 work for me.
but in my case i have 4 tab， not all the time KeepAlive with AutomaticKeepAliveClientMixin, tab2 will reload when tab2 -> tab4 -> tab1 -> tab2.

**Comment by zoechi** [comment]
@CarGuo can you please create a new issue for that part with the issue template filled (code to reproduce, `flutter doctor -v` output, ...)

**Comment by pickupsb** [comment]
> I think this is an issue that was fixed a while ago.
> Can you please try with a more recent Flutter version?
> 
> ```
> flutter upgrade
> ```

not fixed,still happens in version 0.96

**Comment by pickupsb** [comment]
> `flutter upgrade` 0.5.7 work for me.
> but in my case i have 4 tab， not all the time KeepAlive with AutomaticKeepAliveClientMixin, tab2 will reload when tab2 -> tab4 -> tab1 -> tab2.

the same problem

**Comment by gbarnett** [comment]
Also experiencing this problem

**Comment by zoechi** [comment]
The issue is long closed.
Please create a new issue with properly filled out issue template.
