### ISSUE TITLE
Failed assertion: 'debugDoingThisResize || debugDoingThisLayout || (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#19812]
When I select text and tap on "Copy" in the context menu of a multiline TextField

```
I/flutter (22886): 2075 2018-07-26 14:57:54.578159 SEVERE lookatmybaby_flutter.sentry_error_reporter: Context: building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#449f5](dirty, state: _OverlayEntryState#0a771), library: widgets library
I/flutter (22886):     error: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter (22886):                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.
I/flutter (22886): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
I/flutter (22886): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
I/flutter (22886): #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart)
I/flutter (22886): #3      RenderBox.size (package:flutter/src/rendering/box.dart:1509:6)
I/flutter (22886): #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2370:24)
I/flutter (22886): #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2103:24)
I/flutter (22886): #6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2027:39)
I/flutter (22886): #7      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:413:20)
I/flutter (22886): #8      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter (22886): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (22886): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (22886): #11     Element.rebuild (package:flutter/src/widgets/framework.dar
```

```
[✓] Flutter (Channel master, v0.5.8-pre.127, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.127 at /Users/zoechi/flutter/flutter
    • Framework revision da0e898da9 (2 days ago), 2018-07-25 01:39:23 +0200
    • Engine revision 95e91e31fa
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Dup of #14489
