### ISSUE TITLE
[Issue] Flutter Driver Test is not running with Dart 2

### ISSUE THREAD

**Issue by nosmirck** [flutter/flutter#19817]
The Flutter Driver is not running with Dart 2.0 (I found out by writing my own tests and figured it was because I wasn't using 'new' and 'const' for Duration and other stuff.

Steps to reproduce with this same repo:

- Clone
- Open Gallery Example Folder (`examples/flutter_gallery`)
- Run tests driver (`flutter drive --target=./test_driver/scroll_perf.dart`)
- Test passes!
- Open `scroll_perf.dart` file (`examples/flutter_gallery/test_driver/scroll_perf.dart`)
- Delete the first appearance of `const` (line 33)
- Run tests driver (`flutter drive --target=./test_driver/scroll_perf.dart`)
- Test fails with the stack trace below: 

```
Using device Android SDK built for x86.
Starting application: ./test_driver/scroll_perf.dart
Initializing gradle...
Built build\app\outputs\apk\debug\app-debug.apk.
I/FlutterActivityDelegate(27860): onResume setting current activity to this
I/flutter (27860): Observatory listening on http://127.0.0.1:39888/
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:58137/
[trace] FlutterDriver: Isolate found with number: 56278360
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:02 +0: scrolling performance test measure
00:03 +0 -1: scrolling performance test measure [E]
  NoSuchMethodError: Attempted to use type 'Duration' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the Duration constructor and forget the 'new' operator?
  Receiver: Duration
  Tried calling: Duration(milliseconds: 300)
  dart:core-patch/dart:core/object_patch.dart 46                Object.noSuchMethod
  test_driver\scroll_perf_test.dart 33:62                       main.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                _Completer.completeError
  test_driver\scroll_perf_test.dart                             main.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  test_driver\scroll_perf_test.dart 24:67                       main.<fn>.<fn>.<fn>
  package:flutter_driver/src/driver/driver.dart 699:17          FlutterDriver.traceAction
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart 694:12          FlutterDriver.traceAction
  test_driver\scroll_perf_test.dart 24:46                       main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  test_driver\scroll_perf_test.dart 23:30                       main.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                 Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 249:15                  Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 246:23                  Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 246:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/declarer.dart 143:66                 Declarer.test.<fn>
  package:test/src/backend/invoker.dart 403:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 402:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 172                                    new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 389:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 389:9                   Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 443:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 387:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 200                                    new Future.microtask.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/timer_impl.dart 391           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage

00:03 +0 -1: scrolling performance test (tearDownAll)
00:04 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Stopping application instance.
Driver tests failed: 255
```
For now, I'm writing my tests with my keywords as if it wasn't Dart 2.0, but I guess, for the sake of consistency, the driver tests should accept newest version of Dart.

EDIT: flutter doctor -v output:
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-CA)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jason-simmons** [comment]
Dart 2 should be supported in driver tests on the Flutter master branch

**Comment by nosmirck** [comment]
@jason-simmons thank you! So, it should be supported in the next release?

**Comment by zoechi** [comment]
@nosmirck you can assume it will be included in the next release

**Comment by nosmirck** [comment]
@zoechi thanks! We can close this then.
