### ISSUE TITLE
integration_ui test is flaky

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#19826]
It failed on #19785 with ([log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci84YWRlY2I2MmUxNzAxZGVjZGYyMmQ3NmRkZWM2NjNiMmQ1Zjc3NDNlDAsSBFRhc2sYgICAgICAigsM)):

```
2018-07-25T16:31:16.428793: stdout: [        ] /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart /Users/flutter/.cocoon/flutter/dev/integration_tests/ui/test_driver/screenshot_test.dart --packages=/Users/flutter/.cocoon/flutter/dev/integration_tests/ui/.packages -rexpanded --preview-dart-2
2018-07-25T16:31:19.566709: stdout: [+3137 ms] 00:00 [32m+0[0m: FlutterDriver (setUpAll)[0m
2018-07-25T16:31:19.610419: stderr: [  +42 ms] [info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:55437/
2018-07-25T16:31:20.253804: stderr: [ +644 ms] [trace] FlutterDriver: Isolate found with number: 665842189
2018-07-25T16:31:20.511030: stderr: [ +257 ms] [trace] FlutterDriver: Isolate is paused at start.
2018-07-25T16:31:20.529121: stderr: [  +18 ms] [trace] FlutterDriver: Attempting to resume isolate
2018-07-25T16:31:20.546549: stderr: [  +17 ms] [trace] FlutterDriver: Waiting for service extension
2018-07-25T16:31:22.430088: stderr: [+1883 ms] [info ] FlutterDriver: Connected to Flutter application.
2018-07-25T16:31:22.443205: stdout: [  +13 ms] 00:02 [32m+0[0m: FlutterDriver should take screenshot[0m
2018-07-25T16:31:30.452638: stdout: [+8009 ms] 00:10 [32m+0[0m[31m -1[0m: FlutterDriver should take screenshot [1m[31m[E][0m[0m
2018-07-25T16:31:30.454410: stdout: [   +1 ms]   JSON-RPC error -32602 (invalid parameters): Invalid params
2018-07-25T16:31:30.479301: stdout: [  +24 ms]   package:json_rpc_2/src/client.dart 110:64             Client.sendRequest
2018-07-25T16:31:30.480184: stdout: [        ]   package:json_rpc_2/src/peer.dart 68:15                Peer.sendRequest
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 627:53  FlutterDriver.screenshot
stdout: [        ]   ===== asynchronous gap ===========================
2018-07-25T16:31:30.480330: stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
2018-07-25T16:31:30.481558: stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver.screenshot
stdout: [        ]   test_driver/screenshot_test.dart 32:57                main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
stdout: [        ]   test_driver/screenshot_test.dart                      main..
stdout: [        ]   package:test/src/backend/declarer.dart 161:27         Declarer.test...
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
stdout: [        ]   package:test/src/backend/declarer.dart                Declarer.test...
stdout: [        ]   package:test/src/backend/invoker.dart 249:15          Invoker.waitForOutstandingCallbacks.
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                          _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                           _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/timer.dart 52:45                           new Timer
stdout: [        ]   dart:async/timer.dart 87:9                            Timer.run
stdout: [        ]   dart:async/future.dart 172:11                         new Future
stdout: [        ]   package:test/src/backend/invoker.dart 402:15          Invoker._onRun...
stdout: [        ] 00:10 [32m+0[0m[31m -1[0m: FlutterDriver (tearDownAll)[0m
2018-07-25T16:31:30.514731: stdout: [  +33 ms] 00:10 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
2018-07-25T16:31:30.530842: stderr: [  +14 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
stderr: [        ] #0      _rootHandleUncaughtError. (dart:async/zone.dart:1114:29)
stderr: [        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stderr: [        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stderr: [        ] #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
stderr: [        ] #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
stderr: [        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
2018-07-25T16:31:30.583529: stdout: [  +53 ms] Stopping application instance.
2018-07-25T16:31:30.583612: stdout: [        ] Stopping application.
2018-07-25T16:31:30.584382: stdout: [        ] /Volumes/DevicelabAndroid/sdk/platform-tools/adb -s ZY2245H6ZS shell am force-stop com.yourcompany.integration_ui
2018-07-25T16:31:31.542652: stdout: [ +958 ms] "flutter drive" took 56,459ms.
2018-07-25T16:31:31.545161: stderr: Driver tests failed: 255
2018-07-25T16:31:31.545260: stderr: 
2018-07-25T16:31:31.545769: stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
stderr: #1      _runTests (package:flutter_tools/src/commands/drive.dart:303:5)
stderr: 
2018-07-25T16:31:31.545895: stderr: #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:126:23)
stderr: 
stderr: #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
stderr: 
stderr: #4      FlutterCommand.run. (package:flutter_tools/src/runner/flutter_command.dart:282:33)
stderr: 
2018-07-25T16:31:31.545988: stderr: #5      AppContext.run. (package:flutter_tools/src/base/context.dart:142:29)
stderr: 
stderr: #6      _rootRun (dart:async/zone.dart:1126:13)
stderr: #7      _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #8      _runZoned (dart:async/zone.dart:1518:10)
stderr: #9      runZoned (dart:async/zone.dart:1465:12)
2018-07-25T16:31:31.546073: stderr: #10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
stderr: 
stderr: #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:273:20)
stderr: #12     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
stderr: 
2018-07-25T16:31:31.546175: stderr: #13     FlutterCommandRunner.runCommand. (package:flutter_tools/src/runner/flutter_command_runner.dart:346:21)
stderr: 
stderr: #14     AppContext.run. (package:flutter_tools/src/base/context.dart:142:29)
stderr: 
stderr: #15     _rootRun (dart:async/zone.dart:1126:13)
stderr: #16     _CustomZone.run (dart:async/zone.dart:1023:19)
2018-07-25T16:31:31.546262: stderr: #17     _runZoned (dart:async/zone.dart:1518:10)
stderr: #18     runZoned (dart:async/zone.dart:1465:12)
stderr: #19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
stderr: 
stderr: #20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:302:19)
stderr: 
stderr: #21     CommandRunner.run. (package:args/command_runner.dart:109:29)
2018-07-25T16:31:31.546348: stderr: #22     new Future.sync (dart:async/future.dart:222:31)
stderr: #23     CommandRunner.run (package:args/command_runner.dart:109:11)
stderr: #24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
stderr: #25     run. (package:flutter_tools/runner.dart:59:20)
stderr: 
2018-07-25T16:31:31.546440: stderr: #26     AppContext.run. (package:flutter_tools/src/base/context.dart:142:29)
stderr: 
stderr: #27     _rootRun (dart:async/zone.dart:1126:13)
stderr: #28     _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #29     _runZoned (dart:async/zone.dart:1518:10)
stderr: #30     runZoned (dart:async/zone.dart:1465:12)
2018-07-25T16:31:31.546526: stderr: #31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
stderr: 
stderr: #32     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
stderr: 
stderr: #33     run (package:flutter_tools/runner.dart:50:10)
stderr: #34     main (package:flutter_tools/executable.dart:51:9)
2018-07-25T16:31:31.546653: stderr: 
stderr: #35     main (file:///Users/flutter/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
stderr: #36     _startIsolate. (dart:isolate/runtime/libisolate_patch.dart:277:32)
stderr: #37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
stderr: 
stderr: 
2018-07-25T16:31:31.572344: exitcode: 255
2018-07-25T16:31:31.590162: Task failed: Executable failed with exit code 255.2018-07-25T16:31:31.590267: 

Stack trace:
2018-07-25T16:31:31.626372: package:flutter_devicelab/framework/utils.dart 77:3        fail
package:flutter_devicelab/framework/utils.dart 283:5       exec
===== asynchronous gap ===========================
dart:async                                                 _AsyncAwaitCompleter.completeError
package:flutter_devicelab/framework/utils.dart             exec
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/framework/utils.dart             exec
package:flutter_devicelab/framework/utils.dart 331:10      flutter
package:flutter_devicelab/tasks/integration_ui.dart 32:13  runEndToEndTests.
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/tasks/integration_ui.dart        runEndToEndTests.
package:flutter_devicelab/framework/utils.dart 369:24      inDirectory
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_devicelab/tasks/integration_ui.dart        runEndToEndTests
package:flutter_devicelab/framework/framework.dart 125:32  _TaskRunner._performTask.
```

It previously flaked on #19721 with ([log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9lZDBmNGUwMzgwZjJmZWUwNzA1ZGRhYzk4ODgzZWFjZTg0YmNkMDg5DAsSBFRhc2sYgICAgICA2AkM)):
```
2018-07-25T11:43:50.558193: stdout: [        ] /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart /Users/flutter/.cocoon/flutter/dev/integration_tests/ui/test_driver/screenshot_test.dart --packages=/Users/flutter/.cocoon/flutter/dev/integration_tests/ui/.packages -rexpanded --preview-dart-2
2018-07-25T11:43:53.776589: stdout: [+3218 ms] 00:00 [32m+0[0m: FlutterDriver (setUpAll)[0m
2018-07-25T11:43:53.825194: stderr: [  +47 ms] [info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:58659/
2018-07-25T11:43:54.477321: stdout: [ +653 ms] 00:00 [32m+0[0m[31m -1[0m: FlutterDriver (setUpAll) [1m[31m[E][0m[0m
2018-07-25T11:43:54.477980: stdout: [        ]   Bad state: No element
2018-07-25T11:43:54.502289: stdout: [  +23 ms]   dart:core/runtime/libarray.dart 165:5                 List.first
2018-07-25T11:43:54.502688: stdout: [        ]   package:flutter_driver/src/driver/driver.dart 181:28  FlutterDriver.connect
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/future_impl.dart 22:43                     _Completer.completeError
stdout: [        ]   dart:async/runtime/libasync_patch.dart 40:18          _AsyncAwaitCompleter.completeError
stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver.connect
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver.connect
stdout: [        ]   test_driver/screenshot_test.dart 14:36                main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/zone.dart 969:22                           _CustomZone.bindUnaryCallbackGuarded
stdout: [        ]   dart:async/future.dart 522:34                         Future.doWhile
stdout: [        ]   dart:async/future.dart 482:12                         Future.forEach
stdout: [        ]   package:test/src/backend/declarer.dart 272:36         Declarer._setUpAll..
stdout: [        ]   dart:async/zone.dart 1126:13                          _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                          _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1518:10                          _runZoned
2018-07-25T11:43:54.502804: stdout: [        ]   dart:async/zone.dart 1465:12                          runZoned
stdout: [        ]   package:test/src/backend/declarer.dart 272:14         Declarer._setUpAll.
stdout: [        ]   package:test/src/backend/invoker.dart 403:25          Invoker._onRun....
2018-07-25T11:43:54.502889: stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                          _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                           _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/timer.dart 52:45                           new Timer
2018-07-25T11:43:54.502988: stdout: [        ]   dart:async/timer.dart 87:9                            Timer.run
2018-07-25T11:43:54.503066: stdout: [        ]   dart:async/future.dart 172:11                         new Future
stdout: [        ]   package:test/src/backend/invoker.dart 402:15          Invoker._onRun...
2018-07-25T11:43:54.505365: stdout: [   +2 ms] 00:00 [32m+0[0m[31m -1[0m: FlutterDriver (tearDownAll)[0m
2018-07-25T11:43:54.531740: stdout: [  +26 ms] 00:00 [32m+0[0m[31m -2[0m: FlutterDriver (tearDownAll) [1m[31m[E][0m[0m
2018-07-25T11:43:54.537536: stdout: [   +5 ms]   NoSuchMethodError: The method 'close' was called on null.
2018-07-25T11:43:54.537700: stdout: [        ]   Receiver: null
stdout: [        ]   Tried calling: close()
2018-07-25T11:43:54.544266: stdout: [   +5 ms]   dart:core/runtime/libobject_patch.dart 46:5                   Object.noSuchMethod
stdout: [        ]   test_driver/screenshot_test.dart 18:20                        main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/future_impl.dart 22:43                             _Completer.completeError
stdout: [        ]   dart:async/runtime/libasync_patch.dart 43:20                  _AsyncAwaitCompleter.completeError.
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.
stdout: [        ]   dart:async/zone.dart 1122:38                                  _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                                  _CustomZone.run
stdout: [        ]   dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.
2018-07-25T11:43:54.544574: stdout: [        ]   dart:async/zone.dart 1126:13                                  _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                                  _CustomZone.run
2018-07-25T11:43:54.544690: stdout: [        ]   dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
2018-07-25T11:43:54.544830: stdout: [        ]   dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.
2018-07-25T11:43:54.545441: stdout: [        ]   dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
stdout: [        ]   dart:isolate/runtime/libtimer_impl.dart 391:30                _Timer._runTimers
stdout: [        ]   dart:isolate/runtime/libtimer_impl.dart 416:5                 _Timer._handleMessage
stdout: [        ]   dart:isolate/runtime/libisolate_patch.dart 165:12             _RawReceivePortImpl._handleMessage
stdout: [        ]   ===== asynchronous gap ===========================
2018-07-25T11:43:54.546005: stdout: [        ]   dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/schedule_microtask.dart 147:47                     scheduleMicrotask
stdout: [        ]   dart:async/runtime/libasync_patch.dart 42:7                   _AsyncAwaitCompleter.completeError
stdout: [        ]   test_driver/screenshot_test.dart                              main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
2018-07-25T11:43:54.546131: stdout: [        ]   dart:async/timer.dart 52:45                                   new Timer
stdout: [        ]   dart:async/timer.dart 87:9                                    Timer.run
stdout: [        ]   dart:async/future.dart 172:11                                 new Future
2018-07-25T11:43:54.546292: stdout: [        ]   package:test/src/backend/invoker.dart 402:15                  Invoker._onRun...
2018-07-25T11:43:54.558615: stdout: [  +12 ms] 00:00 [32m+0[0m[31m -2[0m: [31mSome tests failed.[0m
2018-07-25T11:43:54.560950: stderr: [   +2 ms] Unhandled exception:
2018-07-25T11:43:54.561593: stderr: [        ] Dummy exception to set exit code.
stderr: [        ] #0      _rootHandleUncaughtError. (dart:async/zone.dart:1114:29)
stderr: [        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stderr: [        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stderr: [        ] #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
stderr: [        ] #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
stderr: [        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Also flaked on #19565 with([log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9kZWJkNTAxNThlNjQzZTYwNzIyZTg2ZDUxZjBkNDdiZGYwNjE0OTJjDAsSBFRhc2sYgICAgICA9AgM)):
```
2018-07-20T16:12:55.934015: stdout: [        ] /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart /Users/flutter/.cocoon/flutter/dev/integration_tests/ui/test_driver/screenshot_test.dart --packages=/Users/flutter/.cocoon/flutter/dev/integration_tests/ui/.packages -rexpanded --preview-dart-2
2018-07-20T16:12:59.353712: stdout: [+3419 ms] 00:00 [32m+0[0m: FlutterDriver (setUpAll)[0m
2018-07-20T16:12:59.405960: stderr: [  +51 ms] [info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:53932/
2018-07-20T16:13:00.062502: stdout: [ +657 ms] 00:00 [32m+0[0m[31m -1[0m: FlutterDriver (setUpAll) [1m[31m[E][0m[0m
2018-07-20T16:13:00.063222: stdout: [        ]   Bad state: No element
2018-07-20T16:13:00.089837: stdout: [  +26 ms]   dart:core/runtime/libarray.dart 165:5                 List.first
2018-07-20T16:13:00.090789: stdout: [        ]   package:flutter_driver/src/driver/driver.dart 181:28  FlutterDriver.connect
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/future_impl.dart 22:43                     _Completer.completeError
stdout: [        ]   dart:async/runtime/libasync_patch.dart 40:18          _AsyncAwaitCompleter.completeError
stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver.connect
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
stdout: [        ]   package:flutter_driver/src/driver/driver.dart         FlutterDriver.connect
stdout: [        ]   test_driver/screenshot_test.dart 14:36                main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1055:19                          _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async/zone.dart 969:22                           _CustomZone.bindUnaryCallbackGuarded
stdout: [        ]   dart:async/future.dart 522:34                         Future.doWhile
2018-07-20T16:13:00.091398: stdout: [        ]   dart:async/future.dart 482:12                         Future.forEach
stdout: [        ]   package:test/src/backend/declarer.dart 272:36         Declarer._setUpAll..
2018-07-20T16:13:00.092343: stdout: [        ]   dart:async/zone.dart 1126:13                          _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                          _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1518:10                          _runZoned
2018-07-20T16:13:00.092460: stdout: [        ]   dart:async/zone.dart 1465:12                          runZoned
2018-07-20T16:13:00.093053: stdout: [        ]   package:test/src/backend/declarer.dart 272:14         Declarer._setUpAll.
stdout: [        ]   package:test/src/backend/invoker.dart 403:25          Invoker._onRun....
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                          _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                           _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/timer.dart 52:45                           new Timer
stdout: [        ]   dart:async/timer.dart 87:9                            Timer.run
stdout: [        ]   dart:async/future.dart 172:11                         new Future
stdout: [        ]   package:test/src/backend/invoker.dart 402:15          Invoker._onRun...
2018-07-20T16:13:00.095890: stdout: [   +4 ms] 00:00 [32m+0[0m[31m -1[0m: FlutterDriver (tearDownAll)[0m
2018-07-20T16:13:00.111793: stdout: [  +15 ms] 00:00 [32m+0[0m[31m -2[0m: FlutterDriver (tearDownAll) [1m[31m[E][0m[0m
2018-07-20T16:13:00.118202: stdout: [   +6 ms]   NoSuchMethodError: The method 'close' was called on null.
2018-07-20T16:13:00.118469: stdout: [        ]   Receiver: null
stdout: [        ]   Tried calling: close()
2018-07-20T16:13:00.125533: stdout: [   +7 ms]   dart:core/runtime/libobject_patch.dart 46:5                   Object.noSuchMethod
2018-07-20T16:13:00.125709: stdout: [        ]   test_driver/screenshot_test.dart 18:20                        main..
2018-07-20T16:13:00.127355: stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/future_impl.dart 22:43                             _Completer.completeError
stdout: [        ]   dart:async/runtime/libasync_patch.dart 43:20                  _AsyncAwaitCompleter.completeError.
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.
stdout: [        ]   dart:async/zone.dart 1122:38                                  _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                                  _CustomZone.run
stdout: [        ]   dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
stdout: [        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.
stdout: [        ]   dart:async/zone.dart 1126:13                                  _rootRun
stdout: [        ]   dart:async/zone.dart 1023:19                                  _CustomZone.run
stdout: [        ]   dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.
stdout: [        ]   dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
stdout: [        ]   dart:isolate/runtime/libtimer_impl.dart 391:30                _Timer._runTimers
stdout: [        ]   dart:isolate/runtime/libtimer_impl.dart 416:5                 _Timer._handleMessage
stdout: [        ]   dart:isolate/runtime/libisolate_patch.dart 165:12             _RawReceivePortImpl._handleMessage
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
stdout: [        ]   dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/schedule_microtask.dart 147:47                     scheduleMicrotask
stdout: [        ]   dart:async/runtime/libasync_patch.dart 42:7                   _AsyncAwaitCompleter.completeError
stdout: [        ]   test_driver/screenshot_test.dart                              main..
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
2018-07-20T16:13:00.127736: stdout: [        ]   dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
stdout: [        ]   dart:async/timer.dart 52:45                                   new Timer
stdout: [        ]   dart:async/timer.dart 87:9                                    Timer.run
stdout: [        ]   dart:async/future.dart 172:11                                 new Future
stdout: [        ]   package:test/src/backend/invoker.dart 402:15                  Invoker._onRun...
2018-07-20T16:13:00.141180: stdout: [  +13 ms] 00:00 [32m+0[0m[31m -2[0m: [31mSome tests failed.[0m
```

**Comment by godofredoc** [comment]
Not happening anymore. Please reopen if it fails again.
