### ISSUE TITLE
Error while trying to build MyApp

### ISSUE THREAD

**Issue by omdnaik** [flutter/flutter#19937]
```
I/flutter ( 5664): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5664): The following assertion was thrown building MyApp(dirty):
I/flutter ( 5664): type 'Color' is not a subtype of type 'MaterialColor'
I/flutter ( 5664):
I/flutter ( 5664): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5664): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5664): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5664):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5664):
I/flutter ( 5664): When the exception was thrown, this was the stack:
I/flutter ( 5664): #0      MyApp.build (file:///C:/Users/omkar/IdeaProjects/bucketlist/lib/main.dart:12:31)
I/flutter ( 5664): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter ( 5664): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 5664): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 5664): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 5664): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 5664): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 5664): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 5664): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter ( 5664): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter ( 5664): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter ( 5664): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 5664): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter ( 5664): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter ( 5664): #14     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter ( 5664): #15     main (file:///C:/Users/omkar/IdeaProjects/bucketlist/lib/main.dart:3:16)
I/flutter ( 5664): #16     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 5664): #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 5664): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/        ( 5664): HostConnection::get() New Host Connection established 0x85bcc380, tid 5971
D/EGL_emulation( 5664): eglMakeCurrent: 0x87271bc0: ver 3 0 (tinfo 0x81e78a40)

Performing hot reload...
Unable to hot reload. No instance of Flutter is currently running.
Try again after fixing the above error(s).
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/dart:core/array.dart:165)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:542)
#2      _rootRunUnary (dart:async/zone.dart:1134)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#6      Future._propagateToListeners (dart:async/future_impl.dart:662)
#7      Future._completeWithValue (dart:async/future_impl.dart:477)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

**Comment by jonahwilliams** [comment]
This is most likely a type error in your code that occurs here: `MyApp.build (file:///C:/Users/omkar/IdeaProjects/bucketlist/lib/main.dart:12:31` and not a framework problem.

**Comment by jonahwilliams** [comment]
For reference see: https://github.com/flutter/flutter/issues/15658
