### ISSUE TITLE
FutureBuilder Error

### ISSUE THREAD

**Issue by codeZee** [flutter/flutter#19952]
```
I/flutter (14827): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14827): The following assertion was thrown building FutureBuilder<bool>(dirty, state:
I/flutter (14827): _FutureBuilderState<bool>#6904b):
I/flutter (14827): Failed assertion: boolean expression must not be null
I/flutter (14827): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14827): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14827): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14827):   https://github.com/flutter/flutter/issues/new
I/flutter (14827): When the exception was thrown, this was the stack:
I/flutter (14827): #0      MyApp.build.<anonymous closure> (file:///Users/user/Documents/sellquick_app/lib/main.dart)
I/flutter (14827): #1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
I/flutter (14827): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter (14827): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (14827): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #98     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4772:32)
I/flutter (14827): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #101    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter (14827): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #143    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #146    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #151    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #170    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #179    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (14827): #180    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #183    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #184    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #185    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #186    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #187    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #190    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #191    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #192    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #193    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #198    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #205    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #210    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #211    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #212    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #213    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #215    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #216    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #217    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #223    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #224    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #225    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #226    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #228    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #229    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #232    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #234    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #235    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #236    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (14827): #237    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #239    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (14827): #241    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (14827): #242    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (14827): #243    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (14827): #244    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (14827): #245    Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (14827): #246    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (14827): #247    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (14827): #248    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (14827): #249    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (14827): #250    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (14827): #251    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (14827): #252    runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (14827): #253    main (file:///Users/user/Documents/sellquick_app/lib/main.dart:13:16)
I/flutter (14827): #254    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (14827): #255    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (14827): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
That's very likely an issue with your code but it's hard to make suggestions without seeing the code.

In Dart variables of type `bool` can be `null`, but `if(...)` checks don't allow `null`, which might be the case in your code.

**Comment by codeZee** [comment]
@zoechi here's my code snippet. Something wrong I didn't detect?
 
return new MaterialApp(
    ...
      home: new FutureBuilder<bool>(
          future: sessionManager.isLoggedIn(), //Async method (this returns false by default if null)
          builder: (BuildContext context, AsyncSnapshot<bool> isLoggedIn) {
            return isLoggedIn.data ? new MainPageWidget() : new IntroWidget();
          }),

**Comment by zoechi** [comment]
Check the sample code in https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html
You need to check connection states `ConnectionState....`.

> Async method (this returns false by default if null)

Async methods complete delayed. Until it completes the `builder: ...` function needs to return valid widgets or it causes exceptions.
