### ISSUE TITLE
Flutter issue

### ISSUE THREAD

**Issue by yogesh45** [flutter/flutter#20021]
Performing hot restart...
Restarted app in 1,798ms.
I/flutter ( 3965): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3965): The following assertion was thrown building myHome(dirty, state: MyApp#283ed):
I/flutter ( 3965): 'package:flutter/src/widgets/scroll_view.dart': Failed assertion: line 950 pos 15: 'gridDelegate !=
I/flutter ( 3965): null': is not true.
I/flutter ( 3965): 
I/flutter ( 3965): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3965): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3965): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3965):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3965): 
I/flutter ( 3965): When the exception was thrown, this was the stack:
I/flutter ( 3965): #2      new GridView.builder (package:flutter/src/widgets/scroll_view.dart)
I/flutter ( 3965): #3      MyApp.build (file:///C:/Users/yogeshwaran.j.s/AndroidStudioProjects/flutter_project/lib/main.dart:48:19)
I/flutter ( 3965): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter ( 3965): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 3965): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #100    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
I/flutter ( 3965): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #103    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter ( 3965): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #108    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #109    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #129    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #132    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #165    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #177    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #178    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #180    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #181    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 3965): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #187    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #198    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #200    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #201    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #217    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #218    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #225    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #226    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #228    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #230    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #231    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #232    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #233    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #234    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #236    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #237    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #238    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 3965): #239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 3965): #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 3965): #244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 3965): #245    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 3965): #246    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 3965): #247    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 3965): #248    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter ( 3965): #249    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter ( 3965): #250    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter ( 3965): #251    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 3965): #252    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter ( 3965): #253    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter ( 3965): #254    runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter ( 3965): #255    main (file:///C:/Users/yogeshwaran.j.s/AndroidStudioProjects/flutter_project/lib/main.dart:8:16)
I/flutter ( 3965): #256    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter ( 3965): #257    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3965): (elided 2 frames from class _AssertionError)
I/flutter ( 3965): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3965): Another exception was thrown: 'package:flutter/src/widgets/scroll_view.dart': Failed assertion: line 950 pos 15: 'gridDelegate != null': is not true.

**Comment by zoechi** [comment]
That indicates a problem with your code. We would need the code that allows to reproduce.
Please also add the output of `flutter doctor -v`.
