### ISSUE TITLE
App crashes with java.lang.IllegalStateException: No current tap-and-pay account

### ISSUE THREAD

**Issue by techyrajeev** [flutter/flutter#20038]
## Steps to Reproduce

1. Run the project either in debug or run mode
2. When app loads tap on Google Login button
3. Google login happens successfully and user object is returned from server
4. Waiting for user to redirect from login screen to home screen
4. App gets crashed after few seconds

## Logs

```
07-31 21:16:07.216 25702-26371/? E/SeTransactionSyncTask: Error retrieving account
    java.lang.IllegalStateException: No current tap-and-pay account
        at anbe.b(:com.google.android.gms@12874026@12.8.74 (040700-204998136):3)
        at anbe.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at anvc.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):28)
        at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.b(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at com.google.android.gms.tapandpay.phenotype.PhenotypeCommitIntentOperation.onHandleIntent(:com.google.android.gms@12874026@12.8.74 (040700-204998136):47)
        at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@12874026@12.8.74 (040700-204998136):2)
        at dfm.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):8)
        at npz.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):9)
        at dfr.run(:com.google.android.gms@12874026@12.8.74 (040700-204998136):10)
        at dfo.run(:com.google.android.gms@12874026@12.8.74 (040700-204998136):9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-31 21:16:07.249 25702-25874/? E/SeTransactionSyncTask: Error retrieving account
    java.lang.IllegalStateException: No current tap-and-pay account
        at anbe.b(:com.google.android.gms@12874026@12.8.74 (040700-204998136):3)
        at anbe.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at anvc.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):28)
        at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.b(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at ankq.i(:com.google.android.gms@12874026@12.8.74 (040700-204998136):8)
        at ankq.d(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at anyo.a(:com.google.android.gms@12874026@12.8.74 (040700-204998136):1)
        at pir.run(:com.google.android.gms@12874026@12.8.74 (040700-204998136):38)
        a
```

```
```

Output of `flutter doctor -v`

```
flutter doctor -v                
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.5.1 at /private/var/www/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rajeev/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/rajeev/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 3 categories.

```

**Comment by zoechi** [comment]
Are you using an in-app payment plugin?

**Comment by techyrajeev** [comment]
@zoechi  No I am not using any of it. I am just using google_signin plugin

**Comment by zoechi** [comment]
Seems not to be Flutter specific 
https://stackoverflow.com/questions/50652370/setransactionsynctask-error-retrieving-account-java-lang-illegalstateexception
but no answer yet :-/

**Comment by techyrajeev** [comment]
In debug mode I see this - 
```
The GMS server connection has been suspended (1)
Application finished.
```

**Comment by techyrajeev** [comment]
I have following dependencies in android/build.gradle


 ```
   dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }
```

**Comment by zoechi** [comment]
This stack trace looks unrelated. If you get this consistently, you might want to switch to the `dev` channel version of Flutter.

**Comment by zoechi** [comment]
This doesn't look Flutter-specific.

Did you turn on tap & pay? https://support.google.com/nexus/answer/3470787?hl=en
