### ISSUE TITLE
Android Flutter build fails during flutterBuildDebug

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#20046]
## Steps to Reproduce

0. Probably not reproducible
1. Running Android Studio 3.2 Beta 5 on Ubuntu
2. Navigating to the Android Module with `Tools -> Flutter` (because build just stops on `Initializing gradle`)
3. Make Project (building inside the Android Module)

## Logs

![screenshot](https://i.imgur.com/YwZGaen.png)

*Exception from the right side of the window:*

```
org.gradle.process.internal.ExecException: Process 'command '/media/ubuntu/load/flutter/bin/flutter'' finished with non-zero exit value 1
    at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
    at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:37)
    at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:198)
    at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1102)
    at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1097)
    at org.gradle.api.Project$exec$8.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at BaseFlutterTask.buildBundle(/media/ubuntu/load/flutter/packages/flutter_tools/gradle/flutter.gradle:450)
    at BaseFlutterTask$buildBundle.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
137 more lines
```

```
[✓] Flutter (Channel master, v0.5.8-pre.184, on Linux, locale C.UTF-8)
    • Flutter version 0.5.8-pre.184 at flutterRoot
    • Framework revision 3a6228bead (19 hours ago), 2018-07-30 18:07:23 -0700
    • Engine revision af855e063a
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at androidSdkRoot
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: androidStudioRoot/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at androidStudioRoot
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)
```

The *Flutter and Dart plugins* are working fine in *Android Studio*.

**Comment by abusaadp** [comment]
How to fix this issue? Even I am facing the some issue

**Comment by creativecreatorormaybenot** [comment]
@abusaadp In my case it was system related because I was using Ubuntu Demo with data on a flash drive, which means that there is no general answer to this problem.
