### ISSUE TITLE
ProcessException: Permission Denied

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#20048]
## Steps to Reproduce

1. `flutter build` for Android any options

```
[✓] Flutter (Channel master, v0.5.8-pre.184, on Linux, locale C.UTF-8)
    • Flutter version 0.5.8-pre.184 at flutterRoot
    • Framework revision 3a6228bead (19 hours ago), 2018-07-30 18:07:23 -0700
    • Engine revision af855e063a
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at androidSdkRoot
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: androidStudioRoot/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)
    ✗ Android license status unknown.
```

### command

flutter build apk --debug -v

### exception

ProcessException: ProcessException: Permission denied
  Command: project/android/gradlew -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:227:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:242:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:180:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:161:37)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:268:31)
<asynchronous suspension>
#5      buildApk (package:flutter_tools/src/android/apk.dart:41:10)
<asynchronous suspension>
#6      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:49:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._complete (dart:async/future_impl.dart:476:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

I do not really know how I could help `flutter build` there. Running with `sudo` is not only discouraged, but does also not help. It definitely has permissions for the `gradlew` file. My guess is that it is another file that needs additional permissions, but I only get this from `-v`:

```
...
[ +289 ms] Initializing gradle...
[   +7 ms] Using gradle from project/android/gradlew.
[  +63 ms] project/android/gradlew -v
[  +57 ms] "flutter apk" took 732ms.

EOF
```

**Comment by creativecreatorormaybenot** [comment]
The `project` directory was on a FAT filesystem, where I could not change permissions.

**Comment by dibusiness** [comment]
so How i can change the filesystem
