### ISSUE TITLE
local_auth plugin doesn't throw PlatformException on ios Emulator

### ISSUE THREAD

**Issue by felipecesar42** [flutter/flutter#20107]
When I run my flutter aplication on ios Emulator using the local_auth plugin I can't catch any kind of exception like:

- Passcode/PIN/Pattern Not Set. The user has not yet configured a passcode on iOS or PIN/pattern on Android.
- Touch ID/Fingerprint Not Enrolled. The user has not enrolled any fingerprints on the device.

On Debug Console it prints the following even with no print statement on any of the lib source files

> 1000 = 1;
> }, (null) on <LAClient: 0x608000283250>

## Steps to Reproduce

I'm using the following code when the apps starts:

```
bool authenticated = false;

  try {
    var localAuth = new LocalAuthentication();

    while (authenticated == false) {
      authenticated = await localAuth.authenticateWithBiometrics(
        localizedReason: 'reason',
        stickyAuth: true
      );
    }
  } on PlatformException catch (e) {
    switch(e.code) {
      case auth_error.notAvailable:
        break;
      case auth_error.notEnrolled:
        break;
      case auth_error.passcodeNotSet:
        break;
    }
  }
```

## Logs

flutter run --verbose
```
[  +26 ms] [/Users/felipe/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/felipe/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/felipe/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/felipe/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [/Users/felipe/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 weeks ago
[   +1 ms] [/Users/felipe/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca37
[ +276 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +38 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[  +98 ms] /Users/felipe/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/felipe/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] idevice_id -h
[  +63 ms] which ideviceinstaller
[   +4 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +3 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[ +236 ms] /usr/bin/xcrun simctl list --json devices
[ +108 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] Noroil   • 821d134524311496aa4c393b543e32aff1cbd278 • ios • iOS 11.4.1
[        ] iPhone X • 394591E6-C035-4CC1-BDA9-634EE3E2C0C3     • ios • iOS 11.4 (simulator)
[  +11 ms] "flutter run" took 814ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:250)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:50)
#30     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#31     main (file:///Users/felipe/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)
```

**Comment by NikoYuwono** [comment]
Hi, I think based on the doc [here](https://github.com/flutter/plugins/blob/master/packages/local_auth/lib/local_auth.dart#L31) PlatformException will be only thrown if the phone doesn't support touch id or face id on hardware level, or run on non Android/iOS device.

On code level the reason why there are no PlatformException thrown is [here](https://github.com/flutter/plugins/blob/master/packages/local_auth/ios/Classes/LocalAuthPlugin.m#L117) If you run it on Simulator without enrolled touch id it will fail with LAErrorTouchIDNotEnrolled error, and as you can see in the code that when useErrorDialogs is true, the plugin will present an error dialog to guide the user to the settings page. 

Since useErrorDialogs is set to true by default ([reference](https://github.com/flutter/plugins/blob/master/packages/local_auth/lib/local_auth.dart#L51)) you can set it to false like below and you'll start seeing PlatformException being thrown.

```
authenticated = await localAuth.authenticateWithBiometrics(
         useErrorDialogs: false,
        localizedReason: 'reason',
        stickyAuth: true
      );
```

Hope this can clear things up for you.

**Comment by felipecesar42** [comment]
Thanks a lot @NikoYuwono. This solved my problem, you were right :)
