### ISSUE TITLE
Performing hot reload... flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═══

### ISSUE THREAD

**Issue by levi-l-damian** [flutter/flutter#20113]
```
Performing hot reload...
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12:
flutter: '!_debugDoingBaseline': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart)
flutter: #3      _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:751:35)
flutter: #4      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:782:18)
flutter: #5      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:905:44)
flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #13     _RenderListTile._layoutBox (package:flutter/src/material/list_tile.dart:726:9)
flutter: #14     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:756:28)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #24     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #28     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
flutter: #29     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
flutter: #30     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
flutter: #31     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
flutter: #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #44     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #57     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #59     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #61     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
flutter: #73     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
flutter: #74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
flutter: #75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
flutter: #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
flutter: #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #83     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #84     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #85     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   _RenderDecoration#3fc57 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
flutter:   GestureDetector ← IgnorePointer ← Semantics ← TextField ← DefaultTextStyle ←
flutter:   AnimatedDefaultTextStyle ← _ListTile ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=316.2, 0.0<=h<=685.2)
flutter:   size: Size(316.2, 59.0)
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:   RenderRepaintBoundary#81729 relayoutBoundary=up12 NEEDS-PAINT
flutter:     RenderPointerListener#e3004 relayoutBoundary=up13 NEEDS-PAINT
flutter:       RenderSemanticsAnnotations#786bd relayoutBoundary=up14 NEEDS-PAINT
flutter:         RenderIgnorePointer#959be relayoutBoundary=up15 NEEDS-PAINT
flutter:           RenderLeaderLayer#946ae relayoutBoundary=up16 NEEDS-PAINT
flutter:   RenderTransform#0368f relayoutBoundary=up12 NEEDS-PAINT
flutter:     RenderParagraph#b7435 relayoutBoundary=up13 NEEDS-PAINT
flutter:   RenderConstrainedBox#8bdc6 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
flutter:   RenderCustomPaint#847f4 NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12: '!_debugDoingBaseline': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: _RenderListTile#0d8dc relayoutBoundary=up7 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPadding#417d3 relayoutBoundary=up6 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#521a5 relayoutBoundary=up5 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#646ef relayoutBoundary=up4 NEEDS-PAINT
flutter: Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#521a5 relayoutBoundary=up5
Reloaded 0 of 392 libraries in 712ms.
```

**Comment by zoechi** [comment]
Looks like a dup of #18755
