### ISSUE TITLE
NoSuchMethodError: Class 'YamlList' has no instance method 'containsKey'.

### ISSUE THREAD

**Issue by BlizzaN** [flutter/flutter#20147]
I just created an new project and then I ran the app I got unexpectedly error and I have no idea where I got this error from. 

Here is the log I got:
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --device-id=DB913393-C189-4565-A3FC-9022257EEAD4 lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: Class 'YamlList' has no instance method 'containsKey'.
Receiver: Instance of 'YamlList'
Tried calling: containsKey("plugin")

```
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _pluginFromPubspec (package:flutter_tools/src/plugins.dart:56)
#2      _findPlugins.<anonymous closure> (package:flutter_tools/src/plugins.dart:75)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#4      _findPlugins (package:flutter_tools/src/plugins.dart:73)
#5      injectPlugins (package:flutter_tools/src/plugins.dart:234)
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:62)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:332)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#15     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#24     new Future.sync (dart:async/future.dart:222)
#25     CommandRunner.run (package:args/command_runner.dart:109)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1501)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50)
#35     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#36     main (file:///Users/pontuspettersson92/Desktop/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale sv-SE)
    • Flutter version 0.5.1 at /Users/pontuspettersson92/Desktop/Flutter/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/pontuspettersson92/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone 5s                 • DB913393-C189-4565-A3FC-9022257EEAD4 • ios         • iOS 9.2 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Did you modify `pubspec.yaml` of the newly created project?

**Comment by BlizzaN** [comment]
Yes I did,
I added these things 

location: ^1.3.4
  map_view: ^0.0.14
     - images/trafiksakerhetskamera.png
and commented this line
  # uses-material-design: true
but if I remove the # from uses-material-design: true 
I got this error then:
Error on line 34, column 6 of pubspec.yaml: Expected a key while parsing a block mapping.
     - images/trafiksakerhetskamera.png
     ^

**Comment by BlizzaN** [comment]
It works now, what I did in pubspec.yaml above the images was to remove the hashtag from assets: and then it worked.

**Comment by zoechi** [comment]
Thanks for the update!

You can check https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/pubspec.yaml or the other examples.
In yaml whitespaces (indentation) are relevant.
