### ISSUE TITLE
VideoPlayerController -  Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#20180]
I get lots of such exceptions recently

```
PlatformException: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null)
  File "message_codecs.dart", line 551, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 279, in MethodChannel.invokeMethod
  File "<asynchronous suspension>"
  File "video_player.dart", line 203, in VideoPlayerController.initialize
  File "<asynchronous suspension>"
  File "video_preview_widget.dart", line 13, in new VideoPreviewWidget.
...
```
```
[✓] Flutter (Channel master, v0.5.8-pre.228, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.228 at /Users/zoechi/flutter/flutter
    • Framework revision 9e832121d0 (14 hours ago), 2018-08-02 17:07:36 -0700
    • Engine revision 4893b0760d
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Still seeing this with

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.1-pre.4, on Mac OS X 10.13.6 17G65, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by rtorresware** [comment]
I'm getting this as well

**Comment by collinjackson** [comment]
Are you still seeing this? It seems like it might an issue specific to the video player.

**Comment by zoechi** [comment]
@collinjackson I'm not working on this project anymore since ~6 months, so can't tell.
@rtorresware are you still seeing this?

**Comment by mrgoonie** [comment]
@zoechi @rtorresware @collinjackson 
I got this issue as well with VideoPlayerController at the bold line:

```
_videoController = VideoPlayerController.network(videoUrl);
      **_videoController.initialize().then((_) {**
        _videoController.play();
        if (mounted) setState(() {});
      });
```

The error is:
```
I/ExoPlayerImpl(31678): Init a78a4e2 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
E/MethodChannel#flutter.io/videoPlayer(31678): Failed to handle method call
E/MethodChannel#flutter.io/videoPlayer(31678): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/MethodChannel#flutter.io/videoPlayer(31678): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin$VideoPlayer.<init>(VideoPlayerPlugin.java:86)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:339)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#flutter.io/videoPlayer(31678): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/AudioTrack(31678): stop() called with 6445056 frames delivered
```

Flutter doctor run is all fine.

**Comment by mrgoonie** [comment]
Saw this in `video_player.dart`, could it be the issue?

![image](https://user-images.githubusercontent.com/6857382/55218388-8edaed00-5234-11e9-8d52-c1b73719ba9a.png)

**Comment by mrgoonie** [comment]
Wut? 😕

**Comment by rafagan** [comment]
Same here
