### ISSUE TITLE
Error or executable app in XCode

### ISSUE THREAD

**Issue by antoniokarlos** [flutter/flutter#20198]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --suppress-analytics build bundle --target=/Users/antoniocarlosdeoliveira/Desktop/congresso_2018_03082018/lib/main.dart --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/antoniocarlosdeoliveira/Desktop/congresso_2018_03082018/ios/Flutter/flutter_assets --preview-dart-2

## exception

RangeError: RangeError (index): Invalid value: Only valid value is 0: 1

```
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      readDepfile (package:flutter_tools/src/base/fingerprint.dart:174)
<asynchronous suspension>
#2      Fingerprinter._getPaths (package:flutter_tools/src/base/fingerprint.dart:88)
<asynchronous suspension>
#3      Fingerprinter.doesFingerprintMatch (package:flutter_tools/src/base/fingerprint.dart:60)
<asynchronous suspension>
#4      KernelCompiler.compile (package:flutter_tools/src/compile.dart:104)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:79)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:72)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#15     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#24     new Future.sync (dart:async/future.dart:222)
#25     CommandRunner.run (package:args/command_runner.dart:109)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1501)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50)
#35     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#36     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale pt-BR)
    • Flutter version 0.5.1 at /Users/antoniocarlosdeoliveira/Documents/Flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/antoniocarlosdeoliveira/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 92C1FEBC-67F3-4E35-A510-E86C4B9A9E6A • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by DanTup** [comment]
This issue has been fixed on dev/master channels (see https://github.com/flutter/flutter/issues/17831) but not made the beta channel yet. For now, you should be able to run `flutter clean` when this happens to fix it.
