### ISSUE TITLE
crash caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#20216]
this is my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.238, on Mac OS X 10.13.6 17G65, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

It's some day that when i run my app in emulator or my phone, it crash without show anything error in the dart console.
With iphone emulator it works
I opened android studio and i found in logcat this error:

```
08-04 08:49:19.181 1892-4484/? I/PackageManager.DexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/com.shuttertop.android-rEYfbtFU55zjW8b1E1ljqg==/base.apk pkg=com.shuttertop.android isa=x86_64 dexoptFlags=boot_complete,debuggable,public,enable_hidden_api_checks targetFilter=verify oatDir=/data/app/com.shuttertop.android-rEYfbtFU55zqW8b1E1ljqg==/oat classLoaderContext=PCL[]
08-04 08:49:19.196 1693-1956/? V/installed: DexInv: --- BEGIN '/data/app/com.shuttertop.android-rEYfbtFU55zjW8b1E1ljqg==/base.apk' ---
08-04 08:49:19.632 4486-4486/? I/dex2oat: /system/bin/dex2oat --input-vdex-fd=-1 --output-vdex-fd=10 --compiler-filter=verify --debuggable --classpath-dir=/data/app/com.shuttertop.android-rEYfbtFU55zjW8b1E1ljqg== --class-loader-context=PCL[] --generate-mini-debug-info --compact-dex-level=none --compilation-reason=boot
08-04 08:49:25.597 1693-1956/? V/installed: DexInv: --- END '/data/app/com.shuttertop.android-rEYfbtFU55zjW8b1E1ljqg==/base.apk' (success) ---
08-04 08:49:44.702 1892-4484/? I/BackgroundDexOptService: Pinning optimized code {com.shuttertop.android, com.google.android.dialer, com.google.android.gms}
08-04 08:49:52.200 1892-4629/? I/ActivityManager: Force stopping com.shuttertop.android appid=10085 user=0: from pid 4703
08-04 08:49:57.825 1892-1908/? I/ActivityManager: Force stopping com.shuttertop.android appid=10085 user=-1: installPackageLI
08-04 08:49:57.908 1892-1921/? I/PackageManager: Update package com.shuttertop.android code path from /data/app/com.shuttertop.android-rEYfbtqU55zjW8b1E1ljqg== to /data/app/com.shuttertop.android-JekC485-n_hqk7qvhM12yg==; Retain data and using new
    Update package com.shuttertop.android resource path from /data/app/com.shuttertop.android-rEYfbtFU55zjW8b1E1ljqg== to /data/app/com.shuttertop.android-JekC485-n+
q_hqk7WvhM12yg==; Retain data and using new
08-04 08:49:57.997 2564-4753/? I/IntentFilterIntentSvc: Verifying IntentFilter. verificationId:0 scheme:"https" hosts:"shuttertop.com" package:"com.shuttertop.android".
08-04 08:49:58.176 1892-1921/? I/ActivityManager: Force stopping com.shuttertop.android appid=10085 user=0: pkg removed
08-04 08:49:58.224 1892-1908/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
08-04 08:49:58.493 1892-3951/? I/ActivityManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.shuttertop.android/.MainActivity (has extras)} from uid 2000
08-04 08:49:58.966 1892-1910/? I/ActivityManager: Start proc 4794:com.shuttertop.android/u0a85 for activity com.shuttertop.android/.MainActivity
08-04 08:49:59.076 2564-4754/? I/SingleHostAsyncVerifier: Verification result: checking for a statement with source a <
      a: "https://shuttertop.com"
    >
    , relation delegate_permission/common.handle_all_urls, and target b <
      a: "com.shuttertop.android"
      b <
        a: "***"
      >
    >
     --> false.
08-04 08:49:59.076 2564-4753/? I/IntentFilterIntentSvc: Verification 0 complete. Success:false. Failed hosts:shuttertop.com.
08-04 08:49:59.825 4794-4794/com.shuttertop.android D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-04 08:49:59.828 4794-4794/com.shuttertop.android D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-04 08:49:59.830 4794-4794/com.shuttertop.android D/FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
08-04 08:49:59.831 4794-4794/com.shuttertop.android I/FirebaseInitProvider: FirebaseApp initialization successful
08-04 08:50:00.176 4794-4794/com.shuttertop.android D/AndroidRuntime: Shutting down VM
**08-04 08:50:00.215 4794-4794/com.shuttertop.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shuttertop.android, PID: 4794
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.shuttertop.android/com.shuttertop.android.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.shuttertop.android.MainActivity" on path: DexPathList[[zip file "/data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/base.apk"],nativeLibraryDirectories=[/data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/lib/x86_64, /data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/base.apk!/lib/x86_64, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.shuttertop.android.MainActivity" on path: DexPathList[[zip file "/data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/base.apk"],nativeLibraryDirectories=[/data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/lib/x86_64, /data/app/com.shuttertop.android-JekC485-n_hqk7WvhM12yg==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)** 
08-04 08:50:00.220 4794-4822/com.shuttertop.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-04 08:50:00.238 1892-3877/? W/ActivityManager:   Force finishing activity com.shuttertop.android/.MainActivity
08-04 08:50:00.290 4794-4794/com.shuttertop.android I/Process: Sending signal. PID: 4794 SIG: 9
08-04 08:50:00.313 1892-3877/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
08-04 08:50:00.314 1892-1908/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
08-04 08:50:00.436 1892-4629/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
08-04 08:50:00.484 1892-3877/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
08-04 08:50:00.486 1892-1908/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.apps.photos/.account.full.FetchAccountPropertiesAppUpgradeBroadcastReceiver
08-04 08:50:00.487 1892-1908/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.apps.photos/.account.full.SyncAccountsForLoginBroadcastReceiver
    Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.apps.photos/.experiments.phenotype.full.PhenotypeAppUpgradeBroadcastReceiver
    Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.apps.photos/.notificationchannels.AppUpdateBroadcastReceiver
08-04 08:50:00.643 1892-1902/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.shuttertop.android flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
08-04 08:50:00.665 2564-4847/? I/ChromeSync: [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.shuttertop.android flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
08-04 08:50:00.676 1892-2165/? I/ActivityManager: Process com.shuttertop.android (pid 4794) has died: vis  +99TOP 


```

**Comment by ebeem** [comment]
seems like u accidentally removed/modified your Android `MainActivity` class
can you make sure that `android/app/src/main/kotlin/PACKAGE_NAME/MainActivity.kt` exist?

this file has the MainActivity class that your project could not find, here is the content of mine for your reference

```
package PACKAGE_NAME

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity(): FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}

```

also, make sure you have not changed your AndroidManifest.xml
specifically, these lines

```
<activity
            android:name=".MainActivity"
```

**Comment by romaluca** [comment]
I solved with
`flutter clean`

**Comment by rakeshparveen5** [comment]
@romaluca Thank you :+1:

**Comment by Benjith** [comment]
If you migrated from kotlin to java, you can specify source file in build.gradle 
`sourceSets {
        main.java.srcDirs += 'src/main/**java**'
    }`

**Comment by phanirithvij** [comment]
`flutter clean` did not work for me

**Comment by phanirithvij** [comment]
The error was resolved after I edited my package name everywhere to be the same. And made sure that there was a `MainActivity.java` or `MainActivity.kt` in the `android/app/src/main/kotlin/PACKAGE_NAME/` directory

**Comment by Atuldubey98** [comment]
> `flutter clean` did not work for me

Was this problem solved ? I am also facing the same problem

**Comment by JigarMangukiya7876** [comment]
Hi @Atuldubey98 
please udpate your flutter version.
This may solved your issue.
Thank you

**Comment by nabil25x** [comment]
none of the solutions above worked, any new solutions??
