### ISSUE TITLE
Changed nothing yet flutter has stopped working?

### ISSUE THREAD

**Issue by Joseph-Grabski** [flutter/flutter#20221]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad config line 1 in file .git/config

```
#0      _runSync (package:flutter_tools/src/version.dart:475)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:282)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#10     _rootRunUnary (dart:async/zone.dart:1134)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#14     Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     Future._complete (dart:async/future_impl.dart:472)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#23     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad config line 1 in file .git/config


#0      _runSync (package:flutter_tools/src/version.dart:475)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:129)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:120)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:282)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:194)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     _runZoned (dart:async/zone.dart:1518)
#12     runZoned (dart:async/zone.dart:1465)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:193)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:171)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:126)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     _runZoned (dart:async/zone.dart:1518)
#22     runZoned (dart:async/zone.dart:1465)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:42)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:50)
#26     main (package:flutter_tools/executable.dart:50)
<asynchronous suspension>
#27     main (file:///C:/Users/User/Documents/_Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by ebeem** [comment]
seems like your `.git/config` file is incorrect, maybe you want to check it out and see if something is missing.
here is mine for your reference

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/flutter/flutter.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

```
if yours is empty or has a different syntax ... which is probably at line#1 as the exception says, then you have to fix it and try again.
note that your problem is a git problem rather than a flutter one, and `flutter doctor` tries to use git to get version information but it failed to do so.

if you don't know what to do, cloning the flutter project again should fix the problem.

**Comment by Joseph-Grabski** [comment]
I copied your .git/config and I still get the same issue.

**Comment by Joseph-Grabski** [comment]
When I try to run flutter doctor or any flutter command it says that the command isn't found

**Comment by ebeem** [comment]
command not found is a different error, I think your flutter setup is not right
follow the guide here again 

https://flutter.io/get-started/install/

**Comment by Joseph-Grabski** [comment]
I think I fixed the .git/config issue, but in Visual Studio Code I have the Flutter extension installed - yet there's no syntax highlighting and I can't run Flutter commands. I can use the flutter console from the SDK folder.

**Comment by Joseph-Grabski** [comment]
I managed to fix it using the answer in [https://github.com/Microsoft/vscode/issues/45109](this thread)

**Comment by Nedzierra** [comment]
> seems like your `.git/config` file is incorrect, maybe you want to check it out and see if something is missing.
> here is mine for your reference
> 
> ```
> [core]
> 	repositoryformatversion = 0
> 	filemode = true
> 	bare = false
> 	logallrefupdates = true
> [remote "origin"]
> 	url = https://github.com/flutter/flutter.git
> 	fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
> 	remote = origin
> 	merge = refs/heads/master
> ```
> 
> if yours is empty or has a different syntax ... which is probably at line#1 as the exception says, then you have to fix it and try again.
> note that your problem is a git problem rather than a flutter one, and `flutter doctor` tries to use git to get version information but it failed to do so.
> 
> if you don't know what to do, cloning the flutter project again should fix the problem.

hi sir, where can i find the file ".git/config"? because i have same problem and i cannot found the file.
