### ISSUE TITLE
Uninformative error

### ISSUE THREAD

**Issue by kjwilde** [flutter/flutter#20229]
The following is received when I try to pass a stateless or statefull widget to a window and then use that instance to navigate to it:

```
I/flutter ( 8496): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8496): The following assertion was thrown building Builder(dirty):
I/flutter ( 8496): type '_Type' is not a subtype of type 'Widget'
I/flutter ( 8496): 
I/flutter ( 8496): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8496): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8496): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8496):   https://github.com/flutter/flutter/issues/new
I/flutter ( 8496): 
I/flutter ( 8496): When the exception was thrown, this was the stack:
I/flutter ( 8496): #0      NavButton.build.<anonymous closure>.<anonymous closure> (file:///C:/Users/kwilde/AndroidStudioProjects/ign_mobile_test_4/lib/nav_button.dart:34:41)
I/flutter ( 8496): #1      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:156:14)
I/flutter ( 8496): #2      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:497:43)
I/flutter ( 8496): #3      Builder.build (package:flutter/src/widgets/basic.dart:5377:41)
I/flutter ( 8496): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter ( 8496): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter ( 8496): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 8496): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 8496): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 8496): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 8496): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #80     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 8496): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter ( 8496): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter ( 8496): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter ( 8496): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter ( 8496): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter ( 8496): #91     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4437:32)
I/flutter ( 8496): #92     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter ( 8496): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #94     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 8496): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 8496): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter ( 8496): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 8496): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter ( 8496): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 8496): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter ( 8496): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter ( 8496): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter ( 8496): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter ( 8496): #116    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter ( 8496): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter ( 8496): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 8496): #119    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8496): #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8496): #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8496): #122    _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 8496): #123    _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 8496): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by goderbauer** [comment]
Can you provide a code example that I can use to reproduce the error? Doing so will make this easier to debug.

**Comment by jonahwilliams** [comment]
I've seen the above error with code such as the following:
```
Widget build(_) => Container;
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
