### ISSUE TITLE
RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by wwjd2016** [flutter/flutter#20251]
I got this error when i clone this project on macOS:
```
git clone -b beta https://github.com/flutter/flutter.git

Cloning into 'flutter'...
remote: Counting objects: 132693, done.
remote: Compressing objects: 100% (26/26), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Do you have this problem？and how to resolve it ?

**Comment by zoechi** [comment]
Is this permanent or was it temporary.
Looks more like OS or Git related than Flutter related.

**Comment by wwjd2016** [comment]
@zoechi The windows at home, it works. It seems to be caused by the network of my company or OS，and i used another way, download the zip file, and it works. Thanks!

**Comment by zoechi** [comment]
Thanks for the update!
If `git clone` fails, it's not related to Flutter.

**Comment by aneesalahsab** [comment]
> @zoechi The windows at home, it works. It seems to be caused by the network of my company or OS，and i used another way, download the zip file, and it works. Thanks!

I,m download zip file.. where I extract her ? 
I went  path 
thank you...

**Comment by zoechi** [comment]
@aneesalahsab in https://flutter.io/docs/get-started/install chose your OS and then follow the instructions. They suggest install directories as far as I remember. 
Extract it to a user-related directory where your user account has write permissions (not in a global directory where you need elevated privileges to write).

**Comment by aneesalahsab** [comment]
sam problim...
Launching lib/main.dart on N9560 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "/Users/mac/AndroidStudioProjects/flutter_plugin19/example/android/gradlew" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip


Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 16 more
  Command: /Users/mac/AndroidStudioProjects/flutter_plugin19/example/android/gradlew -v

**Comment by zoechi** [comment]
@aneesalahsab are you behind a proxy?
