### ISSUE TITLE
Issue with show dialog onTap ListTitle widget

### ISSUE THREAD

**Issue by marceloimg93** [flutter/flutter#20302]
I have an issue trying to show a dialog when tapping a LisTitle widget;

When I call the function to showDialog
```
new ListTile( onTap: () => _showQuakes(context, _features[position]['title']) )
```
showDialog function
```
void _showQuakes(BuildContext context, String message) {
  var alert = new AlertDialog(
    title: Text('My app'),
    
    content: Text(message),
    actions: <Widget>[
      new FlatButton(
        child: new Text('OK'),
        onPressed: () { Navigator.pop(context); },
      )
    ],
  );

  showDialog(context: context, builder: (context) => alert);
}
```

Error on terminal

> flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
> flutter: The following assertion was thrown while handling a gesture:
> flutter: 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
> flutter: true.
> flutter:
> flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
> flutter: more information in this error message to help you determine and fix the underlying cause.
> flutter: In either case, please report this assertion by filing a bug on GitHub:
> flutter:   https://github.com/flutter/flutter/issues/new
> flutter:
> flutter: When the exception was thrown, this was the stack:
> flutter: #2      new Text (package:flutter/src/widgets/text.dart:230:15)
> flutter: #3      _showQuakes (file:///Users/marceloivomendesgontijo/projects/learning/flutter/challenge_earth_quake/lib/main.dart:81:14)
> flutter: #4      MyApp.build.<anonymous closure>.<anonymous closure> (file:///Users/marceloivomendesgontijo/projects/learning/flutter/challenge_earth_quake/lib/main.dart:65:32)
> flutter: #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
> flutter: #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
> flutter: #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
> flutter: #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
> flutter: #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
> flutter: #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
> flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
> flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
> flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
> flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
> flutter: #16     _invoke1 (dart:ui/hooks.dart:142:13)
> flutter: #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)
> flutter: (elided 2 frames from class _AssertionError)
> flutter:
> flutter: Handler: onTap
> flutter: Recognizer:
> flutter:   TapGestureRecognizer#3877c(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
> flutter:   Offset(195.0, 342.3), sent tap down)
> flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by marceloimg93** [comment]
Err... I figure it out;

the error message was flutter:

> 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
> flutter: true.

The data I was sending to the showDialog function was = null;
