### ISSUE TITLE
Flutter debug not work

### ISSUE THREAD

**Issue by IshanFx** [flutter/flutter#20304]
My flutter app work fine until I add release config. After that when I try to run in debug mode this error shows in console and app not get loaded. It stuck in white screen.
I/flutter (19596): Observatory server failed to start after 1 tries
I/flutter (19596): Observatory server failed to start after 2 tries
I/flutter (19596): Observatory server failed to start after 3 tries
I/flutter (19596): Observatory server failed to start after 4 tries
I/flutter (19596): Observatory server failed to start after 5 tries
I/flutter (19596): Observatory server failed to start after 6 tries
I/flutter (19596): Observatory server failed to start after 7 tries
I/flutter (19596): Observatory server failed to start after 8 tries
I/flutter (19596): Observatory server failed to start after 9 tries
I/flutter (19596): Observatory server failed to start after 10 tries
I/flutter (19596): Observatory server failed to start after 11 tries
I/flutter (19596): Could not start Observatory HTTP server:
I/flutter (19596): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
I/flutter (19596): #0      _NativeSocket.bind (dart:io/runtime/binsocket_patch.dart:545:7)
I/flutter (19596): <asynchronous suspension>
I/flutter (19596): #1      _RawServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1138:10)
I/flutter (19596): #2      _ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1385:10)
I/flutter (19596): #3      ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1375:26)
I/flutter (19596): #4      _HttpServer.bind (dart:_http/http_impl.dart:2503:10)
I/flutter (19596): #5      HttpServer.bind (dart:_http:276:19)
I/flutter (19596): #6      Server.startup.poll (dart:vmservice_io/server.dart:352:36)
I/flutter (19596): <asynchronous suspension>
I/flutter (19596): #7      Server.startup (dart:vmservice_io/server.dart:364:23)
I/flutter (19596): <asynchronous suspension>
I/flutter (19596): #8      main (dart:vmservice_io:239:12)

How to fix this?

**Comment by IshanFx** [comment]
I found the the issue. I removed network permission when creating release. But It required to developement. So I added that app to manifest and everything works fine.
