### ISSUE TITLE
NPE during rendering - width accessed on a null reference

### ISSUE THREAD

**Issue by dguralnick** [flutter/flutter#20313]
I saw this happen when clicking around in our app. It seems like it happened during a screen transition when we popped a route. Unfortunately I've not been able to repro. Thought I'd file this anyways in case you've seen anything similar in the past. Feel free to close if it's not helpful.

```
08-07 16:42:20.020 15663 15681 I flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
08-07 16:42:20.021 15663 15681 I flutter : The following NoSuchMethodError was thrown during a scheduler callback:
08-07 16:42:20.021 15663 15681 I flutter : The getter 'width' was called on null.
08-07 16:42:20.021 15663 15681 I flutter : Receiver: null
08-07 16:42:20.021 15663 15681 I flutter : Tried calling: width
08-07 16:42:20.021 15663 15681 I flutter : 
08-07 16:42:20.021 15663 15681 I flutter : When the exception was thrown, this was the stack:
08-07 16:42:20.022 15663 15681 I flutter : #0      Offset.& (dart:ui/geometry.dart:290)
08-07 16:42:20.022 15663 15681 I flutter : #1      RenderBox.get:semanticBounds (package:flutter/src/rendering/box.dart:1620)
08-07 16:42:20.022 15663 15681 I flutter : #2      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:3401)
08-07 16:42:20.022 15663 15681 I flutter : #3      new _SemanticsGeometry. (package:flutter/src/rendering/object.dart:3359)
08-07 16:42:20.022 15663 15681 I flutter : #4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3272)
08-07 16:42:20.022 15663 15681 I flutter : #5      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
08-07 16:42:20.022 15663 15681 I flutter : #6      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:144)
08-07 16:42:20.022 15663 15681 I flutter : #7      _GrowableList.addAll (dart:core/runtime/libgrowable_array.dart:194)
08-07 16:42:20.022 15663 15681 I flutter : #8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3298)
08-07 16:42:20.022 15663 15681 I flutter : #9      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
08-07 16:42:20.022 15663 15681 I flutter : #10     Iterable.get:single (dart:core/iterable.dart:552)
08-07 16:42:20.022 15663 15681 I flutter : #11     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2334)
08-07 16:42:20.022 15663 15681 I flutter : #12     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887)
08-07 16:42:20.022 15663 15681 I flutter : #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274)
08-07 16:42:20.022 15663 15681 I flutter : #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627)
08-07 16:42:20.022 15663 15681 I flutter : #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
08-07 16:42:20.022 15663 15681 I flutter : #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
08-07 16:42:20.022 15663 15681 I flutter : #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
08-07 16:42:20.023 15663 15681 I flutter : #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
08-07 16:42:20.023 15663 15681 I flutter : #19     CoreActivityZoneImpl._run.<anonymous closure> (package:ads.acx2.tracking.activity.core.zone/zone.dart:200)
08-07 16:42:20.023 15663 15681 I flutter : #22     CoreActivityZoneImpl._run (package:ads.acx2.tracking.activity.core.zone/zone.dart:197)
08-07 16:42:20.023 15663 15681 I flutter : #25     _invoke (dart:ui/hooks.dart:127)
08-07 16:42:20.023 15663 15681 I flutter : #26     _drawFrame (dart:ui/hooks.dart:114)
08-07 16:42:20.023 15663 15681 I flutter : (elided 4 frames from package dart:async)
08-07 16:42:20.023 15663 15681 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jonahwilliams** [comment]
We might be missing an assert when updating semantics - all render objects must have their size set at this point.

**Comment by mehmetf** [comment]
We have a consistent repro for this now. Please see the internal bug. It is also worth noting that it is the most frequent crash experienced by Mulligan. b/116148083

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/blob/cf2fba7b3b32fc81bc4514703584e42eec6b9626/packages/flutter/lib/src/rendering/box.dart#L1610

@jonahwilliams what assert are you envisioning?  We already assert that `hasSize` is true when we're asked for `size`, but assertions are turned off 'cause this is in release mode.

**Comment by Hixie** [comment]
I'm concerned about this stack. It shouldn't be reaching past `flushSemantics` if accessibility is disabled (in the Google bug it is claimed that this repros without talkback).

**Comment by tvolkert** [comment]
Sounds like Talkback being enabled is related to this bug.  It's currently the top crasher being reported for customer:mulligan.

/cc @dnfield @jonahwilliams

**Comment by dguralnick** [comment]
I've seen it happen on my personal device where I run lastpass (which also performs the accessibility pass).

The precise conditions to reproduce this error are elusive, but we have a fairly reliable way to repro in a development build of our app on a recent release branch.

**Comment by dnfield** [comment]
@jonahwilliams - what about changing https://github.com/flutter/flutter/blob/b55e52c6f73e327b1f9c2b3848b1bc9318767733/packages/flutter/lib/src/rendering/viewport.dart#L182 to 

```dart
    .where((RenderSliver sliver) => sliver.geometry != null && (sliver.geometry.visible || sliver.geometry.cacheExtent > 0.0))
```

**Comment by jonahwilliams** [comment]
@dnfield  If we have a consistent repro, we could apply the patch suggested above internally and see if it removes the error condition. If so, we can land the fix but also take that as an opportunity to reproduce the original error case.

**Comment by tvolkert** [comment]
Cross-posting @dguralnick's comment from internal bug:

> That (checking if `sliver.geometry` is null) would likely be a partial fix; there is an underlying issue causing other similar crashes. For instance, the first issue referenced in this bug: width is called on a null geometry instance here:
https://github.com/flutter/engine/blob/df2e9393a247a8bbe658293dd7ea8da5cdbb8a04/lib/ui/geometry.dart#L290
