### ISSUE TITLE
Navigator.of(context).pop() . below error

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#20334]
```
[0x60800027a900][NW:6.2.1.43] [SessionSocket] recv ping reply [ 0 ] in 39.106.237.88:80
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 155 pos 16:
flutter: '!overlayEntries.first.opaque': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart)
flutter: #3      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:531:7)
flutter: #5      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:396:7)
flutter: #6      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:346:12)
flutter: #7      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:208:17)
flutter: #8      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:369:18)
flutter: #9      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1682:15)
flutter: #10     Router.popPageWithOptionsFromNative (package:dmflutter/router/router.dart:95:67)
flutter: #11     CouponDetail.build.<anonymous closure> (package:dmflutter/coupon.dart:32:37)
flutter: #12     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
flutter: #13     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
flutter: #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #15     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
flutter: #16     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
flutter: #17     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #25     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#f839f(⏮ 0.000; paused; for DMaterialPageRoute<dynamic>(null))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
Dup of #20130
It would be helpful if you could provide the code for a minimal reproduction. 
Please upvote and post additional information in #20130
