### ISSUE TITLE
EXCEPTION CAUGHT BY SCHEDULER LIBRARY heroes.dart: Failed assertion: line 322 pos 12

### ISSUE THREAD

**Issue by 1and1get2** [flutter/flutter#20366]
when running a simple flutter project (a few method channel involved, some routes, nothing much else going on), on my android studio encountered an error as following:

```
I/flutter ( 4975): service extension method received: ext.flutter.inspector.setPubRootDirectories({arg0: /Volumes/Persistence/Data/Workspace/Flutter/Mine/recorder_flutter/recorder, isolateId: isolates/851771930})
I/flutter ( 4975): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4975): The following assertion was thrown during a scheduler callback:
I/flutter ( 4975): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 322 pos 12: '() {
I/flutter ( 4975):       final Animation<double> initial = initialManifest.animation;
I/flutter ( 4975):       switch (initialManifest.type) {
I/flutter ( 4975):         case _HeroFlightType.pop:
I/flutter ( 4975):           return initial.value == 1.0 && initial.status == AnimationStatus.reverse;
I/flutter ( 4975):         case _HeroFlightType.push:
I/flutter ( 4975):           return initial.value == 0.0 && initial.status == AnimationStatus.forward;
I/flutter ( 4975):       }
I/flutter ( 4975):     }()': is not true.
I/flutter ( 4975): 
I/flutter ( 4975): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4975): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4975): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4975):   https://github.com/flutter/flutter/issues/new
I/flutter ( 4975): 
I/flutter ( 4975): When the exception was thrown, this was the stack:
I/flutter ( 4975): #2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart)
I/flutter ( 4975): #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:532:64)
I/flutter ( 4975): #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
I/flutter ( 4975): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4975): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter ( 4975): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 4975): #9      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 4975): #10     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 4975): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 4975): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 4975): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4975): service extension method received: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_8, isolateId: isolates/851771930})
I/flutter ( 4975): Action "Wait for outer event loop" took 0:00:00.820892
```

but nothing seemed abnormal on my app.

no idea how relevant this is, if not, or if it's something you guys are already working on, feel free to close it.

## Logs

`refer to the log file`
[log.log.zip](https://github.com/flutter/flutter/files/2272666/log.log.zip)

##  flutter analyze

```
Analyzing recorder...

   info • Unused import: 'package:flutter/foundation.dart' • lib/App.dart:3:8
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/App.dart:15:7
   info • Unused import: 'dart:async' • lib/BuildConfig.dart:1:8
   info • Unused import: 'dart:async' • lib/main.dart:1:8
   info • 'debugEnableFadingRoutes' is deprecated and shouldn't be used • lib/main.dart:19:21
   info • Unused import: 'dart:async' • lib/model/model_recording.dart:3:8
   info • Unused import: 'package:recorder/App.dart' • lib/model/model_recording.dart:4:8
   info • Use `;` instead of `{}` for empty constructor bodies • lib/model/model_recording.dart:39:22
   info • Use `;` instead of `{}` for empty constructor bodies • lib/model/model_recording.dart:43:26
   info • The method '_updateLastEdit' isn't used • lib/model/model_recording.dart:51:3
   info • Name non-constant identifiers using lowerCamelCase • lib/playground.dart:1:20
   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/services/database.dart:4:8
   info • Unused import: 'dart:io' • lib/ui/update_list.dart:1:8
   info • Unused import: 'package:recorder/App.dart' • lib/ui/update_list.dart:8:8
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/update_list.dart:15:20
   info • Avoid using braces in interpolation when not needed • lib/ui/update_list.dart:96:21
   info • Avoid using braces in interpolation when not needed • lib/ui/update_list.dart:96:29
   info • 'child' is deprecated and shouldn't be used • lib/ui/update_list.dart:129:17
   info • Unused import: 'package:recorder/main.dart' • test/widget_test.dart:12:8
```

##  flutter doctor -v

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.14 18A353d, locale en-NZ)
    • Flutter version 0.5.1 at /Volumes/Persistence/Library/Google/flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Volumes/Persistence/Library/Google/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/ExternalApplications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L213o
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio
    • Android Studio at /Applications/ExternalApplications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/ExternalApplications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • GT I9505 • 9c8b3912 • android-arm • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```

**Comment by slightfoot** [comment]
@zoechi I've been seeing reports in our released apps for similar crashes. I think they might be related so logging it here.

```
iOS 11.4.1, iPhone9,3, 
2.0.0-dev.63.0.flutter-4c9689c1d2 (Mon Jun 18 15:50:02 2018 +0000) on "ios_arm64"
```

```
NoSuchMethodError: NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove()
  File "heroes.dart", line 310, in _HeroFlight._handleAnimationUpdate
  File "listener_helpers.dart", line 161, in _ProxyAnimation&Animation&AnimationLazyListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "listener_helpers.dart", line 161, in _ProxyAnimation&Animation&AnimationLazyListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "listener_helpers.dart", line 161, in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "animation_controller.dart", line 531, in AnimationController._checkStatusChanged
  File "animation_controller.dart", line 547, in AnimationController._tick
  File "ticker.dart", line 229, in Ticker._tick
  File "binding.dart", line 990, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 906, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn>
  File "libcompact_hash.dart", line 363, in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
  File "binding.dart", line 904, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame
  File "binding.dart", line 834, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame
  File "zone.dart", line 1138, in _rootRunUnary
  File "zone.dart", line 1031, in _CustomZone.runUnary
  File "zone.dart", line 933, in _CustomZone.runUnaryGuarded
  File "hooks.dart", line 136, in _invoke1
  File "hooks.dart", line 105, in _beginFrame
```

```
NoSuchMethodError: NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove()
  File "heroes.dart", line 310, in _HeroFlight._handleAnimationUpdate
  File "listener_helpers.dart", line 161, in _ProxyAnimation&Animation&AnimationLazyListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "listener_helpers.dart", line 161, in _ProxyAnimation&Animation&AnimationLazyListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "listener_helpers.dart", line 161, in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "animation_controller.dart", line 531, in AnimationController._checkStatusChanged
  File "animation_controller.dart", line 547, in AnimationController._tick
  File "ticker.dart", line 229, in Ticker._tick
  File "binding.dart", line 990, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 906, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn>
  File "libcompact_hash.dart", line 363, in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
  File "binding.dart", line 904, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame
  File "binding.dart", line 834, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame
  File "zone.dart", line 1138, in _rootRunUnary
  File "zone.dart", line 1031, in _CustomZone.runUnary
  File "zone.dart", line 933, in _CustomZone.runUnaryGuarded
  File "hooks.dart", line 136, in _invoke1
  File "hooks.dart", line 105, in _beginFrame
```

Looks like the crash logs are for an Hero animation going forwards and reverse.

**Comment by 1and1get2** [comment]
this seems to be fixed with the lastest flutter. I'm on dev branch
