### ISSUE TITLE
ProcessException: ProcessException: Permission denied

### ISSUE THREAD

**Issue by abidin5515** [flutter/flutter#20364]
ProcessException: ProcessException: Permission denied
  Command: /home/abidin/Android/Sdk/tools/bin/sdkmanager --licenses

```
#0      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:193)
<asynchronous suspension>
#1      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:152)
<asynchronous suspension>
#2      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#3      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#4      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1126)
#17     _CustomZone.run (dart:async/zone.dart:1023)
#18     runZoned (dart:async/zone.dart:1501)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#22     new Future.sync (dart:async/future.dart:222)
#23     CommandRunner.run (package:args/command_runner.dart:109)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1126)
#28     _CustomZone.run (dart:async/zone.dart:1023)
#29     runZoned (dart:async/zone.dart:1501)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50)
#33     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#34     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: ProcessException: Permission denied
  Command: /home/abidin/Android/Sdk/tools/bin/sdkmanager --licenses

#0      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:193)
<asynchronous suspension>
#1      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:152)
<asynchronous suspension>
#2      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#3      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#4      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:194)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126)
#7      _CustomZone.run (dart:async/zone.dart:1023)
#8      runZoned (dart:async/zone.dart:1501)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#10     _doctorText (package:flutter_tools/runner.dart:193)
<asynchronous suspension>
#11     _createLocalCrashReport (package:flutter_tools/runner.dart:171)
<asynchronous suspension>
#12     _handleToolError (package:flutter_tools/runner.dart:126)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#20     run (package:flutter_tools/runner.dart:50)
#21     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#22     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by zoechi** [comment]
What happens when you execute `/home/abidin/Android/Sdk/tools/bin/sdkmanager --licenses` manually? 
Does the user you are using not have write permissions in the `Android/Sdk` directory?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ritshpatidar** [comment]
ProcessException: ProcessException: Permission denied
Command: /home/abidin/Android/Sdk/tools/bin/sdkmanager --licenses

That means sdkmanager file(or whatever)  needs permission. So, simply give it permission:
```
cd /home/abidin/Android/Sdk/tools/bin/
chmod 777 sdkmanager
```

**Comment by Mritunjay10** [comment]
![Screenshot from 2019-04-05 23-45-09](https://user-images.githubusercontent.com/34881570/55648082-f5e03f00-57fc-11e9-8704-cf7ddcabd931.png)

Make sure your sdkmanger file and adb file are marked as executable. For reference, look at the checkbox in the given image. Hope it helps!!
