### ISSUE TITLE
flutter change channel  master   Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by txg17459** [flutter/flutter#20380]
## Steps to Reproduce

1. ...flutter upgrade
2. ...
Upgrading Flutter from /Users/admin/flutter...
Already up to date.

Upgrading engine...
Downloading common tools...

Oops; flutter has exited unexpectedly.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-version-check doctor

## exception

HttpException: HttpException: Invalid request method, uri = //storage.googleapis.com:443

```
#0      _attempt (package:flutter_tools/src/base/net.dart:42:15)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22:36)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:568:37)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:299:17)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:328:26)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:295:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:315:12)
#7      FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:487:13)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:258:11)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:214:26)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:331:19)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:282:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:273:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:346:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:302:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:109:11)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:50:10)
#41     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#42     main (file:///Users/admin/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:284:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
```

## flutter doctor

```
[!] Flutter (Channel master, v0.5.8-pre.277, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 0.5.8-pre.277 at /Users/admin/flutter
    • Framework revision e5432a2843 (16 hours ago), 2018-08-08 16:45:08 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK at /Users/admin/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.15.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 4.2.2 (API 17) (emulator)

! Doctor found issues in 3 categories.
```

```
```

```
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
