### ISSUE TITLE
Trying to create virtual displays with illegal arguments

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#20456]
We sometimes run into this exception when trying to embed an Android view:

```
E/MethodChannel#flutter/platform_views(21083): Failed to handle method call
E/MethodChannel#flutter/platform_views(21083): java.lang.IllegalArgumentException: width, height, and densityDpi must be greater than 0
E/MethodChannel#flutter/platform_views(21083):  at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:391)
E/MethodChannel#flutter/platform_views(21083):  at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:599)
E/MethodChannel#flutter/platform_views(21083):  at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:590)
E/MethodChannel#flutter/platform_views(21083):  at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:541)
E/MethodChannel#flutter/platform_views(21083):  at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:33)
E/MethodChannel#flutter/platform_views(21083):  at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:131)
E/MethodChannel#flutter/platform_views(21083):  at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:88)
E/MethodChannel#flutter/platform_views(21083):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter/platform_views(21083):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:165)
E/MethodChannel#flutter/platform_views(21083):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(21083):  at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter/platform_views(21083):  at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter/platform_views(21083):  at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#flutter/platform_views(21083):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(21083):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#flutter/platform_views(21083):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

It looks like for some times querying the current display metrics returns zeros.
I can sometimes repro this when doing `flutter run` while the phone's screen is off.
My guess is that FlutterView is detached when we are trying to created the virtual display, can probably either cache the values when they are first available, or wait for the view to be attached before creating a vd.

**Comment by amirh** [comment]
Turns out when the screen is off we pump a single (0,0) frame which causes the crash.

**Comment by luwuer** [comment]
@amirh 
Why size android views to (0, 0 ) will causes crash? In fact i now get the same error when i size a webview(render by Android Views) to (0.1, 0.1).

Why me set width to (0.1, 0.1)?
Because i dont want to modify sdk code and i want paint(render) a webview but dont display in screen,just like css `display: none`，so that i can conmunicate with webview inner Javascript.
