### ISSUE TITLE
Exception after flutter run on a new project

### ISSUE THREAD

**Issue by Cae2** [flutter/flutter#20488]
Got the exception below after installing flutter and run it without any modification:

-----------------
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

String: Exit code 1 from: C:\Projetos\flutter\first\android\gradlew.bat -v:
Exception in thread "main" java.lang.RuntimeException: Could not load wrapper properties from 'C:\Projetos\flutter\first\android\gradle\wrapper\gradle-wrapper.properties'.
	at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:64)
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:47)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
Caused by: java.lang.RuntimeException: No value with key 'distributionUrl' specified in wrapper properties file 'C:\Projetos\flutter\first\android\gradle\wrapper\gradle-wrapper.properties'.
	at org.gradle.wrapper.WrapperExecutor.reportMissingProperty(WrapperExecutor.java:156)
	at org.gradle.wrapper.WrapperExecutor.readDistroUrlDeprecatedWay(WrapperExecutor.java:99)
	at org.gradle.wrapper.WrapperExecutor.readDistroUrl(WrapperExecutor.java:84)
	at org.gradle.wrapper.WrapperExecutor.prepareDistributionUri(WrapperExecutor.java:70)
	at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:57)
	... 2 more

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:249)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:180)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:97)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:90)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:84)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:88)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:272)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1501)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     runZoned (dart:async/zone.dart:1501)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#28     new Future.sync (dart:async/future.dart:222)
#29     CommandRunner.run (package:args/command_runner.dart:109)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1126)
#34     _CustomZone.run (dart:async/zone.dart:1023)
#35     runZoned (dart:async/zone.dart:1501)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50)
#39     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#40     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale pt-BR)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by Cae2** [comment]
solved by reinstalling flutter sdk (probably I missed something earier)
