### ISSUE TITLE
[firebase_database][firebase_animated_list] the method 'insertItem' was called on null

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20523]
here's my widget

```dart
Widget build(BuildContext context) {
    return FirebaseAnimatedList(
      query: FirebaseDatabase.instance
          .reference()
          .child('/users2/$uid/projects')
          .orderByChild('folder')
          .equalTo(null)
          .limitToLast(100),
      sort: (a, b) => (b.key).compareTo(a.key),
      itemBuilder: (_, snap, _animation, index) {
        Project project = Project(snap);

        return FadeTransition(
          opacity: _animation,
          child: Dismissible(
            onDismissed: (d) => _dismiss(d, project),
            key: Key(project.id),
            child: ProjectListItem(project: project),
          ),
        );
      },
    );
  }
```

here's my client side fanout that is triggering this (get new items from public ref, store to private ref)

```dart
  _fanout() async {
    /// get last key
    var snap = await ref.child('projects').orderByKey().limitToLast(1).once();

    /// listen for last 50 since last key
    FirebaseDatabase.instance
        .reference()
        .child('projects')
        .orderByKey()
        .startAt(snap.value?.keys?.first ?? '1')
        .limitToLast(50)
        .onChildAdded
        .listen((Event e) {
      DataSnapshot snap = e.snapshot;
      String pid = snap.key;

      print('update');

      Map<String, dynamic> value = Map.castFrom(snap.value);
      User.instance.ref.child('projects/$pid/').update(value);
    });
```

and here is the error I get every time a new item is pushed to my ref

```
NoSuchMethodError: The method 'insertItem' was called on null.
Receiver: null
Tried calling: insertItem(0, duration: Instance of 'Duration')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      FirebaseAnimatedListState._onChildAdded (package:firebase_database/ui/firebase_animated_list.dart:176:35)
#2      FirebaseSortedList._onChildAdded (package:firebase_database/ui/firebase_sorted_list.dart:90:5)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:578:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

note: this only happens when the values from my copy function are coming in quickly. Race condition? If I put in a breakpoint I can get thru all values without triggering this error.

**Comment by lambasoft** [comment]
I just would like to make you know guys that the same happened to me on a key of a PageView.Builder.

When I added a 1 second delay before the insertItem it worked perfectly!

```
  void addCard(ProfileCardModel card) async {
    int index = pageCards.length;
    pageCards.add(card);
    await Future.delayed(const Duration(seconds: 1), () => "1"); <--- I had to add this
    _pageViewKey.currentState
        .insertItem(index, duration: Duration(milliseconds: 500));
  }
```

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/712. Any further collaboration will be done there.
