### ISSUE TITLE
Error starting new project in flutter.

### ISSUE THREAD

**Issue by fillipeguerra** [flutter/flutter#20579]
I'm trying to create a new flutter project in android studio, but this message always appears 

> Oops; flutter has exited unexpectedly. Crash report written to C:\Users\Fillipe\Desktop\Projects\flutter_01.log; please let us know at https://github.com/flutter/flutter/issues. " .

And in the option flutter_01.log appears 

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter --no-color create --template app --description A new Flutter application. --org com.war flutter_app2
## exception
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Fillipe\Documents\Flutter\flutter_app2\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\src\flutter\packages\flutter_tools\templates\create\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Acesso negado.
, errno = 5)
```

```
#0      _File.throwIfError (dart:io/file_impl.dart:647)
#1      _File.copySync (dart:io/file_impl.dart:352)
#2      LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:29)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:159)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#5      Template.render (package:flutter_tools/src/template.dart:108)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:321)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:221)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Microsoft Windows [versÃ£o 10.0.17134.165], locale pt-BR)
    • Flutter version 0.5.1 at C:\src\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Fillipe\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
```
I would like someone to help me if possible. Thank you!

**Comment by zoechi** [comment]
This looks like a dup of #19522

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
