### ISSUE TITLE
Firebase Messing can't navigate when i lunch on onResume.

### ISSUE THREAD

**Issue by 9wisit** [flutter/flutter#20615]
## Steps to Reproduce

1. Push message form firebase messaging with datas.
2. Try to resume app when tap on notification.
3. Console error about context.

## My Code
```
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
        String id = message['id'];
        print("onMessage: $id");
        getNewsDetail(int.parse(id)).then((news) {
          print(news.information);
        });
      },
      onLaunch: (Map<String, dynamic> message) {
        String id = message['id'];
        print("onLaunch: $id");
          getNewsDetail(int.parse(id)).then((news) {
            Navigator.push(
              context,
              MaterialPageRoute(
                fullscreenDialog: true,
                builder: (context) => NewsDetailScreen(news),
              ),
            );
          });
      },
      onResume: (Map<String, dynamic> message) {
        String id = message['id'];
        print("onResume: $id");
        getNewsDetail(int.parse(id)).then((news) {
          Navigator.push(
            context,
            MaterialPageRoute(
              fullscreenDialog: true,
              builder: (context) => NewsDetailScreen(news),
            ),
          );
        });
      },
    );
```

## My Error
```
E/flutter ( 9961): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9961): Navigator operation requested with a context that does not include a Navigator.
E/flutter ( 9961): The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
E/flutter ( 9961): #0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1179:9)
E/flutter ( 9961): #1      Navigator.of (package:flutter/src/widgets/navigator.dart:1186:6)
E/flutter ( 9961): #2      Navigator.push (package:flutter/src/widgets/navigator.dart:816:22)
E/flutter ( 9961): #3      _InitAppState.initState.<anonymous closure>.<anonymous closure> (file:///Users/Wisit/FlutterProjects/sanuk_conn/lib/main.dart:83:21)
E/flutter ( 9961): #4      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter ( 9961): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter ( 9961): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter ( 9961): #7      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter ( 9961): #8      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter ( 9961): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 9961): #10     getNewsDetail (package:sanuk_conn/API.dart)
E/flutter ( 9961): <asynchronous suspension>
E/flutter ( 9961): #11     _InitAppState.initState.<anonymous closure> (file:///Users/Wisit/FlutterProjects/sanuk_conn/lib/main.dart:82:9)
E/flutter ( 9961): #12     FirebaseMessaging._handleMethod (package:firebase_messaging/firebase_messaging.dart:119:16)
E/flutter ( 9961): <asynchronous suspension>
E/flutter ( 9961): #13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:326:55)
E/flutter ( 9961): <asynchronous suspension>
E/flutter ( 9961): #14     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:299:54)
E/flutter ( 9961): #15     BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
E/flutter ( 9961): <asynchronous suspension>
E/flutter ( 9961): #16     _invoke3 (dart:ui/hooks.dart:162:13)
E/flutter ( 9961): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:75:5)
```

## Logs

```
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-TH)
    • Flutter version 0.5.1 at /Users/Wisit/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Wisit/Library/Android/sdk
    • Android NDK at /Users/Wisit/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (3 available)
    • SM G950F            • ce11171b0a92511104                       • android-arm64 • Android 8.0.0 (API 26)
    • .@TrexCode Devloper • 539ca7a9dcbf0538cc978fb5c942e90d6c385d43 • ios           • iOS 11.4.1
    • iPhone X            • 27B1EDA7-12D7-426F-90F4-1E24D0D85EE2     • ios           • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
You need a valid context. The context you pass doesn't seem to be a context that has a `Navigator` as parent.

**Comment by 9wisit** [comment]
So, How can i improve it?

**Comment by zoechi** [comment]
You need the context of a widget that is a descendant of the Navigator you're addressing.
Your code doesn't provide enough context.

Please consider asking support questions in one of the other channels listed in http://flutter.io/support .

**Comment by beatscode** [comment]
Hi @zoechi could you provide an example of getting the context of a widget that has a descendant? 
Below is a gist of an existing app I'm working on that will not navigate. Stepping through the code puts me here when calling the navigator.
![a6ed1735-4f0a-4120-a89c-c6e77c00a319](https://user-images.githubusercontent.com/1777648/47028389-538dab80-d137-11e8-979b-ab8e2015af73.png)

https://gist.github.com/beatscode/7a1ff933b0a05a6763aaad96266dd648

**Comment by zoechi** [comment]
@beatscode for example https://stackoverflow.com/questions/52186837/how-to-navigate-to-specific-materialpageroute-in-app-from-a-notification-in-flut/52190314#52190314

**Comment by beatscode** [comment]
@zoechi This solution didn't work for me initially. But I instead used Navigator.of(context) instead of Navigator.push(context). And this seems to work. I'm not clear on why using the NavigatorKey didn't work for me. Thanks anyway

**Comment by megadola** [comment]
Here is a working code [main.dart](https://github.com/megadola/Flutter---FCM-Redirecting-onLaunch-and-onResume/blob/master/main.dart)
