### ISSUE TITLE
`flutter has exited unexpectedly` when the debugging target is iOS

### ISSUE THREAD

**Issue by hariprasadiit** [flutter/flutter#20691]
here are the details.

same setup works fine with android.

on iOS app launches fine but, flutter exists with below error and loses connection with the target.

## command

flutter run --debug

## exception

ArgumentError: Invalid argument(s): Cannot find executable for null.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      runCommand (package:flutter_tools/src/base/process.dart:115)
#3      _IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:518)
<asynchronous suspension>
#4      ProtocolDiscovery._forwardPort (package:flutter_tools/src/protocol_discovery.dart:93)
<asynchronous suspension>
#5      ProtocolDiscovery._handleLine (package:flutter_tools/src/protocol_discovery.dart:82)
#6      _rootRunUnary (dart:async/zone.dart:1134)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#10     _DelayedData.perform (dart:async/stream_impl.dart:578)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.5.1 at /Users/hari/development/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPad • 4474fd3c94589784543185ceefc47173d59e2b5f • ios • iOS 9.3.5

! Doctor found issues in 1 category.
```

**Comment by hariprasadiit** [comment]
same problem even with recent `dev` channel

## exception

ArgumentError: Invalid argument(s): Cannot find executable for null.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:7)
#2      runCommand (package:flutter_tools/src/base/process.dart:115:25)
#3      _IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:547:23)
<asynchronous suspension>
#4      ProtocolDiscovery._forwardPort (package:flutter_tools/src/protocol_discovery.dart:89:54)
<asynchronous suspension>
#5      ProtocolDiscovery._handleLine (package:flutter_tools/src/protocol_discovery.dart:78:27)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.5.8 at /Users/hari/development/flutter
    • Framework revision e4b989bf3d (7 days ago), 2018-08-09 09:45:44 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPad • 4474fd3c94589784543185ceefc47173d59e2b5f • ios • iOS 9.3.5

• No issues found!
```

**Comment by DanTup** [comment]
It looks like `iproxy` may be missing. What happens if you run `iproxy` and `which iproxy` from the terminal?

I think `iproxy` is supposed to come from `libimobiledevice` which you probably installs with `brew`. Can you post the output of `brew list`?

**Comment by hariprasadiit** [comment]
@DanTup indeed it was `iproxy` issue. it doesn't seem to come from `libimobiledevice` now. i tried reinstalling multiple times. using `locate` i found it installed in `/usr/local/Cellar/usbmuxd/1.0.10_1/bin/iproxy`. for some odd reason, `brew` didn't symlink it. 
after symlink the has been resolved.

thanks for the help.

**Comment by DanTup** [comment]
Ah, I wasn't sure exactly where it came from but I found other issues suggesting it was `libimobiledevice`.

Glad it's sorted. If this turns out not to be a one off (if you're reading this and have the same issue - please add a comment!) we may want to reopen and investigate.

**Comment by Atteprojects** [comment]
I am having this issue as well. how do I symlink it?[ if the solution above worked]

**Comment by Atteprojects** [comment]
this is my output for 'brew list'

autoconf                gettext                 libidn2                 libtasn1                libusb                  openssl                 python@2                usbmuxd
automake                ideviceinstaller        libimobiledevice        libtool                 libxml2                 pkg-config              readline                wget
gdbm                    ios-deploy              libplist                libunistring            libzip                  python                  sqlite                  xz

**Comment by thosakwe** [comment]
What fixed it for me was `brew link libimobiledevice`.

**Comment by miohtama** [comment]
I had the same issue with Flutter command-line tools and Visual Studio Code tools. 

You can get this error both through command line `flutter emulator --create flutteremu` or using *Flutter: Launch Emulator* in Visual Studio Code.

```
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for null.".
```

You get this error despite `flutter doctor` telling you that everything is in order.

There is a log file, which details the error [here](https://github.com/flutter/flutter/issues/20691).

If you dig deeper you fill find out that the following Android command line tool does not work:

```sh
avdmanager
```

```
No Java runtime present, requesting install.
```

Turns out that `avdmanager` is quite a tricky to get running on macOS, as it seems to be fall short on the default Android SDK installation.  You need to have an external `java` installed and then you need to make sure all environment variables are wired correctly. Plus pinning down a correct Java version was not that easy.

[I wrote a detailed instructions how to get this fixed on this StackOverflow answer](https://stackoverflow.com/questions/61036745/invalid-arguments-cannot-find-executable-for-null-when-emulated-android-on/61869002#61869002).

The correct bug fix would be that `flutter doctor` detects the condition when the user cannot run `avdmanager` and tells the user that this needs to be fixed.
