### ISSUE TITLE
Initial Demo application crashes on AndroidOne device.

### ISSUE THREAD

**Issue by ahmetaa** [flutter/flutter#2070]
### Steps to Reproduce
* Connected the device from USB, developer-debug mode is on.
* Run the demo application from "Getting Started with Flutter" page. I got the messages below:

```
Downloading android-arm artifacts from the cloud, one moment please...
Downloading https://storage.googleapis.com/mojo_infra/flutter/9e1e1fba5474b458458b65f1aa1d0d730af2705b/android-arm/artifacts.zip.
Building APK...
Signing the APK using the debug keystore.
Generated APK to build/app.apk.
Starting lib/main.dart on General Mobile 4G Dual...
Installing app.apk on device.
```
* Then I got the error message "Unfortunately my_app has stopped" on the device.

### Flutter Version

```
Flutter from https://github.com/flutter/flutter.git (on alpha)
flutter revision: 49c0ec3402a58b670d4eefb8ad500d330da59664 (4 days ago)
engine revision : 9e1e1fba5474b458458b65f1aa1d0d730af2705b
[✓] The Android toolchain is fully installed.
```
Model Number: General Mobile 4G Dual
Device Android version is 6.0.1 (Security Patch Level February 1/2016)

### Logs
```
Showing logs for Android:
[Android] --------- beginning of main
[Android] --------- beginning of system
[Android] --------- beginning of crash
[Android] F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20656 (gpu_thread)
[Android] F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[Android] F/DEBUG   : Build fingerprint: 'google/gm4g/gm4g_sprout:6.0.1/MMB29Q/2480792:user/release-keys'
[Android] F/DEBUG   : Revision: '0'
[Android] F/DEBUG   : ABI: 'arm'
[Android] F/DEBUG   : pid: 20641, tid: 20656, name: gpu_thread  >>> com.example.my_app <<<
[Android] F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
[Android] F/DEBUG   :     r0 00008893  r1 ac802b7c  r2 00000000  r3 ac8036ec
[Android] F/DEBUG   :     r4 b8e47aac  r5 a3e7c164  r6 b8db6610  r7 00001000
[Android] F/DEBUG   :     r8 00000006  r9 a3e7c158  sl b8e47a30  fp b8daa610
[Android] F/DEBUG   :     ip b688c358  sp a3268288  lr a3ab5e1d  pc 00000000  cpsr a0000010
[Android] F/DEBUG   : 
[Android] F/DEBUG   : backtrace:
[Android] F/DEBUG   :     #00 pc 00000000  <unknown>
[Android] F/DEBUG   :     #01 pc 00251e19  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #02 pc 002196bb  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #03 pc 002196ed  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #04 pc 00232af3  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #05 pc 00235d8d  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #06 pc 00205f4d  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #07 pc 002056bf  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #08 pc 00201ca9  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #09 pc 00201f09  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #10 pc 000ae363  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #11 pc 002e3d65  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #12 pc 002b347f  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #13 pc 002b300b  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #14 pc 002b2aa9  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #15 pc 002b2c8b  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #16 pc 002b2cdb  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #17 pc 000d8435  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #18 pc 000d93c5  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #19 pc 000d9629  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #20 pc 000d970f  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #21 pc 000be46d  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #22 pc 000baa51  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #23 pc 000c4e15  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #24 pc 000c42fd  /data/app/com.example.my_app-1/lib/arm/libsky_shell.so
[Android] F/DEBUG   :     #25 pc 0004074b  /system/lib/libc.so (__pthread_start(void*)+30)
[Android] F/DEBUG   :     #26 pc 00018091  /system/lib/libc.so (__start_thread+6)
[Android] W/ActivityManager:   Force finishing activity com.example.my_app/org.domokit.sky.shell.SkyActivity
[Android] F/DEBUG   : 
[Android] F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_01
[Android] W/ActivityManager: Exception thrown during pause
[Android] W/ActivityManager: android.os.DeadObjectException
[Android] W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
[Android] W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
[Android] W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
[Android] W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
[Android] W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

```

**Comment by ahmetaa** [comment]
I plugged a Nexus-5 device for the same configuration and it worked.

**Comment by williamgueiros** [comment]
I have the same problems with s5 but I disable and enable , develop mode and it's working again

**Comment by ahmetaa** [comment]
@williamgueiros I tried turning debug mode on-off, unplugging etc but no luck yet.

**Comment by abarth** [comment]
Thanks for the report.  I have an AndroidOne device that I can test with locally.

**Comment by eseidelGoogle** [comment]
@yjbanov also has an AndroidOne he tests with.

**Comment by ahmetaa** [comment]
I installed Android N Beta and latest flutter, it works as expected now. Though I do not know if it was because of flutter changes or Andorid N.

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/*****/projects/flutter
    • Framework revision 646b5350d1 (8 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/*****/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_45-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.1.3

**Comment by abarth** [comment]
Thanks.
