### ISSUE TITLE
Updating deps for dart sdk is unclear

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#20700]
I am having a very difficult updating a package that I created yesterday.  This morning I updated to the newest version of flutter and I keep getting this error
```
$ flutter packages pub get
Resolving dependencies...
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because testplugin_example depends on testplugin from path which requires SDK version <2.0.0, version solving failed.
pub finished with exit code 1
```
But I don't know what I need to do to make this thing realize that such a constraint doesn't exist.  I did a `sudo grep -r '<2.0.0' .`  and the constraint wasn't found in any file in my plugin directory.   

I've tried a `flutter clean`, deleting the `pubspec.lock` from the main directory and example directory, nothing seems to work.

What's the solution here?

## Steps to Reproduce

in $FLUTTER_ROOT:
`git checkout 58e52cc177`
`flutter doctor -v`

in some other directory of your choice:
`flutter create -t plugin -i swift -a kotlin --description "A Flutter plugin" testplugin`
`cd testplugin`
`flutter packages get`

Everything is ok so far, now...
`git checkout master`
`flutter upgrade`

in directory you create plugin
`flutter packages get`

Now you get this 
`Because testplugin_example depends on testplugin from path which requires SDK version <2.0.0, version solving failed.`

## Logs

```
$ flutter packages get -v
[  +33 ms] executing: [/Users/KG/Developer/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/KG/Developer/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/KG/Developer/Flutter/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [/Users/KG/Developer/Flutter/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b5b55447a499012c90c1a357184b5163cd0dc77c
[        ] executing: [/Users/KG/Developer/Flutter/flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 hours ago
[   +1 ms] executing: [/Users/KG/Developer/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +43 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.8-64-gb5b55447a
[ +187 ms] Running "flutter packages get" in testplugin...
[   +5 ms] executing: [/Users/KG/Developer/Mine/testing_safe_to_delete_all_contents/testplugin/] /Users/KG/Developer/Flutter/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning --verbose get --no-precompile
[ +391 ms] Running "flutter packages get" in testplugin... (completed)
[  +76 ms] Running "flutter packages get" in example...
[        ] executing: [/Users/KG/Developer/Mine/testing_safe_to_delete_all_contents/testplugin/example/] /Users/KG/Developer/Flutter/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning --verbose get --no-precompile
[+1813 ms] The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
[   +1 ms] Because testplugin_example depends on testplugin from path which requires SDK version <2.0.0, version solving failed.
[  +26 ms] Running "flutter packages get" in example... (completed)
[  +11 ms] "flutter get" took 2,441ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:89:13)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

**Comment by KevinTheGray** [comment]
not sure how it always happens, but of course I found a solution 5 minutes after creating this issue.

the solution is in your plugins `pubspec.yaml`, _not the example's_, add 
```
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
```

check out something like, `https://github.com/theyakka/fluro/blob/master/pubspec.yaml` as an example.
