### ISSUE TITLE
Intermittent issues when running tests with coverage

### ISSUE THREAD

**Issue by v3rm0n** [flutter/flutter#20808]
## Steps to Reproduce

Not sure how to reproduce this, but our app has grown quite big and we can't run the tests with coverage anymore (works fine without coverage). We have about 7300 lines of code. The "Compilation failed" error happens in a different file every time we run tests. Any recommendations how to get to the root of this issue?

## Logs

https://gist.github.com/v3rm0n/e17a18a021959f5f651fa7a215baaa2d

```
Running "flutter packages get" in project...
! dart_config 0.5.0 from git git@github.com:v3rm0n/dart_config.git at b88bcf
Analyzing project...
No issues found! (ran in 19.3s)
```

Running on CircleCI so Android Studio is missing
```
Downloading Dart SDK from Flutter engine 03f8ba51e3d4d2f4de7875fe1607d781bf0a7409...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 76.9M  100 76.9M    0     0   125M      0 --:--:-- --:--:-- --:--:--  125M
Building flutter tool...
The --packages-dir flag is no longer used and does nothing.
Resolving dependencies... (1.0s)(1.1s)(1.2s)(1.3s)(1.4s)(1.5s)(1.6s)(1.7s)(1.8s)(1.9s)(2.0s)(2.1s)(2.2s)(2.3s)(2.4s)(2.5s)(2.6s)(2.7s)(2.8s)(2.9s)(3.0s)(3.1s)(3.2s)(3.3s)(3.4s)(3.5s)(3.6s)(3.7s)(3.8s)(3.9s)(4.1s)
> analyzer 0.32.4 (was 0.31.2-alpha.2)
> archive 2.0.2 (was 2.0.0) (2.0.3 available)
> args 1.5.0 (was 1.4.3)
> async 2.0.8 (was 2.0.7)
> boolean_selector 1.0.4 (was 1.0.3)
> charcode 1.1.2 (was 1.1.1)
> cli_util 0.1.3+2 (was 0.1.3)
> collection 1.14.11 (was 1.14.6)
+ completion 0.2.1+1
> convert 2.0.2 (was 2.0.1)
> coverage 0.12.2 (was 0.11.0)
> crypto 2.0.6 (was 2.0.5)
> csslib 0.14.5 (was 0.14.4)
+ dart2_constant 1.0.2+dart2
> file 5.0.4 (was 5.0.1)
> file_testing 2.0.3 (was 2.0.0)
> front_end 0.1.4 (was 0.1.0-alpha.12)
> glob 1.1.7 (was 1.1.5)
> html 0.13.3+3 (was 0.13.3+1)
> http 0.11.3+17 (was 0.11.3+16)
  http_multi_server 2.0.5
> http_parser 3.1.3 (was 3.1.2)
> intl 0.15.7 (was 0.15.6)
> io 0.3.3 (was 0.3.2+1)
> js 0.6.1+1 (was 0.6.1)
> json_rpc_2 2.0.9 (was 2.0.8)
> json_schema 1.0.10 (was 1.0.8) (2.0.0-RC2 available)
> kernel 0.3.4 (was 0.3.0-alpha.12)
> linter 0.1.59 (was 0.1.53)
> logging 0.11.3+2 (was 0.11.3+1)
> matcher 0.12.3+1 (was 0.12.2) (0.12.4 available)
> meta 1.1.6 (was 1.1.5)
> mime 0.9.6+2 (was 0.9.6+1)
> mockito 3.0.0 (was 3.0.0-beta)
> multi_server_socket 1.0.2 (was 1.0.1)
> mustache 1.0.2 (was 1.0.1)
> node_preamble 1.4.4 (was 1.4.2)
> package_config 1.0.5 (was 1.0.3)
> package_resolver 1.0.4 (was 1.0.3)
> path 1.6.2 (was 1.6.1)
> petitparser 1.7.7 (was 1.7.6) (2.0.0 available)
> platform 2.2.0 (was 2.1.2)
> plugin 0.2.0+3 (was 0.2.0+2)
> pool 1.3.6 (was 1.3.5)
> process 3.0.5 (was 3.0.1)
> pub_semver 1.4.2 (was 1.4.1)
> quiver 2.0.0+1 (was 0.29.0+1)
> shelf 0.7.3+3 (was 0.7.3+1)
> shelf_packages_handler 1.0.4 (was 1.0.3)
> shelf_static 0.2.8 (was 0.2.7+1)
> shelf_web_socket 0.2.2+4 (was 0.2.2+2)
> source_map_stack_trace 1.1.5 (was 1.1.4)
> source_maps 0.10.7 (was 0.10.5)
> source_span 1.4.1 (was 1.4.0)
> stack_trace 1.9.3 (was 1.9.2)
> stream_channel 1.6.8 (was 1.6.7+1)
> string_scanner 1.0.4 (was 1.0.2)
> term_glyph 1.0.1 (was 1.0.0)
> test 1.3.0 (was 0.12.41)
> typed_data 1.1.6 (was 1.1.5)
> usage 3.4.1 (was 3.4.0)
> utf 0.9.0+5 (was 0.9.0+4)
> vm_service_client 0.2.6 (was 0.2.4+3)
> watcher 0.9.7+10 (was 0.9.7+8)
> web_socket_channel 1.0.9 (was 1.0.8)
> xml 3.0.1 (was 3.0.0) (3.2.0 available)
> yaml 2.1.15 (was 2.1.14)
Downloading mockito 3.0.0...
Downloading file_testing 2.0.3...
Downloading collection 1.14.11...
Downloading yaml 2.1.15...
Downloading logging 0.11.3+2...
Downloading shelf_packages_handler 1.0.4...
Downloading json_schema 1.0.10...
Downloading archive 2.0.2...
Downloading convert 2.0.2...
Downloading plugin 0.2.0+3...
Downloading stack_trace 1.9.3...
Downloading usage 3.4.1...
Downloading csslib 0.14.5...
Downloading crypto 2.0.6...
Downloading typed_data 1.1.6...
Downloading args 1.5.0...
Downloading package_resolver 1.0.4...
Downloading front_end 0.1.4...
Downloading linter 0.1.59...
Downloading source_maps 0.10.7...
Downloading vm_service_client 0.2.6...
Downloading js 0.6.1+1...
Downloading string_scanner 1.0.4...
Downloading shelf 0.7.3+3...
Downloading source_span 1.4.1...
Downloading process 3.0.5...
Downloading completion 0.2.1+1...
Downloading utf 0.9.0+5...
Downloading multi_server_socket 1.0.2...
Downloading stream_channel 1.6.8...
Downloading term_glyph 1.0.1...
Downloading shelf_web_socket 0.2.2+4...
Downloading json_rpc_2 2.0.9...
Downloading io 0.3.3...
Downloading xml 3.0.1...
Downloading http 0.11.3+17...
Downloading charcode 1.1.2...
Downloading async 2.0.8...
Downloading test 1.3.0...
Downloading coverage 0.12.2...
Downloading node_preamble 1.4.4...
Downloading analyzer 0.32.4...
Downloading http_parser 3.1.3...
Downloading path 1.6.2...
Downloading intl 0.15.7...
Downloading cli_util 0.1.3+2...
Downloading pub_semver 1.4.2...
Downloading glob 1.1.7...
Downloading platform 2.2.0...
Downloading pool 1.3.6...
Downloading kernel 0.3.4...
Downloading html 0.13.3+3...
Downloading package_config 1.0.5...
Downloading quiver 2.0.0+1...
Downloading watcher 0.9.7+10...
Downloading mime 0.9.6+2...
Downloading dart2_constant 1.0.2+dart2...
Downloading source_map_stack_trace 1.1.5...
Downloading boolean_selector 1.0.4...
Downloading matcher 0.12.3+1...
Downloading meta 1.1.6...
Downloading web_socket_channel 1.0.9...
Downloading petitparser 1.7.7...
Downloading mustache 1.0.2...
Downloading file 5.0.4...
Downloading shelf_static 0.2.8...
Changed 66 dependencies!
Precompiling executables... (1.0s)(1.1s)(1.2s)(1.3s)(1.4s)(1.5s)(1.6s)(1.7s)(1.8s)(1.9s)(2.0s)(2.1s)(2.2s)(2.3s)(2.4s)(2.5s)(2.6s)(2.7s)(2.8s)(2.9s)(3.0s)(3.1s)(3.2s)(3.3s)(3.4s)(3.5s)(3.6s)(3.7s)(3.8s)(3.9s)(4.0s)(4.1s)(4.2s)(4.3s)
Precompiled json_schema:gensamples.
Precompiled completion:shell_completion_generator.
Precompiled json_schema:schemadot.
Precompiled kernel:size_breakdown.
Precompiled csslib:css.
Precompiled kernel:split.
Precompiled archive:tar.
Precompiled kernel:dump.
Precompiled kernel:count_breakdown.
Precompiled kernel:type_check.
Precompiled coverage:run_and_collect.
Precompiled kernel:eval.
Precompiled kernel:transform.
Precompiled coverage:format_coverage.
Precompiled coverage:collect_coverage.
Precompiled linter:linter.
Precompiled test:test.
Downloading package sky_engine...
Downloading common tools...
Downloading linux-x64 tools...
Downloading android-arm-profile/linux-x64 tools...
Downloading android-arm-release/linux-x64 tools...
Downloading android-arm64-profile/linux-x64 tools...
Downloading android-arm64-release/linux-x64 tools...
Downloading android-arm-dynamic-profile/linux-x64 tools...
Downloading android-arm-dynamic-release/linux-x64 tools...
Downloading android-arm64-dynamic-profile/linux-x64 tools...
Downloading android-arm64-dynamic-release/linux-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
Downloading android-arm64 tools...
Downloading android-arm64-profile tools...
Downloading android-arm64-release tools...
Downloading android-arm-dynamic-profile tools...
Downloading android-arm-dynamic-release tools...
Downloading android-arm64-dynamic-profile tools...
Downloading android-arm64-dynamic-release tools...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.9-pre.84, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[✗] Android Studio (not installed)
[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

Exception output part from the Gist above

```
05:23 +296 -1: /home/cirrus/project/test/src/tracker/tracker_test.dart: Tracker Bloc tracks logged in user with user id as distinct id                                                                 [+24027 ms] test 56: error caught during test; reporting to console
[        ] unhandled error during test:
           /home/cirrus/project/test/src/wallet/wallet_api_test.dart
           Exception: Timed out while collecting coverage.
           #0      CoverageCollector.collectCoverage.<anonymous closure> (package:flutter_tools/src/test/coverage_collector.dart:64:13)
           #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
           #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
           #3      _rootRun (dart:async/zone.dart:1120:38)
           #4      _CustomZone.run (dart:async/zone.dart:1021:19)
           #5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:731:33)
           #6      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
           #7      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
           #8      _rootRun (dart:async/zone.dart:1120:38)
           #9      _CustomZone.run (dart:async/zone.dart:1021:19)
           #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
           #13     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
           #14     _rootRun (dart:async/zone.dart:1124:13)
           #15     _CustomZone.run (dart:async/zone.dart:1021:19)
           #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
           #17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
           #18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
           #19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
           #20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
```

**Comment by zoechi** [comment]
Does your Flutter version contain #20506 already? (just a guess this might be related)

**Comment by v3rm0n** [comment]
From the logs I see that:
```
[        ] executing: [/home/cirrus/sdks/flutter/] git log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3ae5ecebeac362dfc4e96cad038a74559798d517
```
which is the current latest commit in master, so yes.

**Comment by Hixie** [comment]
If you manually hack the timeouts to be longer, does it complete?

**Comment by v3rm0n** [comment]
Which timeout would affect it? Also this exception that was picked out from my stacktrace was not what I meant originally, I was more worried about this actually being the cause of the other one
```
01:58 +210 -1: loading /home/cirrus/project/test/src/ui/paper_test.dart [E]                                                                                                                            
  Failed to load "/home/cirrus/project/test/src/ui/paper_test.dart":
  Compilation failed
  Test: /home/cirrus/project/test/src/ui/paper_test.dart
  Shell: /home/cirrus/sdks/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
```

**Comment by v3rm0n** [comment]
Tried running locally with coverage as well and the tests passed. Looked into it a bit more and found that the difference was concurrency. On my machine it is 2, but on CI it is 30.
If I specified concurrency as 2 on CI as well, the tests passed. Race condition somewhere?

**Comment by Hixie** [comment]
Ah, interesting. We recently changed it to use N-2 CPUs always (where N is the number of processors on the machine). We used to always use 2 whenever doing coverage, and N/2 normally.

Coverage takes a lot of CPU, so it's possible that we're oversubscribing the CI. Are you using Travis?

**Comment by v3rm0n** [comment]
Using CircleCI, with 2 virtual CPUs, lspci says:
```
cirrus@fdf7daaf75ef:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:              4
CPU MHz:               2793.376
BogoMIPS:              5586.75
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm kaiser fsgsbase smep erms xsaveopt
```

**Comment by Hixie** [comment]
Well if the system is lying about the number of CPUs, that's definitely gonna be an issue...

**Comment by Hixie** [comment]
@v3rm0n is manually specifying `-j` to `flutter run` acceptable? I'm not sure what we should do if the report of number of CPUs is inaccurate. That seems like a bug with CircleCI, not Flutter.

**Comment by v3rm0n** [comment]
Yes, works for me.

**Comment by zoechi** [comment]
Sounds like this is solved.

**Comment by bibinmpanicker-deriv** [comment]
> Which timeout would affect it? Also this exception that was picked out from my stacktrace was not what I meant originally, I was more worried about this actually being the cause of the other one
> 
> ```
> 01:58 +210 -1: loading /home/cirrus/project/test/src/ui/paper_test.dart [E]                                                                                                                            
>   Failed to load "/home/cirrus/project/test/src/ui/paper_test.dart":
>   Compilation failed
>   Test: /home/cirrus/project/test/src/ui/paper_test.dart
>   Shell: /home/cirrus/sdks/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester
> ```

@v3rm0n May I know how you fixed this issue ?
