### ISSUE TITLE
Failed assertion in flutter run --machine

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#20812]
If you run `flutter run --machine` with assertions enabled, you get a crash. I'm testing on macOS using the `examples/hello_world` project. Happens with iOS simulator and flutter-tester at least:

```
dantup-macbookpro:hello_world dantup$ FLUTTER_TOOL_ARGS=--enable-asserts flutter run --machine 
[{"event":"daemon.connected","params":{"version":"0.4.1","pid":40801}}]
[{"event":"app.start","params":{"appId":"72f4edf8-abbb-4e78-83b4-00caa2892206","deviceId":"735F9F08-FF94-4E03-BB0E-FE8FD114610F","directory":"/Users/dantup/Dev/Google/flutter/examples/hello_world","supportsRestart":true}}]
Launching lib/main.dart on iPhone X in debug mode...
[{"event":"app.progress","params":{"appId":"72f4edf8-abbb-4e78-83b4-00caa2892206","id":"0","progressId":null,"message":"Starting Xcode build..."}}]
Unhandled exception:
'package:flutter_tools/src/base/logger.dart': Failed assertion: line 330 pos 12: '_isStarted': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:330:12)
#3      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:335:30)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:347:29)
<asynchronous suspension>
#5      IOSSimulator._buildAndInstallApplicationBundle (package:flutter_tools/src/ios/simulators.dart:367:48)
<asynchronous suspension>
#6      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:353:14)
<asynchronous suspension>
#7      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:283:15)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:292:54)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
dantup-macbookpro:hello_world dantup$ 
```

**Comment by DanTup** [comment]
The stack for flutter-tester is slightly different:

```
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:322:12)
#3      FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:410:17)
<asynchronous suspension>
#4      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:317:40)
\<asynchronous suspension>
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:183:36)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:269:12)
<asynchronous suspension>
#7      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:381:62)
#8      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:432:26)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#15     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:781:20)
#16     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:430:15)
<asynchronous suspension>
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:378:12)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:296:38)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#26     Future._complete (dart:async/future_impl.dart:476:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#29     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#30     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#37     Future._complete (dart:async/future_impl.dart:476:7)
#38     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#39     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```
