### ISSUE TITLE
Flutter test driver can not instantiate Future with 'delayed()' factory

### ISSUE THREAD

**Issue by nkpodolyan** [flutter/flutter#20863]
I am not able to use `Future.delayed()` factory, to pause test script execution in integration tests.

Is there a way to make test drive tests wait for a certain amount of time?

## Integration test class:

```
import 'dart:async';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('screen test', () {
    FlutterDriver driver;

    setUpAll(() async {
      // Connects to the app
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null) {
        // Closes the connection
        driver.close();
      }
    });

    test('test screen', () async {
      await (Future.delayed(const Duration(seconds: 2)));

      expect(await driver.getText(find.text("Screen text")), "Screen text");
    });
  });
}
```

## Logs

```
............................................................................................................
[ +599 ms] [info ] FlutterDriver: Connected to Flutter application.
[   +4 ms] 00:00 +0: screen test screen test
[   +9 ms] 00:00 +0 -1: screen test screen test [E]
[   +5 ms]   NoSuchMethodError: No static method 'delayed' declared in class 'Future'.
[        ]   Receiver: Future
[        ]   Tried calling: delayed(Instance of 'Duration')
[  +68 ms]   dart:core-patch/dart:core/errors_patch.dart 203               NoSuchMethodError._throwNew
[        ]   test_driver/lock_screen_test.dart 22:21                       main.<fn>.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/future_impl.dart 22                                _Completer.completeError
[        ]   test_driver/lock_screen_test.dart                             main.<fn>.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/schedule_microtask.dart 147                        scheduleMicrotask
[        ]   dart:async/future.dart 198                                    new Future.microtask
[        ]   test_driver/lock_screen_test.dart 21:34                       main.<fn>.<fn>
[        ]   package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
[        ]   dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
[        ]   package:test/src/backend/declarer.dart 159:70                 Declarer.test.<fn>.<fn>.<fn>
[        ]   package:test/src/backend/invoker.dart 249:15                  Invoker.waitForOutstandingCallbacks.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/schedule_microtask.dart 147                        scheduleMicrotask
[        ]   dart:async/future.dart 198                                    new Future.microtask
[        ]   package:test/src/backend/invoker.dart 246:23                  Invoker.waitForOutstandingCallbacks.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 1501                                     runZoned
[        ]   package:test/src/backend/invoker.dart 246:5                   Invoker.waitForOutstandingCallbacks
[        ]   package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 1501                                     runZoned
[        ]   package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/schedule_microtask.dart 147                        scheduleMicrotask
[        ]   dart:async/future.dart 198                                    new Future.microtask
[        ]   package:test/src/backend/declarer.dart 143:66                 Declarer.test.<fn>
[        ]   package:test/src/backend/invoker.dart 403:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/schedule_microtask.dart 147                        scheduleMicrotask
[        ]   dart:async/future.dart 198                                    new Future.microtask
[        ]   package:test/src/backend/invoker.dart 402:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
[        ]   dart:async/future.dart 174                                    new Future.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1122                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 925                                      _CustomZone.runGuarded
[        ]   dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
[        ]   dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
[        ]   dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
[        ]   dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
[        ]   dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/timer.dart 52                                      new Timer
[        ]   dart:async/timer.dart 87                                      Timer.run
[        ]   dart:async/future.dart 172                                    new Future
[        ]   package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1047                                     _CustomZone.registerCallback
[        ]   dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
[        ]   dart:async/schedule_microtask.dart 147                        scheduleMicrotask
[        ]   dart:async/future.dart 198                                    new Future.microtask
[        ]   package:test/src/backend/invoker.dart 389:27                  Invoker._onRun.<fn>.<fn>.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 1501                                     runZoned
[        ]   package:test/src/backend/invoker.dart 389:9                   Invoker._onRun.<fn>.<fn>
[        ]   package:test/src/backend/invoker.dart 443:15                  Invoker._guardIfGuarded
[        ]   package:test/src/backend/invoker.dart 388:7                   Invoker._onRun.<fn>
[        ]   package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 1501                                     runZoned
[        ]   package:stack_trace/src/chain.dart 99:12                      Chain.capture
[        ]   package:test/src/backend/invoker.dart 387:11                  Invoker._onRun
[        ]   package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
[        ]   package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
[        ]   dart:async/future.dart 200                                    new Future.microtask.<fn>
[        ]   dart:async/zone.dart 1122                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 925                                      _CustomZone.runGuarded
[        ]   dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/zone.dart 1126                                     _rootRun
[        ]   dart:async/zone.dart 1023                                     _CustomZone.run
[        ]   dart:async/zone.dart 925                                      _CustomZone.runGuarded
[        ]   dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/schedule_microtask.dart 41                         _microtaskLoop
[        ]   dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
[        ]   dart:isolate-patch/dart:isolate/timer_impl.dart 391           _Timer._runTimers
[        ]   dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
[        ]   dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
[  +13 ms] 00:01 +0 -1: lock screen test (tearDownAll)
[  +42 ms] 00:01 +0 -1: Some tests failed.
[   +1 ms] Unhandled exception:
[        ] Dummy exception to set exit code.
[        ] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)
[        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] #3      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
[        ] #4      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
[        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
[  +24 ms] Stopping application instance.
[        ] Stopping application.

```

## Analyser output
```
warning • The asset res/image/ does not exist • pubspec.yaml:48:7

```

## Flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-UA)
    • Flutter version 0.5.1 at /Users/mykola/Development/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/mykola/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
