### ISSUE TITLE
FlutterTester.app is failing for me (seems to be running Dart 1.0)

### ISSUE THREAD

**Issue by markmclaren2** [flutter/flutter#20864]
On Mac I'm trying to build the engine and run FlutterTester.app, but it seems to be running Dart 1.0 and so it fails with the newer Flutter apps which use Dart 2.0.

Steps to reproduce:

**Step 1: Build the engine on Mac as [described here](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md)**
`./flutter/tools/gn --unoptimized` 
then 
`ninja -C out/host_debug_unopt`

**2. Create a new flutter app:**
`flutter --local-engine=host_debug_unopt create custom3`

**3. Create the flutter_assets directory:**
`flutter --local-engine=host_debug_unopt build bundle`

**4. Run FlutterTester like this from out/host_debug_unopt directory (replace mark with your username)**
`./FlutterTester.app/Contents/MacOS/FlutterTester --dart-main=/Users/mark/dev/custom3/lib/main.dart --flutter-assets-dir=/Users/mark/dev/custom3/build/flutter_assets --packages=/Users/mark/dev/custom3/.packages`

Here's the error output:

```
'package:flutter/src/services/system_channels.dart': error: line 30 pos 43: initializer is not a valid compile-time constant
  static const MethodChannel navigation = MethodChannel(
                                          ^

#0      new BindingBase (package:flutter/src/foundation/binding.dart:53:5)
#1      new BindingBase&GestureBinding (package:flutter/src/gestures/binding.dart:19:1)
#2      new BindingBase&GestureBinding&ServicesBinding (package:flutter/src/services/binding.dart:19:1)
#3      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/scheduler/binding.dart:189:1)
#4      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/painting/binding.dart:15:1)
#5      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart:24:1)
#6      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart:241:1)
#7      new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart:920:1)
#8      WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:935:11)
#9      runApp (package:flutter/src/widgets/binding.dart:727:25)
#10     main (/Users/mark/dev/custom3/lib/main.dart:3:16)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:286)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:169)

```

Here is my Flutter doctor output:

```
[✓] Flutter (Channel master, v0.5.9-pre.84, on Mac OS X 10.13.6 17G65, locale en-AU)
    • Flutter version 0.5.9-pre.84 at /Users/mark/dev/flutter
    • Framework revision 3ae5ecebea (2 days ago), 2018-08-19 06:25:00 -0400
    • Engine revision 03f8ba51e3
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mark/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by mklim** [comment]
Thanks for the bug report! `FlutterTester.app` was removed in flutter/engine#6314. Please open a new issue if you're still seeing issues with the `flutter_tester` binary.
