### ISSUE TITLE
Using double.infinity in  app wide theme causes text selection toolbar to not behave properly on Android

### ISSUE THREAD

**Issue by thenhawke** [flutter/flutter#20869]
I was trying to get all my buttons to be max width across the entire application by setting the button theme `minWidth` to `double.infinity`. It works as expected but when you select any text in a `TextFormField`, the application crashes. 

## Steps to Reproduce
This is the smallest application I can create to reproduce the crash.
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      theme: ThemeData(
        buttonTheme: ButtonThemeData(
          minWidth: double.infinity,
        ),
      ),
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
           child: TextFormField(),
        ),
      ),
    );
  }
}
```

## Logs

```
I/flutter ( 9631): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9631): The following assertion was thrown during performLayout():
I/flutter ( 9631): BoxConstraints forces an infinite width.
I/flutter ( 9631): These invalid constraints were provided to RenderClipPath's layout() function by the following
I/flutter ( 9631): function, which probably computed the invalid constraints in question:
I/flutter ( 9631):   RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 9631): The offending constraints were:
I/flutter ( 9631):   BoxConstraints(w=Infinity, 36.0<=h<=44.0)
I/flutter ( 9631):
I/flutter ( 9631): When the exception was thrown, this was the stack:
I/flutter ( 9631): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:468:9)
I/flutter ( 9631): #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:509:21)
I/flutter ( 9631): #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:515:6)
I/flutter ( 9631): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1485:24)
I/flutter ( 9631): #4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 9631): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9631): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 9631): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 9631): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9631): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9631): #15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter ( 9631): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #17     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1097:13)
I/flutter ( 9631): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #19     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 9631): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9631): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9631): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9631): #25     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 9631): #26     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 9631): #27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 9631): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 9631): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 9631): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9631): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9631): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9631): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9631): #34     _invoke (dart:ui/hooks.dart:120:13)
I/flutter ( 9631): #35     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter ( 9631):
I/flutter ( 9631): The following RenderObject was being processed when the exception was fired:
I/flutter ( 9631):   RenderConstrainedBox#35682 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631):   creator: ConstrainedBox ← Semantics ← RawMaterialButton ← FlatButton ← Row ← ConstrainedBox ←
I/flutter ( 9631):   Container ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#0c72b ink
I/flutter ( 9631):   renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
I/flutter ( 9631):   parentData: <none> (can use size)
I/flutter ( 9631):   constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=44.0)
I/flutter ( 9631):   size: MISSING
I/flutter ( 9631):   additionalConstraints: BoxConstraints(w=Infinity, 36.0<=h<=Infinity)
I/flutter ( 9631): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 9631):   RenderClipPath#1b22b NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631):     RenderCustomPaint#33d94 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631):       _RenderInkFeatures#8323d NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631):         RenderSemanticsGestureHandler#eb2d2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631):           RenderPointerListener#3ccdd NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9631): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#35682 relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#30e6a relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderFlex#94091 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#c3bda relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#d079a relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderPhysicalModel#993b9 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: RenderBox was not laid out: RenderPhysicalModel#993b9 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 9631): Another exception was thrown: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 1570 pos 12: 'hasSize': is not true.
Application finished.
```

```
flutter analyze
Analyzing test_broken_select...
No issues found! (ran in 2.6s)
```

```
flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-CA)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\thenhawke\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\thenhawke\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • PH 1 • PM1LHMA781404531 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
Still get the exception
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by TahaTesser** [comment]
Testing on latest `dev` using the code sample , doesn't crash the app or produce any exception in debug mode but on Android, toolbar isn't shown when selecting on text but shown on iOS

![flutter_05](https://user-images.githubusercontent.com/48603081/79992161-c9af6300-84d0-11ea-9fa8-a644bc63a998.png)

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-04-22 at 19 34 08](https://user-images.githubusercontent.com/48603081/79992261-dfbd2380-84d0-11ea-9a7f-8d9788718878.png)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Unable to replicate after selecting the text and selection toolbar also shows up properly while selecting text.

<img width="545" alt="Screenshot 2020-12-30 at 6 45 28 PM" src="https://user-images.githubusercontent.com/67046386/103353688-7665c980-4acf-11eb-8219-23c5c810de98.png">

```
W/IInputConnectionWrapper(22961): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
I/zygote  (22961): Do full code cache collection, code=125KB, data=111KB
I/zygote  (22961): After code cache collection, code=110KB, data=75KB
W/IInputConnectionWrapper(22961): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/libEGL  (22961): EGLNativeWindowType 0xcb586008 disconnect failed
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper(22961): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(22961): getTextBeforeCursor on inactive InputConnection
W/libEGL  (22961): EGLNativeWindowType 0xd024a808 disconnect failed
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.137 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8f5d0371af (4 days ago), 2020-12-26 11:07:36 +0330
    • Engine revision f5364860ab
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.



```

</details>

Closing this as fixed.
