### ISSUE TITLE
Getting cookies from HttpClientResponse throws

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#20898]
RangeError (index): Invalid value: Valid value range is empty: 0
```
I/flutter (26221): #1      _Cookie._validate (dart:_http/http_headers.dart:989:14)
I/flutter (26221): #2      _Cookie._parseSetCookieValue (dart:_http/http_headers.dart:933:5)
I/flutter (26221): #3      new _Cookie.fromSetCookieValue (dart:_http/http_headers.dart:849:5)
I/flutter (26221): #4      new Cookie.fromSetCookieValue (dart:_http:1112:16)
I/flutter (26221): #5      _HttpClientResponse.cookies.<anonymous closure> (dart:_http/http_impl.dart:317:26)
I/flutter (26221): #6      List.forEach (dart:core/runtime/libgrowable_array.dart:275:8)
I/flutter (26221): #7      _HttpClientResponse.cookies (dart:_http/http_impl.dart:316:14)
```

**Comment by zoechi** [comment]
This issue should probably be better reported in https://github.com/dart-lang/sdk/issues
