### ISSUE TITLE
TextPainter bidi handling may not be correct.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#20891]
Discussed here: https://github.com/flutter/flutter/pull/20676#pullrequestreview-147871296

Given the following string:

`hello world <RLE> [BOY] HOW DO you DO [SIR] <PDF> good bye`

Written in Flutter as:

```dart
TextSpan(text: 'hello world ${Unicode.RLE}${Unicode.RLO}BOY HOW'
' DO${Unicode.PDF} you ${Unicode.RLO}DO SIR ${Unicode.PDF}${Unicode.PDF}good bye')
``` 

Should produce the visual text:

`hello world RIS OD you OD WOH YOB good bye`

Instead this currently produces:

`hello world OD WHO YOB you RIS OD good bye`.

cc @Hixie

**Comment by jason-simmons** [comment]
This is working as expected on master.

```
new Text('hello world ${Unicode.RLE}${Unicode.RLO}BOY HOW'
         ' DO${Unicode.PDF} you ${Unicode.RLO}DO SIR ${Unicode.PDF}${Unicode.PDF}good bye')
```

renders as

`hello world  RIS OD you OD WOH YOBgood bye`

In your setup, is the text being wrapped across multiple lines?

If there is a line break midway through the text, then the `OD WOH YOB` span would appear on the first line and `RIS OD` would appear on the second line.

**Comment by zoechi** [comment]
This works as explained by @jason-simmons.

![image](https://user-images.githubusercontent.com/405837/49739491-4baf3b00-fc92-11e8-8d04-891184bf4d69.png)


I assume this can be closed then.

**Comment by Piinks** [comment]
Re-opening as this is still presenting in a skipped test.
Test:
https://github.com/flutter/flutter/blob/8ed8b06ac5a1028e689d87592543880882a516da/packages/flutter/test/widgets/text_test.dart#L485

Result:
```
00:27 +123 -1: /tmp/flutter sdk/packages/flutter/test/widgets/text_test.dart: recognizers split semantic node - bidi                                                                                   
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: semantics node matching:
          TestSemantics(
            id: 0,
            rect: Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0),
            elevation: 0.0,
            thickness: 0.0,
            children: <TestSemantics>[
              TestSemantics(
                rect: Rect.fromLTRB(0.0, 0.0, 800.0, 600.0),
                transform:
                  [0] 3.0,0.0,0.0,0.0
                  [1] 0.0,3.0,0.0,0.0
                  [2] 0.0,0.0,1.0,0.0
                  [3] 0.0,0.0,0.0,1.0,
                children: <TestSemantics>[
                  TestSemantics(
                    label: 'hello world ',
                    textDirection: TextDirection.ltr,
                    rect: Rect.fromLTRB(-4.0, -4.0, 480.0, 18.0),
                    children: <TestSemantics>[
                    ],
                  ),
                  TestSemantics(
                    flags: <SemanticsFlag>[SemanticsFlag.isLink],
                    actions: <SemanticsAction>[SemanticsAction.tap],
                    label: 'RIS',
                    textDirection: TextDirection.rtl,
                    rect: Rect.fromLTRB(150.0, -4.0, 200.0, 18.0),
                    children: <TestSemantics>[
                    ],
                  ),
                  TestSemantics(
                    label: ' OD you OD WOH ',
                    textDirection: TextDirection.rtl,
                    rect: Rect.fromLTRB(192.0, -4.0, 424.0, 18.0),
                    children: <TestSemantics>[
                    ],
                  ),
                  TestSemantics(
                    actions: <SemanticsAction>[SemanticsAction.longPress],
                    label: 'YOB',
                    textDirection: TextDirection.rtl,
                    rect: Rect.fromLTRB(416.0, -4.0, 466.0, 18.0),
                    children: <TestSemantics>[
                    ],
                  ),
                  TestSemantics(
                    label: ' good bye',
                    textDirection: TextDirection.rtl,
                    rect: Rect.fromLTRB(472.0, -4.0, 606.0, 18.0),
                    children: <TestSemantics>[
                    ],
                  ),
                ],
              ),
            ],
          )
  Actual: SemanticsTester:<SemanticsTester for SemanticsNode#0(Rect.fromLTRB(0.0, 0.0, 2400.0,
1800.0))>
   Which: expected node id null to have label "hello world " but found label "hello world‫‮ ".
          Current SemanticsNode tree:
            SemanticsNode#0
             │ Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
             │
             └─SemanticsNode#1
               │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0) scaled by 3.0x
               │
               ├─SemanticsNode#2
               │   Rect.fromLTRB(-4.0, -4.0, 480.0, 18.0)
               │   label: "hello world‫‮ "
               │   textDirection: ltr
               │   sortKey: OrdinalSortKey#0e5a6(order: 0.0)
               │
               ├─SemanticsNode#3
               │   Rect.fromLTRB(416.0, -4.0, 466.0, 18.0)
               │   actions: longPress
               │   label: "BOY"
               │   textDirection: rtl
               │   sortKey: OrdinalSortKey#7acb5(order: 1.0)
               │
               ├─SemanticsNode#4
               │   Rect.fromLTRB(192.0, -4.0, 424.0, 18.0)
               │   label: " HOW DO‬ you ‮ DO "
               │   textDirection: rtl
               │   sortKey: OrdinalSortKey#b77ad(order: 2.0)
               │
               ├─SemanticsNode#5
               │   Rect.fromLTRB(150.0, -4.0, 200.0, 18.0)
               │   actions: tap
               │   flags: isLink
               │   label: "SIR"
               │   textDirection: rtl
               │   sortKey: OrdinalSortKey#f1b3d(order: 3.0)
               │
               └─SemanticsNode#6
                   Rect.fromLTRB(472.0, -4.0, 606.0, 18.0)
                   label: "‬‬ good bye"
                   textDirection: rtl
                   sortKey: OrdinalSortKey#f6e36(order: 4.0)
          The semantics tree would have matched the following configuration:
            TestSemantics.root(
              children: <TestSemantics>[
                TestSemantics(
                  id: 1,
                  children: <TestSemantics>[
                    TestSemantics(
                      id: 2,
                      label: 'hello world‫‮ ',
                      textDirection: TextDirection.ltr,
                    ),
                    TestSemantics(
                      id: 3,
                      actions: <SemanticsAction>[SemanticsAction.longPress],
                      label: 'BOY',
                      textDirection: TextDirection.rtl,
                    ),
                    TestSemantics(
                      id: 4,
                      label: ' HOW DO‬ you ‮ DO ',
                      textDirection: TextDirection.rtl,
                    ),
                    TestSemantics(
                      id: 5,
                      flags: <SemanticsFlag>[SemanticsFlag.isLink],
                      actions: <SemanticsAction>[SemanticsAction.tap],
                      label: 'SIR',
                      textDirection: TextDirection.rtl,
                    ),
                    TestSemantics(
                      id: 6,
                      label: '‬‬ good bye',
                      textDirection: TextDirection.rtl,
                    ),
                  ],
                ),
              ],
            )

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/widgets/text_test.dart:550:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/widgets/text_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:744:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:724:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1124:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1121:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#116    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#135    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#144    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#145    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///tmp/flutter%20sdk/packages/flutter/test/widgets/text_test.dart line 550
The test description was:
  recognizers split semantic node - bidi
════════════════════════════════════════════════════════════════════════════════════════════════════

00:27 +123 -2: /tmp/flutter sdk/packages/flutter/test/widgets/text_test.dart: recognizers split semantic node - bidi [E]                                                                               
  Test failed. See exception logs above.
  The test description was: recognizers split semantic node - bidi
```

flutter doctor
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.140, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.0-3.0.pre.140 at /Users/katelovett/github/flutter
    • Framework revision d8577ab260 (46 seconds ago), 2020-07-07 14:48:02 -0700
    • Engine revision f22ac9da9c
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 69aba23371)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • A8FFA716-A67B-4468-B92B-F2B61F2306A0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

• No issues found!
```

**Comment by Hixie** [comment]
Closing, see #62823 for updates.
