### ISSUE TITLE
LayoutBuilder does not work inside of CupertinoAlertDialog

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#20902]
Since grabbing the latest `master` branch: 

```
Flutter version 0.6.2-pre.15
Framework revision adafaee0e3
```

I am unable to use `LayoutBuilder` anywhere inside `CupertinoAlertDialog`.

```
The following assertion was thrown during performLayout():
LayoutBuilder does not support returning intrinsic dimensions.
Calculating the intrinsic dimensions would require running the layout callback speculatively, which might mutate the live render object tree.
```

This happens with all of my `LayoutBuilder`'s in `CupertinoAlertDialog`, which all were working fine before.

```
I/flutter (16217): When the exception was thrown, this was the stack:
I/flutter (16217): #0      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:167:9)
I/flutter (16217): #1      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics (package:flutter/src/widgets/layout_builder.dart:174:6)
I/flutter (16217): #2      _RenderLayoutBuilder.computeMaxIntrinsicHeight (package:flutter/src/widgets/layout_builder.dart:198:12)
I/flutter (16217): #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #6      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #11     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #12     RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:183:20)
I/flutter (16217): #13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #16     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #17     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:593:60)
I/flutter (16217): #18     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:500:39)
I/flutter (16217): #19     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:590:12)
I/flutter (16217): #20     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #21     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #22     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #23     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #25     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #26     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #27     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #28     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #30     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #31     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #32     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #33     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #35     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #36     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #37     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #38     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #39     RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:183:20)
I/flutter (16217): #40     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #41     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #42     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #43     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #44     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:593:60)
I/flutter (16217): #45     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:500:39)
I/flutter (16217): #46     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:590:12)
I/flutter (16217): #47     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #48     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #49     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #50     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #51     _RenderSingleChildViewport.computeMaxIntrinsicHeight (package:flutter/src/widgets/single_child_scroll_view.dart:465:20)
I/flutter (16217): #52     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #53     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #54     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #55     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #57     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #58     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #59     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #60     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #62     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #63     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #64     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #65     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #67     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #68     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #69     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #70     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #72     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #73     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #74     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #75     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #77     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #78     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #79     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #80     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #82     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #83     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #84     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #85     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #87     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #88     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #89     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #90     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #92     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #93     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #94     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #95     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #97     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #98     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #99     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #100    RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #101    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #102    RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #103    __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #104    RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #105    RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #107    RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #108    __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #109    RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #110    RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #111    RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:593:60)
I/flutter (16217): #112    RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:497:48)
I/flutter (16217): #113    RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:590:12)
I/flutter (16217): #114    RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #115    __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #116    RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #117    RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #118    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:95:20)
I/flutter (16217): #119    RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1109:23)
I/flutter (16217): #120    __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:279:23)
I/flutter (16217): #121    RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1107:41)
I/flutter (16217): #122    RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1440:12)
I/flutter (16217): #123    _RenderCupertinoDialog.performRegularLayout (package:flutter/src/cupertino/dialog.dart:644:44)
I/flutter (16217): #124    _RenderCupertinoDialog.performLayout (package:flutter/src/cupertino/dialog.dart:639:7)
I/flutter (16217): #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #126    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #128    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #130    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #131    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1193:11)
I/flutter (16217): #132    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #133    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:263:13)
I/flutter (16217): #134    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #135    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (16217): #136    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #137    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (16217): #138    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #139    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:13)
I/flutter (16217): #140    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #141    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (16217): #142    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #143    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #144    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #145    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #146    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #147    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #148    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #149    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #150    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #151    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #152    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #153    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #154    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #155    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #156    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2885:13)
I/flutter (16217): #157    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #158    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (16217): #159    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #160    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #161    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #162    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #163    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #164    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #165    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #166    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #167    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #168    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #169    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #170    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #171    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #172    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (16217): #173    RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (16217): #174    RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (16217): #175    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
I/flutter (16217): #176    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
I/flutter (16217): #177    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:276:19)
I/flutter (16217): #178    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (16217): #179    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (16217): #180    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (16217): #181    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (16217): #182    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (16217): #184    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (16217): #185    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (16217): #186    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and if possible the code for a minimal reproduction

**Comment by creativecreatorormaybenot** [comment]
```
runApp(MaterialApp(home: Scaffold(body: CupertinoAlertDialog(content: LayoutBuilder(builder: (_, __) => Container())))));
```
I found the change: https://github.com/flutter/flutter/commit/3a4ae280e3a4af0f93709bac7a87a1ce5445533a

**Comment by creativecreatorormaybenot** [comment]
It basically means that https://github.com/flutter/flutter/commit/3a4ae280e3a4af0f93709bac7a87a1ce5445533a disallows `LayoutBuilder` inside `CupertinoAlertDialog`. This is a breaking change for me.

**Comment by creativecreatorormaybenot** [comment]
It actually was the previous one https://github.com/flutter/flutter/commit/21bc9f1b02f657d156980adf2b7436e9872cae35 that broke it.

**Comment by matthew-carroll** [comment]
@creativecreatorormaybenot Would you mind pasting an entire Dialog widget hierarchy that was working for you before?  Then I can see what needs to be done to bring support back.

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll Thanks for your reply.  
Below you can see a minimal code example. I only included the `LayoutBuilder` in the dialog widget hierarchy, which you might have already tested or understood.  
If you like, I could also provide some more of the build tree.

I need the `LayoutBuilder` because I need the constraints in my dialog. I do not know any other way to retrieve the runtime dependend height and width of the dialog and do not know any that work with **intrinsic dimensions**. Any solution in this regard is equally valueable as bringin back `LayoutBuilder` support is because I am currently using the old `CupertinoAlertDialog`, which is *significantly inferior to your new implementation* regarding every other aspect. I really value the way it looks now and like the idea of making it look exactly like the iOS one.

``` dart
runApp(MaterialApp(
      home: Scaffold(
          body: CupertinoAlertDialog(
              content: LayoutBuilder(builder: (_, __) => Container())))));
```

**Comment by matthew-carroll** [comment]
@creativecreatorormaybenot Having a dependency on the width seems reasonable, but are you also placing a dependency on the height?  The new dialog bases its height on its content and buttons, up to the maximum height where the dialog fills the screen.  Therefore, it doesn't really make semantic sense to report a height to a child.

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll Of course, I am only dependent on the width.

**Comment by matthew-carroll** [comment]
Did someone actually fix this?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll No, but I came to the conclusion that this is not an actual problem.

Let us look at the two components individually:

 1. The **height**, what you already mentioned, will depends on the content of the dialog and thus does not make much sense.

 2. `CupertinoAlertDialog`'s **width** is always static. It is simply this: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/dialog.dart#L51  

This means that both dependencies do not make sense.
