### ISSUE TITLE
Hero throws exception with CupertinoTabScaffold

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#20939]
## Steps to Reproduce

1. tap `Next as Page`
2. tap `Next as Dialog`

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

const imageUrl = "https://flutter.io/images/flutter-mark-square-100.png";

void main() {
  runApp(new MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new CupertinoTabScaffold(
      tabBar: new CupertinoTabBar(
        items: <BottomNavigationBarItem>[
          const BottomNavigationBarItem(
            icon: const Icon(Icons.home),
            title: const Text("Left"),
          ),
          const BottomNavigationBarItem(
            icon: const Icon(Icons.gesture),
            title: const Text("Right"),
          ),
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return new MaterialApp(
          home: new Builder(
            builder: (BuildContext context) {
              return new Scaffold(
                appBar: new AppBar(title: const Text("RootPage")),
                body: Column(
                  children: <Widget>[
                    new Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: new RaisedButton(
                        onPressed: () {
                          Navigator.push(context, new CupertinoPageRoute(
                            builder: (BuildContext context) {
                              return new NextPage();
                            },
                          ));
                        },
                        child: const Text("Next as Page"),
                      ),
                    ),
                    new Hero(
                      tag: "hero",
                      child: new Image.network(imageUrl),
                    ),
                  ],
                ),
              );
            },
          ),
        );
      },
    );
  }
}

class NextPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(title: const Text("NextPage")),
      body: Column(
        children: <Widget>[
          new Padding(
            padding: const EdgeInsets.all(8.0),
            child: new Hero(
              tag: "hero",
              child: new Image.network(imageUrl),
            ),
          ),
          new RaisedButton(
            onPressed: () {
              Navigator.of(context, rootNavigator: true).push(new CupertinoPageRoute(
                fullscreenDialog: true,
                builder: (BuildContext context) {
                  return new NextPage();
                },
              ));
            },
            child: const Text("Next as Dialog"),
          ),
        ],
      ),
    );
  }
}
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
flutter: must have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: hero
flutter: Here is the subtree for one of the offending heroes:
flutter: # Hero(tag: hero, state: _HeroState#717bd)
flutter: # └KeyedSubtree-[GlobalKey#cd8bb]
flutter: #  └Image(image: NetworkImage("https://flutter.io/images/flutter-mark-square-100.png", scale: 1.0), alignment: center, state: _ImageState#bd112(stream: ImageStream#5217a(MultiFrameImageStreamCompleter#1b3df, [100×100] @ 1.0x, 2 listeners), pixels: null))
flutter: #   └RawImage(image: null, alignment: center, renderObject: RenderImage#e6d28 relayoutBoundary=up2)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:130:13)
flutter: #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:140:10)
flutter: #2      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #4      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #8      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #42     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #54     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #66     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #72     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #79     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #81     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #82     _TheatreElement.visitChildren (package:flutter/src/widgets/overlay.dart:468:16)
flutter: #83     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #85     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #87     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #89     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #91     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #93     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #95     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #97     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #99     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #100    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #101    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #103    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #105    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #107    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #109    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #111    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #112    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #113    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #115    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #117    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #119    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #121    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #123    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #125    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #126    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #127    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #129    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #131    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #133    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #134    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #135    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #137    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #138    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #139    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #140    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #141    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #142    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #143    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #145    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #147    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #148    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4742:16)
flutter: #149    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #150    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #151    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #153    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #154    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #155    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #156    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3676:14)
flutter: #157    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:144:15)
flutter: #158    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
flutter: #159    Element.visitChildElements (package:flutter/src/widgets/framework.dart:2642:5)
flutter: #160    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:146:13)
flutter: #161    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:510:53)
flutter: #162    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
flutter: #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #164    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
flutter: #165    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #166    _invoke (dart:ui/hooks.dart:120:13)
flutter: #167    _drawFrame (dart:ui/hooks.dart:109:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale ja-JP)
    • Flutter version 0.5.1 at /Applications/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by najeira** [comment]
When searching for Hero from the previous Route, it has multiple screens because it includes Navigator, multiple Heroes are detected.
