### ISSUE TITLE
Oops!Flutter has exited unexpectedly

### ISSUE THREAD

**Issue by MrshaoGx** [flutter/flutter#20977]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Deletion failed, path = '/Volumes/VMware Shared Folders/vm_shared/devicetool/build/ios/iphoneos/Runner.app' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:207)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:479)
<asynchronous suspension>
#4      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:167)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/gxshao/downloads/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Users/gxshao/Downloads/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L232m
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices (1 available)
    • 菠萝手机 • 47eae731ca3b06a5a0cd02145a2a3f4816de4a2c • ios • iOS 10.2

! Doctor found issues in 2 categories.
```

When i was create a new project in Ubuntu 16 and shared with my VMware which operating system is Mac OS 10.13.6 , when i tried to perform this ``` flutter run``` and flutter was crashed. Log as above...

**Comment by zoechi** [comment]
Did you check the current user has write permission in that directory?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by MrshaoGx** [comment]
@zoechi Sorry for the delayed response. I've been busy and didn't use flutter for last month. And the problem was solved.I was create another project and shared part of files to my vmware . and somehow it works, i think the reason caused problem that i tried to built same project in different operating system. Thanks anyway.

**Comment by zoechi** [comment]
Thanks for the update. There are several files and directories listed in 3 `.gitignore` files.
If you copy manually from one machine to the next they are all retained and can cause troubles.
If you use Git commit/clone, then these files won't be created on the destination machine.

**Comment by MrshaoGx** [comment]
> Thanks for the update. There are several files and directories listed in 3 `.gitignore` files.
> If you copy manually from one machine to the next they are all retained and can cause troubles.
> If you use Git commit/clone, then these files won't be created on the destination machine.

I didn't copy manually. I shared the folder by local network. i'll check the ```.gitignore``` file. Thank you for mentioned it.

**Comment by azharrafiq** [comment]
> Thanks for the update. There are several files and directories listed in 3 `.gitignore` files.
> If you copy manually from one machine to the next they are all retained and can cause troubles.
> If you use Git commit/clone, then these files won't be created on the destination machine.

Hi I have the same problem and I copy manually my flutter project from windows to Mac. It runs okay in simulator. However it take a long time on the first launch and my app got rejected because of this. So I want to try to do https://github.com/flutter/flutter/issues/24887#issuecomment-444412020 and then got this "Oops" error.

How to fix it? thank you.
