### ISSUE TITLE
Exception while trying to run example project flutter (28506): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞══

### ISSUE THREAD

**Issue by dsalvado** [flutter/flutter#20970]
Console Feedback:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(28506): onResume setting current activity to this
I/flutter (28506): Nothing saved yet!
Syncing files to device Android SDK built for x86...
I/flutter (28506): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (28506): The following assertion was thrown during performLayout():
I/flutter (28506): not implemented
I/flutter (28506): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (28506): 
I/flutter (28506): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28506): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28506): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28506):   https://github.com/flutter/flutter/issues/new
I/flutter (28506): 
I/flutter (28506): When the exception was thrown, this was the stack:
I/flutter (28506): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (28506): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (28506): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (28506): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (28506): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (28506): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (28506): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (28506): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (28506): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (28506): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (28506): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (28506): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (28506): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (28506): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (28506): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (28506): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (28506): #18     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (28506): #19     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (28506): #20     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:778:32)
I/flutter (28506): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (28506): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #30     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (28506): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (28506): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (28506): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (28506): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (28506): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (28506): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (28506): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter (28506): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (28506): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (28506): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (28506): #75     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter (28506): #76     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (28506): #77     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (28506): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (28506): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (28506): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (28506): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (28506): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (28506): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (28506): #85     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (28506): #86     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (28506): #87     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (28506): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (28506): 
I/flutter (28506): The following RenderObject was being processed when the exception was fired:
I/flutter (28506):   _RenderListTile#85390 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (28506):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (28506):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Align ← ⋯
I/flutter (28506):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (28506):   constraints: BoxConstraints(0.0<=w<=352.6, 0.0<=h<=576.6)
I/flutter (28506):   size: MISSING
I/flutter (28506): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (28506):   RenderSemanticsAnnotations#748fc relayoutBoundary=up8 NEEDS-PAINT
I/flutter (28506):     RenderIgnorePointer#e4f42 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (28506):       RenderPointerListener#c3092 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (28506):         _RenderDecoration#d97ce relayoutBoundary=up11 NEEDS-PAINT
I/flutter (28506):           RenderRepaintBoundary#3fe3f relayoutBoundary=up12 NEEDS-PAINT
I/flutter (28506):           RenderTransform#03a11 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (28506):           RenderConstrainedBox#094f2 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (28506):           RenderCustomPaint#45da2 NEEDS-PAINT
I/flutter (28506):   RenderSemanticsAnnotations#4fda1 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (28506):     RenderConstrainedBox#d09ed relayoutBoundary=up9 NEEDS-PAINT
I/flutter (28506):       RenderPhysicalShape#f6089 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (28506):         RenderCustomPaint#7d72c relayoutBoundary=up11 NEEDS-PAINT
I/flutter (28506):           _RenderInkFeatures#774c7 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (28506): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: _RenderListTile#85390 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderPadding#54b1e relayoutBoundary=up6 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#d68b1 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#7bbe8 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
D/        (28506): HostConnection::get() New Host Connection established 0xc9d03d40, tid 28533
D/EGL_emulation(28506): eglMakeCurrent: 0xdf569260: ver 2 0 (tinfo 0xc9d6a090)
I/flutter (28506): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1604 pos 12: '!_debugDoingBaseline': is not true.
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: _RenderListTile#85390 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderPadding#54b1e relayoutBoundary=up6 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#d68b1 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#7bbe8 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (28506): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
```

**Comment by dsalvado** [comment]
Example Code for read/write to a text file:
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart'; //https://pub.dartlang.org/packages/path_provider#-installing-tab-

void main() async {
  var data = await readData();

  if (data != null) {
    String message = await readData();
    print(message);
  }

  runApp(new MaterialApp(
    title: 'IO',
    home: new Home(),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => new _HomeState();
}

class _HomeState extends State<Home> {
  var _enterDataField = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Read/Write'),
        centerTitle: true,
        backgroundColor: Colors.greenAccent,
      ),
      body: new Container(
        padding: const EdgeInsets.all(13.4),
        alignment: Alignment.topCenter,
        child: new ListTile(
          title: new TextField(
            controller: _enterDataField,
            decoration: new InputDecoration(labelText: 'Write Something'),
          ),
          subtitle: new FlatButton(
              color: Colors.redAccent,
              onPressed: () {
                //save to file
                writeData(_enterDataField.text);
              },
              child: new Column(
                children: <Widget>[
                  new Text('Save Data'),
                  new Padding(padding: new EdgeInsets.all(14.5)),
                  new FutureBuilder(
                      future: readData(),
                      builder:
                          (BuildContext context, AsyncSnapshot<String> data) {
                        if (data.hasData != null) {
                          return new Text(
                            data.data.toString(),
                            style: new TextStyle(color: Colors.white70),
                          );
                        } else {
                          return new Text("No data saved");
                        }
                      })
                ],
              )),
        ),
      ),
    );
  }
}

Future<String> get _localPath async {
  final directory = await getApplicationDocumentsDirectory();
  return directory.path; //home/directory/
}

Future<File> get _localFile async {
  final path = await _localPath;

  return new File('$path/data.txt'); //home/directory/data.txt
}

//Write and Read from our file
Future<File> writeData(String message) async {
  final file = await _localFile;

  //write to file
  return file.writeAsString('$message');
}

Future<String> readData() async {
  try {
    final file = await _localFile;

    //Read
    String data = await file.readAsString();

    return data;
  } catch (e) {
    return "Nothing saved yet!";
  }
}

**Comment by zoechi** [comment]
Dup of #18755

See https://github.com/flutter/flutter/issues/18778#issuecomment-401629158 for an explanation.
