### ISSUE TITLE
Putting a Text as a child of a horizontal Block throws an exception when the Text is wider than the Block

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2099]
Test code:

```dart
void main() {
  runApp(new Container(
      width: 100.0,
      child: new Block(
          children: [new Text('text that\'s longer than 100.0 pixels')],
          scrollDirection: Axis.horizontal)));
}
```

Exception:
```dart
android: I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
android: I/flutter : The following exception was raised during performLayout():
android: I/flutter : 'packages/flutter/src/rendering/block.dart': Failed assertion: line 157: '() {
android: I/flutter :             if (isVertical)
android: I/flutter :             return childExtent == child.getMaxIntrinsicHeight(innerConstraints);
android: I/flutter :             return childExtent == child.getMaxIntrinsicWidth(innerConstraints);
android: I/flutter :           }' is not true.
android: I/flutter : The following RenderObject was being processed when the exception was fired:
android: I/flutter : RenderBlock relayoutSubtreeRoot=up2 NEEDS-LAYOUT
android: I/flutter : This RenderObject had the following owner:
android: I/flutter : BlockBody ← SizeObserver ← Viewport ← SizeObserver ← Listener ← Listener ← _GestureSemantics ← GestureDetector ← ScrollableViewport ← Block ← ⋯
android: I/flutter : This RenderObject had the following child:
android: I/flutter :   RenderParagraph relayoutSubtreeRoot=up3
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      RenderBlock._getIntrinsicMainAxis (packages/flutter/src/rendering/block.dart:157)
android: I/flutter : #2      RenderBlock.getMinIntrinsicWidth (packages/flutter/src/rendering/block.dart:178)
android: I/flutter : #3      RenderBox.debugAssertDoesMeetConstraints (packages/flutter/src/rendering/box.dart:640)
android: I/flutter : #4      RenderBox.size=.<anonymous closure> (packages/flutter/src/rendering/box.dart:502)
android: I/flutter : #5      RenderBox.size= (packages/flutter/src/rendering/box.dart:502)
android: I/flutter : #6      RenderBlockBase.performLayout (packages/flutter/src/rendering/block.dart:112)
android: I/flutter : #7      RenderBlock.performLayout (packages/flutter/src/rendering/block.dart:223)
android: I/flutter : #8      RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #9      RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
android: I/flutter : #10     RenderSizeObserver.performLayout (packages/flutter/src/rendering/proxy_box.dart:1187)
android: I/flutter : #11     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #12     RenderViewport.performLayout (packages/flutter/src/rendering/viewport.dart:232)
android: I/flutter : #13     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #14     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
android: I/flutter : #15     RenderSizeObserver.performLayout (packages/flutter/src/rendering/proxy_box.dart:1187)
android: I/flutter : #16     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #17     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
android: I/flutter : #18     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #19     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
android: I/flutter : #20     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #21     RenderProxyBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:74)
android: I/flutter : #22     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #23     RenderConstrainedBox.performLayout (packages/flutter/src/rendering/proxy_box.dart:207)
android: I/flutter : #24     RenderObject.layout (packages/flutter/src/rendering/object.dart:1038)
android: I/flutter : #25     RenderView.performLayout (packages/flutter/src/rendering/view.dart:96)
android: I/flutter : #26     RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:944)
android: I/flutter : #27     RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:922)
android: I/flutter : #28     BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
android: I/flutter : #29     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:95)
android: I/flutter : #30     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:160)
android: I/flutter : #31     runApp (packages/flutter/src/widgets/binding.dart:166)

```

**Comment by apwilson** [comment]
When I print the childExtent and the maxIntrinsicWidth I get the following:

```dart
child.getMaxIntrinsicWidth(innerConstraints) ===> 214.0
childExtent ===> 40.0
```

**Comment by abarth** [comment]
I think this assert is bogus.  Need to check with @Hixie
