### ISSUE TITLE
flutter_attach_test fails on dart vm assertion

### ISSUE THREAD

**Issue by aam** [flutter/flutter#21003]
Running $FH/flutter/packages/flutter_attach_test with dart vm with assertions enabled crashes VM:
```
 +534 ms] ../../third_party/dart/runtime/vm/object.cc: 2046: error: expected: thread->no_callback_scope_depth() == 0
[        ] Dumping native stack trace for thread 24c80
[        ] ../../third_party/dart/runtime/vm/heap/safepoint.cc: 53: error: expected: T->no_safepoint_scope_depth() == 0
[        ] Aborting re-entrant request for stack trace.
```

More detailed log:
```
$FH/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts --pause_isolates_on_start --enable-vm-service:38613 $FH/flutter/packages/flutter_tools/test/integration/flutter_attach_test.dart
Observatory listening on http://127.0.0.1:38613/

00:00 +0: attached process can hot reload
Spawning flutter [run, --local-engine, host_debug_unopt, -v, --machine, -d, flutter-tester] in /tmp/test_appHANFYD
[  +51 ms] executing: [$FH/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +51 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[        ] executing: [$FH/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[        ] executing: [$FH/flutter/] git log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e4b989bf3dbefc61f11bce298d16f92ebd9cde41
[        ] executing: [$FH/flutter/] git log -n 1 --pretty=format:%ar
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[   +1 ms] executing: [$FH/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.8-0-ge4b989bf3
[  +76 ms] executing: $ANDROID_SDK/platform-tools/adb devices -l
[  +15 ms] Exit code 0 from: $ANDROID_SDK/platform-tools/adb devices -l
[        ] List of devices attached
           ZY223TDXZ2             device usb:1-5.3.1.3 product:athene model:Moto_G__4_ device:athene transport_id:2
[{"event":"daemon.connected","params":{"version":"0.4.1","pid":148714}}]
[{"event":"app.start","params":{"appId":"30e0c020-31a9-43ff-af0a-a96ef277c756","deviceId":"flutter-tester","directory":"/tmp/test_appHANFYD","supportsRestart":true}}]
[ +826 ms] Launching lib/main.dart on Flutter test device in debug mode...
[ +298 ms] DependencyChecker: nothing is modified after 2018-08-24 12:19:14.724.
[   +7 ms] $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --strong --target=flutter --no-link-platform --incremental --packages /tmp/test_appHANFYD/.packages --output-dill build/app.dill --depfile build/snapshot_blob.bin.d /tmp/test_appHA...
[+7542 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +53 ms] Wrote build/flutter_assets
[        ] $FH/engine/src/out/host_debug_unopt/flutter_tester --run-forever --non-interactive --enable-dart-profiling --packages=.packages --start-paused --flutter-assets-dir=build/flutter_assets build/app.dill
[ +460 ms] Observatory URL on device: http://127.0.0.1:36639/
[   +5 ms] Connecting to service protocol: http://127.0.0.1:36639/
[ +125 ms] Do not know weight for: TeXGyreSchola (BoldItalic) 
[ +182 ms] Successfully connected to service protocol: http://127.0.0.1:36639/
[   +3 ms] getVM: {}
[   +7 ms] getIsolate: {isolateId: isolates/54238697}
[   +3 ms] _flutter.listViews: {isolateId: isolates/54238697}
[   +7 ms] Waiting for Flutter view
[+1001 ms] getVM: {}
[   +4 ms] _flutter.listViews: {isolateId: isolates/54238697}
[  +14 ms] DevFS: Creating new filesystem on the device (null)
[        ] _createDevFS: {fsName: test_appHANFYD}
[  +38 ms] DevFS: Created new filesystem on the device (file:///tmp/test_appHANFYDHWWROY/test_appHANFYD/)
[{"event":"app.debugPort","params":{"appId":"30e0c020-31a9-43ff-af0a-a96ef277c756","port":36639,"wsUri":"ws://127.0.0.1:36639/ws","baseUri":"file:///tmp/test_appHANFYDHWWROY/test_appHANFYD/"}}]
{"jsonrpc":"2.0","method":"getVM","id":0,"params":{}}
[   +3 ms] Updating assets
[{"event":"app.progress","params":{"appId":"30e0c020-31a9-43ff-af0a-a96ef277c756","id":"0","progressId":null,"message":"Syncing files to device Flutter test device..."}}]
[  +61 ms] DevFS: Starting sync from LocalDirectory: '/tmp/test_appHANFYD'
[        ] Scanning project files
[   +5 ms] Scanning package files
{"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":64,"targetCPU":"x64","hostCPU":"Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz","version":"2.1.0-dev.2.0.flutter-eab492385c (Wed Aug 8 20:47:25 2018 +0000) on \"linux_x64\"","_profilerMode":"Dart","_nativeZoneMemoryUsage":0,"pid":150656,"startTime":1535138364449,"_embedder":"Flutter","_maxRSS":265584640,"_currentRSS":105000960,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number...
{"jsonrpc":"2.0","method":"getIsolate","id":1,"params":{"isolateId":"isolates/54238697"}}
[  +70 ms] Scanning asset files
[        ] Scanning for deleted files
[  +10 ms] Compiling dart to kernel with 426 updated files
[   +4 ms] $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --incremental --strong --target=flutter --initialize-from-dill=foo --output-dill build/app.dill --packages /tmp/test_appHANFYD/.packages
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number":"54238697","_originNumber":"54238697","startTime":1535138365077,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.000000,"used":1031632,"capacity":2097152,"external":0,"time":0.000000},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":0,"used":20770976,"capacity":21229568,"external":0,"ti...
Waiting for isolate to pause
{"jsonrpc":"2.0","method":"streamListen","id":2,"params":{"streamId":"Debug"}}
{"jsonrpc":"2.0","method":"getIsolate","id":3,"params":{"isolateId":"isolates/54238697"}}
{"jsonrpc":"2.0","id":2,"result":{"type":"Success"}}
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number":"54238697","_originNumber":"54238697","startTime":1535138365076,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.000000,"used":1031984,"capacity":2097152,"external":0,"time":0.000000},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":0,"used":20770976,"capacity":21229568,"external":0,"ti...
{"jsonrpc":"2.0","method":"streamCancel","id":4,"params":{"streamId":"Debug"}}
{"jsonrpc":"2.0","method":"getIsolate","id":5,"params":{"isolateId":"isolates/54238697"}}
{"jsonrpc":"2.0","id":4,"result":{"type":"Success"}}
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number":"54238697","_originNumber":"54238697","startTime":1535138365077,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.000000,"used":1032336,"capacity":2097152,"external":0,"time":0.000000},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":0,"used":20770976,"capacity":21229568,"external":0,"ti...
{"jsonrpc":"2.0","method":"getVM","id":6,"params":{}}
{"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":64,"targetCPU":"x64","hostCPU":"Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz","version":"2.1.0-dev.2.0.flutter-eab492385c (Wed Aug 8 20:47:25 2018 +0000) on \"linux_x64\"","_profilerMode":"Dart","_nativeZoneMemoryUsage":0,"pid":150656,"startTime":1535138364449,"_embedder":"Flutter","_maxRSS":265584640,"_currentRSS":105598976,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number...
{"jsonrpc":"2.0","method":"getIsolate","id":7,"params":{"isolateId":"isolates/54238697"}}
{"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/54238697","name":"main.dart:main()","number":"54238697","_originNumber":"54238697","startTime":1535138365077,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.000000,"used":1032688,"capacity":2097152,"external":0,"time":0.000000},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":0,"used":20770976,"capacity":21229568,"external":0,"ti...
Sending resume (null)
{"jsonrpc":"2.0","method":"resume","id":8,"params":{"isolateId":"isolates/54238697"}}
{"jsonrpc":"2.0", "result":{"type":"Success"},"id":8}
[ +342 ms] topLevelFunction
[ +534 ms] ../../third_party/dart/runtime/vm/object.cc: 2046: error: expected: thread->no_callback_scope_depth() == 0
[        ] Dumping native stack trace for thread 24c80
[        ] ../../third_party/dart/runtime/vm/heap/safepoint.cc: 53: error: expected: T->no_safepoint_scope_depth() == 0
[        ] Aborting re-entrant request for stack trace.
[  +10 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[+6605 ms] Updating files
[  +14 ms] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 54726
[{"event":"app.progress","params":{"appId":"30e0c020-31a9-43ff-af0a-a96ef277c756","id":"0","progressId":null,"finished":true}}]
[{"event":"app.stop","params":{"appId":"30e0c020-31a9-43ff-af0a-a96ef277c756"}}]
[   +3 ms] DevFS: Deleting filesystem on the device (file:///tmp/test_appHANFYDHWWROY/test_appHANFYD/)
[        ] _deleteDevFS: {fsName: test_appHANFYD}
[ +253 ms] TimeoutException after 0:00:00.250000: Future not completed
[  +15 ms] "flutter run" took 18,578ms.
01:00 +0 -1: attached process can hot reload [E]
  TimeoutException after 0:01:00.000000: Test timed out after 1 minutes.
  package:test/src/backend/invoker.dart 332:26                  Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test/src/backend/invoker.dart 330:10                  Invoker._handleError
  package:test/src/backend/invoker.dart 283:9                   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test/src/backend/invoker.dart 281:38                  Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async/runtime/libtimer_patch.dart 21:15                  Timer._createTimer.<fn>
  dart:isolate/runtime/libtimer_impl.dart 382:19                _Timer._runTimers
  dart:isolate/runtime/libtimer_impl.dart 416:5                 _Timer._handleMessage
  dart:isolate/runtime/libisolate_patch.dart 169:12             _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test/src/backend/invoker.dart 280:34                  Invoker.heartbeat
  package:test/src/backend/invoker.dart 242:5                   Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                 Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test/src/backend/declarer.dart 158:13                 Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
  
Closing VM service
Waiting for process to end
Waiting for process to end
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
01:00 +0 -1: Some tests failed.


Process finished with exit code 255

```

**Comment by aam** [comment]
cc @rmacnak-google @a-siva

**Comment by aam** [comment]
In [ParagraphBuilder_constructor](https://github.com/flutter/engine/blob/9f8285ac6c18eeb64492628254ce154a7cb0a6d2/lib/ui/text/paragraph_builder.cc#L87) [Dart_CallConstructor](https://fuchsia.googlesource.com/tonic/+/master/dart_args.h#217)  first uses Int32List to wrap Dart_Handle that holds native args, uses [Dart_TypedDataAcquireData](https://fuchsia.googlesource.com/tonic/+/master/typed_data/int32_list.cc#20) to freeze those bytes. But then at this point no more Dart API call backs are allowed.

However after that `DartCallConstructor` continues with calling `DartWrappable::AssociateWithDartWrapper` which calls `Dart_SetNativeInstanceField`, which proceeds to allocate storage for native fields. At that point VM throws an exception since VM doesn't allow to allocate more objects until `Dart_TypeDataReleaseData` is called.

~stack to Dart_TypeDataAcquireData:
```
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/typed_data/int32_list.cc:20
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/typed_data/int32_list.cc:53
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/dart_args.h:27
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/dart_args.h:93
??:0
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/dart_args.h:220
$FH/engine/src/out/android_debug_unopt/../../flutter/lib/ui/text/paragraph_builder.cc:88
$FH/engine/src/out/android_debug_unopt/../../third_party/dart/runtime/vm/native_entry.cc:198
```

~stack to TypedData::New invocation
```
$FH/engine/src/out/android_debug_unopt/../../third_party/dart/runtime/vm/object.cc:22777
$FH/engine/src/out/android_debug_unopt/../../third_party/dart/runtime/vm/object.cc:17295
$FH/engine/src/out/android_debug_unopt/../../third_party/dart/runtime/vm/dart_api_impl.cc:4557
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/dart_wrappable.cc:52
$FH/engine/src/out/android_debug_unopt/../../third_party/tonic/dart_args.h:223
$FH/engine/src/out/android_debug_unopt/../../flutter/lib/ui/text/paragraph_builder.cc:88
$FH/engine/src/out/android_debug_unopt/../../third_party/dart/runtime/vm/native_entry.cc:198
```
cc @jason-simmons @chinmaygarde for thoughts

**Comment by jason-simmons** [comment]
This should be fixable by changing `ParagraphBuilder::create` to acquire and release the typed data list internally instead of relying on Tonic argument conversion to wrap the list

**Comment by aam** [comment]
There are dozen places where `DartCallConstructor` is similarly used, so hopefully the solution will cover those other constructors too.
