### ISSUE TITLE
Failed assertion

### ISSUE THREAD

**Issue by MattJakarta** [flutter/flutter#21055]
Dear all,

In trying to get to work with Flutter, I have tried to make a widget of my own in which I combine a Container and a Text with a few optional parameters. Code:
```dart
import 'package:flutter/material.dart';

class basicTextWidget extends StatelessWidget {
  String displayText = "";
  Color color = Colors.black;
  double paddingAll = 5.0;
  double paddingLeft = 0.0;
  double paddingRight = 0.0;
  double paddingBottom = 0.0;
  double paddingTop = 0.0;
  double marginAll = 0.0;
  double marginLeft = 0.0;
  double marginRight = 0.0;
  double marginBottom = 0.0;
  double marginTop = 0.0;
  int maxLines = 1;
  bool bold = false;
  bool italic = false;
  double sizeFactor = 1.0;
  TextOverflow textOverflow = TextOverflow.ellipsis;
  TextDirection textDirection = TextDirection.ltr;
  bool textWrap = true;
  TextAlign textAlign = TextAlign.left;

  basicTextWidget(
      this.displayText,
      {this.color,
      this.textAlign,
      this.paddingAll,
      this.paddingLeft,
      this.paddingRight,
      this.paddingBottom,
      this.paddingTop,
      this.marginAll,
      this.marginLeft,
      this.marginRight,
      this.marginBottom,
      this.marginTop,
      this.maxLines,
      this.bold,
      this.italic,
      this.sizeFactor,
      this.textOverflow,
      this.textDirection,
      this.textWrap}):super();

  @override
  Widget build(BuildContext context) {
    EdgeInsetsGeometry padding = new EdgeInsets.all(this.paddingAll);
    if (
    (this.paddingLeft != 0) ||
        (this.paddingRight != 0) ||
        (this.paddingTop != 0) ||
        (this.paddingBottom != 0)
    )
      padding = new EdgeInsets.fromLTRB(
          this.paddingLeft, this.paddingTop, this.paddingRight,
          this.paddingBottom);
    //
    EdgeInsetsGeometry margin = new EdgeInsets.all(this.marginAll);
    if (
    (this.marginLeft != 0) ||
        (this.marginRight != 0) ||
        (this.marginTop != 0) ||
        (this.marginBottom != 0)
    )
      margin = new EdgeInsets.fromLTRB(
          this.marginLeft, this.marginTop, this.marginRight,
          this.marginBottom);
    //
    FontStyle fontStyle = FontStyle.normal;
    if (italic) fontStyle = FontStyle.italic;
    FontWeight fontWeight = FontWeight.normal;
    if (bold) fontWeight = FontWeight.bold;
    TextStyle textStyle = new TextStyle(
      inherit: true,
      color: color,
      fontStyle: fontStyle,
      fontWeight: fontWeight,
    );
    //
    Widget returnValue = new Container(margin: margin, padding: padding,
      child: new Text(
        displayText,
        style: textStyle,
        textDirection: textDirection,
        textAlign: textAlign,
        textScaleFactor: sizeFactor,
      ),
    );
    return returnValue;
  }
}
```
____________________________________________________________________________

I call this from main:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'CustomWidgets/textWidgets.dart';

void main() {
  //todo
  runApp(new MyFirstWidget());
}

class MyFirstWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(title: Text("Test app!")),
            body: Center(
              child:new basicTextWidget("Hallo!",)
            )
        )
    );
  }
}
```

___________________________________________________________________________

What I get on screen is a shipload of Failed assertion: boolean expression must not be null feedback, but no padded Text.

The Console told me this:
```
Initializing hot reload...
I/flutter (27051): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27051): The following assertion was thrown building basicTextWidget(dirty):
I/flutter (27051): Failed assertion: boolean expression must not be null
I/flutter (27051): 
I/flutter (27051): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (27051): more information in this error message to help you determine and fix the underlying cause.
I/flutter (27051): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (27051):   https://github.com/flutter/flutter/issues/new
I/flutter (27051): 
I/flutter (27051): When the exception was thrown, this was the stack:
I/flutter (27051): #0      basicTextWidget.build (file:///home/matt/AndroidStudioProjects/layout_tutorial/lib/CustomWidgets/textWidgets.dart)
I/flutter (27051): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3695:28)
I/flutter (27051): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (27051): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #4      StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (27051): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
I/flutter (27051): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
I/flutter (27051): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #25     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #35     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (27051): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (27051): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #79     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (27051): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #83     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #89     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #95     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
I/flutter (27051): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #99     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
I/flutter (27051): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
I/flutter (27051): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
I/flutter (27051): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
I/flutter (27051): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (27051): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (27051): #109    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (27051): #110    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (27051): #111    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (27051): #112    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27051): #113    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27051): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (27051): #116    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (27051): #117    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (27051): #118    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (27051): (elided one frame from package dart:async)
I/flutter (27051): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 392 libraries in 1,479ms.
V/BoostFramework(27051): BoostFramework() : mPerf = com.qualcomm.qti.Performance@9884c7a
I/FlutterActivityDelegate(27051): onResume setting current activity to this
I/FlutterActivityDelegate(27799): onResume setting current activity to this
I/FlutterActivityDelegate(27051): onResume setting current activity to this
```
____________________________________________________________________________
...asking me most urgently to raise this issue; which I hereby duly do.

Kind regards,

Matt

**Comment by zoechi** [comment]
Could you try stepping through build to figure out what line causes the exception?
The exception indicates that a line like

>     if (italic) fontStyle = FontStyle.italic;

the condition (`italic`) is `null` while only `true` or `false` are allowed.

**Comment by zoechi** [comment]
Dup of #16631

**Comment by nosmirck** [comment]
I believe the main issue is the misunderstanding of how the constructor with optional parameters works. Instead of initializing them in the property declaration itself, do it in the constructor as default values. Example:

```dart

void main() {
  var example = Example("requiered");
  var example2 = Example2("requiered");
  var example3 = Example3("requiered");
  print("${example.requiredString} : ${example.optionalInt}");
  print("${example2.requiredString} : ${example2.optionalInt}");
  print("${example3.requiredString} : ${example3.optionalInt}");
}
class Example extends BaseExample {
   String requiredString;
   int optionalInt = 1;
   Example (this.requiredString, {this.optionalInt}) : super();
}
class Example2 extends BaseExample {
   String requiredString;
   final int optionalInt;
   Example2 (this.requiredString) :
     this.optionalInt = 1,
     super();
}
class Example3 extends BaseExample {
   String requiredString;
   final int optionalInt;
   Example3 (this.requiredString, {this.optionalInt = 1}) : super();
}
class BaseExample {
  BaseExample();
}

Output:
required : null
required : 1
required : 1
```

Optional parameters, when not set from the caller, they will be null, overriding the value you set on the property declaration (never put default values on a property declaration unless they're final!). You can see in the example that the optional property is set during declaration (just like yours) and you can see that, when used, it's null while on the other 2 examples the optional property holds the default value set during the constructor call.

So, you can either use option 2 or 3 (I prefer using option 2, but it's up to you).

This bug is not a problem with the framework but the bad way of using Dart (I had the same issues at the beginning because I never had experience with Dart and coming from a C# and C++ background, we are used to declare the default values when declaring the properties just like you did, but in Dart this is a bad practice)

Hope this helped.

**Comment by goderbauer** [comment]
@nosmirck's explanation is exactly right. It's actually good practice to mark all fields in a SttelessWidget as final (see second example in https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/StatelessWidget-class.html). That way the analyzer would have complained about your code right away.

So, you should change your code to:

```dart
class BasicTextWidget extends StatelessWidget {
  final String displayText;
  final Color color;
  final double paddingAll;
  final double paddingLeft;
  final double paddingRight;
  final double paddingBottom;
  final double paddingTop;
  final double marginAll;
  final double marginLeft;
  final double marginRight;
  final double marginBottom;
  final double marginTop;
  final int maxLines;
  final bool bold;
  final bool italic;
  final double sizeFactor;
  final TextOverflow textOverflow;
  final TextDirection textDirection;
  final bool textWrap;
  final TextAlign textAlign;

  BasicTextWidget(
    this.displayText, {
    this.color: Colors.black,
    this.paddingAll: 5.0,
    this.paddingLeft: 0.0,
    this.paddingRight: 0.0,
    this.paddingBottom: 0.0,
    this.paddingTop: 0.0,
    this.marginAll: 0.0,
    this.marginLeft: 0.0,
    this.marginRight: 0.0,
    this.marginBottom: 0.0,
    this.marginTop: 0.0,
    this.maxLines: 1,
    this.bold: false,
    this.italic: false,
    this.sizeFactor: 1.0,
    this.textOverflow: TextOverflow.ellipsis,
    this.textDirection: TextDirection.ltr,
    this.textWrap: false,
    this.textAlign: TextAlign.left,
    Key key,
  }) : super(key: key);

  /// more stuff here
}
```
