### ISSUE TITLE
Flutter has problems running

### ISSUE THREAD

**Issue by warriorBrian** [flutter/flutter#21053]
**i use android Studio**

flutter running is error:

## command
```
flutter build bundle --suppress-analytics --target E:\app\fultter_app_01\flutter_app\lib\main.dart --preview-dart-2 --filesystem-scheme org-dartlang-root --depfile E:\app\fultter_app_01\flutter_app\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir E:\app\fultter_app_01\flutter_app\build\app\intermediates\flutter\debug/flutter_assets
```
## exception
```
RangeError: RangeError (index): Invalid value: Only valid value is 0: 1
```
```
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      readDepfile (package:flutter_tools/src/base/fingerprint.dart:174)
<asynchronous suspension>
#2      Fingerprinter._getPaths (package:flutter_tools/src/base/fingerprint.dart:88)
<asynchronous suspension>
#3      Fingerprinter.doesFingerprintMatch (package:flutter_tools/src/base/fingerprint.dart:60)
<asynchronous suspension>
#4      KernelCompiler.compile (package:flutter_tools/src/compile.dart:104)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:79)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:72)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#15     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#24     new Future.sync (dart:async/future.dart:222)
#25     CommandRunner.run (package:args/command_runner.dart:109)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1501)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50)
#35     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#36     main (file:///E:/tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.112], locale zh-CN)
    • Flutter version 0.5.1 at E:\tools\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:/Users/liuxiaomeng/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = C:/Users/liuxiaomeng/AppData/Local/Android/Sdk
    • Java binary at: D:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at D:\as
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by warriorBrian** [comment]
@zoechi 
i check `android/local.properties`  **This path is correct!**
**Android SDK to the PATH** This path is correct!
but, It will be inexplicably wrong, I don't know how to fix it!

I also re-created the project to copy the original code into the re-established project.

Is everything normal

**I think it is a mistake in the flutter framework.**

**Comment by warriorBrian** [comment]
@zoechi 
I think I am different from the[#20976] (https://github.com/flutter/flutter/issues/20976)  issues.

my **flutter doctor** Pass all

So I don't know how to solve it, which led me to re-establish a new project.

**So, if you know how to solve this problem, please let me know, thank you**

**Comment by zoechi** [comment]
> my flutter doctor Pass all

Good point.

**Comment by warriorBrian** [comment]
@zoechi  so, Do you know how to solve this problem correctly?

**Comment by zoechi** [comment]
@warriorBrian nope, have to wait for specialists

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/17831#issuecomment-391808736

**Comment by zoechi** [comment]
Is anybody still seeing this?
It looks like this is a dup of #17831 that was fixed 
See https://github.com/flutter/flutter/issues/17831#issuecomment-395925533

**Comment by zoechi** [comment]
@warriorBrian I'm confused 😄 
What does your comment mean? Are you still seeing the error?
Can you please post the output of `flutter doctor -v`?

**Comment by warriorBrian** [comment]
@zoechi I have a new flutter again, there is no way to solve it.
![tim 20190214231325](https://user-images.githubusercontent.com/28696399/52796139-31d50e80-30ae-11e9-9729-6e5f4842f695.png)

**Comment by zoechi** [comment]
@warriorBrian check the output if you really have a recent Flutter version.
Also try `flutter clean`.

**Comment by warriorBrian** [comment]
@zoechi Perfectly solved this problem, I can run normally with flutter clean, it is perfect! 👍

**Comment by Sujan-Murugesh** [comment]
I also got this error . 
builder: (context, snapshot) {
            if(!snapshot.hasData){
              return CircularProgressIndicator();
            }
            return ListView.builder(
                 // To do ....
           );

After adding this lines my app work perfectly....

**Comment by exeptionerror** [comment]
All Possible Working solution added [[Solved] Invalid depfile: Flutter](https://fluttercorner.com/invalid-depfile-flutter/)
