### ISSUE TITLE
I am assigned data from web service to dropdown but i am changeing this value its give me error below 

### ISSUE THREAD

**Issue by Pradipkoravi** [flutter/flutter#21052]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28462): The following assertion was thrown building SeatPage(dirty, state: _SeatPageState#d6ba9):
I/flutter (28462): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 481 pos 15: 'value == null ||
I/flutter (28462): items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.
I/flutter (28462): 
I/flutter (28462): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28462): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28462): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28462):   https://github.com/flutter/flutter/issues/new
I/flutter (28462): 
I/flutter (28462): When the exception was thrown, this was the stack:
I/flutter (28462): #2      new DropdownButton (package:flutter/src/material/dropdown.dart)
I/flutter (28462): #3      _SeatPageState.build (package:menurunnrsevents/pages/seatnumberpage.dart:227:48)
I/flutter (28462): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
I/flutter (28462): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
I/flutter (28462): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (28462): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
I/flutter (28462): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
I/flutter (28462): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (28462): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (28462): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (28462): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (28462): #13     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (28462): #14     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (28462): (elided 2 frames from class _AssertionError)
```

**Comment by zoechi** [comment]
This probably means that the selected value is not contained in the list of values to select from.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
