### ISSUE TITLE
Flutter duplicate key error

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#21160]
My screen is working fine but after Flutter upgrade having padding issue in most of screen and another issue is:
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 8606): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8606): The following assertion was thrown building Products(state: _ProductsState#70260):
I/flutter ( 8606): A GlobalKey was used multiple times inside one widget's child list.
I/flutter ( 8606): The offending GlobalKey was: [LabeledGlobalKey<ScaffoldState>#c2a38]
I/flutter ( 8606): The parent of the widgets with that key was:
I/flutter ( 8606):   Products(state: _ProductsState#70260)
I/flutter ( 8606): The first child to get instantiated with that key became:
I/flutter ( 8606):   Scaffold-[LabeledGlobalKey<ScaffoldState>#c2a38](state: ScaffoldState#0898d(tickers: tracking 1
I/flutter ( 8606):   ticker))
I/flutter ( 8606): The second child that was to be instantiated with that key was:
I/flutter ( 8606):   Products
I/flutter ( 8606): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter ( 8606): 
I/flutter ( 8606): When the exception was thrown, this was the stack:
I/flutter ( 8606): #0      Element._retakeInactiveElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:2866:11)
I/flutter ( 8606): #1      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:2880:8)
I/flutter ( 8606): #2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2908:32)
I/flutter ( 8606): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 8606): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 8606): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 8606): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 8606): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 8606): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 8606): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 8606): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 8606): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 8606): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 8606): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 8606): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 8606): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 8606): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 8606): #58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 8606): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 8606): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter ( 8606): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8606): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8606): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 8606): #65     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 8606): #66     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 8606): #67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
I/flutter ( 8606): (elided one frame from package dart:async)
I/flutter ( 8606): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 528 libraries in 4,661ms.
```

**Comment by zoechi** [comment]
Can you provide a reduced reproduction?
It's hard to tell if this is an issue in your code or Flutter code from the provided information.

Please also add the output of `flutter doctor -v`.

**Comment by rahulmishra1991** [comment]
https://stackoverflow.com/questions/52072010/image-upload-issue

are you able to help me into this?
