### ISSUE TITLE
Data object not working

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#21209]
I am trying to use fetched data but every time getting object issue 

**API:**
http://eh.projectstatus.in/api/web/v1/app/get-product?id=6

**My Code**
```dart
    class _ProductDetailState extends State<ProductDetail> {
      Map proData;
      List images;
      int i = 0;

      @override
      void initState() {
        super.initState();

        restApis.getProductDetail(widget.product_id).then((val) => setState(() {
          setState(() {
           proData = val["data"];
          });
       }));
      }


      @override
      Widget build(BuildContext context) {
        //print("Result Data Inner: ${proData.name}");
       return Scaffold(
          appBar: AppBarComponent(),
         drawer: new Drawer(child: DrawerList()),
          body:Container(
           child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
               children: <Widget>[
                  Container(
                    decoration: BoxDecoration(
                   ),
                   child: Text('${proData["primary_image"]}'),
                  )
               ],
            ),
          ),
          )
        );
      }
    }


**API Code:**

       Future getProductDetail(product_id) async {
        print("API PID: $product_id");
        String apiUrl = '$_apiUrl/app/get-product?id=$product_id';
         http.Response response = await http.get(apiUrl,headers: {
            "Accept": "application/json",
         });
          print("Result: ${response.body}");
          return json.decode(response.body);
        }
```
**Error:**
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 15 of 529 libraries in 5,023ms.
I/flutter ( 7226): API PID: 6
I/flutter ( 7226): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7226): The following NoSuchMethodError was thrown building ProductDetail(dirty, state:
I/flutter ( 7226): _ProductDetailState#af725):
I/flutter ( 7226): The method '[]' was called on null.
I/flutter ( 7226): Receiver: null
I/flutter ( 7226): Tried calling: []("primary_image")
I/flutter ( 7226): 
I/flutter ( 7226): When the exception was thrown, this was the stack:
I/flutter ( 7226): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
I/flutter ( 7226): #1      _ProductDetailState.build (package:ecom_hybrid/ui/product_detail.dart:56:39)
I/flutter ( 7226): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3743:27)
I/flutter ( 7226): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter ( 7226): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter ( 7226): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter ( 7226): #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter ( 7226): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter ( 7226): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter ( 7226): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter ( 7226): #99     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4450:32)
I/flutter ( 7226): #100    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter ( 7226): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #102    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 7226): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 7226): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 7226): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 7226): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 7226): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 7226): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 7226): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 7226): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 7226): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 7226): #124    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 7226): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 7226): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter ( 7226): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7226): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7226): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 7226): #130    _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 7226): #131    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 7226): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
`).then(` indicates that there is some async execution involved.
This means at first when `build` is called `proData` is still `null`.
Only later when `setState` is executed, `proData` will have a value and `build()` will be executed again (because of `setState`) .

```dart
      @override
      Widget build(BuildContext context) {
        //print("Result Data Inner: ${proData.name}");
       return Scaffold(
          appBar: AppBarComponent(),
         drawer: new Drawer(child: DrawerList()),
          body:Container(
           child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
               children: <Widget>[
                  Container(
                    decoration: BoxDecoration(
                   ),
                   child: Text(proData != null ? '${proData["primary_image"]}' : '... waiting for data to arrive ...'),
                  )
               ],
            ),
          ),
          )
        );
      }
    }
```

I'm going to closes because this is not a Flutter issue.
Feel free to add more comments anyway.

Please consider asking support questions in one of the other channels http://flutter.io/support
