### ISSUE TITLE
AlignmentDirectional doesn't work

### ISSUE THREAD

**Issue by Gennki** [flutter/flutter#21266]
## Steps to Reproduce

1. This is my code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: Container(
        color: Color.fromARGB(255, 66, 165, 245),
        child: new Text(
          "Flutter Cheatsheet",
          textDirection: TextDirection.ltr,
          style: TextStyle(fontSize: 20.0),
        ),
        alignment: new AlignmentDirectional(0.0, 0.0),
      ),
    );
  }
}

```
2. Problem:
The text should be centered, but when I run it, the text is displayed in the upper left corner

```
## Logs
Performing hot restart...
Syncing files to device SM G9550...
Restarted application in 1,623ms.
I/flutter (17906): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17906): The following assertion was thrown during performLayout():
I/flutter (17906): 'package:flutter/src/painting/alignment.dart': Failed assertion: line 552 pos 12: 'direction !=
I/flutter (17906): null': is not true.
I/flutter (17906): 
I/flutter (17906): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17906): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17906): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17906):   https://github.com/flutter/flutter/issues/new
I/flutter (17906): 
I/flutter (17906): When the exception was thrown, this was the stack:
I/flutter (17906): #2      AlignmentDirectional.resolve (package:flutter/src/painting/alignment.dart:552:12)
I/flutter (17906): #3      RenderAligningShiftedBox._resolve (package:flutter/src/rendering/shifted_box.dart:252:36)
I/flutter (17906): #4      RenderAligningShiftedBox.alignChild (package:flutter/src/rendering/shifted_box.dart:307:5)
I/flutter (17906): #5      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:384:7)
I/flutter (17906): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (17906): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (17906): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (17906): #9      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (17906): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (17906): #11     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (17906): #12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
I/flutter (17906): #13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
I/flutter (17906): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:276:19)
I/flutter (17906): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (17906): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (17906): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17906): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17906): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17906): #21     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17906): #22     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17906): #23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
I/flutter (17906): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (17906): 
I/flutter (17906): The following RenderObject was being processed when the exception was fired:
I/flutter (17906):   RenderPositionedBox#85f8f relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17906):   creator: Align ← DecoratedBox ← Container ← Center ← MyApp ← [root]
I/flutter (17906):   parentData: <none> (can use size)
I/flutter (17906):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=731.4)
I/flutter (17906):   size: Size(411.4, 731.4)
I/flutter (17906):   alignment: AlignmentDirectional.center
I/flutter (17906):   widthFactor: expand
I/flutter (17906):   heightFactor: expand
I/flutter (17906): This RenderObject had the following child:
I/flutter (17906):   RenderParagraph#89c64 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (17906): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
If you remove the alignment it is centered. 
Can you elaborate what you try to accomplish exactly and what effect you expect from alignment?

**Comment by zoechi** [comment]
Perhaps 
```dart
void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: new Center(
        child: Container(
          color: Color.fromARGB(255, 66, 165, 245),
          child: new Text(
            "Flutter Cheatsheet",
            style: TextStyle(fontSize: 10.0),
          ),
          alignment: Alignment(0.0, 0.0),
        ),
      ),
    );
  }
}
```
The directionality widget is provided by `Scaffold`. If you don't use `Scaffold` you need to provide it yourself. The error could be more clear though.

**Comment by Gennki** [comment]
the output of `flutter doctor -v` is :
------
C:\Users\Flyn\Desktop\myapp>flutter doctor -v
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.228], locale zh-CN)
    • Flutter version 0.6.0 at C:\Users\Flyn\Desktop\flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\User\Development\SDK\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\User\Development\SDK\Android
    • Java binary at: C:\User\Development\Tools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\User\Development\Tools\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\User\Development\Tools\IntelliJ IDEA 2017.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • SM G9550 • 9889193852464d3359 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
------
## But I only use Android Studio development, and it should have nothing to do with IntelliJ IDEA.

**Comment by zoechi** [comment]
Did my suggestion help?

**Comment by zoechi** [comment]
> I only use Android Studio

There is no need for all checkboxes to be ok. 
The output of `flutter doctor -v` Is just a convenient way to collect a set of information that is usually helpful diagnosing like Flutter version, IDE version, OS, ...

**Comment by Gennki** [comment]
Now the text is centered.Thanks for your suggestion .Thank you very much!!!!!!!O(∩_∩)O
Amazing!!!
