### ISSUE TITLE
Flutter Android app crashing when switching branches with different dependencies

### ISSUE THREAD

**Issue by lordgreg** [flutter/flutter#21327]
## Steps to Reproduce
1. I've had an flutter app working without issues. 
1.1 master branch dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  charts_flutter: ^0.4.0
  flutter_svg: ^0.5.0
  flutter_localizations:
    sdk: flutter
  xml2json: ^3.0.1
  flutter_html: ^0.5.3
```

Then I've created a new branch, in which I've also installed another dependency and of course, updated my code:

1.2 feature/graphql branch dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  charts_flutter: ^0.4.0
  flutter_svg: ^0.5.0
  flutter_localizations:
    sdk: flutter
  xml2json: ^3.0.1
  flutter_html: ^0.5.3
  rxdart: ^0.18.1
  graphql_flutter: ^0.9.1
```

However, I've wanted to run my master again so I've switched and started. App didn't start. It didn't start in 2 different emulators, nor on my real device (Pixel 2 XL). App crashes. Returning back to feature branch.. and the app start without any issues.

## Logs

Starting adb logcat, this is the output I get:
```
--------- beginning of crash
09-01 21:13:55.541  6030  6030 E AndroidRuntime: FATAL EXCEPTION: main
09-01 21:13:55.541  6030  6030 E AndroidRuntime: Process: PACKAGE_ID_REPLACED, PID: 6030
09-01 21:13:55.541  6030  6030 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{PACKAGE_ID_REPLACED/PACKAGE_ID_REPLACED.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "PACKAGE_ID_REPLACED.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/base.apk"],nativeLibraryDirectories=[/data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/lib/x86, /data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/base.apk!/lib/x86, /system/lib]]
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-01 21:13:55.541  6030  6030 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "PACKAGE_ID_REPLACED.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/base.apk"],nativeLibraryDirectories=[/data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/lib/x86, /data/app/PACKAGE_ID_REPLACED-XIX_-1CcgT4qSJx6bexRZA==/base.apk!/lib/x86, /system/lib]]
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
09-01 21:13:55.541  6030  6030 E AndroidRuntime:        ... 11 more
09-01 21:13:55.572  1910  2396 W ActivityManager:   Force finishing activity PACKAGE_ID_REPLACED/.MainActivity
09-01 21:13:55.574  1613  2831 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 15622144
09-01 21:13:55.577  1910  1928 I ActivityManager: Showing crash dialog for package PACKAGE_ID_REPLACED u0
09-01 21:13:55.678  2616  4392 E s.nexuslaunche: No package ID ff found for ID 0xffffffff.
09-01 21:13:55.678  2616  4392 E IconLoader: Could not find icon drawable from resource
09-01 21:13:55.678  2616  4392 E IconLoader: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
09-01 21:13:55.678  2616  4392 E IconLoader:    at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
09-01 21:13:55.678  2616  4392 E IconLoader:    at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
09-01 21:13:55.678  2616  4392 E IconLoader:    at android.content.res.Resources.getDrawable(Resources.java:827)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
09-01 21:13:55.678  2616  4392 E IconLoader:    at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
09-01 21:13:55.678  2616  4392 E IconLoader:    at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
09-01 21:13:55.678  2616  4392 E IconLoader:    at android.os.Binder.execTransact(Binder.java:731)
09-01 21:13:55.704  1910  1928 W Looper  : Slow dispatch took 128ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=1
09-01 21:13:55.740  1613  2831 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5783552
09-01 21:13:55.753  1613  2831 I chatty  : uid=1000(system) HwBinder:1613_2 identical 1 line
09-01 21:13:55.764  1613  2831 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5783552
09-01 21:13:55.783  1910  5272 D EGL_emulation: eglMakeCurrent: 0xcae60ee0: ver 3 1 (tinfo 0xd379b5d0)
09-01 21:13:55.877  1910  1928 W Looper  : Slow dispatch took 101ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@9be566 m=0
09-01 21:13:55.877  2062  2295 D EGL_emulation: eglMakeCurrent: 0xd1a17240: ver 3 1 (tinfo 0xe437f640)
09-01 21:13:56.074  1910  1927 W ActivityManager: Activity pause timeout for ActivityRecord{c74be8e u0 PACKAGE_ID_REPLACED/.MainActivity t16 f}
09-01 21:13:56.005  2062  2295 I chatty  : uid=10034(com.android.systemui) RenderThread identical 14 lines
09-01 21:13:56.018  2062  2295 D EGL_emulation: eglMakeCurrent: 0xd1a17240: ver 3 1 (tinfo 0xe437f640)
09-01 21:13:56.150  2716  2716 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
09-01 21:13:56.151  2716  2716 I AudioController: Using mInputStreamFactoryBuilder
```

`flutter run --verbose` produced this:
```
[        ] BUILD SUCCESSFUL in 14s
[        ] 29 actionable tasks: 21 executed, 8 up-to-date
[ +432 ms] Running 'gradlew assembleDebug'... (completed)
[  +26 ms] calculateSha: LocalDirectory: 'C:\Development\DIRNAME\build\app\outputs\apk'/app.apk
[ +453 ms] Built build\app\outputs\apk\debug\app-debug.apk.
[   +1 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump xmltree C:\Development\DIRNAME\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +56 ms] Exit code 0 from: C:\Users\Gregor\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump xmltree C:\Development\DIRNAME\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: package="BUNDLE_ID_REPLACED" (Raw: "BUNDLE_ID_REPLACED")
               E: uses-sdk (line=6)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=23)
                 A: android:label(0x01010001)="AĂśW" (Raw: "AĂśW")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="BUNDLE_ID_REPLACED.MainActivity" (Raw: "BUNDLE_ID_REPLACED.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=46)
                     E: action (line=47)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=49)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +3 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell am force-stop BUNDLE_ID_REPLACED
[  +97 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell pm list packages BUNDLE_ID_REPLACED
[  +65 ms] package:BUNDLE_ID_REPLACED
[   +2 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell cat /data/local/tmp/sky.BUNDLE_ID_REPLACED.sha1
[  +56 ms] a5016a1a38763a57d226ace35427f3e10dd2d380
[   +1 ms] Installing APK.
[   +1 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb version
[  +42 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb.EXE
[        ] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb start-server
[  +44 ms] Installing build\app\outputs\apk\app.apk...
[        ] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 install -t -r C:\Development\DIRNAME\build\app\outputs\apk\app.apk
[+1446 ms] Success
[        ] Installing build\app\outputs\apk\app.apk... (completed)
[   +1 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell echo -n 472d2a2cea497b30997260be0a62cfe338693641 > /data/local/tmp/sky.BUNDLE_ID_REPLACED.sha1
[  +69 ms] Android SDK built for x86 startApp
[   +1 ms] executing: C:\Users\Gregor\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true BUNDLE_ID_REPLACED/BUNDLE_ID_REPLACED.MainActivity
[ +198 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=BUNDLE_ID_REPLACED/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...

```

`flutter analyze`
```
$ flutter analyze
Analyzing PROJECT_ID...

   info - Unused import: '../data/static.dart' - lib\ui\login.dart:9:8

1 issue found. (ran in 9.8s)
```

`flutter doctor -v`
```
$ flutter doctor -v
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.228], locale sl-SI)
    • Flutter version 0.6.0 at C:\Users\Gregor\flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\Gregor\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\Users\Gregor\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by lordgreg** [comment]
Oh, 

`flutter doctor` or `flutter clean` or similar did not help. Neither did downloading completely fresh flutter sdk and moving it to another dir as previous. Neither did deleting emulator images (aka simulating factory restart of device)

**Comment by kaetemi** [comment]
Tried deleting build directory?

**Comment by lordgreg** [comment]
@kaetemi as I've written in my previous comment `flutter clean` (which removes build directory) did not help at all.

**Comment by lordgreg** [comment]
This issue has been solved.

We updated the bundle names in android/ios folders. One thing we forgot (dumb) is to actually update the folder structure for Android platform which was still showing on old package name.
