### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by ShashwatHiregoudar** [flutter/flutter#21346]
## Steps to Reproduce

I created a new flutter application from command line
and it is showing gradle error

## Logs

```
flutter run --verbose
[  +39 ms] executing: [/home/shashwat/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/shashwat/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/home/shashwat/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/shashwat/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 9299c02cf708497d6f72edda8efae0bb8340660e
[        ] executing: [/home/shashwat/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] executing: [/home/shashwat/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.6.0-0-g9299c02
[ +247 ms] executing: /home/shashwat/Android/Sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /home/shashwat/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ZY2244F3QD             device usb:2-3 product:potter_n model:Moto_G__5__Plus device:potter_n transport_id:1
[ +257 ms] /home/shashwat/Android/Sdk/platform-tools/adb -s ZY2244F3QD shell getprop
[  +98 ms] ro.hardware = qcom
[ +791 ms] Launching lib/main.dart on Moto G 5 Plus in debug mode...
[  +28 ms] Initializing gradle...
[  +12 ms] Using gradle from /home/shashwat/sample_app/android/gradlew.
[  +71 ms] executing: /home/shashwat/sample_app/android/gradlew -v
[ +180 ms] Unzipping /home/shashwat/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip to /home/shashwat/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1
                   
                   Exception in thread "main" java.util.zip.ZipException: error in opening zip file
                   	at java.util.zip.ZipFile.open(Native Method)
                   	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
                   	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
                   	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
                   	at org.gradle.wrapper.Install.unzip(Install.java:214)
                   	at org.gradle.wrapper.Install.access$600(Install.java:27)
                   	at org.gradle.wrapper.Install$1.call(Install.java:74)
                   	at org.gradle.wrapper.Install$1.call(Install.java:48)
                   	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
                   	at org.gradle.wrapper.Install.createDist(Install.java:48)
                   	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
                   	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +14 ms] "flutter run" took 1,623ms.

Oops; flutter has exited unexpectedly: "Exit code 1 from: /home/shashwat/sample_app/android/gradlew -v:
Unzipping /home/shashwat/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip to /home/shashwat/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)".
Sending crash report to Google.
Crash report sent (report ID: 6880bda210391838)
Crash report written to /home/shashwat/sample_app/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
flutter analyze
Analyzing sample_app...                                          
No issues found! (ran in 0.9s)

```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.6.0, on Linux, locale en_IN)
    • Flutter version 0.6.0 at /home/shashwat/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/shashwat/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /home/shashwat/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Moto G 5 Plus • ZY2244F3QD • android-arm • Android 7.0 (API 24)

• No issues found!

```

**Comment by zoechi** [comment]
Closing as dup of #15721
Please upvote and follow there.
