### ISSUE TITLE
NoSuchMethodError: Class '_CompileTimeError' has no instance getter 'message'.

### ISSUE THREAD

**Issue by dynamitechetan** [flutter/flutter#21356]
```
Launching lib/main.dart on iPad Pro (10.5-inch) in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.
vm-service: Error: Unhandled exception:
NoSuchMethodError: Class '_CompileTimeError' has no instance getter 'message'.
Receiver: Instance of '_CompileTimeError'
Tried calling: message
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      WebSocketClient.onWebSocketMessage (dart:vmservice_io/server.dart:62:39)
#2      new WebSocketClient.<anonymous closure> (dart:vmservice_io/server.dart:25:32)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#7      _StreamController._add (dart:async/stream_controller.dart:639:7)
#8      _StreamController.add (dart:async/stream_controller.dart:585:5)
#9      new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dar<…>
[VERBOSE-2:dart_isolate.cc(813)] Isolate (575484270) 'vm-service' exited with an error
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CompileTimeError was thrown building Localizations(locale: en_US, delegates:
flutter: [_MaterialLocalizationsDelegate[MaterialLocalizations],
flutter: _WidgetsLocalizationsDelegate[WidgetsLocalizations]], dirty, state: _LocalizationsState#66a9d):
flutter: 'dart:_internal/runtime/libinternal_patch.dart': error: line 119 pos 1: native function
flutter: 'Internal_unsafeCast' (1 arguments) cannot be found
flutter: T unsafeCast<T>(Object v) native "Internal_unsafeCast";
flutter: ^

```
## Steps to Reproduce
Run this app on simulator. This error will show up.

##  FLUTTER Doctor Output
```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.6.0 at /Users/chetankaushik/Downloads/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
    • Android SDK at /Users/chetankaushik/Downloads/android-sdk-mac_x86-1.6_r1
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0-rc2
    • ANDROID_HOME = /Users/chetankaushik/Downloads/android-sdk-mac_x86-1.6_r1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700

[✓] Connected devices (2 available)
    • ONEPLUS A5000        • a92b077a                             • android-arm64 • Android 8.1.0 (API 27)
    • iPad Pro (10.5-inch) • 7E9350D8-BB2B-4A51-B5C7-D7F87DA37B01 • ios           • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Is this still an issue?
Can you provide more information about how to reproduce?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
