### ISSUE TITLE
Widget test "'_currentFakeAsync != null': is not true."

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#21368]
In one test I use

```dart
  group('widget', () {
    testWidgets(
      'create',
      (tester) async {
        await tester.runAsync(() async {
```
and now it fails with the exception below.
This test succeeded recently. I'll investigate more to find out when it started failing.

I have quite a similar test in the same file without `tester.runAsync` that succeeds. 
I don't need `tester.runAsync` there because it uses

```dart
          await expectLater(
            find.byKey(globalKey),
            matchesGoldenFile(
                '$fullTestName.2.contacts_loaded.${Platform.operatingSystem}'
                '.png'),
          );
```

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
#2      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:163:18)
#3      CachingAssetBundle.loadStructuredData (package:flutter/src/services/asset_bundle.dart:184:5)
#4      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:175:18)
#5      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:5)
#6      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:581:20)
#7      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:556:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3779:12)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
#20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
#21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
#29     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
#30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
#31     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
#32     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1659:58)
#33     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:728:15)
#34     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1659:13)
#35     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#37     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
#38     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
#39     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
#40     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#45     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#47     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#68     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#70     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#72     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
#84     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
#85     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
#86     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
#87     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:794:23)
#88     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#89     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#90     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#91     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:705:9)
#94     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#95     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:692:27)
#96     WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:247:47)
#99     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#100    WidgetTester.pump (package:flutter_test/src/widget_tester.dart:247:27)
#101    main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/test/widgets/screens/invite_people_screen/invite_people_screen_test.dart:94:24)
(elided 17 frames from package dart:async and package stack_trace)

The test description was:
create
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: The method 'fromNowBy' was called on null.
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 911 pos 12: '_currentFakeAsync !=
null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:911:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:557:5)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:540:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:884:24)
#13     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:881:15)
#14     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:71:22)
#15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#16     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#21     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
#22     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:166:33)
#27     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#28     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#42     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#43     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 30 frames from class _AssertionError, class _FakeAsync, package dart:async, and package
stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: create
```

```
 (dart2) $ flutter doctor -v
[✓] Flutter (Channel master, v0.7.6-pre.27, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.7.6-pre.27 at /Users/zoechi/flutter/flutter
    • Framework revision 2369087668 (72 minutes ago), 2018-09-03 11:39:32 -0400
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (2 available)
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!
```
Same with
```
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-AT)
```

**Comment by zoechi** [comment]
Skipping this test makes the following tests fail. 
Perhaps it's related to #18507 but the first test reliably fails.

**Comment by zoechi** [comment]
There is no error when I run the tests with `flutter run -t test/...` in the emulator,
but that was already the case before I added `await tester.runAsync(() async {`
I added `runAsync` because streams didn't emit events when running with `flutter test ...`

**Comment by maheshmnj** [comment]
I am getting the same issue ,When I am pumping a widget (which makes a get request and shows loading widget while snapshot is null and then loads the widget)

**Comment by iapicca** [comment]
Hi @zoechi 
testing the code below with the latest master

<details><summary>widget</summary>

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() async {

    int _c = _counter +=1;
    setState(() => _counter = null);
    Future.delayed(const Duration(seconds: 10));  /// [<= change]
    setState(() => _counter = _c);

    // setState(() {
    //   _counter++;  
    // });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            _counter == null ? const CircularProgressIndicator() : /// [<= change]
             Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details><summary>test</summary>


```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:master/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.runAsync(() async {
      // Build our app and trigger a frame.
      await tester.pumpWidget(MyApp());

      // Verify that our counter starts at 0.
      expect(find.text('0'), findsOneWidget);
      expect(find.text('1'), findsNothing);

      // Tap the '+' icon and trigger a frame.
      await tester.tap(find.byIcon(Icons.add));
      await tester.pumpAndSettle(
          Duration(seconds: 5), EnginePhase.build, Duration(minutes: 1));

      // Verify that our counter has incremented.
      expect(find.text('0'), findsNothing);
      expect(find.text('1'), findsOneWidget);
    });
  });
}

```


</details>

<details><summary>logs</summary>

```bash
 nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter_master test -v                                                                               ✔  2743  10:40:35
[ +184 ms] executing: [/Users/nevercode/development/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] e64fe11542238376fdfbf351d81e22d08296da45
[        ] executing: [/Users/nevercode/development/flutter_master/] git tag --contains HEAD
[ +100 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] executing: [/Users/nevercode/development/flutter_master/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +35 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-5.0.pre-17-ge64fe1154
[  +16 ms] executing: [/Users/nevercode/development/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/nevercode/development/flutter_master/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [/Users/nevercode/development/flutter_master/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +14 ms] executing: sw_vers -productName
[  +30 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +26 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.5
[        ] executing: sw_vers -buildVersion
[  +23 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19F101
[  +74 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +323 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +67 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [-r, compact, --concurrency=2, --, /Users/nevercode/Desktop/projects/master/test/widget_test.dart]
00:00 +0: loading /Users/nevercode/Desktop/projects/master/test/widget_test.dart                                                                                                 [ +293 ms] test 0: starting test /Users/nevercode/Desktop/projects/master/test/widget_test.dart
[  +21 ms] test 0: starting shell process
[  +12 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/nevercode/Desktop/projects/master
[   +5 ms] Compiler will use the following file as its incremental dill file:
/var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_compiler.omYU7t/output.dill
[   +7 ms] Listening to compiler controller...
[   +8 ms] Compiling file:///var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_listener.b5jeJe/listener.dart
[  +21 ms] /Users/nevercode/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_compiler.omYU7t/output.dill --packages /Users/nevercode/Desktop/projects/master/.packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --initialize-from-dill /Users/nevercode/Desktop/projects/master/build/testfile.dill.track.dill
[  +35 ms] <- compile file:///var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_listener.b5jeJe/listener.dart
00:03 +0: loading /Users/nevercode/Desktop/projects/master/test/widget_test.dart                                                                                                 [+2848 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_listener.b5jeJe/listener.dart took 2906ms
[   +2 ms] /Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode --verify-entry-points
--enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts
--packages=/Users/nevercode/Desktop/projects/master/.packages
/var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_listener.b5jeJe/listener.dart.dill
[   +2 ms] Using this directory for fonts configuration: /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_fonts.GwveZ7
[   +8 ms] test 0: awaiting initial result for pid 10942
[ +885 ms] test 0: process with pid 10942 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 10942
00:05 +1: Counter increments smoke test                                                                                                                                          [+1279 ms] test 0: process with pid 10942 no longer needed by test harness
[        ] test 0: cleaning up...
[   +1 ms] test 0: ensuring end-of-process for shell
[  +18 ms] test 0: deleting temporary directory
[   +4 ms] test 0: shutting down test harness socket server
[   +6 ms] test 0: finished
00:05 +1: All tests passed!
[  +23 ms] Deleting /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_compiler.omYU7t...
[   +3 ms] killing pid 10933
[  +37 ms] Deleting /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.5OJRM6/flutter_test_fonts.GwveZ7...
[   +6 ms] test package returned with exit code 0
[  +18 ms] "flutter test" took 6,009ms.
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.17, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.17 at /Users/nevercode/development/flutter_master
    • Framework revision e64fe11542 (7 hours ago), 2020-07-23 18:11:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

the issue doesn't seem to occur,
does this code represent the issue you are describing?
Thank you
