### ISSUE TITLE
If the address of the picture is not accessible, the program must be wrong.

### ISSUE THREAD

**Issue by FirePrayer** [flutter/flutter#21414]
## Steps to Reproduce

**If the address of the picture is not accessible, the program must be wrong.**

`class ImageDemo extends StatelessWidget
{
    @override
    Widget build(BuildContext context)
    {
        // TODO: implement build
        //http://www.zwdu.com/files/article/image/14/14507/14507s.jpg
        //http://www.zwdu.com/files/article/image/10/10892/10892s.jpg
        return Container(child: Center(child: Image.network("http://www.zwdu.com/files/article/image/10/10892/10892s.jpg"),),);
    }
}`

## Logs

```
I/flutter ( 9065): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 9065): The following RedirectException was thrown resolving an image codec:
I/flutter ( 9065): Redirect loop detected
I/flutter ( 9065): 
I/flutter ( 9065): When the exception was thrown, this was the stack:
I/flutter ( 9065): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:488:41)
I/flutter ( 9065): <asynchronous suspension>
I/flutter ( 9065): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:469:14)
I/flutter ( 9065): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
I/flutter ( 9065): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
I/flutter ( 9065): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
I/flutter ( 9065): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 9065): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
I/flutter ( 9065): #7      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:581:20)
I/flutter ( 9065): #8      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:556:5)
I/flutter ( 9065): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3813:12)
I/flutter ( 9065): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #94     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #106    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #116    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4911:32)
I/flutter ( 9065): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #119    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter ( 9065): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #135    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #141    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #145    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #154    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #164    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #170    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #197    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4806:14)
I/flutter ( 9065): #198    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #201    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #202    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #203    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #206    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #208    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #209    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #210    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #216    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #217    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #223    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #225    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #227    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #231    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #233    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #239    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #240    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #241    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #242    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #243    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #244    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #246    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #247    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #248    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #249    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #250    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
I/flutter ( 9065): #252    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
I/flutter ( 9065): #253    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3668:5)
I/flutter ( 9065): #254    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3815:11)
I/flutter ( 9065): #255    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3663:5)
I/flutter ( 9065): #256    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 9065): #257    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 9065): #258    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
I/flutter ( 9065): #259    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
I/flutter ( 9065): #260    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
I/flutter ( 9065): #261    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter ( 9065): #262    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
I/flutter ( 9065): #263    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
I/flutter ( 9065): #264    runApp (package:flutter/src/widgets/binding.dart:728:7)
I/flutter ( 9065): #265    main (file:///E:/FlutterProjects/flutter_test03/lib/main.dart:11:5)
I/flutter ( 9065): #266    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 9065): #267    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9065): 
I/flutter ( 9065): Image provider: NetworkImage("http://www.zwdu.com/files/article/image/10/10892/10892s.jpg", scale:
I/flutter ( 9065): 1.0)
I/flutter ( 9065): Image key: NetworkImage("http://www.zwdu.com/files/article/image/10/10892/10892s.jpg", scale: 1.0)
I/flutter ( 9065): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
[√] Flutter (Channel master, v0.7.6-pre.44, on Microsoft Windows [Version 10.0.17134.228], locale zh-CN)
    • Flutter version 0.7.6-pre.44 at F:\GitHub\flutter
    • Framework revision 88c94f57c7 (3 hours ago), 2018-09-04 17:05:30 -0700
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = D:\android-sdk-windows
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • MI 5 • cb73120 • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/45082479-b41dd780-b0f9-11e8-8ab2-2ea28437344e.png)

**Comment by zoechi** [comment]
I can't see anything the development team could do here. This issue is not related to Flutter in any way.
Chrome shows the same result. 
What do you expect the Flutter team to do?

Closing tentatively.
I'll reopen if it turns out there actually is some issue with Flutter.

**Comment by zoechi** [comment]
> don't let it collapse on IOS.

what do you mean by that?

**Comment by FirePrayer** [comment]
In the previous version will crash, just tested the only error message, will not crash.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/pull/18424 should allow to add error handling to prevent exceptions but I haven't tried it yet myself.
