### ISSUE TITLE
Scary error after running on Nexus 5

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2144]
I clicked the run button in Atom, and this is what I saw:

```
[iPhone 6s] 	)
[iPhone 6s] ids_simd: (Error) IDSSimulatorSupport: <IDSSimSupportLocalServer.m __68-[IDSSimSupportLocalServer setNetworkSimulation:enabled:completion:]_block_invoke:561> message send of data {
[iPhone 6s] 	    ControlCmd = SetNetSimulationEnabledCmd;
[iPhone 6s] 	    Enabled = 0;
[iPhone 6s] 	    ServiceName = "com.apple.private.alloy.sockpuppet.classd";
[iPhone 6s] 	} failed with error Error Domain=com.apple.idssimualtorsupport.errors Code=2 "(null)" UserInfo={NSUnderlyingError=0x7fa4e27085c0 {Error Domain=NSMachErrorDomain Code=268435459 "(ipc/send) invalid destination port"}}
[iPhone 6s] sharingd: 17:10:48.510 : Failed to send SDURLSessionProxy startup message, error Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x7f9e884131f0 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}
[iPhone 6s] 		"XPCErrorDescription" => <string: 0x10a1f2ef0> { length = 22, contents = "Connection interrupted" }
[iPhone 6s] 	}>
[iPhone 6s] fileproviderd: Communications error: <OS_xpc_error: <error: 0x10d264b40> { count = 1, contents =
[iPhone 6s] 		"XPCErrorDescription" => <string: 0x10d264ef0> { length = 22, contents = "Connection interrupted" }
[iPhone 6s] 	}>
[iPhone 6s] 		"XPCErrorDescription" => <string: 0x113a67ef0> { length = 22, contents = "Connection interrupted" }
[iPhone 6s] 	}>
[iPhone 6s] CoreSimulatorBridge: Communications error: <OS_xpc_error: <error: 0x106a30b40> { count = 1, contents =
[iPhone 6s] 		"XPCErrorDescription" => <string: 0x106a30ef0> { length = 22, contents = "Connection interrupted" }
[iPhone 6s] 	}>
[iPhone 6s] SpringBoard: Communications error: <OS_xpc_error: <error: 0x110deab40> { count = 1, contents =
[iPhone 6s] 		"XPCErrorDescription" => <string: 0x110deaef0> { length = 22, contents = "Connection interrupted" }
[iPhone 6s] 	}>
[iPhone 6s] routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
[iPhone 6s] routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
[iPhone 6s] syslogd: ASL Sender Statistics
[Nexus 5] --------- beginning of system
[Nexus 5] --------- beginning of main
[Nexus 5] I/flutter : Could not start Observatory HTTP server:
[Nexus 5] I/flutter : SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 8181
[Nexus 5] I/flutter : #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
[Nexus 5] I/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1137)
[Nexus 5] I/flutter : #2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
[Nexus 5] I/flutter : #3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
[Nexus 5] I/flutter : #4      _Future._completeWithValue (dart:async/future_impl.dart:424)
[Nexus 5] I/flutter : #5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
[Nexus 5] I/flutter : #6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[Nexus 5] I/flutter : #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[Nexus 5] I/flutter : #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[Nexus 5] I/flutter : #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[Nexus 5] I/flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[Nexus 5] I/flutter : 
```

**Comment by devoncarew** [comment]
Definitely an error on the android device. Not sure if it's the same things on the simulator. But they'll both be trying to grab the same port.

**Comment by abarth** [comment]
I believe this is fixed with the removal of the updater service.
