### ISSUE TITLE
TextField issue: App crash when user click on textfield

### ISSUE THREAD

**Issue by mahmed8003** [flutter/flutter#21449]
There is strange situation, when I enter the value for Phone number after completing the above fields then app crashes. All the text fields are right aligned. And keyboardType = TextInputType.text. But for phone number field keyboardType is TextInputType.phone.
If I change the keyboardType: to TextInputType.text then it works fine.

![screenshot_2018-09-05-23-19-33-088](https://user-images.githubusercontent.com/1140343/45113283-5faf4200-b163-11e8-83d7-034799b2354c.jpeg)

Error: 
```
Fatal Exception: java.lang.IndexOutOfBoundsException: replace (0 ... -1) has end before start
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1258)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
       at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:163)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:440)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by slightfoot** [comment]
Caused by this PR: https://github.com/flutter/engine/pull/6113
to fix this issue: https://github.com/flutter/flutter/issues/21058

**Comment by jonahwilliams** [comment]
cc @jslavitz

**Comment by slightfoot** [comment]
@jonahwilliams  PR is in flutter/engine#6171 .. feel free to LGTM 😉
