### ISSUE TITLE
Adding some plugins to a Flutter module causes the whole app to fail to build

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#21473]
## Steps to Reproduce

1. Check out https://github.com/mjohnsullivan/dof
2. Build with Android Studio, see that everything runs as expected.
3. Edit flutter_dof/pubspec.yaml to add `fluwx: ^0.1.3` in the `dependencies` section.
4. run `flutter packages get` while standing in the flutter_dof directory.
5. Attempt to run the Android program in Android Studio. Cry. (Kidding. Actually you'll see `Error:Failed to notify project evaluation listener.`) 

Now, technically to *use* this plugin I need to make some changes to the build.gradle files and such. You can see those changes [here](https://github.com/efortuna/insta_flutter/commit/82f533177fa63e8e8fb1535a0ae2b44788aef06c) and [here](https://github.com/efortuna/insta_flutter/commit/0791817024dc70a3768c3aba3961887305f4c61d),
but that shouldn't matter. I think adding a dependency, regardless of whether it's used or not shouldn't prevent me from building the app. 

```
```

```
[✓] Flutter (Channel master, v0.7.6-pre.56, on Linux, locale en_US.UTF-8)
    • Flutter version 0.7.6-pre.56 at /usr/local/google/home/efortuna/googleio/flutter
    • Framework revision 409baff3ac (4 hours ago), 2018-09-05 21:31:29 +0100
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/efortuna/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/intellij-ce-2018.1
    • Flutter plugin version 27.0.2
    • Dart plugin version 181.4892.1

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Pixel 2 XL • 711KPAE0891080 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by jason-simmons** [comment]
I was able to build this app by changing `ext.kotlin_version` in `android_dof/build.gradle` to `1.2.60`

The build had been failing due to an exception in the Kotlin Gradle plugin:
```
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:86)
        ...
Caused by: java.lang.AbstractMethodError
        at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.resolveSubpluginArtifacts(KotlinPlugin.kt:776)
        ...
```

The [Fluwx build script](https://github.com/OpenFlutter/fluwx/blob/master/android/build.gradle) specifies Kotlin version `1.2.60`.  Apparently the app's main script needs to use the same version.

**Comment by efortuna** [comment]
Thank you, @jason-simmons, that fixed our problem! Is this a tooling issue we can improve to better surface that error when building in Android Studio? cc @devoncarew @stevemessick

**Comment by matthew-carroll** [comment]
Note after chatting with @jason-simmons:  I think it is probably OK to ship with this issue for Add2App since, I think, the Kotlin version would be specified within the existing Android app and therefore the developer could change that just as Jason did here and they'll be OK.

However, this issue could be more problematic for a standard project with a generated host app because the host app can't be edited without converting to a non-generated form.  This might still be acceptable for the time being if this situation does not arise very often.  However, if this situation is at all commonplace then I think we need to do something to handle generated host apps.

**Comment by efortuna** [comment]
okay, sounds good. Feel free to close then. My side of the issue is solved. (I just didn't see the error, because AS hid it a little better than from the command line)

**Comment by matthew-carroll** [comment]
I'll leave the issue open until I'm sure the Add2App project structure changes aren't adversely impacted by this.

**Comment by ThinkDigitalRepair** [comment]
> I was able to build this app by changing `ext.kotlin_version` in `android_dof/build.gradle` to `1.2.60`
@jason-simmons where is this file located? I have a different project I'm trying to build and I don't see this folder

**Comment by ThinkDigitalRepair** [comment]
Oh, it's just the regular _YOUR_PROJECT_/android/build.gradle file

**Comment by matanlurey** [comment]
Closing as stale. Feel free to file a new issues if the problem persists.
