### ISSUE TITLE
Everytime I try running flutter I get an OS error

### ISSUE THREAD

**Issue by nikhileshp** [flutter/flutter#21495]
Flutter is always struggling to upgrade its packages. 

```
C:\flutter\flutter_app>flutter packages upgrade -v
fatal: Not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[  +31 ms] executing: [C:\Users\Nick\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Users\Nick\flutter\] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[        ] executing: [C:\Users\Nick\flutter\] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[   +9 ms] https://github.com/flutter/flutter.git
[        ] executing: [C:\Users\Nick\flutter\] git log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 3b309bda072a6b326e8aa4591a5836af600923ce
[   +7 ms] executing: [C:\Users\Nick\flutter\] git log -n 1 --pretty=format:%ar
[  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 9 days ago
[        ] executing: [C:\Users\Nick\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +41 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.7.3-0-g3b309bda0
[ +170 ms] Running "flutter packages upgrade" in flutter_app...
[  +10 ms] executing: [C:\flutter\flutter_app\] C:\Users\Nick\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose upgrade --no-precompile
[+16555 ms] Cannot open file, path = '.\pubspec.lock' (OS Error: Access is denied.
[   +1 ms] , errno = 5)
[  +46 ms] Running "flutter packages upgrade" in flutter_app... (completed)
[  +15 ms] "flutter upgrade" took 16,687ms.
pub upgrade failed (66)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

flutter doctor -v

```
C:\flutter\flutter_app>flutter doctor -v
fatal: Not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.7.3 at C:\Users\Nick\flutter
    • Framework revision 3b309bda07 (9 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Nick\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Can you please add the output of `git --version`?

**Comment by zoechi** [comment]
Cross-link https://stackoverflow.com/questions/52202923/flutter-running-flutter-fails-could-not-find-a-file-named-pubspec-yaml-upd?noredirect=1#comment91358543_52202923

**Comment by nikhileshp** [comment]
The git version

```
C:\flutter\flutter_app>git --version
git version 2.14.1.windows.1
```

**Comment by nikhileshp** [comment]
Do you think it could be a problem with git? Everytime I type a command I get fatal: Not a git repository (or any of the parent directories): .git

**Comment by zoechi** [comment]
That's what made me suspicious. 
You could try updating. The latest version is 2.18.0

**Comment by nikhileshp** [comment]
I just did that. 
I'm getting my version as 
`C:\flutter>git --version
git version 1.9.4.msysgit.2
`
But still the error is the same

**Comment by nikhileshp** [comment]
I updated my version to 2.18 but the problem still persists

```
C:\>git --version
git version 2.18.0.windows.1

```

**Comment by nikhileshp** [comment]
Yes, I am positive! I got rid of it a while ago

**Comment by nikhileshp** [comment]
I found a temporary solution. When I run the same command on Power Shell as an administrator it doesn't show any error.

**Comment by zoechi** [comment]
@nikhileshp running as admin should not be necessary. 
There is some issue with permission settings.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by tl-yang** [comment]
Are you using a docker image? 
When I use [cirrusci/flutter](https://hub.docker.com/r/cirrusci/flutter) the issue occured but using  [adamantium/flutter](https://hub.docker.com/r/adamantium/flutter) everything worked fine!
