### ISSUE TITLE
assert(children != null), in sliver.dart

### ISSUE THREAD

**Issue by Piyush-Pragyan** [flutter/flutter#21503]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Piyush-Pragyan** [comment]
When I trying to write a flutter application, this issue came in the Run console.
I/flutter (12349): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12349): The following assertion was thrown building HomePage(dirty):
I/flutter (12349): 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 253 pos 15: 'children != null': is
I/flutter (12349): not true.
I/flutter (12349): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12349): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12349): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12349):   https://github.com/flutter/flutter/issues/new
I/flutter (12349): When the exception was thrown, this was the stack:
I/flutter (12349): #2      new SliverChildListDelegate (package:flutter/src/widgets/sliver.dart:253:15)
I/flutter (12349): #3      new GridView.count (package:flutter/src/widgets/scroll_view.dart:1135:31)
I/flutter (12349): #4      HomePage.build (package:Shrine/home.dart:85:22)
I/flutter (12349): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3708:28)
I/flutter (12349): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (12349): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter (12349): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter (12349): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter (12349): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter (12349): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter (12349): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter (12349): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter (12349): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter (12349): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter (12349): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter (12349): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter (12349): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (12349): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (12349): #60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (12349): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (12349): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (12349): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12349): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12349): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (12349): #67     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (12349): #68     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (12349): #69     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
I/flutter (12349): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (12349): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 3 of 406 libraries in 938ms.
Also I uploading the results of the command 'flutter doctor -v'
Flutter (Channel beta, v0.6.0, on Linux, locale en_IN.UTF-8)
    • Flutter version 0.6.0 at /home/piyush/development/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/piyush/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /snap/android-studio/53/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /snap/android-studio/53/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Redmi Note 3 • cbce2295 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
Please help me..!!!!

**Comment by zoechi** [comment]
Can you reproduce in a minimal example?

**Comment by Piyush-Pragyan** [comment]
Can you explain what are you saying..??

**Comment by zoechi** [comment]
Please check https://stackoverflow.com/help/mcve 
I was asking for code that allows to reproduce the problem.
