### ISSUE TITLE
Failed assertion 'constraints.hasBoundedWidth': is not true.

### ISSUE THREAD

**Issue by apatil88** [flutter/flutter#21511]
```
I/flutter (12635): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12635): The following assertion was thrown during performLayout():
**I/flutter (12635): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1597 pos 16:
I/flutter (12635): 'constraints.hasBoundedWidth': is not true.**
I/flutter (12635):
I/flutter (12635): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12635): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12635): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12635):   https://github.com/flutter/flutter/issues/new
I/flutter (12635):
I/flutter (12635): When the exception was thrown, this was the stack:
I/flutter (12635): #2      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1597:16)
I/flutter (12635): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #20     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12635): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (12635): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (12635): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12635): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #33     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1193:11)
I/flutter (12635): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #35     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12635): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #44     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1193:11)
I/flutter (12635): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #46     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12635): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #50     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter (12635): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #52     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (12635): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #54     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (12635): #55     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1649:12)
I/flutter (12635): #56     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1612:20)
I/flutter (12635): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (12635): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #74     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (12635): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #76     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter (12635): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (12635): #78     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (12635): #79     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter (12635): #80     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (12635): #81     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (12635): #82     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
I/flutter (12635): #83     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
I/flutter (12635): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:276:19)
I/flutter (12635): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (12635): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (12635): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12635): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12635): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (12635): #90     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (12635): #91     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (12635): (elided 2 frames from class _AssertionError)
I/flutter (12635):
I/flutter (12635): The following RenderObject was being processed when the exception was fired:
I/flutter (12635):   RenderShrinkWrappingViewport#90ae9 relayoutBoundary=up36 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12635):   creator: ShrinkWrappingViewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#d4c26] ← Semantics ←
I/flutter (12635):   Listener ← _GestureSemantics ←
I/flutter (12635):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#45ce0] ←
I/flutter (12635):   _ExcludableScrollSemantics-[GlobalKey#75f6f] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (12635):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (12635):   parentData: <none> (can use size)
I/flutter (12635):   constraints: BoxConstraints(unconstrained)
I/flutter (12635):   size: MISSING
I/flutter (12635):   axisDirection: down
I/flutter (12635):   crossAxisDirection: right
I/flutter (12635):   offset: ScrollPositionWithSingleContext#6d1e9(offset: 0.0, range: null..null, viewport: null,
I/flutter (12635):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#021a4,
I/flutter (12635):   ScrollDirection.idle)
I/flutter (12635): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12635):   RenderSliverPadding#d9b78 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12635):     RenderSliverList#941c4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12635): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#90ae9 relayoutBoundary=up36 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1a6be relayoutBoundary=up35 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#49250 relayoutBoundary=up34 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#7d492 relayoutBoundary=up33 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#0cb78 relayoutBoundary=up32 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: _RenderExcludableScrollSemantics#3ab41 relayoutBoundary=up31 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#0b908 relayoutBoundary=up30 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#359d2 relayoutBoundary=up29 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#3e0af relayoutBoundary=up28 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPadding#6bb68 relayoutBoundary=up27 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderFlex#a7295 relayoutBoundary=up26 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderFlex#1330c relayoutBoundary=up25 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPadding#70522 relayoutBoundary=up24 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#d0185 relayoutBoundary=up23 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#c3e35 relayoutBoundary=up22 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#5e3da relayoutBoundary=up21 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPadding#4d178 relayoutBoundary=up20 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#6ffed relayoutBoundary=up19 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#d928e relayoutBoundary=up18 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#d8b99 relayoutBoundary=up17 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#63d85 relayoutBoundary=up16 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPadding#8308e relayoutBoundary=up15 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 441 pos 12: 'child.hasSize': is not true.
I/flutter (12635): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (12635): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#6436b relayoutBoundary=up11 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#787ab relayoutBoundary=up10 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#8c736 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#003c8 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#33177 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: _RenderExcludableScrollSemantics#eaa60 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d0f86 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#cefe8 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d28e6 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderPadding#afa24 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (12635): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d28e6 relayoutBoundary=up3 NEEDS-PAINT
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Can you please provide information how to reproduce?
Ideally a minimal running code example.

**Comment by apatil88** [comment]
Output of flutter doctor -v:

[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 0.6.0 at C:\Softwares\flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\apatil\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Users\apatil\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.26.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by chakrihacker** [comment]
here is the code
```
new SingleChildScrollView(
        child: new ListView(
      shrinkWrap: true,
      children: <Widget>[
        new Image.asset('assets/card-front.png'),
        new ListView(
          scrollDirection: Axis.horizontal,
          shrinkWrap: true,
          children: <Widget>[
            new TextField(),
          ],
        )
      ],
    ))
```

**Comment by zoechi** [comment]
@chakrihacker you mean you get the same error with this code? Why are you wrapping `ListView` in a `SingleChildScrollView`?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by chakrihacker** [comment]
ok sorry that was wrong code

**Comment by zoechi** [comment]
This issue is long closed.
If you think this is a Flutter issue, please create a new issue with properly filled issue template. 
You can add a link to this issue if you think it's relevant.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
