### ISSUE TITLE
 'package:flutter/src/rendering/object.dart': Failed assertion: line 3118 pos 12: I/flutter (20913): '!node.isInvisible': is not true.

### ISSUE THREAD

**Issue by JoshRice1** [flutter/flutter#21526]
Please let me know if you would like the project nothing special just basic app with the start of firebase auth being added.  I did rename the package due to a typo which might have caused the issue

I/flutter (20913): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20913): The following assertion was thrown during a scheduler callback:
I/flutter (20913): 'package:flutter/src/rendering/object.dart': Failed assertion: line 3118 pos 12:
I/flutter (20913): '!node.isInvisible': is not true.
I/flutter (20913): 
I/flutter (20913): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20913): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20913): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20913):   https://github.com/flutter/flutter/issues/new
I/flutter (20913): 
I/flutter (20913): When the exception was thrown, this was the stack:
I/flutter (20913): #2      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart)
I/flutter (20913): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:153:12)
I/flutter (20913): #4      Iterable.single (dart:core/iterable.dart:567:13)
I/flutter (20913): #5      RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2282:96)
I/flutter (20913): #6      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:887:16)
I/flutter (20913): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
I/flutter (20913): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (20913): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (20913): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (20913): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (20913): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (20913): #14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (20913): #15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (20913): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (20913): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (20913): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by zoechi** [comment]
Looks like a dup of #17148
More details about how to reproduce would be very valueable.

> if you would like the project nothing special just basic app

That would be great (ideally published to GitHub).
