### ISSUE TITLE
When trying to pick an image using image_picker plugin and dropbox as a source in gallery, a fatal exception occurs

### ISSUE THREAD

**Issue by gtselos** [flutter/flutter#21547]
When image_picker is used to pick an image from gallery and the source of the image is dropbox, the following error appears:

```
java.lang.IllegalArgumentException: column '_data' does not exist
```
```
E/AndroidRuntime( 2015): FATAL EXCEPTION: main
E/AndroidRuntime( 2015): Process: io.flutter.plugins.imagepicker.example, PID: 2015
E/AndroidRuntime( 2015): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.dropbox.android.FileCache/filecache/16c7b0bf-804e-4677-ace4-95b688faf932 typ=image/jpeg flg=0x3 }} to activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime( 2015): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4355)
E/AndroidRuntime( 2015): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4398)
E/AndroidRuntime( 2015): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 2015): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
E/AndroidRuntime( 2015): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 2015): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 2015): 	at android.app.ActivityThread.main(ActivityThread.java:6665)
E/AndroidRuntime( 2015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2015): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 2015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
E/AndroidRuntime( 2015): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime( 2015): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:339)
E/AndroidRuntime( 2015): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
E/AndroidRuntime( 2015): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:119)
E/AndroidRuntime( 2015): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:101)
E/AndroidRuntime( 2015): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime( 2015): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime( 2015): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime( 2015): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime( 2015): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:146)
E/AndroidRuntime( 2015): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:139)
E/AndroidRuntime( 2015): 	at android.app.Activity.dispatchActivityResult(Activity.java:7317)
E/AndroidRuntime( 2015): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4351)
E/AndroidRuntime( 2015): 	... 9 more
```

flutter doctor output:
```
flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.5.1 at C:\Users\George T\space\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\George T\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • MI 6 • 18ba4f8 • android-arm64 • Android 8.0.0 (API 26)
```
I created a PR with a possible fix for this issue.

**Comment by zoechi** [comment]
Similar to #17950
