### ISSUE TITLE
flutter doctor not work

### ISSUE THREAD

**Issue by RealMoMo** [flutter/flutter#21544]
## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception
```
FileSystemException: FileSystemException: Deletion failed, path = 'D:\soft\flutter_windows_v0.3.2-beta\flutter\bin\cache\artifacts\engine' (OS Error: 拒绝访问。
, errno = 5)
```
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:207:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:256:16)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:214:26)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:339:19)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:290:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:281:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:109:11)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50:10)
#36     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#37     main (file:///D:/soft/flutter_windows_v0.3.2-beta/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale zh-CN)
    • Flutter version 0.7.3 at D:\soft\flutter_windows_v0.3.2-beta\flutter
    • Framework revision 3b309bda07 (10 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[!] Android toolchain - develop for Android devices
    • Android SDK at D:\soft\adt\adt-bundle-windows-x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • ANDROID_HOME = D:\soft\adt\adt-bundle-windows-x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk
    ✗ Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.1)
    • Android Studio at D:\soft\Android
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at D:\soft\IntelliJ IDEA Community Edition 2017.2.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Can you please try
```
git clean -xfd
```
in `D:\soft\flutter_windows_v0.3.2-beta\flutter`
and then try `flutter doctor` again?

**Comment by zoechi** [comment]
Seems you components of the Android SDK essential for Flutter are not installed on your system.

In Android Studio open Menu `Tools` > `SDK Manager` choose tab `SDK Tools`
check `Android SDK Build-Tools`, `Android SDK Platform-Tools`, `Android SDK Tools` and click `[OK]`.
