### ISSUE TITLE
Error happened on hot reloading the default Flutter app on Android Studio.

### ISSUE THREAD

**Issue by anindyamanna** [flutter/flutter#21546]
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 3721): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3721): The following assertion was thrown building _CupertinoBackGestureDetector<dynamic>(state:
I/flutter ( 3721): _CupertinoBackGestureDetectorState<dynamic>#25ca1):
I/flutter ( 3721): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1785 pos 12: '() {
I/flutter ( 3721):       final AbstractNode parent = this.parent;
I/flutter ( 3721):       if (parent is RenderObject)
I/flutter ( 3721):         return parent._needsCompositing;
I/flutter ( 3721):       return true;
I/flutter ( 3721):     }()': is not true.
I/flutter ( 3721): 
I/flutter ( 3721): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3721): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3721): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3721):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3721): 
I/flutter ( 3721): When the exception was thrown, this was the stack:
I/flutter ( 3721): #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart:1785:12)
I/flutter ( 3721): #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1225:7)
I/flutter ( 3721): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2654:11)
I/flutter ( 3721): #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
I/flutter ( 3721): #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1070:11)
I/flutter ( 3721): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2649:7)
I/flutter ( 3721): #8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4681:18)
I/flutter ( 3721): #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
I/flutter ( 3721): #10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2986:5)
I/flutter ( 3721): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2911:18)
I/flutter ( 3721): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 3721): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #15     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
I/flutter ( 3721): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 3721): #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 3721): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 3721): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 3721): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 3721): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 3721): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 3721): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 3721): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 3721): #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 3721): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 3721): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter ( 3721): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 3721): #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 3721): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 3721): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 3721): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 3721): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 3721): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 3721): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 3721): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 3721): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #69     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 3721): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 3721): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 3721): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #79     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 3721): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 3721): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #85     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 3721): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 3721): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 3721): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 3721): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 3721): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 3721): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 3721): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3721): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3721): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3721): #96     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3721): #97     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3721): #98     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 3721): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 3721): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
I/chatty  ( 3721): uid=10083(com.anindya.flutterapp) Thread-2 identical 2 lines
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1084 pos 12: 'child.parentData != null': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 3721): Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#6f321 NEEDS-PAINT DETACHED
I/flutter ( 3721): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#7f915 NEEDS-PAINT DETACHED
I/flutter ( 3721): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#f639f NEEDS-PAINT DETACHED
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 3721): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 3721): Another exception was thrown: RenderBox was not laid out: RenderFractionalTranslation#f639f DETACHED
Reloaded 0 of 406 libraries in 694ms.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

#19331 looks similar

**Comment by anindyamanna** [comment]
`flutter doctor -v`  output:
```
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.7.3 at C:\Users\Anindya\AndroidStudioProjects\flutter projects\flutter
    • Framework revision 3b309bda07 (10 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Anindya\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by rhymes** [comment]
Happens to me as well when I press the "platform mode in Android Studio":

```text
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-IT)
    • Flutter version 0.8.2 at /Users/rhymes/Development/flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/rhymes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Nexus 5X • 01f7281523649944 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
Merging with #19331
