### ISSUE TITLE
Exception when unwinding a stack from a drawer item button push

### ISSUE THREAD

**Issue by pinkfish** [flutter/flutter#21553]
I think there is a race condition in here where the drawer is deleting but the animation callbacks are still in progress.

```
2018-09-07 09:55:06.726874-0700 Runner[38977:6722533] flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12:
2018-09-07 09:55:06.727150-0700 Runner[38977:6722533] flutter: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
2018-09-07 09:55:06.727322-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.727480-0700 Runner[38977:6722533] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2018-09-07 09:55:06.727673-0700 Runner[38977:6722533] flutter: more information in this error message to help you determine and fix the underlying cause.
2018-09-07 09:55:06.727834-0700 Runner[38977:6722533] flutter: In either case, please report this assertion by filing a bug on GitHub:
2018-09-07 09:55:06.728010-0700 Runner[38977:6722533] flutter:   https://github.com/flutter/flutter/issues/new
2018-09-07 09:55:06.728156-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.728279-0700 Runner[38977:6722533] flutter: When the exception was thrown, this was the stack:
2018-09-07 09:55:06.728412-0700 Runner[38977:6722533] flutter: #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3436:12)
2018-09-07 09:55:06.728586-0700 Runner[38977:6722533] flutter: #3      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
2018-09-07 09:55:06.728727-0700 Runner[38977:6722533] flutter: #4      DrawerControllerState._animationChanged (package:flutter/src/material/drawer.dart:215:5)
2018-09-07 09:55:06.728852-0700 Runner[38977:6722533] flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
2018-09-07 09:55:06.728999-0700 Runner[38977:6722533] flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:608:5)
2018-09-07 09:55:06.729120-0700 Runner[38977:6722533] flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:234:5)
2018-09-07 09:55:06.729264-0700 Runner[38977:6722533] flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-09-07 09:55:06.729385-0700 Runner[38977:6722533] flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
2018-09-07 09:55:06.729517-0700 Runner[38977:6722533] flutter: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
2018-09-07 09:55:06.729614-0700 Runner[38977:6722533] flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
2018-09-07 09:55:06.729773-0700 Runner[38977:6722533] flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
2018-09-07 09:55:06.729899-0700 Runner[38977:6722533] flutter: #13     _invoke1 (dart:ui/hooks.dart:142:13)
2018-09-07 09:55:06.730045-0700 Runner[38977:6722533] flutter: #14     _beginFrame (dart:ui/hooks.dart:113:3)
2018-09-07 09:55:06.730268-0700 Runner[38977:6722533] flutter: (elided 2 frames from class _AssertionError)
2018-09-07 09:55:06.730422-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.730542-0700 Runner[38977:6722533] flutter: The AnimationController notifying listeners was:
2018-09-07 09:55:06.730645-0700 Runner[38977:6722533] flutter:   AnimationController#c0898(◀ 0.098)
2018-09-07 09:55:06.730805-0700 Runner[38977:6722533] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2018-09-07 09:55:06.730932-0700 Runner[38977:6722533] flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
2018-09-07 09:55:06.731079-0700 Runner[38977:6722533] flutter: The following assertion was thrown while notifying listeners for AnimationController:
2018-09-07 09:55:06.731187-0700 Runner[38977:6722533] flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12:
2018-09-07 09:55:06.731289-0700 Runner[38977:6722533] flutter: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
2018-09-07 09:55:06.731385-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.731513-0700 Runner[38977:6722533] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2018-09-07 09:55:06.731632-0700 Runner[38977:6722533] flutter: more information in this error message to help you determine and fix the underlying cause.
2018-09-07 09:55:06.731750-0700 Runner[38977:6722533] flutter: In either case, please report this assertion by filing a bug on GitHub:
2018-09-07 09:55:06.731863-0700 Runner[38977:6722533] flutter:   https://github.com/flutter/flutter/issues/new
2018-09-07 09:55:06.731979-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.732101-0700 Runner[38977:6722533] flutter: When the exception was thrown, this was the stack:
2018-09-07 09:55:06.732221-0700 Runner[38977:6722533] flutter: #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3436:12)
2018-09-07 09:55:06.732340-0700 Runner[38977:6722533] flutter: #3      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
2018-09-07 09:55:06.732455-0700 Runner[38977:6722533] flutter: #4      DrawerControllerState._animationChanged (package:flutter/src/material/drawer.dart:215:5)
2018-09-07 09:55:06.732562-0700 Runner[38977:6722533] flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
2018-09-07 09:55:06.732703-0700 Runner[38977:6722533] flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:608:5)
2018-09-07 09:55:06.732833-0700 Runner[38977:6722533] flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:234:5)
2018-09-07 09:55:06.733076-0700 Runner[38977:6722533] flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-09-07 09:55:06.733210-0700 Runner[38977:6722533] flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
2018-09-07 09:55:06.733406-0700 Runner[38977:6722533] flutter: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
2018-09-07 09:55:06.733589-0700 Runner[38977:6722533] flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
2018-09-07 09:55:06.733814-0700 Runner[38977:6722533] flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
2018-09-07 09:55:06.733992-0700 Runner[38977:6722533] flutter: #13     _invoke1 (dart:ui/hooks.dart:142:13)
2018-09-07 09:55:06.734181-0700 Runner[38977:6722533] flutter: #14     _beginFrame (dart:ui/hooks.dart:113:3)
2018-09-07 09:55:06.734366-0700 Runner[38977:6722533] flutter: (elided 2 frames from class _AssertionError)
2018-09-07 09:55:06.734504-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.734749-0700 Runner[38977:6722533] flutter: The AnimationController notifying listeners was:
2018-09-07 09:55:06.734891-0700 Runner[38977:6722533] flutter:   AnimationController#c0898(◀ 0.051)
2018-09-07 09:55:06.735029-0700 Runner[38977:6722533] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2018-09-07 09:55:06.735177-0700 Runner[38977:6722533] flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
2018-09-07 09:55:06.735421-0700 Runner[38977:6722533] flutter: The following assertion was thrown while notifying listeners for AnimationController:
2018-09-07 09:55:06.735571-0700 Runner[38977:6722533] flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12:
2018-09-07 09:55:06.735753-0700 Runner[38977:6722533] flutter: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
2018-09-07 09:55:06.735936-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.736102-0700 Runner[38977:6722533] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2018-09-07 09:55:06.736267-0700 Runner[38977:6722533] flutter: more information in this error message to help you determine and fix the underlying cause.
2018-09-07 09:55:06.736498-0700 Runner[38977:6722533] flutter: In either case, please report this assertion by filing a bug on GitHub:
2018-09-07 09:55:06.736697-0700 Runner[38977:6722533] flutter:   https://github.com/flutter/flutter/issues/new
2018-09-07 09:55:06.736887-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.737086-0700 Runner[38977:6722533] flutter: When the exception was thrown, this was the stack:
2018-09-07 09:55:06.737422-0700 Runner[38977:6722533] flutter: #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3436:12)
2018-09-07 09:55:06.737664-0700 Runner[38977:6722533] flutter: #3      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
2018-09-07 09:55:06.737886-0700 Runner[38977:6722533] flutter: #4      DrawerControllerState._animationChanged (package:flutter/src/material/drawer.dart:215:5)
2018-09-07 09:55:06.738078-0700 Runner[38977:6722533] flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
2018-09-07 09:55:06.738306-0700 Runner[38977:6722533] flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:608:5)
2018-09-07 09:55:06.738497-0700 Runner[38977:6722533] flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:234:5)
2018-09-07 09:55:06.738769-0700 Runner[38977:6722533] flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-09-07 09:55:06.738998-0700 Runner[38977:6722533] flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
2018-09-07 09:55:06.739200-0700 Runner[38977:6722533] flutter: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
2018-09-07 09:55:06.739535-0700 Runner[38977:6722533] flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
2018-09-07 09:55:06.739839-0700 Runner[38977:6722533] flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
2018-09-07 09:55:06.740050-0700 Runner[38977:6722533] flutter: #13     _invoke1 (dart:ui/hooks.dart:142:13)
2018-09-07 09:55:06.740174-0700 Runner[38977:6722533] flutter: #14     _beginFrame (dart:ui/hooks.dart:113:3)
2018-09-07 09:55:06.740305-0700 Runner[38977:6722533] flutter: (elided 2 frames from class _AssertionError)
2018-09-07 09:55:06.740440-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.740602-0700 Runner[38977:6722533] flutter: The AnimationController notifying listeners was:
2018-09-07 09:55:06.740750-0700 Runner[38977:6722533] flutter:   AnimationController#c0898(◀ 0.032)
2018-09-07 09:55:06.740915-0700 Runner[38977:6722533] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2018-09-07 09:55:06.741072-0700 Runner[38977:6722533] flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
2018-09-07 09:55:06.741220-0700 Runner[38977:6722533] flutter: The following assertion was thrown while notifying listeners for AnimationController:
2018-09-07 09:55:06.741363-0700 Runner[38977:6722533] flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12:
2018-09-07 09:55:06.741497-0700 Runner[38977:6722533] flutter: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
2018-09-07 09:55:06.741630-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.741761-0700 Runner[38977:6722533] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2018-09-07 09:55:06.741920-0700 Runner[38977:6722533] flutter: more information in this error message to help you determine and fix the underlying cause.
2018-09-07 09:55:06.742051-0700 Runner[38977:6722533] flutter: In either case, please report this assertion by filing a bug on GitHub:
2018-09-07 09:55:06.742200-0700 Runner[38977:6722533] flutter:   https://github.com/flutter/flutter/issues/new
2018-09-07 09:55:06.742384-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.742558-0700 Runner[38977:6722533] flutter: When the exception was thrown, this was the stack:
2018-09-07 09:55:06.742717-0700 Runner[38977:6722533] flutter: #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3436:12)
2018-09-07 09:55:06.742858-0700 Runner[38977:6722533] flutter: #3      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
2018-09-07 09:55:06.742983-0700 Runner[38977:6722533] flutter: #4      DrawerControllerState._animationChanged (package:flutter/src/material/drawer.dart:215:5)
2018-09-07 09:55:06.743110-0700 Runner[38977:6722533] flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
2018-09-07 09:55:06.743266-0700 Runner[38977:6722533] flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:608:5)
2018-09-07 09:55:06.743427-0700 Runner[38977:6722533] flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:234:5)
2018-09-07 09:55:06.743577-0700 Runner[38977:6722533] flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-09-07 09:55:06.743705-0700 Runner[38977:6722533] flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
2018-09-07 09:55:06.743833-0700 Runner[38977:6722533] flutter: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
2018-09-07 09:55:06.743992-0700 Runner[38977:6722533] flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
2018-09-07 09:55:06.744172-0700 Runner[38977:6722533] flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
2018-09-07 09:55:06.744333-0700 Runner[38977:6722533] flutter: #13     _invoke1 (dart:ui/hooks.dart:142:13)
2018-09-07 09:55:06.744490-0700 Runner[38977:6722533] flutter: #14     _beginFrame (dart:ui/hooks.dart:113:3)
2018-09-07 09:55:06.744661-0700 Runner[38977:6722533] flutter: (elided 2 frames from class _AssertionError)
2018-09-07 09:55:06.744802-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.744970-0700 Runner[38977:6722533] flutter: The AnimationController notifying listeners was:
2018-09-07 09:55:06.745098-0700 Runner[38977:6722533] flutter:   AnimationController#c0898(◀ 0.003)
2018-09-07 09:55:06.745260-0700 Runner[38977:6722533] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2018-09-07 09:55:06.745406-0700 Runner[38977:6722533] flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
2018-09-07 09:55:06.745573-0700 Runner[38977:6722533] flutter: The following assertion was thrown while notifying listeners for AnimationController:
2018-09-07 09:55:06.745695-0700 Runner[38977:6722533] flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12:
2018-09-07 09:55:06.745839-0700 Runner[38977:6722533] flutter: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
2018-09-07 09:55:06.746008-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.746153-0700 Runner[38977:6722533] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2018-09-07 09:55:06.746337-0700 Runner[38977:6722533] flutter: more information in this error message to help you determine and fix the underlying cause.
2018-09-07 09:55:06.746495-0700 Runner[38977:6722533] flutter: In either case, please report this assertion by filing a bug on GitHub:
2018-09-07 09:55:06.746646-0700 Runner[38977:6722533] flutter:   https://github.com/flutter/flutter/issues/new
2018-09-07 09:55:06.746783-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.746937-0700 Runner[38977:6722533] flutter: When the exception was thrown, this was the stack:
2018-09-07 09:55:06.747087-0700 Runner[38977:6722533] flutter: #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3436:12)
2018-09-07 09:55:06.747226-0700 Runner[38977:6722533] flutter: #3      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
2018-09-07 09:55:06.747368-0700 Runner[38977:6722533] flutter: #4      DrawerControllerState._animationChanged (package:flutter/src/material/drawer.dart:215:5)
2018-09-07 09:55:06.747508-0700 Runner[38977:6722533] flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:109:19)
2018-09-07 09:55:06.747657-0700 Runner[38977:6722533] flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:608:5)
2018-09-07 09:55:06.747807-0700 Runner[38977:6722533] flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:234:5)
2018-09-07 09:55:06.747935-0700 Runner[38977:6722533] flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-09-07 09:55:06.748107-0700 Runner[38977:6722533] flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
2018-09-07 09:55:06.748279-0700 Runner[38977:6722533] flutter: #10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
2018-09-07 09:55:06.748431-0700 Runner[38977:6722533] flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
2018-09-07 09:55:06.748601-0700 Runner[38977:6722533] flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
2018-09-07 09:55:06.748739-0700 Runner[38977:6722533] flutter: #13     _invoke1 (dart:ui/hooks.dart:142:13)
2018-09-07 09:55:06.748853-0700 Runner[38977:6722533] flutter: #14     _beginFrame (dart:ui/hooks.dart:113:3)
2018-09-07 09:55:06.749003-0700 Runner[38977:6722533] flutter: (elided 2 frames from class _AssertionError)
2018-09-07 09:55:06.749170-0700 Runner[38977:6722533] flutter:
2018-09-07 09:55:06.749319-0700 Runner[38977:6722533] flutter: The AnimationController notifying listeners was:
2018-09-07 09:55:06.749467-0700 Runner[38977:6722533] flutter:   AnimationController#c0898(⏮ 0.000; paused)
2018-09-07 09:55:06.749629-0700 Runner[38977:6722533] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Looks similar to #21537 just without the engine crash.
