### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY NotificationListener<KeepAliveNotification>

### ISSUE THREAD

**Issue by AlfredoZuloaga** [flutter/flutter#21559]
This error happens when I have a List with a lot of element around 1000 elements and scrolled of them very fast, 
---Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.8.1-pre.51, on Microsoft Windows [VersiÃ³n 10.0.17134.112], locale es-MX)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.1)
[√] VS Code (version 1.27.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected devices (1 available)
----
I/flutter ( 6914): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6914): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 6914): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14:
I/flutter ( 6914): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6914):
I/flutter ( 6914): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6914): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6914): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6914):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6914):
I/flutter ( 6914): When the exception was thrown, this was the stack:
I/flutter ( 6914): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2798:14)
I/flutter ( 6914): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2832:5)
I/flutter ( 6914): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 6914): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:932:18)
I/flutter ( 6914): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
I/flutter ( 6914): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 6914): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4665:11)
I/flutter ( 6914): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 6914): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 6914): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 6914): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 6914): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 6914): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 6914): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 6914): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 6914): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
I/flutter ( 6914): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 6914): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 6914): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 6914): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 6914): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 6914): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 6914): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 6914): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
I/flutter ( 6914): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:769:34)
I/flutter ( 6914): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
I/flutter ( 6914): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6914): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #41     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 6914): #42     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 6914): #43     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 6914): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #47     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6914): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6914): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6914): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #71     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6914): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6914): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #79     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6914): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6914): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 6914): #86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 6914): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6914): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6914): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6914): #90     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 6914): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 6914): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 6914): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6914): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6914): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6914): #96     _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 6914): #97     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 6914): (elided 2 frames from class _AssertionError)
I/flutter ( 6914): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6914): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6914): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 6914): Another exception was thrown: A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter ( 6914): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 6914): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.

-----

**Comment by AlfredoZuloaga** [comment]
I think was using the package flutter_slidable 0.4.5 and I think it has a Bug that probably causes this error, I disable this package and everything works fine again.
