### ISSUE TITLE
Assertion was thrown building DefaultTextStyle when device orientation changes

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#21562]
## Steps to Reproduce

1. Run example app inside https://github.com/codegrue/card_settings
2. Once the form appears, change the device orientation

Note: this was previously working with an older build of flutter.

## Logs

```
Launching lib/main.dart on iPhone 7 in debug mode...
Xcode build done.
)
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building DefaultTextStyle(debugLabel: (englishLike
flutter: body1).merge(blackCupertino body1), inherit: false, color: Color(0xdd000000), family: .SF UI Text,
flutter: size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping
flutter: at box width, overflow: clip):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3249 pos 12: '() {
flutter:       if (_parent == null) {
flutter:         // We're being deactivated, see deactivateChild()
flutter:         return true;
flutter:       }
flutter:       Element element = _parent;
flutter:       while (ancestor != element && element != null)
flutter:         element = element._parent;
flutter:       return ancestor == element;
flutter:     }()': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Element.inheritFromElement (package:flutter/src/widgets/framework.dart:3249:12)
flutter: #3      StatefulElement.inheritFromElement (package:flutter/src/widgets/framework.dart:3921:18)
flutter: #4      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3271:14)
flutter: #5      Form.of (package:flutter/src/widgets/form.dart:40:38)
flutter: #6      FormFieldState.deactivate (package:flutter/src/widgets/form.dart:341:10)
flutter: #7      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3860:12)
flutter: #8      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1715:13)
flutter: #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3722:14)
flutter: #10     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
flutter: #11     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1726:7)
flutter: #12     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2973:29)
flutter: #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4562:13)
flutter: #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4921:17)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #34     StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #56     StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #86     ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #94     ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #98     ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #114    ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #116    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4531:32)
flutter: #117    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4921:17)
flutter: #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #121    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #125    ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #129    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #135    StatelessElement.update (package:flutter/src/widgets/framework.dart:3748:5)
flutter: #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4813:14)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #141    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #145    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #149    ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #153    ProxyElement.update (package:flutter/src/widgets/framework.dart:3957:5)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #157    StatefulElement.update (package:flutter/src/widgets/framework.dart:3845:5)
flutter: #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:16)
flutter: #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3541:5)
flutter: #161    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #162    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #164    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #165    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #166    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #167    _invoke (dart:ui/hooks.dart:128:13)
flutter: #168    _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2271 pos 16: '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4214 pos 14: '() {
flutter: Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following child:
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4087 pos 14: '_dependents.isEmpty': is not true.
flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
Application finished.
Exited
```

```
flutter analyze
Analyzing card_settings...

   info • The member 'activity' can only be used within instance members of subclasses of 'ScrollPosition' • lib/helpers/scroll_picker.dart:153:35 • invalid_use_of_protected_member

1 issue found. (ran in 3.9s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.8.1-pre.15, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.8.1-pre.15 at /Users/jeff/SDKs/flutter
    • Framework revision 6e64cb0ad8 (2 days ago), 2018-09-05 16:22:12 +0100
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jeff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4668.60

[✓] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 7 • 7AAFF127-35E3-40B4-8512-C2C9DA29795F • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like what #21570 was supposed to fix (merged a few hours ago).
Can you please check if you can reproduce in latest master?

**Comment by codegrue** [comment]
Indeed the latest Master branch fixed the issue.
