### ISSUE TITLE
Error with video_player plugin on iOS

### ISSUE THREAD

**Issue by GiacomoPignoni** [flutter/flutter#21592]
Hi, I have a problem with the video_player plugin, only on iOS.
On Android it work fine, but on iOS it give me this error.
The app worked fine before adding this plugin.
I've already read about other person with this problem (for other plugin) but all the solution don't work for me.
I have the same error with a new project.

## Logs
```
      In file included from /Users/Giacomo/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.6.5/ios/Classes/VideoPlayerPlugin.m:5:
           /Users/Giacomo/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.6.5/ios/Classes/VideoPlayerPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
           #import <Flutter/Flutter.h>
                   ^~~~~~~~~~~~~~~~~~~
           1 error generated.
            
[   +4 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone 8.
[   +6 ms] "flutter run" took 7.740ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:417:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale it-IT)
    • Flutter version 0.7.3 at /Users/Giacomo/Documents/flutter
    • Framework revision 3b309bda07 (11 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/giacomo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 8 • A42834DE-8B62-44A9-AD07-C6E9AB3880EA • ios • iOS 11.4 (simulator)

• No issues found! 
```

**Comment by zoechi** [comment]
#17899, #17943 might contain suggestions.

**Comment by zoechi** [comment]
Unfortunately that's not a lot of information to act on.
Can you reproduce in a new project created with `flutter create`?

**Comment by GiacomoPignoni** [comment]
I have the same error if I make a new app with flutter create

**Comment by zoechi** [comment]
Merging with #18732
