### ISSUE TITLE
JSON Encoding errors are not precise enough

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#21605]
## Steps to Reproduce

While I ran into this error while working on my own serializer, and didn't think about JSON restrictions, this could anger a programmer to no end.

```dart
json.encode({250: 250, 251: 251});
```

This fails with this error:
```
I/flutter ( 7618): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7618): The following JsonUnsupportedObjectError was thrown while handling a gesture:
I/flutter ( 7618): Converting object to an encodable object failed: _LinkedHashMap len:2
I/flutter ( 7618):
I/flutter ( 7618): When the exception was thrown, this was the stack:
I/flutter ( 7618): #0      _JsonStringifier.writeObject (dart:convert/json.dart:703:7)
I/flutter ( 7618): #1      _JsonStringStringifier.printOn (dart:convert/json.dart:902:17)
I/flutter ( 7618): #2      _JsonStringStringifier.stringify (dart:convert/json.dart:884:5)
I/flutter ( 7618): #3      JsonEncoder.convert (dart:convert/json.dart:285:30)
I/flutter ( 7618): #4      JsonCodec.encode (dart:convert/json.dart:184:45)
```

The JSON encoding library probably should warn users about unsupported types on conversion, for example
```
JSON does not support having type int as a key.
```

## Logs

```
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-BE)
    • Flutter version 0.7.3 at C:\tools\flutter
    • Framework revision 3b309bda07 (11 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (2 available)
    • Archos 101c Neon             • A014091600000B7C • android-arm • Android 4.4.2 (API 19)
    • Android SDK built for x86 64 • emulator-5554    • android-x64 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by goderbauer** [comment]
I am assuming you are using the json converter from `dart:convert`? In that case a better place for your bug report may be the Dart repository: https://github.com/dart-lang/sdk/issues/new

**Comment by zoechi** [comment]
The error is from `dart:convert/json.dart:703:7` 
I think it should be reported in https://github.com/dart-lang/sdk/issues
