### ISSUE TITLE
Flutter crashing when I use a list view with checkbox and TextFormField in it and scroll '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.

### ISSUE THREAD

**Issue by mjaffa-figure** [flutter/flutter#21644]
Flutter gives me the red screen of death (`'_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.`) when I click a checkbox in this sample code, focus in the text field, enter a number. Scroll all the way to the bottom then back to middle, scroll to bottom again, then to middle. Click another checkbox. Boom

It won't crash if I in the simulator press enter after entering text into the text field. so it looks like the Text field still has focus and by scrolling around in the list view, the old list view item gets recycled and I don't know what.

When I create a list view like this:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in IntelliJ). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class CheckboxStateItemWithText {
  String text;
  bool isChecked = false;
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  var items = [new CheckboxStateItemWithText(), new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText()];

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: new ListView.builder( itemCount: items.length, itemBuilder: (BuildContext context, int index) {
        var item = items[index];
        List<Widget> children = new List();
        children.add(new SizedBox(width: 15.0, height: 15.0));


        children.add(new Expanded(flex: 5,
            child: new Checkbox(
                value: item.isChecked, onChanged: (checked) async {
              FocusScope.of(context).requestFocus(new FocusNode());
              setState(() {
                item.isChecked = checked;
              });
            })));




        children.add(new Expanded(flex: 6, child: new Row(children: [new Text('info', style: new TextStyle(color: Colors.white))], mainAxisAlignment: MainAxisAlignment.center,)));



        if (item.isChecked) {
          TextEditingController controller = new TextEditingController(text: item.text);
          controller.addListener(() {
            item.text = controller.value.text;
          });
          children.add(new Expanded(
            flex: 3, child: new TextFormField(keyboardType: TextInputType.number, controller: controller, autocorrect: false, validator: (value) {
            if (value.isEmpty) {
              return 'Invalid';
            } else {
              int count = int.parse(value);
              if (count <= 0) {
                return 'Invalid';
              }
            }
          }, onSaved: (value) {
            item.text = value;

          }, textAlign: TextAlign.center,),));
        }
        children.add(new SizedBox(width: 15.0, height: 15.0));


        return new Row(
          children: children,
        );
      }),

      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

Output from flutter doctor:
flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.8.1, on Mac OS X 10.13.6 17G2208, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.26.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Syncing files to device iPhone X...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building NotificationListener<KeepAliveNotification>:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14:
flutter: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2798:14)
flutter: #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2832:5)
flutter: #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
flutter: #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:932:18)
```

**Comment by zoechi** [comment]
```
new CheckboxStateItemWithText(), new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
  new CheckboxStateItemWithText(),
...
```
I hope you are aware of loops in Dart ;-) 
or https://api.dartlang.org/stable/2.0.0/dart-core/List/List.filled.html, https://api.dartlang.org/stable/2.0.0/dart-core/List/List.generate.html

**Comment by zoechi** [comment]
Can you please check if v0.8.2-pre.26 (or later) fixes it for you as well?
https://github.com/flutter/flutter/issues/11895#issuecomment-419985757

**Comment by mjaffa-figure** [comment]
@zoechi Working on v0.8.3-pre.24.

Thanks
