### ISSUE TITLE
Error when using "p" (construction lines) in command prompt

### ISSUE THREAD

**Issue by brilliant-ember** [flutter/flutter#21655]
When I pressed p while running my Flutter application I got this error.

```
I/flutter (25000): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25000): The following assertion was thrown during paint():
I/flutter (25000): 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 334 pos 18:
I/flutter (25000): 'innerRect.bottom <= outerRect.bottom': is not true.
I/flutter (25000):
I/flutter (25000): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25000): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25000): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25000):   https://github.com/flutter/flutter/issues/new
I/flutter (25000):
I/flutter (25000): When the exception was thrown, this was the stack:
I/flutter (25000): #2      RenderSliverPadding.debugPaint.<anonymous closure> (package:flutter/src/rendering/sliver_padding.dart:334:18)
I/flutter (25000): #3      RenderSliverPadding.debugPaint (package:flutter/src/rendering/sliver_padding.dart:339:6)
I/flutter (25000): #4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2024:7)
I/flutter (25000): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2028:6)
I/flutter (25000): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
I/flutter (25000): #7      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:524:17)
I/flutter (25000): #8      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:517:7)
I/flutter (25000): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
I/flutter (25000): #10     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:11)
I/flutter (25000): #11     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:784:29)
I/flutter (25000): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:278:19)
I/flutter (25000): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (25000): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter (25000): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25000): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25000): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (25000): #18     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (25000): #19     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (25000): (elided 2 frames from class _AssertionError)
I/flutter (25000):
I/flutter (25000): The following RenderObject was being processed when the exception was fired:
I/flutter (25000):   RenderViewport#3b269
I/flutter (25000):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#452da] ← Semantics ← Listener ←
I/flutter (25000):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#09cd3] ←
I/flutter (25000):   _ExcludableScrollSemantics-[GlobalKey#4fffd] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (25000):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (25000):   parentData: <none> (can use size)
I/flutter (25000):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=528.4)
I/flutter (25000):   layer: OffsetLayer#1a36c
I/flutter (25000):   size: Size(411.4, 528.4)
I/flutter (25000):   axisDirection: up
I/flutter (25000):   crossAxisDirection: right
I/flutter (25000):   offset: ScrollPositionWithSingleContext#c9644(offset: 0.0, range: 0.0..0.0, viewport: 528.4,
I/flutter (25000):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#65dcb,
I/flutter (25000):   ScrollDirection.idle)
I/flutter (25000):   anchor: 0.0
I/flutter (25000): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (25000):   RenderSliverPadding#40cc4 relayoutBoundary=up1
I/flutter (25000):     RenderSliverList#c2d84 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (25000): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Can you post a running minimal example that allows to reproduce?

**Comment by zoechi** [comment]
Thanks for the reproduction!

**Comment by zoechi** [comment]
Same error as in #10445

**Comment by Piinks** [comment]
This is a dup of https://github.com/flutter/flutter/issues/28406 which will be fixed once https://github.com/flutter/flutter/pull/37033 has landed.
If this is not the case and this bug persists on master after that PR lands, please feel free to re-open.
