### ISSUE TITLE
Flutter crash when I Switched platform rendering to Android

### ISSUE THREAD

**Issue by mrdaios** [flutter/flutter#21668]
- mac
- AndroidStudio

https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#4

**Comment by mrdaios** [comment]
I am sorry.

**Comment by mrdaios** [comment]
Launching lib/main.dart on iPhone 6 in debug mode...
Starting Xcode build...
Xcode build done.
Syncing files to device iPhone 6...
Switched platform rendering to Android.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building SlideTransition(animation: AnimationController#47a34(⏭
flutter: 1.000; paused; for MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20,
flutter: 1.00)➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
flutter: _AnimatedState#0ae9f):
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1853 pos 12: '() {
flutter:       final AbstractNode parent = this.parent;
flutter:       if (parent is RenderObject)
flutter:         return parent._needsCompositing;
flutter:       return true;
flutter:     }()': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject.markNeedsCompositingBitsUpdate (package:flutter/src/rendering/object.dart:1853:12)
flutter: #3      RenderObject.attach (package:flutter/src/rendering/object.dart:1293:7)
flutter: #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.attach (package:flutter/src/rendering/object.dart:2721:11)
flutter: #5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
flutter: #6      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1138:11)
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2716:7)
flutter: #8      SingleChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:4681:18)
flutter: #9      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
flutter: #10     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2986:5)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2911:18)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #53     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #63     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
flutter: #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #70     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #71     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #72     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1152 pos 12: 'child.parentData != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1152 pos 12: 'child.parentData != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/foundation/node.dart': Failed assertion: line 106 pos 12: '_owner != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1152 pos 12: 'child.parentData != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: NoSuchMethodError: The method '_enableMutationsToDirtySubtrees' was called on null.
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
flutter: Another exception was thrown: Tried to paint a RenderObject before its compositing bits were updated.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3236 pos 12: '_ancestorChain.length == 1': is not true.
Switched platform rendering to iOS.
