### ISSUE TITLE
Flutter stripe implementation application crash

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#21674]
I am trying to implement stripe payment plugin for flutter and add the plugin in pubspec.yaml same as flutter stripe payment example but it gives me below error... I am using in the new fresh application.

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,713ms.
E/flutter ( 4683): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4683): MissingPluginException(No implementation found for method setPublishableKey on channel stripe_payment)
E/flutter ( 4683): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #1      StripeSource.setPublishableKey (package:stripe_payment/stripe_payment.dart:21:14)
E/flutter ( 4683): #2      _MyAppState.initState (file:///E:/workstation/stripe_app/lib/main.dart:20:18)
E/flutter ( 4683): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 4683): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4683): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4683): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4683): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
E/flutter ( 4683): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
E/flutter ( 4683): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
E/flutter ( 4683): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 4683): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
E/flutter ( 4683): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
E/flutter ( 4683): #13     runApp (package:flutter/src/widgets/binding.dart:728:7)
E/flutter ( 4683): #14     main (file:///E:/workstation/stripe_app/lib/main.dart:6:3)
E/flutter ( 4683): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4683): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 4683): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4683): MissingPluginException(No implementation found for method addSource on channel stripe_payment)
E/flutter ( 4683): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #1      StripeSource.addSource (package:stripe_payment/stripe_payment.dart:12:41)
E/flutter ( 4683): <asynchronous suspension>
E/flutter ( 4683): #2      _MyAppState.initState (file:///E:/workstation/stripe_app/lib/main.dart:21:18)
E/flutter ( 4683): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3763:58)
E/flutter ( 4683): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
E/flutter ( 4683): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
E/flutter ( 4683): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
E/flutter ( 4683): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
E/flutter ( 4683): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
E/flutter ( 4683): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
E/flutter ( 4683): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
E/flutter ( 4683): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
E/flutter ( 4683): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
E/flutter ( 4683): #13     runApp (package:flutter/src/widgets/binding.dart:728:7)
E/flutter ( 4683): #14     main (file:///E:/workstation/stripe_app/lib/main.dart:6:3)
E/flutter ( 4683): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 4683): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by zoechi** [comment]
The plugin might need an update. 
It's last release is from May.
I think it's better to file an issue in https://github.com/jonasbark/flutter_stripe_payment

**Comment by rahulmishra1991** [comment]
Ok Thanks

**Comment by andreabtis** [comment]
open only the Android project in a new window on AS:

Add in the MainActivity the FlutterFragmentActivity(): like this:
class MainActivity(): FlutterFragmentActivity() {
override fun onCreate(savedInstanceState: Bundle?) {
super.onCreate(savedInstanceState)
GeneratedPluginRegistrant.registerWith(this)
}
}

Customize imports
Upgrade the kotlin version in build.gradle file of your app:
ext.kotlin_version = '1.2.71'
and thats it! 👍
