### ISSUE TITLE
DefaultTabController crashes when used with Streams

### ISSUE THREAD

**Issue by mzayani** [flutter/flutter#21687]
[lib.zip](https://github.com/flutter/flutter/files/2371442/lib.zip)

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building NotificationListener<KeepAliveNotification>:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14:
flutter: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2798:14)
flutter: #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2832:5)
flutter: #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
flutter: #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:932:18)
flutter: #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
flutter: #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4291:5)
flutter: #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4665:11)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
flutter: #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:769:34)
flutter: #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
flutter: #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
flutter: #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #71     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
flutter: #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #81     _invoke (dart:ui/hooks.dart:128:13)
flutter: #82     _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
type 'RenderErrorBox' is not a subtype of type 'RenderSemanticsGestureHandler'
#0      RawGestureDetectorState.replaceSemanticsActions (package:flutter/src/widgets/gesture_detector.dart:597:43)
#1      ScrollableState.setSemanticsActions (package:flutter/src/widgets/scrollable.dart:337:40)
#2      ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:445:13)
#3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:669:5)
#4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:318:5)
#5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:199:7)
#6      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:132:14)
#7      _TabBarViewState._warpToCurrentIndex (package:flutter/src/material/tabs.dart:1126:21)
<asynchronous suspension>
#8      _TabBarViewState._handleTabControll<…>
flutter: Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
flutter: Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:

**Comment by mzayani** [comment]
Using the Bloc pattern in a form that is on one tab. switching between tabs will through the exception.

**Comment by zoechi** [comment]
I believe this is a dup of #11895 

Please see this comment https://github.com/flutter/flutter/issues/11895#issuecomment-419985757
