### ISSUE TITLE
Error while trying to collect test coverage data: Exception: Timed out while collecting coverage.

### ISSUE THREAD

**Issue by jadengis** [flutter/flutter#21698]
## Steps to Reproduce
I am attempting to run unit and widget tests written for my flutter application. I am simply running `flutter test --coverage` from the command line when I hit the issue. This issue occurs intermittently.

## Logs

```
johndengis@code-builder:~/projects/coralhealth/coralhealth$ flutter test --coverage
02:15 +58: ... ErrorStack .pop gives you the top element of the stack                                   unhandled error during test:
/home/johndengis/projects/coralhealth/coralhealth/test/widget/components/search_filter_views_test.dart
Exception: Timed out while collecting coverage.
#0      CoverageCollector.collectCoverage.<anonymous closure> (package:flutter_tools/src/test/coverage_collector.dart:64:13)
#1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#3      _rootRun (dart:async/zone.dart:1120:38)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:731:33)
#6      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#7      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#8      _rootRun (dart:async/zone.dart:1120:38)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#13     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

02:15 +58 -1: loading /home/johndengis/projects/coralhealth/coralhealth/test/widget/components/search_filter_views_test.dart [E]
  Exception: Timed out while collecting coverage.
  package:flutter_tools/src/test/flutter_platform.dart 662:7   _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                            _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18                 _AsyncAwaitCompleter.completeError
  package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 383:36  _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 65:19           PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
  package:test/src/runner/loader.dart                          Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89:31                new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                 _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                  _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                  new Timer
  dart:async/timer.dart 87:9                                   Timer.run
  dart:async/future.dart 174:11                                new Future
  package:test/src/backend/invoker.dart 402:15                 Invoker._onRun.<fn>.<fn>.<fn>
```

```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.7.3 at /home/johndengis/development/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/johndengis/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /snap/android-studio/51/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /snap/android-studio/51/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /home/johndengis/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/181.5540.7
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by jadengis** [comment]
I just tried this out again and it seems to be working, so I'll close the issue. Thanks for following up.
