### ISSUE TITLE
Fresh flutter app build error - no code has been change

### ISSUE THREAD

**Issue by kszyrvercobrador** [flutter/flutter#21717]
## Steps to Reproduce

1. Create new flutter app
2. flutter run

## Logs

```
C:\Workspace\Android\Flutter\Apps\first100days>flutter run --verbose
[  +65 ms] executing: [C:\Workspace\Android\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +86 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\Workspace\Android\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [C:\Workspace\Android\Flutter\flutter\] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\Workspace\Android\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3b309bda072a6b326e8aa4591a5836af600923ce
[        ] executing: [C:\Workspace\Android\Flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +38 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[   +1 ms] executing: [C:\Workspace\Android\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +41 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.7.3-0-g3b309bda0
[ +311 ms] executing: C:\Users\Kszyr Ver Cobrador\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +23 ms] Exit code 0 from: C:\Users\Kszyr Ver Cobrador\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[ +396 ms] C:\Users\Kszyr Ver Cobrador\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell getprop
[  +68 ms] ro.hardware = ranchu
[  +29 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[ +886 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +60 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Workspace\Android\Flutter\Apps\first100days\android\gradlew.bat.
[ +106 ms] executing: C:\Workspace\Android\Flutter\Apps\first100days\android\gradlew.bat -v
[ +840 ms]
                   ------------------------------------------------------------
                   Gradle 4.4
                   ------------------------------------------------------------

                   Build time:   2017-12-06 09:05:06 UTC
                   Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

                   Groovy:       2.4.12
                   Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b02)
                   OS:           Windows 10 10.0 amd64
[        ] Initializing gradle... (completed)
[        ] Resolving dependencies...
[        ] executing: [C:\Workspace\Android\Flutter\Apps\first100days\android\] C:\Workspace\Android\Flutter\Apps\first100days\android\gradlew.bat app:properties
[+1452 ms]
                   FAILURE: Build failed with an exception.

                   * Where:
                   Build file 'C:\Workspace\Android\Flutter\Apps\first100days\android\app\build.gradle' line: 24

                   * What went wrong:
                   A problem occurred evaluating project ':app'.
                   > Plugin with id 'com.android.application' not found.

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                   * Get more help at https://help.gradle.org

                   BUILD FAILED in 1s
[   +4 ms] Resolving dependencies... (completed)
[   +2 ms] * Error running Gradle:
           Exit code 1 from: C:\Workspace\Android\Flutter\Apps\first100days\android\gradlew.bat app:properties:
           
           FAILURE: Build failed with an exception.
           
           * Where:
           Build file 'C:\Workspace\Android\Flutter\Apps\first100days\android\app\build.gradle' line: 24
           
           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Plugin with id 'com.android.application' not found.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 1s
           
[  +17 ms] "flutter run" took 4,077ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:115:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:97:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:316:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:272:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:259:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:411:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

```
Analyzing first100days...
No issues found! (ran in 1.4s)
```

```
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-PH)
    • Flutter version 0.7.3 at C:\Workspace\Android\Flutter\flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Kszyr Ver Cobrador\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by kszyrvercobrador** [comment]
Here's a video for that issue.
https://youtu.be/i7tKbdYthmY

**Comment by aam** [comment]
Can you attach output of `flutter run -v`, please?

Are you able to build and launch sample java Android applications on your emulator, on this machine?

**Comment by kszyrvercobrador** [comment]
@aam I've already attach it above. Yes a was able to build and lunch app but on old version of android studio and flutter.

**Comment by kszyrvercobrador** [comment]
I found the solution for this. Just change the `com.android.tools.build:gradle` version from 3.1.2 to 3.1.4

```
 dependencies {
    classpath 'com.android.tools.build:gradle:3.1.2'
}
dependencies {
    classpath 'com.android.tools.build:gradle:3.1.4'
}
```
