### ISSUE TITLE
Issue with dynamic list and list view

### ISSUE THREAD

**Issue by mayankjanmejay** [flutter/flutter#21819]
Hi, 

I am using a global list, together with a data table which has editable field for quantity (Screenshot 1). I select items, add quantity for them and then add them to cart. When I go back to the ListView which had been working all this time, this happens. This error occurs only in conjunction with TextEditingController. I have attached the offending :P files.

Thanks
```
Launching lib\main.dart on Lenovo TB 8504X in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
V/BoostFramework( 9688): mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V/BoostFramework( 9688): mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
V/BoostFramework( 9688): mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
V/BoostFramework( 9688): mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
V/BoostFramework( 9688): mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
V/BoostFramework( 9688): BoostFramework() : mPerf = com.qualcomm.qti.Performance@88e23c4
I/flutter ( 9688): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9688): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 9688): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14:
I/flutter ( 9688): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 9688):
I/flutter ( 9688): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9688): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9688): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9688):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9688):
I/flutter ( 9688): When the exception was thrown, this was the stack:
I/flutter ( 9688): #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2798:14)
I/flutter ( 9688): #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2832:5)
I/flutter ( 9688): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
I/flutter ( 9688): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:932:18)
I/flutter ( 9688): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
I/flutter ( 9688): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 9688): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4665:11)
I/flutter ( 9688): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 9688): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 9688): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 9688): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 9688): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 9688): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 9688): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 9688): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 9688): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
I/flutter ( 9688): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 9688): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 9688): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 9688): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 9688): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 9688): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 9688): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 9688): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
I/flutter ( 9688): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:769:34)
I/flutter ( 9688): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
I/flutter ( 9688): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 9688): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 9688): #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 9688): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9688): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9688): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9688): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 9688): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9688): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9688): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #77     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 9688): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9688): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 9688): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9688): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9688): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9688): #89     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 9688): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 9688): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9688): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9688): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9688): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9688): #95     _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 9688): #96     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 9688): (elided 2 frames from class _AssertionError)
I/flutter ( 9688): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2798 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 9688): Another exception was thrown: The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following children:
```

![screenshot_20180913-161225](https://user-images.githubusercontent.com/35850067/45490598-3482af00-b770-11e8-9112-4708474f062b.jpeg)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Looks like a dup of #11895 

See also this comment https://github.com/flutter/flutter/issues/11895#issuecomment-419985757

> fixed in v0.8.2-pre.26, j

**Comment by mayankjanmejay** [comment]
Issue still exists

**Comment by mayankjanmejay** [comment]
PS E:\Documents\OneDrive\VS Code\Salesforce App\Versions\Week 38\SalesForceApp.13.09.2018> flutter doctor -v
[√] Flutter (Channel dev, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-GB)
    • Flutter version 0.8.2 at E:\flutter
    • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Mike\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.27.1)
    • VS Code at C:\Users\Mike\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Lenovo TB 8504X • HA0UY29L • android-arm64 • Android 7.1.1 (API 25)

• No issues found!

**Comment by mayankjanmejay** [comment]
[Code.zip](https://github.com/flutter/flutter/files/2379552/Code.zip)

Here are the code files which are evolved in the error.

**Comment by mayankjanmejay** [comment]
@zoechi Updated but still the issue exists.

**Comment by zoechi** [comment]
Can you please create a single runnable `main.dart` file. The files in the zip have no `main()` and import missing files.

**Comment by mayankjanmejay** [comment]
[listTest.zip](https://github.com/flutter/flutter/files/2382769/listTest.zip)
[App.zip](https://github.com/flutter/flutter/files/2382770/App.zip)


I am unable to recreate the issue while keeping a single runnable main.dart. So I have attached App.zip which is the project (cut down version). 

To replicate the error, please compile and 

1) Navigate to the items tab
2) Select 1 item and then add a random number quantity 
3) Click the add to cart icon
4) Navigate to the testing tab
