### ISSUE TITLE
Dart VM crashes after multiple hot restarts

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#21858]
1) Create a default app with "flutter create"
2) Run the app in debug mode
3) Hot restart the app a few times.  After about 3 to 6 restarts, the VM will segfault.

It looks like some variant of this has been happening since https://github.com/flutter/engine/commit/b157d4f5683023836cdf15d42bf56fd201a7084b

@a-siva 

Example stack trace:
(Note that the stack trace is not consistent across runs, but it's usually somewhere within dart::kernel)
```
#0  0x8d202b54 in dart::kernel::Reader::PeekByte (this=<optimized out>) at ../../third_party/dart/runtime/vm/kernel_binary.h:263
#1  dart::kernel::Reader::PeekTag (this=<optimized out>, payload=<optimized out>) at ../../third_party/dart/runtime/vm/kernel_binary.h:285
#2  dart::kernel::KernelReaderHelper::PeekTag (this=<optimized out>, payload=<optimized out>)
    at ../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:2198
#3  dart::kernel::StreamingFlowGraphBuilder::BuildGraph (this=0x8bd79094)
    at ../../third_party/dart/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1942
#4  0x8d211bca in dart::kernel::FlowGraphBuilder::BuildGraph (this=0x8bd791f0)
    at ../../third_party/dart/runtime/vm/compiler/frontend/kernel_to_il.cc:749
#5  0x8d232b58 in dart::DartCompilationPipeline::BuildFlowGraph (this=<optimized out>, zone=<optimized out>, parsed_function=<optimized out>, 
    ic_data_array=..., osr_id=-1, optimized=<optimized out>) at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:165
#6  0x8d2351a8 in dart::CompileParsedFunctionHelper::Compile (this=0x8bd79730, pipeline=0x8bd79f78)
    at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:828
#7  0x8d235ff6 in dart::CompileFunctionHelper (pipeline=0x8bd79f78, function=..., optimized=false, osr_id=-1)
    at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:1019
#8  0x8d235a60 in dart::Compiler::CompileFunction (thread=0x85c47000, function=...)
    at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:1229
#9  0x8d232f48 in dart::DRT_HelperCompileFunction (thread=<optimized out>, arguments=..., isolate=<optimized out>, zone=<optimized out>)
    at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:253
#10 dart::DRT_CompileFunction (arguments=...) at ../../third_party/dart/runtime/vm/compiler/jit/compiler.cc:249
```

**Comment by jason-simmons** [comment]
@chinmaygarde

**Comment by jason-simmons** [comment]
This will happen with no changes to the app between restarts

**Comment by jason-simmons** [comment]
This is happening because during a hot restart DevFS is overwriting the kernel file in place.  The engine still has an open mapping of the kernel file, and the currently running isolate may see a mix of new content and old content as the write happens.

DevFS can work around this by deleting the old file before writing the new file.

**Comment by jason-simmons** [comment]
Landed https://dart-review.googlesource.com/c/sdk/+/75620
