### ISSUE TITLE
flutter refresh doesn't do anything for ios simulator?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2186]
_Detailed issue description here. More information at [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/)_

### Steps to Reproduce
* Simulator is running. Starter app is running in simulator.
* Make a change to text in the flutter starter app
* Run `flutter refresh` from the command line

Expected: app to quickly refresh in simulator
Actual:

```
~/flutter/testme2 $ flutter refresh
~/flutter/testme2 $ 
```

### Flutter Version

```
Flutter from git@github.com:flutter/flutter.git (on hackathon)
flutter revision: 4860e63f444cf3786a6b136430f3058a7b851041 (14 hours ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.
```

### Logs

```
[Nexus 5] E/ActivityManager: Already have existing proc ProcessRecord{d6cb2cf 1020:WebViewLoader-armeabi-v7a/1037} when adding ProcessRecord{dd645c 0:WebViewLoader-armeabi-v7a/1037}
[Nexus 5] W/ActivityManager: Unable to start service Intent { cmp=com.google.android.gms/.measurement.service.b } U=0: not found
[Nexus 5] W/ActivityManager: Unable to start service Intent { cmp=com.google.android.gm/com.android.email.service.AttachmentService } U=0: not found
[Nexus 5] W/System.err: java.lang.Exception: Error converting session
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.log(SourceFile:302)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.toSession(SourceFile:268)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.ClientSessionContext.getSession(SourceFile:87)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getCachedClientSession(SourceFile:711)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getSessionToReuse(SourceFile:377)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(SourceFile:310)
[Nexus 5] W/System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.a(SourceFile:258)
[Nexus 5] W/System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.createSocket(SourceFile:558)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:89)
[Nexus 5] W/System.err: 	at com.android.okhttp.Connection.connect(Connection.java:143)
[Nexus 5] W/System.err: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
[Nexus 5] W/System.err: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:948)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:766)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:665)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.j.a.a(SourceFile:77)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.j.a.a(SourceFile:114)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.be.account.b.e.a(SourceFile:115)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.be.p.a(SourceFile:355)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.be.o.a(SourceFile:260)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.firstparty.dataservice.y.a(SourceFile:197)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.firstparty.dataservice.x.a(SourceFile:558)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.firstparty.dataservice.x.a(SourceFile:196)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.o.a(SourceFile:276)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.o.a(SourceFile:196)
[Nexus 5] W/System.err: 	at com.google.android.b.b.onTransact(SourceFile:137)
[Nexus 5] W/System.err: 	at android.os.Binder.execTransact(Binder.java:453)
[Nexus 5] W/System.err: Caused by: java.io.IOException: Invalid session data
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSessionImpl.<init>(SourceFile:88)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.toSession(SourceFile:267)
[Nexus 5] W/System.err: 	... 33 more
[Nexus 5] W/System.err: java.lang.Exception: Error converting session
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.log(SourceFile:302)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.toSession(SourceFile:268)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.ClientSessionContext.getSession(SourceFile:87)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getCachedClientSession(SourceFile:711)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getSessionToReuse(SourceFile:377)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(SourceFile:310)
[Nexus 5] W/System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.a(SourceFile:258)
[Nexus 5] W/System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.createSocket(SourceFile:558)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:89)
[Nexus 5] W/System.err: 	at com.android.okhttp.Connection.connect(Connection.java:143)
[Nexus 5] W/System.err: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
[Nexus 5] W/System.err: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
[Nexus 5] W/System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:950)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:766)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:674)
[Nexus 5] W/System.err: 	at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:658)
[Nexus 5] W/System.err: 	at com.android.volley.toolbox.HttpClientStack.performRequest(SourceFile:87)
[Nexus 5] W/System.err: 	at com.google.android.gms.auth.be.b.performRequest(SourceFile:44)
[Nexus 5] W/System.err: 	at com.android.volley.toolbox.BasicNetwork.performRequest(SourceFile:96)
[Nexus 5] W/System.err: 	at com.google.android.gms.common.server.v.performRequest(SourceFile:64)
[Nexus 5] W/System.err: 	at com.android.volley.NetworkDispatcher.run(SourceFile:112)
[Nexus 5] W/System.err: Caused by: java.io.IOException: Invalid session data
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSessionImpl.<init>(SourceFile:88)
[Nexus 5] W/System.err: 	at com.google.android.gms.org.conscrypt.a.toSession(SourceFile:267)
[Nexus 5] W/System.err: 	... 26 more
[Nexus 5] W/ActivityManager: Unable to start service Intent { cmp=com.google.android.gm/com.android.email.service.AttachmentService } U=0: not found
```

**Comment by sethladd** [comment]
Oh, I see in the help text "(Android only)"

Maybe we could "fail fast" with `flutter refresh` and say "refresh only works with Android. Please specify an Android device." ?

**Comment by chinmaygarde** [comment]
It now says no supported devices are connected.
