### ISSUE TITLE
NoSuchMethodError: The method '>' was called on null.

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#21887]
## Steps to Reproduce

1. When I start my flutter application on my device after doing `flutter build apk` and `flutter install`, the following error fills the device screen for a split second and then goes away and the app seems to behave just fine after that.

![nosuchmethoderror](https://user-images.githubusercontent.com/5922273/45573244-fce03980-b839-11e8-9f9b-1a5597ae6514.png)

## Logs
The relevant section of the output from `adb logcat` is:
```
36685 09-14 15:59:13.621 19446 19478 I flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
36686 09-14 15:59:13.621 19446 19478 I flutter : The following ArgumentError was thrown during performLayout():
36687 09-14 15:59:13.621 19446 19478 I flutter : Invalid argument(s): 74.0
36688 09-14 15:59:13.624 19446 19478 I flutter :
36689 09-14 15:59:13.624 19446 19478 I flutter : When the exception was thrown, this was the stack:
36690 09-14 15:59:13.626 19446 19478 I flutter : #0      _Double.clamp (dart:core/runtime/libdouble.dart:144)
36691 09-14 15:59:13.626 19446 19478 I flutter : #1      RenderSliverFloatingPinnedPersistentHeader.updateGeometry (package:flutter/src/rendering/sliver_persistent_header.dart:524)
36692 09-14 15:59:13.626 19446 19478 I flutter : #2      RenderSliverFloatingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:482)
36693 09-14 15:59:13.626 19446 19478 I flutter : #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36694 09-14 15:59:13.626 19446 19478 I flutter : #4      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405)
36695 09-14 15:59:13.626 19446 19478 I flutter : #5      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320)
36696 09-14 15:59:13.626 19446 19478 I flutter : #6      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238)
36697 09-14 15:59:13.626 19446 19478 I flutter : #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36698 09-14 15:59:13.626 19446 19478 I flutter : #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36699 09-14 15:59:13.626 19446 19478 I flutter : #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36700 09-14 15:59:13.626 19446 19478 I flutter : #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36701 09-14 15:59:13.626 19446 19478 I flutter : #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36702 09-14 15:59:13.626 19446 19478 I flutter : #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36703 09-14 15:59:13.626 19446 19478 I flutter : #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36704 09-14 15:59:13.626 19446 19478 I flutter : #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36705 09-14 15:59:13.626 19446 19478 I flutter : #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36706 09-14 15:59:13.626 19446 19478 I flutter : #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36707 09-14 15:59:13.627 19446 19478 I flutter : #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36708 09-14 15:59:13.627 19446 19478 I flutter : #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36709 09-14 15:59:13.627 19446 19478 I flutter : #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36710 09-14 15:59:13.627 19446 19478 I flutter : #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36711 09-14 15:59:13.627 19446 19478 I flutter : #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36712 09-14 15:59:13.627 19446 19478 I flutter : #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36713 09-14 15:59:13.627 19446 19478 I flutter : #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36714 09-14 15:59:13.627 19446 19478 I flutter : #24     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141)
36715 09-14 15:59:13.627 19446 19478 I flutter : #25     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338)
36716 09-14 15:59:13.627 19446 19478 I flutter : #26     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243)
36717 09-14 15:59:13.627 19446 19478 I flutter : #27     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355)
36718 09-14 15:59:13.627 19446 19478 I flutter : #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36719 09-14 15:59:13.627 19446 19478 I flutter : #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36720 09-14 15:59:13.627 19446 19478 I flutter : #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36721 09-14 15:59:13.627 19446 19478 I flutter : #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36722 09-14 15:59:13.627 19446 19478 I flutter : #32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192)
36723 09-14 15:59:13.627 19446 19478 I flutter : #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36724 09-14 15:59:13.627 19446 19478 I flutter : #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36725 09-14 15:59:13.627 19446 19478 I flutter : #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36726 09-14 15:59:13.628 19446 19478 I flutter : #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36727 09-14 15:59:13.628 19446 19478 I flutter : #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36728 09-14 15:59:13.628 19446 19478 I flutter : #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36729 09-14 15:59:13.628 19446 19478 I flutter : #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36730 09-14 15:59:13.628 19446 19478 I flutter : #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36731 09-14 15:59:13.628 19446 19478 I flutter : #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36732 09-14 15:59:13.628 19446 19478 I flutter : #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36733 09-14 15:59:13.628 19446 19478 I flutter : #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36734 09-14 15:59:13.628 19446 19478 I flutter : #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36735 09-14 15:59:13.628 19446 19478 I flutter : #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36736 09-14 15:59:13.628 19446 19478 I flutter : #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36737 09-14 15:59:13.628 19446 19478 I flutter : #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36738 09-14 15:59:13.628 19446 19478 I flutter : #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36739 09-14 15:59:13.628 19446 19478 I flutter : #49     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884)
36740 09-14 15:59:13.628 19446 19478 I flutter : #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36741 09-14 15:59:13.628 19446 19478 I flutter : #51     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520)
36742 09-14 15:59:13.628 19446 19478 I flutter : #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36743 09-14 15:59:13.629 19446 19478 I flutter : #53     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36744 09-14 15:59:13.629 19446 19478 I flutter : #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36745 09-14 15:59:13.629 19446 19478 I flutter : #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36746 09-14 15:59:13.629 19446 19478 I flutter : #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36747 09-14 15:59:13.629 19446 19478 I flutter : #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36748 09-14 15:59:13.629 19446 19478 I flutter : #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36749 09-14 15:59:13.629 19446 19478 I flutter : #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36750 09-14 15:59:13.629 19446 19478 I flutter : #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36751 09-14 15:59:13.629 19446 19478 I flutter : #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108)
36752 09-14 15:59:13.629 19446 19478 I flutter : #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1563)
36753 09-14 15:59:13.629 19446 19478 I flutter : #63     RenderView.performLayout (package:flutter/src/rendering/view.dart:147)
36754 09-14 15:59:13.629 19446 19478 I flutter : #64     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438)
36755 09-14 15:59:13.629 19446 19478 I flutter : #65     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697)
36756 09-14 15:59:13.629 19446 19478 I flutter : #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (      package:flutter/src/rendering/binding.dart:270)
36757 09-14 15:59:13.629 19446 19478 I flutter : #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBind      ing.drawFrame (package:flutter/src/widgets/binding.dart:654)
36758 09-14 15:59:13.629 19446 19478 I flutter : #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePers      istentFrameCallback (package:flutter/src/rendering/binding.dart:208)
36759 09-14 15:59:13.629 19446 19478 I flutter : #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.      dart:990)
36760 09-14 15:59:13.629 19446 19478 I flutter : #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:      930)
36761 09-14 15:59:13.629 19446 19478 I flutter : #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src      /scheduler/binding.dart:751)
36762 09-14 15:59:13.630 19446 19478 I flutter : #73     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
36763 09-14 15:59:13.630 19446 19478 I flutter : #74     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
36764 09-14 15:59:13.630 19446 19478 I flutter : #75     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
36765 09-14 15:59:13.630 19446 19478 I flutter : (elided one frame from package dart:async)
36766 09-14 15:59:13.632 19446 19478 I flutter :
36767 09-14 15:59:13.632 19446 19478 I flutter : The following RenderObject was being processed when the exception was fired:
36768 09-14 15:59:13.632 19446 19478 I flutter :   _RenderSliverFloatingPinnedPersistentHeaderForWidgets#c4b25 relayoutBoundary=up1 NEEDS-LAYOUT
36769 09-14 15:59:13.632 19446 19478 I flutter :   NEEDS-PAINT
36770 09-14 15:59:13.632 19446 19478 I flutter :   parentData: paintOffset=Offset(0.0, 0.0)
36771 09-14 15:59:13.632 19446 19478 I flutter :   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
36772 09-14 15:59:13.632 19446 19478 I flutter :   scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 0.0, crossAxisDirection:
36773 09-14 15:59:13.632 19446 19478 I flutter :   AxisDirection.right, viewportMainAxisExtent: 0.0, remainingCacheExtent: 250.0 cacheOrigin: 0.0 )
36774 09-14 15:59:13.632 19446 19478 I flutter :   geometry: null
36775 09-14 15:59:13.632 19446 19478 I flutter :   maxExtent: 130.0
36776 09-14 15:59:13.632 19446 19478 I flutter :   child position: null
36777 09-14 15:59:13.632 19446 19478 I flutter :   effective scroll offset: 0.0
36778 09-14 15:59:13.632 19446 19478 I flutter : This RenderObject had the following descendants (showing up to depth 5):
36779 09-14 15:59:13.632 19446 19478 I flutter :   RenderSemanticsAnnotations#6fd4d relayoutBoundary=up2 NEEDS-PAINT
36780 09-14 15:59:13.632 19446 19478 I flutter :     RenderAnnotatedRegion<SystemUiOverlayStyle>#cf883 relayoutBoundary=up3 NEEDS-PAINT
36781 09-14 15:59:13.632 19446 19478 I flutter :       RenderPhysicalModel#213b8 relayoutBoundary=up4 NEEDS-PAINT
36782 09-14 15:59:13.632 19446 19478 I flutter :         _RenderInkFeatures#d6331 relayoutBoundary=up5 NEEDS-PAINT
36783 09-14 15:59:13.632 19446 19478 I flutter :           RenderPositionedBox#88b14 relayoutBoundary=up6 NEEDS-PAINT
36784 09-14 15:59:13.632 19446 19478 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
36785 09-14 15:59:13.632 19446 19478 I flutter : Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
36786 09-14 15:59:13.634 19446 19478 I flutter : Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
36787 09-14 15:59:13.637 19446 19478 I flutter : OnUnitChangedAction
36788 09-14 15:59:13.643 19446 19478 I flutter : Another exception was thrown: Invalid argument(s): 74.0
36789 09-14 15:59:13.643 19446 19478 I flutter : Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
36790 09-14 15:59:13.643 19446 19478 I flutter : Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
36791 09-14 15:59:13.644 19446 19478 I flutter : Another exception was thrown: NoSuchMethodError: The method '>' was called on null.

```

`flutter analyze` does not report any issues.

```
>flutter doctor -v
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.7.3 at C:\Programs\flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\user1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\user1\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (2 available)
    • Samsung Galaxy S7, 8 0, API 26, 1440x2560 • 192.168.205.101:5555 • android-x86   • Android 8.0.0 (API 26)
    • SAMSUNG SM G935A                          • e61e99ab             • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

I don't see this problem when running in development with `flutter run`.
Also, I don't believe that the number 74.0 is significant in the adb logcat file since this number is different when run multiple times.
Performing a `flutter clean` does not affect the symptoms.

Similar issues:
https://github.com/flutter/flutter/issues/16492
https://github.com/flutter/flutter/issues/19948
https://github.com/flutter/flutter/issues/16160
https://github.com/dart-lang/sdk/issues/31181

**Comment by zoechi** [comment]
Can you provide a reduced/minimal running example (`main.dart`) that allows to reproduce?

It might be an issue in your code but hard to tell without a reproduction.

**Comment by Simpler1** [comment]
The problem can be seen by cloning the following repo:
`git clone https://github.com/MSzalek-Mobile/weight_tracker`
`cd weight_tracker`
`flutter build apk`
`flutter install`

Then startup the app on a device a couple of times.  The problem doesn't show up every time, but if you run it a couple of times it will appear.  I haven't been able to reduce this down to a minimal reproducible widget, but it appears to be related to the SliverAppBar based on the log file.
The problem never appears when debugging, so I'm expecting it is some kind of race condition.

**Comment by zoechi** [comment]
Thanks for the reproduction!
Does this mean you don't get this error in debug builds?

**Comment by zoechi** [comment]
I could reproduce

```
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.8.2 at /Users/zoechi/flutter/flutter
    • Framework revision 5ab9e70727 (8 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Pixel XL • HT69V0203649 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Simpler1** [comment]
I was able to resolve this by removing the "pinned" property:
```
SliverAppBar(
  // pinned: true,
  floating: true,
```
Are `pinned` and `floating` mutually exclusive?

**Comment by zoechi** [comment]
@Hixie I think there is room for improvement

**Comment by goderbauer** [comment]
Minimal example that reproduces the error:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: 60.0,
        color: Colors.green,
        child: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              pinned: true,
              floating: true,
            ),
          ],
        ),
      ),
    );
  }
}
```

Looking at a fix now.

@Simpler1 In general it's good practice to post a minimal example that reproduces the error with your bug instead of just pointing to your full app. That way, we can respond quicker to the actual problem.

**Comment by SnehaK3252** [comment]
Im getting this error when ever I run flutter app






I/flutter ( 9684): position changedLatLng(12.90241460087365, 77.61677742004395)
I/flutter ( 9684): Error occured: NoSuchMethodError: The getter 'mode' was called on null.
I/flutter ( 9684): Receiver: null
I/flutter ( 9684): Tried calling: mode

**Comment by SnehaK3252** [comment]
List<Address> results = [];

  bool isLoading = false;
  Coordinates coordinates;
  var addresses;
  var first;
  Future _onCameraMove(CameraPosition position) async {
    _lastMapPosition = position.target;
    print("position changed" + position.target.toString());
    coordinates =
        new Coordinates(position.target.latitude, position.target.longitude);
    addresses = Geocoder.local.findAddressesFromCoordinates(coordinates);
    // results = addresses.first;
    // print("${results.featureName} : ${results.coordinates}");
    this.setState(() {
      this.isLoading = true;
    });

    try {
      var geocoding = AppState.of(context).mode;

      var results = await geocoding.findAddressesFromCoordinates(coordinates);
      this.setState(() {
        this.results = results;
      });
    } catch (e) {
      print("Error occured: $e");
    } finally {
      this.setState(() {
        this.isLoading = false;
      });
    }
  }

**Comment by masumgandhi** [comment]
=> 
add this. It might solve your problem.
