### ISSUE TITLE
Cannot run another Flutter app on device if one is already running

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2188]
_Detailed issue description here. More information at [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/)_

### Steps to Reproduce
* App is running on your phone.
* Choose your phone from Atom's device chooser.
* Click the Run button.

Expected:

* App refreshes/runs on my phone.

Actual:

* Black screen on phone, errors in logs.

### Flutter Version

```
Flutter from git@github.com:flutter/flutter.git (on hackathon)
flutter revision: 4860e63f444cf3786a6b136430f3058a7b851041 (14 hours ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.
```

### Logs

Output from Atom:

```
flutter start --checked --debug-port=16201 --start-paused --device-id 031462ee213e73b9 • flutter logs
testme2/ • checked mode • debug
Building APK...
Signing the APK using the debug keystore.
Generated APK to build/app.apk.
Installing app.apk on device.
Starting lib/main.dart on Nexus 5...
Showing Nexus 5 logs:
--------- beginning of main
--------- beginning of system
I/flutter : Could not start Observatory HTTP server:
I/flutter : SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 8181
I/flutter : #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
I/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1137)
I/flutter : #2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
I/flutter : #3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
I/flutter : #4      _Future._completeWithValue (dart:async/future_impl.dart:424)
I/flutter : #5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
I/flutter : #6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
I/flutter : #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/flutter : #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
I/flutter : #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
I/flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
I/flutter : 
```

### Crash Reports
_Add relevant crash reports here_

**Comment by sethladd** [comment]
I manually killed all apps on my phone, and re-ran from Atom. It then worked.

**Comment by sethladd** [comment]
Probably a dupe of https://github.com/flutter/flutter/issues/1988
