### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by ashish0910** [flutter/flutter#21903]
After updating flutter (beta channel) I am getting this problem .

```
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because flutter_calendar <0.0.3 requires SDK version >=1.8.0 <2.0.0 and flutter_calendar >=0.0.3 depends on date_utils ^0.0.1, every version of flutter_calendar requires date_utils ^0.0.1.
So, because date_utils <0.1.0 requires SDK version >=1.20.1 <2.0.0 and gym depends on flutter_calendar ^0.0.1, version solving failed.
pub get failed (1)
exit code 1
```

## Logs
```
[  +49 ms] executing: [/Users/ashishaggarwal/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/ashishaggarwal/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +1 ms] executing: [/Users/ashishaggarwal/flutter/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/ashishaggarwal/flutter/] git log -n 1 --pretty=format:%H
[  +17 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3b309bda072a6b326e8aa4591a5836af600923ce
[        ] executing: [/Users/ashishaggarwal/flutter/] git log -n 1 --pretty=format:%ar
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[   +1 ms] executing: [/Users/ashishaggarwal/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.7.3-0-g3b309bda0
[ +180 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +80 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +146 ms] executing: /Users/ashishaggarwal/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/ashishaggarwal/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +13 ms] executing: idevice_id -h
[ +214 ms] /usr/bin/xcrun simctl list --json devices
[ +149 ms] No connected devices.
[        ] Run 'flutter emulators' to list and start any available device emulators.
[        ] If you expected your device to be detected, please run "flutter doctor" to diagnose
[        ] potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.
[  +21 ms] "flutter run" took 723ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:258:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:334:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:290:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:281:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/ashishaggarwal/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


this flutter doctor -v output

[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.7.3 at /Users/ashishaggarwal/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/ashishaggarwal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

```
this is pubspec.yaml file

name: gym
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: any
  firebase_auth: any
  flutter_calendar: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
```

thanks in advance .

**Comment by zoechi** [comment]
Closing because this is already discussed in #21421
