### ISSUE TITLE
AndroidView crash on android editTextView

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#21905]
When i add EditText View form android it show , but when i tap on it instead keyboard popup it crash with error like this 
```
 java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{882ea9e V.E...... ........ -87,87-45,207} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.flutter.plugin.platform.SingleViewPresentation$WindowManagerHandler.invoke(SingleViewPresentation.java:274)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy0.removeViewImmediate(Unknown Source)
        at android.widget.PopupWindow.dismissImmediate(PopupWindow.java:1910)
        at android.widget.PopupWindow.dismiss(PopupWindow.java:1855)
        at android.widget.Editor$HandleView.dismiss(Editor.java:4198)
        at android.widget.Editor$HandleView.hide(Editor.java:4203)
        at android.widget.Editor$SelectionModifierCursorController.hide(Editor.java:5177)
        at android.widget.Editor$TextActionModeCallback.onDestroyActionMode(Editor.java:3816)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onDestroyActionMode(DecorView.java:2260)
        at com.android.internal.view.FloatingActionMode.finish(FloatingActionMode.java:258)
        at android.widget.Editor.stopTextActionMode(Editor.java:2145)
        at android.widget.Editor.onTouchUpEvent(Editor.java:2109)
        at android.widget.TextView.onTouchEvent(TextView.java:8510)
        at android.view.View.dispatchTouchEvent(View.java:9943)
        at io.flutter.plugin.platform.PlatformViewsController.onTouch(PlatformViewsController.java:273)
        at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:98)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
09-15 14:43:34.933 24375-24392/com.therootsinternational.ezestate E/flutter: [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
    PlatformException(error, View=android.widget.PopupWindow$PopupDecorView{882ea9e V.E...... ........ -87,87-45,207} not attached to window manager, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
    <asynchronous suspension>
    #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:514:41)
    <asynchronous suspension>
    #3      _MotionEventsDispatcher.dispatchPointerEvent (package:flutter/src/rendering/platform_view.dart:396:20)
    #4      _MotionEventsDispatcher.handlePointerEvent (package:flutter/src/rendering/platform_view.dart:329:5)
    #5      _AndroidViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:263:18)
    #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
    #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
    #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
    #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
    #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
    #13     _invoke1 (dart:ui/hooks.dart:142:13)
    #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)
09-15 14:43:34.935 24375-24375/com.therootsinternational.ezestate D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
09-15 14:43:34.935 24375-24375/com.therootsinternational.ezestate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.therootsinternational.ezestate, PID: 24375
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4454)
        at android.view.ViewGroup.addView(ViewGroup.java:4295)
        at android.view.ViewGroup.addView(ViewGroup.java:4252)
        at android.widget.PopupWindow.createDecorView(PopupWindow.java:1355)
        at android.widget.PopupWindow.preparePopup(PopupWindow.java:1303)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1146)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1119)
        at android.widget.Editor$HandleView.updatePosition(Editor.java:4318)
        at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2968)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
    
    
    --------- beginning of system
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by shakil807g** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.8.2-pre.24, on Mac OS X 10.13.5 17F77, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    ✗ Android license status unknown.
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
Nishas-MacBook-Pro:~ nisha$

**Comment by zoechi** [comment]
Are you still seeing this with recent Flutter versions?
