### ISSUE TITLE
NPE with camera plugin

### ISSUE THREAD

**Issue by sestegra** [flutter/flutter#21917]
## Steps to Reproduce
1. Use camera plugin with similar code as example (camera-0.2.3)
2. Launch another application
3. App crashes

## Logs
```
09-16 14:31:53.920 28084 28084 E AndroidRuntime: Process: app, PID: 28084
09-16 14:31:53.920 28084 28084 E AndroidRuntime: java.lang.IllegalArgumentException: Surface was abandoned
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:70)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:184)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:94)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:489)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:672)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$2000(CameraPlugin.java:237)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at io.flutter.plugins.camera.CameraPlugin$Camera$3.onOpened(CameraPlugin.java:437)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:585)
09-16 14:31:53.920 28084 28084 E AndroidRuntime: 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:68)
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.7.3 at /flutter/0.7.3
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 21.1.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • Moto C Plus • ZW222422WM • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like a dup of #18348

**Comment by cyanglaz** [comment]
CC @bparrishMines @mklim

**Comment by YuzhouZhang** [comment]
Same error!
Suddenly crashed!
Not sure which code occur this, here is my log:

```
I/ExoPlayerImpl(13708): Init 1.3.1
I/OMXClient(13708): IOmx service obtained
W/AudioTrack(13708): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(13708): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/DynamiteModule(13708): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:11210
I/DynamiteModule(13708): Selected remote version of com.google.android.gms.ads.dynamite, version >= 11210
I/flutter (13708): InterstitialAd event MobileAdEvent.loaded
I/flutter (13708): prefs.getInt('rewardAmount')==0
W/ActivityThread(13708): handleWindowVisibility: no activity for token android.os.BinderProxy@39b6ec9
W/System  (13708): A resource failed to call release. 
I/rnersdictionar(13708): Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
D/DynamitePackage(13708): Instantiating com.google.android.gms.ads.ChimeraAdOverlayCreatorImpl
I/flutter (13708): InterstitialAd event MobileAdEvent.opened
I/flutter (13708): prefs.getInt('rewardAmount')==0
W/FlutterTextInput(13708): method not implemented
W/FlutterTextInput(13708): method not implemented
W/AudioManager(13708): Use of stream types is deprecated for operations other than volume control
W/AudioManager(13708): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/OMXClient(13708): IOmx service obtained
D/SurfaceUtils(13708): connecting to surface 0x774513a010, reason connectToSurface
I/MediaCodec(13708): [OMX.qcom.video.decoder.avc] setting surface generation to 14036997
D/SurfaceUtils(13708): disconnecting from surface 0x774513a010, reason connectToSurface(reconnect)
D/SurfaceUtils(13708): connecting to surface 0x774513a010, reason connectToSurface(reconnect)
W/AHierarchicalStateMachine(13708): Warning message AMessage(what = 'setP', target = 31) = {
W/AHierarchicalStateMachine(13708):   AMessage params = AMessage(what = 0x00000000) = {
W/AHierarchicalStateMachine(13708):                       int32_t android._video-scaling = 1
W/AHierarchicalStateMachine(13708):                     }
W/AHierarchicalStateMachine(13708): } unhandled in root state.
D/SurfaceUtils(13708): set up nativeWindow 0x774513a010 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
D/SurfaceUtils(13708): set up nativeWindow 0x774513a010 for 640x368, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
I/chatty  (13708): uid=10301(com.wingtech.quicklearnersdictionary) CodecLooper identical 2 lines
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
I/chatty  (13708): uid=10301(com.wingtech.quicklearnersdictionary) JNISurfaceTextu identical 1 line
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(13708): buffer descriptor with invalid usage bits 0x2000
E/GLConsumer(13708): [SurfaceTexture-0-13708-25] setDefaultBufferSize: GLConsumer is abandoned!
E/BufferQueueProducer(13708): [SurfaceTexture-0-13708-25] query: BufferQueue has been abandoned
E/Legacy-CameraDevice-JNI(13708): LegacyCameraDevice_nativeDetectSurfaceDimens: Error while querying surface width No such device (-19).
D/AndroidRuntime(13708): Shutting down VM
E/AndroidRuntime(13708): FATAL EXCEPTION: main
E/AndroidRuntime(13708): Process: com.wingtech.quicklearnersdictionary, PID: 13708
E/AndroidRuntime(13708): java.lang.IllegalArgumentException: Surface was abandoned
E/AndroidRuntime(13708): 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:84)
E/AndroidRuntime(13708): 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260)
E/AndroidRuntime(13708): 	at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145)
E/AndroidRuntime(13708): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:508)
E/AndroidRuntime(13708): 	at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:742)
E/AndroidRuntime(13708): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$1200(CameraPlugin.java:285)
E/AndroidRuntime(13708): 	at io.flutter.plugins.camera.CameraPlugin$Camera$3.onOpened(CameraPlugin.java:506)
E/AndroidRuntime(13708): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:143)
E/AndroidRuntime(13708): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(13708): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13708): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(13708): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(13708): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13708): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(13708): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(13708): Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
E/AndroidRuntime(13708): 	at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
E/AndroidRuntime(13708): 	at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:606)
E/AndroidRuntime(13708): 	at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:82)
E/AndroidRuntime(13708): 	... 14 more
I/Process (13708): Sending signal. PID: 13708 SIG: 9
Application finished.
```

**Comment by bparrishMines** [comment]
Hi @sestegra @YuzhouZhang,

Are you still having this problem?

With the latest version [5.0.0](https://pub.dartlang.org/packages/camera/versions/0.5.0), we removed the automatic handling of activity lifecycles. You should call `CameraController.dispose()`
when your app is sent to the background. Then initialize a new `CameraController` when it is in the foreground again.

You can get lifecycles by using the [WidgetsBindingObserver](https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver-class.html) with the `didChangeAppLifecycleState` method.

**Comment by YuzhouZhang** [comment]
@bparrishMines I have tested for two days, and there is no crash anymore.
Thank you for your hard work.

**Comment by sestegra** [comment]
@sestegra No more crash
Thank you
