### ISSUE TITLE
editable.dart '_listenerAttached': is not true.

### ISSUE THREAD

**Issue by ziggycrane** [flutter/flutter#21919]
So I have TextFormField and a DropdownButton in a same screen. 

If I have TextFormField focused and then I press on DropdownButton, I get this error:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building _ScrollableScope:
flutter: 'package:flutter/src/rendering/editable.dart': Failed assertion: line 495 pos 14:
flutter: '_listenerAttached': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderEditable.hasFocus= (package:flutter/src/rendering/editable.dart:495:14)
flutter: #3      _Editable.updateRenderObject (package:flutter/src/widgets/editable_text.dart:1024:9)
flutter: #4      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4300:12)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #30     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #35     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #36     _invoke (dart:ui/hooks.dart:128:13)
flutter: #37     _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```
Flutter doctor -v
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-LV)
    • Flutter version 0.7.3 at /Users/ziggycrane/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/ziggycrane/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/ziggycrane/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • iPhone X • A39CDDE0-B999-472C-843D-5CF2917756A0 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Merging with #21640
