### ISSUE TITLE
Flutter upgrade cannot run application anymore (Android Studio)

### ISSUE THREAD

**Issue by vijaykanta** [flutter/flutter#21912]
I have upgraded my Flutter version from beta 0.5 to beta 0.7.3 as I found out I had difficulties running few plugins. The following is the error I get.
```
Note: /Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.20/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.20/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.0.2/android/src/main/java/io/flutter/plugins/firebase/storage/FirebaseStoragePlugin.java:293: warning: [unchecked] unchecked cast
    Map<String, String> customMetadata = (Map<String, String>) map.get("customMetadata");
                                                                      ^
  required: Map<String,String>
  found:    Object
1 warning
Note: /Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_multiple-0.0.2/android/src/main/java/com/ruiyu/imagepickermultiple/TransparentActivity.java uses unchecked or unsafe operations.`
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/apple/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.6.5/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Built build/app/outputs/apk/debug/app-debug.apk.
Finished with error: NoSuchMethodError: The method 'allElements' was called on null.
Receiver: null
Tried calling: allElements("activity")
```
And here's the output for flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
Where is the allElements("activity") code? I can't find it.

**Comment by vijaykanta** [comment]
Just checked in command line
`flutter run`

gives the following output
`Launching lib/main.dart on SM G900H in debug mode...`
`Initializing gradle...                                       1.9s`
`Resolving dependencies...                                    6.1s`

`Oops; flutter has exited unexpectedly.`
`Sending crash report to Google.`
`Crash report sent (report ID: 771cdf61b4cddbb6)`
`Crash report written to /Users/apple/AndroidStudioProjects/cityjan/flutter_03.log;`
`please let us know at https://github.com/flutter/flutter/issues.`

**Comment by kasalian** [comment]
AM having the same issue see a copy of my log file below


Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\XXXXXXXXXXXXX\Documents\Flutter app\upliftapp\android\gradlew.bat -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:227:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:242:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:181:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#5      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:97:23)
<asynchronous suspension>
#8      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:316:30)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:272:21)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:259:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:411:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._complete (dart:async/future_impl.dart:476:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 0.7.3 at C:\src\flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Studio
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\Studio
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code, 64-bit edition (version 1.27.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • TECNO WX3P • 026061081G003406 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by vijaykanta** [comment]
Okay, here's the latest crash log

```
[flutter_05.log](https://github.com/flutter/flutter/files/2387231/flutter_05.log)
```

**Comment by zoechi** [comment]
`pub cache repair` or `flutter packages pub cache repair` might help

**Comment by vijaykanta** [comment]
Actually I fixed the problem by removing things that I only introduced in the Android manifest file. I removed the 

`tools:replace="android:label"`

from the application tag for whatever reason I put there, then do

`flutter clean`

and voila! it works straight away..

Thanks anyway @zoechi

**Comment by zoechi** [comment]
@vijaykanta thanks for the update. Glad to hear.
I assume it's ok to close then? 
Just add a comment if you think it should be reopened.

**Comment by kroikie** [comment]
@vijaykanta

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/660. Any further collaboration will be done there.
