### ISSUE TITLE
Unable to load asset: AssetManifest.json after HotReload

### ISSUE THREAD

**Issue by sugihartolim** [flutter/flutter#21920]
## Steps to Reproduce
1. create a new application 
2. have an image component on the page
    ```
    this.logo = Center(
        child: Image.asset('assets/logo.jpg'),
    );
   ```
3. run on device/emulator. 
4. app will work fine, image will be shown OK. 
5. modify something in the page. 
6. file/save-all , hot reload. 
7. unhandled exception: Unable to load asset: AssetManifest.json 

Happens in both 'beta' (0.7.3)  and 'master' (0.8.5pre-4)  channel. 
Happens no matter which IDE used (IntelliJ, vs-code, cli). 
Happens on genymotion, noxplayer, and android emulator. 

## pubspec.yaml
    
  ```
  flutter:
    uses-material-design: true
    assets:
      - assets/
   ```

## Logs
```
E/flutter (10387): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (10387): Unable to load asset: AssetManifest.json
E/flutter (10387): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (10387): <asynchronous suspension>
E/flutter (10387): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (10387): <asynchronous suspension>
E/flutter (10387): #2      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:163:18)
E/flutter (10387): #3      CachingAssetBundle.loadStructuredData (package:flutter/src/services/asset_bundle.dart:184:5)
E/flutter (10387): #4      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:175:18)
E/flutter (10387): #5      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:5)
E/flutter (10387): #6      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:585:20)
E/flutter (10387): #7      _ImageState.reassemble (package:flutter/src/widgets/image.dart:579:5)
E/flutter (10387): #8      StatefulElement._reassemble (package:flutter/src/widgets/framework.dart:3778:11)
E/flutter (10387): #9      Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #11     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #12     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #14     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #15     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #17     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #18     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4784:14)
E/flutter (10387): #20     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #21     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4784:14)
E/flutter (10387): #23     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #24     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4784:14)
E/flutter (10387): #26     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #27     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #29     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #30     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #32     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #33     StatefulElement._reassemble (package:flutter/src/widgets/framework.dart:3779:11)
E/flutter (10387): #34     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #36     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #37     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #39     Element._reassemble (package:flutter/src/widgets/framework.dart:2588:5)
E/flutter (10387): #40     Element._reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:2589:13)
E/flutter (10387): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3712:14)
E/flutter (10387): #42     Element._reassemble (package:flutter/src/
```

```
[√] Flutter (Channel master, v0.8.5-pre.5, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.8.5-pre.5 at C:\DEV\flutter
    • Framework revision 1ad538e454 (2 days ago), 2018-09-14 16:47:28 -0700
    • Engine revision 24d94601b9
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\DEV\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\DEV\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • SM N950W • 127.0.0.1:62026 • android-x86 • Android 5.1.1 (API 22)

• No issues found!
```

**Comment by sugihartolim** [comment]
Updating to android 6.0 'fixed' the problem. Closing for now. Thank you.

**Comment by therenca** [comment]
Am still getting the error even after updating to android 6.0 in the nox player

**Comment by fax1ty** [comment]
> @therenca this issue is closed since quite some time.
> Please create a new issue with full information.

Nox with Android 7.1 but 

![image](https://user-images.githubusercontent.com/26363214/56160885-5596d100-5fd9-11e9-8e25-f162ef000791.png)

any update to the code which affects the work with asset image leads to this exception

**Comment by therenca** [comment]
I decided we should just stick to standard accepted dev tools like the android studio's emulator...
Thanks.

**Comment by huy-lv** [comment]
Hope you guys make it work on Nox :D I dont want to use AVD because it spend RAM quite much

**Comment by Saifallak** [comment]
any updates on this ?
getting same error on NOX

```
[√] Flutter (Channel dev, v1.5.8, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
    • Flutter version 1.5.8 at C:\SDKs\flutter
    • Framework revision 0ba67226ee (11 days ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7019

[√] Connected device (1 available)
    • SM G925F • 127.0.0.1:62001 • android-x86 • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by shahinvx** [comment]
just delete the build folder and run your project again..it shod fixed....
