### ISSUE TITLE
Problem using cloud_firestore

### ISSUE THREAD

**Issue by adriendulong** [flutter/flutter#21951]
I have seen the other opened problem about cloud_firestore.
However mine seems different.
I have also a problem when cocoapod try to install cloud_firestore.

This is what I get 

```

CocoaPods' output:
↳
Preparing
Analyzing dependencies
Inspecting targets to integrate
Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
Fetching external sources
-> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
-> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
-> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Resolving dependencies of `Podfile`
[!] Unable to find a specification for `Firebase/Database` depended upon by `cloud_firestore`
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
Error running pod install
```

And if I run `flutter run -v` I get 

``` 
[  +77 ms] Building Runner.app for C8322200-306D-4478-8969-B5124B3FA08F.
[  +16 ms] executing: script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "C8322200-306D-4478-8969-B5124B3FA08F"
[  +55 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS "C8322200-306D-4478-8969-B5124B3FA08F""
[   +5 ms] [DEVICE LOG] Timestamp                       (process)[PID]
[ +179 ms] Skipping kernel compilation. Fingerprint match.
[ +298 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +57 ms] Wrote build/flutter_assets
[   +1 ms] executing: /usr/bin/xcrun simctl get_app_container C8322200-306D-4478-8969-B5124B3FA08F com.example.flutterFirebase
[        ] executing: /usr/bin/killall Runner
[ +141 ms] executing: [ios/] /usr/bin/xcodebuild -list
[ +713 ms] Exit code 0 from: /usr/bin/xcodebuild -list
[        ] Information about project "Runner":
               Targets:
                   Runner

               Build Configurations:
                   Debug
                   Release

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   Runner
[   +2 ms] Trying to resolve native pub services.
[   +2 ms] Looking for YAML at 'pubspec.yaml'
[   +1 ms] No services specified in the manifest
[        ] Found 0 service definition(s).
[   +1 ms] Copying service frameworks to '/Users/adriendulong/Documents/Dev/flutter_firebase/ios/Frameworks'.
[        ] Creating service definitions manifest at 'ios/ServiceDefinitions.json'
[  +20 ms] executing: pod --version
[ +525 ms] 1.5.3
[   +3 ms] Running pod install...
[ +811 ms] Running pod install... (completed)
[        ] CocoaPods' output:
           ↳
[        ]   Preparing

           Analyzing dependencies

           Inspecting targets to integrate
             Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

           Fetching external sources
           -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
           -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
           -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`

           Resolving dependencies of `Podfile`
           [!] Unable to find a specification for `Firebase/Database` depended upon by `cloud_firestore`

           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in `activate_new_spec'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
           /usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
           /usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
           /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
           /usr/local/bin/pod:22:in `load'
           /usr/local/bin/pod:22:in `<main>'

[   +4 ms] Error running pod install
[   +1 ms] Error launching application on iPhone X.
[  +16 ms] "flutter run" took 6 280ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:417:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:356:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Can you please try if `pod install` in `ios/` helps?

Please add the output of `flutter doctor -v`.

**Comment by adriendulong** [comment]
I got the same thing doing `pod install` in `ios/`

```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
[!] Unable to find a specification for `Firebase/Database` depended upon by `cloud_firestore`
```

And this is what I get when I do `flutter doctor -v `:

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale fr-FR)
    • Flutter version 0.8.2 at /Users/adriendulong/Documents/Dev/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/adriendulong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone XS Max • 4AFE0DCD-1F8B-4840-A39C-0FA87DE01C9D • ios • iOS 12.0 (simulator)

• No issues found!
```

Could it be because of the minimum target version that was not set in previous version of flutter? Even if I updated it, maybe it did not update my project?

Thanks for your help

**Comment by PieterAelse** [comment]
I have this same issue... any solution or workaround?

**Comment by dschmucki** [comment]
I had the same problem and had to add `source 'https://github.com/CocoaPods/Specs.git'` to my `Podfile` as I added another source as well which resulted in incomplete specs.

**Comment by kroikie** [comment]
@adriendulong

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/659. Any further collaboration will be done there.
