### ISSUE TITLE
Lexical or Preprocessor Issue - 'connectivity/ConnectivityPlugin.h' file not found

### ISSUE THREAD

**Issue by tiagosito** [flutter/flutter#21989]
Unfortunately I automatically updated the xCode to 10 and received some errors...
I followed this step [#20685](https://github.com/flutter/flutter/issues/20685#issuecomment-413524718)

**but now it results in the following error**

<img width="1552" alt="error" src="https://user-images.githubusercontent.com/17324575/45692598-8ee58c00-bb31-11e8-903e-edf008eb865b.png">

**flutter doctor -v**
```
MacBook-Pro-de-Tiago:adventist_student tiagosito$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale pt-BR)
    • Flutter version 0.7.3 at /Users/tiagosito/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/tiagosito/Library/Android/sdk
    • Android NDK at /Users/tiagosito/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (3 available)
    • iPhone X      • B9E97C88-1755-4309-AE5B-142CB58B85F7 • ios • iOS 12.0 (simulator)
    • iPhone XS     • B11C819A-7DB5-4DE4-8394-E39BB6DFE457 • ios • iOS 12.0 (simulator)
    • iPhone XS Max • 169CE4DC-40AF-4FB5-B708-225A8C63F6FF • ios • iOS 12.0 (simulator)

• No issues found!
```

**flutter run --verbose**
```
MacBook-Pro-de-Tiago:adventist_student tiagosito$ flutter run --verbose
[  +36 ms] executing: [/Users/tiagosito/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/tiagosito/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/tiagosito/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/tiagosito/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3b309bda072a6b326e8aa4591a5836af600923ce
[        ] executing: [/Users/tiagosito/flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] executing: [/Users/tiagosito/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.7.3-0-g3b309bda07
[ +175 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +71 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +124 ms] executing: /Users/tiagosito/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/tiagosito/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] executing: idevice_id -h
[ +369 ms] /usr/bin/xcrun simctl list --json devices
[ +256 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] iPhone X      • B9E97C88-1755-4309-AE5B-142CB58B85F7 • ios • iOS 12.0 (simulator)
[        ] iPhone XS     • B11C819A-7DB5-4DE4-8394-E39BB6DFE457 • ios • iOS 12.0 (simulator)
[        ] iPhone XS Max • 169CE4DC-40AF-4FB5-B708-225A8C63F6FF • ios • iOS 12.0 (simulator)
[  +14 ms] "flutter run" took 964ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:258:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:334:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:290:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:281:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/tiagosito/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by tiagosito** [comment]
**Solved**

**I followed the option 2** [#20685](https://github.com/flutter/flutter/issues/20685#issuecomment-421511890)

I've run the command 
```flutter clean```
and
``` flutter run```
Then did not work... I repeated the commands and again did not work.
So I restarted the notebook ... I repeated the commands... then it worked.

**Comment by amreniouinnovent** [comment]
1-in Xcode from the Product menu choose **clean**
2-while you are in the ios folder run on **terminal** run>> `pod install`
My issue I added the plugin while I was working on windows environment.

**Comment by shellywu** [comment]
open runner.xcworkspace ,it worked!

**Comment by jonsamwell** [comment]
I am still getting this issue.  I have tried all the suggestions but nothing works. Clean, removing podlock file, switch between the Xcode legacy and new build systems.  This is a real blocker.  The app will not build to launch.

Using Xcode 10.1
Connectivity ^0.4.3+7

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/jonsamwell/Development/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonsamwell/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone XR • 283A2870-C3FD-4E8A-B446-0BDE837817E3 • ios • iOS 12.1 (simulator)

• No issues found!
``

**Comment by GaboBrandX** [comment]
> open runner.xcworkspace ,it worked!

Wow! I can't explain why.. but it did worked for me. Thanks!

**Comment by jonsamwell** [comment]
I got it working but creating a new swift project

**Comment by phelipepalte** [comment]
> 1-in Xcode from the Product menu choose **clean**
> 2-while you are in the ios folder run on **terminal** run>> `pod install`
> My issue I added the plugin while I was working on windows environment.
> Update:
> In Xcode link the xconfig file to its path

How to link the xconfig flie?

**Comment by jchenx2** [comment]
> open runner.xcworkspace ,it worked!

great!

**Comment by KyllianDM** [comment]
Hello,
This issue is always here, and open the .xcworkspace didn't solve it.

**Comment by Garciconx** [comment]
> Hello,
> This issue is always here, and open the .xcworkspace didn't solve it.

same issue here!

**Comment by nogicoder** [comment]
I've tried anything possible, and the only thing that finally did work for me was to re-init a new project and move the neccessary files over guys.

**Comment by LaCharcaSoftware** [comment]
For me the problem was that I was trying to create the archive from the Runner.xcodeproj instead of the Runner.xcworkspace (which defines the pods targets). Clean and create build folder and switching to that project solved the issue to produce the archive.

To resolve this:
1) Clean the build folder from terminal: flutter clean
2) Create the build folder from terminal: flutter build ios
3) Open the Runner.xcworkspace
4) Product --> Archive.
