### ISSUE TITLE
'package:flutter/src/widgets/heroes.dart': Failed assertion

### ISSUE THREAD

**Issue by yanwu401909** [flutter/flutter#22025]
```
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(15224): onResume setting current activity to this
Syncing files to device Pixel XL...
I/flutter (15224): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15224): The following assertion was thrown during a scheduler callback:
I/flutter (15224): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 322 pos 12: '() {
I/flutter (15224):       final Animation<double> initial = initialManifest.animation;
I/flutter (15224):       switch (initialManifest.type) {
I/flutter (15224):         case _HeroFlightType.pop:
I/flutter (15224):           return initial.value == 1.0 && initial.status == AnimationStatus.reverse;
I/flutter (15224):         case _HeroFlightType.push:
I/flutter (15224):           return initial.value == 0.0 && initial.status == AnimationStatus.forward;
I/flutter (15224):       }
I/flutter (15224):     }()': is not true.
I/flutter (15224):
I/flutter (15224): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15224): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15224): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15224):   https://github.com/flutter/flutter/issues/new
I/flutter (15224):
I/flutter (15224): When the exception was thrown, this was the stack:
I/flutter (15224): #2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart)
I/flutter (15224): #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:532:64)
I/flutter (15224): #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
I/flutter (15224): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15224): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter (15224): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (15224): #9      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (15224): #10     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (15224): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (15224): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (15224): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/FlutterActivityDelegate(15224): onResume setting current activity to this
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
a minimal reproduction
instructions what steps to make to reproduce the error.

**Comment by zoechi** [comment]
@I-am-original can you please provide a minimal runnable reproduction?

**Comment by I-am-original** [comment]
@zoechi you can find my repo here https://github.com/I-am-original/screens_flutter

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by zoechi** [comment]
I can't reproduce.
Now I get instead 
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,056ms.
I/flutter ( 5497): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5497): The following assertion was thrown during a scheduler callback:
I/flutter ( 5497): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 248 pos 12: 'box != null &&
I/flutter ( 5497): box.hasSize': is not true.
I/flutter ( 5497): 
I/flutter ( 5497): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5497): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5497): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5497):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5497): 
I/flutter ( 5497): When the exception was thrown, this was the stack:
I/flutter ( 5497): #2      _HeroState.startFlight (package:flutter/src/widgets/heroes.dart:248:12)
I/flutter ( 5497): #3      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:451:21)
I/flutter ( 5497): #4      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:684:60)
I/flutter ( 5497): #5      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:630:11)
I/flutter ( 5497): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 5497): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:936:9)
I/flutter ( 5497): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 5497): #12     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 5497): #13     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 5497): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 5497): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5497): Another exception was thrown: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 411 pos 14: 'overlayEntry != null': is not true.
```

I have reduced the original example quite a bit to track that error down and 
it seems to be related to the FABs. If the one commented out now is commented in, the error occurs.
When one or both are commented out, the error does not occur.

To reproduce click 4x until `Modal 2` is shown and then `DONE` and the error shows.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: <String, WidgetBuilder>{
        '/': (context) => HomePage(title: 'Screen 1'),
        '/2': (context) => SecondPage(title: 'Screen 2'),
        '/3': (context) => ThirdPage(title: 'Screen 3'),
        '/4': (context) => FourPage(),
        '/10': (context) => ModalOne(title: 'Modal 1'),
        '/11': (context) => ModalTwo(title: 'Modal 2'),
      },
    );
  }
}

class SlideRightRoute extends PageRouteBuilder {
  final Widget widget;
  SlideRightRoute({this.widget})
      : super(pageBuilder: (BuildContext context, Animation<double> animation,
            Animation<double> secondaryAnimation) {
          return widget;
        }, transitionsBuilder: (BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            Widget child) {
          return SlideTransition(
            position: Tween<Offset>(
              begin: const Offset(0.0, 1.0),
              end: Offset.zero,
            ).animate(secondaryAnimation),
            child: child,
          );
        });
}

class ModalOne extends StatefulWidget {
  ModalOne({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<ModalOne> createState() => _PageState();
}

class _PageState extends State<ModalOne> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          FlatButton(
              child: Text('NEXT',
                  style: Theme.of(context)
                      .textTheme
                      .body1
                      .copyWith(color: Colors.white)),
              onPressed: () {
                Navigator.push(
                  context,
                  CupertinoPageRoute(
                    builder: (context) => ModalTwo(title: "Modal 2"),
                    fullscreenDialog: true,
                  ),
                );
              })
        ],
      ),
      body: Container(
        decoration: BoxDecoration(color: Colors.blueAccent),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.display1,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class ModalTwo extends StatefulWidget {
  ModalTwo({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<ModalTwo> createState() => _ModalTwoState();
}

class _ModalTwoState extends State<ModalTwo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          FlatButton(
              child: Text('DONE',
                  style: Theme.of(context)
                      .textTheme
                      .body1
                      .copyWith(color: Colors.white)),
              onPressed: () {
                Navigator.pushAndRemoveUntil(
                  context,
                  CupertinoPageRoute(
                    builder: (context) => FourPage(),
                  ),
                  ModalRoute.withName('/'),
                );
              })
        ],
      ),
      body: Container(
        decoration: BoxDecoration(color: Colors.blueAccent),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class FourPage extends StatefulWidget {
  final String title = "Screen 4";

  @override
  State<FourPage> createState() => _FourPageState();
}

class _FourPageState extends State<FourPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        decoration: BoxDecoration(color: Colors.grey),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                'You have pushed the button this many times:',
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          FlatButton(
              child: Text('NEXT',
                  style: Theme.of(context)
                      .textTheme
                      .body1
                      .copyWith(color: Colors.white)),
              onPressed: () {
                Navigator.push(
                  context,
                  CupertinoPageRoute(
                    settings: RouteSettings(name: '/2'),
                    builder: (context) => SecondPage(title: "Screen 2"),
                  ),
                );
              })
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class ThirdPage extends StatefulWidget {
  ThirdPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<ThirdPage> createState() => _ThirdPageState();
}

class _ThirdPageState extends State<ThirdPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          FlatButton(
              child: Text('NEXT',
                  style: Theme.of(context)
                      .textTheme
                      .body1
                      .copyWith(color: Colors.white)),
              onPressed: () {
                Navigator.push(
                  context,
                  CupertinoPageRoute(
                    builder: (context) => ModalOne(title: "Modal 1"),
                    fullscreenDialog: true,
                  ),
                );
              })
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
    );
  }
}

class SecondPage extends StatefulWidget {
  SecondPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<SecondPage> createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          FlatButton(
              child: Text('NEXT',
                  style: Theme.of(context)
                      .textTheme
                      .body1
                      .copyWith(color: Colors.white)),
              onPressed: () {
                Navigator.push(
                  context,
                  CupertinoPageRoute(
                    builder: (context) => ThirdPage(title: "Screen 3"),
                  ),
                );
              })
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by Piinks** [comment]
Following up on @zoechi 's reproduction, I've distilled this down a bit further from:

### Code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: <String, WidgetBuilder>{
        '/': (context) => HomePage(),
        '/2': (context) => SecondPage(),
        '/e': (context) => ErrorPage(),
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
        actions: <Widget>[
          FlatButton(
            child: Text('NEXT'),
            onPressed: () {
              Navigator.pushNamed(
                context,
                '/2',
              );
            }
          )
        ],
      ),
      floatingActionButton: FloatingActionButton(
        // heroTag: null,
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Screen 2'),
        actions: <Widget>[
          FlatButton(
            child: Text('NEXT'),
            onPressed: () {
              Navigator.pushNamed( // AndRemoveUntil(
                context,
                '/e',
                // ModalRoute.withName('/'),
              );
            }
          )
        ],
      ),
    );
  }
}

class ErrorPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Error Screen'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}
```

### Log

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 342 pos 12: 'box != null &&
flutter: box.hasSize': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _HeroState.startFlight 
package:flutter/…/widgets/heroes.dart:342
flutter: #3      _HeroFlight.start 
package:flutter/…/widgets/heroes.dart:560
flutter: #4      HeroController._startHeroTransition 
package:flutter/…/widgets/heroes.dart:811
flutter: #5      HeroController._maybeStartHeroTransition.<anonymous closure> 
package:flutter/…/widgets/heroes.dart:757
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1016
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:966
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:874
flutter: #12     _invoke  (dart:ui/hooks.dart:236:10)
flutter: #13     _drawFrame  (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ═════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 520 pos 14: 'overlayEntry != null': is not true.
```


The error seems to be around the call to `Navigator.pushNamedAndRemoveUntil(...)` on line 55, which is commented out here to illustrate the trip. 

The issue does seem to be related to `FloatingActionButton`, as `Navigator.pushNamedAndRemoveUntil(...)` does not result in an error if the `heroTag` property of the button is changed.

Will continue to look into this.
