### ISSUE TITLE
Error while using cloud_firestore plugin 

### ISSUE THREAD

**Issue by jashanpj** [flutter/flutter#22036]
## Steps to Reproduce
   
Create a new project, add cloud_firestore: ^0.8.0 plugin in the dependencies, add Google services-info.plist as per the flutter firebase code lab documentation. Call a collection using stream. 

The main file, just calling a collection.
     <script src="https://gist.github.com/jashanpj/961f01305b3c98c70dbbdd5a6aec28ba.js"></script>

 Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Core":
## Logs

```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    
    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Core":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Core
    
    Specs satisfying the `Firebase/Core` dependency were found, but they required a higher minimum deployment target.
    CocoaPods could not find compatible versions for pod "GoogleUtilities/AppDelegateSwizzler":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Core was resolved to 5.8.0, which depends on
            FirebaseAnalytics (= 5.1.2) was resolved to 5.1.2, which depends on
              GoogleUtilities/AppDelegateSwizzler (~> 5.2.0)
    
    Specs satisfying the `GoogleUtilities/AppDelegateSwizzler (~> 5.2.0)` dependency were found, but they required a higher minimum deployment target.
    CocoaPods could not find compatible versions for pod "gRPC-Core":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Firestore was resolved to 5.8.0, which depends on
            FirebaseFirestore (= 0.13.3) was resolved to 0.13.3, which depends on
              gRPC-C++ (~> 0.0.3) was resolved to 0.0.3, which depends on
                gRPC-C++/Implementation (= 0.0.3) was resolved to 0.0.3, which depends on
                  gRPC-Core (= 1.14.0)
    
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
          Firebase/Firestore was resolved to 5.8.0, which depends on
            FirebaseFirestore (= 0.13.3) was resolved to 0.13.3, which depends on
              gRPC-ProtoRPC (~> 1.0) was resolved to 1.14.1, which depends on
                gRPC-ProtoRPC/Main (= 1.14.1) was resolved to 1.14.1, which depends on
                  gRPC (= 1.14.1) was resolved to 1.14.1, which depends on
                    gRPC/Main (= 1.14.1) was resolved to 1.14.1, which depends on
                      gRPC-Core (= 1.14.1)
    
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
        [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
    
        export LANG=en_US.UTF-8
        [0m
    
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone X.
```

```
```

```
[✓] Flutter (Channel dev, v0.9.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.9.1 at /Users/jashan/Documents/Programming/Flutter/flutter
    • Framework revision bf7c27095c (18 hours ago), 2018-09-18 13:39:21 -0700
    • Engine revision 9e315e6465
    • Dart version 2.1.0-dev.4.0.flutter-050561fd82

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/jashan/Library/Android/sdk
    • Android NDK at /Users/jashan/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5556                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 473AE7A7-1E8A-4513-965A-F58742C2AF3A • ios         • iOS 11.3 (simulator)

• No issues found!

```

**Comment by ened** [comment]
@jashanpj please confirm the error still exists using the latest Flutter & `cloud_firestore` plugin.

**Comment by kroikie** [comment]
@jashanpj

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/656. Any further collaboration will be done there.
