### ISSUE TITLE
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 661 pos 12: 'pixels != I/flutter ( 9650): null': is not true.

### ISSUE THREAD

**Issue by hitanshu1** [flutter/flutter#22042]
```
Performing hot restart...
Syncing files to device IF9031...
Restarted application in 3,355ms.
W/BiChannelGoogleApi( 9650): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@e7928d4
D/FirebaseAuth( 9650): Notifying id token listeners about user ( 0e7g6oYPR7UcLhRpaobvfuyIGSj1 ).
D/FirebaseApp( 9650): Notifying auth state listeners.
D/FirebaseApp( 9650): Notified 1 auth state listeners.
I/flutter ( 9650): Signed in as Hitanshu Gogoi
D/SQLiteDatabase( 9650): beginTransaction()
D/SQLiteDatabase( 9650): endTransaction()
I/flutter ( 9650): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9650): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 9650): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 661 pos 12: 'pixels !=
I/flutter ( 9650): null': is not true.
I/flutter ( 9650): 
I/flutter ( 9650): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9650): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9650): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9650):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9650): 
I/flutter ( 9650): When the exception was thrown, this was the stack:
I/flutter ( 9650): #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart:661:12)
I/flutter ( 9650): #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:255:11)
I/flutter ( 9650): #4      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:324:14)
I/flutter ( 9650): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3833:12)
I/flutter ( 9650): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter ( 9650): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4754:16)
I/flutter ( 9650): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #29     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4754:16)
I/flutter ( 9650): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 9650): #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 9650): #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #68     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter ( 9650): #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter ( 9650): #77     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter ( 9650): #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter ( 9650): #79     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter ( 9650): #80     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter ( 9650): #81     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2341:27)
I/flutter ( 9650): #82     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2173:15)
I/flutter ( 9650): #83     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2340:7)
I/flutter ( 9650): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:655:18)
I/flutter ( 9650): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9650): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9650): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9650): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9650): #89     _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 9650): #90     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 9650): (elided 2 frames from class _AssertionError)
I/flutter ( 9650): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/SQLiteDatabase( 9650): beginTransaction()
D/SQLiteDatabase( 9650): endTransaction()
D/SQLiteDatabase( 9650): beginTransaction()
D/SQLiteDatabase( 9650): endTransaction()
```

my main dart code is below 
```
[import 'package:flutter/material.dart';
import 'package:learningdemo/lancherpage.dart';
import 'package:learningdemo/Pages/loginpage.dart';
import 'package:learningdemo/Pages/learn/learn.dart' as learn;
import 'package:learningdemo/Pages/Play/play.dart' as play;
import 'package:learningdemo/Pages/ActivityFeed/acitvityfeed.dart' as Activity;
import 'package:learningdemo/Pages/Questionanddis/q&a_discussion.dart' as qa;
import 'package:learningdemo/utils/app_utils.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:learningdemo/utils/google_sign_in.dart';
import 'package:learningdemo/Model/Constants.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:learningdemo/Pages/Play/play.dart';
import 'package:learningdemo/Pages/learn/learn.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:learningdemo/Admin/adminmain.dart';
import 'package:learningdemo/Pages/profileTab/otheruserviewphofile.dart';
import 'package:learningdemo/Pages/ActivityFeed/acitvityfeed.dart';
import 'package:learningdemo/Pages/Questionanddis/q&a_discussion.dart';
import 'colors.dart';
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';

String selectedProfile = GOOGLE;

void main(){
  runApp(new MaterialApp(
    title: "Edu",
    home: LauncherPage(),
  debugShowCheckedModeBanner: false,
  routes: <String, WidgetBuilder>{
    LoginPage.routeName: (context) => new LoginPage(),
    Home.routeName: (context) => new Home(),
   ProfilePage.routeName:(context)=>new ProfilePage(),
  AdminMain.routeName:(context)=>new AdminMain()

  },
      theme: buildThemeData(),
  ));
}ThemeData buildThemeData() {
  final baseTheme = ThemeData(
  );

  return baseTheme.copyWith(
//    canvasColor: Colors.black,
//    backgroundColor: Colors.black,
    primaryColor: Colors.blueGrey,
//    primaryColorDark: kPrimaryDark,
    primaryColorLight: kPrimaryLight,
//    accentColor: kSecondaryColor,
    bottomAppBarColor:kSecondaryDark,
    buttonColor: kSecondaryColor,
    sliderTheme: SliderThemeData.fromPrimaryColors(
      primaryColor: Colors.blueGrey,
      primaryColorDark: kPrimaryDark,
      primaryColorLight: Colors.black,
      valueIndicatorTextStyle: TextStyle(),
    ),
//    textTheme: TextTheme().copyWith(
//        subhead: TextStyle(
//            color: Colors.black
//        )),
  );
}


class Home extends StatefulWidget {
  static final String routeName = '/Home';


  @override
  _HomeState createState() => new _HomeState();
}


class _HomeState extends State with SingleTickerProviderStateMixin {
  StreamSubscription<DocumentSnapshot> subscription;
  String _useremail;
  String _username;
  String _userimage;
  String p;
  String id;
  int currentversion=1;
  bool maintainancemode=false;
  int appversion;
  int totalscore;
  String badgename;

  final List<MyTabs> _tabs = [new MyTabs(title: "Learn"),
  new MyTabs(title: "Play"),
  new MyTabs(title: "Acitvity Feed"),
  new MyTabs(title: "Q&A Discussions"),
  new MyTabs(title: "JOBS")
  ];
  MyTabs _myHandler ;
  TabController _controller ;
  void initState() {
    super.initState();
//    checkUserData();
    _controller = new TabController(length: 5, vsync: this);
    _myHandler = _tabs[0];
    _controller.addListener(_handleSelected);

    loadProfiles();
    FirebaseAuth.instance.currentUser().then((user) {
      _useremail = user.email;
      _username =user.displayName;
      _userimage=user.photoUrl;
      p=user.phoneNumber;
      id=user.uid;

    });
//    check();
  }




  loadProfiles() async {
    preferences = await SharedPreferences.getInstance();
    googleProfileUrl = preferences.getString(GOOGLE_PROFILE_URL_KEY);
    googleUserName = preferences.getString(GOOGLE_USERNAME_KEY);
    googleEmailID = preferences.getString(GOOGLE_EMAIL_ID_KEY);
    isSignedInWithGoogle = preferences.getBool(IS_SIGNED_IN_WITH_GOOGLE_KEY);
    if (isSignedInWithGoogle == null)
      isSignedInWithGoogle = false;
    if (selectedProfile == null)
      selectedProfile = GOOGLE;

    setState(() {});
  }

  void _handleSelected() {
    setState(() {
      _myHandler= _tabs[_controller.index];
    });
  }
  void choiceAction(String choice){
    if(choice == Constants.Settings){
      print('Settings');
    }else if(choice == Constants.Subscribe){
      print('Subscribe');
    }else if(choice == Constants.SignOut){
      logoutFromGoogle();
      Navigator.of(context).pop(); // Remove dialog
      Navigator.pushReplacementNamed(context, LoginPage.routeName);
    }
  }
//  @override
//  void dispose() {
//    // TODO: implement dispose
//    super.dispose();
//    controller.dispose();
//  }



  @override
  Widget build(BuildContext context) {


    return new Scaffold(
      resizeToAvoidBottomPadding: false,
      appBar: new AppBar(
          actions: <Widget>[
            new IconButton(icon:new Icon(Icons.perm_identity) , onPressed: (){
              Navigator.of(context).push(new MaterialPageRoute(builder: (context)=>new ProfilePage(profileid: usedid,)));
            }),
            new IconButton(icon: new Icon(Icons.notifications), onPressed: (){
//            Navigator.of(context).push(new MaterialPageRoute(builder: (context)=>new DonutAutoLabelChart()));
            }),
            _useremail=="hitanshugogoi@gmail.com"?IconButton(icon: Icon(FontAwesomeIcons.servicestack,color: Colors.red,), onPressed: (){
              Navigator.of(context).push(new MaterialPageRoute(builder: (context)=>new AdminMain()));// Remove dialog
//            Navigator.pushReplacementNamed(context, AdminMain.routeName);
            }):Container(),
            PopupMenuButton<String>(
              onSelected: choiceAction,
              itemBuilder: (BuildContext context){
                return Constants.choices.map((String choice){
                  return PopupMenuItem<String>(
                    value: choice,
                    child: Text(choice),
                  );
                }).toList();
              },
            )
          ],
          backgroundColor: Colors.blueGrey,
          title:new Text(_myHandler.title),
          bottom: new TabBar(
            controller: _controller,
            tabs: [
              new Tab(icon: new Icon(Icons.school,),),
              new Tab(icon: new Icon(Icons.flash_on)),
              new Tab(icon: new Icon(Icons.home)),
              new Tab(icon: new Icon(Icons.message))
            ],
          )
      ),

      body: new TabBarView(
        controller: _controller,
        children: [
          new learn.Learn(useremail: _useremail,userid: id,),
          new play.Play(currentuserid: id,currentuseremail: _useremail,currentusername: _username,currentuserimage: _userimage,),
          new Activity.ActivityFeed(currentuserimage: _userimage,currentusername: _username,currrentuserid: id,currentuseremail: _useremail,),
          new qa.QADiscussion(currentusername: _username,currentuseremail: _useremail,currentuserimage: _userimage,uid: id,)
        ],
      ),

    );
  }

}
class MyTabs {
  final String title;
  final IconData icon;
  final Color color;
  MyTabs({this.title,this.color,this.icon});
}
](url)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` 
and the plugins you have in `dependencies: ` in `pubspec.yaml`

**Comment by zoechi** [comment]
Merging with #18756

**Comment by karimsajjad** [comment]
I'm getting this same exception

 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30859): The following assertion was thrown while finalizing the widget tree:
I/flutter (30859): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 683 pos 12: 'pixels !=
I/flutter (30859): null': is not true.

**Comment by zoechi** [comment]
This issue is closed. Please follow #18756.

Upvoting (add reaction) is preferred to "me too" comments if the comment doesn't provide new information that helps fixing the issue.

**Comment by zoechi** [comment]
See also #21630
