### ISSUE TITLE
google_maps_flutter: StackOverflowError on zooming in and out

### ISSUE THREAD

**Issue by dumazy** [flutter/flutter#22078]
I'm getting a StackOverflowError using the google_maps_flutter plugin when zooming in and out in London, as the example suggests. This doesn't happen everywhere on the map. It is probably depending on the specific map data that is displayed.

## Steps to Reproduce

1. Implement example at https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter in a new project
2. Click on the button "Go to London"
3. Zoom in and out of the current position.
4. The app crashes.

## Logs

```
E/AndroidRuntime(32147): java.lang.StackOverflowError: stack size 1037KB
E/AndroidRuntime(32147): 	at java.util.Collections$UnmodifiableRandomAccessList.<init>(Collections.java:1437)
E/AndroidRuntime(32147): 	at java.util.Collections.unmodifiableList(Collections.java:1330)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.common.i.<init>(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):2)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):96)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):98)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.b(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):173)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):202)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):42)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):31)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):101)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.b(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):173)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):202)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):42)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):31)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):101)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.b(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):173)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):202)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):42)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):31)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):101)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.b(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):173)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):202)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):42)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):31)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):101)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.b(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):173)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.c(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):202)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):42)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.a(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):31)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.d(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):101)
E/AndroidRuntime(32147): 	at com.google.maps.api.android.lib6.gmm6.indoor.o.e(:com.google.android.gms.dynamite_mapsdynamite@13280048@13.2.80 (040400-211705629):304)

```

`flutter analyze` output
```
Analyzing flutter_research...                                    
No issues found! (ran in 1.0s)
```

`flutter doctor -v` output. I'm using Android Studio 3.2 RC 3

```
[✓] Flutter (Channel master, v0.8.5-pre.7, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.5-pre.7 at /home/fre/Development/Flutter
    • Framework revision 2bca8007bd (4 days ago), 2018-09-16 12:30:34 -0400
    • Engine revision 72665c6827
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/fre/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/idea-IC-182.4129.33
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Nexus 6P • CVH7N15C21001035 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

**Comment by chanchanbn** [comment]
Having the same issue, do you have any solution?

**Comment by miguelpruivo** [comment]
Same here.

**Comment by miguelpruivo** [comment]
**Update:** I "fixed it" myself and PR it by adding a way to enable/disable it which, IMO, makes sense to be available out of the box, since the Maps API already provides it. 
You can now enable/disable the indoor view with the `GoogleMapOptions` and disabling it will prevent the crash. The reason for the crashing is not actually solved, but at least now you can have a way to disable the culprit for such crash. See PR #826.

**Comment by amirh** [comment]
Looks like we got the Android maps code into an inifinite recursion.
I'm following up with the maps team.

**Comment by amirh** [comment]
We believe this is a maps bug tracked in
https://issuetracker.google.com/issues/35829732 and https://issuetracker.google.com/issues/35829548

A fix should be released with a future Google Play Services update.

**Comment by amirh** [comment]
Closed as it doesn't seem that any further action on our side is needed.
