### ISSUE TITLE
Error on flutter analyze

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#22124]
See https://cirrus-ci.com/task/4841332262567936

```
⏩ RUNNING: cd .; bin/flutter analyze --flutter-repo
Analyzing 3 directories...                                      
Error from the analysis server: Analysis failed: /tmp/flutter sdk/packages/flutter/lib/src/widgets/dismissible.dart context: exception_20180921_025115_263
type 'ClassElementHandle' is not a subtype of type 'ClassElementImpl'
#0      InterfaceTypeImpl.lookUpInheritedMember.lookUpImpl (package:analyzer/src/dart/element/type.dart:1787:28)
#1      InterfaceTypeImpl.lookUpInheritedMember.lookUpImpl (package:analyzer/src/dart/element/type.dart:1816:24)
#2      InterfaceTypeImpl.lookUpInheritedMember.lookUpImpl (package:analyzer/src/dart/element/type.dart:1799:32)
#3      InterfaceTypeImpl.lookUpInheritedMember (package:analyzer/src/dart/element/type.dart:1828:24)
#4      ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:599:40)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7807:49)
#6      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:5928:10)
#7      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7807:49)
#8      ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4242:18)
#9      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#10     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3052:59)
#11     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4238:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#13     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1254:17)
#14     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#15     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2966:31)
#16     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:6855:13)
#17     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1250:49)
#18     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1199:13)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#20     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2969:55)
#21     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:6867:13)
#22     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5214:13)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1195:49)
#24     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7695:12)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#26     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3153:55)
#27     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7333:11)
#28     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:5916:11)
#29     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7325:7)
#30     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:5906:13)
#31     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#33     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:6936:18)
#34     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6913:11)
#35     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5253:13)
#36     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#37     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5317:25)
#38     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#39     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:592:10)
#40     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#41     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#42     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#43     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#44     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#45     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#46     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#47     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#48     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#49     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#50     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#51     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#52     new AnalysisServer (package:analysis_server/src/analysis_server.dart:389:29)
#53     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#54     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#55     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:487:21)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _runZoned (dart:async/zone.dart:1516:10)
#59     runZoned (dart:async/zone.dart:1463:12)
#60     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:531:12)
#61     Driver.start (package:analysis_server/src/server/driver.dart:485:7)
#62     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#63     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#64     main (file:///b/build/slave/Linux_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#65     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#66     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
No issues found! (ran in 89.0s)
```

**Comment by a14n** [comment]
I see the same issue locally and reported in dart-lang/sdk#34536

@bwilkerson @scheglov

**Comment by scheglov** [comment]
Fixed as https://github.com/dart-lang/sdk/issues/34546
