### ISSUE TITLE
Flutter Firebase iOS 12 Error

### ISSUE THREAD

**Issue by nhathiwala** [flutter/flutter#22136]
## Steps to Reproduce

1. Install Firebase services
2. Run iOS application on emulator any device.
3. While building iOS app, it fail with an error

## Logs

```
 === BUILD TARGET firebase_ml_vision OF PROJECT Pods WITH CONFIGURATION Debug ===
           
           Check dependencies
           
           Remove stale build products
               /bin/rm -rf /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Headers/firebase_ml_vision-umbrella.h
               /bin/rm -rf /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Headers/FirebaseMlVisionPlugin.h
               /bin/rm -rf /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Modules/module.modulemap
               /bin/rmdir /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Headers
               /bin/rmdir /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework
               /bin/rmdir /Users/USERNAME/Library/Developer/Xcode/DerivedData/Runner-bqldgbhodgkpwubogdvdnskwrgll/Build/Products/Debug-iphonesimulator/firebase_ml_vision
           
           CpHeader Target\ Support\ Files/firebase_ml_vision/firebase_ml_vision-umbrella.h /Users/USERNAME/Developer/flutter/student_perks_v1/build/ios/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Headers/firebase_ml_vision-umbrella.h
               cd /Users/USERNAME/Developer/flutter/student_perks_v1/ios/Pods
               export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/USERNAME/development/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools"
               builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/USERNAME/Developer/flutter/student_perks_v1/ios/Pods/Target\ Support\ Files/firebase_ml_vision/firebase_ml_vision-umbrella.h /Users/USERNAME/Developer/flutter/student_perks_v1/build/ios/Debug-iphonesimulator/firebase_ml_vision/firebase_ml_vision.framework/Headers
           
           
[  +72 ms] Could not build the application for the simulator.
[   +1 ms] Error launching application on iPhone XS Max.
[   +5 ms] "flutter run" took 24,925ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:397:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
```

```
[✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.6 17G65, locale en-SG)
    • Flutter version 0.9.2 at /Users/USERNAME/development/flutter
    • Framework revision 85b4670b2a (2 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/USERNAME/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone XS Max • FDF18FC3-547C-4335-8664-F70841216621 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by nhathiwala** [comment]
**I have targeted iOS to 8.0  for both Pod and Xcode** 
The only place where the app compilation break is due to firebase dependencies. If I remove firebase from the project, it compiles without any error.

```
FIRDatabase.h:154:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_queue_t callbackQueue;
```

**Comment by nhathiwala** [comment]
@zoechi  I found a temporary fix for it:

In your podfile where You see

```
target 'Runner' do
  use_frameworks!  
```
comment user_frameworks!

```
target 'Runner' do
  # use_frameworks!  
```
and go to path /ios of the project

run

`pod install`

and cheers 🍻

**Comment by rlee1990** [comment]
@nhathiwala I still get the same error even after trying your workaround

**Comment by nhathiwala** [comment]
@rlee1990 it worked for me until I updated my macOS to 10.14. Thus this issue continues, I'm pretty sure this issue is somewhat related to the compiler or the Firebase library itself. Without FIrebase library my code compiles with no error. I'm sure Flutter team could be facing the same error and might be working on a fix as this error is very critical one.

**Comment by rlee1990** [comment]
Any update on this?

**Comment by rlee1990** [comment]
The issue has always been flutter_ml_vision the pub needs to be updated

**Comment by kroikie** [comment]
@nhathiwala

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/654. Any further collaboration will be done there.
