### ISSUE TITLE
My first app documentation not working

### ISSUE THREAD

**Issue by MParrao** [flutter/flutter#22158]
## Steps to Reproduce

1. Using the code for the site : https://flutter.io/get-started/codelab/
Or copying the code directly from: https://raw.githubusercontent.com/chalin/flutter-codelabs/master/startup_namer/4_end_of_infinite_list/lib/main.dart throws unhandled exception
2. I think I found the root cause but I'm not sure why... the workaround is to place the _biggerFont variable inside the scope of the _buildRow Widget.
Place the _buildSuggestions Widget inside the scope of the build Widget

## Logs

```

[  +11 ms] [android\] C:\Users\IngMP\AndroidStudioProjects\flutter_test_app\android\gradlew.bat -q -Ptarget=C:\Users\IngMP\AndroidStudioProjects\flutter_test_app\lib\main.dart -Ppreview-dart-2=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+5199 ms] compiler message: Unhandled exception:
[        ] Crash when compiling file:///C:/Users/IngMP/AndroidStudioProjects/flutter_test_app/lib/main.dart,
[        ] at character offset 519:
[        ] lib/main.dart: Internal problem: Unhandled this in defaultTreeNode.
[        ] #0      internalProblem (package:front_end/src/fasta/problems.dart:30)
[        ] #1      unhandled (package:front_end/src/fasta/problems.dart:43)
```

```
```

```
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [VersiÃ³n 10.0.17134.285], locale es-MX)
    • Flutter version 0.2.8 at D:\Program files\Flutter
    • Framework revision b397406561 (6 months ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\IngMP\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: D:\Program files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at D:\Program files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\ProgramFiles\IntelliJ IDEA 2018.1.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by MParrao** [comment]
had an older version of flutter
