### ISSUE TITLE
Flutter google_sign_in throws an exception

### ISSUE THREAD

**Issue by vskr** [flutter/flutter#22179]
This is the version I am usinv
  google_sign_in: "^3.0.5"

Seeing following error after I do
await await _googleSignIn.signIn();

It shows gmail accounts that are logged in the emulator, however when I click on one of them it throws following error, whicih doesn't have enough information to help me debug what the cause is. Any help would be appreciated.

E/flutter (18684): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (18684): PlatformException(sign_in_failed, Status{statusCode=CANCELED, resolution=null}, null)
E/flutter (18684): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (18684): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (18684): <asynchronous suspension>
E/flutter (18684): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:185:58)
E/flutter (18684): <asynchronous suspension>
E/flutter (18684): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:237:28)
E/flutter (18684): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (18684): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (18684): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (18684): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (18684): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
E/flutter (18684): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18684): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by vskr** [comment]
I wiped out data on emulator and now I see the following error.

It is develoepr_error instead of canceled.

E/flutter ( 4593): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4593): PlatformException(sign_in_failed, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
E/flutter ( 4593): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 4593): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 4593): <asynchronous suspension>
E/flutter ( 4593): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:185:58)
E/flutter ( 4593): <asynchronous suspension>
E/flutter ( 4593): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:237:28)
E/flutter ( 4593): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter ( 4593): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter ( 4593): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter ( 4593): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter ( 4593): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
E/flutter ( 4593): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4593): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
D/EGL_emulation( 4593): eglMakeCurrent: 0xe5004780: ver 3 0 (tinfo 0xe5003a30)

**Comment by arpagaus** [comment]
If you've got a new setup for your dev environment registering your new SHA1 fingerprint might help: https://stackoverflow.com/questions/52446960/flutter-firebase-auth-google-sign-in-fail-to-login-with-statuscode-canceled/52459412
