### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by thaofactor** [flutter/flutter#22181]
Here the Console error:
```
I/flutter ( 6080): The following assertion was thrown building RadialProgressBar(state: _RadialSeekBarState#8454c):
I/flutter ( 6080): Failed assertion: boolean expression must not be null
I/flutter ( 6080): 
I/flutter ( 6080): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6080): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6080): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6080):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6080): 
I/flutter ( 6080): When the exception was thrown, this was the stack:
I/flutter ( 6080): #0      RenderCustomPaint._didUpdatePainter (package:flutter/src/rendering/custom_paint.dart:432:20)
I/flutter ( 6080): #1      RenderCustomPaint.foregroundPainter= (package:flutter/src/rendering/custom_paint.dart:422:5)
I/flutter ( 6080): #2      CustomPaint.updateRenderObject (package:flutter/src/widgets/basic.dart:442:9)
I/flutter ( 6080): #3      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4300:12)
I/flutter ( 6080): #4      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4671:11)
I/flutter ( 6080): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6080): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6080): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6080): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #46     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #48     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 6080): #49     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 6080): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #59     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 6080): #60     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 6080): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #68     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #78     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 6080): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 6080): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #84     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #92     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #96     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 6080): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #100    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 6080): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 6080): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 6080): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 6080): #104    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 6080): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 6080): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 6080): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6080): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6080): #109    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6080): #110    _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 6080): #111    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 6080): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/chatty  ( 6080): uid=10085(com.example.icecreamapp) Thread-2 identical 10 lines
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/chatty  ( 6080): uid=10085(com.example.icecreamapp) Thread-2 identical 2 lines
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/chatty  ( 6080): uid=10085(com.example.icecreamapp) Thread-2 identical 5 lines
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
I/chatty  ( 6080): uid=10085(com.example.icecreamapp) Thread-2 identical 14 lines
I/flutter ( 6080): Another exception was thrown: Failed assertion: boolean expression must not be null
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` 
and a minimal runnable reproduction.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
