### ISSUE TITLE
Exception using showMenu without Position parameter

### ISSUE THREAD

**Issue by wolfcro1984** [flutter/flutter#22256]
I'm getting an exception when I try to use the showMenu method without an PopupMenuButton and without specifying position and initialValue parameters which are not marked as required. 

```
showMenu<String>(
      context: context,
      items: [
        PopupMenuItem<String>(
          value: 'edit',
          child: ListTile(
            leading: Icon(Icons.edit),
            title: Text("Edit"),
          ),
        ),
        PopupMenuItem<String>(
          value: 'chart',
          child: ListTile(
            leading: Icon(Icons.delete),
            title: Text("Delete"),
            ),
          ),
        ),
      ],
    )
```
```
The exception i get is:
I/flutter (21534): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (21534): The following NoSuchMethodError was thrown during performLayout():
I/flutter (21534): The getter 'top' was called on null.
I/flutter (21534): Receiver: null
I/flutter (21534): Tried calling: top
I/flutter (21534): When the exception was thrown, this was the stack:
I/flutter (21534): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
I/flutter (21534): #1      _PopupMenuRouteLayout.getPositionForChild (package:flutter/src/material/popup_menu.dart:533:20)
I/flutter (21534): #2      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1099:41)
I/flutter (21534): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (21534): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (21534): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (21534): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (21534): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (21534): #13     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
I/flutter (21534): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (21534): #15     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (21534): #16     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter (21534): #17     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (21534): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (21534): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (21534): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (21534): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (21534): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (21534): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (21534): #24     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (21534): #25     _drawFrame (dart:ui/hooks.dart:117:3)
```

I can easily overcome the exception by setting the positioned parameter but this shouldn't throw an exception because the parameter isn't required.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by wolfcro1984** [comment]
flutter doctor -v output:

[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.14393], locale hr-HR)
    • Flutter version 0.8.2 at C:\src\flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\veljkov\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.26.1)
    • VS Code at C:\Users\veljkov\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.27.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.0.2 (API 21) (emulator)

**Comment by HubertZhang** [comment]
I've encountered the same problem. The application won't crash but the position of menu would be wrong.

**Comment by DarrenGoog** [comment]
Addressed this with https://github.com/flutter/flutter/pull/30206.
