### ISSUE TITLE
android_alarm_manager 0.2.1 causes a crash at app start (requires Firebase to be installed?)

### ISSUE THREAD

**Issue by biklas7** [flutter/flutter#22257]
I'm trying to use the android_alarm_manager plugin but I get this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.coletivinfiniteparking, PID: 5363
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.coletivinfiniteparking/com.example.coletivinfiniteparking.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.coletivinfiniteparking. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.coletivinfiniteparking. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(SourceFile:218)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.<init>(FirebaseAuthPlugin.java:54)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.registerWith(FirebaseAuthPlugin.java:47)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
        at com.example.coletivinfiniteparking.MainActivity.onCreate(MainActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

It seems that this is caused because I should initialize FirebaseApp. 

For what I could understand, Firebase Auth is used in the example of this plugin but I don't need to support Firebase on my project. 

Is it really required to setup Firebase to use this plugin?

**Comment by ahmadmarafa** [comment]
i'm getting the same error

**Comment by wwjjbb** [comment]
Nothing in the alarm plugin depends on firebase so the dependency should be be removed.

The plugin example app does depend on firebase_auth, but deals with that itself. So thats not a problem, other than it making the example more complicated than it needs to be.

**Comment by Patte1808** [comment]
I opened a [PR](https://github.com/flutter/plugins/pull/926) for it, maybe we can somehow create more visibility for this issue.

**Comment by kroikie** [comment]
@biklas7

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/647. Any further collaboration will be done there.
