### ISSUE TITLE
flutter run in cloned repo leads to flutter crash

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#22294]
I cloned [PoojaB26/FlutterBasicWidgets](https://github.com/PoojaB26/FlutterBasicWidgets), then ran `flutter run` in the checkout directory and boom:

## command

flutter run

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/brettmorgan/github/FlutterBasicWidgets/ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v0.9.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.3 at /Users/brettmorgan/flutter
    • Framework revision eed8c7ad07 (5 days ago), 2018-09-20 16:30:07 -0700
    • Engine revision 71457a67d0
    • Dart version 2.1.0-dev.5.0.flutter-c688d0c0c3

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 8 • B682198B-D1D2-4859-8941-19F4053C6691 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
It doesn't contain an `ios` or `android` directory.
Try running `flutter create .` in the project directory and run again.

**Comment by PoojaB26** [comment]
Yes. You have to run <code> flutter create . </code> to create the `android` and `iOS` projects. But make sure your root directory is renamed as all_lowercase_with_underscore  instead of FlutterBasicWidgets. Because Flutter doesn't like CamelCases project names. :/

**Comment by zoechi** [comment]
Thanks @PoojaB26 for chiming in. 
I assume this support question is answered.
