### ISSUE TITLE
package: url_launcher error 

### ISSUE THREAD

**Issue by loloDawit** [flutter/flutter#22295]
## Steps to Reproduce
I added url_launcher 3.0.3 to my project. The error is produced when i try to launch any url. I call

```dart
Future _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url, forceSafariVC: true, forceWebView: true);
    } else {
      throw 'Could not launch $url';
    }
  } 
```
This function and pass in a url. The application shows **this connection is not private** and throws an error.
![screen shot 2018-09-25 at 10 49 19 pm](https://user-images.githubusercontent.com/16858570/46059801-a1555c00-c115-11e8-9556-b015b804f0e1.png)

```
PlatformException(Error, Error while launching https://www.cnn.com/2018/09/25/asia/uss-wasp-us-china-sanctions-intl/index.html, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:54:19)
#3      DetailsPage._launchURL (file:///Users/dawitabera/Desktop/FlutterProject/newsapi/lib/widgets/detailsview.dart:86:13)
<asynchronous suspension>
#4      DetailsPage.build.<anonymous closure> (file:///Users/dawitabera/Desktop/FlutterProject/newsapi/lib/widgets/detailsview.dart:63:25)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
#7      GestureRecognizer.invokeCallback (package:flutter<…>
```
## Logs
flutter run --v 
https://gist.github.com/loloDawit/568b6963a47c189eb52a4a2eb0075c55

## Flutter analyze
No issues found! (ran in 1.8s)

##Flutter Doctor
flutter doctor -v
```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en)
    • Flutter version 0.8.2 at /Users/dawitabera/Downloads/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dawitabera/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone X • B93DEF68-02F9-4F6D-9C41-A20174FDA870 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by cyanglaz** [comment]
`await launch(url, forceSafariVC: true, forceWebView: true);` this throws the exception if the url you try to launch failed. I think we can make it better to not throw an exception but instead return a response object that contains an error object.
But for now, you can try to catch that exception and fail gracefully in you app like:
```dart
try {
   await launch(url, forceSafariVC: true, forceWebView: true);
} catch (e) {
  _handleUrlLaunchingException(e);
}
```

Please let me know if this resolves your issue.
