### ISSUE TITLE
API version check for AccessibilityNodeInfo.setLiveRegion

### ISSUE THREAD

**Issue by Aniki312** [flutter/flutter#22342]
We encounter some crash on Android 4.3 (API level 18) devices 

```
Fatal Exception: java.lang.NoSuchMethodError: android.view.accessibility.AccessibilityNodeInfo.setLiveRegion
       at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:172)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:907)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:917)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:917)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode(AccessibilityInteractionController.java:917)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:828)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:824)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:824)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:710)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:147)
       at android.view.AccessibilityInteractionController.access$300(AccessibilityInteractionController.java:49)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:961)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5202)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Looks like the [setLiveRegion api was introduced in API level 19](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.html#setLiveRegion(int))

But in [AccessibilityBridge.java](https://github.com/flutter/engine/blob/f3d51b0cfbd4d56a74ea0f5b79747b167d106d97/shell/platform/android/io/flutter/view/AccessibilityBridge.java) , the method was called for device with api level >= 18

```
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                result.setEditable(true);
                if (object.textSelectionBase != -1 && object.textSelectionExtent != -1) {
                    result.setTextSelection(object.textSelectionBase, object.textSelectionExtent);
                }
                // Text fields will always be created as a live region, so that updates to
                // the label trigger polite announcements. This makes it easy to follow a11y
                // guidelines for text fields on Android.
                result.setLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);
            }
```
The crash was reported from app shipped with following flutter version 
[✓] Flutter (Channel unknown, v0.7.5, on Mac OS X 10.13.6 17G65, locale zh-Hant-TW)

**Comment by jonahwilliams** [comment]
Thank you for the bug report @Aniki312 ! I have a fix landing shortly.
