### ISSUE TITLE
Android sdkmanager tool not found in MAC OS

### ISSUE THREAD

**Issue by huangyiCode** [flutter/flutter#22343]
This is my out put.When i run the flutter doctor -v:

   bogon:~ dbb-mike$ flutter doctor -v
```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.8.2 at /Users/dbb-mike/Documents/Android/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
```
```
Android sdkmanager tool not found (/Users/dbb-mike/Documents/Android/android-sdk-macosx/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.io/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidValidator._ensureCanRunSdkManager (package:flutter_tools/src/android/android_workflow.dart:261:7)
#2      AndroidValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:195:5)
<asynchronous suspension>
#3      AndroidValidator.validate (package:flutter_tools/src/android/android_workflow.dart:156:19)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:56)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:183:42)
#6      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:173:24)
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

And this my environment config:
   bogon:~ dbb-mike$ cat ~/.bash_profile
export M2_HOME=/Users/dbb-mike/Documents/Android/apache-maven-3.5.4
export ANDROID_HOME=/Users/dbb-mike/Documents/Android/android-sdk-macosx
export ANDORD_ADB=/Users/dbb-mike/Documents/Android/android-sdk-macosx/platform-tools
export FLUTTER=/Users/dbb-mike/Documents/Android/flutter/bin
export PATH=$PATH:$M2_HOME/bin:$ANDORD_ADB:$FLUTTER:$ANDORD_ADB:$ANDROID_HOME/platform-tools
```

Then I want to know how to fixed this problem.thanks.

**Comment by zoechi** [comment]
Similar to #22279

Please add the output of `flutter doctor -v`.

Do you have Android Studio installed?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
