### ISSUE TITLE
Missing canonical name for Reference to #lib510::QueryParam::

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#22355]
I have some trouble creating a release build of my flutter app, no problem in debug mode, but once I tried `flutter build apk --release` then I have this error:

```
compiler message: Unhandled exception:
Missing canonical name for Reference to #lib510::QueryParam::
#0      BinaryPrinter.writeReference (package:kernel/binary/ast_to_binary.dart:528:9)
#1      BinaryPrinter.visitConstructorInvocation (package:kernel/binary/ast_to_binary.dart:1136:5)
#2      ConstructorInvocation.accept (package:kernel/ast.dart:2934:36)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#5      BinaryPrinter.writeAnnotation (package:kernel/binary/ast_to_binary.dart:719:5)
#6      BinaryPrinter.writeAnnotationList (package:kernel/binary/ast_to_binary.dart:727:7)
#7      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1566:5)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:275:8)
#9      BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:230:11)
#10     BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:1577:5)
#11     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:973:5)
#12     FunctionNode.accept (package:kernel/ast.dart:2026:30)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:254:7)
#16     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:839:5)
#17     Procedure.accept (package:kernel/ast.dart:1688:32)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#20     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:238:7)
#21     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:768:5)
#22     Class.accept (package:kernel/ast.dart:921:30)
#23     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#24     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#25     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:238:7)
#26     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:616:5)
#27     Library.accept (package:kernel/ast.dart:409:30)
#28     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:246:10)
#29     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#30     List.forEach (dart:core/runtime/libgrowable_array.dart:275:8)
#31     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:230:11)
#32     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:5)
#33     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:324:5)
#34     FrontendCompiler.writeDillFile (package:vm/frontend_server.dart:385:13)
<asynchronous suspension>
#35     FrontendCompiler.compile (package:vm/frontend_server.dart:350:13)
<asynchronous suspension>
#36     _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
<asynchronous suspension>
#37     starter (package:frontend_server/server.dart:124:27)
<asynchronous suspension>
#38     main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
The QueryParam class is (I guess) this one: 
https://github.com/Jaguar-dart/client/blob/030f0b4f165b6bada4ba6fb6d361daa6b7316fe4/retrofit/lib/annotations/params.dart#L6 
as I use this librairie in my app, but I don't see anything wrong with it :/ 

Any one have an idea ? 

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale fr-FR)
    • Flutter version 0.8.2 at /Users/jaumard/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK at /Users/jaumard/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] Connected devices (1 available)
    • iPhone XS • B5DC034F-6E05-43F4-8E38-42D15E519D70 • ios • iOS 12.0 (simulator)

• No issues found!

```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Can you please check if you still can reproduce with `master` channel?

**Comment by jaumard** [comment]
Just tested, same error:
```
Building AOT snapshot in release mode (android-arm-release)...      
Unhandled exception:
Missing canonical name for Reference to #lib517::QueryParam::
#0      BinaryPrinter.writeReference (package:kernel/binary/ast_to_binary.dart:532:9)
#1      BinaryPrinter.visitConstructorInvocation (package:kernel/binary/ast_to_binary.dart:1140:5)
#2      ConstructorInvocation.accept (package:kernel/ast.dart:2967:36)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#5      BinaryPrinter.writeAnnotation (package:kernel/binary/ast_to_binary.dart:723:5)
#6      BinaryPrinter.writeAnnotationList (package:kernel/binary/ast_to_binary.dart:731:7)
#7      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1570:5)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#9      BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:234:11)
#10     BinaryPrinter.writeVariableDeclarationList (package:kernel/binary/ast_to_binary.dart:1581:5)
#11     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:977:5)
#12     FunctionNode.accept (package:kernel/ast.dart:2059:30)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:258:7)
#16     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:843:5)
#17     Procedure.accept (package:kernel/ast.dart:1721:32)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#20     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#21     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:772:5)
#22     Class.accept (package:kernel/ast.dart:954:30)
#23     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#24     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#25     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:242:7)
#26     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:620:5)
#27     Library.accept (package:kernel/ast.dart:409:30)
#28     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:250:10)
#29     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:11)
#30     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#31     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:234:11)
#32     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49:5)
#33     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:328:5)
#34     FrontendCompiler.writeDillFile (package:vm/frontend_server.dart:406:13)
<asynchronous suspension>
#35     FrontendCompiler.compile (package:vm/frontend_server.dart:368:13)
<asynchronous suspension>
#36     _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
<asynchronous suspension>
#37     starter (package:frontend_server/server.dart:129:27)
<asynchronous suspension>
#38     main (file:///b/build/slave/Mac_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.9.5-pre.16, on Mac OS X 10.13.6 17G65, locale fr-FR)
    • Flutter version 0.9.5-pre.16 at /Users/jaumard/flutter
    • Framework revision fafd615a81 (15 minutes ago), 2018-09-27 12:47:36 -0400
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK at /Users/jaumard/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] Connected device (1 available)
    • iPhone XS • B5DC034F-6E05-43F4-8E38-42D15E519D70 • ios • iOS 12.0 (simulator)

• No issues found!

```

**Comment by jaumard** [comment]
I tried to build a release version of iOS and same crash appear. Witch is logical to me as I guess aot build is required for both platform in release mode.

Is there something I can do/try in order to build a release version of my app ? Even if it not fully optimized (it's not to go in production but I need to setup fastlane in order for testers to test the app)

**Comment by jaumard** [comment]
Any ideas guys ?

**Comment by jaumard** [comment]
Someone manage to create a small repo to reproduce the problem. It's here https://github.com/IsaNascimento/retroJaguarErrorReplication just clone it. Then `flutter build apk` or `flutter build ios` and you'll see the error `Missing canonical name for Reference to #lib227::QueryParam::`

**Comment by jaumard** [comment]
@zoechi if it can help there a fix that can be apply right now, apparently Flutter/Dart doesn't like this kind of methods when building for AOT:
```
 @GetReq(path: "autenticacao/ws")
  Future<void> getWs(@QueryParam() String matricula);
```
instead if you put: 
```
   @GetReq(path: "autenticacao/ws")
  Future<void> getWs(@QueryParam() String matricula) {
    return super.getWs(matricula);
  }
```
Then you can make a release without any problems.

Hope it can be fix quickly :)

**Comment by jonahwilliams** [comment]
The first example you posted isn't valid on `class` only an `abstract class`.

**Comment by jaumard** [comment]
That's true, didn't notice before because it's auto generated code on my side, but if it's not valid, it shouldn't work at all, not only on release mode... it need to be consistent. So I'm guessing it's more a Dart issue than a flutter one on this

**Comment by jonahwilliams** [comment]
Ahh I'm actually wrong that is valid code, I'm looking into it

**Comment by jonahwilliams** [comment]
Filled https://github.com/dart-lang/sdk/issues/34644

**Comment by alexmarkov** [comment]
The fix landed in Dart SDK: https://github.com/dart-lang/sdk/commit/270fd8e4a8d2153647fa39e57d09e02540236976.
I'll update this issue when the fix is rolled into Flutter.

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter in https://github.com/flutter/flutter/commit/30222b7beeeb039c1e8d478f1f018c4950d56162.

**Comment by jaumard** [comment]
@alexmarkov is the fix under the new beta the came out or just into master for now ?

**Comment by zoechi** [comment]
@jaumard It's probably included in `dev` already and then in the next `beta`

**Comment by jaumard** [comment]
Ok thanks ! :)

**Comment by zoechi** [comment]
@jaumard I got the impression a new `beta` is on it's way out, but not sure.

**Comment by jaumard** [comment]
I've got a new one today :) that's why I ask if it's in it `v0.9.4`

**Comment by zoechi** [comment]
I was on `dev` and switched to latest `beta` and I got

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.9.4 at /Users/zoechi/flutter/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
```
> **(2 weeks ago)**

which is why I assumed `0.9.4` is not new enough

**Comment by jaumard** [comment]
Ho ok :) the next one then ^^ thanks for the info
