### ISSUE TITLE
Flutter Apk release build failed 

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#22397]
## Steps to Reproduce

1. ...
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
   > Could not resolve project :fluttertoast.
     Required by:
         project :app
      > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s                                                                                                                                                                         
Gradle task 'assembleRelease'... Done                        3.5s
Gradle task assembleRelease failed with exit code 12. ...
```
3. ...

## Logs

```
[  +35 ms] executing: [/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/flutter/] git log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 4b1717a2c17a38783f5aeb2b3b0721be2a8a4608
[        ] executing: [/flutter/] git log -n 1 --pretty=format:%ar
[  +16 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 83 minutes ago
[        ] executing: [/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +77 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.9.4-29-g4b1717a2c
[ +478 ms] executing: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:4
[  +12 ms] executing: idevice_id -h
[  +54 ms] /usr/bin/xcrun simctl list --json devices
[ +264 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] /Users/test/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +50 ms] ro.hardware = ranchu
[   +4 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[        ] iPhone XR                 • 09F6EE31-F931-4DF2-B39C-5BB0963F9E0A • ios         • iOS 12.0 (simulator)
[  +13 ms] "flutter run" took 825ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:239:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```Analyzing.....                                         
No issues found! (ran in 3.4s)
```

```
[✓] Flutter (Channel master, v0.9.5-pre.29, on Mac OS X 10.14.1 18B45d, locale en)
    • Flutter version 0.9.5-pre.29 at /flutter
    • Framework revision 4b1717a2c1 (85 minutes ago), 2018-09-27 21:26:32 -0400
    • Engine revision 8176f4d3c4
    • Dart version 2.1.0-dev.5.0.flutter-808ed6238b

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/test/Library/Android/sdk
    • Android NDK at /Users/test/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 09F6EE31-F931-4DF2-B39C-5BB0963F9E0A • ios         • iOS 12.0 (simulator)

• No issues found!
```

**Comment by ram231** [comment]
I had a headache with this and I solved it in a lot of ways in android studio(because of gradle update)
add to Build.gradle
```gradle

allprojects {
    repositories {
        google()
        jcenter{ url "http://jcenter.bintray.com/"}
    }
}
```
I had to change the version of kotlin and its depreciated apis from android manully for each package I used.

**Comment by pojoba02** [comment]
@dnfield, any light on this issue?

**Comment by dnfield** [comment]
It looks like you have a gradle error that can't find a project it's supposed to find.  What is futtertoast?  is that your project, or a plugin you're adding, or something else?

**Comment by dnfield** [comment]
I'm not able to reproduce this with a stock `flutter create` project.

**Comment by pojoba02** [comment]
@ram231 do i have to manually upgrade the build gradle in all the packages

**Comment by yy1300326388** [comment]
@dnfield  I am upgrading to Android Studio 3.2, Gradle Version: 4.6 This error occurs, the build Debug version is normal.

**Comment by ram231** [comment]
@pojoba02 First I update the flutter toast in its build.gradle file and everything fucks up. I forgot everything I went with that frustration.

**Comment by pojoba02** [comment]
@dnfield,@ram231,Any light on this issue

**Comment by diegoveloper** [comment]
same issue here

**Comment by henrik-d** [comment]
For me, applying the changes of this PR to my gradle-files solved the issue: https://github.com/flutter/flutter/pull/22790/files

**Comment by yy1300326388** [comment]
```java
lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
}
```

`android/app/build.gradle`

[https://github.com/PonnamKarthik/FlutterToast/issues/18](https://github.com/PonnamKarthik/FlutterToast/issues/18)

**Comment by 466023746** [comment]
> ```java
> lintOptions {
>         disable 'InvalidPackage'
>         checkReleaseBuilds false
> }
> ```
> 
> `android/app/build.gradle`
> 
> [PonnamKarthik/FlutterToast#18](https://github.com/PonnamKarthik/FlutterToast/issues/18)

work for me!

**Comment by jonahwilliams** [comment]
It seems like this is an issue with FlutterToast that has since been solved? its not clear that there is anything for Flutter to do here.

**Comment by rahul860366** [comment]
> > ```java
> > lintOptions {
> >         disable 'InvalidPackage'
> >         checkReleaseBuilds false
> > }
> > ```
> > 
> > 
> > `android/app/build.gradle`
> > [PonnamKarthik/FlutterToast#18](https://github.com/PonnamKarthik/FlutterToast/issues/18)
> 
> work for me!

Thanks a lot. This worked for me too. I have been searching for two days.

**Comment by knyou** [comment]
> ```java
> lintOptions {
>         disable 'InvalidPackage'
>         checkReleaseBuilds false
> }
> ```
> 
> `android/app/build.gradle`
> 
> [PonnamKarthik/FlutterToast#18](https://github.com/PonnamKarthik/FlutterToast/issues/18)

Thanks, it is ok

**Comment by YohannesTz** [comment]
> ```java
> lintOptions {
>         disable 'InvalidPackage'
>         checkReleaseBuilds false
> }
> ```
> 
> `android/app/build.gradle`
> 
> [PonnamKarthik/FlutterToast#18](https://github.com/PonnamKarthik/FlutterToast/issues/

thanks it works perfectly. u saved my day!

**Comment by chinkysight** [comment]
@yy1300326388 your solution worked for me too, but can you please explain what was the problem ?

**Comment by amebrahimi** [comment]
@yy1300326388 this solution works but does not fix the underlying problem. 😔

**Comment by samad324** [comment]
> ```java
> lintOptions {
>         disable 'InvalidPackage'
>         checkReleaseBuilds false
> }
> ```
> 
> `android/app/build.gradle`
> 
> [ponnamkarthik/FlutterToast#18](https://github.com/ponnamkarthik/FlutterToast/issues/18)

It worked but the app crashes after launch.

**Comment by Purvik** [comment]
@samad324  Same thing happens to me also, have you solved it?

**Comment by acoutts** [comment]
Also having this issue.

**Comment by samad324** [comment]
> @samad324 Same thing happens to me also, have you solved it?

Yes, I did solve this issue, but I don't exactly remember how. maybe upgrading the Gradle version worked for me.
