### ISSUE TITLE
Listview builder

### ISSUE THREAD

**Issue by kavkum393** [flutter/flutter#22428]
ERROR:

```
I/flutter (17576): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17576): The following assertion was thrown building MenuPage(dirty):
I/flutter (17576): 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
I/flutter (17576): true.
I/flutter (17576):
I/flutter (17576): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17576): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17576): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17576):   https://github.com/flutter/flutter/issues/new
I/flutter (17576):
I/flutter (17576): When the exception was thrown, this was the stack:
I/flutter (17576): #2      new Text (package:flutter/src/widgets/text.dart:230:15)
I/flutter (17576): #3      MenuPage.build (file:///E:/Apps/products_world/lib/menudetails.dart:44:16)
I/flutter (17576): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3707:28)
I/flutter (17576): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
I/flutter (17576): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (17576): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (17576): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (17576): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (17576): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (17576): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (17576): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (17576): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (17576): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (17576): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (17576): #100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4449:32)
I/flutter (17576): #101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter (17576): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #103    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (17576): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17576): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #111    ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17576): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17576): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17576): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17576): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17576): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17576): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17576): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17576): #125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (17576): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (17576): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (17576): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17576): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17576): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (17576): #131    _invoke (dart:ui/hooks.dart:128:13)
I/flutter (17576): #132    _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (17576): (elided 2 frames from class _AssertionError)
I/flutter (17576): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

CODE:
```dart
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text(title),
        backgroundColor: Colors.purple,
      ),
      body: ListView.builder(
            itemCount: _menuitems.length,
            padding: const EdgeInsets.only(top: 10.0),
            itemExtent: 25.0,
            itemBuilder: (BuildContext context,int index) {
       //       DocumentSnapshot ds = snapshot.data.documents[index];
              return ListTile(
                title: Text(_menuitems[index].itemname)); }
     ) 
      
    );
  }
}
```

Please suggest.

**Comment by zoechi** [comment]
Looks like `_menuitems[index].itemname` sometimes returns `null`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
