### ISSUE TITLE
devfs doesn't handle missing files properly.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#22451]
There is a bug in [`flutter_tools/lib/src/devfs.dart`](https://github.com/flutter/flutter/blob/54c10f44b209f6f056ae6c5fa63ee239a9f1e2d2/packages/flutter_tools/lib/src/devfs.dart#L89) when handling files that don't exist: it just crashes.

The root of the bug is that the stat() function just doesn't check for the file not being found.

This is usually not a problem unless a file is removed while the process is running (e.g. while hot reloading), but causes problems on more ephemeral filesystems.

**Comment by alanrussian** [comment]
Just a heads up as far as impact: this has been causing multiple crashes for me every day

**Comment by gspencergoog** [comment]
@alanrussian Can you attach a `flutter_01.log` file from one of the crashes here, just to make sure I'm fixing the bug you're seeing?

**Comment by gspencergoog** [comment]
Nevermind.  I remembered that you already have:

```
################################
## Steps to Reproduce
################################

1) Made changes
2) Successfully hot reloaded
3) Repeat a few times
4) Made changes again
5) Tried to hot reload

Got this exception: 

Performing hot reload...                                         
NoSuchMethodError: The method 'isAfter' was called on null.
Receiver: null
Tried calling: isAfter(Instance of 'DateTime')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DevFSFileContent.isModified (package:flutter_tools/src/devfs.dart:109:55)
#2      DevFS.update.<anonymous closure> (package:flutter_tools/src/devfs.dart:475:19)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#4      DevFS.update (package:flutter_tools/src/devfs.dart:468:14)
<asynchronous suspension>
#5      FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:387:27)
<asynchronous suspension>
#6      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:320:40)
<asynchronous suspension>
#7      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:555:37)
<asynchronous suspension>
#8      HotRunner.restart (package:flutter_tools/src/run_hot.dart:520:24)
<asynchronous suspension>
#9      HotRunner.handleTerminalCommand (package:flutter_tools/src/run_hot.dart:282:44)
<asynchronous suspension>
#10     ResidentRunner.processTerminalInput (package:flutter_tools/src/resident_runner.dart:754:15)
<asynchronous suspension>
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379:20)
#17     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254:5)
#18     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:480:11)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#27     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#28     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#29     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:278:17)
#30     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:264:5)
#31     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#39     _StreamController._add (dart:async/stream_controller.dart:639:7)
#40     _StreamController.add (dart:async/stream_controller.dart:585:5)
#41     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#42     _rootRunUnary (dart:async/zone.dart:1136:13)
#43     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#47     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#48     _StreamController._add (dart:async/stream_controller.dart:639:7)
#49     _StreamController.add (dart:async/stream_controller.dart:585:5)
#50     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#51     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by alanrussian** [comment]
Thanks for the quick fix!
