### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by mzayani** [flutter/flutter#22464]
just used the this code https://github.com/tensor-programming/flutter_bloc_tutorial

recompile using flutter 0.9.5

it was working at the start, but when adding more characters to the search it crashes

Performing hot restart...
Syncing files to device iPhone 8 Plus...
Restarted application in 1,259ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown building MediaQuery(MediaQueryData(size: Size(414.0, 736.0),
flutter: devicePixelRatio: 3.0, textScaleFactor: 1.0, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
flutter: alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors:
flutter: falseboldText: false)):
flutter: Invalid argument(s)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _StringBase.+ (dart:core/runtime/libstring_patch.dart:251:57)
flutter: #1      MyHomePage.build.<anonymous closure>.<anonymous closure> (file:///Users/xo/code/flutter/tensor-programming/flutter_bloc_tutorial/lib/main.dart:64:64)
flutter: #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:258:20)
flutter: #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:783:67)
flutter: #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
flutter: #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:783:26)
flutter: #6      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:761:69)
flutter: #7      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
flutter: #8      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:772:36)
flutter: #9      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #17     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
flutter: #18     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
flutter: #19     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
flutter: #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #59     _invoke (dart:ui/hooks.dart:139:13)
flutter: #60     _drawFrame (dart:ui/hooks.dart:128:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3533 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.

**Comment by mzayani** [comment]
The issue is caused by a null url for the Image.network

**Comment by zoechi** [comment]
The issue can be closed then, right?
