### ISSUE TITLE
Dart Analyzer terminated (VS Code)

### ISSUE THREAD

**Issue by joshjinlee** [flutter/flutter#22472]
## Steps to Reproduce

I've restarted VS Code, uninstalled and reinstalled the extensions for Flutter and Dart, but the problem persists.  Please help!

## Logs
```
Sat Sep 29 2018 [11:56:07 GMT-0400 (EDT)] Log file started
[11:56:07 GMT-0400 (EDT)] [General] [Info] Searching for SDKs...
[11:56:07 GMT-0400 (EDT)] [General] [Info] Environment PATH:
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Users/useruser/.nvm/versions/node/v9.9.0/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Users/useruser/Tools/flutter/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/sbin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /sbin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/local/bin/NuSMV-2.6.0-Darwin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/local/share/dotnet
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Library/Frameworks/Mono.framework/Versions/Current/Commands
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Applications/Wireshark.app/Contents/MacOS
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /usr/local/mysql/bin/
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Users/useruser/Library/Android/sdk/tools
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Users/useruser/Library/Android/sdk/tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     /Users/useruser/Library/Android/sdk/platform-tools
[11:56:07 GMT-0400 (EDT)] [General] [Info] Found Flutter project at /Users/useruser/Documents/Programming/Projects/eumag/eumag
[11:56:07 GMT-0400 (EDT)] [General] [Info] Searching for flutter
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Looking in:
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Documents/Programming/Projects/eumag/eumag/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Tools/flutter/bin/
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/.nvm/versions/node/v9.9.0/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Tools/flutter/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/sbin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /sbin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin/NuSMV-2.6.0-Darwin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/share/dotnet/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/mysql/bin/
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/platform-tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Found at /Users/useruser/Tools/flutter/bin/
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Returning SDK path /Users/useruser/Tools/flutter for flutter
[11:56:07 GMT-0400 (EDT)] [General] [Info] Searching for dart
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Looking in:
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Tools/flutter/bin/cache/dart-sdk/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/.nvm/versions/node/v9.9.0/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Tools/flutter/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/sbin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /sbin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/bin/NuSMV-2.6.0-Darwin/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/share/dotnet/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /usr/local/mysql/bin/
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Library/Android/sdk/platform-tools/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]         /Users/useruser/Tools/flutter/bin/cache/dart-sdk/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Found at /Users/useruser/Tools/flutter/bin/cache/dart-sdk/bin
[11:56:07 GMT-0400 (EDT)] [General] [Info]     Returning SDK path /Users/useruser/Tools/flutter/bin/cache/dart-sdk for dart
[11:56:09 GMT-0400 (EDT)] [General] [Error] [Analyzer] Analysis failed: /Users/useruser/Documents/Programming/Projects/eumag/eumag/lib/main/song_list.dart
[11:56:09 GMT-0400 (EDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1088:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2945:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:469:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1045:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1764:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8251:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:522:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:21:37)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:428:46)
#10     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:427:26)
#12     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:825:12)
#13     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1206:31)
<asynchronous suspension>
#14     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:39)
<asynchronous suspension>
#15     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#16     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#17     new AnalysisServer (package:analysis_server/src/analysis_server.dart:391:29)
#18     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#19     StdioAnaly…
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] Captured exception
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:232:32)
#2      _TopLevelNameDeclarationsTask.perform (package:analyzer/src/dart/analysis/driver.dart:2562:17)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1031:26)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:391:29)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#9      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:497:21)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:541:12)
#15     Driver.start (package:analysis_server/src/server/driver.dart:495:7)
#16     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] Captured exception
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
#1      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:232:32)
#2      _TopLevelNameDeclarationsTask.perform (package:analyzer/src/dart/analysis/driver.dart:2562:17)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1031:26)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:391:29)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#9      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:497:21)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:541:12)
#15     Driver.start (package:analysis_server/src/server/driver.dart:495:7)
#16     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] Captured exception
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:529:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:558:16)
#3      Future._completeError (dart:async/future_impl.dart:494:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#22     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] Captured exception
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:529:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:558:16)
#3      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[11:56:23 GMT-0400 (EDT)] [General] [Error] [Analyzer] Unhandled exception:
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:529:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[11:56:23 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.editGetFixes (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:529:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/fix_code_action_provider.js:18:27)
	at new Promise (<anonymous>)
	at FixCodeActionProvider.provideCodeActions (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/fix_code_action_provider.js:17:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:750:638
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:750:592)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:101
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/…
[11:56:23 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.editGetAssists (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:517:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/assist_code_action_provider.js:17:27)
	at new Promise (<anonymous>)
	at AssistCodeActionProvider.provideCodeActions (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/assist_code_action_provider.js:16:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:750:638
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:750:592)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:765:101
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resourc…
[11:56:27 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.analysisGetHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/exte…
[11:56:28 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.analysisGetHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/exte…
[11:56:28 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.analysisGetHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/exte…
[11:56:29 GMT-0400 (EDT)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:64:28)
	at Analyzer.sendMessage (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer.js:113:19)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:59:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/services/stdio_service.js:48:16)
	at Analyzer.analysisGetHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/useruser/.vscode/extensions/dart-code.dart-code-2.18.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:178
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:132)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:824
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/exte…
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by joshjinlee** [comment]
Sorry for the delay, I happened to solve the issue on my own.  I can't recall how I fixed it but it had to do with passing down functions as a parameter in a custom widget.

**Comment by JannieT** [comment]
@joshjinlee would you mind sharing how you got this log trace? I tried setting a path in Analyzer Log File under Visual Studio Code User Settings > Dart Configuration, but it looks like the log file is dumped as a binary that I can't inspect.
