### ISSUE TITLE
TabController.animateTo() failed

### ISSUE THREAD

**Issue by wiserbird** [flutter/flutter#22484]
Hello. I am making an ios app using flutter.
I tried to change the selected tab when a button is clicked. 
But some exception occured when TabController.animateTo() function is executed.
Here are my codes and error logs. Is it a new bug?
```dart
class MyTabbedPage extends StatefulWidget {
  const MyTabbedPage({ Key key }) : super(key: key);
  @override
  _MyTabbedPageState createState() => _MyTabbedPageState();
}

class _MyTabbedPageState extends State<MyTabbedPage> with SingleTickerProviderStateMixin {

  TabController _tabController;

  @override
  void initState() {
    super.initState();

    _tabController = new TabController(vsync: this, length: 5);
    _tabController.addListener(_handleTabSelection);
  }

  void _handleTabSelection() {
    print("_tabController index: ${_tabController.index}");
  }

  @override
  void dispose() {

    _tabController.dispose();
    super.dispose();
  }

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return new Scaffold(
      appBar: new AppBar(
        bottom: new TabBar(
          controller: _tabController,
          tabs: [
            new Tab(icon: new Icon(Icons.dashboard)),
            ...
          ],
        ),
        title: new Text(Strings.appName),
      ),
      body: SafeArea(
        child: new TabBarView(
          controller: _tabController,
          children: [
            DashboardWidget(tabController: _tabController,),
            ...
          ],
        ),
      ),
    );
  }
}

class DashboardWidget extends StatefulWidget {

  DashboardWidget({Key key, this.tabController}) : super(key: key);

  final TabController tabController;

  @override
  _DashboardWidgetState createState() => _DashboardWidgetState();
}

class _DashboardWidgetState extends State<DashboardWidget> {

  void changeTab() {
    widget.tabController.animateTo(4,
      duration: const Duration(milliseconds: 300),
      curve: Curves.ease,
    );
  }
}
```

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building NotificationListener<KeepAliveNotification>:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2865 pos 14:
flutter: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2865:14)
flutter: #3      _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2899:5)
flutter: #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:11)
flutter: #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:932:18)
flutter: #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4525:35)
flutter: #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4291:5)
flutter: #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4665:11)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
flutter: #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:769:34)
flutter: #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
flutter: #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
flutter: #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #71     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
flutter: #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #81     _invoke (dart:ui/hooks.dart:128:13)
flutter: #82     _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2865 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2865 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2865 pos 14: '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3509 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
Application finished.
```

$ flutter doctor -v
```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-KR)
    • Flutter version 0.8.2 at /Users/upinel9/work/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/upinel9/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • iPhone XS Max • 97C34A3E-909D-40D8-A018-699DDEBCBC42 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
#11895 looks similar but should be fixed in 0.8.2

**Comment by wiserbird** [comment]
This problem doesn't happen in flutter 0.9.4.
It seems that it has been fixed.
Thank you.

**Comment by zoechi** [comment]
@wiserbird thanks for the update!
Please don't hesitate to add a comment to get it reopened or create a new issue if you're seeing this again.
