### ISSUE TITLE
Coverage reporting isn't working anymore

### ISSUE THREAD

**Issue by MaximilianKlein** [flutter/flutter#22497]
## Steps to Reproduce

1. Create a new flutter application (I used `flutter create -i swift -a kotlin coverage`). The problem occurs in every project.
2. Run tests with coverage in the newly created application (`cd coverage && flutter test --coverage`)

---

 - I'm on the master channel, I also tried it with the dev channel, same problem there
 - I also removed my whole flutter directory and ~/.pub-cache and re-downloaded it.. I once had some caching issues, wanted to rule them out

## Logs

```
> flutter test --coverage --verbose
flutter test --coverage --verbose
[  +32 ms] executing: [/machine-path/Dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/machine-path/Dev/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/machine-path/Dev/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[        ] executing: [/machine-path/Dev/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2a8e35cc9c42e6957b069439eaa56207afed5ea2
[        ] executing: [/machine-path/Dev/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[   +1 ms] executing: [/machine-path/Dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.9.5-35-g2a8e35cc9
[ +398 ms] switching to directory LocalDirectory: 'test' to run tests
[        ] running test package with arguments: [-r, compact, --concurrency=6, --, /machine-path/Dev/coverage/coverage/test/widget_test.dart]
00:00 +0: ... /machine-path/Dev/coverage/coverage/test/widget_test.dart              [ +139 ms] test 0: starting test /machine-path/Dev/coverage/coverage/test/widget_test.dart
[  +21 ms] test 0: starting shell process
[   +2 ms] Stopping scan for flutter_test_config.dart; found project root at /machine-path/Dev/coverage/coverage
[   +1 ms] Compiler will use the following file as its incremental dill file: /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_compiler.aqT4Cm/output.dill
[        ] Listening to compiler controller...
[   +3 ms] Compiling /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_listener.uyr0XQ/listener.dart
[   +7 ms] /machine-path/Dev/flutter/bin/cache/dart-sdk/bin/dart /machine-path/Dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /machine-path/Dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_compiler.aqT4Cm/output.dill --packages /machine-path/Dev/coverage/coverage/.packages --initialize-from-dill /machine-path/Dev/coverage/coverage/build/testfile.dill
00:01 +0: ... /machine-path/Dev/coverage/coverage/test/widget_test.dart              [+1533 ms] Compiling /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_listener.uyr0XQ/listener.dart took 1540ms
[   +1 ms] Copying platform_strong.dill file from /machine-path/Dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/platform_strong.dill
[   +8 ms] /machine-path/Dev/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --flutter-assets-dir=/var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_bundle.SpkNWV --enable-checked-mode --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts --packages=/machine-path/Dev/coverage/coverage/.packages /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_listener.uyr0XQ/listener.dart.dill
[   +1 ms] Using this directory for fonts configuration: /var/folders/mm/wbdn_k8n5rjfvqdtq53t8ttc0000gn/T/flutter_test_fonts.Kq4qKh
[  +11 ms] test 0: awaiting initial result for pid 49094
[  +96 ms] Shell: Observatory listening on http://127.0.0.1:57385/
[        ] test 0: using observatory uri http://127.0.0.1:57385/ from pid 49094
[ +228 ms] test 0: process with pid 49094 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 49094
00:02 +1: Counter increments smoke test                                                       [ +712 ms] test 0: process with pid 49094 no longer needed by test harness
[        ] test 0: collecting coverage
[   +1 ms] pid 49094: collecting coverage data from http://127.0.0.1:57385/...
00:10 +1: Counter increments smoke test                                                       [+7400 ms] test 0: error caught during test; reporting to console
[        ] unhandled error during test:
           /machine-path/Dev/coverage/coverage/test/widget_test.dart
           Bad state: Couldn't find line and column for token 2529 in file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart.
           #0      VMScript._lineAndColumn (package:vm_service_client/src/script.dart:243:5)
           #1      _ScriptLocation._ensureLineAndColumn (package:vm_service_client/src/script.dart:314:26)
           #2      _ScriptLocation.line (package:vm_service_client/src/script.dart:295:5)
           #3      _getCoverageJson (package:coverage/src/collect.dart:103:46)
           <asynchronous suspension>
           #4      _getAllCoverage (package:coverage/src/collect.dart:51:26)
           <asynchronous suspension>
           #5      collect (package:coverage/src/collect.dart:35:18)
           <asynchronous suspension>
           #6      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55:45)
           <asynchronous suspension>
           #7      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
           <asynchronous suspension>
           #8      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:649:30)
           <asynchronous suspension>
           #9      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:407:36)
           #10     PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
           <asynchronous suspension>
           #11     Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:248:36)
           <asynchronous suspension>
           #12     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89:31)
           <asynchronous suspension>
           #13     invoke (package:test/src/utils.dart:242:5)
           #14     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88:7)
           #15     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
           <asynchronous suspension>
           #16     new Future.<anonymous closure> (dart:async/future.dart:176:37)
           #17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
           #18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
           #19     _rootRun (dart:async/zone.dart:1120:38)
           #20     _CustomZone.run (dart:async/zone.dart:1021:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
           #24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
           #25     _rootRun (dart:async/zone.dart:1124:13)
           #26     _CustomZone.run (dart:async/zone.dart:1021:19)
           #27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
           #28     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
           #29     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
           #30     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
           #31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

[  +10 ms] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[  +25 ms] test 0: deleting temporary bundle directory
[   +1 ms] test 0: deleting temporary directory
[   +2 ms] test 0: shutting down test harness socket server
[   +1 ms] test 0: finished with out-of-band failure
00:10 +1 -1: loading /machine-path/Dev/coverage/coverage/test/widget_test.dart [E]
  Bad state: Couldn't find line and column for token 2529 in file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart.
  package:vm_service_client/src/script.dart 243:5               VMScript._lineAndColumn
  package:vm_service_client/src/script.dart 314:26              _ScriptLocation._ensureLineAndColumn
  package:vm_service_client/src/script.dart 295:5               _ScriptLocation.line
  package:coverage/src/collect.dart 103:46                      _getCoverageJson
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                             _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18                  _AsyncAwaitCompleter.completeError
  package:coverage/src/collect.dart                             _getCoverageJson
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getCoverageJson
  package:coverage/src/collect.dart 51:26                       _getAllCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getAllCoverage
  package:coverage/src/collect.dart 35:18                       collect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             collect
  package:flutter_tools/src/test/coverage_collector.dart 55:45  CoverageCollector.collectCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 407:36   _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 65:19            PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:test/src/runner/loader.dart                           Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89:31                 new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
```

```
> flutter analyze
Analyzing coverage...
No issues found! (ran in 2.9s)
```

```
> flutter doctor -v
[✓] Flutter (Channel master, v0.9.6-pre.35, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.6-pre.35 at /machine-path/Dev/flutter
    • Framework revision 2a8e35cc9c (2 days ago), 2018-09-29 08:29:28 +0700
    • Engine revision 0c2b6dc6e3
    • Dart version 2.1.0-dev.6.0.flutter-2aac05fe10

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /machine-path/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jensjoha** [comment]
I cannot reproduce on Linux, but it does appear to happen on Windows. I'll investigate.

**Comment by jensjoha** [comment]
Some background:

File uris, source code for the files and the line-ending information for the files is stored in the dill file produced when compiling.
To void saving duplicate data some information is logically left out, so that only the file uri is stored. This is done for the sdk, i.e. the stuff that the VM already knows about. When loading this url-only in the VM, we match-up the url with what the VM already know so we can reference the same source and line-ending information. This required the urls to be the same though. Otherwise there can be no matching up and referencing the source and line-ending information, and empty ones is used instead.

When we compile we compile against the flutter_patched_sdk, and source/line-endings in this file is left out.
As it turns out, we use the same flutter_patched_sdk for all platforms (linux, mac, windows). This file has the absolute uri "file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart".

The linux, mac and windows builds of the VM (flutter_tester), though, apparently uses a locally-build sdk. The url included in the VM matches on linux, but differs on both mac and windows. As a consequence the matching and referencing works fine on linux, but fails on mac and windows.

```
flutter_patched_sdk/platform_strong.dill: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart
linux flutter_tester: file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart
darwin flutter_tester: file:///b/build/slave/Mac_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart
windows flutter_tester: file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart
```

In the dart-sdk we're building the platform dill file with a custom url scheme so the urls looks like this instead: "org-dartlang-sdk:///sdk/lib/collection/list.dart".
I believe that doing the same for flutter would solve the problem.

**Comment by zanderso** [comment]
It sounds like we should change the `*.dart` entry in `.gitattributes` from:
```
*.dart text
```
to
```
*.dart text eol=lf
```
to avoid auto normalizing on checkout.

And then run:
```
$ git add --renormalize .
```

to make sure that nothing was accidentally checked in with crlf. @jensjoha Can you give that a shot?

**Comment by aam** [comment]
In my experiments after changing and committing `.gitattributes` as per http://go/gh/flutter/flutter/issues/22497#issuecomment-426323697 I had to do 
```
c:> git rm --cached -r .
c:> git reset --hard
```
to have those changes go into effect.

**Comment by dnfield** [comment]
The line endings seems to only be part of it.  Even on Linux, I'm seeing coverage being broken - I just don't get exceptions from vm_service, just this:

```
unhandled error during test:
/usr/local/google/home/dnfield/src/flutter_svg/test/parser_svg_test.dart
Exception: Failed to collect coverage, process terminated prematurely with exit code -11.
#0      CoverageCollector.collectCoverage.<anonymous closure> (package:flutter_tools/src/test/coverage_collector.dart:53:9)
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#2      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#3      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by jensjoha** [comment]
Thanks @dnfield --- I now have a fix for that in review.

**Comment by Hixie** [comment]
Any news on this?

**Comment by dnfield** [comment]
Just to add here - this seemed to be fixed, then it regressed again, and was the cause of the most recent Dart SDK rollback AFAIK.

**Comment by mmcc007** [comment]
As mentioned  in dart-lang/sdk/issues/34561 and FWIW

For me on travis it works for dev on osx and linux, works for beta on linux, but fails for beta on osx
```
Bad state: Couldn't find line and column for token 2529 in file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart.
```
Haven't tried master

https://travis-ci.org/mmcc007/modal_progress_hud/builds/444449740

**Comment by diegoveloper** [comment]
it seems like is working on beta channel but not in dev/master

**Comment by mmcc007** [comment]
working for me on all channels on both linux and mac:
https://travis-ci.org/mmcc007/modal_progress_hud/builds/469575747

**Comment by MaximilianKlein** [comment]
Thank you very much, it works for me now.

**Comment by NickoftheSouth** [comment]
I've just tried to get coverage info with version `2.3.0 ` and Flutter version 
`Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.590], locale
    en-NZ)`
And I can't get it to work at all. The coverage data is definitely there, and valid. I can view the lcov file in the Atom editor.

**Comment by dnfield** [comment]
@NickoftheSouth that sounds like a different issue fro mwhat was reported here - the issue here is about running `flutter test --coverage` crashing.  Can you post a new issue with your problem?  feel free ot tag me in it!
