### ISSUE TITLE
Flutter upgrade crash report

### ISSUE THREAD

**Issue by mrdimaan** [flutter/flutter#22501]
## command

flutter upgrade

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /home/moein/Documents/flutter-dev/bin/cache/dart-sdk/bin/pub.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:7)
#2      runCommand (package:flutter_tools/src/base/process.dart:115:25)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133:33)
<asynchronous suspension>
#4      pub (package:flutter_tools/src/dart/pub.dart:155:18)
<asynchronous suspension>
#5      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#6      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:75:13)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._complete (dart:async/future_impl.dart:476:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.9.3-pre.20, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.3-pre.20 at /home/moein/Documents/flutter-dev
    • Framework revision 6d134e0c86 (8 days ago), 2018-09-29 08:29:28 +0700
    • Engine revision 0c2b6dc6e3
    • Dart version 2.1.0-dev.5.0.flutter-654c4babc8

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/moein/Android/Sdk
    • Android NDK at /home/moein/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • SM J730F • 5200f825ee301577 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by zoechi** [comment]
Did you check if the file `/home/moein/Documents/flutter-dev/bin/cache/dart-sdk/bin/pub` exists?
Please try deleting `/home/moein/Documents/flutter-dev/bin/cache/` and run `flutter doctor again`.

**Comment by mrdimaan** [comment]
Deleted the cache and now:
```
[✓] Flutter (Channel master, v0.9.6-pre.35, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.6-pre.35 at /home/moein/Documents/flutter-dev
    • Framework revision 2a8e35cc9c (2 days ago), 2018-09-29 08:29:28 +0700
    • Engine revision 0c2b6dc6e3
    • Dart version 2.1.0-dev.6.0.flutter-2aac05fe10

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/moein/Android/Sdk
    • Android NDK at /home/moein/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • SM J730F • 5200f825ee301577 • android-arm • Android 7.0 (API 24)

• No issues found!

```

**Comment by zoechi** [comment]
@mrdimaan thanks for the update!
Does this mean the issue can be closed?

**Comment by mrdimaan** [comment]
Yeah my problem is solved. This issue was just for the report
