### ISSUE TITLE
Add item to BottomNavigationBar dynamically at runtime

### ISSUE THREAD

**Issue by nabildevelop** [flutter/flutter#22500]
## Steps to Reproduce

1. Try to add a `BottomNavigationBarItem` at runtime to a `BottomNavigationBar`

```
class HomePageState extends State<HomePage>{
  int curIndex = 0;
  var bottomNavItems =  [
              BottomNavigationBarItem(icon: Icon(Icons.explore), title: Text("Explore")),
              BottomNavigationBarItem(icon: Icon(Icons.account_circle), title: Text("Account")),
            ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          appBar: AppBar(title: Text("Test"),),
          body: RaisedButton(
              child: Text("Add item"),
              onPressed: (){
                setState((){
                  // This line is causing issues
                  bottomNavItems.add(BottomNavigationBarItem(icon: Icon(Icons.notifications), title: Text("Notifs")));
                });
              },
            ),          
          bottomNavigationBar: BottomNavigationBar(
            currentIndex: curIndex,
            items: bottomNavItems,
            onTap: (index){
              setState((){
                curIndex = index;
              });
            },
          ),
        );
  }
}
```

## Logs

1. Exception

```
I/flutter ( 9980): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9980): The following RangeError was thrown building BottomNavigationBar(dirty, state:
I/flutter ( 9980): _BottomNavigationBarState#d4de1(tickers: tracking 2 tickers)):
I/flutter ( 9980): RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
I/flutter ( 9980):
I/flutter ( 9980): When the exception was thrown, this was the stack:
I/flutter ( 9980): #0      List.[] (dart:core/runtime/libgrowable_array.dart:142:60)
I/flutter ( 9980): #1      _BottomNavigationBarState._createTiles (package:flutter/src/material/bottom_navigation_bar.dart:449:26)
I/flutter ( 9980): #2      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:539:47)
I/flutter ( 9980): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
I/flutter ( 9980): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
I/flutter ( 9980): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9980): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9980): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter ( 9980): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter ( 9980): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #25     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9980): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9980): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #35     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter ( 9980): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter ( 9980): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9980): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter ( 9980): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter ( 9980): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter ( 9980): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 9980): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 9980): #61     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 9980): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 9980): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9980): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9980): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9980): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9980): #67     _invoke (dart:ui/hooks.dart:128:13)
I/flutter ( 9980): #68     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter ( 9980): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

2. flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [version 10.0.16299.431], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.27.2)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by Xavjer** [comment]
You are adding your `BottomNavigationBarItem` to your `bottomNavItems` array, not to your `BottomNavigationBar` (This is not the same array object anymore after creating the Bar), therefore it still only has 2 Items and you try to call item 3 which is then out of range.

You can either try using a [TabController](https://docs.flutter.io/flutter/material/TabController-class.html)

Or create a variable containing `BottomNavigationBar` and then add it to it directly in your `setState` `yourBottomNavigationBar.items.add(BottomNavigationBarItem(icon: Icon(Icons.notifications), title: Text("Notifs")));`

This is no flutter issue and therefore the issue should be closed.

**Comment by jonahwilliams** [comment]
Mutating the list of bottom nav bar items is causing the issue here. I've opened a PR to give a better error message. In this case, replacing `items: bottomNavItems` with `items: List.of(bottomNavItems)` will fix the issue
