### ISSUE TITLE
Crash in _ScrollableScope. TextDirection!=null is not true

### ISSUE THREAD

**Issue by isaacgg** [flutter/flutter#22523]
## Steps to Reproduce
Hello, this is my firts code. For the moment it is just a ListView with custom ListTile. I'm getting an error which points outside my code so I think this might be a bug. 
I'm runnig this on my Xiaomi Redmi 4A.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

var info1 = MatchInfo(competition: 'LaLiga', date: new DateTime(2018,12,1), isFinish: true, scoreAway: 2, scoreHome: 1, teamAway: 'Getafe', teamHome: 'Eibar');
var info2 = MatchInfo(competition: 'LaLiga', date: new DateTime(2018,12,1), isFinish: true, scoreAway: 3, scoreHome: 2, teamAway: 'Betis', teamHome: 'Leganes');
var info3 = MatchInfo(competition: 'LaLiga', date: new DateTime(2018,12,1), isFinish: true, scoreAway: 5, scoreHome: 3, teamAway: 'Fujiyama', teamHome: 'Barca');

class MyApp extends StatelessWidget{

  @override
    Widget build(BuildContext context) {
      // TODO: implement build
      return new ListView(
        children: <Widget>[
          new MatchListItem(info1),
          new MatchListItem(info2),
          new MatchListItem(info3)
        ],
      );
    }
}

class MatchInfo{
  final String teamHome;
  final String teamAway;
  final int scoreHome;
  final int scoreAway;
  final String competition;
  final DateTime date;
  final bool isFinish;
  MatchInfo({this.teamHome, this.teamAway, 
  this.scoreHome, this.scoreAway, this.competition, this.date, 
  //this.events, 
  this.isFinish});
}

class MatchListItem extends StatelessWidget{
  final MatchInfo info;

  MatchListItem(this.info);

  @override
  Widget build(BuildContext context) {
      // TODO: implement build

      return new ListTile(
        title: Text('${info.teamAway} - ${info.teamAway}', textDirection: TextDirection.ltr,),
      );
    }
}

```
## Logs
This are my logs.
```
Launching lib\main.dart on Redmi 4A in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (13636): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13636): The following assertion was thrown building _ScrollableScope:
I/flutter (13636): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
I/flutter (13636): != null': is not true.
I/flutter (13636):
I/flutter (13636): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13636): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13636): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13636):   https://github.com/flutter/flutter/issues/new
I/flutter (13636):
I/flutter (13636): When the exception was thrown, this was the stack:
I/flutter (13636): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
I/flutter (13636): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
I/flutter (13636): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
I/flutter (13636): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4288:28)
I/flutter (13636): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4767:11)
I/flutter (13636): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter (13636): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (13636): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (13636): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (13636): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter (13636): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (13636): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (13636): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter (13636): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter (13636): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (13636): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (13636): #79     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
I/flutter (13636): #80     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
I/flutter (13636): #81     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
I/flutter (13636): #82     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (13636): #83     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
I/flutter (13636): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
I/flutter (13636): #85     runApp (package:flutter/src/widgets/binding.dart:728:7)
I/flutter (13636): #86     main (file:///C:/Users/cube/Documents/Flutter/sport_stats/lib/main.dart:3:16)
I/flutter (13636): #87     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter (13636): #88     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (13636): (elided 2 frames from class _AssertionError)
I/flutter (13636): ════════════════════════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
Exited (sigterm)
```

**Comment by salihgueler** [comment]
Please ask your code related questions on stackoverflow before creating an issue. 

The problem is you are using material related classes without wrapping them with MaterialApp.

When you simply wrap your `MyApp` class with MaterialApp. It works fine.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

var info1 = MatchInfo(
    competition: 'LaLiga',
    date: new DateTime(2018, 12, 1),
    isFinish: true,
    scoreAway: 2,
    scoreHome: 1,
    teamAway: 'Getafe',
    teamHome: 'Eibar');
var info2 = MatchInfo(
    competition: 'LaLiga',
    date: new DateTime(2018, 12, 1),
    isFinish: true,
    scoreAway: 3,
    scoreHome: 2,
    teamAway: 'Betis',
    teamHome: 'Leganes');
var info3 = MatchInfo(
    competition: 'LaLiga',
    date: new DateTime(2018, 12, 1),
    isFinish: true,
    scoreAway: 5,
    scoreHome: 3,
    teamAway: 'Fujiyama',
    teamHome: 'Barca');

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new MaterialApp(
      home: Scaffold(
        body: new ListView(
          children: <Widget>[
            new MatchListItem(info1),
            new MatchListItem(info2),
            new MatchListItem(info3)
          ],
        ),
      ),
    );
  }
}

class MatchInfo {
  final String teamHome;
  final String teamAway;
  final int scoreHome;
  final int scoreAway;
  final String competition;
  final DateTime date;
  final bool isFinish;
  MatchInfo(
      {this.teamHome,
      this.teamAway,
      this.scoreHome,
      this.scoreAway,
      this.competition,
      this.date,
      //this.events,
      this.isFinish});
}

class MatchListItem extends StatelessWidget {
  final MatchInfo info;

  MatchListItem(this.info);

  @override
  Widget build(BuildContext context) {
    // TODO: implement build

    return new ListTile(
      title: Text(
        '${info.teamAway} - ${info.teamAway}',
        textDirection: TextDirection.ltr,
      ),
    );
  }
}

```

**Comment by isaacgg** [comment]
Ok, sorry I thought this was a bug

**Comment by Monotoba** [comment]
I think the bug is in the example code on the pub page. This needs to be fixed so new users of the package do not continue to have this issue. This issue was posted months ago and still the example code on the pub page has not been corrected and gives this error. The example is expected to be a "working" example. Otherwise it is useless to new users and will cause more confusion than clarification.

As far as I am concerned, isaacgg is correct in posting an issue. He is only incorrect claiming the issue is with the Provider package when in fact it is with the sample code given on the Provider pub page: https://pub.dev/packages/provider#-example-tab-.
