### ISSUE TITLE
Text(data: null) should throw a better error message

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#22542]
Simple mistake I made when creating an app out of the default `flutter create` template and forgetting to remove the title, but this should give a better error message since it's one that a first-hour developer is relatively more likely to encounter. In text.dart, we simply assert this field is not null. (And since we suggest filing an issue in the exception report, I'm doing so.)

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
D/EGL_emulation(18137): eglMakeCurrent: 0xdb805ac0: ver 2 0 (tinfo 0xda5db050)
D/EGL_emulation(18137): eglMakeCurrent: 0xdd085420: ver 2 0 (tinfo 0xdd083510)
I/flutter (18137): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18137): The following assertion was thrown building HomePage(dirty, state: _HomePageState#a99c9):
I/flutter (18137): 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
I/flutter (18137): true.
I/flutter (18137):
I/flutter (18137): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18137): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18137): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18137):   https://github.com/flutter/flutter/issues/new
I/flutter (18137):
I/flutter (18137): When the exception was thrown, this was the stack:
I/flutter (18137): #2      new Text (package:flutter/src/widgets/text.dart:230:15)
I/flutter (18137): #3      _HomePageState.build (file:///Users/timsneath/git/me/homealtar/lib/home.dart:25:16)
I/flutter (18137): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (18137): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (18137): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #100    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4901:32)
I/flutter (18137): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #103    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
I/flutter (18137): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #108    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #109    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #129    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #132    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
D/        (18137): HostConnection::get() New Host Connection established 0xdd0a05c0, tid 18172
D/EGL_emulation(18137): eglMakeCurrent: 0xdb805ac0: ver 2 0 (tinfo 0xdd0833f0)
I/flutter (18137): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #148    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #165    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #177    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #178    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #180    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #181    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (18137): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #187    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #198    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #200    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #201    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #217    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #218    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #225    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #226    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #228    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #230    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #231    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #232    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #233    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #234    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #236    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #237    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #238    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (18137): #239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (18137): #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (18137): #244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (18137): #245    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (18137): #246    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (18137): #247    Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (18137): #248    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:898:16)
I/flutter (18137): #249    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:869:5)
I/flutter (18137): #250    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:815:17)
I/flutter (18137): #251    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (18137): #252    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:814:13)
I/flutter (18137): #253    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:706:7)
I/flutter (18137): #254    runApp (package:flutter/src/widgets/binding.dart:745:7)
I/flutter (18137): #255    main (file:///Users/timsneath/git/me/homealtar/lib/main.dart:5:16)
I/flutter (18137): #256    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter (18137): #257    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (18137): (elided 2 frames from class _AssertionError)
I/flutter (18137): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Piinks** [comment]
Looks like this was fixed by #28709. 😃
