### ISSUE TITLE
Choice Chip throws an exception without (not required) pressElevation

### ISSUE THREAD

**Issue by MaximilianKlein** [flutter/flutter#22569]
## Steps to Reproduce

1. Start Flutter-Gallery Example
2. Navigate to Material/Chips
3. Tap (a bit longer) on a Choice Chip

![image](https://user-images.githubusercontent.com/35526809/46371221-14b41c00-c688-11e8-831d-ac4c9c0c1e70.png)

The behavior changed a few versions ago. If you provide a value for `pressElevation` it works again, but it is not marked as required (or it has no default value). It seems that this is rather new, I couldn't find a documentation for `pressElevation`.

## Logs

```
I/flutter ( 9731): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9731): The following assertion was thrown building RawChip(dirty, state: _RawChipState#2db2e(tickers:
I/flutter ( 9731): tracking 4 tickers)):
I/flutter ( 9731): 'package:flutter/src/material/material.dart': Failed assertion: line 179 pos 15: 'elevation !=
I/flutter ( 9731): null': is not true.
I/flutter ( 9731):
I/flutter ( 9731): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9731): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9731): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9731):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9731):
I/flutter ( 9731): When the exception was thrown, this was the stack:
I/flutter ( 9731): #2      new Material (package:flutter/src/material/material.dart:179:15)
I/flutter ( 9731): #3      _RawChipState.build (package:flutter/src/material/chip.dart:1466:21)
I/flutter ( 9731): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter ( 9731): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter ( 9731): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 9731): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 9731): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
I/flutter ( 9731): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9731): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9731): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9731): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9731): #13     _invoke (dart:ui/hooks.dart:139:13)
I/flutter ( 9731): #14     _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter ( 9731): (elided 2 frames from class _AssertionError)
I/flutter ( 9731): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9731): Another exception was thrown: setState() or markNeedsBuild() called when widget tree was locked.
I/flutter ( 9731): Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 179 pos 15: 'elevation != null': is not true.
I/flutter ( 9731): Another exception was thrown: setState() or markNeedsBuild() called when widget tree was locked.
```

```
Analyzing flutter_gallery...
No issues found! (ran in 11.0s)
```

```
[✓] Flutter (Channel master, v0.9.6-pre.48, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.6-pre.48 at /<path>/flutter
    • Framework revision 4bd6ad7395 (13 hours ago), 2018-10-02 08:36:21 +0200
    • Engine revision b59c864931
    • Dart version 2.1.0-dev.6.0.flutter-8a919426f0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /<path>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
@jslavitz we need to add the default press elevation to all of the constructors, since it's only in RawChip, all of the parent classes will overwrite it.

**Comment by MaximilianKlein** [comment]
Thanks 👍
