### ISSUE TITLE
Google Maps: Cannot interpret 6 as an activity state

### ISSUE THREAD

**Issue by gonzalonm** [flutter/flutter#22607]
## Steps to Reproduce

1. Be installed `google_sign_in` plugin (not sure if it's needed)
2. Install `google_maps_plugin` plugin
2. Implement `GoogleMap` widget (see example)
3. Do login with a Google account (not sure if it's needed)
4. Open map page

**Expected result:**
Map page draws map without conflict

**Current result:**
Map page is crashing and GoogleMap is not displayed
I'm not sure if the problem is with google_sign_in plugin or the implementation of mi side.

Code:
https://gist.github.com/gonzalonm/e93fedfe8c41b27823d3dfc6d4d8a088

## Logs

```
[ +104 ms] E/MethodChannel#flutter/platform_views(12991): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views(12991): java.lang.IllegalArgumentException: Cannot interpret 6 as an activity state
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:113)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:22)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:26)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:130)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.app.Dialog.show(Dialog.java:302)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.app.Presentation.show(Presentation.java:249)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:75)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:47)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:150)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:89)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
[        ] E/MethodChannel#flutter/platform_views(12991):       at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.os.MessageQueue.next(MessageQueue.java:325)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.os.Looper.loop(Looper.java:142)
[        ] E/MethodChannel#flutter/platform_views(12991):       at android.app.ActivityThread.main(ActivityThread.java:6541)
[        ] E/MethodChannel#flutter/platform_views(12991):       at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/MethodChannel#flutter/platform_views(12991):       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[        ] E/MethodChannel#flutter/platform_views(12991):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
[        ] E/flutter (12991): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
[        ] E/flutter (12991): PlatformException(error, Cannot interpret 6 as an activity state, null)
[   +1 ms] E/flutter (12991): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
[        ] E/flutter (12991): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
[        ] E/flutter (12991): <asynchronous suspension>
[        ] E/flutter (12991): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:541:54)
[  +47 ms] E/flutter (12991): <asynchronous suspension>
[        ] E/flutter (12991): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:465:14)
[        ] E/flutter (12991): <asynchronous suspension>
[        ] E/flutter (12991): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:143:29)
[        ] E/flutter (12991): <asynchronous suspension>
[        ] E/flutter (12991): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:124:5)
[        ] E/flutter (12991): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1548:9)
[        ] E/flutter (12991): #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:262:13)
[        ] E/flutter (12991): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #9      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
[   +1 ms] E/flutter (12991): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
[        ] E/flutter (12991): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
[        ] E/flutter (12991): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #15     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
[        ] E/flutter (12991): #16     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
[        ] E/flutter (12991): #17     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
[   +3 ms] E/flutter (12991): #18     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
[        ] E/flutter (12991): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
[        ] E/flutter (12991): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
[        ] E/flutter (12991): #23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
[        ] E/flutter (12991): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
[        ] E/flutter (12991): #25     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
[        ] E/flutter (12991): #26     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
[        ] E/flutter (12991): #27     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
[        ] E/flutter (12991): #28     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
[        ] E/flutter (12991): #29     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
[        ] E/flutter (12991): #30     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
[        ] E/flutter (12991): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
[        ] E/flutter (12991): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
[        ] E/flutter (12991): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[        ] E/flutter (12991): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] E/flutter (12991): #35     _WidgetsFlu
```

```
info • Name non-constant identifiers using lowerCamelCase • lib/data/calendar_service.dart:9:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/calendar_service.dart:10:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/repository/datastore/calendar_datastore.dart:14:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/repository/datastore/calendar_datastore.dart:15:7 • non_constant_identifier_names
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement • lib/data/repository/datastore/disk_speaker_datastore.dart:22:3 • missing_return
   info • The top level variable '_INIT_TABLE_RANGE' isn't used • lib/data/sheet_service.dart:12:7 • unused_element
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement • lib/domain/usecase/speakers_use_case.dart:18:3 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/home/countdown_event.dart:10:7 • non_constant_identifier_names
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/ui/speaker/speaker_detail.dart:4:7 • must_be_immutable
```

```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.12.6 16G1510, locale en-AR)
    • Flutter version 0.7.3 at [path_to_flutter]
    • Framework revision 3b309bda07 (5 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at [path_to_android_sdk]
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = [path_to_android_sdk]
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by KieranSteyn** [comment]
I'm getting the same error, is there a workaround?

`E/MethodChannel#flutter/platform_views(17205): Failed to handle method call
E/MethodChannel#flutter/platform_views(17205): java.lang.IllegalArgumentException: Cannot interpret 6 as an activity state
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:113)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:22)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:26)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:130)
E/MethodChannel#flutter/platform_views(17205): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
E/MethodChannel#flutter/platform_views(17205): 	at android.app.Dialog.show(Dialog.java:302)
E/MethodChannel#flutter/platform_views(17205): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:75)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:47)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:179)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:118)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter/platform_views(17205): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter/platform_views(17205): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(17205): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(17205): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter/platform_views(17205): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter/platform_views(17205): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(17205): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter/platform_views(17205): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (17205): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (17205): PlatformException(error, Cannot interpret 6 as an activity state, null)
E/flutter (17205): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (17205): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (17205): <asynchronous suspension>
E/flutter (17205): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:541:54)
E/flutter (17205): <asynchronous suspension>
E/flutter (17205): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:465:14)
E/flutter (17205): <asynchronous suspension>
E/flutter (17205): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:145:29)
E/flutter (17205): <asynchronous suspension>
E/flutter (17205): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:126:5)
E/flutter (17205): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1616:9)
E/flutter (17205): #7      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
E/flutter (17205): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
E/flutter (17205): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
E/flutter (17205): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
E/flutter (17205): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
E/flutter (17205): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
E/flutter (17205): #13     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:386:13)
E/flutter (17205): #14     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:208:17)
E/flutter (17205): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
E/flutter (17205): #16     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
E/flutter (17205): #17     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
E/flutter (17205): #18     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
E/flutter (17205): #19     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
E/flutter (17205): #20     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
E/flutter (17205): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
E/flutter (17205): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
E/flutter (17205): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
E/flutter (17205): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (17205): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
E/flutter (17205): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
E/flutter (17205): #27     _invoke (dart:ui/hooks.dart:139:13)
E/flutter (17205): #28     _drawFrame (dart:ui/hooks.dart:128:3)`

`[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-ZA)
    • Flutter version 0.9.4 at D:\Android\flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.28.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Nexus 5X • 00ca51fa8fd7142a • android-arm64 • Android 8.1.0 (API 27)

• No issues found!`

**Comment by duncanhoggan** [comment]
+1 bump.

**Comment by duncanhoggan** [comment]
I've added in the missing Destroyed state in [this](https://github.com/duncanhoggan/plugins/tree/map_activity_state) branch but there is another issue below, looks like its also linked to some kind of life-cycle issue. We are on the brink of shipping an app and this has become a blocking bug, any support/comments are appreciated.

**Comment by sh0umik** [comment]
I stil dont have any explanation to this error but i solved this problem by removing lot of async functions from setState ! Basically i was doing many tings in setState function and lot of those func had async and await on them ! its weird, when i cleaned my code the error is gone !!

**Comment by santubuddy** [comment]
Is there any update

**Comment by kunit1** [comment]
This should already be fixed in the google maps plugin. [PR](https://github.com/flutter/plugins/pull/882)
