### ISSUE TITLE
My Flutter Application for iOS not wokring. Build Failed.

### ISSUE THREAD

**Issue by karandaid** [flutter/flutter#22644]
## Steps to Reproduce
`Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    mkdir -p <url>/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "<url>/ios/Pods/../.symlinks/flutter/ios/Flutter.framework" "<url>/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    
Could not build the application for the simulator.
Error launching application on iPhone X.
`

## Logs
**flutter run --verbose**

```

[ +125 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +180 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/beta
[   +1 ms] executing: [/Applications/flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +1 ms] executing: [/Applications/flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [/Applications/flutter/] git log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 3b309bda072a6b326e8aa4591a5836af600923ce
[   +1 ms] executing: [/Applications/flutter/] git log -n 1 --pretty=format:%ar
[  +48 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 5 weeks ago
[   +2 ms] executing: [/Applications/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +61 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.7.3-0-g3b309bda0
[+3412 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/GMS_Front/' (OS Error: Permission denied, errno = 13)
[   +1 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/drupal/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/test/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/phpmyadmin/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/GMS/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/mysql/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/performance_schema/' (OS Error: Permission denied, errno = 13)
[+3522 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +157 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +323 ms] executing: /Users/karandeepsinghdhaliwal/Library/Android/sdk/platform-tools/adb devices -l
[  +27 ms] Exit code 0 from: /Users/karandeepsinghdhaliwal/Library/Android/sdk/platform-tools/adb devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +46 ms] executing: idevice_id -h
[ +769 ms] /usr/bin/xcrun simctl list --json devices
[ +282 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +12 ms] /Users/karandeepsinghdhaliwal/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +88 ms] ro.hardware = ranchu
[  +13 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[   +2 ms] iPhone X                  • 42BE8DC6-84B6-481A-81D4-AA400CD50848 • ios         • iOS 11.4 (simulator)
[  +44 ms] "flutter run" took 8,482ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:258:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:334:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:290:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:281:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

**flutter doctor**

```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.4 17E199, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.2.4)
[!] VS Code (version 1.27.2)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
be_men_ship (17:42:00):- flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.4 17E199, locale en-CA)
    • Flutter version 0.7.3 at /Applications/flutter
    • Framework revision 3b309bda07 (5 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/karandeepsinghdhaliwal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4155.35

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone X                  • 42BE8DC6-84B6-481A-81D4-AA400CD50848 • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by krishnabhargav** [comment]
Looks like you having multiple devices connected is preventing the run. Try to specify which device you want to run (`flutter run -d <>`).

**Comment by 5ummit** [comment]
> Looks like you having multiple devices connected is preventing the run. Try to specify which device you want to run (`flutter run -d <>`).

That is correct, or if your lazy just open your project from xcode by typing in the terminal `open ios/Runner.xcworkspace` and select a emulator device from the upper right corner:
<img width="411" alt="screen shot 2018-10-04 at 15 42 18" src="https://user-images.githubusercontent.com/33470998/46474711-3b8b6300-c7ec-11e8-8dd3-43243b5a416b.png">

**Comment by karandaid** [comment]
> > Looks like you having multiple devices connected is preventing the run. Try to specify which device you want to run (`flutter run -d <>`).
> 
> That is correct, or if your lazy just open your project from xcode by typing in the terminal `open ios/Runner.xcworkspace` and select a emulator device from the upper right corner:
> <img alt="screen shot 2018-10-04 at 15 42 18" width="411" src="https://user-images.githubusercontent.com/33470998/46474711-3b8b6300-c7ec-11e8-8dd3-43243b5a416b.png">

<img width="346" alt="googleservice-info_plist" src="https://user-images.githubusercontent.com/43832806/46478438-373e5600-c7aa-11e8-94ae-b5e4c4fcbdc3.png">


![screen](https://user-images.githubusercontent.com/43832806/46478548-779dd400-c7aa-11e8-9f50-4a3b82d50c90.png)

I have both of them, I restarted everything with only one emulator. but still having this issue.

@5ummit

**Comment by 5ummit** [comment]
Try to close the android emulator when working on this and mind posting `flutter analyze` please
