### ISSUE TITLE
FutureBuilder doesn't work properly with Firestore

### ISSUE THREAD

**Issue by 5ummit** [flutter/flutter#22729]
Hi, this post is following the post ([issue #19493](https://github.com/flutter/flutter/issues/19493)).
I've been experiencing a quite obvious issue with Firestore in Flutter - you can't create a query using FutureBuilder for some reason.
I'll give you a scenario: Say for example you want to find a specific reference of document 'A' in document 'B' (both are in **different collections**) that's easy, you use a StreamBuilder with `.where(..).snapshots()` and then you build it right? This way is a possibility but it refreshes a X amount of times and it takes way too much bandwidth from the user's end.
I've been trying for a couple of days now to get a StreamBuilder function working as a FutureBuilder to save quotas and bandwidth using stuff like:

```dart
return new FutureBuilder<QuerySnapshot>(
       future: Firestore.instance.collection("locations").where(widget.currentuid, isEqualTo: uid).getDocuments(),
       builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot){
         if (snapshot.hasError) {
           return new Container(width: 0.0, height: 0.0,);
         }
         if (snapshot.connectionState == ConnectionState.waiting) {
           return new Container(width: 0.0, height: 0.0,);
         }
         if (!snapshot.hasData) { 
           return new Container(width: 0.0, height: 0.0,);
         } else if (snapshot.hasData) {
            String id = snapshot.data.documents[0]['id'];
            return new Container(
            width: 280.0,
            child: Text('It's working'),
            ),
         }
       }
      );
```

but it doesn't seem to work (P.S. Didn't try this code it's just an example).
Logs:

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): java.lang.NullPointerException: Provided field path must not be null.
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at com.google.firebase.firestore.FieldPath.zza(com.google.firebase:firebase-firestore@@17.0.5:67)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at com.google.firebase.firestore.Query.whereEqualTo(com.google.firebase:firebase-firestore@@17.0.5:122)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:149)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:487)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13706): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

```
[✓] Flutter (Channel beta, v0.8.3-pre.1, on Mac OS X 10.14.1 18B50c, locale en-UK)
    • Flutter version 0.8.3-pre.1 at /Users/administrator/dev/flutter
    • Framework revision 92ce035fc8 (2 weeks ago), 2018-09-20 19:59:47 +0300
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/administrator/Library/Android/sdk/
    • Android NDK at /Users/administrator/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/administrator/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L232m
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

Firestore is at the latest version.
This is the case for both Android and iOS devices, any ideas?

**Comment by zoechi** [comment]
I'd suggest to do this work outside of widgets entirely and provide a stream to a `StreamBuilder` that only emits a new event when there is initial data or updates for the view to re-render.
There you can cache query results to not fetch again from the server if you have the value already.
That's all not `StreamBuilder`s responsibility. All the `StreamBuilder` does is to re-execute the build function when a new value is emitted from the stream.

**Comment by zoechi** [comment]
See also https://pub.dartlang.org/packages/rxdart for about combining streams in powerful ways.

**Comment by 5ummit** [comment]
Thank you @zoechi for pointing me in a direction, although I didn't quite understand I'll looking around - sent you a message if you could help me it'd be great but to keep this issue useful I'll be closing it here.
