### ISSUE TITLE
When using cloud firestore on iOS, the app was killed

### ISSUE THREAD

**Issue by socar-kong** [flutter/flutter#22736]
## Steps to Reproduce

I just tried to use the cloud firestore.
However, the following bug was caused while running iOS application.
## Logs

```
[  +34 ms] executing: [/Users/kyeonghwan-kong/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/kyeonghwan-kong/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/kyeonghwan-kong/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/kyeonghwan-kong/flutter/] git log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5ab9e70727d858def3a586db7fb98ee580352957
[        ] executing: [/Users/kyeonghwan-kong/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[        ] executing: [/Users/kyeonghwan-kong/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.8.2-0-g5ab9e7072
[ +330 ms] executing: /Users/kyeonghwan-kong/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/kyeonghwan-kong/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ce0417146180ac1702     device usb:338755584X product:dream2lteks model:SM_G955N device:dream2lteks transport_id:1
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +14 ms] executing: idevice_id -h
[  +42 ms] /usr/bin/xcrun simctl list --json devices
[ +203 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] /Users/kyeonghwan-kong/Library/Android/sdk/platform-tools/adb -s ce0417146180ac1702 shell getprop
[ +119 ms] ro.hardware = samsungexynos8895
[   +2 ms] /Users/kyeonghwan-kong/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +27 ms] ro.hardware = ranchu
[   +3 ms] SM G955N                  • ce0417146180ac1702                   • android-arm64 • Android 8.0.0 (API 26)
[        ] Android SDK built for x86 • emulator-5554                        • android-x86   • Android 8.1.0 (API 27) (emulator)
[        ] iPhone XS Max             • FF00A34F-7D49-4625-BEBA-6B4C97A8CEED • ios           • iOS 12.0 (simulator)
[  +19 ms] "flutter run" took 699ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:239:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
Analyzing sample_flutter_chat_app...                             

   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:7:8 • unused_import
   info • Unused import: 'package:sample_flutter_chat_app/main.dart' • test/widget_test.dart:10:8 • unused_import

2 issues found. (ran in 2.6s)
```

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ko-KR)
    • Flutter version 0.8.2 at /Users/kyeonghwan-kong/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/kyeonghwan-kong/Library/Android/sdk
    • Android NDK at /Users/kyeonghwan-kong/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (3 available)
    • SM G955N                  • ce0417146180ac1702                   • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 8.1.0 (API 27) (emulator)
    • iPhone XS Max             • FF00A34F-7D49-4625-BEBA-6B4C97A8CEED • ios           • iOS 12.0 (simulator)

! Doctor found issues in 2 categories.
```

😭

**Comment by socar-kong** [comment]
*SelfAnswer*
The bundle ID in Xcode has confirmed that is a capital letter.
When registering an iOS project in Firebase, I replaced all uppercase letters in the bundle ID with all lowercase letters and registered them with firebase.

and solved it.
