### ISSUE TITLE
Catch a Thrown Exception from Another Function

### ISSUE THREAD

**Issue by pahlevi91** [flutter/flutter#22734]
Hi,
I am new to Flutter, I have a problem when I am trying to catch a thrown exception from another function. Here is the source code that I got from [here](https://medium.com/@kashifmin/flutter-login-app-using-rest-api-and-sqflite-b4815aed2149).

The function A that throw an Exception

```
Future<User> login(String username, String password) {    
    return _netUtil.post(LOGIN_URL, body: {
      "username": username,
      "password": password
    }).then((dynamic res) {
      if(res["user"].containsKey["errors"]) {
        throw new Exception("There is an error!");
      } 
      return new User.map(res["user"]);
    });
  }
```

The function B that catch an exception then show it to the user
```
class LoginScreenPresenter {
  LoginScreenContract _view;
  RestDatasource api = new RestDatasource();
  LoginScreenPresenter(this._view);

  doLogin(String username, String password) {
    api.login(username, password).then((User user) {
      _view.onLoginSuccess(user);
      print("Tada~~");
    }).catchError((Exception error) {
      _view.onLoginError(error.toString());
    });
  }
}
```

However, there is a runtime error in function A:
```
E/flutter ( 8063): #18     NetworkUtil.post (package:cownect_mobile/utils/network_util.dart:26:12)
E/flutter ( 8063): #19     RestDatasource.login (package:cownect_mobile/data/rest_data_format.dart:12:21)
E/flutter ( 8063): <asynchronous suspension>
E/flutter ( 8063): #20     LoginScreenPresenter.doLogin (package:cownect_mobile/screens/login/login_screen_presenter.dart:15:9)
E/flutter ( 8063): #21     _LoginScreenState._submit (package:cownect_mobile/screens/login/login_screen.dart:55:18)
E/flutter ( 8063): #22     _LoginScreenState.build.<anonymous closure> (package:cownect_mobile/screens/login/login_screen.dart:171:29)
E/flutter ( 8063): #23     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 8063): #24     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 8063): #25     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 8063): #26     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 8063): #27     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 8063): #28     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 8063): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter ( 8063): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter ( 8063): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 8063): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter ( 8063): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter ( 8063): #34     _invoke1 (dart:ui/hooks.dart:153:13)
E/flutter ( 8063): #35     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```

I'm stuck in this error and already looked for the solution but still no result.

**Comment by zoechi** [comment]
It's easier to use `async`/`await` with `try`/`catch` than the `catchError` API where it is easier to use it wrongly

```
class LoginScreenPresenter {
  LoginScreenContract _view;
  RestDatasource api = new RestDatasource();
  LoginScreenPresenter(this._view);

  doLogin(String username, String password) {
    try {
      var user = await api.login(username, password);
      _view.onLoginSuccess(user);
    } on Exception catch(error) {
      _view.onLoginError(error.toString());
    }
  }
}
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by pahlevi91** [comment]
I just added 'async' in the function declaration
```
  doLogin(String username, String password) async {
    try {
     var user = await api.login(username, password);
      _view.onLoginSuccess(user);
    } on Exception catch(error) {
      print("tada~~");
      _view.onLoginError(error.toString());
    }
  }
```

One more question, I was a python programmer, and when I have to deal with dictionary or arraylist, when I want to check the index I did like this 'if x in myDictionary' to check if x is index of myDictionary, how do I perform this on Dart? I tried to find it, but I haven't found the answer.

I used `containsKey` on Flutter, but it makes another error.

**Comment by Mikkal24** [comment]
Does the .catchError method simply not work?

**Comment by zoechi** [comment]
@Mikkal24 sure it does, but it's a bit tricky to get it right for all cases.
`async`/`await` is much harder to get wrong.

**Comment by Mikkal24** [comment]
I think I got it to work but, my debugger is still dealing with the exception as if it was un-handled. Separate issue I think.

**Comment by zoechi** [comment]
@Mikkal24 please report in https://github.com/dart-lang/sdk/issues

**Comment by zoechi** [comment]
@sjmcdowall if you mean `'<optimized out>'` then this is a compiler problem which removes source information required to print a proper error message. I think this was fixed already upstream and perhaps even in Flutter `dev` or `master` channel.
If you mean something else, please elaborate.

You can call async functions from everywhere. There are some places where Flutter does not wait for async results because it doesn't make sense because it needs to provide a result for the next screen render (`initState()`, `build()`, ...).

I would need more details to give concrete advice, 
but in validation you'd need to return an intermediate result (valid or invalid) without really knowing and when the async result arrives have the view updated with the validation result that uses the result from the previous async response to calculate the real validation result.

**Comment by zoechi** [comment]
@sjmcdowall 
The pattern is quite the same. Call the async function and call `setState(...)` when the async result becomes available and then when `build()` is called again because of `setState(...)`, use the async result.

> Then the linter complains

I'd consider that a good thing because it tells you that what you are attempting works agains the framework.

> `build() { Futurebuilder, Streambuilder }`

I think this one is covered pretty well.

> validation

For async validator you can thumbs-up and follow #9688

If there are others check if there exists an issue already or create one.

I can't really make sense of your last paragraph.
That would require a minimal reproduction and the full error output you get, but probably better to ask on StackOverflow and create a new issue if it turns out there is actually something to for the Flutter team (fix a bug, add a feature, improve docs).

**Comment by FabioPagano** [comment]
> It's easier to use `async`/`await` with `try`/`catch` than the `catchError`
I had the same problem of the original poster, but in my case I missed an "await" calling the function "A" from the function "B", so the catch in the function "B" (that I wanted to show) was evaluated before the catch of the function "A" (because in that moment there were no error yet raised by the function "A", therefore the catch in the function "B" was not invoked). Adding the missing "await" (it was my failure) calling the "A" function, the catch of the function "B" catched the error raised by the function "A" as expected and the catch of the function "B" showed the error thrown by function "A".

**Comment by olaide-ekolere** [comment]
.catchError((error) {
      print('$error');
      errorMessage = '$error';
}
but there is always an 'Exception:' prefix
