### ISSUE TITLE
Cannot extract a file path from a package URI

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#22733]
`flutter run` fail after the flutter update.
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Unhandled exception:
Unsupported operation: Cannot extract a file path from a package URI
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4589:7)
#1      _writeDepfile (package:vm/frontend_server.dart:662:32)
<asynchronous suspension>
#2      FrontendCompiler.compile (package:vm/frontend_server.dart:367:15)
<asynchronous suspension>
#3      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#4      starter (package:frontend_server/server.dart:133:27)
<asynchronous suspension>
#5      main (file:///b/build/slave/Linux_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Compiler failed on /home/kyawtun/fwork/dartsugar/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1
```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.9.7-pre.46, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.7-pre.46 at /home/k/flutter
    • Framework revision 2d3ff10d62 (9 hours ago), 2018-10-05 07:54:56 +0200
    • Engine revision 90b1023c84
    • Dart version 2.1.0-dev.6.0.flutter-c6254163dc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/k/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /home/k/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/k/app/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /home/k/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /home/k/opt/idea-IU-182.4323.46
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /home/k/app/idea
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Merging with #22721
