### ISSUE TITLE
Error when navigating back to home screen:

### ISSUE THREAD

**Issue by khalithartmann** [flutter/flutter#22766]
Hey, I sometimes get this error when going back to the home page. Does anyone know what the cause could be? 
Thanks in advance! 
```
Error Message: 
I/flutter (20304): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20304): The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#93f80](state:
I/flutter (20304): OverlayState#ed9ed(entries: [OverlayEntry#b893f(opaque: true; maintainState: false),
I/flutter (20304): OverlayEntry#f1cd5(opaque: false; maintainState: true)])):
I/flutter (20304): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4051 pos 14:
I/flutter (20304): '_dependents.isEmpty': is not true.
I/flutter (20304): 
I/flutter (20304): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20304): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20304): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20304):   https://github.com/flutter/flutter/issues/new
I/flutter (20304): 
I/flutter (20304): When the exception was thrown, this was the stack:
I/flutter (20304): #2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4051:14)
I/flutter (20304): #3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4053:6)
I/flutter (20304): #4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1718:25)
I/flutter (20304): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1718:59)
I/flutter (20304): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (20304): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (20304): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (20304): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (20304): #10     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1726:7)
I/flutter (20304): #11     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2955:29)
I/flutter (20304): #12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4484:11)
I/flutter (20304): #13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter (20304): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (20304): #15     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (20304): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (20304): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (20304): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (20304): #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (20304): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (20304): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (20304): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (20304): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (20304): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (20304): #25     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (20304): #26     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (20304): (elided 2 frames from class _AssertionError)
I/flutter (20304): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and a minimal runnable reproduction.
