### ISSUE TITLE
Just reporting.

### ISSUE THREAD

**Issue by Adrianogba** [flutter/flutter#22760]
## What happened

Don't know... Just reporting. I mean, no visible error.

## Version information

Android Studio `3.2` • Flutter plugin `io.flutter 29.0.2` • Dart plugin `181.5616`

Error getting Flutter sdk information.

## Exception

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[Thread-29,4,Idea Thread Group] 86324668
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 3.2#AI-181.5540.7.32.5014246 Studio, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b06,6,Idea Thread Group] 1697333629
```
```
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1057)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:297)
	at io.flutter.server.vmService.VmServiceWrapper.attachIsolate(VmServiceWrapper.java:247)
	at io.flutter.server.vmService.VmServiceWrapper$1$1$1$1.received(VmServiceWrapper.java:148)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:622)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:625)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2673](https://github.com/flutter/flutter-intellij/issues/2673) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Adrianogba** [comment]
@zoechi already there
