### ISSUE TITLE
This ticker was canceled: Ticker(created by _MyHomePageState#a2d8d(lifecycle state: created))

### ISSUE THREAD

**Issue by ifrankyu** [flutter/flutter#22777]
When I was using `AnimationController.animateTo`, I received the following tips:

```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
This ticker was canceled: Ticker(created by _MyHomePageState#a2d8d(lifecycle state: created))
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
This is the smallest example to reproduce this problem.

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in IntelliJ). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'animate To Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  AnimationController progressBarAnimationController;
  Animation progressBarAnimation;

  void _incrementCounter() {
    progressBarAnimationController.forward().orCancel;
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    progressBarAnimationController = new AnimationController(
      vsync: this,
      duration: new Duration(seconds: 10),
    );

    progressBarAnimation =
        new Tween(begin: 0.0, end: 400.0).animate(new CurvedAnimation(
      parent: progressBarAnimationController,
      curve: Curves.linear,
    ));

    progressBarAnimation.addListener(() {
      setState(() {
        if (progressBarAnimation.value > 100.0) {
          progressBarAnimationController.animateTo(
            1.0,
            duration: const Duration(milliseconds: 200),
          );
        }
      });
    });

    progressBarAnimationController.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        progressBarAnimationController.animateTo(
          0.0,
          duration: Duration.zero,
        );
      }
    });
  }

  @override
  void dispose() {
    progressBarAnimationController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: new Stack(
        children: [
          new Positioned(
            left: 0.0,
            top: 0.0,
            child: new Container(
              height: 3.0,
              width: progressBarAnimation.value,
              color: Colors.green,
            ),
          )
        ],
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'animation',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

flutter doctor -v:
```
 frank@Frank-2  /web/native/animateto  flutter doctor -v
[✓] Flutter (Channel master, v0.8.7-pre.5, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.8.7-pre.5 at /web/native/flutter
    • Framework revision e2d0b062d9 (3 weeks ago), 2018-09-18 05:54:03 +0200
    • Engine revision dcbc8a8207
    • Dart version 2.1.0-dev.4.0.flutter-050561fd82

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/frank/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPhone X • 40D64B13-F4EC-4C72-9E74-C1749D568F1F • ios • iOS 11.4 (simulator)

• No issues found!
```
I would be very grateful if you could help me solve this problem.

**Comment by ifrankyu** [comment]
Thank you for your help, you are doing a great job.

**Comment by zoechi** [comment]
Sounds like expected behavior to me
```dart
  /// A future that resolves when this future resolves or throws when the ticker
  /// is canceled.
  ///
  /// If this property is never accessed, then canceling the ticker does not
  /// throw any exceptions. Once this property is accessed, though, if the
  /// corresponding ticker is canceled, then the [Future] returned by this
  /// getter will complete with an error, and if that error is not caught, there
  /// will be an uncaught exception in the current zone.
  Future<void> get orCancel {
```

removing `.orCancel` from ` progressBarAnimationController.forward().orCancel;` fixes the issue.

**Comment by ifrankyu** [comment]
> Sounds like expected behavior to me
> 
> ```dart
>   /// A future that resolves when this future resolves or throws when the ticker
>   /// is canceled.
>   ///
>   /// If this property is never accessed, then canceling the ticker does not
>   /// throw any exceptions. Once this property is accessed, though, if the
>   /// corresponding ticker is canceled, then the [Future] returned by this
>   /// getter will complete with an error, and if that error is not caught, there
>   /// will be an uncaught exception in the current zone.
>   Future<void> get orCancel {
> ```
> 
> removing `.orCancel` from ` progressBarAnimationController.forward().orCancel;` fixes the issue.

Thank you for your help, you are doing a great job.
