### ISSUE TITLE
`flutter test --coverage` on dev/master

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#22774]
When I run `flutter test --coverage` on `https://github.com/dnfield/flutter_svg`, I eventually get this output over and over again:

```
unhandled error during test:
/Users/dnfield/src/flutter_svg/test/xml_svg_test.dart
Bad state: Couldn't find line and column for token 2529 in file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart.
#0      VMScript._lineAndColumn (package:vm_service_client/src/script.dart:243:5)
#1      _ScriptLocation._ensureLineAndColumn (package:vm_service_client/src/script.dart:314:26)
#2      _ScriptLocation.line (package:vm_service_client/src/script.dart:295:5)
#3      _getCoverageJson (package:coverage/src/collect.dart:103:46)
<asynchronous suspension>
#4      _getAllCoverage (package:coverage/src/collect.dart:51:26)
<asynchronous suspension>
#5      collect (package:coverage/src/collect.dart:35:18)
<asynchronous suspension>
#6      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55:45)
<asynchronous suspension>
#7      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
<asynchronous suspension>
#8      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:650:30)
<asynchronous suspension>
#9      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:408:36)
#10     PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
<asynchronous suspension>
#11     Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:248:36)
<asynchronous suspension>
#12     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:92:31)
<asynchronous suspension>
#13     invoke (package:test/src/utils.dart:241:5)
#14     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:91:7)
#15     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:404:25)
<asynchronous suspension>
#16     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#19     _rootRun (dart:async/zone.dart:1120:38)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#29     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#30     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


00:16 +14 -1: loading /Users/dnfield/src/flutter_svg/test/xml_svg_test.dart [E]
  Bad state: Couldn't find line and column for token 2529 in file:///b/build/slave/Linux_Engine/build/src/third_party/dart/sdk/lib/collection/list.dart.
  package:vm_service_client/src/script.dart 243:5               VMScript._lineAndColumn
  package:vm_service_client/src/script.dart 314:26              _ScriptLocation._ensureLineAndColumn
  package:vm_service_client/src/script.dart 295:5               _ScriptLocation.line
  package:coverage/src/collect.dart 103:46                      _getCoverageJson
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                             _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18                  _AsyncAwaitCompleter.completeError
  package:coverage/src/collect.dart                             _getCoverageJson
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getCoverageJson
  package:coverage/src/collect.dart 51:26                       _getAllCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             _getAllCoverage
  package:coverage/src/collect.dart 35:18                       collect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:coverage/src/collect.dart                             collect
  package:flutter_tools/src/test/coverage_collector.dart 55:45  CoverageCollector.collectCoverage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          _FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 408:36   _FlutterPlatform.loadChannel
  package:test/src/runner/plugin/platform.dart 65:19            PlatformPlugin.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23                  _asyncThenWrapperHelper
  package:test/src/runner/loader.dart                           Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 92:31                 new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test/src/backend/invoker.dart 403:15                  Invoker._onRun.<fn>.<fn>.<fn>
```

It eventually causes the process to hang and CI to timeout.  It's reproducing locally as well.  Upstream dart issue?

**Comment by dnfield** [comment]
Duplicate of https://github.com/flutter/flutter/issues/22497
