### ISSUE TITLE
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1)

### ISSUE THREAD

**Issue by sngvahmed** [flutter/flutter#22787]
## Steps to Reproduce

1. I run the flutter run -d all
2. the app work successfully 
3. then i run flutter upgrade
4. the flutter make upgrade then it fails with log beside 

## Logs
```
String: Exit code 1 from: /usr/bin/xcrun simctl install A9A84575-4DBC-4E8B-889E-BD19046E342C /opt/self/orangechat/build/ios/iphonesimulator/Runner.app:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/sngv/Library/Developer/CoreSimulator/Devices/A9A84575-4DBC-4E8B-889E-BD19046E342C/data/Library/Caches/com.apple.mobile.installd.staging/temp.tGi4YA/extracted/Payload/Runner.app
Failed to load Info.plist from bundle at path /Users/sngv/Library/Developer/CoreSimulator/Devices/A9A84575-4DBC-4E8B-889E-BD19046E342C/data/Library/Caches/com.apple.mobile.installd.staging/temp.tGi4YA/extracted/Payload/Runner.app
Underlying error (domain=MIInstallerErrorDomain, code=35):
	Failed to load Info.plist from bundle at path /Users/sngv/Library/Developer/CoreSimulator/Devices/A9A84575-4DBC-4E8B-889E-BD19046E342C/data/Library/Caches/com.apple.mobile.installd.staging/temp.tGi4YA/extracted/Payload/Runner.app

#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:123:12)
#2      IOSSimulator._buildAndInstallApplicationBundle (package:flutter_tools/src/ios/simulators.dart:384:31)
<asynchronous suspension>
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:353:14)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:283:15)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:281:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#16     getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._complete (dart:async/future_impl.dart:476:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#27     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#34     Future._complete (dart:async/future_impl.dart:476:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#37     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#38     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#45     Future._complete (dart:async/future_impl.dart:476:7)
#46     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#52     Future._complete (dart:async/future_impl.dart:476:7)
#53     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#54     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.9.7-pre.61, on Mac OS X 10.13.6 17G65, locale en-EG)
    • Flutter version 0.9.7-pre.61 at /opt/APP/flutter
    • Framework revision 2d81adf74c (34 hours ago), 2018-10-05 22:29:37 -0700
    • Engine revision 572fa5646a
    • Dart version 2.1.0-dev.6.0.flutter-c6254163dc

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/sngv/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone XS Max             • A9A84575-4DBC-4E8B-889E-BD19046E342C • ios         • iOS 12.0 (simulator)

• No issues found!
```

```
Analyzing orangechat...

   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/app.bar.dart:5:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/chat.dart:54:48 • non_constant_identifier_names
   info • The value of the local variable '_result' isn't used • lib/chat.dart:72:15 • unused_local_variable
   info • Unused import: 'package:orangechat/main.dart' • test/widget_test.dart:10:8 • unused_import
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' • test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' • test/widget_test.dart:15:33 • undefined_class

6 issues found. (ran in 10.2s)
```

**Comment by zoechi** [comment]
Is there a reason you added the `flutter doctor -v` output twice?
Can you reproduce with a new project?

**Comment by beardo01** [comment]
Also having the same issue when trying to build the app if it is already on the phone. If I `flutter clean` and then run again, it works, but will fail the second time.

Let me know what information you'd like.

**Comment by sngvahmed** [comment]
@zoechi 
when I pull flutter version and make a new project it's work
Thanks

**Comment by zoechi** [comment]
Perhaps one the answers in https://stackoverflow.com/questions/40327935/failed-to-load-info-plist-from-bundle helps

**Comment by neiljaywarner** [comment]
@zoechi  this is also affecting my colleague for "first-hour" when following flutter.io getting started instructions.

**Comment by neiljaywarner** [comment]
@zoechi our issue was with the oneliner hello-world . example and/or commandline first-hour.

When i used intellij and file-new-project he was able to run.  So he's not blocked.  thanks...

**Comment by zoechi** [comment]
I just run into the same error

I tried a few things. This is my output.
Afterwards I could start the app.
Not sure this is of any help.

```
 (master) $ flutter build ios --no-codesign --simulator --debug
Building com.example.flutter0Generic for simulator (ios)...
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    7.9s                                                                                                                                          
 └─Compiling, linking and signing...                  1.8s                                                                                                                                          
Xcode build done.                                           12.2s
Built /Users/myuser/flutter_playground/flutter_0_generic/build/ios/iphonesimulator/Runner.app.                                                                                             3.2s
myuser@mac ~/flutter_playground/flutter_0_generic
 (master) $ flutter devices
2 connected devices:

Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
iPhone XR                 • 787FAF06-6F62-43F7-926C-A0C10DCA1E66 • ios         • iOS 12.1 (simulator)
myuser@mac ~/flutter_playground/flutter_0_generic
 (master) $ flutter run -d 787FAF06-6F62-43F7-926C-A0C10DCA1E66
Launching lib/main.dart on iPhone XR in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    2.0s                                                                                                                                          
 └─Compiling, linking and signing...                  2.1s                                                                                                                                          
Xcode build done.                                            5.8s                                                                                                                               3.4s

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 336d91f60da438ff)
Crash report written to /Users/myuser/flutter_playground/flutter_0_generic/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```
```
 (master) $ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Downloading dependencies
Installing Flutter (1.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```
```
 (master) $ flutter build ios --release --no-codesign
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.flutter0Generic for device (ios-release)...
Starting Xcode build...                                          
 ├─Building Dart code...                             24.1s                                                                                                                                                                                                                
 ├─Generating dSYM file...                            1.0s                                                                                                                                                                                                                
 ├─Stripping debug symbols...                         1.0s                                                                                                                                                                                                                
 ├─Assembling Flutter resources...                    1.3s                                                                                                                                                                                                                
 └─Compiling, linking and signing...                  9.5s                                                                                                                                                                                                                
Xcode build done.                                           40.0s
Built /Users/myuser/flutter_playground/flutter_0_generic/build/ios/iphoneos/Runner.app.   
```
```
 (master) $ flutter run -d 787FAF06-6F62-43F7-926C-A0C10DCA1E66 --debug
Launching lib/main.dart on iPhone XR in debug mode...
log: Must be admin to run 'stream' command
Script started, output file is /dev/null

Script done, output file is /dev/null
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    2.2s                                                                                                                                                                                                                
 └─Compiling, linking and signing...                  3.1s                                                                                                                                                                                                                
Xcode build done.                                            7.2s         
```

**Comment by nilobarp** [comment]
It happened to me when I deleted the `Main.storyboard`. Had to restore it for the app to work again.

**Comment by hendricgc** [comment]
Up. Also happening here. First install runs correctly but when you delete the application and run `flutter run` again this crash pops.

**Comment by matejthetree** [comment]
same thing happened to me. I was editing plist, but xcode shows no error

**Comment by caiovncius** [comment]
In emulator > Hardware > Erase all Content and Settings, worked for me.

**Comment by normancarcamo** [comment]
> Also having the same issue when trying to build the app if it is already on the phone. If I `flutter clean` and then run again, it works, but will fail the second time.
> 
> Let me know what information you'd like.

This worked for me (oct 14, 2019).

**Comment by jmagman** [comment]
This was an Xcode simulator crash.  If anyone is hitting this on the newest version of Xcode, please comment and we'll reopen and investigate!

**Comment by 1pavanb** [comment]
Alright I've got it fixed for me

Preface:
I was preparing my storyboard and thought Main.storyboard was useless(I still think it is)
because I was not using it, I had created another storyboard

Then I had to put the Main storyboard because the app runs fine but xcode fails the upload for distribution and asks to put it back

Here's when I got the Exception:
I copied the content of my storyboard into the Main.storyboard
Exception:

> Could not parse callback cache, aborting restore

I copied the Main.storyboard (old) back into the Runner folder and the issue's fixed

Main.storyboard
```<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="10117" systemVersion="15F34" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" initialViewController="BYZ-38-t0r">
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="10085"/>
    </dependencies>
    <scenes>
        <!--Flutter View Controller-->
        <scene sceneID="tne-QT-ifu">
            <objects>
                <viewController id="BYZ-38-t0r" customClass="FlutterViewController" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="y3c-jy-aDJ"/>
                        <viewControllerLayoutGuide type="bottom" id="wfy-db-euE"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="8bC-Xf-vdC">
                        <rect key="frame" x="0.0" y="0.0" width="600" height="600"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <color key="backgroundColor" white="1" alpha="1" colorSpace="custom" customColorSpace="calibratedWhite"/>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="dkx-z0-nzr" sceneMemberID="firstResponder"/>
            </objects>
        </scene>
    </scenes>
</document>```

fyi i'm developing on flutter
