### ISSUE TITLE
Regression: Compilation fails without clear error description if the project contains "part" declarations with absolute path

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22785]
I'm using the latest master build. The issue started when I upgraded the master build from 3 or 4 days ago.

Compilation of my project failed with the following error:

```
Initializing gradle...                                       0,6s
Resolving dependencies...                                    1,8s
Gradle task 'assembleRelease'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
U
nhandled exception:
Unsupported operation: C
annot extract a file path from a package URI
#0      _Uri.toFilePath (dart:core/uri.dart:2617:7)
#1      _writeDepfile (package:vm/frontend_server.dart:662:32)
<asynchronous suspension>
#2      FrontendCompiler.compile (package:vm/frontend_server.dart:367:15)
<asynchronous suspension>
#3      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#4      starter (package:frontend_server/server.dart:133:27)
<asynchronous suspension>
#5      main (file:///E:/b/build/slave/Windows_Engine/build/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Compiler terminated unexpectedly.
Gradle task 'assembleRelease'... Done                       28,6s
Gradle task assembleRelease failed with exit code 1
```

It took me a few hours to find out what causes the issue, and how to fix it: 

In one source file of my app, I had a statement like this:
```
part 'package:some_app/chat/data/chat_background_jobs.g.dart';
```

Using a relative path to the part compiles without errors:
```
part 'chat_background_jobs.g.dart';
```

**Comment by daimionsg** [comment]
I had the exact issue as you.. following your advice, I went through my External Libraries > Dart Packages and found the same thing in the permission_handler.dart file. Changing it has taken the error away.

Thanks!

**Comment by rupert2133** [comment]
@daimionsg Can you elaborate on how did you fix the error? I had the same error.

**Comment by rupert2133** [comment]
@daimionsg Thanks! It's working now. I hope flutter team will make update on this.

**Comment by zoechi** [comment]
Merging with #22785

**Comment by sir-boformer** [comment]
@zoechi Merging with what? You linked this issue.

**Comment by zoechi** [comment]
Thanks! fixed.
