### ISSUE TITLE
On Android 4.4, when playing video using system player, the app will be crashed.

### ISSUE THREAD

**Issue by hschenzhimin** [flutter/flutter#22793]
The flutter version is 0.8.2.
```
D/WriteLogs(20435): registry: io.flutter.view.FlutterView{4175a910 VFE..... .F...... 0,0-1280,720}
I/dalvikvm(20435): Could not find method android.graphics.SurfaceTexture.setOnFrameAvailableListener, referenced from method io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>
W/dalvikvm(20435): VFY: unable to resolve virtual method 907: Landroid/graphics/SurfaceTexture;.setOnFrameAvailableListener (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
D/dalvikvm(20435): VFY: replacing opcode 0x6e at 0x0015
E/flutter (20435): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
E/flutter (20435): 	at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:969)
E/flutter (20435): 	at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:955)
E/flutter (20435): 	at com.wondertek.mishitong.ott.plugins.PlayerPlugin.create(PlayerPlugin.java:101)
E/flutter (20435): 	at com.wondertek.mishitong.ott.plugins.PlayerPlugin.onMethodCall(PlayerPlugin.java:69)
E/flutter (20435): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/flutter (20435): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/flutter (20435): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20435): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (20435): 	at android.os.Looper.loop(Looper.java:123)
E/flutter (20435): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
E/flutter (20435): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (20435): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (20435): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/flutter (20435): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
E/flutter (20435): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter (20435): 
F/flutter (20435): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (20435): Fatal signal 6 (SIGABRT) at 0x00004fd3 (code=-6), thread 20435 (v.mishitong.ott)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/MGV2000-UA/MGV2000-UA:4.4.2/KOT49H/31.2.021:user/test-keys'
```

**Comment by liyuqian** [comment]
Thanks for the report! Do you have a small piece of sample code to reproduce the problem? That would greatly help us diagnose the issue.

**Comment by hschenzhimin** [comment]
> Thanks for the report! Do you have a small piece of sample code to reproduce the problem? That would greatly help us diagnose the issue.

Thanks.The crash code is 
SurfaceTextureEntry handle = registry.createSurfaceTexture();

**Comment by liyuqian** [comment]
@hschenzhimin Do you have a more complete sample code (for example, the whole `lib/main.dart`, as shown in https://github.com/flutter/flutter/issues/22777)?

**Comment by liyuqian** [comment]
@amirh : are you familiar with this?

**Comment by najeira** [comment]
same as #22549

**Comment by zoechi** [comment]
Merging with #21730

**Comment by hschenzhimin** [comment]
> Merging with #21730
So how to solve the problem?Should I use the version of sdk older than 0.8.2?
