### ISSUE TITLE
flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by Akinayodeji** [flutter/flutter#22805]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor  or flutter doctor --android-licenses

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\flutter\bin\cache\lockfile' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
    • Flutter version 0.8.2 at C:\Users\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at C:\Users\AYODEJI\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-23, build-tools 23.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 1.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at C:\Users\AYODEJI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Sounds like you were running a `flutter` command using elevated privileges that wasn't able to clear the lock.
Try deleting the file `C:\Users\flutter\bin\cache\lockfile` manually.
Also check that the current user has write permissions in `C:\Users\flutter`

**Comment by Akinayodeji** [comment]
It worked.. thanks zoechi
