### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by bytecrew** [flutter/flutter#22807]
Running through a tutorial on flutter I caught this exception....

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp(dirty, state: _State#f6065):
flutter: type 'List<dynamic>' is not a subtype of type 'List<Widget>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _State.makeRadios (file:///Volumes/Data/dev/apps/input3/lib/main.dart:29:42)
flutter: #1      _State.build (file:///Volumes/Data/dev/apps/input3/lib/main.dart:45:15)
flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #12     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #13     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 414 libraries in 584ms.
```

The code that this is the call to makeRadios() call in the build function.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  _State createState() => new _State();
}

class _State extends State<MyApp> {

  int _value1 = 0;
  int _value2 = 0;

  void _setValue1(int value) => setState(() => _value1 = value);
  void _setValue2(int value) => setState(() => _value2 = value);

  Widget makeRadios() {
    List list = new List();

//    for(int i =0; i < 3; i++) {
//      list.add(new Radio(value: i, groupValue: _value1, onChanged: _setValue1));
//    }

    Column column = new Column(children: list,);

    return column;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Name Here'),
      ),
      body: new Container(
        padding: new EdgeInsets.all(32.0),
        child: new Center(
          child: new Column(
            children: <Widget>[
              makeRadios(),
            ],
          ),
        )
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Change
```dart
List list = new List();
```
to
```dart
List<Widget> list = [];
```
or
```dart
var list = <Widget>[];
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by bytecrew** [comment]
Thanks for the help, I pasted and posted to the place the link in the code asked me to! 😊


________________________________

**Comment by zoechi** [comment]
I see. I think there are plans to improve recognition if the issue is caused by framework code or custom code.

**Comment by bytecrew** [comment]
That would probably save you guys a bit of time answering noob questions 😊
