### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by akash1223** [flutter/flutter#22846]
## exception

String: Exit code 127 from: /Volumes/Work/Flutter Development Data/Flutter Project/footware/android/gradlew -v:
env: bash\r: No such file or directory

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:181:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:270:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:261:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.8.2 at /Volumes/Work/Flutter Development Data/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/akashjagtap/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (3 available)
    • SM G930T                  • c94536d1                             • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 8.1.0 (API 27) (emulator)
    • iPhone XS Max             • 970BF107-AADF-4648-BBC4-B15911C18360 • ios           • iOS 12.0 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Can you please elaborate on what steps to take to reproduce?
What command produced this output?
Did this work before (previous Flutter version)?
Did this work on another project?

**Comment by venkateshatr** [comment]
Just installed flutter on my Mac machine (unzip the flutter 1.0.0 stable version to a folder and added that folder to the $PATH) and issued the command `flutter doctor` which threw the error - `env: bash: No such file or directory`. Please help out here to resolve this issue.

Looks like it is not able to identify the bash command.

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory
indicates that this is an issue with line endings. 
Are you sure you downloaded the MacOS zip file?

**Comment by zoechi** [comment]
Could also be Git config https://stackoverflow.com/questions/22301956/error-with-gradlew-usr-bin-env-bash-no-such-file-or-directory/22301957

**Comment by RonelYin** [comment]
I downloaded "flutter_windows_v1.0.0-stable.zip". After setting PATH, I came across the same issue when I ran `flutter`.I have tried `:set fileformat=unix` in vim, but it seemed not work

**Comment by taojigu** [comment]
restarting  mac maybe help.

**Comment by RonelYin** [comment]
Make sure using `flutter_macos_v1.0.0-stable.zip` instead of `flutter_windows_v1.0.0-stable.zip` on mac. I made such a very stupid mistake!!

**Comment by zoechi** [comment]
Related #17554

**Comment by robinjohn** [comment]
Try the below and that should fix it:  

1. Clean build
``` 
flutter clean
```
2. Make the gradlew bin runnable in unix.
```
vim gradlew
:set fileformat=unix
:wq
```
3. Fix the flutter pub packages cache built from earlier session in windows
```
flutter pub cache repair
```
