### ISSUE TITLE
Crash report on Android by NoSuchMethodError

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#22850]
## Steps to Reproduce

With `video_player` and Android API level 20 below.

## Logs

```
10-08 20:02:09.001: W/dalvikvm(30997): VFY: unable to resolve virtual method 336: Landroid/graphics/SurfaceTexture;.setOnFrameAvailableListener (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
10-08 20:02:09.011: E/flutter(30997): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
10-08 20:02:09.011: E/flutter(30997): 	at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:969)
10-08 20:02:09.011: E/flutter(30997): 	at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:955)
10-08 20:02:09.011: E/flutter(30997): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:394)
10-08 20:02:09.011: E/flutter(30997): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
10-08 20:02:09.011: E/flutter(30997): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
10-08 20:02:09.011: E/flutter(30997): 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-08 20:02:09.011: E/flutter(30997): 	at android.os.MessageQueue.next(MessageQueue.java:138)
10-08 20:02:09.011: E/flutter(30997): 	at android.os.Looper.loop(Looper.java:134)
10-08 20:02:09.011: E/flutter(30997): 	at android.app.ActivityThread.main(ActivityThread.java:5633)
10-08 20:02:09.011: E/flutter(30997): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-08 20:02:09.011: E/flutter(30997): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-08 20:02:09.011: E/flutter(30997): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
10-08 20:02:09.011: E/flutter(30997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
10-08 20:02:09.011: E/flutter(30997): 	at dalvik.system.NativeStart.main(Native Method)
```

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ja-JP)
    • Flutter version 0.8.2 at /Applications/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0
```

**Comment by najeira** [comment]
https://developer.android.com/reference/android/graphics/SurfaceTexture.html#setOnFrameAvailableListener(android.graphics.SurfaceTexture.OnFrameAvailableListener,%20android.os.Handler)

is added in API level 21.

**Comment by najeira** [comment]
same as #22549

**Comment by zoechi** [comment]
Merging with #21730
