### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by andytwoods** [flutter/flutter#22855]
Hi,
afraid I'm a flutter newbie. I was asked to report this bug.
I'll report back if I crack it.
Many thanks,
Andy.

```
Performing hot reload...
Syncing files to device Android SDK built for x86 64...
I/flutter (25832): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25832): The following assertion was thrown building SlideTransition(animation: AnimationController#859ac(⏭
I/flutter (25832): 1.000; paused; for MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20,
I/flutter (25832): 1.00)➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
I/flutter (25832): _AnimatedState#7c1f8):
I/flutter (25832): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4659 pos 12: 'child == _child':
I/flutter (25832): is not true.
I/flutter (25832): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25832): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25832): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25832):   https://github.com/flutter/flutter/issues/new
I/flutter (25832): When the exception was thrown, this was the stack:
I/flutter (25832): #2      SingleChildRenderObjectElement.forgetChild (package:flutter/src/widgets/framework.dart:4659:12)
I/flutter (25832): #3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:2880:14)
I/flutter (25832): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:32)
I/flutter (25832): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (25832): #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (25832): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (25832): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (25832): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (25832): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (25832): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (25832): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
I/flutter (25832): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter (25832): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter (25832): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (25832): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (25832): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (25832): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (25832): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (25832): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (25832): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (25832): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (25832): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (25832): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #47     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (25832): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (25832): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (25832): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (25832): #51     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (25832): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (25832): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (25832): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25832): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25832): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (25832): #58     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (25832): #59     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (25832): #60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (25832): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (25832): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25832): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1503 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter (25832): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#431cb NEEDS-PAINT DETACHED
I/flutter (25832): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#f7a72 NEEDS-PAINT DETACHED
I/flutter (25832): Another exception was thrown: RenderBox was not laid out: RenderOffstage#5fdd2 NEEDS-PAINT
I/flutter (25832): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#431cb NEEDS-PAINT DETACHED
I/flutter (25832): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
Reloaded 3 of 474 libraries in 433ms.
```

**Comment by andytwoods** [comment]
Hi,
straightforward issue. See below new "Text(snapshot.data[index].description". 'description' did not exist in my class.
Cheers,
Andy.

`
class MyItemListPageState extends State<MyItemList> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Stuff List'),
          actions: <Widget>[
            new IconButton(
              icon: const Icon(Icons.add),
              tooltip: 'New',
              onPressed: () {
                navigateToItemModify();
              },
            ),
            new IconButton(
              icon: const Icon(Icons.sort),
              tooltip: 'Sort',
              onPressed: () {
                navigateToItemModify();
              },
            ),
          ]

      ),
      body: new Container(
        padding: new EdgeInsets.all(16.0),
        child: new FutureBuilder<List<Item>>(
          future: fetchEmployeesFromDatabase(),
          builder: (context, snapshot) {
            if (snapshot.hasData) {
              return new ListView.builder(
                  itemCount: snapshot.data.length,
                  itemBuilder: (context, index) {
                    return new Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          new Text(snapshot.data[index].**description**,
                              style: new TextStyle(
                                  fontWeight: FontWeight.bold, fontSize: 18.0)),
                          new Text(snapshot.data[index].**description**,
                              style: new TextStyle(
                                  fontWeight: FontWeight.bold, fontSize: 14.0)),
                          new Divider()
                        ]);
                  });
            } else if (snapshot.hasError) {
              return new Text("${snapshot.error}");
            }
            return new Container(alignment: AlignmentDirectional.center,child: new CircularProgressIndicator(),);
          },
        ),
      ),
    );
  }

  void navigateToItemModify([int id]){
    Navigator.push(
      context,
      new MaterialPageRoute(builder: (context) => new MyItemModify(id: id)),
    );
  }
}`

**Comment by zoechi** [comment]
Are you sure the error and the code change are related?

Does this mean your problem is solved?

**Comment by andytwoods** [comment]
My problem is solved. I'd be surprised if there was another reason for this error arising.

**Comment by zoechi** [comment]
If `description` was a reference to a non-existing property, the application shouldn't have been able to compile at all.

Perhaps a previous build was run or something like that.
Thanks for reporting, but I'm afraid with the available information there is no way to diagnose the problem.
