### ISSUE TITLE
Always getting error while running Flutter command.

### ISSUE THREAD

**Issue by Avnish4** [flutter/flutter#22920]
Hello Everyone. I am new on flutter and i am trying to setup flutter on my system i have downloaded flutter sdk and installed it but now when i am running any flutter command it gives error.

> oops; flutter has exited unexpectedly.
> Sending crash report to Google.
> Crash report sent (report ID: 7102753a4134c0d8)
> Crash report written to D:\Work\Current_Live_Apps\Flutter_Apps\spends\flutter_01.log;
> please let us know at https://github.com/flutter/flutter/issues.

Please check this log.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\Avnish\AppData\Local\Android\sdk\platform-tools\adb.

> ```
> #0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
> #1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
> #2      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:324:48)
> #3      runSync (package:flutter_tools/src/base/process.dart:298:10)
> #4      getAdbDevices (package:flutter_tools/src/android/android_device.dart:536:23)
> #5      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:54:53)
> <asynchronous suspension>
> #6      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:163:56)
> <asynchronous suspension>
> #7      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91:46)
> <asynchronous suspension>
> #8      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:647:54)
> <asynchronous suspension>
> #9      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:56)
> #10     Doctor.diagnose (package:flutter_tools/src/doctor.dart:183:42)
> #11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
> #12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:173:24)
> #13     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
> #14     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
> #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
> #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
> #17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #18     _rootRunUnary (dart:async/zone.dart:1132:38)
> #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #23     Future._complete (dart:async/future_impl.dart:476:7)
> #24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #25     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
> #26     _rootRun (dart:async/zone.dart:1124:13)
> #27     _CustomZone.run (dart:async/zone.dart:1021:19)
> #28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
> #32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
> ```
> 

Any help would be appreciable . Thanks in Advance!

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

> ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\Avnish\AppData\Local\Android\sdk\platform-tools\adb.

Is this the exact and full error message? There seems to be a `bat` or `exe` missing at the end.

**Comment by zoechi** [comment]
Does the file exist with this path?
