### ISSUE TITLE
Unclear error in SpriteWidget.  It's not clear what's null.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2292]
I tried looking at the code but that particular call to drawVertices has many arguments.

```dart
I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
I/flutter : The following exception was raised during paint():
I/flutter : The null object does not have a getter 'isNotEmpty'.
I/flutter : NoSuchMethodError: method not found: 'isNotEmpty'
I/flutter : Receiver: null
I/flutter : Arguments: []
I/flutter : The following RenderObject was being processed when the exception was fired:
I/flutter : SpriteBox relayoutSubtreeRoot=up6
I/flutter : This RenderObject had the following owner:
I/flutter : SpriteWidget ← SketchWidget-[GlobalKey 694865178] ← Stack ← DecoratedBox ← ConstrainedBox ← Container ← SizeObserver ← SizeObserver ← OverflowBox ← ConstrainedBox ← ⋯
I/flutter : This RenderObject has no descendants.
I/flutter : Stack trace:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/flutter : #2      Canvas.drawVertices (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/painting.dart:277)
I/flutter : #3      TexturedLinePainter.paint (packages/flutter_sprites/src/textured_line.dart:172)
I/flutter : #4      EffectLine.paint (packages/flutter_sprites/src/effect_line.dart:166)
I/flutter : #5      Node._visitChildren (packages/flutter_sprites/src/node.dart:710)
I/flutter : #6      Node._visit (packages/flutter_sprites/src/node.dart:664)
I/flutter : #7      Node._visitChildren (packages/flutter_sprites/src/node.dart:715)
I/flutter : #8      Node._visit (packages/flutter_sprites/src/node.dart:664)
I/flutter : #9      SpriteBox.paint (packages/flutter_sprites/src/sprite_box.dart:345)
```

**Comment by Hixie** [comment]
cc @vlidholt

**Comment by abarth** [comment]
What's happening is that the textureCoordinates argument is null, which causes the exception.  We should probably treat null as the same as an empty list in the engine.

**Comment by Hixie** [comment]
Obsolete, we've removed flutter_sprites for now.
