### ISSUE TITLE
Java error from gradlew.bat after upgrading to flutter v0.9.4

### ISSUE THREAD

**Issue by chadidi** [flutter/flutter#22942]
## Steps to Reproduce

1. Upgrade to the latest v0.9.4
2. try to run your application

## Logs

```
$ flutter run --verbose
[  +84 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +116 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/beta
[        ] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[  +35 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92
[        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[  +51 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 weeks ago
[   +2 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.9.4-0-gf37c235c3
[ +308 ms] executing: C:\Users\chadi\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[  +39 ms] Exit code 0 from: C:\Users\chadi\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[        ] List of devices attached
           0123456789ABCDEF       device product:full_I9553_6625 model:PEARL_A7 device:I9553_6625 transport_id:1
[ +358 ms] Found plugin map_view at C:\src\flutter\.pub-cache\git\flutter_google_map_view-95a70d2827ca6120e41df72a90a45a4128c8fb02\
[ +132 ms] Found plugin map_view at C:\src\flutter\.pub-cache\git\flutter_google_map_view-95a70d2827ca6120e41df72a90a45a4128c8fb02\
[ +143 ms] C:\Users\chadi\AppData\Local\Android\Sdk\platform-tools\adb -s 0123456789ABCDEF shell getprop
[ +147 ms] ro.hardware = mt6755
[        ] ro.build.characteristics = default
[+1780 ms] Launching lib/main.dart on PEARL A7 in debug mode...
[  +51 ms] Initializing gradle...
[   +2 ms] Using gradle from C:\Users\chadi\Desktop\Flutter projects\flutter_map_demo\android\gradlew.bat.
[ +208 ms] executing: C:\Users\chadi\Desktop\Flutter projects\flutter_map_demo\android\gradlew.bat -v
[ +612 ms] java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
                        at org.gradle.internal.concurrent.CompositeStoppable.<clinit>(CompositeStoppable.java:37)                        at org.gradle.internal.classloader.ClassLoaderUtils.tryClose(ClassLoaderUtils.java:36)
                        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:64)
                        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
                        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
                        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.lang.reflect.Method.invoke(Method.java:498)
                        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
                        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
                        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
                   Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
                        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                        ... 12 more
[  +30 ms] "flutter run" took 3,607ms.

Oops; flutter has exited unexpectedly: "Exit code 1 from: C:\Users\chadi\Desktop\Flutter projects\flutter_map_demo\android\gradlew.bat -v:
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.gradle.internal.concurrent.CompositeStoppable.<clinit>(CompositeStoppable.java:37)
        at org.gradle.internal.classloader.ClassLoaderUtils.tryClose(ClassLoaderUtils.java:36)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:64)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more".
Sending crash report to Google.
Crash report sent (report ID: 57ff807364461f6e)
Crash report written to C:\Users\chadi\Desktop\Flutter projects\flutter_map_demo\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
$ flutter analyze
Analyzing flutter_map_demo...
No issues found! (ran in 2.1s)
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17763.55], locale en-US)
    • Flutter version 0.9.4 at C:\src\flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\chadi\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Users\chadi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.28.0)
    • VS Code at C:\Users\chadi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • PEARL A7 • 0123456789ABCDEF • android-arm64 • Android 6.0 (API 23)

• No issues found!
```

**Comment by chadidi** [comment]
@zoechi I was testing this app https://github.com/matthewtsmith/flutter_map_demo when this error happened and I think the problem from their files cause when I created a new project and used the same lib files it worked!!
