### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by geirknut** [flutter/flutter#22949]
I/flutter (10539): The following assertion was thrown building Bilkontroll(dirty, state: _BilkontrollState#05b28):
I/flutter (10539): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 490 pos 15: 'value == null ||
I/flutter (10539): items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.
I/flutter (10539): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10539): more information in this error message to help you determine and fix the underlying cause.
When the exception was thrown, this was the stack:
I/flutter (10539): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:490:15)
I/flutter (10539): #3      _BilkontrollState.build (package:esp/bilkontroll.dart:60:23)
I/flutter (10539): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (10539): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (10539): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (10539): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (10539): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter (10539): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (10539): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10539): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (10539): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (10539): #13     _invoke (dart:ui/hooks.dart:139:13)
I/flutter (10539): #14     _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter (10539): (elided 2 frames from class _AssertionError)
I/flutter (10539): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by geirknut** [comment]
Caused
