### ISSUE TITLE
"Bad state: No element" error caused by palette_generator's empty response

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#22952]
## Steps to Reproduce

1. I created a Stateful Widget.
2. I inserted the following code which is from palette_generator's example into the widget in order to get the color palette of an image:
```dart
Future<void> _updatePaletteGenerator(Rect newRegion) async {
    paletteGenerator = await PaletteGenerator.fromImageProvider(
      widget.image,
      size: widget.imageSize,
      region: newRegion,
      maximumColorCount: 20,
    );
    setState(() {});
}
```
3. I called the code inside initState().
4. I used Iterable ```paletteGenerator.colors.first``` to change the background color of a widget.
5. I tested it on iOS Simulator and it smoothly worked.
6. It hardly worked on Android. I had to do hot restart to run it again. It never worked in the second time without hot restart and I got an error when I navigated to different screens and came back to the same screen.

What I see is that it works only in the beginning on Android Simulator whilst iOS Simulator is fine. However, `PaletteGenerator.fromImageProvider()` returns null for the raw image when I try to call it after rerender the widget. So, the rest of the process can't work properly due to the null parameter. As a result, I always receive an empty list for the second try. Something like this: `PaletteGenerator#b6f11(paletteColors: [], targets: null)`

## Logs

```
I/flutter (13109): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13109): The following StateError was thrown building HomeScreen(dirty, state: _HomeScreenState#e3fe0):
I/flutter (13109): Bad state: No element
I/flutter (13109):
I/flutter (13109): When the exception was thrown, this was the stack:
I/flutter (13109): #0      Iterable.first (dart:core/iterable.dart:518:7)
I/flutter (13109): #1      _HomeScreenState.build (package:test/screens/home_screen.dart:76:41)
I/flutter (13109): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (13109): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (13109): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (13109): #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (13109): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
I/flutter (13109): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13109): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13109): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13109): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13109): #11     _invoke (dart:ui/hooks.dart:139:13)
I/flutter (13109): #12     _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter (13109): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
```
[✓] Flutter (Channel dev, v0.9.6, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.9.6 at /Users/test/Library/Android/flutter
    • Framework revision 13684e4f8e (9 days ago), 2018-10-02 14:15:17 -0400
    • Engine revision f6af1f20ba
    • Dart version 2.1.0-dev.6.0.flutter-8a919426f0

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/test/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
@gspencergoog

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by afnx** [comment]
I've added the output

**Comment by gspencergoog** [comment]
Is this on the Android emulator, or on a real device?

If it's on the emulator, can you try adding `--enable-software-rendering` to your `flutter run` command? There are known bugs in the hardware rendering on the emulators that may be causing this problem.

**Comment by afnx** [comment]
I tested on both different emulators and a real device.

It is working on Android emulators after adding `--enable-software-rendering` to the command. As you said, the problem could be the emulator itself. However, it doesn't work on a real Android device either.

**Comment by hupptechnologies** [comment]
@gspencergoog 
Useing this command `flutter run --enable-software-rendering`  issue resolved. But app stauck , slow performance & sometime lost connection.

Here is some log before lost connections.
```
I/Choreographer( 2299): Skipped 51 frames!  The application may be doing too much work on its main thread.
D/        ( 2299): HostConnection::get() New Host Connection established 0xee992eb0, tid 2314
Syncing files to device Google Nexus 5, 6 0 0, API 23, 1080x1920...      
F/libc    ( 2299): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3 in tid 2320 (le.tabbarbottom)
Lost connection to device.
```

**Comment by gspencergoog** [comment]
@afnx, What kind of device are you using (make/model)?

It appears that this is exercising part of the graphics stack that isn't properly implemented in the emulators, but I'm wondering why it still fails on a device.

**Comment by gspencergoog** [comment]
@hupptechnologies, was the "But app stuck , slow performance & sometime lost connection." comment for the emulator, or for a physical device? (your log snippet mentions "Nexus 5", so I'm not sure)

**Comment by afnx** [comment]
@gspencergoog, Samsung Galaxy S7 Edge - Android 8.0 Oreo.

I have a red error screen which says `Bad State: No Element`. It works anytime I clear the data of the app.

**Comment by afnx** [comment]
@gspencergoog, the palette generator works when I clear the data. It works for once and then the error appears for all next attempts. 

For example, I launch the app and it works for once. After that, I navigate to another screen or close the app. Henceforth, the error will always appear. If I clear the data of the app, it will work again for once and the same process will happen again and again.

**Comment by vidklopcic** [comment]
Same here. On the first run (Android - hot reload) works, but every subsequent run silently fails and returns empty palette.

**Comment by hupptechnologies** [comment]
@gspencergoog For simulator. Not tried in real device yet.

**Comment by gucchi43** [comment]
@

**Comment by gspencergoog** [comment]
Closing this, as it appears to not be reproducible, at least in the ways in which I tried to reproduce it.  If you still have problems with this, and have more information about the context in which it is used, that may help.

**Comment by agilob** [comment]
I can reproduce it using simple:
```
  List<PieChartSectionData> _showingSections(final List<Vote> snapshot) {
    print('length ${snapshot.length}');
    return List.generate(
      0,
      (i) {
        return _pieChartFromVote(snapshot[i]);
      },
    );
  }
```
When `snapshot.length` is `== 0` I get the following stacktrace:


```
Performing hot reload...                                               ⡿I/flutter (16258): length 0
⣟I/flutter (16258): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
⣯I/flutter (16258): The following StateError was thrown building StreamBuilder<List<Vote>>(dirty, state:
I/flutter (16258): _StreamBuilderBaseState<List<Vote>, AsyncSnapshot<List<XXXXX>>>#2532c):
I/flutter (16258): Bad state: No element
I/flutter (16258): 
I/flutter (16258): The relevant error-causing widget was:
I/flutter (16258):   StreamBuilder<List<Vote>> file:///home/agilob/xxxx/xxxx/lib/pages/xxxxx.dart:39:22
I/flutter (16258): 
I/flutter (16258): When the exception was thrown, this was the stack:
I/flutter (16258): #0      ListIterable.reduce (dart:_internal/iterable.dart:182:22)
I/flutter (16258): #1      new PieChartData (package:fl_chart/src/chart/pie_chart/pie_chart_data.dart:38:51)
I/flutter (16258): #2      _CreateTeamPageState._buildChartData (package:XXXXX/pages/create_team_page.dart:155:9)
I/flutter (16258): #3      _CreateTeamPageState.build.<anonymous closure> (package:XXXXX/pages/create_team_page.dart:44:26)
I/flutter (16258): #4      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (16258): #5      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (16258): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
I/flutter (16258): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter (16258): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (16258): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (16258): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #30     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #34     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #36     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (16258): #37     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (16258): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #69     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #73     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #85     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #89     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #93     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #97     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #101    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #103    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (16258): #104    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (16258): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #112    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #124    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #128    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #132    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #136    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #144    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #147    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #148    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #153    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #154    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #156    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #161    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #162    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #164    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #170    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #174    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #177    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #178    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #180    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #183    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #184    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #185    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (16258): #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #187    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #190    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #191    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (16258): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #194    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #195    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (16258): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #197    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (16258): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #201    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (16258): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (16258): #203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (16258): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (16258): #205    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (16258): #206    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (16258): #207    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (16258): #208    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (16258): #209    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (16258): #210    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
I/flutter (16258): #212    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (16258): #213    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (16258): #214    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (16258): (elided one frame from package dart:async-patch)
I/flutter (16258):
I/flutter (16258): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter info:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_GB.UTF-8)
```

I can reproduce it on 3 devices (not emulators):

3 connected devices:
```
A   • XXXXX           • android-arm   • Android 4.4.2 (API 19)
B • YYYYY         • android-arm   • Android 7.1.1 (API 25)
C     • 192.168.1.131:5555 • android-arm64 • Android 9 (API 28)
```

It always happens when list if empty, adding 1 element "fixes" the issue.

**Comment by agilob** [comment]
Channel `master` also affected `[✓] Flutter (Channel master, v1.15.4-pre.82, on Linux, locale en_GB.UTF-8)`

**Comment by mwawrusch** [comment]
If this is still an issue, I had something similar: .firstWhere( (z) => z.id == value.issuer.id, orElse: () => null)

was missing orElse in my code.

**Comment by afrozopsy** [comment]
If you are using a physical android device, then unplugging and plugging again the usb into cellphone fixed it for me.
