### ISSUE TITLE
Requested issue report: type <type> is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by thenewmr** [flutter/flutter#22955]
Reporting issue as instructed by error.

> Either the assertion indicates an error in the framework itself, or we should provide substantially
 more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

I do agree that more information should have been provided in order to fix the issue.

I shall try to summarise the issue to keep it concise.

- I was following the Udacity flutter course and following item 13 in lesson 1 
- Whilst looking at code as shown in video in item 12, I noticed this:
`color[50]`
I'm not familiar enough with dart or flutter to know why there was a number in square brackets after the color.  But I noticed that the numbers (50 and 100) were the _borderRadius and _rowHeight respectively.  So thought to use those values instead thinking (perhaps mistakenly) that these are what they referred to.

- This resulted in the error below
- By comparing my code to the solution code (which is not the same as the code in the video - which is fine I guess because I know things are changing fast), I was able to see this difference and figured out the issue.  But the error message or stack trace weren't very helpful.

```
Performing hot reload...
Syncing files to device SM G930F...
I/flutter (17857): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17857): The following assertion was thrown building Category(dirty):
I/flutter (17857): type 'BorderRadius' is not a subtype of type 'int' of 'index'
I/flutter (17857): 
I/flutter (17857): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17857): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17857): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17857):   https://github.com/flutter/flutter/issues/new
I/flutter (17857): 
I/flutter (17857): When the exception was thrown, this was the stack:
I/flutter (17857): #0      ColorSwatch.[] (package:flutter/src/painting/colors.dart)
I/flutter (17857): #1      Category.build (package:task_02_category_widget/category.dart:59:32)
I/flutter (17857): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3707:28)
I/flutter (17857): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
I/flutter (17857): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #5      StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (17857): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #17     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
I/flutter (17857): #18     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter (17857): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (17857): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #58     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #64     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (17857): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
Reloaded 2 of 409 libraries in 1,339ms.
I/flutter (17857): #80     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (17857): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #84     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #90     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
I/flutter (17857): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #100    StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
I/flutter (17857): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
I/flutter (17857): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #106    ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
I/flutter (17857): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (17857): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (17857): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (17857): #110    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (17857): #111    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (17857): #112    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (17857): #113    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17857): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17857): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17857): #117    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17857): #118    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17857): #119    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (17857): (elided one frame from package dart:async)
I/flutter (17857): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Sounds like an issue in your code.
We would need a minimal reproduction that allows us to reproduce.
