### ISSUE TITLE
ld: framework not found Flutter

### ISSUE THREAD

**Issue by DDDKid** [flutter/flutter#22997]
Use AS to create a new Flutter project, when I click run, error:
Ld: framework not found Flutter
<img width="742" alt="2018-10-12 2 24 37" src="https://user-images.githubusercontent.com/43944407/46853970-289f1100-ce32-11e8-91d9-702f319bed44.png">

**Comment by zoechi** [comment]
What output do you get for `flutter run` in a terminal window?

**Comment by alamyudi** [comment]
i'm also experiencing this, not sure why, but it's happen every time i `upgrade` and/or delete flutter command line app, because storage limitation. 

<img width="797" alt="screen shot 2018-10-13 at 10 43 39" src="https://user-images.githubusercontent.com/839045/46900956-ea0e6280-ced4-11e8-9aca-2f853cef2797.png">

to solved this, i switch the flutter channel, from `beta` to `master` then back to `beta` again 😄 .

**Comment by Machiuka** [comment]
> i'm also experiencing this, not sure why, but it's happen every time i `upgrade` and/or delete flutter command line app, because storage limitation.
> 
> <img alt="screen shot 2018-10-13 at 10 43 39" width="797" src="https://user-images.githubusercontent.com/839045/46900956-ea0e6280-ced4-11e8-9aca-2f853cef2797.png">
> 
> to solved this, i switch the flutter channel, from `beta` to `master` then back to `beta` again 😄 .

How do you do that? I have the same problem.

**Comment by masaya-dake** [comment]
have the same problem,too

**Comment by alamyudi** [comment]
@Machiuka type `flutter channel master` in terminal

**Comment by Machiuka** [comment]
It doesn't work. I solve the problem anyway by reinstalling flutter.

**Comment by SNXJ** [comment]
我原本使用stable也出现这个问题，切换到master问题消失，就可以在ios设备运行了

**Comment by Aprilday** [comment]
> 我原本使用stable也出现这个问题，切换到master问题消失，就可以在ios设备运行了
> 
> > (Google translate) I originally used this problem with the stable, the switch to the master problem disappeared, you can run on the ios device.

是的

**Comment by hyiso** [comment]
Also get this issue when integrating flutter to an existing iOS App according to this [wiki](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps ) at step **Under the hood**

**Comment by rainedAllNight** [comment]
I try to "flutter channel master"， but it does't work for me, Finally  I solve the problem  by reinstalling flutter

**Comment by rainedAllNight** [comment]
And the reason of the error is i upgrade and/or delete flutter command line app,  because storage limitation.

**Comment by suesitran** [comment]
"flutter channel master" does not work for me

**Comment by suesitran** [comment]
when i run "flutter build ios --release --verbose", i notice this error below

Encountered error while building for device.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:94:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by VB10** [comment]
ı have some problem @suesitran. I think switch flutter channel catch this problem.(i switch dev-stable).My little fix: new flutter project and go ios/flutter copy app.framework and paste the current project. Solved the problem.

**Comment by gkrawiec** [comment]
@VB10 
I've tried this, but none of my projects have an app.framework file anywhere. Not even newly created projects. Is this a single file? or are you referring to something else?
 
> ı have some problem @suesitran. I think switch flutter channel catch this problem.(i switch dev-stable).My little fix: new flutter project and go ios/flutter copy app.framework and paste the current project. Solved the problem.

**Comment by VB10** [comment]
@gkrawiec 
you don't have app.framework  at creating new project ios/flutter. Flutter build ios or flutter run emulator and you seeing app.framework file and copy your old project folder.(So dont remember if you don't see app.framework means: "have build error or packages error" try "flutter clean" and run again
It's run emulator complete reason look at ios/flutter folder and see app.framework file  )

**Comment by gkrawiec** [comment]
@VB10 Ok, now I understand what you meant. It did create the folder as you described.
 Unfortunately this did not solve my issue. I will see what else I can try. Thanks!

**Comment by hatjs880328s** [comment]
Solve it by reinstall....
Maybe u clean the cache file for XCode ,delete the framework- flutter.

**Comment by melvinm99** [comment]
I could solve it only creating a new flutter project and copying libs and assets  (reinstall didn't solve)

**Comment by amjadaliamjad** [comment]
flutter clean then From ios delete Pods folder and also Podfile and Podfile.lock then re run project. in my case it works

**Comment by vinothvino42** [comment]
I solved it by deleting the entire iOS Project directory and created it again with` flutter create . `command.
