### ISSUE TITLE
Timed out expection while running app

### ISSUE THREAD

**Issue by ChethanUC007** [flutter/flutter#23056]
## Steps to Reproduce

Timed out expectation while running Basic app

Error Log: 

```
flutter run
Launching lib/main.dart on ONE A2003 in debug mode...
Initializing gradle...                                       1.9s
Resolving dependencies...                                    9.3s
Gradle task 'assembleDebug'...
Exception in thread "queued-resource-processor_1" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at F:\sdk\build-tools\27.0.3\aapt2.exe can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
        at com.android.builder.png.AaptProcess.waitForReadyOrFail(AaptProcess.java:178)
        at com.android.builder.internal.aapt.AaptQueueThreadContext.creation(AaptQueueThreadContext.java:56)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:250)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "queued-resource-processor_2" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at F:\sdk\build-tools\27.0.3\aapt2.exe can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
        at com.android.builder.png.AaptProcess.waitForReadyOrFail(AaptProcess.java:178)
        at com.android.builder.internal.aapt.AaptQueueThreadContext.creation(AaptQueueThreadContext.java:56)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:250)
        at java.lang.Thread.run(Thread.java:745)
```

```
flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at F:\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at F:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:\sdk
    • Java binary at: F:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at F:\Android
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\evolu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • ONE A2003 • bbcfb248 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
Have you tried with another device or Android emulator?

**Comment by Empty2k12** [comment]
This is also happening to us in CI. No device there.

```
(cd app && flutter build apk --debug)
Initializing gradle...                                          23.6s
Resolving dependencies...                                       70.1s
Gradle task 'assembleDebug'...                                  
Exception in thread "queued-resource-processor_8" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at /android-sdk/build-tools/27.0.3/aapt2 can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
	at com.android.builder.png.AaptProcess.waitForReadyOrFail(AaptProcess.java:178)
	at com.android.builder.internal.aapt.AaptQueueThreadContext.creation(AaptQueueThreadContext.java:56)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:250)
	at java.lang.Thread.run(Thread.java:748)
```

Counts up until the build is manually aborted.

**Comment by Empty2k12** [comment]
@zoechi @Hixie This is surely a bug. I just provided the information you requested.

**Comment by zoechi** [comment]
The no-response bot went amok. 

Have you tried with disabled AntiVirus as the error suggests or perhaps restart the machine to ensure no other processes hold file references?

**Comment by Empty2k12** [comment]
Here's a general overview of our Container and installed dependencies:

## Versions
```
FLUTTER_VERSION     0.11.9-beta
ANDROID_BUILD_TOOLS 27.0.3
ANDROID_PLATFORM    27
ANDROID_SDK         3859397
```

## Dependencies
```
git
libglu1-mesa
lib32stdc++6
bash
apt-transport-https
lcov
ruby-full
rubygems
build-essential
aptitude
libstdc++6 dart
```
fastlane

## OS
[`openjdk:8`](https://hub.docker.com/_/openjdk/)

## Android SDK
```
platform-tools
build-tools;ANDROID_BUILD_TOOLS
platforms;android-ANDROID_PLATFORM
extras;android;m2repository
extras;google;m2repository
extras;google;google_play_services
```

**Comment by zoechi** [comment]
Have you tried setting `SLAVE_AAPT_TIMEOUT`?

**Comment by Empty2k12** [comment]
@zoechi Just got a PR merged with increased SLAVE_AAPT_TIMEOUT (set to 30). Will report back if crashes happen again.

This should still be considered a bug, as having a lower setting doesn't crash the build, but rather makes it run indefinitely.

**Comment by zoechi** [comment]
@Empty2k12 
Not sure if this is Flutter related. Perhaps it should be reported for Gradle instead.
https://stackoverflow.com/a/35373926/217408

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by markmuthii** [comment]
@Empty2k12 @zoechi I was facing a similar issue with the slave aapt process on windows while working with Cordova. I solved it by setting a system variable SLAVE_AAPT_TIMEOUT to 30. [Source](https://stackoverflow.com/a/35373926/11388821)
