### ISSUE TITLE
flutter build apk fail

### ISSUE THREAD

**Issue by xia-weiyang** [flutter/flutter#23050]
I build apk successfully on the windows system. but it`s failed on the ubuntu system.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release --target-platform android-arm --release

## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/xia/develop/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --await_is_keyword --causal_async_stacks --packages=.packages --url_mapping=dart:ui,/home/xia/develop/flutter/flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart --url_mapping=dart:vmservice_io,/home/xia/develop/flutter/flutter/bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --reify-generic-functions --strong --sync-async --snapshot_kind=app-aot-blobs --vm_snapshot_data=/home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/xia/develop/work/OldTime-App/oldtime/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:66:12)
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:55)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:137:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:109:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel beta, v0.9.4, on Linux, locale zh_CN.UTF-8)
    • Flutter version 0.9.4 at /home/xia/develop/flutter/flutter
    • Framework revision f37c235c32 (3 周前), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5
      

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/xia/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/xia/develop/tool/android-studio-ide-181.5014246-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.2)
    • Android Studio at /home/xia/develop/tool/android-studio-ide-181.5014246-linux/android-studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /home/xia/develop/tool/ideaIU-2018.2.4/idea-IU-182.4505.22
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by xia-weiyang** [comment]
Did not read the report of the 'flutter doctor' carefully.  see #6207
