### ISSUE TITLE
Cutting and pasting issues in text fields on iOS like #22624

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#23087]
If I use themeData platform is TargetPlatform.ios in MaterialApp on android device, then the pasteButtonLabel warning is showing like the issue.  Not warning on iOS device. but i18n not valid. 

----

like the code  [main.dart](https://github.com/CaiJingLong/localization_error_example/blob/e953b2958eb3933ac75b3d4996c7b50af33be5dd/lib/main.dart)

[github repo](https://github.com/CaiJingLong/localization_error_example)

and I tried to create a custom ChineseCupertinoLocalizations, but it didn't work.

[like this](https://github.com/CaiJingLong/localization_error_example/blob/93077ab35c0764ca4824791376a4019b35b3d97f/lib/chinese_localization.dart)
----
If I delete 
```
GlobalMaterialLocalizations.delegate,
GlobalWidgetsLocalizations.delegate,
```
then i18n not valid, and language is english, not chinese.

Everything was normal before the update in v0.9.1, and there was a problem after the 0.10.
-----
before upgrade  flutter version 0.9.1 ,anything is true

---

```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.10.0 at /Users/cai/fluttersdk/flutter
    • Framework revision d954ae6850 (5 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Android NDK at /Users/cai/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Users/cai/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (2 available)
    • MI 8       • b6ec3684                                 • android-arm64 • Android 8.1.0 (API 27)
    • iPad mini2 • 58366e2a63aae6f85e6e806039316c27faa52868 • ios           • iOS 12.0

```

_Originally posted by @CaiJingLong in https://github.com/flutter/flutter/issues/22624#issuecomment-429717417_

**Comment by zoechi** [comment]
Looks related to #19120

**Comment by CaiJingLong** [comment]
link #23847

**Comment by zoechi** [comment]
> pasteButtonLabel warning is showing like the issue

Can you please elaborate on that. 
What warning do you get exactly? 
What are the necessary steps to reproduce?

**Comment by CaiJingLong** [comment]
see the [github repo](https://github.com/CaiJingLong/localization_error_example)
But this may not happen.  It was happened on my android device.

When I click the floatButton, I will get the log `cupertino localization :null`.

And I get the from my command line tools.

whole log is: 
```
I/flutter (28890): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28890): The following NoSuchMethodError was thrown building _TextSelectionToolbar(dirty):
I/flutter (28890): The getter 'pasteButtonLabel' was called on null.
I/flutter (28890): Receiver: null
I/flutter (28890): Tried calling: pasteButtonLabel
I/flutter (28890):
I/flutter (28890): When the exception was thrown, this was the stack:
I/flutter (28890): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (28890): #1      _TextSelectionToolbar.build (package:flutter/src/cupertino/text_selection.dart:92:51)
I/flutter (28890): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731:28)
I/flutter (28890): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (28890): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (28890): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (28890): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (28890): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (28890): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (28890): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (28890): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
I/flutter (28890): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (28890): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (28890): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (28890): #24     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (28890): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (28890): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (28890): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (28890): #28     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4579:32)
I/flutter (28890): #29     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (28890): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
```

flutter doctor -v
```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.10.0 at /Users/cai/fluttersdk/flutter
    • Framework revision d954ae6850 (3 weeks ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Android NDK at /Users/cai/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Users/cai/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (2 available)
    • MI 8      • b6ec3684                             • android-arm64 • Android 8.1.0 (API 27)
    • iPhone SE • 444A5656-8089-4752-BC2A-C5BD25FE41FD • ios           • iOS 11.2 (simulator)

```

**Comment by zoechi** [comment]
Might be #23847

**Comment by CaiJingLong** [comment]
I update fluttersdk version to 0.10.2.
It is effective for me to create my own Chinese cupertino delegate class.

However, there is no default implementation for the local language set to be non English.
So if my local device is non-English and no language delegate is set, the same error will still occur as in the issue topic.

so, I think need add some code to [widgets/localizations.dart#L55](https://github.com/flutter/flutter/blob/9d53d7f848228ecd970d86724452be4cb866d6ff/packages/flutter/lib/src/widgets/localizations.dart#L55).
For example, it is difficult to locate the cause of the error by setting the default implementation in English or by using throw an error to guide developers to create their own language delegation instead of popping up an error when using it.

**Comment by xster** [comment]
Deduping https://github.com/flutter/flutter/issues/13452
