### ISSUE TITLE
build apk --release crash on OPPO R7 Android 5.1.1

### ISSUE THREAD

**Issue by krmao** [flutter/flutter#23089]
## Steps to Reproduce
I tried both master and beta channel and both crash on app startup
0. flutter status
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.1-pre.40, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
[✓] Connected device (1 available)

• No issues found!

```
1. crash by execute command below
```
flutter clean && flutter build apk && adb install build/app/outputs/apk/release/app-release.apk 
```
both
```
flutter clean && flutter build apk --release --verbose && adb install build/app/outputs/apk/release/app-release.apk 
```

## Logs
```
D/PowerSaveService( 2090): PowerSaveReceiver EXTRA_STATUS: status = 5, lastCharging = true
D/UTAnalytics:LogStoreMgr(20985): pid:20985 [store],
D/UTAnalytics:UTSqliteLogStore(20985): pid:20985 sql:SELECT * FROM log ORDER BY time ASC  LIMIT 350,
D/UTAnalytics:LogStoreMgr(20985): pid:20985 [get],[],
I/ActivityManager(  929): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.yimaguquan/com.smart.fluttertemplate.MainActivity bnds=[33,87][286,358]} from uid 10043 and from pid 1973 on display 0
D/UTAnalytics:UploadEngine(20985): pid:20985 UTDC.bBackground:false,AppInfoUtil.isForeground(UTDC.getContext()) ,true,
V/WindowManager(  929): addAppToken: AppWindowToken{3117d53a token=Token{3e850465 ActivityRecord{14f8195c u0 com.yimaguquan/com.smart.fluttertemplate.MainActivity t36}}} to stack=1 task=36 at 0
V/WindowManager(  929): Adding window Window{2f9b6f48 u0 Starting com.yimaguquan} at 6 of 18 (after Window{109a14be u0 com.android.browser/com.android.browser.BrowserActivity})
D/UTAnalytics:UploadTask(20985): pid:20985 mPeriod:30000,
I/ActivityManager(  929): Start proc 23328:com.yimaguquan/u0a146 for activity com.yimaguquan/com.smart.fluttertemplate.MainActivity
D/skia    ( 1973): SkPNGImageEncoder::doEncode bitmap.width() = 180 ,bitmap.height() = 180
D/PackageReceiver( 2090): onReceive, action is: android.intent.action.OPPO_ROM_APP_CHANGE
D/OppoNetworkControl_PackageReceiver( 2090): packageName = com.yimaguquan
D/OppoNetworkControl_PackageReceiver( 2090): hasShow = false
D/PackageReceiver( 2090): networkType = 1, getCount = 1, getColumnCount = 1
D/PackageReceiver( 2090): c.getInt(0) = 1, getColumnName(0) = wifi_state
D/PackageReceiver( 2090): packageName = com.yimaguquan, state = true
V/WindowManager(  929): Changing focus from Window{33ce8cc2 u0 com.oppo.launcher/com.oppo.launcher.Launcher EXITING} to null Callers=com.android.server.wm.WindowManagerService.relayoutWindow:3527 com.android.server.wm.Session.relayout:197 android.view.IWindowSession$Stub.onTransact:273 com.android.server.wm.Session.onTransact:130
W/linker  (23328): libflutter.so: unused DT entry: type 0x6ffffef5 arg 0x1fe04
W/linker  (23328): libflutter.so: unused DT entry: type 0x6ffffffe arg 0x1fda4
W/linker  (23328): libflutter.so: unused DT entry: type 0x6fffffff arg 0x3
E/Process (23328): android_os_Process_getProcessNameByPid pid is 23328
E/Process (23328): android_os_Process_getProcessNameByPid value is com.yimaguquan
I/Adreno-EGL(23328): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I385e983e35)
I/Adreno-EGL(23328): OpenGL ES Shader Compiler Version: E031.25.03.04
I/Adreno-EGL(23328): Build Date: 03/09/16 Wed
I/Adreno-EGL(23328): Local Branch:
I/Adreno-EGL(23328): Remote Branch:
I/Adreno-EGL(23328): Local Patches:
I/Adreno-EGL(23328): Reconstruct Branch:
I/MSM-irqbalance(  455): Decided to move IRQ57 from CPU6 to CPU4
W/ContextImpl(23328): Failed to ensure directory: /storage/sdcard1/Android/data/com.yimaguquan/files/Pictures, /storage/sdcard1 has not mounted right now
W/ContextImpl(23328): Failed to ensure directory: /storage/sdcard1/Android/data/com.yimaguquan/files/Pictures
I/flutter (23328): file:///main.dart
I/flutter (23328): android
I/flutter (23328): zh_CN
I/flutter (23328): null
I/flutter (23328): Linux 3.10.49-perf-g82297e8-00066-gffcc847 #1 SMP PREEMPT Mon Aug 22 11:39:21 CST 2016
I/flutter (23328): null
F/libc    (23328): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x680ef000 in tid 23352 (1.ui)
I/libc    (23328): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
W/        (18362): handle_request(10) debug_value = false;
W/        (18362): wait_for_sigstope = 19
F/libc    (23328): heap corruption detected by dlmalloc_real
F/libc    (23328): Fatal signal 6 (SIGABRT), code -6 in tid 23328 (com.yimaguquan)
I/libc    (23328): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
W/        (18362): wait_for_sigstope = 11
W/        (18362): stopped -- fatal signal, send SIGSTOP to process, request.pid:23328
I/DEBUG   (18362): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (18362): Build fingerprint: 'OPPO/R7Plusm/R7Plusm:5.1.1/LMY47V/1390465867:user/release-keys'
I/DEBUG   (18362): Revision: '0'
I/DEBUG   (18362): ABI: 'arm'
I/DEBUG   (18362): pid: 23328, tid: 23352, name: 1.ui  >>> com.yimaguquan <<<
I/DEBUG   (18362): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x680ef000
I/DEBUG   (18362):     r0 ab0a0930  r1 680eeff8  r2 ffffb6bf  r3 00000000
I/DEBUG   (18362):     r4 6d6fead0  r5 ffffffff  r6 ab09c030  r7 00000000
I/DEBUG   (18362):     r8 680ec6d0  r9 680eb6f0  sl 6d501f25  fp 6d6f2aa8
I/DEBUG   (18362):     ip fffcab14  sp 680ea6c8  lr 6d501ffb  pc 4013eb8c  cpsr a0070010
I/DEBUG   (18362):
I/DEBUG   (18362): backtrace:
I/DEBUG   (18362):     #00 pc 0000fb8c  /system/lib/libc.so (__memcpy_base+92)
I/DEBUG   (18362):     #01 pc 00246ff7  /data/app/com.yimaguquan-1/lib/arm/libflutter.so
I/DEBUG   (18362):     #02 pc 0032925f  /data/app/com.yimaguquan-1/lib/arm/libflutter.so
I/DEBUG   (18362):     #03 pc 0032a0d3  /data/app/com.yimaguquan-1/lib/arm/libflutter.so
I/DEBUG   (18362):     #04 pc 0000261c  /data/data/com.yimaguquan/app_flutter/vm_snapshot_instr
D/ActivityManager(  929): addErrorToDropBox processName = com.yimaguquan
I/DEBUG   (18362):
I/DEBUG   (18362): Tombstone written to: /data/tombstones/tombstone_01
W/        (18362): send SIGCONT to process, request.pid:23328
V/java.lang.ASSERT(  929): in copyTombstone
W/ActivityManager(  929):   Force finishing activity 1 com.yimaguquan/com.smart.fluttertemplate.MainActivity
W/        (18362): handle_request(10) debug_value = false;
E/        (18362): ptrace attach failed: Operation not permitted
D/DropBoxManagerService(  929): file :: /data/system/dropbox/data_app_native_crash@1539590415933.txt
I/Zygote  (  391): Process 23328 exited due to signal (11)
D/gzm_wa_WaNet(20943): upload, afterGzipSize = 309,  preGzipSize = 432, compRatio = 0.7152778
D/gzm_wa_WaNet(20943): request url count: 2
D/gzm_wa_WaNet(20943): request url: https://applog.uc.cn:443/collect?uc_param_str=&chk=67389ba2&vno=1539590416060&enc=m9&zip=gzip&uuid=R7Plusm%257COPPO%257C867620020968878%257C2c%253A5b%253Ab8%253A21%253Ad9%253A98&app=277c899c7008
D/        (  404): charger_monitor log_has_update will be set false
E/gzm_wa_WaNet(20943): response string : retcode=0`retmsg=succ
I/OppoWindowManagerService(  929): Screenshot max retries 4 of Token{3e850465 ActivityRecord{14f8195c u0 com.yimaguquan/com.smart.fluttertemplate.MainActivity t36 f}} appWin=Window{2f9b6f48 u0 Starting com.yimaguquan} drawState=4
W/ActivityManager(  929): Exception thrown during pause
W/ActivityManager(  929): android.os.DeadObjectException
W/ActivityManager(  929): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  929): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  929): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:749)
W/ActivityManager(  929): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:969)
W/ActivityManager(  929): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3245)
W/ActivityManager(  929): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3064)
W/ActivityManager(  929): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:3440)
W/ActivityManager(  929): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12764)
W/ActivityManager(  929): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:12647)
W/ActivityManager(  929): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:13354)
W/ActivityManager(  929): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12856)
W/ActivityManager(  929): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
D/ActivityManager(  929): resumeTopActivityLocked: set keepResume to true.
E/lowmemorykiller(  307): Error opening /proc/23328/oom_score_adj; errno=2
I/ActivityManager(  929): Process com.yimaguquan (pid 23328) has died
D/ActivityManager(  929): cleanUpApplicationRecordLocked:goodbye proc com.yimaguquan
```

### but if I use command below everything is ok
```
flutter clean && flutter run --release
```
why ?

**Comment by zamacona** [comment]
I have the same problem.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by cetorres** [comment]
I have the same issue! Could not solve yet.
