### ISSUE TITLE
Error running flutter packages / doctor

### ISSUE THREAD

**Issue by Salvatore-Giordano** [flutter/flutter#23141]
## Steps to Reproduce

I'm trying to publish a package using `flutter packages pub publish` but it gives me this error:

```
Write failed (OS Error: Broken pipe, errno = 32), port = 0
pub finished with exit code 69
```

## Logs

This is the `flutter doctor -v` output:
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale it-IT)
    • Flutter version 0.9.4 at /Users/salvatore/Development/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

⣾Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
#1      IntelliJValidatorOnMac.pluginsPath (package:flutter_tools/src/doctor.dart:597:31)
#2      IntelliJValidator.validate (package:flutter_tools/src/doctor.dart:434:53)
<asynchronous suspension>
#3      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:52)
#4      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
#5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:152:24)
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#17     Future._complete (dart:async/future_impl.dart:476:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by joeythomaschaske** [comment]
For what it's worth, I did a system restore and it worked. I have a hunch this is the result of previous versions of Intellij/android studio being installed.

**Comment by zoechi** [comment]
So when you update everything again to latest are you still seeing this?

**Comment by joeythomaschaske** [comment]
After performing a system restore and downloading all necessary flutter dependencies, android studio, sdks, Xcode, I am no longer seeing this issue.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
