### ISSUE TITLE
"Cannot open file /engine/darwin-x64/product_vm_isolate_snapshot.bin" when ./gradlew build

### ISSUE THREAD

**Issue by chaangliu** [flutter/flutter#23208]
Hi, I'm adding flutter to an existing app, it works well basically, I can successfully run the hybrid app and assembleDebug/assembleRelease to generate apk file. However when I use ```./gradlew build``` command to build the application, it fails with an exception.
> Task :flutter:flutterBuildDynamicRelease
Crash report written to /Users/some_path/some_application/flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
> Task :flutter:flutterBuildDynamicRelease FAILED

Here is what the ```flutter_07.log```says, it's implying me that ```product_vm_isolate_snapshot.bin``` cannot be found, I browsed the folder and the file wasn't there.. I downloaded the latest [flutter_macos_v0.9.4-beta.zip](https://flutter.io/setup-macos/#get-sdk)  and still cannot find ```product_vm_isolate_snapshot.bin```.

What should I do?

thank you

## command

flutter build bundle --suppress-analytics --target lib/main.dart --depfile /Users/liuchang/Documents/workspace/android/translator_android/translator_flutter/.android/Flutter/build/intermediates/flutter/dynamicRelease/snapshot_blob.bin.d --asset-dir /Users/liuchang/Documents/workspace/android/translator_android/translator_flutter/.android/Flutter/build/intermediates/flutter/dynamicRelease/flutter_assets --release --dynamic

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/some_path/flutter/bin/cache/artifacts/engine/darwin-x64/**product_vm_isolate_snapshot.bin**' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.4 17E199, locale en-CN)
    • Flutter version 0.9.4 at /Users/liuchang/Documents/workspace/flutter/flutter_macos_v0.7.3-beta
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/liuchang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • SM G9500 • 988b5c394548305955 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Comment by jromero** [comment]
Having the same issue on a **new** app when running `./gradlew build` in task `:app:flutterBuildDynamicRelease`

```
## command

flutter build bundle --suppress-analytics --target lib/main.dart --depfile [REDACTED]/build/app/intermediates/flutter/dynamicRelease/snapshot_blob.bin.d --asset-dir [REDACTED]/build/app/intermediates/flutter/dynamicRelease/flutter_assets --release --dynamic

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/usr/local/opt/flutter/bin/cache/artifacts/engine/darwin-x64/product_vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)
```

Doctor:

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.9.4 at /usr/local/opt/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/javier.romero/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/javier.romero/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656

[✓] Connected devices (1 available)
    • iPhone XR • 735A691C-0C2B-4462-A5E9-84DE318B1E9B • ios • iOS 12.0 (simulator)
```

**Comment by jromero** [comment]
Seems related to #22553

**Comment by krmao** [comment]
please how to fix this ? any idea ?
