### ISSUE TITLE
SnackBar error on ios 12.0

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#23243]
Hi,

I am getting SnackBar error on iOS 12.0
```
Launching lib/main.dart on iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: *********"
Running pod install...
Starting Xcode build...
Xcode build done.                                           27,5s
Installing and launching...
flutter: Load tr
Syncing files to device iPhone...
flutter: Load en
[VERBOSE-2:shell.cc(182)] Dart Error: Unhandled exception:
NoSuchMethodError: The method 'showSnackBar' was called on null.
Receiver: null
Tried calling: showSnackBar(Instance of 'SnackBar')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _MyHomePageState._showInSnackBar (package:cep/main.dart:215:31)
#2      _MyHomePageState._showWelcome.<anonymous closure> (package:cep/main.dart:207:8)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._complete (dart:async/future_impl.dart:476:7)
#8      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:16)
#9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"709","method":"getVM","params":{}}
```

**Comment by daanvandenhoek** [comment]
Could you give us some example code to see what you are doing? I think it isn't a problem with IOS but rather that you are trying to call showSnackbar on a state/scaffold that is null

**Comment by nashfive** [comment]
@NTMS2017 It's most certainly not related to the SnackBar itself.
I am pretty sure that your code failed to retrieve the ScaffoldState (either your context is null or there was no Scaffold found in the ancestors of your widget).

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

This doesn't look like a Flutter bug, so I'm closing.

**Comment by NTMS2017** [comment]
@daanvandenhoek In second page on (TabView) I was trying to call showSnackbar on a scaffold that is null. I re-write my code and will test again. Thanks
