### ISSUE TITLE
flutter run is not getting the apk installed on Nox Player

### ISSUE THREAD

**Issue by matthewkooshad** [flutter/flutter#23261]
```
flutter devices
1 connected device:

LGM V300K • 127.0.0.1:62001 • android-x86 • Android 4.4.2 (API 19)
```
```
flutter run
Launching lib/main.dart on LGM V300K in debug mode...
Initializing gradle...
  2.0s
Resolving dependencies...
  2.8s
Gradle task 'assembleDebug'...

Gradle task 'assembleDebug'... Done
  5.1s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
  8.6s
Package install error: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
Error launching application on LGM V300K.
```
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.16299.726], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.28.2)
[√] Connected devices (1 available)
```

**Comment by matthewkooshad** [comment]
i am using the latest version of Nox Player [on windows] from here: https://www.bignox.com/

**Comment by ened** [comment]
Could you please run `adb logcat` during the the installation and post the logs?

**Comment by matthewkooshad** [comment]
[logcat.txt](https://github.com/flutter/flutter/files/2496100/logcat.txt)

**Comment by jmagman** [comment]
```
W/PackageParser(  476): Exception reading /data/app/vmdl-936185143.tmp
W/PackageParser(  476): java.lang.SecurityException: Incorrect signature
W/PackageParser(  476):         at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:223)
W/PackageParser(  476):         at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:293)
W/PackageParser(  476):         at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:263)
W/PackageParser(  476):         at java.util.jar.JarFile.getInputStream(JarFile.java:379)
W/PackageParser(  476):         at android.content.pm.PackageParser.collectCertificates(PackageParser.java:639)
W/PackageParser(  476):         at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:9263)
W/PackageParser(  476):         at com.android.server.pm.PackageManagerService.access$2300(PackageManagerService.java:181)
W/PackageParser(  476):         at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:7296)
W/PackageParser(  476):         at android.os.Handler.handleCallback(Handler.java:733)
W/PackageParser(  476):         at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageParser(  476):         at android.os.Looper.loop(Looper.java:136)
W/PackageParser(  476):         at android.os.HandlerThread.run(HandlerThread.java:61)
```
Package is corrupted?

**Comment by danagbemava-nc** [comment]
Hi @matthewkooshad, do you still experience this issue with the latest stable version of flutter? If so, can you provide the steps you followed to run the application and the logs as well?

**Comment by matthewkooshad** [comment]
I'm guessing it was in 2018 when I started this thread 6 years ago that I stopped using it, because of the problem. I use other things now instead for flutter, so I don't have an answer for your question from 3 hours ago.
