### ISSUE TITLE
flutter crashes on first build/run

### ISSUE THREAD

**Issue by KammererTob** [flutter/flutter#23295]
Most of the time flutter crashes on first build/run after i open the editor and emulator. 
It says this:

```
Oops; flutter has exited unexpectedly.
Crash report written to E:\xxx\flutter_01.log;
```

This is the generated Crash Report:
## command
`
flutter build bundle --suppress-analytics --target lib/main_prod.dart --target-platform android-arm --precompiled --asset-dir E:\xxx\build\app\intermediates\flutter\release/flutter_assets --release
`
## exception
`
FileSystemException: FileSystemException: Deletion failed, path = 'E:\xxx\build\app\intermediates\flutter\release/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)
`

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:207:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:194:15)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:187:9)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:113:9)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:83:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:109:11)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#39     main (file:///F:/Programme/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 0.9.4 at F:\Programme\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\Downloads\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = E:\Downloads\android-sdk-windows
    • Java binary at: E:\Programme\JDK\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at F:\Programme\IntelliJ
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 2 categories.
```
It usually works fine if i just try it again.

**Comment by zoechi** [comment]
Can you please try restart your computer. It might just be a file being locked by another task.

**Comment by KammererTob** [comment]
This happend(s) on multiple occasions with restarts in between. Most of the time it is the first build/run of the day. #22316 does not seem to be related since there is no nodemon in my directory and it always works on the second try without me doing anything. I am using VSCode with the plugin.

**Comment by zoechi** [comment]
Perhaps some Antivirus tools running in the background and reading files `flutter` tries to delete?

**Comment by KammererTob** [comment]
I will try to disable my Antivirus the next time i run flutter for the first time and will report back if the problem persists. Thanks so far.

**Comment by KammererTob** [comment]
I added an exception to my real-time protection and so far i haven't encountered the issue. I will reopen if it appears again. Thanks for the suggestion
