### ISSUE TITLE
DragTarget Setstate while defunct exception

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#233]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [apwilson](https://github.com/apwilson)**
_Monday Oct 26, 2015 at 22:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1808_

----

```dart
10-26 15:26:12.908 E/chromium(12812): [ERROR:dart_error.cc(16)] Unhandled exception:
10-26 15:26:12.908 E/chromium(12812): 'http://localhost:9888/packages/flutter/src/widgets/framework.dart': Failed assertion: line 377 pos 12: '_debugLifecycleState != _StateLifecycle.defunct' is not true.
10-26 15:26:12.908 E/chromium(12812): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
10-26 15:26:12.908 E/chromium(12812): #1      State.setState (http://localhost:9888/packages/flutter/src/widgets/framework.dart:377:12)
10-26 15:26:12.908 E/chromium(12812): #2      DragTargetState.didLeave (http://localhost:9888/packages/flutter/src/widgets/drag_target.dart:168:5)
10-26 15:26:12.908 E/chromium(12812): #3      DragRoute.update (http://localhost:9888/packages/flutter/src/widgets/drag_target.dart:224:21)
10-26 15:26:12.908 E/chromium(12812): #4      _DraggableState._updateDrag.<anonymous closure> (http://localhost:9888/packages/flutter/src/widgets/drag_target.dart:101:16)
10-26 15:26:12.908 E/chromium(12812): #5      State.setState (http://localhost:9888/packages/flutter/src/widgets/framework.dart:378:7)
10-26 15:26:12.908 E/chromium(12812): #6      _DraggableState._updateDrag (http://localhost:9888/packages/flutter/src/widgets/drag_target.dart:100:24)
10-26 15:26:12.908 E/chromium(12812): #7      RenderPointerListener.handleEvent (http://localhost:9888/packages/flutter/src/rendering/proxy_box.dart:949:27)
10-26 15:26:12.908 E/chromium(12812): #8      FlutterBinding.dispatchEvent (http://localhost:9888/packages/flutter/src/rendering/binding.dart:240:20)
10-26 15:26:12.908 E/chromium(12812): #9      FlutterBinding._handlePointerInputEvent (http://localhost:9888/packages/flutter/src/rendering/binding.dart:225:5)
10-26 15:26:12.908 E/chromium(12812): #10     FlutterBinding._handleEvent (http://localhost:9888/packages/flutter/src/rendering/binding.dart:183:7)
```

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 22:30 GMT_

----

Do you have steps to reproduce?

**Comment by Hixie** [comment]
Closing based on out-of-band feedback.
