### ISSUE TITLE
Cant Run, HELP

### ISSUE THREAD

**Issue by yunulfikri** [flutter/flutter#23326]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --release

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Yunul Fikri\Documents\code\ameds\android\gradlew.bat -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:229:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:244:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:181:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:162:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#5      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#8      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#9      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:317:21)
<asynchronous suspension>
#10     ColdRunner.run (package:flutter_tools/src/run_cold.dart:54:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._complete (dart:async/future_impl.dart:476:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-ID)
    • Flutter version 0.9.4 at C:\src\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Redmi 3 • d0c74e0c7cf3 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like a dup of #18938 
Merging...
