### ISSUE TITLE
unallowed additional property application after upgrading 

### ISSUE THREAD

**Issue by panitaxx** [flutter/flutter#23333]
After upgrading to 0.10.1 and building: the following appears in my project 

`Error detected in pubspec.yaml:
#/properties/flutter: unallowed additional property application
Please correct the pubspec.yaml file at C:\Users\ivana\Documents\dev\school_q_tablet\pubspec.yaml
Exited (1)`

## pubspec.yaml 

```
name: school_q_tablet
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  application:
    androidPackage: com.example.schoolqtablet
    iosBundleIdentifier: com.example.schoolQTablet
```

## Logs
```
PS C:\Users\ivana\Documents\dev\school_q_tablet> flutter run --verbose
[  +35 ms] executing: [c:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [c:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] executing: [c:\src\flutter\] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [c:\src\flutter\] git log -n 1 --pretty=format:%H
[  +22 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 6a3ff018b199a7febbe2b5adbb564081d8f49e2f
[        ] executing: [c:\src\flutter\] git log -n 1 --pretty=format:%ar
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[        ] executing: [c:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.10.1-0-g6a3ff018b
[ +119 ms] executing: C:\Users\ivana\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +16 ms] Exit code 0 from: C:\Users\ivana\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[ +100 ms] Error detected in pubspec.yaml:
[        ] #/properties/flutter: unallowed additional property application
[  +11 ms] "flutter run" took 174ms.
Please correct the pubspec.yaml file at C:\Users\ivana\Documents\dev\school_q_tablet\pubspec.yaml

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      FlutterProject._readManifest (package:flutter_tools/src/project.dart:130:7)
<asynchronous suspension>
#2      FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:42:44)
<asynchronous suspension>
#3      FlutterProject.current (package:flutter_tools/src/project.dart:53:46)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:370:59)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:317:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:308:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:393:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:353:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:109:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:235:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///c:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)



[  +20 ms] C:\Users\ivana\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell getprop

```
```
 flutter analyze
Error detected in pubspec.yaml:
#/properties/flutter: unallowed additional property application
Please correct the pubspec.yaml file at C:\Users\ivana\Documents\dev\school_q_tablet\pubspec.yaml
```
```

PS C:\Users\ivana\Documents\dev\school_q_tablet> flutter doctor -v
[√] Flutter (Channel dev, v0.10.1, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.10.1 at c:\src\flutter
    • Framework revision 6a3ff018b1 (2 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ivana\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

• No issues found!

```

**Comment by josvos** [comment]
The same here (using Linux) :-(, when upgrading from 0.10.0 to 0.10.1.  A new project works. When comparing my `pubspec.yaml` with a new project, it seems that the `application` section is not allowed anymore.  But when commenting out that section in my `pubspec.yaml` I got:
```
No application found for TargetPlatform.android_x86.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```
And the suggested `flutter create .` does not work either:
```
Sorry, unable to detect the type of project to recreate. Try creating a fresh
project and migrating your existing code to the new project manually.
```
So I ended up creating my project again and injecting my own stuff (so far only `pubspec.yaml`, `lib`, and `assets`) in the new project and then it works again.

But I would like to know what's going on here and whether there is an alternative solution.

**Comment by zsirfs** [comment]
I also encountered this problem in my update today. My solution is:

Comment out appliction
2. The new build directory is ios and android, I create a new project `flutter create projectname`, then copy the android and ios directories.
3.` flutter run` is ok.

**Comment by zoechi** [comment]
As far as I know 
```
  application:
    androidPackage: com.example.schoolqtablet
    iosBundleIdentifier: com.example.schoolQTablet
```
was only supported experimentally and then removed again.

**Comment by zoechi** [comment]
I'm going to close.
See also https://github.com/flutter/flutter/pull/22935#issuecomment-430379223

**Comment by zoechi** [comment]
I'm going to close.
See also https://github.com/flutter/flutter/pull/22935#issuecomment-430379223

**Comment by zoechi** [comment]
This was only temporarily added in `master` channel as far as I know and was later removed.
I think it was https://github.com/flutter/flutter/pull/22935#issuecomment-430379223

**Comment by zoechi** [comment]
This was only temporarily added in `master` channel as far as I know and was later removed.
I think it was https://github.com/flutter/flutter/pull/22935#issuecomment-430379223

**Comment by josvos** [comment]
The issue is that these *breaking* changes (in a point-point release, 0.10.0 to 0.10.1) should IMHO be well documented in release notes, together with a guide to convert your project.  Now everyone is finding this out themselves, that all together causes a lot of wasted time. Just fixing the `pubspec.yaml` is *not enough* (and you then get a suggestion that doesn't work either, see my comment above) and it seems that most people end up in recreating the whole project.

**Comment by Hixie** [comment]
Yeah if a change was only accidental and landed then was removed, we don't usually retroactively bother to document it. We would definitely document it if it was a permanent change.
