### ISSUE TITLE
 type 'double' is not a subtype of type 'Duration'

### ISSUE THREAD

**Issue by anandrohit909** [flutter/flutter#23340]
```
When the exception was thrown, this was the stack:
I/flutter (26750): #0      _RenderSlider.value= (package:flutter/src/material/slider.dart:623:33)
I/flutter (26750): #1      _SliderRenderObjectWidget.updateRenderObject (package:flutter/src/material/slider.dart:510:9)
I/flutter (26750): #2      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4430:12)
I/flutter (26750): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (26750): #13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (26750): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #43     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #55     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #59     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (26750): #60     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (26750): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #66     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #68     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (26750): #69     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (26750): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #75     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #79     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #89     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #95     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:811:36)
I/flutter (26750): #96     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:761:34)
I/flutter (26750): #97     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter (26750): #98     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:772:36)
I/flutter (26750): #99     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:738:7)
I/flutter (26750): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #101    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (26750): #102    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (26750): #103    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter (26750): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #131    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #135    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #139    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #151    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #155    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #159    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #165    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (26750): #166    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (26750): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #170    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #174    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #177    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #178    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #180    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #183    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #184    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (26750): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #186    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (26750): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #189    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #190    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #194    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #198    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #201    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #202    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (26750): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #206    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (26750): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (26750): #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (26750): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (26750): #210    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (26750): #211    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter (26750): #212    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (26750): #213    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (26750): #214    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (26750): #215    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (26750): #216    _invoke (dart:ui/hooks.dart:139:13)
I/flutter (26750): #217    _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter (26750): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (26750): Another exception was thrown: type 'double' is not a subtype of type 'Duration'
I/flutter (26750): Another exception was thrown: type 'double' is not a subtype of type 'Duration'
```

**Comment by zoechi** [comment]
This looks like you passed a `double` value where a `Duration` was expected.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jason-simmons** [comment]
Actually, it looks like this is an error in the framework
