### ISSUE TITLE
EXCEPTION CAUGHT BY RENDERING LIBRARY

### ISSUE THREAD

**Issue by viztushar** [flutter/flutter#23352]
```
Performing hot reload...
Syncing files to device Moto G 5 Plus...
E/BpSurfaceComposerClient( 9638): Failed to transact (-1)
E/BpSurfaceComposerClient( 9638): Failed to transact (-1)
I/flutter ( 9638): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9638): The following assertion was thrown during performLayout():
I/flutter ( 9638): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12:
I/flutter ( 9638): '!_debugDoingThisLayout': is not true.
I/flutter ( 9638): 
I/flutter ( 9638): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9638): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9638): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9638):   https://github.com/flutter/flutter/issues/new
I/flutter ( 9638): 
I/flutter ( 9638): When the exception was thrown, this was the stack:
I/flutter ( 9638): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1575:12)
I/flutter ( 9638): #3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter ( 9638): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 9638): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 9638): #8      RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1649:12)
I/flutter ( 9638): #9      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1612:20)
I/flutter ( 9638): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #27     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 9638): #28     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter ( 9638): #29     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 9638): #30     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 9638): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #35     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter ( 9638): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #39     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:199:18)
I/flutter ( 9638): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #41     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 9638): #42     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter ( 9638): #43     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter ( 9638): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #61     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 9638): #62     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter ( 9638): #63     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 9638): #64     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 9638): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #69     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter ( 9638): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #86     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
I/flutter ( 9638): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #88     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 9638): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #90     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #92     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #98     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #100    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 9638): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 9638): #102    RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter ( 9638): #103    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter ( 9638): #104    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 9638): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 9638): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter ( 9638): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9638): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
Reloaded 4 of 528 libraries in 1,906ms.
I/flutter ( 9638): [{url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/Abstract_2_thub.png, size: 11 wallpapers, name: Abstract}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub/dopewalls_v102_03_thub.png, size: 50 wallpapers, name: Amoled}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub/dope_wall_v87_17_thub.png, size: 48 wallpapers, name: Animals}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/Android_Oreo_4_thub.png, size: 04 wallpapers, name: Android}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/DopeWalls_v121_09_thub.png, size: 35 wallpapers, name: Building}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/DopeWalls_v121_20_thub.png, size: 15 wallpapers, name: Cars}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/DopeWalls_v121_12_thub.png, size: 11 wallpapers, name: Floral}, {url: https://raw.githubusercontent.com/viztushar/Urban/master/thub2/Football_Walls_01_thub.png, siz
I/flutter ( 9638): #109    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9638): #110    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 9638): #112    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 9638): #113    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 9638): #114    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9638): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 9638): 
I/flutter ( 9638): The following RenderObject was being processed when the exception was fired:
I/flutter ( 9638):   RenderSliverList#50427 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638):   creator: SliverList ← MediaQuery ← SliverPadding ← ShrinkWrappingViewport ← _ScrollableScope ←
I/flutter ( 9638):   IgnorePointer-[GlobalKey#76796] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 9638):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#f355f] ←
I/flutter ( 9638):   _ScrollSemantics-[GlobalKey#67984] ← RepaintBoundary ← ⋯
I/flutter ( 9638):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter ( 9638):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 9638):   scrollOffset: 0.0, remainingPaintExtent: 504.0, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter ( 9638):   AxisDirection.right, viewportMainAxisExtent: 504.0, remainingCacheExtent: 754.0 cacheOrigin: 0.0 )
I/flutter ( 9638):   geometry: null
I/flutter ( 9638):   currently live children: 0 to 0
I/flutter ( 9638): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 9638):   RenderRepaintBoundary#e148a relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638):     RenderSemanticsAnnotations#f80a9 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638):       RenderPadding#c9372 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638):         RenderPhysicalShape#70b40 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638):           RenderCustomPaint#730ed relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9638): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9638): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 9638): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#f0b39 relayoutBoundary=up9 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#61f1b relayoutBoundary=up8 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#05d60 relayoutBoundary=up7 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a4f3e relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#e10b0 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#c839a relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#44779 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#42e6a relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#45fb7 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#45fb7 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter ( 9638): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter ( 9638): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#f0b39 relayoutBoundary=up9 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#61f1b relayoutBoundary=up8 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#05d60 relayoutBoundary=up7 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#a4f3e relayoutBoundary=up6 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#e10b0 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#c839a relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#44779 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#42e6a relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#45fb7 relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 9638): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#45fb7 relayoutBoundary=up1 NEEDS-PAINT

dart code:- https://gist.github.com/viztushar/868e27b6dfb44351a29dd690929697d7
```

**Comment by zoechi** [comment]
Merging with #18107
