### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'int' in type cast

### ISSUE THREAD

**Issue by asadali3274** [flutter/flutter#23350]
## Steps to Reproduce

hi, 
im getting this error while fetching items from json and show in a listview.

## Logs
```

import 'package:flutter/material.dart';
import 'package:gcaol/src/widgets/news_list_tile.dart';
import '../blocs/stories_provider.dart';

class PostsList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final bloc = StoriesProvider.of(context);
    bloc.fetchTopIds();
    return Scaffold(
      appBar:AppBar(
        title: Text('Top Posts'),
      ),
      body: BuildList(bloc),
    );
  }

  Widget BuildList(StoriesBloc bloc){
    return StreamBuilder(
      stream: bloc.topIds,
      builder: (BuildContext context, AsyncSnapshot<List<int>> snapshot){
        if(!snapshot.hasData){
          return Center(
            child: CircularProgressIndicator(),
          );
        }
        if(snapshot.hasError){
          return Text('Error: ${snapshot.error}');
        }
        return ListView.builder(
            itemCount: snapshot.data.length,     ////-------  this show length 10
            itemBuilder: (context, int index){
             bloc.fetchItem(snapshot.data[index]);   //// if i  print(index);  index is printed 0 to 9 but if /// 
                                                                           /// if i print(snapshot.data[index]);  shows me same error
              return NewsListTile(
                itemId: snapshot.data[index],
              );
            },
        );
      },
    );
  }
}

```

```
Performing hot reload...
Syncing files to device D6503...
I/flutter ( 5015): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5015): The following _CastError was thrown building MediaQuery(MediaQueryData(size: Size(360.0, 592.0),
I/flutter ( 5015): devicePixelRatio: 3.0, textScaleFactor: 0.85, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter ( 5015): alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations: falseinvertColors:
I/flutter ( 5015): false)):
I/flutter ( 5015): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'int' in type cast
I/flutter ( 5015): When the exception was thrown, this was the stack:
I/flutter ( 5015): #0      Object._as (dart:core/runtime/libobject_patch.dart:73:25)
I/flutter ( 5015): #1      _CastListBase.[] (dart:_internal/cast.dart:99:46)
I/flutter ( 5015): #2      PostsList.BuildList.<anonymous closure>.<anonymous closure> (package:gcaol/src/screens/posts_list.dart:35:34)
I/flutter ( 5015): #3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197:20)
I/flutter ( 5015): #4      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716:67)
I/flutter ( 5015): #5      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter ( 5015): #6      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716:26)
I/flutter ( 5015): #7      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:69)
I/flutter ( 5015): #8      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
I/flutter ( 5015): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4392:32)
I/flutter ( 5015): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter ( 5015): #18     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 5015): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #22     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #66     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #70     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #74     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4392:32)
I/flutter ( 5015): #77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4782:17)
I/flutter ( 5015): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #85     ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #89     StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #95     StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #105    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #109    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #121    StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #127    StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #129    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #139    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
Reloaded 3 of 596 libraries in 2,341ms.
I/flutter ( 5015): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #153    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #159    StatefulElement.update (package:flutter/src/widgets/framework.dart:3812:5)
I/flutter ( 5015): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #163    StatelessElement.update (package:flutter/src/widgets/framework.dart:3715:5)
I/flutter ( 5015): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #165    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4674:14)
I/flutter ( 5015): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #168    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #169    ProxyElement.update (package:flutter/src/widgets/framework.dart:3922:5)
I/flutter ( 5015): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2712:15)
I/flutter ( 5015): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter ( 5015): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter ( 5015): #173    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter ( 5015): #174    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter ( 5015): #175    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
I/flutter ( 5015): #176    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5015): #177    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5015): #178    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 5015): #180    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 5015): #181    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 5015): #182    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
I/flutter ( 5015): (elided one frame from package dart:async)
I/flutter ( 5015): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5015): Another exception was thrown: A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3510 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 5015): Instance of 'PublishSubject<List<int>>'
Application finished.

```

```
```

```
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
