### ISSUE TITLE
Video Player cannot play youtube URL

### ISSUE THREAD

**Issue by litzbalane2017** [flutter/flutter#23360]
Initialize the controller with youtube URL

```
_controller = VideoPlayerController.network(
      'https://www.youtube.com/watch?v=fhWaJi1Hsfo,
);
```
The player is unable to play the stream with the following error logs:

```
E/ExoPlayerImplInternal(14727): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(14727): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:931)
E/ExoPlayerImplInternal(14727): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
E/ExoPlayerImplInternal(14727): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
E/ExoPlayerImplInternal(14727): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/ExoPlayerImplInternal(14727): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/ExoPlayerImplInternal(14727): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by davidgalarza** [comment]
Youtube don't allow to use the link as stream url, there are  techniques to get a stream url from the youtube link on the server or on the device, but I think that is not allowed in they terms of use.
By the way there is a video that can help you: https://www.youtube.com/watch?v=7IG5kRFIMZw
I hope that youtube release an API to show inline videos actually the unique plugin that use the youtube api open the video in full screen.
https://pub.dartlang.org/packages/flutter_youtube

**Comment by zoechi** [comment]
Merging with #13756

**Comment by ila124** [comment]
how can i stream youtube videos to unity?????
