### ISSUE TITLE
Unterminated string

### ISSUE THREAD

**Issue by 2015-lizaiyang** [flutter/flutter#23365]
```dart
class httpsNet {
  dynamic httpsGet() async {
      HttpClient client = new HttpClient();
      await client
          .getUrl(Uri.parse("https://cnodejs.org/api/v1/topics?page=10&limit=4"))
          .then((HttpClientRequest request) async {
        request.headers.set(HttpHeaders.contentTypeHeader,
            'application/json; charset=UTF-8');
        return await request.close();
      }).then((HttpClientResponse response) async {
        try {
          response.transform(utf8.decoder).listen((contents) {
            debugPrint(contents);
            var userMap = json.decode(contents);
            var user = new Topics.fromJson(userMap);
            debugPrint(user.data[0].content);
          });
        } on Exception catch (e) {
        }
      });
  }
}
```

```
E/flutter ( 7871): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
E/flutter ( 7871): **FormatException: Unterminated string** (at character 6850)
E/flutter ( 7871): ...itle":"使用node-packer要怎么打包egg应用来启动和部署？","last_reply_at":"2018-10-22T10:33:47
E/flutter ( 7871):                                                                               ^
E/flutter ( 7871): 
E/flutter ( 7871): #0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1358:5)
E/flutter ( 7871): #1      _ChunkedJsonParser.close (dart:convert/runtime/libconvert_patch.dart:504:9)
E/flutter ( 7871): #2      _parseJson (dart:convert/runtime/libconvert_patch.dart:30:10)
E/flutter ( 7871): #3      JsonDecoder.convert (dart:convert/json.dart:540:36)
E/flutter ( 7871): #4      JsonCodec.decode (dart:convert/json.dart:167:41)
E/flutter ( 7871): #5      httpsNet.httpsGet.<anonymous closure>.<anonymous closure> (file:///Users/lizaiyang/code/flutter-demo/demo07/lib/login/login.dart:417:32)
E/flutter ( 7871): #6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter ( 7871): #10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 7871): #11     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
E/flutter ( 7871): #12     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
E/flutter ( 7871): #13     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
E/flutter ( 7871): #14     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
E/flutter ( 7871): #15     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
E/flutter ( 7871): #16     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter ( 7871): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter ( 7871): #21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 7871): #22     _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
E/flutter ( 7871): #23     _FilterSink.addSlice (dart:io/data_transformer.dart:611:15)
E/flutter ( 7871): #24     _FilterSink.add (dart:io/data_transformer.dart:596:5)
E/flutter ( 7871): #25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
E/flutter ( 7871): #26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter ( 7871): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #30     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7871): #31     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter ( 7871): #32     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7871): #33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #35     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 7871): #36     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 7871): #37     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 7871): #38     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7871): #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter ( 7871): .213Z","good":false,"top":false,"reply_count":18,"visit_count":892,"create_at":"2018-10-17T10:45:02.898Z","author":{"loginname":"HobaiRiku","avatar_url":"https://avatars2.githubusercontent.com/u/26238803?v=4&s=120"}},{"id":"5b5e78f5673571454c633cea","author_id":"5b56866ae740336c7bedb345","tab":"share","content":"<div class=\"markdown-text\"><p><strong>koa2实战项目介绍（真全栈）：</strong></p>\n<p><strong>Nodejs+koa2实战视频教程</strong>从零开始一步一步让你学会Koa基础以及用用<strong>Koa开发项目</strong>，本教程涉及 用户权限判断 、<strong>验证码</strong> 、分页、多级分类、<strong>ueditor可视化富文本编辑器</strong>、图片上传、<strong>底层DB库封装</strong>、<strong>扩展art-template的核心方法、<strong>ajax改变状态、ajax排序、以及赠送的</strong>Socket.io机器人</strong> 、Socket.io多人聊天室、<strong>Socket.io群聊</strong>、前后端分离 <strong>RESTful API Api</strong>接口、购买域名 服�
E/flutter ( 7871): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
E/flutter ( 7871): **FormatException: Unexpected character** (at character 1)
E/flutter ( 7871): .213Z","good":false,"top":false,"reply_count":18,"visit_count":892,"create_...
E/flutter ( 7871): ^
E/flutter ( 7871): 
E/flutter ( 7871): #0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1358:5)
E/flutter ( 7871): #1      _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1254:9)
E/flutter ( 7871): #2      _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:922:22)
E/flutter ( 7871): #3      _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
E/flutter ( 7871): #4      JsonDecoder.convert (dart:convert/json.dart:540:36)
E/flutter ( 7871): #5      JsonCodec.decode (dart:convert/json.dart:167:41)
E/flutter ( 7871): #6      httpsNet.httpsGet.<anonymous closure>.<anonymous closure> (file:///Users/lizaiyang/code/flutter-demo/demo07/lib/login/login.dart:417:32)
E/flutter ( 7871): #7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter ( 7871): #11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 7871): #12     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
E/flutter ( 7871): #13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
E/flutter ( 7871): #14     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
E/flutter ( 7871): #15     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
E/flutter ( 7871): #16     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
E/flutter ( 7871): #17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter ( 7871): #18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter ( 7871): #22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 7871): #23     _ByteAdapterSink.add (dart:convert/byte_conversion.dart:66:11)
E/flutter ( 7871): #24     _FilterSink.addSlice (dart:io/data_transformer.dart:611:15)
E/flutter ( 7871): #25     _FilterSink.add (dart:io/data_transformer.dart:596:5)
E/flutter ( 7871): #26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
E/flutter ( 7871): #27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter ( 7871): #28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7871): #31     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7871): #32     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter ( 7871): #33     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7871): #34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7871): #35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7871): #36     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 7871): #37     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 7871): #38     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 7871): #39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7871): #40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
![image](https://user-images.githubusercontent.com/21666293/47290897-2c9e1080-d634-11e8-8151-352a6b4a51c6.png)
![image](https://user-images.githubusercontent.com/21666293/47290911-3aec2c80-d634-11e8-82e4-3860a56c0eb1.png)
```
------------------------------------------------------------------------------------------------------
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.2-pre.23, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.28.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
We would need to have the full JSON string to be able to debug.
Can you please post it in a https://gist.github.com/?

**Comment by 2015-lizaiyang** [comment]
> 我们需要有完整的JSON字符串才能调试。
> 你可以在[https://gist.github.com/上](https://gist.github.com/)发帖吗？

Json string data
https://gist.github.com/2015-lizaiyang/99a313f2ef5c7bb5ae81435943592d29

**Comment by zoechi** [comment]
Looks like the JSON is so big it is not entirely contained in the first chunk and therefore split into multiple chunks. `transform` applies decode on the entire result while when you do it in `listen()` it will be applied to the parts in one chunk individually.

Thanks for the reproduction, but it appears the issue is solved and there is nothing to do for the Flutter team.
