### ISSUE TITLE
Flutter App Crashed on Compiled Engine

### ISSUE THREAD

**Issue by CLARKYJ** [flutter/flutter#23364]
## command

flutter run --local-engine-src-path=/Users/yinjie/Documents/flutter/engine/src --local-engine=ios_debug_unopt

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/yinjie/Documents/flutter/engine/src/out/host_debug_unopt/dart-sdk/bin/dart.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
#2      ResidentCompiler._compile (package:flutter_tools/src/compile.dart:278)
<asynchronous suspension>
#3      ResidentCompiler.recompile (package:flutter_tools/src/compile.dart:231)
<asynchronous suspension>
#4      DevFS.update (package:flutter_tools/src/devfs.dart:508)
<asynchronous suspension>
#5      FlutterDevice.updateDevFS (package:flutter_tools/src/resident_runner.dart:391)
<asynchronous suspension>
#6      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:294)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:160)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:246)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     _runZoned (dart:async/zone.dart:1518)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#19     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:322)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1126)
#23     _CustomZone.run (dart:async/zone.dart:1023)
#24     _runZoned (dart:async/zone.dart:1518)
#25     runZoned (dart:async/zone.dart:1465)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:278)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#29     new Future.sync (dart:async/future.dart:222)
#30     CommandRunner.run (package:args/command_runner.dart:109)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:187)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     _runZoned (dart:async/zone.dart:1518)
#37     runZoned (dart:async/zone.dart:1465)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:50)
#41     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#42     main (file:///Users/yinjie/Documents/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.5.5, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 0.5.5 at /Users/yinjie/Documents/github/flutter
    • Framework revision 020e0ef55c (4 months ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/yinjie/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone • 231589f8374d18fd876a2490445de8c740ea5a36 • ios • iOS 12.0.1

! Doctor found issues in 2 categories.
```

PS. I have compiled sim && device engine. It seems worked well on simulator, but crashed when I used engine compiled for device. don't know why : )

**Comment by CLARKYJ** [comment]
sorry, I forget to complie host_debug_unopt, it seems to cause this.

**Comment by mraleph** [comment]
You also need to build a matching host configuration (see the error message: it complains that is can't find an artifact from host_debug_unopt)

**Comment by Vadaski** [comment]
> sorry, I forget to complie host_debug_unopt, it seems to cause this.

Could you share how to complie host_debug_unopt？
I have the same problem.

**Comment by Vadaski** [comment]
## command

flutter run --local-engine-src-path /Users/didi/workspace/flutter/engine/src --local-engine=ios_debug_sim_unopt -v

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/didi/workspace/flutter/engine/src/out/host_debug_unopt/dart-sdk/bin/dart.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:760:44)
#3      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:658:14)
#4      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#5      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#6      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#14     _rootRun (dart:async/zone.dart:1180:38)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.17.3 at /Users/didi/workspace/env/flutter
    • Framework revision b041144f83 (3 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/didi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 0A519B3C-DF89-4640-B6EB-C144ED060640 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```
