### ISSUE TITLE
Local_auth plugin with MissingPluginException(No implementation found for method authenticateWithBiometrics on channel plugins.flutter.io/local_auth)

### ISSUE THREAD

**Issue by function1983** [flutter/flutter#23379]
## Steps to Reproduce

1. Add local_auth: ^0.3.0 to a working project
2. Copy the example code from the package. I attach it here, not sure if it helps [https://gist.github.com/function1983/42c1c47413c570d08edc5e50ffa98d60](https://gist.github.com/function1983/42c1c47413c570d08edc5e50ffa98d60)
3. Add `<uses-permission android:name="android.permission.USE_FINGERPRINT"/>` to Android manifests as instructed
4. `flutter run`returns with error
5. `flutter clean` doesn't help
6. library is imported as shown
![screen](https://user-images.githubusercontent.com/3862078/47314388-adc4ca00-d66b-11e8-90b3-bb350595de0c.png)

## Logs

```
E/flutter (15593): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
E/flutter (15593): MissingPluginException(No implementation found for method authenticateWithBiometrics on channel plugins.flutter.io/local_auth)
E/flutter (15593): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (15593): <asynchronous suspension>
E/flutter (15593): #1      LocalAuthentication.authenticateWithBiometrics (package:local_auth/local_auth.dart:75:27)
E/flutter (15593): <asynchronous suspension>
E/flutter (15593): #2      _MyAppState._authenticate (file:///media/func/SSD/NewAndroid/myapp/lib/main.dart:65:34)
E/flutter (15593): <asynchronous suspension>
E/flutter (15593): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (15593): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (15593): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (15593): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (15593): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (15593): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (15593): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:20)
E/flutter (15593): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:117:22)
E/flutter (15593): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:97:7)
E/flutter (15593): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:60:7)
E/flutter (15593): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:44:7)
E/flutter (15593): #14     _invoke1 (dart:ui/hooks.dart:159:13)
E/flutter (15593): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.10.2-pre.25, on Linux, locale en_US.UTF-8)
    • Flutter version 0.10.2-pre.25 at /media/func/SSD/NewAndroid/flutter
    • Framework revision 0edbe726a1 (2 hours ago), 2018-10-22 10:29:00 -0700
    • Engine revision 58cdd53f90
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /media/func/SSD/AndroidSDK
    • Android NDK at /media/func/SSD/AndroidSDK/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /media/func/SSD/AndroidSDK
    • Java binary at: /media/func/SSD/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at /media/func/SSD/android-studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.28.2)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Mi A1 • 192.168.31.10:5555 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Somewhat similar to #16819

**Comment by function1983** [comment]
Thanks @zoechi , it was an honest mistake. In my project there are TWO GeneratedPluginRegistrant.class

1. com.mycompany.GeneratedPluginRegistrant; and
2. io.flutter.plugins.GeneratedPluginRegistrant

After specifically calling `io.flutter.plugins.GeneratedPluginRegistrant.registerWith(this);` in `MainActivity extends FlutterActivity` all is working well now.

Hope it helps other who faces the same problem as I did.
Thank you.

**Comment by AaronLazarusGomes** [comment]
i don't seem to have a .java file and i have a .kt file... what would i do in that case? 

Please do help
