### ISSUE TITLE
implementation of the flutter cupertino date picker has error on real device

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#23405]
Hi, 

I implement the flutter cupertino date picker and got error as follows.
This worked on emulator but gives error on Samsung S7 Edge (SM G935F), any idea?
```
[{"event":"app.progress","params":{"appId":"63f4d9b5-e279-40e8-b545-bb881d631a7c","id":"7","progressId":"hot.reload","message":"Performing hot reload..."}}]Performing hot reload...

Syncing files to device SM G935F...
I/flutter (13909): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13909): The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(360.0,
I/flutter (13909): 640.0), devicePixelRatio: 4.0, textScaleFactor: 1.0, padding: EdgeInsets(0.0, 24.0, 0.0, 0.0),
I/flutter (13909): viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: true, accessibleNavigation:
I/flutter (13909): falsedisableAnimations: falseinvertColors: falseboldText: false)):
I/flutter (13909): The method 'datePickerDayOfMonth' was called on null.
I/flutter (13909): Receiver: null
I/flutter (13909): Tried calling: datePickerDayOfMonth(1)
I/flutter (13909): 
I/flutter (13909): When the exception was thrown, this was the stack:
I/flutter (13909): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (13909): #1      CupertinoDatePicker._getColumnWidth (package:flutter/src/cupertino/date_picker.dart:303:51)
I/flutter (13909): #2      _CupertinoDatePickerDateState.didChangeDependencies (package:flutter/src/cupertino/date_picker.dart:702:85)
I/flutter (13909): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3802:12)
I/flutter (13909): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
I/flutter (13909): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
I/flutter (13909): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
I/flutter (13909): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #9      ProxyElement.update (package:flutter/src/widgets/framework.dart:3946:5)
I/flutter (13909): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (13909): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3834:5)
I/flutter (13909): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (13909): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:3946:5)
I/flutter (13909): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (13909): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (13909): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3834:5)
I/flutter (13909): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #63     ProxyElement.update (package:flutter/src/widgets/framework.dart:3946:5)
I/flutter (13909): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:3834:5)
I/flutter (13909): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #73     StatelessElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (13909): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4802:14)
I/flutter (13909): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #79     ProxyElement.update (package:flutter/src/widgets/framework.dart:3946:5)
I/flutter (13909): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2728:15)
I/flutter (13909): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
I/flutter (13909): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
I/flutter (13909): #83     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2272:33)
I/flutter (13909): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:660:20)
I/flutter (13909): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (13909): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13909): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13909): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (13909): #90     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (13909): #91     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (13909): #92     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (13909): (elided one frame from package dart:async)
I/flutter (13909): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 9 of 680 libraries in 2.279ms.
```

**Comment by zoechi** [comment]
That would require the code that allows to reproduce (stripped of all unrelated code).
It sounds like `localizations` are missing.
Might be related to #13452

@goderbauer ?

Please add the output of `flutter doctor -v`.

**Comment by xster** [comment]
Deduping https://github.com/flutter/flutter/issues/13452
