### ISSUE TITLE
Simple input sample not working anymore

### ISSUE THREAD

**Issue by jwiese-ms** [flutter/flutter#23419]
Not sure why this is crashing, code should work just fine but isn't.  Here is the code and the error.

```
class _MyHomePageState extends State<MyHomePage> {
  
  final TextCtrl = TextEditingController();
  String inputstr;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        padding: EdgeInsets.all(20.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(hintText: 'Say something'),
              onChanged: (String textinput) {
                setState( () {
                  inputstr = TextCtrl.text.length.toString();
                });
              },
              controller: TextCtrl,
            ),
            Text(inputstr),
          ],
        ),
      ),
    );
  }
}
```

```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.                                            8.3s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#feeb2):
flutter: 'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Text (package:flutter/src/widgets/text.dart:230:15)
flutter: #3      _MyHomePageState.build (file:///Users/johnwiese/Source/Flutter/tutorials/test_1/lib/main.dart:51:13)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3765:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3677:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #26     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4900:32)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #79     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #94     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #104    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #116    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #126    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4900:32)
flutter: #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #129    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
flutter: #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #135    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #141    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #145    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #149    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #151    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #155    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #174    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #186    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #187    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #190    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #191    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #192    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #193    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #202    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #203    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #206    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #207    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4795:14)
flutter: #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #213    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #218    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #219    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #220    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #221    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #222    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #224    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #225    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #226    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #227    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #231    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #232    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #233    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #234    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #235    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #237    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #238    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #245    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #246    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #247    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #248    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #249    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #250    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #251    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #252    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #253    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #256    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #257    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #258    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #259    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #260    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #262    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #263    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #264    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3804:11)
flutter: #265    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #266    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #267    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #268    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3688:16)
flutter: #269    Element.rebuild (package:flutter/src/widgets/framework.dart:3530:5)
flutter: #270    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3657:5)
flutter: #271    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3652:5)
flutter: #272    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2936:14)
flutter: #273    Element.updateChild (package:flutter/src/widgets/framework.dart:2739:12)
flutter: #274    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:888:16)
flutter: #275    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:859:5)
flutter: #276    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:805:17)
flutter: #277    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2252:19)
flutter: #278    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:804:13)
flutter: #279    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:696:7)
flutter: #280    runApp (package:flutter/src/widgets/binding.dart:735:7)
flutter: #281    main (file:///Users/johnwiese/Source/Flutter/tutorials/test_1/lib/main.dart:3:16)
flutter: #282    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #283    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jwiese-ms** [comment]
After debugging for a while it appears what it doesn't like is that the backing String is not initialized and setting the Text's content to it is what is failing.  Could probably have a better error for this as it should be something that could be pinpointed, no?

**Comment by zoechi** [comment]
I think it's pretty clear.

> flutter: #2      new Text (package:flutter/src/widgets/text.dart:230:15)
flutter: #3      _MyHomePageState.build (file:///Users/johnwiese/Source/Flutter/tutorials/test_1/lib/main.dart:51:13)

If you navigate to `Text(` (ctrl-click or F3) you get

![image](https://user-images.githubusercontent.com/405837/47414269-daaed500-d770-11e8-8d6c-9c115f111770.png)

which shows the assertion on line 230 that expects `this.data != null` that failed.
`this.data` is the first required parameter to the `Text(...)` constructor.
