### ISSUE TITLE
java.lang.NoSuchMethodError: java.util.Locale.getScript on Android 4.4.2 XiaoMi device

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#23449]
```
java.lang.NoSuchMethodError: java.util.Locale.getScript
        at io.flutter.view.FlutterView.setLocales(FlutterView.java:354)
        at io.flutter.view.FlutterView.<init>(FlutterView.java:175)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:157)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:85)
        at com.shoppertise.pocketbook.MainActivity.onCreate(MainActivity.kt:10)
        at android.app.Activity.performCreate(Activity.java:5242)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
        at android.app.ActivityThread.access$800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5052)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
        at dalvik.system.NativeStart.main(Native Method)
```
## Logs

```
[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.14 18A391, locale en-MY)
    • Flutter version 0.10.1 at /Users/anders/flutter
    • Framework revision 6a3ff018b1 (5 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/anders/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM T815Y                  • 3300ffc315341365                         • android-arm • Android 7.0 (API 24) (emulator)
    • HM 1S                     • d0925617                                 • android-arm • Android 4.4.4 (API 19)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 4.4.2 (API 19) (emulator)
    • Anders’ iPhone X          • fb459deb33528e3571bfac0a2e555307cc879773 • ios         • iOS 12.0.1

! Doctor found issues in 2 categories.

```

**Comment by anderscheow** [comment]
I realised it was because of this
`firebaseAuth.setLanguageCode(locale.languageCode)`

**Comment by microdog** [comment]
Run into the same issue. Has this been fixed by https://github.com/flutter/engine/pull/6619?

**Comment by anderscheow** [comment]
@nvi9 Is this fix released?

**Comment by zoechi** [comment]
This should be fixed. Please add a comment if you're still seeing this to have the issue reopened.

**Comment by queeniequ** [comment]
@zoechi Not fixed. it seems the commit is not merged successfully. Please see https://github.com/flutter/flutter/pull/23323

**Comment by hartmannj** [comment]
I am having the same issue based on a Google pre-launch report with following crash log (on Samsung Galaxy S3, Android 4.3):

```
java.lang.NoSuchMethodError: java.util.Locale.getScript
	at io.flutter.embedding.engine.systemchannels.LocalizationChannel.sendLocales(LocalizationChannel.java:38)
	at io.flutter.view.FlutterView.sendLocalesToDart(FlutterView.java:334)
	at io.flutter.view.FlutterView.<init>(FlutterView.java:187)
	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:161)
	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
```
Doctor version:
```
Flutter version 1.2.3-pre.45
Framework revision d7b0aab634 (3 hours ago), 2019-02-26 10:34:03 +0800
Engine revision f7306394e3
Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
```

**Comment by zoechi** [comment]
@hartmannj can you please create a new issue. This one was closed and inactive for quite some time.
Either your problem is a regression or a different issue and therefore probably better to start a new one.

**Comment by kroikie** [comment]
@anderscheow

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/599. Any further collaboration will be done there.
