### ISSUE TITLE
flutter doctor returns [Unhandled exception: Exception: idevice_id returned an error]

### ISSUE THREAD

**Issue by Hanggi** [flutter/flutter#23455]
I ran the flutter doctor, there were some brew install items, after install these items I got this problem:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
Unhandled exception:
Exception: idevice_id returned an error:

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:122:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:152:53)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:112:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:163:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:607:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:152:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

And no solution, I don't know why this happen.

anybody help me.

**Comment by jordansilva** [comment]
I'm facing the same issue. I tried everything. Changed the channel, reinstall ideviceinstaller and libimobiledevice using --HEAD. I removed files from /var/db/lockdown/* and gave permission 777 to /var/db/lockdown/. 

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.13.6 17G65, locale en-NL)
⣽Unhandled exception:
Exception: idevice_id returned an error:

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:122:9)`

**Comment by Hanggi** [comment]
@jordansilva yes, me too, somebody said plug in the iphone to the computer, but still not work for me. 

I remember that there was a problem like follow.
> A recent change to libimobiledevice bumped the constraint on libusbmuxd to >= version 1.1.0. The current usbmuxd homebrew package is version 1.0.10.

After I fix this issue, the flutter doctor return `Exception: idevice_id returned an error:`

**Comment by jordansilva** [comment]
@Hanggi I plugged my phone and seems to work now :)
```
brew uninstall ideviceinstaller -g
brew uninstall libimobiledevice -g
brew install --HEAD libimobiledevice -g
brew install ideviceinstaller -g
sudo rm -rf /var/db/lockdown/*
sudo chmod -R 777 /var/db/lockdown/
```

**Comment by xhidnoda** [comment]
Nop...still not work for me

**Comment by jpeiffer** [comment]
Same.  Every time I attempt to launch the Flutter app, I receive:
```
idevice_id returned an error:
Exited (1)
```

`flutter doctor -v` results in:
```
[jpeiffer] ~/git/urbanft/flutter-uft$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.9.4 at /Users/jpeiffer/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

⣾Unhandled exception:
Exception: idevice_id returned an error:

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:122:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:152:53)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:112:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:163:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:91:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:607:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:152:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Merging with #23341 because there is more discussion

**Comment by sunhuaiwu** [comment]
nice

**Comment by gwenqing** [comment]
How to solve this problem

**Comment by zoechi** [comment]
@gwenqing follow #23341

**Comment by frazras** [comment]
running `sudo pkill usbmuxd` worked for me

**Comment by nisimjoseph** [comment]
I notice something interesting on my end, the Apple Simulator and Android working well and detected well. but when I connect real iPhone device, iPhone 6/7, both cause the issue. 
When I remove them from the computer USB all back to work and the simulators, Android and iOS working great.

Does anyone know why the real devices causing it?

**Comment by angelopolotto** [comment]
I got this error too. I tried all the solutions above and I couldn't solve this in my Mac.

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale pt-BR)
    • Flutter version 1.2.1 at /Users/polotto/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

⣻Unhandled exception:
Exception: ideviceinfo returned an error:

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:141:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:156:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:110:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by nisimjoseph** [comment]
Hi @angelopolotto,
I got this error too when the `libimobiledevice` is not installed well. 
did you got errors when doing `brew install --HEAD libimobiledevice` ?
if so, please do the following steps I wrote here https://github.com/flutter/flutter/issues/10633#issuecomment-475572976 and it supposed to work for you.

**Comment by angelopolotto** [comment]
I was getting this error, the odd is that error isn't clear:

```
Updating Homebrew...
Error: libimobiledevice 1.2.0_3 is already installed
To install HEAD_3, first run `brew unlink libimobiledevice`
Warning: Skipping (old) /usr/local/Cellar/libimobiledevice/1.2.0_3 due to it being linked
```

But, I solved with your comment, thank you so much!

**Comment by magnatestech** [comment]
@frazras thanks 
running sudo pkill usbmuxd worked for me on Mac OSX

**Comment by humbertojllins** [comment]
> @Hanggi I plugged my phone and seems to work now :)
> 
> ```
> brew uninstall ideviceinstaller -g
> brew uninstall libimobiledevice -g
> brew install --HEAD libimobiledevice -g
> brew install ideviceinstaller -g
> sudo rm -rf /var/db/lockdown/*
> sudo chmod -R 777 /var/db/lockdown/
> ```

tês man!

**Comment by bobdeng** [comment]
> I notice something interesting on my end, the Apple Simulator and Android working well and detected well. but when I connect real iPhone device, iPhone 6/7, both cause the issue.
> When I remove them from the computer USB all back to work and the simulators, Android and iOS working great.
> 
> Does anyone know why the real devices causing it?
> 
> Plus, when I do `brew install --HEAD libimobiledevice` it gives me an exception on the build.

me too

**Comment by bobdeng** [comment]
> I notice something interesting on my end, the Apple Simulator and Android working well and detected well. but when I connect real iPhone device, iPhone 6/7, both cause the issue.
> When I remove them from the computer USB all back to work and the simulators, Android and iOS working great.
> 
> Does anyone know why the real devices causing it?
> 
> Plus, when I do `brew install --HEAD libimobiledevice` it gives me an exception on the build.

I got exception when I use iPhone 6, it's ok when I use iPad 4

**Comment by nisimjoseph** [comment]
@bobdeng please see here https://github.com/flutter/flutter/issues/10633#issuecomment-475572976. I had the same issue with the USB, this will take care it if the compilation pass fine.
the issue is in the resolved ticket.

**Comment by JLPenaLopez** [comment]
> @Hanggi I plugged my phone and seems to work now :)
> 
> ```
> brew uninstall ideviceinstaller -g
> brew uninstall libimobiledevice -g
> brew install --HEAD libimobiledevice -g
> brew install ideviceinstaller -g
> sudo rm -rf /var/db/lockdown/*
> sudo chmod -R 777 /var/db/lockdown/
> ```

Thanks! 👍

**Comment by carlose18** [comment]
> @Hanggi I plugged my phone and seems to work now :)
> 
> ```
> brew uninstall ideviceinstaller -g
> brew uninstall libimobiledevice -g
> brew install --HEAD libimobiledevice -g
> brew install ideviceinstaller -g
> sudo rm -rf /var/db/lockdown/*
> sudo chmod -R 777 /var/db/lockdown/
> ```

craaaackkkk

**Comment by chankongching** [comment]
in the latest version of brew, after running brew update, those old commands are not working. According to documentation of [https://github.com/flutter/flutter/issues/22595], this is the command to make it work, and the following had fixed my problem
`brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice`

**Comment by lawreyios** [comment]
> running `sudo pkill usbmuxd` worked for me on Mac OSX

Did this and a restart of my VisualStudioCode and business back to normal!
