### ISSUE TITLE
`--build-shared-library` is broken with the latest NDK

### ISSUE THREAD

**Issue by microdog** [flutter/flutter#23458]
I'm unable to build apk with `--build-shared-library` option enabled after upgrading NDK to the latest version 18.1.5063045(r18b). After switching back to NDK 17.2.4988734(r17c), it works well.

## Steps to Reproduce

1. Upgrade to the latest NDK(r18b, 18.1.5063045)
2. `flutter build apk --build-shared-library`
3. Will print `Oops; flutter has exited unexpectedly.`

## Logs

```
Initializing gradle...                                       0.9s
Resolving dependencies...                                    2.1s
Gradle task 'assembleRelease'...

Oops; flutter has exited unexpectedly.
Crash report written to /Users/microdog/Workspace/Project/#####/#####_flutter/flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.

Gradle task 'assembleRelease'... Done                       35.1s
Gradle task assembleRelease failed with exit code 1
```

### command

```
flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /Users/microdog/Workspace/Project/#####/#####_flutter/build/app/intermediates/flutter/release --build-shared-library --target-platform android-arm --release
```

### exception

```
ProcessException: ProcessException: Process "/Users/microdog/Workspace/Android/SDK/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc" exited abnormally:
ld: unknown option: --sysroot=/Users/microdog/Workspace/Android/SDK/ndk-bundle/platforms/android-16/arch-arm
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Command: /Users/microdog/Workspace/Android/SDK/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot /Users/microdog/Workspace/Android/SDK/ndk-bundle/platforms/android-16/arch-arm -shared -nostdlib -o /Users/microdog/Workspace/Project/#####/#####_flutter/build/app/intermediates/flutter/release/app.so /Users/microdog/Workspace/Project/#####/#####_flutter/build/app/intermediates/flutter/release/snapshot_assembly.S
```

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      AOTSnapshotter._buildAndroidSharedLibrary (package:flutter_tools/src/base/build.dart:282:18)
<asynchronous suspension>
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:220:38)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:137:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:383:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:317:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:308:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:393:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:353:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:109:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:235:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///Users/microdog/bin/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

### flutter doctor

```
[✓] Flutter (Channel dev, v0.10.1, on Mac OS X 10.14 18A391, locale en-CN)
    • Flutter version 0.10.1 at /Users/microdog/bin/flutter
    • Framework revision 6a3ff018b1 (5 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/microdog/Workspace/Android/SDK
    • Android NDK at /Users/microdog/Workspace/Android/SDK/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Users/microdog/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    •  • 2b5a6e708d99fc0e5075184e5813f1167438d892 • ios • iOS 

! Doctor found issues in 1 category.
```

**Comment by galvesribeiro** [comment]
Same problem here. 

Any plans on fix that?

**Comment by kangwang1988** [comment]
@mraleph 
Any ideas towards this? Should we edit flutter_tools to limit not use ndk18 or any other way?

**Comment by mraleph** [comment]
This should fix it: https://github.com/flutter/flutter/pull/26642
