### ISSUE TITLE
Golden image failure when loading image asset

### ISSUE THREAD

**Issue by miguelcmedeiros** [flutter/flutter#23466]
I have a set of widget tests using golden images that always fail on the first one, although the remaining are similar. Specifically, when the widget under test has load an image asset (AssetImage in my case).

## Steps to Reproduce

Here's an example of the tests:

```
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/material.dart';

void main() {
  Widget testWidget(String asset) => MaterialApp(
        home: Scaffold(
          body: RepaintBoundary(
            child: Container(
              width: 200.0,
              height: 200.0,
              decoration: const BoxDecoration(
                image: DecorationImage(
                  image: AssetImage(
                    'assets/images/Check.png',
                  ),
                ),
              ),
            ),
          ),
        ),
      );

  testWidgets('test 1', (WidgetTester tester) async {
    await tester.pumpWidget(testWidget('assets/images/Check.png'));
    await expectLater(
      find.byType(Container),
      matchesGoldenFile('golden_images/test1.png'),
      skip: !Platform.isMacOS,
    );
  });

  testWidgets('test 2', (WidgetTester tester) async {
    await tester.pumpWidget(testWidget('assets/images/Check.png'));
    await expectLater(
      find.byType(Container),
      matchesGoldenFile('golden_images/test2.png'),
      skip: !Platform.isMacOS,
    );
  });

  testWidgets('test 3', (WidgetTester tester) async {
    await tester.pumpWidget(testWidget('assets/images/Check.png'));
    await expectLater(
      find.byType(Container),
      matchesGoldenFile('golden_images/test3.png'),
      skip: !Platform.isMacOS,
    );
  });
}
```

## Logs

**Command**
`flutter test --update-goldens test/golden_image_test.dart`

```
00:03 +0: test 1                                                                                                                                                          
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
#2      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:163:18)
#3      CachingAssetBundle.loadStructuredData (package:flutter/src/services/asset_bundle.dart:184:5)
#4      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:175:18)
#5      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:5)
#6      DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:239:55)
#7      _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:413:19)
#8      _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:431:5)
#9      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1940:16)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#19     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:188:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:169:7)
#21     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
#22     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:360:5)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#26     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:472:11)
#27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#30     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:367:12)
#31     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1689:17)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#39     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#40     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#41     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:188:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:169:7)
#43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#46     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:900:17)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#50     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2420:13)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#55     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#56     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#57     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:188:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:169:7)
#59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#63     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:2897:11)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#66     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
#67     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:604:5)
#68     RenderStack.paint (package:flutter/src/rendering/stack.dart:612:7)
#69     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#71     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#81     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#84     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:561:11)
#85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
#90     RenderView.paint (package:flutter/src/rendering/view.dart:178:15)
#91     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
#92     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#93     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#94     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:852:29)
#95     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:798:27)
#96     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&GestureBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#97     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#98     _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#99     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:705:9)
#102    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#103    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:692:27)
#104    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:227:22)
#107    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#108    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:224:27)
#109    main.<anonymous closure> (file:///Users/user/IdeaProjects/dachue/test/golden_image_test.dart:26:18)
#111    main.<anonymous closure> (file:///Users/user/IdeaProjects/dachue/test/golden_image_test.dart:25:25)
#112    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:72:23)
#113    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:556:19)
#127    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:900:17)
#129    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:888:35)
(elided 34 frames from class _FakeAsync, package dart:async, and package stack_trace)

The test description was:
test 1
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +0 -1: test 1 [E]                                                                                                                                                   
  Test failed. See exception logs above.
  The test description was: test 1
  
00:03 +2 -1: Some tests failed.   
```

**Flutter analyze**
```
flutter analyze
Analyzing dachue...                                              
No issues found! (ran in 32.1s)
```

**Flutter doctor**
```
flutter doctor -v
[✓] Flutter (Channel unknown, v0.9.2, on Mac OS X 10.13.6 17G65, locale en-NL)
    • Flutter version 0.9.2 at /Users/user/IdeaProjects/dachue/flutter
    • Framework revision 85b4670b2a (5 weeks ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • iPhone XS • 68C9BA47-3E93-41B9-96BD-AFA0F1F777A6 • ios • iOS 12.0 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
See 
https://docs.flutter.io/flutter/widgets/DefaultAssetBundle-class.html
(and https://stackoverflow.com/questions/49480080/flutter-load-assets-for-tests)

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by miguelcmedeiros** [comment]
@zoechi, thanks for the feedback.
I'll try it out.

**Comment by miguelcmedeiros** [comment]
This worked fine. I'm closing this issue.

**Comment by shehry3894** [comment]
Following help me
1.  Quit the app
2. `>> flutter clean`
3. `>> flutter run`

**Comment by UnnikrishnanBhargavakurup** [comment]
@zoechi- What if I'm trying to test is not a widget. I need to test an api class which read a JSON file from the asset folder and it is not working in the test env. It's throwing the same asset not found error.

**Comment by patreu22** [comment]
Hi @UnnikrishnanBhargavakurup - I have exactly the same problem, did you find any workaround to achieve that in the meanwhile?
