### ISSUE TITLE
ExpansionTile and ExpansionPanel can not embed ListView

### ISSUE THREAD

**Issue by chinshou** [flutter/flutter#23464]
## Steps to Reproduce

1. run following code, flutter will report lots of error message and can not display the expected listview.
```dart 
//main.dart
import 'package:flutter/material.dart';
import 'expansion_tile.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData.dark(),
      //home: ExpansionPanelListDemo(),
      home: ExpansionTileDemo(),
    );
  }
}

//expansion_tile.dart
import 'package:flutter/material.dart';

class ExpansionTileDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('expansion tile demo'),
      ),
      body: Center(
        child: ExpansionTile(
          title: Text('Expansion Tile'),
          leading: Icon(Icons.ac_unit),
          backgroundColor: Colors.white12,
          children: <Widget>[
            ListTile(
              title: Text('list tile'),
              subtitle: Text('subtitle'),
            ),
            WarnListPage(),
          ],
//          initiallyExpanded: true,
        ),
      ),
    );
  }
}

class WarnListPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new WarnListState();
}

class WarnListState extends State {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemCount: 40, itemBuilder: buildItem);
  }

  //ListView的Item
  Widget buildItem(BuildContext context, int index) {
    return new Text("Warnings");
  }
}
```

## Logs
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 2 of 417 libraries in 677ms.
I/flutter (22676): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22676): The following assertion was thrown during performResize():
I/flutter (22676): Vertical viewport was given unbounded height.
I/flutter (22676): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter (22676): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter (22676): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter (22676): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter (22676): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter (22676): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter (22676): the height of the viewport to the sum of the heights of its children.
I/flutter (22676): When the exception was thrown, this was the stack:
I/flutter (22676): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1133:15)
I/flutter (22676): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1186:6)
I/flutter (22676): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1616:9)
I/flutter (22676): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #19     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (22676): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #21     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (22676): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (22676): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #26     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (22676): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (22676): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (22676): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #32     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (22676): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (22676): #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (22676): #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (22676): #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (22676): #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (22676): #38     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter (22676): #39     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (22676): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (22676): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:661:13)
I/flutter (22676): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (22676): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22676): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22676): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (22676): #46     _invoke (dart:ui/hooks.dart:145:13)
I/flutter (22676): #47     _drawFrame (dart:ui/hooks.dart:134:3)
I/flutter (22676): The following RenderObject was being processed when the exception was fired:
I/flutter (22676):   RenderViewport#9c52b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22676):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#5256d] ← Semantics ← Listener ←
I/flutter (22676):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#6be84] ←
I/flutter (22676):   _ScrollSemantics-[GlobalKey#0e6b2] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (22676):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (22676):   parentData: <none> (can use size)
I/flutter (22676):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
I/flutter (22676):   size: MISSING
I/flutter (22676):   axisDirection: down
I/flutter (22676):   crossAxisDirection: right
I/flutter (22676):   offset: ScrollPositionWithSingleContext#190a0(offset: 0.0, range: null..null, viewport: null,
I/flutter (22676):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#2310a,
I/flutter (22676):   ScrollDirection.idle)
I/flutter (22676):   anchor: 0.0
I/flutter (22676): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (22676):   RenderSliverPadding#6c4ff NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22676):     RenderSliverList#c3b1d NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22676): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderViewport#9c52b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderViewport#9c52b NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#70432 relayoutBoundary=up15 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#564a9 relayoutBoundary=up14 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#edc1c relayoutBoundary=up13 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#c19b1 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#b0090 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b1f70 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#a316d relayoutBoundary=up9 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#dd60c relayoutBoundary=up8 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderFlex#42986 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: RenderBox was not laid out: RenderFlex#42986 relayoutBoundary=up7
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1575 pos 12: '!_debugDoingThisLayout': is not true.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (22676): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
```

```
C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel dev, v0.10.1, on Microsoft Windows [Version 10.0.17134.345], locale zh-CN)
    • Flutter version 0.10.1 at c:\Flutter
    • Framework revision 6a3ff018b1 (6 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\hubdog\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.0.2 (API 21) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
> Vertical viewport was given unbounded height.

You need to limit the height.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by hrwndr** [comment]
@chinshou I am facing the same problem, did you find any solution to this problem?

**Comment by Ess-Soft** [comment]
same issue here too
im using `CustomScrollview` as root of `Scaffold` body and `SliverList` isn't working inside `ExpansionTile`
> Reloaded 4 of 619 libraries in 2,503ms.
I/flutter (29008): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (29008): The following assertion was thrown building Container(constraints: BoxConstraints(0.0<=w<=Infinity,
I/flutter (29008): h=150.0)):
I/flutter (29008): A RenderConstrainedBox expected a child of type RenderBox but received a child of type
I/flutter (29008): RenderSliverList.
I/flutter (29008): RenderObjects expect specific types of children because they coordinate with their children during
I/flutter (29008): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
I/flutter (29008): RenderSliver does not understand the RenderBox layout protocol.
I/flutter (29008): 
I/flutter (29008): The RenderConstrainedBox that expected a RenderBox child was created by:
I/flutter (29008):   ConstrainedBox ← Container ← StreamBuilder<QuerySnapshot> ← Column ← Align ← ClipRect ← Column ←
I/flutter (29008):   Padding ← DecoratedBox ← Container ← AnimatedBuilder ← ExpansionTile ← ⋯
I/flutter (29008): 
I/flutter (29008): The RenderSliverList that did not match the expected child type was created by:
I/flutter (29008):   SliverList ← ConstrainedBox ← Container ← StreamBuilder<QuerySnapshot> ← Column ← Align ← ClipRect
I/flutter (29008):   ← Column ← Padding ← DecoratedBox ← Container ← AnimatedBuilder ← ⋯
I/flutter (29008):

**Comment by zoechi** [comment]
@Ess-Soft 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by chinshou** [comment]
Please check the solution at https://stackoverflow.com/questions/52214706/flutter-vertical-viewport-unbounded-height-error

**Comment by Miko2x** [comment]
> same issue here too
> im using `CustomScrollview` as root of `Scaffold` body and `SliverList` isn't working inside `ExpansionTile`
> 
> ```
> Reloaded 4 of 619 libraries in 2,503ms.
> I/flutter (29008): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter (29008): The following assertion was thrown building Container(constraints: BoxConstraints(0.0<=w<=Infinity,
> I/flutter (29008): h=150.0)):
> I/flutter (29008): A RenderConstrainedBox expected a child of type RenderBox but received a child of type
> I/flutter (29008): RenderSliverList.
> I/flutter (29008): RenderObjects expect specific types of children because they coordinate with their children during
> I/flutter (29008): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
> I/flutter (29008): RenderSliver does not understand the RenderBox layout protocol.
> I/flutter (29008): 
> I/flutter (29008): The RenderConstrainedBox that expected a RenderBox child was created by:
> I/flutter (29008):   ConstrainedBox ← Container ← StreamBuilder<QuerySnapshot> ← Column ← Align ← ClipRect ← Column ←
> I/flutter (29008):   Padding ← DecoratedBox ← Container ← AnimatedBuilder ← ExpansionTile ← ⋯
> I/flutter (29008): 
> I/flutter (29008): The RenderSliverList that did not match the expected child type was created by:
> I/flutter (29008):   SliverList ← ConstrainedBox ← Container ← StreamBuilder<QuerySnapshot> ← Column ← Align ← ClipRect
> I/flutter (29008):   ← Column ← Padding ← DecoratedBox ← Container ← AnimatedBuilder ← ⋯
> I/flutter (29008): 
> ```

Have you found the solution? I'm also on the same issue

**Comment by mostafa2142** [comment]
have you found the solution ? im having this issue too
