### ISSUE TITLE
Exception displaying an image from an asset

### ISSUE THREAD

**Issue by bytecrew** [flutter/flutter#23472]
## Steps to Reproduce

I am trying to display an image in a flutter app.

I have added an images directory and have a file in that directory called iu.png.

In `pubspec.yaml` I have:
```
assets:
    - images/iu.png
```

in main.dart I have:

```
child: new Column(
    children: <Widget>[
        new Text('Image Demo'),
        new Image.asset('images/iu.png'),
    ],
),
```

```
When I run the code in either an Android or iOS simulator I get the following exception:

I/flutter ( 9252): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════ I/flutter ( 9252): The following assertion was thrown resolving an image codec: I/flutter ( 9252): Unable to load asset: images/iu.png I/flutter ( 9252): I/flutter ( 9252): When the exception was thrown, this was the stack: I/flutter ( 9252): #0 PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7) I/flutter ( 9252): I/flutter ( 9252): #1
AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44) I/flutter ( 9252): I/flutter ( 9252): #2
AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14) I/flutter ( 9252): #3 ImageProvider.resolve.. (package:flutter/src/painting/image_provider.dart:266:86) I/flutter ( 9252): #4 ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20) I/flutter ( 9252): #5 ImageProvider.resolve. (package:flutter/src/painting/image_provider.dart:266:63) I/flutter ( 9252): (elided 8 frames from package dart:async) I/flutter ( 9252): I/flutter ( 9252): Image provider: AssetImage(bundle: null, name: "images/iu.png") I/flutter ( 9252): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#54de0(), name: "images/iu.png", scale: I/flutter ( 9252): 1.0) I/flutter ( 9252): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
I am using the latest flutter master and flutter doctor output is:
```
Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel master, v0.10.2-pre.21, on Mac OS X 10.13.6 17G65, locale en-GB) [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3) [✓] iOS toolchain - develop for iOS devices (Xcode 10.0) [✓] Android Studio (version 3.2) [✓] IntelliJ IDEA Community Edition (version 2018.2.3) [✓] Connected device (2 available)
Anyone have any clues?
```
## Logs

```
```

```
MBP:layout3 lol$ flutter analyze
Analyzing layout3...                                             
No issues found! (ran in 2.1s)
MBP:layout3 lol$ 
```

```
MBP:layout3 lol$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.2-pre.47, on Mac OS X 10.13.6 17G65, locale
    en-GB)
    • Flutter version 0.10.2-pre.47 at /Volumes/Data/dev/flutter
    • Framework revision 9dfc0f3aaa (11 hours ago), 2018-10-24 07:22:08 +0100
    • Engine revision 2586e94122
    • Dart version 2.1.0-dev.7.1.flutter-45f9462398

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/lol/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by anuranBarman** [comment]
Please make sure your pubspec.yaml file looks like this. if you made a folder called **assets** and then under it a folder called **images** then your pubspec.yaml file should look like this.
```yaml
assets:
    - assets/images/
```
Do care about the indentation here. That matters. For loading the images do something here like this
```dart
Image(image: AssetImage('assets/images/googlehome.jpg'),)
```
my folder structure is like below
```
assets
-images
--googlehome.jpg
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
