### ISSUE TITLE
Unable to run "flutter doctor" on MacOS Mojave

### ISSUE THREAD

**Issue by Joouis** [flutter/flutter#23494]
## Steps to Reproduce

1. Download `flutter_macos_v0.9.4-beta.zip` on flutter.io
2. Unzip it, and change directory to the folder
3. Run `./bin/flutter doctor`

## Logs

```
$ ./bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
⣾Unhandled exception:
NoSuchMethodError: The method '<' was called on null.
Receiver: null
Tried calling: <(Instance of 'Version')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      CocoaPods.evaluateCocoaPodsInstallation (package:flutter_tools/src/ios/cocoapods.dart:69:28)
<asynchronous suspension>
#2      CocoaPodsValidator.validate (package:flutter_tools/src/ios/ios_workflow.dart:210:12)
<asynchronous suspension>
#3      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:265:52)
#4      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#5      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:262:36)
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:105:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:152:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:28:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Merging with #23462
Please check the comment https://github.com/flutter/flutter/issues/23462#issuecomment-432926400 for how to fix.

**Comment by Joouis** [comment]
@zoechi Comment you mentioned works for me. Thanks!
