### ISSUE TITLE
'package:flutter/src/widgets/text.dart': Failed assertion: line 230 pos 15: 'data != null': is not true

### ISSUE THREAD

**Issue by engeslamsaad** [flutter/flutter#23507]
```
I/flutter (12132): When the exception was thrown, this was the stack:
I/flutter (12132): #2      new Text (package:flutter/src/widgets/text.dart:230:15)
I/flutter (12132): #3      ListViewCars.build.<anonymous closure> (package:lagaam2/listCars.dart:81:52)
I/flutter (12132): #4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:258:20)
I/flutter (12132): #5      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:783:67)
I/flutter (12132): #6      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter (12132): #7      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:783:26)
I/flutter (12132): #8      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:55)
I/flutter (12132): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (12132): #10     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
I/flutter (12132): #11     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:256:23)
I/flutter (12132): #12     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
I/flutter (12132): #13     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter (12132): #14     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
I/flutter (12132): #15     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:245:5)
I/flutter (12132): #16     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:323:5)
I/flutter (12132): #17     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter (12132): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #19     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (12132): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #21     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (12132): #22     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter (12132): #23     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter (12132): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (12132): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (12132): #41     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (12132): #42     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (12132): #43     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (12132): #44     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (12132): #45     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter (12132): #46     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (12132): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (12132): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
I/flutter (12132): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (12132): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12132): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12132): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (12132): #53     _invoke (dart:ui/hooks.dart:139:13)
I/flutter (12132): #54     _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter (12132): (elided 2 frames from class _AssertionError)
I/flut
```

**Comment by zoechi** [comment]
`Text(...)` requires the first parameter `data` to be not `null`.
If you pass `null` you get this exception.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
