### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE LIBRARY

### ISSUE THREAD

**Issue by rspilker** [flutter/flutter#23538]
## Logs
```
I/flutter ( 1036): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1036): The following assertion was thrown while dispatching a pointer event:
I/flutter ( 1036): 'package:flutter/src/painting/box_decoration.dart': Failed assertion: line 309 pos 12: '(Offset.zero
I/flutter ( 1036): & size).contains(position)': is not true.
I/flutter ( 1036): 
I/flutter ( 1036): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1036): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1036): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1036):   https://github.com/flutter/flutter/issues/new
I/flutter ( 1036): 
I/flutter ( 1036): When the exception was thrown, this was the stack:
I/flutter ( 1036): #2      BoxDecoration.hitTest (package:flutter/src/painting/box_decoration.dart:309:12)
I/flutter ( 1036): #3      RenderDecoratedBox.hitTestSelf (package:flutter/src/rendering/proxy_box.dart:1925:24)
I/flutter ( 1036): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:58)
I/flutter ( 1036): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #7      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
I/flutter ( 1036): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #9      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
I/flutter ( 1036): #10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #15     _RenderSliverMultiBoxAdaptor&RenderSliver&ContainerRenderObjectMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1475:22)
I/flutter ( 1036): #16     RenderSliverMultiBoxAdaptor.hitTestChildren (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:457:11)
I/flutter ( 1036): #17     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1137:11)
I/flutter ( 1036): #18     RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266:20)
I/flutter ( 1036): #19     RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1137:11)
I/flutter ( 1036): #20     RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:43)
I/flutter ( 1036): #21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #24     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2780:37)
I/flutter ( 1036): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #28     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:164:19)
I/flutter ( 1036): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #36     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:500:18)
I/flutter ( 1036): #37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
I/flutter ( 1036): #41     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:164:19)
I/flutter ( 1036): #42     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
I/flutter ( 1036): #43     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
I/flutter ( 1036): #44     GridState._itemHit (package:bnoggles/screens/game/widgets/game_board_grid.dart:46:13)
I/flutter ( 1036): #45     GridState._move (package:bnoggles/screens/game/widgets/game_board_grid.dart:38:7)
I/flutter ( 1036): #46     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2506:14)
I/flutter ( 1036): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 1036): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 1036): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 1036): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 1036): #51     _invoke1 (dart:ui/hooks.dart:153:13)
I/flutter ( 1036): #52     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
I/flutter ( 1036): (elided 2 frames from class _AssertionError)
I/flutter ( 1036): 
I/flutter ( 1036): Event:
I/flutter ( 1036):   PointerMoveEvent(Offset(220.9, 523.1))
I/flutter ( 1036): Target:
I/flutter ( 1036):   RenderPointerListener#f7476 relayoutBoundary=up3
I/flutter ( 1036): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale nl-NL)
    • Flutter version 0.9.4 at D:\flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Android\Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Nexus 6P • ENU7N15A28005684 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
Can you please provide any information about how to reproduce (minimal running reproduction)?

**Comment by rspilker** [comment]
I'll give it a try. So far, it happens more often but I cannot reproduce it.

**Comment by rspilker** [comment]
No luck so far, I'll keep trying.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by xiaozi7912** [comment]
I got problem like this issue



## Steps to Reproduce



1. implement ListView in Drawer
2. tap ListView with two fingers and throw exception
3. ListView can't scroll anymore

## Logs



```
[  +24 ms] executing: [D:\03_Softs\flutter\] git log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 90326b6184d3ada2c5be61a9086578cacca8d9ad
[   +4 ms] executing: [D:\03_Softs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +37 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.8.1-56-g90326b618
[  +17 ms] executing: [D:\03_Softs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +3 ms] executing: [D:\03_Softs\flutter\] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +51 ms] executing: [D:\03_Softs\flutter\] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +82 ms] executing: C:\Users\larryliu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +17 ms] Exit code 0 from: C:\Users\larryliu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           HQ6ADBT15534           device product:v36bml_uhl_00709 model:HTC_D628u device:htc_v36bml_uhl
           transport_id:5
           K1AXB76331512JE        device product:WW_X01BD model:ASUS_X01BDA device:ASUS_X01BD_1 transport_id:4
[  +17 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to
act on all
           devices.
[   +5 ms] C:\Users\larryliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s HQ6ADBT15534 shell getprop
[ +113 ms] ro.hardware = mt6735
[   +3 ms] ro.build.characteristics = default
[   +4 ms] C:\Users\larryliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s K1AXB76331512JE shell getprop
[  +59 ms] ro.hardware = qcom
[  +14 ms] HTC D628u   • HQ6ADBT15534    • android-arm64  • Android 5.1 (API 22)
[   +1 ms] ASUS X01BDA • K1AXB76331512JE • android-arm64  • Android 9 (API 28)
[        ] Windows     • Windows         • windows-x64    • Microsoft Windows [Version 10.0.17134.885]
[        ] Chrome      • chrome          • web-javascript • Google Chrome 75.0.3770.100
[   +9 ms] "flutter run" took 323ms.
[   +1 ms] "flutter run" took 323ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:284:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:461:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:57:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#39     main (file:///D:/03_Softs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```



```
Analyzing flutter_app...
No issues found! (ran in 2.8s)
```



```
[√] Flutter (Channel master, v1.8.2-pre.56, on Microsoft Windows [Version 10.0.17134.885], locale zh-TW)
    • Flutter version 1.8.2-pre.56 at D:\03_Softs\flutter
    • Framework revision 90326b6184 (4 hours ago), 2019-07-12 09:46:48 +0530
    • Engine revision d1dcd18486
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\larryliu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (4 available)
    • HTC D628u   • HQ6ADBT15534    • android-arm64  • Android 5.1 (API 22)
    • ASUS X01BDA • K1AXB76331512JE • android-arm64  • Android 9 (API 28)
    • Windows     • Windows         • windows-x64    • Microsoft Windows [Version 10.0.17134.885]
    • Chrome      • chrome          • web-javascript • Google Chrome 75.0.3770.100

! Doctor found issues in 1 category.
```

```
I/flutter (22338): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22338): The following assertion was thrown while dispatching a pointer event:
I/flutter (22338): 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons ==
I/flutter (22338): kPrimaryButton': is not true.
I/flutter (22338): 
I/flutter (22338): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22338): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22338): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22338):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22338): 
I/flutter (22338): When the exception was thrown, this was the stack:
I/flutter (22338): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
I/flutter (22338): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
I/flutter (22338): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (22338): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter (22338): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (22338): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (22338): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (22338): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (22338): #13     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter (22338): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter (22338): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (22338): 
I/flutter (22338): Event:
I/flutter (22338):   PointerUpEvent#db361(position: Offset(248.0, 322.7), timeStamp: 105:00:12.491000, pointer: 9,
I/flutter (22338):   kind: touch, device: 1, down: false, pressure: 0.4, pressureMin: 0.0, size: 0.4, radiusMajor:
I/flutter (22338):   25.7, radiusMinor: 25.7)
I/flutter (22338): Target:
I/flutter (22338):   <WidgetsFlutterBinding>
I/flutter (22338): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22338): Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
```

part of code
```
class MainScreenDrawer extends StatefulWidget {
  final DrawerCallback callback;

  MainScreenDrawer({this.callback});

  @override
  MainScreenDrawerState createState() => MainScreenDrawerState();
}

class MainScreenDrawerState extends State<MainScreenDrawer> {
  @override
  void initState() {
    super.initState();
    print("MainScreenDrawerState initState");
  }

  @override
  void deactivate() {
    super.deactivate();
    _isDeactivate = true;
  }

  @override
  void dispose() {
    print("MainScreenDrawerState dispose");
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Drawer(
      child: Container(
        child: Stack(
          children: <Widget>[
            ListView.separated(
              itemCount: _groupList.length,
              itemBuilder: (BuildContext context, int index) {
                return GroupListViewItem(_groupList[index].groupId, _groupList[index].groupName);
              },
              separatorBuilder: (BuildContext context, int index) {
                return Divider(
                  color: Colors.black,
                );
              },
            ),
            Visibility(
              visible: _showLoading,
              child: Align(
                alignment: Alignment.center,
                child: SizedBox(
                  child: CircularProgressIndicator(
                    strokeWidth: 5,
                  ),
                  width: 50,
                  height: 50,
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class GroupListViewItem extends StatefulWidget {
  int _groupId;

  String _groupName;

  GroupListViewItem(int groupId, String groupName) {
    _groupId = groupId;
    _groupName = groupName;
  }

  @override
  GroupListViewItemState createState() => GroupListViewItemState();
}

class GroupListViewItemState extends State<GroupListViewItem> {
  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(widget._groupName),
      subtitle: Text(widget._groupId.toString()),
      trailing: Text(widget._groupName),
    );
  }
}
```

**Comment by bhallaramdhatarwal** [comment]
I am also facing similar problem but on Share.share(); like bellow 

ListTile(
                  title: Text(S.of(context).share, textAlign: TextAlign.center),
                  onTap: () {
                    Navigator.of(context).pop();
                    final RenderBox box = context.findRenderObject();
                    Share.share(product.name,sharePositionOrigin:box.localToGlobal(Offset.zero) & box.size);
                  })

Thanks in advance
