### ISSUE TITLE
Error when making a PR to plugins or running locally firebase plugin example

### ISSUE THREAD

**Issue by ffeu** [flutter/flutter#23533]
```
[!] Unable to find a specification for `Flutter` depended upon by `firebase_core`
```

I'm trying to [make a PR to flutter/plugins](https://github.com/flutter/plugins/pull/869) and I'm facing this error, however, when running the example locally I see the same error.

Locally I have already performed `pod update`, `pod repo remove master`, `pod setup`... with no success.

This is another  [PR with a similar error message](https://github.com/flutter/plugins/pull/867/checks?check_run_id=26375305), but on another plugin - which makes me believe this is not related to one single plugin.

### flutter run (or pod install)
```
Launching lib/main.dart on iPhone 7 Plus in debug mode...
Running pod install...                                       0.5s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`arm64`)

    Fetching external sources
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `Flutter` depended upon by `firebase_core`

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53:in `block in
    sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in
    `with_no_such_dependency_error_handling'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52:in
    `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a
    platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 7 Plus.
```

### flutter doctor -v
```
[✓] Flutter (Channel master, v0.10.2-pre.60, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 0.10.2-pre.60 at /Users/feu/Projects/flutter
    • Framework revision def1d80566 (2 hours ago), 2018-10-25 11:29:31 -0700
    • Engine revision a6e816b2a6
    • Dart version 2.1.0-dev.8.0.flutter-45f9462398

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/feu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone 7 Plus • DD6EEA57-E342-4210-8A55-9AA895D3613D • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by ffeu** [comment]
Fixed by flutter/flutter#23528
