### ISSUE TITLE
crash error when flutter beta 0.9.4 work with engine 

### ISSUE THREAD

**Issue by Natoto** [flutter/flutter#23547]
## Steps to Reproduce
 
1.  fork & download & gclient sync & build `flutter/engine` with command `ninja -C out/ios_debug_unopt && ninja -C out/host_debug_unopt` to product `flutter.framework` in the `ios_debug_unopt` folder
2.  replace `flutter/bin/cache/artifacts/engine/ios/flutter.framework`
3.  run demo `flutter_gallery` with ios device

## crash Logs
 ```
2018-10-26 10:09:39.648270+0800 Runner[1109:590888] flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2018-10-26 10:09:39.663196+0800 Runner[1109:590888] flutter: The following NoSuchMethodError was thrown building IconTheme(IconThemeData#2abdc(color:
2018-10-26 10:09:39.663352+0800 Runner[1109:590888] flutter: Color(0xdd000000))):
2018-10-26 10:09:39.663417+0800 Runner[1109:590888] flutter: The getter 'languageCode' was called on null.
2018-10-26 10:09:39.663613+0800 Runner[1109:590888] flutter: Receiver: null
2018-10-26 10:09:39.663725+0800 Runner[1109:590888] flutter: Tried calling: languageCode
2018-10-26 10:09:39.665583+0800 Runner[1109:590888] flutter:
2018-10-26 10:09:39.665632+0800 Runner[1109:590888] flutter: When the exception was thrown, this was the stack:
2018-10-26 10:09:39.670266+0800 Runner[1109:590888] flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
2018-10-26 10:09:39.670441+0800 Runner[1109:590888] flutter: #1      _WidgetsAppState._resolveLocale (package:flutter/src/widgets/app.dart:691:44)
2018-10-26 10:09:39.670679+0800 Runner[1109:590888] flutter: #2      _WidgetsAppState.initState (package:flutter/src/widgets/app.dart:566:15)
2018-10-26 10:09:39.670756+0800 Runner[1109:590888] flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
2018-10-26 10:09:39.670881+0800 Runner[1109:590888] flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.670977+0800 Runner[1109:590888] flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.671095+0800 Runner[1109:590888] flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.671423+0800 Runner[1109:590888] flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.671526+0800 Runner[1109:590888] flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.671702+0800 Runner[1109:590888] flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.671809+0800 Runner[1109:590888] flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.671991+0800 Runner[1109:590888] flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.672089+0800 Runner[1109:590888] flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.672375+0800 Runner[1109:590888] flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.672502+0800 Runner[1109:590888] flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.672647+0800 Runner[1109:590888] flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.672742+0800 Runner[1109:590888] flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.672888+0800 Runner[1109:590888] flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.672997+0800 Runner[1109:590888] flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.673123+0800 Runner[1109:590888] flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.673703+0800 Runner[1109:590888] flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.673836+0800 Runner[1109:590888] flutter: #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.673985+0800 Runner[1109:590888] flutter: #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.674086+0800 Runner[1109:590888] flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.674249+0800 Runner[1109:590888] flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.674347+0800 Runner[1109:590888] flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.674484+0800 Runner[1109:590888] flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.674635+0800 Runner[1109:590888] flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.674757+0800 Runner[1109:590888] flutter: #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
2018-10-26 10:09:39.674898+0800 Runner[1109:590888] flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.675011+0800 Runner[1109:590888] flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.675141+0800 Runner[1109:590888] flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.676153+0800 Runner[1109:590888] flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.676333+0800 Runner[1109:590888] flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.676485+0800 Runner[1109:590888] flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.676616+0800 Runner[1109:590888] flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.676761+0800 Runner[1109:590888] flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.676890+0800 Runner[1109:590888] flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.677128+0800 Runner[1109:590888] flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.677254+0800 Runner[1109:590888] flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.677388+0800 Runner[1109:590888] flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.677508+0800 Runner[1109:590888] flutter: #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
2018-10-26 10:09:39.677636+0800 Runner[1109:590888] flutter: #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.677745+0800 Runner[1109:590888] flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.677863+0800 Runner[1109:590888] flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.678010+0800 Runner[1109:590888] flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
2018-10-26 10:09:39.678132+0800 Runner[1109:590888] flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
2018-10-26 10:09:39.678275+0800 Runner[1109:590888] flutter: #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
2018-10-26 10:09:39.678388+0800 Runner[1109:590888] flutter: #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
2018-10-26 10:09:39.678483+0800 Runner[1109:590888] flutter: #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
2018-10-26 10:09:39.678628+0800 Runner[1109:590888] flutter: #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
2018-10-26 10:09:39.678749+0800 Runner[1109:590888] flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
2018-10-26 10:09:39.678898+0800 Runner[1109:590888] flutter: #52     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:901:16)
2018-10-26 10:09:39.679013+0800 Runner[1109:590888] flutter: #53     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:872:5)
2018-10-26 10:09:39.679122+0800 Runner[1109:590888] flutter: #54     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:818:17)
2018-10-26 10:09:39.679253+0800 Runner[1109:590888] flutter: #55     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
2018-10-26 10:09:39.679373+0800 Runner[1109:590888] flutter: #56     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:817:13)
2018-10-26 10:09:39.679509+0800 Runner[1109:590888] flutter: #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:709:7)
2018-10-26 10:09:39.679624+0800 Runner[1109:590888] flutter: #58     runApp (package:flutter/src/widgets/binding.dart:748:7)
2018-10-26 10:09:39.679748+0800 Runner[1109:590888] flutter: #59     main (file:///Users/boo/Documents/flutter/examples/flutter_gallery/lib/main.dart:13:3)
2018-10-26 10:09:39.679904+0800 Runner[1109:590888] flutter: #60     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
2018-10-26 10:09:39.680066+0800 Runner[1109:590888] flutter: #61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
2018-10-26 10:09:39.682756+0800 Runner[1109:590888] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Probably related to 

- https://github.com/flutter/flutter/pull/23583
- https://github.com/flutter/engine/pull/6632
- https://github.com/flutter/engine/pull/6613

I don't know what

> replace flutter/bin/cache/artifacts/engine/ios/flutter.framework

is for exactly, but I guess this error results from some inconsistency between used framework and gallery code or similar that should be fixed in latest versions.

**Comment by Natoto** [comment]
`replace flutter/bin/cache/artifacts/engine/ios/flutter.framework` 

> Probably related to
> 
> * #23583
> * [flutter/engine#6632](https://github.com/flutter/engine/pull/6632)
> * [flutter/engine#6613](https://github.com/flutter/engine/pull/6613)
> 
> I don't know what
> 
> > replace flutter/bin/cache/artifacts/engine/ios/flutter.framework
> 
> is for exactly, but I guess this error results from some inconsistency between used framework and gallery code or similar that should be fixed in latest versions.
that means exactly
use myself built flutter.framework  replace `/some flutter path/bin/cache/artifacts/engine/ios/flutter.framework`
and run demo
---

thank u for response~

10.29 update

the problem has been resolve as next steps

before build , revert engine version `git reset --hard 74625aed323d04f2add0410e84038d250f51b616`

and,  use `gclient sync --with_branch_heads —with_tags`  rather than  `gclient sync` 

and built & run successfully ~~

**Comment by zoechi** [comment]
Sounds like this issue can be closed.
Please add a comment if you disagree.
