### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation

### ISSUE THREAD

**Issue by MarcelEdward2** [flutter/flutter#23559]
## Steps to Reproduce

In the pre-launch report on the play store, I get 'Probleem: Usage of non-SDK interfaces' on a android 9 device test.

On the other devices with lower android version this problem does not occur. 

How can I prevent the usage of the non-SDK intefaces so will not get reports of our apps not running or crashing on android 9 devices ?

## Logs
```
10-19 02:42:53.418: D/StrictMode(12719): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String;
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getMethod(Class.java:2064)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.gms.org.conscrypt.Platform.<clinit>(:com.google.android.gms@13280037@13.2.80 (100400-211705629):1)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.gms.org.conscrypt.Platform.setup(Unknown Source:0)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.gms.org.conscrypt.OpenSSLProvider.<init>(:com.google.android.gms@13280037@13.2.80 (100400-211705629):4)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(:com.google.android.gms@13280037@13.2.80 (100400-211705629):17)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.reflect.Method.invoke(Native Method)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.gms.e.a.a(Unknown Source:83)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.i.a(Unknown Source:0)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.ac.run(Unknown Source:2)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.a.fm.c(Unknown Source:0)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.a.fq.call(Unknown Source:2)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.a.fm.a(Unknown Source:0)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.a.fp.run(Unknown Source:4)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.firebase.firestore.a.fm$a.run(Unknown Source:15)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Thread.run(Thread.java:764)
10-19 02:42:53.418: D/StrictMode(12719): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/hardware/input/InputManager;->getInstance()Landroid/hardware/input/InputManager;
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getMethod(Class.java:2064)
10-19 02:42:53.418: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.base.InputManagerEventInjectionStrategy.a(InputManagerEventInjectionStrategy.java:7)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:8)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:12)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:7)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.DaggerBaseLayerComponent$ViewInteractionComponentImpl.a(DaggerBaseLayerComponent.java:29)
10-19 02:42:53.418: D/StrictMode(12719): 	at androidx.test.espresso.Espresso.a(Espresso.java:1)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.tryExtractingScreenState(HybridStateExtractor.java:39)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.getStableScreen(HybridStateExtractor.java:10)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.action.LocalActionExecutor.waitForResults(LocalActionExecutor.java:10)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:23)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
10-19 02:42:53.418: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.Looper.loop(Looper.java:193)
10-19 02:42:53.418: D/StrictMode(12719): 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-19 02:42:53.420: D/StrictMode(12719): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/hardware/input/InputManager;->injectInputEvent(Landroid/view/InputEvent;I)Z
10-19 02:42:53.420: D/StrictMode(12719): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
10-19 02:42:53.420: D/StrictMode(12719): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
10-19 02:42:53.420: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
10-19 02:42:53.420: D/StrictMode(12719): 	at java.lang.Class.getMethod(Class.java:2064)
10-19 02:42:53.420: D/StrictMode(12719): 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.base.InputManagerEventInjectionStrategy.a(InputManagerEventInjectionStrategy.java:12)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:8)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:12)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:7)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.DaggerBaseLayerComponent$ViewInteractionComponentImpl.a(DaggerBaseLayerComponent.java:29)
10-19 02:42:53.420: D/StrictMode(12719): 	at androidx.test.espresso.Espresso.a(Espresso.java:1)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.tryExtractingScreenState(HybridStateExtractor.java:39)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.getStableScreen(HybridStateExtractor.java:10)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.action.LocalActionExecutor.waitForResults(LocalActionExecutor.java:10)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:23)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
10-19 02:42:53.420: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
10-19 02:42:53.420: D/StrictMode(12719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 02:42:53.420: D/StrictMode(12719): 	at android.os.Looper.loop(Looper.java:193)
10-19 02:42:53.420: D/StrictMode(12719): 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-19 02:42:53.421: D/StrictMode(12719): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/hardware/input/InputManager;->INJECT_INPUT_EVENT_MODE_WAIT_FOR_FINISH:I
10-19 02:42:53.421: D/StrictMode(12719): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
10-19 02:42:53.421: D/StrictMode(12719): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
10-19 02:42:53.421: D/StrictMode(12719): 	at java.lang.Class.getPublicFieldRecursive(Native Method)
10-19 02:42:53.421: D/StrictMode(12719): 	at java.lang.Class.getField(Class.java:1599)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.base.InputManagerEventInjectionStrategy.a(InputManagerEventInjectionStrategy.java:15)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.base.BaseLayerModule_ProvideEventInjectorFactory.get(BaseLayerModule_ProvideEventInjectorFactory.java:8)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerImpl_Factory.get(UiControllerImpl_Factory.java:12)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.base.UiControllerModule_ProvideUiControllerFactory.get(UiControllerModule_ProvideUiControllerFactory.java:7)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.obfuscated.ba.a.get(DoubleCheck.java:10)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.DaggerBaseLayerComponent$ViewInteractionComponentImpl.a(DaggerBaseLayerComponent.java:29)
10-19 02:42:53.421: D/StrictMode(12719): 	at androidx.test.espresso.Espresso.a(Espresso.java:1)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.tryExtractingScreenState(HybridStateExtractor.java:39)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.getStableScreen(HybridStateExtractor.java:10)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.action.LocalActionExecutor.waitForResults(LocalActionExecutor.java:10)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:23)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
10-19 02:42:53.421: D/StrictMode(12719): 	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
10-19 02:42:53.421: D/StrictMode(12719): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 02:42:53.421: D/StrictMode(12719): 	at android.os.Looper.loop(Looper.java:193)
10-19 02:42:53.421: D/StrictMode(12719): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by MisterJimson** [comment]
See here https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

This is not directly related to Flutter, just new restrictions as part of Android 9.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by MarcelEdward2** [comment]
[√] Flutter (Channel master, v0.10.2-pre.47, on Microsoft Windows [Version 10.0.17134.345], locale nl-NL)
    • Flutter version 0.10.2-pre.47 at C:\flutter
    • Framework revision 9dfc0f3aaa (5 days ago), 2018-10-24 07:22:08 +0100
    • Engine revision 2586e94122
    • Dart version 2.1.0-dev.7.1.flutter-45f9462398

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Marcel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • 5015X • NFL7ORWS99999999 • android-arm • Android 5.1 (API 22)

• No issues found!

**Comment by MarcelEdward2** [comment]
> See here https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces
> 
> This is not directly related to Flutter, just new restrictions as part of Android 9.

But does this mean flutter apps will not run on Android 9 devices  ?

**Comment by MarcelEdward2** [comment]
With the latest update of flutter the non-sdk problem seems to be gone
