### ISSUE TITLE
Cannot build iOS / run pod install

### ISSUE THREAD

**Issue by littlemarc2011** [flutter/flutter#23573]
## Steps to Reproduce

1. Create a flutter plugin: ```flutter create --template=plugin --description="Android Pay & Apple Pay" --org="me.marc_little" --project-name="flutter_pay" --ios-language=swift flutter_pay```
**``#a`` will be trying to build with flutter**
2a. ```cd flutter_pay/example/```
3a. ```flutter build ios --no-codesign```
**``#b`` will be trying to run pod install**
2b. ```cd flutter_pay/example/ios/```
3b. ```pod install```
(both #a and #b have the same output since build runs pod install)

## Logs

```
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building me.marc_little.flutterPayExample for device (ios-release)...
Running pod install...                                       0.6s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
    [!] There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:
    Runner: Swift 
    Runner: Swift 4.0

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer/target_inspector.rb:248:in `compute_swift_version_from_targets'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer/target_inspector.rb:50:in `compute_results'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:921:in `block (3 levels) in inspect_targets_to_integrate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:919:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:919:in `block (2 levels) in inspect_targets_to_integrate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/bigmarco/Repositories in
    PATH, mode 040777

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```

## ``flutter analyze``
```
Marcs-MacBook-Pro:example bigmarco$ flutter analyze
Analyzing example...                                             
No issues found! (ran in 2.8s)
Marcs-MacBook-Pro:example bigmarco$ cd ../
Marcs-MacBook-Pro:flutter_pay bigmarco$ flutter analyze
Analyzing flutter_pay...                                         
No issues found! (ran in 1.6s)
```

## ``flutter doctor -v``
```
[✓] Flutter (Channel master, v0.10.2-pre.60, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.10.2-pre.60 at /Users/bigmarco/Repositories/flutter
    • Framework revision def1d80566 (21 hours ago), 2018-10-25 11:29:31 -0700
    • Engine revision a6e816b2a6
    • Dart version 2.1.0-dev.8.0.flutter-45f9462398

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/bigmarco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4323.44

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by littlemarc2011** [comment]
I updated flutter, recreated the plugin (with the same command) and everything worked perfectly. The issue may have been on my end and this can be closed unless other people are having this issue also.
