### ISSUE TITLE
No named parameter with the name 'decorationStyle'.

### ISSUE THREAD

**Issue by HuRuWo** [flutter/flutter#23581]
## Steps to Reproduce

1. flutter  create new_project
2. cd new_project
3. flutter run

## Logs

```
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/flutter ( 5334): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5334): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter ( 5334): 'package:flutter/src/painting/text_style.dart': error: line 243 pos 10:
I/flutter ( 5334): file:///H:/flutter/packages/flutter/lib/src/painting/text_style.dart:243:10: Error: 'FontStyle'
I/flutter ( 5334): isn't an instance field of this class.
I/flutter ( 5334):     this.FontStyle,
I/flutter ( 5334):          ^^^^^^^^^
I/flutter ( 5334):     this.FontStyle,
I/flutter ( 5334):          ^
I/flutter ( 5334): 'package:flutter/src/material/typography.dart': error: line 495 pos 15: error evaluating constant
I/flutter ( 5334): constructor
I/flutter ( 5334):     display4: TextStyle(debugLabel: 'blackMountainView display4', fontFamily: 'Roboto',
I/flutter ( 5334):     inherit: true, color: Colors.black54, decoration: TextDecoration.none),
I/flutter ( 5334):               ^
I/flutter ( 5334): 'package:flutter/src/material/typography.dart': error: line 463 pos 36: Not a constant expression.
I/flutter ( 5334):           _MaterialTextColorThemes.blackMountainView,
I/flutter ( 5334):                                    ^
I/flutter ( 5334): 
I/flutter ( 5334): When the exception was thrown, this was the stack:
I/flutter ( 5334): #0      new ThemeData (package:flutter/src/material/theme_data.dart:203:35)
I/flutter ( 5334): #1      MyApp.build (file:///H:/gey_flutter/gey_flutter/lib/main.dart:11:18)
I/flutter ( 5334): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731:28)
I/flutter ( 5334): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter ( 5334): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 5334): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter ( 5334): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter ( 5334): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 5334): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 5334): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:898:16)
I/flutter ( 5334): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:869:5)
I/flutter ( 5334): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:815:17)
I/flutter ( 5334): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter ( 5334): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:814:13)
I/flutter ( 5334): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:706:7)
I/flutter ( 5334): #15     runApp (package:flutter/src/widgets/binding.dart:745:7)
I/flutter ( 5334): #16     main (file:///H:/gey_flutter/gey_flutter/lib/main.dart:3:16)
I/flutter ( 5334): #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 5334): #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 5334): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
>flutter analyze
Analyzing gey_flutter...
No issues found! (ran in 6.1s)

```

```


```

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.10.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.28.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
There seems to be some inconsistency in your Flutter installation.
The mentioned line doesn't contain the referred code https://github.com/flutter/flutter/blob/v0.10.0/packages/flutter/lib/src/painting/text_style.dart#L243

Can you please try
```
git clean -xfd
git pull
flutter doctor
```
in `H:\flutter`

**Comment by HuRuWo** [comment]
I reinstall my system . 
and  it work
-----------
a new error

logs 
```
* Error running Gradle:
ProcessException: Process "E:\flutter_app\flutter_app\android\gradlew.bat" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\flutter_app\flutter_app\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: E:\flutter_app\flutter_app\android\gradlew.bat app:properties
```

**Comment by zoechi** [comment]
Merging with #23404
