### ISSUE TITLE
diconnect() causing error

### ISSUE THREAD

**Issue by ayush-12** [flutter/flutter#23625]
I am using google sign in with Firebase. First time I am able to log in and get user credentials as well but while pressing sign out button I am signing out in below lines and this works fine.
```dart
    await _auth.signOut();
    await _googleSignIn.signOut();
```

but when adding      `await _googleSignIn.disconnect();`
some times the user gets signed out properly then while logging in again the app freezes or sometimes the app freezes before signing the user out.

Below are the logs.
```
E/flutter (16617): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (16617): PlatformException(status, Failed to disconnect., null)
E/flutter (16617): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (16617): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (16617): <asynchronous suspension>
E/flutter (16617): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter (16617): <asynchronous suspension>
E/flutter (16617): #3      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:269:28)
E/flutter (16617): #4      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (16617): #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (16617): #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (16617): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (16617): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
E/flutter (16617): #9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (16617): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ayush-12** [comment]
PS E:\Projects\Flutter Projects\abc> flutter doctor
Waiting for another flutter command to release the startup lock...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.25.1)
[!] Connected devices
    ! No devices available

**Comment by GiacomoK** [comment]
Same problem here

**Comment by thanhhuan1990** [comment]
Same problem too.

**Comment by alice-0-kim** [comment]
The problem still persists. Is there an update regarding this issue? Below are the logs:
```
E/flutter ( 5046): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(status, Failed to disconnect., null)
E/flutter ( 5046): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 5046): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 5046): <asynchronous suspension>
E/flutter ( 5046): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:330:48)
E/flutter ( 5046): <asynchronous suspension>
E/flutter ( 5046): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:218:23)
E/flutter ( 5046): <asynchronous suspension>
E/flutter ( 5046): #4      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:257:20)
E/flutter ( 5046): #5      GoogleSignIn.disconnect (package:google_sign_in/google_sign_in.dart:335:47)
E/flutter ( 5046): #6      MyHomePageState._handleSignOut (package:hello_world/main.dart:143:18)
E/flutter ( 5046): <asynchronous suspension>
E/flutter ( 5046): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 5046): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 5046): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 5046): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 5046): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
E/flutter ( 5046): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
E/flutter ( 5046): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 5046): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 5046): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
E/flutter ( 5046): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 5046): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5046): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5046): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5046): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5046): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5046): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5046): #23     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 5046): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 5046): 
```
Thank you!

**Comment by jorgefalconcampos** [comment]
Same issue here... did you find any solution?

**Comment by kroikie** [comment]
@ayush-12

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/592. Any further collaboration will be done there.

**Comment by uysalserkan08** [comment]
same problem..

**Comment by SPK-RPI** [comment]
```
handleLogOut() async {
    await _googleSignIn.disconnect().whenComplete(() async {
      await _auth.signOut();
    });
  }
```

Works fine for me but next time when I Tap on login Button it silently  sign in insted of providing a list of accounts. How to get the list of accounts back.
