### ISSUE TITLE
Gallery app crashes on startup -  android.os.DeadObjectException

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2367]
Trying to launch the Material Gallery example. 

```
hansmuller@chumley:/builds/dev/flutter$ (cd /builds/dev/flutter/examples/material_gallery/; pub get; flutter start --checked;  flutter logs)
Resolving dependencies... 
Got dependencies!
Building APK...
Warning: signing the APK using the debug keystore.
Generated APK to build/app.apk.
Installing app.apk on device.
Starting lib/main.dart on Nexus 5...
Showing Nexus 5 logs:
--------- beginning of crash
--------- beginning of main
--------- beginning of system
W/ActivityManager:   Force finishing activity 1 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11500)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11397)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12081)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11592)
W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

```

**Comment by Hixie** [comment]
@jason-simmons found a fix that I'm trying to land in https://github.com/flutter/flutter/pull/2371.

**Comment by HansMuller** [comment]
Fixed by https://github.com/flutter/engine/pull/2449 but see
https://github.com/flutter/flutter/issues/2383
