### ISSUE TITLE
Flutter crashes while running ./gradlew build (Task :app:flutterBuildDynamicRelease FAILED)

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#23684]
**Background :** 
I want to implement facebook auth login in my flutter app, so started to follow the guidelines from here : https://developers.facebook.com/docs/facebook-login/android and was stuck at step 3.3 : _Build your project._ 
Below is my project configuration for android and flutter respectively:

**Flutter version:** 
`Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git Framework • revision f37c235c32 (5 weeks ago) • 2018-09-25 17:45:40 -0400 Engine • revision 74625aed32 Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044`

**android/app/build.gradle:**

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 27

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId ""
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
}

apply plugin: 'com.google.gms.google-services'

```
**android project build.gradle:**

```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**gradle-wrapper.properties:**

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip`

**Flutter dependencies:**

```gradle
dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_login: ^1.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.0"

  # Making REST requests
  http: "^0.11.3+16"

  #Firebase authentication plugin
  firebase_auth: "^0.5.11"

  # Firebase cloud messaging
  firebase_messaging: "^1.0.5"

  # Google sign-in plugin for Firebase authentication
  google_sign_in: "^3.0.4"

  # Grey scale for pro profile images based on availability for video call
  image: "^2.0.4"

  # Show toast messages
  fluttertoast: "^2.0.8"

  # Upload credit cards
  stripe_api: ^1.0.3

  # open terms of service and privacy policy URLs
  url_launcher: "^3.0.3"

  # connect to web sockets
  web_socket_channel: ^1.0.9
```
**Android Studio version : 3.1.3**

Since I had not touched the _android_ or _iOS_ folders in my flutter repo earlier and in order to implement facebook auth, I have to install facebook sdk and sync the repo, I came across this issue. After adding _mavenCentral_ in `project module of build.gradle` and adding _implementation 'com.facebook.android:facebook-android-sdk:[4,5)'_ in `app module of build.gradle`, I tried to run `./gradlew build` from android path which gave me different errors that I fixed (ex: most of the errors were related to `fluttertoast` plugin used in my flutter app. But then, I started to get this error consistently:

`Could not resolve project :fluttertoast. Required by: project :app       > java.lang.NullPointerException (no error message)`

For which I came across this issue : https://github.com/flutter/flutter/issues/22397. I implemented the changes based on most recent comment in this issue, but observed a crash as below:

```
./gradlew build

> Configure project :app
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 11.4.2 will be used.
please apply google-services plugin at the bottom of the build file.
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/dynamicProfile, src/dynamicProfile/nullnull, src/nullnull, src/dynamicProfile, src/nullnullDynamicProfile]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/profile, src/profile/nullnull, src/nullnull, src/profile, src/nullnullProfile]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/dynamicRelease, src/dynamicRelease/nullnull, src/nullnull, src/dynamicRelease, src/nullnullDynamicRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:processDebugGoogleServices
Parsing json file: /Users/deeptibelsare/Documents/QuickCarl/qc_flutter/android/app/google-services.json

> Task :app:processDynamicProfileGoogleServices
Parsing json file: /Users/deeptibelsare/Documents/QuickCarl/qc_flutter/android/app/google-services.json

> Task :app:flutterBuildDynamicRelease
Running "flutter packages get" in qc_flutter...                  1.1s

Oops; flutter has exited unexpectedly.
Crash report written to /Users/deeptibelsare/Documents/QuickCarl/qc_flutter/flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```
**Crash log:**

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

`flutter build bundle --suppress-analytics --target lib/main.dart --depfile /Users/deeptibelsare/Documents/QuickCarl/qc_flutter/build/app/intermediates/flutter/dynamicRelease/snapshot_blob.bin.d --asset-dir /Users/deeptibelsare/Documents/QuickCarl/qc_flutter/build/app/intermediates/flutter/dynamicRelease/flutter_assets --release --dynamic`

## exception

`FileSystemException: FileSystemException: Cannot open file, path = '/Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter/bin/cache/artifacts/engine/darwin-x64/product_vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)`

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.2 17C88, locale en-US)
    • Flutter version 0.9.4 at /Users/deeptibelsare/Documents/DarshanUdacity/Flutter/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.
```
I hope the provided details and crash log will be helpful.

**Comment by DK15** [comment]
@gordinmitya the flutter facebook plugin documentation (https://pub.dartlang.org/packages/flutter_facebook_login) says "_Also some minimal Android & iOS specific configuration must be done, otherwise your app will crash_."
So I believe we need to follow android and iOS example even after adding flutter dependency.
Also, I do have `google-services.json` at correct path. I have gone through the medium article you shared earlier and it also says to complete step 1 to 6 for `android` and step 1 to 4 for `iOS`.

**Comment by DK15** [comment]
@zoechi wondering if there's any workaround until this is fixed ?

**Comment by zoechi** [comment]
Sorry, can't help you here. My gradle knowledge is quite limited.

**Comment by cyanglaz** [comment]
@DK15 It seems the crash could happen on the plugin itself. Unfortunately, https://pub.dartlang.org/packages/flutter_facebook_login is a plugin that we do not maintain. Have you fired a bug on their GitHub and see what they have to say about it?
