### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by gggustafson** [flutter/flutter#23710]
In accordance with the following:

```
Oops; flutter has exited unexpectedly.
Crash report written to C:\Gustafson\flutter\navigation_basics\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
Crash report follows.

[flutter_01.log](https://github.com/flutter/flutter/files/2527677/flutter_01.log)

**Comment by nklayman** [comment]
Try deleting the folder manually at 

`C:\Gustafson\flutter\navigation_basics\build\app\intermediates\flutter\debug/flutter_assets`

That is what appears to cause the error

```
## exception

FileSystemException: FileSystemException: Deletion failed, path = 'C:\Gustafson\flutter\navigation_basics\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)
```

**Comment by zoechi** [comment]
Something else probably has a file opened in that directory which prevents flutter to delete it.

See 
- https://github.com/flutter/flutter/issues/22316#issuecomment-426705145
- https://github.com/flutter/flutter/issues/23295#issuecomment-432186004

**Comment by gggustafson** [comment]
If another process has a required file open, flutter should provide a message stating that and not crash. 

I deleted the directory and:

```
1. Pressed F5
2. Following displayed:

Launching lib\main.dart on SM G925V in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.

3. Displays "Installing..." and "Syncing..."
4. Then <source not available>.
```

The Debug Console displays:

```
Launching lib\main.dart on SM G925V in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
Unhandled exception:
NoSuchMethodError: The getter 'className' was called on null.
Receiver: null
Tried calling: className
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      serializeProcedure (package:front_end/src/fasta/kernel/utils.dart:99:29)
#2      FrontendCompiler.compileExpression (package:vm/frontend_server.dart:494:16)
<asynchronous suspension>
#3      _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:60:22)
#4      listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:770:20)
<asynchronous suspension>
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#10     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#11     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#12     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#13     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#20     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#21     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#22     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#23     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#24     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#25     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#30     _StreamController._add (dart:async/stream_controller.dart:639:7)
#31     _StreamController.add (dart:async/stream_controller.dart:585:5)
#32     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#37     _StreamController._add (dart:async/stream_controller.dart:639:7)
#38     _StreamController.add (dart:async/stream_controller.dart:585:5)
#39     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#40     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

It turns out that the following code was in main.dart:

```
// *********************************************** class Game_Settings

class Game_Settings {
  double milliseconds_multiplier = 500.0;
  bool   randomize_colors = false;
} // class Game_Settings

Game_Settings game_settings;
```

Unfortunately, the last line should have been:

`Game_Settings game_settings = Game_Settings ( );`

Without that line, game_settings was null and the exception occurred. 

I do not know what semantic analysis is performed by flutter/dart. In other environments, this programmer error might have been caught by the compiler not as a run-time exception. Also, the message **The getter 'className' was called on null** is not really helpful insofar as the are a large number of classes in the code. Even if the error detecting of the compiler cannot be strengthened, at least the error message should be repaired.

**Comment by zoechi** [comment]
> FileSystemException: FileSystemException: Deletion failed, path = 'C:\Gustafson\flutter\navigation_basics\build\app\intermediates\flutter\debug/flutter_assets' (OS Error: The directory is not empty.
, errno = 145)

Actually I find the error message quite helpful.
This directory is not supposed to be used by other tools and the OS doesn't tell why it didn't delete the directory.

> this programmer error might have been caught by the compiler not as a run-time exception.

this will probably be covered when and if Dart gets non-nullable types (which are considered for Dart 3.0)

> The getter 'className' was called on null

It's not clear to me where this error comes from.
Perhaps a dup of #19347 but there is no easy way to reproduce.  
I didn't have time to have a closer look at https://github.com/flutter/flutter/issues/19347#issuecomment-416988611

**Comment by gggustafson** [comment]
Thanks. I'll close
