### ISSUE TITLE
Application works on iOS and Android emulators but fails on Android device (One Plus 6)

### ISSUE THREAD

**Issue by GyuriMajercsik** [flutter/flutter#23723]
```
Launching lib/main.dart on ONEPLUS A6003 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device ONEPLUS A6003...
I/flutter ( 7937): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7937): The following assertion was thrown during performLayout():
I/flutter ( 7937): 'package:flutter/src/rendering/table.dart': Failed assertion: line 882 pos 16: 'tableWidth >=
I/flutter ( 7937): targetWidth': is not true.
I/flutter ( 7937): 
I/flutter ( 7937): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7937): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7937): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7937):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7937): 
I/flutter ( 7937): When the exception was thrown, this was the stack:
I/flutter ( 7937): #2      RenderTable._computeColumnWidths (package:flutter/src/rendering/table.dart:882:16)
I/flutter ( 7937): #3      RenderTable.performLayout (package:flutter/src/rendering/table.dart:1000:33)
I/flutter ( 7937): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #5      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 7937): #6      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 7937): #7      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 7937): #8      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 7937): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #13     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter ( 7937): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #30     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
I/flutter ( 7937): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #32     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 7937): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #34     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter ( 7937): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter ( 7937): #46     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter ( 7937): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter ( 7937): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 7937): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 7937): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
I/flutter ( 7937): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 7937): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7937): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7937): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 7937): #56     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 7937): #57     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 7937): #58     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 7937): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 7937): 
I/flutter ( 7937): The following RenderObject was being processed when the exception was fired:
I/flutter ( 7937):   RenderTable#8a02a relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):   creator: Table ← GameMap ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ←
I/flutter ( 7937):   AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#a1071 ink
I/flutter ( 7937):   renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter ( 7937):   AnimatedPhysicalModel ← ⋯
I/flutter ( 7937):   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
I/flutter ( 7937):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=734.1)
I/flutter ( 7937):   size: MISSING
I/flutter ( 7937):   default column width: FlexColumnWidth(1.0)
I/flutter ( 7937):   table size: 6×6
I/flutter ( 7937):   column offsets: unknown
I/flutter ( 7937):   row offsets: []
I/flutter ( 7937): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 7937):   RenderSemanticsGestureHandler#7c26b NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):     RenderPointerListener#1688f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):       RenderConstrainedBox#ac049 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):         RenderStack#ee614 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#e82af NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#59864 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#9977c NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#e02b3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#2cbcc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):   RenderSemanticsGestureHandler#6bc75 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):     RenderPointerListener#5892a NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):       RenderConstrainedBox#fc16f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):         RenderStack#f32a9 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#c9e43 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#9a777 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#1dfc9 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#78d1f NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):   RenderSemanticsGestureHandler#1e578 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):     RenderPointerListener#df696 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):       RenderConstrainedBox#01498 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):         RenderStack#0d3fa NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#eefea NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#f81b4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#41c66 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#a8c76 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937):           RenderConstrainedBox#d397e NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7937): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7937): Another exception was thrown: RenderBox was not laid out: RenderTable#8a02a relayoutBoundary=up1 NEEDS-PAINT
I/flutter ( 7937): Another exception was thrown: 'package:flutter/src/rendering/table.dart': Failed assertion: line 1127 pos 12: '_rowTops.length == rows + 1': is not true.
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
W/1.gpu   ( 7937): type=1400 audit(0.0:2178334): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17724 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7937): type=1400 audit(0.0:2178335): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17724 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7937): type=1400 audit(0.0:2178336): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17724 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7937): type=1400 audit(0.0:2178337): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17724 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7937): type=1400 audit(0.0:2178338): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=17724 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
I/chatty  ( 7937): uid=10246(com.mjk.rigy.connections) RenderThread identical 14 lines
E/libc    ( 7937): Access denied finding property "vendor.debug.egl.swapinterval"
E/flutter ( 7937): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 7937): Cannot hit test a render box that has never been laid out.
E/flutter ( 7937): The hitTest() method was called on this RenderBox:
E/flutter ( 7937):   RenderStack#6bb8f NEEDS-LAYOUT NEEDS-PAINT
E/flutter ( 7937): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter ( 7937): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1899:11)
E/flutter ( 7937): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1922:6)
E/flutter ( 7937): #2      _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 7937): #3      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:365:12)
E/flutter ( 7937): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #9      RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1655:18)
E/flutter ( 7937): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #16     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2780:37)
E/flutter ( 7937): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #20     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2413:18)
E/flutter ( 7937): #21     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2393:12)
E/flutter ( 7937): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 7937): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 7937): #28     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:2890:31)
E/flutter ( 7937): #29     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 7937): #30     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:595:12)
E/flutter ( 7937): #31     RenderBox
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and a minimal runnable example that allows to reproduce.

Could be depend on the screen width. 
Perhaps it's smaller on the phone than on the emulator you are using.

**Comment by GyuriMajercsik** [comment]
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-RO)
    • Flutter version 0.9.4 at /Users/gyuri/Apps/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/gyuri/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone XS Max             • D78EC3C4-0079-4C65-84A0-0255A52EB461 • ios         • iOS 12.0 (simulator)

**Comment by GyuriMajercsik** [comment]
I will also try to come with a useful example.

**Comment by GyuriMajercsik** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: Table(
        children: _buildRows(),
      ),
    );
  }

  List<TableRow> _buildRows() {
    Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5, 6, 7, 8],
      2: [1, 2, 3, 4, 5, 6, 7, 8],
      3: [1, 2, 3, 4, 5, 6, 7, 8],
      4: [1, 2, 3, 4, 5, 6, 7, 8],
      5: [1, 2, 3, 4, 5, 6, 7, 8],
      6: [1, 2, 3, 4, 5, 6, 7, 8],
      7: [1, 2, 3, 4, 5, 6, 7, 8],
      8: [1, 2, 3, 4, 5, 6, 7, 8],
    };

    List<TableRow> rows = List();

    input.forEach((key, value) {
      rows.add(TableRow(
          children: value.map((nr) {
        return SizedBox(
          width: 90.0,
          height: 90.0,
          child: Text('$nr'),
        );
      }).toList()));
    });

    return rows;
  }
}

```

**Comment by GyuriMajercsik** [comment]
After playing with the input values I found the following. 

- **it works in case the input is:** 
```
Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5,],
    };
```

- **the crash happens  if the input is :** 

```
Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5, 6],
    };
```

- **it works if the input is:** 
```
Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5, 6, 7],
    };
```

- **a blank screen shows up, without any error if the input is:** 

```
Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5, 6, 7, 8],
    };
```

**Comment by sosospicy** [comment]
The same table error shows on Iphone 6 Plus too...

**Comment by zoechi** [comment]
Can you please check if you can still reproduce in `master` channel after #27112 ?

**Comment by sosospicy** [comment]
@zoechi 
Thank you for your quick response. Unfortunately it failed again.
What i've done:
Upgrade flutter:
`flutter channel master
flutter upgrade`

Then check version:
`flutter --version
Flutter 1.1.10-pre.206 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1d773ace3f (27 minutes ago) • 2019-01-29 09:23:27 +0100
Engine • revision 9b6d5031a3
Tools • Dart 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)`

Error:
`Launching lib/main.dart on Dev Iphone6p in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:***
                                                                                                                                                                                                                   ├─Assembling Flutter resources...                           1.5s
 └─Compiling, linking and signing...                        14.4s
Xcode build done.                                           31.2s
Installing and launching...                                        22.7s
 3,604ms (!)
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Dev Iphone6p is available at: http://127.0.0.1:1024/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/table.dart': Failed assertion: line 882 pos 16: 'tableWidth >=
flutter: targetWidth': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderTable._computeColumnWidths (package:flutter/src/rendering/table.dart:8`

**Comment by zoechi** [comment]
@sosospicy thanks for checking.

**Comment by GyuriMajercsik** [comment]
I can confirm that it is still reproducing on version **1.0.0** and **master** as well. 

On **master** there is a slight difference: 

In case of the following input (with the test app I posted before): 
```
Map<int, List<int>> input = {
      1: [1, 2, 3, 4, 5, 6, 7, 8],
    };
```
On **1.0.0** a blank screen appears, but on **master** is the following: 

<img width="183" alt="screenshot 2019-01-29 at 12 49 19" src="https://user-images.githubusercontent.com/1482221/51903195-5352ac80-23c4-11e9-9ac5-7da2844e5f27.png">

**Comment by zoechi** [comment]
@GyuriMajercsik current master is `v1.1.10-pre.205` though, not `1.0.0` (just to be sure)

**Comment by GyuriMajercsik** [comment]
I tried on both channels: **stable** and **master**. 
Just making sure it's still reproducing on **stable** ( 1.0.0 ) before trying it on **master**.

**Comment by sosospicy** [comment]
For me this error came out when I use `FlexColumnWidth` to set table column width.  When I replace it with another implementer of TableColumnWidth: `FractionColumnWidth`, the render exception gone and finally got a happy ending~

**Comment by bang88** [comment]
This stop me publish an app for Android user.

**Comment by Shathin** [comment]
I have same error in the debug version of the application on my One Plus 5. But the screen renders properly on the release version of the application on the same device.

**Comment by Ogiwara-CostlierRain464** [comment]
Both `FlexColumnWidth` and `FractionColumnWidth` didn't work for me, and I finally chose `FixedColumnWidth`.

**Comment by darrenaustin** [comment]
I was able to reproduce this problem using the above sample code on an Android emulator with Pixel 2 profile running Pie. From where it was tripping the assertion, it might be a floating point rounding issue. Needs more investigation.

**Comment by chunhtai** [comment]
I think it is the rounding issue, This has happened in other place as well. It tripped with
tableWidth 411.4285714285714 targetWidth 411.42857142857144

I will put up a pr to fix it

**Comment by mleonhard** [comment]
@chunhtai Thanks for this fix.  It unblocked me. :)
