### ISSUE TITLE
error compiling even the demo test

### ISSUE THREAD

**Issue by imnick002** [flutter/flutter#23739]
```
[hello] flutter create hello
Waiting for another flutter command to release the startup lock...
Creating project hello...
  hello\.gitignore (created)
  hello\.idea\libraries\Dart_SDK.xml (created)
  hello\.idea\libraries\Flutter_for_Android.xml (created)
  hello\.idea\modules.xml (created)
  hello\.idea\runConfigurations\main_dart.xml (created)
  hello\.idea\workspace.xml (created)
  hello\.metadata (created)
  hello\android\app\build.gradle (created)
  hello\android\app\src\main\java\com\example\hello\MainActivity.java (created)
  hello\android\build.gradle (created)
  hello\android\app\src\main\AndroidManifest.xml (created)
  hello\android\app\src\main\res\drawable\launch_background.xml (created)
  hello\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 8d9ea2e1563ace08)
Crash report written to C:\Users\Nick\Documents\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1
```

**Comment by imnick002** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create hello

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Nick\Documents\hello\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\Nick\flutter\packages\flutter_tools\templates\create\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.copySync (dart:io/file_impl.dart:352:5)
#2      _LocalFile&LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:29:50)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:167:18)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#5      Template.render (package:flutter_tools/src/template.dart:109:24)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:364:21)
#7      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:305:23)
<asynchronous suspension>
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:172:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.376], locale en-IN)
    • Flutter version 0.9.4 at C:\Users\Nick\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Nick\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\Nick\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at C:\Users\Nick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Can you please try restarting your computer.

> Waiting for another flutter command to release the startup lock...

and 

> FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Nick\Documents\hello\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\Nick\flutter\packages\flutter_tools\templates\create\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

indicate that multiple processes are trying to access the same files.

Also please ensure you have the licenses accepted

>   ✗ Android license status unknown.

try `flutter doctor --licenses` or `sdkmanager --licenses`

**Comment by zoechi** [comment]
related/follow-up to #23722

**Comment by imnick002** [comment]
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
Please review your Gradle project setup in the android/ folder.

**Comment by zoechi** [comment]
Merging with #23404
