### ISSUE TITLE
The following assertion was thrown during paint():

### ISSUE THREAD

**Issue by Rohan-Amit** [flutter/flutter#23734]
```
flutter: #2      _rectIsValid (dart:ui/painting.dart:26:10)
flutter: #3      Canvas.drawImageRect (dart:ui/painting.dart:3272:12)
flutter: #4      paintImage (package:flutter/src/painting/decoration_image.dart:438:14)
flutter: #5      RenderImage.paint (package:flutter/src/rendering/image.dart:339:5)
flutter: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #11     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #14     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
flutter: #15     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
flutter: #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #18     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
flutter: #19     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:360:5)
flutter: #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #23     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:472:11)
flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #27     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1709:88)
flutter: #28     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:29:12)
flutter: #29     ClipContext.clipRRectAndPaint (package:flutter/src/painting/clip.dart:49:5)
flutter: #30     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1709:17)
flutter: #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:13)
flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2085:7)
flutter: #38     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
flutter: #39     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
flutter: #40     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:852:29)
flutter: #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:272:19)
flutter: #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
flutter: #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #47     _invoke (dart:ui/hooks.dart:139:13)
flutter: #48     _drawFrame (dart:ui/hooks.dart:128:3)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderImage#a7ecd relayoutBoundary=up4
flutter:   creator: RawImage ← Semantics ← Image ← Align ← Container ← Expanded ← Column ← Container ←
flutter:   MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=541.3)
flutter:   size: Size(150.0, 200.0)
flutter:   image: [397×150]
flutter:   width: 150.0
flutter:   height: 200.0
flutter:   scale: 0.0
flutter:   alignment: center
flutter:   invertColors: false
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Rect argument contained a NaN value.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and a minimal runnable reproduction.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
