### ISSUE TITLE
"NoSuchMethodError: The method 'removeLocalHistoryEntry' was called on null." when closing BottomSheet

### ISSUE THREAD

**Issue by JannikJung** [flutter/flutter#23743]
Hello,

I am trying to implement a PersitentBottomSheet (which should be used to select filters for a query).
As I am using this widget in two parts of my app, I created a new Widget (FilterWidget, see below) which I pass to the showBottomSheet() method.

I can open the BottomSheet without a problem. As soon as I slide it downwards to close it, I get the following Error:

```
[        ] E/flutter (11691): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
[        ] E/flutter (11691): NoSuchMethodError: The method 'removeLocalHistoryEntry' was called on null.
[        ] E/flutter (11691): Receiver: null
[        ] E/flutter (11691): Tried calling: removeLocalHistoryEntry(Instance of 'LocalHistoryEntry')
[        ] E/flutter (11691): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
[        ] E/flutter (11691): #1      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:299:12)
[        ] E/flutter (11691): #2      _MapPageState.toggleFilterBottomSheet (package:astery/tabs/map_page.dart:156:18)
[        ] E/flutter (11691): <asynchronous suspension>
[        ] E/flutter (11691): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
[        ] E/flutter (11691): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
[        ] E/flutter (11691): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] E/flutter (11691): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
[        ] E/flutter (11691): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
[        ] E/flutter (11691): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
[        ] E/flutter (11691): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
[        ] E/flutter (11691): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
[        ] E/flutter (11691): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
[        ] E/flutter (11691): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
[        ] E/flutter (11691): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
[        ] E/flutter (11691): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
[        ] E/flutter (11691): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
[        ] E/flutter (11691): #16     _invoke1 (dart:ui/hooks.dart:153:13)
[        ] E/flutter (11691): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```

I am calling the BottomSheet like that:

```dart
toggleFilterBottomSheet() async {
    if (controller == null || await controller.closed) {
      controller = _scaffoldGlobalKey.currentState.showBottomSheet((context) {
        return filterWidget;
      });
    } else {
      controller.close();
    }
  }
```

Here is the implementation of my FilterWidget:

```dart
import 'package:flutter/material.dart';

class FilterWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new _FilterWidgetState();
  }
}

class _FilterWidgetState extends State<FilterWidget> {
  double _radius = 10.0;
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 200.0,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          Center(
            child: Slider(
              value: _radius,
              onChanged: (double value) => onChangedSlider(value),
              onChangeEnd: onChangeEndSlider(),
              divisions: 9,
              min: 10.0,
              max: 100.0,
              label: 'km',
            ),
          ),
          ),
          ),
        ],
      ),
    );
  }

  onChangedSlider(double value) {}
  onChangeEndSlider() {}
}

```

Last but not least, here is the output of flutter doctor:
```
C:\Users\janni\Development\IdeaProjects\app>flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale de-DE)
    • Flutter version 0.9.4 at C:\Users\janni\Development\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\janni\Development\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\janni\Development\Android\Sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    • All Android licenses accepted.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Users\janni\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\183.3975.18
    • Flutter plugin version 29.1.4
    • Dart plugin version 183.3975.18

[√] Connected devices (1 available)
    • MI 5 • f470f194 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
Can you please provide a complete running minimal reproduction in one `lib/main.dart` file?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ShoshaniRon** [comment]
I found a workaround, just add a boolean attribute.
`_bottomSheetController = showBottomSheet(
context: context,
builder: (context) => ....);
setState(() {
isSheetOpen = true;
});
await _bottomSheetController.closed;
setState(() {
isSheetOpen=false;
});
`
now everytime the bottom sheet will open or close this flag will change his state,
base on the state you can decide what to do.

hope it was helpful.
