### ISSUE TITLE
Flutter tries to first run the first activity instead of looking for Main?

### ISSUE THREAD

**Issue by YourFavouriteOreo** [flutter/flutter#23757]
I was trying to install https://github.com/hnvn/flutter_image_cropper which involved adding an activity to the android manifest.  However, it broke when the new activity was placed above the original activity so we assumed that flutter tries to run the new activity since it was placed higher than Main Acitivity.

At least based on this Log: 

```
String: Exit code 1 from: C:\Users\YourFavouriteOreo\AppData\Local\Android\sdk\platform-tools\adb -s LGH86090aac5bf shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.cookbook/com.yalantis.ucrop.UCropActivity:

Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.cookbook/com.yalantis.ucrop.UCropActivity (has extras) }
```

It may be a better option in the long term to find
```xml
 <intent-filter>
      <action android:name="android.intent.action.MAIN"/>
      <category android:name="android.intent.category.LAUNCHER"/>
  </intent-filter>
```
Rest of the Error Log: 
```
## command

flutter run

## exception

String: Exit code 1 from: C:\Users\YourFavouriteOreo\AppData\Local\Android\sdk\platform-tools\adb -s LGH86090aac5bf shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.cookbook/com.yalantis.ucrop.UCropActivity:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.cookbook/com.yalantis.ucrop.UCropActivity (has extras) }

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.cookbook/com.yalantis.ucrop.UCropActivity (has extras) } from null (pid=25887, uid=2000) not exported from uid 10337
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:3177)
	at com.android.commands.am.Am.runStart(Am.java:640)
	at com.android.commands.am.Am.onRun(Am.java:388)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
	at com.android.commands.am.Am.main(Am.java:121)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)


#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:440:34)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:287:54)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:262:39)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._complete (dart:async/future_impl.dart:476:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\Users\YourFavouriteOreo\Documents\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\YourFavouriteOreo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • LG H860 • LGH86090aac5bf • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
#21765 might be related

**Comment by TahaTesser** [comment]
Hi @YourFavouriteOreo 
Given the mentioned issues are closed

If you're still experiencing this issue
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
I will reopen it 
Thank you
