### ISSUE TITLE
 Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.

### ISSUE THREAD

**Issue by 2015-lizaiyang** [flutter/flutter#23761]
The environment
```
/Users/lizaiyang/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.28.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```
Code implementation
```dart
class StraightLine extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final Paint paint = new Paint()
      ..color = Colors.yellow
      ..strokeWidth = 2.0
      ..style = PaintingStyle.stroke;

    var sunImage = new NetworkImage("https://resources.ninghao.org/images/childhood-in-a-picture.jpg");
    sunImage.obtainKey(new ImageConfiguration()).then((val) {
      var load = sunImage.load(val);
      load.addListener((listener, err) async {
        await listener.image.toByteData().then((onValue) async {
          debugPrint(onValue.buffer.asUint8List().toString());
          await ui.instantiateImageCodec(onValue.buffer.asUint8List()).then((ui.Codec codec) {
            debugPrint(codec.toString());
            codec.getNextFrame().then((info){
              canvas.drawImage(info.image, size.center(Offset.zero), paint);
            });
          });
        });
      });
      debugPrint(load.toString());
    });
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/OpenGLRenderer(20020): Davey! duration=1671ms; Flags=1, IntendedVsync=1280251586188672, Vsync=1280252936188618, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1280252939798337, AnimationStart=1280252940094337, PerformTraversalsStart=1280252940487337, DrawStart=1280252973649337, SyncQueued=1280252977523337, SyncStart=1280252986056337, IssueDrawCommandsStart=1280252986765337, SwapBuffers=1280253215465337, FrameCompleted=1280253266205337, DequeueBufferDuration=35070000, QueueBufferDuration=887000, 
Syncing files to device Android SDK built for x86...
I/flutter (20020): MultiFrameImageStreamCompleter#a43d6(unresolved, 1 listener)
D/        (20020): HostConnection::get() New Host Connection established 0xe09fcbc0, tid 20064
D/EGL_emulation(20020): eglMakeCurrent: 0xe87c6160: ver 3 0 (tinfo 0xe0fd0b50)
I/flutter (20020): [107, 138, 44, 255, 105, 136, 43, 255, 103, 133, 43, 255, 104, 132, 47, 255, 106, 133, 52, 255, 109, 133, 57, 255, 108, 132, 58, 255, 107, 130, 58, 255, 103, 123, 60, 255, 103, 123, 62, 255, 103, 121, 63, 255, 102, 119, 64, 255, 104, 118, 65, 255, 103, 117, 68, 255, 102, 115, 69, 255, 103, 115, 69, 255, 103, 110, 76, 255, 102, 109, 75, 255, 101, 108, 74, 255, 101, 108, 75, 255, 100, 107, 74, 255, 100, 107, 76, 255, 100, 107, 76, 255, 100, 107, 76, 255, 99, 105, 69, 255, 98, 106, 69, 255, 97, 105, 68, 255, 94, 104, 67, 255, 92, 104, 64, 255, 89, 104, 63, 255, 88, 105, 63, 255, 87, 104, 62, 255, 88, 102, 53, 255, 89, 103, 52, 255, 87, 104, 49, 255, 83, 105, 41, 255, 77, 103, 32, 255, 71, 102, 26, 255, 69, 102, 21, 255, 69, 103, 19, 255, 66, 101, 19, 255, 64, 99, 15, 255, 61, 97, 9, 255, 58, 94, 6, 255, 56, 92, 4, 255, 54, 89, 5, 255, 52, 87, 7, 255, 50, 84, 8, 255, 46, 83, 5, 255, 47, 84, 4, 255, 51, 86, 6, 255, 53, 88, 8, 255, 56, 89, 8, 255, 60, 93, 12, 255, 65, 97, 14, 255, 68, 100, 17, 255, 70, 102, 17, 25
*****E/flutter (20020): [ERROR:flutter/lib/ui/painting/codec.cc(100)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.*****
E/flutter (20020): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (20020): Exception: operation failed
E/flutter (20020): #0      StraightLine.paint.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/lizaiyang/code/flutter-demo/flutter_app_02/lib/main.dart:144:11)
E/flutter (20020): <asynchronous suspension>
E/flutter (20020): #1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (20020): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (20020): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (20020): #4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (20020): #5      Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (20020): #6      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (20020): #7      _futurize.<anonymous closure> (dart:ui/painting.dart:3651:17)
E/flutter (20020): #8      Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1530:17)
```

**Comment by zoechi** [comment]
Is this the same on Android/iPhone, real device/emulator, different image files?

**Comment by zoechi** [comment]
Looks like you try to decode a decoded image.

This worked for me

```
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    var sunImage = new NetworkImage(
        "https://resources.ninghao.org/images/childhood-in-a-picture.jpg");
    sunImage.obtainKey(new ImageConfiguration()).then((val) {
      var load = sunImage.load(val);
      load.addListener((listener, err) async {
        setState(() => image = listener);
      });
    });
  }

  ImageInfo image;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: image != null
                  ? Padding(
                      padding: EdgeInsets.all(10.0),
                      child: CustomPaint(painter: StraightLine(image)),
                    )
                  : Text('loading ...'),
            ),
          ],
        ),
      ),
    );
  }
}

class StraightLine extends CustomPainter {
  StraightLine(this.image);

  final ImageInfo image;

  @override
  void paint(Canvas canvas, Size size) {
    final Paint paint = new Paint()
      ..color = Colors.yellow
      ..strokeWidth = 2.0
      ..style = PaintingStyle.stroke;

    canvas.drawImage(
        image.image, Offset(0 - (image.image.width / 2), 0), paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by 2015-lizaiyang** [comment]
@zoechi thank you!  I've learned。
All of the data needs to be ready by the time the frame is drawn. Using a Future in this case means the data is only available after the canvas has been rendered.

**Comment by zoechi** [comment]
yup, and this caused an exception that the object was already disposed.
I think it was `canvas.drawImage(...)` which is reasonable.

Can we close this issue?

**Comment by 2015-lizaiyang** [comment]
yes, thank you! off it!

**Comment by haipv2** [comment]
@zoechi : I get the error:
The argument type 'Future<Null> Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener' error at load.addListener. 
How can I fix it? 
Thanks a lot!!!
