### ISSUE TITLE
  HandshakeException: Handshake error in client (OS Error:      	WRONG_VERSION_NUMBER(tls_record.cc:242))

### ISSUE THREAD

**Issue by naivor** [flutter/flutter#23767]
my flutter application work fine  last  week, but  now  it  seems have some  problem,here is  the  log:

```
10-31 17:02:47.278 2658-2680/com.turing E/flutter: [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
    HandshakeException: Handshake error in client (OS Error: 
    	WRONG_VERSION_NUMBER(tls_record.cc:242))
    #0      IOClient.send (package:http/src/io_client.dart:30:23)
    <asynchronous suspension>
    #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
    <asynchronous suspension>
    #2      BaseClient.get (package:http/src/base_client.dart:34:5)
    #3      get.<anonymous closure> (package:http/http.dart:47:34)
    #4      _withClient (package:http/http.dart:167:20)
    <asynchronous suspension>
    #5      get (package:http/http.dart:47:3)
    #6      _loadDate (file:///Users/tianlai/Workspace/Turing/lib/utils/netutils.dart:110:17)
    <asynchronous suspension>
    #7      Param.loadData (file:///Users/tianlai/Workspace/Turing/lib/utils/netutils.dart:57:15)
    #8      loaddisplay (file:///Users/tianlai/Workspace/Turing/lib/utils/netutils.dart:177:17)
    #9      _HomePageState.buildTopBanner (file:///Users/tianlai/Workspace/Turing/lib/ui/home.dart:265:14)
    #10     _HomePageState.initState (file:///Users/tianlai/Workspace/Turing/lib/ui/home.dart:35:14)
    #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
    #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
    #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
    #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
    #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
    #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
    #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
    #19     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3993:11)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #21     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4901:32)
    #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
    #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4796:14)
    #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
    #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
    #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
    #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
    #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
    #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
    #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
    #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
    #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
    #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
    #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
    #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
    #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
    #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
    #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
    #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
    #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
    #45     Element.inflateWidget (package:flutt
```

and  flutter doctor  -v   :

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/tianlai/Library/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/tianlai/Library/Android/sdk
    • Android NDK at /Users/tianlai/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /Users/tianlai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 5X • 0200e3c611b4310f • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

what  i  should  do  to  solve  it?

**Comment by zoechi** [comment]
To be able to investigate we would need exact steps how to reproduce.

**Comment by naivor** [comment]
i  dont know  how  to  reproduct  it   ,  it  appears  sudden

**Comment by zoechi** [comment]
You mean it also doesn't reproduce reliably for you?

**Comment by swavkulinski** [comment]
have the same issue connecting from emulator to locally hosted nodejs express service. At the same time I am connecting successfully to local web socket created in rust.

**Comment by zoechi** [comment]
@swavkulinski can you please add the output of `flutter doctor -v`?

**Comment by swavkulinski** [comment]
Solved: - check your server if it is there and it is **https** not **http**.

my current doctor says

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by theochampion** [comment]
Am running into exactly the same issue, any update on this?

**Comment by Petit-Pas** [comment]
Me too, just happened.
If I can add some details on it, it doesn't work on my machine (or my phone, dunno), but my colleagues can make it work.

**Comment by echinsito** [comment]
I think the error is when the internet coneccion have very low latency

**Comment by rcshetty3** [comment]
Any one find a solution for this ?

**Comment by contactlutforrahman** [comment]
Please write your codes for calling http.

**Comment by andreddie81** [comment]
getting the same error, what was the solution for this??
