### ISSUE TITLE
Firebase plugin throwing exception when calling getDocuments

### ISSUE THREAD

**Issue by DanielSmith1239** [flutter/flutter#23789]
## Steps to Reproduce
Call `getDocuments` on a google Firestore query.
### It throws the following exception:
---
```
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.auth.internal.zzab.zzf(int)' on a null object reference
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.google.firebase.auth.FirebaseAuth.addIdTokenListener(Unknown Source:16)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.google.firebase.firestore.obfuscated.zzc.<init>(com.google.firebase:firebase-firestore@@17.1.1:76)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.1.1:109)
rebase:firebase-firestore@@17.1.1:51)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.1.1:87)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@17.1.1:78)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:82)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getCollectionReference(CloudFirestorePlugin.java:87)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:139)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:488)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at android.app.ActivityThread.main(ActivityThread.java:6649)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(30918): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
I/flutter (30918): PlatformException(error, Attempt to invoke virtual method 'void com.google.firebase.auth.internal.zzab.zzf(int)' on a null object reference, null)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

I have seen similar exceptions. Probably some version conflict in Gradle settings with google play services or similar.
Please search issues.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by kroikie** [comment]
@DanielSmith1239

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/589. Any further collaboration will be done there.
