### ISSUE TITLE
GridView / CustomScrollView randomly fails assert depending on childAspectRatio value and screen resolution

### ISSUE THREAD

**Issue by FViscardi** [flutter/flutter#23819]
Since tickets with similar issues are already months (or over a year) old and still open, I'll post it as separate issue:

When using GridView or CustomScrollView, any childAspectRatio (besides 1.0) has a chance to trigger this problem, due to a double precision issue:

```
I/flutter ( 5004): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5004): The following assertion was thrown during performLayout():
I/flutter ( 5004): SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".
I/flutter ( 5004): The maxPaintExtent is 208.75000000000003, but the paintExtent is 208.75000000000006. Maybe you have
I/flutter ( 5004): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter ( 5004): functions, or the clamp() method, to the paintExtent? By definition, a sliver can't paint more than
I/flutter ( 5004): the maximum that it can paint!
I/flutter ( 5004): The RenderSliver that returned the offending geometry was:
I/flutter ( 5004):   RenderSliverGrid#3a956 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5004):   creator: SliverGrid ← SliverPadding ← ShrinkWrappingViewport ← _ScrollableScope ←
I/flutter ( 5004):   IgnorePointer-[GlobalKey#78fe7] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 5004):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ffd86] ←
I/flutter ( 5004):   _ScrollSemantics-[GlobalKey#59efa] ← RepaintBoundary ← CustomPaint ← ⋯
I/flutter ( 5004):   parentData: paintOffset=Offset(20.0, 20.0) (can use size)
I/flutter ( 5004):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 5004):   scrollOffset: 0.0, remainingPaintExtent: 492.0, crossAxisExtent: 344.0, crossAxisDirection:
I/flutter ( 5004):   AxisDirection.right, viewportMainAxisExtent: 512.0, remainingCacheExtent: 742.0 cacheOrigin: 0.0 )
I/flutter ( 5004):   geometry: SliverGeometry(scrollExtent: 208.8, paintExtent: 208.8, maxPaintExtent: 208.8,
I/flutter ( 5004):   hasVisualOverflow: true, cacheExtent: 208.8)
I/flutter ( 5004):   currently live children: 0 to 11
```

To be more specific:
`I/flutter ( 5004): The maxPaintExtent is 208.75000000000003, but the paintExtent is 208.75000000000006. Maybe you have`

```
return new CustomScrollView(
	slivers: <Widget>[
		new SliverPadding(
			padding: const EdgeInsets.all( 20.0 ),
			sliver: SliverGrid.count(
				crossAxisCount:   2,
				crossAxisSpacing: 10.0,
				childAspectRatio: 4.8,
				children:         items,
			),
		),
	],
);
```

Another example:
```
		return new GridView.count(
			crossAxisSpacing: 10.0,
			childAspectRatio: 4.8,
			crossAxisCount:   2,
			children:         items,
		);
```

This problem seems to depend on screen size, as it only appears on certain emulated devices and not on others.

Since the issue comes from sliver.dart, I can't do much from the outside:

```
if (maxPaintExtent < paintExtent) {
        verify(false,
          'The "maxPaintExtent" is less than the "paintExtent".\n' +
          _debugCompareFloats('maxPaintExtent', maxPaintExtent, 'paintExtent', paintExtent) +
          'By definition, a sliver can\'t paint more than the maximum that it can paint!'
        );
      }
```

There are a number similar issues still open, that seem to have the same cause:
https://github.com/flutter/flutter/issues/11079
https://github.com/flutter/flutter/issues/16086
https://github.com/flutter/flutter/pull/16126
https://github.com/flutter/flutter/issues/16125

If it's too difficult or time consuming to fix this issue properly right now, could the assert at least be turned into a warning instead? Right now the only "solution" for me is to guess the right number for `childAspectRatio` every time I test on a different device, as I can't seem to be able to predict the Sliver's behavior :)

```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/dev1/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/dev1/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/dev1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/dev1/android-studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by jslavitz** [comment]
@FViscardi Working on this right now!

**Comment by jslavitz** [comment]
@FViscardi Can you update to the latest version of Flutter and see if you're still running into this error. Right now, on the most current version of Flutter – `Flutter version 0.10.1-pre.241` – the assert you've listed does not trigger with your example or even with a childAspectRatio of 4.8786912934048 😃. So it may have been fixed!

**Comment by FViscardi** [comment]
@jslavitz I'll test it over the next hour and let you know :) Would be fantastic, of course!

**Comment by FViscardi** [comment]
@jslavitz Hm... should 0.10.3-pre.89 work as well? I switched to the master channel and upgraded:

```
[✓] Flutter (Channel master, v0.10.3-pre.89, on Linux, locale en_US.UTF-8)
    • Flutter version 0.10.3-pre.89 at /home/dev1/flutter
    • Framework revision 1ab33ec5fb (13 hours ago), 2018-11-02 20:02:07 -0700
    • Engine revision 88cb78cdf6
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)
```

But I still manage to get the error:

```
I/flutter ( 7255): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7255): The following assertion was thrown during performLayout():
I/flutter ( 7255): SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".
I/flutter ( 7255): The maxPaintExtent is 382.70833333333337, but the paintExtent is 382.7083333333334. Maybe you have
I/flutter ( 7255): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter ( 7255): functions, or the clamp() method, to the paintExtent? By definition, a sliver can't paint more than
I/flutter ( 7255): the maximum that it can paint!
I/flutter ( 7255): The RenderSliver that returned the offending geometry was:
I/flutter ( 7255):   RenderSliverGrid#ee908 relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 7255):   creator: SliverGrid ← SliverPadding ← ShrinkWrappingViewport ← _ScrollableScope ←
I/flutter ( 7255):   IgnorePointer-[GlobalKey#77543] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 7255):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#0047a] ←
I/flutter ( 7255):   _ScrollSemantics-[GlobalKey#35570] ← RepaintBoundary ← CustomPaint ← ⋯
I/flutter ( 7255):   parentData: paintOffset=Offset(20.0, 20.0) (can use size)
I/flutter ( 7255):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 7255):   scrollOffset: 0.0, remainingPaintExtent: 492.0, crossAxisExtent: 344.0, crossAxisDirection:
I/flutter ( 7255):   AxisDirection.right, viewportMainAxisExtent: 512.0, remainingCacheExtent: 742.0 cacheOrigin: 0.0 )
I/flutter ( 7255):   geometry: SliverGeometry(scrollExtent: 382.7, paintExtent: 382.7, maxPaintExtent: 382.7,
I/flutter ( 7255):   hasVisualOverflow: true, cacheExtent: 382.7)
I/flutter ( 7255):   currently live children: 0 to 21
I/flutter ( 7255): 
I/flutter ( 7255): When the exception was thrown, this was the stack:
I/flutter ( 7255): #0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:672:9)
I/flutter ( 7255): #1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:690:15)
I/flutter ( 7255): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:702:6)
I/flutter ( 7255): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1057:21)
I/flutter ( 7255): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1636:19)
...
```

Maybe I'm doing something wrong with the upgrade? I uninstalled the app and redeployed it just to be sure it's not some weird caching issue.

**Comment by jslavitz** [comment]
@FViscardi I'm confused why we're getting different results? Can your run `Flutter upgrade` and `Flutter pub get` and `git pull upstream master` to make sure we're at the same place code wise? Do you have an example app that I can run that will give me the error? I copied the code you wrote in your first post and ran that on a device and was still able to get any error...

**Comment by FViscardi** [comment]
@jslavitz I'm terribly sorry, but I won't get more time to test it this weekend, since I need to finish some other stuff for an demo next week and can't risk fidgeting around too much with my flutter version right now. I'll let you know as soon as I get the chance to do it, sorry! Still, as far as I can tell, I'm on the latest version and everything is updated (master channel, pub get, etc).

By the way, I'm testing with a Nexus 4 API 28, 768 x 1280: xhdpi, API: 28, Android 9.0 (Google APIs), x86 - emulated via AVD in Android Studio. Ubuntu 18.04.1 LTS - I doubt that info makes any difference, but maybe that's where the problem lies?

**Comment by jslavitz** [comment]
@FViscardi No worries! I'll see if I can checkout the pre-89 version and see if there's a difference!
