### ISSUE TITLE
Running a widget example crashes flutter

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2383]
All the widget examples I've tried running this way crash on startup.

```
hansmuller@chumley:/builds/dev/flutter$ (cd /builds/dev/flutter/examples/widgets; flutter run --checked --target /builds/dev/flutter/examples/widgets/scrollbar.dart;  flutter logs)
Building flutter tool...
Using pre-built SkyShell.apk.
Starting scrollbar.dart on Nexus 5...
Showing Nexus 5 logs:
--------- beginning of crash
--------- beginning of system
W/ActivityManager:   Force finishing activity 1 org.domokit.sky.shell/.SkyActivity
--------- beginning of main
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11500)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11397)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12081)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11592)
W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by abarth** [comment]
Is this different than the other startup crash from this morning?

**Comment by HansMuller** [comment]
I don't think so. It's strange that the gallery app now starts as expected, but the widget examples do not.

**Comment by Hixie** [comment]
It's different in that this one didn't get fixed by the earlier fix.

**Comment by abarth** [comment]
Fixed in https://github.com/flutter/engine/pull/2457

Needs an engine roll.
