### ISSUE TITLE
Layout Error durring Execute

### ISSUE THREAD

**Issue by sallysat** [flutter/flutter#23843]
hi
I am new in Flutter , my page layout have some exceptions during Debug , however it is work
this is exceptions : 

```
I/flutter (23166): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23166): The following assertion was thrown during performLayout():
I/flutter (23166): type '_InternalLinkedHashMap<String, Object>' is not a subtype of type 'String'
I/flutter (23166): 
I/flutter (23166): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23166): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23166): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23166):   https://github.com/flutter/flutter/issues/new
I/flutter (23166): 
I/flutter (23166): When the exception was thrown, this was the stack:
I/flutter (23166): #0      TodoDetailStateMain.getStructuredGridCell (package:todo_app/screens/mainoptions.dart:154:60)
I/flutter (23166): #1      TodoDetailStateMain._buildpage.<anonymous closure> (package:todo_app/screens/mainoptions.dart:126:22)
I/flutter (23166): #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:258:20)
I/flutter (23166): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:783:67)
I/flutter (23166): #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter (23166): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:783:26)
I/flutter (23166): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:55)
I/flutter (23166): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (23166): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
I/flutter (23166): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:256:23)
I/flutter (23166): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
I/flutter (23166): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter (23166): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
I/flutter (23166): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:245:5)
I/flutter (23166): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:323:5)
I/flutter (23166): #15     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:543:12)
I/flutter (23166): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (23166): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (23166): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter (23166): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter (23166): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter (23166): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #44     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (23166): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #46     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:13)
I/flutter (23166): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #48     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (23166): #49     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (23166): #50     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (23166): #51     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (23166): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #56     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter (23166): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #58     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (23166): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (23166): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (23166): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)

```
this is My code section that that threw this exceptions :

```
GridView.builder(
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 3),
        padding: const EdgeInsets.all(10.0),
        itemCount: mainlist.maincatlist.length,
        itemBuilder: (BuildContext context, int index) {
          return new GridTile(
            footer: new Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  new Flexible(
                    child: new SizedBox(
                      height: 16.0,
                      width: 85.0,
                      child: new Text(
                        mainlist.maincatlist[index]["name"],
                        maxLines: 2,
                        textAlign: TextAlign.center,

                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  )
                ]),
            child: new Container(
              alignment: Alignment.center,
              height: 500.0,
                child: new Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    new SizedBox(

                      height: 85.0,
                      width: 85.0,

                  child: new FloatingActionButton(

                      child: new Row(

                        children: <Widget>[

                              new SizedBox(
                                child: new Container(
                                  padding: const EdgeInsets.only(left:10.0,right: 10.0),
                                  alignment: Alignment.center,
                                  child: new CircleAvatar(

                                    backgroundColor: Colors.white,
                                    radius: 25.0,

                                    child: new Icon(
                                        mainlist.maincatlist[index]
                                        ["icon"],
                                        size: 50.0,
                                        color: mainlist.maincatlist[index]
                                        ["color"]),
                                  ),
          ),
                              ),
                            ],
                      ),
                    onPressed: () {FirstPageOnTap(index);},tooltip: mainlist.maincatlist[index]["title"],clipBehavior: Clip.antiAlias,isExtended: true,backgroundColor: Colors.white,),

                    ),
                  ],),
            ),
          );
        },
      ),
```

**Comment by zoechi** [comment]
It looks like the issue is in your code.

The Flutter issue here is that it produces this message

> I/flutter (23166): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23166): more information in this error message to help you determine and fix the underlying cause.

but I believe this is a known issue that is planned to be addressed.

I'm therefore going to close.
Thanks for your contribution!
