### ISSUE TITLE
Code generation does not work when adding Flutter as a dependency to my annotation package

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#23845]
I am working on a Locale management tool. It uses annotations to facilitate language management. I have setup of three projects, a `translator` project with the annotation, a `translator_generator` that contains source_gen, build_runner and its configuration, and an `example` flutter app to demo.

When I add `flutter` and `flutter_localizations` to my translator `pubspec.yaml`, and just add a flutter import statement, the code generation process fails with (I wanted to have access to the `Locale` class in my annotation): 

```
➜  example git:(feature/process_annotation) ✗ flutter packages pub run build_runner build --verbose --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 327ms

Failed to launch the build script. This is likely due to a misconfigured builder definition. See the generated script at .dart_tool/build/entrypoint/build.dart to find errors.
IsolateSpawnException: Unable to spawn isolate: dart:ui:1: Error: Not found: dart:ui.
pub finished with exit code 78

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:142:32)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#10     Future._complete (dart:async/future_impl.dart:476:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

However, if I remove the Flutter dependencies and the import, the code is generated as expected.

This is my flutter doctor:

```
➜  translator.flutter git:(master) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
[✓] VS Code (version 1.28.2)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by jorgecoca** [comment]
@zoechi after reading that thread, I think it is a dup.
However, that issue is going to be open for almost a year now, and it does not seem to have even a plan for how it should be fixed. I believe this prevents currently any code generation tools to use any Flutter classes, which is a big problem IMO.
