### ISSUE TITLE
When the exception was thrown, this was the stack

### ISSUE THREAD

**Issue by wangqianjun** [flutter/flutter#23859]
```
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart:158:16)
flutter: #3      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:188:19)
flutter: #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:678:7)
flutter: #5      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:530:7)
flutter: #6      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:466:12)
flutter: #7      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:211:17)
flutter: #8      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:490:18)
flutter: #9      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1799:15)
flutter: #10     Navigator.pop (package:flutter/src/widgets/navigator.dart:1167:34)
flutter: #11     _ProjectListMainWigetState.build.<anonymous closure> (package:merchant_flutter/ui/project/project_main_list.dart:181:25)
flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:139:19)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:117:22)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:97:7)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:60:7)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:44:7)
flutter: #23     _invoke1 (dart:ui/hooks.dart:159:13)
flutter: #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#4fd96(⏮ 0.000; paused; for
flutter:   XMaterialPageRoute<dynamic>(hrd://project_main_list_100))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
I think we need a minimal runnable reproduction to investigate
and the output of `flutter doctor -v`.
