### ISSUE TITLE
clearAuthCache in GoogleSignInPlugin needs to be called off the main thread

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#23852]
I noticed this exception today:
```
Failed to handle method call
java.lang.IllegalStateException: Calling this from your main thread can lead to deadlock
    at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Preconditions.java:291)
    at com.google.android.gms.auth.GoogleAuthUtilLight.clearToken(GoogleAuthUtilLight.java:519)
    at com.google.android.gms.auth.GoogleAuthUtil.clearToken(GoogleAuthUtil.java:651)
    at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.clearAuthCache(GoogleSignInPlugin.java:408)
    at com.google.android.flutter.plugins.ssoauth.SSOAuthPlugin.onMethodCall(SSOAuthPlugin.java:118)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
    at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:327)
    at android.os.Looper.loop(Looper.java:169)
    at android.app.ActivityThread.main(ActivityThread.java:6873)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
PlatformException(error, Calling this from your main thread can lead to deadlock, null)
```

**Comment by mehmetf** [comment]
@alanrussian 

Something like this should work:

```diff
@@ -404,12 +402,27 @@ public class GoogleSignInPlugin implements MethodCallHandler {
     /** Clears the token kept in the client side cache. */
     @Override
     public void clearAuthCache(Result result, String token) {
-      try {
-        GoogleAuthUtil.clearToken(registrar.context(), token);
-        result.success(null);
-      } catch (GoogleAuthException | IOException e) {
-        result.error(ERROR_REASON_EXCEPTION, e.getMessage(), e);
-      }
+      Callable<void> clearTokenTask =
+          new Callable<void>() {
+            @Override
+            public void call() throws Exception {
+              GoogleAuthUtil.clearToken(registrar.context(), token);
+            }
+          };
+
+      backgroundTaskRunner.runInBackground(
+          clearTokenTask,
+          new BackgroundTaskRunner.Callback<void>() {
+            @Override
+            public void run(Future<void> tokenFuture) {
+              try {
+                tokenFuture.get();
+                result.success(null);
+              } catch (ExecutionException e) {
+                result.error(ERROR_REASON_EXCEPTION, e.getCause().getMessage(), null);
+              }
+            }
+          });
     }
```

Please test out and let me know if it works.

**Comment by mehmetf** [comment]
Closed via https://github.com/flutter/plugins/pull/889
