### ISSUE TITLE
flutter run build.gradle error

### ISSUE THREAD

**Issue by msal4** [flutter/flutter#23868]
## Steps to Reproduce

1. flutter create newapp
2. cd newapp
3. flutter run

## Logs

```
[  +22 ms] executing: [/home/msal/apps/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +276 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/beta
[        ] executing: [/home/msal/apps/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/home/msal/apps/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/msal/apps/flutter/] git log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92
[   +1 ms] executing: [/home/msal/apps/flutter/] git log -n 1 --pretty=format:%ar
[  +59 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[   +1 ms] executing: [/home/msal/apps/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.9.4-0-gf37c235c3
[ +167 ms] executing: /home/msal/Android/Sdk/platform-tools/adb devices -l
[  +48 ms] Exit code 0 from: /home/msal/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[ +963 ms] /home/msal/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +47 ms] ro.hardware = ranchu
[  +11 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[+1548 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[ +154 ms] Initializing gradle...
[  +52 ms] Using gradle from /home/msal/newapp/android/gradlew.
[  +35 ms] executing: /home/msal/newapp/android/gradlew -v
[+6672 ms]
                   ------------------------------------------------------------
                   Gradle 4.4
                   ------------------------------------------------------------

                   Build time:   2017-12-06 09:05:06 UTC
                   Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

                   Groovy:       2.4.12
                   Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
                   JVM:          1.8.0_192 (Oracle Corporation 25.192-b26)
                   OS:           Linux 4.14.65-1-MANJARO amd64
[        ] Initializing gradle... (completed)
[        ] Resolving dependencies...
[        ] executing: [/home/msal/newapp/android/] /home/msal/newapp/android/gradlew app:properties
[+2783 ms] Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

                   FAILURE: Build failed with an exception.

                   * Where:
                   Build file '/home/msal/newapp/android/app/build.gradle' line: 25

                   * What went wrong:
                   A problem occurred evaluating project ':app'.
                   > Could not resolve all files for configuration 'classpath'.
                      > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
                        Searched in the following locations:
                            https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                   * Get more help at https://help.gradle.org

                   BUILD FAILED in 2s
[   +3 ms] Resolving dependencies... (completed)
[   +2 ms] * Error running Gradle:
           Exit code 1 from: /home/msal/newapp/android/gradlew app:properties:
           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

           FAILURE: Build failed with an exception.

           * Where:
           Build file '/home/msal/newapp/android/app/build.gradle' line: 25

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Could not resolve all files for configuration 'classpath'.
              > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
                Searched in the following locations:
                    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 2s

[  +12 ms] "flutter run" took 12,387ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:115:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:267:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:262:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

```
Analyzing newapp...
No issues found! (ran in 13.7s)
```

```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/msal/apps/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/msal/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_192-b26)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Merging with #23404
