### ISSUE TITLE
Debugging experience has been worse since v0.10.0~

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#23872]
Not sure what the issue is but ever since a couple weeks ago my debugging experience has progressively gotten worse using flutter in visual studio code.

When I use hot reload and refresh within a few seconds I get this error and have no idea what to do about it, the debugger then crashes and I have to restart debugging:

```
TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:842:9)
<asynchronous suspension>
#1      VM.invokeRpc (package:flutter_tools/src/vmservice.dart:859:49)
<asynchronous suspension>
#2      VM.refreshViews (package:flutter_tools/src/vmservice.dart:957:25)
#3      FlutterDevice.refreshViews (package:flutter_tools/src/resident_runner.dart:87:30)
#4      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:689:41)
#5      _rootRun (dart:async/zone.dart:1120:38)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
#8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
#10     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#11     Future.wait.<anonymous closure> (dart:async/future.dart:399:22)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#17     Future._complete (dart:async/future_impl.dart:476:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#20     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#21     ServiceObject.reload (package:flutter_tools/src/vmservice.dart)
<asynchronous suspension>
#22     HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:685:41)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#30     Future.wait.<anonymous closure> (dart:async/future.dart:399:22)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Exited (255)
```

**Comment by abacaj** [comment]
So I switched to channel `dev` and this issue does not seem to manifest

**Comment by dnfield** [comment]
@Hixie, we were talking about this error impacting tests  and adding retries for that - could this actually be a Dart or Engine issue though if it's now taking longer than it used to?

**Comment by Hixie** [comment]
cc @DanTup

**Comment by Hixie** [comment]
@abacaj Do you still see this on master?

**Comment by DanTup** [comment]
@abacaj 

> When I use hot reload and refresh within a few seconds

What does `refresh` mean here?

Can you capture a log (run the `Dart: Capture Logs` command from the command palette and tick the `Flutter Run` and `Debugger (Observatory)` categories), then repro the issue and attach the log?
