### ISSUE TITLE
Serious problem with flutter 

### ISSUE THREAD

**Issue by ankit007im** [flutter/flutter#23887]
## Steps to Reproduce

I tried to run the flutter app from cmd using `flutter create repo`
and then `cd repo`
`flutter run`

After running this command the following errors are shown:

` * Error running Gradle:
           Exit code 1 from: D:\projectFlutter\repo\android\gradlew.bat app:properties:
           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'D:\projectFlutter\repo\android\app\build.gradle' line: 25

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Could not resolve all files for configuration 'classpath'.
              > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
                Searched in the following locations:
                    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s`

## Logs

  `D:\projectFlutter\repo>flutter run --verbose
[  +56 ms] executing: [C:\Users\Processing\Desktop\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +318 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/beta
[   +5 ms] executing: [C:\Users\Processing\Desktop\flutter\] git rev-parse --abbrev-ref HEAD
[ +289 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] beta
[   +5 ms] executing: [C:\Users\Processing\Desktop\flutter\] git ls-remote --get-url origin
[ +218 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[   +5 ms] executing: [C:\Users\Processing\Desktop\flutter\] git log -n 1 --pretty=format:%H
[ +280 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92
[   +5 ms] executing: [C:\Users\Processing\Desktop\flutter\] git log -n 1 --pretty=format:%ar
[ +302 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 5 weeks ago
[   +6 ms] executing: [C:\Users\Processing\Desktop\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +282 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v0.9.4-0-gf37c235c3
[ +363 ms] executing: C:\Users\Processing\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +27 ms] Exit code 0 from: C:\Users\Processing\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           ZL33B28246             device product:nicklaus_f model:Moto_E__4__Plus device:nicklaus_f transport_id:1
[ +400 ms] C:\Users\Processing\AppData\Local\Android\sdk\platform-tools\adb -s ZL33B28246 shell getprop
[ +143 ms] ro.hardware = mt6735
[   +2 ms] ro.build.characteristics = default
[ +728 ms] Launching lib/main.dart on Moto E 4 Plus in debug mode...
[  +38 ms] Initializing gradle...
[   +2 ms] Using gradle from D:\projectFlutter\repo\android\gradlew.bat.
[ +106 ms] executing: D:\projectFlutter\repo\android\gradlew.bat -v
[ +757 ms]
                   ------------------------------------------------------------
                   Gradle 4.4
                   ------------------------------------------------------------

                   Build time:   2017-12-06 09:05:06 UTC
                   Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

                   Groovy:       2.4.12
                   Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b06)
                   OS:           Windows 10 10.0 amd64
[   +3 ms] Initializing gradle... (completed)
[   +1 ms] Resolving dependencies...
[   +3 ms] executing: [D:\projectFlutter\repo\android\] D:\projectFlutter\repo\android\gradlew.bat app:properties
[+1307 ms] Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

                   FAILURE: Build failed with an exception.

                   * Where:
                   Build file 'D:\projectFlutter\repo\android\app\build.gradle' line: 25

                   * What went wrong:
                   A problem occurred evaluating project ':app'.
                   > Could not resolve all files for configuration 'classpath'.
                      > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
                        Searched in the following locations:
                            https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                   * Get more help at https://help.gradle.org

                   BUILD FAILED in 1s
[  +15 ms] Resolving dependencies... (completed)
[   +6 ms] * Error running Gradle:
           Exit code 1 from: D:\projectFlutter\repo\android\gradlew.bat app:properties:
           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'D:\projectFlutter\repo\android\app\build.gradle' line: 25

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Could not resolve all files for configuration 'classpath'.
              > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
                Searched in the following locations:
                    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s

[  +51 ms] "flutter run" took 3,628ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:115:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:267:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:262:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)`
-->

```
```

   `D:\projectFlutter\repo>flutter analyze
Analyzing repo...
No issues found! (ran in 1.9s)`

```
```
D:\projectFlutter\repo>flutter doctor -v
       ```[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at C:\Users\Processing\Desktop\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Processing\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Processing\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected devices (1 available)
    • Moto E 4 Plus • ZL33B28246 • android-arm • Android 7.1.1 (API 25)

• No issues found!````



```
```

**Comment by ankit007im** [comment]
I am facing this error with every flutter app

**Comment by diegoveloper** [comment]
This is already fixed on master/dev channels , I think it's still pending on beta channel : 
https://github.com/flutter/flutter/pull/23397
