### ISSUE TITLE
Oops flutter has exited unexpectedly

### ISSUE THREAD

**Issue by LevQo** [flutter/flutter#23909]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-version-check doctor

## exception

ArgumentError: Invalid argument(s): join(null, "Programs\Microsoft VS Code"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1088:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:136:38)
#3      VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:79:14)
#4      VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20:10)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:59:44)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:97:46)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:104:39)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:162:41)
<asynchronous suspension>
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:29:39)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#17     Future._complete (dart:async/future_impl.dart:476:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 0.9.4 at D:\Soft\FlutterSDK\flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.0
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

• No issues found!
```

**Comment by DanTup** [comment]
@LevQo Are you on Windows 7?

Can you open a command prompt and type `echo %LocalAppData%` (or in PowerShell `$env:LocalAppData`)?

It seems like your `LocalAppData` environment variable might not be set, but it has [apparently](http://environmentvariables.org/LocalAppData) been around since Windows Vista.

**Comment by LevQo** [comment]
@DanTup Yes, Windows 7.
`echo %LocalAppData%` Nothing happens.

**Comment by LevQo** [comment]
@DanTup Thanks. It works.

**Comment by LevQo** [comment]
@DanTup Yes, i added `%LocalAppData%` and `%AppData%`.

**Comment by DanTup** [comment]
@LevQo Do you know why they weren't already set?

I've pushed a fix to avoid the crash in this case (though it won't find the user-scoped VS Code install if this is the case, since it doesn't know where to look).
