### ISSUE TITLE
Can't run Google Maps Flutter plugin

### ISSUE THREAD

**Issue by braulio94** [flutter/flutter#23911]
## Steps to Reproduce
 
1. Install [Google Maps Flutter plugin](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter) including the Google Maps key
2. Copy the code in the [Getting started guide](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter#getting-started)
3. Run the project

## Logs

![screenshot-1541260394973](https://user-images.githubusercontent.com/20057010/47954513-13c62100-df8b-11e8-9ce0-1a745565eb07.jpg)

```
[ +132 ms] I/flutter (29191): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +18 ms] I/flutter (29191): The following _CompileTimeError was thrown building GoogleMap(dirty, state: _GoogleMapState#5fffc):
[        ] I/flutter (29191): 'file:///C:/Users/Braulio/AppData/Roaming/Pub/Cache/git/plugins-5b45f58ccab7009d473d6c767e9e40ddcabedde3/packages/google_maps_flutter/lib/src/google_map.dart':
[        ] I/flutter (29191): error: line 42 pos 36:
[        ] I/flutter (29191): file:///C:/Users/Braulio/AppData/Roaming/Pub/Cache/git/plugins-5b45f58ccab7009d473d6c767e9e40ddcabedde3/packages/google_maps_flutter/lib/src/google_map.dart:42:36:
[        ] I/flutter (29191): Error: The argument type 'dart.core::Set<invalid-type>' can't be assigned to the parameter type
[        ] I/flutter (29191): 'dart.core::List<#lib1::OneSequenceGestureRecognizer>'.
[        ] I/flutter (29191): Try changing the type of the parameter, or casting the argument to
[        ] I/flutter (29191): 'dart.core::List<#lib1::OneSequenceGestureRecognizer>'.
[        ] I/flutter (29191):         gestureRecognizers: widget.gestureRecognizers,
[        ] I/flutter (29191):                                    ^
[        ] I/flutter (29191):         gestureRecognizers: widget.gestureRecognizers,
[        ] I/flutter (29191):                                    ^
[  +17 ms] I/flutter (29191): 
[        ] I/flutter (29191): When the exception was thrown, this was the stack:
[  +32 ms] I/flutter (29191): #0      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
[        ] I/flutter (29191): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
[        ] I/flutter (29191): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #3      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #24     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3967:11)
[        ] I/flutter (29191): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #26     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4771:32)
[        ] I/flutter (29191): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #116    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[ +995 ms] I/flutter (29191): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[   +2 ms] I/flutter (29191): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #151    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #157    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #166    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #167    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
[        ] I/flutter (29191): #168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #177    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #178    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #179    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
[        ] I/flutter (29191): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
[        ] I/flutter (29191): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
[        ] I/flutter (29191): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
[        ] I/flutter (29191): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
[        ] I/flutter (29191): #190    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4449:32)
[        ] I/flutter (29191): #191    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
[        ] I/flutter (29191): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #193    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
[        ] I/flutter (29191): #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #197    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
[        ] I/flutter (29191): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #200    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #201    ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
[        ] I/flutter (29191): #202    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #203    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
[        ] I/flutter (29191): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #206    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #207    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
[        ] I/flutter (29191): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #209    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
[        ] I/flutter (29191): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #211    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
[        ] I/flutter (29191): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
[        ] I/flutter (29191): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
[        ] I/flutter (29191): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
[        ] I/flutter (29191): #215    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
[        ] I/flutter (29191): #216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
[        ] I/flutter (29191): #217    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[        ] I/flutter (29191): #218    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter (29191): #219    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter (29191): #220    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
[        ] I/flutter (29191): #221    _invoke (dart:ui/hooks.dart:128:13)
[        ] I/flutter (29191): #222    _drawFrame (dart:ui/hooks.dart:117:3)
[        ] I/flutter (29191): ════════════════════════════════════════════════════════════════════════════════════════════════════
[
```

**Comment by 5ummit** [comment]
Didn't even know it has been publicly available, maybe try and create a project with it? (Try to use another widget dedicated for the `maps` package and a main widget for an appbar and container for example)

**Comment by braulio94** [comment]
@5ummit I can use it now. Heads-up, use flutter in the master channel so you don't run into the same problems I did. 

 

> 1. Install [Google Maps Flutter plugin](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter)

![screenshot-1541401464549](https://user-images.githubusercontent.com/20057010/47997204-53137f80-e0fb-11e8-8fe9-04427466cdd3.jpg)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by braulio94** [comment]
It's resolved never mind!
