### ISSUE TITLE
I don't know what just happened with my app, i think it's crash...

### ISSUE THREAD

**Issue by 91priyansh** [flutter/flutter#23922]
Here is the error that i am getting 
```
I/Choreographer(14958): Skipped 299 frames!  The application may be doing too much work on its main thread.
E/flutter (14958): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (14958): PlatformException(ERROR_GEOCODING_ADDRESS, grpc failed, null)
E/flutter (14958): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (14958): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (14958): <asynchronous suspension>
E/flutter (14958): #2      Geolocator.placemarkFromAddress (package:geolocator/geolocator.dart:228:30)
E/flutter (14958): <asynchronous suspension>
E/flutter (14958): #3      HomePageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///E:/Playground/app/lib/pages/homepage.dart:53:34)
E/flutter (14958): #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (14958): #5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (14958): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (14958): #7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (14958): #8      Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (14958): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (14958): #10     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (14958): #11     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (14958): #12     Geolocator.getCurrentPosition (package:geolocator/geolocator.dart)
E/flutter (14958): <asynchronous suspension>
E/flutter (14958): #13     HomePageState.build.<anonymous closure>.<anonymous closure> (file:///E:/Playground/app/lib/pages/homepage.dart:49:32)
E/flutter (14958): #14     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (14958): #15     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (14958): #16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (14958): #17     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (14958): #18     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (14958): #19     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (14958): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (14958): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (14958): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (14958): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (14958): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (14958): #25     _invoke1 (dart:ui/hooks.dart:153:13)
E/flutter (14958): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```

**Comment by rohandkn** [comment]
I believe this means something in your code is causing heavy computation on the main thread. This processing is more heavy that what the device(or emulator) can handle. Generally, you have to look at your code for inefficiencies. Hope this helps.

**Comment by 91priyansh** [comment]
Okay I look into my code and improve my code....PlatformException(ERROR_GEOCODING_ADDRESS, grpc failed, null) do you have any idea why it is throw this exception?

**Comment by zoechi** [comment]
If this is with a release build and/or on an emulator, this doesn't necessarily mean much.
It looks like this should reported in https://github.com/baseflowit/flutter-geolocator/issues anyway.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by abumoallim** [comment]
I am having the same issue. It was working previously but suddenly it stopped working on real devices. It is working perfectly in emulators. Previously it was working with Real devices too.
