### ISSUE TITLE
GlobalObjectKey_WidgetsAppState with dirty state

### ISSUE THREAD

**Issue by Adrianogba** [flutter/flutter#23924]
## What happened

I've tried to update some newly added switches based on some data stored using shared_preferences library.

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 30.0.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

```
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

I/flutter ( 2193): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter ( 2193): _WidgetsAppState#862d6](dirty, state: NavigatorState#12070(tickers: tracking 4 tickers)):
I/flutter ( 2193): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1946 pos 12: '!_debugLocked':
I/flutter ( 2193): is not true.
I/flutter ( 2193): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2193): more information in this error message to help you determine and fix the underlying cause.
```

## Stack

```
When the exception was thrown, this was the stack:
I/flutter ( 2193): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:1946:12)
I/flutter ( 2193): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter ( 2193): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter ( 2193): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 2193): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 2193): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #22     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter ( 2193): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 2193): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 2193): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 2193): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 2193): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 2193): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter ( 2193): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter ( 2193): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter ( 2193): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter ( 2193): #64     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 2193): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter ( 2193): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 2193): #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2193): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2193): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 2193): #71     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 2193): #72     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 2193): #73     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 2193): (elided 3 frames from class _AssertionError and package dart:async)
```

## Code

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:sindico_amigo_2_flutter/models/usuario.dart';

import 'package:sindico_amigo_2_flutter/widgets/loading.dart';

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';

import 'package:sindico_amigo_2_flutter/widgets/appbar.dart';
import 'package:sindico_amigo_2_flutter/pages/page_mudeasenha.dart';

class PageMais extends StatefulWidget {
  bool isSindico;

  PageMais(this.isSindico);

  @override
  State<StatefulWidget> createState() {
    var state = new PageMaisState();
    state.isSindico=this.isSindico;
    return state;
  }
}

class PageMaisState extends State<PageMais> {
  bool isSindico;

  bool recebeSms=false;
  bool recebeEmail=false;


  @override
  Widget build(BuildContext context) {
    atualizarNotificacoes();
    return appBar("Mais", isSindico, true, context, null,
        new Scaffold(
          backgroundColor: Colors.grey[200],
          body: ListView(
            children: <Widget>[
              Container(child: Padding(padding: EdgeInsets.only(left: 25.0, top: 15.0, bottom: 15.0, right: 15.0),
                  child: Text("Configurações", style: TextStyle(color: Colors.grey[900], fontSize: 16.0))),),
              new Divider(height: 1.0),
              new FlatButton(onPressed: (){

              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Receber notificações por Email"),
                      trailing: Switch(value: recebeEmail, onChanged: (bool value){})
                  )),
              new Divider(height: 1.0),

              new FlatButton(onPressed: (){

              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Receber notificações por SMS"),
                      trailing: Switch(value: recebeSms, onChanged: (bool value){})
                  )),
              new Divider(height: 1.0),

              new FlatButton(onPressed: (){
                Navigator.push(context, MaterialPageRoute(builder: (context) => PageMudarASenha(isSindico)));
              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Mudar a Senha"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),


              new FlatButton(onPressed: (){
                if(isSindico){
                  Navigator.pop(context);
                  Navigator.pop(context);
                }else{
                  //gambiarra pra sobreescrever as rotas da CupertinoTabView
                  //showDialog(context: context, builder: (context){Navigator.pop(context);Navigator.pop(context);});

                  Navigator.pop(context);
                  Navigator.pop(context);
                }


              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Sair"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),

              Container(child: Padding(padding: EdgeInsets.only(left: 25.0, top: 15.0, bottom: 15.0, right: 15.0),
                  child: Text("Ajuda", style: TextStyle(color: Colors.grey[900], fontSize: 16.0))),),

              new Divider(height: 1.0),
              new FlatButton(onPressed: (){
                var url = 'https://play.google.com/store/apps/details?id=br.com.pbsoft.sindicoamigo';
                if (Platform.isIOS) {url = 'https://itunes.apple.com/br/app/sindico-amigo-2-0/id1247549583?mt=8';}
                launch(url);

              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Avalie o App"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),
              new FlatButton(onPressed: (){
                launch("https://www.sindicoamigo.com.br/");
              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      title: Text("Saiba mais"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),

              Container(child: Padding(padding: EdgeInsets.only(left: 25.0, top: 15.0, bottom: 15.0, right: 15.0),
                  child: Text("Redes Sociais", style: TextStyle(color: Colors.grey[900], fontSize: 16.0))),),
              new Divider(height: 1.0),
              new FlatButton(onPressed: (){
                launch("https://www.facebook.com/pbsoftinfo");
              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      leading: new Icon(FontAwesomeIcons.facebook, color: Color(0xFF3b5998),),
                      title: Text("Curta-nos no Facebook"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),
              new FlatButton(onPressed: (){
                launch("https://twitter.com/pbsoftinfo");
              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      leading: new Icon(FontAwesomeIcons.twitter, color: Color(0xFF00aced)),
                      title: Text("Siga-nos no Twitter"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),
              new FlatButton(onPressed: (){
                launch("https://www.instagram.com/pbsoftinfo");
              },padding: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  color: Colors.white,
                  child: new ListTile(
                      leading: new Icon(FontAwesomeIcons.instagram, color: Color(0xFF517fa4)),
                      title: Text("Curta-nos no Instagram"),
                      trailing: Icon(Icons.keyboard_arrow_right, color: Colors.grey)
                  )),
              new Divider(height: 1.0),
              new Container(
                padding: EdgeInsets.all(15.0),
                child: Column(
                  children: <Widget>[
                    Image.asset(
                      'assets/pbsoft_logo.png',
                      height: 30.0,
                      fit: BoxFit.contain,
                      color: Colors.grey,
                    ),
                  Text("Versão: 2.1.5", style: TextStyle(color: Colors.grey),)
                  ],

                ))
            ],
          ),
        )
    );
  }
  void atualizarNotificacoes() async {
    try {
      loadingDialog(context);
      final prefs = await SharedPreferences.getInstance();
      var usuario = new Usuario.getUsuario(prefs);

      if(usuario.recebe_sms!=null&&usuario.recebe_sms.toString().toLowerCase().trim()=="s"){
        recebeSms=true;
      }

      if(usuario.recebe_email!=null&&usuario.recebe_email.toString().toLowerCase().trim()=="s"){
        recebeEmail=true;
      }
      setState(() {});
    }catch(e){

    }
  }

}
```

## flutter doctor -v

```

[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.18247.1001], locale en-US)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Custom Phone, 5 1 0, API 22, 768x1280 • 192.168.181.101:5555 • android-x86 • Android 5.1 (API 22)

• No issues found!
```

**Comment by NMateu** [comment]
it can have a relationship with doubled Navigator.pop(context) in one of the FlatButton, it can simply be closed one route too far. I had the same problem

**Comment by goderbauer** [comment]
@Adrianogba  Can you please post a minimal code sample that reproduces the problem? The posted code has a lot of external dependencies that seem irrelevant making this problem harder to debug.

**Comment by Adrianogba** [comment]
@goderbauer I think the problem was solved. After some updates this wasn't happening anymore. And it was white a while. I don't recall when, but was months ago.
