### ISSUE TITLE
AppLocalizations some time crash the app at startup

### ISSUE THREAD

**Issue by pjcau** [flutter/flutter#23920]
Hi guys, 
some times I have this issue the app startup.
My configuration is:
```
Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (6 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044
```
I use this system [https://github.com/flutter/website/tree/master/src/_includes/code/internationalization/minimal/](url) advice in [https://flutter.io/tutorials/internationalization/#defining-class](url) .

```
Starting Xcode build...
Xcode build done.                                            9.5s
flutter: initState - value is true
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building FutureBuilder<bool>(dirty, state:
flutter: _FutureBuilderState<bool>#ce877):
flutter: The getter 'splashDescription' was called on null.
flutter: Receiver: null
flutter: Tried calling: splashDescription
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      _SplashPageState.loadSplashPage (package:baby_learn_with_game/Screen/splash.dart:117:47)
flutter: #2      _SplashPageState.build.<anonymous closure> (package:baby_learn_with_game/Screen/splash.dart:76:30)
flutter: #3      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
flutter: #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #70     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
flutter: #77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #123    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #133    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #134    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
flutter: #135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
Syncing files to device iPhone XR...
flutter: #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #139    _invoke (dart:ui/hooks.dart:139:13)
flutter: #140    _drawFrame (dart:ui/hooks.dart:128:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter:  Go to Home
flutter: Another exception was thrown: NoSuchMethodError: The getter 'appTitle' was called on null.
```

**Comment by zoechi** [comment]
Seems like an issue in your custom code.

> flutter: #1      _SplashPageState.loadSplashPage (package:baby_learn_with_game/Screen/splash.dart:117:47)

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by pjcau** [comment]
Hi the code in this line is

  ```
new Text(AppLocalizations.of(context).splashDescription,
            textScaleFactor: 1.5)
```
and suppose the AppLocalizations.of is null, because context is different because before is used, and splashDescription is a static string. Can you give support it?

**Comment by zoechi** [comment]
As mentioned it's better to ask how-to questions on StackOverflow or one of the other channels.
