### ISSUE TITLE
application with android_alarm_manager does not work in 0.10.2

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#23935]
## Problem

android alarm manager depends on firebase_auth. but if the application does not use firebase, it ends up crashing upon start due to missing firebase initialization.

## Resolution

modify android alarm manager in a way that it won't force to initialize firebase auth because alarm manager should be able to run without firebase at all.

## History

this problem can be found also in previous versions of flutter, but it could be bypassed by manually removing firebase_auth from .packages and .flutter-plugins after building but before running the app. Since 0.10.2, this workaround is no longer functioning.

## Steps to Reproduce

1. add android_alarm_manager to any project that does not use firebase
2. follow all instructions in Getting started section at https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager
3. run application

## Logs

```
11-05 07:51:40.279 28860-28860/sk.fourq.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sk.fourq.app, PID: 28860
    java.lang.RuntimeException: Unable to start activity ComponentInfo{sk.fourq.app/sk.fourq.app.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process sk.fourq.app. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process sk.fourq.app. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(SourceFile:218)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:0)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.<init>(FirebaseAuthPlugin.java:54)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.registerWith(FirebaseAuthPlugin.java:47)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:34)
        at sk.fourq.app.MainActivity.onCreate(MainActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:7036)
        at android.app.Activity.performCreate(Activity.java:7027)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
```

## FLUTTER ANALYZE

```
ethael@turbo:[~/app] flutter analyze
Running "flutter packages get" in app...                      
Analyzing app...                                              
No issues found! (ran in 6.3s)
```

## FLUTTER DOCTOR

```
ethael@turbo:[~/app] flutter doctor -v
[✓] Flutter (Channel dev, v0.10.2, on Linux, locale en_US.utf8)
    • Flutter version 0.10.2 at /opt/flutter
    • Framework revision d8cbb80206 (10 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /opt/idea
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[✓] Connected device (1 available)
    • Nokia 6 1 • PL2GAR0000000000 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by 5ummit** [comment]
@zoechi ..

**Comment by ethael** [comment]
I am not sure if I understand correctly those added labels.

1. waiting for customer response. What data do you need from me as a original reporter that is blocking you from fixing the issue?

2. milestone is set for "coming years"? does this mean it is not going to be fixed in any near future?

**Comment by zoechi** [comment]
Sorry, the "customer response" label was a mistake.
The milestone is just a preliminary pool.

**Comment by ethael** [comment]
I went through the code of both the plugin and example and there is no usage of firebase_auth besides its declaration. So I have forked the project and removed firebase_auth from pubspec.yaml and tried to run example project. It failed on:

> File google-services.json is missing. The Google Services Plugin cannot function without it.

So I also removed google-services dependency from gradle files, because it also should not be necessary to have these when using or testing the plugin. After that, the example project started and ran without issues:

> ethael@turbo:[~/Code/personal/android_alarm_manager/example] flutter run --release
> Initializing gradle...                                       0.5s
> Resolving dependencies...                                    2.2s
> Launching lib/main.dart on Nokia 6 1 in release mode...
> Gradle task 'assembleRelease'...                                 
> Gradle task 'assembleRelease'... Done                        7.6s
> Built build/app/outputs/apk/release/app-release.apk (4.8MB).
> Installing build/app/outputs/apk/app.apk...                  2.4s
> 
> To quit, press "q".
> 
> I/flutter (20253): [2018-11-07 07:14:54.503248] Hello, world! isolate=472434269 
> I/flutter (20253): [2018-11-07 07:15:45.305393] Hello, world! isolate=472434269 

Then I used this forked repo as a dependency in out project using dependency_overrides and it worked well too.

Forked repo: https://github.com/4Q-s-r-o/android_alarm_manager

**Comment by ethael** [comment]
Sorry, wrong button

**Comment by ethael** [comment]
@bkonyi @zoechi 

any chance someone will look at this in recent future? looks like a not very time consuming fix...

**Comment by Patte1808** [comment]
I created a [PR](https://github.com/flutter/plugins/pull/926) for that, maybe it'll be soon merged. :)

**Comment by bkonyi** [comment]
Sorry for the delay, must have gotten buried in my queue. I've merged the PR from @Patte1808, but I'll still need to publish a new version of the plugin before it's available on pub. I'll do that today and follow up here when it's done.
