### ISSUE TITLE
Java Plugins Fail with Kotlin Channels 

### ISSUE THREAD

**Issue by jrmarkham** [flutter/flutter#24017]
Project Builds (Kotlin fails / Java works)
https://github.com/jrmarkham/flutter_plugins_kotlin
https://github.com/jrmarkham/flutter_plugins_java 

Tech Specs: 
```
MacOS: 10.14.1
Flutter (Channel dev, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.10.2 at /usr/local/lib/flutter
    • Framework revision d8cbb80206 (12 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

IDEs: Intellij Ultimate 2018.2.5 // Android Studio 3.2.1
```

I have found that developing channels with Kotlin and using packages (that are java) causes issues. I built 2 identical projects with 2 plugins (image picker and URL launcher) both projects work before the channel is added. 

In the Java Channel project after the channel is added the project continues to work. All good.

However, in the Kotlin app once the channel is added; the plugins nor the channel works.

IntelliJ
On builds from IntelliJ I get : 
```
plugins errors and can rarely launch a test in an emulator (so I try in Android Studio):

Error:(4, 38) java: package io.flutter.plugins.imagepicker does not exist
Error:(5, 38) java: package io.flutter.plugins.urllauncher does not exist
Error:(15, 5) java: cannot find symbol
  symbol:   variable ImagePickerPlugin
  location: class io.flutter.plugins.GeneratedPluginRegistrant
Error:(16, 5) java: cannot find symbol
  symbol:   variable UrlLauncherPlugin
  location: class io.flutter.plugins.GeneratedPluginRegistrant 
```
ANDROID STUDIO
It will compile and run from Android Studio, but nothing functions here are the Logcat errors:

ON KOTLIN CHANNEL
```
2018-11-06 14:23:59.684 13854-13876/? E/flutter: [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method test on channel com.channels/test)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      _PluginUIState.channel (package:plugins_kotlin/src/screens/plugin_ui.dart:29:44)
    <asynchronous suspension>
    #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
    #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
    #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
    #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
    #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
    #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
    #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
    #15     _invoke1 (dart:ui/hooks.dart:159:13)
    #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```

ON PLUGIN (URL LAUNCHER)
```
2018-11-06 14:25:22.718 13854-13876/? E/flutter: [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      canLaunch (package:url_launcher/url_launcher.dart:88:25)
    <asynchronous suspension>
    #2      _PluginUIState.urlLaunch (package:plugins_kotlin/src/screens/plugin_ui.dart:19:15)
    <asynchronous suspension>
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
    #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
    #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
    #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
    #16     _invoke1 (dart:ui/hooks.dart:159:13)
    #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```

ON PLUGIN (IMAGE PICKER)

```
2018-11-06 14:26:19.949 13854-13876/? E/flutter: [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      ImagePicker.pickImage (package:image_picker/image_picker.dart:47:40)
    <asynchronous suspension>
    #2      _ImageGalleryUIState.selectImage (package:plugins_kotlin/src/screens/im_gal.dart:17:33)
    <asynchronous suspension>
    #3      _ImageGalleryUIState._uiControlRowWidget.<anonymous closure> (package:plugins_kotlin/src/screens/im_gal.dart:53:15)
    #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
    #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
    #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
    #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
    #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
    #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
    #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
    #17     _invoke1 (dart:ui/hooks.dart:159:13)
    #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
2018-11-06 14:26:23.154 1386-1407/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 12380003 , only wrote 12153600
```

**Comment by jrmarkham** [comment]
This is an error in my code which I copied from your documents on creating channels: 

https://flutter.io/docs/development/platform-integration/platform-channels
In Kotlin version this line of code is missing from the main block: 
 GeneratedPluginRegistrant.registerWith(this)

@dnfield found this in the iOS issue I posted.
