### ISSUE TITLE
FlutterViewController pushRoute: didn't work for multiple  paths.

### ISSUE THREAD

**Issue by ryansong** [flutter/flutter#24053]
## Steps to Reproduce

No matter what path set in `pushRoute:`  only the last widget set in routes returned. Is there any best practice or issue?
`FlutterMethodChannel` associate with  `FlutterViewController` seems can't be release for some reason,  anyone can given some idea about keeping memory or reusing the VM& environment?

```dart
  runZoned(() => runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text("11"),
      ),
      body: Container(
        child: Text("11"),
      ),
    ), // becomes the route named '/'
    routes: <String, WidgetBuilder> {
      '/followus': (BuildContext context) => FeedBackUs(),
      '/feedback': (BuildContext context) => FollowUs(),
    },
```
```

- (void)feedback {
    FlutterViewController* flutterViewController = [TBJFlutterVC new];
//    [flutterViewController setInitialRoute:@"/"];
    [flutterViewController pushRoute:@"/feedback"];
    [self.navigationController pushViewController:flutterViewController animated:YES];
}


- (void)followus {
    FlutterViewController* flutterViewController = [TBJFlutterVC new];
//    [flutterViewController setInitialRoute:@"/"];
    [flutterViewController pushRoute:@"/followus"];
    [self.navigationController pushViewController:flutterViewController animated:YES];
}

```

## Logs

```
 flutter run --verbose
[  +36 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[   +2 ms] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 2fc2581be450d72a79be6b2463fc99b2d3464b16
[   +1 ms] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%ar
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 11 hours ago
[   +2 ms] executing: [/usr/local/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +108 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v0.10.2-120-g2fc2581be
[ +349 ms] executing: /Users/ryan/Library/Android/sdk/platform-tools/adb devices -l
[  +16 ms] Exit code 0 from: /Users/ryan/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +18 ms] executing: idevice_id -h
[ +195 ms] executing: which ideviceinstaller
[  +12 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[  +15 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[  +14 ms] /usr/bin/xcrun simctl list --json devices
[ +441 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +12 ms] ryan      • d8ab5033c4855012a157889b85b098eb4779e9fc • ios • iOS 12.1.1
[   +1 ms] iPhone XR • 56CDE7F2-8616-44B1-AE83-4C2198F0CC26     • ios • iOS 12.1 (simulator)
[  +28 ms] "flutter run" took 1,002ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:248:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:378:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:334:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:325:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///usr/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
 flutter analyze
Analyzing tbj-flutter-plugin...                                  

   info • Unused import: 'dart:ui' • lib/main.dart:3:8 • unused_import

1 issue found. (ran in 2.7s)

```

```
flutter doctor -v
[✓] Flutter (Channel master, v0.10.3-pre.120, on Mac OS X 10.13.6 17G3025, locale en-CN)
    • Flutter version 0.10.3-pre.120 at /usr/local/flutter
    • Framework revision 2fc2581be4 (11 hours ago), 2018-11-06 17:24:39 -0800
    • Engine revision dda667f8f0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected device (2 available)
    • ryan      • d8ab5033c4855012a157889b85b098eb4779e9fc • ios • iOS 12.1.1
    • iPhone XR • 56CDE7F2-8616-44B1-AE83-4C2198F0CC26     • ios • iOS 12.1 (simulator)

• No issues found!

```

**Comment by dnfield** [comment]
I'm not sure I fully understand the question, but I know this issue has raised confusion for many people.

As far as holding on to the state goes, you can create a `FlutterEngine` object on the Objective C side and pass that into `FlutterViewController`'s `initWithEngine` initializer.

Can you clarify the behavior you're seeing with `pushRoute`?

**Comment by tdesc** [comment]
@dnfield could you give a hint what is correct initial sequence for route working with FlutterViewController's initWithEngine 
setInitialRoute and pushRoute seem to be completely ignored.

Sequence of actions: 

  ```
guard let engine = FlutterEngine(name: "someName", project: nil) else { preconditionFailure() }
    
        engine.run(withEntrypoint: "main")
        guard let view = FlutterViewController(engine: engine,
                                      nibName: nil,
                                      bundle: nil) else { preconditionFailure() }
        view.setInitialRoute("routeOne")
```
Call of routePush do nothing 
` view.pushRoute("routeTwo")`

Dart view only showed up with initial '/' route
Flutter 0.11.10-pre.3 • channel master

**Comment by dnfield** [comment]
If you use initWithEngind, setInitialRoute won't work.  You'll have to set up your own method channel.  See https://GitHub.com/flutter/ios_afd2app for an example.

**Comment by joshuaton** [comment]
> If you use initWithEngind, setInitialRoute won't work. You'll have to set up your own method channel. See https://GitHub.com/flutter/ios_afd2app for an example.

@dnfield the example is 404, is there another example?

**Comment by dnfield** [comment]
It lives in the examples directory of this repository now

**Comment by hyojae85** [comment]
@dnfield I'm also seeing an 404.

**Comment by jmagman** [comment]
The [documentation](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#route) discusses initial/push/pop routes:
```obj-c
FlutterEngine *flutterEngine =
    [[FlutterEngine alloc] initWithName:@"my flutter engine"];
[[flutterEngine navigationChannel] invokeMethod:@"setInitialRoute"
                                      arguments:@"/onboarding"];
[flutterEngine run];
```
```
Warning: "setInitialRoute" on the navigationChannel must be called before running your FlutterEngine in order for Flutter’s first frame to use the desired route.

Specifically, this must be called before running the Dart entrypoint. The entrypoint may lead to a series of events where runApp builds a Material/Cupertino/WidgetsApp that implicitly creates a Navigator that might window.defaultRouteName when the NavigatorState is first initialized.

Setting the initial route after running the engine doesn’t have an effect.
```
```
 Tip: In order to imperatively change your current Flutter route from the platform side after the FlutterEngine is already running, use pushRoute() or popRoute() on the FlutterViewController.

To pop the iOS route from the Flutter side, call SystemNavigator.pop().
```
Closing for now, let us know if that doesn't answer your question.  Please file an issues you see!
