### ISSUE TITLE
failed to allocate CCPR index buffer

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#24083]
Not sure how to repro, but I just saw this:

```
D/skia    (32003): WARNING: failed to allocate CCPR index buffer. No paths will be drawn.
E/flutter (32003): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (32003): Exception: operation failed
E/flutter (32003): #0      OffsetLayer.toImage (package:flutter/src/rendering/layer.dart:798:14)
E/flutter (32003): <asynchronous suspension>
E/flutter (32003): #1      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2620:18)
E/flutter (32003): #2      _DiagramFlutterBinding.takeSnapshot (package:diagram_capture/diagram_capture.dart:192:19)
E/flutter (32003): #3      DiagramController.drawDiagramToImage (package:diagram_capture/diagram_capture.dart:308:21)
E/flutter (32003): #4      DiagramController.drawDiagramToFile (package:diagram_capture/diagram_capture.dart:329:37)
E/flutter (32003): <asynchronous suspension>
E/flutter (32003): #5      ContainerDiagramStep.generateDiagram (package:diagrams/src/container.dart:75:29)
E/flutter (32003): #6      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
E/flutter (32003): #7      ContainerDiagramStep.generateDiagram (package:diagrams/src/container.dart:72:31)
E/flutter (32003): #8      DiagramStep.generateDiagrams (package:diagrams/src/diagram_step.dart:42:23)
E/flutter (32003): #9      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (32003): #10     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (32003): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (32003): #12     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (32003): #13     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (32003): #14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (32003): #15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
E/flutter (32003): #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (32003): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

cc @liyuqian @chinmaygarde @cbracken

**Comment by csmartdalton86** [comment]
What the CCPR message means is the OpenGL driver failed to allocate a GPU buffer.  Could be due to a number of reasons, including memory pressure. When this happens, CCPR should just gracefully not draw.

My guess is, both the CCPR message and the exception that follows are caused by the same bad conditions in the system;  one is not caused by the other.

**Comment by jason-simmons** [comment]
I can reproduce the crash reliably by running this app:
    https://github.com/flutter/assets-for-api-docs/tree/master/packages/diagram_capture/example

This is failing because at the time of the `toImage` call the GPU thread does not have a current EGL context.  The EGL context is set within `GPUSurfaceGL::AcquireFrame`.  But if `toImage` is called before the first frame is rendered, then the GPU thread can not invoke OpenGL APIs, resulting in errors within Skia.
