### ISSUE TITLE
Gradle unable to find certification path to request target

### ISSUE THREAD

**Issue by artur855** [flutter/flutter#24107]
I need help
I created a flutter app with the command 

```bash
flutter create hello_world 
```
But i cant launch the app. I have already add the certificates to the carcets and i also have changed the configuration in the build.gradle and flutter.gradle, but the error still happens. These are de messages that are showed when i run the app.

> flutter run --verbose

```
[  +51 ms] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git rev-parse --abbrev-ref HEAD
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[   +2 ms] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git ls-remote --get-url origin
[  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 15949316053e4d342d863d586df656a6e47a67ee
[        ] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git log -n 1 --pretty=format:%ar
[  +31 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 27 hours ago
[   +1 ms] executing: [C:\Users\ARTHUR_GONCALVES\Documents\flutter\] git describe --match v*.*.* --first-parent --long
--tags
[  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.10.2-126-g159493160
[ +180 ms] executing: C:\Users\ARTHUR_GONCALVES\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +25 ms] Exit code 0 from: C:\Users\ARTHUR_GONCALVES\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_armv7 model:sdk_google_phone_armv7 device:generic
           transport_id:7
[ +353 ms] C:\Users\ARTHUR_GONCALVES\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell getprop
[ +273 ms] ro.hardware = ranchu
[  +34 ms] Using hardware rendering with device sdk google phone armv7. If you get graphics artifacts, consider enabling
software
           rendering with "--enable-software-rendering".
[ +585 ms] Launching lib/main.dart on sdk google phone armv7 in debug mode...
[  +51 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\gradlew.bat.
[ +110 ms] executing: C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\gradlew.bat -v
[ +603 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b06)
                    OS:           Windows 10 10.0 amd64
[   +2 ms] Initializing gradle... (completed)
[   +1 ms] Resolving dependencies...
[        ] executing: [C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\]
C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\gradlew.bat app:properties
[+2664 ms]
                    > Configure project :app

                    Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details
                    of the afterEvaluate {} error.

                    FAILURE: Build failed with an exception.

                    * Where:
                    Build file 'C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\app\build.gradle'
                    line: 25

                    * What went wrong:
                    A problem occurred evaluating project ':app'.
                    > Could not resolve all artifacts for configuration 'classpath'.
                       > Could not download bcpkix-jdk15on.jar (org.bouncycastle:bcpkix-jdk15on:1.56)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download bcprov-jdk15on.jar (org.bouncycastle:bcprov-jdk15on:1.56)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.2.0)
                          > Could not get resource
                          'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download jimfs.jar (com.google.jimfs:jimfs:1.1)
                          > Could not get resource
                          'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
                             > Could not HEAD 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download gson.jar (com.google.code.gson:gson:2.8.0)
                          > Could not get resource
                          'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.5.2)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.ja
                             r'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.4.5)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.0)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.ja
                          r'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0
                             .jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download antlr4.jar (org.antlr:antlr4:4.5.3)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
                             > Could not HEAD 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download juniversalchardet.jar
                       (com.googlecode.juniversalchardet:juniversalchardet:1.0.3)
                          > Could not get resource
                          'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/junivers
                          alchardet-1.0.3.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniv
                             ersalchardet-1.0.3.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.2.71)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.ja
                          r'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71
                             .jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download proguard-base.jar (net.sf.proguard:proguard-base:6.0.3)
                          > Could not get resource
                          'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download auto-value.jar (com.google.auto.value:auto-value:1.5.2)
                          > Could not get resource
                          'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download jdom2.jar (org.jdom:jdom2:2.0.6)
                          > Could not get resource 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
                             > Could not HEAD 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download commons-codec.jar (commons-codec:commons-codec:1.9)
                          > Could not get resource
                          'https://jcenter.bintray.com/commons-codec/commons-codec/1.9/commons-codec-1.9.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/commons-codec/commons-codec/1.9/commons-codec-1.9.jar'.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target
                       > Could not download jaxb-runtime.jar (org.glassfish.jaxb:jaxb-runtime:2.2.11)
                          > Could not get resource
                          'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar'.
                             > Could not HEAD
                             'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar
                             '.
                                > sun.security.validator.ValidatorException: PKIX path building failed:
                                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid
                                certification path to requested target

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
                    log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 2s
[   +9 ms] Resolving dependencies... (completed)
[   +9 ms] * Error running Gradle:
           ProcessException: Process "C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\gradlew.bat"
exited
           abnormally:

           > Configure project :app

           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the
afterEvaluate
           {} error.

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\app\build.gradle' line: 25

           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Could not resolve all artifacts for configuration 'classpath'.
              > Could not download bcpkix-jdk15on.jar (org.bouncycastle:bcpkix-jdk15on:1.56)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download bcprov-jdk15on.jar (org.bouncycastle:bcprov-jdk15on:1.56)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.2.0)
                 > Could not get resource 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
                    > Could not HEAD 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download jimfs.jar (com.google.jimfs:jimfs:1.1)
                 > Could not get resource 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
                    > Could not HEAD 'https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download gson.jar (com.google.code.gson:gson:2.8.0)
                 > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar'.
                    > Could not HEAD 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.5.2)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.4.5)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.5/httpcore-4.4.5.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.2.0)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar'.
                    > Could not HEAD
                    'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download antlr4.jar (org.antlr:antlr4:4.5.3)
                 > Could not get resource 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
                    > Could not HEAD 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download juniversalchardet.jar (com.googlecode.juniversalchardet:juniversalchardet:1.0.3)
                 > Could not get resource

'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar'
                 .
                    > Could not HEAD

'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.j
                    ar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.2.71)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar'.
                    > Could not HEAD
                    'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download proguard-base.jar (net.sf.proguard:proguard-base:6.0.3)
                 > Could not get resource
                 'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download auto-value.jar (com.google.auto.value:auto-value:1.5.2)
                 > Could not get resource
                 'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download jdom2.jar (org.jdom:jdom2:2.0.6)
                 > Could not get resource 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
                    > Could not HEAD 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download commons-codec.jar (commons-codec:commons-codec:1.9)
                 > Could not get resource
'https://jcenter.bintray.com/commons-codec/commons-codec/1.9/commons-codec-1.9.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/commons-codec/commons-codec/1.9/commons-codec-1.9.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target
              > Could not download jaxb-runtime.jar (org.glassfish.jaxb:jaxb-runtime:2.2.11)
                 > Could not get resource
                 'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar'.
                    > Could not HEAD
'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar'.
                       > sun.security.validator.ValidatorException: PKIX path building failed:
                       sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification
path to
                       requested target

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with
           --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 2s
             Command: C:\Users\ARTHUR_GONCALVES\Documents\workspace\hello_world\android\gradlew.bat app:properties

[  +28 ms] "flutter run" took 4.820ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:264:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:260:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:397:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:383:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

> flutter analyze

```
Analyzing hello_world...
No issues found! (ran in 43.5s)
```

> flutter doctor -v

```
[√] Flutter (Channel master, v0.10.3-pre.126, on Microsoft Windows [versÃ£o 10.0.17134.48], locale pt-BR)
    • Flutter version 0.10.3-pre.126 at C:\Users\ARTHUR_GONCALVES\Documents\flutter
    • Framework revision 1594931605 (27 hours ago), 2018-11-07 07:05:19 -0500
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ARTHUR_GONCALVES\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\ARTHUR_GONCALVES\Documents\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Users\ARTHUR_GONCALVES\Documents\android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • sdk google phone armv7 • emulator-5554 • android-arm • Android 7.0 (API 24) (emulator)
```

**Comment by zoechi** [comment]
Looks like #23404 just with a different dependency.
Please check the solutions and workarounds.

**Comment by zoechi** [comment]
Are you still seeing this?
