### ISSUE TITLE
ml_vision visionText error List<dynamic is not a subtype of type Map<dynamic, dynamic>

### ISSUE THREAD

**Issue by gimox** [flutter/flutter#24112]
ml_vision has error on visionText. 
The code to reproduce is the example  in ml_vision repo. 

```
[VERBOSE-2:shell.cc(188)] Dart Error: Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
#0      TextRecognizer.processImage (file:///Users/giorgiomodoni/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.2.0+1/lib/src/text_recognizer.dart:21:33)
<asynchronous suspension>
#1      TextRecognizer.detectInImage (file:///Users/giorgiomodoni/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.2.0+1/lib/src/text_recognizer.dart:39:12)
<asynchronous suspension>
#2      _TfGameState._scanImage (package:iana_mobile/src/pages/tf_game.dart:89:38)
<asynchronous suspension>
#3      _TfGameState.build.<anonymous closure> (package:iana_mobile/src/pages/tf_game.dart:163:39)
#4      _PopupMenuButtonState.showButtonMenu.<anonymous closure> (package:flutter/src/material/popup_menu.dart)
#5      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
```

```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G3025, locale it-IT)
    • Flutter version 0.10.2 at /Users/giorgiomodoni/development/flutter
    • Framework revision d8cbb80206 (13 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/giorgiomodoni/Library/Android/sdk
    • Android NDK at /Users/giorgiomodoni/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/giorgiomodoni/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone XS                 • 0339A595-2304-4EF8-BC9E-39445E1C4783 • ios         • iOS 12.1 (simulator)
```

**Comment by collinjackson** [comment]
@bparrishMines  can you check if this is fixed?

**Comment by bparrishMines** [comment]
Yea this was fixed with https://github.com/flutter/plugins/pull/899. Closing

**Comment by kroikie** [comment]
@gimox

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/581. Any further collaboration will be done there.
