### ISSUE TITLE
Custom primarySwatch (MaterialColor) in ThemeData in release mode: tried calling &()

### ISSUE THREAD

**Issue by Footurist** [flutter/flutter#24149]
Code:

```
import "package:flutter/material.dart";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
      return MaterialApp(
        theme: ThemeData(
          primarySwatch: MaterialColor(
            Colors.grey.shade200.value,
            {
              50: Colors.grey.shade50,
              100: Colors.grey.shade100,
              200: Colors.grey.shade200,
              300: Colors.grey.shade300,
              400: Colors.grey.shade400,
              500: Colors.grey.shade500,
              600: Colors.grey.shade600,
              700: Colors.grey.shade700,
              800: Colors.grey.shade800,
              900: Colors.grey.shade900
            }
          ),
        ),
        home: Scaffold(
          body: Container()
        )
      );
    }
}
```

Exception:

```
I/flutter (19080): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19080): The following NoSuchMethodError was thrown building MyApp(dirty):
I/flutter (19080): The method '&' was called on null.
I/flutter (19080): Receiver: null
I/flutter (19080): Tried calling: &()
I/flutter (19080):
I/flutter (19080): When the exception was thrown, this was the stack:
I/flutter (19080): #0      _HashBase._hashPattern (dart:collection/runtime/libcompact_hash.dart:98)
I/flutter (19080): #1      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._getValueOrData (dart:collection/runtime/libcompact_hash.dart:329)
I/flutter (19080): #2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[] (dart:collection/runtime/libcompact_hash.dart:351)
I/flutter (19080): #3      ColorSwatch.[] (package:flutter/src/painting/colors.dart:550)
I/flutter (19080): #4      MaterialColor.get:shade200 (package:flutter/src/material/colors.dart:34)
I/flutter (19080): #5      MyApp.build (file:///C:/Users/Nils/codingProjects/flutter/replica_deezer/lib/main.dart:21)
I/flutter (19080): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731)
I/flutter (19080): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678)
I/flutter (19080): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3531)
I/flutter (19080): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658)
I/flutter (19080): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653)
I/flutter (19080): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937)
I/flutter (19080): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2740)
I/flutter (19080): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:901)
I/flutter (19080): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:872)
I/flutter (19080): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:818)
I/flutter (19080): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253)
I/flutter (19080): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:817)
I/flutter (19080): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:709)
I/flutter (19080): #19     runApp (package:flutter/src/widgets/binding.dart:748)
I/flutter (19080): #20     main (file:///C:/Users/Nils/codingProjects/flutter/replica_deezer/lib/main.dart:13)
I/flutter (19080): #21     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289)
I/flutter (19080): #22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
I/flutter (19080): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter doctor:

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.16299.309], locale de-DE)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Nils\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Nils\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Nils\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected devices (1 available)
    • Redmi Note 5 • 10c5c6cf • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

The exception only occurs when running with --release. In debug mode everything works. What's the problem?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Footurist** [comment]
> Please add the output of `flutter doctor -v`.

I just added it.

**Comment by HansMuller** [comment]
I've tried this on the current "tip of tree" as well as v0.9.4 and am unable to reproduce the problem.

It looks like you've got a corrupt copy of painting/colors.dart?  The stack trace has:
```
ColorSwatch.[] (package:flutter/src/painting/colors.dart:550)
```
The 0.9.4 version of colors.dart only has 473 lines and the `operator []` definition is on line 455.

**Comment by Footurist** [comment]
> Try
> 
> git clean -xfd
> flutter doctor
>
> in the Flutter install directory to fix your Flutter install.

The copy was indeed corrupt and this worked. Thanks alot.
