### ISSUE TITLE
[11.0] Hot Reload Times out all the time on 

### ISSUE THREAD

**Issue by agrosner** [flutter/flutter#24157]
## Steps to Reproduce

1. Run my app. 
2. Make a change
3. Hot reload works once
4. Hot reload then times out next time with:
```
Unhandled exception:
TimeoutException: Request to Dart VM Service timed out: _reloadSources({pause: true, rootLibUri: file:///Users/andrewgrosner/Library/Developer/CoreSimulator/Devices/0AE4C4FA-17EE-4067-AFB7-5DF20D1D2164/data/Containers/Data/Application/5CF271D3-0C84-4D16-986B-1C93763173BD/tmp/flutter_exampleOTinPc/flutter_example/lib/main.dart.incremental.dill, packagesUri: file:///Users/andrewgrosner/Library/Developer/CoreSimulator/Devices/0AE4C4FA-17EE-4067-AFB7-5DF20D1D2164/data/Containers/Data/Application/5CF271D3-0C84-4D16-986B-1C93763173BD/tmp/flutter_exampleOTinPc/flutter_example/.packages, isolateId: isolates/15195125})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:842:9)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:1101:15)
#2      Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1148:51)
<asynchronous suspension>
#3      FlutterDevice.reloadSources (package:flutter_tools/src/resident_runner.dart:145:66)
#4      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:625:73)
<asynchronous suspension>
#5      HotRunner.restart (package:flutter_tools/src/run_hot.dart:563:24)
<asynchronous suspension>
#6      AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:810:19)
#7      AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:479:18)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:823:20)
#15     AppDomain.restart (package:flutter_tools/src/commands/daemon.dart:478:32)
<asynchronous suspension>
#16     Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)
#19     Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#26     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#27     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#34     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#35     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#44     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#45     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#46     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#54     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#55     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#56     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#57     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#58     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#59     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#60     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#61     _rootRunUnary (dart:async/zone.dart:1132:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#66     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#67     _StreamController._add (dart:async/stream_controller.dart:639:7)
#68     _StreamController.add (dart:async/stream_controller.dart:585:5)
#69     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#70     _rootRunUnary (dart:async/zone.dart:1136:13)
#71     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#72     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#73     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#74     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#75     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#76     _StreamController._add (dart:async/stream_controller.dart:639:7)
#77     _StreamController.add (dart:async/stream_controller.dart:585:5)
#78     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#79     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#80     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#81     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#82     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#83     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

### Logs

```
[✓] Flutter (Channel dev, v0.11.0, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.0 at /Users/andrewgrosner/flutter
    • Framework revision c319b890b3 (11 days ago), 2018-10-29 19:44:36 -0700
    • Engine revision 162b2e98c0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/andrewgrosner/Library/Android/sdk
    • Android NDK at /Users/andrewgrosner/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/andrewgrosner/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.4 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3 RC)
    • IntelliJ at /Users/andrewgrosner/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone XS Max • 0AE4C4FA-17EE-4067-AFB7-5DF20D1D2164 • ios • iOS 12.1 (simulator)

```

**Comment by agrosner** [comment]
It seems that it happens on 11.0 only. rolling back to 10.2 fixes the issue.

**Comment by lifenautjoe** [comment]
Same problem here! Upgraded yesterday to `11.0`.

**Comment by monmonja** [comment]
got the same issue too with 11.3 on android studio

**Comment by agrosner** [comment]
This appears fixed since I tested 1.0
