### ISSUE TITLE
Update flutter to 10.2 beta leads to application crash

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#24221]
After the last update of flutter 0.10.2 beta, my application stopped working. When application load, I see a crash, which is accompanied by the following exceptions. The constructors of some base classes are probably changed. Tell what exactly has changed so that I can adapt the application to these changes.

```
Launching lib/main.dart on SM G925I in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (17062): select = true
Syncing files to device SM G925I...
I/flutter (17062): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17062): The following NoSuchMethodError was thrown during performLayout():
I/flutter (17062): No top-level method '' declared.
I/flutter (17062): Receiver: top-level
I/flutter (17062): Tried calling: (color: Instance of 'Color', decoration: null, decorationColor: null,
I/flutter (17062): decorationStyle: null, fontWeight: null, fontStyle: null, textBaseline: null, fontFamily:
I/flutter (17062): "MaterialIcons", fontSize: 24.0, letterSpacing: null, wordSpacing: null, height: null, locale: null,
I/flutter (17062): foreground: null, background: null, shadows: null)
I/flutter (17062): When the exception was thrown, this was the stack:
I/flutter (17062): #0      TextStyle.getTextStyle (package:flutter/src/painting/text_style.dart)
I/flutter (17062): #1      TextSpan.build (package:flutter/src/painting/text_span.dart:168:31)
I/flutter (17062): #2      TextPainter.layout (package:flutter/src/painting/text_painter.dart:352:13)
I/flutter (17062): #3      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:199:18)
I/flutter (17062): #4      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:203:5)
I/flutter (17062): #5      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:269:5)
I/flutter (17062): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #7      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (17062): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (17062): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #15     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (17062): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #17     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (17062): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #19     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (17062): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #21     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (17062): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #33     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (17062): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #35     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (17062): #36     _ToolbarLayout.performLayout (package:flutter/src/widgets/navigation_toolbar.dart:124:22)
I/flutter (17062): #37     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (17062): #38     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (17062): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #40     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1097:13)
I/flutter (17062): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #43     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (17062): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #45     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (17062): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #47     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (17062): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (17062): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #58     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
I/flutter (17062): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #60     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (17062): #61     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:307:20)
I/flutter (17062): #62     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (17062): #63     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (17062): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #68     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (17062): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #85     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2880:13)
I/flutter (17062): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #87     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (17062): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #89     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #95     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #97     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #99     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (17062): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (17062): #101    RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (17062): #102    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter (17062): #103    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (17062): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (17062): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
I/flutter (17062): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (17062): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17062): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17062): #109    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (17062): failed to read FileSystemException: Exists failed, path = '/storage/emulated/0/hsmSchemes/Scheme' (OS Error: Permission denied, errno = 13)
I/flutter (17062): [basicEvents,37814240-e440-11e8-aea3-4760d7eac46b,2018-11-11 09:12:57.958,2018-11-11 09:12:57.958,(INIT(INIT description))(FINISH(FINISH description))]
I/flutter (17062): [basicEvents,37814240-e440-11e8-aea3-4760d7eac46b,2018-11-11 09:12:57.958,2018-11-11 09:12:57.958,(INIT(INIT description))(FINISH(FINISH description))]
I/flutter (17062): select = false
I/flutter (17062): #111    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (17062): #112    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (17062): #113    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (17062): (elided one frame from package dart:async)
I/flutter (17062): The following RenderObject was being processed when the exception was fired:
I/flutter (17062):   RenderParagraph#f0217 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (17062):   creator: RichText ← Center ← SizedBox ← ExcludeSemantics ← Semantics ← Icon ← IconTheme ← Builder
I/flutter (17062):   ← Align ← SizedBox ← Padding ← ConstrainedBox ← ⋯
I/flutter (17062):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (17062):   constraints: BoxConstraints(0.0<=w<=24.0, 0.0<=h<=24.0)
I/flutter (17062):   size: MISSING
I/flutter (17062):   textAlign: start
I/flutter (17062):   textDirection: ltr
I/flutter (17062):   softWrap: wrapping at box width
I/flutter (17062):   overflow: clip
I/flutter (17062):   locale: en_US
I/flutter (17062):   maxLines: unlimited
I/flutter (17062): This RenderObject has no descendants.
I/flutter (17062): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17062): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 310 pos 12: 'child.hasSize': is not true.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: RenderBox was not laid out: RenderParagraph#52d1c relayoutBoundary=up12 NEEDS-PAINT
I/flutter (17062): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#ca011 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (17062): Another exception was thrown: 'package:flutter/src/painting/box_decoration.dart': error: line 377 pos 48: file:///home/michael_k/flutter/packages/flutter/lib/src/painting/box_decoration.dart:377:48: Error: The getter 'offset' isn't defined for the class '#lib1::BoxShadow'.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: 'package:flutter/src/painting/box_shadow.dart': error: line 37 pos 14: file:///home/michael_k/flutter/packages/flutter/lib/src/painting/box_shadow.dart:37:14: Error: No named parameter with the name 'color'.
I/flutter (17062): Another exception was thrown: 'package:flutter/src/rendering/layer.dart': error: line 189 pos 15: file:///home/michael_k/flutter/packages/flutter/lib/src/rendering/layer.dart:189:15: Error: The method 'addRetained' isn't defined for the class 'dart.ui::SceneBuilder'.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: RenderBox was not laid out: RenderParagraph#52d1c relayoutBoundary=up12 NEEDS-PAINT
I/flutter (17062): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#ca011 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (17062): Another exception was thrown: 'package:flutter/src/painting/box_decoration.dart': error: line 377 pos 48: file:///home/michael_k/flutter/packages/flutter/lib/src/painting/box_decoration.dart:377:48: Error: The getter 'offset' isn't defined for the class '#lib1::BoxShadow'.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: NoSuchMethodError: No top-level method '' declared.
I/flutter (17062): Another exception was thrown: 'package:flutter/src/rendering/layer.dart': error: line 189 pos 15: file:///home/michael_k/flutter/packages/flutter/lib/src/rendering/layer.dart:189:15: Error: The method 'addRetained' isn't defined for the class 'dart.ui::SceneBuilder'.
Error -32000 received from application: Server error

```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and a minimal runnable reproduction.

**Comment by micrcx** [comment]
```
/home/michael_k/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.2)
[✓] Connected device (1 available)

• No issues found!
Process finished with exit code 0
```

**Comment by micrcx** [comment]
/home/michael_k/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.2)
[✓] Connected device (1 available)

• No issues found!
Process finished with exit code 0

**Comment by zoechi** [comment]
Does this mean you can not reproduce the issue anymore?

**Comment by micrcx** [comment]
At the moment I really can't say anything and can't reproduce the situation. But I still have 2 computers on which I did not update flutter to version 0.10.2. Therefore, all options are open.

**Comment by zoechi** [comment]
Thanks for the update, just reopen if you encounter it again.
