### ISSUE TITLE
Exception in AdjustableDropdownListTile caught by devicelab  ios_sample_catalog_generator

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#24235]
```
2018-11-11T18:27:23.665604: stdout: flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2018-11-11T18:27:23.675363: stdout: flutter: The following NoSuchMethodError was thrown building AdjustableDropdownListTile(dirty):
2018-11-11T18:27:23.675520: stdout: flutter: The method 'indexOf' was called on null.
2018-11-11T18:27:23.676237: stdout: flutter: Receiver: null
2018-11-11T18:27:23.676832: stdout: flutter: Tried calling: indexOf(null)
2018-11-11T18:27:23.677192: stdout: flutter:
2018-11-11T18:27:23.677883: stdout: flutter: When the exception was thrown, this was the stack:
2018-11-11T18:27:23.690030: stdout: flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
2018-11-11T18:27:23.691124: stdout: flutter: #1      AdjustableDropdownListTile.build (file:///Users/flutter/.cocoon/flutter/examples/catalog/lib/custom_semantics.dart:33:36)
2018-11-11T18:27:23.692011: stdout: flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3752:28)
2018-11-11T18:27:23.692961: stdout: flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
2018-11-11T18:27:23.693883: stdout: flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2018-11-11T18:27:23.694923: stdout: flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
2018-11-11T18:27:23.695783: stdout: flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
2018-11-11T18:27:23.697945: stdout: flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
2018-11-11T18:27:23.698084: stdout: flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
2018-11-11T18:27:23.698849: stdout: flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
2018-11-11T18:27:23.699761: stdout: flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
2018-11-11T18:27:23.700792: stdout: flutter: #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
2018-11-11T18:27:23.701641: stdout: flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
2018-11-11T18:27:23.702668: stdout: flutter: #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
2018-11-11T18:27:23.703564: stdout: flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
2018-11-11T18:27:23.704430: stdout: flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
2018-11-11T18:27:23.705348: stdout: flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2018-11-11T18:27:23.706257: stdout: flutter: #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
2018-11-11T18:27:23.707307: stdout: flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
2018-11-11T18:27:23.708610: stdout: flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
2018-11-11T18:27:23.709359: stdout: flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2018-11-11T18:27:23.710470: stdout: flutter: #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
2018-11-11T18:27:23.711400: stdout: flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
2018-11-11T18:27:23.712391: stdout: flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
2018-11-11T18:27:23.713450: stdout: flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2018-11-11T18:27:23.714706: stdout: flutter: #25     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
2018-11-11T18:27:23.716476: stdout: flutter: #26     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
2018-11-11T18:27:23.717945: stdout: flutter: #27     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
2018-11-11T18:27:23.719194: stdout: flutter: #28     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
2018-11-11T18:27:23.720306: stdout: flutter: #29     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
2018-11-11T18:27:23.721482: stdout: flutter: #30     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
2018-11-11T18:27:23.722166: stdout: flutter: #31     _invoke (dart:ui/hooks.dart:151:13)
2018-11-11T18:27:23.722914: stdout: flutter: #32     _drawFrame (dart:ui/hooks.dart:140:3)
2018-11-11T18:27:23.730871: stdout: flutter:
```

**Comment by jonahwilliams** [comment]
This hasn't happened in a long time
