### ISSUE TITLE
NoSuchMethodError: The method 'toLowerCase' was called on null. in release mode only

### ISSUE THREAD

**Issue by sobhi-ar** [flutter/flutter#24269]
This is happening only in release mode, debug mode doesn't give any errors, tried flutter clean but nothing changed...
It is showing the red screen with the error "The method 'toLowerCase' was called on null" (I'm not using this method at all) after splash screen immediately. 

## Logs

```
I/flutter (32478): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (32478): The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(0.0, 0.0),
I/flutter (32478): devicePixelRatio: 1.0, textScaleFactor: 1.15, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter (32478): alwaysUse24HourFormat: true, accessibleNavigation: falsedisableAnimations: falseinvertColors:
I/flutter (32478): false)):
I/flutter (32478): The method 'toLowerCase' was called on null.
I/flutter (32478): Receiver: null
I/flutter (32478): Tried calling: toLowerCase()
I/flutter (32478): When the exception was thrown, this was the stack:
I/flutter (32478): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48)
I/flutter (32478): #1      new GlobalWidgetsLocalizations. (package:flutter_localizations/src/widgets_localizations.dart:29)
I/flutter (32478): #2      GlobalWidgetsLocalizations.load (package:flutter_localizations/src/widgets_localizations.dart:56)
I/flutter (32478): #3      _WidgetsLocalizationsDelegate.load (package:flutter_localizations/src/widgets_localizations.dart:73)
I/flutter (32478): #4      _loadAll (package:flutter/src/widgets/localizations.dart:57)
I/flutter (32478): #5      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:504)
I/flutter (32478): #6      _LocalizationsState.didUpdateWidget (package:flutter/src/widgets/localizations.dart:493)
I/flutter (32478): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3796)
I/flutter (32478): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921)
I/flutter (32478): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #15     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811)
I/flutter (32478): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921)
I/flutter (32478): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921)
I/flutter (32478): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714)
I/flutter (32478): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811)
I/flutter (32478): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921)
I/flutter (32478): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811)
I/flutter (32478): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2711)
I/flutter (32478): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665)
I/flutter (32478): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3507)
I/flutter (32478): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255)
I/flutter (32478): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653)
I/flutter (32478): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208)
I/flutter (32478): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter (32478): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter (32478): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842)
I/flutter (32478): #49     _invoke (dart:ui/hooks.dart:128)
I/flutter (32478): #50     _drawFrame (dart:ui/hooks.dart:117)
I/flutter (32478): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (32478): Another exception was thrown: NoSuchMethodError: The method 'toLowerCase' was called on null.
```

_______________________________

Flutter analyze : 
```
Analyzing ...                                        

   info • The value of the field '_street' isn't used • lib/View/OrderSummaryPage.dart:22:10 • unused_field
   info • The value of the field '_incrementingPrice' isn't used • lib/View/ProductDetailsPage.dart:24:10 • unused_field

2 issues found. (ran in 9.5s)
```
_________________________

Flutter doctor :
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.7.3 at /Users/.../development/flutter
    • Framework revision 3b309bda07 (3 months ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    ...

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
It comes from this line https://github.com/flutter/flutter/blob/7245c4a6f604c0e4446c1d1fc2aeb4502bd65e21/packages/flutter_localizations/lib/src/widgets_localizations.dart#L29

It seems there is no `languageCode` in the passed `locale`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by sobhi-ar** [comment]
Thank you for your response, yes it was a mistake from me with something related to shared preferences. Now it is fixed
Thank you.

**Comment by pnirav996** [comment]
> Thank you for your response, yes it was a mistake from me with something related to shared preferences. Now it is fixed
> Thank you.

How to solve that problem. I have same.
