### ISSUE TITLE
Gridview report "EXCEPTION CAUGHT BY RENDERING LIBRARY "

### ISSUE THREAD

**Issue by huobaiyu** [flutter/flutter#24274]
My `flutter --version`

```
Flutter 0.11.4-pre.6 • channel master • https://github.com/flutter/flutter.git
Framework • revision df57dc9da9 (23 hours ago) • 2018-11-11 22:36:47 -0800
Engine • revision 5646e86a6f
Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)
```
Source Code: 
```dart
class ClassPage extends StatefulWidget {
  @override
  State createState() => new _ClassPageState();
}

class _ClassPageState extends State<ClassPage> {
  _scanQRCode(){
     // TODO: implement scan QR code.

  }
  List<Container> _buildClassGridTileList(){

    List<Image> _classFuncListIcon = [
      new Image.asset('images/application/class-notification.png'),
      new Image.asset('images/application/class-circle.png'),
      new Image.asset('images/application/class-attendance.png'),
      new Image.asset('images/application/elective-courses.png'),
      new Image.asset('images/application/home-work.png'),
    ];
    return new List.generate(
      _classFuncListIcon.length,
      (int index) { return new Container(
            width: 30.0,
            height: 30.0,
            color: Color((Random().nextDouble() * 0xFFFFFF).toInt() << 0).withOpacity(1.0),
            child:  _classFuncListIcon[index]);
      }
    );
  }

  @override
  Widget build(BuildContext context) {

    Widget _classGridView = new GridView.count(
      crossAxisCount: 4,
      padding: const EdgeInsets.all(4.0),
      mainAxisSpacing: 20.0,
      crossAxisSpacing: 4.0,
      children: _buildClassGridTileList(),     
    );

    return new Scaffold(
        appBar: new AppBar(
          title: new Text("6.5"),
          centerTitle: true,
          actions: [
            new IconButton(
              icon: new Icon(Icons.scanner), onPressed: _scanQRCode),
          ],
          
        ),
        body: new Column(
          children: [
            new Text("Class", style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, fontStyle: FontStyle.italic),),
            new Center(child: _classGridView),
          ],
        ),
    );
  }
}
```
```
erro message:
I/flutter (25256): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25256): The following assertion was thrown during performResize():
I/flutter (25256): Vertical viewport was given unbounded height.
I/flutter (25256): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter (25256): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter (25256): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter (25256): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter (25256): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter (25256): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter (25256): the height of the viewport to the sum of the heights of its children.
I/flutter (25256):
I/flutter (25256): When the exception was thrown, this was the stack:
I/flutter (25256): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1129:15)
I/flutter (25256): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1182:6)
I/flutter (25256): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
I/flutter (25256): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #19     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (25256): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #21     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (25256): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #23     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (25256): #24     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (25256): #25     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (25256): #26     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (25256): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (25256): #31     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (25256): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (25256): #33     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (25256): #34     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (25256): #35     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (25256): #36     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (25256): #37     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (25256): #38     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (25256): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (25256): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (25256): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (25256): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (25256): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (25256): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (25256): #45     _invoke (dart:ui/hooks.dart:151:13)
I/flutter (25256): #46     _drawFrame (dart:ui/hooks.dart:140:3)
I/flutter (25256):
I/flutter (25256): The following RenderObject was being processed when the exception was fired:
I/flutter (25256):   RenderViewport#ac109 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25256):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#9212b] ← Semantics ← Listener ←
I/flutter (25256):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#f475f] ←
I/flutter (25256):   _ScrollSemantics-[GlobalKey#47097] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (25256):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (25256):   parentData: <none> (can use size)
I/flutter (25256):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
I/flutter (25256):   size: MISSING
I/flutter (25256):   axisDirection: down
I/flutter (25256):   crossAxisDirection: right
I/flutter (25256):   offset: ScrollPositionWithSingleContext#63b49(offset: 0.0, range: null..null, viewport: null,
I/flutter (25256):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#54d63,
I/flutter (25256):   ScrollDirection.idle)
I/flutter (25256):   anchor: 0.0
I/flutter (25256): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (25256):   RenderSliverPadding#089ad NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25256):     RenderSliverGrid#6cf70 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25256): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderViewport#ac109 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderViewport#ac109 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#5e294 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#14f5a relayoutBoundary=up12 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#1fc39 relayoutBoundary=up11 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#6ddcb relayoutBoundary=up10 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#2e630 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#d2cb3 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#8a0f8 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b67d6 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderPositionedBox#543d9 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: RenderBox was not laid out: RenderFlex#49fc2 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (25256): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (25256): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
```

**Comment by zoechi** [comment]
Did this work in a previous Flutter version?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by huobaiyu** [comment]
I don't know. Because i  did not run my program in a previous flutter version. But I guess this problem should be easily reproduced.

**Comment by zoechi** [comment]
> I guess this problem should be easily reproduced.

> To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into lib/main.dart of a new project and run to reproduce.

It would be with a minimal reproduction

**Comment by huobaiyu** [comment]
Pls copy the following code to main.dart for reproducing the errors: 
import 'dart:math';
import 'package:flutter/material.dart';

class ClassPage extends StatefulWidget {
  @override
  State createState() => new _ClassPageState();
}

class _ClassPageState extends State<ClassPage> {

  List<Container> _buildClassGridTileList(){

    List<Text> _classFuncListIcon = [
      new Text('images/application/class-notification.png'),
      new Text('images/application/class-circle.png'),
      new Text('images/application/class-attendance.png'),
      new Text('images/application/elective-courses.png'),
      new Text('images/application/home-work.png'),
    ];
    return new List.generate(
      _classFuncListIcon.length,
      (int index) { return new Container(
            width: 30.0,
            height: 30.0,
            color: Color((Random().nextDouble() * 0xFFFFFF).toInt() << 0).withOpacity(1.0),
            child:  _classFuncListIcon[index]);
      }
    );
  }

  @override
  Widget build(BuildContext context) {

    Widget _classGridView = new GridView.count(
      crossAxisCount: 4,
      padding: const EdgeInsets.all(4.0),
      mainAxisSpacing: 20.0,
      crossAxisSpacing: 4.0,
      children: _buildClassGridTileList(),     
    );

    return new MaterialApp(
      title: 'GridView Error reproduced.',
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("GridView Error reproduced."),
          centerTitle: true,
          actions: [
            new IconButton(
              icon: new Icon(Icons.scanner),),
          ],
          
        ),
        body: new Column(
          children: [
            new Text("Class", style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, fontStyle: FontStyle.italic),),
            new Center(child: _classGridView),
          ],
        ),),
    );
  }
}

void main() {
   runApp(new ClassPage());
}

**Comment by goderbauer** [comment]
This exception is not a bug in the framework. If you place a GridView (or any ScrollView) inside a Column (or any Flex widget) the column will tell the GridView that it can be as tall as it wants to be ("unbound vertical layout constraints"). However a ScrollView needs to know how much space it has in the scroll direction in order to determine how much content is visible. That's why you're seeing the assertion. (For more Information on how this works see the "Layout algorithm" section in the [Column](https://docs.flutter.io/flutter/widgets/Column-class.html) docs)

If you replace the Center widget with an [Expanded](https://docs.flutter.io/flutter/widgets/Expanded-class.html) widget everything should work out as expected. The Expanded widget will size the GridView to take up all the remaining vertical space in the Column.
