### ISSUE TITLE
'_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true when I scroll the list quickly

### ISSUE THREAD

**Issue by shaomaicheng** [flutter/flutter#24284]
I have a Listview and every item have a animation to open a view component
when i scroll the view and item rebuilder, i have a exception like this:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Container(AlignmentDirectional.topStart, constraints:
flutter: BoxConstraints(0.0<=w<=Infinity, h=1.7), margin: EdgeInsets(8.0, 0.0, 8.0, 8.0)):
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1408 pos 14:
flutter: '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1408:14)
flutter: #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:1852:11)
flutter: #4      RenderConstrainedBox.additionalConstraints= (package:flutter/src/rendering/proxy_box.dart:212:5)
flutter: #5      ConstrainedBox.updateRenderObject (package:flutter/src/widgets/basic.dart:1849:18)
flutter: #6      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4430:12)
flutter: #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4801:11)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #33     _invoke (dart:ui/hooks.dart:128:13)
flutter: #34     _drawFrame (dart:ui/hooks.dart:117:3)
flutter: (elided 2 frames from class _AssertionError)
```

I do not know what happen, my code is very long, so .I don't have the convenience to provide  complete code

in my widget State class:

```dart
 @override
  void initState() {
    // TODO: implement initState
    super.initState();
    animationListener = () {
      setState(() {});
    };
    _initAnimation();
    if (widget.todo.showDetails) {
      show();
    }
  }
```

crash happen in  this line code:
```
 if (widget.todo.showDetails) {
      show();
    }
```

thanks for google flutter dev team

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Cflelf** [comment]
I also meet this problem. I find if I add WidgetSpan in a text, this assert must appear.
