### ISSUE TITLE
pub upgrade failed in Windows 10

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#24309]
## Steps to Reproduce

1. download beta
2. extract all
3. double click flutter_console

## Logs

```

         ######## ##       ##     ## ######## ######## ######## ########
         ##       ##       ##     ##    ##       ##    ##       ##     ##
         ##       ##       ##     ##    ##       ##    ##       ##     ##
         ######   ##       ##     ##    ##       ##    ######   ########
         ##       ##       ##     ##    ##       ##    ##       ##   ##
         ##       ##       ##     ##    ##       ##    ##       ##    ##
         ##       ########  #######     ##       ##    ######## ##     ##


 WELCOME to the Flutter Console.
 ================================================================================

 Use the console below this message to interact with the "flutter" command.
 Run "flutter doctor" to check if your system is ready to run Flutter apps.
 Run "flutter create <app_name>" to create a new Flutter project.

 Run "flutter help" to see all available commands.

 Want to use an IDE to interact with Flutter? https://flutter.io/ide-setup/

 Want to run the "flutter" command from any Command Prompt or PowerShell window?
 Add Flutter to your PATH: https://flutter.io/setup-windows/#update-your-path

 ================================================================================

C:\Users\k>cd xwork/

C:\Users\k\xwork>cd dartsugar

C:\Users\k\xwork\dartsugar>flutter upgrade
Building flutter tool...
Running pub upgrade...
Upgrading Flutter from C:\Users\k\flutter...
From https://github.com/flutter/flutter
   72bf075e8..df57dc9da  dev        -> origin/dev
   931c03791..6142e3324  master     -> origin/master
 * [new tag]             v0.11.4    -> v0.11.4
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.11.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 72bf075e8d (4 days ago) • 2018-11-09 20:36:17 -0800
Engine • revision 5646e86a6f
Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

Running "flutter packages upgrade" in dartsugar...
Git error. Command: git clone --mirror https://github.com/yathit/flutterlocation.git C:\Users\k\flutter\.pub-cache\git\cache\flutterlocation-b58b044fb99d1737bb246885c8282daf9a2d4412
Cloning into bare repository 'C:\Users\k\flutter\.pub-cache\git\cache\flutterlocation-b58b044fb99d1737bb246885c8282daf9a2d4412'...
pub upgrade failed (69) -- attempting retry 1 in 1 second...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 2 in 2 seconds...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 3 in 4 seconds...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 4 in 8 seconds...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 5 in 16 seconds...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 6 in 32 seconds...
Git error. Command: git fetch
```

```
flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Windows, locale en-SG)
    • Flutter version 0.11.3 at C:\Users\k\flutter
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\k\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\k\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
are you behind a proxy?

**Comment by zoechi** [comment]
Might be a dup of #14964

**Comment by yathit** [comment]
No proxy. I have mac and it is working fine. Windows also work fine a week ago.

**Comment by zoechi** [comment]
It could be a permission problem.

I'd try in the Flutter install dir

```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```

**Comment by yathit** [comment]
Hopeful, but still not working

```
Microsoft Windows [Version 10.0.17134.376]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\k>cd flutter

C:\Users\k\flutter>git clean -xfd
Removing .idea/
Removing .pub-cache/
Skipping repository bin/cache/pkg/goldens
Removing bin/cache/pkg/sky_engine
Removing bin/cache/.dartignore
Removing bin/cache/artifacts
Removing bin/cache/dart-sdk
Removing bin/cache/downloads
Removing bin/cache/engine-dart-sdk.stamp
Removing bin/cache/engine.stamp
Removing bin/cache/flutter.bat.lock
Removing bin/cache/flutter_tools.snapshot
Removing bin/cache/flutter_tools.stamp
Removing bin/cache/flutter_version_check.stamp
Removing bin/cache/goldens.lockfile
Removing bin/cache/gradle_wrapper.stamp
Removing bin/cache/lockfile
Removing bin/cache/material_fonts.stamp
Removing bin/mingit/
Removing dev/automated_tests/pubspec.lock
Removing dev/benchmarks/complex_layout/complex_layout.iml
Removing dev/benchmarks/complex_layout/pubspec.lock
Removing dev/benchmarks/microbenchmarks/pubspec.lock
Removing dev/bots/bots.iml
Removing dev/bots/pubspec.lock
Removing dev/devicelab/devicelab.iml
Removing dev/devicelab/pubspec.lock
Removing dev/integration_tests/android_semantics_testing/pubspec.lock
Removing dev/integration_tests/android_views/pubspec.lock
Removing dev/integration_tests/channels/pubspec.lock
Removing dev/integration_tests/external_ui/pubspec.lock
Removing dev/integration_tests/flavors/pubspec.lock
Removing dev/integration_tests/named_isolates/pubspec.lock
Removing dev/integration_tests/platform_interaction/pubspec.lock
Removing dev/integration_tests/ui/pubspec.lock
Removing dev/manual_tests/android.iml
Removing dev/manual_tests/manual_tests.iml
Removing dev/manual_tests/pubspec.lock
Removing dev/snippets/pubspec.lock
Removing dev/tools/pubspec.lock
Removing dev/tools/tools.iml
Removing dev/tools/vitool/pubspec.lock
Removing examples/catalog/catalog.iml
Removing examples/catalog/pubspec.lock
Removing examples/flutter_gallery/android.iml
Removing examples/flutter_gallery/flutter_gallery.iml
Removing examples/flutter_gallery/pubspec.lock
Removing examples/flutter_view/flutter_view.iml
Removing examples/flutter_view/pubspec.lock
Removing examples/hello_world/android.iml
Removing examples/hello_world/hello_world.iml
Removing examples/hello_world/pubspec.lock
Removing examples/layers/layers.iml
Removing examples/layers/pubspec.lock
Removing examples/platform_channel/android.iml
Removing examples/platform_channel/platform_channel.iml
Removing examples/platform_channel/pubspec.lock
Removing examples/platform_channel_swift/platform_channel_swift.iml
Removing examples/platform_channel_swift/pubspec.lock
Removing examples/platform_view/android.iml
Removing examples/platform_view/full_platform_view.iml
Removing examples/platform_view/pubspec.lock
Removing examples/stocks/android.iml
Removing examples/stocks/pubspec.lock
Removing examples/stocks/stocks.iml
Removing flutter_root.iml
Removing packages/flutter/coverage/
Removing packages/flutter/flutter.iml
Removing packages/flutter/pubspec.lock
Removing packages/flutter_driver/flutter_driver.iml
Removing packages/flutter_driver/pubspec.lock
Removing packages/flutter_goldens/pubspec.lock
Removing packages/flutter_goldens_client/pubspec.lock
Removing packages/flutter_localizations/flutter_localizations.iml
Removing packages/flutter_localizations/pubspec.lock
Removing packages/flutter_test/flutter_test.iml
Removing packages/flutter_test/pubspec.lock
Removing packages/flutter_test/test/test_config/project_root/pubspec.lock
Removing packages/flutter_tools/.dart_tool/
Removing packages/flutter_tools/.packages
Removing packages/flutter_tools/flutter_tools.iml
Removing packages/flutter_tools/pubspec.lock
Removing packages/flutter_tools/test/data/asset_test/main/pubspec.lock
Removing packages/fuchsia_remote_debug_protocol/pubspec.lock
Removing version

C:\Users\k\flutter>git stash save --keep-index
No local changes to save

C:\Users\k\flutter>git stash drop
No stash entries found.

C:\Users\k\flutter>git pull
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 40 (delta 23), reused 32 (delta 23), pack-reused 7
Unpacking objects: 100% (40/40), done.
From https://github.com/flutter/flutter
   df57dc9da..97e03104a  dev        -> origin/dev
   6142e3324..d5a177f7a  master     -> origin/master
 * [new tag]             v0.11.5    -> v0.11.5
Already up to date.

C:\Users\k\flutter>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 5646e86a6f442dc6f4158ae7010ab13d72a0b356...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Downloading Material fonts...                               308.9s
Downloading package sky_engine...                            0.6s
Downloading common tools...                                  1.0s
Downloading windows-x64 tools...                             1.4s
Downloading android-arm-profile/windows-x64 tools...         0.7s
Downloading android-arm-release/windows-x64 tools...         0.6s
Downloading android-arm64-profile/windows-x64 tools...       0.7s
Downloading android-arm64-release/windows-x64 tools...       0.6s
Downloading android-x86 tools...                             1.6s
Downloading android-x64 tools...                            132.5s
Downloading android-arm tools...                             0.3s
Downloading android-arm-profile tools...                     0.2s
Downloading android-arm-release tools...                     0.2s
Downloading android-arm64 tools...                           0.4s
Downloading android-arm64-profile tools...                   0.2s
Downloading android-arm64-release tools...                   0.2s
Downloading android-arm-dynamic-profile tools...             0.4s
Downloading android-arm-dynamic-release tools...             0.3s
Downloading android-arm64-dynamic-profile tools...           0.3s
Downloading android-arm64-dynamic-release tools...           0.3s
Downloading Gradle Wrapper...                                0.0s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.3, on Windows, locale en-SG)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] VS Code (version 1.28.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\k\flutter>cd ..

C:\Users\k>cd xwork

C:\Users\k\xwork>cd dartsugar

C:\Users\k\xwork\dartsugar>flutter upgrade
Upgrading Flutter from C:\Users\k\flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.11.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 72bf075e8d (4 days ago) • 2018-11-09 20:36:17 -0800
Engine • revision 5646e86a6f
Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

Running "flutter packages upgrade" in dartsugar...
pub upgrade failed (1)

C:\Users\k\xwork\dartsugar>
```

**Comment by yathit** [comment]
```
flutter upgrade -v
[  +43 ms] executing: [C:\Users\k\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Users\k\flutter\] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +1 ms] executing: [C:\Users\k\flutter\] git ls-remote --get-url origin
[  +25 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [C:\Users\k\flutter\] git log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 72bf075e8d6961d2ca6df462b2228954f8d0e73a
[        ] executing: [C:\Users\k\flutter\] git log -n 1 --pretty=format:%ar
[  +26 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 4 days ago
[   +1 ms] executing: [C:\Users\k\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +27 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.11.3-0-g72bf075e8
[  +78 ms] executing: [C:\Users\k\flutter\] git rev-parse @{u}
[  +60 ms] 72bf075e8d6961d2ca6df462b2228954f8d0e73a
[   +3 ms] Upgrading Flutter from C:\Users\k\flutter...
[   +4 ms] executing: [C:\Users\k\flutter\] git pull --ff-only
[+2313 ms] Already up to date.
[   +3 ms] Upgrading engine...
[   +1 ms] executing: [C:\Users\k\flutter\] bin\flutter --no-color --no-version-check precache
[ +965 ms] Already up-to-date.
[ +197 ms] Flutter 0.11.3 • channel beta • https://github.com/flutter/flutter.git
                    Framework • revision 72bf075e8d (4 days ago) • 2018-11-09 20:36:17 -0800
                    Engine • revision 5646e86a6f
                    Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)
[   +6 ms] Running "flutter packages upgrade" in dartsugar...
[   +3 ms] executing: [C:\Users\k\xwork\dartsugar\] C:\Users\k\flutter\bin\cache\dart-sdk\bin\pub.bat
--verbosity=warning --verbose upgrade --no-precompile
[+32453 ms] Running "flutter packages upgrade" in dartsugar... (completed)
[  +13 ms] "flutter upgrade" took 36,078ms.
pub upgrade failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:75:13)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:400:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#11     Future._complete (dart:async/future_impl.dart:476:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
I think this is a dup of https://github.com/flutter/flutter/issues/15014 / https://github.com/dart-lang/pub/issues/1591

**Comment by zoechi** [comment]
Please check the output of `env` if it contains anything with `PROXY`

**Comment by yathit** [comment]
No, it does not have anything with proxy

**Comment by yathit** [comment]
What is working is now is creating another local account and fresh install from the instruction.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by 91priyansh** [comment]
I am also getting  same error

**Comment by zoechi** [comment]
@91priyansh are you behind a firewall (China)?
Please post the log output.
Please add the output of `flutter doctor -v`.

**Comment by bmilovanovic** [comment]
This fails for me also. Here's the output of `flutter doctor -v`.

[√] Flutter (Channel stable, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.17134.858], locale en-US)
    • Flutter version 1.7.8+hotfix.2 at C:\src\flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 5.1.1 (API 22) (emulator)

**Comment by siddsarkar** [comment]
> are you behind a proxy?

yes
