### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by alyfreym** [flutter/flutter#24390]
`## command

flutter --suppress-analytics build bundle --target-platform=ios --target=/Users/MacMini/Documents/Projects/CROSS/nextgen_platform/lib/main.dart --debug --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/MacMini/Documents/Projects/CROSS/nextgen_platform/ios/Flutter/flutter_assets --track-widget-creation

## exception

ArgumentError: Invalid argument(s): Uri fonts:SFUI-Regular.otf must have scheme 'file:'.

```
#0      PosixStyle.pathFromUri (package:path/src/style/posix.dart:44:5)
#1      Context.fromUri (package:path/src/context.dart:986:32)
#2      _resolveAsset (package:flutter_tools/src/asset.dart:637:36)
#3      _parseAssets (package:flutter_tools/src/asset.dart:547:32)
#4      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:125:53)
<asynchronous suspension>
#5      buildAssets (package:flutter_tools/src/bundle.dart:150:40)
<asynchronous suspension>
#6      build (package:flutter_tools/src/bundle.dart:119:36)
<asynchronous suspension>
#7      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:89:11)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#40     main (file:///Users/MacMini/Documents/Projects/LIBRARY/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.11.7-pre.21, on Mac OS X 10.14 18A391, locale en-RU)
    • Flutter version 0.11.7-pre.21 at /Users/MacMini/Documents/Projects/LIBRARY/flutter
    • Framework revision 33f8030b32 (10 hours ago), 2018-11-14 23:06:49 -0500
    • Engine revision 00e4abff84
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/MacMini/Library/Developer/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

• No issues found!
```
`

**Comment by alyfreym** [comment]
I incorrectly specified the path to the font in the pabspech.yaml. Correct-fonts/UI-Regular.otf. incorrect - fonts:UI-Regular.otf

**Comment by alyfreym** [comment]
I incorrectly specified the path to the font in the pabspech.yaml. Correct-fonts/UI-Regular.otf. incorrect - fonts:UI-Regular.otf
