### ISSUE TITLE
DropdownButtonMenu positioned too high

### ISSUE THREAD

**Issue by nattyg93** [flutter/flutter#24417]
(This is my first bug report, so my apologies if I have not followed the template correctly)

## Steps to reproduce

When using a DropdownButton in a Navigator with a size that is constrained such that it's height is smaller than the height reported by `MediaQuery.of(context).size.height` an assert in `_DropdownMenuRouteLayout<T>`'s `getPositionForChild` method (`assert(menuTop + menuHeight <= size.height);`) is triggered. This results in the position not been returned. Thus, the `_DropDownMenu` is positioned at the top of the screen. However, in production (with asserts not being checked) this is not an issue as the position is successfully returned.

In the case of the screenshot below, I have a Navigator as the body of a Scaffold with a BottomNavigationBar, so the Navigator's size is the screen height - BottomNavigationBar.

![screenshot_1542335104](https://user-images.githubusercontent.com/4318027/48594264-13bf1b80-e9a4-11e8-98e7-909c61a3bf92.png)

## Logs
```
[   +1 ms] I/flutter (15245): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[   +9 ms] I/flutter (15245): The following assertion was thrown during performLayout():
[        ] I/flutter (15245): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 247 pos 16: 'menuTop +
[        ] I/flutter (15245): menuHeight <= size.height': is not true.
[   +5 ms] I/flutter (15245):
[        ] I/flutter (15245): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (15245): more information in this error message to help you determine and fix the underlying cause.
[   +8 ms] I/flutter (15245): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (15245):   https://github.com/flutter/flutter/issues/new
[        ] I/flutter (15245):
[        ] I/flutter (15245): When the exception was thrown, this was the stack:
[  +18 ms] I/flutter (15245): #2      _DropdownMenuRouteLayout.getPositionForChild.<anonymous closure> (package:flutter/src/material/dropdown.dart:247:16)
[        ] I/flutter (15245): #3      _DropdownMenuRouteLayout.getPositionForChild (package:flutter/src/material/dropdown.dart:250:6)
[        ] I/flutter (15245): #4      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1099:41)
[        ] I/flutter (15245): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[  +21 ms] I/flutter (15245): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[  +44 ms] I/flutter (15245): #15     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2880:13)
[        ] I/flutter (15245): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] I/flutter (15245): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #19     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter (15245): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #31     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] I/flutter (15245): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (15245): #33     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
[        ] I/flutter (15245): #34     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
[        ] I/flutter (15245): #35     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
[        ] I/flutter (15245): #36     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
[        ] I/flutter (15245): #37     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
[        ] I/flutter (15245): #38     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
[        ] I/flutter (15245): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
[   +1 ms] I/flutter (15245): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:674:13)
[        ] I/flutter (15245): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
[        ] I/flutter (15245): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter (15245): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter (15245): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
[        ] I/flutter (15245): #45     _invoke (dart:ui/hooks.dart:145:13)
[        ] I/flutter (15245): #46     _drawFrame (dart:ui/hooks.dart:134:3)
[        ] I/flutter (15245): (elided 2 frames from class _AssertionError)
[        ] I/flutter (15245):
[        ] I/flutter (15245): The following RenderObject was being processed when the exception was fired:
[        ] I/flutter (15245):   RenderCustomSingleChildLayoutBox#924c5 NEEDS-LAYOUT NEEDS-PAINT
[        ] I/flutter (15245):   creator: CustomSingleChildLayout ← Builder ← MediaQuery ← Builder ←
[        ] I/flutter (15245):   RepaintBoundary-[GlobalKey#15d2a] ← IgnorePointer ← AnimatedBuilder ← RepaintBoundary ←
[        ] I/flutter (15245):   _FocusScopeMarker ← Semantics ← FocusScope ← PageStorage ← ⋯
[        ] I/flutter (15245):   parentData: <none> (can use size)
[        ] I/flutter (15245):   constraints: BoxConstraints(w=411.4, h=627.4)
[        ] I/flutter (15245):   size: Size(411.4, 627.4)
[        ] I/flutter (15245): This RenderObject had the following descendants (showing up to depth 5):
[        ] I/flutter (15245):   RenderAnimatedOpacity#60090 relayoutBoundary=up1 NEEDS-PAINT
[        ] I/flutter (15245):     RenderCustomPaint#5c3a5 relayoutBoundary=up2 NEEDS-PAINT
[        ] I/flutter (15245):       RenderSemanticsAnnotations#736c6 relayoutBoundary=up3 NEEDS-PAINT
[        ] I/flutter (15245):         RenderCustomPaint#ce47e relayoutBoundary=up4 NEEDS-PAINT
[        ] I/flutter (15245):           _RenderInkFeatures#355f7 relayoutBoundary=up5 NEEDS-PAINT
[  +36 ms] I/flutter (15245): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G65, locale en-AU)
    • Flutter version 0.10.2 at /Users/<username>/.local/lib/flutter
    • Framework revision d8cbb80206 (3 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/<username>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/<username>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

• No issues found!
```

**Comment by zoechi** [comment]
Can you please provide a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce?

**Comment by nattyg93** [comment]
@zoechi
Can do. I am under a tight deadline at the moment, so might not be until the weekend.

**Comment by nattyg93** [comment]
@zoechi 

This is causing the behaviour I'm experiencing. It's also worth noting that bug does not present when the padding below is removed.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: Scaffold(
        body: Navigator(
          onGenerateRoute: (RouteSettings settings) => MaterialPageRoute<void>(
                builder: (BuildContext context) {
                  return Column(
                    children: [
                      // The height of this container may need to be increased
                      // for larger testing devices
                      Container(height: 100.0),
                      Container(
                        margin: EdgeInsets.symmetric(horizontal: 20.0),
                        padding: EdgeInsets.symmetric(horizontal: 20.0),  // <--- this padding
                        child: DropdownButton<int>(
                          value: 12,
                          isExpanded: true,
                          onChanged: (int i) => print('changed to $i'),
                          items: List<DropdownMenuItem<int>>.generate(
                            100,
                            (int i) => DropdownMenuItem<int>(
                                  value: i,
                                  child: Text(i.toString()),
                                ),
                          ),
                        ),
                      ),
                    ],
                  );
                },
              ),
        ),
        bottomNavigationBar: BottomNavigationBar(
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.ac_unit),
              title: Text('item 1'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.ac_unit),
              title: Text('item 2'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
It seems this is a feature request similar to #23865.
Is this right? Can we merge the issues?

**Comment by nattyg93** [comment]
This isn't the same as #23865. This is a bug. The DropdownButton is throwing an exception resulting in the pop up menu being rendered in the wrong position. As you can see in the image I attached, the popup is rendered in the top left corner, whereas it should be offset.

**Comment by EbenZhang** [comment]
got the same issue.
- Create a new app
- Add a DropdownButton
- Change the mainAxisAlignment to space between

```
mainAxisAlignment: MainAxisAlignment.spaceBetween,
  children: <Widget>[
    Text(
      'You have pushed the button this many times:',
    ),
    Text(
      '$_counter',
      style: Theme.of(context).textTheme.display1,
    ),
    DropdownButton(items: [DropdownMenuItem(child: Text("a")), DropdownMenuItem(child: Text("b"),)], onChanged: (value) {},)
  ],
```

![image](https://user-images.githubusercontent.com/596334/50509166-df20a280-0abf-11e9-9b62-6f15b6078e0c.png)

It works if I add a bottomNavigationBar `bottomNavigationBar: BottomAppBar(child: Icon(Icons.ac_unit)),`

**Comment by HansMuller** [comment]
@nattyg93 Sorry about the long delay. I can reproduce the problem with the test case from https://github.com/flutter/flutter/issues/24417#issuecomment-440632324

Looking into it.
