### ISSUE TITLE
Googlemap not rendering in ios

### ISSUE THREAD

**Issue by ZeroCool00** [flutter/flutter#24434]
I've seen that googlemap for ios is available now. i update flutter and run project again. i get this error

```
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
Google Maps SDK for iOS version: 2.7.30514.0
        [3.1 15CF4642-4C1D-40A1-88BC-2C09FC3CF654 192.168.0.103.55837<->64.233.185.190:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 1.395s, DNS @0.026s took 0.173s, TCP @0.202s took 0.289s, TLS took 0.604s
        bytes in/out: 4135/714, packets in/out: 9/9, rtt: 0.286s, retransmitted packets: 0, out-of-order packets: 2

```

also check with android after update.. its working fine.

## Logs
```
[+12005 ms] [DEVICE LOG] 2018-11-16 17:35:32.955045+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x61905, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.955133+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":initWithEffectiveBundleIdentifier:bundle:, "self":"0x600000017540", "identifier":(null), "bundle":(null)}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.955216+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":init, "new":'00 00 00 00 00 00 F0 BF 00 00 00 00 00 00 F0 BF 00 00 00 00 00 00 00 00
00 00 00 00 00 00 F0 3F 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00'}
[   +1 ms] [DEVICE LOG] 2018-11-16 17:35:32.955279+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":lifecycle, "old":"0x0", "new":"0x6000000d5f50"}
[  +18 ms] [DEVICE LOG] 2018-11-16 17:35:32.955315+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x61906, Description: CL:
_CLClientCreateWithBundleIdentifierAndPath
[        ] [DEVICE LOG] 2018-11-16 17:35:32.955351+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client]
{"msg":"_CLClientCreateWithBundleIdentifierAndPath", "event":activity, "effectiveBundleIdentifier":(null), "effectiveBundlePath":(null)}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.955389+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Legacy:Generic] #Warning Setting CLCommon's runloop
after it was already established
[   +1 ms] [DEVICE LOG] 2018-11-16 17:35:32.955476+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"client allocated",
"client":"0x7f9929644fc0"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.955754+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x61907, Description: CL: _CLClientCreateConnection
[        ] [DEVICE LOG] 2018-11-16 17:35:32.956040+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"_CLClientCreateConnection",
"event":activity, "client":"0x7f9929644fc0"}
[  +39 ms] [DEVICE LOG] 2018-11-16 17:35:32.956812+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x61908, Description: CL: Sending cached messages to daemon
[        ] [DEVICE LOG] 2018-11-16 17:35:32.957435+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"Sending cached messages to
daemon", "event":activity}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.958125+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] #Warning No cached registration message
[        ] [DEVICE LOG] 2018-11-16 17:35:32.958806+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":pausesLocationUpdatesAutomatically, "old":0, "new":1}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.959050+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x61909, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.959104+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":setDelegate:, "self":"0x600000017540", "delegate":"0x600000474340"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.959334+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190a, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.959517+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":setDesiredAccuracy:, "self":"0x600000017540", "accuracy":"-1.000000"}
[   +1 ms] [DEVICE LOG] 2018-11-16 17:35:32.959726+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":desiredAccuracy, "old":"-1.000000", "new":"-1.000000"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.959931+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190b, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.960280+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":setActivityType:, "self":"0x600000017540", "activityType":3}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.960509+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":activityType, "old":0, "new":3}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.961871+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":allowsMapCorrection, "old":1, "new":0}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.972667+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190c, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.972790+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":setDelegate:, "self":"0x60400001cff0", "delegate":"0x0"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.972824+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190d, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2018-11-16 17:35:32.972914+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager",
"event":activity, "_cmd":dealloc, "self":"0x60400001cff0"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.972992+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x60400001cff0", "property":requestingLocation, "old":0, "new":0}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.974726+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x60400001cff0", "property":requestingRanging, "old":0, "new":0}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.974892+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x60400001cff0", "property":updatingRanging, "old":0, "new":0}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.975109+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"invalidating client",
"client":"0x7f992972bb10"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.975852+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"client about to be destroyed",
"client":"0x7f992972bb10"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.976184+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x60400001cff0", "property":lifecycle, "old":"0x6040000de3e0", "new":"0x0"}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.982361+0530  localhost Runner[24122]: (CFNetwork) TIC Enabling TLS [5:0x600000367140]
[        ] [DEVICE LOG] 2018-11-16 17:35:32.982429+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Start [5:0x600000367140]
[        ] [DEVICE LOG] 2018-11-16 17:35:32.982499+0530  localhost Runner[24122]: (CFNetwork) Task <6620A017-0A6A-4C00-B614-16BDA323285A>.<1> setting up Connection 5
[        ] [DEVICE LOG] 2018-11-16 17:35:32.982560+0530  localhost Runner[24122]: (libnetwork.dylib) [com.apple.network:] [5 clients4.google.com:443 stream, pid: 24122,
tls] start
[        ] [DEVICE LOG] 2018-11-16 17:35:32.999593+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":previousAuthorizationStatus, "old":0, "new":0}
[        ] [DEVICE LOG] 2018-11-16 17:35:32.999668+0530  localhost Runner[24122]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition",
"event":state_transition, "state":LocationManager, "id":"0x600000017540", "property":previousAuthorizationStatusValid, "old":0, "new":1}
[  +65 ms] [DEVICE LOG] 2018-11-16 17:35:33.096082+0530  localhost Runner[24122]: (CoreUI) [com.apple.coreui:framework] CUICatalog: Invalid asset name supplied: '(null)'
[        ] [DEVICE LOG] 2018-11-16 17:35:33.096144+0530  localhost Runner[24122]: (CoreUI) [com.apple.coreui:framework] CUICatalog: Invalid asset name supplied: '(null)'
[   +1 ms] [DEVICE LOG] 2018-11-16 17:35:33.096176+0530  localhost Runner[24122]: (CoreUI) [com.apple.coreui:framework] CUICatalog: Invalid asset name supplied: '(null)'
[        ] [DEVICE LOG] 2018-11-16 17:35:33.096205+0530  localhost Runner[24122]: (CoreUI) [com.apple.coreui:framework] CUICatalog: Invalid asset name supplied: '(null)'
[  +48 ms] [DEVICE LOG] 2018-11-16 17:35:33.146369+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the
PrerollContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[  +21 ms] [DEVICE LOG] 2018-11-16 17:35:33.168742+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the
PaintContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
[  +45 ms] [DEVICE LOG] 2018-11-16 17:35:33.214767+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the
PrerollContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[  +21 ms] [DEVICE LOG] 2018-11-16 17:35:33.236270+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the
PaintContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
[  +50 ms] [DEVICE LOG] 2018-11-16 17:35:33.286460+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the
PrerollContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[  +42 ms] [DEVICE LOG] 2018-11-16 17:35:33.328288+0530  localhost Runner[24122]: (Flutter) [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the
PaintContext does not support embedding
[        ] [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
[ +102 ms] [DEVICE LOG] 2018-11-16 17:35:33.433769+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 1, Pending(0)
[ +283 ms] [DEVICE LOG] 2018-11-16 17:35:33.717046+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 2, Pending(0)
[  +22 ms] [DEVICE LOG] 2018-11-16 17:35:33.736139+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 11, Pending(0)
[        ] [DEVICE LOG] 2018-11-16 17:35:33.737629+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 12, Pending(0)
[        ] [DEVICE LOG] 2018-11-16 17:35:33.738278+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 14, Pending(0)
[        ] [DEVICE LOG] 2018-11-16 17:35:33.739587+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190e, Description: SecTrustEvaluateIfNecessary
[   +3 ms] [DEVICE LOG] 2018-11-16 17:35:33.743416+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x6190f, Description: SecTrustEvaluateIfNecessary
[   +2 ms] [DEVICE LOG] 2018-11-16 17:35:33.745753+0530  localhost Runner[24122]: (CFNetwork) System Trust Evaluation yielded status(0)
[        ] [DEVICE LOG] 2018-11-16 17:35:33.745974+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Trust Result [5:0x600000367140]: 0
[ +281 ms] [DEVICE LOG] 2018-11-16 17:35:34.027705+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x635c0, Description: SecTrustReportTLSAnalytics
[   +1 ms] [DEVICE LOG] 2018-11-16 17:35:34.028000+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Event [5:0x600000367140]: 20, Pending(0)
[        ] [DEVICE LOG] 2018-11-16 17:35:34.028131+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Connected [5:0x600000367140]: Err(16)
[        ] [DEVICE LOG] 2018-11-16 17:35:34.028332+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Event [5:0x600000367140]: 1
[        ] [DEVICE LOG] 2018-11-16 17:35:34.028523+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Event [5:0x600000367140]: 8
[        ] [DEVICE LOG] 2018-11-16 17:35:34.028690+0530  localhost Runner[24122]: (CFNetwork) TIC TLS Handshake Complete [5:0x600000367140]
[        ] [DEVICE LOG] 2018-11-16 17:35:34.029165+0530  localhost Runner[24122]: (CFNetwork) Task <6620A017-0A6A-4C00-B614-16BDA323285A>.<1> now using Connection 5
[        ] [DEVICE LOG] 2018-11-16 17:35:34.029248+0530  localhost Runner[24122]: (CFNetwork) Task <6620A017-0A6A-4C00-B614-16BDA323285A>.<1> sent request, body S
[ +311 ms] [DEVICE LOG] 2018-11-16 17:35:34.341990+0530  localhost Runner[24122]: (CFNetwork) Task <6620A017-0A6A-4C00-B614-16BDA323285A>.<1> received response, status 200
content K
[   +3 ms] [DEVICE LOG] 2018-11-16 17:35:34.344489+0530  localhost Runner[24122]: (CFNetwork) Task <6620A017-0A6A-4C00-B614-16BDA323285A>.<1> response ended
[+63802 ms] [DEVICE LOG] 2018-11-16 17:36:38.145794+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Cancel [5:0x600000367140]
[        ] [DEVICE LOG] 2018-11-16 17:36:38.146074+0530  localhost Runner[24122]: (libnetwork.dylib) [com.apple.network:] [5 clients4.google.com:443 stream, pid: 24122,
tls] cancelled
[        ] [DEVICE LOG]         [5.1 B77FBF4D-88EE-48D7-BA59-642F0DDC56A0 192.168.0.103.54910<->216.58.193.174:443]
[        ] [DEVICE LOG]         Connected Path: satisfied (Path is satisfied), interface: en0
[        ] [DEVICE LOG]         Duration: 65.165s, DNS @0.006s took 0.162s, TCP @0.170s took 0.280s, TLS took 0.595s
[        ] [DEVICE LOG]         bytes in/out: 4183/1209, packets in/out: 10/10, rtt: 0.284s, retransmitted packets: 0, out-of-order packets: 0
[        ]      [5.1 B77FBF4D-88EE-48D7-BA59-642F0DDC56A0 192.168.0.103.54910<->216.58.193.174:443]
[        ]      Connected Path: satisfied (Path is satisfied), interface: en0
[        ]      Duration: 65.165s, DNS @0.006s took 0.162s, TCP @0.170s took 0.280s, TLS took 0.595s
[        ]      bytes in/out: 4183/1209, packets in/out: 10/10, rtt: 0.284s, retransmitted packets: 0, out-of-order packets: 0
[        ] [DEVICE LOG] 2018-11-16 17:36:38.146294+0530  localhost Runner[24122]: (CFNetwork) TIC TCP Conn Destroyed [5:0x600000367140]
[        ] [DEVICE LOG] 2018-11-16 17:36:38.146478+0530  localhost Runner[24122]: (CFNetwork) TIC Read Status [5:0x0]: 1:57
[        ] [DEVICE LOG] 2018-11-16 17:36:38.146513+0530  localhost Runner[24122]: (CFNetwork) TIC Read Status [5:0x0]: 1:57
[        ] [DEVICE LOG] 2018-11-16 17:36:38.146624+0530  localhost Runner[24122]: (Runner) Created Activity ID: 0x635c1, Description: SecTrustReportTLSAnalytics

```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.11.3 at /MyDrive/flutter
    • Framework revision 72bf075e8d (6 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/micra/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone X • 2F2062B3-2D8B-4F72-8CA7-209587B4462A • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by amirh** [comment]
View embedding on iOS is currently in preview and needs to be explicitly enabled.
See more details in https://github.com/flutter/flutter/issues/19030#issuecomment-437534853

**Comment by AndroidEngineerChenXiaoshuang** [comment]
Hello, I have been reporting such an anomaly.
 [VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
This is AppDelegate:
`
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    IOSTextViewPlugin.registerWith(pluginRegistrar: registrar(forPlugin: "IOSTextViewPlugin"))
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`

This is IOSTextViewPlugin

`
class IOSTextViewPlugin{
    public static func registerWith(pluginRegistrar: FlutterPluginRegistrar){
        let factory = IOSTextViewPlatformTextViewFactory.init(messenger: pluginRegistrar.messenger())
        pluginRegistrar.register(factory, withId: "IOSTextViewPlugin")
    }
}
`
This is IOSTextViewPlatformTextViewFactory
`
class IOSTextViewPlatformTextViewFactory:NSObject,FlutterPlatformViewFactory{
    
    private let messenger: FlutterBinaryMessenger
    
    init(messenger: FlutterBinaryMessenger){
        self.messenger = messenger
    }
    
    func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        return IOSTextView.init(messenger: messenger, frame: frame, viewId: viewId, args: args)
    }
}
`
This is IOSTextView
`
class IOSTextView :NSObject,FlutterPlatformView{
    
    private let frame: CGRect
    private let viewId: Int64
    private let messenger: FlutterBinaryMessenger
    private var uiLabel: UILabel
    
    init(messenger: FlutterBinaryMessenger,frame: CGRect, viewId: Int64, args: Any?){
        self.messenger = messenger
        self.frame = frame
        self.viewId = viewId
        
        uiLabel = UILabel.init(frame: frame)
        uiLabel.text = "UILabel"
    }
    
    func view() -> UIView {
        return uiLabel
    }
    
}
`
This is Dart
`
void main() => runApp(BaiduMapApp());

class BaiduMapApp extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return BaiduMapAppState();
  }
}

class BaiduMapAppState extends State<BaiduMapApp> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      title: "Platform View Test",
      home: Scaffold(
        appBar: AppBar(
          title: Text('Platform View Test'),
        ),
        body: Center(
            child: SizedBox(
                width: 100,
                height: 100,
                child: defaultTargetPlatform == TargetPlatform.android
                    ? AndroidView(
                  viewType: 'AndroidTextViewPlugin',
                  creationParams: {"content": "通过参数传入的文本内容"},
                  creationParamsCodec: const StandardMessageCodec(),
                  onPlatformViewCreated: onMyViewCreated,
                )
                    : UiKitView(viewType: 'IOSTextViewPlugin',)
            )),
      ),
    );
  }

  MethodChannel _channel;

  void onMyViewCreated(int id) {
    _channel = MethodChannel('AndroidTextView$id');
    _channel.invokeMethod('setText', 'Hello World');
  }
}
`

![image](https://user-images.githubusercontent.com/22950417/51545346-c75cf400-1e9c-11e9-85f8-4e0cd36cb1b2.png)

I am using the simulator

**Comment by amirh** [comment]
Hi, check the README file for instructions on how to enable the developers preview(and the implications of doing so).
I'd suggest trying StackOverflow for support questions.

**Comment by p8ul** [comment]
Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.
[stackoverflow](https://stackoverflow.com/questions/54395776/flutter-throws-an-exception-using-flutterplatformview)
<key>io.flutter.embedded_views_preview</key>
<true/>

**Comment by bemesquita** [comment]
Using Flutter: `1.9.1+hotfix6`

Added:
```
<key>io.flutter.embedded_views_preview</key>
<true/> 
```

Still not working.

**Comment by bemesquita** [comment]
Flutter Version: `1.9.1+hotifix6`
Google Maps Flutter Version: `0.5.21+12`

Added on plist.info:
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```
Still not working.

**Comment by supertrens** [comment]
Same issue here , I add ```<key>io.flutter.embedded_views_preview</key>
<true/>```  to the `info.plist` and  ```    GMSServices.provideAPIKey(API_KEY)
``` to the `AppDelegate.swift` file , still nothing

**Comment by Dlvnkenye** [comment]
> Same issue here , I add `<key>io.flutter.embedded_views_preview</key> <true/>` to the `info.plist` and ` GMSServices.provideAPIKey(API_KEY)` to the `AppDelegate.swift` file , still nothing

I have the same issue

**Comment by supertrens** [comment]
<details>
  <summary> @Dlvnkenye It worked for me. Here are the <b>steps</b> I took.</summary>
   <ol>
     <li>Run <em>flutter clean</em> </li>
    <li> add <em><key>io.flutter.embedded_views_preview</key> <true/></em> to the info.plist  (Pic 1) . </li>
     <li> in AppDelegate.swift, I add <em>GMSServices.provideAPIKey(API_KEY)</em>. <br> PS) Make sure u import the google library ( pic 2 to see final result) </li>
  </ol>
</details>


```PIC 1```
<img width="536" alt="Pic1" src="https://user-images.githubusercontent.com/11289465/71430518-4ab74300-2707-11ea-951d-6de5e2269978.png">

```PIC 2```
<img width="841" alt="Screen Shot 2019-12-25 at 11 10 22 AM" src="https://user-images.githubusercontent.com/11289465/71430546-6fabb600-2707-11ea-9b97-a54b2081de65.png">

**Comment by Dlvnkenye** [comment]
@supertrens , I did follow the instruction above but I am getting the following error 
`Performing hot restart...                                               
Restarted application in 1,972ms.
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'plugins.flutter.io/google_maps')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:168:41)
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:621:71)
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:571:5)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:581:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#8      Element.inf<…>
`

**Comment by supertrens** [comment]
Do u mind sharing your repo? I could take a quick look at it

**Comment by Dlvnkenye** [comment]
@supertrens thank you for response, now it is working I uninstall flutter , and reinstall the latest version "v1.12.13+hotfix.5" but the problem was still the same. after searching I came across a similar issue raised and followed the step provided by  in the link bellow [cuikun](https://github.com/flutter/flutter/issues/25714#issue-393755300) 
I run "**flutter run --verbose**"
<img width="582" alt="Screenshot 2019-12-26 at 04 44 39" src="https://user-images.githubusercontent.com/40869745/71453056-71728980-279a-11ea-9dbf-190f4a7d7833.png">
this revels two errors : **Error running pod install** and **Error launching application on iPhone 11 Pro Max**. once the app rebuild  and pod install everything worked.

**Comment by anton-kli** [comment]
I have same issue, and I fix that when removed all pods added on info.plist:
 <key>io.flutter.embedded_views_preview</key>
    <true/>
and install all pods again.

**Comment by SalilThreeplus** [comment]
I have added io.flutter.embedded_views_preview flag in info.plist. My application runs fine in debug mode on iOS but it gets stuck in release mode on splash screen after adding io.flutter.embedded_views_preview this flag.
