### ISSUE TITLE
Flutter app crashes after very first load

### ISSUE THREAD

**Issue by skrizanovic** [flutter/flutter#24448]
After updating flutter, the app is crashing every time it is opened except for the very first time it is installed to the emulator.

here is the log
```
11-17 08:15:01.031  4028  4028 W System  : ClassLoader referenced unknown path: /system/app/DeskClock/lib/x86
11-17 08:15:01.038  1599  3810 I ActivityManager: Killing 2392:com.google.android.calendar/u0a22 (adj 15): empty #17
11-17 08:15:07.160  3907  3907 W FA      : setCurrentScreen cannot be called with the same class and name
11-17 08:15:10.306  1695  2172 D EGL_emulation: eglMakeCurrent: 0xad814c60: ver 3 1 (tinfo 0xad8125c0)
11-17 08:15:10.329  1327  1629 W audio_hw_generic: Not supplying enough data to HAL, expected position 2543168 , only wrote 2405379
11-17 08:15:10.363  1599  1643 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher3/.Launcher (has extras)} from uid 1000 on display 0
11-17 08:15:10.383  1234  1269 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1806336
11-17 08:15:10.404  1327  1629 D AudioFlinger: mixer(0xb4380000) throttle end: throttle time(11)
11-17 08:15:10.495  1957  2129 D EGL_emulation: eglMakeCurrent: 0xad814ae0: ver 3 1 (tinfo 0xad8126d0)
11-17 08:15:10.756  3907  3907 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb25df8a0
11-17 08:15:10.791  3907  3988 D EGL_emulation: eglMakeCurrent: 0xa937e640: ver 3 1 (tinfo 0x97a3ef60)
11-17 08:15:10.792  3907  3988 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb40be7e0
11-17 08:15:11.360  1957  2129 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-17 08:15:11.360  1957  2129 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-17 08:15:12.489  1327  1629 D AudioFlinger: mixer(0xb4380000) throttle end: throttle time(10)
11-17 08:15:13.684  1599  1980 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.faws.feast/.MainActivity (has extras)} from uid 10009 on display 0
11-17 08:15:13.689  1599  1613 W BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) }
to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10009)
11-17 08:15:13.689  1599  1613 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1957, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.search.core.icingsync.ApplicationLaunchReceiver
11-17 08:15:13.738  3907  3907 D EGL_emulation: eglCreateContext: 0xa937d500: maj 3 min 1 rcv 4
11-17 08:15:13.746  1327  1629 D AudioFlinger: mixer(0xb4380000) throttle end: throttle time(6)
11-17 08:15:13.763  3907  3907 D EGL_emulation: eglMakeCurrent: 0xa937d500: ver 3 1 (tinfo 0xacf83b60)
11-17 08:15:13.763  3907  3907 E eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
11-17 08:15:13.763  3907  3907 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
11-17 08:15:13.763  3907  3907 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
11-17 08:15:13.768  3907  3907 E eglCodecCommon: glUtilsParamSize: unknow param 0x000087fe
11-17 08:15:13.804  3907  3988 D EGL_emulation: eglMakeCurrent: 0xa937e640: ver 3 1 (tinfo 0x97a3ef60)
11-17 08:15:13.817  3907  3937 D EGL_emulation: eglMakeCurrent: 0xa937d500: ver 3 1 (tinfo 0xad812e30)
11-17 08:15:13.865  3907  3937 D skia    : Program linking failed.
11-17 08:15:13.874  1957  2129 D EGL_emulation: eglMakeCurrent: 0xad814ae0: ver 3 1 (tinfo 0xad8126d0)
11-17 08:15:13.876  1957  2129 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb2516820
11-17 08:15:13.890  3907  3937 E emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glLinkProgram:1310 GL error 0x501
11-17 08:15:13.895  3907  3937 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008741
11-17 08:15:13.896  3907  3937 F libc    : /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
11-17 08:15:13.897  3907  3937 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3937 (1.gpu)
11-17 08:15:14.001  1324  1324 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-17 08:15:14.001  1324  1324 F DEBUG   : Build fingerprint: 'Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/4931947:userdebug/test-keys'
11-17 08:15:14.001  1324  1324 F DEBUG   : Revision: '0'
11-17 08:15:14.001  1324  1324 F DEBUG   : ABI: 'x86'
11-17 08:15:14.001  1324  1324 F DEBUG   : pid: 3907, tid: 3937, name: 1.gpu  >>> com.faws.feast <<<
11-17 08:15:14.001  1324  1324 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-17 08:15:14.007  1324  1324 F DEBUG   : Abort message: '/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed'
11-17 08:15:14.007  1324  1324 F DEBUG   :     eax 00000000  ebx 00000f43  ecx 00000f61  edx 00000006
11-17 08:15:14.007  1324  1324 F DEBUG   :     esi 9edfa980  edi 0000000c
11-17 08:15:14.008  1324  1324 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000007  xss 0000007b
11-17 08:15:14.008  1324  1324 F DEBUG   :     eip b7341a56  ebp 00000f61  esp 9edf7cf0  flags 00200202
11-17 08:15:13.993  1324  1324 W debuggerd: type=1400 audit(0.0:30): avc: denied { search } for name="com.faws.feast" dev="dm-0" ino=19204 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
11-17 08:15:14.017  1324  1324 F DEBUG   :
11-17 08:15:14.017  1324  1324 F DEBUG   : backtrace:
11-17 08:15:14.019  1324  1324 F DEBUG   :     #00 pc 00083a56  /system/lib/libc.so (tgkill+22)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #01 pc 00081608  /system/lib/libc.so (pthread_kill+70)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #02 pc 00027205  /system/lib/libc.so (raise+36)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #03 pc 000209e4  /system/lib/libc.so (abort+80)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #04 pc 00024741  /system/lib/libc.so (__libc_fatal+32)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #05 pc 00020b63  /system/lib/libc.so (__assert2+60)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #06 pc 0062df04  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #07 pc 0062e377  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #08 pc 0062e179  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.019  1324  1324 F DEBUG   :     #09 pc 0062d7be  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.020  1324  1324 F DEBUG   :     #10 pc 0062d713  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.020  1324  1324 F DEBUG   :     #11 pc 00630c48  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.020  1324  1324 F DEBUG   :     #12 pc 00630c80  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.020  1324  1324 F DEBUG   :     #13 pc 007e21a6  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.021  1324  1324 F DEBUG   :     #14 pc 007ddf64  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.021  1324  1324 F DEBUG   :     #15 pc 007df207  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #16 pc 0076a52c  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #17 pc 007fb0f9  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #18 pc 00800b3b  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #19 pc 00805baa  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #20 pc 0077929d  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #21 pc 00779170  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #22 pc 007660bc  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #23 pc 0076677c  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #24 pc 007f2407  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #25 pc 007f2317  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.022  1324  1324 F DEBUG   :     #26 pc 006be6c3  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #27 pc 009e3930  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #28 pc 006997c1  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #29 pc 006a0143  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #30 pc 006a05a6  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #31 pc 006a0864  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #32 pc 006a0455  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #33 pc 006a0796  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #34 pc 006695ed  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #35 pc 00669538  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #36 pc 0066b678  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #37 pc 0001afa7  /system/lib/libutils.so (android::Looper::pollInner(int)+439)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #38 pc 0001b307  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+53)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #39 pc 0000b675  /system/lib/libandroid.so (ALooper_pollOnce+96)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #40 pc 0066b77b  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #41 pc 00667d5e  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.023  1324  1324 F DEBUG   :     #42 pc 00669e53  /data/app/com.faws.feast-1/lib/x86/libflutter.so (offset 0x5c6000)
11-17 08:15:14.024  1324  1324 F DEBUG   :     #43 pc 00080ab3  /system/lib/libc.so (__pthread_start(void*)+56)
11-17 08:15:14.024  1324  1324 F DEBUG   :     #44 pc 00021952  /system/lib/libc.so (__start_thread+25)
11-17 08:15:14.024  1324  1324 F DEBUG   :     #45 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
11-17 08:15:14.103  1324  1324 W debuggerd: type=1400 audit(0.0:31): avc: denied { search } for name="com.faws.feast" dev="dm-0" ino=19204 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
11-17 08:15:14.286  1324  1324 F DEBUG   :
11-17 08:15:14.286  1324  1324 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_01
11-17 08:15:14.286  1324  1324 E DEBUG   : AM write failed: Broken pipe
11-17 08:15:14.286  1599  1616 I BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
11-17 08:15:14.299  1599  4057 W ActivityManager:   Force finishing activity com.faws.feast/.MainActivity
11-17 08:15:14.317  1234  1596 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1806336
11-17 08:15:14.324  1599  4057 D         : HostConnection::get() New Host Connection established 0x9c7acb40, tid 4057
11-17 08:15:14.331  1599  1643 W InputDispatcher: channel '2f54a2a com.faws.feast/com.faws.feast.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-17 08:15:14.331  1599  1643 E InputDispatcher: channel '2f54a2a com.faws.feast/com.faws.feast.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-17 08:15:14.340  1599  3243 D GraphicsStats: Buffer count: 5
11-17 08:15:14.348  1599  3245 I WindowState: WIN DEATH: Window{2f54a2a u0 com.faws.feast/com.faws.feast.MainActivity}
11-17 08:15:14.348  1599  3245 W InputDispatcher: Attempted to unregister already unregistered input channel '2f54a2a com.faws.feast/com.faws.feast.MainActivity (server)'
11-17 08:15:14.350  1599  3810 I WindowState: WIN DEATH: Window{7c28f60 u0 SurfaceView}
11-17 08:15:14.352  1330  1330 I Zygote  : Process 3907 exited due to signal (6)
11-17 08:15:14.352  1599  4057 W ActivityManager: Exception thrown during pause
11-17 08:15:14.352  1599  4057 W ActivityManager: android.os.DeadObjectException
11-17 08:15:14.352  1599  4057 W ActivityManager:       at android.os.BinderProxy.transactNative(Native Method)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at android.os.BinderProxy.transact(Binder.java:503)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
11-17 08:15:14.352  1599  4057 W ActivityManager:       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
11-17 08:15:14.355  1232  1232 E lowmemorykiller: Error opening /proc/3907/oom_score_adj; errno=2
11-17 08:15:14.357  1599  1611 I ActivityManager: Process com.faws.feast (pid 3907) has died
11-17 08:15:14.410  1695  2172 D EGL_emulation: eglMakeCurrent: 0xad814c60: ver 3 1 (tinfo 0xad8125c0)
11-17 08:15:14.453  1957  2129 D EGL_emulation: eglMakeCurrent: 0xad814ae0: ver 3 1 (tinfo 0xad8126d0)
11-17 08:15:14.473  1599  3179 I OpenGLRenderer: Initialized EGL, version 1.4
11-17 08:15:14.485  1599  3179 D EGL_emulation: eglCreateContext: 0x9ca26960: maj 3 min 1 rcv 4
11-17 08:15:14.511  1599  3244 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.520  1599  2123 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.527  1599  3810 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.542  1599  2191 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.558  1599  3179 D EGL_emulation: eglMakeCurrent: 0x9ca26960: ver 3 1 (tinfo 0x99c42680)
11-17 08:15:14.560  1599  3179 E eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
11-17 08:15:14.561  1599  3179 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
11-17 08:15:14.561  1599  3179 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
11-17 08:15:14.566  1599  1991 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.573  1599  2191 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-17 08:15:14.581  1599  3179 D EGL_emulation: eglMakeCurrent: 0x9ca26960: ver 3 1 (tinfo 0x99c42680)
11-17 08:15:14.979  1599  1618 W WindowAnimator: Failed to dispatch window animation state change.
11-17 08:15:14.979  1599  1618 W WindowAnimator: android.os.DeadObjectException
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:603)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:739)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Looper.loop(Looper.java:148)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-17 08:15:14.979  1599  1618 W WindowAnimator: Failed to dispatch window animation state change.
11-17 08:15:14.979  1599  1618 W WindowAnimator: android.os.DeadObjectException
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:603)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:739)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.Looper.loop(Looper.java:148)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
11-17 08:15:14.979  1599  1618 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-17 08:15:16.030  1599  3179 D EGL_emulation: eglMakeCurrent: 0x9ca26960: ver 3 1 (tinfo 0x99c42680)
11-17 08:15:16.032  1599  3179 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9d6f9aa0
11-17 08:15:16.044  1599  1991 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 3907 uid 10069
11-17 08:15:16.067  1327  1629 D AudioFlinger: mixer(0xb4380000) throttle end: throttle time(7)
11-17 08:15:16.240  1599  1618 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
11-17 08:15:19.131  1327  1629 W audio_hw_generic: Not supplying enough data to HAL, expected position 3176250 , only wrote 2791403
11-17 08:16:00.055  1234  1291 D hwcomposer: hw_composer sent 206 syncs in 60s
11-17 08:17:00.070  1234  1291 D hwcomposer: hw_composer sent 7 syncs in 60s
11-17 08:18:00.065  1234  1291 D hwcomposer: hw_composer sent 16 syncs in 60s
11-17 08:19:00.056  1234  1291 D hwcomposer: hw_composer sent 10 syncs in 60s
```

I keep seeing the dead object exception, but all it does it use the splash screen, and redirect to my custom screen after 5 seconds. 

When I run debug, it will work on the very first attempt (when its not installed in the emulator) but the second time it will not work, just crashes before even getting to any code. 
If I uninstall it from the emulator, then it appeears to work again, but just the first time.

It appears to be happening in the sqlLite opendatabase method call.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
