### ISSUE TITLE
[google_maps_flutter_example] Error UiKitView isn't defined. 

### ISSUE THREAD

**Issue by hungrymonkey** [flutter/flutter#24460]
## Steps to Reproduce

1. Clone google_maps_flutter/example
2. flutter run -v
3. Error: The method 'UiKitView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'

I am unable to build the example google_maps_flutter code.

## Logs

```
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&Re
           ndererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
[        ] I/flutter ( 4751): #228

_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&Re
           ndererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
[        ] I/flutter ( 4751): #229
           _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
           (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter ( 4751): #230
           _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
           (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter ( 4751): #231
           _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
           (package:flutter/src/scheduler/binding.dart:842:5)
[        ] I/flutter ( 4751): #232    _invoke (dart:ui/hooks.dart:145:13)
[        ] I/flutter ( 4751): #233    _drawFrame (dart:ui/hooks.dart:134:3)
[        ] I/flutter ( 4751):
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[+6850 ms] I/flutter ( 4751): Another exception was thrown: NoSuchMethodError: The method 'removeListener' was called
on null.
[ +911 ms] I/flutter ( 4751): Another exception was thrown:

'file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart': error: line 47
                    pos 14:
file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart:47:14:
                    Error: The method 'UiKitView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'.
[+8026 ms] I/chatty  ( 4751): uid=10080(io.flutter.plugins.googlemapsexample) 1.ui identical 1 line
[        ] I/flutter ( 4751): Another exception was thrown:
           'file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart': error:
line 47
           pos 14:
file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart:47:14:
           Error: The method 'UiKitView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'.
[+2011 ms] I/flutter ( 4751): Another exception was thrown:

'file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart': error: line 47
                    pos 14:
file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart:47:14:
                    Error: The method 'UiKitView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'.
[ +835 ms] I/flutter ( 4751): Another exception was thrown:

'file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart': error: line 47
                    pos 14:
file:///Users/psuedofinnish/git_repo/plugins/packages/google_maps_flutter/lib/src/google_map.dart:47:14:
                    Error: The method 'UiKitView' isn't defined for the class 'google_maps_flutter::_GoogleMapState'.
[+1518 ms] I/zygote  ( 4751): Do partial code cache collection, code=29KB, data=24KB
[        ] I/zygote  ( 4751): After code cache collection, code=29KB, data=24KB
[        ] I/zygote  ( 4751): Increasing code cache capacity to 128KB
```

```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.10.2 at /Users/psuedofinnish/flutter
    • Framework revision d8cbb80206 (3 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/psuedofinnish/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

![screenshot_1542425630](https://user-images.githubusercontent.com/771339/48656240-3b7ba700-e9d7-11e8-876d-89f14964506e.png)

**Comment by hungrymonkey** [comment]
tested another guy solution.
this plugin only works with the dev channel
```
[✓] Flutter (Channel dev, v0.11.6, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.6 at /Users/psuedofinnish/flutter
    • Framework revision d44aa57c12 (2 days ago), 2018-11-14 11:09:56 -0800
    • Engine revision 114d33d3ca
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/psuedofinnish/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by hungrymonkey** [comment]
I highly recommend you download android 9 or PIE because you do not need to update the google play store seperately.
