### ISSUE TITLE
pageview error when scrolling

### ISSUE THREAD

**Issue by minh98** [flutter/flutter#24470]
when i scrolling pageview.

LOG:

```
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 2 of 420 libraries in 1,362ms.
I/flutter ( 5647): onpagechanged:0
I/flutter ( 5647): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 5647): The following assertion was thrown while handling a gesture:
I/flutter ( 5647): 'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 602 pos 15: 'curve !=
I/flutter ( 5647): null': is not true.
I/flutter ( 5647): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5647): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5647): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5647):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5647): When the exception was thrown, this was the stack:
I/flutter ( 5647): #2      new DrivenScrollActivity (package:flutter/src/widgets/scroll_activity.dart:602:15)
I/flutter ( 5647): #3      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:182:43)
I/flutter ( 5647): #4      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:119:21)
I/flutter ( 5647): #5      MyHomePageState.build.<anonymous closure> (package:flutter_tnutest/main/main.dart:115:29)
I/flutter ( 5647): #6      _PageViewState.build.<anonymous closure> (package:flutter/src/widgets/page_view.dart:559:20)
I/flutter ( 5647): #7      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125:27)
I/flutter ( 5647): #8      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter ( 5647): #9      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter ( 5647): #10     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3344:39)
I/flutter ( 5647): #11     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59:12)
I/flutter ( 5647): #12     DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:443:118)
I/flutter ( 5647): #13     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:654:14)
I/flutter ( 5647): #14     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:219:9)
I/flutter ( 5647): #15     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
I/flutter ( 5647): #16     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:127:5)
I/flutter ( 5647): #17     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:373:14)
I/flutter ( 5647): #18     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:470:12)
I/flutter ( 5647): #19     DragGestureRecognizer.handleEvent.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:143:50)
I/flutter ( 5647): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 5647): #21     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:143:11)
I/flutter ( 5647): #22     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 5647): #23     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 5647): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter ( 5647): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter ( 5647): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter ( 5647): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 5647): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter ( 5647): #29     _invoke1 (dart:ui/hooks.dart:165:13)
I/flutter ( 5647): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:5)
I/flutter ( 5647): (elided 2 frames from class _AssertionError)
I/flutter ( 5647): Handler: onUpdate
I/flutter ( 5647): Recognizer:
I/flutter ( 5647):   HorizontalDragGestureRecognizer#0de8b
I/flutter ( 5647): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5647): onpagechanged:1
I/flutter ( 5647): Another exception was thrown: 'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 602 pos 15: 'curve != null': is not true.
I/flutter ( 5647): onpagechanged:2
I/flutter ( 5647): Another exception was thrown: 'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 602 pos 15: 'curve != null': is not true.

                _controller.animateToPage(index, duration: Duration(milliseconds: 300), curve: null);



```

doctor -v:

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.11.3 at /Users/tbm/Documents/Flutter/flutter
    • Framework revision 72bf075e8d (7 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/tbm/Library/Android/sdk
    • Android NDK at /Users/tbm/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • MI 4W                     • 26a836fd      • android-arm • Android 6.0.1 (API 23)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

my code: https://ideone.com/lbl9YM

**Comment by darioielardi** [comment]
Animating with a `PageController` requires a `curve` parameter that in your code is passed as `null`. The framework is simply instructed to throw if that curve is null ( `assert(curve != null)` ).
