### ISSUE TITLE
Crash related to locale after upgrade?

### ISSUE THREAD

**Issue by lifenautjoe** [flutter/flutter#24492]
## Steps to Reproduce

1. Run `flutter upgrade`
2. Re-run app
3. Crash with exception related to locale (?)

## Logs

````
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following StateError was thrown building IconTheme(IconThemeData#2abdc(color:
flutter: Color(0xdd000000))):
flutter: Bad state: No element
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.first (dart:core/runtime/libarray.dart:92:5)
flutter: #1      _WidgetsAppState._resolveLocales (package:flutter/src/widgets/app.dart:785:78)
flutter: #2      _WidgetsAppState.initState (package:flutter/src/widgets/app.dart:663:15)
flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3808:58)
flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #41     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
flutter: #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #54     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
flutter: #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #64     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #65     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #66     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #67     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #68     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #70     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #71     main (package:Openbook/main.dart:129:3)
flutter: #72     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #73     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

````

The crash occurs in line

````
      final Locale locale = widget.localeResolutionCallback(preferredLocales.first, widget.supportedLocales);
````

of

`_WidgetsAppState._resolveLocales (package:flutter/src/widgets/app.dart:785:78)`

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14 18A391,
    locale en-NL)
    • Flutter version 0.11.3 at
      /Users/joelhernandez/Documents/code/flutter
    • Framework revision 72bf075e8d (8 days ago), 2018-11-09
      20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK
    28.0.2)
    • Android SDK at /Users/joelhernandez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for
      native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-C
      ode.flutter

[✓] Connected device (1 available)
    • 🥑 • 1d548d079169fde4d329284ea2448a5b8982eaf3 • ios • iOS
      12.0
```

**Comment by noordawod** [comment]
Fixed in Flutter now: https://github.com/flutter/flutter/pull/24481
