### ISSUE TITLE
flutter has exited unexpectedly with _Utf8Decoder.convert

### ISSUE THREAD

**Issue by kurakurakuda** [flutter/flutter#24523]
Hi everyone, when I run `flutter run --enable-software-rendering` in console of AndroidStudio, 
The application is crashed with below error.
In my console, 
I share my issue.  Could you someone help ?
I didn't find the root cause because I didn't change any encording setting...

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --enable-software-rendering

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x92 (at offset 0)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:568:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
 [32m[✓] [39m Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale ja-JP)
     [32m• [39m Flutter version 0.11.3 at C:\Users\81909\flutter\flutter
     [32m• [39m Framework revision 72bf075e8d (9 days ago), 2018-11-09 20:36:17 -0800
     [32m• [39m Engine revision 5646e86a6f
     [32m• [39m Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

 [32m[✓] [39m Android toolchain - develop for Android devices (Android SDK 27.0.3)
     [32m• [39m Android SDK at C:\Users\81909\AppData\Local\Android\sdk
     [32m• [39m Android NDK location not configured (optional; useful for native profiling support)
     [32m• [39m Platform android-27, build-tools 27.0.3
     [32m• [39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
     [32m• [39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
     [32m• [39m All Android licenses accepted.

 [32m[✓] [39m Android Studio (version 3.2)
     [32m• [39m Android Studio at C:\Program Files\Android\Android Studio
     [32m• [39m Flutter plugin version 30.0.1
     [32m• [39m Dart plugin version 181.5656
     [32m• [39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

 [32m[✓] [39m VS Code (version 1.28.2)
     [32m• [39m VS Code at C:\Users\81909\AppData\Local\Programs\Microsoft VS Code
     [32m• [39m Flutter extension version 2.20.0

 [32m[✓] [39m VS Code, 64-bit edition (version 1.28.2)
     [32m• [39m VS Code at C:\Program Files\Microsoft VS Code
     [32m• [39m Flutter extension version 2.20.0

 [32m[✓] [39m Connected device (1 available)
     [32m• [39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

 [32m• [39m No issues found!
```

**Comment by salihgueler** [comment]
Does your application crash on installing phase or after it runs? Because it seems to me that it's more of a encoding issue (you can refer to [this question](https://stackoverflow.com/questions/25720474/dart-upload-file-error-formatexception-bad-utf-8-encoding-0xbf))

**Comment by zoechi** [comment]
Merging with #15646
