### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xd8 (at offset 165)

### ISSUE THREAD

**Issue by ChuangLee** [flutter/flutter#24562]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk -v

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xd8 (at offset 165)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:484:15)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:87:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v0.11.7, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    [32m•[39m Flutter version 0.11.7 at C:\dev\flutter
    [32m•[39m Framework revision 7a005e1dcd (16 hours ago), 2018-11-19 11:14:05 -0500
    [32m•[39m Engine revision 2e06da3df9
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at C:\dev\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\dev\Android\android-studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at C:\dev\Android\android-studio
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m Connected device (1 available)
    [32m•[39m MIX 2 • 8c6c10d4 • android-arm64 • Android 8.0.0 (API 26)

[32m•[39m No issues found!
```

**Comment by zoechi** [comment]
Merging with #15646
