### ISSUE TITLE
Flutter cant download or upgrade dependencies

### ISSUE THREAD

**Issue by owolabiezekiel** [flutter/flutter#24588]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages upgrade

## exception

FileSystemException: FileSystemException: writeFrom failed, path = 'C:\flutter\version' (OS Error: Access is denied.
, errno = 5)

```
#0      _RandomAccessFile.writeFrom.<anonymous closure> (dart:io/file_impl.dart:868:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[!] Flutter (Channel beta, v0.11.8, on Microsoft Windows [Version 10.0.17763.134], locale en-US)
    • Flutter version 0.11.8 at C:\flutter
    • Framework revision f5b02e3c05 (8 hours ago), 2018-11-20 07:49:29 -0800
    • Engine revision 1baf081343
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\owoez\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Is this related to #24592? 
This looks like a permission problem in `C:\flutter`
How could you get this `flutter doctor -v` output when an hour later you run into #24592?
