### ISSUE TITLE
firebase messaging plugins causes app to crash after flutter /dart upgrade.

### ISSUE THREAD

**Issue by sulaemansantoso** [flutter/flutter#24639]
After flutter upgrade my app would crash. i can bypass the problem 
by removing firebase messaging plugins and its reference on my document , compile it and app would work. and afterward if i add firebase plugins back in and uncomment my reference it would still work.

but if i push to source control and pull it it would be the same problem all over again

basically the same with https://github.com/flutter/flutter/issues/23215 only on firebase messaging plugins

**Comment by zoechi** [comment]
Can you please try executing `flutter clean` every time after removing/adding the plugin.

Please add the output of `flutter doctor -v` and the crash log output.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by rshrc** [comment]
Hey @zoechi 

I am facing a similar issue. I've just added the plugin and just getting the token.. cross checked the manifest code and all. It was working perfectly fine a few days ago.

*This is the error log*

```
Launching lib/main.dart on Redmi Note 7 Pro in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /home/rshrc/develpoment/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+4/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/rshrc/develpoment/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.5/android/src/main/java/com/flutter_webview_plugin/WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/xyz.ajax.bethe( 8089): Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugins.firebasemessaging.FlutterFirebaseInstanceIDService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceIdService;
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(io.flutter.plugin.common.PluginRegistry$Registrar) (FirebaseMessagingPlugin.java:42)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.flutter.plugin.common.PluginRegistry) (GeneratedPluginRegistrant.java:19)
I/xyz.ajax.bethe( 8089):   at void xyz.ajax.bethel.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:11)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7224)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7213)
I/xyz.ajax.bethe( 8089):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1272)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2926)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3081)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1831)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdService" on path: DexPathList[[zip file "/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/lib/arm64, /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/xyz.ajax.bethe( 8089):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:171)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(io.flutter.plugin.common.PluginRegistry$Registrar) (FirebaseMessagingPlugin.java:42)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.flutter.plugin.common.PluginRegistry) (GeneratedPluginRegistrant.java:19)
I/xyz.ajax.bethe( 8089):   at void xyz.ajax.bethel.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:11)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7224)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7213)
I/xyz.ajax.bethe( 8089):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1272)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2926)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3081)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1831)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): 
I/xyz.ajax.bethe( 8089): Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugins.firebasemessaging.FlutterFirebaseInstanceIDService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceIdService;
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(io.flutter.plugin.common.PluginRegistry$Registrar) (FirebaseMessagingPlugin.java:42)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.flutter.plugin.common.PluginRegistry) (GeneratedPluginRegistrant.java:19)
I/xyz.ajax.bethe( 8089):   at void xyz.ajax.bethel.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:11)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7224)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7213)
I/xyz.ajax.bethe( 8089):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1272)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2926)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3081)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1831)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceIdService" on path: DexPathList[[zip file "/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/lib/arm64, /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/xyz.ajax.bethe( 8089):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:171)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(io.flutter.plugin.common.PluginRegistry$Registrar) (FirebaseMessagingPlugin.java:42)
I/xyz.ajax.bethe( 8089):   at void io.flutter.plugins.GeneratedPluginRegistrant.registerWith(io.flutter.plugin.common.PluginRegistry) (GeneratedPluginRegistrant.java:19)
I/xyz.ajax.bethe( 8089):   at void xyz.ajax.bethel.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:11)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7224)
I/xyz.ajax.bethe( 8089):   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7213)
I/xyz.ajax.bethe( 8089):   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1272)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2926)
I/xyz.ajax.bethe( 8089):   at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3081)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
I/xyz.ajax.bethe( 8089):   at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1831)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): 
W/Activity( 8089): Slow Operation: Activity xyz.ajax.bethel/.MainActivity onCreate took 965ms
I/FA      ( 8089): Tag Manager is not found and thus will not be used
W/xyz.ajax.bethe( 8089): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/xyz.ajax.bethe( 8089): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/xyz.ajax.bethe( 8089): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/xyz.ajax.bethe( 8089): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
I/OpenGLRenderer( 8089): Initialized EGL, version 1.4
D/OpenGLRenderer( 8089): Swap behavior 2
Syncing files to device Redmi Note 7 Pro...
I/Choreographer( 8089): Skipped 52 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer( 8089): Davey! duration=1026ms; Flags=1, IntendedVsync=158380525667962, Vsync=158381392334594, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=158381400070639, AnimationStart=158381401599650, PerformTraversalsStart=158381402694285, DrawStart=158381407988608, SyncQueued=158381411347410, SyncStart=158381411414337, IssueDrawCommandsStart=158381411575118, SwapBuffers=158381549214129, FrameCompleted=158381551994077, DequeueBufferDuration=7788000, QueueBufferDuration=670000, 
I/xyz.ajax.bethe( 8089): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.FirebaseMessagingService>: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at android.app.Service android.app.AppComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:103)
I/xyz.ajax.bethe( 8089):   at android.app.Service androidx.core.app.CoreComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3547)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.access$1400(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:200)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1689)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): 
I/xyz.ajax.bethe( 8089): Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at android.app.Service android.app.AppComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:103)
I/xyz.ajax.bethe( 8089):   at android.app.Service androidx.core.app.CoreComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3547)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.access$1400(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:200)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1689)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.VMClassLoader.findLoadedClass(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:738)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:363)
I/xyz.ajax.bethe( 8089):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/xyz.ajax.bethe( 8089):   at android.app.Service android.app.AppComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (AppComponentFactory.java:103)
I/xyz.ajax.bethe( 8089):   at android.app.Service androidx.core.app.CoreComponentFactory.instantiateService(java.lang.ClassLoader, java.lang.String, android.content.Intent) (CoreComponentFactory.java:68)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3547)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.access$1400(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:200)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1689)
I/xyz.ajax.bethe( 8089):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
I/xyz.ajax.bethe( 8089):   at void android.os.Looper.loop() (Looper.java:201)
I/xyz.ajax.bethe( 8089):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
I/xyz.ajax.bethe( 8089):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/xyz.ajax.bethe( 8089):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:873)
I/xyz.ajax.bethe( 8089): 
D/AndroidRuntime( 8089): Shutting down VM
E/AndroidRuntime( 8089): FATAL EXCEPTION: main
E/AndroidRuntime( 8089): Process: xyz.ajax.bethel, PID: 8089
E/AndroidRuntime( 8089): java.lang.RuntimeException: Unable to instantiate service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/lib/arm64, /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 8089): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3552)
E/AndroidRuntime( 8089): 	at android.app.ActivityThread.access$1400(ActivityThread.java:200)
E/AndroidRuntime( 8089): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
E/AndroidRuntime( 8089): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8089): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime( 8089): 	at android.app.ActivityThread.main(ActivityThread.java:6823)
E/AndroidRuntime( 8089): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8089): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime( 8089): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime( 8089): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/lib/arm64, /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime( 8089): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
E/AndroidRuntime( 8089): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8089): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8089): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
E/AndroidRuntime( 8089): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime( 8089): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3547)
E/AndroidRuntime( 8089): 	... 8 more
E/AndroidRuntime( 8089): 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
E/AndroidRuntime( 8089): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 8089): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 8089): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 8089): 		... 12 more
E/AndroidRuntime( 8089): 	Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
E/AndroidRuntime( 8089): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 8089): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 8089): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 8089): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8089): 		... 15 more
E/AndroidRuntime( 8089): 	Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/xyz.ajax.bethel-3_V-Cq-5F8UZxzIAKX-NyQ==/base.apk)
E/AndroidRuntime( 8089): 		... 15 more
I/Process ( 8089): Sending signal. PID: 8089 SIG: 9
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:45677/88spe6mDTek=/
```

*Behavior of the app*
The app crashes on launch. I thought it was device specific, but when I built it for more devices, it crashed there too. Removal of the plugin makes it work perfectly.

Thank You and I hope this was the correct amount of information that was required.

**Comment by broberts-nybble** [comment]
Hi Guys,

How was this fixed?

**Comment by Arjunraj-k** [comment]
just run `flutter clean` and run your app again.

**Comment by mnorhamizan** [comment]
I too am facing similar issue. Running ```flutter clean``` does not work
