### ISSUE TITLE
Impossible to run any flutter commands Windows 10 flutter_windows_v0.11.9-beta

### ISSUE THREAD

**Issue by artcrespo** [flutter/flutter#24663]
## Steps to Reproduce

Impossible to run flutter commands from the flutter_console.bat and from any command prompt or PowerShell if env variables (flutter\bin) added to PATH

Fresh install (first time)

Flutter version => flutter_windows_v0.11.9-beta

*** Windows 10 10.0.17134 Build 17134 with Git commands (added in PATH with the installation of Git) can be run from the command prompt or PowerShell

1. All the steps in the documentation
https://flutter.io/docs/get-started/install/windows
2. Double-clicking C:\src\flutter\flutter_console.bat
3. Console appears but running flutter doctor, the console displays an unhandled exception

## Logs

```
C:\Users\username>flutter doctor
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: D:\Program Files (x86)\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
#5      runSync (package:flutter_tools/src/base/process.dart:300:10)
#6      _runGit (package:flutter_tools/src/version.dart:516:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:16)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:69:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:171:48)
#14     new Usage (package:flutter_tools/src/usage.dart:27:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#21     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#22     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:51:10)
#32     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#33     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
same error as above
```

**Comment by artcrespo** [comment]
After reading many articles like this one it seems that is the spaces contained in the path for the execution of any command that causes an unhandled exception. https://github.com/flutter/flutter/issues/19359#issue-341177382

**Comment by philipjbousfield** [comment]
I have the same problem but different output. When I run flutter doctor I get:

'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale en-GB)
|CreateProcessW failed 2
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 652e65c9e22ba987)
\CreateProcessW failed 2                                                                                               Crash report written to C:\Users\philb\flutter\flutter_01.log;
please let us know at https://g

**Comment by zoechi** [comment]
Merging with #19359
