### ISSUE TITLE
flutter doctor fails

### ISSUE THREAD

**Issue by philipjbousfield** [flutter/flutter#24672]
## Steps to Reproduce

1. flutter doctor -v
2. ...
3. ...

## command

flutter doctor

## exception
```
ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\philb\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses
```

```
#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:244:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#11     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: ProcessException: The system cannot find the file specified.

  Command: C:\Users\philb\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:244:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#20     _doctorText (package:flutter_tools/runner.dart:187:19)
#21     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#22     _doctorText (package:flutter_tools/runner.dart:183:27)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#24     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#25     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#26     _handleToolError (package:flutter_tools/runner.dart:120:33)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#33     Future._complete (dart:async/future_impl.dart:476:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#37     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#44     Future._complete (dart:async/future_impl.dart:476:7)
#45     Stream.fold.<anonymous closure> (dart:async/stream.dart:726:18)
#46     _rootRun (dart:async/zone.dart:1120:38)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#50     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#51     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#52     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#53     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#54     _StringAdapterSink.close (dart:convert/string_conversion.dart:281:11)
#55     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:336:20)
#56     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:94:18)
#57     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#58     _rootRun (dart:async/zone.dart:1120:38)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#64     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#65     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#66     _rootRun (dart:async/zone.dart:1120:38)
#67     _CustomZone.run (dart:async/zone.dart:1021:19)
#68     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#69     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#70     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#71     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#72     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#73     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#74     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:70:11)
#75     _FilterSink.close (dart:io/data_transformer.dart:636:11)
#76     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:94:18)
#77     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#78     _rootRun (dart:async/zone.dart:1120:38)
#79     _CustomZone.run (dart:async/zone.dart:1021:19)
#80     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#81     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#82     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#83     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#84     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#85     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#86     _rootRun (dart:async/zone.dart:1120:38)
#87     _CustomZone.run (dart:async/zone.dart:1021:19)
#88     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#89     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#90     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#91     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#92     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
#93     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
#94     _StreamController.close (dart:async/stream_controller.dart:621:5)
#95     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#96     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#97     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#98     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#99     _rootRunUnary (dart:async/zone.dart:1132:38)
#100    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#101    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#102    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#103    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#104    _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#105    _StreamController._add (dart:async/stream_controller.dart:639:7)
#106    _StreamController.add (dart:async/stream_controller.dart:585:5)
#107    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#108    _rootRunUnary (dart:async/zone.dart:1132:38)
#109    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#113    _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#114    _StreamController._add (dart:async/stream_controller.dart:639:7)
#115    _StreamController.add (dart:async/stream_controller.dart:585:5)
#116    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1005:19)
#117    _rootRun (dart:async/zone.dart:1120:38)
#118    _CustomZone.run (dart:async/zone.dart:1021:19)
#119    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#120    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#121    _rootRun (dart:async/zone.dart:1124:13)
#122    _CustomZone.run (dart:async/zone.dart:1021:19)
#123    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#124    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#125    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#126    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#127    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
C:\Users\philb>flutter doctor -v
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "c:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale en-GB)
    • Flutter version 0.11.9 at c:\src\flutter
    • Framework revision d48e6e433c (2 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

|CreateProcessW failed 2
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 7093daea2779f3a2)
\CreateProcessW failed 2                                                                                               Crash report written to C:\Users\philb\flutter_09.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by philipjbousfield** [comment]
Sorry the log seemed to get missed off...….

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\philb\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

```
#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:244:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#11     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: ProcessException: The system cannot find the file specified.

  Command: C:\Users\philb\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses

#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:244:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#20     _doctorText (package:flutter_tools/runner.dart:187:19)
#21     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#22     _doctorText (package:flutter_tools/runner.dart:183:27)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#24     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#25     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#26     _handleToolError (package:flutter_tools/runner.dart:120:33)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#33     Future._complete (dart:async/future_impl.dart:476:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#37     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#44     Future._complete (dart:async/future_impl.dart:476:7)
#45     Stream.fold.<anonymous closure> (dart:async/stream.dart:726:18)
#46     _rootRun (dart:async/zone.dart:1120:38)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#50     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#51     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#52     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#53     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#54     _StringAdapterSink.close (dart:convert/string_conversion.dart:281:11)
#55     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:336:20)
#56     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:94:18)
#57     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#58     _rootRun (dart:async/zone.dart:1120:38)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#64     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#65     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#66     _rootRun (dart:async/zone.dart:1120:38)
#67     _CustomZone.run (dart:async/zone.dart:1021:19)
#68     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#69     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#70     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#71     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#72     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#73     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#74     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:70:11)
#75     _FilterSink.close (dart:io/data_transformer.dart:636:11)
#76     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:94:18)
#77     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#78     _rootRun (dart:async/zone.dart:1120:38)
#79     _CustomZone.run (dart:async/zone.dart:1021:19)
#80     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#81     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#82     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#83     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#84     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#85     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#86     _rootRun (dart:async/zone.dart:1120:38)
#87     _CustomZone.run (dart:async/zone.dart:1021:19)
#88     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#89     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#90     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#91     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#92     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
#93     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
#94     _StreamController.close (dart:async/stream_controller.dart:621:5)
#95     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#96     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#97     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#98     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#99     _rootRunUnary (dart:async/zone.dart:1132:38)
#100    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#101    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#102    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#103    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#104    _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#105    _StreamController._add (dart:async/stream_controller.dart:639:7)
#106    _StreamController.add (dart:async/stream_controller.dart:585:5)
#107    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#108    _rootRunUnary (dart:async/zone.dart:1132:38)
#109    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#113    _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#114    _StreamController._add (dart:async/stream_controller.dart:639:7)
#115    _StreamController.add (dart:async/stream_controller.dart:585:5)
#116    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1005:19)
#117    _rootRun (dart:async/zone.dart:1120:38)
#118    _CustomZone.run (dart:async/zone.dart:1021:19)
#119    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#120    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#121    _rootRun (dart:async/zone.dart:1124:13)
#122    _CustomZone.run (dart:async/zone.dart:1021:19)
#123    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#124    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#125    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#126    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#127    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by awazgyawali** [comment]
Does this file exist in your system
C:\Users\philb\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT

I think the Android SDK is not setuped in the correct directory.

**Comment by philipjbousfield** [comment]
C:\Users\philb\AppData\Local\Android\Sdk\tools\bin>dir
 Volume in drive C is Windows
 Volume Serial Number is 44EC-5869

 Directory of C:\Users\philb\AppData\Local\Android\Sdk\tools\bin

22/11/2018  17:40    <DIR>          .
22/11/2018  17:40    <DIR>          ..
22/11/2018  17:40             6,742 apkanalyzer
22/11/2018  17:40             2,227 archquery.bat
22/11/2018  17:40             3,035 avdmanager.bat
22/11/2018  17:40             2,215 jobb.bat
22/11/2018  17:40             3,839 lint.bat
22/11/2018  17:40             2,053 monkeyrunner.bat
22/11/2018  17:40             3,042 sdkmanager.bat
22/11/2018  17:40             2,189 uiautomatorviewer.bat
               8 File(s)         25,342 bytes
               2 Dir(s)  46,377,525,248 bytes free

Yep its there. How do I check if the sdk is correctly setup?

**Comment by philipjbousfield** [comment]
just found a reference to setting up ANDROID_HOME and ANDROID_SDK_ROOT. Set them both to C:\Users\philb\AppData\Local\Android\Sdk. No change.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by cdkd321** [comment]
just enter android studio, enter configure -> update android sdk -> Android Sdk Tools to new version . then exe the commend "flutter doctor -v"

**Comment by sandy9808** [comment]
hey have you found the solution to this issue
