### ISSUE TITLE
Why my hot reload button always gray ?

### ISSUE THREAD

**Issue by badboy-tian** [flutter/flutter#24674]
I use android studio develop flutter app, but the hot reload button is always gray, i can not click it and the app can not hot reload. 
![image](https://user-images.githubusercontent.com/2835129/48945631-f8d14600-ef65-11e8-830c-02888e85e130.png)

## Logs

```
➜  snapmod_app flutter analyze
Analyzing snapmod_app...                                         

   info • This function has a return type of 'Future<ResponseResult>', but doesn't end with a return statement • lib/api/base_api.dart:17:10 • missing_return
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:21:22 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:40:20 • unnecessary_brace_in_string_interps
   info • This function has a return type of 'Future<ResponseResult>', but doesn't end with a return statement • lib/api/base_api.dart:52:10 • missing_return
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:56:26 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:57:22 • unnecessary_brace_in_string_interps
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/model/AVObject.dart:1:8 • unused_import
   info • Unused import: 'dart:async' • lib/model/AVObject.dart:2:8 • unused_import

8 issues found. (ran in 1.0s)
➜  snapmod_app flutter run --verbose
[  +19 ms] executing: [/Users/tian/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/tian/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] executing: [/Users/tian/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/tian/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d48e6e433cc5ca67b24b19f70aaa197e84ba63c1
[        ] executing: [/Users/tian/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 days ago
[        ] executing: [/Users/tian/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.11.9-0-gd48e6e433
[ +190 ms] executing: /Users/tian/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/tian/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           eccdc00f               device usb:337903616X product:natrium model:MI_5s_Plus device:natrium transport_id:1
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:2
[   +7 ms] executing: idevice_id -h
[  +25 ms] /usr/bin/xcrun simctl list --json devices
[ +155 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/tian/Library/Android/sdk/platform-tools/adb -s eccdc00f shell getprop
[  +53 ms] ro.hardware = qcom
[   +1 ms] /Users/tian/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +20 ms] ro.hardware = ranchu
[   +2 ms] MI 5s Plus                   • eccdc00f      • android-arm64 • Android 7.0 (API 24)
[        ] Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 9 (API 28) (emulator)
[   +8 ms] "flutter run" took 431ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:249:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/tian/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


```

```
flutter analyze
Analyzing snapmod_app...                                         

   info • This function has a return type of 'Future<ResponseResult>', but doesn't end with a return statement • lib/api/base_api.dart:17:10 • missing_return
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:21:22 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:40:20 • unnecessary_brace_in_string_interps
   info • This function has a return type of 'Future<ResponseResult>', but doesn't end with a return statement • lib/api/base_api.dart:52:10 • missing_return
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:56:26 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/api/base_api.dart:57:22 • unnecessary_brace_in_string_interps
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/model/AVObject.dart:1:8 • unused_import
   info • Unused import: 'dart:async' • lib/model/AVObject.dart:2:8 • unused_import

8 issues found. (ran in 1.0s)

```

```
  snapmod_app flutter doctor -v
[✓] Flutter (Channel dev, v0.11.9, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 0.11.9 at /Users/tian/flutter
    • Framework revision d48e6e433c (2 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/tian/Library/Android/sdk
    • Android NDK at /Users/tian/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.3
    • Dart plugin version 183.4284.122

[✓] Connected device (2 available)
    • MI 5s Plus                   • eccdc00f      • android-arm64 • Android 7.0 (API 24)
    • Android SDK built for x86 64 • emulator-5554 • android-x64   • Android 9 (API 28) (emulator)

• No issues found!
➜  snapmod_app 

```

**Comment by HeavenOSK** [comment]
Do you use just ‘Run’ button to launch an app? If you not tried to use ‘Debug Run⚙️’ button, have a try!

**Comment by badboy-tian** [comment]
@HeavenOSK can not work

![image](https://user-images.githubusercontent.com/2835129/48950938-ca5c6680-ef77-11e8-8712-2bfaadacb5e3.png)

**Comment by HeavenOSK** [comment]
Sorry I cannot help you.

**Comment by badboy-tian** [comment]
I fixed it. 
![image](https://user-images.githubusercontent.com/2835129/48990761-af9e1380-f16a-11e8-85ca-50015388be7c.png)
because set proxy

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/16875#issuecomment-384758566

**Comment by ionut442** [comment]
> I fixed it.
> ![image](https://user-images.githubusercontent.com/2835129/48990761-af9e1380-f16a-11e8-85ca-50015388be7c.png)
> because set proxy

@badboy-tian I have the same problem. Can you please tell me when can I find these settings?

**Comment by badboy-tian** [comment]
@ionut442  just close your http proxy

**Comment by VenkateshMahi** [comment]
If you're opening IntelliJ(flutter project) for the first time after installing Flutter and Dart plugins, just restart the IntelliJ by clicking on File - > Invalidate Caches/Restart -> Just Restart.

Tested and it works fine.!
