### ISSUE TITLE
flutter run not working on ios simulator

### ISSUE THREAD

**Issue by vipinagrahari** [flutter/flutter#24695]
## command

flutter run --flavor development -t lib/flavors/main_dev.dart -v

## exception

```
ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/vipin/Library/Developer/CoreSimulator/Devices/DAE7804F-C35A-4847-94AF-BC094BE584DC/data/Library/Caches/com.apple.mobile.installd.staging/temp.FTuLly/extracted/Payload/Runner.app
Failed to load Info.plist from bundle at path /Users/vipin/Library/Developer/CoreSimulator/Devices/DAE7804F-C35A-4847-94AF-BC094BE584DC/data/Library/Caches/com.apple.mobile.installd.staging/temp.FTuLly/extracted/Payload/Runner.app
Underlying error (domain=MIInstallerErrorDomain, code=35):
	Failed to load Info.plist from bundle at path /Users/vipin/Library/Developer/CoreSimulator/Devices/DAE7804F-C35A-4847-94AF-BC094BE584DC/data/Library/Caches/com.apple.mobile.installd.staging/temp.FTuLly/extracted/Payload/Runner.app
  Command: /usr/bin/xcrun simctl install DAE7804F-C35A-4847-94AF-BC094BE584DC /Users/vipin/Documents/freightbro/product/app-flutter/fb-flutterapp/frb_shipper/build/ios/iphonesimulator/Runner.app
```

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:125:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:396:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:308:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#11     Future._complete (dart:async/future_impl.dart:476:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#14     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#15     getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#22     Future._complete (dart:async/future_impl.dart:476:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#26     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#33     Future._complete (dart:async/future_impl.dart:476:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#37     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#44     Future._complete (dart:async/future_impl.dart:476:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#51     Future._complete (dart:async/future_impl.dart:476:7)
#52     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#53     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v0.11.9, on Mac OS X 10.14.1 18B75, locale en-IN)
    [32m•[39m Flutter version 0.11.9 at /Users/vipin/Downloads/soft/flutter
    [32m•[39m Framework revision d48e6e433c (3 days ago), 2018-11-20 22:05:23 -0500
    [32m•[39m Engine revision 5c8147450d
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at /Users/vipin/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/vipin/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 30.0.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone XR • DAE7804F-C35A-4847-94AF-BC094BE584DC • ios • iOS 12.1 (simulator)

[32m•[39m No issues found!
```

**Comment by zoechi** [comment]
Merging with #22787

**Comment by vipinagrahari** [comment]
This issue is Nowhere related to #22787

**Comment by vipinagrahari** [comment]
> Merging with #22787

This is Nowhere related with #22787

**Comment by kyleDEVV** [comment]
So I just got the new MacBook Pro 2018 (15") and I was greated with this exact error when opening some old projects, this problem isn't major. When I rerun the debug-request I get through.

**Comment by zoechi** [comment]
How did you move the project? Did you checkout from GitHub or similar or did you copy from machine to machine.
If you copied manually try deleting `ios/` and `android/`, run `flutter create .` and re-apply manual changes you made to files in these directories before.

**Comment by nihalreddy33** [comment]
Restart your emulator once, it worked for me.
