### ISSUE TITLE
NPE on firebase_auth 6.x.x

### ISSUE THREAD

**Issue by KammererTob** [flutter/flutter#24708]
I cannot exactly pinpoint the version, but i am currently using 0.6.6 and experienced this one before on 0.6.2+1. It does not happen on 0.5.20/19

## Steps to Reproduce

1. Install app
2. Call FirebaseAuth.instance.currentUser() with no user
3. NullPointerException in Logs.

## Logs

```
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.getAuth(FirebaseAuthPlugin.java:57)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:66)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#plugins.flutter.io/firebase_auth(15894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale de-DE)
    • Flutter version 0.11.9 at C:\SDKs\flutter
    • Framework revision d48e6e433c (4 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\SDKs\android
    • Java binary at: D:\Programme\JDK\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\puelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • Nexus 5 • 04e4439e2522805e • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 2 categories.
```

**Comment by KammererTob** [comment]
This seem to be resolved together with:
https://github.com/flutter/flutter/issues/24435

Not sure what exactly made the error disappear, but here is my current config:

1. flutter 1.0.0 (0.11.13 also worked)

2.  changed google-services:3.2.1 to 4.2.0
```
classpath 'com.android.tools.build:gradle:3.2.1'
classpath 'com.google.gms:google-services:4.2.0'
```

3.  changed firebase_auth to 0.6.6 from 0.5.19
```
firebase_auth: ^0.6.6
google_sign_in: ^3.2.4
```
