### ISSUE TITLE
Exceptions during hot reload render poorly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#24723]
For example:
```
Performing hot reload...                                        I/flutter (18351): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18351): The following assertion was thrown during performLayout():
I/flutter (18351): RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
I/flutter (18351): Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
I/flutter (18351): defeats the point of viewports being lazy.
I/flutter (18351): If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
I/flutter (18351): to achieve that effect by just giving the viewport loose constraints, without needing to measure its
I/flutter (18351): intrinsic dimensions.
I/flutter (18351): 
I/flutter (18351): When the exception was thrown, this was the stack:
I/flutter (18351): #0      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1549:9)
...
```

**Comment by Piinks** [comment]
If @goderbauer's comment is correct, this is a quick fix. Can you clarify @Hixie?

**Comment by Hixie** [comment]
Yup.

**Comment by jonahwilliams** [comment]
This is still the case today. The fix would be to make the Device logger's aware of any active status spinners when run from the terminal. If present, logs should be deferred until the spinner is completed or cancelled

**Comment by pedromassangocode** [comment]
This does not seems valid anymore, however, There may be a new issue here. The actual message on latest `master` channel is:

```bash
Performing hot reload...
Syncing files to device iPhone 11 Pro Max...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Home(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 381 pos 10: 'data != null'

The relevant error-causing widget was: 
  Home file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:5:13
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:381:10)
#3      Home.build (package:flutter_example/main.dart:19:22)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4715:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4641:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4335:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 528 libraries in 286ms.
```

New new issue may be that the logs shows the error message first and then the "Reloaded" message, from my understanding is that Flutter reload first to get the new changes and then it should show the error. If this is valid we definitely should track on a separate issue.

Closing this as fixed.

<details><summary>Sample code (to reproduce just replace the text string with null and hot-reload)</summary>

```dart
import 'package:flutter/material.dart';

void main() =>
    runApp(MaterialApp(
      home: Home(),
    ),
    );

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox(
        height: 320,
        child: PageView(
          children: [
            RaisedButton(
              onPressed: () {},
              child: Text('Flutter'),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.200, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.200 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 25b8c095cd (5 hours ago), 2020-09-16 01:27:03 -0400
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>
