### ISSUE TITLE
A TextField as a child of a Row would be an error

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#24724]
## code
```dart
Row(children: <Widget>[TextField()],)
```

## Logs

```
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter: The following assertion was thrown during performLayout():
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter: BoxConstraints forces an infinite width.
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter: These invalid constraints were provided to RenderRepaintBoundary's layout() function by the
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter: following function, which probably computed the invalid constraints in question:
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter:   _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:815:11)
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter: The offending constraints were:
11-26 13:38:59.811 31878-31893/com.yilinggou I/flutter:   BoxConstraints(w=Infinity, 0.0<=h<=Infinity)
11-26 13:38:59.815 31878-31893/com.yilinggou I/flutter: When the exception was thrown, this was the stack:
11-26 13:38:59.827 31878-31893/com.yilinggou I/flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:504:9)
11-26 13:38:59.827 31878-31893/com.yilinggou I/flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:545:21)
11-26 13:38:59.827 31878-31893/com.yilinggou I/flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:551:6)
11-26 13:38:59.827 31878-31893/com.yilinggou I/flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1549:24)
11-26 13:38:59.827 31878-31893/com.yilinggou I/flutter: #4      _RenderDecoration._layout.layoutLineBox (package:flutter/src/material/input_decorator.dart:815:11)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #5      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:847:18)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #6      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:976:44)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.828 31878-31893/com.yilinggou I/flutter: #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
11-26 13:38:59.829 31878-31893/com.yilinggou I/flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.829 31878-31893/com.yilinggou I/flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.829 31878-31893/com.yilinggou I/flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #20     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #26     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #28     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:549:15)
11-26 13:38:59.830 31878-31893/com.yilinggou I/flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #30     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.831 31878-31893/com.yilinggou I/flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.832 31878-31893/com.yilinggou I/flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #50     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.833 31878-31893/com.yilinggou I/flutter: #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #63     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #65     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #67     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.834 31878-31893/com.yilinggou I/flutter: #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #77     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #78     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
11-26 13:38:59.835 31878-31893/com.yilinggou I/flutter: #79     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
11-26 13:38:59.836 31878-31893/com.yilinggou I/flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #87     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #88     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
11-26 13:38:59.837 31878-31893/com.yilinggou I/flutter: #89     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
11-26 13:38:59.838 31878-31893/com.yilinggou I/flutter: (elided one frame from package dart:async)
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter: The following RenderObject was being processed when the exception was fired:
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   _RenderDecoration#64859 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   GestureDetector ← IgnorePointer ← Semantics ← TextField ← Row ← Column ← DecoratedBox ← ⋯
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   parentData: <none> (can use size)
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   constraints: BoxConstraints(unconstrained)
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   size: MISSING
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter: This RenderObject had the following descendants (showing up to depth 5):
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   RenderRepaintBoundary#4c5b7 NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:     RenderPointerListener#b9174 NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:       RenderSemanticsAnnotations#419d6 NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:         RenderIgnorePointer#e23dc NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:           RenderLeaderLayer#f901f NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   RenderConstrainedBox#21447 NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.846 31878-31893/com.yilinggou I/flutter:   RenderCustomPaint#10aca NEEDS-LAYOUT NEEDS-PAINT
11-26 13:38:59.847 31878-31893/com.yilinggou I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
11-26 13:38:59.849 31878-31893/com.yilinggou I/flutter: Another exception was thrown: RenderBox was not laid out: _RenderDecoration#64859 relayoutBoundary=up5 NEEDS-PAINT
11-26 13:38:59.851 31878-31893/com.yilinggou I/flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#1cba0 relayoutBoundary=up4 NEEDS-PAINT
11-26 13:38:59.853 31878-31893/com.yilinggou I/flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#b14b9 relayoutBoundary=up3 NEEDS-PAINT
11-26 13:38:59.855 31878-31893/com.yilinggou I/flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#9f7f3 relayoutBoundary=up2 NEEDS-PAINT
11-26 13:38:59.857 31878-31893/com.yilinggou I/flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#ab1ab relayoutBoundary=up1 NEEDS-PAINT
11-26 13:38:59.911 31878-31893/com.yilinggou I/flutter: Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
```
## environment

```
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.15063], locale zh-CN)
    • Flutter version 0.11.9 at C:\flutter\flutter
    • Framework revision d48e6e433c (5 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor--android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • t1host • 192.168.0.129:5555 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```

**Comment by lishuhao** [comment]
This is not a bug. Try this
```dart
Row(
     children: <Widget>[
         Expanded(child: TextField()),
     ],
)
```

**Comment by zoechi** [comment]
Thanks @lishuhao 

@2534290808 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by 2534290808** [comment]
Ok, thank you for your answer

**Comment by rhodul** [comment]
Added autofocus to the example from @lishuhao and it fails again:
```
Row(
     children: <Widget>[
         Expanded(child: TextField(autofocus: true)),
     ],
)
```

**Comment by patelkrunal78** [comment]
This Might Help You....
https://icetutor.com/question/textfield-inside-of-row-causes-layout-exception-unable-to-calculate-size/

**Comment by JinHoSo** [comment]
@rhodul same here, autofocus caused the error
