### ISSUE TITLE
I used path_provider and there is an error that I can't open the file.

### ISSUE THREAD

**Issue by gaojuanjuan** [flutter/flutter#24765]
```
E/flutter (29646): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (29646): FileSystemException: Cannot open file, path = '/data/user/0/com.zyqy.mengwajimobile/app_flutter/allkb.json' (OS Error: No such file or directory, errno = 2)
E/flutter (29646): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
E/flutter (29646): #1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (29646): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (29646): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (29646): #4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (29646): #5      Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter (29646): #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter (29646): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (29646): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by kangwang1988** [comment]
Can you make sure whether the allkb.json exists in the app_flutter folder?

**Comment by kangwang1988** [comment]
Paste the sample code to reproduce this problem and the flutter doctor -v for us to figure out what is happening.

**Comment by gaojuanjuan** [comment]
sample code:
```
  Future<File> _getLocalFile() async {
    final dir = await getDirectory();

    File file = new File('${dir.path}/$tag.json');
    print('创建文件夹了${file.path}');
    file.exists().then((e) {
      print('目录存在但文件不存在');
    });
    return file;
  }
```
log：
```
I/flutter ( 6678): 创建文件夹了/data/user/0/com.zyqy.mengwajimobile/app_flutter/allkb.json
I/flutter ( 6678): 目录存在但文件不存在
```

flutter doctor -v:
```
C:\MyWorkSpace\mengwaji_mobile>flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    • Flutter version 0.11.3 at C:\flutter
    • Framework revision 72bf075e8d (2 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\73951\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\73951\AppData\Local\Android\Sdk
    • Java binary at: C:\DevelopmentTool\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\DevelopmentTool\AndroidStudio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

**Comment by gaojuanjuan** [comment]
The file was not created successfully

**Comment by gaojuanjuan** [comment]
> Paste the sample code to reproduce this problem and the flutter doctor -v for us to figure out what is happening.

simple code:
```
  Future<File> _getLocalFile() async {
    final dir = await getDirectory();

    File file = new File('${dir.path}/$tag.json');
    var isExist = await file.exists();
    if (isExist) {
      print('File exists------------------>_getLocalFile()');
    } else {
      print('file does not exist---------->_getLocalFile()');
    }
    return file;
  }
```
log:
```
file does not exist---------->_getLocalFile()
```
flutter doctor -v:
```
C:\MyWorkSpace\mengwaji_mobile>flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    • Flutter version 0.11.3 at C:\flutter
    • Framework revision 72bf075e8d (2 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\73951\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\73951\AppData\Local\Android\Sdk
    • Java binary at: C:\DevelopmentTool\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\DevelopmentTool\AndroidStudio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

**Comment by zoechi** [comment]
> log:
> 
>     file does not exist---------->_getLocalFile()

seems to indicate that the file doesn't exist. So why do you expect to be able to open it?

**Comment by kangwang1988** [comment]
Directory tempDir = await getTemporaryDirectory();
  String tempPath = tempDir.path;
  File f = new File("${tempPath}/allkb.kb");
  f.writeAsStringSync("KWLM");
  bool exists = f.existsSync();

@gaojuanjuan 
Add the f.writeAsStringSync("KWLM") to see if right.

**Comment by gaojuanjuan** [comment]
Ok, I will try，thank you

**Comment by zoechi** [comment]
I'm going to close because that looks like a support request that is better discussed
in one of the other channels listed at http://flutter.io/support .

**Comment by gaojuanjuan** [comment]
> I'm going to close because that looks like a support request that is better discussed
> in one of the other channels listed at http://flutter.io/support .

ok

**Comment by Onus31** [comment]
Please give me answer for this error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot create file, path = '/data/user/0/com.example.qrcreator/cache/' (OS Error: Is a directory, errno = 21)

**Comment by tamoyal** [comment]
Why is this closed? It's still a problem and it's a bit strange.  I just randomly get write failures to the application documents directory. I guess I'll use the temp directory for now but it's not ideal

**Comment by andynvt** [comment]
I got `FileSystemException: Cannot create file, path = '/storage/emulated/0/Download/test_HMID_v1.0.37_b134(20210525_1014).apk' (OS Error: File exists, errno = 17)`
