### ISSUE TITLE
Could not start Observatory HTTP server ...

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2478]
If I interactively dismiss a flutter app while `flutter start` is underway with a new app, the following persistent error usually results. Rebooting the phone corrects the problem.

```
I/flutter : SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 8181
I/flutter : #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
I/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1137)
I/flutter : #2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
I/flutter : #3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
I/flutter : #4      _Future._completeWithValue (dart:async/future_impl.dart:424)
I/flutter : #5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
I/flutter : #6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
I/flutter : #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/flutter : #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
I/flutter : #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
I/flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
