### ISSUE TITLE
Flutter tool crash when downgrading

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#24792]
When downgrading from an internal testing build to beta channel v0.11.9 machine, the build process crashed during flutter run:

## command

flutter run --verbose

## exception
```
NoSuchMethodError: NoSuchMethodError: The method 'allElements' was called on null.
Receiver: null
Tried calling: allElements("activity")
```

```
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ApkManifestData.parseFromXmlDump (package:flutter_tools/src/application_package.dart:427:53)
#2      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:66:10)
#3      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:100:27)
<asynchronous suspension>
#4      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#26     Future._complete (dart:async/future_impl.dart:476:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.9 at /Users/timsneath/flutter
    • Framework revision d48e6e433c (22 hours ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/timsneath/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

/cc @tvolkert @timsneath

**Comment by cbracken** [comment]
Given that flutter version changes don't happen all that frequently for most users (other than those on master), one solution here would be to assume a clean build is required if we detect the flutter version has changed since the last build.

The `Fingerprinter` attempts to compute whether builds are necessary based on the SHAs of a declared list of expected inputs, outputs, and the transitive closure of source deps as emitted by gen_snapshot and the kernel compiler depfiles. Assuming correctly declared inputs, outputs and depfiles, that should be sufficient in the absence of changes to the build logic itself. In order to catch changes to the build logic, declaring flutter itself as an input makes sense (one way might be just check the commit SHA via git rev-parse HEAD).

**Comment by jonahwilliams** [comment]
Inspecting this code: https://github.com/flutter/flutter/blob/7f3c9b6bdab5a38cfa9eb4ba5aa5d7c5378282f3/packages/flutter_tools/lib/src/application_package.dart#L190

I think the issue was fixed by existing when parsing failed with the change before https://github.com/flutter/flutter/commit/dffbfebbf1c6ecacf6890843b0a13bb4e74598d3 or similar.
