### ISSUE TITLE
Test harness should check for running Timers and AnimationControllers

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2481]
If an AnimationController is still running after a test ends, the code will assert in any subsequent test, as shown in the log below. According to @Hixie, this happens because the test harness resets all AnimationControllers back to 0.0 before testWidgets() is called.

IMO, any AnimationControllers or Timers that are running after a test should be asserted as a bug. We should assert on running Timers and AnimationControllers instead of setting them back to zero. At least for AnimationControllers, the error message should talk about calling `stop()` in `dispose()`.

Inevitably, some developer somewhere will want to run an AnimationController or Timer that spans tests, so it should probably be possible to disable this check.

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: a5887b6fb41c3a5e343c6132bb89cb1c10fafb95 (3 hours ago)
Engine:    70b92500df0006a9756fb9302a431322456a38fd
```

### Logs
```
00:01 +3: TabBar tap selection bar                                                                 
-- EXCEPTION CAUGHT BY SCHEDULER LIBRARY -------------------------------
An exception was raised during a scheduler callback:
'/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/animation/animation_controller.dart': Failed assertion: line 249 pos 12: 'timeInSeconds >= 0.0' is not true.
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      _InterpolationSimulation.x (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/animation/animation_controller.dart:249:12)
#2      AnimationController._tick (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/animation/animation_controller.dart:220:26)
#3      Ticker._tick (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/scheduler/ticker.dart:68:12)
#4      BindingBase&Scheduler.invokeFrameCallback (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/scheduler/scheduler.dart:274:15)
#5      BindingBase&Scheduler._invokeTransientFrameCallbacks.<anonymous closure> (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/scheduler/scheduler.dart:228:9)
#6      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#7      BindingBase&Scheduler._invokeTransientFrameCallbacks (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/scheduler/scheduler.dart:226:15)
#8      BindingBase&Scheduler.handleBeginFrame (/media/jimbe/mojossd/abc/src/example/test/packages/flutter/src/scheduler/scheduler.dart:248:5)
#9      WidgetTester.pump (/media/jimbe/mojossd/abc/src/example/test/packages/flutter_test/src/widget_tester.dart:121:13)
#10     WidgetTester.pumpWidget (/media/jimbe/mojossd/abc/src/example/test/packages/flutter_test/src/widget_tester.dart:102:5)
#11     main.<anonymous closure>.<anonymous closure> (///media/jimbe/mojossd/abc/src/example/test/abc_test.dart:130:20)
```

**Comment by abarth** [comment]
Great idea.  Found a bunch of bugs.
