### ISSUE TITLE
ReordableListView throws an exception when item of the list changes during reorder

### ISSUE THREAD

**Issue by madtocc** [flutter/flutter#24822]
I have a list of items and when the state of any item of the list changes it throws an exception

## Steps to Reproduce
1. Click and hold one item of the ReordableListView
2. Change the state of one or more items (while holding or dragging one item of the list)

## Logs
```
I/flutter (27768): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27768): The following assertion was thrown building
I/flutter (27768): _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#d8dc4](dirty, state: _OverlayEntryState#3b794):
I/flutter (27768): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1493 pos 18: 'debugDoingThisResize
I/flutter (27768): || debugDoingThisLayout ||
I/flutter (27768):                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not
I/flutter (27768):                  true.
I/flutter (27768):
I/flutter (27768): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (27768): more information in this error message to help you determine and fix the underlying cause.
I/flutter (27768): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (27768):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (27768):
I/flutter (27768): When the exception was thrown, this was the stack:
I/flutter (27768): #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1493:18)
I/flutter (27768): #3      RenderBox.size (package:flutter/src/rendering/box.dart:1499:6)
I/flutter (27768): #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2426:24)
I/flutter (27768): #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2166:24)
I/flutter (27768): #6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2037:39)
I/flutter (27768): #7      _DragAvatar._build (package:flutter/src/widgets/drag_target.dart:699:39)
I/flutter (27768): #8      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
I/flutter (27768): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (27768): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (27768): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #14     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter (27768): #15     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (27768): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #17     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (27768): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter (27768): #28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (27768): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (27768): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (27768): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (27768): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (27768): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (27768): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (27768): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #58     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (27768): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (27768): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (27768): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (27768): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #64     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter (27768): #65     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (27768): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (27768): #67     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
I/flutter (27768): #68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (27768): #69     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
I/flutter (27768): #70     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter (27768): #71     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter (27768): #72     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter (27768): #73     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
I/flutter (27768): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27768): #75     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (27768): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27768): #77     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (27768): #78     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (27768): #79     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (27768): #80     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (27768): #81     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (27768): #82     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (27768): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (27768): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (27768): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (27768): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27768): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27768): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (27768): #89     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (27768): #90     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (27768): (elided 2 frames from class _AssertionError)
I/flutter (27768): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel master, v0.11.11-pre.11, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.11.11-pre.11 at /Users/mt/flutter
    • Framework revision 9d878ca493 (9 hours ago), 2018-11-27 22:31:49 -0800
    • Engine revision be973ea196
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/mt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/mt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • ZUK Z2131 • 1eb6bcb2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by madtocc** [comment]
Hi, thanks for the quick reply :) I made a small example to show what happened, however I couldn't reproduce the error. So I revised my app code and it turns out that it happens because the ReordableListView is inside the frontlayer of the backdrop menu. When I remove the backdrop menu this exception is not shown. The backdrop menu was adapted from the gallery app ... Let me know if it's relevant to post a code including the backdrop so the exception is shown. 
I'm sorry I thought this always happened and since it is not a big deal I guess you can close it. I will try to dig deeper to figure out what can cause this.
Thanks

**Comment by zoechi** [comment]
A full running example that we can just copy to `lib/main.dart` of a new project created with `flutter create foo` would be very much appreciated.

I'm going to close.
If you have such a reproduction just post it as comment and I'll reopen.
