### ISSUE TITLE
Why must I use root permission to open?

### ISSUE THREAD

**Issue by scottjeremy** [flutter/flutter#24849]
```
#which flutter
/home/user/Software/flutter/bin/flutter

#flutter run
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                          ⣻
Oops; flutter has exited unexpectedly.
 
Sending crash report to Google.
```

When I using root, it work...

I use ```ln``` to connect to /usr/bin
```
#whick flutter
/usr/bin/flutter

#sudo flutter run
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Using hardware rendering with device Android SDK built for x86. If you get graphics
artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.4s
Resolving dependencies...                                    0.8s
Gradle task 'assembleDebug'...                                   
Gradle task 'assembleDebug'... Done                          0.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Android SDK built for x86...             
D/EGL_emulation( 9164): eglMakeCurrent: 0xe89857e0: ver 2 0 (tinfo 0xe8983e30)
D/        ( 9164): HostConnection::get() New Host Connection established 0xe5d56d80, tid 9191
D/EGL_emulation( 9164): eglMakeCurrent: 0xe69cd060: ver 2 0 (tinfo 0xe69d0e10)
 0.9s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state),
press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:35691/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

so do vscode, I have to use root permissions to start vscode so it can be debugged. If not
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
ProcessException: Process "/home/scott/nomnom/android/gradlew" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip
Exception in thread "main" java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2037)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /home/scott/nomnom/android/gradlew -v
Exited (sigterm)
```

```
#flutter doctor -v
[✓] Flutter (Channel beta, v0.11.10, on Linux, locale zh_CN.UTF-8)
    • Flutter version 0.11.10 at /home/scott/Software/flutter
    • Framework revision c27c4a265e (2 days ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/scott/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/scott/Software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/scott/Software/android-studio
    • Flutter plugin version 31.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Because Flutter generates some executables in its installation directory on-demand.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
