### ISSUE TITLE
e2e testing in Stock does not work

### ISSUE THREAD

**Issue by yathit** [flutter/flutter#24841]
## Steps to Reproduce

Run end-to-end test for stock app

1. cd example/stocks
2. flutter drive --target=test_driver/scroll_perf.dart

## Logs

```
I/flutter (11287): Observatory listening on http://127.0.0.1:34629/
Unhandled exception:
NoSuchMethodError: The method 'setUpAll' was called on null.
Receiver: null
Tried calling: setUpAll(Closure: () => Future<Null>)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      setUpAll (package:test_api/test_api.dart:255:40)
#2      main (file:///home/mbikyaw/dwork/examples/stocks/test_driver/scroll_perf_test.dart:13:3)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
 output of running `flutter doctor -v` 

```
[✓] Flutter (Channel beta, v0.11.11, on Linux, locale en_US.UTF-8)
    • Flutter version 0.11.11 at /home/k/flutter
    • Framework revision e7680128af (25 hours ago), 2018-11-27 21:33:50 -0500
    • Engine revision be973ea196
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/k/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/k/opt/android-studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /home/k/opt/android-studio/bin/studio.sh
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /home/k/opt/android-studio/bin/studio.sh
    ✗ Android Studio not found at /home/k/opt/android-studio/bin/studio.sh
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /home/k/opt/idea-IU-181.4668.68
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 1 category.

```

**Comment by jonahwilliams** [comment]
I accidentally change this during a refactor. This should import package:test not test:api and it will work as expected

**Comment by yathit** [comment]
@jonahwilliams  Thansk. Yes work after changes. But where is stocks_scroll_perf file? I cannot find it.

**Comment by jonahwilliams** [comment]
I'm not sure, it might depend on where you run it from. I would use grep or something similar to search for it

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.
