### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by manhnt79** [flutter/flutter#24850]
```
I/flutter (29722): The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#4b6f3](state:
I/flutter (29722): OverlayState#9ec1a(tickers: tracking 12 tickers, entries: [OverlayEntry#dfb4a(opaque: false;
I/flutter (29722): maintainState: false), OverlayEntry#b21ce(opaque: false; maintainState: true),
I/flutter (29722): OverlayEntry#1713a(opaque: true; maintainState: false), OverlayEntry#8877c(opaque: false;
I/flutter (29722): maintainState: true), OverlayEntry#8ccce(opaque: true; maintainState: false),
I/flutter (29722): OverlayEntry#734af(opaque: false; maintainState: true)])):
I/flutter (29722): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4051 pos 14:
I/flutter (29722): '_dependents.isEmpty': is not true.
I/flutter (29722):
I/flutter (29722): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (29722): more information in this error message to help you determine and fix the underlying cause.
I/flutter (29722): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (29722):   https://github.com/flutter/flutter/issues/new
I/flutter (29722):
I/flutter (29722): When the exception was thrown, this was the stack:
I/flutter (29722): #2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4051:14)
I/flutter (29722): #3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4053:6)
I/flutter (29722): #4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1718:25)
I/flutter (29722): #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1718:59)
I/flutter (29722): #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #14     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4754:16)
I/flutter (29722): #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #48     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #68     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (29722): #69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3688:14)
I/flutter (29722): #75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1717:13)
I/flutter (29722): #76     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1726:7)
I/flutter (29722): #77     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2955:29)
I/flutter (29722): #78     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4484:11)
I/flutter (29722): #79     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
I/flutter (29722): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (29722): #81     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (29722): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
I/flutter (29722): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter (29722): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter (29722): #85     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
I/flutter (29722): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
I/flutter (29722): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (29722): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (29722): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (29722): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (29722): #91     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (29722): #92     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (29722): (elided 2 frames from class _AssertionError)
I/flutter (29722): ═════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Can you please provide additional information how to reproduce?

**Comment by zoechi** [comment]
#12964 looks similar

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
