### ISSUE TITLE
Flutter version 0.11.10  Xcode build (iPhone 6) error

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#24879]
Hi,

my app works on android but I am getting error on iOS as showing below.

**EXCEPTION CAUGHT BY WIDGETS LIBRARY Xcode build (iPhone 6) The getter 'languageCode' was called on null.**

**// TODO: FLUTTER main.dart ====================================================**
```
import 'dart:async';
import 'dart:io';

import 'package:cep/language/lang_delegate.dart' as Niyazi;
import 'package:connectivity/connectivity.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';

void main() {
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    return new MaterialApp(

      // TODO: SUPPORTED LOCALE
      supportedLocales: [
        const Locale('tr', 'TR'),
        const Locale('en', 'US'),
        const Locale('ru', 'RU'),
      ],

      localizationsDelegates: [
        const Niyazi.LangDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      localeResolutionCallback:
          (Locale locale, Iterable<Locale> supportedLocales) {
        for (Locale supportedLocale in supportedLocales) {
          if (supportedLocale.languageCode == locale.languageCode ||
              supportedLocale.countryCode == locale.countryCode) {
            return supportedLocale;
          }
        }
        return supportedLocales.first;
      },


      debugShowCheckedModeBanner: false,
      title: ’Niyazi Mobile’,
      theme: new ThemeData(
        primaryColor: Colors.green,
      ),
      home: new MySplash(),
    );
  }
}
```

**// My lang_delegate.dart ========================================================**
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'lang.dart';

class LangDelegate extends LocalizationsDelegate<Lang> {
  const LangDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['tr', 'en', 'ru'].contains(locale.languageCode);

  @override
  Future<Lang> load(Locale locale) async {
    Lang _lang = new Lang(locale);
    await _lang.load();
    print(locale);
    return _lang;
  }

  @override
  bool shouldReload(LangDelegate old) => false;
}

```

**// My lang.dart ==================================================================**
```
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class Lang {
  Lang(this.locale);

  final Locale locale;

  static Lang of(BuildContext context) {
    return Localizations.of<Lang>(context, Lang);
  }

  Map<String, String> _sentences;

  Future<bool> load() async {
    String _data = await rootBundle
        .loadString('packages/cep/language/lang/${this.locale.languageCode}.json'); // My Json files + in pubspec.yaml
    Map<String, dynamic> _result = json.decode(_data);

    this._sentences = new Map();
    _result.forEach((String key, dynamic value) {
      this._sentences[key] = value.toString();
    });

    return true;
  }

  String trans(String key) {
    return this._sentences[key];
  }
}
```

**ERROR ==================================================================**

```
Launching lib/main.dart on iPhone 6 in debug mode...
Starting Xcode build...
Xcode build done.                                           13,9s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building IconTheme(IconThemeData#2abdc(color:
flutter: Color(0xdd000000))):
flutter: The getter 'languageCode' was called on null.
flutter: Receiver: null
flutter: Tried calling: languageCode
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      MyApp.build.<anonymous closure> (package:cep/main.dart:75:54)
flutter: #2      _WidgetsAppState._resolveLocales (package:flutter/src/widgets/app.dart:838:36)
flutter: #3      _WidgetsAppState.initState (package:flutter/src/widgets/app.dart:716:15)
flutter: #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3808:58)
flutter: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
flutter: #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
flutter: #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
flutter: #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #52     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #53     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #54     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #55     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #56     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #58     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #59     main (package:cep/main.dart:50:3)
flutter: #60     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ══════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device iPhone 6...

```

**FLUTTER DOCTOR -V**

```
Niyazi-MBP:cep niyazitoros$ flutter doctor -v
[✓] Flutter (Channel dev, v0.11.10, on Mac OS X 10.14.1 18B75, locale tr-CY)
    • Flutter version 0.11.10 at /users/niyazitoros/flutter
    • Framework revision c27c4a265e (4 days ago), 2018-11-26 17:07:24 -0500
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK at /Users/niyazitoros/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[✓] Connected device (1 available)
    • iPhone 6 • EE36CC70-F1B1-41D4-A2C6-1084BE85DA38 • ios • iOS 12.1 (simulator)

• No issues found!

```

**Comment by NTMS2017** [comment]
ERROR LINE is bold one.

```
 for (Locale supportedLocale in supportedLocales) {
          if (supportedLocale.languageCode == **locale.languageCode** ||
              supportedLocale.countryCode == **locale.countryCode**) {
            return supportedLocale;
          }
        }
```

**Comment by zoechi** [comment]
There was a related change recently where `locale` can be `null` until the device provides it (with some delay).

check if `locale` is `null` and use some default behavior until it becomes `!= null`.

**Comment by NTMS2017** [comment]
How do I do that? 
I also follow https://flutter-news.com/tutorials/flutter-internationalization-by-using-json-files.5 example and I get same error in here.

**Comment by NTMS2017** [comment]
When I try to use this 

```
  if (locale.languageCode == null) {

        } else {
          for (Locale supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == locale.languageCode || supportedLocale.countryCode == locale.countryCode) {
              return supportedLocale;
            }
          }
        }

        return supportedLocales.first;
```

**I got another error as shown below:**

```
Launching lib/main.dart on iPhone 6 in debug mode...
Starting Xcode build...
Xcode build done.                                           12,8s
Finished with error: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.8ijBNF/extracted/Payload/Runner.app
Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.8ijBNF/extracted/Payload/Runner.app
Underlying error (domain=MIInstallerErrorDomain, code=35):
	Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.8ijBNF/extracted/Payload/Runner.app
  Command: /usr/bin/xcrun simctl install EE36CC70-F1B1-41D4-A2C6-1084BE85DA38 /Users/niyazitoros/IdeaProjects/capital_internationalized/build/ios/iphonesimulator/Runner.app

```

**Comment by NTMS2017** [comment]
New Flutter Documents  **https://flutter.io/docs/development/accessibility-and-localization/internationalization#an-alternative-class-for-the-apps-localized-resources** tells us that we should use **SynchronousFuture**. Also provides us a complete source code in here;  **https://github.com/flutter/website/blob/master/src/_includes/code/internationalization/minimal/main.dart**

I follow the reading and look at the example. I also did create an example as shown above link. Still, I am getting same error. Any idea why the documentation and example still has error?

**ERROR:**
Launching lib/main.dart on iPhone 6 in debug mode...
Starting Xcode build...
Xcode build done.                                           12,9s
Finished with error: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.r58nhh/extracted/Payload/Runner.app
Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.r58nhh/extracted/Payload/Runner.app
Underlying error (domain=MIInstallerErrorDomain, code=35):
	Failed to load Info.plist from bundle at path /Users/niyazitoros/Library/Developer/CoreSimulator/Devices/EE36CC70-F1B1-41D4-A2C6-1084BE85DA38/data/Library/Caches/com.apple.mobile.installd.staging/temp.r58nhh/extracted/Payload/Runner.app
  Command: /usr/bin/xcrun simctl install EE36CC70-F1B1-41D4-A2C6-1084BE85DA38 /Users/niyazitoros/IdeaProjects/capital_internationalized/build/ios/iphonesimulator/Runner.app

**Comment by zoechi** [comment]
Can't imagine this `Failed to load Info.plist` being related to `if (locale.languageCode == null) {`
Try `flutter clean`

**Comment by NTMS2017** [comment]
https://flutter.io/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle has an appendix section that talks about Updating the iOS app bundle. I try to follow that as well but I failed to add another language as shown below. It shows the German Language but it doesn't show Turkish or Russian language. Any idea why? Or any work around?

![ekran resmi 2018-11-30 15 54 59](https://user-images.githubusercontent.com/33287468/49293364-9ffb3380-f4b8-11e8-8aee-fe5715bd8de8.png)

**Comment by NTMS2017** [comment]
Follow Flutter doc as I posted above. I use invalidate Caches / Restart and try to build and I got different error and I am guessing I come very close to achieving it, if I get and help. 

**New Error is:** The method '[]' was called on null. Receiver: null Tried calling: []("title")

Here is the my project picture and the code:
![ekran resmi 2018-11-30 16 06 33](https://user-images.githubusercontent.com/33287468/49293926-2cf2bc80-f4ba-11e8-8000-97699ade1a20.png)


**The pub spec.yaml:**
```
name: capital_internationalized
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - packages/capital_internationalized/resources/lang/tr.json
    - packages/capital_internationalized/resources/lang/en.json
```

**The json data TR:**
```
{
  "title": "Merhaba dünya"
}
```

**The json data EN:**
```
{
  "title": "Hello world"
}
```


**The language_localization.dart:**

```
import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// TODO: CLASS - (DemoLocalizations) ##########################################
class DemoLocalizations {
  DemoLocalizations(this.locale);

  final Locale locale;

  static DemoLocalizations of(BuildContext context) {
    return Localizations.of<DemoLocalizations>(context, DemoLocalizations);
  }

  Map<String, String> _sentences;

  Future<bool> load() async {
    String data = await rootBundle.loadString(
        'packages/capital_internationalized/resources/lang/${this.locale
            .languageCode}.json');
    Map<String, dynamic> _result = json.decode(data);

    this._sentences = new Map();
    _result.forEach((String key, dynamic value) {
      this._sentences[key] = value.toString();
    });

    return true;
  }

  String trans(String key) {
    return this._sentences[key];
  }
}

```

**The language_delegate.dart:**

```
import 'package:flutter/material.dart';
import 'language_localization.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;


// TODO: CLASS - (DemoLocalizationsDelegate) ##################################
class DemoLocalizationsDelegate extends LocalizationsDelegate<DemoLocalizations> {
  const DemoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'tr'].contains(locale.languageCode);

  @override
  Future<DemoLocalizations> load(Locale locale) {
    // Returning a SynchronousFuture here because an async "load" operation
    // isn't needed to produce an instance of DemoLocalizations.
    return SynchronousFuture<DemoLocalizations>(DemoLocalizations(locale));
  }

  @override
  bool shouldReload(DemoLocalizationsDelegate old) => false;
}


```

**And the ERROR:**

```
Initializing hot reload...
Syncing files to device iPhone 6...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building Builder(dirty):
flutter: The method '[]' was called on null.
flutter: Receiver: null
flutter: Tried calling: []("title")
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      DemoLocalizations.trans (package:capital_internationalized/language/language_localization.dart:33:27)
flutter: #2      Demo.build.<anonymous closure> (package:capital_internationalized/main.dart:15:80)
flutter: #3      _WidgetsAppState.build.<anonymous closure> (package:flutter/src/widgets/app.dart:1165:39)
flutter: #4      Builder.build (package:flutter/src/widgets/basic.dart:5736:41)
flutter: #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3752:28)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #34     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3759:5)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
flutter: #57     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #65     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #66     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 434 libraries in 3.031ms.


```

**Comment by NTMS2017** [comment]
Above post I show the link from Flutter Doc. Using the minimal example the I get error on iOS 12 iphone 6 using the **SynchronousFuture** method. It seems it never initiated, thats why I am keep getting [] null on error. But I change the code and use Future await and now its working in both ios 12 iphone 6 and android.
