### ISSUE TITLE
video_player in TabBarView throws error

### ISSUE THREAD

**Issue by premy** [flutter/flutter#24877]
Hi there, I'm simply trying to play a video in TabBarView.
For testing I created a dart file and pasted in the example code from https://github.com/flutter/plugins/tree/master/packages/video_player#example. Then I tried calling it from my (stateless) `TabBarView` page like this:

```dart
TabBarView(
    physics: NeverScrollableScrollPhysics(),
   children: [
      AtendimentoTabs("paciente",snapshot),
      AtendimentoTabs("atendimento",snapshot),
      AtendimentoTabs("recomendados",snapshot),
      AtendimentoTabs("fotos",snapshot),
      VideoApp(),
   ])
```

All of the above tabs work fine, but when I switch to VideoApp(), the console shows the following error (app does not crash though):

```
I/flutter ( 5591): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5591): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 5591): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 683 pos 12: 'pixels !=
I/flutter ( 5591): null': is not true.
I/flutter ( 5591): 
I/flutter ( 5591): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5591): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5591): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5591):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5591): 
I/flutter ( 5591): When the exception was thrown, this was the stack:
I/flutter ( 5591): #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart:683:12)
I/flutter ( 5591): #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:255:11)
I/flutter ( 5591): #4      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:343:14)
I/flutter ( 5591): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3900:12)
I/flutter ( 5591): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1709:13)
I/flutter ( 5591): #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter ( 5591): #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #26     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter ( 5591): #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter ( 5591): #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter ( 5591): #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter ( 5591): #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #68     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter ( 5591): #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #74     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter ( 5591): #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #77     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter ( 5591): #78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 5591): #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5591): #87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 5591): #88     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter ( 5591): #89     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1718:25)
I/flutter ( 5591): #90     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2372:27)
I/flutter ( 5591): #91     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2204:15)
I/flutter ( 5591): #92     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2371:7)
I/flutter ( 5591): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:678:18)
I/flutter ( 5591): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 5591): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5591): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5591): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5591): #98     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 5591): #99     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 5591): (elided 2 frames from class _AssertionError)
I/flutter ( 5591): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ExoPlayerImpl( 5591): Release 4ba9ccd [ExoPlayerLib/2.8.0] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5591): Init 3a23801 [ExoPlayerLib/2.8.0] [generic_x86, Android SDK built for x86, Google, 27]
E/ExoPlayerImplInternal( 5591): Source error.
E/ExoPlayerImplInternal( 5591): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
E/ExoPlayerImplInternal( 5591): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5591): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5591): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 5591): Caused by: java.net.SocketTimeoutException: failed to connect to www.sample-videos.com/45.249.110.23 (port 443) from /192.168.232.2 (port 40826) after 8000ms
E/ExoPlayerImplInternal( 5591): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
E/ExoPlayerImplInternal( 5591): 	at libcore.io.IoBridge.connect(IoBridge.java:129)
E/ExoPlayerImplInternal( 5591): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
E/ExoPlayerImplInternal( 5591): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/ExoPlayerImplInternal( 5591): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/ExoPlayerImplInternal( 5591): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/ExoPlayerImplInternal( 5591): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/ExoPlayerImplInternal( 5591): 	at java.net.Socket.connect(Socket.java:621)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
E/ExoPlayerImplInternal( 5591): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:356)
E/ExoPlayerImplInternal( 5591): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
E/ExoPlayerImplInternal( 5591): 	... 5 more
```

**Comment by zoechi** [comment]
Merging with #21630
