### ISSUE TITLE
cloud_firestore Query "where" does not accept DocumentSnapshot

### ISSUE THREAD

**Issue by edwardmelody** [flutter/flutter#24903]
I have collection paid to mapping between user and product. They're reference to its collection.

## Steps to Reproduce

1. I tried to use collection string in where clause ex. product/ya7sfEyWSl5Pa7iINsLp, /product/ya7sfEyWSl5Pa7iINsLp or only ya7sfEyWSl5Pa7iINsLp. It can not found anything.
```dart
Firestore.instance
	.collection('paid')
	.where('product', isEqualTo: 'product/ya7sfEyWSl5Pa7iINsLp')
	.snapshots()
	.listen((paid) {
	print(paid.documents.length); // return 0
	paid.documents.forEach((doc) {
		print(doc.data);
	});
});
```

2. I tried to use DocumentSnapshot in where clause. It isn't worked and throwing an exception.
```dart
var product = await Firestore.instance
	.collection('product')
	.document('ya7sfEyWSl5Pa7iINsLp')
	.get();

Firestore.instance
	.collection('paid')
	.where('product', isEqualTo: product) // exception
	.snapshots()
	.listen((paid) {
	print(paid.documents.length);
	paid.documents.forEach((doc) {
		print(doc.data);
	});
});
```

## Logs

When I use DocumentSnapshot in where clause. Yep. It said "Invalid argument: Instance of 'DocumentSnapshot'".

```
E/flutter ( 9069): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 9069): Invalid argument: Instance of 'DocumentSnapshot'
E/flutter ( 9069): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:353:7)
E/flutter ( 9069): #1      FirestoreMessageCodec.writeValue (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore_message_codec.dart:60:13)
E/flutter ( 9069): #2      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:343:9)
E/flutter ( 9069): #3      FirestoreMessageCodec.writeValue (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore_message_codec.dart:60:13)
E/flutter ( 9069): #4      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:343:9)
E/flutter ( 9069): #5      FirestoreMessageCodec.writeValue (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore_message_codec.dart:60:13)
E/flutter ( 9069): #6      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:350:9)
E/flutter ( 9069): #7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter ( 9069): #8      MapView.forEach (dart:collection/maps.dart:351:10)
E/flutter ( 9069): #9      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:348:13)
E/flutter ( 9069): #10     FirestoreMessageCodec.writeValue (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore_message_codec.dart:60:13)
E/flutter ( 9069): #11     StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:350:9)
E/flutter ( 9069): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter ( 9069): #13     StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:348:13)
E/flutter ( 9069): #14     FirestoreMessageCodec.writeValue (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore_message_codec.dart:60:13)
E/flutter ( 9069): #15     StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:506:18)
E/flutter ( 9069): #16     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:288:13)
E/flutter ( 9069): <asynchronous suspension>
E/flutter ( 9069): #17     Query.snapshots.<anonymous closure> (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/query.dart:56:37)
```

## flutter analyze

```
No issue found.
```

##  flutter doctor -v

```
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 10.0.17134.407], locale th-TH)
    • Flutter version 0.11.13 at C:\flutter
    • Framework revision 58c8489fcd (2 days ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\siang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

```

**Comment by cyanglaz** [comment]
cc @collinjackson

**Comment by edman** [comment]
You need to query with a document _reference_, not a snapshot.

E.g. removing the `.get()` from example 2 above should work:

```dart
var productReference = Firestore.instance
	.collection('product')
	.document('ya7sfEyWSl5Pa7iINsLp');

Firestore.instance
	.collection('paid')
	.where('product', isEqualTo: productReference)
	.snapshots()
	.listen((paid) {
	print(paid.documents.length);
	paid.documents.forEach((doc) {
		print(doc.data);
	});
});
```

**Comment by collinjackson** [comment]
It seems like this is working as intended. Native iOS SDK throws a similar exception when passing a `DocumentSnapshot` as an argument to `where`. As @edman suggested you can use a `DocumentReference` instead.

2019-04-14 07:16:58.892045-0700 Runner[59042:3139566] *** Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'Unsupported type: FIRQueryDocumentSnapshot'
*** First throw call stack:
(

**Comment by kroikie** [comment]
@edwardmelody

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/562. Any further collaboration will be done there.
