### ISSUE TITLE
flutter run test/widget_test.dart + Performing hot restart... Going wrong

### ISSUE THREAD

**Issue by omrllm** [flutter/flutter#24902]
## Steps to Reproduce

1. Just create a flutter project from scratch, the one with "You have pushed the button this many times:".
2. run from your terminal in your app folder `flutter run test/widget_test.dart`
3. Hot Restart by pressing R

## Logs

# flutter analyze

```
Analyzing untitled...                                            
No issues found! (ran in 2.0s)
```

# flutter doctor

```[✓] Flutter (Channel beta, v0.11.13, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /home/omar/android/sdk/platform-tools
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

# What I get in the Terminal Panel

``` Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching test/widget_test.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.0s
Resolving dependencies...                                    2.5s
Gradle task 'assembleDebug'...                                   
Gradle task 'assembleDebug'... Done                          8.1s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  1.8s
E/flutter ( 6680): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 6680): NoSuchMethodError: The method 'test' was called on null.
E/flutter ( 6680): Receiver: null
E/flutter ( 6680): Tried calling: test("Counter increments smoke test", Closure: () => Future<void>, onPlatform: null, retry: null, skip: false, solo: false, tags: null, testOn: null, timeout: Instance of 'Timeout')
E/flutter ( 6680): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 6680): #1      test (package:test_api/test_api.dart:101:13)
E/flutter ( 6680): #2      testWidgets (package:flutter_test/src/widget_tester.dart:66:3)
E/flutter ( 6680): #3      main (file:///home/omar/mprojects/untitled/test/widget_test.dart:14:3)
E/flutter ( 6680): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter ( 6680): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Syncing files to device Android SDK built for x86...         2.5s
```

**Comment by jonahwilliams** [comment]
Hi @omrllm, there is a workaround for this bug, in your test file add:

```
import 'package:flutter_test/flutter_test.dart' hide group;
import 'package:test/test.dart' show group;

void main() {
  group('', () { // Rest of tests });
}
```

For updates please follow https://github.com/flutter/flutter/issues/24650
