### ISSUE TITLE
[RESOLVED] Flutter not working anymore

### ISSUE THREAD

**Issue by ajaybhatia** [flutter/flutter#24921]
Hi Team,

I'm facing an issue while running flutter command with any switch. The error log is given as follow:

```
Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(":")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      getExecutablePath (package:process/src/interface/common.dart:59:60)
#2      _getExecutable (package:process/src/interface/local_process_manager.dart:111:16)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
#5      runSync (package:flutter_tools/src/base/process.dart:300:10)
#6      _runGit (package:flutter_tools/src/version.dart:516:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:16)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:69:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:171:48)
#14     new Usage (package:flutter_tools/src/usage.dart:27:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#21     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#22     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:51:10)
#32     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#33     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
**Platform:** `Arch Linux x64`

Thanks

**Comment by zoechi** [comment]
Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#ways-to-fix

**Comment by ajaybhatia** [comment]
Already tried. Not able to solve the issue.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Please also post the exact command you used to get above error output.

**Comment by kyleDEVV** [comment]
> Please also post the exact command you used to get above error output.

Under breakpoints run with all expectations enabled, send a gist with your problem.

**Comment by ajaybhatia** [comment]
> Please also post the exact command you used to get above error output.

## Steps to Reproduce

1. Unzip flutter .zip.
2. Update path.
3. Run **flutter doctor** and receive error. 

Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(":")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      getExecutablePath (package:process/src/interface/common.dart:59:60)
#2      _getExecutable (package:process/src/interface/local_process_manager.dart:111:16)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
#5      runSync (package:flutter_tools/src/base/process.dart:300:10)
#6      _runGit (package:flutter_tools/src/version.dart:516:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:16)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:69:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:171:48)
#14     new Usage (package:flutter_tools/src/usage.dart:27:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#21     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#22     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:51:10)
#32     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#33     main (file:///opt/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by zoechi** [comment]
Do you have the zip file of the previous working Flutter version still around?
Could you try if starts working again if you extract this file instead?

**Comment by ajaybhatia** [comment]
> Do you have the zip file of the previous working Flutter version still around?
> Could you try if starts working again if you extract this file instead?

No I don't have the previous working version zip.

**Comment by zoechi** [comment]
If you know the version number of the latest working version you should be able to get it by adapting the url https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.11.13-beta.tar.xz accordingly.

**Comment by zoechi** [comment]
Not sure what you mean with "nothing".
If the previous version doesn't work anymore it's unlikely to be a Flutter issue.

**Comment by ajaybhatia** [comment]
> Not sure what you mean with "nothing".
> If the previous version doesn't work anymore it's unlikely to be a Flutter issue.

Few days back everything from working. I even didn't pull from Github but still got the error. I tried with pulling the commits and error persists. I removed the cloned repo and download the zipfrom flutter.io but still getting same error. Fyi I even switched between beta and master branches to make it workable but it didn't help.

**Comment by wouterhardeman** [comment]
What happens when you run the following command in your Flutter folder?

```git rev-parse --abbrev-ref --symbolic @{u}```

This command should return something like **origin/beta**. It seems to crash when that command is executed.

**Comment by ajaybhatia** [comment]
> What happens when you run the following command in your Flutter folder?
> 
> `git rev-parse --abbrev-ref --symbolic @{u}`
> 
> This command should return something like **origin/beta**. It seems to crash when that command is executed.

I've switched to master and the command git rev-parse --abbrev-ref --symbolic @{u} gives me **origin/master**

**Comment by wouterhardeman** [comment]
I've looked in the dart process package and it appears it can't get your PATH from the environment.

This line causes your error: https://github.com/google/process.dart/blob/master/lib/src/interface/common.dart#L59

So it might to be a issue with ArchLinux support in dart:io or a misconfiguration in your environment. But it's not a Flutter issue.

**Comment by ajaybhatia** [comment]
> I've looked in the dart process package and it appears it can't get your PATH from the environment.
> 
> This line causes your error: https://github.com/google/process.dart/blob/master/lib/src/interface/common.dart#L59
> 
> So it might to be a issue with ArchLinux support in dart:io or a misconfiguration in your environment. But it's not a Flutter issue.

I'm not sure about it but I've not installed dart as a seperate package in my Arch system. I'm using flutter sdk from last 6 months and never faced issue like that. I'm developing a project and it's halted for no reason. I can't do anything. The matter needs to be resolved.

**Comment by ajaybhatia** [comment]
Finally resolved the issue. @wouterhardeman you're right. My zshrc was messed with JAVA_HOME path. But I'm still in dilemma whether java has do with flutter SDK or not?

**Comment by zoechi** [comment]
The Android SDK depends on Java and you can't build without it. Flutter doctor probably calls `javac --version` or similar to get the installed Java version.

**Comment by ThinkDigitalRepair** [comment]
I've been getting this for the past week as well. It was only happening when building for Android, but not iOS. 
Oops; flutter has exited unexpectedly.
```
thinkdigital@ThinkDigitalsMBP~/development/flutter $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 5b78567938eb66f7)
Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("=")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:57:85)
#2      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:200:67)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#6      new List.from (dart:core/runtime/libarray_patch.dart:45:19)
#7      Iterable.toList (dart:core/iterable.dart:398:16)
#8      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:202:10)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:157:26)
#10     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:147:41)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#14     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#15     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#16     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:43)
#17     javaPath (package:flutter_tools/src/android/android_studio.dart:32:24)
#18     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:493:24)
#19     AndroidLicenseValidator._checkJavaVersionNoOutput (package:flutter_tools/src/android/android_workflow.dart:207:42)
<asynchronous suspension>
#20     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:182:17)
<asynchronous suspension>
#21     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#24     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#25     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#26     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#27     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#28     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#39     _doctorText (package:flutter_tools/runner.dart:187:19)
#40     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#41     _doctorText (package:flutter_tools/runner.dart:183:27)
#42     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#45     _handleToolError (package:flutter_tools/runner.dart:120:33)
#46     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#52     Future._complete (dart:async/future_impl.dart:473:7)
#53     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#54     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#55     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#56     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#57     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#58     _rootRunUnary (dart:async/zone.dart:1132:38)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#62     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#63     Future._complete (dart:async/future_impl.dart:473:7)
#64     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#65     _rootRun (dart:async/zone.dart:1120:38)
#66     _CustomZone.run (dart:async/zone.dart:1021:19)
#67     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#68     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#69     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#70     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#71     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#72     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#73     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#74     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#75     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#76     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#77     _rootRun (dart:async/zone.dart:1120:38)
#78     _CustomZone.run (dart:async/zone.dart:1021:19)
#79     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#80     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#81     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#82     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#83     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#84     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#85     _rootRun (dart:async/zone.dart:1120:38)
#86     _CustomZone.run (dart:async/zone.dart:1021:19)
#87     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#88     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#89     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#90     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#91     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#92     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#93     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#94     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#95     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#96     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#97     _rootRun (dart:async/zone.dart:1120:38)
#98     _CustomZone.run (dart:async/zone.dart:1021:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#100    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#101    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#102    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#103    _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#104    _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#105    _rootRun (dart:async/zone.dart:1120:38)
#106    _CustomZone.run (dart:async/zone.dart:1021:19)
#107    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#108    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#109    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#110    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#111    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#112    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#113    _StreamController.close (dart:async/stream_controller.dart:622:5)
#114    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#115    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#116    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#117    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#118    _rootRunUnary (dart:async/zone.dart:1132:38)
#119    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#120    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#121    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#122    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#123    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#124    _StreamController._add (dart:async/stream_controller.dart:640:7)
#125    _StreamController.add (dart:async/stream_controller.dart:586:5)
#126    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#127    _rootRunUnary (dart:async/zone.dart:1132:38)
#128    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#129    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#130    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#131    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#132    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#133    _StreamController._add (dart:async/stream_controller.dart:640:7)
#134    _StreamController.add (dart:async/stream_controller.dart:586:5)
#135    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#136    _rootRun (dart:async/zone.dart:1120:38)
#137    _CustomZone.run (dart:async/zone.dart:1021:19)
#138    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#139    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#140    _rootRun (dart:async/zone.dart:1124:13)
#141    _CustomZone.run (dart:async/zone.dart:1021:19)
#142    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#143    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#144    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#145    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#146    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by zoechi** [comment]
@ThinkDigitalRepair it came up a few times recently with AS downloaded from JetBrains Toolbox #27670

**Comment by msobocin** [comment]
resolved with last update of flutter

**Comment by kangwang1988** [comment]
@ThinkDigitalRepair 
Fixed&Landed in https://github.com/flutter/flutter/pull/27687

**Comment by ThinkDigitalRepair** [comment]
I'm using Intellij. I did download AS though, even though I don't use it. So a new update is ready?

**Comment by msobocin** [comment]
@ThinkDigitalRepair  try to upgrade flutter

**Comment by ThinkDigitalRepair** [comment]
@msobocin I currently have Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 24, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
I'm upgrading it again now to 182.5107.16.33.5264788

**Comment by ThinkDigitalRepair** [comment]
Ok, great. It works for me now with Android Studio version 182.5107.16.33.5264788 and Flutter (Channel master, v1.2.1-pre.181, on Mac OS X 10.14.2 18C54,
    locale en-US)
Thanks, guys
