### ISSUE TITLE
Camera plugin occasionally crashes sending permission reply multiple times on Android

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#24949]
## Steps to Reproduce

1. This happened during our live coding session for Flutter Live. We ran on a Pixel 3, and were developing this: https://github.com/efortuna/final_countdown
2. I THINK what might have happened, is we had already accepted the camera permissions, by initing the camera, and then we happened to hot reload at the exact time that it was about to take a picture (and checking that we had accepted permissions to use the camera). 

## Logs

This was the stacktrace of the crash:

```
12-04 02:39:45.112 21395 21395 E AndroidRuntime: Process: com.example.finalcountdown, PID: 21395
12-04 02:39:45.112 21395 21395 E AndroidRuntime: java.lang.IllegalStateException: Reply already submitted
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:203)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at io.flutter.plugins.camera.CameraPlugin$Camera$4.onImageAvailable(CameraPlugin.java:537)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-04 02:39:45.112 21395 21395 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
[✓] Flutter (Channel beta, v0.11.12, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.12 at /Users/efortuna/flutter
    • Framework revision 06ec8d3b41 (5 days ago), 2018-11-28 15:56:58 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/efortuna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • Pixel 3 • 8APX0WR2M • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by amirh** [comment]
Looking at the current code I cannot currently think of a way that the result will be completed twice.
I couldn't make exactly which plugin version you were using, but since the stack trace shows that onImageAvailable included line 537 I think it's pretty old (this wasn't the case for the last few months).

My best guess would be that this happened with a pretty old camera plugin and maybe hit the issue that was fixed by https://github.com/flutter/plugins/pull/384 but can't be sure.

I'm closing this issue, assuming it is not valid anymore. If anyone hits it again please re-open (and please also mention the plugin version you are using).
