### ISSUE TITLE
How is it possible to get the stacktrace of native exceptions?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#24987]
I am just exploring this project: https://github.com/flutter/crashy
Everything works just fine, but i also want to have a way to retrieve the stacktrace of native exceptions? Is there a way? If i am executing this project local i get this in my console: 

```
**E/MethodChannel#crashy-custom-channel(10053): Failed to handle method call**
**E/MethodChannel#crashy-custom-channel(10053): java.lang.IllegalStateException: This is Java exception**
**E/MethodChannel#crashy-custom-channel(10053): 	at com.hapi.hapiapp.MainActivity.onMethodCall(MainActivity.java:24)**
**E/MethodChannel#crashy-custom-channel(10053): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)**
**E/MethodChannel#crashy-custom-channel(10053): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)**
**E/MethodChannel#crashy-custom-channel(10053): 	at android.os.MessageQueue.nativePollOnce(Native Method)**
**E/MethodChannel#crashy-custom-channel(10053): 	at android.os.MessageQueue.next(MessageQueue.java:326)**
**E/MethodChannel#crashy-custom-channel(10053): 	at android.os.Looper.loop(Looper.java:160)**
**E/MethodChannel#crashy-custom-channel(10053): 	at android.app.ActivityThread.main(ActivityThread.java:6669)**
**E/MethodChannel#crashy-custom-channel(10053): 	at java.lang.reflect.Method.invoke(Native Method)**
**E/MethodChannel#crashy-custom-channel(10053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)**
**E/MethodChannel#crashy-custom-channel(10053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)**
I/flutter (10053): Caught error: PlatformException(error, This is Java exception, null)
I/flutter (10053): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
I/flutter (10053): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
I/flutter (10053): <asynchronous suspension>
I/flutter (10053): #2      _MainPageState.build.<anonymous closure>.<anonymous closure> (package:hapi/widgets/pages/main/main_page.dart:218:57)
I/flutter (10053): <asynchronous suspension>
I/flutter (10053): #3      _OptionsButtonWidgetState._subButton.<anonymous closure> (package:hapi/widgets/components/optionsbutton_widget.dart:91:20)
I/flutter (10053): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter (10053): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter (10053): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (10053): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (10053): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (10053): #9      PrimaryPointerGestureRecognizer.handleEvent
```

Nether with **runZoned** or **FlutterError.onError** i can access the stacktrace of the native exception.

**Comment by zoechi** [comment]
Somewhat related to #14765

**Comment by marandaneto** [comment]
We've (Sentry.io) released a Prelease for Flutter Apps.

This package includes support to native crashes through Sentry's native SDKs: (Android and iOS). It will capture errors in the native layer, including (Java/Kotlin/C/C++ for Android and Objective-C/Swift for iOS).

https://pub.dev/packages/sentry_flutter/

try out and let us know if you find any issues :)

**Comment by blasten** [comment]
There's also the stacktrace property. https://api.flutter.dev/flutter/services/PlatformException/stacktrace.html, but the platform side must send the stacktrace. 

For un-captured traces, another option is to register a global exception handler in the platform side, and expose the exception in Dart.
