### ISSUE TITLE
I have problem with upgrade to flutter 1.0

### ISSUE THREAD

**Issue by Sanpong** [flutter/flutter#25019]
```
Upgrading Flutter from C:\flutter...
Updating f37c235c3..5391447fa
error: Your local changes to the following files would be overwritten by merge:
        packages/flutter_tools/gradle/flutter.gradle
Please commit your changes or stash them before you merge.
error: Your local changes to the following files would be overwritten by merge:
        dev/automated_tests/pubspec.yaml
        dev/benchmarks/complex_layout/pubspec.yaml
        dev/benchmarks/microbenchmarks/pubspec.yaml
        dev/bots/pubspec.yaml
        dev/devicelab/pubspec.yaml
        dev/integration_tests/android_semantics_testing/pubspec.yaml
        dev/integration_tests/android_views/pubspec.yaml
        dev/integration_tests/channels/pubspec.yaml
        dev/integration_tests/external_ui/pubspec.yaml
        dev/integration_tests/flavors/pubspec.yaml
        dev/integration_tests/platform_interaction/pubspec.yaml
        dev/integration_tests/ui/pubspec.yaml
        dev/manual_tests/pubspec.yaml
        dev/tools/pubspec.yaml
        dev/tools/vitool/pubspec.yaml
        examples/catalog/pubspec.yaml
        examples/flutter_gallery/pubspec.yaml
        examples/hello_world/pubspec.yaml
        examples/layers/pubspec.yaml
        examples/platform_channel/pubspec.yaml
        examples/platform_channel_swift/pubspec.yaml
        examples/stocks/pubspec.yaml
        packages/flutter/pubspec.yaml
        packages/flutter_driver/pubspec.yaml
        packages/flutter_goldens/pubspec.yaml
        packages/flutter_goldens_client/pubspec.yaml
        packages/flutter_localizations/pubspec.yaml
        packages/flutter_test/pubspec.yaml
        packages/flutter_tools/pubspec.yaml
        packages/fuchsia_remote_debug_protocol/pubspec.yaml
Please commit your changes or stash them before you merge.
Aborting

C:\Users\sanpo>flutter upgrade -v
[  +71 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +169 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/beta
[        ] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92
[   +1 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[  +79 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 months ago
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +84 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.9.4-0-gf37c235c3
[ +159 ms] executing: [C:\flutter\] git rev-parse @{u}
[ +125 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +2 ms] Upgrading Flutter from C:\flutter...
[   +7 ms] executing: [C:\flutter\] git pull --ff-only
[+3374 ms] Updating f37c235c3..5391447fa
[   +5 ms] error: Your local changes to the following files would be overwritten by merge:
[   +7 ms]      packages/flutter_tools/gradle/flutter.gradle
[   +1 ms] Please commit your changes or stash them before you merge.
[   +1 ms] error: Your local changes to the following files would be overwritten by merge:
[   +1 ms]      dev/automated_tests/pubspec.yaml
[   +1 ms]      dev/benchmarks/complex_layout/pubspec.yaml
[   +1 ms]      dev/benchmarks/microbenchmarks/pubspec.yaml
[   +1 ms]      dev/bots/pubspec.yaml
[   +1 ms]      dev/devicelab/pubspec.yaml
[   +1 ms]      dev/integration_tests/android_semantics_testing/pubspec.yaml
[   +1 ms]      dev/integration_tests/android_views/pubspec.yaml
[   +4 ms]      dev/integration_tests/channels/pubspec.yaml
[   +1 ms]      dev/integration_tests/external_ui/pubspec.yaml
[   +1 ms]      dev/integration_tests/flavors/pubspec.yaml
[   +1 ms]      dev/integration_tests/platform_interaction/pubspec.yaml
[   +1 ms]      dev/integration_tests/ui/pubspec.yaml
[   +1 ms]      dev/manual_tests/pubspec.yaml
[   +1 ms]      dev/tools/pubspec.yaml
[   +1 ms]      dev/tools/vitool/pubspec.yaml
[   +2 ms]      examples/catalog/pubspec.yaml
[   +3 ms]      examples/flutter_gallery/pubspec.yaml
[   +1 ms]      examples/hello_world/pubspec.yaml
[   +1 ms]      examples/layers/pubspec.yaml
[   +1 ms]      examples/platform_channel/pubspec.yaml
[   +1 ms]      examples/platform_channel_swift/pubspec.yaml
[   +2 ms]      examples/stocks/pubspec.yaml
[   +1 ms]      packages/flutter/pubspec.yaml
[   +1 ms]      packages/flutter_driver/pubspec.yaml
[   +4 ms]      packages/flutter_goldens/pubspec.yaml
[   +1 ms]      packages/flutter_goldens_client/pubspec.yaml
[   +4 ms]      packages/flutter_localizations/pubspec.yaml
[   +1 ms]      packages/flutter_test/pubspec.yaml
[   +2 ms]      packages/flutter_tools/pubspec.yaml
[   +2 ms]      packages/fuchsia_remote_debug_protocol/pubspec.yaml
[   +1 ms] Please commit your changes or stash them before you merge.
[   +1 ms] Aborting
[  +41 ms] "flutter upgrade" took 3,715ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:53:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by xia-weiyang** [comment]
Please commit your changes or stash them before you merge.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted should help get around that.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Sanpong** [comment]
Thank you for all. I can upgrade flutter 1.0

**Comment by larryq** [comment]
Just FYI, I had this same problem and the link above from @zoechi fixed it perfectly.  No idea why git thought I had changed those files, I'm guessing my `flutter upgrade `command bombed out along the way...
