### ISSUE TITLE
debugDumpState() : EXCEPTION CAUGHT BY GESTURE LIBRARY

### ISSUE THREAD

**Issue by turnidge** [flutter/flutter#2503]
_Detailed issue description here. More information at [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/)_

### Steps to Reproduce

1. Create a new flutter project in Atom using Packages > Flutter > Create new Flutter project...
2. Edit the _incrementCounter method to call debugDumpApp():

```
  void _incrementCounter() {
    setState(() {
      _counter++;
      debugDumpApp();
    });
  }
```

Run the program and click on the button.  I got the exception:

```
WidgetFlutterBinding - CHECKED MODE
-- EXCEPTION CAUGHT BY GESTURE LIBRARY ---------------------------------
The following exception was raised while routing a pointer event:
type 'MappedIterable<GestureRecognizer, dynamic>' is not a subtype of type 'List<String>' of 'gestures'.
Event:
PointerUpEvent(Point(369.7, 688.7))
Stack trace:
#0      RawGestureDetectorState.debugFillDescription (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/gesture_detector.dart:343)
#1      State.toString (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:391)
#2      _StringBase._interpolate (dart:core-patch/string_patch.dart:822)
#3      StatefulComponentElement.debugFillDescription (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1331)
#4      Element.toString (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:984)
#5      _StringBase._interpolate (dart:core-patch/string_patch.dart:833)
#6      Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1002)
#7      Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#8      Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#9      Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#10     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#11     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#12     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1008)
#13     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#14     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#15     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#16     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#17     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#18     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#19     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#20     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#21     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#22     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#23     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#24     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#25     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#26     Element.toStringDeep (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:1009)
#27     debugDumpApp (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/binding.dart:176)
#28     _FlutterDemoState._incrementCounter.<anonymous closure> (/Users/turnidge/hackathon/emptyproject/lib/main.dart:24)
#29     State.setState (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/widgets/framework.dart:352)
#30     _FlutterDemoState._incrementCounter (/Users/turnidge/hackathon/emptyproject/lib/main.dart:22)
#31     _InkResponseState._handleTap (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/material/ink_well.dart:101)
#32     TapGestureRecognizer._checkUp (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/tap.dart:83)
#33     TapGestureRecognizer.handlePrimaryPointer (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/tap.dart:33)
#34     PrimaryPointerGestureRecognizer.handleEvent (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/recognizer.dart:138)
#35     PointerRouter.route (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/pointer_router.dart:65)
#36     BindingBase&Scheduler&Gesturer.handleEvent (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/binding.dart:117)
#37     BindingBase&Scheduler&Gesturer.dispatchEvent (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/binding.dart:96)
#38     BindingBase&Scheduler&Gesturer._handlePointerEvent (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/binding.dart:71)
#39     BindingBase&Scheduler&Gesturer._handlePointerPacket (/Users/turnidge/hackathon/emptyproject/packages/flutter/src/gestures/binding.dart:43)
#40     _dispatchPointerPacket (file:///private/tmp/flutter_build_workspace/src/out/ios_sim_Release/gen/sky/bindings/hooks.dart:43)
------------------------------------------------------------------------
```

### Flutter Version

Flutter from https://github.com/flutter/flutter.git (on hackathon)
flutter revision: 758de5ed10ab4d7035ec03ca7bcc9f613ceecd6f (8 days ago)
engine revision : 006a702b30182b7622f54c30f538f70df4398614

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.

**Comment by turnidge** [comment]
@Hixie

**Comment by Hixie** [comment]
The hackathon branch is ancient. Move to master, where this is already fixed. :-)

**Comment by sethladd** [comment]
Will file a request to bump hackathon branch.

**Comment by abarth** [comment]
Hackathon branch updated.
