### ISSUE TITLE
Failed assertion when Scaffold is disposed with open drawer

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#25047]
Here's a simple repro (press the button in the drawer).

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _displayScaffold = true;

  @override
  Widget build(BuildContext context) {
    if (!_displayScaffold) return Container();
    return MyScaffold(
      onDrawerButtonPressed: () {
        setState(() {
          _displayScaffold = false;
        });
      },
    );
  }
}

class MyScaffold extends StatelessWidget {
  final VoidCallback onDrawerButtonPressed;

  const MyScaffold({Key key, this.onDrawerButtonPressed}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      drawer: Drawer(
        child: RaisedButton(
          onPressed: onDrawerButtonPressed,
          child: Text('PRESS ME'),
        ),
      ),
    );
  }
}
```

```
I/flutter (24703): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24703): The following assertion was thrown while finalizing the widget tree:
I/flutter (24703): setState() or markNeedsBuild() called when widget tree was locked.
I/flutter (24703): This _ModalScope<dynamic> widget cannot be marked as needing to build because the framework is
I/flutter (24703): locked.
I/flutter (24703): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (24703):   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#994b6](state:
I/flutter (24703):   _ModalScopeState<dynamic>#e7d70)
I/flutter (24703): 
I/flutter (24703): When the exception was thrown, this was the stack:
I/flutter (24703): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3502:9)
I/flutter (24703): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
I/flutter (24703): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
I/flutter (24703): #3      _ModalScopeState._routeSetState (package:flutter/src/widgets/routes.dart:584:5)
I/flutter (24703): #4      ModalRoute.setState (package:flutter/src/widgets/routes.dart:683:30)
I/flutter (24703): #5      ModalRoute.changedInternalState (package:flutter/src/widgets/routes.dart:1154:5)
I/flutter (24703): #6      _ModalRoute&TransitionRoute&LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:468:7)
I/flutter (24703): #7      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:299:12)
I/flutter (24703): #8      DrawerControllerState.dispose (package:flutter/src/material/drawer.dart:211:20)
I/flutter (24703): #9      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3878:12)
I/flutter (24703): #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1709:13)
I/flutter (24703): #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #18     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4926:16)
I/flutter (24703): #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
I/flutter (24703): #31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4826:14)
I/flutter (24703): #37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #43     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #44     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #46     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #47     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #49     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #50     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #52     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #53     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter (24703): #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3733:14)
I/flutter (24703): #55     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter (24703): #56     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (24703): #57     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1718:25)
I/flutter (24703): #58     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2372:27)
I/flutter (24703): #59     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2204:15)
I/flutter (24703): #60     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2371:7)
I/flutter (24703): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:678:18)
I/flutter (24703): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (24703): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (24703): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (24703): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (24703): #66     _invoke (dart:ui/hooks.dart:151:13)
I/flutter (24703): #67     _drawFrame (dart:ui/hooks.dart:140:3)
I/flutter (24703): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24703): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3473 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
I/chatty  (24703): uid=10149(com.example.testing) 1.ui identical 13 lines
I/flutter (24703): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3473 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
```

**Comment by HansMuller** [comment]
The crash occurs because DrawerControllerState.dispose() removes its local history entry in BuildOwner.finalizeTree(), where we dispose of the inactive elements.
```
  class DrawerControllerState extends State<DrawerController> with SingleTickerProviderStateMixin {
    @override
    void dispose() {
      _historyEntry?.remove(); // !!
      _controller.dispose();
      super.dispose();
    }
  }
```
This causes the enclosing ModalRoute to call setState() (on its ModalScope) which trips an assert about calling setState() from within build.

It's possible to avoid the problem by doing the _historyEntry work in a new frame:
```
  void dispose() {
    SchedulerBinding.instance.scheduleFrameCallback((Duration timestamp) {
      _closed = true; // so that DrawerState.close() will do nothing
      _historyEntry?.remove();
    });
```
The version of the code above passes the tests and appears to work correctly. It's a hack of course, but it's not clear what the "correct" approach would be.

It seems like we shouldn't ever do anything in State.dispose() that might trigger a build and we should warn about that in the State.dispose() docs. In this case, we can't know that the local history entry needs to be removed until we discover as much in the dispose() method. The request for a build is needed because visuals, notably the appbar's back button, depend on the history entries.

Talking with @Hixie  about this.

**Comment by HansMuller** [comment]
After looking into this further, we've sadly concluded that removing the scaffold while the drawer is open is not supported. The app will have to close the drawer, with `Navigator.pop()`, before rebuilding the app without the scaffold. Here's a version of the test app that does that: https://gist.github.com/HansMuller/8ff39856dd5ee1f13bd4e93a907cf200

Detecting this failure mode is difficult for the same reason that automatically correcting it is: by the time we learn that the Scaffold is being removed (by the time its `dispose()` method is called) it's too late.

**Comment by alanrussian** [comment]
Mulligan does this in production today. Do you know if there will be any
release mode side effects? Of the top of my head I think we've seen random
crashes related to this although maybe I'm mistaken.

It would be a large effort for us to refactor this. I can explain why if
you're curious (or link you to an internal design doc). The refactoring is
something we'd like to do for other reasons but we probably won't be able
to get to it anytime soon.

**Comment by HansMuller** [comment]
Closing the drawer before rebuilding without the scaffold shouldn't have any side effects. It queues up the same rebuild request, but that happens in the same frame as everything else.

**Comment by MichaelPriebe** [comment]
As in the above referenced issue, I am getting this error without even disposing the drawer at all. It happens for me when I push while the drawer is opened.

**Comment by HansMuller** [comment]
@MichaelPriebe - you're right, it's enough to rebuild a scaffold that had a drawer without one. To avoid the problem with implicitly disposing the drawer, pop the route first. See https://github.com/flutter/flutter/issues/25601#issuecomment-451018092

**Comment by larssn** [comment]
@HansMuller How would you close the drawer when in response to rotation event?

Is a chicken and egg scenario: In order to determine if the drawer is open, we need to listen to a LayoutBuilder or OrientationBuilder, and by then, the Scaffold has already been rebuilt, and thus the crash.

It's a pretty common scenario to support a drawer on phone screens, but not on tablets, since they have more room.

Would you consider reopening? Maybe it could be fixed in the future.

**Comment by Xgamefactory** [comment]
same problem here. there should be a proper fix.

**Comment by leaxoy** [comment]
Same here, leave current scaffold with opened drawer and goto another scaffold cause crash.
