### ISSUE TITLE
When I executed the flutter doctor command, I always made a mistake (I am Chinese, using Google temporary mirror)

### ISSUE THREAD

**Issue by ForyouLight** [flutter/flutter#25056]
## Steps to Reproduce

1. flutter doctor
2. ...
3. ...

## Logs

```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Doctor summary (to see all details, run flutter doctor -v):
```

```
Crash report written to C:\Users\Steven\flutter_08.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by zoechi** [comment]
Please try the commands listed in https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#ways-to-fix to fix your Flutter installation.

**Comment by ForyouLight** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: your current branch 'master' does not have any commits yet


```
#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:438:45)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: your current branch 'master' does not have any commits yet


#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:438:45)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#27     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by ForyouLight** [comment]
The above is log

**Comment by zoechi** [comment]
Please post the output of ` git --version`
You need Git 2.x installed and in `PATH`

**Comment by ForyouLight** [comment]
I re-cloned the project from GitHub and solved...
