### ISSUE TITLE
Transaction.get throws exception if the document doesnt exist

### ISSUE THREAD

**Issue by iamjavademon** [flutter/flutter#25083]
Why does this issue keep coming and going?
```
VERBOSE-2:shell.cc(182)] Dart Error: Unhandled exception:
PlatformException(9, Transaction failed all retries., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      Firestore.runTransaction (file:///Users/olaide.ekeolere/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/firestore.dart:114:10)
<asynchronous suspension>
```

**Comment by cyanglaz** [comment]
@iamjavademon Does the issue still persist for you? Seems like we fixed a lot of related issues.

**Comment by collinjackson** [comment]
Filed #30577 to write a test for transactions.

**Comment by kroikie** [comment]
@iamjavademon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/552. Any further collaboration will be done there.
