### ISSUE TITLE
Unhandled exception running flutter from hidden folder

### ISSUE THREAD

**Issue by RLittlesII** [flutter/flutter#25089]
## Steps to Reproduce

1. Follow [Get the Flutter SDK](https://flutter.io/docs/get-started/install/macos#get-the-flutter-sdk)
2. Copy Flutter to ~/.flutter
3. Add Flutter to $PATH
4. Run `flutter doctor -v`

## Logs

```
Unhandled exception:
FileSystemException: Cannot create file, path = '/Users/<username>/.flutter' (OS Error: Is a directory, errno = 21)
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.createSync (dart:io/file_impl.dart:285:5)
#2      new IOPersistentProperties (package:usage/src/usage_impl_io.dart:119:13)
#3      new AnalyticsIO (package:usage/src/usage_impl_io.dart:30:17)
#4      new Usage (package:flutter_tools/src/usage.dart:29:18)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#11     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#12     _handleToolError (package:flutter_tools/runner.dart:107:7)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#21     run (package:flutter_tools/runner.dart:51:10)
#22     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#23     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#24     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
```

**Comment by zoechi** [comment]
I think this is not because it's a hidden folder, but because it's the `~/.flutter` folder which Flutter tries to create.

**Comment by simonsolberg** [comment]
I hit the same issue. 

> I think this is not because it's a hidden folder, but because it's the `~/.flutter` folder which Flutter tries to create.

Renamed the folder to ~/.flutterio and that fixed it. Thanks. Maybe at least a warning in https://flutter.io/docs/get-started/install/linux about not using $HOME/.flutter for your SDK? :)

**Comment by RLittlesII** [comment]
I would want flutter to realize the folder exists and handle it correctly.  I get that the current install process doesn't force the convention.

Short term editing the docs would most likely keep people from running into the issue.  And I renamed mine to `~/flutter` to get over the issue.  But all my other global tools exist in `~/.<toolname>` so it would be nice to keep that convention.
