### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by arnold-parge** [flutter/flutter#25113]
Flutter crash report

## command
```
flutter run --verbose
```
## exception
```
ProcessException: ProcessException: Process "/home/arnold/Android/Sdk/platform-tools/adb" exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.mappoc/com.apptreesoftware.mapview.MapActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.mappoc/com.apptreesoftware.mapview.MapActivity (has extras) } from null (pid=18259, uid=2000) not exported from uid 10231

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.mappoc/com.apptreesoftware.mapview.MapActivity (has extras) } from null (pid=18259, uid=2000) not exported from uid 10231
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1693)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:462)
	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:278)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:908)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4775)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15547)
	at android.os.Binder.shellCommand(Binder.java:597)
	at android.os.Binder.onTransact(Binder.java:495)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4336)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3075)
	at android.os.Binder.execTransact(Binder.java:702)
  Command: /home/arnold/Android/Sdk/platform-tools/adb -s 254b9b657d26 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.mappoc/com.apptreesoftware.mapview.MapActivity


#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:441:34)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._complete (dart:async/future_impl.dart:476:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.0.0 at /home/arnold/installed/flutter
    [32m•[39m Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK 27.0.3)
    [32m•[39m Android SDK at /home/arnold/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-27, build-tools 27.0.3
    [32m•[39m Java binary at: /home/arnold/installed/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    [31m✗[39m Android license status unknown.

[32m[✓][39m Android Studio (version 3.0)
    [32m•[39m Android Studio at /home/arnold/installed/android-studio
    [32m•[39m Flutter plugin version 23.2.1
    [32m•[39m Dart plugin version 171.4424
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Redmi 6A • 254b9b657d26 • android-arm • Android 8.1.0 (API 27)

[33m![39m Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
There error looks similar to #23757

**Comment by zoechi** [comment]
Can you reproduce with a new app created with `flutter create foo`?
What additional steps are required to reproduce?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by alex9153** [comment]
Hi. Did you fix it ?

**Comment by DEVANANDJALLA** [comment]
hey i Still have this issue.
