### ISSUE TITLE
Successive calls to `precacheImage()` throw an exception

### ISSUE THREAD

**Issue by westy92** [flutter/flutter#25143]
## Steps to Reproduce

1. Call `precacheImage(const NetworkImage('https://via.placeholder.com/350x150'), context);`
2. Wait a few seconds, allowing for the image to cache.
3. Call the same line of code.

I found this easiest to reproduce by placing the line of code in a `IconButton`'s `onPressed` handler. Pressing the button the first time works fine, but pressing it a second time consistently produces the following error.

For added context, `package:Checkiday/main.dart:270:15` in the below logs is the line of code above.

## Logs

```
[+7803 ms] I/flutter ( 9077): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +8 ms] I/flutter ( 9077): The following StateError was thrown by an image error listener:
[        ] I/flutter ( 9077): Bad state: Future already completed
[  +10 ms] I/flutter ( 9077): 
[        ] I/flutter ( 9077): When the exception was thrown, this was the stack:
[  +10 ms] I/flutter ( 9077): #1      precacheImage.errorListener (package:flutter/src/widgets/image.dart:88:15)
[        ] I/flutter ( 9077): #2      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:327:24)
[        ] I/flutter ( 9077): #3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:284:9)
[        ] I/flutter ( 9077): #4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:519:5)
[        ] I/flutter ( 9077): #5      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:512:7)
[        ] I/flutter ( 9077): <asynchronous suspension>
[        ] I/flutter ( 9077): #6      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:528:7)
[        ] I/flutter ( 9077): #7      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:156:25)
[        ] I/flutter ( 9077): #8      precacheImage (package:flutter/src/widgets/image.dart:101:10)
[        ] I/flutter ( 9077): #9      _HomePageState.build.<anonymous closure> (package:Checkiday/main.dart:270:15)
[        ] I/flutter ( 9077): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
[        ] I/flutter ( 9077): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
[        ] I/flutter ( 9077): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[        ] I/flutter ( 9077): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
[        ] I/flutter ( 9077): #14     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
[        ] I/flutter ( 9077): #15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] I/flutter ( 9077): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
[        ] I/flutter ( 9077): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
[        ] I/flutter ( 9077): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
[        ] I/flutter ( 9077): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
[        ] I/flutter ( 9077): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
[        ] I/flutter ( 9077): #21     _invoke1 (dart:ui/hooks.dart:168:13)
[        ] I/flutter ( 9077): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
[        ] I/flutter ( 9077): (elided one frame from package dart:async)
[        ] I/flutter ( 9077): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/westy92/Source/flutter
    • Framework revision 5391447fae (10 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/westy92/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/westy92/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/westy92/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Pixel • FA69H0305733 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by westy92** [comment]
@zoechi attached is a minimal `lib/main.dart` as requested.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          precacheImage(const NetworkImage('https://via.placeholder.com/350x150'), context);
        },
        child: Icon(Icons.image),
      ),
    );
  }
}
```

Reproduction steps are still about the same.
1. Tap the FAB.
2. Wait a few seconds for the image to cache.
3. Tap the FAB.

Stacktrace with this minimal example:
```
I/flutter (24987): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (24987): The following StateError was thrown by an image error listener:
I/flutter (24987): Bad state: Future already completed
I/flutter (24987): 
I/flutter (24987): When the exception was thrown, this was the stack:
I/flutter (24987): #1      precacheImage.errorListener (package:flutter/src/widgets/image.dart:88:15)
I/flutter (24987): #2      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:327:24)
I/flutter (24987): #3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:284:9)
I/flutter (24987): #4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:519:5)
I/flutter (24987): #5      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:512:7)
I/flutter (24987): <asynchronous suspension>
I/flutter (24987): #6      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:528:7)
I/flutter (24987): #7      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:156:25)
I/flutter (24987): #8      precacheImage (package:flutter/src/widgets/image.dart:101:10)
I/flutter (24987): #9      _MyHomePageState.build.<anonymous closure> (package:flutter_local_test/main.dart:29:11)
I/flutter (24987): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter (24987): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter (24987): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (24987): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (24987): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (24987): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (24987): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (24987): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (24987): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (24987): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (24987): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (24987): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (24987): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (24987): #23     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (24987): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter (24987): (elided one frame from package dart:async)
I/flutter (24987): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by truongsinh** [comment]
`package:flutter/src/widgets/image.dart:101`
```
  stream.addListener(listener, onError: errorListener);
  completer.future.then<void>((void value) { stream.removeListener(listener); });
```

when we remove `listener`, we should remove `errorListener` as well. I'm making test case for this

**Comment by truongsinh** [comment]
I tracked down and fix the problem from @westy92 's example, but haven't figured out the unit test for it #25159

**Comment by truongsinh** [comment]
possibly related

packages/flutter/lib/src/painting/image_stream.dart:224
```dart
  /// If the [ImageStreamCompleter] completes multiple images over its lifetime,
  /// this listener will fire multiple times.
```

**Comment by truongsinh** [comment]
unit test added for #25159
