### ISSUE TITLE
google_maps_flutter crash NullPointerException on Android

### ISSUE THREAD

**Issue by melvinm99** [flutter/flutter#25169]
Hi, I'm using the official google_maps_flutter plugin on a physical Android device (Oneplus 6t) and since last Flutter upgrade I'm getting black screen when calling GoogleMap widget. I'm currently on the master branch. Any help would be really appreciated, thank you.

## Plugin version
  google_maps_flutter: ^0.0.3+3

## Code to Reproduce

```dart
 _buildScaffold(LatLng position){
    Scaffold s = new Scaffold(
      key: _scaffoldKey,
      appBar: buildAppBar(context),
      resizeToAvoidBottomPadding: false,
    
      body:
      new Padding(
          padding: new EdgeInsets.all(8.0),
          child: widget.viewSwitchManager.mapView
              ? new Column(
            children: [
              new Flexible(
                  child: new Stack(
                      children: <Widget>[
                    google_maps.GoogleMap(
                      onMapCreated: _onMapCreated,

                      options: google_maps.GoogleMapOptions(
                        mapType: google_maps.MapType.normal,
                        myLocationEnabled: true,
                        cameraPosition: google_maps.CameraPosition(
                          target: google_maps.LatLng(position.latitude, position.longitude),
                          zoom: 11.0,
                        ),

                      ),
                    ),

                   
                    _showFloatingMapListButton(),
                    _showFloatingFiltersButton(),

                  ]))
            ],
          )
              :
          Stack(
              children: <Widget>[
                events != null ?
                new Swiper(
                  loop: false,
                  itemBuilder: (BuildContext context, int index) {
                    EventTheTableLight event = events[index];
                    return EventSwiperCard(event: event);
                  },
                  itemCount: events.length,
                  viewportFraction: 0.8,
                  scale: 0.9,
                ) : SizedBox(),
                _showFloatingMapListButton(),
                _showFloatingFiltersButton(),
              ])


      ),

      /*bottomNavigationBar: BottomAppBar(
        child: new Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            IconButton(
                icon: Icon(Icons.filter_list),
                onPressed: () {
                  _filtersBottomSheet();
            }),
            SizedBox(width: MediaQuery.of(context).size.width/1.8,),
            IconButton(
                icon: Icon(Icons.refresh),
                onPressed: () {
              refreshEvents();
            }),

          ],
        ),
      ),*/
    );
    if(widget.viewSwitchManager.mapView && gMapController != null) {
      _buildMarkers(position);
      gMapController.onMarkerTapped.add(_onMarkerTapped);
    }
    //if (!_searched)
      //_updateMapCenter(position, 13.0);
    return s;
  }
```

## Logs 
```
E/MethodChannel#flutter/platform_views(13580): Failed to handle method call
E/MethodChannel#flutter/platform_views(13580): java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
E/MethodChannel#flutter/platform_views(13580): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:141)
E/MethodChannel#flutter/platform_views(13580): 	at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:118)
E/MethodChannel#flutter/platform_views(13580): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#flutter/platform_views(13580): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter/platform_views(13580): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(13580): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(13580): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter/platform_views(13580): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#flutter/platform_views(13580): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(13580): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#flutter/platform_views(13580): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (13580): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (13580): PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null)
E/flutter (13580): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (13580): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (13580): <asynchronous suspension>
E/flutter (13580): #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:131:41)
E/flutter (13580): <asynchronous suspension>
E/flutter (13580): #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:447:71)
E/flutter (13580): <asynchronous suspension>
E/flutter (13580): #4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:397:5)
E/flutter (13580): #5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:407:5)
E/flutter (13580): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
E/flutter (13580): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (13580): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (13580): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (13580): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (13580): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (13580): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (13580): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (13580): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (13580): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (13580): #16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
E/flutter (13580): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (13580): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (13580): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (13580): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (13580): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (13580): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (13580): #23     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
E/flutter (13580): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (13580): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
E/flutter (13580): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (13580): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (13580): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (13580): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (13580): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (13580): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (13580): #32     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
E/flutter (13580): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (13580): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (13580): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (13580): #36     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
E/flutter (13580): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (13580): #38     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
E/flutter (13580): #39     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
E/flutter (13580): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (13580): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (13580): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (13580): #43     Stateful
```

## Flutter Analyze (nothing remarkable I think..)
``` 
info • The value of the local variable 'code' isn't used • lib/businesslogic/EventsHandler.dart:45:11 • unused_local_variable
   info • The value of the local variable 'code' isn't used • lib/businesslogic/EventsHandler.dart:202:11 • unused_local_variable
   info • The value of the local variable 'code' isn't used • lib/businesslogic/EventsHandler.dart:216:11 • unused_local_variable
   info • The value of the local variable 'userUuid' isn't used • lib/businesslogic/NotificationHandler.dart:58:18 • unused_local_variable
   info • Await only futures • lib/businesslogic/NotificationHandler.dart:161:19 • await_only_futures
   info • Don't explicitly initialize variables to null • lib/businesslogic/NotificationHandler.dart:162:12 • avoid_init_to_null
   info • The value of the local variable 'code' isn't used • lib/businesslogic/RestaurantsHandler.dart:100:11 • unused_local_variable
   info • The value of the local variable 'current' isn't used • lib/businesslogic/SignInHandler.dart:195:55 • unused_local_variable
   info • The value of the local variable 'profile' isn't used • lib/businesslogic/SignInHandler.dart:362:9 • unused_local_variable
   info • The value of the local variable 'code' isn't used • lib/businesslogic/UserHandler.dart:59:9 • unused_local_variable
   info • The value of the local variable 'code' isn't used • lib/businesslogic/UserHandler.dart:66:11 • unused_local_variable
   info • The value of the local variable 'code' isn't used • lib/businesslogic/UserHandler.dart:96:9 • unused_local_variable
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/businesslogic/ViewSwitchManager.dart:9:7 • unnecessary_getters_setters
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/businesslogic/ViewSwitchManager.dart:10:12 • unnecessary_getters_setters
warning • The parameter 'onPressed' is required • lib/ui/SplashScreen.dart:138:29 • missing_required_param
warning • The parameter 'onPressed' is required • lib/ui/SplashScreen.dart:140:29 • missing_required_param
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/host/NavigationScaffoldHost.dart:13:7 • must_be_immutable
   info • The value of the field '_children' isn't used • lib/ui/host/NavigationScaffoldHost.dart:28:22 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/host/NavigationScaffoldHost.dart:30:7 • non_constant_identifier_names
   info • The value of the local variable 'width' isn't used • lib/ui/host/NavigationScaffoldHost.dart:102:12 • unused_local_variable
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/host/events/event_creation/EventCreationFilterPage.dart:20:7 • must_be_immutable
   info • The value of the field '_dateKey' isn't used • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:38:30 • unused_field
   info • The value of the field '_timeKey' isn't used • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:39:30 • unused_field
   info • The value of the field '_tagsKey' isn't used • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:40:30 • unused_field
   info • The value of the field '_spotKey' isn't used • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:41:30 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:55:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:58:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/host/events/event_creation/EventCreationFilterPage.dart:69:7 • non_constant_identifier_names
   info • Don't import implementation files from another package • lib/ui/host/events/event_creation/RestaurantSearchBar.dart:5:8 • implementation_imports
   info • The method '_buildGuestsList' isn't used • lib/ui/host/events/event_info/EventGuestsListPage.dart:325:19 • unused_element
   info • Avoid using braces in interpolation when not needed • lib/ui/host/events/event_info/EventGuestsListPage.dart:332:18 • unnecessary_brace_in_string_interps
   info • The value of the local variable 'width' isn't used • lib/ui/host/events/event_info/EventInfoPageHost.dart:47:12 • unused_local_variable
   info • The method '_buildDialog' isn't used • lib/ui/host/events/event_info/EventInfoPageHost.dart:327:10 • unused_element
   info • The value of the field '_children' isn't used • lib/ui/host/events/event_info/EventPageHost.dart:21:22 • unused_field
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/ui/host/events/event_info/EventPageHost.dart:157:3 • missing_return
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/host/events/event_info/UserSwipeCard.dart:8:7 • must_be_immutable
   info • The operator x ~/ y is more efficient than (x / y).toInt() • lib/ui/host/events/event_info/UserSwipeCard.dart:97:51 • division_optimization
   info • Don't import implementation files from another package • lib/ui/host/events/my_events/EventSearchBar.dart:5:8 • implementation_imports
   info • The method '_buildEventsList' isn't used • lib/ui/host/events/my_events/EventSearchBar.dart:266:10 • unused_element
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/host/events/my_events/MyCreatedEventsPage.dart:35:8 • must_call_super
   info • Await only futures • lib/ui/host/events/my_events/MyCreatedEventsPage.dart:114:5 • await_only_futures
   info • Await only futures • lib/ui/host/events/my_events/MyCreatedEventsPage.dart:118:5 • await_only_futures
   info • The value of the field '_currentIndex' isn't used • lib/ui/host/events/my_events/MyEventsPage.dart:19:7 • unused_field
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/host/events/my_events/MyWaitingEventsPage.dart:34:8 • must_call_super
   info • Await only futures • lib/ui/host/events/my_events/MyWaitingEventsPage.dart:115:5 • await_only_futures
   info • The value of the local variable 'numParticipants' isn't used • lib/ui/host/events/my_events/MyWaitingEventsPage.dart:140:9 • unused_local_variable
   info • The method '_openRequestsListPage' isn't used • lib/ui/host/events/my_events/MyWaitingEventsPage.dart:327:8 • unused_element
   info • The value of the local variable 'height' isn't used • lib/ui/host/payment/PaymentPage.dart:83:12 • unused_local_variable
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/host/payment/PaypalPage.dart:6:9 • non_constant_identifier_names
   info • The name utf8 is shown, but not used • lib/ui/host/payment/StripePage.dart:2:28 • unused_shown_name
   info • The method '_addSource' isn't used • lib/ui/host/payment/StripePage.dart:27:8 • unused_element
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/host/profile/ProfilePageHost.dart:21:7 • must_be_immutable
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method • lib/ui/host/profile/ProfilePageHost.dart:61:8
          • must_call_super
   info • The value of the local variable '_editMode' isn't used • lib/ui/host/profile/ProfilePageHost.dart:62:10 • unused_local_variable
   info • The method '_showScoreInfoDialog' isn't used • lib/ui/host/profile/ProfilePageHost.dart:128:8 • unused_element
   info • The value of the local variable 'height' isn't used • lib/ui/host/profile/ProfilePageHost.dart:158:12 • unused_local_variable
   info • The method '_reloadProfileImage' isn't used • lib/ui/host/profile/ProfilePageHost.dart:625:8 • unused_element
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/login/CuisinesFullScreenDialogPage.dart:24:8 • must_call_super
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/login/LanguagesFullScreenDialogPage.dart:25:8 • must_call_super
   info • Unused import: 'package:thetable/entity/User.dart' • lib/ui/login/LoginPage.dart:7:8 • unused_import
   info • The value of the field '_radioValue' isn't used • lib/ui/login/LoginPage.dart:52:7 • unused_field
   info • The method '_handleRadioValueChange' isn't used • lib/ui/login/LoginPage.dart:485:8 • unused_element
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/login/PlaceTypesFullScreenDialogPage.dart:6:7 • must_be_immutable
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/login/PlaceTypesFullScreenDialogPage.dart:24:8 • must_call_super
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/login/RegistrationAdditionalForm.dart:39:7 • must_be_immutable
   info • The value of the local variable 'now' isn't used • lib/ui/login/RegistrationAdditionalForm.dart:1378:11 • unused_local_variable
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/NavigationScaffoldGuest.dart:15:7 • must_be_immutable
   info • The value of the field '_children' isn't used • lib/ui/pages/NavigationScaffoldGuest.dart:30:22 • unused_field
   info • The value of the local variable 'width' isn't used • lib/ui/pages/NavigationScaffoldGuest.dart:119:12 • unused_local_variable
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:17:7 • must_be_immutable
   info • The value of the field '_dateKey' isn't used • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:35:30 • unused_field
   info • The value of the field '_timeKey' isn't used • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:36:30 • unused_field
   info • The value of the field '_tagsKey' isn't used • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:37:30 • unused_field
   info • The value of the field '_spotKey' isn't used • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:38:30 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:52:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/events/event_creation/EventCreationFiltersPage.dart:54:7 • non_constant_identifier_names
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/events/event_creation/EventCreationPlacePage.dart:27:7 • must_be_immutable
   info • The value of the field '_selectedDrawerIndex' isn't used • lib/ui/pages/events/event_creation/EventCreationPlacePage.dart:42:7 • unused_field
   info • The value of the field '_address' isn't used • lib/ui/pages/events/event_creation/EventCreationPlacePage.dart:55:10 • unused_field
   info • The value of the field '_dialVisible' isn't used • lib/ui/pages/events/event_creation/EventCreationPlacePage.dart:68:8 • unused_field
   info • The method '_buildRestaurantList' isn't used • lib/ui/pages/events/event_creation/EventCreationPlacePage.dart:672:16 • unused_element
   info • Don't import implementation files from another package • lib/ui/pages/events/event_creation/RestaurantSearchBar.dart:5:8 • implementation_imports
   info • The method '_buildGuestsList' isn't used • lib/ui/pages/events/event_info/EventGuestsListPage.dart:349:19 • unused_element
   info • Avoid using braces in interpolation when not needed • lib/ui/pages/events/event_info/EventGuestsListPage.dart:356:18 • unnecessary_brace_in_string_interps
   info • The value of the local variable 'width' isn't used • lib/ui/pages/events/event_info/EventInfoPageGuest.dart:72:12 • unused_local_variable
   info • Await only futures • lib/ui/pages/events/event_info/EventInfoPageGuest.dart:375:25 • await_only_futures
   info • Await only futures • lib/ui/pages/events/event_info/EventInfoPageGuest.dart:398:27 • await_only_futures
   info • Await only futures • lib/ui/pages/events/event_info/EventInfoPageGuest.dart:407:27 • await_only_futures
   info • The method '_buildDialog' isn't used • lib/ui/pages/events/event_info/EventInfoPageGuest.dart:478:10 • unused_element
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/events/event_info/UserSwipeCard.dart:8:7 • must_be_immutable
   info • The operator x ~/ y is more efficient than (x / y).toInt() • lib/ui/pages/events/event_info/UserSwipeCard.dart:97:47 • division_optimization
   info • Use `;` instead of `{}` for empty constructor bodies • lib/ui/pages/events/event_info/chat/EventChatPage.dart:88:45 • empty_constructor_bodies
   info • Unused import: 'package:flutter_speed_dial/flutter_speed_dial.dart' • lib/ui/pages/events/event_search/SearchEventsPage.dart:5:8 • unused_import
   info • Unused import: 'package:intl/intl.dart' • lib/ui/pages/events/event_search/SearchEventsPage.dart:9:8 • unused_import
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/events/event_search/SearchEventsPage.dart:34:7 • must_be_immutable
   info • The value of the field '_selectedDrawerIndex' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:50:7 • unused_field
   info • The value of the field '_currentPosition' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:80:10 • unused_field
   info • The value of the field '_dialVisible' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:82:8 • unused_field
   info • The value of the field '_searched' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:83:8 • unused_field
   info • The value of the local variable 'detail' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:202:49 • unused_local_variable
   info • The method '_buildTags' isn't used • lib/ui/pages/events/event_search/SearchEventsPage.dart:264:16 • unused_element
   info • Await only futures • lib/ui/pages/events/event_search/SearchEventsPage.dart:696:7 • await_only_futures
   info • The value of the field '_scaffoldKey' isn't used • lib/ui/pages/events/event_search/event_filters/QuickFiltersEventModalBottomSheet.dart:76:9 • unused_field
   info • Don't import implementation files from another package • lib/ui/pages/events/event_search/my_events/EventSearchBar.dart:5:8 • implementation_imports
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/pages/events/event_search/my_events/MyCreatedEventsPage.dart:35:8 • must_call_super
   info • Await only futures • lib/ui/pages/events/event_search/my_events/MyCreatedEventsPage.dart:114:5 • await_only_futures
   info • Await only futures • lib/ui/pages/events/event_search/my_events/MyCreatedEventsPage.dart:118:5 • await_only_futures
   info • The value of the field '_currentIndex' isn't used • lib/ui/pages/events/event_search/my_events/MyEventsPage.dart:20:7 • unused_field
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/pages/events/event_search/my_events/MyJoinedEventsPage.dart:33:8 • must_call_super
   info • Await only futures • lib/ui/pages/events/event_search/my_events/MyJoinedEventsPage.dart:112:5 • await_only_futures
   info • The method '_openRequestsListPage' isn't used • lib/ui/pages/events/event_search/my_events/MyJoinedEventsPage.dart:128:8 • unused_element
   info • The value of the local variable 'numParticipants' isn't used • lib/ui/pages/events/event_search/my_events/MyJoinedEventsPage.dart:145:9 • unused_local_variable
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method •
          lib/ui/pages/events/event_search/my_events/MyWaitingEventsPage.dart:34:8 • must_call_super
   info • Await only futures • lib/ui/pages/events/event_search/my_events/MyWaitingEventsPage.dart:115:5 • await_only_futures
   info • The value of the local variable 'numParticipants' isn't used • lib/ui/pages/events/event_search/my_events/MyWaitingEventsPage.dart:140:9 • unused_local_variable
   info • The method '_openRequestsListPage' isn't used • lib/ui/pages/events/event_search/my_events/MyWaitingEventsPage.dart:318:8 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/events/event_search/my_events/RequestsListPage.dart:37:18 • non_constant_identifier_names
   info • The value of the field '_scaffoldKey' isn't used • lib/ui/pages/events/event_search/restaurant_filters/QuickFiltersRestaurantModalBottomSheet.dart:73:9 •
          unused_field
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/ui/pages/profile/ProfilePage.dart:17:7 • must_be_immutable
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method • lib/ui/pages/profile/ProfilePage.dart:51:8 •
          must_call_super
   info • The value of the local variable '_editMode' isn't used • lib/ui/pages/profile/ProfilePage.dart:52:10 • unused_local_variable
   info • The method '_showScoreInfoDialog' isn't used • lib/ui/pages/profile/ProfilePage.dart:119:8 • unused_element
   info • The value of the local variable 'height' isn't used • lib/ui/pages/profile/ProfilePage.dart:149:12 • unused_local_variable
   info • Await only futures • lib/ui/pages/profile/UserSettingsPage.dart:220:7 • await_only_futures
   info • Await only futures • lib/ui/pages/profile/UserSettingsPage.dart:226:7 • await_only_futures
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:4:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:5:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:6:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:7:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:8:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:9:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:10:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:11:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:12:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:13:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:14:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:15:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:16:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:19:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:20:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:21:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:22:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:24:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:26:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:28:17 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Configuration.dart:32:17 • non_constant_identifier_names
   info • Avoid using unnecessary statements • lib/utils/Utils.dart:96:7 • unnecessary_statements
   info • This function has a return type of 'String', but doesn't end with a return statement • lib/utils/Utils.dart:198:10 • missing_return
   info • This function has a return type of 'String', but doesn't end with a return statement • lib/utils/Utils.dart:217:10 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/Utils.dart:217:17 • non_constant_identifier_names
```

## Flutter doctor -v: 
```
[✓] Flutter (Channel master, v1.0.1-pre.8, on Mac OS X 10.14.1 18B75, locale en-IT)
    • Flutter version 1.0.1-pre.8 at /Users/mel/Applications/flutter
    • Framework revision e7a4e7c3b6 (2 hours ago), 2018-12-10 11:21:28 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • ONEPLUS A6013 •                              • android-arm64 • Android 9 (API 28)
    • iPhone XR     • • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by melvinm99** [comment]
I think the problem is that TargetPlatform, which in some way is set to iOS.... I'll keep on investigating on that and write back any potential fix.

**Comment by melvinm99** [comment]
Workaround (or, at least, something similar):
if(LocalPlatform().isAndroid)
      debugDefaultTargetPlatformOverride = TargetPlatform.android;
    else
      debugDefaultTargetPlatformOverride = TargetPlatform.iOS;

**Comment by EHBradford** [comment]
Encountering a black screen on an IOS device myself.   Android platform works.   

I'm sorry but I am a complete Flutter novice so I probably cannot be much of any additional help per debugging myself.

One thing to note, I cannot locate anything even remotely resembling AppDelegate.m on my system so in an effort to get Google Maps running. on IOS I copied the example as shown on multiple websites to the appropriate place and put in my maps API Key.

**Comment by collinjackson** [comment]
@iskakaushik

**Comment by iskakaushik** [comment]
@melvinm99 i tried to repro using the following snippet, but things seem to work fine, https://gist.github.com/iskakaushik/693e9b54331960a59ee5ac20ec8b25e1 let me know if you are still seeing this issue on the latest version of the plugin, will re-open the issue.
