### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by liuzhengcai** [flutter/flutter#25182]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xe4 (at offset 9)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:484:15)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    [32m•[39m Flutter version 1.0.0 at D:\AndroidSDK\flutter
    [32m•[39m Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at E:\androidsdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = E:\androidsdk
    [32m•[39m Java binary at: F:\android-studio-ide-181.5014246-windows\android-studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at F:\android-studio-ide-181.5014246-windows\android-studio
    [32m•[39m Flutter plugin version 31.1.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by GaryQian** [comment]
Related to https://github.com/flutter/flutter/issues/15646

**Comment by DineshTamang** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target lib/main.dart --target-platform android-arm --precompiled --asset-dir C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\release/flutter_assets --release

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\release\flutter_assets\images\quartha_tutorial.png' (OS Error: The system cannot find the file specified.
, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
    • Flutter version 1.0.0 at C:\Users\ENiX\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ENiX\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
