### ISSUE TITLE
error when running default widget_test.dart: 

### ISSUE THREAD

**Issue by yev17** [flutter/flutter#25197]
## Steps to Reproduce
Restarted Windows 10
removed all files from 'C:\Users\blue\AppData\Local\Temp\'
started Android Studio
Created new Flutter Project
Ran it successfully
Opened 'widget_test.dart', ran it.

One out of two tests failed:  The process cannot access the file because it is being used by another process.

## Logs

```
Testing started at 4:24 AM ...
D:\dev\src\flutter\flutter\bin\flutter.bat --no-color test --machine --plain-name "Counter increments smoke test" test\widget_test.dart
unhandled error during finalization of test:
D:\dev\quane\flutter\t2\test\widget_test.dart
FileSystemException: Deletion failed, path = 'C:\Users\blue\AppData\Local\Temp\flutter_test_listener.84f200aa-fd26-11e8-8dc3-7440bbd6aa69' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:207:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      _FlutterPlatform._createListenerDart.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:819:15)
<asynchronous suspension>
#4      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:785:26)
<asynchronous suspension>
#5      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:465:36)
#6      _FlutterPlatform.load (package:flutter_tools/src/test/flutter_platform.dart:420:46)
<asynchronous suspension>
#7      Loader.loadFile.<anonymous closure> (package:test_core/src/runner/loader.dart:222:36)
<asynchronous suspension>
#8      new LoadSuite.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/load_suite.dart:98:31)
<asynchronous suspension>
#9      invoke (package:test_api/src/utils.dart:241:5)
#10     new LoadSuite.<anonymous closure> (package:test_core/src/runner/load_suite.dart:97:7)
#11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:399:25)
<asynchronous suspension>
#12     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#14     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#15     _rootRun (dart:async/zone.dart:1120:38)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#20     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#24     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#25     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#26     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


FileSystemException: Deletion failed, path = 'C:\Users\blue\AppData\Local\Temp\flutter_test_listener.84f200aa-fd26-11e8-8dc3-7440bbd6aa69' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

dart:io/directory_impl.dart 207:7                                     _Directory._deleteSync
dart:io/file_system_entity.dart 466:47                                FileSystemEntity.deleteSync
package:file/src/forwarding/forwarding_file_system_entity.dart 72:16  ForwardingFileSystemEntity.deleteSync
package:flutter_tools/src/test/flutter_platform.dart 819:15           _FlutterPlatform._createListenerDart.<fn>
===== asynchronous gap ===========================
dart:async/future_impl.dart 22:43                                     _Completer.completeError
dart:async/runtime/libasync_patch.dart 43:20                          _AsyncAwaitCompleter.completeError.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15          StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48          StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1120:38                                          _rootRun
dart:async/zone.dart 1021:19                                          _CustomZone.run
dart:async/zone.dart 923:7                                            _CustomZone.runGuarded
dart:async/zone.dart 963:23                                           _CustomZone.bindCallbackGuarded.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15          StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48          StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1124:13                                          _rootRun
dart:async/zone.dart 1021:19                                          _CustomZone.run
dart:async/zone.dart 923:7                                            _CustomZone.runGuarded
dart:async/zone.dart 963:23                                           _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 41:21                              _microtaskLoop
dart:async/schedule_microtask.dart 50:5                               _startMicrotaskLoop
dart:isolate/runtime/libisolate_patch.dart 115:13                     _runPendingImmediateCallback
dart:isolate/runtime/libisolate_patch.dart 172:5                      _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1045:19                                          _CustomZone.registerCallback
dart:async/zone.dart 962:22                                           _CustomZone.bindCallbackGuarded
dart:async/schedule_microtask.dart 147:47                             scheduleMicrotask
dart:async/runtime/libasync_patch.dart 42:7                           _AsyncAwaitCompleter.completeError
package:flutter_tools/src/test/flutter_platform.dart                  _FlutterPlatform._createListenerDart.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                          _CustomZone.registerUnaryCallback
dart:async/runtime/libasync_patch.dart 77:23                          _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart                  _FlutterPlatform._startTest
package:flutter_tools/src/test/flutter_platform.dart 465:36           _FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 420:46           _FlutterPlatform.load
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                          _CustomZone.registerUnaryCallback
dart:async/runtime/libasync_patch.dart 77:23                          _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                              Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31                    new LoadSuite.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1045:19                                          _CustomZone.registerCallback
dart:async/zone.dart 962:22                                           _CustomZone.bindCallbackGuarded
dart:async/timer.dart 52:45                                           new Timer
dart:async/timer.dart 87:9                                            Timer.run
dart:async/future.dart 174:11                                         new Future
package:test_api/src/backend/invoker.dart 398:11                      Invoker._onRun.<fn>.<fn>.<fn>
```

```
D:\dev\quane\flutter\t2>flutter analyze
Analyzing t2...
No issues found! (ran in 1.4s)
```

```
D:\dev\quane\flutter\t2>flutter doctor -v
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 1.0.0 at D:\dev\src\flutter\flutter
    • Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\blue\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\dev\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\dev\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.29.1)
    • VS Code at C:\Users\blue\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Sounds like some anti-virus is locking files in C:\Users\blue\AppData\Local\Temp\

**Comment by yev17** [comment]
You're correct!
This problem was caused by McAfee antivirus.  Replacing it with ZoneAlarm (I planned to do it anyway) did the trick.
Thank you!
    On Tuesday, December 11, 2018, 5:06:48 AM EST, Günter Zöchbauer <notifications@github.com> wrote:  
 
 
Sounds like some anti-virus is locking files in C:\Users\blue\AppData\Local\Temp\
