### ISSUE TITLE
Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture... on a Null object Reference

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#25241]
When running the camera plugin (camera: ^0.2.6), even with the example code, if you try to take a photo for the first time, you'll often get the below error. Toggling the cameras get the camera to show up and it works fine, but checking for the initialized state of the camera first doesn't help in this instance.

```
W/CameraDevice-JV-0(14986): Stream configuration failed due to: endConfigure:508: Camera 0: Unsupported set of inputs/outputs provided
E/CameraCaptureSession(14986): Session 0: Failed to create capture session; configuration failed
E/MethodChannel#plugins.flutter.io/camera(14986): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(14986): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
E/MethodChannel#plugins.flutter.io/camera(14986): 	at io.flutter.plugins.camera.CameraPlugin$Camera.takePicture(CameraPlugin.java:577)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:256)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:202)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/camera(14986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (14986): Error: error
I/flutter (14986): Error Message: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference

```

**Comment by zoechi** [comment]
Looks like #25036 but there is only a part of the exception output visible in a screenshot.
#25036 and 24891 show 
```
E/CameraCaptureSession(14986): Session 0: Failed to create capture session; configuration failed
```
in their output. Not sure if this is related to or causing the crash.

**Comment by kunalgrover05** [comment]
Couldn't find out why the bug happens, but seems like it is related to some initialization callback not waited correctly for in the plugin. 

#### Repro scenario:
Case where Camera and Storage permissions were asked(first launch). In the related bugs too, it is the same case where the bug is intermittent. 

#### Workaround:
Ugly hack to add a simple delay before calling ```controller.takePicture(filePath)```. Based on: https://stackoverflow.com/questions/37509237/taking-images-camera2api/40904906#40904906

```
      await Future.delayed(new Duration(seconds: 1));
```

**Comment by kangwang1988** [comment]
@ToxicAlex 
Can you reproduce this issue using the latest plugin example:
i.e., 0.3.0+1: https://github.com/flutter/plugins/blob/master/packages/camera/pubspec.yaml
I tried it using the latest master, but can't reproduce it.

**Comment by ToxicAlex** [comment]
I was able to reproduce it here: https://gist.github.com/ToxicAlex/a05a7dfdf24a034c6d8b671c7c115b63

Looks like it could do with the image being deleted and then recreated with the same name

**Comment by ToxicAlex** [comment]
From a bit more testing I found that the error didn't occur every time so I updated main.dart to run the breaking code until an error occurs (after initialising by touching on the gesture detector).

**Comment by kangwang1988** [comment]
@ToxicAlex 
It's your custom code(while loop) which resulted in this issue.
```
  void _runErrorCreation() async {
    if (!_runningErrorCreation) {
      _count = 0;
      _runningErrorCreation = true;
      await _startImageStream();
//      while (await _startImageStream()) {}
      _runningErrorCreation = false;
    }
  }
```

**Comment by ToxicAlex** [comment]
@kangwang1988 yes it's when the image stream is started a second (or subsequent times) that the error is caused. But in my application I wanted to be able to stop the image stream and take a photo again before starting the image stream. How can I avoid causing this error?

**Comment by zoechi** [comment]
Let the plugin maintainer decide if this is working as intended or a bug.

**Comment by CoreyCole** [comment]
I'm getting this error only in release mode on android (debug mode it is working fine):
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
       at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
       at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:7009)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
The error occurs when we try to start the camera preview after the user grants camera permission.

**Comment by pratamatama** [comment]
I also getting this error when capturing image.

```
E/MethodChannel#plugins.flutter.io/camera(32435): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(32435): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
E/MethodChannel#plugins.flutter.io/camera(32435): 	at io.flutter.plugins.camera.Camera.takePicture(Camera.java:253)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:77)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#plugins.flutter.io/camera(32435): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/flutter (32435): CameraException(error, Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference)
```
