### ISSUE TITLE
webview_flutter running crash

### ISSUE THREAD

**Issue by huang-weilong** [flutter/flutter#25259]
When I run the example of the webview_flutter plugin and open the webpage (https://flutter.io), I click on any link in the webpage, the program crashes, the phone does not respond, and I can only force the phone to restart. The following is the log information:
```W/System.err( 5829): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
W/System.err( 5829): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1399)
W/System.err( 5829): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1386)
W/System.err( 5829): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
W/System.err( 5829): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
W/System.err( 5829): 	at com.android.webview.chromium.WebViewContentsClientAdapter$NullWebViewClient.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:233)
W/System.err( 5829): 	at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:401)
W/System.err( 5829): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:261)
W/System.err( 5829): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 5829): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err( 5829): 	at android.os.Handler.dispatchMessage(Handler.java:111)
W/System.err( 5829): 	at android.os.Looper.loop(Looper.java:194)
W/System.err( 5829): 	at android.app.ActivityThread.main(ActivityThread.java:5714)
W/System.err( 5829): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5829): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5829): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
W/System.err( 5829): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
F/chromium( 5829): [FATAL:jni_android.cc(269)] Check failed: false. Please include Java exception stack in crash report
F/libc    ( 5829): Fatal signal 6 (SIGABRT), code -6 in tid 5829 (wflutterexample)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

What webview_flutter version are you using (check `pubspec.lock`)

**Comment by zoechi** [comment]
#24866 is similar for `url_launcher`

**Comment by scofield-hello** [comment]
I have the same problem

**Comment by timtraversy** [comment]
I get this crash with the `webview_flutter` plugin, but also if I just create an Android WebView myself. Running Android 5 on a Galaxy S4.

**Comment by zoechi** [comment]
Don't forget to thumbs-up the initial comment which is used for priority

**Comment by kangwang1988** [comment]
@huang-weilong 
A minimal demo would be helpful.

**Comment by timtraversy** [comment]
This `lib/main.dart` is enough for repro:
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://flutter.io',
    );
  }
}
```
If you click on any button on that web page the app crashes with error:
```
flutter.tools W/System.err( 7414): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
flutter.tools W/System.err( 7414): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1610)
flutter.tools W/System.err( 7414): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1597)
flutter.tools W/System.err( 7414): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
flutter.tools W/System.err( 7414): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
flutter.tools W/System.err( 7414): 	at com.android.webview.chromium.WebViewContentsClientAdapter$NullWebViewClient.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:199)
flutter.tools W/System.err( 7414): 	at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:339)
flutter.tools W/System.err( 7414): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:261)
flutter.tools W/System.err( 7414): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
flutter.tools W/System.err( 7414): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:28)
flutter.tools W/System.err( 7414): 	at android.os.Handler.dispatchMessage(Handler.java:102)
flutter.tools W/System.err( 7414): 	at android.os.Looper.loop(Looper.java:145)
flutter.tools W/System.err( 7414): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
flutter.tools W/System.err( 7414): 	at java.lang.reflect.Method.invoke(Native Method)
flutter.tools W/System.err( 7414): 	at java.lang.reflect.Method.invoke(Method.java:372)
flutter.tools W/System.err( 7414): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
flutter.tools W/System.err( 7414): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
flutter.tools F/chromium( 7414):    [FATAL:jni_android.cc(271)] Check failed: false.
flutter.tools F/libc    ( 7414):    Fatal signal 6 (SIGABRT), code -6 in tid 7414 (example.newproj)
```
I can repro this on a Galaxy S4 running 5.0.

**Comment by kangwang1988** [comment]
Using the latest master branch(flutter and plugins), I failed to reproduce this crash:
'flutter doctor -v'
```dart
KyleWongdeMacBook-Pro:flutter_issue_25259 kylewong$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.2-pre.19, on Mac OS X 10.14.4 18E184e, locale en-CN)
    • Flutter version 1.2.2-pre.19 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 20d9de58d0 (7 hours ago), 2019-02-15 18:43:36 -0800
    • Engine revision 033f2072c3
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
```
![image](https://user-images.githubusercontent.com/817851/52897544-dbccac00-3210-11e9-8a43-9313d77fee95.png)

**Comment by timtraversy** [comment]
What Android OS is that?

**Comment by kangwang1988** [comment]
Android 8

**Comment by timtraversy** [comment]
Well I'm running 5.0 (admittedly old). I wonder what @huang-weilong is using. I think this is probably OS specific.

**Comment by huang-weilong** [comment]
I am using Android 5.1 (API 22). You can view the `flutter doctor -v` information I commented on earlier. @timtraversy

**Comment by zoechi** [comment]
Looks like there was a similar issue with `url_launcher` that was fixed recently #24866

**Comment by TahaTesser** [comment]
Issue is reproduced on 

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.84], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\Code\flutter_stable
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Code\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

<details>
 <summary>Code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://flutter.io',
    );
  }
}

```


</details>

<details>
 <summary>Logs</summary>

```
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity( 2440): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 2440): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 2440): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 2440): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 2440): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@28f991b5
D/FlutterActivityAndFragmentDelegate( 2440): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation( 2440): eglMakeCurrent: 0x7f00a6214200: ver 3 1
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
D/        ( 2440): HostConnection::get() New Host Connection established 0x7f00b39570f0, tid 2474
D/        ( 2440): HostConnection::get() New Host Connection established 0x7f00a8e480f0, tid 2457
I/art     ( 2440): Background partial concurrent mark sweep GC freed 1355(126KB) AllocSpace objects, 0(0B) LOS objects, 53% free, 884KB/1908KB, paused 197.216ms total 303.235ms
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
I/WebViewFactory( 2440): Loading com.android.webview version 37 (4174711-x86_64) (code 100008)
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
I/LibraryLoader( 2440): Loading: webviewchromium
I/LibraryLoader( 2440): Time to load native libraries: 1017 ms (timestamps 6471-7488)
I/LibraryLoader( 2440): Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider( 2440): Binding Chromium to main looper Looper (main, tid 1) {1f77426d}
I/LibraryLoader( 2440): Expected native library version number "",actual native library version number ""
I/chromium( 2440): [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController( 2440): Initializing chromium process, renderers=0
W/art     ( 2440): Attempt to remove local handle scope entry from IRT, ignoring
W/AudioManagerAndroid( 2440): Requires BLUETOOTH permission
W/chromium( 2440): [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
I/chromium( 2440): [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=72 off=46092 len=2953
I/chromium( 2440): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:73 off:228796 len:643667
D/EGL_emulation( 2440): eglCreateContext: 0x7f00a3848740: maj 3 min 1 rcv 4
D/EGL_emulation( 2440): eglMakeCurrent: 0x7f00a3848740: ver 3 1
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008824
W/chromium( 2440): [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
W/chromium( 2440): [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
W/art     ( 2440): Attempt to remove local handle scope entry from IRT, ignoring
W/AwContents( 2440): onDetachedFromWindow called when already detached. Ignoring
D/EGL_emulation( 2440): eglMakeCurrent: 0x7f00b3f50200: ver 3 1
D/EGL_emulation( 2440): eglMakeCurrent: 0x7f00b3f50200: ver 3 1
D/EGL_emulation( 2440): eglMakeCurrent: 0x7f00b3f50200: ver 3 1
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x00008741
D/        ( 2440): HostConnection::get() New Host Connection established 0x7f00a9098080, tid 2456
W/chromium( 2440): [WARNING:simple_index_file.cc(337)] Could not map Simple Index file.
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
D/MediaResourceGetter( 2440): no ethernet/wifi connection detected
W/MediaResourceGetter( 2440): non-file URI can't be read due to unsuitable network conditions
E/MediaResourceGetter( 2440): Unable to configure metadata extractor
I/art     ( 2440): Background sticky concurrent mark sweep GC freed 4167(189KB) AllocSpace objects, 0(0B) LOS objects, 13% free, 1645KB/1908KB, paused 52.891ms total 122.030ms
D/MediaResourceGetter( 2440): no ethernet/wifi connection detected
W/MediaResourceGetter( 2440): non-file URI can't be read due to unsuitable network conditions
E/MediaResourceGetter( 2440): Unable to configure metadata extractor
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
D/MediaResourceGetter( 2440): no ethernet/wifi connection detected
W/MediaResourceGetter( 2440): non-file URI can't be read due to unsuitable network conditions
E/MediaResourceGetter( 2440): Unable to configure metadata extractor
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon( 2440): glUtilsParamSize: unknow param 0x000085b5

```

</details>

**Comment by danagbemava-nc** [comment]
@huang-weilong I tried to reproduce your issue but since I do not have the specific OS version to verify this behaviour, can you confirm if this is still an issue using the latest plugin and framework version?
