### ISSUE TITLE
Error during screenshot of flutter app,no app crash but console print this error,Android

### ISSUE THREAD

**Issue by theshivamlko** [flutter/flutter#25311]
```
Gesture Screenshot Enabled = true
D/ViewRootImpl(17810): Gesture Screenshot triggered, ignore event
I/chatty  (17810): uid=10217(app.beetu.beetu) identical 2 lines
D/ViewRootImpl(17810): Gesture Screenshot triggered, ignore event
E/flutter (17810): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (17810): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 248 pos 18: '_pointers.containsKey(datum.device)': is not true.
E/flutter (17810): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (17810): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (17810): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:248:18)
E/flutter (17810): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
E/flutter (17810): #4      ListQueue.addAll (dart:collection/queue.dart:715:25)
E/flutter (17810): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
E/flutter (17810): #6      _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (17810): #7      _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
D/ViewRootImpl(17810): Gesture Screenshot triggered, ignore event
```

## Steps to Reproduce

1. ListView with each item has GestureDetector, 
2. on taking Screenshot with 3 finger swipe from top to bottom this error shows in console
3. Device OnePlus 3T, Android 8.0
 
 
##flutter doctor -v here.  
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 1.0.0 at F:\Programming\Flutter\flutter
    • Framework revision 5391447fae (13 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Navoki\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Navoki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected device (1 available)
    • ONEPLUS A3003 • ec6202af • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
