### ISSUE TITLE
Exception in Flutter when running on Android emulator (TextEdit)

### ISSUE THREAD

**Issue by kika** [flutter/flutter#25355]
I did `flutter upgrade`, I'm on `dev` channel, version is 1.1.1-pre5
Android emulator comes from Android Studio 3.3RC2. The emulated device is API22 5.1

Steps to reproduce:
```
cd flutter/examples/flutter_gallery
flutter pub get
flutter run -d emulator-5554
```

Go to Material -> Text Fields, enter something in the first field (`Name`) then move the cursor back with the keyboard arrows and delete a character with the `Delete` key. Then move the cursor to the right with the arrow key. Bammm:

```
I/flutter (13229): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (13229): The following NoSuchMethodError was thrown during a platform message callback:
I/flutter (13229): The getter 'length' was called on null.
I/flutter (13229): Receiver: null
I/flutter (13229): Tried calling: length
I/flutter (13229): When the exception was thrown, this was the stack:
I/flutter (13229): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (13229): #1      RenderEditable._handleHorizontalArrows (package:flutter/src/rendering/editable.dart:320:49)
I/flutter (13229): #2      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:289:19)
I/flutter (13229): #3      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:244:17)
I/flutter (13229): <asynchronous suspension>
I/flutter (13229): #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:65:49)
I/flutter (13229): <asynchronous suspension>
I/flutter (13229): #5      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
I/flutter (13229): <asynchronous suspension>
I/flutter (13229): #6      _invoke3 (dart:ui/hooks.dart:201:13)
I/flutter (13229): #7      _dispatchPlatformMessage (dart:ui/hooks.dart:110:5)
I/flutter (13229): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by kika** [comment]
Can not reproduce on iOS, neither Simulator nor a real device. Do not have an Android device, unfortunately.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by HansMuller** [comment]
cc @jslavitz

**Comment by kika** [comment]
I've updated already, so the version now is 1.1.2-pre.24, but the crash is still reproducible on Android emulator. Here's the `flutter doctor -v`:
```
flutter doctor -v
[✓] Flutter (Channel master, v1.1.2-pre.24, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.1.2-pre.24 at /Users/kika/Scratch/flutter
    • Framework revision 4cd87705b7 (16 hours ago), 2018-12-13 20:36:08 -0800
    • Engine revision a549981da7
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 5s                 • D0A87E46-DDD7-46CF-B400-B4A4799315FF • ios         • iOS 12.1 (simulator)
```

**Comment by kika** [comment]
I don't know what the tag `team:gallery` means, but this bug is not specific to the gallery, I encountered it in my code, I just used the gallery as an easy repro case.

**Comment by Piinks** [comment]
Hi @kika, Are you still experiencing this issue? I have not been able to reproduce it on an emulator or a physical device.

**Comment by kika** [comment]
@Piinks Not reproducible anymore
