### ISSUE TITLE
NestedScrollView and AnimatedList not working

### ISSUE THREAD

**Issue by Greatcallie** [flutter/flutter#25368]
## Steps to Reproduce

```dart
class Relationships extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
// TODO: implement createState
    return _ViewPostState();
  }
}

class _ViewPostState extends State<Relationships> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
        // Add 6 lines from here...
        body: new NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return <Widget>[
          new SliverAppBar(
            pinned: false,
            title: new Text('Post View'),
          ),
        ];
      },
      body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            new ListView(
              children: <Widget>[
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),
                Text("hello"),

                AnimatedList(
                    itemBuilder: (_, int index, Animation<double> animation) {
                  return Text('hello');
                })
              ],
            ),
          ]),
    ));
  }
}

```

1. ...
2. ...
3. ...
```
## Logs
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performResize():
flutter: Vertical viewport was given unbounded height.
flutter: Viewports expand in the scrolling direction to fill their container.In this case, a vertical
flutter: viewport was given an unlimited amount of vertical space in which to expand. This situation
flutter: typically happens when a scrollable widget is nested inside another scrollable widget.
flutter: If this widget is always nested in a scrollable widget there is no need to use a viewport because
flutter: there will always be enough vertical space for the children. In this case, consider using a Column
flutter: instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
flutter: the height of the viewport to the sum of the heights of its children.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1129:15)
flutter: #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1182:6)
flutter: #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
flutter: #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
flutter: #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #15     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:121:13)
flutter: #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #17     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
flutter: #18     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
flutter: #19     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
flutter: #32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
flutter: #33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
flutter: #34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #39     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #41     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
flutter: #42     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
flutter: #43     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
flutter: #44     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
flutter: #45     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
flutter: #46     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
flutter: #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
flutter: #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #53     _invoke (dart:ui/hooks.dart:154:13)
flutter: #54     _drawFrame (dart:ui/hooks.dart:143:3)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderViewport#cd44f NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#f42f1] ← Semantics ← Listener ←
flutter:   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#f3b13] ←
flutter:   _ScrollSemantics-[GlobalKey#1d8bd] ← Scrollable ← PrimaryScrollController ← ListView ← Column ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
flutter:   size: MISSING
flutter:   axisDirection: down
flutter:   crossAxisDirection: right
flutter:   offset: _NestedScrollPosition#923cb(inner, offset: 0.0, range: null..null, viewport: null)
flutter:   anchor: 0.0
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:   RenderSliverPadding#dff06 NEEDS-LAYOUT NEEDS-PAINT
flutter:     RenderSliverList#7f6af NEEDS-LAYOUT NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderViewport#cd44f NEEDS-LAYOUT NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderViewport#cd44f NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1a4a8 relayoutBoundary=up5 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#e41bd relayoutBoundary=up4 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderPointerListener#ec82c relayoutBoundary=up3 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#4617e relayoutBoundary=up2 NEEDS-PAINT
flutter: Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#94ae5 relayoutBoundary=up1 NEEDS-PAINT
flutter: Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.0.0 at /Users/greatcallie/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/greatcallie/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • BDC07290-93E6-4FB6-B029-4D1E548BA498 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by Greatcallie** [comment]
I have tried several ways of combining the content. initially the list view scrolls then I added Animatedlist and that was the problem.

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

For example I'm pretty sure the issue can be reproduced without importing 

```
import 'package:cached_network_image/cached_network_image.dart';
import 'package:firebase_database/ui/firebase_animated_list.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:naijahub_flutter/widgets/comment_widget.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:flutter_html_view/flutter_html_view.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:photo_view/photo_view.dart';
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Greatcallie** [comment]
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
> 
> For example I'm pretty sure the issue can be reproduced without importing
> 
> ```
> import 'package:cached_network_image/cached_network_image.dart';
> import 'package:firebase_database/ui/firebase_animated_list.dart';
> import 'package:firebase_database/firebase_database.dart';
> import 'package:naijahub_flutter/widgets/comment_widget.dart';
> import 'package:timeago/timeago.dart' as timeago;
> import 'package:flutter_html_view/flutter_html_view.dart';
> import 'package:carousel_slider/carousel_slider.dart';
> import 'package:photo_view/photo_view.dart';
> ```
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Are you with me please?

**Comment by zoechi** [comment]
The error message means that Flutter can't calculate the height
because a widget is inside another widget that has virtually infinite height (scrollable).
You even nested such infinite height widgets.

You might wrap the `ListView` with `Expanded` and `AnimatedList` with 
```dart
                  SizedBox(
                      height: 200,
```
(depending on what you actually try to accomplish)

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Greatcallie** [comment]
But I don't know the size of AnimatedList neither do I know the size of the ListView. How do I let the children determine their size?

**Comment by Greatcallie** [comment]
> The error message means that Flutter can't calculate the height
> because a widget is inside another widget that has virtually infinite height (scrollable).
> You even nested such infinite height widgets.
> 
> You might wrap the `ListView` with `Expanded` and `AnimatedList` with
> 
> ```dart
>                   SizedBox(
>                       height: 200,
> ```
> 
> (depending on what you actually try to accomplish)
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

What am trying to accomplish is not really complicated. I have 2 independent data sources which should serve both the ListView and AnimatedList and I just want them to be able to resize themselves based on the content. Or do I have to route to a new page?

**Comment by zoechi** [comment]
I think this should better be asked on StackOverflow or discussed in Gitter, Google groups, ...

**Comment by Greatcallie** [comment]
You are right! But since you know it, why don't you answer me? Flutter is still relatively new and I may not get an answer there.

**Comment by Greatcallie** [comment]
I mean what then is the use of NestedScrollView if you can't solve this situation. It may be hard to admit but NestedScrollView isn't doing what it was supposed to do!

**Comment by erperejildo** [comment]
@Greatcallie did you solve the issue? I am facing exactly the same thing: I do not know how big my list is going to be. I want it dynamic and have a SizeBox with a fixed height is not a good solution in my opinion @zoechi

**Comment by Greatcallie** [comment]
I used a SizedBox even though as you said it is not the intended behaviour.
But I have moved on...

**Comment by erperejildo** [comment]
how do you specify the full height? Also, what about if you have more element outside this SizedBox? Can you have the same vertical scroll?

Sad that we cannot have an appropriate supper on Flutter original repo

**Comment by Greatcallie** [comment]
You don't specify the full height you simply specify the height of the
SizedBox.

**Comment by erperejildo** [comment]
On that case that's not a good solution. I need a dynamic list with a dynamic height which is going to push down my button to add more items to it. I can't have a fixed height on it I'm afraid

**Comment by erperejildo** [comment]
This is the closest I could get:
```
body: Column(
        children: <Widget>[
          //To insert a listview inside a column,wrap with an Expanded widget
          // to give column an unbounded height for the listview
          Expanded(
            child: SafeArea(
              child: AnimatedList(
                key: _listKey,
                initialItemCount: _data.length,
                itemBuilder:
                    (BuildContext context, int index, Animation animation) {
                  return _buildItem(_data[index], index, animation);
                },
              ),
            ),
          ),
          FloatingActionButton(
            onPressed: () {
              _insertSingleItem();
            },
            tooltip: 'Add new team',
            child: Icon(Icons.add),
            backgroundColor: Colors.red,
          )
        ],
      ),
```
