### ISSUE TITLE
Could not install build/ios/iphoneos/Runner.app on ....

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#25370]
I'm trying to run my application on profile mode with the command: 
```
flutter run --profile --target=lib/main-staging.dart
```

But it doesn't work, it say it can't install it on the device... no problem in debug mode, but release and profile doesn't work... 
No problem on Android :) 

## Logs

[log.txt](https://github.com/flutter/flutter/files/2680025/log.txt)

```
...
[   +5 ms] "flutter run" took 49 234ms.
[        ] Could not install build/ios/iphoneos/Runner.app on 09e05a2baacde4b9261c05f770f8df6cfb1ec4b8.
[   +1 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Error running application on iPhone de Andrea.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale fr-FR)
    • Flutter version 1.0.0 at /Users/jaumard/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK at /Users/jaumard/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.3
    • Dart plugin version 183.4733

[✓] Connected device (1 available)
    • iPhone de Andrea • 09e05a2baacde4b9261c05f770f8df6cfb1ec4b8 • ios • iOS 12.1.1

• No issues found!
```

**Comment by zoechi** [comment]
I assume you tried `flutter clean`?

**Comment by zoechi** [comment]
There are fatal errors
```
            CompileSwift normal armv7
                cd /Users/jaumard/StudioProjects/kiwi_mobile/ios
                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/jaumard/StudioProjects/kiwi_mobile/ios/Runner/AppDelegate.swift /Users/jaumard/StudioProjects/kiwi_mobile/ios/Runner/Utils/HostInfoManager.swift /Users/jaumard/StudioProjects/kiwi_mobile/ios/Runner/Utils/HostInfo.swift -emit-module-path /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/Runner.swiftmodule -emit-module-doc-path /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/Runner.swiftdoc -serialize-diagnostics-path /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/AppDelegate.dia -emit-objc-header-path /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/Runner-Swift.h -emit-dependencies-path /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/AppDelegate.d -target armv7-apple-ios10.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -I /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/FMDB -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/FirebaseCore -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/GTMOAuth2 -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/GTMSessionFetcher -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/GoogleToolboxForMac -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/GoogleUtilities -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/PhoneNumberKit -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/Protobuf -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/RxSwift -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/device_info -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/firebase_analytics -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/flutter_crashlytics -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/flutter_credit_card_dongle -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/flutter_scan_bluetooth -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/flutter_webview_plugin -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/geolocator -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/google_api_availability -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/google_sign_in -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/nanopb -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/native_device_orientation -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/package_info -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/permission_handler -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/phone_number -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/qr_mobile_vision -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/share -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/shared_preferences -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/sqflite -F /Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/url_launcher -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/Crashlytics/iOS -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/Fabric/iOS -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/FirebaseAnalytics/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/FirebaseInstanceID/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/../.symlinks/flutter/ios-profile -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/GoogleAppMeasurement/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/GoogleMobileVision/BarcodeDetector/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/GoogleMobileVision/Detector/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/GoogleSignIn/Frameworks -F /Users/jaumard/StudioProjects/kiwi_mobile/ios/Flutter -g -module-cache-path /Users/jaumard/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4.2 -O -D COCOAPODS -D COCOAPODS -enable-swift3-objc-inference -warn-swift3-objc-inference-minimal -serialize-debugging-options -Xcc -I/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Runner-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/jaumard/StudioProjects/kiwi_mobile/build/ios/Profile-iphoneos/include -Xcc -I/Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/Firebase/CoreOnly/Sources -Xcc -I/Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/Headers/Public -Xcc -I/Users/jaumard/StudioProjects/kiwi_mobile/ios/Pods/Headers/Public/Firebase -Xcc -I/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/DerivedSources/armv7 -Xcc -I/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/DerivedSources -Xcc -DCOCOAPODS=1 -Xcc -DGTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 -Xcc -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -DCOCOAPODS=1 -Xcc -DCOCOAPODS=1 -Xcc -DGTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 -Xcc -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -DGTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 -Xcc -DCOCOAPODS=1 -Xcc -DGTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 -Xcc -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -Xcc -DCOCOAPODS=1 -Xcc -DGTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 -Xcc -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -working-directory/Users/jaumard/StudioProjects/kiwi_mobile/ios -import-objc-header /Users/jaumard/StudioProjects/kiwi_mobile/ios/Runner/Runner-Bridging-Header.h -pch-output-dir /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/PrecompiledHeaders -module-name Runner -num-threads 8 -o /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/AppDelegate.o -o /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/HostInfoManager.o -o /Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/Runner.build/Profile-iphoneos/Runner.build/Objects-normal/armv7/HostInfo.o
            fatal error: file '/Users/jaumard/StudioProjects/kiwi_mobile/ios/Runner/GeneratedPluginRegistrant.h' has been modified since the precompiled header '/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_UHO4D87BWASC-clang_17YH3N4HXBHXH.pch' was built
            note: please rebuild precompiled header '/Users/jaumard/Library/Developer/Xcode/DerivedData/Runner-fhcjnhceqgrsifclykenqneqkwum/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_UHO4D87BWASC-clang_17YH3N4HXBHXH.pch'
```
but I don't know if they are relevant.

**Comment by jaumard** [comment]
Yes I tried `flutter clean` but no luck :/

**Comment by abdalmonem** [comment]
on real device ?
open settings on iphone
navigate to general > device management
select your app profile
tap on "trust"

**Comment by jaumard** [comment]
None of that worked for me @abdalmonem

**Comment by kangwang1988** [comment]
@jaumard 
I've read the log.txt and think zoechi's comment would be more useful, there are fatal errors.
You can try open your-flutter-project/ios with xcode,  I think it will also fail because of a pure ios problem instead of flutter one.

**Comment by jaumard** [comment]
Hello @kangwang1988 

Here is what I've tried from Xcode:

- Run button (debug mode) -> works
- Profile button (release mode) -> works
- Run button (release mode by editing Scheme and chose release build configuration) -> doesn't works but reason is 

```
Could not find an option named "track-widget-creation".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Failed to build /Users/jaumard/StudioProjects/kiwi_mobile2.
Command /bin/sh failed with exit code 255
``` 

Problem is pure iOS but not sure it come from my project here... or at least I don't know what I can do to fix this

**Comment by kangwang1988** [comment]
`track-widget-creation` is created by flutter_tools(debug mode), specified in Generated.xcconfig(TRACK_WIDGET_CREATION=true).
You have to run 'flutter build ios --release' before running the release mode from Xcode. This('flutter build ios --release') will update Generated.xcconfig, it will reset flutter related environment, like
```
FLUTTER_ROOT=/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
FLUTTER_APPLICATION_PATH=/Users/kylewong/Codes/Flutter/alibaba-flutter/plugins/packages/shared_preferences/example
FLUTTER_TARGET=/Users/kylewong/Codes/Flutter/alibaba-flutter/plugins/packages/shared_preferences/example/lib/main.dart
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
FLUTTER_FRAMEWORK_DIR=/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/cache/artifacts/engine/ios-release
```

**Comment by Chetan8488** [comment]
Please follow these commands:
- flutter clear
- flutter build ios

**Comment by ChristianPauly** [comment]
I have the same problem. In Xcode everything is working fine and the app starts but with the command flutter run, I get:

`Launching lib/main.dart on Christians iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team
in Xcode project: 5PML6X8G87
                                                                                 ├─Assembling Flutter resources...                           7,2s               You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.     
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
 └─Compiling, linking and signing...                        41,8s
Xcode build done.                                           74,8s
Installing and launching...                                        40,0s
Could not install build/ios/iphoneos/Runner.app on
67622fc009bf2b55c64bc8a6cee84a8c9ef60283.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Christians iPhone.`

Im using the latest versions of xcode and flutter on a clean new environment. The app is in fact installing on my iPhone and launching but hot reload isn't possible.
I have tried "flutter clean" and "flutter build ios" as mentioned but nothing changed.

**Comment by view-ing** [comment]
> I have the same problem. In Xcode everything is working fine and the app starts but with the command flutter run, I get:
> 
> `Launching lib/main.dart on Christians iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team
> in Xcode project: 5PML6X8G87
> ├─Assembling Flutter resources... 7,2s You've implemented -[ application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
> You've implemented -[ application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
> └─Compiling, linking and signing... 41,8s
> Xcode build done. 74,8s
> Installing and launching... 40,0s
> Could not install build/ios/iphoneos/Runner.app on
> 67622fc009bf2b55c64bc8a6cee84a8c9ef60283.
> Try launching Xcode and selecting "Product > Run" to fix the problem:
> open ios/Runner.xcworkspace
> 
> Error launching application on Christians iPhone.`
> 
> Im using the latest versions of xcode and flutter on a clean new environment. The app is in fact installing on my iPhone and launching but hot reload isn't possible.
> I have tried "flutter clean" and "flutter build ios" as mentioned but nothing changed.

Me too.

Solve ?

**Comment by rohmanhm** [comment]
https://github.com/flutter/flutter/issues/25370

**Comment by Sh1d0w** [comment]
From the following thread https://forums.developer.apple.com/thread/109156

> It seems like the reason causing this problem is the 'get-task-allow' flag of .mobileprovision file, which suppose to be set to true, but now is set to false instead. This 'false' flag causes Xcode losing the privilege to attach the target with debugger.
The problem is caused by Apple's end since they issue the .mobileprovision file, and with free account we do not have the access to alter the flags in that file. The only thing we can do, I think, is waiting for Apple to take actions on this problem.

Solution: pay apple $99 per year ....

**Comment by jaumard** [comment]
@Sh1d0w not the problem here as I'm paying :) but still not able to do it. And if it was the problem it will not work from Xcode too, here it works in my case.

**Comment by khachuong** [comment]
> Please follow these commands:
> 
> ```
> flutter clean
> flutter build ios
> ```

thanks you very much @Chetan8488 , you saved my day

**Comment by kennenfromchina** [comment]
```
➜  zhilun_busin_compan_app git:(dev_card) ✗ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              2.5s
Running Xcode build...

 ├─Assembling Flutter resources...                           9.1s
 └─Compiling, linking and signing...                         8.2s
Xcode build done.                                           20.7s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 11 Pro Max.
➜  zhilun_busin_compan_app git:(dev_card) ✗
```

**Comment by apastuhov** [comment]
@kennenfromchina Maybe you changed name of the application via xcode? Then in `ios/Runner.xcodeproj/project.pbxproj` find `/* Debug */ = {` section, and there change value of `PRODUCT_NAME` to `Runner`.

After that use `flutter clean && flutter run` to run the app. And maybe it is better to put such issues to StackOverflow. ;)

**Comment by peakcool** [comment]
> @kennenfromchina Maybe you changed name of the application via xcode? Then in `ios/Runner.xcodeproj/project.pbxproj` find `/* Debug */ = {` section, and there change value of `PRODUCT_NAME` to `Runner`.
> 
> After that use `flutter clean && flutter run` to run the app. And maybe it is better to put such issues to StackOverflow. :)

THX! :)

**Comment by lukepighetti** [comment]
You used to be able to just change the display name in Xcode and have it work. How are we supposed to change the name now that this breaks builds?

**Comment by erf** [comment]
@lukepighetti i rolled back the name change, then set it again and now it worked..

**Comment by lukepighetti** [comment]
@jmagman requesting reopen and tag `regression`, or the final word on how we're expected to set the name of our iOS apps moving forward

**Comment by jmagman** [comment]
@lukepighetti @erf If you are hitting an issue on app display rename, that sounds like a completely different issue.  You may be hitting https://github.com/flutter/flutter/issues/41793.

**Comment by marceloimg93** [comment]
> @kennenfromchina Maybe you changed name of the application via xcode? Then in `ios/Runner.xcodeproj/project.pbxproj` find `/* Debug */ = {` section, and there change value of `PRODUCT_NAME` to `Runner`.
> 
> After that use `flutter clean && flutter run` to run the app. And maybe it is better to put such issues to StackOverflow. :)

Thanks! This solved my problem!

**Comment by Greatcallie** [comment]
I must say Flutter is getting really more and more difficult to use
