### ISSUE TITLE
 EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by LilySny** [flutter/flutter#25393]
My code is giving this error:

```
I/flutter ( 6493): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6493): The following assertion was thrown building ChatMessage(dirty):
I/flutter ( 6493): 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 451 pos 16: 'url !=
I/flutter ( 6493): null': is not true.
I/flutter ( 6493): 
I/flutter ( 6493): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6493): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6493): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6493):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6493): 
I/flutter ( 6493): When the exception was thrown, this was the stack:
I/flutter ( 6493): #2      new NetworkImage (package:flutter/src/painting/image_provider.dart:451:16)
I/flutter ( 6493): #3      ChatMessage.build (package:chat_online/main.dart:244:32)
I/flutter ( 6493): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter ( 6493): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 6493): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 6493): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 6493): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 6493): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 6493): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 6493): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 6493): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 6493): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 6493): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 6493): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 6493): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 6493): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 6493): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 6493): #27     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 6493): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 6493): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 6493): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 6493): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 6493): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 6493): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 6493): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 6493): #37     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
I/flutter ( 6493): #38     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:20)
I/flutter ( 6493): #39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 6493): #40     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter ( 6493): #41     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter ( 6493): #42     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter ( 6493): #43     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter ( 6493): #44     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter ( 6493): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter ( 6493): #46     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:341:5)
I/flutter ( 6493): #47     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter ( 6493): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #49     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 6493): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #51     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 6493): #52     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter ( 6493): #53     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter ( 6493): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 6493): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #71     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter ( 6493): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 6493): #73     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 6493): #74     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 6493): #75     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 6493): #76     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 6493): #77     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 6493): #78     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 6493): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 6493): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 6493): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 6493): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6493): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6493): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6493): #85     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 6493): #86     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 6493): (elided 2 frames from class _AssertionError)
```

Here is where the error is:

```dart
Expanded(
                child: StreamBuilder(
                    stream: Firestore.instance.collection("messages").snapshots(),
                    builder: (context,snapshot) {
                      switch(snapshot.connectionState){
                        case ConnectionState.none:
                        case ConnectionState.waiting:
                          return Center(
                            child: CircularProgressIndicator(),
                          );
                        default:
                          return ListView.builder(
                              reverse: true,
                              itemCount: snapshot.data.documents.length,
                              itemBuilder: (context, index) {
                                List r = snapshot.data.documents.reversed.toList();
                                return ChatMessage(r[index].data); // this line is the problem
                              }
                          );
```

ChatMessage class:

```dart
class ChatMessage extends StatelessWidget {
  final Map<String, dynamic> data;
  ChatMessage(this.data);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 10.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Container(
            margin: const EdgeInsets.only(right: 16.0 ),
            child: CircleAvatar(
              backgroundImage: NetworkImage(data["senderPhotoUrl"]),
            ),
          ),
          Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(data["senderName"],
                  style: Theme.of(context).textTheme.subhead,),
                  Container(
                    margin: const EdgeInsets.only(top: 5.0),
                    child: data["urlImg"] != null ?
                    Image.network(data["urlImg"], width: 250.0) :
                   Text(data["text"])
                  )
                ],
              ))
        ],
      ),
    );
  }
```

_sendMessage method 

```dart
void _sendMessage({String text, String urlImg}){
Firestore.instance.collection("messages").add(
  {
    "text" : text,
    "urlImg" : urlImg,
    "senderName" : googleSignIn.currentUser.displayName,
    "senderPhotoUrl" : googleSignIn.currentUser.photoUrl
  }
);
}
```

flutter doctor:

```
C:\src\flutter\bin\flutter.bat --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.471], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[!] VS Code (version 1.29.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

packages get :

```
Running "flutter packages get" in chat_online...                 1,4s
Process finished with exit code 0
```

the packages implemented are all in the latest version

**Comment by zoechi** [comment]
You need to return an alternative widget (`Container()` for example if `r[index].data['urlImg']` is `null`

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by aboubackr** [comment]
var uri = await Uri.http("mydomain", "/api/external/mobile", {
          'page': "$_current_page",
          'app_code': 'APP_CODE',
          'query': '123 Main Street',
          'country': 'Fr',
          'language': 'fr',
        });
        var response = await http.get(uri);
        var data = json.decode(response.body);

I/flutter (17190): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17190): The following FormatException was thrown building MyHomePage(dirty, state:
I/flutter (17190): _MyHomePageState#e8248(ticker inactive)):
I/flutter (17190): Invalid radix-10 number
I/flutter (17190): 90.2
