### ISSUE TITLE
This is a small question about the assert

### ISSUE THREAD

**Issue by XHL-study** [flutter/flutter#25396]
## Steps to Reproduce

1.
```
 Widget _sectionTitle(String text) {
    return new Container(
//      color: Colors.blue,
      margin: EdgeInsets.only(top: 20.0, bottom: 10.0),
      child: new Text(text,
          style: new TextStyle(fontSize: 18.0, color: Colors.blueGrey,background: new Paint()..color = Colors.greenAccent.withOpacity(10.5))),
    );
  }
```
2.
![image](https://user-images.githubusercontent.com/22956309/50038123-6cdaa780-0055-11e9-8db3-616d6fcd8602.png)

```

3.flutter doctor -v
```
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.376], locale zh-CN)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!

```

## Logs

I/flutter ( 3071): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3071): The following assertion was thrown building TextPage(dirty):
I/flutter ( 3071): 'dart:ui/painting.dart': Failed assertion: line 187: '<optimized out>': is not true.
I/flutter ( 3071): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3071): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3071): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3071):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 3071): When the exception was thrown, this was the stack:
I/flutter ( 3071): #2      Color.withOpacity (dart:ui/painting.dart:187:12)
I/flutter ( 3071): #3      TextPage._sectionTitle (package:my_first_flutter_app/view/text_page.dart:14:123)
I/flutter ( 3071): #4      TextPage.build (package:my_first_flutter_app/view/text_page.dart:33:17)
I/flutter ( 3071): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter ( 3071): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 3071): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 3071): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 3071): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #26     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 3071): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 3071): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 3071): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 3071): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 3071): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 3071): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 3071): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 3071): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 3071): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 3071): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 3071): #60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 3071): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 3071): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 3071): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3071): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3071): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter ( 3071): #67     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3071): #68     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3071): #69     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 3071): (elided 3 frames from class _AssertionError and package dart:async)
```

```
```

```
```

```
```

**Comment by zoechi** [comment]
The hit exception would be

![image](https://user-images.githubusercontent.com/405837/50056649-1fe2f800-015f-11e9-82b4-f6e457c2d9bb.png)

**Comment by stuz5000** [comment]
Sure seems like this could stand a better error message :-/

**Comment by dlero** [comment]
Hi
The error is here 
Colors.greenAccent.withOpacity(**_10.5_**)

10.5 this number must be between 0 an 1
