### ISSUE TITLE
my problem with post request to a api

### ISSUE THREAD

**Issue by SHIVAGANESHKING** [flutter/flutter#25460]
```
I/flutter ( 5041): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 5041): The following assertion was thrown while handling a gesture:
I/flutter ( 5041): type '_Type' is not a subtype of type 'String'
I/flutter ( 5041): 
I/flutter ( 5041): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5041): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5041): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5041):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5041): 
I/flutter ( 5041): When the exception was thrown, this was the stack:
I/flutter ( 5041): #0      LoginScreenState.build.<anonymous closure> (package:cesr_ui/Login/login_screen.dart:83:21)
I/flutter ( 5041): #1      FormFieldState._validate (package:flutter/src/widgets/form.dart)
I/flutter ( 5041): #2      FormFieldState.validate.<anonymous closure> (package:flutter/src/widgets/form.dart:306:7)
I/flutter ( 5041): #3      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
I/flutter ( 5041): #4      FormFieldState.validate (package:flutter/src/widgets/form.dart:305:5)
I/flutter ( 5041): #5      FormState._validate (package:flutter/src/widgets/form.dart:155:25)
I/flutter ( 5041): #6      FormState.validate (package:flutter/src/widgets/form.dart:149:12)
I/flutter ( 5041): #7      LoginScreenState._submit (package:cesr_ui/Login/login_screen.dart:41:14)
I/flutter ( 5041): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter ( 5041): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter ( 5041): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 5041): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter ( 5041): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter ( 5041): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter ( 5041): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 5041): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 5041): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter ( 5041): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter ( 5041): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter ( 5041): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 5041): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter ( 5041): #21     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter ( 5041): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter ( 5041): 
I/flutter ( 5041): Handler: onTap
I/flutter ( 5041): Recognizer:
I/flutter ( 5041):   TapGestureRecognizer#77654(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter ( 5041):   Offset(181.4, 278.0), sent tap down)
I/flutter ( 5041): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
There might be a missing `()`. Hard to tell without seeing the code.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
