### ISSUE TITLE
Crash on Xiaomi device running on Kitkat when trying to use Firebase packages

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#25491]
When I try to launch the app on Xiaomi device with Kitkat version, the app crash. I included several Firebase packages (`firebase_admob`, `firebase_performance`, `firebase_analytics`, `firebase_auth`)

## Exception

```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/io.anders.randomsensei-2.apk"],nativeLibraryDirectories=[/data/app-lib/io.anders.randomsensei-2, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4828)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4420)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4360)
        at android.app.ActivityThread.access$1500(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5052)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/io.anders.randomsensei-2.apk"],nativeLibraryDirectories=[/data/app-lib/io.anders.randomsensei-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4813)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4420) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4360) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5052) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
        at dalvik.system.NativeStart.main(Native Method) 
```

## Logs

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-MY)
    • Flutter version 1.0.0 at /Users/anders/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/anders/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (3 available)
    • SM T815Y      • 3300ffc315341365                     • android-arm • Android 7.0 (API 24) (emulator)
    • HM 1S         • d0925617                             • android-arm • Android 4.4.4 (API 19)
    • iPhone XS Max • 1272421A-FE77-4B49-9F2E-3EE3A0CF58E3 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
Similar to #20801

**Comment by anderscheow** [comment]
Any potential solution for this problem? It might delay my app going to live

**Comment by jonjon1123** [comment]
I am experiencing this same issue on the below emulator device. Same code had no issues on newer devices. It certainly seems like an issue with older devices.

```
Name: 4.65_720p_Galaxy_Nexus_API_18
CPU/ABI: Google APIs Intel Atom (x86)
Path: C:\Users\Jon\.android\avd\4.65_720p_Galaxy_Nexus_API_18.avd
Target: google_apis [Google APIs] (API level 18)
Skin: 720x1280
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: 4.65in 720p (Galaxy Nexus)
hw.lcd.width: 720
hw.initialOrientation: Portrait
image.androidVersion.api: 18
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: 4.65  720p (Galaxy Nexus) API 18
hw.gpu.mode: auto
hw.ramSize: 1024
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1280
vm.heapSize: 80
skin.dynamic: yes
hw.device.manufacturer: Generic
hw.gps: yes
skin.path.backup: _no_skin
hw.audioInput: yes
image.sysdir.1: system-images\android-18\google_apis\x86\
showDeviceFrame: no
hw.camera.back: virtualscene
AvdId: 4.65_720p_Galaxy_Nexus_API_18
hw.lcd.density: 320
hw.arc: false
hw.device.hash2: MD5:5c288d27461585ecc73a535555e7cf61
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

**Comment by zoechi** [comment]
@jonjon1123 ensure you create an emulator with Google Play

**Comment by jonjon1123** [comment]
@zoechi I am using the system image shown in the following screenshot. It says it has the Google APIs so I assumed it was the correct one.
![image](https://user-images.githubusercontent.com/691969/50617089-f17c5100-0eb0-11e9-8244-ff51c820355d.png)

@kangwang1988 Based on the top up-voted answer in the link you provided, I need to enable multidex. I have `multiDexEnabled true` in my android/app/build.gradle and have tried adding the `implementation 'com.android.support:multidex:1.0.3'` dependency, but it doesn't make any difference. Since this is a Flutter app, I didn't create the Application class. It was set to `android:name="io.flutter.app.FlutterApplication"` out of the box. So I am not sure how I would do the other steps related to the main Application class. Also, I have had the `multiDexEnabled true` setting in place for quite some time with no issues like this.

**Comment by anderscheow** [comment]
Found a workaround.

Create a custom application.
```
package com.example

import android.app.Activity
import android.app.Application
import android.content.Context
import android.support.multidex.MultiDex

import io.flutter.view.FlutterMain

class CustomApplication : Application() {
    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        MultiDex.install(this)
    }

    override fun onCreate() {
        super.onCreate()
        FlutterMain.startInitialization(this)
    }

    private var mCurrentActivity: Activity? = null

    fun getCurrentActivity(): Activity? {
        return mCurrentActivity
    }

    fun setCurrentActivity(mCurrentActivity: Activity) {
        this.mCurrentActivity = mCurrentActivity
    }
}
```

Apply the custom application to AndroidManifest.xml
```
<application
        android:name=".CustomApplication"    <-- Here
        android:label="Example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
```

**Comment by jonjon1123** [comment]
@anderscheow That workaround did the trick for me. Thanks!

**Comment by rdcoder33** [comment]
> ```java
> package com.example
> 
> import android.app.Activity
> import android.app.Application
> import android.content.Context
> import android.support.multidex.MultiDex
> 
> import io.flutter.view.FlutterMain
> 
> class CustomApplication : Application() {
>     override fun attachBaseContext(base: Context) {
>         super.attachBaseContext(base)
>         MultiDex.install(this)
>     }
> 
>     override fun onCreate() {
>         super.onCreate()
>         FlutterMain.startInitialization(this)
>     }
> 
>     private var mCurrentActivity: Activity? = null
> 
>     fun getCurrentActivity(): Activity? {
>         return mCurrentActivity
>     }
> 
>     fun setCurrentActivity(mCurrentActivity: Activity) {
>         this.mCurrentActivity = mCurrentActivity
>     }
> }
> ```

Bro in which file I have to write custom application code?

**Comment by anderscheow** [comment]
@rdcoder33 You have to create a new file named `CustomApplication.kt` (name up to you), then apply this file to your `AndroidManifest.xml`.`<application>` tag

**Comment by zukinaru** [comment]
@anderscheow above solution by creating CustomApplication class, not working for me.

now, it come with new error :

```
E/AndroidRuntime( 2145): java.lang.RuntimeException: Unable to instantiate application example.myapps.CustomApplication: java.lang.ClassNotFoundException: Didn't find class "example.myapps.CustomApplication" on path: DexPathList[[zip file "/data/app/example.myapps-1.apk"],nativeLibraryDirectories=[/data/app-lib/example.myapps-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 2145): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
E/AndroidRuntime( 2145): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4352)
E/AndroidRuntime( 2145): 	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
E/AndroidRuntime( 2145): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
E/AndroidRuntime( 2145): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2145): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2145): 	at android.app.ActivityThread.main(ActivityThread.java:5052)
E/AndroidRuntime( 2145): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2145): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2145): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
E/AndroidRuntime( 2145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
E/AndroidRuntime( 2145): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2145): Caused by: java.lang.ClassNotFoundException: Didn't find class "example.myapps.CustomApplication" on path: DexPathList[[zip file "/data/app/example.myapps-1.apk"],nativeLibraryDirectories=[/data/app-lib/example.myapps-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 2145): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 2145): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 2145): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 2145): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
E/AndroidRuntime( 2145): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
E/AndroidRuntime( 2145): 	... 11 more
```

**Comment by opensourcegps** [comment]
I'm also having this issue. Flutter does not work on API 16-21 with any firebase plugin because of Multidex. 

```
E/AndroidRuntime( 3106): FATAL EXCEPTION: main
E/AndroidRuntime( 3106): Process: com.appname.app, PID: 3106
E/AndroidRuntime( 3106): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.appname.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.appname.app-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 3106): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3106): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 3106): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3106): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3106): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 3106): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 3106): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3106): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/com.appname.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.appname.app-1, /vendor/lib, /system/lib]]
E/AndroidRuntime( 3106): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 3106): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 3106): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 3106): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
E/AndroidRuntime( 3106): 	... 12 more
```

**Comment by kroikie** [comment]
@anderscheow

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/537. Any further collaboration will be done there.

**Comment by iapicca** [comment]
Hi @anderscheow
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you
