### ISSUE TITLE
use TabBar

### ISSUE THREAD

**Issue by YuanGaoQi** [flutter/flutter#25493]
```
I/flutter ( 2811): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 2811): The following assertion was thrown while handling a gesture:
I/flutter ( 2811): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 111 pos 12: 'value >= 0
I/flutter ( 2811): && (value < length || length == 0)': is not true.
I/flutter ( 2811): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2811): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2811): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2811):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 2811): When the exception was thrown, this was the stack:
I/flutter ( 2811): #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:111:12)
I/flutter ( 2811): #3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:163:5)
I/flutter ( 2811): #4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:885:17)
I/flutter ( 2811): #5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:961:21)
I/flutter ( 2811): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter ( 2811): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter ( 2811): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 2811): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter ( 2811): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter ( 2811): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter ( 2811): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 2811): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 2811): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter ( 2811): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter ( 2811): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter ( 2811): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 2811): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter ( 2811): #19     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter ( 2811): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter ( 2811): (elided 2 frames from class _AssertionError)
I/flutter ( 2811): Handler: onTap
I/flutter ( 2811): Recognizer:
I/flutter ( 2811):   TapGestureRecognizer#fbf57(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter ( 2811):   Offset(352.4, 114.6), sent tap down)
I/flutter ( 2811): ═══════════════════════════
```

**Comment by zoechi** [comment]
Please check if it is like #16292

**Comment by zoechi** [comment]
If that doesn't solve your problem ...

to investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by YuanGaoQi** [comment]
update v1.0 ok ,Thank you
