### ISSUE TITLE
Error occuring when using child property with container widget

### ISSUE THREAD

**Issue by hkjain1991** [flutter/flutter#25494]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new FriendlyChatApp());
}

class FriendlyChatApp extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Center(child: Container(
      color: Colors.teal.shade700,
      child: Text('Test'),
      constraints: BoxConstraints(maxHeight: 230.0),
    ),);
  }
}
```
This is above code which I wrote.

Following error is coming after running:
```
I/flutter ( 5276): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5276): The following assertion was thrown building Text("Test"):
I/flutter ( 5276): No Directionality widget found.
I/flutter ( 5276): RichText widgets require a Directionality widget ancestor.
I/flutter ( 5276): The specific widget that could not find a Directionality ancestor was:
I/flutter ( 5276):   RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Test")
I/flutter ( 5276): The ownership chain for the affected widget is:
I/flutter ( 5276):   RichText ← Text ← DecoratedBox ← ConstrainedBox ← Container ← Center ← FriendlyChatApp ← [root]
I/flutter ( 5276): Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
I/flutter ( 5276): top of your application widget tree. It determines the ambient reading direction and is used, for
I/flutter ( 5276): example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
I/flutter ( 5276): EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.
I/flutter ( 5276): 
I/flutter ( 5276): When the exception was thrown, this was the stack:
I/flutter ( 5276): #0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:241:7)
I/flutter ( 5276): #1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:257:4)
I/flutter ( 5276): #2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:4493:37)
I/flutter ( 5276): #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4482:28)
I/flutter ( 5276): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5276): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5276): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5276): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5276): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5276): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5276): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5276): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5276): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5276): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5276): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5276): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5276): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5276): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5276): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5276): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5276): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5276): #33     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
I/flutter ( 5276): #34     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
I/flutter ( 5276): #35     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
I/flutter ( 5276): #36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 5276): #37     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
I/flutter ( 5276): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
I/flutter ( 5276): #39     runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter ( 5276): #40     main (package:flutter_sample_app/main.dart:4:3)
I/flutter ( 5276): #41     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 5276): #42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 5276): ════════════════════════════════════════════════════════════════════════════════════════════════════


Please let me know what I am missing in code.
```

**Comment by zoechi** [comment]
Some widgets depend on ancestor widgets to be available
like `Text()` depends on having an ancestor https://docs.flutter.io/flutter/widgets/Directionality-class.html
If you wrap your root widget in https://docs.flutter.io/flutter/widgets/WidgetsApp-class.html https://docs.flutter.io/flutter/material/MaterialApp-class.html or https://docs.flutter.io/flutter/cupertino/CupertinoApp-class.html this is already included.
As far as I know the direction is derived from the locale by default.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by patelkrunal78** [comment]
Similar issue to No [Directionality widget found](https://icetutor.com/question/no-directionality-widget-found)
