### ISSUE TITLE
Cannot access '<init>': it is public/*package*/ in 'Builder' when adding instabug

### ISSUE THREAD

**Issue by Mantas0726** [flutter/flutter#25500]
I'm trying to add instabug to my flutter project, for now I would be happy to have it working for Android.

If I follow the 2 simple steps provided on instabug installation guide:
1. add - `implementation 'com.instabug.library:instabug:8.0.14'` -> to app level build file
2. Initialize it in -> `MainActivity.kt` like so: 

```java
package com.****

import android.os.Bundle

import com.instabug.library.Instabug
import com.instabug.library.invocation.InstabugInvocationEvent
import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity() : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)

        Instabug.Builder(this, "3e6abe78db59274e7282163467950734")
                .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
                .build()
    }
}
```

But then I encounter an error: 
```
e: C:\myproject_flutter\android\app\src\main\kotlin\com\myproject\myprojectflutter\MainActivity.kt: (15, 18): Cannot access '<init>': it is public/*package*/ in
'Builder'
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 12s
[ +494 ms] Gradle task 'assembleDebug'... (completed)
[  +13 ms] "flutter run" took 19,225ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:399:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:300:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:379:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#26     Future._complete (dart:async/future_impl.dart:476:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

However [this SO question](https://stackoverflow.com/questions/52708370/any-fix-for-instabug-captures-blank-screen-and-video-for-flutter-application-an) suggests, that someone has added it successfully.

What am I doing wrong here? Has anyone successfully installed instabug on their flutter project, help would be much appreciated.

Flutter doctor:

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale en-GB)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Me\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • E6653 • BH901DAE4D • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by Mantas0726** [comment]
> Instabug needs to be initialized with an application context in an application class.

Could you provide an example? 

What do you mean by 'application class'?

**Comment by Hixie** [comment]
This seems like an issue to bring up with instabug... it doesn't seem to be a Flutter-specific issue. Please reopen if you disagree. Thanks!

**Comment by neiljaywarner** [comment]
@Hixie  while i see your point, screen recording tools may depend on "native" Android or iOS recording techniques, and business people requesting these features may not realize Flutter's different approach makes these difficult. (same thing with Appium/etc)

So giving special credence, perhaps in an FAQ to some of these items would be awesome.
e.g.- even if it is very rough.
Q: I used to use get screen recordings from Tool X, which doe snot support them, what do i do?
A: We have heard tool Y supports flutter, here is their support page

Q: I used to use Appium, Espresso and UIAutomator for testing, what do I do know?
A: Since flutter does not view Ids, we cannot find views in the same way, but these same concerns can be met with technique x,y,z.

Sorry to highjack the thread...  or should i put in docuemntation site request?

**Comment by victwise** [comment]
> > Instabug debe inicializarse con un contexto de aplicación en una clase de aplicación.
> 
> @amrbrkt
> ¿Podrías dar un ejemplo?

hi, this works for me :

Instabug.Builder(application, "APP_TOKEN" )
            .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
            .build()

**Comment by victwise** [comment]
> > Instabug needs to be initialized with an application context in an application class.
> 
> @amrbrkt
> Could you provide an example?

hi, this works for me :

`Instabug.Builder(application, "APP_TOKEN" )
            .setInvocationEvents(InstabugInvocationEvent.SHAKE, InstabugInvocationEvent.SCREENSHOT)
            .build()`
