### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ZMAsd** [flutter/flutter#25600]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

HttpException: HttpException: , uri = https://storage.googleapis.com/flutter_infra/flutter/fonts/13ac995daa9dda0a6ba0a45f1fccc541e616a74c/fonts.zip

```
#0      _attempt (package:flutter_tools/src/base/net.dart:63:39)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22:36)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:618:37)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:304:17)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:333:26)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:300:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:320:12)
#7      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:356:12)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:263:11)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:219:26)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:431:19)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:382:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:373:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:111:11)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:51:10)
#41     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#42     main (file:///Users/minzhang/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
encountered exception: Exception: Android sdkmanager tool not found (/Users/minzhang/Library/Android/sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.io/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidLicenseValidator._ensureCanRunSdkManager (package:flutter_tools/src/android/android_workflow.dart:312:7)
#2      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:246:5)
<asynchronous suspension>
#3      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:184:19)
<asynchronous suspension>
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#6      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#11     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#13     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#20     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#22     _doctorText (package:flutter_tools/runner.dart:187:19)
#23     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#24     _doctorText (package:flutter_tools/runner.dart:183:27)
#25     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#26     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#27     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#28     _handleToolError (package:flutter_tools/runner.dart:120:33)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#35     Future._complete (dart:async/future_impl.dart:476:7)
#36     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#37     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#38     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#39     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#40     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#41     _rootRunBinary (dart:async/zone.dart:1144:38)
#42     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#43     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#44     Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#45     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#46     Future._completeError (dart:async/future_impl.dart:494:5)
#47     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#48     _Completer.completeError (dart:async/future_impl.dart:27:5)
#49     _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#50     IOClient.send (package:http/src/io_client.dart)
#51     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#52     _rootRunBinary (dart:async/zone.dart:1144:38)
#53     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#54     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#55     Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#56     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#57     Future._completeError (dart:async/future_impl.dart:494:5)
#58     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:542:7)
#59     _rootRun (dart:async/zone.dart:1124:13)
#60     _CustomZone.run (dart:async/zone.dart:1021:19)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
