### ISSUE TITLE
Finished with error: Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by iBotasky** [flutter/flutter#25605]
## Steps to Reproduce

I'm running my app without errors yesterday, I have not idea what's wrong that I can't run my App
with this error on Android platform. And it's work fine on iOS platform.
that's the errors:
```
Launching lib/main.dart on ONEPLUS A5010 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Finished with error: Invalid argument(s): Invalid type for "path": null
```

## Logs

```
  flutter_cybird git:(master) ✗ flutter run --verbose
[  +27 ms] executing: [/Users/juhu/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/juhu/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/juhu/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/juhu/flutter/] git log -n 1 --pretty=format:%H
[  +17 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 3d8aec2b99b6e7d3190f5e991b86899a2df15e91
[        ] executing: [/Users/juhu/flutter/] git log -n 1 --pretty=format:%ar
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 hours ago
[        ] executing: [/Users/juhu/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +268 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.1.3-9-g3d8aec2b9
[ +296 ms] executing: /Users/juhu/Library/Android/sdk/platform-tools/adb devices -l
[  +43 ms] Exit code 0 from: /Users/juhu/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           342b3a0e               device usb:341835776X product:OnePlus5T model:ONEPLUS_A5010 device:OnePlus5T transport_id:2
[   +7 ms] executing: idevice_id -h
[  +31 ms] /usr/bin/xcrun simctl list --json devices
[ +224 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/juhu/Library/Android/sdk/platform-tools/adb -s 342b3a0e shell getprop
[  +62 ms] ro.hardware = qcom
[   +4 ms] ONEPLUS A5010 • 342b3a0e                             • android-arm64 • Android 8.1.0 (API 27)
[        ] iPhone XR     • 13DC0DBC-478E-4FDC-B7FB-AF0F1E33467D • ios           • iOS 12.1 (simulator)
[   +9 ms] "flutter run" took 635ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:222:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:504:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:460:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:451:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/juhu/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
Analyzing flutter_cybird...                                      

   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:3:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:4:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:5:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:6:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:7:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:10:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:11:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:12:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:13:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:16:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:20:4 • non_constant_identifier_names
   info • The value of the field '_currentIndex' isn't used • lib/ui/movie/Movie.dart:13:7 • unused_field
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:9:8 • unused_import
   info • Unused import: 'package:flutter_cybird/main.dart' • test/widget_test.dart:11:8 • unused_import

```

```
flutter doctor -v
[✓] Flutter (Channel master, v1.1.4-pre.9, on Mac OS X 10.14.2 18C54, locale en-CN)
    • Flutter version 1.1.4-pre.9 at /Users/juhu/flutter
    • Framework revision 3d8aec2b99 (3 hours ago), 2018-12-19 20:09:07 -0800
    • Engine revision 5ec8ef8509
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/juhu/Library/Android/sdk
    • Android NDK at /Users/juhu/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • ONEPLUS A5010 • 342b3a0e                             • android-arm64 • Android 8.1.0 (API 27)
    • iPhone XR     • 13DC0DBC-478E-4FDC-B7FB-AF0F1E33467D • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
To investigate we would need the instructions how to reproduce.
Can you reproduce in a new project created with `flutter create foo`?

**Comment by phoebewow** [comment]
> To investigate we would need the instructions how to reproduce.
> Can you reproduce in a new project created with `flutter create foo`?

I had the same problem, trying flutter create foo and then flutter run, and the same problem
[flutter_01.log](https://github.com/flutter/flutter/files/2697844/flutter_01.log)

**Comment by iBotasky** [comment]
@zoechi yeah, it's reproduce on my new project.
```
Launching lib/main.dart on OPPO R11s in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Finished with error: Invalid argument(s): Invalid type for "path": null
```

**Comment by wasibpkr** [comment]
**Oops; flutter has exited unexpectedly.**


_// this is my log file :  flutter_01.log;_
----------------------------------
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d ONEPLUS

## exception

ArgumentError: Invalid argument(s): Invalid type for "path": null

```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:161:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:25:49)
#2      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:429:8)
<asynchronous suspension>
#3      buildGradleProject (package:flutter_tools/src/android/gradle.dart:308:14)
<asynchronous suspension>
#4      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:379:13)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:274:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:378:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:526:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.1.4-pre.9, on Mac OS X 10.14.1 18B75, locale en-GB)
    [32m•[39m Flutter version 1.1.4-pre.9 at /Users/wasibe/development/tools/flutter
    [32m•[39m Framework revision 3d8aec2b99 (4 hours ago), 2018-12-19 20:09:07 -0800
    [32m•[39m Engine revision 5ec8ef8509
    [32m•[39m Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/wasibe/Library/Android/sdk
    [32m•[39m Android NDK at /Users/wasibe/Library/Android/sdk/ndk-bundle
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.1.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.30.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.21.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m ONEPLUS A6000             • 9f5d89ae      • android-arm64 • Android 9 (API 28)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

[32m•[39m No issues found!
```

_// flutter doctor no issues_

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.4-pre.9, on Mac OS X 10.14.1 18B75, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by wasibpkr** [comment]
I think this problem came after new update!
bcoz, I just updated my flutter now,

**Comment by zoechi** [comment]
Should be easy enough to check by switching to `dev` channel.

**Comment by zmtzawqlp** [comment]
you are not alone... 
I update flutter to lastest in master branch, then Flutter module project can't run .

Launching lib\main.dart on MI 6 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\host\outputs\apk\debug\app-debug.apk.
Finished with error: Invalid argument(s): Invalid type for "path": null

**Comment by Hard3333** [comment]
Same error!

**Comment by phoebewow** [comment]
Switching to dev channel does work

**Comment by zmtzawqlp** [comment]
dev branch is ok?

**Comment by zoechi** [comment]
Tentatively added TODAY

**Comment by wasibpkr** [comment]
yeah its worked when I switched my channel to 'dev'
to do that just run the command : flutter channel dev

**Comment by dnfield** [comment]
I haven't been able to reproduce this locally, but I suspect https://github.com/flutter/flutter/pull/25595 fixes it - can you try again after updating to latest master?

**Comment by dnfield** [comment]
I take it back, I did repro this locally (just had to make a new project).  Upgrading to latest master fixed it for me.

There's one more tweak we need, which will land shortly.

**Comment by sbaranov** [comment]
Excellent, https://github.com/flutter/flutter/pull/25595 and https://github.com/flutter/flutter/pull/25631 should fix the problem reported by wasibpkr@ above. Still, the original problem reported by iBotasky@ at the very top seems something different?

**Comment by dnfield** [comment]
Hmm. The stack is different but the final error looks similar..  @iBotasky Can you check whether #25631 fixes your issue?

**Comment by dnfield** [comment]
I'm going to reopen this while we wait for confirmation, but it should be fixed.

**Comment by aldobm** [comment]
Update flutter and this error FIX.

[✓] Flutter (Channel master, v1.1.4-pre.14, on Mac OS X 10.13.6 17G65, locale
    es-EC)
    • Flutter version 1.1.4-pre.14 at /Users/aldo/flutter
    • Framework revision 7a88fbc5fd (43 minutes ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aldo/Library/Android/sdk
    • Android NDK at /Users/aldo/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

**Comment by Hixie** [comment]
@iBotasky Please let us know if you still see this. We suspect it is fixed. Thanks.

**Comment by iBotasky** [comment]
@Hixie @dnfield 
I'm still watch this issue.
I upgrade the flutter on the `master` branch just now, and this issue not produce again.
This issue seems is fixed.
