### ISSUE TITLE
WidgetTester.getSemantics should deal better with force-merged semantics

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#25669]
`WidgetTester.getSemantics` [1] is not really aware of the semantics behind `MergeSemantics` [2], which force-merged individual SemanticsNodes into one. Instead of returning a SemanticsNode that contains the force-merged data, it returns individual un-merged SemanticsNodes. This makes it very hard to test the code that does the force-merging in [3].

We need to change `getSemantics` to better deal with force-merging. The individual nodes it currently returns are meaningless after force-merging. And accessing the forceMerged data in a test is .. awkward right now.

Example:

```dart
testWidgets('force-merge', (WidgetTester tester) async {
    final SemanticsTester semantics = SemanticsTester(tester);
    final Key key = GlobalKey();

    await tester.pumpWidget(MaterialApp(
        home: Card(
          elevation: 10.0,
          child: Column(
            children: <Widget>[
              const Text('abs. elevation: 10.0'),
              MergeSemantics(
                child: Semantics(
                  explicitChildNodes: true, // just to be sure that it's going to be an explicit merge
                  child: Column(
                    children: const <Widget>[
                      Card(
                        elevation: 15.0,
                        child: Text('abs. elevation 25.0'),
                      ),
                      Card(
                        elevation: 5.0,
                        child: Text('abs. elevation 15.0'),
                      )
                    ],
                  ),
                ),
              ),
            ],
          )
        )
    ));


    final SemanticsNode node = tester.getSemantics(find.text('abs. elevation 25.0'));
    // The following line fails because we're getting back the unmerged node...
    expect(node.label, 'abs. elevation 25.0\nabs. elevation 15.0');

   // ... instead we have to do the following awkward workaround to get the merged data:
    SemanticsData mergedChildData;
    elevation10.visitChildren((SemanticsNode child) {
      expect(mergedChildData, isNull);
      mergedChildData = child.getSemanticsData();
      return true;
    });

    expect(mergedChildData.label, 'abs. elevation 25.0\nabs. elevation 15.0');

    semantics.dispose();
  });
```

[1] https://master-docs.flutter.io/flutter/flutter_test/WidgetTester/getSemantics.html
[2] https://master-docs.flutter.io/flutter/widgets/MergeSemantics-class.html
[3] https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/semantics/semantics.dart#L1652-L1708

**Comment by goderbauer** [comment]
Some random thoughts:
* the merged "SemanticsNode" does not exist as a proper `SemanticsNode` in memory. We only generate the merged `SemanticsData`.
* maybe `getSemantics` should return a `SemanticsData` object instead?
* but then some data (e.g. child-parent relationship) would be unavailable in tests.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.21.0-6.0.pre.41`.
<details>
 <summary>Logs</summary>

 ```
00:02 +0: force-merge
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'abs. elevation 25.0\n'
            'abs. elevation 15.0'
  Actual: ''
   Which: is different. Both strings start the same, but the actual value is missing the following
trailing characters: abs. eleva ...

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Users/Isa/Google%20Drive/Nevercode/triage/test/widget_test.dart:44:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///C:/Users/Isa/Google%20Drive/Nevercode/triage/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:145:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:768:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:748:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1157:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1154:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:229:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:226:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:381:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:368:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:413:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:367:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:366:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#116    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#135    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#144    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#145    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Users/Isa/Google%20Drive/Nevercode/triage/test/widget_test.dart line 44
The test description was:
  force-merge
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: force-merge [E]
  Test failed. See exception logs above.
  The test description was: force-merge

00:02 +0 -1: Some tests failed.
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.41, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.41 at C:\Development\flutter_master
    • Framework revision 39fa00201d (5 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Reproduces as of latest `master, 3.4.0-18.0.pre`, The test currently fails
Here's a sample test from the SDK (with a workaround)

https://github.com/flutter/flutter/blob/a9858ec52495ecd45adc7bdda30c709d877e1416/packages/flutter/test/semantics/semantics_elevation_test.dart#L250-L304

<details>
<summary>logs</summary>

```console
Connecting to VM Service at http://127.0.0.1:61612/Cgez7v4ukew=/ws
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: 'abs. elevation 25.0\n'
            'abs. elevation 15.0'
  Actual: ''
   Which: is different. Both strings start the same, but the actual value is missing the following
trailing characters: abs. eleva ...

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/mahesh/Desktop/flutter_issue/test/widget_test.dart:50:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/mahesh/Desktop/flutter_issue/test/widget_test.dart line 50
The test description was:
  force-merge
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: force-merge

✖ force-merge
Exited (1)

```
</details> 

<details>
<summary>widget_test.dart</summary>

```dart
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility in the flutter_test package. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter_test/flutter_test.dart';


void main() {
testWidgets('force-merge', (WidgetTester tester) async {
    // final SemanticsTester semantics = SemanticsTester(tester);

    final Key key = GlobalKey();

    await tester.pumpWidget(MaterialApp(
        home: Card(
          elevation: 10.0,
          child: Column(
            children: <Widget>[
              const Text('abs. elevation: 10.0'),
              MergeSemantics(
                child: Semantics(
                  explicitChildNodes: true, // just to be sure that it's going to be an explicit merge
                  child: Column(
                    children: const <Widget>[
                      Card(
                        elevation: 15.0,
                        child: Text('abs. elevation 25.0'),
                      ),
                      Card(
                        elevation: 5.0,
                        child: Text('abs. elevation 15.0'),
                      )
                    ],
                  ),
                ),
              ),
            ],
          )
        )
    ));


    final SemanticsNode elevation10 = tester.getSemantics(find.text('abs. elevation 25.0'));
    // The following line fails because we're getting back the unmerged node...
    expect(elevation10.label, 'abs. elevation 25.0\nabs. elevation 15.0');

   // ... instead we have to do the following awkward workaround to get the merged data:
    SemanticsData? mergedChildData;
    elevation10.visitChildren((SemanticsNode child) {
      expect(mergedChildData, isNull);
      mergedChildData = child.getSemanticsData();
      return true;
    });

    expect(mergedChildData!.label, 'abs. elevation 25.0\nabs. elevation 15.0');

    // semantics.dispose();
  });
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.4.0-18.0.pre, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.4.0-18.0.pre on channel master at
      /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 069f504297 (3 months ago), 2022-08-30 18:20:09 -0700
    • Engine revision 0ef08a8525
    • Dart version 2.19.0 (build 2.19.0-152.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.8 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS
      12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
