### ISSUE TITLE
firebase local label detection

### ISSUE THREAD

**Issue by Pizza1** [flutter/flutter#25695]
Hi,

I'm trying to use firebase's local image detection but it seems like it's running out of memory (it's requesting 64MB and there's ~600MB free on the phone). Is there a way to fix this? (I've tried setting android:largeHeap="true")

This is the code I'm running:

```dart
var image = await ImagePicker.pickImage(source: ImageSource.camera);
   final FirebaseVisionImage visionImage = FirebaseVisionImage.fromFile(image);
   final LabelDetector labelDetector = FirebaseVision.instance.labelDetector();
   final List<Label> labels = await labelDetector.detectInImage(visionImage);
```

And this is the log:
```
Reloaded 1 of 524 libraries in 1,652ms.
D/ViewRootImpl@b7b0e5[MainActivity](28002): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -838772736}
V/InputMethodManager(28002): Starting input: tba=android.view.inputmethod.EditorInfo@b925e0 nm : com.example.myapp ic=null
I/InputMethodManager(28002): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(28002): Input channel constructed: fd=88
V/InputMethodManager(28002): Starting input: tba=android.view.inputmethod.EditorInfo@f2c05b nm : com.example.myapp ic=null
D/ViewRootImpl@b7b0e5[MainActivity](28002): ViewPostImeInputStage processPointer 0
E/BoostFramework(28002): BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
V/BoostFramework(28002): BoostFramework() : mPerf = null
D/ViewRootImpl@b7b0e5[MainActivity](28002): ViewPostImeInputStage processPointer 1
D/ViewRootImpl@b7b0e5[MainActivity](28002): MSG_WINDOW_FOCUS_CHANGED 0
D/SurfaceView(28002): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={Surface(name=null)/@0xa87666b isValid=false 0}
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.destroy()#1
D/ViewRootImpl@b7b0e5[MainActivity](28002): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/InputTransport(28002): Input channel destroyed: fd=88
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.destroy()#1
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.destroy()#1
D/ViewRootImpl@b7b0e5[MainActivity](28002): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
D/SurfaceView(28002): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x7 surface={Surface(name=null)/@0xa87666b isValid=true -838772736}
D/mali_winsys(28002): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
D/ViewRootImpl@b7b0e5[MainActivity](28002): Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x7 surface={isValid=true -867090432} surfaceGenerationChanged=true
I/OpenGLRenderer(28002): Initialized EGL, version 1.4
D/OpenGLRenderer(28002): Swap behavior 1
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.initialize() mSurface={isValid=true -867090432} hwInitialized=true
D/mali_winsys(28002): EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
D/ViewRootImpl@b7b0e5[MainActivity](28002): MSG_WINDOW_FOCUS_CHANGED 1
D/ViewRootImpl@b7b0e5[MainActivity](28002): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -867090432}
V/InputMethodManager(28002): Starting input: tba=android.view.inputmethod.EditorInfo@586dfd3 nm : com.example.myapp ic=null
I/InputMethodManager(28002): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(28002): Input channel constructed: fd=88
I/DynamiteModule(28002): Considering local module com.google.android.gms.vision.dynamite.imagelabel:180000 and remote module com.google.android.gms.vision.dynamite.imagelabel:0
I/DynamiteModule(28002): Selected local version of com.google.android.gms.vision.dynamite.imagelabel
W/native  (28002): commandlineflags.cc:1511 Ignoring RegisterValidateFunction() for flag pointer 0xc8f293c0: no flag found at that address
E/art     (28002): The String#value field is not present on Android versions >= 6.0
W/native  (28002): classifier_client.cc:308 Not enough score calibration parameters for classifier head index 0: got 430, expected 447
I/art     (28002): Waiting for a blocking GC Alloc
I/art     (28002): WaitForGcToComplete blocked for 6.247ms for cause Alloc
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc partial concurrent mark sweep GC freed 8839(432KB) AllocSpace objects, 3(12MB) LOS objects, 17% free, 72MB/88MB, paused 476us total 26.597ms
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc sticky concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 383us total 5.843ms
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc concurrent mark sweep GC freed 18(528B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 385us total 36.846ms
I/art     (28002): Forcing collection of SoftReferences for 60MB allocation
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 372us total 35.279ms
W/art     (28002): Throwing OutOfMemoryError "Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM"
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc sticky concurrent mark sweep GC freed 4(488B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 347us total 5.535ms
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 407us total 17.498ms
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 371us total 35.897ms
I/art     (28002): Forcing collection of SoftReferences for 60MB allocation
I/art     (28002): Starting a blocking GC Alloc
I/art     (28002): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 17% free, 72MB/88MB, paused 373us total 35.105ms
W/art     (28002): Throwing OutOfMemoryError "Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM"
E/flutter (28002): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.OutOfMemoryError: Failed to allocate a 63701004 byte allocation with 16777216 free bytes and 55MB until OOM
E/flutter (28002): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/flutter (28002): 	at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
E/flutter (28002): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:613)
E/flutter (28002): 	at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:636)
E/flutter (28002): 	at com.google.firebase.ml.vision.common.FirebaseVisionImage.getBitmapForDebugging(Unknown Source)
E/flutter (28002): 	at com.google.firebase.ml.vision.label.FirebaseVisionLabelDetector.detectInImage(Unknown Source)
E/flutter (28002): 	at io.flutter.plugins.firebasemlvision.LabelDetector.handleDetection(LabelDetector.java:49)
E/flutter (28002): 	at io.flutter.plugins.firebasemlvision.FirebaseMlVisionPlugin.onMethodCall(FirebaseMlVisionPlugin.java:53)
E/flutter (28002): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/flutter (28002): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/flutter (28002): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (28002): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (28002): 	at android.os.Looper.loop(Looper.java:136)
E/flutter (28002): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/flutter (28002): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28002): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1510)
E/flutter (28002): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1400)
E/flutter (28002):
F/flutter (28002): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
F/libc    (28002): Fatal signal 6 (SIGABRT), code -6 in tid 28002 (myapp)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/s5neoltevl/s5neoltecan:7.0/NRD90M/G903WVLU1CQI1:user/release-keys'
Revision: '12'
ABI: 'arm'
pid: 28002, tid: 28002, name: myapp  >>> com.example.myapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
'
r0 00000000  r1 00006d62  r2 00000006  r3 00000008
r4 f07b158c  r5 00000006  r6 f07b1534  r7 0000010c
r8 00000006  r9 00000000  sl deadd3d0  fp ca1ec030
ip 0000000b  sp fffd03b8  lr eeb624c7  pc eeb64d30  cpsr 600f0010
backtrace:
#00 pc 0004ad30  /system/lib/libc.so (tgkill+12)
#01 pc 000484c3  /system/lib/libc.so (pthread_kill+34)
#02 pc 0001dd99  /system/lib/libc.so (raise+10)
#03 pc 00019521  /system/lib/libc.so (__libc_android_abort+34)
#04 pc 00017160  /system/lib/libc.so (abort+4)
#05 pc 0053ea03  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#06 pc 00535a2d  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#07 pc 00534eef  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#08 pc 005657fd  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#09 pc 0053fe6d  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#10 pc 0054142d  /data/app/com.example.myapp-2/lib/arm/libflutter.so (offset 0x4e5000)
#11 pc 00011e77  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+614)
#12 pc 00011b83  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
#13 pc 000973ad  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
#14 pc 02614a65  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (android.os.MessageQueue.nativePollOnce+96)
#15 pc 02615f81  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (android.os.MessageQueue.next+188)
#16 pc 02611669  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (android.os.Looper.loop+364)
#17 pc 01f92003  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (android.app.ActivityThread.main+598)
#18 pc 000a9341  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
#19 pc 004075d1  /system/lib/libart.so (art_quick_invoke_static_stub+228)
#20 pc 000b065f  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
#21 pc 00316973  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+58)
#22 pc 00317ce7  /system/lib/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j+766)
#23 pc 002bea3d  /system/lib/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+40)
#24 pc 00606159  /system/framework/arm/boot.oat (offset 0x56f000) (java.lang.reflect.Method.invoke+116)
#25 pc 02bb8dd9  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+100)
#26 pc 02bba439  /system/framework/arm/boot-framework.oat (offset 0x1efb000) (com.android.internal.os.ZygoteInit.main+1684)
#27 pc 000a9341  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
#28 pc 004075d1  /system/lib/libart.so (art_quick_invoke_static_stub+228)
#29 pc 000b065f  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
#30 pc 00316973  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+58)
#31 pc 00316783  /system/lib/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+266)
#32 pc 00278bf7  /system/lib/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+426)
#33 pc 0006a5e5  /system/lib/libandroid_runtime.so
#34 pc 0006c0d7  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+510)
#35 pc 00002ea7  /system/bin/app_process32
#36 pc 00016d79  /system/lib/libc.so (__libc_init+48)
#37 pc 0000299c  /system/bin/app_process32
Lost connection to device.
Exited (sigterm)
```

**Comment by kroikie** [comment]
@Pizza1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/532. Any further collaboration will be done there.
