### ISSUE TITLE
[Android Device] suddenly app unable to launch - Logcat detailed.

### ISSUE THREAD

**Issue by m4mum** [flutter/flutter#25693]
Editor : Android Studio
Simple basic app was working fine. After multiple run it stopped running suddenly
Tried: flutter clean
logcat below (Only Error logs)

---
2018-12-22 18:05:00.135 3362-3362/? E/RegisteredServicesCache: Next Tag=services
2018-12-22 18:05:00.136 3362-3362/? E/RegisteredServicesCache: 1invalidateCache:WriteServiceStateToFile
2018-12-22 18:05:00.136 3362-3362/? E/RegisteredServicesCache:  Writing service state Data Always
2018-12-22 18:05:00.295 26062-3081/? E/memtrack: Couldn't load memtrack module
2018-12-22 18:05:00.413 3074-3074/? E/app_process: No implementation found for boolean android.os.SystemProperties.native_get_boolean(java.lang.String, boolean) (tried Java_android_os_SystemProperties_native_1get_1boolean and Java_android_os_SystemProperties_native_1get_1boolean__Ljava_lang_String_2Z)
2018-12-22 18:05:00.413 3074-3074/? E/app_process: No implementation found for boolean android.os.SystemProperties.native_get_boolean(java.lang.String, boolean) (tried Java_android_os_SystemProperties_native_1get_1boolean and Java_android_os_SystemProperties_native_1get_1boolean__Ljava_lang_String_2Z)
2018-12-22 18:05:03.089 1312-1422/? E/PackageManager: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
2018-12-22 18:05:03.090 1312-1422/? E/PackageManager.DexOptimizer: Well this is awkward; package io.flutter.app.FlutterApplication had UID -1
    java.lang.Throwable
        at com.android.server.pm.PackageDexOptimizer.performDexOptLI(PackageDexOptimizer.java:150)
        at com.android.server.pm.PackageDexOptimizer.performDexOpt(PackageDexOptimizer.java:126)
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:19987)
        at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:19547)
        at com.android.server.pm.PackageManagerService.-wrap35(Unknown Source:0)
        at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:16810)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
2018-12-22 18:05:04.676 953-29891/? E/installd: Failed to delete /data/app/vmdl1936110231.tmp: No such file or directory
2018-12-22 18:05:04.782 1312-14568/? E/OnePlusAppBootManager: # startActivityLocked # aInfo = null
-----

**Comment by zoechi** [comment]
Might be an issue with your emulator.
Try to create a new one and try again.

https://stackoverflow.com/questions/22629568/couldnt-load-memtrack-module-logcat-error
