### ISSUE TITLE
App Build Failed

### ISSUE THREAD

**Issue by mehedisunny** [flutter/flutter#25691]
## exception

ProcessException: ProcessException: No such file or directory
  Command: /home/mehedi/Projects/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --causal_async_stacks --packages=.packages --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/home/mehedi/Projects/bhold/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/home/mehedi/Projects/bhold/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/home/mehedi/Projects/bhold/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/home/mehedi/Projects/bhold/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/mehedi/Projects/bhold/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:133:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:55)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:139:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:526:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:460:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:451:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#36     main (file:///home/mehedi/Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel dev, v1.1.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.4 at /home/mehedi/Projects/flutter
    • Framework revision 7a88fbc5fd (2 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/mehedi/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/69/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.1)
    • Android Studio at /snap/android-studio/53/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /snap/android-studio/69/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • SM G935F • ce11160bec67c03105 • android-arm64 • Android 6.0.1 (API 23)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Looks exactly like #23050
