### ISSUE TITLE
Flutter inspector: Toggle select Widget Mode crashes

### ISSUE THREAD

**Issue by rumaan** [flutter/flutter#25707]
## Steps to Reproduce

On tapping the 'Toggle Select Widget Mode button' in the Flutter Inspector (IntelliJ IDEA) I get this error:

![ezgif-1-13c0d113a790](https://user-images.githubusercontent.com/18492868/50383341-b2dbdf00-06d7-11e9-89e4-18c36ccffc80.gif)

### IntelliJ console output
```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.                                            8.5s
Syncing files to device iPhone X...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Title(color: MaterialColor(primary value:
flutter: Color(0xff2196f3))):
flutter: 'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 2158 pos 12:
flutter: 'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart:2158:12)
flutter: #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
flutter: #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #43     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #51     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #59     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #71     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
flutter: #72     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #88     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #90     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #98     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #108    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #118    StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #124    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #128    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #133    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #134    _invoke (dart:ui/hooks.dart:154:13)
flutter: #135    _drawFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

 ### flutter doctor -v :
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-IN)
    • Flutter version 1.0.0 at /Users/rumaankhalander/Flutter/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rumaankhalander/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone X • 7011A89B-7A8A-473C-BEAF-870C623A6E53 • ios • iOS 11.3
      (simulator)

! Doctor found issues in 1 category.

```

### Attached Dart File (in zip):
[fileio.dart.zip](https://github.com/flutter/flutter/files/2705948/fileio.dart.zip)

**Comment by zoechi** [comment]
I can reproduce with the reduced code below when I nest `MaterialApp`.

This is again a great example why a reproduction should be complete and runnable including `main() {}`

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: FileioPage(),
    );
  }
}

class FileioPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Container(),
    ));
  }
}
```
```
[✓] Flutter (Channel master, v1.1.4-pre.9, on Mac OS X 10.14.1 18B75, locale en-AT)
    • Flutter version 1.1.4-pre.9 at /Users/zoechi/flutter/flutter
    • Framework revision 3d8aec2b99 (3 days ago), 2018-12-19 20:09:07 -0800
    • Engine revision 5ec8ef8509
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by rumaan** [comment]
@zoechi Is this a **flutter-intellij** issue?

**Comment by zoechi** [comment]
Why would you want to nest `MaterialApp`?
I'd say just don't do it.
Perhaps there could be a better error message.

**Comment by rumaan** [comment]
@zoechi Ok thank you! I just removed the inner `MaterialApp` and it works! 😄

**Comment by zoechi** [comment]
I leave this open for consideration if a better error message is possible.

**Comment by jacob314** [comment]
Bumping up the priority. This assert can safely be ignored and we need to start ignoring it instead of crashing users.

**Comment by TahaTesser** [comment]
Hi @zoechi 
Not able to reproduce this issue on latest Android Studio and `dev` channel

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (5 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.129
• No issues found!
```

</details>

if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
