### ISSUE TITLE
couldn't find "libflutter.so" with firebase_ml_vision

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#25722]
## Steps to Reproduce

1. Create default flutter application.
2. Add firebase_ml_vision (usually you would need more configuration, but its not needed here.)
3. Build and install app-release manually (debugging works for some reason)
3. Crash.

## Logs

```
12-23 18:14:29.040  8412  8412 D AndroidRuntime: Shutting down VM
12-23 18:14:29.041  8412  8412 E AndroidRuntime: FATAL EXCEPTION: main
12-23 18:14:29.041  8412  8412 E AndroidRuntime: Process: com.example.testing, PID: 8412
12-23 18:14:29.041  8412  8412 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/lib/x86, /data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1669)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MichaelPriebe** [comment]
The solution to use
```
        ndk {
            abiFilters 'armeabi-v7a'
        }
```
just gives me an error when installing the application

```
adb: failed to install .\app-release.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by gerryhigh** [comment]
Seems related to this issue: https://github.com/flutter/flutter/issues/18494

**Comment by MichaelPriebe** [comment]
Any news on this though? Looks like all solutions either don't work or severely degrade performance.

**Comment by hariprasadiit** [comment]
@zoechi This issue is related to flutter not building for both `32 bit` and `64 bit` archs for `Android` build. I think we can remove `t:xcode` tag

**Comment by kroikie** [comment]
@MichaelPriebe

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/530. Any further collaboration will be done there.
