### ISSUE TITLE
starflut version incompatible with Dart2.1   Error: The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.  Because flutt_cam depends on starflut any which requires SDK version >=1.19.0 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by tash149** [flutter/flutter#25729]
## Steps to Reproduce

1. To pubspec.yaml file add 

dependencies:
  image_picker: ^0.4.10
  path_provider: ^0.4.1
  starflut: ^0.5.2

## Logs

```
[  +13 ms] executing: [/home/tash149/.apps/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[ +164 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/dev
[   +1 ms] executing: [/home/tash149/.apps/flutter/] git rev-parse --abbrev-ref
HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[        ] executing: [/home/tash149/.apps/flutter/] git ls-remote --get-url
origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/tash149/.apps/flutter/] git log -n 1
--pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/home/tash149/.apps/flutter/] git log -n 1
--pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] executing: [/home/tash149/.apps/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.0.0-0-g5391447fa
[  +58 ms] "flutter run" took 12ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:484:9)
<asynchronous suspension>
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:246:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main
(file:///home/tash149/.apps/flutter/packages/flutter_tools/bin/flutter_tools.dar
t:8:3)
#35     _startIsolate.<anonymous closure>
(dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:171:12)


```

```
Running "flutter packages get" in flutt_cam...                   
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because flutt_cam depends on starflut >=0.5.1 which requires SDK version >=1.19.0 <2.0.0, version solving failed.
 
pub get failed (1)

```

```
[✓] Flutter (Channel dev, v1.0.0, on Linux, locale en_IN)
    • Flutter version 1.0.0 at /home/tash149/.apps/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/tash149/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[!] VS Code (version 1.30.0)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Redmi Note 4 • 20db0cbe0104 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.


```

**Comment by zoechi** [comment]
You need to raise the issue with starflut.
starflut depends on an old Flutter version (based on Dart 1.x)
