### ISSUE TITLE
[image_picker] Flutter android app will be crashed when selecting HEIC image

### ISSUE THREAD

**Issue by manhnhhdvn** [flutter/flutter#25741]
## Steps to Reproduce

1. Take a [HEIC](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) image from an iPhone (iOS 11 or later).
2. Upload it to Google Drive.
3. Select it from flutter app run in Android device. The app will be crashed (select directly from Google Drive, or download and select it from the local library has the same result).

#### Update:
Posted error log was output when make a call to ```pickImage``` function with ```maxWidth``` and ```maxHeight``` values like this:

```dart
ImagePicker.pickImage(
  source: ImageSource.gallery,
  maxWidth: 360.0,
  maxHeight: 360.0,
  );
```

If I make a call to ```pickImage``` function with no ```maxWidth``` and ```maxHeight```, it will return the correct result.
(In this case, my app still crashes, but because of ```lookupMimeType``` function in ```mime_type``` library returning null, unrelated to this issue)

## Logs

```
D/skia    (25346): --- SkAndroidCodec::NewFromStream returned null
D/AndroidRuntime(25346): Shutting down VM
E/AndroidRuntime(25346): FATAL EXCEPTION: main
E/AndroidRuntime(25346): Process: jp.myapp.dev, PID: 25346
E/AndroidRuntime(25346): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/107 flg=0x1 }} to activity {jp.myapp.dev/jp.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(25346): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4324)
E/AndroidRuntime(25346): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
E/AndroidRuntime(25346): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(25346): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
E/AndroidRuntime(25346): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(25346): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(25346): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime(25346): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25346): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(25346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime(25346): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(25346): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:48)
E/AndroidRuntime(25346): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
E/AndroidRuntime(25346): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:454)
E/AndroidRuntime(25346): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:396)
E/AndroidRuntime(25346): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(25346): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(25346): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(25346): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(25346): 	at android.app.Activity.dispatchActivityResult(Activity.java:7235)
E/AndroidRuntime(25346): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
E/AndroidRuntime(25346): 	... 9 more
```

## flutter doctor -v

```
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.14.1 18B75, locale ja-JP)
    • Flutter version 1.1.4 at /Users/ManhNH/Projects/Flutter/flutter
    • Framework revision 7a88fbc5fd (4 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ManhNH/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone XR                 • ABF2313D-6E8F-4915-8A48-4FFCCF874C4C • ios
      • iOS 12.1 (simulator)

• No issues found!
```

**Comment by GaryQian** [comment]
Related: https://github.com/flutter/flutter/issues/20522

However, the crashing does not seem to be correct...

**Comment by manhnhhdvn** [comment]
@GaryQian I updated my post

**Comment by valconetti** [comment]
Hey @manhnhhdvn,

The Exception of this issue is `Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth() on a null object reference`. This can happen on Android 8 and lower. `decodeFile` returns `null` because HEIC files have only been supported since Android 9.
[This PR from November 2019 ](https://github.com/flutter/plugins/pull/2293) checks if the bitmap is null and directly returns null if that is the case. So the exception from this issue will not occur anymore.

There are still 2 issues with HEIC images on Android.
1. On Android 8 and lower they are just not supported, if you pick an HEIC image the plugin will return null. I'll add that to the documentation.
2. On Android 9 and higher HEIC images are supported, but can’t be decoded by Flutter and thus can’t be shown. The issue to track progress on that topic is: https://github.com/flutter/flutter/issues/20522.

When picking HEIC images on Android 9 and higher, while changing `maxWidth` or `maxHeight`, it should work. This is because Android changed the HEIC image to PNG or JPG while resizing it, which Flutter is able to decode.

**Comment by mvanbeusekom** [comment]
Closing this issue as per explanation of @valconetti. Further progress of handling HEIC images on Android 9 is tracked in issue #20522.
