### ISSUE TITLE
CompileTimeError: No named parameter with the name 'fontFamilyFallback' after upgrade to master, v1.1.5-pre.24

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#25756]
## Steps to Reproduce
Use a `TextStyle` I assume? I don't know why it's crashing, so it's hard to find the steps to reproduce. I'll provide them when I have time and stumble across it again, but right now I have to just switch to a different branch.

## Logs

```
I/flutter ( 7343): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7343): The following _CompileTimeError was thrown during performLayout():
I/flutter ( 7343): 'package:flutter/src/painting/text_style.dart': error: line 728 pos 7:
I/flutter ( 7343): file:///Users/thinkdigital/development/flutter/packages/flutter/lib/src/painting/text_style.dart:728:7:
I/flutter ( 7343): Error: No named parameter with the name 'fontFamilyFallback'.
I/flutter ( 7343):       fontFamilyFallback: fontFamilyFallback,
I/flutter ( 7343):       ^^^^^^^^^^^^^^^^^^
I/flutter ( 7343):       fontFamilyFallback: fontFamilyFallback,
I/flutter ( 7343):       ^
I/flutter ( 7343): 
I/flutter ( 7343): When the exception was thrown, this was the stack:
I/flutter ( 7343): #0      TextSpan.build (package:flutter/src/painting/text_span.dart:170:31)
I/flutter ( 7343): #1      TextPainter.layout (package:flutter/src/painting/text_painter.dart:353:13)
I/flutter ( 7343): #2      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:199:18)
I/flutter ( 7343): #3      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:203:5)
I/flutter ( 7343): #4      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart:269:5)
I/flutter ( 7343): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7343): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
```

```
```

## Flutter Doctor -v

```
[✓] Flutter (Channel master, v1.1.5-pre.24, on Mac OS X 10.14.2 18C54, locale
    en-US)
    • Flutter version 1.1.5-pre.24 at /Users/thinkdigital/development/flutter
    • Framework revision 4d2d800d9e (19 hours ago), 2018-12-24 18:47:40 -0500
    • Engine revision d8c5ec0e11
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/thinkdigital/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5124
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0
      (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
The line 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_style.dart#L719-L728
refers to `ui.TextStyle` but https://github.com/flutter/engine/blob/215ca15600887ffeffef2df3f216e0189159150e/lib/ui/text.dart#L377-L395 doesn't have that parameter yet.

**Comment by ThinkDigitalRepair** [comment]
*anymore?

**Comment by DanTup** [comment]
> but https://github.com/flutter/engine/blob/215ca15600887ffeffef2df3f216e0189159150e/lib/ui/text.dart#L377-L395 doesn't have that parameter yet.

When I click that link, I do see `fontFamilyFallback` right in the middle. It also seems to exist in the version of the engine in the output above:

https://github.com/flutter/engine/blob/d8c5ec0e11/lib/ui/text.dart#L386

@ThinkDigitalRepair could you try uninstalling the app from your device, running `flutter clean` and then testing again?

**Comment by ThinkDigitalRepair** [comment]
That's an interesting troubleshooting option. I can try that today. I
figured it wasn't part of the code base to start with In the new version.
It didn't show up in my project files when following the link to the
library.

**Comment by zoechi** [comment]
There are such inconsistencies sometimes on master channel.
I'd expect it to be solved by now if you ensure you have the latest update. 
Ensure your Flutter install is clean https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted
If not switch to `dev` channel and try `master` again after a few days if you prefer `master`.

**Comment by GaryQian** [comment]
An explanation of what is happening here:

There is a known bug where the version of dart::ui cached in the build/ directory is not updated. The dart::ui library is precompiled as part of the engine build, and we currently do not update it properly if the engine rolls any new changes in dart::ui.

When you did a `flutter clean`, the build directory was emptied and the latest version of dart::ui was downloaded.
