### ISSUE TITLE
AutomaticKeepAliveClientMixin will reinit wile navigator to a new page and back

### ISSUE THREAD

**Issue by iBotasky** [flutter/flutter#25806]
## Steps to Reproduce

1. I have a HomePage with a PageView with 4 sub pages, and they all implement `AutomaticKeepAliveClientMixin`. And they only init just one time while I select the same tab many times.
![image](https://user-images.githubusercontent.com/13627665/50471427-7d910300-09ef-11e9-91de-2c50a10c9d00.png)

![image](https://user-images.githubusercontent.com/13627665/50471190-82a18280-09ee-11e9-83e1-c9e2e018592f.png)

2. And there in Movie tab, I tap the list item navigator to movie detail page, and go back to HomePage,
while I select the other tabs exclude Movie tab, the selection page will init again.

![image](https://user-images.githubusercontent.com/13627665/50471291-ed52be00-09ee-11e9-9c31-9e2c3049689d.png)

3. Is that possible cause by the Navigator, there is Navigator code:
```dart
  static toMovieDetail(
      BuildContext context, String title, String id, String imageUrl) {
    Navigator.push(
        context,
        MaterialPageRoute(
            builder: (context) => MovieDetail(
                  title: title,
                  id: id,
                  imageUrl: imageUrl,
                )));
  }
```

## Logs

```
flutter_cybird git:(master) flutter run --verbose
[  +23 ms] executing: [/Users/juhu/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/juhu/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/juhu/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/juhu/flutter/] git log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] c24923c79a3dcdeccc8235242fe8dad2d2883ad9
[        ] executing: [/Users/juhu/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 hours ago
[        ] executing: [/Users/juhu/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +264 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.1.4-27-gc24923c79
[ +390 ms] executing: /Users/juhu/Library/Android/sdk/platform-tools/adb devices -l
[  +22 ms] Exit code 0 from: /Users/juhu/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           41a4dafe               device usb:336592896X product:R11s model:OPPO_R11s device:R11s transport_id:1
[   +7 ms] executing: idevice_id -h
[  +32 ms] /usr/bin/xcrun simctl list --json devices
[ +210 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] /Users/juhu/Library/Android/sdk/platform-tools/adb -s 41a4dafe shell getprop
[ +125 ms] ro.hardware = qcom
[   +4 ms] OPPO R11s • 41a4dafe                             • android-arm64 • Android 7.1.1 (API 25)
[        ] iPhone XR • 13DC0DBC-478E-4FDC-B7FB-AF0F1E33467D • ios           • iOS 12.1 (simulator)
[   +9 ms] "flutter run" took 755ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:222:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:503:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:459:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:450:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/juhu/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
 flutter_cybird git:(master) flutter analyze
Analyzing flutter_cybird...                                      

   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:3:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:4:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:6:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:7:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:10:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:11:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:12:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:13:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:16:5 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/constant/Constant.dart:20:4 • non_constant_identifier_names
   info • Unused import: 'package:flutter_cybird/ui/movie/MovieDetail.dart' • lib/main.dart:5:8 • unused_import
   info • The value of the field '_currentIndex' isn't used • lib/ui/movie/Movie.dart:13:7 • unused_field
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:9:8 • unused_import
   info • Unused import: 'package:flutter_cybird/main.dart' • test/widget_test.dart:11:8 • unused_import

15 issues found. (ran in 4.8s)

```

```
flutter_cybird git:(master) flutter doctor -v
[✓] Flutter (Channel master, v1.1.5-pre.27, on Mac OS X 10.14.2 18C54, locale en-CN)
    • Flutter version 1.1.5-pre.27 at /Users/juhu/flutter
    • Framework revision c24923c79a (9 hours ago), 2018-12-26 17:58:40 -0500
    • Engine revision 9daf5c8d21
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/juhu/Library/Android/sdk
    • Android NDK at /Users/juhu/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • OPPO R11s • 41a4dafe                             • android-arm64 • Android 7.1.1 (API 25)
    • iPhone XR • 13DC0DBC-478E-4FDC-B7FB-AF0F1E33467D • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
I'm not sure what the problem and the expected behavior is

> And they only init just one time while I select the same tab many times.

I think that's working as intended.

**Comment by iBotasky** [comment]
@zoechi Yes,I mean it's working fine there.

**Comment by zoechi** [comment]
Please elaborate. I still have no idea what the issue is about.

> what the problem and the expected behavior is

**Comment by zoechi** [comment]
Is this a duplicate of #25807?

**Comment by iBotasky** [comment]
The widget implement `AutomaticKeepAliveClientMixin` will not keep alive while `Navigator.push` into a new page and back. 
My english is poor. sorry about it.

**Comment by iBotasky** [comment]
> Is this a duplicate of #25807?

No, mine is work fine at this situation.
But init again while Navigator to a new page and back.

**Comment by zoechi** [comment]
Please post the code as minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce instead of fragments that we need to put together ourselves to have a runnable example.

**Comment by iBotasky** [comment]
Here is the code:
```dart
void main() => runApp(MaterialApp(
      title: 'Fybird',
      theme: ThemeData(primaryColor: Colors.blue[800]),
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('First Page'),
          ),
          body: TabBarView(
            children: [
              TabView(),
              TabView(),
              TabView(),
            ],
          ),
        ),
      ),
    ));

class TabView extends StatefulWidget {
  @override
  _TabViewState createState() => _TabViewState();
}

class _TabViewState extends State<TabView> with AutomaticKeepAliveClientMixin {
  @override
  void initState() {
    super.initState();
    debugPrint("Tab View init");
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: Center(
          child: RaisedButton(
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (context) => SecondPage()));
            },
            child: Text("Init all TabViews and tap to New Page"),
          ),
        ));
  }

  @override
  bool get wantKeepAlive => true;
}

class SecondPage extends StatefulWidget {
  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Page"),
      ),
      body: Container(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        child: Center(
            child: Text(
                "Bac to the first page, and tap the TapView will init again, not alive.")),
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Duplicate of #25310

**Comment by mickyliu945** [comment]
> AutomaticKeepAliveClientMixin

@iBotasky  All sub page build method should  invoke super.build(context) at first;

**Comment by iBotasky** [comment]
@mickyliu945 
Thanks, I have invoke `super.build(context)` at the build method, and this issue has been solve.
I find that the document has mention that.
[Document](https://docs.flutter.io/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html)
