### ISSUE TITLE
_listenerAttached': is not true

### ISSUE THREAD

**Issue by adhikagunadarma** [flutter/flutter#25809]
## Steps to Reproduce

So i have been working on list view that implements search function on it to search any data through the list view. It has been working really well, but i have found a bug on it. The bug occurs whenever i press search, type something on it, close it, press search again and start typing again for any data on the list. Whenever i press any item/data from the list after doing so,  i see red screen error/glitch for a moment only on the app bar just before the page is transitioned into another page. And the exception shows like this : 

```
I/flutter ( 8127): Another exception was thrown: 'package:flutter/src/rendering/editabl
e.dart': Failed assertion: line 599 pos 14: '_listenerAttached': is not true.
I/flutter ( 8127): Another exception was thrown: Duplicate GlobalKey detected in widget
 tree.
```

Any way here's my code on my the app bar : 
```dart
  Widget _buildAppBar() {
    if (_search) {
      return new AppBar(
      backgroundColor: Theme.Colors.primaryColor.withOpacity(0.8),
      elevation: 5.0,
      title: TextField(
        onChanged: (value) {
          filterSearchResults(value);
        },
        autofocus: true,
        keyboardType: TextInputType.text,
        focusNode: _searchFocusNode,
        controller: _searchController,
        style: TextStyle(
            fontFamily: Theme.Font.secondaryFont,
            fontSize: _searchFontSize,
            letterSpacing: 1.5,
            fontWeight: FontWeight.w500,
            color: Colors.black),
        decoration: InputDecoration(
          suffixIcon: IconButton(
            icon: Icon(
              FontAwesomeIcons.times,
              color: Colors.black,
              size: _searchIconSize,
            ),
            onPressed: (){
              {
                setState(() {
//                  searchAnimalsData.clear();
                  _searchController.clear();
                  filteredAnimals.clear();
                  filteredAnimals.addAll(animals);
                });
              }
            },
          ),
          border: InputBorder.none,
          hintText: "Enter name here..",
          hintStyle: TextStyle(
              letterSpacing: 1.5,
              fontWeight: FontWeight.w500,
              fontFamily: Theme.Font.secondaryFont,
              fontSize: _miscFontSize),
        ),
      ),
      leading: IconButton(
        icon: new Icon(
            FontAwesomeIcons.arrowLeft,
            color: Colors.black,
            size: _searchIconSize,
          ),
        onPressed: (){
          setState(() {
            _search = false;
            searchAnimalsData.clear();
            _searchController.clear();
            filteredAnimals.clear();
            filteredAnimals.addAll(animals);
          });
        },
      ),
    );
    } else {
      return new AppBar(
      backgroundColor: Theme.Colors.primaryColor.withOpacity(0.8),
      elevation: 5.0,
      title: new Text(
        "Encyclopedia List",
        style: TextStyle(
            fontFamily: Theme.Font.secondaryFont,
            fontSize: _searchFontSize,
            letterSpacing: 1.5,
            fontWeight: FontWeight.w500,
            color: Colors.black),

      ),
      leading: IconButton(
        icon: new Icon(
          FontAwesomeIcons.search,
          color: Colors.black,
          size: _searchIconSize,
        ),
        onPressed: (){
          setState(() {
            _search = true;

          });
        },
      ),
    );
    }
  }
```

And here's for the search function : 
```dart
  void filterSearchResults(String query) {
    if(query.isNotEmpty) {
      searchAnimalsData.clear();
      animals.forEach((item) {
        if(item.name.toLowerCase().contains(query.toLowerCase())) {
          searchAnimalsData.add(item);
        }
      });
      setState(() {
        filteredAnimals.clear();
        filteredAnimals.addAll(searchAnimalsData);
      });
//      return;
    } else {
      setState(() {
//        searchAnimalsData.clear();
        _searchController.clear();
        filteredAnimals.clear();
        filteredAnimals.addAll(animals);
      });
    }
  }
```

## Logs

```
[  +10 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and
rebuild state),
           press "R".
[   +6 ms] An Observatory debugger and profiler on A1601 is available at:
http://127.0.0.1:64205/
[   +1 ms] For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
[+19367 ms] W/Firestore(10478): (0.6.6-dev) [Firestore]: The behavior for
java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
[   +1 ms] W/Firestore(10478): To hide this warning and ensure your app does not break,
you need to add the following code to your app before calling any other Cloud Firestore
methods:
[   +1 ms] W/Firestore(10478): 
[        ] W/Firestore(10478): FirebaseFirestore firestore =
FirebaseFirestore.getInstance();
[        ] W/Firestore(10478): FirebaseFirestoreSettings settings = new
FirebaseFirestoreSettings.Builder()
[        ] W/Firestore(10478):     .setTimestampsInSnapshotsEnabled(true)
[        ] W/Firestore(10478):     .build();
[        ] W/Firestore(10478): firestore.setFirestoreSettings(settings);
[        ] W/Firestore(10478): 
[        ] W/Firestore(10478): With this change, timestamps stored in Cloud Firestore
will be read back as com.google.firebase.Timestamp objects instead of as system
java.util.Date objects. So you will also need to update code expecting a java.util.Date
to instead expect a Timestamp. For example:
[   +1 ms] W/Firestore(10478): 
[        ] W/Firestore(10478): // Old:
[        ] W/Firestore(10478): java.util.Date date = snapshot.getDate("created_at");
[        ] W/Firestore(10478): // New:
[        ] W/Firestore(10478): Timestamp timestamp =
snapshot.getTimestamp("created_at");
[        ] W/Firestore(10478): java.util.Date date = timestamp.toDate();
[        ] W/Firestore(10478): 
[        ] W/Firestore(10478): Please audit all existing usages of java.util.Date when
you enable the new behavior. In a future release, the behavior will be changed to the
new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
[   +1 ms] W/linker  (10478):
/data/app/com.google.android.gms-1/lib/arm64/libconscrypt_gmscore_jni.so: unused DT
entry: type 0x6ffffffe arg 0x18e4
[   +1 ms] W/linker  (10478):
/data/app/com.google.android.gms-1/lib/arm64/libconscrypt_gmscore_jni.so: unused DT
entry: type 0x6fffffff arg 0x2
[   +2 ms] V/NativeCrypto(10478): Registering
com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
[  +64 ms] I/ProviderInstaller(10478): Installed default security provider
GmsCore_OpenSSL
[ +500 ms] I/System.out(10478): [CDS][DNS] getAllByNameImpl netId = 0
[        ] D/libc-netbsd(10478): [getaddrinfo]: mtk hostname=firestore.googleapis.com;
servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10234; ai_addrlen=0;
ai_canonname=(null); ai_flags=4; ai_family=0
[   +1 ms] D/libc-netbsd(10478): [getaddrinfo]: mtk hostname=firestore.googleapis.com;
servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10234; ai_addrlen=0;
ai_canonname=(null); ai_flags=1024; ai_family=0
[  +21 ms] D/libc-netbsd(10478): getaddrinfo: firestore.googleapis.com get result from
proxy >>
[  +15 ms] I/System.out(10478): [CDS]connect[firestore.googleapis.com/74.125.24.95:443]
tm:90
[   +2 ms] D/Posix   (10478): [Posix_connect Debug]Process
adhikagunadarma.release.catdogencyclopedia :443
[  +49 ms] D/libc-netbsd(10478): [getaddrinfo]: mtk hostname=firestore.googleapis.com;
servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10234; ai_addrlen=0;
ai_canonname=(null); ai_flags=4; ai_family=0
[+1604 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +172 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +8 ms] D/MALI    (10478): glReadPixels:1684: --
[ +203 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +6 ms] D/MALI    (10478): glReadPixels:1684: --
[ +369 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +2 ms] D/MALI    (10478): glReadPixels:1684: --
[ +244 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +2 ms] D/MALI    (10478): glReadPixels:1684: --
[ +549 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +3 ms] D/MALI    (10478): glReadPixels:1684: --
[ +151 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[ +229 ms] D/MALI    (10478): glReadPixels:1684: --
[  +15 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[  +31 ms] D/MALI    (10478): glReadPixels:1684: --
[+22578 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[  +18 ms] D/MALI    (10478): glReadPixels:1684: --
[+1503 ms] I/View    (10478): Key down dispatch to io.flutter.view.FlutterView{367b0a8
VFE..... .F...... 0,0-720,1280}, event = KeyEvent { action=ACTION_DOWN,
keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0,
eventTime=16412371, downTime=16412371, deviceId=6, source=0x101 }
[ +201 ms] I/View    (10478): Key up dispatch to io.flutter.view.FlutterView{367b0a8
VFE..... .F...... 0,0-720,1280}, event = KeyEvent { action=ACTION_UP,
keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0,
eventTime=16412516, downTime=16412371, deviceId=6, source=0x101 }
[+4869 ms] V/InputMethodManager(10478): START INPUT:
io.flutter.view.FlutterView{367b0a8 VFE..... .F...... 0,0-720,1280}
ic=io.flutter.plugin.editing.InputConnectionAdaptor@2826be1
tba=android.view.inputmethod.EditorInfo@1f6cad06 controlFlags=#0
[+4272 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +7 ms] D/MALI    (10478): glReadPixels:1684: --
[ +212 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[+1025 ms] V/InputMethodManager(10478): START INPUT:
io.flutter.view.FlutterView{367b0a8 VFE..... .F....I. 0,0-720,1280}
ic=io.flutter.plugin.editing.InputConnectionAdaptor@2150a9f4
tba=android.view.inputmethod.EditorInfo@29d8e51d controlFlags=#0
[  +24 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +7 ms] D/MALI    (10478): glReadPixels:1684: --
[ +335 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[  +23 ms] D/MALI    (10478): glReadPixels:1684: --
[ +225 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +179 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +8 ms] D/MALI    (10478): glReadPixels:1684: --
[ +295 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +239 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +8 ms] D/MALI    (10478): glReadPixels:1684: --
[  +76 ms] V/InputMethodManager(10478): START INPUT:
io.flutter.view.FlutterView{367b0a8 VFE..... .F....I. 0,0-720,1280}
ic=io.flutter.plugin.editing.InputConnectionAdaptor@38969392
tba=android.view.inputmethod.EditorInfo@2dff8163 controlFlags=#0
[ +110 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +193 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +215 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[  +12 ms] D/MALI    (10478): glReadPixels:1684: --
[ +156 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +332 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,728,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +289 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +222 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +6 ms] D/MALI    (10478): glReadPixels:1684: --
[ +263 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +249 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +245 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[  +79 ms] I/flutter (10478): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
[  +19 ms] I/flutter (10478): The following assertion was thrown building
_ScrollableScope:
[        ] I/flutter (10478): 'package:flutter/src/rendering/editable.dart': Failed
assertion: line 599 pos 14:
[        ] I/flutter (10478): '_listenerAttached': is not true.
[  +10 ms] I/flutter (10478): Either the assertion indicates an error in the framework
itself, or we should provide substantially
[        ] I/flutter (10478): more information in this error message to help you
determine and fix the underlying cause.
[        ] I/flutter (10478): In either case, please report this assertion by filing a
bug on GitHub:
[        ] I/flutter (10478):
https://github.com/flutter/flutter/issues/new?template=BUG.md
[  +12 ms] I/flutter (10478): When the exception was thrown, this was the stack:
[   +5 ms] I/flutter (10478): #2      RenderEditable.hasFocus=
(package:flutter/src/rendering/editable.dart:599:14)
[   +1 ms] I/flutter (10478): #3      _Editable.updateRenderObject
(package:flutter/src/widgets/editable_text.dart:1114:9)
[        ] I/flutter (10478): #4      RenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4494:12)
[   +1 ms] I/flutter (10478): #5      Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[   +1 ms] I/flutter (10478): #6      SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[   +1 ms] I/flutter (10478): #7      Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #8      SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #9      Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #10     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #11     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #12     ProxyElement.update
(package:flutter/src/widgets/framework.dart:3990:5)
[        ] I/flutter (10478): #13     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #14     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #15     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #16     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #17     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #18     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #19     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #20     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #21     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #22     StatefulElement.update
(package:flutter/src/widgets/framework.dart:3878:5)
[        ] I/flutter (10478): #23     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #24     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #25     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #26     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #27     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #28     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:4867:14)
[        ] I/flutter (10478): #29     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #30     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #31     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #32     StatelessElement.update
(package:flutter/src/widgets/framework.dart:3781:5)
[        ] I/flutter (10478): #33     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #34     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #35     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #36     StatefulElement.update
(package:flutter/src/widgets/framework.dart:3878:5)
[   +1 ms] I/flutter (10478): #37     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #38     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #39     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #40     StatefulElement.update
(package:flutter/src/widgets/framework.dart:3878:5)
[        ] I/flutter (10478): #41     Element.updateChild
(package:flutter/src/widgets/framework.dart:2742:15)
[        ] I/flutter (10478): #42     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3732:16)
[        ] I/flutter (10478): #43     Element.rebuild
(package:flutter/src/widgets/framework.dart:3547:5)
[        ] I/flutter (10478): #44     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2286:33)
[        ] I/flutter (10478): #45
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&Pain
tingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:676:20)
[   +1 ms] I/flutter (10478): #46
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&Pain
tingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:219:5)
[   +1 ms] I/flutter (10478): #47
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._inv
okeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[   +1 ms] I/flutter (10478): #48
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.hand
leDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter (10478): #49
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._han
dleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
[        ] I/flutter (10478): #50     _invoke (dart:ui/hooks.dart:154:13)
[        ] I/flutter (10478): #51     _drawFrame (dart:ui/hooks.dart:143:3)
[        ] I/flutter (10478): (elided 2 frames from class _AssertionError)
[        ] I/flutter (10478):
═══════════════════════════════════════════════════════════════════════════════════════
═════════════
[ +320 ms] I/flutter (10478): Another exception was thrown: Duplicate GlobalKey
detected in widget tree.
[ +365 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +300 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +258 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --
[ +701 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +228 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +205 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +4 ms] D/MALI    (10478): glReadPixels:1684: --
[ +227 ms] D/MALI    (10478): glReadPixels:1680: ++:(x,y,w,h)=(0,0,729,486)
[   +5 ms] D/MALI    (10478): glReadPixels:1684: --

```

```
Analyzing cat_dog_encyclopedia...

   info - The value of the field '_bgImage' isn't used - lib\style\theme.dart:24:16 - unused_field
   info - The value of the field '_imageThreshold' isn't used - lib\ui\details_page.dart:47:17 - unused_field
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\details_page.dart:50:17 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\ui\details_page.dart:51:17 - non_constant_identifier_names
   info - The method '_buildBottomBar' isn't used - lib\ui\details_page.dart:321:10 - unused_element
   info - The value of the field '_searchText' isn't used - lib\ui\list_animals.dart:58:10 - unused_field
   info - The method '_buildBottomBar' isn't used - lib\ui\list_animals.dart:337:10 - unused_element

7 issues found. (ran in 11.9s)

```

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at D:\adhikagunadarma\Iseng\Flutter\flutter_sdk
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\asuss\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • A1601 • 7TLFTCT8HEHMU4BM • android-arm64 • Android 5.1 (API 22)

• No issues found!

```

**Comment by zoechi** [comment]
Might be a dup of #21640

**Comment by adhikagunadarma** [comment]
> Might be a dup of #21640

just checked the page, and the issue is pretty much same.
Thanks for the help @zoechi
