### ISSUE TITLE
Flutter_view installs audioplayers playback resource audio error

### ISSUE THREAD

**Issue by cnqiuxue** [flutter/flutter#25832]
## Steps to Reproduce

1.
```yml
dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.7.8

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/gongjiaoka.mp3
```
2.
```dart
import 'package:audioplayers/audio_cache.dart';
AudioCache audioCache = new AudioCache();
```
3.
```dart
 @override
  void initState() {
    audioCache.play('gongjiaoka.mp3');
    super.initState();
  }
```
4、
![image](https://user-images.githubusercontent.com/26665435/50502545-0e70e880-0a9b-11e9-8705-5095d33fff6b.png)

## Logs
```
E/flutter ( 9576): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 9576): MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 9576): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 9576): <asynchronous suspension>
E/flutter ( 9576): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:24:38)
E/flutter ( 9576): <asynchronous suspension>
E/flutter ( 9576): #2      AudioCache.fetchToMemory (package:audioplayers/audio_cache.dart:54:37)
E/flutter ( 9576): <asynchronous suspension>
E/flutter ( 9576): #3      AudioCache.load (package:audioplayers/audio_cache.dart:72:37)
E/flutter ( 9576): <asynchronous suspension>
E/flutter ( 9576): #4      AudioCache.play (package:audioplayers/audio_cache.dart:87:23)
E/flutter ( 9576): <asynchronous suspension>
E/flutter ( 9576): #5      _MyHomePageState.initState (package:flutter_view/main.dart:47:16)
E/flutter ( 9576): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter ( 9576): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 9576): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 9576): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 9576): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 9576): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 9576): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 9576): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 9576): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 9576): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 9576): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 9576): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 9576): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 9576): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 9576): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 9576): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 9576): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 9576): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 9576): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 9576): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 9576): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 9576): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 9576): #44     Com
```

```
bcmac001siMac:flutter_view bc-mac-001$ flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/bc-mac-001/Dev/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/bc-mac-001/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/bc-mac-001/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • ZUK Z1 • cb8cb8dd • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

```

**Comment by zoechi** [comment]
You could check if one of the suggestions in 
- https://github.com/flutter/flutter/issues/24171#issuecomment-439667926
- https://github.com/flutter/flutter/issues/24561#issuecomment-440205984 
- https://github.com/flutter/flutter/issues/21674#issuecomment-425865894
- https://github.com/flutter/flutter/issues/17545#issuecomment-395763875
- https://github.com/flutter/flutter/issues/15085#issuecomment-370169678
works for you as well

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ramioooz** [comment]
hot reloads not doing so well when adding/changing audio files to player.
quit out/stop running flutter process/debug and restart again.
worked for me.

Thanks
