### ISSUE TITLE
Calling forward/reverse on animationController: NoSuchMethodError

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#25847]
## Steps to Reproduce

1. Create two pages where the second page has an animationController that starts in initState.
2. navigate back out and in so the controller gets disposed and initiated again
2. call controller.stop() when the state of the application is paused
3. Call forward when the state is resumed (here the error occurs).

```dart
 @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _controller = AnimationController(
      duration: Duration(seconds: 60),
      vsync: this,
      value: 1.0,
    );

  _controller.forward();
  }
```

```dart
  @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.paused && _controller.isAnimating) {
      _controller.stop();
    } else if (state == AppLifecycleState.resumed) {
      _controller.forward();
    }
  }
```
## Logs

```
[+5557 ms] E/flutter (11601): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
[        ] E/flutter (11601): NoSuchMethodError: The method 'stop' was called on null.
[        ] E/flutter (11601): Receiver: null
[        ] E/flutter (11601): Tried calling: stop(canceled: true)
[        ] E/flutter (11601): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
[        ] E/flutter (11601): #1      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:650:13)
[        ] E/flutter (11601): #2      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:525:5)
[        ] E/flutter (11601): #3      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:442:12)
[        ] E/flutter (11601): #4      TaskBodyPageState.didChangeAppLifecycleState (package:quickit/src/pages/tasks/widgets/task_body_page.dart:61:19)
[        ] E/flutter (11601): <asynchronous suspension>
[        ] E/flutter (11601): #5
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:501:16)
[   +1 ms] E/flutter (11601): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleLifecycleMessage
(package:flutter/src/scheduler/binding.dart:254:5)
[        ] E/flutter (11601): <asynchronous suspension>
[        ] E/flutter (11601): #7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:65:49)
[        ] E/flutter (11601): <asynchronous suspension>
[        ] E/flutter (11601): #8      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
[        ] E/flutter (11601): <asynchronous suspension>
[        ] E/flutter (11601): #9      _invoke3 (dart:ui/hooks.dart:196:13)
[        ] E/flutter (11601): #10     _dispatchPlatformMessage (dart:ui/hooks.dart:105:5)
[        ] E/BpSurfaceComposerClient(11601): Failed to transact (-1)
[        ] E/BpSurfaceComposerClient(11601): Failed to transact (-1)
```

```
```

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-GB)
    • Flutter version 1.0.0 at C:\Users\Robert\flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2018.2.4
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • ONEPLUS A3003 • 5ffff941 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by RobertBrunhage** [comment]
Resolved it by adding WidgetsBinding.instance.removeObserver(this); to the dispose (had forgotten it).

Maybe the error message for this can be improved?

**Comment by goderbauer** [comment]
@RobertBrunhage Why are you listening for the app life cycle state in this case and stop the animation? The engine should already stop all animations when the app is paused.

**Comment by goderbauer** [comment]
We should add an assert to stop and similar methods to tell you that it was called on a disposed AnimationController.

**Comment by RobertBrunhage** [comment]
@dnfield @goderbauer Used it as a timer and it was not consistent to when it would pause itself. Sometimes it didn't pause after several minutes in the background and sometimes it did pause after 1 minute. Saved the date to remove the seconds from the animation when the app went back to foreground.

I needed to have exact seconds and later moved on to Timer to better handle this.
