### ISSUE TITLE
any solution plzz

### ISSUE THREAD

**Issue by NawazS** [flutter/flutter#25878]
```
I/flutter ( 7544): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/zygote  ( 7544): Background concurrent copying GC freed 21551(1991KB) AllocSpace objects, 9(244KB) LOS objects, 54% free, 1266KB/2MB, paused 7.051ms total 127.342ms
I/flutter ( 7544): The following assertion was thrown building StreamBuilder<DocumentSnapshot>(dirty, state:
I/flutter ( 7544): _StreamBuilderBaseState<DocumentSnapshot, AsyncSnapshot<DocumentSnapshot>>#a739f):
I/flutter ( 7544): Failed assertion: boolean expression must not be null
I/zygote  ( 7544): The ClassLoaderContext is a special shared library.
I/chatty  ( 7544): uid=10079(com.example.firebaseloginadmin) FirestoreWorker identical 1 line
I/zygote  ( 7544): The ClassLoaderContext is a special shared library.
I/flutter ( 7544): 
I/flutter ( 7544): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7544): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7544): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7544):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7544): 
V/NativeCrypto( 7544): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
I/flutter ( 7544): When the exception was thrown, this was the stack:
I/flutter ( 7544): #0      HomePage.build.<anonymous closure> (package:firebase_login_admin/home_page.dart:21:24)
I/flutter ( 7544): #1      StreamBuilder.build (package:flutter/src/widgets/async.dart:423:74)
I/flutter ( 7544): #2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter ( 7544): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 7544): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 7544): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 7544): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
I/flutter ( 7544): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #112    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #128    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
D/NetworkSecurityConfig( 7544): No Network Security Config specified, using platform default
I/ProviderInstaller( 7544): Installed default security provider GmsCore_OpenSSL
I/flutter ( 7544): #138    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #147    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #153    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #154    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #155    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #159    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #163    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7544): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #175    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7544): #182    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7544): #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7544): #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7544): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7544): #186    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4643:32)
I/flutter ( 7544): #187    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 7544): #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #189    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 7544): #190    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #192    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #193    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 7544): #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #197    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 7544): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #199    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 7544): #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #202    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #203    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 7544): #204    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #205    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 7544): #206    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #207    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 7544): #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 7544): #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7544): #210    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7544): #211    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 7544): #212    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 7544): #213    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 7544): #214    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7544): #215    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7544): #216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 7544): #217    _invoke (dart:ui/hooks.dart:159:13)
I/flutter ( 7544): #218    _drawFrame (dart:ui/hooks.dart:148:3)
I/flutter ( 7544): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7544): Another exception was thrown: Failed assertion: boolean expression must not be null
I/flutter ( 7544): Another exception was thrown: Failed assertion: boolean expression must not be null
I/FirebaseAuth( 7544): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth( 7544): [FirebaseAuth:] Preparing to create service connection to gms implementation
```

**Comment by zoechi** [comment]
> `Failed assertion: boolean expression must not be null`

Sounds like an issue in your custom code.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
