### ISSUE TITLE
Get Center lat long of google map using google_maps library?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [flutter/flutter#25918]
Hello folks,
  Recently am started working on flutter , so i have decided to start from google maps so i have implemented it  using google_map library , but when i trying to get center point of the map am getting issue like this:

```
12-31 15:22:43.853 6768-6797/com.example.demoapp I/flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════

12-31 15:22:43.874 6768-6797/com.example.demoapp I/flutter: The following NoSuchMethodError was thrown while dispatching notifications for GoogleMapController:
    The getter 'target' was called on null.
    Receiver: null
    Tried calling: target
12-31 15:22:43.875 6768-6797/com.example.demoapp I/flutter: When the exception was thrown, this was the stack:
12-31 15:22:43.897 6768-6797/com.example.demoapp I/flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
    #1      MapsDemoState._extractMapInfo (package:demoapp/GoogleMaps.dart:115:21)
    #2      MapsDemoState._onMapChanged.<anonymous closure> (package:demoapp/GoogleMaps.dart:109:7)
    #3      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
    #4      MapsDemoState._onMapChanged (package:demoapp/GoogleMaps.dart:108:5)
    #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:208:21)
12-31 15:22:43.898 6768-6797/com.example.demoapp I/flutter: #6      GoogleMapController._handleMethodCall (file:///E:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.0.3+3/lib/src/controller.dart:104:9)
12-31 15:22:43.899 6768-6797/com.example.demoapp I/flutter: <asynchronous suspension>
    #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:344:55)
    <asynchronous suspension>
    #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:312:54)
    #9      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
    <asynchronous suspension>
    #10     _invoke3 (dart:ui/hooks.dart:196:13)
    #11     _dispatchPlatformMessage (dart:ui/hooks.dart:105:5)
```

This is the code am trying to execute don't know whether it's my mistake or any issue in library any suggestion would be very much helpful for me .  Now let me post what i have tried so far:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'package:geocoder/geocoder.dart';
import 'package:geolocator/geolocator.dart';
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(title: const Text('Google Maps demo')),
      body: MapsDemo(),
    ),
  ));
}

class MapsDemo extends StatefulWidget {

  @override
  State createState() => MapsDemoState();
}


class MapsDemoState extends State<MapsDemo> {
  var geolocator = Geolocator();
  Position position;
  static final CameraPosition _kInitialPosition = const CameraPosition(
    target: LatLng(-33.852, 151.211),
    zoom: 11.0,
  );
  CameraPosition _position = _kInitialPosition;
  bool _isMoving = false;
  StreamSubscription _getPositionSubscription;
  var locationOptions = LocationOptions(accuracy: LocationAccuracy.high, timeInterval: 10);
  GoogleMapController mapController;
  @override
  void initState() {
    super.initState();
    _getPositionSubscription=   geolocator.getPositionStream(locationOptions).listen(
            (Position position) {
             this.position=position;
          print(position == null ? 'Unknown' : position.latitude.toString() + ', ' + position.longitude.toString());
          mapController.animateCamera(
            CameraUpdate.newCameraPosition(
              CameraPosition(
                  target: LatLng(position.latitude,position.longitude), zoom: 20.0),

            ),
          );

        });
  }
  @override
  Widget build(BuildContext context) {


    return  Stack(
      children: [
        Container(
          width: double.infinity,
          height: double.infinity,
          child: GoogleMap(
              onMapCreated: _onMapCreated,
              options: GoogleMapOptions(
                  myLocationEnabled: true
              )

          ),
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Align(
            alignment: Alignment.bottomCenter,
            child:   new RaisedButton(
              onPressed: _getAddress,
              textColor: Colors.white,
              color: Colors.red,
              padding: const EdgeInsets.all(8.0),
              child: new Text(
                "GetAddress",
              ),
            ),
          ),
        ),
        Center(
          child: Image.asset(
              'assets/images/startloc.png'
              ,height: 60,
            width: 60,
          ),
        )
      ],


    );

  }

  void _onMapCreated(GoogleMapController controller) {

    mapController = controller;
    mapController.addListener(_onMapChanged);
    _extractMapInfo();
    setState(() {});

  }
  void _onMapChanged() {
    setState(() {
      _extractMapInfo();
    });
  }

  void _extractMapInfo() {
    _position = mapController.cameraPosition;
    print(_position.target.longitude);
    _isMoving = mapController.isCameraMoving;
  }

  Future _getAddress() async {
//    List<Placemark> placemark = await Geolocator().placemarkFromCoordinates(position.latitude,position.longitude);
//     print(placemark.elementAt(0).locality);\
    print( _position.target.latitude);
    final coordinates = new Coordinates(_position.target.latitude,_position.target.longitude);

    print(coordinates);

   var addresses = await Geocoder.local.findAddressesFromCoordinates(coordinates);
   print( addresses.first.addressLine);
  }
  @override
  void dispose() {
    _getPositionSubscription.cancel();
    super.dispose();
  }

}
```

This is the code am running , please someone helpme out need to get center latlong of google map

**Comment by YogeshLegendkiller** [comment]
Hello folks,
Recently am started working on flutter , so i have decided to start from google maps so i have implemented it using google_map library , but when i trying to get center point of the map am getting issue like this:

```
12-31 15:22:43.853 6768-6797/com.example.demoapp I/flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════

12-31 15:22:43.874 6768-6797/com.example.demoapp I/flutter: The following NoSuchMethodError was thrown while dispatching notifications for GoogleMapController:
The getter 'target' was called on null.
Receiver: null
Tried calling: target
12-31 15:22:43.875 6768-6797/com.example.demoapp I/flutter: When the exception was thrown, this was the stack:
12-31 15:22:43.897 6768-6797/com.example.demoapp I/flutter: #0 Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1 MapsDemoState._extractMapInfo (package:demoapp/GoogleMaps.dart:115:21)
#2 MapsDemoState._onMapChanged. (package:demoapp/GoogleMaps.dart:109:7)
#3 State.setState (package:flutter/src/widgets/framework.dart:1130:30)
#4 MapsDemoState._onMapChanged (package:demoapp/GoogleMaps.dart:108:5)
#5 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:208:21)
12-31 15:22:43.898 6768-6797/com.example.demoapp I/flutter: #6 GoogleMapController._handleMethodCall (file:///E:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.0.3+3/lib/src/controller.dart:104:9)
12-31 15:22:43.899 6768-6797/com.example.demoapp I/flutter: 
#7 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:344:55)

#8 MethodChannel.setMethodCallHandler. (package:flutter/src/services/platform_channel.dart:312:54)
#9 BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)

#10 _invoke3 (dart:ui/hooks.dart:196:13)
#11 _dispatchPlatformMessage (dart:ui/hooks.dart:105:5)
```

This is the code am trying to execute don't know whether it's my mistake or any issue in library any suggestion would be very much helpful for me . Now let me post what i have tried so far:



```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'package:geocoder/geocoder.dart';
import 'package:geolocator/geolocator.dart';
void main() {
runApp(MaterialApp(
home: Scaffold(
appBar: AppBar(title: const Text('Google Maps demo')),
body: MapsDemo(),
),
));
}

class MapsDemo extends StatefulWidget {

@override
State createState() => MapsDemoState();
}

class MapsDemoState extends State {
var geolocator = Geolocator();
Position position;
static final CameraPosition _kInitialPosition = const CameraPosition(
target: LatLng(-33.852, 151.211),
zoom: 11.0,
);
CameraPosition _position = _kInitialPosition;
bool _isMoving = false;
StreamSubscription _getPositionSubscription;
var locationOptions = LocationOptions(accuracy: LocationAccuracy.high, timeInterval: 10);
GoogleMapController mapController;
@override
void initState() {
super.initState();
_getPositionSubscription= geolocator.getPositionStream(locationOptions).listen(
(Position position) {
this.position=position;
print(position == null ? 'Unknown' : position.latitude.toString() + ', ' + position.longitude.toString());
mapController.animateCamera(
CameraUpdate.newCameraPosition(
CameraPosition(
target: LatLng(position.latitude,position.longitude), zoom: 20.0),

        ),
      );

    });
}
@override
Widget build(BuildContext context) {

return  Stack(
  children: [
    Container(
      width: double.infinity,
      height: double.infinity,
      child: GoogleMap(
          onMapCreated: _onMapCreated,
          options: GoogleMapOptions(
              myLocationEnabled: true
          )

      ),
    ),
    Padding(
      padding: const EdgeInsets.all(8.0),
      child: Align(
        alignment: Alignment.bottomCenter,
        child:   new RaisedButton(
          onPressed: _getAddress,
          textColor: Colors.white,
          color: Colors.red,
          padding: const EdgeInsets.all(8.0),
          child: new Text(
            "GetAddress",
          ),
        ),
      ),
    ),
    Center(
      child: Image.asset(
          'assets/images/startloc.png'
          ,height: 60,
        width: 60,
      ),
    )
  ],


);
}

void _onMapCreated(GoogleMapController controller) {

mapController = controller;
mapController.addListener(_onMapChanged);
_extractMapInfo();
setState(() {});
}
void _onMapChanged() {
setState(() {
_extractMapInfo();
});
}

void _extractMapInfo() {
_position = mapController.cameraPosition;
print(_position.target.longitude);
_isMoving = mapController.isCameraMoving;
}

Future _getAddress() async {
// List placemark = await Geolocator().placemarkFromCoordinates(position.latitude,position.longitude);
// print(placemark.elementAt(0).locality);
print( _position.target.latitude);
final coordinates = new Coordinates(_position.target.latitude,_position.target.longitude);

print(coordinates);
var addresses = await Geocoder.local.findAddressesFromCoordinates(coordinates);
print( addresses.first.addressLine);
}
@override
void dispose() {
_getPositionSubscription.cancel();
super.dispose();
}

}

```
This is the code am running , please someone helpme out need to get center latlong of google map

**Comment by YogeshLegendkiller** [comment]
@zoechi  then this feature is missing right ?

**Comment by daanvandenhoek** [comment]
> 
> 
> @zoechi then this feature is missing right ?

No your code is missing a very importent line.
if you read the comments of `mapController.cameraPosition;`
you can read that you need the options trackCameraPosition your google map.
you have the options:
```
GoogleMapOptions(
                  myLocationEnabled: true
              )
```

but to get the cameraposition you also need the option:
So change it to:
```
GoogleMapOptions(
                  myLocationEnabled: true,
trackCameraPosition: true
              )
```

and that should work (it does for me)

**Comment by YogeshLegendkiller** [comment]
@daanvandenhoek  THANKS BRO IT WORKS

**Comment by zoechi** [comment]
Sounds like this is a support request that was solved.
Thanks @daanvandenhoek

**Comment by Kaakati** [comment]
appearently the GoogleMapController has changed, where can I find `cameraPosition` now?

**Comment by FrimJo** [comment]
`trackCameraPosition` does not exist on `GoogleMap` any longer, where can I force the map to center on user? 

Currently I'm using geolocation with a subscription to position where I run `animateCamera` on the `GoogleMapController` which works fine. But I want to be able to toggle this off when user manually moves the map, and turn it on again when user uses the "center on user" button, but I can not find a way to add a callback this this button.

**Comment by haashem** [comment]
The right way:
you can easily get center of visible region using mapController:

```dart
 final LatLng? mapCenter = (await mapController?.getVisibleRegion())?.center;
```

```dart
extension LatLngBoundsX on LatLngBounds {
  LatLng get center {
    return LatLng((southwest.latitude + northeast.latitude) / 2,
        (southwest.longitude + northeast.longitude) / 2);
  }
}
```

[reference](https://stackoverflow.com/questions/29322582/how-to-calculate-center-of-bounds-without-googlemaps)

**Comment by harlekintiger** [comment]
Be careful, while @haashem 's approach works in most cases, it gets increasingly more inaccurate the more zoomed out you are. It will also completely fail at the wrap around point of the LatLng coordinate system.    

The GoogleMap widget has an `onCameraMove` callback which provides the middle of the visible map as `CameraPosition`. You could use a local variable to store the current middle point and update it with a method.


```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class GoogleMapsWrapper extends StatefulWidget {
  @override
  _GoogleMapsWrapperState createState() => _GoogleMapsWrapperState();
}

class _GoogleMapsWrapperState extends State<GoogleMapsWrapper> {

  GoogleMapController gMapController;
  LatLng middlePointOfScreenOnMap;


  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      onCameraMove: (CameraPosition cameraPosition) => middlePointOfScreenOnMap = cameraPosition.target,
      onMapCreated: (GoogleMapController controller) => gMapController = controller, 
    );
  }
} 
```
