### ISSUE TITLE
Support rootBundle and/or fail gracefully in "flutter test"

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#25925]
_(This is at Flutter 1.0.0 Stable)_

Related (closed) issue: https://github.com/flutter/flutter/issues/23466
Related (closed) S/O: https://stackoverflow.com/questions/49480080/flutter-load-assets-for-tests

Currently, when you have a widget that loads an asset, for example using `Image.asset`, and you try to test that widget (`flutter test test/my_icon_test.dart`), you get the following bizarre error message:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
...
#376    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:897:35)
```

After reading the above issues, I realized that relying on the `rootBundle` in widget tests is unsupported, and the suggested alternatives is to basically implement the bundle yourself for a test. That seems ... pretty rough for what (I expect) most users want to do, for example take golden tests of various widgets.

A more short-term fix might be handling this error case better in `flutter test` (i.e. the feedback of the error shouldn't leak some mysterious `AssetManinfest.json` file).

## Doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by matanlurey** [comment]
Oops, closing as a duplicate of https://github.com/flutter/flutter/issues/12999.
