### ISSUE TITLE
InterstitialAd not show in real UNIT_ID 

### ISSUE THREAD

**Issue by zrg-team** [flutter/flutter#25938]
## Steps to Reproduce

AndroidManifest.xml
```xml
<application>
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-6308632307209872~8632944973"/>
```
Code
```dart
FirebaseAdMob.instance.initialize(appId: 'ca-app-pub-6308632307209872~8632944973');
interstitialAd = InterstitialAd(
        adUnitId: READING_ADS_ID,
        targetingInfo: targetingInfo,
        listener: (MobileAdEvent event) {
          if (event == MobileAdEvent.loaded) {
            interstitialAd?.show();
          }
          if (event == MobileAdEvent.clicked || event == MobileAdEvent.closed) {
            widget.clearReadingCount();
          }
        }
      )..load();
```
it worked with `InterstitialAd.testUnitId` but not real unit id 

## Logs

```
[   +6 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +4 ms] An Observatory debugger and profiler on Google Nexus 5X, 6 0 0, API 23, 1080x1920 is available at:
http://127.0.0.1:60836/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+62176 ms] I/flutter ( 1814): ══╡ EXCEPTION CAUGHT BY GESTURE
╞═══════════════════════════════════════════════════════════════════
[   +8 ms] I/flutter ( 1814): The following assertion was thrown while handling a gesture:
[        ] I/flutter ( 1814): Failed assertion: boolean expression must not be null
[   +3 ms] I/flutter ( 1814): Either the assertion indicates an error in the framework itself, or we should provide
substantially
[        ] I/flutter ( 1814): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 1814): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 1814):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 1814): When the exception was thrown, this was the stack:
[   +8 ms] I/flutter ( 1814): #0      Newsfeed.build.<anonymous closure> (package:cat_dog/common/components/Newsfeed.dart:95:42)
[        ] I/flutter ( 1814): #1      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
[   +1 ms] I/flutter ( 1814): #2      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
[        ] I/flutter ( 1814): #3      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
[        ] I/flutter ( 1814): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] I/flutter ( 1814): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:184:20)
[   +1 ms] I/flutter ( 1814): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:158:22)
[   +8 ms] I/flutter ( 1814): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:138:7)
[   +7 ms] I/flutter ( 1814): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:101:7)
[   +1 ms] I/flutter ( 1814): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:85:7)
[   +1 ms] I/flutter ( 1814): #10     _invoke1 (dart:ui/hooks.dart:168:13)
[        ] I/flutter ( 1814): #11     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
[        ] I/flutter ( 1814): Handler: onTap
[        ] I/flutter ( 1814): Recognizer:
[        ] I/flutter ( 1814):   TapGestureRecognizer#180bc(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
[   +1 ms] I/flutter ( 1814):   Offset(81.1, 606.5), sent tap down)
[        ] I/flutter ( 1814):
════════════════════════════════════════════════════════════════════════════════════════════════════
[  +44 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[        ] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[        ] I/flutter ( 1814): [INFO] LoggingMiddleware: {Action: Instance of 'AddReadingCount', State: Instance of 'AppState',
ts: 2019-01-01 03:53:27.083585}
[   +7 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[   +5 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[        ] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[   +2 ms] I/Ads     ( 1814): Starting ad request.
[        ] I/Ads     ( 1814): SDK version: afma-sdk-a-v13000000.13000000.0
[        ] I/Ads     ( 1814): Use AdRequest.Builder.addTestDevice("2A1FC96FE50FDD0E92CCE3B0A2EF1C5F") to get test ads on this
device.
[   +3 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[   +3 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[  +24 ms] V/WebViewFactory( 1814): webViewPackageName: com.android.webview
[   +1 ms] I/WebViewFactory( 1814): Loading com.android.webview version 44.0.2403.119 (code 246011910)
[ +215 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[   +6 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[  +25 ms] W/System  ( 1814): ClassLoader referenced unknown path: /system/app/webview/lib/x86
[ +114 ms] I/LibraryLoader( 1814): Time to load native libraries: 64 ms (timestamps 3041-3105)
[        ] I/LibraryLoader( 1814): Expected native library version number "",actual native library version number ""
[ +374 ms] W/art     ( 1814): Attempt to remove non-JNI local reference, dumping thread
[ +252 ms] W/GooglePlayServicesUtil( 1814): Google Play Store is missing.
[  +26 ms] V/WebViewChromiumFactoryProvider( 1814): Binding Chromium to main looper Looper (main, tid 1) {9ec656c}
[   +2 ms] I/LibraryLoader( 1814): Expected native library version number "",actual native library version number ""
[   +3 ms] I/chromium( 1814): [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0
[  +10 ms] I/BrowserStartupController( 1814): Initializing chromium process, singleProcess=true
[   +7 ms] W/art     ( 1814): Attempt to remove non-JNI local reference, dumping thread
[   +3 ms] E/SysUtils( 1814): ApplicationContext is null in ApplicationStatus
[  +55 ms] W/chromium( 1814): [WARNING:resource_bundle.cc(285)] locale_file_path.empty()
[  +17 ms] E/libEGL  ( 1814): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
[        ] E/libEGL  ( 1814): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
[  +30 ms] E/eglCodecCommon( 1814): glUtilsParamSize: unknow param 0x00008d57
[  +81 ms] W/AudioManagerAndroid( 1814): Requires BLUETOOTH permission
[  +46 ms] E/DataReductionProxySettingListener( 1814): No DRP key due to exception:java.lang.ClassNotFoundException:
com.android.webview.chromium.Drp
[ +106 ms] W/art     ( 1814): Attempt to remove non-JNI local reference, dumping thread
[  +12 ms] W/AwContents( 1814): onDetachedFromWindow called when already detached. Ignoring
[   +8 ms] W/art     ( 1814): Attempt to remove non-JNI local reference, dumping thread
[        ] W/art     ( 1814): Attempt to remove non-JNI local reference, dumping thread
[  +65 ms] W/chromium( 1814): [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
[ +585 ms] D/        ( 1814): HostConnection::get() New Host Connection established 0xe8bd2c60, tid 1928
[ +443 ms] W/BindingManager( 1814): Cannot call determinedVisibility() - never saw a connection for the pid: 1814
[+1614 ms] W/Ads     ( 1814): Received error HTTP response code: 400
[   +5 ms] W/Ads     ( 1814): There was a problem getting an ad response. ErrorCode: 0
[   +2 ms] W/Ads     ( 1814): Failed to load ad: 0
[        ] W/flutter ( 1814): onAdFailedToLoad: 0
[  +22 ms] E/FirebaseInstanceId( 1814): Google Play services missing or without correct permission.

```

```
Analyzing cat_dog...
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.5 17F77, locale en-VN)
    • Flutter version 1.0.0 at /Users/mac-lt108/Documents/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mac-lt108/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mac-lt108/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected device (1 available)
    • Google Nexus 5X, 6 0 0, API 23, 1080x1920 • 192.168.56.101:5555 • android-x86 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by zrg-team** [comment]
sorry ! it worked

**Comment by kroikie** [comment]
@zrg-team

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/525. Any further collaboration will be done there.
