### ISSUE TITLE
OnFocus if the textfield error is thrown

### ISSUE THREAD

**Issue by prachiFam** [flutter/flutter#26002]
On android there is error

![device-2019-01-03-125651](https://user-images.githubusercontent.com/46080902/50626949-36f35980-0f57-11e9-8037-959d8d92616f.png)

## Logs
```
When the exception was thrown, this was the stack:
I/flutter (18068): #2      FocusScopeNode.setFirstFocus (package:flutter/src/widgets/focus_manager.dart:315:12)
I/flutter (18068): #3      FocusScopeNode.reparentScopeIfNeeded (package:flutter/src/widgets/focus_manager.dart:338:7)
I/flutter (18068): #4      _FocusScopeState.build (package:flutter/src/widgets/focus_scope.dart:104:28)
I/flutter (18068): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (18068): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (18068): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (18068): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (18068): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (18068): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (18068): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (18068): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (18068): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (18068): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (18068): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2943:38)
I/flutter (18068): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
I/flutter (18068): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #57     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #94     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #103    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #108    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #109    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #110    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (18068): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #131    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068): #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (18068): #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (18068): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (18068): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (18068): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (18068): #137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (18068): #138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (18068)

```

**Comment by zoechi** [comment]
#16601 looks similar.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kerberjg** [comment]
Seems to be a dupe of #11719
