### ISSUE TITLE
Improve error output for projects copyied from another machine.

### ISSUE THREAD

**Issue by AnassL** [flutter/flutter#26014]
Error while trying to run on Windows a Flutter App created on mac - flutter has exited unexpectedly

## Steps to Reproduce

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception
```
FileSystemException: FileSystemException: Cannot open file, path = 'D:\_Flutter\news\.flutter-plugins' (OS Error: Access denied.
, errno = 5)
```
```
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.openSync (dart:io/file_impl.dart:491:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:616:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:640:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:99:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:288:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:139:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:389:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#40     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.17134.472], locale fr-FR)
    [32m•[39m Flutter version 1.0.0 at C:\_sdk\flutter
    [32m•[39m Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at C:\Users\Anass\AppData\Local\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = C:\Users\Anass\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code, 64-bit edition (version 1.30.1)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 2.21.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

[32m•[39m No issues found!
```

**Comment by kangwang1988** [comment]
Check the mode for 'D:_Flutter\news.flutter-plugins' and make sure it's writable.
Beside, check if it working fine when creating a totally new flutter project in your windows.
@AnassL

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

If you didn't use `git clone` to copy the project, you might need to delete the files and directories listed in `.gitignore` manually.
`access denied` could mean another app has the file open, like a virus scanner.

**Comment by AnassL** [comment]
@zoechi I fixed the issue just by renaming the file created by mac OS: ".flutter-plugins" to whatever file name, another ".flutter-plugings" file was created by Flutter on Windows, and the app could run normally on the emulator. I just wanted to warn about this bug.

**Comment by zoechi** [comment]
@AnassL thanks!
I also think it is a good idea to improve the error output for this situation.

**Comment by AnassL** [comment]
Yes, I agree, thanks.

**Comment by zoechi** [comment]
Reopen for improving error message.

**Comment by jonahwilliams** [comment]
We've since add `.flutter-plugins` to the default gitignore template. This file contains OS specific paths so it isn't safe to commit to source control.

**Comment by TarchyV** [comment]
Just want to point out I am running into this issue on Flutter Beta v1.10.7
