### ISSUE TITLE
DropdownButtonFormField with Firestore Streambuilder show an error is value is null.

### ISSUE THREAD

**Issue by ketulrastogi** [flutter/flutter#26083]
Launching lib\main.dart on Redmi 3S in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
W/ResourceType( 9291): No package identifier when getting name for resource number 0x00000000
I/DynamiteModule( 9291): Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:3
I/DynamiteModule( 9291): Selected local version of com.google.android.gms.flags
V/NativeCrypto( 9291): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
I/art     ( 9291): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     ( 9291): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     ( 9291): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/art     ( 9291): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/ProviderInstaller( 9291): Installed default security provider GmsCore_OpenSSL
I/flutter ( 9291): rto
I/flutter ( 9291): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9291): The following assertion was thrown building DropdownButtonFormField<DocumentSnapshot>(dirty, state:
I/flutter ( 9291): _DropdownButtonFormFieldState<DocumentSnapshot>#26f52):
I/flutter ( 9291): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 514 pos 15: 'items == null ||
I/flutter ( 9291): value == null || items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not
I/flutter ( 9291): true.
I/flutter ( 9291): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9291): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9291): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9291):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9291): When the exception was thrown, this was the stack:
I/flutter ( 9291): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:514:15)
I/flutter ( 9291): #3      new DropdownButtonFormField.<anonymous closure> (package:flutter/src/material/dropdown.dart:796:23)
I/flutter ( 9291): #4      FormFieldState.build (package:flutter/src/widgets/form.dart)
I/flutter ( 9291): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 9291): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 9291): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 9291): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 9291): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 9291): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 9291): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 9291): #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 9291): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 9291): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 9291): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 9291): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 9291): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 9291): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 9291): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 9291): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 9291): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 9291): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 9291): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 9291): #24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 9291): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 9291): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 9291): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9291): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9291): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9291): #30     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 9291): #31     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 9291): (elided 2 frames from class _AssertionError)
I/flutter ( 9291): ════════════════════════════════════════════════════════════════════════════════════════════════════

example.dart file

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class DropdownButtonFormFieldExample extends StatefulWidget {
  @override
  _DropdownButtonFormFieldExampleState createState() =>
      _DropdownButtonFormFieldExampleState();
}

class _DropdownButtonFormFieldExampleState
    extends State<DropdownButtonFormFieldExample> {
  final updateFormKey = GlobalKey<FormState>();
  DocumentSnapshot currentCategory;
  TextEditingController categoryController = new TextEditingController();
  String categoryname;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Dropdown Button'),),
          body: Container(
        child: Form(
          key: updateFormKey,
          child: Container(
            padding: EdgeInsets.all(8.0),
            child: ListView(
              children: <Widget>[
                Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    new StreamBuilder<QuerySnapshot>(
                        stream: Firestore.instance
                            .collection('categories')
                            .snapshots(),
                        builder: (BuildContext context,
                            AsyncSnapshot<QuerySnapshot> snapshot) {
                          if (snapshot.hasError) {
                            print(snapshot.error);
                          } else {
                            if (!snapshot.hasData) {
                              return Text('Loading...');
                            }

                            // currentCategory = snapshot.data.documents[0];
                            return Container(
                              padding: EdgeInsets.all(16.0),
                              decoration: new BoxDecoration(
                                color: Colors.grey[200],
                                borderRadius: BorderRadius.only(
                                  topLeft: Radius.circular(4.0),
                                  topRight: Radius.circular(4.0),
                                ),
                              ),
                              child: DropdownButtonHideUnderline(
                                child:
                                    new DropdownButtonFormField<DocumentSnapshot>(
                                  // value: currentCategory,

                                  value: currentCategory,

                                  onChanged: (DocumentSnapshot newValue) {
                                    setState(() {
                                      currentCategory = newValue;
                                    });
                                    print(currentCategory.data['name']);
                                  },
                                  validator: (currentCategory) {
                                    if (currentCategory == null) {
                                      return 'Category Not Selected';
                                    }
                                  },

                                  onSaved: (DocumentSnapshot newValue) {
                                    setState(() {
                                      currentCategory = newValue;
                                    });
                                    print(currentCategory.data);
                                  },
                                  hint: Text('Select Category'),
                                  items: snapshot.data.documents
                                      .map((DocumentSnapshot document) {
                                    return new DropdownMenuItem<DocumentSnapshot>(
                                        value: document,
                                        child: new Container(
                                          decoration: new BoxDecoration(
                                              borderRadius:
                                                  new BorderRadius.circular(5.0)),
                                          height: 100.0,
                                          padding: EdgeInsets.fromLTRB(
                                              10.0, 2.0, 10.0, 0.0),
                                          //color: primaryColor,
                                          child: new Text(
                                            document.data['name'],
                                          ),
                                        ));
                                  }).toList(),
                                ),
                              ),
                            );
                          }
                        }),
                    Padding(
                      padding: EdgeInsets.all(8.0),
                    ),
                    TextFormField(
                      controller: categoryController,
                      decoration: InputDecoration(
                          labelText: 'Category Name', filled: true),
                      validator: (input) {
                        if (input.isEmpty) {
                          return 'Category name can not be empty';
                        } else {
                          return null;
                        }
                      },
                      onSaved: (input) {
                        categoryname = input;
                      },
                    ),
                    Padding(
                      padding: EdgeInsets.all(8.0),
                    ),
                    Padding(
                      padding: EdgeInsets.all(8.0),
                    )
                  ],
                ),
                Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    Container(),
                  ],
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.29.1)
[√] Connected device (1 available)

• No issues found!

Kindly help me to resolve this issue soon.
Thanks in Advance.

**Comment by ketulrastogi** [comment]
But if I pass first item as currentCategory = snapshot.data.documents[0];
it does not update value after selecting different items.
it shows default value in dropdownbutton, not updated value.

**Comment by ketulrastogi** [comment]
just reproduce it and see output.
thanks

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jimshepherd** [comment]
I experience the same incorrect behavior in which the state of the DropdownButtonFormField is not updated when a new value is selected. I have created a pull request that fixes this issue.
#26132
