### ISSUE TITLE
App starts to black screen if it can't start observatory

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#2609]
This is a fairly bad UX problem, there's little feedback as to what is going wrong, and it's not clear that the thing that needs killing is on the device rather than on the desktop.

Could we adjust so that we opened observatory on a free port on the device rather than hanging?

### Steps to Reproduce
- Start an app on a device (Leave it running)
- Start a new project in Atom
- Start the new project => Black screen on the device

- kill both apps on the device
- restart app, now works

### Flutter Version

```
flutter --version
Flutter from https://github.com/flutter/flutter.git (on alpha)
Framework: 2fe456bf957d5df792b716599aa6f21d98997228 (8 days ago)
Engine:    d474e9d2b60a9cb111c09844c10081b68bde9252
```

### Logs

```
Showing Nexus 7 logs:
--------- beginning of main
I/flutter : Could not start Observatory HTTP server:
I/flutter : SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 8181
I/flutter : #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:494)
I/flutter : #1      _RootZone.runUnary (dart:async/zone.dart:1137)
I/flutter : #2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
I/flutter : #3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
I/flutter : #4      _Future._completeWithValue (dart:async/future_impl.dart:424)
I/flutter : #5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
I/flutter : #6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
I/flutter : #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
I/flutter : #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
I/flutter : #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
I/flutter : #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
I/flutter : 
--------- beginning of system
```

**Comment by eseidelGoogle** [comment]
This is actually a pretty common report. :(  I believe @johnmccutchan has a plan in https://github.com/flutter/flutter/issues/1988
