### ISSUE TITLE
The system cannot find the path specified and exited abnormally in flutter

### ISSUE THREAD

**Issue by verianggoro** [flutter/flutter#26136]
I want to run my first application with flutter but there is an error like this

## command

flutter run

## exception

```
ProcessException: ProcessException: Process "C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android\gradlew.bat" exited abnormally:
```
```
------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
OS:           Windows 10 10.0 amd64


The system cannot find the path specified.
  Command: C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android\gradlew.bat -v
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:185:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:166:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
````
how to fix it ??

**Comment by verianggoro** [comment]
when I run it on an android studio there is an error like this
`The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Launching lib\main.dart on Redmi Note 3 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android\gradlew.bat" exited abnormally:

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
OS:           Windows 10 10.0 amd64


The system cannot find the path specified.
  Command: C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android\gradlew.bat -v`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by verianggoro** [comment]
```C:\Users\IT20\AndroidStudioProjects\flutter_app_first>flutter doctor -v
The system cannot find the path specified.
The system cannot find the path specified.
[√] Flutter (Channel master, v1.1.6-pre.36, on Windows, locale id-ID)
    • Flutter version 1.1.6-pre.36 at D:\src\flutter
    • Framework revision 2e883f8552 (7 hours ago), 2019-01-06 16:38:13 -0800
    • Engine revision 716185fb79
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\IT20\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • sdk • emulator-5554 • android-arm • Android 4.4.2 (API 19) (emulator)

• No issues found!```


This is ouput of ```flutter doctor -v```

**Comment by kangwang1988** [comment]
@verianggoro 
Please paste the file names for folder "C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android" recursively.

**Comment by verianggoro** [comment]
which subfolder ? flutter sdk ?

**Comment by kangwang1988** [comment]
@verianggoro 
No, just subfolders(recursively) for your flutterproject/android directory.

**Comment by verianggoro** [comment]
```@if "%DEBUG%" == "" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%" == "0" goto init

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto init

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail

:init
@rem Get command-line arguments, handling Windowz variants

if not "%OS%" == "Windows_NT" goto win9xME_args
if "%@eval[2+2]" == "4" goto 4NT_args

:win9xME_args
@rem Slurp the command line arguments.
set CMD_LINE_ARGS=
set _SKIP=2

:win9xME_args_slurp
if "x%~1" == "x" goto execute

set CMD_LINE_ARGS=%*
goto execute

:4NT_args
@rem Get arguments from the 4NT Shell from JP Software
set CMD_LINE_ARGS=%$

:execute
@rem Setup the command line

set CLASSPATH=C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android

@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.launcher.GradleMain %CMD_LINE_ARGS%

:end
@rem End local scope for the variables with windows NT shell
if "%ERRORLEVEL%"=="0" goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
if  not "" == "%GRADLE_EXIT_CONSOLE%" exit 1
exit /b 1

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
```

This is file gradlew.bat

**Comment by kangwang1988** [comment]
@verianggoro 
Thanks. The gradlew.bat seems fine.
Can you try `flutter -v doctor -v` and give the whole log here.

**Comment by verianggoro** [comment]
```The system cannot find the path specified.
The system cannot find the path specified.
[  +52 ms] executing: [D:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/stable
[   +1 ms] executing: [D:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] executing: [D:\src\flutter\] git ls-remote --get-url origin
[  +58 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [D:\src\flutter\] git log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +1 ms] executing: [D:\src\flutter\] git log -n 1 --pretty=format:%ar
[  +48 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 6 weeks ago
[   +2 ms] executing: [D:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +50 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.0.0-0-g5391447
[ +783 ms] java -version
[ +275 ms] [√] Flutter (Channel stable, v1.0.0, on Windows, locale id-ID)
[   +4 ms]     • Flutter version 1.0.0 at D:\src\flutter
[   +1 ms]     • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
[   +1 ms]     • Engine revision 7375a0f414
[   +2 ms]     • Dart version 2.1.0
-[   +4 ms] executing: D:\android-sdk\platform-tools\adb devices -l
[  +26 ms] Exit code 0 from: D:\android-sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk model:sdk device:generic transport_id:2
[  +23 ms] D:\android-sdk\platform-tools\adb -s emulator-5554 shell getprop                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |[ +227 ms] executing: D:\android-sdk\tools\bin\sdkmanager --licenses                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   -[ +217 ms] ro.hardware = goldfish                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [+2673 ms] [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[   +2 ms]     • Android SDK at D:\android-sdk
[   +1 ms]     • Android NDK location not configured (optional; useful for native profiling support)
[   +2 ms]     • Platform android-28, build-tools 28.0.3
[   +1 ms]     • ANDROID_HOME = D:\android-sdk
[   +2 ms]     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
[   +1 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
[   +1 ms]     • All Android licenses accepted.
[   +2 ms] [√] Android Studio (version 3.0)
[   +1 ms]     • Android Studio at C:\Program Files\Android\Android Studio
[   +2 ms]     • Flutter plugin version 23.2.1
[   +1 ms]     • Dart plugin version 171.4424
[   +1 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
[   +1 ms] [√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[   +1 ms]     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
[   +3 ms]     • Flutter plugin version 31.3.3
[   +1 ms]     • Dart plugin version 182.5124
[   +2 ms] [√] VS Code (version 1.30.1)
[   +1 ms]     • VS Code at C:\Users\IT20\AppData\Local\Programs\Microsoft VS Code
[   +1 ms]     • Flutter extension version 2.21.1
[   +3 ms] [√] Connected device (1 available)
[   +1 ms]     • sdk • emulator-5554 • android-arm • Android 4.4.2 (API 19) (emulator)
[   +1 ms] • No issues found!
[  +15 ms] "flutter doctor" took 4.162ms.```

this output    ```flutter -v doctor -v```

**Comment by kangwang1988** [comment]
@verianggoro 
Got it. flutter doctor seems fine.
Now please run
```
cd C:\Users\IT20\AndroidStudioProjects\flutter_app_first\android
./gradlew.bat -v
```
and paste the result here.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by sslp** [comment]
Exact same issue on my end.

`C:\Users\USERNAME\flutter_app\android>gradlew.bat -v

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Windows 10 10.0 amd64`

**Comment by sslp** [comment]
Resolved.

**Comment by sslp** [comment]
Resolved by looking at what path cannont be found using Process Monitor.

**Comment by abcnow** [comment]
I am having the same problem on windows.. I already added the path into the environment but it keeps telling me that 

D:\flutter>flutter doctor
The system cannot find the path specified.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.915], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by DyaryRaoof** [comment]
in my case, I had a & sign in the name of the folder that I had put in the flutter project. removing it solved the problem for me.

**Comment by Iampato** [comment]
The same issue over here any solutions ?
