### ISSUE TITLE
* Error running Gradle

### ISSUE THREAD

**Issue by a7me63azzab** [flutter/flutter#26145]
## Please save us with the final release of [google_maps_flutter]

1. i want to get lat and long on touch event from google map 
2. first i try google_maps_flutter in my app but i found that what i need not supported yet in this package
3. so i install another package [map_view] after i found what i need  
```dart
mapView.onMapTapped
     .listen((location) => print("Touched location $location"));
mapView.onMapLongTapped
     .listen((location) => print("Long tapped location $location"));
```
4. After running the app , i get below error

## After running this command , the issue appear

> flutter run

## android/build.gradle
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

//---------------------

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}

```

## android/app/build.gradle

```gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}




//--------------------------
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.mazady"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        manifestPlaceholders = [
          onesignal_app_id: '99bdca37-cf47-4b16-b44a-6844741cbf86',
          // Project number pulled from dashboard, local value is ignored.
          onesignal_google_project_number: 'REMOTE'
      ]
      ndk{
          abiFilters "armeabi-v7a"
      }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'
    implementation 'com.android.support:appcompat-v7:28.0.3'
    implementation 'com.android.support:support-v4:28.0.3'
}

```

## Logs

```
[  +25 ms] executing: [/home/a7me63azza8/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/a7me63azza8/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/home/a7me63azza8/development/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/a7me63azza8/development/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/home/a7me63azza8/development/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[        ] executing: [/home/a7me63azza8/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[  +84 ms] executing: /home/a7me63azza8/Android/Sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /home/a7me63azza8/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ZH8002SYU4             device usb:2-1 product:D2302 model:D2302 device:D2302 transport_id:1
[ +187 ms] Found plugin geolocator at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/
[   +5 ms] Found plugin google_api_availability at
/home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-1.0.4/
[   +4 ms] Found plugin google_maps_flutter at
/home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.0.3+3/
[   +7 ms] Found plugin image_picker at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.4.10/
[   +6 ms] Found plugin map_view at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/map_view-0.0.14/
[   +4 ms] Found plugin onesignal at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/
[   +6 ms] Found plugin permission_handler at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/
[   +7 ms] Found plugin shared_preferences at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[ +102 ms] Found plugin geolocator at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-2.1.1/
[   +3 ms] Found plugin google_api_availability at
/home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_api_availability-1.0.4/
[   +2 ms] Found plugin google_maps_flutter at
/home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.0.3+3/
[   +4 ms] Found plugin image_picker at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.4.10/
[  +11 ms] Found plugin map_view at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/map_view-0.0.14/
[   +3 ms] Found plugin onesignal at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/
[   +3 ms] Found plugin permission_handler at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-2.1.2/
[   +5 ms] Found plugin shared_preferences at /home/a7me63azza8/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +57 ms] /home/a7me63azza8/Android/Sdk/platform-tools/adb -s ZH8002SYU4 shell getprop
[ +235 ms] ro.hardware = qcom
[ +862 ms] Launching lib/main.dart on D2302 in debug mode...
[  +29 ms] Initializing gradle...
[  +17 ms] Using gradle from /home/a7me63azza8/flutter_works/mazady/android/gradlew.
[  +84 ms] executing: /home/a7me63azza8/flutter_works/mazady/android/gradlew -v
[ +773 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Linux 4.15.0-43-generic amd64
[        ] Initializing gradle... (completed)
[        ] Resolving dependencies...
[        ] executing: [/home/a7me63azza8/flutter_works/mazady/android/] /home/a7me63azza8/flutter_works/mazady/android/gradlew app:properties
[+58700 ms] 
                     > Configure project :onesignal
                     WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
                     It will be removed at the end of 2018. For more information see:
                     http://d.android.com/r/tools/update-dependency-configurations.html

                     > Configure project :map_view
                     WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version
                     (28.0.3) for Android Gradle Plugin 3.2.1.
                     Android SDK Build Tools 28.0.3 will be used.
                     To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android
                     Gradle Plugin now has a default version of the build tools.

                     > Configure project :geolocator
                     WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version
                     (28.0.3) for Android Gradle Plugin 3.2.1.
                     Android SDK Build Tools 28.0.3 will be used.
                     To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android
                     Gradle Plugin now has a default version of the build tools.


                     FAILURE: Build failed with an exception.

                     * What went wrong:
                     The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'android' is using version
                     1.1.2-4.

                     * Try:
                     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
                     --scan to get full insights.

                     * Get more help at https://help.gradle.org

                     BUILD FAILED in 58s
[   +3 ms] Resolving dependencies... (completed)
[   +3 ms] * Error running Gradle:
           ProcessException: Process "/home/a7me63azza8/flutter_works/mazady/android/gradlew" exited abnormally:
           
           > Configure project :onesignal
           WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
           It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
           
           > Configure project :map_view
           WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for
Android
           Gradle Plugin 3.2.1.
           Android SDK Build Tools 28.0.3 will be used.
           To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle
Plugin now has a
           default version of the build tools.
           
           > Configure project :geolocator
           WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for
Android
           Gradle Plugin 3.2.1.
           Android SDK Build Tools 28.0.3 will be used.
           To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle
Plugin now has a
           default version of the build tools.
           
           
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'android' is using version 1.1.2-4.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full
           insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 58s
             Command: /home/a7me63azza8/flutter_works/mazady/android/gradlew app:properties
           
[  +13 ms] "flutter run" took 61,189ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

## dependencies:
```yml
 cupertino_icons: ^0.1.2
  map_view: ^0.0.14
  scoped_model: ^1.0.1
  shared_preferences: ^0.4.3
  image_picker: ^0.4.10
  fluro: ^1.4.0
  http: ^0.12.0
  geolocator: ^2.1.1
  carousel_pro: ^0.0.13
  onesignal: ^1.0.3
  flutter_datetime_picker: ^1.0.6
  dio: ^1.0.13
  timeago: ^2.0.10
  mime: ^0.9.6+2
```

## flutter analyze
```
Analyzing mazady...                                              
No issues found! (ran in 2.8s)

```

## flutter doctor -v
```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/a7me63azza8/development/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/a7me63azza8/Android/Sdk
    • Android NDK at /home/a7me63azza8/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/a7me63azza8/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • D2302 • ZH8002SYU4 • android-arm • Android 5.1.1 (API 22)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like 

>            The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'android' is using version 1.1.2-4.

is the main cause.

**Comment by a7me63azzab** [comment]
Hello, @zoechi  thanks for your response , yeah i agree with you coz after i installed map_view package and add this dependency 
```
 classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4'
```
to build.gradle and after running  the error appear

**Comment by zoechi** [comment]
Any reason why you add `1.1.2-4` and not `1.2.51` as the error message requests?

**Comment by a7me63azzab** [comment]
@zoechi  first i  try 1.1.2-4 , then i try 1.2.51 and get the same error

**Comment by zoechi** [comment]
Then please report the issue in the `map_view` repo so that they release an updated version.

I'm going to close because I don't think this is caused by Flutter.

**Comment by a7me63azzab** [comment]
ok, thanks , I know that its a map_view issue , and i go to their repo and found this 
![map error](https://user-images.githubusercontent.com/13996786/50758860-10d9fc00-126c-11e9-9526-58124a668923.png)
So i came here to ask if i can use google_maps_flutter to get lat and long on touch event from google map or not ?
That what i want to do ? Get location in response to user touch events ???

And Thank you for your interest .

**Comment by zoechi** [comment]
You can fork map_view plugin and fix it yourself until google_maps_flutter provides what you need.
