### ISSUE TITLE
clip_test.dart flaky

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#26316]
The following test failure was [seen on Cirrus](https://cirrus-ci.com/task/5249093725061120) and passed with a re-run:

```
09:50 +2276 ~34: /private/tmp/flutter sdk/packages/flutter/test/widgets/clip_test.dart: PhysicalShape painting with Clip.antiAliasWithSaveLayer                                                        
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TimeoutException was thrown running a test:
TimeoutException after 0:00:13.500000: The test exceeded the timeout. It may have hung.
Consider using "addTime" to increase the timeout before expensive operations.
When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._checkTimeout (package:flutter_test/src/binding.dart:833:25)
#16     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#17     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
#22     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:883:27)
#23     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#24     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
#27     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:0:0)
#28     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:249:15)
#34     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:398:11)
(elided 24 frames from package dart:async and package stack_trace)
The test description was:
PhysicalShape painting with Clip.antiAliasWithSaveLayer
```

**Comment by goderbauer** [comment]
This is a golden test, we have chanced the way these tests execute and as far as I know we haven't seen this flake in a very long time. Please re-open (with a new stack trace) if somebody still sees this.
