### ISSUE TITLE
'Xcode build done' but then nothing happens if bundle identifier contains a dash

### ISSUE THREAD

**Issue by robin7331** [flutter/flutter#26357]
## Steps to Reproduce

1. Write any Flutter code (did not find that this issue is related to my code) 
2. Press F5 or 'flutter run' (I am using VSCode)
3. Output seems to build the XCode Projekt but the App is not launched on my Simulator or actual iPhone X

Sometimes when this happens and I switch the device (so from the iPhone to the simulator) it works.
But I cannot reproduce this issue with a concrete set of steps. It just happens all the time..
I get no errors what so ever. 

Sometimes it just works fine.

Any Ideas? :/
Thanks!

## Logs

This is the output of ```flutter run```

```
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                       1.5s
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.7s

 └─Compiling, linking and signing...                 22.1s

Xcode build done.                                           25.4s
27.3s
```

This is the output when I press F5
``` 
Launching lib/main.dart on iPhone XR in debug mode...
Xcode build done.                                           23.2s
``` 

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-DE)
    • Flutter version 1.0.0 at /usr/local/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone XR • E8322A0F-3A55-46F6-9756-8CBB4937C540 • ios • iOS 12.1 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by tudor07** [comment]
What device do you have selected in VSCode in the bar at the bottom ?

**Comment by robin7331** [comment]
Currently its ``` iPhone XR (ios emulator) ```

**Comment by zoechi** [comment]
@DanTup 

I experienced similar behavior frequently recently with IntelliJ/Android but another click on "Debug" usually launches the app.

**Comment by DanTup** [comment]
@robin7331 Can you repro from the terminal at all? If so, running `flutter run -v` may help track down where it's stalling. If not, in VS Code you can try running the `Dart: Capture Logs` command (tick only `Flutter Run`) and reproduce to get some logs.

**Comment by robin7331** [comment]
Note: The ```flutter run``` command executes to this point and then halts for a couple of minutes before it fails: ```executing: /usr/bin/xcrun simctl launch 06C215B6-E9EA-47D2-9D3F-E4AAABAA8C1D "de.falkemedia.flutter-test" --enable-dart-profiling --enable-checked-mode--observatory-port=0``` 

Since the previous command successfully installed the App onto my Simulators Homescreen I am able to Tap on it.
If I do that the App starts and even produces Debug Output. Hot-Reloading is not working though. After a couple of minutes it finally still crashes with this output:

```
[+4364 ms] executing: /usr/bin/xcrun simctl install 06C215B6-E9EA-47D2-9D3F-E4AAABAA8C1D /Users/robin/Documents/Privat/flutter_tutorial/build/ios/iphonesimulator/Runner.app
[+3459 ms] executing: /usr/bin/xcrun simctl launch 06C215B6-E9EA-47D2-9D3F-E4AAABAA8C1D "de.falkemedia.flutter-test" --enable-dart-profiling --enable-checked-mode--observatory-port=0

NOTE: It was stuck here. Then I tapped on the homescreen icon of the App.

[+72372 ms] [DEVICE LOG] 2019-01-11 14:05:16.948305+0100  localhost Runner[6768]: (libMobileGestalt.dylib) libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
[        ] [DEVICE LOG] 2019-01-11 14:05:16.948360+0100  localhost Runner[6768]: (libMobileGestalt.dylib) MGIsDeviceOneOfType is not supported on this platform.
[   +2 ms] [DEVICE LOG] 2019-01-11 14:05:16.954242+0100  localhost Runner[6768]: (libAccessibility.dylib) [com.apple.Accessibility:AccessibilitySupport] Retrieving resting unlock: 0
[ +196 ms] [DEVICE LOG] 2019-01-11 14:05:17.150538+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13600, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.150764+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13601, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.150913+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13602, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.151223+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13603, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.151400+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13604, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.151591+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13605, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.151833+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13606, Description: Updating Key-Value Observers Of Preferences
[ +207 ms] [DEVICE LOG] 2019-01-11 14:05:17.358981+0100  localhost Runner[6768]: (FrontBoardServices) [com.apple.BackBoard:Display] [FBSDisplaySource 1-1] silently connecting <FBSDisplayConfiguration: 0x600001696920; Main; mode: "768x1024@2x 60Hz p3 SDR">
[        ] [DEVICE LOG] 2019-01-11 14:05:17.359057+0100  localhost Runner[6768]: (FrontBoardServices) [com.apple.BackBoard:Display] [FBSDisplaySource 1-1] initialized <FBSDisplayConfiguration: 0x600001696920; Main; mode: "768x1024@2x 60Hz p3 SDR">
[   +3 ms] [DEVICE LOG] 2019-01-11 14:05:17.362887+0100  localhost Runner[6768]: (AXMediaUtilities) [com.apple.Accessibility:AXMediaCommon] Unable to look up screen scale
[        ] [DEVICE LOG] 2019-01-11 14:05:17.362926+0100  localhost Runner[6768]: (AXMediaUtilities) [com.apple.Accessibility:AXMediaCommon] Unexpected physical screen orientation
[  +26 ms] [DEVICE LOG] 2019-01-11 14:05:17.387829+0100  localhost Runner[6768]: (AXMediaUtilities) [com.apple.Accessibility:AXMediaCommon] Unable to look up screen scale
[   +3 ms] [DEVICE LOG] 2019-01-11 14:05:17.392474+0100  localhost Runner[6768]: (AXMediaUtilities) [com.apple.Accessibility:AXMediaCommon] Unable to look up screen scale
[        ] [DEVICE LOG] 2019-01-11 14:05:17.392518+0100  localhost Runner[6768]: (AXMediaUtilities) [com.apple.Accessibility:AXMediaCommon] Unexpected physical screen orientation
[   +9 ms] [DEVICE LOG] 2019-01-11 14:05:17.403686+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13607, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.403899+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13608, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.404073+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x13609, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.404392+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x1360a, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.404604+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x1360b, Description: Updating Key-Value Observers Of Preferences
[        ] [DEVICE LOG] 2019-01-11 14:05:17.404894+0100  localhost Runner[6768]: (Runner) Created Activity ID: 0x1360c, Description: Updating Key-Value Observers Of Preferences
[ +245 ms] [DEVICE LOG] 2019-01-11 14:05:17.650830+0100  localhost Runner[6768]: (UIKitCore) You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
[        ] [DEVICE LOG] 2019-01-11 14:05:17.651012+0100  localhost Runner[6768]: (UIKitCore) You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
[  +93 ms] [DEVICE LOG] 2019-01-11 14:05:17.744350+0100  localhost Runner[6768]: (Flutter) flutter: Observatory listening on http://127.0.0.1:50950/
[   +5 ms] Observatory URL on device: http://127.0.0.1:50950/
[ +295 ms] [DEVICE LOG] 2019-01-11 14:05:18.045727+0100  localhost Runner[6768]: (Flutter) flutter: Product Manager Widget Constructor
[        ] flutter: Product Manager Widget Constructor
[ +168 ms] [DEVICE LOG] 2019-01-11 14:05:18.214534+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Will reevaluate codeitems and load any needed ax code items now
[        ] [DEVICE LOG] 2019-01-11 14:05:18.215272+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] found 13 axbundle(s)requiring load
[ +107 ms] [DEVICE LOG] 2019-01-11 14:05:18.322673+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Finished loading ax code items
[  +68 ms] [DEVICE LOG] 2019-01-11 14:05:18.390865+0100  localhost Runner[6768]: (Flutter) flutter: Product Manager Widget createState()
[        ] flutter: Product Manager Widget createState()
[        ] [DEVICE LOG] 2019-01-11 14:05:18.391205+0100  localhost Runner[6768]: (Flutter) flutter: Product Manager State initState()
[        ] flutter: Product Manager State initState()
[  +32 ms] [DEVICE LOG] 2019-01-11 14:05:18.424388+0100  localhost Runner[6768]: (Flutter) flutter: Product Manager State build()
[        ] flutter: Product Manager State build()
[        ] [DEVICE LOG] 2019-01-11 14:05:18.424590+0100  localhost Runner[6768]: (Flutter) flutter: Products Widget Constructor
[        ] flutter: Products Widget Constructor
[        ] [DEVICE LOG] 2019-01-11 14:05:18.425398+0100  localhost Runner[6768]: (Flutter) flutter: Products Widget Build
[        ] flutter: Products Widget Build
[ +197 ms] [DEVICE LOG] 2019-01-11 14:05:18.622395+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Will reevaluate codeitems and load any needed ax code items now
[        ] [DEVICE LOG] 2019-01-11 14:05:18.622610+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] found 0 axbundle(s) requiring load
[        ] [DEVICE LOG] 2019-01-11 14:05:18.623462+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Finished loading ax code items
[ +353 ms] [DEVICE LOG] 2019-01-11 14:05:18.975833+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Will reevaluate codeitems and load any needed ax code items now
[        ] [DEVICE LOG] 2019-01-11 14:05:18.976016+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] found 0 axbundle(s) requiring load
[        ] [DEVICE LOG] 2019-01-11 14:05:18.976073+0100  localhost Runner[6768]: (AccessibilityUtilities) [com.apple.Accessibility:AXLoading] Finished loading ax code items
[   +1 ms] ProcessException: Process "/usr/bin/xcrun" exited abnormally:
           "de.falkemedia.flutter-test": -1

           An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
           The request to open ""de.falkemedia.flutter-test"" failed.
           The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard").
           Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
                The operation couldn’t be completed. Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
                Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
             Command: /usr/bin/xcrun simctl launch 06C215B6-E9EA-47D2-9D3F-E4AAABAA8C1D "de.falkemedia.flutter-test" --enable-dart-profiling --enable-checked-mode--observatory-port=0
[   +2 ms] Error launching application on iPad Pro (9.7-inch).

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

[+47195 ms] "de.falkemedia.flutter-test": -1

            An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
            The request to open ""de.falkemedia.flutter-test"" failed.
            The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard").
            Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
                The operation couldn’t be completed. Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
                Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
[   +5 ms] "flutter run" took 165,325ms.
```

**Comment by robin7331** [comment]
Another Note: 

In both cases the resulting error seems to be the same:

```
[+130046 ms] "de.falkemedia.flutter-test": -1

             An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
             The request to open ""de.falkemedia.flutter-test"" failed.
             The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard").
             Underlying error (domain=FBSOpenApplicationErrorDomain, code=4):
             	The operation couldn’t be completed. Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
             	Application ""de.falkemedia.flutter-test"" is unknown to FrontBoard.
```

**Comment by DanTup** [comment]
How certain are you that it's fixed? In [the Apple](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1) docs it says:

> This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.

Which suggests the hyphen should be allowed 🤔

**Comment by robin7331** [comment]
I had not a single issue like that since I changed the identifier.
So I guess that was the problem.

**Comment by itbrauerei** [comment]
@DanTup I have the same problem and can also confirm that the dash in die bundle identifier is the issue. Starting the App directly from xcode works as expected.
Since I would like to migrate an existing App (with dash), removing the dash from the identifier is not working for me.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)
• No issues found!

**Comment by kangwang1988** [comment]
@robin7331 
<img width="1395" alt="screen shot 2019-02-03 at 11 42 12 pm" src="https://user-images.githubusercontent.com/817851/52178778-5e1aa080-280d-11e9-868d-92bdc88a7c04.png">

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html

>The UTI Character Set
A uniform type identifier is a Unicode string that usually contains characters in the ASCII character set. However, only a subset of the ASCII characters are permitted. You may use the Roman alphabet in upper and lower case (A–Z, a–z), the digits 0 through 9, the dot (“.”), and the hyphen (“-”). This restriction is based on DNS name restrictions, set forth in RFC 1035.

Uniform type identifiers may also contain any of the Unicode characters greater than U+007F.

**Comment by zoechi** [comment]
The regexp doesn't exclude `-` https://github.com/flutter/flutter/pull/26300/files 
Can you please check with latest `master`, perhaps #26300 affects this issue as well.

**Comment by itbrauerei** [comment]
Hi, great work, thanks!
With the latest master everything works as expected, incl. starting, stopping and hot reloading.

**Comment by zoechi** [comment]
@robin7331 can you confirm?

**Comment by robin7331** [comment]
@zoechi Jep. Just updated flutter, created a new project with a dash in its bundle identifier and it works fine. Thanks to all involved in this issue!
