### ISSUE TITLE
Flutter log, works on iOS but not Android

### ISSUE THREAD

**Issue by huntbeat** [flutter/flutter#26363]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter run
```
## exception
```
ProcessException: ProcessException: Process "/home/hunter/Android/Sdk/platform-tools/adb" exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hive/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.hive/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) } from null (pid=23116, uid=2000) not exported from uid 10197

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.hive/com.apptreesoftware.barcodescan.BarcodeScannerActivity (has extras) } from null (pid=23116, uid=2000) not exported from uid 10197
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1793)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:844)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:573)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1250)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:515)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5930)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5904)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:483)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:165)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:17929)
	at android.os.Binder.shellCommand(Binder.java:655)
	at android.os.Binder.onTransact(Binder.java:553)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3540)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3819)
	at android.os.Binder.execTransact(Binder.java:752)
  Command: /home/hunter/Android/Sdk/platform-tools/adb -s 1207ea0b shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.hive/com.apptreesoftware.barcodescan.BarcodeScannerActivity
```

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:441:34)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._complete (dart:async/future_impl.dart:476:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /usr/local/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/hunter/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/hunter/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 1207ea0b • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by wouterhardeman** [comment]
It appears you have not configured the permissions in the AndroidManifest.xml. Take a look at the Getting Started guide here: https://github.com/apptreesoftware/flutter_barcode_reader#getting-started

**Comment by huntbeat** [comment]
Thank you!

**Comment by huntbeat** [comment]
Still getting the same error for some reason. I have changed
AndroidManifest, the build.gradle files, installed kotlin via Android
Studio, and ran flutter packages get. What else should I check?

**Comment by wouterhardeman** [comment]
This fix might help: https://github.com/apptreesoftware/flutter_barcode_reader/issues/41#issuecomment-421316199

**Comment by huntbeat** [comment]
Never mind, fixed my mistake. I appreciate the quick help!

**Comment by zoechi** [comment]
Looks like a support request that was solved. Thanks @wouterhardeman.
