### ISSUE TITLE
 Localizations return always English on android

### ISSUE THREAD

**Issue by ammar-esrawi** [flutter/flutter#26382]
`Localizations.localeOf(context);` always return **en_**  in my Android device, but the device language is Arabic , the device run on Android 6.0.1

**Comment by kangwang1988** [comment]
@ammar-esrawi 
`flutter doctor -v` please.
Besides, minimal demo project which can help reproduce this issue would be helpful.

**Comment by ammar-esrawi** [comment]
@kangwang1988 
kindly find the requested info and feel free to request any other info 

```
C:\flutter\flutter_framework\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\flutter\flutter_framework
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:/android/sdk/new
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/android/sdk/new
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 32-bit edition
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • ASUS Z00ED • F8AZCY18L950 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
Process finished with exit code 0
```

the demo app
```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    Locale myLocale = Localizations.localeOf(context);
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              myLocale.toString(),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by ammar-esrawi** [comment]
another situation related to the localization present here once you call the function from the application context it generates an exception please check the following 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    Locale myLocale = Localizations.localeOf(context);////////////////////the change is here 
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title:  myLocale.toString()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
             "not important",
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
 
```

the generated log is

```
Launching lib\main.dart on ASUS Z00ED in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/flutter (26358): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (26358): The following assertion was thrown building MyApp(dirty):
I/flutter (26358): a Localizations ancestor was not found
I/flutter (26358): 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 417 pos 12: 'scope != null'
I/flutter (26358): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (26358): more information in this error message to help you determine and fix the underlying cause.
I/flutter (26358): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (26358):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (26358): When the exception was thrown, this was the stack:
I/flutter (26358): #2      Localizations.localeOf (package:flutter/src/widgets/localizations.dart:417:12)
I/flutter (26358): #3      MyApp.build (package:i18n_test/main.dart:9:37)
I/flutter (26358): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter (26358): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (26358): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (26358): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (26358): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (26358): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (26358): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (26358): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
I/flutter (26358): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
I/flutter (26358): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
I/flutter (26358): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (26358): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
I/flutter (26358): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
I/flutter (26358): #17     runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter (26358): #18     main (package:i18n_test/main.dart:3:16)
I/flutter (26358): #19     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter (26358): #20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (26358): (elided 2 frames from class _AssertionError)
I/flutter (26358): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device ASUS Z00ED...

```

**Comment by zoechi** [comment]
>  in my Android device

Have you tried anything else like Android emulator, other Android device, iOS device, iOS simulator?

**Comment by ammar-esrawi** [comment]
@zoechi  the same on other devices

i have not try it in android emulators nor IOS (device and emulator )

**Comment by zoechi** [comment]
>     Locale myLocale = Localizations.localeOf(context);////////////////////the change is here 

> I/flutter (26358): 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 417 pos 12: 'scope != null'

This is expected behavior because this scope does not provide `Localizations`.
This is outside `MaterialApp` which provides it and only it's children can access it using `Localizations.of(...)`

**Comment by ammar-esrawi** [comment]
> This is expected behavior because this scope does not provide Localizations.
> This is outside MaterialApp which provides it and only it's children can access it using Localizations.of(...)

so what is the way to get the current device language in this level or if there are any way in the main() 

then we may use it to init a special implemented translation singleton  
thank you so much

**Comment by zoechi** [comment]
You need to list the locales you want to support
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      supportedLocales: [
        const Locale('en', 'US'), // English
        const Locale('he', 'IL'), // Hebrew
        const Locale('de', 'AT'), // Hebrew
        // ... other locales the app supports
      ],
      home: MyHomePage(title: ''),
    );
  }
}
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ammar-esrawi** [comment]
@zoechi  ok thank you for your time

**Comment by amreniouinnovent** [comment]
@zoechi what if I want to support font family based on the current language?
 `ThemeData(fontFamily: appLocaleFont)`
Is there any workaround for getting the app locale for setting the font family?

**Comment by deakjahn** [comment]
@amreniouinnovent the problem is that you're using a wrong context. You need to use a context one level below that. To to that, you might use the `builder` parameter of the `MaterialApp`, create your theme there and the context the builder passes will already be OK to get the locale. I found a blog describing just this here: https://medium.com/saugo360/flutter-different-fonts-for-different-locales-d190a89b58c

**Comment by deakjahn** [comment]
I stumbled upon another solution that doesn't involve a context:

    import 'dart:ui' as ui;
    Locale(ui.window.locale.languageCode, ui.window.locale.countryCode)

**Comment by amreniouinnovent** [comment]
@deakjahn Yes you are right ..I didn't know about the builder
Thanks a lot

**Comment by dark-chocolate** [comment]
@deakjahn I tried `builder` separately, your second solution separately, and both of them combined also, but every time it showed me `en` locale, tested in iOS real device and Simulator. 

```
    Builder( // used as body in Scaffold
      builder: (context2) {
        Locale(window.locale.languageCode, window.locale.countryCode);
        print("${Localizations.localeOf(context2)}");
        return Center();
      },
    )
```

**Comment by dipendra-sharma** [comment]
is there any solution for this?

**Comment by dipendra-sharma** [comment]
> import 'dart:ui' as ui;

is it working? I'm not getting correct locale in my iPhone 7. it's always en

**Comment by dark-chocolate** [comment]
I have created a new issue here for iOS. If anyone has some solution, you're most welcome!!!

https://github.com/flutter/flutter/issues/39230

**Comment by iassal** [comment]
> I stumbled upon another solution that doesn't involve a context:
> 
> ```
> import 'dart:ui' as ui;
> Locale(ui.window.locale.languageCode, ui.window.locale.countryCode)
> ```
Worth noting that there is a rare issue that happens in iOS https://github.com/flutter/flutter/issues/39032

**Comment by ershat-dl** [comment]
I think you should give value to `locale` property in `MaterialApp`.  
and then try `Localizations.localeOf(context)`.
