### ISSUE TITLE
Oops; flutter has exited unexpectedly

### ISSUE THREAD

**Issue by francovp** [flutter/flutter#26467]
## Steps to Reproduce

1. Executing any flutter command in the flutter_console.bat
```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 66ed647bd16b3197)
```

## Logs

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

FormatException: FormatException: Not a valid package name (at character 1)
dart# Generated by pub on 2019-01-12 12
^
```
```
#0      parse (package:package_config/packages_file.dart:57:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:14:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:35:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:39:5)
#4      FlutterCommandRunner._checkFlutterCopy (package:flutter_tools/src/runner/flutter_command_runner.dart:543:41)
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:374:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#14     new Future.sync (dart:async/future.dart:224:31)
#15     CommandRunner.run (package:args/command_runner.dart:111:11)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#27     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\Users\fvale\Repositorios\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\fvale\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Please post your `pubspec.yaml`

**Comment by francovp** [comment]
I'm trying to install the packages from the flutter_catalog example

```
name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.4.0+20

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.3
  fluttertoast: ^2.1.0
  english_words: ^3.1.3
  flutter_gallery_assets: ^0.1.6
  transparent_image:
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  firebase_storage: ^1.0.4
  firebase_analytics: ^1.0.6
  firebase_database: ^1.0.5
  cloud_firestore: ^0.8.2
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  image_picker: ^0.4.10
  flutter_webview_plugin: ^0.3.0
  firebase_ml_vision: ^0.2.0
  flutter_markdown: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

But I don't think is a problem of the project, because now I can't execute flutter commands from the flutter_console.bat in the flutter repo.

**Comment by zoechi** [comment]
This one https://github.com/X-Wei/flutter_catalog ?

**Comment by zoechi** [comment]
Can you please try to find out where the `.packages` file is that contains `dart# Generated by pub on 2019-01-12 12
^` (as 1st line)?

**Comment by francovp** [comment]
Is in the root directory of the project.

That's what you are asking for?

**Comment by kangwang1988** [comment]
@francovp 
Yes, .packages is located in the root directory for you flutter project.
Paste the content of .packages or delete .packages and run `flutter packages get` again to see if it works.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
