### ISSUE TITLE
flutter_auth: Exception on Android when linking phone number with email/password account

### ISSUE THREAD

**Issue by kika** [flutter/flutter#26477]
I'm using `0.7.0` with `AuthCredential` API. The code that causes the exception on Android (only) is this:
```dart
Future<String> verifyPhoneComplete(String code, String verifyId) {
    firebase.AuthCredential phoneCred =
      firebase.PhoneAuthProvider.getCredential(
        verificationId: verifyId,
        smsCode: code
      );
    return _auth.linkWithCredential(phoneCred).then((user) => user.uid);
```

Exception:
```
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): java.lang.IllegalArgumentException: Given String is empty or null
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at com.google.firebase.auth.EmailAuthProvider.getCredential(Unknown Source)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleLinkWithEmailAndPassword(FirebaseAuthPlugin.java:272)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:122)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/MethodChannel#plugins.flutter.io/firebase_auth( 1893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

`flutter doctor -v`:
```
[✓] Flutter (Channel dev, v1.1.8, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.1.8 at /Volumes/ExtStripe/Scratch/flutter
    • Framework revision 985ccb6d14 (4 days ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 5s                 • D0A87E46-DDD7-46CF-B400-B4A4799315FF • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by kika** [comment]
Here's the fix:
1. https://github.com/flutter/plugins/pull/980/commits/b26b2722283f072797a13586df91c7d74758d820
2. https://github.com/flutter/plugins/pull/1069

And you are GTG.

**Comment by collinjackson** [comment]
I believe that we fixed linkWithCredential on Android in firebase_auth 0.8.2 (flutter/plugins#1333)

If you're still seeing this please let me know by filing a new issue. Thanks!

**Comment by kroikie** [comment]
@kika

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/509. Any further collaboration will be done there.
