### ISSUE TITLE
There was a problem setting the global theme - 设置全局主题的时候出现了问题

### ISSUE THREAD

**Issue by AndromedaX7** [flutter/flutter#26486]
我用一个InheritedWidget 的实现类：GlobalThemeSetter 设置全局主题：
实现如下：
```dart
class GlobalThemeSetter extends InheritedWidget {
  GlobalThemeSetter({this.child, this.themeSetter}) : super(child: child);
  final ThemeDataFunction themeSetter;//typedef ThemeDataFunction = ThemeData Function(ThemeData theme);
  final Widget child;

  @override
  bool updateShouldNotify(InheritedWidget oldWidget) {
    return true;
  }

  static GlobalThemeSetter of(BuildContext context) {
    return context.inheritFromWidgetOfExactType(GlobalThemeSetter);
  }
}
```
下面是AppState 的内容：
```dart
class AppState extends State<App> {
  String initRoute = "/";
  PageFlag currentPage = PageFlag.Splash;

  ThemeData _theme = ThemeData(primaryColor: Colors.blue);

  @override
  Widget build(BuildContext context) {
    return GlobalThemeSetter(
      themeSetter: (theme) {
        setState(() {
          _theme = theme;
        });
      },
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'hello',
        theme: _theme,
        home:  Container(color:Theme.of(context).primaryColor)
      ),
    );
  }
```
当我调用
```dart
GlobalThemeSetter.of(context).themeSetter(Theme.of(contex).copyWith(
primaryColor:Colors.pink,
));
```
出现异常
如下是异常输出：
```
I/flutter (31136): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31136): The following assertion was thrown building AnimatedTheme(duration: 200ms, dirty, state:
I/flutter (31136): _AnimatedThemeState#c4ab9(ticker active, ThemeDataTween(ThemeData#66d96(buttonTheme:
I/flutter (31136): ButtonThemeData#f2cc2(buttonColor: Color(0xffe0e0e0), colorScheme: ColorScheme#f08c2(primary:
I/flutter (31136): MaterialColor(primary value: Color(0xff2196f3)), primaryVariant: Color(0xff1976d2), secondary:
I/flutter (31136): Color(0xff2196f3), secondaryVariant: Color(0xff1976d2), background: Color(0xff90caf9), error:
I/flutter (31136): Color(0xffd32f2f), onSecondary: Color(0xffffffff), onBackground: Color(0xffffffff)),
I/flutter (31136): materialTapTargetSize: MaterialTapTargetSize.padded), textTheme: TextTheme#204ed, primaryTextTheme:
I/flutter (31136): TextTheme#ef275(display4: TextStyle(debugLabel: whiteMountainView display4, inherit: true, color:
I/flutter (31136): Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), display3: TextStyle(debugLabel:
I/flutter (31136): whiteMountainView display3, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter (31136): TextDecoration.none), display2: TextStyle(debugLabel: whiteMountainView display2, inherit: true,
I/flutter (31136): color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), display1:
I/flutter (31136): TextStyle(debugLabel: whiteMountainView display1, inherit: true, color: Color(0xb3ffffff), family:
I/flutter (31136): Roboto, decoration: TextDecoration.none), headline: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): headline, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): title: TextStyle(debugLabel: whiteMountainView title, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), subhead: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): subhead, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): body2: TextStyle(debugLabel: whiteMountainView body2, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), body1: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): body1, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): caption: TextStyle(debugLabel: whiteMountainView caption, inherit: true, color: Color(0xb3ffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), button: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): button, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): subtitle): TextStyle(debugLabel: whiteMountainView subtitle, inherit: true, color:
I/flutter (31136): Color(0xffffffff), family: Roboto, decoration: TextDecoration.none), overline: TextStyle(debugLabel:
I/flutter (31136): whiteMountainView overline, inherit: true, color: Color(0xffffffff), family: Roboto, decoration:
I/flutter (31136): TextDecoration.none)), accentTextTheme: TextTheme#ef275(display4: TextStyle(debugLabel:
I/flutter (31136): whiteMountainView display4, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter (31136): TextDecoration.none), display3: TextStyle(debugLabel: whiteMountainView display3, inherit: true,
I/flutter (31136): color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), display2:
I/flutter (31136): TextStyle(debugLabel: whiteMountainView display2, inherit: true, color: Color(0xb3ffffff), family:
I/flutter (31136): Roboto, decoration: TextDecoration.none), display1: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): display1, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): headline: TextStyle(debugLabel: whiteMountainView headline, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), title: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): title, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): subhead: TextStyle(debugLabel: whiteMountainView subhead, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), body2: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): body2, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): body1: TextStyle(debugLabel: whiteMountainView body1, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), caption: TextStyle(debugLabel: whiteMountainView
I/flutter (31136): caption, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): button: TextStyle(debugLabel: whiteMountainView button, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none), subtitle): TextStyle(debugLabel: whiteMountainView
I/flutter (31136): subtitle, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter (31136): overline: TextStyle(debugLabel: whiteMountainView overline, inherit: true, color: Color(0xffffffff),
I/flutter (31136): family: Roboto, decoration: TextDecoration.none)), inputDecorationTheme: InputDecorationTheme#116d3,
I/flutter (31136): iconTheme: IconThemeData#2abdc(color: Color(0xdd000000)), primaryIconTheme:
I/flutter (31136): IconThemeData#15fa8(color: Color(0xffffffff)), accentIconTheme: IconThemeData#15fa8(color:
I/flutter (31136): Color(0xffffffff)), sliderTheme: SliderThemeData#9a6dc, tabBarTheme: TabBarTheme#12410, chipTheme:
I/flutter (31136): ChipThemeData#26231, materialTapTargetSize: MaterialTapTargetSize.padded, pageTransitionsTheme:
I/flutter (31136): PageTransitionsTheme#61687) → ThemeData#0093a(primaryColor: MaterialColor(primary value:
I/flutter (31136): Color(0xffe91e63)), buttonTheme: ButtonThemeData#f2cc2(buttonColor: Color(0xffe0e0e0), colorScheme:
I/flutter (31136): ColorScheme#f08c2(primary: MaterialColor(primary value: Color(0xff2196f3)), primaryVariant:
I/flutter (31136): Color(0xff1976d2), secondary: Color(0xff2196f3), secondaryVariant: Color(0xff1976d2), background:
I/flutter (31136): Color(0xff90caf9), error: Color(0xffd32f2f), onSecondary: Color(0xffffffff), onBackground:
I/flutter (31136): Color(0xffffffff)), materialTapTargetSize: MaterialTapTargetSize.padded), textTheme:
I/flutter (31136): TextTheme#b4029(display4: TextStyle(debugLabel: (englishLike display4 2014).merge(blackMountainView
I/flutter (31136): display4), inherit: false, color: Color(0x8a000000), family: Roboto, size: 112.0, weight: 100,
I/flutter (31136): baseline: alphabetic, decoration: TextDecoration.none), display3: TextStyle(debugLabel: (englishLike
I/flutter (31136): display3 2014).merge(blackMountainView display3), inherit: false, color: Color(0x8a000000), family:
I/flutter (31136): Roboto, size: 56.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), display2:
I/flutter (31136): TextStyle(debugLabel: (englishLike display2 2014).merge(blackMountainView display2), inherit: false,
I/flutter (31136): color: Color(0x8a000000), family: Roboto, size: 45.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), display1: TextStyle(debugLabel: (englishLike display1
I/flutter (31136): 2014).merge(blackMountainView display1), inherit: false, color: Color(0x8a000000), family: Roboto,
I/flutter (31136): size: 34.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), headline:
I/flutter (31136): TextStyle(debugLabel: (englishLike headline 2014).merge(blackMountainView headline), inherit: false,
I/flutter (31136): color: Color(0xdd000000), family: Roboto, size: 24.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), title: TextStyle(debugLabel: (englishLike title 2014).merge(blackMountainView
I/flutter (31136): title), inherit: false, color: Color(0xdd000000), family: Roboto, size: 20.0, weight: 500, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), subhead: TextStyle(debugLabel: (englishLike subhead
I/flutter (31136): 2014).merge(blackMountainView subhead), inherit: false, color: Color(0xdd000000), family: Roboto,
I/flutter (31136): size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), body2:
I/flutter (31136): TextStyle(debugLabel: (englishLike body2 2014).merge(blackMountainView body2), inherit: false,
I/flutter (31136): color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), body1: TextStyle(debugLabel: (englishLike body1 2014).merge(blackMountainView
I/flutter (31136): body1), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), caption: TextStyle(debugLabel: (englishLike caption
I/flutter (31136): 2014).merge(blackMountainView caption), inherit: false, color: Color(0x8a000000), family: Roboto,
I/flutter (31136): size: 12.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), button:
I/flutter (31136): TextStyle(debugLabel: (englishLike button 2014).merge(blackMountainView button), inherit: false,
I/flutter (31136): color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), subtitle): TextStyle(debugLabel: (englishLike subtitle
I/flutter (31136): 2014).merge(blackMountainView subtitle), inherit: false, color: Color(0xff000000), family: Roboto,
I/flutter (31136): size: 14.0, weight: 500, letterSpacing: 0.1, baseline: alphabetic, decoration: TextDecoration.none),
I/flutter (31136): overline: TextStyle(debugLabel: (englishLike overline 2014).merge(blackMountainView overline),
I/flutter (31136): inherit: false, color: Color(0xff000000), family: Roboto, size: 10.0, weight: 400, letterSpacing:
I/flutter (31136): 1.5, baseline: alphabetic, decoration: TextDecoration.none)), primaryTextTheme:
I/flutter (31136): TextTheme#5befd(display4: TextStyle(debugLabel: (englishLike display4 2014).merge(whiteMountainView
I/flutter (31136): display4), inherit: false, color: Color(0xb3ffffff), family: Roboto, size: 112.0, weight: 100,
I/flutter (31136): baseline: alphabetic, decoration: TextDecoration.none), display3: TextStyle(debugLabel: (englishLike
I/flutter (31136): display3 2014).merge(whiteMountainView display3), inherit: false, color: Color(0xb3ffffff), family:
I/flutter (31136): Roboto, size: 56.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), display2:
I/flutter (31136): TextStyle(debugLabel: (englishLike display2 2014).merge(whiteMountainView display2), inherit: false,
I/flutter (31136): color: Color(0xb3ffffff), family: Roboto, size: 45.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), display1: TextStyle(debugLabel: (englishLike display1
I/flutter (31136): 2014).merge(whiteMountainView display1), inherit: false, color: Color(0xb3ffffff), family: Roboto,
I/flutter (31136): size: 34.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), headline:
I/flutter (31136): TextStyle(debugLabel: (englishLike headline 2014).merge(whiteMountainView headline), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 24.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), title: TextStyle(debugLabel: (englishLike title 2014).merge(whiteMountainView
I/flutter (31136): title), inherit: false, color: Color(0xffffffff), family: Roboto, size: 20.0, weight: 500, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), subhead: TextStyle(debugLabel: (englishLike subhead
I/flutter (31136): 2014).merge(whiteMountainView subhead), inherit: false, color: Color(0xffffffff), family: Roboto,
I/flutter (31136): size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), body2:
I/flutter (31136): TextStyle(debugLabel: (englishLike body2 2014).merge(whiteMountainView body2), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), body1: TextStyle(debugLabel: (englishLike body1 2014).merge(whiteMountainView
I/flutter (31136): body1), inherit: false, color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 400, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), caption: TextStyle(debugLabel: (englishLike caption
I/flutter (31136): 2014).merge(whiteMountainView caption), inherit: false, color: Color(0xb3ffffff), family: Roboto,
I/flutter (31136): size: 12.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), button:
I/flutter (31136): TextStyle(debugLabel: (englishLike button 2014).merge(whiteMountainView button), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), subtitle): TextStyle(debugLabel: (englishLike subtitle
I/flutter (31136): 2014).merge(whiteMountainView subtitle), inherit: false, color: Color(0xffffffff), family: Roboto,
I/flutter (31136): size: 14.0, weight: 500, letterSpacing: 0.1, baseline: alphabetic, decoration: TextDecoration.none),
I/flutter (31136): overline: TextStyle(debugLabel: (englishLike overline 2014).merge(whiteMountainView overline),
I/flutter (31136): inherit: false, color: Color(0xffffffff), family: Roboto, size: 10.0, weight: 400, letterSpacing:
I/flutter (31136): 1.5, baseline: alphabetic, decoration: TextDecoration.none)), accentTextTheme:
I/flutter (31136): TextTheme#5befd(display4: TextStyle(debugLabel: (englishLike display4 2014).merge(whiteMountainView
I/flutter (31136): display4), inherit: false, color: Color(0xb3ffffff), family: Roboto, size: 112.0, weight: 100,
I/flutter (31136): baseline: alphabetic, decoration: TextDecoration.none), display3: TextStyle(debugLabel: (englishLike
I/flutter (31136): display3 2014).merge(whiteMountainView display3), inherit: false, color: Color(0xb3ffffff), family:
I/flutter (31136): Roboto, size: 56.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), display2:
I/flutter (31136): TextStyle(debugLabel: (englishLike display2 2014).merge(whiteMountainView display2), inherit: false,
I/flutter (31136): color: Color(0xb3ffffff), family: Roboto, size: 45.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), display1: TextStyle(debugLabel: (englishLike display1
I/flutter (31136): 2014).merge(whiteMountainView display1), inherit: false, color: Color(0xb3ffffff), family: Roboto,
I/flutter (31136): size: 34.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), headline:
I/flutter (31136): TextStyle(debugLabel: (englishLike headline 2014).merge(whiteMountainView headline), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 24.0, weight: 400, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), title: TextStyle(debugLabel: (englishLike title 2014).merge(whiteMountainView
I/flutter (31136): title), inherit: false, color: Color(0xffffffff), family: Roboto, size: 20.0, weight: 500, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), subhead: TextStyle(debugLabel: (englishLike subhead
I/flutter (31136): 2014).merge(whiteMountainView subhead), inherit: false, color: Color(0xffffffff), family: Roboto,
I/flutter (31136): size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), body2:
I/flutter (31136): TextStyle(debugLabel: (englishLike body2 2014).merge(whiteMountainView body2), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), body1: TextStyle(debugLabel: (englishLike body1 2014).merge(whiteMountainView
I/flutter (31136): body1), inherit: false, color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 400, baseline:
I/flutter (31136): alphabetic, decoration: TextDecoration.none), caption: TextStyle(debugLabel: (englishLike caption
I/flutter (31136): 2014).merge(whiteMountainView caption), inherit: false, color: Color(0xb3ffffff), family: Roboto,
I/flutter (31136): size: 12.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none), button:
I/flutter (31136): TextStyle(debugLabel: (englishLike button 2014).merge(whiteMountainView button), inherit: false,
I/flutter (31136): color: Color(0xffffffff), family: Roboto, size: 14.0, weight: 500, baseline: alphabetic, decoration:
I/flutter (31136): TextDecoration.none), subtitle): TextStyle(debugLabel: (englishLike subtitle
I/flutter (31136): 2014).merge(whiteMountainView subtitle), inherit: false, color: Color(0xffffffff), family: Roboto,
I/flutter (31136): size: 14.0, weight: 500, letterSpacing: 0.1, baseline: alphabetic, decoration: TextDecoration.none),
I/flutter (31136): overline: TextStyle(debugLabel: (englishLike overline 2014).merge(whiteMountainView overline),
I/flutter (31136): inherit: false, color: Color(0xffffffff), family: Roboto, size: 10.0, weight: 400, letterSpacing:
I/flutter (31136): 1.5, baseline: alphabetic, decoration: TextDecoration.none)), inputDecorationTheme:
I/flutter (31136): InputDecorationTheme#116d3, iconTheme: IconThemeData#2abdc(color: Color(0xdd000000)),
I/flutter (31136): primaryIconTheme: IconThemeData#15fa8(color: Color(0xffffffff)), accentIconTheme:
I/flutter (31136): IconThemeData#15fa8(color: Color(0xffffffff)), sliderTheme: SliderThemeData#9a6dc, tabBarTheme:
I/flutter (31136): TabBarTheme#12410, chipTheme: ChipThemeData#26231, materialTapTargetSize:
I/flutter (31136): MaterialTapTargetSize.padded, pageTransitionsTheme: PageTransitionsTheme#61687)))):
I/flutter (31136): 'package:flutter/src/painting/text_style.dart': Failed assertion: line 588 pos 12: 'a == null || b
I/flutter (31136): == null || a.inherit == b.inherit': is not true.
I/flutter (31136): 
I/flutter (31136): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31136): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31136): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31136):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (31136): 
I/flutter (31136): When the exception was thrown, this was the stack:
I/flutter (31136): #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:588:12)
I/flutter (31136): #3      TextTheme.lerp (package:flutter/src/material/text_theme.dart:466:27)
I/flutter (31136): #4      ThemeData.lerp (package:flutter/src/material/theme_data.dart:840:28)
I/flutter (31136): #5      ThemeDataTween.lerp (package:flutter/src/material/theme.dart:187:41)
I/flutter (31136): #6      Tween.transform (package:flutter/src/animation/tween.dart:260:12)
I/flutter (31136): #7      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
I/flutter (31136): #8      _AnimatedThemeState.build (package:flutter/src/material/theme.dart:250:19)
I/flutter (31136): #9      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (31136): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (31136): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (31136): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (31136): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (31136): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (31136): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (31136): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (31136): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (31136): #18     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (31136): #19     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (31136): (elided 2 frames from class _AssertionError)
I/flutter (31136): 
```

**Comment by kangwang1988** [comment]
@AndromedaX7 
Please create a minimal project(or main.dart) to help reproduce this issue would be much helpful.
Besides, please provide `flutter doctor -v` here.

**Comment by zoechi** [comment]
Looks similar to #19150

**Comment by JingLMalan** [comment]
Maybe you best use English to describe your issue benefits for developers to give a solution.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
