### ISSUE TITLE
Hot Restart doesn't work on second page

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [flutter/flutter#26491]
I have a very small app with two pages, main page and details page. Details page loads when I hit a button on the main page. The issue is when I change the colour of a button on the details page, Hot Reload or Hot Restart doesn't update the button. I need to do stop & start of the debugger.

**Comment by kangwang1988** [comment]
@Dhana-Krishnasamy 
Please provide a minimal demo to reproduce this issue.
Paster result for `flutter doctor -v` here besides.

**Comment by Dhana-Krishnasamy** [comment]
@kangwang1988 Here is the source which has this problem : `https://github.com/Dhana-Krishnasamy/flutter-sample`.
Steps to reproduce: After loading the app in iPhone X simulator, change color or text values in this page : `https://github.com/Dhana-Krishnasamy/flutter-sample/blob/master/lib/pages/product_details_page.dart#L26-L27`, the changes wont be visible even with `Hot Restart`. Editor used is VS Code

Here is `flutter doctor -v` output

> [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
>     • Flutter version 1.0.0 at /Users/Dhana/Projects/flutter/sdk/flutter
>     • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
>     • Engine revision 7375a0f414
>     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at /Users/Dhana/Library/Android/sdk
>     • Android NDK at /Users/Dhana/Library/Android/sdk/ndk-bundle
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [✓] Connected device (1 available)
>     • iPhone X • 28A00073-2A1F-4C2D-8D3A-22250F88FD3D • ios • iOS 12.1 (simulator)
> 
> • No issues found!


@zoechi As I mentioned earlier the page doesnt reflect the changes even with `Hot Restart`

**Comment by zoechi** [comment]
The app doesn't work for me on iOS

I only get 

![image](https://user-images.githubusercontent.com/405837/51085857-3f117d00-173f-11e9-8465-f4e3daecc545.png)


Fixing `import './pages//product_details_page.dart';` might help (double slash)

Hot reload changes work for me on Android.

**Comment by Dhana-Krishnasamy** [comment]
I have now removed the extra slash. Which version on android os and device did you use please so I could use the same?

**Comment by zoechi** [comment]
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-AT)
...
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```
Perhaps you could explain exactly what changes you made at what location to test hot-reload.
The link above doesn't point to a location for text or color values.

**Comment by Dhana-Krishnasamy** [comment]
I have tested it on Nexus 5 device with Android 6.0.1,  same behaviour that app doesnt reflect the changes unless I stop and start the debugger. I have now updated the link to point to two lines one is button Text and other is button Color.

Exact steps

1.  Start debugger from vs code (press F5)
2. Once the app loads, hit Add Product button to add a product
3. Hit Details button below the image, which will take you to the Product Details page where you will see the button in question.
4. On VS Code, open this file https://github.com/Dhana-Krishnasamy/flutter-sample/blob/master/lib/pages/product_details_page.dart#L25-L26,
5. At line #25, Button is text is DELETE, change it to DELETE ME in vs code. Save the changes.  
6. Open VS code command list (Cmd + shift + P)
7. Select 'Flutter: Hot Reload' , ( For me at this point app flashes quickly and Button still reads DELETE)
8. Hit back button on top left, and click Details button to recheck ( for me Button still reads DELETE)
9. Now Open VS code command list (Cmd + shift + P)
10. Select 'Flutter: Hot Restart' , app flushes to goes to first page with no products added.
11. Hit Add Product and Hit Details on the product ( on the product details page, for me, Button still reads DELETE)
12. Stop the debugger, app closes on the simulator 
13. Start the debugger (F5) , app loads on the simulator, and Hit Add Product to add a new product
14. Hit Details button below the image ( on the product details page, for me, Button still reads DELETE ME).

Same is true when I change the button color to say accentColor instead of accentColor.

**Comment by zoechi** [comment]
> Open VS code command list (Cmd + shift + P)

what is this for? I'm using IntelliJ/Android Studio.

**Comment by zoechi** [comment]
Have you tried `flutter clean` and uninstalling the app from the device/emulator?

**Comment by Dhana-Krishnasamy** [comment]
VS Code doesn't have button/icon for both Hot Reload and Hot Restart.  Cmd+shift+P lists both the options which then I can hit. This is what I get when I press Cmd+shift+P
![image](https://user-images.githubusercontent.com/3668490/51086569-26559700-1740-11e9-806f-b6aa3a7a0b34.png)

**Comment by Dhana-Krishnasamy** [comment]
> I can't reproduce. Hot reload changes the text and color as you expect.
> 
> Have you tried `flutter clean` and uninstalling the app from the device/emulator?

will try these and update.. thanks

**Comment by Dhana-Krishnasamy** [comment]
> > I can't reproduce. Hot reload changes the text and color as you expect.
> > Have you tried `flutter clean` and uninstalling the app from the device/emulator?
> 
> will try these and update.. thanks

I used command prompt to `flutter clean`  , then removed the app from the simulator.
Then from command prompt `flutter run`   build crashed with
`Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 37f8658acfcf6948)`
Then ran `flutter run` again, this time app loads, but again same behaviour. Please note this is the first time ever I'm trying flutter, so there are no old builds/binaries are on the machine.

build crash log

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter run
> 
> ## exception
> 
> ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
> An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
> This app could not be installed at this time.
> Failed to load Info.plist from bundle at path /Users/Dhana/Library/Developer/CoreSimulator/Devices/28A00073-2A1F-4C2D-8D3A-22250F88FD3D/data/Library/Caches/com.apple.mobile.installd.staging/temp.NKQ7Kh/extracted/Payload/Runner.app
> Failed to load Info.plist from bundle at path /Users/Dhana/Library/Developer/CoreSimulator/Devices/28A00073-2A1F-4C2D-8D3A-22250F88FD3D/data/Library/Caches/com.apple.mobile.installd.staging/temp.NKQ7Kh/extracted/Payload/Runner.app
> Underlying error (domain=MIInstallerErrorDomain, code=35):
> 	Failed to load Info.plist from bundle at path /Users/Dhana/Library/Developer/CoreSimulator/Devices/28A00073-2A1F-4C2D-8D3A-22250F88FD3D/data/Library/Caches/com.apple.mobile.installd.staging/temp.NKQ7Kh/extracted/Payload/Runner.app
>   Command: /usr/bin/xcrun simctl install 28A00073-2A1F-4C2D-8D3A-22250F88FD3D /Users/Dhana/Projects/flutter/flutter_course/build/ios/iphonesimulator/Runner.app
> 
> ```
> #0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
> <asynchronous suspension>
> #1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:125:16)
> #2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:396:31)
> <asynchronous suspension>
> #3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:308:15)
> <asynchronous suspension>
> #4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
> #5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #6      _rootRunUnary (dart:async/zone.dart:1132:38)
> #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #10     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #11     Future._complete (dart:async/future_impl.dart:476:7)
> #12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #13     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
> #14     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
> #15     getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart)
> #16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #17     _rootRunUnary (dart:async/zone.dart:1132:38)
> #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #19     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #21     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #22     Future._complete (dart:async/future_impl.dart:476:7)
> #23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
> #25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
> #26     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
> #27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #28     _rootRunUnary (dart:async/zone.dart:1132:38)
> #29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #30     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #32     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #33     Future._complete (dart:async/future_impl.dart:476:7)
> #34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #35     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
> #36     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
> #37     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
> #38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #39     _rootRunUnary (dart:async/zone.dart:1132:38)
> #40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #41     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #43     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #44     Future._complete (dart:async/future_impl.dart:476:7)
> #45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #46     _rootRunUnary (dart:async/zone.dart:1132:38)
> #47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #48     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
> #49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
> #50     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
> #51     Future._complete (dart:async/future_impl.dart:476:7)
> #52     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #53     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
> #54     _rootRun (dart:async/zone.dart:1124:13)
> #55     _CustomZone.run (dart:async/zone.dart:1021:19)
> #56     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #59     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
> #60     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
> ```
> 
> ## flutter doctor
> 
> ```
> [32m[✓][39m Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
>     [32m•[39m Flutter version 1.0.0 at /Users/Dhana/Projects/flutter/sdk/flutter
>     [32m•[39m Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
>     [32m•[39m Engine revision 7375a0f414
>     [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [32m[✓][39m Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     [32m•[39m Android SDK at /Users/Dhana/Library/Android/sdk
>     [32m•[39m Android NDK at /Users/Dhana/Library/Android/sdk/ndk-bundle
>     [32m•[39m Platform android-27, build-tools 27.0.3
>     [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     [32m•[39m All Android licenses accepted.
> 
> [32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
>     [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
>     [32m•[39m Xcode 10.1, Build version 10B61
>     [32m•[39m ios-deploy 1.9.4
>     [32m•[39m CocoaPods version 1.5.3
> 
> [32m[✓][39m Android Studio (version 3.2)
>     [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
>     [32m•[39m Flutter plugin version 31.3.1
>     [32m•[39m Dart plugin version 181.5656
>     [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [32m[✓][39m Connected device (1 available)
>     [32m•[39m iPhone X • 28A00073-2A1F-4C2D-8D3A-22250F88FD3D • ios • iOS 12.1 (simulator)
> 
> [32m•[39m No issues found!
> ```
>

**Comment by zoechi** [comment]
> Please note this is the first time ever I'm trying flutter

This also means you created the project with the same Flutter version you have currently installed?

Otherwise you could try deleting `android/` and `ios/` and run `flutter create .` in the project directory.

**Comment by Dhana-Krishnasamy** [comment]
> > Please note this is the first time ever I'm trying flutter
> 
> This also means you created the project with the same Flutter version you have currently installed?
Yes

> Otherwise you could try deleting `android/` and `ios/` and run `flutter create .` in the project directory.

`flutter create` failed with below error

![image](https://user-images.githubusercontent.com/3668490/51086979-2a37e800-1745-11e9-81b7-4b17e92c471d.png)

What options do I need to specify? may be `-i` ?

**Comment by Kartik1607** [comment]
`flutter create .` Notice the dot (.)

**Comment by Dhana-Krishnasamy** [comment]
> > > Please note this is the first time ever I'm trying flutter
> > 
> > 
> > This also means you created the project with the same Flutter version you have currently installed?
> > Yes
> 
> > Otherwise you could try deleting `android/` and `ios/` and run `flutter create .` in the project directory.
> 
> `flutter create` failed with below error
> 
> ![image](https://user-images.githubusercontent.com/3668490/51086979-2a37e800-1745-11e9-81b7-4b17e92c471d.png)
> 
> What options do I need to specify? may be `-i` ?

My bad, didn't notice the dot. I've redone the steps and using only the command prompt. I see the same issue when I press `r` or `R`
![screenshot 2019-01-13 at 15 19 29](https://user-images.githubusercontent.com/3668490/51087114-be567f00-1746-11e9-846a-35184d521803.png)

**Comment by Dhana-Krishnasamy** [comment]
> Please note, hot reloading works on the first page ( if change Details to something else reload works).. the issue is only on the second ( product details page).
> Going to try with android now...
> 
> when OS are you guys testing this on? I'm on Mac

Same behaviour on 
`Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)`

Going to try this on another mac later...

**Comment by Kartik1607** [comment]
Would it be possible to share a video screen record?

**Comment by zoechi** [comment]
Glad to hear this is solved.
