### ISSUE TITLE
issue with snackBar

### ISSUE THREAD

**Issue by nnarendra** [flutter/flutter#26493]
## Steps to Reproduce
I am using below code to show snack bar
```dart
 final snackBar = SnackBar(
                        content: Text('Yay! A SnackBar!'),
                        action: SnackBarAction(
                          label: 'Undo',
                          onPressed: () {
                            // Some code to undo the change!
                          },
                        ),
                      );

                      // Find the Scaffold in the Widget tree and use it to show a SnackBar!
                      Scaffold.of(context).showSnackBar(snackBar);
```
```
When the exception was thrown, this was the stack:
I/flutter ( 7610): #2      Scaffold.of (package:flutter/src/material/scaffold.dart:942:12)
I/flutter ( 7610): #3      FirstScreen.build.<anonymous closure> (file:///home/narendra/Androd/flutter_work/btay/lib/screen1.dart:73:32)
I/flutter ( 7610): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter ( 7610): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter ( 7610): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 7610): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter ( 7610): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter ( 7610): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter ( 7610): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter ( 7610): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter ( 7610): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter ( 7610): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter ( 7610): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter ( 7610): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 7610): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter ( 7610): #17     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter ( 7610): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by zoechi** [comment]
> When the exception was thrown, this was the stack:

The information about the exception itself is missing

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

https://stackoverflow.com/questions/40579879/display-snackbar-in-flutter might help.
