### ISSUE TITLE
Issue with Network Image with Firebase

### ISSUE THREAD

**Issue by princerai770** [flutter/flutter#26502]
I was trying to build a gallary app and the image link are stored in firebase cloud..But i'm facing some issues and none of the existing post solved my problem.
Here's the code:

```dart
import 'dart:async';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class myapp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "New Image",
      home: imgscreen(),
    );
  }
}

class imgscreen extends StatefulWidget {
  @override
  _imgscreenState createState() => _imgscreenState();
}

class _imgscreenState extends State<imgscreen> {
  @override
  final CollectionReference collectionReference=Firestore.instance.collection("wallpapers");
  List<DocumentSnapshot> images;
  StreamSubscription<QuerySnapshot> subscription;

  @override
  void initState() {
    super.initState();
    subscription=collectionReference.snapshots().listen((datasnap){
    setState(() {
      images=datasnap.documents;

    });
    });

  }


  @override
  void dispose() {
    subscription?.cancel();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(title: new Text("Photo Gallery"),),
      body: images != null?
      StaggeredGridView.countBuilder(
          crossAxisCount: 4,
          itemCount: images.length,
          itemBuilder: (context,ind){
            String im=images[ind].data['url'];
            return new Material(
              child: new InkWell(
                child: new Hero(
                    tag: im,
                    child:new FadeInImage(
                        placeholder: new AssetImage('images/im2.jpg'),
                        image: new NetworkImage(im),fit: BoxFit.cover,
                    )
                ),
              ),
            );

      },
      staggeredTileBuilder:(i)=>new StaggeredTile.count(2, i.isEven?2:3),mainAxisSpacing: 8.0,crossAxisSpacing: 8.0,)
    :new Center(child: new CircularProgressIndicator(),
      )
    );
  }
}
```

**Here's the error:**

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 11,472ms.

E/flutter ( 7315): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/chatty  ( 7315): uid=10094(com.example.firebase) 1.io identical 6 lines
E/flutter ( 7315): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 7315): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 7315): The following _Exception was thrown resolving an image codec:
I/flutter ( 7315): Exception: operation failed
I/flutter ( 7315): 
I/flutter ( 7315): When the exception was thrown, this was the stack:
I/flutter ( 7315): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:498:12)
I/flutter ( 7315): <asynchronous suspension>
I/flutter ( 7315): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:471:14)
I/flutter ( 7315): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:86)
I/flutter ( 7315): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
I/flutter ( 7315): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:63)
I/flutter ( 7315): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 7315): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:265:30)
I/flutter ( 7315): #7      _ImageProviderResolver.resolve (package:flutter/src/widgets/fade_in_image.dart:333:29)
I/flutter ( 7315): #8      _FadeInImageState._resolveImage (package:flutter/src/widgets/fade_in_image.dart:408:20)
I/flutter ( 7315): #9      _FadeInImageState.didChangeDependencies (package:flutter/src/widgets/fade_in_image.dart:390:5)
I/flutter ( 7315): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
I/flutter ( 7315): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 7315): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #108    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 7315): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 7315): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 7315): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 7315): #114    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 7315): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 7315): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 7315): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 7315): #118    SliverVariableSizeBoxAdaptorElement.updateChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:170:36)
I/flutter ( 7315): #119    SliverVariableSizeBoxAdaptorElement.createChild.<anonymous closure> (package:flutter_staggered_grid_view/src/widgets/sliver.dart:154:20)
I/flutter ( 7315): #120    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 7315): #121    SliverVariableSizeBoxAdaptorElement.createChild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:150:11)
I/flutter ( 7315): #122    RenderSliverVariableSizeBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:239:23)
I/flutter ( 7315): #123    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter ( 7315): #124    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter ( 7315): #125    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter ( 7315): #126    RenderSliverVariableSizeBoxAdaptor._createOrObtainChild (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:227:5)
I/flutter ( 7315): #127    RenderSliverVariableSizeBoxAdaptor.addAndLayoutChild (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:304:5)
I/flutter ( 7315): #128    RenderSliverStaggeredGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:330:13)
I/flutter ( 7315): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #130    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 7315): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #132    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 7315): #133    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter ( 7315): #134    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter ( 7315): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #136    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #138    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #140    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #142    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #143    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #144    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #145    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #146    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #147    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #148    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #149    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #150    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 7315): #151    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 7315): #152    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 7315): #153    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 7315): #154    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 7315): #155    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 7315): #156    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 7315): #157    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 7315): #158    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 7315): #159    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 7315): #160    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 7315): #161    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 7315): #162    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 7315): #163    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 7315): #164    _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 7315): #165    _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 7315): 
I/flutter ( 7315): Image provider: NetworkImage("https://unsplash.com/photos/ZqKYkwSfsJQ", scale: 1.0)
I/flutter ( 7315): Image key: NetworkImage("https://unsplash.com/photos/ZqKYkwSfsJQ", scale: 1.0)
I/flutter ( 7315): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7315): Another exception was thrown: Exception: operation failed
I/chatty  ( 7315): uid=10094(com.example.firebase) Thread-3 identical 5 lines
I/flutter ( 7315): Another exception was thrown: Exception: operation failed
```

flutter doctor:
```
C:\Users\PrInCe\AndroidStudioProjects\firebase>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale en-IN)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\PrInCe\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.30.1)
    • VS Code at C:\Users\PrInCe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

```

**Comment by JediBurrell** [comment]
Could you please format the code and log with three graves on both side?

Like such: \```code\```

And add the output of `flutter doctor -v`

**Comment by princerai770** [comment]
@JediBurrell is it right?and sorry for that..am new here.

**Comment by zoechi** [comment]
`https://unsplash.com/photos/ZqKYkwSfsJQ` does not return an image. It returns HTML.
`'https://images.unsplash.com/photo-1541615008677-0d46e9f9dcb6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80'` would be the URL to get the image.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by princerai770** [comment]
Thnku so much..👍
