### ISSUE TITLE
flutter: type 'Future<dynamic>' is not a subtype of type 'List<dynamic>'

### ISSUE THREAD

**Issue by wufangjian** [flutter/flutter#26506]
**ERROR**
```
Xcode build done.                                            5.3s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown attaching to the render tree:
flutter: type 'Future<dynamic>' is not a subtype of type 'List<String>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new HomePageState (package:tc_flutter/auth/index.dart:14:28)
flutter: #1      Auth.createState (package:tc_flutter/auth/index.dart:6:38)
flutter: #2      new StatefulElement (package:flutter/src/widgets/framework.dart:3789:23)
flutter: #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:795:38)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2948:40)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #12     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #13     main (package:tc_flutter/main.dart:7:3)
flutter: #14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**async Method**
```dart
// index.dart

static getData(num page) async {
    var url = 'https://xxxx/images?page=${page}&per_page=10';
    var httpClient = new HttpClient();
    var request = await httpClient.getUrl(Uri.parse(url));
    var response = await request.close();
    
    if (response.statusCode == 200) {
      var str = await response.transform(utf8.decoder).join();
      var data = json.decode(str);
      var photos = data['photos'];
      List<String> res = new List();
      for (var i = 0, len = photos.length; i < len; i++) {
        res.add(photos[i]['source']['g']);
      }
      return res;
    }
  }
```

**Call method**
```dart
//  main.dart

List<String> items = API.getData(1);
```

**JSON**

![image](https://user-images.githubusercontent.com/6982055/51095833-8147c680-17f2-11e9-8b36-b4434f9c2028.png)

**Comment by Positev** [comment]
That error means you are trying to assign a future to a list. use the .then((){})  method on the future to create a list and return it.

future.then((){
    return List():
});

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by MaxZubko** [comment]
**Help me
Error:  _Another exception was thrown: type 'Future<dynamic>' is not a subtype of type 'String'_**

file 1
```
Future<String> addDataToCart(data) async{
    DocumentReference ref = await db.collection('cart').add(data);
    print(ref.documentID);
    return ref.documentID;
  }
```
file 2 (bloc)
```
void addDataToCart(
    String data,
    ) async {
    Future<String> id = db.addDataToCart(data);
    this.id = id as String;
    _inId.add(this.id);
  }
```
file 3
```
 onTap: () {
              blocCart.addDataToCart(blocTickets.readData());
            },
```
