### ISSUE TITLE
url_lancher issues

### ISSUE THREAD

**Issue by Mon-ius** [flutter/flutter#26504]
My environment is fine.
It's on android device, device name is XiaoMi Mix2S
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

while Using the example code

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(Scaffold(
    body: Center(
      child: RaisedButton(
        onPressed: _launchURL,
        child: Text('Show Flutter homepage'),
      ),
    ),
  ));
}

_launchURL() async {
  const url = 'https://flutter.io';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

```
Error
```

I/flutter ( 9434): #12     runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter ( 9434): #13     main (package:flutter_sensors_example/main.dart:5:3)
I/flutter ( 9434): #14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 9434): #15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9434): ════════════════════════════════════════════════════════════════════════════════════════════════════
W/rsensorsexampl( 9434): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
```

**Comment by Mon-ius** [comment]
Completed Error infomation:

```
I/flutter ( 9434): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9434): The following assertion was thrown attaching to the render tree:
I/flutter ( 9434): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter ( 9434): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter ( 9434): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter ( 9434): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter ( 9434): The context used was:
I/flutter ( 9434):   Scaffold(dirty, state: ScaffoldState#6794e(lifecycle state: initialized, tickers: tracking 1
I/flutter ( 9434):   ticker))
I/flutter ( 9434):
I/flutter ( 9434): When the exception was thrown, this was the stack:
I/flutter ( 9434): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:481:5)
I/flutter ( 9434): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1449:50)
I/flutter ( 9434): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
I/flutter ( 9434): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 9434): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 9434): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 9434): #6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
I/flutter ( 9434): #7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
I/flutter ( 9434): #8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
I/flutter ( 9434): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 9434): #10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
I/flutter ( 9434): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
I/flutter ( 9434): #12     runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter ( 9434): #13     main (package:flutter_sensors_example/main.dart:5:3)
I/flutter ( 9434): #14     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 9434): #15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9434): ════════════════════════════════════════════════════════════════════════════════════════════════════
W/rsensorsexampl( 9434): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
```

**Comment by Mon-ius** [comment]
```
url_launcher:
    git:
      url: git://github.com/flutter/plugins
      path: packages/url_launcher
```

**Comment by jonahwilliams** [comment]
Scaffold requires a MediaQuery widget as a parent. Normally this would be provided from a MaterialApp widget. The problem is unrelated to url launcher.

```
void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    ),
  ));
}
```
