### ISSUE TITLE
Device info plugin throws NPE in background

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#26524]
Device info plugin throws NPE when launched in background (`FlutterNativeView(context, true)`)
Logcat:

```
2019-01-14 16:22:17.468 24050-24050/? E/MethodChannel#plugins.flutter.io/device_info: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
        at io.flutter.plugins.deviceinfo.DeviceInfoPlugin.getAndroidId(DeviceInfoPlugin.java:98)
        at io.flutter.plugins.deviceinfo.DeviceInfoPlugin.onMethodCall(DeviceInfoPlugin.java:69)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-14 16:22:17.472 24050-24276/? E/flutter: [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    PlatformException(error, Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
    <asynchronous suspension>
    #2      DeviceInfoPlugin.androidInfo (package:device_info/device_info.dart:25:25)
    <asynchronous suspension>
    #3      Singleton.init (package:[MY_APP]/singleton.dart:72:45)
    <asynchronous suspension>
    #4      main (package:baby_monitor/main.dart:38:12)
    #5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
    #6      main (package:baby_monitor/main.dart:31:10)
    #7      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Try/catch could be a solution:
```java
  /**
   * Returns the Android hardware device ID that is unique between the device + user and app
   * signing. This key will change if the app is uninstalled or its data is cleared. Device factory
   * reset will also result in a value change.
   *
   * @return The android ID
   */
  @SuppressLint("HardwareIds")
  private String getAndroidId() {
    try {
      return Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID);
    } catch (NullPointerException npe) {
      return "null";
    }
  }
```

But I think this feature should be removed from plugin instead of suppressing warning, which has a valid reason.

**Comment by zoechi** [comment]
Can you publish a minimal reproduction project on GitHub.
Any other Information about how to reproduce?
Is this only on specific devices?

**Comment by rostopira** [comment]
@zoechi really? You need reproduction project for one line issue?
Nope, it's not device specific, it's specific for background usage
But I was wrong with solution for the issue, actually:
```
  /** Plugin registration. */
  public static void registerWith(Registrar registrar) {
    final MethodChannel channel =
        new MethodChannel(registrar.messenger(), "plugins.flutter.io/device_info");
    channel.setMethodCallHandler(new DeviceInfoPlugin(registrar.activity()));
  }
```
`registrar.activity()` **is nullable** in case of running flutter in background, as I said already `FlutterNativeView(context, true)`
Replacing `registrar.activity()` with `registrar.context()` will solve that

**Comment by rostopira** [comment]
Oh, that was fixed already https://github.com/flutter/plugins/pull/921

**Comment by zoechi** [comment]
Duplicate of #24633
