### ISSUE TITLE
ios build works via xcode, but not on Android studio on Mac VM

### ISSUE THREAD

**Issue by Mantas0726** [flutter/flutter#26532]
I have created a new Flutter project on my windows machine and made a shared folder with MacOs VM. It runs well on windows, I have managed to get it working in xcode, however, when I do `flutter run` in Android Studio this error occurs:

```
Automatically signing iOS for device deployment using specified development team in Xcode project: M****
Starting Xcode build...                                          
Xcode build done.                                            1.4s
xcodebuild: error: Unable to load workspace '._Runner.xcworkspace'.
        Reason: Unknown.

Oops; flutter has exited unexpectedly: "Exit code 74 from: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace ._Runner.xcworkspace -scheme Runner BUILD_DIR=/Volumes/VMware Shared Folders/tst/flutter_app/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p3/0cdlthzs6slc2zv7vf4lbcvc0000gn/T/flutter_build_log_pipe.y6AQTx/pipe_to_stdout -showBuildSettings".
Sending crash report to Google.
Crash report sent (report ID: b2552852b05aa8f2)
Crash report written to /Volumes/VMware Shared Folders/tst/flutter_app/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

flutter_01.log:

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

String: Exit code 74 from: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace ._Runner.xcworkspace -scheme Runner BUILD_DIR=/Volumes/VMware Shared Folders/tst/flutter_app/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p3/0cdlthzs6slc2zv7vf4lbcvc0000gn/T/flutter_build_log_pipe.y6AQTx/pipe_to_stdout -showBuildSettings

#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:353:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:284:10)
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:505:69)
<asynchronous suspension>
#3      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:247:50)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._complete (dart:async/future_impl.dart:476:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#25     Future._complete (dart:async/future_impl.dart:476:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-LT)
    [32m•[39m Flutter version 1.0.0 at /Users/mantas/flutter
    [32m•[39m Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at /Users/mantas/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Irena’s iPhone • 1c26c3ec6e3b799052c0d4647e8c7e05e0b3bbd6 • ios • iOS 11.2.6

[32m•[39m No issues found!
```

**Comment by zoechi** [comment]
Can you reproduce with a new project created with `flutter create foo` or only with an existing project?

**Comment by zoechi** [comment]
You need to delete files and folders listed in `.gitignore`.
Using Git to share the project would prevent such errors.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
