### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/wutao/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip

### ISSUE THREAD

**Issue by murphywu** [flutter/flutter#26570]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter run -d 92cd38f4
```

## exception
```
ProcessException: ProcessException: Process "/Users/wutao/workspace/projects/myflutterapp/android/gradlew" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/wutao/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /Users/wutao/workspace/projects/myflutterapp/android/gradlew -v
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:189:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:170:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:98:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:90:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:84:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:101:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:289:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:272:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:275:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:378:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#29     Future._complete (dart:async/future_impl.dart:473:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.1.9, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.1.9 at /Users/wutao/workspace/flutter
    [32m•[39m Framework revision 1407091bfb (6 days ago), 2019-01-08 20:40:19 -0800
    [32m•[39m Engine revision e5ec3cf3ea
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/wutao/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 9.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 9.3, Build version 9E145
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 29.0.1
    [32m•[39m Dart plugin version 173.4700
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[32m[✓][39m Connected device (3 available)
    [32m•[39m MI 4LTE   • 92cd38f4         • android-arm • Android 6.0.1 (API 23)
    [32m•[39m dpos      • 5606780500900006 • android-arm • Android 4.4.2 (API 19)
    [32m•[39m TPS650mt1 • 18048027700694   • android-arm • Android 5.1.1 (API 22)

[32m•[39m No issues found!
```

```
➜  myflutterapp flutter doctor -v
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 1.1.9 at /Users/wutao/workspace/flutter
    • Framework revision 1407091bfb (6 days ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wutao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (3 available)
    • MI 4LTE   • 92cd38f4         • android-arm • Android 6.0.1 (API 23)
    • dpos      • 5606780500900006 • android-arm • Android 4.4.2 (API 19)
    • TPS650mt1 • 18048027700694   • android-arm • Android 5.1.1 (API 22)

• No issues found!

```

**Comment by zoechi** [comment]
When you run again you get the same result?

https://github.com/flutter/flutter/issues/11856#issuecomment-453638071 might be worth a try

See also https://github.com/flutter/flutter/issues/15106#issuecomment-450739151

**Comment by murphywu** [comment]
@zoechi 
I solved this is problem by referencing the [#15106 (comment)](https://github.com/flutter/flutter/issues/15106#issuecomment-450739151) step 2. I change the gradle-wrapper.properties distributionUrl to my local gradle version. Thanks for your help.

**Comment by ezrogha** [comment]
From the error locate the folder `/Users/wutao/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv` and delete it with all it's, then run the app again

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/101987149-3e881500-3ccd-11eb-9790-3f2253b8ef82.png)

Just download that file, and move to your folder `/Users/wutao/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/` then it will find.

The reason for why this happen is mostly because of, it try to download but failded. and your local were broken. Download it again.
