### ISSUE TITLE
[Plugins android_alarm_manager] Exceptions occurred when registering and using other plug-ins

### ISSUE THREAD

**Issue by hanj315** [flutter/flutter#26582]
When I use the `android_alarm_manager` plug-in with other plug-ins, there are some exceptions. I can't tell if it's `android_alarm_manager` or other plug-in specifications or if I'm using it in the wrong way.
I can only avoid these questions in other ways at present, but I hope to use the normal way to complete the function.

> device_info: ^0.3.0
> barcode_scan: ^0.0.8

```
An exception occurs when the device_info plug-in is used in the callback method of android_alarm_manager
---
E/MethodChannel#plugins.flutter.io/device_info(18776): Failed to handle method call
E/MethodChannel#plugins.flutter.io/device_info(18776): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at io.flutter.plugins.deviceinfo.DeviceInfoPlugin.getAndroidId(DeviceInfoPlugin.java:98)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at io.flutter.plugins.deviceinfo.DeviceInfoPlugin.onMethodCall(DeviceInfoPlugin.java:69)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at android.os.Looper.loop(Looper.java:141)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at android.app.ActivityThread.main(ActivityThread.java:5696)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
E/MethodChannel#plugins.flutter.io/device_info(18776): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
E/flutter (18776): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (18776): PlatformException(error, Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference, null)
E/flutter (18776): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (18776): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #2      DeviceInfoPlugin.androidInfo (package:device_info/device_info.dart:25:25)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #3      TTT.aaaasync (package:demo_flutter_android_alarm_manager/main.dart:39:54)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #4      _alarmManagerCallbackDispatcher.<anonymous closure> (package:android_alarm_manager/android_alarm_manager.dart:41:12)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:344:55)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:312:54)
E/flutter (18776): #7      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
E/flutter (18776): <asynchronous suspension>
E/flutter (18776): #8      _invoke3 (dart:ui/hooks.dart:196:13)
E/flutter (18776): #9      _dispatchPlatformMessage (dart:ui/hooks.dart:105:5)

---

barcode_scan plug-in will have an exception when Android_alarm_manager uses registration. At present, I can only manually copy other code generated in GeneratedPluginRegistrant except barcode_scan.
---


[{"event":"app.progress","params":{"appId":"429984ed-7075-40a5-89c9-481e8cbae0fe","id":"3","progressId":null,"message":"Installing build/app/outputs/apk/app.apk..."}}]Installing build/app/outputs/apk/app.apk...

E/flutter (20450): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (20450): PlatformException(error, registrar.activity() must not be null, null)
E/flutter (20450): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (20450): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (20450): <asynchronous suspension>
E/flutter (20450): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:70:10)
E/flutter (20450): <asynchronous suspension>
E/flutter (20450): #3      main (package:android_alarm_manager_example/main.dart:44:29)
E/flutter (20450): <asynchronous suspension>
E/flutter (20450): #4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (20450): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Syncing files to device MI 4LTE...
```

**Comment by wouterhardeman** [comment]
Related to: https://github.com/flutter/flutter/issues/26003
