### ISSUE TITLE
Error on TextEditingController() in  TextFormField()  with initialValue parameter

### ISSUE THREAD

**Issue by Mon-ius** [flutter/flutter#26608]
```
I/flutter (16425): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (16425): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (16425): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (16425): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (16425): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (16425): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (16425): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (16425): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (16425): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (16425): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (16425): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (16425): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16425): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16425): #59     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (16425): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (16425): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (16425): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (16425): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (16425): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (16425): #66     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (16425): #67     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (16425): #68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (16425): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (16425): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 3 of 533 libraries in 707ms.
```

**Comment by Mon-ius** [comment]
```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/monius/development/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version openjdk version "1.8.0_152-release"

[✓] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • MIX 2S • ee1abd44 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Mon-ius** [comment]
```
I/flutter (16745): #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #212    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16745): #217    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #218    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #219    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16745): #223    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #224    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #225    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (16745): #226    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #228    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16745): #230    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #231    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #232    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #233    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #234    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16745): #236    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #237    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #238    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (16745): #239    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #240    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #241    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (16745): #243    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (16745): #244    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (16745): #245    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (16745): #246    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (16745): #247    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (16745): #248    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
I/flutter (16745): #249    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
I/flutter (16745): #250    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
I/flutter (16745): #251    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (16745): #252    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
I/flutter (16745): #253    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
I/flutter (16745): #254    runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter (16745): #255    main (package:flutter_sensors_example/main.dart:9:16)
I/flutter (16745): #256    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter (16745): #257    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (16745): (elided 2 frames from class _AssertionError)
I/flutter (16745): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Mon-ius** [comment]
Root of Evil 
```

    final name = TextFormField(
      keyboardType: TextInputType.text,
      autofocus: false,
      controller: _name,
      initialValue: "password",
      decoration: InputDecoration(
        hintText: 'UserName',
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(32.0)),
      ),
```

**Comment by zoechi** [comment]
The error output above is still incomplete and is missing the essential part.

The minimal reproduction should be self-contained,  runnable as-is,
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Ok, I built a reproduction myself with your code.

```
I/flutter (18011): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18011): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#3dd0f):
I/flutter (18011): 'package:flutter/src/material/text_form_field.dart': Failed assertion: line 105 pos 15:
I/flutter (18011): 'initialValue == null || controller == null': is not true.
I/flutter (18011): 
I/flutter (18011): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18011): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18011): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18011):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18011): 
I/flutter (18011): When the exception was thrown, this was the stack:
I/flutter (18011): #2      new TextFormField (package:flutter/src/material/text_form_field.dart:105:15)
I/flutter (18011): #3      _MyHomePageState.build (package:flutter_0_generic/main.dart:40:13)
I/flutter (18011): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
```

which states that `initialValue` or `controller` must be `null` which is violated by your code.

Pass the initial value to the `controller` instead if you think you need one.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
