### ISSUE TITLE
gestures/force_press.dart': 'pressure.isNaN ? true : (pressure <= 1.0 && pressure >= 0.0)': is not true.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26624]
I'm on Android:
```
I/flutter (13366): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13366): The following assertion was thrown while routing a pointer event:
I/flutter (13366): 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 219 pos 14: 'pressure.isNaN
I/flutter (13366): ? true : (pressure <= 1.0 && pressure >= 0.0)': is not true.
I/flutter (13366): 
I/flutter (13366): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13366): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13366): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13366):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13366): 
I/flutter (13366): When the exception was thrown, this was the stack:
I/flutter (13366): #2      ForcePressGestureRecognizer.handleEvent (package:flutter/src/gestures/force_press.dart:219:14)
I/flutter (13366): #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (13366): #4      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (13366): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (13366): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (13366): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (13366): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (13366): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (13366): #10     _invoke1 (dart:ui/hooks.dart:187:13)
I/flutter (13366): #11     _dispatchPointerDataPacket (dart:ui/hooks.dart:138:5)
I/flutter (13366): (elided 2 frames from class _AssertionError)
I/flutter (13366): 
I/flutter (13366): Event:
I/flutter (13366):   PointerMoveEvent(Offset(211.8, 342.5))
I/flutter (13366): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I was hitting an input field a bunch.

**Comment by Hixie** [comment]
cc @jslavitz

**Comment by Hixie** [comment]
I patch around this in https://github.com/flutter/flutter/pull/26629

**Comment by Hixie** [comment]
...but the root cause is https://github.com/flutter/flutter/issues/26628

**Comment by xster** [comment]
Going to dupe into #26563
