### ISSUE TITLE
No reason error when self-built class have int parameter 

### ISSUE THREAD

**Issue by Mon-ius** [flutter/flutter#26665]
```
Built build/app/outputs/apk/debug/app-debug.apk.
E/MethodChannel#flutter_sensors(31734): Failed to handle method call
E/MethodChannel#flutter_sensors(31734): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Int
E/MethodChannel#flutter_sensors(31734): 	at cl.ceisufro.fluttersensors.FlutterSensorsPlugin.isSensorAvailable(FlutterSensorsPlugin.kt:79)
E/MethodChannel#flutter_sensors(31734): 	at cl.ceisufro.fluttersensors.FlutterSensorsPlugin.onMethodCall(FlutterSensorsPlugin.kt:70)
E/MethodChannel#flutter_sensors(31734): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#flutter_sensors(31734): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter_sensors(31734): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_sensors(31734): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_sensors(31734): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter_sensors(31734): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/MethodChannel#flutter_sensors(31734): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_sensors(31734): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter_sensors(31734): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Application finished.
```

**Comment by wouterhardeman** [comment]
The plugin that you are using is not a first party plugin. You can try using https://pub.dartlang.org/packages/sensors or file an issue in the repository of the plugin you are using.

**Comment by zoechi** [comment]
Closing because this looks like an issue in 3rd-party code.

Feels free to add a comment to have the issue reopened if you disagree.
