### ISSUE TITLE
[Plugins] Android Image picker crashes when the main activity gets destroyed after launching the Image Picker activity, and back button is pressed.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#26676]
Steps to reproduce:

1. Use android device, switch on "don't keep activities" option in android developer options setting. 
2. Launch the example app, click on any of the options (select from gallery or select from camera).
3. Press back button and see crash. 

Cause:
The direct cause of the crash is that the pendingResult in `ImagePickerDelegate.java` is `null`. And it throws a null pointer exception here
```java
 private void finishWithSuccess(String imagePath) {
   pendingResult.success(imagePath);
   clearMethodCallAndResult();
  }
```
the pending Result should not suppose to be null, but because the "don't keep activities" is on, MainActivity gets created again and the ImagePickerDelegate gets created again, it lost the pendingResult from the first creation. 

This crash should not happen too often because in real daily usage, main activity should not be destroyed too often. 

Stack Trace:
```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.flutter.plugins.imagepicker.example, PID: 20394
    java.lang.RuntimeException: Unable to resume activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/72 flg=0x1 }} to activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3421)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/72 flg=0x1 }} to activity {io.flutter.plugins.imagepicker.example/io.flutter.plugins.imagepickerexample.MainActivity}: java.lang.IllegalStateException: Received image from picker that was not requested
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4094)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3395)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
     Caused by: java.lang.IllegalStateException: Received image from picker that was not requested
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:457)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:396)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
        at android.app.Activity.dispatchActivityResult(Activity.java:6931)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3395) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
Application terminated.
```

Beyond the crash:
If MainActivity do get destroyed and recreated, even there is no crash (with null pointer fixes, etc.), the dart part of the plugin might not receive necessary information from the Java code.

**Comment by cyanglaz** [comment]
Same as https://github.com/flutter/flutter/issues/17950.
