### ISSUE TITLE
package:flutter/src/material/app_bar.dart': error: line 399 pos 29

### ISSUE THREAD

**Issue by pacifire** [flutter/flutter#26700]
All the IconButton's in the app started throwing error after a restart.
So, i had to add IconData in all the project.

But now AppBar (i.e. flutter/src/material/app_bar.dart) is throwing the error that we need to add IconData in the Appbar's class.

My APP BAR IS LIKE: 

I cannot change the Flutter's library code :-( Please check. I am adding the error thrown.

```
return Scaffold(
      
        // appBar: AppBar(title: new Text(_pageTitle), elevation: 4.0, primary: true, toolbarOpacity: 1.0, bottomOpacity: 1.0),**//This is also not working**.
        appBar: AppBar(title: new Text(_pageTitle)),**//This is also not working, earlier this was working.**
        body: dashboardBody,//Center(child: Text("My Page"))//dashboardBody is another Widget.
        drawer: Drawer(
          // Add a ListView to the drawer. This ensures the user can scroll
          // through the options in the Drawer if there isn't enough vertical
          // space to fit everything.

          child: dashboardType,
        ));
```

```
I/flutter (10154): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10154): The following _CompileTimeError was thrown building AppBar(dirty, state: _AppBarState#bbdc3):
I/flutter (10154): 'package:flutter/src/material/app_bar.dart': error: line 399 pos 29:
I/flutter (10154): file:///Users/samarjeet/Desktop/flutter/packages/flutter/lib/src/material/app_bar.dart:399:29:
I/flutter (10154): Error: Too few positional arguments: 1 required, 0 given.
I/flutter (10154):         leading = IconButton(
I/flutter (10154):                             ^
I/flutter (10154):         leading = IconButton(
I/flutter (10154):                             ^
I/flutter (10154):
I/flutter (10154): When the exception was thrown, this was the stack:
I/flutter (10154): #0      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (10154): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (10154): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #3      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (10154): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #7      ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (10154): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (10154): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (10154): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (10154): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter (10154): #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (10154): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (10154): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (10154): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (10154): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (10154): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (10154): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (10154): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (10154): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (10154): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (10154): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (10154): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
```
//MANY LOGS ARE BELOW....

**Comment by zoechi** [comment]
Sounds like you accidentally modified Flutter SDK source.
Run `git status` in your Flutter install directory to check.

To fix you can use https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by pacifire** [comment]
@zoechi : Thanks a lot. I don't know, how I changed the Flutter SDK source.
But your answer helped a lot. Thanks, all issues fixed. Thanks a lot.

**Comment by zoechi** [comment]
@pacifire glad to hear. There is some work on IDE's to prevent that better.
