### ISSUE TITLE
crash on nested Navigator with GlobalKey

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#26704]
The following flutter project reproduces the issue. Run the project, press button "1", then press button "2".

  https://github.com/SteveAlexander/navigator_issue

When using two levels of nested Navigator, where they have GlobalKeys, on the second route pushed, the app crashes with the following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building FocusScope(dirty, state: _FocusScopeState#7e10a):
flutter: 'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 315 pos 12: 'child._parent
flutter: == null || child._parent == this': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      FocusScopeNode.setFirstFocus (package:flutter/src/widgets/focus_manager.dart:315:12)
flutter: #3      FocusScopeNode.reparentScopeIfNeeded (package:flutter/src/widgets/focus_manager.dart:338:7)
flutter: #4      _FocusScopeState.build (package:flutter/src/widgets/focus_scope.dart:104:28)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2943:38)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
etc.
```

The exception looks similar to https://github.com/flutter/flutter/issues/11719, but while that one is about TextFields, this one is specific to how Navigators interact with GlobalKeys.

The problem also looks similar to this old issue about nested focus scopes, fixed by @Hixie in 2015: https://github.com/flutter/flutter/pull/448

**Comment by SteveAlexander** [comment]
Relevant portion of code, to save looking at the github project:

```dart
class _MyHomePageState extends State<MyHomePage> {

  GlobalKey<NavigatorState> parentNavKey = GlobalKey<NavigatorState>(
    debugLabel: 'parentNavKey'
  );

  GlobalKey page1key = GlobalKey(debugLabel: 'page1key');
  GlobalKey page2key = GlobalKey(debugLabel: 'page2key');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Navigator(
        key: parentNavKey,
        onGenerateRoute: (RouteSettings settings) {
          switch (settings.name) {
            case '1': return MaterialPageRoute(
              settings: RouteSettings(isInitialRoute: true),
              builder: (_) => Navigator(
                key: page1key,
                onGenerateRoute: (settings) => MaterialPageRoute(
                  settings: settings,
                  builder: (_) => Center(child: Text('Page 1'))
                )
              )
            );
            case '2': return MaterialPageRoute(
              settings: RouteSettings(isInitialRoute: true),
              builder: (_) => Navigator(
                key: page1key,
                onGenerateRoute: (settings) => MaterialPageRoute(
                  settings: settings,
                  builder: (_) => Center(child: Text('Page 2'))
                )
              )
            );
            default: return MaterialPageRoute(
              settings: RouteSettings(isInitialRoute: true),
              builder: (_) => Center(child: Text('Initial page'))
            );
          }
        }
      ),
      bottomNavigationBar: SafeArea(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            FlatButton(
              onPressed: () =>
                  parentNavKey.currentState.pushReplacementNamed('1'),
              color: Colors.grey,
              child: Text('1')
            ),
            FlatButton(
              onPressed: () =>
                  parentNavKey.currentState.pushReplacementNamed('2'),
              color: Colors.grey,
              child: Text('2')
            )
          ]
        )
      ),
    );
  }
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.1.10-pre.93, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.1.10-pre.93 at /Users/steve/code/flutter
    • Framework revision 36a493602c (16 hours ago), 2019-01-16 23:12:47 +0100
    • Engine revision 3c0aa918de
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 492df72739)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone XR • 1EE1625B-61BB-421E-B104-CB3C8A5B6076 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by SteveAlexander** [comment]
I have tried reproducing this issue without GlobalKeys — it only errors with GlobalKeys.

I have tried reproducing this issue using other widgets than Navigator — it only errors with nested Navigators.

**Comment by zoechi** [comment]
A similar error was reported in #16601

**Comment by SteveAlexander** [comment]
Looking through the `focus_manager.dart` code, I've found something I'm having trouble making sense of.

First of all, the top of the traceback looks like this:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building FocusScope(dirty, state: _FocusScopeState#197ee):
flutter: 'package:flutter/src/widgets/focus_manager.dart': Failed assertion: line 315 pos 12: 'child._parent
flutter: == null || child._parent == this': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      FocusScopeNode.setFirstFocus (package:flutter/src/widgets/focus_manager.dart:315:12)
flutter: #3      FocusScopeNode.reparentScopeIfNeeded (package:flutter/src/widgets/focus_manager.dart:338:7)
flutter: #4      _FocusScopeState.build (package:flutter/src/widgets/focus_scope.dart:104:28)
```

Looking at `FocusScopeNode.reparentScopeIfNeeded`:

```dart
  void reparentScopeIfNeeded(FocusScopeNode child) {
    assert(child != null);
    if (child._parent == null || child._parent == this)
      return;
    if (child.isFirstFocus)
      setFirstFocus(child);
    else
      child.detach();
  }
```

So, `setFirstFocus(child)` is called only when `child._parent` is a `FocusScopeNode`, and it is different than `this`. That is, `child._parent` is not `null`, and is not `this`.

But, when `setFirstFocus` is called, the first thing we do is assert that `child._parent` is either `null` or `this`.

```dart
  void setFirstFocus(FocusScopeNode child) {
    assert(child != null);
    assert(child._parent == null || child._parent == this);
    if (_firstChild == child)
      return;
    child.detach();
    _prepend(child);
    assert(child._parent == this);
    _didChangeFocusChain();
  }
```

That doesn't make sense to me — in `reparentScopeIfNeeded`, if parent is not `this` then call `setFirstFocus` and insist that parent is this.

If this isn't clear enough already, here's the flow of statements when `child._parent == this` is true.

```dart
    assert(child != null);
    if (child._parent == null || child._parent == this)
      return;
    // child._parent cannot be this
    if (child.isFirstFocus) {
      assert(child != null);
      assert(child._parent == null || child._parent == this);
      // child._parent must be this
      if (_firstChild == child)
        return;
      child.detach();
  }
```

**Comment by maxlapides** [comment]
I'm having a very similar issue with my app

**Comment by nicholasgerard** [comment]
Any updates on this? Having the same issue when using GlobalKeys to programmatically control nested navigators in CupertinoTabViews.
