### ISSUE TITLE
flutter - FormatException Invalid date format

### ISSUE THREAD

**Issue by donniexyz** [flutter/flutter#26751]
In brief: The "Invalid date format" dart error is seems to be caused by flutter, as standalone Dart program can process the date.

## Steps to Reproduce

1. Fresh install latest stable flutter & Android Studio 
2. cmd> flutter console
3. cmd> flutter doctor
      OR
   cmd> flutter create

## command

flutter create test

## exception

FormatException: FormatException: Invalid date format
C:\arkansa\apps\flutter>"c:\Program Files\Git\bin\git.exe" log -n 1 --pretty=...

```
#0      DateTime.parse (dart:core/date_time.dart:334:7)
#1      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:273:56)
<asynchronous suspension>
#2      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:377:41)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1463:12)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#11     new Future.sync (dart:async/future.dart:224:31)
#12     CommandRunner.run (package:args/command_runner.dart:111:11)
#13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#14     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#22     run (package:flutter_tools/runner.dart:51:10)
#23     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#24     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#25     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v0.0.0-unknown, on Microsoft Windows [Version 10.0.17134.472], locale en-MY)
    [32m•[39m Flutter version 0.0.0-unknown at C:\arkansa\apps\flutter
    [32m•[39m Framework revision C:\arkansa\a (C:\arkansa\apps\flutter>"c:\Program Files\Git\bin\git.exe" log -n 1
      --pretty=format:%ar 
      7 weeks ago), C:\arkansa\apps\flutter>"c:\Program Files\Git\bin\git.exe" log -n 1 --pretty=format:%ad --date=iso 
      2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at d:\arkansa\apps\android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = d:\arkansa\apps\android-sdk
    [32m•[39m Java binary at: C:\Program Files\Java\jdk1.8.0_191\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Android Studio (version 3.1)
    [32m•[39m Android Studio at D:\arkansa\apps\android-studio
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[33m[!][39m IntelliJ IDEA Community Edition (version 2018.3)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.2
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [32m•[39m Dart plugin version 183.4886.3
    [32m•[39m For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```

## Standalone Dart DateTime.parse

```
C:\arkansa\apps\flutter>"c:\Program Files\Git\bin\git.exe" log -n 1 --pretty=format:%ad --date=iso
2018-11-29 19:41:26 -0800

C:\arkansa\apps\flutter>"c:\Program Files\Git\bin\git.exe" log -n 1 --pretty=format:%ad --date=iso-strict
2018-11-29T19:41:26-08:00
```

test.dart
```
void main() {
  print('Hello, World!');
  print(DateTime.parse("2018-11-29 19:41:26 -0800"));
  print(DateTime.parse("2018-11-29T19:41:26-08:00"));
}
```

output:
```
Hello, World!
2018-11-30 03:41:26.000Z
2018-11-30 03:41:26.000Z
```

**Comment by zoechi** [comment]
This doesn't look good
> ```dart 
> �[32m[✓]�[39m Flutter (Channel stable, v0.0.0-unknown,
> ```

Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by donniexyz** [comment]
Hi Zoechi,

Thank you, it has been fixed now.
The root cause: there is a batch file git.cmd that its path appear before git.exe path in environment.
After the git.cmd is removed, flutter doctor works as normal.

```
C:\arkansa\apps\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-MY)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

C:\arkansa\apps\flutter>
```

Thanks again.

Regards
