### ISSUE TITLE
I got no response when I try to request the banned addresses in iOS simulator

### ISSUE THREAD

**Issue by MarshallYang** [flutter/flutter#26789]
## Steps to Reproduce

Because of the GFW, I have to set VPN or Shadowsocks to request the banned addresses. I found that when I try to request "google.com" and I got no response but a timeout exception in iOS simulator, what I know is that the simulator has the same network as your computer, I have already set ss to visit banned hostnames and I can visit "google.com" using Safari in simulator, but in this way, I got no response, the code is shown below.
```
HttpClient()
        .getUrl(Uri.parse('https://google.com'))
        .then((request) => request.close())
        .then((response) =>
        response.transform(Utf8Decoder()).listen(print));
```

## Logs

```
 [DEVICE LOG] 2019-01-19 09:00:39.727354+0800  localhost Runner[1997]: (Flutter) [VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
[        ] [DEVICE LOG] SocketException: OS Error: Operation timed out, errno = 60, address = google.com, port = 50658
[   +2 ms] [DEVICE LOG] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
[        ] [DEVICE LOG] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] [DEVICE LOG] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ] [VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
[        ] SocketException: OS Error: Operation timed out, errno = 60, address = google.com, port = 50658
[        ] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
[        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

```
```

```
```

**Comment by kangwang1988** [comment]
See: https://docs.flutter.io/flutter/dart-io/HttpClient/findProxy.html

**Comment by kangwang1988** [comment]
As I don't think this is a bug/feature request for flutter,
Closing issue #26789
