### ISSUE TITLE
Cannot build app ios in release

### ISSUE THREAD

**Issue by pjcau** [flutter/flutter#26812]
Hi Guys, 

I cannot build after last upgrade flutter. The my locale situation is

 
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.135, on Mac OS X 10.14.2 18C54, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (5 available)

• No issues found!
```

and after the command and the response for release command build on ios

```
flutter build ios                     
Building com.pjonny84.babyLearnWithGame for device (ios-rele                                                                                             ├─Building Dart code...                                     6.8s                                                                                       Unhandled exception:                                                                                                
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:492:5)
#3      AnsiStatus.cancel (package:flutter_tools/src/base/logger.dart:731:11)
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:470:30)
<asynchronous suspension>
#5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#6      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#7      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:482:29)
<asynchronous suspension>
#8      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


```

**Comment by zoechi** [comment]
Please ensure your Flutter installation is not corrupted https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by zoechi** [comment]
Did you check if you can still reproduce if you switch back to `dev` channel?

**Comment by pjcau** [comment]
> Please ensure your Flutter installation is not corrupted https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

Yes I do, but it's same
```

 (flutter clean && flutter build ios && cd ios && fastlane ios beta)
Deleting 'build/'.
Building com.pjonny84.babyLearnWithGame for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 5WA53Z6P42                                                                                                                       ├─Building Dart code...                                    92.4s                                                                                                                                                                  Unhandled exception:                                                                                                
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:492:5)
#3      AnsiStatus.cancel (package:flutter_tools/src/base/logger.dart:731:11)
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:470:30)
<asynchronous suspension>
#5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#6      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#7      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:482:29)
<asynchronous suspension>
#8      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

**Comment by zoechi** [comment]
That means it is not a regression? What version did you upgrade from before you saw the error?

**Comment by zoechi** [comment]
> Yes I do, but it's same

relates to which of my suggestions?

**Comment by pjcau** [comment]
> > Please ensure your Flutter installation is not corrupted https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted
> 
> Yes I do, but it's same
> 
> ```
> 
>  (flutter clean && flutter build ios && cd ios && fastlane ios beta)
> Deleting 'build/'.
> Building com.pjonny84.babyLearnWithGame for device (ios-release)...
> Automatically signing iOS for device deployment using specified development team in Xcode project: 5WA53Z6P42                                                                                                                       ├─Building Dart code...                                    92.4s                                                                                                                                                                  Unhandled exception:                                                                                                
> NoSuchMethodError: The method 'cancel' was called on null.
> Receiver: null
> Tried calling: cancel()
> #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
> #1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
> #2      Status.cancel (package:flutter_tools/src/base/logger.dart:492:5)
> #3      AnsiStatus.cancel (package:flutter_tools/src/base/logger.dart:731:11)
> #4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:470:30)
> <asynchronous suspension>
> #5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
> <asynchronous suspension>
> #6      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
> <asynchronous suspension>
> #7      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:482:29)
> <asynchronous suspension>
> #8      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
> <asynchronous suspension>
> #9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
> #10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #11     _rootRunUnary (dart:async/zone.dart:1132:38)
> #12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #16     Future._complete (dart:async/future_impl.dart:473:7)
> #17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #18     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
> #19     _rootRun (dart:async/zone.dart:1124:13)
> #20     _CustomZone.run (dart:async/zone.dart:1021:19)
> #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
> #25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
> ```

I use this 

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.135, on Mac OS X 10.14.2 18C54, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (5 available)

• No issues found!
```

**Comment by zoechi** [comment]
Tentatively added `today` label

**Comment by zuozuo** [comment]
I met the same problem. 

```shell
➜  myapp flutter run
Running "flutter packages get" in myapp...                          0.4s
Launching lib/main.dart on iPhone XR in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                           1.3s
Unhandled exception:
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:492:5)
#3      AnsiStatus.cancel (package:flutter_tools/src/base/logger.dart:731:11)
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:470:30)
<asynchronous suspension>
#5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#6      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:482:29)
<asynchronous suspension>
#7      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:378:48)
<asynchronous suspension>
#8      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:308:15)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:305:54)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#20     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#30     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#31     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#38     Future._complete (dart:async/future_impl.dart:473:7)
#39     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#40     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#41     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#42     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#49     Future._complete (dart:async/future_impl.dart:473:7)
#50     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#51     _rootRunUnary (dart:async/zone.dart:1132:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#56     Future._complete (dart:async/future_impl.dart:473:7)
#57     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#58     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#59     _rootRun (dart:async/zone.dart:1124:13)
#60     _CustomZone.run (dart:async/zone.dart:1021:19)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by dnfield** [comment]
Reproduced as well locally.

We have a test that almost would have caught this, but it tests building a debug instead of a release IPA :(

**Comment by a396901990** [comment]
i update to latest master today. can't build with same error
