### ISSUE TITLE
No MaterialLocalizations found

### ISSUE THREAD

**Issue by a7me63azzab** [flutter/flutter#26822]
## code
```
import 'package:flutter/material.dart';

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  void _openRecordingWidget(context) {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Container(
            child: Text('Recording'),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Audio Recorder'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Add'),
            onPressed: () => _openRecordingWidget(context),
          ),
        ),
      ),
    );
  }
}


```

### Error
```
I/flutter (23955): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (23955): The following assertion was thrown while handling a gesture:
I/flutter (23955): No MaterialLocalizations found.
I/flutter (23955): MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (23955): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter (23955): by the material library. 
I/flutter (23955): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
I/flutter (23955): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter (23955): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter (23955):   MyApp
I/flutter (23955): The ancestors of this widget were:
I/flutter (23955):   [root]
I/flutter (23955): When the exception was thrown, this was the stack:
I/flutter (23955): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
I/flutter (23955): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
I/flutter (23955): #2      showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart:328:10)
I/flutter (23955): #3      _MyAppState._openRecordingWidget (package:flutter_audio_recorder/lib/app.dart:12:5)
I/flutter (23955): #4      _MyAppState.build.<anonymous closure> (package:flutter_audio_recorder/lib/app.dart:31:30)
I/flutter (23955): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter (23955): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter (23955): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (23955): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (23955): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (23955): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
I/flutter (23955): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (23955): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (23955): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (23955): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (23955): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (23955): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (23955): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (23955): #18     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (23955): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter (23955): Handler: onTap
I/flutter (23955): Recognizer:
I/flutter (23955):   TapGestureRecognizer#b048d(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (23955):   Offset(176.7, 332.7), sent tap down)
I/flutter (23955): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

### flutter analyze
```
Analyzing flutter_audio_recorder...                              
No issues found! (ran in 8.5s)

```

### flutter doctor -v
```
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/a7me63azza8/development/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/a7me63azza8/Android/Sdk
    • Android NDK at /home/a7me63azza8/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/a7me63azza8/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • D2302 • ZH8002SYU4 • android-arm • Android 5.1.1 (API 22)

• No issues found!

```

**Comment by zoechi** [comment]
Looks similar to #18254
