### ISSUE TITLE
`flutter run` exception with space and & in project path

### ISSUE THREAD

**Issue by Thorsenna** [flutter/flutter#26891]
## command

flutter run

## exception

```
ProcessException: ProcessException: Process "C:\Users\asus\Downloads\flutter tuto\flutter tuto\12 Flutter Basic Layouts & Container Widgets\078 intro-layouts-containers\intro_layouts_containers\android\gradlew.bat" exited abnormally:
'Container' nâ€™est pas reconnu en tant que commande interne
ou externe, un programme exÃ©cutable ou un fichier de commandes.
Erreur : impossible de trouver ou charger la classe principale org.gradle.wrapper.GradleWrapperMain
  Command: C:\Users\asus\Downloads\flutter tuto\flutter tuto\12 Flutter Basic Layouts & Container Widgets\078 intro-layouts-containers\intro_layouts_containers\android\gradlew.bat -v
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:185:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:166:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.10586], locale
    fr-FR)
    [32m•[39m Flutter version 1.0.0 at C:\flutter
    [32m•[39m Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at C:\Users\asus\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 31.3.3
    [32m•[39m Dart plugin version 182.5124
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.30.2)
    [32m•[39m VS Code at C:\Users\asus\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 2.21.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Moto C • ZY322DHQ9F • android-arm • Android 7.0 (API 24)

[32m•[39m No issues found!
```

**Comment by zoechi** [comment]
I'd try to move the project to a path without space and `&` and perhaps a shorter path instead of

```
  Command: C:\Users\asus\Downloads\flutter tuto\flutter tuto\12 Flutter Basic Layouts & Container Widgets\078 intro-layouts-containers\intro_layouts_containers\android\gradlew.bat -v
```

**Comment by Thorsenna** [comment]
That worked , thanks !!

**Comment by Thorsenna** [comment]
> I'd try to move the project to a path without space and `&` and perhaps a shorter path instead of
> 
> ```
>   Command: C:\Users\asus\Downloads\flutter tuto\flutter tuto\12 Flutter Basic Layouts & Container Widgets\078 intro-layouts-containers\intro_layouts_containers\android\gradlew.bat -v
> ```

thatt worked thanks !!

**Comment by zanderso** [comment]
@blasten is this the same issue as the one you fixed recently?

**Comment by blasten** [comment]
Yup!
