### ISSUE TITLE
Image picker plugin crash with Yandex.Disk

### ISSUE THREAD

**Issue by ZzZombo** [flutter/flutter#26940]
## Steps to Reproduce
1. Launch image picker with the gallery as the source.
2. Use Yandex.Disk as the provider.
3. Choose `Обои для рабочего стола.jpg`.

## Logs

```D/GraphicBuffer(28315): register, handle(0x9832af10) (w:720 h:1196 s:720 f:0x1 u:0x000f02)
D/GraphicBuffer(28315): register, handle(0x98329fc0) (w:720 h:1196 s:720 f:0x1 u:0x000f02)
D/SettingsInterface(28315):  from settings cache , name = sound_effects_enabled , value = 0
D/ActivityThread(28315): ACT-AM_ON_PAUSE_CALLED ActivityRecord{2e659f3 token=android.os.BinderProxy@6e86b0 {app.com.example.flutterapp/app.com.example.flutterapp.MainActivity}}
D/ActivityThread(28315): ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@6e86b0
I/SurfaceView(28315): updateWindow -- onWindowVisibilityChanged, visibility = 8, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): Cur surface: Surface(name=null)/@0x1e58236, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): New surface: Surface(name=null)/@0x8291537, vis=false, frame=Rect(0, 0 - 1196, 720), this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): Callback --> surfaceDestroyed, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): surfaceDestroyed callback +, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
D/Surface (28315): Surface::disconnect(this=0x9abfcb00,api=1)
D/GraphicBuffer(28315): unregister, handle(0x9832b0d0) (w:720 h:1196 s:720 f:0x1 u:0x000f02)
D/GraphicBuffer(28315): unregister, handle(0x9832af10) (w:720 h:1196 s:720 f:0x1 u:0x000f02)
D/GraphicBuffer(28315): unregister, handle(0x98329fc0) (w:720 h:1196 s:720 f:0x1 u:0x000f02)
D/Surface (28315): Surface::disconnect(this=0x9abfcb00,api=1)
I/SurfaceView(28315): surfaceDestroyed callback -, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
V/SurfaceView(28315): Layout: x=0 y=0 w=1196 h=720, frame=Rect(0, 0 - 1196, 720), this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
D/Surface (28315): Surface::disconnect(this=0x9fcfcf00,api=1)
D/GraphicBuffer(28315): unregister, handle(0xab159370) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
D/Surface (28315): Surface::disconnect(this=0x9fcfcf00,api=1)
I/SurfaceView(28315): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
V/ActivityThread(28315): Finishing stop of ActivityRecord{2e659f3 token=android.os.BinderProxy@6e86b0 {app.com.example.flutterapp/app.com.example.flutterapp.MainActivity}}: show=false win=com.android.internal.policy.PhoneWindow@c23ee5b
V/PhoneWindow(28315): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{2c59b55 app.com.example.flutterapp/app.com.example.flutterapp.MainActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{402a24f I.E...... R......D 0,0-1280,720}
D/ActivityThread(28315): ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@6e86b0
I/SurfaceView(28315): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): updateWindow -- onWindowVisibilityChanged, visibility = 4, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
I/SurfaceView(28315): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a59a5e3 VFE...... .F...... 0,0-1196,720}
D/ActivityThread(28315): holder:android.app.IActivityManager$ContentProviderHolder@208e7a6, holder.provider:android.content.ContentProviderProxy@4c365e7
V/ProviderLeakDetecter(28315): Cursor Open:226220093 Total Opened Cursor Count:1.
V/ProviderLeakDetecter(28315): Cursor Close:226220093 Total Opened Cursor Count:0.
D/AndroidRuntime(28315): Shutting down VM
E/AndroidRuntime(28315): FATAL EXCEPTION: main
E/AndroidRuntime(28315): Process: app.com.example.flutterapp, PID: 28315
E/AndroidRuntime(28315): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://ru.yandex.disk.filescache/d0/Обои для рабочего стола.jpg flg=0x1 }} to activity {app.com.example.flutterapp/app.com.example.flutterapp.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime(28315): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3940)
E/AndroidRuntime(28315): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3983)
E/AndroidRuntime(28315): 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
E/AndroidRuntime(28315): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
E/AndroidRuntime(28315): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(28315): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(28315): 	at android.app.ActivityThread.main(ActivityThread.java:5765)
E/AndroidRuntime(28315): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28315): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(28315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:683)
E/AndroidRuntime(28315): Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
E/AndroidRuntime(28315): 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
E/AndroidRuntime(28315): 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
E/AndroidRuntime(28315): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:119)
E/AndroidRuntime(28315): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:101)
E/AndroidRuntime(28315): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime(28315): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime(28315): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(28315): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(28315): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(28315): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(28315): 	at app.com.example.flutterapp.MainActivity.onActivityResult(MainActivity.kt:71)
E/AndroidRuntime(28315): 	at android.app.Activity.dispatchActivityResult(Activity.java:6500)
E/AndroidRuntime(28315): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3936)
E/AndroidRuntime(28315): 	... 9 more
I/Process (28315): Sending signal. PID: 28315 SIG: 9
Lost connection to device.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ZzZombo** [comment]
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale ru-RU)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\<dir>\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    X Android license status unknown.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\<dir>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • LEAGOO M8 • YDIFWWUKEELFQOC6 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by pepegich** [comment]
fixed https://github.com/flutter/plugins/pull/1265

**Comment by mayankverma3333** [comment]
i am also facing same issue .
any solution?
