### ISSUE TITLE
running integration tests with option --flavor development returns timeout

### ISSUE THREAD

**Issue by YAPSHUB** [flutter/flutter#26968]
I am able to run flutter run --flavor development without any error, however when I intend to run integration tests with flutter driver --target=test_driver/app.dart --flavor development, i run into this error. App is installed but tests fail.

Any help or pointers to solve this is highly appreciated.

*Error Log*

 DriverError: Timed out waiting for Flutter Driver extension to become available. Ensure your test app (often: lib/main.dart) imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
  Original error: null
  Original stack trace:
  null

  package:flutter_driver/src/driver/driver.dart 355:9  FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                    _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18         _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart        FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                         _CustomZone.registerBinaryCallback
  dart:async/runtime/libasync_patch.dart 86:23         _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart        FlutterDriver.connect
  test_driver/security_test.dart 15:36                 main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                         _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                          _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 529:34                        Future.doWhile
  dart:async/future.dart 489:12                        Future.forEach
  package:test_api/src/backend/declarer.dart 291:36    Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/declarer.dart 291:14    Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 399:25     Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                         _CustomZone.registerCallback
  dart:async/zone.dart 962:22                          _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                          new Timer
  dart:async/timer.dart 87:9                           Timer.run
  dart:async/future.dart 174:11                        new Future
  package:test_api/src/backend/invoker.dart 398:11     Invoker._onRun.<fn>.<fn>.<fn>

01:00 +0 -1: Security App (tearDownAll)
01:00 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by jlhour** [comment]
Thanks for noticing it. Any way to bypass the issue in the meantime?

**Comment by YAPSHUB** [comment]
@jlhour I'm afraid not. It is unclear where the timeout error is generated from.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce this using the example flavors app in the flutter repo. The line `import 'package:test/main.dart' as app` is questionable - is you application named `test`?

**Comment by YAPSHUB** [comment]
application name is something different, just for reporting the bug, i replaced it with test. 
Could I send any other information to be able to reproduce the bug?

**Comment by natefrechette** [comment]
I hit the same issue in my application for iOS. I found that the issue was xcode's build configuration was overriding the `--target` file flutter drive was running. 

So to fix this, I added a `Debug-testing` scheme to my XCode project and pointed its `FLUTTER_TARGET`  build setting to my `test_driver/app.dart` file.

Now when I run: `flutter drive --target=test_driver/app.dart --flavor testing --debug` it correctly calls the flutter driver app and allows the FlutterDriver to connect and not time out.

Hope this helps!

**Comment by jonahwilliams** [comment]
Thank you @natefrechette, that is very helpful information

**Comment by randikachan** [comment]
It will be great if you can add bit more information on your approach @natefrechette :-)
Thanks in advance!

**Comment by natefrechette** [comment]
Sure! I made a video a while ago detailing how I set up my apps to run in multiple environments (dev, staging, prod, etc) which ties into how I run my integration tests (hopefully you will find that helpful). I would follow this setup first so that your app is setup to be able to target specific build modes for different environments 

https://www.youtube.com/watch?v=AxEmcv0askc

Regarding running integration tests on iOS, once my project is setup to run on different environments, I do the following to make sure I can run integration tests:

<img width="315" alt="Screen Shot 2019-09-30 at 10 16 58 AM" src="https://user-images.githubusercontent.com/5225094/65887698-6317fb80-e36c-11e9-8735-13dcf691a3cf.png">

Focus on the highlighted `lib/app/flavors/main_testing.dart` & `test_drive/app.dart` files. `test_driver/app.dart` (creates the app for integration testing) is the file I point to when running integration tests, and it imports `main_testing.dart` (creates the app for the testing environment) as shown below

<img width="664" alt="Screen Shot 2019-09-30 at 10 33 25 AM" src="https://user-images.githubusercontent.com/5225094/65888772-12a19d80-e36e-11e9-8974-49d89882744e.png">

- Unfortunately, when you run flutter drive and just point to `test_driver/app.dart`, it does not work for the reasons detailed above. It appears XCode does not respect the `--target` parameter and instead, uses the `FLUTTER_TARGET` value specified in XCOde build settings
- So, set the `FLUTTER_TARGET` build setting to point to the `test_driver_app.dart` file as shown in the screenshot below. 

<img width="1163" alt="Screen Shot 2019-09-30 at 10 21 08 AM" src="https://user-images.githubusercontent.com/5225094/65888078-ef2a2300-e36c-11e9-9935-d1e42a3f57e2.png">

That way, when you run `flutter drive --target=test_driver/app.dart --flavor testing --debug` flutter driver knows to run the test located at `test_driver/app.dart, use the `testing` flavor and to run it in debug mode. `FLUTTER_TARGET` ensures XCode uses the correct main dart file

I hope this helps. Follow the youtube video plus these steps and you should be good to go. If not comment and I can provide more assistance.

Cheers

**Comment by randikachan** [comment]
Thank you @natefrechette for the prompt reply, will look into this! 👍

**Comment by avioli** [comment]
For me, the issue was that I had a line in my `Config.xcconfig` redefining the `FLUTTER_TARGET`:

```
FLUTTER_TARGET=lib/main-${FLAVOR}.dart
```

Since flutter itself exports that in `Generated.xcconfig` I removed the line and all started working as expected.

**Comment by rfitz123** [comment]
Has anybody had this issue on android specifically? I don't have an identical issue, but the `flutter drive` command seems to be ignoring my `flavor`, which causes subsequent errors. It runs `assembleDebug` instead of `assembleAlphaDebug`

**Comment by thirumalraopathi** [comment]
hi natefrechette

i am facing below issue while running flutter driver to test futter app any suggestions or help
i tried in android emulator and real android device 

Unhandled exception:
TimeoutException after 0:01:30.000000: Timeout while waiting for observatory debugger uri

**Comment by natefrechette** [comment]
Hey @thirumalraopathi can you provide me with some more information about your setup? What command are you running for your driver tests?

**Comment by thirumalraopathi** [comment]
> 

@natefrechette  it got resolved finally thanks a lot for your quick response :).

it was issue in build.gradle file i made changes by removing flavors ,signing config, keystore properties then it started working

**Comment by kritika333** [comment]
I navigated from this post #132471. I am getting this error Unhandled exception:
TimeoutException after 0:01:30.000000: Timeout while waiting for observatory debugger uri
 when trying to run BDD test cases. when I am only running app its running with no issues but when running test cases with command flutter drive --target=test_driver/app.dart . then my build is passing and app is launching successfully but getting this error. My files are same as given in post #132471. Can some one please suggest something

**Comment by ankigure22** [comment]
> keystore



> I navigated from this post #132471. I am getting this error Unhandled exception: TimeoutException after 0:01:30.000000: Timeout while waiting for observatory debugger uri when trying to run BDD test cases. when I am only running app its running with no issues but when running test cases with command flutter drive --target=test_driver/app.dart . then my build is passing and app is launching successfully but getting this error. My files are same as given in post #132471. Can some one please suggest something. I am getting this error on both android and ios.

I am also facing the same issue which was mentioned above and i am on latest flutter and dart verion.

**Comment by Rarsh1992** [comment]
> > keystore
> 
> > I navigated from this post #132471. I am getting this error Unhandled exception: TimeoutException after 0:01:30.000000: Timeout while waiting for observatory debugger uri when trying to run BDD test cases. when I am only running app its running with no issues but when running test cases with command flutter drive --target=test_driver/app.dart . then my build is passing and app is launching successfully but getting this error. My files are same as given in post #132471. Can some one please suggest something. I am getting this error on both android and ios.
> 
> I am also facing the same issue which was mentioned above and i am on latest flutter and dart verion.

Hi There,

Did you manage to resolve this issue?
If so could you please tell me whats the fix.
:)

Thanks

**Comment by hiraowais** [comment]
> Hi I navigated from this post #132471. but this issue was closed without any resolution. Is there a way/workround to fix this problem.
> 
> Command I am using to run tests: flutter clean && flutter drive -t "test_driver/bdd.dart"
> 
> Observation: app launches fine in both ios/android emulator, but then everything halts and just 1 line error message appears.
> 
> "Unhandled exception: TimeoutException after 0:03:00.000000: Timeout while waiting for observatory debugger uri"
> 
> Flutter doctor output: Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-x64, locale en-IE) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0) [✓] Xcode - develop for iOS and macOS (Xcode 15.0.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2023.1) [✓] IntelliJ IDEA Community Edition (version 2022.2.2) [✓] VS Code (version 1.84.2) [✓] Connected device (3 available) [✓] Network resources
> 
> I have used enableFlutterDriverExtension(); too
> 
> Nothing is working.
> 
> I'll really appreciate if someone could help me get over this issue,Please
> 
> Thanks

@Rarsh1992 
I'm having the same issue. Were you ever able to resolve it? Thanks
