### ISSUE TITLE
exception was catched but exception information still show in debug console(on android)

### ISSUE THREAD

**Issue by shyandsy** [flutter/flutter#27014]
## Steps to Reproduce

https://github.com/shyandsy/cipher2

1. download this plugin, and run example code on android

2. the exception was catched, but the exception information still show in output console

(for ios, these exception information doesnt show)

## Logs

```
E/MethodChannel#cipher2(21849): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
E/MethodChannel#cipher2(21849): 	at com.shyandsy.cipher2.Cipher2Plugin.onMethodCall(Cipher2Plugin.kt:79)
E/MethodChannel#cipher2(21849): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#cipher2(21849): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#cipher2(21849): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#cipher2(21849): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#cipher2(21849): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#cipher2(21849): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#cipher2(21849): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#cipher2(21849): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#cipher2(21849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/FlutterNativeView(21849): Uncaught exception in binary message listener
E/FlutterNativeView(21849): java.lang.IllegalStateException: Reply already submitted
E/FlutterNativeView(21849): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/FlutterNativeView(21849): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:218)
E/FlutterNativeView(21849): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/FlutterNativeView(21849): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(21849): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/FlutterNativeView(21849): 	at android.os.Looper.loop(Looper.java:160)
E/FlutterNativeView(21849): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/FlutterNativeView(21849): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(21849): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/FlutterNativeView(21849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (21849): testDecrytion case6: pass
```

**Comment by zoechi** [comment]
I haven't built a plugin myself yet 
but my guess is you should add `return;` after each `result.success(...)` or `result.error(...)` to avoid it being called multiple times.
Just a wild guess.
