### ISSUE TITLE
Multiple widgets used the same GlobalKey with using GlobalKey TabBarView AutomaticKeepAliveClientMixin

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#27010]
I want use Tab1's(which `AutomaticKeepAliveClientMixin` is `true`) context to do something other, i try to use a global key to store it, but when tab to Tab2, the exception will throw.

## Steps to Reproduce

1. run demo in main.txt(please change file type to .dart)
2. tab on Tab2

## Logs
```
I/flutter (16780): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16780): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (16780): Multiple widgets used the same GlobalKey.
I/flutter (16780): The key [GlobalKey#b6544] was used by multiple widgets. The parents of those widgets were:
I/flutter (16780): - RepaintBoundary-[<[GlobalKey#b6544]>](renderObject: RenderRepaintBoundary#b9717)
I/flutter (16780): - RepaintBoundary-[<[GlobalKey#b6544]>](renderObject: RenderRepaintBoundary#aad53 NEEDS-LAYOUT
I/flutter (16780):   NEEDS-PAINT)
I/flutter (16780): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter (16780): 
I/flutter (16780): When the exception was thrown, this was the stack:
I/flutter (16780): #0      GlobalKey._debugReserveFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:172:11)
I/flutter (16780): #1      GlobalKey._debugReserveFor (package:flutter/src/widgets/framework.dart:190:6)
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  TabController primaryTC;
  final GlobalKey<State> list1Key = new GlobalKey<State>();
  @override
  void initState() {
    primaryTC = new TabController(length: 3, vsync: this);
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    var primaryTabBar = new TabBar(
      controller: primaryTC,
      labelColor: Colors.blue,
      indicatorColor: Colors.blue,
      indicatorSize: TabBarIndicatorSize.label,
      indicatorWeight: 2.0,
      isScrollable: false,
      unselectedLabelColor: Colors.grey,
      tabs: [
        Tab(text: "Tab0"),
        Tab(text: "Tab1"),
        Tab(text: "Tab2"),
      ],
    );
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Column(
          children: <Widget>[
            primaryTabBar,
            Expanded(
              child: TabBarView(
                children: <Widget>[
                  List1(list1Key),
                  List2(),
                  List3(),
                ],
                controller: primaryTC,
              ),
            )
          ],
        ));
  }
}

class List1 extends StatefulWidget {
  List1(Key key) : super(key: key);
  @override
  _List1State createState() => _List1State();
}

class _List1State extends State<List1> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
      //store Page state
      itemBuilder: (c, i) {
        return Container(
          alignment: Alignment.center,
          height: 60.0,
          child: Text(Key("Tab2").toString() + ": ListView$i"),
        );
      },
      itemCount: 50,
    );
  }

  @override
  void updateKeepAlive() {
    // TODO: implement updateKeepAlive
    super.updateKeepAlive();
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}

class List2 extends StatefulWidget {
  @override
  _List2State createState() => _List2State();
}

class _List2State extends State<List2> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
      //store Page state
      itemBuilder: (c, i) {
        return Container(
          alignment: Alignment.center,
          height: 60.0,
          child: Text(Key("Tab2").toString() + ": ListView$i"),
        );
      },
      itemCount: 50,
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}

class List3 extends StatefulWidget {
  @override
  _List3State createState() => _List3State();
}

class _List3State extends State<List3> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
      //store Page state
      itemBuilder: (c, i) {
        return Container(
          alignment: Alignment.center,
          height: 60.0,
          child: Text(Key("Tab2").toString() + ": ListView$i"),
        );
      },
      itemCount: 50,
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}
```

```
D:\Flutter\flutter_source\dev>flutter doctor -v
[√] Flutter (Channel dev, v1.1.9, on Microsoft Windows [Version 10.0.17134.523], locale zh-CN)
    • Flutter version 1.1.9 at D:\Flutter\flutter_source\dev
    • Framework revision 1407091bfb (2 weeks ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • MI 6 • 5a4b233b • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by zoechi** [comment]
The error is similar to #24660

**Comment by pepegich** [comment]
same issue if call     _controller.animateTo(0) if current index is 2. jump over 1 tab.

**Comment by SteveAlexander** [comment]
I'm still waiting for a review of my PR that fixes this: https://github.com/flutter/flutter/pull/24821

You might try applying the PR if you're encountering this problem, and reporting whether it fixes it for you.

**Comment by pbouttier** [comment]
I can confirm, it fix the problem. I hope a quick integration :D

**Comment by carmas123** [comment]
Fix using https://pub.dartlang.org/packages/extended_tabs

**Comment by zmtzawqlp** [comment]
@carmas123,   i use @SteveAlexander code in extended tabs , i can't wait the pr of SteveAlexander

**Comment by HansMuller** [comment]
Here's a simpler test case: https://gist.github.com/HansMuller/4410e538db815fec41dda23da84a08f4

The source of the problem appears to be the temporary reordering of the TabBarView's PageView to enable the "warp" animation from the first tab to the last. If the first TabBarView child has a GlobalKey, the reported failure occurs.

@chunhtai - I'd been hoping that https://github.com/flutter/flutter/pull/29188 would have fixed this case?

**Comment by chunhtai** [comment]
yes, it should fix the issue, I am currently fixing failing test to reland it

**Comment by HansMuller** [comment]
I just confirmed that #29188 does fix the problem demonstrated by my simplified version of the test case: https://gist.github.com/HansMuller/4410e538db815fec41dda23da84a08f4

**Comment by HansMuller** [comment]
I can also confirm that #29188 corrects the problem with the original test case: https://gist.github.com/HansMuller/fc28f5c4850530525154157bada89cd1

**Comment by shihaohong** [comment]
I just tested the original test case provided by @zmtzawqlp and it no longer throws an error in the master branch. Seems to have been fixed by https://github.com/flutter/flutter/pull/31978
