### ISSUE TITLE
FadeInImage does not work as intended when filtering the dataset (Reposted issue)

### ISSUE THREAD

**Issue by namanix** [flutter/flutter#27031]
I've already posted this bug before but it got closed due to inactivity.

Currently i'm trying to create a userlist with search function and a small picture in front of every user.
When i first load everything in it works well. But when i start searching. The pictures in front of the users don't correspond with the correct users anymore.

To make this a lot easier to reproduce, i've created a sample project (I did this because a fallback image on the local system is needed).
Just run the app. Wait for the picture to load (Only the first picture will load. The second one will 404 but that's intended). When the picture is loaded click on "Press here" and you will see that the url containing the 404 picture will be displayed in front of a working picture. (`https://google.nl/404.jpg` will be placed in front of the working picture).

As a small addition. This does not happen with the normal Image widget. Only with the FadeInImage

Sample project: [Flutter_FadeInImageBug](https://github.com/namanix/Flutter_FadeInImageBug)

**Comment by zoechi** [comment]
The image link is broken https://google.nl/404.jpg

**Comment by zoechi** [comment]
This is probably because `"https://google.nl/404.jpg"` causes 
```
I/flutter ( 8753): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 8753): The following _Exception was thrown resolving an image codec:
I/flutter ( 8753): Exception: HTTP request failed, statusCode: 404, https://google.nl/404.jpg
I/flutter ( 8753): 
I/flutter ( 8753): When the exception was thrown, this was the stack:
I/flutter ( 8753): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:496:7)
I/flutter ( 8753): <asynchronous suspension>
I/flutter ( 8753): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:475:14)
I/flutter ( 8753): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:285:105)
```

**Comment by zoechi** [comment]
What about 
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  //First picture exists. Second is 404
  Map<String, bool> sampleData = {
    "https://static-news.moneycontrol.com/static-mcnews/2018/08/Germany.jpg":
        false,
    "https://google.nl/404.jpg": false,
  };

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    _preCacheImage();
  }

  void _preCacheImage() async {
    for (final imageKey in sampleData.keys) {
      bool succeeded = true;
      await precacheImage(NetworkImage(imageKey), context,
          onError: (_, __) => succeeded = false);
      sampleData[imageKey] = succeeded;
    }
  }

  void removeFirst() {
    setState(() {
      sampleData.remove(sampleData.keys.first);
      print("Did it!");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        children: <Widget>[
          Container(
            child: ListView.builder(
                itemCount: sampleData == null ? 0 : sampleData.length,
                itemBuilder: (BuildContext context, int index) {
                  final key = sampleData.keys.toList()[index];
                  return ListTile(
                    key: ValueKey<String>(key),
                    title: Text(key),
                    leading: FadeInImage(
                      placeholder: AssetImage('assets/FallBackUsersImage.jpg'),
                      image: sampleData[key]
                          ? NetworkImage(key)
                          : AssetImage('assets/FallBackUsersImage.jpg'),
                      width: 50.0,
                    ),
                  );
                }),
            height: 200.0,
          ),
          InkWell(
            child: Padding(
              padding: EdgeInsets.all(20.0),
              child: Text('Press here'),
            ),
            onTap: removeFirst,
          ),
        ],
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Made a small change

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
