### ISSUE TITLE
flutter_crashlytics issue: MissingPluginException

### ISSUE THREAD

**Issue by yjoo9317** [flutter/flutter#27055]
## Steps to Reproduce

I've been trying to use fluter_crashlytics as explained at https://pub.dartlang.org/packages/flutter_crashlytics

But when it tried to initialize with ```FlutterCrashlytics().initialize()```, it returns Dart Error: 
```
Unhandled exception:
MissingPluginException(No implementation found for method initialize on channel flutter_crashlytics).
```

Which is coming from platfom_channel.dart
```dart
    final dynamic result = await BinaryMessages.send(
      name,
      codec.encodeMethodCall(MethodCall(method, arguments)),
    );
    if (result == null)
      throw MissingPluginException('No implementation found for method $method on channel $name');
    return codec.decodeEnvelope(result);
```

That means should I implement "flutter_crashlytics" channel?
The page didn't mention about that.
So I thought the plugin should provide that implementation.
Or Maybe I am missing a big basic thing here.
Thanks.

No issue from Doctor.
I am using version 1.0.0
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
```
## Logs

```
Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method initialize on channel flutter_crashlytics)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
<asynchronous suspension>
#1      FlutterCrashlytics.initialize (package:flutter_crashlytics/flutter_crashlytics.dart:18:53)
<asynchronous suspension>
#2      main (package:my_package/main.dart:24:30)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
```

```
```

**Comment by zoechi** [comment]
Have you tried reporting in https://github.com/kiwi-bop/flutter_crashlytics/issues
`flutter_crashlytics` is a community project not maintained by the Flutter team.

**Comment by yjoo9317** [comment]
OK. Fair enough. Thanks.
