### ISSUE TITLE
Flutter view in Android app is not notified in release mode when the device size changes

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#27051]
Repro steps here: https://stackoverflow.com/questions/53838043/how-to-rebuild-flutter-widgets-when-device-size-changes-in-release-mode-for-flu

This seems specific to a Flutter View inside an Android app in release mode. I tried reproducing it on a 100% Flutter app and didn't find a difference between debug and release mode (but this was a while ago).

Pasted here:
 1. Pull down this example: https://github.com/flutter/flutter/tree/master/examples/flutter_view
 2. Replace main.dart with (I know it's messy):
```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(FlutterView());
}

class FlutterView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter View',
      theme: ThemeData(
        primarySwatch: Colors.grey,
      ),
      home: RandomContainer(),
    );
  }
}

class RandomContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    print('maryx $size');
    return MyHomePage(
      title: 'Flutter Demo Home Page',
      width: size.width,
      height: size.height,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key key,
    this.title,
    this.width,
    this.height,
  }) : super(key: key);

  final String title;
  final double width;
  final double height;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String _channel = 'increment';
  static const String _pong = 'pong';
  static const String _emptyMessage = '';
  static const BasicMessageChannel<String> platform =
      BasicMessageChannel<String>(_channel, StringCodec());

  int _counter = 0;

  Widget _image = Container();

  @override
  void initState() {
    super.initState();
    platform.setMessageHandler(_handlePlatformIncrement);
    _buildImage();
  }

  Future<String> _handlePlatformIncrement(String message) async {
    setState(() {
      _counter++;
    });
    return _emptyMessage;
  }

  void _sendFlutterIncrement() {
    platform.send(_pong);
  }

  Widget _buildWidgets() {
    final size = MediaQuery.of(context).size;
    return Stack(
      children: [
        Center(
          child: Container(
            width: size.width - 50.0,
            height: 100.0,
            color: Colors.pink[900],
          ),
        ),
        Center(
          child: _image,
        ),
        Center(
            child: Container(
          width: 100.0,
          height: 50.0,
          color: Colors.pink[200],
        )),
      ],
    );
  }

  Future<void> _buildImage() async {
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);

    final rrect = ui.RRect.fromRectAndRadius(
        ui.Rect.fromLTWH(0.0, 0.0, widget.width, 100.0),
        Radius.circular(widget.width / 2));
    canvas.drawRRect(rrect, ui.Paint()..color = Colors.pink[500]);

    // Save drawing into a png.
    final picture = recorder.endRecording();
    final image = await picture.toImage(widget.width.toInt(), 100);
    final pngBytes = await image.toByteData(format: ui.ImageByteFormat.png);

    // See https://github.com/flutter/flutter/issues/6246
    if (!mounted) return;

    // Save png as an Image widget.
    setState(() {
      _image = Image.memory(
        pngBytes.buffer.asUint8List(),
        height: 100,
        width: widget.width,
        fit: BoxFit.cover,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Expanded(
            child: Center(
                child: Text(
                    'Platform button tapped $_counter time${_counter == 1 ? '' : 's'}.',
                    style: const TextStyle(fontSize: 17.0))),
          ),
          _buildWidgets(),
          Container(
            padding: const EdgeInsets.only(bottom: 15.0, left: 5.0),
            child: Row(
              children: <Widget>[
                Image.asset('assets/flutter-mark-square-64.png', scale: 1.5),
                const Text('Flutter', style: TextStyle(fontSize: 30.0)),
              ],
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _sendFlutterIncrement,
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

Debug: 
![image](https://user-images.githubusercontent.com/3357543/51712681-70facd00-1fe4-11e9-8415-65382cb30d5c.png)

Release:
![image](https://user-images.githubusercontent.com/3357543/51712689-77894480-1fe4-11e9-86e3-3d13c4a9f649.png)

In debug mode, the widget draws correctly, but in release mode, the widget is sized 0x0 because at the moment that it's being drawn, the device size is 0x0. This seems to be related: https://github.com/flutter/flutter/issues/11697

How do I tell the widget to redraw once its size changes? Supposedly both LayoutBuilder and MediaQuery should be telling the widget to redraw, and when I add print statements, the device size IS changing:

```
12-18 12:01:31.084  1587  1752 I flutter : device: Size(0.0, 0.0)
12-18 12:01:31.087  1587  1752 I flutter : length 200.0 // hardcoded widget, used as a control (does not depend on device size)
12-18 12:01:31.088  1587  1752 I flutter : length 0.0 // widget based on device size
12-18 12:01:31.089  1587  1752 I flutter : length 0.0 // widget based on device size
12-18 12:01:31.563  1587  1752 I flutter : device: Size(600.0, 400.0)
```
and I would've expected the middle 3 lines to repeat (redraw) but they don't.

For comparison, this is what it looks like in debug mode. It completely bypasses the 0x0 device size:
```
12-18 12:10:44.506  1897  2063 I flutter : device: Size(600.0, 400.0)
12-18 12:10:44.593  1897  2063 I flutter : length 200.0
12-18 12:10:44.627  1897  2063 I flutter : length 563.3333333333334
12-18 12:10:44.631  1897  2063 I flutter : length 333.3333333333334
```

Flutter doctor:
```
[✓] Flutter (Channel master, v1.1.10-pre.170, on Mac OS X 10.13.6 17G4015, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)
```
(aware of iOS issues, but I'm running the example via Terminal and on an Android device)

**Comment by zoechi** [comment]
There is the known behavior that in release mode, probably because the app start quicker, the first update that notifies about the screen size is 0x0 and only a bit later the real size is pushed.

Perhaps there should be an event listener registered to get notified about updates instead only reading the first value.

What is the behavior when you rotate the phone? Does it update?

**Comment by zoechi** [comment]
I made a few changes
```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(FlutterView());
}

class FlutterView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter View',
      theme: ThemeData(
        primarySwatch: Colors.grey,
      ),
      home: RandomContainer(),
    );
  }
}

class RandomContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    print('maryx $size');
    return MyHomePage(
      title: 'Flutter Demo Home Page',
      width: size.width == 0 ? 1 : size.width,
      height: size.height == 0 ? 1 : size.height,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key key,
    this.title,
    this.width,
    this.height,
  }) : super(key: key);

  final String title;
  final double width;
  final double height;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String _channel = 'increment';
  static const String _pong = 'pong';
  static const String _emptyMessage = '';
  static const BasicMessageChannel<String> platform =
      BasicMessageChannel<String>(_channel, StringCodec());

  int _counter = 0;

  Widget _image = Container();

  @override
  void initState() {
    super.initState();
    platform.setMessageHandler(_handlePlatformIncrement);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _buildImage();
  }

  Future<String> _handlePlatformIncrement(String message) async {
    setState(() {
      _counter++;
    });
    return _emptyMessage;
  }

  void _sendFlutterIncrement() {
    platform.send(_pong);
  }

  Widget _buildWidgets() {
    final size = MediaQuery.of(context).size;
    return Stack(
      children: [
        Center(
          child: Container(
            width: size.width - 50.0,
            height: 100.0,
            color: Colors.pink[900],
          ),
        ),
        Center(
          child: _image,
        ),
        Center(
            child: Container(
          width: 100.0,
          height: 50.0,
          color: Colors.pink[200],
        )),
      ],
    );
  }

  Future<void> _buildImage() async {
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);

    final rrect = ui.RRect.fromRectAndRadius(
        ui.Rect.fromLTWH(0.0, 0.0, widget.width, 100.0),
        Radius.circular(widget.width / 2));
    canvas.drawRRect(rrect, ui.Paint()..color = Colors.pink[500]);

    // Save drawing into a png.
    final picture = recorder.endRecording();
    final image = await picture.toImage(widget.width.toInt(), 100);
    final pngBytes = await image.toByteData(format: ui.ImageByteFormat.png);

    // See https://github.com/flutter/flutter/issues/6246
    if (!mounted) return;

    // Save png as an Image widget.
    setState(() {
      _image = Image.memory(
        pngBytes.buffer.asUint8List(),
        height: 100,
        width: widget.width,
        fit: BoxFit.cover,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Expanded(
            child: Center(
                child: Text(
                    'Platform button tapped $_counter time${_counter == 1 ? '' : 's'}.',
                    style: const TextStyle(fontSize: 17.0))),
          ),
          _buildWidgets(),
          Container(
            padding: const EdgeInsets.only(bottom: 15.0, left: 5.0),
            child: Row(
              children: <Widget>[
                Image.asset('assets/FallBackUsersImage.jpg', scale: 6),
                const Text('Flutter', style: TextStyle(fontSize: 30.0)),
              ],
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _sendFlutterIncrement,
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
it doesn't look the same as your release build screenshots, but it should you give some ideas what went wrong.

**Comment by maryx** [comment]
Yep, understand that it starts off as 0x0 in release mode.

When I rotate (with the code I pasted above), there is a change in size for sure, but the code doesn't update to resize:
```
I/flutter (17565): maryx Size(0.0, 0.0) // Initial size
I/flutter (17565): 0.0
E/flutter (17565): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter (17565): Exception: Invalid image dimensions.
E/flutter (17565): #0      Picture.toImage (dart:ui/painting.dart:3689)
E/flutter (17565): #1      _MyHomePageState._buildImage (package:flutter_view/main.dart:117)
E/flutter (17565): <asynchronous suspension>
E/flutter (17565): #2      _MyHomePageState.initState (package:flutter_view/main.dart:68)
E/flutter (17565): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830)
E/flutter (17565): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696)
E/flutter (17565): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732)
E/flutter (17565): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
E/flutter (17565): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701)
E/flutter (17565): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696)
E/flutter (17565): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860)
E/flutter (17565): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732)
E/flutter (17565): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
E/flutter (17565): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701)
E/flutter (17565): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696)
E/flutter (17565): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860)
E/flutter (17565): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860)
E/flutter (17565): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860)
E/flutter (17565): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860)
E/flutter (17565): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732)
E/flutter (17565): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
E/flutter (17565): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701)
E/flutter (17565): #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848)
E/flutter (17565): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696)
E/flutter (17565): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732)
E/flutter (17565): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
E/flutter (17565): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701)
E/flutter (17565): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696)
E/flutter (17565): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950)
E/flutter (17565): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753)
E/flutter (17565): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3
I/flutter (17565): maryx Size(320.0, 260.7) // Originally portrait
I/flutter (17565): maryx Size(521.3, 160.0) // here is where I rotate the phone
```
I tried your code in release and debug and on first draw, the dark pink rectangle does show up, with no borderRadius because it thinks `widget.width` is 1. Upon rotating the screen, the borderRadius does change. But then rotating back to portrait mode, even though `widget.width` is 521, the image again has no borderRadius.

It seems like the device width/height are one step behind when I'm in both debug and release mode. When I load the app in portrait (in debug):
```
I/flutter (20120): maryx Size(320.0, 260.7)                             
I/flutter (20120): didChangeDependencies was just called                
I/flutter (20120): building an image (in _buildImage())                                    
I/flutter (20120): width of device: 320.0                               
I/flutter (20120): _buildWidgets() called, size of Size(320.0, 260.7)   
```
This loads the image fine with the border radius.

I rotate the screen to landscape:
```
I/flutter (20120): didChangeDependencies was just called
I/flutter (20120): building an image (in _buildImage())         
I/flutter (20120): width of device: 320.0
I/flutter (20120): maryx Size(521.3, 160.0)
I/flutter (20120): _buildWidgets() called, size of Size(521.3, 160.0)
I/flutter (20120): _buildWidgets() called, size of Size(521.3, 160.0)
```
This is strange, the print of Size does say the width is 521.3, but the `widget.width` value is still 320.
There is still a border radius but it's smaller than expected.

I rotate the screen back to portrait:
```
I/flutter (20120): didChangeDependencies was just called
I/flutter (20120): building an image (in _buildImage())         
I/flutter (20120): width of device: 521.3333333333334
I/flutter (20120): maryx Size(320.0, 260.7)
I/flutter (20120): _buildWidgets() called, size of Size(320.0, 260.7)
I/flutter (20120): _buildWidgets() called, size of Size(320.0, 260.7)
```

At this point, the border radius has disappeared on my image, although it reappears in landscape mode.

I see the main diffs in your code are:
 - Draw the image on didUpdateDependencies, not initState. This makes sense, and is a source of my issue. The wording for this could be clarified, that a developer has to listen to dependency changes rather than rely on MediaQuery to surface the update (`Querying the current media using MediaQuery.of will cause your widget to rebuild automatically whenever the MediaQueryData changes (e.g., if the user rotates their device).`) on https://docs.flutter.io/flutter/widgets/MediaQuery-class.html
 - Have a 1x1 as a placeholder in case the device is 0. I've been using this (with the device's dimensions) as a workaround so far.

I'll continue looking to see what can be wrong. I did note the width in `_buildWidgets` should be math.max(0, size.width - 50.0), otherwise there can be a BoxConstraints issue.

**Comment by zoechi** [comment]
> that a developer has to listen to dependency changes rather than rely on MediaQuery

That's not the problem. The problem is that you call `_buildImage()` only in `initState`. If you'd build it in `build()` where you query `MediaQuery` then it would also work but it would be inefficient because it would be rebuilt every time `build()` is called.
With `didChangeDependencies` it's only called when an `InheritedWidget` like `MediaQuery` notifies about a change.

I'm going to close. I think this should better be asked in one of the other channels listed in http://flutter.io/support.

If it turns out to actually be a Flutter issue or missing feature, feel free to create a new issue. Thanks!

**Comment by yn-tadpole** [comment]
MediaQuery is a bad idea. Sometimes we must initialize AnimationController in initState method with a device size, but MediaQuery cant work without a context.
window.physicalSize is a option, but it often return zero size  on app start in release mode as same as the MediaQuery. App run faster brings a problem. :(  Hope a solution.

**Comment by maryx** [comment]
@yn-tadpole Feel free to reopen this as an issue! I think ultimately I managed to do a workaround for my case but your example is valid (especially if you add a code snippet demonstrating it).

**Comment by yn-tadpole** [comment]
@maryx Good idea. look at the [https://github.com/flutter/flutter/issues/36533](url)
