### ISSUE TITLE
Android Alarm android.os.Looper 

### ISSUE THREAD

**Issue by tegarkurniawan** [flutter/flutter#27063]
## Steps to Reproduce
all code Java plugin error cannot resolve symbol and Exception has occurred.
```
PlatformException (PlatformException(error, Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference, null))
```

1. ... add plugin https://pub.dartlang.org/packages/android_alarm_manager#-installing-tab- 
2. ... follow instruction add service and Application.java and application name = '.Application'
3. ...

## Logs
```
Exception has occurred.
PlatformException (PlatformException(error, Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference, null))
Launching lib\main.dart on vivo 1723 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/AlarmService(32557): Starting AlarmService...
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:9)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.lyokone.location.LocationPlugin.<init>(LocationPlugin.java:76)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:211)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:16)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.example.csulsales.Application.registerWith(Application.java:18)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startAlarmService(AlarmService.java:65)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at android.os.Looper.loop(Looper.java:150)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at android.app.ActivityThread.main(ActivityThread.java:6800)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(32557): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.isWidgetCreationTrackedError -32601 received from application: Method not found
method not available: ext.flutter.debugPaintError -32601 received from application: Method not found
method not available: ext.flutter.showPerformanceOverlayError -32601 received from application: Method not found
method not available: ext.flutter.repaintRainbowError -32601 received from application: Method not found
method not available: ext.flutter.timeDilationError -32601 received from application: Method not found
method not available: ext.flutter.debugAllowBannerError -32601 received from application: Method not found
method not available: ext.flutter.debugPaintBaselinesEnabledError -32601 received from application: Method not found
method not available: ext.flutter.inspector.show
D/ViewRootImpl[MainActivity](32557): onDisplayChange oldDisplayState=2 newDisplayState=1
```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale id-ID)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.30.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by tegarkurniawan** [comment]
all code plugin java android alarm manager error cannot resolve symbol

**Comment by tegarkurniawan** [comment]
what is the solution to this problem?

**Comment by cbracken** [comment]
Thanks for your contribution. Since we haven't seen a reply, we're going to reluctantly close this bug for now, but if you're able to produce a reduced repro case, I'd encourage you do file a new bug with those details and refer back to this one in the comments.

**Comment by lucygeneric** [comment]
for reference, this one looks to be an issue with flutter location plugin, see here https://github.com/Lyokone/flutterlocation/issues/347
https://github.com/Lyokone/flutterlocation/pull/314
