### ISSUE TITLE
PopupMenuButton attribute initialValue with itemBuilder add PopupMenuDivider

### ISSUE THREAD

**Issue by mofada** [flutter/flutter#27072]
First , this is my code: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('PopupMenuButton'),
      ),
      body: Container(
        child: Center(
          child: PopupMenuButton<String>(
            child: Text('menu'),
            initialValue: '1',
            itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                  PopupMenuItem(
                    child: Text('1'),
                    value: '1',
                  ),
                  PopupMenuDivider(),
                  PopupMenuItem(
                    child: Text('2'),
                    value: '2',
                  ),
                ],
          ),
        ),
      ),
    );
  }
}
```

error screen:
![image](https://user-images.githubusercontent.com/22286246/51730977-6f98d580-20b4-11e9-9a04-2ce410e6775b.png)

========

When I run the code, everything works fine, but when I click on the `PopupMenuButton `problem, I looked at the error log and found that there is a problem with the `PopupMenuDivider `in the `itemBuilder`. The error log is attached below.

## Logs

```
I/flutter (21380): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21380): The following assertion was thrown building _PopupMenu<String>(dirty):
I/flutter (21380): type 'String' is not a subtype of type 'Null' of 'value'
I/flutter (21380): 
I/flutter (21380): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21380): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21380): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21380):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (21380): 
I/flutter (21380): When the exception was thrown, this was the stack:
I/flutter (21380): #0      PopupMenuDivider.represents (package:flutter/src/material/popup_menu.dart)
I/flutter (21380): #1      _PopupMenu.build (package:flutter/src/material/popup_menu.dart:446:56)
I/flutter (21380): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
I/flutter (21380): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (21380): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #5      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (21380): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (21380): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (21380): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #19     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (21380): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (21380): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (21380): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (21380): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #43     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (21380): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (21380): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (21380): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (21380): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (21380): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (21380): #53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (21380): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (21380): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (21380): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (21380): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (21380): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (21380): #60     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (21380): #61     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (21380): #62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (21380): (elided one frame from package dart:async)
I/flutter (21380): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
F:\WorkSpace\Flutter\flutter_widgets\flutter_widgets>flutter analyze
Analyzing flutter_widgets...

   info - Prefer using /// for doc comments - lib\beans\grid_item.dart:1:1 - slash_for_doc_comments
   info - Prefer using /// for doc comments - lib\page\main_page.dart:3:1 - slash_for_doc_comments
   info - Unused import: 'package:flutter/material.dart' - test\widget_test.dart:8:8 - unused_import
   info - Unused import: 'package:flutter_widgets/main.dart' - test\widget_test.dart:11:8 - unused_import

```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: D:\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android\android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
@jason-simmons

**Comment by jason-simmons** [comment]
@Hixie does the `PopupMenuDivider` class need to be parameterized?

**Comment by mofada** [comment]
Problems in this line.
![image](https://user-images.githubusercontent.com/22286246/51781155-c99aa900-214f-11e9-9660-e64c3615c107.png)
`PopupMenuDivider` The generic is `Null`, if I use `String`, but String is not a subclass of `Null`, then there will be problems.
![image](https://user-images.githubusercontent.com/22286246/51781160-ee8f1c00-214f-11e9-8ac7-973578656f6a.png)
