### ISSUE TITLE
WidgetsApp doesn't require onGenerateRoute but Navigator (which it uses) does.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2709]
```
I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
I/flutter : Exception caught while building WidgetsApp
I/flutter : 'packages/flutter/src/widgets/navigator.dart': Failed assertion: line 147: 'onGenerateRoute != null' is not true.
I/flutter : Stack trace:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      Navigator.Navigator (packages/flutter/src/widgets/navigator.dart:147)
I/flutter : #2      WidgetsAppState.build (packages/flutter/src/widgets/app.dart:190)
I/flutter : #3      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1281)
```

**Comment by Hixie** [comment]
Wow, this is all kinds of broken. The routes argument is entirely ignored, for example.

**Comment by Hixie** [comment]
Ok well for now I'm making WidgetsApp require onGenerateRoute and dropping routes.
