### ISSUE TITLE
Why flutter_localization can not supported for Chinese?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#27134]
> I'm writing something about the flutter l10n, ,when I change to Chinese language, the app crashed and throw some erroes,just like this:

```
I/flutter ( 4851): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞═══
I/flutter ( 4851): The following assertion was thrown building AppBar(dirty, state: _AppBarState#68fd2):
I/flutter ( 4851): No MaterialLocalizations found.
I/flutter ( 4851): AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter ( 4851): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter ( 4851): by the material library.
I/flutter ( 4851): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
I/flutter ( 4851): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter ( 4851): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter ( 4851):   AppBar
I/flutter ( 4851): The ancestors of this widget were:
I/flutter ( 4851):   FlexibleSpaceBarSettings
I/flutter ( 4851):   ConstrainedBox(BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=80.0))
I/flutter ( 4851):   MediaQuery(MediaQueryData(size: Size(360.0, 592.0), devicePixelRatio: 2.0, textScaleFactor:
1.0,
I/flutter ( 4851):   padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
I/flutter ( 4851):   false, accessibleNavigation: falsedisableAnimations: falseinvertColors: falseboldText: false))
I/flutter ( 4851):   LayoutId-[<_ScaffoldSlot.appBar>](id: _ScaffoldSlot.appBar)
I/flutter ( 4851):   CustomMultiChildLayout
I/flutter ( 4851):   AnimatedBuilder(animation: AnimationController#04932(⏭ 1.000; paused))
I/flutter ( 4851):   DefaultTextStyle(debugLabel: (tall body1 2014).merge(blackMountainView body1), inherit: false,
I/flutter ( 4851):   color: Color(0xdd000000), family: Roboto, size: 15.0, weight: 400, baseline: alphabetic,
I/flutter ( 4851):   decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
I/flutter ( 4851):   AnimatedDefaultTextStyle(duration: 200ms, debugLabel: (englishLike body1
I/flutter ( 4851):   2014).merge(blackMountainView body1), inherit: false, color: Color(0xdd000000), family: Roboto,
I/flutter ( 4851):   size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping
I/flutter ( 4851):   at box width, overflow: clip)
I/flutter ( 4851):   _InkFeatures-[GlobalKey#fe4d2 ink renderer]
I/flutter ( 4851):   NotificationListener<LayoutChangedNotification>
I/flutter ( 4851):   PhysicalModel(shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color:
I/flutter ( 4851):   Color(0xfffafafa), shadowColor: Color(0xff000000))
I/flutter ( 4851):   AnimatedPhysicalModel(duration: 200ms, shape: rectangle, borderRadius: BorderRadius.zero,
I/flutter ( 4851):   elevation: 0.0, color: Color(0xfffafafa), animateColor: false, shadowColor: Color(0xff000000),
I/flutter ( 4851):   animateShadowColor: true)
I/flutter ( 4851):   Material(type: canvas, color: Color(0xfffafafa))
I/flutter ( 4851):   PrimaryScrollController(ScrollController#a08fc(no clients))
I/flutter ( 4851):   _ScaffoldScope
I/flutter ( 4851):   Scaffold
I/flutter ( 4851):   MyHomePage
I/flutter ( 4851):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter ( 4851):   hintOverrides: null)
I/flutter ( 4851):   Builder
I/flutter ( 4851):   RepaintBoundary-[GlobalKey#fd956]
I/flutter ( 4851):   IgnorePointer(ignoring: false)
I/flutter ( 4851):   FadeTransition(opacity: AnimationController#47820(⏭ 1.000; paused; for
I/flutter ( 4851):   MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩CurveTween(curve: Cubic(0.42, 0.00, 1.00,
I/flutter ( 4851):   1.00))➩1.0)
I/flutter ( 4851):   FractionalTranslation
I/flutter ( 4851):   SlideTransition(animation: AnimationController#47820(⏭ 1.000; paused; for
I/flutter ( 4851):   MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩CurveTween(curve: Cubic(0.40, 0.00, 0.20,
I/flutter ( 4851):   1.00))➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0))
I/flutter ( 4851):   _FadeUpwardsPageTransition
I/flutter ( 4851):   AnimatedBuilder(animation: Listenable.merge([AnimationController#47820(⏭ 1.000; paused; for
I/flutter ( 4851):   MaterialPageRoute<dynamic>(/))➩ProxyAnimation,
I/flutter ( 4851):   kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation]))
I/flutter ( 4851):   RepaintBoundary
I/flutter ( 4851):   _FocusScopeMarker
I/flutter ( 4851):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter ( 4851):   hintOverrides: null)
I/flutter ( 4851):   FocusScope
I/flutter ( 4851):   PageStorage
I/flutter ( 4851):   Offstage(offstage: false)
I/flutter ( 4851):   _ModalScopeStatus(active)
I/flutter ( 4851):   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#8d831]
I/flutter ( 4851):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#0c804]
I/flutter ( 4851):   Stack(alignment: AlignmentDirectional.topStart, fit: expand, overflow: clip)
I/flutter ( 4851):   _Theatre
I/flutter ( 4851):   Overlay-[LabeledGlobalKey<OverlayState>#20179]
I/flutter ( 4851):   _FocusScopeMarker
I/flutter ( 4851):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter ( 4851):   hintOverrides: null)
I/flutter ( 4851):   FocusScope
I/flutter ( 4851):   AbsorbPointer(absorbing: false)
I/flutter ( 4851):   Listener(listeners: [down, up, cancel], behavior: deferToChild)
I/flutter ( 4851):   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#bd7fc]
I/flutter ( 4851):   DefaultTextStyle(debugLabel: fallback style; consider putting your text in a Material, inherit:
I/flutter ( 4851):   true, color: Color(0xd0ff0000), family: monospace, size: 48.0, weight: 900, decoration: double
I/flutter ( 4851):   Color(0xffffff00) TextDecoration.underline, softWrap: wrapping at box width, overflow: clip)
I/flutter ( 4851):   CustomPaint
I/flutter ( 4851):   Banner("DEBUG", textDirection: ltr, location: topEnd, Color(0xa0b71c1c), text inherit: true, text
I/flutter ( 4851):   color: Color(0xffffffff), text size: 10.2, text weight: 900, text height: 1.0x)
I/flutter ( 4851):   CheckedModeBanner("DEBUG")
I/flutter ( 4851):   Title(title: "Flutter Demo", color: MaterialColor(primary value: Color(0xff2196f3)))
I/flutter ( 4851):   Directionality(textDirection: ltr)
I/flutter ( 4851):   _LocalizationsScope-[GlobalKey#d138e]
I/flutter ( 4851):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter ( 4851):   textDirection: ltr, hintOverrides: null)
I/flutter ( 4851):   Localizations(locale: cn, delegates: [GlobalMaterialLocalizations.delegate(49 locales),
I/flutter ( 4851):   GlobalWidgetsLocalizations.delegate(all locales), SpecificLocalizationsDelegate[AppLocalizations],
I/flutter ( 4851):   DefaultMaterialLocalizations.delegate(en_US), DefaultCupertinoLocalizations.delegate(en_US),
I/flutter ( 4851):   DefaultWidgetsLocalizations.delegate(en_US)])
I/flutter ( 4851):   MediaQuery(MediaQueryData(size: Size(360.0, 592.0), devicePixelRatio: 2.0, textScaleFactor:
1.0,
I/flutter ( 4851):   padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
I/flutter ( 4851):   false, accessibleNavigation: falsedisableAnimations: falseinvertColors: falseboldText: false))
I/flutter ( 4851):   WidgetsApp-[GlobalObjectKey _MaterialAppState#52a02]
I/flutter ( 4851):   IconTheme(IconThemeData#2abdc(color: Color(0xdd000000)))
I/flutter ( 4851):   _InheritedTheme
I/flutter ( 4851):   Theme(ThemeData#654c3(buttonTheme: ButtonThemeData#e6439(buttonColor: Color(0xffe0e0e0),
I/flutter ( 4851):   colorScheme: ColorScheme#6a3d4(primary: MaterialColor(primary value: Color(0xff2196f3)),
I/flutter ( 4851):   primaryVariant: Color(0xff1976d2), secondary: Color(0xff2196f3), secondaryVariant:
I/flutter ( 4851):   Color(0xff1976d2), background: Color(0xff90caf9), error: Color(0xffd32f2f), onSecondary:
I/flutter ( 4851):   Color(0xffffffff), onBackground: Color(0xffffffff)), materialTapTargetSize:
I/flutter ( 4851):   MaterialTapTargetSize.padded), textTheme: TextTheme#204ed, primaryTextTheme:
I/flutter ( 4851):   TextTheme#ef275(display4: TextStyle(debugLabel: whiteMountainView display4, inherit: true, color:
I/flutter ( 4851):   Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), display3:
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView display3, inherit: true, color: Color(0xb3ffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), display2: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   display2, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), display1: TextStyle(debugLabel: whiteMountainView display1, inherit: true,
I/flutter ( 4851):   color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), headline:
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView headline, inherit: true, color: Color(0xffffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), title: TextStyle(debugLabel: whiteMountainView title,
I/flutter ( 4851):   inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter ( 4851):   subhead: TextStyle(debugLabel: whiteMountainView subhead, inherit: true, color: Color(0xffffffff),
I/flutter ( 4851):   family: Roboto, decoration: TextDecoration.none), body2: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   body2, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none),
I/flutter ( 4851):   body1: TextStyle(debugLabel: whiteMountainView body1, inherit: true, color: Color(0xffffffff),
I/flutter ( 4851):   family: Roboto, decoration: TextDecoration.none), caption: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   caption, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), button: TextStyle(debugLabel: whiteMountainView button, inherit: true,
I/flutter ( 4851):   color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none), subtitle):
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView subtitle, inherit: true, color: Color(0xffffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), overline: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   overline, inherit: true, color: Color(0xffffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none)), accentTextTheme: TextTheme#ef275(display4: TextStyle(debugLabel:
I/flutter ( 4851):   whiteMountainView display4, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), display3: TextStyle(debugLabel: whiteMountainView display3, inherit: true,
I/flutter ( 4851):   color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), display2:
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView display2, inherit: true, color: Color(0xb3ffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), display1: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   display1, inherit: true, color: Color(0xb3ffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), headline: TextStyle(debugLabel: whiteMountainView headline, inherit: true,
I/flutter ( 4851):   color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none), title:
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView title, inherit: true, color: Color(0xffffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), subhead: TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   subhead, inherit: true, color: Color(0xffffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), body2: TextStyle(debugLabel: whiteMountainView body2, inherit: true, color:
I/flutter ( 4851):   Color(0xffffffff), family: Roboto, decoration: TextDecoration.none), body1: TextStyle(debugLabel:
I/flutter ( 4851):   whiteMountainView body1, inherit: true, color: Color(0xffffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), caption: TextStyle(debugLabel: whiteMountainView caption, inherit: true,
I/flutter ( 4851):   color: Color(0xb3ffffff), family: Roboto, decoration: TextDecoration.none), button:
I/flutter ( 4851):   TextStyle(debugLabel: whiteMountainView button, inherit: true, color: Color(0xffffffff), family:
I/flutter ( 4851):   Roboto, decoration: TextDecoration.none), subtitle): TextStyle(debugLabel: whiteMountainView
I/flutter ( 4851):   subtitle, inherit: true, color: Color(0xffffffff), family: Roboto, decoration:
I/flutter ( 4851):   TextDecoration.none), overline: TextStyle(debugLabel: whiteMountainView overline, inherit: true,
I/flutter ( 4851):   color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none)), inputDecorationTheme:
I/flutter ( 4851):   InputDecorationTheme#862db, iconTheme: IconThemeData#2abdc(color: Color(0xdd000000)),
I/flutter ( 4851):   primaryIconTheme: IconThemeData#15fa8(color: Color(0xffffffff)), accentIconTheme:
I/flutter ( 4851):   IconThemeData#15fa8(color: Color(0xffffffff)), sliderTheme: SliderThemeData#a2f8b, tabBarTheme:
I/flutter ( 4851):   TabBarTheme#12410, chipTheme: ChipThemeData#7f6dd, materialTapTargetSize:
I/flutter ( 4851):   MaterialTapTargetSize.padded, pageTransitionsTheme: PageTransitionsTheme#cbbda))
I/flutter ( 4851):   AnimatedTheme(duration: 200ms)
I/flutter ( 4851):   ScrollConfiguration(behavior: _MaterialScrollBehavior)
I/flutter ( 4851):   MaterialApp
I/flutter ( 4851):   MyApp
I/flutter ( 4851):   [root]
I/flutter ( 4851):
I/flutter ( 4851): When the exception was thrown, this was the stack:
I/flutter ( 4851): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
I/flutter ( 4851): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
I/flutter ( 4851): #2      _AppBarState.build (package:flutter/src/material/app_bar.dart:371:12)
I/flutter ( 4851): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 4851): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 4851): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 4851): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter ( 4851): #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 4851): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 4851): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 4851): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 4851): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 4851): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 4851): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 4851): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4851): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4851): #67     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 4851): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 4851): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 4851): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4851): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4851): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 4851): #73     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 4851): #74     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 4851): ════════════════════════════════════════════════════════════════
```
----

> THe shapshot like this:

![cn](https://user-images.githubusercontent.com/27602662/51791520-648e9400-21df-11e9-8e49-f2ab623e7080.PNG)

----

and the code like this:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'localizations.dart';


void main() => runApp(MyApp());



typedef void LocaleChangeCallback(Locale locale);


class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  SpecificLocalizationsDelegate _specificLocalizationsDelegate;


  @override
  void initState() {
      super.initState();
      _specificLocalizationsDelegate = SpecificLocalizationsDelegate(new Locale('en'));
  }

  onLocaleChange(Locale locale){
    setState(() {
       _specificLocalizationsDelegate = SpecificLocalizationsDelegate(locale);
    });
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        _specificLocalizationsDelegate
      ],
      supportedLocales: [
        Locale('en'),
        Locale('ar'),
        Locale('cn')
      ],
      locale: _specificLocalizationsDelegate.overriddenLocale,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // home: MyHomePage(title: 'Flutter Demo Home Page'),
      home: MyHomePage(onLocaleChange, title: '国际化测试'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage(this.callback,{Key key, this.title}) : super(key: key);

  final String title;

  LocaleChangeCallback callback;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          new FlatButton(
            child:new Text('EngLish'),
            onPressed:(){
              this.setState((){
                widget.callback(new Locale('en'));
              });
            },
            color:AppLocalizations.of(context).locale == 'en' ? Colors.grey : Colors.blueAccent,
          ),
          new FlatButton(
            child:new Text('عربي '),
            onPressed:(){
              this.setState((){
                widget.callback(new Locale('ar'));
              });
            },
            color:AppLocalizations.of(context).locale == 'ar' ? Colors.grey : Colors.blueAccent,
          ),
          new FlatButton(
            child:new Text('中文'),
            onPressed:(){
              this.setState((){
                widget.callback(new Locale('cn'));
              });
            },
            color:AppLocalizations.of(context).locale == 'cn' ? Colors.grey : Colors.blueAccent,
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            // Text('You have pushed the button this many times:'),
             Text(AppLocalizations.of(context).lblname),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by zoechi** [comment]
Is this iOS or Android?

Please add the output of `flutter doctor -v`.

**Comment by AweiLoveAndroid** [comment]
android @zoechi

**Comment by HansMuller** [comment]
The supported Chinese locale is Locale('zh') - see https://docs.flutter.io/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html.
