### ISSUE TITLE
ArCore Plugin permission issues 

### ISSUE THREAD

**Issue by khalithartmann** [flutter/flutter#27131]
Hey guys, so i have successfully written a ARCore plugin that for Flutter and it seemed to be working fine for a about 2 months. Well ... not anymore. Somehow my application is not able to access my flutter camera anymore. Need help ... 

This is the output i get: 
```
E/libc    (25739): Access denied finding property "camera.aux.packagelist"
W/Binder:25739_4(25739): type=1400 audit(0.0:447942): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=21329 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (25739): Access denied finding property "camera.aux.packagelist"
W/Binder:25739_5(25739): type=1400 audit(0.0:447943): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=21329 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/third_party/arcore/ar/core/android/sdk/session_create.cc(25739): Entering ArSession_create
I/third_party/arcore/ar/core/android/sdk/session_create.cc(25739): ARCore Version: APK version code: 181112096
I/native  (25739): version_check.cc:23 ARCore Version: APK version:1.6.181112096
I/native  (25739): version_check.cc:24 ARCore Version: emulated SDK version:1.5.180815000
I/third_party/arcore/ar/core/android/sdk/session_create.cc(25739): ARCore Version: SDK build name: 1.5
I/third_party/arcore/ar/core/android/sdk/session_create.cc(25739): Dynamite load ok.
I/native  (25739): session_create_implementation.cc:49 Entering ArSession_createWithSettingsImplementation_private. ARCore SDK version: [1.5.180815000].
V/third_party/redwood/base/jni_common/jni_helper.cc(25739): JniHelper: attached thread. (Called from line 189.)
I/native  (25739): session_create_implementation_shared.cc:784 Persistent online recalibration is enabled by Phenotype.
E/native  (25739): online_calibration_manager.cc:47 OnlineCalibrationManager: Could not open /data/user/0/com.peqas.peqas/cache/arcore-online-recalibration for reading.
I/native  (25739): cpu_feature_extractor.cc:56 Doing adaptive frequency feature extraction using KLT.
I/native  (25739): device_profile_conversions.cc:143 used_active_calibration: 2
I/native  (25739): device_profile_conversions.cc:143 used_active_calibration: 2
I/native  (25739): android_sensors.cc:80 Using uncalibrated accelerometer.
I/native  (25739): android_sensors.cc:110 Using uncalibrated magnetometer.
I/native  (25739): config_helpers.cc:207 Does not find IMU intrinsic covariance matrix in profile for id: 100
I/native  (25739): calibration_provider.cc:1000 Using default initial IMU intrinsic covariance matrix.
I/native  (25739): config_helpers.cc:60 Does not find camera intrinsic covariance matrix in profile for id 0
I/native  (25739): calibration_provider.cc:874 Using default initial camera intrinsic covariance matrix.
I/native  (25739): config_helpers.cc:133 Does not find extrinsic covariance matrix in profile for IMU id 100
I/native  (25739): calibration_provider.cc:936 Using default initial extrinsic covariance matrix.
I/native  (25739): vio_helper.cc:32 Use calibrated IMU scale factors.
I/native  (25739): vio_helper.cc:44 Use calibrated IMU misalignment factors.
I/native  (25739): device_profile_conversions.cc:143 used_active_calibration: 2
W/ARCore-AnchorServiceClientFactory(25739): The API key for use with the Google AR service could not be obtained!
I/native  (25739): android_camera.cc:1188 Initializing camera manager.
E/libc    (25739): Access denied finding property "camera.nolimit.clientname"
E/ACameraManager(25739): [Eeee] 374@getCameraIdList available number of camera is 2. 
W/com.peqas.peqas(25739): type=1400 audit(0.0:447944): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=21329 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/native  (25739): android_camera.cc:1212 Camera manager initialized successfully with 2 cameras.
W/native  (25739): motion_analysis_calculator.cc:361 No input video header found. Downstream calculators expecting video headers are likely to fail.
I/native  (25739): session_create_implementation.cc:183 ArSession_createWithSettingsImplementation_private returning OK.
I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc(25739): Loading AImage symbols
I/third_party/arcore/ar/core/android/sdk/image_metadata_jni.cc(25739): Loading ACameraMetadata symbols
I/FlutterArcoreView(25739): Session created man
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_DATA_INVALID_FORMAT: Failed to parse bytes containing image database.
I/flutter (25739): Scanner.ArCore
D/libEGL  (25739): eglInitialize: enter
D/libEGL  (25739): eglInitialize: exit(res=1)
D/libEGL  (25739): eglInitialize: enter
D/libEGL  (25739): eglInitialize: exit(res=1)
I/System.out(25739): android: image recognition resumed 
W/com.peqas.peqas(25739): type=1400 audit(0.0:447945): avc: denied { search } for comm=474C5468726561642033363638 name="ctx" dev="debugfs" ino=14805 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
E/FlutterArcoreView(25739): com.google.ar.core.exceptions.SessionPausedException
E/FlutterArcoreView(25739): 	at com.google.ar.core.V.b(Unknown Source:2)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:14)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.nativeUpdate(Native Method)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.update(Unknown Source:12)
E/FlutterArcoreView(25739): 	at com.peqas.arcoreplugin.FlutterArcoreView.onDrawFrame(FlutterArcoreView.java:302)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
E/FlutterArcoreView(25739): com.google.ar.core.exceptions.SessionPausedException
E/FlutterArcoreView(25739): 	at com.google.ar.core.V.b(Unknown Source:2)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:14)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.nativeUpdate(Native Method)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.update(Unknown Source:12)
E/FlutterArcoreView(25739): 	at com.peqas.arcoreplugin.FlutterArcoreView.onDrawFrame(FlutterArcoreView.java:302)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
E/FlutterArcoreView(25739): com.google.ar.core.exceptions.SessionPausedException
E/FlutterArcoreView(25739): 	at com.google.ar.core.V.b(Unknown Source:2)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:14)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.nativeUpdate(Native Method)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.update(Unknown Source:12)
E/FlutterArcoreView(25739): 	at com.peqas.arcoreplugin.FlutterArcoreView.onDrawFrame(FlutterArcoreView.java:302)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
D/libEGL  (25739): eglInitialize: enter
D/libEGL  (25739): eglInitialize: exit(res=1)
D/libEGL  (25739): eglInitialize: enter
D/libEGL  (25739): eglInitialize: exit(res=1)
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
E/FlutterArcoreView(25739): com.google.ar.core.exceptions.SessionPausedException
E/FlutterArcoreView(25739): 	at com.google.ar.core.V.b(Unknown Source:2)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:14)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.nativeUpdate(Native Method)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.update(Unknown Source:12)
E/FlutterArcoreView(25739): 	at com.peqas.arcoreplugin.FlutterArcoreView.onDrawFrame(FlutterArcoreView.java:302)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
E/FlutterArcoreView(25739): com.google.ar.core.exceptions.SessionPausedException
E/FlutterArcoreView(25739): 	at com.google.ar.core.V.b(Unknown Source:2)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:14)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.nativeUpdate(Native Method)
E/FlutterArcoreView(25739): 	at com.google.ar.core.Session.update(Unknown Source:12)
E/FlutterArcoreView(25739): 	at com.peqas.arcoreplugin.FlutterArcoreView.onDrawFrame(FlutterArcoreView.java:302)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
E/FlutterArcoreView(25739): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
E/native  (25739): status.cc:156 ArStatusErrorSpace::AR_ERROR_SESSION_PAUSED: Could not update frame, session is paused.
E/FlutterArcoreView(25739): Exception on the OpenGL thread
```

Flutter doctor: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[!] VS Code (version 1.30.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

my Plugin  AndoidManifest: 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.peqas.arcoreplugin">
    <!-- "AR Required" apps must declare minSdkVersion ≥ 24 -->

    <uses-permission android:name="android.permission.CAMERA" />

    <!-- Indicates that app requires ARCore ("AR Required"). Ensures app is only
         visible in the Google Play Store on devices that support ARCore.
    -->
    <uses-feature android:name="android.hardware.camera.ar" />

    <application>
        <!-- Indicates that app requires ARCore ("AR Required"). Causes Google
             Play Store to download and install ARCore when the app is installed.
        -->
        <meta-data android:name="com.google.ar.core" android:value="required" />
    </application>
</manifest>
```
App Android Manifest:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.peqas.peqas">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="peqas"
        android:icon="@mipmap/ic_launcher"
        tools:ignore="GoogleAppIndexingWarning">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```
Pleaseee  help .... 

Thank you in advance 👍

**Comment by zoechi** [comment]
Similar error in https://github.com/rmtmckenzie/flutter_qr_mobile_vision/issues/49

https://stackoverflow.com/questions/50035729/camera-app-on-android/50036728#50036728 might help

**Comment by zoechi** [comment]
Can you try with a different device?

**Comment by zoechi** [comment]
Please provide more details about the device that causes this error.

**Comment by khalithartmann** [comment]
Thank you for the fast reply. I managed to fix the error. Turned out not to be related to the plugin at all. 
Kind Regards 👍

**Comment by ashik5119** [comment]
> Thank you for the fast reply. I managed to fix the error. Turned out not to be related to the plugin at all.
> Kind Regards
@khalithartmann how did you solve the issue?

**Comment by nar3n12** [comment]
> Thank you for the fast reply. I managed to fix the error. Turned out not to be related to the plugin at all.
> Kind Regards 👍

how did you solve?
