### ISSUE TITLE
designated cpu to "armeabi-v7a",simulator with arm cpu type crashed

### ISSUE THREAD

**Issue by czronaldo11** [flutter/flutter#27145]
## Steps to Reproduce
1.use simplest demo,set ndk in build.gradle,designated cpu to `armeabi-v7a`
```
        ndk {
            abiFilters "armeabi-v7a"
        }
```
2. run the app on  yeshen simulator(夜神模拟器),which one is arm cpu type
3. the app is crash

## Logs

```
01-27 10:57:03.817 4018-4035/com.tencent.lgs A/libc: Fatal signal 4 (SIGILL) at 0x00000fb2 (code=0), thread 4035 (1.ui)
01-27 10:57:03.917 157-157/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-27 10:57:03.917 157-157/? I/DEBUG: Build fingerprint: 'samsung/SM-G955F/SM-G955F:4.4.2/JLS36C/381190110:user/release-keys'
01-27 10:57:03.917 157-157/? I/DEBUG: Revision: '0'
01-27 10:57:03.917 157-157/? I/DEBUG: pid: 4018, tid: 4035, name: 1.ui  >>> com.tencent.lgs <<<
01-27 10:57:03.917 157-157/? I/DEBUG: signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
01-27 10:57:03.947 157-157/? I/DEBUG:     eax 00000000  ebx 00000fc3  ecx 00000006  edx 00000000
01-27 10:57:03.947 157-157/? I/DEBUG:     esi 00000008  edi 1a215030
01-27 10:57:03.947 157-157/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000043  xss 0000007b
01-27 10:57:03.947 157-157/? I/DEBUG:     eip 7ebd1700  ebp 7e53b6ac  esp 7e53b694  flags 00200246
01-27 10:57:03.947 157-157/? I/DEBUG: backtrace:
01-27 10:57:03.947 157-157/? I/DEBUG:     #00  pc 00194700  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG: stack:
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b654  7ed20de4  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b658  7ed20de4  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b65c  7e53b6ec  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b660  7eb01dd7  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b664  00000002  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b668  00000000  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b66c  7ec8db30  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b670  0000036c  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b674  7e53b724  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b678  00000001  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b67c  00000000  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b680  7e63aba0  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b684  7ec8bf4c  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b688  00000000  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b68c  7e53b6ac  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b690  7ebd1682  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:     #00  7e53b694  7e53b6a4  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b698  00000006  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b69c  0000029c  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6a0  00000001  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6a4  00000028  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6a8  00000000  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6ac  7e53b6cc  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6b0  7ebcb351  /system/lib/libhoudini.so
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6b4  1a215030  [stack:4034]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6b8  00000b01  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6bc  000002f5  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6c0  1a215030  [stack:4034]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6c4  00000000  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6c8  00000001  
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6cc  7e53b6ec  [stack:4035]
01-27 10:57:03.947 157-157/? I/DEBUG:          7e53b6d0  7eb01848  /system/lib/libhoudini.so
01-27 10:57:03.967 308-4044/? W/ActivityManager:   Force finishing activity com.tencent.lgs/shequ.qqx5.tencent.com.x5shequmain.MainActivity
01-27 10:57:03.967 308-331/? I/BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
01-27 10:57:03.977 161-161/? D/Zygote: Process 4018 exited cleanly (255)
01-27 10:57:04.267 308-4044/? I/WindowManager: Screenshot max retries 4 of Token{4a972288 ActivityRecord{4a9acd9c u0 com.tencent.lgs/shequ.qqx5.tencent.com.x5shequmain.MainActivity t22 f}} appWin=Window{4a80b7a0 u0 Starting com.tencent.lgs} drawState=4
01-27 10:57:04.267 308-4044/? W/WindowManager: Screenshot failure taking screenshot for (1280x720) to layer 21015
01-27 10:57:04.267 308-4044/? W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException
        at android.os.BinderProxy.transact(Native Method)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2456)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2330)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2035)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9573)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9466)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10119)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9662)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

```
D:\Program Files\Nox\bin>flutter doctor -v
[âˆš] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    â€¢ Flutter version 1.0.0 at D:\flutter
    â€¢ Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    â€¢ Engine revision 7375a0f414
    â€¢ Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    â€¢ Android SDK at E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Android NDK location not configured (optional; useful for native profiling support)
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ ANDROID_HOME = E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[âˆš] Android Studio (version 3.2)
    â€¢ Android Studio at E:\Program Files\Android\Android Studio
    â€¢ Flutter plugin version 29.1.1
    â€¢ Dart plugin version 181.5656
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment]
@mraleph ?

**Comment by kangwang1988** [comment]
@czronaldo11 
Consider to run flutter using a unoptimized engine build and run it on the emulator.
Then symbolicate the crash.
We can't move further before more detailed information.
https://github.com/flutter/flutter/wiki/Crashes
https://github.com/flutter/flutter/wiki/Compiling-the-engine
https://github.com/flutter/flutter/wiki/Debugging-the-engine

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
