### ISSUE TITLE
TabbedView not rendering anything at all

### ISSUE THREAD

**Issue by jordyvandomselaar** [flutter/flutter#27159]
When using the following minimal code:

`main.dart` renders `Editor`

```dart
import 'package:flutter/material.dart';
import 'package:markdown/Editor.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget{
  build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Markdown App")),
      body: ListView(
        children: <Widget>[
          Editor()
        ],
      ),
    );
  }
}
```

`Editor`:

```dart
import 'package:flutter/material.dart';

class Editor extends StatefulWidget {
  @override
  State createState() {
    return EditorState();
  }
}

class EditorState extends State<Editor> with SingleTickerProviderStateMixin {
  TabController _tabController;

  @override
  void initState() {
    super.initState();

    _tabController = TabController(length: 2, vsync: this);
  }

  build(BuildContext context) {
    return Column(
      children: <Widget>[
        Text("foo"),
        TabBarView(
          controller: _tabController,
          children: <Widget>[
            Text("Markdown"),
            Text("rendered"),
          ],
        )
      ],
    );
  }
}
```

I get a white screen; it doesn't render anything at all:

![image](https://user-images.githubusercontent.com/12712484/51807790-e805bf00-228b-11e9-9f44-d3b96d154365.png)

Weird enough the `TabbedView` renders my items when not contained in a `Column` or any other component.

**Flutter doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-NL)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

I did find the following error:

```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The getter 'visible' was called on null.
Receiver: null
Tried calling: visible
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:26)
#2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
#3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
#4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
#5      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2777:37)
#6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:113:19)
#7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
#8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderPro<…>
```

**Comment by OsaXma** [comment]
You need to constraint the TabBarView size. You can use a container with a box constraint or you can use Expanded.  Here's a working example of TabBar: 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(appBar: AppBar(), body: MyCustomTab()));
  }
}

class MyCustomTab extends StatefulWidget {
  @override
  MyCustomTabState createState() => MyCustomTabState();

}

class MyCustomTabState extends State<MyCustomTab> {
  final _formKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      initialIndex: 0,
      child: Form(
        key: _formKey,
        child: Column(
          children: <Widget>[
            Container(
                constraints: BoxConstraints.expand(height: 40),
                child: TabBar(
                  tabs: <Widget>[
                    Text("Tab 1",
                        style: TextStyle(
                            fontWeight: FontWeight.bold, color: Colors.black)),
                    Text("Tab 2",
                        style: TextStyle(
                            fontWeight: FontWeight.bold, color: Colors.black))
                  ],
                )),
            Expanded(
                child: TabBarView(
              children: <Widget>[
                Center(child: Text("Tab 1 View")),
                Center(child: Text("Tab 2 View"))
              ],
            )),
          ],
        ),
      ),
    );
  }
}

```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
