### ISSUE TITLE
Google Maps returns java.lang.NullPointerException only on Samsung Galaxy S9+

### ISSUE THREAD

**Issue by JTorrus** [flutter/flutter#27177]
## Steps to Reproduce

1. Implement [Google Maps for Flutter](https://pub.dartlang.org/packages/google_maps_flutter) `0.2.0` in my project.

2. Run app in a Samsung Galaxy S9+ with Android 9.

3. Try to navigate to another route or refresh from the Google Maps screen, .

## Logs

Running `flutter run` and following the steps previously explained.

```
D/AndroidRuntime( 3085): Shutting down VM
E/AndroidRuntime( 3085): FATAL EXCEPTION: main
E/AndroidRuntime( 3085): Process: com.squat.app, PID: 3085
E/AndroidRuntime( 3085): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.wm.DisplayContent.getOrientation()' on a null object reference
E/AndroidRuntime( 3085): 	at android.os.Parcel.createException(Parcel.java:1972)
E/AndroidRuntime( 3085): 	at android.os.Parcel.readException(Parcel.java:1934)
E/AndroidRuntime( 3085): 	at android.os.Parcel.readException(Parcel.java:1884)
E/AndroidRuntime( 3085): 	at android.view.IWindowSession$Stub$Proxy.remove(IWindowSession.java:1106)
E/AndroidRuntime( 3085): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4499)
E/AndroidRuntime( 3085): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:7902)
E/AndroidRuntime( 3085): 	at android.view.ViewRootImpl.die(ViewRootImpl.java:7870)
E/AndroidRuntime( 3085): 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:497)
E/AndroidRuntime( 3085): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:435)
E/AndroidRuntime( 3085): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
E/AndroidRuntime( 3085): 	at android.app.Dialog.dismissDialog(Dialog.java:517)
E/AndroidRuntime( 3085): 	at android.app.Dialog.dismiss(Dialog.java:500)
E/AndroidRuntime( 3085): 	at android.app.Dialog.cancel(Dialog.java:1461)
E/AndroidRuntime( 3085): 	at android.app.Presentation.handleDisplayRemoved(Presentation.java:297)
E/AndroidRuntime( 3085): 	at android.app.Presentation.access$100(Presentation.java:151)
E/AndroidRuntime( 3085): 	at android.app.Presentation$2.onDisplayRemoved(Presentation.java:365)
E/AndroidRuntime( 3085): 	at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:1191)
E/AndroidRuntime( 3085): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3085): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime( 3085): 	at android.app.ActivityThread.main(ActivityThread.java:6967)
E/AndroidRuntime( 3085): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3085): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 3085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/AndroidRuntime( 3085): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 3085): 	at com.android.server.wm.WindowManagerService.updateOrientationFromAppTokensLocked(WindowManagerService.java:2924)
E/AndroidRuntime( 3085): 	at com.android.server.wm.WindowManagerService.updateOrientationFromAppTokensLocked(WindowManagerService.java:2917)
E/AndroidRuntime( 3085): 	at com.android.server.wm.WindowState.removeIfPossible(WindowState.java:2685)
E/AndroidRuntime( 3085): 	at com.android.server.wm.WindowState.removeIfPossible(WindowState.java:2556)
E/AndroidRuntime( 3085): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:1898)
E/AndroidRuntime( 3085): 

```

Running `flutter analyze`

```
Analyzing squat_app...                                           
No issues found! (ran in 1.0s)
```

## Flutter Doctor

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-ES)
    • Flutter version 1.1.9 at /Users/javier/Documents/flutter
    • Framework revision 1407091bfb (3 weeks ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/javier/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • SM G965F • 223dcc0211037ece   • android-arm64 • Android 9 (API 28)
    • SM G935F • 9885b649415a574e33 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!


```
## Additional info
I tested with a variety of devices and Android versions: Xiaomi Mi A1 with Android 9, Samsung Galaxy S7 edge with Android 8.1, Samsung Galaxy A3 with Android 6.0.1 and Samsung Galaxy S9+ with Android 9. The app worked in all devices except in the S9+. 

I have `compileSdkVersion` and `targetSdkVersion` set to API 28 in my app's `build.gradle` and added this line in my Manifest 
```xml
<uses-library android:name="org.apache.http.legacy" android:required="false" />
```

I also updated my `gradle.properties` adding the following lines

```groovy
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by PingShen** [comment]
how to fix

**Comment by timsneath** [comment]
@PingShen are you experiencing the same error on the same phone? Have you updated to the latest version of the maps plug-in? If so, please share your `flutter doctor -v` output and ideally a small reproducible sample.

**Comment by darshankawar** [comment]
@JTorrus 
Is this still a valid issue using [latest](https://pub.dev/packages/google_maps_flutter/install) plugin version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
