### ISSUE TITLE
ListView '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.

### ISSUE THREAD

**Issue by Waged** [flutter/flutter#27174]
`ListView` is so laggy after adding container when data  fetching from network.
Although data and everything is working fine but the view is so laggy and produces to me:
```
The App: https://github.com/Waged/news
LOG :
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5781): The following assertion was thrown building FutureBuilder<ItemModel>(state:
I/flutter ( 5781): _FutureBuilderState<ItemModel>#01167):
I/flutter ( 5781): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1411 pos 14:
I/flutter ( 5781): '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
I/flutter ( 5781): 
I/flutter ( 5781): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5781): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5781): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5781):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5781): 
I/flutter ( 5781): When the exception was thrown, this was the stack:
I/flutter ( 5781): #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1411:14)
I/flutter ( 5781): #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:1842:11)
I/flutter ( 5781): #4      RenderObject.dropChild (package:flutter/src/rendering/object.dart:1160:5)
I/flutter ( 5781): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:2714:7)
I/flutter ( 5781): #6      SingleChildRenderObjectElement.removeChildRenderObject (package:flutter/src/widgets/framework.dart:4888:18)
I/flutter ( 5781): #7      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:4728:36)
I/flutter ( 5781): #8      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:2856:13)
I/flutter ( 5781): #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 5781): #10     Element.detachRenderObject (package:flutter/src/widgets/framework.dart:2855:5)
I/flutter ( 5781): #11     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2985:11)
I/flutter ( 5781): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2750:7)
I/flutter ( 5781): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5781): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5781): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 5781): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 5781): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 5781): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5781): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5781): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5781): #21     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 5781): #22     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 5781): (elided 2 frames from class _AssertionError)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
