### ISSUE TITLE
UIKitView in Column  Exception

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#27173]
Flutter code 
```dart
              child: Column(
                children: <Widget>[
                  UiKitView(
                    viewType: 'plugins.flutter.io/webview',
                  ),
                  Text('ffff'),
                  Text('ffff'),
            ],
```
iOS code:
```objective-c
- (instancetype)initWithFrame:(CGRect)frame
               viewIdentifier:(int64_t)viewId
                    arguments:(id _Nullable)args
              binaryMessenger:(NSObject<FlutterBinaryMessenger>*)messenger {
  if ([super init]) {
    _viewId = viewId;
      
      
      nativeView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 0,0)];
      nativeView.backgroundColor = [UIColor redColor];
      UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 100, 30)];
      label.text = @"native Text";
      [nativeView addSubview:label];

      
  }
  return self;
}

- (UIView*)view {
    return nativeView;
    //  return _webView;
}
```
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderConstrainedBox object was given an infinite size during layout.
flutter: This probably means that it is a render object that tries to be as big as possible, but it was put
flutter: inside another render object that allows its children to pick their own size.
flutter: The nearest ancestor providing an unbounded height constraint is:
flutter:   RenderIndexedSemantics#75989 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
flutter:   AutomaticKeepAlive ← SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
flutter:   IgnorePointer-[GlobalKey#92b4c] ← Semantics ← Listener ← ⋯
flutter:   parentData: index=0; layoutOffset=0.0 (can use size)
flutter:   constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
flutter:   semantic boundary
flutter:   size: MISSING
flutter:   index: 0
flutter: The constraints that applied to the RenderConstrainedBox were:
flutter:   BoxConstraints(w=414.0, 0.0<=h<=Infinity)
flutter: The exact size it was given was:
flutter:   Size(414.0, Infinity)
flutter: See https://flutter.io/layout/ for more information.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1749:9)
flutter: #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
flutter: #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
flutter: #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
flutter: #4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:261:7)
flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #10     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #12     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #14     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
flutter: #15     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
flutter: #16     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #30     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #32     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #34     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
flutter: #35     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
flutter: #36     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
flutter: #37     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #42     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1203:11)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #50     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #63     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2900:13)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #65     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #67     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
flutter: #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
flutter: #79     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
flutter: #80     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
flutter: #81     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:686:13)
flutter: #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #89     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #90     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #91     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderConstrainedBox#b3902 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: SizedBox.expand ← UiKitView ← RepaintBoundary-[<0>] ← IndexedSemantics ←
flutter:   NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← SliverList ←
flutter:   MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
flutter:   size: Size(414.0, Infinity)
flutter:   additionalConstraints: BoxConstraints(biggest)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderRepaintBoundary object was given an infinite size during layout.
flutter: Another exception was thrown: RenderIndexedSemantics object was given an infinite size during layout.
flutter: Another exception was thrown: RenderUiKitView object was given an infinite size during layout.
flutter: Another exception was thrown: RenderUiKitView object was given an infinite size during layout.
flutter: Another exception was thrown: RenderRepaintBoundary object was given an infinite size during layout.
flutter: Another exception was thrown: RenderIndexedSemantics object was given an infinite size during layout.
Lost connection to device.
```

Flutter doctor=============
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.1.9, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)
```

**Comment by lichentao** [comment]
![image](https://user-images.githubusercontent.com/5095376/51831816-09b78280-232e-11e9-9f65-5618f34805a1.png)

**Comment by zoechi** [comment]
You can't put a widget that expects a limited height directly into a `Column`.
Wrap it in an `Expanded`:
 
```dart
          child: Column(
                children: <Widget>[
                 Expanded(child:
                    UiKitView(
                      viewType: 'plugins.flutter.io/webview',
                    ),
                    Text('ffff'),
                    Text('ffff'),
                 ),
            ],
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ezamagni** [comment]
I had a very similar problem, which i resolved by placing my native widget inside a SizedBox.
However, it would be very nice if Flutter could infer the right dimension for an unbounded native widget when it provides an implementation of the [intrinsicContentSize property](https://developer.apple.com/documentation/uikit/uiview/1622600-intrinsiccontentsize).
