### ISSUE TITLE
When engine crashes, we output three separate stack traces

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2718]
...only one of which is really useful.

Example:

```
E/flutter : #00 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #01 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #02 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #03 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #04 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #05 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #06 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #07 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #08 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #09 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #10 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #11 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #12 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #13 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #14 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #15 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #16 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #17 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #18 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #19 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #20 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #21 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #22 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #23 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #24 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #25 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #26 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #27 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #28 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #29 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #30 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #31 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #32 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #33 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #34 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #35 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #36 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #37 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #38 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #39 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #40 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #41 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #42 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #43 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #44 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so+0x005dc083
E/flutter : #45 0xa0dc6083 /data/app/com.yourcompany.worldClock-1/lib/arm
--------- beginning of crash
F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfbadbeef in tid 23778 (ui_thread)
F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'google/shamu/shamu:6.0.1/MMB29W/2641372:user/release-keys'
F/DEBUG   : Revision: '0'
F/DEBUG   : ABI: 'arm'
F/DEBUG   : pid: 23752, tid: 23778, name: ui_thread  >>> com.yourcompany.worldClock <<<
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfbadbeef
F/DEBUG   :     r0 9a536f64  r1 9dff9a68  r2 00000014  r3 fbadbeef
F/DEBUG   :     r4 00000000  r5 472ed640  r6 00000001  r7 96c67200
F/DEBUG   :     r8 00000000  r9 9e1a1400  sl 9ff10ab8  fp 00000040
F/DEBUG   :     ip 9dff9318  sp 9a537068  lr a0b31ff1  pc a08c30f6  cpsr 80070030
F/DEBUG   :
F/DEBUG   : backtrace:
F/DEBUG   :     #00 pc 000d90f6  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #01 pc 0058c0b9  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #02 pc 005a2ff3  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #03 pc 005a3025  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #04 pc 00595d89  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #05 pc 005900f3  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #06 pc 0059011d  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #07 pc 0059a7ed  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #08 pc 005aa34d  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #09 pc 005aa35d  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #10 pc 005b7461  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #11 pc 005b74e1  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #12 pc 0039b099  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #13 pc 004987f9  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #14 pc 0054bcb3  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #15 pc 00470ca9  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #16 pc 00470e89  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #17 pc 00417b21  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #18 pc 0041837d  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #19 pc 00419095  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #20 pc 0056a29d  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #21 pc 0056a3bf  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #22 pc 004e60d3  /data/app/com.yourcompany.worldClock-1/lib/arm/libsky_shell.so
F/DEBUG   :     #23 pc 0003f45f  /system/lib/libc.so (__pthread_start(void*)+30)
F/DEBUG   :     #24 pc 00019b43  /system/lib/libc.so (__start_thread+6)
W/ActivityManager:   Force finishing activity com.yourcompany.worldClock/org.domokit.sky.shell.SkyActivity
F/DEBUG   :
F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_09
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager:      at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager:      at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager:      at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager:      at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager:      at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager:      at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager:      at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
W/ActivityManager:      at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
W/ActivityManager:      at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
W/ActivityManager:      at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
W/ActivityManager:      at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
W/ActivityManager:      at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by Hixie** [comment]
See also: https://github.com/flutter/flutter/issues/2221
