### ISSUE TITLE
Exception thrown by package modal_progress_hud - its simple impl only 

### ISSUE THREAD

**Issue by pavanjoshi** [flutter/flutter#27221]
## Steps to Reproduce

Basic Implementation of Flutter package : 
https://pub.dartlang.org/packages/modal_progress_hud

as shown in the example. 

## Logs

I/flutter (28537): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28537): The following assertion was thrown building LoginPage(dirty, state: _LoginPageState#f76d1):
I/flutter (28537): 'package:modal_progress_hud/modal_progress_hud.dart': Failed assertion: line 43 pos 16: 'child !=
I/flutter (28537): null': is not true.
I/flutter (28537): 
I/flutter (28537): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28537): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28537): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28537):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28537): 
I/flutter (28537): When the exception was thrown, this was the stack:
I/flutter (28537): #2      new ModalProgressHUD (package:modal_progress_hud/modal_progress_hud.dart:43:16)
I/flutter (28537): #3      _LoginPageState.build (package:flutter_app/page/login.dart:185:13)
I/flutter (28537): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (28537): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (28537): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (28537): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)

**Comment by pavanjoshi** [comment]
Sorry! solved
