### ISSUE TITLE
Admob Interstitial Ad not showing on emulator devices

### ISSUE THREAD

**Issue by haikalpe123** [flutter/flutter#27233]
## Steps to Reproduce

I'm using `firebase_admob` for my apps, yesterday it works perfectly...the ads were showing in the emulator devices. But today, it's suddenly throw an error. Can you guys help me?

## Logs

```
E/flutter ( 5531): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5531): PlatformException(load_failed_ad, cannot reload a failed ad, id=461653319, null)
E/flutter ( 5531): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 5531): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 5531): <asynchronous suspension>
E/flutter ( 5531): #2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:521:61)
E/flutter ( 5531): <asynchronous suspension>
E/flutter ( 5531): #3      InterstitialAd.load (package:firebase_admob/firebase_admob.dart:307:12)
E/flutter ( 5531): #4      _IntiyState.build.<anonymous closure> (package:subscribepewds/inti.dart:542:21)
E/flutter ( 5531): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 5531): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 5531): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 5531): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 5531): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 5531): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5531): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
E/flutter ( 5531): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 5531): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 5531): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 5531): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 5531): #16     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5531): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by zoechi** [comment]
You probably updated to newer package versions. See for example https://github.com/flutter/flutter/issues/27128#issuecomment-458274311

**Comment by mklim** [comment]
This looks like an error from the plugin itself to me, not obviously related to the AndroidX migration itself. It may be related to another change pulled in by upgrading? Nothing in the commit log looks like it's touched the platform code since last release, though.

> `PlatformException(load_failed_ad, cannot reload a failed ad, id=461653319, null)`

**Comment by haikalpe123** [comment]
**here is my depedencies**

   flutter_swiper:
   flare_flutter:
   material_design_icons_flutter: 3.0.3392
   url_launcher: ^4.0.3
   firebase_admob: ^0.7.0
   firebase_core: ^0.3.0

i've tried to downgrade the firebase_admob to 0.7.0 from 0.8.0 but it still not work..

**Comment by kroikie** [comment]
@haikalpe123

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/480. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
