### ISSUE TITLE
Loggin in with google bad utf-8 exception

### ISSUE THREAD

**Issue by thonwhal** [flutter/flutter#27245]
1. Firstly, Why every problem is about utf-8, i hate this thing.
2. My program was working after i tried to add google signin via firebase, its not working anymore.
3. Please help i really like flutter but everything is broke..

## command
```
flutter run
```
## exception
```
FormatException: FormatException: Bad UTF-8 encoding 0xfd (at offset 88)
```
```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:568:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale tr-TR)
    [32m•[39m Flutter version 1.0.0 at C:\src\flutter
    [32m•[39m Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    [32m•[39m Engine revision 7375a0f414
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at C:\Users\Thonwhal\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 32.0.1
    [32m•[39m Dart plugin version 182.5124
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.30.2)
    [32m•[39m VS Code at C:\Users\Thonwhal\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 2.22.2

[32m[✓][39m Connected device (1 available)
    [32m•[39m ASUS Z012S • **********• android-arm64 • Android 9 (API 28)

[32m•[39m No issues found!
```
```
Analyze
Analyzing help...
No issues found! (ran in 3.3s)
```

```
flutter doctor -v

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale tr-TR)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Thonwhal\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\Thonwhal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.2

[√] Connected device (1 available)
    • ASUS Z012S • ***********• android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by thonwhal** [comment]
@zoechi i tried these but nothing changed. Almost 8 hours i am trying to fix this..

**Comment by zoechi** [comment]
A wild guess is https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by thonwhal** [comment]
Worked because my additions on build.gradle deleted 
Doesn't work after i add these codes:
`classpath 'com.google.gms:google-services:4.0.1'`
`implementation 'com.google.firebase:firebase-core:16.0.1'`
`apply plugin: 'com.google.gms.google-services'`

**Comment by zoechi** [comment]
`flutter package pub cache repair` would be worth a try.

**Comment by zoechi** [comment]
Perhaps also https://github.com/flutter/flutter/issues/19074#issuecomment-402489964

**Comment by thonwhal** [comment]
> 
> 
> `flutter package pub cache repair` would be worth a try.

`Could not find a command named "package".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.`

**Comment by zoechi** [comment]
Sorry, forgot an `s` `flutter packages pub cache repair`

**Comment by thonwhal** [comment]
> 
> 
> Sorry, forgot an `s` `flutter packages pub cache repair`

`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
FAILURE: Build failed with an exception.
* What went wrong:
FormatException: Bad UTF-8 encoding 0xfd (at offset 33)`


i did it but again and again..

**Comment by zoechi** [comment]
Please also check https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by thonwhal** [comment]
> 
> 
> Please also check https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted
desperately tried but nothing changed

**Comment by thonwhal** [comment]
[https://github.com/flutter/plugins/tree/master/packages/firebase_auth/example](url)
btw i tried this but it didn't work. Could you try for me ?

**Comment by thonwhal** [comment]
Okay i am really happy now , i found the solution but its not a good solution because downgrading something is not good for me..
change /build.gradle dependicies
`classpath 'com.google.gms:google-services:4.0.1'` to `classpath 'com.google.gms:google-services:3.2.1'`
work like charm

**Comment by zoechi** [comment]
Are you sure `classpath 'com.google.gms:google-services:4.0.1'` worked already?

**Comment by thonwhal** [comment]
> 
> 
> Are you sure `classpath 'com.google.gms:google-services:4.0.1'` worked already?

yes pretty sure

**Comment by kroikie** [comment]
@thonwhal

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/479. Any further collaboration will be done there.
