### ISSUE TITLE
Observatory error on linux (flutter-desktop-embedding)

### ISSUE THREAD

**Issue by techpuls-damir** [flutter/flutter#27291]
When I compile and run flutter-desktop-embeding example on Ubuntu, and try to connect to observatory I get the following error:
```
Disconnected from VM: Connection saw corrupt JSON message: FormatException: SyntaxError: Unexpected number in JSON at position 305
```
Application seems to work fine.

I have tried doing the same under windows, and obsrvatory works fine.

```
[✓] Flutter (Channel master, v1.1.10-pre.206, on Linux, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] VS Code (version 1.30.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
[last-ws-frame.txt](https://github.com/flutter/flutter/files/2812738/last-ws-frame.txt)
```
Navigated to http://127.0.0.1:40173/
main.dart.js:8633 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
Ej @ main.dart.js:8633
Y @ main.dart.js:29394
(anonymous) @ main.dart.js:16506
(anonymous) @ main.dart.js:3149
$2 @ main.dart.js:3483
$0 @ main.dart.js:38139
m_ @ main.dart.js:38113
$2 @ main.dart.js:38137
D @ main.dart.js:3130
rJ @ main.dart.js:16611
(anonymous) @ main.dart.js:38317
(anonymous) @ main.dart.js:3149
$2 @ main.dart.js:3483
$0 @ main.dart.js:38139
m_ @ main.dart.js:38113
$2 @ main.dart.js:38137
D @ main.dart.js:3130
$0 @ main.dart.js:38325
$0 @ main.dart.js:37894
dart.ru @ main.dart.js:3306
h0 @ main.dart.js:4619
z3 @ main.dart.js:3417
a3Z @ main.dart.js:3389
tN @ main.dart.js:37882
(anonymous) @ main.dart.js:38305
(anonymous) @ main.dart.js:3149
$2 @ main.dart.js:3483
D @ main.dart.js:3130
oj @ main.dart.js:38307
(anonymous) @ main.dart.js:39761
(anonymous) @ main.dart.js:39756
(anonymous) @ main.dart.js:39759
(anonymous) @ main.dart.js:39761
DevTools failed to parse SourceMap: http://127.0.0.1:40173/main.dart.js.map
main.dart.js:2694 INFO: 2019-01-30 14:25:59.461: Starting Observatory
main.dart.js:2694 INFO: 2019-01-30 14:25:59.516: Setting initial target to ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.527: _switchVM from:null to:vm@ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.537: Installing page: Instance of 'minified:Yd'
main.dart.js:2694 INFO: 2019-01-30 14:25:59.582: Sending all delayed requests.
main.dart.js:2694 INFO: 2019-01-30 14:25:59.586: GET [0] streamListen({streamId: VM}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.588: WebSocketVM connection opened: ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.593: RESPONSE [0] streamListen
main.dart.js:2694 INFO: 2019-01-30 14:25:59.599: GET [1] streamListen({streamId: Isolate}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.605: RESPONSE [1] streamListen
main.dart.js:2694 INFO: 2019-01-30 14:25:59.609: GET [2] streamListen({streamId: Debug}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.613: RESPONSE [2] streamListen
main.dart.js:2694 INFO: 2019-01-30 14:25:59.618: GET [3] streamListen({streamId: _Graph}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.622: RESPONSE [3] streamListen
main.dart.js:2694 INFO: 2019-01-30 14:25:59.630: GET [4] streamListen({streamId: _Service}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.646: RESPONSE [4] streamListen
main.dart.js:2694 INFO: 2019-01-30 14:25:59.650: GET [5] getVM({}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.656: RESPONSE [5] getVM
main.dart.js:2694 INFO: 2019-01-30 14:25:59.661: GET [6] getIsolate({isolateId: isolates/986583284}) from ws://127.0.0.1:40173/ws
main.dart.js:2694 SEVERE: 2019-01-30 14:25:59.708: Disconnecting: Error decoding message: FormatException: SyntaxError: Unexpected number in JSON at position 309
FormatException: SyntaxError: Unexpected number in JSON at position 309
    at Object.p (http://127.0.0.1:40173/main.dart.js:1613:3)
    at Object.a1F (http://127.0.0.1:40173/main.dart.js:5837:9)
    at MT.pQ (http://127.0.0.1:40173/main.dart.js:6100:28)
    at MT.eG (http://127.0.0.1:40173/main.dart.js:6102:30)
    at nQ.oK (http://127.0.0.1:40173/main.dart.js:22038:11)
    at nQ.z4 (http://127.0.0.1:40173/main.dart.js:22047:8)
    at nQ.dart.u2.G4 (http://127.0.0.1:40173/main.dart.js:22067:11)
    at Object.eval (eval at tV (http://127.0.0.1:40173/main.dart.js:1745:15), <anonymous>:3:36)
    at a_l.$1 (http://127.0.0.1:40173/main.dart.js:22159:30)
    at ZS.$1 (http://127.0.0.1:40173/main.dart.js:9164:30)
main.dart.js:2694 INFO: 2019-01-30 14:25:59.716: Canceling all pending requests.
main.dart.js:2694 INFO: 2019-01-30 14:25:59.718: WebSocketVM connection error: ws://127.0.0.1:40173/ws
main.dart.js:2694 INFO: 2019-01-30 14:25:59.721: Lost an existing connection to a VM
main.dart.js:2694 SEVERE: 2019-01-30 14:25:59.776: Unable to reload object: NetworkRpcException(Canceling request: Connection saw corrupt JSON message: FormatException: SyntaxError: Unexpected number in JSON at position 309(id: 6 method: getIsolate params: {isolateId: isolates/986583284}))
main.dart.js 3162:17    Object.eH
main.dart.js 20360:25   YA.$1
main.dart.js 38134:29   UB.$0
main.dart.js 38113:9    Uw.m_
main.dart.js 38132:15   UC.$1
===== asynchronous gap ===========================
main.dart.js 4646:115   Zu.cG
main.dart.js 3199:41    Object.z0
main.dart.js 3737:17    T.mj
main.dart.js 3742:28    T.bA
main.dart.js 20214:65   nQ.cD
main.dart.js 20568:28   an.cD
===== asynchronous gap ===========================
main.dart.js 4652:123   Zu.im
main.dart.js 3152:12    Object.F
main.dart.js 20577:17   an.cb
main.dart.js 19928:6    an.dart.U.kk
main.dart.js 19928:117  an.dart.U.kk
main.dart.js 19913:22   an.aJ
===== asynchronous gap ===========================
main.dart.js 4646:115   Zu.cG
main.dart.js 3722:17    T.dL
main.dart.js 3724:30    T.a5
main.dart.js 19928:12   nQ.dart.U.kk
main.dart.js 19928:117  nQ.dart.U.kk
main.dart.js 14996:10   Yd.be

main.dart.js:2694 INFO: 2019-01-30 14:25:59.812: Eagerly loading an isolate failed: NetworkRpcException(Canceling request: Connection saw corrupt JSON message: FormatException: SyntaxError: Unexpected number in JSON at position 309(id: 6 method: getIsolate params: {isolateId: isolates/986583284}))
main.dart.js 3162:17    Object.eH
main.dart.js 20360:25   YA.$1
main.dart.js 38134:29   UB.$0
main.dart.js 38113:9    Uw.m_
main.dart.js 38132:15   UC.$1
===== asynchronous gap ===========================
main.dart.js 4646:115   Zu.cG
main.dart.js 3199:41    Object.z0
main.dart.js 3737:17    T.mj
main.dart.js 3742:28    T.bA
main.dart.js 20214:65   nQ.cD
main.dart.js 20568:28   an.cD
===== asynchronous gap ===========================
main.dart.js 4652:123   Zu.im
main.dart.js 3152:12    Object.F
main.dart.js 20577:17   an.cb
main.dart.js 19928:6    an.dart.U.kk
main.dart.js 19928:117  an.dart.U.kk
main.dart.js 19913:22   an.aJ
===== asynchronous gap ===========================
main.dart.js 4646:115   Zu.cG
main.dart.js 3722:17    T.dL
main.dart.js 3724:30    T.a5
main.dart.js 19928:12   nQ.dart.U.kk
main.dart.js 19928:117  nQ.dart.U.kk
main.dart.js 14996:10   Yd.be
```

**Comment by zoechi** [comment]
The JSON error seems to point at 
```json
{
  "jsonrpc": "2.0",
  "result": {
    "type": "Isolate",
    "fixedId": true,
    "id": "isolates\/986583284",
    "name": "main.dart:main()",
    "number": "986583284",
    "_originNumber": "986583284",
    "startTime": 1548854453645,
    "_heaps": {
      "new": {
        "type": "HeapSpace",
        "name": "new",
        "vmName": "Scavenger",
        "collections": 1,
        "avgCollectionPeriodMillis": 306018, <<<
        ...
```

**Comment by stuartmorgan** [comment]
Does this still happen for you? I haven't been able to reproduce, and we haven't had any other reports, so if it's persistent for you we'll need to try to narrow down what's unusual about your configuration.

**Comment by techpuls-damir** [comment]
Observatory is working for me on current master.

**Comment by stuartmorgan** [comment]
Glad to hear it, sounds like it was just a temporary regression then. Closing.
