### ISSUE TITLE
firebase_auth anonymous sign in fails with NPE

### ISSUE THREAD

**Issue by autolainen** [flutter/flutter#27300]
I am trying to do anonymous sign in to Firebase:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  @override
  void initState() {
    super.initState();
    _handleSignIn();
  }

  Future<FirebaseUser> _handleSignIn() async {
    final FirebaseUser user = await _auth.signInAnonymously();
    print("signed in " + user.displayName);
    return user;
  }
}
```
The exception is:
```
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInAnonymously()' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInAnonymously(FirebaseAuthPlugin.java:292)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:86)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
E/flutter (15551): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (15551): PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInAnonymously()' on a null object reference, null)
E/flutter (15551): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (15551): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #2      FirebaseAuth.signInAnonymously (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.0+1/lib/src/firebase_auth.dart:85:10)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #3      _MyHomePageState._handleSignIn (package:shopping_list_flutter/main.dart:98:43)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #4      _MyHomePageState.initState (package:shopping_list_flutter/main.dart:67:5)
E/flutter (15551): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (15551): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (15551): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #42     Element.updateChild (packag
```
Dependencies are:
```
  firebase_auth: ^0.8.0+1
  google_sign_in: ^4.0.0
```
Doctor:
```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:/Android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Android_sdk
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • SM A310F • 310084d1272f13c7 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
The log says Flutter plugins not installed but in fact they are installed.

**Comment by wouterhardeman** [comment]
Have you followed the Android integration part of the guide? https://pub.dartlang.org/packages/firebase_auth

Are Google Play services enabled on your device or emulator?

**Comment by autolainen** [comment]
Yes I've done integration steps. I'm running the app on my device and I believe Google Play services enabled on it.

It might be not clear at a glance but in fact `_auth` is not null.

**Comment by zoechi** [comment]
Did you also follow the info in https://pub.dartlang.org/packages/firebase_auth#-changelog-tab- under version `0.8.0`?

**Comment by autolainen** [comment]
The project didn't even compile unless I migrated to AndroidX.
I created this project with version 1.0 of Flutter

**Comment by asarazan** [comment]
I'm also seeing this crash but with getCurrentUser. It seems like some kind of race condition for the android SDK's FirebaseAuth to get initialized or something. It has worked in the past.

**Comment by roccadev** [comment]
Same NPE with FlutterAuth for me, when calling currentUser. I tried to delay the creation of the instance (by a few seconds) to check if there was any race condition, but it always throws.
Other Firebase services, for instance Firestore and Analytics, work just fine, so I can rule out a misconfiguration. This service seems not to be registered in the FirebaseApp.
Tried on both emulator API28 w/ Play Services and real device.

firebase_auth: ^0.8.1

I'm set up to use Androidx.

build.gradle (project):
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }

build.gradle (app):
implementation 'com.google.firebase:firebase-core:16.0.7'
implementation 'com.google.android.gms:play-services-auth:16.0.1'
// no other dependencies

[√] Flutter (Channel beta, v1.2.1, on Microsoft Windows [Versione 10.0.17134.590], locale it-IT)
    • Flutter version 1.2.1 at E:\Flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: E:\Android\android-studio-35\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at E:\Android\android-studio-33
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at E:\Android\android-studio-35
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

**Comment by alfredoqt** [comment]
A lot of people seem to have this issue and the @FlutterIssues team does not say anything. What is up with this? I have not been able to run the app on android for two weeks now.

**Comment by lukepighetti** [comment]
I'm getting Firebase auth errors. It used to be that you could do Anonymous auth without any of the Google SignIn plugins. Is that no longer the case?

**Comment by ashutoshsingh05** [comment]
I ran into the same problem a couple of days ago, found this [issue](https://github.com/flutter/flutter/issues/28057) and ran 'flutter clean'. This time it worked for my case.

**Comment by eclbetty** [comment]
Have this problem for quite some time now, found a solution that makes my project works with firebase auth, hope this helps. 

1. [Migrate your flutter project to AndroidX](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility), found out that the template code produced by Flutter SDK are not up to date even if I have the latest version installed. 

2. Go into `[project]/android/build.gradle`. Change the ext.kotlin_version to 1.3.x 

3. Register your app on Firebase's website, add the config file to your app. (Don't follow the 3rd step written on the Firebase's website. )

4. Add the classpath to the `[project]/android/build.gradle` file. (

```
buildscript {
  dependencies {
    // Add this line
    classpath 'com.google.gms:google-services:4.3.0'
  }
}
```

5. Add the apply plugin to the `[project]/android/app/build.gradle` file.

```
// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```

6. Open your flutter project with Android Studio to Sync the build.gradle file and it firebase auth should be working fine in your Flutter project now. 

> Here's the build.gradle code of my working project 

`[project]/android/app/build.gradle`
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.firebase_retest"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

apply plugin: 'com.google.gms.google-services'
```

`[project]/android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.3.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by kroikie** [comment]
@autolainen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/474. Any further collaboration will be done there.
