### ISSUE TITLE
 EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by rohitsainik** [flutter/flutter#27303]
## Logs

```
I/flutter ( 8118): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8118): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 8118): Failed assertion: boolean expression must not be null
I/flutter ( 8118): 
I/flutter ( 8118): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8118): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8118): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8118):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8118): 
I/flutter ( 8118): When the exception was thrown, this was the stack:
I/flutter ( 8118): #0      _RenderCustomClip.clipper= (package:flutter/src/rendering/proxy_box.dart:1153:20)
I/flutter ( 8118): #1      ClipPath.updateRenderObject (package:flutter/src/widgets/basic.dart:718:18)
I/flutter ( 8118): #2      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4494:12)
I/flutter ( 8118): #3      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4865:11)
I/flutter ( 8118): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #5      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter ( 8118): #6      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 8118): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter ( 8118): #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 8118): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 8118): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #27     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
I/flutter ( 8118): #28     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:978:34)
I/flutter ( 8118): #29     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter ( 8118): #30     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:989:36)
I/flutter ( 8118): #31     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:955:7)
I/flutter ( 8118): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #39     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter ( 8118): #40     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 8118): #41     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 8118): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #69     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 8118): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #81     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #85     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 8118): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #89     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #93     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #95     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
I/flutter ( 8118): #96     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 8118): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #100    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #104    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #107    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #108    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #114    StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter ( 8118): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 8118): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #120    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #124    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #127    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #128    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #132    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 8118): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #140    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 8118): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 8118): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 8118): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8118): #144    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 8118): #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 8118): #146    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 8118): #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8118): #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8118): #149    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8118): #150    _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 8118): #151    _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 8118): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter ( 8118): Another exception was thrown: A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3549 pos 14: 'owner._debugCurrentBuildTarget == this': is not true.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4131 pos 14: '_dependents.isEmpty': is not true.
I/flutter ( 8118): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
I/flutter ( 8118): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 12: '_children.contains(child)': is not true.
I/flutter ( 8118): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by aboubackr** [comment]
if (this._hasMoreItems) {
      final response =await http.get(this._next_page_url);
      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        if (data.isEmpty) {
          _refreshController.sendBack(false, RefreshStatus.noMore);
        } else {
          this._next_page_url = data["next_page_url"];
          this._current_page = data["current_page"];
          this._last_page_url = data["last_page_url"];
          this._hasMoreItems = data["current_page"] >= data["last_page"] ? false : true;
          setState(() {
            this.items+=data["data"];
          });
          _refreshController.sendBack(false, RefreshStatus.idle);
        }
      }
    }


}, {productName: MONTRE GUCCI, mtt1: 150, mtt2: 100, avatar: FIIAN31.jpg, avatar2: FIIAN32.jpg, avatar3: FIIAN33.jpg, description: MONTRE GUCCI, devise: EUR €, categorie: 1, office: 2}, {productName: MONTRE HUBLOT, mtt1: 240000000, mtt2: 94000000, avatar: FIIAN41.jpg, avatar2: FIIAN42.jpg, avatar3: FIIAN43.jpg, description: MONTRE HUBLOT AMERICAN, devise: USD $, categorie: 1, office: 2}, {productName: SAC A DOS, mtt1: 350000, mtt2: 250000, avatar: FIIAN51.jpg, avatar2: FIIAN52.jpg, avatar3: FIIAN53.jpg, description: null, devise: GNF, categorie: 5, office: 2}, {productName: LUNETTE FERA<…>
flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #144    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #152    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #153    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #154    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #155    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #156    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #157    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #158    _invoke (dart:ui/hooks.dart:154:13)
flutter: #159    _drawFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
