### ISSUE TITLE
I am having this run time error and there is no error in code

### ISSUE THREAD

**Issue by megh248** [flutter/flutter#27302]
```
C:\workspace\FlutterProject\chat_app>flutter run
Launching lib/main.dart on Redmi Note 4 in debug mode...
Initializing gradle...                                       6.1s
Resolving dependencies...                                   37.4s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                          8.4s
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter ( 4315): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4315): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#c589f):
I/flutter ( 4315): 'package:flutter/src/widgets/app.dart': Failed assertion: line 169 pos 15: 'navigatorObservers !=
I/flutter ( 4315): null': is not true.
I/flutter ( 4315):
I/flutter ( 4315): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4315): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4315): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4315):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4315):
I/flutter ( 4315): When the exception was thrown, this was the stack:
I/flutter ( 4315): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:169:15)
I/flutter ( 4315): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:410:14)
I/flutter ( 4315): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 4315): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 4315): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4315): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 4315): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 4315): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 4315): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 4315): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 4315): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 4315): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 4315): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 4315): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 4315): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 4315): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 4315): #18     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
I/flutter ( 4315): #19     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
I/flutter ( 4315): #20     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
I/flutter ( 4315): #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 4315): #22     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
I/flutter ( 4315): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
I/flutter ( 4315): #24     runApp (package:flutter/src/widgets/binding.dart:756:7)
I/flutter ( 4315): #25     main (package:chat_app/main.dart:3:16)
I/flutter ( 4315): #26     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 4315): #27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4315): (elided 2 frames from class _AssertionError)
I/flutter ( 4315): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Redmi Note 4...                      4.0s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Redmi Note 4 is available at: http://127.0.0.1:20257/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
V/BoostFramework( 4315): BoostFramework() : mPerf = com.qualcomm.qti.Performance@a981fec
Lost connection to device.
```

**Comment by zoechi** [comment]
You shouldn't pass `null` to `navigationObserver: null`

```dart
WidgetsApp(
  navigatorObservers: null,
  ...
```
Either pass a custom `NavigatorObserver` or do not pass the parameter at all, so that the default value will be used.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
