### ISSUE TITLE
PopupMenuItem not working

### ISSUE THREAD

**Issue by oreazamu** [flutter/flutter#27336]
`PopupMenuItem` doesn't seem to work correctly. When I click on `PopupMenuButton` widget, it throws below exception.

Code snippet as follows:

```dart
class Settings{
  static const String About = 'About';
  static const String Help = 'Help';
  static const List<String> choices = <String>[
    About, Help
  ];
}
```
```dart
 @override
  Widget build(BuildContext context) {
    final Color iconColor = Theme.of(context).accentColor;

    return MaterialApp(
        color: Colors.blueGrey,
        home: Scaffold(
            appBar: AppBar(
                title: Text('Bursa Imbas'),
                actions: <Widget>[
                  PopupMenuButton<String>(
                    onSelected: popUpSettings,
                    itemBuilder: (BuildContext context) {
                      Settings.choices.map((String choice){
                        PopupMenuItem<String>(
                          value: choice,
                          child: Text(choice),
                        );
                      }).toList();
                    }

```

```
> I/flutter (17527): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
> I/flutter (17527): The following assertion was thrown while handling a gesture:
> I/flutter (17527): 'package:flutter/src/material/popup_menu.dart': Failed assertion: line 723 pos 10: 'items != null &&
> I/flutter (17527): items.isNotEmpty': is not true.
> I/flutter (17527): 
> I/flutter (17527): Either the assertion indicates an error in the framework itself, or we should provide substantially
> I/flutter (17527): more information in this error message to help you determine and fix the underlying cause.
> I/flutter (17527): In either case, please report this assertion by filing a bug on GitHub:
> I/flutter (17527):   https://github.com/flutter/flutter/issues/new?template=BUG.md
> I/flutter (17527): 
> I/flutter (17527): When the exception was thrown, this was the stack:
> I/flutter (17527): #2      showMenu (package:flutter/src/material/popup_menu.dart:723:10)
> I/flutter (17527): #3      _PopupMenuButtonState.showButtonMenu (package:flutter/src/material/popup_menu.dart:898:5)
> I/flutter (17527): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
> I/flutter (17527): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
> I/flutter (17527): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
> I/flutter (17527): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
> I/flutter (17527): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
> I/flutter (17527): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
> I/flutter (17527): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
> I/flutter (17527): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
> I/flutter (17527): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
> I/flutter (17527): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
> I/flutter (17527): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
> I/flutter (17527): #15     _invoke1 (dart:ui/hooks.dart:168:13)
> I/flutter (17527): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
> I/flutter (17527): (elided 2 frames from class _AssertionError)
> I/flutter (17527): 
> I/flutter (17527): Handler: onTap
> I/flutter (17527): Recognizer:
> I/flutter (17527):   TapGestureRecognizer#4592b(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
> I/flutter (17527):   Offset(388.2, 59.4), sent tap down)
> I/flutter (17527): ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_GB.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by zoechi** [comment]
To investigate we would need a minimal **runnable** reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by apaatsio** [comment]
@oreazamu Your itemBuilder function does not return anything. It's missing the `return` keyword.
