### ISSUE TITLE
Intermittent ''_dependants.isEmpty' is not true" exception

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2733]
I've been seeing this exception, but only intermittently. Not sure what the root problem is as the stack doesn't contain anything directly related to what I'm working on.

Note also: I think in American English we just use 'dependent'.

```
--------- beginning of main
--------- beginning of system
I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
I/flutter : Exception caught while building Overlay-[GlobalKey 699493554]
I/flutter : 'packages/flutter/src/widgets/framework.dart': Failed assertion: line 1543: '_dependants.isEmpty' is not true.
I/flutter : Stack trace:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      InheritedElement.debugDeactivated.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1543)
I/flutter : #2      InheritedElement.debugDeactivated (packages/flutter/src/widgets/framework.dart:1542)
I/flutter : #3      _InactiveElements._deactivate.<anonymous closure> (packages/flutter/src/widgets/framework.dart:610)
I/flutter : #4      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:610)
I/flutter : #5      ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #6      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #7      ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #8      _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #9      SingleChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1875)
I/flutter : #10     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #11     SingleChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1875)
I/flutter : #12     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #13     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #14     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #15     SingleChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1875)
I/flutter : #16     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #17     SingleChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1875)
I/flutter : #18     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #19     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #20     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #21     SingleChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1875)
I/flutter : #22     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #23     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #24     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #25     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #26     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #27     ComponentElement.visitChildren (packages/flutter/src/widgets/framework.dart:1318)
I/flutter : #28     _InactiveElements._deactivate (packages/flutter/src/widgets/framework.dart:609)
I/flutter : #29     _InactiveElements.add (packages/flutter/src/widgets/framework.dart:618)
I/flutter : #30     Element._deactivateChild (packages/flutter/src/widgets/framework.dart:893)
I/flutter : #31     RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1779)
I/flutter : #32     MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:2006)
I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:743)
I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1306)
I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1224)
I/flutter : #36     WidgetFlutterBinding.buildDirtyElements.<anonymous closure> (packages/flutter/src/widgets/binding.dart:137)
I/flutter : #37     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:1139)
I/flutter : #38     WidgetFlutterBinding.buildDirtyElements (packages/flutter/src/widgets/binding.dart:132)
I/flutter : #39     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:95)
I/flutter : #40     BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:78)
I/flutter : #41     BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:278)
I/flutter : #42     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:255)
I/flutter : #43     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
I/flutter : ------------------------------------------------------------------------
```

**Comment by abarth** [comment]
There's a bug with how we handle inherited widgets and tree mutations.  This is probably another symptom.

**Comment by abarth** [comment]
Spelling fix in https://github.com/flutter/flutter/pull/2746
