### ISSUE TITLE
More than two lines of error while using the Text control!

### ISSUE THREAD

**Issue by zhongqiang1995** [flutter/flutter#27348]
```dart
 var textStyle = TextStyle(

              fontSize: size,
              fontWeight: FontWeight.bold,
              color: Color(0xff333333));

          var child = Text(
            title,
            style: textStyle,
            overflow: TextOverflow.ellipsis,
 );
```

More than two lines of error while using the Text control!

## Logs
```
I/OpenGLRenderer(13420): Davey! duration=1214ms; Flags=1, IntendedVsync=38062143811153, Vsync=38063260477775, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=38063276178713, AnimationStart=38063276261713, PerformTraversalsStart=38063276769713, DrawStart=38063287791713, SyncQueued=38063293576713, SyncStart=38063298750713, IssueDrawCommandsStart=38063302392713, SwapBuffers=38063339752713, FrameCompleted=38063363725713, DequeueBufferDuration=14297000, QueueBufferDuration=772000, 
I/flutter (13420): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13420): The following assertion was thrown building Container:
I/flutter (13420): 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 100 pos 15:
I/flutter (13420): 'padding.isNonNegative': is not true.
I/flutter (13420): 
I/flutter (13420): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13420): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13420): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13420):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13420): 
I/flutter (13420): When the exception was thrown, this was the stack:
I/flutter (13420): #2      new RenderPadding (package:flutter/src/rendering/shifted_box.dart:100:15)
I/flutter (13420): #3      Padding.createRenderObject (package:flutter/src/widgets/basic.dart:1453:12)
I/flutter (13420): #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4482:28)
I/flutter (13420): #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4859:11)
I/flutter (13420): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (13420): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (13420): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (13420): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (13420): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (13420): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (13420): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (13420): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (13420): #14     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:118:18)
I/flutter (13420): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (13420): #16     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:107:11)
I/flutter (13420): #17     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter (13420): #18     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter (13420): #19     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter (13420): #20     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:205:5)
I/flutter (13420): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #24     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (13420): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (13420): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #35     RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:142:12)
I/flutter (13420): #36     RenderSliverPinnedPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:294:5)
I/flutter (13420): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #38     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (13420): #39     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (13420): #40     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (13420): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #62     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:199:18)
I/flutter (13420): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #64     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (13420): #65     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (13420): #66     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (13420): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #84     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (13420): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #86     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (13420): #87     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (13420): #88     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (13420): #89     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (13420): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #94     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (13420): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #98     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #100    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #102    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #104    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #108    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #110    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #111    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
I/flutter (13420): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #113    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
D/        (13420): HostConnection::get() New Host Connection established 0x75a44cca7540, tid 13441
D/EGL_emulation(13420): eglMakeCurrent: 0x75a44e6fa740: ver 3 0 (tinfo 0x75a4561a1ce0)
I/flutter (13420): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #115    __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #117    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #119    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #121    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #123    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #124    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #125    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (13420): #126    RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13420): #127    RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
I/flutter (13420): #128    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (13420): #129    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (13420): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (13420): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (13420): #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (13420): #133    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13420): #134    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13420): #135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (13420): #137    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (13420): #138    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (13420): #139    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (13420): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (13420): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
I can not reproduce 
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    var title = 'foo';
    var size = 18.0;
    var textStyle = TextStyle(
        fontSize: size, fontWeight: FontWeight.bold, color: Color(0xff333333));

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            Text(
              title,
              style: textStyle,
              overflow: TextOverflow.ellipsis,
            ),
          ],
        ),
      ),
    );
  }
}
```
```
[✓] Flutter (Channel master, v1.1.10-pre.205, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
