### ISSUE TITLE
Flutter firebase dynamic links cannot install application

### ISSUE THREAD

**Issue by agnoam** [flutter/flutter#27360]
## Steps to Reproduce

I have install the firebase_dynamic_links: ^0.2.0 successfuly. and I didn't add any new code to my app,
but when I install again my app, this plugin crushed the build of the app with this exception:

```
flutter\.pub-cache\hosted\pub.dartlang.org\firebase_dynamic_links-0.2.0\android\src\main\java\io\flutter\plugins\firebasedynamiclinks\FirebaseDynamicLinksPlugin.java:93: error: cannot find symbol
      public void onComplete(@NonNull Task<ShortDynamicLink> task) {
```

My Flutter doctor response: 

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale he-IL)
    • Flutter version 1.0.0 at \Downloads\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at \AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = \AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.30.2)
    • VS Code at \AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Mi A1 • ****PhoneID**** • android-arm64 • Android 9 (API 28)
```

**Comment by zoechi** [comment]
I guess you used `0.1.1` previously and updated to `0.2.0` which came out 2 days ago.

Please check https://pub.dartlang.org/packages/firebase_dynamic_links#-changelog-tab-

**Comment by zoechi** [comment]
Either switch back to `0.1.0` or migrate to AndroidX

**Comment by agnoam** [comment]
There is another exception now:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

**Comment by zoechi** [comment]
Is this for debug or release build?

**Comment by zoechi** [comment]
Probably https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by agnoam** [comment]
Your solution didn't work: 

```
Dex: The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$8.updateIndex(DexMerger.java:565)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:276)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:574)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:166)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by agnoam** [comment]
> Is this for debug or release build?

debug

**Comment by zoechi** [comment]
Try https://stackoverflow.com/questions/49886597/multidex-issue-with-flutter

**Comment by agnoam** [comment]
Thanks a lot. the solution was just to enable the multidex in the gradle.
