### ISSUE TITLE
Flutter App does not run "gradlew exited abnormally"

### ISSUE THREAD

**Issue by hetkpatel** [flutter/flutter#27447]
## Steps to Reproduce

1. Created a new Flutter App `flutter create flutter_app`
2. Ran the default Flutter project to test if it works on my physical device `flutter run`

## Logs

`flutter run --verbose`:

```
[  +32 ms] executing: [/Users/hetpatel/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/hetpatel/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/hetpatel/Documents/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/hetpatel/Documents/flutter/] git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/hetpatel/Documents/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 weeks ago
[   +1 ms] executing: [/Users/hetpatel/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +489 ms] executing: /Volumes/HPBD2017/AndroidSDK/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Volumes/HPBD2017/AndroidSDK/platform-tools/adb devices -l
[        ] List of devices attached
           fc204956               device usb:336592896X product:heroqltetmo model:SM_G930T device:heroqltetmo transport_id:2
[  +10 ms] executing: idevice_id -h
[  +56 ms] /usr/bin/xcrun simctl list --json devices
[ +527 ms] /Volumes/HPBD2017/AndroidSDK/platform-tools/adb -s fc204956 shell getprop
[  +99 ms] ro.hardware = qcom
[+1005 ms] Launching lib/main.dart on SM G930T in debug mode...
[  +27 ms] Initializing gradle...
[   +6 ms] Using gradle from /Volumes/HPBD2017/FlutterProjects/veggie_diet/android/gradlew.
[   +8 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +79 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.3
[ +102 ms] executing: /Volumes/HPBD2017/FlutterProjects/veggie_diet/android/gradlew -v
[ +889 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.14.2 x86_64
[   +1 ms] Initializing gradle... (completed)
[   +1 ms] Resolving dependencies...
[        ] executing: [/Volumes/HPBD2017/FlutterProjects/veggie_diet/android/] /Volumes/HPBD2017/FlutterProjects/veggie_diet/android/gradlew app:properties
[+62065 ms] 
                     FAILURE: Build failed with an exception.

                     * What went wrong:
                     Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
                     > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

                     * Try:
                     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                     * Get more help at https://help.gradle.org

                     BUILD FAILED in 1m 1s
[   +8 ms] Resolving dependencies... (completed)
[   +2 ms] * Error running Gradle:
           ProcessException: Process "/Volumes/HPBD2017/FlutterProjects/veggie_diet/android/gradlew" exited abnormally:
           
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
           > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 1m 1s
             Command: /Volumes/HPBD2017/FlutterProjects/veggie_diet/android/gradlew app:properties
           
[  +18 ms] "flutter run" took 65,328ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:111:11)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:51:10)
#40     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#41     main (file:///b/build/slave/Mac_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

`flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/hetpatel/Documents/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Volumes/HPBD2017/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • SM G930T • fc204956 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by kangwang1988** [comment]
@hetkpatel 
> * What went wrong:
           Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
           > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

It seems to be a pure gradle issue instead of flutter one.
You can reproduce it by:
```
cd /Volumes/HPBD2017/FlutterProjects/veggie_diet/android
./gradlew app:properties
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by apaatsio** [comment]
I have the same problem on Linux. I got around it by running flutter with sudo:

`sudo flutter run`

I haven't figured out the root cause yet.
