### ISSUE TITLE
TabBarView Dont Working with StreamBuilder (RxDart)(BUG)

### ISSUE THREAD

**Issue by breitembach** [flutter/flutter#27445]
this problem only happens when I call `StreamBuilder`, but with `FutureBuilder` it works normally.
`_tabBarViewSheduleBuilder` and `_buildTabViewFinishedBuilder` both return `StreamBuilder`.
and when I click on the second `tabView` and I go back to the first I get a 

```
Bad State Stream error has already been listened to.
```
even with different bloc instances.

**Here are the Code.**
```dart
return DefaultTabController(
      length: 2,
      child: Scaffold(
        drawer: CustomDrawer(PageControllerGlobal.instance.pageController),
        appBar: AppBar(
          actions: <Widget>[
            new IconButton(
              icon: actionIcon,
              onPressed: () {
                setState(() {
                  if (this.actionIcon.icon == Icons.search) {
                    this.actionIcon = Icon(
                      Icons.close,
                      color: Colors.white,
                    );
                    this.appBarTitle = TextFormField(
                      controller: _searchQuery,
                      style: TextStyle(
                        color: Colors.white, decoration: TextDecoration.none
                      ),
                      decoration: InputDecoration(
                        enabledBorder: const UnderlineInputBorder(
                          // width: 0.0 produces a thin "hairline" border
                          borderSide:
                              const BorderSide(color: Colors.white, width: 1),
                        ),
                        focusedBorder: UnderlineInputBorder(
                            borderSide: BorderSide(color: Colors.white)),
                        suffixIcon: Icon(Icons.search, color: Colors.white),
                        hintText: "Buscar...",
                        hintStyle: TextStyle(color: Colors.white)
                      ),
                    );
                    _handleSearchStart();
                  } else {
                    _handleSearchEnd();
                  }
                });
              },
            ),
             PopupMenuButton<OrderOptions>(
              itemBuilder: (context) => <PopupMenuEntry<OrderOptions>>[
                const PopupMenuItem<OrderOptions>(
                  child: Text("Ordenar por Data"),
                  value: OrderOptions.orderaz,
                ),
                const PopupMenuItem<OrderOptions>(
                  child: Text("Ordenar por status"),
                  value: OrderOptions.orderza,
                ),
              ],
              // onSelected: _orderList,
            )
          ],
          bottom: TabBar(
            tabs: [
              Tab(icon: Icon(Icons.av_timer), text: "Agendados"), //@TODO
              Tab(icon: Icon(Icons.check_circle), text: "Realizados"),
            ],
          ),
          title: appBarTitle,
        ),
        body: TabBarView(
          children: [
          // ListView(
          //     children: _IsSearching ? _buildSearchList() : _buildList(),
          // ),
          // ListView(
          //   children: _IsSearching ? _buildSearchList() : _buildList(),
          // ),
          _tabBarViewSheduleBuilder(context),
          _buildTabViewFinishedBuilder(context),
        ]),
      ),
    );
```

**ERROR**

```
I/flutter (14352): #43     RenderObject.invokeLayoutCallback 
package:flutter/…/rendering/object.dart:1730
I/flutter (14352): #44     RenderSliverMultiBoxAdaptor._createOrObtainChild 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:263
I/flutter (14352): #45     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:378
I/flutter (14352): #46     RenderSliverFixedExtentBoxAdaptor.performLayout 
package:flutter/…/rendering/sliver_fixed_extent_list.dart:184
I/flutter (14352): #47     RenderObject.layout 
package:flutter/…/rendering/object.dart:1634
I/flutter (14352): #48     RenderViewportBase.layoutChildSequence 
package:flutter/…/rendering/viewport.dart:405
I/flutter (14352): #49     RenderViewport._attemptLayout 
package:flutter/…/rendering/viewport.dart:1316
I/flutter (14352): #50     RenderViewport.performLayout 
package:flutter/…/rendering/viewport.dart:1234
I/flutter (14352): #51     RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1509
I/flutter (14352): #52     PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:768
I/flutter (14352): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:281
I/flutter (14352): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:686
I/flutter (14352): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:219
I/flutter (14352): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:990
I/flutter (14352): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:930
I/flutter (14352): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:842
I/flutter (14352): #59     _invoke (dart:ui/hooks.dart:159:13)
I/flutter (14352): #60     _drawFrame (dart:ui/hooks.dart:148:3)
I/flutter (14352): (elided 3 frames from package dart:async)
I/flutter (14352): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (14352): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter (14352): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter (14352): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2270 pos 20: '_debugCurrentBuildTarget == context': is not true.
I/flutter (14352): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (14352): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 580 pos 16: 'indexOf(child) == index': is not true.
I/chatty  (14352): uid=10219(com.example.bfmobile) Thread-9 identical 4 lines
I/flutter (14352): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 580 pos 16: 'indexOf(child) == index': is not true.
```

**Comment by hjJunior** [comment]
Could u please provide an complete example, I can't be sure what is happens on `_tabBarViewSheduleBuilder` and `_buildTabViewFinishedBuilder` or maybe provide minimalist example that happens the same problem

**Comment by breitembach** [comment]
Both
```
return StreamBuilder(
      stream: bloc.freightListAccepted,
      builder: (context, AsyncSnapshot<FreightsList> snapshot) {
        if (snapshot.hasError) return new Text('Error: ${snapshot.error}');
        if (!snapshot.hasData) return Center(child: CircularProgressIndicator());
        if (snapshot.data.freights.length == 0) return Center(child: Text(""));

        List<ScheduleFreight> freights = snapshot.data.freights;
        return ListView.builder(
          padding: EdgeInsets.only(top: 10),
          itemCount: freights.length,
          itemBuilder: (BuildContext context, int index) {
            print(index);
            return Card(
              child: ListTile(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      fullscreenDialog: true,
                      builder: (context) => Scaffold(
                        appBar: AppBar(
                          title: Text("Detalhes do Agendamento"),
                        ),
                        body: DetailScheduleFreightScreen(
                          freight: freights[index],
                        ),
                      )
                    )
                  );
                },
                contentPadding: EdgeInsets.all(10),
                dense: false,
                subtitle: Padding(
                  padding: EdgeInsets.all(8),
                  child: Text(freights[index].user.fullName),
                ),
                trailing: Icon(Icons.keyboard_arrow_right,
                    color: Theme.of(context).primaryColor),
                title: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Expanded(
                      child: Column(
                        children: <Widget>[
                          Row(
                            children: <Widget>[
                              Icon(Icons.date_range, color: Colors.grey[700],),
                              Text("Data: ${freights[index].date}")
                            ],
                          ),
                          Padding(padding: EdgeInsets.only(top: 5)),
                          Row(
                            children: <Widget>[
                              Icon(Icons.schedule, color: Colors.grey[700],),
                              SizedBox(
                                width: 5,
                              ),
                              Text("Hora: ${freights[index].time}")
                            ],
                          ),
                        ],
                      ), 
                    ),
                    Container(
                      padding: EdgeInsets.only(top: 35),
                      child: Row(
                        children: <Widget>[
                          SizedBox(
                            width: 20,
                            height: 20,
                            child: Icon(
                                FontAwesomeIcons.check,
                                color: Theme.of(context).accentColor,
                              ),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 10),
                          ),
                          Text(freights[index].statusFreight, style: TextStyle(fontSize: 14)),
                        ],
                      )
                    )
                  ]
                ),
              ),
            );
          }, //itemBuilder
        );
      },
    );
```

**Comment by hjJunior** [comment]
I'm not pretty but I think u log is incomplete, it's starting from `I/flutter (14352): #43     RenderObject.invokeLayoutCallbac` generrally start with `#1 ...`
I'm not expert, can u could provide this complete info, maybe use past raw I could try to help u

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
