### ISSUE TITLE
Unwanted Info logs on volume button press

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#27454]
## Steps to Reproduce

Press any volume button after running the app

## Logs

```
I/SessionManager(17660): dispatchVolumeKeyEvent:com.infitio.adharasocketioexample true KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=62625140, downTime=62625140, deviceId=7, source=0x101 } -2147483648 false java.lang.Throwable
I/SessionManager(17660): 	at android.media.session.MediaSessionManager.dispatchVolumeKeyEventInternal(MediaSessionManager.java:365)
I/SessionManager(17660): 	at android.media.session.MediaSessionManager.dispatchVolumeKeyEventAsSystemService(MediaSessionManager.java:358)
I/SessionManager(17660): 	at com.android.internal.policy.PhoneWindow.onKeyDown(PhoneWindow.java:1899)
I/SessionManager(17660): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:350)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5319)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5187)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4830)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4698)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4887)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4698)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4863)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5024)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
I/SessionManager(17660): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
I/SessionManager(17660): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/SessionManager(17660): 	at android.os.MessageQueue.next(MessageQueue.java:326)
I/SessionManager(17660): 	at android.os.Looper.loop(Looper.java:160)
I/SessionManager(17660): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
I/SessionManager(17660): 	at java.lang.reflect.Method.invoke(Native Method)
I/SessionManager(17660): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
I/SessionManager(17660): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/SessionManager(17660): dispatchVolumeKeyEvent:com.infitio.adharasocketioexample true KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=62625301, downTime=62625140, deviceId=7, source=0x101 } -2147483648 false java.lang.Throwable
I/SessionManager(17660): 	at android.media.session.MediaSessionManager.dispatchVolumeKeyEventInternal(MediaSessionManager.java:365)
I/SessionManager(17660): 	at android.media.session.MediaSessionManager.dispatchVolumeKeyEventAsSystemService(MediaSessionManager.java:358)
I/SessionManager(17660): 	at com.android.internal.policy.PhoneWindow.onKeyUp(PhoneWindow.java:2000)
I/SessionManager(17660): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:351)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5319)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5187)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4830)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4698)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4887)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4698)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4671)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4724)
I/SessionManager(17660): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4690)
I/SessionManager(17660): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4863)
I/SessionManager(17660): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5024)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
I/SessionManager(17660): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
I/SessionManager(17660): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
I/SessionManager(17660): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/SessionManager(17660): 	at android.os.MessageQueue.next(MessageQueue.java:326)
I/SessionManager(17660): 	at android.os.Looper.loop(Looper.java:160)
I/SessionManager(17660): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
I/SessionManager(17660): 	at java.lang.reflect.Method.invoke(Native Method)
I/SessionManager(17660): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
I/SessionManager(17660): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
GrackN-33c0:adhara_socket_io rohit$ flutter analyze
Analyzing adhara_socket_io...                                    
No issues found! (ran in 7.9s)

```

```
GrackN-33c0:adhara_socket_io rohit$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale
    en-IN)
    • Flutter version 1.0.0 at /Users/rohit/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26
      -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rohit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rohit/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 10.90.175.37:5555 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Can you please publish a minimal reproduction project to GitHub?
