### ISSUE TITLE
Relevant Android log messages missing from "flutter logs"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27458]
Here are some errors that I would like to have known about but that weren't included with our current filters:

```
02-02 22:45:28.817  1148  5562 I ActivityManager: Force stopping com.raccoonfink.cruisemonkey appid=10181 user=0: from pid 14822
```

```
02-02 22:45:31.290 12597 12623 W PackageParser: Ignoring duplicate uses-permissions/uses-permissions-sdk-m: android.permission.READ_EXTERNAL_STORAGE in package: com.raccoonfink.cruisemonkey at: Binary XML file line #17
```

```
02-02 22:29:52.187  1148  1537 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.raccoonfink.cruisemonkey/.MainActivity bnds=[316,2452][585,2852]} from uid 10040
02-02 22:29:52.220  1148  1185 I ActivityManager: Start proc 13984:com.raccoonfink.cruisemonkey/u0a181 for activity com.raccoonfink.cruisemonkey/.MainActivity
02-02 22:29:52.402 13984 13984 E AndroidRuntime: FATAL EXCEPTION: main
02-02 22:29:52.402 13984 13984 E AndroidRuntime: Process: com.raccoonfink.cruisemonkey, PID: 13984
02-02 22:29:52.402 13984 13984 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raccoonfink.cruisemonkey/com.raccoonfink.cruisemonkey.MainActivity}: android.content.res.Resources$NotFoundException: Drawable com.raccoonfink.cruisemonk\
ey:drawable/launch_background with resource ID #0x7f050002
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 22:29:52.402 13984 13984 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.raccoonfink.cruisemonkey:drawable/launch_background with resource ID #0x7f050002
02-02 22:29:52.402 13984 13984 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f050002
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.res.Resources.getDrawable(Resources.java:827)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.Context.getDrawable(Context.java:635)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2622)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2672)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2071)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:151)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:85)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.raccoonfink.cruisemonkey.MainActivity.onCreate(MainActivity.kt:10)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7144)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7135)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-02 22:29:52.402 13984 13984 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: <bitmap> requires a valid 'src' attribute
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:849)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:770)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1321)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:279)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
02-02 22:29:52.402 13984 13984 E AndroidRuntime:        ... 25 more
02-02 22:29:52.407  1148  3050 W ActivityManager:   Force finishing activity com.raccoonfink.cruisemonkey/.MainActivity
```

**Comment by jonahwilliams** [comment]
Currently we don't use any information from the `ApplicationPackage` when creating the log reader for Android devices.  If we included the id `com.raccoonfink.cruisemonkey` for example, we could also grab the first, second, and part of the third lines.

Grabbing the entire stack for three might be a bit tricky. When we see something that looks like a stack trace, we could cache it unconditionally. Then check if it contains a reference to our app id in it, or toss it otherwise.

On the other hand, some of this functionality is bound to already be implemented in adb itself, so I'll start there before I create something too hacky.

**Comment by jonahwilliams** [comment]
I think this was fixed by https://github.com/flutter/flutter/commit/7f400af35a0716efc86f5b9401dcbedc501c2ed7
