### ISSUE TITLE
Can't combine StaggeredGridView with CustomScrollView

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#27469]
I wannat build serverl slivers widget inside CustomScrollView, here is what I do now:

```dart
Widget _buildListView() {
    if (isDataLoaded)
      return Container(
        color: Colors.black,
        child: StaggeredGridView.countBuilder(
          padding: EdgeInsets.all(4.0),
          crossAxisCount: 4,
          itemCount: data.length,
          itemBuilder: (context, i) {
            String imgPath = data[i]['largeImageURL'];
            return Material(
              clipBehavior: Clip.antiAlias,
              borderRadius: BorderRadius.circular(10.0),
              child: InkWell(
                child: Hero(
                    tag: imgPath,
                    child: FadeInImage(
                        fit: BoxFit.cover,
                        placeholder:
                            AssetImage('assets/images/default_pic.png'),
                        image: NetworkImage(imgPath))),
                onTap: () {
                  Navigator.of(context).push(MaterialPageRoute(
                      builder: (context) => ImagePreviewPage2(
                          tag: imgPath,
                          image: new Image.network(imgPath),
                          url: imgPath)));
                },
              ),
            );
          },
          staggeredTileBuilder: (i) => StaggeredTile.count(2, i.isEven ? 2 : 3),
          mainAxisSpacing: 8.0,
          crossAxisSpacing: 8.0,
        ),
      );
    else
      return Container(
        child: Center(
            child: CircularProgressIndicator(
                valueColor:
                    new AlwaysStoppedAnimation<Color>(Colors.yellowAccent))),
        color: Colors.black,
      );
  }

@override
  Widget build(BuildContext context) {
    return new CupertinoPageScaffold(
        backgroundColor: Colors.black,
        child: CustomScrollView(slivers: <Widget>[
          CupertinoSliverNavigationBar(
            backgroundColor: Colors.white,
            border: Border(),
            largeTitle: Text("美图"),
          ),
           SliverToBoxAdapter(
            child: _buildListView(),
          ),
        
        ]));
  }
```

Simply, I need a StaggeredGridView to show pictures, however, it goes to this error:

```
 ⣯flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performResize():
flutter: Vertical viewport was given unbounded height.
flutter: Viewports expand in the scrolling direction to fill their container.In this case, a vertical
flutter: viewport was given an unlimited amount of vertical space in which to expand. This situation
flutter: typically happens when a scrollable widget is nested inside another scrollable widget.
flutter: If this widget is always nested in a scrollable widget there is no need to use a viewport because
flutter: there will always be enough vertical space for the children. In this case, consider using a Column
flutter: instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
flutter: the height of the viewport to the sum of the heights of its children.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1129:15)
flutter: #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1182:6)
flutter: #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
flutter: #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)

```

So after I google a lot, seems no way make StaggeredGridView inside CustomScrollView. What should I do in this situation?

**Comment by dcov** [comment]
The problem is that you're nesting `Viewport`s. The parent `Viewport` is created by `CustomScrollView`, and the child `Viewport` is created by `StaggeredGridView` and it's the one that throws the unbounded height exception. 

You need to extract the `StaggeredGridView` into a `SliverStaggeredGrid` that creates a `RenderSliver` instead of a `RenderViewport`.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
